OPAL (Object Oriented Parallel Accelerator Library): RangeSelector Class Reference
RangeSelector Class Reference
#include <RangeSelector.h>
Public Member Functions
RangeSelector (const Beamline &, const RangeRep &range)
Constructor.
virtual ~RangeSelector ()
virtual void execute ()
Execute the algorithm.
virtual void visitFlaggedElmPtr (const FlaggedElmPtr &)
Apply the visitor to an FlaggedElmPtr.
Public Member Functions inherited from DefaultVisitor
DefaultVisitor (const Beamline &beamline, bool backBeam, bool backTrack)
Constructor.
virtual ~DefaultVisitor ()=0
virtual void visitBeamline (const Beamline &)
Apply the algorithm to a beam line.
virtual void visitCCollimator (const CCollimator &)
Apply the algorithm to a collimator.
virtual void visitComponent (const Component &)
Apply the algorithm to an arbitrary component.
virtual void visitCorrector (const Corrector &)
Apply the algorithm to a closed orbit corrector.
virtual void visitCyclotron (const Cyclotron &)
Apply the algorithm to an cyclotron.
virtual void visitDegrader (const Degrader &)
Apply the algorithm to a degrader.
virtual void visitDrift (const Drift &)
Apply the algorithm to a drift space.
virtual void visitFlexibleCollimator (const FlexibleCollimator &)
Apply the algorithm to a flexible collimator.
virtual void visitMarker (const Marker &)
Apply the algorithm to a marker.
virtual void visitMonitor (const Monitor &)
Apply the algorithm to a beam position monitor.
virtual void visitMultipole (const Multipole &)
Apply the algorithm to a multipole.
virtual void visitMultipoleT (const MultipoleT &)
Apply the algorithm to to an arbitrary multipole.
virtual void visitMultipoleTStraight (const MultipoleTStraight &)
Apply the algorithm to an arbitrary straight multipole.
virtual void visitMultipoleTCurvedConstRadius (const MultipoleTCurvedConstRadius &)
Apply the algorithm to an arbitrary curved multipole of constant radius.
virtual void visitMultipoleTCurvedVarRadius (const MultipoleTCurvedVarRadius &)
Apply the algorithm to an arbitrary curved multipole of variable radius.
virtual void visitOffset (const Offset &)
Apply the algorithm to an offset (placement).
virtual void visitOutputPlane (const OutputPlane &)
Apply the algorithm to an output plane.
virtual void visitProbe (const Probe &prob)
Apply the algorithm to a probe.
virtual void visitRBend (const RBend &)
Apply the algorithm to a rectangular bend.
virtual void visitRBend3D (const RBend3D &)
Apply the algorithm to a rectangular bend.
virtual void visitRFCavity (const RFCavity &)
Apply the algorithm to a RF cavity.
virtual void visitRing (const Ring &)
Apply the algorithm to a ring.
virtual void visitSBend (const SBend &)
Apply the algorithm to a sector bend.
virtual void visitSBend3D (const SBend3D &)
Apply the algorithm to a sector bend with 3D field map.
virtual void visitScalingFFAMagnet (const ScalingFFAMagnet &)
Apply the algorithm to a scaling FFA magnet.
virtual void visitSeptum (const Septum &)
Apply the algorithm to a septum.
virtual void visitSolenoid (const Solenoid &)
Apply the algorithm to a solenoid.
virtual void visitSource (const Source &)
Apply the algorithm to a source.
virtual void visitStripper (const Stripper &)
Apply the algorithm to a particle stripper.
virtual void visitTravelingWave (const TravelingWave &)
Apply the algorithm to a traveling wave.
virtual void visitVacuum (const Vacuum &)
Apply the algorithm to a vacuum space.
virtual void visitVariableRFCavity (const VariableRFCavity &vcav)
Apply the algorithm to a a variable RF cavity.
virtual void visitVariableRFCavityFringeField (const VariableRFCavityFringeField &vcav)
Apply the algorithm to a a variable RF cavity with Fringe Field.
virtual void visitVerticalFFAMagnet (const VerticalFFAMagnet &)
Apply the algorithm to a vertical FFA magnet.
Public Member Functions inherited from BeamlineVisitor
BeamlineVisitor ()
virtual ~BeamlineVisitor ()
Protected Member Functions
virtual void handleBeamline (const FlaggedElmPtr &)
The operation to be done for beamlines.
virtual void handleElement (const FlaggedElmPtr &)
The operation to be done for elements.
Protected Attributes
RangeRep itsRange
Working data for range.
Protected Attributes inherited from DefaultVisitor
const Beamline & itsLine
bool back_beam
bool back_track
bool back_path
double flip_B
double flip_s
Private Member Functions
RangeSelector ()
RangeSelector (const RangeSelector &)
void operator= (const RangeSelector &)
Detailed Description
Definition at line 29 of file RangeSelector.h.
Constructor & Destructor Documentation
RangeSelector() [1/3]
RangeSelector::RangeSelector (const Beamline & beamline, const RangeRep & range)
Constructor.
Definition at line 31 of file RangeSelector.cpp.
~RangeSelector()
RangeSelector::~RangeSelector () virtual
Definition at line 36 of file RangeSelector.cpp.
RangeSelector() [2/3]
RangeSelector::RangeSelector () private
RangeSelector() [3/3]
RangeSelector::RangeSelector (const RangeSelector &) private
Member Function Documentation
execute()
void RangeSelector::execute () virtual
Execute the algorithm.
Reimplemented from DefaultVisitor.
Reimplemented in Selector.
Definition at line 40 of file RangeSelector.cpp.
References DefaultVisitor::execute(), RangeRep::initialize(), and itsRange.
Referenced by Selector::execute().
handleBeamline()
void RangeSelector::handleBeamline (const FlaggedElmPtr & fep) protected virtual
The operation to be done for beamlines.
Definition at line 64 of file RangeSelector.cpp.
References DefaultVisitor::visitFlaggedElmPtr().
Referenced by visitFlaggedElmPtr().
handleElement()
void RangeSelector::handleElement (const FlaggedElmPtr & fep) protected virtual
The operation to be done for elements.
Reimplemented in Selector.
Definition at line 69 of file RangeSelector.cpp.
References RangeRep::isActive(), itsRange, and DefaultVisitor::visitFlaggedElmPtr().
Referenced by visitFlaggedElmPtr().
operator=()
void RangeSelector::operator= (const RangeSelector &) private
visitFlaggedElmPtr()
void RangeSelector::visitFlaggedElmPtr (const FlaggedElmPtr & fep) virtual
Apply the visitor to an FlaggedElmPtr.
Reimplemented from DefaultVisitor.
Definition at line 46 of file RangeSelector.cpp.
References RangeRep::enter(), ElmPtr::getElement(), handleBeamline(), handleElement(), itsRange, and RangeRep::leave().
Member Data Documentation
itsRange
RangeRep RangeSelector::itsRange protected
Working data for range.
Definition at line 55 of file RangeSelector.h.
Referenced by execute(), Selector::handleElement(), handleElement(), and visitFlaggedElmPtr().
The documentation for this class was generated from the following files:
src/Tables/RangeSelector.h
src/Tables/RangeSelector.cpp