OPAL (Object Oriented Parallel Accelerator Library): mslang::Polygon Struct Reference
mslang::Polygon Struct Reference
#include <Polygon.h>
Public Member Functions
void triangulize (std::vector< Vector_t > &nodes)
virtual void print (int ident)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Public Member Functions inherited from mslang::Function
virtual ~Function ()
virtual void apply (std::vector< std::shared_ptr< Base >> &bfuncs)=0
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
Static Public Member Functions inherited from mslang::Function
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
std::vector< Triangle > triangles_m
Additional Inherited Members
Static Public Attributes inherited from mslang::Function
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\((.*)"
Detailed Description
Definition at line 8 of file Polygon.h.
Member Function Documentation
apply()
void mslang::Polygon::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Definition at line 44 of file Polygon.cpp.
References triangles_m.
parse_detail()
bool mslang::Polygon::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 15 of file Polygon.cpp.
References Physics::e, end(), endl(), mslang::ArgumentExtractor::get(), mslang::ArgumentExtractor::getLengthConsumed(), mslang::ArgumentExtractor::getNumArguments(), mslang::parseMathExpression(), and triangulize().
Referenced by mslang::Function::parse().
print()
void mslang::Polygon::print (int ident) virtual
Implements mslang::Function.
Definition at line 40 of file Polygon.cpp.
triangulize()
void mslang::Polygon::triangulize (std::vector< Vector_t > & nodes)
Definition at line 10 of file Polygon.cpp.
References Mesher::getTriangles(), and triangles_m.
Referenced by parse_detail().
Member Data Documentation
triangles_m
std::vector<Triangle> mslang::Polygon::triangles_m
Definition at line 9 of file Polygon.h.
Referenced by apply(), and triangulize().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Polygon.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Polygon.cpp