OPAL (Object Oriented Parallel Accelerator Library): TagMaker Class Reference
TagMaker Class Reference
#include <TagMaker.h>
Classes
class TagCompare
class TagInfo
Public Member Functions
TagMaker (void)
virtual ~TagMaker (void)
int next_tag (int t, int s=1000)
int current_tag (int t, int s=1000)
int reset_tag (int t, int s=1000)
Private Member Functions
TagInfo & create_base_tag (int t, int s=1000)
Private Attributes
std::map< int, TagInfo, TagCompare > TagList
Detailed Description
Definition at line 27 of file TagMaker.h.
Constructor & Destructor Documentation
TagMaker()
TagMaker::TagMaker (void) inline
Definition at line 32 of file TagMaker.h.
~TagMaker()
virtual TagMaker::~TagMaker (void) inline virtual
Definition at line 33 of file TagMaker.h.
Member Function Documentation
create_base_tag()
TagInfo& TagMaker::create_base_tag (int t, int s = 1000) inline private
Definition at line 92 of file TagMaker.h.
References TagMaker::TagInfo::base, TagMaker::TagInfo::cycleSize, and TagList.
Referenced by current_tag(), next_tag(), and reset_tag().
current_tag()
int TagMaker::current_tag (int t, int s = 1000) inline
Definition at line 48 of file TagMaker.h.
References TagMaker::TagInfo::base, create_base_tag(), and TagMaker::TagInfo::current.
next_tag()
int TagMaker::next_tag (int t, int s = 1000) inline
Definition at line 39 of file TagMaker.h.
References TagMaker::TagInfo::base, create_base_tag(), TagMaker::TagInfo::current, and TagMaker::TagInfo::cycleSize.
Referenced by BareField< T1, D >::accumGuardCells(), ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), assign(), DiscField< Dim >::distribute_offsets(), ParallelTTracker::evenlyDistributeParticles(), FieldLayout< Dim >::FieldLayout(), BareField< T1, D >::fillGuardCells(), FieldDataSource< T, Dim, M, C >::gather_data(), BareField< T1, D >::getsingle(), BareField< T1, D >::getsingle_bc(), ParticleSpatialLayout< T, Dim, Mesh >::new_swap_particles(), pap(), DiscConfig::parse_config(), FieldPrint< T, Dim >::print(), FieldDebugPrint< T, Dim >::print(), DiscField< Dim >::read(), FieldLayout< Dim >::read(), DiscParticle::read_meta(), DiscField< Dim >::read_meta(), ParticleSpatialLayout< T, Dim, Mesh >::rebuild_layout(), reduce(), reduce_masked(), IpplParticleBase< T >::resetID(), LossDataSink::saveASCII(), scatter(), ParticleSpatialLayout< T, Dim, Mesh >::short_swap_particles(), ParallelCyclotronTracker::singleParticleDump(), spap(), ParticleCashedLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleInteractLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleSpatialLayout< T, Dim, Mesh >::swap_particles(), ParticleUniformLayout< T, Dim >::update(), ParticleCashedLayout< T, Dim, Mesh >::update(), ParticleInteractLayout< T, Dim, Mesh >::update(), ParticleSpatialLayout< T, Dim, Mesh >::update(), BoxLibLayout< T, Dim >::update(), BoxParticleCachingPolicy< T, Dim, Mesh >::updateGhostParticles(), BareField< T1, D >::write(), DiscParticle::write(), DiscField< Dim >::write(), and Distribution::writeOutFileEmission().
reset_tag()
int TagMaker::reset_tag (int t, int s = 1000) inline
Definition at line 56 of file TagMaker.h.
References TagMaker::TagInfo::base, create_base_tag(), and TagMaker::TagInfo::current.
Member Data Documentation
TagList
std::map<int, TagInfo, TagCompare> TagMaker::TagList private
Definition at line 87 of file TagMaker.h.
Referenced by create_base_tag().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Message/TagMaker.h