OPAL (Object Oriented Parallel Accelerator Library): DistributionMoments Class Reference
DistributionMoments Class Reference
#include <DistributionMoments.h>
Public Member Functions
DistributionMoments ()
void compute (const std::vector< OpalParticle >::const_iterator &, const std::vector< OpalParticle >::const_iterator &)
void compute (PartBunchBase< double, 3 > const &)
void computeMeanKineticEnergy (PartBunchBase< double, 3 > const &)
void computeDebyeLength (PartBunchBase< double, 3 > const &, double)
void computePlasmaParameter (double)
Vector_t getMeanPosition () const
Vector_t getStandardDeviationPosition () const
Vector_t getMeanMomentum () const
Vector_t getStandardDeviationMomentum () const
Vector_t getNormalizedEmittance () const
Vector_t getGeometricEmittance () const
Vector_t getStandardDeviationRP () const
Vector_t getHalo () const
Vector_t getMaxR () const
Vector_t get68Percentile () const
Vector_t get95Percentile () const
Vector_t get99Percentile () const
Vector_t get99_99Percentile () const
Vector_t getNormalizedEmittance68Percentile () const
Vector_t getNormalizedEmittance95Percentile () const
Vector_t getNormalizedEmittance99Percentile () const
Vector_t getNormalizedEmittance99_99Percentile () const
double getMeanTime () const
double getStdTime () const
double getMeanGamma () const
double getMeanKineticEnergy () const
double getTemperature () const
double getDebyeLength () const
double getPlasmaParameter () const
double getStdKineticEnergy () const
double getDx () const
double getDDx () const
double getDy () const
double getDDy () const
FMatrix< double, 6, 6 > getMoments6x6 () const
double getTotalCharge () const
double getTotalMass () const
double getTotalNumParticles () const
Private Types
using iterator_t = std::vector< Vektor< double, 2 > >::const_iterator
Private Member Functions
bool isParticleExcluded (const OpalParticle &) const
template<class InputIt >
void computeMeans (const InputIt &, const InputIt &)
template<class InputIt >
void computeStatistics (const InputIt &, const InputIt &)
template<class InputIt >
void computePercentiles (const InputIt &, const InputIt &)
std::pair< double, iterator_t > determinePercentilesDetail (const iterator_t &begin, const iterator_t &end, const std::vector< int > &globalAccumulatedHistogram, const std::vector< int > &localAccumulatedHistogram, unsigned int dimension, int numRequiredParticles) const
double computeNormalizedEmittance (const iterator_t &begin, const iterator_t &end) const
void fillMembers (std::vector< double > const &)
void reset ()
void resetPlasmaParameters ()
Private Attributes
Vector_t meanR_m
Vector_t meanP_m
Vector_t stdR_m
Vector_t stdP_m
Vector_t stdRP_m
Vector_t normalizedEps_m
Vector_t geometricEps_m
Vector_t halo_m
Vector_t maxR_m
Vector_t minR_m
Vector_t sixtyEightPercentile_m
Vector_t normalizedEps68Percentile_m
Vector_t ninetyFivePercentile_m
Vector_t normalizedEps95Percentile_m
Vector_t ninetyNinePercentile_m
Vector_t normalizedEps99Percentile_m
Vector_t ninetyNine_NinetyNinePercentile_m
Vector_t normalizedEps99_99Percentile_m
double meanTime_m
double stdTime_m
double meanKineticEnergy_m
double temperature_m
double debyeLength_m
double plasmaParameter_m
double stdKineticEnergy_m
double meanGamma_m
double centroid_m [6]
FMatrix< double, 6, 6 > moments_m
double totalCharge_m
double totalMass_m
unsigned int totalNumParticles_m
Static Private Attributes
static const double percentileOneSigmaNormalDist_m = std::erf(1 / sqrt(2))
static const double percentileTwoSigmasNormalDist_m = std::erf(2 / sqrt(2))
static const double percentileThreeSigmasNormalDist_m = std::erf(3 / sqrt(2))
static const double percentileFourSigmasNormalDist_m = std::erf(4 / sqrt(2))
Detailed Description
Definition at line 33 of file DistributionMoments.h.
Member Typedef Documentation
iterator_t
using DistributionMoments::iterator_t = std::vector<Vektor<double, 2> >::const_iterator private
Definition at line 88 of file DistributionMoments.h.
Constructor & Destructor Documentation
DistributionMoments()
DistributionMoments::DistributionMoments ()
Definition at line 40 of file DistributionMoments.cpp.
References reset(), and resetPlasmaParameters().
Member Function Documentation
compute() [1/2]
void DistributionMoments::compute (const std::vector< OpalParticle >::const_iterator & first, const std::vector< OpalParticle >::const_iterator & last)
Definition at line 51 of file DistributionMoments.cpp.
References computeStatistics().
Referenced by PartBunchBase< double, 3 >::calcBeamParameters(), and LossDataSink::saveH5().
compute() [2/2]
void DistributionMoments::compute (PartBunchBase< double, 3 > const & bunch)
Definition at line 46 of file DistributionMoments.cpp.
References PartBunchBase< T, Dim >::begin(), computeStatistics(), and PartBunchBase< T, Dim >::end().
computeDebyeLength()
void DistributionMoments::computeDebyeLength (PartBunchBase< double, 3 > const & bunch_r, double density)
Definition at line 434 of file DistributionMoments.cpp.
References allreduce(), Physics::c, computePlasmaParameter(), debyeLength_m, Physics::epsilon_0, Units::eV2kg, Util::getGamma(), Units::GeV2eV, Physics::m_e, pow(), Physics::q_e, resetPlasmaParameters(), sqrt(), and temperature_m.
Referenced by PartBunchBase< double, 3 >::calcDebyeLength().
computeMeanKineticEnergy()
void DistributionMoments::computeMeanKineticEnergy (PartBunchBase< double, 3 > const & bunch)
Definition at line 422 of file DistributionMoments.cpp.
References allreduce(), Util::getKineticEnergy(), and meanKineticEnergy_m.
Referenced by PartBunchBase< double, 3 >::calcEMean().
computeMeans()
template<class InputIt > void DistributionMoments::computeMeans (const InputIt & first, const InputIt & last) private
Definition at line 58 of file DistributionMoments.cpp.
References allreduce(), centroid_m, Util::getGamma(), OpalParticle::getMass(), OpalParticle::getP(), OpalParticle::getTime(), isParticleExcluded(), max(), maxR_m, meanGamma_m, meanKineticEnergy_m, meanP_m, meanR_m, meanTime_m, minR_m, and totalNumParticles_m.
Referenced by computeStatistics().
computeNormalizedEmittance()
double DistributionMoments::computeNormalizedEmittance (const iterator_t & begin, const iterator_t & end) const private
Definition at line 340 of file DistributionMoments.cpp.
References allreduce(), begin(), end(), max(), pow(), and sqrt().
Referenced by computePercentiles().
computePercentiles()
template<class InputIt > void DistributionMoments::computePercentiles (const InputIt & first, const InputIt & last) private
Definition at line 167 of file DistributionMoments.cpp.
References abs(), allreduce(), computeNormalizedEmittance(), Options::computePercentiles, determinePercentilesDetail(), floor(), log10(), max(), maxR_m, meanR_m, minR_m, ninetyFivePercentile_m, ninetyNine_NinetyNinePercentile_m, ninetyNinePercentile_m, normalizedEps68Percentile_m, normalizedEps95Percentile_m, normalizedEps99_99Percentile_m, normalizedEps99Percentile_m, percentileFourSigmasNormalDist_m, percentileOneSigmaNormalDist_m, percentileThreeSigmasNormalDist_m, percentileTwoSigmasNormalDist_m, pow(), sixtyEightPercentile_m, and totalNumParticles_m.
Referenced by computeStatistics().
computePlasmaParameter()
void DistributionMoments::computePlasmaParameter (double density)
Definition at line 476 of file DistributionMoments.cpp.
References debyeLength_m, Physics::pi, plasmaParameter_m, and pow().
Referenced by computeDebyeLength().
computeStatistics()
template<class InputIt > void DistributionMoments::computeStatistics (const InputIt & first, const InputIt & last) private
Definition at line 123 of file DistributionMoments.cpp.
References allreduce(), centroid_m, computeMeans(), computePercentiles(), fillMembers(), OpalParticle::getCharge(), Util::getKineticEnergy(), OpalParticle::getMass(), OpalParticle::getP(), OpalParticle::getTime(), isParticleExcluded(), meanKineticEnergy_m, meanTime_m, pow(), reset(), and totalNumParticles_m.
Referenced by compute().
determinePercentilesDetail()
std::pair< double, DistributionMoments::iterator_t > DistributionMoments::determinePercentilesDetail (const iterator_t & begin, const iterator_t & end, const std::vector< int > & globalAccumulatedHistogram, const std::vector< int > & localAccumulatedHistogram, unsigned int dimension, int numRequiredParticles) const private
Computes the percentile and the range of all local particles that are contained therein. In a first step the container globalAccumulatedHistogram is looped through until accumulated histogram value exceeds the required number of particles. The percentile then is between the boundaries of the last histogram bin before the loop stopped. Then all particle coordinates that are between the boundaries of this bin are communicated acros all nodes and sorted. The exact percentile is then determined by counting the n smallest coordinates such that the total number of partiles results is equal to 'numRequiredParticles'. In accordance with matlab (?) the percentile is the midpoint between the last particle within the percentile and tje first particle outside. Finally each node determines which of its particles are contained in the percentile.
To determine the histogram, the coordinates should not be used directly. Instead, the absolute value of the difference between a coordinate and the mean, |x - <x>|, should be used so that the percentile values are similar to the standard deviation.
Parameters
begin begin of a container containing the one dimensional phase space of all local particles.
end end of the container.
globalAccumulatedHistogram container with partial sum of histogram values of position coordinates summed up across all nodes. The first value should be 0.
localAccumulatedHistogram container with partial sum of histogram values of position coordinates of all local particles. The first value should be 0.
dimension dimension of the one dimensional phase space.
numRequiredParticles number of particles that are contained in the requested percentile. Is determined by the total number of particles and the percentile.
Returns
: pair of percentile and iterator pointing to the element after the range contained in the percentile.
Definition at line 292 of file DistributionMoments.cpp.
References abs(), allreduce(), begin(), end(), IpplInfo::getNodes(), meanR_m, and IpplInfo::myNode().
Referenced by computePercentiles().
fillMembers()
void DistributionMoments::fillMembers (std::vector< double > const & localMoments) private
Definition at line 376 of file DistributionMoments.cpp.
References centroid_m, geometricEps_m, halo_m, Options::haloShift, max(), meanGamma_m, meanP_m, meanR_m, moments_m, normalizedEps_m, pow(), sqrt(), stdKineticEnergy_m, stdP_m, stdR_m, stdRP_m, stdTime_m, totalCharge_m, totalMass_m, and totalNumParticles_m.
Referenced by computeStatistics().
get68Percentile()
Vector_t DistributionMoments::get68Percentile () const inline
Definition at line 285 of file DistributionMoments.h.
References sixtyEightPercentile_m.
Referenced by PartBunchBase< double, 3 >::get_68Percentile().
get95Percentile()
Vector_t DistributionMoments::get95Percentile () const inline
Definition at line 297 of file DistributionMoments.h.
References ninetyFivePercentile_m.
Referenced by PartBunchBase< double, 3 >::get_95Percentile().
get99_99Percentile()
Vector_t DistributionMoments::get99_99Percentile () const inline
Definition at line 321 of file DistributionMoments.h.
References ninetyNine_NinetyNinePercentile_m.
Referenced by PartBunchBase< double, 3 >::get_99_99Percentile().
get99Percentile()
Vector_t DistributionMoments::get99Percentile () const inline
Definition at line 309 of file DistributionMoments.h.
References ninetyNinePercentile_m.
Referenced by PartBunchBase< double, 3 >::get_99Percentile().
getDDx()
double DistributionMoments::getDDx () const inline
Definition at line 243 of file DistributionMoments.h.
References moments_m.
Referenced by PartBunchBase< double, 3 >::get_DDx().
getDDy()
double DistributionMoments::getDDy () const inline
Definition at line 255 of file DistributionMoments.h.
References moments_m.
Referenced by PartBunchBase< double, 3 >::get_DDy().
getDebyeLength()
double DistributionMoments::getDebyeLength () const inline
Definition at line 220 of file DistributionMoments.h.
References debyeLength_m.
Referenced by PartBunchBase< double, 3 >::get_debyeLength().
getDx()
double DistributionMoments::getDx () const inline
Definition at line 237 of file DistributionMoments.h.
References moments_m.
Referenced by PartBunchBase< double, 3 >::get_Dx().
getDy()
double DistributionMoments::getDy () const inline
Definition at line 249 of file DistributionMoments.h.
References moments_m.
Referenced by PartBunchBase< double, 3 >::get_Dy().
getGeometricEmittance()
Vector_t DistributionMoments::getGeometricEmittance () const inline
Definition at line 170 of file DistributionMoments.h.
References geometricEps_m.
Referenced by PartBunchBase< double, 3 >::get_emit().
getHalo()
Vector_t DistributionMoments::getHalo () const inline
Definition at line 182 of file DistributionMoments.h.
References halo_m.
Referenced by PartBunchBase< double, 3 >::get_halo().
getMaxR()
Vector_t DistributionMoments::getMaxR () const inline
Definition at line 333 of file DistributionMoments.h.
References abs(), max(), maxR_m, and minR_m.
getMeanGamma()
double DistributionMoments::getMeanGamma () const inline
Definition at line 200 of file DistributionMoments.h.
References meanGamma_m.
Referenced by PartBunchBase< double, 3 >::get_gamma().
getMeanKineticEnergy()
double DistributionMoments::getMeanKineticEnergy () const inline
Definition at line 206 of file DistributionMoments.h.
References meanKineticEnergy_m.
Referenced by PartBunchBase< double, 3 >::get_meanKineticEnergy().
getMeanMomentum()
Vector_t DistributionMoments::getMeanMomentum () const inline
Definition at line 152 of file DistributionMoments.h.
References meanP_m.
Referenced by PartBunchBase< double, 3 >::get_pmean().
getMeanPosition()
Vector_t DistributionMoments::getMeanPosition () const inline
Definition at line 140 of file DistributionMoments.h.
References meanR_m.
Referenced by PartBunchBase< double, 3 >::boundp_destroyCycl(), PartBunchBase< double, 3 >::boundp_destroyT(), PartBunchBase< double, 3 >::get_centroid(), and PartBunchBase< double, 3 >::get_rmean().
getMeanTime()
double DistributionMoments::getMeanTime () const inline
Definition at line 188 of file DistributionMoments.h.
References meanTime_m.
getMoments6x6()
FMatrix< double, 6, 6 > DistributionMoments::getMoments6x6 () const inline
Definition at line 261 of file DistributionMoments.h.
References moments_m.
Referenced by PartBunchBase< double, 3 >::getSigmaMatrix().
getNormalizedEmittance()
Vector_t DistributionMoments::getNormalizedEmittance () const inline
Definition at line 164 of file DistributionMoments.h.
References normalizedEps_m.
Referenced by PartBunchBase< double, 3 >::get_norm_emit().
getNormalizedEmittance68Percentile()
Vector_t DistributionMoments::getNormalizedEmittance68Percentile () const inline
Definition at line 291 of file DistributionMoments.h.
References normalizedEps68Percentile_m.
Referenced by PartBunchBase< double, 3 >::get_normalizedEps_68Percentile().
getNormalizedEmittance95Percentile()
Vector_t DistributionMoments::getNormalizedEmittance95Percentile () const inline
Definition at line 303 of file DistributionMoments.h.
References normalizedEps95Percentile_m.
Referenced by PartBunchBase< double, 3 >::get_normalizedEps_95Percentile().
getNormalizedEmittance99_99Percentile()
Vector_t DistributionMoments::getNormalizedEmittance99_99Percentile () const inline
Definition at line 327 of file DistributionMoments.h.
References normalizedEps99_99Percentile_m.
Referenced by PartBunchBase< double, 3 >::get_normalizedEps_99_99Percentile().
getNormalizedEmittance99Percentile()
Vector_t DistributionMoments::getNormalizedEmittance99Percentile () const inline
Definition at line 315 of file DistributionMoments.h.
References normalizedEps99Percentile_m.
Referenced by PartBunchBase< double, 3 >::get_normalizedEps_99Percentile().
getPlasmaParameter()
double DistributionMoments::getPlasmaParameter () const inline
Definition at line 225 of file DistributionMoments.h.
References plasmaParameter_m.
Referenced by PartBunchBase< double, 3 >::get_plasmaParameter().
getStandardDeviationMomentum()
Vector_t DistributionMoments::getStandardDeviationMomentum () const inline
Definition at line 158 of file DistributionMoments.h.
References stdP_m.
Referenced by PartBunchBase< double, 3 >::get_prms().
getStandardDeviationPosition()
Vector_t DistributionMoments::getStandardDeviationPosition () const inline
Definition at line 146 of file DistributionMoments.h.
References stdR_m.
Referenced by PartBunchBase< double, 3 >::boundp_destroyCycl(), PartBunchBase< double, 3 >::boundp_destroyT(), and PartBunchBase< double, 3 >::get_rrms().
getStandardDeviationRP()
Vector_t DistributionMoments::getStandardDeviationRP () const inline
Definition at line 176 of file DistributionMoments.h.
References stdRP_m.
Referenced by PartBunchBase< double, 3 >::get_rprms().
getStdKineticEnergy()
double DistributionMoments::getStdKineticEnergy () const inline
Definition at line 231 of file DistributionMoments.h.
References stdKineticEnergy_m.
Referenced by PartBunchBase< double, 3 >::getdE().
getStdTime()
double DistributionMoments::getStdTime () const inline
Definition at line 194 of file DistributionMoments.h.
References stdTime_m.
getTemperature()
double DistributionMoments::getTemperature () const inline
Definition at line 213 of file DistributionMoments.h.
References Physics::c, Units::eV2kg, Physics::kB, and temperature_m.
Referenced by PartBunchBase< double, 3 >::get_temperature().
getTotalCharge()
double DistributionMoments::getTotalCharge () const inline
Definition at line 267 of file DistributionMoments.h.
References totalCharge_m.
getTotalMass()
double DistributionMoments::getTotalMass () const inline
Definition at line 273 of file DistributionMoments.h.
References totalMass_m.
getTotalNumParticles()
double DistributionMoments::getTotalNumParticles () const inline
Definition at line 279 of file DistributionMoments.h.
References totalNumParticles_m.
isParticleExcluded()
bool DistributionMoments::isParticleExcluded (const OpalParticle & particle) const private
Definition at line 521 of file DistributionMoments.cpp.
References Options::amr, OpalParticle::getId(), OpalData::getInstance(), and OpalData::isInOPALCyclMode().
Referenced by computeMeans(), and computeStatistics().
reset()
void DistributionMoments::reset () private
Definition at line 483 of file DistributionMoments.cpp.
References begin(), centroid_m, end(), geometricEps_m, halo_m, meanKineticEnergy_m, meanP_m, meanR_m, moments_m, ninetyFivePercentile_m, ninetyNine_NinetyNinePercentile_m, ninetyNinePercentile_m, normalizedEps68Percentile_m, normalizedEps95Percentile_m, normalizedEps99_99Percentile_m, normalizedEps99Percentile_m, normalizedEps_m, sixtyEightPercentile_m, stdKineticEnergy_m, stdP_m, stdR_m, stdRP_m, totalCharge_m, totalMass_m, and totalNumParticles_m.
Referenced by computeStatistics(), and DistributionMoments().
resetPlasmaParameters()
void DistributionMoments::resetPlasmaParameters () private
Definition at line 514 of file DistributionMoments.cpp.
References debyeLength_m, plasmaParameter_m, and temperature_m.
Referenced by computeDebyeLength(), and DistributionMoments().
Member Data Documentation
centroid_m
double DistributionMoments::centroid_m[6] private
Definition at line 126 of file DistributionMoments.h.
Referenced by computeMeans(), computeStatistics(), fillMembers(), and reset().
debyeLength_m
double DistributionMoments::debyeLength_m private
Definition at line 122 of file DistributionMoments.h.
Referenced by computeDebyeLength(), computePlasmaParameter(), getDebyeLength(), and resetPlasmaParameters().
geometricEps_m
Vector_t DistributionMoments::geometricEps_m private
Definition at line 105 of file DistributionMoments.h.
Referenced by fillMembers(), getGeometricEmittance(), and reset().
halo_m
Vector_t DistributionMoments::halo_m private
Definition at line 106 of file DistributionMoments.h.
Referenced by fillMembers(), getHalo(), and reset().
maxR_m
Vector_t DistributionMoments::maxR_m private
Definition at line 107 of file DistributionMoments.h.
Referenced by computeMeans(), computePercentiles(), and getMaxR().
meanGamma_m
double DistributionMoments::meanGamma_m private
Definition at line 125 of file DistributionMoments.h.
Referenced by computeMeans(), fillMembers(), and getMeanGamma().
meanKineticEnergy_m
double DistributionMoments::meanKineticEnergy_m private
Definition at line 120 of file DistributionMoments.h.
Referenced by computeMeanKineticEnergy(), computeMeans(), computeStatistics(), getMeanKineticEnergy(), and reset().
meanP_m
Vector_t DistributionMoments::meanP_m private
Definition at line 100 of file DistributionMoments.h.
Referenced by computeMeans(), fillMembers(), getMeanMomentum(), and reset().
meanR_m
Vector_t DistributionMoments::meanR_m private
Definition at line 99 of file DistributionMoments.h.
Referenced by computeMeans(), computePercentiles(), determinePercentilesDetail(), fillMembers(), getMeanPosition(), and reset().
meanTime_m
double DistributionMoments::meanTime_m private
Definition at line 118 of file DistributionMoments.h.
Referenced by computeMeans(), computeStatistics(), and getMeanTime().
minR_m
Vector_t DistributionMoments::minR_m private
Definition at line 108 of file DistributionMoments.h.
Referenced by computeMeans(), computePercentiles(), and getMaxR().
moments_m
FMatrix<double, 6, 6> DistributionMoments::moments_m private
Definition at line 127 of file DistributionMoments.h.
Referenced by fillMembers(), getDDx(), getDDy(), getDx(), getDy(), getMoments6x6(), and reset().
ninetyFivePercentile_m
Vector_t DistributionMoments::ninetyFivePercentile_m private
Definition at line 111 of file DistributionMoments.h.
Referenced by computePercentiles(), get95Percentile(), and reset().
ninetyNine_NinetyNinePercentile_m
Vector_t DistributionMoments::ninetyNine_NinetyNinePercentile_m private
Definition at line 115 of file DistributionMoments.h.
Referenced by computePercentiles(), get99_99Percentile(), and reset().
ninetyNinePercentile_m
Vector_t DistributionMoments::ninetyNinePercentile_m private
Definition at line 113 of file DistributionMoments.h.
Referenced by computePercentiles(), get99Percentile(), and reset().
normalizedEps68Percentile_m
Vector_t DistributionMoments::normalizedEps68Percentile_m private
Definition at line 110 of file DistributionMoments.h.
Referenced by computePercentiles(), getNormalizedEmittance68Percentile(), and reset().
normalizedEps95Percentile_m
Vector_t DistributionMoments::normalizedEps95Percentile_m private
Definition at line 112 of file DistributionMoments.h.
Referenced by computePercentiles(), getNormalizedEmittance95Percentile(), and reset().
normalizedEps99_99Percentile_m
Vector_t DistributionMoments::normalizedEps99_99Percentile_m private
Definition at line 116 of file DistributionMoments.h.
Referenced by computePercentiles(), getNormalizedEmittance99_99Percentile(), and reset().
normalizedEps99Percentile_m
Vector_t DistributionMoments::normalizedEps99Percentile_m private
Definition at line 114 of file DistributionMoments.h.
Referenced by computePercentiles(), getNormalizedEmittance99Percentile(), and reset().
normalizedEps_m
Vector_t DistributionMoments::normalizedEps_m private
Definition at line 104 of file DistributionMoments.h.
Referenced by fillMembers(), getNormalizedEmittance(), and reset().
percentileFourSigmasNormalDist_m
const double DistributionMoments::percentileFourSigmasNormalDist_m = std::erf(4 / sqrt(2)) static private
Definition at line 136 of file DistributionMoments.h.
Referenced by computePercentiles().
percentileOneSigmaNormalDist_m
const double DistributionMoments::percentileOneSigmaNormalDist_m = std::erf(1 / sqrt(2)) static private
Definition at line 133 of file DistributionMoments.h.
Referenced by computePercentiles().
percentileThreeSigmasNormalDist_m
const double DistributionMoments::percentileThreeSigmasNormalDist_m = std::erf(3 / sqrt(2)) static private
Definition at line 135 of file DistributionMoments.h.
Referenced by computePercentiles().
percentileTwoSigmasNormalDist_m
const double DistributionMoments::percentileTwoSigmasNormalDist_m = std::erf(2 / sqrt(2)) static private
Definition at line 134 of file DistributionMoments.h.
Referenced by computePercentiles().
plasmaParameter_m
double DistributionMoments::plasmaParameter_m private
Definition at line 123 of file DistributionMoments.h.
Referenced by computePlasmaParameter(), getPlasmaParameter(), and resetPlasmaParameters().
sixtyEightPercentile_m
Vector_t DistributionMoments::sixtyEightPercentile_m private
Definition at line 109 of file DistributionMoments.h.
Referenced by computePercentiles(), get68Percentile(), and reset().
stdKineticEnergy_m
double DistributionMoments::stdKineticEnergy_m private
Definition at line 124 of file DistributionMoments.h.
Referenced by fillMembers(), getStdKineticEnergy(), and reset().
stdP_m
Vector_t DistributionMoments::stdP_m private
Definition at line 102 of file DistributionMoments.h.
Referenced by fillMembers(), getStandardDeviationMomentum(), and reset().
stdR_m
Vector_t DistributionMoments::stdR_m private
Definition at line 101 of file DistributionMoments.h.
Referenced by fillMembers(), getStandardDeviationPosition(), and reset().
stdRP_m
Vector_t DistributionMoments::stdRP_m private
Definition at line 103 of file DistributionMoments.h.
Referenced by fillMembers(), getStandardDeviationRP(), and reset().
stdTime_m
double DistributionMoments::stdTime_m private
Definition at line 119 of file DistributionMoments.h.
Referenced by fillMembers(), and getStdTime().
temperature_m
double DistributionMoments::temperature_m private
Definition at line 121 of file DistributionMoments.h.
Referenced by computeDebyeLength(), getTemperature(), and resetPlasmaParameters().
totalCharge_m
double DistributionMoments::totalCharge_m private
Definition at line 129 of file DistributionMoments.h.
Referenced by fillMembers(), getTotalCharge(), and reset().
totalMass_m
double DistributionMoments::totalMass_m private
Definition at line 130 of file DistributionMoments.h.
Referenced by fillMembers(), getTotalMass(), and reset().
totalNumParticles_m
unsigned int DistributionMoments::totalNumParticles_m private
Definition at line 131 of file DistributionMoments.h.
Referenced by computeMeans(), computePercentiles(), computeStatistics(), fillMembers(), getTotalNumParticles(), and reset().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algorithms/DistributionMoments.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algorithms/DistributionMoments.cpp