OPAL (Object Oriented Parallel Accelerator Library): FileParticleAttribDataSource< T > Class Template Reference
FileParticleAttribDataSource< T > Class Template Reference
#include <FilePtclAttribDataSource.h>
Public Member Functions
FileParticleAttribDataSource (const char *, DataConnect *, int, ParticleAttrib< T > &)
virtual ~FileParticleAttribDataSource ()
virtual bool update ()
virtual void interact (const char *=0)
Public Member Functions inherited from DataSourceObject
DataSourceObject (const char *nm, DataSource *ds, DataConnect *dc, int tm)
DataSourceObject ()
virtual ~DataSourceObject ()
bool connected () const
DataConnect * getConnection ()
DataSource * getSource ()
Public Member Functions inherited from NamedObj
NamedObj (const char *nm=0)
virtual ~NamedObj ()
const char * name () const
const char * setName (const char *nm=0)
Private Attributes
DiscParticle * DP
ParticleAttrib< T > & MyParticles
int counter
Additional Inherited Members
Protected Attributes inherited from DataSourceObject
DataConnect * Connection
DataSource * Source
int TransferMethod
Detailed Description
template<class T>
class FileParticleAttribDataSource< T >
Definition at line 31 of file FilePtclAttribDataSource.h.
Constructor & Destructor Documentation
FileParticleAttribDataSource()
template<class T > FileParticleAttribDataSource< T >::FileParticleAttribDataSource (const char * nm, DataConnect * dc, int tm, ParticleAttrib< T > & P)
Definition at line 37 of file FilePtclAttribDataSource.hpp.
References DataSourceObject::Connection, FileParticleAttribDataSource< T >::DP, DataConnect::DSID(), endl(), ERRORMSG, FileDataConnect::getTypeString(), DiscParticle::INPUT, DataSource::INPUT, NamedObj::name(), DiscParticle::OUTPUT, DataSource::OUTPUT, and DataSourceObject::TransferMethod.
~FileParticleAttribDataSource()
template<class T > FileParticleAttribDataSource< T >::~FileParticleAttribDataSource () virtual
Definition at line 62 of file FilePtclAttribDataSource.hpp.
Member Function Documentation
interact()
template<class T > void FileParticleAttribDataSource< T >::interact (const char * = 0) virtual
Reimplemented from DataSourceObject.
Definition at line 90 of file FilePtclAttribDataSource.hpp.
update()
template<class T > bool FileParticleAttribDataSource< T >::update () virtual
Reimplemented from DataSourceObject.
Definition at line 73 of file FilePtclAttribDataSource.hpp.
References DataSource::INPUT, and DataSource::OUTPUT.
Member Data Documentation
counter
template<class T> int FileParticleAttribDataSource< T >::counter private
Definition at line 63 of file FilePtclAttribDataSource.h.
DP
template<class T> DiscParticle* FileParticleAttribDataSource< T >::DP private
Definition at line 57 of file FilePtclAttribDataSource.h.
Referenced by FileParticleAttribDataSource< T >::FileParticleAttribDataSource().
MyParticles
template<class T> ParticleAttrib<T>& FileParticleAttribDataSource< T >::MyParticles private
Definition at line 60 of file FilePtclAttribDataSource.h.
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/FilePtclAttribDataSource.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/FilePtclAttribDataSource.hpp