OPAL (Object Oriented Parallel Accelerator Library): src/Classic/Algorithms/CoordinateSystemTrafo.h File Reference
CoordinateSystemTrafo.h File Reference
#include "Algorithms/BoostMatrix.h"
#include "Algorithms/Vektor.h"
#include "Algorithms/Quaternion.h"
Classes
class CoordinateSystemTrafo
Functions
std::ostream & operator<< (std::ostream &os, const CoordinateSystemTrafo &trafo)
Inform & operator<< (Inform &os, const CoordinateSystemTrafo &trafo)
Function Documentation
operator<<() [1/2]
std::ostream& operator<< (std::ostream & os, const CoordinateSystemTrafo & trafo) inline
Definition at line 41 of file CoordinateSystemTrafo.h.
References CoordinateSystemTrafo::print().
operator<<() [2/2]
Inform& operator<< (Inform & os, const CoordinateSystemTrafo & trafo) inline
Definition at line 47 of file CoordinateSystemTrafo.h.
References Inform::getStream(), and CoordinateSystemTrafo::print().