OPAL (Object Oriented Parallel Accelerator Library): PatchBC< T, D, M, C > Class Template Reference
PatchBC< T, D, M, C > Class Template Reference abstract
#include <BCond.h>
Public Member Functions
PatchBC (unsigned face)
void apply (Field< T, D, M, C > &)
virtual void applyPatch (typename Field< T, D, M, C >::iterator, const NDIndex< D > &)=0
virtual void write (std::ostream &out) const
Public Member Functions inherited from BCondBase< T, D, M, C >
BCondBase (unsigned int face, int i=allComponents, int j=allComponents)
virtual ~BCondBase ()
virtual BCondBase< T, D, M, C > * clone () const =0
int getComponent () const
unsigned int getFace () const
bool changesPhysicalCells () const
Public Member Functions inherited from RefCounted
RefCounted ()
Additional Inherited Members
Public Attributes inherited from RefCounted
int RefCount
Static Public Attributes inherited from BCondBase< T, D, M, C >
static int allComponents = -9999
Protected Attributes inherited from BCondBase< T, D, M, C >
int m_component
unsigned int m_face
bool m_changePhysical
Detailed Description
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering>
class PatchBC< T, D, M, C >
Definition at line 835 of file BCond.h.
Constructor & Destructor Documentation
PatchBC()
template<class T , unsigned D, class M , class C > PatchBC< T, D, M, C >::PatchBC (unsigned face)
Definition at line 6097 of file BCond.hpp.
Member Function Documentation
apply()
template<class T , unsigned D, class M , class C > void PatchBC< T, D, M, C >::apply (Field< T, D, M, C > & A) virtual
Implements BCondBase< T, D, M, C >.
Definition at line 6112 of file BCond.hpp.
References AddGuardCells(), BareField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), LField< T, Dim >::getAllocated(), BareField< T, Dim >::getDomain(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), Index::intersect(), BareField< T, Dim >::leftGuard(), max(), min(), BareField< T, Dim >::rightGuard(), BareFieldIterator< T, Dim >::SetCurrentLocation(), Index::touches(), and LField< T, Dim >::Uncompress().
applyPatch()
template<class T , unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering> virtual void PatchBC< T, D, M, C >::applyPatch (typename Field< T, D, M, C >::iterator , const NDIndex< D > &) pure virtual
write()
template<class T , unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering> virtual void PatchBC< T, D, M, C >::write (std::ostream & out) const inline virtual
Reimplemented from BCondBase< T, D, M, C >.
Definition at line 859 of file BCond.h.
References BCondBase< T, D, M, C >::getFace().
The documentation for this class was generated from the following files:
ippl/src/Field/BCond.h
ippl/src/Field/BCond.hpp