OPAL (Object Oriented Parallel Accelerator Library): ippl/src/FieldLayout/BinaryBalancer.hpp File Reference
BinaryBalancer.hpp File Reference
#include "FieldLayout/BinaryBalancer.h"
#include "FieldLayout/FieldLayout.h"
#include "Field/BareField.h"
#include "Utility/PAssert.h"
Functions
void BcastCuts (int cutLoc, int cutAxis, int bcast_tag)
template<unsigned Dim>
NDIndex< Dim > CalcBinaryRepartition (FieldLayout< Dim > &layout, BareField< double, Dim > &weights)
Function Documentation
BcastCuts()
void BcastCuts (int cutLoc, int cutAxis, int bcast_tag) inline
Definition at line 454 of file BinaryBalancer.hpp.
References Communicate::broadcast_all(), IpplInfo::Comm, and Message::put().
CalcBinaryRepartition()
template<unsigned Dim> NDIndex<Dim> CalcBinaryRepartition (FieldLayout< Dim > & layout, BareField< double, Dim > & weights)
Definition at line 586 of file BinaryBalancer.hpp.
References IpplInfo::Comm, FieldLayout< Dim >::getDomain(), Communicate::getNodes(), and Communicate::myNode().
Referenced by BinaryRepartition().