OPAL (Object Oriented Parallel Accelerator Library): GuardCellSizes< Dim > Class Template Reference
GuardCellSizes< Dim > Class Template Reference
#include <FieldSpec.h>
Public Member Functions
GuardCellSizes ()
GuardCellSizes (unsigned s)
GuardCellSizes (unsigned *s)
GuardCellSizes (unsigned l, unsigned r)
GuardCellSizes (unsigned *l, unsigned *r)
constexpr GuardCellSizes (const GuardCellSizes< Dim > &)=default
GuardCellSizes< Dim > & operator= (const GuardCellSizes< Dim > &gc)
void set_Left (unsigned s)
void set_Left (unsigned *s)
void set_Left (unsigned d, unsigned *s)
void set_Right (unsigned s)
void set_Right (unsigned *s)
void set_Right (unsigned d, unsigned *s)
unsigned left (unsigned d) const
unsigned right (unsigned d) const
bool operator< (const GuardCellSizes< Dim > &r) const
bool operator== (const GuardCellSizes< Dim > &r) const
Private Attributes
unsigned Left [Dim]
unsigned Right [Dim]
Detailed Description
template<unsigned Dim>
class GuardCellSizes< Dim >
Definition at line 17 of file FieldSpec.h.
Constructor & Destructor Documentation
GuardCellSizes() [1/6]
template<unsigned Dim> GuardCellSizes< Dim >::GuardCellSizes () inline
Definition at line 25 of file GuardCellSizes.h.
References Dim, GuardCellSizes< Dim >::Left, and GuardCellSizes< Dim >::Right.
GuardCellSizes() [2/6]
template<unsigned Dim> GuardCellSizes< Dim >::GuardCellSizes (unsigned s)
Definition at line 31 of file GuardCellSizes.hpp.
References Dim.
GuardCellSizes() [3/6]
template<unsigned Dim> GuardCellSizes< Dim >::GuardCellSizes (unsigned * s)
Definition at line 40 of file GuardCellSizes.hpp.
References Dim.
GuardCellSizes() [4/6]
template<unsigned Dim> GuardCellSizes< Dim >::GuardCellSizes (unsigned l, unsigned r)
Definition at line 49 of file GuardCellSizes.hpp.
References Dim.
GuardCellSizes() [5/6]
template<unsigned Dim> GuardCellSizes< Dim >::GuardCellSizes (unsigned * l, unsigned * r)
Definition at line 60 of file GuardCellSizes.hpp.
References Dim.
GuardCellSizes() [6/6]
template<unsigned Dim> constexpr GuardCellSizes< Dim >::GuardCellSizes (const GuardCellSizes< Dim > &) default
Member Function Documentation
left()
template<unsigned Dim> unsigned GuardCellSizes< Dim >::left (unsigned d) const inline
Definition at line 52 of file GuardCellSizes.h.
References GuardCellSizes< Dim >::Left.
Referenced by calcEurekaDomain(), FieldLayout< Dim >::fitsGuardCells(), GuardCellSizes< Dim >::operator<(), and GuardCellSizes< Dim >::operator==().
operator<()
template<unsigned Dim> bool GuardCellSizes< Dim >::operator< (const GuardCellSizes< Dim > & r) const inline
Definition at line 82 of file GuardCellSizes.h.
References Dim, GuardCellSizes< Dim >::left(), and GuardCellSizes< Dim >::right().
operator=()
template<unsigned Dim> GuardCellSizes<Dim>& GuardCellSizes< Dim >::operator= (const GuardCellSizes< Dim > & gc) inline
Definition at line 35 of file GuardCellSizes.h.
References Dim, GuardCellSizes< Dim >::Left, and GuardCellSizes< Dim >::Right.
operator==()
template<unsigned Dim> bool GuardCellSizes< Dim >::operator== (const GuardCellSizes< Dim > & r) const inline
Definition at line 96 of file GuardCellSizes.h.
References Dim, GuardCellSizes< Dim >::left(), and GuardCellSizes< Dim >::right().
right()
template<unsigned Dim> unsigned GuardCellSizes< Dim >::right (unsigned d) const inline
Definition at line 53 of file GuardCellSizes.h.
References GuardCellSizes< Dim >::Right.
Referenced by calcEurekaDomain(), FieldLayout< Dim >::fitsGuardCells(), GuardCellSizes< Dim >::operator<(), and GuardCellSizes< Dim >::operator==().
set_Left() [1/3]
template<unsigned Dim> void GuardCellSizes< Dim >::set_Left (unsigned s)
Definition at line 71 of file GuardCellSizes.hpp.
References Dim.
set_Left() [2/3]
template<unsigned Dim> void GuardCellSizes< Dim >::set_Left (unsigned * s)
Definition at line 80 of file GuardCellSizes.hpp.
References Dim.
set_Left() [3/3]
template<unsigned Dim> void GuardCellSizes< Dim >::set_Left (unsigned d, unsigned * s)
Definition at line 89 of file GuardCellSizes.hpp.
set_Right() [1/3]
template<unsigned Dim> void GuardCellSizes< Dim >::set_Right (unsigned s)
Definition at line 97 of file GuardCellSizes.hpp.
References Dim.
set_Right() [2/3]
template<unsigned Dim> void GuardCellSizes< Dim >::set_Right (unsigned * s)
Definition at line 106 of file GuardCellSizes.hpp.
References Dim.
set_Right() [3/3]
template<unsigned Dim> void GuardCellSizes< Dim >::set_Right (unsigned d, unsigned * s)
Definition at line 115 of file GuardCellSizes.hpp.
Member Data Documentation
Left
template<unsigned Dim> unsigned GuardCellSizes< Dim >::Left[Dim] private
Definition at line 62 of file GuardCellSizes.h.
Referenced by GuardCellSizes< Dim >::GuardCellSizes(), GuardCellSizes< Dim >::left(), and GuardCellSizes< Dim >::operator=().
Right
template<unsigned Dim> unsigned GuardCellSizes< Dim >::Right[Dim] private
Definition at line 63 of file GuardCellSizes.h.
Referenced by GuardCellSizes< Dim >::GuardCellSizes(), GuardCellSizes< Dim >::operator=(), and GuardCellSizes< Dim >::right().
The documentation for this class was generated from the following files:
ippl/src/Field/FieldSpec.h
ippl/src/Field/GuardCellSizes.h
ippl/src/Field/GuardCellSizes.hpp