OPAL (Object Oriented Parallel Accelerator Library): SDDSParserException Class Reference
SDDSParserException Class Reference
#include <SDDSParserException.h>
Public Member Functions
SDDSParserException (const std::string &meth, const std::string &descr)
virtual const char * what () const throw ()
virtual const char * where () const throw ()
Private Attributes
std::string descr_
std::string meth_
Detailed Description
Definition at line 22 of file SDDSParserException.h.
Constructor & Destructor Documentation
SDDSParserException()
SDDSParserException::SDDSParserException (const std::string & meth, const std::string & descr) inline
Definition at line 26 of file SDDSParserException.h.
References descr_, and meth_.
Member Function Documentation
what()
virtual const char* SDDSParserException::what () const throw () inline virtual
Definition at line 31 of file SDDSParserException.h.
References descr_.
Referenced by main(), and SDDSVariable::operator()().
where()
virtual const char* SDDSParserException::where () const throw () inline virtual
Definition at line 35 of file SDDSParserException.h.
References meth_.
Referenced by main().
Member Data Documentation
descr_
std::string SDDSParserException::descr_ private
Definition at line 41 of file SDDSParserException.h.
Referenced by SDDSParserException(), and what().
meth_
std::string SDDSParserException::meth_ private
Definition at line 42 of file SDDSParserException.h.
Referenced by SDDSParserException(), and where().
The documentation for this class was generated from the following file:
optimizer/Util/SDDSParser/SDDSParserException.h