OPAL (Object Oriented Parallel Accelerator Library): SpecializedGreensFunction< 3 > Struct Template Reference
SpecializedGreensFunction< 3 > Struct Template Reference
Static Public Member Functions
template<class T , class FT , class FT2 >
static void calculate (Vektor< T, 3 > &hrsq, FT &grn, FT2 *grnI)
template<class T , class FT , class FT2 >
static void calculate (Vektor< T, 3 > &hrsq, FT &grn, FT2 *grnI)
template<class T , class FT , class FT2 >
static void calculate (Vektor< T, 3 > &hrsq, FT &grn, FT2 *grnI, double alpha, double eps)
Detailed Description
template<>
struct SpecializedGreensFunction< 3 >
Definition at line 28 of file FFTBoxPoissonSolver.cpp.
Member Function Documentation
calculate() [1/3]
template<class T , class FT , class FT2 > static void SpecializedGreensFunction< 3 >::calculate (Vektor< T, 3 > & hrsq, FT & grn, FT2 * grnI) inline static
Definition at line 30 of file FFTBoxPoissonSolver.cpp.
References sqrt().
calculate() [2/3]
template<class T , class FT , class FT2 > static void SpecializedGreensFunction< 3 >::calculate (Vektor< T, 3 > & hrsq, FT & grn, FT2 * grnI) inline static
Definition at line 38 of file FFTPoissonSolver.cpp.
References sqrt().
calculate() [3/3]
template<class T , class FT , class FT2 > static void SpecializedGreensFunction< 3 >::calculate (Vektor< T, 3 > & hrsq, FT & grn, FT2 * grnI, double alpha, double eps) inline static
Definition at line 51 of file P3MPoissonSolver.cpp.
References Physics::alpha, erf(), ke, min(), real(), and sqrt().
The documentation for this struct was generated from the following files:
src/Solvers/FFTBoxPoissonSolver.cpp
src/Solvers/FFTPoissonSolver.cpp
src/Solvers/P3MPoissonSolver.cpp