OPAL (Object Oriented Parallel Accelerator Library): Vnode< Dim > Class Template Reference
Vnode< Dim > Class Template Reference
#include <Vnode.h>
Public Member Functions
Vnode ()
Vnode (const NDIndex< Dim > &domain, int node, int vnode=-1)
Vnode (const Vnode< Dim > &vn)
Vnode< Dim > & operator= (const Vnode< Dim > &vn)
int getNode () const
int getVnode () const
const NDIndex< Dim > & getDomain () const
Message & putMessage (Message &m) const
Message & getMessage (Message &m)
Public Member Functions inherited from RefCounted
RefCounted ()
Private Attributes
NDIndex< Dim > Domain
int Node
int vnode_m
Additional Inherited Members
Public Attributes inherited from RefCounted
int RefCount
Detailed Description
template<unsigned Dim>
class Vnode< Dim >
Definition at line 18 of file Vnode.h.
Constructor & Destructor Documentation
Vnode() [1/3]
template<unsigned Dim> Vnode< Dim >::Vnode () inline
Definition at line 47 of file Vnode.h.
Vnode() [2/3]
template<unsigned Dim> Vnode< Dim >::Vnode (const NDIndex< Dim > & domain, int node, int vnode = -1) inline
Definition at line 50 of file Vnode.h.
Vnode() [3/3]
template<unsigned Dim> Vnode< Dim >::Vnode (const Vnode< Dim > & vn) inline
Definition at line 54 of file Vnode.h.
Member Function Documentation
getDomain()
template<unsigned Dim> const NDIndex<Dim>& Vnode< Dim >::getDomain (void) const inline
Definition at line 67 of file Vnode.h.
References Vnode< Dim >::Domain.
Referenced by FieldLayout< Dim >::FieldLayout(), FieldLayout< Dim >::getLocalNDIndex(), LSIndex< Dim >::LSIndex(), and FieldLayout< Dim >::write().
getMessage()
template<unsigned Dim> Message& Vnode< Dim >::getMessage (Message & m) inline
Definition at line 78 of file Vnode.h.
References Vnode< Dim >::Domain, Message::get(), Vnode< Dim >::Node, and Vnode< Dim >::vnode_m.
Referenced by FieldLayout< Dim >::FieldLayout().
getNode()
template<unsigned Dim> int Vnode< Dim >::getNode () const inline
Definition at line 65 of file Vnode.h.
References Vnode< Dim >::Node.
Referenced by FieldLayout< Dim >::getLocalNDIndex(), FieldLayout< Dim >::read(), and FieldLayout< Dim >::write().
getVnode()
template<unsigned Dim> int Vnode< Dim >::getVnode () const inline
Definition at line 66 of file Vnode.h.
References Vnode< Dim >::vnode_m.
Referenced by FieldLayout< Dim >::FieldLayout(), and FieldLayout< Dim >::write().
operator=()
template<unsigned Dim> Vnode<Dim>& Vnode< Dim >::operator= (const Vnode< Dim > & vn) inline
Definition at line 58 of file Vnode.h.
References Vnode< Dim >::Domain, Vnode< Dim >::Node, and Vnode< Dim >::vnode_m.
putMessage()
template<unsigned Dim> Message& Vnode< Dim >::putMessage (Message & m) const inline
Definition at line 70 of file Vnode.h.
References Vnode< Dim >::Domain, Vnode< Dim >::Node, Message::put(), and Vnode< Dim >::vnode_m.
Member Data Documentation
Domain
template<unsigned Dim> NDIndex<Dim> Vnode< Dim >::Domain private
Definition at line 41 of file Vnode.h.
Referenced by Vnode< Dim >::getDomain(), Vnode< Dim >::getMessage(), Vnode< Dim >::operator=(), and Vnode< Dim >::putMessage().
Node
template<unsigned Dim> int Vnode< Dim >::Node private
Definition at line 42 of file Vnode.h.
Referenced by Vnode< Dim >::getMessage(), Vnode< Dim >::getNode(), Vnode< Dim >::operator=(), and Vnode< Dim >::putMessage().
vnode_m
template<unsigned Dim> int Vnode< Dim >::vnode_m private
Definition at line 43 of file Vnode.h.
Referenced by Vnode< Dim >::getMessage(), Vnode< Dim >::getVnode(), Vnode< Dim >::operator=(), and Vnode< Dim >::putMessage().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/FieldLayout/Vnode.h