OPAL (Object Oriented Parallel Accelerator Library): IfStatement Class Reference
IfStatement Class Reference
If statement.
#include <IfStatement.h>
Public Member Functions
IfStatement (const Parser &, TokenStream &)
Constructor.
virtual ~IfStatement ()
virtual void execute (const Parser &)
Execute.
Public Member Functions inherited from Statement
Statement (const std::string &name, int line)
Constructor.
Statement (const std::string &name, TokenList &)
Constructor.
virtual ~Statement ()
void append (const Token &)
Append a token.
bool atEnd () const
Test for end of command.
bool boolean (bool &value)
Return boolean value.
bool delimiter (char c)
Test for delimiter.
bool delimiter (const char *s)
Test for delimiter choice.
Token & getCurrent ()
Return current token and skip it.
bool integer (int &value)
Return signed integer.
bool integer (unsigned &value)
Return unsigned integer.
bool keyword (const char *s)
Test for keyword.
bool real (double &value)
Return real value.
bool str (std::string &value)
Return string value.
bool word (std::string &value)
Return word value.
void mark ()
Mark position in command.
void restore ()
Return to marked position.
void start ()
Return to start.
void skip ()
Skip.
unsigned int position () const
Return current character number in line.
virtual void print (std::ostream &os) const
Print statement.
virtual void printWhere (Inform &msg, bool withToken) const
Print position.
std::string str () const
Private Member Functions
IfStatement ()
IfStatement (const IfStatement &)
void operator= (const IfStatement &)
Private Attributes
Statement * then_block
Statement * else_block
Additional Inherited Members
Public Types inherited from Statement
typedef std::list< Token > TokenList
The type of the enclosed token list.
Protected Attributes inherited from Statement
int stat_line
std::string buffer_name
TokenList tokens
TokenList::iterator curr
TokenList::iterator keep
Detailed Description
If statement.
Definition at line 35 of file IfStatement.h.
Constructor & Destructor Documentation
IfStatement() [1/3]
IfStatement::IfStatement (const Parser & parser, TokenStream & is)
Constructor.
Definition at line 35 of file IfStatement.cpp.
References Statement::append(), else_block, Token::isDel(), Token::isEOF(), Token::isKey(), TokenStream::putBack(), Parser::readStatement(), TokenStream::readToken(), and then_block.
~IfStatement()
IfStatement::~IfStatement () virtual
Definition at line 73 of file IfStatement.cpp.
References else_block, and then_block.
IfStatement() [2/3]
IfStatement::IfStatement () private
IfStatement() [3/3]
IfStatement::IfStatement (const IfStatement &) private
Member Function Documentation
execute()
void IfStatement::execute (const Parser & parser) virtual
Execute.
Implements Statement.
Definition at line 79 of file IfStatement.cpp.
References else_block, ERRORMSG, Statement::execute(), Attributes::getBool(), OpalData::getInstance(), Attributes::makeBool(), Attribute::parse(), Statement::print(), Statement::start(), then_block, and OpalData::update().
operator=()
void IfStatement::operator= (const IfStatement &) private
Member Data Documentation
else_block
Statement* IfStatement::else_block private
Definition at line 57 of file IfStatement.h.
Referenced by execute(), IfStatement(), and ~IfStatement().
then_block
Statement* IfStatement::then_block private
Definition at line 56 of file IfStatement.h.
Referenced by execute(), IfStatement(), and ~IfStatement().
The documentation for this class was generated from the following files:
src/OpalParser/IfStatement.h
src/OpalParser/IfStatement.cpp