OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Index/SIndex.hpp File Reference
SIndex.hpp File Reference
#include "Index/SIndex.h"
#include "Index/IndexedSIndex.h"
#include "FieldLayout/FieldLayout.h"
#include "Utility/PAssert.h"
Functions
template<unsigned int Dim>
std::ostream & operator<< (std::ostream &o, const SIndex< Dim > &si)
Function Documentation
operator<<()
template<unsigned int Dim> std::ostream& operator<< (std::ostream & o, const SIndex< Dim > & si)
Definition at line 741 of file SIndex.hpp.
References a, SIndex< Dim >::begin_iv(), SIndex< Dim >::end_iv(), endl(), SIndex< Dim >::getDomain(), SIndex< Dim >::getOffset(), and SIndex< Dim >::size_iv().