OPAL (Object Oriented Parallel Accelerator Library): DefaultVisitor Class Reference
DefaultVisitor Class Reference abstract
#include <DefaultVisitor.h>
Public Member Functions
DefaultVisitor (const Beamline &beamline, bool backBeam, bool backTrack)
Constructor.
virtual ~DefaultVisitor ()=0
virtual void execute ()
Apply the algorithm to the top-level beamline.
virtual void visitBeamline (const Beamline &)
Apply the algorithm to a beam line.
virtual void visitCCollimator (const CCollimator &)
Apply the algorithm to a collimator.
virtual void visitComponent (const Component &)
Apply the algorithm to an arbitrary component.
virtual void visitCorrector (const Corrector &)
Apply the algorithm to a closed orbit corrector.
virtual void visitCyclotron (const Cyclotron &)
Apply the algorithm to an cyclotron.
virtual void visitDegrader (const Degrader &)
Apply the algorithm to a degrader.
virtual void visitDrift (const Drift &)
Apply the algorithm to a drift space.
virtual void visitFlaggedElmPtr (const FlaggedElmPtr &)
Apply the algorithm to a FlaggedElmPtr.
virtual void visitFlexibleCollimator (const FlexibleCollimator &)
Apply the algorithm to a flexible collimator.
virtual void visitMarker (const Marker &)
Apply the algorithm to a marker.
virtual void visitMonitor (const Monitor &)
Apply the algorithm to a beam position monitor.
virtual void visitMultipole (const Multipole &)
Apply the algorithm to a multipole.
virtual void visitMultipoleT (const MultipoleT &)
Apply the algorithm to to an arbitrary multipole.
virtual void visitOffset (const Offset &)
Apply the algorithm to an offset (placement).
virtual void visitOutputPlane (const OutputPlane &)
Apply the algorithm to an output plane.
virtual void visitProbe (const Probe &prob)
Apply the algorithm to a probe.
virtual void visitRBend (const RBend &)
Apply the algorithm to a rectangular bend.
virtual void visitRBend3D (const RBend3D &)
Apply the algorithm to a rectangular bend.
virtual void visitRFCavity (const RFCavity &)
Apply the algorithm to a RF cavity.
virtual void visitRing (const Ring &)
Apply the algorithm to a ring.
virtual void visitSBend (const SBend &)
Apply the algorithm to a sector bend.
virtual void visitSBend3D (const SBend3D &)
Apply the algorithm to a sector bend with 3D field map.
virtual void visitScalingFFAMagnet (const ScalingFFAMagnet &)
Apply the algorithm to a scaling FFA magnet.
virtual void visitSeptum (const Septum &)
Apply the algorithm to a septum.
virtual void visitSolenoid (const Solenoid &)
Apply the algorithm to a solenoid.
virtual void visitSource (const Source &)
Apply the algorithm to a source.
virtual void visitStripper (const Stripper &)
Apply the algorithm to a particle stripper.
virtual void visitTravelingWave (const TravelingWave &)
Apply the algorithm to a traveling wave.
virtual void visitVacuum (const Vacuum &)
Apply the algorithm to a vacuum space.
virtual void visitVariableRFCavity (const VariableRFCavity &vcav)
Apply the algorithm to a a variable RF cavity.
virtual void visitVariableRFCavityFringeField (const VariableRFCavityFringeField &vcav)
Apply the algorithm to a a variable RF cavity with Fringe Field.
virtual void visitVerticalFFAMagnet (const VerticalFFAMagnet &)
Apply the algorithm to a vertical FFA magnet.
Public Member Functions inherited from BeamlineVisitor
BeamlineVisitor ()
virtual ~BeamlineVisitor ()
Protected Attributes
const Beamline & itsLine
bool back_beam
bool back_track
bool back_path
double flip_B
double flip_s
Private Member Functions
DefaultVisitor ()
DefaultVisitor (const DefaultVisitor &)
void operator= (const DefaultVisitor &)
virtual void applyDefault (const ElementBase &)
Private Attributes
bool local_flip
Detailed Description
Definition at line 30 of file DefaultVisitor.h.
Constructor & Destructor Documentation
DefaultVisitor() [1/3]
DefaultVisitor::DefaultVisitor (const Beamline & beamline, bool backBeam, bool backTrack)
Constructor.
Definition at line 65 of file DefaultVisitor.cpp.
References back_beam, back_path, back_track, flip_B, flip_s, and local_flip.
~DefaultVisitor()
DefaultVisitor::~DefaultVisitor () pure virtual
Definition at line 75 of file DefaultVisitor.cpp.
DefaultVisitor() [2/3]
DefaultVisitor::DefaultVisitor () private
DefaultVisitor() [3/3]
DefaultVisitor::DefaultVisitor (const DefaultVisitor &) private
Member Function Documentation
applyDefault()
void DefaultVisitor::applyDefault (const ElementBase &) private virtual
Definition at line 231 of file DefaultVisitor.cpp.
Referenced by visitCCollimator(), visitComponent(), visitCorrector(), visitCyclotron(), visitDegrader(), visitDrift(), visitFlexibleCollimator(), visitMarker(), visitMonitor(), visitMultipole(), visitMultipoleT(), visitOffset(), visitOutputPlane(), visitProbe(), visitRBend(), visitRBend3D(), visitRFCavity(), visitRing(), visitSBend(), visitSBend3D(), visitScalingFFAMagnet(), visitSeptum(), visitSolenoid(), visitSource(), visitStripper(), visitTravelingWave(), visitVacuum(), visitVariableRFCavity(), and visitVerticalFFAMagnet().
execute()
void DefaultVisitor::execute () virtual
Apply the algorithm to the top-level beamline.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelTTracker, ParallelCyclotronTracker, Selector, and RangeSelector.
Definition at line 79 of file DefaultVisitor.cpp.
References ElementBase::accept(), back_beam, back_track, itsLine, and local_flip.
Referenced by RangeSelector::execute(), Line::replace(), Sequence::replace(), and Select::select().
operator=()
void DefaultVisitor::operator= (const DefaultVisitor &) private
visitBeamline()
void DefaultVisitor::visitBeamline (const Beamline & bl) virtual
Apply the algorithm to a beam line.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelTTracker, and ParallelCyclotronTracker.
Definition at line 213 of file DefaultVisitor.cpp.
References Beamline::iterate(), and local_flip.
visitCCollimator()
void DefaultVisitor::visitCCollimator (const CCollimator & coll) virtual
Apply the algorithm to a collimator.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelTTracker, and ParallelCyclotronTracker.
Definition at line 85 of file DefaultVisitor.cpp.
References applyDefault().
visitComponent()
void DefaultVisitor::visitComponent (const Component & comp) virtual
Apply the algorithm to an arbitrary component.
Implements BeamlineVisitor.
Reimplemented in Tracker.
Definition at line 89 of file DefaultVisitor.cpp.
References applyDefault().
visitCorrector()
void DefaultVisitor::visitCorrector (const Corrector & corr) virtual
Apply the algorithm to a closed orbit corrector.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelTTracker, and ParallelCyclotronTracker.
Definition at line 93 of file DefaultVisitor.cpp.
References applyDefault().
visitCyclotron()
void DefaultVisitor::visitCyclotron (const Cyclotron & cyc) virtual
Apply the algorithm to an cyclotron.
Implements BeamlineVisitor.
Reimplemented in ParallelCyclotronTracker.
Definition at line 97 of file DefaultVisitor.cpp.
References applyDefault().
visitDegrader()
void DefaultVisitor::visitDegrader (const Degrader & deg) virtual
Apply the algorithm to a degrader.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelTTracker, and ParallelCyclotronTracker.
Definition at line 101 of file DefaultVisitor.cpp.
References applyDefault(), and matheval::detail::math::deg().
visitDrift()
void DefaultVisitor::visitDrift (const Drift & drf) virtual
Apply the algorithm to a drift space.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelTTracker, and ParallelCyclotronTracker.
Definition at line 105 of file DefaultVisitor.cpp.
References applyDefault().
visitFlaggedElmPtr()
void DefaultVisitor::visitFlaggedElmPtr (const FlaggedElmPtr & fep) virtual
Apply the algorithm to a FlaggedElmPtr.
Implements BeamlineVisitor.
Reimplemented in Replacer, RangeSelector, and Flagger.
Definition at line 220 of file DefaultVisitor.cpp.
References ElementBase::accept(), ElmPtr::getElement(), FlaggedElmPtr::getReflectionFlag(), and local_flip.
Referenced by RangeSelector::handleBeamline(), RangeSelector::handleElement(), Flagger::visitFlaggedElmPtr(), and Replacer::visitFlaggedElmPtr().
visitFlexibleCollimator()
void DefaultVisitor::visitFlexibleCollimator (const FlexibleCollimator & coll) virtual
Apply the algorithm to a flexible collimator.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelTTracker, and ParallelCyclotronTracker.
Definition at line 109 of file DefaultVisitor.cpp.
References applyDefault().
visitMarker()
void DefaultVisitor::visitMarker (const Marker & mark) virtual
Apply the algorithm to a marker.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelTTracker, and ParallelCyclotronTracker.
Definition at line 113 of file DefaultVisitor.cpp.
References applyDefault().
visitMonitor()
void DefaultVisitor::visitMonitor (const Monitor & mon) virtual
Apply the algorithm to a beam position monitor.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelTTracker, and ParallelCyclotronTracker.
Definition at line 117 of file DefaultVisitor.cpp.
References applyDefault().
visitMultipole()
void DefaultVisitor::visitMultipole (const Multipole & mult) virtual
Apply the algorithm to a multipole.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelTTracker, and ParallelCyclotronTracker.
Definition at line 121 of file DefaultVisitor.cpp.
References applyDefault().
visitMultipoleT()
void DefaultVisitor::visitMultipoleT (const MultipoleT & multT) virtual
Apply the algorithm to to an arbitrary multipole.
Implements BeamlineVisitor.
Reimplemented in ParallelTTracker, and ParallelCyclotronTracker.
Definition at line 125 of file DefaultVisitor.cpp.
References applyDefault().
visitOffset()
void DefaultVisitor::visitOffset (const Offset & off) virtual
Apply the algorithm to an offset (placement).
Implements BeamlineVisitor.
Reimplemented in ParallelCyclotronTracker.
Definition at line 129 of file DefaultVisitor.cpp.
References applyDefault().
visitOutputPlane()
void DefaultVisitor::visitOutputPlane (const OutputPlane & out) virtual
Apply the algorithm to an output plane.
Implements BeamlineVisitor.
Reimplemented in ParallelCyclotronTracker.
Definition at line 133 of file DefaultVisitor.cpp.
References applyDefault().
visitProbe()
void DefaultVisitor::visitProbe (const Probe & prob) virtual
Apply the algorithm to a probe.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelCyclotronTracker, and ParallelTTracker.
Definition at line 137 of file DefaultVisitor.cpp.
References applyDefault().
visitRBend()
void DefaultVisitor::visitRBend (const RBend & bend) virtual
Apply the algorithm to a rectangular bend.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelCyclotronTracker, and ParallelTTracker.
Definition at line 141 of file DefaultVisitor.cpp.
References applyDefault().
visitRBend3D()
void DefaultVisitor::visitRBend3D (const RBend3D & bend) virtual
Apply the algorithm to a rectangular bend.
Reimplemented from BeamlineVisitor.
Reimplemented in ParallelTTracker.
Definition at line 145 of file DefaultVisitor.cpp.
References applyDefault().
visitRFCavity()
void DefaultVisitor::visitRFCavity (const RFCavity & cav) virtual
Apply the algorithm to a RF cavity.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelTTracker, and ParallelCyclotronTracker.
Definition at line 149 of file DefaultVisitor.cpp.
References applyDefault().
visitRing()
void DefaultVisitor::visitRing (const Ring & ring) virtual
Apply the algorithm to a ring.
Implements BeamlineVisitor.
Reimplemented in ParallelCyclotronTracker.
Definition at line 153 of file DefaultVisitor.cpp.
References applyDefault().
visitSBend()
void DefaultVisitor::visitSBend (const SBend & bend) virtual
Apply the algorithm to a sector bend.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelCyclotronTracker, and ParallelTTracker.
Definition at line 157 of file DefaultVisitor.cpp.
References applyDefault().
visitSBend3D()
void DefaultVisitor::visitSBend3D (const SBend3D & bend) virtual
Apply the algorithm to a sector bend with 3D field map.
Implements BeamlineVisitor.
Reimplemented in ParallelCyclotronTracker.
Definition at line 161 of file DefaultVisitor.cpp.
References applyDefault().
visitScalingFFAMagnet()
void DefaultVisitor::visitScalingFFAMagnet (const ScalingFFAMagnet & spiral) virtual
Apply the algorithm to a scaling FFA magnet.
Implements BeamlineVisitor.
Reimplemented in ParallelCyclotronTracker.
Definition at line 165 of file DefaultVisitor.cpp.
References applyDefault().
visitSeptum()
void DefaultVisitor::visitSeptum (const Septum & sept) virtual
Apply the algorithm to a septum.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelCyclotronTracker, and ParallelTTracker.
Definition at line 169 of file DefaultVisitor.cpp.
References applyDefault().
visitSolenoid()
void DefaultVisitor::visitSolenoid (const Solenoid & sol) virtual
Apply the algorithm to a solenoid.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelCyclotronTracker, and ParallelTTracker.
Definition at line 173 of file DefaultVisitor.cpp.
References applyDefault().
visitSource()
void DefaultVisitor::visitSource (const Source & sou) virtual
Apply the algorithm to a source.
Implements BeamlineVisitor.
Reimplemented in ParallelTTracker.
Definition at line 177 of file DefaultVisitor.cpp.
References applyDefault().
visitStripper()
void DefaultVisitor::visitStripper (const Stripper & stripper) virtual
Apply the algorithm to a particle stripper.
Implements BeamlineVisitor.
Reimplemented in ParallelCyclotronTracker.
Definition at line 181 of file DefaultVisitor.cpp.
References applyDefault().
visitTravelingWave()
void DefaultVisitor::visitTravelingWave (const TravelingWave & trw) virtual
Apply the algorithm to a traveling wave.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, and ParallelTTracker.
Definition at line 185 of file DefaultVisitor.cpp.
References applyDefault().
visitVacuum()
void DefaultVisitor::visitVacuum (const Vacuum & vac) virtual
Apply the algorithm to a vacuum space.
Implements BeamlineVisitor.
Reimplemented in ThickTracker, ParallelCyclotronTracker, and ParallelTTracker.
Definition at line 195 of file DefaultVisitor.cpp.
References applyDefault().
visitVariableRFCavity()
void DefaultVisitor::visitVariableRFCavity (const VariableRFCavity & vcav) virtual
Apply the algorithm to a a variable RF cavity.
Implements BeamlineVisitor.
Reimplemented in ParallelCyclotronTracker.
Definition at line 199 of file DefaultVisitor.cpp.
References applyDefault().
visitVariableRFCavityFringeField()
void DefaultVisitor::visitVariableRFCavityFringeField (const VariableRFCavityFringeField & vcav) virtual
Apply the algorithm to a a variable RF cavity with Fringe Field.
Implements BeamlineVisitor.
Reimplemented in ParallelCyclotronTracker.
Definition at line 204 of file DefaultVisitor.cpp.
visitVerticalFFAMagnet()
void DefaultVisitor::visitVerticalFFAMagnet (const VerticalFFAMagnet & mag) virtual
Apply the algorithm to a vertical FFA magnet.
Implements BeamlineVisitor.
Reimplemented in ParallelCyclotronTracker.
Definition at line 208 of file DefaultVisitor.cpp.
References applyDefault().
Member Data Documentation
back_beam
bool DefaultVisitor::back_beam protected
Definition at line 155 of file DefaultVisitor.h.
Referenced by DefaultVisitor(), execute(), and Tracker::visitComponent().
back_path
bool DefaultVisitor::back_path protected
Definition at line 157 of file DefaultVisitor.h.
Referenced by DefaultVisitor().
back_track
bool DefaultVisitor::back_track protected
Definition at line 156 of file DefaultVisitor.h.
Referenced by DefaultVisitor(), execute(), ParallelTTracker::execute(), ParallelTTracker::findStartPosition(), ParallelTTracker::updateReferenceParticle(), and Tracker::visitComponent().
flip_B
double DefaultVisitor::flip_B protected
Definition at line 160 of file DefaultVisitor.h.
Referenced by DefaultVisitor().
flip_s
double DefaultVisitor::flip_s protected
Definition at line 161 of file DefaultVisitor.h.
Referenced by DefaultVisitor().
itsLine
const Beamline& DefaultVisitor::itsLine protected
Definition at line 152 of file DefaultVisitor.h.
Referenced by execute().
local_flip
bool DefaultVisitor::local_flip private
Definition at line 176 of file DefaultVisitor.h.
Referenced by DefaultVisitor(), execute(), visitBeamline(), and visitFlaggedElmPtr().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algorithms/DefaultVisitor.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algorithms/DefaultVisitor.cpp