OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Field/ReductionLoc.hpp File Reference
ReductionLoc.hpp File Reference
#include "Field/ReductionLoc.h"
#include "Index/NDIndex.h"
#include "Field/AssignDefs.h"
#include "Message/Message.h"
#include "Message/GlobalComm.h"
Classes
struct ReduceLoc< T, LOC >
Functions
template<class T1 , class T2 , class LOC >
ReduceLoc< typename PETEBinaryReturn< T1, T2, FnMin >::type, LOC > Min (const ReduceLoc< T1, LOC > &lhs, const ReduceLoc< T2, LOC > &rhs)
template<class T1 , class T2 , class LOC >
ReduceLoc< typename PETEBinaryReturn< T1, T2, FnMax >::type, LOC > Max (const ReduceLoc< T1, LOC > &lhs, const ReduceLoc< T2, LOC > &rhs)
template<class T , class CompOp , class AccOp , unsigned D>
T::PETE_Return_t Reduction (const PETE_Expr< T > &const_expr, CompOp comp_op, AccOp acc_op, NDIndex< D > &loc)
Function Documentation
Max()
template<class T1 , class T2 , class LOC > ReduceLoc<typename PETEBinaryReturn<T1,T2,FnMax>::type, LOC> Max (const ReduceLoc< T1, LOC > & lhs, const ReduceLoc< T2, LOC > & rhs) inline
Definition at line 80 of file ReductionLoc.hpp.
References ReduceLoc< T, LOC >::Loc, and ReduceLoc< T, LOC >::Val.
Min()
template<class T1 , class T2 , class LOC > ReduceLoc<typename PETEBinaryReturn<T1,T2,FnMin>::type, LOC> Min (const ReduceLoc< T1, LOC > & lhs, const ReduceLoc< T2, LOC > & rhs) inline
Definition at line 68 of file ReductionLoc.hpp.
References ReduceLoc< T, LOC >::Loc, and ReduceLoc< T, LOC >::Val.
Reduction()
template<class T , class CompOp , class AccOp , unsigned D> T::PETE_Return_t Reduction (const PETE_Expr< T > & const_expr, CompOp comp_op, AccOp acc_op, NDIndex< D > & loc)
Definition at line 94 of file ReductionLoc.hpp.
References for_each(), ReduceLoc< T, LOC >::Loc, Hypervolume::n, PETE_apply(), PETE_Expr< WrappedExpr >::PETE_unwrap(), Attrib::Distribution::R, reduce_masked(), and ReduceLoc< T, LOC >::Val.
Referenced by any(), bounds(), max(), min(), minmax(), and where().