OPAL (Object Oriented Parallel Accelerator Library): BareField< T, Dim > Class Template Reference
BareField< T, Dim > Class Template Reference
#include <FFT.h>
Public Types
enum { Dim_u = Dim }
enum { IsExpr = 0 }
typedef T T_t
typedef FieldLayout< Dim > Layout_t
typedef LField< T, Dim > LField_t
typedef vmap< typename Unique::type, my_auto_ptr< LField< T, Dim > > > ac_id_larray
typedef ac_id_larray::iterator iterator_if
typedef ac_id_larray::const_iterator const_iterator_if
typedef LField< T, Dim >::iterator LFI
typedef BareFieldIterator< T, Dim > iterator
typedef iterator PETE_Expr_t
Public Types inherited from User
typedef Unique::type ID_t
Public Types inherited from PETE_Expr< BareField< T, Dim > >
typedef BareField< T, Dim > Wrapped
Public Member Functions
BareField ()
BareField (const BareField< T, Dim > &)
BareField (Layout_t &)
BareField (Layout_t &, const GuardCellSizes< Dim > &)
~BareField ()
void initialize (Layout_t &)
void initialize (Layout_t &, const bool)
void initialize (Layout_t &, const GuardCellSizes< Dim > &)
iterator_if begin_if ()
iterator_if end_if ()
const_iterator_if begin_if () const
const_iterator_if end_if () const
ac_id_larray::size_type size_if () const
virtual void fillGuardCells (bool reallyFill=true) const
void setGuardCells (const T &) const
void accumGuardCells ()
bool isDirty () const
void setDirtyFlag ()
void clearDirtyFlag ()
void fillGuardCellsIfNotDirty () const
Layout_t & getLayout () const
IndexedBareField< T, Dim, 1 > operator[] (const Index &idx)
IndexedBareField< T, Dim, 1 > operator[] (int i)
IndexedBareField< T, Dim, Dim > operator[] (const NDIndex< Dim > &nidx)
SubBareField< T, Dim, SIndex< Dim > > operator[] (const SIndex< Dim > &)
const GuardCellSizes< Dim > & getGC () const
const GuardCellSizes< Dim > & getGuardCellSizes () const
unsigned leftGuard (unsigned d) const
unsigned rightGuard (unsigned d) const
const Index & getIndex (unsigned d) const
const NDIndex< Dim > & getDomain () const
const BareField< T, Dim > & operator= (T x)
const BareField< T, Dim > & operator= (const BareField< T, Dim > &x)
template<class X >
const BareField< T, Dim > & operator= (const BareField< X, Dim > &x)
template<class B >
const BareField< T, Dim > & operator= (const PETE_Expr< B > &x)
bool compressible () const
double CompressedFraction () const
void Compress () const
void Uncompress () const
void setCompression (bool compress)
virtual void Repartition (UserList *)
virtual void notifyUserOfDelete (UserList *)
iterator begin () const
iterator end () const
iterator beginLoc (const FieldLoc< Dim > &loc) const
void prepareForScalarCode (bool tryfill=true)
void finishScalarCode (bool modified=true)
T & localElement (const NDIndex< Dim > &) const
void getsingle (const NDIndex< Dim > &, T &) const
void write (std::ostream &)
iterator MakeExpression () const
Public Member Functions inherited from FieldLayoutUser
FieldLayoutUser ()
virtual ~FieldLayoutUser ()
Public Member Functions inherited from User
User ()
virtual ~User ()
ID_t get_Id () const
Public Member Functions inherited from PETE_Expr< BareField< T, Dim > >
BareField< T, Dim > & PETE_unwrap ()
const BareField< T, Dim > & PETE_unwrap () const
Protected Attributes
ac_id_larray Locals_ac
Protected Attributes inherited from User
ID_t Id
Private Member Functions
void setup ()
void getsingle_bc (const NDIndex< Dim > &, T &) const
Private Attributes
Layout_t * Layout
GuardCellSizes< Dim > Gc
bool dirty_m
bool compressible_m
bool pinned
Friends
class BareFieldIterator< T, Dim >
Detailed Description
template<class T, unsigned Dim>
class BareField< T, Dim >
The FFT class performs complex-to-complex, real-to-complex, or sine transforms on IPPL Fields. FFT is templated on the type of transform to be performed, the dimensionality of the Field to transform, and the floating-point precision type of the Field (float or double).
Definition at line 26 of file FFT.h.
Member Typedef Documentation
ac_id_larray
template<class T, unsigned Dim> typedef vmap< typename Unique::type, my_auto_ptr< LField<T,Dim> > > BareField< T, Dim >::ac_id_larray
Definition at line 91 of file BareField.h.
const_iterator_if
template<class T, unsigned Dim> typedef ac_id_larray::const_iterator BareField< T, Dim >::const_iterator_if
Definition at line 93 of file BareField.h.
iterator
template<class T, unsigned Dim> typedef BareFieldIterator<T,Dim> BareField< T, Dim >::iterator
Definition at line 97 of file BareField.h.
iterator_if
template<class T, unsigned Dim> typedef ac_id_larray::iterator BareField< T, Dim >::iterator_if
Definition at line 92 of file BareField.h.
Layout_t
template<class T, unsigned Dim> typedef FieldLayout<Dim> BareField< T, Dim >::Layout_t
Definition at line 61 of file BareField.h.
LFI
template<class T, unsigned Dim> typedef LField<T,Dim>::iterator BareField< T, Dim >::LFI
Definition at line 94 of file BareField.h.
LField_t
template<class T, unsigned Dim> typedef LField<T,Dim> BareField< T, Dim >::LField_t
Definition at line 62 of file BareField.h.
PETE_Expr_t
template<class T, unsigned Dim> typedef iterator BareField< T, Dim >::PETE_Expr_t
Definition at line 326 of file BareField.h.
T_t
template<class T, unsigned Dim> typedef T BareField< T, Dim >::T_t
Definition at line 60 of file BareField.h.
Member Enumeration Documentation
anonymous enum
template<class T, unsigned Dim> anonymous enum
Enumerator
Dim_u
Definition at line 63 of file BareField.h.
anonymous enum
template<class T, unsigned Dim> anonymous enum
Enumerator
IsExpr
Definition at line 325 of file BareField.h.
Constructor & Destructor Documentation
BareField() [1/4]
template<class T , unsigned Dim> BareField< T, Dim >::BareField () inline
Definition at line 369 of file BareField.h.
BareField() [2/4]
template<class T, unsigned Dim> BareField< T, Dim >::BareField (const BareField< T, Dim > & a)
Definition at line 48 of file BareField.hpp.
BareField() [3/4]
template<class T, unsigned Dim> BareField< T, Dim >::BareField (Layout_t & l) inline
Definition at line 385 of file BareField.h.
BareField() [4/4]
template<class T, unsigned Dim> BareField< T, Dim >::BareField (Layout_t & l, const GuardCellSizes< Dim > & g) inline
Definition at line 402 of file BareField.h.
~BareField()
template<class T , unsigned Dim> BareField< T, Dim >::~BareField ()
Definition at line 83 of file BareField.hpp.
Member Function Documentation
accumGuardCells()
template<class T , unsigned Dim> void BareField< T, Dim >::accumGuardCells ()
Definition at line 698 of file BareField.hpp.
Referenced by ParticleAttrib< ParticleOrigin >::scatter(), and scatter().
begin()
template<class T, unsigned Dim> iterator BareField< T, Dim >::begin () const inline
Definition at line 234 of file BareField.h.
Referenced by PatchBC< T, D, M, C >::apply(), assign(), UniformCartesian< Dim, MFLOAT >::getCellPositionField(), Cartesian< Dim, MFLOAT >::getCellPositionField(), Cartesian< Dim, MFLOAT >::getCellVolumeField(), Cartesian< Dim, MFLOAT >::getDeltaCellField(), Cartesian< Dim, MFLOAT >::getDeltaVertexField(), UniformCartesian< Dim, MFLOAT >::getVertexPositionField(), Cartesian< Dim, MFLOAT >::getVertexPositionField(), BareField< T1, D >::MakeExpression(), and Cartesian< Dim, MFLOAT >::storeSpacingFields().
begin_if() [1/2]
template<class T, unsigned Dim> iterator_if BareField< T, Dim >::begin_if () inline
Definition at line 100 of file BareField.h.
Referenced by ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), PatchBC< T, D, M, C >::apply(), assign(), CalcIndexedReceive(), ComponentFunctionFaceBCApply(), ComponentLinearExtrapolateFaceBCApply(), BareField< T1, D >::Compress(), ExtrapolateAndZeroFaceBCApply(), ExtrapolateFaceBCApply(), FieldDebugWriteb(), BareField< T1, D >::fillGuardCells(), for_each(), FunctionFaceBCApply(), Interpolator::getFieldIter(), IndexedLocalAssign(), IndexedSend(), InterpolationFaceBCApply(), LinearExtrapolateFaceBCApply(), PeriodicFaceBCApply(), FieldPrint< T, Dim >::print(), FieldDebugPrint< T, Dim >::print(), DiscField< Dim >::read(), BareField< T1, D >::setGuardCells(), UniformCartesian< Dim, MFLOAT >::storeSpacingFields(), Cartesian< Dim, MFLOAT >::storeSpacingFields(), FFT< CCTransform, Dim, T >::transform(), BareField< T1, D >::Uncompress(), and DiscField< Dim >::write().
begin_if() [2/2]
template<class T, unsigned Dim> const_iterator_if BareField< T, Dim >::begin_if () const inline
Definition at line 102 of file BareField.h.
beginLoc()
template<class T, unsigned Dim> iterator BareField< T, Dim >::beginLoc (const FieldLoc< Dim > & loc) const inline
Definition at line 249 of file BareField.h.
clearDirtyFlag()
template<class T, unsigned Dim> void BareField< T, Dim >::clearDirtyFlag () inline
Definition at line 118 of file BareField.h.
Referenced by BareField< T1, D >::BareField(), and BareField< T1, D >::fillGuardCells().
Compress()
template<class T , unsigned Dim> void BareField< T, Dim >::Compress () const
Definition at line 991 of file BareField.hpp.
Referenced by assign(), ParticleAttrib< ParticleOrigin >::gather(), DiscField< Dim >::read(), and BareField< T1, D >::setCompression().
CompressedFraction()
template<class T , unsigned Dim> double BareField< T, Dim >::CompressedFraction () const
Definition at line 1021 of file BareField.hpp.
compressible()
template<class T, unsigned Dim> bool BareField< T, Dim >::compressible () const inline
Definition at line 191 of file BareField.h.
Referenced by assign(), and DiscField< Dim >::read().
end()
template<class T, unsigned Dim> iterator BareField< T, Dim >::end () const inline
Definition at line 241 of file BareField.h.
Referenced by Cartesian< Dim, MFLOAT >::storeSpacingFields().
end_if() [1/2]
template<class T, unsigned Dim> iterator_if BareField< T, Dim >::end_if () inline
Definition at line 101 of file BareField.h.
Referenced by ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), PatchBC< T, D, M, C >::apply(), assign(), ComponentFunctionFaceBCApply(), ComponentLinearExtrapolateFaceBCApply(), BareField< T1, D >::Compress(), ExtrapolateAndZeroFaceBCApply(), ExtrapolateFaceBCApply(), FieldDebugWriteb(), BareField< T1, D >::fillGuardCells(), for_each(), FunctionFaceBCApply(), Interpolator::getFieldIter(), IndexedLocalAssign(), IndexedSend(), InterpolationFaceBCApply(), LinearExtrapolateFaceBCApply(), PeriodicFaceBCApply(), FieldPrint< T, Dim >::print(), FieldDebugPrint< T, Dim >::print(), DiscField< Dim >::read(), BareField< T1, D >::setGuardCells(), UniformCartesian< Dim, MFLOAT >::storeSpacingFields(), Cartesian< Dim, MFLOAT >::storeSpacingFields(), FFT< CCTransform, Dim, T >::transform(), BareField< T1, D >::Uncompress(), and DiscField< Dim >::write().
end_if() [2/2]
template<class T, unsigned Dim> const_iterator_if BareField< T, Dim >::end_if () const inline
Definition at line 103 of file BareField.h.
fillGuardCells()
template<class T , unsigned Dim> void BareField< T, Dim >::fillGuardCells (bool reallyFill = true) const virtual
Reimplemented in Field< T, Dim, M, C >, Field< double, 3, Mesh_t, Center_t >, and Field< Vector_t, 3, Mesh_t, Center_t >.
Definition at line 297 of file BareField.hpp.
Referenced by IndexedBareFieldIterator< T, Dim >::FillGCIfNecessary(), Field< Vector_t, 3, Mesh_t, Center_t >::fillGuardCells(), BareField< T1, D >::fillGuardCellsIfNotDirty(), BareField< T1, D >::prepareForScalarCode(), FieldDebugPrint< T, Dim >::print(), UniformCartesian< Dim, MFLOAT >::storeSpacingFields(), and Cartesian< Dim, MFLOAT >::storeSpacingFields().
fillGuardCellsIfNotDirty()
template<class T, unsigned Dim> void BareField< T, Dim >::fillGuardCellsIfNotDirty () const inline
Definition at line 122 of file BareField.h.
Referenced by assign(), BareField< T1, D >::finishScalarCode(), and DiscField< Dim >::read().
finishScalarCode()
template<class T, unsigned Dim> void BareField< T, Dim >::finishScalarCode (bool modified = true) inline
Definition at line 280 of file BareField.h.
getDomain()
template<class T, unsigned Dim> const NDIndex<Dim>& BareField< T, Dim >::getDomain (void) const inline
Definition at line 152 of file BareField.h.
Referenced by ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), PatchBC< T, D, M, C >::apply(), assign(), CalcParallelInterpolationDomain(), CalcParallelPeriodicDomain(), ComponentFunctionFaceBCApply(), ComponentLinearExtrapolateFaceBCApply(), ExtrapolateAndZeroFaceBCApply(), ExtrapolateFaceBCApply(), FFTBoxPoissonSolver::FFTBoxPoissonSolver(), IndexedBareFieldIterator< T, Dim >::FillGCIfNecessary(), FunctionFaceBCApply(), InterpolationFaceBCApply(), LinearExtrapolateFaceBCApply(), PeriodicFaceBCApply(), FieldDebugPrint< T, Dim >::print(), sfp1(), sfp2(), and sfp3().
getGC()
template<class T, unsigned Dim> const GuardCellSizes<Dim>& BareField< T, Dim >::getGC () const inline
Definition at line 146 of file BareField.h.
Referenced by BareField< T1, D >::fillGuardCells(), BareField< T1, D >::leftGuard(), BareField< T1, D >::rightGuard(), and FFT< CCTransform, Dim, T >::transform().
getGuardCellSizes()
template<class T, unsigned Dim> const GuardCellSizes<Dim>& BareField< T, Dim >::getGuardCellSizes () const inline
Definition at line 147 of file BareField.h.
Referenced by ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), PatchBC< T, D, M, C >::apply(), assign(), ComponentFunctionFaceBCApply(), ComponentLinearExtrapolateFaceBCApply(), ExtrapolateAndZeroFaceBCApply(), ExtrapolateFaceBCApply(), FunctionFaceBCApply(), InterpolationFaceBCApply(), LinearExtrapolateFaceBCApply(), PeriodicFaceBCApply(), FieldDebugPrint< T, Dim >::print(), UniformCartesian< Dim, MFLOAT >::storeSpacingFields(), and Cartesian< Dim, MFLOAT >::storeSpacingFields().
getIndex()
template<class T, unsigned Dim> const Index& BareField< T, Dim >::getIndex (unsigned d) const inline
Definition at line 151 of file BareField.h.
getLayout()
template<class T, unsigned Dim> Layout_t& BareField< T, Dim >::getLayout () const inline
Definition at line 131 of file BareField.h.
Referenced by ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), assign(), BareField< T1, D >::BareField(), CalcIndexedReceive(), SubFieldTraits< T, Dim, SIndex< Dim >, NDIndex< Dim > >::construct(), SubFieldTraits< T, Dim, SIndex< Dim >, SOffset< Dim > >::construct(), FieldDebugWriteb(), IndexedBareFieldIterator< T, Dim >::FillGCIfNecessary(), BareField< T1, D >::fillGuardCells(), fp1(), fp2(), fp3(), BareField< T1, D >::getDomain(), Interpolator::getFieldIter(), BareField< T1, D >::getIndex(), ggfp1(), ggfp2(), ggfp3(), makeMesh(), DiscField< Dim >::read(), sfp1(), sfp2(), sfp3(), FFT< CCTransform, Dim, T >::transform(), and DiscField< Dim >::write().
getsingle()
template<class T, unsigned int Dim> void BareField< T, Dim >::getsingle (const NDIndex< Dim > & Indexes, T & r) const
Definition at line 1201 of file BareField.hpp.
Referenced by IndexedBareField< T, Dim, Brackets >::get().
getsingle_bc()
template<class T, unsigned D> void BareField< T, D >::getsingle_bc (const NDIndex< D > & Indexes, T & r) const private
Definition at line 1271 of file BareField.hpp.
initialize() [1/3]
template<class T , unsigned Dim> void BareField< T, Dim >::initialize (Layout_t & l)
Definition at line 100 of file BareField.hpp.
Referenced by Field< Vector_t, 3, Mesh_t, Center_t >::initialize().
initialize() [2/3]
template<class T , unsigned Dim> void BareField< T, Dim >::initialize (Layout_t & l, const bool p)
Definition at line 114 of file BareField.hpp.
initialize() [3/3]
template<class T , unsigned Dim> void BareField< T, Dim >::initialize (Layout_t & l, const GuardCellSizes< Dim > & gc)
Definition at line 128 of file BareField.hpp.
isDirty()
template<class T, unsigned Dim> bool BareField< T, Dim >::isDirty () const inline
Definition at line 116 of file BareField.h.
Referenced by assign(), BareField< T1, D >::fillGuardCellsIfNotDirty(), ParticleAttrib< ParticleOrigin >::gather(), BareField< T1, D >::prepareForScalarCode(), and FieldDebugPrint< T, Dim >::print().
leftGuard()
template<class T, unsigned Dim> unsigned BareField< T, Dim >::leftGuard (unsigned d) const inline
Definition at line 148 of file BareField.h.
Referenced by PatchBC< T, D, M, C >::apply(), CalcParallelInterpolationDomain(), CalcParallelPeriodicDomain(), ComponentFunctionFaceBCApply(), ComponentLinearExtrapolateFaceBCApply(), ExtrapolateAndZeroFaceBCApply(), ExtrapolateFaceBCApply(), FieldDebugWriteb(), FunctionFaceBCApply(), ggfp1(), ggfp2(), ggfp3(), InterpolationFaceBCApply(), LinearExtrapolateFaceBCApply(), PeriodicFaceBCApply(), sfp1(), sfp2(), sfp3(), UniformCartesian< Dim, MFLOAT >::storeSpacingFields(), and Cartesian< Dim, MFLOAT >::storeSpacingFields().
localElement()
template<class T , unsigned Dim> T & BareField< T, Dim >::localElement (const NDIndex< Dim > & Indexes) const
Definition at line 1154 of file BareField.hpp.
Referenced by MGPoissonSolver::computePotential().
MakeExpression()
template<class T, unsigned Dim> iterator BareField< T, Dim >::MakeExpression () const inline
Definition at line 327 of file BareField.h.
notifyUserOfDelete()
template<class T , unsigned Dim> void BareField< T, Dim >::notifyUserOfDelete (UserList * userlist) virtual
Implements User.
Reimplemented in Field< T, Dim, M, C >, Field< double, 3, Mesh_t, Center_t >, and Field< Vector_t, 3, Mesh_t, Center_t >.
Definition at line 1079 of file BareField.hpp.
Referenced by Field< Vector_t, 3, Mesh_t, Center_t >::notifyUserOfDelete().
operator=() [1/4]
template<class T, unsigned Dim> const BareField<T,Dim>& BareField< T, Dim >::operator= (T x) inline
Definition at line 155 of file BareField.h.
operator=() [2/4]
template<class T, unsigned Dim> const BareField<T,Dim>& BareField< T, Dim >::operator= (const BareField< T, Dim > & x) inline
Definition at line 163 of file BareField.h.
operator=() [3/4]
template<class T, unsigned Dim> template<class X > const BareField<T,Dim>& BareField< T, Dim >::operator= (const BareField< X, Dim > & x) inline
Definition at line 171 of file BareField.h.
operator=() [4/4]
template<class T, unsigned Dim> template<class B > const BareField<T,Dim>& BareField< T, Dim >::operator= (const PETE_Expr< B > & x) inline
Definition at line 180 of file BareField.h.
operator[]() [1/4]
template<class T , unsigned Dim> IndexedBareField< T, Dim, 1 > BareField< T, Dim >::operator[] (const Index & idx) inline
Definition at line 416 of file BareField.h.
operator[]() [2/4]
template<class T , unsigned Dim> IndexedBareField< T, Dim, 1 > BareField< T, Dim >::operator[] (int i) inline
Definition at line 423 of file BareField.h.
operator[]() [3/4]
template<class T , unsigned Dim> IndexedBareField< T, Dim, Dim > BareField< T, Dim >::operator[] (const NDIndex< Dim > & nidx) inline
Definition at line 430 of file BareField.h.
operator[]() [4/4]
template<class T , unsigned Dim> SubBareField< T, Dim, SIndex< Dim > > BareField< T, Dim >::operator[] (const SIndex< Dim > & s) inline
Definition at line 437 of file BareField.h.
prepareForScalarCode()
template<class T, unsigned Dim> void BareField< T, Dim >::prepareForScalarCode (bool tryfill = true) inline
Definition at line 262 of file BareField.h.
Repartition()
template<class T , unsigned Dim> void BareField< T, Dim >::Repartition (UserList * userlist) virtual
Implements FieldLayoutUser.
Reimplemented in Field< T, Dim, M, C >, Field< double, 3, Mesh_t, Center_t >, and Field< Vector_t, 3, Mesh_t, Center_t >.
Definition at line 1054 of file BareField.hpp.
rightGuard()
template<class T, unsigned Dim> unsigned BareField< T, Dim >::rightGuard (unsigned d) const inline
Definition at line 149 of file BareField.h.
Referenced by PatchBC< T, D, M, C >::apply(), CalcParallelPeriodicDomain(), ComponentFunctionFaceBCApply(), ComponentLinearExtrapolateFaceBCApply(), ExtrapolateAndZeroFaceBCApply(), ExtrapolateFaceBCApply(), FieldDebugWriteb(), FunctionFaceBCApply(), LinearExtrapolateFaceBCApply(), PeriodicFaceBCApply(), UniformCartesian< Dim, MFLOAT >::storeSpacingFields(), and Cartesian< Dim, MFLOAT >::storeSpacingFields().
setCompression()
template<class T, unsigned Dim> void BareField< T, Dim >::setCompression (bool compress) inline
Definition at line 207 of file BareField.h.
Referenced by BareField< T1, D >::finishScalarCode(), and BareField< T1, D >::prepareForScalarCode().
setDirtyFlag()
template<class T, unsigned Dim> void BareField< T, Dim >::setDirtyFlag () inline
Definition at line 117 of file BareField.h.
Referenced by assign(), BareField< T1, D >::finishScalarCode(), DiscField< Dim >::read(), and BareField< T1, D >::setGuardCells().
setGuardCells()
template<class T, unsigned Dim> void BareField< T, Dim >::setGuardCells (const T & val) const
Definition at line 616 of file BareField.hpp.
Referenced by ParticleAttrib< ParticleOrigin >::scatter(), and scatter().
setup()
template<class T , unsigned Dim> void BareField< T, Dim >::setup (void) private
Definition at line 150 of file BareField.hpp.
Referenced by BareField< T1, D >::BareField().
size_if()
template<class T, unsigned Dim> ac_id_larray::size_type BareField< T, Dim >::size_if () const inline
Definition at line 104 of file BareField.h.
Referenced by assign().
Uncompress()
template<class T , unsigned Dim> void BareField< T, Dim >::Uncompress () const
Definition at line 1005 of file BareField.hpp.
Referenced by ParticleAttrib< ParticleOrigin >::gather(), ParticleAttrib< ParticleOrigin >::scatter(), scatter(), BareField< T1, D >::setCompression(), Cartesian< Dim, MFLOAT >::storeSpacingFields(), and BareField< T1, D >::Uncompress().
write()
template<class T , unsigned Dim> void BareField< T, Dim >::write (std::ostream & out)
Definition at line 208 of file BareField.hpp.
Referenced by operator<<().
Friends And Related Function Documentation
BareFieldIterator< T, Dim >
template<class T, unsigned Dim> friend class BareFieldIterator< T, Dim > friend
Definition at line 334 of file BareField.h.
Member Data Documentation
compressible_m
template<class T, unsigned Dim> bool BareField< T, Dim >::compressible_m private
Definition at line 354 of file BareField.h.
Referenced by BareField< T1, D >::compressible(), and BareField< T1, D >::setCompression().
dirty_m
template<class T, unsigned Dim> bool BareField< T, Dim >::dirty_m private
Definition at line 351 of file BareField.h.
Referenced by BareField< T1, D >::clearDirtyFlag(), BareField< T1, D >::isDirty(), and BareField< T1, D >::setDirtyFlag().
Gc
template<class T, unsigned Dim> GuardCellSizes<Dim> BareField< T, Dim >::Gc private
Definition at line 343 of file BareField.h.
Referenced by BareField< T1, D >::BareField(), BareField< T1, D >::getGC(), and BareField< T1, D >::getGuardCellSizes().
Layout
template<class T, unsigned Dim> Layout_t* BareField< T, Dim >::Layout private
Definition at line 340 of file BareField.h.
Referenced by BareField< T1, D >::getLayout().
Locals_ac
template<class T, unsigned Dim> ac_id_larray BareField< T, Dim >::Locals_ac protected
Definition at line 331 of file BareField.h.
Referenced by BareField< T1, D >::BareField(), BareField< T1, D >::begin_if(), BareField< T1, D >::end_if(), Field< Vector_t, 3, Mesh_t, Center_t >::Repartition(), BareField< T1, D >::Repartition(), and BareField< T1, D >::size_if().
pinned
template<class T, unsigned Dim> bool BareField< T, Dim >::pinned private
Definition at line 357 of file BareField.h.
The documentation for this class was generated from the following files:
ippl/src/FFT/FFT.h
ippl/src/Field/BareField.h
ippl/src/Field/BareField.hpp