OPAL (Object Oriented Parallel Accelerator Library): FTpsData< N > Class Template Reference
FTpsData< N > Class Template Reference
Internal utility class for FTps<T,N> class.
#include <FTpsData.h>
Public Member Functions
FTpsData ()
~FTpsData ()
Static Public Member Functions
static const FMonomial< N > & getExponents (int index)
static int getIndex (const FMonomial< N > &)
static int getOrder (int index)
static int getSize (int order)
static int orderStart (int order)
static int orderStart (int order, int nv)
static int orderEnd (int order)
static int orderEnd (int order, int nv)
static int orderLength (int order)
static int orderLength (int orderL, int orderH)
static const Array1D< int > & getProductArray (int index)
static const Array1D< int > & getVariableList (int index)
static const Array1D< TpsSubstitution > & getSubTable ()
static void setup (int order)
Private Member Functions
FTpsData (const FTpsData &)
void operator= (const FTpsData &)
void build (int order)
void fillSubst (int var, int order, FMonomial< N > &pow, int &next)
Private Attributes
Array1D< FArray1D< int, N+1 > > binom
Array1D< int > bin
Array1D< FMonomial< N > > expon
Array1D< Array1D< int > > prod
Array1D< int > lookBack
Array1D< int > lbBound
Array1D< int > Giorgilli2ExponIndex
Array1D< Array1D< int > > vrblList
Array1D< TpsSubstitution > subTable
Static Private Attributes
static int topOrder
static int topSize
static FTpsData< N > * theBook = new FTpsData<N>()
Detailed Description
template<int N>
class FTpsData< N >
Internal utility class for FTps<T,N> class.
Definition at line 33 of file FTpsData.h.
Constructor & Destructor Documentation
FTpsData() [1/2]
template<int N> FTpsData< N >::FTpsData ()
Definition at line 285 of file FTpsData.h.
~FTpsData()
template<int N> FTpsData< N >::~FTpsData ()
Definition at line 294 of file FTpsData.h.
FTpsData() [2/2]
template<int N> FTpsData< N >::FTpsData (const FTpsData< N > &) private
Member Function Documentation
build()
template<int N> void FTpsData< N >::build (int order) private
Definition at line 303 of file FTpsData.h.
fillSubst()
template<int N> void FTpsData< N >::fillSubst (int var, int order, FMonomial< N > & pow, int & next) private
Definition at line 419 of file FTpsData.h.
getExponents()
template<int N> const FMonomial< N > & FTpsData< N >::getExponents (int index) inline static
Definition at line 158 of file FTpsData.h.
Referenced by FTps< double, 2 *3 >::getExponents(), operator<<(), and FTps< double, 2 *3 >::put().
getIndex()
template<int N> int FTpsData< N >::getIndex (const FMonomial< N > & pows) static
Definition at line 165 of file FTpsData.h.
Referenced by FTps< double, 2 *3 >::get(), FTps< double, 2 *3 >::getCoefficient(), FTps< double, 2 *3 >::getIndex(), FTps< double, 2 *3 >::operator[](), and FTps< double, 2 *3 >::setCoefficient().
getOrder()
template<int N> int FTpsData< N >::getOrder (int index) inline static
Definition at line 180 of file FTpsData.h.
Referenced by FTps< double, 2 *3 >::makeMonomial(), and FTps< double, 2 *3 >::setCoefficient().
getProductArray()
template<int N> const Array1D< int > & FTpsData< N >::getProductArray (int index) inline static
Definition at line 237 of file FTpsData.h.
Referenced by FLieGenerator< T, N >::derivative(), FTps< double, 2 *3 >::derivative(), FTps< double, 2 *3 >::divide(), FTps< double, 2 *3 >::getProductArray(), FTps< double, 2 *3 >::integral(), FTps< double, 2 *3 >::inverse(), operator*(), and FLieGenerator< T, N >::transform().
getSize()
template<int N> int FTpsData< N >::getSize (int order) inline static
Definition at line 187 of file FTpsData.h.
Referenced by FTpsRep< double, N >::FTpsRep(), FVps< T, N >::FVps(), FLieGenerator< T, N >::getBottomIndex(), FLieGenerator< T, N >::getSize(), FTps< double, 2 *3 >::getSize(), and FLieGenerator< T, N >::getTopIndex().
getSubTable()
template<int N> const Array1D< TpsSubstitution > & FTpsData< N >::getSubTable () inline static
Definition at line 268 of file FTpsData.h.
Referenced by FTps< double, 2 *3 >::getSubTable(), and FLieGenerator< T, N >::transform().
getVariableList()
template<int N> const Array1D< int > & FTpsData< N >::getVariableList (int index) inline static
Definition at line 244 of file FTpsData.h.
Referenced by FTps< double, 2 *3 >::getVariableList(), FVps< T, N >::substitute(), and FTps< double, 2 *3 >::substitute().
operator=()
template<int N> void FTpsData< N >::operator= (const FTpsData< N > &) private
orderEnd() [1/2]
template<int N> int FTpsData< N >::orderEnd (int order) inline static
Definition at line 208 of file FTpsData.h.
Referenced by FTpsRep< double, N >::end(), FTps< double, 2 *3 >::end(), and FTps< double, 2 *3 >::orderEnd().
orderEnd() [2/2]
template<int N> int FTpsData< N >::orderEnd (int order, int nv) inline static
Definition at line 215 of file FTpsData.h.
orderLength() [1/2]
template<int N> int FTpsData< N >::orderLength (int order) inline static
Definition at line 222 of file FTpsData.h.
Referenced by FTps< double, 2 *3 >::orderLength().
orderLength() [2/2]
template<int N> int FTpsData< N >::orderLength (int orderL, int orderH) inline static
Definition at line 230 of file FTpsData.h.
orderStart() [1/2]
template<int N> int FTpsData< N >::orderStart (int order) inline static
Definition at line 194 of file FTpsData.h.
Referenced by FTpsRep< double, N >::begin(), FTps< double, 2 *3 >::begin(), FTps< double, 2 *3 >::evalMonoms(), FTps< double, 2 *3 >::evaluate(), and FTps< double, 2 *3 >::orderStart().
orderStart() [2/2]
template<int N> int FTpsData< N >::orderStart (int order, int nv) inline static
Definition at line 201 of file FTpsData.h.
setup()
template<int N> void FTpsData< N >::setup (int order) static
Definition at line 275 of file FTpsData.h.
Referenced by FTpsRep< double, N >::FTpsRep(), and FTps< double, 2 *3 >::setGlobalTruncOrder().
Member Data Documentation
bin
template<int N> Array1D<int> FTpsData< N >::bin private
Definition at line 101 of file FTpsData.h.
binom
template<int N> Array1D< FArray1D < int, N + 1 > > FTpsData< N >::binom private
Definition at line 98 of file FTpsData.h.
expon
template<int N> Array1D< FMonomial<N> > FTpsData< N >::expon private
Definition at line 104 of file FTpsData.h.
Giorgilli2ExponIndex
template<int N> Array1D<int> FTpsData< N >::Giorgilli2ExponIndex private
Definition at line 120 of file FTpsData.h.
lbBound
template<int N> Array1D<int> FTpsData< N >::lbBound private
Definition at line 116 of file FTpsData.h.
lookBack
template<int N> Array1D<int> FTpsData< N >::lookBack private
Definition at line 115 of file FTpsData.h.
prod
template<int N> Array1D< Array1D<int> > FTpsData< N >::prod private
Definition at line 109 of file FTpsData.h.
subTable
template<int N> Array1D< TpsSubstitution > FTpsData< N >::subTable private
Definition at line 126 of file FTpsData.h.
theBook
template<int N> FTpsData< N > * FTpsData< N >::theBook = new FTpsData<N>() static private
Definition at line 135 of file FTpsData.h.
topOrder
template<int N> int FTpsData< N >::topOrder static private
Definition at line 129 of file FTpsData.h.
topSize
template<int N> int FTpsData< N >::topSize static private
Definition at line 132 of file FTpsData.h.
vrblList
template<int N> Array1D< Array1D<int> > FTpsData< N >::vrblList private
Definition at line 123 of file FTpsData.h.
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/src/Classic/FixedAlgebra/FTpsData.h