OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Classic/FixedAlgebra/LinearFun.hpp File Reference
LinearFun.hpp File Reference
#include "FixedAlgebra/LinearFun.h"
#include "FixedAlgebra/FMatrix.h"
#include "FixedAlgebra/FVector.h"
#include "Utilities/DivideError.h"
#include "Utilities/FormatError.h"
#include <iomanip>
#include <iostream>
#include <cstring>
#include <functional>
Functions
template<class T , int N>
LinearFun< T, N > operator+ (const LinearFun< T, N > &lhs, const LinearFun< T, N > &rhs)
Add.
template<class T , int N>
LinearFun< T, N > operator- (const LinearFun< T, N > &lhs, const LinearFun< T, N > &rhs)
Subtract.
template<class T , int N>
LinearFun< T, N > operator+ (const LinearFun< T, N > &lhs, const T &rhs)
Add.
template<class T , int N>
LinearFun< T, N > operator- (const LinearFun< T, N > &lhs, const T &rhs)
Subtract.
template<class T , int N>
LinearFun< T, N > operator+ (const T &lhs, const LinearFun< T, N > &rhs)
Add.
template<class T , int N>
LinearFun< T, N > operator- (const T &lhs, const LinearFun< T, N > &rhs)
Subtract.
template<class T , int N>
LinearFun< T, N > operator* (const LinearFun< T, N > &lhs, const LinearFun< T, N > &rhs)
Multiply.
template<class T , int N>
LinearFun< T, N > operator/ (const LinearFun< T, N > &lhs, const LinearFun< T, N > &rhs)
Divide.
template<class T , int N>
LinearFun< T, N > operator* (const LinearFun< T, N > &lhs, const T &rhs)
Multiply.
template<class T , int N>
LinearFun< T, N > operator/ (const LinearFun< T, N > &lhs, const T &rhs)
Divide.
template<class T , int N>
LinearFun< T, N > operator* (const T &lhs, const LinearFun< T, N > &rhs)
Multiply.
template<class T , int N>
LinearFun< T, N > operator/ (const T &lhs, const LinearFun< T, N > &rhs)
Divide 1 / LinearFun.
template<class T , int N>
bool operator== (const T &lhs, const LinearFun< T, N > &rhs)
Equality.
template<class T , int N>
bool operator!= (const T &lhs, const LinearFun< T, N > &rhs)
Inequality.
template<class T , int N>
std::istream & operator>> (std::istream &is, LinearFun< T, N > &tps)
Extract LinearFun from stream [b]is[/b].
template<class T , int N>
std::ostream & operator<< (std::ostream &os, const LinearFun< T, N > &tps)
Insert LinearFun to stream [b]os[/b].
Function Documentation
operator!=()
template<class T , int N> bool operator!= (const T & lhs, const LinearFun< T, N > & rhs) inline
Inequality.
Definition at line 463 of file LinearFun.hpp.
operator*() [1/3]
template<class T , int N> LinearFun<T, N> operator* (const LinearFun< T, N > & lhs, const LinearFun< T, N > & rhs) inline
Multiply.
Definition at line 418 of file LinearFun.hpp.
References LinearFun< T, N >::multiply().
operator*() [2/3]
template<class T , int N> LinearFun<T, N> operator* (const LinearFun< T, N > & lhs, const T & rhs) inline
Multiply.
Definition at line 430 of file LinearFun.hpp.
operator*() [3/3]
template<class T , int N> LinearFun<T, N> operator* (const T & lhs, const LinearFun< T, N > & rhs) inline
Multiply.
Definition at line 444 of file LinearFun.hpp.
operator+() [1/3]
template<class T , int N> LinearFun<T, N> operator+ (const LinearFun< T, N > & lhs, const LinearFun< T, N > & rhs) inline
Add.
Definition at line 376 of file LinearFun.hpp.
operator+() [2/3]
template<class T , int N> LinearFun<T, N> operator+ (const LinearFun< T, N > & lhs, const T & rhs) inline
Add.
Definition at line 390 of file LinearFun.hpp.
operator+() [3/3]
template<class T , int N> LinearFun<T, N> operator+ (const T & lhs, const LinearFun< T, N > & rhs) inline
Add.
Definition at line 404 of file LinearFun.hpp.
operator-() [1/3]
template<class T , int N> LinearFun<T, N> operator- (const LinearFun< T, N > & lhs, const LinearFun< T, N > & rhs) inline
Subtract.
Definition at line 383 of file LinearFun.hpp.
operator-() [2/3]
template<class T , int N> LinearFun<T, N> operator- (const LinearFun< T, N > & lhs, const T & rhs) inline
Subtract.
Definition at line 397 of file LinearFun.hpp.
operator-() [3/3]
template<class T , int N> LinearFun<T, N> operator- (const T & lhs, const LinearFun< T, N > & rhs) inline
Subtract.
Definition at line 411 of file LinearFun.hpp.
operator/() [1/3]
template<class T , int N> LinearFun<T, N> operator/ (const LinearFun< T, N > & lhs, const LinearFun< T, N > & rhs) inline
Divide.
Definition at line 424 of file LinearFun.hpp.
References LinearFun< T, N >::inverse(), and LinearFun< T, N >::multiply().
operator/() [2/3]
template<class T , int N> LinearFun<T, N> operator/ (const LinearFun< T, N > & lhs, const T & rhs) inline
Divide.
Definition at line 437 of file LinearFun.hpp.
operator/() [3/3]
template<class T , int N> LinearFun<T, N> operator/ (const T & lhs, const LinearFun< T, N > & rhs) inline
Divide 1 / LinearFun.
Definition at line 451 of file LinearFun.hpp.
References LinearFun< T, N >::inverse().
operator<<()
template<class T , int N> std::ostream& operator<< (std::ostream & os, const LinearFun< T, N > & tps) inline
Insert LinearFun to stream [b]os[/b].
Definition at line 475 of file LinearFun.hpp.
operator==()
template<class T , int N> bool operator== (const T & lhs, const LinearFun< T, N > & rhs) inline
Equality.
Definition at line 457 of file LinearFun.hpp.
operator>>()
template<class T , int N> std::istream& operator>> (std::istream & is, LinearFun< T, N > & tps) inline
Extract LinearFun from stream [b]is[/b].
Definition at line 469 of file LinearFun.hpp.
References LinearFun< T, N >::get().