OPAL (Object Oriented Parallel Accelerator Library): Ring Class Reference
Ring Class Reference
Ring describes a ring type geometry for tracking.
#include <Ring.h>
Public Member Functions
Ring (const std::string &ring)
Ring (const Ring &ring)
virtual ~Ring ()
virtual bool apply (const size_t &id, const double &t, Vector_t &E, Vector_t &B) override
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void initialise (PartBunchBase< double, 3 > *bunch)
virtual void finalise () override
virtual bool bends () const override
virtual void accept (BeamlineVisitor &visitor) const override
virtual void getDimensions (double &zBegin, double &zEnd) const override
virtual ElementBase * clone () const override
void appendElement (const Component &element)
virtual EMField & getField () override
virtual const EMField & getField () const override
virtual PlanarArcGeometry & getGeometry () override
virtual const PlanarArcGeometry & getGeometry () const override
void setLossDataSink (LossDataSink *sink)
PartBunchBase< double, 3 > * getLossDataSink () const
void setRefPartBunch (PartBunchBase< double, 3 > *bunch)
PartBunchBase< double, 3 > * getRefPartBunch () const
void setHarmonicNumber (double cyclHarm)
double getHarmonicNumber ()
void setRFFreq (double rfFreq)
double getRFFreq () const
void setBeamRInit (double rInit)
double getBeamRInit () const
void setBeamPhiInit (double phiInit)
double getBeamPhiInit () const
void setBeamThetaInit (double thetaInit)
double getBeamThetaInit () const
void setBeamPRInit (double pRInit)
double getBeamPRInit () const
void setLatticeRInit (double rInit)
double getLatticeRInit () const
void setLatticePhiInit (double phiInit)
double getLatticePhiInit () const
Vector_t getNextPosition () const
Vector_t getNextNormal () const
void setLatticeThetaInit (double thetaInit)
double getLatticeThetaInit () const
void setSymmetry (double symmetry)
void setScale (double scale)
double getSymmetry () const
void setIsClosed (bool isClosed)
double getIsClosed () const
void setRingAperture (double minR, double maxR)
double getRingMinR () const
double getRingMaxR () const
void lockRing ()
RingSection * getSection (int i) const
RingSection * getLastSectionPlaced () const
size_t getNumberOfRingSections () const
std::vector< RingSection * > getSectionsAt (const Vector_t &pos)
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual ElementType getType () const override
Get element type std::string.
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static Vector_t convert (const Vector3D &vec)
static Vector3D convert (const Vector_t &vec)
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Private Member Functions
void resetAzimuths ()
void checkAndClose ()
void buildRingSections ()
void rotateToCyclCoordinates (Euclid3D &euclid3d) const
Vector_t getStartPosition () const
Vector_t getStartNormal () const
Ring ()
Ring & operator= (const Ring &ring)
void checkMidplane (Euclid3D delta) const
Rotation3D getRotationStartToEnd (Euclid3D delta) const
Static Private Member Functions
static bool sectionCompare (RingSection const *const sec1, RingSection const *const sec2)
Private Attributes
PlanarArcGeometry planarArcGeometry_m
PartBunchBase< double, 3 > * refPartBunch_m
LossDataSink * lossDS_m
double beamRInit_m
double beamPRInit_m
double beamPhiInit_m
double beamThetaInit_m
double latticeRInit_m
double latticePhiInit_m
double latticeThetaInit_m
bool willDoAperture_m = false
double minR2_m
double maxR2_m
bool isLocked_m
bool isClosed_m
int symmetry_m
double scale_m = 1.
double cyclHarm_m
double rfFreq_m
double phiStep_m
std::vector< RingSectionList > ringSections_m
RingSectionList section_list_m
Static Private Attributes
static const double lengthTolerance_m = 1e-2
static const double angleTolerance_m = 1e-2
Additional Inherited Members
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Ring describes a ring type geometry for tracking.
Ring describes a ring type geometry for tracking. Ring provides the necessary interfaces for e.g. OPAL-CYCL to track through the ring geometry, while enabling the user to add arbitrary field elements in a closed geometry.
Ring uses similar routines to OPAL-T OpalBeamline class to set up geometry; note that as OPAL-CYCL places the beam in an x-y geometry we place in an x-y geometry for Ring (i.e. the axis of the ring is by default the z-axis). So far only placement of elements in the midplane is supported. It is not possible to give vertical displacements or rotations, or add elements that might create vertical displacements and rotations.
Also aim to maintain backwards compatibility with Cyclotron (i.e. use ParallelCyclotronTracker)
Definition at line 53 of file Ring.h.
Constructor & Destructor Documentation
Ring() [1/3]
Ring::Ring (const std::string & ring)
Constructor
Parameters
ring Name of the ring as defined in the input file
Definition at line 41 of file Ring.cpp.
References setRefPartBunch().
Ring() [2/3]
Ring::Ring (const Ring & ring)
Copy constructor
Can't copy LossDataSink so throw exception if this is set
Definition at line 59 of file Ring.cpp.
References buildRingSections(), lossDS_m, refPartBunch_m, section_list_m, and setRefPartBunch().
~Ring()
Ring::~Ring () virtual
Destructor - deletes lossDS_m if not nullptr
Definition at line 90 of file Ring.cpp.
References section_list_m.
Ring() [3/3]
Ring::Ring () private
Disabled
Referenced by clone().
Member Function Documentation
accept()
void Ring::accept (BeamlineVisitor & visitor) const override virtual
Accept the BeamlineVisitor
Just calls visitRing function on the visitor. I guess the point of this function is that it enables us to store a pointer to the visitor object or something
Implements ElementBase.
Definition at line 55 of file Ring.cpp.
References BeamlineVisitor::visitRing().
appendElement()
void Ring::appendElement (const Component & element)
Add element to the ring
Add element to the ring. Elements are assumed to occupy a region of space defined by a (flat) plane at the start and a plane at the end, both infinite in extent. The position and rotation of these planes are defined according to the Component geometry given by element.getGeometry().
Caller owns memory allocated to element - Ring makes a copy.
Throws an exception if the geometry would bend the element out of the midplane (elements out of midplane are not yet supported). Note that BeamlineGeometry considers midplane to be x-z, whereas Ring considers midplane to be x-y; we apply a rotation during set up.
The element is assumed to extend not beyond the element geometry; Ring applies a bounding box based on the element geometry, if there are field maps expanding outside this region they may get cut.
Definition at line 234 of file Ring.cpp.
References atan2(), checkMidplane(), ElementBase::clone(), cos(), endl(), Rotation3D::getAxis(), RingSection::getComponent(), RingSection::getEndNormal(), RingSection::getEndPosition(), ElementBase::getGeometry(), ElementBase::getName(), getNextNormal(), getNextPosition(), Euclid3D::getRotation(), RingSection::getStartNormal(), RingSection::getStartPosition(), BGeometryBase::getTotalTransform(), Euclid3D::getVector(), gmsg, RingSection::handleOffset(), isLocked_m, rotateToCyclCoordinates(), section_list_m, RingSection::setComponent(), RingSection::setComponentOrientation(), RingSection::setComponentPosition(), RingSection::setEndNormal(), RingSection::setEndPosition(), RingSection::setStartNormal(), RingSection::setStartPosition(), and sin().
Referenced by lockRing(), ParallelCyclotronTracker::visitMultipoleT(), ParallelCyclotronTracker::visitMultipoleTCurvedConstRadius(), ParallelCyclotronTracker::visitMultipoleTCurvedVarRadius(), ParallelCyclotronTracker::visitMultipoleTStraight(), ParallelCyclotronTracker::visitOffset(), ParallelCyclotronTracker::visitSBend3D(), ParallelCyclotronTracker::visitScalingFFAMagnet(), ParallelCyclotronTracker::visitVariableRFCavity(), and ParallelCyclotronTracker::visitVerticalFFAMagnet().
apply() [1/2]
bool Ring::apply (const size_t & id, const double & t, Vector_t & E, Vector_t & B) override virtual
Overwrite data in vector E and B with electric and magnetic field
Parameters
i index of item in RefPartBunch_m - particle bunch
t time
E array where electric field vector is stored - any existing data is overwritten
B array where magnetic field vector is stored - any existing data is overwritten
Returns
false if particle is outside of the field map apertures, else true. If particle is off the field maps, then set flag on the particle "Bin" data to -1 and store in LossDataSink
Reimplemented from Component.
Definition at line 95 of file Ring.cpp.
References LossDataSink::addParticle(), PartBunchBase< T, Dim >::Bin, endl(), ElementBase::getName(), gmsgALL, level4(), lossDS_m, PartBunchBase< T, Dim >::M, PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::Q, PartBunchBase< T, Dim >::R, and refPartBunch_m.
apply() [2/2]
bool Ring::apply (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Overwrite data in vector E and B with electromagnetic field at point R
Parameters
R 3 vector position at which the field is found in Cartesian coordinates (i.e. x, y, z with z=vertical)
P 3 vector momentum
centroid unknown, but not used - bunch mean maybe?
t time
E vector where electric field vector will be stored - any existing data is overwritten
B vector where magnetic field vector will be stored - any existing data is overwritten
Returns
false if particle is outside of the ring aperture, else true. If particle is off the field maps, then set flag on the particle "Bin" data to -1
Reimplemented from Component.
Definition at line 116 of file Ring.cpp.
References PartBunchBase< T, Dim >::get_centroid(), getSectionsAt(), maxR2_m, Attrib::Distribution::R, refPartBunch_m, scale_m, and willDoAperture_m.
bends()
virtual bool Ring::bends () const inline override virtual
Returns true - Ring is assumed to bend particles, being a ring
Implements Component.
Definition at line 131 of file Ring.h.
buildRingSections()
void Ring::buildRingSections () private
Definition at line 351 of file Ring.cpp.
References phiStep_m, ringSections_m, section_list_m, and Physics::two_pi.
Referenced by lockRing(), and Ring().
checkAndClose()
void Ring::checkAndClose () private
Definition at line 336 of file Ring.cpp.
References abs(), angleTolerance_m, lengthTolerance_m, and section_list_m.
Referenced by lockRing().
checkMidplane()
void Ring::checkMidplane (Euclid3D delta) const private
Definition at line 187 of file Ring.cpp.
References abs(), angleTolerance_m, Rotation3D::getAxis(), Euclid3D::getRotation(), Euclid3D::getVector(), and lengthTolerance_m.
Referenced by appendElement().
clone()
virtual ElementBase* Ring::clone () const inline override virtual
Inherited copy constructor
Implements ElementBase.
Definition at line 145 of file Ring.h.
References Ring().
Referenced by ParallelCyclotronTracker::visitRing().
convert() [1/2]
Vector_t Ring::convert (const Vector3D & vec) inline static
Convert from a Vector3D to a Vector_t
Definition at line 421 of file Ring.h.
convert() [2/2]
Vector3D Ring::convert (const Vector_t & vec) inline static
Convert from a Vector_t to a Vector3D
Definition at line 425 of file Ring.h.
finalise()
void Ring::finalise () override virtual
Clean up the Ring
Ring relinquishes RefPartBunchBase<double, 3> pointer and deletes LossDataSink
Implements Component.
Definition at line 161 of file Ring.cpp.
References lossDS_m, Component::online_m, LossDataSink::save(), and setLossDataSink().
getBeamPhiInit()
double Ring::getBeamPhiInit () const inline
Get the initial beam azimuthal angle
Definition at line 231 of file Ring.h.
References beamPhiInit_m.
Referenced by ParallelCyclotronTracker::visitRing().
getBeamPRInit()
double Ring::getBeamPRInit () const inline
Get the initial beam radial momentum
Definition at line 243 of file Ring.h.
References beamPRInit_m.
Referenced by ParallelCyclotronTracker::visitRing().
getBeamRInit()
double Ring::getBeamRInit () const inline
Get the initial beam radius
Definition at line 225 of file Ring.h.
References beamRInit_m.
Referenced by ParallelCyclotronTracker::visitRing().
getBeamThetaInit()
double Ring::getBeamThetaInit () const inline
Get the initial beam rotation relative to the tangent vector
Definition at line 237 of file Ring.h.
References beamThetaInit_m.
Referenced by ParallelCyclotronTracker::visitRing().
getDimensions()
void Ring::getDimensions (double & zBegin, double & zEnd) const override virtual
Not implemented - always throws an exception
Implements Component.
Definition at line 145 of file Ring.cpp.
getField() [1/2]
virtual EMField& Ring::getField () inline override virtual
Not implemented, throws an exception
Implements Component.
Definition at line 169 of file Ring.h.
getField() [2/2]
virtual const EMField& Ring::getField () const inline override virtual
Not implemented, throws an exception
Implements Component.
Definition at line 172 of file Ring.h.
getGeometry() [1/2]
virtual PlanarArcGeometry& Ring::getGeometry () inline override virtual
Not implemented
Implements ElementBase.
Definition at line 175 of file Ring.h.
References planarArcGeometry_m.
getGeometry() [2/2]
virtual const PlanarArcGeometry& Ring::getGeometry () const inline override virtual
Not implemented
Implements ElementBase.
Definition at line 178 of file Ring.h.
References planarArcGeometry_m.
getHarmonicNumber()
double Ring::getHarmonicNumber () inline
Get the harmonic number for RF (number of bunches in the ring)
Definition at line 212 of file Ring.h.
References cyclHarm_m.
Referenced by ParallelCyclotronTracker::getHarmonicNumber(), and ParallelCyclotronTracker::visitRing().
getIsClosed()
double Ring::getIsClosed () const inline
Get flag for closure checking
Definition at line 288 of file Ring.h.
References isClosed_m.
getLastSectionPlaced()
RingSection * Ring::getLastSectionPlaced () const
Get the last section placed or nullptr if no sections were placed yet
Definition at line 364 of file Ring.cpp.
References section_list_m.
getLatticePhiInit()
double Ring::getLatticePhiInit () const inline
Get the initial element's azimuthal angle
Definition at line 255 of file Ring.h.
References latticePhiInit_m.
getLatticeRInit()
double Ring::getLatticeRInit () const inline
Get the initial element's radius
Definition at line 249 of file Ring.h.
References latticeRInit_m.
getLatticeThetaInit()
double Ring::getLatticeThetaInit () const inline
Get the first element's horizontal angle
Get the angle in the ring plane with respect to the tangent vector
Definition at line 273 of file Ring.h.
References latticeThetaInit_m.
getLossDataSink()
PartBunchBase<double, 3>* Ring::getLossDataSink () const
Get pointer to lossDataSink.
Ring still owns the memory to which lossDataSink points.
getNextNormal()
Vector_t Ring::getNextNormal () const
Get the initial element's start normal in cartesian coordinates
Definition at line 220 of file Ring.cpp.
References getStartNormal(), and section_list_m.
Referenced by appendElement().
getNextPosition()
Vector_t Ring::getNextPosition () const
Get the initial element's start position in cartesian coordinates
Definition at line 206 of file Ring.cpp.
References getStartPosition(), and section_list_m.
Referenced by appendElement().
getNumberOfRingSections()
size_t Ring::getNumberOfRingSections () const
Get number of RingSections
Definition at line 402 of file Ring.cpp.
References section_list_m.
Referenced by PyOpal::Field::getNumberOfElements(), and getSection().
getRefPartBunch()
PartBunchBase<double, 3>* Ring::getRefPartBunch () const
Get pointer to RefPartBunchBase<double, 3> from the bunch.
Ring does not own this memory (so neither does caller).
getRFFreq()
double Ring::getRFFreq () const inline
Get the nominal RF frequency
Definition at line 219 of file Ring.h.
References rfFreq_m.
getRingMaxR()
double Ring::getRingMaxR () const inline
Get the ring maximum
Definition at line 300 of file Ring.h.
References maxR2_m, and sqrt().
getRingMinR()
double Ring::getRingMinR () const inline
Get the ring minimum
Definition at line 297 of file Ring.h.
References minR2_m, and sqrt().
getRotationStartToEnd()
Rotation3D Ring::getRotationStartToEnd (Euclid3D delta) const private
Definition at line 176 of file Ring.cpp.
References atan2(), Euclid3D::getRotation(), and Rotation3D::ZRotation().
getSection()
RingSection * Ring::getSection (int i) const
Return ith section. Throw a readable exception if i is not valid
Definition at line 387 of file Ring.cpp.
References getNumberOfRingSections(), sec(), and section_list_m.
Referenced by PyOpal::Field::getElementEndNormal(), PyOpal::Field::getElementEndPosition(), PyOpal::Field::getElementName(), PyOpal::Field::getElementStartNormal(), and PyOpal::Field::getElementStartPosition().
getSectionsAt()
std::vector< RingSection * > Ring::getSectionsAt (const Vector_t & pos)
Get the list of sections at position pos
Definition at line 172 of file Ring.cpp.
References section_list_m.
Referenced by apply().
getStartNormal()
Vector_t Ring::getStartNormal () const private
Definition at line 228 of file Ring.cpp.
References cos(), latticePhiInit_m, latticeThetaInit_m, and sin().
Referenced by getNextNormal().
getStartPosition()
Vector_t Ring::getStartPosition () const private
Definition at line 214 of file Ring.cpp.
References cos(), latticePhiInit_m, latticeRInit_m, and sin().
Referenced by getNextPosition().
getSymmetry()
double Ring::getSymmetry () const inline
Get the rotational symmetry of the ring (number of cells)
Definition at line 282 of file Ring.h.
References symmetry_m.
Referenced by ParallelCyclotronTracker::visitRing().
initialise() [1/2]
void Ring::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Initialise the Ring
Parameters
bunch the particle bunch. Ring borrows this pointer (caller owns memory)
startField - not used
endField - not used
scaleFactor - not used
Implements Component.
Definition at line 156 of file Ring.cpp.
Referenced by ParallelCyclotronTracker::visitRing().
initialise() [2/2]
void Ring::initialise (PartBunchBase< double, 3 > * bunch) virtual
Initialise the Ring - set the bunch and allocate a new LossDataSink
Parameters
bunch the particle bunch. Ring borrows this pointer (caller owns memory)
Definition at line 150 of file Ring.cpp.
References ElementBase::getName(), Component::online_m, setLossDataSink(), and setRefPartBunch().
lockRing()
void Ring::lockRing ()
Lock the ring
Lock the ring; apply closure checks and symmetry properties as required. Impose rule that start must be before end and switch objects around if this is not the case. Sort by startPosition azimuthal angle.
Sets isLocked_m to true. New elements can no longer be added (as it may break the symmetry/bound checking)
Definition at line 291 of file Ring.cpp.
References appendElement(), buildRingSections(), checkAndClose(), endl(), gmsg, isClosed_m, isLocked_m, section_list_m, and symmetry_m.
Referenced by ParallelCyclotronTracker::execute().
operator=()
Ring& Ring::operator= (const Ring & ring) private
Disabled
resetAzimuths()
void Ring::resetAzimuths () private
Definition at line 321 of file Ring.cpp.
References section_list_m.
rotateToCyclCoordinates()
void Ring::rotateToCyclCoordinates (Euclid3D & euclid3d) const private
Definition at line 197 of file Ring.cpp.
References Rotation3D::getAxis(), Euclid3D::getRotation(), and Euclid3D::getVector().
Referenced by appendElement().
sectionCompare()
bool Ring::sectionCompare (RingSection const *const sec1, RingSection const *const sec2) static private
Definition at line 371 of file Ring.cpp.
setBeamPhiInit()
void Ring::setBeamPhiInit (double phiInit) inline
Set the initial beam azimuthal angle
Definition at line 228 of file Ring.h.
References beamPhiInit_m.
Referenced by OpalRingDefinition::update().
setBeamPRInit()
void Ring::setBeamPRInit (double pRInit) inline
Set the initial beam radial momentum
Definition at line 240 of file Ring.h.
References beamPRInit_m.
Referenced by OpalRingDefinition::update().
setBeamRInit()
void Ring::setBeamRInit (double rInit) inline
Set the initial beam radius
Definition at line 222 of file Ring.h.
References beamRInit_m.
Referenced by OpalRingDefinition::update().
setBeamThetaInit()
void Ring::setBeamThetaInit (double thetaInit) inline
Set the initial beam rotation relative to the tangent vector
Definition at line 234 of file Ring.h.
References beamThetaInit_m.
Referenced by OpalRingDefinition::update().
setHarmonicNumber()
void Ring::setHarmonicNumber (double cyclHarm) inline
Set the harmonic number for RF (number of bunches in the ring)
Definition at line 209 of file Ring.h.
References cyclHarm_m.
Referenced by OpalRingDefinition::update().
setIsClosed()
void Ring::setIsClosed (bool isClosed) inline
Set flag for closure checking
Definition at line 285 of file Ring.h.
References isClosed_m.
Referenced by OpalRingDefinition::update().
setLatticePhiInit()
void Ring::setLatticePhiInit (double phiInit) inline
Set the initial element's azimuthal angle
Definition at line 252 of file Ring.h.
References latticePhiInit_m.
Referenced by OpalRingDefinition::update().
setLatticeRInit()
void Ring::setLatticeRInit (double rInit) inline
Set the initial element's radius
Definition at line 246 of file Ring.h.
References latticeRInit_m.
Referenced by OpalRingDefinition::update().
setLatticeThetaInit()
void Ring::setLatticeThetaInit (double thetaInit) inline
Set the first element's horizontal angle
Set the angle in the ring plane with respect to the tangent vector
Definition at line 267 of file Ring.h.
References latticeThetaInit_m.
Referenced by OpalRingDefinition::update().
setLossDataSink()
void Ring::setLossDataSink (LossDataSink * sink)
Set LossDataSink to sink.
Parameters
sink The LossDataSink. Ring takes ownership of memory allocated to sink
Definition at line 140 of file Ring.cpp.
References lossDS_m.
Referenced by finalise(), and initialise().
setRefPartBunch()
void Ring::setRefPartBunch (PartBunchBase< double, 3 > * bunch)
Set RefPartBunchBase<double, 3> to bunch.
Parameters
sink The Bunch. Ring borrows memory allocated to bunch.
Note for compliance with style guide and compatibility with parent two pointer to RefPartBunchBase<double, 3> are stored; this keeps them aligned
Definition at line 167 of file Ring.cpp.
References Component::RefPartBunch_m, and refPartBunch_m.
Referenced by initialise(), and Ring().
setRFFreq()
void Ring::setRFFreq (double rfFreq) inline
Set the nominal RF frequency
Definition at line 216 of file Ring.h.
References rfFreq_m.
Referenced by OpalRingDefinition::update().
setRingAperture()
void Ring::setRingAperture (double minR, double maxR)
Set the ring aperture limits
minR; the minimum radius allowed during tracking. Throws if minR < 0
maxR; the maximum radius allowed during tracking. Throws if maxR < 0 Sets willDoRingAperture_m to true.
Definition at line 376 of file Ring.cpp.
References maxR2_m, minR2_m, and willDoAperture_m.
Referenced by OpalRingDefinition::update().
setScale()
void Ring::setScale (double scale) inline
Set the scaling factor for the fields
Definition at line 279 of file Ring.h.
References scale_m.
Referenced by OpalRingDefinition::update().
setSymmetry()
void Ring::setSymmetry (double symmetry) inline
Set the rotational symmetry of the ring (number of cells)
Definition at line 276 of file Ring.h.
References symmetry_m.
Referenced by OpalRingDefinition::update().
Member Data Documentation
angleTolerance_m
const double Ring::angleTolerance_m = 1e-2 static private
Definition at line 418 of file Ring.h.
Referenced by checkAndClose(), and checkMidplane().
beamPhiInit_m
double Ring::beamPhiInit_m private
Definition at line 379 of file Ring.h.
Referenced by getBeamPhiInit(), and setBeamPhiInit().
beamPRInit_m
double Ring::beamPRInit_m private
Definition at line 378 of file Ring.h.
Referenced by getBeamPRInit(), and setBeamPRInit().
beamRInit_m
double Ring::beamRInit_m private
Definition at line 377 of file Ring.h.
Referenced by getBeamRInit(), and setBeamRInit().
beamThetaInit_m
double Ring::beamThetaInit_m private
Definition at line 380 of file Ring.h.
Referenced by getBeamThetaInit(), and setBeamThetaInit().
cyclHarm_m
double Ring::cyclHarm_m private
Definition at line 406 of file Ring.h.
Referenced by getHarmonicNumber(), and setHarmonicNumber().
isClosed_m
bool Ring::isClosed_m private
Definition at line 398 of file Ring.h.
Referenced by getIsClosed(), lockRing(), and setIsClosed().
isLocked_m
bool Ring::isLocked_m private
Definition at line 394 of file Ring.h.
Referenced by appendElement(), and lockRing().
latticePhiInit_m
double Ring::latticePhiInit_m private
Definition at line 384 of file Ring.h.
Referenced by getLatticePhiInit(), getStartNormal(), getStartPosition(), and setLatticePhiInit().
latticeRInit_m
double Ring::latticeRInit_m private
Definition at line 383 of file Ring.h.
Referenced by getLatticeRInit(), getStartPosition(), and setLatticeRInit().
latticeThetaInit_m
double Ring::latticeThetaInit_m private
Definition at line 385 of file Ring.h.
Referenced by getLatticeThetaInit(), getStartNormal(), and setLatticeThetaInit().
lengthTolerance_m
const double Ring::lengthTolerance_m = 1e-2 static private
Definition at line 417 of file Ring.h.
Referenced by checkAndClose(), and checkMidplane().
lossDS_m
LossDataSink* Ring::lossDS_m private
Definition at line 374 of file Ring.h.
Referenced by apply(), finalise(), Ring(), and setLossDataSink().
maxR2_m
double Ring::maxR2_m private
Definition at line 391 of file Ring.h.
Referenced by apply(), getRingMaxR(), and setRingAperture().
minR2_m
double Ring::minR2_m private
Definition at line 390 of file Ring.h.
Referenced by getRingMinR(), and setRingAperture().
phiStep_m
double Ring::phiStep_m private
Definition at line 412 of file Ring.h.
Referenced by buildRingSections().
planarArcGeometry_m
PlanarArcGeometry Ring::planarArcGeometry_m private
Definition at line 363 of file Ring.h.
Referenced by getGeometry().
refPartBunch_m
PartBunchBase<double, 3>* Ring::refPartBunch_m private
Definition at line 369 of file Ring.h.
Referenced by apply(), Ring(), and setRefPartBunch().
rfFreq_m
double Ring::rfFreq_m private
Definition at line 409 of file Ring.h.
Referenced by getRFFreq(), and setRFFreq().
ringSections_m
std::vector<RingSectionList> Ring::ringSections_m private
Definition at line 413 of file Ring.h.
Referenced by buildRingSections().
scale_m
double Ring::scale_m = 1. private
Definition at line 403 of file Ring.h.
Referenced by apply(), and setScale().
section_list_m
RingSectionList Ring::section_list_m private
Definition at line 414 of file Ring.h.
Referenced by appendElement(), buildRingSections(), checkAndClose(), getLastSectionPlaced(), getNextNormal(), getNextPosition(), getNumberOfRingSections(), getSection(), getSectionsAt(), lockRing(), resetAzimuths(), Ring(), and ~Ring().
symmetry_m
int Ring::symmetry_m private
Definition at line 401 of file Ring.h.
Referenced by getSymmetry(), lockRing(), and setSymmetry().
willDoAperture_m
bool Ring::willDoAperture_m = false private
Definition at line 389 of file Ring.h.
Referenced by apply(), and setRingAperture().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/Ring.h
src/Classic/AbsBeamline/Ring.cpp