OPAL (Object Oriented Parallel Accelerator Library): Mesh< Dim > Class Template Reference
Mesh< Dim > Class Template Reference
#include <Mesh.h>
Public Types
enum { Dimension = Dim }
typedef UserList::ID_t ID_t
typedef iterator_user iterator_if
typedef size_type_user size_type_if
Public Member Functions
Mesh ()
virtual ~Mesh ()
ID_t get_Id () const
void checkin (FieldLayoutUser &f)
void checkout (FieldLayoutUser &f)
size_type_if size_if () const
iterator_if begin_if ()
iterator_if end_if ()
void notifyOfChange ()
Static Public Attributes
static std::string MeshBC_E_Names [3] = {"Reflective","Periodic ","No BC "}
Additional Inherited Members
Private Types inherited from UserList
typedef User::ID_t Key
typedef vmap< Key, User * > UserList_t
typedef UserList_t::iterator iterator_user
typedef UserList_t::size_type size_type_user
typedef User::ID_t ID_t
Private Member Functions inherited from UserList
UserList ()
virtual ~UserList ()
size_type_user getNumUsers () const
ID_t getUserListID () const
bool haveUser (Key key) const
User & getUser (Key key)
iterator_user begin_user ()
iterator_user end_user ()
virtual ID_t checkinUser (User &user)
virtual void checkoutUser (Key key, bool informuser=false)
virtual void checkoutUser (const User &user, bool informuser=false)
Detailed Description
template<unsigned Dim>
class Mesh< Dim >
Definition at line 35 of file Mesh.h.
Member Typedef Documentation
ID_t
template<unsigned Dim> typedef UserList::ID_t Mesh< Dim >::ID_t
Definition at line 39 of file Mesh.h.
iterator_if
template<unsigned Dim> typedef iterator_user Mesh< Dim >::iterator_if
Definition at line 40 of file Mesh.h.
size_type_if
template<unsigned Dim> typedef size_type_user Mesh< Dim >::size_type_if
Definition at line 41 of file Mesh.h.
Member Enumeration Documentation
anonymous enum
template<unsigned Dim> anonymous enum
Enumerator
Dimension
Definition at line 44 of file Mesh.h.
Constructor & Destructor Documentation
Mesh()
template<unsigned int Dim> Mesh< Dim >::Mesh ()
Definition at line 37 of file Mesh.hpp.
~Mesh()
template<unsigned int Dim> Mesh< Dim >::~Mesh () virtual
Definition at line 43 of file Mesh.hpp.
Member Function Documentation
begin_if()
template<unsigned Dim> iterator_if Mesh< Dim >::begin_if () inline
Definition at line 98 of file Mesh.h.
References UserList::begin_user().
checkin()
template<unsigned Dim> void Mesh< Dim >::checkin (FieldLayoutUser & f) inline
Definition at line 89 of file Mesh.h.
References UserList::checkinUser().
checkout()
template<unsigned Dim> void Mesh< Dim >::checkout (FieldLayoutUser & f) inline
Definition at line 94 of file Mesh.h.
References UserList::checkoutUser().
end_if()
template<unsigned Dim> iterator_if Mesh< Dim >::end_if () inline
Definition at line 99 of file Mesh.h.
References UserList::end_user().
get_Id()
template<unsigned Dim> ID_t Mesh< Dim >::get_Id () const inline
Definition at line 84 of file Mesh.h.
References UserList::getUserListID().
notifyOfChange()
template<unsigned int Dim> void Mesh< Dim >::notifyOfChange ()
Definition at line 51 of file Mesh.hpp.
References FieldLayoutUser::Repartition().
size_if()
template<unsigned Dim> size_type_if Mesh< Dim >::size_if () const inline
Definition at line 97 of file Mesh.h.
References UserList::getNumUsers().
Member Data Documentation
MeshBC_E_Names
template<unsigned Dim> std::string Mesh< Dim >::MeshBC_E_Names = {"Reflective","Periodic ","No BC "} static
Definition at line 47 of file Mesh.h.
The documentation for this class was generated from the following files:
ippl/src/Meshes/Mesh.h
ippl/src/Meshes/Mesh.hpp