OPAL (Object Oriented Parallel Accelerator Library): cmp_diff Namespace Reference
cmp_diff Namespace Reference
Functions
bool almost_eq (double A, double B, double maxDiff=1e-15, double maxRelDiff=DBL_EPSILON)
bool almost_eq_zero (double A, double maxDiff=1e-15)
bool eq (double x, double y)
bool eq_zero (double x)
bool le (double x, double y)
bool le_zero (double x)
bool lt (double x, double y)
bool lt_zero (double x)
bool ge (double x, double y)
bool ge_zero (double x)
bool gt (double x, double y)
bool gt_zero (double x)
Function Documentation
almost_eq()
bool cmp_diff::almost_eq (double A, double B, double maxDiff = 1e-15, double maxRelDiff = DBL_EPSILON) inline
Definition at line 132 of file BoundaryGeometry.cpp.
References abs().
almost_eq_zero()
bool cmp_diff::almost_eq_zero (double A, double maxDiff = 1e-15) inline
Definition at line 148 of file BoundaryGeometry.cpp.
References abs().
eq()
bool cmp_diff::eq (double x, double y) inline
Definition at line 153 of file BoundaryGeometry.cpp.
Referenced by PartBunchBase< double, 3 >::setBinCharge().
eq_zero()
bool cmp_diff::eq_zero (double x) inline
Definition at line 154 of file BoundaryGeometry.cpp.
ge()
bool cmp_diff::ge (double x, double y) inline
Definition at line 159 of file BoundaryGeometry.cpp.
ge_zero()
bool cmp_diff::ge_zero (double x) inline
Definition at line 160 of file BoundaryGeometry.cpp.
gt()
bool cmp_diff::gt (double x, double y) inline
Definition at line 161 of file BoundaryGeometry.cpp.
gt_zero()
bool cmp_diff::gt_zero (double x) inline
Definition at line 162 of file BoundaryGeometry.cpp.
le()
bool cmp_diff::le (double x, double y) inline
Definition at line 155 of file BoundaryGeometry.cpp.
le_zero()
bool cmp_diff::le_zero (double x) inline
Definition at line 156 of file BoundaryGeometry.cpp.
lt()
bool cmp_diff::lt (double x, double y) inline
Definition at line 157 of file BoundaryGeometry.cpp.
Referenced by CalcIndexedReceive(), P3MPoissonSolver::calculateGridForces(), FFTBoxPoissonSolver::FFTBoxPoissonSolver(), IndexedLocalAssign(), IndexedSend(), and FFTPoissonSolver::initializeFields().
lt_zero()
bool cmp_diff::lt_zero (double x) inline
Definition at line 158 of file BoundaryGeometry.cpp.