OPAL (Object Oriented Parallel Accelerator Library): Vektor< T, D > Class Template Reference
Vektor< T, D > Class Template Reference
#include <TSVMeta.h>
Public Types
enum { ElemDim = 1 }
enum { Size = D }
typedef T Element_t
Public Member Functions
Vektor ()
Vektor (const Vektor< T, D > &rhs)
template<class T1 , unsigned D1>
Vektor (const Vektor< T1, D1 > &rhs)
Vektor (const T &x00)
Vektor (const T &x00, const T &x01)
Vektor (const T &x00, const T &x01, const T &x02)
Vektor (const T &x00, const T &x01, const T &x02, const T &x03)
~Vektor ()
const Vektor< T, D > & operator= (const Vektor< T, D > &rhs)
template<class T1 >
const Vektor< T, D > & operator= (const Vektor< T1, D > &rhs)
const Vektor< T, D > & operator= (const T &rhs)
template<class T1 >
Vektor< T, D > & operator+= (const Vektor< T1, D > &rhs)
Vektor< T, D > & operator+= (const T &rhs)
template<class T1 >
Vektor< T, D > & operator-= (const Vektor< T1, D > &rhs)
Vektor< T, D > & operator-= (const T &rhs)
template<class T1 >
Vektor< T, D > & operator*= (const Vektor< T1, D > &rhs)
Vektor< T, D > & operator*= (const T &rhs)
template<class T1 >
Vektor< T, D > & operator/= (const Vektor< T1, D > &rhs)
Vektor< T, D > & operator/= (const T &rhs)
Element_t & operator[] (unsigned int i)
Element_t operator[] (unsigned int i) const
Element_t & operator() (unsigned int i)
Element_t operator() (unsigned int i) const
bool operator== (const Vektor< T, D > &that) const
bool operator!= (const Vektor< T, D > &that) const
Message & putMessage (Message &m) const
Message & getMessage (Message &m)
Private Attributes
T X [D]
Detailed Description
template<class T, unsigned D>
class Vektor< T, D >
Definition at line 24 of file TSVMeta.h.
Member Typedef Documentation
Element_t
template<class T, unsigned D> typedef T Vektor< T, D >::Element_t
Definition at line 35 of file Vektor.h.
Member Enumeration Documentation
anonymous enum
template<class T, unsigned D> anonymous enum
Enumerator
ElemDim
Definition at line 36 of file Vektor.h.
anonymous enum
template<class T, unsigned D> anonymous enum
Enumerator
Size
Definition at line 37 of file Vektor.h.
Constructor & Destructor Documentation
Vektor() [1/7]
template<class T, unsigned D> Vektor< T, D >::Vektor () inline
Definition at line 40 of file Vektor.h.
Vektor() [2/7]
template<class T, unsigned D> Vektor< T, D >::Vektor (const Vektor< T, D > & rhs) inline
Definition at line 45 of file Vektor.h.
Vektor() [3/7]
template<class T, unsigned D> template<class T1 , unsigned D1> Vektor< T, D >::Vektor (const Vektor< T1, D1 > & rhs) inline
Definition at line 51 of file Vektor.h.
Vektor() [4/7]
template<class T, unsigned D> Vektor< T, D >::Vektor (const T & x00) inline
Definition at line 57 of file Vektor.h.
Vektor() [5/7]
template<class T, unsigned D> Vektor< T, D >::Vektor (const T & x00, const T & x01) inline
Definition at line 62 of file Vektor.h.
Vektor() [6/7]
template<class T, unsigned D> Vektor< T, D >::Vektor (const T & x00, const T & x01, const T & x02) inline
Definition at line 68 of file Vektor.h.
Vektor() [7/7]
template<class T, unsigned D> Vektor< T, D >::Vektor (const T & x00, const T & x01, const T & x02, const T & x03) inline
Definition at line 75 of file Vektor.h.
~Vektor()
template<class T, unsigned D> Vektor< T, D >::~Vektor () inline
Definition at line 84 of file Vektor.h.
Member Function Documentation
getMessage()
template<class T, unsigned D> Message& Vektor< T, D >::getMessage (Message & m) inline
Definition at line 180 of file Vektor.h.
Referenced by Vektor< int, 3 >::getMessage(), and ParticleSpatialLayout< T, Dim, Mesh >::rebuild_layout().
operator!=()
template<class T, unsigned D> bool Vektor< T, D >::operator!= (const Vektor< T, D > & that) const inline
Definition at line 168 of file Vektor.h.
operator()() [1/2]
template<class T , unsigned D> Vektor< T, D >::Element_t & Vektor< T, D >::operator() (unsigned int i)
Definition at line 207 of file Vektor.h.
operator()() [2/2]
template<class T , unsigned D> Vektor< T, D >::Element_t Vektor< T, D >::operator() (unsigned int i) const
Definition at line 214 of file Vektor.h.
operator*=() [1/2]
template<class T, unsigned D> template<class T1 > Vektor<T,D>& Vektor< T, D >::operator*= (const Vektor< T1, D > & rhs) inline
Definition at line 130 of file Vektor.h.
operator*=() [2/2]
template<class T, unsigned D> Vektor<T,D>& Vektor< T, D >::operator*= (const T & rhs) inline
Definition at line 135 of file Vektor.h.
operator+=() [1/2]
template<class T, unsigned D> template<class T1 > Vektor<T,D>& Vektor< T, D >::operator+= (const Vektor< T1, D > & rhs) inline
Definition at line 106 of file Vektor.h.
operator+=() [2/2]
template<class T, unsigned D> Vektor<T,D>& Vektor< T, D >::operator+= (const T & rhs) inline
Definition at line 111 of file Vektor.h.
operator-=() [1/2]
template<class T, unsigned D> template<class T1 > Vektor<T,D>& Vektor< T, D >::operator-= (const Vektor< T1, D > & rhs) inline
Definition at line 118 of file Vektor.h.
operator-=() [2/2]
template<class T, unsigned D> Vektor<T,D>& Vektor< T, D >::operator-= (const T & rhs) inline
Definition at line 123 of file Vektor.h.
operator/=() [1/2]
template<class T, unsigned D> template<class T1 > Vektor<T,D>& Vektor< T, D >::operator/= (const Vektor< T1, D > & rhs) inline
Definition at line 142 of file Vektor.h.
operator/=() [2/2]
template<class T, unsigned D> Vektor<T,D>& Vektor< T, D >::operator/= (const T & rhs) inline
Definition at line 148 of file Vektor.h.
operator=() [1/3]
template<class T, unsigned D> const Vektor<T,D>& Vektor< T, D >::operator= (const Vektor< T, D > & rhs) inline
Definition at line 87 of file Vektor.h.
operator=() [2/3]
template<class T, unsigned D> template<class T1 > const Vektor<T,D>& Vektor< T, D >::operator= (const Vektor< T1, D > & rhs) inline
Definition at line 93 of file Vektor.h.
operator=() [3/3]
template<class T, unsigned D> const Vektor<T,D>& Vektor< T, D >::operator= (const T & rhs) inline
Definition at line 98 of file Vektor.h.
operator==()
template<class T, unsigned D> bool Vektor< T, D >::operator== (const Vektor< T, D > & that) const inline
Definition at line 165 of file Vektor.h.
operator[]() [1/2]
template<class T , unsigned D> Vektor< T, D >::Element_t & Vektor< T, D >::operator[] (unsigned int i)
Definition at line 193 of file Vektor.h.
operator[]() [2/2]
template<class T , unsigned D> Vektor< T, D >::Element_t Vektor< T, D >::operator[] (unsigned int i) const
Definition at line 200 of file Vektor.h.
putMessage()
template<class T, unsigned D> Message& Vektor< T, D >::putMessage (Message & m) const inline
Definition at line 174 of file Vektor.h.
Referenced by Vektor< int, 3 >::putMessage(), and ParticleSpatialLayout< T, Dim, Mesh >::rebuild_layout().
Member Data Documentation
X
template<class T, unsigned D> T Vektor< T, D >::X[D] private
Definition at line 188 of file Vektor.h.
Referenced by Vektor< int, 3 >::getMessage(), Vektor< int, 3 >::operator==(), Vektor< int, 3 >::putMessage(), and Vektor< int, 3 >::Vektor().
The documentation for this class was generated from the following files:
ippl/src/AppTypes/TSVMeta.h
ippl/src/AppTypes/Vektor.h