OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/AppTypes/Vektor.h File Reference
Vektor.h File Reference
#include "Utility/PAssert.h"
#include "Message/Message.h"
#include "PETE/IpplExpressions.h"
#include "AppTypes/TSVMeta.h"
#include <cmath>
#include <iostream>
#include <iomanip>
Classes
class Vektor< T, D >
Functions
template<class T , unsigned D>
Vektor< T, D > operator- (const Vektor< T, D > &op)
template<class T , unsigned D>
const Vektor< T, D > & operator+ (const Vektor< T, D > &op)
template<class T1 , class T2 , unsigned D>
PETEBinaryReturn< T1, T2, OpMultipply >::type dot (const Vektor< T1, D > &lhs, const Vektor< T2, D > &rhs)
template<class T1 , class T2 , unsigned D>
Vektor< typename PETEBinaryReturn< T1, T2, OpMultipply >::type, D > cross (const Vektor< T1, D > &lhs, const Vektor< T2, D > &rhs)
template<class T , unsigned D>
double euclidean_norm (const Vektor< T, D > &a)
template<class T , unsigned D>
std::ostream & operator<< (std::ostream &out, const Vektor< T, D > &rhs)
Function Documentation
cross()
template<class T1 , class T2 , unsigned D> Vektor<typename PETEBinaryReturn<T1,T2,OpMultipply>::type,D> cross (const Vektor< T1, D > & lhs, const Vektor< T2, D > & rhs) inline
Definition at line 276 of file Vektor.h.
dot()
template<class T1 , class T2 , unsigned D> PETEBinaryReturn<T1,T2,OpMultipply>::type dot (const Vektor< T1, D > & lhs, const Vektor< T2, D > & rhs) inline
Definition at line 265 of file Vektor.h.
Referenced by euclidean_norm().
euclidean_norm()
template<class T , unsigned D> double euclidean_norm (const Vektor< T, D > & a) inline
Definition at line 286 of file Vektor.h.
References a, dot(), and sqrt().
operator+()
template<class T , unsigned D> const Vektor<T,D>& operator+ (const Vektor< T, D > & op) inline
Definition at line 237 of file Vektor.h.
operator-()
template<class T , unsigned D> Vektor<T,D> operator- (const Vektor< T, D > & op) inline
Definition at line 229 of file Vektor.h.
operator<<()
template<class T , unsigned D> std::ostream& operator<< (std::ostream & out, const Vektor< T, D > & rhs) inline
Definition at line 295 of file Vektor.h.