OPAL (Object Oriented Parallel Accelerator Library): ApplyField< T > Struct Template Reference
ApplyField< T > Struct Template Reference
Public Member Functions
ApplyField (double alpha_, double ke_, bool isIntGreen_)
void operator() (std::size_t i, std::size_t j, PartBunch &P_r) const
Public Attributes
double alpha
double ke
bool isIntGreen
Detailed Description
template<class T>
struct ApplyField< T >
Definition at line 61 of file P3MPoissonSolver.cpp.
Constructor & Destructor Documentation
ApplyField()
template<class T > ApplyField< T >::ApplyField (double alpha_, double ke_, bool isIntGreen_) inline
Definition at line 62 of file P3MPoissonSolver.cpp.
Member Function Documentation
operator()()
template<class T > void ApplyField< T >::operator() (std::size_t i, std::size_t j, PartBunch & P_r) const inline
Definition at line 64 of file P3MPoissonSolver.cpp.
References ApplyField< T >::alpha, Dim, PartBunchBase< T, Dim >::Ef, erf(), exp(), ApplyField< T >::isIntGreen, ApplyField< T >::ke, pow(), PartBunchBase< T, Dim >::Q, PartBunchBase< T, Dim >::R, and sqrt().
Member Data Documentation
alpha
template<class T > double ApplyField< T >::alpha
Definition at line 97 of file P3MPoissonSolver.cpp.
Referenced by ApplyField< T >::operator()().
isIntGreen
template<class T > bool ApplyField< T >::isIntGreen
Definition at line 99 of file P3MPoissonSolver.cpp.
Referenced by ApplyField< T >::operator()().
ke
template<class T > double ApplyField< T >::ke
Definition at line 98 of file P3MPoissonSolver.cpp.
Referenced by ApplyField< T >::operator()().
The documentation for this struct was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/src/Solvers/P3MPoissonSolver.cpp