OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/opal.h File Reference
opal.h File Reference
#include "Utility/IpplInfo.h"
Functions
int run_opal (char *arg[], std::string inputfile, int restartStep=-2, int infoLevel=1, int warnLevel=1, MPI_Comm comm=MPI_COMM_WORLD)
Function Documentation
run_opal()
int run_opal (char * arg[], std::string inputfile, int restartStep = -2, int infoLevel = 1, int warnLevel = 1, MPI_Comm comm = MPI_COMM_WORLD)
Definition at line 32 of file opal.cpp.
References Options::amr, Communicate::barrier(), _Fieldmap::clearDictionary(), IpplInfo::Comm, Configure::configure(), OpalData::deleteInstance(), IpplInfo::Error, OpalData::getInstance(), gmsg, handleGSLErrors(), IpplInfo::Info, Options::infoLevel, min(), OpalParser::run(), Inform::setDestination(), OpalData::setRestartFileName(), OpalData::setRestartRun(), OpalData::setRestartStep(), OpalData::storeInputFn(), IpplInfo::Warn, and Options::warnLevel.
Referenced by OpalSimulation::run().