OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyTrackCmdNS Namespace Reference
PyOpal::PyTrackCmdNS Namespace Reference
Functions
void executeWrapper (PyOpalObject< TrackCmd > &cmd)
void executeWrapper (PyOpalObjectNS::PyOpalObject< TrackCmd > &cmd)
BOOST_PYTHON_MODULE (track)
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyTrackCmdNS::BOOST_PYTHON_MODULE (track)
Definition at line 34 of file PyTrackCmd.cpp.
References executeWrapper(), PyOpal::Globals::Initialise(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_class(), and PyOpal::ExceptionTranslation::registerExceptions().
executeWrapper() [1/2]
void PyOpal::PyTrackCmdNS::executeWrapper (PyOpalObject< TrackCmd > & cmd)
Referenced by BOOST_PYTHON_MODULE().
executeWrapper() [2/2]
void PyOpal::PyTrackCmdNS::executeWrapper (PyOpalObjectNS::PyOpalObject< TrackCmd > & cmd)
Definition at line 28 of file PyTrackCmd.cpp.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalShared().