OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyFieldSolverNS Namespace Reference
PyOpal::PyFieldSolverNS Namespace Reference
Functions
void registerFieldSolver (PyOpalObjectNS::PyOpalObject< FieldSolver > &fs)
BOOST_PYTHON_MODULE (field_solver)
Variables
std::string track_run_docstring = std::string()
const char * module_docstring = "build a tracking object"
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyFieldSolverNS::BOOST_PYTHON_MODULE (field_solver)
Definition at line 48 of file PyFieldSolver.cpp.
References Hypervolume::fs, and PyOpal::ExceptionTranslation::registerExceptions().
registerFieldSolver()
void PyOpal::PyFieldSolverNS::registerFieldSolver (PyOpalObjectNS::PyOpalObject< FieldSolver > & fs)
Definition at line 43 of file PyFieldSolver.cpp.
References OpalData::define(), Hypervolume::fs, and OpalData::getInstance().
Variable Documentation
module_docstring
const char* PyOpal::PyFieldSolverNS::module_docstring = "build a tracking object"
Definition at line 12 of file PyFieldSolver.cpp.
track_run_docstring
std::string PyOpal::PyFieldSolverNS::track_run_docstring = std::string()
Definition at line 9 of file PyFieldSolver.cpp.