OPAL (Object Oriented Parallel Accelerator Library): Astra1DMagnetoStatic_fast Class Reference
Astra1DMagnetoStatic_fast Class Reference
#include <Astra1DMagnetoStatic_fast.h>
Public Member Functions
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const
virtual void getFieldDimensions (double &zBegin, double &zEnd) const
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const
virtual bool getFieldDerivative (const Vector_t &R, Vector_t &E, Vector_t &B, const DiffDirection &dir) const
virtual void swap ()
virtual void getInfo (Inform *)
virtual double getFrequency () const
virtual void setFrequency (double freq)
Public Member Functions inherited from Astra1D_fast
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &F)
virtual bool isInside (const Vector_t &r) const
Public Member Functions inherited from Fieldmap
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Private Member Functions
Astra1DMagnetoStatic_fast (std::string aFilename)
virtual ~Astra1DMagnetoStatic_fast ()
virtual void readMap ()
bool readFileHeader (std::ifstream &file)
int stripFileHeader (std::ifstream &file)
Friends
class Fieldmap
Additional Inherited Members
Static Public Member Functions inherited from Fieldmap
static Fieldmap * getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions inherited from Astra1D_fast
Astra1D_fast (std::string aFilename)
virtual ~Astra1D_fast ()
virtual void freeMap ()
bool determineNumSamplingPoints (std::ifstream &file)
double readFieldData (std::ifstream &file)
void normalizeFieldData (double maxEz)
std::vector< double > getEvenlyDistributedSamplingPoints ()
std::vector< double > interpolateFieldData (std::vector< double > &samplingPoints)
void computeFieldDerivatives (std::vector< double > &fourierComponents, int accuracy)
std::vector< double > computeFourierCoefficients (int accuracy, std::vector< double > &evenSampling)
Protected Member Functions inherited from Fieldmap
Fieldmap ()=delete
Fieldmap (const std::string &aFilename)
virtual ~Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions inherited from Fieldmap
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes inherited from Astra1D_fast
double * onAxisField_m
double * zvals_m
gsl_spline * onAxisInterpolants_m [4]
gsl_interp_accel * onAxisAccel_m [4]
double hz_m
double zbegin_m
double zend_m
double length_m
int num_gridpz_m
int numHeaderLines_m
Protected Attributes inherited from Fieldmap
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Detailed Description
Definition at line 6 of file Astra1DMagnetoStatic_fast.h.
Constructor & Destructor Documentation
Astra1DMagnetoStatic_fast()
Astra1DMagnetoStatic_fast::Astra1DMagnetoStatic_fast (std::string aFilename) private
Definition at line 9 of file Astra1DMagnetoStatic_fast.cpp.
References Astra1D_fast::determineNumSamplingPoints(), Fieldmap::disableFieldmapWarning(), Physics::e, Fieldmap::Filename_m, Astra1D_fast::hz_m, Astra1D_fast::length_m, Fieldmap::noFieldmapWarning(), Astra1D_fast::num_gridpz_m, Astra1D_fast::numHeaderLines_m, Astra1D_fast::onAxisField_m, readFileHeader(), TAstraMagnetoStatic, Fieldmap::Type, Astra1D_fast::zbegin_m, and Astra1D_fast::zend_m.
~Astra1DMagnetoStatic_fast()
Astra1DMagnetoStatic_fast::~Astra1DMagnetoStatic_fast () private virtual
Definition at line 41 of file Astra1DMagnetoStatic_fast.cpp.
References Astra1D_fast::freeMap().
Member Function Documentation
getFieldDerivative()
bool Astra1DMagnetoStatic_fast::getFieldDerivative (const Vector_t & R, Vector_t & E, Vector_t & B, const DiffDirection & dir) const virtual
Implements Astra1D_fast.
Definition at line 93 of file Astra1DMagnetoStatic_fast.cpp.
getFieldDimensions() [1/2]
void Astra1DMagnetoStatic_fast::getFieldDimensions (double & zBegin, double & zEnd) const virtual
Implements Astra1D_fast.
Definition at line 97 of file Astra1DMagnetoStatic_fast.cpp.
References Astra1D_fast::zbegin_m, and Astra1D_fast::zend_m.
getFieldDimensions() [2/2]
void Astra1DMagnetoStatic_fast::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const virtual
Implements Astra1D_fast.
Definition at line 102 of file Astra1DMagnetoStatic_fast.cpp.
getFieldstrength()
bool Astra1DMagnetoStatic_fast::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const virtual
Implements Astra1D_fast.
Definition at line 75 of file Astra1DMagnetoStatic_fast.cpp.
References Astra1D_fast::onAxisAccel_m, Astra1D_fast::onAxisInterpolants_m, Attrib::Distribution::R, and Astra1D_fast::zbegin_m.
getFrequency()
double Astra1DMagnetoStatic_fast::getFrequency () const virtual
Implements Astra1D_fast.
Definition at line 111 of file Astra1DMagnetoStatic_fast.cpp.
getInfo()
void Astra1DMagnetoStatic_fast::getInfo (Inform * msg) virtual
Implements Astra1D_fast.
Definition at line 107 of file Astra1DMagnetoStatic_fast.cpp.
References endl(), Fieldmap::Filename_m, Astra1D_fast::zbegin_m, and Astra1D_fast::zend_m.
readFileHeader()
bool Astra1DMagnetoStatic_fast::readFileHeader (std::ifstream & file) private
Definition at line 118 of file Astra1DMagnetoStatic_fast.cpp.
References Physics::e, Fieldmap::normalize_m, and Util::toUpper().
Referenced by Astra1DMagnetoStatic_fast().
readMap()
void Astra1DMagnetoStatic_fast::readMap () private virtual
Reimplemented from Astra1D_fast.
Definition at line 45 of file Astra1DMagnetoStatic_fast.cpp.
References Fieldmap::checkMap(), Astra1D_fast::computeFieldDerivatives(), Astra1D_fast::computeFourierCoefficients(), endl(), Fieldmap::Filename_m, Astra1D_fast::getEvenlyDistributedSamplingPoints(), INFOMSG, Astra1D_fast::interpolateFieldData(), Astra1D_fast::length_m, level3(), Astra1D_fast::normalizeFieldData(), Astra1D_fast::num_gridpz_m, Astra1D_fast::onAxisAccel_m, Astra1D_fast::onAxisField_m, Astra1D_fast::onAxisInterpolants_m, Astra1D_fast::readFieldData(), stripFileHeader(), Fieldmap::typeset_msg(), and Astra1D_fast::zvals_m.
setFrequency()
void Astra1DMagnetoStatic_fast::setFrequency (double freq) virtual
Implements Astra1D_fast.
Definition at line 115 of file Astra1DMagnetoStatic_fast.cpp.
stripFileHeader()
int Astra1DMagnetoStatic_fast::stripFileHeader (std::ifstream & file) private
Definition at line 141 of file Astra1DMagnetoStatic_fast.cpp.
References Physics::e.
Referenced by readMap().
swap()
void Astra1DMagnetoStatic_fast::swap () virtual
Implements Astra1D_fast.
Definition at line 104 of file Astra1DMagnetoStatic_fast.cpp.
Friends And Related Function Documentation
Fieldmap
friend class Fieldmap friend
Definition at line 27 of file Astra1DMagnetoStatic_fast.h.
The documentation for this class was generated from the following files:
src/Classic/Fields/Astra1DMagnetoStatic_fast.h
src/Classic/Fields/Astra1DMagnetoStatic_fast.cpp