OPAL (Object Oriented Parallel Accelerator Library): FMDummy Class Reference
FMDummy Class Reference
#include <FMDummy.h>
Public Member Functions
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const
virtual bool getFieldDerivative (const Vector_t &R, Vector_t &E, Vector_t &B, const DiffDirection &dir) const
virtual void getFieldDimensions (double &zBegin, double &zEnd) const
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const
virtual void swap ()
virtual void getInfo (Inform *)
virtual double getFrequency () const
virtual void setFrequency (double freq)
Public Member Functions inherited from Fieldmap
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &onaxis)
virtual bool isInside (const Vector_t &) const
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Private Member Functions
FMDummy (std::string aFilename)
~FMDummy ()
virtual void readMap ()
virtual void freeMap ()
Private Attributes
double zbegin_m
double zend_m
Friends
class Fieldmap
Additional Inherited Members
Static Public Member Functions inherited from Fieldmap
static Fieldmap * getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions inherited from Fieldmap
Fieldmap ()=delete
Fieldmap (const std::string &aFilename)
virtual ~Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions inherited from Fieldmap
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes inherited from Fieldmap
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Detailed Description
Definition at line 6 of file FMDummy.h.
Constructor & Destructor Documentation
FMDummy()
FMDummy::FMDummy (std::string aFilename) private
Definition at line 5 of file FMDummy.cpp.
References Fieldmap::disableFieldmapWarning(), endl(), Fieldmap::Filename_m, IpplInfo::myNode(), Fieldmap::typeset_msg(), and WARNMSG.
~FMDummy()
FMDummy::~FMDummy () private
Definition at line 25 of file FMDummy.cpp.
Member Function Documentation
freeMap()
void FMDummy::freeMap () private virtual
Implements Fieldmap.
Definition at line 31 of file FMDummy.cpp.
getFieldDerivative()
bool FMDummy::getFieldDerivative (const Vector_t & R, Vector_t & E, Vector_t & B, const DiffDirection & dir) const virtual
Implements Fieldmap.
Definition at line 38 of file FMDummy.cpp.
getFieldDimensions() [1/2]
void FMDummy::getFieldDimensions (double & zBegin, double & zEnd) const virtual
Implements Fieldmap.
Definition at line 42 of file FMDummy.cpp.
References zbegin_m, and zend_m.
getFieldDimensions() [2/2]
void FMDummy::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const virtual
Implements Fieldmap.
Definition at line 46 of file FMDummy.cpp.
getFieldstrength()
bool FMDummy::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const virtual
Implements Fieldmap.
Definition at line 34 of file FMDummy.cpp.
getFrequency()
double FMDummy::getFrequency () const virtual
Implements Fieldmap.
Definition at line 54 of file FMDummy.cpp.
getInfo()
void FMDummy::getInfo (Inform *) virtual
Implements Fieldmap.
Definition at line 51 of file FMDummy.cpp.
readMap()
void FMDummy::readMap () private virtual
Implements Fieldmap.
Definition at line 28 of file FMDummy.cpp.
setFrequency()
void FMDummy::setFrequency (double freq) virtual
Implements Fieldmap.
Definition at line 59 of file FMDummy.cpp.
swap()
void FMDummy::swap () virtual
Implements Fieldmap.
Definition at line 48 of file FMDummy.cpp.
Friends And Related Function Documentation
Fieldmap
friend class Fieldmap friend
Definition at line 28 of file FMDummy.h.
Member Data Documentation
zbegin_m
double FMDummy::zbegin_m private
Definition at line 25 of file FMDummy.h.
Referenced by getFieldDimensions().
zend_m
double FMDummy::zend_m private
Definition at line 26 of file FMDummy.h.
Referenced by getFieldDimensions().
The documentation for this class was generated from the following files:
src/Classic/Fields/FMDummy.h
src/Classic/Fields/FMDummy.cpp