OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Classic/Algebra/SliceIterator.h File Reference
SliceIterator.h File Reference
#include <iterator>
Classes
class SliceIterator< T >
Iterator for array slice.
class ConstSliceIterator< T >
Iterator for array slice.
Functions
template<class T >
std::random_access_iterator_tag iterator_category (const SliceIterator< T > &)
template<class T >
std::random_access_iterator_tag iterator_category (const ConstSliceIterator< T > &)
template<class T >
T * value_type (const SliceIterator< T > &)
template<class T >
T * value_type (const ConstSliceIterator< T > &)
Function Documentation
iterator_category() [1/2]
template<class T > std::random_access_iterator_tag iterator_category (const SliceIterator< T > &) inline
Definition at line 180 of file SliceIterator.h.
iterator_category() [2/2]
template<class T > std::random_access_iterator_tag iterator_category (const ConstSliceIterator< T > &) inline
Definition at line 186 of file SliceIterator.h.
value_type() [1/2]
template<class T > T* value_type (const SliceIterator< T > &) inline
Definition at line 191 of file SliceIterator.h.
References Attrib::Legacy::Distribution::T.
Referenced by BareField< T1, D >::accumGuardCells(), Communicate::add_to_send_cache(), ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), assign(), CalcIndexedReceive(), ParticleAttrib< ParticleOrigin >::calcSortList(), ClosedOrbitFinder< Value_type, Size_type, Stepper >::computeOrbitProperties(), MapGenerator< Value_type, Size_type, Series_type, Map_type, Hamiltonian_type, Space_charge_type >::computeTunes(), vmap< std::string, DiscConfig::SMPData *>::equal_range(), BareField< T1, D >::fillGuardCells(), PutSingleItem< T, false, false >::get_iter(), Timing::getTimer(), Directory::insert(), vmap< std::string, DiscConfig::SMPData *>::lower_bound(), vmap< std::string, DiscConfig::SMPData *>::operator[](), PutSingleItem< T, false, false >::put(), PutSingleItem< T, true, true >::put(), and vmap< std::string, DiscConfig::SMPData *>::upper_bound().
value_type() [2/2]
template<class T > T* value_type (const ConstSliceIterator< T > &) inline
Definition at line 196 of file SliceIterator.h.
References Attrib::Legacy::Distribution::T.