OPAL (Object Oriented Parallel Accelerator Library): SeptumRep Class Reference
SeptumRep Class Reference
#include <SeptumRep.h>
Public Member Functions
SeptumRep (const std::string &name)
Constructor with given name.
SeptumRep ()
SeptumRep (const SeptumRep &)
virtual ~SeptumRep ()
virtual ElementBase * clone () const
Return clone.
virtual Channel * getChannel (const std::string &aKey, bool=false)
Construct a read/write channel.
virtual NullField & getField ()
Get field.
virtual const NullField & getField () const
Get field.
virtual StraightGeometry & getGeometry ()
Get geometry.
virtual const StraightGeometry & getGeometry () const
Get geometry.
virtual void setActive (bool=true)
Set active flag.
Public Member Functions inherited from Septum
Septum (const std::string &name)
Constructor with given name.
Septum ()
Septum (const Septum &)
void operator= (const Septum &)=delete
virtual ~Septum ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to Septum.
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
void initialise (PartBunchBase< double, 3 > *bunch)
virtual ElementBase::ElementType getType () const override
Override implementation of PluginElement.
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
Pure virtual implementation of Component.
void setWidth (double width)
Member variable access.
double getWidth () const
Public Member Functions inherited from PluginElement
PluginElement (const std::string &name)
Constructor with given name.
PluginElement ()
PluginElement (const PluginElement &)
void operator= (const PluginElement &)=delete
virtual ~PluginElement ()
void setDimensions (double xstart, double xend, double ystart, double yend)
Set dimensions and consistency checks.
bool check (PartBunchBase< double, 3 > *bunch, const int turnnumber, const double t, const double tstep)
int checkPoint (const double &x, const double &y) const
Checks if coordinate is within element.
void save ()
Save output.
void initialise (PartBunchBase< double, 3 > *bunch)
virtual void finalise () final
virtual void goOffline () final
virtual bool bends () const override
virtual void getDimensions (double &zBegin, double &zEnd) const override
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
double getXStart () const
Member variable access.
double getXEnd () const
double getYStart () const
double getYEnd () const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual bool Online ()
virtual void setComponentType (std::string)
virtual std::string getComponentType () const
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Attributes
NullField field
The zero magnetic field.
StraightGeometry geometry
The septa's geometry.
bool active
The active/inactive flag.
Protected Attributes inherited from PluginElement
double rmin_m
radius closest to the origin
Point geom_m [5]
actual geometry positions with adaptive width such that each particle hits element once per turn
double A_m
double B_m
double R_m
double C_m
Geometric lengths used in calculations.
std::unique_ptr< LossDataSink > lossDs_m
Pointer to Loss instance.
int numPassages_m = 0
Number of turns (number of times save() method is called)
double xstart_m
input geometry positions
double xend_m
double ystart_m
double yend_m
double rstart_m
double rend_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Private Member Functions
void operator= (const SeptumRep &)
Additional Inherited Members
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from PluginElement
void setGeom (const double dist)
Sets geometry geom_m with element width dist.
void changeWidth (PartBunchBase< double, 3 > *bunch, int i, const double tstep, const double tangle)
Change probe width depending on step size and angle of particle.
double calculateIncidentAngle (double xp, double yp) const
Calculate angle of particle/bunch wrt to element.
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 25 of file SeptumRep.h.
Constructor & Destructor Documentation
SeptumRep() [1/3]
SeptumRep::SeptumRep (const std::string & name) explicit
Constructor with given name.
Definition at line 49 of file SeptumRep.cpp.
SeptumRep() [2/3]
SeptumRep::SeptumRep ()
Definition at line 39 of file SeptumRep.cpp.
Referenced by clone().
SeptumRep() [3/3]
SeptumRep::SeptumRep (const SeptumRep & right)
Definition at line 44 of file SeptumRep.cpp.
~SeptumRep()
SeptumRep::~SeptumRep () virtual
Definition at line 54 of file SeptumRep.cpp.
Member Function Documentation
clone()
ElementBase * SeptumRep::clone () const virtual
Return clone.
Implements ElementBase.
Definition at line 58 of file SeptumRep.cpp.
References SeptumRep().
getChannel()
Channel * SeptumRep::getChannel (const std::string & aKey, bool create = false) virtual
Construct a read/write channel.
Reimplemented from ElementBase.
Definition at line 63 of file SeptumRep.cpp.
References ElementBase::getChannel().
getField() [1/2]
NullField & SeptumRep::getField () virtual
Get field.
Implements Component.
Definition at line 73 of file SeptumRep.cpp.
References field.
getField() [2/2]
const NullField & SeptumRep::getField () const virtual
Get field.
Implements Component.
Definition at line 77 of file SeptumRep.cpp.
References field.
getGeometry() [1/2]
StraightGeometry & SeptumRep::getGeometry () virtual
Get geometry.
Get geometry.
Implements ElementBase.
Definition at line 81 of file SeptumRep.cpp.
References geometry.
getGeometry() [2/2]
const StraightGeometry & SeptumRep::getGeometry () const virtual
Get geometry.
Implements ElementBase.
Definition at line 85 of file SeptumRep.cpp.
References geometry.
operator=()
void SeptumRep::operator= (const SeptumRep &) private
setActive()
void SeptumRep::setActive (bool flag = true) virtual
Set active flag.
Definition at line 90 of file SeptumRep.cpp.
References active.
Member Data Documentation
active
bool SeptumRep::active protected
The active/inactive flag.
Definition at line 79 of file SeptumRep.h.
Referenced by setActive().
field
NullField SeptumRep::field protected
The zero magnetic field.
Definition at line 73 of file SeptumRep.h.
Referenced by getField().
geometry
StraightGeometry SeptumRep::geometry protected
The septa's geometry.
Definition at line 76 of file SeptumRep.h.
Referenced by getGeometry().
The documentation for this class was generated from the following files:
src/Classic/BeamlineCore/SeptumRep.h
src/Classic/BeamlineCore/SeptumRep.cpp