OPAL (Object Oriented Parallel Accelerator Library): SubFieldIter< T, Dim, SOffset< Dim > > Class Template Reference
SubFieldIter< T, Dim, SOffset< Dim > > Class Template Reference
#include <SubFieldIter.h>
Public Types
enum { IsExpr = 1 }
typedef SOffset< Dim > Subset_t
typedef SubFieldIter< T, Dim, Subset_t > SFI
typedef SFI PETE_Expr_t
typedef T PETE_Return_t
Public Types inherited from SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >
enum
Public Types inherited from PETE_Expr< SubFieldIter< T, Dim, SOffset< Dim > > >
typedef SubFieldIter< T, Dim, SOffset< Dim > > Wrapped
Public Member Functions
SubFieldIter (const BareField< T, Dim > &df, const typename BareField< T, Dim >::iterator_if &ldf, const SOffset< Dim > &s, unsigned int B)
SubFieldIter ()
~SubFieldIter ()
void setLFieldData (LField< T, Dim > *p, NDIndex< Dim > &n)
void initialize ()
bool findIntersection (const NDIndex< Dim > &loc, NDIndex< Dim > &inter)
bool plugBase (const NDIndex< Dim > &)
void rewind (unsigned)
void step (unsigned int)
void step (unsigned int, int)
int size (unsigned int d) const
T & operator* ()
T & offset ()
T & offset (int)
T & unit_offset (int)
int Stride (int)
bool CanCompress () const
void Compress (T)
bool TryCompress ()
bool TryCompress (T)
bool IsCompressed () const
bool DomainCompressed () const
PETE_Expr_t MakeExpression () const
Public Member Functions inherited from SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >
SubFieldIterBase (const BareField< T, Dim > &df, const typename BareField< T, Dim >::iterator_if &ldf, const SOffset< Dim > &s, unsigned int B)
SubFieldIterBase ()
~SubFieldIterBase ()
BareField< T, Dim > & getBareField ()
const BareField< T, Dim > & getBareField () const
BareField< T, Dim >::iterator_if getLFieldIter () const
SOffset< Dim > & getDomain ()
const SOffset< Dim > & getDomain () const
bool checkBrackets () const
unsigned int getBrackets () const
BareField< T, Dim >::iterator_if nextLField ()
LField< T, Dim > * getLField ()
const LField< T, Dim > * getLField () const
void setLField (LField< T, Dim > *p)
void setLFieldData (LField< T, Dim > *p, NDIndex< Dim > &)
void FillGCIfNecessary () const
Public Member Functions inherited from PETE_Expr< SubFieldIter< T, Dim, SOffset< Dim > > >
SubFieldIter< T, Dim, SOffset< Dim > > & PETE_unwrap ()
const SubFieldIter< T, Dim, SOffset< Dim > > & PETE_unwrap () const
Static Public Member Functions
static int getSubsetType ()
static bool matchType (int)
static void makeNDIndex (const Subset_t &s, NDIndex< Dim > &i)
Private Attributes
T * SingleValPtr
T SingleValStore
NDIndex< Dim > Component
Detailed Description
template<class T, unsigned int Dim>
class SubFieldIter< T, Dim, SOffset< Dim > >
Definition at line 527 of file SubFieldIter.h.
Member Typedef Documentation
PETE_Expr_t
template<class T , unsigned int Dim> typedef SFI SubFieldIter< T, Dim, SOffset< Dim > >::PETE_Expr_t
Definition at line 633 of file SubFieldIter.h.
PETE_Return_t
template<class T , unsigned int Dim> typedef T SubFieldIter< T, Dim, SOffset< Dim > >::PETE_Return_t
Definition at line 634 of file SubFieldIter.h.
SFI
template<class T , unsigned int Dim> typedef SubFieldIter<T, Dim, Subset_t> SubFieldIter< T, Dim, SOffset< Dim > >::SFI
Definition at line 535 of file SubFieldIter.h.
Subset_t
template<class T , unsigned int Dim> typedef SOffset<Dim> SubFieldIter< T, Dim, SOffset< Dim > >::Subset_t
Definition at line 534 of file SubFieldIter.h.
Member Enumeration Documentation
anonymous enum
template<class T , unsigned int Dim> anonymous enum
Enumerator
IsExpr
Definition at line 632 of file SubFieldIter.h.
Constructor & Destructor Documentation
SubFieldIter() [1/2]
template<class T , unsigned int Dim> SubFieldIter< T, Dim, SOffset< Dim > >::SubFieldIter (const BareField< T, Dim > & df, const typename BareField< T, Dim >::iterator_if & ldf, const SOffset< Dim > & s, unsigned int B) inline
Definition at line 538 of file SubFieldIter.h.
SubFieldIter() [2/2]
template<class T , unsigned int Dim> SubFieldIter< T, Dim, SOffset< Dim > >::SubFieldIter () inline
Definition at line 544 of file SubFieldIter.h.
~SubFieldIter()
template<class T , unsigned int Dim> SubFieldIter< T, Dim, SOffset< Dim > >::~SubFieldIter () inline
Definition at line 547 of file SubFieldIter.h.
Member Function Documentation
CanCompress()
template<class T , unsigned int Dim> bool SubFieldIter< T, Dim, SOffset< Dim > >::CanCompress () const inline
Definition at line 621 of file SubFieldIter.h.
Compress()
template<class T , unsigned int Dim> void SubFieldIter< T, Dim, SOffset< Dim > >::Compress (T) inline
Definition at line 622 of file SubFieldIter.h.
DomainCompressed()
template<class T , unsigned int Dim> bool SubFieldIter< T, Dim, SOffset< Dim > >::DomainCompressed () const inline
Definition at line 626 of file SubFieldIter.h.
findIntersection()
template<class T , unsigned int Dim> bool SubFieldIter< T, Dim, SOffset< Dim > >::findIntersection (const NDIndex< Dim > & loc, NDIndex< Dim > & inter) inline
Definition at line 585 of file SubFieldIter.h.
References NDIndex< Dim >::empty().
getSubsetType()
template<class T , unsigned int Dim> static int SubFieldIter< T, Dim, SOffset< Dim > >::getSubsetType () inline static
Definition at line 570 of file SubFieldIter.h.
References SOffsetSubsetType.
initialize()
template<class T , unsigned int Dim> void SubFieldIter< T, Dim, SOffset< Dim > >::initialize () inline
Definition at line 574 of file SubFieldIter.h.
IsCompressed()
template<class T , unsigned int Dim> bool SubFieldIter< T, Dim, SOffset< Dim > >::IsCompressed () const inline
Definition at line 625 of file SubFieldIter.h.
MakeExpression()
template<class T , unsigned int Dim> PETE_Expr_t SubFieldIter< T, Dim, SOffset< Dim > >::MakeExpression () const inline
Definition at line 635 of file SubFieldIter.h.
makeNDIndex()
template<class T , unsigned int Dim> static void SubFieldIter< T, Dim, SOffset< Dim > >::makeNDIndex (const Subset_t & s, NDIndex< Dim > & i) inline static
Definition at line 591 of file SubFieldIter.h.
References Dim.
matchType()
template<class T , unsigned int Dim> static bool SubFieldIter< T, Dim, SOffset< Dim > >::matchType (int) inline static
Definition at line 571 of file SubFieldIter.h.
offset() [1/2]
template<class T , unsigned int Dim> T& SubFieldIter< T, Dim, SOffset< Dim > >::offset () inline
Definition at line 614 of file SubFieldIter.h.
References offset().
Referenced by offset().
offset() [2/2]
template<class T , unsigned int Dim> T& SubFieldIter< T, Dim, SOffset< Dim > >::offset (int) inline
Definition at line 615 of file SubFieldIter.h.
operator*()
template<class T , unsigned int Dim> T& SubFieldIter< T, Dim, SOffset< Dim > >::operator* (void) inline
Definition at line 613 of file SubFieldIter.h.
plugBase()
template<class T , unsigned int Dim> bool SubFieldIter< T, Dim, SOffset< Dim > >::plugBase (const NDIndex< Dim > &) inline
Definition at line 598 of file SubFieldIter.h.
rewind()
template<class T , unsigned int Dim> void SubFieldIter< T, Dim, SOffset< Dim > >::rewind (unsigned) inline
Definition at line 601 of file SubFieldIter.h.
setLFieldData()
template<class T , unsigned int Dim> void SubFieldIter< T, Dim, SOffset< Dim > >::setLFieldData (LField< T, Dim > * p, NDIndex< Dim > & n) inline
Definition at line 554 of file SubFieldIter.h.
References LField< T, Dim >::begin(), SOffset< Dim >::begin(), Dim, LField< T, Dim >::getOwned(), Hypervolume::n, BrickIterator< T, Dim >::offset(), and SubFieldIterBase< T, Dim, S, ExprDim >::setLFieldData().
size()
template<class T , unsigned int Dim> int SubFieldIter< T, Dim, SOffset< Dim > >::size (unsigned int d) const inline
Definition at line 608 of file SubFieldIter.h.
step() [1/2]
template<class T , unsigned int Dim> void SubFieldIter< T, Dim, SOffset< Dim > >::step (unsigned int) inline
Definition at line 604 of file SubFieldIter.h.
step() [2/2]
template<class T , unsigned int Dim> void SubFieldIter< T, Dim, SOffset< Dim > >::step (unsigned int, int) inline
Definition at line 605 of file SubFieldIter.h.
Stride()
template<class T , unsigned int Dim> int SubFieldIter< T, Dim, SOffset< Dim > >::Stride (int) inline
Definition at line 619 of file SubFieldIter.h.
TryCompress() [1/2]
template<class T , unsigned int Dim> bool SubFieldIter< T, Dim, SOffset< Dim > >::TryCompress () inline
Definition at line 623 of file SubFieldIter.h.
TryCompress() [2/2]
template<class T , unsigned int Dim> bool SubFieldIter< T, Dim, SOffset< Dim > >::TryCompress (T) inline
Definition at line 624 of file SubFieldIter.h.
unit_offset()
template<class T , unsigned int Dim> T& SubFieldIter< T, Dim, SOffset< Dim > >::unit_offset (int) inline
Definition at line 618 of file SubFieldIter.h.
Member Data Documentation
Component
template<class T , unsigned int Dim> NDIndex<Dim> SubFieldIter< T, Dim, SOffset< Dim > >::Component private
Definition at line 640 of file SubFieldIter.h.
SingleValPtr
template<class T , unsigned int Dim> T* SubFieldIter< T, Dim, SOffset< Dim > >::SingleValPtr private
Definition at line 638 of file SubFieldIter.h.
SingleValStore
template<class T , unsigned int Dim> T SubFieldIter< T, Dim, SOffset< Dim > >::SingleValStore private
Definition at line 639 of file SubFieldIter.h.
The documentation for this class was generated from the following file:
ippl/src/SubField/SubFieldIter.h