OPAL (Object Oriented Parallel Accelerator Library): Multipole Class Reference
Multipole Class Reference abstract
Interface for general multipole.
#include <Multipole.h>
Public Member Functions
Multipole (const std::string &name)
Constructor with given name.
Multipole ()
Multipole (const Multipole &)
virtual ~Multipole ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to Multipole.
virtual BMultipoleField & getField () override=0
Get multipole field.
virtual const BMultipoleField & getField () const override=0
Get multipole field. Version for const object.
double getNormalComponent (int n) const
Get normal component.
double getSkewComponent (int n) const
Get skew component.
void setNormalComponent (int, double)
Set normal component.
void setNormalComponent (int, double, double)
Set normal component.
void setSkewComponent (int, double)
Set skew component.
void setSkewComponent (int, double, double)
Set skew component.
size_t getMaxNormalComponentIndex () const
size_t getMaxSkewComponentIndex () const
void setNSlices (const std::size_t &nSlices)
std::size_t getNSlices () const
bool isFocusing (unsigned int component) const
virtual StraightGeometry & getGeometry () override=0
Get geometry.
virtual const StraightGeometry & getGeometry () const override=0
Get geometry.
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void finalise () override
virtual bool bends () const override
virtual ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
virtual bool isInside (const Vector_t &r) const override
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void computeField (Vector_t R, Vector_t &E, Vector_t &B)
void operator= (const Multipole &)
Private Attributes
std::vector< double > NormalComponents
std::vector< double > NormalComponentErrors
std::vector< double > SkewComponents
std::vector< double > SkewComponentErrors
int max_SkewComponent_m
int max_NormalComponent_m
std::size_t nSlices_m
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Interface for general multipole.
Definition at line 47 of file Multipole.h.
Constructor & Destructor Documentation
Multipole() [1/3]
Multipole::Multipole (const std::string & name) explicit
Constructor with given name.
Definition at line 64 of file Multipole.cpp.
Multipole() [2/3]
Multipole::Multipole ()
Definition at line 47 of file Multipole.cpp.
Multipole() [3/3]
Multipole::Multipole (const Multipole & right)
Definition at line 52 of file Multipole.cpp.
~Multipole()
Multipole::~Multipole () virtual
Definition at line 76 of file Multipole.cpp.
Member Function Documentation
accept()
void Multipole::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to Multipole.
Implements ElementBase.
Definition at line 80 of file Multipole.cpp.
References BeamlineVisitor::visitMultipole().
apply() [1/2]
bool Multipole::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 274 of file Multipole.cpp.
References computeField(), ElementBase::getElementLength(), ElementBase::getFlagDeleteOnTransverseExit(), ElementBase::isInsideTransverse(), Attrib::Distribution::R, PartBunchBase< T, Dim >::R, and Component::RefPartBunch_m.
apply() [2/2]
bool Multipole::apply (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 290 of file Multipole.cpp.
References computeField(), ElementBase::getElementLength(), ElementBase::getFlagDeleteOnTransverseExit(), ElementBase::isInsideTransverse(), and Attrib::Distribution::R.
applyToReferenceParticle()
bool Multipole::applyToReferenceParticle (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 299 of file Multipole.cpp.
References computeField(), ElementBase::getElementLength(), ElementBase::isInsideTransverse(), max_NormalComponent_m, max_SkewComponent_m, NormalComponentErrors, NormalComponents, Attrib::Distribution::R, SkewComponentErrors, and SkewComponents.
bends()
bool Multipole::bends () const override virtual
Implements Component.
Definition at line 333 of file Multipole.cpp.
computeField()
void Multipole::computeField (Vector_t R, Vector_t & E, Vector_t & B) private
Definition at line 151 of file Multipole.cpp.
References DECAPOLE, DIPOLE, max_NormalComponent_m, max_SkewComponent_m, NormalComponents, OCTUPOLE, QUADRUPOLE, Attrib::Distribution::R, SEXTUPOLE, and SkewComponents.
Referenced by apply(), and applyToReferenceParticle().
finalise()
void Multipole::finalise () override virtual
Implements Component.
Definition at line 329 of file Multipole.cpp.
References Component::online_m.
getDimensions()
void Multipole::getDimensions (double & zBegin, double & zEnd) const override virtual
Implements Component.
Definition at line 338 of file Multipole.cpp.
References ElementBase::getElementLength().
getField() [1/2]
virtual BMultipoleField& Multipole::getField () override pure virtual
Get multipole field.
Implements Component.
Implemented in SingleMultipole< order >, and MultipoleRep.
Referenced by ThickTracker::visitMultipole().
getField() [2/2]
virtual const BMultipoleField& Multipole::getField () const override pure virtual
Get multipole field. Version for const object.
Implements Component.
Implemented in SingleMultipole< order >, and MultipoleRep.
getGeometry() [1/2]
virtual StraightGeometry& Multipole::getGeometry () override pure virtual
Get geometry.
Implements ElementBase.
Implemented in SingleMultipole< order >, and MultipoleRep.
getGeometry() [2/2]
virtual const StraightGeometry& Multipole::getGeometry () const override pure virtual
Get geometry.
Implements ElementBase.
Implemented in SingleMultipole< order >, and MultipoleRep.
getMaxNormalComponentIndex()
size_t Multipole::getMaxNormalComponentIndex () const inline
Definition at line 157 of file Multipole.h.
References NormalComponents.
getMaxSkewComponentIndex()
size_t Multipole::getMaxSkewComponentIndex () const inline
Definition at line 162 of file Multipole.h.
References SkewComponents.
getNormalComponent()
double Multipole::getNormalComponent (int n) const
Get normal component.
Definition at line 85 of file Multipole.cpp.
References max_NormalComponent_m, Hypervolume::n, and NormalComponents.
Referenced by MultipoleRep::getChannel().
getNSlices()
std::size_t Multipole::getNSlices () const
Definition at line 147 of file Multipole.cpp.
References nSlices_m.
Referenced by ThickTracker::visitMultipole().
getSkewComponent()
double Multipole::getSkewComponent (int n) const
Get skew component.
Definition at line 93 of file Multipole.cpp.
References max_SkewComponent_m, Hypervolume::n, and SkewComponents.
Referenced by MultipoleRep::getChannel().
getType()
ElementType Multipole::getType () const override virtual
Get element type std::string.
Reimplemented from Component.
Definition at line 344 of file Multipole.cpp.
References MULTIPOLE.
initialise()
void Multipole::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Implements Component.
Definition at line 322 of file Multipole.cpp.
References ElementBase::getElementLength(), Component::online_m, and Component::RefPartBunch_m.
isFocusing()
bool Multipole::isFocusing (unsigned int component) const
Definition at line 357 of file Multipole.cpp.
References PartBunchBase< T, Dim >::getChargePerParticle(), NormalComponents, pow(), and Component::RefPartBunch_m.
isInside()
bool Multipole::isInside (const Vector_t & r) const override virtual
Reimplemented from ElementBase.
Definition at line 349 of file Multipole.cpp.
References ElementBase::getElementLength(), and ElementBase::isInsideTransverse().
operator=()
void Multipole::operator= (const Multipole &) private
setNormalComponent() [1/2]
void Multipole::setNormalComponent (int n, double v) inline
Set normal component.
Definition at line 147 of file Multipole.h.
References Hypervolume::n.
Referenced by MultipoleRep::getChannel(), OpalSextupole::update(), OpalMultipole::update(), OpalOctupole::update(), and OpalQuadrupole::update().
setNormalComponent() [2/2]
void Multipole::setNormalComponent (int n, double v, double vError)
Set normal component.
Definition at line 101 of file Multipole.cpp.
References DIPOLE, max_NormalComponent_m, Hypervolume::n, NormalComponentErrors, NormalComponents, and PAssert_GE.
setNSlices()
void Multipole::setNSlices (const std::size_t & nSlices)
Definition at line 142 of file Multipole.cpp.
References nSlices_m.
Referenced by OpalQuadrupole::update().
setSkewComponent() [1/2]
void Multipole::setSkewComponent (int n, double v) inline
Set skew component.
Definition at line 152 of file Multipole.h.
References Hypervolume::n.
Referenced by MultipoleRep::getChannel(), OpalSextupole::update(), OpalMultipole::update(), OpalOctupole::update(), and OpalQuadrupole::update().
setSkewComponent() [2/2]
void Multipole::setSkewComponent (int n, double v, double vError)
Set skew component.
Definition at line 121 of file Multipole.cpp.
References DIPOLE, max_SkewComponent_m, Hypervolume::n, PAssert_GT, SkewComponentErrors, and SkewComponents.
Member Data Documentation
max_NormalComponent_m
int Multipole::max_NormalComponent_m private
Definition at line 142 of file Multipole.h.
Referenced by applyToReferenceParticle(), computeField(), getNormalComponent(), and setNormalComponent().
max_SkewComponent_m
int Multipole::max_SkewComponent_m private
Definition at line 141 of file Multipole.h.
Referenced by applyToReferenceParticle(), computeField(), getSkewComponent(), and setSkewComponent().
NormalComponentErrors
std::vector<double> Multipole::NormalComponentErrors private
Definition at line 138 of file Multipole.h.
Referenced by applyToReferenceParticle(), and setNormalComponent().
NormalComponents
std::vector<double> Multipole::NormalComponents private
Definition at line 137 of file Multipole.h.
Referenced by applyToReferenceParticle(), computeField(), getMaxNormalComponentIndex(), getNormalComponent(), isFocusing(), and setNormalComponent().
nSlices_m
std::size_t Multipole::nSlices_m private
Definition at line 143 of file Multipole.h.
Referenced by getNSlices(), and setNSlices().
SkewComponentErrors
std::vector<double> Multipole::SkewComponentErrors private
Definition at line 140 of file Multipole.h.
Referenced by applyToReferenceParticle(), and setSkewComponent().
SkewComponents
std::vector<double> Multipole::SkewComponents private
Definition at line 139 of file Multipole.h.
Referenced by applyToReferenceParticle(), computeField(), getMaxSkewComponentIndex(), getSkewComponent(), and setSkewComponent().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/AbsBeamline/Multipole.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/AbsBeamline/Multipole.cpp