OPAL (Object Oriented Parallel Accelerator Library): ExtrapolateAndZeroFace< T, D, M, C > Class Template Reference
ExtrapolateAndZeroFace< T, D, M, C > Class Template Reference
#include <BCond.h>
Public Types
typedef BCondBase< T, D, M, C > BCondBaseTDMC
Public Member Functions
ExtrapolateAndZeroFace (unsigned f, T o, T s, int i=BCondBaseTDMC::allComponents, int j=BCondBaseTDMC::allComponents)
virtual void apply (Field< T, D, M, C > &)
virtual BCondBase< T, D, M, C > * clone () const
virtual void write (std::ostream &) const
const T & getOffset () const
const T & getSlope () const
Public Member Functions inherited from BCondBase< T, D, M, C >
BCondBase (unsigned int face, int i=allComponents, int j=allComponents)
virtual ~BCondBase ()
int getComponent () const
unsigned int getFace () const
bool changesPhysicalCells () const
Public Member Functions inherited from RefCounted
RefCounted ()
Protected Attributes
T Offset
T Slope
Protected Attributes inherited from BCondBase< T, D, M, C >
int m_component
unsigned int m_face
bool m_changePhysical
Additional Inherited Members
Public Attributes inherited from RefCounted
int RefCount
Static Public Attributes inherited from BCondBase< T, D, M, C >
static int allComponents = -9999
Detailed Description
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering>
class ExtrapolateAndZeroFace< T, D, M, C >
Definition at line 434 of file BCond.h.
Member Typedef Documentation
BCondBaseTDMC
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering> typedef BCondBase<T,D,M,C> ExtrapolateAndZeroFace< T, D, M, C >::BCondBaseTDMC
Definition at line 441 of file BCond.h.
Constructor & Destructor Documentation
ExtrapolateAndZeroFace()
template<class T , unsigned D, class M , class C > ExtrapolateAndZeroFace< T, D, M, C >::ExtrapolateAndZeroFace (unsigned f, T o, T s, int i = BCondBaseTDMC::allComponents, int j = BCondBaseTDMC::allComponents)
Definition at line 309 of file BCond.hpp.
Member Function Documentation
apply()
template<class T , unsigned D, class M , class C > void ExtrapolateAndZeroFace< T, D, M, C >::apply (Field< T, D, M, C > & A) virtual
Implements BCondBase< T, D, M, C >.
Definition at line 3612 of file BCond.hpp.
References ExtrapolateAndZeroFaceBCApply().
clone()
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering> virtual BCondBase<T,D,M,C>* ExtrapolateAndZeroFace< T, D, M, C >::clone () const inline virtual
Implements BCondBase< T, D, M, C >.
Definition at line 450 of file BCond.h.
getOffset()
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering> const T& ExtrapolateAndZeroFace< T, D, M, C >::getOffset () const inline
Definition at line 458 of file BCond.h.
References ExtrapolateAndZeroFace< T, D, M, C >::Offset.
Referenced by ExtrapolateAndZeroFaceBCApply2().
getSlope()
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering> const T& ExtrapolateAndZeroFace< T, D, M, C >::getSlope () const inline
Definition at line 459 of file BCond.h.
References ExtrapolateAndZeroFace< T, D, M, C >::Slope.
Referenced by ExtrapolateAndZeroFaceBCApply2().
write()
template<class T , unsigned D, class M , class C > void ExtrapolateAndZeroFace< T, D, M, C >::write (std::ostream & o) const virtual
Reimplemented from BCondBase< T, D, M, C >.
Reimplemented in ZeroGuardsAndZeroFace< T, D, M, C >, and NegReflectAndZeroFace< T, D, M, C >.
Definition at line 207 of file BCond.hpp.
Member Data Documentation
Offset
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering> T ExtrapolateAndZeroFace< T, D, M, C >::Offset protected
Definition at line 462 of file BCond.h.
Referenced by ExtrapolateAndZeroFace< T, D, M, C >::getOffset().
Slope
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering> T ExtrapolateAndZeroFace< T, D, M, C >::Slope protected
Definition at line 462 of file BCond.h.
Referenced by ExtrapolateAndZeroFace< T, D, M, C >::getSlope().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BCond.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BCond.hpp