OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyOutputPlane Namespace Reference
PyOpal::PyOutputPlane Namespace Reference
Functions
BOOST_PYTHON_MODULE (output_plane)
Variables
const char * module_docstring = "output_plane contains the OutputPlane class"
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyOutputPlane::BOOST_PYTHON_MODULE (output_plane)
Definition at line 52 of file PyOutputPlane.cpp.
References PyOpal::Globals::Initialise(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_element_class(), and PyOpal::ExceptionTranslation::registerExceptions().
Variable Documentation
module_docstring
const char* PyOpal::PyOutputPlane::module_docstring = "output_plane contains the OutputPlane class"
Definition at line 50 of file PyOutputPlane.cpp.