OPAL (Object Oriented Parallel Accelerator Library): Format Class Reference
Format Class Reference
#include <Format.h>
Public Member Functions
Format (Message *)
unsigned int getItemCount ()
unsigned int getSize ()
unsigned int getFormatSize ()
unsigned int getItemElems (int i)
unsigned int getItemBytes (int i)
void print ()
Private Attributes
unsigned int items
unsigned int size
std::vector< unsigned int > format_array
Detailed Description
Definition at line 27 of file Format.h.
Constructor & Destructor Documentation
Format()
Format::Format (Message * msg)
Definition at line 21 of file Format.cpp.
References format_array, Message::item(), items, Message::MsgItem::numBytes(), Message::MsgItem::numElems(), size, and Message::size().
Member Function Documentation
getFormatSize()
unsigned int Format::getFormatSize () inline
Definition at line 36 of file Format.h.
References items.
getItemBytes()
unsigned int Format::getItemBytes (int i) inline
Definition at line 42 of file Format.h.
References format_array.
Referenced by MsgBuffer::add(), and MsgBuffer::get().
getItemCount()
unsigned int Format::getItemCount () inline
Definition at line 30 of file Format.h.
References items.
Referenced by MsgBuffer::add(), and MsgBuffer::get().
getItemElems()
unsigned int Format::getItemElems (int i) inline
Definition at line 39 of file Format.h.
References format_array.
Referenced by MsgBuffer::add(), and MsgBuffer::get().
getSize()
unsigned int Format::getSize () inline
Definition at line 33 of file Format.h.
References size.
Referenced by MsgBuffer::get(), and MsgBuffer::MsgBuffer().
print()
void Format::print ()
Definition at line 36 of file Format.cpp.
References endl(), format_array, items, and size.
Member Data Documentation
format_array
std::vector<unsigned int> Format::format_array private
Definition at line 50 of file Format.h.
Referenced by Format(), getItemBytes(), getItemElems(), and print().
items
unsigned int Format::items private
Definition at line 49 of file Format.h.
Referenced by Format(), getFormatSize(), getItemCount(), and print().
size
unsigned int Format::size private
Definition at line 49 of file Format.h.
Referenced by Format(), getSize(), and print().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Message/Format.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Message/Format.cpp