OPAL (Object Oriented Parallel Accelerator Library): mslang::AffineTransformation Struct Reference
mslang::AffineTransformation Struct Reference
#include <AffineTransformation.h>
Public Member Functions
AffineTransformation (const Vector_t &row0, const Vector_t &row1)
AffineTransformation ()
AffineTransformation getInverse () const
Vector_t getOrigin () const
double getAngle () const
Vector_t transformTo (const Vector_t &v) const
Vector_t transformFrom (const Vector_t &v) const
AffineTransformation mult (const AffineTransformation &B)
Public Member Functions inherited from Tenzor< double, 3 >
Tenzor ()
Tenzor (DontInitialize)
Tenzor (const Tenzor< double, D > &rhs)
Tenzor (const double &x00)
Tenzor (const double &x00, const double &x10, const double &x01, const double &x11)
Tenzor (const double &x00, const double &x10, const double &x20, const double &x01, const double &x11, const double &x21, const double &x02, const double &x12, const double &x22)
Tenzor (const SymTenzor< double, D > &)
Tenzor (const AntiSymTenzor< double, D > &)
~Tenzor ()
const Tenzor< double, D > & operator= (const Tenzor< double, D > &rhs)
const Tenzor< double, D > & operator= (const Tenzor< T1, D > &rhs)
const Tenzor< double, D > & operator= (const double &rhs)
Tenzor< double, D > & operator+= (const Tenzor< T1, D > &rhs)
Tenzor< double, D > & operator+= (const double &rhs)
Tenzor< double, D > & operator-= (const Tenzor< T1, D > &rhs)
Tenzor< double, D > & operator-= (const double &rhs)
Tenzor< double, D > & operator*= (const Tenzor< T1, D > &rhs)
Tenzor< double, D > & operator*= (const double &rhs)
Tenzor< double, D > & operator/= (const Tenzor< T1, D > &rhs)
Tenzor< double, D > & operator/= (const double &rhs)
void diagonal (const double &rhs)
int len (void) const
int size (void) const
Element_t & operator[] (unsigned int i)
Element_t operator[] (unsigned int i) const
Element_t & operator() (unsigned int i)
Element_t operator() (unsigned int i) const
Element_t operator() (unsigned int i, unsigned int j) const
Element_t & operator() (unsigned int i, unsigned int j)
Element_t operator() (const std::pair< int, int > i) const
Element_t & operator() (const std::pair< int, int > i)
bool operator== (const Tenzor< double, D > &that) const
bool operator!= (const Tenzor< double, D > &that) const
Message & putMessage (Message &m) const
Message & getMessage (Message &m)
Additional Inherited Members
Public Types inherited from Tenzor< double, 3 >
enum
enum
typedef double Element_t
Detailed Description
Definition at line 11 of file AffineTransformation.h.
Constructor & Destructor Documentation
AffineTransformation() [1/2]
mslang::AffineTransformation::AffineTransformation (const Vector_t & row0, const Vector_t & row1) inline
Definition at line 12 of file AffineTransformation.h.
AffineTransformation() [2/2]
mslang::AffineTransformation::AffineTransformation () inline
Definition at line 17 of file AffineTransformation.h.
Member Function Documentation
getAngle()
double mslang::AffineTransformation::getAngle () const inline
Definition at line 40 of file AffineTransformation.h.
References atan2().
Referenced by mslang::Triangle::print(), mslang::Ellipse::print(), and mslang::Rectangle::print().
getInverse()
AffineTransformation mslang::AffineTransformation::getInverse () const inline
Definition at line 20 of file AffineTransformation.h.
References det().
Referenced by transformFrom().
getOrigin()
Vector_t mslang::AffineTransformation::getOrigin () const inline
Definition at line 36 of file AffineTransformation.h.
Referenced by mslang::Triangle::print(), mslang::Ellipse::print(), and mslang::Rectangle::print().
mult()
AffineTransformation mslang::AffineTransformation::mult (const AffineTransformation & B) inline
Definition at line 57 of file AffineTransformation.h.
References dot().
Referenced by mslang::Repeat::apply().
transformFrom()
Vector_t mslang::AffineTransformation::transformFrom (const Vector_t & v) const inline
Definition at line 52 of file AffineTransformation.h.
References getInverse(), and transformTo().
Referenced by mslang::Rectangle::computeBoundingBox(), mslang::Triangle::computeBoundingBox(), mslang::Ellipse::computeBoundingBox(), mslang::Triangle::writeGnuplot(), mslang::Ellipse::writeGnuplot(), and mslang::Rectangle::writeGnuplot().
transformTo()
Vector_t mslang::AffineTransformation::transformTo (const Vector_t & v) const inline
Definition at line 44 of file AffineTransformation.h.
References dot().
Referenced by mslang::Rectangle::isInside(), mslang::Triangle::isInside(), mslang::Ellipse::isInside(), and transformFrom().
The documentation for this struct was generated from the following file:
src/Classic/Utilities/MSLang/AffineTransformation.h