OPAL (Object Oriented Parallel Accelerator Library): SDDSWriter Class Reference
SDDSWriter Class Reference
#include <SDDSWriter.h>
Public Types
typedef std::pair< std::string, std::string > desc_t
typedef std::tuple< std::string, std::string, std::string > param_t
typedef std::pair< std::string, size_t > data_t
typedef std::tuple< std::string, std::string, std::string, std::string > cols_t
Public Member Functions
SDDSWriter (const std::string &fname, bool restart)
virtual ~SDDSWriter ()
virtual void write (PartBunchBase< double, 3 > *)
void rewindLines (size_t numberOfLines)
delete the last 'numberOfLines' lines of the file 'fileName'
void replaceVersionString ()
double getLastValue (const std::string &column)
bool exists () const
Protected Member Functions
void addDescription (const std::string &text, const std::string &content)
template<typename T >
void addParameter (const std::string &name, const std::string &type, const std::string &desc, const T &value)
void addDefaultParameters ()
void addColumn (const std::string &name, const std::string &type, const std::string &unit, const std::string &desc)
void addInfo (const std::string &mode, const size_t &no_row_counts)
void writeRow ()
void open ()
void close ()
void writeHeader ()
Write SDDS header.
template<typename T >
std::string toString (const T &val)
bool hasColumns () const
Protected Attributes
std::string fname_m
std::ios_base::openmode mode_m
First write to the statistics output file.
SDDSColumnSet columns_m
Private Member Functions
void writeDescription ()
void writeParameters ()
void writeColumns ()
void writeInfo ()
Private Attributes
std::ofstream os_m
std::string indent_m
desc_t desc_m
std::queue< param_t > params_m
std::queue< std::string > paramValues_m
data_t info_m
Static Private Attributes
static constexpr unsigned int precision_m = 15
Detailed Description
Definition at line 39 of file SDDSWriter.h.
Member Typedef Documentation
cols_t
typedef std::tuple<std::string, std::string, std::string, std::string> SDDSWriter::cols_t
Definition at line 57 of file SDDSWriter.h.
data_t
typedef std::pair<std::string, size_t> SDDSWriter::data_t
Definition at line 51 of file SDDSWriter.h.
desc_t
typedef std::pair<std::string, std::string> SDDSWriter::desc_t
Definition at line 43 of file SDDSWriter.h.
param_t
typedef std::tuple<std::string, std::string, std::string> SDDSWriter::param_t
Definition at line 48 of file SDDSWriter.h.
Constructor & Destructor Documentation
SDDSWriter()
SDDSWriter::SDDSWriter (const std::string & fname, bool restart)
Definition at line 32 of file SDDSWriter.cpp.
References endl(), fname_m, Hypervolume::fs, INFOMSG, and mode_m.
~SDDSWriter()
virtual SDDSWriter::~SDDSWriter () inline virtual
Definition at line 61 of file SDDSWriter.h.
Member Function Documentation
addColumn()
void SDDSWriter::addColumn (const std::string & name, const std::string & type, const std::string & unit, const std::string & desc) protected
addDefaultParameters()
void SDDSWriter::addDefaultParameters () protected
Definition at line 209 of file SDDSWriter.cpp.
References addParameter(), Util::getGitRevision(), OpalData::getInstance(), IpplInfo::getNodes(), OPAL_PROJECT_NAME, and OPAL_PROJECT_VERSION.
Referenced by ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), GridLBalWriter::fillHeader(), MemoryWriter::fillHeader(), MultiBunchDump::fillHeader(), StatWriter::fillHeader(), and MemoryProfiler::header().
addDescription()
void SDDSWriter::addDescription (const std::string & text, const std::string & content) inline protected
Definition at line 159 of file SDDSWriter.h.
References desc_m.
Referenced by ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), GridLBalWriter::fillHeader(), MemoryWriter::fillHeader(), MultiBunchDump::fillHeader(), StatWriter::fillHeader(), and MemoryProfiler::header().
addInfo()
void SDDSWriter::addInfo (const std::string & mode, const size_t & no_row_counts) inline protected
Definition at line 178 of file SDDSWriter.h.
References info_m.
Referenced by ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), GridLBalWriter::fillHeader(), MemoryWriter::fillHeader(), MultiBunchDump::fillHeader(), StatWriter::fillHeader(), and MemoryProfiler::header().
addParameter()
template<typename T > void SDDSWriter::addParameter (const std::string & name, const std::string & type, const std::string & desc, const T & value) protected
Definition at line 166 of file SDDSWriter.h.
References name, params_m, and paramValues_m.
Referenced by addDefaultParameters().
close()
void SDDSWriter::close () protected
Definition at line 142 of file SDDSWriter.cpp.
References IpplInfo::myNode(), and os_m.
Referenced by ElementPositionWriter::addRow(), MonitorStatisticsWriter::addRow(), LBalWriter::write(), GridLBalWriter::write(), MemoryWriter::write(), MultiBunchDump::write(), StatWriter::write(), and MemoryProfiler::write().
exists()
bool SDDSWriter::exists () const inline
Definition at line 153 of file SDDSWriter.h.
References fname_m.
getLastValue()
double SDDSWriter::getLastValue (const std::string & column)
Definition at line 123 of file SDDSWriter.cpp.
References fname_m, SDDS::SDDSParser::getValue(), and SDDS::SDDSParser::run().
hasColumns()
bool SDDSWriter::hasColumns () const inline protected
Definition at line 200 of file SDDSWriter.h.
References columns_m, and SDDSColumnSet::hasColumns().
Referenced by ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), GridLBalWriter::fillHeader(), MemoryWriter::fillHeader(), MultiBunchDump::fillHeader(), StatWriter::fillHeader(), and MemoryProfiler::header().
open()
void SDDSWriter::open () protected
Definition at line 132 of file SDDSWriter.cpp.
References fname_m, mode_m, IpplInfo::myNode(), os_m, and precision_m.
Referenced by ElementPositionWriter::addRow(), MonitorStatisticsWriter::addRow(), LBalWriter::write(), GridLBalWriter::write(), MemoryWriter::write(), MultiBunchDump::write(), StatWriter::write(), and MemoryProfiler::write().
replaceVersionString()
void SDDSWriter::replaceVersionString ()
Definition at line 78 of file SDDSWriter.cpp.
References fname_m, Hypervolume::fs, Util::getGitRevision(), SDDS::SDDSParser::getParameterValue(), IpplInfo::myNode(), OPAL_PROJECT_NAME, OPAL_PROJECT_VERSION, and SDDS::SDDSParser::run().
rewindLines()
void SDDSWriter::rewindLines (size_t numberOfLines)
delete the last 'numberOfLines' lines of the file 'fileName'
Definition at line 48 of file SDDSWriter.cpp.
References fname_m, Hypervolume::fs, and IpplInfo::myNode().
toString()
template<typename T > std::string SDDSWriter::toString (const T & val) protected
Definition at line 191 of file SDDSWriter.h.
References precision_m.
Referenced by GridLBalWriter::write(), and MemoryProfiler::write().
write()
virtual void SDDSWriter::write (PartBunchBase< double, 3 > *) inline virtual
Reimplemented in MemoryProfiler, GridLBalWriter, MemoryWriter, and LBalWriter.
Definition at line 63 of file SDDSWriter.h.
writeColumns()
void SDDSWriter::writeColumns () private
Definition at line 189 of file SDDSWriter.cpp.
References columns_m, indent_m, os_m, and SDDSColumnSet::writeHeader().
Referenced by writeHeader().
writeDescription()
void SDDSWriter::writeDescription () private
Definition at line 165 of file SDDSWriter.cpp.
References desc_m, endl(), indent_m, and os_m.
Referenced by writeHeader().
writeHeader()
void SDDSWriter::writeHeader () protected
Write SDDS header.
Writes the appropriate SDDS format header information, The SDDS tools can be used for plotting data.
Definition at line 149 of file SDDSWriter.cpp.
References mode_m, IpplInfo::myNode(), writeColumns(), writeDescription(), writeInfo(), and writeParameters().
Referenced by ElementPositionWriter::addRow(), MonitorStatisticsWriter::addRow(), LBalWriter::write(), GridLBalWriter::write(), MemoryWriter::write(), MultiBunchDump::write(), StatWriter::write(), and MemoryProfiler::write().
writeInfo()
void SDDSWriter::writeInfo () private
Definition at line 194 of file SDDSWriter.cpp.
References endl(), indent_m, info_m, os_m, and paramValues_m.
Referenced by writeHeader().
writeParameters()
void SDDSWriter::writeParameters () private
Definition at line 174 of file SDDSWriter.cpp.
References indent_m, os_m, and params_m.
Referenced by writeHeader().
writeRow()
void SDDSWriter::writeRow () inline protected
Definition at line 185 of file SDDSWriter.h.
References columns_m, os_m, and SDDSColumnSet::writeRow().
Referenced by ElementPositionWriter::addRow(), MonitorStatisticsWriter::addRow(), LBalWriter::write(), GridLBalWriter::write(), MemoryWriter::write(), MultiBunchDump::write(), StatWriter::write(), and MemoryProfiler::write().
Member Data Documentation
columns_m
SDDSColumnSet SDDSWriter::columns_m protected
Definition at line 122 of file SDDSWriter.h.
Referenced by ElementPositionWriter::addRow(), MonitorStatisticsWriter::addRow(), ElementPositionWriter::fillHeader(), LBalWriter::fillHeader(), MonitorStatisticsWriter::fillHeader(), MemoryWriter::fillHeader(), GridLBalWriter::fillHeader(), MultiBunchDump::fillHeader(), StatWriter::fillHeader(), hasColumns(), MemoryProfiler::header(), LBalWriter::write(), GridLBalWriter::write(), MemoryWriter::write(), MultiBunchDump::write(), StatWriter::write(), MemoryProfiler::write(), writeColumns(), and writeRow().
desc_m
desc_t SDDSWriter::desc_m private
Definition at line 142 of file SDDSWriter.h.
Referenced by addDescription(), and writeDescription().
fname_m
std::string SDDSWriter::fname_m protected
Definition at line 112 of file SDDSWriter.h.
Referenced by exists(), getLastValue(), open(), replaceVersionString(), rewindLines(), StatBaseWriter::rewindToSpos(), and SDDSWriter().
indent_m
std::string SDDSWriter::indent_m private
Definition at line 140 of file SDDSWriter.h.
Referenced by writeColumns(), writeDescription(), writeInfo(), and writeParameters().
info_m
data_t SDDSWriter::info_m private
Definition at line 145 of file SDDSWriter.h.
Referenced by addInfo(), and writeInfo().
mode_m
std::ios_base::openmode SDDSWriter::mode_m protected
First write to the statistics output file.
Initially set to std::ios::out so that SDDS format header information is written to file during the first write call to the statistics output file. Variable is then reset to std::ios::app so that header information is only written once.
Definition at line 120 of file SDDSWriter.h.
Referenced by LBalWriter::fillHeader(), GridLBalWriter::fillHeader(), MemoryWriter::fillHeader(), MultiBunchDump::fillHeader(), StatWriter::fillHeader(), MemoryProfiler::header(), open(), SDDSWriter(), and writeHeader().
os_m
std::ofstream SDDSWriter::os_m private
Definition at line 138 of file SDDSWriter.h.
Referenced by close(), open(), writeColumns(), writeDescription(), writeInfo(), writeParameters(), and writeRow().
params_m
std::queue<param_t> SDDSWriter::params_m private
Definition at line 143 of file SDDSWriter.h.
Referenced by addParameter(), and writeParameters().
paramValues_m
std::queue<std::string> SDDSWriter::paramValues_m private
Definition at line 144 of file SDDSWriter.h.
Referenced by addParameter(), and writeInfo().
precision_m
constexpr unsigned int SDDSWriter::precision_m = 15 static private
Definition at line 148 of file SDDSWriter.h.
Referenced by open(), and toString().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Structure/SDDSWriter.h
/psi/home/gsell/data/src/OPAL/src/src/Structure/SDDSWriter.cpp