OPAL (Object Oriented Parallel Accelerator Library): RFCavityRep Class Reference
RFCavityRep Class Reference
#include <RFCavityRep.h>
Public Member Functions
RFCavityRep (const std::string &name)
Constructor with given name.
RFCavityRep ()
RFCavityRep (const RFCavityRep &)
virtual ~RFCavityRep ()
virtual ElementBase * clone () const
Return clone.
virtual Channel * getChannel (const std::string &aKey, bool=false)
Construct a read/write channel.
virtual AcceleratingField & getField ()
Get field.
virtual const AcceleratingField & getField () const
Get field.
virtual StraightGeometry & getGeometry ()
Get geometry.
virtual const StraightGeometry & getGeometry () const
Get geometry.
virtual double getAmplitude () const
Get amplitude.
virtual double getFrequency () const
Get frequency.
virtual double getPhase () const
Get phase.
virtual void setAmplitude (double V)
Set amplitude.
virtual void setFrequency (double f)
Set frequency.
virtual void setPhase (double phi)
Set phase.
Public Member Functions inherited from RFCavity
RFCavity (const std::string &name)
Constructor with given name.
RFCavity ()
RFCavity (const RFCavity &)
virtual ~RFCavity ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to RFCavity.
void setFrequency (double freq)
void dropFieldmaps ()
virtual void setFieldMapFN (const std::string &fmapfn)
Set the name of the field map.
virtual std::string getFieldMapFN () const
virtual void setAmplitudem (double vPeak)
virtual double getAmplitudem () const
virtual void setAmplitudeError (double vPeakError)
virtual double getAmplitudeError () const
virtual void setFrequencym (double freq)
virtual double getFrequencym () const
virtual void setPhasem (double phase)
virtual double getPhasem () const
double getPhasem (double t) const
virtual void setPhaseError (double phaseError)
virtual double getPhaseError () const
void setCavityType (const std::string &type)
CavityType getCavityType () const
std::string getCavityTypeString () const
virtual void setFast (bool fast)
virtual bool getFast () const
virtual void setAutophaseVeto (bool veto=true)
virtual bool getAutophaseVeto () const
virtual double getAutoPhaseEstimate (const double &E0, const double &t0, const double &q, const double &m)
virtual double getAutoPhaseEstimateFallback (double E0, double t0, double q, double m)
virtual std::pair< double, double > trackOnAxisParticle (const double &p0, const double &t0, const double &dt, const double &q, const double &mass, std::ofstream *out=nullptr)
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void initialise (PartBunchBase< double, 3 > *bunch, std::shared_ptr< AbstractTimeDependence > freq_atd, std::shared_ptr< AbstractTimeDependence > ampl_atd, std::shared_ptr< AbstractTimeDependence > phase_atd)
virtual void finalise () override
virtual bool bends () const override
virtual void goOnline (const double &kineticEnergy) override
virtual void goOffline () override
virtual void setDesignEnergy (const double &ekin, bool changeable=true) override
virtual double getDesignEnergy () const override
void setRmin (double rmin)
virtual double getRmin () const
void setRmax (double rmax)
virtual double getRmax () const
void setAzimuth (double angle)
virtual double getAzimuth () const
void setPerpenDistance (double pdis)
virtual double getPerpenDistance () const
void setGapWidth (double gapwidth)
virtual double getGapWidth () const
void setPhi0 (double phi0)
virtual double getPhi0 () const
virtual double getCosAzimuth () const
virtual double getSinAzimuth () const
virtual double getCycFrequency () const
void getMomentaKick (const double normalRadius, double momentum[], const double t, const double dtCorrt, const int PID, const double restMass, const int chargenumber)
used in OPAL-cycl
double spline (double z, double *za)
virtual ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
virtual bool isInside (const Vector_t &r) const override
void setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setAmplitudeModelName (std::string name)
std::string getAmplitudeModelName ()
void setPhaseModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setPhaseModelName (std::string name)
std::string getPhaseModelName ()
void setFrequencyModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setFrequencyModelName (std::string name)
std::string getFrequencyModelName ()
virtual double getElementLength () const override
Get design length.
virtual void getElementDimensions (double &begin, double &end) const override
virtual CoordinateSystemTrafo getEdgeToBegin () const override
virtual CoordinateSystemTrafo getEdgeToEnd () const override
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual void setElementLength (double length)
Set design length.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static void setIgnore (bool ignore=false)
Set ignore switch.
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Private Member Functions
void operator= (const RFCavityRep &)
Private Attributes
StraightGeometry geometry
The cavity's geometry.
AcceleratingField field
The cavity's field.
Static Private Attributes
static bool ignoreCavities = false
Cavities are ignored (amplitude = 0) when this switch is set.
Additional Inherited Members
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from RFCavity
std::shared_ptr< AbstractTimeDependence > phaseTD_m
std::string phaseName_m
std::shared_ptr< AbstractTimeDependence > amplitudeTD_m
std::string amplitudeName_m
std::shared_ptr< AbstractTimeDependence > frequencyTD_m
std::string frequencyName_m
std::string filename_m
double scale_m
double scaleError_m
double phase_m
double phaseError_m
double frequency_m
bool fast_m
bool autophaseVeto_m
double designEnergy_m
Fieldmap * fieldmap_m
double startField_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 26 of file RFCavityRep.h.
Constructor & Destructor Documentation
RFCavityRep() [1/3]
RFCavityRep::RFCavityRep (const std::string & name) explicit
Constructor with given name.
Definition at line 68 of file RFCavityRep.cpp.
RFCavityRep() [2/3]
RFCavityRep::RFCavityRep ()
Definition at line 57 of file RFCavityRep.cpp.
Referenced by clone().
RFCavityRep() [3/3]
RFCavityRep::RFCavityRep (const RFCavityRep & right)
Definition at line 62 of file RFCavityRep.cpp.
~RFCavityRep()
RFCavityRep::~RFCavityRep () virtual
Definition at line 73 of file RFCavityRep.cpp.
Member Function Documentation
clone()
ElementBase * RFCavityRep::clone () const virtual
Return clone.
Implements ElementBase.
Definition at line 77 of file RFCavityRep.cpp.
References RFCavityRep().
getAmplitude()
double RFCavityRep::getAmplitude () const virtual
Get amplitude.
Implements RFCavity.
Definition at line 111 of file RFCavityRep.cpp.
References field, ConstEzField::getEz(), and ignoreCavities.
getChannel()
Channel * RFCavityRep::getChannel (const std::string & aKey, bool create = false) virtual
Construct a read/write channel.
Reimplemented from ElementBase.
Definition at line 82 of file RFCavityRep.cpp.
References ElementBase::getChannel().
getField() [1/2]
AcceleratingField & RFCavityRep::getField () virtual
Get field.
Implements Component.
Definition at line 93 of file RFCavityRep.cpp.
References field.
getField() [2/2]
const AcceleratingField & RFCavityRep::getField () const virtual
Get field.
Implements Component.
Definition at line 97 of file RFCavityRep.cpp.
References field.
getFrequency()
double RFCavityRep::getFrequency () const virtual
Get frequency.
Implements RFCavity.
Definition at line 116 of file RFCavityRep.cpp.
References field, and OscillatingField< Field >::getFrequency().
getGeometry() [1/2]
StraightGeometry & RFCavityRep::getGeometry () virtual
Get geometry.
Implements ElementBase.
Definition at line 102 of file RFCavityRep.cpp.
References geometry.
getGeometry() [2/2]
const StraightGeometry & RFCavityRep::getGeometry () const virtual
Get geometry.
Implements ElementBase.
Definition at line 106 of file RFCavityRep.cpp.
References geometry.
getPhase()
double RFCavityRep::getPhase () const virtual
Get phase.
Implements RFCavity.
Definition at line 121 of file RFCavityRep.cpp.
References field, and OscillatingField< Field >::getPhase().
operator=()
void RFCavityRep::operator= (const RFCavityRep &) private
setAmplitude()
void RFCavityRep::setAmplitude (double V) virtual
Set amplitude.
Definition at line 126 of file RFCavityRep.cpp.
References field, and ConstEzField::setEz().
Referenced by OpalCavity::update().
setFrequency()
void RFCavityRep::setFrequency (double f) virtual
Set frequency.
Definition at line 131 of file RFCavityRep.cpp.
References field, and OscillatingField< Field >::setFrequency().
Referenced by OpalCavity::update().
setIgnore()
void RFCavityRep::setIgnore (bool ignore = false) static
Set ignore switch.
Definition at line 140 of file RFCavityRep.cpp.
References ignoreCavities.
setPhase()
void RFCavityRep::setPhase (double phi) virtual
Set phase.
Definition at line 136 of file RFCavityRep.cpp.
References field, and OscillatingField< Field >::setPhase().
Referenced by OpalCavity::update().
Member Data Documentation
field
AcceleratingField RFCavityRep::field private
The cavity's field.
Definition at line 102 of file RFCavityRep.h.
Referenced by getAmplitude(), getField(), getFrequency(), getPhase(), setAmplitude(), setFrequency(), and setPhase().
geometry
StraightGeometry RFCavityRep::geometry private
The cavity's geometry.
Definition at line 99 of file RFCavityRep.h.
Referenced by getGeometry().
ignoreCavities
bool RFCavityRep::ignoreCavities = false static private
Cavities are ignored (amplitude = 0) when this switch is set.
Definition at line 105 of file RFCavityRep.h.
Referenced by getAmplitude(), and setIgnore().
The documentation for this class was generated from the following files:
src/Classic/BeamlineCore/RFCavityRep.h
src/Classic/BeamlineCore/RFCavityRep.cpp