OPAL (Object Oriented Parallel Accelerator Library): _FM3DMagnetoStaticExtended Class Reference
_FM3DMagnetoStaticExtended Class Reference
#include <FM3DMagnetoStaticExtended.h>
Classes
struct IndexTriplet
Public Member Functions
virtual ~_FM3DMagnetoStaticExtended ()
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const
virtual bool getFieldDerivative (const Vector_t &R, Vector_t &E, Vector_t &B, const DiffDirection &dir) const
virtual void getFieldDimensions (double &zBegin, double &zEnd) const
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const
virtual void swap ()
virtual void getInfo (Inform *msg)
virtual double getFrequency () const
virtual void setFrequency (double freq)
virtual bool isInside (const Vector_t &r) const
Public Member Functions inherited from _Fieldmap
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &onaxis)
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Private Types
enum {
LX = 0, LY = 0, LZ = 0, HX = 4,
HY = 2, HZ = 1
}
Private Member Functions
_FM3DMagnetoStaticExtended (const std::string &filename)
virtual void readMap ()
virtual void freeMap ()
IndexTriplet getIndex (const Vector_t &X) const
unsigned long getIndex (unsigned int i, unsigned int j, unsigned int k) const
Vector_t interpolateTrilinearly (const Vector_t &X) const
double getWeightedData (double *data, const IndexTriplet &idx, unsigned short corner) const
void integrateBx (unsigned j)
void integrateBz (unsigned j)
void integrateBy (unsigned j)
void smoothData (double *data, unsigned j)
void saveField (const std::string &fname, unsigned int j) const
Static Private Member Functions
static FM3DMagnetoStaticExtended create (const std::string &filename)
Private Attributes
double * FieldstrengthBx_m
double * FieldstrengthBy_m
double * FieldstrengthBz_m
double xbegin_m
double xend_m
double ybegin_m
double yend_m
double zbegin_m
double zend_m
double length_m
double hx_m
double hy_m
double hz_m
unsigned int num_gridpx_m
unsigned int num_gridpy_m
unsigned int num_gridpz_m
Friends
class _Fieldmap
Additional Inherited Members
Static Public Member Functions inherited from _Fieldmap
static Fieldmap getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions inherited from _Fieldmap
_Fieldmap ()=delete
_Fieldmap (const std::string &filename)
virtual ~_Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions inherited from _Fieldmap
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes inherited from _Fieldmap
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Detailed Description
Definition at line 6 of file FM3DMagnetoStaticExtended.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
LX
LY
LZ
HX
HY
HZ
Definition at line 47 of file FM3DMagnetoStaticExtended.h.
Constructor & Destructor Documentation
~_FM3DMagnetoStaticExtended()
_FM3DMagnetoStaticExtended::~_FM3DMagnetoStaticExtended () virtual
Definition at line 90 of file FM3DMagnetoStaticExtended.cpp.
References freeMap().
_FM3DMagnetoStaticExtended()
_FM3DMagnetoStaticExtended::_FM3DMagnetoStaticExtended (const std::string & filename) private
Definition at line 14 of file FM3DMagnetoStaticExtended.cpp.
References abs(), Units::cm2m, _Fieldmap::disableFieldmapWarning(), Physics::e, _Fieldmap::Filename_m, hx_m, hy_m, hz_m, _Fieldmap::interpreteEOF(), length_m, _Fieldmap::lines_read_m, max(), _Fieldmap::normalize_m, num_gridpx_m, num_gridpy_m, num_gridpz_m, T2DMagnetoStatic, Util::toUpper(), _Fieldmap::Type, xbegin_m, xend_m, ybegin_m, yend_m, zbegin_m, and zend_m.
Referenced by create().
Member Function Documentation
create()
FM3DMagnetoStaticExtended _FM3DMagnetoStaticExtended::create (const std::string & filename) static private
Definition at line 94 of file FM3DMagnetoStaticExtended.cpp.
References _FM3DMagnetoStaticExtended().
Referenced by _Fieldmap::getFieldmap().
freeMap()
void _FM3DMagnetoStaticExtended::freeMap () private virtual
Implements _Fieldmap.
Definition at line 632 of file FM3DMagnetoStaticExtended.cpp.
References FieldstrengthBx_m, FieldstrengthBy_m, and FieldstrengthBz_m.
Referenced by ~_FM3DMagnetoStaticExtended().
getFieldDerivative()
bool _FM3DMagnetoStaticExtended::getFieldDerivative (const Vector_t & R, Vector_t & E, Vector_t & B, const DiffDirection & dir) const virtual
Implements _Fieldmap.
Definition at line 701 of file FM3DMagnetoStaticExtended.cpp.
getFieldDimensions() [1/2]
void _FM3DMagnetoStaticExtended::getFieldDimensions (double & zBegin, double & zEnd) const virtual
Implements _Fieldmap.
Definition at line 705 of file FM3DMagnetoStaticExtended.cpp.
References zbegin_m, and zend_m.
getFieldDimensions() [2/2]
void _FM3DMagnetoStaticExtended::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const virtual
Implements _Fieldmap.
Definition at line 710 of file FM3DMagnetoStaticExtended.cpp.
References xbegin_m, xend_m, yend_m, zbegin_m, and zend_m.
getFieldstrength()
bool _FM3DMagnetoStaticExtended::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const virtual
Implements _Fieldmap.
Definition at line 689 of file FM3DMagnetoStaticExtended.cpp.
References copysign(), interpolateTrilinearly(), isInside(), and Attrib::Distribution::R.
getFrequency()
double _FM3DMagnetoStaticExtended::getFrequency () const virtual
Implements _Fieldmap.
Definition at line 726 of file FM3DMagnetoStaticExtended.cpp.
getIndex() [1/2]
_FM3DMagnetoStaticExtended::IndexTriplet _FM3DMagnetoStaticExtended::getIndex (const Vector_t & X) const inline private
Definition at line 99 of file FM3DMagnetoStaticExtended.h.
References abs(), floor(), hx_m, hy_m, hz_m, _FM3DMagnetoStaticExtended::IndexTriplet::i, _FM3DMagnetoStaticExtended::IndexTriplet::j, _FM3DMagnetoStaticExtended::IndexTriplet::k, num_gridpx_m, num_gridpy_m, num_gridpz_m, PAssert_LT, _FM3DMagnetoStaticExtended::IndexTriplet::weight, X, xbegin_m, and zbegin_m.
Referenced by getWeightedData(), integrateBx(), integrateBy(), integrateBz(), interpolateTrilinearly(), readMap(), saveField(), and smoothData().
getIndex() [2/2]
unsigned long _FM3DMagnetoStaticExtended::getIndex (unsigned int i, unsigned int j, unsigned int k) const inline private
Definition at line 90 of file FM3DMagnetoStaticExtended.h.
References num_gridpx_m, num_gridpy_m, num_gridpz_m, and PAssert_LT.
getInfo()
void _FM3DMagnetoStaticExtended::getInfo (Inform * msg) virtual
Implements _Fieldmap.
Definition at line 722 of file FM3DMagnetoStaticExtended.cpp.
References endl(), _Fieldmap::Filename_m, zbegin_m, and zend_m.
getWeightedData()
double _FM3DMagnetoStaticExtended::getWeightedData (double * data, const IndexTriplet & idx, unsigned short corner) const private
Definition at line 678 of file FM3DMagnetoStaticExtended.cpp.
References getIndex(), HX, HY, HZ, _FM3DMagnetoStaticExtended::IndexTriplet::i, _FM3DMagnetoStaticExtended::IndexTriplet::j, _FM3DMagnetoStaticExtended::IndexTriplet::k, and _FM3DMagnetoStaticExtended::IndexTriplet::weight.
Referenced by interpolateTrilinearly().
integrateBx()
void _FM3DMagnetoStaticExtended::integrateBx (unsigned j) private
Definition at line 163 of file FM3DMagnetoStaticExtended.cpp.
References FieldstrengthBx_m, FieldstrengthBy_m, getIndex(), hx_m, hy_m, num_gridpx_m, and num_gridpz_m.
Referenced by readMap().
integrateBy()
void _FM3DMagnetoStaticExtended::integrateBy (unsigned j) private
Definition at line 288 of file FM3DMagnetoStaticExtended.cpp.
References FieldstrengthBx_m, FieldstrengthBy_m, FieldstrengthBz_m, getIndex(), hx_m, hy_m, hz_m, num_gridpx_m, and num_gridpz_m.
Referenced by readMap().
integrateBz()
void _FM3DMagnetoStaticExtended::integrateBz (unsigned j) private
Definition at line 230 of file FM3DMagnetoStaticExtended.cpp.
References FieldstrengthBy_m, FieldstrengthBz_m, getIndex(), hy_m, hz_m, num_gridpx_m, and num_gridpz_m.
Referenced by readMap().
interpolateTrilinearly()
Vector_t _FM3DMagnetoStaticExtended::interpolateTrilinearly (const Vector_t & X) const private
Definition at line 644 of file FM3DMagnetoStaticExtended.cpp.
References FieldstrengthBx_m, FieldstrengthBy_m, FieldstrengthBz_m, getIndex(), getWeightedData(), HX, HY, HZ, LX, LY, LZ, and X.
Referenced by getFieldstrength().
isInside()
bool _FM3DMagnetoStaticExtended::isInside (const Vector_t & r) const inline virtual
Reimplemented from _Fieldmap.
Definition at line 84 of file FM3DMagnetoStaticExtended.h.
References abs(), length_m, xbegin_m, xend_m, and yend_m.
Referenced by getFieldstrength().
readMap()
void _FM3DMagnetoStaticExtended::readMap () private virtual
Implements _Fieldmap.
Definition at line 99 of file FM3DMagnetoStaticExtended.cpp.
References abs(), endl(), FieldstrengthBx_m, FieldstrengthBy_m, FieldstrengthBz_m, _Fieldmap::Filename_m, getIndex(), _Fieldmap::getLine(), hx_m, INFOMSG, integrateBx(), integrateBy(), integrateBz(), level3(), _Fieldmap::normalize_m, num_gridpx_m, num_gridpy_m, num_gridpz_m, smoothData(), _Fieldmap::typeset_msg(), and xbegin_m.
saveField()
void _FM3DMagnetoStaticExtended::saveField (const std::string & fname, unsigned int j) const private
Definition at line 610 of file FM3DMagnetoStaticExtended.cpp.
References FieldstrengthBx_m, FieldstrengthBy_m, FieldstrengthBz_m, getIndex(), hx_m, hy_m, hz_m, num_gridpx_m, num_gridpz_m, xbegin_m, and zbegin_m.
setFrequency()
void _FM3DMagnetoStaticExtended::setFrequency (double freq) virtual
Implements _Fieldmap.
Definition at line 730 of file FM3DMagnetoStaticExtended.cpp.
smoothData()
void _FM3DMagnetoStaticExtended::smoothData (double * data, unsigned j) private
Definition at line 505 of file FM3DMagnetoStaticExtended.cpp.
References abs(), getIndex(), num_gridpx_m, num_gridpy_m, num_gridpz_m, pow(), and sum().
Referenced by readMap().
swap()
void _FM3DMagnetoStaticExtended::swap () virtual
Implements _Fieldmap.
Definition at line 719 of file FM3DMagnetoStaticExtended.cpp.
Friends And Related Function Documentation
_Fieldmap
friend class _Fieldmap friend
Definition at line 80 of file FM3DMagnetoStaticExtended.h.
Member Data Documentation
FieldstrengthBx_m
double* _FM3DMagnetoStaticExtended::FieldstrengthBx_m private
3D array with Bx, read in first along z0 - r0 to rN then z1 - r0 to rN until zN - r0 to rN
Definition at line 62 of file FM3DMagnetoStaticExtended.h.
Referenced by freeMap(), integrateBx(), integrateBy(), interpolateTrilinearly(), readMap(), and saveField().
FieldstrengthBy_m
double* _FM3DMagnetoStaticExtended::FieldstrengthBy_m private
3D array with By, read in like Bx
Definition at line 63 of file FM3DMagnetoStaticExtended.h.
Referenced by freeMap(), integrateBx(), integrateBy(), integrateBz(), interpolateTrilinearly(), readMap(), and saveField().
FieldstrengthBz_m
double* _FM3DMagnetoStaticExtended::FieldstrengthBz_m private
3D array with Bz, read in like Bx
Definition at line 64 of file FM3DMagnetoStaticExtended.h.
Referenced by freeMap(), integrateBy(), integrateBz(), interpolateTrilinearly(), readMap(), and saveField().
hx_m
double _FM3DMagnetoStaticExtended::hx_m private
length between points in grid, x-direction, m
Definition at line 73 of file FM3DMagnetoStaticExtended.h.
Referenced by _FM3DMagnetoStaticExtended(), getIndex(), integrateBx(), integrateBy(), readMap(), and saveField().
hy_m
double _FM3DMagnetoStaticExtended::hy_m private
length between points in grid, y-direction, m
Definition at line 74 of file FM3DMagnetoStaticExtended.h.
Referenced by _FM3DMagnetoStaticExtended(), getIndex(), integrateBx(), integrateBy(), integrateBz(), and saveField().
hz_m
double _FM3DMagnetoStaticExtended::hz_m private
length between points in grid, z-direction, m
Definition at line 75 of file FM3DMagnetoStaticExtended.h.
Referenced by _FM3DMagnetoStaticExtended(), getIndex(), integrateBy(), integrateBz(), and saveField().
length_m
double _FM3DMagnetoStaticExtended::length_m private
Definition at line 72 of file FM3DMagnetoStaticExtended.h.
Referenced by _FM3DMagnetoStaticExtended(), and isInside().
num_gridpx_m
unsigned int _FM3DMagnetoStaticExtended::num_gridpx_m private
Read in number of points after 0(not counted here) in grid, x-direction
Definition at line 76 of file FM3DMagnetoStaticExtended.h.
Referenced by _FM3DMagnetoStaticExtended(), getIndex(), integrateBx(), integrateBy(), integrateBz(), readMap(), saveField(), and smoothData().
num_gridpy_m
unsigned int _FM3DMagnetoStaticExtended::num_gridpy_m private
Read in number of points after 0(not counted here) in grid, y-direction
Definition at line 77 of file FM3DMagnetoStaticExtended.h.
Referenced by _FM3DMagnetoStaticExtended(), getIndex(), readMap(), and smoothData().
num_gridpz_m
unsigned int _FM3DMagnetoStaticExtended::num_gridpz_m private
Read in number of points after 0(not counted here) in grid, z-direction
Definition at line 78 of file FM3DMagnetoStaticExtended.h.
Referenced by _FM3DMagnetoStaticExtended(), getIndex(), integrateBx(), integrateBy(), integrateBz(), readMap(), saveField(), and smoothData().
xbegin_m
double _FM3DMagnetoStaticExtended::xbegin_m private
Definition at line 66 of file FM3DMagnetoStaticExtended.h.
Referenced by _FM3DMagnetoStaticExtended(), getFieldDimensions(), getIndex(), isInside(), readMap(), and saveField().
xend_m
double _FM3DMagnetoStaticExtended::xend_m private
Definition at line 67 of file FM3DMagnetoStaticExtended.h.
Referenced by _FM3DMagnetoStaticExtended(), getFieldDimensions(), and isInside().
ybegin_m
double _FM3DMagnetoStaticExtended::ybegin_m private
Definition at line 68 of file FM3DMagnetoStaticExtended.h.
Referenced by _FM3DMagnetoStaticExtended().
yend_m
double _FM3DMagnetoStaticExtended::yend_m private
Definition at line 69 of file FM3DMagnetoStaticExtended.h.
Referenced by _FM3DMagnetoStaticExtended(), getFieldDimensions(), and isInside().
zbegin_m
double _FM3DMagnetoStaticExtended::zbegin_m private
Definition at line 70 of file FM3DMagnetoStaticExtended.h.
Referenced by _FM3DMagnetoStaticExtended(), getFieldDimensions(), getIndex(), getInfo(), and saveField().
zend_m
double _FM3DMagnetoStaticExtended::zend_m private
Definition at line 71 of file FM3DMagnetoStaticExtended.h.
Referenced by _FM3DMagnetoStaticExtended(), getFieldDimensions(), and getInfo().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/FM3DMagnetoStaticExtended.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/FM3DMagnetoStaticExtended.cpp