OPAL (Object Oriented Parallel Accelerator Library): TpsRep< T > Class Template Reference
TpsRep< T > Class Template Reference
#include <Tps.h>
Private Member Functions
TpsRep< T > * clone ()
TpsRep< T > * grab ()
T * data ()
TpsRep< T > & operator= (const TpsRep< T > &)
Static Private Member Functions
static void * operator new (size_t s, size_t extra)
static void operator delete (void *)
static TpsRep< T > * create (int maxOrder, int trcOrder, int variables)
static TpsRep< T > * zero ()
static void release (TpsRep< T > *)
Private Attributes
int ref
int maxOrd
int trcOrd
int len
TpsData * help
Friends
class Tps< T >
Detailed Description
template<class T>
class TpsRep< T >
Definition at line 28 of file Tps.h.
Member Function Documentation
clone()
template<class T > TpsRep< T > * TpsRep< T >::clone () inline private
Definition at line 184 of file Tps.hpp.
References TpsRep< T >::data(), TpsRep< T >::help, TpsRep< T >::len, TpsRep< T >::maxOrd, TpsRep< T >::ref, Attrib::Legacy::Distribution::T, and TpsRep< T >::trcOrd.
create()
template<class T > TpsRep< T > * TpsRep< T >::create (int maxOrder, int trcOrder, int variables) inline static private
Definition at line 144 of file Tps.hpp.
References TpsRep< T >::data(), TpsData::getSize(), TpsData::getTpsData(), TpsRep< T >::help, TpsRep< T >::len, TpsRep< T >::maxOrd, TpsRep< T >::ref, Attrib::Legacy::Distribution::T, and TpsRep< T >::trcOrd.
Referenced by Tps< T >::derivative(), Tps< T >::filter(), Tps< T >::integral(), Tps< T >::makeMonomial(), Tps< T >::makeVariable(), Tps< T >::makeVarPower(), Tps< T >::multiply(), Tps< T >::multiplyVariable(), Tps< T >::operator+=(), Tps< T >::operator-(), Tps< T >::operator-=(), Tps< T >::scaleMonomials(), and Tps< T >::setCoefficient().
data()
template<class T > T * TpsRep< T >::data () inline private
Definition at line 118 of file Tps.hpp.
References Attrib::Legacy::Distribution::T.
Referenced by TpsRep< T >::clone(), TpsRep< T >::create(), Tps< T >::derivative(), Tps< T >::filter(), Tps< T >::integral(), Tps< T >::makeVariable(), Tps< T >::multiplyVariable(), Tps< T >::operator+=(), Tps< T >::operator-(), Tps< T >::operator-=(), Tps< T >::setCoefficient(), and TpsRep< T >::zero().
grab()
template<class T > TpsRep< T > * TpsRep< T >::grab () inline private
Definition at line 202 of file Tps.hpp.
References Hypervolume::ref.
operator delete()
template<class T > void TpsRep< T >::operator delete (void * p) inline static private
Definition at line 136 of file Tps.hpp.
operator new()
template<class T > void * TpsRep< T >::operator new (size_t s, size_t extra) inline static private
Definition at line 126 of file Tps.hpp.
operator=()
template<class T> TpsRep<T>& TpsRep< T >::operator= (const TpsRep< T > &) private
release()
template<class T > void TpsRep< T >::release (TpsRep< T > * p) inline static private
Definition at line 209 of file Tps.hpp.
References TpsRep< T >::ref.
Referenced by Tps< T >::clear(), Tps< T >::operator+=(), Tps< T >::operator-=(), Tps< T >::operator=(), Tps< T >::setCoefficient(), and Tps< T >::~Tps().
zero()
template<class T > TpsRep< T > * TpsRep< T >::zero () inline static private
Definition at line 168 of file Tps.hpp.
References TpsRep< T >::data(), TpsRep< T >::help, TpsRep< T >::len, TpsRep< T >::maxOrd, TpsRep< T >::ref, Attrib::Legacy::Distribution::T, and TpsRep< T >::trcOrd.
Referenced by Tps< T >::clear(), and Tps< T >::operator=().
Friends And Related Function Documentation
Tps< T >
template<class T> friend class Tps< T > friend
Definition at line 78 of file Tps.hpp.
Member Data Documentation
help
template<class T> TpsData* TpsRep< T >::help private
Definition at line 107 of file Tps.hpp.
Referenced by TpsRep< T >::clone(), TpsRep< T >::create(), and TpsRep< T >::zero().
len
template<class T> int TpsRep< T >::len private
Definition at line 104 of file Tps.hpp.
Referenced by TpsRep< T >::clone(), TpsRep< T >::create(), and TpsRep< T >::zero().
maxOrd
template<class T> int TpsRep< T >::maxOrd private
Definition at line 100 of file Tps.hpp.
Referenced by TpsRep< T >::clone(), TpsRep< T >::create(), and TpsRep< T >::zero().
ref
template<class T> int TpsRep< T >::ref private
Definition at line 97 of file Tps.hpp.
Referenced by TpsRep< T >::clone(), TpsRep< T >::create(), TpsRep< T >::release(), and TpsRep< T >::zero().
trcOrd
template<class T> int TpsRep< T >::trcOrd private
Definition at line 101 of file Tps.hpp.
Referenced by TpsRep< T >::clone(), TpsRep< T >::create(), and TpsRep< T >::zero().
The documentation for this class was generated from the following files:
src/Classic/Algebra/Tps.h
src/Classic/Algebra/Tps.hpp