OPAL (Object Oriented Parallel Accelerator Library): AmrPartBunch Class Reference
AmrPartBunch Class Reference
#include <AmrPartBunch.h>
Public Types
typedef AmrParticle_t pbase_t
Public Types inherited from PartBunchBase< double, 3 >
enum UnitState_t
typedef AbstractParticle< double, Dim >::ParticlePos_t ParticlePos_t
typedef AbstractParticle< double, Dim >::ParticleIndex_t ParticleIndex_t
typedef AbstractParticle< double, Dim >::UpdateFlags UpdateFlags_t
typedef AbstractParticle< double, Dim >::Position_t Position_t
typedef std::pair< Vector_t, Vector_t > VectorPair_t
Public Member Functions
AmrPartBunch (const PartData *ref)
AmrPartBunch (const PartData *ref, pbase_t *pbase_p)
~AmrPartBunch ()
pbase_t * getAmrParticleBase ()
const pbase_t * getAmrParticleBase () const
void initialize (FieldLayout_t *fLayout)
void do_binaryRepart ()
Vector_t get_hr () const
void set_meshEnlargement (double dh)
VectorPair_t getEExtrema ()
double getRho (int x, int y, int z)
FieldLayout_t & getFieldLayout ()
void boundp ()
void computeSelfFields ()
void computeSelfFields (int bin)
void computeSelfFields_cycl (double gamma)
void computeSelfFields_cycl (int bin)
void setSolver (FieldSolver *fs)
virtual void setBinCharge (int, double)
Set the charge of one bin to the value of q and all other to zero.
virtual void setBinCharge (int)
Set the charge of all other the ones in bin to zero.
const AmrObject * getAmrObject () const
PoissonSolver * getFieldSolver ()
const PoissonSolver * getFieldSolver () const
void setBaseLevelMeshSpacing (const Vector_t &hr)
void setAmrDomainRatio (const std::vector< double > &ratio)
void gatherLevelStatistics ()
const size_t & getLevelStatistics (int l) const
void updateLorentzFactor (int bin=0)
void updateLorentzFactor (double gamma)
void setBCAllPeriodic ()
void setBCAllOpen ()
void setBCForDCBeam ()
Public Member Functions inherited from PartBunchBase< double, 3 >
virtual ~PartBunchBase ()
PartBunchBase (AbstractParticle< double, Dim > *pb, const PartData *ref)
PartBunchBase (const PartBunchBase &rhs)=delete
bool getIfBeamEmitting ()
int getLastEmittedEnergyBin ()
size_t getNumberOfEmissionSteps ()
int getNumberOfEnergyBins ()
void Rebin ()
void setEnergyBins (int numberOfEnergyBins)
bool weHaveEnergyBins ()
void switchToUnitlessPositions (bool use_dt_per_particle=false)
void switchOffUnitlessPositions (bool use_dt_per_particle=false)
void setDistribution (Distribution *d, std::vector< Distribution * > addedDistributions, size_t &np)
void setDistribution (Distribution *d, size_t numberOfParticles, double current, const Beamline &bl)
bool isGridFixed () const
bool hasBinning () const
void setTEmission (double t)
double getTEmission ()
bool doEmission ()
bool weHaveBins () const
void setPBins (PartBins *pbin)
void setPBins (PartBinsCyc *pbin)
size_t emitParticles (double eZ)
Emit particles in the given bin i.e. copy the particles from the bin structure into the particle container.
void updateNumTotal ()
void rebin ()
int getLastemittedBin ()
void setLocalBinCount (size_t num, int bin)
void calcGammas ()
Compute the gammas of all bins.
void calcGammas_cycl ()
void calcDebyeLength ()
Compute the (global) Debye length for the beam.
double getBinGamma (int bin)
Get gamma of one bin.
size_t calcNumPartsOutside (Vector_t x)
returns the number of particles outside of a box defined by x
void calcLineDensity (unsigned int nBins, std::vector< double > &lineDensity, std::pair< double, double > &meshInfo)
calculates the 1d line density (not normalized) and append it to a file.
void setBeamFrequency (double v)
void boundp_destroyCycl ()
size_t boundp_destroyT ()
size_t destroyT ()
virtual double getPx (int i)
virtual double getPy (int i)
virtual double getPz (int i)
virtual double getPx0 (int i)
virtual double getPy0 (int i)
virtual double getX (int i)
virtual double getY (int i)
virtual double getZ (int i)
virtual double getX0 (int i)
virtual double getY0 (int i)
virtual void setZ (int i, double zcoo)
void get_bounds (Vector_t &rmin, Vector_t &rmax) const
void getLocalBounds (Vector_t &rmin, Vector_t &rmax) const
std::pair< Vector_t, double > getBoundingSphere ()
std::pair< Vector_t, double > getLocalBoundingSphere ()
void push_back (OpalParticle const &p)
void setParticle (FVector< double, 6 > z, int ii)
void setParticle (OpalParticle const &p, int ii)
OpalParticle getParticle (int ii)
ConstIterator begin () const
ConstIterator end () const
void maximumAmplitudes (const FMatrix< double, 6, 6 > &D, double &axmax, double &aymax)
Return maximum amplitudes.
void setdT (double dt)
double getdT () const
void setT (double t)
void incrementT ()
double getT () const
double get_sPos () const
void set_sPos (double s)
double get_gamma () const
double get_meanKineticEnergy () const
double get_temperature () const
double get_debyeLength () const
double get_plasmaParameter () const
double get_rmsDensity () const
Vector_t get_origin () const
Vector_t get_maxExtent () const
Vector_t get_centroid () const
Vector_t get_rrms () const
Vector_t get_rprms () const
Vector_t get_rmean () const
Vector_t get_prms () const
Vector_t get_pmean () const
Vector_t get_pmean_Distribution () const
Vector_t get_emit () const
Vector_t get_norm_emit () const
Vector_t get_halo () const
Vector_t get_68Percentile () const
Vector_t get_95Percentile () const
Vector_t get_99Percentile () const
Vector_t get_99_99Percentile () const
Vector_t get_normalizedEps_68Percentile () const
Vector_t get_normalizedEps_95Percentile () const
Vector_t get_normalizedEps_99Percentile () const
Vector_t get_normalizedEps_99_99Percentile () const
double get_Dx () const
double get_Dy () const
double get_DDx () const
double get_DDy () const
void gatherLoadBalanceStatistics ()
size_t getLoadBalance (int p) const
void get_PBounds (Vector_t &min, Vector_t &max) const
void calcBeamParameters ()
void calcBeamParametersInitial ()
double getCouplingConstant () const
void setCouplingConstant (double c)
void setCharge (double q)
void setChargeZeroPart (double q)
void setMass (double mass)
void setMassZeroPart (double mass)
double getCharge () const
get the total charge per simulation particle
double getChargePerParticle () const
get the macro particle charge
double getMassPerParticle () const
bool hasFieldSolver ()
FieldSolverType getFieldSolverType () const
Return the fieldsolver type if we have a fieldsolver.
void setStepsPerTurn (int n)
int getStepsPerTurn () const
void setGlobalTrackStep (long long n)
step in multiple TRACK commands
long long getGlobalTrackStep () const
void setLocalTrackStep (long long n)
step in a TRACK command
void incTrackSteps ()
long long getLocalTrackStep () const
void setNumBunch (short n)
short getNumBunch () const
void setTotalNumPerBunch (size_t numpart, short n)
size_t getTotalNumPerBunch (short n) const
void setLocalNumPerBunch (size_t numpart, short n)
size_t getLocalNumPerBunch (short n) const
void countTotalNumPerBunch ()
void setGlobalMeanR (Vector_t globalMeanR)
Vector_t getGlobalMeanR ()
void setGlobalToLocalQuaternion (Quaternion_t globalToLocalQuaternion)
Quaternion_t getGlobalToLocalQuaternion ()
void setSteptoLastInj (int n)
int getSteptoLastInj () const
double calcMeanPhi ()
calculate average angle of longitudinal direction of bins
bool resetPartBinID2 (const double eta)
reset Bin[] for each particle according to the method given in paper PAST-AB(064402) by G. Fubiani et al.
bool resetPartBinBunch ()
double getdE () const
virtual double getGamma (int i)
virtual double getBeta (int i)
virtual void actT ()
const PartData * getReference () const
double getEmissionDeltaT ()
DistributionType getDistType () const
double getMomentumTolerance () const
Quaternion_t getQKs3D ()
void setQKs3D (Quaternion_t q)
Vector_t getKs3DRefr ()
void setKs3DRefr (Vector_t r)
Vector_t getKs3DRefp ()
void setKs3DRefp (Vector_t p)
void iterateEmittedBin (int binNumber)
void calcEMean ()
Inform & print (Inform &os)
virtual void runTests ()
virtual void resetInterpolationCache (bool clearCache=false)
virtual void swap (unsigned int i, unsigned int j)
virtual void resizeMesh ()
size_t getTotalNum () const
void setTotalNum (size_t n)
void setLocalNum (size_t n)
size_t getLocalNum () const
size_t getDestroyNum () const
size_t getGhostNum () const
ParticleLayout< double, Dim > & getLayout ()
const ParticleLayout< double, Dim > & getLayout () const
bool getUpdateFlag (UpdateFlags_t f) const
void setUpdateFlag (UpdateFlags_t f, bool val)
ParticleBConds< Position_t, Dimension > & getBConds ()
void setBConds (const ParticleBConds< Position_t, Dimension > &bc)
bool singleInitNode () const
void resetID ()
void update ()
void update (const ParticleAttrib< char > &canSwap)
void createWithID (unsigned id)
void create (size_t M)
void globalCreate (size_t np)
void destroy (size_t M, size_t I, bool doNow=false)
void performDestroy (bool updateLocalNum=false)
void ghostDestroy (size_t M, size_t I)
FMatrix< double, 2 *Dim, 2 *Dim > getSigmaMatrix () const
double getQ () const
Access to reference data.
double getM () const
double getP () const
double getE () const
ParticleOrigin getPOrigin () const
ParticleType getPType () const
double getInitialBeta () const
double getInitialGamma () const
void resetQ (double q)
void resetM (double m)
void setPOrigin (ParticleOrigin)
void setPType (const std::string &type)
Private Member Functions
void updateFieldContainers_m ()
void updateDomainLength (Vektor< int, 3 > &grid)
void updateFields (const Vector_t &hr, const Vector_t &origin)
Private Attributes
AmrObject * amrobj_mp
pbase_t * amrpbase_mp
FieldLayout_t * fieldlayout_m
std::unique_ptr< size_t[]> globalPartPerLevel_m
Additional Inherited Members
Public Attributes inherited from PartBunchBase< double, 3 >
ParticlePos_t & R
ParticleIndex_t & ID
ParticleAttrib< Vector_t > P
ParticleAttrib< double > Q
ParticleAttrib< double > M
ParticleAttrib< double > Phi
ParticleAttrib< Vector_t > Ef
ParticleAttrib< Vector_t > Eftmp
ParticleAttrib< Vector_t > Bf
ParticleAttrib< int > Bin
ParticleAttrib< double > dt
ParticleAttrib< ParticleType > PType
ParticleAttrib< ParticleOrigin > POrigin
ParticleAttrib< int > TriID
ParticleAttrib< short > cavityGapCrossed
ParticleAttrib< short > bunchNum
Vector_t RefPartR_m
Vector_t RefPartP_m
CoordinateSystemTrafo toLabTrafo_m
ParticleOrigin refPOrigin_m
ParticleType refPType_m
PartBins * pbin_m
IpplTimings::TimerRef distrReload_m
timer for IC, can not be in Distribution.h
IpplTimings::TimerRef distrCreate_m
double dtScInit_m
double deltaTau_m
Static Public Attributes inherited from PartBunchBase< double, 3 >
static const unsigned Dimension
Protected Member Functions inherited from PartBunchBase< double, 3 >
size_t calcMoments ()
void calcMomentsInitial ()
double calculateAngle (double x, double y)
angle range [0~2PI) degree
Protected Attributes inherited from PartBunchBase< double, 3 >
IpplTimings::TimerRef boundpTimer_m
IpplTimings::TimerRef boundpBoundsTimer_m
IpplTimings::TimerRef boundpUpdateTimer_m
IpplTimings::TimerRef statParamTimer_m
IpplTimings::TimerRef histoTimer_m
IpplTimings::TimerRef selfFieldTimer_m
timer for selfField calculation
const PartData * reference
UnitState_t unit_state_
UnitState_t stateOfLastBoundP_
double centroid_m [2 *Dim]
holds the centroid of the beam
double dt_m
holds the timestep in seconds
double t_m
holds the actual time of the integration
double spos_m
the position along design trajectory
Vector_t globalMeanR_m
Quaternion_t globalToLocalQuaternion_m
Vector_t rmax_m
maximal extend of particles
Vector_t rmin_m
minimal extend of particles
double rmsDensity_m
Vector_t hr_m
meshspacing of cartesian mesh
Vektor< int, 3 > nr_m
meshsize of cartesian mesh
FieldSolver * fs_m
stores the used field solver
double couplingConstant_m
double qi_m
double massPerParticle_m
int distDump_m
counter to store the distribution dump
double dh_m
Mesh enlargement.
double tEmission_m
relative enlargement of the mesh
std::unique_ptr< double[]> bingamma_m
holds the gamma of the bin
std::unique_ptr< size_t[]> binemitted_m
int stepsPerTurn_m
steps per turn for OPAL-cycl
long long localTrackStep_m
step in a TRACK command
long long globalTrackStep_m
if multiple TRACK commands
short numBunch_m
current bunch number
std::vector< size_t > bunchTotalNum_m
number of particles per bunch
std::vector< size_t > bunchLocalNum_m
int SteptoLastInj_m
std::unique_ptr< size_t[]> globalPartPerNode_m
Distribution * dist_m
DistributionMoments momentsComputer_m
bool dcBeam_m
double periodLength_m
std::shared_ptr< AbstractParticle< double, Dim > > pbase_m
Detailed Description
Definition at line 27 of file AmrPartBunch.h.
Member Typedef Documentation
pbase_t
typedef AmrParticle_t AmrPartBunch::pbase_t
Definition at line 30 of file AmrPartBunch.h.
Constructor & Destructor Documentation
AmrPartBunch() [1/2]
AmrPartBunch::AmrPartBunch (const PartData * ref)
Definition at line 25 of file AmrPartBunch.cpp.
AmrPartBunch() [2/2]
AmrPartBunch::AmrPartBunch (const PartData * ref, pbase_t * pbase_p)
Definition at line 34 of file AmrPartBunch.cpp.
~AmrPartBunch()
AmrPartBunch::~AmrPartBunch ()
Definition at line 43 of file AmrPartBunch.cpp.
Member Function Documentation
boundp()
void AmrPartBunch::boundp () virtual
Reimplemented from PartBunchBase< double, 3 >.
Definition at line 137 of file AmrPartBunch.cpp.
References amrobj_mp, amrpbase_mp, PartBunchBase< double, 3 >::boundpTimer_m, AmrParticleBase< PLayout >::domainMapping(), PartBunchBase< double, 3 >::ID, ParticleAttrib< T >::isDirty(), AmrParticleBase< PLayout >::isForbidTransform(), PartBunchBase< double, 3 >::R, ParticleAttrib< T >::resetDirtyFlag(), AmrParticleBase< PLayout >::setForbidTransform(), IpplTimings::startTimer(), PartBunchBase< double, 3 >::stateOfLastBoundP_, IpplTimings::stopTimer(), PartBunchBase< double, 3 >::unit_state_, PartBunchBase< double, 3 >::update(), and updateLorentzFactor().
computeSelfFields() [1/2]
void AmrPartBunch::computeSelfFields () virtual
Implements PartBunchBase< double, 3 >.
Definition at line 178 of file AmrPartBunch.cpp.
References amrobj_mp, AmrObject::computeSelfFields(), PartBunchBase< double, 3 >::fs_m, FieldSolver::hasValidSolver(), PartBunchBase< double, 3 >::selfFieldTimer_m, IpplTimings::startTimer(), and IpplTimings::stopTimer().
computeSelfFields() [2/2]
void AmrPartBunch::computeSelfFields (int bin) virtual
Implements PartBunchBase< double, 3 >.
Definition at line 191 of file AmrPartBunch.cpp.
References amrobj_mp, AmrObject::computeSelfFields(), PartBunchBase< double, 3 >::selfFieldTimer_m, IpplTimings::startTimer(), and IpplTimings::stopTimer().
computeSelfFields_cycl() [1/2]
void AmrPartBunch::computeSelfFields_cycl (double gamma) virtual
Implements PartBunchBase< double, 3 >.
Definition at line 198 of file AmrPartBunch.cpp.
References amrobj_mp, AmrObject::computeSelfFields_cycl(), PartBunchBase< double, 3 >::selfFieldTimer_m, IpplTimings::startTimer(), and IpplTimings::stopTimer().
computeSelfFields_cycl() [2/2]
void AmrPartBunch::computeSelfFields_cycl (int bin) virtual
Implements PartBunchBase< double, 3 >.
Definition at line 205 of file AmrPartBunch.cpp.
References amrobj_mp, AmrObject::computeSelfFields_cycl(), AmrObject::initFineLevels(), AmrObject::isRefined(), PartBunchBase< double, 3 >::selfFieldTimer_m, IpplTimings::startTimer(), and IpplTimings::stopTimer().
do_binaryRepart()
void AmrPartBunch::do_binaryRepart () virtual
Reimplemented from PartBunchBase< double, 3 >.
Definition at line 61 of file AmrPartBunch.cpp.
References amrobj_mp, amrpbase_mp, AmrParticleBase< PLayout >::domainMapping(), AmrObject::initFineLevels(), AmrParticleBase< PLayout >::isForbidTransform(), AmrObject::isRefined(), AmrParticleBase< PLayout >::setForbidTransform(), PartBunchBase< double, 3 >::update(), and updateLorentzFactor().
Referenced by set_meshEnlargement().
gatherLevelStatistics()
void AmrPartBunch::gatherLevelStatistics ()
Definition at line 225 of file AmrPartBunch.cpp.
References amrobj_mp, amrpbase_mp, AmrParticleBase< PLayout >::getLocalNumPerLevel(), globalPartPerLevel_m, AmrObject::maxLevel(), and reduce().
get_hr()
Vector_t AmrPartBunch::get_hr () const virtual
Reimplemented from PartBunchBase< double, 3 >.
Definition at line 93 of file AmrPartBunch.cpp.
References amrpbase_mp, AmrParticleBase< PLayout >::getScalingFactor(), and PartBunchBase< double, 3 >::hr_m.
getAmrObject()
const AmrObject* AmrPartBunch::getAmrObject () const inline
Definition at line 80 of file AmrPartBunch.h.
References amrobj_mp.
Referenced by GridLBalWriter::fillHeader(), and GridLBalWriter::write().
getAmrParticleBase() [1/2]
AmrPartBunch::pbase_t * AmrPartBunch::getAmrParticleBase ()
Definition at line 46 of file AmrPartBunch.cpp.
References amrpbase_mp.
Referenced by AmrBoxLib::computeSelfFields_cycl(), AmrBoxLib::initFineLevels(), AmrBoxLib::postRegrid_m(), MultiBunchHandler::readBunch(), AmrBoxLib::solvePoisson_m(), AmrBoxLib::tagForChargeDensity_m(), AmrBoxLib::tagForMaxNumParticles_m(), AmrBoxLib::tagForMinNumParticles_m(), AmrBoxLib::tagForMomenta_m(), AmrYtWriter::writeBunch(), and AmrYtWriter::writeParticles_m().
getAmrParticleBase() [2/2]
const AmrPartBunch::pbase_t * AmrPartBunch::getAmrParticleBase () const
Definition at line 51 of file AmrPartBunch.cpp.
References amrpbase_mp.
getEExtrema()
AmrPartBunch::VectorPair_t AmrPartBunch::getEExtrema () virtual
Implements PartBunchBase< double, 3 >.
Definition at line 112 of file AmrPartBunch.cpp.
References amrobj_mp, and AmrObject::getEExtrema().
getFieldLayout()
FieldLayout_t & AmrPartBunch::getFieldLayout () virtual
Implements PartBunchBase< double, 3 >.
Definition at line 130 of file AmrPartBunch.cpp.
References fieldlayout_m.
getFieldSolver() [1/2]
PoissonSolver* AmrPartBunch::getFieldSolver () inline
Definition at line 84 of file AmrPartBunch.h.
References PartBunchBase< double, 3 >::fs_m, and FieldSolver::solver_m.
Referenced by AmrBoxLib::computeSelfFields_cycl(), AmrBoxLib::postRegrid_m(), and AmrBoxLib::solvePoisson_m().
getFieldSolver() [2/2]
const PoissonSolver* AmrPartBunch::getFieldSolver () const inline
Definition at line 88 of file AmrPartBunch.h.
References PartBunchBase< double, 3 >::fs_m, and FieldSolver::solver_m.
getLevelStatistics()
const size_t & AmrPartBunch::getLevelStatistics (int l) const
Only a valid call of root core (core 0)
Parameters
l is the level
Definition at line 246 of file AmrPartBunch.cpp.
References globalPartPerLevel_m.
getRho()
double AmrPartBunch::getRho (int x, int y, int z) virtual
Implements PartBunchBase< double, 3 >.
Definition at line 116 of file AmrPartBunch.cpp.
References amrobj_mp, and AmrObject::getRho().
initialize()
void AmrPartBunch::initialize (FieldLayout_t * fLayout) virtual
Implements PartBunchBase< double, 3 >.
Definition at line 56 of file AmrPartBunch.cpp.
set_meshEnlargement()
void AmrPartBunch::set_meshEnlargement (double dh) virtual
Reimplemented from PartBunchBase< double, 3 >.
Definition at line 99 of file AmrPartBunch.cpp.
References amrpbase_mp, do_binaryRepart(), AmrParticleBase< PLayout >::getAmrLayout(), PartBunchBase< T, Dim >::set_meshEnlargement(), and BoxLibLayout< T, Dim >::setBoundingBox().
setAmrDomainRatio()
void AmrPartBunch::setAmrDomainRatio (const std::vector< double > & ratio)
Change the AMR Poisson computation domain.
Parameters
ratio per direction.
Definition at line 220 of file AmrPartBunch.cpp.
References amrpbase_mp, AmrParticleBase< PLayout >::getAmrLayout(), and BoxLibLayout< T, Dim >::setDomainRatio().
setBaseLevelMeshSpacing()
void AmrPartBunch::setBaseLevelMeshSpacing (const Vector_t & hr) inline
Definition at line 92 of file AmrPartBunch.h.
References PartBunchBase< double, 3 >::hr_m.
Referenced by AmrBoxLib::updateMesh().
setBCAllOpen()
void AmrPartBunch::setBCAllOpen () inline virtual
Reimplemented from PartBunchBase< double, 3 >.
Definition at line 130 of file AmrPartBunch.h.
setBCAllPeriodic()
void AmrPartBunch::setBCAllPeriodic () inline virtual
Reimplemented from PartBunchBase< double, 3 >.
Definition at line 129 of file AmrPartBunch.h.
setBCForDCBeam()
void AmrPartBunch::setBCForDCBeam () inline virtual
Reimplemented from PartBunchBase< double, 3 >.
Definition at line 131 of file AmrPartBunch.h.
setBinCharge() [1/2]
virtual void AmrPartBunch::setBinCharge (int bin, double q) inline virtual
Set the charge of one bin to the value of q and all other to zero.
Reimplemented from PartBunchBase< double, 3 >.
Definition at line 73 of file AmrPartBunch.h.
setBinCharge() [2/2]
virtual void AmrPartBunch::setBinCharge (int bin) inline virtual
Set the charge of all other the ones in bin to zero.
Reimplemented from PartBunchBase< double, 3 >.
Definition at line 74 of file AmrPartBunch.h.
setSolver()
void AmrPartBunch::setSolver (FieldSolver * fs) inline virtual
Reimplemented from PartBunchBase< double, 3 >.
Definition at line 68 of file AmrPartBunch.h.
References amrobj_mp, Hypervolume::fs, FieldSolver::getAmrObject(), and PartBunchBase< T, Dim >::setSolver().
updateDomainLength()
void AmrPartBunch::updateDomainLength (Vektor< int, 3 > & grid) private virtual
Implements PartBunchBase< double, 3 >.
Definition at line 291 of file AmrPartBunch.cpp.
References amrobj_mp, and AmrObject::getBaseLevelGridPoints().
updateFieldContainers_m()
void AmrPartBunch::updateFieldContainers_m () private
Definition at line 289 of file AmrPartBunch.cpp.
updateFields()
void AmrPartBunch::updateFields (const Vector_t & hr, const Vector_t & origin) private virtual
Reimplemented from PartBunchBase< double, 3 >.
Definition at line 296 of file AmrPartBunch.cpp.
updateLorentzFactor() [1/2]
void AmrPartBunch::updateLorentzFactor (int bin = 0)
Update the Lorentz factor before every domainMapping in order to have the correct boosted frame for the particle redistribution, regrid and computation of the self-field forces
Parameters
bin is the energy bin
Definition at line 251 of file AmrPartBunch.cpp.
References PartBunchBase< double, 3 >::get_gamma(), PartBunchBase< double, 3 >::getBinGamma(), and PartBunchBase< double, 3 >::weHaveBins().
Referenced by boundp(), AmrBoxLib::computeSelfFields_cycl(), and do_binaryRepart().
updateLorentzFactor() [2/2]
void AmrPartBunch::updateLorentzFactor (double gamma)
Update the Lorentz factor before every domainMapping in order to have the correct boosted frame for the particle redistribution, regrid and computation of the self-field forces. This function is only used in the single bunch case.
Parameters
gamma is the Lorentz factor
Definition at line 275 of file AmrPartBunch.cpp.
References amrpbase_mp, OpalData::getInstance(), and AmrParticleBase< PLayout >::setLorentzFactor().
Member Data Documentation
amrobj_mp
AmrObject* AmrPartBunch::amrobj_mp private
Definition at line 145 of file AmrPartBunch.h.
Referenced by boundp(), computeSelfFields(), computeSelfFields_cycl(), do_binaryRepart(), gatherLevelStatistics(), getAmrObject(), getEExtrema(), getRho(), setSolver(), and updateDomainLength().
amrpbase_mp
pbase_t* AmrPartBunch::amrpbase_mp private
Definition at line 146 of file AmrPartBunch.h.
Referenced by boundp(), do_binaryRepart(), gatherLevelStatistics(), get_hr(), getAmrParticleBase(), set_meshEnlargement(), setAmrDomainRatio(), and updateLorentzFactor().
fieldlayout_m
FieldLayout_t* AmrPartBunch::fieldlayout_m private
Definition at line 151 of file AmrPartBunch.h.
Referenced by getFieldLayout().
globalPartPerLevel_m
std::unique_ptr<size_t[]> AmrPartBunch::globalPartPerLevel_m private
Definition at line 153 of file AmrPartBunch.h.
Referenced by gatherLevelStatistics(), and getLevelStatistics().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algorithms/AmrPartBunch.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algorithms/AmrPartBunch.cpp