OPAL (Object Oriented Parallel Accelerator Library): mslang::Rectangle Struct Reference
mslang::Rectangle Struct Reference
#include <Rectangle.h>
Public Member Functions
Rectangle ()
Rectangle (const Rectangle &right)
virtual ~Rectangle ()
virtual void print (int indentwidth)
virtual void computeBoundingBox ()
virtual bool isInside (const Vector_t &R) const
virtual void writeGnuplot (std::ofstream &out) const
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
virtual std::shared_ptr< Base > clone () const
Public Member Functions inherited from mslang::Base
Base ()
Base (const Base &right)
virtual ~Base ()
virtual void divideBy (std::vector< std::shared_ptr< Base > > &divisors)
Public Member Functions inherited from mslang::Function
virtual ~Function ()
virtual void apply (std::vector< std::shared_ptr< Base >> &bfuncs)=0
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *fun)
Static Public Member Functions inherited from mslang::Function
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
double width_m
double height_m
Public Attributes inherited from mslang::Base
AffineTransformation trafo_m
BoundingBox2D bb_m
std::vector< std::shared_ptr< Base > > divisor_m
Additional Inherited Members
Static Public Attributes inherited from mslang::Function
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\((.*)"
Detailed Description
Definition at line 7 of file Rectangle.h.
Constructor & Destructor Documentation
Rectangle() [1/2]
mslang::Rectangle::Rectangle () inline
Definition at line 11 of file Rectangle.h.
Rectangle() [2/2]
mslang::Rectangle::Rectangle (const Rectangle & right) inline
Definition at line 17 of file Rectangle.h.
~Rectangle()
virtual mslang::Rectangle::~Rectangle () inline virtual
Definition at line 23 of file Rectangle.h.
Member Function Documentation
apply()
void mslang::Rectangle::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Definition at line 89 of file Rectangle.cpp.
References clone().
clone()
std::shared_ptr< Base > mslang::Rectangle::clone () const virtual
Implements mslang::Base.
Definition at line 93 of file Rectangle.cpp.
References mslang::Base::bb_m, mslang::Base::divisor_m, height_m, mslang::Base::trafo_m, and width_m.
Referenced by apply().
computeBoundingBox()
void mslang::Rectangle::computeBoundingBox () virtual
Implements mslang::Base.
Definition at line 24 of file Rectangle.cpp.
References mslang::Base::bb_m, mslang::Base::divisor_m, height_m, mslang::Base::trafo_m, mslang::AffineTransformation::transformFrom(), and width_m.
isInside()
bool mslang::Rectangle::isInside (const Vector_t & R) const virtual
Implements mslang::Base.
Definition at line 50 of file Rectangle.cpp.
References abs(), mslang::Base::bb_m, mslang::Base::divisor_m, height_m, mslang::BoundingBox2D::isInside(), Attrib::Distribution::R, mslang::Base::trafo_m, mslang::AffineTransformation::transformTo(), width_m, and X.
parse_detail()
bool mslang::Rectangle::parse_detail (iterator & it, const iterator & end, Function * fun) static
Definition at line 107 of file Rectangle.cpp.
References Physics::e, end(), endl(), mslang::ArgumentExtractor::get(), mslang::ArgumentExtractor::getLengthConsumed(), height_m, mslang::parseMathExpression(), mslang::Function::UDouble, and width_m.
Referenced by mslang::Function::parse().
print()
void mslang::Rectangle::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 9 of file Rectangle.cpp.
References endl(), mslang::AffineTransformation::getAngle(), mslang::AffineTransformation::getOrigin(), height_m, Units::rad2deg, mslang::Base::trafo_m, and width_m.
writeGnuplot()
void mslang::Rectangle::writeGnuplot (std::ofstream & out) const virtual
Implements mslang::Base.
Definition at line 66 of file Rectangle.cpp.
References mslang::Base::divisor_m, endl(), height_m, mslang::Base::trafo_m, mslang::AffineTransformation::transformFrom(), and width_m.
Member Data Documentation
height_m
double mslang::Rectangle::height_m
Definition at line 9 of file Rectangle.h.
Referenced by clone(), computeBoundingBox(), isInside(), mslang::Mask::parse_detail(), parse_detail(), print(), and writeGnuplot().
width_m
double mslang::Rectangle::width_m
Definition at line 8 of file Rectangle.h.
Referenced by clone(), computeBoundingBox(), isInside(), mslang::Mask::parse_detail(), parse_detail(), print(), and writeGnuplot().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Rectangle.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Rectangle.cpp