OPAL (Object Oriented Parallel Accelerator Library): ManyMasterSplit< TopoDiscoveryStrategy > Class Template Reference
ManyMasterSplit< TopoDiscoveryStrategy > Class Template Reference
#include <ManyMasterSplit.h>
Public Member Functions
ManyMasterSplit (CmdArguments_t args, MPI_Comm comm=MPI_COMM_WORLD)
virtual ~ManyMasterSplit ()
virtual void split ()
virtual int getNrWorkerGroups () const
Get number of worker groups.
Private Member Functions
void parseArguments ()
Private Attributes
size_t num_masters_
size_t num_coworkers_worker_
Additional Inherited Members
Protected Member Functions inherited from SplitStrategy
SplitStrategy (CmdArguments_t args, MPI_Comm comm=MPI_COMM_WORLD)
virtual ~SplitStrategy ()
MPI_Comm getComm () const
int getRank () const
int getGlobalRank () const
int getNP () const
Role_t getRole () const
int getLeader () const
int getPoller () const
Protected Attributes inherited from SplitStrategy
int rank_
int global_rank_
int num_procs_
int group_id_
CmdArguments_t cmd_args_
Role_t role_
std::vector< unsigned int > colorings_
defines comm splitting
int leader_
every core specifies a leader (master is its own leader)
int poller_
every core can specifies a master
Detailed Description
template<class TopoDiscoveryStrategy>
class ManyMasterSplit< TopoDiscoveryStrategy >
A very simple splitting strategy where we have a one core optimizer and pilot (and k of those "islands") and many-core worker groups. The number of islands and co-workers is retrieved from the passed command line arguments:
num-masters
num-coworkers
Definition at line 22 of file ManyMasterSplit.h.
Constructor & Destructor Documentation
ManyMasterSplit()
template<class TopoDiscoveryStrategy > ManyMasterSplit< TopoDiscoveryStrategy >::ManyMasterSplit (CmdArguments_t args, MPI_Comm comm = MPI_COMM_WORLD) inline
Definition at line 26 of file ManyMasterSplit.h.
~ManyMasterSplit()
template<class TopoDiscoveryStrategy > virtual ManyMasterSplit< TopoDiscoveryStrategy >::~ManyMasterSplit () inline virtual
Definition at line 31 of file ManyMasterSplit.h.
Member Function Documentation
getNrWorkerGroups()
template<class TopoDiscoveryStrategy > virtual int ManyMasterSplit< TopoDiscoveryStrategy >::getNrWorkerGroups () const inline virtual
Get number of worker groups.
Implements SplitStrategy.
Definition at line 97 of file ManyMasterSplit.h.
References ManyMasterSplit< TopoDiscoveryStrategy >::num_coworkers_worker_, ManyMasterSplit< TopoDiscoveryStrategy >::num_masters_, and SplitStrategy::num_procs_.
parseArguments()
template<class TopoDiscoveryStrategy > void ManyMasterSplit< TopoDiscoveryStrategy >::parseArguments () inline private
Definition at line 106 of file ManyMasterSplit.h.
References SplitStrategy::cmd_args_, Physics::e, endl(), SplitStrategy::getComm(), ManyMasterSplit< TopoDiscoveryStrategy >::num_coworkers_worker_, ManyMasterSplit< TopoDiscoveryStrategy >::num_masters_, and SplitStrategy::num_procs_.
Referenced by ManyMasterSplit< TopoDiscoveryStrategy >::split().
split()
template<class TopoDiscoveryStrategy > virtual void ManyMasterSplit< TopoDiscoveryStrategy >::split () inline virtual
Forcing concrete implementation to split and assign poller, optimizer and worker nodes.
Implements SplitStrategy.
Definition at line 35 of file ManyMasterSplit.h.
References SplitStrategy::colorings_, SplitStrategy::group_id_, SplitStrategy::leader_, ManyMasterSplit< TopoDiscoveryStrategy >::num_coworkers_worker_, ManyMasterSplit< TopoDiscoveryStrategy >::num_masters_, SplitStrategy::num_procs_, OPTIMIZER, ManyMasterSplit< TopoDiscoveryStrategy >::parseArguments(), POLLER, SplitStrategy::poller_, SplitStrategy::rank_, SplitStrategy::role_, and WORKER.
Member Data Documentation
num_coworkers_worker_
template<class TopoDiscoveryStrategy > size_t ManyMasterSplit< TopoDiscoveryStrategy >::num_coworkers_worker_ private
Definition at line 104 of file ManyMasterSplit.h.
Referenced by ManyMasterSplit< TopoDiscoveryStrategy >::getNrWorkerGroups(), ManyMasterSplit< TopoDiscoveryStrategy >::parseArguments(), and ManyMasterSplit< TopoDiscoveryStrategy >::split().
num_masters_
template<class TopoDiscoveryStrategy > size_t ManyMasterSplit< TopoDiscoveryStrategy >::num_masters_ private
Definition at line 103 of file ManyMasterSplit.h.
Referenced by ManyMasterSplit< TopoDiscoveryStrategy >::getNrWorkerGroups(), ManyMasterSplit< TopoDiscoveryStrategy >::parseArguments(), and ManyMasterSplit< TopoDiscoveryStrategy >::split().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/optimizer/Comm/Splitter/ManyMasterSplit.h