OPAL (Object Oriented Parallel Accelerator Library): ElementPositionWriter Class Reference
ElementPositionWriter Class Reference
#include <ElementPositionWriter.h>
Public Member Functions
ElementPositionWriter (const std::string &fname)
void addRow (double spos, const std::vector< double > &row, const std::string &elements)
Public Member Functions inherited from SDDSWriter
SDDSWriter (const std::string &fname, bool restart)
virtual ~SDDSWriter ()
virtual void write (PartBunchBase< double, 3 > *)
void rewindLines (size_t numberOfLines)
delete the last 'numberOfLines' lines of the file 'fileName'
void replaceVersionString ()
double getLastValue (const std::string &column)
bool exists () const
Private Member Functions
void fillHeader ()
Additional Inherited Members
Public Types inherited from SDDSWriter
typedef std::pair< std::string, std::string > desc_t
typedef std::tuple< std::string, std::string, std::string > param_t
typedef std::pair< std::string, size_t > data_t
typedef std::tuple< std::string, std::string, std::string, std::string > cols_t
Protected Member Functions inherited from SDDSWriter
void addDescription (const std::string &text, const std::string &content)
template<typename T >
void addParameter (const std::string &name, const std::string &type, const std::string &desc, const T &value)
void addDefaultParameters ()
void addColumn (const std::string &name, const std::string &type, const std::string &unit, const std::string &desc)
void addInfo (const std::string &mode, const size_t &no_row_counts)
void writeRow ()
void open ()
void close ()
void writeHeader ()
Write SDDS header.
template<typename T >
std::string toString (const T &val)
bool hasColumns () const
Protected Attributes inherited from SDDSWriter
std::string fname_m
std::ios_base::openmode mode_m
First write to the statistics output file.
SDDSColumnSet columns_m
Detailed Description
Definition at line 6 of file ElementPositionWriter.h.
Constructor & Destructor Documentation
ElementPositionWriter()
ElementPositionWriter::ElementPositionWriter (const std::string & fname) explicit
Definition at line 6 of file ElementPositionWriter.cpp.
Member Function Documentation
addRow()
void ElementPositionWriter::addRow (double spos, const std::vector< double > & row, const std::string & elements)
Definition at line 96 of file ElementPositionWriter.cpp.
References SDDSColumnSet::addColumnValue(), SDDSWriter::close(), SDDSWriter::columns_m, fillHeader(), IpplInfo::myNode(), SDDSWriter::open(), SDDSWriter::writeHeader(), and SDDSWriter::writeRow().
fillHeader()
void ElementPositionWriter::fillHeader () private
Definition at line 11 of file ElementPositionWriter.cpp.
References SDDSColumnSet::addColumn(), SDDSWriter::addDefaultParameters(), SDDSWriter::addDescription(), SDDSWriter::addInfo(), SDDSWriter::columns_m, OpalData::getInstance(), and SDDSWriter::hasColumns().
Referenced by addRow().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Structure/ElementPositionWriter.h
/psi/home/gsell/data/src/OPAL/src/src/Structure/ElementPositionWriter.cpp