OPAL (Object Oriented Parallel Accelerator Library): OpalTravelingWave Class Reference
OpalTravelingWave Class Reference
#include <OpalTravelingWave.h>
Public Types
enum {
VOLT = COMMON, DVOLT, FREQ, LAG,
DLAG, FMAPFN, APVETO, FAST,
NUMCELLS, DESIGNENERGY, MODE, SIZE
}
The attributes of class OpalTravelingWave.
Public Types inherited from OpalElement
enum {
TYPE, APERT, LENGTH, ELEMEDGE,
WAKEF, PARTICLEMATTERINTERACTION, ORIGIN, ORIENTATION,
X, Y, Z, THETA,
PHI, PSI, DX, DY,
DZ, DTHETA, DPHI, DPSI,
OUTFN, DELETEONTRANSVERSEEXIT, COMMON
}
The common attributes for all elements.
Public Types inherited from Element
enum ReferenceType { IS_ENTRY, IS_CENTRE, IS_EXIT }
Reference for element positioning.
Public Member Functions
OpalTravelingWave ()
Exemplar constructor.
virtual ~OpalTravelingWave ()
virtual OpalTravelingWave * clone (const std::string &name)
Make clone.
virtual void update ()
Update the embedded CLASSIC cavity.
Public Member Functions inherited from OpalElement
virtual ~OpalElement ()
virtual double getLength () const
Return element length.
const std::string getTypeName () const
Return the element's type name.
std::pair< ApertureType, std::vector< double > > getApert () const
const std::string getWakeF () const
Return the element's type name.
const std::string getParticleMatterInteraction () const
const std::string getWMaterial () const
const std::string getWakeGeom () const
std::vector< double > getWakeParam () const
const std::string getWakeConductivity () const
virtual void parse (Statement &)
Parse the element.
virtual void print (std::ostream &) const
Print the object.
virtual void updateUnknown (ElementBase *)
Transmit the `‘unknown’' (not known to OPAL) attributes to CLASSIC.
Public Member Functions inherited from Element
virtual ~Element ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual double getEntrance (ReferenceType) const
Return arc length from origin to entrance (negative !).
virtual double getExit (ReferenceType) const
Return arc length from origin to exit (positive !).
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded CLASSIC element.
void setElement (ElementBase *)
Assign new CLASSIC element.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
OpalTravelingWave (const OpalTravelingWave &)
void operator= (const OpalTravelingWave &)
OpalTravelingWave (const std::string &name, OpalTravelingWave *parent)
Private Attributes
OpalWake * owk_m
Additional Inherited Members
Static Public Member Functions inherited from Element
static Element * find (const std::string &name)
Find named Element.
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from OpalElement
OpalElement (int size, const char *name, const char *help)
Exemplar constructor.
OpalElement (const std::string &name, OpalElement *parent)
Clone constructor.
void registerOwnership () const
Protected Member Functions inherited from Element
Element (int size, const char *name, const char *help)
Constructor for exemplars.
Element (const std::string &name, Element *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Static Protected Member Functions inherited from OpalElement
static void printMultipoleStrength (std::ostream &os, int order, int &len, const std::string &sName, const std::string &tName, const Attribute &length, const Attribute &vNorm, const Attribute &vSkew)
Print multipole components in OPAL-8 format.
static void printAttribute (std::ostream &os, const std::string &name, const std::string &image, int &len)
Print an attribute with a OPAL-8 name (as an expression).
static void printAttribute (std::ostream &os, const std::string &name, double value, int &len)
Print an attribute with a OPAL-8 name (as a constant).
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 25 of file OpalTravelingWave.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
The attributes of class OpalTravelingWave.
Enumerator
VOLT
DVOLT
FREQ
LAG
DLAG
FMAPFN
APVETO
FAST
NUMCELLS
DESIGNENERGY
MODE
SIZE
Definition at line 30 of file OpalTravelingWave.h.
Constructor & Destructor Documentation
OpalTravelingWave() [1/3]
OpalTravelingWave::OpalTravelingWave ()
Exemplar constructor.
Definition at line 26 of file OpalTravelingWave.cpp.
References APVETO, DESIGNENERGY, DLAG, DVOLT, FAST, FMAPFN, FREQ, Object::itsAttr, LAG, Attributes::makeBool(), Attributes::makeReal(), Attributes::makeString(), MODE, NUMCELLS, OpalElement::registerOwnership(), Element::setElement(), and VOLT.
Referenced by clone().
~OpalTravelingWave()
OpalTravelingWave::~OpalTravelingWave () virtual
Definition at line 66 of file OpalTravelingWave.cpp.
References owk_m.
OpalTravelingWave() [2/3]
OpalTravelingWave::OpalTravelingWave (const OpalTravelingWave &) private
OpalTravelingWave() [3/3]
OpalTravelingWave::OpalTravelingWave (const std::string & name, OpalTravelingWave * parent) private
Definition at line 59 of file OpalTravelingWave.cpp.
References name, and Element::setElement().
Member Function Documentation
clone()
OpalTravelingWave * OpalTravelingWave::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 71 of file OpalTravelingWave.cpp.
References name, and OpalTravelingWave().
Referenced by update().
operator=()
void OpalTravelingWave::operator= (const OpalTravelingWave &) private
update()
void OpalTravelingWave::update () virtual
Update the embedded CLASSIC cavity.
Reimplemented from OpalElement.
Definition at line 76 of file OpalTravelingWave.cpp.
References APVETO, clone(), DESIGNENERGY, DLAG, DVOLT, FAST, OpalWake::find(), FMAPFN, FREQ, Attributes::getBool(), Element::getElement(), Object::getOpalName(), Attributes::getReal(), Attributes::getString(), OpalWake::initWakefunction(), Object::itsAttr, LAG, OpalElement::LENGTH, Units::MHz2Hz, MODE, Units::MVpm2Vpm, NUMCELLS, owk_m, TravelingWaveRep::setAmplitude(), RFCavity::setAmplitudeError(), RFCavity::setAmplitudem(), RFCavity::setAutophaseVeto(), RFCavity::setDesignEnergy(), ElementBase::setElementLength(), RFCavity::setFast(), RFCavity::setFieldMapFN(), TravelingWaveRep::setFrequency(), RFCavity::setFrequencym(), TravelingWave::setMode(), TravelingWave::setNumCells(), TravelingWaveRep::setPhase(), RFCavity::setPhaseError(), TravelingWave::setPhasem(), ElementBase::setWake(), Physics::two_pi, OpalElement::update(), OpalElement::updateUnknown(), VOLT, OpalElement::WAKEF, and OpalWake::wf_m.
Member Data Documentation
owk_m
OpalWake* OpalTravelingWave::owk_m private
Definition at line 65 of file OpalTravelingWave.h.
Referenced by update(), and ~OpalTravelingWave().
The documentation for this class was generated from the following files:
src/Elements/OpalTravelingWave.h
src/Elements/OpalTravelingWave.cpp