OPAL (Object Oriented Parallel Accelerator Library): IntNGP Class Reference
IntNGP Class Reference
#include <IntNGP.h>
Public Member Functions
IntNGP ()
~IntNGP ()
Public Member Functions inherited from Interpolator
Interpolator ()
~Interpolator ()
Static Public Member Functions
template<class FT , unsigned Dim, class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh)
template<class FT , unsigned Dim, class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh, NDIndex< Dim > &ngp)
template<class FT , unsigned Dim, class M , class C >
static void scatter (const FT &pdata, Field< FT, Dim, M, C > &f, const NDIndex< Dim > &ngp)
template<class FT , unsigned Dim, class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh)
template<class FT , unsigned Dim, class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh, NDIndex< Dim > &ngp)
template<class FT , unsigned Dim, class M , class C >
static void gather (FT &pdata, const Field< FT, Dim, M, C > &f, const NDIndex< Dim > &ngp)
Additional Inherited Members
Static Protected Member Functions inherited from Interpolator
template<class T , unsigned Dim>
static CompressedBrickIterator< T, Dim > getFieldIter (const BareField< T, Dim > &f, const NDIndex< Dim > &pt)
Detailed Description
Definition at line 34 of file IntNGP.h.
Constructor & Destructor Documentation
IntNGP()
IntNGP::IntNGP () inline
Definition at line 38 of file IntNGP.h.
~IntNGP()
IntNGP::~IntNGP () inline
Definition at line 39 of file IntNGP.h.
Member Function Documentation
gather() [1/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntNGP::gather (FT & pdata, const Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh) inline static
Definition at line 94 of file IntNGP.h.
References FindNGP(), and Interpolator::getFieldIter().
gather() [2/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntNGP::gather (FT & pdata, const Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh, NDIndex< Dim > & ngp) inline static
Definition at line 111 of file IntNGP.h.
References FindNGP(), and Interpolator::getFieldIter().
gather() [3/3]
template<class FT , unsigned Dim, class M , class C > static void IntNGP::gather (FT & pdata, const Field< FT, Dim, M, C > & f, const NDIndex< Dim > & ngp) inline static
Definition at line 128 of file IntNGP.h.
References Interpolator::getFieldIter().
scatter() [1/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntNGP::scatter (const FT & pdata, Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh) inline static
Definition at line 46 of file IntNGP.h.
References FindNGP(), and Interpolator::getFieldIter().
scatter() [2/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntNGP::scatter (const FT & pdata, Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh, NDIndex< Dim > & ngp) inline static
Definition at line 63 of file IntNGP.h.
References FindNGP(), and Interpolator::getFieldIter().
scatter() [3/3]
template<class FT , unsigned Dim, class M , class C > static void IntNGP::scatter (const FT & pdata, Field< FT, Dim, M, C > & f, const NDIndex< Dim > & ngp) inline static
Definition at line 80 of file IntNGP.h.
References Interpolator::getFieldIter().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/IntNGP.h