OPAL (Object Oriented Parallel Accelerator Library): Attribute Class Reference
Attribute Class Reference
A representation of an Object attribute.
#include <Attribute.h>
Public Member Functions
Attribute ()
Default constructor.
Attribute (const Attribute &rhs)
Copy constructor.
Attribute (AttributeHandler *h, AttributeBase *b=nullptr)
Constructor defining a parser and an optional value.
~Attribute ()
const Attribute & operator= (const Attribute &)
operator bool () const
Test for valid pointer.
AttributeBase & getBase () const
Return reference to polymorphic value.
bool isBaseAllocated () const
std::string getImage () const
Return printable representation.
AttributeHandler & getHandler () const
Return a reference to the parser.
const std::string & getHelp () const
Return the help string.
const std::string & getName () const
Return the attribute name.
const std::string & getType () const
Return the attribute type.
bool isDeferred () const
Return [b]deferred[/b] flag.
void setDeferred (bool)
Set read-only flag.
bool isExpression () const
Test for expression.
bool isReadOnly () const
Test for read only.
void setReadOnly (bool)
Set read-only flag.
void parse (Statement &stat, bool eval)
Parse attribute.
void parseComponent (Statement &stat, bool eval, int index)
Parse array component.
void set (AttributeBase *newBase)
Define new value.
void setDefault ()
Assign default value.
void print (int &len) const
Print attribute.
bool defaultUsed () const
Private Attributes
Pointer< AttributeBase > base
Pointer< AttributeHandler > handler
bool isDefault
Detailed Description
A representation of an Object attribute.
Definition at line 52 of file Attribute.h.
Constructor & Destructor Documentation
Attribute() [1/3]
Attribute::Attribute ()
Default constructor.
Definition at line 34 of file Attribute.cpp.
Attribute() [2/3]
Attribute::Attribute (const Attribute & rhs)
Copy constructor.
Definition at line 41 of file Attribute.cpp.
Attribute() [3/3]
Attribute::Attribute (AttributeHandler * h, AttributeBase * b = nullptr)
Constructor defining a parser and an optional value.
Definition at line 48 of file Attribute.cpp.
~Attribute()
Attribute::~Attribute ()
Definition at line 55 of file Attribute.cpp.
Member Function Documentation
defaultUsed()
bool Attribute::defaultUsed () const inline
Definition at line 173 of file Attribute.h.
References isDefault.
getBase()
AttributeBase & Attribute::getBase () const
Return reference to polymorphic value.
Definition at line 69 of file Attribute.cpp.
References base.
Referenced by Attributes::getBool(), Attributes::getBoolArray(), Attributes::getPlace(), Attributes::getRange(), Attributes::getReal(), Attributes::getRealArray(), Attributes::getString(), Attributes::getStringArray(), Attributes::getTableRow(), Attributes::getTokenList(), Attributes::getTokenListArray(), operator<<(), Attributes::UpperCaseStringArray::parseComponent(), Attributes::RealArray::parseComponent(), Attributes::BoolArray::parseComponent(), Attributes::StringArray::parseComponent(), Attributes::TokenListArray::parseComponent(), OpalElement::printMultipoleStrength(), Attributes::setBool(), Attributes::setPredefinedString(), Attributes::setReal(), Attributes::setString(), and Attributes::setUpperCaseString().
getHandler()
AttributeHandler & Attribute::getHandler () const
Return a reference to the parser.
Definition at line 77 of file Attribute.cpp.
References handler.
Referenced by Attributes::getBool(), Attributes::getReal(), Attributes::getRealArray(), Attributes::getString(), Attributes::getStringArray(), Attributes::getTokenList(), Attributes::getTokenListArray(), Attributes::setBool(), Attributes::setBoolArray(), Attributes::setPlace(), Attributes::setPredefinedString(), Attributes::setRange(), Attributes::setReal(), Attributes::setRealArray(), Attributes::setString(), Attributes::setStringArray(), Attributes::setTableRow(), Attributes::setTokenList(), Attributes::setUpperCaseString(), and Attributes::setUpperCaseStringArray().
getHelp()
const std::string & Attribute::getHelp () const
Return the help string.
Definition at line 82 of file Attribute.cpp.
References AttributeHandler::getHelp(), and handler.
Referenced by PyOpal::PyOpalObjectNS::PyOpalObject< C >::getDocString().
getImage()
std::string Attribute::getImage () const
Return printable representation.
Definition at line 87 of file Attribute.cpp.
References base, and AttributeBase::getImage().
Referenced by print(), and OpalElement::printMultipoleStrength().
getName()
const std::string & Attribute::getName () const
Return the attribute name.
Definition at line 92 of file Attribute.cpp.
References AttributeHandler::getName(), and handler.
Referenced by Attributes::getBoolArray(), Attributes::getPlace(), Attributes::getRange(), Attributes::getTableRow(), print(), OpalTrimCoil::printPolynom(), Attributes::setBool(), Attributes::setBoolArray(), Attributes::setPlace(), Attributes::setPredefinedString(), Attributes::setRange(), Attributes::setReal(), Attributes::setRealArray(), Attributes::setString(), Attributes::setStringArray(), Attributes::setTableRow(), Attributes::setTokenList(), Attributes::setUpperCaseString(), Attributes::setUpperCaseStringArray(), and OpalElement::updateUnknown().
getType()
const std::string & Attribute::getType () const
Return the attribute type.
Definition at line 97 of file Attribute.cpp.
References AttributeHandler::getType(), and handler.
isBaseAllocated()
bool Attribute::isBaseAllocated () const
Definition at line 73 of file Attribute.cpp.
References base.
Referenced by Attributes::getBool(), Attributes::getBoolArray(), Attributes::getPlace(), Attributes::getRange(), Attributes::getReal(), Attributes::getRealArray(), Attributes::getString(), Attributes::getStringArray(), Attributes::getTableRow(), Attributes::getTokenList(), Attributes::getTokenListArray(), Attributes::setBool(), Attributes::setPredefinedString(), Attributes::setReal(), Attributes::setString(), and Attributes::setUpperCaseString().
isDeferred()
bool Attribute::isDeferred () const
Return [b]deferred[/b] flag.
Definition at line 102 of file Attribute.cpp.
References handler, and AttributeHandler::isDeferred().
isExpression()
bool Attribute::isExpression () const
Test for expression.
Definition at line 112 of file Attribute.cpp.
References base, and AttributeBase::isExpression().
Referenced by print().
isReadOnly()
bool Attribute::isReadOnly () const
Test for read only.
Definition at line 117 of file Attribute.cpp.
References handler, and AttributeHandler::isReadOnly().
operator bool()
Attribute::operator bool () const inline
Test for valid pointer.
Definition at line 169 of file Attribute.h.
operator=()
const Attribute & Attribute::operator= (const Attribute & rhs)
Definition at line 59 of file Attribute.cpp.
References base, and handler.
parse()
void Attribute::parse (Statement & stat, bool eval)
Parse attribute.
Definition at line 127 of file Attribute.cpp.
References handler, isDefault, and AttributeHandler::parse().
Referenced by IfStatement::execute(), WhileStatement::execute(), and OpalElement::parse().
parseComponent()
void Attribute::parseComponent (Statement & stat, bool eval, int index)
Parse array component.
Definition at line 133 of file Attribute.cpp.
References handler, isDefault, and AttributeHandler::parseComponent().
Referenced by OpalElement::parse().
print()
void Attribute::print (int & len) const
Print attribute.
Definition at line 151 of file Attribute.cpp.
References endl(), getImage(), getName(), gmsg, isExpression(), and name.
set()
void Attribute::set (AttributeBase * newBase)
Define new value.
Definition at line 139 of file Attribute.cpp.
References base, and isDefault.
Referenced by Attributes::Bool::parse(), Attributes::Real::parse(), Attributes::String::parse(), Attributes::Place::parse(), Attributes::Range::parse(), Attributes::BoolArray::parse(), Attributes::RealArray::parse(), Attributes::Reference::parse(), Attributes::TableRow::parse(), Attributes::TokenList::parse(), Attributes::BoolArray::parseComponent(), Attributes::RealArray::parseComponent(), Attributes::setBool(), Attributes::setBoolArray(), Attributes::setPlace(), Attributes::setPredefinedString(), Attributes::setRange(), Attributes::setReal(), Attributes::setRealArray(), Attributes::setString(), Attributes::setStringArray(), Attributes::setTableRow(), Attributes::setTokenList(), Attributes::setTokenListArray(), Attributes::setUpperCaseString(), and Attributes::setUpperCaseStringArray().
setDefault()
void Attribute::setDefault ()
Assign default value.
Definition at line 145 of file Attribute.cpp.
References base, AttributeHandler::getDefault(), handler, and isDefault.
Referenced by OpalElement::parse().
setDeferred()
void Attribute::setDeferred (bool flag)
Set read-only flag.
Definition at line 107 of file Attribute.cpp.
References handler, and AttributeHandler::setDeferred().
setReadOnly()
void Attribute::setReadOnly (bool flag)
Set read-only flag.
Definition at line 122 of file Attribute.cpp.
References handler, and AttributeHandler::setReadOnly().
Member Data Documentation
base
Pointer<AttributeBase> Attribute::base private
Definition at line 157 of file Attribute.h.
Referenced by getBase(), getImage(), isBaseAllocated(), isExpression(), operator=(), set(), and setDefault().
handler
Pointer<AttributeHandler> Attribute::handler private
Definition at line 160 of file Attribute.h.
Referenced by getHandler(), getHelp(), getName(), getType(), isDeferred(), isReadOnly(), operator=(), parse(), parseComponent(), setDefault(), setDeferred(), and setReadOnly().
isDefault
bool Attribute::isDefault private
Definition at line 162 of file Attribute.h.
Referenced by defaultUsed(), parse(), parseComponent(), set(), and setDefault().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/AbstractObjects/Attribute.h
/psi/home/gsell/data/src/OPAL/src/src/AbstractObjects/Attribute.cpp