OPAL (Object Oriented Parallel Accelerator Library): BMultipoleField Class Reference
BMultipoleField Class Reference
The magnetic field of a multipole.
#include <BMultipoleField.h>
Classes
struct Pair
Public Member Functions
BMultipoleField ()
Default constructor.
BMultipoleField (const BMultipoleField &)
virtual ~BMultipoleField ()
BMultipoleField & operator= (const BMultipoleField &)
virtual BVector Bfield (const Point3D &P) const
Get field.
virtual BVector Bfield (const Point3D &P, double t) const
Get field.
double getNormalComponent (int n) const
Get component.
double getSkewComponent (int n) const
Get component.
void setNormalComponent (int n, double Bn)
Set component.
void setSkewComponent (int n, double Bn)
Set component.
double normal (int) const
Get component.
double skew (int) const
Get component.
double & normal (int)
Get component.
double & skew (int)
Get component.
BMultipoleField & addField (const BMultipoleField &field)
Add to field.
BMultipoleField & subtractField (const BMultipoleField &field)
Subtract from field.
void scale (double scalar)
Scale the field.
int order () const
Return order.
Public Member Functions inherited from StaticMagneticField
StaticMagneticField ()
virtual ~StaticMagneticField ()
Public Member Functions inherited from EMField
EMField ()
Default constructor.
EMField (const EMField &right)
virtual ~EMField ()
const EMField & operator= (const EMField &right)
virtual EVector Efield (const Point3D &P) const
Get field.
virtual EVector Efield (const Point3D &P, double t) const
Get field.
virtual EBVectors EBfield (const Point3D &P) const
Get field.
virtual EBVectors EBfield (const Point3D &P, double t) const
Get field.
Private Member Functions
void reserve (int n)
Private Attributes
Pair * pairs
int itsOrder
Additional Inherited Members
Static Public Attributes inherited from EMField
static const EVector ZeroEfield
The constant representing a zero electric field.
static const BVector ZeroBfield
The constant representing a zero magnetic field.
static const EBVectors ZeroEBfield
The constant representing a zero electromagnetic field.
Detailed Description
The magnetic field of a multipole.
Definition at line 36 of file BMultipoleField.h.
Constructor & Destructor Documentation
BMultipoleField() [1/2]
BMultipoleField::BMultipoleField ()
Default constructor.
Definition at line 85 of file BMultipoleField.cpp.
BMultipoleField() [2/2]
BMultipoleField::BMultipoleField (const BMultipoleField & rhs)
Definition at line 91 of file BMultipoleField.cpp.
References itsOrder, and pairs.
~BMultipoleField()
BMultipoleField::~BMultipoleField () virtual
Definition at line 104 of file BMultipoleField.cpp.
References pairs.
Member Function Documentation
addField()
BMultipoleField & BMultipoleField::addField (const BMultipoleField & field)
Add to field.
Definition at line 166 of file BMultipoleField.cpp.
References itsOrder, pairs, and reserve().
Bfield() [1/2]
BVector BMultipoleField::Bfield (const Point3D & P) const virtual
Get field.
Reimplemented from EMField.
Definition at line 126 of file BMultipoleField.cpp.
References BMultipoleField::Pair::A, BMultipoleField::Pair::B, Point3D::getX(), Point3D::getY(), imag(), itsOrder, pairs, real(), and X.
Referenced by Bfield().
Bfield() [2/2]
BVector BMultipoleField::Bfield (const Point3D & P, double t) const virtual
Get field.
Reimplemented from EMField.
Definition at line 139 of file BMultipoleField.cpp.
References Bfield().
getNormalComponent()
double BMultipoleField::getNormalComponent (int n) const inline
Get component.
Definition at line 161 of file BMultipoleField.h.
References BMultipoleField::Pair::B, itsOrder, Hypervolume::n, and pairs.
Referenced by RBendRep::getB(), SBendRep::getB(), RBend::getNormalComponent(), SBend::getNormalComponent(), and ThickTracker::visitMultipole().
getSkewComponent()
double BMultipoleField::getSkewComponent (int n) const inline
Get component.
Definition at line 170 of file BMultipoleField.h.
References BMultipoleField::Pair::A, itsOrder, Hypervolume::n, and pairs.
Referenced by RBend::getSkewComponent(), and SBend::getSkewComponent().
normal() [1/2]
double BMultipoleField::normal (int n) const inline
Get component.
Definition at line 187 of file BMultipoleField.h.
References BMultipoleField::Pair::B, Hypervolume::n, and pairs.
Referenced by Tracker::applyThinMultipole(), Tracker::buildMultipoleVectorPotential(), Tracker::buildMultipoleVectorPotential2D(), Tracker::buildSBendVectorPotential(), Tracker::buildSBendVectorPotential2D(), and BMultipoleField::Pair::Pair().
normal() [2/2]
double & BMultipoleField::normal (int n) inline
Get component.
Definition at line 179 of file BMultipoleField.h.
References BMultipoleField::Pair::B, Hypervolume::n, and pairs.
operator=()
BMultipoleField & BMultipoleField::operator= (const BMultipoleField & rhs)
Definition at line 109 of file BMultipoleField.cpp.
References itsOrder, and pairs.
order()
int BMultipoleField::order () const inline
Return order.
Definition at line 156 of file BMultipoleField.h.
References itsOrder.
Referenced by Tracker::applyThinMultipole(), Tracker::buildMultipoleVectorPotential(), Tracker::buildMultipoleVectorPotential2D(), Tracker::buildSBendVectorPotential(), and Tracker::buildSBendVectorPotential2D().
reserve()
void BMultipoleField::reserve (int n) private
Definition at line 187 of file BMultipoleField.cpp.
References itsOrder, Hypervolume::n, and pairs.
Referenced by addField(), setNormalComponent(), setSkewComponent(), and subtractField().
scale()
void BMultipoleField::scale (double scalar) virtual
Scale the field.
Implements EMField.
Definition at line 180 of file BMultipoleField.cpp.
References itsOrder, and pairs.
Referenced by BMultipoleField::Pair::operator*(), and BMultipoleField::Pair::operator*=().
setNormalComponent()
void BMultipoleField::setNormalComponent (int n, double Bn)
Set component.
Definition at line 144 of file BMultipoleField.cpp.
References BMultipoleField::Pair::B, itsOrder, Hypervolume::n, pairs, and reserve().
Referenced by BSingleMultipoleField< order >::operator BMultipoleField(), RBendRep::setB(), SBendRep::setB(), RBend::setNormalComponent(), SBend::setNormalComponent(), OpalRBend::update(), OpalSBend::update(), OpalMultipole::update(), OpalSextupole::update(), OpalOctupole::update(), and OpalQuadrupole::update().
setSkewComponent()
void BMultipoleField::setSkewComponent (int n, double Bn)
Set component.
Definition at line 155 of file BMultipoleField.cpp.
References a, BMultipoleField::Pair::A, itsOrder, Hypervolume::n, pairs, and reserve().
Referenced by BSingleMultipoleField< order >::operator BMultipoleField(), RBend::setSkewComponent(), SBend::setSkewComponent(), OpalSBend::update(), OpalRBend::update(), OpalSextupole::update(), OpalMultipole::update(), OpalOctupole::update(), and OpalQuadrupole::update().
skew() [1/2]
double BMultipoleField::skew (int n) const inline
Get component.
Definition at line 191 of file BMultipoleField.h.
References BMultipoleField::Pair::A, Hypervolume::n, and pairs.
Referenced by Tracker::applyThinMultipole(), Tracker::buildMultipoleVectorPotential(), Tracker::buildMultipoleVectorPotential2D(), Tracker::buildSBendVectorPotential(), and Tracker::buildSBendVectorPotential2D().
skew() [2/2]
double & BMultipoleField::skew (int n) inline
Get component.
Definition at line 183 of file BMultipoleField.h.
References BMultipoleField::Pair::A, Hypervolume::n, and pairs.
subtractField()
BMultipoleField & BMultipoleField::subtractField (const BMultipoleField & field)
Subtract from field.
Definition at line 173 of file BMultipoleField.cpp.
References itsOrder, pairs, and reserve().
Member Data Documentation
itsOrder
int BMultipoleField::itsOrder private
Definition at line 149 of file BMultipoleField.h.
Referenced by addField(), Bfield(), BMultipoleField(), getNormalComponent(), getSkewComponent(), operator=(), order(), reserve(), scale(), setNormalComponent(), setSkewComponent(), and subtractField().
pairs
Pair* BMultipoleField::pairs private
Definition at line 146 of file BMultipoleField.h.
Referenced by addField(), Bfield(), BMultipoleField(), getNormalComponent(), getSkewComponent(), normal(), operator=(), reserve(), scale(), setNormalComponent(), setSkewComponent(), skew(), subtractField(), and ~BMultipoleField().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/BMultipoleField.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/BMultipoleField.cpp