OPAL (Object Oriented Parallel Accelerator Library): cmp_ulp_obsolete Namespace Reference
cmp_ulp_obsolete Namespace Reference
Functions
bool almost_eq (double A, double B, double maxDiff=1e-20, int maxUlps=1000)
bool almost_eq_zero (double A, double maxDiff=1e-15)
bool eq (double x, double y)
bool eq_zero (double x)
bool le (double x, double y)
bool le_zero (double x)
bool lt (double x, double y)
bool lt_zero (double x)
bool ge (double x, double y)
bool ge_zero (double x)
bool gt (double x, double y)
bool gt_zero (double x)
Function Documentation
almost_eq()
bool cmp_ulp_obsolete::almost_eq (double A, double B, double maxDiff = 1e-20, int maxUlps = 1000) inline
Definition at line 170 of file BoundaryGeometry.cpp.
References abs(), and matheval::detail::math::isnan().
almost_eq_zero()
bool cmp_ulp_obsolete::almost_eq_zero (double A, double maxDiff = 1e-15) inline
Definition at line 209 of file BoundaryGeometry.cpp.
References abs().
eq()
bool cmp_ulp_obsolete::eq (double x, double y) inline
Definition at line 213 of file BoundaryGeometry.cpp.
eq_zero()
bool cmp_ulp_obsolete::eq_zero (double x) inline
Definition at line 214 of file BoundaryGeometry.cpp.
ge()
bool cmp_ulp_obsolete::ge (double x, double y) inline
Definition at line 219 of file BoundaryGeometry.cpp.
ge_zero()
bool cmp_ulp_obsolete::ge_zero (double x) inline
Definition at line 220 of file BoundaryGeometry.cpp.
gt()
bool cmp_ulp_obsolete::gt (double x, double y) inline
Definition at line 221 of file BoundaryGeometry.cpp.
gt_zero()
bool cmp_ulp_obsolete::gt_zero (double x) inline
Definition at line 222 of file BoundaryGeometry.cpp.
le()
bool cmp_ulp_obsolete::le (double x, double y) inline
Definition at line 215 of file BoundaryGeometry.cpp.
le_zero()
bool cmp_ulp_obsolete::le_zero (double x) inline
Definition at line 216 of file BoundaryGeometry.cpp.
lt()
bool cmp_ulp_obsolete::lt (double x, double y) inline
Definition at line 217 of file BoundaryGeometry.cpp.
lt_zero()
bool cmp_ulp_obsolete::lt_zero (double x) inline
Definition at line 218 of file BoundaryGeometry.cpp.