OPAL (Object Oriented Parallel Accelerator Library): _FM3DMagnetoStatic Class Reference
_FM3DMagnetoStatic Class Reference
#include <FM3DMagnetoStatic.h>
Classes
struct IndexTriplet
Public Member Functions
virtual ~_FM3DMagnetoStatic ()
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const
virtual void getFieldDimensions (double &zBegin, double &zEnd) const
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const
virtual bool getFieldDerivative (const Vector_t &R, Vector_t &E, Vector_t &B, const DiffDirection &dir) const
virtual void swap ()
virtual void getInfo (Inform *msg)
virtual double getFrequency () const
virtual void setFrequency (double freq)
virtual bool isInside (const Vector_t &r) const
Public Member Functions inherited from _Fieldmap
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &onaxis)
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Private Types
enum {
LX = 0, LY = 0, LZ = 0, HX = 4,
HY = 2, HZ = 1
}
Private Member Functions
_FM3DMagnetoStatic (const std::string &filename)
virtual void readMap ()
virtual void freeMap ()
IndexTriplet getIndex (const Vector_t &X) const
unsigned long getIndex (unsigned int i, unsigned int j, unsigned int k) const
Vector_t interpolateTrilinearly (const Vector_t &X) const
double getWeightedData (double *data, const IndexTriplet &idx, unsigned short corner) const
Static Private Member Functions
static FM3DMagnetoStatic create (const std::string &filename)
Private Attributes
double * FieldstrengthBz_m
double * FieldstrengthBx_m
double * FieldstrengthBy_m
double xbegin_m
double xend_m
double ybegin_m
double yend_m
double zbegin_m
double zend_m
double hx_m
double hy_m
double hz_m
unsigned int num_gridpx_m
unsigned int num_gridpy_m
unsigned int num_gridpz_m
Friends
class _Fieldmap
Additional Inherited Members
Static Public Member Functions inherited from _Fieldmap
static Fieldmap getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions inherited from _Fieldmap
_Fieldmap ()=delete
_Fieldmap (const std::string &filename)
virtual ~_Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions inherited from _Fieldmap
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes inherited from _Fieldmap
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Detailed Description
Definition at line 6 of file FM3DMagnetoStatic.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
LX
LY
LZ
HX
HY
HZ
Definition at line 47 of file FM3DMagnetoStatic.h.
Constructor & Destructor Documentation
~_FM3DMagnetoStatic()
_FM3DMagnetoStatic::~_FM3DMagnetoStatic () virtual
Definition at line 88 of file FM3DMagnetoStatic.cpp.
References freeMap().
_FM3DMagnetoStatic()
_FM3DMagnetoStatic::_FM3DMagnetoStatic (const std::string & filename) private
Definition at line 12 of file FM3DMagnetoStatic.cpp.
References Units::cm2m, Physics::e, _Fieldmap::Filename_m, hx_m, hy_m, hz_m, _Fieldmap::interpreteEOF(), _Fieldmap::normalize_m, num_gridpx_m, num_gridpy_m, num_gridpz_m, T3DMagnetoStatic, Util::toUpper(), _Fieldmap::Type, xbegin_m, xend_m, ybegin_m, yend_m, zbegin_m, and zend_m.
Referenced by create().
Member Function Documentation
create()
FM3DMagnetoStatic _FM3DMagnetoStatic::create (const std::string & filename) static private
Definition at line 92 of file FM3DMagnetoStatic.cpp.
References _FM3DMagnetoStatic().
Referenced by _Fieldmap::getFieldmap().
freeMap()
void _FM3DMagnetoStatic::freeMap () private virtual
Implements _Fieldmap.
Definition at line 152 of file FM3DMagnetoStatic.cpp.
References FieldstrengthBx_m, FieldstrengthBy_m, and FieldstrengthBz_m.
Referenced by ~_FM3DMagnetoStatic().
getFieldDerivative()
bool _FM3DMagnetoStatic::getFieldDerivative (const Vector_t & R, Vector_t & E, Vector_t & B, const DiffDirection & dir) const virtual
Implements _Fieldmap.
Definition at line 219 of file FM3DMagnetoStatic.cpp.
getFieldDimensions() [1/2]
void _FM3DMagnetoStatic::getFieldDimensions (double & zBegin, double & zEnd) const virtual
Implements _Fieldmap.
Definition at line 223 of file FM3DMagnetoStatic.cpp.
References zbegin_m, and zend_m.
getFieldDimensions() [2/2]
void _FM3DMagnetoStatic::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const virtual
Implements _Fieldmap.
Definition at line 227 of file FM3DMagnetoStatic.cpp.
getFieldstrength()
bool _FM3DMagnetoStatic::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const virtual
Implements _Fieldmap.
Definition at line 164 of file FM3DMagnetoStatic.cpp.
References interpolateTrilinearly(), isInside(), and Attrib::Distribution::R.
getFrequency()
double _FM3DMagnetoStatic::getFrequency () const inline virtual
Implements _Fieldmap.
Definition at line 86 of file FM3DMagnetoStatic.h.
getIndex() [1/2]
_FM3DMagnetoStatic::IndexTriplet _FM3DMagnetoStatic::getIndex (const Vector_t & X) const inline private
Definition at line 103 of file FM3DMagnetoStatic.h.
References floor(), hx_m, hy_m, hz_m, _FM3DMagnetoStatic::IndexTriplet::i, _FM3DMagnetoStatic::IndexTriplet::j, _FM3DMagnetoStatic::IndexTriplet::k, num_gridpx_m, num_gridpy_m, num_gridpz_m, PAssert_LT, _FM3DMagnetoStatic::IndexTriplet::weight, X, xbegin_m, ybegin_m, and zbegin_m.
Referenced by getWeightedData(), interpolateTrilinearly(), and readMap().
getIndex() [2/2]
unsigned long _FM3DMagnetoStatic::getIndex (unsigned int i, unsigned int j, unsigned int k) const inline private
Definition at line 94 of file FM3DMagnetoStatic.h.
References num_gridpx_m, num_gridpy_m, num_gridpz_m, and PAssert_LT.
getInfo()
void _FM3DMagnetoStatic::getInfo (Inform * msg) virtual
Implements _Fieldmap.
Definition at line 231 of file FM3DMagnetoStatic.cpp.
References endl(), _Fieldmap::Filename_m, xbegin_m, xend_m, ybegin_m, yend_m, zbegin_m, and zend_m.
getWeightedData()
double _FM3DMagnetoStatic::getWeightedData (double * data, const IndexTriplet & idx, unsigned short corner) const private
Definition at line 208 of file FM3DMagnetoStatic.cpp.
References getIndex(), HX, HY, HZ, _FM3DMagnetoStatic::IndexTriplet::i, _FM3DMagnetoStatic::IndexTriplet::j, _FM3DMagnetoStatic::IndexTriplet::k, and _FM3DMagnetoStatic::IndexTriplet::weight.
Referenced by interpolateTrilinearly().
interpolateTrilinearly()
Vector_t _FM3DMagnetoStatic::interpolateTrilinearly (const Vector_t & X) const private
Definition at line 174 of file FM3DMagnetoStatic.cpp.
References FieldstrengthBx_m, FieldstrengthBy_m, FieldstrengthBz_m, getIndex(), getWeightedData(), HX, HY, HZ, LX, LY, LZ, and X.
Referenced by getFieldstrength().
isInside()
bool _FM3DMagnetoStatic::isInside (const Vector_t & r) const inline virtual
Reimplemented from _Fieldmap.
Definition at line 78 of file FM3DMagnetoStatic.h.
References xbegin_m, xend_m, ybegin_m, yend_m, zbegin_m, and zend_m.
Referenced by getFieldstrength().
readMap()
void _FM3DMagnetoStatic::readMap () private virtual
Implements _Fieldmap.
Definition at line 97 of file FM3DMagnetoStatic.cpp.
References abs(), endl(), FieldstrengthBx_m, FieldstrengthBy_m, FieldstrengthBz_m, _Fieldmap::Filename_m, getIndex(), _Fieldmap::getLine(), hx_m, hy_m, INFOMSG, level3(), _Fieldmap::normalize_m, num_gridpx_m, num_gridpy_m, num_gridpz_m, _Fieldmap::typeset_msg(), xbegin_m, and ybegin_m.
setFrequency()
void _FM3DMagnetoStatic::setFrequency (double freq) inline virtual
Implements _Fieldmap.
Definition at line 91 of file FM3DMagnetoStatic.h.
swap()
void _FM3DMagnetoStatic::swap () virtual
Implements _Fieldmap.
Definition at line 229 of file FM3DMagnetoStatic.cpp.
Friends And Related Function Documentation
_Fieldmap
friend class _Fieldmap friend
Definition at line 74 of file FM3DMagnetoStatic.h.
Member Data Documentation
FieldstrengthBx_m
double* _FM3DMagnetoStatic::FieldstrengthBx_m private
3D array with Bx
Definition at line 55 of file FM3DMagnetoStatic.h.
Referenced by freeMap(), interpolateTrilinearly(), and readMap().
FieldstrengthBy_m
double* _FM3DMagnetoStatic::FieldstrengthBy_m private
3D array with By
Definition at line 56 of file FM3DMagnetoStatic.h.
Referenced by freeMap(), interpolateTrilinearly(), and readMap().
FieldstrengthBz_m
double* _FM3DMagnetoStatic::FieldstrengthBz_m private
3D array with Bz
Definition at line 54 of file FM3DMagnetoStatic.h.
Referenced by freeMap(), interpolateTrilinearly(), and readMap().
hx_m
double _FM3DMagnetoStatic::hx_m private
length between points in grid, x-direction
Definition at line 67 of file FM3DMagnetoStatic.h.
Referenced by _FM3DMagnetoStatic(), getIndex(), and readMap().
hy_m
double _FM3DMagnetoStatic::hy_m private
length between points in grid, y-direction
Definition at line 68 of file FM3DMagnetoStatic.h.
Referenced by _FM3DMagnetoStatic(), getIndex(), and readMap().
hz_m
double _FM3DMagnetoStatic::hz_m private
length between points in grid, z-direction
Definition at line 69 of file FM3DMagnetoStatic.h.
Referenced by _FM3DMagnetoStatic(), and getIndex().
num_gridpx_m
unsigned int _FM3DMagnetoStatic::num_gridpx_m private
Read in number of points after 0(not counted here) in grid, r-direction
Definition at line 70 of file FM3DMagnetoStatic.h.
Referenced by _FM3DMagnetoStatic(), getIndex(), and readMap().
num_gridpy_m
unsigned int _FM3DMagnetoStatic::num_gridpy_m private
Read in number of points after 0(not counted here) in grid, r-direction
Definition at line 71 of file FM3DMagnetoStatic.h.
Referenced by _FM3DMagnetoStatic(), getIndex(), and readMap().
num_gridpz_m
unsigned int _FM3DMagnetoStatic::num_gridpz_m private
Read in number of points after 0(not counted here) in grid, z-direction
Definition at line 72 of file FM3DMagnetoStatic.h.
Referenced by _FM3DMagnetoStatic(), getIndex(), and readMap().
xbegin_m
double _FM3DMagnetoStatic::xbegin_m private
Definition at line 58 of file FM3DMagnetoStatic.h.
Referenced by _FM3DMagnetoStatic(), getIndex(), getInfo(), isInside(), and readMap().
xend_m
double _FM3DMagnetoStatic::xend_m private
Definition at line 59 of file FM3DMagnetoStatic.h.
Referenced by _FM3DMagnetoStatic(), getInfo(), and isInside().
ybegin_m
double _FM3DMagnetoStatic::ybegin_m private
Definition at line 61 of file FM3DMagnetoStatic.h.
Referenced by _FM3DMagnetoStatic(), getIndex(), getInfo(), isInside(), and readMap().
yend_m
double _FM3DMagnetoStatic::yend_m private
Definition at line 62 of file FM3DMagnetoStatic.h.
Referenced by _FM3DMagnetoStatic(), getInfo(), and isInside().
zbegin_m
double _FM3DMagnetoStatic::zbegin_m private
Definition at line 64 of file FM3DMagnetoStatic.h.
Referenced by _FM3DMagnetoStatic(), getFieldDimensions(), getIndex(), getInfo(), and isInside().
zend_m
double _FM3DMagnetoStatic::zend_m private
Definition at line 65 of file FM3DMagnetoStatic.h.
Referenced by _FM3DMagnetoStatic(), getFieldDimensions(), getInfo(), and isInside().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/FM3DMagnetoStatic.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/FM3DMagnetoStatic.cpp