OPAL (Object Oriented Parallel Accelerator Library): Attributes::TokenListArray Class Reference
Attributes::TokenListArray Class Reference
Parser for an attribute of type token list array.
#include <TokenListArray.h>
Public Member Functions
TokenListArray (const std::string &name, const std::string &help)
Constructor.
virtual ~TokenListArray ()
virtual const std::string & getType () const
Return attribute type string `‘token list array’'.
virtual void parse (Attribute &, Statement &, bool) const
Parse the attribute.
virtual void parseComponent (Attribute &, Statement &, bool, int) const
Parse a component.
Public Member Functions inherited from AttributeHandler
AttributeHandler (const std::string &name, const std::string &help, AttributeBase *def)
Constructor.
virtual ~AttributeHandler ()
virtual AttributeHandler * clone () const
Make clone.
virtual AttributeBase * getDefault () const
Return default value.
virtual const std::string & getHelp () const
Return help string.
virtual const std::string & getName () const
Return attribute name.
bool isDeferred () const
Return defer flag.
void setDeferred (bool)
Set or reset defer flag.
bool isReadOnly () const
Return read-only flag.
void setReadOnly (bool)
Set or reset read-only flag.
void setPredefinedValues (const std::set< std::string > &, const std::string &)
Add predefined strings values to the help.
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
TokenListArray ()
TokenListArray (const TokenListArray &)
void operator= (const TokenListArray &)
Additional Inherited Members
Public Types inherited from AttributeHandler
enum OwnerType {
ELEMENT, COMMAND, SUB_COMMAND, STATEMENT,
NONE
}
Static Public Member Functions inherited from AttributeHandler
static std::multimap< OwnerType, std::string > getOwner (const std::string &att)
static void addAttributeOwner (const std::string &owner, const OwnerType &type, const std::string &name)
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from AttributeHandler
const std::string itsName
Attribute name.
const std::string itsHelp
Help text.
Pointer< AttributeBase > itsDefault
Default value.
bool is_deferred
Defer flag.
bool is_readonly
Read-only flag.
Detailed Description
Parser for an attribute of type token list array.
Definition at line 34 of file TokenListArray.h.
Constructor & Destructor Documentation
TokenListArray() [1/3]
Attributes::TokenListArray::TokenListArray (const std::string & name, const std::string & help)
Constructor.
Definition at line 34 of file TokenListArray.cpp.
~TokenListArray()
Attributes::TokenListArray::~TokenListArray () virtual
Definition at line 39 of file TokenListArray.cpp.
TokenListArray() [2/3]
Attributes::TokenListArray::TokenListArray () private
TokenListArray() [3/3]
Attributes::TokenListArray::TokenListArray (const TokenListArray &) private
Member Function Documentation
getType()
const std::string & Attributes::TokenListArray::getType () const virtual
Return attribute type string `‘token list array’'.
Implements AttributeHandler.
Definition at line 43 of file TokenListArray.cpp.
operator=()
void Attributes::TokenListArray::operator= (const TokenListArray &) private
parse()
void Attributes::TokenListArray::parse (Attribute & attr, Statement & stat, bool) const virtual
Parse the attribute.
Implements AttributeHandler.
Definition at line 49 of file TokenListArray.cpp.
References Expressions::parseTokenListArray(), and Attributes::setTokenListArray().
parseComponent()
void Attributes::TokenListArray::parseComponent (Attribute & attr, Statement & statement, bool , int index) const virtual
Parse a component.
Reimplemented from AttributeHandler.
Definition at line 55 of file TokenListArray.cpp.
References Attribute::getBase(), Expressions::parseTokenList(), and Attributes::setTokenListArray().
The documentation for this class was generated from the following files:
src/Attributes/TokenListArray.h
src/Attributes/TokenListArray.cpp