OPAL (Object Oriented Parallel Accelerator Library): ValueDefinition Class Reference
ValueDefinition Class Reference
The base class for all OPAL value definitions.
#include <ValueDefinition.h>
Public Member Functions
virtual ~ValueDefinition ()
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual bool getBool () const
Return logical value.
virtual bool getBoolComponent (int) const
Return indexed logical value.
virtual double getReal () const
Return real value.
virtual double getRealComponent (int) const
Return indexed real value.
virtual std::string getString () const
Return string value.
virtual std::string getStringComponent (int) const
Return indexed string value.
Attribute & value ()
Return the attribute representing the value of the definition.
const Attribute & value () const
Return the attribute representing the value of the definition.
Public Member Functions inherited from Object
virtual ~Object ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual Object * clone (const std::string &name)=0
Return a clone.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Member Functions
ValueDefinition (int size, const char *name, const char *help)
Constructor for exemplars.
ValueDefinition (const std::string &name, ValueDefinition *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes
const std::string itsPrefix
The declaration prefix.
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Member Functions
ValueDefinition ()
ValueDefinition (const ValueDefinition &)
void operator= (const ValueDefinition &)
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Detailed Description
The base class for all OPAL value definitions.
Definition at line 31 of file ValueDefinition.h.
Constructor & Destructor Documentation
~ValueDefinition()
ValueDefinition::~ValueDefinition () virtual
Definition at line 28 of file ValueDefinition.cpp.
ValueDefinition() [1/4]
ValueDefinition::ValueDefinition (int size, const char * name, const char * help) protected
Constructor for exemplars.
Definition at line 100 of file ValueDefinition.cpp.
ValueDefinition() [2/4]
ValueDefinition::ValueDefinition (const std::string & name, ValueDefinition * parent) protected
Constructor for clones.
Definition at line 105 of file ValueDefinition.cpp.
ValueDefinition() [3/4]
ValueDefinition::ValueDefinition () private
ValueDefinition() [4/4]
ValueDefinition::ValueDefinition (const ValueDefinition &) private
Member Function Documentation
getBool()
bool ValueDefinition::getBool () const virtual
Return logical value.
Reimplemented in BoolConstant.
Definition at line 47 of file ValueDefinition.cpp.
References Object::getOpalName().
getBoolComponent()
bool ValueDefinition::getBoolComponent (int) const virtual
Return indexed logical value.
Definition at line 54 of file ValueDefinition.cpp.
References Object::getOpalName().
getCategory()
const std::string ValueDefinition::getCategory () const virtual
Return the object category as a string.
Implements Object.
Definition at line 32 of file ValueDefinition.cpp.
getReal()
double ValueDefinition::getReal () const virtual
Return real value.
Reimplemented in RealConstant, and RealVariable.
Definition at line 61 of file ValueDefinition.cpp.
References Object::getOpalName().
Referenced by OpalData::getP0().
getRealComponent()
double ValueDefinition::getRealComponent (int) const virtual
Return indexed real value.
Reimplemented in RealVector.
Definition at line 68 of file ValueDefinition.cpp.
References Object::getOpalName().
getString()
std::string ValueDefinition::getString () const virtual
Return string value.
Reimplemented in StringConstant.
Definition at line 75 of file ValueDefinition.cpp.
References Object::getOpalName().
getStringComponent()
std::string ValueDefinition::getStringComponent (int) const virtual
Return indexed string value.
Definition at line 82 of file ValueDefinition.cpp.
References Object::getOpalName().
operator=()
void ValueDefinition::operator= (const ValueDefinition &) private
shouldTrace()
bool ValueDefinition::shouldTrace () const virtual
Trace flag.
Implements Object.
Definition at line 37 of file ValueDefinition.cpp.
shouldUpdate()
bool ValueDefinition::shouldUpdate () const virtual
Update flag.
Implements Object.
Definition at line 42 of file ValueDefinition.cpp.
value() [1/2]
Attribute & ValueDefinition::value ()
Return the attribute representing the value of the definition.
Definition at line 89 of file ValueDefinition.cpp.
References Object::itsAttr.
Referenced by RealConstant::RealConstant(), RealVariable::RealVariable(), and StringConstant::StringConstant().
value() [2/2]
const Attribute & ValueDefinition::value () const
Return the attribute representing the value of the definition.
Definition at line 94 of file ValueDefinition.cpp.
References Object::itsAttr.
Member Data Documentation
itsPrefix
const std::string ValueDefinition::itsPrefix protected
The declaration prefix.
Definition at line 95 of file ValueDefinition.h.
The documentation for this class was generated from the following files:
src/AbstractObjects/ValueDefinition.h
src/AbstractObjects/ValueDefinition.cpp