OPAL (Object Oriented Parallel Accelerator Library): matheval::detail::grammar< real_t, Iterator >::ufunc_ Struct Reference
matheval::detail::grammar< real_t, Iterator >::ufunc_ Struct Reference
symbol table for unary functions like "abs"
#include <matheval.hpp>
Inherits symbols< std::iterator_traits< Iterator >::value_type, unary_op< real_t >::op_t >.
Public Member Functions
ufunc_ ()
Detailed Description
template<typename real_t, typename Iterator>
struct matheval::detail::grammar< real_t, Iterator >::ufunc_
symbol table for unary functions like "abs"
Definition at line 405 of file matheval.hpp.
Constructor & Destructor Documentation
ufunc_()
template<typename real_t, typename Iterator> matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_ () inline
Definition at line 411 of file matheval.hpp.
References abs(), acos(), asin(), atan(), ceil(), cos(), cosh(), matheval::detail::math::deg(), erf(), erfc(), exp(), floor(), matheval::detail::math::isinf(), matheval::detail::math::isnan(), log(), log10(), matheval::detail::math::rad(), matheval::detail::math::sgn(), sin(), sinh(), sqrt(), tan(), and tanh().
The documentation for this struct was generated from the following file:
src/Classic/Utilities/MSLang/matheval.hpp