OPAL (Object Oriented Parallel Accelerator Library): LineTemplate Class Reference
LineTemplate Class Reference
#include <LineTemplate.h>
Public Member Functions
LineTemplate ()
virtual ~LineTemplate ()
virtual LineTemplate * clone (const std::string &name)
Make clone.
virtual Object * makeInstance (const std::string &name, Statement &stat, const Parser *)
Make line instance.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Make a line template.
void parseTemplate (TokenStream &is, Statement &stat)
Parse the line template.
Public Member Functions inherited from Macro
Macro (int size, const char *name, const char *help)
Exemplar constructor.
Macro (const std::string &name, Object *parent)
Clone constructor.
virtual ~Macro ()
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual void parseActuals (Statement &)
Parse actual arguments.
virtual void parseFormals (Statement &)
Parse formal arguments.
Public Member Functions inherited from Object
virtual ~Object ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
LineTemplate (const LineTemplate &)
void operator= (const LineTemplate &)
LineTemplate (const std::string &name, Object *parent)
Private Attributes
MacroStream body
Friends
class Line
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Macro
std::vector< std::string > formals
The formal argument list.
std::vector< std::vector< Token > > actuals
The actual argument list.
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 34 of file LineTemplate.h.
Constructor & Destructor Documentation
LineTemplate() [1/3]
LineTemplate::LineTemplate ()
Definition at line 34 of file LineTemplate.cpp.
~LineTemplate()
LineTemplate::~LineTemplate () virtual
Definition at line 47 of file LineTemplate.cpp.
LineTemplate() [2/3]
LineTemplate::LineTemplate (const LineTemplate &) private
LineTemplate() [3/3]
LineTemplate::LineTemplate (const std::string & name, Object * parent) private
Definition at line 42 of file LineTemplate.cpp.
Member Function Documentation
clone()
LineTemplate * LineTemplate::clone (const std::string & name) virtual
Make clone.
Reimplemented from Macro.
Definition at line 51 of file LineTemplate.cpp.
makeInstance()
Object * LineTemplate::makeInstance (const std::string & name, Statement & stat, const Parser *) virtual
Make line instance.
Reimplemented from Object.
Definition at line 58 of file LineTemplate.cpp.
References Macro::actuals, Statement::append(), body, Line::clone(), Object::copyAttributes(), OpalData::find(), Macro::formals, OpalData::getInstance(), Object::getOpalName(), Token::getWord(), Token::isEOF(), Token::isWord(), name, Line::parse(), Macro::parseActuals(), MacroStream::readToken(), MacroStream::start(), and Statement::start().
makeTemplate()
Object * LineTemplate::makeTemplate (const std::string & , TokenStream & , Statement &) virtual
Make a line template.
Reimplemented from Object.
Definition at line 109 of file LineTemplate.cpp.
operator=()
void LineTemplate::operator= (const LineTemplate &) private
parseTemplate()
void LineTemplate::parseTemplate (TokenStream & is, Statement & stat)
Parse the line template.
Definition at line 115 of file LineTemplate.cpp.
References MacroStream::append(), Statement::atEnd(), body, Statement::getCurrent(), Token::isDel(), Statement::keyword(), Macro::parseFormals(), and PAssert.
Referenced by Line::makeTemplate().
Friends And Related Function Documentation
Line
friend class Line friend
Definition at line 36 of file LineTemplate.h.
Member Data Documentation
body
MacroStream LineTemplate::body private
Definition at line 71 of file LineTemplate.h.
Referenced by makeInstance(), and parseTemplate().
The documentation for this class was generated from the following files:
src/Lines/LineTemplate.h
src/Lines/LineTemplate.cpp