OPAL (Object Oriented Parallel Accelerator Library): DriftRep Class Reference
DriftRep Class Reference
#include <DriftRep.h>
Public Member Functions
DriftRep (const std::string &name)
Constructor with given name.
DriftRep ()
DriftRep (const DriftRep &)
virtual ~DriftRep ()
virtual ElementBase * clone () const
Return clone.
virtual Channel * getChannel (const std::string &aKey, bool=false)
Construct a read/write channel.
virtual NullField & getField ()
Get field.
virtual const NullField & getField () const
Get field.
virtual StraightGeometry & getGeometry ()
Get geometry.
virtual const StraightGeometry & getGeometry () const
Get geometry.
Public Member Functions inherited from Drift
Drift (const std::string &name)
Constructor with given name.
Drift ()
Drift (const Drift &right)
virtual ~Drift ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to Drift.
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void finalise () override
virtual bool bends () const override
virtual ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
void setNSlices (const std::size_t &nSlices)
std::size_t getNSlices () const
virtual int getRequiredNumberOfTimeSteps () const override
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B)
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void operator= (const DriftRep &)
Private Attributes
NullField field
The zero magnetic field.
StraightGeometry geometry
The geometry.
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 26 of file DriftRep.h.
Constructor & Destructor Documentation
DriftRep() [1/3]
DriftRep::DriftRep (const std::string & name) explicit
Constructor with given name.
Definition at line 52 of file DriftRep.cpp.
DriftRep() [2/3]
DriftRep::DriftRep ()
Definition at line 40 of file DriftRep.cpp.
Referenced by clone().
DriftRep() [3/3]
DriftRep::DriftRep (const DriftRep & right)
Definition at line 46 of file DriftRep.cpp.
~DriftRep()
DriftRep::~DriftRep () virtual
Definition at line 58 of file DriftRep.cpp.
Member Function Documentation
clone()
ElementBase * DriftRep::clone () const virtual
Return clone.
Implements ElementBase.
Definition at line 62 of file DriftRep.cpp.
References DriftRep().
getChannel()
Channel * DriftRep::getChannel (const std::string & aKey, bool create = false) virtual
Construct a read/write channel.
Reimplemented from ElementBase.
Definition at line 67 of file DriftRep.cpp.
References ElementBase::getChannel().
getField() [1/2]
NullField & DriftRep::getField () virtual
Get field.
Implements Component.
Definition at line 78 of file DriftRep.cpp.
References field.
getField() [2/2]
const NullField & DriftRep::getField () const virtual
Get field.
Implements Component.
Definition at line 82 of file DriftRep.cpp.
References field.
getGeometry() [1/2]
StraightGeometry & DriftRep::getGeometry () virtual
Get geometry.
Implements ElementBase.
Definition at line 87 of file DriftRep.cpp.
References geometry.
getGeometry() [2/2]
const StraightGeometry & DriftRep::getGeometry () const virtual
Get geometry.
Implements ElementBase.
Definition at line 91 of file DriftRep.cpp.
References geometry.
operator=()
void DriftRep::operator= (const DriftRep &) private
Member Data Documentation
field
NullField DriftRep::field private
The zero magnetic field.
Definition at line 69 of file DriftRep.h.
Referenced by getField().
geometry
StraightGeometry DriftRep::geometry private
The geometry.
Definition at line 72 of file DriftRep.h.
Referenced by getGeometry().
The documentation for this class was generated from the following files:
src/Classic/BeamlineCore/DriftRep.h
src/Classic/BeamlineCore/DriftRep.cpp