OPAL (Object Oriented Parallel Accelerator Library): BeamSequence Class Reference
BeamSequence Class Reference abstract
The base class for all OPAL beam lines and sequences.
#include <BeamSequence.h>
Public Member Functions
virtual ~BeamSequence ()
virtual BeamSequence * copy (const std::string &name)=0
Make complete copy.
virtual const std::string getCategory () const
Return the object category as a string.
virtual Beamline * fetchLine () const =0
Return the embedded CLASSIC beam line.
Public Member Functions inherited from Element
virtual ~Element ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual double getLength () const =0
Return element length.
virtual double getEntrance (ReferenceType) const
Return arc length from origin to entrance (negative !).
virtual double getExit (ReferenceType) const
Return arc length from origin to exit (positive !).
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded CLASSIC element.
void setElement (ElementBase *)
Assign new CLASSIC element.
Public Member Functions inherited from Object
virtual ~Object ()
virtual Object * clone (const std::string &name)=0
Return a clone.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static BeamSequence * find (const std::string &name)
Find a BeamSequence by name.
Static Public Member Functions inherited from Element
static Element * find (const std::string &name)
Find named Element.
Protected Member Functions
BeamSequence (int size, const char *name, const char *help)
Constructor for exemplars.
BeamSequence (const std::string &name, BeamSequence *parent)
Constructor for clones.
Protected Member Functions inherited from Element
Element (int size, const char *name, const char *help)
Constructor for exemplars.
Element (const std::string &name, Element *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Private Member Functions
BeamSequence ()
BeamSequence (const BeamSequence &)
void operator= (const BeamSequence &)
Additional Inherited Members
Public Types inherited from Element
enum ReferenceType { IS_ENTRY, IS_CENTRE, IS_EXIT }
Reference for element positioning.
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
The base class for all OPAL beam lines and sequences.
Definition at line 32 of file BeamSequence.h.
Constructor & Destructor Documentation
~BeamSequence()
BeamSequence::~BeamSequence () virtual
Definition at line 27 of file BeamSequence.cpp.
BeamSequence() [1/4]
BeamSequence::BeamSequence (int size, const char * name, const char * help) protected
Constructor for exemplars.
Definition at line 47 of file BeamSequence.cpp.
BeamSequence() [2/4]
BeamSequence::BeamSequence (const std::string & name, BeamSequence * parent) protected
Constructor for clones.
Definition at line 52 of file BeamSequence.cpp.
BeamSequence() [3/4]
BeamSequence::BeamSequence () private
BeamSequence() [4/4]
BeamSequence::BeamSequence (const BeamSequence &) private
Member Function Documentation
copy()
virtual BeamSequence* BeamSequence::copy (const std::string & name) pure virtual
Make complete copy.
Implemented in Sequence, and Line.
fetchLine()
virtual Beamline* BeamSequence::fetchLine () const pure virtual
Return the embedded CLASSIC beam line.
Implemented in Sequence, and Line.
Referenced by Distribution::createMatchedGaussDistribution(), and TrackRun::setupCyclotronTracker().
find()
BeamSequence * BeamSequence::find (const std::string & name) static
Find a BeamSequence by name.
Definition at line 36 of file BeamSequence.cpp.
References OpalData::find(), OpalData::getInstance(), and name.
Referenced by Distribution::createMatchedGaussDistribution(), and TrackCmd::execute().
getCategory()
const std::string BeamSequence::getCategory () const virtual
Return the object category as a string.
Reimplemented from Element.
Definition at line 31 of file BeamSequence.cpp.
operator=()
void BeamSequence::operator= (const BeamSequence &) private
The documentation for this class was generated from the following files:
src/AbstractObjects/BeamSequence.h
src/AbstractObjects/BeamSequence.cpp