OPAL (Object Oriented Parallel Accelerator Library): StringConstant Class Reference
StringConstant Class Reference
#include <StringConstant.h>
Public Member Functions
StringConstant ()
Exemplar constructor.
virtual ~StringConstant ()
virtual bool canReplaceBy (Object *object)
Test if object can be replaced.
virtual StringConstant * clone (const std::string &name)
Make clone.
virtual void print (std::ostream &) const
Print the constant.
virtual void printValue (std::ostream &os) const
Print its value.
virtual std::string getString () const
Return value.
Public Member Functions inherited from ValueDefinition
virtual ~ValueDefinition ()
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual bool getBool () const
Return logical value.
virtual bool getBoolComponent (int) const
Return indexed logical value.
virtual double getReal () const
Return real value.
virtual double getRealComponent (int) const
Return indexed real value.
virtual std::string getStringComponent (int) const
Return indexed string value.
Attribute & value ()
Return the attribute representing the value of the definition.
const Attribute & value () const
Return the attribute representing the value of the definition.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
StringConstant (const StringConstant &)
void operator= (const StringConstant &)
StringConstant (const std::string &name, StringConstant *parent)
StringConstant (const std::string &name, StringConstant *parent, const std::string &value)
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from ValueDefinition
ValueDefinition (int size, const char *name, const char *help)
Constructor for exemplars.
ValueDefinition (const std::string &name, ValueDefinition *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from ValueDefinition
const std::string itsPrefix
The declaration prefix.
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 24 of file StringConstant.h.
Constructor & Destructor Documentation
StringConstant() [1/4]
StringConstant::StringConstant ()
Exemplar constructor.
Definition at line 30 of file StringConstant.cpp.
References OpalData::create(), CREATE_STRINGCONSTANT, Util::getGitRevision(), OpalData::getInstance(), Object::itsAttr, Attributes::makeString(), Object::registerOwnership(), and AttributeHandler::STATEMENT.
Referenced by clone().
~StringConstant()
StringConstant::~StringConstant () virtual
Definition at line 280 of file StringConstant.cpp.
StringConstant() [2/4]
StringConstant::StringConstant (const StringConstant &) private
StringConstant() [3/4]
StringConstant::StringConstant (const std::string & name, StringConstant * parent) private
Definition at line 266 of file StringConstant.cpp.
StringConstant() [4/4]
StringConstant::StringConstant (const std::string & name, StringConstant * parent, const std::string & value) private
Definition at line 271 of file StringConstant.cpp.
References Object::builtin, Object::itsAttr, Attributes::setString(), and ValueDefinition::value().
Member Function Documentation
canReplaceBy()
bool StringConstant::canReplaceBy (Object * object) virtual
Test if object can be replaced.
Reimplemented from Object.
Definition at line 284 of file StringConstant.cpp.
clone()
StringConstant * StringConstant::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 289 of file StringConstant.cpp.
References name, and StringConstant().
getString()
std::string StringConstant::getString () const virtual
Return value.
Reimplemented from ValueDefinition.
Definition at line 294 of file StringConstant.cpp.
References Attributes::getString(), and Object::itsAttr.
Referenced by OpalData::getVariableData(), and Expressions::parseStringValue().
operator=()
void StringConstant::operator= (const StringConstant &) private
print()
void StringConstant::print (std::ostream & os) const virtual
Print the constant.
Reimplemented from Object.
Definition at line 299 of file StringConstant.cpp.
References endl(), Object::getOpalName(), and Object::itsAttr.
printValue()
void StringConstant::printValue (std::ostream & os) const virtual
Print its value.
Reimplemented from Object.
Definition at line 304 of file StringConstant.cpp.
References Object::itsAttr.
The documentation for this class was generated from the following files:
src/ValueDefinitions/StringConstant.h
src/ValueDefinitions/StringConstant.cpp