OPAL (Object Oriented Parallel Accelerator Library): Array1D< T > Class Template Reference
Array1D< T > Class Template Reference
One-dimensional array.
#include <Array1D.h>
Public Types
typedef T value_type
The value type of this array.
typedef T * iterator
The iterator type for the array.
typedef const T * const_iterator
The iterator type for constant array.
Public Member Functions
Array1D ()
Default constructor.
Array1D (int n)
Constructor.
Array1D (int n, const T &t)
Constructor.
Array1D (const Array1D< T > &)
~Array1D ()
Array1D< T > & operator= (const Array1D< T > &)
T & operator() (int n)
Get reference to element.
const T & operator() (int n) const
Get value of element.
T & operator[] (int)
Get reference to element.
const T & operator[] (int) const
Get value of element.
iterator begin ()
Get beginning of data.
iterator end ()
Get end of data.
const_iterator begin () const
Get beginning of data.
const_iterator end () const
Get end of data.
int size () const
Get array size.
void resize (int size)
Change array size.
Protected Attributes
int len
T * data
Detailed Description
template<class T>
class Array1D< T >
One-dimensional array.
Definition at line 36 of file Array1D.h.
Member Typedef Documentation
const_iterator
template<class T> typedef const T* Array1D< T >::const_iterator
The iterator type for constant array.
Definition at line 47 of file Array1D.h.
iterator
template<class T> typedef T* Array1D< T >::iterator
The iterator type for the array.
Definition at line 44 of file Array1D.h.
value_type
template<class T> typedef T Array1D< T >::value_type
The value type of this array.
Definition at line 41 of file Array1D.h.
Constructor & Destructor Documentation
Array1D() [1/4]
template<class T > Array1D< T >::Array1D ()
Default constructor.
Definition at line 127 of file Array1D.h.
Array1D() [2/4]
template<class T > Array1D< T >::Array1D (int n) explicit
Constructor.
Definition at line 140 of file Array1D.h.
Array1D() [3/4]
template<class T> Array1D< T >::Array1D (int n, const T & t)
Constructor.
Definition at line 146 of file Array1D.h.
Array1D() [4/4]
template<class T> Array1D< T >::Array1D (const Array1D< T > & array)
Definition at line 133 of file Array1D.h.
~Array1D()
template<class T > Array1D< T >::~Array1D ()
Definition at line 153 of file Array1D.h.
Member Function Documentation
begin() [1/2]
template<class T > Array1D< T >::iterator Array1D< T >::begin ()
Get beginning of data.
Definition at line 204 of file Array1D.h.
Referenced by Array1D< Tps< T > >::Array1D(), LUMatrix< T >::backSubstitute(), FTps< double, 2 *3 >::derivative(), Matrix< T >::dotcv(), Matrix< T >::dotrv(), euclidean_norm(), FTps< double, 2 *3 >::evalMonoms(), Array2D< int >::getColumn(), TpsData::getProductArray(), Array2D< int >::getRow(), FVps< T, N >::linearTerms(), operator*(), operator+(), Vector< T >::operator+=(), Vector< T >::operator-(), operator-(), Vector< T >::operator-=(), Array1D< Tps< T > >::operator=(), Array2D< int >::putColumn(), Array2D< int >::putRow(), and FLieGenerator< T, N >::transform().
begin() [2/2]
template<class T > Array1D< T >::const_iterator Array1D< T >::begin () const
Get beginning of data.
Definition at line 216 of file Array1D.h.
end() [1/2]
template<class T > Array1D< T >::iterator Array1D< T >::end ()
Get end of data.
Definition at line 210 of file Array1D.h.
Referenced by Array1D< Tps< T > >::Array1D(), Matrix< T >::dotrv(), euclidean_norm(), operator*(), operator+(), operator-(), Array1D< Tps< T > >::operator=(), Array2D< int >::putColumn(), and Array2D< int >::putRow().
end() [2/2]
template<class T > Array1D< T >::const_iterator Array1D< T >::end () const
Get end of data.
Definition at line 222 of file Array1D.h.
operator()() [1/2]
template<class T > T & Array1D< T >::operator() (int n)
Get reference to element.
Definition at line 186 of file Array1D.h.
operator()() [2/2]
template<class T > const T & Array1D< T >::operator() (int n) const
Get value of element.
Definition at line 195 of file Array1D.h.
operator=()
template<class T> Array1D< T > & Array1D< T >::operator= (const Array1D< T > & rhs)
Definition at line 159 of file Array1D.h.
Referenced by Vector< T >::operator=().
operator[]() [1/2]
template<class T > T & Array1D< T >::operator[] (int i) inline
Get reference to element.
Definition at line 174 of file Array1D.h.
operator[]() [2/2]
template<class T > const T & Array1D< T >::operator[] (int i) const inline
Get value of element.
Definition at line 180 of file Array1D.h.
resize()
template<class T > void Array1D< T >::resize (int size)
Change array size.
Definition at line 234 of file Array1D.h.
size()
template<class T > int Array1D< T >::size () const
Get array size.
Definition at line 228 of file Array1D.h.
Referenced by LUMatrix< T >::backSubstitute(), VpsMap< T >::constantTerm(), Matrix< T >::dotcv(), Matrix< T >::dotrv(), Tps< T >::evaluate(), Array2D< int >::getColumn(), TpsMonomial::getIndex(), TpsMonomial::getOrder(), Array2D< int >::getRow(), TpsMonomial::getVariables(), operator+(), Vps< T >::operator+=(), operator-(), Vps< T >::operator-=(), Array2D< int >::putColumn(), Array2D< int >::putRow(), scaled_norm(), VpsMap< T >::substitute(), Tps< T >::substitute(), and FLieGenerator< T, N >::transform().
Member Data Documentation
data
template<class T> T* Array1D< T >::data protected
Definition at line 119 of file Array1D.h.
len
template<class T> int Array1D< T >::len protected
Definition at line 116 of file Array1D.h.
Referenced by Array1D< Tps< T > >::operator=().
The documentation for this class was generated from the following file:
src/Classic/Algebra/Array1D.h