OPAL (Object Oriented Parallel Accelerator Library): TpsMonomial Class Reference
TpsMonomial Class Reference
Exponent array for Tps<T>.
#include <TpsMonomial.h>
Public Member Functions
TpsMonomial (int nVar)
Constructor.
TpsMonomial (int nVar, int var)
Constructor.
TpsMonomial ()
TpsMonomial (const TpsMonomial &)
~TpsMonomial ()
const TpsMonomial & operator= (const TpsMonomial &)
int & operator[] (int index)
Get exponent.
int operator[] (int index) const
Get exponent.
TpsMonomial operator* (const TpsMonomial &rhs) const
Product.
int getIndex () const
Convert.
int getOrder () const
Get order.
int getVariables () const
Get variables.
Private Attributes
Array1D< int > array
Detailed Description
Exponent array for Tps<T>.
Definition at line 31 of file TpsMonomial.h.
Constructor & Destructor Documentation
TpsMonomial() [1/4]
TpsMonomial::TpsMonomial (int nVar)
Constructor.
Definition at line 38 of file TpsMonomial.cpp.
TpsMonomial() [2/4]
TpsMonomial::TpsMonomial (int nVar, int var)
Constructor.
Definition at line 43 of file TpsMonomial.cpp.
References array.
TpsMonomial() [3/4]
TpsMonomial::TpsMonomial ()
Definition at line 28 of file TpsMonomial.cpp.
TpsMonomial() [4/4]
TpsMonomial::TpsMonomial (const TpsMonomial & rhs)
Definition at line 33 of file TpsMonomial.cpp.
~TpsMonomial()
TpsMonomial::~TpsMonomial ()
Definition at line 49 of file TpsMonomial.cpp.
Member Function Documentation
getIndex()
int TpsMonomial::getIndex () const
Convert.
Definition at line 77 of file TpsMonomial.cpp.
References array, getOrder(), TpsData::getTpsData(), TpsData::indexMonomial(), and Array1D< T >::size().
Referenced by Tps< T >::get(), Tps< T >::getCoefficient(), Tps< T >::operator[](), and Tps< T >::setCoefficient().
getOrder()
int TpsMonomial::getOrder () const
Get order.
Definition at line 83 of file TpsMonomial.cpp.
References array, and Array1D< T >::size().
Referenced by getIndex(), and Tps< T >::makeMonomial().
getVariables()
int TpsMonomial::getVariables () const
Get variables.
Definition at line 94 of file TpsMonomial.cpp.
References array, and Array1D< T >::size().
Referenced by Tps< T >::getCoefficient(), Tps< T >::makeMonomial(), operator*(), and Tps< T >::setCoefficient().
operator*()
TpsMonomial TpsMonomial::operator* (const TpsMonomial & rhs) const
Product.
Definition at line 69 of file TpsMonomial.cpp.
References array, getVariables(), and Hypervolume::n.
operator=()
const TpsMonomial & TpsMonomial::operator= (const TpsMonomial & rhs)
Definition at line 53 of file TpsMonomial.cpp.
References array.
operator[]() [1/2]
int & TpsMonomial::operator[] (int index)
Get exponent.
Definition at line 59 of file TpsMonomial.cpp.
References array.
operator[]() [2/2]
int TpsMonomial::operator[] (int index) const
Get exponent.
Definition at line 64 of file TpsMonomial.cpp.
References array.
Member Data Documentation
array
Array1D<int> TpsMonomial::array private
Definition at line 78 of file TpsMonomial.h.
Referenced by getIndex(), getOrder(), getVariables(), operator*(), operator=(), operator[](), and TpsMonomial().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algebra/TpsMonomial.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algebra/TpsMonomial.cpp