OPAL (Object Oriented Parallel Accelerator Library): Attributes::UpperCaseStringArray Class Reference
Attributes::UpperCaseStringArray Class Reference
Parser for an attribute of type string array.
#include <UpperCaseStringArray.h>
Public Member Functions
UpperCaseStringArray (const std::string &name, const std::string &help)
Constructor.
virtual ~UpperCaseStringArray ()
virtual const std::string & getType () const
Return attribute type string `‘string array’'.
virtual void parse (Attribute &, Statement &, bool) const
Parse the attribute.
virtual void parseComponent (Attribute &, Statement &, bool, int) const
Parse a component of the array.
Public Member Functions inherited from AttributeHandler
AttributeHandler (const std::string &name, const std::string &help, AttributeBase *def)
Constructor.
virtual ~AttributeHandler ()
virtual AttributeHandler * clone () const
Make clone.
virtual AttributeBase * getDefault () const
Return default value.
virtual const std::string & getHelp () const
Return help string.
virtual const std::string & getName () const
Return attribute name.
bool isDeferred () const
Return defer flag.
void setDeferred (bool)
Set or reset defer flag.
bool isReadOnly () const
Return read-only flag.
void setReadOnly (bool)
Set or reset read-only flag.
void setPredefinedValues (const std::set< std::string > &, const std::string &)
Add predefined strings values to the help.
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
UpperCaseStringArray ()
UpperCaseStringArray (const UpperCaseStringArray &)
void operator= (const UpperCaseStringArray &)
Additional Inherited Members
Public Types inherited from AttributeHandler
enum OwnerType {
ELEMENT, COMMAND, SUB_COMMAND, STATEMENT,
NONE
}
Static Public Member Functions inherited from AttributeHandler
static std::multimap< OwnerType, std::string > getOwner (const std::string &att)
static void addAttributeOwner (const std::string &owner, const OwnerType &type, const std::string &name)
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from AttributeHandler
const std::string itsName
Attribute name.
const std::string itsHelp
Help text.
Pointer< AttributeBase > itsDefault
Default value.
bool is_deferred
Defer flag.
bool is_readonly
Read-only flag.
Detailed Description
Parser for an attribute of type string array.
Definition at line 30 of file UpperCaseStringArray.h.
Constructor & Destructor Documentation
UpperCaseStringArray() [1/3]
Attributes::UpperCaseStringArray::UpperCaseStringArray (const std::string & name, const std::string & help)
Constructor.
Definition at line 33 of file UpperCaseStringArray.cpp.
~UpperCaseStringArray()
Attributes::UpperCaseStringArray::~UpperCaseStringArray () virtual
Definition at line 38 of file UpperCaseStringArray.cpp.
UpperCaseStringArray() [2/3]
Attributes::UpperCaseStringArray::UpperCaseStringArray () private
UpperCaseStringArray() [3/3]
Attributes::UpperCaseStringArray::UpperCaseStringArray (const UpperCaseStringArray &) private
Member Function Documentation
getType()
const std::string & Attributes::UpperCaseStringArray::getType () const virtual
Return attribute type string `‘string array’'.
Implements AttributeHandler.
Definition at line 42 of file UpperCaseStringArray.cpp.
operator=()
void Attributes::UpperCaseStringArray::operator= (const UpperCaseStringArray &) private
parse()
void Attributes::UpperCaseStringArray::parse (Attribute & attr, Statement & stat, bool) const virtual
Parse the attribute.
Implements AttributeHandler.
Definition at line 48 of file UpperCaseStringArray.cpp.
References Expressions::parseStringArray(), and Attributes::setUpperCaseStringArray().
parseComponent()
void Attributes::UpperCaseStringArray::parseComponent (Attribute & attr, Statement & statement, bool , int index) const virtual
Parse a component of the array.
Reimplemented from AttributeHandler.
Definition at line 55 of file UpperCaseStringArray.cpp.
References Attribute::getBase(), Attributes::getStringArray(), Expressions::parseStringValue(), and Attributes::setUpperCaseStringArray().
The documentation for this class was generated from the following files:
src/Attributes/UpperCaseStringArray.h
src/Attributes/UpperCaseStringArray.cpp