OPAL (Object Oriented Parallel Accelerator Library): UserList Class Reference
UserList Class Reference
#include <UserList.h>
Public Types
typedef User::ID_t Key
typedef vmap< Key, User * > UserList_t
typedef UserList_t::iterator iterator_user
typedef UserList_t::size_type size_type_user
typedef User::ID_t ID_t
Public Member Functions
UserList ()
virtual ~UserList ()
size_type_user getNumUsers () const
ID_t getUserListID () const
bool haveUser (Key key) const
User & getUser (Key key)
iterator_user begin_user ()
iterator_user end_user ()
virtual ID_t checkinUser (User &user)
virtual void checkoutUser (Key key, bool informuser=false)
virtual void checkoutUser (const User &user, bool informuser=false)
Private Attributes
UserList_t userlist
ID_t userlistID
Detailed Description
Definition at line 37 of file UserList.h.
Member Typedef Documentation
ID_t
typedef User::ID_t UserList::ID_t
Definition at line 46 of file UserList.h.
iterator_user
typedef UserList_t::iterator UserList::iterator_user
Definition at line 43 of file UserList.h.
Key
typedef User::ID_t UserList::Key
Definition at line 41 of file UserList.h.
size_type_user
typedef UserList_t::size_type UserList::size_type_user
Definition at line 45 of file UserList.h.
UserList_t
typedef vmap<Key, User *> UserList::UserList_t
Definition at line 42 of file UserList.h.
Constructor & Destructor Documentation
UserList()
UserList::UserList ()
Definition at line 34 of file UserList.cpp.
~UserList()
UserList::~UserList () virtual
Definition at line 39 of file UserList.cpp.
References a, begin_user(), and end_user().
Member Function Documentation
begin_user()
UserList::iterator_user UserList::begin_user ()
Definition at line 77 of file UserList.cpp.
References vmap< Key, T, Compare >::begin(), and userlist.
Referenced by Mesh< Dim >::begin_if(), FieldLayout< Dim >::begin_if(), and ~UserList().
checkinUser()
UserList::ID_t UserList::checkinUser (User & user) virtual
Definition at line 109 of file UserList.cpp.
References User::get_Id(), haveUser(), userlist, and userlistID.
Referenced by Mesh< Dim >::checkin(), and RegionLayout< T, Dim, Mesh >::checkin().
checkoutUser() [1/2]
void UserList::checkoutUser (Key key, bool informuser = false) virtual
Definition at line 124 of file UserList.cpp.
References end_user(), vmap< Key, T, Compare >::erase(), vmap< Key, T, Compare >::find(), and userlist.
Referenced by Mesh< Dim >::checkout(), RegionLayout< T, Dim, Mesh >::checkout(), and checkoutUser().
checkoutUser() [2/2]
void UserList::checkoutUser (const User & user, bool informuser = false) virtual
Definition at line 138 of file UserList.cpp.
References checkoutUser(), and User::get_Id().
end_user()
UserList::iterator_user UserList::end_user ()
Definition at line 84 of file UserList.cpp.
References vmap< Key, T, Compare >::end(), and userlist.
Referenced by checkoutUser(), Mesh< Dim >::end_if(), FieldLayout< Dim >::end_if(), getUser(), and ~UserList().
getNumUsers()
UserList::size_type_user UserList::getNumUsers () const
Definition at line 47 of file UserList.cpp.
References vmap< Key, T, Compare >::size(), and userlist.
Referenced by Mesh< Dim >::size_if(), and FieldLayout< Dim >::size_if().
getUser()
User & UserList::getUser (Key key)
Definition at line 68 of file UserList.cpp.
References end_user(), vmap< Key, T, Compare >::find(), PInsist, and userlist.
getUserListID()
UserList::ID_t UserList::getUserListID () const
Definition at line 54 of file UserList.cpp.
References userlistID.
Referenced by Mesh< Dim >::get_Id(), RegionLayout< T, Dim, Mesh >::get_Id(), FieldLayout< Dim >::get_Id(), Field< Vector_t, 3, Mesh_t, Center_t >::notifyUserOfDelete(), RegionLayout< T, Dim, Mesh >::notifyUserOfDelete(), BareField< T1, D >::notifyUserOfDelete(), SIndex< Dim >::notifyUserOfDelete(), ParticleCashedLayout< T, Dim, Mesh >::Repartition(), Field< Vector_t, 3, Mesh_t, Center_t >::Repartition(), ParticleInteractLayout< T, Dim, Mesh >::Repartition(), RegionLayout< T, Dim, Mesh >::Repartition(), and SIndex< Dim >::Repartition().
haveUser()
bool UserList::haveUser (Key key) const
Definition at line 61 of file UserList.cpp.
References vmap< Key, T, Compare >::count(), and userlist.
Referenced by checkinUser().
Member Data Documentation
userlist
UserList_t UserList::userlist private
Definition at line 100 of file UserList.h.
Referenced by begin_user(), checkinUser(), checkoutUser(), end_user(), getNumUsers(), getUser(), and haveUser().
userlistID
ID_t UserList::userlistID private
Definition at line 103 of file UserList.h.
Referenced by checkinUser(), and getUserListID().
The documentation for this class was generated from the following files:
ippl/src/Utility/UserList.h
ippl/src/Utility/UserList.cpp