OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Field/AssignDefs.h File Reference
AssignDefs.h File Reference
#include "Field/AssignTags.h"
Classes
class BareField< T, Dim >
class BareFieldIterator< T, Dim >
class IndexedBareFieldIterator< T, Dim >
struct PlugBase< D >
Functions
template<class T , class C , unsigned int D>
bool for_each (const BareFieldIterator< T, D > &p, SameFieldID s, C)
template<class T , class C , unsigned int D>
bool for_each (const IndexedBareFieldIterator< T, D > &p, SameFieldID s, C)
template<class C >
bool for_each (const Index::cursor &, SameFieldID, C)
template<class T , class C >
bool for_each (const PETE_Scalar< T > &, SameFieldID, C)
template<class T , unsigned int D1, unsigned D2, class C >
bool for_each (IndexedBareFieldIterator< T, D1 > &p, const PlugBase< D2 > &f, C)
template<class C , unsigned D>
bool for_each (Index::cursor &p, const PlugBase< D > &f, C)
template<class T , class C , unsigned D>
bool for_each (const PETE_Scalar< T > &, const PlugBase< D > &, C)
template<class T , class C , unsigned int D>
bool for_each (const IndexedBareFieldIterator< T, D > &p, IsCompressed, C)
template<class T , class C , unsigned int D>
bool for_each (const BareFieldIterator< T, D > &p, IsCompressed, C)
template<class C >
bool for_each (const Index::cursor &, IsCompressed, C)
template<class T , class C >
bool for_each (const PETE_Scalar< T > &, IsCompressed, C)
template<class T , unsigned int D>
T & for_each (const BrickIterator< T, D > &p, EvalFunctor_0)
int for_each (const Index::cursor &p, EvalFunctor_0)
template<class T , unsigned int D>
T & for_each (const BrickIterator< T, D > &p, const EvalFunctor_1 &e)
template<class T , unsigned int D>
T & for_each (const BrickIterator< T, D > &p, const UnitEvalFunctor_1 &e)
int for_each (const Index::cursor &p, const EvalFunctor_1 &e)
template<class T >
T for_each (const PETE_Scalar< T > &p, const EvalFunctor_1 &)
template<class T , unsigned int D>
T & for_each (const BrickIterator< T, D > &p, const EvalFunctor_2 &e)
template<class T , unsigned int D>
T & for_each (const BrickIterator< T, D > &p, const UnitEvalFunctor_2 &e)
int for_each (const Index::cursor &p, const EvalFunctor_2 &e)
template<class T >
T for_each (const PETE_Scalar< T > &p, const EvalFunctor_2 &)
template<class T , unsigned int D>
T & for_each (const BrickIterator< T, D > &p, const EvalFunctor_3 &e)
template<class T , unsigned int D>
T & for_each (const BrickIterator< T, D > &p, const UnitEvalFunctor_3 &e)
int for_each (const Index::cursor &p, const EvalFunctor_3 &e)
template<class T >
T for_each (const PETE_Scalar< T > &p, const EvalFunctor_3 &)
template<class T , class C , unsigned int D>
int for_each (BareFieldIterator< T, D > &p, BeginLField, C)
template<class T , class C >
int for_each (PETE_Scalar< T > &, BeginLField, C)
template<class T , class C , unsigned int D>
int for_each (BareFieldIterator< T, D > &p, NextLField, C)
template<class T , class C >
int for_each (PETE_Scalar< T > &, NextLField, C)
template<class T , class C , unsigned int D>
int for_each (IndexedBareFieldIterator< T, D > &p, StepFunctor s, C)
template<class T , class C , unsigned int D>
int for_each (BareFieldIterator< T, D > &p, StepFunctor s, C)
template<class T , class C , unsigned int D>
int for_each (BrickIterator< T, D > &p, StepFunctor s, C)
template<class C >
int for_each (Index::cursor &p, StepFunctor s, C)
template<class T , class C >
int for_each (PETE_Scalar< T > &, StepFunctor, C)
template<class T , class C , unsigned int D>
int for_each (IndexedBareFieldIterator< T, D > &p, RewindFunctor s, C)
template<class T , class C , unsigned int D>
int for_each (BareFieldIterator< T, D > &p, RewindFunctor s, C)
template<class T , class C , unsigned int D>
int for_each (BrickIterator< T, D > &p, RewindFunctor s, C)
template<class C >
int for_each (Index::cursor &p, RewindFunctor s, C)
template<class T , class C >
int for_each (PETE_Scalar< T > &, RewindFunctor, C)
template<class T , class C , unsigned int D>
int for_each (BrickIterator< T, D > &p, PETE_CountElems, C)
template<class T , class C , unsigned int D>
int for_each (BareFieldIterator< T, D > &p, PETE_CountElems, C)
template<class T , class C , unsigned int D>
int for_each (IndexedBareFieldIterator< T, D > &p, PETE_CountElems, C)
template<class T , class C , unsigned int D>
int for_each (IndexedBareFieldIterator< T, D > &p, PETE_Increment, C)
template<class T , class C , unsigned int D>
int for_each (BareFieldIterator< T, D > &p, PETE_Increment, C)
template<class T , class C , unsigned int D>
int for_each (BrickIterator< T, D > &p, PETE_Increment, C)
template<class T , class C , unsigned int D>
bool for_each (const IndexedBareFieldIterator< T, D > &iter, HasUnitStride, C)
template<class T , class C , unsigned int D>
bool for_each (const BareFieldIterator< T, D > &iter, HasUnitStride, C)
template<class T , class C , unsigned int D>
bool for_each (const BrickIterator< T, D > &iter, HasUnitStride, C)
template<class C >
bool for_each (const Index::cursor &, HasUnitStride, C)
template<class T , class C >
bool for_each (const PETE_Scalar< T > &, HasUnitStride, C)
template<class T , class C , unsigned int D, unsigned int D1, class T1 >
int for_each (const IndexedBareFieldIterator< T, D > &p, const FillGCIfNecessaryTag< D1, T1 > &f, C)
template<class T , class C , unsigned int D, unsigned int D1, class T1 >
int for_each (const BareFieldIterator< T, D > &, const FillGCIfNecessaryTag< D1, T1 > &, C)
template<class T , class C , unsigned int D, class T1 >
int for_each (const PETE_Scalar< T > &, const FillGCIfNecessaryTag< D, T1 > &, C)
template<class C , unsigned int D, class T1 >
int for_each (const Index::cursor &, const FillGCIfNecessaryTag< D, T1 > &, C)
Function Documentation
for_each() [1/54]
template<class T , class C , unsigned int D> bool for_each (const BareFieldIterator< T, D > & p, SameFieldID s, C) inline
Definition at line 30 of file AssignDefs.h.
References SameFieldID::fID, and BareFieldIterator< T, Dim >::GetBareField().
Referenced by BrickExpLoop< LHS, RHS, OP, Dim >::apply(), BrickExpLoop< LHS, RHS, OP, 1U >::apply(), BrickExpLoop< LHS, RHS, OP, 2U >::apply(), BrickExpLoop< LHS, RHS, OP, 3U >::apply(), assign(), SIndexExpLoop< OP, Dim >::evaluate(), SIndexExpLoop< OP, 1U >::evaluate(), SIndexExpLoop< OP, 2U >::evaluate(), SIndexExpLoop< OP, 3U >::evaluate(), AssignActions< Dim, SIExprTag< true > >::fillgc(), AssignActions< Dim, SIExprTag< false > >::fillgc(), ClosedOrbitFinder< Value_type, Size_type, Stepper >::getMomentum(), ParallelCyclotronTracker::getTunes(), AmrMultiGrid::iterate_m(), AmrMultiGrid::map2vector_m(), AssignActions< Dim, SIExprTag< false > >::nextLField(), AssignActions< Dim, SIExprTag< true > >::plugbase(), AssignActions< Dim, SIExprTag< false > >::plugbase(), Reduction(), and TryCompressLHS().
for_each() [2/54]
template<class T , class C , unsigned int D> bool for_each (const IndexedBareFieldIterator< T, D > & p, SameFieldID s, C) inline
Definition at line 37 of file AssignDefs.h.
References SameFieldID::fID, and BareFieldIterator< T, Dim >::GetBareField().
for_each() [3/54]
template<class C > bool for_each (const Index::cursor & , SameFieldID , C) inline
Definition at line 47 of file AssignDefs.h.
for_each() [4/54]
template<class T , class C > bool for_each (const PETE_Scalar< T > & , SameFieldID , C) inline
Definition at line 57 of file AssignDefs.h.
for_each() [5/54]
template<class T , unsigned int D1, unsigned D2, class C > bool for_each (IndexedBareFieldIterator< T, D1 > & p, const PlugBase< D2 > & f, C) inline
Definition at line 81 of file AssignDefs.h.
References PlugBase< D >::Domain, and IndexedBareFieldIterator< T, Dim >::plugBase().
for_each() [6/54]
template<class C , unsigned D> bool for_each (Index::cursor & p, const PlugBase< D > & f, C) inline
Definition at line 91 of file AssignDefs.h.
References PlugBase< D >::Domain, Index::cursor::id(), and Index::cursor::plugBase().
for_each() [7/54]
template<class T , class C , unsigned D> bool for_each (const PETE_Scalar< T > & , const PlugBase< D > & , C) inline
Definition at line 112 of file AssignDefs.h.
for_each() [8/54]
template<class T , class C , unsigned int D> bool for_each (const IndexedBareFieldIterator< T, D > & p, IsCompressed , C) inline
Definition at line 125 of file AssignDefs.h.
References BareFieldIterator< T, Dim >::IsCompressed().
for_each() [9/54]
template<class T , class C , unsigned int D> bool for_each (const BareFieldIterator< T, D > & p, IsCompressed , C) inline
Definition at line 132 of file AssignDefs.h.
References BareFieldIterator< T, Dim >::IsCompressed().
for_each() [10/54]
template<class C > bool for_each (const Index::cursor & , IsCompressed , C) inline
Definition at line 142 of file AssignDefs.h.
for_each() [11/54]
template<class T , class C > bool for_each (const PETE_Scalar< T > & , IsCompressed , C) inline
Definition at line 152 of file AssignDefs.h.
for_each() [12/54]
template<class T , unsigned int D> T& for_each (const BrickIterator< T, D > & p, EvalFunctor_0) inline
Definition at line 166 of file AssignDefs.h.
for_each() [13/54]
int for_each (const Index::cursor & p, EvalFunctor_0) inline
Definition at line 175 of file AssignDefs.h.
for_each() [14/54]
template<class T , unsigned int D> T& for_each (const BrickIterator< T, D > & p, const EvalFunctor_1 & e) inline
Definition at line 189 of file AssignDefs.h.
References Physics::e, and BrickIterator< T, Dim >::offset().
for_each() [15/54]
template<class T , unsigned int D> T& for_each (const BrickIterator< T, D > & p, const UnitEvalFunctor_1 & e) inline
Definition at line 196 of file AssignDefs.h.
References Physics::e, and BrickIterator< T, Dim >::unit_offset().
for_each() [16/54]
int for_each (const Index::cursor & p, const EvalFunctor_1 & e) inline
Definition at line 205 of file AssignDefs.h.
References Physics::e, and Index::cursor::offset().
for_each() [17/54]
template<class T > T for_each (const PETE_Scalar< T > & p, const EvalFunctor_1 &) inline
Definition at line 215 of file AssignDefs.h.
References Attrib::Legacy::Distribution::T.
for_each() [18/54]
template<class T , unsigned int D> T& for_each (const BrickIterator< T, D > & p, const EvalFunctor_2 & e) inline
Definition at line 229 of file AssignDefs.h.
References Physics::e, and BrickIterator< T, Dim >::offset().
for_each() [19/54]
template<class T , unsigned int D> T& for_each (const BrickIterator< T, D > & p, const UnitEvalFunctor_2 & e) inline
Definition at line 236 of file AssignDefs.h.
References Physics::e, and BrickIterator< T, Dim >::unit_offset().
for_each() [20/54]
int for_each (const Index::cursor & p, const EvalFunctor_2 & e) inline
Definition at line 245 of file AssignDefs.h.
References Physics::e, and Index::cursor::offset().
for_each() [21/54]
template<class T > T for_each (const PETE_Scalar< T > & p, const EvalFunctor_2 &) inline
Definition at line 255 of file AssignDefs.h.
References Attrib::Legacy::Distribution::T.
for_each() [22/54]
template<class T , unsigned int D> T& for_each (const BrickIterator< T, D > & p, const EvalFunctor_3 & e) inline
Definition at line 269 of file AssignDefs.h.
References Physics::e, and BrickIterator< T, Dim >::offset().
for_each() [23/54]
template<class T , unsigned int D> T& for_each (const BrickIterator< T, D > & p, const UnitEvalFunctor_3 & e) inline
Definition at line 276 of file AssignDefs.h.
References Physics::e, and BrickIterator< T, Dim >::offset().
for_each() [24/54]
int for_each (const Index::cursor & p, const EvalFunctor_3 & e) inline
Definition at line 285 of file AssignDefs.h.
References Physics::e, and Index::cursor::offset().
for_each() [25/54]
template<class T > T for_each (const PETE_Scalar< T > & p, const EvalFunctor_3 &) inline
Definition at line 295 of file AssignDefs.h.
References Attrib::Legacy::Distribution::T.
for_each() [26/54]
template<class T , class C , unsigned int D> int for_each (BareFieldIterator< T, D > & p, BeginLField , C) inline
Definition at line 308 of file AssignDefs.h.
References BareFieldIterator< T, Dim >::beginLField().
for_each() [27/54]
template<class T , class C > int for_each (PETE_Scalar< T > & , BeginLField , C) inline
Definition at line 319 of file AssignDefs.h.
for_each() [28/54]
template<class T , class C , unsigned int D> int for_each (BareFieldIterator< T, D > & p, NextLField , C) inline
Definition at line 332 of file AssignDefs.h.
References BareFieldIterator< T, Dim >::nextLField().
for_each() [29/54]
template<class T , class C > int for_each (PETE_Scalar< T > & , NextLField , C) inline
Definition at line 343 of file AssignDefs.h.
for_each() [30/54]
template<class T , class C , unsigned int D> int for_each (IndexedBareFieldIterator< T, D > & p, StepFunctor s, C) inline
Definition at line 356 of file AssignDefs.h.
References StepFunctor::D, and BrickIterator< T, Dim >::step().
for_each() [31/54]
template<class T , class C , unsigned int D> int for_each (BareFieldIterator< T, D > & p, StepFunctor s, C) inline
Definition at line 364 of file AssignDefs.h.
References StepFunctor::D, and BrickIterator< T, Dim >::step().
for_each() [32/54]
template<class T , class C , unsigned int D> int for_each (BrickIterator< T, D > & p, StepFunctor s, C) inline
Definition at line 372 of file AssignDefs.h.
References StepFunctor::D, and BrickIterator< T, Dim >::step().
for_each() [33/54]
template<class C > int for_each (Index::cursor & p, StepFunctor s, C) inline
Definition at line 383 of file AssignDefs.h.
References StepFunctor::D, and Index::cursor::step().
for_each() [34/54]
template<class T , class C > int for_each (PETE_Scalar< T > & , StepFunctor , C) inline
Definition at line 394 of file AssignDefs.h.
for_each() [35/54]
template<class T , class C , unsigned int D> int for_each (IndexedBareFieldIterator< T, D > & p, RewindFunctor s, C) inline
Definition at line 407 of file AssignDefs.h.
References RewindFunctor::D, and BrickIterator< T, Dim >::rewind().
for_each() [36/54]
template<class T , class C , unsigned int D> int for_each (BareFieldIterator< T, D > & p, RewindFunctor s, C) inline
Definition at line 416 of file AssignDefs.h.
References RewindFunctor::D, and BrickIterator< T, Dim >::rewind().
for_each() [37/54]
template<class T , class C , unsigned int D> int for_each (BrickIterator< T, D > & p, RewindFunctor s, C) inline
Definition at line 425 of file AssignDefs.h.
References RewindFunctor::D, and BrickIterator< T, Dim >::rewind().
for_each() [38/54]
template<class C > int for_each (Index::cursor & p, RewindFunctor s, C) inline
Definition at line 436 of file AssignDefs.h.
References RewindFunctor::D, and Index::cursor::rewind().
for_each() [39/54]
template<class T , class C > int for_each (PETE_Scalar< T > & , RewindFunctor , C) inline
Definition at line 447 of file AssignDefs.h.
for_each() [40/54]
template<class T , class C , unsigned int D> int for_each (BrickIterator< T, D > & p, PETE_CountElems , C) inline
Definition at line 460 of file AssignDefs.h.
References BrickCounter< Dim >::size().
for_each() [41/54]
template<class T , class C , unsigned int D> int for_each (BareFieldIterator< T, D > & p, PETE_CountElems , C) inline
Definition at line 470 of file AssignDefs.h.
References BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), BareFieldIterator< T, Dim >::GetBareField(), and Hypervolume::n.
for_each() [42/54]
template<class T , class C , unsigned int D> int for_each (IndexedBareFieldIterator< T, D > & p, PETE_CountElems , C) inline
Definition at line 481 of file AssignDefs.h.
References BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), BareFieldIterator< T, Dim >::GetBareField(), IndexedBareFieldIterator< T, Dim >::getDomain(), and Hypervolume::n.
for_each() [43/54]
template<class T , class C , unsigned int D> int for_each (IndexedBareFieldIterator< T, D > & p, PETE_Increment , C) inline
Definition at line 501 of file AssignDefs.h.
for_each() [44/54]
template<class T , class C , unsigned int D> int for_each (BareFieldIterator< T, D > & p, PETE_Increment , C) inline
Definition at line 510 of file AssignDefs.h.
for_each() [45/54]
template<class T , class C , unsigned int D> int for_each (BrickIterator< T, D > & p, PETE_Increment , C) inline
Definition at line 519 of file AssignDefs.h.
for_each() [46/54]
template<class T , class C , unsigned int D> bool for_each (const IndexedBareFieldIterator< T, D > & iter, HasUnitStride , C) inline
Definition at line 534 of file AssignDefs.h.
References BrickIterator< T, Dim >::Stride().
for_each() [47/54]
template<class T , class C , unsigned int D> bool for_each (const BareFieldIterator< T, D > & iter, HasUnitStride , C) inline
Definition at line 541 of file AssignDefs.h.
References BrickIterator< T, Dim >::Stride().
for_each() [48/54]
template<class T , class C , unsigned int D> bool for_each (const BrickIterator< T, D > & iter, HasUnitStride , C) inline
Definition at line 548 of file AssignDefs.h.
References BrickIterator< T, Dim >::Stride().
for_each() [49/54]
template<class C > bool for_each (const Index::cursor & , HasUnitStride , C) inline
Definition at line 555 of file AssignDefs.h.
for_each() [50/54]
template<class T , class C > bool for_each (const PETE_Scalar< T > & , HasUnitStride , C) inline
Definition at line 562 of file AssignDefs.h.
for_each() [51/54]
template<class T , class C , unsigned int D, unsigned int D1, class T1 > int for_each (const IndexedBareFieldIterator< T, D > & p, const FillGCIfNecessaryTag< D1, T1 > & f, C) inline
Definition at line 575 of file AssignDefs.h.
References FillGCIfNecessaryTag< D, T1 >::bf_m, and IndexedBareFieldIterator< T, Dim >::FillGCIfNecessary().
for_each() [52/54]
template<class T , class C , unsigned int D, unsigned int D1, class T1 > int for_each (const BareFieldIterator< T, D > & , const FillGCIfNecessaryTag< D1, T1 > & , C) inline
Definition at line 584 of file AssignDefs.h.
for_each() [53/54]
template<class T , class C , unsigned int D, class T1 > int for_each (const PETE_Scalar< T > & , const FillGCIfNecessaryTag< D, T1 > & , C) inline
Definition at line 592 of file AssignDefs.h.
for_each() [54/54]
template<class C , unsigned int D, class T1 > int for_each (const Index::cursor & , const FillGCIfNecessaryTag< D, T1 > & , C) inline
Definition at line 599 of file AssignDefs.h.