OPAL (Object Oriented Parallel Accelerator Library): ParticleAttribDataSource Class Reference
ParticleAttribDataSource Class Reference abstract
#include <PtclAttribDataSource.h>
Public Member Functions
ParticleAttribDataSource (const char *, DataConnect *, int, ParticleAttribBase *, DataSource *)
virtual ~ParticleAttribDataSource ()
void setDisconnected ()
virtual void * getConnectStorage ()
virtual void putMessage (Message *)=0
virtual void prepare_data (bool, unsigned)=0
virtual void insert_data (unsigned, unsigned, Message *)=0
Public Member Functions inherited from DataSourceObject
DataSourceObject (const char *nm, DataSource *ds, DataConnect *dc, int tm)
DataSourceObject ()
virtual ~DataSourceObject ()
bool connected () const
DataConnect * getConnection ()
DataSource * getSource ()
virtual bool update ()
virtual void interact (const char *=0)
Public Member Functions inherited from NamedObj
NamedObj (const char *nm=0)
virtual ~NamedObj ()
const char * name () const
const char * setName (const char *nm=0)
Protected Attributes
IpplParticleBaseDataSource * PBase
Protected Attributes inherited from DataSourceObject
DataConnect * Connection
DataSource * Source
int TransferMethod
Detailed Description
Definition at line 38 of file PtclAttribDataSource.h.
Constructor & Destructor Documentation
ParticleAttribDataSource()
ParticleAttribDataSource::ParticleAttribDataSource (const char * nm, DataConnect * dc, int tm, ParticleAttribBase * pa, DataSource * ds)
Definition at line 32 of file PtclAttribDataSource.cpp.
References IpplParticleBaseDataSource::find_particle_base(), NamedObj::name(), PBase, and NamedObj::setName().
~ParticleAttribDataSource()
ParticleAttribDataSource::~ParticleAttribDataSource () virtual
Definition at line 53 of file PtclAttribDataSource.cpp.
Member Function Documentation
getConnectStorage()
virtual void* ParticleAttribDataSource::getConnectStorage () inline virtual
Definition at line 56 of file PtclAttribDataSource.h.
insert_data()
virtual void ParticleAttribDataSource::insert_data (unsigned , unsigned , Message *) pure virtual
prepare_data()
virtual void ParticleAttribDataSource::prepare_data (bool , unsigned) pure virtual
putMessage()
virtual void ParticleAttribDataSource::putMessage (Message *) pure virtual
setDisconnected()
void ParticleAttribDataSource::setDisconnected () inline
Definition at line 49 of file PtclAttribDataSource.h.
References PBase.
Referenced by IpplParticleBaseDataSource::disconnect_attrib().
Member Data Documentation
PBase
IpplParticleBaseDataSource* ParticleAttribDataSource::PBase protected
Definition at line 77 of file PtclAttribDataSource.h.
Referenced by ParticleAttribDataSource(), and setDisconnected().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/PtclAttribDataSource.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/PtclAttribDataSource.cpp