OPAL (Object Oriented Parallel Accelerator Library): FlexibleCollimatorRep Class Reference
FlexibleCollimatorRep Class Reference
#include <FlexibleCollimatorRep.h>
Public Member Functions
FlexibleCollimatorRep (const std::string &name)
Constructor with given name.
FlexibleCollimatorRep ()
FlexibleCollimatorRep (const FlexibleCollimatorRep &)
virtual ~FlexibleCollimatorRep ()
virtual ElementBase * clone () const
Return clone.
virtual Channel * getChannel (const std::string &aKey, bool=false)
Construct a read/write channel.
virtual NullField & getField ()
Get field.
virtual const NullField & getField () const
Get field.
virtual StraightGeometry & getGeometry ()
Get geometry.
virtual const StraightGeometry & getGeometry () const
Get geometry.
Public Member Functions inherited from FlexibleCollimator
FlexibleCollimator (const std::string &name)
Constructor with given name.
FlexibleCollimator ()
FlexibleCollimator (const FlexibleCollimator &rhs)
virtual ~FlexibleCollimator ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to FlexibleCollimator.
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual bool checkCollimator (PartBunchBase< double, 3 > *bunch, const int turnnumber, const double t, const double tstep)
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void initialise (PartBunchBase< double, 3 > *bunch)
virtual void finalise () override
virtual bool bends () const override
virtual void goOnline (const double &kineticEnergy) override
virtual void goOffline () override
virtual ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
void print ()
unsigned int getLosses () const
void setDescription (const std::string &desc)
std::string getDescription () const
bool isStopped (const Vector_t &R)
void writeHolesAndQuadtree (const std::string &baseFilename) const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void operator= (const FlexibleCollimatorRep &)
Private Attributes
NullField field
StraightGeometry geometry
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 26 of file FlexibleCollimatorRep.h.
Constructor & Destructor Documentation
FlexibleCollimatorRep() [1/3]
FlexibleCollimatorRep::FlexibleCollimatorRep (const std::string & name) explicit
Constructor with given name.
Definition at line 51 of file FlexibleCollimatorRep.cpp.
FlexibleCollimatorRep() [2/3]
FlexibleCollimatorRep::FlexibleCollimatorRep ()
Definition at line 39 of file FlexibleCollimatorRep.cpp.
Referenced by clone().
FlexibleCollimatorRep() [3/3]
FlexibleCollimatorRep::FlexibleCollimatorRep (const FlexibleCollimatorRep & right)
Definition at line 45 of file FlexibleCollimatorRep.cpp.
~FlexibleCollimatorRep()
FlexibleCollimatorRep::~FlexibleCollimatorRep () virtual
Definition at line 57 of file FlexibleCollimatorRep.cpp.
Member Function Documentation
clone()
ElementBase * FlexibleCollimatorRep::clone () const virtual
Return clone.
Implements ElementBase.
Definition at line 61 of file FlexibleCollimatorRep.cpp.
References FlexibleCollimatorRep().
getChannel()
Channel * FlexibleCollimatorRep::getChannel (const std::string & aKey, bool create = false) virtual
Construct a read/write channel.
Reimplemented from ElementBase.
Definition at line 66 of file FlexibleCollimatorRep.cpp.
References ElementBase::getChannel().
getField() [1/2]
NullField & FlexibleCollimatorRep::getField () virtual
Get field.
Implements Component.
Definition at line 77 of file FlexibleCollimatorRep.cpp.
References field.
getField() [2/2]
const NullField & FlexibleCollimatorRep::getField () const virtual
Get field.
Implements Component.
Definition at line 81 of file FlexibleCollimatorRep.cpp.
References field.
getGeometry() [1/2]
StraightGeometry & FlexibleCollimatorRep::getGeometry () virtual
Get geometry.
Implements ElementBase.
Definition at line 86 of file FlexibleCollimatorRep.cpp.
References geometry.
getGeometry() [2/2]
const StraightGeometry & FlexibleCollimatorRep::getGeometry () const virtual
Get geometry.
Implements ElementBase.
Definition at line 90 of file FlexibleCollimatorRep.cpp.
References geometry.
operator=()
void FlexibleCollimatorRep::operator= (const FlexibleCollimatorRep &) private
Member Data Documentation
field
NullField FlexibleCollimatorRep::field private
Definition at line 82 of file FlexibleCollimatorRep.h.
Referenced by getField().
geometry
StraightGeometry FlexibleCollimatorRep::geometry private
Definition at line 85 of file FlexibleCollimatorRep.h.
Referenced by getGeometry().
The documentation for this class was generated from the following files:
src/Classic/BeamlineCore/FlexibleCollimatorRep.h
src/Classic/BeamlineCore/FlexibleCollimatorRep.cpp