OPAL (Object Oriented Parallel Accelerator Library): QRDecomposition Namespace Reference
QRDecomposition Namespace Reference
Functions
void solve (double *Matrix, double *Solution, double *rightHandSide, const int &M, const int &N)
Function Documentation
solve()
void QRDecomposition::solve (double * Matrix, double * Solution, double * rightHandSide, const int & M, const int & N)
Definition at line 367 of file FM1DProfile2.cpp.
References Attrib::Distribution::R, and sqrt().
Referenced by PySquarePolynomialMap::exact_solve(), and _FM1DProfile2::readMap().