OPAL (Object Oriented Parallel Accelerator Library): SDDS::parser::associate_parser< Iterator > Struct Template Reference
SDDS::parser::associate_parser< Iterator > Struct Template Reference
#include <associate.hpp>
Inherits grammar< Iterator, associate(), skipper< Iterator > >.
Public Member Functions
associate_parser (error_handler< Iterator > &_error_handler)
Public Attributes
qi::rule< Iterator, associate(), skipper< Iterator > > start
qi::rule< Iterator, std::string(), skipper< Iterator > > string
qi::rule< Iterator, std::string(), skipper< Iterator > > quoted_string
qi::rule< Iterator, std::string(), skipper< Iterator > > associate_name
qi::rule< Iterator, std::string(), skipper< Iterator > > associate_filename
qi::rule< Iterator, std::string(), skipper< Iterator > > associate_path
qi::rule< Iterator, std::string(), skipper< Iterator > > associate_description
qi::rule< Iterator, std::string(), skipper< Iterator > > associate_contents
qi::rule< Iterator, long(), skipper< Iterator > > associate_sdds
qi::rule< Iterator, ast::nil(), skipper< Iterator > > associate_unsupported_pre
qi::rule< Iterator, ast::nil(), skipper< Iterator > > associate_unsupported_post
Detailed Description
template<typename Iterator>
struct SDDS::parser::associate_parser< Iterator >
Definition at line 101 of file associate.hpp.
Constructor & Destructor Documentation
associate_parser()
template<typename Iterator > SDDS::parser::associate_parser< Iterator >::associate_parser (error_handler< Iterator > & _error_handler)
Definition at line 30 of file associate_def.hpp.
References Physics::alpha, SDDS::parser::associate_parser< Iterator >::associate_contents, SDDS::parser::associate_parser< Iterator >::associate_description, SDDS::parser::associate_parser< Iterator >::associate_filename, SDDS::parser::associate_parser< Iterator >::associate_name, SDDS::parser::associate_parser< Iterator >::associate_path, SDDS::parser::associate_parser< Iterator >::associate_sdds, SDDS::parser::associate_parser< Iterator >::associate_unsupported_post, SDDS::parser::associate_parser< Iterator >::associate_unsupported_pre, SDDS::parser::associate_parser< Iterator >::quoted_string, SDDS::parser::associate_parser< Iterator >::start, and SDDS::parser::associate_parser< Iterator >::string.
Member Data Documentation
associate_contents
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::associate_parser< Iterator >::associate_contents
Definition at line 106 of file associate.hpp.
Referenced by SDDS::parser::associate_parser< Iterator >::associate_parser().
associate_description
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::associate_parser< Iterator >::associate_description
Definition at line 106 of file associate.hpp.
Referenced by SDDS::parser::associate_parser< Iterator >::associate_parser().
associate_filename
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::associate_parser< Iterator >::associate_filename
Definition at line 106 of file associate.hpp.
Referenced by SDDS::parser::associate_parser< Iterator >::associate_parser().
associate_name
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::associate_parser< Iterator >::associate_name
Definition at line 106 of file associate.hpp.
Referenced by SDDS::parser::associate_parser< Iterator >::associate_parser().
associate_path
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::associate_parser< Iterator >::associate_path
Definition at line 106 of file associate.hpp.
Referenced by SDDS::parser::associate_parser< Iterator >::associate_parser().
associate_sdds
template<typename Iterator > qi::rule<Iterator, long(), skipper<Iterator> > SDDS::parser::associate_parser< Iterator >::associate_sdds
Definition at line 109 of file associate.hpp.
Referenced by SDDS::parser::associate_parser< Iterator >::associate_parser().
associate_unsupported_post
template<typename Iterator > qi::rule<Iterator, ast::nil(), skipper<Iterator> > SDDS::parser::associate_parser< Iterator >::associate_unsupported_post
Definition at line 110 of file associate.hpp.
Referenced by SDDS::parser::associate_parser< Iterator >::associate_parser().
associate_unsupported_pre
template<typename Iterator > qi::rule<Iterator, ast::nil(), skipper<Iterator> > SDDS::parser::associate_parser< Iterator >::associate_unsupported_pre
Definition at line 110 of file associate.hpp.
Referenced by SDDS::parser::associate_parser< Iterator >::associate_parser().
quoted_string
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::associate_parser< Iterator >::quoted_string
Definition at line 106 of file associate.hpp.
Referenced by SDDS::parser::associate_parser< Iterator >::associate_parser().
start
template<typename Iterator > qi::rule<Iterator, associate(), skipper<Iterator> > SDDS::parser::associate_parser< Iterator >::start
Definition at line 105 of file associate.hpp.
Referenced by SDDS::parser::associate_parser< Iterator >::associate_parser().
string
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::associate_parser< Iterator >::string
Definition at line 106 of file associate.hpp.
Referenced by SDDS::parser::associate_parser< Iterator >::associate_parser().
The documentation for this struct was generated from the following files:
optimizer/Util/SDDSParser/associate.hpp
optimizer/Util/SDDSParser/associate_def.hpp