OPAL (Object Oriented Parallel Accelerator Library): FileDataConnect Class Reference
FileDataConnect Class Reference
#include <FileDataConnect.h>
Public Member Functions
FileDataConnect (const char *nm, unsigned int numobjs=1, const char *ts=0, int n=0)
virtual ~FileDataConnect ()
unsigned int getNumObjects () const
const char * getTypeString () const
virtual bool connected () const
Public Member Functions inherited from DataConnect
DataConnect (const char *nm, const char *id, int dtm=DataSource::OUTPUT, int n=0)
virtual ~DataConnect ()
const char * DSID () const
int getDefaultTransferMethod () const
void setDefaultTransferMethod (int m)
int getNodes () const
bool onConnectNode () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
unsigned int size () const
unsigned int numDataSources () const
bool empty () const
virtual DataConnect * connect (const char *, DataSource *, int=DataSource::DEFAULT)
virtual DataConnect * connect (const char *, DataSource &, int=DataSource::DEFAULT)
virtual bool connect (DataSourceObject *)
virtual void updateConnections (DataConnect *=0)
virtual void disconnectConnections ()
virtual void interact (const char *=0, DataConnect *=0)
virtual void ready ()
Public Member Functions inherited from NamedObj
NamedObj (const char *nm=0)
virtual ~NamedObj ()
const char * name () const
const char * setName (const char *nm=0)
Private Attributes
unsigned int NumObjects
std::string TypeString
Additional Inherited Members
Public Types inherited from DataConnect
typedef std::vector< DataSource * > container_t
typedef container_t::iterator iterator
typedef container_t::const_iterator const_iterator
Detailed Description
Definition at line 25 of file FileDataConnect.h.
Constructor & Destructor Documentation
FileDataConnect()
FileDataConnect::FileDataConnect (const char * nm, unsigned int numobjs = 1, const char * ts = 0, int n = 0) inline
Definition at line 29 of file FileDataConnect.h.
References TypeString.
~FileDataConnect()
virtual FileDataConnect::~FileDataConnect () inline virtual
Definition at line 39 of file FileDataConnect.h.
Member Function Documentation
connected()
virtual bool FileDataConnect::connected () const inline virtual
Reimplemented from DataConnect.
Definition at line 56 of file FileDataConnect.h.
getNumObjects()
unsigned int FileDataConnect::getNumObjects () const inline
Definition at line 46 of file FileDataConnect.h.
References NumObjects.
Referenced by FileFieldDataSource< T, Dim, M, C >::FileFieldDataSource().
getTypeString()
const char* FileDataConnect::getTypeString () const inline
Definition at line 49 of file FileDataConnect.h.
References TypeString.
Referenced by FileFieldDataSource< T, Dim, M, C >::FileFieldDataSource(), FileIpplParticleBaseDataSource< T >::FileIpplParticleBaseDataSource(), and FileParticleAttribDataSource< T >::FileParticleAttribDataSource().
Member Data Documentation
NumObjects
unsigned int FileDataConnect::NumObjects private
Definition at line 60 of file FileDataConnect.h.
Referenced by getNumObjects().
TypeString
std::string FileDataConnect::TypeString private
Definition at line 61 of file FileDataConnect.h.
Referenced by FileDataConnect(), and getTypeString().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/FileDataConnect.h