OPAL (Object Oriented Parallel Accelerator Library): Random Class Reference
Random Class Reference
The CLASSIC random generator.
#include <ClassicRandom.h>
Public Member Functions
Random ()
Constructor with default seed.
Random (int seed)
Constructor with given seed.
~Random ()
void reseed (int seed=123456789)
Set a new seed.
double uniform ()
Uniform distribution.
void gauss (double &gr1, double &gr2)
Gaussian distribution.
int integer ()
Uniform distribution.
void init55 (int seed)
Initialise random number generator.
Private Member Functions
void irngen ()
Private Attributes
int irn [nr]
int next
Detailed Description
The CLASSIC random generator.
Definition at line 36 of file ClassicRandom.h.
Constructor & Destructor Documentation
Random() [1/2]
Random::Random ()
Constructor with default seed.
Definition at line 28 of file ClassicRandom.cpp.
References init55().
Random() [2/2]
Random::Random (int seed)
Constructor with given seed.
Definition at line 37 of file ClassicRandom.cpp.
References init55(), and Options::seed.
~Random()
Random::~Random ()
Definition at line 43 of file ClassicRandom.cpp.
Member Function Documentation
gauss()
void Random::gauss (double & gr1, double & gr2)
Gaussian distribution.
Definition at line 64 of file ClassicRandom.cpp.
References log(), sqrt(), and uniform().
Referenced by Expressions::gauss(), and Expressions::Tgauss().
init55()
void Random::init55 (int seed)
Initialise random number generator.
Definition at line 91 of file ClassicRandom.cpp.
References next, and Options::seed.
Referenced by Option::execute(), Random(), and reseed().
integer()
int Random::integer ()
Uniform distribution.
Definition at line 83 of file ClassicRandom.cpp.
References irn, irngen(), next, and nr.
irngen()
void Random::irngen () private
Definition at line 122 of file ClassicRandom.cpp.
References irn, and nr.
Referenced by integer().
reseed()
void Random::reseed (int seed = 123456789)
Set a new seed.
Definition at line 48 of file ClassicRandom.cpp.
References init55(), and Options::seed.
uniform()
double Random::uniform ()
Uniform distribution.
Definition at line 54 of file ClassicRandom.cpp.
Referenced by gauss(), and Expressions::ranf().
Member Data Documentation
irn
int Random::irn[nr] private
Definition at line 75 of file ClassicRandom.h.
Referenced by integer(), and irngen().
next
int Random::next private
Definition at line 78 of file ClassicRandom.h.
Referenced by init55(), and integer().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/ClassicRandom.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/ClassicRandom.cpp