OPAL (Object Oriented Parallel Accelerator Library): vmap< Key, T, Compare > Class Template Reference
vmap< Key, T, Compare > Class Template Reference
#include <vmap.h>
Classes
class value_compare
Public Types
typedef Key key_type
typedef std::pair< Key, T > value_type
typedef Compare key_compare
typedef rep_type::reference reference
typedef rep_type::const_reference const_reference
typedef rep_type::iterator iterator
typedef rep_type::const_iterator const_iterator
typedef rep_type::reverse_iterator reverse_iterator
typedef rep_type::const_reverse_iterator const_reverse_iterator
typedef rep_type::size_type size_type
typedef rep_type::difference_type difference_type
Public Member Functions
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
key_compare key_comp () const
value_compare value_comp () const
bool empty () const
size_type size () const
size_type max_size () const
size_type capacity () const
void swap (vmap< Key, T, Compare > &x)
void reserve (size_type n)
vmap (const Compare &comp=Compare())
vmap (const vmap< Key, T, Compare > &x)
vmap< Key, T, Compare > & operator= (const vmap< Key, T, Compare > &x)
std::pair< iterator, bool > insert (const value_type &x)
iterator insert (iterator hint_i, const value_type &x)
void insert (const value_type *first, const value_type *last)
void erase (iterator position_i)
void erase (iterator first_i, iterator last_i)
size_type erase (const key_type &x)
T & operator[] (const key_type &k)
iterator find (const key_type &x)
iterator lower_bound (const key_type &x)
iterator upper_bound (const key_type &x)
std::pair< iterator, iterator > equal_range (const key_type &x)
size_type count (const key_type &x) const
const T & operator[] (const key_type &k) const
const_iterator find (const key_type &x) const
const_iterator lower_bound (const key_type &x) const
const_iterator upper_bound (const key_type &x) const
std::pair< const_iterator, const_iterator > equal_range (const key_type &x) const
Private Types
typedef std::vector< value_type > rep_type
Private Member Functions
bool Gt (const key_type &a, const key_type &b) const
bool Ge (const key_type &a, const key_type &b) const
bool Le (const key_type &a, const key_type &b) const
Private Attributes
rep_type V_c
Compare Lt
Detailed Description
template<class Key, class T, class Compare = dummy_less<Key>>
class vmap< Key, T, Compare >
Definition at line 58 of file vmap.h.
Member Typedef Documentation
const_iterator
template<class Key, class T, class Compare = dummy_less<Key>> typedef rep_type::const_iterator vmap< Key, T, Compare >::const_iterator
Definition at line 99 of file vmap.h.
const_reference
template<class Key, class T, class Compare = dummy_less<Key>> typedef rep_type::const_reference vmap< Key, T, Compare >::const_reference
Definition at line 97 of file vmap.h.
const_reverse_iterator
template<class Key, class T, class Compare = dummy_less<Key>> typedef rep_type::const_reverse_iterator vmap< Key, T, Compare >::const_reverse_iterator
Definition at line 101 of file vmap.h.
difference_type
template<class Key, class T, class Compare = dummy_less<Key>> typedef rep_type::difference_type vmap< Key, T, Compare >::difference_type
Definition at line 103 of file vmap.h.
iterator
template<class Key, class T, class Compare = dummy_less<Key>> typedef rep_type::iterator vmap< Key, T, Compare >::iterator
Definition at line 98 of file vmap.h.
key_compare
template<class Key, class T, class Compare = dummy_less<Key>> typedef Compare vmap< Key, T, Compare >::key_compare
Definition at line 65 of file vmap.h.
key_type
template<class Key, class T, class Compare = dummy_less<Key>> typedef Key vmap< Key, T, Compare >::key_type
Definition at line 63 of file vmap.h.
reference
template<class Key, class T, class Compare = dummy_less<Key>> typedef rep_type::reference vmap< Key, T, Compare >::reference
Definition at line 96 of file vmap.h.
rep_type
template<class Key, class T, class Compare = dummy_less<Key>> typedef std::vector< value_type > vmap< Key, T, Compare >::rep_type private
Definition at line 80 of file vmap.h.
reverse_iterator
template<class Key, class T, class Compare = dummy_less<Key>> typedef rep_type::reverse_iterator vmap< Key, T, Compare >::reverse_iterator
Definition at line 100 of file vmap.h.
size_type
template<class Key, class T, class Compare = dummy_less<Key>> typedef rep_type::size_type vmap< Key, T, Compare >::size_type
Definition at line 102 of file vmap.h.
value_type
template<class Key, class T, class Compare = dummy_less<Key>> typedef std::pair<Key, T> vmap< Key, T, Compare >::value_type
Definition at line 64 of file vmap.h.
Constructor & Destructor Documentation
vmap() [1/2]
template<class Key, class T, class Compare = dummy_less<Key>> vmap< Key, T, Compare >::vmap (const Compare & comp = Compare()) inline
Definition at line 129 of file vmap.h.
vmap() [2/2]
template<class Key, class T, class Compare> vmap< Key, T, Compare >::vmap (const vmap< Key, T, Compare > & x)
Definition at line 36 of file vmap.hpp.
Member Function Documentation
begin() [1/2]
template<class Key, class T, class Compare = dummy_less<Key>> iterator vmap< Key, T, Compare >::begin () inline
Definition at line 107 of file vmap.h.
Referenced by DiscMeta::begin(), Field< Vector_t, 3, Mesh_t, Center_t >::begin_BConds(), BareField< T1, D >::begin_if(), RegionLayout< T, Dim, Mesh >::begin_iv(), and UserList::begin_user().
begin() [2/2]
template<class Key, class T, class Compare = dummy_less<Key>> const_iterator vmap< Key, T, Compare >::begin () const inline
Definition at line 112 of file vmap.h.
capacity()
template<class Key, class T, class Compare = dummy_less<Key>> size_type vmap< Key, T, Compare >::capacity () const inline
Definition at line 122 of file vmap.h.
count()
template<class Key , class T , class Compare > vmap< Key, T, Compare >::size_type vmap< Key, T, Compare >::count (const key_type & x) const
Definition at line 313 of file vmap.hpp.
Referenced by UserList::haveUser().
empty()
template<class Key, class T, class Compare = dummy_less<Key>> bool vmap< Key, T, Compare >::empty () const inline
Definition at line 119 of file vmap.h.
end() [1/2]
template<class Key, class T, class Compare = dummy_less<Key>> iterator vmap< Key, T, Compare >::end () inline
Definition at line 108 of file vmap.h.
Referenced by BareField< T1, D >::BareField(), DiscMeta::end(), Field< Vector_t, 3, Mesh_t, Center_t >::end_BConds(), BareField< T1, D >::end_if(), RegionLayout< T, Dim, Mesh >::end_iv(), UserList::end_user(), and IpplInfo::find_smp_nodes().
end() [2/2]
template<class Key, class T, class Compare = dummy_less<Key>> const_iterator vmap< Key, T, Compare >::end () const inline
Definition at line 113 of file vmap.h.
equal_range() [1/2]
template<class Key , class T , class Compare > std::pair< typename vmap< Key, T, Compare >::iterator, typename vmap< Key, T, Compare >::iterator > vmap< Key, T, Compare >::equal_range (const key_type & x)
Definition at line 265 of file vmap.hpp.
equal_range() [2/2]
template<class Key , class T , class Compare > std::pair< typename vmap< Key, T, Compare >::const_iterator, typename vmap< Key, T, Compare >::const_iterator > vmap< Key, T, Compare >::equal_range (const key_type & x) const
Definition at line 378 of file vmap.hpp.
erase() [1/3]
template<class Key , class T , class Compare > void vmap< Key, T, Compare >::erase (iterator position_i)
Definition at line 165 of file vmap.hpp.
Referenced by UserList::checkoutUser().
erase() [2/3]
template<class Key , class T , class Compare > void vmap< Key, T, Compare >::erase (iterator first_i, iterator last_i)
Definition at line 178 of file vmap.hpp.
erase() [3/3]
template<class Key , class T , class Compare > vmap< Key, T, Compare >::size_type vmap< Key, T, Compare >::erase (const key_type & x)
Definition at line 192 of file vmap.hpp.
find() [1/2]
template<class Key , class T , class Compare > vmap< Key, T, Compare >::iterator vmap< Key, T, Compare >::find (const key_type & x)
Definition at line 214 of file vmap.hpp.
Referenced by UserList::checkoutUser(), IpplInfo::find_smp_nodes(), and UserList::getUser().
find() [2/2]
template<class Key , class T , class Compare > vmap< Key, T, Compare >::const_iterator vmap< Key, T, Compare >::find (const key_type & x) const
Definition at line 329 of file vmap.hpp.
Ge()
template<class Key, class T, class Compare = dummy_less<Key>> bool vmap< Key, T, Compare >::Ge (const key_type & a, const key_type & b) const inline private
Definition at line 88 of file vmap.h.
Gt()
template<class Key, class T, class Compare = dummy_less<Key>> bool vmap< Key, T, Compare >::Gt (const key_type & a, const key_type & b) const inline private
Definition at line 87 of file vmap.h.
insert() [1/3]
template<class Key , class T , class Compare > std::pair< typename vmap< Key, T, Compare >::iterator, bool > vmap< Key, T, Compare >::insert (const value_type & x)
Definition at line 73 of file vmap.hpp.
Referenced by BareField< T1, D >::BareField(), DiscMeta::DiscMeta(), FieldLayout< Dim >::FieldLayout(), and IpplInfo::find_smp_nodes().
insert() [2/3]
template<class Key , class T , class Compare > vmap< Key, T, Compare >::iterator vmap< Key, T, Compare >::insert (iterator hint_i, const value_type & x)
Definition at line 112 of file vmap.hpp.
insert() [3/3]
template<class Key , class T , class Compare > void vmap< Key, T, Compare >::insert (const value_type * first, const value_type * last)
Definition at line 145 of file vmap.hpp.
key_comp()
template<class Key, class T, class Compare = dummy_less<Key>> key_compare vmap< Key, T, Compare >::key_comp () const inline
Definition at line 117 of file vmap.h.
Le()
template<class Key, class T, class Compare = dummy_less<Key>> bool vmap< Key, T, Compare >::Le (const key_type & a, const key_type & b) const inline private
Definition at line 89 of file vmap.h.
lower_bound() [1/2]
template<class Key , class T , class Compare > vmap< Key, T, Compare >::iterator vmap< Key, T, Compare >::lower_bound (const key_type & x)
Definition at line 236 of file vmap.hpp.
lower_bound() [2/2]
template<class Key , class T , class Compare > vmap< Key, T, Compare >::const_iterator vmap< Key, T, Compare >::lower_bound (const key_type & x) const
Definition at line 349 of file vmap.hpp.
max_size()
template<class Key, class T, class Compare = dummy_less<Key>> size_type vmap< Key, T, Compare >::max_size () const inline
Definition at line 121 of file vmap.h.
operator=()
template<class Key, class T, class Compare> vmap< Key, T, Compare > & vmap< Key, T, Compare >::operator= (const vmap< Key, T, Compare > & x)
Definition at line 51 of file vmap.hpp.
operator[]() [1/2]
template<class Key , class T , class Compare > T & vmap< Key, T, Compare >::operator[] (const key_type & k)
Definition at line 278 of file vmap.hpp.
operator[]() [2/2]
template<class Key , class T , class Compare > const T & vmap< Key, T, Compare >::operator[] (const key_type & k) const
Definition at line 392 of file vmap.hpp.
rbegin() [1/2]
template<class Key, class T, class Compare = dummy_less<Key>> reverse_iterator vmap< Key, T, Compare >::rbegin () inline
Definition at line 109 of file vmap.h.
rbegin() [2/2]
template<class Key, class T, class Compare = dummy_less<Key>> const_reverse_iterator vmap< Key, T, Compare >::rbegin () const inline
Definition at line 114 of file vmap.h.
rend() [1/2]
template<class Key, class T, class Compare = dummy_less<Key>> reverse_iterator vmap< Key, T, Compare >::rend () inline
Definition at line 110 of file vmap.h.
rend() [2/2]
template<class Key, class T, class Compare = dummy_less<Key>> const_reverse_iterator vmap< Key, T, Compare >::rend () const inline
Definition at line 115 of file vmap.h.
reserve()
template<class Key, class T, class Compare = dummy_less<Key>> void vmap< Key, T, Compare >::reserve (size_type n) inline
Definition at line 125 of file vmap.h.
Referenced by BareField< T1, D >::BareField().
size()
template<class Key, class T, class Compare = dummy_less<Key>> size_type vmap< Key, T, Compare >::size (void) const inline
Definition at line 120 of file vmap.h.
Referenced by IpplInfo::find_smp_nodes(), UserList::getNumUsers(), operator==(), DiscMeta::size(), BareField< T1, D >::size_if(), RegionLayout< T, Dim, Mesh >::size_iv(), and DiscField< Dim >::write().
swap()
template<class Key, class T, class Compare = dummy_less<Key>> void vmap< Key, T, Compare >::swap (vmap< Key, T, Compare > & x) inline
Definition at line 124 of file vmap.h.
upper_bound() [1/2]
template<class Key , class T , class Compare > vmap< Key, T, Compare >::iterator vmap< Key, T, Compare >::upper_bound (const key_type & x)
Definition at line 251 of file vmap.hpp.
upper_bound() [2/2]
template<class Key , class T , class Compare > vmap< Key, T, Compare >::const_iterator vmap< Key, T, Compare >::upper_bound (const key_type & x) const
Definition at line 364 of file vmap.hpp.
value_comp()
template<class Key, class T, class Compare = dummy_less<Key>> value_compare vmap< Key, T, Compare >::value_comp () const inline
Definition at line 118 of file vmap.h.
Member Data Documentation
Lt
template<class Key, class T, class Compare = dummy_less<Key>> Compare vmap< Key, T, Compare >::Lt private
Definition at line 86 of file vmap.h.
Referenced by vmap< std::string, DiscConfig::SMPData *>::Ge(), vmap< std::string, DiscConfig::SMPData *>::Gt(), vmap< std::string, DiscConfig::SMPData *>::key_comp(), vmap< std::string, DiscConfig::SMPData *>::Le(), vmap< std::string, DiscConfig::SMPData *>::operator=(), and vmap< std::string, DiscConfig::SMPData *>::value_comp().
V_c
template<class Key, class T, class Compare = dummy_less<Key>> rep_type vmap< Key, T, Compare >::V_c private
Definition at line 83 of file vmap.h.
Referenced by vmap< std::string, DiscConfig::SMPData *>::begin(), vmap< std::string, DiscConfig::SMPData *>::capacity(), vmap< std::string, DiscConfig::SMPData *>::empty(), vmap< std::string, DiscConfig::SMPData *>::end(), vmap< std::string, DiscConfig::SMPData *>::max_size(), vmap< std::string, DiscConfig::SMPData *>::operator=(), vmap< std::string, DiscConfig::SMPData *>::rbegin(), vmap< std::string, DiscConfig::SMPData *>::rend(), vmap< std::string, DiscConfig::SMPData *>::reserve(), vmap< std::string, DiscConfig::SMPData *>::size(), vmap< std::string, DiscConfig::SMPData *>::swap(), and vmap< std::string, DiscConfig::SMPData *>::vmap().
The documentation for this class was generated from the following files:
ippl/src/Utility/vmap.h
ippl/src/Utility/vmap.hpp