OPAL (Object Oriented Parallel Accelerator Library): OpalMultipoleTCurvedVarRadius Class Reference
OpalMultipoleTCurvedVarRadius Class Reference
#include <OpalMultipoleTCurvedVarRadius.h>
Public Types
enum {
TP = COMMON, RFRINGE, LFRINGE, HAPERT,
VAPERT, MAXFORDER, MAXXORDER, ANGLE,
ROTATION, EANGLE, BBLENGTH, SIZE
}
Public Types inherited from OpalElement
enum {
TYPE, APERT, LENGTH, ELEMEDGE,
WAKEF, PARTICLEMATTERINTERACTION, ORIGIN, ORIENTATION,
X, Y, Z, THETA,
PHI, PSI, DX, DY,
DZ, DTHETA, DPHI, DPSI,
OUTFN, COMMON
}
The common attributes for all elements.
Public Types inherited from Element
enum ReferenceType { IS_ENTRY, IS_CENTRE, IS_EXIT }
Reference for element positioning.
Public Member Functions
OpalMultipoleTCurvedVarRadius ()
virtual ~OpalMultipoleTCurvedVarRadius ()
virtual OpalMultipoleTCurvedVarRadius * clone (const std::string &name)
virtual void update ()
void print (std::ostream &os) const
Print the object.
Public Member Functions inherited from OpalElement
virtual ~OpalElement ()
virtual double getLength () const
Return element length.
const std::string getTypeName () const
Return the element's type name.
std::pair< ElementBase::ApertureType, std::vector< double > > getApert () const
const std::string getWakeF () const
Return the element's type name.
const std::string getParticleMatterInteraction () const
const std::string getWMaterial () const
const std::string getWakeGeom () const
std::vector< double > getWakeParam () const
const std::string getWakeConductivity () const
virtual void parse (Statement &)
Parse the element.
virtual void updateUnknown (ElementBase *)
Transmit the `‘unknown’' (not known to OPAL) attributes to CLASSIC.
Public Member Functions inherited from Element
virtual ~Element ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual double getEntrance (ReferenceType) const
Return arc length from origin to entrance (negative !).
virtual double getExit (ReferenceType) const
Return arc length from origin to exit (positive !).
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded CLASSIC element.
void setElement (ElementBase *)
Assign new CLASSIC element.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
OpalMultipoleTCurvedVarRadius (const OpalMultipoleTCurvedVarRadius &)
void operator= (const OpalMultipoleTCurvedVarRadius &)
OpalMultipoleTCurvedVarRadius (const std::string &name, OpalMultipoleTCurvedVarRadius *parent)
Additional Inherited Members
Static Public Member Functions inherited from Element
static Element * find (const std::string &name)
Find named Element.
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from OpalElement
OpalElement (int size, const char *name, const char *help)
Exemplar constructor.
OpalElement (const std::string &name, OpalElement *parent)
Clone constructor.
void registerOwnership () const
Protected Member Functions inherited from Element
Element (int size, const char *name, const char *help)
Constructor for exemplars.
Element (const std::string &name, Element *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Static Protected Member Functions inherited from OpalElement
static void printMultipoleStrength (std::ostream &os, int order, int &len, const std::string &sName, const std::string &tName, const Attribute &length, const Attribute &vNorm, const Attribute &vSkew)
Print multipole components in OPAL-8 format.
static void printAttribute (std::ostream &os, const std::string &name, const std::string &image, int &len)
Print an attribute with a OPAL-8 name (as an expression).
static void printAttribute (std::ostream &os, const std::string &name, double value, int &len)
Print an attribute with a OPAL-8 name (as a constant).
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
OpalMultipoleTCurvedVarRadius provides user interface information for the MultipoleTCurvedVarRadius object
Defines input parameters
Definition at line 40 of file OpalMultipoleTCurvedVarRadius.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
TP
RFRINGE
LFRINGE
HAPERT
VAPERT
MAXFORDER
MAXXORDER
ANGLE
ROTATION
EANGLE
BBLENGTH
SIZE
Definition at line 45 of file OpalMultipoleTCurvedVarRadius.h.
Constructor & Destructor Documentation
OpalMultipoleTCurvedVarRadius() [1/3]
OpalMultipoleTCurvedVarRadius::OpalMultipoleTCurvedVarRadius ()
Default constructor initialises UI parameters.
Definition at line 47 of file OpalMultipoleTCurvedVarRadius.cpp.
References ANGLE, BBLENGTH, EANGLE, HAPERT, Object::itsAttr, LFRINGE, Attributes::makeReal(), Attributes::makeRealArray(), MAXFORDER, MAXXORDER, OpalElement::registerOwnership(), RFRINGE, ROTATION, Element::setElement(), TP, and VAPERT.
Referenced by clone().
~OpalMultipoleTCurvedVarRadius()
OpalMultipoleTCurvedVarRadius::~OpalMultipoleTCurvedVarRadius () virtual
Destructor does nothing
Definition at line 90 of file OpalMultipoleTCurvedVarRadius.cpp.
OpalMultipoleTCurvedVarRadius() [2/3]
OpalMultipoleTCurvedVarRadius::OpalMultipoleTCurvedVarRadius (const OpalMultipoleTCurvedVarRadius &) private
OpalMultipoleTCurvedVarRadius() [3/3]
OpalMultipoleTCurvedVarRadius::OpalMultipoleTCurvedVarRadius (const std::string & name, OpalMultipoleTCurvedVarRadius * parent) private
Definition at line 83 of file OpalMultipoleTCurvedVarRadius.cpp.
References name, and Element::setElement().
Member Function Documentation
clone()
OpalMultipoleTCurvedVarRadius * OpalMultipoleTCurvedVarRadius::clone (const std::string & name) virtual
Inherited copy constructor
Implements Object.
Definition at line 94 of file OpalMultipoleTCurvedVarRadius.cpp.
References name, and OpalMultipoleTCurvedVarRadius().
operator=()
void OpalMultipoleTCurvedVarRadius::operator= (const OpalMultipoleTCurvedVarRadius &) private
print()
void OpalMultipoleTCurvedVarRadius::print (std::ostream & os) const virtual
Print the object.
Reimplemented from OpalElement.
Definition at line 99 of file OpalMultipoleTCurvedVarRadius.cpp.
References OpalElement::print().
update()
void OpalMultipoleTCurvedVarRadius::update () virtual
Update the MultipoleTCurvedVarRadius with new parameters from UI parser
Reimplemented from OpalElement.
Definition at line 104 of file OpalMultipoleTCurvedVarRadius.cpp.
References ANGLE, BBLENGTH, EANGLE, Element::getElement(), MultipoleTCurvedVarRadius::getGeometry(), Attributes::getReal(), Attributes::getRealArray(), HAPERT, Object::itsAttr, OpalElement::LENGTH, LFRINGE, MAXFORDER, MAXXORDER, RFRINGE, ROTATION, MultipoleTBase::setAperture(), MultipoleTCurvedVarRadius::setBendAngle(), MultipoleTBase::setBoundingBoxLength(), Element::setElement(), ElementBase::setElementLength(), MultipoleTBase::setEntranceAngle(), MultipoleTBase::setFringeField(), MultipoleTBase::setLength(), MultipoleTCurvedVarRadius::setMaxOrder(), MultipoleTCurvedVarRadius::setMaxXOrder(), MultipoleTBase::setRotation(), MultipoleTBase::setTransMaxOrder(), MultipoleTBase::setTransProfile(), TP, OpalElement::update(), OpalElement::updateUnknown(), and VAPERT.
The documentation for this class was generated from the following files:
src/Elements/OpalMultipoleTCurvedVarRadius.h
src/Elements/OpalMultipoleTCurvedVarRadius.cpp