OPAL (Object Oriented Parallel Accelerator Library): BrickCounter< Dim > Class Template Reference
BrickCounter< Dim > Class Template Reference
#include <BrickIterator.h>
Public Member Functions
BrickCounter ()
BrickCounter (const NDIndex< Dim > &)
BrickCounter & operator++ ()
bool done (unsigned d) const
void step (unsigned d)
void rewind (unsigned d)
int size (unsigned d) const
int GetOffset (unsigned d) const
Protected Member Functions
void op_pp ()
Protected Attributes
vec< int, Dim > Counters
vec< int, Dim > Counts
Detailed Description
template<unsigned Dim>
class BrickCounter< Dim >
Definition at line 22 of file BrickIterator.h.
Constructor & Destructor Documentation
BrickCounter() [1/2]
template<unsigned Dim> BrickCounter< Dim >::BrickCounter () inline
Definition at line 27 of file BrickIterator.h.
BrickCounter() [2/2]
template<unsigned Dim> BrickCounter< Dim >::BrickCounter (const NDIndex< Dim > & counted)
Definition at line 36 of file BrickIterator.hpp.
References Dim.
Member Function Documentation
done()
template<unsigned Dim> bool BrickCounter< Dim >::done (unsigned d) const inline
Definition at line 36 of file BrickIterator.h.
References BrickCounter< Dim >::Counters, and BrickCounter< Dim >::Counts.
Referenced by BareFieldIterator< T, Dim >::done(), and SIndexExpLoop< OP, Dim >::evaluate().
GetOffset()
template<unsigned Dim> int BrickCounter< Dim >::GetOffset (unsigned d) const inline
Definition at line 46 of file BrickIterator.h.
References BrickCounter< Dim >::Counters.
Referenced by BareFieldIterator< T, Dim >::GetCurrentLocation(), and BareFieldIterator< T, Dim >::isInGC().
op_pp()
template<unsigned Dim> void BrickCounter< Dim >::op_pp () protected
Definition at line 49 of file BrickIterator.hpp.
References Dim.
Referenced by BrickCounter< Dim >::operator++().
operator++()
template<unsigned Dim> BrickCounter& BrickCounter< Dim >::operator++ () inline
Definition at line 33 of file BrickIterator.h.
References BrickCounter< Dim >::op_pp().
rewind()
template<unsigned Dim> void BrickCounter< Dim >::rewind (unsigned d) inline
Definition at line 40 of file BrickIterator.h.
References BrickCounter< Dim >::Counters.
Referenced by SIndexExpLoop< OP, Dim >::evaluate(), and BrickIterator< T, Dim >::rewind().
size()
template<unsigned Dim> int BrickCounter< Dim >::size (unsigned d) const inline
Definition at line 43 of file BrickIterator.h.
References BrickCounter< Dim >::Counts.
Referenced by all_values_equal(), LField< T, Dim >::CanCompressBasedOnPhysicalCells(), and for_each().
step()
template<unsigned Dim> void BrickCounter< Dim >::step (unsigned d) inline
Definition at line 39 of file BrickIterator.h.
References BrickCounter< Dim >::Counters.
Referenced by SIndexExpLoop< OP, Dim >::evaluate(), and BrickIterator< T, Dim >::step().
Member Data Documentation
Counters
template<unsigned Dim> vec<int,Dim> BrickCounter< Dim >::Counters protected
Definition at line 50 of file BrickIterator.h.
Referenced by BrickCounter< Dim >::done(), BrickCounter< Dim >::GetOffset(), BrickCounter< Dim >::rewind(), and BrickCounter< Dim >::step().
Counts
template<unsigned Dim> vec<int,Dim> BrickCounter< Dim >::Counts protected
Definition at line 51 of file BrickIterator.h.
Referenced by BrickCounter< Dim >::done(), and BrickCounter< Dim >::size().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BrickIterator.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BrickIterator.hpp