OPAL (Object Oriented Parallel Accelerator Library): ippl/src/SubField/SubFieldAssign.hpp File Reference
SubFieldAssign.hpp File Reference
#include "SubField/SubFieldAssign.h"
#include "SubField/SubFieldAssignDefs.h"
#include "SubField/SubBareField.h"
#include "SubField/SubFieldTraits.h"
#include "SubField/SubFieldIter.h"
#include "Field/BareField.h"
#include "Field/BrickExpression.h"
#include "Field/LField.h"
#include "Field/Assign.h"
#include "Field/AssignDefs.h"
#include "Utility/IpplInfo.h"
Functions
template<class T1 , unsigned Dim, class S , class RHS , class OP >
void assign (SubBareField< T1, Dim, S > a, RHS b, OP op, ExprTag< true >)
Function Documentation
assign()
template<class T1 , unsigned Dim, class S , class RHS , class OP > void assign (SubBareField< T1, Dim, S > a, RHS b, OP op, ExprTag< true >)
Definition at line 44 of file SubFieldAssign.hpp.
References a, IpplInfo::abort(), LField< T, Dim >::begin(), endl(), ERRORMSG, IpplInfo::extraCompressChecks, FillGCIfNecessary(), for_each(), LField< T, Dim >::getOwned(), INCIPPLSTAT, PETE_apply(), PInsist, LField< T, Dim >::TryCompress(), TryCompressLHS(), and LField< T, Dim >::Uncompress().
Referenced by assign().