OPAL (Object Oriented Parallel Accelerator Library): ippl/src/SubParticle/SubParticleAssign.hpp File Reference
SubParticleAssign.hpp File Reference
#include "SubParticle/SubParticleAssign.h"
#include "SubParticle/SubParticleAssignDefs.h"
#include "SubParticle/SubParticleAttrib.h"
#include "Particle/ParticleAttrib.h"
#include "Index/SIndex.h"
#include "Index/LSIndex.h"
#include "Field/BrickExpression.h"
#include "Utility/IpplStats.h"
Classes
struct PAIsAssign< OP >
struct PAIsAssign< OpAssign >
Functions
template<class PA , class T , unsigned Dim, class RHS , class OP >
void assign (SubParticleAttrib< PA, T, Dim > a, RHS b, OP, ExprTag< true >)
Function Documentation
assign()
template<class PA , class T , unsigned Dim, class RHS , class OP > void assign (SubParticleAttrib< PA, T, Dim > a, RHS b, OP , ExprTag< true >)
Definition at line 54 of file SubParticleAssign.hpp.
References a, IpplInfo::abort(), BrickExpression< Dim, LHS, RHS, OP >::apply(), endl(), ERRORMSG, FillGCIfNecessary(), for_each(), SubParticleAttribIter< PA, T, Dim >::getLFieldIter(), INCIPPLSTAT, SubParticleAttribIter< PA, T, Dim >::initialize(), SubParticleAttribIter< PA, T, Dim >::nextLField(), and PInsist.
Referenced by assign().