OPAL (Object Oriented Parallel Accelerator Library): AmrYtWriter Class Reference
AmrYtWriter Class Reference
#include <AmrYtWriter.h>
Public Member Functions
AmrYtWriter (int step, int bin=0)
void writeFields (const amr::AmrScalarFieldContainer_t &rho, const amr::AmrScalarFieldContainer_t &phi, const amr::AmrVectorFieldContainer_t &efield, const amr::AmrIntArray_t &refRatio, const amr::AmrGeomContainer_t &geom, const int &nLevel, const double &time, const double &scale)
void writeBunch (const AmrPartBunch *bunch_p, const double &time, const double &gamma)
Public Member Functions inherited from AbstractAmrWriter
virtual ~AbstractAmrWriter ()
Private Member Functions
void writeParticles_m (int level, std::ofstream &ofs, int fnum, amrex::Vector< int > &which, amrex::Vector< int > &count, amrex::Vector< long > &where, const AmrPartBunch *bunch_p, const double gamma) const
Private Attributes
std::string dir_m
directory where to write files
std::vector< std::string > intData_m
integer bunch data
std::vector< std::string > realData_m
real bunch data
Detailed Description
Definition at line 34 of file AmrYtWriter.h.
Constructor & Destructor Documentation
AmrYtWriter()
AmrYtWriter::AmrYtWriter (int step, int bin = 0) explicit
Parameters
step we write
bin energy bin we write (multi-bunch simulation)
Definition at line 39 of file AmrYtWriter.cpp.
References Communicate::barrier(), IpplInfo::Comm, dir_m, Hypervolume::fs, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInputBasename(), OpalData::getInstance(), intData_m, IpplInfo::myNode(), and realData_m.
Member Function Documentation
writeBunch()
void AmrYtWriter::writeBunch (const AmrPartBunch * bunch_p, const double & time, const double & scale) virtual
Parameters
bunch_p
time
scale used for mapping
Implements AbstractAmrWriter.
Definition at line 298 of file AmrYtWriter.cpp.
References allreduce(), Communicate::barrier(), IpplInfo::Comm, dir_m, BoxLibLayout< T, Dim >::finestLevel(), AmrParticleBase< PLayout >::getAmrLayout(), AmrPartBunch::getAmrParticleBase(), PartBunchBase< T, Dim >::getLayout(), AmrParticleBase< PLayout >::getLocalNumPerLevel(), PartBunchBase< T, Dim >::getTotalNum(), Options::info, intData_m, max(), min(), IpplInfo::myNode(), realData_m, where(), and writeParticles_m().
writeFields()
void AmrYtWriter::writeFields (const amr::AmrScalarFieldContainer_t & rho, const amr::AmrScalarFieldContainer_t & phi, const amr::AmrVectorFieldContainer_t & efield, const amr::AmrIntArray_t & refRatio, const amr::AmrGeomContainer_t & geom, const int & nLevel, const double & time, const double & scale) virtual
Write yt files to the simulation subdirectory data/amr/yt. The data can be visualized using the python script pyOPALTools/amrPlots/visualize.py. Use the help to find out how to call the script.
Implements AbstractAmrWriter.
Definition at line 93 of file AmrYtWriter.cpp.
References Communicate::barrier(), IpplInfo::Comm, dir_m, IpplInfo::myNode(), and Hypervolume::n.
writeParticles_m()
void AmrYtWriter::writeParticles_m (int level, std::ofstream & ofs, int fnum, amrex::Vector< int > & which, amrex::Vector< int > & count, amrex::Vector< long > & where, const AmrPartBunch * bunch_p, const double gamma) const private
Definition at line 558 of file AmrYtWriter.cpp.
References AmrParticleLevelCounter< Key, T, Compare, Allocator >::begin(), PartBunchBase< T, Dim >::Bf, PartBunchBase< T, Dim >::Bin, PartBunchBase< T, Dim >::dt, PartBunchBase< T, Dim >::Ef, AmrPartBunch::getAmrParticleBase(), OpalData::getInstance(), PartBunchBase< T, Dim >::getLayout(), AmrParticleBase< PLayout >::getLocalNumPerLevel(), AmrParticleBase< PLayout >::Grid, PartBunchBase< T, Dim >::ID, Options::info, intData_m, PartBunchBase< T, Dim >::M, IpplInfo::myNode(), PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::Q, PartBunchBase< T, Dim >::R, realData_m, and where().
Referenced by writeBunch().
Member Data Documentation
dir_m
std::string AmrYtWriter::dir_m private
directory where to write files
Definition at line 88 of file AmrYtWriter.h.
Referenced by AmrYtWriter(), writeBunch(), and writeFields().
intData_m
std::vector<std::string> AmrYtWriter::intData_m private
integer bunch data
Definition at line 90 of file AmrYtWriter.h.
Referenced by AmrYtWriter(), writeBunch(), and writeParticles_m().
realData_m
std::vector<std::string> AmrYtWriter::realData_m private
real bunch data
Definition at line 91 of file AmrYtWriter.h.
Referenced by AmrYtWriter(), writeBunch(), and writeParticles_m().
The documentation for this class was generated from the following files:
src/Amr/AmrYtWriter.h
src/Amr/AmrYtWriter.cpp