OPAL (Object Oriented Parallel Accelerator Library): Configure Namespace Reference
Configure Namespace Reference
Functions
void configure ()
Configure all commands.
Function Documentation
configure()
void Configure::configure ()
Configure all commands.
Definition at line 250 of file Configure.cpp.
References Versions::fillChanges().
Referenced by opalMain(), and run_opal().