OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyRingDefinition Namespace Reference
PyOpal::PyRingDefinition Namespace Reference
Functions
BOOST_PYTHON_MODULE (ring_definition)
Variables
std::string ring_definition_docstring = std::string()
const char * module_docstring = "build a ring_definition"
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyRingDefinition::BOOST_PYTHON_MODULE (ring_definition)
Definition at line 36 of file PyRingDefinition.cpp.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::addGetOpalElement(), PyOpal::Globals::Initialise(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_class(), and PyOpal::ExceptionTranslation::registerExceptions().
Variable Documentation
module_docstring
const char * PyOpal::PyRingDefinition::module_docstring = "build a ring_definition"
Definition at line 14 of file PyRingDefinition.cpp.
ring_definition_docstring
std::string PyOpal::PyRingDefinition::ring_definition_docstring = std::string()
Definition at line 11 of file PyRingDefinition.cpp.