OPAL (Object Oriented Parallel Accelerator Library): MultipoleT Class Reference
MultipoleT Class Reference final
#include <MultipoleT.h>
Public Member Functions
MultipoleT (const std::string &name)
MultipoleT (const MultipoleT &right)
~MultipoleT () override=default
ElementBase * clone () const override
void accept (BeamlineVisitor &visitor) const override
BGeometryBase & getGeometry () override
const BGeometryBase & getGeometry () const override
EMField & getField () override
const EMField & getField () const override
bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
void finalise () override
bool bends () const override
size_t getMaxFOrder () const
size_t getMaxXOrder () const
void setMaxOrder (size_t orderZ, size_t orderX)
std::size_t getTransMaxOrder () const
void setTransProfile (const std::vector< double > &profile)
const std::vector< double > & getTransProfile () const
void setFringeField (const double &s0, const double &lambda_left, const double &lambda_right)
std::tuple< double, double, double > getFringeField () const
void setEntranceAngle (double entranceAngle)
void setEntryOffset (double offset)
double getEntryOffset () const
bool getVariableRadius () const
void setBendAngle (double angle, bool variableRadius)
double getBendAngle () const
double getEntranceAngle () const
void setElementLength (double length) override
double getLength () const
void setAperture (const double &vertAp, const double &horizAp)
std::tuple< double, double > getAperture ()
void setRotation (double rot)
double getRotation () const
double getBoundingBoxLength () const
void setBoundingBoxLength (double boundingBoxLength)
void getDimensions (double &, double &) const override
double getFringeDeriv (const std::size_t &n, const double &s)
double getFnDerivX (const std::size_t &n, const double &x, const double &s)
double getFnDerivS (const std::size_t &n, const double &x, const double &s)
double getTransDeriv (const std::size_t &n, const double &x) const
Vector_t toMagnetCoords (const Vector_t &R)
Vector_t getField (const Vector_t &magnetCoords)
Vector_t localCartesianToOpalCartesian (const Vector_t &r)
double localCartesianRotation ()
void setScalingName (const std::string &name)
void setScalingModel (const std::shared_ptr< AbstractTimeDependence > &td)
std::string getScalingName () const
void initialiseTimeDepencencies () const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual ElementType getType () const override
Get element type std::string.
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Member Functions
Vector_t rotateFrame (const Vector_t &R) const
bool insideAperture (const Vector_t &R) const
bool insideBoundingBox (const Vector_t &R) const
void chooseImplementation ()
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes
endfieldmodel::Tanh fringeField_l {endfieldmodel::Tanh()}
endfieldmodel::Tanh fringeField_r {endfieldmodel::Tanh()}
std::size_t maxFOrder_m {3}
std::size_t maxXOrder_m {20}
std::vector< double > transProfile_m {0.0}
size_t transMaxOrder_m {1}
double length_m {1.0}
double entranceAngle_m {0.0}
double rotation_m {0.0}
double bendAngle_m {0.0}
bool variableRadius_m {false}
double boundingBoxLength_m {0.0}
double entryOffset_m {0.0}
double verticalApert_m {0.5}
double horizontalApert_m {0.5}
BMultipoleField dummy
std::string scalingName_m
std::shared_ptr< AbstractTimeDependence > scalingTD_m
std::unique_ptr< MultipoleTBase > implementation_ {}
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
MultipoleT implements a straight or curved combined
function magnet (up to arbitrary multipole component) with fringe fields.
Class category: AbsBeamline
$Author: Titus Dascalu, Martin Duy Tat, Chris Rogers
The field is obtained from the scalar potential
\[ V = f_0(x,s) z + f_1 (x,s) \frac{z^3}{3!} + f_2 (x,s) \frac{z^5}{5!} + ... \]
(x,z,s) -> Frenet-Serret local coordinates along the magnet
z -> vertical component
assume mid-plane symmetry
set field on mid-plane -> \(B_z = f_0(x,s) = T(x) \cdot S(s) \)
T(x) -> transverse profile; this is a polynomial describing the field expansion on the mid-plane inside the magnet (not in the fringe field); 1st term is the dipole strength, 2nd term is the quadrupole gradient * x, etc.
-> when setting the magnet, one gives the multipole coefficients of this polynomial (i.e. dipole strength,
quadrupole gradient, etc.)
----------— example --------------------------------------------—
Setting a combined function magnet with dipole, quadrupole and sextupole components:
\(T(x) = B_0 + B_1 \cdot x + B_2 \cdot x^2 \)
user gives \(B_0, B_1, B_2 \)
----------— example end ----------------------------------------—
S(s) -> fringe field
recursion -> \(f_n (x,s) = (-1)^n \cdot \sum_{i=0}^{n} C_n^i \cdot T^{(2i)} \cdot S^{(2n-2i)} \)
for curved magnets the above recursion is more complicated
\(C_n^i \) -> binomial coeff; \(T^{(n)} \) -> n-th derivative
Definition at line 88 of file MultipoleT.h.
Constructor & Destructor Documentation
MultipoleT() [1/2]
MultipoleT::MultipoleT (const std::string & name) explicit
Constructor
Parameters
name -> User-defined name
Definition at line 42 of file MultipoleT.cpp.
References chooseImplementation().
Referenced by clone().
MultipoleT() [2/2]
MultipoleT::MultipoleT (const MultipoleT & right)
Copy constructor
Definition at line 47 of file MultipoleT.cpp.
References chooseImplementation(), and Component::RefPartBunch_m.
~MultipoleT()
MultipoleT::~MultipoleT () override default
Destructor
Member Function Documentation
accept()
void MultipoleT::accept (BeamlineVisitor & visitor) const override virtual
Accept a beamline visitor
Implements ElementBase.
Definition at line 73 of file MultipoleT.cpp.
References initialiseTimeDepencencies(), and BeamlineVisitor::visitMultipoleT().
apply() [1/2]
bool MultipoleT::apply (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Calculate the field at some arbitrary position
If particle is outside field map true is returned, otherwise false is returned
Parameters
R -> Position in the lab coordinate system of the multipole
P -> Not used
t -> Time at which the field is to be calculated
E -> Calculated electric field - always 0 (no E-field)
B -> Calculated magnetic field
Reimplemented from Component.
Definition at line 129 of file MultipoleT.cpp.
References getField(), ElementBase::getFlagDeleteOnTransverseExit(), insideAperture(), insideBoundingBox(), Attrib::Distribution::R, scalingTD_m, and toMagnetCoords().
Referenced by apply().
apply() [2/2]
bool MultipoleT::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Calculate the field at the position of the ith particle
Parameters
i -> Index of the particle event; field is calculated at this position If particle is outside field map true is returned, otherwise false is returned
t -> Time at which the field is to be calculated
E -> Calculated electric field - always 0 (no E-field)
B -> Calculated magnetic field
Reimplemented from Component.
Definition at line 228 of file MultipoleT.cpp.
References apply(), PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::R, and Component::RefPartBunch_m.
bends()
bool MultipoleT::bends () const override virtual
Return true if dipole component not zero
Implements Component.
Definition at line 293 of file MultipoleT.cpp.
References bendAngle_m, and transProfile_m.
chooseImplementation()
void MultipoleT::chooseImplementation () protected
Definition at line 247 of file MultipoleT.cpp.
References bendAngle_m, implementation_, and variableRadius_m.
Referenced by MultipoleT(), and setBendAngle().
clone()
ElementBase * MultipoleT::clone () const override virtual
Inheritable copy constructor
Implements ElementBase.
Definition at line 69 of file MultipoleT.cpp.
References MultipoleT().
Referenced by ParallelCyclotronTracker::visitMultipoleT().
finalise()
void MultipoleT::finalise () override virtual
Finalise the MultipoleT - sets bunch to nullptr
Implements Component.
Definition at line 224 of file MultipoleT.cpp.
References Component::RefPartBunch_m.
getAperture()
std::tuple<double, double> MultipoleT::getAperture () inline
Get the aperture dimensions
Returns
{verticalApert, horizontalApert}
Definition at line 206 of file MultipoleT.h.
References horizontalApert_m, and verticalApert_m.
getBendAngle()
double MultipoleT::getBendAngle () const inline
Get the bending angle of the magnet
Definition at line 187 of file MultipoleT.h.
References bendAngle_m.
Referenced by MultipoleTCurvedConstRadius::getFn(), MultipoleTCurvedVarRadius::getFn(), MultipoleTCurvedConstRadius::getScaleFactor(), MultipoleTCurvedVarRadius::getScaleFactor(), MultipoleTCurvedConstRadius::initialise(), MultipoleTCurvedVarRadius::initialise(), MultipoleTCurvedVarRadius::localCartesianToCurvilinear(), MultipoleTCurvedConstRadius::localCartesianToOpalCartesian(), MultipoleTCurvedConstRadius::transformBField(), MultipoleTCurvedVarRadius::transformBField(), and MultipoleTCurvedConstRadius::transformCoords().
getBoundingBoxLength()
double MultipoleT::getBoundingBoxLength () const inline
Get the bounding box size
Definition at line 215 of file MultipoleT.h.
References boundingBoxLength_m.
getDimensions()
void MultipoleT::getDimensions (double & , double &) const inline override virtual
Not implemented
Implements Component.
Definition at line 221 of file MultipoleT.h.
getEntranceAngle()
double MultipoleT::getEntranceAngle () const inline
Get the entrance angle
Definition at line 189 of file MultipoleT.h.
References entranceAngle_m.
getEntryOffset()
double MultipoleT::getEntryOffset () const inline
Get the offset of the entry point from the standard position
Definition at line 181 of file MultipoleT.h.
References entryOffset_m.
Referenced by MultipoleTCurvedVarRadius::initialise().
getField() [1/3]
EMField& MultipoleT::getField () inline override virtual
Return a dummy field value
Implements Component.
Definition at line 107 of file MultipoleT.h.
References dummy.
Referenced by apply().
getField() [2/3]
const EMField& MultipoleT::getField () const inline override virtual
Return a dummy field value
Implements Component.
Definition at line 109 of file MultipoleT.h.
References dummy.
getField() [3/3]
Vector_t MultipoleT::getField (const Vector_t & magnetCoords)
Calculate B-field in the local Frenet-Serret frame
Transform B-field from local to lab coordinates
Definition at line 117 of file MultipoleT.cpp.
References implementation_.
getFnDerivS()
double MultipoleT::getFnDerivS (const std::size_t & n, const double & x, const double & s)
Calculate partial derivative of fn wrt s using a 5-point finite difference formula Error of order stepSize^4
Parameters
n -> nth derivative
x -> Coordinate x
s -> Coordinate s
Definition at line 210 of file MultipoleT.cpp.
References Physics::e, getFringeDeriv(), getTransDeriv(), implementation_, and Hypervolume::n.
Referenced by MultipoleTBase::getBs().
getFnDerivX()
double MultipoleT::getFnDerivX (const std::size_t & n, const double & x, const double & s)
Calculate partial derivative of fn wrt x using a 5-point finite difference formula Error of order stepSize^4
Parameters
n -> nth derivative
x -> Coordinate x
s -> Coordinate s
Definition at line 196 of file MultipoleT.cpp.
References Physics::e, getFringeDeriv(), getTransDeriv(), implementation_, and Hypervolume::n.
Referenced by MultipoleTBase::getBx().
getFringeDeriv()
double MultipoleT::getFringeDeriv (const std::size_t & n, const double & s)
Returns the value of the fringe field n-th derivative at s
Parameters
n -> nth derivative
s -> Coordinate s
Definition at line 159 of file MultipoleT.cpp.
References fringeField_l, fringeField_r, endfieldmodel::Tanh::getLambda(), endfieldmodel::Tanh::getNegTanh(), endfieldmodel::Tanh::getTanh(), endfieldmodel::Tanh::getX0(), tanhderiv::integrate(), and Hypervolume::n.
Referenced by MultipoleTStraight::getBs(), MultipoleTStraight::getBx(), MultipoleTCurvedConstRadius::getFn(), MultipoleTCurvedVarRadius::getFn(), MultipoleTStraight::getFn(), getFnDerivS(), getFnDerivX(), and MultipoleTCurvedVarRadius::getScaleFactor().
getFringeField()
std::tuple< double, double, double > MultipoleT::getFringeField () const
Get the fringe field model
Returns
{s0, leftFringe, rightFringe}
Definition at line 155 of file MultipoleT.cpp.
References fringeField_l, fringeField_r, endfieldmodel::Tanh::getLambda(), and endfieldmodel::Tanh::getX0().
Referenced by MultipoleTCurvedVarRadius::initialise(), MultipoleTCurvedVarRadius::localCartesianToCurvilinear(), and MultipoleTCurvedVarRadius::transformBField().
getGeometry() [1/2]
BGeometryBase & MultipoleT::getGeometry () override virtual
Return the cell geometry
Implements ElementBase.
Definition at line 315 of file MultipoleT.cpp.
References implementation_.
getGeometry() [2/2]
const BGeometryBase & MultipoleT::getGeometry () const override virtual
Return the cell geometry
Implements ElementBase.
Definition at line 319 of file MultipoleT.cpp.
References implementation_.
getLength()
double MultipoleT::getLength () const inline
Get the length of the magnet
Definition at line 196 of file MultipoleT.h.
References length_m.
Referenced by MultipoleTCurvedConstRadius::getFn(), MultipoleTCurvedVarRadius::getFn(), MultipoleTCurvedConstRadius::getScaleFactor(), MultipoleTCurvedVarRadius::getScaleFactor(), MultipoleTStraight::initialise(), MultipoleTCurvedConstRadius::initialise(), MultipoleTCurvedVarRadius::initialise(), MultipoleTCurvedVarRadius::localCartesianToCurvilinear(), MultipoleTCurvedConstRadius::localCartesianToOpalCartesian(), MultipoleTStraight::localCartesianToOpalCartesian(), MultipoleTCurvedConstRadius::transformBField(), MultipoleTCurvedVarRadius::transformBField(), MultipoleTStraight::transformCoords(), and MultipoleTCurvedConstRadius::transformCoords().
getMaxFOrder()
size_t MultipoleT::getMaxFOrder () const inline
Get the number of terms used in calculation of field components
Definition at line 143 of file MultipoleT.h.
References maxFOrder_m.
Referenced by MultipoleTStraight::getBs(), MultipoleTBase::getBs(), MultipoleTStraight::getBx(), MultipoleTBase::getBx(), MultipoleTBase::getBz(), MultipoleTCurvedConstRadius::initialise(), and MultipoleTCurvedVarRadius::initialise().
getMaxXOrder()
size_t MultipoleT::getMaxXOrder () const inline
Definition at line 144 of file MultipoleT.h.
References maxXOrder_m.
Referenced by MultipoleTCurvedConstRadius::initialise(), and MultipoleTCurvedVarRadius::initialise().
getRotation()
double MultipoleT::getRotation () const inline
Get the angle of rotation of the magnet around its axis
Definition at line 213 of file MultipoleT.h.
References rotation_m.
getScalingName()
std::string MultipoleT::getScalingName () const inline
Definition at line 262 of file MultipoleT.h.
References scalingName_m.
getTransDeriv()
double MultipoleT::getTransDeriv (const std::size_t & n, const double & x) const
Returns the value of the transverse field n-th derivative at x
Transverse field is a polynomial in x, differentiation follows usual polynomial rules of differentiation
Parameters
n -> nth derivative
x -> Coordinate x
Definition at line 172 of file MultipoleT.cpp.
References getTransMaxOrder(), getTransProfile(), Hypervolume::n, and transMaxOrder_m.
Referenced by MultipoleTStraight::getBs(), MultipoleTStraight::getBx(), MultipoleTCurvedConstRadius::getFn(), MultipoleTCurvedVarRadius::getFn(), MultipoleTStraight::getFn(), getFnDerivS(), and getFnDerivX().
getTransMaxOrder()
std::size_t MultipoleT::getTransMaxOrder () const inline
Get the maximum order in the given transverse profile
Definition at line 151 of file MultipoleT.h.
References transMaxOrder_m.
Referenced by getTransDeriv(), MultipoleTCurvedConstRadius::setMaxOrder(), and MultipoleTCurvedVarRadius::setMaxOrder().
getTransProfile()
const std::vector<double>& MultipoleT::getTransProfile () const inline
Get all terms of transverse profile
Definition at line 157 of file MultipoleT.h.
References transProfile_m.
Referenced by getTransDeriv().
getVariableRadius()
bool MultipoleT::getVariableRadius () const inline
Get the variable radius of the magnet
Definition at line 183 of file MultipoleT.h.
References variableRadius_m.
initialise()
void MultipoleT::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Initialise the MultipoleT
Parameters
bunch -> Bunch the global bunch object
startField -> Not used
endField -> Not used
Implements Component.
Definition at line 297 of file MultipoleT.cpp.
References implementation_, and Component::RefPartBunch_m.
initialiseTimeDepencencies()
void MultipoleT::initialiseTimeDepencencies () const
Definition at line 308 of file MultipoleT.cpp.
References AbstractTimeDependence::getTimeDependence(), scalingName_m, and scalingTD_m.
Referenced by accept(), and PyOpal::PyOpalObjectNS::PyOpalObject< C >::doSetup().
insideAperture()
bool MultipoleT::insideAperture (const Vector_t & R) const protected
Definition at line 98 of file MultipoleT.cpp.
References abs(), horizontalApert_m, Attrib::Distribution::R, and verticalApert_m.
Referenced by apply().
insideBoundingBox()
bool MultipoleT::insideBoundingBox (const Vector_t & R) const protected
Definition at line 103 of file MultipoleT.cpp.
References boundingBoxLength_m, fabs(), and Attrib::Distribution::R.
Referenced by apply().
localCartesianRotation()
double MultipoleT::localCartesianRotation ()
Definition at line 327 of file MultipoleT.cpp.
References implementation_.
localCartesianToOpalCartesian()
Vector_t MultipoleT::localCartesianToOpalCartesian (const Vector_t & r)
Definition at line 323 of file MultipoleT.cpp.
References implementation_.
rotateFrame()
Vector_t MultipoleT::rotateFrame (const Vector_t & R) const protected
Rotate the frame to account for the rotation and entry angles.
Parameters
R -> coordinate to rotate
Returns
-> rotated coordinate
Apply two 2D rotation matrices to coordinate vector Rotate around central axis => skew fields Rotate azimuthally => entrance angle
Definition at line 78 of file MultipoleT.cpp.
References cos(), entranceAngle_m, Attrib::Distribution::R, rotation_m, and sin().
Referenced by toMagnetCoords().
setAperture()
void MultipoleT::setAperture (const double & vertAp, const double & horizAp)
Set the aperture dimensions
This element only supports a rectangular aperture
Parameters
vertAp -> Vertical aperture length
horizAp -> Horisontal aperture length
Definition at line 258 of file MultipoleT.cpp.
References horizontalApert_m, and verticalApert_m.
setBendAngle()
void MultipoleT::setBendAngle (double angle, bool variableRadius)
Set the bending angle of the magnet
Definition at line 240 of file MultipoleT.cpp.
References bendAngle_m, chooseImplementation(), and variableRadius_m.
setBoundingBoxLength()
void MultipoleT::setBoundingBoxLength (double boundingBoxLength)
Set the bounding box size. This controls the region for
Parameters
boundingBoxLength -> Distance between centre and entrance
Definition at line 263 of file MultipoleT.cpp.
References boundingBoxLength_m.
setElementLength()
void MultipoleT::setElementLength (double length) override virtual
Set the length of the magnet If straight-> Actual length If curved -> Arc length
Reimplemented from ElementBase.
Definition at line 232 of file MultipoleT.cpp.
References implementation_, length_m, and ElementBase::setElementLength().
Referenced by OpalMultipoleT::update().
setEntranceAngle()
void MultipoleT::setEntranceAngle (double entranceAngle)
Set the entrance angle
Parameters
entranceAngle -> Entrance angle
Definition at line 285 of file MultipoleT.cpp.
References entranceAngle_m.
setEntryOffset()
void MultipoleT::setEntryOffset (double offset)
Set the offset of the entry point from the standard position
Parameters
offset positive for further away from the center
Definition at line 289 of file MultipoleT.cpp.
References entryOffset_m.
setFringeField()
void MultipoleT::setFringeField (const double & s0, const double & lambda_left, const double & lambda_right)
Set fringe field model
Tanh model used here
\[ 1/2 * \left [tanh \left(\frac{s + s_0}{\lambda_{left}} \right) - tanh \left(\frac{s - s_0}{\lambda_{right}} \right) \right] \]
Parameters
s0 -> Centre field length and
lambda_left -> Left end field length
lambda_right -> Right end field length
Definition at line 146 of file MultipoleT.cpp.
References fringeField_l, fringeField_r, implementation_, maxFOrder_m, endfieldmodel::Tanh::setLambda(), and endfieldmodel::Tanh::setX0().
setMaxOrder()
void MultipoleT::setMaxOrder (size_t orderZ, size_t orderX)
Set the number of terms used in calculation of field components
Parameters
orderZ -> Number of terms in expansion in z
orderX -> Number of terms in expansion in x
Definition at line 275 of file MultipoleT.cpp.
References implementation_, maxFOrder_m, and maxXOrder_m.
setRotation()
void MultipoleT::setRotation (double rot)
Set the angle of rotation of the magnet around its axis
To make skew components
Parameters
rot -> Angle of rotation
Definition at line 281 of file MultipoleT.cpp.
References rotation_m.
setScalingModel()
void MultipoleT::setScalingModel (const std::shared_ptr< AbstractTimeDependence > & td) inline
Definition at line 261 of file MultipoleT.h.
References scalingTD_m.
setScalingName()
void MultipoleT::setScalingName (const std::string & name)
Definition at line 303 of file MultipoleT.cpp.
References name, and scalingName_m.
setTransProfile()
void MultipoleT::setTransProfile (const std::vector< double > & profile)
Set the the transverse profile
Parameters
profile -> Multipole field profile
Definition at line 267 of file MultipoleT.cpp.
References transMaxOrder_m, and transProfile_m.
toMagnetCoords()
Vector_t MultipoleT::toMagnetCoords (const Vector_t & R)
Rotate coordinates around the central axis of the magnet
Go to local Frenet-Serret coordinates
Definition at line 107 of file MultipoleT.cpp.
References implementation_, Attrib::Distribution::R, and rotateFrame().
Referenced by apply().
Member Data Documentation
bendAngle_m
double MultipoleT::bendAngle_m {0.0} protected
Definition at line 289 of file MultipoleT.h.
Referenced by bends(), chooseImplementation(), getBendAngle(), and setBendAngle().
boundingBoxLength_m
double MultipoleT::boundingBoxLength_m {0.0} protected
Definition at line 291 of file MultipoleT.h.
Referenced by getBoundingBoxLength(), insideBoundingBox(), and setBoundingBoxLength().
dummy
BMultipoleField MultipoleT::dummy protected
Not implemented
Definition at line 297 of file MultipoleT.h.
Referenced by getField().
entranceAngle_m
double MultipoleT::entranceAngle_m {0.0} protected
Definition at line 287 of file MultipoleT.h.
Referenced by getEntranceAngle(), rotateFrame(), and setEntranceAngle().
entryOffset_m
double MultipoleT::entryOffset_m {0.0} protected
Definition at line 292 of file MultipoleT.h.
Referenced by getEntryOffset(), and setEntryOffset().
fringeField_l
endfieldmodel::Tanh MultipoleT::fringeField_l {endfieldmodel::Tanh()} protected
Definition at line 276 of file MultipoleT.h.
Referenced by getFringeDeriv(), getFringeField(), and setFringeField().
fringeField_r
endfieldmodel::Tanh MultipoleT::fringeField_r {endfieldmodel::Tanh()} protected
Definition at line 277 of file MultipoleT.h.
Referenced by getFringeDeriv(), getFringeField(), and setFringeField().
horizontalApert_m
double MultipoleT::horizontalApert_m {0.5} protected
Definition at line 295 of file MultipoleT.h.
Referenced by getAperture(), insideAperture(), and setAperture().
implementation_
std::unique_ptr<MultipoleTBase> MultipoleT::implementation_ {} protected
Definition at line 302 of file MultipoleT.h.
Referenced by chooseImplementation(), getField(), getFnDerivS(), getFnDerivX(), getGeometry(), initialise(), localCartesianRotation(), localCartesianToOpalCartesian(), setElementLength(), setFringeField(), setMaxOrder(), and toMagnetCoords().
length_m
double MultipoleT::length_m {1.0} protected
Magnet parameters
Definition at line 286 of file MultipoleT.h.
Referenced by getLength(), and setElementLength().
maxFOrder_m
std::size_t MultipoleT::maxFOrder_m {3} protected
Number of terms in z expansion used in calculating field components
Definition at line 279 of file MultipoleT.h.
Referenced by getMaxFOrder(), setFringeField(), and setMaxOrder().
maxXOrder_m
std::size_t MultipoleT::maxXOrder_m {20} protected
Highest order of polynomial expansions in x
Definition at line 281 of file MultipoleT.h.
Referenced by getMaxXOrder(), and setMaxOrder().
rotation_m
double MultipoleT::rotation_m {0.0} protected
Definition at line 288 of file MultipoleT.h.
Referenced by getRotation(), rotateFrame(), and setRotation().
scalingName_m
std::string MultipoleT::scalingName_m protected
Definition at line 299 of file MultipoleT.h.
Referenced by getScalingName(), initialiseTimeDepencencies(), and setScalingName().
scalingTD_m
std::shared_ptr<AbstractTimeDependence> MultipoleT::scalingTD_m mutable protected
Definition at line 300 of file MultipoleT.h.
Referenced by apply(), initialiseTimeDepencencies(), and setScalingModel().
transMaxOrder_m
size_t MultipoleT::transMaxOrder_m {1} protected
Definition at line 284 of file MultipoleT.h.
Referenced by getTransDeriv(), getTransMaxOrder(), and setTransProfile().
transProfile_m
std::vector<double> MultipoleT::transProfile_m {0.0} protected
List of transverse profile coefficients
Definition at line 283 of file MultipoleT.h.
Referenced by bends(), getTransProfile(), and setTransProfile().
variableRadius_m
bool MultipoleT::variableRadius_m {false} protected
Definition at line 290 of file MultipoleT.h.
Referenced by chooseImplementation(), getVariableRadius(), and setBendAngle().
verticalApert_m
double MultipoleT::verticalApert_m {0.5} protected
Assume rectangular aperture with these dimensions
Definition at line 294 of file MultipoleT.h.
Referenced by getAperture(), insideAperture(), and setAperture().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/AbsBeamline/MultipoleT.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/AbsBeamline/MultipoleT.cpp