OPAL (Object Oriented Parallel Accelerator Library): DataSourceObject Class Reference
DataSourceObject Class Reference
#include <DataSourceObject.h>
Public Member Functions
DataSourceObject (const char *nm, DataSource *ds, DataConnect *dc, int tm)
DataSourceObject ()
virtual ~DataSourceObject ()
bool connected () const
DataConnect * getConnection ()
DataSource * getSource ()
virtual bool update ()
virtual void interact (const char *=0)
Public Member Functions inherited from NamedObj
NamedObj (const char *nm=0)
virtual ~NamedObj ()
const char * name () const
const char * setName (const char *nm=0)
Protected Attributes
DataConnect * Connection
DataSource * Source
int TransferMethod
Detailed Description
Definition at line 53 of file DataSourceObject.h.
Constructor & Destructor Documentation
DataSourceObject() [1/2]
DataSourceObject::DataSourceObject (const char * nm, DataSource * ds, DataConnect * dc, int tm) inline
Definition at line 57 of file DataSourceObject.h.
DataSourceObject() [2/2]
DataSourceObject::DataSourceObject () inline
Definition at line 61 of file DataSourceObject.h.
Referenced by make_DataSourceObject().
~DataSourceObject()
virtual DataSourceObject::~DataSourceObject () inline virtual
Definition at line 65 of file DataSourceObject.h.
Member Function Documentation
connected()
bool DataSourceObject::connected () const inline
Definition at line 68 of file DataSourceObject.h.
References Connection.
Referenced by DataSource::connect().
getConnection()
DataConnect* DataSourceObject::getConnection () inline
Definition at line 71 of file DataSourceObject.h.
References Connection.
Referenced by DataConnect::connect(), DataSource::connect(), and IpplParticleBaseDataSource::find_particle_base().
getSource()
DataSource* DataSourceObject::getSource () inline
Definition at line 74 of file DataSourceObject.h.
References Source.
Referenced by DataConnect::connect(), and DataSource::connect().
interact()
virtual void DataSourceObject::interact (const char * = 0) inline virtual
Reimplemented in FileFieldDataSource< T, Dim, M, C >, FileParticleAttribDataSource< T >, and FileIpplParticleBaseDataSource< T >.
Definition at line 93 of file DataSourceObject.h.
update()
virtual bool DataSourceObject::update () inline virtual
Reimplemented in FileFieldDataSource< T, Dim, M, C >, FileParticleAttribDataSource< T >, and FileIpplParticleBaseDataSource< T >.
Definition at line 86 of file DataSourceObject.h.
Member Data Documentation
Connection
DataConnect* DataSourceObject::Connection protected
Definition at line 98 of file DataSourceObject.h.
Referenced by connected(), FileFieldDataSource< T, Dim, M, C >::FileFieldDataSource(), FileIpplParticleBaseDataSource< T >::FileIpplParticleBaseDataSource(), FileParticleAttribDataSource< T >::FileParticleAttribDataSource(), and getConnection().
Source
DataSource* DataSourceObject::Source protected
Definition at line 102 of file DataSourceObject.h.
Referenced by getSource().
TransferMethod
int DataSourceObject::TransferMethod protected
Definition at line 107 of file DataSourceObject.h.
Referenced by FileFieldDataSource< T, Dim, M, C >::FileFieldDataSource(), FileIpplParticleBaseDataSource< T >::FileIpplParticleBaseDataSource(), and FileParticleAttribDataSource< T >::FileParticleAttribDataSource().
The documentation for this class was generated from the following file:
ippl/src/DataSource/DataSourceObject.h