OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Field/AssignGeneralBF.hpp File Reference
AssignGeneralBF.hpp File Reference
#include "Field/Assign.h"
#include "Field/AssignDefs.h"
#include "Field/BareField.h"
#include "Field/BrickExpression.h"
#include "Field/IndexedBareField.h"
#include "Field/LField.h"
#include "Message/Communicate.h"
#include "Message/Message.h"
#include "Utility/PAssert.h"
#include "Utility/IpplInfo.h"
#include "Utility/IpplStats.h"
#include "PETE/IpplExpressions.h"
#include <map>
#include <vector>
#include <functional>
#include <utility>
#include <iostream>
#include <typeinfo>
Functions
template<class T1 , unsigned Dim, class RHS , class Op >
void assign (const BareField< T1, Dim > &clhs, RHS rhsp, Op op, ExprTag< false >)
Function Documentation
assign()
template<class T1 , unsigned Dim, class RHS , class Op > void assign (const BareField< T1, Dim > & clhs, RHS rhsp, Op op, ExprTag< false >)
Definition at line 67 of file AssignGeneralBF.hpp.
References ASSIGNMSG, LField< T, Dim >::begin(), BareField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), IpplInfo::Comm, COMM_ANY_NODE, LField< T, Dim >::Compress(), BareField< T, Dim >::Compress(), BareField< T, Dim >::compressible(), NDIndex< Dim >::contains(), NDIndex< Dim >::containsAllPoints(), Dim, BareField< T, Dim >::end_if(), endl(), F_GEN_ASSIGN_TAG, F_TAG_CYCLE, BareField< T, Dim >::fillGuardCellsIfNotDirty(), LField< T, Dim >::getAllocated(), BareField< T, Dim >::getDomain(), BareField< T, Dim >::getGuardCellSizes(), BareField< T, Dim >::getLayout(), NDIndex< Dim >::getMessage(), IpplInfo::getNodes(), LField< T, Dim >::getOwned(), INFORM_ALL_NODES, NDIndex< Dim >::intersect(), LField< T, Dim >::IsCompressed(), TagMaker::next_tag(), PAssert, PETE_apply(), NDIndex< Dim >::putMessage(), Communicate::receive_block(), Communicate::send(), BareField< T, Dim >::setDirtyFlag(), Message::size(), BareField< T, Dim >::size_if(), FieldLayout< Dim >::touch_range_rdv(), NDIndex< Dim >::touches(), CompressedBrickIterator< T, Dim >::TryCompress(), LField< T, Dim >::Uncompress(), and value_type().