OPAL (Object Oriented Parallel Accelerator Library): EurekaAssign< T > Struct Template Reference
EurekaAssign< T > Struct Template Reference
#include <BCond.hpp>
Public Member Functions
EurekaAssign (int c)
Static Public Member Functions
static const T & get (const T &x, int)
static T & get (T &x, int)
Public Attributes
int m_component
Detailed Description
template<class T>
struct EurekaAssign< T >
Definition at line 5413 of file BCond.hpp.
Constructor & Destructor Documentation
EurekaAssign()
template<class T> EurekaAssign< T >::EurekaAssign (int c) inline
Definition at line 5424 of file BCond.hpp.
Member Function Documentation
get() [1/2]
template<class T> static const T& EurekaAssign< T >::get (const T & x, int) inline static
Definition at line 5415 of file BCond.hpp.
References endl(), and ERRORMSG.
Referenced by PETE_apply().
get() [2/2]
template<class T> static T& EurekaAssign< T >::get (T & x, int) inline static
Definition at line 5419 of file BCond.hpp.
References endl(), and ERRORMSG.
Member Data Documentation
m_component
template<class T> int EurekaAssign< T >::m_component
Definition at line 5423 of file BCond.hpp.
The documentation for this struct was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BCond.hpp