OPAL (Object Oriented Parallel Accelerator Library): Statement Class Reference
Statement Class Reference abstract
Interface for statements.
#include <Statement.h>
Public Types
typedef std::list< Token > TokenList
The type of the enclosed token list.
Public Member Functions
Statement (const std::string &name, int line)
Constructor.
Statement (const std::string &name, TokenList &)
Constructor.
virtual ~Statement ()
void append (const Token &)
Append a token.
bool atEnd () const
Test for end of command.
bool boolean (bool &value)
Return boolean value.
bool delimiter (char c)
Test for delimiter.
bool delimiter (const char *s)
Test for delimiter choice.
virtual void execute (const Parser &)=0
Execute.
Token & getCurrent ()
Return current token and skip it.
bool integer (int &value)
Return signed integer.
bool integer (unsigned &value)
Return unsigned integer.
bool keyword (const char *s)
Test for keyword.
bool real (double &value)
Return real value.
bool str (std::string &value)
Return string value.
bool word (std::string &value)
Return word value.
void mark ()
Mark position in command.
void restore ()
Return to marked position.
void start ()
Return to start.
void skip ()
Skip.
unsigned int position () const
Return current character number in line.
virtual void print (std::ostream &os) const
Print statement.
virtual void printWhere (Inform &msg, bool withToken) const
Print position.
std::string str () const
Protected Attributes
int stat_line
std::string buffer_name
TokenList tokens
TokenList::iterator curr
TokenList::iterator keep
Detailed Description
Interface for statements.
Definition at line 38 of file Statement.h.
Member Typedef Documentation
TokenList
typedef std::list<Token> Statement::TokenList
The type of the enclosed token list.
Definition at line 43 of file Statement.h.
Constructor & Destructor Documentation
Statement() [1/2]
Statement::Statement (const std::string & name, int line)
Constructor.
Definition at line 28 of file Statement.cpp.
Statement() [2/2]
Statement::Statement (const std::string & name, TokenList & list)
Constructor.
Definition at line 33 of file Statement.cpp.
References curr, and tokens.
~Statement()
Statement::~Statement () virtual
Definition at line 40 of file Statement.cpp.
References tokens.
Member Function Documentation
append()
void Statement::append (const Token & token)
Append a token.
Definition at line 45 of file Statement.cpp.
References tokens.
Referenced by IfStatement::IfStatement(), LineTemplate::makeInstance(), OpalParser::parseBracketList(), OpalParser::parseTokenList(), OpalParser::readStatement(), and WhileStatement::WhileStatement().
atEnd()
bool Statement::atEnd () const
Test for end of command.
Definition at line 50 of file Statement.cpp.
References curr, and tokens.
Referenced by MacroCmd::makeTemplate(), OpalParser::parse(), Expressions::parseBracketList(), OpalParser::parseEnd(), LineTemplate::parseTemplate(), Expressions::parseTokenList(), and skip().
boolean()
bool Statement::boolean (bool & value)
Return boolean value.
Definition at line 55 of file Statement.cpp.
References curr, tokens, and word().
Referenced by Expressions::parseRelation().
delimiter() [1/2]
bool Statement::delimiter (char c)
Test for delimiter.
Definition at line 101 of file Statement.cpp.
References Physics::c, curr, and tokens.
Referenced by List::list(), MacroCmd::makeTemplate(), OpalParser::parse(), OpalElement::parse(), Object::parse(), OpalParser::parseAction(), Macro::parseActuals(), Expressions::parseAnd(), Expressions::parseArrayFactor(), Expressions::parseArrayPrimary(), Expressions::parseArrayTerm(), OpalParser::parseAssign(), Expressions::parseBool(), Expressions::parseBoolArray(), Expressions::parseBracketList(), Expressions::parseColumnGenerator(), OpalParser::parseDefine(), Expressions::parseDelimiter(), OpalParser::parseEnd(), Expressions::parseFactor(), Macro::parseFormals(), Line::parseList(), OpalParser::parseMacro(), SequenceParser::parseMember(), Expressions::parsePlace(), SequenceParser::parsePosition(), Expressions::parsePrimary(), Expressions::parseRange(), Expressions::parseReal(), Expressions::parseRealArray(), Expressions::parseReference(), Expressions::parseRelation(), Expressions::parseRowGenerator(), Object::parseShortcut(), Expressions::parseString(), Expressions::parseStringArray(), Expressions::parseStringValue(), Expressions::parseTableGenerator(), Expressions::parseTerm(), and Expressions::parseTokenListArray().
delimiter() [2/2]
bool Statement::delimiter (const char * s)
Test for delimiter choice.
Definition at line 111 of file Statement.cpp.
References curr, and tokens.
execute()
virtual void Statement::execute (const Parser &) pure virtual
Execute.
Implemented in SimpleStatement, CompoundStatement, IfStatement, and WhileStatement.
Referenced by IfStatement::execute(), and WhileStatement::execute().
getCurrent()
Token & Statement::getCurrent ()
Return current token and skip it.
Definition at line 74 of file Statement.cpp.
References curr.
Referenced by MacroCmd::makeTemplate(), OpalParser::parse(), Macro::parseActuals(), Expressions::parseBracketList(), OpalParser::parseMacro(), LineTemplate::parseTemplate(), and Expressions::parseTokenList().
integer() [1/2]
bool Statement::integer (int & value)
Return signed integer.
Definition at line 79 of file Statement.cpp.
References curr, and tokens.
Referenced by List::list(), and Line::parseList().
integer() [2/2]
bool Statement::integer (unsigned & value)
Return unsigned integer.
Definition at line 90 of file Statement.cpp.
References curr, and tokens.
keyword()
bool Statement::keyword (const char * s)
Test for keyword.
Definition at line 121 of file Statement.cpp.
References curr, and tokens.
Referenced by MacroCmd::makeTemplate(), SequenceParser::parse(), OpalParser::parse(), Expressions::parseArrayPrimary(), OpalParser::parseAssign(), OpalParser::parseDefine(), Expressions::parsePlace(), SequenceParser::parsePosition(), Expressions::parseRange(), LineTemplate::parseTemplate(), and SequenceTemplate::parseTemplate().
mark()
void Statement::mark ()
Mark position in command.
Definition at line 170 of file Statement.cpp.
References curr, and keep.
Referenced by OpalParser::parse(), OpalParser::parseMacro(), Expressions::parseRelation(), Object::parseShortcut(), and Expressions::parseTokenList().
position()
unsigned int Statement::position () const
Return current character number in line.
Definition at line 190 of file Statement.cpp.
References Physics::c, curr, and tokens.
Referenced by OpalParser::parse(), and OpalParser::parseEnd().
print()
void Statement::print (std::ostream & os) const virtual
Print statement.
Definition at line 204 of file Statement.cpp.
References Physics::c, endl(), and tokens.
Referenced by IfStatement::execute(), WhileStatement::execute(), operator<<(), OpalParser::parse(), OpalParser::parseEnd(), and str().
printWhere()
void Statement::printWhere (Inform & msg, bool withToken) const virtual
Print position.
Definition at line 217 of file Statement.cpp.
References buffer_name, curr, endl(), stat_line, and tokens.
Referenced by OpalParser::readStatement().
real()
bool Statement::real (double & value)
Return real value.
Definition at line 131 of file Statement.cpp.
References curr, and tokens.
Referenced by Expressions::parseArrayPrimary(), and Expressions::parsePrimary().
restore()
void Statement::restore ()
Return to marked position.
Definition at line 175 of file Statement.cpp.
References curr, and keep.
Referenced by OpalParser::parse(), OpalParser::parseMacro(), Expressions::parseRelation(), Object::parseShortcut(), and Expressions::parseTokenList().
skip()
void Statement::skip ()
Skip.
Definition at line 185 of file Statement.cpp.
References atEnd(), and curr.
start()
void Statement::start ()
Return to start.
Definition at line 180 of file Statement.cpp.
References curr, and tokens.
Referenced by IfStatement::execute(), List::list(), LineTemplate::makeInstance(), SequenceParser::parse(), OpalParser::parse(), OpalParser::parseAction(), OpalParser::parseAssign(), OpalParser::parseDefine(), and OpalParser::readStatement().
str() [1/2]
bool Statement::str (std::string & value)
Return string value.
Definition at line 148 of file Statement.cpp.
References curr, and tokens.
Referenced by Expressions::parseString(), and Expressions::parseStringValue().
str() [2/2]
std::string Statement::str () const
Definition at line 232 of file Statement.cpp.
References print().
word()
bool Statement::word (std::string & value)
Return word value.
Definition at line 159 of file Statement.cpp.
References curr, and tokens.
Referenced by boolean(), Expressions::parseRelation(), Object::parseShortcut(), Expressions::parseString(), and Expressions::parseStringValue().
Member Data Documentation
buffer_name
std::string Statement::buffer_name protected
Definition at line 176 of file Statement.h.
Referenced by CompoundStatement::CompoundStatement(), and printWhere().
curr
TokenList::iterator Statement::curr protected
Definition at line 180 of file Statement.h.
Referenced by atEnd(), boolean(), delimiter(), WhileStatement::execute(), SimpleStatement::execute(), getCurrent(), integer(), keyword(), mark(), position(), printWhere(), real(), restore(), skip(), start(), Statement(), str(), and word().
keep
TokenList::iterator Statement::keep protected
Definition at line 181 of file Statement.h.
Referenced by WhileStatement::execute(), SimpleStatement::execute(), mark(), and restore().
stat_line
int Statement::stat_line protected
Definition at line 173 of file Statement.h.
Referenced by CompoundStatement::CompoundStatement(), and printWhere().
tokens
TokenList Statement::tokens protected
Definition at line 179 of file Statement.h.
Referenced by append(), atEnd(), boolean(), delimiter(), WhileStatement::execute(), SimpleStatement::execute(), integer(), keyword(), position(), print(), printWhere(), real(), start(), Statement(), str(), word(), and ~Statement().
The documentation for this class was generated from the following files:
src/Classic/Parser/Statement.h
src/Classic/Parser/Statement.cpp