OPAL (Object Oriented Parallel Accelerator Library): NamedObj Class Reference
NamedObj Class Reference
#include <NamedObj.h>
Public Member Functions
NamedObj (const char *nm=0)
virtual ~NamedObj ()
const char * name () const
const char * setName (const char *nm=0)
Private Attributes
std::string MyName
Detailed Description
Definition at line 25 of file NamedObj.h.
Constructor & Destructor Documentation
NamedObj()
NamedObj::NamedObj (const char * nm = 0) inline
Definition at line 28 of file NamedObj.h.
References MyName.
~NamedObj()
virtual NamedObj::~NamedObj () inline virtual
Definition at line 32 of file NamedObj.h.
Member Function Documentation
name()
const char* NamedObj::name () const inline
Definition at line 35 of file NamedObj.h.
References MyName.
Referenced by FileFieldDataSource< T, Dim, M, C >::FileFieldDataSource(), FileIpplParticleBaseDataSource< T >::FileIpplParticleBaseDataSource(), FileParticleAttribDataSource< T >::FileParticleAttribDataSource(), and ParticleAttribDataSource::ParticleAttribDataSource().
setName()
const char* NamedObj::setName (const char * nm = 0) inline
Definition at line 38 of file NamedObj.h.
References MyName.
Referenced by ParticleAttribDataSource::ParticleAttribDataSource().
Member Data Documentation
MyName
std::string NamedObj::MyName private
Definition at line 47 of file NamedObj.h.
Referenced by name(), NamedObj(), and setName().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/NamedObj.h