OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyOpalLocalCartesianOffset Namespace Reference
PyOpal::PyOpalLocalCartesianOffset Namespace Reference
Functions
BOOST_PYTHON_MODULE (local_cartesian_offset)
Variables
std::string track_run_docstring = std::string()
const char * module_docstring = "build a local cartesian offset"
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyOpalLocalCartesianOffset::BOOST_PYTHON_MODULE (local_cartesian_offset)
Definition at line 32 of file PyLocalCartesianOffset.cpp.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::addGetOpalElement(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_class(), and PyOpal::ExceptionTranslation::registerExceptions().
Variable Documentation
module_docstring
const char * PyOpal::PyOpalLocalCartesianOffset::module_docstring = "build a local cartesian offset"
Definition at line 15 of file PyLocalCartesianOffset.cpp.
track_run_docstring
std::string PyOpal::PyOpalLocalCartesianOffset::track_run_docstring = std::string()
Definition at line 12 of file PyLocalCartesianOffset.cpp.