OPAL (Object Oriented Parallel Accelerator Library): FFTPACK< T > Class Template Reference
FFTPACK< T > Class Template Reference
#include <fftpack_FFT.h>
Public Types
typedef std::complex< T > Complex_t
Public Member Functions
FFTPACK (void)
~FFTPACK (void)
void setup (unsigned numTransformDims, const int *transformTypes, const int *axisLengths)
void callFFT (unsigned transformDim, int direction, Complex_t *data)
void callFFT (unsigned transformDim, int direction, T *data)
Private Attributes
unsigned numTransformDims_m
int * transformType_m
int * axisLength_m
T ** trig_m
Detailed Description
template<class T>
class FFTPACK< T >
Definition at line 101 of file fftpack_FFT.h.
Member Typedef Documentation
Complex_t
template<class T> typedef std::complex<T> FFTPACK< T >::Complex_t
Definition at line 106 of file fftpack_FFT.h.
Constructor & Destructor Documentation
FFTPACK()
template<class T> FFTPACK< T >::FFTPACK (void) inline
Definition at line 109 of file fftpack_FFT.h.
~FFTPACK()
template<class T > FFTPACK< T >::~FFTPACK (void) inline
Definition at line 141 of file fftpack_FFT.h.
Member Function Documentation
callFFT() [1/2]
template<class T> void FFTPACK< T >::callFFT (unsigned transformDim, int direction, Complex_t * data)
Referenced by FFT< CCTransform, Dim, T >::transform().
callFFT() [2/2]
template<class T > void FFTPACK< T >::callFFT (unsigned transformDim, int direction, T * data) inline
Definition at line 255 of file fftpack_FFT.h.
References abs(), endl(), ERRORMSG, PAssert_EQ, and PAssert_LT.
setup()
template<class T > void FFTPACK< T >::setup (unsigned numTransformDims, const int * transformTypes, const int * axisLengths) inline
Definition at line 153 of file fftpack_FFT.h.
References endl(), ERRORMSG, and Attrib::Legacy::Distribution::T.
Referenced by FFT< CCTransform, Dim, T >::FFT().
Member Data Documentation
axisLength_m
template<class T> int* FFTPACK< T >::axisLength_m private
Definition at line 130 of file fftpack_FFT.h.
numTransformDims_m
template<class T> unsigned FFTPACK< T >::numTransformDims_m private
Definition at line 128 of file fftpack_FFT.h.
transformType_m
template<class T> int* FFTPACK< T >::transformType_m private
Definition at line 129 of file fftpack_FFT.h.
trig_m
template<class T> T** FFTPACK< T >::trig_m private
Definition at line 131 of file fftpack_FFT.h.
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/FFT/fftpack_FFT.h