OPAL (Object Oriented Parallel Accelerator Library): UniformCartesian< Dim, MFLOAT > Class Template Reference
UniformCartesian< Dim, MFLOAT > Class Template Reference
#include <BCond.h>
Public Types
typedef Cell DefaultCentering
typedef MFLOAT MeshValue_t
typedef Vektor< MFLOAT, Dim > MeshVektor_t
Public Types inherited from Mesh< Dim >
enum { Dimension = Dim }
typedef UserList::ID_t ID_t
typedef iterator_user iterator_if
typedef size_type_user size_type_if
Public Member Functions
UniformCartesian ()
~UniformCartesian ()
UniformCartesian (const NDIndex< Dim > &ndi)
UniformCartesian (const Index &I)
UniformCartesian (const Index &I, const Index &J)
UniformCartesian (const Index &I, const Index &J, const Index &K)
UniformCartesian (const NDIndex< Dim > &ndi, MFLOAT *const delX)
UniformCartesian (const Index &I, MFLOAT *const delX)
UniformCartesian (const Index &I, const Index &J, MFLOAT *const delX)
UniformCartesian (const Index &I, const Index &J, const Index &K, MFLOAT *const delX)
UniformCartesian (const NDIndex< Dim > &ndi, MFLOAT *const delX, const Vektor< MFLOAT, Dim > &orig)
UniformCartesian (const Index &I, MFLOAT *const delX, const Vektor< MFLOAT, Dim > &orig)
UniformCartesian (const Index &I, const Index &J, MFLOAT *const delX, const Vektor< MFLOAT, Dim > &orig)
UniformCartesian (const Index &I, const Index &J, const Index &K, MFLOAT *const delX, const Vektor< MFLOAT, Dim > &orig)
void initialize (const NDIndex< Dim > &ndi)
void initialize (const Index &I)
void initialize (const Index &I, const Index &J)
void initialize (const Index &I, const Index &J, const Index &K)
void initialize (const NDIndex< Dim > &ndi, MFLOAT *const delX)
void initialize (const Index &I, MFLOAT *const delX)
void initialize (const Index &I, const Index &J, MFLOAT *const delX)
void initialize (const Index &I, const Index &J, const Index &K, MFLOAT *const delX)
void initialize (const NDIndex< Dim > &ndi, MFLOAT *const delX, const Vektor< MFLOAT, Dim > &orig)
void initialize (const Index &I, MFLOAT *const delX, const Vektor< MFLOAT, Dim > &orig)
void initialize (const Index &I, const Index &J, MFLOAT *const delX, const Vektor< MFLOAT, Dim > &orig)
void initialize (const Index &I, const Index &J, const Index &K, MFLOAT *const delX, const Vektor< MFLOAT, Dim > &orig)
void storeSpacingFields ()
void storeSpacingFields (e_dim_tag p1, int vnodes=-1)
void storeSpacingFields (e_dim_tag p1, e_dim_tag p2, int vnodes=-1)
void storeSpacingFields (e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, int vnodes=-1)
void storeSpacingFields (e_dim_tag *p, int vnodes=-1)
void storeSpacingFields (e_dim_tag p1, unsigned vnodes1, bool recurse=false, int vnodes=-1)
void storeSpacingFields (e_dim_tag p1, e_dim_tag p2, unsigned vnodes1, unsigned vnodes2, bool recurse=false, int vnodes=-1)
void storeSpacingFields (e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, bool recurse=false, int vnodes=-1)
void storeSpacingFields (e_dim_tag *p, unsigned *vnodesPerDirection, bool recurse=false, int vnodes=-1)
Vektor< MFLOAT, Dim > get_origin () const
MFLOAT get_meshSpacing (unsigned d) const
MFLOAT get_volume () const
void set_origin (const Vektor< MFLOAT, Dim > &o)
void set_meshSpacing (MFLOAT *const del)
void print (std::ostream &)
void print (Inform &)
MFLOAT getCellVolume (const NDIndex< Dim > &) const
Field< MFLOAT, Dim, UniformCartesian< Dim, MFLOAT >, Cell > & getCellVolumeField (Field< MFLOAT, Dim, UniformCartesian< Dim, MFLOAT >, Cell > &) const
MFLOAT getVertRangeVolume (const NDIndex< Dim > &) const
MFLOAT getCellRangeVolume (const NDIndex< Dim > &) const
NDIndex< Dim > getNearestVertex (const Vektor< MFLOAT, Dim > &) const
NDIndex< Dim > getVertexBelow (const Vektor< MFLOAT, Dim > &) const
NDIndex< Dim > getCellContaining (const Vektor< MFLOAT, Dim > &x) const
Vektor< MFLOAT, Dim > getVertexPosition (const NDIndex< Dim > &) const
Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Vert > & getVertexPositionField (Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Vert > &) const
Vektor< MFLOAT, Dim > getCellPosition (const NDIndex< Dim > &) const
Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Cell > & getCellPositionField (Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Cell > &) const
Vektor< MFLOAT, Dim > getDeltaVertex (const NDIndex< Dim > &) const
Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Cell > & getDeltaVertexField (Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Cell > &) const
Vektor< MFLOAT, Dim > getDeltaCell (const NDIndex< Dim > &) const
Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Vert > & getDeltaCellField (Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Vert > &) const
Vektor< MFLOAT, Dim > * getSurfaceNormals (const NDIndex< Dim > &) const
void getSurfaceNormalFields (Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Cell > **) const
Vektor< MFLOAT, Dim > getSurfaceNormal (const NDIndex< Dim > &, unsigned) const
Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Cell > & getSurfaceNormalField (Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Cell > &, unsigned) const
Public Member Functions inherited from Mesh< Dim >
Mesh ()
virtual ~Mesh ()
ID_t get_Id () const
void checkin (FieldLayoutUser &f)
void checkout (FieldLayoutUser &f)
size_type_if size_if () const
iterator_if begin_if ()
iterator_if end_if ()
void notifyOfChange ()
Public Attributes
unsigned gridSizes [Dim]
Vektor< MFLOAT, Dim > Dvc [1<< Dim]
bool hasSpacingFields
BareField< Vektor< MFLOAT, Dim >, Dim > * VertSpacings
BareField< Vektor< MFLOAT, Dim >, Dim > * CellSpacings
Private Member Functions
void setup ()
void set_Dvc ()
Private Attributes
MFLOAT meshSpacing [Dim]
MFLOAT volume
Vektor< MFLOAT, Dim > origin
FieldLayout< Dim > * FlCell
FieldLayout< Dim > * FlVert
Additional Inherited Members
Static Public Attributes inherited from Mesh< Dim >
static std::string MeshBC_E_Names [3] = {"Reflective","Periodic ","No BC "}
Detailed Description
template<unsigned Dim, class MFLOAT = double>
class UniformCartesian< Dim, MFLOAT >
Definition at line 24 of file BCond.h.
Member Typedef Documentation
DefaultCentering
template<unsigned Dim, class MFLOAT = double> typedef Cell UniformCartesian< Dim, MFLOAT >::DefaultCentering
Definition at line 37 of file UniformCartesian.h.
MeshValue_t
template<unsigned Dim, class MFLOAT = double> typedef MFLOAT UniformCartesian< Dim, MFLOAT >::MeshValue_t
Definition at line 38 of file UniformCartesian.h.
MeshVektor_t
template<unsigned Dim, class MFLOAT = double> typedef Vektor<MFLOAT,Dim> UniformCartesian< Dim, MFLOAT >::MeshVektor_t
Definition at line 39 of file UniformCartesian.h.
Constructor & Destructor Documentation
UniformCartesian() [1/13]
template<unsigned Dim, class MFLOAT = double> UniformCartesian< Dim, MFLOAT >::UniformCartesian () inline
Definition at line 42 of file UniformCartesian.h.
References UniformCartesian< Dim, MFLOAT >::hasSpacingFields.
~UniformCartesian()
template<unsigned Dim, class MFLOAT = double> UniformCartesian< Dim, MFLOAT >::~UniformCartesian () inline
Definition at line 47 of file UniformCartesian.h.
References UniformCartesian< Dim, MFLOAT >::CellSpacings, UniformCartesian< Dim, MFLOAT >::FlCell, UniformCartesian< Dim, MFLOAT >::FlVert, UniformCartesian< Dim, MFLOAT >::hasSpacingFields, and UniformCartesian< Dim, MFLOAT >::VertSpacings.
UniformCartesian() [2/13]
template<unsigned Dim, class MFLOAT > UniformCartesian< Dim, MFLOAT >::UniformCartesian (const NDIndex< Dim > & ndi)
Definition at line 41 of file UniformCartesian.hpp.
References Dim.
UniformCartesian() [3/13]
template<unsigned Dim, class MFLOAT > UniformCartesian< Dim, MFLOAT >::UniformCartesian (const Index & I)
Definition at line 84 of file UniformCartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, and Index::stride().
UniformCartesian() [4/13]
template<unsigned Dim, class MFLOAT > UniformCartesian< Dim, MFLOAT >::UniformCartesian (const Index & I, const Index & J)
Definition at line 123 of file UniformCartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, and Index::stride().
UniformCartesian() [5/13]
template<unsigned Dim, class MFLOAT > UniformCartesian< Dim, MFLOAT >::UniformCartesian (const Index & I, const Index & J, const Index & K)
Definition at line 167 of file UniformCartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, and Index::stride().
UniformCartesian() [6/13]
template<unsigned Dim, class MFLOAT > UniformCartesian< Dim, MFLOAT >::UniformCartesian (const NDIndex< Dim > & ndi, MFLOAT *const delX)
Definition at line 55 of file UniformCartesian.hpp.
References Dim.
UniformCartesian() [7/13]
template<unsigned Dim, class MFLOAT > UniformCartesian< Dim, MFLOAT >::UniformCartesian (const Index & I, MFLOAT *const delX)
Definition at line 98 of file UniformCartesian.hpp.
References Dim, Index::first(), Index::length(), and PInsist.
UniformCartesian() [8/13]
template<unsigned Dim, class MFLOAT > UniformCartesian< Dim, MFLOAT >::UniformCartesian (const Index & I, const Index & J, MFLOAT *const delX)
Definition at line 140 of file UniformCartesian.hpp.
References Dim, Index::first(), Index::length(), and PInsist.
UniformCartesian() [9/13]
template<unsigned Dim, class MFLOAT > UniformCartesian< Dim, MFLOAT >::UniformCartesian (const Index & I, const Index & J, const Index & K, MFLOAT *const delX)
Definition at line 187 of file UniformCartesian.hpp.
References Dim, Index::first(), Index::length(), and PInsist.
UniformCartesian() [10/13]
template<unsigned Dim, class MFLOAT > UniformCartesian< Dim, MFLOAT >::UniformCartesian (const NDIndex< Dim > & ndi, MFLOAT *const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 67 of file UniformCartesian.hpp.
References Dim.
UniformCartesian() [11/13]
template<unsigned Dim, class MFLOAT > UniformCartesian< Dim, MFLOAT >::UniformCartesian (const Index & I, MFLOAT *const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 110 of file UniformCartesian.hpp.
References Dim, Index::length(), and PInsist.
UniformCartesian() [12/13]
template<unsigned Dim, class MFLOAT > UniformCartesian< Dim, MFLOAT >::UniformCartesian (const Index & I, const Index & J, MFLOAT *const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 153 of file UniformCartesian.hpp.
References Dim, Index::length(), and PInsist.
UniformCartesian() [13/13]
template<unsigned Dim, class MFLOAT > UniformCartesian< Dim, MFLOAT >::UniformCartesian (const Index & I, const Index & J, const Index & K, MFLOAT *const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 203 of file UniformCartesian.hpp.
References Dim, Index::length(), and PInsist.
Member Function Documentation
get_meshSpacing()
template<unsigned Dim, class MFLOAT > MFLOAT UniformCartesian< Dim, MFLOAT >::get_meshSpacing (unsigned d) const
Definition at line 461 of file UniformCartesian.hpp.
References Dim, and PAssert_LT.
Referenced by FFTBoxPoissonSolver::FFTBoxPoissonSolver(), P3MPoissonSolver::initializeFields(), FFTPoissonSolver::initializeFields(), and MGPoissonSolver::MGPoissonSolver().
get_origin()
template<unsigned Dim, class MFLOAT > Vektor< MFLOAT, Dim > UniformCartesian< Dim, MFLOAT >::get_origin () const
Definition at line 420 of file UniformCartesian.hpp.
get_volume()
template<unsigned Dim, class MFLOAT > MFLOAT UniformCartesian< Dim, MFLOAT >::get_volume () const
Definition at line 471 of file UniformCartesian.hpp.
getCellContaining()
template<unsigned Dim, class MFLOAT = double> NDIndex<Dim> UniformCartesian< Dim, MFLOAT >::getCellContaining (const Vektor< MFLOAT, Dim > & x) const inline
Definition at line 197 of file UniformCartesian.h.
References UniformCartesian< Dim, MFLOAT >::getVertexBelow().
getCellPosition()
template<unsigned Dim, class MFLOAT > Vektor< MFLOAT, Dim > UniformCartesian< Dim, MFLOAT >::getCellPosition (const NDIndex< Dim > & ndi) const
Definition at line 1065 of file UniformCartesian.hpp.
References Dim, endl(), and ERRORMSG.
getCellPositionField()
template<unsigned Dim, class MFLOAT > Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Cell > & UniformCartesian< Dim, MFLOAT >::getCellPositionField (Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Cell > & cellPositions) const
Definition at line 1083 of file UniformCartesian.hpp.
References BareField< T, Dim >::begin(), and Dim.
getCellRangeVolume()
template<unsigned Dim, class MFLOAT > MFLOAT UniformCartesian< Dim, MFLOAT >::getCellRangeVolume (const NDIndex< Dim > & ndi) const
Definition at line 962 of file UniformCartesian.hpp.
References abs(), and Dim.
getCellVolume()
template<unsigned Dim, class MFLOAT > MFLOAT UniformCartesian< Dim, MFLOAT >::getCellVolume (const NDIndex< Dim > & ndi) const
Definition at line 915 of file UniformCartesian.hpp.
References Dim, endl(), and ERRORMSG.
getCellVolumeField()
template<unsigned Dim, class MFLOAT > Field< MFLOAT, Dim, UniformCartesian< Dim, MFLOAT >, Cell > & UniformCartesian< Dim, MFLOAT >::getCellVolumeField (Field< MFLOAT, Dim, UniformCartesian< Dim, MFLOAT >, Cell > & volumes) const
Definition at line 928 of file UniformCartesian.hpp.
getDeltaCell()
template<unsigned Dim, class MFLOAT > Vektor< MFLOAT, Dim > UniformCartesian< Dim, MFLOAT >::getDeltaCell (const NDIndex< Dim > & ndi) const
Definition at line 1132 of file UniformCartesian.hpp.
References Dim.
getDeltaCellField()
template<unsigned Dim, class MFLOAT > Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Vert > & UniformCartesian< Dim, MFLOAT >::getDeltaCellField (Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Vert > & cellSpacings) const
Definition at line 1145 of file UniformCartesian.hpp.
References Dim.
getDeltaVertex()
template<unsigned Dim, class MFLOAT > Vektor< MFLOAT, Dim > UniformCartesian< Dim, MFLOAT >::getDeltaVertex (const NDIndex< Dim > & ndi) const
Definition at line 1105 of file UniformCartesian.hpp.
References Dim.
getDeltaVertexField()
template<unsigned Dim, class MFLOAT > Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Cell > & UniformCartesian< Dim, MFLOAT >::getDeltaVertexField (Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Cell > & vertexSpacings) const
Definition at line 1118 of file UniformCartesian.hpp.
References Dim.
getNearestVertex()
template<unsigned Dim, class MFLOAT > NDIndex< Dim > UniformCartesian< Dim, MFLOAT >::getNearestVertex (const Vektor< MFLOAT, Dim > & x) const
Definition at line 987 of file UniformCartesian.hpp.
References Dim.
getSurfaceNormal()
template<unsigned Dim, class MFLOAT > Vektor< MFLOAT, Dim > UniformCartesian< Dim, MFLOAT >::getSurfaceNormal (const NDIndex< Dim > & , unsigned face) const
Definition at line 1202 of file UniformCartesian.hpp.
References Dim.
getSurfaceNormalField()
template<unsigned Dim, class MFLOAT > Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Cell > & UniformCartesian< Dim, MFLOAT >::getSurfaceNormalField (Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Cell > & surfaceNormalField, unsigned face) const
Definition at line 1233 of file UniformCartesian.hpp.
References Dim.
getSurfaceNormalFields()
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::getSurfaceNormalFields (Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Cell > ** surfaceNormalsFields) const
Definition at line 1176 of file UniformCartesian.hpp.
References assign(), and Dim.
getSurfaceNormals()
template<unsigned Dim, class MFLOAT > Vektor< MFLOAT, Dim > * UniformCartesian< Dim, MFLOAT >::getSurfaceNormals (const NDIndex< Dim > &) const
Definition at line 1158 of file UniformCartesian.hpp.
References Dim.
getVertexBelow()
template<unsigned Dim, class MFLOAT > NDIndex< Dim > UniformCartesian< Dim, MFLOAT >::getVertexBelow (const Vektor< MFLOAT, Dim > & x) const
Definition at line 1006 of file UniformCartesian.hpp.
References Dim.
Referenced by UniformCartesian< Dim, MFLOAT >::getCellContaining().
getVertexPosition()
template<unsigned Dim, class MFLOAT > Vektor< MFLOAT, Dim > UniformCartesian< Dim, MFLOAT >::getVertexPosition (const NDIndex< Dim > & ndi) const
Definition at line 1025 of file UniformCartesian.hpp.
References Dim, endl(), and ERRORMSG.
getVertexPositionField()
template<unsigned Dim, class MFLOAT > Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Vert > & UniformCartesian< Dim, MFLOAT >::getVertexPositionField (Field< Vektor< MFLOAT, Dim >, Dim, UniformCartesian< Dim, MFLOAT >, Vert > & vertexPositions) const
Definition at line 1043 of file UniformCartesian.hpp.
References BareField< T, Dim >::begin(), and Dim.
getVertRangeVolume()
template<unsigned Dim, class MFLOAT > MFLOAT UniformCartesian< Dim, MFLOAT >::getVertRangeVolume (const NDIndex< Dim > & ndi) const
Definition at line 938 of file UniformCartesian.hpp.
References abs(), and Dim.
initialize() [1/12]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::initialize (const NDIndex< Dim > & ndi)
Definition at line 221 of file UniformCartesian.hpp.
References Dim.
initialize() [2/12]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::initialize (const Index & I)
Definition at line 267 of file UniformCartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, and Index::stride().
initialize() [3/12]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::initialize (const Index & I, const Index & J)
Definition at line 309 of file UniformCartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, and Index::stride().
initialize() [4/12]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::initialize (const Index & I, const Index & J, const Index & K)
Definition at line 356 of file UniformCartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, and Index::stride().
initialize() [5/12]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::initialize (const NDIndex< Dim > & ndi, MFLOAT *const delX)
Definition at line 236 of file UniformCartesian.hpp.
References Dim.
initialize() [6/12]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::initialize (const Index & I, MFLOAT *const delX)
Definition at line 282 of file UniformCartesian.hpp.
References Dim, Index::first(), Index::length(), and PInsist.
initialize() [7/12]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::initialize (const Index & I, const Index & J, MFLOAT *const delX)
Definition at line 327 of file UniformCartesian.hpp.
References Dim, Index::first(), Index::length(), and PInsist.
initialize() [8/12]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::initialize (const Index & I, const Index & J, const Index & K, MFLOAT *const delX)
Definition at line 377 of file UniformCartesian.hpp.
References Dim, Index::first(), Index::length(), and PInsist.
initialize() [9/12]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::initialize (const NDIndex< Dim > & ndi, MFLOAT *const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 249 of file UniformCartesian.hpp.
References Dim.
initialize() [10/12]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::initialize (const Index & I, MFLOAT *const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 295 of file UniformCartesian.hpp.
References Dim, Index::length(), and PInsist.
initialize() [11/12]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::initialize (const Index & I, const Index & J, MFLOAT *const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 341 of file UniformCartesian.hpp.
References Dim, Index::length(), and PInsist.
initialize() [12/12]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::initialize (const Index & I, const Index & J, const Index & K, MFLOAT *const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 394 of file UniformCartesian.hpp.
References Dim, Index::length(), and PInsist.
print() [1/2]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::print (std::ostream & out)
Definition at line 883 of file UniformCartesian.hpp.
References Options::info.
Referenced by operator<<().
print() [2/2]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::print (Inform & out)
Definition at line 892 of file UniformCartesian.hpp.
References Dim.
set_Dvc()
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::set_Dvc () private
Definition at line 444 of file UniformCartesian.hpp.
References Dim.
set_meshSpacing()
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::set_meshSpacing (MFLOAT *const del)
Definition at line 428 of file UniformCartesian.hpp.
References Dim.
Referenced by PartBunch::resizeMesh(), and PartBunch::updateFields().
set_origin()
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::set_origin (const Vektor< MFLOAT, Dim > & o)
Definition at line 412 of file UniformCartesian.hpp.
Referenced by PartBunch::resizeMesh(), and PartBunch::updateFields().
setup()
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::setup (void) private
Definition at line 26 of file UniformCartesian.hpp.
storeSpacingFields() [1/9]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::storeSpacingFields ()
Definition at line 502 of file UniformCartesian.hpp.
References Dim, and PARALLEL.
storeSpacingFields() [2/9]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag p1, int vnodes = -1)
Definition at line 512 of file UniformCartesian.hpp.
storeSpacingFields() [3/9]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag p1, e_dim_tag p2, int vnodes = -1)
Definition at line 521 of file UniformCartesian.hpp.
storeSpacingFields() [4/9]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, int vnodes = -1)
Definition at line 531 of file UniformCartesian.hpp.
storeSpacingFields() [5/9]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag * p, int vnodes = -1)
Definition at line 542 of file UniformCartesian.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), Dim, BareField< T, Dim >::end_if(), BareField< T, Dim >::fillGuardCells(), LField< T, Dim >::getAllocated(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), min(), NDIndex< Dim >::plugBase(), BareField< T, Dim >::rightGuard(), Attrib::Legacy::Distribution::T, and NDIndex< Dim >::touches().
storeSpacingFields() [6/9]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag p1, unsigned vnodes1, bool recurse = false, int vnodes = -1)
Definition at line 689 of file UniformCartesian.hpp.
References Dim.
storeSpacingFields() [7/9]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag p1, e_dim_tag p2, unsigned vnodes1, unsigned vnodes2, bool recurse = false, int vnodes = -1)
Definition at line 702 of file UniformCartesian.hpp.
References Dim.
storeSpacingFields() [8/9]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, bool recurse = false, int vnodes = -1)
Definition at line 716 of file UniformCartesian.hpp.
References Dim.
storeSpacingFields() [9/9]
template<unsigned Dim, class MFLOAT > void UniformCartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag * p, unsigned * vnodesPerDirection, bool recurse = false, int vnodes = -1)
Definition at line 736 of file UniformCartesian.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), Dim, BareField< T, Dim >::end_if(), BareField< T, Dim >::fillGuardCells(), LField< T, Dim >::getAllocated(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), min(), NDIndex< Dim >::plugBase(), BareField< T, Dim >::rightGuard(), Attrib::Legacy::Distribution::T, and NDIndex< Dim >::touches().
Member Data Documentation
CellSpacings
template<unsigned Dim, class MFLOAT = double> BareField<Vektor<MFLOAT,Dim>,Dim>* UniformCartesian< Dim, MFLOAT >::CellSpacings
Definition at line 122 of file UniformCartesian.h.
Referenced by UniformCartesian< Dim, MFLOAT >::~UniformCartesian().
Dvc
template<unsigned Dim, class MFLOAT = double> Vektor<MFLOAT,Dim> UniformCartesian< Dim, MFLOAT >::Dvc[1<< Dim]
Definition at line 119 of file UniformCartesian.h.
FlCell
template<unsigned Dim, class MFLOAT = double> FieldLayout<Dim>* UniformCartesian< Dim, MFLOAT >::FlCell private
Definition at line 106 of file UniformCartesian.h.
Referenced by UniformCartesian< Dim, MFLOAT >::~UniformCartesian().
FlVert
template<unsigned Dim, class MFLOAT = double> FieldLayout<Dim>* UniformCartesian< Dim, MFLOAT >::FlVert private
Definition at line 107 of file UniformCartesian.h.
Referenced by UniformCartesian< Dim, MFLOAT >::~UniformCartesian().
gridSizes
template<unsigned Dim, class MFLOAT = double> unsigned UniformCartesian< Dim, MFLOAT >::gridSizes[Dim]
Definition at line 118 of file UniformCartesian.h.
hasSpacingFields
template<unsigned Dim, class MFLOAT = double> bool UniformCartesian< Dim, MFLOAT >::hasSpacingFields
Definition at line 120 of file UniformCartesian.h.
Referenced by UniformCartesian< Dim, MFLOAT >::UniformCartesian(), and UniformCartesian< Dim, MFLOAT >::~UniformCartesian().
meshSpacing
template<unsigned Dim, class MFLOAT = double> MFLOAT UniformCartesian< Dim, MFLOAT >::meshSpacing[Dim] private
Definition at line 103 of file UniformCartesian.h.
origin
template<unsigned Dim, class MFLOAT = double> Vektor<MFLOAT,Dim> UniformCartesian< Dim, MFLOAT >::origin private
Definition at line 105 of file UniformCartesian.h.
VertSpacings
template<unsigned Dim, class MFLOAT = double> BareField<Vektor<MFLOAT,Dim>,Dim>* UniformCartesian< Dim, MFLOAT >::VertSpacings
Definition at line 121 of file UniformCartesian.h.
Referenced by UniformCartesian< Dim, MFLOAT >::~UniformCartesian().
volume
template<unsigned Dim, class MFLOAT = double> MFLOAT UniformCartesian< Dim, MFLOAT >::volume private
Definition at line 104 of file UniformCartesian.h.
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BCond.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Meshes/UniformCartesian.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Meshes/UniformCartesian.hpp