OPAL (Object Oriented Parallel Accelerator Library): LOMB_class Class Reference
LOMB_class Class Reference
#include <lomb.h>
Public Member Functions
LOMB_class (int)
virtual ~LOMB_class (void)
int period (std::vector< LOMB_TYPE > *indata, std::vector< LOMB_TYPE > *outdata, double ofac, double hifac, int *nout, int *jmax, double *prob, int amp)
int avevar (std::vector< LOMB_TYPE > *data, double *ave, double *var)
double signi (double *peak, int *nout, double *ofac)
int moment (std::vector< LOMB_TYPE > *indata, double *ave, double *adev, double *sdev, double *var, double *skew, double *curt)
Detailed Description
Definition at line 27 of file lomb.h.
Constructor & Destructor Documentation
LOMB_class()
LOMB_class::LOMB_class (int) explicit
Definition at line 14 of file lomb.cpp.
~LOMB_class()
LOMB_class::~LOMB_class (void) virtual
Definition at line 23 of file lomb.cpp.
Member Function Documentation
avevar()
int LOMB_class::avevar (std::vector< LOMB_TYPE > * data, double * ave, double * var)
Definition at line 175 of file lomb.cpp.
References Hypervolume::n.
Referenced by period().
moment()
int LOMB_class::moment (std::vector< LOMB_TYPE > * indata, double * ave, double * adev, double * sdev, double * var, double * skew, double * curt)
Definition at line 248 of file lomb.cpp.
References abs(), Hypervolume::n, pow(), and sqrt().
period()
int LOMB_class::period (std::vector< LOMB_TYPE > * indata, std::vector< LOMB_TYPE > * outdata, double ofac, double hifac, int * nout, int * jmax, double * prob, int amp)
Definition at line 34 of file lomb.cpp.
References arg(), atan2(), avevar(), Physics::c, cos(), exp(), Hypervolume::n, pow(), sin(), sqrt(), Physics::two_pi, LOMB_TYPE::x, and LOMB_TYPE::y.
signi()
double LOMB_class::signi (double * peak, int * nout, double * ofac)
Definition at line 221 of file lomb.cpp.
References exp(), and pow().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Algorithms/lomb.h
/psi/home/gsell/data/src/OPAL/src/src/Algorithms/lomb.cpp