OPAL (Object Oriented Parallel Accelerator Library): FileIpplParticleBaseDataSource< T > Class Template Reference
FileIpplParticleBaseDataSource< T > Class Template Reference
#include <FilePtclBaseDataSource.h>
Public Member Functions
FileIpplParticleBaseDataSource (const char *, DataConnect *, int, IpplParticleBase< T > &)
virtual ~FileIpplParticleBaseDataSource ()
virtual bool update ()
virtual void interact (const char *=0)
Public Member Functions inherited from DataSourceObject
DataSourceObject (const char *nm, DataSource *ds, DataConnect *dc, int tm)
DataSourceObject ()
virtual ~DataSourceObject ()
bool connected () const
DataConnect * getConnection ()
DataSource * getSource ()
Public Member Functions inherited from NamedObj
NamedObj (const char *nm=0)
virtual ~NamedObj ()
const char * name () const
const char * setName (const char *nm=0)
Private Attributes
DiscParticle * DP
IpplParticleBase< T > & MyParticles
int counter
Additional Inherited Members
Protected Attributes inherited from DataSourceObject
DataConnect * Connection
DataSource * Source
int TransferMethod
Detailed Description
template<class T>
class FileIpplParticleBaseDataSource< T >
Definition at line 31 of file FilePtclBaseDataSource.h.
Constructor & Destructor Documentation
FileIpplParticleBaseDataSource()
template<class T > FileIpplParticleBaseDataSource< T >::FileIpplParticleBaseDataSource (const char * nm, DataConnect * dc, int tm, IpplParticleBase< T > & P)
Definition at line 36 of file FilePtclBaseDataSource.hpp.
References DataSourceObject::Connection, FileIpplParticleBaseDataSource< T >::DP, DataConnect::DSID(), endl(), ERRORMSG, FileDataConnect::getTypeString(), DiscParticle::INPUT, DataSource::INPUT, NamedObj::name(), DiscParticle::OUTPUT, DataSource::OUTPUT, and DataSourceObject::TransferMethod.
~FileIpplParticleBaseDataSource()
template<class T > FileIpplParticleBaseDataSource< T >::~FileIpplParticleBaseDataSource () virtual
Definition at line 61 of file FilePtclBaseDataSource.hpp.
Member Function Documentation
interact()
template<class T > void FileIpplParticleBaseDataSource< T >::interact (const char * = 0) virtual
Reimplemented from DataSourceObject.
Definition at line 89 of file FilePtclBaseDataSource.hpp.
update()
template<class T > bool FileIpplParticleBaseDataSource< T >::update () virtual
Reimplemented from DataSourceObject.
Definition at line 72 of file FilePtclBaseDataSource.hpp.
References DataSource::INPUT, and DataSource::OUTPUT.
Member Data Documentation
counter
template<class T> int FileIpplParticleBaseDataSource< T >::counter private
Definition at line 63 of file FilePtclBaseDataSource.h.
DP
template<class T> DiscParticle* FileIpplParticleBaseDataSource< T >::DP private
Definition at line 57 of file FilePtclBaseDataSource.h.
Referenced by FileIpplParticleBaseDataSource< T >::FileIpplParticleBaseDataSource().
MyParticles
template<class T> IpplParticleBase<T>& FileIpplParticleBaseDataSource< T >::MyParticles private
Definition at line 60 of file FilePtclBaseDataSource.h.
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/FilePtclBaseDataSource.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/FilePtclBaseDataSource.hpp