OPAL (Object Oriented Parallel Accelerator Library): Astra1DDynamic_fast Class Reference
Astra1DDynamic_fast Class Reference
#include <Astra1DDynamic_fast.h>
Public Member Functions
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const
virtual bool getFieldDerivative (const Vector_t &R, Vector_t &E, Vector_t &B, const DiffDirection &dir) const
virtual void getFieldDimensions (double &zBegin, double &zEnd) const
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const
virtual void swap ()
virtual void getInfo (Inform *)
virtual double getFrequency () const
virtual void setFrequency (double freq)
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &F)
Public Member Functions inherited from Astra1D_fast
virtual bool isInside (const Vector_t &r) const
Public Member Functions inherited from Fieldmap
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Private Member Functions
Astra1DDynamic_fast (std::string aFilename)
virtual ~Astra1DDynamic_fast ()
virtual void readMap ()
bool readFileHeader (std::ifstream &file)
int stripFileHeader (std::ifstream &file)
Private Attributes
double frequency_m
double xlrep_m
Friends
class Fieldmap
Additional Inherited Members
Static Public Member Functions inherited from Fieldmap
static Fieldmap * getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions inherited from Astra1D_fast
Astra1D_fast (std::string aFilename)
virtual ~Astra1D_fast ()
virtual void freeMap ()
bool determineNumSamplingPoints (std::ifstream &file)
double readFieldData (std::ifstream &file)
void normalizeFieldData (double maxEz)
std::vector< double > getEvenlyDistributedSamplingPoints ()
std::vector< double > interpolateFieldData (std::vector< double > &samplingPoints)
void computeFieldDerivatives (std::vector< double > &fourierComponents, int accuracy)
std::vector< double > computeFourierCoefficients (int accuracy, std::vector< double > &evenSampling)
Protected Member Functions inherited from Fieldmap
Fieldmap ()=delete
Fieldmap (const std::string &aFilename)
virtual ~Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions inherited from Fieldmap
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes inherited from Astra1D_fast
double * onAxisField_m
double * zvals_m
gsl_spline * onAxisInterpolants_m [4]
gsl_interp_accel * onAxisAccel_m [4]
double hz_m
double zbegin_m
double zend_m
double length_m
int num_gridpz_m
int numHeaderLines_m
Protected Attributes inherited from Fieldmap
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Detailed Description
Definition at line 27 of file Astra1DDynamic_fast.h.
Constructor & Destructor Documentation
Astra1DDynamic_fast()
Astra1DDynamic_fast::Astra1DDynamic_fast (std::string aFilename) private
Definition at line 31 of file Astra1DDynamic_fast.cpp.
References Physics::c, Astra1D_fast::determineNumSamplingPoints(), Fieldmap::disableFieldmapWarning(), Physics::e, Fieldmap::Filename_m, frequency_m, Astra1D_fast::hz_m, Astra1D_fast::length_m, Fieldmap::noFieldmapWarning(), Astra1D_fast::num_gridpz_m, Astra1D_fast::numHeaderLines_m, Astra1D_fast::onAxisField_m, readFileHeader(), TAstraDynamic, Physics::two_pi, Fieldmap::Type, xlrep_m, Astra1D_fast::zbegin_m, and Astra1D_fast::zend_m.
~Astra1DDynamic_fast()
Astra1DDynamic_fast::~Astra1DDynamic_fast () private virtual
Definition at line 69 of file Astra1DDynamic_fast.cpp.
References Astra1D_fast::freeMap().
Member Function Documentation
getFieldDerivative()
bool Astra1DDynamic_fast::getFieldDerivative (const Vector_t & R, Vector_t & E, Vector_t & B, const DiffDirection & dir) const virtual
Implements Astra1D_fast.
Definition at line 133 of file Astra1DDynamic_fast.cpp.
References Astra1D_fast::onAxisAccel_m, Astra1D_fast::onAxisInterpolants_m, Attrib::Distribution::R, and Astra1D_fast::zbegin_m.
getFieldDimensions() [1/2]
void Astra1DDynamic_fast::getFieldDimensions (double & zBegin, double & zEnd) const virtual
Implements Astra1D_fast.
Definition at line 141 of file Astra1DDynamic_fast.cpp.
References Astra1D_fast::zbegin_m, and Astra1D_fast::zend_m.
getFieldDimensions() [2/2]
void Astra1DDynamic_fast::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const virtual
Implements Astra1D_fast.
Definition at line 146 of file Astra1DDynamic_fast.cpp.
getFieldstrength()
bool Astra1DDynamic_fast::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const virtual
Implements Astra1D_fast.
Definition at line 103 of file Astra1DDynamic_fast.cpp.
References Physics::c, Physics::e, Astra1D_fast::onAxisAccel_m, Astra1D_fast::onAxisInterpolants_m, Attrib::Distribution::R, xlrep_m, and Astra1D_fast::zbegin_m.
getFrequency()
double Astra1DDynamic_fast::getFrequency () const virtual
Implements Astra1D_fast.
Definition at line 155 of file Astra1DDynamic_fast.cpp.
References frequency_m.
getInfo()
void Astra1DDynamic_fast::getInfo (Inform * msg) virtual
Implements Astra1D_fast.
Definition at line 151 of file Astra1DDynamic_fast.cpp.
References endl(), Fieldmap::Filename_m, Astra1D_fast::zbegin_m, and Astra1D_fast::zend_m.
getOnaxisEz()
void Astra1DDynamic_fast::getOnaxisEz (std::vector< std::pair< double, double > > & F) virtual
Reimplemented from Astra1D_fast.
Definition at line 163 of file Astra1DDynamic_fast.cpp.
References abs(), Fieldmap::Filename_m, Astra1D_fast::hz_m, Astra1D_fast::num_gridpz_m, Astra1D_fast::onAxisField_m, and Astra1D_fast::zvals_m.
readFileHeader()
bool Astra1DDynamic_fast::readFileHeader (std::ifstream & file) private
Definition at line 197 of file Astra1DDynamic_fast.cpp.
References Physics::e, frequency_m, Fieldmap::normalize_m, and Util::toUpper().
Referenced by Astra1DDynamic_fast().
readMap()
void Astra1DDynamic_fast::readMap () private virtual
Reimplemented from Astra1D_fast.
Definition at line 73 of file Astra1DDynamic_fast.cpp.
References Fieldmap::checkMap(), Astra1D_fast::computeFieldDerivatives(), Astra1D_fast::computeFourierCoefficients(), Physics::e, endl(), Fieldmap::Filename_m, Astra1D_fast::getEvenlyDistributedSamplingPoints(), INFOMSG, Astra1D_fast::interpolateFieldData(), Astra1D_fast::length_m, level3(), Astra1D_fast::normalizeFieldData(), Astra1D_fast::num_gridpz_m, Astra1D_fast::onAxisAccel_m, Astra1D_fast::onAxisField_m, Astra1D_fast::onAxisInterpolants_m, Astra1D_fast::readFieldData(), stripFileHeader(), Fieldmap::typeset_msg(), and Astra1D_fast::zvals_m.
setFrequency()
void Astra1DDynamic_fast::setFrequency (double freq) virtual
Implements Astra1D_fast.
Definition at line 159 of file Astra1DDynamic_fast.cpp.
References frequency_m.
stripFileHeader()
int Astra1DDynamic_fast::stripFileHeader (std::ifstream & file) private
Definition at line 222 of file Astra1DDynamic_fast.cpp.
References Physics::e.
Referenced by readMap().
swap()
void Astra1DDynamic_fast::swap () virtual
Implements Astra1D_fast.
Definition at line 148 of file Astra1DDynamic_fast.cpp.
Friends And Related Function Documentation
Fieldmap
friend class Fieldmap friend
Definition at line 52 of file Astra1DDynamic_fast.h.
Member Data Documentation
frequency_m
double Astra1DDynamic_fast::frequency_m private
Definition at line 49 of file Astra1DDynamic_fast.h.
Referenced by Astra1DDynamic_fast(), getFrequency(), readFileHeader(), and setFrequency().
xlrep_m
double Astra1DDynamic_fast::xlrep_m private
Definition at line 50 of file Astra1DDynamic_fast.h.
Referenced by Astra1DDynamic_fast(), and getFieldstrength().
The documentation for this class was generated from the following files:
src/Classic/Fields/Astra1DDynamic_fast.h
src/Classic/Fields/Astra1DDynamic_fast.cpp