OPAL (Object Oriented Parallel Accelerator Library): Voxel Class Reference
Voxel Class Reference
Public Member Functions
Voxel ()
Voxel (const Vector_t &min, const Vector_t &max)
void scale (const Vector_t &scale)
bool intersect (const Ray &r, double &tmin, double &tmax) const
bool intersect (const Ray &r) const
int intersect (const Triangle &t) const
Vector_t extent () const
bool isInside (const Vector_t &P) const
Public Attributes
Vector_t pts [2]
Detailed Description
Definition at line 608 of file BoundaryGeometry.cpp.
Constructor & Destructor Documentation
Voxel() [1/2]
Voxel::Voxel () inline
Definition at line 610 of file BoundaryGeometry.cpp.
Voxel() [2/2]
Voxel::Voxel (const Vector_t & min, const Vector_t & max) inline
Definition at line 611 of file BoundaryGeometry.cpp.
References max(), min(), and pts.
Member Function Documentation
extent()
Vector_t Voxel::extent () const inline
Definition at line 674 of file BoundaryGeometry.cpp.
References pts.
Referenced by intersect().
intersect() [1/3]
bool Voxel::intersect (const Ray & r, double & tmin, double & tmax) const inline
Definition at line 627 of file BoundaryGeometry.cpp.
References cmp_diff::ge_zero(), cmp_diff::gt(), Ray::inv_direction, cmp_diff::lt(), Ray::origin, pts, and Ray::sign.
Referenced by intersect(), BoundaryGeometry::intersectTinyLineSegmentBoundary(), and BoundaryGeometry::intersectTriangleVoxel().
intersect() [2/3]
bool Voxel::intersect (const Ray & r) const inline
Definition at line 655 of file BoundaryGeometry.cpp.
References intersect().
intersect() [3/3]
int Voxel::intersect (const Triangle & t) const inline
Definition at line 663 of file BoundaryGeometry.cpp.
References extent(), pts, Triangle::scale(), and scale().
isInside()
bool Voxel::isInside (const Vector_t & P) const inline
Definition at line 678 of file BoundaryGeometry.cpp.
References cmp_diff::ge(), cmp_diff::le(), and pts.
scale()
void Voxel::scale (const Vector_t & scale) inline
Definition at line 615 of file BoundaryGeometry.cpp.
References pts.
Referenced by intersect().
Member Data Documentation
pts
Vector_t Voxel::pts[2]
Definition at line 690 of file BoundaryGeometry.cpp.
Referenced by extent(), intersect(), BoundaryGeometry::intersectTinyLineSegmentBoundary(), isInside(), scale(), and Voxel().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/src/Structure/BoundaryGeometry.cpp