OPAL (Object Oriented Parallel Accelerator Library): Tracker Class Reference
Tracker Class Reference
#include <Tracker.h>
Public Member Functions
Tracker (const Beamline &, const PartData &, bool backBeam, bool backTrack)
Constructor.
Tracker (const Beamline &, PartBunchBase< double, 3 > *bunch, const PartData &, bool backBeam, bool backTrack)
Constructor.
virtual ~Tracker ()
const PartBunchBase< double, 3 > * getBunch () const
Return the current bunch.
void addToBunch (const OpalParticle &)
Add particle to bunch.
virtual void visitComponent (const Component &)
Store the bunch.
virtual void setNumBunch (short)
set total number of tracked bunches
virtual short getNumBunch ()
get total number of tracked bunches
Public Member Functions inherited from AbstractTracker
AbstractTracker (const Beamline &, const PartData &, bool backBeam, bool backTrack)
Constructor.
virtual ~AbstractTracker ()
Public Member Functions inherited from DefaultVisitor
DefaultVisitor (const Beamline &beamline, bool backBeam, bool backTrack)
Constructor.
virtual ~DefaultVisitor ()=0
virtual void execute ()
Apply the algorithm to the top-level beamline.
virtual void visitBeamline (const Beamline &)
Apply the algorithm to a beam line.
virtual void visitCCollimator (const CCollimator &)
Apply the algorithm to a collimator.
virtual void visitCorrector (const Corrector &)
Apply the algorithm to a closed orbit corrector.
virtual void visitCyclotron (const Cyclotron &)
Apply the algorithm to an cyclotron.
virtual void visitDegrader (const Degrader &)
Apply the algorithm to a degrader.
virtual void visitDrift (const Drift &)
Apply the algorithm to a drift space.
virtual void visitFlaggedElmPtr (const FlaggedElmPtr &)
Apply the algorithm to a FlaggedElmPtr.
virtual void visitFlexibleCollimator (const FlexibleCollimator &)
Apply the algorithm to a flexible collimator.
virtual void visitMarker (const Marker &)
Apply the algorithm to a marker.
virtual void visitMonitor (const Monitor &)
Apply the algorithm to a beam position monitor.
virtual void visitMultipole (const Multipole &)
Apply the algorithm to a multipole.
virtual void visitMultipoleT (const MultipoleT &)
Apply the algorithm to to an arbitrary multipole.
virtual void visitMultipoleTStraight (const MultipoleTStraight &)
Apply the algorithm to an arbitrary straight multipole.
virtual void visitMultipoleTCurvedConstRadius (const MultipoleTCurvedConstRadius &)
Apply the algorithm to an arbitrary curved multipole of constant radius.
virtual void visitMultipoleTCurvedVarRadius (const MultipoleTCurvedVarRadius &)
Apply the algorithm to an arbitrary curved multipole of variable radius.
virtual void visitOffset (const Offset &)
Apply the algorithm to an offset (placement).
virtual void visitOutputPlane (const OutputPlane &)
Apply the algorithm to an output plane.
virtual void visitProbe (const Probe &prob)
Apply the algorithm to a probe.
virtual void visitRBend (const RBend &)
Apply the algorithm to a rectangular bend.
virtual void visitRBend3D (const RBend3D &)
Apply the algorithm to a rectangular bend.
virtual void visitRFCavity (const RFCavity &)
Apply the algorithm to a RF cavity.
virtual void visitRing (const Ring &)
Apply the algorithm to a ring.
virtual void visitSBend (const SBend &)
Apply the algorithm to a sector bend.
virtual void visitSBend3D (const SBend3D &)
Apply the algorithm to a sector bend with 3D field map.
virtual void visitScalingFFAMagnet (const ScalingFFAMagnet &)
Apply the algorithm to a scaling FFA magnet.
virtual void visitSeptum (const Septum &)
Apply the algorithm to a septum.
virtual void visitSolenoid (const Solenoid &)
Apply the algorithm to a solenoid.
virtual void visitSource (const Source &)
Apply the algorithm to a source.
virtual void visitStripper (const Stripper &)
Apply the algorithm to a particle stripper.
virtual void visitTravelingWave (const TravelingWave &)
Apply the algorithm to a traveling wave.
virtual void visitVacuum (const Vacuum &)
Apply the algorithm to a vacuum space.
virtual void visitVariableRFCavity (const VariableRFCavity &vcav)
Apply the algorithm to a a variable RF cavity.
virtual void visitVariableRFCavityFringeField (const VariableRFCavityFringeField &vcav)
Apply the algorithm to a a variable RF cavity with Fringe Field.
virtual void visitVerticalFFAMagnet (const VerticalFFAMagnet &)
Apply the algorithm to a vertical FFA magnet.
Public Member Functions inherited from BeamlineVisitor
BeamlineVisitor ()
virtual ~BeamlineVisitor ()
Public Attributes
FieldList cavities_m
const Beamline & itsBeamline_m
Protected Member Functions
void applyDrift (double length)
Apply a drift length.
void applyThinMultipole (const BMultipoleField &field, double factor)
void applyThinSBend (const BMultipoleField &field, double scale, double h)
void applyTransform (const Euclid3D &, double refLength=0.0)
Apply a geometric transformation.
FTps< double, 2 > buildMultipoleVectorPotential2D (const BMultipoleField &)
Construct vector potential for a Multipole.
FTps< double, 6 > buildMultipoleVectorPotential (const BMultipoleField &)
Construct vector potential for a Multipole.
FTps< double, 2 > buildSBendVectorPotential2D (const BMultipoleField &, double h)
Construct vector potential for a SBend.
FTps< double, 6 > buildSBendVectorPotential (const BMultipoleField &, double h)
Construct vector potential for a SBend.
Protected Attributes
PartBunchBase< double, 3 > * itsBunch_m
The bunch of particles to be tracked.
Protected Attributes inherited from AbstractTracker
const PartData itsReference
The reference information.
Protected Attributes inherited from DefaultVisitor
const Beamline & itsLine
bool back_beam
bool back_track
bool back_path
double flip_B
double flip_s
Private Member Functions
Tracker ()
Tracker (const Tracker &)
void operator= (const Tracker &)
Additional Inherited Members
Public Types inherited from AbstractTracker
enum {
X, PX, Y, PY,
T, PT
}
Detailed Description
Definition at line 76 of file Tracker.h.
Constructor & Destructor Documentation
Tracker() [1/4]
Tracker::Tracker (const Beamline & beamline, const PartData & reference, bool backBeam, bool backTrack)
Constructor.
Definition at line 82 of file Tracker.cpp.
Tracker() [2/4]
Tracker::Tracker (const Beamline & beamline, PartBunchBase< double, 3 > * bunch, const PartData & reference, bool backBeam, bool backTrack)
Constructor.
Definition at line 88 of file Tracker.cpp.
~Tracker()
Tracker::~Tracker () virtual
Definition at line 98 of file Tracker.cpp.
Tracker() [3/4]
Tracker::Tracker () private
Tracker() [4/4]
Tracker::Tracker (const Tracker &) private
Member Function Documentation
addToBunch()
void Tracker::addToBunch (const OpalParticle & part)
Add particle to bunch.
Definition at line 107 of file Tracker.cpp.
References itsBunch_m, and PartBunchBase< T, Dim >::push_back().
applyDrift()
void Tracker::applyDrift (double length) protected
Apply a drift length.
Definition at line 122 of file Tracker.cpp.
References dot(), PartData::getBeta(), PartBunchBase< T, Dim >::getLocalNum(), PartData::getM(), PartData::getP(), OpalParticle::getP(), PartBunchBase< T, Dim >::getParticle(), OpalParticle::getX(), OpalParticle::getY(), OpalParticle::getZ(), itsBunch_m, AbstractTracker::itsReference, max(), PartBunchBase< T, Dim >::setParticle(), OpalParticle::setX(), OpalParticle::setY(), OpalParticle::setZ(), and sqrt().
applyThinMultipole()
void Tracker::applyThinMultipole (const BMultipoleField & field, double factor) protected
Definition at line 141 of file Tracker.cpp.
References OpalParticle::getPx(), OpalParticle::getPy(), OpalParticle::getX(), OpalParticle::getY(), max(), BMultipoleField::normal(), BMultipoleField::order(), OpalParticle::setPx(), OpalParticle::setPy(), and BMultipoleField::skew().
applyThinSBend()
void Tracker::applyThinSBend (const BMultipoleField & field, double scale, double h) protected
Definition at line 170 of file Tracker.cpp.
References FTps< T, N >::derivative(), FTps< T, N >::evaluate(), OpalParticle::getPx(), OpalParticle::getPy(), OpalParticle::getX(), OpalParticle::getY(), OpalParticle::setPx(), and OpalParticle::setPy().
applyTransform()
void Tracker::applyTransform (const Euclid3D & euclid, double refLength = 0.0) protected
Apply a geometric transformation.
Definition at line 189 of file Tracker.cpp.
References PartData::getBeta(), PartBunchBase< T, Dim >::getLocalNum(), PartData::getM(), PartData::getP(), PartBunchBase< T, Dim >::getParticle(), OpalParticle::getPx(), OpalParticle::getPy(), OpalParticle::getPz(), OpalParticle::getX(), Euclid3D::getX(), OpalParticle::getY(), Euclid3D::getY(), OpalParticle::getZ(), Euclid3D::getZ(), Euclid3D::isIdentity(), itsBunch_m, AbstractTracker::itsReference, Euclid3D::M(), PartBunchBase< T, Dim >::setParticle(), OpalParticle::setPx(), OpalParticle::setPy(), OpalParticle::setX(), OpalParticle::setY(), OpalParticle::setZ(), and sqrt().
buildMultipoleVectorPotential()
Series Tracker::buildMultipoleVectorPotential (const BMultipoleField & field) protected
Construct vector potential for a Multipole.
Definition at line 253 of file Tracker.cpp.
References FTps< T, N >::getMaxOrder(), FTps< double, 6 >::makeVariable(), BMultipoleField::normal(), BMultipoleField::order(), FTps< T, N >::setTruncOrder(), BMultipoleField::skew(), AbstractTracker::X, and AbstractTracker::Y.
buildMultipoleVectorPotential2D()
Series2 Tracker::buildMultipoleVectorPotential2D (const BMultipoleField & field) protected
Construct vector potential for a Multipole.
Definition at line 226 of file Tracker.cpp.
References FTps< T, N >::getMaxOrder(), FTps< T, N >::makeVariable(), BMultipoleField::normal(), BMultipoleField::order(), FTps< T, N >::setTruncOrder(), and BMultipoleField::skew().
buildSBendVectorPotential()
Series Tracker::buildSBendVectorPotential (const BMultipoleField & field, double h) protected
Construct vector potential for a SBend.
Definition at line 332 of file Tracker.cpp.
References FTps< T, N >::derivative(), FTps< T, N >::getMaxOrder(), FTps< double, 6 >::makeVariable(), BMultipoleField::normal(), BMultipoleField::order(), FTps< T, N >::setTruncOrder(), BMultipoleField::skew(), AbstractTracker::X, and AbstractTracker::Y.
buildSBendVectorPotential2D()
Series2 Tracker::buildSBendVectorPotential2D (const BMultipoleField & field, double h) protected
Construct vector potential for a SBend.
Definition at line 280 of file Tracker.cpp.
References FTps< T, N >::derivative(), FTps< T, N >::getMaxOrder(), FTps< T, N >::makeVariable(), BMultipoleField::normal(), BMultipoleField::order(), FTps< T, N >::setTruncOrder(), BMultipoleField::skew(), and AbstractTracker::X.
getBunch()
const PartBunchBase< double, 3 > * Tracker::getBunch () const
Return the current bunch.
Definition at line 102 of file Tracker.cpp.
References itsBunch_m.
getNumBunch()
virtual short Tracker::getNumBunch () inline virtual
get total number of tracked bunches
Definition at line 117 of file Tracker.h.
operator=()
void Tracker::operator= (const Tracker &) private
setNumBunch()
virtual void Tracker::setNumBunch (short) inline virtual
set total number of tracked bunches
Definition at line 114 of file Tracker.h.
visitComponent()
void Tracker::visitComponent (const Component & comp) virtual
Store the bunch.
Apply the algorithm to an arbitrary component.
Reimplemented from DefaultVisitor.
Definition at line 117 of file Tracker.cpp.
References DefaultVisitor::back_beam, DefaultVisitor::back_track, itsBunch_m, AbstractTracker::itsReference, and Component::trackBunch().
Member Data Documentation
cavities_m
FieldList Tracker::cavities_m
Definition at line 120 of file Tracker.h.
itsBeamline_m
const Beamline& Tracker::itsBeamline_m
Definition at line 122 of file Tracker.h.
Referenced by ThickTracker::prepareSections(), and ParallelTTracker::prepareSections().
itsBunch_m
PartBunchBase<double, 3>* Tracker::itsBunch_m protected
The bunch of particles to be tracked.
Definition at line 151 of file Tracker.h.
Referenced by addToBunch(), ThickTracker::advanceDispersion_m(), ThickTracker::advanceParticles_m(), applyDrift(), ParallelTTracker::applyFractionalStep(), ParallelCyclotronTracker::applyPluginElements(), applyTransform(), ParallelTTracker::autophaseCavities(), ParallelCyclotronTracker::bgf_main_collision_test(), ParallelCyclotronTracker::borisExternalFields(), ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), ParallelCyclotronTracker::bunchDumpStatData(), ParallelCyclotronTracker::bunchMode_m(), ParallelCyclotronTracker::calcMeanP(), ParallelCyclotronTracker::calcMeanR(), ParallelTTracker::changeDT(), ParallelCyclotronTracker::checkFileMomentum(), ParallelCyclotronTracker::checkNumPart(), ParallelTTracker::computeExternalFields(), ParallelTTracker::computeParticleMatterInteraction(), ParallelCyclotronTracker::computePathLengthUpdate(), ParallelTTracker::computeSpaceChargeFields(), ParallelCyclotronTracker::computeSpaceChargeFields_m(), ParallelTTracker::computeWakefield(), ParallelCyclotronTracker::deleteParticle(), ParallelTTracker::doBinaryRepartition(), ThickTracker::dump_m(), ParallelTTracker::dumpStats(), ParallelTTracker::emitParticles(), ParallelTTracker::evenlyDistributeParticles(), ParallelCyclotronTracker::execute(), ParallelTTracker::execute(), ThickTracker::execute(), ParallelCyclotronTracker::finalizeTracking_m(), ParallelTTracker::findStartPosition(), ParallelCyclotronTracker::gapCrossKick_m(), ParallelCyclotronTracker::GenericTracker(), getBunch(), ParallelCyclotronTracker::getFieldsAtPoint(), ParallelCyclotronTracker::globalToLocal(), ParallelTTracker::hasEndOfLineReached(), ParallelCyclotronTracker::initDistInGlobalFrame(), ParallelCyclotronTracker::initializeTracking_m(), ParallelCyclotronTracker::initTrackOrbitFile(), ParallelCyclotronTracker::injectBunch(), ParallelCyclotronTracker::isMultiBunch(), ParallelCyclotronTracker::kick(), ParallelTTracker::kickParticles(), ParallelCyclotronTracker::localToGlobal(), ParallelCyclotronTracker::MtsTracker(), ParallelTTracker::prepareEmission(), ParallelCyclotronTracker::push(), ParallelTTracker::pushParticles(), ParallelCyclotronTracker::repartition(), ParallelCyclotronTracker::RFkick(), ParallelCyclotronTracker::rotateAroundX(), ParallelCyclotronTracker::rotateAroundZ(), ParallelCyclotronTracker::rotateWithQuaternion(), ParallelCyclotronTracker::saveInjectValues(), ParallelTTracker::selectDT(), ParallelCyclotronTracker::seoMode_m(), ParallelTTracker::setTime(), ParallelCyclotronTracker::setTimeStep(), ParallelCyclotronTracker::singleMode_m(), ParallelCyclotronTracker::singleParticleDump(), ParallelTTracker::timeIntegration2(), ThickTracker::track_m(), ParallelTTracker::transformBunch(), ThickTracker::update_m(), ParallelCyclotronTracker::update_m(), ThickTracker::updateParticle_m(), ParallelCyclotronTracker::updatePathLength(), ParallelTTracker::updateReferenceParticle(), ParallelTTracker::updateRefToLabCSTrafo(), ParallelCyclotronTracker::updateTime(), ParallelCyclotronTracker::visitCCollimator(), ParallelTTracker::visitCCollimator(), visitComponent(), ParallelTTracker::visitCorrector(), ParallelCyclotronTracker::visitCyclotron(), ParallelTTracker::visitDegrader(), ParallelTTracker::visitDrift(), ThickTracker::visitDrift(), ParallelTTracker::visitFlexibleCollimator(), ParallelTTracker::visitMarker(), ParallelTTracker::visitMonitor(), ParallelTTracker::visitMultipole(), ThickTracker::visitMultipole(), ParallelTTracker::visitMultipoleT(), ParallelCyclotronTracker::visitOutputPlane(), ParallelTTracker::visitProbe(), ParallelCyclotronTracker::visitProbe(), ParallelTTracker::visitRBend(), ParallelTTracker::visitRBend3D(), ParallelTTracker::visitRFCavity(), ParallelCyclotronTracker::visitRFCavity(), ParallelCyclotronTracker::visitRing(), ParallelTTracker::visitSBend(), ThickTracker::visitSBend(), ParallelTTracker::visitSeptum(), ParallelCyclotronTracker::visitSeptum(), ParallelTTracker::visitSolenoid(), ParallelTTracker::visitSource(), ParallelCyclotronTracker::visitStripper(), ParallelTTracker::visitTravelingWave(), ParallelTTracker::visitVacuum(), ParallelCyclotronTracker::visitVacuum(), and ParallelTTracker::writePhaseSpace().
The documentation for this class was generated from the following files:
src/Classic/Algorithms/Tracker.h
src/Classic/Algorithms/Tracker.cpp