OPAL (Object Oriented Parallel Accelerator Library): ippl/src/FieldLayout/BinaryBalancer.h File Reference
BinaryBalancer.h File Reference
#include "FieldLayout/BinaryBalancer.hpp"
Classes
class FieldLayout< Dim >
class BareField< T, Dim >
class BinaryRepartitionFailed
Functions
template<unsigned Dim>
NDIndex< Dim > CalcBinaryRepartition (FieldLayout< Dim > &, BareField< double, Dim > &)
template<unsigned Dim>
void BinaryRepartition (FieldLayout< Dim > &layout, BareField< double, Dim > &weights)
Function Documentation
BinaryRepartition()
template<unsigned Dim> void BinaryRepartition (FieldLayout< Dim > & layout, BareField< double, Dim > & weights) inline
Definition at line 68 of file BinaryBalancer.h.
References CalcBinaryRepartition(), and FieldLayout< Dim >::Repartition().
Referenced by PartBunch::do_binaryRepart().
CalcBinaryRepartition()
template<unsigned Dim> NDIndex<Dim> CalcBinaryRepartition (FieldLayout< Dim > & , BareField< double, Dim > &)
Definition at line 586 of file BinaryBalancer.hpp.
References IpplInfo::Comm, FieldLayout< Dim >::getDomain(), Communicate::getNodes(), and Communicate::myNode().
Referenced by BinaryRepartition().