OPAL (Object Oriented Parallel Accelerator Library): ParticleInteractAttrib< T > Class Template Reference
ParticleInteractAttrib< T > Class Template Reference
#include <ParticleInteractAttrib.h>
Public Types
typedef ParticleAttrib< T >::ParticleList_t ParticleList_t
Public Types inherited from ParticleAttrib< T >
enum { IsExpr = 0 }
typedef T Return_t
typedef std::vector< T > ParticleList_t
typedef ParticleAttribIterator< T > iterator
typedef ParticleAttribConstIterator< T > const_iterator
typedef ParticleAttribBase::SortListIndex_t SortListIndex_t
typedef ParticleAttribBase::SortList_t SortList_t
typedef const_iterator PETE_Expr_t
Public Types inherited from ParticleAttribBase
typedef long SortListIndex_t
typedef std::vector< SortListIndex_t > SortList_t
Public Types inherited from DataSource
enum DsMode { INPUT, OUTPUT, BOTH, DEFAULT }
typedef std::vector< DataSourceObject * > container_t
Public Types inherited from PETE_Expr< ParticleAttrib< T > >
typedef ParticleAttrib< T > Wrapped
Public Member Functions
ParticleInteractAttrib ()
ParticleInteractAttrib (const ParticleInteractAttrib< T > &pa)
ParticleInteractAttrib (const ParticleAttrib< T > &pa)
~ParticleInteractAttrib ()
template<class T1 >
const ParticleInteractAttrib< T > & operator= (const PETE_Expr< T1 > &rhs)
const ParticleInteractAttrib< T > & operator= (const ParticleInteractAttrib< T > &rhs)
const ParticleInteractAttrib< T > & operator= (const ParticleAttrib< T > &rhs)
const ParticleInteractAttrib< T > & operator= (T rhs)
ParticleList_t::reference operator[] (size_t n)
ParticleList_t::const_reference operator[] (size_t n) const
ParticleList_t::reference ghostAttrib (size_t n)
ParticleList_t::const_reference ghostAttrib (size_t n) const
virtual size_t putMessage (Message &, size_t, size_t)
virtual size_t putMessage (Message &m, const std::vector< size_t > &v)
virtual size_t ghostDestroy (size_t M, size_t I)
virtual size_t ghostPutMessage (Message &msg, size_t M, size_t I)
virtual size_t ghostPutMessage (Message &msg, const std::vector< size_t > &v)
virtual size_t ghostGetMessage (Message &, size_t)
virtual void printDebug (Inform &)
Public Member Functions inherited from ParticleAttrib< T >
ParticleAttrib ()
ParticleAttrib (const ParticleAttrib< T > &pa)
~ParticleAttrib ()
bool isDirty ()
void resetDirtyFlag ()
ParticleList_t::reference operator[] (size_t n)
ParticleList_t::const_reference operator[] (size_t n) const
template<unsigned Dim>
SubParticleAttrib< ParticleAttrib< T >, T, Dim > operator[] (const SIndex< Dim > &s) const
PETE_Expr_t MakeExpression () const
iterator begin ()
iterator end ()
const_iterator cbegin () const
const_iterator cend () const
size_t size (void) const
ParticleAttribElem< T, 1U > operator() (unsigned)
ParticleAttribElem< T, 2U > operator() (unsigned, unsigned)
ParticleAttribElem< T, 3U > operator() (unsigned, unsigned, unsigned)
template<unsigned Dim, class M , class C , class PT , class IntOp >
void scatter (Field< T, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &) const
template<unsigned Dim, class M , class C , class PT , class IntOp , class CacheData >
void scatter (Field< T, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &, ParticleAttrib< CacheData > &cache) const
template<unsigned Dim, class M , class C , class IntOp , class CacheData >
void scatter (Field< T, Dim, M, C > &f, const IntOp &, const ParticleAttrib< CacheData > &cache) const
template<unsigned Dim, class M , class C , class PT , class IntOp >
void gather (const Field< T, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &)
template<unsigned Dim, class M , class C , class PT , class IntOp , class CacheData >
void gather (const Field< T, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &, ParticleAttrib< CacheData > &cache)
template<unsigned Dim, class M , class C , class IntOp , class CacheData >
void gather (const Field< T, Dim, M, C > &f, const IntOp &, const ParticleAttrib< CacheData > &cache)
template<class T1 >
const ParticleAttrib< T > & operator= (const PETE_Expr< T1 > &rhs)
const ParticleAttrib< T > & operator= (const ParticleAttrib< T > &rhs)
const ParticleAttrib< T > & operator= (T rhs)
virtual void create (size_t)
virtual void destroy (size_t M, size_t I, bool optDestroy=true)
virtual void destroy (const std::vector< std::pair< size_t, size_t > > &dlist, bool optDestroy=true)
virtual size_t getMessage (Message &, size_t)
virtual void ghostCreate (size_t)
virtual void calcSortList (SortList_t &slist, bool ascending=true)
virtual void sort (SortList_t &slist)
Public Member Functions inherited from ParticleAttribBase
ParticleAttribBase (unsigned int size, const std::string &typestr)
ParticleAttribBase (const ParticleAttribBase &pa)
virtual ~ParticleAttribBase ()
unsigned int elementSize () const
const std::string & typeString () const
void setTemporary (bool t)
bool isTemporary () const
Public Member Functions inherited from DataSource
DataSource ()
virtual ~DataSource ()
bool connected (DataConnect *=0) const
DataSourceObject * findDataSourceObject (DataConnect *) const
DataConnect * connect (const char *, DataConnect *=0, int=DataSource::DEFAULT)
bool connect (DataSourceObject *)
bool disconnect (DataConnect *=0)
bool updateConnection (DataConnect *=0)
void interact (DataConnect *=0)
void interact (const char *, DataConnect *=0)
Public Member Functions inherited from PETE_Expr< ParticleAttrib< T > >
ParticleAttrib< T > & PETE_unwrap ()
const ParticleAttrib< T > & PETE_unwrap () const
Private Attributes
ParticleList_t GhostList
Additional Inherited Members
Protected Member Functions inherited from ParticleAttrib< T >
virtual DataSourceObject * createDataSourceObject (const char *nm, DataConnect *dc, int tm)
Protected Attributes inherited from ParticleAttrib< T >
ParticleList_t ParticleList
size_t LocalSize
Detailed Description
template<class T>
class ParticleInteractAttrib< T >
Definition at line 68 of file ParticleInteractAttrib.h.
Member Typedef Documentation
ParticleList_t
template<class T> typedef ParticleAttrib<T>::ParticleList_t ParticleInteractAttrib< T >::ParticleList_t
Definition at line 71 of file ParticleInteractAttrib.h.
Constructor & Destructor Documentation
ParticleInteractAttrib() [1/3]
template<class T> ParticleInteractAttrib< T >::ParticleInteractAttrib () inline
Definition at line 74 of file ParticleInteractAttrib.h.
ParticleInteractAttrib() [2/3]
template<class T> ParticleInteractAttrib< T >::ParticleInteractAttrib (const ParticleInteractAttrib< T > & pa) inline
Definition at line 77 of file ParticleInteractAttrib.h.
ParticleInteractAttrib() [3/3]
template<class T> ParticleInteractAttrib< T >::ParticleInteractAttrib (const ParticleAttrib< T > & pa) inline
Definition at line 79 of file ParticleInteractAttrib.h.
~ParticleInteractAttrib()
template<class T> ParticleInteractAttrib< T >::~ParticleInteractAttrib () inline
Definition at line 83 of file ParticleInteractAttrib.h.
Member Function Documentation
ghostAttrib() [1/2]
template<class T> ParticleList_t::reference ParticleInteractAttrib< T >::ghostAttrib (size_t n) inline
Definition at line 139 of file ParticleInteractAttrib.h.
References ParticleInteractAttrib< T >::GhostList, and Hypervolume::n.
ghostAttrib() [2/2]
template<class T> ParticleList_t::const_reference ParticleInteractAttrib< T >::ghostAttrib (size_t n) const inline
Definition at line 142 of file ParticleInteractAttrib.h.
References ParticleInteractAttrib< T >::GhostList, and Hypervolume::n.
ghostDestroy()
template<class T > size_t ParticleInteractAttrib< T >::ghostDestroy (size_t M, size_t I) virtual
Reimplemented from ParticleAttrib< T >.
Definition at line 61 of file ParticleInteractAttrib.hpp.
ghostGetMessage()
template<class T > size_t ParticleInteractAttrib< T >::ghostGetMessage (Message & msg, size_t M) virtual
Reimplemented from ParticleAttrib< T >.
Definition at line 92 of file ParticleInteractAttrib.hpp.
References getMessage_iter(), and Attrib::Legacy::Distribution::T.
ghostPutMessage() [1/2]
template<class T> virtual size_t ParticleInteractAttrib< T >::ghostPutMessage (Message & msg, size_t M, size_t I) inline virtual
Reimplemented from ParticleAttrib< T >.
Definition at line 168 of file ParticleInteractAttrib.h.
References ParticleInteractAttrib< T >::putMessage().
ghostPutMessage() [2/2]
template<class T> virtual size_t ParticleInteractAttrib< T >::ghostPutMessage (Message & msg, const std::vector< size_t > & v) inline virtual
Reimplemented from ParticleAttrib< T >.
Definition at line 173 of file ParticleInteractAttrib.h.
References ParticleInteractAttrib< T >::putMessage().
operator=() [1/4]
template<class T> template<class T1 > const ParticleInteractAttrib<T>& ParticleInteractAttrib< T >::operator= (const PETE_Expr< T1 > & rhs) inline
Definition at line 91 of file ParticleInteractAttrib.h.
References assign().
operator=() [2/4]
template<class T> const ParticleInteractAttrib<T>& ParticleInteractAttrib< T >::operator= (const ParticleInteractAttrib< T > & rhs) inline
Definition at line 97 of file ParticleInteractAttrib.h.
References assign(), endl(), ERRORMSG, and ParticleAttrib< T >::size().
operator=() [3/4]
template<class T> const ParticleInteractAttrib<T>& ParticleInteractAttrib< T >::operator= (const ParticleAttrib< T > & rhs) inline
Definition at line 108 of file ParticleInteractAttrib.h.
References assign(), endl(), ERRORMSG, and ParticleAttrib< T >::size().
operator=() [4/4]
template<class T> const ParticleInteractAttrib<T>& ParticleInteractAttrib< T >::operator= (T rhs) inline
Definition at line 118 of file ParticleInteractAttrib.h.
References assign().
operator[]() [1/2]
template<class T> ParticleList_t::reference ParticleInteractAttrib< T >::operator[] (size_t n) inline
Definition at line 130 of file ParticleInteractAttrib.h.
References ParticleInteractAttrib< T >::GhostList, Hypervolume::n, ParticleAttrib< T >::ParticleList, and ParticleAttrib< T >::size().
operator[]() [2/2]
template<class T> ParticleList_t::const_reference ParticleInteractAttrib< T >::operator[] (size_t n) const inline
Definition at line 134 of file ParticleInteractAttrib.h.
References ParticleInteractAttrib< T >::GhostList, Hypervolume::n, ParticleAttrib< T >::ParticleList, and ParticleAttrib< T >::size().
printDebug()
template<class T > void ParticleInteractAttrib< T >::printDebug (Inform & o) virtual
Reimplemented from ParticleAttrib< T >.
Definition at line 105 of file ParticleInteractAttrib.hpp.
putMessage() [1/2]
template<class T > size_t ParticleInteractAttrib< T >::putMessage (Message & msg, size_t M, size_t I) virtual
Reimplemented from ParticleAttrib< T >.
Definition at line 37 of file ParticleInteractAttrib.hpp.
References putMessage().
Referenced by ParticleInteractAttrib< T >::ghostPutMessage().
putMessage() [2/2]
template<class T> virtual size_t ParticleInteractAttrib< T >::putMessage (Message & m, const std::vector< size_t > & v) inline virtual
Reimplemented from ParticleAttrib< T >.
Definition at line 151 of file ParticleInteractAttrib.h.
References ParticleAttrib< T >::putMessage().
Member Data Documentation
GhostList
template<class T> ParticleList_t ParticleInteractAttrib< T >::GhostList private
Definition at line 190 of file ParticleInteractAttrib.h.
Referenced by ParticleInteractAttrib< T >::ghostAttrib(), and ParticleInteractAttrib< T >::operator[]().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/ParticleInteractAttrib.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/ParticleInteractAttrib.hpp