OPAL (Object Oriented Parallel Accelerator Library): SDDS::parser::include_parser< Iterator > Struct Template Reference
SDDS::parser::include_parser< Iterator > Struct Template Reference
#include <include.hpp>
Inherits grammar< Iterator, include(), skipper< Iterator > >.
Public Member Functions
include_parser (error_handler< Iterator > &_error_handler)
Public Attributes
qi::rule< Iterator, include(), skipper< Iterator > > start
qi::rule< Iterator, std::string(), skipper< Iterator > > string
qi::rule< Iterator, std::string(), skipper< Iterator > > quoted_string
qi::rule< Iterator, std::string(), skipper< Iterator > > include_filename
Detailed Description
template<typename Iterator>
struct SDDS::parser::include_parser< Iterator >
Definition at line 81 of file include.hpp.
Constructor & Destructor Documentation
include_parser()
template<typename Iterator > SDDS::parser::include_parser< Iterator >::include_parser (error_handler< Iterator > & _error_handler)
Definition at line 30 of file include_def.hpp.
References Physics::alpha, PyOpal::PyAbstractTimeDependence::function(), SDDS::parser::include_parser< Iterator >::include_filename, SDDS::parser::include_parser< Iterator >::quoted_string, SDDS::parser::include_parser< Iterator >::start, and SDDS::parser::include_parser< Iterator >::string.
Member Data Documentation
include_filename
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::include_parser< Iterator >::include_filename
Definition at line 86 of file include.hpp.
Referenced by SDDS::parser::include_parser< Iterator >::include_parser().
quoted_string
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::include_parser< Iterator >::quoted_string
Definition at line 86 of file include.hpp.
Referenced by SDDS::parser::include_parser< Iterator >::include_parser().
start
template<typename Iterator > qi::rule<Iterator, include(), skipper<Iterator> > SDDS::parser::include_parser< Iterator >::start
Definition at line 85 of file include.hpp.
Referenced by SDDS::parser::include_parser< Iterator >::include_parser().
string
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::include_parser< Iterator >::string
Definition at line 86 of file include.hpp.
Referenced by SDDS::parser::include_parser< Iterator >::include_parser().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/optimizer/Util/SDDSParser/include.hpp
/psi/home/gsell/data/src/OPAL/src/optimizer/Util/SDDSParser/include_def.hpp