OPAL (Object Oriented Parallel Accelerator Library): cmp_diff Namespace Reference
cmp_diff Namespace Reference
Functions
bool almost_eq (double A, double B, double maxDiff=1e-15, double maxRelDiff=DBL_EPSILON)
bool almost_eq_zero (double A, double maxDiff=1e-15)
bool eq (double x, double y)
bool eq_zero (double x)
bool le (double x, double y)
bool le_zero (double x)
bool lt (double x, double y)
bool lt_zero (double x)
bool ge (double x, double y)
bool ge_zero (double x)
bool gt (double x, double y)
bool gt_zero (double x)
Function Documentation
almost_eq()
bool cmp_diff::almost_eq (double A, double B, double maxDiff = 1e-15, double maxRelDiff = DBL_EPSILON) inline
Definition at line 89 of file CmpFloat.h.
References abs().
almost_eq_zero()
bool cmp_diff::almost_eq_zero (double A, double maxDiff = 1e-15) inline
Definition at line 105 of file CmpFloat.h.
References abs().
eq()
bool cmp_diff::eq (double x, double y) inline
Definition at line 110 of file CmpFloat.h.
Referenced by PartBunchBase< double, 3 >::setBinCharge().
eq_zero()
bool cmp_diff::eq_zero (double x) inline
Definition at line 111 of file CmpFloat.h.
Referenced by BoundaryGeometry::intersectLineTriangle(), and BoundaryGeometry::intersectTinyLineSegmentBoundary().
ge()
bool cmp_diff::ge (double x, double y) inline
Definition at line 116 of file CmpFloat.h.
Referenced by Voxel::isInside().
ge_zero()
bool cmp_diff::ge_zero (double x) inline
Definition at line 117 of file CmpFloat.h.
Referenced by Voxel::intersect(), and BoundaryGeometry::intersectLineTriangle().
gt()
bool cmp_diff::gt (double x, double y) inline
Definition at line 118 of file CmpFloat.h.
Referenced by Voxel::intersect(), and BoundaryGeometry::intersectLineTriangle().
gt_zero()
bool cmp_diff::gt_zero (double x) inline
Definition at line 119 of file CmpFloat.h.
le()
bool cmp_diff::le (double x, double y) inline
Definition at line 112 of file CmpFloat.h.
Referenced by BoundaryGeometry::intersectLineTriangle(), and Voxel::isInside().
le_zero()
bool cmp_diff::le_zero (double x) inline
Definition at line 113 of file CmpFloat.h.
lt()
bool cmp_diff::lt (double x, double y) inline
Definition at line 114 of file CmpFloat.h.
Referenced by CalcIndexedReceive(), FFTBoxPoissonSolver::FFTBoxPoissonSolver(), IndexedLocalAssign(), IndexedSend(), P3MPoissonSolver::initializeFields(), FFTPoissonSolver::initializeFields(), Voxel::intersect(), BoundaryGeometry::intersectLineTriangle(), and BoundaryGeometry::isInside().
lt_zero()
bool cmp_diff::lt_zero (double x) inline
Definition at line 115 of file CmpFloat.h.
Referenced by BoundaryGeometry::intersectLineTriangle().