OPAL (Object Oriented Parallel Accelerator Library): PartBunchBase< T, Dim > Class Template Reference
PartBunchBase< T, Dim > Class Template Reference abstract
#include <OpalData.h>
Inherits enable_shared_from_this< PartBunchBase< T, Dim > >.
Classes
class ConstIterator
Public Types
enum UnitState_t { units = 0, unitless = 1 }
typedef AbstractParticle< T, Dim >::ParticlePos_t ParticlePos_t
typedef AbstractParticle< T, Dim >::ParticleIndex_t ParticleIndex_t
typedef AbstractParticle< T, Dim >::UpdateFlags UpdateFlags_t
typedef AbstractParticle< T, Dim >::Position_t Position_t
typedef std::pair< Vector_t, Vector_t > VectorPair_t
Public Member Functions
virtual ~PartBunchBase ()
PartBunchBase (AbstractParticle< T, Dim > *pb, const PartData *ref)
PartBunchBase (const PartBunchBase &rhs)=delete
virtual void initialize (FieldLayout_t *fLayout)=0
bool getIfBeamEmitting ()
int getLastEmittedEnergyBin ()
size_t getNumberOfEmissionSteps ()
int getNumberOfEnergyBins ()
void Rebin ()
void setEnergyBins (int numberOfEnergyBins)
bool weHaveEnergyBins ()
void switchToUnitlessPositions (bool use_dt_per_particle=false)
void switchOffUnitlessPositions (bool use_dt_per_particle=false)
void setDistribution (Distribution *d, std::vector< Distribution *> addedDistributions, size_t &np)
void setDistribution (Distribution *d, size_t numberOfParticles, double current, const Beamline &bl)
bool isGridFixed () const
bool hasBinning () const
void setTEmission (double t)
double getTEmission ()
bool doEmission ()
bool weHaveBins () const
void setPBins (PartBins *pbin)
void setPBins (PartBinsCyc *pbin)
size_t emitParticles (double eZ)
Emit particles in the given bin i.e. copy the particles from the bin structure into the particle container.
void updateNumTotal ()
void rebin ()
int getLastemittedBin ()
void setLocalBinCount (size_t num, int bin)
void calcGammas ()
Compute the gammas of all bins.
void calcGammas_cycl ()
void calcDebyeLength ()
Compute the (global) Debye length for the beam.
double getBinGamma (int bin)
Get gamma of one bin.
virtual void setBinCharge (int bin, double q)
Set the charge of one bin to the value of q and all other to zero.
virtual void setBinCharge (int bin)
Set the charge of all other the ones in bin to zero.
size_t calcNumPartsOutside (Vector_t x)
returns the number of particles outside of a box defined by x
void calcLineDensity (unsigned int nBins, std::vector< double > &lineDensity, std::pair< double, double > &meshInfo)
calculates the 1d line density (not normalized) and append it to a file.
void setBeamFrequency (double v)
virtual void boundp ()
void boundp_destroyCycl ()
size_t boundp_destroyT ()
size_t destroyT ()
virtual double getPx (int i)
virtual double getPy (int i)
virtual double getPz (int i)
virtual double getPx0 (int i)
virtual double getPy0 (int i)
virtual double getX (int i)
virtual double getY (int i)
virtual double getZ (int i)
virtual double getX0 (int i)
virtual double getY0 (int i)
virtual void setZ (int i, double zcoo)
void get_bounds (Vector_t &rmin, Vector_t &rmax) const
void getLocalBounds (Vector_t &rmin, Vector_t &rmax) const
std::pair< Vector_t, double > getBoundingSphere ()
std::pair< Vector_t, double > getLocalBoundingSphere ()
void push_back (OpalParticle const &p)
void setParticle (FVector< double, 6 > z, int ii)
void setParticle (OpalParticle const &p, int ii)
OpalParticle getParticle (int ii)
ConstIterator begin () const
ConstIterator end () const
void maximumAmplitudes (const FMatrix< double, 6, 6 > &D, double &axmax, double &aymax)
Return maximum amplitudes.
void setdT (double dt)
double getdT () const
void setT (double t)
void incrementT ()
double getT () const
double get_sPos () const
void set_sPos (double s)
double get_gamma () const
double get_meanKineticEnergy () const
double get_temperature () const
double get_debyeLength () const
double get_plasmaParameter () const
double get_rmsDensity () const
Vector_t get_origin () const
Vector_t get_maxExtent () const
Vector_t get_centroid () const
Vector_t get_rrms () const
Vector_t get_rprms () const
Vector_t get_rmean () const
Vector_t get_prms () const
Vector_t get_pmean () const
Vector_t get_pmean_Distribution () const
Vector_t get_emit () const
Vector_t get_norm_emit () const
Vector_t get_halo () const
Vector_t get_68Percentile () const
Vector_t get_95Percentile () const
Vector_t get_99Percentile () const
Vector_t get_99_99Percentile () const
Vector_t get_normalizedEps_68Percentile () const
Vector_t get_normalizedEps_95Percentile () const
Vector_t get_normalizedEps_99Percentile () const
Vector_t get_normalizedEps_99_99Percentile () const
virtual Vector_t get_hr () const
double get_Dx () const
double get_Dy () const
double get_DDx () const
double get_DDy () const
virtual void set_meshEnlargement (double dh)
void gatherLoadBalanceStatistics ()
size_t getLoadBalance (int p) const
void get_PBounds (Vector_t &min, Vector_t &max) const
void calcBeamParameters ()
void calcBeamParametersInitial ()
double getCouplingConstant () const
void setCouplingConstant (double c)
void setCharge (double q)
void setChargeZeroPart (double q)
void setMass (double mass)
void setMassZeroPart (double mass)
double getCharge () const
get the total charge per simulation particle
double getChargePerParticle () const
get the macro particle charge
double getMassPerParticle () const
virtual void setSolver (FieldSolver *fs)
bool hasFieldSolver ()
FieldSolverType getFieldSolverType () const
Return the fieldsolver type if we have a fieldsolver.
void setStepsPerTurn (int n)
int getStepsPerTurn () const
void setGlobalTrackStep (long long n)
step in multiple TRACK commands
long long getGlobalTrackStep () const
void setLocalTrackStep (long long n)
step in a TRACK command
void incTrackSteps ()
long long getLocalTrackStep () const
void setNumBunch (short n)
short getNumBunch () const
void setTotalNumPerBunch (size_t numpart, short n)
size_t getTotalNumPerBunch (short n) const
void setLocalNumPerBunch (size_t numpart, short n)
size_t getLocalNumPerBunch (short n) const
void countTotalNumPerBunch ()
void setGlobalMeanR (Vector_t globalMeanR)
Vector_t getGlobalMeanR ()
void setGlobalToLocalQuaternion (Quaternion_t globalToLocalQuaternion)
Quaternion_t getGlobalToLocalQuaternion ()
void setSteptoLastInj (int n)
int getSteptoLastInj () const
double calcMeanPhi ()
calculate average angle of longitudinal direction of bins
bool resetPartBinID2 (const double eta)
reset Bin[] for each particle according to the method given in paper PAST-AB(064402) by G. Fubiani et al.
bool resetPartBinBunch ()
double getdE () const
virtual double getGamma (int i)
virtual double getBeta (int i)
virtual void actT ()
const PartData * getReference () const
double getEmissionDeltaT ()
DistributionType getDistType () const
double getMomentumTolerance () const
Quaternion_t getQKs3D ()
void setQKs3D (Quaternion_t q)
Vector_t getKs3DRefr ()
void setKs3DRefr (Vector_t r)
Vector_t getKs3DRefp ()
void setKs3DRefp (Vector_t p)
void iterateEmittedBin (int binNumber)
void calcEMean ()
Inform & print (Inform &os)
virtual void runTests ()
virtual void do_binaryRepart ()
virtual void resetInterpolationCache (bool clearCache=false)
virtual VectorPair_t getEExtrema ()=0
virtual double getRho (int x, int y, int z)=0
virtual void computeSelfFields ()=0
virtual void computeSelfFields (int bin)=0
virtual void computeSelfFields_cycl (double gamma)=0
virtual void computeSelfFields_cycl (int bin)=0
virtual void swap (unsigned int i, unsigned int j)
virtual void setBCAllPeriodic ()
virtual void setBCAllOpen ()
virtual void setBCForDCBeam ()
virtual FieldLayout_t & getFieldLayout ()=0
virtual void resizeMesh ()
size_t getTotalNum () const
void setTotalNum (size_t n)
void setLocalNum (size_t n)
size_t getLocalNum () const
size_t getDestroyNum () const
size_t getGhostNum () const
ParticleLayout< T, Dim > & getLayout ()
const ParticleLayout< T, Dim > & getLayout () const
bool getUpdateFlag (UpdateFlags_t f) const
void setUpdateFlag (UpdateFlags_t f, bool val)
ParticleBConds< Position_t, Dimension > & getBConds ()
void setBConds (const ParticleBConds< Position_t, Dimension > &bc)
bool singleInitNode () const
void resetID ()
void update ()
void update (const ParticleAttrib< char > &canSwap)
void createWithID (unsigned id)
void create (size_t M)
void globalCreate (size_t np)
void destroy (size_t M, size_t I, bool doNow=false)
void performDestroy (bool updateLocalNum=false)
void ghostDestroy (size_t M, size_t I)
FMatrix< double, 2 *Dim, 2 *Dim > getSigmaMatrix () const
double getQ () const
Access to reference data.
double getM () const
double getP () const
double getE () const
ParticleOrigin getPOrigin () const
ParticleType getPType () const
double getInitialBeta () const
double getInitialGamma () const
void resetQ (double q)
void resetM (double m)
void setPOrigin (ParticleOrigin)
void setPType (const std::string &type)
Public Attributes
ParticlePos_t & R
ParticleIndex_t & ID
ParticleAttrib< Vector_t > P
ParticleAttrib< double > Q
ParticleAttrib< double > M
ParticleAttrib< double > Phi
ParticleAttrib< Vector_t > Ef
ParticleAttrib< Vector_t > Eftmp
ParticleAttrib< Vector_t > Bf
ParticleAttrib< int > Bin
ParticleAttrib< double > dt
ParticleAttrib< ParticleType > PType
ParticleAttrib< ParticleOrigin > POrigin
ParticleAttrib< int > TriID
ParticleAttrib< short > cavityGapCrossed
ParticleAttrib< short > bunchNum
Vector_t RefPartR_m
Vector_t RefPartP_m
CoordinateSystemTrafo toLabTrafo_m
ParticleOrigin refPOrigin_m
ParticleType refPType_m
PartBins * pbin_m
IpplTimings::TimerRef distrReload_m
timer for IC, can not be in Distribution.h
IpplTimings::TimerRef distrCreate_m
double dtScInit_m
double deltaTau_m
Static Public Attributes
static const unsigned Dimension = Dim
Protected Member Functions
size_t calcMoments ()
void calcMomentsInitial ()
double calculateAngle (double x, double y)
angle range [0~2PI) degree
Protected Attributes
IpplTimings::TimerRef boundpTimer_m
IpplTimings::TimerRef boundpBoundsTimer_m
IpplTimings::TimerRef boundpUpdateTimer_m
IpplTimings::TimerRef statParamTimer_m
IpplTimings::TimerRef histoTimer_m
IpplTimings::TimerRef selfFieldTimer_m
timer for selfField calculation
const PartData * reference
UnitState_t unit_state_
UnitState_t stateOfLastBoundP_
double centroid_m [2 *Dim]
holds the centroid of the beam
double dt_m
holds the timestep in seconds
double t_m
holds the actual time of the integration
double spos_m
the position along design trajectory
Vector_t globalMeanR_m
Quaternion_t globalToLocalQuaternion_m
Vector_t rmax_m
maximal extend of particles
Vector_t rmin_m
minimal extend of particles
double rmsDensity_m
Vector_t hr_m
meshspacing of cartesian mesh
Vektor< int, 3 > nr_m
meshsize of cartesian mesh
FieldSolver * fs_m
stores the used field solver
double couplingConstant_m
double qi_m
double massPerParticle_m
int distDump_m
counter to store the distribution dump
double dh_m
Mesh enlargement.
double tEmission_m
relative enlargement of the mesh
std::unique_ptr< double[]> bingamma_m
holds the gamma of the bin
std::unique_ptr< size_t[]> binemitted_m
int stepsPerTurn_m
steps per turn for OPAL-cycl
long long localTrackStep_m
step in a TRACK command
long long globalTrackStep_m
if multiple TRACK commands
short numBunch_m
current bunch number
std::vector< size_t > bunchTotalNum_m
number of particles per bunch
std::vector< size_t > bunchLocalNum_m
int SteptoLastInj_m
std::unique_ptr< size_t[]> globalPartPerNode_m
Distribution * dist_m
DistributionMoments momentsComputer_m
bool dcBeam_m
double periodLength_m
std::shared_ptr< AbstractParticle< T, Dim > > pbase_m
Private Member Functions
virtual void updateDomainLength (Vektor< int, 3 > &grid)=0
virtual void updateFields (const Vector_t &hr, const Vector_t &origin)
void setup (AbstractParticle< T, Dim > *pb)
Private Attributes
std::unique_ptr< Inform > pmsg_m
std::unique_ptr< std::ofstream > f_stream
bool fixed_grid
if the grid does not have to adapt
Detailed Description
template<class T, unsigned Dim>
class PartBunchBase< T, Dim >
H5PartWrapper: a class that manages calls to H5Part
Definition at line 34 of file OpalData.h.
Member Typedef Documentation
ParticleIndex_t
template<class T, unsigned Dim> typedef AbstractParticle<T, Dim>::ParticleIndex_t PartBunchBase< T, Dim >::ParticleIndex_t
Definition at line 53 of file PartBunchBase.h.
ParticlePos_t
template<class T, unsigned Dim> typedef AbstractParticle<T, Dim>::ParticlePos_t PartBunchBase< T, Dim >::ParticlePos_t
Definition at line 52 of file PartBunchBase.h.
Position_t
template<class T, unsigned Dim> typedef AbstractParticle<T, Dim>::Position_t PartBunchBase< T, Dim >::Position_t
Definition at line 55 of file PartBunchBase.h.
UpdateFlags_t
template<class T, unsigned Dim> typedef AbstractParticle<T, Dim>::UpdateFlags PartBunchBase< T, Dim >::UpdateFlags_t
Definition at line 54 of file PartBunchBase.h.
VectorPair_t
template<class T, unsigned Dim> typedef std::pair<Vector_t, Vector_t> PartBunchBase< T, Dim >::VectorPair_t
Definition at line 57 of file PartBunchBase.h.
Member Enumeration Documentation
UnitState_t
template<class T, unsigned Dim> enum PartBunchBase::UnitState_t
Enumerator
units
unitless
Definition at line 61 of file PartBunchBase.h.
Constructor & Destructor Documentation
~PartBunchBase()
template<class T, unsigned Dim> virtual PartBunchBase< T, Dim >::~PartBunchBase () inline virtual
Definition at line 64 of file PartBunchBase.h.
PartBunchBase() [1/2]
template<class T, unsigned Dim> PartBunchBase< T, Dim >::PartBunchBase (AbstractParticle< T, Dim > * pb, const PartData * ref)
Definition at line 41 of file PartBunchBase.hpp.
PartBunchBase() [2/2]
template<class T, unsigned Dim> PartBunchBase< T, Dim >::PartBunchBase (const PartBunchBase< T, Dim > & rhs) delete
Member Function Documentation
actT()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::actT () virtual
Definition at line 1730 of file PartBunchBase.hpp.
begin()
template<class T, unsigned Dim> ConstIterator PartBunchBase< T, Dim >::begin () const inline
Definition at line 279 of file PartBunchBase.h.
Referenced by begin(), and DistributionMoments::compute().
boundp()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::boundp () virtual
In case of dcBeam_m && hr_m < 0 this is the first call to boundp and we have to set hr completely i.e. x,y and z.
Reimplemented in AmrPartBunch.
Definition at line 510 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::boundp_destroyT(), ParallelTTracker::computeParticleMatterInteraction(), ParallelTTracker::computeSpaceChargeFields(), ParallelCyclotronTracker::computeSpaceChargeFields_m(), ParallelCyclotronTracker::deleteParticle(), Distribution::doRestartOpalCycl(), Distribution::doRestartOpalT(), ParallelCyclotronTracker::initDistInGlobalFrame(), Distribution::injectBeam(), and MultiBunchHandler::readBunch().
boundp_destroyCycl()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::boundp_destroyCycl ()
delete particles which are too far away from the center of beam
Definition at line 611 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::computeSpaceChargeFields_m().
boundp_destroyT()
template<class T , unsigned Dim> size_t PartBunchBase< T, Dim >::boundp_destroyT ()
This is only temporary in order to get the collimator and pepperpot working
Definition at line 719 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::computeExternalFields().
calcBeamParameters()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::calcBeamParameters ()
Definition at line 1267 of file PartBunchBase.hpp.
Referenced by Undulator::apply(), GreenWakeFunction::apply(), PartBunchBase< double, 3 >::boundp_destroyCycl(), PartBunchBase< double, 3 >::boundp_destroyT(), ParallelTTracker::computeSpaceChargeFields(), ParallelTTracker::computeWakefield(), ParallelCyclotronTracker::deleteParticle(), PartBunchBase< double, 3 >::destroyT(), DataSink::dumpSDDS(), ParallelCyclotronTracker::finalizeTracking_m(), ParallelCyclotronTracker::initDistInGlobalFrame(), MultiBunchHandler::injectBunch(), TrackRun::setupCyclotronTracker(), TrackRun::setupThickTracker(), TrackRun::setupTTracker(), ThickTracker::update_m(), ParallelTTracker::writePhaseSpace(), H5PartWrapperForPT::writeStep(), and H5PartWrapperForPC::writeStepHeader().
calcBeamParametersInitial()
template<class T, unsigned Dim> void PartBunchBase< T, Dim >::calcBeamParametersInitial ()
calcDebyeLength()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::calcDebyeLength ()
Compute the (global) Debye length for the beam.
Definition at line 413 of file PartBunchBase.hpp.
calcEMean()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::calcEMean ()
Definition at line 1754 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::dumpStats(), Distribution::injectBeam(), and ThickTracker::update_m().
calcGammas()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::calcGammas ()
Compute the gammas of all bins.
Definition at line 339 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::computeSpaceChargeFields().
calcGammas_cycl()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::calcGammas_cycl ()
Definition at line 386 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::computeSpaceChargeFields_m(), PartBunchBase< double, 3 >::resetPartBinBunch(), and PartBunchBase< double, 3 >::resetPartBinID2().
calcLineDensity()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::calcLineDensity (unsigned int nBins, std::vector< double > & lineDensity, std::pair< double, double > & meshInfo)
calculates the 1d line density (not normalized) and append it to a file.
calcLineDensity()
See also
ParallelTTracker
Warning
none yet
DETAILED TODO
Definition at line 471 of file PartBunchBase.hpp.
Referenced by GreenWakeFunction::apply(), CSRIGFWakeFunction::calculateLineDensity(), and CSRWakeFunction::calculateLineDensity().
calcMeanPhi()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::calcMeanPhi ()
calculate average angle of longitudinal direction of bins
Definition at line 1518 of file PartBunchBase.hpp.
calcMoments()
template<class T, unsigned Dim> size_t PartBunchBase< T, Dim >::calcMoments () protected
calcMomentsInitial()
template<class T, unsigned Dim> void PartBunchBase< T, Dim >::calcMomentsInitial () protected
calcNumPartsOutside()
template<class T , unsigned Dim> size_t PartBunchBase< T, Dim >::calcNumPartsOutside (Vector_t x)
returns the number of particles outside of a box defined by x
Definition at line 438 of file PartBunchBase.hpp.
Referenced by DataSink::dumpSDDS().
calculateAngle()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::calculateAngle (double x, double y) protected
angle range [0~2PI) degree
Definition at line 1797 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::calcMeanPhi().
computeSelfFields() [1/2]
template<class T, unsigned Dim> virtual void PartBunchBase< T, Dim >::computeSelfFields () pure virtual
Implemented in PartBunch, and AmrPartBunch.
Referenced by ParallelTTracker::computeSpaceChargeFields().
computeSelfFields() [2/2]
template<class T, unsigned Dim> virtual void PartBunchBase< T, Dim >::computeSelfFields (int bin) pure virtual
Implemented in PartBunch, and AmrPartBunch.
computeSelfFields_cycl() [1/2]
template<class T, unsigned Dim> virtual void PartBunchBase< T, Dim >::computeSelfFields_cycl (double gamma) pure virtual
Implemented in PartBunch, and AmrPartBunch.
Referenced by ParallelCyclotronTracker::computeSpaceChargeFields_m().
computeSelfFields_cycl() [2/2]
template<class T, unsigned Dim> virtual void PartBunchBase< T, Dim >::computeSelfFields_cycl (int bin) pure virtual
Implemented in PartBunch, and AmrPartBunch.
countTotalNumPerBunch()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::countTotalNumPerBunch ()
Definition at line 1455 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::boundp_destroyCycl(), and ParallelCyclotronTracker::initDistInGlobalFrame().
create()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::create (size_t M)
Definition at line 1990 of file PartBunchBase.hpp.
Referenced by Undulator::apply(), Stripper::doCheck(), Distribution::doRestartOpalCycl(), Distribution::doRestartOpalT(), Distribution::emitParticles(), ParallelTTracker::evenlyDistributeParticles(), Distribution::injectBeam(), PartBunchBase< double, 3 >::push_back(), and MultiBunchHandler::readBunch().
createWithID()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::createWithID (unsigned id)
Definition at line 1985 of file PartBunchBase.hpp.
Referenced by ScatteringPhysics::addParticleBackToBunch().
destroy()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::destroy (size_t M, size_t I, bool doNow = false)
Definition at line 2000 of file PartBunchBase.hpp.
Referenced by Undulator::apply(), PartBunchBase< double, 3 >::boundp_destroyCycl(), PartBunchBase< double, 3 >::boundp_destroyT(), ScatteringPhysics::copyFromBunch(), ParallelCyclotronTracker::deleteParticle(), PartBunchBase< double, 3 >::destroyT(), and ParallelTTracker::evenlyDistributeParticles().
destroyT()
template<class T , unsigned Dim> size_t PartBunchBase< T, Dim >::destroyT ()
Definition at line 762 of file PartBunchBase.hpp.
Referenced by BeamStrippingPhysics::apply(), and ParallelTTracker::computeExternalFields().
do_binaryRepart()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::do_binaryRepart () virtual
Reimplemented in AmrPartBunch, and PartBunch.
Definition at line 212 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::doBinaryRepartition(), and ParallelCyclotronTracker::repartition().
doEmission()
template<class T , unsigned Dim> bool PartBunchBase< T, Dim >::doEmission ()
Definition at line 266 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::prepareEmission().
emitParticles()
template<class T , unsigned Dim> size_t PartBunchBase< T, Dim >::emitParticles (double eZ)
Emit particles in the given bin i.e. copy the particles from the bin structure into the particle container.
Definition at line 299 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::emitParticles().
end()
template<class T, unsigned Dim> ConstIterator PartBunchBase< T, Dim >::end () const inline
Definition at line 283 of file PartBunchBase.h.
Referenced by DistributionMoments::compute(), and end().
gatherLoadBalanceStatistics()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::gatherLoadBalanceStatistics ()
Definition at line 1244 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::boundp_destroyT(), PartBunchBase< double, 3 >::destroyT(), and DataSink::dumpSDDS().
get_68Percentile()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_68Percentile () const
Definition at line 1168 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_95Percentile()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_95Percentile () const
Definition at line 1173 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_99_99Percentile()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_99_99Percentile () const
Definition at line 1183 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_99Percentile()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_99Percentile () const
Definition at line 1178 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_bounds()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::get_bounds (Vector_t & rmin, Vector_t & rmax) const
Definition at line 876 of file PartBunchBase.hpp.
Referenced by CSRIGFWakeFunction::apply(), CSRWakeFunction::apply(), GreenWakeFunction::apply(), PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::boundp_destroyCycl(), PartBunchBase< double, 3 >::calcBeamParameters(), PartBunchBase< double, 3 >::calcLineDensity(), Vacuum::checkVacuum(), ParallelTTracker::computeExternalFields(), CCollimator::doFinaliseCheck(), Septum::doPreCheck(), Probe::doPreCheck(), Stripper::doPreCheck(), CCollimator::doPreCheck(), ThickTracker::dump_m(), ParallelTTracker::execute(), PartBunchBase< double, 3 >::getBoundingSphere(), and ParallelTTracker::writePhaseSpace().
get_centroid()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_centroid () const
Definition at line 1105 of file PartBunchBase.hpp.
Referenced by Undulator::apply(), Ring::apply(), ParallelTTracker::computeSpaceChargeFields(), MultiBunchHandler::injectBunch(), H5PartWrapperForPC::writeStepHeader(), and H5PartWrapperForPT::writeStepHeader().
get_DDx()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::get_DDx () const
Definition at line 1220 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_DDy()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::get_DDy () const
Definition at line 1226 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_debyeLength()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::get_debyeLength () const
Definition at line 1078 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_Dx()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::get_Dx () const
Definition at line 1208 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_Dy()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::get_Dy () const
Definition at line 1214 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_emit()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_emit () const
Definition at line 1151 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::print(), H5PartWrapperForPT::writeStepHeader(), and H5PartWrapperForPC::writeStepHeader().
get_gamma()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::get_gamma () const
Definition at line 1061 of file PartBunchBase.hpp.
Referenced by Undulator::apply(), ThickTracker::update_m(), H5PartWrapperForPC::writeStepHeader(), and H5PartWrapperForPT::writeStepHeader().
get_halo()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_halo () const
Definition at line 1163 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_hr()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_hr () const virtual
Reimplemented in AmrPartBunch.
Definition at line 1232 of file PartBunchBase.hpp.
Referenced by MGPoissonSolver::MGPoissonSolver(), PartBunchBase< double, 3 >::print(), H5PartWrapperForPC::writeStepData(), and H5PartWrapperForPT::writeStepData().
get_maxExtent()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_maxExtent () const
Definition at line 1099 of file PartBunchBase.hpp.
Referenced by Undulator::apply(), StatWriter::write(), H5PartWrapperForPT::writeStepHeader(), and H5PartWrapperForPC::writeStepHeader().
get_meanKineticEnergy()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::get_meanKineticEnergy () const
Definition at line 1067 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), CSRIGFWakeFunction::calculateGreenFunction(), ParallelTTracker::dumpStats(), Expressions::getEkin(), PartBunchBase< double, 3 >::print(), StatWriter::write(), H5PartWrapperForPT::writeStepHeader(), and H5PartWrapperForPC::writeStepHeader().
get_norm_emit()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_norm_emit () const
Definition at line 1157 of file PartBunchBase.hpp.
Referenced by StatWriter::write(), H5PartWrapperForPC::writeStepHeader(), and H5PartWrapperForPT::writeStepHeader().
get_normalizedEps_68Percentile()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_normalizedEps_68Percentile () const
Definition at line 1188 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_normalizedEps_95Percentile()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_normalizedEps_95Percentile () const
Definition at line 1193 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_normalizedEps_99_99Percentile()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_normalizedEps_99_99Percentile () const
Definition at line 1203 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_normalizedEps_99Percentile()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_normalizedEps_99Percentile () const
Definition at line 1198 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_origin()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_origin () const
Definition at line 1093 of file PartBunchBase.hpp.
Referenced by H5PartWrapperForPC::writeStepData(), H5PartWrapperForPT::writeStepData(), H5PartWrapperForPT::writeStepHeader(), and H5PartWrapperForPC::writeStepHeader().
get_PBounds()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::get_PBounds (Vector_t & min, Vector_t & max) const
Definition at line 1261 of file PartBunchBase.hpp.
Referenced by H5PartWrapperForPC::writeStepHeader(), and H5PartWrapperForPT::writeStepHeader().
get_plasmaParameter()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::get_plasmaParameter () const
Definition at line 1083 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_pmean()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_pmean () const
Definition at line 1135 of file PartBunchBase.hpp.
Referenced by Undulator::apply(), ParallelTTracker::computeSpaceChargeFields(), ParallelTTracker::computeWakefield(), PartBunchBase< double, 3 >::getSigmaMatrix(), PartBunchBase< double, 3 >::print(), H5PartWrapperForPT::writeStepHeader(), and H5PartWrapperForPC::writeStepHeader().
get_pmean_Distribution()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_pmean_Distribution () const
Definition at line 1141 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::execute(), and ThickTracker::execute().
get_prms()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_prms () const
Definition at line 1129 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::print(), StatWriter::write(), H5PartWrapperForPT::writeStepHeader(), and H5PartWrapperForPC::writeStepHeader().
get_rmean()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_rmean () const
Definition at line 1123 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::calcNumPartsOutside(), PartBunchBase< double, 3 >::getSigmaMatrix(), PartBunchBase< double, 3 >::print(), StatWriter::write(), and H5PartWrapperForPC::writeStepHeader().
get_rmsDensity()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::get_rmsDensity () const
Definition at line 1088 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
get_rprms()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_rprms () const
Definition at line 1117 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::print(), and StatWriter::write().
get_rrms()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::get_rrms () const
Definition at line 1111 of file PartBunchBase.hpp.
Referenced by DataSink::dumpSDDS(), MultiBunchHandler::injectBunch(), PartBunchBase< double, 3 >::print(), StatWriter::write(), H5PartWrapperForPC::writeStepHeader(), and H5PartWrapperForPT::writeStepHeader().
get_sPos()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::get_sPos () const
get the spos of the primary beam
Parameters
none
Definition at line 1049 of file PartBunchBase.hpp.
Referenced by CSRIGFWakeFunction::apply(), CSRWakeFunction::apply(), BeamStrippingPhysics::apply(), Monitor::applyToReferenceParticle(), Distribution::doRestartOpalCycl(), ParallelTTracker::execute(), ParallelCyclotronTracker::initDistInGlobalFrame(), Monitor::initialise(), PartBunchBase< double, 3 >::print(), ParallelCyclotronTracker::saveInjectValues(), ThickTracker::update_m(), MemoryWriter::write(), StatWriter::write(), MemoryProfiler::write(), H5PartWrapperForPC::writeStepHeader(), and H5PartWrapperForPT::writeStepHeader().
get_temperature()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::get_temperature () const
Definition at line 1073 of file PartBunchBase.hpp.
Referenced by StatWriter::write().
getBConds()
template<class T, unsigned Dim> ParticleBConds<Position_t, Dimension>& PartBunchBase< T, Dim >::getBConds () inline
Definition at line 527 of file PartBunchBase.h.
getBeta()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getBeta (int i) virtual
Definition at line 1724 of file PartBunchBase.hpp.
getBinGamma()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getBinGamma (int bin)
Get gamma of one bin.
Definition at line 420 of file PartBunchBase.hpp.
Referenced by AmrBoxLib::computeSelfFields_cycl().
getBoundingSphere()
template<class T , unsigned Dim> std::pair< Vector_t, double > PartBunchBase< T, Dim >::getBoundingSphere ()
Definition at line 918 of file PartBunchBase.hpp.
getCharge()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getCharge () const
get the total charge per simulation particle
Definition at line 1317 of file PartBunchBase.hpp.
Referenced by StatWriter::write(), DataSink::writeImpactStatistics(), H5PartWrapperForPT::writeStepHeader(), and H5PartWrapperForPC::writeStepHeader().
getChargePerParticle()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getChargePerParticle () const
get the macro particle charge
Definition at line 1323 of file PartBunchBase.hpp.
Referenced by Undulator::apply(), GreenWakeFunction::apply(), ParallelCyclotronTracker::computeSpaceChargeFields_m(), Distribution::doRestartOpalCycl(), Distribution::emitParticles(), Distribution::injectBeam(), Multipole::isFocusing(), and DataSink::writeImpactStatistics().
getCouplingConstant()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getCouplingConstant () const
Definition at line 1276 of file PartBunchBase.hpp.
getdE()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getdE () const
Definition at line 1700 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::print(), StatWriter::write(), H5PartWrapperForPT::writeStepHeader(), and H5PartWrapperForPC::writeStepHeader().
getDestroyNum()
template<class T , unsigned Dim> size_t PartBunchBase< T, Dim >::getDestroyNum () const
Definition at line 1917 of file PartBunchBase.hpp.
getDistType()
template<class T , unsigned Dim> DistributionType PartBunchBase< T, Dim >::getDistType () const
Definition at line 1676 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::initDistInGlobalFrame().
getdT()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getdT () const
Definition at line 1025 of file PartBunchBase.hpp.
Referenced by Undulator::apply(), BeamStrippingPhysics::apply(), ScatteringPhysics::apply(), Corrector::apply(), Degrader::applyToReferenceParticle(), Monitor::applyToReferenceParticle(), ParallelTTracker::autophaseCavities(), ParallelCyclotronTracker::bgf_main_collision_test(), Bend2D::calculateBendAngle(), Bend2D::calculateRefTrajectory(), ParallelTTracker::changeDT(), ParallelTTracker::computeParticleMatterInteraction(), MGPoissonSolver::computePotential(), Monitor::driftToCorrectPositionAndSave(), ThickTracker::dump_m(), Distribution::emitParticles(), ParallelTTracker::emitParticles(), ParallelTTracker::execute(), ParallelTTracker::findStartPosition(), Corrector::goOnline(), RBend3D::initialise(), ParallelCyclotronTracker::initializeTracking_m(), ParallelTTracker::prepareEmission(), PartBunchBase< double, 3 >::print(), ParallelTTracker::selectDT(), ParallelTTracker::setTime(), ParallelCyclotronTracker::setTimeStep(), PartBunchBase< double, 3 >::switchOffUnitlessPositions(), PartBunchBase< double, 3 >::switchToUnitlessPositions(), ParallelTTracker::timeIntegration2(), ParallelTTracker::updateReferenceParticle(), ParallelTTracker::updateRefToLabCSTrafo(), StatWriter::write(), and ParallelTTracker::writePhaseSpace().
getE()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getE () const
Definition at line 1648 of file PartBunchBase.hpp.
getEExtrema()
template<class T, unsigned Dim> virtual VectorPair_t PartBunchBase< T, Dim >::getEExtrema () pure virtual
Implemented in PartBunch, and AmrPartBunch.
getEmissionDeltaT()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getEmissionDeltaT ()
Definition at line 1742 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::prepareEmission(), and ParallelTTracker::selectDT().
getFieldLayout()
template<class T, unsigned Dim> virtual FieldLayout_t& PartBunchBase< T, Dim >::getFieldLayout () pure virtual
Implemented in PartBunch, and AmrPartBunch.
Referenced by H5PartWrapperForPC::writeStepData(), and H5PartWrapperForPT::writeStepData().
getFieldSolverType()
template<class T , unsigned Dim> FieldSolverType PartBunchBase< T, Dim >::getFieldSolverType () const
Return the fieldsolver type if we have a fieldsolver.
Definition at line 1361 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::computeSpaceChargeFields_m().
getGamma()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getGamma (int i) virtual
Definition at line 1718 of file PartBunchBase.hpp.
getGhostNum()
template<class T , unsigned Dim> size_t PartBunchBase< T, Dim >::getGhostNum () const
Definition at line 1922 of file PartBunchBase.hpp.
Referenced by P3MPoissonSolver::calculatePairForces().
getGlobalMeanR()
template<class T , unsigned Dim> Vector_t PartBunchBase< T, Dim >::getGlobalMeanR ()
Definition at line 1487 of file PartBunchBase.hpp.
getGlobalToLocalQuaternion()
template<class T , unsigned Dim> Quaternion_t PartBunchBase< T, Dim >::getGlobalToLocalQuaternion ()
Definition at line 1500 of file PartBunchBase.hpp.
getGlobalTrackStep()
template<class T , unsigned Dim> long long PartBunchBase< T, Dim >::getGlobalTrackStep () const
Definition at line 1389 of file PartBunchBase.hpp.
Referenced by Monitor::applyToReferenceParticle(), Distribution::doRestartOpalT(), ThickTracker::dump_m(), ParallelTTracker::dumpStats(), ParallelTTracker::execute(), H5PartWrapperForPT::writeStepHeader(), and H5PartWrapperForPC::writeStepHeader().
getIfBeamEmitting()
template<class T , unsigned Dim> bool PartBunchBase< T, Dim >::getIfBeamEmitting ()
Definition at line 91 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::boundp(), ParallelTTracker::emitParticles(), and ParallelTTracker::selectDT().
getInitialBeta()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getInitialBeta () const
Definition at line 1706 of file PartBunchBase.hpp.
Referenced by ThickTracker::advanceDispersion_m(), and ThickTracker::updateParticle_m().
getInitialGamma()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getInitialGamma () const
Definition at line 1712 of file PartBunchBase.hpp.
Referenced by Distribution::createOpalCycl(), and ThickTracker::updateParticle_m().
getKs3DRefp()
template<class T, unsigned Dim> Vector_t PartBunchBase< T, Dim >::getKs3DRefp ()
getKs3DRefr()
template<class T, unsigned Dim> Vector_t PartBunchBase< T, Dim >::getKs3DRefr ()
getLastemittedBin()
template<class T , unsigned Dim> int PartBunchBase< T, Dim >::getLastemittedBin ()
Definition at line 322 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::computeSpaceChargeFields_m(), and ParallelCyclotronTracker::deleteParticle().
getLastEmittedEnergyBin()
template<class T , unsigned Dim> int PartBunchBase< T, Dim >::getLastEmittedEnergyBin ()
Definition at line 105 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::computeSpaceChargeFields().
getLayout() [1/2]
template<class T , unsigned Dim> ParticleLayout< T, Dim > & PartBunchBase< T, Dim >::getLayout ()
Definition at line 1937 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::boundp(), AmrBoxLib::create(), AmrYtWriter::writeBunch(), and AmrYtWriter::writeParticles_m().
getLayout() [2/2]
template<class T , unsigned Dim> const ParticleLayout< T, Dim > & PartBunchBase< T, Dim >::getLayout () const
Definition at line 1942 of file PartBunchBase.hpp.
getLoadBalance()
template<class T , unsigned Dim> size_t PartBunchBase< T, Dim >::getLoadBalance (int p) const
Definition at line 1255 of file PartBunchBase.hpp.
Referenced by LBalWriter::write().
getLocalBoundingSphere()
template<class T , unsigned Dim> std::pair< Vector_t, double > PartBunchBase< T, Dim >::getLocalBoundingSphere ()
Definition at line 931 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::computeParticleMatterInteraction().
getLocalBounds()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::getLocalBounds (Vector_t & rmin, Vector_t & rmax) const
Definition at line 897 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::get_bounds(), and PartBunchBase< double, 3 >::getLocalBoundingSphere().
getLocalNum()
template<class T , unsigned Dim> size_t PartBunchBase< T, Dim >::getLocalNum () const
Definition at line 1911 of file PartBunchBase.hpp.
Referenced by ScatteringPhysics::addParticleBackToBunch(), ThickTracker::advanceParticles_m(), CSRIGFWakeFunction::apply(), CSRWakeFunction::apply(), Undulator::apply(), GreenWakeFunction::apply(), Tracker::applyDrift(), Tracker::applyTransform(), ParallelCyclotronTracker::bgf_main_collision_test(), ParallelCyclotronTracker::borisExternalFields(), PartBunchBase< double, 3 >::boundp_destroyCycl(), PartBunchBase< double, 3 >::boundp_destroyT(), ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), ParallelCyclotronTracker::bunchDumpStatData(), ParallelCyclotronTracker::bunchMode_m(), MultiBunchHandler::calcBunchBeamParameters(), PartBunchBase< double, 3 >::calcGammas(), PartBunchBase< double, 3 >::calcGammas_cycl(), PartBunchBase< double, 3 >::calcLineDensity(), ParallelCyclotronTracker::calcMeanP(), PartBunchBase< double, 3 >::calcMeanPhi(), ParallelCyclotronTracker::calcMeanR(), PartBunchBase< double, 3 >::calcNumPartsOutside(), P3MPoissonSolver::calculatePairForces(), ParallelTTracker::changeDT(), ParallelCyclotronTracker::checkNumPart(), Vacuum::checkVacuum(), ParallelTTracker::computeExternalFields(), ParallelTTracker::computeParticleMatterInteraction(), ParallelCyclotronTracker::computePathLengthUpdate(), ParallelTTracker::computeSpaceChargeFields(), ParallelTTracker::computeWakefield(), ScatteringPhysics::copyFromBunch(), PartBunchBase< double, 3 >::countTotalNumPerBunch(), Distribution::createOpalCycl(), ParallelCyclotronTracker::deleteParticle(), PartBunchBase< double, 3 >::destroyT(), Septum::doCheck(), Probe::doCheck(), Stripper::doCheck(), CCollimator::doCheck(), OutputPlane::doCheck(), CCollimator::doFinaliseCheck(), BeamStrippingPhysics::doPhysics(), Distribution::doRestartOpalCycl(), Distribution::emitParticles(), PartBunchBase< double, 3 >::end(), ParallelTTracker::evenlyDistributeParticles(), ParallelCyclotronTracker::finalizeTracking_m(), PartBunchBase< double, 3 >::gatherLoadBalanceStatistics(), PartBunchBase< double, 3 >::getLocalBounds(), ParallelCyclotronTracker::globalToLocal(), Degrader::goOnline(), MultiBunchHandler::injectBunch(), ParallelCyclotronTracker::kick(), ParallelTTracker::kickParticles(), ParallelCyclotronTracker::localToGlobal(), PartBunchBase< double, 3 >::maximumAmplitudes(), PartBunchBase< T, Dim >::ConstIterator::operator*(), AmrBoxLib::postRegrid_m(), ParallelCyclotronTracker::push(), PartBunchBase< double, 3 >::push_back(), ParallelTTracker::pushParticles(), MultiBunchHandler::readBunch(), PartBunchBase< double, 3 >::resetPartBinBunch(), PartBunchBase< double, 3 >::resetPartBinID2(), ParallelCyclotronTracker::rotateAroundX(), ParallelCyclotronTracker::rotateAroundZ(), ParallelCyclotronTracker::rotateWithQuaternion(), MultiBunchHandler::saveBunch(), ParallelCyclotronTracker::seoMode_m(), ParallelTTracker::setTime(), ParallelCyclotronTracker::singleMode_m(), ParallelCyclotronTracker::singleParticleDump(), PartBunchBase< double, 3 >::swap(), PartBunchBase< double, 3 >::switchOffUnitlessPositions(), PartBunchBase< double, 3 >::switchToUnitlessPositions(), ParallelTTracker::timeIntegration2(), ParallelTTracker::transformBunch(), ThickTracker::update_m(), PartBunchBase< double, 3 >::updateNumTotal(), Vacuum::updateParticleAttributes(), StatWriter::write(), ParallelTTracker::writePhaseSpace(), H5PartWrapperForPT::writeStepData(), and H5PartWrapperForPC::writeStepData().
getLocalNumPerBunch()
template<class T , unsigned Dim> size_t PartBunchBase< T, Dim >::getLocalNumPerBunch (short n) const
Definition at line 1448 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::deleteParticle().
getLocalTrackStep()
template<class T , unsigned Dim> long long PartBunchBase< T, Dim >::getLocalTrackStep () const
Definition at line 1407 of file PartBunchBase.hpp.
Referenced by MGPoissonSolver::computeMap(), MGPoissonSolver::computePotential(), AmrBoxLib::computeSelfFields_cycl(), Distribution::doRestartOpalT(), ParallelCyclotronTracker::initializeTracking_m(), ParallelCyclotronTracker::initTrackOrbitFile(), H5PartWrapperForPC::writeStepHeader(), and H5PartWrapperForPT::writeStepHeader().
getM()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getM () const
Definition at line 1636 of file PartBunchBase.hpp.
Referenced by ScatteringPhysics::apply(), Degrader::applyToReferenceParticle(), MultiBunchHandler::calcBunchBeamParameters(), BendBase::calcDesignRadius(), BendBase::calcFieldAmplitude(), BendBase::calcGamma(), CSRIGFWakeFunction::calculateGreenFunction(), Distribution::createOpalCycl(), Distribution::createOpalT(), Distribution::doRestartOpalCycl(), ParallelTTracker::execute(), ParallelCyclotronTracker::finalizeTracking_m(), ParallelTTracker::findStartPosition(), PartBunchBase< double, 3 >::get_pmean_Distribution(), Corrector::goOnline(), PartBunchBase< T, Dim >::ConstIterator::operator*(), H5PartWrapperForPC::readStepHeader(), ParallelCyclotronTracker::RFkick(), Corrector::setDesignEnergy(), Distribution::setupEmissionModelAstra(), Distribution::setupEmissionModelNone(), Distribution::setupParticleBins(), Vacuum::updateParticleAttributes(), H5PartWrapperForPT::writeStepHeader(), and H5PartWrapperForPC::writeStepHeader().
getMassPerParticle()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getMassPerParticle () const
Definition at line 1328 of file PartBunchBase.hpp.
Referenced by Distribution::emitParticles(), and Distribution::injectBeam().
getMomentumTolerance()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getMomentumTolerance () const
Definition at line 1682 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::checkFileMomentum(), and Distribution::createOpalT().
getNumberOfEmissionSteps()
template<class T , unsigned Dim> size_t PartBunchBase< T, Dim >::getNumberOfEmissionSteps ()
Definition at line 116 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::prepareEmission().
getNumberOfEnergyBins()
template<class T , unsigned Dim> int PartBunchBase< T, Dim >::getNumberOfEnergyBins ()
Definition at line 122 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::boundp_destroyT(), ParallelTTracker::computeSpaceChargeFields(), PartBunchBase< double, 3 >::destroyT(), and ParallelTTracker::prepareEmission().
getNumBunch()
template<class T , unsigned Dim> short PartBunchBase< T, Dim >::getNumBunch () const
Definition at line 1421 of file PartBunchBase.hpp.
Referenced by MultiBunchHandler::calcBunchBeamParameters(), ParallelCyclotronTracker::deleteParticle(), Distribution::doRestartOpalCycl(), ParallelCyclotronTracker::execute(), AmrBoxLib::initFineLevels(), ParallelCyclotronTracker::initializeTracking_m(), MultiBunchHandler::MultiBunchHandler(), H5PartWrapperForPC::readStepData(), and H5PartWrapperForPC::writeStepHeader().
getP()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getP () const
Definition at line 1642 of file PartBunchBase.hpp.
Referenced by Distribution::createOpalT(), and Distribution::setupParticleBins().
getParticle()
template<class T , unsigned Dim> OpalParticle PartBunchBase< T, Dim >::getParticle (int ii)
Definition at line 977 of file PartBunchBase.hpp.
Referenced by Tracker::applyDrift(), Tracker::applyTransform(), and PartBunchBase< double, 3 >::maximumAmplitudes().
getPOrigin()
template<class T , unsigned Dim> ParticleOrigin PartBunchBase< T, Dim >::getPOrigin () const
Definition at line 1654 of file PartBunchBase.hpp.
Referenced by Stripper::doFinaliseCheck().
getPType()
template<class T , unsigned Dim> ParticleType PartBunchBase< T, Dim >::getPType () const
Definition at line 1665 of file PartBunchBase.hpp.
Referenced by BeamStrippingPhysics::apply(), ScatteringPhysics::apply(), ScatteringPhysics::computeEnergyLoss(), Distribution::emitParticles(), and Distribution::injectBeam().
getPx()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getPx (int i) virtual
Definition at line 815 of file PartBunchBase.hpp.
getPx0()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getPx0 (int i) virtual
Definition at line 830 of file PartBunchBase.hpp.
getPy()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getPy (int i) virtual
Definition at line 820 of file PartBunchBase.hpp.
getPy0()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getPy0 (int i) virtual
Definition at line 835 of file PartBunchBase.hpp.
getPz()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getPz (int i) virtual
Definition at line 825 of file PartBunchBase.hpp.
getQ()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getQ () const
Access to reference data.
Definition at line 1630 of file PartBunchBase.hpp.
Referenced by ScatteringPhysics::apply(), Degrader::applyToReferenceParticle(), BendBase::calcDesignRadius(), BendBase::calcFieldAmplitude(), Distribution::createOpalCycl(), Distribution::createOpalT(), Distribution::emitParticles(), RBend::findChordLength(), Bend2D::findIdealBendParameters(), RBend3D::initialise(), RFCavity::initialise(), ParallelCyclotronTracker::RFkick(), Vacuum::updateParticleAttributes(), H5PartWrapperForPT::writeStepHeader(), and H5PartWrapperForPC::writeStepHeader().
getQKs3D()
template<class T, unsigned Dim> Quaternion_t PartBunchBase< T, Dim >::getQKs3D ()
getReference()
template<class T , unsigned Dim> const PartData * PartBunchBase< T, Dim >::getReference () const
Definition at line 1736 of file PartBunchBase.hpp.
Referenced by Bend2D::setupPusher(), RFCavity::trackOnAxisParticle(), and RBend3D::trackRefParticleThrough().
getRho()
template<class T, unsigned Dim> virtual double PartBunchBase< T, Dim >::getRho (int x, int y, int z) pure virtual
Implemented in AmrPartBunch, and PartBunch.
Referenced by H5PartWrapperForPC::writeStepData(), and H5PartWrapperForPT::writeStepData().
getSigmaMatrix()
template<class T , unsigned Dim> FMatrix< double, 2 *Dim, 2 *Dim > PartBunchBase< T, Dim >::getSigmaMatrix () const
Definition at line 2020 of file PartBunchBase.hpp.
Referenced by ThickTracker::track_m(), and StatWriter::write().
getStepsPerTurn()
template<class T , unsigned Dim> int PartBunchBase< T, Dim >::getStepsPerTurn () const
Definition at line 1377 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::initializeTracking_m().
getSteptoLastInj()
template<class T , unsigned Dim> int PartBunchBase< T, Dim >::getSteptoLastInj () const
Definition at line 1512 of file PartBunchBase.hpp.
Referenced by Distribution::doRestartOpalCycl(), and H5PartWrapperForPC::writeStepHeader().
getT()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getT () const
Definition at line 1043 of file PartBunchBase.hpp.
Referenced by Undulator::apply(), ScatteringPhysics::apply(), ParallelTTracker::applyFractionalStep(), ParallelCyclotronTracker::applyPluginElements(), ParallelTTracker::autophaseCavities(), ParallelCyclotronTracker::bgf_main_collision_test(), ParallelCyclotronTracker::borisExternalFields(), ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), ParallelCyclotronTracker::bunchDumpStatData(), MultiBunchHandler::calcBunchBeamParameters(), ParallelTTracker::computeExternalFields(), ParallelTTracker::computeParticleMatterInteraction(), AmrBoxLib::computeSelfFields_cycl(), BeamStrippingPhysics::doPhysics(), Distribution::doRestartOpalT(), ThickTracker::dump_m(), ParallelTTracker::dumpStats(), ParallelTTracker::emitParticles(), ParallelTTracker::execute(), AmrBoxLib::getT(), AmrBoxLib::initFineLevels(), ParallelCyclotronTracker::initializeTracking_m(), PartBunchBase< T, Dim >::ConstIterator::operator*(), PartBunchBase< double, 3 >::print(), ParallelCyclotronTracker::push(), ParallelCyclotronTracker::saveInjectValues(), ThickTracker::update_m(), ParallelTTracker::updateReferenceParticle(), ParallelCyclotronTracker::updateTime(), LBalWriter::write(), GridLBalWriter::write(), MemoryWriter::write(), StatWriter::write(), MemoryProfiler::write(), DataSink::writeImpactStatistics(), ParallelTTracker::writePhaseSpace(), H5PartWrapperForPT::writeStepHeader(), and H5PartWrapperForPC::writeStepHeader().
getTEmission()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getTEmission ()
Definition at line 260 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::prepareEmission().
getTotalNum()
template<class T , unsigned Dim> size_t PartBunchBase< T, Dim >::getTotalNum () const
Definition at line 1906 of file PartBunchBase.hpp.
Referenced by Undulator::apply(), ParallelCyclotronTracker::applyPluginElements(), PartBunchBase< double, 3 >::boundp(), ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), ParallelCyclotronTracker::bunchMode_m(), PartBunchBase< double, 3 >::calcGammas(), ParallelCyclotronTracker::calcMeanP(), ParallelCyclotronTracker::calcMeanR(), ParallelTTracker::computeExternalFields(), ParallelTTracker::computeParticleMatterInteraction(), ParallelCyclotronTracker::computePathLengthUpdate(), PartBunchBase< double, 3 >::countTotalNumPerBunch(), Distribution::createOpalCycl(), PartBunchBase< double, 3 >::destroyT(), Probe::doInitialise(), Distribution::doRestartOpalCycl(), Distribution::doRestartOpalT(), ThickTracker::dump_m(), ParallelTTracker::emitParticles(), ParallelTTracker::evenlyDistributeParticles(), ParallelTTracker::execute(), ParallelCyclotronTracker::finalizeTracking_m(), ParallelCyclotronTracker::GenericTracker(), Monitor::initialise(), MultiBunchHandler::injectBunch(), ParallelCyclotronTracker::MtsTracker(), MultiBunchHandler::MultiBunchHandler(), PartBunchBase< double, 3 >::print(), PartBunchBase< double, 3 >::setCharge(), PartBunchBase< double, 3 >::setMass(), ParallelCyclotronTracker::update_m(), StatWriter::write(), AmrYtWriter::writeBunch(), DataSink::writeImpactStatistics(), H5Writer::writePhaseSpace(), ParallelTTracker::writePhaseSpace(), H5PartWrapperForPC::writeStep(), and H5PartWrapperForPT::writeStep().
getTotalNumPerBunch()
template<class T , unsigned Dim> size_t PartBunchBase< T, Dim >::getTotalNumPerBunch (short n) const
Definition at line 1434 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::calcMeanR(), and ParallelCyclotronTracker::computePathLengthUpdate().
getUpdateFlag()
template<class T , unsigned Dim> bool PartBunchBase< T, Dim >::getUpdateFlag (UpdateFlags_t f) const
Definition at line 1947 of file PartBunchBase.hpp.
getX()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getX (int i) virtual
Definition at line 841 of file PartBunchBase.hpp.
getX0()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getX0 (int i) virtual
Definition at line 859 of file PartBunchBase.hpp.
getY()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getY (int i) virtual
Definition at line 847 of file PartBunchBase.hpp.
getY0()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getY0 (int i) virtual
Definition at line 865 of file PartBunchBase.hpp.
getZ()
template<class T , unsigned Dim> double PartBunchBase< T, Dim >::getZ (int i) virtual
Definition at line 853 of file PartBunchBase.hpp.
ghostDestroy()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::ghostDestroy (size_t M, size_t I)
Definition at line 2010 of file PartBunchBase.hpp.
globalCreate()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::globalCreate (size_t np)
Definition at line 1995 of file PartBunchBase.hpp.
hasBinning()
template<class T , unsigned Dim> bool PartBunchBase< T, Dim >::hasBinning () const
Definition at line 248 of file PartBunchBase.hpp.
Referenced by H5PartWrapperForPC::writeStepData().
hasFieldSolver()
template<class T , unsigned Dim> bool PartBunchBase< T, Dim >::hasFieldSolver ()
Definition at line 1351 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::bunchMode_m(), ParallelTTracker::computeExternalFields(), ParallelTTracker::computeParticleMatterInteraction(), AmrBoxLib::computeSelfFields_cycl(), ParallelTTracker::computeWakefield(), ParallelTTracker::doBinaryRepartition(), ParallelTTracker::evenlyDistributeParticles(), ParallelCyclotronTracker::getFieldsAtPoint(), and ParallelCyclotronTracker::MtsTracker().
incrementT()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::incrementT ()
Definition at line 1037 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::computeParticleMatterInteraction(), and ParallelTTracker::execute().
incTrackSteps()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::incTrackSteps ()
Definition at line 1401 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::execute().
initialize()
template<class T, unsigned Dim> virtual void PartBunchBase< T, Dim >::initialize (FieldLayout_t * fLayout) pure virtual
Implemented in PartBunch, and AmrPartBunch.
Referenced by PartBunchBase< double, 3 >::setSolver().
isGridFixed()
template<class T , unsigned Dim> bool PartBunchBase< T, Dim >::isGridFixed () const
Definition at line 242 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::boundp().
iterateEmittedBin()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::iterateEmittedBin (int binNumber)
Definition at line 1748 of file PartBunchBase.hpp.
Referenced by Distribution::emitParticles(), and Distribution::injectBeam().
maximumAmplitudes()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::maximumAmplitudes (const FMatrix< double, 6, 6 > & D, double & axmax, double & aymax)
Return maximum amplitudes.
Definition at line 986 of file PartBunchBase.hpp.
performDestroy()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::performDestroy (bool updateLocalNum = false)
Definition at line 2005 of file PartBunchBase.hpp.
Referenced by ScatteringPhysics::copyFromBunch(), ParallelCyclotronTracker::deleteParticle(), and PartBunchBase< double, 3 >::destroyT().
print()
template<class T , unsigned Dim> Inform & PartBunchBase< T, Dim >::print (Inform & os)
Definition at line 1759 of file PartBunchBase.hpp.
Referenced by Undulator::apply(), and PartBunch::print().
push_back()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::push_back (OpalParticle const & p)
Definition at line 944 of file PartBunchBase.hpp.
Referenced by Tracker::addToBunch().
Rebin()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::Rebin ()
Definition at line 128 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::emitParticles().
rebin()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::rebin ()
Definition at line 313 of file PartBunchBase.hpp.
resetID()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::resetID ()
Definition at line 1962 of file PartBunchBase.hpp.
resetInterpolationCache()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::resetInterpolationCache (bool clearCache = false) virtual
Reimplemented in PartBunch.
Definition at line 1821 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::computeSpaceChargeFields(), and ParallelTTracker::emitParticles().
resetM()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::resetM (double m)
Definition at line 1694 of file PartBunchBase.hpp.
Referenced by Stripper::doFinaliseCheck().
resetPartBinBunch()
template<class T , unsigned Dim> bool PartBunchBase< T, Dim >::resetPartBinBunch ()
Definition at line 1608 of file PartBunchBase.hpp.
Referenced by MultiBunchHandler::updateParticleBins().
resetPartBinID2()
template<class T , unsigned Dim> bool PartBunchBase< T, Dim >::resetPartBinID2 (const double eta)
reset Bin[] for each particle according to the method given in paper PAST-AB(064402) by G. Fubiani et al.
Definition at line 1557 of file PartBunchBase.hpp.
Referenced by MultiBunchHandler::updateParticleBins().
resetQ()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::resetQ (double q)
Set reference data
Definition at line 1688 of file PartBunchBase.hpp.
Referenced by Stripper::doFinaliseCheck().
resizeMesh()
template<class T, unsigned Dim> virtual void PartBunchBase< T, Dim >::resizeMesh () inline virtual
Reimplemented in PartBunch.
Definition at line 506 of file PartBunchBase.h.
runTests()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::runTests () virtual
Definition at line 1815 of file PartBunchBase.hpp.
set_meshEnlargement()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::set_meshEnlargement (double dh) virtual
Reimplemented in AmrPartBunch.
Definition at line 1238 of file PartBunchBase.hpp.
Referenced by FieldSolver::initAmrObject_m(), FieldSolver::initSolver(), and AmrPartBunch::set_meshEnlargement().
set_sPos()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::set_sPos (double s)
Definition at line 1055 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::execute(), ThickTracker::execute(), H5PartWrapperForPT::readStepHeader(), H5PartWrapperForPC::readStepHeader(), ThickTracker::update_m(), ParallelCyclotronTracker::updatePathLength(), and ParallelTTracker::writePhaseSpace().
setBCAllOpen()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setBCAllOpen () virtual
Reimplemented in AmrPartBunch, and PartBunch.
Definition at line 1854 of file PartBunchBase.hpp.
Referenced by TrackRun::setupFieldsolver().
setBCAllPeriodic()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setBCAllPeriodic () virtual
Reimplemented in AmrPartBunch, and PartBunch.
Definition at line 1848 of file PartBunchBase.hpp.
setBCForDCBeam()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setBCForDCBeam () virtual
Reimplemented in AmrPartBunch, and PartBunch.
Definition at line 1860 of file PartBunchBase.hpp.
Referenced by TrackRun::setupFieldsolver().
setBConds()
template<class T, unsigned Dim> void PartBunchBase< T, Dim >::setBConds (const ParticleBConds< Position_t, Dimension > & bc) inline
Definition at line 531 of file PartBunchBase.h.
setBeamFrequency()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setBeamFrequency (double v)
Definition at line 2015 of file PartBunchBase.hpp.
Referenced by TrackRun::setupTTracker().
setBinCharge() [1/2]
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setBinCharge (int bin, double q) virtual
Set the charge of one bin to the value of q and all other to zero.
Reimplemented in AmrPartBunch.
Definition at line 426 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::computeSpaceChargeFields(), and ParallelCyclotronTracker::computeSpaceChargeFields_m().
setBinCharge() [2/2]
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setBinCharge (int bin) virtual
Set the charge of all other the ones in bin to zero.
Reimplemented in AmrPartBunch.
Definition at line 432 of file PartBunchBase.hpp.
setCharge()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setCharge (double q)
Definition at line 1288 of file PartBunchBase.hpp.
Referenced by TrackRun::setupCyclotronTracker(), TrackRun::setupThickTracker(), and TrackRun::setupTTracker().
setChargeZeroPart()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setChargeZeroPart (double q)
Definition at line 1298 of file PartBunchBase.hpp.
Referenced by TrackRun::setupThickTracker(), and TrackRun::setupTTracker().
setCouplingConstant()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setCouplingConstant (double c)
Definition at line 1282 of file PartBunchBase.hpp.
Referenced by TrackRun::setupCyclotronTracker(), TrackRun::setupThickTracker(), and TrackRun::setupTTracker().
setDistribution() [1/2]
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setDistribution (Distribution * d, std::vector< Distribution *> addedDistributions, size_t & np)
Definition at line 218 of file PartBunchBase.hpp.
Referenced by TrackRun::setDistributionParallelT(), and TrackRun::setupCyclotronTracker().
setDistribution() [2/2]
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setDistribution (Distribution * d, size_t numberOfParticles, double current, const Beamline & bl)
Definition at line 232 of file PartBunchBase.hpp.
setdT()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setdT (double dt)
Definition at line 1019 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::computeParticleMatterInteraction(), ParallelTTracker::execute(), ParallelTTracker::selectDT(), TrackRun::setupCyclotronTracker(), TrackRun::setupThickTracker(), TrackRun::setupTTracker(), and ThickTracker::update_m().
setEnergyBins()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setEnergyBins (int numberOfEnergyBins)
Definition at line 145 of file PartBunchBase.hpp.
Referenced by Distribution::initializeBeam(), and PartBunchBase< double, 3 >::setPBins().
setGlobalMeanR()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setGlobalMeanR (Vector_t globalMeanR)
Definition at line 1481 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::computeSpaceChargeFields(), and ParallelCyclotronTracker::computeSpaceChargeFields_m().
setGlobalToLocalQuaternion()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setGlobalToLocalQuaternion (Quaternion_t globalToLocalQuaternion)
Definition at line 1493 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::computeSpaceChargeFields_m().
setGlobalTrackStep()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setGlobalTrackStep (long long n)
step in multiple TRACK commands
Definition at line 1383 of file PartBunchBase.hpp.
Referenced by H5PartWrapperForPC::readStepHeader(), H5PartWrapperForPT::readStepHeader(), and ThickTracker::update_m().
setKs3DRefp()
template<class T, unsigned Dim> void PartBunchBase< T, Dim >::setKs3DRefp (Vector_t p)
setKs3DRefr()
template<class T, unsigned Dim> void PartBunchBase< T, Dim >::setKs3DRefr (Vector_t r)
setLocalBinCount()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setLocalBinCount (size_t num, int bin)
Definition at line 331 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::deleteParticle().
setLocalNum()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setLocalNum (size_t n)
Definition at line 1932 of file PartBunchBase.hpp.
setLocalNumPerBunch()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setLocalNumPerBunch (size_t numpart, short n)
Definition at line 1441 of file PartBunchBase.hpp.
Referenced by MultiBunchHandler::calcBunchBeamParameters(), ParallelCyclotronTracker::deleteParticle(), MultiBunchHandler::injectBunch(), and MultiBunchHandler::readBunch().
setLocalTrackStep()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setLocalTrackStep (long long n)
step in a TRACK command
Definition at line 1395 of file PartBunchBase.hpp.
Referenced by H5PartWrapperForPC::readStepHeader(), H5PartWrapperForPT::readStepHeader(), TrackRun::setupThickTracker(), TrackRun::setupTTracker(), and ParallelCyclotronTracker::update_m().
setMass()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setMass (double mass)
Definition at line 1304 of file PartBunchBase.hpp.
Referenced by TrackRun::setupCyclotronTracker(), and TrackRun::setupTTracker().
setMassZeroPart()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setMassZeroPart (double mass)
Definition at line 1311 of file PartBunchBase.hpp.
Referenced by TrackRun::setupTTracker().
setNumBunch()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setNumBunch (short n)
Definition at line 1413 of file PartBunchBase.hpp.
Referenced by Distribution::initializeBeam(), MultiBunchHandler::injectBunch(), and H5PartWrapperForPC::readStepHeader().
setParticle() [1/2]
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setParticle (FVector< double, 6 > z, int ii)
Definition at line 959 of file PartBunchBase.hpp.
Referenced by Tracker::applyDrift(), and Tracker::applyTransform().
setParticle() [2/2]
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setParticle (OpalParticle const & p, int ii)
Definition at line 970 of file PartBunchBase.hpp.
setPBins() [1/2]
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setPBins (PartBins * pbin)
Definition at line 284 of file PartBunchBase.hpp.
Referenced by Distribution::createOpalCycl(), Distribution::doRestartOpalCycl(), and MultiBunchHandler::MultiBunchHandler().
setPBins() [2/2]
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setPBins (PartBinsCyc * pbin)
Definition at line 292 of file PartBunchBase.hpp.
setPOrigin()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setPOrigin (ParticleOrigin origin)
Definition at line 1659 of file PartBunchBase.hpp.
Referenced by Stripper::doCheck().
setPType()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setPType (const std::string & type)
Definition at line 1670 of file PartBunchBase.hpp.
Referenced by TrackRun::setupCyclotronTracker(), and TrackRun::setupTTracker().
setQKs3D()
template<class T, unsigned Dim> void PartBunchBase< T, Dim >::setQKs3D (Quaternion_t q)
setSolver()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setSolver (FieldSolver * fs) virtual
CAN not re-inizialize ParticleLayout this is an IPPL issue
Reimplemented in AmrPartBunch.
Definition at line 1333 of file PartBunchBase.hpp.
Referenced by AmrPartBunch::setSolver(), and TrackRun::setupFieldsolver().
setStepsPerTurn()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setStepsPerTurn (int n)
Definition at line 1371 of file PartBunchBase.hpp.
Referenced by TrackRun::setupCyclotronTracker().
setSteptoLastInj()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setSteptoLastInj (int n)
Definition at line 1506 of file PartBunchBase.hpp.
Referenced by H5PartWrapperForPC::readStepHeader().
setT()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setT (double t)
Definition at line 1031 of file PartBunchBase.hpp.
Referenced by Undulator::apply(), ParallelTTracker::applyFractionalStep(), ParallelTTracker::computeParticleMatterInteraction(), ParallelTTracker::execute(), ParallelTTracker::findStartPosition(), H5PartWrapperForPC::readStepHeader(), H5PartWrapperForPT::readStepHeader(), TrackRun::setupThickTracker(), TrackRun::setupTTracker(), ThickTracker::update_m(), and ParallelCyclotronTracker::updateTime().
setTEmission()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setTEmission (double t)
Definition at line 254 of file PartBunchBase.hpp.
Referenced by Distribution::initializeBeam().
setTotalNum()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setTotalNum (size_t n)
Definition at line 1927 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::deleteParticle(), PartBunchBase< double, 3 >::destroyT(), and PartBunchBase< double, 3 >::updateNumTotal().
setTotalNumPerBunch()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setTotalNumPerBunch (size_t numpart, short n)
Definition at line 1427 of file PartBunchBase.hpp.
Referenced by MultiBunchHandler::calcBunchBeamParameters(), ParallelCyclotronTracker::deleteParticle(), MultiBunchHandler::injectBunch(), and MultiBunchHandler::readBunch().
setup()
template<class T, unsigned Dim> void PartBunchBase< T, Dim >::setup (AbstractParticle< T, Dim > * pb) private
Definition at line 1871 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::PartBunchBase().
setUpdateFlag()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setUpdateFlag (UpdateFlags_t f, bool val)
Definition at line 1952 of file PartBunchBase.hpp.
setZ()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::setZ (int i, double zcoo) virtual
Definition at line 871 of file PartBunchBase.hpp.
singleInitNode()
template<class T , unsigned Dim> bool PartBunchBase< T, Dim >::singleInitNode () const
Definition at line 1957 of file PartBunchBase.hpp.
swap()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::swap (unsigned int i, unsigned int j) virtual
Reimplemented in PartBunch.
Definition at line 1826 of file PartBunchBase.hpp.
Referenced by PartBunch::swap().
switchOffUnitlessPositions()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::switchOffUnitlessPositions (bool use_dt_per_particle = false)
Definition at line 188 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::emitParticles(), and ParallelTTracker::pushParticles().
switchToUnitlessPositions()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::switchToUnitlessPositions (bool use_dt_per_particle = false)
Definition at line 164 of file PartBunchBase.hpp.
Referenced by ParallelTTracker::emitParticles(), and ParallelTTracker::pushParticles().
update() [1/2]
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::update ()
Definition at line 1967 of file PartBunchBase.hpp.
update() [2/2]
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::update (const ParticleAttrib< char > & canSwap)
Definition at line 1976 of file PartBunchBase.hpp.
updateDomainLength()
template<class T, unsigned Dim> virtual void PartBunchBase< T, Dim >::updateDomainLength (Vektor< int, 3 > & grid) private pure virtual
Implemented in AmrPartBunch, and PartBunch.
Referenced by PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::boundp_destroyCycl(), PartBunchBase< double, 3 >::boundp_destroyT(), and PartBunchBase< double, 3 >::calcLineDensity().
updateFields()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::updateFields (const Vector_t & hr, const Vector_t & origin) private virtual
Reimplemented in AmrPartBunch, and PartBunch.
Definition at line 1866 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::boundp(), and PartBunchBase< double, 3 >::boundp_destroyCycl().
updateNumTotal()
template<class T , unsigned Dim> void PartBunchBase< T, Dim >::updateNumTotal ()
Definition at line 305 of file PartBunchBase.hpp.
Referenced by ParallelCyclotronTracker::applyPluginElements(), ParallelTTracker::computeParticleMatterInteraction(), ParallelTTracker::emitParticles(), and ParallelCyclotronTracker::MtsTracker().
weHaveBins()
template<class T , unsigned Dim> bool PartBunchBase< T, Dim >::weHaveBins () const
Definition at line 275 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::boundp_destroyCycl(), Stripper::doCheck(), and ParallelCyclotronTracker::isMultiBunch().
weHaveEnergyBins()
template<class T , unsigned Dim> bool PartBunchBase< T, Dim >::weHaveEnergyBins ()
Definition at line 154 of file PartBunchBase.hpp.
Referenced by PartBunchBase< double, 3 >::boundp_destroyT(), ParallelTTracker::computeSpaceChargeFields(), PartBunchBase< double, 3 >::destroyT(), ParallelTTracker::emitParticles(), and ParallelTTracker::execute().
Member Data Documentation
Bf
template<class T, unsigned Dim> ParticleAttrib< Vector_t > PartBunchBase< T, Dim >::Bf
Definition at line 583 of file PartBunchBase.h.
Referenced by ScatteringPhysics::addParticleBackToBunch(), ParallelCyclotronTracker::borisExternalFields(), ParallelCyclotronTracker::bunchMode_m(), ParallelTTracker::computeExternalFields(), AmrBoxLib::computeSelfFields_cycl(), ParallelTTracker::computeSpaceChargeFields(), ParallelCyclotronTracker::computeSpaceChargeFields_m(), ScatteringPhysics::copyFromBunch(), Distribution::emitParticles(), ParallelTTracker::execute(), ParallelCyclotronTracker::getFieldsAtPoint(), Distribution::injectBeam(), ParallelCyclotronTracker::kick(), ParallelTTracker::kickParticles(), PartBunchBase< double, 3 >::setup(), PartBunchBase< double, 3 >::swap(), ParallelTTracker::transformBunch(), AmrYtWriter::writeParticles_m(), H5PartWrapperForPT::writeStepData(), and H5PartWrapperForPC::writeStepData().
Bin
template<class T, unsigned Dim> ParticleAttrib< int > PartBunchBase< T, Dim >::Bin
Definition at line 584 of file PartBunchBase.h.
Referenced by ScatteringPhysics::addParticleBackToBunch(), Stepper< FieldFunction, Arguments... >::advance(), Degrader::apply(), Ring::apply(), Cyclotron::apply(), ParallelCyclotronTracker::bgf_main_collision_test(), PartBunchBase< double, 3 >::boundp_destroyCycl(), PartBunchBase< double, 3 >::boundp_destroyT(), ParallelCyclotronTracker::bunchMode_m(), PartBunchBase< double, 3 >::calcGammas(), PartBunchBase< double, 3 >::calcGammas_cycl(), PartBunchBase< double, 3 >::calcMeanPhi(), Vacuum::checkVacuum(), ParallelTTracker::computeExternalFields(), AmrBoxLib::computeSelfFields_cycl(), ScatteringPhysics::copyFromBunch(), ParallelCyclotronTracker::deleteParticle(), PartBunchBase< double, 3 >::destroyT(), Septum::doCheck(), Stripper::doCheck(), CCollimator::doCheck(), BeamStrippingPhysics::doPhysics(), Distribution::emitParticles(), ParallelCyclotronTracker::initDistInGlobalFrame(), Distribution::injectBeam(), ParallelCyclotronTracker::kick(), ParallelCyclotronTracker::push(), MultiBunchHandler::readBunch(), H5PartWrapperForPC::readStepData(), H5PartWrapperForPT::readStepData(), PartBunchBase< double, 3 >::Rebin(), PartBunchBase< double, 3 >::rebin(), PartBunchBase< double, 3 >::resetPartBinBunch(), PartBunchBase< double, 3 >::resetPartBinID2(), PartBunchBase< double, 3 >::setBinCharge(), PartBunchBase< double, 3 >::setup(), ParallelCyclotronTracker::singleMode_m(), AmrBoxLib::solvePoisson_m(), PartBunchBase< double, 3 >::swap(), AmrBoxLib::tagForChargeDensity_m(), AmrYtWriter::writeParticles_m(), and H5PartWrapperForPC::writeStepData().
binemitted_m
template<class T, unsigned Dim> std::unique_ptr<size_t[]> PartBunchBase< T, Dim >::binemitted_m protected
Definition at line 694 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp_destroyT(), PartBunchBase< double, 3 >::calcGammas(), PartBunchBase< double, 3 >::destroyT(), PartBunchBase< double, 3 >::iterateEmittedBin(), and PartBunchBase< double, 3 >::setEnergyBins().
bingamma_m
template<class T, unsigned Dim> std::unique_ptr<double[]> PartBunchBase< T, Dim >::bingamma_m protected
holds the gamma of the bin
Definition at line 689 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::calcGammas(), PartBunchBase< double, 3 >::calcGammas_cycl(), PartBunchBase< double, 3 >::getBinGamma(), and PartBunchBase< double, 3 >::setEnergyBins().
boundpBoundsTimer_m
template<class T, unsigned Dim> IpplTimings::TimerRef PartBunchBase< T, Dim >::boundpBoundsTimer_m protected
Definition at line 622 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::boundp_destroyCycl(), and PartBunchBase< double, 3 >::setup().
boundpTimer_m
template<class T, unsigned Dim> IpplTimings::TimerRef PartBunchBase< T, Dim >::boundpTimer_m protected
Definition at line 621 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::boundp_destroyCycl(), and PartBunchBase< double, 3 >::setup().
boundpUpdateTimer_m
template<class T, unsigned Dim> IpplTimings::TimerRef PartBunchBase< T, Dim >::boundpUpdateTimer_m protected
Definition at line 623 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::boundp_destroyCycl(), and PartBunchBase< double, 3 >::setup().
bunchLocalNum_m
template<class T, unsigned Dim> std::vector<size_t> PartBunchBase< T, Dim >::bunchLocalNum_m protected
Definition at line 710 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::countTotalNumPerBunch(), PartBunchBase< double, 3 >::getLocalNumPerBunch(), PartBunchBase< double, 3 >::setLocalNumPerBunch(), and PartBunchBase< double, 3 >::setNumBunch().
bunchNum
template<class T, unsigned Dim> ParticleAttrib< short > PartBunchBase< T, Dim >::bunchNum
Definition at line 590 of file PartBunchBase.h.
Referenced by Cyclotron::apply(), ParallelCyclotronTracker::bgf_main_collision_test(), MultiBunchHandler::calcBunchBeamParameters(), ParallelCyclotronTracker::calcMeanR(), ParallelCyclotronTracker::computePathLengthUpdate(), PartBunchBase< double, 3 >::countTotalNumPerBunch(), ParallelCyclotronTracker::deleteParticle(), Septum::doCheck(), Probe::doCheck(), Stripper::doCheck(), CCollimator::doCheck(), OutputPlane::doCheck(), MultiBunchHandler::readBunch(), H5PartWrapperForPC::readStepData(), PartBunchBase< double, 3 >::setup(), PartBunchBase< double, 3 >::swap(), and H5PartWrapperForPC::writeStepData().
bunchTotalNum_m
template<class T, unsigned Dim> std::vector<size_t> PartBunchBase< T, Dim >::bunchTotalNum_m protected
number of particles per bunch
Definition at line 709 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::countTotalNumPerBunch(), PartBunchBase< double, 3 >::getTotalNumPerBunch(), PartBunchBase< double, 3 >::setNumBunch(), and PartBunchBase< double, 3 >::setTotalNumPerBunch().
cavityGapCrossed
template<class T, unsigned Dim> ParticleAttrib< short > PartBunchBase< T, Dim >::cavityGapCrossed
Definition at line 589 of file PartBunchBase.h.
Referenced by ParallelCyclotronTracker::bunchMode_m(), ParallelCyclotronTracker::gapCrossKick_m(), PartBunchBase< double, 3 >::setup(), ParallelCyclotronTracker::singleMode_m(), and PartBunchBase< double, 3 >::swap().
centroid_m
template<class T, unsigned Dim> double PartBunchBase< T, Dim >::centroid_m[2 *Dim] protected
holds the centroid of the beam
Definition at line 641 of file PartBunchBase.h.
couplingConstant_m
template<class T, unsigned Dim> double PartBunchBase< T, Dim >::couplingConstant_m protected
Definition at line 674 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getCouplingConstant(), and PartBunchBase< double, 3 >::setCouplingConstant().
dcBeam_m
template<class T, unsigned Dim> bool PartBunchBase< T, Dim >::dcBeam_m protected
Definition at line 727 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp().
deltaTau_m
template<class T, unsigned Dim> double PartBunchBase< T, Dim >::deltaTau_m
Definition at line 608 of file PartBunchBase.h.
Referenced by TrackRun::setupThickTracker(), and TrackRun::setupTTracker().
dh_m
template<class T, unsigned Dim> double PartBunchBase< T, Dim >::dh_m protected
Mesh enlargement.
Definition at line 683 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::boundp_destroyCycl(), PartBunchBase< double, 3 >::calcLineDensity(), PartBunchBase< double, 3 >::print(), and PartBunchBase< double, 3 >::set_meshEnlargement().
Dimension
template<class T, unsigned Dim> const unsigned PartBunchBase< T, Dim >::Dimension = Dim static
Definition at line 59 of file PartBunchBase.h.
Referenced by AmrBoxLib::getEExtrema().
dist_m
template<class T, unsigned Dim> Distribution* PartBunchBase< T, Dim >::dist_m protected
Definition at line 723 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::boundp_destroyT(), PartBunchBase< double, 3 >::calcGammas(), PartBunchBase< double, 3 >::destroyT(), PartBunchBase< double, 3 >::doEmission(), PartBunchBase< double, 3 >::emitParticles(), PartBunchBase< double, 3 >::get_pmean_Distribution(), PartBunchBase< double, 3 >::getDistType(), PartBunchBase< double, 3 >::getEmissionDeltaT(), PartBunchBase< double, 3 >::getIfBeamEmitting(), PartBunchBase< double, 3 >::getLastEmittedEnergyBin(), PartBunchBase< double, 3 >::getNumberOfEmissionSteps(), PartBunchBase< double, 3 >::getNumberOfEnergyBins(), PartBunchBase< double, 3 >::Rebin(), PartBunchBase< double, 3 >::setDistribution(), and PartBunchBase< double, 3 >::weHaveEnergyBins().
distDump_m
template<class T, unsigned Dim> int PartBunchBase< T, Dim >::distDump_m protected
counter to store the distribution dump
Definition at line 680 of file PartBunchBase.h.
distrCreate_m
template<class T, unsigned Dim> IpplTimings::TimerRef PartBunchBase< T, Dim >::distrCreate_m
Definition at line 605 of file PartBunchBase.h.
Referenced by Distribution::createOpalT(), and PartBunchBase< double, 3 >::setup().
distrReload_m
template<class T, unsigned Dim> IpplTimings::TimerRef PartBunchBase< T, Dim >::distrReload_m
timer for IC, can not be in Distribution.h
Definition at line 604 of file PartBunchBase.h.
Referenced by Distribution::doRestartOpalCycl(), Distribution::doRestartOpalT(), and PartBunchBase< double, 3 >::setup().
dt
template<class T, unsigned Dim> ParticleAttrib< double > PartBunchBase< T, Dim >::dt
Definition at line 585 of file PartBunchBase.h.
Referenced by ScatteringPhysics::addParticleBackToBunch(), Source::apply(), FlexibleCollimator::apply(), Undulator::apply(), Degrader::apply(), Monitor::apply(), ParallelTTracker::changeDT(), ParallelTTracker::computeExternalFields(), ScatteringPhysics::copyFromBunch(), Distribution::emitParticles(), ParallelTTracker::evenlyDistributeParticles(), ParallelTTracker::kickParticles(), ParallelTTracker::pushParticles(), PartBunchBase< double, 3 >::setdT(), ParallelTTracker::setTime(), ParallelCyclotronTracker::setTimeStep(), PartBunchBase< double, 3 >::setup(), PartBunchBase< double, 3 >::swap(), PartBunchBase< double, 3 >::switchOffUnitlessPositions(), PartBunchBase< double, 3 >::switchToUnitlessPositions(), ParallelTTracker::timeIntegration2(), ThickTracker::update_m(), and AmrYtWriter::writeParticles_m().
dt_m
template<class T, unsigned Dim> double PartBunchBase< T, Dim >::dt_m protected
holds the timestep in seconds
Definition at line 644 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getdT(), PartBunchBase< double, 3 >::incrementT(), and PartBunchBase< double, 3 >::setdT().
dtScInit_m
template<class T, unsigned Dim> double PartBunchBase< T, Dim >::dtScInit_m
Definition at line 608 of file PartBunchBase.h.
Referenced by TrackRun::setupThickTracker(), and TrackRun::setupTTracker().
Ef
template<class T, unsigned Dim> ParticleAttrib< Vector_t > PartBunchBase< T, Dim >::Ef
Definition at line 580 of file PartBunchBase.h.
Referenced by ScatteringPhysics::addParticleBackToBunch(), CSRIGFWakeFunction::apply(), CSRWakeFunction::apply(), GreenWakeFunction::apply(), ParallelCyclotronTracker::borisExternalFields(), ParallelCyclotronTracker::bunchMode_m(), ParallelTTracker::computeExternalFields(), AmrBoxLib::computeSelfFields_cycl(), ParallelTTracker::computeSpaceChargeFields(), ParallelCyclotronTracker::computeSpaceChargeFields_m(), ParallelTTracker::computeWakefield(), ScatteringPhysics::copyFromBunch(), Distribution::emitParticles(), ParallelTTracker::execute(), ParallelCyclotronTracker::getFieldsAtPoint(), Distribution::injectBeam(), ParallelCyclotronTracker::kick(), ParallelTTracker::kickParticles(), ApplyField< T >::operator()(), PartBunchBase< double, 3 >::setup(), PartBunchBase< double, 3 >::swap(), ParallelTTracker::transformBunch(), AmrYtWriter::writeParticles_m(), H5PartWrapperForPC::writeStepData(), and H5PartWrapperForPT::writeStepData().
Eftmp
template<class T, unsigned Dim> ParticleAttrib< Vector_t > PartBunchBase< T, Dim >::Eftmp
Definition at line 581 of file PartBunchBase.h.
Referenced by AmrBoxLib::computeSelfFields_cycl(), PartBunchBase< double, 3 >::setup(), and PartBunchBase< double, 3 >::swap().
f_stream
template<class T, unsigned Dim> std::unique_ptr<std::ofstream> PartBunchBase< T, Dim >::f_stream private
Definition at line 616 of file PartBunchBase.h.
fixed_grid
template<class T, unsigned Dim> bool PartBunchBase< T, Dim >::fixed_grid private
if the grid does not have to adapt
Definition at line 618 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::isGridFixed().
fs_m
template<class T, unsigned Dim> FieldSolver* PartBunchBase< T, Dim >::fs_m protected
stores the used field solver
Definition at line 672 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::getFieldSolverType(), PartBunchBase< double, 3 >::hasFieldSolver(), and PartBunchBase< double, 3 >::setSolver().
globalMeanR_m
template<class T, unsigned Dim> Vector_t PartBunchBase< T, Dim >::globalMeanR_m protected
Initialize the translation vector and rotation quaternion here. Cyclotron tracker will reset these values each timestep TTracker can just use 0 translation and 0 rotation (quat[1 0 0 0]).
Definition at line 655 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getGlobalMeanR(), and PartBunchBase< double, 3 >::setGlobalMeanR().
globalPartPerNode_m
template<class T, unsigned Dim> std::unique_ptr<size_t[]> PartBunchBase< T, Dim >::globalPartPerNode_m protected
Definition at line 721 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::calcNumPartsOutside(), PartBunchBase< double, 3 >::gatherLoadBalanceStatistics(), PartBunchBase< double, 3 >::getLoadBalance(), and PartBunchBase< double, 3 >::setup().
globalToLocalQuaternion_m
template<class T, unsigned Dim> Quaternion_t PartBunchBase< T, Dim >::globalToLocalQuaternion_m protected
Definition at line 656 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getGlobalToLocalQuaternion(), and PartBunchBase< double, 3 >::setGlobalToLocalQuaternion().
globalTrackStep_m
template<class T, unsigned Dim> long long PartBunchBase< T, Dim >::globalTrackStep_m protected
if multiple TRACK commands
Definition at line 703 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getGlobalTrackStep(), PartBunchBase< double, 3 >::incTrackSteps(), and PartBunchBase< double, 3 >::setGlobalTrackStep().
histoTimer_m
template<class T, unsigned Dim> IpplTimings::TimerRef PartBunchBase< T, Dim >::histoTimer_m protected
Definition at line 626 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::setup().
hr_m
template<class T, unsigned Dim> Vector_t PartBunchBase< T, Dim >::hr_m protected
meshspacing of cartesian mesh
Definition at line 667 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::boundp_destroyCycl(), and PartBunchBase< double, 3 >::get_hr().
ID
template<class T, unsigned Dim> ParticleIndex_t& PartBunchBase< T, Dim >::ID
Definition at line 573 of file PartBunchBase.h.
Referenced by Source::apply(), FlexibleCollimator::apply(), Degrader::apply(), Monitor::apply(), ParallelCyclotronTracker::bgf_main_collision_test(), PartBunchBase< double, 3 >::boundp(), ScatteringPhysics::copyFromBunch(), Septum::doCheck(), Probe::doCheck(), Stripper::doCheck(), CCollimator::doCheck(), OutputPlane::doCheck(), BeamStrippingPhysics::doPhysics(), ParallelTTracker::evenlyDistributeParticles(), ParallelCyclotronTracker::finalizeTracking_m(), ParallelCyclotronTracker::getFieldsAtPoint(), PartBunchBase< double, 3 >::getParticle(), ParallelCyclotronTracker::initDistInGlobalFrame(), Distribution::injectBeam(), PartBunchBase< T, Dim >::ConstIterator::operator*(), H5PartWrapperForPT::readStepData(), ParallelCyclotronTracker::RFkick(), ParallelCyclotronTracker::seoMode_m(), ParallelCyclotronTracker::singleMode_m(), ParallelCyclotronTracker::singleParticleDump(), BeamStrippingPhysics::transformToSecondary(), AmrYtWriter::writeParticles_m(), H5PartWrapperForPC::writeStepData(), and H5PartWrapperForPT::writeStepData().
localTrackStep_m
template<class T, unsigned Dim> long long PartBunchBase< T, Dim >::localTrackStep_m protected
step in a TRACK command
Definition at line 700 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getLocalTrackStep(), PartBunchBase< double, 3 >::incTrackSteps(), and PartBunchBase< double, 3 >::setLocalTrackStep().
M
template<class T, unsigned Dim> ParticleAttrib< double > PartBunchBase< T, Dim >::M
Definition at line 578 of file PartBunchBase.h.
Referenced by ScatteringPhysics::addParticleBackToBunch(), Source::apply(), FlexibleCollimator::apply(), Monitor::apply(), Ring::apply(), Cyclotron::apply(), ParallelCyclotronTracker::bgf_main_collision_test(), ScatteringPhysics::copyFromBunch(), PartBunchBase< double, 3 >::create(), RK4< FieldFunction, Arguments >::derivate_m(), PartBunchBase< double, 3 >::destroy(), Septum::doCheck(), Probe::doCheck(), Stripper::doCheck(), CCollimator::doCheck(), OutputPlane::doCheck(), BeamStrippingPhysics::doPhysics(), Distribution::emitParticles(), ParallelTTracker::evenlyDistributeParticles(), PartBunchBase< double, 3 >::getParticle(), PartBunchBase< double, 3 >::ghostDestroy(), Distribution::injectBeam(), ParallelCyclotronTracker::kick(), LF2< FieldFunction, Arguments >::kick_m(), MultiBunchHandler::readBunch(), H5PartWrapperForPC::readStepData(), MultiBunchHandler::saveBunch(), PartBunchBase< double, 3 >::setMass(), PartBunchBase< double, 3 >::setup(), PartBunchBase< double, 3 >::swap(), BeamStrippingPhysics::transformToSecondary(), Vacuum::updateParticleAttributes(), AmrYtWriter::writeParticles_m(), and H5PartWrapperForPC::writeStepData().
massPerParticle_m
template<class T, unsigned Dim> double PartBunchBase< T, Dim >::massPerParticle_m protected
Definition at line 677 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getMassPerParticle(), PartBunchBase< double, 3 >::setMass(), and PartBunchBase< double, 3 >::setMassZeroPart().
momentsComputer_m
template<class T, unsigned Dim> DistributionMoments PartBunchBase< T, Dim >::momentsComputer_m protected
Definition at line 724 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp_destroyCycl(), PartBunchBase< double, 3 >::boundp_destroyT(), PartBunchBase< double, 3 >::calcBeamParameters(), PartBunchBase< double, 3 >::calcDebyeLength(), PartBunchBase< double, 3 >::calcEMean(), PartBunchBase< double, 3 >::get_68Percentile(), PartBunchBase< double, 3 >::get_95Percentile(), PartBunchBase< double, 3 >::get_99_99Percentile(), PartBunchBase< double, 3 >::get_99Percentile(), PartBunchBase< double, 3 >::get_centroid(), PartBunchBase< double, 3 >::get_DDx(), PartBunchBase< double, 3 >::get_DDy(), PartBunchBase< double, 3 >::get_debyeLength(), PartBunchBase< double, 3 >::get_Dx(), PartBunchBase< double, 3 >::get_Dy(), PartBunchBase< double, 3 >::get_emit(), PartBunchBase< double, 3 >::get_gamma(), PartBunchBase< double, 3 >::get_halo(), PartBunchBase< double, 3 >::get_meanKineticEnergy(), PartBunchBase< double, 3 >::get_norm_emit(), PartBunchBase< double, 3 >::get_normalizedEps_68Percentile(), PartBunchBase< double, 3 >::get_normalizedEps_95Percentile(), PartBunchBase< double, 3 >::get_normalizedEps_99_99Percentile(), PartBunchBase< double, 3 >::get_normalizedEps_99Percentile(), PartBunchBase< double, 3 >::get_plasmaParameter(), PartBunchBase< double, 3 >::get_pmean(), PartBunchBase< double, 3 >::get_prms(), PartBunchBase< double, 3 >::get_rmean(), PartBunchBase< double, 3 >::get_rprms(), PartBunchBase< double, 3 >::get_rrms(), PartBunchBase< double, 3 >::get_temperature(), PartBunchBase< double, 3 >::getdE(), and PartBunchBase< double, 3 >::getSigmaMatrix().
nr_m
template<class T, unsigned Dim> Vektor<int, 3> PartBunchBase< T, Dim >::nr_m protected
meshsize of cartesian mesh
Definition at line 669 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::boundp_destroyCycl(), and PartBunchBase< double, 3 >::boundp_destroyT().
numBunch_m
template<class T, unsigned Dim> short PartBunchBase< T, Dim >::numBunch_m protected
current bunch number
Definition at line 706 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::countTotalNumPerBunch(), PartBunchBase< double, 3 >::getNumBunch(), PartBunchBase< double, 3 >::resetPartBinBunch(), and PartBunchBase< double, 3 >::setNumBunch().
P
template<class T, unsigned Dim> ParticleAttrib< Vector_t > PartBunchBase< T, Dim >::P
Definition at line 576 of file PartBunchBase.h.
Referenced by ScatteringPhysics::addParticleBackToBunch(), Stepper< FieldFunction, Arguments... >::advance(), ThickTracker::advanceParticles_m(), Source::apply(), FlexibleCollimator::apply(), Undulator::apply(), Degrader::apply(), Solenoid::apply(), TravelingWave::apply(), VerticalFFAMagnet::apply(), ScalingFFAMagnet::apply(), Monitor::apply(), RBend3D::apply(), SBend3D::apply(), VariableRFCavity::apply(), Corrector::apply(), Ring::apply(), VariableRFCavityFringeField::apply(), RFCavity::apply(), MultipoleT::apply(), Cyclotron::apply(), ParallelCyclotronTracker::bgf_main_collision_test(), PartBunchBase< double, 3 >::boundp(), ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), ParallelCyclotronTracker::bunchDumpStatData(), ParallelCyclotronTracker::bunchMode_m(), MultiBunchHandler::calcBunchBeamParameters(), PartBunchBase< double, 3 >::calcGammas(), PartBunchBase< double, 3 >::calcGammas_cycl(), ParallelCyclotronTracker::calcMeanP(), PartBunchBase< double, 3 >::calcMeanPhi(), PluginElement::changeWidth(), ParallelCyclotronTracker::checkFileMomentum(), ParallelTTracker::computeExternalFields(), ParallelTTracker::computeParticleMatterInteraction(), ParallelCyclotronTracker::computePathLengthUpdate(), ParallelTTracker::computeWakefield(), ScatteringPhysics::copyFromBunch(), ParallelCyclotronTracker::deleteParticle(), LF2< FieldFunction, Arguments >::doAdvance_m(), RK4< FieldFunction, Arguments >::doAdvance_m(), Septum::doCheck(), Probe::doCheck(), Stripper::doCheck(), CCollimator::doCheck(), OutputPlane::doCheck(), BeamStrippingPhysics::doPhysics(), Distribution::doRestartOpalCycl(), Distribution::emitParticles(), ParallelTTracker::evenlyDistributeParticles(), ParallelCyclotronTracker::finalizeTracking_m(), ParallelCyclotronTracker::gapCrossKick_m(), PartBunchBase< double, 3 >::get_PBounds(), PartBunchBase< double, 3 >::getParticle(), ParallelCyclotronTracker::initDistInGlobalFrame(), Distribution::injectBeam(), ParallelCyclotronTracker::kick(), LF2< FieldFunction, Arguments >::kick_m(), ParallelTTracker::kickParticles(), ParallelCyclotronTracker::MtsTracker(), PartBunchBase< T, Dim >::ConstIterator::operator*(), ParallelCyclotronTracker::push(), PartBunchBase< double, 3 >::push_back(), ParallelTTracker::pushParticles(), MultiBunchHandler::readBunch(), H5PartWrapperForPC::readStepData(), H5PartWrapperForPT::readStepData(), PartBunchBase< double, 3 >::resetPartBinID2(), ParallelCyclotronTracker::RFkick(), MultiBunchHandler::saveBunch(), ParallelCyclotronTracker::seoMode_m(), PartBunchBase< double, 3 >::setParticle(), PartBunchBase< double, 3 >::setup(), ParallelCyclotronTracker::singleMode_m(), ParallelCyclotronTracker::singleParticleDump(), PartBunchBase< double, 3 >::swap(), AmrBoxLib::tagForMomenta_m(), ParallelTTracker::transformBunch(), StatWriter::write(), AmrYtWriter::writeParticles_m(), ParallelTTracker::writePhaseSpace(), H5PartWrapperForPT::writeStepData(), and H5PartWrapperForPC::writeStepData().
pbase_m
template<class T, unsigned Dim> std::shared_ptr<AbstractParticle<T, Dim> > PartBunchBase< T, Dim >::pbase_m protected
Definition at line 729 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::create(), PartBunchBase< double, 3 >::createWithID(), PartBunchBase< double, 3 >::destroy(), PartBunchBase< double, 3 >::getBConds(), PartBunchBase< double, 3 >::getDestroyNum(), PartBunchBase< double, 3 >::getGhostNum(), PartBunchBase< double, 3 >::getLayout(), PartBunchBase< double, 3 >::getLocalNum(), PartBunchBase< double, 3 >::getTotalNum(), PartBunchBase< double, 3 >::getUpdateFlag(), PartBunchBase< double, 3 >::ghostDestroy(), PartBunchBase< double, 3 >::globalCreate(), PartBunchBase< double, 3 >::performDestroy(), PartBunchBase< double, 3 >::resetID(), PartBunchBase< double, 3 >::setBConds(), PartBunchBase< double, 3 >::setLocalNum(), PartBunchBase< double, 3 >::setTotalNum(), PartBunchBase< double, 3 >::setUpdateFlag(), PartBunchBase< double, 3 >::singleInitNode(), and PartBunchBase< double, 3 >::update().
pbin_m
template<class T, unsigned Dim> PartBins* PartBunchBase< T, Dim >::pbin_m
Definition at line 601 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp_destroyCycl(), PartBunchBase< double, 3 >::calcGammas_cycl(), PartBunchBase< double, 3 >::calcMeanPhi(), PartBunchBase< double, 3 >::getLastemittedBin(), PartBunchBase< double, 3 >::hasBinning(), MultiBunchHandler::MultiBunchHandler(), PartBunchBase< double, 3 >::rebin(), PartBunchBase< double, 3 >::resetPartBinBunch(), PartBunchBase< double, 3 >::resetPartBinID2(), PartBunchBase< double, 3 >::setLocalBinCount(), PartBunchBase< double, 3 >::setPBins(), and PartBunchBase< double, 3 >::weHaveBins().
periodLength_m
template<class T, unsigned Dim> double PartBunchBase< T, Dim >::periodLength_m protected
Definition at line 728 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp(), and PartBunchBase< double, 3 >::setBeamFrequency().
Phi
template<class T, unsigned Dim> ParticleAttrib< double > PartBunchBase< T, Dim >::Phi
Definition at line 579 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::setup(), and PartBunchBase< double, 3 >::swap().
pmsg_m
template<class T, unsigned Dim> std::unique_ptr<Inform> PartBunchBase< T, Dim >::pmsg_m private
Definition at line 615 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::setup().
POrigin
template<class T, unsigned Dim> ParticleAttrib< ParticleOrigin > PartBunchBase< T, Dim >::POrigin
Definition at line 587 of file PartBunchBase.h.
Referenced by Stripper::doCheck(), Distribution::emitParticles(), ParallelTTracker::evenlyDistributeParticles(), Distribution::injectBeam(), MultiBunchHandler::readBunch(), MultiBunchHandler::saveBunch(), PartBunchBase< double, 3 >::setup(), TrackRun::setupCyclotronTracker(), PartBunchBase< double, 3 >::swap(), BeamStrippingPhysics::transformToSecondary(), and H5PartWrapperForPT::writeStepData().
PType
template<class T, unsigned Dim> ParticleAttrib< ParticleType > PartBunchBase< T, Dim >::PType
Definition at line 586 of file PartBunchBase.h.
Referenced by BeamStrippingPhysics::doPhysics(), Distribution::emitParticles(), Distribution::injectBeam(), PartBunchBase< double, 3 >::setup(), PartBunchBase< double, 3 >::swap(), BeamStrippingPhysics::transformToSecondary(), and H5PartWrapperForPT::writeStepData().
Q
template<class T, unsigned Dim> ParticleAttrib< double > PartBunchBase< T, Dim >::Q
Definition at line 577 of file PartBunchBase.h.
Referenced by ScatteringPhysics::addParticleBackToBunch(), Source::apply(), FlexibleCollimator::apply(), Undulator::apply(), Monitor::apply(), Ring::apply(), Cyclotron::apply(), ParallelCyclotronTracker::bgf_main_collision_test(), PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::calcLineDensity(), AmrBoxLib::computeSelfFields_cycl(), ParallelTTracker::computeSpaceChargeFields(), ParallelCyclotronTracker::computeSpaceChargeFields_m(), ScatteringPhysics::copyFromBunch(), RK4< FieldFunction, Arguments >::derivate_m(), Septum::doCheck(), Probe::doCheck(), Stripper::doCheck(), CCollimator::doCheck(), OutputPlane::doCheck(), BeamStrippingPhysics::doPhysics(), Distribution::doRestartOpalCycl(), Distribution::emitParticles(), ParallelTTracker::evenlyDistributeParticles(), PartBunchBase< double, 3 >::getCharge(), PartBunchBase< double, 3 >::getParticle(), Distribution::injectBeam(), ParallelCyclotronTracker::kick(), LF2< FieldFunction, Arguments >::kick_m(), ApplyField< T >::operator()(), PartBunchBase< T, Dim >::ConstIterator::operator*(), PartBunchBase< double, 3 >::print(), MultiBunchHandler::readBunch(), H5PartWrapperForPC::readStepData(), H5PartWrapperForPT::readStepData(), MultiBunchHandler::saveBunch(), PartBunchBase< double, 3 >::setBinCharge(), PartBunchBase< double, 3 >::setCharge(), PartBunchBase< double, 3 >::setup(), AmrBoxLib::solvePoisson_m(), PartBunchBase< double, 3 >::swap(), AmrBoxLib::tagForChargeDensity_m(), BeamStrippingPhysics::transformToSecondary(), Vacuum::updateParticleAttributes(), AmrYtWriter::writeParticles_m(), H5PartWrapperForPC::writeStepData(), and H5PartWrapperForPT::writeStepData().
qi_m
template<class T, unsigned Dim> double PartBunchBase< T, Dim >::qi_m protected
Definition at line 676 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getChargePerParticle(), PartBunchBase< double, 3 >::print(), PartBunchBase< double, 3 >::setBinCharge(), PartBunchBase< double, 3 >::setCharge(), and PartBunchBase< double, 3 >::setChargeZeroPart().
R
template<class T, unsigned Dim> ParticlePos_t& PartBunchBase< T, Dim >::R
Definition at line 572 of file PartBunchBase.h.
Referenced by ScatteringPhysics::addParticleBackToBunch(), Stepper< FieldFunction, Arguments... >::advance(), ThickTracker::advanceParticles_m(), CSRIGFWakeFunction::apply(), CSRWakeFunction::apply(), Source::apply(), FlexibleCollimator::apply(), Undulator::apply(), Degrader::apply(), Solenoid::apply(), TravelingWave::apply(), GreenWakeFunction::apply(), VerticalFFAMagnet::apply(), ScalingFFAMagnet::apply(), Monitor::apply(), RBend3D::apply(), Bend2D::apply(), SBend3D::apply(), VariableRFCavity::apply(), Corrector::apply(), Ring::apply(), VariableRFCavityFringeField::apply(), Component::apply(), RFCavity::apply(), Multipole::apply(), MultipoleT::apply(), Cyclotron::apply(), ParallelCyclotronTracker::bgf_main_collision_test(), ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), ParallelCyclotronTracker::bunchDumpStatData(), ParallelCyclotronTracker::bunchMode_m(), MultiBunchHandler::calcBunchBeamParameters(), ParallelCyclotronTracker::calcMeanR(), P3MPoissonSolver::calculatePairForces(), Vacuum::checkVacuum(), ParallelTTracker::computeExternalFields(), ParallelTTracker::computeParticleMatterInteraction(), AmrBoxLib::computeSelfFields_cycl(), ParallelTTracker::computeSpaceChargeFields(), ParallelCyclotronTracker::computeSpaceChargeFields_m(), ParallelTTracker::computeWakefield(), ScatteringPhysics::copyFromBunch(), ParallelCyclotronTracker::deleteParticle(), RK4< FieldFunction, Arguments >::derivate_m(), LF2< FieldFunction, Arguments >::doAdvance_m(), RK4< FieldFunction, Arguments >::doAdvance_m(), Septum::doCheck(), Probe::doCheck(), Stripper::doCheck(), CCollimator::doCheck(), OutputPlane::doCheck(), BeamStrippingPhysics::doPhysics(), Distribution::doRestartOpalCycl(), Distribution::emitParticles(), ParallelTTracker::evenlyDistributeParticles(), ParallelCyclotronTracker::gapCrossKick_m(), ParallelCyclotronTracker::initDistInGlobalFrame(), Distribution::injectBeam(), ParallelCyclotronTracker::kick(), LF2< FieldFunction, Arguments >::kick_m(), ParallelTTracker::kickParticles(), ParallelCyclotronTracker::MtsTracker(), ApplyField< T >::operator()(), PartBunchBase< T, Dim >::ConstIterator::operator*(), ParallelCyclotronTracker::push(), ParallelTTracker::pushParticles(), MultiBunchHandler::readBunch(), H5PartWrapperForPT::readStepData(), H5PartWrapperForPC::readStepData(), ParallelCyclotronTracker::RFkick(), MultiBunchHandler::saveBunch(), ParallelCyclotronTracker::seoMode_m(), ParallelCyclotronTracker::singleMode_m(), ParallelCyclotronTracker::singleParticleDump(), AmrBoxLib::solvePoisson_m(), AmrBoxLib::tagForChargeDensity_m(), AmrBoxLib::tagForMaxNumParticles_m(), AmrBoxLib::tagForMinNumParticles_m(), AmrBoxLib::tagForMomenta_m(), ParallelTTracker::transformBunch(), StatWriter::write(), AmrYtWriter::writeParticles_m(), ParallelTTracker::writePhaseSpace(), H5PartWrapperForPC::writeStepData(), and H5PartWrapperForPT::writeStepData().
reference
template<class T, unsigned Dim> const PartData* PartBunchBase< T, Dim >::reference protected
Definition at line 630 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getE(), PartBunchBase< double, 3 >::getInitialBeta(), PartBunchBase< double, 3 >::getInitialGamma(), PartBunchBase< double, 3 >::getM(), PartBunchBase< double, 3 >::getMomentumTolerance(), PartBunchBase< double, 3 >::getP(), PartBunchBase< double, 3 >::getQ(), PartBunchBase< double, 3 >::getReference(), PartBunchBase< double, 3 >::resetM(), and PartBunchBase< double, 3 >::resetQ().
RefPartP_m
template<class T, unsigned Dim> Vector_t PartBunchBase< T, Dim >::RefPartP_m
Definition at line 593 of file PartBunchBase.h.
Referenced by Undulator::apply(), ParallelTTracker::applyFractionalStep(), ParallelTTracker::autophaseCavities(), ParallelTTracker::execute(), ParallelTTracker::findStartPosition(), H5PartWrapperForPT::readStepHeader(), ParallelCyclotronTracker::singleParticleDump(), ParallelTTracker::updateReferenceParticle(), ParallelTTracker::updateRefToLabCSTrafo(), StatWriter::write(), ParallelTTracker::writePhaseSpace(), H5PartWrapperForPT::writeStepHeader(), and H5PartWrapperForPC::writeStepHeader().
RefPartR_m
template<class T, unsigned Dim> Vector_t PartBunchBase< T, Dim >::RefPartR_m
Definition at line 592 of file PartBunchBase.h.
Referenced by Undulator::apply(), ParallelTTracker::applyFractionalStep(), ParallelTTracker::autophaseCavities(), ParallelTTracker::execute(), ParallelTTracker::findStartPosition(), ParallelTTracker::hasEndOfLineReached(), H5PartWrapperForPT::readStepHeader(), ParallelCyclotronTracker::singleParticleDump(), ParallelTTracker::updateReferenceParticle(), ParallelTTracker::updateRefToLabCSTrafo(), StatWriter::write(), ParallelTTracker::writePhaseSpace(), H5PartWrapperForPC::writeStepHeader(), and H5PartWrapperForPT::writeStepHeader().
refPOrigin_m
template<class T, unsigned Dim> ParticleOrigin PartBunchBase< T, Dim >::refPOrigin_m
Definition at line 597 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getPOrigin(), and PartBunchBase< double, 3 >::setPOrigin().
refPType_m
template<class T, unsigned Dim> ParticleType PartBunchBase< T, Dim >::refPType_m
Definition at line 598 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getPType(), and PartBunchBase< double, 3 >::setPType().
rmax_m
template<class T, unsigned Dim> Vector_t PartBunchBase< T, Dim >::rmax_m protected
maximal extend of particles
Definition at line 659 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::boundp_destroyCycl(), PartBunchBase< double, 3 >::calcBeamParameters(), PartBunchBase< double, 3 >::get_maxExtent(), and PartBunchBase< double, 3 >::print().
rmin_m
template<class T, unsigned Dim> Vector_t PartBunchBase< T, Dim >::rmin_m protected
minimal extend of particles
Definition at line 661 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::boundp_destroyCycl(), PartBunchBase< double, 3 >::calcBeamParameters(), PartBunchBase< double, 3 >::get_origin(), and PartBunchBase< double, 3 >::print().
rmsDensity_m
template<class T, unsigned Dim> double PartBunchBase< T, Dim >::rmsDensity_m protected
Definition at line 664 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::calcDebyeLength(), and PartBunchBase< double, 3 >::get_rmsDensity().
selfFieldTimer_m
template<class T, unsigned Dim> IpplTimings::TimerRef PartBunchBase< T, Dim >::selfFieldTimer_m protected
timer for selfField calculation
Definition at line 628 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::setup().
spos_m
template<class T, unsigned Dim> double PartBunchBase< T, Dim >::spos_m protected
the position along design trajectory
Definition at line 648 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::get_sPos(), and PartBunchBase< double, 3 >::set_sPos().
stateOfLastBoundP_
template<class T, unsigned Dim> UnitState_t PartBunchBase< T, Dim >::stateOfLastBoundP_ protected
Definition at line 638 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp().
statParamTimer_m
template<class T, unsigned Dim> IpplTimings::TimerRef PartBunchBase< T, Dim >::statParamTimer_m protected
Definition at line 624 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::calcBeamParameters(), and PartBunchBase< double, 3 >::setup().
stepsPerTurn_m
template<class T, unsigned Dim> int PartBunchBase< T, Dim >::stepsPerTurn_m protected
steps per turn for OPAL-cycl
Definition at line 697 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getStepsPerTurn(), and PartBunchBase< double, 3 >::setStepsPerTurn().
SteptoLastInj_m
template<class T, unsigned Dim> int PartBunchBase< T, Dim >::SteptoLastInj_m protected
this parameter records the current steps since last bunch injection it helps to inject new bunches correctly in the restart run of OPAL-cycl it is stored during phase space dump.
Definition at line 715 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getSteptoLastInj(), and PartBunchBase< double, 3 >::setSteptoLastInj().
t_m
template<class T, unsigned Dim> double PartBunchBase< T, Dim >::t_m protected
holds the actual time of the integration
Definition at line 646 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getT(), PartBunchBase< double, 3 >::incrementT(), and PartBunchBase< double, 3 >::setT().
tEmission_m
template<class T, unsigned Dim> double PartBunchBase< T, Dim >::tEmission_m protected
relative enlargement of the mesh
if larger than 0, emitt particles for tEmission_m [s]
Definition at line 686 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::getTEmission(), and PartBunchBase< double, 3 >::setTEmission().
toLabTrafo_m
template<class T, unsigned Dim> CoordinateSystemTrafo PartBunchBase< T, Dim >::toLabTrafo_m
Definition at line 595 of file PartBunchBase.h.
Referenced by Undulator::apply(), ParallelTTracker::applyFractionalStep(), ParallelTTracker::computeExternalFields(), ParallelTTracker::computeParticleMatterInteraction(), Monitor::driftToCorrectPositionAndSave(), ParallelTTracker::emitParticles(), ParallelTTracker::execute(), ParallelTTracker::findStartPosition(), H5PartWrapperForPT::readStepHeader(), ParallelTTracker::updateRefToLabCSTrafo(), ParallelTTracker::writePhaseSpace(), and H5PartWrapperForPT::writeStepHeader().
TriID
template<class T, unsigned Dim> ParticleAttrib< int > PartBunchBase< T, Dim >::TriID
Definition at line 588 of file PartBunchBase.h.
Referenced by Distribution::emitParticles(), ParallelTTracker::evenlyDistributeParticles(), Distribution::injectBeam(), PartBunchBase< double, 3 >::setup(), and PartBunchBase< double, 3 >::swap().
unit_state_
template<class T, unsigned Dim> UnitState_t PartBunchBase< T, Dim >::unit_state_ protected
Definition at line 637 of file PartBunchBase.h.
Referenced by PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::switchOffUnitlessPositions(), and PartBunchBase< double, 3 >::switchToUnitlessPositions().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/AbstractObjects/OpalData.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algorithms/PartBunchBase.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algorithms/PartBunchBase.hpp