OPAL (Object Oriented Parallel Accelerator Library): src/Classic/AbsBeamline/Offset.cpp File Reference
Offset.cpp File Reference
#include "AbsBeamline/Offset.h"
#include <cmath>
#include "Utilities/GeneralClassicException.h"
#include "BeamlineGeometry/Euclid3DGeometry.h"
#include "AbsBeamline/BeamlineVisitor.h"
#include "Physics/Physics.h"
Functions
bool operator== (const Offset &off1, const Offset &off2)
bool operator!= (const Offset &off1, const Offset &off2)
std::ostream & operator<< (std::ostream &out, const Offset &off)
Function Documentation
operator!=()
bool operator!= (const Offset & off1, const Offset & off2)
Return not of operator ==
Definition at line 223 of file Offset.cpp.
operator<<()
std::ostream& operator<< (std::ostream & out, const Offset & off1)
Print Offset off1 to the ostream
Definition at line 227 of file Offset.cpp.
References endl(), Offset::getEndDirection(), Offset::getEndPosition(), Offset::getIsLocal(), and ElementBase::getName().
operator==()
bool operator== (const Offset & off1, const Offset & off2)
Return true if off1 is equal to off2 within static floating point tolerance
Definition at line 198 of file Offset.cpp.
References abs(), Offset::float_tolerance, Rotation3D::getAxis(), Offset::getEndDirection(), Offset::getEndPosition(), Offset::getGeometry(), Offset::getIsLocal(), ElementBase::getName(), Euclid3D::getRotation(), Euclid3DGeometry::getTotalTransform(), Euclid3D::getVector(), and Offset::isGeometryAllocated().