OPAL (Object Oriented Parallel Accelerator Library): FM3DMagnetoStatic Class Reference
FM3DMagnetoStatic Class Reference
#include <FM3DMagnetoStatic.h>
Classes
struct IndexTriplet
Public Member Functions
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const
virtual void getFieldDimensions (double &zBegin, double &zEnd) const
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const
virtual bool getFieldDerivative (const Vector_t &R, Vector_t &E, Vector_t &B, const DiffDirection &dir) const
virtual void swap ()
virtual void getInfo (Inform *msg)
virtual double getFrequency () const
virtual void setFrequency (double freq)
virtual bool isInside (const Vector_t &r) const
Public Member Functions inherited from Fieldmap
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &onaxis)
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Private Types
enum {
LX = 0, LY = 0, LZ = 0, HX = 4,
HY = 2, HZ = 1
}
Private Member Functions
FM3DMagnetoStatic (std::string aFilename)
~FM3DMagnetoStatic ()
virtual void readMap ()
virtual void freeMap ()
IndexTriplet getIndex (const Vector_t &X) const
unsigned long getIndex (unsigned int i, unsigned int j, unsigned int k) const
Vector_t interpolateTrilinearly (const Vector_t &X) const
double getWeightedData (double *data, const IndexTriplet &idx, unsigned short corner) const
Private Attributes
double * FieldstrengthBz_m
double * FieldstrengthBx_m
double * FieldstrengthBy_m
double xbegin_m
double xend_m
double ybegin_m
double yend_m
double zbegin_m
double zend_m
double hx_m
double hy_m
double hz_m
unsigned int num_gridpx_m
unsigned int num_gridpy_m
unsigned int num_gridpz_m
Friends
class Fieldmap
Additional Inherited Members
Static Public Member Functions inherited from Fieldmap
static Fieldmap * getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions inherited from Fieldmap
Fieldmap ()=delete
Fieldmap (const std::string &aFilename)
virtual ~Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions inherited from Fieldmap
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes inherited from Fieldmap
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Detailed Description
Definition at line 6 of file FM3DMagnetoStatic.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
LX
LY
LZ
HX
HY
HZ
Definition at line 44 of file FM3DMagnetoStatic.h.
Constructor & Destructor Documentation
FM3DMagnetoStatic()
FM3DMagnetoStatic::FM3DMagnetoStatic (std::string aFilename) private
Definition at line 11 of file FM3DMagnetoStatic.cpp.
References Physics::e, Fieldmap::Filename_m, hx_m, hy_m, hz_m, Fieldmap::interpreteEOF(), Fieldmap::normalize_m, num_gridpx_m, num_gridpy_m, num_gridpz_m, T3DMagnetoStatic, Util::toUpper(), Fieldmap::Type, xbegin_m, xend_m, ybegin_m, yend_m, zbegin_m, and zend_m.
~FM3DMagnetoStatic()
FM3DMagnetoStatic::~FM3DMagnetoStatic () private
Definition at line 87 of file FM3DMagnetoStatic.cpp.
References freeMap().
Member Function Documentation
freeMap()
void FM3DMagnetoStatic::freeMap () private virtual
Implements Fieldmap.
Definition at line 146 of file FM3DMagnetoStatic.cpp.
References endl(), FieldstrengthBx_m, FieldstrengthBy_m, FieldstrengthBz_m, Fieldmap::Filename_m, INFOMSG, level3(), and Fieldmap::typeset_msg().
Referenced by ~FM3DMagnetoStatic().
getFieldDerivative()
bool FM3DMagnetoStatic::getFieldDerivative (const Vector_t & R, Vector_t & E, Vector_t & B, const DiffDirection & dir) const virtual
Implements Fieldmap.
Definition at line 216 of file FM3DMagnetoStatic.cpp.
getFieldDimensions() [1/2]
void FM3DMagnetoStatic::getFieldDimensions (double & zBegin, double & zEnd) const virtual
Implements Fieldmap.
Definition at line 220 of file FM3DMagnetoStatic.cpp.
References zbegin_m, and zend_m.
getFieldDimensions() [2/2]
void FM3DMagnetoStatic::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const virtual
Implements Fieldmap.
Definition at line 224 of file FM3DMagnetoStatic.cpp.
getFieldstrength()
bool FM3DMagnetoStatic::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const virtual
Implements Fieldmap.
Definition at line 161 of file FM3DMagnetoStatic.cpp.
References interpolateTrilinearly(), isInside(), and Attrib::Distribution::R.
getFrequency()
double FM3DMagnetoStatic::getFrequency () const inline virtual
Implements Fieldmap.
Definition at line 83 of file FM3DMagnetoStatic.h.
getIndex() [1/2]
FM3DMagnetoStatic::IndexTriplet FM3DMagnetoStatic::getIndex (const Vector_t & X) const inline private
Definition at line 100 of file FM3DMagnetoStatic.h.
References floor(), hx_m, hy_m, hz_m, FM3DMagnetoStatic::IndexTriplet::i, FM3DMagnetoStatic::IndexTriplet::j, FM3DMagnetoStatic::IndexTriplet::k, num_gridpx_m, num_gridpy_m, num_gridpz_m, PAssert_LT, FM3DMagnetoStatic::IndexTriplet::weight, X, xbegin_m, ybegin_m, and zbegin_m.
Referenced by getWeightedData(), interpolateTrilinearly(), and readMap().
getIndex() [2/2]
unsigned long FM3DMagnetoStatic::getIndex (unsigned int i, unsigned int j, unsigned int k) const inline private
Definition at line 91 of file FM3DMagnetoStatic.h.
References num_gridpx_m, num_gridpy_m, num_gridpz_m, and PAssert_LT.
getInfo()
void FM3DMagnetoStatic::getInfo (Inform * msg) virtual
Implements Fieldmap.
Definition at line 228 of file FM3DMagnetoStatic.cpp.
References endl(), Fieldmap::Filename_m, xbegin_m, xend_m, ybegin_m, yend_m, zbegin_m, and zend_m.
getWeightedData()
double FM3DMagnetoStatic::getWeightedData (double * data, const IndexTriplet & idx, unsigned short corner) const private
Definition at line 205 of file FM3DMagnetoStatic.cpp.
References getIndex(), HX, HY, HZ, FM3DMagnetoStatic::IndexTriplet::i, FM3DMagnetoStatic::IndexTriplet::j, FM3DMagnetoStatic::IndexTriplet::k, and FM3DMagnetoStatic::IndexTriplet::weight.
Referenced by interpolateTrilinearly().
interpolateTrilinearly()
Vector_t FM3DMagnetoStatic::interpolateTrilinearly (const Vector_t & X) const private
Definition at line 171 of file FM3DMagnetoStatic.cpp.
References FieldstrengthBx_m, FieldstrengthBy_m, FieldstrengthBz_m, getIndex(), getWeightedData(), HX, HY, HZ, LX, LY, LZ, and X.
Referenced by getFieldstrength().
isInside()
bool FM3DMagnetoStatic::isInside (const Vector_t & r) const inline virtual
Reimplemented from Fieldmap.
Definition at line 75 of file FM3DMagnetoStatic.h.
References xbegin_m, xend_m, ybegin_m, yend_m, zbegin_m, and zend_m.
Referenced by getFieldstrength().
readMap()
void FM3DMagnetoStatic::readMap () private virtual
Implements Fieldmap.
Definition at line 91 of file FM3DMagnetoStatic.cpp.
References abs(), endl(), FieldstrengthBx_m, FieldstrengthBy_m, FieldstrengthBz_m, Fieldmap::Filename_m, getIndex(), Fieldmap::getLine(), hx_m, hy_m, INFOMSG, level3(), Fieldmap::normalize_m, num_gridpx_m, num_gridpy_m, num_gridpz_m, Fieldmap::typeset_msg(), xbegin_m, and ybegin_m.
setFrequency()
void FM3DMagnetoStatic::setFrequency (double freq) inline virtual
Implements Fieldmap.
Definition at line 88 of file FM3DMagnetoStatic.h.
swap()
void FM3DMagnetoStatic::swap () virtual
Implements Fieldmap.
Definition at line 226 of file FM3DMagnetoStatic.cpp.
Friends And Related Function Documentation
Fieldmap
friend class Fieldmap friend
Definition at line 71 of file FM3DMagnetoStatic.h.
Member Data Documentation
FieldstrengthBx_m
double* FM3DMagnetoStatic::FieldstrengthBx_m private
3D array with Bx
Definition at line 52 of file FM3DMagnetoStatic.h.
Referenced by freeMap(), interpolateTrilinearly(), and readMap().
FieldstrengthBy_m
double* FM3DMagnetoStatic::FieldstrengthBy_m private
3D array with By
Definition at line 53 of file FM3DMagnetoStatic.h.
Referenced by freeMap(), interpolateTrilinearly(), and readMap().
FieldstrengthBz_m
double* FM3DMagnetoStatic::FieldstrengthBz_m private
3D array with Bz
Definition at line 51 of file FM3DMagnetoStatic.h.
Referenced by freeMap(), interpolateTrilinearly(), and readMap().
hx_m
double FM3DMagnetoStatic::hx_m private
length between points in grid, x-direction
Definition at line 64 of file FM3DMagnetoStatic.h.
Referenced by FM3DMagnetoStatic(), getIndex(), and readMap().
hy_m
double FM3DMagnetoStatic::hy_m private
length between points in grid, y-direction
Definition at line 65 of file FM3DMagnetoStatic.h.
Referenced by FM3DMagnetoStatic(), getIndex(), and readMap().
hz_m
double FM3DMagnetoStatic::hz_m private
length between points in grid, z-direction
Definition at line 66 of file FM3DMagnetoStatic.h.
Referenced by FM3DMagnetoStatic(), and getIndex().
num_gridpx_m
unsigned int FM3DMagnetoStatic::num_gridpx_m private
Read in number of points after 0(not counted here) in grid, r-direction
Definition at line 67 of file FM3DMagnetoStatic.h.
Referenced by FM3DMagnetoStatic(), getIndex(), and readMap().
num_gridpy_m
unsigned int FM3DMagnetoStatic::num_gridpy_m private
Read in number of points after 0(not counted here) in grid, r-direction
Definition at line 68 of file FM3DMagnetoStatic.h.
Referenced by FM3DMagnetoStatic(), getIndex(), and readMap().
num_gridpz_m
unsigned int FM3DMagnetoStatic::num_gridpz_m private
Read in number of points after 0(not counted here) in grid, z-direction
Definition at line 69 of file FM3DMagnetoStatic.h.
Referenced by FM3DMagnetoStatic(), getIndex(), and readMap().
xbegin_m
double FM3DMagnetoStatic::xbegin_m private
Definition at line 55 of file FM3DMagnetoStatic.h.
Referenced by FM3DMagnetoStatic(), getIndex(), getInfo(), isInside(), and readMap().
xend_m
double FM3DMagnetoStatic::xend_m private
Definition at line 56 of file FM3DMagnetoStatic.h.
Referenced by FM3DMagnetoStatic(), getInfo(), and isInside().
ybegin_m
double FM3DMagnetoStatic::ybegin_m private
Definition at line 58 of file FM3DMagnetoStatic.h.
Referenced by FM3DMagnetoStatic(), getIndex(), getInfo(), isInside(), and readMap().
yend_m
double FM3DMagnetoStatic::yend_m private
Definition at line 59 of file FM3DMagnetoStatic.h.
Referenced by FM3DMagnetoStatic(), getInfo(), and isInside().
zbegin_m
double FM3DMagnetoStatic::zbegin_m private
Definition at line 61 of file FM3DMagnetoStatic.h.
Referenced by FM3DMagnetoStatic(), getFieldDimensions(), getIndex(), getInfo(), and isInside().
zend_m
double FM3DMagnetoStatic::zend_m private
Definition at line 62 of file FM3DMagnetoStatic.h.
Referenced by FM3DMagnetoStatic(), getFieldDimensions(), getInfo(), and isInside().
The documentation for this class was generated from the following files:
src/Classic/Fields/FM3DMagnetoStatic.h
src/Classic/Fields/FM3DMagnetoStatic.cpp