OPAL (Object Oriented Parallel Accelerator Library): RootFinderForCSR Class Reference
RootFinderForCSR Class Reference
#include <RootFinderForCSR.h>
Classes
struct PolyParams
Public Member Functions
RootFinderForCSR (double a, double b, double d, double e)
bool hasPositiveRealRoots ()
template<class T >
T computeValue (const T &x) const
template<class T >
T computeDerivative (T x) const
double searchRoot (const double &tol)
std::pair< double, double > getSearchRange () const
Static Private Member Functions
static double computeValueGSL (double x, void *params)
Private Attributes
double a_m
double b_m
double d_m
double e_m
std::pair< double, double > searchRange_m
std::complex< double > deltaZero_m
std::complex< double > deltaOne_m
std::vector< double > thirdOrderRoots_m
Detailed Description
Definition at line 16 of file RootFinderForCSR.h.
Constructor & Destructor Documentation
RootFinderForCSR()
RootFinderForCSR::RootFinderForCSR (double a, double b, double d, double e) inline
Definition at line 18 of file RootFinderForCSR.h.
References a, deltaOne_m, deltaZero_m, and pow().
Member Function Documentation
computeDerivative()
template<class T > T RootFinderForCSR::computeDerivative (T x) const inline
Definition at line 92 of file RootFinderForCSR.h.
References a_m, b_m, d_m, pow(), and Attrib::Legacy::Distribution::T.
computeValue()
template<class T > T RootFinderForCSR::computeValue (const T & x) const inline
Definition at line 85 of file RootFinderForCSR.h.
References a_m, b_m, d_m, e_m, pow(), and Attrib::Legacy::Distribution::T.
Referenced by hasPositiveRealRoots(), and searchRoot().
computeValueGSL()
static double RootFinderForCSR::computeValueGSL (double x, void * params) inline static private
Definition at line 151 of file RootFinderForCSR.h.
References RootFinderForCSR::PolyParams::a_m, RootFinderForCSR::PolyParams::b_m, RootFinderForCSR::PolyParams::d_m, RootFinderForCSR::PolyParams::e_m, and pow().
Referenced by searchRoot().
getSearchRange()
std::pair<double, double> RootFinderForCSR::getSearchRange () const inline
Definition at line 132 of file RootFinderForCSR.h.
References searchRange_m.
hasPositiveRealRoots()
bool RootFinderForCSR::hasPositiveRealRoots () inline
Definition at line 33 of file RootFinderForCSR.h.
References a_m, abs(), b_m, C1, C2, computeValue(), copysign(), deltaOne_m, deltaZero_m, Physics::e, pow(), searchRange_m, sqrt(), and thirdOrderRoots_m.
Referenced by CSRWakeFunction::calcPsi(), and CSRIGFWakeFunction::calcPsi().
searchRoot()
double RootFinderForCSR::searchRoot (const double & tol) inline
Definition at line 98 of file RootFinderForCSR.h.
References a_m, b_m, computeValue(), computeValueGSL(), d_m, e_m, searchRange_m, and Attrib::Legacy::Distribution::T.
Referenced by CSRWakeFunction::calcPsi(), and CSRIGFWakeFunction::calcPsi().
Member Data Documentation
a_m
double RootFinderForCSR::a_m private
Definition at line 138 of file RootFinderForCSR.h.
Referenced by computeDerivative(), computeValue(), hasPositiveRealRoots(), and searchRoot().
b_m
double RootFinderForCSR::b_m private
Definition at line 139 of file RootFinderForCSR.h.
Referenced by computeDerivative(), computeValue(), hasPositiveRealRoots(), and searchRoot().
d_m
double RootFinderForCSR::d_m private
Definition at line 140 of file RootFinderForCSR.h.
Referenced by computeDerivative(), computeValue(), and searchRoot().
deltaOne_m
std::complex<double> RootFinderForCSR::deltaOne_m private
Definition at line 163 of file RootFinderForCSR.h.
Referenced by hasPositiveRealRoots(), and RootFinderForCSR().
deltaZero_m
std::complex<double> RootFinderForCSR::deltaZero_m private
Definition at line 162 of file RootFinderForCSR.h.
Referenced by hasPositiveRealRoots(), and RootFinderForCSR().
e_m
double RootFinderForCSR::e_m private
Definition at line 141 of file RootFinderForCSR.h.
Referenced by computeValue(), and searchRoot().
searchRange_m
std::pair<double, double> RootFinderForCSR::searchRange_m private
Definition at line 160 of file RootFinderForCSR.h.
Referenced by getSearchRange(), hasPositiveRealRoots(), and searchRoot().
thirdOrderRoots_m
std::vector<double> RootFinderForCSR::thirdOrderRoots_m private
Definition at line 165 of file RootFinderForCSR.h.
Referenced by hasPositiveRealRoots().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Solvers/RootFinderForCSR.h