OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyOpalElement Namespace Reference
PyOpal::PyOpalElement Namespace Reference
Functions
BOOST_PYTHON_MODULE (opal_element)
Variables
std::string track_run_docstring = std::string()
const char * module_docstring = "opal element base class"
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyOpalElement::BOOST_PYTHON_MODULE (opal_element)
Definition at line 28 of file PyOpalElement.cpp.
References PyOpal::Globals::Initialise(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_element_class(), and PyOpal::ExceptionTranslation::registerExceptions().
Variable Documentation
module_docstring
const char* PyOpal::PyOpalElement::module_docstring = "opal element base class"
Definition at line 14 of file PyOpalElement.cpp.
track_run_docstring
std::string PyOpal::PyOpalElement::track_run_docstring = std::string()
Definition at line 11 of file PyOpalElement.cpp.