OPAL (Object Oriented Parallel Accelerator Library): IpplMessageCounter Class Reference
IpplMessageCounter Class Reference
#include <IpplMessageCounter.h>
Public Member Functions
IpplMessageCounterRegion * getActiveRegion ()
void setActiveRegion (int)
void unsetActiveRegion ()
int addRegion (IpplMessageCounterRegion *)
void registerMessage (int)
void on ()
void off ()
void print ()
Static Public Member Functions
static IpplMessageCounter & getInstance ()
Private Member Functions
IpplMessageCounter ()
IpplMessageCounter (IpplMessageCounter const &copy)
IpplMessageCounter & operator= (IpplMessageCounter const &copy)
Private Attributes
int activeRegion
std::vector< IpplMessageCounterRegion * > counterRegions
bool ison
Detailed Description
Definition at line 38 of file IpplMessageCounter.h.
Constructor & Destructor Documentation
IpplMessageCounter() [1/2]
IpplMessageCounter::IpplMessageCounter () private
Definition at line 5 of file IpplMessageCounter.cpp.
IpplMessageCounter() [2/2]
IpplMessageCounter::IpplMessageCounter (IpplMessageCounter const & copy) private
Member Function Documentation
addRegion()
int IpplMessageCounter::addRegion (IpplMessageCounterRegion * mcr)
Definition at line 28 of file IpplMessageCounter.cpp.
References counterRegions.
Referenced by IpplMessageCounterRegion::IpplMessageCounterRegion().
getActiveRegion()
IpplMessageCounterRegion * IpplMessageCounter::getActiveRegion ()
Definition at line 10 of file IpplMessageCounter.cpp.
References activeRegion, and counterRegions.
Referenced by registerMessage().
getInstance()
static IpplMessageCounter& IpplMessageCounter::getInstance () inline static
Definition at line 41 of file IpplMessageCounter.h.
Referenced by IpplMessageCounterRegion::begin(), IpplMessageCounterRegion::end(), IpplMessageCounterRegion::IpplMessageCounterRegion(), CommMPI::mysend(), CommMPI::raw_isend(), CommMPI::raw_send(), and CommMPI::resend().
off()
void IpplMessageCounter::off () inline
Definition at line 56 of file IpplMessageCounter.h.
References ison.
on()
void IpplMessageCounter::on () inline
Definition at line 55 of file IpplMessageCounter.h.
References ison.
operator=()
IpplMessageCounter& IpplMessageCounter::operator= (IpplMessageCounter const & copy) private
print()
void IpplMessageCounter::print ()
Definition at line 63 of file IpplMessageCounter.cpp.
References counterRegions.
registerMessage()
void IpplMessageCounter::registerMessage (int size)
Definition at line 33 of file IpplMessageCounter.cpp.
References getActiveRegion(), ison, and IpplMessageCounterRegion::registerMessage().
Referenced by CommMPI::mysend(), CommMPI::raw_isend(), CommMPI::raw_send(), and CommMPI::resend().
setActiveRegion()
void IpplMessageCounter::setActiveRegion (int ar)
Definition at line 18 of file IpplMessageCounter.cpp.
References activeRegion.
Referenced by IpplMessageCounterRegion::begin().
unsetActiveRegion()
void IpplMessageCounter::unsetActiveRegion ()
Definition at line 23 of file IpplMessageCounter.cpp.
References activeRegion.
Referenced by IpplMessageCounterRegion::end().
Member Data Documentation
activeRegion
int IpplMessageCounter::activeRegion private
Definition at line 65 of file IpplMessageCounter.h.
Referenced by getActiveRegion(), setActiveRegion(), and unsetActiveRegion().
counterRegions
std::vector<IpplMessageCounterRegion*> IpplMessageCounter::counterRegions private
Definition at line 66 of file IpplMessageCounter.h.
Referenced by addRegion(), getActiveRegion(), and print().
ison
bool IpplMessageCounter::ison private
Definition at line 67 of file IpplMessageCounter.h.
Referenced by off(), on(), and registerMessage().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/IpplMessageCounter.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/IpplMessageCounter.cpp