OPAL (Object Oriented Parallel Accelerator Library): RBend Class Reference
RBend Class Reference abstract
#include <RBend.h>
Public Member Functions
RBend (const std::string &name)
Constructor with given name.
RBend ()
RBend (const RBend &)
virtual ~RBend ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to RBend.
virtual double getB () const =0
Get dipole field of RBend.
virtual RBendGeometry & getGeometry () override=0
Get RBend geometry.
virtual const RBendGeometry & getGeometry () const override=0
Get RBend geometry.
virtual BMultipoleField & getField () override=0
Get multipole expansion of field.
virtual const BMultipoleField & getField () const override=0
Get multipole expansion of field.
double getNormalComponent (int) const
Get normal component.
double getSkewComponent (int) const
Get skew component.
void setNormalComponent (int, double)
Set normal component.
void setSkewComponent (int, double)
Set skew component.
virtual double getEntryFaceRotation () const =0
Get pole entry face rotation.
virtual double getExitFaceRotation () const =0
Get exit pole face rotation.
virtual double getEntryFaceCurvature () const =0
Get entry pole face curvature.
virtual double getExitFaceCurvature () const =0
Get exit pole face curvature.
virtual double getSlices () const =0
Get number of slices.
virtual double getStepsize () const =0
Get stepsize.
virtual ElementBase::ElementType getType () const override
Get element type std::string.
virtual void setBendAngle (double angle) override
virtual void setEntranceAngle (double entranceAngle) override
Public Member Functions inherited from Bend2D
Bend2D (const std::string &name)
Constructor with given name.
Bend2D ()
Bend2D (const Bend2D &)
virtual ~Bend2D ()
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
Apply field to particles with coordinates in magnet frame.
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
Apply field to particles in beam frame.
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void goOnline (const double &kineticEnergy) override
virtual void finalise () override
virtual void getDimensions (double &sBegin, double &sEnd) const override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
double getBendRadius () const
double getEffectiveCenter () const
double getEffectiveLength () const
void setK1 (double k1)
Set quadrupole field component.
void setExitAngle (double exitAngle)
virtual double getExitAngle () const override
std::vector< Vector_t > getOutline () const
MeshData getSurfaceMesh () const
virtual CoordinateSystemTrafo getEdgeToEnd () const override
CoordinateSystemTrafo getBeginToEnd_local () const
virtual bool isInside (const Vector_t &r) const override
void setNSlices (const std::size_t &nSlices)
std::size_t getNSlices () const
std::array< double, 2 > getEntranceFringeFieldLength () const
Get entrance fringe field length.
std::array< double, 2 > getExitFringeFieldLength () const
Get exit fringe field length.
BoundingBox getBoundingBoxInLabCoords () const override
Public Member Functions inherited from BendBase
BendBase ()
BendBase (const BendBase &)
BendBase (const std::string &)
virtual bool bends () const
Indicates that element bends the beam.
double getChordLength () const
double getBendAngle () const
double getEntranceAngle () const
void setFullGap (double)
double getFullGap () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
double getDesignEnergy () const
std::vector< Vector_t > getDesignPath () const
void setFieldAmplitude (double k0, double k0s)
double getFieldAmplitude () const
void setFieldMapFN (std::string fileName)
std::string getFieldMapFN () const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual void goOffline ()
virtual bool Online ()
virtual void setComponentType (std::string)
virtual std::string getComponentType () const
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void operator= (const RBend &)
virtual bool findChordLength (double &chordLength) override
Additional Inherited Members
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from Bend2D
void setMessageHeader (const std::string &header)
double getStartField () const
Protected Member Functions inherited from BendBase
double calcDesignRadius (double fieldAmplitude) const
Calculate design radius from design energy and field amplitude.
double calcFieldAmplitude (double radius) const
Calculate field amplitude from design energy and radius.
double calcBendAngle (double chordLength, double radius) const
Calculate bend angle from chord length and design radius.
double calcDesignRadius (double chordLength, double angle) const
Calculate design radius from chord length and bend angle.
double calcGamma () const
Calculate gamma from design energy.
double calcBetaGamma () const
Calculate beta*gamma from design energy.
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from BendBase
double chordLength_m
double angle_m
Bend angle.
double entranceAngle_m
Fieldmap * fieldmap_m
Magnet field map.
const bool fast_m = false
Flag to turn on fast field calculation.
double gap_m
Full vertical gap of the magnets.
double designEnergy_m
Bend design energy (eV).
bool designEnergyChangeable_m
std::vector< Vector_t > refTrajMap_m
Map of reference particle trajectory.
double fieldAmplitudeX_m
double fieldAmplitudeY_m
double fieldAmplitude_m
Field amplitude.
std::string fileName_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 58 of file RBend.h.
Constructor & Destructor Documentation
RBend() [1/3]
RBend::RBend (const std::string & name) explicit
Constructor with given name.
Definition at line 72 of file RBend.cpp.
References Bend2D::setMessageHeader().
RBend() [2/3]
RBend::RBend ()
Definition at line 62 of file RBend.cpp.
RBend() [3/3]
RBend::RBend (const RBend & right)
Definition at line 66 of file RBend.cpp.
References Bend2D::setMessageHeader().
~RBend()
RBend::~RBend () virtual
Definition at line 78 of file RBend.cpp.
Member Function Documentation
accept()
void RBend::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to RBend.
Implements Bend2D.
Definition at line 81 of file RBend.cpp.
References BeamlineVisitor::visitRBend().
findChordLength()
bool RBend::findChordLength (double & chordLength) override private virtual
Implements Bend2D.
Definition at line 129 of file RBend.cpp.
References abs(), asin(), BendBase::calcDesignRadius(), copysign(), BendBase::fieldAmplitudeX_m, BendBase::fieldAmplitudeY_m, BendBase::getBendAngle(), ElementBase::getElementLength(), BendBase::getEntranceAngle(), PartBunchBase< T, Dim >::getQ(), Component::RefPartBunch_m, and sin().
getB()
virtual double RBend::getB () const pure virtual
Get dipole field of RBend.
Implemented in RBendRep.
getEntryFaceCurvature()
virtual double RBend::getEntryFaceCurvature () const pure virtual
Get entry pole face curvature.
Implemented in RBendRep.
getEntryFaceRotation()
virtual double RBend::getEntryFaceRotation () const pure virtual
Get pole entry face rotation.
Implemented in RBendRep.
getExitFaceCurvature()
virtual double RBend::getExitFaceCurvature () const pure virtual
Get exit pole face curvature.
Implemented in RBendRep.
getExitFaceRotation()
virtual double RBend::getExitFaceRotation () const pure virtual
Get exit pole face rotation.
Implemented in RBendRep.
getField() [1/2]
virtual BMultipoleField& RBend::getField () override pure virtual
Get multipole expansion of field.
Implements Component.
Implemented in RBendRep.
Referenced by getNormalComponent(), getSkewComponent(), setNormalComponent(), and setSkewComponent().
getField() [2/2]
virtual const BMultipoleField& RBend::getField () const override pure virtual
Get multipole expansion of field.
Implements Component.
Implemented in RBendRep.
getGeometry() [1/2]
virtual RBendGeometry& RBend::getGeometry () override pure virtual
Get RBend geometry.
Implements ElementBase.
Implemented in RBendRep.
getGeometry() [2/2]
virtual const RBendGeometry& RBend::getGeometry () const override pure virtual
Get RBend geometry.
Implements ElementBase.
Implemented in RBendRep.
getNormalComponent()
double RBend::getNormalComponent (int n) const
Get normal component.
Definition at line 89 of file RBend.cpp.
References getField(), BMultipoleField::getNormalComponent(), and Hypervolume::n.
getSkewComponent()
double RBend::getSkewComponent (int n) const
Get skew component.
Definition at line 93 of file RBend.cpp.
References getField(), BMultipoleField::getSkewComponent(), and Hypervolume::n.
getSlices()
virtual double RBend::getSlices () const pure virtual
Get number of slices.
Implemented in RBendRep.
getStepsize()
virtual double RBend::getStepsize () const pure virtual
Get stepsize.
Implemented in RBendRep.
getType()
ElementBase::ElementType RBend::getType () const override virtual
Get element type std::string.
Implements Bend2D.
Definition at line 115 of file RBend.cpp.
References ElementBase::RBEND.
operator=()
void RBend::operator= (const RBend &) private
setBendAngle()
void RBend::setBendAngle (double angle) override virtual
Reimplemented from BendBase.
Definition at line 119 of file RBend.cpp.
References BendBase::getEntranceAngle(), BendBase::setBendAngle(), and Bend2D::setExitAngle().
Referenced by OpalRBend::update().
setEntranceAngle()
void RBend::setEntranceAngle (double entranceAngle) override virtual
Reimplemented from Bend2D.
Definition at line 124 of file RBend.cpp.
References BendBase::getBendAngle(), Bend2D::setEntranceAngle(), and Bend2D::setExitAngle().
Referenced by OpalRBend::update().
setNormalComponent()
void RBend::setNormalComponent (int n, double v)
Set normal component.
Definition at line 97 of file RBend.cpp.
References getField(), Hypervolume::n, and BMultipoleField::setNormalComponent().
setSkewComponent()
void RBend::setSkewComponent (int n, double v)
Set skew component.
Definition at line 101 of file RBend.cpp.
References getField(), Hypervolume::n, and BMultipoleField::setSkewComponent().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/RBend.h
src/Classic/AbsBeamline/RBend.cpp