OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyLineNS Namespace Reference
PyOpal::PyLineNS Namespace Reference
Functions
BOOST_PYTHON_MODULE (line)
Variables
const char * module_docstring
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyLineNS::BOOST_PYTHON_MODULE (line)
Definition at line 29 of file PyLine.cpp.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::addGetOpalElement(), PyOpal::PyLine_< C >::append(), PyOpal::PyLine_< C >::getElement(), PyOpal::PyLine_< C >::getLength(), PyOpal::Globals::Initialise(), PyOpal::PyLine_< C >::make_class(), PyOpal::ExceptionTranslation::registerExceptions(), PyOpal::PyLine_< C >::registerObject(), and PyOpal::PyLine_< C >::setElement().
Variable Documentation
module_docstring
const char* PyOpal::PyLineNS::module_docstring
Initial value:
=
"The line module handles building of a line of elements in OPAL"
Definition at line 10 of file PyLine.cpp.