OPAL (Object Oriented Parallel Accelerator Library): PyOpal::Field Namespace Reference
PyOpal::Field Namespace Reference
Functions
py::object get_field_value_parallelt (double x, double y, double z, double t, ParallelTTracker *tracker)
py::object get_field_value_cyclotron (double x, double y, double z, double t, ParallelCyclotronTracker *tracker)
py::object get_field_value_ring (double x, double y, double z, double t, Ring *ring)
py::object get_field_value (double x, double y, double z, double t)
BOOST_PYTHON_MODULE (field)
Variables
std::string field_docstring
std::string get_field_value_docstring
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::Field::BOOST_PYTHON_MODULE (field)
Definition at line 95 of file PyField.cpp.
References field_docstring, get_field_value(), get_field_value_docstring, and PyOpal::ExceptionTranslation::registerExceptions().
get_field_value()
py::object PyOpal::Field::get_field_value (double x, double y, double z, double t)
Definition at line 76 of file PyField.cpp.
References get_field_value_cyclotron(), get_field_value_parallelt(), get_field_value_ring(), and TrackRun::getTracker().
Referenced by BOOST_PYTHON_MODULE().
get_field_value_cyclotron()
py::object PyOpal::Field::get_field_value_cyclotron (double x, double y, double z, double t, ParallelCyclotronTracker * tracker)
Definition at line 37 of file PyField.cpp.
Referenced by get_field_value().
get_field_value_parallelt()
py::object PyOpal::Field::get_field_value_parallelt (double x, double y, double z, double t, ParallelTTracker * tracker)
Definition at line 17 of file PyField.cpp.
References Attrib::Distribution::R.
Referenced by get_field_value().
get_field_value_ring()
py::object PyOpal::Field::get_field_value_ring (double x, double y, double z, double t, Ring * ring)
Definition at line 52 of file PyField.cpp.
References Ring::apply(), and Attrib::Distribution::R.
Referenced by get_field_value().
Variable Documentation
field_docstring
std::string PyOpal::Field::field_docstring
Initial value:
=
  "field module enables user to get the field at a point"
Definition at line 7 of file PyField.h.
Referenced by BOOST_PYTHON_MODULE().
get_field_value_docstring
std::string PyOpal::Field::get_field_value_docstring
Definition at line 10 of file PyField.h.
Referenced by BOOST_PYTHON_MODULE().