OPAL (Object Oriented Parallel Accelerator Library): Timer Class Reference
Timer Class Reference
#include <Timer.h>
Public Member Functions
Timer ()
void clear ()
void start ()
void stop ()
double clock_time ()
double user_time ()
double system_time ()
double cpu_time ()
Private Attributes
double wall_m
double user_m
double sys_m
boost::timer::cpu_timer timer_m
Detailed Description
Definition at line 27 of file Timer.h.
Constructor & Destructor Documentation
Timer()
Timer::Timer ()
Definition at line 24 of file Timer.cpp.
References clear().
Member Function Documentation
clear()
void Timer::clear (void)
Definition at line 29 of file Timer.cpp.
References sys_m, user_m, and wall_m.
Referenced by IpplTimerInfo::clear(), IpplInfo::IpplInfo(), IpplStats::IpplStats(), DiscField< Dim >::read_data(), IpplTimerInfo::start(), Timer(), and DiscField< Dim >::write_offset_and_data().
clock_time()
double Timer::clock_time ()
Definition at line 50 of file Timer.cpp.
References wall_m.
Referenced by operator<<(), DiscField< Dim >::read_data(), IpplTimerInfo::stop(), and DiscField< Dim >::write_offset_and_data().
cpu_time()
double Timer::cpu_time ()
Definition at line 65 of file Timer.cpp.
References sys_m, and user_m.
Referenced by operator<<(), and IpplTimerInfo::stop().
start()
void Timer::start ()
Definition at line 34 of file Timer.cpp.
References timer_m.
Referenced by IpplInfo::IpplInfo(), IpplStats::IpplStats(), DiscField< Dim >::read_data(), IpplTimerInfo::start(), and DiscField< Dim >::write_offset_and_data().
stop()
void Timer::stop ()
Definition at line 39 of file Timer.cpp.
References sys_m, timer_m, user_m, and wall_m.
Referenced by IpplTimerInfo::clear(), IpplInfo::IpplInfo(), IpplStats::IpplStats(), DiscField< Dim >::read_data(), IpplTimerInfo::start(), IpplTimerInfo::stop(), and DiscField< Dim >::write_offset_and_data().
system_time()
double Timer::system_time ()
Definition at line 60 of file Timer.cpp.
References sys_m.
user_time()
double Timer::user_time ()
Definition at line 55 of file Timer.cpp.
References user_m.
Member Data Documentation
sys_m
double Timer::sys_m private
Definition at line 45 of file Timer.h.
Referenced by clear(), cpu_time(), stop(), and system_time().
timer_m
boost::timer::cpu_timer Timer::timer_m private
Definition at line 46 of file Timer.h.
Referenced by start(), and stop().
user_m
double Timer::user_m private
Definition at line 44 of file Timer.h.
Referenced by clear(), cpu_time(), stop(), and user_time().
wall_m
double Timer::wall_m private
Definition at line 43 of file Timer.h.
Referenced by clear(), clock_time(), and stop().
The documentation for this class was generated from the following files:
ippl/src/Utility/Timer.h
ippl/src/Utility/Timer.cpp