OPAL (Object Oriented Parallel Accelerator Library): SubFieldTraits< T, Dim, SIndex< Dim >, SOffset< Dim > > Struct Template Reference
SubFieldTraits< T, Dim, SIndex< Dim >, SOffset< Dim > > Struct Template Reference
#include <SubFieldTraits.h>
Public Types
enum { Brackets_u = 0 }
typedef SIndex< Dim > Return_t
Static Public Member Functions
static int construct (SIndex< Dim > &out, const SOffset< Dim > &s, BareField< T, Dim > &A)
static void combine (const SIndex< Dim > &s1, const SOffset< Dim > &s2, Return_t &out, unsigned int, BareField< T, Dim > &)
Detailed Description
template<class T, unsigned int Dim>
struct SubFieldTraits< T, Dim, SIndex< Dim >, SOffset< Dim > >
Definition at line 217 of file SubFieldTraits.h.
Member Typedef Documentation
Return_t
template<class T , unsigned int Dim> typedef SIndex<Dim> SubFieldTraits< T, Dim, SIndex< Dim >, SOffset< Dim > >::Return_t
Definition at line 225 of file SubFieldTraits.h.
Member Enumeration Documentation
anonymous enum
template<class T , unsigned int Dim> anonymous enum
Enumerator
Brackets_u
Definition at line 226 of file SubFieldTraits.h.
Member Function Documentation
combine()
template<class T , unsigned int Dim> static void SubFieldTraits< T, Dim, SIndex< Dim >, SOffset< Dim > >::combine (const SIndex< Dim > & s1, const SOffset< Dim > & s2, Return_t & out, unsigned int, BareField< T, Dim > &) inline static
Definition at line 227 of file SubFieldTraits.h.
construct()
template<class T , unsigned int Dim> static int SubFieldTraits< T, Dim, SIndex< Dim >, SOffset< Dim > >::construct (SIndex< Dim > & out, const SOffset< Dim > & s, BareField< T, Dim > & A) inline static
Definition at line 218 of file SubFieldTraits.h.
References Dim, BareField< T, Dim >::getLayout(), SIndex< Dim >::initialize(), and SIndex< Dim >::needInitialize().
The documentation for this struct was generated from the following file:
ippl/src/SubField/SubFieldTraits.h