OPAL (Object Oriented Parallel Accelerator Library): Astra1DMagnetoStatic Class Reference
Astra1DMagnetoStatic Class Reference
#include <Astra1DMagnetoStatic.h>
Public Member Functions
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const
virtual void getFieldDimensions (double &zBegin, double &zEnd) const
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const
virtual bool getFieldDerivative (const Vector_t &R, Vector_t &E, Vector_t &B, const DiffDirection &dir) const
virtual void swap ()
virtual void getInfo (Inform *)
virtual double getFrequency () const
virtual void setFrequency (double freq)
virtual bool isInside (const Vector_t &r) const
Public Member Functions inherited from Fieldmap
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &onaxis)
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Private Member Functions
Astra1DMagnetoStatic (std::string aFilename)
~Astra1DMagnetoStatic ()
virtual void readMap ()
virtual void freeMap ()
Private Attributes
double * FourCoefs_m
double zbegin_m
double zend_m
double length_m
int accuracy_m
int num_gridpz_m
Friends
class Fieldmap
Additional Inherited Members
Static Public Member Functions inherited from Fieldmap
static Fieldmap * getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions inherited from Fieldmap
Fieldmap ()=delete
Fieldmap (const std::string &aFilename)
virtual ~Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions inherited from Fieldmap
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes inherited from Fieldmap
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Detailed Description
Definition at line 6 of file Astra1DMagnetoStatic.h.
Constructor & Destructor Documentation
Astra1DMagnetoStatic()
Astra1DMagnetoStatic::Astra1DMagnetoStatic (std::string aFilename) private
Definition at line 15 of file Astra1DMagnetoStatic.cpp.
References accuracy_m, Fieldmap::disableFieldmapWarning(), Physics::e, Fieldmap::Filename_m, length_m, Fieldmap::lines_read_m, Fieldmap::noFieldmapWarning(), Fieldmap::normalize_m, num_gridpz_m, TAstraMagnetoStatic, Util::toUpper(), Fieldmap::Type, zbegin_m, and zend_m.
~Astra1DMagnetoStatic()
Astra1DMagnetoStatic::~Astra1DMagnetoStatic () private
Definition at line 74 of file Astra1DMagnetoStatic.cpp.
References freeMap().
Member Function Documentation
freeMap()
void Astra1DMagnetoStatic::freeMap () private virtual
Implements Fieldmap.
Definition at line 160 of file Astra1DMagnetoStatic.cpp.
References endl(), Fieldmap::Filename_m, FourCoefs_m, INFOMSG, level3(), and Fieldmap::typeset_msg().
Referenced by ~Astra1DMagnetoStatic().
getFieldDerivative()
bool Astra1DMagnetoStatic::getFieldDerivative (const Vector_t & R, Vector_t & E, Vector_t & B, const DiffDirection & dir) const virtual
Implements Fieldmap.
Definition at line 205 of file Astra1DMagnetoStatic.cpp.
getFieldDimensions() [1/2]
void Astra1DMagnetoStatic::getFieldDimensions (double & zBegin, double & zEnd) const virtual
Implements Fieldmap.
Definition at line 209 of file Astra1DMagnetoStatic.cpp.
References zbegin_m, and zend_m.
getFieldDimensions() [2/2]
void Astra1DMagnetoStatic::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const virtual
Implements Fieldmap.
Definition at line 213 of file Astra1DMagnetoStatic.cpp.
getFieldstrength()
bool Astra1DMagnetoStatic::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const virtual
Implements Fieldmap.
Definition at line 170 of file Astra1DMagnetoStatic.cpp.
References accuracy_m, cos(), FourCoefs_m, length_m, Hypervolume::n, Physics::pi, Attrib::Distribution::R, sin(), Physics::two_pi, and zbegin_m.
getFrequency()
double Astra1DMagnetoStatic::getFrequency () const virtual
Implements Fieldmap.
Definition at line 222 of file Astra1DMagnetoStatic.cpp.
getInfo()
void Astra1DMagnetoStatic::getInfo (Inform * msg) virtual
Implements Fieldmap.
Definition at line 218 of file Astra1DMagnetoStatic.cpp.
References endl(), Fieldmap::Filename_m, zbegin_m, and zend_m.
isInside()
bool Astra1DMagnetoStatic::isInside (const Vector_t & r) const inline virtual
Reimplemented from Fieldmap.
Definition at line 38 of file Astra1DMagnetoStatic.h.
References zbegin_m, and zend_m.
readMap()
void Astra1DMagnetoStatic::readMap () private virtual
Implements Fieldmap.
Definition at line 78 of file Astra1DMagnetoStatic.cpp.
References abs(), accuracy_m, Physics::e, endl(), Fieldmap::Filename_m, FourCoefs_m, Fieldmap::getLine(), INFOMSG, level3(), Fieldmap::normalize_m, num_gridpz_m, real(), Fieldmap::typeset_msg(), zbegin_m, and zend_m.
setFrequency()
void Astra1DMagnetoStatic::setFrequency (double freq) virtual
Implements Fieldmap.
Definition at line 226 of file Astra1DMagnetoStatic.cpp.
swap()
void Astra1DMagnetoStatic::swap () virtual
Implements Fieldmap.
Definition at line 215 of file Astra1DMagnetoStatic.cpp.
Friends And Related Function Documentation
Fieldmap
friend class Fieldmap friend
Definition at line 35 of file Astra1DMagnetoStatic.h.
Member Data Documentation
accuracy_m
int Astra1DMagnetoStatic::accuracy_m private
Definition at line 32 of file Astra1DMagnetoStatic.h.
Referenced by Astra1DMagnetoStatic(), getFieldstrength(), and readMap().
FourCoefs_m
double* Astra1DMagnetoStatic::FourCoefs_m private
Definition at line 26 of file Astra1DMagnetoStatic.h.
Referenced by freeMap(), getFieldstrength(), and readMap().
length_m
double Astra1DMagnetoStatic::length_m private
Definition at line 30 of file Astra1DMagnetoStatic.h.
Referenced by Astra1DMagnetoStatic(), and getFieldstrength().
num_gridpz_m
int Astra1DMagnetoStatic::num_gridpz_m private
Definition at line 33 of file Astra1DMagnetoStatic.h.
Referenced by Astra1DMagnetoStatic(), and readMap().
zbegin_m
double Astra1DMagnetoStatic::zbegin_m private
Definition at line 28 of file Astra1DMagnetoStatic.h.
Referenced by Astra1DMagnetoStatic(), getFieldDimensions(), getFieldstrength(), getInfo(), isInside(), and readMap().
zend_m
double Astra1DMagnetoStatic::zend_m private
Definition at line 29 of file Astra1DMagnetoStatic.h.
Referenced by Astra1DMagnetoStatic(), getFieldDimensions(), getInfo(), isInside(), and readMap().
The documentation for this class was generated from the following files:
src/Classic/Fields/Astra1DMagnetoStatic.h
src/Classic/Fields/Astra1DMagnetoStatic.cpp