OPAL (Object Oriented Parallel Accelerator Library): ParticleUniformLayout< T, Dim > Class Template Reference
ParticleUniformLayout< T, Dim > Class Template Reference
#include <ParticleBalancer.h>
Public Types
typedef int pair_t
typedef pair_t * pair_iterator
typedef ParticleLayout< T, Dim >::SingleParticlePos_t SingleParticlePos_t
typedef ParticleLayout< T, Dim >::Index_t Index_t
typedef ParticleAttrib< SingleParticlePos_t > ParticlePos_t
typedef ParticleAttrib< Index_t > ParticleIndex_t
Public Types inherited from ParticleLayout< T, Dim >
enum { Dimension = Dim }
enum UpdateFlags {
SWAP, BCONDS, NUMFLAGS, OPTDESTROY,
ALL
}
typedef T Position_t
typedef unsigned Index_t
typedef Vektor< T, Dim > SingleParticlePos_t
Public Member Functions
ParticleUniformLayout ()
~ParticleUniformLayout ()
void update (IpplParticleBase< ParticleUniformLayout< T, Dim > > &p, const ParticleAttrib< char > *canSwap=0)
void printDebug (Inform &)
Public Member Functions inherited from ParticleLayout< T, Dim >
ParticleLayout ()
~ParticleLayout ()
void setUpdateFlag (UpdateFlags f, bool val)
bool getUpdateFlag (UpdateFlags f) const
ParticleBConds< T, Dim > & getBConds ()
void setBConds (const ParticleBConds< T, Dim > &bc)
Private Attributes
int * LocalSize
int * Change
int * MsgCount
Additional Inherited Members
Protected Member Functions inherited from ParticleLayout< T, Dim >
template<class PPT , class NDI >
void apply_bconds (unsigned n, PPT &R, const ParticleBConds< T, Dim > &bcs, const NDI &nr)
Detailed Description
template<class T, unsigned Dim>
class ParticleUniformLayout< T, Dim >
Definition at line 30 of file ParticleBalancer.h.
Member Typedef Documentation
Index_t
template<class T , unsigned Dim> typedef ParticleLayout<T, Dim>::Index_t ParticleUniformLayout< T, Dim >::Index_t
Definition at line 48 of file ParticleUniformLayout.h.
pair_iterator
template<class T , unsigned Dim> typedef pair_t* ParticleUniformLayout< T, Dim >::pair_iterator
Definition at line 44 of file ParticleUniformLayout.h.
pair_t
template<class T , unsigned Dim> typedef int ParticleUniformLayout< T, Dim >::pair_t
Definition at line 43 of file ParticleUniformLayout.h.
ParticleIndex_t
template<class T , unsigned Dim> typedef ParticleAttrib<Index_t> ParticleUniformLayout< T, Dim >::ParticleIndex_t
Definition at line 52 of file ParticleUniformLayout.h.
ParticlePos_t
template<class T , unsigned Dim> typedef ParticleAttrib<SingleParticlePos_t> ParticleUniformLayout< T, Dim >::ParticlePos_t
Definition at line 51 of file ParticleUniformLayout.h.
SingleParticlePos_t
template<class T , unsigned Dim> typedef ParticleLayout<T, Dim>::SingleParticlePos_t ParticleUniformLayout< T, Dim >::SingleParticlePos_t
Definition at line 47 of file ParticleUniformLayout.h.
Constructor & Destructor Documentation
ParticleUniformLayout()
template<class T , unsigned Dim> ParticleUniformLayout< T, Dim >::ParticleUniformLayout ()
Definition at line 39 of file ParticleUniformLayout.hpp.
References IpplInfo::getNodes().
~ParticleUniformLayout()
template<class T , unsigned Dim> ParticleUniformLayout< T, Dim >::~ParticleUniformLayout ()
Definition at line 51 of file ParticleUniformLayout.hpp.
Member Function Documentation
printDebug()
template<class T , unsigned Dim> void ParticleUniformLayout< T, Dim >::printDebug (Inform & o)
Definition at line 313 of file ParticleUniformLayout.hpp.
update()
template<class T , unsigned Dim> void ParticleUniformLayout< T, Dim >::update (IpplParticleBase< ParticleUniformLayout< T, Dim > > & p, const ParticleAttrib< char > * canSwap = 0)
Definition at line 65 of file ParticleUniformLayout.hpp.
References IpplInfo::Comm, Communicate::COMM_ANY_NODE, Message::get(), IpplInfo::getNodes(), IpplInfo::myNode(), TagMaker::next_tag(), P_LAYOUT_CYCLE, P_WEIGHTED_LAYOUT_TAG, P_WEIGHTED_RETURN_TAG, P_WEIGHTED_TRANSFER_TAG, Message::put(), Communicate::receive_block(), and Communicate::send().
Member Data Documentation
Change
template<class T , unsigned Dim> int* ParticleUniformLayout< T, Dim >::Change private
Definition at line 80 of file ParticleUniformLayout.h.
LocalSize
template<class T , unsigned Dim> int* ParticleUniformLayout< T, Dim >::LocalSize private
Definition at line 79 of file ParticleUniformLayout.h.
MsgCount
template<class T , unsigned Dim> int* ParticleUniformLayout< T, Dim >::MsgCount private
Definition at line 81 of file ParticleUniformLayout.h.
The documentation for this class was generated from the following files:
ippl/src/Particle/ParticleBalancer.h
ippl/src/Particle/ParticleUniformLayout.h
ippl/src/Particle/ParticleUniformLayout.hpp