OPAL (Object Oriented Parallel Accelerator Library): interpolation::MVector< Tmplt > Class Template Reference
interpolation::MVector< Tmplt > Class Template Reference
#include <MVector.h>
Public Member Functions
MVector ()
MVector (const MVector< Tmplt > &mv)
MVector (const Tmplt *ta_beg, const Tmplt *ta_end)
MVector (std::vector< Tmplt > tv)
MVector (size_t i)
MVector (size_t i, Tmplt value)
template<class Tmplt2 >
MVector (MVector< Tmplt2 >)
~MVector ()
size_t num_row () const
Tmplt & operator() (size_t i)
const Tmplt & operator() (size_t i) const
MVector< Tmplt > sub (size_t n1, size_t n2) const
MMatrix< Tmplt > T () const
MVector< Tmplt > & operator= (const MVector< Tmplt > &mv)
template<>
const double & operator() (const size_t i) const
template<>
const m_complex & operator() (const size_t i) const
template<>
double & operator() (const size_t i)
template<>
m_complex & operator() (const size_t i)
template<>
MVector< double > & operator= (const MVector< double > &mv)
template<>
MVector< m_complex > & operator= (const MVector< m_complex > &mv)
Private Member Functions
void build_vector (size_t size)
void build_vector (const Tmplt *data_start, const Tmplt *data_end)
void delete_vector ()
template<>
void build_vector (size_t size)
template<>
void build_vector (size_t size)
template<>
void delete_vector ()
template<>
void delete_vector ()
Static Private Member Functions
static gsl_vector * get_vector (const MVector< double > &m)
static gsl_vector_complex * get_vector (const MVector< m_complex > &m)
Private Attributes
void * _vector
Friends
class MMatrix< Tmplt >
class MMatrix< double >
MVector< m_complex > & operator*= (MVector< m_complex > &v, m_complex c)
MVector< double > & operator*= (MVector< double > &v, double d)
MVector< m_complex > & operator+= (MVector< m_complex > &v1, MVector< m_complex > v2)
MVector< double > & operator+= (MVector< double > &v1, MVector< double > v2)
MVector< m_complex > operator* (MMatrix< m_complex > m, MVector< m_complex > v)
MVector< double > operator* (MMatrix< double > m, MVector< double > v)
Detailed Description
template<class Tmplt>
class interpolation::MVector< Tmplt >
Definition at line 119 of file MVector.h.
Constructor & Destructor Documentation
MVector() [1/7]
template<class Tmplt> interpolation::MVector< Tmplt >::MVector () inline
Definition at line 122 of file MVector.h.
MVector() [2/7]
template<typename Tmplt > interpolation::MVector< Tmplt >::MVector (const MVector< Tmplt > & mv)
Definition at line 77 of file MVector.cpp.
MVector() [3/7]
template<class Tmplt> interpolation::MVector< Tmplt >::MVector (const Tmplt * ta_beg, const Tmplt * ta_end) inline
Definition at line 124 of file MVector.h.
References interpolation::MVector< Tmplt >::build_vector().
MVector() [4/7]
template<class Tmplt> interpolation::MVector< Tmplt >::MVector (std::vector< Tmplt > tv) inline
Definition at line 125 of file MVector.h.
References interpolation::MVector< Tmplt >::build_vector().
MVector() [5/7]
template<typename Tmplt > interpolation::MVector< Tmplt >::MVector (size_t i)
Definition at line 70 of file MVector.cpp.
References interpolation::MVector< Tmplt >::build_vector().
MVector() [6/7]
template<typename Tmplt > interpolation::MVector< Tmplt >::MVector (size_t i, Tmplt value)
Definition at line 82 of file MVector.cpp.
References interpolation::MVector< Tmplt >::build_vector().
MVector() [7/7]
template<class Tmplt> template<class Tmplt2 > interpolation::MVector< Tmplt >::MVector (MVector< Tmplt2 >)
~MVector()
template<class Tmplt > interpolation::MVector< Tmplt >::~MVector () inline
Definition at line 207 of file MVector.h.
Member Function Documentation
build_vector() [1/4]
template<> void interpolation::MVector< double >::build_vector (size_t size) private
Definition at line 90 of file MVector.cpp.
build_vector() [2/4]
template<> void interpolation::MVector< m_complex >::build_vector (size_t size) private
Definition at line 97 of file MVector.cpp.
build_vector() [3/4]
template<class Tmplt> void interpolation::MVector< Tmplt >::build_vector (size_t size) private
Referenced by interpolation::MVector< Tmplt >::MVector().
build_vector() [4/4]
template<class Tmplt > void interpolation::MVector< Tmplt >::build_vector (const Tmplt * data_start, const Tmplt * data_end) private
Definition at line 104 of file MVector.cpp.
delete_vector() [1/3]
template<class Tmplt> void interpolation::MVector< Tmplt >::delete_vector () private
delete_vector() [2/3]
template<> void interpolation::MVector< double >::delete_vector () inline private
Definition at line 209 of file MVector.h.
delete_vector() [3/3]
template<> void interpolation::MVector< m_complex >::delete_vector () inline private
Definition at line 211 of file MVector.h.
get_vector() [1/2]
template<class Tmplt > gsl_vector inline * interpolation::MVector< Tmplt >::get_vector (const MVector< double > & m) static private
Definition at line 246 of file MVector.h.
References interpolation::MVector< Tmplt >::_vector.
Referenced by interpolation::MMatrix< double >::eigenvalues(), and interpolation::MMatrix< double >::eigenvectors().
get_vector() [2/2]
template<class Tmplt > gsl_vector_complex inline * interpolation::MVector< Tmplt >::get_vector (const MVector< m_complex > & m) static private
Definition at line 254 of file MVector.h.
References interpolation::MVector< Tmplt >::_vector.
num_row()
template<class Tmplt > template size_t interpolation::MVector< Tmplt >::num_row () const
Definition at line 112 of file MVector.cpp.
Referenced by interpolation::operator-(), interpolation::MVector< Tmplt >::operator=(), interpolation::operator==(), and interpolation::operator>>().
operator()() [1/6]
template<> const double & interpolation::MVector< double >::operator() (const size_t i) const
Definition at line 118 of file MVector.cpp.
operator()() [2/6]
template<> const m_complex & interpolation::MVector< m_complex >::operator() (const size_t i) const
Definition at line 121 of file MVector.cpp.
operator()() [3/6]
template<> double & interpolation::MVector< double >::operator() (const size_t i)
Definition at line 124 of file MVector.cpp.
operator()() [4/6]
template<> m_complex & interpolation::MVector< m_complex >::operator() (const size_t i)
Definition at line 127 of file MVector.cpp.
operator()() [5/6]
template<class Tmplt> Tmplt& interpolation::MVector< Tmplt >::operator() (size_t i)
operator()() [6/6]
template<class Tmplt> const Tmplt& interpolation::MVector< Tmplt >::operator() (size_t i) const
operator=() [1/3]
template<class Tmplt> MVector<Tmplt>& interpolation::MVector< Tmplt >::operator= (const MVector< Tmplt > & mv)
operator=() [2/3]
template<> MVector< double > & interpolation::MVector< double >::operator= (const MVector< double > & mv)
Definition at line 154 of file MVector.cpp.
References interpolation::MVector< Tmplt >::_vector, and interpolation::MVector< Tmplt >::num_row().
operator=() [3/3]
template<> MVector< m_complex > & interpolation::MVector< m_complex >::operator= (const MVector< m_complex > & mv)
Definition at line 165 of file MVector.cpp.
References interpolation::MVector< Tmplt >::_vector, and interpolation::MVector< Tmplt >::num_row().
sub()
template<class Tmplt > MVector< Tmplt > interpolation::MVector< Tmplt >::sub (size_t n1, size_t n2) const
Definition at line 192 of file MVector.cpp.
T()
template<class Tmplt > template MMatrix< m_complex > interpolation::MVector< Tmplt >::T () const
Definition at line 132 of file MVector.cpp.
Friends And Related Function Documentation
MMatrix< double >
template<class Tmplt> friend class MMatrix< double > friend
Definition at line 151 of file MVector.h.
MMatrix< Tmplt >
template<class Tmplt> friend class MMatrix< Tmplt > friend
Definition at line 150 of file MVector.h.
operator* [1/2]
template<class Tmplt> MVector<m_complex> operator* (MMatrix< m_complex > m, MVector< m_complex > v) friend
Definition at line 271 of file MMatrix.h.
operator* [2/2]
template<class Tmplt> MVector<double> operator* (MMatrix< double > m, MVector< double > v) friend
Definition at line 278 of file MMatrix.h.
operator*= [1/2]
template<class Tmplt> MVector<m_complex>& operator*= (MVector< m_complex > & v, m_complex c) friend
Definition at line 213 of file MVector.h.
operator*= [2/2]
template<class Tmplt> MVector<double>& operator*= (MVector< double > & v, double d) friend
Definition at line 215 of file MVector.h.
operator+= [1/2]
template<class Tmplt> MVector<m_complex>& operator+= (MVector< m_complex > & v1, MVector< m_complex > v2) friend
Definition at line 228 of file MVector.h.
operator+= [2/2]
template<class Tmplt> MVector<double>& operator+= (MVector< double > & v1, MVector< double > v2) friend
Definition at line 230 of file MVector.h.
Member Data Documentation
_vector
template<class Tmplt> void* interpolation::MVector< Tmplt >::_vector private
Definition at line 163 of file MVector.h.
Referenced by interpolation::MVector< Tmplt >::get_vector(), interpolation::operator*(), interpolation::operator*=(), interpolation::operator+=(), and interpolation::MVector< Tmplt >::operator=().
The documentation for this class was generated from the following files:
src/Classic/Fields/Interpolation/MVector.h
src/Classic/Fields/Interpolation/MVector.cpp