OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Meshes/Cartesian.hpp File Reference
Cartesian.hpp File Reference
#include "Utility/PAssert.h"
#include "Utility/IpplException.h"
#include "Utility/IpplInfo.h"
#include "Field/BareField.h"
#include "Field/BrickExpression.h"
#include "Field/LField.h"
#include "Field/Field.h"
#include "Field/Assign.h"
#include "Field/AssignDefs.h"
Classes
struct OpMeshPeriodic< T >
struct OpMeshExtrapolate< T >
Namespaces
IPPL
Functions
template<class T >
void PETE_apply (OpMeshPeriodic< T >, T &a, T b)
template<class T >
void PETE_apply (OpMeshExtrapolate< T > e, T &a, T b)
template<class T , class MFLOAT >
Field< T, 1U, Cartesian< 1U, MFLOAT >, Cell > & Div (Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > &x, Field< T, 1U, Cartesian< 1U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< T, 2U, Cartesian< 2U, MFLOAT >, Cell > & Div (Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > &x, Field< T, 2U, Cartesian< 2U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< T, 3U, Cartesian< 3U, MFLOAT >, Cell > & Div (Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > &x, Field< T, 3U, Cartesian< 3U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< T, 1U, Cartesian< 1U, MFLOAT >, Vert > & Div (Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > &x, Field< T, 1U, Cartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 2U, Cartesian< 2U, MFLOAT >, Vert > & Div (Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > &x, Field< T, 2U, Cartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 3U, Cartesian< 3U, MFLOAT >, Vert > & Div (Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > &x, Field< T, 3U, Cartesian< 3U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 1U, Cartesian< 1U, MFLOAT >, Vert > & Div (Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > &x, Field< T, 1U, Cartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 2U, Cartesian< 2U, MFLOAT >, Vert > & Div (Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > &x, Field< T, 2U, Cartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 3U, Cartesian< 3U, MFLOAT >, Vert > & Div (Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > &x, Field< T, 3U, Cartesian< 3U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 1U, Cartesian< 1U, MFLOAT >, Cell > & Div (Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > &x, Field< T, 1U, Cartesian< 1U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< T, 2U, Cartesian< 2U, MFLOAT >, Cell > & Div (Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > &x, Field< T, 2U, Cartesian< 2U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< T, 3U, Cartesian< 3U, MFLOAT >, Cell > & Div (Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > &x, Field< T, 3U, Cartesian< 3U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & Div (Field< Tenzor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > &x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > & Div (Field< Tenzor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > &x, Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & Div (Field< Tenzor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > &x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & Div (Field< SymTenzor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > &x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > & Div (Field< SymTenzor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > &x, Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & Div (Field< SymTenzor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > &x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & Div (Field< Tenzor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > &x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & Div (Field< Tenzor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > &x, Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & Div (Field< Tenzor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > &x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & Div (Field< SymTenzor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > &x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & Div (Field< SymTenzor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > &x, Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & Div (Field< SymTenzor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > &x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & Grad (Field< T, 1U, Cartesian< 1U, MFLOAT >, Vert > &x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2u >, 2U, Cartesian< 2U, MFLOAT >, Cell > & Grad (Field< T, 2U, Cartesian< 2U, MFLOAT >, Vert > &x, Field< Vektor< T, 2u >, 2U, Cartesian< 2U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & Grad (Field< T, 3U, Cartesian< 3U, MFLOAT >, Vert > &x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & Grad (Field< T, 1U, Cartesian< 1U, MFLOAT >, Cell > &x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & Grad (Field< T, 2U, Cartesian< 2U, MFLOAT >, Cell > &x, Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & Grad (Field< T, 3U, Cartesian< 3U, MFLOAT >, Cell > &x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & Grad (Field< T, 1U, Cartesian< 1U, MFLOAT >, Vert > &x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & Grad (Field< T, 2U, Cartesian< 2U, MFLOAT >, Vert > &x, Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & Grad (Field< T, 3U, Cartesian< 3U, MFLOAT >, Vert > &x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & Grad (Field< T, 1U, Cartesian< 1U, MFLOAT >, Cell > &x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2u >, 2U, Cartesian< 2U, MFLOAT >, Cell > & Grad (Field< T, 2U, Cartesian< 2U, MFLOAT >, Cell > &x, Field< Vektor< T, 2u >, 2U, Cartesian< 2U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & Grad (Field< T, 3U, Cartesian< 3U, MFLOAT >, Cell > &x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Tenzor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & Grad (Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > &x, Field< Tenzor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Tenzor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > & Grad (Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > &x, Field< Tenzor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Tenzor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & Grad (Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > &x, Field< Tenzor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Tenzor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & Grad (Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > &x, Field< Tenzor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Tenzor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & Grad (Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > &x, Field< Tenzor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Tenzor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & Grad (Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > &x, Field< Tenzor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > &x, Field< T2, 1U, Cartesian< 1U, MFLOAT >, Cell > &w, Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > &x, Field< T2, 2U, Cartesian< 2U, MFLOAT >, Cell > &w, Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > &x, Field< T2, 3U, Cartesian< 3U, MFLOAT >, Cell > &w, Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > &x, Field< T2, 1U, Cartesian< 1U, MFLOAT >, Vert > &w, Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > &x, Field< T2, 2U, Cartesian< 2U, MFLOAT >, Vert > &w, Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > &x, Field< T2, 3U, Cartesian< 3U, MFLOAT >, Vert > &w, Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > &r)
template<class T1 , class MFLOAT >
Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > &x, Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > &r)
template<class T1 , class MFLOAT >
Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > &x, Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > &r)
template<class T1 , class MFLOAT >
Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > &x, Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > &r)
template<class T1 , class MFLOAT >
Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > &x, Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > &r)
template<class T1 , class MFLOAT >
Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > &x, Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > &r)
template<class T1 , class MFLOAT >
Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > &x, Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > &r)
Function Documentation
Div() [1/24]
template<class T , class MFLOAT > Field<T,1U,Cartesian<1U,MFLOAT>,Cell>& Div (Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & x, Field< T, 1U, Cartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 2192 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [2/24]
template<class T , class MFLOAT > Field<T,2U,Cartesian<2U,MFLOAT>,Cell>& Div (Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & x, Field< T, 2U, Cartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 2207 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [3/24]
template<class T , class MFLOAT > Field<T,3U,Cartesian<3U,MFLOAT>,Cell>& Div (Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & x, Field< T, 3U, Cartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 2225 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [4/24]
template<class T , class MFLOAT > Field<T,1U,Cartesian<1U,MFLOAT>,Vert>& Div (Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & x, Field< T, 1U, Cartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 2250 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [5/24]
template<class T , class MFLOAT > Field<T,2U,Cartesian<2U,MFLOAT>,Vert>& Div (Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > & x, Field< T, 2U, Cartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 2265 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [6/24]
template<class T , class MFLOAT > Field<T,3U,Cartesian<3U,MFLOAT>,Vert>& Div (Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & x, Field< T, 3U, Cartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 2283 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [7/24]
template<class T , class MFLOAT > Field<T,1U,Cartesian<1U,MFLOAT>,Vert>& Div (Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & x, Field< T, 1U, Cartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 2323 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [8/24]
template<class T , class MFLOAT > Field<T,2U,Cartesian<2U,MFLOAT>,Vert>& Div (Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & x, Field< T, 2U, Cartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 2338 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [9/24]
template<class T , class MFLOAT > Field<T,3U,Cartesian<3U,MFLOAT>,Vert>& Div (Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & x, Field< T, 3U, Cartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 2359 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [10/24]
template<class T , class MFLOAT > Field<T,1U,Cartesian<1U,MFLOAT>,Cell>& Div (Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & x, Field< T, 1U, Cartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 2396 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [11/24]
template<class T , class MFLOAT > Field<T,2U,Cartesian<2U,MFLOAT>,Cell>& Div (Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > & x, Field< T, 2U, Cartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 2411 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [12/24]
template<class T , class MFLOAT > Field<T,3U,Cartesian<3U,MFLOAT>,Cell>& Div (Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & x, Field< T, 3U, Cartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 2432 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [13/24]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,Cartesian<1U,MFLOAT>,Cell>& Div (Field< Tenzor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 2465 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [14/24]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,Cartesian<2U,MFLOAT>,Cell>& Div (Field< Tenzor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & x, Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 2480 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [15/24]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,Cartesian<3U,MFLOAT>,Cell>& Div (Field< Tenzor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 2498 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [16/24]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,Cartesian<1U,MFLOAT>,Cell>& Div (Field< SymTenzor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 2523 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [17/24]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,Cartesian<2U,MFLOAT>,Cell>& Div (Field< SymTenzor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & x, Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 2538 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [18/24]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,Cartesian<3U,MFLOAT>,Cell>& Div (Field< SymTenzor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 2556 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [19/24]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,Cartesian<1U,MFLOAT>,Vert>& Div (Field< Tenzor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 2582 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [20/24]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,Cartesian<2U,MFLOAT>,Vert>& Div (Field< Tenzor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > & x, Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 2597 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [21/24]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,Cartesian<3U,MFLOAT>,Vert>& Div (Field< Tenzor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 2615 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [22/24]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,Cartesian<1U,MFLOAT>,Vert>& Div (Field< SymTenzor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 2641 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [23/24]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,Cartesian<2U,MFLOAT>,Vert>& Div (Field< SymTenzor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > & x, Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 2656 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Div() [24/24]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,Cartesian<3U,MFLOAT>,Vert>& Div (Field< SymTenzor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 2674 of file Cartesian.hpp.
References dot(), and PAssert_EQ.
Grad() [1/18]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,Cartesian<1U,MFLOAT>,Cell>& Grad (Field< T, 1U, Cartesian< 1U, MFLOAT >, Vert > & x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 2702 of file Cartesian.hpp.
References PAssert_EQ.
Referenced by PartBunch::computeSelfFields(), and PartBunch::computeSelfFields_cycl().
Grad() [2/18]
template<class T , class MFLOAT > Field<Vektor<T,2u>,2U,Cartesian<2U,MFLOAT>,Cell>& Grad (Field< T, 2U, Cartesian< 2U, MFLOAT >, Vert > & x, Field< Vektor< T, 2u >, 2U, Cartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 2716 of file Cartesian.hpp.
References PAssert_EQ.
Grad() [3/18]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,Cartesian<3U,MFLOAT>,Cell>& Grad (Field< T, 3U, Cartesian< 3U, MFLOAT >, Vert > & x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 2733 of file Cartesian.hpp.
References PAssert_EQ.
Grad() [4/18]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,Cartesian<1U,MFLOAT>,Vert>& Grad (Field< T, 1U, Cartesian< 1U, MFLOAT >, Cell > & x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 2759 of file Cartesian.hpp.
References PAssert_EQ.
Grad() [5/18]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,Cartesian<2U,MFLOAT>,Vert>& Grad (Field< T, 2U, Cartesian< 2U, MFLOAT >, Cell > & x, Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 2773 of file Cartesian.hpp.
References PAssert_EQ.
Grad() [6/18]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,Cartesian<3U,MFLOAT>,Vert>& Grad (Field< T, 3U, Cartesian< 3U, MFLOAT >, Cell > & x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 2790 of file Cartesian.hpp.
References PAssert_EQ.
Grad() [7/18]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,Cartesian<1U,MFLOAT>,Vert>& Grad (Field< T, 1U, Cartesian< 1U, MFLOAT >, Vert > & x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 2830 of file Cartesian.hpp.
References PAssert_EQ.
Grad() [8/18]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,Cartesian<2U,MFLOAT>,Vert>& Grad (Field< T, 2U, Cartesian< 2U, MFLOAT >, Vert > & x, Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 2848 of file Cartesian.hpp.
References PAssert_EQ.
Grad() [9/18]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,Cartesian<3U,MFLOAT>,Vert>& Grad (Field< T, 3U, Cartesian< 3U, MFLOAT >, Vert > & x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 2874 of file Cartesian.hpp.
References PAssert_EQ.
Grad() [10/18]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,Cartesian<1U,MFLOAT>,Cell>& Grad (Field< T, 1U, Cartesian< 1U, MFLOAT >, Cell > & x, Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 2910 of file Cartesian.hpp.
References PAssert_EQ.
Grad() [11/18]
template<class T , class MFLOAT > Field<Vektor<T,2u>,2U,Cartesian<2U,MFLOAT>,Cell>& Grad (Field< T, 2U, Cartesian< 2U, MFLOAT >, Cell > & x, Field< Vektor< T, 2u >, 2U, Cartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 2928 of file Cartesian.hpp.
References PAssert_EQ.
Grad() [12/18]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,Cartesian<3U,MFLOAT>,Cell>& Grad (Field< T, 3U, Cartesian< 3U, MFLOAT >, Cell > & x, Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 2954 of file Cartesian.hpp.
References PAssert_EQ.
Grad() [13/18]
template<class T , class MFLOAT > Field<Tenzor<T,1U>,1U,Cartesian<1U,MFLOAT>,Cell>& Grad (Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & x, Field< Tenzor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 2990 of file Cartesian.hpp.
References outerProduct(), and PAssert_EQ.
Grad() [14/18]
template<class T , class MFLOAT > Field<Tenzor<T,2U>,2U,Cartesian<2U,MFLOAT>,Cell>& Grad (Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & x, Field< Tenzor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 3005 of file Cartesian.hpp.
References outerProduct(), and PAssert_EQ.
Grad() [15/18]
template<class T , class MFLOAT > Field<Tenzor<T,3U>,3U,Cartesian<3U,MFLOAT>,Cell>& Grad (Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & x, Field< Tenzor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 3023 of file Cartesian.hpp.
References outerProduct(), and PAssert_EQ.
Grad() [16/18]
template<class T , class MFLOAT > Field<Tenzor<T,1U>,1U,Cartesian<1U,MFLOAT>,Vert>& Grad (Field< Vektor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Cell > & x, Field< Tenzor< T, 1U >, 1U, Cartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 3050 of file Cartesian.hpp.
References outerProduct(), and PAssert_EQ.
Grad() [17/18]
template<class T , class MFLOAT > Field<Tenzor<T,2U>,2U,Cartesian<2U,MFLOAT>,Vert>& Grad (Field< Vektor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Cell > & x, Field< Tenzor< T, 2U >, 2U, Cartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 3065 of file Cartesian.hpp.
References outerProduct(), and PAssert_EQ.
Grad() [18/18]
template<class T , class MFLOAT > Field<Tenzor<T,3U>,3U,Cartesian<3U,MFLOAT>,Vert>& Grad (Field< Vektor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Cell > & x, Field< Tenzor< T, 3U >, 3U, Cartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 3083 of file Cartesian.hpp.
References outerProduct(), and PAssert_EQ.
PETE_apply() [1/2]
template<class T > void PETE_apply (OpMeshPeriodic< T > , T & a, T b) inline
Definition at line 816 of file Cartesian.hpp.
References a.
PETE_apply() [2/2]
template<class T > void PETE_apply (OpMeshExtrapolate< T > e, T & a, T b) inline
Definition at line 828 of file Cartesian.hpp.
References a, and Physics::e.