OPAL (Object Oriented Parallel Accelerator Library): BrickIterator< T, Dim > Class Template Reference
BrickIterator< T, Dim > Class Template Reference
#include <BrickIterator.h>
Public Types
typedef T PETE_Return_t
typedef BrickIterator< T, Dim > PETE_Expr_t
Public Member Functions
BrickIterator ()
BrickIterator (T *, const NDIndex< Dim > &, const NDIndex< Dim > &)
BrickIterator (T *, const vec< int, Dim > &)
BrickIterator & operator++ ()
bool whole () const
bool operator== (const BrickIterator< T, Dim > &a) const
bool operator!= (const BrickIterator< T, Dim > &a) const
T & operator* () const
void step (unsigned d)
void rewind (unsigned d)
T & offset (int i) const
T & offset (int i, int j) const
T & offset (int i, int j, int k) const
T & offset (int *i) const
T & unit_offset (int i) const
T & unit_offset (int i, int j) const
T & unit_offset (int i, int j, int k) const
void moveBy (int i)
void moveBy (int i, int j)
void moveBy (int i, int j, int k)
void moveBy (const int *i)
int Stride (int i) const
Message & putMessage (Message &, bool makecopy=true)
Message & getMessage (Message &)
PETE_Expr_t MakeExpression () const
Public Member Functions inherited from BrickCounter< Dim >
BrickCounter ()
BrickCounter (const NDIndex< Dim > &)
BrickCounter & operator++ ()
bool done (unsigned d) const
void step (unsigned d)
void rewind (unsigned d)
int size (unsigned d) const
int GetOffset (unsigned d) const
Protected Member Functions
void op_pp ()
Protected Member Functions inherited from BrickCounter< Dim >
void op_pp ()
Protected Attributes
T *__restrict__ Current
vec< int, Dim > Strides
bool Whole
Protected Attributes inherited from BrickCounter< Dim >
vec< int, Dim > Counters
vec< int, Dim > Counts
Detailed Description
template<class T, unsigned Dim>
class BrickIterator< T, Dim >
Definition at line 59 of file BrickIterator.h.
Member Typedef Documentation
PETE_Expr_t
template<class T, unsigned Dim> typedef BrickIterator<T,Dim> BrickIterator< T, Dim >::PETE_Expr_t
Definition at line 175 of file BrickIterator.h.
PETE_Return_t
template<class T, unsigned Dim> typedef T BrickIterator< T, Dim >::PETE_Return_t
Definition at line 174 of file BrickIterator.h.
Constructor & Destructor Documentation
BrickIterator() [1/3]
template<class T, unsigned Dim> BrickIterator< T, Dim >::BrickIterator () inline
Definition at line 64 of file BrickIterator.h.
BrickIterator() [2/3]
template<class T , unsigned Dim> BrickIterator< T, Dim >::BrickIterator (T * p, const NDIndex< Dim > & counted, const NDIndex< Dim > & domalloc)
Definition at line 68 of file BrickIterator.hpp.
References BrickIterator< T, Dim >::Current, Dim, Hypervolume::n, BrickIterator< T, Dim >::Strides, and BrickIterator< T, Dim >::Whole.
BrickIterator() [3/3]
template<class T , unsigned Dim> BrickIterator< T, Dim >::BrickIterator (T * p, const vec< int, Dim > & sizes)
Definition at line 90 of file BrickIterator.hpp.
References Dim, and Hypervolume::n.
Member Function Documentation
getMessage()
template<class T , unsigned Dim> Message & BrickIterator< T, Dim >::getMessage (Message & m)
Definition at line 190 of file BrickIterator.hpp.
References Message::MsgItem::data(), Dim, Message::get(), Message::item(), Hypervolume::n, PInsist, and Attrib::Legacy::Distribution::T.
Referenced by CompressedBrickIterator< T, Dim >::getMessage().
MakeExpression()
template<class T, unsigned Dim> PETE_Expr_t BrickIterator< T, Dim >::MakeExpression () const inline
Definition at line 176 of file BrickIterator.h.
moveBy() [1/4]
template<class T, unsigned Dim> void BrickIterator< T, Dim >::moveBy (int i) inline
Definition at line 135 of file BrickIterator.h.
References BrickIterator< T, Dim >::Current, and BrickIterator< T, Dim >::Strides.
Referenced by IntCICImpl< Dim >::gather(), IntCICImpl< 1U >::gather(), IntCICImpl< 2U >::gather(), IntCICImpl< 3U >::gather(), IntCICImpl< Dim >::scatter(), IntCICImpl< 1U >::scatter(), IntCICImpl< 2U >::scatter(), IntCICImpl< 3U >::scatter(), and BareFieldIterator< T, Dim >::SetCurrentLocation().
moveBy() [2/4]
template<class T, unsigned Dim> void BrickIterator< T, Dim >::moveBy (int i, int j) inline
Definition at line 140 of file BrickIterator.h.
References BrickIterator< T, Dim >::Current, and BrickIterator< T, Dim >::Strides.
moveBy() [3/4]
template<class T, unsigned Dim> void BrickIterator< T, Dim >::moveBy (int i, int j, int k) inline
Definition at line 146 of file BrickIterator.h.
References BrickIterator< T, Dim >::Current, and BrickIterator< T, Dim >::Strides.
moveBy() [4/4]
template<class T, unsigned Dim> void BrickIterator< T, Dim >::moveBy (const int * i) inline
Definition at line 153 of file BrickIterator.h.
References BrickIterator< T, Dim >::Current, Dim, and BrickIterator< T, Dim >::Strides.
offset() [1/4]
template<class T, unsigned Dim> T& BrickIterator< T, Dim >::offset (int i) const inline
Definition at line 107 of file BrickIterator.h.
References BrickIterator< T, Dim >::Current, and BrickIterator< T, Dim >::Strides.
Referenced by all_values_equal(), FieldDebugWriteb(), for_each(), IntSUDSImpl< 1U >::gather(), IntTSCImpl< 1U >::gather(), IntCICImpl< 1U >::gather(), IntSUDSImpl< 2U >::gather(), IntTSCImpl< 2U >::gather(), IntSUDSImpl< 3U >::gather(), IntCICImpl< 2U >::gather(), IntTSCImpl< 3U >::gather(), IntCICImpl< 3U >::gather(), IntSUDSImpl< 1U >::scatter(), IntCICImpl< 1U >::scatter(), IntTSCImpl< 1U >::scatter(), IntSUDSImpl< 2U >::scatter(), IntTSCImpl< 2U >::scatter(), IntCICImpl< 2U >::scatter(), IntSUDSImpl< 3U >::scatter(), IntTSCImpl< 3U >::scatter(), IntCICImpl< 3U >::scatter(), and SubFieldIter< T, Dim, SOffset< Dim > >::setLFieldData().
offset() [2/4]
template<class T, unsigned Dim> T& BrickIterator< T, Dim >::offset (int i, int j) const inline
Definition at line 111 of file BrickIterator.h.
References BrickIterator< T, Dim >::Current, and BrickIterator< T, Dim >::Strides.
offset() [3/4]
template<class T, unsigned Dim> T& BrickIterator< T, Dim >::offset (int i, int j, int k) const inline
Definition at line 115 of file BrickIterator.h.
References BrickIterator< T, Dim >::Current, and BrickIterator< T, Dim >::Strides.
offset() [4/4]
template<class T, unsigned Dim> T& BrickIterator< T, Dim >::offset (int * i) const inline
Definition at line 119 of file BrickIterator.h.
References BrickIterator< T, Dim >::Current, vec< T, Length >::dot(), and BrickIterator< T, Dim >::Strides.
op_pp()
template<class T , unsigned Dim> void BrickIterator< T, Dim >::op_pp () protected
Definition at line 111 of file BrickIterator.hpp.
References Dim.
Referenced by BrickIterator< T, Dim >::operator++().
operator!=()
template<class T, unsigned Dim> bool BrickIterator< T, Dim >::operator!= (const BrickIterator< T, Dim > & a) const inline
Definition at line 83 of file BrickIterator.h.
References a, and BrickIterator< T, Dim >::Current.
operator*()
template<class T, unsigned Dim> T& BrickIterator< T, Dim >::operator* () const inline
Definition at line 89 of file BrickIterator.h.
References BrickIterator< T, Dim >::Current.
Referenced by BareFieldIterator< T, Dim >::operator*().
operator++()
template<class T, unsigned Dim> BrickIterator& BrickIterator< T, Dim >::operator++ () inline
Definition at line 73 of file BrickIterator.h.
References BrickIterator< T, Dim >::op_pp().
Referenced by IndexedBareFieldIterator< T, Dim >::operator++(), and BareFieldIterator< T, Dim >::operator++().
operator==()
template<class T, unsigned Dim> bool BrickIterator< T, Dim >::operator== (const BrickIterator< T, Dim > & a) const inline
Definition at line 79 of file BrickIterator.h.
References a, and BrickIterator< T, Dim >::Current.
putMessage()
template<class T , unsigned Dim> Message & BrickIterator< T, Dim >::putMessage (Message & m, bool makecopy = true)
Definition at line 139 of file BrickIterator.hpp.
References Dim, Hypervolume::n, Message::put(), Message::putmsg(), Message::setCopy(), Message::setDelete(), and Attrib::Legacy::Distribution::T.
Referenced by CompressedBrickIterator< T, Dim >::putMessage().
rewind()
template<class T, unsigned Dim> void BrickIterator< T, Dim >::rewind (unsigned d) inline
Definition at line 100 of file BrickIterator.h.
References BrickIterator< T, Dim >::Current, BrickCounter< Dim >::rewind(), and BrickIterator< T, Dim >::Strides.
Referenced by for_each().
step()
template<class T, unsigned Dim> void BrickIterator< T, Dim >::step (unsigned d) inline
Definition at line 95 of file BrickIterator.h.
References BrickIterator< T, Dim >::Current, BrickCounter< Dim >::step(), and BrickIterator< T, Dim >::Strides.
Referenced by all_values_equal(), and for_each().
Stride()
template<class T, unsigned Dim> int BrickIterator< T, Dim >::Stride (int i) const inline
Definition at line 160 of file BrickIterator.h.
References BrickIterator< T, Dim >::Strides.
Referenced by for_each().
unit_offset() [1/3]
template<class T, unsigned Dim> T& BrickIterator< T, Dim >::unit_offset (int i) const inline
Definition at line 123 of file BrickIterator.h.
References BrickIterator< T, Dim >::Current.
Referenced by for_each().
unit_offset() [2/3]
template<class T, unsigned Dim> T& BrickIterator< T, Dim >::unit_offset (int i, int j) const inline
Definition at line 127 of file BrickIterator.h.
References BrickIterator< T, Dim >::Current, and BrickIterator< T, Dim >::Strides.
unit_offset() [3/3]
template<class T, unsigned Dim> T& BrickIterator< T, Dim >::unit_offset (int i, int j, int k) const inline
Definition at line 131 of file BrickIterator.h.
References BrickIterator< T, Dim >::Current, and BrickIterator< T, Dim >::Strides.
whole()
template<class T, unsigned Dim> bool BrickIterator< T, Dim >::whole () const inline
Definition at line 76 of file BrickIterator.h.
References BrickIterator< T, Dim >::Whole.
Referenced by DiscField< Dim >::write_offset_and_data().
Member Data Documentation
Current
template<class T, unsigned Dim> T* __restrict__ BrickIterator< T, Dim >::Current protected
Definition at line 180 of file BrickIterator.h.
Referenced by BrickIterator< T, Dim >::BrickIterator(), BrickIterator< T, Dim >::moveBy(), BrickIterator< T, Dim >::offset(), BrickIterator< T, Dim >::operator!=(), BrickIterator< T, Dim >::operator*(), BrickIterator< T, Dim >::operator==(), BrickIterator< T, Dim >::rewind(), BrickIterator< T, Dim >::step(), and BrickIterator< T, Dim >::unit_offset().
Strides
template<class T, unsigned Dim> vec<int,Dim> BrickIterator< T, Dim >::Strides protected
Definition at line 181 of file BrickIterator.h.
Referenced by BrickIterator< T, Dim >::BrickIterator(), BrickIterator< T, Dim >::moveBy(), BrickIterator< T, Dim >::offset(), BrickIterator< T, Dim >::rewind(), BrickIterator< T, Dim >::step(), BrickIterator< T, Dim >::Stride(), and BrickIterator< T, Dim >::unit_offset().
Whole
template<class T, unsigned Dim> bool BrickIterator< T, Dim >::Whole protected
Definition at line 182 of file BrickIterator.h.
Referenced by BrickIterator< T, Dim >::BrickIterator(), and BrickIterator< T, Dim >::whole().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BrickIterator.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BrickIterator.hpp