OPAL (Object Oriented Parallel Accelerator Library): Select Class Reference
Select Class Reference
#include <Select.h>
Public Member Functions
Select ()
Exemplar constructor.
virtual ~Select ()
virtual Select * clone (const std::string &name)
Make clone.
virtual void execute ()
Execute the command.
Public Member Functions inherited from Action
virtual ~Action ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
Select (const Select &)
void operator= (const Select &)
Select (const std::string &name, Select *parent)
void select (const Beamline &)
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Action
Action (int size, const char *name, const char *help)
Constructor for exemplars.
Action (const std::string &name, Action *parent)
Constructor for cloning.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 26 of file Select.h.
Constructor & Destructor Documentation
Select() [1/3]
Select::Select ()
Exemplar constructor.
Definition at line 46 of file Select.cpp.
References Object::itsAttr, Attrib::Distribution::LINE, Attributes::makeBool(), Attributes::makeRange(), Attributes::makeString(), Object::registerOwnership(), AttributeHandler::SUB_COMMAND, and Attrib::Distribution::TYPE.
Referenced by clone().
~Select()
Select::~Select () virtual
Definition at line 82 of file Select.cpp.
Select() [2/3]
Select::Select (const Select &) private
Select() [3/3]
Select::Select (const std::string & name, Select * parent) private
Definition at line 77 of file Select.cpp.
Member Function Documentation
clone()
Select * Select::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 86 of file Select.cpp.
References name, and Select().
execute()
void Select::execute () virtual
Execute the command.
Reimplemented from Object.
Definition at line 91 of file Select.cpp.
References Expressions::find(), OpalData::getInstance(), Attributes::getString(), Object::itsAttr, Attrib::Distribution::LINE, name, and select().
operator=()
void Select::operator= (const Select &) private
select()
void Select::select (const Beamline & bl) private
Definition at line 112 of file Select.cpp.
References endl(), Selector::execute(), DefaultVisitor::execute(), Attributes::getBool(), Selector::getCount(), Attributes::getRange(), Attributes::getString(), gmsg, Options::info, Object::itsAttr, level2(), and Attrib::Distribution::TYPE.
Referenced by execute().
The documentation for this class was generated from the following files:
src/BasicActions/Select.h
src/BasicActions/Select.cpp