OPAL (Object Oriented Parallel Accelerator Library): _FM3DMagnetoStaticH5Block Class Reference
_FM3DMagnetoStaticH5Block Class Reference
#include <FM3DMagnetoStaticH5Block.h>
Public Member Functions
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const
virtual ~_FM3DMagnetoStaticH5Block ()
Public Member Functions inherited from _FM3DH5BlockBase
virtual void getFieldDimensions (double &zBegin, double &zEnd) const
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const
virtual bool getFieldDerivative (const Vector_t &, Vector_t &, Vector_t &, const DiffDirection &) const
virtual void swap ()
virtual void getInfo (Inform *msg)
virtual void setFrequency (double freq)
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &F)
Public Member Functions inherited from _Fieldmap
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Private Member Functions
_FM3DMagnetoStaticH5Block (const std::string &filename)
virtual void readMap ()
virtual void freeMap ()
virtual double getFrequency () const
Static Private Member Functions
static FM3DMagnetoStaticH5Block create (const std::string &filename)
Private Attributes
std::vector< double > FieldstrengthBz_m
std::vector< double > FieldstrengthBx_m
std::vector< double > FieldstrengthBy_m
Friends
class _Fieldmap
class _FM3DH5BlockBase
Additional Inherited Members
Static Public Member Functions inherited from _Fieldmap
static Fieldmap getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Types inherited from _FM3DH5BlockBase
enum : unsigned short {
LX = 0, LY = 0, LZ = 0, HX = 4,
HY = 2, HZ = 1
}
Protected Member Functions inherited from _FM3DH5BlockBase
_FM3DH5BlockBase ()
virtual ~_FM3DH5BlockBase ()
void openFileMPIOCollective (const std::string &filename)
long long getNumSteps (void)
void setStep (const long long)
void getFieldInfo (const char *)
void getResonanceFrequency (void)
void readField (const char *name, double *x, double *y, double *z)
void closeFile (void)
virtual bool isInside (const Vector_t &r) const
unsigned long getIndex (unsigned int i, unsigned int j, unsigned int k) const
IndexTriplet getIndex (const Vector_t &X) const
double getWeightedData (const std::vector< double > &data, const IndexTriplet &idx, unsigned short corner) const
Vector_t interpolateTrilinearly (const std::vector< double > &, const std::vector< double > &, const std::vector< double > &, const Vector_t &X) const
Protected Member Functions inherited from _Fieldmap
_Fieldmap ()=delete
_Fieldmap (const std::string &filename)
virtual ~_Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions inherited from _Fieldmap
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes inherited from _FM3DH5BlockBase
h5_file_t file_m
std::vector< double > FieldstrengthEz_m
std::vector< double > FieldstrengthEx_m
std::vector< double > FieldstrengthEy_m
double xbegin_m
double xend_m
double ybegin_m
double yend_m
double zbegin_m
double zend_m
double hx_m
double hy_m
double hz_m
unsigned int num_gridpx_m
unsigned int num_gridpy_m
unsigned int num_gridpz_m
double frequency_m
bool swap_m
Protected Attributes inherited from _Fieldmap
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Detailed Description
Definition at line 26 of file FM3DMagnetoStaticH5Block.h.
Constructor & Destructor Documentation
~_FM3DMagnetoStaticH5Block()
_FM3DMagnetoStaticH5Block::~_FM3DMagnetoStaticH5Block () virtual
Definition at line 33 of file FM3DMagnetoStaticH5Block.cpp.
References freeMap().
_FM3DMagnetoStaticH5Block()
_FM3DMagnetoStaticH5Block::_FM3DMagnetoStaticH5Block (const std::string & filename) private
Definition at line 22 of file FM3DMagnetoStaticH5Block.cpp.
References _FM3DH5BlockBase::closeFile(), _FM3DH5BlockBase::getFieldInfo(), _FM3DH5BlockBase::getResonanceFrequency(), _FM3DH5BlockBase::openFileMPIOCollective(), T3DMagnetoStaticH5Block, and _Fieldmap::Type.
Referenced by create().
Member Function Documentation
create()
FM3DMagnetoStaticH5Block _FM3DMagnetoStaticH5Block::create (const std::string & filename) static private
Definition at line 37 of file FM3DMagnetoStaticH5Block.cpp.
References _FM3DMagnetoStaticH5Block().
Referenced by _Fieldmap::getFieldmap().
freeMap()
void _FM3DMagnetoStaticH5Block::freeMap () private virtual
Reimplemented from _FM3DH5BlockBase.
Definition at line 76 of file FM3DMagnetoStaticH5Block.cpp.
References FieldstrengthBx_m, FieldstrengthBy_m, FieldstrengthBz_m, _FM3DH5BlockBase::FieldstrengthEx_m, _FM3DH5BlockBase::FieldstrengthEy_m, and _FM3DH5BlockBase::FieldstrengthEz_m.
Referenced by ~_FM3DMagnetoStaticH5Block().
getFieldstrength()
bool _FM3DMagnetoStaticH5Block::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const virtual
Implements _FM3DH5BlockBase.
Definition at line 89 of file FM3DMagnetoStaticH5Block.cpp.
References FieldstrengthBx_m, FieldstrengthBy_m, FieldstrengthBz_m, _FM3DH5BlockBase::FieldstrengthEx_m, _FM3DH5BlockBase::FieldstrengthEy_m, _FM3DH5BlockBase::FieldstrengthEz_m, _FM3DH5BlockBase::interpolateTrilinearly(), _FM3DH5BlockBase::isInside(), and Attrib::Distribution::R.
getFrequency()
double _FM3DMagnetoStaticH5Block::getFrequency () const private virtual
Reimplemented from _FM3DH5BlockBase.
Definition at line 105 of file FM3DMagnetoStaticH5Block.cpp.
readMap()
void _FM3DMagnetoStaticH5Block::readMap () private virtual
Reimplemented from _FM3DH5BlockBase.
Definition at line 42 of file FM3DMagnetoStaticH5Block.cpp.
References _FM3DH5BlockBase::closeFile(), endl(), FieldstrengthBx_m, FieldstrengthBy_m, FieldstrengthBz_m, _FM3DH5BlockBase::FieldstrengthEx_m, _FM3DH5BlockBase::FieldstrengthEy_m, _FM3DH5BlockBase::FieldstrengthEz_m, _Fieldmap::Filename_m, _FM3DH5BlockBase::getNumSteps(), INFOMSG, level3(), _FM3DH5BlockBase::num_gridpx_m, _FM3DH5BlockBase::num_gridpy_m, _FM3DH5BlockBase::num_gridpz_m, _FM3DH5BlockBase::openFileMPIOCollective(), _FM3DH5BlockBase::readField(), _FM3DH5BlockBase::setStep(), and _Fieldmap::typeset_msg().
Friends And Related Function Documentation
_Fieldmap
friend class _Fieldmap friend
Definition at line 54 of file FM3DMagnetoStaticH5Block.h.
_FM3DH5BlockBase
friend class _FM3DH5BlockBase friend
Definition at line 55 of file FM3DMagnetoStaticH5Block.h.
Member Data Documentation
FieldstrengthBx_m
std::vector<double> _FM3DMagnetoStaticH5Block::FieldstrengthBx_m private
3D array with Bx
Definition at line 51 of file FM3DMagnetoStaticH5Block.h.
Referenced by freeMap(), getFieldstrength(), and readMap().
FieldstrengthBy_m
std::vector<double> _FM3DMagnetoStaticH5Block::FieldstrengthBy_m private
3D array with By
Definition at line 52 of file FM3DMagnetoStaticH5Block.h.
Referenced by freeMap(), getFieldstrength(), and readMap().
FieldstrengthBz_m
std::vector<double> _FM3DMagnetoStaticH5Block::FieldstrengthBz_m private
3D array with Bz
Definition at line 50 of file FM3DMagnetoStaticH5Block.h.
Referenced by freeMap(), getFieldstrength(), and readMap().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/FM3DMagnetoStaticH5Block.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/FM3DMagnetoStaticH5Block.cpp