OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Classic/FixedAlgebra/LinearFun.h File Reference
LinearFun.h File Reference
#include <iosfwd>
#include "FixedAlgebra/LinearFun.hpp"
#include "FixedAlgebra/LinearMap.h"
Classes
class FVector< T, N >
A templated representation for vectors.
class LinearMap< T, N >
Linear map with values of type [b]T[/b] in [b]N[/b] variables.
class FMatrix< T, R, C >
A templated representation for matrices.
class LinearFun< T, N >
Linear function in N variables of type T.
Functions
template<class T , int N>
LinearFun< T, N > operator+ (const LinearFun< T, N > &, const LinearFun< T, N > &)
Add.
template<class T , int N>
LinearFun< T, N > operator- (const LinearFun< T, N > &, const LinearFun< T, N > &)
Subtract.
template<class T , int N>
LinearFun< T, N > operator+ (const LinearFun< T, N > &, const T &)
Add.
template<class T , int N>
LinearFun< T, N > operator- (const LinearFun< T, N > &, const T &)
Subtract.
template<class T , int N>
LinearFun< T, N > operator+ (const T &, const LinearFun< T, N > &)
Add.
template<class T , int N>
LinearFun< T, N > operator- (const T &, const LinearFun< T, N > &)
Subtract.
template<class T , int N>
LinearFun< T, N > operator* (const LinearFun< T, N > &, const LinearFun< T, N > &)
Multiply.
template<class T , int N>
LinearFun< T, N > operator/ (const LinearFun< T, N > &, const LinearFun< T, N > &)
Divide.
template<class T , int N>
LinearFun< T, N > operator* (const LinearFun< T, N > &, const T &)
Multiply.
template<class T , int N>
LinearFun< T, N > operator/ (const LinearFun< T, N > &, const T &)
Divide.
template<class T , int N>
LinearFun< T, N > operator* (const T &, const LinearFun< T, N > &)
Multiply.
template<class T , int N>
LinearFun< T, N > operator/ (const T &, const LinearFun< T, N > &)
Divide 1 / LinearFun.
template<class T , int N>
bool operator== (const T &, const LinearFun< T, N > &)
Equality.
template<class T , int N>
bool operator!= (const T &, const LinearFun< T, N > &)
Inequality.
template<class T , int N>
std::istream & operator>> (std::istream &is, LinearFun< T, N > &)
Extract LinearFun from stream [b]is[/b].
template<class T , int N>
std::ostream & operator<< (std::ostream &os, const LinearFun< T, N > &)
Insert LinearFun to stream [b]os[/b].
Function Documentation
operator!=()
template<class T , int N> bool operator!= (const T & , const LinearFun< T, N > &) inline
Inequality.
Definition at line 463 of file LinearFun.hpp.
operator*() [1/3]
template<class T , int N> LinearFun<T, N> operator* (const LinearFun< T, N > & , const LinearFun< T, N > &) inline
Multiply.
Definition at line 418 of file LinearFun.hpp.
References LinearFun< T, N >::multiply().
operator*() [2/3]
template<class T , int N> LinearFun<T, N> operator* (const LinearFun< T, N > & , const T &) inline
Multiply.
Definition at line 430 of file LinearFun.hpp.
operator*() [3/3]
template<class T , int N> LinearFun<T, N> operator* (const T & , const LinearFun< T, N > &) inline
Multiply.
Definition at line 444 of file LinearFun.hpp.
operator+() [1/3]
template<class T , int N> LinearFun<T, N> operator+ (const LinearFun< T, N > & , const LinearFun< T, N > &) inline
Add.
Definition at line 376 of file LinearFun.hpp.
operator+() [2/3]
template<class T , int N> LinearFun<T, N> operator+ (const LinearFun< T, N > & , const T &) inline
Add.
Definition at line 390 of file LinearFun.hpp.
operator+() [3/3]
template<class T , int N> LinearFun<T, N> operator+ (const T & , const LinearFun< T, N > &) inline
Add.
Definition at line 404 of file LinearFun.hpp.
operator-() [1/3]
template<class T , int N> LinearFun<T, N> operator- (const LinearFun< T, N > & , const LinearFun< T, N > &) inline
Subtract.
Definition at line 383 of file LinearFun.hpp.
operator-() [2/3]
template<class T , int N> LinearFun<T, N> operator- (const LinearFun< T, N > & , const T &) inline
Subtract.
Definition at line 397 of file LinearFun.hpp.
operator-() [3/3]
template<class T , int N> LinearFun<T, N> operator- (const T & , const LinearFun< T, N > &) inline
Subtract.
Definition at line 411 of file LinearFun.hpp.
operator/() [1/3]
template<class T , int N> LinearFun<T, N> operator/ (const LinearFun< T, N > & , const LinearFun< T, N > &) inline
Divide.
Definition at line 424 of file LinearFun.hpp.
References LinearFun< T, N >::inverse(), and LinearFun< T, N >::multiply().
operator/() [2/3]
template<class T , int N> LinearFun<T, N> operator/ (const LinearFun< T, N > & , const T &) inline
Divide.
Definition at line 437 of file LinearFun.hpp.
operator/() [3/3]
template<class T , int N> LinearFun<T, N> operator/ (const T & , const LinearFun< T, N > &) inline
Divide 1 / LinearFun.
Definition at line 451 of file LinearFun.hpp.
References LinearFun< T, N >::inverse().
operator<<()
template<class T , int N> std::ostream& operator<< (std::ostream & os, const LinearFun< T, N > &) inline
Insert LinearFun to stream [b]os[/b].
Definition at line 475 of file LinearFun.hpp.
operator==()
template<class T , int N> bool operator== (const T & , const LinearFun< T, N > &) inline
Equality.
Definition at line 457 of file LinearFun.hpp.
operator>>()
template<class T , int N> std::istream& operator>> (std::istream & is, LinearFun< T, N > &) inline
Extract LinearFun from stream [b]is[/b].
Definition at line 469 of file LinearFun.hpp.
References LinearFun< T, N >::get().