OPAL (Object Oriented Parallel Accelerator Library): Attributes::RealArray Class Reference
Attributes::RealArray Class Reference
Parser for an attribute of type real array.
#include <RealArray.h>
Public Member Functions
RealArray (const std::string &name, const std::string &help)
Constructor.
virtual ~RealArray ()
virtual const std::string & getType () const
Return attribute type string `‘real array’'.
virtual void parse (Attribute &, Statement &, bool) const
Parse the attribute.
virtual void parseComponent (Attribute &, Statement &, bool, int) const
Parse a component of the array.
Public Member Functions inherited from AttributeHandler
AttributeHandler (const std::string &name, const std::string &help, AttributeBase *def)
Constructor.
virtual ~AttributeHandler ()
virtual AttributeHandler * clone () const
Make clone.
virtual AttributeBase * getDefault () const
Return default value.
virtual const std::string & getHelp () const
Return help string.
virtual const std::string & getName () const
Return attribute name.
bool isDeferred () const
Return defer flag.
void setDeferred (bool)
Set or reset defer flag.
bool isReadOnly () const
Return read-only flag.
void setReadOnly (bool)
Set or reset read-only flag.
void setPredefinedValues (const std::set< std::string > &, const std::string &)
Add predefined strings values to the help.
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
RealArray ()
RealArray (const RealArray &)
void operator= (const RealArray &)
Additional Inherited Members
Public Types inherited from AttributeHandler
enum OwnerType {
ELEMENT, COMMAND, SUB_COMMAND, STATEMENT,
NONE
}
Static Public Member Functions inherited from AttributeHandler
static std::multimap< OwnerType, std::string > getOwner (const std::string &att)
static void addAttributeOwner (const std::string &owner, const OwnerType &type, const std::string &name)
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from AttributeHandler
const std::string itsName
Attribute name.
const std::string itsHelp
Help text.
Pointer< AttributeBase > itsDefault
Default value.
bool is_deferred
Defer flag.
bool is_readonly
Read-only flag.
Detailed Description
Parser for an attribute of type real array.
Definition at line 32 of file RealArray.h.
Constructor & Destructor Documentation
RealArray() [1/3]
Attributes::RealArray::RealArray (const std::string & name, const std::string & help)
Constructor.
Definition at line 37 of file RealArray.cpp.
~RealArray()
Attributes::RealArray::~RealArray () virtual
Definition at line 42 of file RealArray.cpp.
RealArray() [2/3]
Attributes::RealArray::RealArray () private
RealArray() [3/3]
Attributes::RealArray::RealArray (const RealArray &) private
Member Function Documentation
getType()
const std::string & Attributes::RealArray::getType () const virtual
Return attribute type string `‘real array’'.
Implements AttributeHandler.
Definition at line 46 of file RealArray.cpp.
operator=()
void Attributes::RealArray::operator= (const RealArray &) private
parse()
void Attributes::RealArray::parse (Attribute & attr, Statement & statement, bool eval) const virtual
Parse the attribute.
Implements AttributeHandler.
Definition at line 52 of file RealArray.cpp.
References Expressions::OArray< T >::evaluate(), AttributeHandler::is_deferred, Expressions::parseRealArray(), and Attribute::set().
parseComponent()
void Attributes::RealArray::parseComponent (Attribute & attr, Statement & stat, bool eval, int index) const virtual
Parse a component of the array.
Reimplemented from AttributeHandler.
Definition at line 68 of file RealArray.cpp.
References Attribute::getBase(), Expressions::parseReal(), Attribute::set(), and Expressions::ADeferred< T >::setComponent().
The documentation for this class was generated from the following files:
src/Attributes/RealArray.h
src/Attributes/RealArray.cpp