OPAL (Object Oriented Parallel Accelerator Library): BrickExpLoop< LHS, RHS, OP, Dim > Class Template Reference
BrickExpLoop< LHS, RHS, OP, Dim > Class Template Reference
#include <BrickExpression.hpp>
Static Public Member Functions
static void apply (LHS &__restrict__ Lhs, RHS &__restrict__ Rhs, OP Op)
Detailed Description
template<class LHS, class RHS, class OP, unsigned Dim>
class BrickExpLoop< LHS, RHS, OP, Dim >
Definition at line 21 of file BrickExpression.hpp.
Member Function Documentation
apply()
template<class LHS , class RHS , class OP , unsigned Dim> static void BrickExpLoop< LHS, RHS, OP, Dim >::apply (LHS &__restrict__ Lhs, RHS &__restrict__ Rhs, OP Op) inline static
Definition at line 25 of file BrickExpression.hpp.
References Dim, for_each(), and PETE_apply().
Referenced by BrickExpression< Dim, LHS, RHS, OP >::apply().
The documentation for this class was generated from the following file:
ippl/src/Field/BrickExpression.hpp