OPAL (Object Oriented Parallel Accelerator Library): Source Class Reference
Source Class Reference
#include <Source.h>
Public Member Functions
Source (const std::string &name)
Constructor with given name.
Source ()
Source (const Source &)
virtual ~Source ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to Source.
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void finalise () override
virtual bool bends () const override
virtual void goOnline (const double &kineticEnergy) override
virtual void goOffline () override
virtual ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
virtual int getRequiredNumberOfTimeSteps () const override
void setTransparent ()
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
virtual EMField & getField ()=0
Return field.
virtual const EMField & getField () const =0
Return field.
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void operator= (const Source &)
Private Attributes
double startField_m
double endField_m
bool isTransparent_m
std::unique_ptr< LossDataSink > lossDs_m
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 30 of file Source.h.
Constructor & Destructor Documentation
Source() [1/3]
Source::Source (const std::string & name) explicit
Constructor with given name.
Definition at line 44 of file Source.cpp.
Source() [2/3]
Source::Source ()
Definition at line 33 of file Source.cpp.
Source() [3/3]
Source::Source (const Source & right)
Definition at line 37 of file Source.cpp.
~Source()
Source::~Source () virtual
Definition at line 51 of file Source.cpp.
Member Function Documentation
accept()
void Source::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to Source.
Implements ElementBase.
Definition at line 54 of file Source.cpp.
References BeamlineVisitor::visitSource().
apply()
bool Source::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 58 of file Source.cpp.
References Physics::c, PartBunchBase< T, Dim >::dt, Util::getBeta(), PartBunchBase< T, Dim >::ID, isTransparent_m, lossDs_m, PartBunchBase< T, Dim >::M, Component::online_m, PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::Q, Attrib::Distribution::R, PartBunchBase< T, Dim >::R, and Component::RefPartBunch_m.
bends()
bool Source::bends () const override virtual
Implements Component.
Definition at line 95 of file Source.cpp.
finalise()
void Source::finalise () override virtual
Implements Component.
Definition at line 92 of file Source.cpp.
getDimensions()
void Source::getDimensions (double & zBegin, double & zEnd) const override virtual
Implements Component.
Definition at line 108 of file Source.cpp.
References endField_m, and startField_m.
getRequiredNumberOfTimeSteps()
int Source::getRequiredNumberOfTimeSteps () const inline override virtual
Reimplemented from ElementBase.
Definition at line 79 of file Source.h.
getType()
ElementType Source::getType () const override virtual
Get element type std::string.
Reimplemented from Component.
Definition at line 113 of file Source.cpp.
References SOURCE.
goOffline()
void Source::goOffline () override virtual
Reimplemented from Component.
Definition at line 103 of file Source.cpp.
References lossDs_m, and Component::online_m.
goOnline()
void Source::goOnline (const double & kineticEnergy) override virtual
Reimplemented from Component.
Definition at line 99 of file Source.cpp.
References Component::online_m.
initialise()
void Source::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Implements Component.
Definition at line 83 of file Source.cpp.
References Options::asciidump, ElementBase::getElementLength(), ElementBase::getOutputFN(), lossDs_m, and Component::RefPartBunch_m.
operator=()
void Source::operator= (const Source &) private
setTransparent()
void Source::setTransparent ()
Definition at line 117 of file Source.cpp.
References isTransparent_m.
Referenced by OpalSource::update().
Member Data Documentation
endField_m
double Source::endField_m private
Definition at line 68 of file Source.h.
Referenced by getDimensions().
isTransparent_m
bool Source::isTransparent_m private
Definition at line 70 of file Source.h.
Referenced by apply(), and setTransparent().
lossDs_m
std::unique_ptr<LossDataSink> Source::lossDs_m private
Handling for store the particle out of region
Definition at line 72 of file Source.h.
Referenced by apply(), goOffline(), and initialise().
startField_m
double Source::startField_m private
startingpoint of field, m
Definition at line 67 of file Source.h.
Referenced by getDimensions().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/Source.h
src/Classic/AbsBeamline/Source.cpp