OPAL (Object Oriented Parallel Accelerator Library): StepSizeConfig Class Reference
StepSizeConfig Class Reference
#include <StepSizeConfig.h>
Public Member Functions
StepSizeConfig ()
StepSizeConfig (const StepSizeConfig &right)
void operator= (const StepSizeConfig &)=delete
void push_back (double dt, double zstop, unsigned long numSteps)
void sortAscendingZStop ()
void resetIterator ()
bool reachedStart () const
bool reachedEnd () const
void clear ()
void reverseDirection ()
StepSizeConfig & advanceToPos (double spos)
StepSizeConfig & operator++ ()
StepSizeConfig & operator-- ()
void shiftZStopRight (double front)
void shiftZStopLeft (double back)
double getdT () const
double getZStop () const
unsigned long getNumSteps () const
unsigned long long getMaxSteps () const
unsigned long long getNumStepsFinestResolution () const
double getMinTimeStep () const
double getFinalZStop () const
void print (Inform &out) const
ValueRange< double > getPathLengthRange () const
Private Types
typedef std::tuple< double, double, unsigned long > entry_t
typedef std::list< entry_t > container_t
Private Attributes
container_t configurations_m
container_t::iterator it_m
Detailed Description
Definition at line 29 of file StepSizeConfig.h.
Member Typedef Documentation
container_t
typedef std::list<entry_t> StepSizeConfig::container_t private
Definition at line 82 of file StepSizeConfig.h.
entry_t
typedef std::tuple<double, double, unsigned long> StepSizeConfig::entry_t private
Definition at line 81 of file StepSizeConfig.h.
Constructor & Destructor Documentation
StepSizeConfig() [1/2]
StepSizeConfig::StepSizeConfig () inline
Definition at line 89 of file StepSizeConfig.h.
StepSizeConfig() [2/2]
StepSizeConfig::StepSizeConfig (const StepSizeConfig & right) inline
Definition at line 95 of file StepSizeConfig.h.
Member Function Documentation
advanceToPos()
StepSizeConfig & StepSizeConfig::advanceToPos (double spos)
Definition at line 43 of file StepSizeConfig.cpp.
References configurations_m, getZStop(), and it_m.
Referenced by ParallelTTracker::execute().
clear()
void StepSizeConfig::clear () inline
Definition at line 123 of file StepSizeConfig.h.
References configurations_m, and it_m.
getdT()
double StepSizeConfig::getdT () const
Definition at line 109 of file StepSizeConfig.cpp.
References reachedEnd().
Referenced by OrbitThreader::checkElementLengths(), ParallelTTracker::execute(), and ParallelTTracker::findStartPosition().
getFinalZStop()
double StepSizeConfig::getFinalZStop () const
Definition at line 175 of file StepSizeConfig.cpp.
References configurations_m.
Referenced by ParallelTTracker::writePhaseSpace().
getMaxSteps()
unsigned long long StepSizeConfig::getMaxSteps () const
Definition at line 136 of file StepSizeConfig.cpp.
References configurations_m.
Referenced by ParallelTTracker::execute().
getMinTimeStep()
double StepSizeConfig::getMinTimeStep () const
Definition at line 164 of file StepSizeConfig.cpp.
References configurations_m.
Referenced by ParallelTTracker::execute().
getNumSteps()
unsigned long StepSizeConfig::getNumSteps () const
Definition at line 127 of file StepSizeConfig.cpp.
References reachedEnd().
Referenced by ParallelTTracker::execute().
getNumStepsFinestResolution()
unsigned long long StepSizeConfig::getNumStepsFinestResolution () const
Definition at line 145 of file StepSizeConfig.cpp.
References ceil(), and configurations_m.
Referenced by OrbitThreader::OrbitThreader().
getPathLengthRange()
ValueRange< double > StepSizeConfig::getPathLengthRange () const
Definition at line 202 of file StepSizeConfig.cpp.
References configurations_m, and ValueRange< T >::enlargeIfOutside().
Referenced by OrbitThreader::OrbitThreader().
getZStop()
double StepSizeConfig::getZStop () const
Definition at line 118 of file StepSizeConfig.cpp.
References reachedEnd().
Referenced by advanceToPos(), OrbitThreader::checkElementLengths(), ParallelTTracker::execute(), and ParallelTTracker::findStartPosition().
operator++()
StepSizeConfig & StepSizeConfig::operator++ ()
Definition at line 51 of file StepSizeConfig.cpp.
References it_m, and reachedEnd().
operator--()
StepSizeConfig & StepSizeConfig::operator-- ()
Definition at line 62 of file StepSizeConfig.cpp.
References it_m, and reachedStart().
operator=()
void StepSizeConfig::operator= (const StepSizeConfig &) delete
print()
void StepSizeConfig::print (Inform & out) const
Definition at line 179 of file StepSizeConfig.cpp.
References configurations_m, endl(), and it_m.
push_back()
void StepSizeConfig::push_back (double dt, double zstop, unsigned long numSteps) inline
Definition at line 101 of file StepSizeConfig.h.
References configurations_m.
Referenced by ParallelTTracker::ParallelTTracker().
reachedEnd()
bool StepSizeConfig::reachedEnd () const inline
Definition at line 118 of file StepSizeConfig.h.
References configurations_m, and it_m.
Referenced by OrbitThreader::checkElementLengths(), ParallelTTracker::execute(), ParallelTTracker::findStartPosition(), getdT(), getNumSteps(), getZStop(), and operator++().
reachedStart()
bool StepSizeConfig::reachedStart () const inline
Definition at line 113 of file StepSizeConfig.h.
References configurations_m, and it_m.
Referenced by operator--().
resetIterator()
void StepSizeConfig::resetIterator () inline
Definition at line 108 of file StepSizeConfig.h.
References configurations_m, and it_m.
Referenced by ParallelTTracker::ParallelTTracker().
reverseDirection()
void StepSizeConfig::reverseDirection ()
Definition at line 36 of file StepSizeConfig.cpp.
References configurations_m, and it_m.
Referenced by ParallelTTracker::execute().
shiftZStopLeft()
void StepSizeConfig::shiftZStopLeft (double back)
Definition at line 91 of file StepSizeConfig.cpp.
References configurations_m.
Referenced by ParallelTTracker::findStartPosition().
shiftZStopRight()
void StepSizeConfig::shiftZStopRight (double front)
Definition at line 73 of file StepSizeConfig.cpp.
References configurations_m.
sortAscendingZStop()
void StepSizeConfig::sortAscendingZStop ()
Definition at line 28 of file StepSizeConfig.cpp.
References a, and configurations_m.
Referenced by ParallelTTracker::ParallelTTracker().
Member Data Documentation
configurations_m
container_t StepSizeConfig::configurations_m private
Definition at line 84 of file StepSizeConfig.h.
Referenced by advanceToPos(), clear(), getFinalZStop(), getMaxSteps(), getMinTimeStep(), getNumStepsFinestResolution(), getPathLengthRange(), print(), push_back(), reachedEnd(), reachedStart(), resetIterator(), reverseDirection(), shiftZStopLeft(), shiftZStopRight(), and sortAscendingZStop().
it_m
container_t::iterator StepSizeConfig::it_m private
Definition at line 85 of file StepSizeConfig.h.
Referenced by advanceToPos(), clear(), operator++(), operator--(), print(), reachedEnd(), reachedStart(), resetIterator(), and reverseDirection().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Algorithms/StepSizeConfig.h
/psi/home/gsell/data/src/OPAL/src/src/Algorithms/StepSizeConfig.cpp