OPAL (Object Oriented Parallel Accelerator Library): FieldLayoutUser Class Reference
FieldLayoutUser Class Reference abstract
#include <FieldLayoutUser.h>
Public Member Functions
FieldLayoutUser ()
virtual ~FieldLayoutUser ()
virtual void Repartition (UserList *)=0
Public Member Functions inherited from User
User ()
virtual ~User ()
ID_t get_Id () const
virtual void notifyUserOfDelete (UserList *)=0
Additional Inherited Members
Public Types inherited from User
typedef Unique::type ID_t
Protected Attributes inherited from User
ID_t Id
Detailed Description
Definition at line 27 of file FieldLayoutUser.h.
Constructor & Destructor Documentation
FieldLayoutUser()
FieldLayoutUser::FieldLayoutUser () inline
Definition at line 31 of file FieldLayoutUser.h.
~FieldLayoutUser()
virtual FieldLayoutUser::~FieldLayoutUser () inline virtual
Definition at line 34 of file FieldLayoutUser.h.
Member Function Documentation
Repartition()
virtual void FieldLayoutUser::Repartition (UserList *) pure virtual
Implemented in SIndex< Dim >, BareField< T, Dim >, BareField< Vektor< MFLOAT, Dim >, Dim >, BareField< T1, D >, RegionLayout< T, Dim, MeshType >, RegionLayout< T, Dim, Mesh >, ParticleSpatialLayout< T, Dim, Mesh, CachingPolicy >, ParticleSpatialLayout< T, Dim, Mesh >, ParticleInteractLayout< T, Dim, Mesh >, Field< T, Dim, M, C >, Field< double, 3, Mesh_t, Center_t >, Field< Vector_t, 3, Mesh_t, Center_t >, and ParticleCashedLayout< T, Dim, Mesh >.
Referenced by RegionLayout< T, Dim, Mesh >::make_rnodes(), Mesh< Dim >::notifyOfChange(), and FieldLayout< Dim >::Repartition().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/FieldLayout/FieldLayoutUser.h