OPAL (Object Oriented Parallel Accelerator Library): BrickExpression< Dim, LHS, RHS, OP > Class Template Reference
BrickExpression< Dim, LHS, RHS, OP > Class Template Reference
#include <BrickExpression.h>
Public Member Functions
BrickExpression (const LHS &l, const RHS &r)
BrickExpression (const LHS &l, const RHS &r, const OP &o)
virtual void apply ()
Private Attributes
LHS Lhs
RHS Rhs
OP Op
Detailed Description
template<unsigned Dim, class LHS, class RHS, class OP>
class BrickExpression< Dim, LHS, RHS, OP >
Definition at line 17 of file BrickExpression.h.
Constructor & Destructor Documentation
BrickExpression() [1/2]
template<unsigned Dim, class LHS, class RHS, class OP> BrickExpression< Dim, LHS, RHS, OP >::BrickExpression (const LHS & l, const RHS & r) inline
Definition at line 20 of file BrickExpression.h.
BrickExpression() [2/2]
template<unsigned Dim, class LHS, class RHS, class OP> BrickExpression< Dim, LHS, RHS, OP >::BrickExpression (const LHS & l, const RHS & r, const OP & o) inline
Definition at line 24 of file BrickExpression.h.
Member Function Documentation
apply()
template<unsigned Dim, class LHS , class RHS , class OP > void BrickExpression< Dim, LHS, RHS, OP >::apply () virtual
Definition at line 114 of file BrickExpression.hpp.
References BrickExpLoop< LHS, RHS, OP, Dim >::apply().
Referenced by ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), assign(), ComponentFunctionFaceBCApply(), ExtrapolateAndZeroFaceBCApply2(), ExtrapolateFaceBCApply2(), FunctionFaceBCApply(), InterpolationFaceBCApply(), PeriodicFaceBCApply(), UniformCartesian< Dim, MFLOAT >::storeSpacingFields(), and Cartesian< Dim, MFLOAT >::storeSpacingFields().
Member Data Documentation
Lhs
template<unsigned Dim, class LHS, class RHS, class OP> LHS BrickExpression< Dim, LHS, RHS, OP >::Lhs private
Definition at line 32 of file BrickExpression.h.
Op
template<unsigned Dim, class LHS, class RHS, class OP> OP BrickExpression< Dim, LHS, RHS, OP >::Op private
Definition at line 34 of file BrickExpression.h.
Rhs
template<unsigned Dim, class LHS, class RHS, class OP> RHS BrickExpression< Dim, LHS, RHS, OP >::Rhs private
Definition at line 33 of file BrickExpression.h.
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BrickExpression.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BrickExpression.hpp