OPAL (Object Oriented Parallel Accelerator Library): src/_PyOpal/PyParser.cpp File Reference
PyParser.cpp File Reference
#include <Python.h>
#include <structmember.h>
#include <boost/algorithm/string.hpp>
#include <vector>
#include <string>
#include <sstream>
#include <algorithm>
#include <iterator>
#include "Main.cpp"
#include "mpi.h"
#include "Parser/Parser.h"
#include "OpalParser/OpalParser.h"
Functions
PyObject * initialise_from_opal_file (PyObject *self, PyObject *args, PyObject *kwds)
PyObject * list_objects (PyObject *self, PyObject *args, PyObject *kwds)
PyMODINIT_FUNC PyInit_parser (void)
Variables
std::string initialise_from_opal_file_docstring
std::string list_objects_docstring = "List objects"
const char * module_docstring = "parser module parses the input"
Function Documentation
initialise_from_opal_file()
PyObject* initialise_from_opal_file (PyObject * self, PyObject * args, PyObject * kwds)
Definition at line 23 of file PyParser.cpp.
References opalMain().
list_objects()
PyObject* list_objects (PyObject * self, PyObject * args, PyObject * kwds)
Definition at line 51 of file PyParser.cpp.
References endl(), OpalData::getAllNames(), and OpalData::getInstance().
PyInit_parser()
PyMODINIT_FUNC PyInit_parser (void)
Definition at line 81 of file PyParser.cpp.
Variable Documentation
initialise_from_opal_file_docstring
std::string initialise_from_opal_file_docstring
Initial value:
=
std::string("Initialise from opal file\n")+
std::string("If you are getting an error message from openMPI, try\n")+
std::string("rebuilding the MPI library with --disable-dlopen switch\n")
Definition at line 17 of file PyParser.cpp.
list_objects_docstring
std::string list_objects_docstring = "List objects"
Definition at line 49 of file PyParser.cpp.
module_docstring
const char* module_docstring = "parser module parses the input"
Definition at line 59 of file PyParser.cpp.