OPAL (Object Oriented Parallel Accelerator Library): RangeRep Class Reference
RangeRep Class Reference
Representation of a range within a beam line or sequence.
#include <RangeRep.h>
Public Member Functions
RangeRep ()
Default constructor.
RangeRep (PlaceRep &f, PlaceRep &l)
Constructor from two given places.
RangeRep (const RangeRep &)
~RangeRep ()
const RangeRep & operator= (const RangeRep &)
void initialize ()
Initialise data for search.
bool isActive () const
Test for active range.
void enter (const FlaggedElmPtr &) const
Enter an element or line.
void leave (const FlaggedElmPtr &) const
Leave an element or line.
void print (std::ostream &os) const
Print in input format.
Private Attributes
PlaceRep first
PlaceRep last
bool fullRange
bool status
Detailed Description
Representation of a range within a beam line or sequence.
Definition at line 34 of file RangeRep.h.
Constructor & Destructor Documentation
RangeRep() [1/3]
RangeRep::RangeRep ()
Default constructor.
Definition at line 27 of file RangeRep.cpp.
RangeRep() [2/3]
RangeRep::RangeRep (PlaceRep & f, PlaceRep & l)
Constructor from two given places.
Definition at line 37 of file RangeRep.cpp.
RangeRep() [3/3]
RangeRep::RangeRep (const RangeRep & rep)
Definition at line 32 of file RangeRep.cpp.
~RangeRep()
RangeRep::~RangeRep ()
Definition at line 42 of file RangeRep.cpp.
Member Function Documentation
enter()
void RangeRep::enter (const FlaggedElmPtr & fep) const
Enter an element or line.
Definition at line 70 of file RangeRep.cpp.
References PlaceRep::enter(), first, fullRange, PlaceRep::isActive(), last, and status.
Referenced by RangeSelector::visitFlaggedElmPtr().
initialize()
void RangeRep::initialize ()
Initialise data for search.
Definition at line 54 of file RangeRep.cpp.
References first, fullRange, PlaceRep::initialize(), last, and status.
Referenced by RangeSelector::execute().
isActive()
bool RangeRep::isActive () const
Test for active range.
Definition at line 65 of file RangeRep.cpp.
References status.
Referenced by Selector::handleElement(), and RangeSelector::handleElement().
leave()
void RangeRep::leave (const FlaggedElmPtr & fep) const
Leave an element or line.
Definition at line 80 of file RangeRep.cpp.
References first, fullRange, PlaceRep::isActive(), last, PlaceRep::leave(), and status.
Referenced by RangeSelector::visitFlaggedElmPtr().
operator=()
const RangeRep & RangeRep::operator= (const RangeRep & rep)
Definition at line 46 of file RangeRep.cpp.
References first, fullRange, and last.
print()
void RangeRep::print (std::ostream & os) const
Print in input format.
Definition at line 90 of file RangeRep.cpp.
References first, fullRange, last, and PlaceRep::print().
Referenced by operator<<().
Member Data Documentation
first
PlaceRep RangeRep::first private
Definition at line 71 of file RangeRep.h.
Referenced by enter(), initialize(), leave(), operator=(), and print().
fullRange
bool RangeRep::fullRange private
Definition at line 75 of file RangeRep.h.
Referenced by enter(), initialize(), leave(), operator=(), and print().
last
PlaceRep RangeRep::last private
Definition at line 72 of file RangeRep.h.
Referenced by enter(), initialize(), leave(), operator=(), and print().
status
bool RangeRep::status mutable private
Definition at line 78 of file RangeRep.h.
Referenced by enter(), initialize(), isActive(), and leave().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/AbstractObjects/RangeRep.h
/psi/home/gsell/data/src/OPAL/src/src/AbstractObjects/RangeRep.cpp