OPAL (Object Oriented Parallel Accelerator Library): SimulatedBinaryCrossover< T > Struct Template Reference
SimulatedBinaryCrossover< T > Struct Template Reference
#include <SimulatedBinaryCrossover.h>
Public Member Functions
void crossover (boost::shared_ptr< T > ind1, boost::shared_ptr< T > ind2, CmdArguments_t args)
Detailed Description
template<class T>
struct SimulatedBinaryCrossover< T >
Definition at line 30 of file SimulatedBinaryCrossover.h.
Member Function Documentation
crossover()
template<class T > void SimulatedBinaryCrossover< T >::crossover (boost::shared_ptr< T > ind1, boost::shared_ptr< T > ind2, CmdArguments_t args) inline
Definition at line 32 of file SimulatedBinaryCrossover.h.
References max(), min(), and pow().
The documentation for this struct was generated from the following file:
optimizer/Optimizer/EA/SimulatedBinaryCrossover.h