OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Particle/ParticleBalancer.h File Reference
ParticleBalancer.h File Reference
#include "Particle/ParticleBalancer.hpp"
Classes
class ParticleSpatialLayout< T, Dim, Mesh, CachingPolicy >
class ParticleUniformLayout< T, Dim >
class IpplParticleBase< PLayout >
Functions
template<class T , unsigned Dim, class Mesh , class CachingPolicy >
bool BinaryRepartition (IpplParticleBase< ParticleSpatialLayout< T, Dim, Mesh, CachingPolicy > > &, double=0.0)
template<class T , unsigned Dim>
bool BinaryRepartition (IpplParticleBase< ParticleUniformLayout< T, Dim > > &, double=0.0)
Function Documentation
BinaryRepartition() [1/2]
template<class T , unsigned Dim, class Mesh , class CachingPolicy > bool BinaryRepartition (IpplParticleBase< ParticleSpatialLayout< T, Dim, Mesh, CachingPolicy > > & , double = 0.0)
Definition at line 46 of file ParticleBalancer.hpp.
References IpplInfo::abort(), CalcBinaryRepartition(), Dim, endl(), ERRORMSG, FieldLayout< Dim >::getDomain(), RegionLayout< T, Dim, MeshType >::getFieldLayout(), RegionLayout< T, Dim, MeshType >::getMesh(), RegionLayout< T, Dim, MeshType >::initialized(), RegionLayout< T, Dim, MeshType >::RepartitionLayout(), and scatter().
BinaryRepartition() [2/2]
template<class T , unsigned Dim> bool BinaryRepartition (IpplParticleBase< ParticleUniformLayout< T, Dim > > & , double = 0.0)
Definition at line 144 of file ParticleBalancer.hpp.