OPAL (Object Oriented Parallel Accelerator Library): RelativeFFTLowPassFilter Class Reference
RelativeFFTLowPassFilter Class Reference
#include <RelativeFFTLowPass.h>
Public Member Functions
RelativeFFTLowPassFilter (const double &threshold)
void apply (std::vector< double > &LineDensity)
void calc_derivative (std::vector< double > &histogram, const double &h)
Public Member Functions inherited from Filter
Filter ()
virtual ~Filter ()
Private Attributes
double threshold_m
Detailed Description
Definition at line 6 of file RelativeFFTLowPass.h.
Constructor & Destructor Documentation
RelativeFFTLowPassFilter()
RelativeFFTLowPassFilter::RelativeFFTLowPassFilter (const double & threshold)
Definition at line 8 of file RelativeFFTLowPass.cpp.
Member Function Documentation
apply()
void RelativeFFTLowPassFilter::apply (std::vector< double > & LineDensity) virtual
Implements Filter.
Definition at line 12 of file RelativeFFTLowPass.cpp.
References abs(), real(), and threshold_m.
calc_derivative()
void RelativeFFTLowPassFilter::calc_derivative (std::vector< double > & histogram, const double & h) virtual
Implements Filter.
Definition at line 54 of file RelativeFFTLowPass.cpp.
References abs(), Physics::pi, real(), and threshold_m.
Member Data Documentation
threshold_m
double RelativeFFTLowPassFilter::threshold_m private
Definition at line 13 of file RelativeFFTLowPass.h.
Referenced by apply(), and calc_derivative().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Filters/RelativeFFTLowPass.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Filters/RelativeFFTLowPass.cpp