OPAL (Object Oriented Parallel Accelerator Library): Cartesian< Dim, MFLOAT > Class Template Reference
Cartesian< Dim, MFLOAT > Class Template Reference
#include <Cartesian.h>
Public Types
typedef Cell DefaultCentering
typedef MFLOAT MeshValue_t
typedef Vektor< MFLOAT, Dim > MeshVektor_t
Public Types inherited from Mesh< Dim >
enum { Dimension = Dim }
typedef UserList::ID_t ID_t
typedef iterator_user iterator_if
typedef size_type_user size_type_if
Public Member Functions
Cartesian ()
~Cartesian ()
Cartesian (const NDIndex< Dim > &ndi)
Cartesian (const Index &I)
Cartesian (const Index &I, const Index &J)
Cartesian (const Index &I, const Index &J, const Index &K)
Cartesian (const NDIndex< Dim > &ndi, MFLOAT **const delX)
Cartesian (const Index &I, MFLOAT **const delX)
Cartesian (const Index &I, const Index &J, MFLOAT **const delX)
Cartesian (const Index &I, const Index &J, const Index &K, MFLOAT **const delX)
Cartesian (const NDIndex< Dim > &ndi, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig)
Cartesian (const Index &I, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig)
Cartesian (const Index &I, const Index &J, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig)
Cartesian (const Index &I, const Index &J, const Index &K, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig)
Cartesian (const NDIndex< Dim > &ndi, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig, MeshBC_E *const mbc)
Cartesian (const Index &I, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig, MeshBC_E *const mbc)
Cartesian (const Index &I, const Index &J, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig, MeshBC_E *const mbc)
Cartesian (const Index &I, const Index &J, const Index &K, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig, MeshBC_E *const mbc)
void initialize (const NDIndex< Dim > &ndi)
void initialize (const Index &I)
void initialize (const Index &I, const Index &J)
void initialize (const Index &I, const Index &J, const Index &K)
void initialize (const NDIndex< Dim > &ndi, MFLOAT **const delX)
void initialize (const Index &I, MFLOAT **const delX)
void initialize (const Index &I, const Index &J, MFLOAT **const delX)
void initialize (const Index &I, const Index &J, const Index &K, MFLOAT **const delX)
void initialize (const NDIndex< Dim > &ndi, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig)
void initialize (const Index &I, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig)
void initialize (const Index &I, const Index &J, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig)
void initialize (const Index &I, const Index &J, const Index &K, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig)
void initialize (const NDIndex< Dim > &ndi, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig, MeshBC_E *const mbc)
void initialize (const Index &I, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig, MeshBC_E *const mbc)
void initialize (const Index &I, const Index &J, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig, MeshBC_E *const mbc)
void initialize (const Index &I, const Index &J, const Index &K, MFLOAT **const delX, const Vektor< MFLOAT, Dim > &orig, MeshBC_E *const mbc)
void storeSpacingFields ()
void storeSpacingFields (e_dim_tag p1, int vnodes=-1)
void storeSpacingFields (e_dim_tag p1, e_dim_tag p2, int vnodes=-1)
void storeSpacingFields (e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, int vnodes=-1)
void storeSpacingFields (e_dim_tag *p, int vnodes=-1)
void storeSpacingFields (e_dim_tag p1, unsigned vnodes1, bool recurse=false, int vnodes=-1)
void storeSpacingFields (e_dim_tag p1, e_dim_tag p2, unsigned vnodes1, unsigned vnodes2, bool recurse=false, int vnodes=-1)
void storeSpacingFields (e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, bool recurse=false, int vnodes=-1)
void storeSpacingFields (e_dim_tag *p, unsigned *vnodesPerDirection, bool recurse=false, int vnodes=-1)
Vektor< MFLOAT, Dim > get_origin () const
void get_meshSpacing (unsigned d, MFLOAT *spacings) const
MeshBC_E get_MeshBC (unsigned face) const
MeshBC_E * get_MeshBC () const
void set_origin (const Vektor< MFLOAT, Dim > &o)
void set_meshSpacing (MFLOAT **const del)
void set_MeshBC (unsigned face, MeshBC_E meshBCType)
void set_MeshBC (MeshBC_E *meshBCTypes)
void print (std::ostream &)
MFLOAT getCellVolume (const NDIndex< Dim > &) const
Field< MFLOAT, Dim, Cartesian< Dim, MFLOAT >, Cell > & getCellVolumeField (Field< MFLOAT, Dim, Cartesian< Dim, MFLOAT >, Cell > &) const
MFLOAT getVertRangeVolume (const NDIndex< Dim > &) const
MFLOAT getCellRangeVolume (const NDIndex< Dim > &) const
NDIndex< Dim > getNearestVertex (const Vektor< MFLOAT, Dim > &) const
NDIndex< Dim > getVertexBelow (const Vektor< MFLOAT, Dim > &) const
NDIndex< Dim > getCellContaining (const Vektor< MFLOAT, Dim > &x) const
Vektor< MFLOAT, Dim > getVertexPosition (const NDIndex< Dim > &) const
Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Vert > & getVertexPositionField (Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Vert > &) const
Vektor< MFLOAT, Dim > getCellPosition (const NDIndex< Dim > &) const
Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Cell > & getCellPositionField (Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Cell > &) const
Vektor< MFLOAT, Dim > getDeltaVertex (const NDIndex< Dim > &) const
Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Cell > & getDeltaVertexField (Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Cell > &) const
Vektor< MFLOAT, Dim > getDeltaCell (const NDIndex< Dim > &) const
Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Vert > & getDeltaCellField (Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Vert > &) const
Vektor< MFLOAT, Dim > * getSurfaceNormals (const NDIndex< Dim > &) const
void getSurfaceNormalFields (Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Cell > **) const
Vektor< MFLOAT, Dim > getSurfaceNormal (const NDIndex< Dim > &, unsigned) const
Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Cell > & getSurfaceNormalField (Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Cell > &, unsigned) const
Public Member Functions inherited from Mesh< Dim >
Mesh ()
virtual ~Mesh ()
ID_t get_Id () const
void checkin (FieldLayoutUser &f)
void checkout (FieldLayoutUser &f)
size_type_if size_if () const
iterator_if begin_if ()
iterator_if end_if ()
void notifyOfChange ()
Public Attributes
unsigned gridSizes [Dim]
Vektor< MFLOAT, Dim > Dvc [1<< Dim]
bool hasSpacingFields
BareField< Vektor< MFLOAT, Dim >, Dim > * VertSpacings
BareField< Vektor< MFLOAT, Dim >, Dim > * CellSpacings
Private Member Functions
void updateMeshSpacingGuards (int face)
void setup ()
void set_Dvc ()
Private Attributes
std::map< int, MFLOAT > meshSpacing [Dim]
std::map< int, MFLOAT > meshPosition [Dim]
Vektor< MFLOAT, Dim > origin
MeshBC_E MeshBC [2 *Dim]
FieldLayout< Dim > * FlCell
FieldLayout< Dim > * FlVert
Additional Inherited Members
Static Public Attributes inherited from Mesh< Dim >
static std::string MeshBC_E_Names [3] = {"Reflective","Periodic ","No BC "}
Detailed Description
template<unsigned Dim, class MFLOAT = double>
class Cartesian< Dim, MFLOAT >
Definition at line 28 of file Cartesian.h.
Member Typedef Documentation
DefaultCentering
template<unsigned Dim, class MFLOAT = double> typedef Cell Cartesian< Dim, MFLOAT >::DefaultCentering
Definition at line 37 of file Cartesian.h.
MeshValue_t
template<unsigned Dim, class MFLOAT = double> typedef MFLOAT Cartesian< Dim, MFLOAT >::MeshValue_t
Definition at line 38 of file Cartesian.h.
MeshVektor_t
template<unsigned Dim, class MFLOAT = double> typedef Vektor<MFLOAT,Dim> Cartesian< Dim, MFLOAT >::MeshVektor_t
Definition at line 39 of file Cartesian.h.
Constructor & Destructor Documentation
Cartesian() [1/17]
template<unsigned Dim, class MFLOAT = double> Cartesian< Dim, MFLOAT >::Cartesian () inline
Definition at line 42 of file Cartesian.h.
References Cartesian< Dim, MFLOAT >::hasSpacingFields.
~Cartesian()
template<unsigned Dim, class MFLOAT = double> Cartesian< Dim, MFLOAT >::~Cartesian () inline
Definition at line 47 of file Cartesian.h.
References Cartesian< Dim, MFLOAT >::CellSpacings, Cartesian< Dim, MFLOAT >::FlCell, Cartesian< Dim, MFLOAT >::FlVert, Cartesian< Dim, MFLOAT >::hasSpacingFields, and Cartesian< Dim, MFLOAT >::VertSpacings.
Cartesian() [2/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const NDIndex< Dim > & ndi)
Definition at line 56 of file Cartesian.hpp.
References Dim, and Reflective.
Cartesian() [3/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const Index & I)
Definition at line 132 of file Cartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, Reflective, and Index::stride().
Cartesian() [4/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const Index & I, const Index & J)
Definition at line 202 of file Cartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, Reflective, and Index::stride().
Cartesian() [5/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const Index & I, const Index & J, const Index & K)
Definition at line 283 of file Cartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, Reflective, and Index::stride().
Cartesian() [6/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const NDIndex< Dim > & ndi, MFLOAT **const delX)
Definition at line 78 of file Cartesian.hpp.
References Dim, and Reflective.
Cartesian() [7/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const Index & I, MFLOAT **const delX)
Definition at line 154 of file Cartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, and Reflective.
Cartesian() [8/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const Index & I, const Index & J, MFLOAT **const delX)
Definition at line 231 of file Cartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, and Reflective.
Cartesian() [9/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const Index & I, const Index & J, const Index & K, MFLOAT **const delX)
Definition at line 321 of file Cartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, and Reflective.
Cartesian() [10/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const NDIndex< Dim > & ndi, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 95 of file Cartesian.hpp.
References Dim, and Reflective.
Cartesian() [11/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const Index & I, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 170 of file Cartesian.hpp.
References Dim, Index::length(), PInsist, and Reflective.
Cartesian() [12/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const Index & I, const Index & J, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 249 of file Cartesian.hpp.
References Dim, Index::length(), PInsist, and Reflective.
Cartesian() [13/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const Index & I, const Index & J, const Index & K, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 342 of file Cartesian.hpp.
References Dim, Index::length(), PInsist, and Reflective.
Cartesian() [14/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const NDIndex< Dim > & ndi, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig, MeshBC_E *const mbc)
Definition at line 113 of file Cartesian.hpp.
References Dim.
Cartesian() [15/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const Index & I, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig, MeshBC_E *const mbc)
Definition at line 187 of file Cartesian.hpp.
References Dim, Index::length(), and PInsist.
Cartesian() [16/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const Index & I, const Index & J, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig, MeshBC_E *const mbc)
Definition at line 267 of file Cartesian.hpp.
References Dim, Index::length(), and PInsist.
Cartesian() [17/17]
template<unsigned Dim, class MFLOAT > Cartesian< Dim, MFLOAT >::Cartesian (const Index & I, const Index & J, const Index & K, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig, MeshBC_E *const mbc)
Definition at line 361 of file Cartesian.hpp.
References Dim, Index::length(), and PInsist.
Member Function Documentation
get_MeshBC() [1/2]
template<unsigned Dim, class MFLOAT > MeshBC_E Cartesian< Dim, MFLOAT >::get_MeshBC (unsigned face) const
Definition at line 2159 of file Cartesian.hpp.
get_MeshBC() [2/2]
template<unsigned Dim, class MFLOAT > MeshBC_E * Cartesian< Dim, MFLOAT >::get_MeshBC () const
Definition at line 2169 of file Cartesian.hpp.
References Dim.
get_meshSpacing()
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::get_meshSpacing (unsigned d, MFLOAT * spacings) const
Definition at line 787 of file Cartesian.hpp.
References Dim, Expressions::find(), and PAssert_LT.
get_origin()
template<unsigned Dim, class MFLOAT > Vektor< MFLOAT, Dim > Cartesian< Dim, MFLOAT >::get_origin () const
Definition at line 740 of file Cartesian.hpp.
getCellContaining()
template<unsigned Dim, class MFLOAT = double> NDIndex<Dim> Cartesian< Dim, MFLOAT >::getCellContaining (const Vektor< MFLOAT, Dim > & x) const inline
Definition at line 224 of file Cartesian.h.
References Cartesian< Dim, MFLOAT >::getVertexBelow().
getCellPosition()
template<unsigned Dim, class MFLOAT > Vektor< MFLOAT, Dim > Cartesian< Dim, MFLOAT >::getCellPosition (const NDIndex< Dim > & ndi) const
Definition at line 1778 of file Cartesian.hpp.
References Dim, endl(), and ERRORMSG.
getCellPositionField()
template<unsigned Dim, class MFLOAT > Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Cell > & Cartesian< Dim, MFLOAT >::getCellPositionField (Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Cell > & cellPositions) const
Definition at line 1802 of file Cartesian.hpp.
References BareField< T, Dim >::begin(), and Dim.
getCellRangeVolume()
template<unsigned Dim, class MFLOAT > MFLOAT Cartesian< Dim, MFLOAT >::getCellRangeVolume (const NDIndex< Dim > & ndi) const
Definition at line 1573 of file Cartesian.hpp.
References abs(), Dim, endl(), and ERRORMSG.
getCellVolume()
template<unsigned Dim, class MFLOAT > MFLOAT Cartesian< Dim, MFLOAT >::getCellVolume (const NDIndex< Dim > & ndi) const
Definition at line 1503 of file Cartesian.hpp.
References Dim, endl(), and ERRORMSG.
getCellVolumeField()
template<unsigned Dim, class MFLOAT > Field< MFLOAT, Dim, Cartesian< Dim, MFLOAT >, Cell > & Cartesian< Dim, MFLOAT >::getCellVolumeField (Field< MFLOAT, Dim, Cartesian< Dim, MFLOAT >, Cell > & volumes) const
Definition at line 1520 of file Cartesian.hpp.
References BareField< T, Dim >::begin(), Dim, and Expressions::find().
getDeltaCell()
template<unsigned Dim, class MFLOAT > Vektor< MFLOAT, Dim > Cartesian< Dim, MFLOAT >::getDeltaCell (const NDIndex< Dim > & ndi) const
Definition at line 1882 of file Cartesian.hpp.
References a, Dim, endl(), and ERRORMSG.
getDeltaCellField()
template<unsigned Dim, class MFLOAT > Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Vert > & Cartesian< Dim, MFLOAT >::getDeltaCellField (Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Vert > & cellSpacings) const
Definition at line 1917 of file Cartesian.hpp.
References BareField< T, Dim >::begin(), Dim, and Expressions::find().
getDeltaVertex()
template<unsigned Dim, class MFLOAT > Vektor< MFLOAT, Dim > Cartesian< Dim, MFLOAT >::getDeltaVertex (const NDIndex< Dim > & ndi) const
Definition at line 1827 of file Cartesian.hpp.
References a, Dim, endl(), and ERRORMSG.
getDeltaVertexField()
template<unsigned Dim, class MFLOAT > Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Cell > & Cartesian< Dim, MFLOAT >::getDeltaVertexField (Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Cell > & vertexSpacings) const
Definition at line 1861 of file Cartesian.hpp.
References BareField< T, Dim >::begin(), Dim, and Expressions::find().
getNearestVertex()
template<unsigned Dim, class MFLOAT > NDIndex< Dim > Cartesian< Dim, MFLOAT >::getNearestVertex (const Vektor< MFLOAT, Dim > & x) const
Definition at line 1604 of file Cartesian.hpp.
References Dim, endl(), and ERRORMSG.
getSurfaceNormal()
template<unsigned Dim, class MFLOAT > Vektor< MFLOAT, Dim > Cartesian< Dim, MFLOAT >::getSurfaceNormal (const NDIndex< Dim > & , unsigned face) const
Definition at line 1982 of file Cartesian.hpp.
References Dim.
getSurfaceNormalField()
template<unsigned Dim, class MFLOAT > Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Cell > & Cartesian< Dim, MFLOAT >::getSurfaceNormalField (Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Cell > & surfaceNormalField, unsigned face) const
Definition at line 2013 of file Cartesian.hpp.
References Dim.
getSurfaceNormalFields()
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::getSurfaceNormalFields (Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Cell > ** surfaceNormalsFields) const
Definition at line 1956 of file Cartesian.hpp.
References assign(), and Dim.
getSurfaceNormals()
template<unsigned Dim, class MFLOAT > Vektor< MFLOAT, Dim > * Cartesian< Dim, MFLOAT >::getSurfaceNormals (const NDIndex< Dim > &) const
Definition at line 1938 of file Cartesian.hpp.
References Dim.
getVertexBelow()
template<unsigned Dim, class MFLOAT > NDIndex< Dim > Cartesian< Dim, MFLOAT >::getVertexBelow (const Vektor< MFLOAT, Dim > & x) const
Definition at line 1671 of file Cartesian.hpp.
References Dim, endl(), and ERRORMSG.
Referenced by Cartesian< Dim, MFLOAT >::getCellContaining().
getVertexPosition()
template<unsigned Dim, class MFLOAT > Vektor< MFLOAT, Dim > Cartesian< Dim, MFLOAT >::getVertexPosition (const NDIndex< Dim > & ndi) const
Definition at line 1732 of file Cartesian.hpp.
References Dim, endl(), and ERRORMSG.
getVertexPositionField()
template<unsigned Dim, class MFLOAT > Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Vert > & Cartesian< Dim, MFLOAT >::getVertexPositionField (Field< Vektor< MFLOAT, Dim >, Dim, Cartesian< Dim, MFLOAT >, Vert > & vertexPositions) const
Definition at line 1755 of file Cartesian.hpp.
References BareField< T, Dim >::begin(), and Dim.
getVertRangeVolume()
template<unsigned Dim, class MFLOAT > MFLOAT Cartesian< Dim, MFLOAT >::getVertRangeVolume (const NDIndex< Dim > & ndi) const
Definition at line 1542 of file Cartesian.hpp.
References abs(), Dim, endl(), and ERRORMSG.
initialize() [1/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const NDIndex< Dim > & ndi)
Definition at line 382 of file Cartesian.hpp.
References Dim, and Reflective.
initialize() [2/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const Index & I)
Definition at line 462 of file Cartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, Reflective, and Index::stride().
initialize() [3/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const Index & I, const Index & J)
Definition at line 536 of file Cartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, Reflective, and Index::stride().
initialize() [4/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const Index & I, const Index & J, const Index & K)
Definition at line 621 of file Cartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, Reflective, and Index::stride().
initialize() [5/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const NDIndex< Dim > & ndi, MFLOAT **const delX)
Definition at line 405 of file Cartesian.hpp.
References Dim, and Reflective.
initialize() [6/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const Index & I, MFLOAT **const delX)
Definition at line 485 of file Cartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, and Reflective.
initialize() [7/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const Index & I, const Index & J, MFLOAT **const delX)
Definition at line 566 of file Cartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, and Reflective.
initialize() [8/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const Index & I, const Index & J, const Index & K, MFLOAT **const delX)
Definition at line 660 of file Cartesian.hpp.
References Dim, Index::first(), Index::length(), PInsist, and Reflective.
initialize() [9/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const NDIndex< Dim > & ndi, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 423 of file Cartesian.hpp.
References Dim, and Reflective.
initialize() [10/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const Index & I, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 502 of file Cartesian.hpp.
References Dim, Index::length(), PInsist, and Reflective.
initialize() [11/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const Index & I, const Index & J, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 585 of file Cartesian.hpp.
References Dim, Index::length(), PInsist, and Reflective.
initialize() [12/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const Index & I, const Index & J, const Index & K, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig)
Definition at line 682 of file Cartesian.hpp.
References Dim, Index::length(), PInsist, and Reflective.
initialize() [13/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const NDIndex< Dim > & ndi, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig, MeshBC_E *const mbc)
Definition at line 442 of file Cartesian.hpp.
References Dim.
initialize() [14/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const Index & I, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig, MeshBC_E *const mbc)
Definition at line 520 of file Cartesian.hpp.
References Dim, Index::length(), and PInsist.
initialize() [15/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const Index & I, const Index & J, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig, MeshBC_E *const mbc)
Definition at line 604 of file Cartesian.hpp.
References Dim, Index::length(), and PInsist.
initialize() [16/16]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::initialize (const Index & I, const Index & J, const Index & K, MFLOAT **const delX, const Vektor< MFLOAT, Dim > & orig, MeshBC_E *const mbc)
Definition at line 702 of file Cartesian.hpp.
References Dim, Index::length(), and PInsist.
print()
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::print (std::ostream & out)
Definition at line 1471 of file Cartesian.hpp.
References begin(), Dim, and endl().
Referenced by operator<<().
set_Dvc()
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::set_Dvc () private
Definition at line 769 of file Cartesian.hpp.
References Dim.
set_MeshBC() [1/2]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::set_MeshBC (unsigned face, MeshBC_E meshBCType)
Definition at line 2051 of file Cartesian.hpp.
set_MeshBC() [2/2]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::set_MeshBC (MeshBC_E * meshBCTypes)
Definition at line 2062 of file Cartesian.hpp.
References Dim.
set_meshSpacing()
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::set_meshSpacing (MFLOAT **const del)
Definition at line 748 of file Cartesian.hpp.
References Dim.
set_origin()
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::set_origin (const Vektor< MFLOAT, Dim > & o)
Definition at line 723 of file Cartesian.hpp.
References Dim.
setup()
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::setup (void) private
Definition at line 46 of file Cartesian.hpp.
storeSpacingFields() [1/9]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::storeSpacingFields ()
Definition at line 840 of file Cartesian.hpp.
References Dim, and PARALLEL.
storeSpacingFields() [2/9]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag p1, int vnodes = -1)
Definition at line 850 of file Cartesian.hpp.
storeSpacingFields() [3/9]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag p1, e_dim_tag p2, int vnodes = -1)
Definition at line 859 of file Cartesian.hpp.
storeSpacingFields() [4/9]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, int vnodes = -1)
Definition at line 869 of file Cartesian.hpp.
storeSpacingFields() [5/9]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag * p, int vnodes = -1)
Definition at line 882 of file Cartesian.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), Dim, BareField< T, Dim >::end(), BareField< T, Dim >::end_if(), BareField< T, Dim >::fillGuardCells(), LField< T, Dim >::getAllocated(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), min(), NoBC, Periodic, NDIndex< Dim >::plugBase(), Reflective, BareField< T, Dim >::rightGuard(), Attrib::Legacy::Distribution::T, NDIndex< Dim >::touches(), and BareField< T, Dim >::Uncompress().
storeSpacingFields() [6/9]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag p1, unsigned vnodes1, bool recurse = false, int vnodes = -1)
Definition at line 1152 of file Cartesian.hpp.
References Dim.
storeSpacingFields() [7/9]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag p1, e_dim_tag p2, unsigned vnodes1, unsigned vnodes2, bool recurse = false, int vnodes = -1)
Definition at line 1165 of file Cartesian.hpp.
References Dim.
storeSpacingFields() [8/9]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, bool recurse = false, int vnodes = -1)
Definition at line 1179 of file Cartesian.hpp.
References Dim.
storeSpacingFields() [9/9]
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::storeSpacingFields (e_dim_tag * p, unsigned * vnodesPerDirection, bool recurse = false, int vnodes = -1)
Definition at line 1199 of file Cartesian.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), Dim, BareField< T, Dim >::end(), BareField< T, Dim >::end_if(), endl(), ERRORMSG, BareField< T, Dim >::fillGuardCells(), LField< T, Dim >::getAllocated(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), min(), NoBC, Periodic, NDIndex< Dim >::plugBase(), Reflective, BareField< T, Dim >::rightGuard(), Attrib::Legacy::Distribution::T, NDIndex< Dim >::touches(), and BareField< T, Dim >::Uncompress().
updateMeshSpacingGuards()
template<unsigned Dim, class MFLOAT > void Cartesian< Dim, MFLOAT >::updateMeshSpacingGuards (int face) private
Definition at line 2075 of file Cartesian.hpp.
References endl(), ERRORMSG, NoBC, Periodic, and Reflective.
Member Data Documentation
CellSpacings
template<unsigned Dim, class MFLOAT = double> BareField<Vektor<MFLOAT,Dim>,Dim>* Cartesian< Dim, MFLOAT >::CellSpacings
Definition at line 145 of file Cartesian.h.
Referenced by Cartesian< Dim, MFLOAT >::~Cartesian().
Dvc
template<unsigned Dim, class MFLOAT = double> Vektor<MFLOAT,Dim> Cartesian< Dim, MFLOAT >::Dvc[1<< Dim]
Definition at line 142 of file Cartesian.h.
FlCell
template<unsigned Dim, class MFLOAT = double> FieldLayout<Dim>* Cartesian< Dim, MFLOAT >::FlCell private
Definition at line 127 of file Cartesian.h.
Referenced by Cartesian< Dim, MFLOAT >::~Cartesian().
FlVert
template<unsigned Dim, class MFLOAT = double> FieldLayout<Dim>* Cartesian< Dim, MFLOAT >::FlVert private
Definition at line 128 of file Cartesian.h.
Referenced by Cartesian< Dim, MFLOAT >::~Cartesian().
gridSizes
template<unsigned Dim, class MFLOAT = double> unsigned Cartesian< Dim, MFLOAT >::gridSizes[Dim]
Definition at line 141 of file Cartesian.h.
hasSpacingFields
template<unsigned Dim, class MFLOAT = double> bool Cartesian< Dim, MFLOAT >::hasSpacingFields
Definition at line 143 of file Cartesian.h.
Referenced by Cartesian< Dim, MFLOAT >::Cartesian(), and Cartesian< Dim, MFLOAT >::~Cartesian().
MeshBC
template<unsigned Dim, class MFLOAT = double> MeshBC_E Cartesian< Dim, MFLOAT >::MeshBC[2 *Dim] private
Definition at line 126 of file Cartesian.h.
meshPosition
template<unsigned Dim, class MFLOAT = double> std::map<int,MFLOAT> Cartesian< Dim, MFLOAT >::meshPosition[Dim] private
Definition at line 124 of file Cartesian.h.
meshSpacing
template<unsigned Dim, class MFLOAT = double> std::map<int,MFLOAT> Cartesian< Dim, MFLOAT >::meshSpacing[Dim] private
Definition at line 122 of file Cartesian.h.
origin
template<unsigned Dim, class MFLOAT = double> Vektor<MFLOAT,Dim> Cartesian< Dim, MFLOAT >::origin private
Definition at line 125 of file Cartesian.h.
VertSpacings
template<unsigned Dim, class MFLOAT = double> BareField<Vektor<MFLOAT,Dim>,Dim>* Cartesian< Dim, MFLOAT >::VertSpacings
Definition at line 144 of file Cartesian.h.
Referenced by Cartesian< Dim, MFLOAT >::~Cartesian().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Meshes/Cartesian.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Meshes/Cartesian.hpp