OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Field/CompressedBrickIterator.hpp File Reference
CompressedBrickIterator.hpp File Reference
#include "Field/CompressedBrickIterator.h"
#include "Utility/PAssert.h"
Classes
class CompressedLoopTag< Dim, B >
Functions
template<class T , unsigned Dim>
bool all_values_equal (const CompressedBrickIterator< T, Dim > &iter, T val, CompressedLoopTag< 1, true >)
template<class T , unsigned Dim>
bool all_values_equal (const CompressedBrickIterator< T, Dim > &iter, T val, CompressedLoopTag< 2, true >)
template<class T , unsigned Dim>
bool all_values_equal (const CompressedBrickIterator< T, Dim > &iter, T val, CompressedLoopTag< 3, true >)
template<class T , unsigned Dim1, unsigned Dim2>
bool all_values_equal (CompressedBrickIterator< T, Dim1 > iter, T val, CompressedLoopTag< Dim2, false >)
template<class T , unsigned D1, unsigned D2>
CompressedBrickIterator< T, D2 > permute (const CompressedBrickIterator< T, D1 > &iter, const NDIndex< D1 > &current, const NDIndex< D2 > &perm)
Function Documentation
all_values_equal() [1/4]
template<class T , unsigned Dim> bool all_values_equal (const CompressedBrickIterator< T, Dim > & iter, T val, CompressedLoopTag< 1, true >) inline
Definition at line 89 of file CompressedBrickIterator.hpp.
References Hypervolume::n, BrickIterator< T, Dim >::offset(), and BrickCounter< Dim >::size().
Referenced by all_values_equal(), and CompressedBrickIterator< T, Dim >::CanCompress().
all_values_equal() [2/4]
template<class T , unsigned Dim> bool all_values_equal (const CompressedBrickIterator< T, Dim > & iter, T val, CompressedLoopTag< 2, true >) inline
Definition at line 111 of file CompressedBrickIterator.hpp.
References BrickIterator< T, Dim >::offset(), and BrickCounter< Dim >::size().
all_values_equal() [3/4]
template<class T , unsigned Dim> bool all_values_equal (const CompressedBrickIterator< T, Dim > & iter, T val, CompressedLoopTag< 3, true >) inline
Definition at line 139 of file CompressedBrickIterator.hpp.
References BrickIterator< T, Dim >::offset(), and BrickCounter< Dim >::size().
all_values_equal() [4/4]
template<class T , unsigned Dim1, unsigned Dim2> bool all_values_equal (CompressedBrickIterator< T, Dim1 > iter, T val, CompressedLoopTag< Dim2, false >) inline
Definition at line 169 of file CompressedBrickIterator.hpp.
References all_values_equal(), Hypervolume::n, BrickCounter< Dim >::size(), and BrickIterator< T, Dim >::step().
permute()
template<class T , unsigned D1, unsigned D2> CompressedBrickIterator<T,D2> permute (const CompressedBrickIterator< T, D1 > & iter, const NDIndex< D1 > & current, const NDIndex< D2 > & perm)
Definition at line 278 of file CompressedBrickIterator.hpp.
References CompressedBrickIterator< T, Dim >::GetCompressedData(), CompressedBrickIterator< T, Dim >::GetStride(), and CompressedBrickIterator< T, Dim >::IsCompressed().
Referenced by CompressedBrickIterator< T, Dim >::permute().