OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Message/CRC.h File Reference
CRC.h File Reference
Typedefs
typedef unsigned int CRCTYPE
Functions
CRCTYPE crc (void *icp, int icnt)
Typedef Documentation
CRCTYPE
typedef unsigned int CRCTYPE
Definition at line 25 of file CRC.h.
Function Documentation
crc()
CRCTYPE crc (void * icp, int icnt)
Definition at line 106 of file CRC.cpp.
References crc().
Referenced by crc(), Communicate::fill_msg_buffer(), and Communicate::unpack_message().