OPAL (Object Oriented Parallel Accelerator Library): NDIndex< Dim > Class Template Reference
NDIndex< Dim > Class Template Reference
#include <FieldDataSource.h>
Public Member Functions
NDIndex ()
NDIndex (const Index *idx)
NDIndex (const Index &)
NDIndex (const Index &, const Index &)
NDIndex (const Index &, const Index &, const Index &)
NDIndex (const Index &, const Index &, const Index &, const Index &)
NDIndex (const Index &, const Index &, const Index &, const Index &, const Index &)
NDIndex (const Index &, const Index &, const Index &, const Index &, const Index &, const Index &)
NDIndex (const NDIndex< Dim-1 > &, const Index &)
const Index & operator[] (unsigned d) const
Index & operator[] (unsigned d)
unsigned size () const
bool empty () const
NDIndex< Dim > intersect (const NDIndex< Dim > &) const
template<unsigned D>
NDIndex< Dim > plugBase (const NDIndex< D > &i) const
bool touches (const NDIndex< Dim > &) const
bool contains (const NDIndex< Dim > &a) const
bool containsAllPoints (const NDIndex< Dim > &b) const
bool split (NDIndex< Dim > &l, NDIndex< Dim > &r, unsigned d, double a) const
bool split (NDIndex< Dim > &l, NDIndex< Dim > &r, unsigned d) const
bool split (NDIndex< Dim > &l, NDIndex< Dim > &r) const
Message & putMessage (Message &m) const
Message & getMessage (Message &m)
template<>
NDIndex (const NDIndex< 1 > &ndi, const Index &i)
template<>
NDIndex (const NDIndex< 3 > &ndi, const Index &i)
template<>
NDIndex (const NDIndex< 4 > &ndi, const Index &i)
template<>
NDIndex (const NDIndex< 5 > &ndi, const Index &i)
Private Attributes
Index p [Dim==0?1:Dim]
Detailed Description
template<unsigned Dim>
class NDIndex< Dim >
Definition at line 40 of file FieldDataSource.h.
Constructor & Destructor Documentation
NDIndex() [1/13]
template<unsigned Dim> NDIndex< Dim >::NDIndex () inline
Definition at line 78 of file NDIndex.h.
NDIndex() [2/13]
template<unsigned Dim> NDIndex< Dim >::NDIndex (const Index * idx) inline
Definition at line 22 of file NDIndexInlines.h.
NDIndex() [3/13]
template<unsigned Dim> NDIndex< Dim >::NDIndex (const Index & i0) inline
Definition at line 169 of file NDIndexInlines.h.
NDIndex() [4/13]
template<unsigned Dim> NDIndex< Dim >::NDIndex (const Index & i0, const Index & i1) inline
Definition at line 177 of file NDIndexInlines.h.
NDIndex() [5/13]
template<unsigned Dim> NDIndex< Dim >::NDIndex (const Index & i0, const Index & i1, const Index & i2) inline
Definition at line 186 of file NDIndexInlines.h.
NDIndex() [6/13]
template<unsigned Dim> NDIndex< Dim >::NDIndex (const Index & i0, const Index & i1, const Index & i2, const Index & i3) inline
Definition at line 196 of file NDIndexInlines.h.
NDIndex() [7/13]
template<unsigned Dim> NDIndex< Dim >::NDIndex (const Index & i0, const Index & i1, const Index & i2, const Index & i3, const Index & i4) inline
Definition at line 208 of file NDIndexInlines.h.
NDIndex() [8/13]
template<unsigned Dim> NDIndex< Dim >::NDIndex (const Index & i0, const Index & i1, const Index & i2, const Index & i3, const Index & i4, const Index & i5) inline
Definition at line 221 of file NDIndexInlines.h.
NDIndex() [9/13]
template<unsigned Dim> NDIndex< Dim >::NDIndex (const NDIndex< Dim-1 > & , const Index &)
NDIndex() [10/13]
template<> NDIndex< 2 >::NDIndex (const NDIndex< 1 > & ndi, const Index & i) inline
Definition at line 234 of file NDIndexInlines.h.
NDIndex() [11/13]
template<> NDIndex< 4 >::NDIndex (const NDIndex< 3 > & ndi, const Index & i) inline
Definition at line 247 of file NDIndexInlines.h.
NDIndex() [12/13]
template<> NDIndex< 5 >::NDIndex (const NDIndex< 4 > & ndi, const Index & i) inline
Definition at line 255 of file NDIndexInlines.h.
NDIndex() [13/13]
template<> NDIndex< 6 >::NDIndex (const NDIndex< 5 > & ndi, const Index & i) inline
Definition at line 264 of file NDIndexInlines.h.
Member Function Documentation
contains()
template<unsigned Dim> bool NDIndex< Dim >::contains (const NDIndex< Dim > & a) const inline
Definition at line 92 of file NDIndexInlines.h.
Referenced by assign(), ExtrapolateAndZeroFaceBCApply(), ExtrapolateFaceBCApply(), IndexedLocalAssign(), FieldPrint< T, Dim >::print(), and DiscField< Dim >::read().
containsAllPoints()
template<unsigned Dim> bool NDIndex< Dim >::containsAllPoints (const NDIndex< Dim > & b) const inline
Definition at line 104 of file NDIndexInlines.h.
Referenced by assign(), IndexedLocalAssign(), IndexedReceive(), and TryCompressLHS().
empty()
template<unsigned Dim> bool NDIndex< Dim >::empty () const inline
Definition at line 116 of file NDIndexInlines.h.
Referenced by assign(), SubFieldIter< T, Dim, NDIndex< Dim > >::findIntersection(), and SubFieldIter< T, Dim, SOffset< Dim > >::findIntersection().
getMessage()
template<unsigned Dim> Message& NDIndex< Dim >::getMessage (Message & m) inline
Definition at line 138 of file NDIndex.h.
Referenced by BareField< T1, D >::accumGuardCells(), assign(), FieldLayout< Dim >::FieldLayout(), BareField< T1, D >::fillGuardCells(), FieldDataSource< T, Dim, M, C >::gather_data(), NDIndex< Brackets >::getMessage(), IndexedReceive(), FieldPrint< T, Dim >::print(), FieldDebugPrint< T, Dim >::print(), DiscField< Dim >::read(), BareField< T1, D >::write(), and DiscField< Dim >::write().
intersect()
template<unsigned Dim> NDIndex< Dim > NDIndex< Dim >::intersect (const NDIndex< Dim > & i) const inline
Definition at line 31 of file NDIndexInlines.h.
Referenced by BareField< T1, D >::accumGuardCells(), assign(), CalcIndexedReceive(), ComponentFunctionFaceBCApply(), ComponentLinearExtrapolateFaceBCApply(), DiscField< Dim >::compute_expected(), ExtrapolateAndZeroFaceBCApply(), ExtrapolateAndZeroFaceBCApply2(), ExtrapolateFaceBCApply(), ExtrapolateFaceBCApply2(), BareField< T1, D >::fillGuardCells(), SubFieldIter< T, Dim, NDIndex< Dim > >::findIntersection(), FunctionFaceBCApply(), IndexedLocalAssign(), InterpolationFaceBCApply(), LinearExtrapolateFaceBCApply(), PeriodicFaceBCApply(), FieldPrint< T, Dim >::print(), FieldDebugPrint< T, Dim >::print(), DiscField< Dim >::read(), UniformCartesian< Dim, MFLOAT >::storeSpacingFields(), and Cartesian< Dim, MFLOAT >::storeSpacingFields().
operator[]() [1/2]
template<unsigned Dim> const Index& NDIndex< Dim >::operator[] (unsigned d) const inline
Definition at line 97 of file NDIndex.h.
operator[]() [2/2]
template<unsigned Dim> Index& NDIndex< Dim >::operator[] (unsigned d) inline
Definition at line 101 of file NDIndex.h.
plugBase()
template<unsigned Dim> template<unsigned D> NDIndex<Dim> NDIndex< Dim >::plugBase (const NDIndex< D > & i) const inline
Definition at line 114 of file NDIndex.h.
Referenced by ComponentFunctionFaceBCApply(), ExtrapolateAndZeroFaceBCApply2(), ExtrapolateFaceBCApply2(), FunctionFaceBCApply(), InterpolationFaceBCApply(), PeriodicFaceBCApply(), plugBase(), SubFieldIter< T, Dim, NDIndex< Dim > >::plugBase(), UniformCartesian< Dim, MFLOAT >::storeSpacingFields(), and Cartesian< Dim, MFLOAT >::storeSpacingFields().
putMessage()
template<unsigned Dim> Message& NDIndex< Dim >::putMessage (Message & m) const inline
Definition at line 130 of file NDIndex.h.
Referenced by assign(), FieldDataSource< T, Dim, M, C >::gather_data(), IndexedSend(), FieldPrint< T, Dim >::print(), FieldDebugPrint< T, Dim >::print(), NDIndex< Brackets >::putMessage(), DiscField< Dim >::read(), BareField< T1, D >::write(), and DiscField< Dim >::write().
size()
template<unsigned Dim> unsigned NDIndex< Dim >::size (void) const inline
Definition at line 68 of file NDIndexInlines.h.
Referenced by SIndex< Dim >::addIndex(), DiscField< Dim >::chunk_domain(), DiscField< Dim >::compute_expected(), DiscField< Dim >::distribute_offsets(), FieldLayout< Dim >::initialize(), DiscField< Dim >::read(), SIndex< Dim >::removeIndex(), FieldLayout< Dim >::setup(), BareField< T1, D >::write(), and DiscField< Dim >::write_offset_and_data().
split() [1/3]
template<unsigned Dim> bool NDIndex< Dim >::split (NDIndex< Dim > & l, NDIndex< Dim > & r, unsigned d, double a) const inline
Definition at line 128 of file NDIndexInlines.h.
Referenced by FieldLayout< Dim >::setup(), and NDIndex< Brackets >::split().
split() [2/3]
template<unsigned Dim> bool NDIndex< Dim >::split (NDIndex< Dim > & l, NDIndex< Dim > & r, unsigned d) const inline
Definition at line 140 of file NDIndexInlines.h.
split() [3/3]
template<unsigned Dim> bool NDIndex< Dim >::split (NDIndex< Dim > & l, NDIndex< Dim > & r) const inline
Definition at line 153 of file NDIndexInlines.h.
touches()
template<unsigned Dim> bool NDIndex< Dim >::touches (const NDIndex< Dim > & a) const inline
Definition at line 80 of file NDIndexInlines.h.
Referenced by BareField< T1, D >::accumGuardCells(), AssignTouches< D1, D1 >::apply(), assign(), CalcIndexedReceive(), ComponentFunctionFaceBCApply(), ComponentLinearExtrapolateFaceBCApply(), DiscField< Dim >::compute_expected(), DiscField< Dim >::distribute_offsets(), ExtrapolateAndZeroFaceBCApply(), ExtrapolateFaceBCApply(), BareField< T1, D >::fillGuardCells(), FunctionFaceBCApply(), BareField< T1, D >::getsingle(), IndexedLocalAssign(), IndexedSend(), InterpolationFaceBCApply(), LinearExtrapolateFaceBCApply(), PeriodicFaceBCApply(), FieldPrint< T, Dim >::print(), FieldDebugPrint< T, Dim >::print(), DiscField< Dim >::read(), UniformCartesian< Dim, MFLOAT >::storeSpacingFields(), and Cartesian< Dim, MFLOAT >::storeSpacingFields().
Member Data Documentation
p
template<unsigned Dim> Index NDIndex< Dim >::p[Dim==0?1:Dim] private
Definition at line 145 of file NDIndex.h.
Referenced by NDIndex< Brackets >::getMessage(), NDIndex< Brackets >::operator[](), and NDIndex< Brackets >::putMessage().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/FieldDataSource.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Index/NDIndex.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Index/NDIndexInlines.h