OPAL (Object Oriented Parallel Accelerator Library): src/Classic/BeamlineGeometry/Vector3D.cpp File Reference
Vector3D.cpp File Reference
#include "BeamlineGeometry/Vector3D.h"
Functions
Vector3D operator+ (const Vector3D &lhs, const Vector3D &rhs)
Add.
Vector3D operator- (const Vector3D &lhs, const Vector3D &rhs)
Subtract.
Vector3D operator* (const Vector3D &lhs, double rhs)
Multiply.
Vector3D operator* (double lhs, const Vector3D &rhs)
Multiply.
Vector3D cross (const Vector3D &lhs, const Vector3D &rhs)
Vector cross product.
double dot (const Vector3D &lhs, const Vector3D &rhs)
Vector dot product.
Function Documentation
cross()
Vector3D cross (const Vector3D & lhs, const Vector3D & rhs)
Vector cross product.
Definition at line 111 of file Vector3D.cpp.
Referenced by TSV_MetaCross< Vektor< T1, 3 >, Vektor< T2, 3 > >::apply(), ScatteringPhysics::applyRandomRotation(), getQuaternion(), ParallelCyclotronTracker::getQuaternionTwoVectors(), Bend2D::getSurfaceMesh(), BoundaryGeometry::intersectLineTriangle(), BorisPusher::kick(), Quaternion::operator*=(), and ParallelCyclotronTracker::rotateWithQuaternion().
dot()
double dot (const Vector3D & lhs, const Vector3D & rhs)
Vector dot product.
Definition at line 118 of file Vector3D.cpp.
Referenced by TSV_MetaDot< Vektor< T1, D >, Vektor< T2, D > >::apply(), FlexibleCollimator::apply(), Degrader::apply(), TSV_MetaDot< Tenzor< T1, D >, Tenzor< T2, D > >::apply(), TSV_MetaDot< SymTenzor< T1, D >, SymTenzor< T2, D > >::apply(), TSV_MetaDot< SymTenzor< T1, D >, Tenzor< T2, D > >::apply(), TSV_MetaDot< Tenzor< T1, D >, SymTenzor< T2, D > >::apply(), P3MPoissonSolver::applyConstantFocusing(), Tracker::applyDrift(), ScatteringPhysics::applyRandomRotation(), ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), ParallelCyclotronTracker::bunchDumpStatData(), MultiBunchHandler::calcBunchBeamParameters(), PartBunchBase< double, 3 >::calcGammas(), PartBunchBase< double, 3 >::calcGammas_cycl(), ParallelCyclotronTracker::computePathLengthUpdate(), ParallelCyclotronTracker::computeSpaceChargeFields_m(), ParallelCyclotronTracker::deleteParticle(), Div(), Probe::doCheck(), Stripper::doCheck(), BeamStrippingPhysics::doPhysics(), ParticleInteractLayout< T, Dim, Mesh >::find_pairs(), ParallelCyclotronTracker::gapCrossKick_m(), Euclid3DGeometry::getArcLength(), PartBunchBase< double, 3 >::getBoundingSphere(), Util::getGamma(), PartBunchBase< double, 3 >::getLocalBoundingSphere(), Bend2D::getOutline(), CavityAutophaser::getPhaseAtMaxEnergy(), getQuaternion(), ParallelCyclotronTracker::getQuaternionTwoVectors(), Bend2D::getSurfaceMesh(), ParallelCyclotronTracker::globalToLocal(), ParallelCyclotronTracker::initDistInGlobalFrame(), OrbitThreader::integrate(), BoundaryGeometry::intersectLineTriangle(), BorisPusher::kick(), ParallelCyclotronTracker::localToGlobal(), mslang::AffineTransformation::mult(), Quaternion::Norm(), ParallelCyclotronTracker::normalizeQuaternion(), ParallelCyclotronTracker::normalizeVector(), Quaternion::operator*=(), BoundaryGeometry::partInside(), BorisPusher::push(), ParallelCyclotronTracker::push(), LF2< FieldFunction, Arguments >::push_m(), ParallelCyclotronTracker::rotateAroundX(), ParallelCyclotronTracker::rotateAroundZ(), CoordinateSystemTrafo::rotateFrom(), CoordinateSystemTrafo::rotateTo(), ParallelCyclotronTracker::rotateWithQuaternion(), OrbitThreader::setDesignEnergy(), Bend2D::setFieldCalcParam(), AmrBoxLib::tagForMomenta_m(), RFCavity::trackOnAxisParticle(), CoordinateSystemTrafo::transformFrom(), CoordinateSystemTrafo::transformTo(), and mslang::AffineTransformation::transformTo().
operator*() [1/2]
Vector3D operator* (const Vector3D & lhs, double rhs)
Multiply.
Definition at line 83 of file Vector3D.cpp.
operator*() [2/2]
Vector3D operator* (double lhs, const Vector3D & rhs)
Multiply.
Definition at line 88 of file Vector3D.cpp.
operator+()
Vector3D operator+ (const Vector3D & lhs, const Vector3D & rhs)
Add.
Definition at line 73 of file Vector3D.cpp.
operator-()
Vector3D operator- (const Vector3D & lhs, const Vector3D & rhs)
Subtract.
Definition at line 78 of file Vector3D.cpp.