OPAL (Object Oriented Parallel Accelerator Library): ParticleInteractLayout< T, Dim, Mesh > Class Template Reference
ParticleInteractLayout< T, Dim, Mesh > Class Template Reference
#include <ParticleInteractLayout.h>
Classes
struct pair_t
Public Types
typedef std::vector< pair_t >::iterator pair_iterator
typedef ParticleLayout< T, Dim >::SingleParticlePos_t SingleParticlePos_t
typedef ParticleLayout< T, Dim >::Index_t Index_t
typedef ParticleInteractAttrib< SingleParticlePos_t > ParticlePos_t
typedef ParticleInteractAttrib< Index_t > ParticleIndex_t
typedef ParticleInteractAttrib< T > ParticleInterRadius_t
Public Types inherited from ParticleSpatialLayout< T, Dim, Mesh >
typedef int pair_t
typedef pair_t * pair_iterator
typedef ParticleLayout< T, Dim >::SingleParticlePos_t SingleParticlePos_t
typedef ParticleLayout< T, Dim >::Index_t Index_t
typedef ParticleAttrib< SingleParticlePos_t > ParticlePos_t
typedef ParticleAttrib< Index_t > ParticleIndex_t
typedef RegionLayout< T, Dim, Mesh > RegionLayout_t
Public Types inherited from ParticleLayout< T, Dim >
enum { Dimension = Dim }
enum UpdateFlags {
SWAP, BCONDS, NUMFLAGS, OPTDESTROY,
ALL
}
typedef T Position_t
typedef unsigned Index_t
typedef Vektor< T, Dim > SingleParticlePos_t
Public Types inherited from User
typedef Unique::type ID_t
Public Member Functions
ParticleInteractLayout (FieldLayout< Dim > &)
ParticleInteractLayout (FieldLayout< Dim > &, Mesh &)
ParticleInteractLayout (const RegionLayout< T, Dim, Mesh > &)
ParticleInteractLayout ()
~ParticleInteractLayout ()
void update (IpplParticleBase< ParticleInteractLayout< T, Dim, Mesh > > &p, const ParticleAttrib< char > *canSwap=0)
void getPairlist (unsigned, pair_iterator &, pair_iterator &, IpplParticleBase< ParticleInteractLayout< T, Dim, Mesh > > &)
void setInteractionRadius (const T &r)
void setInteractionRadius (ParticleInterRadius_t &rAttrib)
T getMaxInteractionRadius ()
T getInteractionRadius (unsigned i)
void setNeedGhostSwap (bool cond=true)
virtual void Repartition (UserList *)
Public Member Functions inherited from ParticleSpatialLayout< T, Dim, Mesh >
ParticleSpatialLayout (FieldLayout< Dim > &)
ParticleSpatialLayout (FieldLayout< Dim > &, Mesh &)
ParticleSpatialLayout (const RegionLayout< T, Dim, Mesh > &)
ParticleSpatialLayout ()
~ParticleSpatialLayout ()
FieldLayout< Dim > & getFieldLayout ()
RegionLayout< T, Dim, Mesh > & getLayout ()
const RegionLayout< T, Dim, Mesh > & getLayout () const
int getNodeCount (unsigned i) const
bool getEmptyNode (unsigned i) const
void update (IpplParticleBase< ParticleSpatialLayout< T, Dim, Mesh, BoxParticleCachingPolicy< T, Dim, Mesh > > > &p, const ParticleAttrib< char > *canSwap=0)
void printDebug (Inform &)
virtual void notifyUserOfDelete (UserList *)
void enableCaching ()
void disableCaching ()
Public Member Functions inherited from ParticleLayout< T, Dim >
ParticleLayout ()
~ParticleLayout ()
void setUpdateFlag (UpdateFlags f, bool val)
bool getUpdateFlag (UpdateFlags f) const
ParticleBConds< T, Dim > & getBConds ()
void setBConds (const ParticleBConds< T, Dim > &bc)
Public Member Functions inherited from FieldLayoutUser
FieldLayoutUser ()
virtual ~FieldLayoutUser ()
Public Member Functions inherited from User
User ()
virtual ~User ()
ID_t get_Id () const
Public Member Functions inherited from BoxParticleCachingPolicy< T, Dim, Mesh >
BoxParticleCachingPolicy ()
void setCacheDimension (int d, T length)
void setAllCacheDimensions (T length)
template<class C >
void updateCacheInformation (ParticleSpatialLayout< T, Dim, Mesh, C > &PLayout)
template<class C >
void updateGhostParticles (IpplParticleBase< ParticleSpatialLayout< T, Dim, Mesh, C > > &PData, ParticleSpatialLayout< T, Dim, Mesh, C > &)
Private Member Functions
void setup ()
void rebuild_interaction_data ()
void rebuild_interaction_data (const bool periodicBC[2 *Dim])
void swap_ghost_particles (unsigned, IpplParticleBase< ParticleInteractLayout< T, Dim, Mesh > > &)
void swap_ghost_particles (unsigned, IpplParticleBase< ParticleInteractLayout< T, Dim, Mesh > > &, const bool periodicBC[2 *Dim])
void find_pairs (const unsigned LocalNum, const unsigned a1, const unsigned a2, const bool initLists, IpplParticleBase< ParticleInteractLayout< T, Dim, Mesh > > &PData)
void setMaxInteractionRadius (T maxval)
T getMaxLocalInteractionRadius ()
Private Attributes
bool NeedGhostSwap
bool * InterNodeList
bool * SentToNodeList
unsigned InteractionNodes
std::vector< std::vector< pair_t > *> PairList
T InterRadius
T MaxGlobalInterRadius
ParticleInterRadius_t * InterRadiusArray
Additional Inherited Members
Protected Member Functions inherited from ParticleSpatialLayout< T, Dim, Mesh >
void setup ()
void rebuild_layout (size_t haveLocal, PB &PData)
size_t swap_particles (size_t LocalNum, PB &PData)
size_t swap_particles (size_t LocalNum, PB &PData, const ParticleAttrib< char > &canSwap)
size_t short_swap_particles (size_t LocalNum, PB &PData)
size_t new_swap_particles (size_t LocalNum, PB &PData)
size_t new_swap_particles (size_t LocalNum, PB &PData, const ParticleAttrib< char > &canSwap)
Protected Member Functions inherited from ParticleLayout< T, Dim >
template<class PPT , class NDI >
void apply_bconds (unsigned n, PPT &R, const ParticleBConds< T, Dim > &bcs, const NDI &nr)
Protected Member Functions inherited from BoxParticleCachingPolicy< T, Dim, Mesh >
~BoxParticleCachingPolicy ()
Protected Attributes inherited from ParticleSpatialLayout< T, Dim, Mesh >
RegionLayout< T, Dim, Mesh > RLayout
size_t * NodeCount
bool * EmptyNode
bool * SwapNodeList [Dim]
Message ** SwapMsgList
unsigned NeighborNodes [Dim]
std::vector< size_t > * PutList
bool caching
Protected Attributes inherited from User
ID_t Id
Detailed Description
template<class T, unsigned Dim, class Mesh = UniformCartesian<Dim,T>>
class ParticleInteractLayout< T, Dim, Mesh >
Definition at line 50 of file ParticleInteractLayout.h.
Member Typedef Documentation
Index_t
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> typedef ParticleLayout<T, Dim>::Index_t ParticleInteractLayout< T, Dim, Mesh >::Index_t
Definition at line 77 of file ParticleInteractLayout.h.
pair_iterator
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> typedef std::vector<pair_t>::iterator ParticleInteractLayout< T, Dim, Mesh >::pair_iterator
Definition at line 73 of file ParticleInteractLayout.h.
ParticleIndex_t
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> typedef ParticleInteractAttrib<Index_t> ParticleInteractLayout< T, Dim, Mesh >::ParticleIndex_t
Definition at line 81 of file ParticleInteractLayout.h.
ParticleInterRadius_t
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> typedef ParticleInteractAttrib<T> ParticleInteractLayout< T, Dim, Mesh >::ParticleInterRadius_t
Definition at line 82 of file ParticleInteractLayout.h.
ParticlePos_t
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> typedef ParticleInteractAttrib<SingleParticlePos_t> ParticleInteractLayout< T, Dim, Mesh >::ParticlePos_t
Definition at line 80 of file ParticleInteractLayout.h.
SingleParticlePos_t
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> typedef ParticleLayout<T, Dim>::SingleParticlePos_t ParticleInteractLayout< T, Dim, Mesh >::SingleParticlePos_t
Definition at line 76 of file ParticleInteractLayout.h.
Constructor & Destructor Documentation
ParticleInteractLayout() [1/4]
template<class T , unsigned Dim, class Mesh > ParticleInteractLayout< T, Dim, Mesh >::ParticleInteractLayout (FieldLayout< Dim > & fl)
Definition at line 34 of file ParticleInteractLayout.hpp.
References ParticleInteractLayout< T, Dim, Mesh >::setup().
ParticleInteractLayout() [2/4]
template<class T , unsigned Dim, class Mesh > ParticleInteractLayout< T, Dim, Mesh >::ParticleInteractLayout (FieldLayout< Dim > & fl, Mesh & mesh)
Definition at line 44 of file ParticleInteractLayout.hpp.
References ParticleInteractLayout< T, Dim, Mesh >::setup().
ParticleInteractLayout() [3/4]
template<class T , unsigned Dim, class Mesh > ParticleInteractLayout< T, Dim, Mesh >::ParticleInteractLayout (const RegionLayout< T, Dim, Mesh > & rl)
Definition at line 54 of file ParticleInteractLayout.hpp.
References ParticleInteractLayout< T, Dim, Mesh >::setup().
ParticleInteractLayout() [4/4]
template<class T , unsigned Dim, class Mesh > ParticleInteractLayout< T, Dim, Mesh >::ParticleInteractLayout ()
Definition at line 64 of file ParticleInteractLayout.hpp.
References ParticleInteractLayout< T, Dim, Mesh >::setup().
~ParticleInteractLayout()
template<class T , unsigned Dim, class Mesh > ParticleInteractLayout< T, Dim, Mesh >::~ParticleInteractLayout ()
Definition at line 91 of file ParticleInteractLayout.hpp.
Member Function Documentation
find_pairs()
template<class T , unsigned Dim, class Mesh > void ParticleInteractLayout< T, Dim, Mesh >::find_pairs (const unsigned LocalNum, const unsigned a1, const unsigned a2, const bool initLists, IpplParticleBase< ParticleInteractLayout< T, Dim, Mesh > > & PData) private
Definition at line 883 of file ParticleInteractLayout.hpp.
References begin(), dot(), end(), and Attrib::Legacy::Distribution::T.
getInteractionRadius()
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> T ParticleInteractLayout< T, Dim, Mesh >::getInteractionRadius (unsigned i) inline
Definition at line 144 of file ParticleInteractLayout.h.
References ParticleInteractLayout< T, Dim, Mesh >::InterRadius, and ParticleInteractLayout< T, Dim, Mesh >::InterRadiusArray.
getMaxInteractionRadius()
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> T ParticleInteractLayout< T, Dim, Mesh >::getMaxInteractionRadius () inline
Definition at line 141 of file ParticleInteractLayout.h.
References ParticleInteractLayout< T, Dim, Mesh >::MaxGlobalInterRadius.
getMaxLocalInteractionRadius()
template<class T , unsigned Dim, class Mesh > T ParticleInteractLayout< T, Dim, Mesh >::getMaxLocalInteractionRadius () private
Definition at line 104 of file ParticleInteractLayout.hpp.
getPairlist()
template<class T , unsigned Dim, class Mesh > void ParticleInteractLayout< T, Dim, Mesh >::getPairlist (unsigned n, pair_iterator & bpi, pair_iterator & epi, IpplParticleBase< ParticleInteractLayout< T, Dim, Mesh > > & PData)
Definition at line 125 of file ParticleInteractLayout.hpp.
References Dim, Hypervolume::n, and ParticlePeriodicBCond().
rebuild_interaction_data() [1/2]
template<class T , unsigned Dim, class Mesh > void ParticleInteractLayout< T, Dim, Mesh >::rebuild_interaction_data () private
Definition at line 168 of file ParticleInteractLayout.hpp.
References RegionLayout< T, Dim, MeshType >::begin_iv(), Dim, RegionLayout< T, Dim, MeshType >::end_iv(), IpplInfo::getNodes(), Attrib::Legacy::Distribution::T, and RegionLayout< T, Dim, MeshType >::touch_range_rdv().
rebuild_interaction_data() [2/2]
template<class T , unsigned Dim, class Mesh > void ParticleInteractLayout< T, Dim, Mesh >::rebuild_interaction_data (const bool periodicBC[2 *Dim]) private
Definition at line 227 of file ParticleInteractLayout.hpp.
References RegionLayout< T, Dim, MeshType >::begin_iv(), Dim, RegionLayout< T, Dim, MeshType >::end_iv(), IpplInfo::getNodes(), IpplInfo::myNode(), PAssert, Attrib::Legacy::Distribution::T, RegionLayout< T, Dim, MeshType >::touch_range_rdv(), and NDRegion< T, Dim >::touches().
Repartition()
template<class T , unsigned Dim, class Mesh > void ParticleInteractLayout< T, Dim, Mesh >::Repartition (UserList * userlist) virtual
Reimplemented from ParticleSpatialLayout< T, Dim, Mesh >.
Definition at line 978 of file ParticleInteractLayout.hpp.
References UserList::getUserListID().
setInteractionRadius() [1/2]
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> void ParticleInteractLayout< T, Dim, Mesh >::setInteractionRadius (const T & r) inline
Definition at line 129 of file ParticleInteractLayout.h.
References ParticleInteractLayout< T, Dim, Mesh >::InterRadius, and ParticleInteractLayout< T, Dim, Mesh >::InterRadiusArray.
setInteractionRadius() [2/2]
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> void ParticleInteractLayout< T, Dim, Mesh >::setInteractionRadius (ParticleInterRadius_t & rAttrib) inline
Definition at line 134 of file ParticleInteractLayout.h.
References ParticleInteractLayout< T, Dim, Mesh >::InterRadiusArray.
setMaxInteractionRadius()
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> void ParticleInteractLayout< T, Dim, Mesh >::setMaxInteractionRadius (T maxval) inline private
Definition at line 212 of file ParticleInteractLayout.h.
References ParticleInteractLayout< T, Dim, Mesh >::MaxGlobalInterRadius.
setNeedGhostSwap()
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> void ParticleInteractLayout< T, Dim, Mesh >::setNeedGhostSwap (bool cond = true) inline
Definition at line 151 of file ParticleInteractLayout.h.
References ParticleInteractLayout< T, Dim, Mesh >::NeedGhostSwap.
setup()
template<class T , unsigned Dim, class Mesh > void ParticleInteractLayout< T, Dim, Mesh >::setup (void) private
Definition at line 73 of file ParticleInteractLayout.hpp.
References IpplInfo::getNodes().
Referenced by ParticleInteractLayout< T, Dim, Mesh >::ParticleInteractLayout().
swap_ghost_particles() [1/2]
template<class T , unsigned Dim, class Mesh > void ParticleInteractLayout< T, Dim, Mesh >::swap_ghost_particles (unsigned LocalNum, IpplParticleBase< ParticleInteractLayout< T, Dim, Mesh > > & PData) private
Definition at line 520 of file ParticleInteractLayout.hpp.
References IpplInfo::getNodes(), and Attrib::Legacy::Distribution::T.
swap_ghost_particles() [2/2]
template<class T , unsigned Dim, class Mesh > void ParticleInteractLayout< T, Dim, Mesh >::swap_ghost_particles (unsigned LocalNum, IpplParticleBase< ParticleInteractLayout< T, Dim, Mesh > > & PData, const bool periodicBC[2 *Dim]) private
Definition at line 655 of file ParticleInteractLayout.hpp.
References RegionLayout< T, Dim, MeshType >::begin_iv(), IpplInfo::Comm, Communicate::COMM_ANY_NODE, Dim, RegionLayout< T, Dim, MeshType >::end_iv(), endl(), ERRORMSG, Rnode< T, Dim >::getNode(), IpplInfo::getNodes(), IpplInfo::myNode(), TagMaker::next_tag(), P_LAYOUT_CYCLE, P_SPATIAL_GHOST_TAG, PAssert, Communicate::receive_block(), Communicate::send(), Attrib::Legacy::Distribution::T, RegionLayout< T, Dim, MeshType >::touch_range_rdv(), and NDRegion< T, Dim >::touches().
update()
template<class T , unsigned Dim, class Mesh > void ParticleInteractLayout< T, Dim, Mesh >::update (IpplParticleBase< ParticleInteractLayout< T, Dim, Mesh > > & p, const ParticleAttrib< char > * canSwap = 0)
Definition at line 380 of file ParticleInteractLayout.hpp.
References Communicate::broadcast_others(), IpplInfo::Comm, Communicate::COMM_ANY_NODE, Dim, Message::get(), IpplInfo::getNodes(), IpplInfo::myNode(), TagMaker::next_tag(), P_LAYOUT_CYCLE, P_SPATIAL_LAYOUT_TAG, P_SPATIAL_RETURN_TAG, ParticlePeriodicBCond(), Message::put(), Communicate::receive_block(), Communicate::send(), SWAP, and Attrib::Legacy::Distribution::T.
Member Data Documentation
InteractionNodes
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> unsigned ParticleInteractLayout< T, Dim, Mesh >::InteractionNodes private
Definition at line 167 of file ParticleInteractLayout.h.
InterNodeList
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> bool* ParticleInteractLayout< T, Dim, Mesh >::InterNodeList private
Definition at line 165 of file ParticleInteractLayout.h.
InterRadius
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> T ParticleInteractLayout< T, Dim, Mesh >::InterRadius private
Definition at line 176 of file ParticleInteractLayout.h.
Referenced by ParticleInteractLayout< T, Dim, Mesh >::getInteractionRadius(), and ParticleInteractLayout< T, Dim, Mesh >::setInteractionRadius().
InterRadiusArray
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> ParticleInterRadius_t* ParticleInteractLayout< T, Dim, Mesh >::InterRadiusArray private
Definition at line 177 of file ParticleInteractLayout.h.
Referenced by ParticleInteractLayout< T, Dim, Mesh >::getInteractionRadius(), and ParticleInteractLayout< T, Dim, Mesh >::setInteractionRadius().
MaxGlobalInterRadius
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> T ParticleInteractLayout< T, Dim, Mesh >::MaxGlobalInterRadius private
Definition at line 176 of file ParticleInteractLayout.h.
Referenced by ParticleInteractLayout< T, Dim, Mesh >::getMaxInteractionRadius(), and ParticleInteractLayout< T, Dim, Mesh >::setMaxInteractionRadius().
NeedGhostSwap
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> bool ParticleInteractLayout< T, Dim, Mesh >::NeedGhostSwap private
Definition at line 164 of file ParticleInteractLayout.h.
Referenced by ParticleInteractLayout< T, Dim, Mesh >::setNeedGhostSwap().
PairList
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> std::vector< std::vector<pair_t>* > ParticleInteractLayout< T, Dim, Mesh >::PairList private
Definition at line 170 of file ParticleInteractLayout.h.
SentToNodeList
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> bool* ParticleInteractLayout< T, Dim, Mesh >::SentToNodeList private
Definition at line 166 of file ParticleInteractLayout.h.
The documentation for this class was generated from the following files:
ippl/src/Particle/ParticleInteractLayout.h
ippl/src/Particle/ParticleInteractLayout.hpp