OPAL (Object Oriented Parallel Accelerator Library): CompoundStatement Class Reference
CompoundStatement Class Reference
Compound statement.
#include <CompoundStatement.h>
Public Member Functions
CompoundStatement (TokenStream &)
Constructor.
virtual ~CompoundStatement ()
virtual void execute (const Parser &)
Execute.
Public Member Functions inherited from Statement
Statement (const std::string &name, int line)
Constructor.
Statement (const std::string &name, TokenList &)
Constructor.
virtual ~Statement ()
void append (const Token &)
Append a token.
bool atEnd () const
Test for end of command.
bool boolean (bool &value)
Return boolean value.
bool delimiter (char c)
Test for delimiter.
bool delimiter (const char *s)
Test for delimiter choice.
Token & getCurrent ()
Return current token and skip it.
bool integer (int &value)
Return signed integer.
bool integer (unsigned &value)
Return unsigned integer.
bool keyword (const char *s)
Test for keyword.
bool real (double &value)
Return real value.
bool str (std::string &value)
Return string value.
bool word (std::string &value)
Return word value.
void mark ()
Mark position in command.
void restore ()
Return to marked position.
void start ()
Return to start.
void skip ()
Skip.
unsigned int position () const
Return current character number in line.
virtual void print (std::ostream &os) const
Print statement.
virtual void printWhere (Inform &msg, bool withToken) const
Print position.
std::string str () const
Private Member Functions
CompoundStatement ()
CompoundStatement (const CompoundStatement &)
void operator= (const CompoundStatement &)
Private Attributes
Pointer< MacroStream > tokens
Additional Inherited Members
Public Types inherited from Statement
typedef std::list< Token > TokenList
The type of the enclosed token list.
Protected Attributes inherited from Statement
int stat_line
std::string buffer_name
TokenList tokens
TokenList::iterator curr
TokenList::iterator keep
Detailed Description
Compound statement.
Definition at line 38 of file CompoundStatement.h.
Constructor & Destructor Documentation
CompoundStatement() [1/3]
CompoundStatement::CompoundStatement (TokenStream & is)
Constructor.
Definition at line 28 of file CompoundStatement.cpp.
References MacroStream::append(), Statement::buffer_name, Token::getFile(), Token::getLine(), Token::isDel(), Token::isEOF(), TokenStream::readToken(), Statement::stat_line, and tokens.
~CompoundStatement()
CompoundStatement::~CompoundStatement () virtual
Definition at line 52 of file CompoundStatement.cpp.
CompoundStatement() [2/3]
CompoundStatement::CompoundStatement () private
CompoundStatement() [3/3]
CompoundStatement::CompoundStatement (const CompoundStatement &) private
Member Function Documentation
execute()
void CompoundStatement::execute (const Parser & parser) virtual
Execute.
Implements Statement.
Definition at line 56 of file CompoundStatement.cpp.
References Parser::run(), MacroStream::start(), and tokens.
operator=()
void CompoundStatement::operator= (const CompoundStatement &) private
Member Data Documentation
tokens
Pointer<MacroStream> CompoundStatement::tokens private
Definition at line 60 of file CompoundStatement.h.
Referenced by CompoundStatement(), and execute().
The documentation for this class was generated from the following files:
src/OpalParser/CompoundStatement.h
src/OpalParser/CompoundStatement.cpp