OPAL (Object Oriented Parallel Accelerator Library): ParticleBConds< T, Dim > Class Template Reference
ParticleBConds< T, Dim > Class Template Reference
#include <IpplParticleBase.h>
Public Types
typedef T(* ParticleBCond) (const T, const T, const T)
Public Member Functions
ParticleBConds ()
ParticleBConds< T, Dim > & operator= (const ParticleBConds< T, Dim > &pbc)
ParticleBCond & operator[] (unsigned d)
T apply (const T t, const unsigned d, const NDRegion< T, Dim > &nr) const
T apply (const T t, const unsigned d, const NDIndex< Dim > &ni) const
T apply (const T t, const unsigned d, const T m1, const T m2) const
Private Attributes
ParticleBCond BCList [2 *Dim]
Detailed Description
template<class T, unsigned Dim>
class ParticleBConds< T, Dim >
Definition at line 118 of file IpplParticleBase.h.
Member Typedef Documentation
ParticleBCond
template<class T, unsigned Dim> typedef T(* ParticleBConds< T, Dim >::ParticleBCond) (const T, const T, const T)
Definition at line 77 of file ParticleBConds.h.
Constructor & Destructor Documentation
ParticleBConds()
template<class T, unsigned Dim> ParticleBConds< T, Dim >::ParticleBConds () inline
Definition at line 82 of file ParticleBConds.h.
References ParticleBConds< T, Dim >::BCList, Dim, and ParticleNoBCond().
Member Function Documentation
apply() [1/3]
template<class T, unsigned Dim> T ParticleBConds< T, Dim >::apply (const T t, const unsigned d, const NDRegion< T, Dim > & nr) const inline
Definition at line 99 of file ParticleBConds.h.
References max(), min(), and nr.
Referenced by ParticleBConds< T, Dim >::apply(), and ParticleLayout< T, Dim >::apply_bconds().
apply() [2/3]
template<class T, unsigned Dim> T ParticleBConds< T, Dim >::apply (const T t, const unsigned d, const NDIndex< Dim > & ni) const inline
Definition at line 107 of file ParticleBConds.h.
References ParticleBConds< T, Dim >::apply().
apply() [3/3]
template<class T, unsigned Dim> T ParticleBConds< T, Dim >::apply (const T t, const unsigned d, const T m1, const T m2) const inline
Definition at line 113 of file ParticleBConds.h.
References ParticleBConds< T, Dim >::BCList.
operator=()
template<class T, unsigned Dim> ParticleBConds<T,Dim>& ParticleBConds< T, Dim >::operator= (const ParticleBConds< T, Dim > & pbc) inline
Definition at line 88 of file ParticleBConds.h.
References ParticleBConds< T, Dim >::BCList, and Dim.
operator[]()
template<class T, unsigned Dim> ParticleBCond& ParticleBConds< T, Dim >::operator[] (unsigned d) inline
Definition at line 95 of file ParticleBConds.h.
References ParticleBConds< T, Dim >::BCList.
Member Data Documentation
BCList
template<class T, unsigned Dim> ParticleBCond ParticleBConds< T, Dim >::BCList[2 *Dim] private
Definition at line 124 of file ParticleBConds.h.
Referenced by ParticleBConds< T, Dim >::apply(), ParticleBConds< T, Dim >::operator=(), ParticleBConds< T, Dim >::operator[](), and ParticleBConds< T, Dim >::ParticleBConds().
The documentation for this class was generated from the following files:
ippl/src/Particle/IpplParticleBase.h
ippl/src/Particle/ParticleBConds.h