OPAL (Object Oriented Parallel Accelerator Library): FieldLoc< Dim > Class Template Reference
FieldLoc< Dim > Class Template Reference
#include <FieldLoc.h>
Public Member Functions
FieldLoc (const vec< int, Dim > &v, int f)
FieldLoc (const FieldLoc< Dim > &fl)
FieldLoc ()
~FieldLoc ()
FieldLoc< Dim > & operator= (const FieldLoc< Dim > &fl)
int & operator[] (int n)
int operator[] (int n) const
int getIndex () const
void setIndex (int newval)
NDIndex< Dim > getDomain () const
Private Attributes
vec< int, Dim > loc
int LFIndex
Detailed Description
template<unsigned Dim>
class FieldLoc< Dim >
Definition at line 29 of file FieldLoc.h.
Constructor & Destructor Documentation
FieldLoc() [1/3]
template<unsigned Dim> FieldLoc< Dim >::FieldLoc (const vec< int, Dim > & v, int f) inline
Definition at line 35 of file FieldLoc.h.
FieldLoc() [2/3]
template<unsigned Dim> FieldLoc< Dim >::FieldLoc (const FieldLoc< Dim > & fl) inline
Definition at line 38 of file FieldLoc.h.
FieldLoc() [3/3]
template<unsigned Dim> FieldLoc< Dim >::FieldLoc () inline
Definition at line 41 of file FieldLoc.h.
~FieldLoc()
template<unsigned Dim> FieldLoc< Dim >::~FieldLoc () inline
Definition at line 44 of file FieldLoc.h.
Member Function Documentation
getDomain()
template<unsigned Dim> NDIndex<Dim> FieldLoc< Dim >::getDomain (void) const inline
Definition at line 67 of file FieldLoc.h.
References Dim, and FieldLoc< Dim >::loc.
Referenced by IndexedBareFieldIterator< T, Dim >::SetCurrentLocation().
getIndex()
template<unsigned Dim> int FieldLoc< Dim >::getIndex () const inline
Definition at line 61 of file FieldLoc.h.
References FieldLoc< Dim >::LFIndex.
Referenced by BareFieldIterator< T, Dim >::SetCurrentLocation().
operator=()
template<unsigned Dim> FieldLoc<Dim>& FieldLoc< Dim >::operator= (const FieldLoc< Dim > & fl) inline
Definition at line 47 of file FieldLoc.h.
References FieldLoc< Dim >::LFIndex, and FieldLoc< Dim >::loc.
operator[]() [1/2]
template<unsigned Dim> int& FieldLoc< Dim >::operator[] (int n) inline
Definition at line 56 of file FieldLoc.h.
References FieldLoc< Dim >::loc, and Hypervolume::n.
operator[]() [2/2]
template<unsigned Dim> int FieldLoc< Dim >::operator[] (int n) const inline
Definition at line 57 of file FieldLoc.h.
References FieldLoc< Dim >::loc, and Hypervolume::n.
setIndex()
template<unsigned Dim> void FieldLoc< Dim >::setIndex (int newval) inline
Definition at line 64 of file FieldLoc.h.
References FieldLoc< Dim >::LFIndex.
Referenced by BareFieldIterator< T, Dim >::GetCurrentLocation().
Member Data Documentation
LFIndex
template<unsigned Dim> int FieldLoc< Dim >::LFIndex private
Definition at line 79 of file FieldLoc.h.
Referenced by FieldLoc< Dim >::getIndex(), FieldLoc< Dim >::operator=(), and FieldLoc< Dim >::setIndex().
loc
template<unsigned Dim> vec<int,Dim> FieldLoc< Dim >::loc private
Definition at line 76 of file FieldLoc.h.
Referenced by FieldLoc< Dim >::getDomain(), FieldLoc< Dim >::operator=(), and FieldLoc< Dim >::operator[]().
The documentation for this class was generated from the following file:
ippl/src/Field/FieldLoc.h