OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Message/Communicate.h File Reference
Communicate.h File Reference
#include "Message/TagMaker.h"
#include "Message/Tags.h"
#include <cstdlib>
#include <memory>
#include <cstring>
#include <vector>
#include <utility>
#include <iostream>
#include <mpi.h>
Classes
class CommSendInfo
class Communicate
struct Communicate::MessageData
Functions
std::ostream & operator<< (std::ostream &, const Communicate &)
Variables
const int COMM_ANY_NODE = (-1)
const int COMM_ANY_TAG = (-1)
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & , const Communicate &)
Definition at line 47 of file Communicate.cpp.
References Physics::c.
Variable Documentation
COMM_ANY_NODE
const int COMM_ANY_NODE = (-1)
Definition at line 40 of file Communicate.h.
Referenced by BareField< T1, D >::accumGuardCells(), ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), assign(), FieldLayout< Dim >::FieldLayout(), BareField< T1, D >::fillGuardCells(), IpplInfo::find_smp_nodes(), FieldDataSource< T, Dim, M, C >::gather_data(), BareField< T1, D >::getsingle(), IndexedReceive(), DiscConfig::parse_config(), FieldPrint< T, Dim >::print(), FieldDebugPrint< T, Dim >::print(), ParticleSpatialLayout< T, Dim, Mesh >::rebuild_layout(), reduce(), reduce_masked(), IpplParticleBase< T >::resetID(), LossDataSink::saveASCII(), scatter(), ParallelCyclotronTracker::singleParticleDump(), BareField< T1, D >::write(), DiscParticle::write(), and DiscField< Dim >::write().
COMM_ANY_TAG
const int COMM_ANY_TAG = (-1)
Definition at line 41 of file Communicate.h.
Referenced by DiscField< Dim >::read().