OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Classic/FixedAlgebra/TransportFun.h File Reference
TransportFun.h File Reference
#include <iosfwd>
#include "FixedAlgebra/TransportFun.hpp"
#include "FixedAlgebra/TransportMap.h"
Classes
class FVector< T, N >
A templated representation for vectors.
class TransportMap< T, N >
Transport map with values of type [b]T[/b] in [b]N[/b] variables.
class FMatrix< T, R, C >
A templated representation for matrices.
class TransportFun< T, N >
Transport function in N variables of type T.
Functions
template<class T , int N>
TransportFun< T, N > operator+ (const TransportFun< T, N > &, const TransportFun< T, N > &)
Add.
template<class T , int N>
TransportFun< T, N > operator- (const TransportFun< T, N > &, const TransportFun< T, N > &)
Subtract.
template<class T , int N>
TransportFun< T, N > operator+ (const TransportFun< T, N > &, const T &)
Add.
template<class T , int N>
TransportFun< T, N > operator- (const TransportFun< T, N > &, const T &)
Subtract.
template<class T , int N>
TransportFun< T, N > operator+ (const T &, const TransportFun< T, N > &)
Add.
template<class T , int N>
TransportFun< T, N > operator- (const T &, const TransportFun< T, N > &)
Subtract.
template<class T , int N>
TransportFun< T, N > operator* (const TransportFun< T, N > &, const TransportFun< T, N > &)
Multiply.
template<class T , int N>
TransportFun< T, N > operator/ (const TransportFun< T, N > &, const TransportFun< T, N > &)
Divide.
template<class T , int N>
TransportFun< T, N > operator* (const TransportFun< T, N > &, const T &)
Multiply.
template<class T , int N>
TransportFun< T, N > operator/ (const TransportFun< T, N > &, const T &)
Divide.
template<class T , int N>
TransportFun< T, N > operator* (const T &, const TransportFun< T, N > &)
Multiply.
template<class T , int N>
TransportFun< T, N > operator/ (const T &, const TransportFun< T, N > &)
Divide 1 / TransportFun.
template<class T , int N>
bool operator== (const T &, const TransportFun< T, N > &)
Equality.
template<class T , int N>
bool operator!= (const T &, const TransportFun< T, N > &)
Inequality.
template<class T , int N>
std::istream & operator>> (std::istream &is, TransportFun< T, N > &)
Extract TransportFun from stream [b]is[/b].
template<class T , int N>
std::ostream & operator<< (std::ostream &os, const TransportFun< T, N > &)
Insert TransportFun to stream [b]os[/b].
Function Documentation
operator!=()
template<class T , int N> bool operator!= (const T & , const TransportFun< T, N > &) inline
Inequality.
Definition at line 547 of file TransportFun.hpp.
operator*() [1/3]
template<class T , int N> TransportFun<T, N> operator* (const TransportFun< T, N > & , const TransportFun< T, N > &) inline
Multiply.
Definition at line 502 of file TransportFun.hpp.
References TransportFun< T, N >::multiply().
operator*() [2/3]
template<class T , int N> TransportFun<T, N> operator* (const TransportFun< T, N > & , const T &) inline
Multiply.
Definition at line 514 of file TransportFun.hpp.
operator*() [3/3]
template<class T , int N> TransportFun<T, N> operator* (const T & , const TransportFun< T, N > &) inline
Multiply.
Definition at line 528 of file TransportFun.hpp.
operator+() [1/3]
template<class T , int N> TransportFun<T, N> operator+ (const TransportFun< T, N > & , const TransportFun< T, N > &) inline
Add.
Definition at line 460 of file TransportFun.hpp.
operator+() [2/3]
template<class T , int N> TransportFun<T, N> operator+ (const TransportFun< T, N > & , const T &) inline
Add.
Definition at line 474 of file TransportFun.hpp.
operator+() [3/3]
template<class T , int N> TransportFun<T, N> operator+ (const T & , const TransportFun< T, N > &) inline
Add.
Definition at line 488 of file TransportFun.hpp.
operator-() [1/3]
template<class T , int N> TransportFun<T, N> operator- (const TransportFun< T, N > & , const TransportFun< T, N > &) inline
Subtract.
Definition at line 467 of file TransportFun.hpp.
operator-() [2/3]
template<class T , int N> TransportFun<T, N> operator- (const TransportFun< T, N > & , const T &) inline
Subtract.
Definition at line 481 of file TransportFun.hpp.
operator-() [3/3]
template<class T , int N> TransportFun<T, N> operator- (const T & , const TransportFun< T, N > &) inline
Subtract.
Definition at line 495 of file TransportFun.hpp.
operator/() [1/3]
template<class T , int N> TransportFun<T, N> operator/ (const TransportFun< T, N > & , const TransportFun< T, N > &) inline
Divide.
Definition at line 508 of file TransportFun.hpp.
References TransportFun< T, N >::inverse(), and TransportFun< T, N >::multiply().
operator/() [2/3]
template<class T , int N> TransportFun<T, N> operator/ (const TransportFun< T, N > & , const T &) inline
Divide.
Definition at line 521 of file TransportFun.hpp.
operator/() [3/3]
template<class T , int N> TransportFun<T, N> operator/ (const T & , const TransportFun< T, N > &) inline
Divide 1 / TransportFun.
Definition at line 535 of file TransportFun.hpp.
References TransportFun< T, N >::inverse().
operator<<()
template<class T , int N> std::ostream& operator<< (std::ostream & os, const TransportFun< T, N > &)
Insert TransportFun to stream [b]os[/b].
Definition at line 559 of file TransportFun.hpp.
operator==()
template<class T , int N> bool operator== (const T & , const TransportFun< T, N > &) inline
Equality.
Definition at line 541 of file TransportFun.hpp.
operator>>()
template<class T , int N> std::istream& operator>> (std::istream & is, TransportFun< T, N > &)
Extract TransportFun from stream [b]is[/b].
Definition at line 553 of file TransportFun.hpp.
References TransportFun< T, N >::get().