OPAL (Object Oriented Parallel Accelerator Library): Distribution Class Reference
Distribution Class Reference
#include <Distribution.h>
Classes
class BinomialBehaviorSplitter
class GaussianLikeBehavior
class MDependentBehavior
Public Member Functions
Distribution ()
virtual ~Distribution ()
virtual bool canReplaceBy (Object *object)
Distribution can only be replaced by another distribution.
virtual Distribution * clone (const std::string &name)
Return a clone.
virtual void execute ()
Execute the command.
virtual void update ()
Update this object.
size_t getNumOfLocalParticlesToCreate (size_t n)
void createOpalCycl (PartBunchBase< double, 3 > *beam, size_t numberOfParticles, double current, const Beamline &bl)
void createOpalT (PartBunchBase< double, 3 > *beam, std::vector< Distribution *> addedDistributions, size_t &numberOfParticles)
void createOpalT (PartBunchBase< double, 3 > *beam, size_t &numberOfParticles)
void doRestartOpalT (PartBunchBase< double, 3 > *p, size_t Np, int restartStep, H5PartWrapper *h5wrapper)
void doRestartOpalCycl (PartBunchBase< double, 3 > *p, size_t Np, int restartStep, const int specifiedNumBunch, H5PartWrapper *h5wrapper)
size_t emitParticles (PartBunchBase< double, 3 > *beam, double eZ)
double getPercentageEmitted () const
bool getIfDistEmitting ()
int getLastEmittedEnergyBin ()
double getMaxTOrZ ()
double getMinTOrZ ()
size_t getNumberOfEmissionSteps ()
int getNumberOfEnergyBins ()
double getEmissionDeltaT ()
double getEnergyBinDeltaT ()
double getWeight ()
double getTEmission ()
Vector_t get_pmean () const
std::string getTypeofDistribution ()
DistributionType getType () const
Inform & printInfo (Inform &os) const
bool Rebin ()
void setDistToEmitted (bool emitted)
void setDistType ()
void setSigmaR_m ()
void setSigmaP_m (double massIneV)
void shiftBeam (double &maxTOrZ, double &minTOrZ)
double getEmissionTimeShift () const
void setNumberOfDistributions (unsigned int n)
Public Member Functions inherited from Definition
virtual ~Definition ()
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static Distribution * find (const std::string &name)
Private Types
enum EmissionModel : unsigned short { EmissionModel::NONE, EmissionModel::ASTRA, EmissionModel::NONEQUIL }
enum InputMomentumUnits : unsigned short { InputMomentumUnits::NONE, InputMomentumUnits::EVOVERC }
Private Member Functions
Distribution (const std::string &name, Distribution *parent)
Distribution (const Distribution &)=delete
void operator= (const Distribution &)=delete
std::vector< double > & getXDist ()
std::vector< double > & getBGxDist ()
std::vector< double > & getYDist ()
std::vector< double > & getBGyDist ()
std::vector< double > & getTOrZDist ()
std::vector< double > & getBGzDist ()
void eraseXDist ()
void eraseBGxDist ()
void eraseYDist ()
void eraseBGyDist ()
void eraseTOrZDist ()
void eraseBGzDist ()
void addDistributions ()
void applyEmissionModel (double lowEnergyLimit, double &px, double &py, double &pz, std::vector< double > &additionalRNs)
void applyEmissModelAstra (double &px, double &py, double &pz, std::vector< double > &additionalRNs)
void applyEmissModelNone (double &pz)
void applyEmissModelNonEquil (double eZ, double &px, double &py, double &pz, std::vector< double > &additionalRNs)
void create (size_t &numberOfParticles, double massIneV, double charge)
void calcPartPerDist (size_t numberOfParticles)
void checkEmissionParameters ()
void checkIfEmitted ()
void checkParticleNumber (size_t &numberOfParticles)
void checkFileMomentum (double momentumTol)
void chooseInputMomentumUnits (InputMomentumUnits inputMoUnits)
size_t getNumberOfParticlesInFile (std::ifstream &inputFile)
void createDistributionBinomial (size_t numberOfParticles, double massIneV)
void createDistributionFlattop (size_t numberOfParticles, double massIneV)
void createDistributionMultiGauss (size_t numberOfParticles, double massIneV)
void createDistributionFromFile (size_t numberOfParticles, double massIneV)
void createDistributionGauss (size_t numberOfParticles, double massIneV)
void createMatchedGaussDistribution (size_t numberOfParticles, double massIneV, double charge)
void sampleUniformDisk (gsl_qrng *quasiRandGen2D, double &x1, double &x2)
void fillEBinHistogram ()
void fillParticleBins ()
size_t findEBin (double tOrZ)
void generateAstraFlattopT (size_t numberOfParticles)
void generateBinomial (size_t numberOfParticles)
void generateFlattopLaserProfile (size_t numberOfParticles)
void generateFlattopT (size_t numberOfParticles)
void generateFlattopZ (size_t numberOfParticles)
void generateGaussZ (size_t numberOfParticles)
void generateMatchedGauss (const SigmaGenerator::matrix_t &, size_t numberOfParticles, double massIneV)
void generateLongFlattopT (size_t numberOfParticles)
void generateTransverseGauss (size_t numberOfParticles)
void initializeBeam (PartBunchBase< double, 3 > *beam)
void injectBeam (PartBunchBase< double, 3 > *beam)
void printDist (Inform &os, size_t numberOfParticles) const
void printDistBinomial (Inform &os) const
void printDistFlattop (Inform &os) const
void printDistMultiGauss (Inform &os) const
void printDistFromFile (Inform &os) const
void printDistGauss (Inform &os) const
void printDistMatchedGauss (Inform &os) const
void printEmissionModel (Inform &os) const
void printEmissionModelAstra (Inform &os) const
void printEmissionModelNone (Inform &os) const
void printEmissionModelNonEquil (Inform &os) const
void printEnergyBins (Inform &os) const
void adjustPhaseSpace (double massIneV)
void reflectDistribution (size_t &numberOfParticles)
void scaleDistCoordinates ()
gsl_qrng * selectRandomGenerator (std::string, unsigned int dimension)
Select and allocate gsl random number generator.
void setAttributes ()
void setDistParametersBinomial (double massIneV)
void setDistParametersFlattop (double massIneV)
void setDistParametersMultiGauss (double massIneV)
void setDistParametersGauss (double massIneV)
void setEmissionTime (double &maxT, double &minT)
void setupEmissionModel (PartBunchBase< double, 3 > *beam)
void setupEmissionModelAstra (PartBunchBase< double, 3 > *beam)
void setupEmissionModelNone (PartBunchBase< double, 3 > *beam)
void setupEmissionModelNonEquil ()
void setupEnergyBins (double maxTOrZ, double minTOrZ)
void setupParticleBins (double massIneV, PartBunchBase< double, 3 > *beam)
void shiftDistCoordinates (double massIneV)
void writeOutFileHeader ()
void writeOutFileEmission ()
void writeOutFileInjection ()
Private Attributes
std::string distT_m
DistributionType distrTypeT_m
Distribution type strings.
unsigned int numberOfDistributions_m
List of Distribution types.
bool emitting_m
PartData particleRefData_m
std::vector< Distribution * > addedDistributions_m
Vector of distributions to be added to this distribution.
std::vector< size_t > particlesPerDist_m
EmissionModel emissionModel_m
Emission Model.
double tEmission_m
Emission parameters.
double tBin_m
double currentEmissionTime_m
int currentEnergyBin_m
int currentSampleBin_m
int numberOfEnergyBins_m
int numberOfSampleBins_m
PartBins * energyBins_m
gsl_histogram * energyBinHist_m
Distribution energy bins.
gsl_rng * randGen_m
double pTotThermal_m
Random number generator.
Vector_t pmean_m
Total thermal momentum.
double cathodeWorkFunc_m
double laserEnergy_m
Cathode material work function (eV).
double cathodeFermiEnergy_m
Laser photon energy (eV).
double cathodeTemp_m
Cathode material Fermi energy (eV).
double emitEnergyUpperLimit_m
Cathode temperature (K).
std::vector< std::vector< double > > additionalRNs_m
Upper limit on emission energy distribution (eV).
size_t totalNumberParticles_m
size_t totalNumberEmittedParticles_m
std::vector< double > xDist_m
std::vector< double > pxDist_m
std::vector< double > yDist_m
std::vector< double > pyDist_m
std::vector< double > tOrZDist_m
std::vector< double > pzDist_m
std::vector< double > xWrite_m
std::vector< double > pxWrite_m
std::vector< double > yWrite_m
std::vector< double > pyWrite_m
std::vector< double > tOrZWrite_m
std::vector< double > pzWrite_m
std::vector< size_t > binWrite_m
double avrgpz_m
InputMomentumUnits inputMoUnits_m
double sigmaTRise_m
double sigmaTFall_m
double tPulseLengthFWHM_m
Vector_t sigmaR_m
Vector_t sigmaP_m
Vector_t cutoffR_m
Vector_t cutoffP_m
Vector_t mBinomial_m
matrix_t correlationMatrix_m
double sepPeaks_m
unsigned nPeaks_m
std::string laserProfileFileName_m
std::string laserImageName_m
double laserIntensityCut_m
LaserProfile * laserProfile_m
double I_m
double E_m
double tRise_m
time binned distribution with thermal energy
double tFall_m
double sigmaRise_m
double sigmaFall_m
double cutoff_m
std::string outFilename_m
Static Private Attributes
static const double percentTEmission_m = 0.0005
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Definition
Definition (int size, const char *name, const char *help)
Constructor for exemplars.
Definition (const std::string &name, Definition *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 188 of file Distribution.h.
Member Enumeration Documentation
EmissionModel
enum Distribution::EmissionModel : unsigned short strong private
Enumerator
NONE
ASTRA
NONEQUIL
Definition at line 245 of file Distribution.h.
InputMomentumUnits
enum Distribution::InputMomentumUnits : unsigned short strong private
Enumerator
NONE
EVOVERC
Definition at line 251 of file Distribution.h.
Constructor & Destructor Documentation
Distribution() [1/3]
Distribution::Distribution ()
Definition at line 80 of file Distribution.cpp.
References Object::builtin, clone(), OpalData::define(), OpalData::getInstance(), NODIST, randGen_m, and setAttributes().
Referenced by clone().
~Distribution()
Distribution::~Distribution () virtual
Definition at line 210 of file Distribution.cpp.
References energyBinHist_m, energyBins_m, laserProfile_m, and randGen_m.
Distribution() [2/3]
Distribution::Distribution (const std::string & name, Distribution * parent) private
Parameters
name
parent
Definition at line 141 of file Distribution.cpp.
References NODIST, and randGen_m.
Distribution() [3/3]
Distribution::Distribution (const Distribution &) private delete
Member Function Documentation
addDistributions()
void Distribution::addDistributions () private
Definition at line 601 of file Distribution.cpp.
References addedDistributions_m, particlesPerDist_m, pxDist_m, pyDist_m, pzDist_m, tOrZDist_m, xDist_m, and yDist_m.
Referenced by createOpalT().
adjustPhaseSpace()
void Distribution::adjustPhaseSpace (double massIneV) private
Definition at line 4420 of file Distribution.cpp.
References allreduce(), avrgpz_m, Util::convertMomentumEVoverCToBetaGamma(), distrTypeT_m, emitting_m, EVOVERC, FROMFILE, OpalData::getInstance(), Attributes::getReal(), inputMoUnits_m, Object::itsAttr, Attrib::Distribution::OFFSETPX, Attrib::Distribution::OFFSETPY, pow(), pxDist_m, pyDist_m, pzDist_m, tOrZDist_m, totalNumberParticles_m, xDist_m, and yDist_m.
Referenced by create().
applyEmissionModel()
void Distribution::applyEmissionModel (double lowEnergyLimit, double & px, double & py, double & pz, std::vector< double > & additionalRNs) private
Definition at line 645 of file Distribution.cpp.
References applyEmissModelAstra(), applyEmissModelNone(), applyEmissModelNonEquil(), ASTRA, emissionModel_m, NONE, and NONEQUIL.
Referenced by emitParticles().
applyEmissModelAstra()
void Distribution::applyEmissModelAstra (double & px, double & py, double & pz, std::vector< double > & additionalRNs) private
Definition at line 663 of file Distribution.cpp.
References abs(), acos(), cos(), pTotThermal_m, sin(), sqrt(), and Physics::two_pi.
Referenced by applyEmissionModel().
applyEmissModelNone()
void Distribution::applyEmissModelNone (double & pz) private
Definition at line 674 of file Distribution.cpp.
References pTotThermal_m.
Referenced by applyEmissionModel().
applyEmissModelNonEquil()
void Distribution::applyEmissModelNonEquil (double eZ, double & px, double & py, double & pz, std::vector< double > & additionalRNs) private
Definition at line 678 of file Distribution.cpp.
References acos(), cathodeFermiEnergy_m, cathodeTemp_m, cos(), emitEnergyUpperLimit_m, exp(), Units::GeV2eV, laserEnergy_m, Physics::m_e, pow(), randGen_m, sin(), sqrt(), and Physics::two_pi.
Referenced by applyEmissionModel().
calcPartPerDist()
void Distribution::calcPartPerDist (size_t numberOfParticles) private
Definition at line 735 of file Distribution.cpp.
References addedDistributions_m, distrTypeT_m, Attrib::Distribution::FNAME, FROMFILE, getNumberOfParticlesInFile(), Attributes::getString(), getWeight(), Object::itsAttr, IpplInfo::myNode(), numberOfDistributions_m, and particlesPerDist_m.
Referenced by createOpalCycl(), and createOpalT().
canReplaceBy()
bool Distribution::canReplaceBy (Object * object) virtual
Distribution can only be replaced by another distribution.
Reimplemented from Object.
Definition at line 241 of file Distribution.cpp.
checkEmissionParameters()
void Distribution::checkEmissionParameters () private
Definition at line 804 of file Distribution.cpp.
References abs(), ceil(), currentEnergyBin_m, currentSampleBin_m, Attrib::Distribution::EMISSIONSTEPS, Attributes::getReal(), Object::itsAttr, Attrib::Distribution::NBIN, numberOfEnergyBins_m, and numberOfSampleBins_m.
Referenced by createOpalT(), and generateAstraFlattopT().
checkFileMomentum()
void Distribution::checkFileMomentum (double momentumTol) private
Definition at line 875 of file Distribution.cpp.
References abs(), avrgpz_m, and pmean_m.
Referenced by createOpalT().
checkIfEmitted()
void Distribution::checkIfEmitted () private
Definition at line 829 of file Distribution.cpp.
References ASTRAFLATTOPTH, distrTypeT_m, Attrib::Distribution::EMITTED, emitting_m, Attributes::getBool(), GUNGAUSSFLATTOPTH, and Object::itsAttr.
Referenced by createOpalT().
checkParticleNumber()
void Distribution::checkParticleNumber (size_t & numberOfParticles) private
Definition at line 844 of file Distribution.cpp.
References IpplInfo::getNodes(), reduce(), and tOrZDist_m.
Referenced by createOpalCycl(), and createOpalT().
chooseInputMomentumUnits()
void Distribution::chooseInputMomentumUnits (InputMomentumUnits inputMoUnits) private
Definition at line 891 of file Distribution.cpp.
References EVOVERC, Attributes::getString(), Attrib::Distribution::INPUTMOUNITS, inputMoUnits_m, Object::itsAttr, and NONE.
Referenced by createOpalCycl(), and createOpalT().
clone()
Distribution * Distribution::clone (const std::string & name) virtual
Return a clone.
Implements Object.
Definition at line 245 of file Distribution.cpp.
References Distribution(), and name.
Referenced by Distribution().
create()
void Distribution::create (size_t & numberOfParticles, double massIneV, double charge) private
Create the particle distribution.
Parameters
numberOfParticles to create
massIneV particle charge in eV
charge of the particle type in elementary charge
Definition at line 255 of file Distribution.cpp.
References additionalRNs_m, adjustPhaseSpace(), ASTRA, ASTRAFLATTOPTH, BINOMIAL, createDistributionBinomial(), createDistributionFlattop(), createDistributionFromFile(), createDistributionGauss(), createDistributionMultiGauss(), createMatchedGaussDistribution(), Options::cZero, distrTypeT_m, emissionModel_m, emitting_m, endl(), FLATTOP, FROMFILE, GAUSS, Attributes::getBool(), IpplInfo::getNodes(), getNumOfLocalParticlesToCreate(), gmsg, GUNGAUSSFLATTOPTH, Object::itsAttr, level2(), MATCHEDGAUSS, MULTIGAUSS, IpplInfo::myNode(), NONEQUIL, particlesPerDist_m, randGen_m, reflectDistribution(), Attrib::Distribution::SCALABLE, scaleDistCoordinates(), Options::seed, and tOrZDist_m.
Referenced by createOpalCycl(), and createOpalT().
createDistributionBinomial()
void Distribution::createDistributionBinomial (size_t numberOfParticles, double massIneV) private
Definition at line 908 of file Distribution.cpp.
References generateBinomial(), and setDistParametersBinomial().
Referenced by create().
createDistributionFlattop()
void Distribution::createDistributionFlattop (size_t numberOfParticles, double massIneV) private
Definition at line 914 of file Distribution.cpp.
References emitting_m, generateFlattopLaserProfile(), generateFlattopT(), generateFlattopZ(), laserProfile_m, and setDistParametersFlattop().
Referenced by create().
createDistributionFromFile()
void Distribution::createDistributionFromFile (size_t numberOfParticles, double massIneV) private
Definition at line 1034 of file Distribution.cpp.
References Util::convertMomentumEVoverCToBetaGamma(), EVOVERC, Attrib::Distribution::FNAME, IpplInfo::getComm(), IpplInfo::getNodes(), getNumberOfParticlesInFile(), Attributes::getString(), inputMoUnits_m, Object::itsAttr, max(), IpplInfo::myNode(), pmean_m, pxDist_m, pyDist_m, pzDist_m, Attrib::Distribution::R, reduce(), tOrZDist_m, xDist_m, and yDist_m.
Referenced by create().
createDistributionGauss()
void Distribution::createDistributionGauss (size_t numberOfParticles, double massIneV) private
Definition at line 1334 of file Distribution.cpp.
References emitting_m, generateGaussZ(), generateLongFlattopT(), generateTransverseGauss(), and setDistParametersGauss().
Referenced by create().
createDistributionMultiGauss()
void Distribution::createDistributionMultiGauss (size_t numberOfParticles, double massIneV) private
Definition at line 927 of file Distribution.cpp.
References abs(), avrgpz_m, cutoffP_m, cutoffR_m, emitting_m, exp(), Attributes::getBool(), IpplInfo::getNodes(), Object::itsAttr, IpplInfo::myNode(), nPeaks_m, pow(), pxDist_m, pyDist_m, pzDist_m, randGen_m, Options::rngtype, sampleUniformDisk(), Attrib::Distribution::SCALABLE, selectRandomGenerator(), sepPeaks_m, setDistParametersMultiGauss(), sigmaP_m, sigmaR_m, tOrZDist_m, xDist_m, and yDist_m.
Referenced by create().
createMatchedGaussDistribution()
void Distribution::createMatchedGaussDistribution (size_t numberOfParticles, double massIneV, double charge) private
Definition at line 1166 of file Distribution.cpp.
References Units::A2mA, abs(), Options::cloTuneOnly, Attrib::Distribution::DENERGY, E_m, endl(), Attrib::Distribution::ET, Units::eV2MeV, Attrib::Distribution::EX, SpecificElementVisitor< ELEM >::execute(), Attrib::Distribution::EY, BeamSequence::fetchLine(), BeamSequence::find(), generateMatchedGauss(), Attributes::getBool(), Cyclotron::getCyclHarm(), Cyclotron::getFieldMapFN(), Cyclotron::getFMHighE(), Cyclotron::getFMLowE(), Cyclotron::getPHIinit(), Attributes::getReal(), Attributes::getString(), Units::GeV2MeV, gmsg, I_m, Object::itsAttr, Attrib::Distribution::LINE, Units::m2mm, Attrib::Distribution::MAXSTEPSCO, Attrib::Distribution::MAXSTEPSSI, Attrib::Distribution::NSECTORS, Attrib::Distribution::NSTEPS, Attrib::Distribution::ORDERMAPS, Units::rad2deg, Units::rad2mrad, Attrib::Distribution::RESIDUUM, Attrib::Distribution::RGUESS, Attrib::Distribution::SECTOR, Cyclotron::setPRinit(), and Cyclotron::setRinit().
Referenced by create().
createOpalCycl()
void Distribution::createOpalCycl (PartBunchBase< double, 3 > * beam, size_t numberOfParticles, double current, const Beamline & bl)
Definition at line 1346 of file Distribution.cpp.
References OpalData::addProblemCharacteristicValue(), calcPartPerDist(), checkParticleNumber(), chooseInputMomentumUnits(), create(), E_m, emitting_m, energyBins_m, EVOVERC, fillParticleBins(), PartBunchBase< T, Dim >::getInitialGamma(), OpalData::getInstance(), PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getM(), PartBunchBase< T, Dim >::getQ(), PartBunchBase< T, Dim >::getTotalNum(), I_m, initializeBeam(), injectBeam(), numberOfEnergyBins_m, particlesPerDist_m, setDistType(), PartBunchBase< T, Dim >::setPBins(), setupParticleBins(), shiftDistCoordinates(), tOrZDist_m, totalNumberParticles_m, and writeOutFileHeader().
Referenced by PartBunchBase< double, 3 >::setDistribution().
createOpalT() [1/2]
void Distribution::createOpalT (PartBunchBase< double, 3 > * beam, std::vector< Distribution *> addedDistributions, size_t & numberOfParticles)
Definition at line 1408 of file Distribution.cpp.
References addedDistributions_m.
Referenced by PartBunchBase< double, 3 >::setDistribution().
createOpalT() [2/2]
void Distribution::createOpalT (PartBunchBase< double, 3 > * beam, size_t & numberOfParticles)
Definition at line 1416 of file Distribution.cpp.
References addDistributions(), addedDistributions_m, additionalRNs_m, OpalData::addProblemCharacteristicValue(), ASTRA, ASTRAFLATTOPTH, avrgpz_m, calcPartPerDist(), checkEmissionParameters(), checkFileMomentum(), checkIfEmitted(), checkParticleNumber(), chooseInputMomentumUnits(), Util::convertMomentumEVoverCToBetaGamma(), create(), Options::cZero, PartBunchBase< T, Dim >::distrCreate_m, distrTypeT_m, emissionModel_m, emitting_m, end(), EVOVERC, fillEBinHistogram(), FROMFILE, OpalData::getInstance(), PartBunchBase< T, Dim >::getM(), getMaxTOrZ(), getMinTOrZ(), PartBunchBase< T, Dim >::getMomentumTolerance(), PartBunchBase< T, Dim >::getP(), PartBunchBase< T, Dim >::getQ(), Attributes::getReal(), GUNGAUSSFLATTOPTH, initializeBeam(), injectBeam(), inputMoUnits_m, Object::itsAttr, NONE, numberOfEnergyBins_m, Attrib::Distribution::OFFSETP, particlesPerDist_m, pmean_m, setDistType(), setEmissionTime(), setupEmissionModel(), setupEmissionModelNone(), setupEnergyBins(), shiftBeam(), shiftDistCoordinates(), IpplTimings::startTimer(), IpplTimings::stopTimer(), totalNumberParticles_m, and writeOutFileHeader().
doRestartOpalCycl()
void Distribution::doRestartOpalCycl (PartBunchBase< double, 3 > * p, size_t Np, int restartStep, const int specifiedNumBunch, H5PartWrapper * h5wrapper)
Definition at line 411 of file Distribution.cpp.
References OpalData::addProblemCharacteristicValue(), PartBunchBase< T, Dim >::boundp(), PartBunchBase< T, Dim >::create(), PartBunchBase< T, Dim >::distrReload_m, endl(), energyBins_m, Units::eV2MeV, PartBunchBase< T, Dim >::get_sPos(), PartBunchBase< T, Dim >::getChargePerParticle(), OpalData::getInstance(), PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getM(), IpplInfo::getNodes(), PartBunchBase< T, Dim >::getNumBunch(), H5PartWrapper::getNumParticles(), PartBunchBase< T, Dim >::getSteptoLastInj(), PartBunchBase< T, Dim >::getTotalNum(), INFOMSG, IpplInfo::myNode(), PartBunchBase< T, Dim >::P, PAssert_GE, pow(), H5PartWrapper::predecessorIsSameFlavour(), PartBunchBase< T, Dim >::Q, PartBunchBase< T, Dim >::R, H5PartWrapper::readHeader(), H5PartWrapper::readStep(), reduce(), PartBunchBase< T, Dim >::setPBins(), sqrt(), IpplTimings::startTimer(), and IpplTimings::stopTimer().
Referenced by TrackRun::setupCyclotronTracker().
doRestartOpalT()
void Distribution::doRestartOpalT (PartBunchBase< double, 3 > * p, size_t Np, int restartStep, H5PartWrapper * h5wrapper)
Definition at line 376 of file Distribution.cpp.
References OpalData::addProblemCharacteristicValue(), PartBunchBase< T, Dim >::boundp(), PartBunchBase< T, Dim >::create(), PartBunchBase< T, Dim >::distrReload_m, endl(), OpalData::getGlobalPhaseShift(), PartBunchBase< T, Dim >::getGlobalTrackStep(), OpalData::getInstance(), PartBunchBase< T, Dim >::getLocalTrackStep(), IpplInfo::getNodes(), H5PartWrapper::getNumParticles(), PartBunchBase< T, Dim >::getT(), PartBunchBase< T, Dim >::getTotalNum(), gmsg, IpplInfo::myNode(), PAssert_GE, H5PartWrapper::readHeader(), H5PartWrapper::readStep(), IpplTimings::startTimer(), and IpplTimings::stopTimer().
Referenced by TrackRun::setDistributionParallelT().
emitParticles()
size_t Distribution::emitParticles (PartBunchBase< double, 3 > * beam, double eZ)
Here we emit particles from the cathode.
A typical integration time step, \(\Delta t\), is broken down into 3 sub-steps:
1) Drift particles for \(\frac{\Delta t}{2}\).
2) Calculate fields and advance momentum.
3) Drift particles for \(\frac{\Delta t}{2}\) at the new momentum to complete the full time step.
The difficulty for emission is that at the cathode position there is a step function discontinuity in the fields. If we apply the typical integration time step across this boundary, we get an artificial numerical bunching of the beam, especially at very high accelerating fields. This function takes the cathode position boundary into account in order to achieve smoother particle emission.
During an emission step, an integral number of time bins from the distribution histogram are emitted. However, each particle contained in those time bins will actually be emitted from the cathode at a different time, so will only spend some fraction of the total time step, \(\Delta t_{full-timestep}\), in the simulation. The trick to emission is to give each particle a unique time step, \(Delta t_{temp}\), that is equal to the actual time during the emission step that the particle exists in the simulation. For the next integration time step, the particle's time step is set back to the global time step, \(\Delta t_{full-timestep}\).
Definition at line 1583 of file Distribution.cpp.
References additionalRNs_m, applyEmissionModel(), PartBunchBase< T, Dim >::Bf, PartBunchBase< T, Dim >::Bin, binWrite_m, Physics::c, cathodeFermiEnergy_m, cathodeWorkFunc_m, PartBunchBase< T, Dim >::create(), currentEmissionTime_m, currentEnergyBin_m, currentSampleBin_m, PartBunchBase< T, Dim >::dt, PartBunchBase< T, Dim >::Ef, emitting_m, endl(), Physics::epsilon_0, PartBunchBase< T, Dim >::getChargePerParticle(), PartBunchBase< T, Dim >::getdT(), PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getMassPerParticle(), PartBunchBase< T, Dim >::getPType(), PartBunchBase< T, Dim >::getQ(), INFOMSG, PartBunchBase< T, Dim >::iterateEmittedBin(), laserEnergy_m, level3(), PartBunchBase< T, Dim >::M, max(), numberOfEnergyBins_m, numberOfSampleBins_m, PartBunchBase< T, Dim >::P, Physics::pi, PartBunchBase< T, Dim >::POrigin, pow(), PartBunchBase< T, Dim >::PType, pxDist_m, pxWrite_m, pyDist_m, pyWrite_m, pzDist_m, pzWrite_m, PartBunchBase< T, Dim >::Q, Physics::q_e, PartBunchBase< T, Dim >::R, reduce(), REGULAR, sqrt(), tOrZDist_m, tOrZWrite_m, totalNumberEmittedParticles_m, PartBunchBase< T, Dim >::TriID, writeOutFileEmission(), xDist_m, xWrite_m, yDist_m, and yWrite_m.
Referenced by PartBunchBase< double, 3 >::emitParticles().
eraseBGxDist()
void Distribution::eraseBGxDist () private
Definition at line 1750 of file Distribution.cpp.
References pxDist_m.
eraseBGyDist()
void Distribution::eraseBGyDist () private
Definition at line 1758 of file Distribution.cpp.
References pyDist_m.
eraseBGzDist()
void Distribution::eraseBGzDist () private
Definition at line 1766 of file Distribution.cpp.
References pzDist_m.
eraseTOrZDist()
void Distribution::eraseTOrZDist () private
Definition at line 1762 of file Distribution.cpp.
References tOrZDist_m.
eraseXDist()
void Distribution::eraseXDist () private
Definition at line 1746 of file Distribution.cpp.
References xDist_m.
eraseYDist()
void Distribution::eraseYDist () private
Definition at line 1754 of file Distribution.cpp.
References yDist_m.
execute()
void Distribution::execute () virtual
Execute the command.
Reimplemented from Object.
Definition at line 249 of file Distribution.cpp.
fillEBinHistogram()
void Distribution::fillEBinHistogram () private
Definition at line 1788 of file Distribution.cpp.
References energyBinHist_m, reduce(), and tOrZDist_m.
Referenced by createOpalT().
fillParticleBins()
void Distribution::fillParticleBins () private
Definition at line 1807 of file Distribution.cpp.
References energyBins_m, PartBins::fill(), pxDist_m, pyDist_m, pzDist_m, PartBins::sortArray(), tOrZDist_m, xDist_m, and yDist_m.
Referenced by createOpalCycl().
find()
Distribution * Distribution::find (const std::string & name) static
Definition at line 492 of file Distribution.cpp.
References OpalData::find(), OpalData::getInstance(), and name.
Referenced by TrackRun::setDistributionParallelT(), and TrackRun::setupCyclotronTracker().
findEBin()
size_t Distribution::findEBin (double tOrZ) private
Definition at line 1828 of file Distribution.cpp.
References energyBinHist_m, numberOfEnergyBins_m, and numberOfSampleBins_m.
Referenced by injectBeam(), and writeOutFileInjection().
generateAstraFlattopT()
void Distribution::generateAstraFlattopT (size_t numberOfParticles) private
Definition at line 1841 of file Distribution.cpp.
References a, abs(), checkEmissionParameters(), Attributes::getBool(), IpplInfo::getNodes(), Attributes::getReal(), Object::itsAttr, IpplInfo::myNode(), Attrib::Distribution::NBIN, pzDist_m, randGen_m, Attrib::Legacy::Distribution::SBIN, Attrib::Distribution::SCALABLE, sqrt(), tBin_m, tEmission_m, tOrZDist_m, tPulseLengthFWHM_m, and tRise_m.
Referenced by generateFlattopLaserProfile(), and generateFlattopT().
generateBinomial()
void Distribution::generateBinomial (size_t numberOfParticles) private
Following W. Johos for his report TM-11-14
For the \(x,p_x\) phase space we have:
\[ \epsilon_x = \sigma_x \sigma_{p_x} \cos{(\arcsin{(\sigma_{12}) }) } \]
\begin{eqnarray*} \beta_x &=& \frac{\sigma_x^2}{\epsilon_x} \\ \gamma_x &=& \frac{\sigma_{p_x}^2}{\epsilon_x} \\ \alpha_x &=& -\sigma_{12} \sqrt{(\beta_x \gamma_x)} \\ \end{eqnarray*}
This holds similar for the other dimensions.
Definition at line 1952 of file Distribution.cpp.
References abs(), Physics::alpha, asin(), atan2(), avrgpz_m, copysign(), correlationMatrix_m, cos(), Attributes::getBool(), IpplInfo::getNodes(), Object::itsAttr, max(), mBinomial_m, IpplInfo::myNode(), PM, pow(), pxDist_m, pyDist_m, pzDist_m, randGen_m, Attrib::Distribution::SCALABLE, sigmaP_m, sigmaR_m, sin(), sqrt(), tOrZDist_m, Physics::two_pi, X, xDist_m, and yDist_m.
Referenced by createDistributionBinomial().
generateFlattopLaserProfile()
void Distribution::generateFlattopLaserProfile (size_t numberOfParticles) private
Definition at line 2087 of file Distribution.cpp.
References ASTRAFLATTOPTH, distrTypeT_m, generateAstraFlattopT(), generateLongFlattopT(), Attributes::getBool(), IpplInfo::getNodes(), LaserProfile::getXY(), Object::itsAttr, laserProfile_m, IpplInfo::myNode(), pxDist_m, pyDist_m, Attrib::Distribution::SCALABLE, sigmaR_m, xDist_m, and yDist_m.
Referenced by createDistributionFlattop().
generateFlattopT()
void Distribution::generateFlattopT (size_t numberOfParticles) private
Definition at line 2123 of file Distribution.cpp.
References ASTRAFLATTOPTH, distrTypeT_m, generateAstraFlattopT(), generateLongFlattopT(), Attributes::getBool(), IpplInfo::getNodes(), Object::itsAttr, IpplInfo::myNode(), pxDist_m, pyDist_m, Options::rngtype, sampleUniformDisk(), Attrib::Distribution::SCALABLE, selectRandomGenerator(), sigmaR_m, xDist_m, and yDist_m.
Referenced by createDistributionFlattop().
generateFlattopZ()
void Distribution::generateFlattopZ (size_t numberOfParticles) private
Definition at line 2165 of file Distribution.cpp.
References avrgpz_m, Attributes::getBool(), IpplInfo::getNodes(), Object::itsAttr, IpplInfo::myNode(), pxDist_m, pyDist_m, pzDist_m, randGen_m, Options::rngtype, sampleUniformDisk(), Attrib::Distribution::SCALABLE, selectRandomGenerator(), sigmaR_m, tOrZDist_m, xDist_m, and yDist_m.
Referenced by createDistributionFlattop().
generateGaussZ()
void Distribution::generateGaussZ (size_t numberOfParticles) private
Definition at line 2214 of file Distribution.cpp.
References abs(), avrgpz_m, correlationMatrix_m, cutoffP_m, cutoffR_m, endl(), Attributes::getBool(), IpplInfo::getNodes(), gmsg, Object::itsAttr, IpplInfo::myNode(), pow(), pxDist_m, pyDist_m, pzDist_m, randGen_m, Attrib::Distribution::SCALABLE, sigmaP_m, sigmaR_m, tOrZDist_m, xDist_m, and yDist_m.
Referenced by createDistributionGauss().
generateLongFlattopT()
void Distribution::generateLongFlattopT (size_t numberOfParticles) private
Definition at line 2500 of file Distribution.cpp.
References abs(), cutoffR_m, Attrib::Distribution::FTOSCAMPLITUDE, Attrib::Distribution::FTOSCPERIODS, Attributes::getBool(), IpplInfo::getNodes(), Attributes::getReal(), Object::itsAttr, log(), IpplInfo::myNode(), pzDist_m, randGen_m, Options::rngtype, Attrib::Distribution::SCALABLE, selectRandomGenerator(), sigmaTFall_m, sigmaTRise_m, sin(), sqrt(), tOrZDist_m, tPulseLengthFWHM_m, and Physics::two_pi.
Referenced by createDistributionGauss(), generateFlattopLaserProfile(), and generateFlattopT().
generateMatchedGauss()
void Distribution::generateMatchedGauss (const SigmaGenerator::matrix_t & sigma, size_t numberOfParticles, double massIneV) private
Definition at line 2370 of file Distribution.cpp.
References correlationMatrix_m, RealDiracMatrix::diagonalize(), E_m, Util::getBetaGamma(), Attributes::getBool(), IpplInfo::getNodes(), inputMoUnits_m, Object::itsAttr, IpplInfo::myNode(), NONE, prod(), pxDist_m, pyDist_m, pzDist_m, randGen_m, Attrib::Distribution::SCALABLE, sigmaP_m, sigmaR_m, sqrt(), tOrZDist_m, xDist_m, and yDist_m.
Referenced by createMatchedGaussDistribution().
generateTransverseGauss()
void Distribution::generateTransverseGauss (size_t numberOfParticles) private
Definition at line 2642 of file Distribution.cpp.
References correlationMatrix_m, cutoffP_m, cutoffR_m, Attributes::getBool(), IpplInfo::getNodes(), Object::itsAttr, IpplInfo::myNode(), pow(), pxDist_m, pyDist_m, randGen_m, Attrib::Distribution::SCALABLE, sigmaP_m, sigmaR_m, xDist_m, and yDist_m.
Referenced by createDistributionGauss().
get_pmean()
Vector_t Distribution::get_pmean () const inline
Definition at line 501 of file Distribution.h.
References pmean_m.
Referenced by PartBunchBase< double, 3 >::get_pmean_Distribution().
getBGxDist()
std::vector< double > & Distribution::getBGxDist () private
Definition at line 2861 of file Distribution.cpp.
References pxDist_m.
getBGyDist()
std::vector< double > & Distribution::getBGyDist () private
Definition at line 2869 of file Distribution.cpp.
References pyDist_m.
getBGzDist()
std::vector< double > & Distribution::getBGzDist () private
Definition at line 2877 of file Distribution.cpp.
References pzDist_m.
getEmissionDeltaT()
double Distribution::getEmissionDeltaT ()
Definition at line 2845 of file Distribution.cpp.
References numberOfSampleBins_m, and tBin_m.
Referenced by PartBunchBase< double, 3 >::getEmissionDeltaT().
getEmissionTimeShift()
double Distribution::getEmissionTimeShift () const
Definition at line 4120 of file Distribution.cpp.
References emitting_m, Attributes::getReal(), Object::itsAttr, and Attrib::Distribution::OFFSETT.
Referenced by TrackRun::setDistributionParallelT().
getEnergyBinDeltaT()
double Distribution::getEnergyBinDeltaT ()
Definition at line 2849 of file Distribution.cpp.
References tBin_m.
getIfDistEmitting()
bool Distribution::getIfDistEmitting ()
Definition at line 2803 of file Distribution.cpp.
References emitting_m.
Referenced by PartBunchBase< double, 3 >::doEmission(), PartBunchBase< double, 3 >::getIfBeamEmitting(), and PartBunchBase< double, 3 >::Rebin().
getLastEmittedEnergyBin()
int Distribution::getLastEmittedEnergyBin ()
Definition at line 2807 of file Distribution.cpp.
References currentEnergyBin_m.
Referenced by PartBunchBase< double, 3 >::boundp_destroyT(), PartBunchBase< double, 3 >::destroyT(), and PartBunchBase< double, 3 >::getLastEmittedEnergyBin().
getMaxTOrZ()
double Distribution::getMaxTOrZ ()
Definition at line 2811 of file Distribution.cpp.
References min(), reduce(), and tOrZDist_m.
Referenced by createOpalT().
getMinTOrZ()
double Distribution::getMinTOrZ ()
Definition at line 2824 of file Distribution.cpp.
References max(), reduce(), and tOrZDist_m.
Referenced by createOpalT().
getNumberOfEmissionSteps()
size_t Distribution::getNumberOfEmissionSteps ()
Definition at line 2837 of file Distribution.cpp.
References numberOfEnergyBins_m, and numberOfSampleBins_m.
Referenced by PartBunchBase< double, 3 >::getNumberOfEmissionSteps().
getNumberOfEnergyBins()
int Distribution::getNumberOfEnergyBins ()
Definition at line 2841 of file Distribution.cpp.
References numberOfEnergyBins_m.
Referenced by PartBunchBase< double, 3 >::calcGammas(), PartBunchBase< double, 3 >::getNumberOfEnergyBins(), and PartBunchBase< double, 3 >::weHaveEnergyBins().
getNumberOfParticlesInFile()
size_t Distribution::getNumberOfParticlesInFile (std::ifstream & inputFile) private
Definition at line 1004 of file Distribution.cpp.
References Attrib::Distribution::FNAME, Attributes::getString(), Object::itsAttr, IpplInfo::myNode(), and reduce().
Referenced by calcPartPerDist(), and createDistributionFromFile().
getNumOfLocalParticlesToCreate()
size_t Distribution::getNumOfLocalParticlesToCreate (size_t n)
Calculate the local number of particles evenly and adjust node 0 such that n is matched exactly.
Parameters
n total number of particles
Returns
n / #cores
Parameters
Definition at line 227 of file Distribution.cpp.
References IpplInfo::getNodes(), IpplInfo::myNode(), and Hypervolume::n.
Referenced by create().
getPercentageEmitted()
double Distribution::getPercentageEmitted () const inline
Definition at line 511 of file Distribution.h.
References totalNumberEmittedParticles_m, and totalNumberParticles_m.
Referenced by PartBunchBase< double, 3 >::boundp().
getTEmission()
double Distribution::getTEmission ()
Definition at line 502 of file Distribution.cpp.
References a, ASTRAFLATTOPTH, Attrib::Legacy::Distribution::CUTOFF, cutoff_m, distrTypeT_m, Attributes::getReal(), GUNGAUSSFLATTOPTH, Object::itsAttr, log(), setDistType(), sigmaFall_m, sigmaRise_m, sqrt(), tEmission_m, Attrib::Distribution::TFALL, tFall_m, Attrib::Distribution::TPULSEFWHM, tPulseLengthFWHM_m, Attrib::Distribution::TRISE, and tRise_m.
Referenced by TrackRun::setDistributionParallelT().
getTOrZDist()
std::vector< double > & Distribution::getTOrZDist () private
Definition at line 2873 of file Distribution.cpp.
References tOrZDist_m.
getType()
DistributionType Distribution::getType () const inline
Definition at line 506 of file Distribution.h.
References distrTypeT_m.
Referenced by PartBunchBase< double, 3 >::getDistType().
getTypeofDistribution()
std::string Distribution::getTypeofDistribution () inline
Definition at line 516 of file Distribution.h.
References distT_m.
getWeight()
double Distribution::getWeight ()
Definition at line 2853 of file Distribution.cpp.
References abs(), Attributes::getReal(), Object::itsAttr, and Attrib::Distribution::WEIGHT.
Referenced by calcPartPerDist().
getXDist()
std::vector< double > & Distribution::getXDist () private
Definition at line 2857 of file Distribution.cpp.
References xDist_m.
getYDist()
std::vector< double > & Distribution::getYDist () private
Definition at line 2865 of file Distribution.cpp.
References yDist_m.
initializeBeam()
void Distribution::initializeBeam (PartBunchBase< double, 3 > * beam) private
Definition at line 2725 of file Distribution.cpp.
References numberOfEnergyBins_m, PartBunchBase< T, Dim >::setEnergyBins(), PartBunchBase< T, Dim >::setNumBunch(), PartBunchBase< T, Dim >::setTEmission(), and tEmission_m.
Referenced by createOpalCycl(), and createOpalT().
injectBeam()
void Distribution::injectBeam (PartBunchBase< double, 3 > * beam) private
Definition at line 2737 of file Distribution.cpp.
References PartBunchBase< T, Dim >::Bf, PartBunchBase< T, Dim >::Bin, PartBunchBase< T, Dim >::boundp(), PartBunchBase< T, Dim >::calcEMean(), PartBunchBase< T, Dim >::create(), PartBunchBase< T, Dim >::Ef, endl(), findEBin(), PartBunchBase< T, Dim >::getChargePerParticle(), PartBunchBase< T, Dim >::getMassPerParticle(), PartBunchBase< T, Dim >::getPType(), Attributes::getRealArray(), gmsg, PartBunchBase< T, Dim >::ID, Attrib::Distribution::ID1, Attrib::Distribution::ID2, PartBunchBase< T, Dim >::iterateEmittedBin(), Object::itsAttr, PartBunchBase< T, Dim >::M, numberOfEnergyBins_m, PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::POrigin, PartBunchBase< T, Dim >::PType, pxDist_m, pyDist_m, pzDist_m, PartBunchBase< T, Dim >::Q, PartBunchBase< T, Dim >::R, REGULAR, tOrZDist_m, PartBunchBase< T, Dim >::TriID, writeOutFileInjection(), xDist_m, and yDist_m.
Referenced by createOpalCycl(), and createOpalT().
operator=()
void Distribution::operator= (const Distribution &) private delete
printDist()
void Distribution::printDist (Inform & os, size_t numberOfParticles) const private
Definition at line 2881 of file Distribution.cpp.
References ASTRAFLATTOPTH, BINOMIAL, Options::cZero, distrTypeT_m, endl(), EVOVERC, FLATTOP, FROMFILE, GAUSS, GUNGAUSSFLATTOPTH, inputMoUnits_m, MATCHEDGAUSS, MULTIGAUSS, NONE, printDistBinomial(), printDistFlattop(), printDistFromFile(), printDistGauss(), printDistMatchedGauss(), printDistMultiGauss(), and reduce().
Referenced by printInfo().
printDistBinomial()
void Distribution::printDistBinomial (Inform & os) const private
Definition at line 2934 of file Distribution.cpp.
References correlationMatrix_m, emitting_m, endl(), mBinomial_m, sigmaP_m, and sigmaR_m.
Referenced by printDist().
printDistFlattop()
void Distribution::printDistFlattop (Inform & os) const private
Definition at line 2962 of file Distribution.cpp.
References abs(), ASTRAFLATTOPTH, cutoffR_m, distrTypeT_m, emitting_m, endl(), Attrib::Distribution::FTOSCAMPLITUDE, Attrib::Distribution::FTOSCPERIODS, Attributes::getReal(), GUNGAUSSFLATTOPTH, Object::itsAttr, laserImageName_m, laserIntensityCut_m, laserProfile_m, laserProfileFileName_m, sigmaR_m, sigmaTFall_m, sigmaTRise_m, tPulseLengthFWHM_m, and tRise_m.
Referenced by printDist().
printDistFromFile()
void Distribution::printDistFromFile (Inform & os) const private
Definition at line 3057 of file Distribution.cpp.
References endl(), Attrib::Distribution::FNAME, Attributes::getString(), and Object::itsAttr.
Referenced by printDist().
printDistGauss()
void Distribution::printDistGauss (Inform & os) const private
Definition at line 3090 of file Distribution.cpp.
References abs(), avrgpz_m, correlationMatrix_m, cutoffP_m, cutoffR_m, emitting_m, endl(), Attrib::Distribution::FTOSCAMPLITUDE, Attrib::Distribution::FTOSCPERIODS, Attributes::getReal(), Object::itsAttr, sigmaP_m, sigmaR_m, sigmaTFall_m, sigmaTRise_m, and tPulseLengthFWHM_m.
Referenced by printDist().
printDistMatchedGauss()
void Distribution::printDistMatchedGauss (Inform & os) const private
Definition at line 3065 of file Distribution.cpp.
References correlationMatrix_m, endl(), sigmaP_m, and sigmaR_m.
Referenced by printDist().
printDistMultiGauss()
void Distribution::printDistMultiGauss (Inform & os) const private
Definition at line 3027 of file Distribution.cpp.
References cutoffP_m, cutoffR_m, emitting_m, endl(), nPeaks_m, sepPeaks_m, sigmaP_m, and sigmaR_m.
Referenced by printDist().
printEmissionModel()
void Distribution::printEmissionModel (Inform & os) const private
Definition at line 3149 of file Distribution.cpp.
References ASTRA, emissionModel_m, endl(), NONE, NONEQUIL, printEmissionModelAstra(), printEmissionModelNone(), and printEmissionModelNonEquil().
Referenced by printInfo().
printEmissionModelAstra()
void Distribution::printEmissionModelAstra (Inform & os) const private
Definition at line 3172 of file Distribution.cpp.
References abs(), Attrib::Distribution::EKIN, endl(), Attributes::getReal(), and Object::itsAttr.
Referenced by printEmissionModel().
printEmissionModelNone()
void Distribution::printEmissionModelNone (Inform & os) const private
Definition at line 3179 of file Distribution.cpp.
References abs(), Attrib::Distribution::EKIN, endl(), Attributes::getReal(), and Object::itsAttr.
Referenced by printEmissionModel().
printEmissionModelNonEquil()
void Distribution::printEmissionModelNonEquil (Inform & os) const private
Definition at line 3186 of file Distribution.cpp.
References cathodeFermiEnergy_m, cathodeTemp_m, cathodeWorkFunc_m, endl(), Physics::kB, and laserEnergy_m.
Referenced by printEmissionModel().
printEnergyBins()
void Distribution::printEnergyBins (Inform & os) const private
Definition at line 3194 of file Distribution.cpp.
References endl(), energyBinHist_m, numberOfEnergyBins_m, numberOfSampleBins_m, and sum().
printInfo()
Inform & Distribution::printInfo (Inform & os) const
Definition at line 546 of file Distribution.cpp.
References addedDistributions_m, emitting_m, endl(), Attributes::getBool(), OpalData::getInstance(), Object::itsAttr, numberOfEnergyBins_m, numberOfSampleBins_m, outFilename_m, particlesPerDist_m, printDist(), printEmissionModel(), tBin_m, tEmission_m, and Attrib::Distribution::WRITETOFILE.
Referenced by operator<<().
Rebin()
bool Distribution::Rebin ()
Definition at line 3210 of file Distribution.cpp.
References emitting_m, and numberOfEnergyBins_m.
Referenced by PartBunchBase< double, 3 >::Rebin().
reflectDistribution()
void Distribution::reflectDistribution (size_t & numberOfParticles) private
Definition at line 3223 of file Distribution.cpp.
References Options::cZero, distrTypeT_m, FROMFILE, IpplInfo::myNode(), pxDist_m, pyDist_m, pzDist_m, reduce(), tOrZDist_m, xDist_m, and yDist_m.
Referenced by create().
sampleUniformDisk()
void Distribution::sampleUniformDisk (gsl_qrng * quasiRandGen2D, double & x1, double & x2) private
Definition at line 1770 of file Distribution.cpp.
References pow(), and randGen_m.
Referenced by createDistributionMultiGauss(), generateFlattopT(), and generateFlattopZ().
scaleDistCoordinates()
void Distribution::scaleDistCoordinates () private
Definition at line 3252 of file Distribution.cpp.
References emitting_m, Attributes::getReal(), Object::itsAttr, pxDist_m, Attrib::Distribution::PXMULT, pyDist_m, Attrib::Distribution::PYMULT, pzDist_m, Attrib::Distribution::PZMULT, Attrib::Distribution::TMULT, tOrZDist_m, xDist_m, Attrib::Distribution::XMULT, yDist_m, Attrib::Distribution::YMULT, and Attrib::Distribution::ZMULT.
Referenced by create().
selectRandomGenerator()
gsl_qrng * Distribution::selectRandomGenerator (std::string , unsigned int dimension) private
Select and allocate gsl random number generator.
Definition at line 3274 of file Distribution.cpp.
References endl(), INFOMSG, and Options::rngtype.
Referenced by createDistributionMultiGauss(), generateFlattopT(), generateFlattopZ(), and generateLongFlattopT().
setAttributes()
void Distribution::setAttributes () private
Definition at line 3293 of file Distribution.cpp.
References Attrib::Distribution::CATHTEMP, Attrib::Distribution::CORRT, Attrib::Distribution::CORRX, Attrib::Distribution::CORRY, Attrib::Distribution::CORRZ, Attrib::Legacy::Distribution::CUTOFF, Attrib::Distribution::CUTOFFLONG, Attrib::Distribution::CUTOFFPX, Attrib::Distribution::CUTOFFPY, Attrib::Distribution::CUTOFFPZ, Attrib::Distribution::CUTOFFR, Attrib::Distribution::CUTOFFX, Attrib::Distribution::CUTOFFY, Attrib::Distribution::DENERGY, Attrib::Legacy::Distribution::DISTRIBUTION, Physics::e, Attrib::Distribution::EKIN, Attrib::Distribution::ELASER, Attrib::Distribution::EMISSIONMODEL, Attrib::Distribution::EMISSIONSTEPS, Attrib::Distribution::EMITTED, Attrib::Distribution::ET, Attrib::Distribution::EX, Attrib::Distribution::EY, Attrib::Distribution::FE, Attrib::Distribution::FLIPX, Attrib::Distribution::FLIPY, Attrib::Distribution::FNAME, Attrib::Distribution::FTOSCAMPLITUDE, Attrib::Distribution::FTOSCPERIODS, Attrib::Distribution::ID1, Attrib::Distribution::ID2, Attrib::Distribution::IMAGENAME, Attrib::Distribution::INPUTMOUNITS, Attrib::Distribution::INTENSITYCUT, Object::itsAttr, Attrib::Distribution::LASERPROFFN, Attrib::Distribution::LINE, Attributes::makeBool(), Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeRealArray(), Attributes::makeString(), Attrib::Distribution::MAXSTEPSCO, Attrib::Distribution::MAXSTEPSSI, Attrib::Distribution::MT, Attrib::Distribution::MX, Attrib::Distribution::MY, Attrib::Distribution::MZ, Attrib::Distribution::NBIN, Attrib::Distribution::NPEAKS, Attrib::Distribution::NSECTORS, Attrib::Distribution::NSTEPS, Attrib::Distribution::OFFSETP, Attrib::Distribution::OFFSETPX, Attrib::Distribution::OFFSETPY, Attrib::Distribution::OFFSETPZ, Attrib::Distribution::OFFSETT, Attrib::Distribution::OFFSETX, Attrib::Distribution::OFFSETY, Attrib::Distribution::OFFSETZ, Attrib::Distribution::ORDERMAPS, Attrib::Legacy::Distribution::PT, Attrib::Distribution::PXMULT, Attrib::Distribution::PYMULT, Attrib::Distribution::PZMULT, Attrib::Distribution::R, Attrib::Distribution::R51, Attrib::Distribution::R52, Attrib::Distribution::R61, Attrib::Distribution::R62, Object::registerOwnership(), Attrib::Distribution::RESIDUUM, Attrib::Distribution::RGUESS, Attrib::Distribution::ROTATE180, Attrib::Distribution::ROTATE270, Attrib::Distribution::ROTATE90, Attrib::Legacy::Distribution::SBIN, Attrib::Distribution::SCALABLE, Attrib::Distribution::SECTOR, Attrib::Distribution::SEPPEAKS, Attrib::Legacy::Distribution::SIGMAPT, Attrib::Distribution::SIGMAPX, Attrib::Distribution::SIGMAPY, Attrib::Distribution::SIGMAPZ, Attrib::Distribution::SIGMAR, Attrib::Distribution::SIGMAT, Attrib::Distribution::SIGMAX, Attrib::Distribution::SIGMAY, Attrib::Distribution::SIGMAZ, AttributeHandler::STATEMENT, Attrib::Legacy::Distribution::T, Attrib::Distribution::TFALL, Attrib::Distribution::TMULT, Attrib::Distribution::TPULSEFWHM, Attrib::Distribution::TRISE, Attrib::Distribution::TYPE, Attrib::Distribution::W, Attrib::Distribution::WEIGHT, Attrib::Distribution::WRITETOFILE, Attrib::Distribution::XMULT, Attrib::Distribution::YMULT, and Attrib::Distribution::ZMULT.
Referenced by Distribution().
setDistParametersBinomial()
void Distribution::setDistParametersBinomial (double massIneV) private
Definition at line 3712 of file Distribution.cpp.
References abs(), correlationMatrix_m, Attrib::Distribution::CORRT, Attrib::Distribution::CORRX, Attrib::Distribution::CORRY, Attrib::Distribution::CORRZ, Attrib::Distribution::CUTOFFLONG, cutoffP_m, Attrib::Distribution::CUTOFFPX, Attrib::Distribution::CUTOFFPY, Attrib::Distribution::CUTOFFPZ, cutoffR_m, Attrib::Distribution::CUTOFFX, Attrib::Distribution::CUTOFFY, emitting_m, Attributes::getReal(), Attributes::getRealArray(), Object::itsAttr, mBinomial_m, Attrib::Distribution::MT, Attrib::Distribution::MX, Attrib::Distribution::MY, Attrib::Distribution::MZ, Attrib::Distribution::R, Attrib::Distribution::R51, Attrib::Distribution::R52, Attrib::Distribution::R61, Attrib::Distribution::R62, setSigmaP_m(), and setSigmaR_m().
Referenced by createDistributionBinomial().
setDistParametersFlattop()
void Distribution::setDistParametersFlattop (double massIneV) private
Definition at line 3763 of file Distribution.cpp.
References abs(), ASTRAFLATTOPTH, correlationMatrix_m, Attrib::Distribution::CORRT, Attrib::Distribution::CORRX, Attrib::Distribution::CORRY, Attrib::Distribution::CORRZ, Attrib::Distribution::CUTOFFLONG, cutoffR_m, Attrib::Distribution::CUTOFFX, Attrib::Distribution::CUTOFFY, distrTypeT_m, emitting_m, LaserProfile::FLIPX, Attrib::Distribution::FLIPX, LaserProfile::FLIPY, Attrib::Distribution::FLIPY, Attributes::getBool(), Attributes::getReal(), Attributes::getString(), Attrib::Distribution::IMAGENAME, Attrib::Distribution::INTENSITYCUT, Object::itsAttr, laserImageName_m, laserIntensityCut_m, Attrib::Distribution::LASERPROFFN, laserProfile_m, laserProfileFileName_m, log(), LaserProfile::ROTATE180, Attrib::Distribution::ROTATE180, LaserProfile::ROTATE270, Attrib::Distribution::ROTATE270, LaserProfile::ROTATE90, Attrib::Distribution::ROTATE90, setSigmaP_m(), setSigmaR_m(), sigmaR_m, Attrib::Distribution::SIGMAT, sigmaTFall_m, sigmaTRise_m, sqrt(), Attrib::Distribution::TFALL, Attrib::Distribution::TPULSEFWHM, tPulseLengthFWHM_m, Attrib::Distribution::TRISE, and tRise_m.
Referenced by createDistributionFlattop().
setDistParametersGauss()
void Distribution::setDistParametersGauss (double massIneV) private
Definition at line 3855 of file Distribution.cpp.
References abs(), correlationMatrix_m, Attrib::Distribution::CORRT, Attrib::Distribution::CORRX, Attrib::Distribution::CORRY, Attrib::Distribution::CORRZ, Attrib::Distribution::CUTOFFLONG, cutoffP_m, Attrib::Distribution::CUTOFFPX, Attrib::Distribution::CUTOFFPY, Attrib::Distribution::CUTOFFPZ, Attrib::Distribution::CUTOFFR, cutoffR_m, Attrib::Distribution::CUTOFFX, Attrib::Distribution::CUTOFFY, distrTypeT_m, emitting_m, endl(), Attributes::getReal(), Attributes::getRealArray(), gmsg, Object::itsAttr, log(), MATCHEDGAUSS, max(), Attrib::Distribution::R, Attrib::Distribution::R51, Attrib::Distribution::R52, Attrib::Distribution::R61, Attrib::Distribution::R62, setSigmaP_m(), setSigmaR_m(), Attrib::Distribution::SIGMAR, sigmaR_m, Attrib::Distribution::SIGMAT, sigmaTFall_m, sigmaTRise_m, SMALLESTCUTOFF, sqrt(), Attrib::Distribution::TFALL, Attrib::Distribution::TPULSEFWHM, tPulseLengthFWHM_m, and Attrib::Distribution::TRISE.
Referenced by createDistributionGauss().
setDistParametersMultiGauss()
void Distribution::setDistParametersMultiGauss (double massIneV) private
Definition at line 3839 of file Distribution.cpp.
References abs(), Attrib::Distribution::CUTOFFLONG, cutoffP_m, Attrib::Distribution::CUTOFFPX, Attrib::Distribution::CUTOFFPY, Attrib::Distribution::CUTOFFPZ, cutoffR_m, emitting_m, Attributes::getReal(), Object::itsAttr, Attrib::Distribution::NPEAKS, nPeaks_m, Attrib::Distribution::SEPPEAKS, sepPeaks_m, setSigmaP_m(), and setSigmaR_m().
Referenced by createDistributionMultiGauss().
setDistToEmitted()
void Distribution::setDistToEmitted (bool emitted)
Definition at line 3599 of file Distribution.cpp.
References emitting_m.
setDistType()
void Distribution::setDistType ()
Definition at line 3603 of file Distribution.cpp.
References ASTRAFLATTOPTH, BINOMIAL, Attrib::Legacy::Distribution::DISTRIBUTION, distrTypeT_m, distT_m, FLATTOP, FROMFILE, GAUSS, Attributes::getString(), GUNGAUSSFLATTOPTH, Object::itsAttr, MATCHEDGAUSS, MULTIGAUSS, NODIST, and Attrib::Distribution::TYPE.
Referenced by createOpalCycl(), createOpalT(), and getTEmission().
setEmissionTime()
void Distribution::setEmissionTime (double & maxT, double & minT) private
Definition at line 3664 of file Distribution.cpp.
References addedDistributions_m, ASTRAFLATTOPTH, cutoffR_m, distrTypeT_m, FLATTOP, GAUSS, GUNGAUSSFLATTOPTH, log(), numberOfEnergyBins_m, percentTEmission_m, sigmaTFall_m, sigmaTRise_m, sqrt(), tBin_m, tEmission_m, and tPulseLengthFWHM_m.
Referenced by createOpalT().
setNumberOfDistributions()
void Distribution::setNumberOfDistributions (unsigned int n) inline
Definition at line 241 of file Distribution.h.
References Hypervolume::n, and numberOfDistributions_m.
Referenced by TrackRun::setDistributionParallelT().
setSigmaP_m()
void Distribution::setSigmaP_m (double massIneV)
Definition at line 3644 of file Distribution.cpp.
References abs(), Util::convertMomentumEVoverCToBetaGamma(), endl(), EVOVERC, Attributes::getReal(), inputMoUnits_m, Object::itsAttr, sigmaP_m, Attrib::Legacy::Distribution::SIGMAPT, Attrib::Distribution::SIGMAPX, Attrib::Distribution::SIGMAPY, Attrib::Distribution::SIGMAPZ, and WARNMSG.
Referenced by setDistParametersBinomial(), setDistParametersFlattop(), setDistParametersGauss(), and setDistParametersMultiGauss().
setSigmaR_m()
void Distribution::setSigmaR_m ()
Definition at line 3630 of file Distribution.cpp.
References abs(), Attributes::getReal(), Object::itsAttr, Attrib::Distribution::SIGMAR, sigmaR_m, Attrib::Distribution::SIGMAT, Attrib::Distribution::SIGMAX, Attrib::Distribution::SIGMAY, and Attrib::Distribution::SIGMAZ.
Referenced by setDistParametersBinomial(), setDistParametersFlattop(), setDistParametersGauss(), and setDistParametersMultiGauss().
setupEmissionModel()
void Distribution::setupEmissionModel (PartBunchBase< double, 3 > * beam) private
Definition at line 3958 of file Distribution.cpp.
References ASTRA, ASTRAFLATTOPTH, distrTypeT_m, Attrib::Distribution::EMISSIONMODEL, emissionModel_m, Attributes::getString(), GUNGAUSSFLATTOPTH, Object::itsAttr, NONE, NONEQUIL, setupEmissionModelAstra(), and setupEmissionModelNonEquil().
Referenced by createOpalT().
setupEmissionModelAstra()
void Distribution::setupEmissionModelAstra (PartBunchBase< double, 3 > * beam) private
Definition at line 3997 of file Distribution.cpp.
References abs(), Attrib::Distribution::EKIN, Util::getBetaGamma(), PartBunchBase< T, Dim >::getM(), Attributes::getReal(), Object::itsAttr, pmean_m, and pTotThermal_m.
Referenced by setupEmissionModel().
setupEmissionModelNone()
void Distribution::setupEmissionModelNone (PartBunchBase< double, 3 > * beam) private
Definition at line 4004 of file Distribution.cpp.
References abs(), Attrib::Distribution::EKIN, Util::getBetaGamma(), PartBunchBase< T, Dim >::getM(), Attributes::getReal(), Object::itsAttr, pmean_m, pTotThermal_m, pzDist_m, and reduce().
Referenced by createOpalT().
setupEmissionModelNonEquil()
void Distribution::setupEmissionModelNonEquil () private
Definition at line 4017 of file Distribution.cpp.
References abs(), cathodeFermiEnergy_m, cathodeTemp_m, cathodeWorkFunc_m, Attrib::Distribution::CATHTEMP, Attrib::Distribution::ELASER, emitEnergyUpperLimit_m, Attrib::Distribution::FE, Attributes::getReal(), Units::GeV2eV, Object::itsAttr, Physics::kB, laserEnergy_m, log(), Physics::m_e, pmean_m, pow(), sqrt(), and Attrib::Distribution::W.
Referenced by setupEmissionModel().
setupEnergyBins()
void Distribution::setupEnergyBins (double maxTOrZ, double minTOrZ) private
Definition at line 4035 of file Distribution.cpp.
References emitting_m, energyBinHist_m, numberOfEnergyBins_m, numberOfSampleBins_m, and tEmission_m.
Referenced by createOpalT().
setupParticleBins()
void Distribution::setupParticleBins (double massIneV, PartBunchBase< double, 3 > * beam) private
Definition at line 4046 of file Distribution.cpp.
References abs(), energyBins_m, PartBunchBase< T, Dim >::getM(), PartBunchBase< T, Dim >::getP(), Attributes::getReal(), Object::itsAttr, Attrib::Distribution::NBIN, numberOfEnergyBins_m, Attrib::Legacy::Distribution::PT, Attrib::Legacy::Distribution::SBIN, and PartBins::setGamma().
Referenced by createOpalCycl().
shiftBeam()
void Distribution::shiftBeam (double & maxTOrZ, double & minTOrZ)
Definition at line 4071 of file Distribution.cpp.
References addedDistributions_m, ASTRAFLATTOPTH, distrTypeT_m, emitting_m, FLATTOP, FROMFILE, GAUSS, GUNGAUSSFLATTOPTH, reduce(), tEmission_m, and tOrZDist_m.
Referenced by createOpalT().
shiftDistCoordinates()
void Distribution::shiftDistCoordinates (double massIneV) private
Definition at line 4127 of file Distribution.cpp.
References addedDistributions_m, Util::convertMomentumEVoverCToBetaGamma(), emitting_m, endl(), EVOVERC, Attributes::getReal(), inputMoUnits_m, Object::itsAttr, Attrib::Distribution::OFFSETPX, Attrib::Distribution::OFFSETPY, Attrib::Distribution::OFFSETPZ, Attrib::Distribution::OFFSETX, Attrib::Distribution::OFFSETY, Attrib::Distribution::OFFSETZ, particlesPerDist_m, Attrib::Legacy::Distribution::PT, pxDist_m, pyDist_m, pzDist_m, Attrib::Legacy::Distribution::T, tOrZDist_m, WARNMSG, xDist_m, and yDist_m.
Referenced by createOpalCycl(), and createOpalT().
update()
void Distribution::update () virtual
Update this object.
Reimplemented from Object.
Definition at line 252 of file Distribution.cpp.
writeOutFileEmission()
void Distribution::writeOutFileEmission () private
Definition at line 4235 of file Distribution.cpp.
References Communicate::barrier(), binWrite_m, IpplInfo::Comm, Communicate::COMM_ANY_NODE, endl(), ERRORMSG, Attributes::getBool(), IpplInfo::getComm(), IpplInfo::getNodes(), IPPL_APP_CYCLE, IPPL_APP_TAG2, Object::itsAttr, level1(), IpplInfo::myNode(), TagMaker::next_tag(), outFilename_m, pxWrite_m, pyWrite_m, pzWrite_m, Communicate::raw_probe_receive(), Communicate::raw_receive(), Communicate::raw_send(), tOrZWrite_m, Attrib::Distribution::WRITETOFILE, xWrite_m, and yWrite_m.
Referenced by emitParticles().
writeOutFileHeader()
void Distribution::writeOutFileHeader () private
Definition at line 4180 of file Distribution.cpp.
References Util::combineFilePath(), emitting_m, endl(), OpalData::getAuxiliaryOutputDirectory(), Attributes::getBool(), OpalData::getInputBasename(), OpalData::getInstance(), Object::getOpalName(), gmsg, Object::itsAttr, IpplInfo::myNode(), numberOfEnergyBins_m, outFilename_m, reduce(), Inform::setf(), tOrZDist_m, Inform::width(), and Attrib::Distribution::WRITETOFILE.
Referenced by createOpalCycl(), and createOpalT().
writeOutFileInjection()
void Distribution::writeOutFileInjection () private
Definition at line 4359 of file Distribution.cpp.
References endl(), findEBin(), Attributes::getBool(), IpplInfo::getNodes(), gmsg, Object::itsAttr, IpplInfo::myNode(), numberOfEnergyBins_m, outFilename_m, Inform::precision(), pxDist_m, pyDist_m, pzDist_m, reduce(), tOrZDist_m, Attrib::Distribution::WRITETOFILE, xDist_m, and yDist_m.
Referenced by injectBeam().
Member Data Documentation
addedDistributions_m
std::vector<Distribution *> Distribution::addedDistributions_m private
Vector of distributions to be added to this distribution.
Reference data for particle type (charge, mass etc.)
Definition at line 398 of file Distribution.h.
Referenced by addDistributions(), calcPartPerDist(), createOpalT(), printInfo(), setEmissionTime(), shiftBeam(), and shiftDistCoordinates().
additionalRNs_m
std::vector<std::vector<double> > Distribution::additionalRNs_m private
Upper limit on emission energy distribution (eV).
Definition at line 435 of file Distribution.h.
Referenced by create(), createOpalT(), and emitParticles().
avrgpz_m
double Distribution::avrgpz_m private
Definition at line 458 of file Distribution.h.
Referenced by adjustPhaseSpace(), checkFileMomentum(), createDistributionMultiGauss(), createOpalT(), generateBinomial(), generateFlattopZ(), generateGaussZ(), and printDistGauss().
binWrite_m
std::vector<size_t> Distribution::binWrite_m private
Definition at line 455 of file Distribution.h.
Referenced by emitParticles(), and writeOutFileEmission().
cathodeFermiEnergy_m
double Distribution::cathodeFermiEnergy_m private
Laser photon energy (eV).
Definition at line 431 of file Distribution.h.
Referenced by applyEmissModelNonEquil(), emitParticles(), printEmissionModelNonEquil(), and setupEmissionModelNonEquil().
cathodeTemp_m
double Distribution::cathodeTemp_m private
Cathode material Fermi energy (eV).
Definition at line 432 of file Distribution.h.
Referenced by applyEmissModelNonEquil(), printEmissionModelNonEquil(), and setupEmissionModelNonEquil().
cathodeWorkFunc_m
double Distribution::cathodeWorkFunc_m private
Definition at line 429 of file Distribution.h.
Referenced by emitParticles(), printEmissionModelNonEquil(), and setupEmissionModelNonEquil().
correlationMatrix_m
matrix_t Distribution::correlationMatrix_m private
Definition at line 470 of file Distribution.h.
Referenced by generateBinomial(), generateGaussZ(), generateMatchedGauss(), generateTransverseGauss(), printDistBinomial(), printDistGauss(), printDistMatchedGauss(), setDistParametersBinomial(), setDistParametersFlattop(), and setDistParametersGauss().
currentEmissionTime_m
double Distribution::currentEmissionTime_m private
Definition at line 411 of file Distribution.h.
Referenced by emitParticles().
currentEnergyBin_m
int Distribution::currentEnergyBin_m private
Definition at line 412 of file Distribution.h.
Referenced by checkEmissionParameters(), emitParticles(), and getLastEmittedEnergyBin().
currentSampleBin_m
int Distribution::currentSampleBin_m private
Definition at line 413 of file Distribution.h.
Referenced by checkEmissionParameters(), and emitParticles().
cutoff_m
double Distribution::cutoff_m private
Definition at line 491 of file Distribution.h.
Referenced by getTEmission().
cutoffP_m
Vector_t Distribution::cutoffP_m private
Definition at line 468 of file Distribution.h.
Referenced by createDistributionMultiGauss(), generateGaussZ(), generateTransverseGauss(), printDistGauss(), printDistMultiGauss(), setDistParametersBinomial(), setDistParametersGauss(), and setDistParametersMultiGauss().
cutoffR_m
Vector_t Distribution::cutoffR_m private
Definition at line 467 of file Distribution.h.
Referenced by createDistributionMultiGauss(), generateGaussZ(), generateLongFlattopT(), generateTransverseGauss(), printDistFlattop(), printDistGauss(), printDistMultiGauss(), setDistParametersBinomial(), setDistParametersFlattop(), setDistParametersGauss(), setDistParametersMultiGauss(), and setEmissionTime().
distrTypeT_m
DistributionType Distribution::distrTypeT_m private
Distribution type strings.
Definition at line 387 of file Distribution.h.
Referenced by adjustPhaseSpace(), calcPartPerDist(), checkIfEmitted(), create(), createOpalT(), generateFlattopLaserProfile(), generateFlattopT(), getTEmission(), getType(), printDist(), printDistFlattop(), reflectDistribution(), setDistParametersFlattop(), setDistParametersGauss(), setDistType(), setEmissionTime(), setupEmissionModel(), and shiftBeam().
distT_m
std::string Distribution::distT_m private
Definition at line 386 of file Distribution.h.
Referenced by getTypeofDistribution(), and setDistType().
E_m
double Distribution::E_m private
Definition at line 484 of file Distribution.h.
Referenced by createMatchedGaussDistribution(), createOpalCycl(), and generateMatchedGauss().
emissionModel_m
EmissionModel Distribution::emissionModel_m private
Emission Model.
Definition at line 402 of file Distribution.h.
Referenced by applyEmissionModel(), create(), createOpalT(), printEmissionModel(), and setupEmissionModel().
emitEnergyUpperLimit_m
double Distribution::emitEnergyUpperLimit_m private
Cathode temperature (K).
Definition at line 433 of file Distribution.h.
Referenced by applyEmissModelNonEquil(), and setupEmissionModelNonEquil().
emitting_m
bool Distribution::emitting_m private
Definition at line 391 of file Distribution.h.
Referenced by adjustPhaseSpace(), checkIfEmitted(), create(), createDistributionFlattop(), createDistributionGauss(), createDistributionMultiGauss(), createOpalCycl(), createOpalT(), emitParticles(), getEmissionTimeShift(), getIfDistEmitting(), printDistBinomial(), printDistFlattop(), printDistGauss(), printDistMultiGauss(), printInfo(), Rebin(), scaleDistCoordinates(), setDistParametersBinomial(), setDistParametersFlattop(), setDistParametersGauss(), setDistParametersMultiGauss(), setDistToEmitted(), setupEnergyBins(), shiftBeam(), shiftDistCoordinates(), and writeOutFileHeader().
energyBinHist_m
gsl_histogram* Distribution::energyBinHist_m private
Distribution energy bins.
Definition at line 419 of file Distribution.h.
Referenced by fillEBinHistogram(), findEBin(), printEnergyBins(), setupEnergyBins(), and ~Distribution().
energyBins_m
PartBins* Distribution::energyBins_m private
Number of samples to use per energy bin when emitting beam.
Definition at line 418 of file Distribution.h.
Referenced by createOpalCycl(), doRestartOpalCycl(), fillParticleBins(), setupParticleBins(), and ~Distribution().
I_m
double Distribution::I_m private
Definition at line 483 of file Distribution.h.
Referenced by createMatchedGaussDistribution(), and createOpalCycl().
inputMoUnits_m
InputMomentumUnits Distribution::inputMoUnits_m private
Definition at line 461 of file Distribution.h.
Referenced by adjustPhaseSpace(), chooseInputMomentumUnits(), createDistributionFromFile(), createOpalT(), generateMatchedGauss(), printDist(), setSigmaP_m(), and shiftDistCoordinates().
laserEnergy_m
double Distribution::laserEnergy_m private
Cathode material work function (eV).
Definition at line 430 of file Distribution.h.
Referenced by applyEmissModelNonEquil(), emitParticles(), printEmissionModelNonEquil(), and setupEmissionModelNonEquil().
laserImageName_m
std::string Distribution::laserImageName_m private
Definition at line 478 of file Distribution.h.
Referenced by printDistFlattop(), and setDistParametersFlattop().
laserIntensityCut_m
double Distribution::laserIntensityCut_m private
Definition at line 479 of file Distribution.h.
Referenced by printDistFlattop(), and setDistParametersFlattop().
laserProfile_m
LaserProfile* Distribution::laserProfile_m private
Definition at line 480 of file Distribution.h.
Referenced by createDistributionFlattop(), generateFlattopLaserProfile(), printDistFlattop(), setDistParametersFlattop(), and ~Distribution().
laserProfileFileName_m
std::string Distribution::laserProfileFileName_m private
Definition at line 477 of file Distribution.h.
Referenced by printDistFlattop(), and setDistParametersFlattop().
mBinomial_m
Vector_t Distribution::mBinomial_m private
Definition at line 469 of file Distribution.h.
Referenced by generateBinomial(), printDistBinomial(), and setDistParametersBinomial().
nPeaks_m
unsigned Distribution::nPeaks_m private
Definition at line 474 of file Distribution.h.
Referenced by createDistributionMultiGauss(), printDistMultiGauss(), and setDistParametersMultiGauss().
numberOfDistributions_m
unsigned int Distribution::numberOfDistributions_m private
List of Distribution types.
Definition at line 389 of file Distribution.h.
Referenced by calcPartPerDist(), and setNumberOfDistributions().
numberOfEnergyBins_m
int Distribution::numberOfEnergyBins_m private
Definition at line 414 of file Distribution.h.
Referenced by checkEmissionParameters(), createOpalCycl(), createOpalT(), emitParticles(), findEBin(), getNumberOfEmissionSteps(), getNumberOfEnergyBins(), initializeBeam(), injectBeam(), printEnergyBins(), printInfo(), Rebin(), setEmissionTime(), setupEnergyBins(), setupParticleBins(), writeOutFileHeader(), and writeOutFileInjection().
numberOfSampleBins_m
int Distribution::numberOfSampleBins_m private
Number of energy bins the distribution is broken into. Used for an emitted beam.
Definition at line 416 of file Distribution.h.
Referenced by checkEmissionParameters(), emitParticles(), findEBin(), getEmissionDeltaT(), getNumberOfEmissionSteps(), printEnergyBins(), printInfo(), and setupEnergyBins().
outFilename_m
std::string Distribution::outFilename_m private
Definition at line 493 of file Distribution.h.
Referenced by printInfo(), writeOutFileEmission(), writeOutFileHeader(), and writeOutFileInjection().
particleRefData_m
PartData Distribution::particleRefData_m private
Distribution is an emitted, and is currently emitting, rather than an injected, beam.
Definition at line 394 of file Distribution.h.
particlesPerDist_m
std::vector<size_t> Distribution::particlesPerDist_m private
Definition at line 399 of file Distribution.h.
Referenced by addDistributions(), calcPartPerDist(), create(), createOpalCycl(), createOpalT(), printInfo(), and shiftDistCoordinates().
percentTEmission_m
const double Distribution::percentTEmission_m = 0.0005 static private
Definition at line 406 of file Distribution.h.
Referenced by setEmissionTime().
pmean_m
Vector_t Distribution::pmean_m private
Total thermal momentum.
Definition at line 426 of file Distribution.h.
Referenced by checkFileMomentum(), createDistributionFromFile(), createOpalT(), get_pmean(), setupEmissionModelAstra(), setupEmissionModelNone(), and setupEmissionModelNonEquil().
pTotThermal_m
double Distribution::pTotThermal_m private
Random number generator.
Definition at line 425 of file Distribution.h.
Referenced by applyEmissModelAstra(), applyEmissModelNone(), setupEmissionModelAstra(), and setupEmissionModelNone().
pxDist_m
std::vector<double> Distribution::pxDist_m private
Definition at line 442 of file Distribution.h.
Referenced by addDistributions(), adjustPhaseSpace(), createDistributionFromFile(), createDistributionMultiGauss(), emitParticles(), eraseBGxDist(), fillParticleBins(), generateBinomial(), generateFlattopLaserProfile(), generateFlattopT(), generateFlattopZ(), generateGaussZ(), generateMatchedGauss(), generateTransverseGauss(), getBGxDist(), injectBeam(), reflectDistribution(), scaleDistCoordinates(), shiftDistCoordinates(), and writeOutFileInjection().
pxWrite_m
std::vector<double> Distribution::pxWrite_m private
Definition at line 450 of file Distribution.h.
Referenced by emitParticles(), and writeOutFileEmission().
pyDist_m
std::vector<double> Distribution::pyDist_m private
Definition at line 444 of file Distribution.h.
Referenced by addDistributions(), adjustPhaseSpace(), createDistributionFromFile(), createDistributionMultiGauss(), emitParticles(), eraseBGyDist(), fillParticleBins(), generateBinomial(), generateFlattopLaserProfile(), generateFlattopT(), generateFlattopZ(), generateGaussZ(), generateMatchedGauss(), generateTransverseGauss(), getBGyDist(), injectBeam(), reflectDistribution(), scaleDistCoordinates(), shiftDistCoordinates(), and writeOutFileInjection().
pyWrite_m
std::vector<double> Distribution::pyWrite_m private
Definition at line 452 of file Distribution.h.
Referenced by emitParticles(), and writeOutFileEmission().
pzDist_m
std::vector<double> Distribution::pzDist_m private
Definition at line 446 of file Distribution.h.
Referenced by addDistributions(), adjustPhaseSpace(), createDistributionFromFile(), createDistributionMultiGauss(), emitParticles(), eraseBGzDist(), fillParticleBins(), generateAstraFlattopT(), generateBinomial(), generateFlattopZ(), generateGaussZ(), generateLongFlattopT(), generateMatchedGauss(), getBGzDist(), injectBeam(), reflectDistribution(), scaleDistCoordinates(), setupEmissionModelNone(), shiftDistCoordinates(), and writeOutFileInjection().
pzWrite_m
std::vector<double> Distribution::pzWrite_m private
Definition at line 454 of file Distribution.h.
Referenced by emitParticles(), and writeOutFileEmission().
randGen_m
gsl_rng* Distribution::randGen_m private
GSL histogram used to define energy bin structure.
Definition at line 422 of file Distribution.h.
Referenced by applyEmissModelNonEquil(), create(), createDistributionMultiGauss(), Distribution(), generateAstraFlattopT(), generateBinomial(), generateFlattopZ(), generateGaussZ(), generateLongFlattopT(), generateMatchedGauss(), generateTransverseGauss(), sampleUniformDisk(), and ~Distribution().
sepPeaks_m
double Distribution::sepPeaks_m private
Definition at line 473 of file Distribution.h.
Referenced by createDistributionMultiGauss(), printDistMultiGauss(), and setDistParametersMultiGauss().
sigmaFall_m
double Distribution::sigmaFall_m private
Definition at line 490 of file Distribution.h.
Referenced by getTEmission().
sigmaP_m
Vector_t Distribution::sigmaP_m private
Definition at line 466 of file Distribution.h.
Referenced by createDistributionMultiGauss(), generateBinomial(), generateGaussZ(), generateMatchedGauss(), generateTransverseGauss(), printDistBinomial(), printDistGauss(), printDistMatchedGauss(), printDistMultiGauss(), and setSigmaP_m().
sigmaR_m
Vector_t Distribution::sigmaR_m private
Definition at line 465 of file Distribution.h.
Referenced by createDistributionMultiGauss(), generateBinomial(), generateFlattopLaserProfile(), generateFlattopT(), generateFlattopZ(), generateGaussZ(), generateMatchedGauss(), generateTransverseGauss(), printDistBinomial(), printDistFlattop(), printDistGauss(), printDistMatchedGauss(), printDistMultiGauss(), setDistParametersFlattop(), setDistParametersGauss(), and setSigmaR_m().
sigmaRise_m
double Distribution::sigmaRise_m private
Definition at line 489 of file Distribution.h.
Referenced by getTEmission().
sigmaTFall_m
double Distribution::sigmaTFall_m private
Definition at line 463 of file Distribution.h.
Referenced by generateLongFlattopT(), printDistFlattop(), printDistGauss(), setDistParametersFlattop(), setDistParametersGauss(), and setEmissionTime().
sigmaTRise_m
double Distribution::sigmaTRise_m private
Definition at line 462 of file Distribution.h.
Referenced by generateLongFlattopT(), printDistFlattop(), printDistGauss(), setDistParametersFlattop(), setDistParametersGauss(), and setEmissionTime().
tBin_m
double Distribution::tBin_m private
Increase tEmission_m by twice this percentage to ensure that no particles fall on the leading edge of the first emission time step or the trailing edge of the last emission time step.
Definition at line 410 of file Distribution.h.
Referenced by generateAstraFlattopT(), getEmissionDeltaT(), getEnergyBinDeltaT(), printInfo(), and setEmissionTime().
tEmission_m
double Distribution::tEmission_m private
Emission parameters.
Definition at line 405 of file Distribution.h.
Referenced by generateAstraFlattopT(), getTEmission(), initializeBeam(), printInfo(), setEmissionTime(), setupEnergyBins(), and shiftBeam().
tFall_m
double Distribution::tFall_m private
Definition at line 488 of file Distribution.h.
Referenced by getTEmission().
tOrZDist_m
std::vector<double> Distribution::tOrZDist_m private
Definition at line 445 of file Distribution.h.
Referenced by addDistributions(), adjustPhaseSpace(), checkParticleNumber(), create(), createDistributionFromFile(), createDistributionMultiGauss(), createOpalCycl(), emitParticles(), eraseTOrZDist(), fillEBinHistogram(), fillParticleBins(), generateAstraFlattopT(), generateBinomial(), generateFlattopZ(), generateGaussZ(), generateLongFlattopT(), generateMatchedGauss(), getMaxTOrZ(), getMinTOrZ(), getTOrZDist(), injectBeam(), reflectDistribution(), scaleDistCoordinates(), shiftBeam(), shiftDistCoordinates(), writeOutFileHeader(), and writeOutFileInjection().
tOrZWrite_m
std::vector<double> Distribution::tOrZWrite_m private
Definition at line 453 of file Distribution.h.
Referenced by emitParticles(), and writeOutFileEmission().
totalNumberEmittedParticles_m
size_t Distribution::totalNumberEmittedParticles_m private
Definition at line 438 of file Distribution.h.
Referenced by emitParticles(), and getPercentageEmitted().
totalNumberParticles_m
size_t Distribution::totalNumberParticles_m private
Definition at line 437 of file Distribution.h.
Referenced by adjustPhaseSpace(), createOpalCycl(), createOpalT(), and getPercentageEmitted().
tPulseLengthFWHM_m
double Distribution::tPulseLengthFWHM_m private
Definition at line 464 of file Distribution.h.
Referenced by generateAstraFlattopT(), generateLongFlattopT(), getTEmission(), printDistFlattop(), printDistGauss(), setDistParametersFlattop(), setDistParametersGauss(), and setEmissionTime().
tRise_m
double Distribution::tRise_m private
time binned distribution with thermal energy
Definition at line 487 of file Distribution.h.
Referenced by generateAstraFlattopT(), getTEmission(), printDistFlattop(), and setDistParametersFlattop().
xDist_m
std::vector<double> Distribution::xDist_m private
Definition at line 441 of file Distribution.h.
Referenced by addDistributions(), adjustPhaseSpace(), createDistributionFromFile(), createDistributionMultiGauss(), emitParticles(), eraseXDist(), fillParticleBins(), generateBinomial(), generateFlattopLaserProfile(), generateFlattopT(), generateFlattopZ(), generateGaussZ(), generateMatchedGauss(), generateTransverseGauss(), getXDist(), injectBeam(), reflectDistribution(), scaleDistCoordinates(), shiftDistCoordinates(), and writeOutFileInjection().
xWrite_m
std::vector<double> Distribution::xWrite_m private
Definition at line 449 of file Distribution.h.
Referenced by emitParticles(), and writeOutFileEmission().
yDist_m
std::vector<double> Distribution::yDist_m private
Definition at line 443 of file Distribution.h.
Referenced by addDistributions(), adjustPhaseSpace(), createDistributionFromFile(), createDistributionMultiGauss(), emitParticles(), eraseYDist(), fillParticleBins(), generateBinomial(), generateFlattopLaserProfile(), generateFlattopT(), generateFlattopZ(), generateGaussZ(), generateMatchedGauss(), generateTransverseGauss(), getYDist(), injectBeam(), reflectDistribution(), scaleDistCoordinates(), shiftDistCoordinates(), and writeOutFileInjection().
yWrite_m
std::vector<double> Distribution::yWrite_m private
Definition at line 451 of file Distribution.h.
Referenced by emitParticles(), and writeOutFileEmission().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Distribution/Distribution.h
/psi/home/gsell/data/src/OPAL/src/src/Distribution/Distribution.cpp