OPAL (Object Oriented Parallel Accelerator Library): PluginElement Class Reference
PluginElement Class Reference abstract
#include <PluginElement.h>
Public Member Functions
PluginElement (const std::string &name)
Constructor with given name.
PluginElement ()
PluginElement (const PluginElement &)
void operator= (const PluginElement &)=delete
virtual ~PluginElement ()
void setDimensions (double xstart, double xend, double ystart, double yend)
Set dimensions and consistency checks.
bool check (PartBunchBase< double, 3 > *bunch, const int turnnumber, const double t, const double tstep)
int checkPoint (const double &x, const double &y) const
Checks if coordinate is within element.
void save ()
Save output.
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
Pure virtual implementation of Component.
void initialise (PartBunchBase< double, 3 > *bunch)
virtual void finalise () final
virtual void goOffline () final
virtual bool bends () const override
virtual void getDimensions (double &zBegin, double &zEnd) const override
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
double getXStart () const
Member variable access.
double getXEnd () const
double getYStart () const
double getYEnd () const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
virtual EMField & getField ()=0
Return field.
virtual const EMField & getField () const =0
Return field.
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual bool Online ()
virtual ElementBase::ElementType getType () const
Get element type std::string.
virtual void setComponentType (std::string)
virtual std::string getComponentType () const
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual void accept (BeamlineVisitor &visitor) const =0
Apply visitor.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Member Functions
void setGeom (const double dist)
Sets geometry geom_m with element width dist.
void changeWidth (PartBunchBase< double, 3 > *bunch, int i, const double tstep, const double tangle)
Change probe width depending on step size and angle of particle.
double calculateIncidentAngle (double xp, double yp) const
Calculate angle of particle/bunch wrt to element.
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes
double rmin_m
radius closest to the origin
Point geom_m [5]
actual geometry positions with adaptive width such that each particle hits element once per turn
double A_m
double B_m
double R_m
double C_m
Geometric lengths used in calculations.
std::unique_ptr< LossDataSink > lossDs_m
Pointer to Loss instance.
int numPassages_m = 0
Number of turns (number of times save() method is called)
double xstart_m
input geometry positions
double xend_m
double ystart_m
double yend_m
double rstart_m
double rend_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Private Member Functions
bool preCheck (PartBunchBase< double, 3 > *bunch)
Check if bunch is close to element.
bool finaliseCheck (PartBunchBase< double, 3 > *bunch, bool flagNeedUpdate)
Finalise call after check.
virtual void doInitialise (PartBunchBase< double, 3 > *)
Pure virtual hook for initialise.
virtual bool doCheck (PartBunchBase< double, 3 > *bunch, const int turnnumber, const double t, const double tstep)=0
Pure virtual hook for check.
virtual void doSetGeom ()
Virtual hook for setGeom.
virtual bool doPreCheck (PartBunchBase< double, 3 > *)
Virtual hook for preCheck.
virtual bool doFinaliseCheck (PartBunchBase< double, 3 > *, bool flagNeedUpdate)
Virtual hook for finaliseCheck.
virtual void doFinalise ()
Virtual hook for finalise.
virtual void doGoOffline ()
Virtual hook for goOffline.
Additional Inherited Members
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 30 of file PluginElement.h.
Constructor & Destructor Documentation
PluginElement() [1/3]
PluginElement::PluginElement (const std::string & name) explicit
Constructor with given name.
Definition at line 32 of file PluginElement.cpp.
References setDimensions().
PluginElement() [2/3]
PluginElement::PluginElement ()
Definition at line 29 of file PluginElement.cpp.
PluginElement() [3/3]
PluginElement::PluginElement (const PluginElement & right)
Definition at line 37 of file PluginElement.cpp.
References setDimensions(), xend_m, xstart_m, yend_m, and ystart_m.
~PluginElement()
PluginElement::~PluginElement () virtual
Definition at line 42 of file PluginElement.cpp.
References goOffline(), and Component::online_m.
Member Function Documentation
apply()
bool PluginElement::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Virtual implementation of Component
Reimplemented from Component.
Definition at line 77 of file PluginElement.cpp.
applyToReferenceParticle()
bool PluginElement::applyToReferenceParticle (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 81 of file PluginElement.cpp.
bends()
bool PluginElement::bends () const override virtual
Implements Component.
Definition at line 73 of file PluginElement.cpp.
calculateIncidentAngle()
double PluginElement::calculateIncidentAngle (double xp, double yp) const protected
Calculate angle of particle/bunch wrt to element.
Definition at line 152 of file PluginElement.cpp.
References A_m, abs(), and B_m.
Referenced by Probe::doCheck(), and Stripper::doCheck().
changeWidth()
void PluginElement::changeWidth (PartBunchBase< double, 3 > * bunch, int i, const double tstep, const double tangle) protected
Change probe width depending on step size and angle of particle.
Definition at line 144 of file PluginElement.cpp.
References Physics::c, euclidean_norm(), Util::getGamma(), PartBunchBase< T, Dim >::P, setGeom(), and sqrt().
Referenced by Probe::doCheck(), and Stripper::doCheck().
check()
bool PluginElement::check (PartBunchBase< double, 3 > * bunch, const int turnnumber, const double t, const double tstep)
Check if bunch particles are lost
Definition at line 193 of file PluginElement.cpp.
References doCheck(), finaliseCheck(), and preCheck().
checkPoint()
int PluginElement::checkPoint (const double & x, const double & y) const
Checks if coordinate is within element.
Definition at line 212 of file PluginElement.cpp.
References geom_m, and Point::y.
Referenced by Probe::doCheck(), Stripper::doCheck(), and CCollimator::doCheck().
doCheck()
virtual bool PluginElement::doCheck (PartBunchBase< double, 3 > * bunch, const int turnnumber, const double t, const double tstep) private pure virtual
Pure virtual hook for check.
Implemented in CCollimator, Stripper, Probe, and Septum.
Referenced by check().
doFinalise()
virtual void PluginElement::doFinalise () inline private virtual
Virtual hook for finalise.
Reimplemented in CCollimator, and Stripper.
Definition at line 102 of file PluginElement.h.
Referenced by finalise().
doFinaliseCheck()
virtual bool PluginElement::doFinaliseCheck (PartBunchBase< double, 3 > * , bool flagNeedUpdate) inline private virtual
Virtual hook for finaliseCheck.
Reimplemented in CCollimator, and Stripper.
Definition at line 100 of file PluginElement.h.
Referenced by finaliseCheck().
doGoOffline()
virtual void PluginElement::doGoOffline () inline private virtual
Virtual hook for goOffline.
Reimplemented in Probe.
Definition at line 104 of file PluginElement.h.
Referenced by goOffline().
doInitialise()
virtual void PluginElement::doInitialise (PartBunchBase< double, 3 > *) inline private virtual
Pure virtual hook for initialise.
Reimplemented in CCollimator, Probe, and Septum.
Definition at line 92 of file PluginElement.h.
Referenced by initialise().
doPreCheck()
virtual bool PluginElement::doPreCheck (PartBunchBase< double, 3 > *) inline private virtual
Virtual hook for preCheck.
Reimplemented in CCollimator, Stripper, Probe, and Septum.
Definition at line 98 of file PluginElement.h.
Referenced by preCheck().
doSetGeom()
virtual void PluginElement::doSetGeom () inline private virtual
Virtual hook for setGeom.
Reimplemented in CCollimator.
Definition at line 96 of file PluginElement.h.
Referenced by setGeom().
finalise()
void PluginElement::finalise () final virtual
Implements Component.
Definition at line 59 of file PluginElement.cpp.
References doFinalise(), goOffline(), and Component::online_m.
finaliseCheck()
bool PluginElement::finaliseCheck (PartBunchBase< double, 3 > * bunch, bool flagNeedUpdate) inline private
Finalise call after check.
Definition at line 90 of file PluginElement.h.
References doFinaliseCheck().
Referenced by check().
getDimensions()
void PluginElement::getDimensions (double & zBegin, double & zEnd) const override virtual
Implements Component.
Reimplemented in CCollimator.
Definition at line 207 of file PluginElement.cpp.
getXEnd()
double PluginElement::getXEnd () const
Definition at line 181 of file PluginElement.cpp.
References xend_m.
Referenced by ParallelCyclotronTracker::visitCCollimator(), ParallelCyclotronTracker::visitProbe(), ParallelCyclotronTracker::visitSeptum(), and ParallelCyclotronTracker::visitStripper().
getXStart()
double PluginElement::getXStart () const
Member variable access.
Definition at line 177 of file PluginElement.cpp.
References xstart_m.
Referenced by ParallelCyclotronTracker::visitCCollimator(), ParallelCyclotronTracker::visitProbe(), ParallelCyclotronTracker::visitSeptum(), and ParallelCyclotronTracker::visitStripper().
getYEnd()
double PluginElement::getYEnd () const
Definition at line 189 of file PluginElement.cpp.
References yend_m.
Referenced by ParallelCyclotronTracker::visitCCollimator(), ParallelCyclotronTracker::visitProbe(), ParallelCyclotronTracker::visitSeptum(), and ParallelCyclotronTracker::visitStripper().
getYStart()
double PluginElement::getYStart () const
Definition at line 185 of file PluginElement.cpp.
References ystart_m.
Referenced by ParallelCyclotronTracker::visitCCollimator(), ParallelCyclotronTracker::visitProbe(), ParallelCyclotronTracker::visitSeptum(), and ParallelCyclotronTracker::visitStripper().
goOffline()
void PluginElement::goOffline () final virtual
Reimplemented from Component.
Definition at line 65 of file PluginElement.cpp.
References doGoOffline(), lossDs_m, and Component::online_m.
Referenced by finalise(), and ~PluginElement().
initialise() [1/2]
void PluginElement::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Pure virtual implementation of Component.
Implements Component.
Reimplemented in Septum.
Definition at line 47 of file PluginElement.cpp.
Referenced by ParallelCyclotronTracker::visitCCollimator(), ParallelCyclotronTracker::visitProbe(), and ParallelCyclotronTracker::visitStripper().
initialise() [2/2]
void PluginElement::initialise (PartBunchBase< double, 3 > * bunch)
Definition at line 51 of file PluginElement.cpp.
References Options::asciidump, doInitialise(), ElementBase::getOutputFN(), Component::goOnline(), lossDs_m, and Component::RefPartBunch_m.
operator=()
void PluginElement::operator= (const PluginElement &) delete
preCheck()
bool PluginElement::preCheck (PartBunchBase< double, 3 > * bunch) inline private
Check if bunch is close to element.
Definition at line 88 of file PluginElement.h.
References doPreCheck().
Referenced by check().
save()
void PluginElement::save ()
Save output.
Definition at line 226 of file PluginElement.cpp.
References OpalData::APPEND, OpalData::getInstance(), OpalData::getOpenMode(), lossDs_m, and numPassages_m.
setDimensions()
void PluginElement::setDimensions (double xstart, double xend, double ystart, double yend)
Set dimensions and consistency checks.
Definition at line 85 of file PluginElement.cpp.
References A_m, abs(), B_m, C_m, max(), min(), R_m, rend_m, rmin_m, rstart_m, sqrt(), xend_m, xstart_m, yend_m, and ystart_m.
Referenced by PluginElement(), OpalSeptum::update(), OpalProbe::update(), and OpalStripper::update().
setGeom()
void PluginElement::setGeom (const double dist) protected
Sets geometry geom_m with element width dist.
Definition at line 115 of file PluginElement.cpp.
References doSetGeom(), geom_m, sqrt(), Point::x, xend_m, xstart_m, Point::y, yend_m, and ystart_m.
Referenced by CCollimator::CCollimator(), changeWidth(), Septum::Septum(), CCollimator::setDimensions(), and Septum::setWidth().
Member Data Documentation
A_m
double PluginElement::A_m protected
Definition at line 118 of file PluginElement.h.
Referenced by calculateIncidentAngle(), Probe::doCheck(), Stripper::doCheck(), and setDimensions().
B_m
double PluginElement::B_m protected
Definition at line 118 of file PluginElement.h.
Referenced by calculateIncidentAngle(), Probe::doCheck(), Stripper::doCheck(), and setDimensions().
C_m
double PluginElement::C_m protected
Geometric lengths used in calculations.
Definition at line 118 of file PluginElement.h.
Referenced by Probe::doCheck(), Stripper::doCheck(), and setDimensions().
geom_m
Point PluginElement::geom_m[5] protected
actual geometry positions with adaptive width such that each particle hits element once per turn
Definition at line 117 of file PluginElement.h.
Referenced by checkPoint(), CCollimator::doSetGeom(), and setGeom().
lossDs_m
std::unique_ptr<LossDataSink> PluginElement::lossDs_m protected
Pointer to Loss instance.
Definition at line 120 of file PluginElement.h.
Referenced by Septum::doCheck(), Probe::doCheck(), Stripper::doCheck(), CCollimator::doCheck(), goOffline(), initialise(), and save().
numPassages_m
int PluginElement::numPassages_m = 0 protected
Number of turns (number of times save() method is called)
Definition at line 121 of file PluginElement.h.
Referenced by save().
R_m
double PluginElement::R_m protected
Definition at line 118 of file PluginElement.h.
Referenced by Probe::doCheck(), Stripper::doCheck(), and setDimensions().
rend_m
double PluginElement::rend_m protected
Definition at line 114 of file PluginElement.h.
Referenced by Probe::doInitialise(), Probe::doPreCheck(), and setDimensions().
rmin_m
double PluginElement::rmin_m protected
radius closest to the origin
Definition at line 116 of file PluginElement.h.
Referenced by Probe::doInitialise(), Probe::doPreCheck(), Stripper::doPreCheck(), CCollimator::doPreCheck(), and setDimensions().
rstart_m
double PluginElement::rstart_m protected
Definition at line 113 of file PluginElement.h.
Referenced by Septum::doPreCheck(), and setDimensions().
xend_m
double PluginElement::xend_m protected
Definition at line 110 of file PluginElement.h.
Referenced by CCollimator::CCollimator(), Septum::doCheck(), getXEnd(), PluginElement(), setDimensions(), and setGeom().
xstart_m
double PluginElement::xstart_m protected
input geometry positions
Definition at line 104 of file PluginElement.h.
Referenced by CCollimator::CCollimator(), Septum::doCheck(), getXStart(), PluginElement(), setDimensions(), and setGeom().
yend_m
double PluginElement::yend_m protected
Definition at line 112 of file PluginElement.h.
Referenced by CCollimator::CCollimator(), Septum::doCheck(), getYEnd(), PluginElement(), setDimensions(), and setGeom().
ystart_m
double PluginElement::ystart_m protected
Definition at line 111 of file PluginElement.h.
Referenced by CCollimator::CCollimator(), Septum::doCheck(), getYStart(), PluginElement(), setDimensions(), and setGeom().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/PluginElement.h
src/Classic/AbsBeamline/PluginElement.cpp