OPAL (Object Oriented Parallel Accelerator Library): _FM2DMagnetoStatic Class Reference
_FM2DMagnetoStatic Class Reference
#include <FM2DMagnetoStatic.h>
Public Member Functions
virtual ~_FM2DMagnetoStatic ()
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const
virtual bool getFieldDerivative (const Vector_t &R, Vector_t &E, Vector_t &B, const DiffDirection &dir) const
virtual void getFieldDimensions (double &zBegin, double &zEnd) const
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const
virtual void swap ()
virtual void getInfo (Inform *msg)
virtual double getFrequency () const
virtual void setFrequency (double freq)
virtual bool isInside (const Vector_t &r) const
Public Member Functions inherited from _Fieldmap
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &onaxis)
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Private Member Functions
_FM2DMagnetoStatic (const std::string &filename)
virtual void readMap ()
virtual void freeMap ()
Static Private Member Functions
static FM2DMagnetoStatic create (const std::string &filename)
Private Attributes
double * FieldstrengthBz_m
double * FieldstrengthBr_m
double rbegin_m
double rend_m
double zbegin_m
double zend_m
double hz_m
double hr_m
int num_gridpr_m
int num_gridpz_m
bool swap_m
Friends
class _Fieldmap
Additional Inherited Members
Static Public Member Functions inherited from _Fieldmap
static Fieldmap getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions inherited from _Fieldmap
_Fieldmap ()=delete
_Fieldmap (const std::string &filename)
virtual ~_Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions inherited from _Fieldmap
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes inherited from _Fieldmap
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Detailed Description
Definition at line 6 of file FM2DMagnetoStatic.h.
Constructor & Destructor Documentation
~_FM2DMagnetoStatic()
_FM2DMagnetoStatic::~_FM2DMagnetoStatic () virtual
Definition at line 98 of file FM2DMagnetoStatic.cpp.
References freeMap().
_FM2DMagnetoStatic()
_FM2DMagnetoStatic::_FM2DMagnetoStatic (const std::string & filename) private
Definition at line 11 of file FM2DMagnetoStatic.cpp.
References Units::cm2m, _Fieldmap::disableFieldmapWarning(), Physics::e, endl(), _Fieldmap::Filename_m, hr_m, hz_m, _Fieldmap::interpreteEOF(), _Fieldmap::lines_read_m, _Fieldmap::noFieldmapWarning(), _Fieldmap::normalize_m, num_gridpr_m, num_gridpz_m, rbegin_m, rend_m, swap_m, T2DMagnetoStatic, Util::toUpper(), _Fieldmap::Type, zbegin_m, and zend_m.
Referenced by create().
Member Function Documentation
create()
FM2DMagnetoStatic _FM2DMagnetoStatic::create (const std::string & filename) static private
Definition at line 102 of file FM2DMagnetoStatic.cpp.
References _FM2DMagnetoStatic().
Referenced by _Fieldmap::getFieldmap().
freeMap()
void _FM2DMagnetoStatic::freeMap () private virtual
Implements _Fieldmap.
Definition at line 161 of file FM2DMagnetoStatic.cpp.
References FieldstrengthBr_m, and FieldstrengthBz_m.
Referenced by ~_FM2DMagnetoStatic().
getFieldDerivative()
bool _FM2DMagnetoStatic::getFieldDerivative (const Vector_t & R, Vector_t & E, Vector_t & B, const DiffDirection & dir) const virtual
Implements _Fieldmap.
Definition at line 207 of file FM2DMagnetoStatic.cpp.
References DZ, Physics::e, FieldstrengthBr_m, FieldstrengthBz_m, floor(), hr_m, hz_m, num_gridpr_m, num_gridpz_m, Attrib::Distribution::R, and sqrt().
getFieldDimensions() [1/2]
void _FM2DMagnetoStatic::getFieldDimensions (double & zBegin, double & zEnd) const virtual
Implements _Fieldmap.
Definition at line 309 of file FM2DMagnetoStatic.cpp.
References zbegin_m, and zend_m.
getFieldDimensions() [2/2]
void _FM2DMagnetoStatic::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const virtual
Implements _Fieldmap.
Definition at line 314 of file FM2DMagnetoStatic.cpp.
getFieldstrength()
bool _FM2DMagnetoStatic::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const virtual
Implements _Fieldmap.
Definition at line 171 of file FM2DMagnetoStatic.cpp.
References abs(), FieldstrengthBr_m, FieldstrengthBz_m, floor(), hr_m, hz_m, num_gridpr_m, num_gridpz_m, Attrib::Distribution::R, sqrt(), and zbegin_m.
getFrequency()
double _FM2DMagnetoStatic::getFrequency () const virtual
Implements _Fieldmap.
Definition at line 325 of file FM2DMagnetoStatic.cpp.
getInfo()
void _FM2DMagnetoStatic::getInfo (Inform * msg) virtual
Implements _Fieldmap.
Definition at line 321 of file FM2DMagnetoStatic.cpp.
References endl(), _Fieldmap::Filename_m, zbegin_m, and zend_m.
isInside()
bool _FM2DMagnetoStatic::isInside (const Vector_t & r) const inline virtual
Reimplemented from _Fieldmap.
Definition at line 45 of file FM2DMagnetoStatic.h.
References rend_m, sqrt(), zbegin_m, and zend_m.
readMap()
void _FM2DMagnetoStatic::readMap () private virtual
Implements _Fieldmap.
Definition at line 107 of file FM2DMagnetoStatic.cpp.
References abs(), endl(), FieldstrengthBr_m, FieldstrengthBz_m, _Fieldmap::Filename_m, _Fieldmap::getLine(), INFOMSG, level3(), _Fieldmap::normalize_m, num_gridpr_m, num_gridpz_m, swap_m, and _Fieldmap::typeset_msg().
setFrequency()
void _FM2DMagnetoStatic::setFrequency (double freq) virtual
Implements _Fieldmap.
Definition at line 329 of file FM2DMagnetoStatic.cpp.
swap()
void _FM2DMagnetoStatic::swap () virtual
Implements _Fieldmap.
Definition at line 316 of file FM2DMagnetoStatic.cpp.
References swap_m.
Friends And Related Function Documentation
_Fieldmap
friend class _Fieldmap friend
Definition at line 42 of file FM2DMagnetoStatic.h.
Member Data Documentation
FieldstrengthBr_m
double* _FM2DMagnetoStatic::FieldstrengthBr_m private
2D array with Er, read in like Ez
Definition at line 30 of file FM2DMagnetoStatic.h.
Referenced by freeMap(), getFieldDerivative(), getFieldstrength(), and readMap().
FieldstrengthBz_m
double* _FM2DMagnetoStatic::FieldstrengthBz_m private
2D array with Ez, read in first along z0 - r0 to rN then z1 - r0 to rN until zN - r0 to rN
Definition at line 29 of file FM2DMagnetoStatic.h.
Referenced by freeMap(), getFieldDerivative(), getFieldstrength(), and readMap().
hr_m
double _FM2DMagnetoStatic::hr_m private
length between points in grid, r-direction, m
Definition at line 37 of file FM2DMagnetoStatic.h.
Referenced by _FM2DMagnetoStatic(), getFieldDerivative(), and getFieldstrength().
hz_m
double _FM2DMagnetoStatic::hz_m private
length between points in grid, z-direction, m
Definition at line 36 of file FM2DMagnetoStatic.h.
Referenced by _FM2DMagnetoStatic(), getFieldDerivative(), and getFieldstrength().
num_gridpr_m
int _FM2DMagnetoStatic::num_gridpr_m private
Read in number of points after 0(not counted here) in grid, r-direction
Definition at line 38 of file FM2DMagnetoStatic.h.
Referenced by _FM2DMagnetoStatic(), getFieldDerivative(), getFieldstrength(), and readMap().
num_gridpz_m
int _FM2DMagnetoStatic::num_gridpz_m private
Read in number of points after 0(not counted here) in grid, z-direction
Definition at line 39 of file FM2DMagnetoStatic.h.
Referenced by _FM2DMagnetoStatic(), getFieldDerivative(), getFieldstrength(), and readMap().
rbegin_m
double _FM2DMagnetoStatic::rbegin_m private
Definition at line 32 of file FM2DMagnetoStatic.h.
Referenced by _FM2DMagnetoStatic().
rend_m
double _FM2DMagnetoStatic::rend_m private
Definition at line 33 of file FM2DMagnetoStatic.h.
Referenced by _FM2DMagnetoStatic(), and isInside().
swap_m
bool _FM2DMagnetoStatic::swap_m private
Definition at line 41 of file FM2DMagnetoStatic.h.
Referenced by _FM2DMagnetoStatic(), readMap(), and swap().
zbegin_m
double _FM2DMagnetoStatic::zbegin_m private
Definition at line 34 of file FM2DMagnetoStatic.h.
Referenced by _FM2DMagnetoStatic(), getFieldDimensions(), getFieldstrength(), getInfo(), and isInside().
zend_m
double _FM2DMagnetoStatic::zend_m private
Definition at line 35 of file FM2DMagnetoStatic.h.
Referenced by _FM2DMagnetoStatic(), getFieldDimensions(), getInfo(), and isInside().
The documentation for this class was generated from the following files:
src/Classic/Fields/FM2DMagnetoStatic.h
src/Classic/Fields/FM2DMagnetoStatic.cpp