OPAL (Object Oriented Parallel Accelerator Library): CompressedBrickIterator< T, Dim > Class Template Reference
CompressedBrickIterator< T, Dim > Class Template Reference
#include <FieldDataSource.h>
Public Member Functions
CompressedBrickIterator (T *t, const NDIndex< Dim > &c, const NDIndex< Dim > &a, T &compressed)
CompressedBrickIterator (T *t, const vec< int, Dim > &v, T &compressed)
CompressedBrickIterator (T &t)
CompressedBrickIterator ()
CompressedBrickIterator (const NDIndex< Dim > &a, T &compressed)
CompressedBrickIterator (const BrickIterator< T, Dim > &x, T &compressed)
bool IsCompressed () const
bool CanCompress (const T &) const
void Compress (T &val)
bool TryCompress ()
bool TryCompress (T val)
const CompressedBrickIterator< T, Dim > & operator= (const CompressedBrickIterator< T, Dim > &rhs)
CompressedBrickIterator (const CompressedBrickIterator< T, Dim > &X)
Message & putMessage (Message &m, bool makecopy=true)
Message & getMessage (Message &m)
CompressedBrickIterator< T, 1 > permute (NDIndex< Dim > &current, NDIndex< 1 > &permuted) const
CompressedBrickIterator< T, 2 > permute (NDIndex< Dim > &current, NDIndex< 2 > &permuted) const
CompressedBrickIterator< T, 3 > permute (NDIndex< Dim > &current, NDIndex< 3 > &permuted) const
CompressedBrickIterator< T, 4 > permute (NDIndex< Dim > &current, NDIndex< 4 > &permuted) const
CompressedBrickIterator< T, 5 > permute (NDIndex< Dim > &current, NDIndex< 5 > &permuted) const
CompressedBrickIterator< T, 6 > permute (NDIndex< Dim > &current, NDIndex< 6 > &permuted) const
void SetCurrent (T *p)
void SetCount (int d, int count)
void ResetCounter (int d)
void SetStride (int d, int stride)
int GetStride (int d) const
T & GetCompressedData () const
void SetCompressedData (T *newData)
Public Member Functions inherited from BrickIterator< T, Dim >
BrickIterator ()
BrickIterator (T *, const NDIndex< Dim > &, const NDIndex< Dim > &)
BrickIterator (T *, const vec< int, Dim > &)
BrickIterator & operator++ ()
bool whole () const
bool operator== (const BrickIterator< T, Dim > &a) const
bool operator!= (const BrickIterator< T, Dim > &a) const
T & operator* () const
void step (unsigned d)
void rewind (unsigned d)
T & offset (int i) const
T & offset (int i, int j) const
T & offset (int i, int j, int k) const
T & offset (int *i) const
T & unit_offset (int i) const
T & unit_offset (int i, int j) const
T & unit_offset (int i, int j, int k) const
void moveBy (int i)
void moveBy (int i, int j)
void moveBy (int i, int j, int k)
void moveBy (const int *i)
int Stride (int i) const
Message & putMessage (Message &, bool makecopy=true)
Message & getMessage (Message &)
PETE_Expr_t MakeExpression () const
Public Member Functions inherited from BrickCounter< Dim >
BrickCounter ()
BrickCounter (const NDIndex< Dim > &)
BrickCounter & operator++ ()
bool done (unsigned d) const
void step (unsigned d)
void rewind (unsigned d)
int size (unsigned d) const
int GetOffset (unsigned d) const
Private Attributes
T * CompressedData
Additional Inherited Members
Public Types inherited from BrickIterator< T, Dim >
typedef T PETE_Return_t
typedef BrickIterator< T, Dim > PETE_Expr_t
Protected Member Functions inherited from BrickIterator< T, Dim >
void op_pp ()
Protected Member Functions inherited from BrickCounter< Dim >
void op_pp ()
Protected Attributes inherited from BrickIterator< T, Dim >
T *__restrict__ Current
vec< int, Dim > Strides
bool Whole
Protected Attributes inherited from BrickCounter< Dim >
vec< int, Dim > Counters
vec< int, Dim > Counts
Detailed Description
template<class T, unsigned Dim>
class CompressedBrickIterator< T, Dim >
Definition at line 39 of file FieldDataSource.h.
Constructor & Destructor Documentation
CompressedBrickIterator() [1/7]
template<class T, unsigned Dim> CompressedBrickIterator< T, Dim >::CompressedBrickIterator (T * t, const NDIndex< Dim > & c, const NDIndex< Dim > & a, T & compressed) inline
Definition at line 58 of file CompressedBrickIterator.h.
References CompressedBrickIterator< T, Dim >::CompressedData, and Dim.
CompressedBrickIterator() [2/7]
template<class T, unsigned Dim> CompressedBrickIterator< T, Dim >::CompressedBrickIterator (T * t, const vec< int, Dim > & v, T & compressed) inline
Definition at line 73 of file CompressedBrickIterator.h.
References CompressedBrickIterator< T, Dim >::CompressedData, and Dim.
CompressedBrickIterator() [3/7]
template<class T, unsigned Dim> CompressedBrickIterator< T, Dim >::CompressedBrickIterator (T & t) inline
Definition at line 84 of file CompressedBrickIterator.h.
CompressedBrickIterator() [4/7]
template<class T, unsigned Dim> CompressedBrickIterator< T, Dim >::CompressedBrickIterator () inline
Definition at line 88 of file CompressedBrickIterator.h.
CompressedBrickIterator() [5/7]
template<class T , unsigned Dim> CompressedBrickIterator< T, Dim >::CompressedBrickIterator (const NDIndex< Dim > & a, T & compressed)
Definition at line 42 of file CompressedBrickIterator.hpp.
References Dim.
CompressedBrickIterator() [6/7]
template<class T, unsigned Dim> CompressedBrickIterator< T, Dim >::CompressedBrickIterator (const BrickIterator< T, Dim > & x, T & compressed) inline
Definition at line 96 of file CompressedBrickIterator.h.
CompressedBrickIterator() [7/7]
template<class T , unsigned Dim> CompressedBrickIterator< T, Dim >::CompressedBrickIterator (const CompressedBrickIterator< T, Dim > & X)
Definition at line 341 of file CompressedBrickIterator.hpp.
Member Function Documentation
CanCompress()
template<class T , unsigned Dim> bool CompressedBrickIterator< T, Dim >::CanCompress (const T & val) const
Definition at line 198 of file CompressedBrickIterator.hpp.
References all_values_equal(), and Dim.
Referenced by BareField< T1, D >::accumGuardCells(), and BareField< T1, D >::fillGuardCells().
Compress()
template<class T , unsigned Dim> void CompressedBrickIterator< T, Dim >::Compress (T & val)
Definition at line 359 of file CompressedBrickIterator.hpp.
References Dim.
GetCompressedData()
template<class T, unsigned Dim> T& CompressedBrickIterator< T, Dim >::GetCompressedData () const inline
Definition at line 169 of file CompressedBrickIterator.h.
References CompressedBrickIterator< T, Dim >::CompressedData.
Referenced by permute().
getMessage()
template<class T , unsigned Dim> Message & CompressedBrickIterator< T, Dim >::getMessage (Message & m)
Definition at line 245 of file CompressedBrickIterator.hpp.
References Dim, Message::get(), BrickIterator< T, Dim >::getMessage(), getMessage_iter(), and PAssert.
Referenced by BareField< T1, D >::accumGuardCells(), BareField< T1, D >::fillGuardCells(), FieldDataSource< T, Dim, M, C >::gather_data(), and BareField< T1, D >::write().
GetStride()
template<class T, unsigned Dim> int CompressedBrickIterator< T, Dim >::GetStride (int d) const inline
Definition at line 168 of file CompressedBrickIterator.h.
Referenced by permute().
IsCompressed()
template<class T, unsigned Dim> bool CompressedBrickIterator< T, Dim >::IsCompressed () const inline
Definition at line 100 of file CompressedBrickIterator.h.
References CompressedBrickIterator< T, Dim >::CompressedData.
Referenced by BareField< T1, D >::fillGuardCells(), BareFieldIterator< T, Dim >::IsCompressed(), permute(), and DiscField< Dim >::write_offset_and_data().
operator=()
template<class T , unsigned Dim> const CompressedBrickIterator< T, Dim > & CompressedBrickIterator< T, Dim >::operator= (const CompressedBrickIterator< T, Dim > & rhs)
Definition at line 326 of file CompressedBrickIterator.hpp.
References CompressedBrickIterator< T, Dim >::CompressedData.
permute() [1/6]
template<class T, unsigned Dim> CompressedBrickIterator<T,1> CompressedBrickIterator< T, Dim >::permute (NDIndex< Dim > & current, NDIndex< 1 > & permuted) const inline
Definition at line 146 of file CompressedBrickIterator.h.
References permute().
Referenced by IndexedLocalAssign(), and IndexedSend().
permute() [2/6]
template<class T, unsigned Dim> CompressedBrickIterator<T,2> CompressedBrickIterator< T, Dim >::permute (NDIndex< Dim > & current, NDIndex< 2 > & permuted) const inline
Definition at line 149 of file CompressedBrickIterator.h.
References permute().
permute() [3/6]
template<class T, unsigned Dim> CompressedBrickIterator<T,3> CompressedBrickIterator< T, Dim >::permute (NDIndex< Dim > & current, NDIndex< 3 > & permuted) const inline
Definition at line 152 of file CompressedBrickIterator.h.
References permute().
permute() [4/6]
template<class T, unsigned Dim> CompressedBrickIterator<T,4> CompressedBrickIterator< T, Dim >::permute (NDIndex< Dim > & current, NDIndex< 4 > & permuted) const inline
Definition at line 155 of file CompressedBrickIterator.h.
References permute().
permute() [5/6]
template<class T, unsigned Dim> CompressedBrickIterator<T,5> CompressedBrickIterator< T, Dim >::permute (NDIndex< Dim > & current, NDIndex< 5 > & permuted) const inline
Definition at line 158 of file CompressedBrickIterator.h.
References permute().
permute() [6/6]
template<class T, unsigned Dim> CompressedBrickIterator<T,6> CompressedBrickIterator< T, Dim >::permute (NDIndex< Dim > & current, NDIndex< 6 > & permuted) const inline
Definition at line 161 of file CompressedBrickIterator.h.
References permute().
putMessage()
template<class T , unsigned Dim> Message & CompressedBrickIterator< T, Dim >::putMessage (Message & m, bool makecopy = true)
Definition at line 220 of file CompressedBrickIterator.hpp.
References Dim, Message::put(), BrickIterator< T, Dim >::putMessage(), and putMessage().
Referenced by FieldDataSource< T, Dim, M, C >::gather_data(), and IndexedSend().
ResetCounter()
template<class T, unsigned Dim> void CompressedBrickIterator< T, Dim >::ResetCounter (int d) inline
Definition at line 166 of file CompressedBrickIterator.h.
SetCompressedData()
template<class T, unsigned Dim> void CompressedBrickIterator< T, Dim >::SetCompressedData (T * newData) inline
Definition at line 170 of file CompressedBrickIterator.h.
References CompressedBrickIterator< T, Dim >::CompressedData.
SetCount()
template<class T, unsigned Dim> void CompressedBrickIterator< T, Dim >::SetCount (int d, int count) inline
Definition at line 165 of file CompressedBrickIterator.h.
SetCurrent()
template<class T, unsigned Dim> void CompressedBrickIterator< T, Dim >::SetCurrent (T * p) inline
Definition at line 164 of file CompressedBrickIterator.h.
SetStride()
template<class T, unsigned Dim> void CompressedBrickIterator< T, Dim >::SetStride (int d, int stride) inline
Definition at line 167 of file CompressedBrickIterator.h.
TryCompress() [1/2]
template<class T, unsigned Dim> bool CompressedBrickIterator< T, Dim >::TryCompress () inline
Definition at line 114 of file CompressedBrickIterator.h.
References CompressedBrickIterator< T, Dim >::TryCompress().
Referenced by BareField< T1, D >::accumGuardCells(), assign(), BareField< T1, D >::fillGuardCells(), IndexedSend(), FieldPrint< T, Dim >::print(), FieldDebugPrint< T, Dim >::print(), and CompressedBrickIterator< T, Dim >::TryCompress().
TryCompress() [2/2]
template<class T , unsigned Dim> bool CompressedBrickIterator< T, Dim >::TryCompress (T val)
Definition at line 385 of file CompressedBrickIterator.hpp.
Member Data Documentation
CompressedData
template<class T, unsigned Dim> T* CompressedBrickIterator< T, Dim >::CompressedData private
Definition at line 177 of file CompressedBrickIterator.h.
Referenced by CompressedBrickIterator< T, Dim >::CompressedBrickIterator(), CompressedBrickIterator< T, Dim >::GetCompressedData(), CompressedBrickIterator< T, Dim >::IsCompressed(), CompressedBrickIterator< T, Dim >::operator=(), and CompressedBrickIterator< T, Dim >::SetCompressedData().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/FieldDataSource.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/CompressedBrickIterator.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/CompressedBrickIterator.hpp