OPAL (Object Oriented Parallel Accelerator Library): SubFieldTraits< T, Dim, S1, S2 > Struct Template Reference
SubFieldTraits< T, Dim, S1, S2 > Struct Template Reference
#include <SubFieldTraits.h>
Public Types
enum { Brackets_u = 0 }
typedef S2 Return_t
Static Public Member Functions
static int construct (S1 &, const S2 &, BareField< T, Dim > &)
template<class S3 >
static void combine (const S1 &, const S2 &, S3 &, unsigned int &, BareField< T, Dim > &)
Detailed Description
template<class T, unsigned int Dim, class S1, class S2>
struct SubFieldTraits< T, Dim, S1, S2 >
Definition at line 53 of file SubFieldTraits.h.
Member Typedef Documentation
Return_t
template<class T, unsigned int Dim, class S1, class S2> typedef S2 SubFieldTraits< T, Dim, S1, S2 >::Return_t
Definition at line 61 of file SubFieldTraits.h.
Member Enumeration Documentation
anonymous enum
template<class T, unsigned int Dim, class S1, class S2> anonymous enum
Enumerator
Brackets_u
Definition at line 64 of file SubFieldTraits.h.
Member Function Documentation
combine()
template<class T, unsigned int Dim, class S1, class S2> template<class S3 > static void SubFieldTraits< T, Dim, S1, S2 >::combine (const S1 & , const S2 & , S3 & , unsigned int & , BareField< T, Dim > &) inline static
Definition at line 68 of file SubFieldTraits.h.
References PInsist.
Referenced by SubField< T, Dim, M, C, S >::operator[](), and SubBareField< T, Dim, S >::operator[]().
construct()
template<class T, unsigned int Dim, class S1, class S2> static int SubFieldTraits< T, Dim, S1, S2 >::construct (S1 & , const S2 & , BareField< T, Dim > &) inline static
Definition at line 55 of file SubFieldTraits.h.
References PInsist.
Referenced by SubBareField< T, Dim, S >::SubBareField().
The documentation for this struct was generated from the following file:
ippl/src/SubField/SubFieldTraits.h