OPAL (Object Oriented Parallel Accelerator Library): _FM1DDynamic_fast Class Reference
_FM1DDynamic_fast Class Reference
#include <FM1DDynamic_fast.h>
Public Member Functions
virtual ~_FM1DDynamic_fast ()
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const
virtual bool getFieldDerivative (const Vector_t &R, Vector_t &E, Vector_t &B, const DiffDirection &dir) const
virtual void getFieldDimensions (double &zBegin, double &zEnd) const
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const
virtual void swap ()
virtual void getInfo (Inform *)
virtual double getFrequency () const
virtual void setFrequency (double freq)
virtual void getOnaxisEz (std::vector< std::pair< double, double >> &eZ)
virtual bool isInside (const Vector_t &r) const
Public Member Functions inherited from _Fieldmap
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &onaxis)
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Private Member Functions
_FM1DDynamic_fast (const std::string &filename)
virtual void readMap ()
virtual void freeMap ()
bool checkFileData (std::ifstream &fieldFile, bool parsingPassed)
void computeFieldDerivatives (std::vector< double > fourierCoefs, double onAxisFieldP[], double onAxisFieldPP[], double onAxisFieldPPP[])
void computeFieldOffAxis (const Vector_t &R, Vector_t &E, Vector_t &B, std::vector< double > fieldComponents) const
void computeFieldOnAxis (double z, std::vector< double > &fieldComponents) const
std::vector< double > computeFourierCoefficients (double fieldData[])
void computeInterpolationVectors (double onAxisFieldP[], double onAxisFieldPP[], double onAxisFieldPPP[])
void convertHeaderData ()
void normalizeField (double maxEz, std::vector< double > &fourierCoefs)
double readFileData (std::ifstream &fieldFile, double fieldData[])
double readFileData (std::ifstream &fieldFile, std::vector< std::pair< double, double >> &eZ)
bool readFileHeader (std::ifstream &fieldFile)
void scaleField (double maxEz, std::vector< std::pair< double, double >> &eZ)
void stripFileHeader (std::ifstream &fieldFile)
void prepareForMapCheck (std::vector< double > &fourierCoefs)
Static Private Member Functions
static FM1DDynamic_fast create (const std::string &filename)
Private Attributes
double frequency_m
double twoPiOverLambdaSq_m
Field angular frequency (Hz).
double rBegin_m
2 Pi divided by the field RF wavelength squared.
double rEnd_m
Minimum radius of field.
double zBegin_m
Maximum radius of field.
double zEnd_m
Longitudinal start of field.
double length_m
Longitudinal end of field.
unsigned int numberOfGridPoints_m
Field length.
double deltaZ_m
Number of grid points in field input file.
unsigned int accuracy_m
Field grid point spacing.
double * onAxisField_m
gsl_spline * onAxisFieldInterpolants_m
On axis field data.
gsl_spline * onAxisFieldPInterpolants_m
On axis field interpolation structure.
gsl_spline * onAxisFieldPPInterpolants_m
On axis field first derivative interpolation structure.
gsl_spline * onAxisFieldPPPInterpolants_m
On axis field second derivative interpolation structure.
gsl_interp_accel * onAxisFieldAccel_m
On axis field third derivative interpolation structure.
gsl_interp_accel * onAxisFieldPAccel_m
gsl_interp_accel * onAxisFieldPPAccel_m
gsl_interp_accel * onAxisFieldPPPAccel_m
Friends
class _Fieldmap
Additional Inherited Members
Static Public Member Functions inherited from _Fieldmap
static Fieldmap getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions inherited from _Fieldmap
_Fieldmap ()=delete
_Fieldmap (const std::string &filename)
virtual ~_Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions inherited from _Fieldmap
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes inherited from _Fieldmap
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Detailed Description
Definition at line 6 of file FM1DDynamic_fast.h.
Constructor & Destructor Documentation
~_FM1DDynamic_fast()
_FM1DDynamic_fast::~_FM1DDynamic_fast () virtual
Definition at line 44 of file FM1DDynamic_fast.cpp.
References freeMap().
_FM1DDynamic_fast()
_FM1DDynamic_fast::_FM1DDynamic_fast (const std::string & filename) private
Definition at line 13 of file FM1DDynamic_fast.cpp.
References checkFileData(), convertHeaderData(), deltaZ_m, _Fieldmap::disableFieldmapWarning(), _Fieldmap::Filename_m, length_m, _Fieldmap::noFieldmapWarning(), numberOfGridPoints_m, onAxisField_m, readFileHeader(), T1DDynamic, _Fieldmap::Type, zBegin_m, and zEnd_m.
Referenced by create().
Member Function Documentation
checkFileData()
bool _FM1DDynamic_fast::checkFileData (std::ifstream & fieldFile, bool parsingPassed) private
Definition at line 160 of file FM1DDynamic_fast.cpp.
References _Fieldmap::interpreteEOF(), and numberOfGridPoints_m.
Referenced by _FM1DDynamic_fast().
computeFieldDerivatives()
void _FM1DDynamic_fast::computeFieldDerivatives (std::vector< double > fourierCoefs, double onAxisFieldP[], double onAxisFieldPP[], double onAxisFieldPPP[]) private
Definition at line 172 of file FM1DDynamic_fast.cpp.
References accuracy_m, cos(), deltaZ_m, length_m, Hypervolume::n, numberOfGridPoints_m, Physics::pi, pow(), sin(), and Physics::two_pi.
Referenced by readMap().
computeFieldOffAxis()
void _FM1DDynamic_fast::computeFieldOffAxis (const Vector_t & R, Vector_t & E, Vector_t & B, std::vector< double > fieldComponents) const private
Definition at line 208 of file FM1DDynamic_fast.cpp.
References frequency_m, pow(), Attrib::Distribution::R, and twoPiOverLambdaSq_m.
Referenced by getFieldstrength().
computeFieldOnAxis()
void _FM1DDynamic_fast::computeFieldOnAxis (double z, std::vector< double > & fieldComponents) const private
Definition at line 232 of file FM1DDynamic_fast.cpp.
References onAxisFieldAccel_m, onAxisFieldInterpolants_m, onAxisFieldPAccel_m, onAxisFieldPInterpolants_m, onAxisFieldPPAccel_m, onAxisFieldPPInterpolants_m, onAxisFieldPPPAccel_m, and onAxisFieldPPPInterpolants_m.
Referenced by getFieldstrength().
computeFourierCoefficients()
std::vector< double > _FM1DDynamic_fast::computeFourierCoefficients (double fieldData[]) private
Definition at line 246 of file FM1DDynamic_fast.cpp.
References accuracy_m, and numberOfGridPoints_m.
Referenced by readMap().
computeInterpolationVectors()
void _FM1DDynamic_fast::computeInterpolationVectors (double onAxisFieldP[], double onAxisFieldPP[], double onAxisFieldPPP[]) private
Definition at line 278 of file FM1DDynamic_fast.cpp.
References deltaZ_m, numberOfGridPoints_m, onAxisField_m, onAxisFieldAccel_m, onAxisFieldInterpolants_m, onAxisFieldPAccel_m, onAxisFieldPInterpolants_m, onAxisFieldPPAccel_m, onAxisFieldPPInterpolants_m, onAxisFieldPPPAccel_m, and onAxisFieldPPPInterpolants_m.
Referenced by readMap().
convertHeaderData()
void _FM1DDynamic_fast::convertHeaderData () private
Definition at line 311 of file FM1DDynamic_fast.cpp.
References Physics::c, Units::cm2m, frequency_m, Units::MHz2Hz, pow(), rBegin_m, rEnd_m, Physics::two_pi, twoPiOverLambdaSq_m, zBegin_m, and zEnd_m.
Referenced by _FM1DDynamic_fast().
create()
FM1DDynamic_fast _FM1DDynamic_fast::create (const std::string & filename) static private
Definition at line 48 of file FM1DDynamic_fast.cpp.
References _FM1DDynamic_fast().
Referenced by _Fieldmap::getFieldmap().
freeMap()
void _FM1DDynamic_fast::freeMap () private virtual
Implements _Fieldmap.
Definition at line 85 of file FM1DDynamic_fast.cpp.
References onAxisField_m, onAxisFieldAccel_m, onAxisFieldInterpolants_m, onAxisFieldPAccel_m, onAxisFieldPInterpolants_m, onAxisFieldPPAccel_m, onAxisFieldPPInterpolants_m, onAxisFieldPPPAccel_m, and onAxisFieldPPPInterpolants_m.
Referenced by ~_FM1DDynamic_fast().
getFieldDerivative()
bool _FM1DDynamic_fast::getFieldDerivative (const Vector_t & R, Vector_t & E, Vector_t & B, const DiffDirection & dir) const virtual
Implements _Fieldmap.
Definition at line 111 of file FM1DDynamic_fast.cpp.
References onAxisFieldPAccel_m, onAxisFieldPInterpolants_m, Attrib::Distribution::R, and zBegin_m.
getFieldDimensions() [1/2]
void _FM1DDynamic_fast::getFieldDimensions (double & zBegin, double & zEnd) const virtual
Implements _Fieldmap.
Definition at line 122 of file FM1DDynamic_fast.cpp.
References zBegin_m, and zEnd_m.
getFieldDimensions() [2/2]
void _FM1DDynamic_fast::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const virtual
Implements _Fieldmap.
Definition at line 127 of file FM1DDynamic_fast.cpp.
getFieldstrength()
bool _FM1DDynamic_fast::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const virtual
Implements _Fieldmap.
Definition at line 101 of file FM1DDynamic_fast.cpp.
References computeFieldOffAxis(), computeFieldOnAxis(), Attrib::Distribution::R, and zBegin_m.
getFrequency()
double _FM1DDynamic_fast::getFrequency () const virtual
Implements _Fieldmap.
Definition at line 141 of file FM1DDynamic_fast.cpp.
References frequency_m.
getInfo()
void _FM1DDynamic_fast::getInfo (Inform * msg) virtual
Implements _Fieldmap.
Definition at line 134 of file FM1DDynamic_fast.cpp.
References endl(), _Fieldmap::Filename_m, zBegin_m, and zEnd_m.
getOnaxisEz()
void _FM1DDynamic_fast::getOnaxisEz (std::vector< std::pair< double, double >> & eZ) virtual
Definition at line 149 of file FM1DDynamic_fast.cpp.
References _Fieldmap::Filename_m, numberOfGridPoints_m, readFileData(), scaleField(), and stripFileHeader().
isInside()
bool _FM1DDynamic_fast::isInside (const Vector_t & r) const inline virtual
Reimplemented from _Fieldmap.
Definition at line 82 of file FM1DDynamic_fast.h.
References zBegin_m, and zEnd_m.
normalizeField()
void _FM1DDynamic_fast::normalizeField (double maxEz, std::vector< double > & fourierCoefs) private
Definition at line 325 of file FM1DDynamic_fast.cpp.
References numberOfGridPoints_m, onAxisField_m, and Units::Vpm2MVpm.
Referenced by readMap().
prepareForMapCheck()
void _FM1DDynamic_fast::prepareForMapCheck (std::vector< double > & fourierCoefs) private
Definition at line 435 of file FM1DDynamic_fast.cpp.
References accuracy_m, _Fieldmap::checkMap(), deltaZ_m, length_m, numberOfGridPoints_m, onAxisFieldAccel_m, and onAxisFieldInterpolants_m.
Referenced by readMap().
readFileData() [1/2]
double _FM1DDynamic_fast::readFileData (std::ifstream & fieldFile, double fieldData[]) private
Definition at line 337 of file FM1DDynamic_fast.cpp.
References abs(), _Fieldmap::normalize_m, and numberOfGridPoints_m.
Referenced by getOnaxisEz(), and readMap().
readFileData() [2/2]
double _FM1DDynamic_fast::readFileData (std::ifstream & fieldFile, std::vector< std::pair< double, double >> & eZ) private
Definition at line 353 of file FM1DDynamic_fast.cpp.
References abs(), _Fieldmap::normalize_m, numberOfGridPoints_m, zBegin_m, and zEnd_m.
readFileHeader()
bool _FM1DDynamic_fast::readFileHeader (std::ifstream & fieldFile) private
Definition at line 371 of file FM1DDynamic_fast.cpp.
References accuracy_m, Physics::e, frequency_m, _Fieldmap::normalize_m, numberOfGridPoints_m, rBegin_m, rEnd_m, Util::toUpper(), zBegin_m, and zEnd_m.
Referenced by _FM1DDynamic_fast().
readMap()
void _FM1DDynamic_fast::readMap () private virtual
Implements _Fieldmap.
Definition at line 52 of file FM1DDynamic_fast.cpp.
References computeFieldDerivatives(), computeFourierCoefficients(), computeInterpolationVectors(), endl(), _Fieldmap::Filename_m, INFOMSG, normalizeField(), numberOfGridPoints_m, onAxisField_m, prepareForMapCheck(), readFileData(), stripFileHeader(), and _Fieldmap::typeset_msg().
scaleField()
void _FM1DDynamic_fast::scaleField (double maxEz, std::vector< std::pair< double, double >> & eZ) private
Definition at line 417 of file FM1DDynamic_fast.cpp.
References _Fieldmap::normalize_m, and numberOfGridPoints_m.
Referenced by getOnaxisEz().
setFrequency()
void _FM1DDynamic_fast::setFrequency (double freq) virtual
Implements _Fieldmap.
Definition at line 145 of file FM1DDynamic_fast.cpp.
References frequency_m.
stripFileHeader()
void _FM1DDynamic_fast::stripFileHeader (std::ifstream & fieldFile) private
Definition at line 425 of file FM1DDynamic_fast.cpp.
References _Fieldmap::getLine().
Referenced by getOnaxisEz(), and readMap().
swap()
void _FM1DDynamic_fast::swap () virtual
Implements _Fieldmap.
Definition at line 131 of file FM1DDynamic_fast.cpp.
Friends And Related Function Documentation
_Fieldmap
friend class _Fieldmap friend
Definition at line 79 of file FM1DDynamic_fast.h.
Member Data Documentation
accuracy_m
unsigned int _FM1DDynamic_fast::accuracy_m private
Field grid point spacing.
Definition at line 65 of file FM1DDynamic_fast.h.
Referenced by computeFieldDerivatives(), computeFourierCoefficients(), prepareForMapCheck(), and readFileHeader().
deltaZ_m
double _FM1DDynamic_fast::deltaZ_m private
Number of grid points in field input file.
Definition at line 64 of file FM1DDynamic_fast.h.
Referenced by _FM1DDynamic_fast(), computeFieldDerivatives(), computeInterpolationVectors(), and prepareForMapCheck().
frequency_m
double _FM1DDynamic_fast::frequency_m private
Definition at line 55 of file FM1DDynamic_fast.h.
Referenced by computeFieldOffAxis(), convertHeaderData(), getFrequency(), readFileHeader(), and setFrequency().
length_m
double _FM1DDynamic_fast::length_m private
Longitudinal end of field.
Definition at line 62 of file FM1DDynamic_fast.h.
Referenced by _FM1DDynamic_fast(), computeFieldDerivatives(), and prepareForMapCheck().
numberOfGridPoints_m
unsigned int _FM1DDynamic_fast::numberOfGridPoints_m private
Field length.
Definition at line 63 of file FM1DDynamic_fast.h.
Referenced by _FM1DDynamic_fast(), checkFileData(), computeFieldDerivatives(), computeFourierCoefficients(), computeInterpolationVectors(), getOnaxisEz(), normalizeField(), prepareForMapCheck(), readFileData(), readFileHeader(), readMap(), and scaleField().
onAxisField_m
double* _FM1DDynamic_fast::onAxisField_m private
Definition at line 67 of file FM1DDynamic_fast.h.
Referenced by _FM1DDynamic_fast(), computeInterpolationVectors(), freeMap(), normalizeField(), and readMap().
onAxisFieldAccel_m
gsl_interp_accel* _FM1DDynamic_fast::onAxisFieldAccel_m private
On axis field third derivative interpolation structure.
Corresponding interpolation evaluation accelerators.
Definition at line 74 of file FM1DDynamic_fast.h.
Referenced by computeFieldOnAxis(), computeInterpolationVectors(), freeMap(), and prepareForMapCheck().
onAxisFieldInterpolants_m
gsl_spline* _FM1DDynamic_fast::onAxisFieldInterpolants_m private
On axis field data.
Definition at line 68 of file FM1DDynamic_fast.h.
Referenced by computeFieldOnAxis(), computeInterpolationVectors(), freeMap(), and prepareForMapCheck().
onAxisFieldPAccel_m
gsl_interp_accel* _FM1DDynamic_fast::onAxisFieldPAccel_m private
Definition at line 75 of file FM1DDynamic_fast.h.
Referenced by computeFieldOnAxis(), computeInterpolationVectors(), freeMap(), and getFieldDerivative().
onAxisFieldPInterpolants_m
gsl_spline* _FM1DDynamic_fast::onAxisFieldPInterpolants_m private
On axis field interpolation structure.
Definition at line 69 of file FM1DDynamic_fast.h.
Referenced by computeFieldOnAxis(), computeInterpolationVectors(), freeMap(), and getFieldDerivative().
onAxisFieldPPAccel_m
gsl_interp_accel* _FM1DDynamic_fast::onAxisFieldPPAccel_m private
Definition at line 76 of file FM1DDynamic_fast.h.
Referenced by computeFieldOnAxis(), computeInterpolationVectors(), and freeMap().
onAxisFieldPPInterpolants_m
gsl_spline* _FM1DDynamic_fast::onAxisFieldPPInterpolants_m private
On axis field first derivative interpolation structure.
Definition at line 70 of file FM1DDynamic_fast.h.
Referenced by computeFieldOnAxis(), computeInterpolationVectors(), and freeMap().
onAxisFieldPPPAccel_m
gsl_interp_accel* _FM1DDynamic_fast::onAxisFieldPPPAccel_m private
Definition at line 77 of file FM1DDynamic_fast.h.
Referenced by computeFieldOnAxis(), computeInterpolationVectors(), and freeMap().
onAxisFieldPPPInterpolants_m
gsl_spline* _FM1DDynamic_fast::onAxisFieldPPPInterpolants_m private
On axis field second derivative interpolation structure.
Definition at line 71 of file FM1DDynamic_fast.h.
Referenced by computeFieldOnAxis(), computeInterpolationVectors(), and freeMap().
rBegin_m
double _FM1DDynamic_fast::rBegin_m private
2 Pi divided by the field RF wavelength squared.
Definition at line 58 of file FM1DDynamic_fast.h.
Referenced by convertHeaderData(), and readFileHeader().
rEnd_m
double _FM1DDynamic_fast::rEnd_m private
Minimum radius of field.
Definition at line 59 of file FM1DDynamic_fast.h.
Referenced by convertHeaderData(), and readFileHeader().
twoPiOverLambdaSq_m
double _FM1DDynamic_fast::twoPiOverLambdaSq_m private
Field angular frequency (Hz).
Definition at line 56 of file FM1DDynamic_fast.h.
Referenced by computeFieldOffAxis(), and convertHeaderData().
zBegin_m
double _FM1DDynamic_fast::zBegin_m private
Maximum radius of field.
Definition at line 60 of file FM1DDynamic_fast.h.
Referenced by _FM1DDynamic_fast(), convertHeaderData(), getFieldDerivative(), getFieldDimensions(), getFieldstrength(), getInfo(), isInside(), readFileData(), and readFileHeader().
zEnd_m
double _FM1DDynamic_fast::zEnd_m private
Longitudinal start of field.
Definition at line 61 of file FM1DDynamic_fast.h.
Referenced by _FM1DDynamic_fast(), convertHeaderData(), getFieldDimensions(), getInfo(), isInside(), readFileData(), and readFileHeader().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/FM1DDynamic_fast.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/FM1DDynamic_fast.cpp