OPAL (Object Oriented Parallel Accelerator Library): _FM1DProfile1 Class Reference
_FM1DProfile1 Class Reference
#include <FM1DProfile1.h>
Public Member Functions
virtual ~_FM1DProfile1 ()
virtual bool getFieldDerivative (const Vector_t &X, Vector_t &E, Vector_t &B, const DiffDirection &dir) const
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void getFieldDimensions (double &zBegin, double &zEnd) const
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const
virtual bool getFieldstrength (const Vector_t &X, Vector_t &strength, Vector_t &info) const
virtual double getFrequency () const
virtual void getInfo (Inform *)
virtual void setFrequency (double freq)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void swap ()
virtual void setFieldGap (double gap)
Public Member Functions inherited from _Fieldmap
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
MapType getType ()
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &onaxis)
virtual bool isInside (const Vector_t &) const
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Private Member Functions
_FM1DProfile1 (const std::string &filename)
Constructor with field map file name.
virtual void freeMap ()
virtual void readMap ()
double computeEntranceFringe (double z) const
double computeExitFringe (double z) const
double computeFringe (const std::vector< double > &coefs, double z) const
Static Private Member Functions
static FM1DProfile1 create (const std::string &filename)
Private Attributes
double entranceParameter1_m
double entranceParameter2_m
double entranceParameter3_m
double exitParameter1_m
double exitParameter2_m
double exitParameter3_m
std::vector< double > engeCoeffsEntry_m
Enge coefficients for map entry and exit regions.
std::vector< double > engeCoeffsExit_m
int polyOrderEntry_m
int polyOrderExit_m
Enge function order for entry region.
double gapHeight_m
Enge function order for entry region.
double sBegin_m
Full gap height of field map.
double sEnd_m
Start of field map in s coordinates (m).
Friends
class _Fieldmap
End of field map in s coordinates (m).
Additional Inherited Members
Static Public Member Functions inherited from _Fieldmap
static Fieldmap getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions inherited from _Fieldmap
_Fieldmap ()=delete
_Fieldmap (const std::string &filename)
virtual ~_Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions inherited from _Fieldmap
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes inherited from _Fieldmap
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Detailed Description
Definition at line 14 of file FM1DProfile1.h.
Constructor & Destructor Documentation
~_FM1DProfile1()
_FM1DProfile1::~_FM1DProfile1 () virtual
Definition at line 126 of file FM1DProfile1.cpp.
_FM1DProfile1()
_FM1DProfile1::_FM1DProfile1 (const std::string & filename) private
Constructor with field map file name.
Definition at line 10 of file FM1DProfile1.cpp.
References abs(), Units::cm2m, _Fieldmap::disableFieldmapWarning(), entranceParameter1_m, entranceParameter2_m, entranceParameter3_m, exitParameter1_m, exitParameter2_m, exitParameter3_m, _Fieldmap::Filename_m, gapHeight_m, _Fieldmap::interpreteEOF(), _Fieldmap::noFieldmapWarning(), polyOrderEntry_m, polyOrderExit_m, sBegin_m, sEnd_m, T1DProfile1, and _Fieldmap::Type.
Referenced by create().
Member Function Documentation
computeEntranceFringe()
double _FM1DProfile1::computeEntranceFringe (double z) const private
Definition at line 296 of file FM1DProfile1.cpp.
References computeFringe(), engeCoeffsEntry_m, and gapHeight_m.
Referenced by readMap().
computeExitFringe()
double _FM1DProfile1::computeExitFringe (double z) const private
Definition at line 300 of file FM1DProfile1.cpp.
References computeFringe(), engeCoeffsExit_m, and gapHeight_m.
Referenced by readMap().
computeFringe()
double _FM1DProfile1::computeFringe (const std::vector< double > & coefs, double z) const private
Definition at line 304 of file FM1DProfile1.cpp.
References exp(), and pow().
Referenced by computeEntranceFringe(), and computeExitFringe().
create()
FM1DProfile1 _FM1DProfile1::create (const std::string & filename) static private
Definition at line 129 of file FM1DProfile1.cpp.
References _FM1DProfile1().
Referenced by _Fieldmap::getFieldmap().
freeMap()
void _FM1DProfile1::freeMap () private virtual
Implements _Fieldmap.
Definition at line 214 of file FM1DProfile1.cpp.
get1DProfile1EngeCoeffs()
void _FM1DProfile1::get1DProfile1EngeCoeffs (std::vector< double > & engeCoeffsEntry, std::vector< double > & engeCoeffsExit) virtual
Reimplemented from _Fieldmap.
Definition at line 264 of file FM1DProfile1.cpp.
References engeCoeffsEntry_m, and engeCoeffsExit_m.
get1DProfile1EntranceParam()
void _FM1DProfile1::get1DProfile1EntranceParam (double & entranceParameter1, double & entranceParameter2, double & entranceParameter3) virtual
Reimplemented from _Fieldmap.
Definition at line 271 of file FM1DProfile1.cpp.
References entranceParameter1_m, entranceParameter2_m, and entranceParameter3_m.
get1DProfile1ExitParam()
void _FM1DProfile1::get1DProfile1ExitParam (double & exitParameter1, double & exitParameter2, double & exitParameter3) virtual
Reimplemented from _Fieldmap.
Definition at line 279 of file FM1DProfile1.cpp.
References exitParameter1_m, exitParameter2_m, and exitParameter3_m.
getFieldDerivative()
bool _FM1DProfile1::getFieldDerivative (const Vector_t & X, Vector_t & E, Vector_t & B, const DiffDirection & dir) const virtual
Implements _Fieldmap.
Definition at line 227 of file FM1DProfile1.cpp.
getFieldDimensions() [1/2]
void _FM1DProfile1::getFieldDimensions (double & zBegin, double & zEnd) const virtual
Implements _Fieldmap.
Definition at line 234 of file FM1DProfile1.cpp.
References sBegin_m, and sEnd_m.
getFieldDimensions() [2/2]
void _FM1DProfile1::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const virtual
Implements _Fieldmap.
Definition at line 239 of file FM1DProfile1.cpp.
getFieldGap()
double _FM1DProfile1::getFieldGap () virtual
Reimplemented from _Fieldmap.
Definition at line 287 of file FM1DProfile1.cpp.
References gapHeight_m.
getFieldstrength()
bool _FM1DProfile1::getFieldstrength (const Vector_t & X, Vector_t & strength, Vector_t & info) const virtual
Implements _Fieldmap.
Definition at line 217 of file FM1DProfile1.cpp.
getFrequency()
double _FM1DProfile1::getFrequency () const virtual
Implements _Fieldmap.
Definition at line 257 of file FM1DProfile1.cpp.
getInfo()
void _FM1DProfile1::getInfo (Inform * msg) virtual
Implements _Fieldmap.
Definition at line 251 of file FM1DProfile1.cpp.
References endl(), and _Fieldmap::Filename_m.
readMap()
void _FM1DProfile1::readMap () private virtual
Implements _Fieldmap.
Definition at line 134 of file FM1DProfile1.cpp.
References computeEntranceFringe(), computeExitFringe(), endl(), engeCoeffsEntry_m, engeCoeffsExit_m, entranceParameter1_m, entranceParameter3_m, exitParameter1_m, exitParameter3_m, _Fieldmap::Filename_m, INFOMSG, level3(), polyOrderEntry_m, polyOrderExit_m, and _Fieldmap::typeset_msg().
setFieldGap()
void _FM1DProfile1::setFieldGap (double gap) virtual
Reimplemented from _Fieldmap.
Definition at line 290 of file FM1DProfile1.cpp.
References gapHeight_m.
setFrequency()
void _FM1DProfile1::setFrequency (double freq) virtual
Implements _Fieldmap.
Definition at line 261 of file FM1DProfile1.cpp.
swap()
void _FM1DProfile1::swap () virtual
Implements _Fieldmap.
Definition at line 248 of file FM1DProfile1.cpp.
Friends And Related Function Documentation
_Fieldmap
friend class _Fieldmap friend
End of field map in s coordinates (m).
Definition at line 88 of file FM1DProfile1.h.
Member Data Documentation
engeCoeffsEntry_m
std::vector<double> _FM1DProfile1::engeCoeffsEntry_m private
Enge coefficients for map entry and exit regions.
Definition at line 78 of file FM1DProfile1.h.
Referenced by computeEntranceFringe(), get1DProfile1EngeCoeffs(), and readMap().
engeCoeffsExit_m
std::vector<double> _FM1DProfile1::engeCoeffsExit_m private
Definition at line 79 of file FM1DProfile1.h.
Referenced by computeExitFringe(), get1DProfile1EngeCoeffs(), and readMap().
entranceParameter1_m
double _FM1DProfile1::entranceParameter1_m private
Definition at line 70 of file FM1DProfile1.h.
Referenced by _FM1DProfile1(), get1DProfile1EntranceParam(), and readMap().
entranceParameter2_m
double _FM1DProfile1::entranceParameter2_m private
Definition at line 71 of file FM1DProfile1.h.
Referenced by _FM1DProfile1(), and get1DProfile1EntranceParam().
entranceParameter3_m
double _FM1DProfile1::entranceParameter3_m private
Definition at line 72 of file FM1DProfile1.h.
Referenced by _FM1DProfile1(), get1DProfile1EntranceParam(), and readMap().
exitParameter1_m
double _FM1DProfile1::exitParameter1_m private
Definition at line 73 of file FM1DProfile1.h.
Referenced by _FM1DProfile1(), get1DProfile1ExitParam(), and readMap().
exitParameter2_m
double _FM1DProfile1::exitParameter2_m private
Definition at line 74 of file FM1DProfile1.h.
Referenced by _FM1DProfile1(), and get1DProfile1ExitParam().
exitParameter3_m
double _FM1DProfile1::exitParameter3_m private
Definition at line 75 of file FM1DProfile1.h.
Referenced by _FM1DProfile1(), get1DProfile1ExitParam(), and readMap().
gapHeight_m
double _FM1DProfile1::gapHeight_m private
Enge function order for entry region.
Definition at line 83 of file FM1DProfile1.h.
Referenced by _FM1DProfile1(), computeEntranceFringe(), computeExitFringe(), getFieldGap(), and setFieldGap().
polyOrderEntry_m
int _FM1DProfile1::polyOrderEntry_m private
Definition at line 81 of file FM1DProfile1.h.
Referenced by _FM1DProfile1(), and readMap().
polyOrderExit_m
int _FM1DProfile1::polyOrderExit_m private
Enge function order for entry region.
Definition at line 82 of file FM1DProfile1.h.
Referenced by _FM1DProfile1(), and readMap().
sBegin_m
double _FM1DProfile1::sBegin_m private
Full gap height of field map.
Definition at line 85 of file FM1DProfile1.h.
Referenced by _FM1DProfile1(), and getFieldDimensions().
sEnd_m
double _FM1DProfile1::sEnd_m private
Start of field map in s coordinates (m).
Definition at line 86 of file FM1DProfile1.h.
Referenced by _FM1DProfile1(), and getFieldDimensions().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/FM1DProfile1.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/FM1DProfile1.cpp