OPAL (Object Oriented Parallel Accelerator Library): mslang::Function Struct Reference
mslang::Function Struct Reference abstract
#include <MSLang.h>
Public Member Functions
virtual ~Function ()
virtual void print (int indent)=0
virtual void apply (std::vector< std::shared_ptr< Base >> &bfuncs)=0
Static Public Member Functions
static bool parse (iterator &it, const iterator &end, Function *&fun)
Static Public Attributes
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\((.*)"
Detailed Description
Definition at line 25 of file MSLang.h.
Constructor & Destructor Documentation
~Function()
virtual mslang::Function::~Function () inline virtual
Definition at line 26 of file MSLang.h.
Member Function Documentation
apply()
virtual void mslang::Function::apply (std::vector< std::shared_ptr< Base >> & bfuncs) pure virtual
Referenced by mslang::Rotation::apply(), mslang::Union::apply(), mslang::Translation::apply(), mslang::Shear::apply(), mslang::Repeat::apply(), mslang::Difference::apply(), mslang::Intersection::apply(), mslang::SymmetricDifference::apply(), and FlexibleCollimator::setDescription().
parse()
bool mslang::Function::parse (iterator & it, const iterator & end, Function *& fun) static
Definition at line 48 of file MSLang.cpp.
References end(), FCall, mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Rotation::parse_detail(), mslang::Union::parse_detail(), mslang::Translation::parse_detail(), mslang::Shear::parse_detail(), mslang::Repeat::parse_detail(), mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Ellipse::parse_detail(), and mslang::Rectangle::parse_detail().
Referenced by mslang::parse(), mslang::Rotation::parse_detail(), mslang::Union::parse_detail(), mslang::Translation::parse_detail(), mslang::Shear::parse_detail(), mslang::Repeat::parse_detail(), mslang::Difference::parse_detail(), mslang::Intersection::parse_detail(), and mslang::SymmetricDifference::parse_detail().
print()
virtual void mslang::Function::print (int indent) pure virtual
Implemented in mslang::Ellipse, mslang::Rectangle, mslang::Difference, mslang::Intersection, mslang::SymmetricDifference, mslang::Triangle, mslang::Repeat, mslang::Shear, mslang::Translation, mslang::Union, mslang::Rotation, mslang::Polygon, and mslang::Mask.
Referenced by mslang::Rotation::print(), mslang::Shear::print(), mslang::Translation::print(), mslang::Repeat::print(), mslang::Intersection::print(), mslang::SymmetricDifference::print(), and mslang::Difference::print().
Member Data Documentation
Double
const std::string mslang::Function::Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static
Definition at line 34 of file MSLang.h.
FCall
const std::string mslang::Function::FCall = "([a-z_]*)\\((.*)" static
Definition at line 36 of file MSLang.h.
Referenced by parse().
UDouble
const std::string mslang::Function::UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)" static
Definition at line 33 of file MSLang.h.
Referenced by mslang::Rectangle::parse_detail().
UInt
const std::string mslang::Function::UInt = "([0-9]+)" static
Definition at line 35 of file MSLang.h.
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang.cpp