OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyNDGrid Namespace Reference
PyOpal::PyNDGrid Namespace Reference
Functions
NDGrid initialiseVariableSpacing (boost::python::list gridCoordinates)
NDGrid initialiseFixedSpacing (boost::python::list size, boost::python::list spacing, boost::python::list min)
py::list coordVector (NDGrid &grid, int dimension)
BOOST_PYTHON_MODULE (ndgrid)
Variables
Inform * gmsg
const char * module_docstring = "ndgrid module for generating grids"
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyNDGrid::BOOST_PYTHON_MODULE (ndgrid)
Definition at line 94 of file PyNDGrid.cpp.
References coordVector(), interpolation::NDGrid::getPositionDimension(), initialiseFixedSpacing(), initialiseVariableSpacing(), PyOpal::ExceptionTranslation::registerExceptions(), and interpolation::NDGrid::size().
coordVector()
py::list PyOpal::PyNDGrid::coordVector (NDGrid & grid, int dimension)
Definition at line 76 of file PyNDGrid.cpp.
References interpolation::NDGrid::coordVector(), and interpolation::NDGrid::getPositionDimension().
Referenced by BOOST_PYTHON_MODULE().
initialiseFixedSpacing()
NDGrid PyOpal::PyNDGrid::initialiseFixedSpacing (boost::python::list size, boost::python::list spacing, boost::python::list min)
Definition at line 55 of file PyNDGrid.cpp.
References min().
Referenced by BOOST_PYTHON_MODULE().
initialiseVariableSpacing()
NDGrid PyOpal::PyNDGrid::initialiseVariableSpacing (boost::python::list gridCoordinates)
Definition at line 41 of file PyNDGrid.cpp.
Referenced by BOOST_PYTHON_MODULE().
Variable Documentation
gmsg
Inform* PyOpal::PyNDGrid::gmsg
Definition at line 70 of file Main.cpp.
module_docstring
const char* PyOpal::PyNDGrid::module_docstring = "ndgrid module for generating grids"
Definition at line 92 of file PyNDGrid.cpp.