OPAL (Object Oriented Parallel Accelerator Library): Vacuum Class Reference
Vacuum Class Reference
#include <Vacuum.h>
Public Member Functions
Vacuum (const std::string &name)
Constructor with given name.
Vacuum ()
Vacuum (const Vacuum &rhs)
virtual ~Vacuum ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to Vacuum.
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual bool checkVacuum (PartBunchBase< double, 3 > *bunch, Cyclotron *cycl)
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void initialise (PartBunchBase< double, 3 > *bunch)
virtual void finalise () override
virtual bool bends () const override
virtual void goOnline (const double &kineticEnergy) override
virtual void goOffline () override
virtual ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
bool checkPoint (const Vector_t &R)
double checkPressure (const Vector_t &R)
void setResidualGas (std::string gas)
ResidualGas getResidualGas () const
std::string getResidualGasName ()
void setPressure (double pressure)
double getPressure () const
void setPressureMapFN (std::string pmapfn)
std::string getPressureMapFN () const
void setPScale (double ps)
double getPScale () const
void setTemperature (double temperature)
double getTemperature () const
void setStop (bool stopflag)
bool getStop () const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
virtual EMField & getField ()=0
Return field.
virtual const EMField & getField () const =0
Return field.
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Member Functions
void initR (double rmin, double dr, int nrad)
void getPressureFromFile ()
int idx (int irad, int ktet)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes
PFieldData PField_m
PPositions PP_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Private Member Functions
void operator= (const Vacuum &)
void updateParticleAttributes ()
void print ()
Private Attributes
ParticleMatterInteractionHandler * parmatint_m
mm
ResidualGas gas_m
parameters for Vacuum
double pressure_m
Type of gas for residual vacuum.
std::string pmapfn_m
mbar
double pscale_m
stores the filename of the pressure map
double temperature_m
a scale factor for the P-field
bool stop_m
K.
double minr_m
Flag if particles should be stripped or stopped.
double maxr_m
mm
double minz_m
mm
double maxz_m
mm
Static Private Attributes
static const boost::bimap< ResidualGas, std::string > bmResidualGasString_s
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 61 of file Vacuum.h.
Constructor & Destructor Documentation
Vacuum() [1/3]
Vacuum::Vacuum (const std::string & name) explicit
Constructor with given name.
Definition at line 76 of file Vacuum.cpp.
References NOGAS.
Vacuum() [2/3]
Vacuum::Vacuum ()
Definition at line 55 of file Vacuum.cpp.
Vacuum() [3/3]
Vacuum::Vacuum (const Vacuum & rhs)
Definition at line 60 of file Vacuum.cpp.
~Vacuum()
Vacuum::~Vacuum () virtual
Definition at line 92 of file Vacuum.cpp.
References goOffline(), and Component::online_m.
Member Function Documentation
accept()
void Vacuum::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to Vacuum.
Implements ElementBase.
Definition at line 98 of file Vacuum.cpp.
References BeamlineVisitor::visitVacuum().
apply()
bool Vacuum::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 192 of file Vacuum.cpp.
applyToReferenceParticle()
bool Vacuum::applyToReferenceParticle (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 196 of file Vacuum.cpp.
bends()
bool Vacuum::bends () const inline override virtual
Implements Component.
Definition at line 169 of file Vacuum.h.
checkPoint()
bool Vacuum::checkPoint (const Vector_t & R)
Definition at line 179 of file Vacuum.cpp.
References ElementBase::getElementLength(), OpalData::getInstance(), maxz_m, minr_m, minz_m, Attrib::Distribution::R, and sqrt().
Referenced by checkVacuum().
checkPressure()
double Vacuum::checkPressure (const Vector_t & R)
Definition at line 298 of file Vacuum.cpp.
References atan(), PPositions::delr_m, PPositions::dtet_m, endl(), ElementBase::getName(), getPressure(), gmsg, idx(), level4(), PFieldData::nrad_m, PFieldData::ntetS_m, PField_m, PFieldData::pfld_m, Physics::pi, pmapfn_m, PP_m, Attrib::Distribution::R, matheval::detail::math::rad(), Units::rad2deg, PPositions::rmin_m, sqrt(), and Physics::two_pi.
Referenced by BeamStrippingPhysics::doPhysics().
checkVacuum()
bool Vacuum::checkVacuum (PartBunchBase< double, 3 > * bunch, Cyclotron * cycl) virtual
Definition at line 201 of file Vacuum.cpp.
References ParticleMatterInteractionHandler::apply(), PartBunchBase< T, Dim >::Bin, checkPoint(), euclidean_norm(), PartBunchBase< T, Dim >::get_bounds(), PartBunchBase< T, Dim >::getLocalNum(), Cyclotron::getMaxR(), Cyclotron::getMaxZ(), Cyclotron::getMinR(), Cyclotron::getMinZ(), gmsg, maxr_m, maxz_m, minr_m, minz_m, parmatint_m, ParticleMatterInteractionHandler::print(), PartBunchBase< T, Dim >::R, and reduce().
Referenced by ParallelCyclotronTracker::applyPluginElements().
finalise()
void Vacuum::finalise () override virtual
Implements Component.
Definition at line 266 of file Vacuum.cpp.
References endl(), ElementBase::getName(), gmsg, goOffline(), and Component::online_m.
getDimensions()
void Vacuum::getDimensions (double & zBegin, double & zEnd) const override virtual
Implements Component.
Definition at line 289 of file Vacuum.cpp.
References ElementBase::getElementLength().
getPressure()
double Vacuum::getPressure () const
Definition at line 128 of file Vacuum.cpp.
References pressure_m.
Referenced by checkPressure(), and ParallelCyclotronTracker::visitVacuum().
getPressureFromFile()
void Vacuum::getPressureFromFile () protected
Definition at line 381 of file Vacuum.cpp.
References CHECK_VAC_FSCANF_EOF, PPositions::delr_m, PPositions::dtet_m, endl(), gmsg, idx(), Units::mm2m, PFieldData::nrad_m, PFieldData::ntet_m, PFieldData::ntetS_m, PFieldData::ntot_m, PPositions::Pfact_m, PField_m, PFieldData::pfld_m, pmapfn_m, PP_m, pscale_m, PPositions::rmin_m, and PPositions::tetmin_m.
Referenced by initialise().
getPressureMapFN()
std::string Vacuum::getPressureMapFN () const
Definition at line 141 of file Vacuum.cpp.
References pmapfn_m.
Referenced by ParallelCyclotronTracker::visitVacuum().
getPScale()
double Vacuum::getPScale () const
Definition at line 149 of file Vacuum.cpp.
References pscale_m.
Referenced by ParallelCyclotronTracker::visitVacuum().
getResidualGas()
ResidualGas Vacuum::getResidualGas () const
Definition at line 111 of file Vacuum.cpp.
References gas_m.
Referenced by BeamStrippingPhysics::computeCrossSection(), and BeamStrippingPhysics::getSecondaryParticles().
getResidualGasName()
std::string Vacuum::getResidualGasName ()
Definition at line 115 of file Vacuum.cpp.
References bmResidualGasString_s, gas_m, and NOGAS.
Referenced by BeamStrippingPhysics::print(), print(), and ParallelCyclotronTracker::visitVacuum().
getStop()
bool Vacuum::getStop () const
Definition at line 175 of file Vacuum.cpp.
References stop_m.
Referenced by BeamStrippingPhysics::doPhysics(), and ParallelCyclotronTracker::visitVacuum().
getTemperature()
double Vacuum::getTemperature () const
Definition at line 162 of file Vacuum.cpp.
References temperature_m.
Referenced by BeamStrippingPhysics::doPhysics(), and ParallelCyclotronTracker::visitVacuum().
getType()
ElementType Vacuum::getType () const override virtual
Get element type std::string.
Reimplemented from Component.
Definition at line 294 of file Vacuum.cpp.
References VACUUM.
goOffline()
void Vacuum::goOffline () override virtual
Reimplemented from Component.
Definition at line 285 of file Vacuum.cpp.
References Component::online_m.
Referenced by finalise(), and ~Vacuum().
goOnline()
void Vacuum::goOnline (const double & kineticEnergy) override virtual
Reimplemented from Component.
Definition at line 272 of file Vacuum.cpp.
References Component::online_m.
Referenced by initialise().
idx()
int Vacuum::idx (int irad, int ktet) inline protected
Definition at line 127 of file Vacuum.h.
References PFieldData::ntetS_m, and PField_m.
Referenced by checkPressure(), and getPressureFromFile().
initialise() [1/2]
void Vacuum::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Implements Component.
Definition at line 233 of file Vacuum.cpp.
References ElementBase::getElementLength(), and print().
Referenced by ParallelCyclotronTracker::visitVacuum().
initialise() [2/2]
void Vacuum::initialise (PartBunchBase< double, 3 > * bunch) virtual
Definition at line 242 of file Vacuum.cpp.
References PPositions::delr_m, ElementBase::getParticleMatterInteraction(), getPressureFromFile(), goOnline(), initR(), PFieldData::nrad_m, parmatint_m, PField_m, pmapfn_m, PP_m, Component::RefPartBunch_m, PPositions::rmin_m, and updateParticleAttributes().
initR()
void Vacuum::initR (double rmin, double dr, int nrad) protected
Definition at line 372 of file Vacuum.cpp.
References PPositions::delr_m, PP_m, and PPositions::rarr_m.
Referenced by initialise().
operator=()
void Vacuum::operator= (const Vacuum &) private
print()
void Vacuum::print () private
Definition at line 276 of file Vacuum.cpp.
References endl(), ParticleMatterInteractionHandler::getElement(), ElementBase::getName(), getResidualGasName(), ElementBase::getTypeString(), gmsg, level2(), parmatint_m, and pressure_m.
Referenced by initialise().
setPressure()
void Vacuum::setPressure (double pressure)
Definition at line 124 of file Vacuum.cpp.
References pressure_m.
Referenced by OpalVacuum::update().
setPressureMapFN()
void Vacuum::setPressureMapFN (std::string pmapfn)
Definition at line 137 of file Vacuum.cpp.
References pmapfn_m.
Referenced by OpalVacuum::update().
setPScale()
void Vacuum::setPScale (double ps)
Definition at line 145 of file Vacuum.cpp.
References pscale_m.
Referenced by OpalVacuum::update().
setResidualGas()
void Vacuum::setResidualGas (std::string gas)
Definition at line 102 of file Vacuum.cpp.
References bmResidualGasString_s, gas_m, and NOGAS.
Referenced by OpalVacuum::update().
setStop()
void Vacuum::setStop (bool stopflag)
Definition at line 171 of file Vacuum.cpp.
References stop_m.
Referenced by OpalVacuum::update().
setTemperature()
void Vacuum::setTemperature (double temperature)
Definition at line 158 of file Vacuum.cpp.
References temperature_m.
Referenced by OpalVacuum::update().
updateParticleAttributes()
void Vacuum::updateParticleAttributes () private
Definition at line 259 of file Vacuum.cpp.
References Units::eV2GeV, PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getM(), PartBunchBase< T, Dim >::getQ(), PartBunchBase< T, Dim >::M, PartBunchBase< T, Dim >::Q, Physics::q_e, and Component::RefPartBunch_m.
Referenced by initialise().
Member Data Documentation
bmResidualGasString_s
const boost::bimap< ResidualGas, std::string > Vacuum::bmResidualGasString_s static private
Initial value:
=
    boost::assign::list_of<const boost::bimap<ResidualGas, std::string>::relation>
        (ResidualGas::NOGAS, "NOGAS")
        (ResidualGas::AIR,   "AIR")
        (ResidualGas::H2,    "H2")
Definition at line 156 of file Vacuum.h.
Referenced by getResidualGasName(), and setResidualGas().
gas_m
ResidualGas Vacuum::gas_m private
parameters for Vacuum
Definition at line 139 of file Vacuum.h.
Referenced by getResidualGas(), getResidualGasName(), and setResidualGas().
maxr_m
double Vacuum::maxr_m private
mm
Definition at line 149 of file Vacuum.h.
Referenced by checkVacuum().
maxz_m
double Vacuum::maxz_m private
mm
Definition at line 151 of file Vacuum.h.
Referenced by checkPoint(), and checkVacuum().
minr_m
double Vacuum::minr_m private
Flag if particles should be stripped or stopped.
size limits took from cyclotron
Definition at line 148 of file Vacuum.h.
Referenced by checkPoint(), and checkVacuum().
minz_m
double Vacuum::minz_m private
mm
Definition at line 150 of file Vacuum.h.
Referenced by checkPoint(), and checkVacuum().
parmatint_m
ParticleMatterInteractionHandler* Vacuum::parmatint_m private
mm
Definition at line 154 of file Vacuum.h.
Referenced by checkVacuum(), initialise(), and print().
PField_m
PFieldData Vacuum::PField_m protected
Definition at line 161 of file Vacuum.h.
Referenced by checkPressure(), getPressureFromFile(), idx(), and initialise().
pmapfn_m
std::string Vacuum::pmapfn_m private
mbar
Definition at line 141 of file Vacuum.h.
Referenced by checkPressure(), getPressureFromFile(), getPressureMapFN(), initialise(), and setPressureMapFN().
PP_m
PPositions Vacuum::PP_m protected
Definition at line 164 of file Vacuum.h.
Referenced by checkPressure(), getPressureFromFile(), initialise(), and initR().
pressure_m
double Vacuum::pressure_m private
Type of gas for residual vacuum.
Definition at line 140 of file Vacuum.h.
Referenced by getPressure(), print(), and setPressure().
pscale_m
double Vacuum::pscale_m private
stores the filename of the pressure map
Definition at line 142 of file Vacuum.h.
Referenced by getPressureFromFile(), getPScale(), and setPScale().
stop_m
bool Vacuum::stop_m private
K.
Definition at line 144 of file Vacuum.h.
Referenced by getStop(), and setStop().
temperature_m
double Vacuum::temperature_m private
a scale factor for the P-field
Definition at line 143 of file Vacuum.h.
Referenced by getTemperature(), and setTemperature().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/Vacuum.h
src/Classic/AbsBeamline/Vacuum.cpp