OPAL (Object Oriented Parallel Accelerator Library): EBVectors Class Reference
EBVectors Class Reference
A representation of an electromagnetic field.
#include <EMField.h>
Public Member Functions
EBVectors (const EVector &E, const BVector &B)
Constructor.
EVector getE () const
Get component.
double getEx () const
Get component.
double getEy () const
Get component.
double getEz () const
Get component.
BVector getB () const
Get field.
double getBx () const
Get component.
double getBy () const
Get component.
double getBz () const
Get component.
Private Attributes
EVector E
BVector B
Detailed Description
A representation of an electromagnetic field.
Definition at line 133 of file EMField.h.
Constructor & Destructor Documentation
EBVectors()
EBVectors::EBVectors (const EVector & E, const BVector & B)
Constructor.
Definition at line 93 of file EMField.cpp.
Member Function Documentation
getB()
BVector EBVectors::getB () const
Get field.
Definition at line 114 of file EMField.cpp.
References B.
getBx()
double EBVectors::getBx () const
Get component.
Definition at line 118 of file EMField.cpp.
References B, and BVector::getBx().
getBy()
double EBVectors::getBy () const
Get component.
Definition at line 122 of file EMField.cpp.
References B, and BVector::getBy().
getBz()
double EBVectors::getBz () const
Get component.
Definition at line 126 of file EMField.cpp.
References B, and BVector::getBy().
getE()
EVector EBVectors::getE () const
Get component.
Definition at line 98 of file EMField.cpp.
References E.
getEx()
double EBVectors::getEx () const
Get component.
Definition at line 102 of file EMField.cpp.
References E, and EVector::getEx().
getEy()
double EBVectors::getEy () const
Get component.
Definition at line 106 of file EMField.cpp.
References E, and EVector::getEy().
getEz()
double EBVectors::getEz () const
Get component.
Definition at line 110 of file EMField.cpp.
References E, and EVector::getEz().
Member Data Documentation
B
BVector EBVectors::B private
Definition at line 177 of file EMField.h.
Referenced by getB(), getBx(), getBy(), and getBz().
E
EVector EBVectors::E private
Definition at line 176 of file EMField.h.
Referenced by getE(), getEx(), getEy(), and getEz().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/EMField.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/EMField.cpp