OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Field/GuardCellSizes.h File Reference
GuardCellSizes.h File Reference
#include "Index/NDIndex.h"
#include <iostream>
#include "Field/GuardCellSizes.hpp"
Classes
class GuardCellSizes< Dim >
Functions
template<unsigned Dim>
NDIndex< Dim > AddGuardCells (const NDIndex< Dim > &idx, const GuardCellSizes< Dim > &g)
template<unsigned Dim>
std::ostream & operator<< (std::ostream &, const GuardCellSizes< Dim > &)
Function Documentation
AddGuardCells()
template<unsigned Dim> NDIndex<Dim> AddGuardCells (const NDIndex< Dim > & idx, const GuardCellSizes< Dim > & g) inline
Definition at line 69 of file GuardCellSizes.h.
Referenced by ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), PatchBC< T, D, M, C >::apply(), calcEurekaDomain(), ComponentFunctionFaceBCApply(), ComponentLinearExtrapolateFaceBCApply(), ExtrapolateAndZeroFaceBCApply(), ExtrapolateFaceBCApply(), FunctionFaceBCApply(), BareField< T1, D >::getsingle(), InterpolationFaceBCApply(), LinearExtrapolateFaceBCApply(), FieldLayout< Dim >::new_gc_layout(), PeriodicFaceBCApply(), FieldDebugPrint< T, Dim >::print(), BareField< T1, D >::setup(), UniformCartesian< Dim, MFLOAT >::storeSpacingFields(), and Cartesian< Dim, MFLOAT >::storeSpacingFields().
operator<<()
template<unsigned Dim> std::ostream& operator<< (std::ostream & , const GuardCellSizes< Dim > &)
Definition at line 126 of file GuardCellSizes.hpp.
References Dim.