OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyVerticalFFAMagnet Namespace Reference
PyOpal::PyVerticalFFAMagnet Namespace Reference
Functions
BOOST_PYTHON_MODULE (vertical_ffa_magnet)
Variables
std::string track_run_docstring = std::string()
const char * module_docstring = "build a vertical_ffa_magnet"
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyVerticalFFAMagnet::BOOST_PYTHON_MODULE (vertical_ffa_magnet)
Definition at line 37 of file PyVerticalFFAMagnet.cpp.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::addGetOpalElement(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_class(), and PyOpal::ExceptionTranslation::registerExceptions().
Variable Documentation
module_docstring
const char * PyOpal::PyVerticalFFAMagnet::module_docstring = "build a vertical_ffa_magnet"
Definition at line 13 of file PyVerticalFFAMagnet.cpp.
track_run_docstring
std::string PyOpal::PyVerticalFFAMagnet::track_run_docstring = std::string()
Definition at line 10 of file PyVerticalFFAMagnet.cpp.