OPAL (Object Oriented Parallel Accelerator Library): OPALTimer::Timer Class Reference
OPALTimer::Timer Class Reference
#include <Timer.h>
Public Member Functions
Timer ()
Constructor.
~Timer ()
std::string date () const
Return date.
std::string time () const
Return time.
Private Member Functions
Timer (const Timer &)
void operator= (const Timer &)
Private Attributes
time_t timer
Detailed Description
Definition at line 33 of file Timer.h.
Constructor & Destructor Documentation
Timer() [1/2]
Timer::Timer ()
Constructor.
Definition at line 26 of file Timer.cpp.
References time(), and timer.
~Timer()
Timer::~Timer ()
Definition at line 31 of file Timer.cpp.
Timer() [2/2]
OPALTimer::Timer::Timer (const Timer &) private
Member Function Documentation
date()
std::string Timer::date () const
Return date.
Definition at line 35 of file Timer.cpp.
References timer.
Referenced by GridLBalWriter::fillHeader(), MemoryWriter::fillHeader(), MultiBunchDump::fillHeader(), LBalWriter::fillHeader(), StatWriter::fillHeader(), MemoryProfiler::header(), and AmrMultiGrid::writeSDDSHeader_m().
operator=()
void OPALTimer::Timer::operator= (const Timer &) private
time()
std::string Timer::time () const
Return time.
Definition at line 42 of file Timer.cpp.
References timer.
Referenced by ParallelTTracker::dumpStats(), ParallelTTracker::execute(), MemoryWriter::fillHeader(), GridLBalWriter::fillHeader(), MultiBunchDump::fillHeader(), LBalWriter::fillHeader(), StatWriter::fillHeader(), MemoryProfiler::header(), ScatteringPhysics::print(), Timer(), and AmrMultiGrid::writeSDDSHeader_m().
Member Data Documentation
timer
time_t OPALTimer::Timer::timer private
Definition at line 55 of file Timer.h.
Referenced by date(), time(), and Timer().
The documentation for this class was generated from the following files:
src/Utilities/Timer.h
src/Utilities/Timer.cpp