OPAL (Object Oriented Parallel Accelerator Library): Attributes::BoolArray Class Reference
Attributes::BoolArray Class Reference
Parser for an attribute of type logical array.
#include <BoolArray.h>
Public Member Functions
BoolArray (const std::string &name, const std::string &help)
Constructor.
virtual ~BoolArray ()
virtual const std::string & getType () const
Return attribute type string `‘logical array’'.
virtual void parse (Attribute &, Statement &, bool) const
Parse the attribute.
virtual void parseComponent (Attribute &, Statement &, bool, int) const
Parse a component of the array.
Public Member Functions inherited from AttributeHandler
AttributeHandler (const std::string &name, const std::string &help, AttributeBase *def)
Constructor.
virtual ~AttributeHandler ()
virtual AttributeHandler * clone () const
Make clone.
virtual AttributeBase * getDefault () const
Return default value.
virtual const std::string & getHelp () const
Return help string.
virtual const std::string & getName () const
Return attribute name.
bool isDeferred () const
Return defer flag.
void setDeferred (bool)
Set or reset defer flag.
bool isReadOnly () const
Return read-only flag.
void setReadOnly (bool)
Set or reset read-only flag.
void setPredefinedValues (const std::set< std::string > &, const std::string &)
Add predefined strings values to the help.
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
BoolArray ()
BoolArray (const BoolArray &)
void operator= (const BoolArray &)
Additional Inherited Members
Public Types inherited from AttributeHandler
enum OwnerType {
ELEMENT, COMMAND, SUB_COMMAND, STATEMENT,
NONE
}
Static Public Member Functions inherited from AttributeHandler
static std::multimap< OwnerType, std::string > getOwner (const std::string &att)
static void addAttributeOwner (const std::string &owner, const OwnerType &type, const std::string &name)
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from AttributeHandler
const std::string itsName
Attribute name.
const std::string itsHelp
Help text.
Pointer< AttributeBase > itsDefault
Default value.
bool is_deferred
Defer flag.
bool is_readonly
Read-only flag.
Detailed Description
Parser for an attribute of type logical array.
Definition at line 32 of file BoolArray.h.
Constructor & Destructor Documentation
BoolArray() [1/3]
Attributes::BoolArray::BoolArray (const std::string & name, const std::string & help)
Constructor.
Definition at line 37 of file BoolArray.cpp.
~BoolArray()
Attributes::BoolArray::~BoolArray () virtual
Definition at line 42 of file BoolArray.cpp.
BoolArray() [2/3]
Attributes::BoolArray::BoolArray () private
BoolArray() [3/3]
Attributes::BoolArray::BoolArray (const BoolArray &) private
Member Function Documentation
getType()
const std::string & Attributes::BoolArray::getType () const virtual
Return attribute type string `‘logical array’'.
Implements AttributeHandler.
Definition at line 46 of file BoolArray.cpp.
operator=()
void Attributes::BoolArray::operator= (const BoolArray &) private
parse()
void Attributes::BoolArray::parse (Attribute & attr, Statement & stat, bool eval) const virtual
Parse the attribute.
Implements AttributeHandler.
Definition at line 52 of file BoolArray.cpp.
References AttributeHandler::is_deferred, Expressions::parseBoolArray(), and Attribute::set().
parseComponent()
void Attributes::BoolArray::parseComponent (Attribute & attr, Statement & stat, bool eval, int index) const virtual
Parse a component of the array.
Reimplemented from AttributeHandler.
Definition at line 68 of file BoolArray.cpp.
References Attribute::getBase(), Expressions::parseBool(), Attribute::set(), and Expressions::ADeferred< T >::setComponent().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Attributes/BoolArray.h
/psi/home/gsell/data/src/OPAL/src/src/Attributes/BoolArray.cpp