OPAL (Object Oriented Parallel Accelerator Library): SubBareField< T, Dim, S > Class Template Reference
SubBareField< T, Dim, S > Class Template Reference
#include <SubBareField.h>
Public Types
enum { Dim_u = Dim }
enum { IsExpr = 1 }
typedef T T_t
typedef S Index_t
typedef SubFieldIter< T, Dim, S > iterator
typedef iterator PETE_Expr_t
Public Types inherited from PETE_Expr< SubBareField< T, Dim, S > >
typedef SubBareField< T, Dim, S > Wrapped
Public Member Functions
constexpr SubBareField (const SubBareField< T, Dim, S > &)=default
iterator begin () const
iterator end () const
const S & getDomain () const
void makeNDIndex (NDIndex< Dim > &i)
BareField< T, Dim > & getBareField () const
T get ()
void get (T &r)
bool checkBrackets () const
template<class S2 >
SubBareField< T, Dim, typename SubFieldTraits< T, Dim, S, S2 >::Return_t > operator[] (const S2 &s)
SubBareField< T, Dim, S > & operator= (const SubBareField< T, Dim, S > &)
SubBareField< T, Dim, S > & operator= (T)
template<class B >
SubBareField< T, Dim, S > & operator= (const PETE_Expr< B > &b)
void write (std::ostream &)
iterator MakeExpression () const
PETE_TUTree< OpParens< int >, iterator > operator() (int arg)
PETE_TUTree< OpParens< std::pair< int, int > >, iterator > operator() (int a1, int a2)
template<class S2 >
SubBareField (BareField< T, Dim > &f, const S2 &s)
Public Member Functions inherited from PETE_Expr< SubBareField< T, Dim, S > >
SubBareField< T, Dim, S > & PETE_unwrap ()
const SubBareField< T, Dim, S > & PETE_unwrap () const
Static Public Member Functions
static int getSubsetType ()
Protected Member Functions
bool checkAddBrackets (unsigned int)
Protected Attributes
BareField< T, Dim > & A
S MyDomain
unsigned int Brackets
Friends
class BareField< T, Dim >
Detailed Description
template<class T, unsigned Dim, class S>
class SubBareField< T, Dim, S >
Definition at line 50 of file SubBareField.h.
Member Typedef Documentation
Index_t
template<class T, unsigned Dim, class S> typedef S SubBareField< T, Dim, S >::Index_t
Definition at line 64 of file SubBareField.h.
iterator
template<class T, unsigned Dim, class S> typedef SubFieldIter<T,Dim,S> SubBareField< T, Dim, S >::iterator
Definition at line 65 of file SubBareField.h.
PETE_Expr_t
template<class T, unsigned Dim, class S> typedef iterator SubBareField< T, Dim, S >::PETE_Expr_t
Definition at line 171 of file SubBareField.h.
T_t
template<class T, unsigned Dim, class S> typedef T SubBareField< T, Dim, S >::T_t
Definition at line 63 of file SubBareField.h.
Member Enumeration Documentation
anonymous enum
template<class T, unsigned Dim, class S> anonymous enum
Enumerator
Dim_u
Definition at line 68 of file SubBareField.h.
anonymous enum
template<class T, unsigned Dim, class S> anonymous enum
Enumerator
IsExpr
Definition at line 170 of file SubBareField.h.
Constructor & Destructor Documentation
SubBareField() [1/2]
template<class T, unsigned Dim, class S> constexpr SubBareField< T, Dim, S >::SubBareField (const SubBareField< T, Dim, S > &) default
SubBareField() [2/2]
template<class T, unsigned Dim, class S> template<class S2 > SubBareField< T, Dim, S >::SubBareField (BareField< T, Dim > & f, const S2 & s) inline
Definition at line 211 of file SubBareField.h.
References SubBareField< T, Dim, S >::A, SubBareField< T, Dim, S >::Brackets, SubFieldTraits< T, Dim, S1, S2 >::construct(), and SubBareField< T, Dim, S >::MyDomain.
Member Function Documentation
begin()
template<class T , unsigned int Dim, class S > SubBareField< T, Dim, S >::iterator SubBareField< T, Dim, S >::begin () const
Definition at line 101 of file SubBareField.hpp.
Referenced by SubBareField< T, Dim, S >::MakeExpression(), and SubBareField< T, Dim, S >::operator()().
checkAddBrackets()
template<class T , unsigned int Dim, class S > bool SubBareField< T, Dim, S >::checkAddBrackets (unsigned int B) protected
Definition at line 41 of file SubBareField.hpp.
References Dim, endl(), and ERRORMSG.
Referenced by SubField< T, Dim, M, C, S >::operator[](), and SubBareField< T, Dim, S >::operator[]().
checkBrackets()
template<class T, unsigned Dim, class S> bool SubBareField< T, Dim, S >::checkBrackets () const inline
Definition at line 99 of file SubBareField.h.
References SubBareField< T, Dim, S >::Brackets, and Dim.
Referenced by SubBareField< T, Dim, S >::operator()().
end()
template<class T , unsigned int Dim, class S > SubBareField< T, Dim, S >::iterator SubBareField< T, Dim, S >::end () const
Definition at line 109 of file SubBareField.hpp.
get() [1/2]
template<class T, unsigned Dim, class S> T SubBareField< T, Dim, S >::get () inline
Definition at line 92 of file SubBareField.h.
References Attrib::Legacy::Distribution::T.
get() [2/2]
template<class T, unsigned int Dim, class S > void SubBareField< T, Dim, S >::get (T & r)
Definition at line 83 of file SubBareField.hpp.
References PAssert_EQ.
getBareField()
template<class T, unsigned Dim, class S> BareField<T,Dim>& SubBareField< T, Dim, S >::getBareField () const inline
Definition at line 89 of file SubBareField.h.
References SubBareField< T, Dim, S >::A.
getDomain()
template<class T, unsigned Dim, class S> const S& SubBareField< T, Dim, S >::getDomain (void) const inline
Definition at line 81 of file SubBareField.h.
References SubBareField< T, Dim, S >::MyDomain.
getSubsetType()
template<class T, unsigned Dim, class S> static int SubBareField< T, Dim, S >::getSubsetType () inline static
Definition at line 96 of file SubBareField.h.
MakeExpression()
template<class T, unsigned Dim, class S> iterator SubBareField< T, Dim, S >::MakeExpression () const inline
Definition at line 172 of file SubBareField.h.
References SubBareField< T, Dim, S >::begin().
makeNDIndex()
template<class T, unsigned Dim, class S> void SubBareField< T, Dim, S >::makeNDIndex (NDIndex< Dim > & i) inline
Definition at line 86 of file SubBareField.h.
References SubBareField< T, Dim, S >::MyDomain.
operator()() [1/2]
template<class T, unsigned Dim, class S> PETE_TUTree<OpParens<int>, iterator> SubBareField< T, Dim, S >::operator() (int arg) inline
Definition at line 177 of file SubBareField.h.
References arg(), SubBareField< T, Dim, S >::begin(), and SubBareField< T, Dim, S >::checkBrackets().
operator()() [2/2]
template<class T, unsigned Dim, class S> PETE_TUTree< OpParens< std::pair<int,int> >, iterator> SubBareField< T, Dim, S >::operator() (int a1, int a2) inline
Definition at line 182 of file SubBareField.h.
References SubBareField< T, Dim, S >::begin(), and SubBareField< T, Dim, S >::checkBrackets().
operator=() [1/3]
template<class T, unsigned int Dim, class S> SubBareField< T, Dim, S > & SubBareField< T, Dim, S >::operator= (const SubBareField< T, Dim, S > & t)
Definition at line 59 of file SubBareField.hpp.
References assign().
operator=() [2/3]
template<class T, unsigned int Dim, class S> SubBareField< T, Dim, S > & SubBareField< T, Dim, S >::operator= (T t)
Definition at line 71 of file SubBareField.hpp.
References assign().
operator=() [3/3]
template<class T, unsigned Dim, class S> template<class B > SubBareField<T,Dim,S>& SubBareField< T, Dim, S >::operator= (const PETE_Expr< B > & b) inline
Definition at line 152 of file SubBareField.h.
References assign().
operator[]()
template<class T, unsigned Dim, class S> template<class S2 > SubBareField<T,Dim,typename SubFieldTraits<T,Dim,S,S2>::Return_t> SubBareField< T, Dim, S >::operator[] (const S2 & s) inline
Definition at line 115 of file SubBareField.h.
References SubBareField< T, Dim, S >::A, SubBareField< T, Dim, S >::Brackets, SubBareField< T, Dim, S >::checkAddBrackets(), SubFieldTraits< T, Dim, S1, S2 >::combine(), Dim, SubBareField< T, Dim, S >::MyDomain, and Attrib::Legacy::Distribution::T.
write()
template<class T , unsigned int Dim, class S > void SubBareField< T, Dim, S >::write (std::ostream & o)
Definition at line 120 of file SubBareField.hpp.
References Dim, and PAssert_EQ.
Referenced by operator<<().
Friends And Related Function Documentation
BareField< T, Dim >
template<class T, unsigned Dim, class S> friend class BareField< T, Dim > friend
Definition at line 59 of file SubBareField.h.
Member Data Documentation
A
template<class T, unsigned Dim, class S> BareField<T,Dim>& SubBareField< T, Dim, S >::A protected
Definition at line 190 of file SubBareField.h.
Referenced by SubBareField< T, Dim, S >::getBareField(), SubBareField< T, Dim, S >::operator[](), and SubBareField< T, Dim, S >::SubBareField().
Brackets
template<class T, unsigned Dim, class S> unsigned int SubBareField< T, Dim, S >::Brackets protected
Definition at line 197 of file SubBareField.h.
Referenced by SubBareField< T, Dim, S >::checkBrackets(), SubBareField< T, Dim, S >::operator[](), and SubBareField< T, Dim, S >::SubBareField().
MyDomain
template<class T, unsigned Dim, class S> S SubBareField< T, Dim, S >::MyDomain protected
Definition at line 193 of file SubBareField.h.
Referenced by SubBareField< T, Dim, S >::getDomain(), SubBareField< T, Dim, S >::makeNDIndex(), SubBareField< T, Dim, S >::operator[](), and SubBareField< T, Dim, S >::SubBareField().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/SubField/SubBareField.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/SubField/SubBareField.hpp