OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Utility/FieldDebug.hpp File Reference
FieldDebug.hpp File Reference
#include "Utility/FieldDebug.h"
#include "Utility/FieldDebugPrint.h"
#include "Utility/Inform.h"
#include "Field/BareField.h"
#include <iostream>
#include <iomanip>
Functions
template<class T >
void fp1 (BareField< T, 1U > &field, bool docomm)
template<class T >
void fp2 (BareField< T, 2U > &field, bool docomm)
template<class T >
void fp3 (BareField< T, 3U > &field, bool docomm)
template<class T >
void ggfp1 (BareField< T, 1U > &field, bool docomm)
template<class T >
void ggfp2 (BareField< T, 2U > &field, bool docomm)
template<class T >
void ggfp3 (BareField< T, 3U > &field, bool docomm)
template<class T >
void agfp1 (BareField< T, 1U > &field)
template<class T >
void agfp2 (BareField< T, 2U > &field)
template<class T >
void agfp3 (BareField< T, 3U > &field)
template<class T >
void efp1 (BareField< T, 1U > &field, int i, bool docomm)
template<class T >
void efp2 (BareField< T, 2U > &field, int i, int j, bool docomm)
template<class T >
void efp3 (BareField< T, 3U > &field, int i, int j, int k, bool docomm)
template<class T >
void sfp1 (BareField< T, 1U > &field, int ibase, int ibound, int istride, bool docomm)
template<class T >
void sfp2 (BareField< T, 2U > &field, int ibase, int ibound, int istride, int jbase, int jbound, int jstride, bool docomm)
template<class T >
void sfp3 (BareField< T, 3U > &field, int ibase, int ibound, int istride, int jbase, int jbound, int jstride, int kbase, int kbound, int kstride, bool docomm)
template<class T , unsigned Dim>
void FieldDebugWriteb (BareField< T, Dim > &F)
Function Documentation
agfp1()
template<class T > void agfp1 (BareField< T, 1U > & field)
Definition at line 151 of file FieldDebug.hpp.
References FieldDebugWriteb(), FldDbgInformIsSet, IpplInfo::Info, and setInform().
agfp2()
template<class T > void agfp2 (BareField< T, 2U > & field)
Definition at line 161 of file FieldDebug.hpp.
References FieldDebugWriteb(), FldDbgInformIsSet, IpplInfo::Info, and setInform().
agfp3()
template<class T > void agfp3 (BareField< T, 3U > & field)
Definition at line 171 of file FieldDebug.hpp.
References FieldDebugWriteb(), FldDbgInformIsSet, IpplInfo::Info, and setInform().
efp1()
template<class T > void efp1 (BareField< T, 1U > & field, int i, bool docomm)
Definition at line 181 of file FieldDebug.hpp.
References sfp1().
efp2()
template<class T > void efp2 (BareField< T, 2U > & field, int i, int j, bool docomm)
Definition at line 190 of file FieldDebug.hpp.
References sfp2().
efp3()
template<class T > void efp3 (BareField< T, 3U > & field, int i, int j, int k, bool docomm)
Definition at line 199 of file FieldDebug.hpp.
References sfp3().
FieldDebugWriteb()
template<class T , unsigned Dim> void FieldDebugWriteb (BareField< T, Dim > & F) inline
Definition at line 467 of file FieldDebug.hpp.
References LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), digitsPastDecimal, Dim, elementsPerLine, BareField< T, Dim >::end_if(), endl(), ERRORMSG, FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), LField< T, Dim >::getOwned(), BareField< T, Dim >::leftGuard(), BrickIterator< T, Dim >::offset(), BareField< T, Dim >::rightGuard(), LField< T, Dim >::size(), and widthOfElements.
Referenced by agfp1(), agfp2(), and agfp3().
fp1()
template<class T > void fp1 (BareField< T, 1U > & field, bool docomm)
Definition at line 43 of file FieldDebug.hpp.
References FldDbgInformIsSet, FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::Info, setInform(), and sfp1().
Referenced by Cyclotron::writeOutputFieldFiles().
fp2()
template<class T > void fp2 (BareField< T, 2U > & field, bool docomm)
Definition at line 56 of file FieldDebug.hpp.
References FldDbgInformIsSet, FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::Info, setInform(), and sfp2().
Referenced by Cyclotron::writeOutputFieldFiles().
fp3()
template<class T > void fp3 (BareField< T, 3U > & field, bool docomm)
Definition at line 72 of file FieldDebug.hpp.
References FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), and sfp3().
ggfp1()
template<class T > void ggfp1 (BareField< T, 1U > & field, bool docomm)
Definition at line 91 of file FieldDebug.hpp.
References FldDbgInformIsSet, FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::Info, BareField< T, Dim >::leftGuard(), setInform(), and sfp1().
ggfp2()
template<class T > void ggfp2 (BareField< T, 2U > & field, bool docomm)
Definition at line 106 of file FieldDebug.hpp.
References FldDbgInformIsSet, FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::Info, BareField< T, Dim >::leftGuard(), setInform(), and sfp2().
ggfp3()
template<class T > void ggfp3 (BareField< T, 3U > & field, bool docomm)
Definition at line 126 of file FieldDebug.hpp.
References FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), BareField< T, Dim >::leftGuard(), and sfp3().
sfp1()
template<class T > void sfp1 (BareField< T, 1U > & field, int ibase, int ibound, int istride, bool docomm)
Definition at line 208 of file FieldDebug.hpp.
References digitsPastDecimal, elementsPerLine, endl(), FldDbgInform, FldDbgInformIsSet, BareField< T, Dim >::getDomain(), FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::Info, BareField< T, Dim >::leftGuard(), FieldDebugPrint< T, Dim >::print(), setInform(), and widthOfElements.
Referenced by efp1(), fp1(), and ggfp1().
sfp2()
template<class T > void sfp2 (BareField< T, 2U > & field, int ibase, int ibound, int istride, int jbase, int jbound, int jstride, bool docomm)
Definition at line 261 of file FieldDebug.hpp.
References digitsPastDecimal, elementsPerLine, endl(), FldDbgInform, FldDbgInformIsSet, BareField< T, Dim >::getDomain(), FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::Info, BareField< T, Dim >::leftGuard(), FieldDebugPrint< T, Dim >::print(), setInform(), and widthOfElements.
Referenced by efp2(), fp2(), and ggfp2().
sfp3()
template<class T > void sfp3 (BareField< T, 3U > & field, int ibase, int ibound, int istride, int jbase, int jbound, int jstride, int kbase, int kbound, int kstride, bool docomm)
Definition at line 345 of file FieldDebug.hpp.
References digitsPastDecimal, elementsPerLine, endl(), FldDbgInform, FldDbgInformIsSet, BareField< T, Dim >::getDomain(), FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::Info, BareField< T, Dim >::leftGuard(), FieldDebugPrint< T, Dim >::print(), setInform(), and widthOfElements.
Referenced by efp3(), fp3(), and ggfp3().