OPAL (Object Oriented Parallel Accelerator Library): Macro Class Reference
Macro Class Reference
Abstract base class for macros.
#include <Macro.h>
Public Member Functions
Macro (int size, const char *name, const char *help)
Exemplar constructor.
Macro (const std::string &name, Object *parent)
Clone constructor.
virtual ~Macro ()
virtual Macro * clone (const std::string &name)
Make clone.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual void parseActuals (Statement &)
Parse actual arguments.
virtual void parseFormals (Statement &)
Parse formal arguments.
Public Member Functions inherited from Object
virtual ~Object ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Attributes
std::vector< std::string > formals
The formal argument list.
std::vector< std::vector< Token > > actuals
The actual argument list.
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Member Functions
Macro ()
Macro (const Macro &)
void operator= (const Macro &)
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Detailed Description
Abstract base class for macros.
Definition at line 34 of file Macro.h.
Constructor & Destructor Documentation
Macro() [1/4]
Macro::Macro (int size, const char * name, const char * help)
Exemplar constructor.
Definition at line 28 of file Macro.cpp.
Macro() [2/4]
Macro::Macro (const std::string & name, Object * parent)
Clone constructor.
Definition at line 33 of file Macro.cpp.
~Macro()
Macro::~Macro () virtual
Definition at line 38 of file Macro.cpp.
Macro() [3/4]
Macro::Macro () private
Macro() [4/4]
Macro::Macro (const Macro &) private
Member Function Documentation
clone()
Macro * Macro::clone (const std::string & name) virtual
Make clone.
Implements Object.
Reimplemented in SequenceTemplate, and LineTemplate.
Definition at line 42 of file Macro.cpp.
References Object::getOpalName().
getCategory()
const std::string Macro::getCategory () const virtual
Return the object category as a string.
Implements Object.
Definition at line 49 of file Macro.cpp.
operator=()
void Macro::operator= (const Macro &) private
parseActuals()
void Macro::parseActuals (Statement & stat) virtual
Parse actual arguments.
Definition at line 64 of file Macro.cpp.
References actuals, Statement::delimiter(), Statement::getCurrent(), and Token::isDel().
Referenced by LineTemplate::makeInstance().
parseFormals()
void Macro::parseFormals (Statement & stat) virtual
Parse formal arguments.
Definition at line 100 of file Macro.cpp.
References Statement::delimiter(), formals, Expressions::parseDelimiter(), and Expressions::parseString().
Referenced by MacroCmd::makeTemplate(), LineTemplate::parseTemplate(), and SequenceTemplate::parseTemplate().
shouldTrace()
bool Macro::shouldTrace () const virtual
Trace flag.
Implements Object.
Definition at line 54 of file Macro.cpp.
shouldUpdate()
bool Macro::shouldUpdate () const virtual
Update flag.
Implements Object.
Definition at line 59 of file Macro.cpp.
Member Data Documentation
actuals
std::vector<std::vector < Token > > Macro::actuals protected
The actual argument list.
Definition at line 82 of file Macro.h.
Referenced by LineTemplate::makeInstance(), and parseActuals().
formals
std::vector<std::string> Macro::formals protected
The formal argument list.
Definition at line 78 of file Macro.h.
Referenced by LineTemplate::makeInstance(), and parseFormals().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/OpalParser/Macro.h
/psi/home/gsell/data/src/OPAL/src/src/OpalParser/Macro.cpp