OPAL (Object Oriented Parallel Accelerator Library): FieldDebugPrint< T, Dim > Class Template Reference
FieldDebugPrint< T, Dim > Class Template Reference
#include <FieldDebugPrint.h>
Public Member Functions
FieldDebugPrint (bool printbc=false, unsigned int dataWidth=0, unsigned int dataPrecision=0, unsigned int carReturn=0, bool scientific=true)
~FieldDebugPrint ()
void print (BareField< T, Dim > &, const NDIndex< Dim > &, Inform &, bool=true)
void print (BareField< T, Dim > &, Inform &, bool=true)
void print (BareField< T, Dim > &, const NDIndex< Dim > &, bool=true)
void print (BareField< T, Dim > &, bool=true)
void set_DataWidth (unsigned int in)
void set_DataPrecision (unsigned int in)
void set_CarReturn (unsigned int in)
void set_Scientific (bool in)
void set_PrintBC (bool in)
unsigned int get_DataWidth () const
unsigned int get_DataPrecision () const
unsigned int get_CarReturn () const
bool get_Scientific () const
bool get_PrintBC () const
Private Member Functions
void printelem (bool, T &, unsigned int, Inform &)
Private Attributes
unsigned int DataWidth
unsigned int DataPrecision
unsigned int CarReturn
bool Scientific
bool PrintBC
Detailed Description
template<class T, unsigned Dim>
class FieldDebugPrint< T, Dim >
Definition at line 21 of file FieldDebugPrint.h.
Constructor & Destructor Documentation
FieldDebugPrint()
template<class T, unsigned Dim> FieldDebugPrint< T, Dim >::FieldDebugPrint (bool printbc = false, unsigned int dataWidth = 0, unsigned int dataPrecision = 0, unsigned int carReturn = 0, bool scientific = true) inline
Definition at line 27 of file FieldDebugPrint.h.
~FieldDebugPrint()
template<class T, unsigned Dim> FieldDebugPrint< T, Dim >::~FieldDebugPrint () inline
Definition at line 34 of file FieldDebugPrint.h.
Member Function Documentation
get_CarReturn()
template<class T, unsigned Dim> unsigned int FieldDebugPrint< T, Dim >::get_CarReturn () const inline
Definition at line 55 of file FieldDebugPrint.h.
References FieldDebugPrint< T, Dim >::CarReturn.
get_DataPrecision()
template<class T, unsigned Dim> unsigned int FieldDebugPrint< T, Dim >::get_DataPrecision () const inline
Definition at line 54 of file FieldDebugPrint.h.
References FieldDebugPrint< T, Dim >::DataPrecision.
get_DataWidth()
template<class T, unsigned Dim> unsigned int FieldDebugPrint< T, Dim >::get_DataWidth () const inline
Definition at line 53 of file FieldDebugPrint.h.
References FieldDebugPrint< T, Dim >::DataWidth.
get_PrintBC()
template<class T, unsigned Dim> bool FieldDebugPrint< T, Dim >::get_PrintBC () const inline
Definition at line 57 of file FieldDebugPrint.h.
References FieldDebugPrint< T, Dim >::PrintBC.
get_Scientific()
template<class T, unsigned Dim> bool FieldDebugPrint< T, Dim >::get_Scientific () const inline
Definition at line 56 of file FieldDebugPrint.h.
References FieldDebugPrint< T, Dim >::Scientific.
print() [1/4]
template<class T , unsigned Dim> void FieldDebugPrint< T, Dim >::print (BareField< T, Dim > & F, const NDIndex< Dim > & view, Inform & out, bool allnodes = true)
Definition at line 74 of file FieldDebugPrint.hpp.
References IpplInfo::abort(), AddGuardCells(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), IpplInfo::Comm, COMM_ANY_NODE, Dim, BareField< T, Dim >::end_if(), endl(), ERRORMSG, BareField< T, Dim >::fillGuardCells(), FP_GATHER_TAG, FP_TAG_CYCLE, LField< T, Dim >::getAllocated(), BareField< T, Dim >::getDomain(), BareField< T, Dim >::getGuardCellSizes(), NDIndex< Dim >::getMessage(), getMessage(), IpplInfo::getNodes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::isDirty(), IpplInfo::myNode(), TagMaker::next_tag(), PAssert, NDIndex< Dim >::putMessage(), putMessage(), Communicate::receive_block(), Communicate::send(), Inform::setf(), Attrib::Legacy::Distribution::T, NDIndex< Dim >::touches(), CompressedBrickIterator< T, Dim >::TryCompress(), and LField< T, Dim >::Uncompress().
Referenced by sfp1(), sfp2(), and sfp3().
print() [2/4]
template<class T , unsigned Dim> void FieldDebugPrint< T, Dim >::print (BareField< T, Dim > & F, Inform & out, bool allnodes = true)
Definition at line 39 of file FieldDebugPrint.hpp.
References AddGuardCells(), BareField< T, Dim >::getDomain(), and BareField< T, Dim >::getGuardCellSizes().
print() [3/4]
template<class T , unsigned Dim> void FieldDebugPrint< T, Dim >::print (BareField< T, Dim > & F, const NDIndex< Dim > & view, bool allnodes = true)
Definition at line 65 of file FieldDebugPrint.hpp.
print() [4/4]
template<class T , unsigned Dim> void FieldDebugPrint< T, Dim >::print (BareField< T, Dim > & F, bool allnodes = true)
Definition at line 52 of file FieldDebugPrint.hpp.
References AddGuardCells(), BareField< T, Dim >::getDomain(), and BareField< T, Dim >::getGuardCellSizes().
printelem()
template<class T , unsigned Dim> void FieldDebugPrint< T, Dim >::printelem (bool isavail, T & val, unsigned int i0, Inform & out) private
Definition at line 309 of file FieldDebugPrint.hpp.
References endl(), and Inform::setf().
set_CarReturn()
template<class T, unsigned Dim> void FieldDebugPrint< T, Dim >::set_CarReturn (unsigned int in) inline
Definition at line 48 of file FieldDebugPrint.h.
References FieldDebugPrint< T, Dim >::CarReturn.
set_DataPrecision()
template<class T, unsigned Dim> void FieldDebugPrint< T, Dim >::set_DataPrecision (unsigned int in) inline
Definition at line 47 of file FieldDebugPrint.h.
References FieldDebugPrint< T, Dim >::DataPrecision.
set_DataWidth()
template<class T, unsigned Dim> void FieldDebugPrint< T, Dim >::set_DataWidth (unsigned int in) inline
Definition at line 46 of file FieldDebugPrint.h.
References FieldDebugPrint< T, Dim >::DataWidth.
set_PrintBC()
template<class T, unsigned Dim> void FieldDebugPrint< T, Dim >::set_PrintBC (bool in) inline
Definition at line 50 of file FieldDebugPrint.h.
References FieldDebugPrint< T, Dim >::PrintBC.
set_Scientific()
template<class T, unsigned Dim> void FieldDebugPrint< T, Dim >::set_Scientific (bool in) inline
Definition at line 49 of file FieldDebugPrint.h.
References FieldDebugPrint< T, Dim >::Scientific.
Member Data Documentation
CarReturn
template<class T, unsigned Dim> unsigned int FieldDebugPrint< T, Dim >::CarReturn private
Definition at line 63 of file FieldDebugPrint.h.
Referenced by FieldDebugPrint< T, Dim >::get_CarReturn(), and FieldDebugPrint< T, Dim >::set_CarReturn().
DataPrecision
template<class T, unsigned Dim> unsigned int FieldDebugPrint< T, Dim >::DataPrecision private
Definition at line 62 of file FieldDebugPrint.h.
Referenced by FieldDebugPrint< T, Dim >::get_DataPrecision(), and FieldDebugPrint< T, Dim >::set_DataPrecision().
DataWidth
template<class T, unsigned Dim> unsigned int FieldDebugPrint< T, Dim >::DataWidth private
Definition at line 61 of file FieldDebugPrint.h.
Referenced by FieldDebugPrint< T, Dim >::get_DataWidth(), and FieldDebugPrint< T, Dim >::set_DataWidth().
PrintBC
template<class T, unsigned Dim> bool FieldDebugPrint< T, Dim >::PrintBC private
Definition at line 65 of file FieldDebugPrint.h.
Referenced by FieldDebugPrint< T, Dim >::get_PrintBC(), and FieldDebugPrint< T, Dim >::set_PrintBC().
Scientific
template<class T, unsigned Dim> bool FieldDebugPrint< T, Dim >::Scientific private
Definition at line 64 of file FieldDebugPrint.h.
Referenced by FieldDebugPrint< T, Dim >::get_Scientific(), and FieldDebugPrint< T, Dim >::set_Scientific().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/FieldDebugPrint.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/FieldDebugPrint.hpp