OPAL (Object Oriented Parallel Accelerator Library): OpalWake Class Reference
OpalWake Class Reference
#include <OpalWake.h>
Public Member Functions
OpalWake ()
Exemplar constructor.
virtual ~OpalWake ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual OpalWake * clone (const std::string &name)
Make clone.
virtual void execute ()
Check the WAKE data.
virtual void update ()
Update the WAKE data.
void print (std::ostream &os) const
Print the object.
int getNumberOfBins ()
void initWakefunction (const ElementBase &element)
Public Member Functions inherited from Definition
virtual ~Definition ()
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static OpalWake * find (const std::string &name)
Find named WAKE.
Public Attributes
WakeFunction * wf_m
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Private Types
enum OpalWakeType : unsigned short { OpalWakeType::CSR, OpalWakeType::CSRIGF, OpalWakeType::LONGSHORTRANGE, OpalWakeType::TRANSVSHORTRANGE }
Private Member Functions
OpalWake (const OpalWake &)
void operator= (const OpalWake &)
OpalWake (const std::string &name, OpalWake *parent)
Additional Inherited Members
Protected Member Functions inherited from Definition
Definition (int size, const char *name, const char *help)
Constructor for exemplars.
Definition (const std::string &name, Definition *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 26 of file OpalWake.h.
Member Enumeration Documentation
OpalWakeType
enum OpalWake::OpalWakeType : unsigned short strong private
Enumerator
CSR
CSRIGF
LONGSHORTRANGE
TRANSVSHORTRANGE
Definition at line 59 of file OpalWake.h.
Constructor & Destructor Documentation
OpalWake() [1/3]
OpalWake::OpalWake ()
Exemplar constructor.
Definition at line 50 of file OpalWake.cpp.
References Object::builtin, clone(), OpalData::define(), Attrib::Distribution::FNAME, OpalData::getInstance(), Object::itsAttr, Attributes::makeBool(), Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeString(), Attributes::makeStringArray(), Attrib::Distribution::NBIN, Object::registerOwnership(), AttributeHandler::STATEMENT, Attrib::Distribution::TYPE, and update().
Referenced by clone().
~OpalWake()
OpalWake::~OpalWake () virtual
Definition at line 106 of file OpalWake.cpp.
References wf_m.
OpalWake() [2/3]
OpalWake::OpalWake (const OpalWake &) private
OpalWake() [3/3]
OpalWake::OpalWake (const std::string & name, OpalWake * parent) private
Definition at line 100 of file OpalWake.cpp.
Member Function Documentation
canReplaceBy()
bool OpalWake::canReplaceBy (Object * object) virtual
Test if replacement is allowed.
Reimplemented from Object.
Definition at line 111 of file OpalWake.cpp.
clone()
OpalWake * OpalWake::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 117 of file OpalWake.cpp.
References name, and OpalWake().
Referenced by OpalWake().
execute()
void OpalWake::execute () virtual
Check the WAKE data.
Reimplemented from Object.
Definition at line 122 of file OpalWake.cpp.
References update().
find()
OpalWake * OpalWake::find (const std::string & name) static
Find named WAKE.
Definition at line 127 of file OpalWake.cpp.
References OpalData::find(), OpalData::getInstance(), and name.
Referenced by OpalRBend::update(), OpalSBend::update(), OpalSeptum::update(), OpalProbe::update(), OpalRBend3D::update(), OpalDrift::update(), OpalTravelingWave::update(), and OpalCavity::update().
getNumberOfBins()
int OpalWake::getNumberOfBins ()
Definition at line 136 of file OpalWake.cpp.
References Attributes::getReal(), Object::itsAttr, and Attrib::Distribution::NBIN.
initWakefunction()
void OpalWake::initWakefunction (const ElementBase & element)
Definition at line 147 of file OpalWake.cpp.
References CSR, CSRIGF, CSRIGFWakeFunction, CSRWakeFunction, endl(), OpalFilter::filter_m, OpalFilter::find(), Attrib::Distribution::FNAME, Attributes::getBool(), ElementBase::getName(), Object::getOpalName(), Attributes::getReal(), Attributes::getString(), Attributes::getStringArray(), gmsg, GreenWakeFunction, OpalFilter::initOpalFilter(), Object::itsAttr, LONGITUDINAL, LONGSHORTRANGE, Attrib::Distribution::NBIN, TRANSVERSAL, TRANSVSHORTRANGE, Attrib::Distribution::TYPE, and wf_m.
Referenced by OpalRBend::update(), OpalSBend::update(), OpalSeptum::update(), OpalProbe::update(), OpalRBend3D::update(), OpalDrift::update(), OpalTravelingWave::update(), and OpalCavity::update().
operator=()
void OpalWake::operator= (const OpalWake &) private
print()
void OpalWake::print (std::ostream & msg) const virtual
Print the object.
Reimplemented from Object.
Definition at line 234 of file OpalWake.cpp.
References endl(), Object::getOpalName(), Attributes::getReal(), Object::itsAttr, and Attrib::Distribution::NBIN.
Referenced by operator<<().
update()
void OpalWake::update () virtual
Update the WAKE data.
Reimplemented from Object.
Definition at line 141 of file OpalWake.cpp.
References Object::getOpalName(), and Object::setOpalName().
Referenced by execute(), and OpalWake().
Member Data Documentation
wf_m
WakeFunction* OpalWake::wf_m
Definition at line 56 of file OpalWake.h.
Referenced by initWakefunction(), OpalRBend::update(), OpalSBend::update(), OpalSeptum::update(), OpalProbe::update(), OpalRBend3D::update(), OpalDrift::update(), OpalTravelingWave::update(), OpalCavity::update(), and ~OpalWake().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Structure/OpalWake.h
/psi/home/gsell/data/src/OPAL/src/src/Structure/OpalWake.cpp