BUNCH
{
  
  bunch-sampling
  {
    sample						= true
    directory						= ./
    base-name 						= bunch-sampling/bunch
    rhythm						= 8.0e-12
  }
    
  bunch-visualization
  {
    sample						= false
    directory						= ./
    base-name						= bunch-visualization/bunch
    rhythm						= 5.0e-12
  }
    
  bunch-profile
  {
    sample						= false
    directory						= ./
    base-name						= bunch-profile/bunch
    time						= 2.0e-10
  }
}

FIELD
{
    
  field-visualization
  {
    sample						= false
    type						= in-plane
    field						= Ex
    field						= Ey
    field						= Ez
    plane						= x-normal
    position						= (0.0, 0.0, 110.0)
    directory						= ./
    base-name						= field-visualization/field1
    rhythm						= 5.0
  }
  
  field-visualization
  {
    sample						= false
    type						= in-plane
    field						= Ex
    field						= Ey
    field						= Ez
    plane						= y-normal
    position						= (0.0, 0.0, 110.0)
    directory						= ./
    base-name						= field-visualization/field2
    rhythm						= 30.0
  }
    
  field-profile
  {
    sample						= false
    field                           			= Q
    directory						= ./
    base-name						= field-profile/field
    rhythm						= 100
  }
}

FEL-OUTPUT
{
  radiation-power
  {
    sample						= true
    type						= at-point
    directory						= ./
    base-name						= power-sampling/power
    plane-position					= 1.1e-4
    normalized-frequency				= 1.00
  }
}
