OPAL (Object Oriented Parallel Accelerator Library): Euclid3DGeometry Class Reference
Euclid3DGeometry Class Reference
#include <Euclid3DGeometry.h>
Public Member Functions
Euclid3DGeometry (Euclid3D transformation)
Euclid3DGeometry (const Euclid3DGeometry &right)
virtual ~Euclid3DGeometry ()
const Euclid3DGeometry & operator= (const Euclid3DGeometry &right)
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get geometry length.
virtual void setElementLength (double length)
Set geometry length.
virtual Euclid3D getTransform (double fromS, double toS) const
virtual Euclid3D getTotalTransform () const
Get total transform from beginning to end.
Public Member Functions inherited from BGeometryBase
BGeometryBase ()
BGeometryBase (const BGeometryBase &right)
virtual ~BGeometryBase ()
const BGeometryBase & operator= (const BGeometryBase &right)
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
Private Attributes
Euclid3D transformation_m
Detailed Description
class Euclid3DGeometry
Euclid3DGeometry is a straight line from input to output followed by a rotation.
Definition at line 43 of file Euclid3DGeometry.h.
Constructor & Destructor Documentation
Euclid3DGeometry() [1/2]
Euclid3DGeometry::Euclid3DGeometry (Euclid3D transformation)
Definition at line 34 of file Euclid3DGeometry.cpp.
Euclid3DGeometry() [2/2]
Euclid3DGeometry::Euclid3DGeometry (const Euclid3DGeometry & right)
Definition at line 38 of file Euclid3DGeometry.cpp.
~Euclid3DGeometry()
Euclid3DGeometry::~Euclid3DGeometry () virtual
Definition at line 42 of file Euclid3DGeometry.cpp.
Member Function Documentation
getArcLength()
double Euclid3DGeometry::getArcLength () const virtual
Get arc length.
Implements BGeometryBase.
Definition at line 51 of file Euclid3DGeometry.cpp.
References dot(), Euclid3D::getVector(), sqrt(), and transformation_m.
Referenced by getElementLength(), and setElementLength().
getElementLength()
double Euclid3DGeometry::getElementLength () const virtual
Get geometry length.
Implements BGeometryBase.
Definition at line 56 of file Euclid3DGeometry.cpp.
References getArcLength().
getTotalTransform()
Euclid3D Euclid3DGeometry::getTotalTransform () const virtual
Get total transform from beginning to end.
Reimplemented from BGeometryBase.
Definition at line 73 of file Euclid3DGeometry.cpp.
References transformation_m.
Referenced by Offset::bends(), Offset::operator=(), and operator==().
getTransform()
Euclid3D Euclid3DGeometry::getTransform (double fromS, double toS) const virtual
Not Implemented - raises GeneralClassicException Get transform.
Implements BGeometryBase.
Definition at line 69 of file Euclid3DGeometry.cpp.
operator=()
const Euclid3DGeometry & Euclid3DGeometry::operator= (const Euclid3DGeometry & right)
Definition at line 44 of file Euclid3DGeometry.cpp.
References transformation_m.
setElementLength()
void Euclid3DGeometry::setElementLength (double length) virtual
Set geometry length.
Reimplemented from BGeometryBase.
Definition at line 60 of file Euclid3DGeometry.cpp.
References getArcLength(), Euclid3D::getVector(), Euclid3D::setDisplacement(), and transformation_m.
Member Data Documentation
transformation_m
Euclid3D Euclid3DGeometry::transformation_m private
Definition at line 77 of file Euclid3DGeometry.h.
Referenced by getArcLength(), getTotalTransform(), operator=(), and setElementLength().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/BeamlineGeometry/Euclid3DGeometry.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/BeamlineGeometry/Euclid3DGeometry.cpp