OPAL (Object Oriented Parallel Accelerator Library): IntTSCImpl< 3U > Class Template Reference
IntTSCImpl< 3U > Class Template Reference
#include <IntTSC.h>
Public Member Functions
IntTSCImpl ()
~IntTSCImpl ()
Public Member Functions inherited from Interpolator
Interpolator ()
~Interpolator ()
Static Public Member Functions
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 3U, M, C > &f, const Vektor< PT, 3U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 3U, M, C > &f, const Vektor< PT, 3U > &ppos, const M &mesh, NDIndex< 3U > &ngp, int [3U], Vektor< PT, 3U > &dpos)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 3U, M, C > &f, const NDIndex< 3U > &ngp, const int [3U], const Vektor< PT, 3U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 3U, M, C > &f, const Vektor< PT, 3U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 3U, M, C > &f, const Vektor< PT, 3U > &ppos, const M &mesh, NDIndex< 3U > &ngp, int [3U], Vektor< PT, 3U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 3U, M, C > &f, const NDIndex< 3U > &ngp, const int [3U], const Vektor< PT, 3U > &dpos)
Additional Inherited Members
Static Protected Member Functions inherited from Interpolator
template<class T , unsigned Dim>
static CompressedBrickIterator< T, Dim > getFieldIter (const BareField< T, Dim > &f, const NDIndex< Dim > &pt)
Detailed Description
template<>
class IntTSCImpl< 3U >
Definition at line 652 of file IntTSC.h.
Constructor & Destructor Documentation
IntTSCImpl()
IntTSCImpl< 3U >::IntTSCImpl () inline
Definition at line 656 of file IntTSC.h.
~IntTSCImpl()
IntTSCImpl< 3U >::~IntTSCImpl () inline
Definition at line 657 of file IntTSC.h.
Member Function Documentation
gather() [1/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 3U >::gather (FT & pdata, const Field< FT, 3U, M, C > & f, const Vektor< PT, 3U > & ppos, const M & mesh) inline static
Definition at line 766 of file IntTSC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
gather() [2/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 3U >::gather (FT & pdata, const Field< FT, 3U, M, C > & f, const Vektor< PT, 3U > & ppos, const M & mesh, NDIndex< 3U > & ngp, int [3U], Vektor< PT, 3U > & dpos) inline static
Definition at line 805 of file IntTSC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
gather() [3/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 3U >::gather (FT & pdata, const Field< FT, 3U, M, C > & f, const NDIndex< 3U > & ngp, const int [3U], const Vektor< PT, 3U > & dpos) inline static
Definition at line 843 of file IntTSC.h.
References Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
scatter() [1/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 3U >::scatter (const FT & pdata, Field< FT, 3U, M, C > & f, const Vektor< PT, 3U > & ppos, const M & mesh) inline static
Definition at line 664 of file IntTSC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
scatter() [2/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 3U >::scatter (const FT & pdata, Field< FT, 3U, M, C > & f, const Vektor< PT, 3U > & ppos, const M & mesh, NDIndex< 3U > & ngp, int [3U], Vektor< PT, 3U > & dpos) inline static
Definition at line 704 of file IntTSC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
scatter() [3/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 3U >::scatter (const FT & pdata, Field< FT, 3U, M, C > & f, const NDIndex< 3U > & ngp, const int [3U], const Vektor< PT, 3U > & dpos) inline static
Definition at line 741 of file IntTSC.h.
References Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/IntTSC.h