OPAL (Object Oriented Parallel Accelerator Library): MemoryWriter Class Reference
MemoryWriter Class Reference
#include <MemoryWriter.h>
Public Member Functions
MemoryWriter (const std::string &fname, bool restart)
void write (PartBunchBase< double, 3 > *beam) override
Public Member Functions inherited from SDDSWriter
SDDSWriter (const std::string &fname, bool restart)
virtual ~SDDSWriter ()
void rewindLines (size_t numberOfLines)
delete the last 'numberOfLines' lines of the file 'fileName'
void replaceVersionString ()
double getLastValue (const std::string &column)
bool exists () const
Private Member Functions
void fillHeader ()
Additional Inherited Members
Public Types inherited from SDDSWriter
typedef std::pair< std::string, std::string > desc_t
typedef std::tuple< std::string, std::string, std::string > param_t
typedef std::pair< std::string, size_t > data_t
typedef std::tuple< std::string, std::string, std::string, std::string > cols_t
Protected Member Functions inherited from SDDSWriter
void addDescription (const std::string &text, const std::string &content)
template<typename T >
void addParameter (const std::string &name, const std::string &type, const std::string &desc, const T &value)
void addDefaultParameters ()
void addColumn (const std::string &name, const std::string &type, const std::string &unit, const std::string &desc)
void addInfo (const std::string &mode, const size_t &no_row_counts)
void writeRow ()
void open ()
void close ()
void writeHeader ()
Write SDDS header.
template<typename T >
std::string toString (const T &val)
bool hasColumns () const
Protected Attributes inherited from SDDSWriter
std::string fname_m
std::ios_base::openmode mode_m
First write to the statistics output file.
SDDSColumnSet columns_m
Detailed Description
Definition at line 26 of file MemoryWriter.h.
Constructor & Destructor Documentation
MemoryWriter()
MemoryWriter::MemoryWriter (const std::string & fname, bool restart)
Definition at line 30 of file MemoryWriter.cpp.
Member Function Documentation
fillHeader()
void MemoryWriter::fillHeader () private
Definition at line 35 of file MemoryWriter.cpp.
References SDDSColumnSet::addColumn(), SDDSWriter::addDefaultParameters(), SDDSWriter::addDescription(), SDDSWriter::addInfo(), SDDSWriter::columns_m, OPALTimer::Timer::date(), OpalData::getInputFn(), OpalData::getInstance(), IpplMemoryUsage::getInstance(), IpplInfo::getNodes(), IpplMemoryUsage::getUnit(), SDDSWriter::hasColumns(), SDDSWriter::mode_m, and OPALTimer::Timer::time().
Referenced by write().
write()
void MemoryWriter::write (PartBunchBase< double, 3 > * beam) override virtual
Reimplemented from SDDSWriter.
Definition at line 79 of file MemoryWriter.cpp.
References SDDSColumnSet::addColumnValue(), SDDSWriter::close(), SDDSWriter::columns_m, fillHeader(), PartBunchBase< T, Dim >::get_sPos(), IpplMemoryUsage::getInstance(), IpplMemoryUsage::getMemoryUsage(), IpplInfo::getNodes(), PartBunchBase< T, Dim >::getT(), IpplInfo::myNode(), SDDSWriter::open(), Units::s2ns, IpplMemoryUsage::sample(), SDDSWriter::writeHeader(), and SDDSWriter::writeRow().
The documentation for this class was generated from the following files:
src/Structure/MemoryWriter.h
src/Structure/MemoryWriter.cpp