OPAL (Object Oriented Parallel Accelerator Library): EMField Class Reference
EMField Class Reference abstract
Abstract base class for electromagnetic fields.
#include <EMField.h>
Public Member Functions
EMField ()
Default constructor.
EMField (const EMField &right)
virtual ~EMField ()
const EMField & operator= (const EMField &right)
virtual EVector Efield (const Point3D &P) const
Get field.
virtual BVector Bfield (const Point3D &P) const
Get field.
virtual EVector Efield (const Point3D &P, double t) const
Get field.
virtual BVector Bfield (const Point3D &P, double t) const
Get field.
virtual EBVectors EBfield (const Point3D &P) const
Get field.
virtual EBVectors EBfield (const Point3D &P, double t) const
Get field.
virtual void scale (double scalar)=0
Scale the field.
Static Public Attributes
static const EVector ZeroEfield
The constant representing a zero electric field.
static const BVector ZeroBfield
The constant representing a zero magnetic field.
static const EBVectors ZeroEBfield
The constant representing a zero electromagnetic field.
Detailed Description
Abstract base class for electromagnetic fields.
Definition at line 188 of file EMField.h.
Constructor & Destructor Documentation
EMField() [1/2]
EMField::EMField ()
Default constructor.
Definition at line 146 of file EMField.cpp.
EMField() [2/2]
EMField::EMField (const EMField & right)
Definition at line 150 of file EMField.cpp.
~EMField()
EMField::~EMField () virtual
Definition at line 154 of file EMField.cpp.
Member Function Documentation
Bfield() [1/2]
BVector EMField::Bfield (const Point3D & P) const virtual
Get field.
Reimplemented in OscillatingField< ConstEzField >, BSingleMultipoleField< order >, BMultipoleField, BDipoleField, and ConstBzField.
Definition at line 168 of file EMField.cpp.
References ZeroBfield.
Referenced by Component::Bfield(), Bfield(), and EBfield().
Bfield() [2/2]
BVector EMField::Bfield (const Point3D & P, double t) const virtual
Get field.
Reimplemented in OscillatingField< ConstEzField >, BSingleMultipoleField< order >, BMultipoleField, BDipoleField, and ConstBzField.
Definition at line 178 of file EMField.cpp.
References Bfield(), and X.
EBfield() [1/2]
EBVectors EMField::EBfield (const Point3D & P) const virtual
Get field.
Definition at line 183 of file EMField.cpp.
References Bfield(), Efield(), and X.
Referenced by Component::EBfield(), and EBfield().
EBfield() [2/2]
EBVectors EMField::EBfield (const Point3D & P, double t) const virtual
Get field.
Definition at line 188 of file EMField.cpp.
References EBfield(), and X.
Efield() [1/2]
EVector EMField::Efield (const Point3D & P) const virtual
Get field.
Reimplemented in OscillatingField< ConstEzField >, and ConstEzField.
Definition at line 163 of file EMField.cpp.
References ZeroEfield.
Referenced by EBfield(), Component::Efield(), and Efield().
Efield() [2/2]
EVector EMField::Efield (const Point3D & P, double t) const virtual
Get field.
Reimplemented in OscillatingField< ConstEzField >, and ConstEzField.
Definition at line 173 of file EMField.cpp.
References Efield(), and X.
operator=()
const EMField & EMField::operator= (const EMField & right)
Definition at line 158 of file EMField.cpp.
scale()
virtual void EMField::scale (double scalar) pure virtual
Scale the field.
Implemented in BMultipoleField, BDipoleField, BSingleMultipoleField< order >, ConstBzField, ConstEzField, and NullField.
Member Data Documentation
ZeroBfield
const BVector EMField::ZeroBfield static
The constant representing a zero magnetic field.
Definition at line 239 of file EMField.h.
Referenced by Bfield().
ZeroEBfield
const EBVectors EMField::ZeroEBfield static
The constant representing a zero electromagnetic field.
Definition at line 242 of file EMField.h.
ZeroEfield
const EVector EMField::ZeroEfield static
The constant representing a zero electric field.
Definition at line 236 of file EMField.h.
Referenced by Efield().
The documentation for this class was generated from the following files:
src/Classic/Fields/EMField.h
src/Classic/Fields/EMField.cpp