OPAL (Object Oriented Parallel Accelerator Library): Poller Class Reference
Poller Class Reference abstract
#include <Poller.h>
Public Member Functions
Poller (MPI_Comm comm, double delay=0.1)
virtual ~Poller ()
Protected Member Functions
virtual bool onMessage (MPI_Status status, size_t recv_value)=0
virtual void onStop ()=0
enable implementation to react to STOP tag
virtual void setupPoll ()=0
executed before starting polling loop
virtual void prePoll ()=0
executed before checking for new request
virtual void postPoll ()=0
executed after handling (if any) new request
virtual void run ()
Protected Attributes
MPI_Comm comm_m
communicator the poller listens to requests
bool is_running_
double last_polled_
time of last MPI_Test
double poll_delay_
delay in seconds between polls
Detailed Description
Definition at line 35 of file Poller.h.
Constructor & Destructor Documentation
Poller()
Poller::Poller (MPI_Comm comm, double delay = 0.1) inline
Definition at line 39 of file Poller.h.
References last_polled_.
~Poller()
virtual Poller::~Poller () inline virtual
Definition at line 47 of file Poller.h.
Member Function Documentation
onMessage()
virtual bool Poller::onMessage (MPI_Status status, size_t recv_value) protected pure virtual
User specific behavior on receiving a message.
Returns
boolean indicating if Irecv has to be re-posted
Implemented in Pilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >, SamplePilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >, Worker< Sim_t >, SampleWorker< Sim_t >, FixedPisaNsga2< CrossoverOperator, MutationOperator >, Sampler, and Optimizer.
Referenced by run().
onStop()
virtual void Poller::onStop () protected pure virtual
enable implementation to react to STOP tag
Implemented in Pilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >, Worker< Sim_t >, FixedPisaNsga2< CrossoverOperator, MutationOperator >, Sampler, and Optimizer.
Referenced by run().
postPoll()
virtual void Poller::postPoll () protected pure virtual
executed after handling (if any) new request
Implemented in Pilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >, Worker< Sim_t >, SamplePilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >, FixedPisaNsga2< CrossoverOperator, MutationOperator >, Sampler, and Optimizer.
Referenced by run().
prePoll()
virtual void Poller::prePoll () protected pure virtual
executed before checking for new request
Implemented in Pilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >, Worker< Sim_t >, FixedPisaNsga2< CrossoverOperator, MutationOperator >, Sampler, and Optimizer.
Referenced by run().
run()
virtual void Poller::run () inline protected virtual
The poll loop stops when receiving a 'MPI_STOP_TAG' otherwise passes message to user.
Reimplemented in Pilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >.
Definition at line 79 of file Poller.h.
References comm_m, is_running_, last_polled_, MPI_STOP_TAG, onMessage(), onStop(), poll_delay_, postPoll(), prePoll(), and setupPoll().
Referenced by Sampler::initialize(), SampleWorker< Sim_t >::onMessage(), SampleWorker< Sim_t >::runSlave(), SampleWorker< Sim_t >::SampleWorker(), and Worker< Sim_t >::Worker().
setupPoll()
virtual void Poller::setupPoll () protected pure virtual
executed before starting polling loop
Implemented in Pilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >, Worker< Sim_t >, FixedPisaNsga2< CrossoverOperator, MutationOperator >, Sampler, and Optimizer.
Referenced by run().
Member Data Documentation
comm_m
MPI_Comm Poller::comm_m protected
communicator the poller listens to requests
Definition at line 52 of file Poller.h.
Referenced by SampleWorker< Sim_t >::onMessage(), Worker< Sim_t >::onMessage(), Pilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >::parseInputFile(), run(), and Worker< Sim_t >::setupPoll().
is_running_
bool Poller::is_running_ protected
Definition at line 54 of file Poller.h.
Referenced by run(), Worker< Sim_t >::runCoWorker(), and SampleWorker< Sim_t >::runSlave().
last_polled_
double Poller::last_polled_ protected
time of last MPI_Test
Definition at line 57 of file Poller.h.
Referenced by Poller(), and run().
poll_delay_
double Poller::poll_delay_ protected
delay in seconds between polls
Definition at line 59 of file Poller.h.
Referenced by run().
The documentation for this class was generated from the following file:
optimizer/Pilot/Poller.h