OPAL (Object Oriented Parallel Accelerator Library): PyOpal::ExceptionTranslation Namespace Reference
PyOpal::ExceptionTranslation Namespace Reference
Functions
void registerExceptions ()
template<class T >
void translateException (T const &exception)
template<class T >
void translateOpalException (T const &exception)
Detailed Description
Exception translation uses boost::python hooks to wrap C++ exceptions
Function Documentation
registerExceptions()
void PyOpal::ExceptionTranslation::registerExceptions ()
Register exception translations with boost
Definition at line 23 of file ExceptionTranslation.cpp.
Referenced by PyOpal::PyOpalGlobalCartesianOffset::BOOST_PYTHON_MODULE(), PyOpal::PyOpalLocalCartesianOffset::BOOST_PYTHON_MODULE(), PyOpal::PyOpalElement::BOOST_PYTHON_MODULE(), PyOpal::PyProbe::BOOST_PYTHON_MODULE(), PyOpal::PyEnge::BOOST_PYTHON_MODULE(), PyOpal::PyAsymmetricEnge::BOOST_PYTHON_MODULE(), PyOpal::PyOpalPolynomialTimeDependence::BOOST_PYTHON_MODULE(), PyOpal::PyDistributionNS::BOOST_PYTHON_MODULE(), PyOpal::PyBeamNS::BOOST_PYTHON_MODULE(), PyOpal::PyLineNS::BOOST_PYTHON_MODULE(), PyOpal::PyVerticalFFAMagnet::BOOST_PYTHON_MODULE(), PyOpal::PyTrackCmdNS::BOOST_PYTHON_MODULE(), PyOpal::PyOutputPlane::BOOST_PYTHON_MODULE(), PyOpal::PyMultipoleT::BOOST_PYTHON_MODULE(), PyOpal::PyTrackRunNS::BOOST_PYTHON_MODULE(), PyOpal::PyVariableRFCavity::BOOST_PYTHON_MODULE(), PyOpal::PyFieldSolverNS::BOOST_PYTHON_MODULE(), PyOpal::PyVariableRFCavityFringeField::BOOST_PYTHON_MODULE(), PyOpal::PyOptionNS::BOOST_PYTHON_MODULE(), PyOpal::PyParser::BOOST_PYTHON_MODULE(), PyOpal::PyScalingFFAMagnet::BOOST_PYTHON_MODULE(), PyOpal::PyPolynomialPatch::BOOST_PYTHON_MODULE(), PyOpal::PyRingDefinition::BOOST_PYTHON_MODULE(), PyOpal::PyNDGrid::BOOST_PYTHON_MODULE(), and PyOpal::Field::BOOST_PYTHON_MODULE().
translateException()
template<class T > void PyOpal::ExceptionTranslation::translateException (T const & exception)
Translates the std::exceptions into a RuntimeError
Definition at line 39 of file ExceptionTranslation.h.
translateOpalException()
template<class T > void PyOpal::ExceptionTranslation::translateOpalException (T const & exception)
Translates the OpalExceptions into a RuntimeError
Definition at line 45 of file ExceptionTranslation.h.