OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Region/PRegion.h File Reference
PRegion.h File Reference
#include "Message/Message.h"
#include <iostream>
Classes
class PRegion< T >
class PRegion< T >
Functions
template<class T >
PRegion< T > operator+ (const PRegion< T > &, T)
template<class T >
PRegion< T > operator+ (T, const PRegion< T > &)
template<class T >
PRegion< T > operator- (const PRegion< T > &, T)
template<class T >
PRegion< T > operator- (T, const PRegion< T > &)
template<class T >
PRegion< T > operator- (const PRegion< T > &)
template<class T >
PRegion< T > operator* (const PRegion< T > &, T)
template<class T >
PRegion< T > operator* (T, const PRegion< T > &)
template<class T >
PRegion< T > operator/ (const PRegion< T > &, T)
template<class T >
std::ostream & operator<< (std::ostream &, const PRegion< T > &)
Function Documentation
operator*() [1/2]
template<class T > PRegion< T > operator* (const PRegion< T > & r, T t) inline
Definition at line 249 of file PRegion.h.
References PRegion< T >::first(), and PRegion< T >::last().
operator*() [2/2]
template<class T > PRegion< T > operator* (T t, const PRegion< T > & r) inline
Definition at line 254 of file PRegion.h.
References PRegion< T >::first(), and PRegion< T >::last().
operator+() [1/2]
template<class T > PRegion< T > operator+ (const PRegion< T > & r, T t) inline
Definition at line 222 of file PRegion.h.
References PRegion< T >::first(), and PRegion< T >::last().
operator+() [2/2]
template<class T > PRegion< T > operator+ (T t, const PRegion< T > & r) inline
Definition at line 227 of file PRegion.h.
References PRegion< T >::first(), and PRegion< T >::last().
operator-() [1/3]
template<class T > PRegion< T > operator- (const PRegion< T > & r, T t) inline
Definition at line 232 of file PRegion.h.
References PRegion< T >::first(), and PRegion< T >::last().
operator-() [2/3]
template<class T > PRegion< T > operator- (T t, const PRegion< T > & r) inline
Definition at line 237 of file PRegion.h.
References PRegion< T >::first(), and PRegion< T >::last().
operator-() [3/3]
template<class T > PRegion< T > operator- (const PRegion< T > & r) inline
Definition at line 244 of file PRegion.h.
References PRegion< T >::first(), and PRegion< T >::last().
operator/()
template<class T > PRegion< T > operator/ (const PRegion< T > & r, T t) inline
Definition at line 259 of file PRegion.h.
References PRegion< T >::first(), and PRegion< T >::last().
operator<<()
template<class T > std::ostream & operator<< (std::ostream & out, const PRegion< T > & r) inline
Definition at line 269 of file PRegion.h.
References PRegion< T >::min().