OPAL (Object Oriented Parallel Accelerator Library): SubFieldTraits< T, Dim, SIndex< Dim >, NDIndex< Dim > > Struct Template Reference
SubFieldTraits< T, Dim, SIndex< Dim >, NDIndex< Dim > > Struct Template Reference
#include <SubFieldTraits.h>
Public Types
enum { Brackets_u = 0 }
typedef SIndex< Dim > Return_t
Static Public Member Functions
static int construct (SIndex< Dim > &out, const NDIndex< Dim > &s, BareField< T, Dim > &A)
static void combine (const SIndex< Dim > &s1, const NDIndex< Dim > &s2, Return_t &out, unsigned int, BareField< T, Dim > &)
Detailed Description
template<class T, unsigned int Dim>
struct SubFieldTraits< T, Dim, SIndex< Dim >, NDIndex< Dim > >
Definition at line 196 of file SubFieldTraits.h.
Member Typedef Documentation
Return_t
template<class T , unsigned int Dim> typedef SIndex<Dim> SubFieldTraits< T, Dim, SIndex< Dim >, NDIndex< Dim > >::Return_t
Definition at line 204 of file SubFieldTraits.h.
Member Enumeration Documentation
anonymous enum
template<class T , unsigned int Dim> anonymous enum
Enumerator
Brackets_u
Definition at line 205 of file SubFieldTraits.h.
Member Function Documentation
combine()
template<class T , unsigned int Dim> static void SubFieldTraits< T, Dim, SIndex< Dim >, NDIndex< Dim > >::combine (const SIndex< Dim > & s1, const NDIndex< Dim > & s2, Return_t & out, unsigned int, BareField< T, Dim > &) inline static
Definition at line 206 of file SubFieldTraits.h.
construct()
template<class T , unsigned int Dim> static int SubFieldTraits< T, Dim, SIndex< Dim >, NDIndex< Dim > >::construct (SIndex< Dim > & out, const NDIndex< Dim > & s, BareField< T, Dim > & A) inline static
Definition at line 197 of file SubFieldTraits.h.
References Dim, BareField< T, Dim >::getLayout(), SIndex< Dim >::initialize(), and SIndex< Dim >::needInitialize().
The documentation for this struct was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/SubField/SubFieldTraits.h