OPAL (Object Oriented Parallel Accelerator Library): MacroCmd Class Reference
MacroCmd Class Reference
#include <MacroCmd.h>
Public Member Functions
MacroCmd ()
MacroCmd (const std::string &name, MacroCmd *parent)
virtual ~MacroCmd ()
virtual void execute ()
Execute the macro command.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Make a macro instance.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Make a macro template.
Public Member Functions inherited from Macro
Macro (int size, const char *name, const char *help)
Exemplar constructor.
Macro (const std::string &name, Object *parent)
Clone constructor.
virtual ~Macro ()
virtual Macro * clone (const std::string &name)
Make clone.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual void parseActuals (Statement &)
Parse actual arguments.
virtual void parseFormals (Statement &)
Parse formal arguments.
Public Member Functions inherited from Object
virtual ~Object ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
MacroCmd (const MacroCmd &)
void operator= (const MacroCmd &)
Private Attributes
Pointer< MacroStream > body
const Parser * itsParser
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Macro
std::vector< std::string > formals
The formal argument list.
std::vector< std::vector< Token > > actuals
The actual argument list.
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 35 of file MacroCmd.h.
Constructor & Destructor Documentation
MacroCmd() [1/3]
MacroCmd::MacroCmd ()
Definition at line 34 of file MacroCmd.cpp.
MacroCmd() [2/3]
MacroCmd::MacroCmd (const std::string & name, MacroCmd * parent)
Definition at line 42 of file MacroCmd.cpp.
References body, and name.
~MacroCmd()
MacroCmd::~MacroCmd () virtual
Definition at line 48 of file MacroCmd.cpp.
MacroCmd() [3/3]
MacroCmd::MacroCmd (const MacroCmd &) private
Member Function Documentation
execute()
void MacroCmd::execute () virtual
Execute the macro command.
Reimplemented from Object.
Definition at line 52 of file MacroCmd.cpp.
References body, itsParser, Parser::run(), and MacroStream::start().
makeInstance()
Object * MacroCmd::makeInstance (const std::string & name, Statement & statement, const Parser * parser) virtual
Make a macro instance.
Reimplemented from Object.
Definition at line 59 of file MacroCmd.cpp.
References MacroStream::append(), body, Token::getWord(), Token::isEOF(), Token::isWord(), itsParser, and name.
makeTemplate()
Object * MacroCmd::makeTemplate (const std::string & name, TokenStream & , Statement & statement) virtual
Make a macro template.
Reimplemented from Object.
Definition at line 102 of file MacroCmd.cpp.
References MacroStream::append(), Statement::atEnd(), body, Statement::delimiter(), Statement::getCurrent(), Token::isDel(), Statement::keyword(), name, Macro::parseFormals(), and PAssert.
operator=()
void MacroCmd::operator= (const MacroCmd &) private
Member Data Documentation
body
Pointer<MacroStream> MacroCmd::body private
Definition at line 64 of file MacroCmd.h.
Referenced by execute(), MacroCmd(), makeInstance(), and makeTemplate().
itsParser
const Parser* MacroCmd::itsParser private
Definition at line 67 of file MacroCmd.h.
Referenced by execute(), and makeInstance().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/OpalParser/MacroCmd.h
/psi/home/gsell/data/src/OPAL/src/src/OpalParser/MacroCmd.cpp