OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/SubField/SubFieldAssign.h File Reference
SubFieldAssign.h File Reference
#include "Field/Assign.h"
#include "SubField/SubFieldAssign.hpp"
Classes
class SubBareField< T, Dim, S >
Macros
#define SUB_ASSIGNMENT_OPERATORS(FUNC, OP)
Functions
template<class T1 , unsigned Dim, class S , class RHS , class OP >
void assign (SubBareField< T1, Dim, S > a, RHS b, OP op, ExprTag< true >)
template<class T , unsigned D, class S , class OP >
void assign (SubBareField< T, D, S > a, const T &b, OP op, ExprTag< true >)
template<class T , unsigned D, class S >
void assign (const SubBareField< T, D, S > &lhs, const T &rhs)
template<class T , unsigned D, class S >
void operator<< (const SubBareField< T, D, S > &lhs, const T &rhs)
template<class T , unsigned D, class S >
void operator+= (const SubBareField< T, D, S > &lhs, const T &rhs)
template<class T , unsigned D, class S >
void operator-= (const SubBareField< T, D, S > &lhs, const T &rhs)
template<class T , unsigned D, class S >
void operator*= (const SubBareField< T, D, S > &lhs, const T &rhs)
template<class T , unsigned D, class S >
void operator/= (const SubBareField< T, D, S > &lhs, const T &rhs)
template<class T , unsigned D, class S >
void mineq (const SubBareField< T, D, S > &lhs, const T &rhs)
template<class T , unsigned D, class S >
void maxeq (const SubBareField< T, D, S > &lhs, const T &rhs)
Macro Definition Documentation
SUB_ASSIGNMENT_OPERATORS
#define SUB_ASSIGNMENT_OPERATORS (FUNC, OP)
Value:
\
template<class T, unsigned D, class S>                                   \
inline void                                                              \
FUNC(const SubBareField<T,D,S>& lhs, const T& rhs)                       \
{                                                                        \
  assign(lhs,PETE_Scalar<T>(rhs), OP(),ExprTag<true>());                 \
}
Definition at line 49 of file SubFieldAssign.h.
Function Documentation
assign() [1/3]
template<class T1 , unsigned Dim, class S , class RHS , class OP > void assign (SubBareField< T1, Dim, S > a, RHS b, OP op, ExprTag< true >)
Definition at line 44 of file SubFieldAssign.hpp.
References a, IpplInfo::abort(), LField< T, Dim >::begin(), endl(), ERRORMSG, IpplInfo::extraCompressChecks, FillGCIfNecessary(), for_each(), LField< T, Dim >::getOwned(), INCIPPLSTAT, PETE_apply(), PInsist, LField< T, Dim >::TryCompress(), TryCompressLHS(), and LField< T, Dim >::Uncompress().
Referenced by assign().
assign() [2/3]
template<class T , unsigned D, class S , class OP > void assign (SubBareField< T, D, S > a, const T & b, OP op, ExprTag< true >) inline
Definition at line 42 of file SubFieldAssign.h.
References a, and assign().
assign() [3/3]
template<class T , unsigned D, class S > void assign (const SubBareField< T, D, S > & lhs, const T & rhs) inline
Definition at line 59 of file SubFieldAssign.h.
maxeq()
template<class T , unsigned D, class S > void maxeq (const SubBareField< T, D, S > & lhs, const T & rhs) inline
Definition at line 66 of file SubFieldAssign.h.
mineq()
template<class T , unsigned D, class S > void mineq (const SubBareField< T, D, S > & lhs, const T & rhs) inline
Definition at line 65 of file SubFieldAssign.h.
operator*=()
template<class T , unsigned D, class S > void operator*= (const SubBareField< T, D, S > & lhs, const T & rhs) inline
Definition at line 63 of file SubFieldAssign.h.
operator+=()
template<class T , unsigned D, class S > void operator+= (const SubBareField< T, D, S > & lhs, const T & rhs) inline
Definition at line 61 of file SubFieldAssign.h.
operator-=()
template<class T , unsigned D, class S > void operator-= (const SubBareField< T, D, S > & lhs, const T & rhs) inline
Definition at line 62 of file SubFieldAssign.h.
operator/=()
template<class T , unsigned D, class S > void operator/= (const SubBareField< T, D, S > & lhs, const T & rhs) inline
Definition at line 64 of file SubFieldAssign.h.
operator<<()
template<class T , unsigned D, class S > void operator<< (const SubBareField< T, D, S > & lhs, const T & rhs) inline
Definition at line 60 of file SubFieldAssign.h.