OPAL (Object Oriented Parallel Accelerator Library): MLPoissonSolver Class Reference
MLPoissonSolver Class Reference
#include <MLPoissonSolver.h>
Public Member Functions
MLPoissonSolver (AmrBoxLib *itsAmrObject_p)
void solve (AmrScalarFieldContainer_t &rho, AmrScalarFieldContainer_t &phi, AmrVectorFieldContainer_t &efield, unsigned short baseLevel, unsigned short finestLevel, bool prevAsGuess=true)
double getXRangeMin (unsigned short level=0)
double getXRangeMax (unsigned short level=0)
double getYRangeMin (unsigned short level=0)
double getYRangeMax (unsigned short level=0)
double getZRangeMin (unsigned short level=0)
double getZRangeMax (unsigned short level=0)
Inform & print (Inform &os) const
Public Member Functions inherited from AmrPoissonSolver< AmrBoxLib >
AmrPoissonSolver (AmrBoxLib *itsAmrObject_p)
virtual ~AmrPoissonSolver ()
void computePotential (Field_t &, Vector_t)
void computePotential (Field_t &, Vector_t, double)
void test (PartBunchBase< double, 3 > *)
void hasToRegrid ()
Public Member Functions inherited from PoissonSolver
virtual ~PoissonSolver ()
virtual void resizeMesh (Vector_t &, Vector_t &, const Vector_t &, const Vector_t &, double)
virtual double getinteractionRadius () const
virtual void calculatePairForces (PartBunchBase< double, 3 > *, double)
Private Types
typedef AmrBoxLib::AmrGeomContainer_t GeomContainer_t
typedef amrex::Vector< AmrBoxLib::AmrField_t * > AmrFieldContainer_pt
typedef amrex::Vector< const AmrBoxLib::AmrField_t * > const_AmrFieldContainer_pt
typedef AmrBoxLib::AmrGeometry_t AmrGeometry_t
typedef AmrBoxLib::AmrGrid_t AmrGrid_t
typedef AmrBoxLib::AmrProcMap_t AmrProcMap_t
typedef AmrBoxLib::AmrScalarFieldContainer_t AmrScalarFieldContainer_t
typedef AmrBoxLib::AmrVectorFieldContainer_t AmrVectorFieldContainer_t
typedef AmrBoxLib::AmrGridContainer_t AmrGridContainer_t
typedef AmrBoxLib::AmrProcMapContainer_t AmrProcMapContainer_t
Private Member Functions
void mlmg_m (AmrScalarFieldContainer_t &rho, AmrScalarFieldContainer_t &phi, AmrVectorFieldContainer_t &efield, int baseLevel, int finestLevel)
Private Attributes
double reltol_m
Relative tolearance for solver.
double abstol_m
Absolute tolerance for solver.
Additional Inherited Members
Protected Types inherited from PoissonSolver
typedef Field< int, 3, Mesh_t, Center_t > IField_t
typedef Field< std::complex< double >, 3, Mesh_t, Center_t > CxField_t
Protected Attributes inherited from AmrPoissonSolver< AmrBoxLib >
AmrBoxLib * itsAmrObject_mp
bool regrid_m
is set to true by itsAmrObject_mp and reset to false by solver
Detailed Description
Definition at line 27 of file MLPoissonSolver.h.
Member Typedef Documentation
AmrFieldContainer_pt
typedef amrex::Vector<AmrBoxLib::AmrField_t*> MLPoissonSolver::AmrFieldContainer_pt private
Definition at line 31 of file MLPoissonSolver.h.
AmrGeometry_t
typedef AmrBoxLib::AmrGeometry_t MLPoissonSolver::AmrGeometry_t private
Definition at line 33 of file MLPoissonSolver.h.
AmrGrid_t
typedef AmrBoxLib::AmrGrid_t MLPoissonSolver::AmrGrid_t private
Definition at line 34 of file MLPoissonSolver.h.
AmrGridContainer_t
typedef AmrBoxLib::AmrGridContainer_t MLPoissonSolver::AmrGridContainer_t private
Definition at line 38 of file MLPoissonSolver.h.
AmrProcMap_t
typedef AmrBoxLib::AmrProcMap_t MLPoissonSolver::AmrProcMap_t private
Definition at line 35 of file MLPoissonSolver.h.
AmrProcMapContainer_t
typedef AmrBoxLib::AmrProcMapContainer_t MLPoissonSolver::AmrProcMapContainer_t private
Definition at line 39 of file MLPoissonSolver.h.
AmrScalarFieldContainer_t
typedef AmrBoxLib::AmrScalarFieldContainer_t MLPoissonSolver::AmrScalarFieldContainer_t private
Definition at line 36 of file MLPoissonSolver.h.
AmrVectorFieldContainer_t
typedef AmrBoxLib::AmrVectorFieldContainer_t MLPoissonSolver::AmrVectorFieldContainer_t private
Definition at line 37 of file MLPoissonSolver.h.
const_AmrFieldContainer_pt
typedef amrex::Vector<const AmrBoxLib::AmrField_t*> MLPoissonSolver::const_AmrFieldContainer_pt private
Definition at line 32 of file MLPoissonSolver.h.
GeomContainer_t
typedef AmrBoxLib::AmrGeomContainer_t MLPoissonSolver::GeomContainer_t private
Definition at line 30 of file MLPoissonSolver.h.
Constructor & Destructor Documentation
MLPoissonSolver()
MLPoissonSolver::MLPoissonSolver (AmrBoxLib * itsAmrObject_p)
This solver only works with AmrBoxLib. In order the solver to work the cells need to be of cubic shape. Otherwise the solver stops with the error message that it did not converge (AMReX internal).
Parameters
itsAmrObject_p has information about refinemen ratios, etc.
Definition at line 31 of file MLPoissonSolver.cpp.
Member Function Documentation
getXRangeMax()
double MLPoissonSolver::getXRangeMax (unsigned short level = 0) virtual
Implements PoissonSolver.
Definition at line 60 of file MLPoissonSolver.cpp.
References AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp.
getXRangeMin()
double MLPoissonSolver::getXRangeMin (unsigned short level = 0) virtual
Implements PoissonSolver.
Definition at line 55 of file MLPoissonSolver.cpp.
References AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp.
getYRangeMax()
double MLPoissonSolver::getYRangeMax (unsigned short level = 0) virtual
Implements PoissonSolver.
Definition at line 70 of file MLPoissonSolver.cpp.
References AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp.
getYRangeMin()
double MLPoissonSolver::getYRangeMin (unsigned short level = 0) virtual
Implements PoissonSolver.
Definition at line 65 of file MLPoissonSolver.cpp.
References AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp.
getZRangeMax()
double MLPoissonSolver::getZRangeMax (unsigned short level = 0) virtual
Implements PoissonSolver.
Definition at line 80 of file MLPoissonSolver.cpp.
References AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp.
getZRangeMin()
double MLPoissonSolver::getZRangeMin (unsigned short level = 0) virtual
Implements PoissonSolver.
Definition at line 75 of file MLPoissonSolver.cpp.
References AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp.
mlmg_m()
void MLPoissonSolver::mlmg_m (AmrScalarFieldContainer_t & rho, AmrScalarFieldContainer_t & phi, AmrVectorFieldContainer_t & efield, int baseLevel, int finestLevel) private
Does the actual solve.
Parameters
rho charge density on grids [C / m]
phi electrostatic potential on grid [V]
baseLevel for solve
finestLevel for solve
Definition at line 94 of file MLPoissonSolver.cpp.
References abstol_m, Options::info, AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp, and reltol_m.
Referenced by solve().
print()
Inform & MLPoissonSolver::print (Inform & os) const
Print information abour tolerances.
Parameters
os output stream where to write to
Definition at line 85 of file MLPoissonSolver.cpp.
References abstol_m, endl(), and reltol_m.
solve()
void MLPoissonSolver::solve (AmrScalarFieldContainer_t & rho, AmrScalarFieldContainer_t & phi, AmrVectorFieldContainer_t & efield, unsigned short baseLevel, unsigned short finestLevel, bool prevAsGuess = true) virtual
Multigrid solve based on AMReX FMultiGrid solver. The relative tolerance is set to 1.0e-9 and the absolute tolerance to 0.0.
Parameters
rho right-hand side charge density on grid [C / m]
phi electrostatic potential (unknown) [V]
efield electric field [V / m]
baseLevel for solve
finestLevel for solve
prevAsGuess use of previous solution as initial guess
Reimplemented from PoissonSolver.
Definition at line 37 of file MLPoissonSolver.cpp.
References mlmg_m().
Member Data Documentation
abstol_m
double MLPoissonSolver::abstol_m private
Absolute tolerance for solver.
Definition at line 103 of file MLPoissonSolver.h.
Referenced by mlmg_m(), and print().
reltol_m
double MLPoissonSolver::reltol_m private
Relative tolearance for solver.
Definition at line 102 of file MLPoissonSolver.h.
Referenced by mlmg_m(), and print().
The documentation for this class was generated from the following files:
src/Solvers/AMReXSolvers/MLPoissonSolver.h
src/Solvers/AMReXSolvers/MLPoissonSolver.cpp