OPAL (Object Oriented Parallel Accelerator Library): SigmaGenerator Class Reference
SigmaGenerator Class Reference
#include <SigmaGenerator.h>
Public Types
typedef RealDiracMatrix::matrix_t matrix_t
Type for storing maps.
typedef RealDiracMatrix::sparse_matrix_t sparse_matrix_t
Type for storing the sparse maps.
typedef RealDiracMatrix::vector_t vector_t
Type for storing vectors.
typedef std::vector< double > container_t
Container for storing the properties for each angle.
typedef FTps< double, 2 *3 > Series
Type of the truncated power series.
typedef FVps< double, 2 *3 > Map
Type of a map.
typedef std::function< Series(double, double, double)> Hamiltonian
Type of the Hamiltonian for the cyclotron.
typedef std::function< Series(double, double, double)> SpaceCharge
Type of the Hamiltonian for the space charge.
Public Member Functions
SigmaGenerator (double I, double ex, double ey, double ez, double E, double m, double q, const Cyclotron *cycl, unsigned int N, unsigned int Nsectors, unsigned int truncOrder, bool write=true)
Constructs an object of type SigmaGenerator.
bool match (double accuracy, unsigned int maxit, unsigned int maxitOrbit, Cyclotron *cycl, double denergy, double rguess, bool full)
Searches for a matched distribution.
vector_t decouple (const matrix_t &Mturn, sparse_matrix_t &R, sparse_matrix_t &invR)
Block diagonalizes the symplex part of the one turn transfer matrix.
double isEigenEllipse (const matrix_t &Mturn, const matrix_t &sigma)
Checks if the sigma-matrix is an eigenellipse and returns the L2 error.
matrix_t & getSigma ()
Returns the converged stationary distribution.
unsigned int getIterations () const
Returns the number of iterations needed for convergence (if not converged, it returns zero)
double getError () const
Returns the error (if the program didn't converged, one can call this function to check the error)
std::array< double, 3 > getEmittances () const
const double & getInjectionRadius () const
const double & getInjectionMomentum () const
Private Member Functions
void initialize (double, double)
matrix_t updateInitialSigma (const matrix_t &, const vector_t &, sparse_matrix_t &, sparse_matrix_t &)
Computes the new initial sigma matrix.
void updateSigma (const std::vector< matrix_t > &, const std::vector< matrix_t > &)
Computes new sigma matrices (one for each angle)
double L2ErrorNorm (const matrix_t &, const matrix_t &)
Returns the L2-error norm between the old and new sigma-matrix.
std::string float2string (double val)
Transforms a floating point value to a string.
void writeOrbitOutput_m (const container_t &r_turn, const container_t &peo, const container_t &h_turn, const container_t &fidx_turn, const container_t &ds_turn)
Called within SigmaGenerator::match().
void writeMatrix (std::ofstream &, const matrix_t &)
template<class matrix >
void reduce (matrix &)
template<class matrix >
void expand (matrix &)
Private Attributes
double I_m
Stores the value of the current, \(\left[I\right] = A \).
std::array< double, 3 > emittance_m
double wo_m
Is the orbital frequency, \(\left[\omega_{o}\right] = \frac{1}{s} \).
double E_m
Stores the user-define energy, \(\left[E\right] = MeV \).
double gamma_m
double gamma2_m
Relativistic factor squared.
double nh_m
Harmonic number, \(\left[N_{h}\right] = 1 \).
double beta_m
Velocity (c/v), \(\left[\beta\right] = 1 \).
double mass_m
Is the mass of the particles, \(\left[m\right] = \frac{MeV}{c^{2}} \).
double q_m
Is the particle charge [e].
unsigned int niterations_m
Is the number of iterations needed for convergence.
bool converged_m
Is true if converged, false otherwise.
double Emin_m
Minimum energy needed in cyclotron, \(\left[E_{min}\right] = MeV \).
double Emax_m
Maximum energy reached in cyclotron, \(\left[E_{max}\right] = MeV \).
unsigned int N_m
Number of integration steps for closed orbit computation.
unsigned int nSectors_m
Number of (symmetric) sectors the field is averaged over.
unsigned int nStepsPerSector_m
Number of integration steps per sector (–> also: number of maps per sector)
unsigned int nSteps_m
Number of integration steps in total.
double error_m
Error of computation.
unsigned int truncOrder_m
Truncation order of the power series for the Hamiltonian (cyclotron and space charge)
bool write_m
Decides for writing output (default: true)
matrix_t sigma_m
Stores the stationary distribution (sigma matrix)
std::vector< matrix_t > sigmas_m
Vector storing the second moment matrix for each angle.
Hamiltonian H_m
Stores the Hamiltonian of the cyclotron.
SpaceCharge Hsc_m
Stores the Hamiltonian for the space charge.
Series x_m
All variables x, px, z, pz, l, delta.
Series px_m
Series z_m
Series pz_m
Series l_m
Series delta_m
double rinit_m
double prinit_m
RealDiracMatrix rdm_m
RealDiracMatrix-class member used for decoupling
Detailed Description
Definition at line 51 of file SigmaGenerator.h.
Member Typedef Documentation
container_t
typedef std::vector<double> SigmaGenerator::container_t
Container for storing the properties for each angle.
Definition at line 61 of file SigmaGenerator.h.
Hamiltonian
typedef std::function<Series(double,double,double)> SigmaGenerator::Hamiltonian
Type of the Hamiltonian for the cyclotron.
Definition at line 67 of file SigmaGenerator.h.
Map
typedef FVps<double,2*3> SigmaGenerator::Map
Type of a map.
Definition at line 65 of file SigmaGenerator.h.
matrix_t
typedef RealDiracMatrix::matrix_t SigmaGenerator::matrix_t
Type for storing maps.
Definition at line 55 of file SigmaGenerator.h.
Series
typedef FTps<double,2*3> SigmaGenerator::Series
Type of the truncated power series.
Definition at line 63 of file SigmaGenerator.h.
SpaceCharge
typedef std::function<Series(double,double,double)> SigmaGenerator::SpaceCharge
Type of the Hamiltonian for the space charge.
Definition at line 69 of file SigmaGenerator.h.
sparse_matrix_t
typedef RealDiracMatrix::sparse_matrix_t SigmaGenerator::sparse_matrix_t
Type for storing the sparse maps.
Definition at line 57 of file SigmaGenerator.h.
vector_t
typedef RealDiracMatrix::vector_t SigmaGenerator::vector_t
Type for storing vectors.
Definition at line 59 of file SigmaGenerator.h.
Constructor & Destructor Documentation
SigmaGenerator()
SigmaGenerator::SigmaGenerator (double I, double ex, double ey, double ez, double E, double m, double q, const Cyclotron * cycl, unsigned int N, unsigned int Nsectors, unsigned int truncOrder, bool write = true)
Constructs an object of type SigmaGenerator.
Parameters
I specifies the current for which a matched distribution should be found, \([I] = A \)
ex is the emittance in x-direction (horizontal), \(\left[\varepsilon_{x}\right] = \pi\ mm\ mrad \)
ey is the emittance in y-direction (longitudinal), \(\left[\varepsilon_{y}\right] = \pi\ mm\ mrad \)
ez is the emittance in z-direction (vertical), \(\left[\varepsilon_{z}\right] = \pi\ mm\ mrad \)
E is the energy, \(\left[E\right] = MeV \)
m is the mass of the particles \(\left[m\right] = \frac{MeV}{c^{2}} \)
q is the particle charge [e]
cycl is the cyclotron element
N is the number of integration steps (closed orbit computation). That's why its also the number of maps (for each integration step a map)
Nsectors is the number of sectors that the field map is averaged over (closed orbit computation)
truncOrder is the truncation order for power series of the Hamiltonian
write is a boolean (default: true). If true all maps of all iterations are stored, otherwise not.
Definition at line 54 of file SigmaGenerator.cpp.
References abs(), beta_m, Physics::c, delta_m, Emin_m, emittance_m, Physics::epsilon_0, gamma2_m, gamma_m, Util::getBetaGamma(), H_m, Hsc_m, I_m, l_m, FTps< double, 2 *3 >::makeVariable(), mass_m, Units::MeV2eV, Units::mm2m, Units::mrad2rad, nh_m, Physics::pi, px_m, pz_m, q_m, FTps< double, 2 *3 >::setGlobalTruncOrder(), sqrt(), truncOrder_m, Physics::two_pi, wo_m, x_m, and z_m.
Member Function Documentation
decouple()
SigmaGenerator::vector_t SigmaGenerator::decouple (const matrix_t & Mturn, sparse_matrix_t & R, sparse_matrix_t & invR)
Block diagonalizes the symplex part of the one turn transfer matrix.
It computes the transformation matrix R and its inverse invR.
Parameters
Mturn is a 6x6 dimensional one turn transfer matrix
R is the 6x6 dimensional transformation matrix (gets computed)
invR is the 6x6 dimensional inverse transformation (gets computed)
Definition at line 409 of file SigmaGenerator.cpp.
References RealDiracMatrix::diagonalize(), Attrib::Distribution::R, rdm_m, and RealDiracMatrix::symplex().
Referenced by match().
expand()
template<class matrix > void SigmaGenerator::expand (matrix & M) private
Definition at line 353 of file SigmaGenerator.h.
float2string()
std::string SigmaGenerator::float2string (double val) private
Transforms a floating point value to a string.
Parameters
val is the floating point value which is transformed to a string
Definition at line 813 of file SigmaGenerator.cpp.
Referenced by initialize(), match(), updateInitialSigma(), updateSigma(), and writeOrbitOutput_m().
getEmittances()
std::array< double, 3 > SigmaGenerator::getEmittances () const inline
Returns the emittances (ex,ey,ez) in \(\pi\ mm\ mrad \) for which the code converged (since the whole simulation is done on normalized emittances)
Definition at line 308 of file SigmaGenerator.h.
References beta_m, emittance_m, gamma_m, Units::m2mm, Physics::pi, and Units::rad2mrad.
Referenced by match().
getError()
double SigmaGenerator::getError () const inline
Returns the error (if the program didn't converged, one can call this function to check the error)
Definition at line 301 of file SigmaGenerator.h.
References error_m.
getInjectionMomentum()
const double& SigmaGenerator::getInjectionMomentum () const inline
Definition at line 142 of file SigmaGenerator.h.
References prinit_m.
getInjectionRadius()
const double& SigmaGenerator::getInjectionRadius () const inline
Definition at line 138 of file SigmaGenerator.h.
References rinit_m.
getIterations()
unsigned int SigmaGenerator::getIterations () const inline
Returns the number of iterations needed for convergence (if not converged, it returns zero)
Definition at line 294 of file SigmaGenerator.h.
References converged_m, and niterations_m.
getSigma()
SigmaGenerator::matrix_t & SigmaGenerator::getSigma () inline
Returns the converged stationary distribution.
Definition at line 287 of file SigmaGenerator.h.
References sigma_m.
initialize()
void SigmaGenerator::initialize (double nuz, double ravg) private
Initializes a first guess of the sigma matrix with the assumption of a spherical symmetric beam (ex = ey = ez). For each angle split the same initial guess is taken.
Parameters
nuz is the vertical tune
ravg is the average radius of the closed orbit
Definition at line 458 of file SigmaGenerator.cpp.
References a, abs(), Physics::alpha, beta_m, Physics::c, Util::combineFilePath(), E_m, emittance_m, Physics::epsilon_0, float2string(), gamma2_m, gamma_m, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), I_m, mass_m, Units::MeV2eV, Physics::mu_0, nh_m, nSteps_m, Physics::pi, pow(), q_m, sigmas_m, sqrt(), Physics::two_pi, wo_m, write_m, and writeMatrix().
Referenced by match().
isEigenEllipse()
double SigmaGenerator::isEigenEllipse (const matrix_t & Mturn, const matrix_t & sigma)
Checks if the sigma-matrix is an eigenellipse and returns the L2 error.
The idea of this function is taken from Dr. Christian Baumgarten's program.
Parameters
Mturn is the one turn transfer matrix
sigma is the sigma matrix to be tested
Definition at line 445 of file SigmaGenerator.cpp.
References L2ErrorNorm().
L2ErrorNorm()
double SigmaGenerator::L2ErrorNorm (const matrix_t & oldS, const matrix_t & newS) private
Returns the L2-error norm between the old and new sigma-matrix.
Parameters
oldS is the old sigma matrix
newS is the new sigma matrix
Definition at line 799 of file SigmaGenerator.cpp.
References sqrt().
Referenced by isEigenEllipse(), and match().
match()
bool SigmaGenerator::match (double accuracy, unsigned int maxit, unsigned int maxitOrbit, Cyclotron * cycl, double denergy, double rguess, bool full)
Searches for a matched distribution.
Returns "true" if a matched distribution within the accuracy could be found, returns "false" otherwise.
Parameters
accuracy is used for computing the equilibrium orbit (to a certain accuracy)
maxit is the maximum number of iterations (the program stops if within this value no stationary distribution was found)
maxitOrbit is the maximum number of iterations for finding closed orbit
angle defines the start of the sector (one can choose any angle between 0 and 360)
denergy energy step size for closed orbit finder [MeV]
rguess value of radius for closed orbit finder
type specifies the magnetic field format (e.g. CARBONCYCL)
full match over full turn not just single sector
Definition at line 154 of file SigmaGenerator.cpp.
References Util::combineFilePath(), converged_m, decouple(), Physics::e, E_m, endl(), error_m, float2string(), OpalData::getAuxiliaryOutputDirectory(), getEmittances(), OpalData::getInstance(), Cyclotron::getPHIinit(), gmsg, H_m, Hsc_m, initialize(), L2ErrorNorm(), mass_m, N_m, niterations_m, nSectors_m, nSteps_m, nStepsPerSector_m, prinit_m, q_m, Attrib::Distribution::R, rinit_m, sigma_m, sigmas_m, truncOrder_m, updateInitialSigma(), updateSigma(), write_m, writeMatrix(), and writeOrbitOutput_m().
reduce()
template<class matrix > void SigmaGenerator::reduce (matrix & M) private
Definition at line 320 of file SigmaGenerator.h.
updateInitialSigma()
SigmaGenerator::matrix_t SigmaGenerator::updateInitialSigma (const matrix_t & M, const vector_t & eigen, sparse_matrix_t & R, sparse_matrix_t & invR) private
Computes the new initial sigma matrix.
Parameters
M is the 6x6 one turn transfer matrix
R is the transformation matrix
invR is the inverse transformation matrix
Definition at line 617 of file SigmaGenerator.cpp.
References beta_m, Util::combineFilePath(), E_m, emittance_m, fabs(), float2string(), gamma_m, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), prod(), Attrib::Distribution::R, sign(), sqrt(), write_m, and writeMatrix().
Referenced by match().
updateSigma()
void SigmaGenerator::updateSigma (const std::vector< matrix_t > & Mscs, const std::vector< matrix_t > & Mcycs) private
Computes new sigma matrices (one for each angle)
Mscs is a vector of all space charge maps Mcycs is a vector of all cyclotron maps
Definition at line 761 of file SigmaGenerator.cpp.
References Util::combineFilePath(), E_m, float2string(), OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), niterations_m, nSteps_m, prod(), sigmas_m, write_m, and writeMatrix().
Referenced by match().
writeMatrix()
void SigmaGenerator::writeMatrix (std::ofstream & os, const matrix_t & m) private
Definition at line 857 of file SigmaGenerator.cpp.
References endl(), and write_m.
Referenced by initialize(), match(), updateInitialSigma(), and updateSigma().
writeOrbitOutput_m()
void SigmaGenerator::writeOrbitOutput_m (const container_t & r_turn, const container_t & peo, const container_t & h_turn, const container_t & fidx_turn, const container_t & ds_turn) private
Called within SigmaGenerator::match().
Parameters
r_turn is the radius [m]
peo is the momentum
h_turn is the inverse bending radius
fidx_turn is the field index
ds_turn is the path length element
Definition at line 820 of file SigmaGenerator.cpp.
References Util::combineFilePath(), E_m, endl(), float2string(), OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), and write_m.
Referenced by match().
Member Data Documentation
beta_m
double SigmaGenerator::beta_m private
Velocity (c/v), \(\left[\beta\right] = 1 \).
Definition at line 166 of file SigmaGenerator.h.
Referenced by getEmittances(), initialize(), SigmaGenerator(), and updateInitialSigma().
converged_m
bool SigmaGenerator::converged_m private
Is true if converged, false otherwise.
Definition at line 174 of file SigmaGenerator.h.
Referenced by getIterations(), and match().
delta_m
Series SigmaGenerator::delta_m private
Definition at line 211 of file SigmaGenerator.h.
Referenced by SigmaGenerator().
E_m
double SigmaGenerator::E_m private
Stores the user-define energy, \(\left[E\right] = MeV \).
Definition at line 156 of file SigmaGenerator.h.
Referenced by initialize(), match(), updateInitialSigma(), updateSigma(), and writeOrbitOutput_m().
Emax_m
double SigmaGenerator::Emax_m private
Maximum energy reached in cyclotron, \(\left[E_{max}\right] = MeV \).
Definition at line 178 of file SigmaGenerator.h.
Emin_m
double SigmaGenerator::Emin_m private
Minimum energy needed in cyclotron, \(\left[E_{min}\right] = MeV \).
Definition at line 176 of file SigmaGenerator.h.
Referenced by SigmaGenerator().
emittance_m
std::array<double,3> SigmaGenerator::emittance_m private
Stores the desired emittances, \(\left[\varepsilon_{x}\right] = \left[\varepsilon_{y}\right] = \left[\varepsilon_{z}\right] = m \ rad \)
Definition at line 152 of file SigmaGenerator.h.
Referenced by getEmittances(), initialize(), SigmaGenerator(), and updateInitialSigma().
error_m
double SigmaGenerator::error_m private
Error of computation.
Definition at line 190 of file SigmaGenerator.h.
Referenced by getError(), and match().
gamma2_m
double SigmaGenerator::gamma2_m private
Relativistic factor squared.
Definition at line 162 of file SigmaGenerator.h.
Referenced by initialize(), and SigmaGenerator().
gamma_m
double SigmaGenerator::gamma_m private
Relativistic factor (which can be computed out ot the kinetic energy and rest mass (potential energy)), \(\left[\gamma\right] = 1 \)
Definition at line 160 of file SigmaGenerator.h.
Referenced by getEmittances(), initialize(), SigmaGenerator(), and updateInitialSigma().
H_m
Hamiltonian SigmaGenerator::H_m private
Stores the Hamiltonian of the cyclotron.
Definition at line 205 of file SigmaGenerator.h.
Referenced by match(), and SigmaGenerator().
Hsc_m
SpaceCharge SigmaGenerator::Hsc_m private
Stores the Hamiltonian for the space charge.
Definition at line 208 of file SigmaGenerator.h.
Referenced by match(), and SigmaGenerator().
I_m
double SigmaGenerator::I_m private
Stores the value of the current, \(\left[I\right] = A \).
Definition at line 148 of file SigmaGenerator.h.
Referenced by initialize(), and SigmaGenerator().
l_m
Series SigmaGenerator::l_m private
Definition at line 211 of file SigmaGenerator.h.
Referenced by SigmaGenerator().
mass_m
double SigmaGenerator::mass_m private
Is the mass of the particles, \(\left[m\right] = \frac{MeV}{c^{2}} \).
Definition at line 168 of file SigmaGenerator.h.
Referenced by initialize(), match(), and SigmaGenerator().
N_m
unsigned int SigmaGenerator::N_m private
Number of integration steps for closed orbit computation.
Definition at line 180 of file SigmaGenerator.h.
Referenced by match().
nh_m
double SigmaGenerator::nh_m private
Harmonic number, \(\left[N_{h}\right] = 1 \).
Definition at line 164 of file SigmaGenerator.h.
Referenced by initialize(), and SigmaGenerator().
niterations_m
unsigned int SigmaGenerator::niterations_m private
Is the number of iterations needed for convergence.
Definition at line 172 of file SigmaGenerator.h.
Referenced by getIterations(), match(), and updateSigma().
nSectors_m
unsigned int SigmaGenerator::nSectors_m private
Number of (symmetric) sectors the field is averaged over.
Definition at line 182 of file SigmaGenerator.h.
Referenced by match().
nSteps_m
unsigned int SigmaGenerator::nSteps_m private
Number of integration steps in total.
Definition at line 187 of file SigmaGenerator.h.
Referenced by initialize(), match(), and updateSigma().
nStepsPerSector_m
unsigned int SigmaGenerator::nStepsPerSector_m private
Number of integration steps per sector (–> also: number of maps per sector)
Definition at line 184 of file SigmaGenerator.h.
Referenced by match().
prinit_m
double SigmaGenerator::prinit_m private
Definition at line 214 of file SigmaGenerator.h.
Referenced by getInjectionMomentum(), and match().
px_m
Series SigmaGenerator::px_m private
Definition at line 211 of file SigmaGenerator.h.
Referenced by SigmaGenerator().
pz_m
Series SigmaGenerator::pz_m private
Definition at line 211 of file SigmaGenerator.h.
Referenced by SigmaGenerator().
q_m
double SigmaGenerator::q_m private
Is the particle charge [e].
Definition at line 170 of file SigmaGenerator.h.
Referenced by initialize(), match(), and SigmaGenerator().
rdm_m
RealDiracMatrix SigmaGenerator::rdm_m private
RealDiracMatrix-class member used for decoupling
Definition at line 274 of file SigmaGenerator.h.
Referenced by decouple().
rinit_m
double SigmaGenerator::rinit_m private
Definition at line 213 of file SigmaGenerator.h.
Referenced by getInjectionRadius(), and match().
sigma_m
matrix_t SigmaGenerator::sigma_m private
Stores the stationary distribution (sigma matrix)
Definition at line 199 of file SigmaGenerator.h.
Referenced by getSigma(), and match().
sigmas_m
std::vector<matrix_t> SigmaGenerator::sigmas_m private
Vector storing the second moment matrix for each angle.
Definition at line 202 of file SigmaGenerator.h.
Referenced by initialize(), match(), and updateSigma().
truncOrder_m
unsigned int SigmaGenerator::truncOrder_m private
Truncation order of the power series for the Hamiltonian (cyclotron and space charge)
Definition at line 193 of file SigmaGenerator.h.
Referenced by match(), and SigmaGenerator().
wo_m
double SigmaGenerator::wo_m private
Is the orbital frequency, \(\left[\omega_{o}\right] = \frac{1}{s} \).
Definition at line 154 of file SigmaGenerator.h.
Referenced by initialize(), and SigmaGenerator().
write_m
bool SigmaGenerator::write_m private
Decides for writing output (default: true)
Definition at line 196 of file SigmaGenerator.h.
Referenced by initialize(), match(), updateInitialSigma(), updateSigma(), writeMatrix(), and writeOrbitOutput_m().
x_m
Series SigmaGenerator::x_m private
All variables x, px, z, pz, l, delta.
Definition at line 211 of file SigmaGenerator.h.
Referenced by SigmaGenerator().
z_m
Series SigmaGenerator::z_m private
Definition at line 211 of file SigmaGenerator.h.
Referenced by SigmaGenerator().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Distribution/SigmaGenerator.h
/psi/home/gsell/data/src/OPAL/src/src/Distribution/SigmaGenerator.cpp