OPAL (Object Oriented Parallel Accelerator Library): RBend3D Class Reference
RBend3D Class Reference
Interface for solenoids.
#include <RBend3D.h>
Public Member Functions
RBend3D (const std::string &name)
Constructor with given name.
RBend3D ()
RBend3D (const RBend3D &)
virtual ~RBend3D ()
ElementBase * clone () const override
BGeometryBase & getGeometry () override
const BGeometryBase & getGeometry () const override
EMField & getField () override
const EMField & getField () const override
virtual void accept (BeamlineVisitor &) const override
Apply visitor to RBend3D.
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void finalise () override
virtual void goOnline (const double &kineticEnergy) override
virtual void goOffline () override
virtual ElementBase::ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
virtual bool isInside (const Vector_t &r) const override
MeshData getSurfaceMesh () const
virtual double getExitAngle () const override
Public Member Functions inherited from BendBase
BendBase ()
BendBase (const BendBase &)
BendBase (const std::string &)
virtual bool bends () const
Indicates that element bends the beam.
double getChordLength () const
virtual void setBendAngle (double angle)
double getBendAngle () const
virtual void setEntranceAngle (double entranceAngle)
double getEntranceAngle () const
void setFullGap (double)
double getFullGap () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
double getDesignEnergy () const
std::vector< Vector_t > getDesignPath () const
void setFieldAmplitude (double k0, double k0s)
double getFieldAmplitude () const
void setFieldMapFN (std::string fileName)
std::string getFieldMapFN () const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual bool Online ()
virtual void setComponentType (std::string)
virtual std::string getComponentType () const
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
double trackRefParticleThrough (double dt, bool print=false)
void operator= (const RBend3D &)
Private Attributes
double fieldAmplitudeError_m
double startField_m
double lengthField_m
StraightGeometry geometry_m
BMultipoleField dummyField_m
Additional Inherited Members
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from BendBase
double calcDesignRadius (double fieldAmplitude) const
Calculate design radius from design energy and field amplitude.
double calcFieldAmplitude (double radius) const
Calculate field amplitude from design energy and radius.
double calcBendAngle (double chordLength, double radius) const
Calculate bend angle from chord length and design radius.
double calcDesignRadius (double chordLength, double angle) const
Calculate design radius from chord length and bend angle.
double calcGamma () const
Calculate gamma from design energy.
double calcBetaGamma () const
Calculate beta*gamma from design energy.
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from BendBase
double chordLength_m
double angle_m
Bend angle.
double entranceAngle_m
Fieldmap * fieldmap_m
Magnet field map.
const bool fast_m = false
Flag to turn on fast field calculation.
double gap_m
Full vertical gap of the magnets.
double designEnergy_m
Bend design energy (eV).
bool designEnergyChangeable_m
std::vector< Vector_t > refTrajMap_m
Map of reference particle trajectory.
double fieldAmplitudeX_m
double fieldAmplitudeY_m
double fieldAmplitude_m
Field amplitude.
std::string fileName_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Interface for solenoids.
Definition at line 39 of file RBend3D.h.
Constructor & Destructor Documentation
RBend3D() [1/3]
RBend3D::RBend3D (const std::string & name) explicit
Constructor with given name.
Definition at line 51 of file RBend3D.cpp.
RBend3D() [2/3]
RBend3D::RBend3D ()
Definition at line 36 of file RBend3D.cpp.
Referenced by clone().
RBend3D() [3/3]
RBend3D::RBend3D (const RBend3D & right)
Definition at line 41 of file RBend3D.cpp.
~RBend3D()
RBend3D::~RBend3D () virtual
Definition at line 61 of file RBend3D.cpp.
Member Function Documentation
accept()
void RBend3D::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to RBend3D.
Implements ElementBase.
Definition at line 64 of file RBend3D.cpp.
References BeamlineVisitor::visitRBend3D().
apply() [1/2]
bool RBend3D::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 68 of file RBend3D.cpp.
References PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::R, and Component::RefPartBunch_m.
apply() [2/2]
bool RBend3D::apply (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 72 of file RBend3D.cpp.
References BendBase::fieldAmplitude_m, fieldAmplitudeError_m, BendBase::fieldmap_m, Fieldmap::getFieldstrength(), Attrib::Distribution::R, and startField_m.
applyToReferenceParticle()
bool RBend3D::applyToReferenceParticle (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 83 of file RBend3D.cpp.
References BendBase::fieldAmplitude_m, BendBase::fieldmap_m, Fieldmap::getFieldstrength(), Attrib::Distribution::R, and startField_m.
Referenced by trackRefParticleThrough().
clone()
ElementBase * RBend3D::clone () const override virtual
Inheritable copy constructor
Implements ElementBase.
Definition at line 216 of file RBend3D.cpp.
References RBend3D().
finalise()
void RBend3D::finalise () override virtual
Implements Component.
Definition at line 188 of file RBend3D.cpp.
getDimensions()
void RBend3D::getDimensions (double & zBegin, double & zEnd) const override virtual
Implements Component.
Definition at line 201 of file RBend3D.cpp.
References ElementBase::getElementLength(), and startField_m.
getExitAngle()
double RBend3D::getExitAngle () const inline override virtual
Implements BendBase.
Definition at line 108 of file RBend3D.h.
References BendBase::getBendAngle(), and BendBase::getEntranceAngle().
getField() [1/2]
EMField & RBend3D::getField () override virtual
Return a dummy (0.) field value (what is this for?)
Implements Component.
Definition at line 228 of file RBend3D.cpp.
References dummyField_m.
getField() [2/2]
const EMField & RBend3D::getField () const override virtual
Return a dummy (0.) field value (what is this for?)
Implements Component.
Definition at line 232 of file RBend3D.cpp.
References dummyField_m.
getGeometry() [1/2]
BGeometryBase & RBend3D::getGeometry () override virtual
Return the cell geometry
Implements ElementBase.
Definition at line 220 of file RBend3D.cpp.
References geometry_m.
getGeometry() [2/2]
const BGeometryBase & RBend3D::getGeometry () const override virtual
Return the cell geometry
Implements ElementBase.
Definition at line 224 of file RBend3D.cpp.
References geometry_m.
getSurfaceMesh()
MeshData RBend3D::getSurfaceMesh () const
Definition at line 236 of file RBend3D.cpp.
References BendBase::fieldmap_m, Fieldmap::getFieldDimensions(), MeshData::triangles_m, and MeshData::vertices_m.
Referenced by MeshGenerator::add().
getType()
ElementBase::ElementType RBend3D::getType () const override virtual
Get element type std::string.
Reimplemented from Component.
Definition at line 207 of file RBend3D.cpp.
References ElementBase::RBEND3D.
goOffline()
void RBend3D::goOffline () override virtual
Reimplemented from Component.
Definition at line 196 of file RBend3D.cpp.
References BendBase::fileName_m, Fieldmap::freeMap(), and Component::online_m.
goOnline()
void RBend3D::goOnline (const double & kineticEnergy) override virtual
Reimplemented from Component.
Definition at line 191 of file RBend3D.cpp.
References BendBase::fileName_m, Component::online_m, and Fieldmap::readMap().
Referenced by initialise().
initialise()
void RBend3D::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Implements Component.
Definition at line 93 of file RBend3D.cpp.
References abs(), BendBase::angle_m, atan2(), BendBase::calcFieldAmplitude(), BendBase::chordLength_m, copysign(), BendBase::entranceAngle_m, BendBase::fast_m, BendBase::fieldAmplitude_m, BendBase::fieldAmplitudeX_m, BendBase::fieldAmplitudeY_m, BendBase::fieldmap_m, BendBase::fileName_m, PartBunchBase< T, Dim >::getdT(), ElementBase::getElementLength(), Fieldmap::getFieldDimensions(), Fieldmap::getFieldmap(), Fieldmap::getFieldstrength(), Fieldmap::getInfo(), ElementBase::getName(), PartBunchBase< T, Dim >::getQ(), gmsg, goOnline(), lengthField_m, level2(), Physics::pi, Component::RefPartBunch_m, ElementBase::rotationZAxis_m, ElementBase::setElementLength(), startField_m, trackRefParticleThrough(), and Options::writeBendTrajectories.
isInside()
bool RBend3D::isInside (const Vector_t & r) const override virtual
Reimplemented from ElementBase.
Definition at line 211 of file RBend3D.cpp.
References BendBase::fieldmap_m, Fieldmap::isInside(), and startField_m.
operator=()
void RBend3D::operator= (const RBend3D &) private
trackRefParticleThrough()
double RBend3D::trackRefParticleThrough (double dt, bool print = false) private
Definition at line 268 of file RBend3D.cpp.
References applyToReferenceParticle(), atan2(), Physics::c, BendBase::calcBetaGamma(), BendBase::calcGamma(), Util::combineFilePath(), cos(), endl(), BendBase::entranceAngle_m, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInputBasename(), OpalData::getInstance(), ElementBase::getName(), PartBunchBase< T, Dim >::getReference(), lengthField_m, IpplInfo::myNode(), Component::RefPartBunch_m, sin(), startField_m, tan(), and X.
Referenced by initialise().
Member Data Documentation
dummyField_m
BMultipoleField RBend3D::dummyField_m private
Definition at line 101 of file RBend3D.h.
Referenced by getField().
fieldAmplitudeError_m
double RBend3D::fieldAmplitudeError_m private
scale multiplier error
Definition at line 94 of file RBend3D.h.
Referenced by apply().
geometry_m
StraightGeometry RBend3D::geometry_m private
Definition at line 99 of file RBend3D.h.
Referenced by getGeometry().
lengthField_m
double RBend3D::lengthField_m private
Definition at line 97 of file RBend3D.h.
Referenced by initialise(), and trackRefParticleThrough().
startField_m
double RBend3D::startField_m private
startingpoint of field, m
Definition at line 96 of file RBend3D.h.
Referenced by apply(), applyToReferenceParticle(), getDimensions(), initialise(), isInside(), and trackRefParticleThrough().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/RBend3D.h
src/Classic/AbsBeamline/RBend3D.cpp