OPAL (Object Oriented Parallel Accelerator Library): VariableRFCavity Class Reference
VariableRFCavity Class Reference
#include <VariableRFCavity.h>
Public Member Functions
VariableRFCavity (const std::string &name)
Constructor with given name.
VariableRFCavity (const VariableRFCavity &)
VariableRFCavity ()
VariableRFCavity & operator= (const VariableRFCavity &)
virtual ~VariableRFCavity ()
virtual void accept (BeamlineVisitor &) const override
virtual ElementBase * clone () const override
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void finalise () override
virtual bool bends () const override
virtual void getDimensions (double &, double &) const override
virtual double getAmplitude (double time) const
virtual double getFrequency (double time) const
virtual double getPhase (double time) const
virtual double getHeight () const
virtual double getWidth () const
virtual double getLength () const
virtual void setHeight (double fullHeight)
virtual void setWidth (double fullWidth)
virtual void setLength (double length)
virtual std::shared_ptr< AbstractTimeDependence > getAmplitudeModel () const
virtual std::shared_ptr< AbstractTimeDependence > getPhaseModel () const
virtual std::shared_ptr< AbstractTimeDependence > getFrequencyModel () const
virtual void setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > time_dep)
virtual void setPhaseModel (std::shared_ptr< AbstractTimeDependence > time_dep)
virtual void setFrequencyModel (std::shared_ptr< AbstractTimeDependence > time_dep)
virtual void setAmplitudeName (const std::string &amplitude)
virtual void setPhaseName (const std::string &phase)
virtual void setFrequencyName (const std::string &frequency)
virtual StraightGeometry & getGeometry () override
virtual const StraightGeometry & getGeometry () const override
void initialise () const
virtual EMField & getField () override
Not implemented.
virtual const EMField & getField () const override
Not implemented.
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual ElementType getType () const override
Get element type std::string.
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Member Functions
void initNull ()
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes
std::shared_ptr< AbstractTimeDependence > phaseTD_m
std::shared_ptr< AbstractTimeDependence > amplitudeTD_m
std::shared_ptr< AbstractTimeDependence > frequencyTD_m
std::string phaseName_m
std::string amplitudeName_m
std::string frequencyName_m
double halfWidth_m
double halfHeight_m
double length_m
TimeDependenceCache frequencyCache_m
StraightGeometry geometry
The cavity's geometry.
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Generates a field like E = a(t) * sin{2*pi * integral(f(tau),0,t) + q(t)} B = 0 where E0, B0 are user defined fields, a(t), f(t), q(t) are time dependent amplitude, frequency, phase respectively; it is assumed that these quantities vary sufficiently slowly that Maxwell is satisfied.
The time dependent quantities are
Definition at line 40 of file VariableRFCavity.h.
Constructor & Destructor Documentation
VariableRFCavity() [1/3]
VariableRFCavity::VariableRFCavity (const std::string & name) explicit
Constructor with given name.
Definition at line 30 of file VariableRFCavity.cpp.
References initNull().
VariableRFCavity() [2/3]
VariableRFCavity::VariableRFCavity (const VariableRFCavity & var)
Copy Constructor; performs deepcopy on time-dependence models
Definition at line 38 of file VariableRFCavity.cpp.
References initNull().
VariableRFCavity() [3/3]
VariableRFCavity::VariableRFCavity ()
Default constructor
Definition at line 34 of file VariableRFCavity.cpp.
References initNull().
Referenced by clone().
~VariableRFCavity()
VariableRFCavity::~VariableRFCavity () virtual
Destructor does nothing
The shared_ptrs will self-destruct when reference count goes to 0
Definition at line 69 of file VariableRFCavity.cpp.
Member Function Documentation
accept()
void VariableRFCavity::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to RFCavity.
The RF cavity finds the "time dependence" models by doing a string lookup against a list held by AbstractTimeDependence at accept time.
Implements ElementBase.
Reimplemented in VariableRFCavityFringeField.
Definition at line 171 of file VariableRFCavity.cpp.
References initialise(), and BeamlineVisitor::visitVariableRFCavity().
apply() [1/2]
bool VariableRFCavity::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Calculate the field at the position of the i^th particle
Parameters
i indexes the particle whose field we need
t the time at which the field is calculated
E return value with electric field strength
B return value with magnetic field strength
Returns
True if particle is outside the boundaries; else False
Reimplemented from Component.
Reimplemented in VariableRFCavityFringeField.
Definition at line 127 of file VariableRFCavity.cpp.
References PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::R, and Component::RefPartBunch_m.
Referenced by applyToReferenceParticle().
apply() [2/2]
bool VariableRFCavity::apply (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Calculate the field at a given position
Parameters
R the position at which the field is calculated
P the momentum (not used)
t the time at which the field is calculated
E return value; filled with electric field strength
B return value; filled with magnetic field strength
Returns
True if particle is outside the boundaries; else False
Reimplemented from Component.
Reimplemented in VariableRFCavityFringeField.
Definition at line 138 of file VariableRFCavity.cpp.
References abs(), amplitudeTD_m, frequencyCache_m, TimeDependenceCache::getIntegral(), halfHeight_m, halfWidth_m, length_m, Units::MHz2Hz, phaseTD_m, Attrib::Distribution::R, sin(), and Physics::two_pi.
applyToReferenceParticle()
bool VariableRFCavity::applyToReferenceParticle (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Calculate the field at a given position. This is identical to "apply".
Parameters
R the position at which the field is calculated
P the momentum (not used)
t the time at which the field is calculated
E return value; filled with electric field strength
B return value; filled with magnetic field strength
Returns
True if particle is outside the boundaries; else False
Reimplemented from Component.
Reimplemented in VariableRFCavityFringeField.
Definition at line 153 of file VariableRFCavity.cpp.
References apply(), and Attrib::Distribution::R.
bends()
virtual bool VariableRFCavity::bends () const inline override virtual
Returns
false (cavity does not bend the trajectory)
Implements Component.
Definition at line 119 of file VariableRFCavity.h.
clone()
ElementBase * VariableRFCavity::clone () const override virtual
Inheritable deepcopy method
Implements ElementBase.
Reimplemented in VariableRFCavityFringeField.
Definition at line 167 of file VariableRFCavity.cpp.
References VariableRFCavity().
finalise()
void VariableRFCavity::finalise () override virtual
Finalise following tracking
Just sets RefPartBunch_m to nullptr
Implements Component.
Definition at line 163 of file VariableRFCavity.cpp.
References Component::RefPartBunch_m.
getAmplitude()
double VariableRFCavity::getAmplitude (double time) const inline virtual
Get the amplitude at a given time
Parameters
time the time at which the amplitude is calculated
Returns
the RF field gradient.
Definition at line 229 of file VariableRFCavity.h.
References amplitudeTD_m.
getAmplitudeModel()
std::shared_ptr< AbstractTimeDependence > VariableRFCavity::getAmplitudeModel () const virtual
Returns
shared_ptr to the amplitude (field gradient) time dependence
Definition at line 83 of file VariableRFCavity.cpp.
References amplitudeTD_m.
getDimensions()
virtual void VariableRFCavity::getDimensions (double & , double &) const inline override virtual
Not used (does nothing)
Implements Component.
Definition at line 122 of file VariableRFCavity.h.
getField() [1/2]
EMField & VariableRFCavity::getField () override virtual
Not implemented.
Implements Component.
Definition at line 116 of file VariableRFCavity.cpp.
getField() [2/2]
const EMField & VariableRFCavity::getField () const override virtual
Not implemented.
Implements Component.
Definition at line 121 of file VariableRFCavity.cpp.
getFrequency()
double VariableRFCavity::getFrequency (double time) const inline virtual
Get the frequency at a given time
Parameters
time the time at which the frequency is calculated
Returns
the RF cavity frequency.
Definition at line 237 of file VariableRFCavity.h.
References frequencyTD_m.
getFrequencyModel()
std::shared_ptr< AbstractTimeDependence > VariableRFCavity::getFrequencyModel () const virtual
Returns
shared_ptr to the frequency
Definition at line 91 of file VariableRFCavity.cpp.
References frequencyTD_m.
getGeometry() [1/2]
StraightGeometry & VariableRFCavity::getGeometry () override virtual
Set the cavity geometry
Implements ElementBase.
Definition at line 108 of file VariableRFCavity.cpp.
References geometry.
getGeometry() [2/2]
const StraightGeometry & VariableRFCavity::getGeometry () const override virtual
Returns
the cavity geometry
Implements ElementBase.
Definition at line 112 of file VariableRFCavity.cpp.
References geometry.
getHeight()
double VariableRFCavity::getHeight () const inline virtual
Returns
the full height of the cavity
Definition at line 241 of file VariableRFCavity.h.
References halfHeight_m.
getLength()
double VariableRFCavity::getLength () const inline virtual
Returns
the length of the cavity
Definition at line 249 of file VariableRFCavity.h.
References length_m.
getPhase()
double VariableRFCavity::getPhase (double time) const inline virtual
Get the phase at a given time
Parameters
phase the time at which the phase is calculated
Returns
the RF cavity phase.
Definition at line 233 of file VariableRFCavity.h.
References phaseTD_m.
getPhaseModel()
std::shared_ptr< AbstractTimeDependence > VariableRFCavity::getPhaseModel () const virtual
Returns
shared_ptr to the phase time dependence
Definition at line 87 of file VariableRFCavity.cpp.
References phaseTD_m.
getWidth()
double VariableRFCavity::getWidth () const inline virtual
Returns
the full width of the cavity
Definition at line 245 of file VariableRFCavity.h.
References halfWidth_m.
initialise() [1/2]
void VariableRFCavity::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Initialise ready for tracking
Just sets RefPartBunch_m
Implements Component.
Reimplemented in VariableRFCavityFringeField.
Definition at line 158 of file VariableRFCavity.cpp.
References Component::RefPartBunch_m.
Referenced by PyOpal::PyOpalObjectNS::PyOpalObject< C >::doSetup().
initialise() [2/2]
void VariableRFCavity::initialise () const
Lookup the time dependencies and update.
Throws if the named time dependencies can't be found. Also throws if the width or height is < 1 nm
Definition at line 176 of file VariableRFCavity.cpp.
References amplitudeName_m, Physics::e, frequencyName_m, AbstractTimeDependence::getTimeDependence(), halfHeight_m, halfWidth_m, phaseName_m, setAmplitudeModel(), setFrequencyModel(), and setPhaseModel().
Referenced by accept(), and VariableRFCavityFringeField::initialise().
initNull()
void VariableRFCavity::initNull () protected
Definition at line 73 of file VariableRFCavity.cpp.
References amplitudeName_m, frequencyName_m, halfHeight_m, halfWidth_m, length_m, phaseName_m, and Component::RefPartBunch_m.
Referenced by VariableRFCavityFringeField::initNull(), and VariableRFCavity().
operator=()
VariableRFCavity & VariableRFCavity::operator= (const VariableRFCavity & rhs)
Assignment operator; performs deepcopy on time-dependence models
Definition at line 43 of file VariableRFCavity.cpp.
References amplitudeName_m, amplitudeTD_m, frequencyName_m, frequencyTD_m, ElementBase::getName(), halfHeight_m, halfWidth_m, length_m, phaseName_m, phaseTD_m, setAmplitudeModel(), setFrequencyModel(), setLength(), ElementBase::setName(), and setPhaseModel().
Referenced by VariableRFCavityFringeField::operator=().
setAmplitudeModel()
void VariableRFCavity::setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > time_dep) virtual
Set the amplitude (field gradient) time dependence
Definition at line 95 of file VariableRFCavity.cpp.
References amplitudeTD_m.
Referenced by initialise(), and operator=().
setAmplitudeName()
virtual void VariableRFCavity::setAmplitudeName (const std::string & amplitude) inline virtual
Set the amplitude time dependence name
The name is used to find the amplitude model at accept time
Definition at line 179 of file VariableRFCavity.h.
References amplitudeName_m.
Referenced by OpalVariableRFCavity::update(), and OpalVariableRFCavityFringeField::update().
setFrequencyModel()
void VariableRFCavity::setFrequencyModel (std::shared_ptr< AbstractTimeDependence > time_dep) virtual
Set the frequency time dependence
Definition at line 103 of file VariableRFCavity.cpp.
References frequencyCache_m, frequencyTD_m, and TimeDependenceCache::setTimeDependence().
Referenced by initialise(), and operator=().
setFrequencyName()
virtual void VariableRFCavity::setFrequencyName (const std::string & frequency) inline virtual
Set the frequency time dependence name
The name is used to find the frequency model at accept time
Definition at line 191 of file VariableRFCavity.h.
References frequencyName_m.
Referenced by OpalVariableRFCavity::update(), and OpalVariableRFCavityFringeField::update().
setHeight()
void VariableRFCavity::setHeight (double fullHeight) inline virtual
Set the full height of the cavity
Definition at line 253 of file VariableRFCavity.h.
References halfHeight_m.
Referenced by OpalVariableRFCavity::update(), and OpalVariableRFCavityFringeField::update().
setLength()
void VariableRFCavity::setLength (double length) virtual
Set the length of the cavity
Definition at line 193 of file VariableRFCavity.cpp.
References geometry, length_m, and StraightGeometry::setElementLength().
Referenced by operator=(), OpalVariableRFCavity::update(), and OpalVariableRFCavityFringeField::update().
setPhaseModel()
void VariableRFCavity::setPhaseModel (std::shared_ptr< AbstractTimeDependence > time_dep) virtual
Set the phase time dependence
Definition at line 99 of file VariableRFCavity.cpp.
References phaseTD_m.
Referenced by initialise(), and operator=().
setPhaseName()
virtual void VariableRFCavity::setPhaseName (const std::string & phase) inline virtual
Set the phase time dependence name
The name is used to find the phase model at accept time
Definition at line 185 of file VariableRFCavity.h.
References phaseName_m.
Referenced by OpalVariableRFCavity::update(), and OpalVariableRFCavityFringeField::update().
setWidth()
void VariableRFCavity::setWidth (double fullWidth) inline virtual
Set the full width of the cavity
Definition at line 257 of file VariableRFCavity.h.
References halfWidth_m.
Referenced by OpalVariableRFCavity::update(), and OpalVariableRFCavityFringeField::update().
Member Data Documentation
amplitudeName_m
std::string VariableRFCavity::amplitudeName_m protected
Definition at line 216 of file VariableRFCavity.h.
Referenced by initialise(), initNull(), operator=(), and setAmplitudeName().
amplitudeTD_m
std::shared_ptr<AbstractTimeDependence> VariableRFCavity::amplitudeTD_m protected
Definition at line 213 of file VariableRFCavity.h.
Referenced by apply(), VariableRFCavityFringeField::apply(), getAmplitude(), getAmplitudeModel(), operator=(), and setAmplitudeModel().
frequencyCache_m
TimeDependenceCache VariableRFCavity::frequencyCache_m protected
Definition at line 221 of file VariableRFCavity.h.
Referenced by apply(), and setFrequencyModel().
frequencyName_m
std::string VariableRFCavity::frequencyName_m protected
Definition at line 217 of file VariableRFCavity.h.
Referenced by initialise(), initNull(), operator=(), and setFrequencyName().
frequencyTD_m
std::shared_ptr<AbstractTimeDependence> VariableRFCavity::frequencyTD_m protected
Definition at line 214 of file VariableRFCavity.h.
Referenced by VariableRFCavityFringeField::apply(), getFrequency(), getFrequencyModel(), operator=(), and setFrequencyModel().
geometry
StraightGeometry VariableRFCavity::geometry protected
The cavity's geometry.
Definition at line 224 of file VariableRFCavity.h.
Referenced by getGeometry(), and setLength().
halfHeight_m
double VariableRFCavity::halfHeight_m protected
Definition at line 219 of file VariableRFCavity.h.
Referenced by apply(), VariableRFCavityFringeField::apply(), getHeight(), initialise(), initNull(), operator=(), and setHeight().
halfWidth_m
double VariableRFCavity::halfWidth_m protected
Definition at line 218 of file VariableRFCavity.h.
Referenced by apply(), VariableRFCavityFringeField::apply(), getWidth(), initialise(), initNull(), operator=(), and setWidth().
length_m
double VariableRFCavity::length_m protected
Definition at line 220 of file VariableRFCavity.h.
Referenced by apply(), VariableRFCavityFringeField::apply(), getLength(), initNull(), operator=(), and setLength().
phaseName_m
std::string VariableRFCavity::phaseName_m protected
Definition at line 215 of file VariableRFCavity.h.
Referenced by initialise(), initNull(), operator=(), and setPhaseName().
phaseTD_m
std::shared_ptr<AbstractTimeDependence> VariableRFCavity::phaseTD_m protected
Definition at line 212 of file VariableRFCavity.h.
Referenced by apply(), VariableRFCavityFringeField::apply(), getPhase(), getPhaseModel(), operator=(), and setPhaseModel().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/AbsBeamline/VariableRFCavity.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/AbsBeamline/VariableRFCavity.cpp