OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Index/SIndex.h File Reference
SIndex.h File Reference
#include "Index/NDIndex.h"
#include "Index/SOffset.h"
#include "Index/LSIndex.h"
#include "FieldLayout/FieldLayoutUser.h"
#include "Utility/Inform.h"
#include <memory>
#include <vector>
#include <iostream>
#include "Index/SIndex.hpp"
Classes
class FieldLayout< Dim >
class SIndex< Dim >
class IndexedSIndex< Dim, Brackets >
class SIndex< Dim >
Functions
template<unsigned Dim>
std::ostream & operator<< (std::ostream &, const SIndex< Dim > &)
Function Documentation
operator<<()
template<unsigned Dim> std::ostream& operator<< (std::ostream & , const SIndex< Dim > &)
Definition at line 741 of file SIndex.hpp.
References a, SIndex< Dim >::begin_iv(), SIndex< Dim >::end_iv(), endl(), SIndex< Dim >::getDomain(), SIndex< Dim >::getOffset(), and SIndex< Dim >::size_iv().