OPAL (Object Oriented Parallel Accelerator Library): IpplMessageCounterRegion Class Reference
IpplMessageCounterRegion Class Reference
#include <IpplMessageCounter.h>
Public Member Functions
IpplMessageCounterRegion (const std::string &)
void begin ()
void end ()
void registerMessage (int)
void print (Inform &)
Private Attributes
std::string name
unsigned count
unsigned total_size
int index
Detailed Description
Definition at line 24 of file IpplMessageCounter.h.
Constructor & Destructor Documentation
IpplMessageCounterRegion()
IpplMessageCounterRegion::IpplMessageCounterRegion (const std::string & n)
Definition at line 39 of file IpplMessageCounter.cpp.
References IpplMessageCounter::addRegion(), IpplMessageCounter::getInstance(), and index.
Member Function Documentation
begin()
void IpplMessageCounterRegion::begin ()
Definition at line 45 of file IpplMessageCounter.cpp.
References IpplMessageCounter::getInstance(), index, and IpplMessageCounter::setActiveRegion().
Referenced by ParticleSpatialLayout< T, Dim, Mesh >::update().
end()
void IpplMessageCounterRegion::end ()
Definition at line 50 of file IpplMessageCounter.cpp.
References IpplMessageCounter::getInstance(), and IpplMessageCounter::unsetActiveRegion().
Referenced by ParticleSpatialLayout< T, Dim, Mesh >::update().
print()
void IpplMessageCounterRegion::print (Inform & msg)
Definition at line 74 of file IpplMessageCounter.cpp.
References count, endl(), name, reduce(), and total_size.
registerMessage()
void IpplMessageCounterRegion::registerMessage (int size)
Definition at line 55 of file IpplMessageCounter.cpp.
References count, and total_size.
Referenced by IpplMessageCounter::registerMessage().
Member Data Documentation
count
unsigned IpplMessageCounterRegion::count private
Definition at line 33 of file IpplMessageCounter.h.
Referenced by print(), and registerMessage().
index
int IpplMessageCounterRegion::index private
Definition at line 35 of file IpplMessageCounter.h.
Referenced by begin(), and IpplMessageCounterRegion().
name
std::string IpplMessageCounterRegion::name private
Definition at line 32 of file IpplMessageCounter.h.
Referenced by print().
total_size
unsigned IpplMessageCounterRegion::total_size private
Definition at line 34 of file IpplMessageCounter.h.
Referenced by print(), and registerMessage().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/IpplMessageCounter.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/IpplMessageCounter.cpp