OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/SubParticle/SubParticleAssign.h File Reference
SubParticleAssign.h File Reference
#include "Field/Assign.h"
#include "SubParticle/SubParticleAttrib.h"
#include "SubParticle/SubParticleAssign.hpp"
Macros
#define SUBPARTICLE_ASSIGNMENT_OPERATORS(FUNC, OP)
Functions
template<class PA , class T , unsigned Dim, class RHS , class OP >
void assign (SubParticleAttrib< PA, T, Dim > a, RHS b, OP op, ExprTag< true >)
template<class PA , class T , unsigned Dim, class OP >
void assign (SubParticleAttrib< PA, T, Dim > a, const T &b, OP op, ExprTag< true >)
template<class PA , class T , unsigned Dim>
void assign (const SubParticleAttrib< PA, T, Dim > &lhs, const T &rhs)
template<class PA , class T , unsigned Dim>
void operator<< (const SubParticleAttrib< PA, T, Dim > &lhs, const T &rhs)
template<class PA , class T , unsigned Dim>
void operator+= (const SubParticleAttrib< PA, T, Dim > &lhs, const T &rhs)
template<class PA , class T , unsigned Dim>
void operator-= (const SubParticleAttrib< PA, T, Dim > &lhs, const T &rhs)
template<class PA , class T , unsigned Dim>
void operator*= (const SubParticleAttrib< PA, T, Dim > &lhs, const T &rhs)
template<class PA , class T , unsigned Dim>
void operator/= (const SubParticleAttrib< PA, T, Dim > &lhs, const T &rhs)
template<class PA , class T , unsigned Dim>
void mineq (const SubParticleAttrib< PA, T, Dim > &lhs, const T &rhs)
template<class PA , class T , unsigned Dim>
void maxeq (const SubParticleAttrib< PA, T, Dim > &lhs, const T &rhs)
Macro Definition Documentation
SUBPARTICLE_ASSIGNMENT_OPERATORS
#define SUBPARTICLE_ASSIGNMENT_OPERATORS (FUNC, OP)
Value:
\
template<class PA, class T, unsigned Dim>                       \
inline void                                                     \
FUNC(const SubParticleAttrib<PA,T,Dim>& lhs, const T& rhs)      \
{                                                               \
  assign(lhs, PETE_Scalar<T>(rhs), OP(), ExprTag<true>());      \
}
Definition at line 59 of file SubParticleAssign.h.
Function Documentation
assign() [1/3]
template<class PA , class T , unsigned Dim, class RHS , class OP > void assign (SubParticleAttrib< PA, T, Dim > a, RHS b, OP op, ExprTag< true >)
Definition at line 54 of file SubParticleAssign.hpp.
References a, IpplInfo::abort(), BrickExpression< Dim, LHS, RHS, OP >::apply(), endl(), ERRORMSG, FillGCIfNecessary(), for_each(), SubParticleAttribIter< PA, T, Dim >::getLFieldIter(), INCIPPLSTAT, SubParticleAttribIter< PA, T, Dim >::initialize(), SubParticleAttribIter< PA, T, Dim >::nextLField(), and PInsist.
Referenced by assign().
assign() [2/3]
template<class PA , class T , unsigned Dim, class OP > void assign (SubParticleAttrib< PA, T, Dim > a, const T & b, OP op, ExprTag< true >) inline
Definition at line 52 of file SubParticleAssign.h.
References a, and assign().
assign() [3/3]
template<class PA , class T , unsigned Dim> void assign (const SubParticleAttrib< PA, T, Dim > & lhs, const T & rhs) inline
Definition at line 69 of file SubParticleAssign.h.
maxeq()
template<class PA , class T , unsigned Dim> void maxeq (const SubParticleAttrib< PA, T, Dim > & lhs, const T & rhs) inline
Definition at line 76 of file SubParticleAssign.h.
mineq()
template<class PA , class T , unsigned Dim> void mineq (const SubParticleAttrib< PA, T, Dim > & lhs, const T & rhs) inline
Definition at line 75 of file SubParticleAssign.h.
operator*=()
template<class PA , class T , unsigned Dim> void operator*= (const SubParticleAttrib< PA, T, Dim > & lhs, const T & rhs) inline
Definition at line 73 of file SubParticleAssign.h.
operator+=()
template<class PA , class T , unsigned Dim> void operator+= (const SubParticleAttrib< PA, T, Dim > & lhs, const T & rhs) inline
Definition at line 71 of file SubParticleAssign.h.
operator-=()
template<class PA , class T , unsigned Dim> void operator-= (const SubParticleAttrib< PA, T, Dim > & lhs, const T & rhs) inline
Definition at line 72 of file SubParticleAssign.h.
operator/=()
template<class PA , class T , unsigned Dim> void operator/= (const SubParticleAttrib< PA, T, Dim > & lhs, const T & rhs) inline
Definition at line 74 of file SubParticleAssign.h.
operator<<()
template<class PA , class T , unsigned Dim> void operator<< (const SubParticleAttrib< PA, T, Dim > & lhs, const T & rhs) inline
Definition at line 70 of file SubParticleAssign.h.