OPAL (Object Oriented Parallel Accelerator Library): ComponentFunctionFace< T, D, M, C > Class Template Reference
ComponentFunctionFace< T, D, M, C > Class Template Reference
#include <BCond.h>
Public Types
typedef BCondBase< T, D, M, C > BCondBaseTDMC
Public Member Functions
ComponentFunctionFace (typename ApplyToComponentType< T >::type(*func)(typename ApplyToComponentType< T >::type), unsigned face, int i=BCondBaseTDMC::allComponents, int j=BCondBaseTDMC::allComponents)
void apply (Field< T, D, M, C > &)
BCondBase< T, D, M, C > * clone () const
virtual void write (std::ostream &out) const
Public Member Functions inherited from BCondBase< T, D, M, C >
BCondBase (unsigned int face, int i=allComponents, int j=allComponents)
virtual ~BCondBase ()
int getComponent () const
unsigned int getFace () const
bool changesPhysicalCells () const
Public Member Functions inherited from RefCounted
RefCounted ()
Public Attributes
ApplyToComponentType< T >::type(* Func)(typename ApplyToComponentType< T >::type)
Public Attributes inherited from RefCounted
int RefCount
Additional Inherited Members
Static Public Attributes inherited from BCondBase< T, D, M, C >
static int allComponents = -9999
Protected Attributes inherited from BCondBase< T, D, M, C >
int m_component
unsigned int m_face
bool m_changePhysical
Detailed Description
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering>
class ComponentFunctionFace< T, D, M, C >
Definition at line 645 of file BCond.h.
Member Typedef Documentation
BCondBaseTDMC
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering> typedef BCondBase<T,D,M,C> ComponentFunctionFace< T, D, M, C >::BCondBaseTDMC
Definition at line 663 of file BCond.h.
Constructor & Destructor Documentation
ComponentFunctionFace()
template<class T , unsigned D, class M , class C > ComponentFunctionFace< T, D, M, C >::ComponentFunctionFace (typename ApplyToComponentType< T >::type(*)(typename ApplyToComponentType< T >::type) func, unsigned face, int i = BCondBaseTDMC::allComponents, int j = BCondBaseTDMC::allComponents)
Definition at line 327 of file BCond.hpp.
References endl(), and ERRORMSG.
Member Function Documentation
apply()
template<class T , unsigned D, class M , class C > void ComponentFunctionFace< T, D, M, C >::apply (Field< T, D, M, C > & A) virtual
Implements BCondBase< T, D, M, C >.
Definition at line 4993 of file BCond.hpp.
References ComponentFunctionFaceBCApply().
clone()
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering> BCondBase<T,D,M,C>* ComponentFunctionFace< T, D, M, C >::clone () const inline virtual
Implements BCondBase< T, D, M, C >.
Definition at line 672 of file BCond.h.
write()
template<class T , unsigned int D, class M , class C > void ComponentFunctionFace< T, D, M, C >::write (std::ostream & out) const virtual
Reimplemented from BCondBase< T, D, M, C >.
Definition at line 190 of file BCond.hpp.
Member Data Documentation
Func
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering> ApplyToComponentType<T>::type(* ComponentFunctionFace< T, D, M, C >::Func) (typename ApplyToComponentType< T >::type)
Definition at line 682 of file BCond.h.
Referenced by ComponentFunctionFaceBCApply().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BCond.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BCond.hpp