OPAL (Object Oriented Parallel Accelerator Library): Degrader Class Reference
Degrader Class Reference
#include <Degrader.h>
Public Types
enum Plane { OFF, X, Y, XY }
Plane selection.
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Public Member Functions
Degrader (const std::string &name)
Constructor with given name.
Degrader ()
Degrader (const Degrader &rhs)
virtual ~Degrader ()
virtual void accept (BeamlineVisitor &) const
Apply visitor to Degrader.
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B)
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField)
virtual void initialise (PartBunchBase< double, 3 > *bunch)
virtual void finalise ()
virtual bool bends () const
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual ElementBase::ElementType getType () const
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const
std::string getDegraderShape ()
virtual bool isInMaterial (double z)
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
virtual EMField & getField ()=0
Return field.
virtual const EMField & getField () const =0
Return field.
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual bool Online ()
virtual void setComponentType (std::string)
virtual std::string getComponentType () const
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void operator= (const Degrader &)
Private Attributes
std::vector< double > PosX_m
std::vector< double > PosY_m
std::vector< double > PosZ_m
std::vector< double > MomentumX_m
std::vector< double > MomentumY_m
std::vector< double > MomentumZ_m
std::vector< double > time_m
std::vector< int > id_m
std::unique_ptr< LossDataSink > lossDs_m
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 30 of file Degrader.h.
Member Enumeration Documentation
Plane
enum Degrader::Plane
Plane selection.
Enumerator
OFF
Monitor is off (inactive).
X
Monitor acts on x-plane.
Y
Monitor acts on y-plane.
XY
Monitor acts on both planes.
Definition at line 35 of file Degrader.h.
Constructor & Destructor Documentation
Degrader() [1/3]
Degrader::Degrader (const std::string & name) explicit
Constructor with given name.
Definition at line 49 of file Degrader.cpp.
Degrader() [2/3]
Degrader::Degrader ()
Definition at line 33 of file Degrader.cpp.
Degrader() [3/3]
Degrader::Degrader (const Degrader & rhs)
Definition at line 37 of file Degrader.cpp.
~Degrader()
Degrader::~Degrader () virtual
Definition at line 54 of file Degrader.cpp.
References goOffline(), and Component::online_m.
Member Function Documentation
accept()
void Degrader::accept (BeamlineVisitor & visitor) const virtual
Apply visitor to Degrader.
Implements ElementBase.
Definition at line 60 of file Degrader.cpp.
References BeamlineVisitor::visitDegrader().
apply()
bool Degrader::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) virtual
Reimplemented from Component.
Definition at line 73 of file Degrader.cpp.
References PartBunchBase< T, Dim >::Bin, Physics::c, dot(), PartBunchBase< T, Dim >::dt, PartBunchBase< T, Dim >::ID, id_m, isInMaterial(), MomentumX_m, MomentumY_m, MomentumZ_m, PartBunchBase< T, Dim >::P, PosX_m, PosY_m, PosZ_m, Attrib::Distribution::R, PartBunchBase< T, Dim >::R, Component::RefPartBunch_m, sqrt(), and time_m.
applyToReferenceParticle()
bool Degrader::applyToReferenceParticle (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) virtual
Reimplemented from Component.
Definition at line 101 of file Degrader.cpp.
References Physics::c, ParticleMatterInteractionHandler::computeEnergyLoss(), euclidean_norm(), PartBunchBase< T, Dim >::getdT(), PartBunchBase< T, Dim >::getM(), ElementBase::getParticleMatterInteraction(), PartBunchBase< T, Dim >::getQ(), isInMaterial(), Attrib::Distribution::R, and Component::RefPartBunch_m.
bends()
bool Degrader::bends () const virtual
Implements Component.
Definition at line 153 of file Degrader.cpp.
finalise()
void Degrader::finalise () virtual
Implements Component.
Definition at line 126 of file Degrader.cpp.
References endl(), and gmsg.
getDegraderShape()
std::string Degrader::getDegraderShape ()
Definition at line 166 of file Degrader.cpp.
getDimensions()
void Degrader::getDimensions (double & zBegin, double & zEnd) const virtual
Implements Component.
Definition at line 157 of file Degrader.cpp.
References ElementBase::getElementLength().
getType()
ElementBase::ElementType Degrader::getType () const virtual
Get element type std::string.
Reimplemented from Component.
Definition at line 162 of file Degrader.cpp.
References ElementBase::DEGRADER.
goOffline()
void Degrader::goOffline () virtual
Reimplemented from Component.
Definition at line 146 of file Degrader.cpp.
References endl(), lossDs_m, and Component::online_m.
Referenced by ~Degrader().
goOnline()
void Degrader::goOnline (const double & kineticEnergy) virtual
Reimplemented from Component.
Definition at line 130 of file Degrader.cpp.
References PartBunchBase< T, Dim >::getLocalNum(), id_m, MomentumX_m, MomentumY_m, MomentumZ_m, Component::online_m, PosX_m, PosY_m, PosZ_m, Component::RefPartBunch_m, and time_m.
initialise() [1/2]
void Degrader::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) virtual
Implements Component.
Definition at line 116 of file Degrader.cpp.
References ElementBase::getElementLength().
initialise() [2/2]
void Degrader::initialise (PartBunchBase< double, 3 > * bunch) virtual
Definition at line 121 of file Degrader.cpp.
References Options::asciidump, ElementBase::getOutputFN(), lossDs_m, and Component::RefPartBunch_m.
isInMaterial()
bool Degrader::isInMaterial (double z) inline virtual
check if the particle is in the degarder material
Definition at line 65 of file Degrader.cpp.
References ElementBase::getElementLength().
Referenced by apply(), and applyToReferenceParticle().
operator=()
void Degrader::operator= (const Degrader &) private
Member Data Documentation
id_m
std::vector<int> Degrader::id_m private
Definition at line 96 of file Degrader.h.
Referenced by apply(), and goOnline().
lossDs_m
std::unique_ptr<LossDataSink> Degrader::lossDs_m private
Definition at line 98 of file Degrader.h.
Referenced by goOffline(), and initialise().
MomentumX_m
std::vector<double> Degrader::MomentumX_m private
Definition at line 92 of file Degrader.h.
Referenced by apply(), and goOnline().
MomentumY_m
std::vector<double> Degrader::MomentumY_m private
Definition at line 93 of file Degrader.h.
Referenced by apply(), and goOnline().
MomentumZ_m
std::vector<double> Degrader::MomentumZ_m private
Definition at line 94 of file Degrader.h.
Referenced by apply(), and goOnline().
PosX_m
std::vector<double> Degrader::PosX_m private
Definition at line 89 of file Degrader.h.
Referenced by apply(), and goOnline().
PosY_m
std::vector<double> Degrader::PosY_m private
Definition at line 90 of file Degrader.h.
Referenced by apply(), and goOnline().
PosZ_m
std::vector<double> Degrader::PosZ_m private
Definition at line 91 of file Degrader.h.
Referenced by apply(), and goOnline().
time_m
std::vector<double> Degrader::time_m private
Definition at line 95 of file Degrader.h.
Referenced by apply(), and goOnline().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/Degrader.h
src/Classic/AbsBeamline/Degrader.cpp