OPAL (Object Oriented Parallel Accelerator Library): IntCICImpl< 3U > Class Template Reference
IntCICImpl< 3U > Class Template Reference
#include <IntCIC.h>
Public Member Functions
IntCICImpl ()
~IntCICImpl ()
Public Member Functions inherited from Interpolator
Interpolator ()
~Interpolator ()
Static Public Member Functions
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 3U, M, C > &f, const Vektor< PT, 3U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 3U, M, C > &f, const Vektor< PT, 3U > &ppos, const M &mesh, NDIndex< 3U > &ngp, int lgpoff[3U], Vektor< PT, 3U > &dpos)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 3U, M, C > &f, const NDIndex< 3U > &ngp, const int lgpoff[3U], const Vektor< PT, 3U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 3U, M, C > &f, const Vektor< PT, 3U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 3U, M, C > &f, const Vektor< PT, 3U > &ppos, const M &mesh, NDIndex< 3U > &ngp, int lgpoff[3U], Vektor< PT, 3U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 3U, M, C > &f, const NDIndex< 3U > &ngp, const int lgpoff[3U], const Vektor< PT, 3U > &dpos)
template<class FT , class M , class PT >
static void scatter (const Vektor< FT, 3U > &pdata, Field< Vektor< FT, 3U >, 3U, M, Edge > &f, const Vektor< PT, 3U > &ppos, const M &mesh)
template<class FT , class M , class PT >
static void scatter (const FT &, Field< FT, 3U, M, Edge > &, const Vektor< PT, 3U > &, const M &)
template<class FT , class M , class PT >
static void scatter (const FT &, Field< FT, 3U, M, Edge > &, const Vektor< PT, 3U > &, const M &, NDIndex< 3U > &, int [3U], Vektor< PT, 3U > &)
template<class FT , class M , class PT >
static void scatter (const FT &, Field< FT, 3U, M, Edge > &, const NDIndex< 3U > &, const int [3U], const Vektor< PT, 3U > &)
template<class FT , class M , class PT >
static void gather (Vektor< FT, 3U > &pdata, const Field< Vektor< FT, 3U >, 3U, M, Edge > &f, const Vektor< PT, 3U > &ppos, const M &mesh)
template<class FT , class M , class PT >
static void gather (FT &, const Field< FT, 3U, M, Edge > &, const Vektor< PT, 3U > &, const M &)
template<class FT , class M , class PT >
static void gather (FT &, const Field< FT, 3U, M, Edge > &, const Vektor< PT, 3U > &, const M &, NDIndex< 3U > &, int [3U], Vektor< PT, 3U > &)
template<class FT , class M , class PT >
static void gather (FT &, const Field< FT, 3U, M, Edge > &, const NDIndex< 3U > &, const int [3U], const Vektor< PT, 3U > &)
Additional Inherited Members
Static Protected Member Functions inherited from Interpolator
template<class T , unsigned Dim>
static CompressedBrickIterator< T, Dim > getFieldIter (const BareField< T, Dim > &f, const NDIndex< Dim > &pt)
Detailed Description
template<>
class IntCICImpl< 3U >
Definition at line 806 of file IntCIC.h.
Constructor & Destructor Documentation
IntCICImpl()
IntCICImpl< 3U >::IntCICImpl () inline
Definition at line 810 of file IntCIC.h.
~IntCICImpl()
IntCICImpl< 3U >::~IntCICImpl () inline
Definition at line 811 of file IntCIC.h.
Member Function Documentation
gather() [1/7]
template<class FT , class M , class C , class PT > static void IntCICImpl< 3U >::gather (FT & pdata, const Field< FT, 3U, M, C > & f, const Vektor< PT, 3U > & ppos, const M & mesh) inline static
Definition at line 935 of file IntCIC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
gather() [2/7]
template<class FT , class M , class C , class PT > static void IntCICImpl< 3U >::gather (FT & pdata, const Field< FT, 3U, M, C > & f, const Vektor< PT, 3U > & ppos, const M & mesh, NDIndex< 3U > & ngp, int lgpoff[3U], Vektor< PT, 3U > & dpos) inline static
Definition at line 983 of file IntCIC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
gather() [3/7]
template<class FT , class M , class C , class PT > static void IntCICImpl< 3U >::gather (FT & pdata, const Field< FT, 3U, M, C > & f, const NDIndex< 3U > & ngp, const int lgpoff[3U], const Vektor< PT, 3U > & dpos) inline static
Definition at line 1029 of file IntCIC.h.
References Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
gather() [4/7]
template<class FT , class M , class PT > static void IntCICImpl< 3U >::gather (Vektor< FT, 3U > & pdata, const Field< Vektor< FT, 3U >, 3U, M, Edge > & f, const Vektor< PT, 3U > & ppos, const M & mesh) inline static
Definition at line 1121 of file IntCIC.h.
References FindDelta(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
gather() [5/7]
template<class FT , class M , class PT > static void IntCICImpl< 3U >::gather (FT & , const Field< FT, 3U, M, Edge > & , const Vektor< PT, 3U > & , const M &) inline static
Definition at line 1161 of file IntCIC.h.
References endl(), and ERRORMSG.
gather() [6/7]
template<class FT , class M , class PT > static void IntCICImpl< 3U >::gather (FT & , const Field< FT, 3U, M, Edge > & , const Vektor< PT, 3U > & , const M & , NDIndex< 3U > & , int [3U], Vektor< PT, 3U > &) inline static
Definition at line 1171 of file IntCIC.h.
References endl(), and ERRORMSG.
gather() [7/7]
template<class FT , class M , class PT > static void IntCICImpl< 3U >::gather (FT & , const Field< FT, 3U, M, Edge > & , const NDIndex< 3U > & , const int [3U], const Vektor< PT, 3U > &) inline static
Definition at line 1181 of file IntCIC.h.
References endl(), and ERRORMSG.
scatter() [1/7]
template<class FT , class M , class C , class PT > static void IntCICImpl< 3U >::scatter (const FT & pdata, Field< FT, 3U, M, C > & f, const Vektor< PT, 3U > & ppos, const M & mesh) inline static
Definition at line 818 of file IntCIC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
scatter() [2/7]
template<class FT , class M , class C , class PT > static void IntCICImpl< 3U >::scatter (const FT & pdata, Field< FT, 3U, M, C > & f, const Vektor< PT, 3U > & ppos, const M & mesh, NDIndex< 3U > & ngp, int lgpoff[3U], Vektor< PT, 3U > & dpos) inline static
Definition at line 866 of file IntCIC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
scatter() [3/7]
template<class FT , class M , class C , class PT > static void IntCICImpl< 3U >::scatter (const FT & pdata, Field< FT, 3U, M, C > & f, const NDIndex< 3U > & ngp, const int lgpoff[3U], const Vektor< PT, 3U > & dpos) inline static
Definition at line 912 of file IntCIC.h.
References Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
scatter() [4/7]
template<class FT , class M , class PT > static void IntCICImpl< 3U >::scatter (const Vektor< FT, 3U > & pdata, Field< Vektor< FT, 3U >, 3U, M, Edge > & f, const Vektor< PT, 3U > & ppos, const M & mesh) inline static
Definition at line 1052 of file IntCIC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
scatter() [5/7]
template<class FT , class M , class PT > static void IntCICImpl< 3U >::scatter (const FT & , Field< FT, 3U, M, Edge > & , const Vektor< PT, 3U > & , const M &) inline static
Definition at line 1093 of file IntCIC.h.
References endl(), and ERRORMSG.
scatter() [6/7]
template<class FT , class M , class PT > static void IntCICImpl< 3U >::scatter (const FT & , Field< FT, 3U, M, Edge > & , const Vektor< PT, 3U > & , const M & , NDIndex< 3U > & , int [3U], Vektor< PT, 3U > &) inline static
Definition at line 1102 of file IntCIC.h.
References endl(), and ERRORMSG.
scatter() [7/7]
template<class FT , class M , class PT > static void IntCICImpl< 3U >::scatter (const FT & , Field< FT, 3U, M, Edge > & , const NDIndex< 3U > & , const int [3U], const Vektor< PT, 3U > &) inline static
Definition at line 1111 of file IntCIC.h.
References endl(), and ERRORMSG.
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/IntCIC.h