OPAL (Object Oriented Parallel Accelerator Library): cmp_ulp Namespace Reference
cmp_ulp Namespace Reference
Functions
bool almost_eq (double A, double B, double maxDiff=1e-20, int maxUlps=1000)
bool almost_eq_zero (double A, double maxDiff=1e-15)
bool eq (double x, double y)
bool eq_zero (double x)
bool le (double x, double y)
bool le_zero (double x)
bool lt (double x, double y)
bool lt_zero (double x)
bool ge (double x, double y)
bool ge_zero (double x)
bool gt (double x, double y)
bool gt_zero (double x)
Function Documentation
almost_eq()
bool cmp_ulp::almost_eq (double A, double B, double maxDiff = 1e-20, int maxUlps = 1000) inline
Definition at line 189 of file CmpFloat.h.
References abs(), and matheval::detail::math::isnan().
almost_eq_zero()
bool cmp_ulp::almost_eq_zero (double A, double maxDiff = 1e-15) inline
Definition at line 215 of file CmpFloat.h.
References abs().
eq()
bool cmp_ulp::eq (double x, double y) inline
Definition at line 218 of file CmpFloat.h.
eq_zero()
bool cmp_ulp::eq_zero (double x) inline
Definition at line 219 of file CmpFloat.h.
ge()
bool cmp_ulp::ge (double x, double y) inline
Definition at line 224 of file CmpFloat.h.
ge_zero()
bool cmp_ulp::ge_zero (double x) inline
Definition at line 225 of file CmpFloat.h.
gt()
bool cmp_ulp::gt (double x, double y) inline
Definition at line 226 of file CmpFloat.h.
gt_zero()
bool cmp_ulp::gt_zero (double x) inline
Definition at line 227 of file CmpFloat.h.
le()
bool cmp_ulp::le (double x, double y) inline
Definition at line 220 of file CmpFloat.h.
le_zero()
bool cmp_ulp::le_zero (double x) inline
Definition at line 221 of file CmpFloat.h.
lt()
bool cmp_ulp::lt (double x, double y) inline
Definition at line 222 of file CmpFloat.h.
lt_zero()
bool cmp_ulp::lt_zero (double x) inline
Definition at line 223 of file CmpFloat.h.