OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/SubParticle/SubParticleAssignDefs.h File Reference
SubParticleAssignDefs.h File Reference
#include "SubField/SubFieldAssignDefs.h"
#include "SubParticle/SubParticleAttrib.h"
Functions
template<class PA , class T , unsigned D, class C >
bool for_each (SubParticleAttribIter< PA, T, D > &, DomainCompressed, C)
template<class PA , class T , unsigned D, class C >
bool for_each (SubParticleAttribIter< PA, T, D > &p, SameSubsetType s, C)
template<class PA , class T , unsigned D, class C >
int for_each (SubParticleAttribIter< PA, T, D > &p, SubsetInit, C)
template<class PA , class T , unsigned D, class C >
int for_each (SubParticleAttribIter< PA, T, D > &p, SubsetNextLField, C)
template<class PA , class T , unsigned D, class C >
bool for_each (SubParticleAttribIter< PA, T, D > &, SameFieldID, C)
template<class PA , class T , unsigned D, class C >
bool for_each (SubParticleAttribIter< PA, T, D > &p, const PlugBase< D > &f, C)
template<class PA , class T , unsigned D, class C >
bool for_each (SubParticleAttribIter< PA, T, D > &, IsCompressed, C)
template<class PA , class T , unsigned D>
T & for_each (SubParticleAttribIter< PA, T, D > &p, const EvalFunctor_1 &e)
template<class PA , class T , unsigned D>
T & for_each (SubParticleAttribIter< PA, T, D > &p, const EvalFunctor_0 &)
template<class PA , class T , unsigned D, class C >
bool for_each (SubParticleAttribIter< PA, T, D > &, HasUnitStride, C)
template<class PA , class T , unsigned D, class C , class T1 >
int for_each (SubParticleAttribIter< PA, T, D > &, const FillGCIfNecessaryTag< D, T1 > &, C)
Function Documentation
for_each() [1/11]
template<class PA , class T , unsigned D, class C > bool for_each (SubParticleAttribIter< PA, T, D > & , DomainCompressed , C) inline
Definition at line 26 of file SubParticleAssignDefs.h.
for_each() [2/11]
template<class PA , class T , unsigned D, class C > bool for_each (SubParticleAttribIter< PA, T, D > & p, SameSubsetType s, C) inline
Definition at line 39 of file SubParticleAssignDefs.h.
References SameSubsetType::fID, and SubParticleAttribIter< PA, T, Dim >::matchType().
for_each() [3/11]
template<class PA , class T , unsigned D, class C > int for_each (SubParticleAttribIter< PA, T, D > & p, SubsetInit , C) inline
Definition at line 52 of file SubParticleAssignDefs.h.
References SubParticleAttribIter< PA, T, Dim >::initialize().
for_each() [4/11]
template<class PA , class T , unsigned D, class C > int for_each (SubParticleAttribIter< PA, T, D > & p, SubsetNextLField , C) inline
Definition at line 66 of file SubParticleAssignDefs.h.
References SubParticleAttribIter< PA, T, Dim >::nextLField().
for_each() [5/11]
template<class PA , class T , unsigned D, class C > bool for_each (SubParticleAttribIter< PA, T, D > & , SameFieldID , C) inline
Definition at line 80 of file SubParticleAssignDefs.h.
for_each() [6/11]
template<class PA , class T , unsigned D, class C > bool for_each (SubParticleAttribIter< PA, T, D > & p, const PlugBase< D > & f, C) inline
Definition at line 93 of file SubParticleAssignDefs.h.
References PlugBase< D >::Domain, and SubParticleAttribIter< PA, T, Dim >::plugBase().
for_each() [7/11]
template<class PA , class T , unsigned D, class C > bool for_each (SubParticleAttribIter< PA, T, D > & , IsCompressed , C) inline
Definition at line 100 of file SubParticleAssignDefs.h.
for_each() [8/11]
template<class PA , class T , unsigned D> T& for_each (SubParticleAttribIter< PA, T, D > & p, const EvalFunctor_1 & e) inline
Definition at line 117 of file SubParticleAssignDefs.h.
References Physics::e, and SubParticleAttribIter< PA, T, Dim >::offset().
for_each() [9/11]
template<class PA , class T , unsigned D> T& for_each (SubParticleAttribIter< PA, T, D > & p, const EvalFunctor_0 &) inline
Definition at line 124 of file SubParticleAssignDefs.h.
References IpplInfo::abort(), ERRORMSG, and SubParticleAttribIter< PA, T, Dim >::offset().
for_each() [10/11]
template<class PA , class T , unsigned D, class C > bool for_each (SubParticleAttribIter< PA, T, D > & , HasUnitStride , C) inline
Definition at line 142 of file SubParticleAssignDefs.h.
for_each() [11/11]
template<class PA , class T , unsigned D, class C , class T1 > int for_each (SubParticleAttribIter< PA, T, D > & , const FillGCIfNecessaryTag< D, T1 > & , C) inline
Definition at line 156 of file SubParticleAssignDefs.h.