OPAL (Object Oriented Parallel Accelerator Library): OpalVariableRFCavityFringeField Class Reference
OpalVariableRFCavityFringeField Class Reference
#include <OpalVariableRFCavityFringeField.h>
Public Types
enum {
PHASE_MODEL = COMMON, AMPLITUDE_MODEL, FREQUENCY_MODEL, WIDTH,
HEIGHT, CENTRE_LENGTH, END_LENGTH, CAVITY_CENTRE,
MAX_ORDER, SIZE
}
Public Types inherited from OpalElement
enum {
TYPE, APERT, LENGTH, ELEMEDGE,
WAKEF, PARTICLEMATTERINTERACTION, ORIGIN, ORIENTATION,
X, Y, Z, THETA,
PHI, PSI, DX, DY,
DZ, DTHETA, DPHI, DPSI,
OUTFN, COMMON
}
The common attributes for all elements.
Public Types inherited from Element
enum ReferenceType { IS_ENTRY, IS_CENTRE, IS_EXIT }
Reference for element positioning.
Public Member Functions
OpalVariableRFCavityFringeField (const std::string &name, OpalVariableRFCavityFringeField *parent)
OpalVariableRFCavityFringeField ()
OpalVariableRFCavityFringeField * clone ()
virtual OpalVariableRFCavityFringeField * clone (const std::string &name)
virtual ~OpalVariableRFCavityFringeField ()
virtual void update ()
Public Member Functions inherited from OpalElement
virtual ~OpalElement ()
virtual double getLength () const
Return element length.
const std::string getTypeName () const
Return the element's type name.
std::pair< ElementBase::ApertureType, std::vector< double > > getApert () const
const std::string getWakeF () const
Return the element's type name.
const std::string getParticleMatterInteraction () const
const std::string getWMaterial () const
const std::string getWakeGeom () const
std::vector< double > getWakeParam () const
const std::string getWakeConductivity () const
virtual void parse (Statement &)
Parse the element.
virtual void print (std::ostream &) const
Print the object.
virtual void updateUnknown (ElementBase *)
Transmit the `‘unknown’' (not known to OPAL) attributes to CLASSIC.
Public Member Functions inherited from Element
virtual ~Element ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual double getEntrance (ReferenceType) const
Return arc length from origin to entrance (negative !).
virtual double getExit (ReferenceType) const
Return arc length from origin to exit (positive !).
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded CLASSIC element.
void setElement (ElementBase *)
Assign new CLASSIC element.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
OpalVariableRFCavityFringeField (const OpalVariableRFCavityFringeField &)
void operator= (const OpalVariableRFCavityFringeField &)
Static Private Member Functions
static size_t convertToUnsigned (double value, std::string name)
Static Private Attributes
static const std::string doc_string
static constexpr double unsignedTolerance = 1e-9
Additional Inherited Members
Static Public Member Functions inherited from Element
static Element * find (const std::string &name)
Find named Element.
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from OpalElement
OpalElement (int size, const char *name, const char *help)
Exemplar constructor.
OpalElement (const std::string &name, OpalElement *parent)
Clone constructor.
void registerOwnership () const
Protected Member Functions inherited from Element
Element (int size, const char *name, const char *help)
Constructor for exemplars.
Element (const std::string &name, Element *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Static Protected Member Functions inherited from OpalElement
static void printMultipoleStrength (std::ostream &os, int order, int &len, const std::string &sName, const std::string &tName, const Attribute &length, const Attribute &vNorm, const Attribute &vSkew)
Print multipole components in OPAL-8 format.
static void printAttribute (std::ostream &os, const std::string &name, const std::string &image, int &len)
Print an attribute with a OPAL-8 name (as an expression).
static void printAttribute (std::ostream &os, const std::string &name, double value, int &len)
Print an attribute with a OPAL-8 name (as a constant).
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
OpalVariableRFCavityFringeField
Definition at line 35 of file OpalVariableRFCavityFringeField.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
enum maps string to integer value for UI definitions
Enumerator
PHASE_MODEL
AMPLITUDE_MODEL
FREQUENCY_MODEL
WIDTH
HEIGHT
CENTRE_LENGTH
END_LENGTH
CAVITY_CENTRE
MAX_ORDER
SIZE
Definition at line 38 of file OpalVariableRFCavityFringeField.h.
Constructor & Destructor Documentation
OpalVariableRFCavityFringeField() [1/3]
OpalVariableRFCavityFringeField::OpalVariableRFCavityFringeField (const std::string & name, OpalVariableRFCavityFringeField * parent)
Copy constructor
Definition at line 68 of file OpalVariableRFCavityFringeField.cpp.
References Element::getElement(), and Element::setElement().
OpalVariableRFCavityFringeField() [2/3]
OpalVariableRFCavityFringeField::OpalVariableRFCavityFringeField ()
Default constructor
Definition at line 42 of file OpalVariableRFCavityFringeField.cpp.
References AMPLITUDE_MODEL, CAVITY_CENTRE, CENTRE_LENGTH, END_LENGTH, FREQUENCY_MODEL, HEIGHT, Object::itsAttr, Attributes::makeReal(), Attributes::makeString(), MAX_ORDER, PHASE_MODEL, OpalElement::registerOwnership(), Element::setElement(), and WIDTH.
Referenced by clone().
~OpalVariableRFCavityFringeField()
OpalVariableRFCavityFringeField::~OpalVariableRFCavityFringeField () virtual
Destructor does nothing
Definition at line 77 of file OpalVariableRFCavityFringeField.cpp.
OpalVariableRFCavityFringeField() [3/3]
OpalVariableRFCavityFringeField::OpalVariableRFCavityFringeField (const OpalVariableRFCavityFringeField &) private
Member Function Documentation
clone() [1/2]
OpalVariableRFCavityFringeField * OpalVariableRFCavityFringeField::clone ()
Inherited copy constructor
Call on a base class to instantiate an object of derived class's type
Definition at line 85 of file OpalVariableRFCavityFringeField.cpp.
References Object::getOpalName(), and OpalVariableRFCavityFringeField().
clone() [2/2]
OpalVariableRFCavityFringeField * OpalVariableRFCavityFringeField::clone (const std::string & name) virtual
Inherited copy constructor
Call on a base class to instantiate an object of derived class's type
Implements Object.
Definition at line 80 of file OpalVariableRFCavityFringeField.cpp.
References name, and OpalVariableRFCavityFringeField().
convertToUnsigned()
size_t OpalVariableRFCavityFringeField::convertToUnsigned (double value, std::string name) inline static private
Check for conversion to unsigned int
Definition at line 124 of file OpalVariableRFCavityFringeField.cpp.
References abs(), floor(), name, and unsignedTolerance.
Referenced by update().
operator=()
void OpalVariableRFCavityFringeField::operator= (const OpalVariableRFCavityFringeField &) private
update()
void OpalVariableRFCavityFringeField::update () virtual
Update the OpalVariableRFCavity with new parameters from UI parser
Reimplemented from OpalElement.
Definition at line 89 of file OpalVariableRFCavityFringeField.cpp.
References AMPLITUDE_MODEL, CAVITY_CENTRE, CENTRE_LENGTH, convertToUnsigned(), end(), END_LENGTH, FREQUENCY_MODEL, Element::getElement(), Attributes::getReal(), Attributes::getString(), HEIGHT, Object::itsAttr, OpalElement::LENGTH, MAX_ORDER, PHASE_MODEL, VariableRFCavity::setAmplitudeName(), VariableRFCavityFringeField::setCavityCentre(), Element::setElement(), VariableRFCavityFringeField::setEndField(), VariableRFCavity::setFrequencyName(), VariableRFCavity::setHeight(), VariableRFCavity::setLength(), VariableRFCavityFringeField::setMaxOrder(), VariableRFCavity::setPhaseName(), VariableRFCavity::setWidth(), tanh(), OpalElement::update(), and WIDTH.
Member Data Documentation
doc_string
const std::string OpalVariableRFCavityFringeField::doc_string static private
Initial value:
=
      std::string("The \"VARIABLE_RF_CAVITY_FRINGE_FIELD\" element defines an RF cavity ")+
      std::string("with time dependent frequency, phase and amplitude.")
Definition at line 83 of file OpalVariableRFCavityFringeField.h.
unsignedTolerance
constexpr double OpalVariableRFCavityFringeField::unsignedTolerance = 1e-9 static private
Definition at line 84 of file OpalVariableRFCavityFringeField.h.
Referenced by convertToUnsigned().
The documentation for this class was generated from the following files:
src/Elements/OpalVariableRFCavityFringeField.h
src/Elements/OpalVariableRFCavityFringeField.cpp