OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyDistributionNS Namespace Reference
PyOpal::PyDistributionNS Namespace Reference
Functions
void registerDistribution (PyOpalObjectNS::PyOpalObject< Distribution > &dist)
BOOST_PYTHON_MODULE (distribution)
Variables
std::string distribution_docstring = std::string()
const char * module_docstring = "build a distribution object"
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyDistributionNS::BOOST_PYTHON_MODULE (distribution)
Definition at line 30 of file PyDistribution.cpp.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::addExecute(), PyOpal::Globals::Initialise(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_class(), registerDistribution(), and PyOpal::ExceptionTranslation::registerExceptions().
registerDistribution()
void PyOpal::PyDistributionNS::registerDistribution (PyOpalObjectNS::PyOpalObject< Distribution > & dist)
Definition at line 25 of file PyDistribution.cpp.
References OpalData::define(), OpalData::getInstance(), and PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalShared().
Referenced by BOOST_PYTHON_MODULE().
Variable Documentation
distribution_docstring
std::string PyOpal::PyDistributionNS::distribution_docstring = std::string()
Definition at line 10 of file PyDistribution.cpp.
module_docstring
const char* PyOpal::PyDistributionNS::module_docstring = "build a distribution object"
Definition at line 13 of file PyDistribution.cpp.