OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Classic/Algebra/TpsMath.h File Reference
TpsMath.h File Reference
#include "Algebra/Tps.h"
#include "Utilities/DomainError.h"
#include <cmath>
Functions
template<class T >
Tps< T > pow (const Tps< T > &x, int y)
Integer power.
template<class T >
Tps< T > sqrt (const Tps< T > &x)
Square root.
template<class T >
Tps< T > sin (const Tps< T > &x)
Sine.
template<class T >
Tps< T > cos (const Tps< T > &x)
Cosine.
template<class T >
Tps< T > tan (const Tps< T > &x)
Tangent.
template<class T >
Tps< T > cot (const Tps< T > &x)
Cotangent.
template<class T >
Tps< T > sec (const Tps< T > &x)
Secant.
template<class T >
Tps< T > csc (const Tps< T > &x)
Cosecant.
template<class T >
Tps< T > exp (const Tps< T > &x)
Exponential.
template<class T >
Tps< T > log (const Tps< T > &x)
Natural logarithm.
template<class T >
Tps< T > sinh (const Tps< T > &x)
Hyperbolic sine.
template<class T >
Tps< T > cosh (const Tps< T > &x)
Hyperbolic cosine.
template<class T >
Tps< T > tanh (const Tps< T > &x)
Hyperbolic tangent.
Function Documentation
cos()
template<class T > Tps< T > cos (const Tps< T > & x)
Cosine.
Definition at line 129 of file TpsMath.h.
References Tps< T >::getTruncOrder(), sin(), Attrib::Legacy::Distribution::T, and Tps< T >::Taylor().
Referenced by Ring::appendElement(), mslang::Repeat::apply(), TravelingWave::apply(), VariableRFCavityFringeField::apply(), RFCavity::apply(), Cyclotron::apply(), Distribution::applyEmissModelAstra(), Distribution::applyEmissModelNonEquil(), ScatteringPhysics::applyRandomRotation(), mslang::Rotation::applyRotation(), ScatteringPhysics::applyRotation(), TravelingWave::applyToReferenceParticle(), RFCavity::applyToReferenceParticle(), OscillatingField< ConstEzField >::Bfield(), ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), _Fieldmap::checkMap(), OpalBeamline::compute3DLattice(), mslang::Ellipse::computeBoundingBox(), ScatteringPhysics::computeCoulombScattering(), _FM1DElectroStatic_fast::computeFieldDerivatives(), _FM1DMagnetoStatic_fast::computeFieldDerivatives(), _Astra1D_fast::computeFieldDerivatives(), _FM1DDynamic_fast::computeFieldDerivatives(), _FM1DDynamic::computeFieldOnAxis(), _FM1DElectroStatic::computeFieldOnAxis(), _FM1DMagnetoStatic::computeFieldOnAxis(), ClosedOrbitFinder< Value_type, Size_type, Stepper >::computeTune(), SectorField::convertToCartesian(), SectorField::convertToPolar(), MapAnalyser::createRotMatrix_m(), RingSection::doesOverlap(), ParallelCyclotronTracker::dumpAzimuthAngles_m(), ParallelCyclotronTracker::dumpThetaEachTurn_m(), OscillatingField< ConstEzField >::Efield(), Distribution::generateBinomial(), TravelingWave::getAutoPhaseEstimate(), RFCavity::getAutoPhaseEstimate(), MeshGenerator::getCylinder(), TravelingWave::getdA(), RFCavity::getdA(), TravelingWave::getdB(), RFCavity::getdB(), TravelingWave::getdE(), RFCavity::getdE(), _FM1DDynamic::getFieldDerivative(), _Astra1DDynamic::getFieldDerivative(), _FM1DElectroStatic::getFieldDerivative(), _FM1DMagnetoStatic::getFieldDerivative(), _Astra1DDynamic::getFieldstrength(), _Astra1DElectroStatic::getFieldstrength(), _Astra1DMagnetoStatic::getFieldstrength(), SectorMagneticFieldMap::getFieldstrength(), ScalingFFAMagnet::getFieldValue(), SinusoidalTimeDependence::getIntegral(), RFCavity::getMomentaKick(), Bend2D::getOutline(), getQuaternion(), ParallelCyclotronTracker::getQuaternionTwoVectors(), Ring::getStartNormal(), Ring::getStartPosition(), Bend2D::getSurfaceMesh(), Util::getTaitBryantAngles(), coordinatetransform::CoordinateTransform::getUnitTangentVector(), coordinatetransform::getUnitTangentVectorY(), Offset::globalCylindricalOffset(), ParallelCyclotronTracker::globalToLocal(), RFCavity::initialise(), MultipoleTCurvedConstRadius::localCartesianToOpalCartesian(), MultipoleTCurvedVarRadius::localCartesianToOpalCartesian(), Offset::localCylindricalOffset(), ParallelCyclotronTracker::localToGlobal(), GreenWakeFunction::Wake::operator()(), GlobalFunctions::_cos::operator()(), LOMB_class::period(), H5PartWrapperForPT::readStepHeader(), Offset::rotate(), ParallelCyclotronTracker::rotateAroundX(), ParallelCyclotronTracker::rotateAroundZ(), MultipoleT::rotateFrame(), Rotation3D::Rotation3D(), sec(), ParallelCyclotronTracker::seoMode_m(), _FM1DProfile2::setEdgeConstants(), Bend2D::setEntranceAngle(), Bend2D::setFieldBoundaries(), Bend2D::setFieldCalcParam(), sin(), tan(), RBend3D::trackRefParticleThrough(), RealDiracMatrix::transform(), MultipoleTCurvedConstRadius::transformBField(), MultipoleTCurvedVarRadius::transformBField(), MultipoleTCurvedVarRadius::transformCoords(), matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_(), OpalElement::update(), RingSection::updateComponentOrientation(), Offset::updateGeometry(), ParallelCyclotronTracker::visitCyclotron(), ParallelCyclotronTracker::visitRing(), DumpEMFields::writeFieldLine(), mslang::Ellipse::writeGnuplot(), Rotation3D::XRotation(), Rotation3D::YRotation(), and Rotation3D::ZRotation().
cosh()
template<class T > Tps< T > cosh (const Tps< T > & x)
Hyperbolic cosine.
Definition at line 222 of file TpsMath.h.
References Tps< T >::getTruncOrder(), sinh(), Attrib::Legacy::Distribution::T, and Tps< T >::Taylor().
Referenced by coordinatetransform::CoordinateTransform::getUnitTangentVector(), coordinatetransform::getUnitTangentVectorX(), coordinatetransform::getUnitTangentVectorY(), sinh(), tanh(), RealDiracMatrix::transform(), MultipoleTCurvedVarRadius::transformBField(), and matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
cot()
template<class T > Tps<T> cot (const Tps< T > & x)
Cotangent.
csc()
template<class T > Tps< T > csc (const Tps< T > & x)
Cosecant.
Definition at line 159 of file TpsMath.h.
References sin().
exp()
template<class T > Tps< T > exp (const Tps< T > & x)
Exponential.
Definition at line 165 of file TpsMath.h.
References Tps< T >::getTruncOrder(), Attrib::Legacy::Distribution::T, and Tps< T >::Taylor().
Referenced by Distribution::applyEmissModelNonEquil(), Bend2D::calcEngeFunction(), BeamStrippingPhysics::computeCrossSectionChebyshev(), _FM1DProfile1::computeFringe(), Distribution::createDistributionMultiGauss(), Util::erfinv(), BeamStrippingPhysics::evalGasStripping(), BeamStrippingPhysics::evalLorentzStripping(), _FM1DProfile2::getFieldstrength(), VerticalFFAMagnet::getFieldValue(), endfieldmodel::Enge::gN(), ApplyField< T >::operator()(), GlobalFunctions::_pow::operator()(), GlobalFunctions::_exp::operator()(), LOMB_class::period(), LOMB_class::signi(), and matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
log()
template<class T > Tps< T > log (const Tps< T > & x)
Natural logarithm.
Definition at line 182 of file TpsMath.h.
References Tps< T >::getTruncOrder(), and Attrib::Legacy::Distribution::T.
Referenced by CSRIGFWakeFunction::calculateGreenFunction(), ScatteringPhysics::computeCoulombScattering(), BeamStrippingPhysics::computeCrossSectionChebyshev(), ScatteringPhysics::computeEnergyLoss(), TrimCoilMirrored::doApplyField(), Util::erfinv(), Random::gauss(), Distribution::generateLongFlattopT(), Distribution::GaussianLikeBehavior::get(), Distribution::getTEmission(), coordinatetransform::CoordinateTransform::getUnitTangentVector(), coordinatetransform::getUnitTangentVectorX(), coordinatetransform::getUnitTangentVectorY(), FFTBoxPoissonSolver::integratedGreensFunction(), FFTPoissonSolver::integratedGreensFunction(), P3MPoissonSolver::integratedGreensFunction(), GlobalFunctions::_log::operator()(), IndexMap::print(), _FM1DProfile2::readMap(), Distribution::setDistParametersFlattop(), Distribution::setDistParametersGauss(), Distribution::setEmissionTime(), Distribution::setupEmissionModelNonEquil(), FFTBoxPoissonSolver::shiftedIntGreensFunction(), FFTPoissonSolver::shiftedIntGreensFunction(), Util::toStringWithThousandSep(), MultipoleTCurvedVarRadius::transformBField(), and matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
pow()
template<class T > Tps< T > pow (const Tps< T > & x, int y)
Integer power.
Definition at line 76 of file TpsMath.h.
References Tps< T >::inverse(), and Attrib::Legacy::Distribution::T.
Referenced by Distribution::adjustPhaseSpace(), Distribution::applyEmissModelNonEquil(), polynomial::RecursionRelation::applyOperator(), polynomial::RecursionRelationTwo::applyOperator(), matheval::detail::grammar< real_t, Iterator >::bfunc_::bfunc_(), BendBase::calcBetaGamma(), MultiBunchHandler::calcBunchBeamParameters(), Bend2D::calcEngeFunction(), Bend2D::calcEntranceFringeField(), Bend2D::calcExitFringeField(), CSRWakeFunction::calcPsi(), CSRIGFWakeFunction::calcPsi(), CSRWakeFunction::calculateContributionAfter(), CSRIGFWakeFunction::calculateContributionAfter(), CSRWakeFunction::calculateContributionInside(), CSRIGFWakeFunction::calculateGreenFunction(), _Fieldmap::checkMap(), SocialNetworkGraph< TopoDiscoveryStrategy_t >::chooseRandomNeighbor(), BeamStrippingPhysics::computeCrossSectionBohr(), BeamStrippingPhysics::computeCrossSectionNakai(), BeamStrippingPhysics::computeCrossSectionTabata(), DistributionMoments::computeDebyeLength(), RootFinderForCSR::computeDerivative(), ScatteringPhysics::computeEnergyLoss(), _FM1DElectroStatic_fast::computeFieldDerivatives(), _FM1DMagnetoStatic_fast::computeFieldDerivatives(), _FM1DDynamic_fast::computeFieldDerivatives(), _FM1DDynamic::computeFieldOffAxis(), _FM1DElectroStatic::computeFieldOffAxis(), _FM1DMagnetoStatic::computeFieldOffAxis(), _FM1DElectroStatic_fast::computeFieldOffAxis(), _FM1DDynamic_fast::computeFieldOffAxis(), _FM1DMagnetoStatic_fast::computeFieldOffAxis(), _FM1DDynamic::computeFieldOnAxis(), _FM1DElectroStatic::computeFieldOnAxis(), _FM1DMagnetoStatic::computeFieldOnAxis(), _FM1DProfile1::computeFringe(), DistributionMoments::computeNormalizedEmittance(), DistributionMoments::computePercentiles(), DistributionMoments::computePlasmaParameter(), LossDataSink::computeSetStatistics(), DistributionMoments::computeStatistics(), RootFinderForCSR::computeValue(), RootFinderForCSR::computeValueGSL(), _FM1DDynamic::convertHeaderData(), _FM1DDynamic_fast::convertHeaderData(), Distribution::createDistributionMultiGauss(), SimulatedBinaryCrossover< T >::crossover(), Distribution::doRestartOpalCycl(), Distribution::emitParticles(), Bend2D::estimateFieldAdjustmentStep(), DistributionMoments::fillMembers(), TpsData::fillSubst(), ParallelCyclotronTracker::finalizeTracking_m(), ParallelTTracker::findStartPosition(), Distribution::generateBinomial(), Distribution::generateGaussZ(), Distribution::generateTransverseGauss(), Distribution::MDependentBehavior::get(), PartBunchBase< double, 3 >::get_pmean_Distribution(), Util::getBetaGamma(), interpolation::PPSolveFactory::getDerivPoints(), RFCavity::getMomentaKick(), Bend2D::getOutline(), Bend2D::getSurfaceMesh(), Corrector::goOnline(), matheval::detail::grammar< real_t, Iterator >::grammar(), Cyclotron::gutdf5d(), RootFinderForCSR::hasPositiveRealRoots(), SigmaGenerator::initialize(), P3MPoissonSolver::integratedGreensFunction(), Bend2D::isFieldZero(), Multipole::isFocusing(), mslang::Ellipse::isInside(), Degrader::isInside(), ElementBase::isInsideTransverse(), PartBunchBase< double, 3 >::maximumAmplitudes(), LOMB_class::moment(), ApplyField< T >::operator()(), GlobalFunctions::_pow::operator()(), LOMB_class::period(), H5PartWrapperForPC::readStepHeader(), PartBunchBase< double, 3 >::resetPartBinID2(), ParallelCyclotronTracker::RFkick(), RootFinderForCSR::RootFinderForCSR(), Distribution::sampleUniformDisk(), savgol(), Corrector::setDesignEnergy(), Bend2D::setFieldCalcParam(), Distribution::setupEmissionModelNonEquil(), LOMB_class::signi(), _FM3DMagnetoStaticExtended::smoothData(), Util::toStringWithThousandSep(), and mslang::Ellipse::writeGnuplot().
sec()
template<class T > Tps< T > sec (const Tps< T > & x)
Secant.
Definition at line 153 of file TpsMath.h.
References cos().
Referenced by PyOpal::Field::getElementEndNormal(), PyOpal::Field::getElementEndPosition(), PyOpal::Field::getElementName(), PyOpal::Field::getElementStartNormal(), PyOpal::Field::getElementStartPosition(), and Ring::getSection().
sin()
template<class T > Tps< T > sin (const Tps< T > & x)
Sine.
Definition at line 111 of file TpsMath.h.
References cos(), Tps< T >::getTruncOrder(), Attrib::Legacy::Distribution::T, and Tps< T >::Taylor().
Referenced by Ring::appendElement(), mslang::Repeat::apply(), TravelingWave::apply(), VariableRFCavity::apply(), VariableRFCavityFringeField::apply(), RFCavity::apply(), Cyclotron::apply(), Distribution::applyEmissModelAstra(), Distribution::applyEmissModelNonEquil(), ScatteringPhysics::applyRandomRotation(), mslang::Rotation::applyRotation(), ScatteringPhysics::applyRotation(), TravelingWave::applyToReferenceParticle(), RFCavity::applyToReferenceParticle(), ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), BendBase::calcDesignRadius(), _Fieldmap::checkMap(), OpalBeamline::compute3DLattice(), mslang::Ellipse::computeBoundingBox(), ScatteringPhysics::computeCoulombScattering(), _Astra1D_fast::computeFieldDerivatives(), _FM1DElectroStatic_fast::computeFieldDerivatives(), _FM1DMagnetoStatic_fast::computeFieldDerivatives(), _FM1DDynamic_fast::computeFieldDerivatives(), _FM1DDynamic::computeFieldOnAxis(), _FM1DElectroStatic::computeFieldOnAxis(), _FM1DMagnetoStatic::computeFieldOnAxis(), ClosedOrbitFinder< Value_type, Size_type, Stepper >::computeTune(), SectorField::convertToCartesian(), SectorField::convertToPolar(), cos(), MapAnalyser::createRotMatrix_m(), csc(), RingSection::doesOverlap(), ParallelCyclotronTracker::dumpAzimuthAngles_m(), ParallelCyclotronTracker::dumpThetaEachTurn_m(), RBend::findChordLength(), Distribution::generateBinomial(), Distribution::generateLongFlattopT(), RBendGeometry::getArcLength(), TravelingWave::getAutoPhaseEstimate(), RFCavity::getAutoPhaseEstimate(), MeshGenerator::getCylinder(), TravelingWave::getdA(), RFCavity::getdA(), TravelingWave::getdB(), RFCavity::getdB(), TravelingWave::getdE(), RFCavity::getdE(), _Astra1DDynamic::getFieldDerivative(), _FM1DDynamic::getFieldDerivative(), _FM1DElectroStatic::getFieldDerivative(), _FM1DMagnetoStatic::getFieldDerivative(), _Astra1DDynamic::getFieldstrength(), _Astra1DMagnetoStatic::getFieldstrength(), _Astra1DElectroStatic::getFieldstrength(), SectorMagneticFieldMap::getFieldstrength(), ScalingFFAMagnet::getFieldValue(), RFCavity::getMomentaKick(), Bend2D::getOutline(), getQuaternion(), ParallelCyclotronTracker::getQuaternionTwoVectors(), Ring::getStartNormal(), Ring::getStartPosition(), Bend2D::getSurfaceMesh(), Util::getTaitBryantAngles(), coordinatetransform::CoordinateTransform::getUnitTangentVector(), coordinatetransform::getUnitTangentVectorX(), SinusoidalTimeDependence::getValue(), Offset::globalCylindricalOffset(), ParallelCyclotronTracker::globalToLocal(), TravelingWave::initialise(), RFCavity::initialise(), MultipoleTCurvedConstRadius::localCartesianToOpalCartesian(), MultipoleTCurvedVarRadius::localCartesianToOpalCartesian(), Offset::localCylindricalOffset(), ParallelCyclotronTracker::localToGlobal(), GlobalFunctions::_sin::operator()(), LOMB_class::period(), H5PartWrapperForPT::readStepHeader(), Offset::rotate(), ParallelCyclotronTracker::rotateAroundX(), ParallelCyclotronTracker::rotateAroundZ(), MultipoleT::rotateFrame(), Rotation3D::Rotation3D(), ParallelCyclotronTracker::seoMode_m(), _FM1DProfile2::setEdgeConstants(), Bend2D::setEntranceAngle(), Bend2D::setFieldCalcParam(), sinti(), tan(), RBend3D::trackRefParticleThrough(), RealDiracMatrix::transform(), MultipoleTCurvedConstRadius::transformBField(), MultipoleTCurvedVarRadius::transformBField(), MultipoleTCurvedConstRadius::transformCoords(), MultipoleTCurvedVarRadius::transformCoords(), matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_(), OpalRBend::update(), OpalSBend::update(), OpalRBend3D::update(), OpalElement::update(), RingSection::updateComponentOrientation(), Offset::updateGeometry(), ParallelCyclotronTracker::visitCyclotron(), ParallelCyclotronTracker::visitRing(), DumpEMFields::writeFieldLine(), Rotation3D::XRotation(), Rotation3D::YRotation(), and Rotation3D::ZRotation().
sinh()
template<class T > Tps< T > sinh (const Tps< T > & x)
Hyperbolic sine.
Definition at line 204 of file TpsMath.h.
References cosh(), Tps< T >::getTruncOrder(), Attrib::Legacy::Distribution::T, and Tps< T >::Taylor().
Referenced by cosh(), tanh(), RealDiracMatrix::transform(), and matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
sqrt()
template<class T > Tps< T > sqrt (const Tps< T > & x)
Square root.
Definition at line 91 of file TpsMath.h.
References Tps< T >::getTruncOrder(), Attrib::Legacy::Distribution::T, and Tps< T >::Taylor().
Referenced by AmrOpenBoundary< Level >::abc1_m(), AmrOpenBoundary< Level >::abc2_m(), AmrOpenBoundary< Level >::abc3_m(), Undulator::apply(), Degrader::apply(), GreenWakeFunction::apply(), Tracker::applyDrift(), Distribution::applyEmissModelAstra(), Distribution::applyEmissModelNonEquil(), ScatteringPhysics::applyRandomRotation(), Tracker::applyTransform(), Hamiltonian::bendFringe(), PartBunchBase< double, 3 >::boundp(), ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), BendBase::calcBetaGamma(), MultiBunchHandler::calcBunchBeamParameters(), PartBunchBase< double, 3 >::calcGammas(), PartBunchBase< double, 3 >::calcGammas_cycl(), SpecializedGreensFunction< 3 >::calculate(), P3MGreensFunction< 3 >::calculate(), CSRIGFWakeFunction::calculateGreenFunction(), PluginElement::changeWidth(), _Fieldmap::checkMap(), Vacuum::checkPoint(), Vacuum::checkPressure(), EllipticDomain::compute(), ScatteringPhysics::computeCoulombScattering(), BeamStrippingPhysics::computeCrossSectionBohr(), DistributionMoments::computeDebyeLength(), ScatteringPhysics::computeEnergyLoss(), DistributionMoments::computeNormalizedEmittance(), ClosedOrbitFinder< Value_type, Size_type, Stepper >::computeOrbitProperties(), ParallelCyclotronTracker::computePathLengthUpdate(), LaserProfile::computeProfileStatistics(), ParallelCyclotronTracker::computeRadius(), PartBunch::computeSelfFields(), PartBunch::computeSelfFields_cycl(), AmrBoxLib::computeSelfFields_cycl(), LossDataSink::computeSetStatistics(), SectorField::convertToPolar(), RK4< FieldFunction, Arguments >::derivate_m(), Probe::doCheck(), Stripper::doCheck(), BeamStrippingPhysics::doPhysics(), Distribution::doRestartOpalCycl(), Hamiltonian::drift(), ParallelCyclotronTracker::dumpThetaEachTurn_m(), Distribution::emitParticles(), Util::erfinv(), Bend2D::estimateFieldAdjustmentStep(), euclidean_norm(), BeamStrippingPhysics::evalLorentzStripping(), DistributionMoments::fillMembers(), ParallelCyclotronTracker::finalizeTracking_m(), ClosedOrbitFinder< Value_type, Size_type, Stepper >::findOrbit(), ClosedOrbitFinder< Value_type, Size_type, Stepper >::findOrbitOfEnergy_m(), ParallelTTracker::findStartPosition(), Random::gauss(), Distribution::generateAstraFlattopT(), Distribution::generateBinomial(), Distribution::generateLongFlattopT(), Distribution::generateMatchedGauss(), Distribution::MDependentBehavior::get(), Distribution::GaussianLikeBehavior::get(), PartBunchBase< double, 3 >::get_pmean_Distribution(), Euclid3DGeometry::getArcLength(), Rotation3D::getAxis(), Util::getBetaGamma(), MapAnalyser::getBlockDiagonal_m(), PartBunchBase< double, 3 >::getBoundingSphere(), OutputPlane::getDerivatives(), TravelingWave::getdT(), RFCavity::getdT(), _FM2DMagnetoStatic::getFieldDerivative(), _FM2DElectroStatic::getFieldstrength(), _FM2DMagnetoStatic::getFieldstrength(), _FM2DDynamic::getFieldstrength(), ScalingFFAMagnet::getFieldValue(), Util::getGamma(), PartBunchBase< double, 3 >::getLocalBoundingSphere(), RFCavity::getMomentaKick(), CavityAutophaser::getPhaseAtMaxEnergy(), getQuaternion(), ParallelCyclotronTracker::getQuaternionTwoVectors(), Ring::getRingMaxR(), Ring::getRingMinR(), Distribution::getTEmission(), RingSection::getVirtualBoundingBox(), Corrector::goOnline(), RootFinderForCSR::hasPositiveRealRoots(), FDoubleEigen< N >::hqr(), FDoubleEigen< N >::hqr2(), ParallelCyclotronTracker::initDistInGlobalFrame(), BoundaryGeometry::initialize(), SigmaGenerator::initialize(), OrbitThreader::integrate(), FFTBoxPoissonSolver::integratedGreensFunction(), FFTPoissonSolver::integratedGreensFunction(), P3MPoissonSolver::integratedGreensFunction(), OutputPlane::interpolation(), _FM2DElectroStatic::isInside(), _FM2DMagnetoStatic::isInside(), _FM2DDynamic::isInside(), BorisPusher::kick(), SigmaGenerator::L2ErrorNorm(), Quaternion::length(), SocialNetworkGraph< TopoDiscoveryStrategy_t >::manhattenDistance(), LOMB_class::moment(), MapAnalyser::normalizeEigen_m(), ParallelCyclotronTracker::normalizeQuaternion(), ParallelCyclotronTracker::normalizeVector(), SumErrSqRadialPeak::operator()(), SumErrSq::operator()(), ApplyField< T >::operator()(), GlobalFunctions::_sqrt::operator()(), GreenWakeFunction::Wake::operator()(), BoundaryGeometry::partInside(), LOMB_class::period(), OpalElement::printMultipoleStrength(), BorisPusher::push(), LF2< FieldFunction, Arguments >::push_m(), Hamiltonian::quadrupole(), Quaternion::Quaternion(), Hamiltonian::rbend(), H5PartWrapperForPC::readStepHeader(), PartBunchBase< double, 3 >::resetPartBinID2(), MultipoleTCurvedVarRadius::reverseTransformResidual(), ParallelCyclotronTracker::RFkick(), Expressions::Rmsa(), Rotation3D::Rotation3D(), SampleGaussianSequence::SampleGaussianSequence(), Hamiltonian::sbend(), scaled_norm(), PartData::setBeta(), Corrector::setDesignEnergy(), OrbitThreader::setDesignEnergy(), PluginElement::setDimensions(), Distribution::setDistParametersFlattop(), Distribution::setDistParametersGauss(), PartData::setE(), Distribution::setEmissionTime(), PartData::setGamma(), PluginElement::setGeom(), SocialNetworkGraph< TopoDiscoveryStrategy_t >::setNetworkNeighbors(), MapAnalyser::setNMatrix_m(), PartData::setP(), Distribution::setupEmissionModelNonEquil(), FFTBoxPoissonSolver::shiftedIntGreensFunction(), FFTPoissonSolver::shiftedIntGreensFunction(), SigmaGenerator::SigmaGenerator(), QRDecomposition::solve(), PartBins::sortArray(), RFCavity::trackOnAxisParticle(), matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_(), OpalOutputPlane::update(), ThickTracker::update_m(), Offset::updateGeometry(), SigmaGenerator::updateInitialSigma(), ThickTracker::updateParticle_m(), ParallelCyclotronTracker::visitCyclotron(), ParallelCyclotronTracker::visitRing(), ThickTracker::visitSBend(), Werrf(), and mslang::Ellipse::writeGnuplot().
tan()
template<class T > Tps< T > tan (const Tps< T > & x)
Tangent.
Definition at line 147 of file TpsMath.h.
References cos(), and sin().
Referenced by mslang::Shear::applyShear(), Hamiltonian::fringeField(), RBendGeometry::getEntrancePatch(), RBendGeometry::getExitPatch(), GlobalFunctions::_tan::operator()(), Bend2D::setEntranceAngle(), Bend2D::setExitAngle(), RBend3D::trackRefParticleThrough(), matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_(), and mslang::Ellipse::writeGnuplot().
tanh()
template<class T > Tps< T > tanh (const Tps< T > & x)
Hyperbolic tangent.
Definition at line 240 of file TpsMath.h.
References cosh(), and sinh().
Referenced by endfieldmodel::Tanh::getNegTanh(), endfieldmodel::Tanh::getTanh(), coordinatetransform::CoordinateTransform::getUnitTangentVector(), coordinatetransform::getUnitTangentVectorX(), coordinatetransform::getUnitTangentVectorY(), MultipoleTCurvedVarRadius::transformBField(), matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_(), and OpalVariableRFCavityFringeField::update().