OPAL (Object Oriented Parallel Accelerator Library): mslang::QuadTree Struct Reference
mslang::QuadTree Struct Reference
#include <QuadTree.h>
Public Member Functions
QuadTree ()
QuadTree (int l, const BoundingBox2D &b)
QuadTree (const QuadTree &right)
~QuadTree ()
void reset ()
void operator= (const QuadTree &right)
void transferIfInside (std::list< std::shared_ptr< Base > > &objs)
void buildUp ()
void writeGnuplot (std::ostream &out) const
bool isInside (const Vector_t &R) const
void getDepth (unsigned int &d) const
Public Attributes
int level_m
std::list< std::shared_ptr< Base > > objects_m
BoundingBox2D bb_m
std::vector< std::shared_ptr< QuadTree > > nodes_m
Detailed Description
Definition at line 9 of file QuadTree.h.
Constructor & Destructor Documentation
QuadTree() [1/3]
mslang::QuadTree::QuadTree () inline
Definition at line 15 of file QuadTree.h.
Referenced by buildUp(), operator=(), and QuadTree().
QuadTree() [2/3]
mslang::QuadTree::QuadTree (int l, const BoundingBox2D & b) inline
Definition at line 21 of file QuadTree.h.
QuadTree() [3/3]
mslang::QuadTree::QuadTree (const QuadTree & right)
Definition at line 5 of file QuadTree.cpp.
References nodes_m, and QuadTree().
~QuadTree()
mslang::QuadTree::~QuadTree ()
Definition at line 19 of file QuadTree.cpp.
References nodes_m, and objects_m.
Member Function Documentation
buildUp()
void mslang::QuadTree::buildUp ()
Definition at line 58 of file QuadTree.cpp.
References bb_m, mslang::BoundingBox2D::center_m, mslang::BoundingBox2D::height_m, level_m, nodes_m, objects_m, QuadTree(), mslang::BoundingBox2D::width_m, and X.
Referenced by FlexibleCollimator::FlexibleCollimator(), and FlexibleCollimator::setDescription().
getDepth()
void mslang::QuadTree::getDepth (unsigned int & d) const
Definition at line 124 of file QuadTree.cpp.
References level_m, and nodes_m.
isInside()
bool mslang::QuadTree::isInside (const Vector_t & R) const
Definition at line 104 of file QuadTree.cpp.
References bb_m, mslang::BoundingBox2D::center_m, nodes_m, objects_m, Attrib::Distribution::R, and X.
Referenced by FlexibleCollimator::isStopped().
operator=()
void mslang::QuadTree::operator= (const QuadTree & right)
Definition at line 32 of file QuadTree.cpp.
References bb_m, level_m, nodes_m, objects_m, and QuadTree().
reset()
void mslang::QuadTree::reset ()
Definition at line 27 of file QuadTree.cpp.
References nodes_m, and objects_m.
Referenced by FlexibleCollimator::setDescription().
transferIfInside()
void mslang::QuadTree::transferIfInside (std::list< std::shared_ptr< Base > > & objs)
Definition at line 48 of file QuadTree.cpp.
References bb_m, mslang::BoundingBox2D::isInside(), and objects_m.
writeGnuplot()
void mslang::QuadTree::writeGnuplot (std::ostream & out) const
Definition at line 91 of file QuadTree.cpp.
References bb_m, endl(), level_m, nodes_m, objects_m, and mslang::BoundingBox2D::writeGnuplot().
Referenced by FlexibleCollimator::writeHolesAndQuadtree().
Member Data Documentation
bb_m
BoundingBox2D mslang::QuadTree::bb_m
Definition at line 12 of file QuadTree.h.
Referenced by buildUp(), FlexibleCollimator::FlexibleCollimator(), isInside(), operator=(), FlexibleCollimator::setDescription(), transferIfInside(), and writeGnuplot().
level_m
int mslang::QuadTree::level_m
Definition at line 10 of file QuadTree.h.
Referenced by buildUp(), getDepth(), operator=(), and writeGnuplot().
nodes_m
std::vector<std::shared_ptr<QuadTree> > mslang::QuadTree::nodes_m
Definition at line 13 of file QuadTree.h.
Referenced by buildUp(), getDepth(), isInside(), operator=(), QuadTree(), reset(), writeGnuplot(), and ~QuadTree().
objects_m
std::list<std::shared_ptr<Base> > mslang::QuadTree::objects_m
Definition at line 11 of file QuadTree.h.
Referenced by buildUp(), FlexibleCollimator::FlexibleCollimator(), isInside(), operator=(), reset(), FlexibleCollimator::setDescription(), transferIfInside(), writeGnuplot(), and ~QuadTree().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/QuadTree.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/QuadTree.cpp