OPAL (Object Oriented Parallel Accelerator Library): IntCICImpl< Dim > Class Template Reference
IntCICImpl< Dim > Class Template Reference
#include <IntCIC.h>
Public Member Functions
IntCICImpl ()
~IntCICImpl ()
Public Member Functions inherited from Interpolator
Interpolator ()
~Interpolator ()
Static Public Member Functions
template<class FT , class M , class C , class PT >
static void scatter (const FT &, Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void scatter (const FT &, Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh, NDIndex< Dim > &ngp, int lgpoff[Dim], Vektor< PT, Dim > &dpos)
template<class FT , class M , class C , class PT >
static void scatter (const FT &, Field< FT, Dim, M, C > &f, const NDIndex< Dim > &ngp, const int lgpoff[Dim], const Vektor< PT, Dim > &)
template<class FT , class M , class C , class PT >
static void gather (FT &, const Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void gather (FT &, const Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh, NDIndex< Dim > &ngp, int lgpoff[Dim], Vektor< PT, Dim > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &, const Field< FT, Dim, M, C > &f, const NDIndex< Dim > &ngp, const int lgpoff[Dim], const Vektor< PT, Dim > &)
Additional Inherited Members
Static Protected Member Functions inherited from Interpolator
template<class T , unsigned Dim>
static CompressedBrickIterator< T, Dim > getFieldIter (const BareField< T, Dim > &f, const NDIndex< Dim > &pt)
Detailed Description
template<unsigned Dim>
class IntCICImpl< Dim >
Definition at line 37 of file IntCIC.h.
Constructor & Destructor Documentation
IntCICImpl()
template<unsigned Dim> IntCICImpl< Dim >::IntCICImpl () inline
Definition at line 41 of file IntCIC.h.
~IntCICImpl()
template<unsigned Dim> IntCICImpl< Dim >::~IntCICImpl () inline
Definition at line 42 of file IntCIC.h.
Member Function Documentation
gather() [1/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntCICImpl< Dim >::gather (FT & , const Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh) inline static
Definition at line 145 of file IntCIC.h.
References Dim, endl(), ERRORMSG, FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::moveBy().
Referenced by IntCIC::gather().
gather() [2/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntCICImpl< Dim >::gather (FT & , const Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh, NDIndex< Dim > & ngp, int lgpoff[Dim], Vektor< PT, Dim > & dpos) inline static
Definition at line 186 of file IntCIC.h.
References Dim, endl(), ERRORMSG, FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::moveBy().
gather() [3/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntCICImpl< Dim >::gather (FT & , const Field< FT, Dim, M, C > & f, const NDIndex< Dim > & ngp, const int lgpoff[Dim], const Vektor< PT, Dim > &) inline static
Definition at line 225 of file IntCIC.h.
References endl(), ERRORMSG, Interpolator::getFieldIter(), and BrickIterator< T, Dim >::moveBy().
scatter() [1/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntCICImpl< Dim >::scatter (const FT & , Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh) inline static
Definition at line 49 of file IntCIC.h.
References Dim, endl(), ERRORMSG, FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::moveBy().
Referenced by IntCIC::scatter().
scatter() [2/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntCICImpl< Dim >::scatter (const FT & , Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh, NDIndex< Dim > & ngp, int lgpoff[Dim], Vektor< PT, Dim > & dpos) inline static
Definition at line 90 of file IntCIC.h.
References Dim, endl(), ERRORMSG, FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::moveBy().
scatter() [3/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntCICImpl< Dim >::scatter (const FT & , Field< FT, Dim, M, C > & f, const NDIndex< Dim > & ngp, const int lgpoff[Dim], const Vektor< PT, Dim > &) inline static
Definition at line 129 of file IntCIC.h.
References endl(), ERRORMSG, Interpolator::getFieldIter(), and BrickIterator< T, Dim >::moveBy().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/IntCIC.h