OPAL (Object Oriented Parallel Accelerator Library): BCondBase< T, D, M, C > Class Template Reference
BCondBase< T, D, M, C > Class Template Reference abstract
#include <BCond.h>
Public Member Functions
BCondBase (unsigned int face, int i=allComponents, int j=allComponents)
virtual ~BCondBase ()
virtual void apply (Field< T, D, M, C > &)=0
virtual BCondBase< T, D, M, C > * clone () const =0
virtual void write (std::ostream &) const
int getComponent () const
unsigned int getFace () const
bool changesPhysicalCells () const
Public Member Functions inherited from RefCounted
RefCounted ()
Static Public Attributes
static int allComponents = -9999
Protected Attributes
int m_component
unsigned int m_face
bool m_changePhysical
Additional Inherited Members
Public Attributes inherited from RefCounted
int RefCount
Detailed Description
template<class T, unsigned D, class M, class C>
class BCondBase< T, D, M, C >
Definition at line 28 of file BCond.h.
Constructor & Destructor Documentation
BCondBase()
template<class T , unsigned int D, class M , class C > BCondBase< T, D, M, C >::BCondBase (unsigned int face, int i = allComponents, int j = allComponents)
Definition at line 56 of file BCond.hpp.
References endl(), ERRORMSG, get_tag(), getTensorOrder(), IPPL_ANTISYMTENSOR, IPPL_SYMTENSOR, IPPL_TENSOR, BCondBase< T, D, M, C >::m_component, PAssert_GT, and Attrib::Legacy::Distribution::T.
~BCondBase()
template<class T , unsigned D, class M , class C > virtual BCondBase< T, D, M, C >::~BCondBase () inline virtual
Definition at line 161 of file BCond.h.
Member Function Documentation
apply()
template<class T , unsigned D, class M , class C > virtual void BCondBase< T, D, M, C >::apply (Field< T, D, M, C > &) pure virtual
Implemented in PatchBC< T, D, M, C >, ComponentLinearExtrapolateFace< T, D, M, C >, LinearExtrapolateFace< T, D, M, C >, EurekaFace< T, D, M, C >, ComponentFunctionFace< T, D, M, C >, FunctionFace< T, D, M, C >, ExtrapolateAndZeroFace< T, D, M, C >, ExtrapolateFace< T, D, M, C >, ParallelInterpolationFace< T, D, M, C >, ParallelPeriodicFace< T, D, M, C >, InterpolationFace< T, D, M, C >, PeriodicFace< T, D, M, C >, and BCondNoAction< T, D, M, C >.
changesPhysicalCells()
template<class T , unsigned D, class M , class C > bool BCondBase< T, D, M, C >::changesPhysicalCells () const inline
Definition at line 175 of file BCond.h.
References BCondBase< T, D, M, C >::m_changePhysical.
clone()
template<class T , unsigned D, class M , class C > virtual BCondBase<T,D,M,C>* BCondBase< T, D, M, C >::clone () const pure virtual
Implemented in ComponentLinearExtrapolateFace< T, D, M, C >, LinearExtrapolateFace< T, D, M, C >, EurekaFace< T, D, M, C >, ComponentFunctionFace< T, D, M, C >, FunctionFace< T, D, M, C >, ExtrapolateAndZeroFace< T, D, M, C >, ExtrapolateFace< T, D, M, C >, ParallelInterpolationFace< T, D, M, C >, ParallelPeriodicFace< T, D, M, C >, InterpolationFace< T, D, M, C >, PeriodicFace< T, D, M, C >, and BCondNoAction< T, D, M, C >.
getComponent()
template<class T , unsigned D, class M , class C > int BCondBase< T, D, M, C >::getComponent () const inline
Definition at line 169 of file BCond.h.
References BCondBase< T, D, M, C >::m_component.
Referenced by ComponentFunctionFaceBCApply(), ExtrapolateAndZeroFaceBCApply2(), ExtrapolateAndZeroFaceBCApply3(), ExtrapolateFaceBCApply2(), InterpolationFaceBCApply(), and PeriodicFaceBCApply().
getFace()
template<class T , unsigned D, class M , class C > unsigned int BCondBase< T, D, M, C >::getFace () const inline
Definition at line 172 of file BCond.h.
References BCondBase< T, D, M, C >::m_face.
Referenced by CalcParallelInterpolationDomain(), CalcParallelPeriodicDomain(), ComponentFunctionFaceBCApply(), ExtrapolateAndZeroFaceBCApply(), ExtrapolateFaceBCApply(), FunctionFaceBCApply(), InterpolationFaceBCApply(), LinearExtrapolateFaceBCApply(), PeriodicFaceBCApply(), and PatchBC< T, D, M, C >::write().
write()
template<class T , unsigned int D, class M , class C > void BCondBase< T, D, M, C >::write (std::ostream & out) const virtual
Reimplemented in PatchBC< T, D, M, C >, ComponentLinearExtrapolateFace< T, D, M, C >, LinearExtrapolateFace< T, D, M, C >, EurekaFace< T, D, M, C >, ComponentFunctionFace< T, D, M, C >, FunctionFace< T, D, M, C >, ZeroGuardsAndZeroFace< T, D, M, C >, ZeroFace< T, D, M, C >, ConstantFace< T, D, M, C >, NegReflectAndZeroFace< T, D, M, C >, NegReflectFace< T, D, M, C >, PosReflectFace< T, D, M, C >, ExtrapolateAndZeroFace< T, D, M, C >, ExtrapolateFace< T, D, M, C >, ParallelInterpolationFace< T, D, M, C >, ParallelPeriodicFace< T, D, M, C >, InterpolationFace< T, D, M, C >, PeriodicFace< T, D, M, C >, and BCondNoAction< T, D, M, C >.
Definition at line 107 of file BCond.hpp.
Member Data Documentation
allComponents
template<class T , unsigned D, class M , class C > int BCondBase< T, D, M, C >::allComponents = -9999 static
Definition at line 152 of file BCond.h.
m_changePhysical
template<class T , unsigned D, class M , class C > bool BCondBase< T, D, M, C >::m_changePhysical protected
Definition at line 187 of file BCond.h.
Referenced by BCondBase< T, D, M, C >::changesPhysicalCells().
m_component
template<class T , unsigned D, class M , class C > int BCondBase< T, D, M, C >::m_component protected
Definition at line 181 of file BCond.h.
Referenced by BCondBase< T, D, M, C >::BCondBase(), and BCondBase< T, D, M, C >::getComponent().
m_face
template<class T , unsigned D, class M , class C > unsigned int BCondBase< T, D, M, C >::m_face protected
Definition at line 184 of file BCond.h.
Referenced by BCondBase< T, D, M, C >::getFace().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BCond.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BCond.hpp