OPAL (Object Oriented Parallel Accelerator Library): Solenoid Class Reference
Solenoid Class Reference abstract
Interface for solenoids.
#include <Solenoid.h>
Public Member Functions
Solenoid (const std::string &name)
Constructor with given name.
Solenoid ()
Solenoid (const Solenoid &)
virtual ~Solenoid ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to Solenoid.
virtual double getBz () const =0
Get solenoid field Bz in Teslas.
void setKS (double ks)
void setDKS (double ks)
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void finalise () override
virtual bool bends () const override
virtual void goOnline (const double &kineticEnergy) override
virtual void goOffline () override
void setFieldMapFN (std::string fn)
void setFast (bool fast)
bool getFast () const
virtual ElementBase::ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
virtual bool isInside (const Vector_t &r) const override
virtual void getElementDimensions (double &zBegin, double &zEnd) const override
virtual CoordinateSystemTrafo getEdgeToBegin () const override
virtual CoordinateSystemTrafo getEdgeToEnd () const override
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
virtual EMField & getField ()=0
Return field.
virtual const EMField & getField () const =0
Return field.
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual bool Online ()
virtual void setComponentType (std::string)
virtual std::string getComponentType () const
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void operator= (const Solenoid &)
Private Attributes
std::string filename_m
Fieldmap * myFieldmap_m
double scale_m
double scaleError_m
double startField_m
bool fast_m
Additional Inherited Members
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Interface for solenoids.
Definition at line 36 of file Solenoid.h.
Constructor & Destructor Documentation
Solenoid() [1/3]
Solenoid::Solenoid (const std::string & name) explicit
Constructor with given name.
Definition at line 51 of file Solenoid.cpp.
Solenoid() [2/3]
Solenoid::Solenoid ()
Definition at line 35 of file Solenoid.cpp.
Solenoid() [3/3]
Solenoid::Solenoid (const Solenoid & right)
Definition at line 40 of file Solenoid.cpp.
~Solenoid()
Solenoid::~Solenoid () virtual
Definition at line 62 of file Solenoid.cpp.
Member Function Documentation
accept()
void Solenoid::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to Solenoid.
Implements ElementBase.
Definition at line 67 of file Solenoid.cpp.
References BeamlineVisitor::visitSolenoid().
apply() [1/2]
bool Solenoid::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 84 of file Solenoid.cpp.
References PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::R, and Component::RefPartBunch_m.
apply() [2/2]
bool Solenoid::apply (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 88 of file Solenoid.cpp.
References ElementBase::getElementLength(), Fieldmap::getFieldstrength(), myFieldmap_m, Attrib::Distribution::R, scale_m, scaleError_m, and startField_m.
applyToReferenceParticle()
bool Solenoid::applyToReferenceParticle (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 102 of file Solenoid.cpp.
References ElementBase::getElementLength(), Fieldmap::getFieldstrength(), myFieldmap_m, Attrib::Distribution::R, scale_m, and startField_m.
bends()
bool Solenoid::bends () const override virtual
Implements Component.
Definition at line 142 of file Solenoid.cpp.
finalise()
void Solenoid::finalise () override virtual
Implements Component.
Definition at line 139 of file Solenoid.cpp.
getBz()
virtual double Solenoid::getBz () const pure virtual
Get solenoid field Bz in Teslas.
Implemented in SolenoidRep.
getDimensions()
void Solenoid::getDimensions (double & zBegin, double & zEnd) const override virtual
Implements Component.
Definition at line 165 of file Solenoid.cpp.
References ElementBase::getElementLength(), and startField_m.
getEdgeToBegin()
CoordinateSystemTrafo Solenoid::getEdgeToBegin () const inline override virtual
Reimplemented from ElementBase.
Definition at line 108 of file Solenoid.h.
References startField_m.
getEdgeToEnd()
CoordinateSystemTrafo Solenoid::getEdgeToEnd () const inline override virtual
Reimplemented from ElementBase.
Definition at line 117 of file Solenoid.h.
References ElementBase::getElementLength(), and startField_m.
getElementDimensions()
void Solenoid::getElementDimensions (double & zBegin, double & zEnd) const override virtual
Reimplemented from ElementBase.
Definition at line 180 of file Solenoid.cpp.
References begin(), end(), ElementBase::getElementLength(), and startField_m.
getFast()
bool Solenoid::getFast () const
Definition at line 80 of file Solenoid.cpp.
References fast_m.
getType()
ElementBase::ElementType Solenoid::getType () const override virtual
Get element type std::string.
Reimplemented from Component.
Definition at line 171 of file Solenoid.cpp.
References ElementBase::SOLENOID.
goOffline()
void Solenoid::goOffline () override virtual
Reimplemented from Component.
Definition at line 152 of file Solenoid.cpp.
References filename_m, Fieldmap::freeMap(), and Component::online_m.
goOnline()
void Solenoid::goOnline (const double & kineticEnergy) override virtual
Reimplemented from Component.
Definition at line 147 of file Solenoid.cpp.
References filename_m, Component::online_m, and Fieldmap::readMap().
initialise()
void Solenoid::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Implements Component.
Definition at line 117 of file Solenoid.cpp.
References fast_m, filename_m, ElementBase::getElementLength(), Fieldmap::getFieldDimensions(), Fieldmap::getFieldmap(), Fieldmap::getInfo(), ElementBase::getName(), gmsg, level2(), myFieldmap_m, Component::RefPartBunch_m, ElementBase::setElementLength(), and startField_m.
isInside()
bool Solenoid::isInside (const Vector_t & r) const override virtual
Reimplemented from ElementBase.
Definition at line 175 of file Solenoid.cpp.
References Fieldmap::isInside(), ElementBase::isInsideTransverse(), and myFieldmap_m.
operator=()
void Solenoid::operator= (const Solenoid &) private
setDKS()
void Solenoid::setDKS (double ks)
Definition at line 161 of file Solenoid.cpp.
References scaleError_m.
Referenced by OpalSolenoid::update().
setFast()
void Solenoid::setFast (bool fast)
Definition at line 75 of file Solenoid.cpp.
References fast_m.
Referenced by OpalSolenoid::update().
setFieldMapFN()
void Solenoid::setFieldMapFN (std::string fn)
Definition at line 71 of file Solenoid.cpp.
References filename_m.
Referenced by OpalSolenoid::update().
setKS()
void Solenoid::setKS (double ks)
Definition at line 157 of file Solenoid.cpp.
References scale_m.
Referenced by OpalSolenoid::update().
Member Data Documentation
fast_m
bool Solenoid::fast_m private
Definition at line 100 of file Solenoid.h.
Referenced by getFast(), initialise(), and setFast().
filename_m
std::string Solenoid::filename_m private
The name of the inputfile
Definition at line 93 of file Solenoid.h.
Referenced by goOffline(), goOnline(), initialise(), and setFieldMapFN().
myFieldmap_m
Fieldmap* Solenoid::myFieldmap_m private
Definition at line 94 of file Solenoid.h.
Referenced by apply(), applyToReferenceParticle(), initialise(), and isInside().
scale_m
double Solenoid::scale_m private
scale multiplier
Definition at line 95 of file Solenoid.h.
Referenced by apply(), applyToReferenceParticle(), and setKS().
scaleError_m
double Solenoid::scaleError_m private
scale multiplier error
Definition at line 96 of file Solenoid.h.
Referenced by apply(), and setDKS().
startField_m
double Solenoid::startField_m private
startingpoint of field, m
Definition at line 98 of file Solenoid.h.
Referenced by apply(), applyToReferenceParticle(), getDimensions(), getEdgeToBegin(), getEdgeToEnd(), getElementDimensions(), and initialise().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/Solenoid.h
src/Classic/AbsBeamline/Solenoid.cpp