OPAL (Object Oriented Parallel Accelerator Library): OpalRBend Class Reference
OpalRBend Class Reference
#include <OpalRBend.h>
Public Member Functions
OpalRBend ()
Exemplar constructor.
virtual ~OpalRBend ()
virtual OpalRBend * clone (const std::string &name)
Make clone.
virtual void update ()
Update the embedded CLASSIC bend.
Public Member Functions inherited from OpalBend
OpalBend (const char *name, const char *help)
Exemplar constructor.
virtual ~OpalBend ()
virtual void print (std::ostream &) const
Print the bend magnet.
Public Member Functions inherited from OpalElement
virtual ~OpalElement ()
virtual double getLength () const
Return element length.
const std::string getTypeName () const
Return the element's type name.
std::pair< ElementBase::ApertureType, std::vector< double > > getApert () const
const std::string getWakeF () const
Return the element's type name.
const std::string getParticleMatterInteraction () const
const std::string getWMaterial () const
const std::string getWakeGeom () const
std::vector< double > getWakeParam () const
const std::string getWakeConductivity () const
virtual void parse (Statement &)
Parse the element.
virtual void updateUnknown (ElementBase *)
Transmit the `‘unknown’' (not known to OPAL) attributes to CLASSIC.
Public Member Functions inherited from Element
virtual ~Element ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual double getEntrance (ReferenceType) const
Return arc length from origin to entrance (negative !).
virtual double getExit (ReferenceType) const
Return arc length from origin to exit (positive !).
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded CLASSIC element.
void setElement (ElementBase *)
Assign new CLASSIC element.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
OpalRBend (const OpalRBend &)
void operator= (const OpalRBend &)
OpalRBend (const std::string &name, OpalRBend *parent)
Private Attributes
OpalWake * owk_m
ParticleMatterInteraction * parmatint_m
Additional Inherited Members
Public Types inherited from OpalBend
enum {
ANGLE = COMMON, K0, K0S, K1,
K1S, K2, K2S, K3,
K3S, E1, E2, H1,
H2, HGAP, FINT, SLICES,
STEPSIZE, FMAPFN, GAP, HAPERT,
ROTATION, DESIGNENERGY, GREATERTHANPI, NSLICES,
SIZE
}
The attribute numbers for OPAL bend magnets.
Public Types inherited from OpalElement
enum {
TYPE, APERT, LENGTH, ELEMEDGE,
WAKEF, PARTICLEMATTERINTERACTION, ORIGIN, ORIENTATION,
X, Y, Z, THETA,
PHI, PSI, DX, DY,
DZ, DTHETA, DPHI, DPSI,
OUTFN, COMMON
}
The common attributes for all elements.
Public Types inherited from Element
enum ReferenceType { IS_ENTRY, IS_CENTRE, IS_EXIT }
Reference for element positioning.
Static Public Member Functions inherited from Element
static Element * find (const std::string &name)
Find named Element.
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from OpalBend
OpalBend (const std::string &name, OpalBend *parent)
Clone constructor.
Protected Member Functions inherited from OpalElement
OpalElement (int size, const char *name, const char *help)
Exemplar constructor.
OpalElement (const std::string &name, OpalElement *parent)
Clone constructor.
void registerOwnership () const
Protected Member Functions inherited from Element
Element (int size, const char *name, const char *help)
Constructor for exemplars.
Element (const std::string &name, Element *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Static Protected Member Functions inherited from OpalElement
static void printMultipoleStrength (std::ostream &os, int order, int &len, const std::string &sName, const std::string &tName, const Attribute &length, const Attribute &vNorm, const Attribute &vSkew)
Print multipole components in OPAL-8 format.
static void printAttribute (std::ostream &os, const std::string &name, const std::string &image, int &len)
Print an attribute with a OPAL-8 name (as an expression).
static void printAttribute (std::ostream &os, const std::string &name, double value, int &len)
Print an attribute with a OPAL-8 name (as a constant).
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 26 of file OpalRBend.h.
Constructor & Destructor Documentation
OpalRBend() [1/3]
OpalRBend::OpalRBend ()
Exemplar constructor.
Definition at line 28 of file OpalRBend.cpp.
References OpalElement::registerOwnership(), and Element::setElement().
Referenced by clone().
~OpalRBend()
OpalRBend::~OpalRBend () virtual
Definition at line 48 of file OpalRBend.cpp.
References owk_m, and parmatint_m.
OpalRBend() [2/3]
OpalRBend::OpalRBend (const OpalRBend &) private
OpalRBend() [3/3]
OpalRBend::OpalRBend (const std::string & name, OpalRBend * parent) private
Definition at line 40 of file OpalRBend.cpp.
References name, and Element::setElement().
Member Function Documentation
clone()
OpalRBend * OpalRBend::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 54 of file OpalRBend.cpp.
References name, and OpalRBend().
Referenced by update().
operator=()
void OpalRBend::operator= (const OpalRBend &) private
update()
void OpalRBend::update () virtual
Update the embedded CLASSIC bend.
Reimplemented from OpalElement.
Definition at line 59 of file OpalRBend.cpp.
References OpalBend::ANGLE, OpalElement::APERT, Physics::c, clone(), ParticleMatterInteraction::clone(), OpalBend::DESIGNENERGY, OpalBend::E1, OpalBend::E2, endl(), ERRORMSG, OpalWake::find(), ParticleMatterInteraction::find(), ElementBase::fixPosition(), OpalBend::FMAPFN, OpalBend::GAP, ElementBase::getCSTrafoGlobal2Local(), Element::getElement(), RBendRep::getGeometry(), OpalData::getInstance(), ElementBase::getName(), Object::getOpalName(), CoordinateSystemTrafo::getOrigin(), OpalData::getP0(), Attributes::getReal(), CoordinateSystemTrafo::getRotation(), Attributes::getString(), OpalBend::H1, OpalBend::H2, ParticleMatterInteraction::handler_m, OpalBend::HAPERT, ParticleMatterInteraction::initParticleMatterInteractionHandler(), OpalWake::initWakefunction(), ElementBase::isPositioned(), Object::itsAttr, OpalBend::K0, OpalBend::K0S, OpalBend::K1, OpalBend::K1S, OpalBend::K2, OpalBend::K2S, OpalBend::K3, OpalBend::K3S, OpalElement::LENGTH, OpalBend::NSLICES, owk_m, parmatint_m, OpalElement::PARTICLEMATTERINTERACTION, ElementBase::RECTANGULAR, ElementBase::releasePosition(), OpalBend::ROTATION, ElementBase::setAperture(), RBendGeometry::setBendAngle(), RBend::setBendAngle(), ElementBase::setCSTrafoGlobal2Local(), BendBase::setDesignEnergy(), StraightGeometry::setElementLength(), RBend::setEntranceAngle(), RBendRep::setEntryFaceCurvature(), RBendRep::setEntryFaceRotation(), RBendRep::setExitFaceCurvature(), RBendRep::setExitFaceRotation(), RBendRep::setField(), BendBase::setFieldAmplitude(), BendBase::setFieldMapFN(), BendBase::setFullGap(), Bend2D::setK1(), BMultipoleField::setNormalComponent(), Bend2D::setNSlices(), ElementBase::setParticleMatterInteraction(), BMultipoleField::setSkewComponent(), RBendRep::setSlices(), RBendRep::setStepsize(), ElementBase::setWake(), sin(), OpalBend::SLICES, OpalBend::STEPSIZE, OpalElement::update(), OpalElement::updateUnknown(), OpalElement::WAKEF, and OpalWake::wf_m.
Member Data Documentation
owk_m
OpalWake* OpalRBend::owk_m private
Definition at line 50 of file OpalRBend.h.
Referenced by update(), and ~OpalRBend().
parmatint_m
ParticleMatterInteraction* OpalRBend::parmatint_m private
Definition at line 51 of file OpalRBend.h.
Referenced by update(), and ~OpalRBend().
The documentation for this class was generated from the following files:
src/Elements/OpalRBend.h
src/Elements/OpalRBend.cpp