OPAL (Object Oriented Parallel Accelerator Library): FlexibleCollimator Class Reference
FlexibleCollimator Class Reference
#include <FlexibleCollimator.h>
Public Member Functions
FlexibleCollimator (const std::string &name)
Constructor with given name.
FlexibleCollimator ()
FlexibleCollimator (const FlexibleCollimator &rhs)
virtual ~FlexibleCollimator ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to FlexibleCollimator.
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual bool checkCollimator (PartBunchBase< double, 3 > *bunch, const int turnnumber, const double t, const double tstep)
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void initialise (PartBunchBase< double, 3 > *bunch)
virtual void finalise () override
virtual bool bends () const override
virtual void goOnline (const double &kineticEnergy) override
virtual void goOffline () override
virtual ElementBase::ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
void print ()
unsigned int getLosses () const
void setDescription (const std::string &desc)
std::string getDescription () const
bool isStopped (const Vector_t &R)
void writeHolesAndQuadtree (const std::string &baseFilename) const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
virtual EMField & getField ()=0
Return field.
virtual const EMField & getField () const =0
Return field.
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual bool Online ()
virtual void setComponentType (std::string)
virtual std::string getComponentType () const
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void operator= (const FlexibleCollimator &)
Private Attributes
std::string description_m
std::vector< std::shared_ptr< mslang::Base > > holes_m
mslang::BoundingBox bb_m
mslang::QuadTree tree_m
bool informed_m
unsigned int losses_m
std::unique_ptr< LossDataSink > lossDs_m
ParticleMatterInteractionHandler * parmatint_m
Additional Inherited Members
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 31 of file FlexibleCollimator.h.
Constructor & Destructor Documentation
FlexibleCollimator() [1/3]
FlexibleCollimator::FlexibleCollimator (const std::string & name) explicit
Constructor with given name.
Definition at line 59 of file FlexibleCollimator.cpp.
FlexibleCollimator() [2/3]
FlexibleCollimator::FlexibleCollimator ()
Definition at line 34 of file FlexibleCollimator.cpp.
FlexibleCollimator() [3/3]
FlexibleCollimator::FlexibleCollimator (const FlexibleCollimator & rhs)
Definition at line 39 of file FlexibleCollimator.cpp.
References mslang::QuadTree::bb_m, bb_m, mslang::QuadTree::buildUp(), holes_m, mslang::QuadTree::objects_m, and tree_m.
~FlexibleCollimator()
FlexibleCollimator::~FlexibleCollimator () virtual
Definition at line 69 of file FlexibleCollimator.cpp.
References goOffline(), and Component::online_m.
Member Function Documentation
accept()
void FlexibleCollimator::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to FlexibleCollimator.
Implements ElementBase.
Definition at line 79 of file FlexibleCollimator.cpp.
References BeamlineVisitor::visitFlexibleCollimator().
apply()
bool FlexibleCollimator::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 102 of file FlexibleCollimator.cpp.
References Physics::c, dot(), PartBunchBase< T, Dim >::dt, PartBunchBase< T, Dim >::ID, isStopped(), lossDs_m, losses_m, PartBunchBase< T, Dim >::M, PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::Q, Attrib::Distribution::R, PartBunchBase< T, Dim >::R, Component::RefPartBunch_m, and sqrt().
applyToReferenceParticle()
bool FlexibleCollimator::applyToReferenceParticle (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 123 of file FlexibleCollimator.cpp.
bends()
bool FlexibleCollimator::bends () const inline override virtual
Implements Component.
Definition at line 101 of file FlexibleCollimator.h.
checkCollimator()
bool FlexibleCollimator::checkCollimator (PartBunchBase< double, 3 > * bunch, const int turnnumber, const double t, const double tstep) virtual
Definition at line 134 of file FlexibleCollimator.cpp.
finalise()
void FlexibleCollimator::finalise () override virtual
Implements Component.
Definition at line 163 of file FlexibleCollimator.cpp.
References endl(), ElementBase::getName(), gmsg, goOffline(), and Component::online_m.
getDescription()
std::string FlexibleCollimator::getDescription () const inline
Definition at line 106 of file FlexibleCollimator.h.
References description_m.
getDimensions()
void FlexibleCollimator::getDimensions (double & zBegin, double & zEnd) const override virtual
Implements Component.
Definition at line 200 of file FlexibleCollimator.cpp.
References ElementBase::getElementLength().
getLosses()
unsigned int FlexibleCollimator::getLosses () const inline
Definition at line 96 of file FlexibleCollimator.h.
References losses_m.
Referenced by ParallelTTracker::writePhaseSpace().
getType()
ElementBase::ElementType FlexibleCollimator::getType () const override virtual
Get element type std::string.
Reimplemented from Component.
Definition at line 205 of file FlexibleCollimator.cpp.
References ElementBase::FLEXIBLECOLLIMATOR.
goOffline()
void FlexibleCollimator::goOffline () override virtual
Reimplemented from Component.
Definition at line 193 of file FlexibleCollimator.cpp.
References lossDs_m, and Component::online_m.
Referenced by finalise(), and ~FlexibleCollimator().
goOnline()
void FlexibleCollimator::goOnline (const double & kineticEnergy) override virtual
Reimplemented from Component.
Definition at line 169 of file FlexibleCollimator.cpp.
References Component::online_m, and print().
Referenced by initialise().
initialise() [1/2]
void FlexibleCollimator::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Implements Component.
Definition at line 142 of file FlexibleCollimator.cpp.
References Options::asciidump, ElementBase::getElementLength(), ElementBase::getOutputFN(), ElementBase::getParticleMatterInteraction(), goOnline(), lossDs_m, parmatint_m, and Component::RefPartBunch_m.
initialise() [2/2]
void FlexibleCollimator::initialise (PartBunchBase< double, 3 > * bunch) virtual
Definition at line 153 of file FlexibleCollimator.cpp.
References Options::asciidump, ElementBase::getOutputFN(), ElementBase::getParticleMatterInteraction(), goOnline(), lossDs_m, parmatint_m, and Component::RefPartBunch_m.
isStopped()
bool FlexibleCollimator::isStopped (const Vector_t & R)
Definition at line 84 of file FlexibleCollimator.cpp.
References bb_m, ElementBase::getElementLength(), mslang::BoundingBox::isInside(), mslang::QuadTree::isInside(), ElementBase::isInsideTransverse(), Attrib::Distribution::R, and tree_m.
Referenced by apply().
operator=()
void FlexibleCollimator::operator= (const FlexibleCollimator &) private
print()
void FlexibleCollimator::print ()
Definition at line 175 of file FlexibleCollimator.cpp.
References endl(), ERRORMSG, gmsg, informed_m, level3(), IpplInfo::myNode(), Component::RefPartBunch_m, and Fieldmap::typeset_msg().
Referenced by goOnline().
setDescription()
void FlexibleCollimator::setDescription (const std::string & desc)
Definition at line 209 of file FlexibleCollimator.cpp.
References mslang::Function::apply(), mslang::QuadTree::bb_m, bb_m, mslang::QuadTree::buildUp(), mslang::BoundingBox::center_m, Physics::e, mslang::BoundingBox::height_m, holes_m, max(), min(), mslang::QuadTree::objects_m, mslang::parse(), mslang::QuadTree::reset(), tree_m, and mslang::BoundingBox::width_m.
Referenced by OpalECollimator::update(), OpalSlit::update(), OpalRCollimator::update(), OpalFlexibleCollimator::update(), and OpalPepperPot::update().
writeHolesAndQuadtree()
void FlexibleCollimator::writeHolesAndQuadtree (const std::string & baseFilename) const
Definition at line 262 of file FlexibleCollimator.cpp.
References Util::combineFilePath(), OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), holes_m, IpplInfo::myNode(), tree_m, and mslang::QuadTree::writeGnuplot().
Referenced by OpalFlexibleCollimator::update().
Member Data Documentation
bb_m
mslang::BoundingBox FlexibleCollimator::bb_m private
Definition at line 85 of file FlexibleCollimator.h.
Referenced by FlexibleCollimator(), isStopped(), and setDescription().
description_m
std::string FlexibleCollimator::description_m private
Definition at line 83 of file FlexibleCollimator.h.
Referenced by getDescription().
holes_m
std::vector<std::shared_ptr<mslang::Base> > FlexibleCollimator::holes_m private
Definition at line 84 of file FlexibleCollimator.h.
Referenced by FlexibleCollimator(), setDescription(), and writeHolesAndQuadtree().
informed_m
bool FlexibleCollimator::informed_m private
Definition at line 88 of file FlexibleCollimator.h.
Referenced by print().
lossDs_m
std::unique_ptr<LossDataSink> FlexibleCollimator::lossDs_m private
Definition at line 90 of file FlexibleCollimator.h.
Referenced by apply(), goOffline(), and initialise().
losses_m
unsigned int FlexibleCollimator::losses_m private
Definition at line 89 of file FlexibleCollimator.h.
Referenced by apply(), and getLosses().
parmatint_m
ParticleMatterInteractionHandler* FlexibleCollimator::parmatint_m private
Definition at line 92 of file FlexibleCollimator.h.
Referenced by initialise().
tree_m
mslang::QuadTree FlexibleCollimator::tree_m private
Definition at line 86 of file FlexibleCollimator.h.
Referenced by FlexibleCollimator(), isStopped(), setDescription(), and writeHolesAndQuadtree().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/FlexibleCollimator.h
src/Classic/AbsBeamline/FlexibleCollimator.cpp