OPAL (Object Oriented Parallel Accelerator Library): GreenWakeFunction::Wake Class Reference
GreenWakeFunction::Wake Class Reference
Public Member Functions
Wake (double s, double Z0, double a, double sigma, int acMode, double tau, WakeDirection direction)
double operator() (double k)
Used to integrate the function.
Private Attributes
double Z0_
impedance
double a_
radius
double sigma_
material constant
double s_
distance from the particle
int acMode_
conductivity either 1="AC" or 2="DC"
double tau_
material constant
WakeDirection direction_
direction either 1="Longitudinal" 0= "Transversal"
Detailed Description
Definition at line 70 of file GreenWakeFunction.h.
Constructor & Destructor Documentation
Wake()
GreenWakeFunction::Wake::Wake (double s, double Z0, double a, double sigma, int acMode, double tau, WakeDirection direction) inline
Definition at line 73 of file GreenWakeFunction.h.
Member Function Documentation
operator()()
double GreenWakeFunction::Wake::operator() (double k) inline
Used to integrate the function.
Parameters
[in] k parameter
Returns
the function value at position k
Definition at line 84 of file GreenWakeFunction.h.
References a_, abs(), acMode_, Physics::c, cos(), direction_, endl(), ERRORMSG, LONGITUDINAL, Physics::pi, real(), s_, sigma_, sqrt(), tau_, TRANSVERSAL, and Z0_.
Member Data Documentation
a_
double GreenWakeFunction::Wake::a_ private
radius
Definition at line 117 of file GreenWakeFunction.h.
Referenced by operator()().
acMode_
int GreenWakeFunction::Wake::acMode_ private
conductivity either 1="AC" or 2="DC"
Definition at line 123 of file GreenWakeFunction.h.
Referenced by operator()().
direction_
WakeDirection GreenWakeFunction::Wake::direction_ private
direction either 1="Longitudinal" 0= "Transversal"
Definition at line 127 of file GreenWakeFunction.h.
Referenced by operator()().
s_
double GreenWakeFunction::Wake::s_ private
distance from the particle
Definition at line 121 of file GreenWakeFunction.h.
Referenced by operator()().
sigma_
double GreenWakeFunction::Wake::sigma_ private
material constant
Definition at line 119 of file GreenWakeFunction.h.
Referenced by operator()().
tau_
double GreenWakeFunction::Wake::tau_ private
material constant
Definition at line 125 of file GreenWakeFunction.h.
Referenced by operator()().
Z0_
double GreenWakeFunction::Wake::Z0_ private
impedance
Definition at line 115 of file GreenWakeFunction.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Solvers/GreenWakeFunction.h