OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Utility/IpplInfo.cpp File Reference
IpplInfo.cpp File Reference
#include "Utility/IpplInfo.h"
#include "Utility/Inform.h"
#include "Utility/IpplStats.h"
#include "Utility/PAssert.h"
#include "Utility/RandomNumberGen.h"
#include "Utility/vmap.h"
#include "DataSource/DataConnectCreator.h"
#include "Message/CommCreator.h"
#include "Message/Communicate.h"
#include "IpplVersions.h"
#include <unistd.h>
#include <cstdio>
#include <csignal>
Functions
std::ostream & operator<< (std::ostream &o, const IpplInfo &)
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & o, const IpplInfo &)
Definition at line 118 of file IpplInfo.cpp.
References IpplInfo::chunkSize(), Timer::clock_time(), IpplInfo::Comm, Timer::cpu_time(), IpplInfo::deferGuardCellFills, IpplInfo::extraCompressChecks, IpplInfo::getNodes(), IpplInfo::getSMPNodes(), IpplInfo::getSMPs(), IpplStats::getTime(), IpplInfo::myNode(), IpplInfo::mySMP(), IpplInfo::mySMPNode(), Communicate::name(), IpplInfo::noFieldCompression, IpplInfo::offsetStorage, IpplInfo::perSMPParallelIO(), IpplInfo::retransmit(), IpplInfo::Stats, and IpplInfo::useChecksums().