Option, VERSION=10900;

magnetF: VERTICALFFAMAGNET,
          B0=1,
          FIELD_INDEX=2,
          MAX_HORIZONTAL_POWER=10,
          END_LENGTH=1,
          CENTRE_LENGTH=2,
          HEIGHT_NEG_EXTENT=1,
          HEIGHT_POS_EXTENT=1,
          WIDTH=1,
          BB_LENGTH=1;

ringdef: RINGDEFINITION, HARMONIC_NUMBER=1, LAT_RINIT=5, LAT_PHIINIT=0,
         LAT_THETAINIT=0., BEAM_PHIINIT=0, BEAM_PRINIT=0,
         BEAM_RINIT=0.0, SYMMETRY=1, RFFREQ=1, IS_CLOSED=false,
         MIN_R=0., MAX_R=10;

l1: Line = (ringdef, magnetF);

Dist1: DISTRIBUTION, TYPE=fromfile, FNAME="disttest.dat", INPUTMOUNITS=NONE;

Fs1:FIELDSOLVER, FSTYPE=None, MX=5, MY=5, MT=5,
                 PARFFTX=true, PARFFTY=false, PARFFTT=false,
                 BCFFTX=open, BCFFTY=open, BCFFTT=open,BBOXINCR=2;

//// STEP SIZE ////

beam1: BEAM, MASS=0.938, CHARGE=1, pc=1, NPART=4, BCURRENT=1, CHARGE=1.0, BFREQ=1.0;

TRACK, LINE=l1, BEAM=beam1, MAXSTEPS=1, STEPSPERTURN=1;
RUN, METHOD="CYCLOTRON-T", BEAM=beam1, FIELDSOLVER=Fs1, DISTRIBUTION=Dist1;
ENDTRACK;
STOP;
