OPAL (Object Oriented Parallel Accelerator Library): VariableRFCavityFringeField Class Reference
VariableRFCavityFringeField Class Reference
#include <VariableRFCavityFringeField.h>
Public Member Functions
VariableRFCavityFringeField (const std::string &name)
Constructor with given name.
VariableRFCavityFringeField (const VariableRFCavityFringeField &)
VariableRFCavityFringeField ()
VariableRFCavityFringeField & operator= (const VariableRFCavityFringeField &)
virtual ~VariableRFCavityFringeField ()
virtual void accept (BeamlineVisitor &) const override
void initialise () const
virtual ElementBase * clone () const override
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void setEndField (std::shared_ptr< endfieldmodel::EndFieldModel > endField)
virtual std::shared_ptr< endfieldmodel::EndFieldModel > getEndField () const
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void setCavityCentre (double zCentre)
virtual double getCavityCentre () const
virtual void setMaxOrder (size_t maxOrder)
virtual size_t getMaxOrder () const
void initialiseCoefficients ()
void printCoefficients (std::ostream &out) const
std::vector< std::vector< double > > getEzCoefficients () const
std::vector< std::vector< double > > getEyCoefficients () const
std::vector< std::vector< double > > getBxCoefficients () const
Public Member Functions inherited from VariableRFCavity
VariableRFCavity (const std::string &name)
Constructor with given name.
VariableRFCavity (const VariableRFCavity &)
VariableRFCavity ()
VariableRFCavity & operator= (const VariableRFCavity &)
virtual ~VariableRFCavity ()
virtual void finalise () override
virtual bool bends () const override
virtual void getDimensions (double &, double &) const override
virtual double getAmplitude (double time) const
virtual double getFrequency (double time) const
virtual double getPhase (double time) const
virtual double getHeight () const
virtual double getWidth () const
virtual double getLength () const
virtual void setHeight (double fullHeight)
virtual void setWidth (double fullWidth)
virtual void setLength (double length)
virtual std::shared_ptr< AbstractTimeDependence > getAmplitudeModel () const
virtual std::shared_ptr< AbstractTimeDependence > getPhaseModel () const
virtual std::shared_ptr< AbstractTimeDependence > getFrequencyModel () const
virtual void setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > time_dep)
virtual void setPhaseModel (std::shared_ptr< AbstractTimeDependence > time_dep)
virtual void setFrequencyModel (std::shared_ptr< AbstractTimeDependence > time_dep)
virtual void setAmplitudeName (const std::string &amplitude)
virtual void setPhaseName (const std::string &phase)
virtual void setFrequencyName (const std::string &frequency)
virtual StraightGeometry & getGeometry () override
virtual const StraightGeometry & getGeometry () const override
void initialise () const
virtual EMField & getField () override
Not implemented.
virtual const EMField & getField () const override
Not implemented.
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual ElementType getType () const override
Get element type std::string.
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Attributes
double zCentre_m
size_t maxOrder_m
std::shared_ptr< endfieldmodel::EndFieldModel > endField_m
std::vector< std::vector< double > > f_m
std::vector< std::vector< double > > g_m
std::vector< std::vector< double > > h_m
Protected Attributes inherited from VariableRFCavity
std::shared_ptr< AbstractTimeDependence > phaseTD_m
std::shared_ptr< AbstractTimeDependence > amplitudeTD_m
std::shared_ptr< AbstractTimeDependence > frequencyTD_m
std::string phaseName_m
std::string amplitudeName_m
std::string frequencyName_m
double halfWidth_m
double halfHeight_m
double length_m
TimeDependenceCache frequencyCache_m
StraightGeometry geometry
The cavity's geometry.
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Private Member Functions
void initNull ()
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from VariableRFCavity
void initNull ()
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Generates a field like Ey = E0*a(t)*y^{2n+1} g_n(z) sin{f(t)*t-q(t)} Ez = E0*a(t)*y^{2n} f_n(z) sin{f(t)*t-q(t)} Bx = B0*a(t)*y^{2n+1} h_n(z) cos{f(t)*t-q(t)} where E0, is a user-defined field and B0 is the corresponding magnetic field magnitude; f_n is a user-defined axial field dependence and g_n, h_n are the corresponding off-axis field dependencies. a(t), f(t), q(t) are time dependent amplitude, frequency, phase respectively; it is assumed that these quantities vary sufficiently slowly that Maxwell is satisfied.
Inherits from VariableRFCavity; inheritance is used here to share code from VariableRFCavity.
Set/get methods use metres
Field units are kG and GV/mm
Definition at line 50 of file VariableRFCavityFringeField.h.
Constructor & Destructor Documentation
VariableRFCavityFringeField() [1/3]
VariableRFCavityFringeField::VariableRFCavityFringeField (const std::string & name) explicit
Constructor with given name.
Definition at line 29 of file VariableRFCavityFringeField.cpp.
References initNull().
VariableRFCavityFringeField() [2/3]
VariableRFCavityFringeField::VariableRFCavityFringeField (const VariableRFCavityFringeField & var)
Copy Constructor; performs deepcopy on time-dependence models
Definition at line 37 of file VariableRFCavityFringeField.cpp.
References initNull().
VariableRFCavityFringeField() [3/3]
VariableRFCavityFringeField::VariableRFCavityFringeField ()
Default constructor
Definition at line 33 of file VariableRFCavityFringeField.cpp.
References initNull().
Referenced by clone().
~VariableRFCavityFringeField()
VariableRFCavityFringeField::~VariableRFCavityFringeField () virtual
Destructor does nothing
The shared_ptrs will self-destruct when reference count goes to 0
Definition at line 55 of file VariableRFCavityFringeField.cpp.
Member Function Documentation
accept()
void VariableRFCavityFringeField::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to RFCavity.
The RF cavity finds the "time dependence" models by doing a string lookup against a list held by AbstractTimeDependence at accept time.
Reimplemented from VariableRFCavity.
Definition at line 69 of file VariableRFCavityFringeField.cpp.
References initialise(), initialiseCoefficients(), and BeamlineVisitor::visitVariableRFCavity().
apply() [1/2]
bool VariableRFCavityFringeField::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Calculate the field at the position of the i^th particle
Parameters
i indexes the particle whose field we need
t the time at which the field is calculated
E return value with electric field strength
B return value with magnetic field strength
Returns
True if particle is outside the boundaries; else False
Reimplemented from VariableRFCavity.
Definition at line 139 of file VariableRFCavityFringeField.cpp.
References PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::R, and Component::RefPartBunch_m.
Referenced by applyToReferenceParticle().
apply() [2/2]
bool VariableRFCavityFringeField::apply (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Calculate the field at a given position
Parameters
R the position at which the field is calculated
P the momentum (not used)
t the time at which the field is calculated
E return value; filled with electric field strength
B return value; filled with magnetic field strength
Returns
True if particle is outside the boundaries; else False
Reimplemented from VariableRFCavity.
Definition at line 77 of file VariableRFCavityFringeField.cpp.
References abs(), VariableRFCavity::amplitudeTD_m, cos(), endField_m, f_m, VariableRFCavity::frequencyTD_m, g_m, h_m, VariableRFCavity::halfHeight_m, VariableRFCavity::halfWidth_m, Units::Hz2GHz, VariableRFCavity::length_m, maxOrder_m, Units::MHz2Hz, Hypervolume::n, VariableRFCavity::phaseTD_m, Attrib::Distribution::R, sin(), Units::T2kG, Physics::two_pi, and zCentre_m.
applyToReferenceParticle()
bool VariableRFCavityFringeField::applyToReferenceParticle (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Calculate the field at a given position. This is identical to "apply".
Parameters
R the position at which the field is calculated
P the momentum (not used)
t the time at which the field is calculated
E return value; filled with electric field strength
B return value; filled with magnetic field strength
Returns
True if particle is outside the boundaries; else False
Reimplemented from VariableRFCavity.
Definition at line 144 of file VariableRFCavityFringeField.cpp.
References apply(), and Attrib::Distribution::R.
clone()
ElementBase * VariableRFCavityFringeField::clone () const override virtual
Inheritable deepcopy method
Reimplemented from VariableRFCavity.
Definition at line 58 of file VariableRFCavityFringeField.cpp.
References VariableRFCavityFringeField().
getBxCoefficients()
std::vector< std::vector< double > > VariableRFCavityFringeField::getBxCoefficients () const inline
Get the coefficients for Bx
Definition at line 209 of file VariableRFCavityFringeField.h.
References h_m.
getCavityCentre()
double VariableRFCavityFringeField::getCavityCentre () const inline virtual
Set the offset of centre of the cavity field from the element start in metres
Definition at line 180 of file VariableRFCavityFringeField.h.
References zCentre_m.
getEndField()
std::shared_ptr< endfieldmodel::EndFieldModel > VariableRFCavityFringeField::getEndField () const inline virtual
Get the endFieldModel
Returns
the endFieldModel; VariableRFCavityFringe retains ownership of the memory allocated to the endFieldModel.
Definition at line 197 of file VariableRFCavityFringeField.h.
References endField_m.
getEyCoefficients()
std::vector< std::vector< double > > VariableRFCavityFringeField::getEyCoefficients () const inline
Get the coefficients for Ey
Definition at line 205 of file VariableRFCavityFringeField.h.
References g_m.
getEzCoefficients()
std::vector< std::vector< double > > VariableRFCavityFringeField::getEzCoefficients () const inline
Get the coefficients for Ez
Definition at line 201 of file VariableRFCavityFringeField.h.
References f_m.
getMaxOrder()
size_t VariableRFCavityFringeField::getMaxOrder () const inline virtual
Get the maximum y power that will be used in field calculations
Definition at line 193 of file VariableRFCavityFringeField.h.
References maxOrder_m.
initialise() [1/2]
void VariableRFCavityFringeField::initialise () const inline
Lookup the time dependencies and update.
Throws if the named time dependencies can't be found. Also throws if the width or height is < 1 nm
Definition at line 189 of file VariableRFCavityFringeField.h.
References VariableRFCavity::initialise().
Referenced by accept(), and PyOpal::PyOpalObjectNS::PyOpalObject< C >::doSetup().
initialise() [2/2]
void VariableRFCavityFringeField::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Initialise ready for tracking
Does any setup on VirtualRFCavity and sets field expansion coefficients
Reimplemented from VariableRFCavity.
Definition at line 152 of file VariableRFCavityFringeField.cpp.
References VariableRFCavity::initialise(), and initialiseCoefficients().
initialiseCoefficients()
void VariableRFCavityFringeField::initialiseCoefficients ()
Set the coefficients for calculating the field expansion
Definition at line 169 of file VariableRFCavityFringeField.cpp.
References Physics::c, f_m, g_m, h_m, Units::m2mm, maxOrder_m, Hypervolume::n, and Units::s2ns.
Referenced by accept(), initialise(), and setMaxOrder().
initNull()
void VariableRFCavityFringeField::initNull () private
Definition at line 62 of file VariableRFCavityFringeField.cpp.
References endField_m, VariableRFCavity::initNull(), maxOrder_m, and zCentre_m.
Referenced by VariableRFCavityFringeField().
operator=()
VariableRFCavityFringeField & VariableRFCavityFringeField::operator= (const VariableRFCavityFringeField & rhs)
Assignment operator; performs deepcopy on time-dependence models
Definition at line 42 of file VariableRFCavityFringeField.cpp.
References endField_m, f_m, g_m, h_m, VariableRFCavity::operator=(), setEndField(), and zCentre_m.
printCoefficients()
void VariableRFCavityFringeField::printCoefficients (std::ostream & out) const
Print the coefficients to ostream out
Definition at line 209 of file VariableRFCavityFringeField.cpp.
References endl(), f_m, g_m, h_m, and printVector().
setCavityCentre()
void VariableRFCavityFringeField::setCavityCentre (double zCentre) inline virtual
Get the offset of centre of the cavity field from the element start in metres
Definition at line 176 of file VariableRFCavityFringeField.h.
References zCentre_m.
Referenced by OpalVariableRFCavityFringeField::update().
setEndField()
void VariableRFCavityFringeField::setEndField (std::shared_ptr< endfieldmodel::EndFieldModel > endField) virtual
Set the endFieldModel
Parameters
endField the new endFieldModel. VariableRFCavityFringe takes ownership of the memory allocated to endField.
Definition at line 219 of file VariableRFCavityFringeField.cpp.
References end(), and endField_m.
Referenced by operator=(), and OpalVariableRFCavityFringeField::update().
setMaxOrder()
void VariableRFCavityFringeField::setMaxOrder (size_t maxOrder) inline virtual
Set the maximum y power
Definition at line 184 of file VariableRFCavityFringeField.h.
References initialiseCoefficients(), and maxOrder_m.
Referenced by OpalVariableRFCavityFringeField::update().
Member Data Documentation
endField_m
std::shared_ptr<endfieldmodel::EndFieldModel> VariableRFCavityFringeField::endField_m protected
Definition at line 167 of file VariableRFCavityFringeField.h.
Referenced by apply(), getEndField(), initNull(), operator=(), and setEndField().
f_m
std::vector<std::vector<double> > VariableRFCavityFringeField::f_m protected
Definition at line 168 of file VariableRFCavityFringeField.h.
Referenced by apply(), getEzCoefficients(), initialiseCoefficients(), operator=(), and printCoefficients().
g_m
std::vector<std::vector<double> > VariableRFCavityFringeField::g_m protected
Definition at line 169 of file VariableRFCavityFringeField.h.
Referenced by apply(), getEyCoefficients(), initialiseCoefficients(), operator=(), and printCoefficients().
h_m
std::vector<std::vector<double> > VariableRFCavityFringeField::h_m protected
Definition at line 170 of file VariableRFCavityFringeField.h.
Referenced by apply(), getBxCoefficients(), initialiseCoefficients(), operator=(), and printCoefficients().
maxOrder_m
size_t VariableRFCavityFringeField::maxOrder_m protected
Definition at line 166 of file VariableRFCavityFringeField.h.
Referenced by apply(), getMaxOrder(), initialiseCoefficients(), initNull(), and setMaxOrder().
zCentre_m
double VariableRFCavityFringeField::zCentre_m protected
Definition at line 165 of file VariableRFCavityFringeField.h.
Referenced by apply(), getCavityCentre(), initNull(), operator=(), and setCavityCentre().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/AbsBeamline/VariableRFCavityFringeField.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/AbsBeamline/VariableRFCavityFringeField.cpp