OPAL (Object Oriented Parallel Accelerator Library): SequenceParser Class Reference
SequenceParser Class Reference
The parser for SEQUENCE members.
#include <SequenceParser.h>
Classes
struct Reference
Public Member Functions
SequenceParser (Sequence *)
Constructor.
virtual ~SequenceParser ()
virtual void parse (Statement &) const
Parse sequence member.
Public Member Functions inherited from OpalParser
OpalParser ()
virtual ~OpalParser ()
virtual Statement * readStatement (TokenStream *) const
Read complete statement from a token stream.
virtual void run () const
Read current stream.
virtual void run (TokenStream *) const
Read given stream.
void stop () const
Set stop flag.
Public Member Functions inherited from Parser
Parser ()
virtual ~Parser ()
Private Types
typedef std::list< Reference > RefList
typedef Sequence::TLine TLine
Private Member Functions
SequenceParser ()
SequenceParser (const SequenceParser &)
void operator= (const SequenceParser &)
void fillPositions () const
void findFromPositions () const
void findNeighbourPositions () const
void parseMember (Statement &) const
void parsePosition (Statement &, Object &, bool defined) const
Private Attributes
Sequence * itsSequence
bool okFlag
RefList references
TLine itsLine
Additional Inherited Members
Static Public Member Functions inherited from OpalParser
static Token readToken ()
Return next input token.
Protected Member Functions inherited from OpalParser
void execute (Object *, const std::string &) const
Execute or check the current command.
virtual Object * find (const std::string &) const
Find object by name in the main directory.
virtual void parseAction (Statement &) const
Parse executable command.
virtual void parseAssign (Statement &) const
Parse assignment statement.
virtual void parseDefine (Statement &) const
Parse definition.
virtual void parseEnd (Statement &) const
Check for end of statement.
virtual void parseMacro (const std::string &name, Statement &) const
Parse macro definition or call.
virtual void printHelp (const std::string &) const
Print help on named command.
Detailed Description
The parser for SEQUENCE members.
Definition at line 40 of file SequenceParser.h.
Member Typedef Documentation
RefList
typedef std::list<Reference> SequenceParser::RefList private
Definition at line 71 of file SequenceParser.h.
TLine
typedef Sequence::TLine SequenceParser::TLine private
Definition at line 74 of file SequenceParser.h.
Constructor & Destructor Documentation
SequenceParser() [1/3]
SequenceParser::SequenceParser (Sequence * seq)
Constructor.
Definition at line 38 of file SequenceParser.cpp.
~SequenceParser()
SequenceParser::~SequenceParser () virtual
Definition at line 43 of file SequenceParser.cpp.
SequenceParser() [2/3]
SequenceParser::SequenceParser () private
SequenceParser() [3/3]
SequenceParser::SequenceParser (const SequenceParser &) private
Member Function Documentation
fillPositions()
void SequenceParser::fillPositions () const private
Definition at line 86 of file SequenceParser.cpp.
References SequenceMember::ABSOLUTE, findFromPositions(), findNeighbourPositions(), and references.
Referenced by parse().
findFromPositions()
void SequenceParser::findFromPositions () const private
Definition at line 118 of file SequenceParser.cpp.
References Sequence::findNamedPosition(), itsLine, itsSequence, and references.
Referenced by fillPositions().
findNeighbourPositions()
void SequenceParser::findNeighbourPositions () const private
Definition at line 132 of file SequenceParser.cpp.
References SequenceMember::ABSOLUTE, SequenceMember::DRIFT, SequenceMember::END, Element::find(), Object::findAttribute(), Element::getLength(), Object::getOpalName(), Attributes::getReal(), Attributes::getString(), SequenceMember::IMMEDIATE, Element::IS_CENTRE, Element::IS_ENTRY, Element::IS_EXIT, itsLine, itsSequence, name, SequenceMember::NEXT, SequenceMember::PREVIOUS, Hypervolume::ref, and references.
Referenced by fillPositions().
operator=()
void SequenceParser::operator= (const SequenceParser &) private
parse()
void SequenceParser::parse (Statement & stat) const virtual
Parse sequence member.
Reimplemented from OpalParser.
Definition at line 47 of file SequenceParser.cpp.
References Sequence::addEndMarkers(), fillPositions(), OpalData::getInstance(), Sequence::insertDrifts(), itsLine, itsSequence, Statement::keyword(), OpalData::makeDirty(), okFlag, OpalParser::parseEnd(), parseMember(), Statement::start(), OpalParser::stop(), and Sequence::storeLine().
parseMember()
void SequenceParser::parseMember (Statement & stat) const private
Definition at line 235 of file SequenceParser.cpp.
References Object::clone(), ElementBase::copyStructure(), OpalData::define(), Statement::delimiter(), OpalParser::find(), OpalData::getInstance(), Object::getOpalName(), SequenceMember::GLOBAL, itsLine, itsSequence, SequenceMember::itsType, SequenceMember::LOCAL, Object::makeInstance(), SequenceMember::OpalElement, OpalParser::parseEnd(), parsePosition(), Expressions::parseString(), ElmPtr::setElement(), and FlaggedElmPtr::setReflectionFlag().
Referenced by parse().
parsePosition()
void SequenceParser::parsePosition (Statement & stat, Object & elem, bool defined) const private
Definition at line 320 of file SequenceParser.cpp.
References SequenceMember::ABSOLUTE, Statement::delimiter(), SequenceMember::DRIFT, SequenceMember::END, Object::findAttribute(), SequenceMember::FROM, Object::getOpalName(), SequenceMember::IMMEDIATE, SequenceMember::itsFlag, SequenceMember::itsPosition, Statement::keyword(), name, SequenceMember::NEXT, Expressions::parseDelimiter(), Expressions::parseRealConst(), Expressions::parseString(), SequenceMember::PREVIOUS, and Hypervolume::ref.
Referenced by parseMember().
Member Data Documentation
itsLine
TLine SequenceParser::itsLine mutable private
Definition at line 106 of file SequenceParser.h.
Referenced by findFromPositions(), findNeighbourPositions(), parse(), and parseMember().
itsSequence
Sequence* SequenceParser::itsSequence private
Definition at line 97 of file SequenceParser.h.
Referenced by findFromPositions(), findNeighbourPositions(), parse(), and parseMember().
okFlag
bool SequenceParser::okFlag mutable private
Definition at line 100 of file SequenceParser.h.
Referenced by parse().
references
RefList SequenceParser::references mutable private
Definition at line 103 of file SequenceParser.h.
Referenced by fillPositions(), findFromPositions(), and findNeighbourPositions().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Lines/SequenceParser.h
/psi/home/gsell/data/src/OPAL/src/src/Lines/SequenceParser.cpp