OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/FieldDebug.h File Reference
FieldDebug.h File Reference
#include "Utility/FieldDebugFunctions.h"
#include "Utility/FieldDebug.hpp"
Classes
class BareField< T, Dim >
Functions
template<class T >
void fp1 (BareField< T, 1U > &field, bool docomm=true)
template<class T >
void fp2 (BareField< T, 2U > &field, bool docomm=true)
template<class T >
void fp3 (BareField< T, 3U > &field, bool docomm=true)
template<class T >
void ggfp1 (BareField< T, 1U > &field, bool docomm=true)
template<class T >
void ggfp2 (BareField< T, 2U > &field, bool docomm=true)
template<class T >
void ggfp3 (BareField< T, 3U > &field, bool docomm=true)
template<class T >
void agfp1 (BareField< T, 1U > &field)
template<class T >
void agfp2 (BareField< T, 2U > &field)
template<class T >
void agfp3 (BareField< T, 3U > &field)
template<class T >
void efp1 (BareField< T, 1U > &field, int i, bool docomm=true)
template<class T >
void efp2 (BareField< T, 2U > &field, int i, int j, bool docomm=true)
template<class T >
void efp3 (BareField< T, 3U > &field, int i, int j, int k, bool docomm=true)
template<class T >
void sfp1 (BareField< T, 1U > &field, int ibase, int ibound, int istride, bool docomm=true)
template<class T >
void sfp2 (BareField< T, 2U > &field, int ibase, int ibound, int istride, int jbase, int jbound, int jstride, bool docomm=true)
template<class T >
void sfp3 (BareField< T, 3U > &field, int ibase, int ibound, int istride, int jbase, int jbound, int jstride, int kbase, int kbound, int kstride, bool docomm=true)
Variables
Inform * FldDbgInform
bool FldDbgInformIsSet
int elementsPerLine
int digitsPastDecimal
int widthOfElements
Function Documentation
agfp1()
template<class T > void agfp1 (BareField< T, 1U > & field)
Definition at line 151 of file FieldDebug.hpp.
References FieldDebugWriteb(), FldDbgInformIsSet, IpplInfo::Info, and setInform().
agfp2()
template<class T > void agfp2 (BareField< T, 2U > & field)
Definition at line 161 of file FieldDebug.hpp.
References FieldDebugWriteb(), FldDbgInformIsSet, IpplInfo::Info, and setInform().
agfp3()
template<class T > void agfp3 (BareField< T, 3U > & field)
Definition at line 171 of file FieldDebug.hpp.
References FieldDebugWriteb(), FldDbgInformIsSet, IpplInfo::Info, and setInform().
efp1()
template<class T > void efp1 (BareField< T, 1U > & field, int i, bool docomm = true)
Definition at line 181 of file FieldDebug.hpp.
References sfp1().
efp2()
template<class T > void efp2 (BareField< T, 2U > & field, int i, int j, bool docomm = true)
Definition at line 190 of file FieldDebug.hpp.
References sfp2().
efp3()
template<class T > void efp3 (BareField< T, 3U > & field, int i, int j, int k, bool docomm = true)
Definition at line 199 of file FieldDebug.hpp.
References sfp3().
fp1()
template<class T > void fp1 (BareField< T, 1U > & field, bool docomm = true)
Definition at line 43 of file FieldDebug.hpp.
References FldDbgInformIsSet, FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::Info, setInform(), and sfp1().
Referenced by Cyclotron::writeOutputFieldFiles().
fp2()
template<class T > void fp2 (BareField< T, 2U > & field, bool docomm = true)
Definition at line 56 of file FieldDebug.hpp.
References FldDbgInformIsSet, FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::Info, setInform(), and sfp2().
Referenced by Cyclotron::writeOutputFieldFiles().
fp3()
template<class T > void fp3 (BareField< T, 3U > & field, bool docomm = true)
Definition at line 72 of file FieldDebug.hpp.
References FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), and sfp3().
ggfp1()
template<class T > void ggfp1 (BareField< T, 1U > & field, bool docomm = true)
Definition at line 91 of file FieldDebug.hpp.
References FldDbgInformIsSet, FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::Info, BareField< T, Dim >::leftGuard(), setInform(), and sfp1().
ggfp2()
template<class T > void ggfp2 (BareField< T, 2U > & field, bool docomm = true)
Definition at line 106 of file FieldDebug.hpp.
References FldDbgInformIsSet, FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::Info, BareField< T, Dim >::leftGuard(), setInform(), and sfp2().
ggfp3()
template<class T > void ggfp3 (BareField< T, 3U > & field, bool docomm = true)
Definition at line 126 of file FieldDebug.hpp.
References FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), BareField< T, Dim >::leftGuard(), and sfp3().
sfp1()
template<class T > void sfp1 (BareField< T, 1U > & field, int ibase, int ibound, int istride, bool docomm = true)
Definition at line 208 of file FieldDebug.hpp.
References digitsPastDecimal, elementsPerLine, endl(), FldDbgInform, FldDbgInformIsSet, BareField< T, Dim >::getDomain(), FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::Info, BareField< T, Dim >::leftGuard(), FieldDebugPrint< T, Dim >::print(), setInform(), and widthOfElements.
Referenced by efp1(), fp1(), and ggfp1().
sfp2()
template<class T > void sfp2 (BareField< T, 2U > & field, int ibase, int ibound, int istride, int jbase, int jbound, int jstride, bool docomm = true)
Definition at line 261 of file FieldDebug.hpp.
References digitsPastDecimal, elementsPerLine, endl(), FldDbgInform, FldDbgInformIsSet, BareField< T, Dim >::getDomain(), FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::Info, BareField< T, Dim >::leftGuard(), FieldDebugPrint< T, Dim >::print(), setInform(), and widthOfElements.
Referenced by efp2(), fp2(), and ggfp2().
sfp3()
template<class T > void sfp3 (BareField< T, 3U > & field, int ibase, int ibound, int istride, int jbase, int jbound, int jstride, int kbase, int kbound, int kstride, bool docomm = true)
Definition at line 345 of file FieldDebug.hpp.
References digitsPastDecimal, elementsPerLine, endl(), FldDbgInform, FldDbgInformIsSet, BareField< T, Dim >::getDomain(), FieldLayout< Dim >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::Info, BareField< T, Dim >::leftGuard(), FieldDebugPrint< T, Dim >::print(), setInform(), and widthOfElements.
Referenced by efp3(), fp3(), and ggfp3().
Variable Documentation
digitsPastDecimal
int digitsPastDecimal
Definition at line 53 of file FieldDebugFunctions.cpp.
Referenced by FieldDebugWriteb(), sfp1(), sfp2(), sfp3(), and spap().
elementsPerLine
int elementsPerLine
Definition at line 52 of file FieldDebugFunctions.cpp.
Referenced by FieldDebugWriteb(), sfp1(), sfp2(), sfp3(), and spap().
FldDbgInform
Inform* FldDbgInform
Definition at line 31 of file FieldDebugFunctions.cpp.
Referenced by epap(), pap(), sfp1(), sfp2(), sfp3(), and spap().
FldDbgInformIsSet
bool FldDbgInformIsSet
Definition at line 38 of file FieldDebugFunctions.cpp.
Referenced by agfp1(), agfp2(), agfp3(), epap(), fp1(), fp2(), ggfp1(), ggfp2(), pap(), sfp1(), sfp2(), sfp3(), and spap().
widthOfElements
int widthOfElements
Definition at line 54 of file FieldDebugFunctions.cpp.
Referenced by FieldDebugWriteb(), sfp1(), sfp2(), sfp3(), and spap().