OPAL (Object Oriented Parallel Accelerator Library): CenteredFieldLayout< Dim, Mesh, Centering > Class Template Reference
CenteredFieldLayout< Dim, Mesh, Centering > Class Template Reference
#include <CenteredFieldLayout.h>
Public Member Functions
CenteredFieldLayout (Mesh &mesh, e_dim_tag *p=0, int vnodes=-1)
CenteredFieldLayout (Mesh &mesh, e_dim_tag p1, int vnodes=-1)
CenteredFieldLayout (Mesh &mesh, e_dim_tag p1, e_dim_tag p2, int vnodes=-1)
CenteredFieldLayout (Mesh &mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, int vnodes=-1)
CenteredFieldLayout (Mesh &mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, int vnodes=-1)
CenteredFieldLayout (Mesh &mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, e_dim_tag p5, int vnodes=-1)
CenteredFieldLayout (Mesh &mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, e_dim_tag p5, e_dim_tag p6, int vnodes=-1)
CenteredFieldLayout (Mesh &mesh, e_dim_tag *p, unsigned *vnodesAlongDirection, bool recurse=false, int vnodes=-1)
CenteredFieldLayout (Mesh &mesh, e_dim_tag p1, unsigned vnodes1, bool recurse=false, int vnodes=-1)
CenteredFieldLayout (Mesh &mesh, e_dim_tag p1, e_dim_tag p2, unsigned vnodes1, unsigned vnodes2, bool recurse=false, int vnodes=-1)
CenteredFieldLayout (Mesh &mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, bool recurse=false, int vnodes=-1)
CenteredFieldLayout (Mesh &mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, unsigned vnodes4, bool recurse=false, int vnodes=-1)
CenteredFieldLayout (Mesh &mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, e_dim_tag p5, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, unsigned vnodes4, unsigned vnodes5, bool recurse=false, int vnodes=-1)
CenteredFieldLayout (Mesh &mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, e_dim_tag p5, e_dim_tag p6, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, unsigned vnodes4, unsigned vnodes5, unsigned vnodes6, bool recurse=false, int vnodes=-1)
CenteredFieldLayout (Mesh &mesh, const NDIndex< Dim > *dombegin, const NDIndex< Dim > *domend, const int *nbegin, const int *nend)
Public Member Functions inherited from FieldLayout< Dim >
FieldLayout ()
FieldLayout (const char *filename)
FieldLayout (const Index &i1, e_dim_tag p1=PARALLEL, int vnodes=-1)
FieldLayout (const Index &i1, const Index &i2, e_dim_tag p1=PARALLEL, e_dim_tag p2=PARALLEL, int vnodes=-1)
FieldLayout (const Index &i1, const Index &i2, const Index &i3, e_dim_tag p1=PARALLEL, e_dim_tag p2=PARALLEL, e_dim_tag p3=PARALLEL, int vnodes=-1)
FieldLayout (const Index &i1, const Index &i2, const Index &i3, const Index &i4, e_dim_tag p1=PARALLEL, e_dim_tag p2=PARALLEL, e_dim_tag p3=PARALLEL, e_dim_tag p4=PARALLEL, int vnodes=-1)
FieldLayout (const Index &i1, const Index &i2, const Index &i3, const Index &i4, const Index &i5, e_dim_tag p1=PARALLEL, e_dim_tag p2=PARALLEL, e_dim_tag p3=PARALLEL, e_dim_tag p4=PARALLEL, e_dim_tag p5=PARALLEL, int vnodes=-1)
FieldLayout (const Index &i1, const Index &i2, const Index &i3, const Index &i4, const Index &i5, const Index &i6, e_dim_tag p1=PARALLEL, e_dim_tag p2=PARALLEL, e_dim_tag p3=PARALLEL, e_dim_tag p4=PARALLEL, e_dim_tag p5=PARALLEL, e_dim_tag p6=PARALLEL, int vnodes=-1)
FieldLayout (const Index &i1, e_dim_tag p1, unsigned vnodes1, bool recurse=false, int vnodes=-1)
FieldLayout (const Index &i1, const Index &i2, e_dim_tag p1, e_dim_tag p2, unsigned vnodes1, unsigned vnodes2, bool recurse=false, int vnodes=-1)
FieldLayout (const Index &i1, const Index &i2, const Index &i3, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, bool recurse=false, int vnodes=-1)
FieldLayout (const Index &i1, const Index &i2, const Index &i3, const Index &i4, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, unsigned vnodes4, bool recurse=false, int vnodes=-1)
FieldLayout (const Index &i1, const Index &i2, const Index &i3, const Index &i4, const Index &i5, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, e_dim_tag p5, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, unsigned vnodes4, unsigned vnodes5, bool recurse=false, int vnodes=-1)
FieldLayout (const Index &i1, const Index &i2, const Index &i3, const Index &i4, const Index &i5, const Index &i6, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, e_dim_tag p5, e_dim_tag p6, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, unsigned vnodes4, unsigned vnodes5, unsigned vnodes6, bool recurse=false, int vnodes=-1)
FieldLayout (const NDIndex< Dim > &domain, e_dim_tag *p=0, int vnodes=-1)
FieldLayout (const NDIndex< Dim > &domain, e_dim_tag *p, unsigned *vnodesPerDirection, bool recurse=false, int vnodes=-1)
FieldLayout (const NDIndex< Dim > &Domain, const NDIndex< Dim > *begin, const NDIndex< Dim > *end)
FieldLayout (const NDIndex< Dim > &Domain, const Vnode< Dim > *begin, const Vnode< Dim > *end)
FieldLayout (const NDIndex< Dim > &Domain, const NDIndex< Dim > *dombegin, const NDIndex< Dim > *domend, const int *nbegin, const int *nend)
virtual ~FieldLayout ()
void initialize (const Index &i1, e_dim_tag p1=PARALLEL, int vnodes=-1)
void initialize (const Index &i1, const Index &i2, e_dim_tag p1=PARALLEL, e_dim_tag p2=PARALLEL, int vnodes=-1)
void initialize (const Index &i1, const Index &i2, const Index &i3, e_dim_tag p1=PARALLEL, e_dim_tag p2=PARALLEL, e_dim_tag p3=PARALLEL, int vnodes=-1)
void initialize (const Index &i1, const Index &i2, const Index &i3, const Index &i4, e_dim_tag p1=PARALLEL, e_dim_tag p2=PARALLEL, e_dim_tag p3=PARALLEL, e_dim_tag p4=PARALLEL, int vnodes=-1)
void initialize (const Index &i1, const Index &i2, const Index &i3, const Index &i4, const Index &i5, e_dim_tag p1=PARALLEL, e_dim_tag p2=PARALLEL, e_dim_tag p3=PARALLEL, e_dim_tag p4=PARALLEL, e_dim_tag p5=PARALLEL, int vnodes=-1)
void initialize (const Index &i1, const Index &i2, const Index &i3, const Index &i4, const Index &i5, const Index &i6, e_dim_tag p1=PARALLEL, e_dim_tag p2=PARALLEL, e_dim_tag p3=PARALLEL, e_dim_tag p4=PARALLEL, e_dim_tag p5=PARALLEL, e_dim_tag p6=PARALLEL, int vnodes=-1)
void initialize (const NDIndex< Dim > &domain, e_dim_tag *p=0, int vnodes=-1)
void initialize (const Index &i1, e_dim_tag p1, unsigned vnodes1, bool recurse=false, int vnodes=-1)
void initialize (const Index &i1, const Index &i2, e_dim_tag p1, e_dim_tag p2, unsigned vnodes1, unsigned vnodes2, bool recurse=false, int vnodes=-1)
void initialize (const Index &i1, const Index &i2, const Index &i3, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, bool recurse=false, int vnodes=-1)
void initialize (const Index &i1, const Index &i2, const Index &i3, const Index &i4, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, unsigned vnodes4, bool recurse=false, int vnodes=-1)
void initialize (const Index &i1, const Index &i2, const Index &i3, const Index &i4, const Index &i5, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, e_dim_tag p5, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, unsigned vnodes4, unsigned vnodes5, bool recurse=false, int vnodes=-1)
void initialize (const Index &i1, const Index &i2, const Index &i3, const Index &i4, const Index &i5, const Index &i6, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, e_dim_tag p5, e_dim_tag p6, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, unsigned vnodes4, unsigned vnodes5, unsigned vnodes6, bool recurse=false, int vnodes=-1)
void initialize (const NDIndex< Dim > &domain, e_dim_tag *p, unsigned *vnodesPerDirection, bool recurse=false, int vnodes=-1)
void initialize (const NDIndex< Dim > &Domain, const NDIndex< Dim > *dombegin, const NDIndex< Dim > *domend, const int *nbegin, const int *nend)
void Repartition (const NDIndex< Dim > *, const NDIndex< Dim > *)
void Repartition (const NDIndex< Dim > &domain)
void Repartition (const Vnode< Dim > *, const Vnode< Dim > *)
const NDIndex< Dim > & getDomain () const
template<unsigned Dim2>
bool operator== (const FieldLayout< Dim2 > &x) const
bool read (const char *filename)
bool write (const char *filename)
int numVnodes (void) const
ac_id_vnodes::size_type size_iv () const
iterator_iv begin_iv ()
iterator_iv end_iv ()
const_iterator_iv begin_iv () const
const_iterator_iv end_iv () const
ac_gc_domain_vnodes::size_type size_rgdv () const
iterator_gdv begin_rgdv ()
iterator_gdv end_rgdv ()
ac_domain_vnodes::size_type size_rdv (const GuardCellSizes< Dim > &gc=gc0()) const
iterator_dv begin_rdv (const GuardCellSizes< Dim > &gc=gc0())
iterator_dv end_rdv (const GuardCellSizes< Dim > &gc=gc0())
touch_range_dv touch_range_rdv (const NDIndex< Dim > &domain, const GuardCellSizes< Dim > &gc=gc0()) const
size_type_if size_if () const
iterator_if begin_if ()
iterator_if end_if ()
bool fitsGuardCells (const GuardCellSizes< Dim > &gc) const
e_dim_tag getDistribution (unsigned int d) const
e_dim_tag getRequestedDistribution (unsigned int d) const
unsigned getVnodesPerDirection (unsigned dir)
UserList::ID_t get_Id () const
void checkin (FieldLayoutUser &f, const GuardCellSizes< Dim > &gc=gc0())
void checkout (FieldLayoutUser &f)
NDIndex< Dim > getLocalNDIndex ()
void write (std::ostream &) const
Additional Inherited Members
Public Types inherited from FieldLayout< Dim >
typedef vmap< Unique::type, my_auto_ptr< Vnode< Dim > > > ac_id_vnodes
typedef DomainMap< NDIndex< Dim >, RefCountedP< Vnode< Dim > >, Touches< Dim >, Contains< Dim >, Split< Dim > > ac_domain_vnodes
typedef vmap< GuardCellSizes< Dim >, my_auto_ptr< ac_domain_vnodes > > ac_gc_domain_vnodes
typedef ac_id_vnodes::iterator iterator_iv
typedef ac_id_vnodes::const_iterator const_iterator_iv
typedef ac_domain_vnodes::iterator iterator_dv
typedef ac_domain_vnodes::touch_iterator touch_iterator_dv
typedef std::pair< touch_iterator_dv, touch_iterator_dv > touch_range_dv
typedef ac_gc_domain_vnodes::iterator iterator_gdv
typedef iterator_user iterator_if
typedef size_type_user size_type_if
Detailed Description
template<unsigned Dim, class Mesh, class Centering>
class CenteredFieldLayout< Dim, Mesh, Centering >
Definition at line 19 of file CenteredFieldLayout.h.
Constructor & Destructor Documentation
CenteredFieldLayout() [1/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, e_dim_tag * p = 0, int vnodes = -1)
Definition at line 306 of file CenteredFieldLayout.hpp.
References centeredInitialize(), Dim, Mesh< Dim >::Dimension, and PInsist.
CenteredFieldLayout() [2/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, e_dim_tag p1, int vnodes = -1)
Definition at line 320 of file CenteredFieldLayout.hpp.
References centeredInitialize(), Dim, Mesh< Dim >::Dimension, and PInsist.
CenteredFieldLayout() [3/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, e_dim_tag p1, e_dim_tag p2, int vnodes = -1)
Definition at line 333 of file CenteredFieldLayout.hpp.
References centeredInitialize(), Dim, Mesh< Dim >::Dimension, and PInsist.
CenteredFieldLayout() [4/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, int vnodes = -1)
Definition at line 348 of file CenteredFieldLayout.hpp.
References centeredInitialize(), Dim, Mesh< Dim >::Dimension, and PInsist.
CenteredFieldLayout() [5/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, int vnodes = -1)
Definition at line 363 of file CenteredFieldLayout.hpp.
References centeredInitialize(), Dim, Mesh< Dim >::Dimension, and PInsist.
CenteredFieldLayout() [6/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, e_dim_tag p5, int vnodes = -1)
Definition at line 378 of file CenteredFieldLayout.hpp.
References centeredInitialize(), Dim, Mesh< Dim >::Dimension, and PInsist.
CenteredFieldLayout() [7/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, e_dim_tag p5, e_dim_tag p6, int vnodes = -1)
Definition at line 394 of file CenteredFieldLayout.hpp.
References centeredInitialize(), Dim, Mesh< Dim >::Dimension, and PInsist.
CenteredFieldLayout() [8/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, e_dim_tag * p, unsigned * vnodesAlongDirection, bool recurse = false, int vnodes = -1)
Definition at line 419 of file CenteredFieldLayout.hpp.
References centeredInitialize(), Dim, Mesh< Dim >::Dimension, and PInsist.
CenteredFieldLayout() [9/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, e_dim_tag p1, unsigned vnodes1, bool recurse = false, int vnodes = -1)
Definition at line 433 of file CenteredFieldLayout.hpp.
References centeredInitialize(), Dim, Mesh< Dim >::Dimension, and PInsist.
CenteredFieldLayout() [10/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, e_dim_tag p1, e_dim_tag p2, unsigned vnodes1, unsigned vnodes2, bool recurse = false, int vnodes = -1)
Definition at line 448 of file CenteredFieldLayout.hpp.
References centeredInitialize(), Dim, Mesh< Dim >::Dimension, and PInsist.
CenteredFieldLayout() [11/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, bool recurse = false, int vnodes = -1)
Definition at line 467 of file CenteredFieldLayout.hpp.
References centeredInitialize(), Dim, Mesh< Dim >::Dimension, and PInsist.
CenteredFieldLayout() [12/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, unsigned vnodes4, bool recurse = false, int vnodes = -1)
Definition at line 486 of file CenteredFieldLayout.hpp.
References centeredInitialize(), Dim, Mesh< Dim >::Dimension, and PInsist.
CenteredFieldLayout() [13/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, e_dim_tag p5, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, unsigned vnodes4, unsigned vnodes5, bool recurse = false, int vnodes = -1)
Definition at line 507 of file CenteredFieldLayout.hpp.
References centeredInitialize(), Dim, Mesh< Dim >::Dimension, and PInsist.
CenteredFieldLayout() [14/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, e_dim_tag p1, e_dim_tag p2, e_dim_tag p3, e_dim_tag p4, e_dim_tag p5, e_dim_tag p6, unsigned vnodes1, unsigned vnodes2, unsigned vnodes3, unsigned vnodes4, unsigned vnodes5, unsigned vnodes6, bool recurse = false, int vnodes = -1)
Definition at line 529 of file CenteredFieldLayout.hpp.
References centeredInitialize(), Dim, Mesh< Dim >::Dimension, and PInsist.
CenteredFieldLayout() [15/15]
template<unsigned Dim, class Mesh , class Centering > CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout (Mesh & mesh, const NDIndex< Dim > * dombegin, const NDIndex< Dim > * domend, const int * nbegin, const int * nend)
Definition at line 556 of file CenteredFieldLayout.hpp.
References centeredInitialize().
The documentation for this class was generated from the following files:
ippl/src/FieldLayout/CenteredFieldLayout.h
ippl/src/FieldLayout/CenteredFieldLayout.hpp