OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyDistributionNS Namespace Reference
PyOpal::PyDistributionNS Namespace Reference
Functions
void registerDistribution (PyOpalObjectNS::PyOpalObject< Distribution > &dist)
BOOST_PYTHON_MODULE (distribution)
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyDistributionNS::BOOST_PYTHON_MODULE (distribution)
Definition at line 39 of file PyDistribution.cpp.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::addExecute(), PyOpal::Globals::Initialise(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_class(), registerDistribution(), and PyOpal::ExceptionTranslation::registerExceptions().
registerDistribution()
void PyOpal::PyDistributionNS::registerDistribution (PyOpalObjectNS::PyOpalObject< Distribution > & dist)
Definition at line 33 of file PyDistribution.cpp.
References OpalData::define(), OpalData::getInstance(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalShared(), and Object::update().
Referenced by BOOST_PYTHON_MODULE().