OPAL (Object Oriented Parallel Accelerator Library): IntCIC Class Reference
IntCIC Class Reference
#include <IntCIC.h>
Public Member Functions
IntCIC ()
~IntCIC ()
Static Public Member Functions
template<class FT , unsigned Dim, class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh)
template<class FT , unsigned Dim, class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh, CacheDataCIC< PT, Dim > &cache)
template<class FT , unsigned Dim, class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, Dim, M, C > &f, const CacheDataCIC< PT, Dim > &cache)
template<class FT , unsigned Dim, class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh)
template<class FT , unsigned Dim, class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh, CacheDataCIC< PT, Dim > &cache)
template<class FT , unsigned Dim, class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, Dim, M, C > &f, const CacheDataCIC< PT, Dim > &cache)
Detailed Description
Definition at line 1191 of file IntCIC.h.
Constructor & Destructor Documentation
IntCIC()
IntCIC::IntCIC () inline
Definition at line 1195 of file IntCIC.h.
~IntCIC()
IntCIC::~IntCIC () inline
Definition at line 1196 of file IntCIC.h.
Member Function Documentation
gather() [1/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntCIC::gather (FT & pdata, const Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh) inline static
Definition at line 1231 of file IntCIC.h.
References IntCICImpl< Dim >::gather().
gather() [2/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntCIC::gather (FT & pdata, const Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh, CacheDataCIC< PT, Dim > & cache) inline static
Definition at line 1240 of file IntCIC.h.
References CacheDataCIC< T, Dim >::Delta_m, IntCICImpl< Dim >::gather(), CacheDataCIC< T, Dim >::Index_m, and CacheDataCIC< T, Dim >::Offset_m.
gather() [3/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntCIC::gather (FT & pdata, const Field< FT, Dim, M, C > & f, const CacheDataCIC< PT, Dim > & cache) inline static
Definition at line 1250 of file IntCIC.h.
References CacheDataCIC< T, Dim >::Delta_m, IntCICImpl< Dim >::gather(), CacheDataCIC< T, Dim >::Index_m, and CacheDataCIC< T, Dim >::Offset_m.
scatter() [1/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntCIC::scatter (const FT & pdata, Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh) inline static
Definition at line 1203 of file IntCIC.h.
References IntCICImpl< Dim >::scatter().
scatter() [2/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntCIC::scatter (const FT & pdata, Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh, CacheDataCIC< PT, Dim > & cache) inline static
Definition at line 1212 of file IntCIC.h.
References CacheDataCIC< T, Dim >::Delta_m, CacheDataCIC< T, Dim >::Index_m, CacheDataCIC< T, Dim >::Offset_m, and IntCICImpl< Dim >::scatter().
scatter() [3/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntCIC::scatter (const FT & pdata, Field< FT, Dim, M, C > & f, const CacheDataCIC< PT, Dim > & cache) inline static
Definition at line 1222 of file IntCIC.h.
References CacheDataCIC< T, Dim >::Delta_m, CacheDataCIC< T, Dim >::Index_m, CacheDataCIC< T, Dim >::Offset_m, and IntCICImpl< Dim >::scatter().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/IntCIC.h