OPAL (Object Oriented Parallel Accelerator Library): OpalTrimCoil Class Reference
OpalTrimCoil Class Reference
#include <OpalTrimCoil.h>
Public Member Functions
OpalTrimCoil ()
Exemplar constructor.
virtual ~OpalTrimCoil ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual OpalTrimCoil * clone (const std::string &name)
Make clone.
virtual void execute ()
Check the OpalTrimCoil data.
virtual void update ()
Update the OpalTrimCoil data.
Inform & print (Inform &os) const
void initOpalTrimCoil ()
Initialise implementation.
Public Member Functions inherited from Definition
virtual ~Definition ()
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static OpalTrimCoil * find (const std::string &name)
Find named trim coil.
Public Attributes
std::unique_ptr< TrimCoil > trimcoil_m
Actual implementation.
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Private Member Functions
OpalTrimCoil (const std::string &name, OpalTrimCoil *parent)
void printPolynom (Inform &os, const Attribute &attr) const
Helper method for printing.
OpalTrimCoil (const OpalTrimCoil &)=delete
Not implemented.
void operator= (const OpalTrimCoil &)=delete
Additional Inherited Members
Protected Member Functions inherited from Definition
Definition (int size, const char *name, const char *help)
Constructor for exemplars.
Definition (const std::string &name, Definition *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 37 of file OpalTrimCoil.h.
Constructor & Destructor Documentation
OpalTrimCoil() [1/3]
OpalTrimCoil::OpalTrimCoil ()
Exemplar constructor.
Definition at line 56 of file OpalTrimCoil.cpp.
References Object::builtin, clone(), OpalData::define(), OpalData::getInstance(), Object::itsAttr, Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeRealArray(), Object::registerOwnership(), AttributeHandler::STATEMENT, Attrib::Distribution::TYPE, and update().
Referenced by clone().
~OpalTrimCoil()
OpalTrimCoil::~OpalTrimCoil () virtual
Definition at line 114 of file OpalTrimCoil.cpp.
OpalTrimCoil() [2/3]
OpalTrimCoil::OpalTrimCoil (const OpalTrimCoil &) private delete
Not implemented.
OpalTrimCoil() [3/3]
OpalTrimCoil::OpalTrimCoil (const std::string & name, OpalTrimCoil * parent) private
Private copy constructor, called by clone
Definition at line 108 of file OpalTrimCoil.cpp.
Member Function Documentation
canReplaceBy()
bool OpalTrimCoil::canReplaceBy (Object * object) virtual
Test if replacement is allowed.
Reimplemented from Object.
Definition at line 118 of file OpalTrimCoil.cpp.
clone()
OpalTrimCoil * OpalTrimCoil::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 124 of file OpalTrimCoil.cpp.
References name, and OpalTrimCoil().
Referenced by OpalTrimCoil().
execute()
void OpalTrimCoil::execute () virtual
Check the OpalTrimCoil data.
Reimplemented from Object.
Definition at line 129 of file OpalTrimCoil.cpp.
References update().
find()
OpalTrimCoil * OpalTrimCoil::find (const std::string & name) static
Find named trim coil.
Definition at line 134 of file OpalTrimCoil.cpp.
References OpalData::find(), OpalData::getInstance(), and name.
Referenced by OpalCyclotron::update().
initOpalTrimCoil()
void OpalTrimCoil::initOpalTrimCoil ()
Initialise implementation.
Definition at line 150 of file OpalTrimCoil.cpp.
References endl(), Attributes::getReal(), Attributes::getRealArray(), Attributes::getString(), gmsg, Object::itsAttr, level3(), trimcoil_m, and Attrib::Distribution::TYPE.
Referenced by OpalCyclotron::update().
operator=()
void OpalTrimCoil::operator= (const OpalTrimCoil &) private delete
print()
Inform & OpalTrimCoil::print (Inform & os) const
Definition at line 181 of file OpalTrimCoil.cpp.
References endl(), Object::getOpalName(), Attributes::getReal(), Attributes::getString(), Object::itsAttr, printPolynom(), and Attrib::Distribution::TYPE.
Referenced by operator<<().
printPolynom()
void OpalTrimCoil::printPolynom (Inform & os, const Attribute & attr) const private
Helper method for printing.
Definition at line 205 of file OpalTrimCoil.cpp.
References Attribute::getName(), and Attributes::getRealArray().
Referenced by print().
update()
void OpalTrimCoil::update () virtual
Update the OpalTrimCoil data.
Reimplemented from Object.
Definition at line 144 of file OpalTrimCoil.cpp.
References Object::getOpalName(), and Object::setOpalName().
Referenced by execute(), and OpalTrimCoil().
Member Data Documentation
trimcoil_m
std::unique_ptr<TrimCoil> OpalTrimCoil::trimcoil_m
Actual implementation.
Definition at line 69 of file OpalTrimCoil.h.
Referenced by initOpalTrimCoil(), and OpalCyclotron::update().
The documentation for this class was generated from the following files:
src/Classic/TrimCoils/OpalTrimCoil.h
src/Classic/TrimCoils/OpalTrimCoil.cpp