OPAL (Object Oriented Parallel Accelerator Library): ParticleProperties Class Reference
ParticleProperties Class Reference
#include <ParticleProperties.h>
Static Public Member Functions
static ParticleType getParticleType (const std::string &str)
static std::string getParticleTypeString (const ParticleType &type)
static double getParticleMass (const ParticleType &type)
static double getParticleCharge (const ParticleType &type)
static double getParticleChargeInCoulomb (const ParticleType &type)
Static Private Attributes
static const boost::bimap< ParticleType, std::string > bmParticleType_s
static const std::map< ParticleType, double > particleMass_m
static const std::map< ParticleType, double > particleCharge_m
Detailed Description
Definition at line 51 of file ParticleProperties.h.
Member Function Documentation
getParticleCharge()
double ParticleProperties::getParticleCharge (const ParticleType & type) static
Definition at line 41 of file ParticleProperties.cpp.
References particleCharge_m.
Referenced by getParticleChargeInCoulomb(), and Beam::update().
getParticleChargeInCoulomb()
double ParticleProperties::getParticleChargeInCoulomb (const ParticleType & type) static
Definition at line 45 of file ParticleProperties.cpp.
References getParticleCharge(), and Physics::q_e.
Referenced by BeamStrippingPhysics::transformToSecondary().
getParticleMass()
double ParticleProperties::getParticleMass (const ParticleType & type) static
Definition at line 37 of file ParticleProperties.cpp.
References particleMass_m.
Referenced by BeamStrippingPhysics::transformToSecondary(), and Beam::update().
getParticleType()
ParticleType ParticleProperties::getParticleType (const std::string & str) static
Definition at line 24 of file ParticleProperties.cpp.
References bmParticleType_s, and UNNAMED.
Referenced by PartBunchBase< double, 3 >::setPType(), and Beam::update().
getParticleTypeString()
std::string ParticleProperties::getParticleTypeString (const ParticleType & type) static
Definition at line 33 of file ParticleProperties.cpp.
References bmParticleType_s.
Referenced by BeamStrippingPhysics::apply(), ScatteringPhysics::apply(), and BeamStrippingPhysics::transformToSecondary().
Member Data Documentation
bmParticleType_s
const boost::bimap< ParticleType, std::string > ParticleProperties::bmParticleType_s static private
Initial value:
=
    boost::assign::list_of<const boost::bimap<ParticleType, std::string>::relation>
        (ParticleType::UNNAMED,    "UNNAMED")
        (ParticleType::ELECTRON,   "ELECTRON")
        (ParticleType::POSITRON,   "POSITRON")
        (ParticleType::MUON,       "MUON")
        (ParticleType::PROTON,     "PROTON")
        (ParticleType::ANTIPROTON, "ANTIPROTON")
        (ParticleType::DEUTERON,   "DEUTERON")
        (ParticleType::HMINUS,     "HMINUS")
        (ParticleType::HYDROGEN,   "HYDROGEN")
        (ParticleType::H2P,        "H2P")
        (ParticleType::H3P,        "H3P")
        (ParticleType::ALPHA,      "ALPHA")
        (ParticleType::CARBON,     "CARBON")
        (ParticleType::XENON,      "XENON")
        (ParticleType::URANIUM,    "URANIUM")
Definition at line 63 of file ParticleProperties.h.
Referenced by getParticleType(), and getParticleTypeString().
particleCharge_m
const std::map< ParticleType, double > ParticleProperties::particleCharge_m static private
Initial value:
= {
    {ParticleType::ELECTRON,   -1.0},
    {ParticleType::POSITRON,    1.0},
    {ParticleType::MUON,       -1.0},
    {ParticleType::PROTON,      1.0},
    {ParticleType::ANTIPROTON, -1.0},
    {ParticleType::DEUTERON,    1.0},
    {ParticleType::HMINUS,     -1.0},
    {ParticleType::HYDROGEN,    0.0},
    {ParticleType::H2P,         1.0},
    {ParticleType::H3P,         1.0},
    {ParticleType::ALPHA,       2.0},
    {ParticleType::CARBON,      6.0},
    {ParticleType::XENON,      54.0},
    {ParticleType::URANIUM,    92.0}
}
Definition at line 66 of file ParticleProperties.h.
Referenced by getParticleCharge().
particleMass_m
const std::map< ParticleType, double > ParticleProperties::particleMass_m static private
Initial value:
= {
    {ParticleType::ELECTRON,   Physics::m_e},
    {ParticleType::POSITRON,   Physics::m_e},
    {ParticleType::MUON,       Physics::m_mu},
    {ParticleType::PROTON,     Physics::m_p},
    {ParticleType::ANTIPROTON, Physics::m_p},
    {ParticleType::DEUTERON,   Physics::m_d},
    {ParticleType::HMINUS,     Physics::m_hm},
    {ParticleType::HYDROGEN,   Physics::m_h},
    {ParticleType::H2P,        Physics::m_h2p},
    {ParticleType::H3P,        Physics::m_h3p},
    {ParticleType::ALPHA,      Physics::m_alpha},
    {ParticleType::CARBON,     Physics::m_c},
    {ParticleType::XENON,      Physics::m_xe},
    {ParticleType::URANIUM,    Physics::m_u}
}
Definition at line 65 of file ParticleProperties.h.
Referenced by getParticleMass().
The documentation for this class was generated from the following files:
src/Classic/Physics/ParticleProperties.h
src/Classic/Physics/ParticleProperties.cpp