OPAL (Object Oriented Parallel Accelerator Library): FFT< RCTransform, Dim, T > Class Template Reference
FFT< RCTransform, Dim, T > Class Template Reference
#include <FFT.h>
Public Types
typedef FieldLayout< Dim > Layout_t
typedef BareField< T, Dim > RealField_t
typedef LField< T, Dim > RealLField_t
typedef std::complex< T > Complex_t
typedef BareField< Complex_t, Dim > ComplexField_t
typedef LField< Complex_t, Dim > ComplexLField_t
typedef FFTBase< Dim, T >::Domain_t Domain_t
Public Types inherited from FFTBase< Dim, T >
enum { dimensions = Dim }
enum FFT_e { ccFFT, rcFFT, sineFFT, cosineFFT }
typedef T Precision_t
typedef NDIndex< Dim > Domain_t
typedef FFTPACK< T > InternalFFT_t
Public Member Functions
FFT (const Domain_t &rdomain, const Domain_t &cdomain, const bool transformTheseDims[Dim], const bool &compressTemps=false)
FFT (const Domain_t &rdomain, const Domain_t &cdomain, const bool &compressTemps=false, int serialAxes=1)
~FFT (void)
void transform (int direction, RealField_t &f, ComplexField_t &g, const bool &constInput=false)
void transform (const char *directionName, RealField_t &f, ComplexField_t &g, const bool &constInput=false)
void transform (int direction, ComplexField_t &f, RealField_t &g, const bool &constInput=false)
void transform (const char *directionName, ComplexField_t &f, RealField_t &g, const bool &constInput=false)
Public Member Functions inherited from FFTBase< Dim, T >
FFTBase ()
FFTBase (FFT_e transform, const Domain_t &domain, const bool transformTheseDims[Dim], bool compressTemps)
FFTBase (FFT_e transform, const Domain_t &domain, bool compressTemps)
virtual ~FFTBase (void)
void write (std::ostream &out) const
void setDirectionName (int direction, const char *directionName)
void setNormFact (Precision_t nf)
int transVnodes () const
Private Member Functions
void setup (void)
Private Attributes
Layout_t ** tempLayouts_m
Layout_t * tempRLayout_m
ComplexField_t ** tempFields_m
RealField_t * tempRField_m
Domain_t complexDomain_m
int serialAxes_m
Additional Inherited Members
Protected Member Functions inherited from FFTBase< Dim, T >
int getDirection (const char *directionName) const
translate direction name string into dimension number
bool transformDim (unsigned d) const
query whether this dimension is to be transformed
unsigned numTransformDims (void) const
query number of transform dimensions
unsigned activeDimension (unsigned d) const
get dimension number from list of transformed dimensions
InternalFFT_t & getEngine (void)
access the internal FFT Engine
Precision_t & getNormFact (void)
get the FFT normalization factor
const Domain_t & getDomain (void) const
get our domain
bool checkDomain (const Domain_t &dom1, const Domain_t &dom2) const
compare indexes of two domains
bool compressTemps (void) const
do we compress temps?
Static Protected Attributes inherited from FFTBase< Dim, T >
static GuardCellSizes< Dim > nullGC = GuardCellSizes<Dim>()
null GuardCellSizes object for checking BareField arguments to transform
Detailed Description
template<size_t Dim, class T>
class FFT< RCTransform, Dim, T >
real-to-complex FFT class
Definition at line 395 of file FFT.h.
Member Typedef Documentation
Complex_t
template<size_t Dim, class T > typedef std::complex<T> FFT< RCTransform, Dim, T >::Complex_t
Definition at line 405 of file FFT.h.
ComplexField_t
template<size_t Dim, class T > typedef BareField<Complex_t,Dim> FFT< RCTransform, Dim, T >::ComplexField_t
Definition at line 406 of file FFT.h.
ComplexLField_t
template<size_t Dim, class T > typedef LField<Complex_t,Dim> FFT< RCTransform, Dim, T >::ComplexLField_t
Definition at line 407 of file FFT.h.
Domain_t
template<size_t Dim, class T > typedef FFTBase<Dim, T>::Domain_t FFT< RCTransform, Dim, T >::Domain_t
Definition at line 408 of file FFT.h.
Layout_t
template<size_t Dim, class T > typedef FieldLayout<Dim> FFT< RCTransform, Dim, T >::Layout_t
Definition at line 402 of file FFT.h.
RealField_t
template<size_t Dim, class T > typedef BareField<T,Dim> FFT< RCTransform, Dim, T >::RealField_t
Definition at line 403 of file FFT.h.
RealLField_t
template<size_t Dim, class T > typedef LField<T,Dim> FFT< RCTransform, Dim, T >::RealLField_t
Definition at line 404 of file FFT.h.
Constructor & Destructor Documentation
FFT() [1/2]
template<size_t Dim, class T > FFT< RCTransform, Dim, T >::FFT (const Domain_t & rdomain, const Domain_t & cdomain, const bool transformTheseDims[Dim], const bool & compressTemps = false)
Create a new FFT object with the given domains for input/output Fields Specify which dimensions to transform along. Optional argument compress indicates whether or not to compress temporary Fields in between uses.
FFT() [2/2]
template<size_t Dim, class T > FFT< RCTransform, Dim, T >::FFT (const Domain_t & rdomain, const Domain_t & cdomain, const bool & compressTemps = false, int serialAxes = 1)
Same as above, but transform all dims:
~FFT()
template<size_t Dim, class T > FFT< RCTransform, Dim, T >::~FFT (void)
Definition at line 922 of file FFT.hpp.
References FFTBase< Dim, T >::numTransformDims().
Member Function Documentation
setup()
template<size_t Dim, class T > void FFT< RCTransform, Dim, T >::setup (void) private
complex-to-real FFT on GPU: pass pointer to GPU memory where complex field is stored, do the inverse FFT and transfer real field back to host memory setup performs all the initializations necessary after the transform directions have been specified.
Definition at line 785 of file FFT.hpp.
References FFTBase< Dim, T >::activeDimension(), Dim, FFTBase< Dim, T >::getDomain(), FFTBase< Dim, T >::numTransformDims(), PARALLEL, PAssert_GT, PAssert_LT, PInsist, SERIAL, and FFTBase< Dim, T >::transVnodes().
transform() [1/4]
template<size_t Dim, class T > void FFT< RCTransform, Dim, T >::transform (int direction, RealField_t & f, ComplexField_t & g, const bool & constInput = false)
real-to-complex FFT: specify +1 or -1 to indicate forward or inverse transform, or specify the user-defined name string for the direction. Supply a second BareField to store the output. optional argument constInput indicates whether or not to treat the input Field argument f as const. If not, we can use it as a temporary in order to avoid an additional data transpose.
transform() [2/4]
template<size_t Dim, class T > void FFT< RCTransform, Dim, T >::transform (const char * directionName, RealField_t & f, ComplexField_t & g, const bool & constInput = false)
transform() [3/4]
template<size_t Dim, class T > void FFT< RCTransform, Dim, T >::transform (int direction, ComplexField_t & f, RealField_t & g, const bool & constInput = false)
real-to-complex FFT on GPU: transfer the real field to GPU execute FFT return the pointer to memory on GPU where complex results are storedcomplex-to-real FFT Same as above, but with input and output field types reversed.
transform() [4/4]
template<size_t Dim, class T > void FFT< RCTransform, Dim, T >::transform (const char * directionName, ComplexField_t & f, RealField_t & g, const bool & constInput = false)
Member Data Documentation
complexDomain_m
template<size_t Dim, class T > Domain_t FFT< RCTransform, Dim, T >::complexDomain_m private
domain of the resulting complex fields const Domain_t& complexDomain_m;
Definition at line 490 of file FFT.h.
serialAxes_m
template<size_t Dim, class T > int FFT< RCTransform, Dim, T >::serialAxes_m private
number of axes to make serial
Definition at line 495 of file FFT.h.
tempFields_m
template<size_t Dim, class T > ComplexField_t** FFT< RCTransform, Dim, T >::tempFields_m private
The array of temporary fields, one for each transform direction These use the corresponding tempLayouts.
Definition at line 479 of file FFT.h.
tempLayouts_m
template<size_t Dim, class T > Layout_t** FFT< RCTransform, Dim, T >::tempLayouts_m private
How the temporary fields are laid out; these are computed from the input Field's domain. This will be allocated as an array of FieldLayouts with nTransformDims elements. Each is SERIAL along the zeroth dimension and the axes are permuted so that the transform direction is first
Definition at line 469 of file FFT.h.
tempRField_m
template<size_t Dim, class T > RealField_t* FFT< RCTransform, Dim, T >::tempRField_m private
We need one real internal Field in this case.
Definition at line 484 of file FFT.h.
tempRLayout_m
template<size_t Dim, class T > Layout_t* FFT< RCTransform, Dim, T >::tempRLayout_m private
extra layout for the one real Field needed
Definition at line 474 of file FFT.h.
The documentation for this class was generated from the following files:
ippl/src/FFT/FFT.h
ippl/src/FFT/FFT.hpp