OPAL (Object Oriented Parallel Accelerator Library): src/Classic/Parser/Token.cpp File Reference
Token.cpp File Reference
#include "Parser/Token.h"
#include "Utilities/ParseError.h"
#include <cctype>
#include <iostream>
#include <sstream>
Functions
std::ostream & operator<< (std::ostream &os, const Token &token)
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & os, const Token & token)
Definition at line 220 of file Token.cpp.
References Token::getInteger(), Token::getLex(), Token::getReal(), Token::getType(), Token::IS_DELIMITER, Token::IS_EOF, Token::IS_ERROR, Token::IS_INTEGER, Token::IS_REAL, Token::IS_STRING, and Token::IS_WORD.