OPAL (Object Oriented Parallel Accelerator Library): SequenceTemplate Class Reference
SequenceTemplate Class Reference
#include <SequenceTemplate.h>
Public Member Functions
SequenceTemplate ()
virtual ~SequenceTemplate ()
virtual SequenceTemplate * clone (const std::string &name)
Make clone.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Make line instance.
virtual Object * makeTemplate (const std::string &name, TokenStream &, Statement &)
Make a sequence template.
void parseTemplate (TokenStream &, Statement &)
Parse the sequence template.
Public Member Functions inherited from Macro
Macro (int size, const char *name, const char *help)
Exemplar constructor.
Macro (const std::string &name, Object *parent)
Clone constructor.
virtual ~Macro ()
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual void parseActuals (Statement &)
Parse actual arguments.
virtual void parseFormals (Statement &)
Parse formal arguments.
Public Member Functions inherited from Object
virtual ~Object ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
SequenceTemplate (const SequenceTemplate &)
void operator= (const SequenceTemplate &)
SequenceTemplate (const std::string &name, Object *parent)
Private Attributes
MacroStream body
Friends
class Sequence
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Macro
std::vector< std::string > formals
The formal argument list.
std::vector< std::vector< Token > > actuals
The actual argument list.
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 36 of file SequenceTemplate.h.
Constructor & Destructor Documentation
SequenceTemplate() [1/3]
SequenceTemplate::SequenceTemplate ()
Definition at line 41 of file SequenceTemplate.cpp.
~SequenceTemplate()
SequenceTemplate::~SequenceTemplate () virtual
Definition at line 54 of file SequenceTemplate.cpp.
SequenceTemplate() [2/3]
SequenceTemplate::SequenceTemplate (const SequenceTemplate &) private
SequenceTemplate() [3/3]
SequenceTemplate::SequenceTemplate (const std::string & name, Object * parent) private
Definition at line 49 of file SequenceTemplate.cpp.
Member Function Documentation
clone()
SequenceTemplate * SequenceTemplate::clone (const std::string & name) virtual
Make clone.
Reimplemented from Macro.
Definition at line 58 of file SequenceTemplate.cpp.
makeInstance()
Object * SequenceTemplate::makeInstance (const std::string & name, Statement & statement, const Parser *) virtual
Make line instance.
Reimplemented from Object.
Definition at line 65 of file SequenceTemplate.cpp.
References MacroStream::append(), Sequence::clone(), Object::copyAttributes(), OpalData::find(), OpalData::getInstance(), Token::getWord(), Token::isEOF(), Token::isWord(), name, OpalParser::run(), and MacroStream::start().
makeTemplate()
Object * SequenceTemplate::makeTemplate (const std::string & name, TokenStream & , Statement &) virtual
Make a sequence template.
Reimplemented from Object.
Definition at line 119 of file SequenceTemplate.cpp.
operator=()
void SequenceTemplate::operator= (const SequenceTemplate &) private
parseTemplate()
void SequenceTemplate::parseTemplate (TokenStream & is, Statement & statement)
Parse the sequence template.
Definition at line 125 of file SequenceTemplate.cpp.
References MacroStream::append(), body, Token::isDel(), Token::isEOF(), Token::isKey(), Statement::keyword(), Object::parse(), Macro::parseFormals(), PAssert, and TokenStream::readToken().
Referenced by Sequence::makeTemplate().
Friends And Related Function Documentation
Sequence
friend class Sequence friend
Definition at line 38 of file SequenceTemplate.h.
Member Data Documentation
body
MacroStream SequenceTemplate::body private
Definition at line 72 of file SequenceTemplate.h.
Referenced by parseTemplate().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Lines/SequenceTemplate.h
/psi/home/gsell/data/src/OPAL/src/src/Lines/SequenceTemplate.cpp