OPAL (Object Oriented Parallel Accelerator Library): IntSUDSImpl< 3U > Class Template Reference
IntSUDSImpl< 3U > Class Template Reference
#include <IntSUDS.h>
Public Member Functions
IntSUDSImpl ()
~IntSUDSImpl ()
Public Member Functions inherited from Interpolator
Interpolator ()
~Interpolator ()
Static Public Member Functions
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 3U, M, C > &f, const Vektor< PT, 3U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 3U, M, C > &f, const Vektor< PT, 3U > &ppos, const M &mesh, NDIndex< 3U > &ngp, Vektor< PT, 3U > &dpos)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 3U, M, C > &f, const NDIndex< 3U > &ngp, const Vektor< PT, 3U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 3U, M, C > &f, const Vektor< PT, 3U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 3U, M, C > &f, const Vektor< PT, 3U > &ppos, const M &mesh, NDIndex< 3U > &ngp, Vektor< PT, 3U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 3U, M, C > &f, const NDIndex< 3U > &ngp, const Vektor< PT, 3U > &dpos)
Additional Inherited Members
Static Protected Member Functions inherited from Interpolator
template<class T , unsigned Dim>
static CompressedBrickIterator< T, Dim > getFieldIter (const BareField< T, Dim > &f, const NDIndex< Dim > &pt)
Detailed Description
template<>
class IntSUDSImpl< 3U >
Definition at line 476 of file IntSUDS.h.
Constructor & Destructor Documentation
IntSUDSImpl()
IntSUDSImpl< 3U >::IntSUDSImpl () inline
Definition at line 480 of file IntSUDS.h.
~IntSUDSImpl()
IntSUDSImpl< 3U >::~IntSUDSImpl () inline
Definition at line 481 of file IntSUDS.h.
Member Function Documentation
gather() [1/3]
template<class FT , class M , class C , class PT > static void IntSUDSImpl< 3U >::gather (FT & pdata, const Field< FT, 3U, M, C > & f, const Vektor< PT, 3U > & ppos, const M & mesh) inline static
Definition at line 568 of file IntSUDS.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
gather() [2/3]
template<class FT , class M , class C , class PT > static void IntSUDSImpl< 3U >::gather (FT & pdata, const Field< FT, 3U, M, C > & f, const Vektor< PT, 3U > & ppos, const M & mesh, NDIndex< 3U > & ngp, Vektor< PT, 3U > & dpos) inline static
Definition at line 596 of file IntSUDS.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
gather() [3/3]
template<class FT , class M , class C , class PT > static void IntSUDSImpl< 3U >::gather (FT & pdata, const Field< FT, 3U, M, C > & f, const NDIndex< 3U > & ngp, const Vektor< PT, 3U > & dpos) inline static
Definition at line 624 of file IntSUDS.h.
References Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
scatter() [1/3]
template<class FT , class M , class C , class PT > static void IntSUDSImpl< 3U >::scatter (const FT & pdata, Field< FT, 3U, M, C > & f, const Vektor< PT, 3U > & ppos, const M & mesh) inline static
Definition at line 488 of file IntSUDS.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
scatter() [2/3]
template<class FT , class M , class C , class PT > static void IntSUDSImpl< 3U >::scatter (const FT & pdata, Field< FT, 3U, M, C > & f, const Vektor< PT, 3U > & ppos, const M & mesh, NDIndex< 3U > & ngp, Vektor< PT, 3U > & dpos) inline static
Definition at line 519 of file IntSUDS.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
scatter() [3/3]
template<class FT , class M , class C , class PT > static void IntSUDSImpl< 3U >::scatter (const FT & pdata, Field< FT, 3U, M, C > & f, const NDIndex< 3U > & ngp, const Vektor< PT, 3U > & dpos) inline static
Definition at line 550 of file IntSUDS.h.
References Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
The documentation for this class was generated from the following file:
ippl/src/Particle/IntSUDS.h