OPAL (Object Oriented Parallel Accelerator Library): HashPairBuilderPeriodic< PBase > Class Template Reference
HashPairBuilderPeriodic< PBase > Class Template Reference
#include <HashPairBuilderPeriodic.h>
Public Types
enum { Dim = PBase::Dim }
typedef PBase::Position_t Position_t
Public Member Functions
HashPairBuilderPeriodic (PBase &p)
template<class Pred , class OP >
void for_each (const Pred &pred, const OP &op, Vektor< double, 3 > extend_l, Vektor< double, 3 > extend_r)
Private Member Functions
template<class Pred >
int get_bucket_id (int i, const Pred &)
Private Attributes
PBase & particles
Vektor< int, 3 > buckets_per_dim
Vektor< double, 3 > h_chaining
Vektor< double, 3 > rmin_m
Vektor< double, 3 > rmax_m
Detailed Description
template<class PBase>
class HashPairBuilderPeriodic< PBase >
Definition at line 10 of file HashPairBuilderPeriodic.h.
Member Typedef Documentation
Position_t
template<class PBase > typedef PBase::Position_t HashPairBuilderPeriodic< PBase >::Position_t
Definition at line 14 of file HashPairBuilderPeriodic.h.
Member Enumeration Documentation
anonymous enum
template<class PBase > anonymous enum
Enumerator
Dim
Definition at line 13 of file HashPairBuilderPeriodic.h.
Constructor & Destructor Documentation
HashPairBuilderPeriodic()
template<class PBase > HashPairBuilderPeriodic< PBase >::HashPairBuilderPeriodic (PBase & p) inline
Definition at line 16 of file HashPairBuilderPeriodic.h.
Member Function Documentation
for_each()
template<class PBase > template<class Pred , class OP > void HashPairBuilderPeriodic< PBase >::for_each (const Pred & pred, const OP & op, Vektor< double, 3 > extend_l, Vektor< double, 3 > extend_r) inline
Definition at line 19 of file HashPairBuilderPeriodic.h.
References HashPairBuilderPeriodic< PBase >::buckets_per_dim, endl(), floor(), HashPairBuilderPeriodic< PBase >::get_bucket_id(), HashPairBuilderPeriodic< PBase >::h_chaining, max(), Hypervolume::n, HashPairBuilderPeriodic< PBase >::particles, HashPairBuilderPeriodic< PBase >::rmax_m, and HashPairBuilderPeriodic< PBase >::rmin_m.
get_bucket_id()
template<class PBase > template<class Pred > int HashPairBuilderPeriodic< PBase >::get_bucket_id (int i, const Pred &) inline private
Definition at line 157 of file HashPairBuilderPeriodic.h.
References HashPairBuilderPeriodic< PBase >::buckets_per_dim, HashPairBuilderPeriodic< PBase >::h_chaining, HashPairBuilderPeriodic< PBase >::particles, and HashPairBuilderPeriodic< PBase >::rmin_m.
Referenced by HashPairBuilderPeriodic< PBase >::for_each().
Member Data Documentation
buckets_per_dim
template<class PBase > Vektor<int,3> HashPairBuilderPeriodic< PBase >::buckets_per_dim private
Definition at line 171 of file HashPairBuilderPeriodic.h.
Referenced by HashPairBuilderPeriodic< PBase >::for_each(), and HashPairBuilderPeriodic< PBase >::get_bucket_id().
h_chaining
template<class PBase > Vektor<double,3> HashPairBuilderPeriodic< PBase >::h_chaining private
Definition at line 173 of file HashPairBuilderPeriodic.h.
Referenced by HashPairBuilderPeriodic< PBase >::for_each(), and HashPairBuilderPeriodic< PBase >::get_bucket_id().
particles
template<class PBase > PBase& HashPairBuilderPeriodic< PBase >::particles private
Definition at line 170 of file HashPairBuilderPeriodic.h.
Referenced by HashPairBuilderPeriodic< PBase >::for_each(), and HashPairBuilderPeriodic< PBase >::get_bucket_id().
rmax_m
template<class PBase > Vektor<double,3> HashPairBuilderPeriodic< PBase >::rmax_m private
Definition at line 175 of file HashPairBuilderPeriodic.h.
Referenced by HashPairBuilderPeriodic< PBase >::for_each().
rmin_m
template<class PBase > Vektor<double,3> HashPairBuilderPeriodic< PBase >::rmin_m private
Definition at line 174 of file HashPairBuilderPeriodic.h.
Referenced by HashPairBuilderPeriodic< PBase >::for_each(), and HashPairBuilderPeriodic< PBase >::get_bucket_id().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/PairBuilder/HashPairBuilderPeriodic.h