OPAL (Object Oriented Parallel Accelerator Library): ApplyField< T > Struct Template Reference
ApplyField< T > Struct Template Reference
Public Member Functions
ApplyField (T c, double r, double epsilon, double alpha)
void operator() (std::size_t i, std::size_t j, PartBunch &P, Vektor< double, 3 > &shift) const
Public Attributes
T C
double R
double eps
double a
Detailed Description
template<class T>
struct ApplyField< T >
Definition at line 76 of file P3MPoissonSolver.cpp.
Constructor & Destructor Documentation
ApplyField()
template<class T > ApplyField< T >::ApplyField (T c, double r, double epsilon, double alpha) inline
Definition at line 77 of file P3MPoissonSolver.cpp.
Member Function Documentation
operator()()
template<class T > void ApplyField< T >::operator() (std::size_t i, std::size_t j, PartBunch & P, Vektor< double, 3 > & shift) const inline
Definition at line 78 of file P3MPoissonSolver.cpp.
References ApplyField< T >::a, ApplyField< T >::C, Dim, PartBunchBase< T, Dim >::Ef, ApplyField< T >::eps, erf(), exp(), ke, PartBunchBase< T, Dim >::Phi, PartBunchBase< T, Dim >::Q, PartBunchBase< T, Dim >::R, and sqrt().
Member Data Documentation
a
template<class T > double ApplyField< T >::a
Definition at line 110 of file P3MPoissonSolver.cpp.
Referenced by ApplyField< T >::operator()().
C
template<class T > T ApplyField< T >::C
Definition at line 107 of file P3MPoissonSolver.cpp.
Referenced by ApplyField< T >::operator()().
eps
template<class T > double ApplyField< T >::eps
Definition at line 109 of file P3MPoissonSolver.cpp.
Referenced by ApplyField< T >::operator()().
R
template<class T > double ApplyField< T >::R
Definition at line 108 of file P3MPoissonSolver.cpp.
The documentation for this struct was generated from the following file:
src/Solvers/P3MPoissonSolver.cpp