OPAL (Object Oriented Parallel Accelerator Library): List Class Reference
List Class Reference
The LIST command.
#include <List.h>
Public Member Functions
List ()
Exemplar constructor.
virtual ~List ()
virtual List * clone (const std::string &name)
Make clone.
virtual void execute ()
Execute the command.
Public Member Functions inherited from Action
virtual ~Action ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
List (const List &)
void operator= (const List &)
List (const std::string &name, List *parent)
void list (std::ostream &, Table *)
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Action
Action (int size, const char *name, const char *help)
Constructor for exemplars.
Action (const std::string &name, Action *parent)
Constructor for cloning.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
The LIST command.
Definition at line 32 of file List.h.
Constructor & Destructor Documentation
List() [1/3]
List::List ()
Exemplar constructor.
Definition at line 50 of file List.cpp.
References Attrib::Distribution::FNAME, Object::itsAttr, Attributes::makeBool(), Attributes::makeString(), Attributes::makeTokenListArray(), Object::registerOwnership(), and AttributeHandler::STATEMENT.
Referenced by clone().
~List()
List::~List () virtual
Definition at line 71 of file List.cpp.
List() [2/3]
List::List (const List &) private
List() [3/3]
List::List (const std::string & name, List * parent) private
Definition at line 66 of file List.cpp.
Member Function Documentation
clone()
List * List::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 75 of file List.cpp.
References List(), and name.
execute()
void List::execute () virtual
Execute the command.
Reimplemented from Object.
Definition at line 80 of file List.cpp.
References Table::find(), Attrib::Distribution::FNAME, Attributes::getString(), Object::itsAttr, and list().
list()
void List::list (std::ostream & os, Table * table) private
Definition at line 106 of file List.cpp.
References Statement::delimiter(), Attributes::getBool(), Table::getDefault(), Object::getOpalName(), Attributes::getTokenListArray(), Statement::integer(), Object::itsAttr, Expressions::parseTableExpression(), Table::printTable(), and Statement::start().
Referenced by execute().
operator=()
void List::operator= (const List &) private
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Tables/List.h
/psi/home/gsell/data/src/OPAL/src/src/Tables/List.cpp