OPAL (Object Oriented Parallel Accelerator Library): Expressions::SAutomatic< T > Class Template Reference
Expressions::SAutomatic< T > Class Template Reference
Object attribute with an `‘automatic’' scalar value.
#include <SAutomatic.h>
Public Member Functions
SAutomatic (PtrToScalar< T > expr)
Constructor.
SAutomatic (const SAutomatic< T > &)
virtual ~SAutomatic ()
virtual SAutomatic< T > * clone () const
Make clone.
virtual T evaluate ()
Evaluate.
virtual void invalidate ()
Invalidate.
Public Member Functions inherited from Expressions::SDeferred< T >
SDeferred (PtrToScalar< T > expr)
Constructor.
SDeferred (const SDeferred< T > &)
virtual ~SDeferred ()
virtual bool isExpression () const
Return expression flag.
virtual void print (std::ostream &) const
Print the attribute value.
Public Member Functions inherited from Expressions::SValue< T >
SValue ()
Default constructor.
SValue (const T &val)
Constructor.
SValue (const SValue< T > &)
virtual ~SValue ()
template<>
void print (std::ostream &os) const
Print value.
template<>
void print (std::ostream &os) const
Print value.
template<>
void print (std::ostream &os) const
Print value.
Public Member Functions inherited from AttributeBase
AttributeBase ()
virtual ~AttributeBase ()
std::string getImage () const
Convert to string.
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
SAutomatic ()
void operator= (const SAutomatic< T > &)
Private Attributes
bool is_known
Additional Inherited Members
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Expressions::SDeferred< T >
PtrToScalar< T > expr_ptr
Pointer to expression.
Protected Attributes inherited from Expressions::SValue< T >
T value
The value of the attribute.
Detailed Description
template<class T>
class Expressions::SAutomatic< T >
Object attribute with an `‘automatic’' scalar value.
Definition at line 38 of file SAutomatic.h.
Constructor & Destructor Documentation
SAutomatic() [1/3]
template<class T > Expressions::SAutomatic< T >::SAutomatic (PtrToScalar< T > expr) explicit
Constructor.
Definition at line 82 of file SAutomatic.h.
References OpalData::getInstance(), and OpalData::registerExpression().
SAutomatic() [2/3]
template<class T > Expressions::SAutomatic< T >::SAutomatic (const SAutomatic< T > & rhs)
Definition at line 75 of file SAutomatic.h.
References OpalData::getInstance(), and OpalData::registerExpression().
~SAutomatic()
template<class T > Expressions::SAutomatic< T >::~SAutomatic () virtual
Definition at line 89 of file SAutomatic.h.
References OpalData::getInstance(), and OpalData::unregisterExpression().
SAutomatic() [3/3]
template<class T> Expressions::SAutomatic< T >::SAutomatic () private
Member Function Documentation
clone()
template<class T > SAutomatic< T > * Expressions::SAutomatic< T >::clone () const virtual
Make clone.
Reimplemented from Expressions::SDeferred< T >.
Definition at line 96 of file SAutomatic.h.
evaluate()
template<class T > T Expressions::SAutomatic< T >::evaluate () virtual
Evaluate.
Reimplemented from Expressions::SDeferred< T >.
Definition at line 102 of file SAutomatic.h.
References Expressions::SDeferred< T >::evaluate().
invalidate()
template<class T > void Expressions::SAutomatic< T >::invalidate () virtual
Invalidate.
Reimplemented from Invalidator.
Definition at line 113 of file SAutomatic.h.
operator=()
template<class T> void Expressions::SAutomatic< T >::operator= (const SAutomatic< T > &) private
Member Data Documentation
is_known
template<class T> bool Expressions::SAutomatic< T >::is_known mutable private
Definition at line 67 of file SAutomatic.h.
The documentation for this class was generated from the following file:
src/Expressions/SAutomatic.h