OPAL (Object Oriented Parallel Accelerator Library): Corrector Class Reference
Corrector Class Reference abstract
Interface for general corrector.
#include <Corrector.h>
Public Types
enum Plane { OFF, X, Y, XY }
Plane selection.
Public Member Functions
Corrector (const std::string &name)
Constructor with given name.
Corrector ()
Corrector (const Corrector &right)
virtual ~Corrector ()
virtual void accept (BeamlineVisitor &) const
Apply a visitor to Corrector.
virtual BDipoleField & getField ()=0
Return the corrector field.
virtual const BDipoleField & getField () const =0
Return the corrector field.
virtual StraightGeometry & getGeometry ()=0
Return the corrector geometry.
virtual const StraightGeometry & getGeometry () const =0
Return the corrector geometry. Version for const object.
virtual Plane getPlane () const =0
Return the plane on which the corrector acts.
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B)
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField)
virtual void goOnline (const double &kineticEnergy)
virtual void finalise ()
virtual bool bends () const
virtual ElementType getType () const
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const
void setKickX (double k)
void setKickY (double k)
virtual void setDesignEnergy (const double &ekin, bool changeable=true)
double getKickX () const
double getKickY () const
void setKickField (const Vector_t &k0)
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void goOffline ()
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Member Functions
void operator= (const Corrector &)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes
Plane plane_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Private Attributes
double kickX_m
double kickY_m
double designEnergy_m
bool designEnergyChangeable_m
bool kickFieldSet_m
Vector_t kickField_m
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Interface for general corrector.
Definition at line 35 of file Corrector.h.
Member Enumeration Documentation
Plane
enum Corrector::Plane
Plane selection.
Enumerator
OFF
Corrector is off (inactive).
X
Corrector acts on x-plane.
Y
Corrector acts on y-plane.
XY
Corrector acts on both planes.
Definition at line 40 of file Corrector.h.
Constructor & Destructor Documentation
Corrector() [1/3]
Corrector::Corrector (const std::string & name) explicit
Constructor with given name.
Definition at line 48 of file Corrector.cpp.
Corrector() [2/3]
Corrector::Corrector ()
Definition at line 32 of file Corrector.cpp.
Corrector() [3/3]
Corrector::Corrector (const Corrector & right)
Definition at line 37 of file Corrector.cpp.
~Corrector()
Corrector::~Corrector () virtual
Definition at line 59 of file Corrector.cpp.
Member Function Documentation
accept()
void Corrector::accept (BeamlineVisitor & visitor) const virtual
Apply a visitor to Corrector.
Implements ElementBase.
Definition at line 63 of file Corrector.cpp.
References BeamlineVisitor::visitCorrector().
apply() [1/2]
bool Corrector::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) virtual
Reimplemented from Component.
Definition at line 67 of file Corrector.cpp.
References PartBunchBase< T, Dim >::P, Attrib::Distribution::R, PartBunchBase< T, Dim >::R, and Component::RefPartBunch_m.
apply() [2/2]
bool Corrector::apply (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) virtual
Reimplemented from Component.
Definition at line 74 of file Corrector.cpp.
References Physics::c, PartBunchBase< T, Dim >::getdT(), ElementBase::getElementLength(), ElementBase::getFlagDeleteOnTransverseExit(), Util::getGamma(), ElementBase::isInsideTransverse(), kickField_m, Attrib::Distribution::R, and Component::RefPartBunch_m.
bends()
bool Corrector::bends () const virtual
Implements Component.
Definition at line 141 of file Corrector.cpp.
finalise()
void Corrector::finalise () virtual
Implements Component.
Definition at line 105 of file Corrector.cpp.
getDimensions()
void Corrector::getDimensions (double & zBegin, double & zEnd) const virtual
Implements Component.
Definition at line 145 of file Corrector.cpp.
References ElementBase::getElementLength().
getField() [1/2]
virtual BDipoleField& Corrector::getField () pure virtual
Return the corrector field.
Implements Component.
Implemented in CorrectorRep.
getField() [2/2]
virtual const BDipoleField& Corrector::getField () const pure virtual
Return the corrector field.
Implements Component.
Implemented in CorrectorRep.
getGeometry() [1/2]
virtual StraightGeometry& Corrector::getGeometry () pure virtual
Return the corrector geometry.
Implements ElementBase.
Implemented in CorrectorRep.
Referenced by goOnline(), and setDesignEnergy().
getGeometry() [2/2]
virtual const StraightGeometry& Corrector::getGeometry () const pure virtual
Return the corrector geometry. Version for const object.
Implements ElementBase.
Implemented in CorrectorRep.
getKickX()
double Corrector::getKickX () const inline
Definition at line 142 of file Corrector.h.
References kickX_m.
getKickY()
double Corrector::getKickY () const inline
Definition at line 147 of file Corrector.h.
References kickY_m.
getPlane()
virtual Plane Corrector::getPlane () const pure virtual
Return the plane on which the corrector acts.
Implemented in CorrectorRep, XCorrectorRep, and YCorrectorRep.
getType()
ElementType Corrector::getType () const virtual
Get element type std::string.
Reimplemented from Component.
Definition at line 151 of file Corrector.cpp.
References CORRECTOR.
goOnline()
void Corrector::goOnline (const double & kineticEnergy) virtual
Reimplemented from Component.
Definition at line 108 of file Corrector.cpp.
References Physics::c, designEnergy_m, PartBunchBase< T, Dim >::getdT(), StraightGeometry::getElementLength(), getGeometry(), PartBunchBase< T, Dim >::getM(), kickFieldSet_m, pow(), Component::RefPartBunch_m, and sqrt().
initialise()
void Corrector::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) virtual
Implements Component.
Definition at line 100 of file Corrector.cpp.
References ElementBase::getElementLength(), and Component::RefPartBunch_m.
operator=()
void Corrector::operator= (const Corrector &) protected
setDesignEnergy()
void Corrector::setDesignEnergy (const double & ekin, bool changeable = true) virtual
Reimplemented from Component.
Definition at line 126 of file Corrector.cpp.
References designEnergy_m, designEnergyChangeable_m, StraightGeometry::getElementLength(), getGeometry(), PartBunchBase< T, Dim >::getM(), kickFieldSet_m, pow(), Component::RefPartBunch_m, and sqrt().
Referenced by OpalHKicker::update(), OpalVKicker::update(), and OpalKicker::update().
setKickField()
void Corrector::setKickField (const Vector_t & k0) inline
Definition at line 152 of file Corrector.h.
References kickField_m, and kickFieldSet_m.
Referenced by OpalHKicker::update(), OpalVKicker::update(), and OpalKicker::update().
setKickX()
void Corrector::setKickX (double k) inline
Definition at line 132 of file Corrector.h.
References kickX_m.
Referenced by OpalHKicker::update(), and OpalKicker::update().
setKickY()
void Corrector::setKickY (double k) inline
Definition at line 137 of file Corrector.h.
References kickY_m.
Referenced by OpalVKicker::update(), and OpalKicker::update().
Member Data Documentation
designEnergy_m
double Corrector::designEnergy_m private
Definition at line 117 of file Corrector.h.
Referenced by goOnline(), and setDesignEnergy().
designEnergyChangeable_m
bool Corrector::designEnergyChangeable_m private
Definition at line 118 of file Corrector.h.
Referenced by setDesignEnergy().
kickField_m
Vector_t Corrector::kickField_m private
Definition at line 121 of file Corrector.h.
Referenced by apply(), and setKickField().
kickFieldSet_m
bool Corrector::kickFieldSet_m private
Definition at line 119 of file Corrector.h.
Referenced by goOnline(), setDesignEnergy(), and setKickField().
kickX_m
double Corrector::kickX_m private
Definition at line 115 of file Corrector.h.
Referenced by getKickX(), and setKickX().
kickY_m
double Corrector::kickY_m private
Definition at line 116 of file Corrector.h.
Referenced by getKickY(), and setKickY().
plane_m
Plane Corrector::plane_m protected
Definition at line 128 of file Corrector.h.
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/AbsBeamline/Corrector.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/AbsBeamline/Corrector.cpp