OPAL (Object Oriented Parallel Accelerator Library): Replacer Class Reference
Replacer Class Reference
Replace all references to named element by a new version.
#include <Replacer.h>
Public Member Functions
Replacer (const Beamline &, const std::string &name, ElementBase *elm)
Constructor.
virtual ~Replacer ()
virtual void visitFlaggedElmPtr (const FlaggedElmPtr &)
Apply the visitor to an FlaggedElmPtr.
Public Member Functions inherited from DefaultVisitor
DefaultVisitor (const Beamline &beamline, bool backBeam, bool backTrack)
Constructor.
virtual ~DefaultVisitor ()=0
virtual void execute ()
Apply the algorithm to the top-level beamline.
virtual void visitBeamline (const Beamline &)
Apply the algorithm to a beam line.
virtual void visitCCollimator (const CCollimator &)
Apply the algorithm to a collimator.
virtual void visitComponent (const Component &)
Apply the algorithm to an arbitrary component.
virtual void visitCorrector (const Corrector &)
Apply the algorithm to a closed orbit corrector.
virtual void visitCyclotron (const Cyclotron &)
Apply the algorithm to an cyclotron.
virtual void visitDegrader (const Degrader &)
Apply the algorithm to a degrader.
virtual void visitDrift (const Drift &)
Apply the algorithm to a drift space.
virtual void visitFlexibleCollimator (const FlexibleCollimator &)
Apply the algorithm to a flexible collimator.
virtual void visitMarker (const Marker &)
Apply the algorithm to a marker.
virtual void visitMonitor (const Monitor &)
Apply the algorithm to a beam position monitor.
virtual void visitMultipole (const Multipole &)
Apply the algorithm to a multipole.
virtual void visitMultipoleT (const MultipoleT &)
Apply the algorithm to to an arbitrary multipole.
virtual void visitMultipoleTStraight (const MultipoleTStraight &)
Apply the algorithm to an arbitrary straight multipole.
virtual void visitMultipoleTCurvedConstRadius (const MultipoleTCurvedConstRadius &)
Apply the algorithm to an arbitrary curved multipole of constant radius.
virtual void visitMultipoleTCurvedVarRadius (const MultipoleTCurvedVarRadius &)
Apply the algorithm to an arbitrary curved multipole of variable radius.
virtual void visitOffset (const Offset &)
Apply the algorithm to an offset (placement).
virtual void visitProbe (const Probe &prob)
Apply the algorithm to a probe.
virtual void visitRBend (const RBend &)
Apply the algorithm to a rectangular bend.
virtual void visitRBend3D (const RBend3D &)
Apply the algorithm to a rectangular bend.
virtual void visitRFCavity (const RFCavity &)
Apply the algorithm to a RF cavity.
virtual void visitRing (const Ring &)
Apply the algorithm to a ring.
virtual void visitSBend (const SBend &)
Apply the algorithm to a sector bend.
virtual void visitSBend3D (const SBend3D &)
Apply the algorithm to a sector bend with 3D field map.
virtual void visitScalingFFAMagnet (const ScalingFFAMagnet &)
Apply the algorithm to a scaling FFA magnet.
virtual void visitSeptum (const Septum &)
Apply the algorithm to a septum.
virtual void visitSolenoid (const Solenoid &)
Apply the algorithm to a solenoid.
virtual void visitSource (const Source &)
Apply the algorithm to a source.
virtual void visitStripper (const Stripper &)
Apply the algorithm to a particle stripper.
virtual void visitTravelingWave (const TravelingWave &)
Apply the algorithm to a traveling wave.
virtual void visitVacuum (const Vacuum &)
Apply the algorithm to a vacuum space.
virtual void visitVariableRFCavity (const VariableRFCavity &vcav)
Apply the algorithm to a a variable RF cavity.
virtual void visitVariableRFCavityFringeField (const VariableRFCavityFringeField &vcav)
Apply the algorithm to a a variable RF cavity with Fringe Field.
virtual void visitVerticalFFAMagnet (const VerticalFFAMagnet &)
Apply the algorithm to a vertical FFA magnet.
Public Member Functions inherited from BeamlineVisitor
BeamlineVisitor ()
virtual ~BeamlineVisitor ()
Private Member Functions
Replacer ()
Replacer (const Replacer &)
void operator= (const Replacer &)
Private Attributes
const std::string itsName
ElementBase * newBase
Additional Inherited Members
Protected Attributes inherited from DefaultVisitor
const Beamline & itsLine
bool back_beam
bool back_track
bool back_path
double flip_B
double flip_s
Detailed Description
Replace all references to named element by a new version.
Definition at line 32 of file Replacer.h.
Constructor & Destructor Documentation
Replacer() [1/3]
Replacer::Replacer (const Beamline & beamline, const std::string & name, ElementBase * elm)
Constructor.
Definition at line 32 of file Replacer.cpp.
~Replacer()
Replacer::~Replacer () virtual
Definition at line 41 of file Replacer.cpp.
Replacer() [2/3]
Replacer::Replacer () private
Replacer() [3/3]
Replacer::Replacer (const Replacer &) private
Member Function Documentation
operator=()
void Replacer::operator= (const Replacer &) private
visitFlaggedElmPtr()
void Replacer::visitFlaggedElmPtr (const FlaggedElmPtr & fep) virtual
Apply the visitor to an FlaggedElmPtr.
Reimplemented from DefaultVisitor.
Definition at line 45 of file Replacer.cpp.
References ElementBase::copyStructure(), ElmPtr::getElement(), ElementBase::getName(), itsName, name, newBase, Element::setElement(), and DefaultVisitor::visitFlaggedElmPtr().
Member Data Documentation
itsName
const std::string Replacer::itsName private
Definition at line 53 of file Replacer.h.
Referenced by visitFlaggedElmPtr().
newBase
ElementBase* Replacer::newBase private
Definition at line 56 of file Replacer.h.
Referenced by visitFlaggedElmPtr().
The documentation for this class was generated from the following files:
src/Lines/Replacer.h
src/Lines/Replacer.cpp