OPAL (Object Oriented Parallel Accelerator Library): Message::MsgItem Class Reference
Message::MsgItem Class Reference
#include <Message.h>
Classes
struct MsgItemBuf
Public Member Functions
MsgItem ()
MsgItem (void *d, unsigned int elems, unsigned int totbytes, bool needcopy, bool needdel)
MsgItem (const MsgItem &m)
~MsgItem ()
unsigned int numBytes () const
unsigned int numElems () const
unsigned int elemSize () const
bool willNeedDelete () const
void cancelDelete ()
void * data ()
void deleteData ()
Private Attributes
void * item
unsigned int elements
unsigned int bytesize
MsgItemBuf defbuf
bool needDelete
Detailed Description
Definition at line 150 of file Message.h.
Constructor & Destructor Documentation
MsgItem() [1/3]
Message::MsgItem::MsgItem () inline
Definition at line 166 of file Message.h.
MsgItem() [2/3]
Message::MsgItem::MsgItem (void * d, unsigned int elems, unsigned int totbytes, bool needcopy, bool needdel) inline
Definition at line 169 of file Message.h.
References item, and needDelete.
MsgItem() [3/3]
Message::MsgItem::MsgItem (const MsgItem & m) inline
Definition at line 206 of file Message.h.
References defbuf, and item.
~MsgItem()
Message::MsgItem::~MsgItem () inline
Definition at line 215 of file Message.h.
Member Function Documentation
cancelDelete()
void Message::MsgItem::cancelDelete () inline
Definition at line 238 of file Message.h.
References needDelete.
Referenced by Message::remove().
data()
void* Message::MsgItem::data () inline
Definition at line 244 of file Message.h.
References item.
Referenced by MsgBuffer::add(), Communicate::fill_msg_buffer(), PutSingleItem< T, false, false >::get_iter(), BrickIterator< T, Dim >::getMessage(), Message::getmsg(), reduce(), Message::remove(), and scatter().
deleteData()
void Message::MsgItem::deleteData () inline
Definition at line 250 of file Message.h.
References item, and willNeedDelete().
elemSize()
unsigned int Message::MsgItem::elemSize () const inline
Definition at line 226 of file Message.h.
References bytesize.
numBytes()
unsigned int Message::MsgItem::numBytes () const inline
Definition at line 218 of file Message.h.
References bytesize.
Referenced by MsgBuffer::add(), Communicate::fill_msg_buffer(), Communicate::find_msg_length(), Format::Format(), Message::getmsg(), operator<<(), and Message::remove().
numElems()
unsigned int Message::MsgItem::numElems () const inline
Definition at line 222 of file Message.h.
References elements.
Referenced by MsgBuffer::add(), Communicate::fill_msg_buffer(), Format::Format(), PutSingleItem< T, false, false >::get_iter(), and operator<<().
willNeedDelete()
bool Message::MsgItem::willNeedDelete () const inline
Definition at line 232 of file Message.h.
References item, and needDelete.
Referenced by deleteData(), operator<<(), and Message::remove().
Member Data Documentation
bytesize
unsigned int Message::MsgItem::bytesize private
Definition at line 261 of file Message.h.
Referenced by elemSize(), and numBytes().
defbuf
MsgItemBuf Message::MsgItem::defbuf private
Definition at line 264 of file Message.h.
Referenced by MsgItem().
elements
unsigned int Message::MsgItem::elements private
Definition at line 261 of file Message.h.
Referenced by numElems().
item
void* Message::MsgItem::item private
Definition at line 258 of file Message.h.
Referenced by data(), deleteData(), MsgItem(), and willNeedDelete().
needDelete
bool Message::MsgItem::needDelete private
Definition at line 267 of file Message.h.
Referenced by cancelDelete(), MsgItem(), and willNeedDelete().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Message/Message.h