OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Classic/Algorithms/Quaternion.h File Reference
Quaternion.h File Reference
#include "AppTypes/Vektor.h"
#include "Algorithms/BoostMatrix.h"
#include "Algorithms/Vektor.h"
Classes
class Quaternion
Typedefs
typedef Quaternion Quaternion_t
Functions
Quaternion getQuaternion (Vector_t vec, Vector_t reference)
Typedef Documentation
Quaternion_t
typedef Quaternion Quaternion_t
Definition at line 42 of file Quaternion.h.
Function Documentation
getQuaternion()
Quaternion getQuaternion (Vector_t vec, Vector_t reference)
Definition at line 34 of file Quaternion.cpp.
References abs(), cos(), cross(), dot(), Physics::e, IpplRandom, Physics::pi, Hypervolume::ref, sin(), and sqrt().
Referenced by ParallelTTracker::applyFractionalStep(), ParallelTTracker::computeSpaceChargeFields(), ParallelTTracker::computeWakefield(), Monitor::driftToCorrectPositionAndSave(), Bend2D::getOutline(), Bend2D::setFieldCalcParam(), and ParallelTTracker::updateRefToLabCSTrafo().