OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyEnge Namespace Reference
PyOpal::PyEnge Namespace Reference
Functions
BOOST_PYTHON_MODULE (enge)
Variables
const char * module_docstring
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyEnge::BOOST_PYTHON_MODULE (enge)
Definition at line 30 of file PyEnge.cpp.
References PyOpal::Globals::Initialise(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_class(), and PyOpal::ExceptionTranslation::registerExceptions().
Variable Documentation
module_docstring
const char* PyOpal::PyEnge::module_docstring
Initial value:
=
"enge module holds an Enge end field 'plugin' class for use with field models\n"
Definition at line 12 of file PyEnge.cpp.