OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Field/CompressedBrickIterator.h File Reference
CompressedBrickIterator.h File Reference
#include "Field/BrickIterator.h"
#include <iostream>
#include "Field/CompressedBrickIterator.hpp"
Classes
class CompressedBrickIterator< T, Dim >
class CompressedBrickIterator< T, Dim >
Functions
template<class T , unsigned D1, unsigned D2>
CompressedBrickIterator< T, D2 > permute (const CompressedBrickIterator< T, D1 > &, const NDIndex< D1 > &, const NDIndex< D2 > &)
Function Documentation
permute()
template<class T , unsigned D1, unsigned D2> CompressedBrickIterator<T,D2> permute (const CompressedBrickIterator< T, D1 > & , const NDIndex< D1 > & , const NDIndex< D2 > &)
Definition at line 278 of file CompressedBrickIterator.hpp.
References CompressedBrickIterator< T, Dim >::GetCompressedData(), CompressedBrickIterator< T, Dim >::GetStride(), and CompressedBrickIterator< T, Dim >::IsCompressed().
Referenced by CompressedBrickIterator< T, Dim >::permute().