OPAL (Object Oriented Parallel Accelerator Library): mslang::Difference Struct Reference
mslang::Difference Struct Reference
#include <Difference.h>
Public Member Functions
Difference ()
Difference (const Difference &right)
virtual ~Difference ()
virtual void print (int indentwidth)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Public Member Functions inherited from mslang::Function
virtual ~Function ()
virtual void apply (std::vector< std::shared_ptr< Base >> &bfuncs)=0
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
Static Public Member Functions inherited from mslang::Function
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
Function * dividend_m
Function * divisor_m
Additional Inherited Members
Static Public Attributes inherited from mslang::Function
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\((.*)"
Detailed Description
Definition at line 7 of file Difference.h.
Constructor & Destructor Documentation
Difference() [1/2]
mslang::Difference::Difference () inline
Definition at line 11 of file Difference.h.
Difference() [2/2]
mslang::Difference::Difference (const Difference & right) inline
Definition at line 14 of file Difference.h.
~Difference()
virtual mslang::Difference::~Difference () inline virtual
Definition at line 19 of file Difference.h.
References dividend_m, and divisor_m.
Member Function Documentation
apply()
void mslang::Difference::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Definition at line 16 of file Difference.cpp.
References mslang::Function::apply(), dividend_m, and divisor_m.
parse_detail()
bool mslang::Difference::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 32 of file Difference.cpp.
References dividend_m, divisor_m, end(), and mslang::Function::parse().
Referenced by mslang::Function::parse().
print()
void mslang::Difference::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 6 of file Difference.cpp.
References dividend_m, divisor_m, and mslang::Function::print().
Member Data Documentation
dividend_m
Function* mslang::Difference::dividend_m
Definition at line 8 of file Difference.h.
Referenced by apply(), parse_detail(), print(), and ~Difference().
divisor_m
Function* mslang::Difference::divisor_m
Definition at line 9 of file Difference.h.
Referenced by apply(), parse_detail(), print(), and ~Difference().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Difference.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Difference.cpp