OPAL (Object Oriented Parallel Accelerator Library): ParticleMatterInteractionHandler Class Reference
ParticleMatterInteractionHandler Class Reference abstract
#include <ParticleMatterInteractionHandler.h>
Public Member Functions
ParticleMatterInteractionHandler (std::string name, ElementBase *elref)
virtual ~ParticleMatterInteractionHandler ()
virtual void apply (PartBunchBase< double, 3 > *bunch, const std::pair< Vector_t, double > &boundingSphere)=0
virtual const std::string getType () const =0
virtual void print (Inform &os)=0
virtual bool stillActive ()=0
virtual double getTime ()=0
virtual std::string getName ()=0
virtual size_t getParticlesInMat ()=0
virtual unsigned getRediffused ()=0
virtual unsigned int getNumEntered ()=0
void setFlagAllParticlesIn (bool p)
bool getFlagAllParticlesIn () const
void updateElement (ElementBase *newref)
ElementBase * getElement ()
virtual bool computeEnergyLoss (PartBunchBase< double, 3 > *bunch, Vector_t &P, const double deltat, bool includeFluctuations=true) const =0
Protected Attributes
ElementBase * element_ref_m
bool allParticleInMat_m
if all particles are in matter stay inside the particle matter interaction
const std::string name_m
std::unique_ptr< InsideTester > hitTester_m
Detailed Description
Definition at line 38 of file ParticleMatterInteractionHandler.h.
Constructor & Destructor Documentation
ParticleMatterInteractionHandler()
ParticleMatterInteractionHandler::ParticleMatterInteractionHandler (std::string name, ElementBase * elref) inline
Definition at line 74 of file ParticleMatterInteractionHandler.h.
~ParticleMatterInteractionHandler()
virtual ParticleMatterInteractionHandler::~ParticleMatterInteractionHandler () inline virtual
Definition at line 42 of file ParticleMatterInteractionHandler.h.
Member Function Documentation
apply()
virtual void ParticleMatterInteractionHandler::apply (PartBunchBase< double, 3 > * bunch, const std::pair< Vector_t, double > & boundingSphere) pure virtual
Implemented in ScatteringPhysics, and BeamStrippingPhysics.
Referenced by Vacuum::checkVacuum(), and CCollimator::doFinaliseCheck().
computeEnergyLoss()
virtual bool ParticleMatterInteractionHandler::computeEnergyLoss (PartBunchBase< double, 3 > * bunch, Vector_t & P, const double deltat, bool includeFluctuations = true) const pure virtual
Implemented in BeamStrippingPhysics, and ScatteringPhysics.
Referenced by Degrader::applyToReferenceParticle().
getElement()
ElementBase * ParticleMatterInteractionHandler::getElement () inline
Definition at line 86 of file ParticleMatterInteractionHandler.h.
References element_ref_m.
Referenced by ParticleMatterInteraction::print(), and Vacuum::print().
getFlagAllParticlesIn()
bool ParticleMatterInteractionHandler::getFlagAllParticlesIn () const inline
Definition at line 96 of file ParticleMatterInteractionHandler.h.
References allParticleInMat_m.
getName()
virtual std::string ParticleMatterInteractionHandler::getName () pure virtual
Implemented in ScatteringPhysics, and BeamStrippingPhysics.
getNumEntered()
virtual unsigned int ParticleMatterInteractionHandler::getNumEntered () pure virtual
Implemented in ScatteringPhysics, and BeamStrippingPhysics.
getParticlesInMat()
virtual size_t ParticleMatterInteractionHandler::getParticlesInMat () pure virtual
Implemented in ScatteringPhysics, and BeamStrippingPhysics.
Referenced by CCollimator::doFinaliseCheck().
getRediffused()
virtual unsigned ParticleMatterInteractionHandler::getRediffused () pure virtual
Implemented in ScatteringPhysics, and BeamStrippingPhysics.
getTime()
virtual double ParticleMatterInteractionHandler::getTime () pure virtual
Implemented in ScatteringPhysics, and BeamStrippingPhysics.
getType()
virtual const std::string ParticleMatterInteractionHandler::getType () const pure virtual
Implemented in ScatteringPhysics, and BeamStrippingPhysics.
print()
virtual void ParticleMatterInteractionHandler::print (Inform & os) pure virtual
Implemented in ScatteringPhysics, and BeamStrippingPhysics.
Referenced by Vacuum::checkVacuum(), and CCollimator::doFinaliseCheck().
setFlagAllParticlesIn()
void ParticleMatterInteractionHandler::setFlagAllParticlesIn (bool p) inline
Definition at line 91 of file ParticleMatterInteractionHandler.h.
References allParticleInMat_m.
Referenced by ParallelTTracker::computeParticleMatterInteraction(), and CCollimator::doFinaliseCheck().
stillActive()
virtual bool ParticleMatterInteractionHandler::stillActive () pure virtual
Implemented in ScatteringPhysics, and BeamStrippingPhysics.
Referenced by CCollimator::doFinaliseCheck().
updateElement()
void ParticleMatterInteractionHandler::updateElement (ElementBase * newref) inline
Definition at line 81 of file ParticleMatterInteractionHandler.h.
References element_ref_m.
Referenced by ElementBase::ElementBase(), and ParticleMatterInteraction::updateElement().
Member Data Documentation
allParticleInMat_m
bool ParticleMatterInteractionHandler::allParticleInMat_m protected
if all particles are in matter stay inside the particle matter interaction
Definition at line 66 of file ParticleMatterInteractionHandler.h.
Referenced by ScatteringPhysics::apply(), getFlagAllParticlesIn(), and setFlagAllParticlesIn().
element_ref_m
ElementBase* ParticleMatterInteractionHandler::element_ref_m protected
Definition at line 64 of file ParticleMatterInteractionHandler.h.
Referenced by ScatteringPhysics::addBackToBunch(), BeamStrippingPhysics::apply(), ScatteringPhysics::copyFromBunch(), getElement(), BeamStrippingPhysics::getName(), ScatteringPhysics::getName(), BeamStrippingPhysics::print(), ScatteringPhysics::print(), ScatteringPhysics::ScatteringPhysics(), ScatteringPhysics::setTimeStepForLeavingParticles(), and updateElement().
hitTester_m
std::unique_ptr<InsideTester> ParticleMatterInteractionHandler::hitTester_m protected
Definition at line 70 of file ParticleMatterInteractionHandler.h.
Referenced by ScatteringPhysics::addBackToBunch(), BeamStrippingPhysics::apply(), ScatteringPhysics::computeInteraction(), ScatteringPhysics::copyFromBunch(), BeamStrippingPhysics::doPhysics(), and ScatteringPhysics::ScatteringPhysics().
name_m
const std::string ParticleMatterInteractionHandler::name_m protected
Definition at line 68 of file ParticleMatterInteractionHandler.h.
Referenced by BeamStrippingPhysics::getName(), ScatteringPhysics::getName(), BeamStrippingPhysics::print(), and ScatteringPhysics::print().
The documentation for this class was generated from the following file:
src/Classic/Solvers/ParticleMatterInteractionHandler.h