OPAL (Object Oriented Parallel Accelerator Library): Selector Class Reference
Selector Class Reference
#include <Selector.h>
Public Member Functions
Selector (const Beamline &, const RangeRep &range, const std::string &cName, const std::string &tName, const std::string &pString)
Constructor.
virtual ~Selector ()
virtual void execute ()
Execute the selection.
int getCount () const
Return the count of selected elements.
Public Member Functions inherited from RangeSelector
RangeSelector (const Beamline &, const RangeRep &range)
Constructor.
virtual ~RangeSelector ()
virtual void visitFlaggedElmPtr (const FlaggedElmPtr &)
Apply the visitor to an FlaggedElmPtr.
Public Member Functions inherited from DefaultVisitor
DefaultVisitor (const Beamline &beamline, bool backBeam, bool backTrack)
Constructor.
virtual ~DefaultVisitor ()=0
virtual void visitBeamline (const Beamline &)
Apply the algorithm to a beam line.
virtual void visitCCollimator (const CCollimator &)
Apply the algorithm to a collimator.
virtual void visitComponent (const Component &)
Apply the algorithm to an arbitrary component.
virtual void visitCorrector (const Corrector &)
Apply the algorithm to a closed orbit corrector.
virtual void visitCyclotron (const Cyclotron &)
Apply the algorithm to an cyclotron.
virtual void visitDegrader (const Degrader &)
Apply the algorithm to a degrader.
virtual void visitDrift (const Drift &)
Apply the algorithm to a drift space.
virtual void visitFlexibleCollimator (const FlexibleCollimator &)
Apply the algorithm to a flexible collimator.
virtual void visitMarker (const Marker &)
Apply the algorithm to a marker.
virtual void visitMonitor (const Monitor &)
Apply the algorithm to a beam position monitor.
virtual void visitMultipole (const Multipole &)
Apply the algorithm to a multipole.
virtual void visitMultipoleT (const MultipoleT &)
Apply the algorithm to to an arbitrary multipole.
virtual void visitMultipoleTStraight (const MultipoleTStraight &)
Apply the algorithm to an arbitrary straight multipole.
virtual void visitMultipoleTCurvedConstRadius (const MultipoleTCurvedConstRadius &)
Apply the algorithm to an arbitrary curved multipole of constant radius.
virtual void visitMultipoleTCurvedVarRadius (const MultipoleTCurvedVarRadius &)
Apply the algorithm to an arbitrary curved multipole of variable radius.
virtual void visitOffset (const Offset &)
Apply the algorithm to an offset (placement).
virtual void visitProbe (const Probe &prob)
Apply the algorithm to a probe.
virtual void visitRBend (const RBend &)
Apply the algorithm to a rectangular bend.
virtual void visitRBend3D (const RBend3D &)
Apply the algorithm to a rectangular bend.
virtual void visitRFCavity (const RFCavity &)
Apply the algorithm to a RF cavity.
virtual void visitRing (const Ring &)
Apply the algorithm to a ring.
virtual void visitSBend (const SBend &)
Apply the algorithm to a sector bend.
virtual void visitSBend3D (const SBend3D &)
Apply the algorithm to a sector bend with 3D field map.
virtual void visitScalingFFAMagnet (const ScalingFFAMagnet &)
Apply the algorithm to a scaling FFA magnet.
virtual void visitSeptum (const Septum &)
Apply the algorithm to a septum.
virtual void visitSolenoid (const Solenoid &)
Apply the algorithm to a solenoid.
virtual void visitSource (const Source &)
Apply the algorithm to a source.
virtual void visitStripper (const Stripper &)
Apply the algorithm to a particle stripper.
virtual void visitTravelingWave (const TravelingWave &)
Apply the algorithm to a traveling wave.
virtual void visitVacuum (const Vacuum &)
Apply the algorithm to a vacuum space.
virtual void visitVariableRFCavity (const VariableRFCavity &vcav)
Apply the algorithm to a a variable RF cavity.
virtual void visitVariableRFCavityFringeField (const VariableRFCavityFringeField &vcav)
Apply the algorithm to a a variable RF cavity with Fringe Field.
virtual void visitVerticalFFAMagnet (const VerticalFFAMagnet &)
Apply the algorithm to a vertical FFA magnet.
Public Member Functions inherited from BeamlineVisitor
BeamlineVisitor ()
virtual ~BeamlineVisitor ()
Protected Member Functions
virtual void handleElement (const FlaggedElmPtr &)
The operation to be done for elements.
Protected Member Functions inherited from RangeSelector
virtual void handleBeamline (const FlaggedElmPtr &)
The operation to be done for beamlines.
Private Member Functions
Selector ()
Selector (const Selector &)
void operator= (const Selector &)
Private Attributes
const Element * itsClass
const std::string itsType
const RegularExpression * itsPattern
int itsCount
Additional Inherited Members
Protected Attributes inherited from RangeSelector
RangeRep itsRange
Working data for range.
Protected Attributes inherited from DefaultVisitor
const Beamline & itsLine
bool back_beam
bool back_track
bool back_path
double flip_B
double flip_s
Detailed Description
Definition at line 28 of file Selector.h.
Constructor & Destructor Documentation
Selector() [1/3]
Selector::Selector (const Beamline & bl, const RangeRep & range, const std::string & cName, const std::string & tName, const std::string & pString)
Constructor.
Definition at line 30 of file Selector.cpp.
References endl(), Element::find(), itsClass, itsPattern, and Options::warn.
~Selector()
Selector::~Selector () virtual
Definition at line 48 of file Selector.cpp.
References itsPattern.
Selector() [2/3]
Selector::Selector () private
Selector() [3/3]
Selector::Selector (const Selector &) private
Member Function Documentation
execute()
void Selector::execute () virtual
Execute the selection.
Reimplemented from RangeSelector.
Definition at line 53 of file Selector.cpp.
References RangeSelector::execute(), and itsCount.
Referenced by Select::select().
getCount()
int Selector::getCount () const
Return the count of selected elements.
Definition at line 86 of file Selector.cpp.
References itsCount.
Referenced by Select::select().
handleElement()
void Selector::handleElement (const FlaggedElmPtr & fep) protected virtual
The operation to be done for elements.
Reimplemented from RangeSelector.
Definition at line 59 of file Selector.cpp.
References Element::find(), ElmPtr::getElement(), ElementBase::getName(), OpalElement::getTypeName(), RangeRep::isActive(), Object::isTreeMember(), itsClass, itsCount, itsPattern, RangeSelector::itsRange, itsType, RegularExpression::match(), name, and FlaggedElmPtr::setSelectionFlag().
operator=()
void Selector::operator= (const Selector &) private
Member Data Documentation
itsClass
const Element* Selector::itsClass private
Definition at line 60 of file Selector.h.
Referenced by handleElement(), and Selector().
itsCount
int Selector::itsCount private
Definition at line 69 of file Selector.h.
Referenced by execute(), getCount(), and handleElement().
itsPattern
const RegularExpression* Selector::itsPattern private
Definition at line 66 of file Selector.h.
Referenced by handleElement(), Selector(), and ~Selector().
itsType
const std::string Selector::itsType private
Definition at line 63 of file Selector.h.
Referenced by handleElement().
The documentation for this class was generated from the following files:
src/Tables/Selector.h
src/Tables/Selector.cpp