OPAL (Object Oriented Parallel Accelerator Library): PlaceRep Class Reference
PlaceRep Class Reference
Representation of a place within a beam line or sequence.
#include <PlaceRep.h>
Public Member Functions
PlaceRep ()
Default constructor.
PlaceRep (const std::string &)
Construct default place.
PlaceRep (const PlaceRep &)
~PlaceRep ()
const PlaceRep & operator= (const PlaceRep &)
void append (const std::string &, int occur)
Add a name/occurrence pair.
void initialize ()
Initialise data for search.
void enter (const FlaggedElmPtr &) const
Enter an element or line.
void leave (const FlaggedElmPtr &) const
Leave an element or line.
bool isActive () const
Return status.
bool isSelected () const
Return select flag.
void print (std::ostream &os) const
Print in input format.
Private Types
typedef std::vector< std::pair< std::string, int > > Data
Private Attributes
Data data
bool is_selected
bool status
Data::size_type seen
Detailed Description
Representation of a place within a beam line or sequence.
Definition at line 41 of file PlaceRep.h.
Member Typedef Documentation
Data
typedef std::vector<std::pair<std::string, int> > PlaceRep::Data private
Definition at line 87 of file PlaceRep.h.
Constructor & Destructor Documentation
PlaceRep() [1/3]
PlaceRep::PlaceRep ()
Default constructor.
Definition at line 29 of file PlaceRep.cpp.
References initialize().
PlaceRep() [2/3]
PlaceRep::PlaceRep (const std::string & def) explicit
Construct default place.
Definition at line 41 of file PlaceRep.cpp.
References append(), and initialize().
PlaceRep() [3/3]
PlaceRep::PlaceRep (const PlaceRep & rhs)
Definition at line 35 of file PlaceRep.cpp.
References initialize().
~PlaceRep()
PlaceRep::~PlaceRep ()
Definition at line 48 of file PlaceRep.cpp.
Member Function Documentation
append()
void PlaceRep::append (const std::string & name, int occur)
Add a name/occurrence pair.
Definition at line 59 of file PlaceRep.cpp.
References data, and name.
Referenced by Expressions::parsePlace(), and PlaceRep().
enter()
void PlaceRep::enter (const FlaggedElmPtr & fep) const
Enter an element or line.
Definition at line 70 of file PlaceRep.cpp.
References data, FlaggedElmPtr::getCounter(), ElmPtr::getElement(), ElementBase::getName(), name, seen, and status.
Referenced by RangeRep::enter().
initialize()
void PlaceRep::initialize ()
Initialise data for search.
Definition at line 64 of file PlaceRep.cpp.
References seen, and status.
Referenced by RangeRep::initialize(), operator=(), and PlaceRep().
isActive()
bool PlaceRep::isActive () const
Return status.
Definition at line 98 of file PlaceRep.cpp.
References status.
Referenced by RangeRep::enter(), and RangeRep::leave().
isSelected()
bool PlaceRep::isSelected () const
Return select flag.
Definition at line 103 of file PlaceRep.cpp.
References is_selected.
leave()
void PlaceRep::leave (const FlaggedElmPtr & fep) const
Leave an element or line.
Definition at line 84 of file PlaceRep.cpp.
References data, FlaggedElmPtr::getCounter(), ElmPtr::getElement(), ElementBase::getName(), name, seen, and status.
Referenced by RangeRep::leave().
operator=()
const PlaceRep & PlaceRep::operator= (const PlaceRep & rhs)
Definition at line 52 of file PlaceRep.cpp.
References data, and initialize().
print()
void PlaceRep::print (std::ostream & os) const
Print in input format.
Definition at line 108 of file PlaceRep.cpp.
References data.
Referenced by operator<<(), and RangeRep::print().
Member Data Documentation
data
Data PlaceRep::data private
Definition at line 88 of file PlaceRep.h.
Referenced by append(), enter(), leave(), operator=(), and print().
is_selected
bool PlaceRep::is_selected private
Definition at line 91 of file PlaceRep.h.
Referenced by isSelected().
seen
Data::size_type PlaceRep::seen mutable private
Definition at line 97 of file PlaceRep.h.
Referenced by enter(), initialize(), and leave().
status
bool PlaceRep::status mutable private
Definition at line 94 of file PlaceRep.h.
Referenced by enter(), initialize(), isActive(), and leave().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/AbstractObjects/PlaceRep.h
/psi/home/gsell/data/src/OPAL/src/src/AbstractObjects/PlaceRep.cpp