OPAL (Object Oriented Parallel Accelerator Library): FLieGenerator< T, N > Class Template Reference
FLieGenerator< T, N > Class Template Reference
A representation for a homogeneous polynomial, used as a Lie generator.
#include <FLieGenerator.h>
Public Member Functions
FLieGenerator (int)
Construct a zero generator of given order.
FLieGenerator (const FTps< T, 2 *N > &, int)
Construct a zero generator of given order by extraction.
FLieGenerator ()
FLieGenerator (const FLieGenerator &)
~FLieGenerator ()
const FLieGenerator & operator= (const FLieGenerator &)
bool operator== (const FLieGenerator &) const
T * begin ()
Get pointer to beginning of generator.
T * end ()
Get pointer past end of generator.
const T * begin () const
Get pointer to beginning of generator.
const T * end () const
Get pointer past end of generator.
T & operator[] (int n)
Get element.
const T & operator[] (int n) const
Get element.
FLieGenerator operator- () const
Change sign of generator.
FLieGenerator & operator*= (const T &)
Multiply by scalar and assign.
FLieGenerator & operator/= (const T &)
Divide by scalar and assign.
FLieGenerator & operator+= (const FLieGenerator &)
Add vector and assign.
FLieGenerator & operator-= (const FLieGenerator &)
Subtract vector and assign.
void clear ()
Clear all coefficients.
FLieGenerator derivative (int var) const
Partial derivative.
bool isZero () const
Test for zero.
FLieGenerator scale (const FLieGenerator &) const
Scale monomial-wise.
template<class U >
FLieGenerator< U, N > transform (const FMatrix< U, 2 *N, 2 *N > &) const
Substitute matrix in Lie generator.
int getOrder () const
Return order of this generator.
int getBottomIndex () const
Return bottom index of this generator.
int getTopIndex () const
Return top index of this generator.
Static Private Member Functions
static int getSize (int order)
static int getBottomIndex (int order)
static int getTopIndex (int order)
Private Attributes
int itsOrder
int bottomIndex
int topIndex
Array1D< T > itsCoeffs
Detailed Description
template<class T, int N>
class FLieGenerator< T, N >
A representation for a homogeneous polynomial, used as a Lie generator.
Definition at line 40 of file FLieGenerator.h.
Constructor & Destructor Documentation
FLieGenerator() [1/4]
template<class T , int N> FLieGenerator< T, N >::FLieGenerator (int order) explicit
Construct a zero generator of given order.
Definition at line 38 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::itsCoeffs, and Attrib::Legacy::Distribution::T.
FLieGenerator() [2/4]
template<class T , int N> FLieGenerator< T, N >::FLieGenerator (const FTps< T, 2 *N > & tps, int order)
Construct a zero generator of given order by extraction.
Definition at line 49 of file FLieGenerator.hpp.
References FTps< T, N >::begin(), FLieGenerator< T, N >::bottomIndex, FTps< T, N >::getMaxOrder(), FLieGenerator< T, N >::itsCoeffs, Attrib::Legacy::Distribution::T, and FLieGenerator< T, N >::topIndex.
FLieGenerator() [3/4]
template<class T , int N> FLieGenerator< T, N >::FLieGenerator ()
Definition at line 64 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::itsCoeffs, and Attrib::Legacy::Distribution::T.
FLieGenerator() [4/4]
template<class T , int N> FLieGenerator< T, N >::FLieGenerator (const FLieGenerator< T, N > & rhs)
Definition at line 75 of file FLieGenerator.hpp.
~FLieGenerator()
template<class T , int N> FLieGenerator< T, N >::~FLieGenerator ()
Definition at line 85 of file FLieGenerator.hpp.
Member Function Documentation
begin() [1/2]
template<class T , int N> T * FLieGenerator< T, N >::begin () inline
Get pointer to beginning of generator.
Definition at line 102 of file FLieGenerator.hpp.
Referenced by toComplex().
begin() [2/2]
template<class T , int N> const T * FLieGenerator< T, N >::begin () const inline
Get pointer to beginning of generator.
Definition at line 109 of file FLieGenerator.hpp.
clear()
template<class T , int N> void FLieGenerator< T, N >::clear ()
Clear all coefficients.
Definition at line 209 of file FLieGenerator.hpp.
References Attrib::Legacy::Distribution::T.
derivative()
template<class T , int N> FLieGenerator< T, N > FLieGenerator< T, N >::derivative (int var) const
Partial derivative.
Definition at line 215 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::getBottomIndex(), FTpsData< N >::getProductArray(), and FLieGenerator< T, N >::getTopIndex().
end() [1/2]
template<class T , int N> T * FLieGenerator< T, N >::end () inline
Get pointer past end of generator.
Definition at line 115 of file FLieGenerator.hpp.
Referenced by imag(), real(), and toComplex().
end() [2/2]
template<class T , int N> const T * FLieGenerator< T, N >::end () const inline
Get pointer past end of generator.
Definition at line 122 of file FLieGenerator.hpp.
getBottomIndex() [1/2]
template<class T , int N> int FLieGenerator< T, N >::getBottomIndex () const inline
Return bottom index of this generator.
Definition at line 314 of file FLieGenerator.hpp.
Referenced by FLieGenerator< T, N >::derivative(), and operator*().
getBottomIndex() [2/2]
template<class T , int N> int FLieGenerator< T, N >::getBottomIndex (int order) inline static private
Definition at line 335 of file FLieGenerator.hpp.
References FTpsData< N >::getSize().
getOrder()
template<class T , int N> int FLieGenerator< T, N >::getOrder () const inline
Return order of this generator.
Definition at line 307 of file FLieGenerator.hpp.
Referenced by operator*(), operator<<(), and toComplex().
getSize()
template<class T , int N> int FLieGenerator< T, N >::getSize (int order) inline static private
Definition at line 328 of file FLieGenerator.hpp.
References FTpsData< N >::getSize().
getTopIndex() [1/2]
template<class T , int N> int FLieGenerator< T, N >::getTopIndex () const inline
Return top index of this generator.
Definition at line 321 of file FLieGenerator.hpp.
Referenced by FLieGenerator< T, N >::derivative(), and operator*().
getTopIndex() [2/2]
template<class T , int N> int FLieGenerator< T, N >::getTopIndex (int order) inline static private
Definition at line 342 of file FLieGenerator.hpp.
References FTpsData< N >::getSize().
isZero()
template<class T , int N> bool FLieGenerator< T, N >::isZero () const
Test for zero.
Definition at line 234 of file FLieGenerator.hpp.
References Attrib::Legacy::Distribution::T.
Referenced by operator*(), FLieGenerator< T, N >::operator+=(), and FLieGenerator< T, N >::operator-=().
operator*=()
template<class T , int N> FLieGenerator< T, N > & FLieGenerator< T, N >::operator*= (const T & val)
Multiply by scalar and assign.
Definition at line 152 of file FLieGenerator.hpp.
operator+=()
template<class T , int N> FLieGenerator< T, N > & FLieGenerator< T, N >::operator+= (const FLieGenerator< T, N > & rhs)
Add vector and assign.
Definition at line 177 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::isZero(), FLieGenerator< T, N >::itsCoeffs, and FLieGenerator< T, N >::itsOrder.
operator-()
template<class T , int N> FLieGenerator< T, N > FLieGenerator< T, N >::operator- () const
Change sign of generator.
Definition at line 140 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::itsCoeffs.
operator-=()
template<class T , int N> FLieGenerator< T, N > & FLieGenerator< T, N >::operator-= (const FLieGenerator< T, N > & rhs)
Subtract vector and assign.
Definition at line 193 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::isZero(), FLieGenerator< T, N >::itsCoeffs, and FLieGenerator< T, N >::itsOrder.
operator/=()
template<class T , int N> FLieGenerator< T, N > & FLieGenerator< T, N >::operator/= (const T & val)
Divide by scalar and assign.
Definition at line 164 of file FLieGenerator.hpp.
operator=()
template<class T , int N> const FLieGenerator< T, N > & FLieGenerator< T, N >::operator= (const FLieGenerator< T, N > & rhs)
Definition at line 91 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::bottomIndex, FLieGenerator< T, N >::itsCoeffs, FLieGenerator< T, N >::itsOrder, and FLieGenerator< T, N >::topIndex.
operator==()
template<class T, int N> bool FLieGenerator< T, N >::operator== (const FLieGenerator< T, N > &) const
operator[]() [1/2]
template<class T , int N> T & FLieGenerator< T, N >::operator[] (int n) inline
Get element.
Definition at line 128 of file FLieGenerator.hpp.
operator[]() [2/2]
template<class T , int N> const T & FLieGenerator< T, N >::operator[] (int n) const inline
Get element.
Definition at line 134 of file FLieGenerator.hpp.
scale()
template<class T , int N> FLieGenerator< T, N > FLieGenerator< T, N >::scale (const FLieGenerator< T, N > & rhs) const
Scale monomial-wise.
Definition at line 247 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::itsCoeffs.
transform()
template<class T , int N> template<class U > FLieGenerator< U, N > FLieGenerator< T, N >::transform (const FMatrix< U, 2 *N, 2 *N > & mat) const
Substitute matrix in Lie generator.
Definition at line 257 of file FLieGenerator.hpp.
References Array1D< T >::begin(), Physics::c, FTpsData< N >::getProductArray(), FTpsData< N >::getSubTable(), TpsSubstitution::index, TpsSubstitution::order, prod(), Array1D< T >::size(), TpsSubstitution::skip, Attrib::Legacy::Distribution::T, and TpsSubstitution::variable.
Member Data Documentation
bottomIndex
template<class T, int N> int FLieGenerator< T, N >::bottomIndex private
Definition at line 146 of file FLieGenerator.h.
Referenced by FLieGenerator< T, N >::FLieGenerator(), and FLieGenerator< T, N >::operator=().
itsCoeffs
template<class T, int N> Array1D<T> FLieGenerator< T, N >::itsCoeffs private
Definition at line 152 of file FLieGenerator.h.
Referenced by FLieGenerator< T, N >::FLieGenerator(), FLieGenerator< T, N >::operator+=(), FLieGenerator< T, N >::operator-(), FLieGenerator< T, N >::operator-=(), FLieGenerator< T, N >::operator=(), and FLieGenerator< T, N >::scale().
itsOrder
template<class T, int N> int FLieGenerator< T, N >::itsOrder private
Definition at line 143 of file FLieGenerator.h.
Referenced by FLieGenerator< T, N >::operator+=(), FLieGenerator< T, N >::operator-=(), and FLieGenerator< T, N >::operator=().
topIndex
template<class T, int N> int FLieGenerator< T, N >::topIndex private
Definition at line 149 of file FLieGenerator.h.
Referenced by FLieGenerator< T, N >::FLieGenerator(), and FLieGenerator< T, N >::operator=().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/FixedAlgebra/FLieGenerator.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/FixedAlgebra/FLieGenerator.hpp