OPAL (Object Oriented Parallel Accelerator Library): BVector Class Reference
BVector Class Reference
A magnetic field vector.
#include <EMField.h>
Public Member Functions
BVector (double, double, double)
Constructor.
BVector operator* (double scalar) const
Scale.
double getBx () const
Get component.
double getBy () const
Get component.
double getBz () const
Get component.
Private Attributes
double Bx
double By
double Bz
Detailed Description
A magnetic field vector.
Definition at line 97 of file EMField.h.
Constructor & Destructor Documentation
BVector()
BVector::BVector (double Bxx, double Byy, double Bzz)
Constructor.
Definition at line 70 of file EMField.cpp.
References Bx, By, and Bz.
Referenced by operator*().
Member Function Documentation
getBx()
double BVector::getBx () const
Get component.
Definition at line 78 of file EMField.cpp.
References Bx.
Referenced by EBVectors::getBx().
getBy()
double BVector::getBy () const
Get component.
Definition at line 82 of file EMField.cpp.
References By.
Referenced by EBVectors::getBy(), and EBVectors::getBz().
getBz()
double BVector::getBz () const
Get component.
Definition at line 86 of file EMField.cpp.
References Bz.
operator*()
BVector BVector::operator* (double scalar) const
Scale.
Definition at line 74 of file EMField.cpp.
References BVector(), Bx, By, and Bz.
Member Data Documentation
Bx
double BVector::Bx private
Definition at line 123 of file EMField.h.
Referenced by BVector(), getBx(), and operator*().
By
double BVector::By private
Definition at line 123 of file EMField.h.
Referenced by BVector(), getBy(), and operator*().
Bz
double BVector::Bz private
Definition at line 123 of file EMField.h.
Referenced by BVector(), getBz(), and operator*().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/EMField.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/EMField.cpp