OPAL (Object Oriented Parallel Accelerator Library): OptPilotException Class Reference
OptPilotException Class Reference
#include <OptPilotException.h>
Public Member Functions
OptPilotException (const std::string &meth, const std::string &descr)
virtual const char * what () const throw ()
virtual const char * where () const throw ()
Private Attributes
std::string descr_
std::string meth_
Detailed Description
Definition at line 26 of file OptPilotException.h.
Constructor & Destructor Documentation
OptPilotException()
OptPilotException::OptPilotException (const std::string & meth, const std::string & descr) inline
Definition at line 30 of file OptPilotException.h.
References descr_, and meth_.
Member Function Documentation
what()
virtual const char* OptPilotException::what () const throw () inline virtual
Definition at line 35 of file OptPilotException.h.
References descr_.
Referenced by SampleWorker< Sim_t >::onMessage(), Worker< Sim_t >::onMessage(), RadialPeak::operator()(), ProbeVariable::operator()(), SeptumExpr::operator()(), NumberOfPeaks::operator()(), SumErrSqRadialPeak::operator()(), MaxNormRadialPeak::operator()(), SumErrSq::operator()(), Worker< Sim_t >::runCoWorker(), and SampleWorker< Sim_t >::runSlave().
where()
virtual const char* OptPilotException::where () const throw () inline virtual
Definition at line 39 of file OptPilotException.h.
References meth_.
Member Data Documentation
descr_
std::string OptPilotException::descr_ private
Definition at line 45 of file OptPilotException.h.
Referenced by OptPilotException(), and what().
meth_
std::string OptPilotException::meth_ private
Definition at line 46 of file OptPilotException.h.
Referenced by OptPilotException(), and where().
The documentation for this class was generated from the following file:
optimizer/Util/OptPilotException.h