OPAL (Object Oriented Parallel Accelerator Library): Object Class Reference
Object Class Reference abstract
The base class for all OPAL objects.
#include <Object.h>
Public Member Functions
virtual ~Object ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual Object * clone (const std::string &name)=0
Return a clone.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual const std::string getCategory () const =0
Return the object category as a string.
virtual bool shouldTrace () const =0
Trace flag.
virtual bool shouldUpdate () const =0
Update flag.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Public Attributes
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Member Functions
Object ()
Object (const Object &object)
void operator= (const Object &)
Private Attributes
Object * itsParent
std::string itsName
std::string itsHelp
int occurrence
double timeStamp
std::set< Invalidator * > references
bool sharedFlag
Detailed Description
The base class for all OPAL objects.
Definition at line 48 of file Object.h.
Constructor & Destructor Documentation
~Object()
Object::~Object () virtual
Definition at line 39 of file Object.cpp.
References references.
Object() [1/4]
Object::Object (int size, const char * name, const char * help) protected
Constructor for exemplars.
Definition at line 356 of file Object.cpp.
References builtin, flagged, and modified.
Object() [2/4]
Object::Object (const std::string & name, Object * parent) protected
Constructor for clones.
Definition at line 368 of file Object.cpp.
References builtin, flagged, and modified.
Object() [3/4]
Object::Object () private
Object() [4/4]
Object::Object (const Object & object) private
Member Function Documentation
canReplaceBy()
bool Object::canReplaceBy (Object * object) virtual
Test if replacement is allowed.
Reimplemented in Distribution, Table, BoundaryGeometry, Element, OpalTrimCoil, ParticleMatterInteraction, Beam, OpalFilter, Action, RealConstant, RealVariable, OpalWake, BoolConstant, RealVector, and StringConstant.
Definition at line 48 of file Object.cpp.
Referenced by OpalData::define().
clear()
void Object::clear ()
Clear the occurrence counter.
Definition at line 341 of file Object.cpp.
References occurrence.
Referenced by FieldSolver::initSolver().
clone()
virtual Object* Object::clone (const std::string & name) pure virtual
Return a clone.
Implemented in Distribution, DumpEMFields, DumpFields, OpalMultipoleTCurvedConstRadius, OpalMultipoleTCurvedVarRadius, BoundaryGeometry, OpalCyclotron, OpalMultipoleTStraight, OpalOffset::OpalLocalCartesianOffset, OpalOffset::OpalGlobalCartesianOffset, OpalOffset::OpalLocalCylindricalOffset, FieldSolver, OpalCavity, OpalRingDefinition, OpalVariableRFCavityFringeField, OpalOffset::OpalGlobalCylindricalOffset, OpalOutputPlane, OpalScalingFFAMagnet, OpalPolynomialTimeDependence, OpalSplineTimeDependence, OpalSBend3D, OpalStripper, OpalVariableRFCavity, OpalTrimCoil, OpalMultipoleT, OpalTravelingWave, Sequence, OpalVacuum, Macro, OpalUndulator, OpalCCollimator, OpalRBend3D, OpalVerticalFFAMagnet, SequenceTemplate, TrackRun, OpalKicker, OpalPepperPot, ParticleMatterInteraction, OpalProbe, OpalQuadrupole, Line, LineTemplate, OpalDrift, OpalOctupole, OpalSeptum, Beam, OpalFlexibleCollimator, OpalMultipole, OpalSextupole, OpalSolenoid, OpalVKicker, OpalFilter, OpalECollimator, OpalHKicker, OpalRCollimator, OpalSlit, List, OpalDegrader, OpalSource, RealConstant, RealVariable, OpalSample, TrackEnd, OpalWake, Option, OpalMarker, SampleCmd, BoolConstant, RealVector, StringConstant, Select, OpalRBend, OpalSBend, Call, Echo, Help, PSystem, Quit, Stop, System, Title, Value, TrackCmd, OpalMonitor, OpalAsymmetricEnge, OpalEnge, OptimizeCmd, Constraint, DVar, and Objective.
Referenced by OpalParser::parseAction(), OpalParser::parseAssign(), OpalParser::parseDefine(), and SequenceParser::parseMember().
copyAttributes()
void Object::copyAttributes (const Object & source)
Copy attributes from another object.
Definition at line 54 of file Object.cpp.
References itsAttr.
Referenced by LineTemplate::makeInstance(), and SequenceTemplate::makeInstance().
execute()
void Object::execute () virtual
Execute the command.
Reimplemented in Distribution, DumpEMFields, DumpFields, FieldSolver, BoundaryGeometry, OpalTrimCoil, TrackRun, ParticleMatterInteraction, Beam, OpalFilter, List, MacroCmd, OpalSample, TrackEnd, OpalWake, Option, SampleCmd, Select, Call, Echo, Help, PSystem, Quit, Stop, System, Title, Value, TrackCmd, OptimizeCmd, Constraint, DVar, and Objective.
Definition at line 59 of file Object.cpp.
findAttribute() [1/2]
Attribute * Object::findAttribute (const std::string & name) virtual
Find an attribute by name.
Definition at line 64 of file Object.cpp.
References itsAttr, and name.
Referenced by SequenceParser::findNeighbourPositions(), OpalElement::getParticleMatterInteraction(), OpalElement::getTypeName(), OpalElement::getWakeF(), OpalElement::parse(), parse(), OpalParser::parseAssign(), SequenceParser::parsePosition(), and parseShortcut().
findAttribute() [2/2]
const Attribute * Object::findAttribute (const std::string & name) const virtual
Find an attribute by name.
Definition at line 74 of file Object.cpp.
References itsAttr, and name.
getBaseObject()
const Object * Object::getBaseObject () const
Return the object's base type object.
Definition at line 303 of file Object.cpp.
References itsParent.
getCategory()
virtual const std::string Object::getCategory () const pure virtual
Return the object category as a string.
Implemented in Table, Element, Macro, BeamSequence, Action, ValueDefinition, and Definition.
Referenced by OpalData::getVariableNames().
getOpalName()
const std::string & Object::getOpalName () const
Return object name.
Definition at line 310 of file Object.cpp.
References itsName.
Referenced by OpalVariableRFCavity::clone(), Macro::clone(), OpalVariableRFCavityFringeField::clone(), OpalOffset::OpalLocalCartesianOffset::clone(), OpalData::create(), OpalData::define(), ParallelCyclotronTracker::execute(), Sequence::findDriftLength(), SequenceParser::findNeighbourPositions(), ValueDefinition::getBool(), ValueDefinition::getBoolComponent(), ValueDefinition::getReal(), ValueDefinition::getRealComponent(), ValueDefinition::getString(), ValueDefinition::getStringComponent(), ParticleMatterInteraction::initParticleMatterInteractionHandler(), OpalWake::initWakefunction(), List::list(), LineTemplate::makeInstance(), makeInstance(), parse(), SequenceParser::parseMember(), SequenceParser::parsePosition(), parseShortcut(), StringConstant::print(), BoolConstant::print(), RealVector::print(), RealConstant::print(), RealVariable::print(), OpalWake::print(), OpalFilter::print(), ParticleMatterInteraction::print(), OpalTrimCoil::print(), Line::print(), Sequence::print(), Beam::print(), OpalElement::print(), print(), BoundaryGeometry::printInfo(), FieldSolver::printInfo(), OpalElement::registerOwnership(), registerOwnership(), Line::replace(), Sequence::replace(), OpalScalingFFAMagnet::setupDefaultEndField(), OpalEnge::update(), OpalAsymmetricEnge::update(), OpalSBend::update(), OpalRBend::update(), OpalRCollimator::update(), OpalSlit::update(), OpalECollimator::update(), OpalFlexibleCollimator::update(), OpalSeptum::update(), OpalProbe::update(), OpalWake::update(), OpalPepperPot::update(), OpalRBend3D::update(), OpalDrift::update(), OpalFilter::update(), OpalTravelingWave::update(), ParticleMatterInteraction::update(), OpalPolynomialTimeDependence::update(), OpalTrimCoil::update(), OpalOffset::OpalGlobalCylindricalOffset::update(), OpalCavity::update(), OpalOffset::OpalLocalCylindricalOffset::update(), OpalOffset::OpalGlobalCartesianOffset::update(), OpalOffset::OpalLocalCartesianOffset::update(), BoundaryGeometry::update(), Beam::update(), and Distribution::writeOutFileHeader().
getParent()
Object * Object::getParent () const
Return parent pointer.
Definition at line 315 of file Object.cpp.
References itsParent.
Referenced by OpalData::erase(), OpalElement::print(), print(), OpalElement::registerOwnership(), and registerOwnership().
increment()
int Object::increment ()
Increment and return the occurrence counter.
Definition at line 346 of file Object.cpp.
References occurrence.
Referenced by Sequence::storeLine().
isBuiltin()
bool Object::isBuiltin () const
True, if [b]this[/b] is a built-in object.
Definition at line 268 of file Object.cpp.
References builtin.
Referenced by OpalData::define(), and OpalData::getVariableNames().
isDirty()
bool Object::isDirty () const
True, if the [b]modified[/b] flag is set.
Definition at line 289 of file Object.cpp.
References modified.
isFlagged()
bool Object::isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
Definition at line 299 of file Object.cpp.
References flagged.
isShared()
bool Object::isShared () const virtual
Shared flag.
Definition at line 273 of file Object.cpp.
References sharedFlag.
Referenced by Sequence::print().
isTreeMember()
bool Object::isTreeMember (const Object * subTree) const
Test for tree membership.
Definition at line 320 of file Object.cpp.
References itsParent.
Referenced by Selector::handleElement(), and OpalParser::parseAssign().
makeInstance()
Object * Object::makeInstance (const std::string & name, Statement & , const Parser *) virtual
Macro handler function.
Reimplemented in SequenceTemplate, LineTemplate, and MacroCmd.
Definition at line 91 of file Object.cpp.
References getOpalName().
Referenced by OpalParser::parseDefine(), Line::parseList(), OpalParser::parseMacro(), and SequenceParser::parseMember().
makeTemplate()
Object * Object::makeTemplate (const std::string & name, TokenStream & , Statement &) virtual
Macro handler function.
Reimplemented in Sequence, Line, SequenceTemplate, LineTemplate, and MacroCmd.
Definition at line 85 of file Object.cpp.
References name.
Referenced by OpalParser::parseMacro().
occurrenceCount()
int Object::occurrenceCount ()
Return the occurrence counter.
Definition at line 351 of file Object.cpp.
References occurrence.
operator=()
void Object::operator= (const Object &) private
parse()
void Object::parse (Statement & stat) virtual
Parse the object.
Reimplemented in OpalElement, Sequence, Line, Call, Echo, Help, PSystem, System, Title, and Value.
Definition at line 97 of file Object.cpp.
References Statement::delimiter(), findAttribute(), getOpalName(), name, Expressions::parseDelimiter(), Expressions::parseRealConst(), and Expressions::parseString().
Referenced by Sequence::parse(), OpalParser::parseAction(), OpalParser::parseDefine(), and SequenceTemplate::parseTemplate().
parseShortcut()
void Object::parseShortcut (Statement & stat, bool eval = true) virtual
Parser for single-attribute commands.
Definition at line 129 of file Object.cpp.
References Statement::delimiter(), findAttribute(), getOpalName(), itsAttr, Statement::mark(), name, Statement::restore(), and Statement::word().
Referenced by Call::parse(), Value::parse(), Title::parse(), System::parse(), PSystem::parse(), Help::parse(), and Echo::parse().
print()
void Object::print (std::ostream & msg) const virtual
Print the object.
Reimplemented in DumpEMFields, DumpFields, OpalElement, Sequence, Beam, OpalMultipoleTCurvedConstRadius, OpalMultipoleTCurvedVarRadius, OpalOffset::OpalLocalCartesianOffset, OpalMultipoleTStraight, OpalOffset::OpalGlobalCartesianOffset, OpalOffset::OpalLocalCylindricalOffset, OpalOffset::OpalGlobalCylindricalOffset, OpalRingDefinition, Line, OpalBend, OpalPolynomialTimeDependence, OpalSplineTimeDependence, ParticleMatterInteraction, OpalMultipoleT, OpalFilter, OpalRBend3D, OpalWake, OpalQuadrupole, OpalOctupole, OpalMultipole, OpalSextupole, RealConstant, RealVariable, OpalMarker, BoolConstant, RealVector, and StringConstant.
Definition at line 161 of file Object.cpp.
References endl(), getOpalName(), getParent(), and itsAttr.
Referenced by printValue().
printHelp()
void Object::printHelp (std::ostream &) const virtual
Print help.
Definition at line 201 of file Object.cpp.
References endl(), gmsg, itsAttr, itsHelp, max(), and name.
Referenced by Help::execute().
printValue()
void Object::printValue (std::ostream & os) const inline virtual
Reimplemented in RealConstant, RealVariable, BoolConstant, RealVector, and StringConstant.
Definition at line 280 of file Object.h.
References print().
registerOwnership()
void Object::registerOwnership (const AttributeHandler::OwnerType & itsClass) const
Definition at line 191 of file Object.cpp.
References AttributeHandler::addAttributeOwner(), end(), getOpalName(), getParent(), itsAttr, and name.
Referenced by Beam::Beam(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), Call::Call(), Constraint::Constraint(), DumpEMFields::DumpEMFields(), DumpFields::DumpFields(), DVar::DVar(), Echo::Echo(), FieldSolver::FieldSolver(), Help::Help(), Line::Line(), List::List(), Objective::Objective(), OpalFilter::OpalFilter(), OpalSample::OpalSample(), OpalTrimCoil::OpalTrimCoil(), OpalWake::OpalWake(), OptimizeCmd::OptimizeCmd(), Option::Option(), ParticleMatterInteraction::ParticleMatterInteraction(), PSystem::PSystem(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVector::RealVector(), SampleCmd::SampleCmd(), Select::Select(), Sequence::Sequence(), Distribution::setAttributes(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), and Value::Value().
registerReference()
void Object::registerReference (Invalidator * a)
Register a reference to this object.
Definition at line 182 of file Object.cpp.
References Hypervolume::ref, and references.
replace()
void Object::replace (Object * oldObject, Object * newObject) virtual
Replace references.
Reimplemented in Sequence, and Line.
Definition at line 258 of file Object.cpp.
setDirty()
void Object::setDirty (bool dirty)
Set/reset the [b]modified[/b] flag.
Definition at line 283 of file Object.cpp.
References modified.
Referenced by OpalData::define(), OpalData::makeDirty(), and RealVariable::RealVariable().
setFlag()
void Object::setFlag (bool flag)
Flag/unflag this object, e. g. to control output of objects for.
Definition at line 294 of file Object.cpp.
References flagged.
setOpalName()
void Object::setOpalName (const std::string & name)
Set object name.
Definition at line 331 of file Object.cpp.
References itsName, and name.
Referenced by OpalWake::update(), OpalFilter::update(), ParticleMatterInteraction::update(), OpalTrimCoil::update(), BoundaryGeometry::update(), and Beam::update().
setParent()
void Object::setParent (Object * parent)
Set parent object.
Definition at line 336 of file Object.cpp.
References itsParent.
Referenced by OpalData::erase().
setShared()
void Object::setShared (bool flag) virtual
Set/reset shared flag.
Reimplemented in Element.
Definition at line 278 of file Object.cpp.
References sharedFlag.
Referenced by OpalParser::parseDefine(), and Element::setShared().
shouldTrace()
virtual bool Object::shouldTrace () const pure virtual
Trace flag.
Implemented in Table, Element, Macro, Action, ValueDefinition, and Definition.
Referenced by OpalParser::execute().
shouldUpdate()
virtual bool Object::shouldUpdate () const pure virtual
Update flag.
Implemented in Table, Element, Macro, Action, ValueDefinition, and Definition.
Referenced by OpalParser::execute().
unregisterReference()
void Object::unregisterReference (Invalidator * a)
Unegister a reference to this object.
Definition at line 187 of file Object.cpp.
References Hypervolume::ref, and references.
update()
void Object::update () virtual
Update this object.
Reimplemented in Distribution, OpalElement, Sequence, FieldSolver, Beam, BoundaryGeometry, OpalMultipoleTCurvedConstRadius, OpalMultipoleTCurvedVarRadius, OpalOffset::OpalLocalCartesianOffset, OpalCyclotron, OpalMultipoleTStraight, OpalOffset::OpalGlobalCartesianOffset, OpalOffset::OpalLocalCylindricalOffset, OpalVariableRFCavityFringeField, OpalCavity, OpalOutputPlane, OpalOffset::OpalGlobalCylindricalOffset, OpalRingDefinition, OpalTrimCoil, OpalPolynomialTimeDependence, OpalSplineTimeDependence, OpalScalingFFAMagnet, OpalVariableRFCavity, OpalKicker, OpalSBend3D, OpalStripper, ParticleMatterInteraction, OpalMultipoleT, OpalTravelingWave, OpalVKicker, OpalVacuum, OpalQuadrupole, OpalFilter, OpalDrift, OpalOctupole, OpalUndulator, OpalCCollimator, OpalMultipole, OpalRBend3D, OpalSextupole, OpalVerticalFFAMagnet, OpalPepperPot, OpalProbe, OpalWake, OpalSeptum, OpalFlexibleCollimator, OpalSolenoid, OpalECollimator, OpalHKicker, OpalMarker, OpalRCollimator, OpalSlit, OpalDegrader, OpalSource, OpalRBend, OpalSBend, OpalMonitor, OpalAsymmetricEnge, and OpalEnge.
Definition at line 263 of file Object.cpp.
Referenced by PyOpal::PyDistributionNS::registerDistribution().
Member Data Documentation
builtin
bool Object::builtin protected
Built-in flag.
Definition at line 233 of file Object.h.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), Distribution::Distribution(), isBuiltin(), Object(), OpalFilter::OpalFilter(), OpalMarker::OpalMarker(), OpalTrimCoil::OpalTrimCoil(), OpalWake::OpalWake(), ParticleMatterInteraction::ParticleMatterInteraction(), RealConstant::RealConstant(), StringConstant::StringConstant(), and Table::~Table().
flagged
bool Object::flagged protected
Object flag.
Definition at line 242 of file Object.h.
Referenced by isFlagged(), Object(), and setFlag().
itsAttr
std::vector<Attribute> Object::itsAttr
The object attributes.
Definition at line 216 of file Object.h.
Referenced by Distribution::adjustPhaseSpace(), Beam::Beam(), BoolConstant::BoolConstant(), BoundaryGeometry::BoundaryGeometry(), DumpFields::buildGrid(), DumpEMFields::buildGrid(), Distribution::calcPartPerDist(), Call::Call(), Distribution::checkEmissionParameters(), Distribution::checkIfEmitted(), Distribution::chooseInputMomentumUnits(), Constraint::Constraint(), copyAttributes(), Distribution::create(), Distribution::createDistributionFromFile(), Distribution::createDistributionMultiGauss(), Distribution::createMatchedGaussDistribution(), Distribution::createOpalT(), DumpEMFields::DumpEMFields(), DumpFields::DumpFields(), DVar::DVar(), Echo::Echo(), OptimizeCmd::execute(), TrackCmd::execute(), Call::execute(), Title::execute(), Value::execute(), Echo::execute(), Help::execute(), PSystem::execute(), System::execute(), Select::execute(), Option::execute(), SampleCmd::execute(), List::execute(), Beam::execute(), TrackRun::execute(), FieldSolver::FieldSolver(), findAttribute(), Distribution::generateAstraFlattopT(), Distribution::generateBinomial(), Distribution::generateFlattopLaserProfile(), Distribution::generateFlattopT(), Distribution::generateFlattopZ(), Distribution::generateGaussZ(), Distribution::generateLongFlattopT(), Distribution::generateMatchedGauss(), Distribution::generateTransverseGauss(), BoundaryGeometry::getA(), OpalElement::getApert(), BoundaryGeometry::getB(), BoolConstant::getBool(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), TrackCmd::getDT(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), Distribution::getEmissionTimeShift(), Constraint::getExpression(), Objective::getExpression(), BoundaryGeometry::getFilename(), Beam::getFrequency(), ParticleMatterInteraction::getInteractionType(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), Line::getLength(), Sequence::getLength(), OpalElement::getLength(), BoundaryGeometry::getLength(), DVar::getLowerBound(), Beam::getMass(), TrackCmd::getMaxSteps(), FieldSolver::getMT(), FieldSolver::getMX(), FieldSolver::getMY(), OpalWake::getNumberOfBins(), Beam::getNumberOfParticles(), Distribution::getNumberOfParticlesInFile(), Beam::getParticleName(), RealConstant::getReal(), RealVariable::getReal(), RealVector::getRealComponent(), Sequence::getReference(), BoundaryGeometry::getS(), TrackCmd::getStepsPerTurn(), StringConstant::getString(), TrackCmd::getT0(), FieldSolver::getTagging_m(), Distribution::getTEmission(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), OpalTrimCoil::getTrimCoilType(), FieldSolver::getType(), DVar::getUpperBound(), DVar::getVariable(), OpalSample::getVariable(), Distribution::getWeight(), TrackCmd::getZStart(), TrackCmd::getZStop(), FieldSolver::hasPeriodicZ(), Help::Help(), FieldSolver::initAmrObject_m(), FieldSolver::initAmrSolver_m(), FieldSolver::initCartesianFields(), OpalSample::initialize(), OpalFilter::initOpalFilter(), OpalTrimCoil::initOpalTrimCoil(), ParticleMatterInteraction::initParticleMatterInteractionHandler(), FieldSolver::initSolver(), OpalWake::initWakefunction(), Distribution::injectBeam(), Line::Line(), List::List(), List::list(), Objective::Objective(), OpalAsymmetricEnge::OpalAsymmetricEnge(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalCCollimator::OpalCCollimator(), OpalCyclotron::OpalCyclotron(), OpalDegrader::OpalDegrader(), OpalDrift::OpalDrift(), OpalECollimator::OpalECollimator(), OpalElement::OpalElement(), OpalEnge::OpalEnge(), OpalFilter::OpalFilter(), OpalFlexibleCollimator::OpalFlexibleCollimator(), OpalOffset::OpalGlobalCartesianOffset::OpalGlobalCartesianOffset(), OpalOffset::OpalGlobalCylindricalOffset::OpalGlobalCylindricalOffset(), OpalHKicker::OpalHKicker(), OpalKicker::OpalKicker(), OpalOffset::OpalLocalCartesianOffset::OpalLocalCartesianOffset(), OpalOffset::OpalLocalCylindricalOffset::OpalLocalCylindricalOffset(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalMultipoleTCurvedConstRadius::OpalMultipoleTCurvedConstRadius(), OpalMultipoleTCurvedVarRadius::OpalMultipoleTCurvedVarRadius(), OpalMultipoleTStraight::OpalMultipoleTStraight(), OpalOctupole::OpalOctupole(), OpalOutputPlane::OpalOutputPlane(), OpalPepperPot::OpalPepperPot(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRBend3D::OpalRBend3D(), OpalRCollimator::OpalRCollimator(), OpalRingDefinition::OpalRingDefinition(), OpalSample::OpalSample(), OpalSBend3D::OpalSBend3D(), OpalScalingFFAMagnet::OpalScalingFFAMagnet(), OpalSeptum::OpalSeptum(), OpalSextupole::OpalSextupole(), OpalSlit::OpalSlit(), OpalSolenoid::OpalSolenoid(), OpalSource::OpalSource(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalStripper::OpalStripper(), OpalTravelingWave::OpalTravelingWave(), OpalTrimCoil::OpalTrimCoil(), OpalUndulator::OpalUndulator(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVariableRFCavityFringeField::OpalVariableRFCavityFringeField(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), OpalVKicker::OpalVKicker(), OpalWake::OpalWake(), OptimizeCmd::OptimizeCmd(), Option::Option(), Sequence::parse(), DumpEMFields::parseCoordinateSystem(), parseShortcut(), ParticleMatterInteraction::ParticleMatterInteraction(), StringConstant::print(), BoolConstant::print(), RealVector::print(), RealVariable::print(), RealConstant::print(), OpalWake::print(), TrackRun::print(), OpalFilter::print(), ParticleMatterInteraction::print(), OpalTrimCoil::print(), Sequence::print(), Beam::print(), DumpFields::print(), print(), DumpEMFields::print(), Distribution::printDistFlattop(), Distribution::printDistFromFile(), Distribution::printDistGauss(), Distribution::printEmissionModelAstra(), Distribution::printEmissionModelNone(), printHelp(), BoundaryGeometry::printInfo(), FieldSolver::printInfo(), Distribution::printInfo(), StringConstant::printValue(), BoolConstant::printValue(), RealVector::printValue(), RealConstant::printValue(), RealVariable::printValue(), PSystem::PSystem(), RealConstant::RealConstant(), RealVariable::RealVariable(), RealVector::RealVector(), OpalElement::registerOwnership(), registerOwnership(), OptimizeCmd::run(), SampleCmd::SampleCmd(), Distribution::scaleDistCoordinates(), Select::Select(), Select::select(), Sequence::Sequence(), Distribution::setAttributes(), TrackRun::setBoundaryGeometry(), Distribution::setDistParametersBinomial(), Distribution::setDistParametersFlattop(), Distribution::setDistParametersGauss(), Distribution::setDistParametersMultiGauss(), TrackRun::setDistributionParallelT(), Distribution::setDistType(), FieldSolver::setMT(), FieldSolver::setMX(), FieldSolver::setMY(), TrackRun::setRunMethod(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), TrackRun::setupCyclotronTracker(), OpalScalingFFAMagnet::setupDefaultEndField(), Distribution::setupEmissionModel(), Distribution::setupEmissionModelAstra(), Distribution::setupEmissionModelNone(), Distribution::setupEmissionModelNonEquil(), TrackRun::setupFieldsolver(), OpalScalingFFAMagnet::setupNamedEndField(), Distribution::setupParticleBins(), TrackRun::setupThickTracker(), TrackRun::setupTTracker(), Distribution::shiftDistCoordinates(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), TrackRun::TrackRun(), OpalEnge::update(), OpalAsymmetricEnge::update(), OpalMonitor::update(), OpalSBend::update(), OpalRBend::update(), OpalSource::update(), OpalDegrader::update(), OpalECollimator::update(), OpalHKicker::update(), OpalSlit::update(), OpalRCollimator::update(), OpalFlexibleCollimator::update(), OpalSolenoid::update(), OpalSeptum::update(), OpalProbe::update(), OpalPepperPot::update(), Option::update(), OpalSextupole::update(), OpalMultipole::update(), OpalVerticalFFAMagnet::update(), OpalCCollimator::update(), OpalRBend3D::update(), OpalOctupole::update(), OpalDrift::update(), OpalUndulator::update(), OpalQuadrupole::update(), OpalVacuum::update(), OpalVKicker::update(), OpalTravelingWave::update(), OpalMultipoleT::update(), OpalKicker::update(), OpalStripper::update(), OpalSBend3D::update(), OpalVariableRFCavity::update(), OpalScalingFFAMagnet::update(), OpalSplineTimeDependence::update(), OpalPolynomialTimeDependence::update(), OpalRingDefinition::update(), OpalOffset::OpalGlobalCylindricalOffset::update(), OpalCavity::update(), OpalOutputPlane::update(), OpalVariableRFCavityFringeField::update(), OpalOffset::OpalLocalCylindricalOffset::update(), OpalOffset::OpalGlobalCartesianOffset::update(), OpalMultipoleTStraight::update(), OpalCyclotron::update(), OpalOffset::OpalLocalCartesianOffset::update(), OpalMultipoleTCurvedVarRadius::update(), OpalMultipoleTCurvedConstRadius::update(), Beam::update(), OpalElement::update(), OpalElement::updateUnknown(), Value::Value(), ValueDefinition::value(), Distribution::writeOutFileEmission(), Distribution::writeOutFileHeader(), and Distribution::writeOutFileInjection().
itsHelp
std::string Object::itsHelp private
Definition at line 258 of file Object.h.
Referenced by printHelp().
itsName
std::string Object::itsName private
Definition at line 255 of file Object.h.
Referenced by getOpalName(), and setOpalName().
itsParent
Object* Object::itsParent private
Definition at line 252 of file Object.h.
Referenced by getBaseObject(), getParent(), isTreeMember(), and setParent().
modified
bool Object::modified protected
Dirty flag.
Definition at line 238 of file Object.h.
Referenced by isDirty(), Object(), and setDirty().
occurrence
int Object::occurrence private
Definition at line 261 of file Object.h.
Referenced by clear(), increment(), and occurrenceCount().
references
std::set<Invalidator *> Object::references private
Definition at line 268 of file Object.h.
Referenced by registerReference(), unregisterReference(), and ~Object().
sharedFlag
bool Object::sharedFlag private
Definition at line 271 of file Object.h.
Referenced by isShared(), and setShared().
timeStamp
double Object::timeStamp private
Definition at line 264 of file Object.h.
The documentation for this class was generated from the following files:
src/AbstractObjects/Object.h
src/AbstractObjects/Object.cpp