OPAL (Object Oriented Parallel Accelerator Library): AmrMultiGrid Class Reference
AmrMultiGrid Class Reference
#include <AmrMultiGrid.h>
Public Types
enum Interpolater { TRILINEAR = 0, LAGRANGE, PIECEWISE_CONST }
Supported interpolaters for prolongation operation.
enum BaseSolver {
BICGSTAB, MINRES, PCPG, CG,
GMRES, STOCHASTIC_CG, RECYCLING_CG, RECYCLING_GMRES,
SA
}
Supported bottom solvers.
enum Boundary { DIRICHLET = 0, OPEN, PERIODIC }
Supported physical boundaries.
enum Norm { L1, L2, LINF }
Supported convergence criteria.
typedef amr::matrix_t matrix_t
typedef amr::vector_t vector_t
typedef amr::multivector_t mv_t
typedef amr::dmap_t dmap_t
typedef amr::comm_t comm_t
typedef amr::local_ordinal_t lo_t
typedef amr::global_ordinal_t go_t
typedef amr::scalar_t scalar_t
typedef AmrMultiGridLevel< matrix_t, vector_t > AmrMultiGridLevel_t
typedef AmrMultiGridLevel_t::AmrField_t AmrField_t
typedef AmrMultiGridLevel_t::AmrGeometry_t AmrGeometry_t
typedef AmrMultiGridLevel_t::AmrField_u AmrField_u
typedef AmrMultiGridLevel_t::AmrField_s AmrField_s
typedef AmrMultiGridLevel_t::AmrIntVect_t AmrIntVect_t
typedef AmrMultiGridLevel_t::indices_t indices_t
typedef AmrMultiGridLevel_t::coefficients_t coefficients_t
typedef AmrMultiGridLevel_t::umap_t umap_t
typedef AmrMultiGridLevel_t::boundary_t boundary_t
typedef BottomSolver< Teuchos::RCP< matrix_t >, Teuchos::RCP< mv_t >, AmrMultiGridLevel_t > bsolver_t
typedef BelosBottomSolver< AmrMultiGridLevel_t > BelosSolver_t
typedef Amesos2BottomSolver< AmrMultiGridLevel_t > Amesos2Solver_t
typedef MueLuBottomSolver< AmrMultiGridLevel_t > MueLuSolver_t
typedef AmrPreconditioner< matrix_t, AmrMultiGridLevel_t > preconditioner_t
typedef Ifpack2Preconditioner< AmrMultiGridLevel_t > Ifpack2Preconditioner_t
typedef MueLuPreconditioner< AmrMultiGridLevel_t > MueLuPreconditioner_t
typedef amrex::BoxArray boxarray_t
typedef amrex::Box box_t
typedef amrex::BaseFab< int > basefab_t
typedef amrex::FArrayBox farraybox_t
typedef AmrSmoother::Smoother Smoother
typedef amr::Preconditioner Preconditioner
Public Member Functions
AmrMultiGrid (AmrBoxLib *itsAmrObject_p, const std::string &bsolver, const std::string &prec, const bool &rebalance, const std::string &reuse, const std::string &bcx, const std::string &bcy, const std::string &bcz, const std::string &smoother, const std::size_t &nSweeps, const std::string &interp, const std::string &norm)
void solve (AmrScalarFieldContainer_t &rho, AmrScalarFieldContainer_t &phi, AmrVectorFieldContainer_t &efield, unsigned short baseLevel, unsigned short finestLevel, bool prevAsGuess=true)
void setNumberOfSweeps (const std::size_t &nSweeps)
void setMaxNumberOfIterations (const std::size_t &maxiter)
std::size_t getNumIters ()
scalar_t getLevelResidualNorm (lo_t level)
void setVerbose (bool verbose)
void setTolerance (const scalar_t &eps)
double getXRangeMin (unsigned short level=0)
double getXRangeMax (unsigned short level=0)
double getYRangeMin (unsigned short level=0)
double getYRangeMax (unsigned short level=0)
double getZRangeMin (unsigned short level=0)
double getZRangeMax (unsigned short level=0)
Inform & print (Inform &os) const
Public Member Functions inherited from AmrPoissonSolver< AmrBoxLib >
AmrPoissonSolver (AmrBoxLib *itsAmrObject_p)
virtual ~AmrPoissonSolver ()
void computePotential (Field_t &, Vector_t)
void computePotential (Field_t &, Vector_t, double)
void test (PartBunchBase< double, 3 > *)
void hasToRegrid ()
Public Member Functions inherited from PoissonSolver
virtual ~PoissonSolver ()
virtual void resizeMesh (Vector_t &, Vector_t &, const Vector_t &, const Vector_t &, double)
Private Member Functions
void initPhysicalBoundary_m (const Boundary *bc)
void initLevels_m (const amrex::Vector< AmrField_u > &rho, const amrex::Vector< AmrGeometry_t > &geom, bool regrid)
void clearMasks_m ()
void initGuess_m (bool reset)
scalar_t iterate_m ()
bool isConverged_m (std::vector< scalar_t > &rhsNorms, std::vector< scalar_t > &resNorms)
void residual_m (const lo_t &level, Teuchos::RCP< vector_t > &r, const Teuchos::RCP< vector_t > &b, const Teuchos::RCP< vector_t > &x)
void relax_m (const lo_t &level)
void residual_no_fine_m (const lo_t &level, Teuchos::RCP< vector_t > &result, const Teuchos::RCP< vector_t > &rhs, const Teuchos::RCP< vector_t > &crs_rhs, const Teuchos::RCP< vector_t > &b)
scalar_t evalNorm_m (const Teuchos::RCP< const vector_t > &x)
void initResidual_m (std::vector< scalar_t > &rhsNorms, std::vector< scalar_t > &resNorms)
void computeEfield_m (AmrVectorFieldContainer_t &efield)
void setup_m (const amrex::Vector< AmrField_u > &rho, const amrex::Vector< AmrField_u > &phi, const bool &matrices=true)
void buildSingleLevel_m (const amrex::Vector< AmrField_u > &rho, const amrex::Vector< AmrField_u > &phi, const bool &matrices=true)
void buildMultiLevel_m (const amrex::Vector< AmrField_u > &rho, const amrex::Vector< AmrField_u > &phi, const bool &matrices=true)
void open_m (const lo_t &level, const bool &matrices)
void close_m (const lo_t &level, const bool &matrices)
void buildNoFinePoissonMatrix_m (const lo_t &level, const go_t &gidx, const AmrIntVect_t &iv, const basefab_t &mfab, const scalar_t *invdx2)
void buildCompositePoissonMatrix_m (const lo_t &level, const go_t &gidx, const AmrIntVect_t &iv, const basefab_t &mfab, const basefab_t &rfab, const scalar_t *invdx2)
void buildRestrictionMatrix_m (const lo_t &level, const go_t &gidx, const AmrIntVect_t &iv, D_DECL(const go_t &ii, const go_t &jj, const go_t &kk), const basefab_t &rfab)
void buildInterpolationMatrix_m (const lo_t &level, const go_t &gidx, const AmrIntVect_t &iv, const basefab_t &cfab)
void buildCrseBoundaryMatrix_m (const lo_t &level, const go_t &gidx, const AmrIntVect_t &iv, const basefab_t &mfab, const basefab_t &cfab, const scalar_t *invdx2)
void buildFineBoundaryMatrix_m (const lo_t &level, const go_t &gidx, const AmrIntVect_t &iv, const basefab_t &mfab, const basefab_t &rfab)
void buildDensityVector_m (const lo_t &level, const AmrField_t &rho)
void buildPotentialVector_m (const lo_t &level, const AmrField_t &phi)
void buildGradientMatrix_m (const lo_t &level, const go_t &gidx, const AmrIntVect_t &iv, const basefab_t &mfab, const scalar_t *invdx)
void amrex2trilinos_m (const lo_t &level, const lo_t &comp, const AmrField_t &mf, Teuchos::RCP< vector_t > &mv)
void trilinos2amrex_m (const lo_t &level, const lo_t &comp, AmrField_t &mf, const Teuchos::RCP< vector_t > &mv)
void map2vector_m (umap_t &map, indices_t &indices, coefficients_t &values)
void smooth_m (const lo_t &level, Teuchos::RCP< vector_t > &e, Teuchos::RCP< vector_t > &r)
void restrict_m (const lo_t &level)
void prolongate_m (const lo_t &level)
void averageDown_m (const lo_t &level)
void initInterpolater_m (const Interpolater &interp)
void initCrseFineInterp_m (const Interpolater &interface)
void initBaseSolver_m (const BaseSolver &solver, const bool &rebalance, const std::string &reuse)
void initPrec_m (const Preconditioner &prec, const std::string &reuse)
Boundary convertToEnumBoundary_m (const std::string &bc)
Interpolater convertToEnumInterpolater_m (const std::string &interp)
BaseSolver convertToEnumBaseSolver_m (const std::string &bsolver)
Preconditioner convertToEnumPreconditioner_m (const std::string &prec)
Smoother convertToEnumSmoother_m (const std::string &smoother)
Norm convertToEnumNorm_m (const std::string &norm)
void writeSDDSHeader_m (std::ofstream &outfile)
void writeSDDSData_m (const scalar_t &error)
Private Attributes
Teuchos::RCP< comm_t > comm_mp
communicator
std::unique_ptr< AmrInterpolater< AmrMultiGridLevel_t > > interp_mp
interpolater without coarse-fine interface
std::unique_ptr< AmrInterpolater< AmrMultiGridLevel_t > > interface_mp
interpolater for coarse-fine interface
std::size_t nIter_m
number of iterations till convergence
std::size_t bIter_m
number of iterations of bottom solver
std::size_t maxiter_m
maximum number of iterations allowed
std::size_t nSweeps_m
number of smoothing iterations
Smoother smootherType_m
type of smoother
std::vector< std::unique_ptr< AmrMultiGridLevel_t > > mglevel_m
container for levels
std::shared_ptr< bsolver_t > solver_mp
bottom solver
std::vector< std::shared_ptr< AmrSmoother > > smoother_m
error smoother
std::shared_ptr< preconditioner_t > prec_mp
preconditioner for bottom solver
int lbase_m
base level (currently only 0 supported)
int lfine_m
fineste level
int nlevel_m
number of levelss
boundary_t bc_m [AMREX_SPACEDIM]
boundary conditions
int nBcPoints_m
maximum number of stencils points for BC
Norm norm_m
norm for convergence criteria (l1, l2, linf)
std::string snorm_m
norm for convergence criteria
scalar_t eps_m
rhs scale for convergence
bool verbose_m
If true, a SDDS file is written.
std::string fname_m
SDDS filename.
std::ios_base::openmode flag_m
std::ios::out or std::ios::app
Additional Inherited Members
Protected Types inherited from PoissonSolver
typedef Field< int, 3, Mesh_t, Center_t > IField_t
typedef Field< std::complex< double >, 3, Mesh_t, Center_t > CxField_t
Protected Attributes inherited from AmrPoissonSolver< AmrBoxLib >
AmrBoxLib * itsAmrObject_mp
bool regrid_m
is set to true by itsAmrObject_mp and reset to false by solver
Detailed Description
Definition at line 44 of file AmrMultiGrid.h.
Member Typedef Documentation
Amesos2Solver_t
typedef Amesos2BottomSolver<AmrMultiGridLevel_t> AmrMultiGrid::Amesos2Solver_t
Definition at line 75 of file AmrMultiGrid.h.
AmrField_s
typedef AmrMultiGridLevel_t::AmrField_s AmrMultiGrid::AmrField_s
Definition at line 61 of file AmrMultiGrid.h.
AmrField_t
typedef AmrMultiGridLevel_t::AmrField_t AmrMultiGrid::AmrField_t
Definition at line 58 of file AmrMultiGrid.h.
AmrField_u
typedef AmrMultiGridLevel_t::AmrField_u AmrMultiGrid::AmrField_u
Definition at line 60 of file AmrMultiGrid.h.
AmrGeometry_t
typedef AmrMultiGridLevel_t::AmrGeometry_t AmrMultiGrid::AmrGeometry_t
Definition at line 59 of file AmrMultiGrid.h.
AmrIntVect_t
typedef AmrMultiGridLevel_t::AmrIntVect_t AmrMultiGrid::AmrIntVect_t
Definition at line 62 of file AmrMultiGrid.h.
AmrMultiGridLevel_t
typedef AmrMultiGridLevel<matrix_t, vector_t> AmrMultiGrid::AmrMultiGridLevel_t
Definition at line 56 of file AmrMultiGrid.h.
basefab_t
typedef amrex::BaseFab<int> AmrMultiGrid::basefab_t
Definition at line 85 of file AmrMultiGrid.h.
BelosSolver_t
typedef BelosBottomSolver<AmrMultiGridLevel_t> AmrMultiGrid::BelosSolver_t
Definition at line 74 of file AmrMultiGrid.h.
boundary_t
typedef AmrMultiGridLevel_t::boundary_t AmrMultiGrid::boundary_t
Definition at line 66 of file AmrMultiGrid.h.
box_t
typedef amrex::Box AmrMultiGrid::box_t
Definition at line 84 of file AmrMultiGrid.h.
boxarray_t
typedef amrex::BoxArray AmrMultiGrid::boxarray_t
Definition at line 83 of file AmrMultiGrid.h.
bsolver_t
typedef BottomSolver< Teuchos::RCP<matrix_t>, Teuchos::RCP<mv_t>, AmrMultiGridLevel_t > AmrMultiGrid::bsolver_t
Definition at line 72 of file AmrMultiGrid.h.
coefficients_t
typedef AmrMultiGridLevel_t::coefficients_t AmrMultiGrid::coefficients_t
Definition at line 64 of file AmrMultiGrid.h.
comm_t
typedef amr::comm_t AmrMultiGrid::comm_t
Definition at line 51 of file AmrMultiGrid.h.
dmap_t
typedef amr::dmap_t AmrMultiGrid::dmap_t
Definition at line 50 of file AmrMultiGrid.h.
farraybox_t
typedef amrex::FArrayBox AmrMultiGrid::farraybox_t
Definition at line 86 of file AmrMultiGrid.h.
go_t
typedef amr::global_ordinal_t AmrMultiGrid::go_t
Definition at line 53 of file AmrMultiGrid.h.
Ifpack2Preconditioner_t
typedef Ifpack2Preconditioner<AmrMultiGridLevel_t> AmrMultiGrid::Ifpack2Preconditioner_t
Definition at line 80 of file AmrMultiGrid.h.
indices_t
typedef AmrMultiGridLevel_t::indices_t AmrMultiGrid::indices_t
Definition at line 63 of file AmrMultiGrid.h.
lo_t
typedef amr::local_ordinal_t AmrMultiGrid::lo_t
Definition at line 52 of file AmrMultiGrid.h.
matrix_t
typedef amr::matrix_t AmrMultiGrid::matrix_t
Definition at line 47 of file AmrMultiGrid.h.
MueLuPreconditioner_t
typedef MueLuPreconditioner<AmrMultiGridLevel_t> AmrMultiGrid::MueLuPreconditioner_t
Definition at line 81 of file AmrMultiGrid.h.
MueLuSolver_t
typedef MueLuBottomSolver<AmrMultiGridLevel_t> AmrMultiGrid::MueLuSolver_t
Definition at line 76 of file AmrMultiGrid.h.
mv_t
typedef amr::multivector_t AmrMultiGrid::mv_t
Definition at line 49 of file AmrMultiGrid.h.
Preconditioner
typedef amr::Preconditioner AmrMultiGrid::Preconditioner
Definition at line 90 of file AmrMultiGrid.h.
preconditioner_t
typedef AmrPreconditioner<matrix_t, AmrMultiGridLevel_t> AmrMultiGrid::preconditioner_t
Definition at line 78 of file AmrMultiGrid.h.
scalar_t
typedef amr::scalar_t AmrMultiGrid::scalar_t
Definition at line 54 of file AmrMultiGrid.h.
Smoother
typedef AmrSmoother::Smoother AmrMultiGrid::Smoother
Definition at line 88 of file AmrMultiGrid.h.
umap_t
typedef AmrMultiGridLevel_t::umap_t AmrMultiGrid::umap_t
Definition at line 65 of file AmrMultiGrid.h.
vector_t
typedef amr::vector_t AmrMultiGrid::vector_t
Definition at line 48 of file AmrMultiGrid.h.
Member Enumeration Documentation
BaseSolver
enum AmrMultiGrid::BaseSolver
Supported bottom solvers.
Enumerator
BICGSTAB
MINRES
PCPG
CG
GMRES
STOCHASTIC_CG
RECYCLING_CG
RECYCLING_GMRES
SA
Definition at line 100 of file AmrMultiGrid.h.
Boundary
enum AmrMultiGrid::Boundary
Supported physical boundaries.
Enumerator
DIRICHLET
OPEN
PERIODIC
Definition at line 135 of file AmrMultiGrid.h.
Interpolater
enum AmrMultiGrid::Interpolater
Supported interpolaters for prolongation operation.
Enumerator
TRILINEAR
LAGRANGE
PIECEWISE_CONST
Definition at line 93 of file AmrMultiGrid.h.
Norm
enum AmrMultiGrid::Norm
Supported convergence criteria.
Enumerator
L1
L2
LINF
Definition at line 142 of file AmrMultiGrid.h.
Constructor & Destructor Documentation
AmrMultiGrid()
AmrMultiGrid::AmrMultiGrid (AmrBoxLib * itsAmrObject_p, const std::string & bsolver, const std::string & prec, const bool & rebalance, const std::string & reuse, const std::string & bcx, const std::string & bcy, const std::string & bcz, const std::string & smoother, const std::size_t & nSweeps, const std::string & interp, const std::string & norm)
Instantiation used in Structure/FieldSolver.cpp
Parameters
itsAmrObject_p has information about refinemen ratios, etc.
bsolver bottom solver
prec preconditioner for bottom solver
rebalance of preconditioner (SA only)
bcx boundary condition in x
bcy boundary condition in y
bcz boundary condition in z
smoother for level solution
nSweeps when smoothing
interp interpolater between levels
norm for convergence criteria
Definition at line 42 of file AmrMultiGrid.cpp.
References convertToEnumBaseSolver_m(), convertToEnumBoundary_m(), convertToEnumInterpolater_m(), convertToEnumNorm_m(), convertToEnumPreconditioner_m(), convertToEnumSmoother_m(), endl(), flag_m, fname_m, INFOMSG, initBaseSolver_m(), initCrseFineInterp_m(), initInterpolater_m(), initPhysicalBoundary_m(), initPrec_m(), norm_m, and smootherType_m.
Member Function Documentation
amrex2trilinos_m()
void AmrMultiGrid::amrex2trilinos_m (const lo_t & level, const lo_t & comp, const AmrField_t & mf, Teuchos::RCP< vector_t > & mv) private
Data transfer from AMReX to Trilinos.
Parameters
mf is the multifab of a level
comp component to copy
mv is the vector to be filled
level where to perform
Definition at line 1656 of file AmrMultiGrid.cpp.
References mglevel_m.
Referenced by buildDensityVector_m(), and buildPotentialVector_m().
averageDown_m()
void AmrMultiGrid::averageDown_m (const lo_t & level) private
Average data from fine level to coarse
Parameters
level finest level is omitted
Definition at line 1844 of file AmrMultiGrid.cpp.
References lfine_m, mglevel_m, IpplTimings::startTimer(), and IpplTimings::stopTimer().
Referenced by solve().
buildCompositePoissonMatrix_m()
void AmrMultiGrid::buildCompositePoissonMatrix_m (const lo_t & level, const go_t & gidx, const AmrIntVect_t & iv, const basefab_t & mfab, const basefab_t & rfab, const scalar_t * invdx2) private
Build the Poisson matrix for a level that got refined (it does not take the covered cells (covered by fine cells) into account). The finest level does not build such a matrix. It takes care of physical boundaries (i.e. mesh boundary). Internal boundaries (i.e. boundaries due to crse-fine interfaces) are treated by the boundary matrix.
Parameters
iv is the current cell
mfab is the mask (internal cell, boundary cell, ...) of that level
rfab is the mask between levels
level for which we build the special Poisson matrix
Definition at line 1111 of file AmrMultiGrid.cpp.
References interface_mp, lbase_m, map2vector_m(), and mglevel_m.
Referenced by buildMultiLevel_m().
buildCrseBoundaryMatrix_m()
void AmrMultiGrid::buildCrseBoundaryMatrix_m (const lo_t & level, const go_t & gidx, const AmrIntVect_t & iv, const basefab_t & mfab, const basefab_t & cfab, const scalar_t * invdx2) private
The boundary values at the crse-fine-interface need to be taken into account properly. This matrix is used to update the fine boundary values from the coarse values, i.e.
\[ x^{(l)} = B_{crse}\cdot x^{(l-1)} \]
Dirichlet boundary condition
Parameters
iv is the current cell
mfab is the mask (internal cell, boundary cell, ...) of that level
cells all fine cells that are at the crse-fine interface
level the base level is omitted
Definition at line 1358 of file AmrMultiGrid.cpp.
References interface_mp, lbase_m, map2vector_m(), and mglevel_m.
Referenced by buildMultiLevel_m().
buildDensityVector_m()
void AmrMultiGrid::buildDensityVector_m (const lo_t & level, const AmrField_t & rho) inline private
Copy data from AMReX to Trilinos
Parameters
rho is the charge density
level for which to copy
Definition at line 1564 of file AmrMultiGrid.cpp.
References amrex2trilinos_m(), and mglevel_m.
Referenced by buildMultiLevel_m(), and buildSingleLevel_m().
buildFineBoundaryMatrix_m()
void AmrMultiGrid::buildFineBoundaryMatrix_m (const lo_t & level, const go_t & gidx, const AmrIntVect_t & iv, const basefab_t & mfab, const basefab_t & rfab) private
The boundary values at the crse-fine-interface need to be taken into account properly. This matrix is used to update the coarse boundary values from fine values, i.e.
\[ x^{(l)} = B_{fine}\cdot x^{(l+1)} \]
Dirichlet boundary condition. Flux matching.
Parameters
level the finest level is omitted
gidx the global index
iv is the current cell
mfab is the mask (internal cell, boundary cell, ...) of that level
rfab is the mask between levels
Definition at line 1423 of file AmrMultiGrid.cpp.
References begin(), end(), interface_mp, lfine_m, map2vector_m(), mglevel_m, and AmrMultiGridLevel< MatrixType, VectorType >::PHYSBNDRY.
Referenced by buildMultiLevel_m().
buildGradientMatrix_m()
void AmrMultiGrid::buildGradientMatrix_m (const lo_t & level, const go_t & gidx, const AmrIntVect_t & iv, const basefab_t & mfab, const scalar_t * invdx) private
Gradient matrix is used to compute the electric field
Parameters
iv is the current cell
mfab is the mask (internal cell, boundary cell, ...) of that level
level for which to compute
Definition at line 1578 of file AmrMultiGrid.cpp.
References lbase_m, map2vector_m(), and mglevel_m.
Referenced by buildMultiLevel_m(), and buildSingleLevel_m().
buildInterpolationMatrix_m()
void AmrMultiGrid::buildInterpolationMatrix_m (const lo_t & level, const go_t & gidx, const AmrIntVect_t & iv, const basefab_t & cfab) private
Interpolate data from coarse cells to appropriate refined cells. The interpolation scheme is allowed only to have local cells in the stencil, i.e. 2D –> 4, 3D –> 8.
\[ x^{(l)} = I\cdot x^{(l-1)} \]
Parameters
iv is the current cell
level for which to build the interpolation matrix. The finest level does not build such a matrix.
Definition at line 1321 of file AmrMultiGrid.cpp.
References interp_mp, lbase_m, map2vector_m(), and mglevel_m.
Referenced by buildMultiLevel_m().
buildMultiLevel_m()
void AmrMultiGrid::buildMultiLevel_m (const amrex::Vector< AmrField_u > & rho, const amrex::Vector< AmrField_u > & phi, const bool & matrices = true) private
Build all matrices and vectors needed for multi-level computation
Definition at line 778 of file AmrMultiGrid.cpp.
References buildCompositePoissonMatrix_m(), buildCrseBoundaryMatrix_m(), buildDensityVector_m(), buildFineBoundaryMatrix_m(), buildGradientMatrix_m(), buildInterpolationMatrix_m(), buildNoFinePoissonMatrix_m(), buildRestrictionMatrix_m(), close_m(), lbase_m, mglevel_m, nlevel_m, nSweeps_m, open_m(), smoother_m, smootherType_m, and solver_mp.
Referenced by setup_m().
buildNoFinePoissonMatrix_m()
void AmrMultiGrid::buildNoFinePoissonMatrix_m (const lo_t & level, const go_t & gidx, const AmrIntVect_t & iv, const basefab_t & mfab, const scalar_t * invdx2) private
Build the Poisson matrix for a level assuming no finer level (i.e. the whole fine mesh is taken into account). It takes care of physical boundaries (i.e. mesh boundary). Internal boundaries (i.e. boundaries due to crse-fine interfaces) are treated by the boundary matrix.
Parameters
iv is the current cell
mfab is the mask (internal cell, boundary cell, ...) of that level
level for which we build the Poisson matrix
Definition at line 1030 of file AmrMultiGrid.cpp.
References interface_mp, lbase_m, map2vector_m(), and mglevel_m.
Referenced by buildMultiLevel_m(), and buildSingleLevel_m().
buildPotentialVector_m()
void AmrMultiGrid::buildPotentialVector_m (const lo_t & level, const AmrField_t & phi) inline private
Copy data from AMReX to Trilinos
Parameters
phi is the potential
level for which to copy
Definition at line 1571 of file AmrMultiGrid.cpp.
References amrex2trilinos_m(), and mglevel_m.
buildRestrictionMatrix_m()
void AmrMultiGrid::buildRestrictionMatrix_m (const lo_t & level, const go_t & gidx, const AmrIntVect_t & iv, D_DECL(const go_t &ii, const go_t &jj, const go_t &kk) , const basefab_t & rfab) private
Build a matrix that averages down the data of the fine cells down to the corresponding coarse cells. The base level does not build such a matrix.
\[ x^{(l)} = R\cdot x^{(l+1)} \]
Parameters
iv is the current cell
rfab is the mask between levels
level for which to build restriction matrix
Definition at line 1269 of file AmrMultiGrid.cpp.
References lfine_m, mglevel_m, and serialize().
Referenced by buildMultiLevel_m().
buildSingleLevel_m()
void AmrMultiGrid::buildSingleLevel_m (const amrex::Vector< AmrField_u > & rho, const amrex::Vector< AmrField_u > & phi, const bool & matrices = true) private
Build all matrices and vectors needed for single-level computation
Definition at line 717 of file AmrMultiGrid.cpp.
References buildDensityVector_m(), buildGradientMatrix_m(), buildNoFinePoissonMatrix_m(), close_m(), lbase_m, mglevel_m, open_m(), and solver_mp.
Referenced by setup_m().
clearMasks_m()
void AmrMultiGrid::clearMasks_m () private
Clear masks (required to build matrices) no longer needed.
Definition at line 317 of file AmrMultiGrid.cpp.
References mglevel_m, and nlevel_m.
Referenced by setup_m().
close_m()
void AmrMultiGrid::close_m (const lo_t & level, const bool & matrices) private
Call fill complete
Parameters
level for which we filled matrix
matrices if we set matrices as well.
Definition at line 992 of file AmrMultiGrid.cpp.
References lbase_m, lfine_m, mglevel_m, and solver_mp.
Referenced by buildMultiLevel_m(), and buildSingleLevel_m().
computeEfield_m()
void AmrMultiGrid::computeEfield_m (AmrVectorFieldContainer_t & efield) private
Parameters
efield to compute
Definition at line 664 of file AmrMultiGrid.cpp.
References lbase_m, mglevel_m, nlevel_m, IpplTimings::startTimer(), IpplTimings::stopTimer(), and trilinos2amrex_m().
Referenced by solve().
convertToEnumBaseSolver_m()
AmrMultiGrid::BaseSolver AmrMultiGrid::convertToEnumBaseSolver_m (const std::string & bsolver) private
Converts string to enum BaseSolver
Parameters
bsolver bottom solver
Definition at line 2041 of file AmrMultiGrid.cpp.
References amr::SA.
Referenced by AmrMultiGrid().
convertToEnumBoundary_m()
AmrMultiGrid::Boundary AmrMultiGrid::convertToEnumBoundary_m (const std::string & bc) private
Convertstring to enum Boundary
Parameters
bc boundary condition
Definition at line 2008 of file AmrMultiGrid.cpp.
Referenced by AmrMultiGrid().
convertToEnumInterpolater_m()
AmrMultiGrid::Interpolater AmrMultiGrid::convertToEnumInterpolater_m (const std::string & interp) private
Converts string to enum Interpolater
Parameters
interp interpolater
Definition at line 2024 of file AmrMultiGrid.cpp.
Referenced by AmrMultiGrid().
convertToEnumNorm_m()
AmrMultiGrid::Norm AmrMultiGrid::convertToEnumNorm_m (const std::string & norm) private
Converts string to enum Norm
Parameters
norm either L1, L2, LInf
Definition at line 2107 of file AmrMultiGrid.cpp.
References Hypervolume::n.
Referenced by AmrMultiGrid().
convertToEnumPreconditioner_m()
AmrMultiGrid::Preconditioner AmrMultiGrid::convertToEnumPreconditioner_m (const std::string & prec) private
Converts string to enum Preconditioner
Parameters
prec preconditioner
Definition at line 2082 of file AmrMultiGrid.cpp.
References Ifpack2Preconditioner< Level >::fillMap(), MueLuPreconditioner< Level >::fillMap(), and EmissionModelT::NONE.
Referenced by AmrMultiGrid().
convertToEnumSmoother_m()
AmrMultiGrid::Smoother AmrMultiGrid::convertToEnumSmoother_m (const std::string & smoother) private
Converts string to enum Smoother
Parameters
smoother of level solution
Definition at line 2101 of file AmrMultiGrid.cpp.
References AmrSmoother::convertToEnumSmoother().
Referenced by AmrMultiGrid().
evalNorm_m()
AmrMultiGrid::scalar_t AmrMultiGrid::evalNorm_m (const Teuchos::RCP< const vector_t > & x) private
Vector norm computation.
Parameters
x is the vector for which we compute the norm
Returns
the evaluated norm of a level
Definition at line 595 of file AmrMultiGrid.cpp.
References norm_m.
Referenced by getLevelResidualNorm(), and initResidual_m().
getLevelResidualNorm()
AmrMultiGrid::scalar_t AmrMultiGrid::getLevelResidualNorm (lo_t level)
Obtain the residual norm of a level
Parameters
level for which error is requested
Returns
the norm of the residual
Definition at line 184 of file AmrMultiGrid.cpp.
References evalNorm_m(), and mglevel_m.
Referenced by iterate_m().
getNumIters()
std::size_t AmrMultiGrid::getNumIters ()
Obtain some convergence info
Returns
the number of iterations till convergence
Definition at line 179 of file AmrMultiGrid.cpp.
References nIter_m.
getXRangeMax()
double AmrMultiGrid::getXRangeMax (unsigned short level = 0) virtual
Implements PoissonSolver.
Definition at line 2241 of file AmrMultiGrid.cpp.
References AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp.
getXRangeMin()
double AmrMultiGrid::getXRangeMin (unsigned short level = 0) virtual
Implements PoissonSolver.
Definition at line 2236 of file AmrMultiGrid.cpp.
References AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp.
getYRangeMax()
double AmrMultiGrid::getYRangeMax (unsigned short level = 0) virtual
Implements PoissonSolver.
Definition at line 2251 of file AmrMultiGrid.cpp.
References AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp.
getYRangeMin()
double AmrMultiGrid::getYRangeMin (unsigned short level = 0) virtual
Implements PoissonSolver.
Definition at line 2246 of file AmrMultiGrid.cpp.
References AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp.
getZRangeMax()
double AmrMultiGrid::getZRangeMax (unsigned short level = 0) virtual
Implements PoissonSolver.
Definition at line 2261 of file AmrMultiGrid.cpp.
References AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp.
getZRangeMin()
double AmrMultiGrid::getZRangeMin (unsigned short level = 0) virtual
Implements PoissonSolver.
Definition at line 2256 of file AmrMultiGrid.cpp.
References AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp.
initBaseSolver_m()
void AmrMultiGrid::initBaseSolver_m (const BaseSolver & solver, const bool & rebalance, const std::string & reuse) private
Instantiate a bottom solver
Parameters
solver type
rebalance solver (SA only)
reuse types of SA hierarchy
Definition at line 1904 of file AmrMultiGrid.cpp.
References MueLuBottomSolver< Level >::convertToMueLuReuseOption(), prec_mp, amr::SA, and solver_mp.
Referenced by AmrMultiGrid().
initCrseFineInterp_m()
void AmrMultiGrid::initCrseFineInterp_m (const Interpolater & interface) private
Instantiate interface interpolater
Parameters
interface handler
Definition at line 1885 of file AmrMultiGrid.cpp.
References interface_mp.
Referenced by AmrMultiGrid().
initGuess_m()
void AmrMultiGrid::initGuess_m (bool reset) private
Reset potential to zero (currently)
Parameters
reset solution to initial guess (zero)
Definition at line 326 of file AmrMultiGrid.cpp.
References mglevel_m, and nlevel_m.
Referenced by solve().
initInterpolater_m()
void AmrMultiGrid::initInterpolater_m (const Interpolater & interp) private
Instantiate interpolater
Parameters
interp interpolater type
Definition at line 1867 of file AmrMultiGrid.cpp.
References interp_mp.
Referenced by AmrMultiGrid().
initLevels_m()
void AmrMultiGrid::initLevels_m (const amrex::Vector< AmrField_u > & rho, const amrex::Vector< AmrGeometry_t > & geom, bool regrid) private
Instantiate all levels and set boundary conditions
Parameters
rho is the charge density
geom is the geometry
regrid was performed
Definition at line 227 of file AmrMultiGrid.cpp.
References bc_m, comm_mp, AmrBoxLib::getMeshScaling(), AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp, lbase_m, mglevel_m, and nlevel_m.
Referenced by solve().
initPhysicalBoundary_m()
void AmrMultiGrid::initPhysicalBoundary_m (const Boundary * bc) private
Instantiate boundary object
Parameters
bc boundary conditions length must be equal to AMREX_SPACEDIM
Definition at line 199 of file AmrMultiGrid.cpp.
References bc_m, and nBcPoints_m.
Referenced by AmrMultiGrid().
initPrec_m()
void AmrMultiGrid::initPrec_m (const Preconditioner & prec, const std::string & reuse) private
Instantiate a preconditioner for the bottom solver
Parameters
precond type
reuse types of SA hierarchy
Definition at line 1978 of file AmrMultiGrid.cpp.
References amr::BLOCK_GS, amr::BLOCK_JACOBI, amr::CHEBYSHEV, MueLuPreconditioner< Level >::convertToMueLuReuseOption(), amr::GS, amr::ILUT, amr::JACOBI, EmissionModelT::NONE, prec_mp, amr::RILUK, and amr::SA.
Referenced by AmrMultiGrid().
initResidual_m()
void AmrMultiGrid::initResidual_m (std::vector< scalar_t > & rhsNorms, std::vector< scalar_t > & resNorms) private
Initial convergence criteria values.
Parameters
rhsNorms per level of right-hand side (is filled)
resNorms per level of residual (is filled)
Definition at line 623 of file AmrMultiGrid.cpp.
References comm_mp, endl(), evalNorm_m(), mglevel_m, nlevel_m, and residual_m().
Referenced by iterate_m().
isConverged_m()
bool AmrMultiGrid::isConverged_m (std::vector< scalar_t > & rhsNorms, std::vector< scalar_t > & resNorms) private
Compute norms / level and check convergence
Returns
true if converged
Definition at line 391 of file AmrMultiGrid.cpp.
Referenced by iterate_m().
iterate_m()
AmrMultiGrid::scalar_t AmrMultiGrid::iterate_m () private
Actual solve.
Returns
the the max. residual
Definition at line 336 of file AmrMultiGrid.cpp.
References bIter_m, eps_m, for_each(), getLevelResidualNorm(), initResidual_m(), isConverged_m(), lfine_m, maxiter_m, mglevel_m, nIter_m, nlevel_m, relax_m(), residual_m(), and solver_mp.
Referenced by solve().
map2vector_m()
void AmrMultiGrid::map2vector_m (umap_t & map, indices_t & indices, coefficients_t & values) inline private
Some indices might occur several times due to boundary conditions, etc. We avoid this by filling a map and then copying the data to a vector for filling the matrices. The map gets cleared inside the function.
Parameters
indices in matrix
values are the coefficients
Definition at line 1725 of file AmrMultiGrid.cpp.
References for_each().
Referenced by buildCompositePoissonMatrix_m(), buildCrseBoundaryMatrix_m(), buildFineBoundaryMatrix_m(), buildGradientMatrix_m(), buildInterpolationMatrix_m(), and buildNoFinePoissonMatrix_m().
open_m()
void AmrMultiGrid::open_m (const lo_t & level, const bool & matrices) private
Set matrix and vector pointer
Parameters
level for which we fill matrix + vector
matrices if we need to set matrices as well or only vectors.
Definition at line 876 of file AmrMultiGrid.cpp.
References interface_mp, interp_mp, lbase_m, lfine_m, mglevel_m, nBcPoints_m, and solver_mp.
Referenced by buildMultiLevel_m(), and buildSingleLevel_m().
print()
Inform & AmrMultiGrid::print (Inform & os) const
Print information abour tolerances.
Parameters
os output stream where to write to
Definition at line 2266 of file AmrMultiGrid.cpp.
References endl().
prolongate_m()
void AmrMultiGrid::prolongate_m (const lo_t & level) private
Update error of fine level based on error of coarse level
Parameters
level to update
Definition at line 1827 of file AmrMultiGrid.cpp.
References mglevel_m, IpplTimings::startTimer(), and IpplTimings::stopTimer().
Referenced by relax_m().
relax_m()
void AmrMultiGrid::relax_m (const lo_t & level) private
Recursive call.
Parameters
level to relax
Definition at line 463 of file AmrMultiGrid.cpp.
References lbase_m, lfine_m, mglevel_m, prolongate_m(), residual_no_fine_m(), restrict_m(), smooth_m(), solver_mp, IpplTimings::startTimer(), and IpplTimings::stopTimer().
Referenced by iterate_m().
residual_m()
void AmrMultiGrid::residual_m (const lo_t & level, Teuchos::RCP< vector_t > & r, const Teuchos::RCP< vector_t > & b, const Teuchos::RCP< vector_t > & x) private
Compute composite residual of a level
Parameters
r is the residual to compute
b is the right-hand side
x is the left-hand side
level to solve for
Definition at line 400 of file AmrMultiGrid.cpp.
References lfine_m, and mglevel_m.
Referenced by initResidual_m(), and iterate_m().
residual_no_fine_m()
void AmrMultiGrid::residual_no_fine_m (const lo_t & level, Teuchos::RCP< vector_t > & result, const Teuchos::RCP< vector_t > & rhs, const Teuchos::RCP< vector_t > & crs_rhs, const Teuchos::RCP< vector_t > & b) private
Compute the residual of a level without considering refined level.
Parameters
result is computed
rhs is the right-hand side
crs_rhs is the coarse right-hand side for internal boundary
b is the left-hand side
level to solver for
Definition at line 550 of file AmrMultiGrid.cpp.
References mglevel_m.
Referenced by relax_m(), and restrict_m().
restrict_m()
void AmrMultiGrid::restrict_m (const lo_t & level) private
Restrict coarse level residual based on fine level residual
Parameters
level to restrict
Definition at line 1770 of file AmrMultiGrid.cpp.
References mglevel_m, residual_no_fine_m(), IpplTimings::startTimer(), and IpplTimings::stopTimer().
Referenced by relax_m().
setMaxNumberOfIterations()
void AmrMultiGrid::setMaxNumberOfIterations (const std::size_t & maxiter)
Specify the maximum number of iterations
Parameters
maxiter \([0, \infty[ \)
Definition at line 170 of file AmrMultiGrid.cpp.
References maxiter_m.
setNumberOfSweeps()
void AmrMultiGrid::setNumberOfSweeps (const std::size_t & nSweeps)
Specify the number of smoothing steps
Parameters
nSweeps for each smoothing step
Definition at line 165 of file AmrMultiGrid.cpp.
References nSweeps_m.
setTolerance()
void AmrMultiGrid::setTolerance (const scalar_t & eps)
Change accuracy of solver
Definition at line 194 of file AmrMultiGrid.cpp.
References eps_m.
setup_m()
void AmrMultiGrid::setup_m (const amrex::Vector< AmrField_u > & rho, const amrex::Vector< AmrField_u > & phi, const bool & matrices = true) private
Build all matrices and vectors, i.e. AMReX to Trilinos
Parameters
matrices if we need to build matrices as well or only vectors.
Definition at line 688 of file AmrMultiGrid.cpp.
References buildMultiLevel_m(), buildSingleLevel_m(), clearMasks_m(), lbase_m, lfine_m, mglevel_m, solver_mp, IpplTimings::startTimer(), and IpplTimings::stopTimer().
Referenced by solve().
setVerbose()
void AmrMultiGrid::setVerbose (bool verbose)
Enable solver info dumping into SDDS file
Definition at line 189 of file AmrMultiGrid.cpp.
References verbose_m.
smooth_m()
void AmrMultiGrid::smooth_m (const lo_t & level, Teuchos::RCP< vector_t > & e, Teuchos::RCP< vector_t > & r) private
Perform one smoothing step
Parameters
e error to update (left-hand side)
r residual (right-hand side)
level on which to relax
Definition at line 1753 of file AmrMultiGrid.cpp.
References Physics::e, smoother_m, IpplTimings::startTimer(), and IpplTimings::stopTimer().
Referenced by relax_m().
solve()
void AmrMultiGrid::solve (AmrScalarFieldContainer_t & rho, AmrScalarFieldContainer_t & phi, AmrVectorFieldContainer_t & efield, unsigned short baseLevel, unsigned short finestLevel, bool prevAsGuess = true) virtual
Used in OPAL
Parameters
rho right-hand side charge density on grid [C / m]
phi electrostatic potential (unknown) [V]
efield electric field [V / m]
baseLevel for solve
finestLevel for solve
prevAsGuess use of previous solution as initial guess
Reimplemented from PoissonSolver.
Definition at line 110 of file AmrMultiGrid.cpp.
References averageDown_m(), computeEfield_m(), initGuess_m(), initLevels_m(), iterate_m(), AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp, lbase_m, lfine_m, mglevel_m, nlevel_m, AmrPoissonSolver< AmrBoxLib >::regrid_m, setup_m(), trilinos2amrex_m(), verbose_m, and writeSDDSData_m().
trilinos2amrex_m()
void AmrMultiGrid::trilinos2amrex_m (const lo_t & level, const lo_t & comp, AmrField_t & mf, const Teuchos::RCP< vector_t > & mv) private
Data transfer from Trilinos to AMReX.
Parameters
level to copy
comp component to copy
mf is the multifab to be filled
mv is the corresponding Trilinos vector
Definition at line 1690 of file AmrMultiGrid.cpp.
References mglevel_m.
Referenced by computeEfield_m(), and solve().
writeSDDSData_m()
void AmrMultiGrid::writeSDDSData_m (const scalar_t & error) private
SDDS data write (done by root core)
Parameters
error to write
Definition at line 2192 of file AmrMultiGrid.cpp.
References bIter_m, comm_mp, flag_m, fname_m, AmrBoxLib::getT(), AmrPoissonSolver< AmrBoxLib >::itsAmrObject_mp, nIter_m, AmrPoissonSolver< AmrBoxLib >::regrid_m, IpplTimings::startTimer(), IpplTimings::stopTimer(), and writeSDDSHeader_m().
Referenced by solve().
writeSDDSHeader_m()
void AmrMultiGrid::writeSDDSHeader_m (std::ofstream & outfile) private
SDDS header is written by root core
Parameters
outfile output stream
Definition at line 2123 of file AmrMultiGrid.cpp.
References comm_mp, OPALTimer::Timer::date(), endl(), Util::getGitRevision(), OpalData::getInputFn(), OpalData::getInstance(), OpalData::isInOPALCyclMode(), OpalData::isInOPALTMode(), OPAL_PROJECT_NAME, OPAL_PROJECT_VERSION, snorm_m, and OPALTimer::Timer::time().
Referenced by writeSDDSData_m().
Member Data Documentation
bc_m
boundary_t AmrMultiGrid::bc_m[AMREX_SPACEDIM] private
boundary conditions
Definition at line 693 of file AmrMultiGrid.h.
Referenced by initLevels_m(), and initPhysicalBoundary_m().
bIter_m
std::size_t AmrMultiGrid::bIter_m private
number of iterations of bottom solver
Definition at line 672 of file AmrMultiGrid.h.
Referenced by iterate_m(), and writeSDDSData_m().
comm_mp
Teuchos::RCP<comm_t> AmrMultiGrid::comm_mp private
communicator
Definition at line 663 of file AmrMultiGrid.h.
Referenced by initLevels_m(), initResidual_m(), writeSDDSData_m(), and writeSDDSHeader_m().
eps_m
scalar_t AmrMultiGrid::eps_m private
rhs scale for convergence
Definition at line 699 of file AmrMultiGrid.h.
Referenced by iterate_m(), and setTolerance().
flag_m
std::ios_base::openmode AmrMultiGrid::flag_m private
std::ios::out or std::ios::app
Definition at line 703 of file AmrMultiGrid.h.
Referenced by AmrMultiGrid(), and writeSDDSData_m().
fname_m
std::string AmrMultiGrid::fname_m private
SDDS filename.
Definition at line 702 of file AmrMultiGrid.h.
Referenced by AmrMultiGrid(), and writeSDDSData_m().
interface_mp
std::unique_ptr<AmrInterpolater<AmrMultiGridLevel_t> > AmrMultiGrid::interface_mp private
interpolater for coarse-fine interface
Definition at line 669 of file AmrMultiGrid.h.
Referenced by buildCompositePoissonMatrix_m(), buildCrseBoundaryMatrix_m(), buildFineBoundaryMatrix_m(), buildNoFinePoissonMatrix_m(), initCrseFineInterp_m(), and open_m().
interp_mp
std::unique_ptr<AmrInterpolater<AmrMultiGridLevel_t> > AmrMultiGrid::interp_mp private
interpolater without coarse-fine interface
Definition at line 666 of file AmrMultiGrid.h.
Referenced by buildInterpolationMatrix_m(), initInterpolater_m(), and open_m().
lbase_m
int AmrMultiGrid::lbase_m private
base level (currently only 0 supported)
Definition at line 689 of file AmrMultiGrid.h.
Referenced by buildCompositePoissonMatrix_m(), buildCrseBoundaryMatrix_m(), buildGradientMatrix_m(), buildInterpolationMatrix_m(), buildMultiLevel_m(), buildNoFinePoissonMatrix_m(), buildSingleLevel_m(), close_m(), computeEfield_m(), initLevels_m(), open_m(), relax_m(), setup_m(), and solve().
lfine_m
int AmrMultiGrid::lfine_m private
fineste level
Definition at line 690 of file AmrMultiGrid.h.
Referenced by averageDown_m(), buildFineBoundaryMatrix_m(), buildRestrictionMatrix_m(), close_m(), iterate_m(), open_m(), relax_m(), residual_m(), setup_m(), and solve().
maxiter_m
std::size_t AmrMultiGrid::maxiter_m private
maximum number of iterations allowed
Definition at line 673 of file AmrMultiGrid.h.
Referenced by iterate_m(), and setMaxNumberOfIterations().
mglevel_m
std::vector<std::unique_ptr<AmrMultiGridLevel_t > > AmrMultiGrid::mglevel_m private
container for levels
Definition at line 678 of file AmrMultiGrid.h.
Referenced by amrex2trilinos_m(), averageDown_m(), buildCompositePoissonMatrix_m(), buildCrseBoundaryMatrix_m(), buildDensityVector_m(), buildFineBoundaryMatrix_m(), buildGradientMatrix_m(), buildInterpolationMatrix_m(), buildMultiLevel_m(), buildNoFinePoissonMatrix_m(), buildPotentialVector_m(), buildRestrictionMatrix_m(), buildSingleLevel_m(), clearMasks_m(), close_m(), computeEfield_m(), getLevelResidualNorm(), initGuess_m(), initLevels_m(), initResidual_m(), iterate_m(), open_m(), prolongate_m(), relax_m(), residual_m(), residual_no_fine_m(), restrict_m(), setup_m(), solve(), and trilinos2amrex_m().
nBcPoints_m
int AmrMultiGrid::nBcPoints_m private
maximum number of stencils points for BC
Definition at line 694 of file AmrMultiGrid.h.
Referenced by initPhysicalBoundary_m(), and open_m().
nIter_m
std::size_t AmrMultiGrid::nIter_m private
number of iterations till convergence
Definition at line 671 of file AmrMultiGrid.h.
Referenced by getNumIters(), iterate_m(), and writeSDDSData_m().
nlevel_m
int AmrMultiGrid::nlevel_m private
number of levelss
Definition at line 691 of file AmrMultiGrid.h.
Referenced by buildMultiLevel_m(), clearMasks_m(), computeEfield_m(), initGuess_m(), initLevels_m(), initResidual_m(), iterate_m(), and solve().
norm_m
Norm AmrMultiGrid::norm_m private
norm for convergence criteria (l1, l2, linf)
Definition at line 696 of file AmrMultiGrid.h.
Referenced by AmrMultiGrid(), and evalNorm_m().
nSweeps_m
std::size_t AmrMultiGrid::nSweeps_m private
number of smoothing iterations
Definition at line 674 of file AmrMultiGrid.h.
Referenced by buildMultiLevel_m(), and setNumberOfSweeps().
prec_mp
std::shared_ptr<preconditioner_t> AmrMultiGrid::prec_mp private
preconditioner for bottom solver
Definition at line 687 of file AmrMultiGrid.h.
Referenced by initBaseSolver_m(), and initPrec_m().
smoother_m
std::vector<std::shared_ptr<AmrSmoother> > AmrMultiGrid::smoother_m private
error smoother
Definition at line 684 of file AmrMultiGrid.h.
Referenced by buildMultiLevel_m(), and smooth_m().
smootherType_m
Smoother AmrMultiGrid::smootherType_m private
type of smoother
Definition at line 675 of file AmrMultiGrid.h.
Referenced by AmrMultiGrid(), and buildMultiLevel_m().
snorm_m
std::string AmrMultiGrid::snorm_m private
norm for convergence criteria
Definition at line 697 of file AmrMultiGrid.h.
Referenced by writeSDDSHeader_m().
solver_mp
std::shared_ptr<bsolver_t> AmrMultiGrid::solver_mp private
bottom solver
Definition at line 681 of file AmrMultiGrid.h.
Referenced by buildMultiLevel_m(), buildSingleLevel_m(), close_m(), initBaseSolver_m(), iterate_m(), open_m(), relax_m(), and setup_m().
verbose_m
bool AmrMultiGrid::verbose_m private
If true, a SDDS file is written.
Definition at line 701 of file AmrMultiGrid.h.
Referenced by setVerbose(), and solve().
The documentation for this class was generated from the following files:
src/Solvers/AMR_MG/AmrMultiGrid.h
src/Solvers/AMR_MG/AmrMultiGrid.cpp