OPAL (Object Oriented Parallel Accelerator Library): OpalVerticalFFAMagnet Class Reference
OpalVerticalFFAMagnet Class Reference
#include <OpalVerticalFFAMagnet.h>
Public Types
enum {
B0 = COMMON, FIELD_INDEX, WIDTH, MAX_HORIZONTAL_POWER,
END_LENGTH, CENTRE_LENGTH, BB_LENGTH, HEIGHT_NEG_EXTENT,
HEIGHT_POS_EXTENT, SIZE
}
Public Types inherited from OpalElement
enum {
TYPE, APERT, LENGTH, ELEMEDGE,
WAKEF, PARTICLEMATTERINTERACTION, ORIGIN, ORIENTATION,
X, Y, Z, THETA,
PHI, PSI, DX, DY,
DZ, DTHETA, DPHI, DPSI,
OUTFN, DELETEONTRANSVERSEEXIT, COMMON
}
The common attributes for all elements.
Public Types inherited from Element
enum ReferenceType { IS_ENTRY, IS_CENTRE, IS_EXIT }
Reference for element positioning.
Public Member Functions
OpalVerticalFFAMagnet ()
virtual ~OpalVerticalFFAMagnet ()
virtual OpalVerticalFFAMagnet * clone (const std::string &name)
virtual void update ()
Public Member Functions inherited from OpalElement
virtual ~OpalElement ()
virtual double getLength () const
Return element length.
const std::string getTypeName () const
Return the element's type name.
std::pair< ApertureType, std::vector< double > > getApert () const
const std::string getWakeF () const
Return the element's type name.
const std::string getParticleMatterInteraction () const
const std::string getWMaterial () const
const std::string getWakeGeom () const
std::vector< double > getWakeParam () const
const std::string getWakeConductivity () const
virtual void parse (Statement &)
Parse the element.
virtual void print (std::ostream &) const
Print the object.
virtual void updateUnknown (ElementBase *)
Transmit the `‘unknown’' (not known to OPAL) attributes to CLASSIC.
Public Member Functions inherited from Element
virtual ~Element ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual double getEntrance (ReferenceType) const
Return arc length from origin to entrance (negative !).
virtual double getExit (ReferenceType) const
Return arc length from origin to exit (positive !).
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded CLASSIC element.
void setElement (ElementBase *)
Assign new CLASSIC element.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
OpalVerticalFFAMagnet (const OpalVerticalFFAMagnet &)
void operator= (const OpalVerticalFFAMagnet &)
OpalVerticalFFAMagnet (const std::string &name, OpalVerticalFFAMagnet *parent)
Static Private Attributes
static const std::string docstring_m
Additional Inherited Members
Static Public Member Functions inherited from Element
static Element * find (const std::string &name)
Find named Element.
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from OpalElement
OpalElement (int size, const char *name, const char *help)
Exemplar constructor.
OpalElement (const std::string &name, OpalElement *parent)
Clone constructor.
void registerOwnership () const
Protected Member Functions inherited from Element
Element (int size, const char *name, const char *help)
Constructor for exemplars.
Element (const std::string &name, Element *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Static Protected Member Functions inherited from OpalElement
static void printMultipoleStrength (std::ostream &os, int order, int &len, const std::string &sName, const std::string &tName, const Attribute &length, const Attribute &vNorm, const Attribute &vSkew)
Print multipole components in OPAL-8 format.
static void printAttribute (std::ostream &os, const std::string &name, const std::string &image, int &len)
Print an attribute with a OPAL-8 name (as an expression).
static void printAttribute (std::ostream &os, const std::string &name, double value, int &len)
Print an attribute with a OPAL-8 name (as a constant).
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 23 of file OpalVerticalFFAMagnet.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
enum maps string to integer value for UI definitions
Enumerator
B0
FIELD_INDEX
WIDTH
MAX_HORIZONTAL_POWER
END_LENGTH
CENTRE_LENGTH
BB_LENGTH
HEIGHT_NEG_EXTENT
HEIGHT_POS_EXTENT
SIZE
Definition at line 27 of file OpalVerticalFFAMagnet.h.
Constructor & Destructor Documentation
OpalVerticalFFAMagnet() [1/3]
OpalVerticalFFAMagnet::OpalVerticalFFAMagnet ()
Default constructor initialises UI parameters.
Definition at line 29 of file OpalVerticalFFAMagnet.cpp.
References B0, BB_LENGTH, CENTRE_LENGTH, END_LENGTH, FIELD_INDEX, HEIGHT_NEG_EXTENT, HEIGHT_POS_EXTENT, Object::itsAttr, Attributes::makeReal(), MAX_HORIZONTAL_POWER, OpalElement::registerOwnership(), Element::setElement(), VerticalFFAMagnet::setEndField(), and WIDTH.
Referenced by clone().
~OpalVerticalFFAMagnet()
OpalVerticalFFAMagnet::~OpalVerticalFFAMagnet () virtual
Destructor does nothing
Definition at line 83 of file OpalVerticalFFAMagnet.cpp.
OpalVerticalFFAMagnet() [2/3]
OpalVerticalFFAMagnet::OpalVerticalFFAMagnet (const OpalVerticalFFAMagnet &) private
OpalVerticalFFAMagnet() [3/3]
OpalVerticalFFAMagnet::OpalVerticalFFAMagnet (const std::string & name, OpalVerticalFFAMagnet * parent) private
Definition at line 75 of file OpalVerticalFFAMagnet.cpp.
References name, Element::setElement(), and VerticalFFAMagnet::setEndField().
Member Function Documentation
clone()
OpalVerticalFFAMagnet * OpalVerticalFFAMagnet::clone (const std::string & name) virtual
Inherited copy constructor
Implements Object.
Definition at line 86 of file OpalVerticalFFAMagnet.cpp.
References name, and OpalVerticalFFAMagnet().
operator=()
void OpalVerticalFFAMagnet::operator= (const OpalVerticalFFAMagnet &) private
update()
void OpalVerticalFFAMagnet::update () virtual
Update the VerticalFFA with new parameters from UI parser
Reimplemented from OpalElement.
Definition at line 90 of file OpalVerticalFFAMagnet.cpp.
References B0, BB_LENGTH, CENTRE_LENGTH, END_LENGTH, FIELD_INDEX, floor(), Element::getElement(), VerticalFFAMagnet::getEndField(), Attributes::getReal(), HEIGHT_NEG_EXTENT, HEIGHT_POS_EXTENT, VerticalFFAMagnet::initialise(), Object::itsAttr, MAX_HORIZONTAL_POWER, VerticalFFAMagnet::setB0(), VerticalFFAMagnet::setBBLength(), Element::setElement(), VerticalFFAMagnet::setFieldIndex(), endfieldmodel::Tanh::setLambda(), VerticalFFAMagnet::setMaxOrder(), VerticalFFAMagnet::setNegativeVerticalExtent(), VerticalFFAMagnet::setPositiveVerticalExtent(), endfieldmodel::Tanh::setTanhDiffIndices(), VerticalFFAMagnet::setWidth(), endfieldmodel::Tanh::setX0(), and WIDTH.
Member Data Documentation
docstring_m
const std::string OpalVerticalFFAMagnet::docstring_m static private
Initial value:
=
      std::string("The \"VerticalFFAMagnet\" element defines a vertical FFA ") +
      std::string("magnet, which has a field that increases in the vertical ") +
      std::string("direction while maintaining similar orbits.")
Definition at line 60 of file OpalVerticalFFAMagnet.h.
The documentation for this class was generated from the following files:
src/Elements/OpalVerticalFFAMagnet.h
src/Elements/OpalVerticalFFAMagnet.cpp