OPAL (Object Oriented Parallel Accelerator Library): MultipoleRep Class Reference
MultipoleRep Class Reference
#include <MultipoleRep.h>
Public Member Functions
MultipoleRep (const std::string &name)
Constructor with given name.
MultipoleRep ()
MultipoleRep (const MultipoleRep &)
virtual ~MultipoleRep ()
virtual ElementBase * clone () const
Return clone.
virtual Channel * getChannel (const std::string &aKey, bool=false)
Construct a read/write channel.
virtual BMultipoleField & getField ()
Get field.
virtual const BMultipoleField & getField () const
Get field.
virtual StraightGeometry & getGeometry ()
Get geometry.
virtual const StraightGeometry & getGeometry () const
Get geometry.
virtual void setField (const BMultipoleField &field)
Set mulitpole field.
Public Member Functions inherited from Multipole
Multipole (const std::string &name)
Constructor with given name.
Multipole ()
Multipole (const Multipole &)
virtual ~Multipole ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to Multipole.
double getNormalComponent (int n) const
Get normal component.
double getSkewComponent (int n) const
Get skew component.
void setNormalComponent (int, double)
Set normal component.
void setNormalComponent (int, double, double)
Set normal component.
void setSkewComponent (int, double)
Set skew component.
void setSkewComponent (int, double, double)
Set skew component.
size_t getMaxNormalComponentIndex () const
size_t getMaxSkewComponentIndex () const
void setNSlices (const std::size_t &nSlices)
std::size_t getNSlices () const
bool isFocusing (unsigned int component) const
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void finalise () override
virtual bool bends () const override
virtual ElementBase::ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
virtual bool isInside (const Vector_t &r) const override
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual void setComponentType (std::string)
virtual std::string getComponentType () const
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void operator= (const MultipoleRep &)
Private Attributes
StraightGeometry geometry
Multipole geometry.
BMultipoleField field
Multipole field.
Additional Inherited Members
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 24 of file MultipoleRep.h.
Constructor & Destructor Documentation
MultipoleRep() [1/3]
MultipoleRep::MultipoleRep (const std::string & name) explicit
Constructor with given name.
Definition at line 58 of file MultipoleRep.cpp.
MultipoleRep() [2/3]
MultipoleRep::MultipoleRep ()
Definition at line 44 of file MultipoleRep.cpp.
Referenced by clone().
MultipoleRep() [3/3]
MultipoleRep::MultipoleRep (const MultipoleRep & multipole)
Definition at line 51 of file MultipoleRep.cpp.
~MultipoleRep()
MultipoleRep::~MultipoleRep () virtual
Definition at line 65 of file MultipoleRep.cpp.
Member Function Documentation
clone()
ElementBase * MultipoleRep::clone () const virtual
Return clone.
Implements ElementBase.
Definition at line 69 of file MultipoleRep.cpp.
References MultipoleRep().
getChannel()
Channel * MultipoleRep::getChannel (const std::string & aKey, bool create = false) virtual
Construct a read/write channel.
Reimplemented from ElementBase.
Definition at line 74 of file MultipoleRep.cpp.
References ElementBase::getChannel(), Multipole::getNormalComponent(), Multipole::getSkewComponent(), Hypervolume::n, Multipole::setNormalComponent(), and Multipole::setSkewComponent().
getField() [1/2]
BMultipoleField & MultipoleRep::getField () virtual
Get field.
Implements Multipole.
Definition at line 117 of file MultipoleRep.cpp.
References field.
getField() [2/2]
const BMultipoleField & MultipoleRep::getField () const virtual
Get field.
Implements Multipole.
Definition at line 122 of file MultipoleRep.cpp.
References field.
getGeometry() [1/2]
StraightGeometry & MultipoleRep::getGeometry () virtual
Get geometry.
Implements Multipole.
Definition at line 108 of file MultipoleRep.cpp.
References geometry.
getGeometry() [2/2]
const StraightGeometry & MultipoleRep::getGeometry () const virtual
Get geometry.
Implements Multipole.
Definition at line 112 of file MultipoleRep.cpp.
References geometry.
operator=()
void MultipoleRep::operator= (const MultipoleRep &) private
setField()
void MultipoleRep::setField (const BMultipoleField & field) virtual
Set mulitpole field.
Definition at line 127 of file MultipoleRep.cpp.
References field.
Referenced by OpalMultipole::update(), OpalSextupole::update(), OpalOctupole::update(), and OpalQuadrupole::update().
Member Data Documentation
field
BMultipoleField MultipoleRep::field private
Multipole field.
Definition at line 72 of file MultipoleRep.h.
Referenced by getField(), and setField().
geometry
StraightGeometry MultipoleRep::geometry private
Multipole geometry.
Definition at line 69 of file MultipoleRep.h.
Referenced by getGeometry().
The documentation for this class was generated from the following files:
src/Classic/BeamlineCore/MultipoleRep.h
src/Classic/BeamlineCore/MultipoleRep.cpp