OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Particle/ParticleAttrib.hpp File Reference
ParticleAttrib.hpp File Reference
#include "Particle/ParticleAttrib.h"
#include "Field/Field.h"
#include "Field/LField.h"
#include "Message/Message.h"
#include "Utility/IpplInfo.h"
#include "Utility/PAssert.h"
#include "Utility/IpplStats.h"
#include "AppTypes/AppTypeTraits.h"
Classes
struct PASortCompare< T >
struct PASortCompare< char >
struct PASortCompare< unsigned char >
struct PASortCompare< short >
struct PASortCompare< unsigned short >
struct PASortCompare< int >
struct PASortCompare< unsigned int >
struct PASortCompare< long >
struct PASortCompare< unsigned long >
struct PASortCompare< float >
struct PASortCompare< double >
Macros
#define PA_SORT_COMPARE_SCALAR(SCALAR)
Functions
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp >
void scatter (Field< FT, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &, FT val)
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp , class CacheData >
void scatter (Field< FT, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &, ParticleAttrib< CacheData > &cache, FT val)
template<class FT , unsigned Dim, class M , class C , class IntOp , class CacheData >
void scatter (Field< FT, Dim, M, C > &f, const IntOp &, const ParticleAttrib< CacheData > &cache, FT val)
Macro Definition Documentation
PA_SORT_COMPARE_SCALAR
#define PA_SORT_COMPARE_SCALAR (SCALAR)
Value:
template<>                                                              \
struct PASortCompare<SCALAR>                                            \
{                                                                       \
  static bool compare(const SCALAR &a, const SCALAR &b, bool ascending) \
  {                                                                     \
    return (ascending ? (a < b) : (a > b));                             \
  }                                                                     \
};
Definition at line 390 of file ParticleAttrib.hpp.
Function Documentation
scatter() [1/3]
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp > void scatter (Field< FT, Dim, M, C > & f, const ParticleAttrib< Vektor< PT, Dim > > & pp, const IntOp & , FT val)
Definition at line 562 of file ParticleAttrib.hpp.
References BareField< T, Dim >::accumGuardCells(), ParticleAttrib< T >::cbegin(), Field< T, Dim, M, C >::get_mesh(), INCIPPLSTAT, BareField< T, Dim >::setGuardCells(), ParticleAttribConstIterator< T >::size(), and BareField< T, Dim >::Uncompress().
Referenced by scatter().
scatter() [2/3]
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp , class CacheData > void scatter (Field< FT, Dim, M, C > & f, const ParticleAttrib< Vektor< PT, Dim > > & pp, const IntOp & , ParticleAttrib< CacheData > & cache, FT val)
Definition at line 587 of file ParticleAttrib.hpp.
References BareField< T, Dim >::accumGuardCells(), ParticleAttrib< T >::begin(), Field< T, Dim, M, C >::get_mesh(), INCIPPLSTAT, scatter(), BareField< T, Dim >::setGuardCells(), ParticleAttribIterator< T >::size(), and BareField< T, Dim >::Uncompress().
scatter() [3/3]
template<class FT , unsigned Dim, class M , class C , class IntOp , class CacheData > void scatter (Field< FT, Dim, M, C > & f, const IntOp & , const ParticleAttrib< CacheData > & cache, FT val)
Definition at line 613 of file ParticleAttrib.hpp.
References BareField< T, Dim >::accumGuardCells(), ParticleAttrib< T >::begin(), INCIPPLSTAT, scatter(), BareField< T, Dim >::setGuardCells(), ParticleAttrib< T >::size(), and BareField< T, Dim >::Uncompress().