OPAL (Object Oriented Parallel Accelerator Library): OpalFilter Class Reference
OpalFilter Class Reference
#include <OpalFilter.h>
Public Member Functions
OpalFilter ()
Exemplar constructor.
virtual ~OpalFilter ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual OpalFilter * clone (const std::string &name)
Make clone.
virtual void execute ()
Check the OpalFilter data.
virtual void update ()
Update the OpalFilter data.
void print (std::ostream &os) const
Print the object.
void initOpalFilter ()
void apply (std::vector< double > &histogram)
void calc_derivative (std::vector< double > &histogram, const double &hz)
Public Member Functions inherited from Definition
virtual ~Definition ()
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static OpalFilter * find (const std::string &name)
Find named FILTER.
Public Attributes
Filter * filter_m
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Private Types
enum FilterType : unsigned short { FilterType::SAVITZKYGOLAY, FilterType::FIXEDFFTLOWPASS, FilterType::RELATIVEFFTLOWPASS, FilterType::STENCIL }
Private Member Functions
OpalFilter (const OpalFilter &)
void operator= (const OpalFilter &)
OpalFilter (const std::string &name, OpalFilter *parent)
Additional Inherited Members
Protected Member Functions inherited from Definition
Definition (int size, const char *name, const char *help)
Constructor for exemplars.
Definition (const std::string &name, Definition *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 30 of file OpalFilter.h.
Member Enumeration Documentation
FilterType
enum OpalFilter::FilterType : unsigned short strong private
Enumerator
SAVITZKYGOLAY
FIXEDFFTLOWPASS
RELATIVEFFTLOWPASS
STENCIL
Definition at line 64 of file OpalFilter.h.
Constructor & Destructor Documentation
OpalFilter() [1/3]
OpalFilter::OpalFilter ()
Exemplar constructor.
Definition at line 55 of file OpalFilter.cpp.
References Object::builtin, clone(), OpalData::define(), Physics::e, OpalData::getInstance(), Object::itsAttr, Attributes::makePredefinedString(), Attributes::makeReal(), NLEFT_DEFAULT, NPOINTS_DEFAULT, NRIGHT_DEFAULT, POLYORDER_DEFAULT, Object::registerOwnership(), AttributeHandler::STATEMENT, Attrib::Distribution::TYPE, and update().
Referenced by clone().
~OpalFilter()
OpalFilter::~OpalFilter () virtual
Definition at line 102 of file OpalFilter.cpp.
References filter_m.
OpalFilter() [2/3]
OpalFilter::OpalFilter (const OpalFilter &) private
OpalFilter() [3/3]
OpalFilter::OpalFilter (const std::string & name, OpalFilter * parent) private
Definition at line 96 of file OpalFilter.cpp.
Member Function Documentation
apply()
void OpalFilter::apply (std::vector< double > & histogram) inline
Definition at line 79 of file OpalFilter.h.
References Filter::apply(), and filter_m.
calc_derivative()
void OpalFilter::calc_derivative (std::vector< double > & histogram, const double & hz) inline
Definition at line 84 of file OpalFilter.h.
References Filter::calc_derivative(), and filter_m.
canReplaceBy()
bool OpalFilter::canReplaceBy (Object * object) virtual
Test if replacement is allowed.
Reimplemented from Object.
Definition at line 108 of file OpalFilter.cpp.
clone()
OpalFilter * OpalFilter::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 114 of file OpalFilter.cpp.
References name, and OpalFilter().
Referenced by OpalFilter().
execute()
void OpalFilter::execute () virtual
Check the OpalFilter data.
Reimplemented from Object.
Definition at line 119 of file OpalFilter.cpp.
References update().
find()
OpalFilter * OpalFilter::find (const std::string & name) static
Find named FILTER.
Definition at line 124 of file OpalFilter.cpp.
References OpalData::find(), OpalData::getInstance(), and name.
Referenced by OpalWake::initWakefunction().
initOpalFilter()
void OpalFilter::initOpalFilter ()
Definition at line 141 of file OpalFilter.cpp.
References abs(), endl(), filter_m, FIXEDFFTLOWPASS, Attributes::getReal(), Attributes::getString(), gmsg, INFOMSG, Object::itsAttr, NLEFT_DEFAULT, NRIGHT_DEFAULT, RELATIVEFFTLOWPASS, SAVITZKYGOLAY, STENCIL, and Attrib::Distribution::TYPE.
Referenced by OpalWake::initWakefunction().
operator=()
void OpalFilter::operator= (const OpalFilter &) private
print()
void OpalFilter::print (std::ostream & msg) const virtual
Print the object.
Reimplemented from Object.
Definition at line 204 of file OpalFilter.cpp.
References endl(), Object::getOpalName(), Attributes::getReal(), Attributes::getString(), Object::itsAttr, and Attrib::Distribution::TYPE.
Referenced by operator<<().
update()
void OpalFilter::update () virtual
Update the OpalFilter data.
Reimplemented from Object.
Definition at line 135 of file OpalFilter.cpp.
References Object::getOpalName(), and Object::setOpalName().
Referenced by execute(), and OpalFilter().
Member Data Documentation
filter_m
Filter* OpalFilter::filter_m
Definition at line 61 of file OpalFilter.h.
Referenced by apply(), calc_derivative(), initOpalFilter(), OpalWake::initWakefunction(), and ~OpalFilter().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Utilities/OpalFilter.h
/psi/home/gsell/data/src/OPAL/src/src/Utilities/OpalFilter.cpp