OPAL (Object Oriented Parallel Accelerator Library): GridLBalWriter Class Reference
GridLBalWriter Class Reference
#include <GridLBalWriter.h>
Public Member Functions
GridLBalWriter (const std::string &fname, bool restart)
void write (PartBunchBase< double, 3 > *beam)
Public Member Functions inherited from SDDSWriter
SDDSWriter (const std::string &fname, bool restart)
virtual ~SDDSWriter ()
virtual void write (const PartBunchBase< double, 3 > *)
void rewindLines (size_t numberOfLines)
delete the last 'numberOfLines' lines of the file 'fileName'
void replaceVersionString ()
double getLastValue (const std::string &column)
bool exists () const
Private Member Functions
void fillHeader (const PartBunchBase< double, 3 > *beam)
Additional Inherited Members
Public Types inherited from SDDSWriter
typedef std::pair< std::string, std::string > desc_t
typedef std::tuple< std::string, std::string, std::string > param_t
typedef std::pair< std::string, size_t > data_t
typedef std::tuple< std::string, std::string, std::string, std::string > cols_t
Protected Member Functions inherited from SDDSWriter
void addDescription (const std::string &text, const std::string &content)
template<typename T >
void addParameter (const std::string &name, const std::string &type, const std::string &desc, const T &value)
void addDefaultParameters ()
void addColumn (const std::string &name, const std::string &type, const std::string &unit, const std::string &desc)
void addInfo (const std::string &mode, const size_t &no_row_counts)
void writeRow ()
void open ()
void close ()
void writeHeader ()
Write SDDS header.
template<typename T >
std::string toString (const T &val)
bool hasColumns () const
Protected Attributes inherited from SDDSWriter
std::string fname_m
std::ios_base::openmode mode_m
First write to the statistics output file.
SDDSColumnSet columns_m
Detailed Description
Definition at line 26 of file GridLBalWriter.h.
Constructor & Destructor Documentation
GridLBalWriter()
GridLBalWriter::GridLBalWriter (const std::string & fname, bool restart)
Definition at line 30 of file GridLBalWriter.cpp.
Member Function Documentation
fillHeader()
void GridLBalWriter::fillHeader (const PartBunchBase< double, 3 > * beam) private
Definition at line 35 of file GridLBalWriter.cpp.
References SDDSColumnSet::addColumn(), SDDSWriter::addDefaultParameters(), SDDSWriter::addDescription(), SDDSWriter::addInfo(), SDDSWriter::columns_m, OPALTimer::Timer::date(), AmrPartBunch::getAmrObject(), OpalData::getInputFn(), OpalData::getInstance(), IpplInfo::getNodes(), SDDSWriter::hasColumns(), SDDSWriter::mode_m, and OPALTimer::Timer::time().
Referenced by write().
write()
void GridLBalWriter::write (PartBunchBase< double, 3 > * beam)
Definition at line 91 of file GridLBalWriter.cpp.
References SDDSColumnSet::addColumnValue(), SDDSWriter::close(), SDDSWriter::columns_m, fillHeader(), AmrPartBunch::getAmrObject(), AmrObject::getGridStatistics(), IpplInfo::getNodes(), PartBunchBase< T, Dim >::getT(), IpplInfo::myNode(), SDDSWriter::open(), Units::s2ns, SDDSWriter::toString(), SDDSWriter::writeHeader(), and SDDSWriter::writeRow().
The documentation for this class was generated from the following files:
src/Structure/GridLBalWriter.h
src/Structure/GridLBalWriter.cpp