OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Field/AssignTags.h File Reference
AssignTags.h File Reference
#include "Index/NDIndex.h"
Classes
class BareField< T, Dim >
struct SameFieldID
struct IsCompressed
struct EvalFunctor_1
struct UnitEvalFunctor_1
struct EvalFunctor_2
struct UnitEvalFunctor_2
struct EvalFunctor_3
struct UnitEvalFunctor_3
struct BeginLField
struct NextLField
struct StepFunctor
struct RewindFunctor
struct HasUnitStride
struct FillGCIfNecessaryTag< D, T1 >
struct FGCINTag< D, T1 >
Functions
template<unsigned D, class T1 >
FillGCIfNecessaryTag< D, T1 > FillGCIfNecessary (const BareField< T1, D > &bf)
template<unsigned D, class T1 >
FillGCIfNecessaryTag< D, T1 > FillGCIfNecessary (FGCINTag< D, T1 >)
Function Documentation
FillGCIfNecessary() [1/2]
template<unsigned D, class T1 > FillGCIfNecessaryTag<D,T1> FillGCIfNecessary (const BareField< T1, D > & bf) inline
Definition at line 126 of file AssignTags.h.
Referenced by assign(), AssignActions< Dim, SIExprTag< true > >::fillgc(), and AssignActions< Dim, SIExprTag< false > >::fillgc().
FillGCIfNecessary() [2/2]
template<unsigned D, class T1 > FillGCIfNecessaryTag<D,T1> FillGCIfNecessary (FGCINTag< D, T1 >) inline
Definition at line 146 of file AssignTags.h.