OPAL (Object Oriented Parallel Accelerator Library): ParallelInterpolationFace< T, D, M, C > Class Template Reference
ParallelInterpolationFace< T, D, M, C > Class Template Reference
#include <BCond.h>
Public Types
typedef BCondBase< T, D, M, C > Base_t
Public Types inherited from InterpolationFace< T, D, M, C >
typedef BCondBase< T, D, M, C > BCondBaseTDMC
Public Member Functions
ParallelInterpolationFace (unsigned f, int i=Base_t::allComponents, int j=Base_t::allComponents)
virtual void apply (Field< T, D, M, C > &)
virtual Base_t * clone () const
virtual void write (std::ostream &out) const
Public Member Functions inherited from InterpolationFace< T, D, M, C >
InterpolationFace (unsigned f, int i=BCondBaseTDMC::allComponents, int j=BCondBaseTDMC::allComponents)
Public Member Functions inherited from BCondBase< T, D, M, C >
BCondBase (unsigned int face, int i=allComponents, int j=allComponents)
virtual ~BCondBase ()
int getComponent () const
unsigned int getFace () const
bool changesPhysicalCells () const
Public Member Functions inherited from RefCounted
RefCounted ()
Additional Inherited Members
Public Attributes inherited from RefCounted
int RefCount
Static Public Attributes inherited from BCondBase< T, D, M, C >
static int allComponents = -9999
Protected Attributes inherited from BCondBase< T, D, M, C >
int m_component
unsigned int m_face
bool m_changePhysical
Detailed Description
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering>
class ParallelInterpolationFace< T, D, M, C >
Definition at line 349 of file BCond.h.
Member Typedef Documentation
Base_t
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering> typedef BCondBase<T,D,M,C> ParallelInterpolationFace< T, D, M, C >::Base_t
Definition at line 359 of file BCond.h.
Constructor & Destructor Documentation
ParallelInterpolationFace()
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering> ParallelInterpolationFace< T, D, M, C >::ParallelInterpolationFace (unsigned f, int i = Base_t::allComponents, int j = Base_t::allComponents) inline
Definition at line 361 of file BCond.h.
Member Function Documentation
apply()
template<class T , unsigned D, class M , class C > void ParallelInterpolationFace< T, D, M, C >::apply (Field< T, D, M, C > & A) virtual
Reimplemented from InterpolationFace< T, D, M, C >.
Definition at line 2035 of file BCond.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), BC_PARALLEL_PERIODIC_TAG, BC_TAG_CYCLE, BareField< T, Dim >::begin_if(), CalcParallelInterpolationDomain(), IpplInfo::Comm, COMM_ANY_NODE, BareField< T, Dim >::end_if(), endl(), BareField< T, Dim >::getDomain(), BareField< T, Dim >::getGuardCellSizes(), BareField< T, Dim >::getLayout(), IpplInfo::getNodes(), INFORM_ALL_NODES, TagMaker::next_tag(), PAssert, Communicate::receive_block(), Communicate::send(), Message::size(), Attrib::Legacy::Distribution::T, and value_type().
clone()
template<class T, unsigned D, class M = UniformCartesian<D,double>, class C = typename M::DefaultCentering> virtual Base_t* ParallelInterpolationFace< T, D, M, C >::clone () const inline virtual
Reimplemented from InterpolationFace< T, D, M, C >.
Definition at line 373 of file BCond.h.
write()
template<class T , unsigned int D, class M , class C > void ParallelInterpolationFace< T, D, M, C >::write (std::ostream & out) const virtual
Reimplemented from InterpolationFace< T, D, M, C >.
Definition at line 127 of file BCond.hpp.
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BCond.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BCond.hpp