OPAL (Object Oriented Parallel Accelerator Library): DataSource Class Reference
DataSource Class Reference abstract
#include <DataSource.h>
Public Types
enum DsMode { INPUT, OUTPUT, BOTH, DEFAULT }
typedef std::vector< DataSourceObject * > container_t
Public Member Functions
DataSource ()
virtual ~DataSource ()
bool connected (DataConnect *=0) const
DataSourceObject * findDataSourceObject (DataConnect *) const
DataConnect * connect (const char *, DataConnect *=0, int=DataSource::DEFAULT)
bool connect (DataSourceObject *)
bool disconnect (DataConnect *=0)
bool updateConnection (DataConnect *=0)
void interact (DataConnect *=0)
void interact (const char *, DataConnect *=0)
Protected Member Functions
virtual DataSourceObject * createDataSourceObject (const char *, DataConnect *, int)=0
Private Attributes
container_t ConnectionList
Detailed Description
Definition at line 56 of file DataSource.h.
Member Typedef Documentation
container_t
typedef std::vector<DataSourceObject *> DataSource::container_t
Definition at line 67 of file DataSource.h.
Member Enumeration Documentation
DsMode
enum DataSource::DsMode
Enumerator
INPUT
OUTPUT
BOTH
DEFAULT
Definition at line 64 of file DataSource.h.
Constructor & Destructor Documentation
DataSource()
DataSource::DataSource ()
Definition at line 36 of file DataSource.cpp.
~DataSource()
DataSource::~DataSource () virtual
Definition at line 43 of file DataSource.cpp.
References disconnect().
Member Function Documentation
connect() [1/2]
DataConnect * DataSource::connect (const char * nm, DataConnect * dataconn = 0, int tm = DataSource::DEFAULT)
Definition at line 83 of file DataSource.cpp.
References connected(), DataConnectCreator::create(), createDataSourceObject(), DEFAULT, endl(), ERRORMSG, and DataConnect::getDefaultTransferMethod().
Referenced by DataConnect::connect().
connect() [2/2]
bool DataSource::connect (DataSourceObject * dso)
Definition at line 127 of file DataSource.cpp.
References DataConnect::checkin(), DataSourceObject::connected(), ConnectionList, DataSourceObject::getConnection(), and DataSourceObject::getSource().
connected()
bool DataSource::connected (DataConnect * dataconn = 0) const
Definition at line 69 of file DataSource.cpp.
References ConnectionList, and findDataSourceObject().
Referenced by connect().
createDataSourceObject()
virtual DataSourceObject* DataSource::createDataSourceObject (const char * , DataConnect * , int) protected pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, ParticleAttrib< ParticleOrigin >, IpplParticleBase< PLayout >, IpplParticleBase< T >, Field< T, Dim, M, C >, Field< double, 3, Mesh_t, Center_t >, and Field< Vector_t, 3, Mesh_t, Center_t >.
Referenced by connect().
disconnect()
bool DataSource::disconnect (DataConnect * dataconn = 0)
Definition at line 143 of file DataSource.cpp.
References a, DataConnect::checkout(), and ConnectionList.
Referenced by DataConnect::checkout(), and ~DataSource().
findDataSourceObject()
DataSourceObject * DataSource::findDataSourceObject (DataConnect * dc) const
Definition at line 55 of file DataSource.cpp.
References a, and ConnectionList.
Referenced by connected().
interact() [1/2]
void DataSource::interact (DataConnect * dataconn = 0)
Definition at line 195 of file DataSource.cpp.
References a, and ConnectionList.
interact() [2/2]
void DataSource::interact (const char * str, DataConnect * dataconn = 0)
Definition at line 208 of file DataSource.cpp.
References a, and ConnectionList.
updateConnection()
bool DataSource::updateConnection (DataConnect * dataconn = 0)
Definition at line 176 of file DataSource.cpp.
References a, and ConnectionList.
Member Data Documentation
ConnectionList
container_t DataSource::ConnectionList private
Definition at line 138 of file DataSource.h.
Referenced by connect(), connected(), disconnect(), findDataSourceObject(), interact(), and updateConnection().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/DataSource.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/DataSource.cpp