OPAL (Object Oriented Parallel Accelerator Library): Monitor Class Reference
Monitor Class Reference abstract
#include <Monitor.h>
Public Types
enum Plane { OFF, X, Y, XY }
Plane selection.
Public Member Functions
Monitor (const std::string &name)
Constructor with given name.
Monitor ()
Monitor (const Monitor &)
virtual ~Monitor ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to Monitor.
virtual StraightGeometry & getGeometry () override=0
Get geometry.
virtual const StraightGeometry & getGeometry () const override=0
Get geometry. Version for const object.
virtual Plane getPlane () const =0
Get plane on which monitor observes.
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void finalise () override
virtual bool bends () const override
virtual void goOnline (const double &kineticEnergy) override
virtual void goOffline () override
virtual ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
void setCollectionType (CollectionType type)
virtual int getRequiredNumberOfTimeSteps () const override
virtual bool isInside (const Vector_t &r) const override
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
virtual EMField & getField ()=0
Return field.
virtual const EMField & getField () const =0
Return field.
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static void writeStatistics ()
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Private Member Functions
void driftToCorrectPositionAndSave (const Vector_t &R, const Vector_t &P)
void operator= (const Monitor &)
Private Attributes
std::string filename_m
Plane plane_m
CollectionType type_m
unsigned int numPassages_m
std::unique_ptr< LossDataSink > lossDs_m
Static Private Attributes
static std::map< double, SetStatistics > statFileEntries_sm
static const double halfLength_s = 0.005
Additional Inherited Members
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 32 of file Monitor.h.
Member Enumeration Documentation
Plane
enum Monitor::Plane
Plane selection.
Enumerator
OFF
Monitor is off (inactive).
X
Monitor acts on x-plane.
Y
Monitor acts on y-plane.
XY
Monitor acts on both planes.
Definition at line 37 of file Monitor.h.
Constructor & Destructor Documentation
Monitor() [1/3]
Monitor::Monitor (const std::string & name) explicit
Constructor with given name.
Definition at line 51 of file Monitor.cpp.
References SPATIAL.
Monitor() [2/3]
Monitor::Monitor ()
Definition at line 37 of file Monitor.cpp.
Monitor() [3/3]
Monitor::Monitor (const Monitor & right)
Definition at line 42 of file Monitor.cpp.
~Monitor()
Monitor::~Monitor () virtual
Definition at line 60 of file Monitor.cpp.
Member Function Documentation
accept()
void Monitor::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to Monitor.
Implements ElementBase.
Definition at line 64 of file Monitor.cpp.
References BeamlineVisitor::visitMonitor().
apply()
bool Monitor::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 68 of file Monitor.cpp.
References Physics::c, PartBunchBase< T, Dim >::dt, Util::getBeta(), PartBunchBase< T, Dim >::ID, lossDs_m, PartBunchBase< T, Dim >::M, Component::online_m, PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::Q, Attrib::Distribution::R, PartBunchBase< T, Dim >::R, Component::RefPartBunch_m, SPATIAL, and type_m.
applyToReferenceParticle()
bool Monitor::applyToReferenceParticle (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Definition at line 106 of file Monitor.cpp.
References OpalData::APPEND, Physics::c, ElementBase::csTrafoGlobal2Local_m, driftToCorrectPositionAndSave(), euclidean_norm(), PartBunchBase< T, Dim >::get_sPos(), Util::getBeta(), PartBunchBase< T, Dim >::getdT(), PartBunchBase< T, Dim >::getGlobalTrackStep(), OpalData::getInstance(), OpalData::getOpenMode(), lossDs_m, numPassages_m, Attrib::Distribution::R, Component::RefPartBunch_m, CoordinateSystemTrafo::rotateFrom(), statFileEntries_sm, TEMPORAL, CoordinateSystemTrafo::transformFrom(), and type_m.
bends()
bool Monitor::bends () const override virtual
Implements Component.
Definition at line 199 of file Monitor.cpp.
driftToCorrectPositionAndSave()
void Monitor::driftToCorrectPositionAndSave (const Vector_t & R, const Vector_t & P) private
Definition at line 91 of file Monitor.cpp.
References Physics::c, Util::getBeta(), ElementBase::getCSTrafoGlobal2Local(), PartBunchBase< T, Dim >::getdT(), getQuaternion(), lossDs_m, Component::RefPartBunch_m, CoordinateSystemTrafo::rotateTo(), PartBunchBase< T, Dim >::toLabTrafo_m, CoordinateSystemTrafo::transformTo(), and ElementBase::update().
Referenced by applyToReferenceParticle().
finalise()
void Monitor::finalise () override virtual
Implements Component.
Definition at line 180 of file Monitor.cpp.
getDimensions()
void Monitor::getDimensions (double & zBegin, double & zEnd) const override virtual
Implements Component.
Definition at line 203 of file Monitor.cpp.
References halfLength_s.
getGeometry() [1/2]
virtual StraightGeometry& Monitor::getGeometry () override pure virtual
Get geometry.
Implements ElementBase.
Implemented in MonitorRep.
getGeometry() [2/2]
virtual const StraightGeometry& Monitor::getGeometry () const override pure virtual
Get geometry. Version for const object.
Implements ElementBase.
Implemented in MonitorRep.
getPlane()
virtual Plane Monitor::getPlane () const pure virtual
Get plane on which monitor observes.
Implemented in MonitorRep.
getRequiredNumberOfTimeSteps()
int Monitor::getRequiredNumberOfTimeSteps () const inline override virtual
Reimplemented from ElementBase.
Definition at line 119 of file Monitor.h.
getType()
ElementType Monitor::getType () const override virtual
Get element type std::string.
Reimplemented from Component.
Definition at line 209 of file Monitor.cpp.
References MONITOR.
goOffline()
void Monitor::goOffline () override virtual
Reimplemented from Component.
Definition at line 188 of file Monitor.cpp.
References lossDs_m, numPassages_m, statFileEntries_sm, TEMPORAL, and type_m.
goOnline()
void Monitor::goOnline (const double & kineticEnergy) override virtual
Reimplemented from Component.
Definition at line 184 of file Monitor.cpp.
References Component::online_m.
initialise()
void Monitor::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Implements Component.
Definition at line 149 of file Monitor.cpp.
References Options::asciidump, Communicate::barrier(), IpplInfo::Comm, filename_m, Hypervolume::fs, PartBunchBase< T, Dim >::get_sPos(), OpalData::getInstance(), ElementBase::getOutputFN(), PartBunchBase< T, Dim >::getTotalNum(), halfLength_s, lossDs_m, IpplInfo::myNode(), Component::RefPartBunch_m, type_m, and OpalData::WRITE.
isInside()
bool Monitor::isInside (const Vector_t & r) const inline override virtual
Reimplemented from ElementBase.
Definition at line 125 of file Monitor.h.
References abs(), ElementBase::getElementLength(), and ElementBase::isInsideTransverse().
operator=()
void Monitor::operator= (const Monitor &) private
setCollectionType()
void Monitor::setCollectionType (CollectionType type) inline
Definition at line 114 of file Monitor.h.
References type_m.
Referenced by OpalMonitor::update().
writeStatistics()
void Monitor::writeStatistics () static
Definition at line 213 of file Monitor.cpp.
References MonitorStatisticsWriter::addRow(), OpalData::getInputBasename(), OpalData::getInstance(), Util::rewindLinesSDDS(), and statFileEntries_sm.
Referenced by ParallelTTracker::execute().
Member Data Documentation
filename_m
std::string Monitor::filename_m private
The name of the outputfile
Definition at line 102 of file Monitor.h.
Referenced by initialise().
halfLength_s
const double Monitor::halfLength_s = 0.005 static private
Definition at line 110 of file Monitor.h.
Referenced by getDimensions(), and initialise().
lossDs_m
std::unique_ptr<LossDataSink> Monitor::lossDs_m private
Definition at line 107 of file Monitor.h.
Referenced by apply(), applyToReferenceParticle(), driftToCorrectPositionAndSave(), goOffline(), and initialise().
numPassages_m
unsigned int Monitor::numPassages_m private
Definition at line 105 of file Monitor.h.
Referenced by applyToReferenceParticle(), and goOffline().
plane_m
Plane Monitor::plane_m private
Definition at line 103 of file Monitor.h.
statFileEntries_sm
std::map< double, SetStatistics > Monitor::statFileEntries_sm static private
Definition at line 109 of file Monitor.h.
Referenced by applyToReferenceParticle(), goOffline(), and writeStatistics().
type_m
CollectionType Monitor::type_m private
Definition at line 104 of file Monitor.h.
Referenced by apply(), applyToReferenceParticle(), goOffline(), initialise(), and setCollectionType().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/AbsBeamline/Monitor.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/AbsBeamline/Monitor.cpp