OPAL (Object Oriented Parallel Accelerator Library): FieldPrint< T, Dim > Class Template Reference
FieldPrint< T, Dim > Class Template Reference
#include <FieldPrint.h>
Public Member Functions
FieldPrint (BareField< T, Dim > &f, unsigned parent=0, int indexWidth=3, int dataWidth=8, int dataPrecision=4, int carReturn=-1, bool scientific=false)
~FieldPrint ()
void print (NDIndex< Dim > &view)
void set_IndexWidth (unsigned in)
void set_DataWidth (unsigned in)
void set_DataPrecision (unsigned in)
void set_CarReturn (int in)
void set_Scientific (bool in)
Private Attributes
BareField< T, Dim > & MyField
unsigned Parent
unsigned IndexWidth
unsigned DataWidth
unsigned DataPrecision
int CarReturn
bool Scientific
Detailed Description
template<class T, unsigned Dim>
class FieldPrint< T, Dim >
Definition at line 21 of file FieldPrint.h.
Constructor & Destructor Documentation
FieldPrint()
template<class T , unsigned Dim> FieldPrint< T, Dim >::FieldPrint (BareField< T, Dim > & f, unsigned parent = 0, int indexWidth = 3, int dataWidth = 8, int dataPrecision = 4, int carReturn = -1, bool scientific = false) inline
Definition at line 26 of file FieldPrint.h.
~FieldPrint()
template<class T , unsigned Dim> FieldPrint< T, Dim >::~FieldPrint () inline
Definition at line 33 of file FieldPrint.h.
Member Function Documentation
print()
template<class T , unsigned Dim> void FieldPrint< T, Dim >::print (NDIndex< Dim > & view)
Definition at line 39 of file FieldPrint.hpp.
References LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), IpplInfo::Comm, COMM_ANY_NODE, NDIndex< Dim >::contains(), Dim, BareField< T, Dim >::end_if(), endl(), ERRORMSG, FP_GATHER_TAG, FP_TAG_CYCLE, NDIndex< Dim >::getMessage(), getMessage(), IpplInfo::getNodes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), TagMaker::next_tag(), PAssert, NDIndex< Dim >::putMessage(), putMessage(), Communicate::receive_block(), Communicate::send(), Inform::setf(), Attrib::Legacy::Distribution::T, NDIndex< Dim >::touches(), CompressedBrickIterator< T, Dim >::TryCompress(), and LField< T, Dim >::Uncompress().
set_CarReturn()
template<class T , unsigned Dim> void FieldPrint< T, Dim >::set_CarReturn (int in) inline
Definition at line 40 of file FieldPrint.h.
References FieldPrint< T, Dim >::CarReturn.
set_DataPrecision()
template<class T , unsigned Dim> void FieldPrint< T, Dim >::set_DataPrecision (unsigned in) inline
Definition at line 39 of file FieldPrint.h.
References FieldPrint< T, Dim >::DataPrecision.
set_DataWidth()
template<class T , unsigned Dim> void FieldPrint< T, Dim >::set_DataWidth (unsigned in) inline
Definition at line 38 of file FieldPrint.h.
References FieldPrint< T, Dim >::DataWidth.
set_IndexWidth()
template<class T , unsigned Dim> void FieldPrint< T, Dim >::set_IndexWidth (unsigned in) inline
Definition at line 37 of file FieldPrint.h.
References FieldPrint< T, Dim >::IndexWidth.
set_Scientific()
template<class T , unsigned Dim> void FieldPrint< T, Dim >::set_Scientific (bool in) inline
Definition at line 41 of file FieldPrint.h.
References FieldPrint< T, Dim >::Scientific.
Member Data Documentation
CarReturn
template<class T , unsigned Dim> int FieldPrint< T, Dim >::CarReturn private
Definition at line 52 of file FieldPrint.h.
Referenced by FieldPrint< T, Dim >::set_CarReturn().
DataPrecision
template<class T , unsigned Dim> unsigned FieldPrint< T, Dim >::DataPrecision private
Definition at line 51 of file FieldPrint.h.
Referenced by FieldPrint< T, Dim >::set_DataPrecision().
DataWidth
template<class T , unsigned Dim> unsigned FieldPrint< T, Dim >::DataWidth private
Definition at line 50 of file FieldPrint.h.
Referenced by FieldPrint< T, Dim >::set_DataWidth().
IndexWidth
template<class T , unsigned Dim> unsigned FieldPrint< T, Dim >::IndexWidth private
Definition at line 49 of file FieldPrint.h.
Referenced by FieldPrint< T, Dim >::set_IndexWidth().
MyField
template<class T , unsigned Dim> BareField<T,Dim>& FieldPrint< T, Dim >::MyField private
Definition at line 44 of file FieldPrint.h.
Parent
template<class T , unsigned Dim> unsigned FieldPrint< T, Dim >::Parent private
Definition at line 46 of file FieldPrint.h.
Scientific
template<class T , unsigned Dim> bool FieldPrint< T, Dim >::Scientific private
Definition at line 53 of file FieldPrint.h.
Referenced by FieldPrint< T, Dim >::set_Scientific().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/FieldPrint.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/FieldPrint.hpp