OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Index/IndexInlines.h File Reference
IndexInlines.h File Reference
#include "Utility/Unique.h"
#include "Utility/PAssert.h"
Macros
#define INDEX_PETE_DOUBLE_OPERATOR(OP, APP)
#define INDEX_PETE_FLOAT_OPERATOR(OP, APP)
#define INDEX_PETE_INT_OPERATOR(OP, APP)
Functions
Index operator+ (const Index &i, int off)
Index operator+ (int off, const Index &i)
Index operator- (const Index &i, int off)
Index operator- (int off, const Index &i)
Index operator- (const Index &i)
Index operator* (const Index &i, int m)
Index operator* (int m, const Index &i)
Index operator/ (const Index &i, int d)
PETE_TBTree< OpAdd, Index::PETE_Expr_t, PETE_Scalar< double > > operator+ (const Index &idx, double x)
PETE_TBTree< OpAdd, PETE_Scalar< double >, Index::PETE_Expr_t > operator+ (double x, const Index &idx)
PETE_TBTree< OpSubtract, Index::PETE_Expr_t, PETE_Scalar< double > > operator- (const Index &idx, double x)
PETE_TBTree< OpSubtract, PETE_Scalar< double >, Index::PETE_Expr_t > operator- (double x, const Index &idx)
PETE_TBTree< OpMultipply, Index::PETE_Expr_t, PETE_Scalar< double > > operator* (const Index &idx, double x)
PETE_TBTree< OpMultipply, PETE_Scalar< double >, Index::PETE_Expr_t > operator* (double x, const Index &idx)
PETE_TBTree< OpDivide, Index::PETE_Expr_t, PETE_Scalar< double > > operator/ (const Index &idx, double x)
PETE_TBTree< OpDivide, PETE_Scalar< double >, Index::PETE_Expr_t > operator/ (double x, const Index &idx)
PETE_TBTree< OpMod, Index::PETE_Expr_t, PETE_Scalar< double > > operator% (const Index &idx, double x)
PETE_TBTree< OpMod, PETE_Scalar< double >, Index::PETE_Expr_t > operator% (double x, const Index &idx)
PETE_TBTree< OpLT, Index::PETE_Expr_t, PETE_Scalar< double > > lt (const Index &idx, double x)
PETE_TBTree< OpLT, PETE_Scalar< double >, Index::PETE_Expr_t > lt (double x, const Index &idx)
PETE_TBTree< OpLE, Index::PETE_Expr_t, PETE_Scalar< double > > le (const Index &idx, double x)
PETE_TBTree< OpLE, PETE_Scalar< double >, Index::PETE_Expr_t > le (double x, const Index &idx)
PETE_TBTree< OpGT, Index::PETE_Expr_t, PETE_Scalar< double > > gt (const Index &idx, double x)
PETE_TBTree< OpGT, PETE_Scalar< double >, Index::PETE_Expr_t > gt (double x, const Index &idx)
PETE_TBTree< OpGE, Index::PETE_Expr_t, PETE_Scalar< double > > ge (const Index &idx, double x)
PETE_TBTree< OpGE, PETE_Scalar< double >, Index::PETE_Expr_t > ge (double x, const Index &idx)
PETE_TBTree< OpEQ, Index::PETE_Expr_t, PETE_Scalar< double > > eq (const Index &idx, double x)
PETE_TBTree< OpEQ, PETE_Scalar< double >, Index::PETE_Expr_t > eq (double x, const Index &idx)
PETE_TBTree< OpNE, Index::PETE_Expr_t, PETE_Scalar< double > > ne (const Index &idx, double x)
PETE_TBTree< OpNE, PETE_Scalar< double >, Index::PETE_Expr_t > ne (double x, const Index &idx)
PETE_TBTree< FnMax, Index::PETE_Expr_t, PETE_Scalar< double > > Max (const Index &idx, double x)
PETE_TBTree< FnMax, PETE_Scalar< double >, Index::PETE_Expr_t > Max (double x, const Index &idx)
PETE_TBTree< FnMin, Index::PETE_Expr_t, PETE_Scalar< double > > Min (const Index &idx, double x)
PETE_TBTree< FnMin, PETE_Scalar< double >, Index::PETE_Expr_t > Min (double x, const Index &idx)
PETE_TBTree< OpAdd, Index::PETE_Expr_t, PETE_Scalar< float > > operator+ (const Index &idx, float x)
PETE_TBTree< OpAdd, PETE_Scalar< float >, Index::PETE_Expr_t > operator+ (float x, const Index &idx)
PETE_TBTree< OpSubtract, Index::PETE_Expr_t, PETE_Scalar< float > > operator- (const Index &idx, float x)
PETE_TBTree< OpSubtract, PETE_Scalar< float >, Index::PETE_Expr_t > operator- (float x, const Index &idx)
PETE_TBTree< OpMultipply, Index::PETE_Expr_t, PETE_Scalar< float > > operator* (const Index &idx, float x)
PETE_TBTree< OpMultipply, PETE_Scalar< float >, Index::PETE_Expr_t > operator* (float x, const Index &idx)
PETE_TBTree< OpDivide, Index::PETE_Expr_t, PETE_Scalar< float > > operator/ (const Index &idx, float x)
PETE_TBTree< OpDivide, PETE_Scalar< float >, Index::PETE_Expr_t > operator/ (float x, const Index &idx)
PETE_TBTree< OpMod, Index::PETE_Expr_t, PETE_Scalar< float > > operator% (const Index &idx, float x)
PETE_TBTree< OpMod, PETE_Scalar< float >, Index::PETE_Expr_t > operator% (float x, const Index &idx)
PETE_TBTree< OpLT, Index::PETE_Expr_t, PETE_Scalar< float > > lt (const Index &idx, float x)
PETE_TBTree< OpLT, PETE_Scalar< float >, Index::PETE_Expr_t > lt (float x, const Index &idx)
PETE_TBTree< OpLE, Index::PETE_Expr_t, PETE_Scalar< float > > le (const Index &idx, float x)
PETE_TBTree< OpLE, PETE_Scalar< float >, Index::PETE_Expr_t > le (float x, const Index &idx)
PETE_TBTree< OpGT, Index::PETE_Expr_t, PETE_Scalar< float > > gt (const Index &idx, float x)
PETE_TBTree< OpGT, PETE_Scalar< float >, Index::PETE_Expr_t > gt (float x, const Index &idx)
PETE_TBTree< OpGE, Index::PETE_Expr_t, PETE_Scalar< float > > ge (const Index &idx, float x)
PETE_TBTree< OpGE, PETE_Scalar< float >, Index::PETE_Expr_t > ge (float x, const Index &idx)
PETE_TBTree< OpEQ, Index::PETE_Expr_t, PETE_Scalar< float > > eq (const Index &idx, float x)
PETE_TBTree< OpEQ, PETE_Scalar< float >, Index::PETE_Expr_t > eq (float x, const Index &idx)
PETE_TBTree< OpNE, Index::PETE_Expr_t, PETE_Scalar< float > > ne (const Index &idx, float x)
PETE_TBTree< OpNE, PETE_Scalar< float >, Index::PETE_Expr_t > ne (float x, const Index &idx)
PETE_TBTree< FnMax, Index::PETE_Expr_t, PETE_Scalar< float > > Max (const Index &idx, float x)
PETE_TBTree< FnMax, PETE_Scalar< float >, Index::PETE_Expr_t > Max (float x, const Index &idx)
PETE_TBTree< FnMin, Index::PETE_Expr_t, PETE_Scalar< float > > Min (const Index &idx, float x)
PETE_TBTree< FnMin, PETE_Scalar< float >, Index::PETE_Expr_t > Min (float x, const Index &idx)
PETE_TBTree< OpMod, Index::PETE_Expr_t, PETE_Scalar< int > > operator% (const Index &idx, int x)
PETE_TBTree< OpMod, PETE_Scalar< int >, Index::PETE_Expr_t > operator% (int x, const Index &idx)
PETE_TBTree< OpLT, Index::PETE_Expr_t, PETE_Scalar< int > > lt (const Index &idx, int x)
PETE_TBTree< OpLT, PETE_Scalar< int >, Index::PETE_Expr_t > lt (int x, const Index &idx)
PETE_TBTree< OpLE, Index::PETE_Expr_t, PETE_Scalar< int > > le (const Index &idx, int x)
PETE_TBTree< OpLE, PETE_Scalar< int >, Index::PETE_Expr_t > le (int x, const Index &idx)
PETE_TBTree< OpGT, Index::PETE_Expr_t, PETE_Scalar< int > > gt (const Index &idx, int x)
PETE_TBTree< OpGT, PETE_Scalar< int >, Index::PETE_Expr_t > gt (int x, const Index &idx)
PETE_TBTree< OpGE, Index::PETE_Expr_t, PETE_Scalar< int > > ge (const Index &idx, int x)
PETE_TBTree< OpGE, PETE_Scalar< int >, Index::PETE_Expr_t > ge (int x, const Index &idx)
PETE_TBTree< OpEQ, Index::PETE_Expr_t, PETE_Scalar< int > > eq (const Index &idx, int x)
PETE_TBTree< OpEQ, PETE_Scalar< int >, Index::PETE_Expr_t > eq (int x, const Index &idx)
PETE_TBTree< OpNE, Index::PETE_Expr_t, PETE_Scalar< int > > ne (const Index &idx, int x)
PETE_TBTree< OpNE, PETE_Scalar< int >, Index::PETE_Expr_t > ne (int x, const Index &idx)
PETE_TBTree< FnMax, Index::PETE_Expr_t, PETE_Scalar< int > > Max (const Index &idx, int x)
PETE_TBTree< FnMax, PETE_Scalar< int >, Index::PETE_Expr_t > Max (int x, const Index &idx)
PETE_TBTree< FnMin, Index::PETE_Expr_t, PETE_Scalar< int > > Min (const Index &idx, int x)
PETE_TBTree< FnMin, PETE_Scalar< int >, Index::PETE_Expr_t > Min (int x, const Index &idx)
Macro Definition Documentation
INDEX_PETE_DOUBLE_OPERATOR
#define INDEX_PETE_DOUBLE_OPERATOR (OP, APP)
Value:
\
inline                                                               \
PETE_TBTree< APP , Index::PETE_Expr_t , PETE_Scalar<double> >        \
OP (const Index& idx, double x)                                    \
{                                                                    \
  typedef                                                            \
    PETE_TBTree< APP , Index::PETE_Expr_t , PETE_Scalar<double> >    \
    Return_t;                                                        \
  return Return_t( idx.MakeExpression(), PETE_Scalar<double>(x) );   \
}                                                                    \
                                                                     \
inline                                                               \
PETE_TBTree< APP , PETE_Scalar<double> , Index::PETE_Expr_t >        \
OP (double x , const Index& idx)                                   \
{                                                                    \
  typedef                                                            \
    PETE_TBTree< APP , PETE_Scalar<double> , Index::PETE_Expr_t >    \
    Return_t;                                                        \
  return Return_t( PETE_Scalar<double>(x) , idx.MakeExpression());   \
}
Definition at line 324 of file IndexInlines.h.
INDEX_PETE_FLOAT_OPERATOR
#define INDEX_PETE_FLOAT_OPERATOR (OP, APP)
Value:
\
inline                                                               \
PETE_TBTree< APP , Index::PETE_Expr_t , PETE_Scalar<float> >         \
OP (const Index& idx, float x)                                     \
{                                                                    \
  typedef                                                            \
    PETE_TBTree< APP , Index::PETE_Expr_t , PETE_Scalar<float> >    \
    Return_t;                                                        \
  return Return_t( idx.MakeExpression(), PETE_Scalar<float>(x) );   \
}                                                                    \
                                                                     \
inline                                                               \
PETE_TBTree< APP , PETE_Scalar<float> , Index::PETE_Expr_t >         \
OP (float x , const Index& idx)                                    \
{                                                                    \
  typedef                                                            \
    PETE_TBTree< APP , PETE_Scalar<float> , Index::PETE_Expr_t >    \
    Return_t;                                                        \
  return Return_t( PETE_Scalar<float>(x) , idx.MakeExpression());   \
}
Definition at line 366 of file IndexInlines.h.
INDEX_PETE_INT_OPERATOR
#define INDEX_PETE_INT_OPERATOR (OP, APP)
Value:
\
inline                                                               \
PETE_TBTree< APP , Index::PETE_Expr_t , PETE_Scalar<int> >           \
OP (const Index& idx, int x)                                       \
{                                                                    \
  typedef                                                            \
    PETE_TBTree< APP , Index::PETE_Expr_t , PETE_Scalar<int> >       \
    Return_t;                                                        \
  return Return_t( idx.MakeExpression(), PETE_Scalar<int>(x) );      \
}                                                                    \
                                                                     \
inline                                                               \
PETE_TBTree< APP , PETE_Scalar<int> , Index::PETE_Expr_t >           \
OP (int x , const Index& idx)                                      \
{                                                                    \
  typedef                                                            \
    PETE_TBTree< APP , PETE_Scalar<int> , Index::PETE_Expr_t >       \
    Return_t;                                                        \
  return Return_t( PETE_Scalar<int>(x) , idx.MakeExpression());      \
}
Definition at line 408 of file IndexInlines.h.
Function Documentation
eq() [1/6]
PETE_TBTree< OpEQ , Index::PETE_Expr_t , PETE_Scalar<double> > eq (const Index & idx, double x) inline
Definition at line 356 of file IndexInlines.h.
eq() [2/6]
PETE_TBTree< OpEQ , PETE_Scalar<double> , Index::PETE_Expr_t > eq (double x, const Index & idx) inline
Definition at line 356 of file IndexInlines.h.
eq() [3/6]
PETE_TBTree< OpEQ , Index::PETE_Expr_t , PETE_Scalar<float> > eq (const Index & idx, float x) inline
Definition at line 398 of file IndexInlines.h.
eq() [4/6]
PETE_TBTree< OpEQ , PETE_Scalar<float> , Index::PETE_Expr_t > eq (float x, const Index & idx) inline
Definition at line 398 of file IndexInlines.h.
eq() [5/6]
PETE_TBTree< OpEQ , Index::PETE_Expr_t , PETE_Scalar<int> > eq (const Index & idx, int x) inline
Definition at line 436 of file IndexInlines.h.
eq() [6/6]
PETE_TBTree< OpEQ , PETE_Scalar<int> , Index::PETE_Expr_t > eq (int x, const Index & idx) inline
Definition at line 436 of file IndexInlines.h.
ge() [1/6]
PETE_TBTree< OpGE , PETE_Scalar<double> , Index::PETE_Expr_t > ge (double x, const Index & idx) inline
Definition at line 355 of file IndexInlines.h.
ge() [2/6]
PETE_TBTree< OpGE , Index::PETE_Expr_t , PETE_Scalar<double> > ge (const Index & idx, double x) inline
Definition at line 355 of file IndexInlines.h.
ge() [3/6]
PETE_TBTree< OpGE , Index::PETE_Expr_t , PETE_Scalar<float> > ge (const Index & idx, float x) inline
Definition at line 397 of file IndexInlines.h.
ge() [4/6]
PETE_TBTree< OpGE , PETE_Scalar<float> , Index::PETE_Expr_t > ge (float x, const Index & idx) inline
Definition at line 397 of file IndexInlines.h.
ge() [5/6]
PETE_TBTree< OpGE , PETE_Scalar<int> , Index::PETE_Expr_t > ge (int x, const Index & idx) inline
Definition at line 435 of file IndexInlines.h.
ge() [6/6]
PETE_TBTree< OpGE , Index::PETE_Expr_t , PETE_Scalar<int> > ge (const Index & idx, int x) inline
Definition at line 435 of file IndexInlines.h.
gt() [1/6]
PETE_TBTree< OpGT , Index::PETE_Expr_t , PETE_Scalar<double> > gt (const Index & idx, double x) inline
Definition at line 354 of file IndexInlines.h.
gt() [2/6]
PETE_TBTree< OpGT , PETE_Scalar<double> , Index::PETE_Expr_t > gt (double x, const Index & idx) inline
Definition at line 354 of file IndexInlines.h.
gt() [3/6]
PETE_TBTree< OpGT , Index::PETE_Expr_t , PETE_Scalar<float> > gt (const Index & idx, float x) inline
Definition at line 396 of file IndexInlines.h.
gt() [4/6]
PETE_TBTree< OpGT , PETE_Scalar<float> , Index::PETE_Expr_t > gt (float x, const Index & idx) inline
Definition at line 396 of file IndexInlines.h.
gt() [5/6]
PETE_TBTree< OpGT , Index::PETE_Expr_t , PETE_Scalar<int> > gt (const Index & idx, int x) inline
Definition at line 434 of file IndexInlines.h.
gt() [6/6]
PETE_TBTree< OpGT , PETE_Scalar<int> , Index::PETE_Expr_t > gt (int x, const Index & idx) inline
Definition at line 434 of file IndexInlines.h.
le() [1/6]
PETE_TBTree< OpLE , Index::PETE_Expr_t , PETE_Scalar<double> > le (const Index & idx, double x) inline
Definition at line 353 of file IndexInlines.h.
le() [2/6]
PETE_TBTree< OpLE , PETE_Scalar<double> , Index::PETE_Expr_t > le (double x, const Index & idx) inline
Definition at line 353 of file IndexInlines.h.
le() [3/6]
PETE_TBTree< OpLE , Index::PETE_Expr_t , PETE_Scalar<float> > le (const Index & idx, float x) inline
Definition at line 395 of file IndexInlines.h.
le() [4/6]
PETE_TBTree< OpLE , PETE_Scalar<float> , Index::PETE_Expr_t > le (float x, const Index & idx) inline
Definition at line 395 of file IndexInlines.h.
le() [5/6]
PETE_TBTree< OpLE , PETE_Scalar<int> , Index::PETE_Expr_t > le (int x, const Index & idx) inline
Definition at line 433 of file IndexInlines.h.
le() [6/6]
PETE_TBTree< OpLE , Index::PETE_Expr_t , PETE_Scalar<int> > le (const Index & idx, int x) inline
Definition at line 433 of file IndexInlines.h.
lt() [1/6]
PETE_TBTree< OpLT , Index::PETE_Expr_t , PETE_Scalar<double> > lt (const Index & idx, double x) inline
Definition at line 352 of file IndexInlines.h.
lt() [2/6]
PETE_TBTree< OpLT , PETE_Scalar<double> , Index::PETE_Expr_t > lt (double x, const Index & idx) inline
Definition at line 352 of file IndexInlines.h.
lt() [3/6]
PETE_TBTree< OpLT , Index::PETE_Expr_t , PETE_Scalar<float> > lt (const Index & idx, float x) inline
Definition at line 394 of file IndexInlines.h.
lt() [4/6]
PETE_TBTree< OpLT , PETE_Scalar<float> , Index::PETE_Expr_t > lt (float x, const Index & idx) inline
Definition at line 394 of file IndexInlines.h.
lt() [5/6]
PETE_TBTree< OpLT , PETE_Scalar<int> , Index::PETE_Expr_t > lt (int x, const Index & idx) inline
Definition at line 432 of file IndexInlines.h.
lt() [6/6]
PETE_TBTree< OpLT , Index::PETE_Expr_t , PETE_Scalar<int> > lt (const Index & idx, int x) inline
Definition at line 432 of file IndexInlines.h.
Max() [1/6]
PETE_TBTree< FnMax , PETE_Scalar<double> , Index::PETE_Expr_t > Max (double x, const Index & idx) inline
Definition at line 359 of file IndexInlines.h.
Max() [2/6]
PETE_TBTree< FnMax , Index::PETE_Expr_t , PETE_Scalar<double> > Max (const Index & idx, double x) inline
Definition at line 359 of file IndexInlines.h.
Max() [3/6]
PETE_TBTree< FnMax , Index::PETE_Expr_t , PETE_Scalar<float> > Max (const Index & idx, float x) inline
Definition at line 401 of file IndexInlines.h.
Max() [4/6]
PETE_TBTree< FnMax , PETE_Scalar<float> , Index::PETE_Expr_t > Max (float x, const Index & idx) inline
Definition at line 401 of file IndexInlines.h.
Max() [5/6]
PETE_TBTree< FnMax , Index::PETE_Expr_t , PETE_Scalar<int> > Max (const Index & idx, int x) inline
Definition at line 439 of file IndexInlines.h.
Max() [6/6]
PETE_TBTree< FnMax , PETE_Scalar<int> , Index::PETE_Expr_t > Max (int x, const Index & idx) inline
Definition at line 439 of file IndexInlines.h.
Min() [1/6]
PETE_TBTree< FnMin , Index::PETE_Expr_t , PETE_Scalar<double> > Min (const Index & idx, double x) inline
Definition at line 360 of file IndexInlines.h.
Min() [2/6]
PETE_TBTree< FnMin , PETE_Scalar<double> , Index::PETE_Expr_t > Min (double x, const Index & idx) inline
Definition at line 360 of file IndexInlines.h.
Min() [3/6]
PETE_TBTree< FnMin , Index::PETE_Expr_t , PETE_Scalar<float> > Min (const Index & idx, float x) inline
Definition at line 402 of file IndexInlines.h.
Min() [4/6]
PETE_TBTree< FnMin , PETE_Scalar<float> , Index::PETE_Expr_t > Min (float x, const Index & idx) inline
Definition at line 402 of file IndexInlines.h.
Min() [5/6]
PETE_TBTree< FnMin , Index::PETE_Expr_t , PETE_Scalar<int> > Min (const Index & idx, int x) inline
Definition at line 440 of file IndexInlines.h.
Min() [6/6]
PETE_TBTree< FnMin , PETE_Scalar<int> , Index::PETE_Expr_t > Min (int x, const Index & idx) inline
Definition at line 440 of file IndexInlines.h.
ne() [1/6]
PETE_TBTree< OpNE , Index::PETE_Expr_t , PETE_Scalar<double> > ne (const Index & idx, double x) inline
Definition at line 357 of file IndexInlines.h.
Referenced by PartBunchBase< double, 3 >::boundp_destroyT(), ParallelTTracker::computeExternalFields(), ScatteringPhysics::copyFromBunch(), and PartBunchBase< double, 3 >::destroyT().
ne() [2/6]
PETE_TBTree< OpNE , PETE_Scalar<double> , Index::PETE_Expr_t > ne (double x, const Index & idx) inline
Definition at line 357 of file IndexInlines.h.
ne() [3/6]
PETE_TBTree< OpNE , PETE_Scalar<float> , Index::PETE_Expr_t > ne (float x, const Index & idx) inline
Definition at line 399 of file IndexInlines.h.
ne() [4/6]
PETE_TBTree< OpNE , Index::PETE_Expr_t , PETE_Scalar<float> > ne (const Index & idx, float x) inline
Definition at line 399 of file IndexInlines.h.
ne() [5/6]
PETE_TBTree< OpNE , Index::PETE_Expr_t , PETE_Scalar<int> > ne (const Index & idx, int x) inline
Definition at line 437 of file IndexInlines.h.
ne() [6/6]
PETE_TBTree< OpNE , PETE_Scalar<int> , Index::PETE_Expr_t > ne (int x, const Index & idx) inline
Definition at line 437 of file IndexInlines.h.
operator%() [1/6]
PETE_TBTree< OpMod , Index::PETE_Expr_t , PETE_Scalar<double> > operator% (const Index & idx, double x) inline
Definition at line 350 of file IndexInlines.h.
operator%() [2/6]
PETE_TBTree< OpMod , PETE_Scalar<double> , Index::PETE_Expr_t > operator% (double x, const Index & idx) inline
Definition at line 350 of file IndexInlines.h.
operator%() [3/6]
PETE_TBTree< OpMod , Index::PETE_Expr_t , PETE_Scalar<float> > operator% (const Index & idx, float x) inline
Definition at line 392 of file IndexInlines.h.
operator%() [4/6]
PETE_TBTree< OpMod , PETE_Scalar<float> , Index::PETE_Expr_t > operator% (float x, const Index & idx) inline
Definition at line 392 of file IndexInlines.h.
operator%() [5/6]
PETE_TBTree< OpMod , PETE_Scalar<int> , Index::PETE_Expr_t > operator% (int x, const Index & idx) inline
Definition at line 430 of file IndexInlines.h.
operator%() [6/6]
PETE_TBTree< OpMod , Index::PETE_Expr_t , PETE_Scalar<int> > operator% (const Index & idx, int x) inline
Definition at line 430 of file IndexInlines.h.
operator*() [1/6]
Index operator* (const Index & i, int m) inline
Definition at line 187 of file IndexInlines.h.
operator*() [2/6]
Index operator* (int m, const Index & i) inline
Definition at line 192 of file IndexInlines.h.
operator*() [3/6]
PETE_TBTree< OpMultipply , Index::PETE_Expr_t , PETE_Scalar<double> > operator* (const Index & idx, double x) inline
Definition at line 348 of file IndexInlines.h.
operator*() [4/6]
PETE_TBTree< OpMultipply , PETE_Scalar<double> , Index::PETE_Expr_t > operator* (double x, const Index & idx) inline
Definition at line 348 of file IndexInlines.h.
operator*() [5/6]
PETE_TBTree< OpMultipply , PETE_Scalar<float> , Index::PETE_Expr_t > operator* (float x, const Index & idx) inline
Definition at line 390 of file IndexInlines.h.
operator*() [6/6]
PETE_TBTree< OpMultipply , Index::PETE_Expr_t , PETE_Scalar<float> > operator* (const Index & idx, float x) inline
Definition at line 390 of file IndexInlines.h.
operator+() [1/6]
Index operator+ (const Index & i, int off) inline
Definition at line 162 of file IndexInlines.h.
operator+() [2/6]
Index operator+ (int off, const Index & i) inline
Definition at line 167 of file IndexInlines.h.
operator+() [3/6]
PETE_TBTree< OpAdd , PETE_Scalar<double> , Index::PETE_Expr_t > operator+ (double x, const Index & idx) inline
Definition at line 346 of file IndexInlines.h.
operator+() [4/6]
PETE_TBTree< OpAdd , Index::PETE_Expr_t , PETE_Scalar<double> > operator+ (const Index & idx, double x) inline
Definition at line 346 of file IndexInlines.h.
operator+() [5/6]
PETE_TBTree< OpAdd , PETE_Scalar<float> , Index::PETE_Expr_t > operator+ (float x, const Index & idx) inline
Definition at line 388 of file IndexInlines.h.
operator+() [6/6]
PETE_TBTree< OpAdd , Index::PETE_Expr_t , PETE_Scalar<float> > operator+ (const Index & idx, float x) inline
Definition at line 388 of file IndexInlines.h.
operator-() [1/7]
Index operator- (const Index & i, int off) inline
Definition at line 172 of file IndexInlines.h.
operator-() [2/7]
Index operator- (int off, const Index & i) inline
Definition at line 177 of file IndexInlines.h.
operator-() [3/7]
Index operator- (const Index & i) inline
Definition at line 182 of file IndexInlines.h.
operator-() [4/7]
PETE_TBTree< OpSubtract , PETE_Scalar<double> , Index::PETE_Expr_t > operator- (double x, const Index & idx) inline
Definition at line 347 of file IndexInlines.h.
operator-() [5/7]
PETE_TBTree< OpSubtract , Index::PETE_Expr_t , PETE_Scalar<double> > operator- (const Index & idx, double x) inline
Definition at line 347 of file IndexInlines.h.
operator-() [6/7]
PETE_TBTree< OpSubtract , PETE_Scalar<float> , Index::PETE_Expr_t > operator- (float x, const Index & idx) inline
Definition at line 389 of file IndexInlines.h.
operator-() [7/7]
PETE_TBTree< OpSubtract , Index::PETE_Expr_t , PETE_Scalar<float> > operator- (const Index & idx, float x) inline
Definition at line 389 of file IndexInlines.h.
operator/() [1/5]
Index operator/ (const Index & i, int d) inline
Definition at line 197 of file IndexInlines.h.
References Index::First, and Index::Stride.
operator/() [2/5]
PETE_TBTree< OpDivide , PETE_Scalar<double> , Index::PETE_Expr_t > operator/ (double x, const Index & idx) inline
Definition at line 349 of file IndexInlines.h.
operator/() [3/5]
PETE_TBTree< OpDivide , Index::PETE_Expr_t , PETE_Scalar<double> > operator/ (const Index & idx, double x) inline
Definition at line 349 of file IndexInlines.h.
operator/() [4/5]
PETE_TBTree< OpDivide , PETE_Scalar<float> , Index::PETE_Expr_t > operator/ (float x, const Index & idx) inline
Definition at line 391 of file IndexInlines.h.
operator/() [5/5]
PETE_TBTree< OpDivide , Index::PETE_Expr_t , PETE_Scalar<float> > operator/ (const Index & idx, float x) inline
Definition at line 391 of file IndexInlines.h.