OPAL (Object Oriented Parallel Accelerator Library): OpalElement Class Reference
OpalElement Class Reference
#include <OpalElement.h>
Public Types
enum {
TYPE, APERT, LENGTH, ELEMEDGE,
WAKEF, PARTICLEMATTERINTERACTION, ORIGIN, ORIENTATION,
X, Y, Z, THETA,
PHI, PSI, DX, DY,
DZ, DTHETA, DPHI, DPSI,
OUTFN, COMMON
}
The common attributes for all elements.
Public Types inherited from Element
enum ReferenceType { IS_ENTRY, IS_CENTRE, IS_EXIT }
Reference for element positioning.
Public Member Functions
virtual ~OpalElement ()
virtual double getLength () const
Return element length.
const std::string getTypeName () const
Return the element's type name.
std::pair< ElementBase::ApertureType, std::vector< double > > getApert () const
const std::string getWakeF () const
Return the element's type name.
const std::string getParticleMatterInteraction () const
const std::string getWMaterial () const
const std::string getWakeGeom () const
std::vector< double > getWakeParam () const
const std::string getWakeConductivity () const
virtual void parse (Statement &)
Parse the element.
virtual void print (std::ostream &) const
Print the object.
virtual void update ()
Update the embedded CLASSIC element.
virtual void updateUnknown (ElementBase *)
Transmit the `‘unknown’' (not known to OPAL) attributes to CLASSIC.
Public Member Functions inherited from Element
virtual ~Element ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual double getEntrance (ReferenceType) const
Return arc length from origin to entrance (negative !).
virtual double getExit (ReferenceType) const
Return arc length from origin to exit (positive !).
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded CLASSIC element.
void setElement (ElementBase *)
Assign new CLASSIC element.
Public Member Functions inherited from Object
virtual ~Object ()
virtual Object * clone (const std::string &name)=0
Return a clone.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Member Functions
OpalElement (int size, const char *name, const char *help)
Exemplar constructor.
OpalElement (const std::string &name, OpalElement *parent)
Clone constructor.
void registerOwnership () const
Protected Member Functions inherited from Element
Element (int size, const char *name, const char *help)
Constructor for exemplars.
Element (const std::string &name, Element *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Static Protected Member Functions
static void printMultipoleStrength (std::ostream &os, int order, int &len, const std::string &sName, const std::string &tName, const Attribute &length, const Attribute &vNorm, const Attribute &vSkew)
Print multipole components in OPAL-8 format.
static void printAttribute (std::ostream &os, const std::string &name, const std::string &image, int &len)
Print an attribute with a OPAL-8 name (as an expression).
static void printAttribute (std::ostream &os, const std::string &name, double value, int &len)
Print an attribute with a OPAL-8 name (as a constant).
Private Member Functions
OpalElement ()
void operator= (const OpalElement &)
Private Attributes
int itsSize
Additional Inherited Members
Static Public Member Functions inherited from Element
static Element * find (const std::string &name)
Find named Element.
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 28 of file OpalElement.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
The common attributes for all elements.
Enumerator
TYPE
APERT
LENGTH
ELEMEDGE
WAKEF
PARTICLEMATTERINTERACTION
ORIGIN
ORIENTATION
X
Y
Z
THETA
PHI
PSI
DX
DY
DZ
DTHETA
DPHI
DPSI
OUTFN
COMMON
Definition at line 33 of file OpalElement.h.
Constructor & Destructor Documentation
~OpalElement()
OpalElement::~OpalElement () virtual
Definition at line 128 of file OpalElement.cpp.
OpalElement() [1/3]
OpalElement::OpalElement (int size, const char * name, const char * help) protected
Exemplar constructor.
Definition at line 40 of file OpalElement.cpp.
References AttributeHandler::addAttributeOwner(), APERT, COMMON, DPHI, DPSI, DTHETA, DX, DY, DZ, ELEMEDGE, AttributeHandler::ELEMENT, end(), Object::itsAttr, LENGTH, Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeRealArray(), Attributes::makeString(), ORIENTATION, ORIGIN, OUTFN, PARTICLEMATTERINTERACTION, PHI, PSI, THETA, TYPE, WAKEF, X, Y, and Z.
OpalElement() [2/3]
OpalElement::OpalElement (const std::string & name, OpalElement * parent) protected
Clone constructor.
Definition at line 123 of file OpalElement.cpp.
OpalElement() [3/3]
OpalElement::OpalElement () private
Member Function Documentation
getApert()
std::pair< ElementBase::ApertureType, std::vector< double > > OpalElement::getApert () const
Definition at line 132 of file OpalElement.cpp.
References APERT, ElementBase::CONIC_ELLIPTICAL, ElementBase::CONIC_RECTANGULAR, ElementBase::ELLIPTICAL, Attributes::getString(), Object::itsAttr, and ElementBase::RECTANGULAR.
Referenced by update().
getLength()
double OpalElement::getLength () const virtual
Return element length.
Implements Element.
Definition at line 285 of file OpalElement.cpp.
References Attributes::getReal(), Object::itsAttr, and LENGTH.
Referenced by OpalMultipole::update().
getParticleMatterInteraction()
const std::string OpalElement::getParticleMatterInteraction () const
Definition at line 303 of file OpalElement.cpp.
References Object::findAttribute(), and Attributes::getString().
getTypeName()
const std::string OpalElement::getTypeName () const
Return the element's type name.
Definition at line 290 of file OpalElement.cpp.
References Object::findAttribute(), and Attributes::getString().
Referenced by Selector::handleElement().
getWakeConductivity()
const std::string OpalElement::getWakeConductivity () const
getWakeF()
const std::string OpalElement::getWakeF () const
Return the element's type name.
Functions to get the wake field parametes
Definition at line 298 of file OpalElement.cpp.
References Object::findAttribute(), and Attributes::getString().
getWakeGeom()
const std::string OpalElement::getWakeGeom () const
getWakeParam()
std::vector<double> OpalElement::getWakeParam () const
getWMaterial()
const std::string OpalElement::getWMaterial () const
operator=()
void OpalElement::operator= (const OpalElement &) private
parse()
void OpalElement::parse (Statement & stat) virtual
Parse the element.
Reimplemented from Object.
Definition at line 308 of file OpalElement.cpp.
References Statement::delimiter(), Object::findAttribute(), name, Attribute::parse(), Attribute::parseComponent(), Expressions::parseDelimiter(), Expressions::parseRealConst(), Expressions::parseString(), and Attribute::setDefault().
print()
void OpalElement::print (std::ostream & os) const virtual
Print the object.
Reimplemented from Object.
Reimplemented in OpalRingDefinition, OpalMultipoleT, OpalMultipoleTCurvedConstRadius, OpalMultipoleTCurvedVarRadius, OpalOffset::OpalLocalCartesianOffset, OpalMultipoleTStraight, OpalOffset::OpalGlobalCartesianOffset, OpalOffset::OpalLocalCylindricalOffset, OpalOffset::OpalGlobalCylindricalOffset, OpalBend, OpalPolynomialTimeDependence, OpalSplineTimeDependence, OpalRBend3D, OpalQuadrupole, OpalOctupole, OpalMultipole, OpalSextupole, and OpalMarker.
Definition at line 343 of file OpalElement.cpp.
References endl(), Object::getOpalName(), and Object::getParent().
Referenced by OpalMarker::print(), OpalSextupole::print(), OpalMultipole::print(), OpalOctupole::print(), OpalQuadrupole::print(), OpalRBend3D::print(), OpalBend::print(), OpalSplineTimeDependence::print(), OpalPolynomialTimeDependence::print(), OpalOffset::OpalGlobalCylindricalOffset::print(), OpalOffset::OpalLocalCylindricalOffset::print(), OpalOffset::OpalGlobalCartesianOffset::print(), OpalMultipoleTStraight::print(), OpalMultipoleT::print(), OpalMultipoleTCurvedVarRadius::print(), OpalMultipoleTCurvedConstRadius::print(), OpalOffset::OpalLocalCartesianOffset::print(), and OpalRingDefinition::print().
printAttribute() [1/2]
void OpalElement::printAttribute (std::ostream & os, const std::string & name, const std::string & image, int & len) static protected
Print an attribute with a OPAL-8 name (as an expression).
Definition at line 568 of file OpalElement.cpp.
References name.
Referenced by printMultipoleStrength().
printAttribute() [2/2]
void OpalElement::printAttribute (std::ostream & os, const std::string & name, double value, int & len) static protected
Print an attribute with a OPAL-8 name (as a constant).
Definition at line 581 of file OpalElement.cpp.
References name.
printMultipoleStrength()
void OpalElement::printMultipoleStrength (std::ostream & os, int order, int & len, const std::string & sName, const std::string & tName, const Attribute & length, const Attribute & vNorm, const Attribute & vSkew) static protected
Print multipole components in OPAL-8 format.
Definition at line 358 of file OpalElement.cpp.
References atan2(), Attribute::getBase(), Attribute::getImage(), Attributes::getReal(), AttributeBase::isExpression(), Physics::pi, printAttribute(), and sqrt().
registerOwnership()
void OpalElement::registerOwnership () const protected
Definition at line 588 of file OpalElement.cpp.
References AttributeHandler::addAttributeOwner(), COMMON, AttributeHandler::ELEMENT, end(), Object::getOpalName(), Object::getParent(), Object::itsAttr, itsSize, and name.
Referenced by OpalCavity::OpalCavity(), OpalCCollimator::OpalCCollimator(), OpalCyclotron::OpalCyclotron(), OpalDegrader::OpalDegrader(), OpalDrift::OpalDrift(), OpalECollimator::OpalECollimator(), OpalFlexibleCollimator::OpalFlexibleCollimator(), OpalOffset::OpalGlobalCartesianOffset::OpalGlobalCartesianOffset(), OpalOffset::OpalGlobalCylindricalOffset::OpalGlobalCylindricalOffset(), OpalHKicker::OpalHKicker(), OpalKicker::OpalKicker(), OpalOffset::OpalLocalCartesianOffset::OpalLocalCartesianOffset(), OpalOffset::OpalLocalCylindricalOffset::OpalLocalCylindricalOffset(), OpalMonitor::OpalMonitor(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalMultipoleTCurvedConstRadius::OpalMultipoleTCurvedConstRadius(), OpalMultipoleTCurvedVarRadius::OpalMultipoleTCurvedVarRadius(), OpalMultipoleTStraight::OpalMultipoleTStraight(), OpalOctupole::OpalOctupole(), OpalPepperPot::OpalPepperPot(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRBend::OpalRBend(), OpalRBend3D::OpalRBend3D(), OpalRCollimator::OpalRCollimator(), OpalRingDefinition::OpalRingDefinition(), OpalSBend::OpalSBend(), OpalSBend3D::OpalSBend3D(), OpalScalingFFAMagnet::OpalScalingFFAMagnet(), OpalSeptum::OpalSeptum(), OpalSextupole::OpalSextupole(), OpalSlit::OpalSlit(), OpalSolenoid::OpalSolenoid(), OpalSource::OpalSource(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalStripper::OpalStripper(), OpalTravelingWave::OpalTravelingWave(), OpalUndulator::OpalUndulator(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVariableRFCavityFringeField::OpalVariableRFCavityFringeField(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), and OpalVKicker::OpalVKicker().
update()
void OpalElement::update () virtual
Update the embedded CLASSIC element.
Reimplemented from Object.
Reimplemented in OpalVariableRFCavityFringeField, OpalRingDefinition, OpalMultipoleT, OpalMultipoleTCurvedConstRadius, OpalMultipoleTCurvedVarRadius, OpalOffset::OpalLocalCartesianOffset, OpalVariableRFCavity, OpalCyclotron, OpalMultipoleTStraight, OpalOffset::OpalGlobalCartesianOffset, OpalScalingFFAMagnet, OpalOffset::OpalLocalCylindricalOffset, OpalCavity, OpalOffset::OpalGlobalCylindricalOffset, OpalPolynomialTimeDependence, OpalSplineTimeDependence, OpalKicker, OpalSBend3D, OpalStripper, OpalTravelingWave, OpalVKicker, OpalVacuum, OpalQuadrupole, OpalDrift, OpalOctupole, OpalUndulator, OpalCCollimator, OpalMultipole, OpalRBend3D, OpalSextupole, OpalPepperPot, OpalVerticalFFAMagnet, OpalProbe, OpalSeptum, OpalFlexibleCollimator, OpalSolenoid, OpalDegrader, OpalECollimator, OpalHKicker, OpalMarker, OpalRCollimator, OpalSlit, OpalSource, OpalRBend, OpalSBend, and OpalMonitor.
Definition at line 467 of file OpalElement.cpp.
References Quaternion::conjugate(), cos(), DPHI, DPSI, DTHETA, DX, DY, DZ, ELEMEDGE, ElementBase::fixPosition(), getApert(), Element::getElement(), Attributes::getReal(), Attributes::getRealArray(), Object::itsAttr, ORIENTATION, ORIGIN, PHI, PSI, ElementBase::setAperture(), ElementBase::setCSTrafoGlobal2Local(), ElementBase::setElementPosition(), ElementBase::setMisalignment(), ElementBase::setRotationAboutZ(), sin(), THETA, X, Y, and Z.
Referenced by OpalMonitor::update(), OpalRBend::update(), OpalSBend::update(), OpalSource::update(), OpalDegrader::update(), OpalECollimator::update(), OpalRCollimator::update(), OpalHKicker::update(), OpalSlit::update(), OpalSolenoid::update(), OpalFlexibleCollimator::update(), OpalSeptum::update(), OpalProbe::update(), OpalPepperPot::update(), OpalMultipole::update(), OpalRBend3D::update(), OpalCCollimator::update(), OpalSextupole::update(), OpalDrift::update(), OpalUndulator::update(), OpalOctupole::update(), OpalQuadrupole::update(), OpalVacuum::update(), OpalVKicker::update(), OpalTravelingWave::update(), OpalStripper::update(), OpalKicker::update(), OpalCavity::update(), OpalMultipoleTStraight::update(), OpalVariableRFCavity::update(), OpalMultipoleTCurvedVarRadius::update(), OpalMultipoleTCurvedConstRadius::update(), OpalMultipoleT::update(), and OpalVariableRFCavityFringeField::update().
updateUnknown()
void OpalElement::updateUnknown (ElementBase * base) virtual
Transmit the `‘unknown’' (not known to OPAL) attributes to CLASSIC.
Definition at line 559 of file OpalElement.cpp.
References Attribute::getName(), Attributes::getReal(), Object::itsAttr, itsSize, and ElementBase::setAttribute().
Referenced by OpalMonitor::update(), OpalRBend::update(), OpalSBend::update(), OpalSource::update(), OpalDegrader::update(), OpalHKicker::update(), OpalMarker::update(), OpalRCollimator::update(), OpalECollimator::update(), OpalSlit::update(), OpalFlexibleCollimator::update(), OpalSolenoid::update(), OpalSeptum::update(), OpalProbe::update(), OpalPepperPot::update(), OpalCCollimator::update(), OpalRBend3D::update(), OpalMultipole::update(), OpalSextupole::update(), OpalOctupole::update(), OpalUndulator::update(), OpalDrift::update(), OpalQuadrupole::update(), OpalVacuum::update(), OpalVKicker::update(), OpalTravelingWave::update(), OpalKicker::update(), OpalStripper::update(), OpalCavity::update(), OpalCyclotron::update(), OpalMultipoleTStraight::update(), OpalMultipoleT::update(), OpalMultipoleTCurvedVarRadius::update(), and OpalMultipoleTCurvedConstRadius::update().
Member Data Documentation
itsSize
int OpalElement::itsSize private
Definition at line 138 of file OpalElement.h.
Referenced by registerOwnership(), and updateUnknown().
The documentation for this class was generated from the following files:
src/Elements/OpalElement.h
src/Elements/OpalElement.cpp