OPAL (Object Oriented Parallel Accelerator Library): PutSingleItem< T, true, true > Struct Template Reference
PutSingleItem< T, true, true > Struct Template Reference
#include <Message.h>
Static Public Member Functions
static Message & put (Message &, T, T)
static Message & get (Message &, T)
static Message & put (Message &, const std::vector< size_t > &, T)
static Message & get_iter (Message &, T)
Detailed Description
template<class T>
struct PutSingleItem< T, true, true >
Definition at line 129 of file Message.h.
Member Function Documentation
get()
template<class T > Message & PutSingleItem< T, true, true >::get (Message & msg, T ptr) static
Definition at line 183 of file Message.hpp.
get_iter()
template<class T > Message & PutSingleItem< T, true, true >::get_iter (Message & m, T o) static
Definition at line 198 of file Message.hpp.
put() [1/2]
template<class T > Message & PutSingleItem< T, true, true >::put (Message & msg, T beg, T end) static
Definition at line 173 of file Message.hpp.
References end(), Message::putmsg(), and value_type().
put() [2/2]
template<class T > Message & PutSingleItem< T, true, true >::put (Message & m, const std::vector< size_t > & indices, T beg) static
Definition at line 190 of file Message.hpp.
The documentation for this struct was generated from the following files:
ippl/src/Message/Message.h
ippl/src/Message/Message.hpp