OPAL (Object Oriented Parallel Accelerator Library): IpplParticleBaseDataSource Class Reference
IpplParticleBaseDataSource Class Reference abstract
#include <PtclBaseDataSource.h>
Public Types
typedef std::vector< ParticleAttribDataSource * > AttribList_t
typedef std::vector< IpplParticleBaseDataSource * > BaseList_t
Public Member Functions
IpplParticleBaseDataSource (const char *, DataConnect *, int, DataSource *)
virtual ~IpplParticleBaseDataSource ()
AttribList_t::iterator begin_attrib ()
AttribList_t::iterator end_attrib ()
virtual bool connect_attrib (ParticleAttribDataSource *)
virtual bool disconnect_attrib (ParticleAttribDataSource *)
virtual bool has_attrib (ParticleAttribBase *)=0
Public Member Functions inherited from DataSourceObject
DataSourceObject (const char *nm, DataSource *ds, DataConnect *dc, int tm)
DataSourceObject ()
virtual ~DataSourceObject ()
bool connected () const
DataConnect * getConnection ()
DataSource * getSource ()
virtual bool update ()
virtual void interact (const char *=0)
Public Member Functions inherited from NamedObj
NamedObj (const char *nm=0)
virtual ~NamedObj ()
const char * name () const
const char * setName (const char *nm=0)
Static Public Member Functions
static BaseList_t::iterator begin_base ()
static BaseList_t::iterator end_base ()
static IpplParticleBaseDataSource * find_particle_base (ParticleAttribDataSource *, ParticleAttribBase *)
Protected Member Functions
void checkin ()
void checkout ()
Private Attributes
AttribList_t AttribList
Static Private Attributes
static BaseList_t BaseList
Additional Inherited Members
Protected Attributes inherited from DataSourceObject
DataConnect * Connection
DataSource * Source
int TransferMethod
Detailed Description
Definition at line 40 of file PtclBaseDataSource.h.
Member Typedef Documentation
AttribList_t
typedef std::vector<ParticleAttribDataSource *> IpplParticleBaseDataSource::AttribList_t
Definition at line 44 of file PtclBaseDataSource.h.
BaseList_t
typedef std::vector<IpplParticleBaseDataSource *> IpplParticleBaseDataSource::BaseList_t
Definition at line 45 of file PtclBaseDataSource.h.
Constructor & Destructor Documentation
IpplParticleBaseDataSource()
IpplParticleBaseDataSource::IpplParticleBaseDataSource (const char * nm, DataConnect * dc, int tm, DataSource * ds)
Definition at line 38 of file PtclBaseDataSource.cpp.
~IpplParticleBaseDataSource()
IpplParticleBaseDataSource::~IpplParticleBaseDataSource () virtual
Definition at line 47 of file PtclBaseDataSource.cpp.
References AttribList, checkout(), and disconnect_attrib().
Member Function Documentation
begin_attrib()
AttribList_t::iterator IpplParticleBaseDataSource::begin_attrib () inline
Definition at line 55 of file PtclBaseDataSource.h.
References AttribList.
begin_base()
static BaseList_t::iterator IpplParticleBaseDataSource::begin_base () inline static
Definition at line 59 of file PtclBaseDataSource.h.
References BaseList.
Referenced by checkin(), and find_particle_base().
checkin()
void IpplParticleBaseDataSource::checkin () protected
Definition at line 89 of file PtclBaseDataSource.cpp.
References BaseList, begin_base(), and end_base().
checkout()
void IpplParticleBaseDataSource::checkout () protected
Definition at line 106 of file PtclBaseDataSource.cpp.
References BaseList.
Referenced by ~IpplParticleBaseDataSource().
connect_attrib()
bool IpplParticleBaseDataSource::connect_attrib (ParticleAttribDataSource * pa) virtual
Definition at line 121 of file PtclBaseDataSource.cpp.
References AttribList.
disconnect_attrib()
bool IpplParticleBaseDataSource::disconnect_attrib (ParticleAttribDataSource * pa) virtual
Definition at line 130 of file PtclBaseDataSource.cpp.
References AttribList, and ParticleAttribDataSource::setDisconnected().
Referenced by ~IpplParticleBaseDataSource().
end_attrib()
AttribList_t::iterator IpplParticleBaseDataSource::end_attrib () inline
Definition at line 56 of file PtclBaseDataSource.h.
References AttribList.
end_base()
static BaseList_t::iterator IpplParticleBaseDataSource::end_base () inline static
Definition at line 60 of file PtclBaseDataSource.h.
References BaseList.
Referenced by checkin(), and find_particle_base().
find_particle_base()
IpplParticleBaseDataSource * IpplParticleBaseDataSource::find_particle_base (ParticleAttribDataSource * pa, ParticleAttribBase * pabase) static
Definition at line 67 of file PtclBaseDataSource.cpp.
References begin_base(), end_base(), DataSourceObject::getConnection(), and has_attrib().
Referenced by ParticleAttribDataSource::ParticleAttribDataSource().
has_attrib()
virtual bool IpplParticleBaseDataSource::has_attrib (ParticleAttribBase *) pure virtual
Referenced by find_particle_base().
Member Data Documentation
AttribList
AttribList_t IpplParticleBaseDataSource::AttribList private
Definition at line 101 of file PtclBaseDataSource.h.
Referenced by begin_attrib(), connect_attrib(), disconnect_attrib(), end_attrib(), and ~IpplParticleBaseDataSource().
BaseList
IpplParticleBaseDataSource::BaseList_t IpplParticleBaseDataSource::BaseList static private
Definition at line 104 of file PtclBaseDataSource.h.
Referenced by begin_base(), checkin(), checkout(), and end_base().
The documentation for this class was generated from the following files:
ippl/src/DataSource/PtclBaseDataSource.h
ippl/src/DataSource/PtclBaseDataSource.cpp