OPAL (Object Oriented Parallel Accelerator Library): IntTSCImpl< Dim > Class Template Reference
IntTSCImpl< Dim > Class Template Reference
#include <IntTSC.h>
Public Member Functions
IntTSCImpl ()
~IntTSCImpl ()
Public Member Functions inherited from Interpolator
Interpolator ()
~Interpolator ()
Static Public Member Functions
template<class FT , class M , class C , class PT >
static void scatter (const FT &, Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void scatter (const FT &, Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh, NDIndex< Dim > &ngp, int [Dim], Vektor< PT, Dim > &dpos)
template<class FT , class M , class C , class PT >
static void scatter (const FT &, Field< FT, Dim, M, C > &f, const NDIndex< Dim > &ngp, const int [Dim], const Vektor< PT, Dim > &)
template<class FT , class M , class C , class PT >
static void gather (FT &, const Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void gather (FT &, const Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh, NDIndex< Dim > &ngp, int [Dim], Vektor< PT, Dim > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &, const Field< FT, Dim, M, C > &f, const NDIndex< Dim > &ngp, const int [Dim], const Vektor< PT, Dim > &)
Additional Inherited Members
Static Protected Member Functions inherited from Interpolator
template<class T , unsigned Dim>
static CompressedBrickIterator< T, Dim > getFieldIter (const BareField< T, Dim > &f, const NDIndex< Dim > &pt)
Detailed Description
template<unsigned Dim>
class IntTSCImpl< Dim >
Definition at line 37 of file IntTSC.h.
Constructor & Destructor Documentation
IntTSCImpl()
template<unsigned Dim> IntTSCImpl< Dim >::IntTSCImpl () inline
Definition at line 41 of file IntTSC.h.
~IntTSCImpl()
template<unsigned Dim> IntTSCImpl< Dim >::~IntTSCImpl () inline
Definition at line 42 of file IntTSC.h.
Member Function Documentation
gather() [1/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntTSCImpl< Dim >::gather (FT & , const Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh) inline static
Definition at line 148 of file IntTSC.h.
References Dim, endl(), ERRORMSG, FindDelta(), FindNGP(), FindPos(), and Interpolator::getFieldIter().
Referenced by IntTSC::gather().
gather() [2/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntTSCImpl< Dim >::gather (FT & , const Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh, NDIndex< Dim > & ngp, int [Dim], Vektor< PT, Dim > & dpos) inline static
Definition at line 190 of file IntTSC.h.
References endl(), ERRORMSG, FindDelta(), FindNGP(), FindPos(), and Interpolator::getFieldIter().
gather() [3/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntTSCImpl< Dim >::gather (FT & , const Field< FT, Dim, M, C > & f, const NDIndex< Dim > & ngp, const int [Dim], const Vektor< PT, Dim > &) inline static
Definition at line 230 of file IntTSC.h.
References endl(), ERRORMSG, and Interpolator::getFieldIter().
scatter() [1/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntTSCImpl< Dim >::scatter (const FT & , Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh) inline static
Definition at line 49 of file IntTSC.h.
References endl(), ERRORMSG, FindDelta(), FindNGP(), FindPos(), and Interpolator::getFieldIter().
Referenced by IntTSC::scatter().
scatter() [2/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntTSCImpl< Dim >::scatter (const FT & , Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh, NDIndex< Dim > & ngp, int [Dim], Vektor< PT, Dim > & dpos) inline static
Definition at line 92 of file IntTSC.h.
References endl(), ERRORMSG, FindDelta(), FindNGP(), FindPos(), and Interpolator::getFieldIter().
scatter() [3/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntTSCImpl< Dim >::scatter (const FT & , Field< FT, Dim, M, C > & f, const NDIndex< Dim > & ngp, const int [Dim], const Vektor< PT, Dim > &) inline static
Definition at line 132 of file IntTSC.h.
References endl(), ERRORMSG, and Interpolator::getFieldIter().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/IntTSC.h