OPAL (Object Oriented Parallel Accelerator Library): SumErrSqRadialPeak Struct Reference
SumErrSqRadialPeak Struct Reference
#include <SumErrSqRadialPeak.h>
Public Member Functions
Expressions::Result_t operator() (client::function::arguments_t args)
Static Public Attributes
static const std::string name
Private Attributes
std::string meas_filename_
std::string sim_filename_
int begin_
int end_
boost::tuple< std::string, std::string, int, int > argument_types
Detailed Description
Definition at line 43 of file SumErrSqRadialPeak.h.
Member Function Documentation
operator()()
Expressions::Result_t SumErrSqRadialPeak::operator() (client::function::arguments_t args) inline
Definition at line 47 of file SumErrSqRadialPeak.h.
References begin_, Physics::e, end_, endl(), meas_filename_, sim_filename_, sqrt(), sum(), and OptPilotException::what().
Member Data Documentation
argument_types
boost::tuple<std::string, std::string, int, int> SumErrSqRadialPeak::argument_types private
Definition at line 103 of file SumErrSqRadialPeak.h.
begin_
int SumErrSqRadialPeak::begin_ private
Definition at line 99 of file SumErrSqRadialPeak.h.
Referenced by operator()().
end_
int SumErrSqRadialPeak::end_ private
Definition at line 100 of file SumErrSqRadialPeak.h.
Referenced by operator()().
meas_filename_
std::string SumErrSqRadialPeak::meas_filename_ private
Definition at line 97 of file SumErrSqRadialPeak.h.
Referenced by operator()().
name
const std::string SumErrSqRadialPeak::name static
Definition at line 45 of file SumErrSqRadialPeak.h.
sim_filename_
std::string SumErrSqRadialPeak::sim_filename_ private
Definition at line 98 of file SumErrSqRadialPeak.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/optimizer/Expression/SumErrSqRadialPeak.h