OPAL (Object Oriented Parallel Accelerator Library): DiscMeta Class Reference
DiscMeta Class Reference
#include <DiscMeta.h>
Public Types
typedef std::pair< int, std::string * > element_t
typedef vmap< int, element_t > container_t
typedef container_t::iterator iterator
typedef container_t::const_iterator const_iterator
typedef container_t::value_type value_type
Public Member Functions
DiscMeta (const char *fname)
~DiscMeta ()
const std::string & getFilename () const
unsigned int size () const
int getLineNumber (unsigned int) const
const std::string & getKeyword (unsigned int)
int getNumWords (unsigned int) const
std::string * getWords (unsigned int)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
void printDebug (Inform &)
Private Member Functions
bool read_meta_line (FILE *, std::string *&, int &)
Private Attributes
std::string MetaFile
container_t Lines
Detailed Description
Definition at line 35 of file DiscMeta.h.
Member Typedef Documentation
const_iterator
typedef container_t::const_iterator DiscMeta::const_iterator
Definition at line 42 of file DiscMeta.h.
container_t
typedef vmap<int, element_t> DiscMeta::container_t
Definition at line 40 of file DiscMeta.h.
element_t
typedef std::pair<int, std::string *> DiscMeta::element_t
Definition at line 39 of file DiscMeta.h.
iterator
typedef container_t::iterator DiscMeta::iterator
Definition at line 41 of file DiscMeta.h.
value_type
typedef container_t::value_type DiscMeta::value_type
Definition at line 43 of file DiscMeta.h.
Constructor & Destructor Documentation
DiscMeta()
DiscMeta::DiscMeta (const char * fname)
Definition at line 37 of file DiscMeta.cpp.
References IpplInfo::abort(), endl(), ERRORMSG, vmap< Key, T, Compare >::insert(), Lines, MetaFile, IpplInfo::myNode(), and read_meta_line().
~DiscMeta()
DiscMeta::~DiscMeta ()
Definition at line 76 of file DiscMeta.cpp.
References a, begin(), and end().
Member Function Documentation
begin() [1/2]
iterator DiscMeta::begin () inline
Definition at line 76 of file DiscMeta.h.
References vmap< Key, T, Compare >::begin(), and Lines.
Referenced by getLineNumber(), getNumWords(), getWords(), FieldLayout< Dim >::read(), DiscParticle::read_meta(), and ~DiscMeta().
begin() [2/2]
const_iterator DiscMeta::begin () const inline
Definition at line 78 of file DiscMeta.h.
References vmap< Key, T, Compare >::begin(), and Lines.
end() [1/2]
iterator DiscMeta::end () inline
Definition at line 77 of file DiscMeta.h.
References vmap< Key, T, Compare >::end(), and Lines.
Referenced by getLineNumber(), getNumWords(), getWords(), FieldLayout< Dim >::read(), and ~DiscMeta().
end() [2/2]
const_iterator DiscMeta::end () const inline
Definition at line 79 of file DiscMeta.h.
References vmap< Key, T, Compare >::end(), and Lines.
getFilename()
const std::string& DiscMeta::getFilename () const inline
Definition at line 58 of file DiscMeta.h.
References MetaFile.
getKeyword()
const std::string & DiscMeta::getKeyword (unsigned int n)
Definition at line 106 of file DiscMeta.cpp.
References getWords(), and Hypervolume::n.
Referenced by printDebug().
getLineNumber()
int DiscMeta::getLineNumber (unsigned int n) const
Definition at line 87 of file DiscMeta.cpp.
References begin(), end(), Hypervolume::n, PAssert, PAssert_LT, and size().
getNumWords()
int DiscMeta::getNumWords (unsigned int n) const
Definition at line 116 of file DiscMeta.cpp.
References begin(), end(), Hypervolume::n, PAssert, PAssert_LT, and size().
Referenced by printDebug().
getWords()
std::string * DiscMeta::getWords (unsigned int n)
Definition at line 135 of file DiscMeta.cpp.
References begin(), end(), Hypervolume::n, and PAssert.
Referenced by getKeyword(), and printDebug().
printDebug()
void DiscMeta::printDebug (Inform & msg)
Definition at line 186 of file DiscMeta.cpp.
References endl(), getKeyword(), getNumWords(), getWords(), MetaFile, and size().
read_meta_line()
bool DiscMeta::read_meta_line (FILE * f, std::string *& tokens, int & numtokens) private
Definition at line 154 of file DiscMeta.cpp.
References DiscConfig::dc_tokenize_string().
Referenced by DiscMeta().
size()
unsigned int DiscMeta::size (void) const inline
Definition at line 61 of file DiscMeta.h.
References Lines, and vmap< Key, T, Compare >::size().
Referenced by getLineNumber(), getNumWords(), and printDebug().
Member Data Documentation
Lines
container_t DiscMeta::Lines private
Definition at line 89 of file DiscMeta.h.
Referenced by begin(), DiscMeta(), end(), and size().
MetaFile
std::string DiscMeta::MetaFile private
Definition at line 86 of file DiscMeta.h.
Referenced by DiscMeta(), getFilename(), and printDebug().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/DiscMeta.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/DiscMeta.cpp