OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/MakeDataSource.hpp File Reference
MakeDataSource.hpp File Reference
#include "DataSource/MakeDataSource.h"
#include "DataSource/DataSourceObject.h"
#include "DataSource/DataConnect.h"
#include "DataSource/FileFieldDataSource.h"
#include "DataSource/FilePtclBaseDataSource.h"
#include "DataSource/FilePtclAttribDataSource.h"
Classes
class FileFieldDataSource< T, Dim, M, C >
class FileParticleAttribDataSource< T >
class FileIpplParticleBaseDataSource< T >
Functions
template<class T , unsigned Dim, class M , class C >
DataSourceObject * make_DataSourceObject (const char *nm, DataConnect *dc, int t, Field< T, Dim, M, C > &F)
template<class T >
DataSourceObject * make_DataSourceObject (const char *nm, DataConnect *dc, int t, ParticleAttrib< T > &P)
template<class PLayout >
DataSourceObject * make_DataSourceObject (const char *nm, DataConnect *dc, int t, IpplParticleBase< PLayout > &P)
Function Documentation
make_DataSourceObject() [1/3]
template<class T , unsigned Dim, class M , class C > DataSourceObject* make_DataSourceObject (const char * nm, DataConnect * dc, int t, Field< T, Dim, M, C > & F)
Definition at line 53 of file MakeDataSource.hpp.
References DataSourceObject::DataSourceObject(), and DataConnect::DSID().
Referenced by Field< Vector_t, 3, Mesh_t, Center_t >::createDataSourceObject(), IpplParticleBase< T >::createDataSourceObject(), and ParticleAttrib< ParticleOrigin >::createDataSourceObject().
make_DataSourceObject() [2/3]
template<class T > DataSourceObject* make_DataSourceObject (const char * nm, DataConnect * dc, int t, ParticleAttrib< T > & P)
Definition at line 78 of file MakeDataSource.hpp.
References DataSourceObject::DataSourceObject(), and DataConnect::DSID().
make_DataSourceObject() [3/3]
template<class PLayout > DataSourceObject* make_DataSourceObject (const char * nm, DataConnect * dc, int t, IpplParticleBase< PLayout > & P)
Definition at line 103 of file MakeDataSource.hpp.
References DataSourceObject::DataSourceObject(), and DataConnect::DSID().