OPAL (Object Oriented Parallel Accelerator Library): PartData Class Reference
PartData Class Reference
Particle reference data.
#include <PartData.h>
Public Member Functions
PartData (double charge, double mass, double momentum)
Constructor.
PartData ()
double getQ () const
The constant charge per particle.
double getM () const
The constant mass per particle.
double getP () const
The constant reference momentum per particle.
double getE () const
The constant reference Energy per particle.
double getBeta () const
The relativistic beta per particle.
double getGamma () const
The relativistic gamma per particle.
void setP (double p)
Set reference momentum.
void setE (double E)
Set reference energy.
void setBeta (double beta)
Set beta.
void setGamma (double gamma)
Set gamma.
void setM (double m)
Set reference mass expressed in eV/c^2.
void setQ (double q)
Set reference charge expressed in proton charges,.
Protected Attributes
double charge
double mass
double beta
double gamma
Detailed Description
Particle reference data.
Definition at line 35 of file PartData.h.
Constructor & Destructor Documentation
PartData() [1/2]
PartData::PartData (double charge, double mass, double momentum)
Constructor.
Definition at line 29 of file PartData.cpp.
References charge, mass, and setP().
PartData() [2/2]
PartData::PartData ()
Definition at line 36 of file PartData.cpp.
References beta, charge, gamma, and mass.
Member Function Documentation
getBeta()
double PartData::getBeta () const inline
The relativistic beta per particle.
Definition at line 124 of file PartData.h.
References beta.
Referenced by Tracker::applyDrift(), Tracker::applyTransform(), PartBunchBase< double, 3 >::getInitialBeta(), ParallelCyclotronTracker::visitCyclotron(), and ParallelCyclotronTracker::visitRing().
getE()
double PartData::getE () const inline
The constant reference Energy per particle.
Definition at line 119 of file PartData.h.
References gamma, and mass.
Referenced by PartBunchBase< double, 3 >::getE().
getGamma()
double PartData::getGamma () const inline
The relativistic gamma per particle.
Definition at line 129 of file PartData.h.
References gamma.
Referenced by ThickTracker::fillGaps_m(), PartBunchBase< double, 3 >::getInitialGamma(), ParallelCyclotronTracker::visitCyclotron(), ThickTracker::visitDrift(), ThickTracker::visitMultipole(), and ParallelCyclotronTracker::visitRing().
getM()
double PartData::getM () const inline
The constant mass per particle.
Definition at line 109 of file PartData.h.
References mass.
Referenced by Tracker::applyDrift(), Tracker::applyTransform(), PartBunchBase< double, 3 >::getM(), CavityAutophaser::getPhaseAtMaxEnergy(), CavityAutophaser::guessCavityPhase(), OrbitThreader::integrate(), BorisPusher::kick(), OrbitThreader::setDesignEnergy(), CavityAutophaser::track(), Beam::update(), and ThickTracker::visitSBend().
getP()
double PartData::getP () const inline
The constant reference momentum per particle.
Definition at line 114 of file PartData.h.
References beta, gamma, and mass.
Referenced by Tracker::applyDrift(), Tracker::applyTransform(), ParallelTTracker::execute(), PartBunchBase< double, 3 >::getP(), Beam::print(), and ThickTracker::visitMultipole().
getQ()
double PartData::getQ () const inline
The constant charge per particle.
Definition at line 104 of file PartData.h.
References charge.
Referenced by CavityAutophaser::getPhaseAtMaxEnergy(), PartBunchBase< double, 3 >::getQ(), CavityAutophaser::guessCavityPhase(), BorisPusher::kick(), CavityAutophaser::track(), ThickTracker::visitMultipole(), and ThickTracker::visitSBend().
setBeta()
void PartData::setBeta (double beta)
Set beta.
Definition at line 73 of file PartData.cpp.
References beta, gamma, and sqrt().
setE()
void PartData::setE (double E)
Set reference energy.
Definition at line 61 of file PartData.cpp.
References beta, gamma, mass, and sqrt().
Referenced by Beam::update().
setGamma()
void PartData::setGamma (double gamma)
Set gamma.
Definition at line 83 of file PartData.cpp.
References beta, gamma, and sqrt().
Referenced by Beam::update().
setM()
void PartData::setM (double m) inline
Set reference mass expressed in eV/c^2.
Definition at line 86 of file PartData.h.
References mass.
setP()
void PartData::setP (double p)
Set reference momentum.
Definition at line 44 of file PartData.cpp.
References beta, Physics::e, gamma, mass, and sqrt().
Referenced by PartData(), and Beam::update().
setQ()
void PartData::setQ (double q) inline
Set reference charge expressed in proton charges,.
Definition at line 89 of file PartData.h.
References charge.
Member Data Documentation
beta
double PartData::beta protected
Definition at line 96 of file PartData.h.
Referenced by ParallelTTracker::execute(), ParallelTTracker::findStartPosition(), getBeta(), getP(), PartData(), setBeta(), setE(), setGamma(), setP(), and ParallelTTracker::writePhaseSpace().
charge
double PartData::charge protected
Definition at line 94 of file PartData.h.
Referenced by getQ(), PartData(), and setQ().
gamma
double PartData::gamma protected
Definition at line 97 of file PartData.h.
Referenced by ParallelTTracker::findStartPosition(), getE(), getGamma(), getP(), PartData(), setBeta(), setE(), setGamma(), and setP().
mass
double PartData::mass protected
Definition at line 95 of file PartData.h.
Referenced by getE(), getM(), getP(), PartData(), setE(), setM(), and setP().
The documentation for this class was generated from the following files:
src/Classic/Algorithms/PartData.h
src/Classic/Algorithms/PartData.cpp