OPAL (Object Oriented Parallel Accelerator Library): src/Classic/FixedAlgebra/FLieGenerator.h File Reference
FLieGenerator.h File Reference
#include "Algebra/Array1D.h"
#include <complex>
#include "FixedAlgebra/FLieGenerator.hpp"
Classes
class FArray1D< T, N >
A templated representation for one-dimensional arrays.
class FMatrix< T, R, C >
A templated representation for matrices.
class FTps< T, N >
Truncated power series in N variables of type T.
class FLieGenerator< T, N >
A representation for a homogeneous polynomial, used as a Lie generator.
Functions
template<class T , int N>
FLieGenerator< T, N > operator+ (const FLieGenerator< T, N > &, const FLieGenerator< T, N > &)
Add.
template<class T , int N>
FLieGenerator< T, N > operator- (const FLieGenerator< T, N > &, const FLieGenerator< T, N > &)
Subtract.
template<class T , int N>
FLieGenerator< T, N > operator* (const FLieGenerator< T, N > &, const T &)
Multiply by scalar.
template<class T , int N>
FLieGenerator< T, N > operator* (const T &, const FLieGenerator< T, N > &)
Multiply by scalar.
template<class T , int N>
FLieGenerator< T, N > operator* (const FLieGenerator< T, N > &, const FLieGenerator< T, N > &)
Multiply by Lie generator.
template<class T , int N>
FLieGenerator< T, N > operator/ (const FLieGenerator< T, N > &, const T &)
Divide by scalar.
template<class T , int N>
FLieGenerator< T, N > real (const FLieGenerator< std::complex< T >, N > &)
Take real part of a complex generator.
template<class T , int N>
FLieGenerator< T, N > imag (const FLieGenerator< std::complex< T >, N > &)
Take imaginary part of a complex generator.
template<class T , int N>
FLieGenerator< std::complex< T >, N > toComplex (const FLieGenerator< T, N > &)
Convert real generator to complex.
template<class T , int N>
FLieGenerator< T, N > PoissonBracket (const FLieGenerator< T, N > &, const FLieGenerator< T, N > &)
Poisson bracket of two Lie generators.
template<class T , int N>
std::ostream & operator<< (std::ostream &, const FLieGenerator< T, N > &)
Output.
Function Documentation
imag()
template<class T , int N> FLieGenerator<T, N> imag (const FLieGenerator< std::complex< T >, N > &)
Take imaginary part of a complex generator.
Definition at line 437 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::end(), and Attrib::Legacy::Distribution::T.
Referenced by BMultipoleField::Bfield(), BSingleMultipoleField< order >::Bfield(), FDoubleEigen< N >::eigenVectors(), FDoubleEigen< N >::hqr2(), MapAnalyser::invertMatrix_m(), MapAnalyser::normalizeEigen_m(), sqrt(), and Werrf().
operator*() [1/3]
template<class T , int N> FLieGenerator<T, N> operator* (const FLieGenerator< T, N > & , const T &)
Multiply by scalar.
Definition at line 368 of file FLieGenerator.hpp.
operator*() [2/3]
template<class T , int N> FLieGenerator<T, N> operator* (const T & , const FLieGenerator< T, N > &)
Multiply by scalar.
Definition at line 376 of file FLieGenerator.hpp.
operator*() [3/3]
template<class T , int N> FLieGenerator<T, N> operator* (const FLieGenerator< T, N > & , const FLieGenerator< T, N > &)
Multiply by Lie generator.
Definition at line 384 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::getBottomIndex(), FLieGenerator< T, N >::getOrder(), FTpsData< N >::getProductArray(), FLieGenerator< T, N >::getTopIndex(), FLieGenerator< T, N >::isZero(), and Attrib::Legacy::Distribution::T.
operator+()
template<class T , int N> FLieGenerator<T, N> operator+ (const FLieGenerator< T, N > & , const FLieGenerator< T, N > &)
Add.
Definition at line 352 of file FLieGenerator.hpp.
operator-()
template<class T , int N> FLieGenerator<T, N> operator- (const FLieGenerator< T, N > & , const FLieGenerator< T, N > &)
Subtract.
Definition at line 360 of file FLieGenerator.hpp.
operator/()
template<class T , int N> FLieGenerator<T, N> operator/ (const FLieGenerator< T, N > & , const T &)
Divide by scalar.
Definition at line 414 of file FLieGenerator.hpp.
operator<<()
template<class T , int N> std::ostream& operator<< (std::ostream & , const FLieGenerator< T, N > &)
Output.
Definition at line 515 of file FLieGenerator.hpp.
References endl(), FTpsData< N >::getExponents(), FLieGenerator< T, N >::getOrder(), Inform::precision(), Inform::setf(), and Attrib::Legacy::Distribution::T.
PoissonBracket()
template<class T , int N> FLieGenerator<T, N> PoissonBracket (const FLieGenerator< T, N > & , const FLieGenerator< T, N > &)
Poisson bracket of two Lie generators.
Definition at line 466 of file FLieGenerator.hpp.
real()
template<class T , int N> FLieGenerator<T, N> real (const FLieGenerator< std::complex< T >, N > &)
Take real part of a complex generator.
Definition at line 422 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::end(), and Attrib::Legacy::Distribution::T.
Referenced by FixedFFTLowPassFilter::apply(), RelativeFFTLowPassFilter::apply(), BMultipoleField::Bfield(), BSingleMultipoleField< order >::Bfield(), RelativeFFTLowPassFilter::calc_derivative(), FixedFFTLowPassFilter::calc_derivative(), SpecializedGreensFunction< 3 >::calculate(), P3MPoissonSolver::calculateGridForces(), GreenWakeFunction::CalcWakeFFT(), DumpFields::checkInt(), DumpEMFields::checkInt(), GreenWakeFunction::compEnergy(), interpolation::complex(), Astra1D_fast::computeFourierCoefficients(), convlv(), erf(), Attributes::getStringArray(), matheval::detail::grammar< real_t, Iterator >::grammar(), FDoubleEigen< N >::hqr2(), MapAnalyser::invertMatrix_m(), GreenWakeFunction::Wake::operator()(), MapAnalyser::printPhaseShift_m(), Astra1DElectroStatic::readMap(), Astra1DMagnetoStatic::readMap(), Astra1DDynamic::readMap(), GreenWakeFunction::setWakeFromFile(), sqrt(), and Werrf().
toComplex()
template<class T , int N> FLieGenerator<std::complex<T>, N> toComplex (const FLieGenerator< T, N > &)
Convert real generator to complex.
Definition at line 452 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::begin(), FLieGenerator< T, N >::end(), FLieGenerator< T, N >::getOrder(), and Attrib::Legacy::Distribution::T.