OPAL (Object Oriented Parallel Accelerator Library): mslang::Rotation Struct Reference
mslang::Rotation Struct Reference
#include <Rotation.h>
Public Member Functions
virtual ~Rotation ()
virtual void print (int indentwidth)
void applyRotation (std::vector< std::shared_ptr< Base > > &bfuncs)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Public Member Functions inherited from mslang::Function
virtual ~Function ()
virtual void apply (std::vector< std::shared_ptr< Base >> &bfuncs)=0
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
Static Public Member Functions inherited from mslang::Function
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
Function * func_m
double angle_m
Additional Inherited Members
Static Public Attributes inherited from mslang::Function
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\((.*)"
Detailed Description
Definition at line 7 of file Rotation.h.
Constructor & Destructor Documentation
~Rotation()
virtual mslang::Rotation::~Rotation () inline virtual
Definition at line 11 of file Rotation.h.
References func_m.
Member Function Documentation
apply()
void mslang::Rotation::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Definition at line 33 of file Rotation.cpp.
References mslang::Function::apply(), applyRotation(), and func_m.
applyRotation()
void mslang::Rotation::applyRotation (std::vector< std::shared_ptr< Base > > & bfuncs)
Definition at line 17 of file Rotation.cpp.
References angle_m, cos(), and sin().
Referenced by apply().
parse_detail()
bool mslang::Rotation::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 38 of file Rotation.cpp.
References angle_m, Physics::e, end(), endl(), func_m, mslang::ArgumentExtractor::get(), mslang::ArgumentExtractor::getLengthConsumed(), mslang::Function::parse(), and mslang::parseMathExpression().
Referenced by mslang::Function::parse().
print()
void mslang::Rotation::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 8 of file Rotation.cpp.
References angle_m, endl(), func_m, and mslang::Function::print().
Member Data Documentation
angle_m
double mslang::Rotation::angle_m
Definition at line 9 of file Rotation.h.
Referenced by applyRotation(), parse_detail(), and print().
func_m
Function* mslang::Rotation::func_m
Definition at line 8 of file Rotation.h.
Referenced by apply(), parse_detail(), print(), and ~Rotation().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Rotation.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Rotation.cpp