OPAL (Object Oriented Parallel Accelerator Library): PyOpal::Field Namespace Reference
PyOpal::Field Namespace Reference
Functions
py::object get_field_value_cyclotron (double x, double y, double z, double t, ParallelCyclotronTracker *tracker)
py::object get_field_value (double x, double y, double z, double t)
Ring * getRing ()
std::string getElementName (int i)
boost::python::object getElementStartPosition (int i)
boost::python::object getElementEndPosition (int i)
boost::python::object getElementStartNormal (int i)
boost::python::object getElementEndNormal (int i)
size_t getNumberOfElements ()
BOOST_PYTHON_MODULE (field)
Variables
std::string field_docstring
std::string get_field_value_docstring
std::string element_name_docstring
std::string start_pos_docstring
std::string end_pos_docstring
std::string start_norm_docstring
std::string end_norm_docstring
std::string num_elements_docstring
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::Field::BOOST_PYTHON_MODULE (field)
Definition at line 170 of file PyField.cpp.
References element_name_docstring, field_docstring, get_field_value(), get_field_value_docstring, getElementEndNormal(), getElementEndPosition(), getElementName(), getElementStartNormal(), getElementStartPosition(), getNumberOfElements(), PyOpal::Globals::Initialise(), num_elements_docstring, and PyOpal::ExceptionTranslation::registerExceptions().
get_field_value()
py::object PyOpal::Field::get_field_value (double x, double y, double z, double t)
Definition at line 88 of file PyField.cpp.
References get_field_value_cyclotron(), and TrackRun::getTracker().
Referenced by BOOST_PYTHON_MODULE().
get_field_value_cyclotron()
py::object PyOpal::Field::get_field_value_cyclotron (double x, double y, double z, double t, ParallelCyclotronTracker * tracker)
Definition at line 70 of file PyField.cpp.
References ParallelCyclotronTracker::computeExternalFields_m(), and Attrib::Distribution::R.
Referenced by get_field_value().
getElementEndNormal()
boost::python::object PyOpal::Field::getElementEndNormal (int i)
Definition at line 155 of file PyField.cpp.
References getRing(), Ring::getSection(), and sec().
Referenced by BOOST_PYTHON_MODULE().
getElementEndPosition()
boost::python::object PyOpal::Field::getElementEndPosition (int i)
Definition at line 137 of file PyField.cpp.
References getRing(), Ring::getSection(), and sec().
Referenced by BOOST_PYTHON_MODULE().
getElementName()
std::string PyOpal::Field::getElementName (int i)
Definition at line 116 of file PyField.cpp.
References ElementBase::getName(), getRing(), Ring::getSection(), and sec().
Referenced by BOOST_PYTHON_MODULE().
getElementStartNormal()
boost::python::object PyOpal::Field::getElementStartNormal (int i)
Definition at line 146 of file PyField.cpp.
References getRing(), Ring::getSection(), and sec().
Referenced by BOOST_PYTHON_MODULE().
getElementStartPosition()
boost::python::object PyOpal::Field::getElementStartPosition (int i)
Definition at line 129 of file PyField.cpp.
References getRing(), Ring::getSection(), and sec().
Referenced by BOOST_PYTHON_MODULE().
getNumberOfElements()
size_t PyOpal::Field::getNumberOfElements ()
Definition at line 165 of file PyField.cpp.
References Ring::getNumberOfRingSections(), and getRing().
Referenced by BOOST_PYTHON_MODULE().
getRing()
Ring* PyOpal::Field::getRing ()
Definition at line 101 of file PyField.cpp.
References ParallelCyclotronTracker::getRing(), and TrackRun::getTracker().
Referenced by getElementEndNormal(), getElementEndPosition(), getElementName(), getElementStartNormal(), getElementStartPosition(), and getNumberOfElements().
Variable Documentation
element_name_docstring
std::string PyOpal::Field::element_name_docstring
Initial value:
=
"Return a string holding the name of the i^th element [m].\n\n"
Definition at line 114 of file PyField.cpp.
Referenced by BOOST_PYTHON_MODULE().
end_norm_docstring
std::string PyOpal::Field::end_norm_docstring
Initial value:
=
"Return a tuple holding the vector (x, y, z) normal to the face of the\n"
"element end, pointing towards the next element and having length 1.\n\n"
Definition at line 152 of file PyField.cpp.
end_pos_docstring
std::string PyOpal::Field::end_pos_docstring
Initial value:
=
"Return a tuple holding the end position of the element (x, y, z) [m].\n\n"
Definition at line 135 of file PyField.cpp.
field_docstring
std::string PyOpal::Field::field_docstring
Initial value:
=
  "field module enables user to get the field at a point"
Definition at line 30 of file PyField.cpp.
Referenced by BOOST_PYTHON_MODULE().
get_field_value_docstring
std::string PyOpal::Field::get_field_value_docstring
Definition at line 33 of file PyField.cpp.
Referenced by BOOST_PYTHON_MODULE().
num_elements_docstring
std::string PyOpal::Field::num_elements_docstring
Initial value:
=
"Return an integer corresponding to the number of elements stored in the Ring\n"
"If this is 0, check that the track has been executed - the element\n"
"placements are done during Track setup.\n\n"
Definition at line 161 of file PyField.cpp.
Referenced by BOOST_PYTHON_MODULE().
start_norm_docstring
std::string PyOpal::Field::start_norm_docstring
Initial value:
=
"Return a tuple holding the vector (x, y, z) normal to the face of the\n"
"element start, pointing towards the element and having length 1.\n\n"
Definition at line 143 of file PyField.cpp.
start_pos_docstring
std::string PyOpal::Field::start_pos_docstring
Initial value:
=
"Return a tuple holding the start position of the element (x, y, z) [m].\n\n"
Definition at line 126 of file PyField.cpp.