OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyTrackRunNS Namespace Reference
PyOpal::PyTrackRunNS Namespace Reference
Functions
void setRunName (PyOpalObjectNS::PyOpalObject< TrackRun > &, std::string name)
BOOST_PYTHON_MODULE (track_run)
Variables
std::string track_run_docstring = std::string()
const char * module_docstring = "build a tracking object"
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyTrackRunNS::BOOST_PYTHON_MODULE (track_run)
Definition at line 53 of file PyTrackRun.cpp.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::addExecute(), PyOpal::Globals::Initialise(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_class(), PyOpal::ExceptionTranslation::registerExceptions(), and setRunName().
setRunName()
void PyOpal::PyTrackRunNS::setRunName (PyOpalObjectNS::PyOpalObject< TrackRun > & , std::string name)
Definition at line 49 of file PyTrackRun.cpp.
References OpalData::getInstance(), name, and OpalData::storeInputFn().
Referenced by BOOST_PYTHON_MODULE().
Variable Documentation
module_docstring
const char* PyOpal::PyTrackRunNS::module_docstring = "build a tracking object"
Definition at line 47 of file PyTrackRun.cpp.
track_run_docstring
std::string PyOpal::PyTrackRunNS::track_run_docstring = std::string()
Definition at line 45 of file PyTrackRun.cpp.