OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Index/NDIndexInlines.h File Reference
NDIndexInlines.h File Reference
#include "Utility/PAssert.h"
Functions
template<unsigned D1, unsigned D2>
NDIndex< D1 > plugBase (const NDIndex< D1 > &i1, const NDIndex< D2 > &i2)
template<unsigned D1, unsigned D2>
bool isStencil (const NDIndex< D1 > &i1, const NDIndex< D2 > &i2)
Function Documentation
isStencil()
template<unsigned D1, unsigned D2> bool isStencil (const NDIndex< D1 > & i1, const NDIndex< D2 > & i2) inline
Definition at line 287 of file NDIndexInlines.h.
Referenced by IndexedBareFieldIterator< T, Dim >::FillGCIfNecessary().
plugBase()
template<unsigned D1, unsigned D2> NDIndex<D1> plugBase (const NDIndex< D1 > & i1, const NDIndex< D2 > & i2) inline
Definition at line 44 of file NDIndexInlines.h.
References NDIndex< Dim >::plugBase().
Referenced by NDIndex< Brackets >::plugBase().