OPAL (Object Oriented Parallel Accelerator Library): TrackRun Class Reference
TrackRun Class Reference
#include <TrackRun.h>
Public Member Functions
TrackRun ()
Exemplar constructor.
virtual ~TrackRun ()
virtual TrackRun * clone (const std::string &name)
Make clone.
virtual void execute ()
Execute the command.
Public Member Functions inherited from Action
virtual ~Action ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
TrackRun (const TrackRun &)
void operator= (const TrackRun &)
TrackRun (const std::string &name, TrackRun *parent)
void setupTTracker ()
void setupCyclotronTracker ()
void setupThickTracker ()
void setupFieldsolver ()
void initDataSink (const int &numBunch=1)
double setDistributionParallelT (Beam *beam)
Private Attributes
Tracker * itsTracker
Distribution * dist
std::vector< Distribution * > distrs_m
FieldSolver * fs
DataSink * ds
H5PartWrapper * phaseSpaceSink_m
OpalData * opal
Static Private Attributes
static const std::string defaultDistribution
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Action
Action (int size, const char *name, const char *help)
Constructor for exemplars.
Action (const std::string &name, Action *parent)
Constructor for cloning.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 35 of file TrackRun.h.
Constructor & Destructor Documentation
TrackRun() [1/3]
TrackRun::TrackRun ()
Exemplar constructor.
Definition at line 74 of file TrackRun.cpp.
References Attrib::Legacy::Distribution::DISTRIBUTION, OpalData::getInstance(), Object::itsAttr, Attributes::makeBool(), Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeString(), Attributes::makeStringArray(), opal, Object::registerOwnership(), and AttributeHandler::SUB_COMMAND.
Referenced by clone().
~TrackRun()
TrackRun::~TrackRun () virtual
Definition at line 131 of file TrackRun.cpp.
References phaseSpaceSink_m.
TrackRun() [2/3]
TrackRun::TrackRun (const TrackRun &) private
TrackRun() [3/3]
TrackRun::TrackRun (const std::string & name, TrackRun * parent) private
Definition at line 120 of file TrackRun.cpp.
References OpalData::getInstance(), and opal.
Member Function Documentation
clone()
TrackRun * TrackRun::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 137 of file TrackRun.cpp.
References name, and TrackRun().
execute()
void TrackRun::execute () virtual
Execute the command.
Reimplemented from Object.
Definition at line 142 of file TrackRun.cpp.
References begin(), OpalData::bunchIsAllocated(), Versions::changes, endl(), DefaultVisitor::execute(), Attributes::getReal(), Attributes::getString(), Object::itsAttr, itsTracker, opal, OPAL_VERSION_MAJOR, OPAL_VERSION_MINOR, OpalData::setRestartRun(), setupCyclotronTracker(), setupThickTracker(), setupTTracker(), and Options::version.
initDataSink()
void TrackRun::initDataSink (const int & numBunch = 1) private
Definition at line 619 of file TrackRun.cpp.
References DataSink::changeH5Wrapper(), ds, OpalData::getDataSink(), OpalData::hasDataSinkAllocated(), OpalData::inRestartRun(), opal, phaseSpaceSink_m, and OpalData::setDataSink().
Referenced by setupCyclotronTracker(), setupThickTracker(), and setupTTracker().
operator=()
void TrackRun::operator= (const TrackRun &) private
setDistributionParallelT()
double TrackRun::setDistributionParallelT (Beam * beam) private
Definition at line 635 of file TrackRun.cpp.
References Track::block, Track::bunch, defaultDistribution, dist, Attrib::Legacy::Distribution::DISTRIBUTION, distrs_m, Distribution::doRestartOpalT(), endl(), Distribution::find(), Beam::getChargePerParticle(), Distribution::getEmissionTimeShift(), Beam::getNumberOfParticles(), OpalData::getRestartStep(), Attributes::getStringArray(), Distribution::getTEmission(), gmsg, OpalData::hasBunchAllocated(), OpalData::inRestartRun(), Object::itsAttr, opal, phaseSpaceSink_m, PartBunchBase< T, Dim >::setDistribution(), OpalData::setGlobalPhaseShift(), and Distribution::setNumberOfDistributions().
Referenced by setupThickTracker(), and setupTTracker().
setupCyclotronTracker()
void TrackRun::setupCyclotronTracker () private
getFrequency() gets RF frequency [MHz], NOT isochronous revolution frequency of particle! getCurrent() gets beamcurrent [A]
Definition at line 426 of file TrackRun.cpp.
References abs(), Track::block, Track::bunch, PartBunchBase< T, Dim >::calcBeamParameters(), BoundaryGeometry::clone(), Distribution::createOpalCycl(), defaultDistribution, dist, Attrib::Legacy::Distribution::DISTRIBUTION, Distribution::doRestartOpalCycl(), ds, Track::dT, endl(), Physics::epsilon_0, BeamSequence::fetchLine(), Beam::find(), BoundaryGeometry::find(), Distribution::find(), fs, H5PartWrapperForPC::getAzimuth(), Beam::getCharge(), Beam::getChargePerParticle(), Beam::getCurrent(), H5PartWrapperForPC::getElevation(), Beam::getFrequency(), OpalData::getInputBasename(), OpalData::getInstance(), Beam::getMass(), Beam::getMassPerParticle(), H5PartWrapperForPC::getMeanMomentum(), Beam::getNumberOfParticles(), Beam::getParticleName(), H5PartWrapperForPC::getPreviousH5Local(), Attributes::getReal(), H5PartWrapperForPC::getReferencePr(), H5PartWrapperForPC::getReferencePt(), H5PartWrapperForPC::getReferencePz(), H5PartWrapperForPC::getReferenceR(), H5PartWrapperForPC::getReferenceT(), H5PartWrapperForPC::getReferenceZ(), OpalData::getRestartFileName(), OpalData::getRestartStep(), Attributes::getString(), Attributes::getStringArray(), gmsg, OpalData::hasBunchAllocated(), initDataSink(), OpalData::inRestartRun(), Object::itsAttr, itsTracker, Track::localTimeSteps, opal, phaseSpaceSink_m, Physics::pi, PartBunchBase< T, Dim >::POrigin, Options::psDumpFreq, Physics::q_e, Track::reference, REGULAR, PartBunchBase< T, Dim >::setCharge(), PartBunchBase< T, Dim >::setCouplingConstant(), PartBunchBase< T, Dim >::setdT(), OpalData::setGlobalGeometry(), OpalData::setInOPALCyclMode(), PartBunchBase< T, Dim >::setMass(), PartBunchBase< T, Dim >::setPType(), PartBunchBase< T, Dim >::setStepsPerTurn(), setupFieldsolver(), Options::statDumpFreq, Track::stepsPerTurn, Track::timeIntegrator, and Track::use.
Referenced by execute().
setupFieldsolver()
void TrackRun::setupFieldsolver () private
Definition at line 586 of file TrackRun.cpp.
References OpalData::addProblemCharacteristicValue(), Options::amr, Track::block, Track::bunch, Beam::find(), FieldSolver::find(), fs, OpalData::getInstance(), FieldSolver::getMT(), FieldSolver::getMX(), FieldSolver::getMY(), Beam::getNumberOfParticles(), Attributes::getString(), FieldSolver::getType(), FieldSolver::hasPeriodicZ(), FieldSolver::initCartesianFields(), OpalData::inRestartRun(), Object::itsAttr, opal, PartBunchBase< T, Dim >::setBCAllOpen(), and PartBunchBase< T, Dim >::setSolver().
Referenced by setupCyclotronTracker(), setupThickTracker(), and setupTTracker().
setupThickTracker()
void TrackRun::setupThickTracker () private
Definition at line 204 of file TrackRun.cpp.
References Track::block, Track::bunch, PartBunchBase< T, Dim >::calcBeamParameters(), BoundaryGeometry::clone(), Track::deltaTau, PartBunchBase< T, Dim >::deltaTau_m, dist, ds, Track::dT, Track::dtScInit, PartBunchBase< T, Dim >::dtScInit_m, endl(), Physics::epsilon_0, Beam::find(), BoundaryGeometry::find(), fs, OpalData::getInputBasename(), OpalData::getInstance(), OpalData::getRestartFileName(), OpalData::getRestartStep(), Attributes::getString(), gmsg, OpalData::hasBunchAllocated(), initDataSink(), OpalData::inRestartRun(), Object::itsAttr, itsTracker, level2(), Track::localTimeSteps, opal, phaseSpaceSink_m, Physics::pi, Options::psDumpFreq, Track::reference, PartBunchBase< T, Dim >::setCharge(), PartBunchBase< T, Dim >::setChargeZeroPart(), PartBunchBase< T, Dim >::setCouplingConstant(), setDistributionParallelT(), PartBunchBase< T, Dim >::setdT(), OpalData::setGlobalGeometry(), PartBunchBase< T, Dim >::setLocalTrackStep(), setupFieldsolver(), Options::statDumpFreq, Track::t0_m, Track::truncOrder, Track::zstart, and Track::zstop.
Referenced by execute().
setupTTracker()
void TrackRun::setupTTracker () private
Definition at line 307 of file TrackRun.cpp.
References Track::block, Track::bunch, PartBunchBase< T, Dim >::calcBeamParameters(), BoundaryGeometry::clone(), Track::deltaTau, PartBunchBase< T, Dim >::deltaTau_m, dist, ds, Track::dT, Track::dtScInit, PartBunchBase< T, Dim >::dtScInit_m, endl(), Physics::epsilon_0, Beam::find(), BoundaryGeometry::find(), fs, Attributes::getBool(), Beam::getFrequency(), OpalData::getInputBasename(), OpalData::getInstance(), Beam::getMassPerParticle(), Beam::getParticleName(), OpalData::getRestartFileName(), OpalData::getRestartStep(), Attributes::getString(), gmsg, OpalData::hasBunchAllocated(), OpalData::hasGlobalGeometry(), initDataSink(), OpalData::inRestartRun(), Object::itsAttr, itsTracker, level2(), Track::localTimeSteps, opal, phaseSpaceSink_m, Physics::pi, Options::psDumpFreq, Track::reference, PartBunchBase< T, Dim >::runTests(), PartBunchBase< T, Dim >::setBeamFrequency(), PartBunchBase< T, Dim >::setCharge(), PartBunchBase< T, Dim >::setChargeZeroPart(), PartBunchBase< T, Dim >::setCouplingConstant(), setDistributionParallelT(), PartBunchBase< T, Dim >::setdT(), OpalData::setGlobalGeometry(), OpalData::setInOPALTMode(), PartBunchBase< T, Dim >::setLocalTrackStep(), PartBunchBase< T, Dim >::setMass(), PartBunchBase< T, Dim >::setMassZeroPart(), PartBunchBase< T, Dim >::setPType(), setupFieldsolver(), Options::statDumpFreq, Track::t0_m, Track::zstart, and Track::zstop.
Referenced by execute().
Member Data Documentation
defaultDistribution
const std::string TrackRun::defaultDistribution static private
Definition at line 83 of file TrackRun.h.
Referenced by setDistributionParallelT(), and setupCyclotronTracker().
dist
Distribution* TrackRun::dist private
Definition at line 71 of file TrackRun.h.
Referenced by setDistributionParallelT(), setupCyclotronTracker(), setupThickTracker(), and setupTTracker().
distrs_m
std::vector<Distribution *> TrackRun::distrs_m private
Definition at line 73 of file TrackRun.h.
Referenced by setDistributionParallelT().
ds
DataSink* TrackRun::ds private
Definition at line 77 of file TrackRun.h.
Referenced by initDataSink(), setupCyclotronTracker(), setupThickTracker(), and setupTTracker().
fs
FieldSolver* TrackRun::fs private
Definition at line 75 of file TrackRun.h.
Referenced by setupCyclotronTracker(), setupFieldsolver(), setupThickTracker(), and setupTTracker().
itsTracker
Tracker* TrackRun::itsTracker private
Definition at line 69 of file TrackRun.h.
Referenced by execute(), setupCyclotronTracker(), setupThickTracker(), and setupTTracker().
opal
OpalData* TrackRun::opal private
Definition at line 81 of file TrackRun.h.
Referenced by execute(), initDataSink(), setDistributionParallelT(), setupCyclotronTracker(), setupFieldsolver(), setupThickTracker(), setupTTracker(), and TrackRun().
phaseSpaceSink_m
H5PartWrapper* TrackRun::phaseSpaceSink_m private
Definition at line 79 of file TrackRun.h.
Referenced by initDataSink(), setDistributionParallelT(), setupCyclotronTracker(), setupThickTracker(), setupTTracker(), and ~TrackRun().
The documentation for this class was generated from the following files:
src/Track/TrackRun.h
src/Track/TrackRun.cpp