OPAL (Object Oriented Parallel Accelerator Library): Matrix3D Class Reference
Matrix3D Class Reference
3-dimensional matrix.
#include <Matrix3D.h>
Public Member Functions
Matrix3D ()
Default constructor.
Matrix3D (const Vector3D &a, const Vector3D &b, const Vector3D &c)
Constructor.
Matrix3D (double x11, double x12, double x13, double x21, double x22, double x23, double x31, double x32, double x33)
Constructor.
bool operator== (const Matrix3D &) const
bool operator!= (const Matrix3D &) const
double & operator() (int i, int k)
Get element.
double operator() (int i, int k) const
Get element.
Matrix3D & operator+= (const Matrix3D &rhs)
Add and assign.
Matrix3D & operator-= (const Matrix3D &rhs)
Subtract and assign.
Matrix3D & operator*= (const Matrix3D &rhs)
Multiply and assign.
Matrix3D & operator*= (double factor)
Multiply and assign.
Matrix3D inverse () const
Inverse.
bool isIdentity () const
Test for identity.
Matrix3D transpose () const
Transpose.
Static Public Member Functions
static Matrix3D Identity ()
Make identity.
Private Attributes
double m [3][3]
Detailed Description
3-dimensional matrix.
Definition at line 33 of file Matrix3D.h.
Constructor & Destructor Documentation
Matrix3D() [1/3]
Matrix3D::Matrix3D () inline
Default constructor.
Definition at line 113 of file Matrix3D.h.
References m.
Referenced by Identity(), and inverse().
Matrix3D() [2/3]
Matrix3D::Matrix3D (const Vector3D & a, const Vector3D & b, const Vector3D & c)
Constructor.
Definition at line 28 of file Matrix3D.cpp.
References a, Physics::c, and m.
Matrix3D() [3/3]
Matrix3D::Matrix3D (double x11, double x12, double x13, double x21, double x22, double x23, double x31, double x32, double x33)
Constructor.
Definition at line 41 of file Matrix3D.cpp.
References m.
Member Function Documentation
Identity()
Matrix3D Matrix3D::Identity () static
Make identity.
Definition at line 117 of file Matrix3D.cpp.
References Matrix3D().
inverse()
Matrix3D Matrix3D::inverse () const
Inverse.
Definition at line 129 of file Matrix3D.cpp.
References det(), m, and Matrix3D().
isIdentity()
bool Matrix3D::isIdentity () const
Test for identity.
Definition at line 122 of file Matrix3D.cpp.
References m.
Referenced by Rotation3D::isIdentity().
operator!=()
bool Matrix3D::operator!= (const Matrix3D & rhs) const
Definition at line 63 of file Matrix3D.cpp.
References m.
operator()() [1/2]
double & Matrix3D::operator() (int i, int k) inline
Get element.
Definition at line 126 of file Matrix3D.h.
References m.
operator()() [2/2]
double Matrix3D::operator() (int i, int k) const inline
Get element.
Definition at line 130 of file Matrix3D.h.
References m.
operator*=() [1/2]
Matrix3D & Matrix3D::operator*= (const Matrix3D & rhs)
Multiply and assign.
Definition at line 98 of file Matrix3D.cpp.
operator*=() [2/2]
Matrix3D & Matrix3D::operator*= (double factor)
Multiply and assign.
Definition at line 103 of file Matrix3D.cpp.
References m.
operator+=()
Matrix3D & Matrix3D::operator+= (const Matrix3D & rhs)
Add and assign.
Definition at line 70 of file Matrix3D.cpp.
References m.
operator-=()
Matrix3D & Matrix3D::operator-= (const Matrix3D & rhs)
Subtract and assign.
Definition at line 84 of file Matrix3D.cpp.
References m.
operator==()
bool Matrix3D::operator== (const Matrix3D & rhs) const
Definition at line 56 of file Matrix3D.cpp.
References m.
transpose()
Matrix3D Matrix3D::transpose () const
Transpose.
Definition at line 149 of file Matrix3D.cpp.
References m.
Member Data Documentation
m
double Matrix3D::m[3][3] private
Definition at line 90 of file Matrix3D.h.
Referenced by inverse(), isIdentity(), Matrix3D(), operator!=(), operator()(), operator*=(), operator+=(), operator-=(), operator==(), and transpose().
The documentation for this class was generated from the following files:
src/Classic/BeamlineGeometry/Matrix3D.h
src/Classic/BeamlineGeometry/Matrix3D.cpp