OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Field/Field.hpp File Reference
Field.hpp File Reference
#include "Field/Field.h"
#include "Field/IndexedField.h"
#include "DataSource/MakeDataSource.h"
#include "Index/SIndex.h"
#include "SubField/SubField.h"
#include "Utility/IpplStats.h"
Functions
template<class T , unsigned Dim, class M , class C >
M * makeMesh (Field< T, Dim, M, C > &f)
Function Documentation
makeMesh()
template<class T , unsigned Dim, class M , class C > M* makeMesh (Field< T, Dim, M, C > & f) inline
Definition at line 54 of file Field.hpp.
References FieldLayout< Dim >::getDomain(), and BareField< T, Dim >::getLayout().
Referenced by Field< Vector_t, 3, Mesh_t, Center_t >::Field(), and Field< Vector_t, 3, Mesh_t, Center_t >::initialize().