OPAL (Object Oriented Parallel Accelerator Library): MultipoleT Class Reference
MultipoleT Class Reference
#include <MultipoleT.h>
Public Member Functions
MultipoleT (const std::string &name)
MultipoleT (const MultipoleT &right)
~MultipoleT ()
ElementBase * clone () const override
EMField & getField () override
const EMField & getField () const override
void getDimensions (double &zBegin, double &zEnd) const override
bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
void initialise (PartBunchBase< double, 3 > *, double &startField, double &endField) override
void initialise ()
void finalise () override
bool bends () const override
PlanarArcGeometry & getGeometry () override
const PlanarArcGeometry & getGeometry () const override
void accept (BeamlineVisitor &visitor) const override
double getDipoleConstant () const
void setDipoleConstant (double B0)
std::size_t getMaxOrder () const
void setMaxOrder (std::size_t maxOrder)
std::size_t getMaxXOrder () const
void setMaxXOrder (std::size_t maxXOrder)
std::size_t getTransMaxOrder () const
void setTransMaxOrder (std::size_t transMaxOrder)
void setTransProfile (std::size_t n, double Bn)
double getTransProfile (int n) const
std::vector< double > getTransProfile () const
bool setFringeField (double s0, double lambda_left, double lambda_right)
std::vector< double > getFringeLength () const
void setBendAngle (double angle)
double getBendAngle () const
void setEntranceAngle (double entranceAngle)
double getEntranceAngle () const
double getBendRadius () const
void setLength (double length)
double getLength () const
double getChordLength () const
void setAperture (double vertAp, double horizAp)
std::vector< double > getAperture () const
void setRotation (double rot)
double getRotation () const
void setVarRadius ()
bool getVarRadius () const
double getBoundingBoxLength () const
void setBoundingBoxLength (const double &boundingBoxLength)
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual ElementBase::ElementType getType () const
Get element type std::string.
virtual void setComponentType (std::string)
virtual std::string getComponentType () const
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
MultipoleT operator= (const MultipoleT &rhs)
Vector_t rotateFrame (const Vector_t &R)
Vector_t rotateFrameInverse (Vector_t &B)
Vector_t transformCoords (const Vector_t &R)
double getBx (const Vector_t &R)
double getBz (const Vector_t &R)
double getBs (const Vector_t &R)
double getFringeDeriv (int n, double s)
double getTransDeriv (std::size_t n, double x)
bool insideAperture (const Vector_t &R)
double getRadius (double s)
double getScaleFactor (double x, double s)
double getFnDerivX (std::size_t n, double x, double s)
double getFnDerivS (std::size_t n, double x, double s)
double getFn (std::size_t n, double x, double s)
Private Attributes
endfieldmodel::Tanh fringeField_l
endfieldmodel::Tanh fringeField_r
std::size_t maxOrder_m = 0
std::size_t maxOrderX_m = 0
std::vector< polynomial::RecursionRelationTwo > recursion_VarRadius_m
std::vector< polynomial::RecursionRelation > recursion_ConstRadius_m
std::size_t transMaxOrder_m = 0
std::vector< double > transProfile_m
PlanarArcGeometry planarArcGeometry_m
double length_m
double angle_m
double entranceAngle_m
double rotation_m
bool variableRadius_m
double boundingBoxLength_m
double verticalApert_m
double horizApert_m
BMultipoleField dummy
Additional Inherited Members
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
MultipoleT defines a straight or curved combined function magnet (up to arbitrary multipole component) with Fringe Fields
Class category: AbsBeamline
$Author: Titus Dascalu, Martin Duy Tat, Chris Rogers
The field is obtained from the scalar potential
\[ V = f_0(x,s) z + f_1 (x,s) \frac{z^3}{3!} + f_2 (x,s) \frac{z^5}{5!} + ... \]
(x,z,s) -> Frenet-Serret local coordinates along the magnet
z -> vertical component
assume mid-plane symmetry
set field on mid-plane -> \(B_z = f_0(x,s) = T(x) \cdot S(s) \)
T(x) -> transverse profile; this is a polynomial describing the field expansion on the mid-plane inside the magnet (not in the fringe field); 1st term is the dipole strength, 2nd term is the quadrupole gradient * x, etc.
-> when setting the magnet, one gives the multipole coefficients of this polynomial (i.e. dipole strength, quadrupole gradient, etc.)
----------— example --------------------------------------------—
Setting a combined function magnet with dipole, quadrupole and sextupole components:
\(T(x) = B_0 + B_1 \cdot x + B_2 \cdot x^2 \)
user gives \(B_0, B_1, B_2 \)
----------— example end ----------------------------------------—
S(s) -> fringe field
recursion -> \(f_n (x,s) = (-1)^n \cdot \sum_{i=0}^{n} C_n^i \cdot T^{(2i)} \cdot S^{(2n-2i)} \)
for curved magnets the above recursion is more complicated
\(C_n^i \) -> binomial coeff; \(T^{(n)} \) -> n-th derivative
Definition at line 89 of file MultipoleT.h.
Constructor & Destructor Documentation
MultipoleT() [1/2]
MultipoleT::MultipoleT (const std::string & name) explicit
Constructor
Parameters
name -> User-defined name
Definition at line 40 of file MultipoleT.cpp.
Referenced by clone().
MultipoleT() [2/2]
MultipoleT::MultipoleT (const MultipoleT & right)
Copy constructor
Definition at line 58 of file MultipoleT.cpp.
References Component::RefPartBunch_m.
~MultipoleT()
MultipoleT::~MultipoleT ()
Destructor
Definition at line 81 of file MultipoleT.cpp.
Member Function Documentation
accept()
void MultipoleT::accept (BeamlineVisitor & visitor) const override virtual
Accept a beamline visitor
Implements ElementBase.
Definition at line 403 of file MultipoleT.cpp.
References BeamlineVisitor::visitMultipoleT().
apply() [1/2]
bool MultipoleT::apply (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Calculate the field at some arbitrary position If particle is outside field map true is returned, otherwise false is returned
Parameters
R -> Position in the lab coordinate system of the multipole
P -> Not used
t -> Time at which the field is to be calculated
E -> Calculated electric field - always 0 (no E-field)
B -> Calculated magnetic field
Rotate coordinates around the central axis of the magnet
If magnet is not straight go to local Frenet-Serret coordinates
Transform B-field from local to lab coordinates
Reimplemented from Component.
Definition at line 94 of file MultipoleT.cpp.
References angle_m, cos(), cosh(), fringeField_l, fringeField_r, getBs(), getBx(), getBz(), endfieldmodel::Tanh::getLambda(), endfieldmodel::Tanh::getX0(), insideAperture(), length_m, log(), Attrib::Distribution::R, rotateFrame(), sin(), tanh(), transformCoords(), variableRadius_m, and X.
Referenced by apply().
apply() [2/2]
bool MultipoleT::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Calculate the field at the position of the ith particle
Parameters
i -> Index of the particle event override; field is calculated at this position If particle is outside field map true is returned, otherwise false is returned
t -> Time at which the field is to be calculated
E -> Calculated electric field - always 0 (no E-field)
B -> Calculated magnetic field
Reimplemented from Component.
Definition at line 135 of file MultipoleT.cpp.
References apply(), PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::R, and Component::RefPartBunch_m.
bends()
bool MultipoleT::bends () const override virtual
Return true if dipole component not zero
Implements Component.
Definition at line 544 of file MultipoleT.cpp.
References transProfile_m.
clone()
ElementBase * MultipoleT::clone () const override virtual
Inheritable copy constructor
Implements ElementBase.
Definition at line 84 of file MultipoleT.cpp.
References initialise(), and MultipoleT().
Referenced by ParallelCyclotronTracker::visitMultipoleT().
finalise()
void MultipoleT::finalise () override virtual
Finalise the MultipoleT - sets bunch to NULL
Implements Component.
Definition at line 90 of file MultipoleT.cpp.
References Component::RefPartBunch_m.
getAperture()
std::vector< double > MultipoleT::getAperture () const
Get the aperture dimensions Returns a vector of 2 doubles
Definition at line 415 of file MultipoleT.cpp.
References horizApert_m, and verticalApert_m.
getBendAngle()
double MultipoleT::getBendAngle () const inline
Get the bending angle of the magnet
Definition at line 418 of file MultipoleT.h.
References angle_m.
getBendRadius()
double MultipoleT::getBendRadius () const
Get the bending radius
Not used, when needed radius is found from length_m / angle_m
getBoundingBoxLength()
double MultipoleT::getBoundingBoxLength () const inline
Get distance between centre of magnet and entrance
Definition at line 430 of file MultipoleT.h.
References boundingBoxLength_m.
getBs()
double MultipoleT::getBs (const Vector_t & R) private
Returns the component of the field along the central axis 1/h_s * sum_n z^(2n+1) / (2n+1)! f_n
Definition at line 319 of file MultipoleT.cpp.
References angle_m, Physics::e, getFnDerivS(), getFringeDeriv(), getScaleFactor(), getTransDeriv(), maxOrder_m, Hypervolume::n, Attrib::Distribution::R, and variableRadius_m.
Referenced by apply().
getBx()
double MultipoleT::getBx (const Vector_t & R) private
Get field component methods
Returns the radial component of the field sum_n z^(2n+1) / (2n+1)! * f_n
Definition at line 286 of file MultipoleT.cpp.
References angle_m, Physics::e, getFnDerivX(), getFringeDeriv(), getTransDeriv(), maxOrder_m, Hypervolume::n, Attrib::Distribution::R, and variableRadius_m.
Referenced by apply().
getBz()
double MultipoleT::getBz (const Vector_t & R) private
Returns the vertical field component sum_n f_n * z^(2n) / (2n)!
Definition at line 255 of file MultipoleT.cpp.
References angle_m, Physics::e, getFn(), getFringeDeriv(), getTransDeriv(), maxOrder_m, Hypervolume::n, Attrib::Distribution::R, and variableRadius_m.
Referenced by apply().
getChordLength()
double MultipoleT::getChordLength () const
Not used
getDimensions()
void MultipoleT::getDimensions (double & zBegin, double & zEnd) const override virtual
Not implemented
Implements Component.
Definition at line 407 of file MultipoleT.cpp.
getDipoleConstant()
double MultipoleT::getDipoleConstant () const inline
Get the dipole constant B_0
Definition at line 379 of file MultipoleT.h.
References transProfile_m.
getEntranceAngle()
double MultipoleT::getEntranceAngle () const inline
Get the entrance angle
Definition at line 367 of file MultipoleT.h.
References entranceAngle_m.
getField() [1/2]
EMField & MultipoleT::getField () override virtual
Return a dummy field value
Implements Component.
Definition at line 556 of file MultipoleT.cpp.
References dummy.
getField() [2/2]
const EMField & MultipoleT::getField () const override virtual
Return a dummy field value
Implements Component.
Definition at line 560 of file MultipoleT.cpp.
References dummy.
getFn()
double MultipoleT::getFn (std::size_t n, double x, double s) private
Calculate fn(x, s) by expanding the differential operator (from Laplacian and scalar potential) in terms of polynomials
Parameters
n -> nth derivative
x -> Coordinate x
s -> Coordinate s
Definition at line 477 of file MultipoleT.cpp.
References angle_m, getFringeDeriv(), getTransDeriv(), length_m, Hypervolume::n, recursion_ConstRadius_m, recursion_VarRadius_m, and variableRadius_m.
Referenced by getBz(), getFnDerivS(), and getFnDerivX().
getFnDerivS()
double MultipoleT::getFnDerivS (std::size_t n, double x, double s) private
Calculate partial derivative of fn wrt s using a 5-point finite difference formuln Error of order stepSize^4
Parameters
n -> nth derivative
x -> Coordinate x
s -> Coordinate s
Definition at line 463 of file MultipoleT.cpp.
References Physics::e, getFn(), getFringeDeriv(), getTransDeriv(), and Hypervolume::n.
Referenced by getBs().
getFnDerivX()
double MultipoleT::getFnDerivX (std::size_t n, double x, double s) private
Calculate partial derivative of fn wrt x using a 5-point finite difference formula
Error of order stepSize^4
Parameters
n -> nth derivative
x -> Coordinate x
s -> Coordinate s
Definition at line 449 of file MultipoleT.cpp.
References Physics::e, getFn(), getFringeDeriv(), getTransDeriv(), and Hypervolume::n.
Referenced by getBx().
getFringeDeriv()
double MultipoleT::getFringeDeriv (int n, double s) private
Returns the value of the fringe field n-th derivative at s
Parameters
n -> nth derivative
s -> Coordinate s
Definition at line 353 of file MultipoleT.cpp.
References fringeField_l, fringeField_r, endfieldmodel::Tanh::getNegTanh(), endfieldmodel::Tanh::getTanh(), tanhderiv::integrate(), and Hypervolume::n.
Referenced by getBs(), getBx(), getBz(), getFn(), getFnDerivS(), getFnDerivX(), and getRadius().
getFringeLength()
std::vector< double > MultipoleT::getFringeLength () const
Return vector of 2 doubles [left fringe length, right fringelength]
Definition at line 422 of file MultipoleT.cpp.
References fringeField_l, fringeField_r, and endfieldmodel::Tanh::getLambda().
getGeometry() [1/2]
PlanarArcGeometry & MultipoleT::getGeometry () override virtual
Return the cell geometry
Implements ElementBase.
Definition at line 548 of file MultipoleT.cpp.
References planarArcGeometry_m.
getGeometry() [2/2]
const PlanarArcGeometry & MultipoleT::getGeometry () const override virtual
Return the cell geometry
Implements ElementBase.
Definition at line 552 of file MultipoleT.cpp.
References planarArcGeometry_m.
getLength()
double MultipoleT::getLength () const inline
Get the length of the magnet
Definition at line 426 of file MultipoleT.h.
References length_m.
getMaxOrder()
std::size_t MultipoleT::getMaxOrder () const inline
Get the number of terms used in calculation of field components
Definition at line 383 of file MultipoleT.h.
References maxOrder_m.
getMaxXOrder()
std::size_t MultipoleT::getMaxXOrder () const inline
Get highest power of x in polynomial expansions
Definition at line 388 of file MultipoleT.h.
References maxOrderX_m.
getRadius()
double MultipoleT::getRadius (double s) private
Radius of curvature
If radius of curvature is infinite, -1 is returned
If radius is constant, then
\(\rho(s) = length_m / angle_m \)
If radius is variable, then \(\rho(s) = rho(0) * S(0) / S(s) \) where S(s) is the fringe field
Parameters
s -> Coordinate s
Definition at line 429 of file MultipoleT.cpp.
References angle_m, getFringeDeriv(), length_m, and variableRadius_m.
Referenced by getScaleFactor().
getRotation()
double MultipoleT::getRotation () const inline
Get the angle of rotation of the magnet around its axis
Definition at line 406 of file MultipoleT.h.
References rotation_m.
getScaleFactor()
double MultipoleT::getScaleFactor (double x, double s) private
Returns the scale factor \(h_s = 1 + x / \rho(s) \)
Parameters
x -> Coordinate x
s -> Coordinate s
Definition at line 441 of file MultipoleT.cpp.
References angle_m, getRadius(), length_m, and variableRadius_m.
Referenced by getBs().
getTransDeriv()
double MultipoleT::getTransDeriv (std::size_t n, double x) private
Returns the value of the transverse field n-th derivative at x
Parameters
n -> nth derivative
x -> Coordinate x
Sets a vector of the coefficients in the polynomial expansion of transverse profile; shifts them to the left and multiply by corresponding power each time to take derivative once; repeats until desired derivative is reached
Definition at line 366 of file MultipoleT.cpp.
References Hypervolume::n, transMaxOrder_m, and transProfile_m.
Referenced by getBs(), getBx(), getBz(), getFn(), getFnDerivS(), and getFnDerivX().
getTransMaxOrder()
std::size_t MultipoleT::getTransMaxOrder () const inline
Get the maximum order in the given transverse profile
Definition at line 397 of file MultipoleT.h.
References transMaxOrder_m.
getTransProfile() [1/2]
double MultipoleT::getTransProfile (int n) const inline
Get transverse profile
Parameters
n -> Power of x
Definition at line 371 of file MultipoleT.h.
References Hypervolume::n, and transProfile_m.
getTransProfile() [2/2]
std::vector< double > MultipoleT::getTransProfile () const inline
Get all terms of transverse profile
Definition at line 375 of file MultipoleT.h.
References transProfile_m.
getVarRadius()
bool MultipoleT::getVarRadius () const inline
Get the value of variableRadius_m
Definition at line 359 of file MultipoleT.h.
References variableRadius_m.
initialise() [1/2]
void MultipoleT::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Initialise the MultipoleT
Parameters
bunch -> Bunch the global bunch object
startField -> Not used
endField -> Not used
Implements Component.
Definition at line 537 of file MultipoleT.cpp.
References initialise(), and Component::RefPartBunch_m.
Referenced by clone(), and OpalMultipoleT::update().
initialise() [2/2]
void MultipoleT::initialise ()
Initialises the geometry
Definition at line 532 of file MultipoleT.cpp.
References angle_m, boundingBoxLength_m, length_m, planarArcGeometry_m, PlanarArcGeometry::setCurvature(), and PlanarArcGeometry::setElementLength().
Referenced by initialise().
insideAperture()
bool MultipoleT::insideAperture (const Vector_t & R) private
Tests if inside the magnet
Parameters
R -> Coordinate vector
Definition at line 172 of file MultipoleT.cpp.
References abs(), horizApert_m, Attrib::Distribution::R, and verticalApert_m.
Referenced by apply().
operator=()
MultipoleT MultipoleT::operator= (const MultipoleT & rhs) private
rotateFrame()
Vector_t MultipoleT::rotateFrame (const Vector_t & R) private
Rotate frame for skew elements Consecutive rotations: 1st -> about central axis 2nd -> azimuthal rotation
Parameters
R -> Vector to be rotated
Apply two 2D rotation matrices to coordinate vector Rotate around central axis => skew fields Rotate azymuthaly => entrance angle
Definition at line 140 of file MultipoleT.cpp.
References cos(), entranceAngle_m, Attrib::Distribution::R, rotation_m, and sin().
Referenced by apply().
rotateFrameInverse()
Vector_t MultipoleT::rotateFrameInverse (Vector_t & B) private
Inverse of the 1st rotation in rotateFrame() method
Used to rotate B field back to global coordinate system
This function represents the inverse of the rotation around the central axis performed by rotateFrame() method Used to rotate B field back to global coordinate system
Definition at line 160 of file MultipoleT.cpp.
References cos(), rotation_m, and sin().
setAperture()
void MultipoleT::setAperture (double vertAp, double horizAp)
Set the aperture dimensions This element only supports a rectangular aperture
Parameters
vertAp -> Vertical aperture length
horizAp -> Horisontal aperture length
Definition at line 410 of file MultipoleT.cpp.
References horizApert_m, and verticalApert_m.
Referenced by OpalMultipoleT::update().
setBendAngle()
void MultipoleT::setBendAngle (double angle) inline
Set the bending angle of the magnet
Definition at line 414 of file MultipoleT.h.
References angle_m.
Referenced by OpalMultipoleT::update().
setBoundingBoxLength()
void MultipoleT::setBoundingBoxLength (const double & boundingBoxLength) inline
Set distance between centre of magnet and enctrance
Parameters
boundingBoxLength -> Distance between centre and entrance
Definition at line 434 of file MultipoleT.h.
References boundingBoxLength_m.
Referenced by OpalMultipoleT::update().
setDipoleConstant()
void MultipoleT::setDipoleConstant (double B0)
Set the dipole constant B_0
Definition at line 396 of file MultipoleT.cpp.
References transMaxOrder_m, and transProfile_m.
setEntranceAngle()
void MultipoleT::setEntranceAngle (double entranceAngle) inline
Set the entrance angle
Parameters
entranceAngle -> Entrance angle
Definition at line 363 of file MultipoleT.h.
References entranceAngle_m.
Referenced by OpalMultipoleT::update().
setFringeField()
bool MultipoleT::setFringeField (double s0, double lambda_left, double lambda_right)
Set fringe field model
Tanh model used here
\[ 1/2 * \left [tanh \left(\frac{s + s_0}{\lambda_{left}} \right) - tanh \left(\frac{s - s_0}{\lambda_{right}} \right) \right] \]
Parameters
s0 -> Centre field length
Definition at line 243 of file MultipoleT.cpp.
References fringeField_l, fringeField_r, and maxOrder_m.
Referenced by OpalMultipoleT::update().
setLength()
void MultipoleT::setLength (double length) inline
Set the length of the magnet
If straight-> Actual length
If curved -> Arc length
Definition at line 422 of file MultipoleT.h.
References abs(), and length_m.
Referenced by OpalMultipoleT::update().
setMaxOrder()
void MultipoleT::setMaxOrder (std::size_t maxOrder)
Set the number of terms used in calculation of field components
Maximum power of z in Bz is 2 * maxOrder_m
Parameters
maxOrder -> Number of terms in expansion in z
Definition at line 212 of file MultipoleT.cpp.
References angle_m, maxOrder_m, maxOrderX_m, recursion_ConstRadius_m, recursion_VarRadius_m, polynomial::RecursionRelation::resizeX(), polynomial::RecursionRelationTwo::resizeX(), transMaxOrder_m, polynomial::RecursionRelation::truncate(), polynomial::RecursionRelationTwo::truncate(), and variableRadius_m.
Referenced by OpalMultipoleT::update().
setMaxXOrder()
void MultipoleT::setMaxXOrder (std::size_t maxXOrder) inline
Set the number of terms used in polynomial expansions
Parameters
maxXOrder -> Number of terms in expansion in z
Definition at line 393 of file MultipoleT.h.
References maxOrderX_m.
Referenced by OpalMultipoleT::update().
setRotation()
void MultipoleT::setRotation (double rot) inline
Set the angle of rotation of the magnet around its axis
To make skew components
Parameters
rot -> Angle of rotation
Definition at line 410 of file MultipoleT.h.
References rotation_m.
Referenced by OpalMultipoleT::update().
setTransMaxOrder()
void MultipoleT::setTransMaxOrder (std::size_t transMaxOrder) inline
Set the maximum order in the given transverse profile
Parameters
transMaxOrder -> Highest power of x in field expansion
Definition at line 401 of file MultipoleT.h.
References transMaxOrder_m, and transProfile_m.
Referenced by OpalMultipoleT::update().
setTransProfile()
void MultipoleT::setTransProfile (std::size_t n, double Bn)
Set transverse profile T(x) T(x) = B_0 + B1 x + B2 x^2 + B3 x^3 + ...
Parameters
n -> Order of the term (d^n/dx^n) to be set
Bn -> Value of transverse profile coefficient
Definition at line 235 of file MultipoleT.cpp.
References Hypervolume::n, transMaxOrder_m, and transProfile_m.
Referenced by OpalMultipoleT::update().
setVarRadius()
void MultipoleT::setVarRadius () inline
Set variable radius flag to true
Definition at line 355 of file MultipoleT.h.
References variableRadius_m.
Referenced by OpalMultipoleT::update().
transformCoords()
Vector_t MultipoleT::transformCoords (const Vector_t & R) private
Transform to Frenet-Serret coordinates for sector magnets
Definition at line 181 of file MultipoleT.cpp.
References Physics::alpha, angle_m, atan(), fringeField_l, fringeField_r, endfieldmodel::Tanh::getLambda(), coordinatetransform::CoordinateTransform::getTransformation(), endfieldmodel::Tanh::getX0(), length_m, Attrib::Distribution::R, sin(), variableRadius_m, and X.
Referenced by apply().
Member Data Documentation
angle_m
double MultipoleT::angle_m private
Definition at line 283 of file MultipoleT.h.
Referenced by apply(), getBendAngle(), getBs(), getBx(), getBz(), getFn(), getRadius(), getScaleFactor(), initialise(), setBendAngle(), setMaxOrder(), and transformCoords().
boundingBoxLength_m
double MultipoleT::boundingBoxLength_m private
Distance between centre of magnet and entrance
Definition at line 289 of file MultipoleT.h.
Referenced by getBoundingBoxLength(), initialise(), and setBoundingBoxLength().
dummy
BMultipoleField MultipoleT::dummy private
Not implemented
Definition at line 299 of file MultipoleT.h.
Referenced by getField().
entranceAngle_m
double MultipoleT::entranceAngle_m private
Definition at line 284 of file MultipoleT.h.
Referenced by getEntranceAngle(), rotateFrame(), and setEntranceAngle().
fringeField_l
endfieldmodel::Tanh MultipoleT::fringeField_l private
Definition at line 251 of file MultipoleT.h.
Referenced by apply(), getFringeDeriv(), getFringeLength(), setFringeField(), and transformCoords().
fringeField_r
endfieldmodel::Tanh MultipoleT::fringeField_r private
Definition at line 252 of file MultipoleT.h.
Referenced by apply(), getFringeDeriv(), getFringeLength(), setFringeField(), and transformCoords().
horizApert_m
double MultipoleT::horizApert_m private
Definition at line 297 of file MultipoleT.h.
Referenced by getAperture(), insideAperture(), and setAperture().
length_m
double MultipoleT::length_m private
Magnet parameters
Definition at line 282 of file MultipoleT.h.
Referenced by apply(), getFn(), getLength(), getRadius(), getScaleFactor(), initialise(), setLength(), and transformCoords().
maxOrder_m
std::size_t MultipoleT::maxOrder_m = 0 private
Field expansion parameters
Number of terms in z expansion used in calculating field components
Definition at line 256 of file MultipoleT.h.
Referenced by getBs(), getBx(), getBz(), getMaxOrder(), setFringeField(), and setMaxOrder().
maxOrderX_m
std::size_t MultipoleT::maxOrderX_m = 0 private
Highest order of polynomial expansions in x
Definition at line 258 of file MultipoleT.h.
Referenced by getMaxXOrder(), setMaxOrder(), and setMaxXOrder().
planarArcGeometry_m
PlanarArcGeometry MultipoleT::planarArcGeometry_m private
Geometry
Definition at line 267 of file MultipoleT.h.
Referenced by getGeometry(), and initialise().
recursion_ConstRadius_m
std::vector<polynomial::RecursionRelation> MultipoleT::recursion_ConstRadius_m private
Definition at line 261 of file MultipoleT.h.
Referenced by getFn(), and setMaxOrder().
recursion_VarRadius_m
std::vector<polynomial::RecursionRelationTwo> MultipoleT::recursion_VarRadius_m private
Objects for storing differential operator acting on Fn
Definition at line 260 of file MultipoleT.h.
Referenced by getFn(), and setMaxOrder().
rotation_m
double MultipoleT::rotation_m private
Definition at line 285 of file MultipoleT.h.
Referenced by getRotation(), rotateFrame(), rotateFrameInverse(), and setRotation().
transMaxOrder_m
std::size_t MultipoleT::transMaxOrder_m = 0 private
Highest power in given mid-plane field
Definition at line 263 of file MultipoleT.h.
Referenced by getTransDeriv(), getTransMaxOrder(), setDipoleConstant(), setMaxOrder(), setTransMaxOrder(), and setTransProfile().
transProfile_m
std::vector<double> MultipoleT::transProfile_m private
List of transverse profile coefficients
Definition at line 265 of file MultipoleT.h.
Referenced by bends(), getDipoleConstant(), getTransDeriv(), getTransProfile(), setDipoleConstant(), setTransMaxOrder(), and setTransProfile().
variableRadius_m
bool MultipoleT::variableRadius_m private
Variable radius flag
Definition at line 287 of file MultipoleT.h.
Referenced by apply(), getBs(), getBx(), getBz(), getFn(), getRadius(), getScaleFactor(), getVarRadius(), setMaxOrder(), setVarRadius(), and transformCoords().
verticalApert_m
double MultipoleT::verticalApert_m private
Assume rectangular aperture with these dimensions
Definition at line 296 of file MultipoleT.h.
Referenced by getAperture(), insideAperture(), and setAperture().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/MultipoleT.h
src/Classic/AbsBeamline/MultipoleT.cpp