OPAL (Object Oriented Parallel Accelerator Library): TpsData Class Reference
TpsData Class Reference
Bookkeeping class for Tps<T>.
#include <TpsData.h>
Public Member Functions
TpsData ()
~TpsData ()
const TpsMonomial & getExponents (int index) const
int getOrder (int index) const
const int * getProductArray (int index) const
int getSize (int order) const
const Array1D< TpsSubstitution > & getSubTable () const
int getVariables () const
int indexMonomial (const TpsMonomial &) const
Static Public Member Functions
static TpsData * getTpsData (int nOrd, int nVar)
Private Types
typedef Array1D< TpsMonomial > ExponentTable
typedef Array1D< int > ProductRow
typedef Array1D< ProductRow > ProductTable
typedef Array2D< int > BinomialTable
Private Member Functions
TpsData (const TpsData &)
void operator= (const TpsData &)
void build (int max, int nVar)
void clear ()
void fillSubst (int var, int order, TpsMonomial &pow, int &next)
Private Attributes
int variables
int topOrder
int maxSize
ExponentTable expon
ProductTable prod
BinomialTable binom
Array1D< TpsSubstitution > subTable
Detailed Description
Bookkeeping class for Tps<T>.
Definition at line 35 of file TpsData.h.
Member Typedef Documentation
BinomialTable
typedef Array2D<int> TpsData::BinomialTable private
Definition at line 101 of file TpsData.h.
ExponentTable
typedef Array1D<TpsMonomial> TpsData::ExponentTable private
Definition at line 91 of file TpsData.h.
ProductRow
typedef Array1D<int> TpsData::ProductRow private
Definition at line 95 of file TpsData.h.
ProductTable
typedef Array1D<ProductRow> TpsData::ProductTable private
Definition at line 96 of file TpsData.h.
Constructor & Destructor Documentation
TpsData() [1/2]
TpsData::TpsData ()
Definition at line 34 of file TpsData.cpp.
References clear().
~TpsData()
TpsData::~TpsData ()
Definition at line 39 of file TpsData.cpp.
TpsData() [2/2]
TpsData::TpsData (const TpsData &) private
Member Function Documentation
build()
void TpsData::build (int max, int nVar) private
Definition at line 66 of file TpsData.cpp.
References binom, getSize(), maxSize, topOrder, and variables.
Referenced by getTpsData().
clear()
void TpsData::clear () private
Definition at line 147 of file TpsData.cpp.
References topOrder, and variables.
Referenced by TpsData().
fillSubst()
void TpsData::fillSubst (int var, int order, TpsMonomial & pow, int & next) private
Definition at line 154 of file TpsData.cpp.
References TpsSubstitution::index, TpsSubstitution::order, pow(), TpsSubstitution::skip, and TpsSubstitution::variable.
getExponents()
const TpsMonomial & TpsData::getExponents (int index) const inline
Definition at line 112 of file TpsData.h.
References expon.
getOrder()
int TpsData::getOrder (int index) const inline
Definition at line 120 of file TpsData.h.
References expon.
getProductArray()
const int * TpsData::getProductArray (int index) const inline
Definition at line 116 of file TpsData.h.
References Array1D< T >::begin(), and prod.
getSize()
int TpsData::getSize (int order) const inline
Definition at line 124 of file TpsData.h.
References binom, and topOrder.
Referenced by build(), and TpsRep< T >::create().
getSubTable()
const Array1D< TpsSubstitution > & TpsData::getSubTable () const inline
Definition at line 128 of file TpsData.h.
References subTable.
Referenced by VpsMap< T >::constantTerm(), and VpsMap< T >::substitute().
getTpsData()
TpsData * TpsData::getTpsData (int nOrd, int nVar) static
Definition at line 43 of file TpsData.cpp.
References build().
Referenced by VpsMap< T >::constantTerm(), TpsRep< T >::create(), TpsMonomial::getIndex(), and VpsMap< T >::substitute().
getVariables()
int TpsData::getVariables () const inline
Definition at line 132 of file TpsData.h.
References variables.
indexMonomial()
int TpsData::indexMonomial (const TpsMonomial & pows) const
Definition at line 53 of file TpsData.cpp.
References binom, and variables.
Referenced by TpsMonomial::getIndex().
operator=()
void TpsData::operator= (const TpsData &) private
Member Data Documentation
binom
BinomialTable TpsData::binom private
Definition at line 102 of file TpsData.h.
Referenced by build(), getSize(), and indexMonomial().
expon
ExponentTable TpsData::expon private
Definition at line 92 of file TpsData.h.
Referenced by getExponents(), and getOrder().
maxSize
int TpsData::maxSize private
Definition at line 88 of file TpsData.h.
Referenced by build().
prod
ProductTable TpsData::prod private
Definition at line 97 of file TpsData.h.
Referenced by getProductArray().
subTable
Array1D<TpsSubstitution> TpsData::subTable private
Definition at line 105 of file TpsData.h.
Referenced by getSubTable().
topOrder
int TpsData::topOrder private
Definition at line 85 of file TpsData.h.
Referenced by build(), clear(), and getSize().
variables
int TpsData::variables private
Definition at line 82 of file TpsData.h.
Referenced by build(), clear(), getVariables(), and indexMonomial().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algebra/TpsData.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algebra/TpsData.cpp