OPAL (Object Oriented Parallel Accelerator Library): StraightGeometry Class Reference
StraightGeometry Class Reference
A geometry representing a straight line.
#include <StraightGeometry.h>
Public Member Functions
StraightGeometry (double length=0.0)
Constructor.
StraightGeometry (const StraightGeometry &right)
virtual ~StraightGeometry ()
const StraightGeometry & operator= (const StraightGeometry &right)
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
double getOrigin () const
Get origin.
double getEntrance () const
Get entrance.
double getExit () const
Get exit.
Euclid3D getTransform (double fromS, double toS) const
Get transform.
Euclid3D getTransform (double s) const
Get transform.
Euclid3D getTotalTransform () const
Get transform.
Euclid3D getEntranceFrame () const
Get transform.
Euclid3D getExitFrame () const
Get transform.
Public Member Functions inherited from BGeometryBase
BGeometryBase ()
BGeometryBase (const BGeometryBase &right)
virtual ~BGeometryBase ()
const BGeometryBase & operator= (const BGeometryBase &right)
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
Private Attributes
double len
Detailed Description
A geometry representing a straight line.
Definition at line 34 of file StraightGeometry.h.
Constructor & Destructor Documentation
StraightGeometry() [1/2]
StraightGeometry::StraightGeometry (double length = 0.0) inline
Constructor.
Definition at line 109 of file StraightGeometry.h.
StraightGeometry() [2/2]
StraightGeometry::StraightGeometry (const StraightGeometry & right) inline
Definition at line 112 of file StraightGeometry.h.
~StraightGeometry()
StraightGeometry::~StraightGeometry () virtual
Definition at line 31 of file StraightGeometry.cpp.
Member Function Documentation
getArcLength()
double StraightGeometry::getArcLength () const virtual
Get arc length.
Implements BGeometryBase.
Reimplemented in RBendGeometry.
Definition at line 35 of file StraightGeometry.cpp.
References len.
getElementLength()
double StraightGeometry::getElementLength () const virtual
Get design length.
Implements BGeometryBase.
Definition at line 40 of file StraightGeometry.cpp.
References len.
Referenced by RBendGeometry::getArcLength(), RBendGeometry::getEntrancePatch(), RBendGeometry::getExitPatch(), Corrector::goOnline(), and Corrector::setDesignEnergy().
getEntrance()
double StraightGeometry::getEntrance () const virtual
Get entrance.
Reimplemented from BGeometryBase.
Definition at line 59 of file StraightGeometry.cpp.
References len.
getEntranceFrame()
Euclid3D StraightGeometry::getEntranceFrame () const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 84 of file StraightGeometry.cpp.
References len, and Euclid3D::translation().
Referenced by RBendGeometry::getEntranceFrame().
getExit()
double StraightGeometry::getExit () const virtual
Get exit.
Reimplemented from BGeometryBase.
Definition at line 64 of file StraightGeometry.cpp.
References len.
getExitFrame()
Euclid3D StraightGeometry::getExitFrame () const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 89 of file StraightGeometry.cpp.
References len, and Euclid3D::translation().
Referenced by RBendGeometry::getExitFrame().
getOrigin()
double StraightGeometry::getOrigin () const virtual
Get origin.
Reimplemented from BGeometryBase.
Definition at line 54 of file StraightGeometry.cpp.
References len.
getTotalTransform()
Euclid3D StraightGeometry::getTotalTransform () const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 74 of file StraightGeometry.cpp.
References len, and Euclid3D::translation().
Referenced by RBendGeometry::getTotalTransform().
getTransform() [1/2]
Euclid3D StraightGeometry::getTransform (double fromS, double toS) const virtual
Get transform.
Implements BGeometryBase.
Definition at line 69 of file StraightGeometry.cpp.
References Euclid3D::translation().
getTransform() [2/2]
Euclid3D StraightGeometry::getTransform (double s) const virtual
Get transform.
Reimplemented from BGeometryBase.
Definition at line 79 of file StraightGeometry.cpp.
References Euclid3D::translation().
operator=()
const StraightGeometry & StraightGeometry::operator= (const StraightGeometry & right) inline
Definition at line 117 of file StraightGeometry.h.
References len.
setElementLength()
void StraightGeometry::setElementLength (double length) virtual
Set design length.
Reimplemented from BGeometryBase.
Definition at line 45 of file StraightGeometry.cpp.
References len, and max().
Referenced by MultipoleTStraight::initialise(), VerticalFFAMagnet::initialise(), VariableRFCavity::setLength(), and OpalRBend::update().
Member Data Documentation
len
double StraightGeometry::len private
Definition at line 104 of file StraightGeometry.h.
Referenced by getArcLength(), getElementLength(), getEntrance(), getEntranceFrame(), getExit(), getExitFrame(), getOrigin(), getTotalTransform(), operator=(), and setElementLength().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/BeamlineGeometry/StraightGeometry.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/BeamlineGeometry/StraightGeometry.cpp