OPAL (Object Oriented Parallel Accelerator Library): OpalOffset::OpalLocalCartesianOffset Class Reference
OpalOffset::OpalLocalCartesianOffset Class Reference
#include <OpalLocalCartesianOffset.h>
Public Types
enum {
END_POSITION_X = COMMON, END_POSITION_Y, END_NORMAL_X, END_NORMAL_Y,
SIZE
}
Public Types inherited from OpalElement
enum {
TYPE, APERT, LENGTH, ELEMEDGE,
WAKEF, PARTICLEMATTERINTERACTION, ORIGIN, ORIENTATION,
X, Y, Z, THETA,
PHI, PSI, DX, DY,
DZ, DTHETA, DPHI, DPSI,
OUTFN, DELETEONTRANSVERSEEXIT, COMMON
}
The common attributes for all elements.
Public Types inherited from Element
enum ReferenceType { IS_ENTRY, IS_CENTRE, IS_EXIT }
Reference for element positioning.
Public Member Functions
OpalLocalCartesianOffset ()
virtual ~OpalLocalCartesianOffset ()
virtual OpalLocalCartesianOffset * clone ()
virtual OpalLocalCartesianOffset * clone (const std::string &name)
void update ()
virtual void print (std::ostream &) const
Public Member Functions inherited from OpalElement
virtual ~OpalElement ()
virtual double getLength () const
Return element length.
const std::string getTypeName () const
Return the element's type name.
std::pair< ApertureType, std::vector< double > > getApert () const
const std::string getWakeF () const
Return the element's type name.
const std::string getParticleMatterInteraction () const
const std::string getWMaterial () const
const std::string getWakeGeom () const
std::vector< double > getWakeParam () const
const std::string getWakeConductivity () const
virtual void parse (Statement &)
Parse the element.
virtual void updateUnknown (ElementBase *)
Transmit the `‘unknown’' (not known to OPAL) attributes to CLASSIC.
Public Member Functions inherited from Element
virtual ~Element ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual double getEntrance (ReferenceType) const
Return arc length from origin to entrance (negative !).
virtual double getExit (ReferenceType) const
Return arc length from origin to exit (positive !).
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded CLASSIC element.
void setElement (ElementBase *)
Assign new CLASSIC element.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
OpalLocalCartesianOffset (const OpalLocalCartesianOffset &)
void operator= (const OpalLocalCartesianOffset &)
OpalLocalCartesianOffset (const std::string &name, OpalLocalCartesianOffset *parent)
Static Private Attributes
static const std::string doc_string
Additional Inherited Members
Static Public Member Functions inherited from Element
static Element * find (const std::string &name)
Find named Element.
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from OpalElement
OpalElement (int size, const char *name, const char *help)
Exemplar constructor.
OpalElement (const std::string &name, OpalElement *parent)
Clone constructor.
void registerOwnership () const
Protected Member Functions inherited from Element
Element (int size, const char *name, const char *help)
Constructor for exemplars.
Element (const std::string &name, Element *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Static Protected Member Functions inherited from OpalElement
static void printMultipoleStrength (std::ostream &os, int order, int &len, const std::string &sName, const std::string &tName, const Attribute &length, const Attribute &vNorm, const Attribute &vSkew)
Print multipole components in OPAL-8 format.
static void printAttribute (std::ostream &os, const std::string &name, const std::string &image, int &len)
Print an attribute with a OPAL-8 name (as an expression).
static void printAttribute (std::ostream &os, const std::string &name, double value, int &len)
Print an attribute with a OPAL-8 name (as a constant).
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
OpalLocalCartesianOffset provides classes for making offsets between elements in a ring geometry; only condition is that they must be in the midplane
Definition at line 44 of file OpalLocalCartesianOffset.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumeration maps to UI parameters
Enumerator
END_POSITION_X
END_POSITION_Y
END_NORMAL_X
END_NORMAL_Y
SIZE
Definition at line 47 of file OpalLocalCartesianOffset.h.
Constructor & Destructor Documentation
OpalLocalCartesianOffset() [1/3]
OpalOffset::OpalLocalCartesianOffset::OpalLocalCartesianOffset ()
Define mapping from enum variables to string UI parameter names
Definition at line 45 of file OpalLocalCartesianOffset.cpp.
References END_NORMAL_X, END_NORMAL_Y, END_POSITION_X, END_POSITION_Y, Object::itsAttr, Attributes::makeReal(), OpalElement::registerOwnership(), and Element::setElement().
Referenced by clone().
~OpalLocalCartesianOffset()
OpalOffset::OpalLocalCartesianOffset::~OpalLocalCartesianOffset () virtual
No memory allocated so does nothing
Definition at line 81 of file OpalLocalCartesianOffset.cpp.
OpalLocalCartesianOffset() [2/3]
OpalOffset::OpalLocalCartesianOffset::OpalLocalCartesianOffset (const OpalLocalCartesianOffset &) private
OpalLocalCartesianOffset() [3/3]
OpalOffset::OpalLocalCartesianOffset::OpalLocalCartesianOffset (const std::string & name, OpalLocalCartesianOffset * parent) private
Definition at line 76 of file OpalLocalCartesianOffset.cpp.
References name, and Element::setElement().
Member Function Documentation
clone() [1/2]
OpalLocalCartesianOffset * OpalOffset::OpalLocalCartesianOffset::clone () virtual
Inherited copy constructor
Definition at line 63 of file OpalLocalCartesianOffset.cpp.
References Object::getOpalName(), and OpalLocalCartesianOffset().
clone() [2/2]
OpalLocalCartesianOffset * OpalOffset::OpalLocalCartesianOffset::clone (const std::string & name) virtual
Inherited copy constructor
Implements Object.
Definition at line 68 of file OpalLocalCartesianOffset.cpp.
References name, and OpalLocalCartesianOffset().
operator=()
void OpalOffset::OpalLocalCartesianOffset::operator= (const OpalLocalCartesianOffset &) private
print()
void OpalOffset::OpalLocalCartesianOffset::print (std::ostream & out) const virtual
Calls print on the OpalElement
Reimplemented from OpalElement.
Definition at line 72 of file OpalLocalCartesianOffset.cpp.
References OpalElement::print().
update()
void OpalOffset::OpalLocalCartesianOffset::update () virtual
Receive parameters from the parser and hand them off to the OpalCylindricalOffset
Reimplemented from OpalElement.
Definition at line 83 of file OpalLocalCartesianOffset.cpp.
References END_NORMAL_X, END_NORMAL_Y, END_POSITION_X, END_POSITION_Y, Element::getElement(), Object::getOpalName(), Attributes::getReal(), Object::itsAttr, Offset::localCartesianOffset(), name, and Element::setElement().
Member Data Documentation
doc_string
const std::string OpalOffset::OpalLocalCartesianOffset::doc_string static private
Initial value:
=
    std::string("The \"LOCAL_CARTESIAN_OFFSET\" element defines an offset")+
    std::string("in cartesian coordinates, relative to the last placed ")+
    std::string("element.")
Definition at line 82 of file OpalLocalCartesianOffset.h.
The documentation for this class was generated from the following files:
src/Elements/OpalOffset/OpalLocalCartesianOffset.h
src/Elements/OpalOffset/OpalLocalCartesianOffset.cpp