OPAL (Object Oriented Parallel Accelerator Library): Stripper Class Reference
Stripper Class Reference
#include <Stripper.h>
Public Member Functions
Stripper (const std::string &name)
Constructor with given name.
Stripper ()
Stripper (const Stripper &)
void operator= (const Stripper &)=delete
virtual ~Stripper ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to Stripper.
virtual int getRequiredNumberOfTimeSteps () const override
virtual ElementType getType () const override
Override implementation of PluginElement.
void setOPCharge (double charge)
Member variable access.
double getOPCharge () const
void setOPMass (double mass)
double getOPMass () const
void setOPYield (double yield)
double getOPYield () const
void setStop (bool stopflag)
bool getStop () const
Public Member Functions inherited from PluginElement
PluginElement (const std::string &name)
Constructor with given name.
PluginElement ()
PluginElement (const PluginElement &)
void operator= (const PluginElement &)=delete
virtual ~PluginElement ()
void setDimensions (double xstart, double xend, double ystart, double yend)
Set dimensions and consistency checks.
bool check (PartBunchBase< double, 3 > *bunch, const int turnnumber, const double t, const double tstep)
int checkPoint (const double &x, const double &y) const
Checks if coordinate is within element.
void save ()
Save output.
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
Pure virtual implementation of Component.
void initialise (PartBunchBase< double, 3 > *bunch)
virtual void finalise () final
virtual void goOffline () final
virtual bool bends () const override
virtual void getDimensions (double &zBegin, double &zEnd) const override
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
double getXStart () const
Member variable access.
double getXEnd () const
double getYStart () const
double getYEnd () const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
virtual EMField & getField ()=0
Return field.
virtual const EMField & getField () const =0
Return field.
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
virtual bool doCheck (PartBunchBase< double, 3 > *bunch, const int turnnumber, const double t, const double tstep) override
Record hits when bunch particles pass.
virtual void doFinalise () override
Virtual hook for finalise.
virtual bool doPreCheck (PartBunchBase< double, 3 > *) override
Virtual hook for preCheck.
virtual bool doFinaliseCheck (PartBunchBase< double, 3 > *bunch, bool flagNeedUpdate) override
Virtual hook for finaliseCheck.
Private Attributes
double opcharge_m
Charge number of the out-coming particle.
double opmass_m
Mass of the out-coming particle.
double opyield_m
Yield of the out-coming particle.
bool stop_m
Flag if particles should be stripped or stopped.
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from PluginElement
void setGeom (const double dist)
Sets geometry geom_m with element width dist.
void changeWidth (PartBunchBase< double, 3 > *bunch, int i, const double tstep, const double tangle)
Change probe width depending on step size and angle of particle.
double calculateIncidentAngle (double xp, double yp) const
Calculate angle of particle/bunch wrt to element.
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from PluginElement
double rmin_m
radius closest to the origin
Point geom_m [5]
actual geometry positions with adaptive width such that each particle hits element once per turn
double A_m
double B_m
double R_m
double C_m
Geometric lengths used in calculations.
std::unique_ptr< LossDataSink > lossDs_m
Pointer to Loss instance.
int numPassages_m = 0
Number of turns (number of times save() method is called)
double xstart_m
input geometry positions
double xend_m
double ystart_m
double yend_m
double rstart_m
double rend_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 31 of file Stripper.h.
Constructor & Destructor Documentation
Stripper() [1/3]
Stripper::Stripper (const std::string & name) explicit
Constructor with given name.
Definition at line 39 of file Stripper.cpp.
Stripper() [2/3]
Stripper::Stripper ()
Definition at line 36 of file Stripper.cpp.
Stripper() [3/3]
Stripper::Stripper (const Stripper & right)
Definition at line 47 of file Stripper.cpp.
~Stripper()
Stripper::~Stripper () virtual
Definition at line 55 of file Stripper.cpp.
Member Function Documentation
accept()
void Stripper::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to Stripper.
Implements ElementBase.
Definition at line 57 of file Stripper.cpp.
References BeamlineVisitor::visitStripper().
doCheck()
bool Stripper::doCheck (PartBunchBase< double, 3 > * bunch, const int turnnumber, const double t, const double tstep) override private virtual
Record hits when bunch particles pass.
Implements PluginElement.
Definition at line 112 of file Stripper.cpp.
References PluginElement::A_m, PluginElement::B_m, PartBunchBase< T, Dim >::Bin, PartBunchBase< T, Dim >::bunchNum, Physics::c, PluginElement::C_m, PluginElement::calculateIncidentAngle(), PluginElement::changeWidth(), PluginElement::checkPoint(), PartBunchBase< T, Dim >::create(), dot(), endl(), PartBunchBase< T, Dim >::getLocalNum(), ElementBase::getName(), PartBunchBase< T, Dim >::ID, INFORM_ALL_NODES, level4(), PluginElement::lossDs_m, PartBunchBase< T, Dim >::M, opcharge_m, opmass_m, opyield_m, PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::POrigin, PartBunchBase< T, Dim >::Q, Physics::q_e, PartBunchBase< T, Dim >::R, PluginElement::R_m, REGULAR, PartBunchBase< T, Dim >::setPOrigin(), sqrt(), stop_m, STRIPPED, and PartBunchBase< T, Dim >::weHaveBins().
doFinalise()
void Stripper::doFinalise () override private virtual
Virtual hook for finalise.
Reimplemented from PluginElement.
Definition at line 61 of file Stripper.cpp.
References endl(), ElementBase::getName(), and gmsg.
doFinaliseCheck()
bool Stripper::doFinaliseCheck (PartBunchBase< double, 3 > * bunch, bool flagNeedUpdate) override private virtual
Virtual hook for finaliseCheck.
Reimplemented from PluginElement.
Definition at line 177 of file Stripper.cpp.
References PartBunchBase< T, Dim >::getPOrigin(), Units::GeV2eV, opcharge_m, opmass_m, reduce(), PartBunchBase< T, Dim >::resetM(), PartBunchBase< T, Dim >::resetQ(), stop_m, and STRIPPED.
doPreCheck()
bool Stripper::doPreCheck (PartBunchBase< double, 3 > * bunch) override private virtual
Virtual hook for preCheck.
Reimplemented from PluginElement.
Definition at line 97 of file Stripper.cpp.
References abs(), Physics::e, PartBunchBase< T, Dim >::get_bounds(), max(), and PluginElement::rmin_m.
getOPCharge()
double Stripper::getOPCharge () const
Definition at line 81 of file Stripper.cpp.
References opcharge_m.
Referenced by ParallelCyclotronTracker::visitStripper().
getOPMass()
double Stripper::getOPMass () const
Definition at line 85 of file Stripper.cpp.
References opmass_m.
Referenced by ParallelCyclotronTracker::visitStripper().
getOPYield()
double Stripper::getOPYield () const
Definition at line 89 of file Stripper.cpp.
References opyield_m.
getRequiredNumberOfTimeSteps()
int Stripper::getRequiredNumberOfTimeSteps () const inline override virtual
Reimplemented from ElementBase.
Definition at line 78 of file Stripper.h.
getStop()
bool Stripper::getStop () const
Definition at line 93 of file Stripper.cpp.
References stop_m.
Referenced by ParallelCyclotronTracker::visitStripper().
getType()
ElementType Stripper::getType () const override virtual
Override implementation of PluginElement.
Reimplemented from Component.
Definition at line 191 of file Stripper.cpp.
References STRIPPER.
operator=()
void Stripper::operator= (const Stripper &) delete
setOPCharge()
void Stripper::setOPCharge (double charge)
Member variable access.
Definition at line 65 of file Stripper.cpp.
References opcharge_m.
Referenced by OpalStripper::update().
setOPMass()
void Stripper::setOPMass (double mass)
Definition at line 69 of file Stripper.cpp.
References opmass_m.
Referenced by OpalStripper::update().
setOPYield()
void Stripper::setOPYield (double yield)
Definition at line 73 of file Stripper.cpp.
References opyield_m.
Referenced by OpalStripper::update().
setStop()
void Stripper::setStop (bool stopflag)
Definition at line 77 of file Stripper.cpp.
References stop_m.
Referenced by OpalStripper::update().
Member Data Documentation
opcharge_m
double Stripper::opcharge_m private
Charge number of the out-coming particle.
Definition at line 71 of file Stripper.h.
Referenced by doCheck(), doFinaliseCheck(), getOPCharge(), and setOPCharge().
opmass_m
double Stripper::opmass_m private
Mass of the out-coming particle.
Definition at line 72 of file Stripper.h.
Referenced by doCheck(), doFinaliseCheck(), getOPMass(), and setOPMass().
opyield_m
double Stripper::opyield_m private
Yield of the out-coming particle.
Definition at line 73 of file Stripper.h.
Referenced by doCheck(), getOPYield(), and setOPYield().
stop_m
bool Stripper::stop_m private
Flag if particles should be stripped or stopped.
Definition at line 74 of file Stripper.h.
Referenced by doCheck(), doFinaliseCheck(), getStop(), and setStop().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/Stripper.h
src/Classic/AbsBeamline/Stripper.cpp