OPAL (Object Oriented Parallel Accelerator Library): RBendRep Class Reference
RBendRep Class Reference
#include <RBendRep.h>
Public Member Functions
RBendRep (const std::string &name)
Constructor with given name.
RBendRep ()
RBendRep (const RBendRep &)
virtual ~RBendRep ()
virtual ElementBase * clone () const
Return clone.
virtual Channel * getChannel (const std::string &aKey, bool=false)
Construct a read/write channel.
virtual BMultipoleField & getField ()
Get field.
virtual const BMultipoleField & getField () const
Get field.
virtual RBendGeometry & getGeometry ()
Get geometry.
virtual const RBendGeometry & getGeometry () const
Get geometry.
virtual double getB () const
Get field.
virtual void setB (double By)
Set vertical component.
virtual void setField (const BMultipoleField &field)
Set field.
virtual double getEntryFaceRotation () const
Get pole entry face rotation.
virtual double getExitFaceRotation () const
Get exit pole face rotation.
virtual double getEntryFaceCurvature () const
Get entry pole face curvature.
virtual double getExitFaceCurvature () const
Get exit pole face curvature.
virtual void setEntryFaceRotation (double e1)
Set pole entry face rotation.
virtual void setExitFaceRotation (double e2)
Set exit pole face rotation.
virtual void setEntryFaceCurvature (double h1)
Set entry pole face curvature.
virtual void setExitFaceCurvature (double h2)
Set exit pole face curvature.
virtual double getSlices () const
Get number of slices.
virtual double getStepsize () const
Get stepsize.
virtual void setSlices (double sl)
Set number of slices.
virtual void setStepsize (double ds)
Set stepsize.
Public Member Functions inherited from RBend
RBend (const std::string &name)
Constructor with given name.
RBend ()
RBend (const RBend &)
virtual ~RBend ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to RBend.
double getNormalComponent (int) const
Get normal component.
double getSkewComponent (int) const
Get skew component.
void setNormalComponent (int, double)
Set normal component.
void setSkewComponent (int, double)
Set skew component.
virtual ElementType getType () const override
Get element type std::string.
virtual void setBendAngle (double angle) override
virtual void setEntranceAngle (double entranceAngle) override
Public Member Functions inherited from Bend2D
Bend2D (const std::string &name)
Constructor with given name.
Bend2D ()
Bend2D (const Bend2D &)
virtual ~Bend2D ()
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
Apply field to particles with coordinates in magnet frame.
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
Apply field to particles in beam frame.
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void goOnline (const double &kineticEnergy) override
virtual void finalise () override
virtual void getDimensions (double &sBegin, double &sEnd) const override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
double getBendRadius () const
double getEffectiveCenter () const
double getEffectiveLength () const
void setK1 (double k1)
Set quadrupole field component.
void setExitAngle (double exitAngle)
virtual double getExitAngle () const override
std::vector< Vector_t > getOutline () const
MeshData getSurfaceMesh () const
virtual CoordinateSystemTrafo getEdgeToEnd () const override
CoordinateSystemTrafo getBeginToEnd_local () const
virtual bool isInside (const Vector_t &r) const override
void setNSlices (const std::size_t &nSlices)
std::size_t getNSlices () const
std::array< double, 2 > getEntranceFringeFieldLength () const
Get entrance fringe field length.
std::array< double, 2 > getExitFringeFieldLength () const
Get exit fringe field length.
BoundingBox getBoundingBoxInLabCoords () const override
Public Member Functions inherited from BendBase
BendBase ()
BendBase (const BendBase &)
BendBase (const std::string &)
virtual bool bends () const
Indicates that element bends the beam.
double getChordLength () const
double getBendAngle () const
double getEntranceAngle () const
void setFullGap (double)
double getFullGap () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
double getDesignEnergy () const
std::vector< Vector_t > getDesignPath () const
void setFieldAmplitude (double k0, double k0s)
double getFieldAmplitude () const
void setFieldMapFN (std::string fileName)
std::string getFieldMapFN () const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual void goOffline ()
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void operator= (const RBendRep &)
Private Attributes
RBendGeometry geometry
The bend geometry.
BMultipoleField field
The multipole expansion.
double rEntry
double rExit
double hEntry
double hExit
double slices
double stepsize
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from Bend2D
void setMessageHeader (const std::string &header)
double getStartField () const
Protected Member Functions inherited from BendBase
double calcDesignRadius (double fieldAmplitude) const
Calculate design radius from design energy and field amplitude.
double calcFieldAmplitude (double radius) const
Calculate field amplitude from design energy and radius.
double calcBendAngle (double chordLength, double radius) const
Calculate bend angle from chord length and design radius.
double calcDesignRadius (double chordLength, double angle) const
Calculate design radius from chord length and bend angle.
double calcGamma () const
Calculate gamma from design energy.
double calcBetaGamma () const
Calculate beta*gamma from design energy.
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from BendBase
double chordLength_m
double angle_m
Bend angle.
double entranceAngle_m
Fieldmap fieldmap_m
Magnet field map.
const bool fast_m = false
Flag to turn on fast field calculation.
double gap_m
Full vertical gap of the magnets.
double designEnergy_m
Bend design energy (eV).
bool designEnergyChangeable_m
std::vector< Vector_t > refTrajMap_m
Map of reference particle trajectory.
double fieldAmplitudeX_m
double fieldAmplitudeY_m
double fieldAmplitude_m
Field amplitude.
std::string fileName_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 28 of file RBendRep.h.
Constructor & Destructor Documentation
RBendRep() [1/3]
RBendRep::RBendRep (const std::string & name) explicit
Constructor with given name.
Definition at line 45 of file RBendRep.cpp.
References hEntry, hExit, rEntry, and rExit.
RBendRep() [2/3]
RBendRep::RBendRep ()
Definition at line 26 of file RBendRep.cpp.
References hEntry, hExit, rEntry, and rExit.
Referenced by clone().
RBendRep() [3/3]
RBendRep::RBendRep (const RBendRep & rhs)
Definition at line 34 of file RBendRep.cpp.
References hEntry, hExit, rEntry, and rExit.
~RBendRep()
RBendRep::~RBendRep () virtual
Definition at line 53 of file RBendRep.cpp.
Member Function Documentation
clone()
ElementBase * RBendRep::clone () const virtual
Return clone.
Implements ElementBase.
Definition at line 57 of file RBendRep.cpp.
References RBendRep().
getB()
double RBendRep::getB () const virtual
Get field.
Implements RBend.
Definition at line 85 of file RBendRep.cpp.
References field, and BMultipoleField::getNormalComponent().
getChannel()
Channel * RBendRep::getChannel (const std::string & aKey, bool create = false) virtual
Construct a read/write channel.
Reimplemented from ElementBase.
Definition at line 62 of file RBendRep.cpp.
References ElementBase::getChannel().
getEntryFaceCurvature()
double RBendRep::getEntryFaceCurvature () const virtual
Get entry pole face curvature.
Implements RBend.
Definition at line 111 of file RBendRep.cpp.
References hEntry.
getEntryFaceRotation()
double RBendRep::getEntryFaceRotation () const virtual
Get pole entry face rotation.
Implements RBend.
Definition at line 94 of file RBendRep.cpp.
References rEntry.
getExitFaceCurvature()
double RBendRep::getExitFaceCurvature () const virtual
Get exit pole face curvature.
Implements RBend.
Definition at line 115 of file RBendRep.cpp.
References hExit.
getExitFaceRotation()
double RBendRep::getExitFaceRotation () const virtual
Get exit pole face rotation.
Implements RBend.
Definition at line 99 of file RBendRep.cpp.
References rExit.
getField() [1/2]
BMultipoleField & RBendRep::getField () virtual
Get field.
Implements RBend.
Definition at line 67 of file RBendRep.cpp.
References field.
getField() [2/2]
const BMultipoleField & RBendRep::getField () const virtual
Get field.
Implements RBend.
Definition at line 71 of file RBendRep.cpp.
References field.
getGeometry() [1/2]
RBendGeometry & RBendRep::getGeometry () virtual
Get geometry.
Implements RBend.
Definition at line 76 of file RBendRep.cpp.
References geometry.
Referenced by OpalRBend::update().
getGeometry() [2/2]
const RBendGeometry & RBendRep::getGeometry () const virtual
Get geometry.
Implements RBend.
Definition at line 80 of file RBendRep.cpp.
References geometry.
getSlices()
double RBendRep::getSlices () const virtual
Get number of slices.
Implements RBend.
Definition at line 128 of file RBendRep.cpp.
References slices.
getStepsize()
double RBendRep::getStepsize () const virtual
Get stepsize.
Implements RBend.
Definition at line 132 of file RBendRep.cpp.
References stepsize.
operator=()
void RBendRep::operator= (const RBendRep &) private
setB()
void RBendRep::setB (double By) virtual
Set vertical component.
Definition at line 89 of file RBendRep.cpp.
References field, and BMultipoleField::setNormalComponent().
setEntryFaceCurvature()
void RBendRep::setEntryFaceCurvature (double h1) virtual
Set entry pole face curvature.
Definition at line 119 of file RBendRep.cpp.
References hEntry.
Referenced by OpalRBend::update().
setEntryFaceRotation()
void RBendRep::setEntryFaceRotation (double e1) virtual
Set pole entry face rotation.
Definition at line 103 of file RBendRep.cpp.
References rEntry.
Referenced by OpalRBend::update().
setExitFaceCurvature()
void RBendRep::setExitFaceCurvature (double h2) virtual
Set exit pole face curvature.
Definition at line 123 of file RBendRep.cpp.
References hExit.
Referenced by OpalRBend::update().
setExitFaceRotation()
void RBendRep::setExitFaceRotation (double e2) virtual
Set exit pole face rotation.
Definition at line 107 of file RBendRep.cpp.
References rExit.
Referenced by OpalRBend::update().
setField()
void RBendRep::setField (const BMultipoleField & field) virtual
Set field.
Definition at line 145 of file RBendRep.cpp.
References field.
Referenced by OpalRBend::update().
setSlices()
void RBendRep::setSlices (double sl) virtual
Set number of slices.
Definition at line 136 of file RBendRep.cpp.
References slices.
Referenced by OpalRBend::update().
setStepsize()
void RBendRep::setStepsize (double ds) virtual
Set stepsize.
Definition at line 140 of file RBendRep.cpp.
References stepsize.
Referenced by OpalRBend::update().
Member Data Documentation
field
BMultipoleField RBendRep::field private
The multipole expansion.
Definition at line 142 of file RBendRep.h.
Referenced by getB(), getField(), setB(), and setField().
geometry
RBendGeometry RBendRep::geometry private
The bend geometry.
Definition at line 139 of file RBendRep.h.
Referenced by getGeometry().
hEntry
double RBendRep::hEntry private
Definition at line 147 of file RBendRep.h.
Referenced by getEntryFaceCurvature(), RBendRep(), and setEntryFaceCurvature().
hExit
double RBendRep::hExit private
Definition at line 148 of file RBendRep.h.
Referenced by getExitFaceCurvature(), RBendRep(), and setExitFaceCurvature().
rEntry
double RBendRep::rEntry private
Definition at line 145 of file RBendRep.h.
Referenced by getEntryFaceRotation(), RBendRep(), and setEntryFaceRotation().
rExit
double RBendRep::rExit private
Definition at line 146 of file RBendRep.h.
Referenced by getExitFaceRotation(), RBendRep(), and setExitFaceRotation().
slices
double RBendRep::slices private
Definition at line 151 of file RBendRep.h.
Referenced by getSlices(), and setSlices().
stepsize
double RBendRep::stepsize private
Definition at line 152 of file RBendRep.h.
Referenced by getStepsize(), and setStepsize().
The documentation for this class was generated from the following files:
src/Classic/BeamlineCore/RBendRep.h
src/Classic/BeamlineCore/RBendRep.cpp