OPAL (Object Oriented Parallel Accelerator Library): IntCICImpl< 1U > Class Template Reference
IntCICImpl< 1U > Class Template Reference
#include <IntCIC.h>
Public Member Functions
IntCICImpl ()
~IntCICImpl ()
Public Member Functions inherited from Interpolator
Interpolator ()
~Interpolator ()
Static Public Member Functions
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 1U, M, C > &f, const Vektor< PT, 1U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 1U, M, C > &f, const Vektor< PT, 1U > &ppos, const M &mesh, NDIndex< 1U > &ngp, int lgpoff[1U], Vektor< PT, 1U > &dpos)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 1U, M, C > &f, const NDIndex< 1U > &ngp, const int lgpoff[1U], const Vektor< PT, 1U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 1U, M, C > &f, const Vektor< PT, 1U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 1U, M, C > &f, const Vektor< PT, 1U > &ppos, const M &mesh, NDIndex< 1U > &ngp, int lgpoff[1U], Vektor< PT, 1U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 1U, M, C > &f, const NDIndex< 1U > &ngp, const int lgpoff[1U], const Vektor< PT, 1U > &dpos)
Additional Inherited Members
Static Protected Member Functions inherited from Interpolator
template<class T , unsigned Dim>
static CompressedBrickIterator< T, Dim > getFieldIter (const BareField< T, Dim > &f, const NDIndex< Dim > &pt)
Detailed Description
template<>
class IntCICImpl< 1U >
Definition at line 242 of file IntCIC.h.
Constructor & Destructor Documentation
IntCICImpl()
IntCICImpl< 1U >::IntCICImpl () inline
Definition at line 246 of file IntCIC.h.
~IntCICImpl()
IntCICImpl< 1U >::~IntCICImpl () inline
Definition at line 247 of file IntCIC.h.
Member Function Documentation
gather() [1/3]
template<class FT , class M , class C , class PT > static void IntCICImpl< 1U >::gather (FT & pdata, const Field< FT, 1U, M, C > & f, const Vektor< PT, 1U > & ppos, const M & mesh) inline static
Definition at line 353 of file IntCIC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
gather() [2/3]
template<class FT , class M , class C , class PT > static void IntCICImpl< 1U >::gather (FT & pdata, const Field< FT, 1U, M, C > & f, const Vektor< PT, 1U > & ppos, const M & mesh, NDIndex< 1U > & ngp, int lgpoff[1U], Vektor< PT, 1U > & dpos) inline static
Definition at line 395 of file IntCIC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
gather() [3/3]
template<class FT , class M , class C , class PT > static void IntCICImpl< 1U >::gather (FT & pdata, const Field< FT, 1U, M, C > & f, const NDIndex< 1U > & ngp, const int lgpoff[1U], const Vektor< PT, 1U > & dpos) inline static
Definition at line 435 of file IntCIC.h.
References Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
scatter() [1/3]
template<class FT , class M , class C , class PT > static void IntCICImpl< 1U >::scatter (const FT & pdata, Field< FT, 1U, M, C > & f, const Vektor< PT, 1U > & ppos, const M & mesh) inline static
Definition at line 254 of file IntCIC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
scatter() [2/3]
template<class FT , class M , class C , class PT > static void IntCICImpl< 1U >::scatter (const FT & pdata, Field< FT, 1U, M, C > & f, const Vektor< PT, 1U > & ppos, const M & mesh, NDIndex< 1U > & ngp, int lgpoff[1U], Vektor< PT, 1U > & dpos) inline static
Definition at line 296 of file IntCIC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
scatter() [3/3]
template<class FT , class M , class C , class PT > static void IntCICImpl< 1U >::scatter (const FT & pdata, Field< FT, 1U, M, C > & f, const NDIndex< 1U > & ngp, const int lgpoff[1U], const Vektor< PT, 1U > & dpos) inline static
Definition at line 336 of file IntCIC.h.
References Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/IntCIC.h