OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Classic/FixedAlgebra/Taylor.h File Reference
Taylor.h File Reference
#include "Algebra/Array1D.h"
#include "FixedAlgebra/Taylor.hpp"
Classes
class Taylor< T >
A representation for a Taylor series in one variable,.
Functions
template<class T >
Taylor< T > operator+ (const Taylor< T > &, const Taylor< T > &)
Add.
template<class T >
Taylor< T > operator- (const Taylor< T > &, const Taylor< T > &)
Subtract.
template<class T >
Taylor< T > operator* (const Taylor< T > &, double)
Multiply by scalar.
template<class T >
Taylor< T > operator* (double, const Taylor< T > &)
Multiply by scalar.
template<class T >
Taylor< T > operator/ (const Taylor< T > &, double)
Divide by scalar.
template<class T >
Taylor< T > PoissonBracket (const Taylor< T > &, const Taylor< T > &)
Poisson bracket of two Taylor seriess.
template<class T >
std::ostream & operator<< (std::ostream &, const Taylor< T > &)
Output.
Function Documentation
operator*() [1/2]
template<class T > Taylor<T> operator* (const Taylor< T > & , double)
Multiply by scalar.
Definition at line 235 of file Taylor.hpp.
References Taylor< T >::begin(), Taylor< T >::end(), Taylor< T >::getOrder(), and Attrib::Legacy::Distribution::T.
operator*() [2/2]
template<class T > Taylor<T> operator* (double , const Taylor< T > &)
Multiply by scalar.
Definition at line 248 of file Taylor.hpp.
References Taylor< T >::begin(), Taylor< T >::end(), Taylor< T >::getOrder(), and Attrib::Legacy::Distribution::T.
operator+()
template<class T > Taylor<T> operator+ (const Taylor< T > & , const Taylor< T > &)
Add.
Definition at line 203 of file Taylor.hpp.
References Taylor< T >::begin(), Taylor< T >::end(), Taylor< T >::getOrder(), max(), and Attrib::Legacy::Distribution::T.
operator-()
template<class T > Taylor<T> operator- (const Taylor< T > & , const Taylor< T > &)
Subtract.
Definition at line 219 of file Taylor.hpp.
References Taylor< T >::begin(), Taylor< T >::end(), Taylor< T >::getOrder(), max(), and Attrib::Legacy::Distribution::T.
operator/()
template<class T > Taylor<T> operator/ (const Taylor< T > & , double)
Divide by scalar.
Definition at line 261 of file Taylor.hpp.
References Taylor< T >::begin(), Taylor< T >::end(), Taylor< T >::getOrder(), and Attrib::Legacy::Distribution::T.
operator<<()
template<class T > std::ostream& operator<< (std::ostream & , const Taylor< T > &)
Output.
Definition at line 290 of file Taylor.hpp.
References endl().
PoissonBracket()
template<class T > Taylor<T> PoissonBracket (const Taylor< T > & , const Taylor< T > &)
Poisson bracket of two Taylor seriess.
Definition at line 274 of file Taylor.hpp.
References Taylor< T >::getOrder().