OPAL (Object Oriented Parallel Accelerator Library): TravelingWave Class Reference
TravelingWave Class Reference abstract
Interface for Traveling Wave.
#include <TravelingWave.h>
Public Types
enum CavityType { SW, TW }
Public Types inherited from RFCavity
enum CavityType { SW, SGSW }
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Public Member Functions
TravelingWave (const std::string &name)
Constructor with given name.
TravelingWave ()
TravelingWave (const TravelingWave &)
virtual ~TravelingWave ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to TravelingWave.
virtual double getAmplitude () const override=0
Get RF amplitude.
virtual double getFrequency () const override=0
Get RF frequencey.
virtual double getPhase () const override=0
Get RF phase.
virtual void setPhasem (double phase) override
void setNumCells (int NumCells)
void setMode (double mode)
virtual double getAutoPhaseEstimate (const double &E0, const double &t0, const double &q, const double &m) override
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void finalise () override
virtual bool bends () const override
virtual void goOnline (const double &kineticEnergy) override
virtual void goOffline () override
virtual ElementBase::ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
virtual bool isInside (const Vector_t &r) const override
virtual void getElementDimensions (double &begin, double &end) const override
virtual CoordinateSystemTrafo getEdgeToBegin () const override
virtual CoordinateSystemTrafo getEdgeToEnd () const override
Public Member Functions inherited from RFCavity
RFCavity (const std::string &name)
Constructor with given name.
RFCavity ()
RFCavity (const RFCavity &)
virtual ~RFCavity ()
void dropFieldmaps ()
virtual void setFieldMapFN (std::string fmapfn)
Set the name of the field map.
virtual std::string getFieldMapFN () const
virtual void setAmplitudem (double vPeak)
virtual double getAmplitudem () const
virtual void setAmplitudeError (double vPeakError)
virtual double getAmplitudeError () const
virtual void setFrequencym (double freq)
void setFrequency (double freq)
virtual double getFrequencym () const
virtual double getPhasem () const
double getPhasem (double t) const
virtual void setPhaseError (double phaseError)
virtual double getPhaseError () const
void setCavityType (std::string type)
std::string getCavityType () const
virtual void setFast (bool fast)
virtual bool getFast () const
virtual void setAutophaseVeto (bool veto=true)
virtual bool getAutophaseVeto () const
virtual double getAutoPhaseEstimateFallback (double E0, double t0, double q, double m)
virtual std::pair< double, double > trackOnAxisParticle (const double &p0, const double &t0, const double &dt, const double &q, const double &mass, std::ofstream *out=NULL)
virtual void initialise (PartBunchBase< double, 3 > *bunch, std::shared_ptr< AbstractTimeDependence > freq_atd, std::shared_ptr< AbstractTimeDependence > ampl_atd, std::shared_ptr< AbstractTimeDependence > phase_atd)
virtual void setDesignEnergy (const double &ekin, bool changeable=true) override
virtual double getDesignEnergy () const override
void setRmin (double rmin)
void setRmax (double rmax)
void setAzimuth (double angle)
void setPerpenDistance (double pdis)
void setGapWidth (double gapwidth)
void setPhi0 (double phi0)
virtual double getRmin () const
virtual double getRmax () const
virtual double getAzimuth () const
virtual double getCosAzimuth () const
virtual double getSinAzimuth () const
virtual double getPerpenDistance () const
virtual double getGapWidth () const
virtual double getPhi0 () const
virtual void setComponentType (std::string name) override
virtual std::string getComponentType () const override
virtual double getCycFrequency () const
void getMomentaKick (const double normalRadius, double momentum[], const double t, const double dtCorrt, const int PID, const double restMass, const int chargenumber)
used in OPAL-cycl
double spline (double z, double *za)
void setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setAmplitudeModelName (std::string name)
std::string getAmplitudeModelName ()
void setPhaseModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setPhaseModelName (std::string name)
std::string getPhaseModelName ()
void setFrequencyModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setFrequencyModelName (std::string name)
std::string getFrequencyModelName ()
virtual double getElementLength () const override
Get design length.
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
virtual EMField & getField ()=0
Return field.
virtual const EMField & getField () const =0
Return field.
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual void setElementLength (double length)
Set design length.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
double getdE (const int &i, const int &I, const std::vector< double > &t, const double &phi, const std::vector< std::pair< double, double > > &F) const
double getdT (const int &i, const int &I, const std::vector< double > &E, const std::vector< std::pair< double, double > > &F, const double mass) const
double getdA (const int &i, const int &I, const std::vector< double > &t, const double &phi, const std::vector< std::pair< double, double > > &F) const
double getdB (const int &i, const int &I, const std::vector< double > &t, const double &phi, const std::vector< std::pair< double, double > > &F) const
void operator= (const TravelingWave &)
Private Attributes
double scaleCore_m
double scaleCoreError_m
double phaseCore1_m
double phaseCore2_m
double phaseExit_m
double startCoreField_m
double startExitField_m
double mappedStartExitField_m
double PeriodLength_m
int NumCells_m
double CellLength_m
double Mode_m
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from RFCavity
std::shared_ptr< AbstractTimeDependence > phase_td_m
std::string phase_name_m
std::shared_ptr< AbstractTimeDependence > amplitude_td_m
std::string amplitude_name_m
std::shared_ptr< AbstractTimeDependence > frequency_td_m
std::string frequency_name_m
std::string filename_m
double scale_m
double scaleError_m
double phase_m
double phaseError_m
double frequency_m
bool fast_m
bool autophaseVeto_m
double designEnergy_m
Fieldmap * fieldmap_m
double startField_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Interface for Traveling Wave.
Definition at line 37 of file TravelingWave.h.
Member Enumeration Documentation
CavityType
enum TravelingWave::CavityType
Enumerator
SW
TW
Definition at line 41 of file TravelingWave.h.
Constructor & Destructor Documentation
TravelingWave() [1/3]
TravelingWave::TravelingWave (const std::string & name) explicit
Constructor with given name.
Definition at line 60 of file TravelingWave.cpp.
TravelingWave() [2/3]
TravelingWave::TravelingWave ()
Definition at line 38 of file TravelingWave.cpp.
TravelingWave() [3/3]
TravelingWave::TravelingWave (const TravelingWave & right)
Definition at line 43 of file TravelingWave.cpp.
~TravelingWave()
TravelingWave::~TravelingWave () virtual
Definition at line 77 of file TravelingWave.cpp.
Member Function Documentation
accept()
void TravelingWave::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to TravelingWave.
Reimplemented from RFCavity.
Definition at line 81 of file TravelingWave.cpp.
References BeamlineVisitor::visitTravelingWave().
apply() [1/2]
bool TravelingWave::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from RFCavity.
Definition at line 85 of file TravelingWave.cpp.
References PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::R, and Component::RefPartBunch_m.
apply() [2/2]
bool TravelingWave::apply (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from RFCavity.
Definition at line 89 of file TravelingWave.cpp.
References CellLength_m, cos(), RFCavity::fieldmap_m, floor(), RFCavity::frequency_m, RFCavity::getElementLength(), Fieldmap::getFieldstrength(), Fieldmap::isInside(), mappedStartExitField_m, PeriodLength_m, RFCavity::phase_m, phaseCore1_m, phaseCore2_m, RFCavity::phaseError_m, phaseExit_m, Attrib::Distribution::R, RFCavity::scale_m, scaleCore_m, scaleCoreError_m, RFCavity::scaleError_m, sin(), startCoreField_m, and startExitField_m.
applyToReferenceParticle()
bool TravelingWave::applyToReferenceParticle (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from RFCavity.
Definition at line 141 of file TravelingWave.cpp.
References CellLength_m, cos(), RFCavity::fieldmap_m, floor(), RFCavity::frequency_m, RFCavity::getElementLength(), Fieldmap::getFieldstrength(), Fieldmap::isInside(), mappedStartExitField_m, PeriodLength_m, RFCavity::phase_m, phaseCore1_m, phaseCore2_m, phaseExit_m, Attrib::Distribution::R, RFCavity::scale_m, scaleCore_m, sin(), startCoreField_m, and startExitField_m.
bends()
bool TravelingWave::bends () const override virtual
Reimplemented from RFCavity.
Definition at line 233 of file TravelingWave.cpp.
finalise()
void TravelingWave::finalise () override virtual
Reimplemented from RFCavity.
Definition at line 230 of file TravelingWave.cpp.
getAmplitude()
virtual double TravelingWave::getAmplitude () const override pure virtual
Get RF amplitude.
Implements RFCavity.
Implemented in TravelingWaveRep.
getAutoPhaseEstimate()
double TravelingWave::getAutoPhaseEstimate (const double & E0, const double & t0, const double & q, const double & m) override virtual
Reimplemented from RFCavity.
Definition at line 263 of file TravelingWave.cpp.
References abs(), atan(), cos(), endl(), RFCavity::fieldmap_m, floor(), RFCavity::frequency_m, getdA(), getdB(), getdE(), getdT(), Fieldmap::getOnaxisEz(), IpplInfo::Info, INFOMSG, level2(), Mode_m, NumCells_m, RFCavity::phase_m, phaseCore1_m, phaseCore2_m, phaseExit_m, Physics::pi, Inform::precision(), Physics::rad2deg, RFCavity::scale_m, scaleCore_m, sin(), and Physics::two_pi.
getdA()
double TravelingWave::getdA (const int & i, const int & I, const std::vector< double > & t, const double & phi, const std::vector< std::pair< double, double > > & F) const inline private
Definition at line 179 of file TravelingWave.h.
References cos(), RFCavity::frequency_m, and sin().
Referenced by getAutoPhaseEstimate().
getdB()
double TravelingWave::getdB (const int & i, const int & I, const std::vector< double > & t, const double & phi, const std::vector< std::pair< double, double > > & F) const inline private
Definition at line 190 of file TravelingWave.h.
References cos(), RFCavity::frequency_m, and sin().
Referenced by getAutoPhaseEstimate().
getdE()
double TravelingWave::getdE (const int & i, const int & I, const std::vector< double > & t, const double & phi, const std::vector< std::pair< double, double > > & F) const inline private
Definition at line 141 of file TravelingWave.h.
References cos(), RFCavity::frequency_m, and sin().
Referenced by getAutoPhaseEstimate().
getDimensions()
void TravelingWave::getDimensions (double & zBegin, double & zEnd) const override virtual
Reimplemented from RFCavity.
Definition at line 247 of file TravelingWave.cpp.
References RFCavity::getElementLength(), and PeriodLength_m.
getdT()
double TravelingWave::getdT (const int & i, const int & I, const std::vector< double > & E, const std::vector< std::pair< double, double > > & F, const double mass) const inline private
Definition at line 151 of file TravelingWave.h.
References Physics::c, and sqrt().
Referenced by getAutoPhaseEstimate().
getEdgeToBegin()
CoordinateSystemTrafo TravelingWave::getEdgeToBegin () const inline override virtual
Reimplemented from RFCavity.
Definition at line 220 of file TravelingWave.h.
References PeriodLength_m.
getEdgeToEnd()
CoordinateSystemTrafo TravelingWave::getEdgeToEnd () const inline override virtual
Reimplemented from RFCavity.
Definition at line 227 of file TravelingWave.h.
References RFCavity::getElementLength(), and PeriodLength_m.
getElementDimensions()
void TravelingWave::getElementDimensions (double & begin, double & end) const override virtual
Reimplemented from RFCavity.
Definition at line 253 of file TravelingWave.cpp.
References begin(), end(), RFCavity::getElementLength(), and PeriodLength_m.
getFrequency()
virtual double TravelingWave::getFrequency () const override pure virtual
Get RF frequencey.
Implements RFCavity.
Implemented in TravelingWaveRep.
getPhase()
virtual double TravelingWave::getPhase () const override pure virtual
Get RF phase.
Implements RFCavity.
Implemented in TravelingWaveRep.
getType()
ElementBase::ElementType TravelingWave::getType () const override virtual
Get element type std::string.
Reimplemented from RFCavity.
Definition at line 259 of file TravelingWave.cpp.
References ElementBase::TRAVELINGWAVE.
goOffline()
void TravelingWave::goOffline () override virtual
Reimplemented from RFCavity.
Definition at line 243 of file TravelingWave.cpp.
References RFCavity::filename_m, and Fieldmap::freeMap().
goOnline()
void TravelingWave::goOnline (const double & kineticEnergy) override virtual
Reimplemented from RFCavity.
Definition at line 238 of file TravelingWave.cpp.
References RFCavity::filename_m, Component::online_m, and Fieldmap::readMap().
initialise()
void TravelingWave::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Reimplemented from RFCavity.
Definition at line 193 of file TravelingWave.cpp.
References abs(), CellLength_m, floor(), gmsg, RFCavity::initialise(), mappedStartExitField_m, Mode_m, NumCells_m, PeriodLength_m, RFCavity::phase_m, phaseCore1_m, phaseCore2_m, phaseExit_m, Physics::pi, Component::RefPartBunch_m, RFCavity::scale_m, scaleCore_m, scaleCoreError_m, RFCavity::scaleError_m, ElementBase::setElementLength(), sin(), startCoreField_m, startExitField_m, RFCavity::startField_m, and Physics::two_pi.
isInside()
bool TravelingWave::isInside (const Vector_t & r) const override virtual
Reimplemented from RFCavity.
Definition at line 397 of file TravelingWave.cpp.
References ElementBase::isInsideTransverse(), PeriodLength_m, and startExitField_m.
operator=()
void TravelingWave::operator= (const TravelingWave &) private
setMode()
void TravelingWave::setMode (double mode) inline
Definition at line 215 of file TravelingWave.h.
References Mode_m.
Referenced by OpalTravelingWave::update().
setNumCells()
void TravelingWave::setNumCells (int NumCells) inline
Definition at line 210 of file TravelingWave.h.
References NumCells_m.
Referenced by OpalTravelingWave::update().
setPhasem()
void TravelingWave::setPhasem (double phase) inline override virtual
Reimplemented from RFCavity.
Definition at line 202 of file TravelingWave.h.
References floor(), Mode_m, NumCells_m, RFCavity::phase_m, phaseCore1_m, phaseCore2_m, phaseExit_m, Physics::pi, and Physics::two_pi.
Referenced by OpalTravelingWave::update().
Member Data Documentation
CellLength_m
double TravelingWave::CellLength_m private
Definition at line 111 of file TravelingWave.h.
Referenced by apply(), applyToReferenceParticle(), and initialise().
mappedStartExitField_m
double TravelingWave::mappedStartExitField_m private
Definition at line 107 of file TravelingWave.h.
Referenced by apply(), applyToReferenceParticle(), and initialise().
Mode_m
double TravelingWave::Mode_m private
Definition at line 112 of file TravelingWave.h.
Referenced by getAutoPhaseEstimate(), initialise(), setMode(), and setPhasem().
NumCells_m
int TravelingWave::NumCells_m private
Definition at line 110 of file TravelingWave.h.
Referenced by getAutoPhaseEstimate(), initialise(), setNumCells(), and setPhasem().
PeriodLength_m
double TravelingWave::PeriodLength_m private
Definition at line 109 of file TravelingWave.h.
Referenced by apply(), applyToReferenceParticle(), getDimensions(), getEdgeToBegin(), getEdgeToEnd(), getElementDimensions(), initialise(), and isInside().
phaseCore1_m
double TravelingWave::phaseCore1_m private
Definition at line 101 of file TravelingWave.h.
Referenced by apply(), applyToReferenceParticle(), getAutoPhaseEstimate(), initialise(), and setPhasem().
phaseCore2_m
double TravelingWave::phaseCore2_m private
Definition at line 102 of file TravelingWave.h.
Referenced by apply(), applyToReferenceParticle(), getAutoPhaseEstimate(), initialise(), and setPhasem().
phaseExit_m
double TravelingWave::phaseExit_m private
Definition at line 103 of file TravelingWave.h.
Referenced by apply(), applyToReferenceParticle(), getAutoPhaseEstimate(), initialise(), and setPhasem().
scaleCore_m
double TravelingWave::scaleCore_m private
Definition at line 98 of file TravelingWave.h.
Referenced by apply(), applyToReferenceParticle(), getAutoPhaseEstimate(), and initialise().
scaleCoreError_m
double TravelingWave::scaleCoreError_m private
Definition at line 99 of file TravelingWave.h.
Referenced by apply(), and initialise().
startCoreField_m
double TravelingWave::startCoreField_m private
starting point of field(m)
Definition at line 105 of file TravelingWave.h.
Referenced by apply(), applyToReferenceParticle(), and initialise().
startExitField_m
double TravelingWave::startExitField_m private
Definition at line 106 of file TravelingWave.h.
Referenced by apply(), applyToReferenceParticle(), initialise(), and isInside().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/TravelingWave.h
src/Classic/AbsBeamline/TravelingWave.cpp