OPAL (Object Oriented Parallel Accelerator Library): AbsFileStream Class Reference
AbsFileStream Class Reference abstract
A stream of input tokens.
#include <AbsFileStream.h>
Public Member Functions
AbsFileStream (const std::string &name)
Constructor.
virtual ~AbsFileStream ()
virtual bool fillLine ()=0
Read next input line.
virtual Token readToken ()
Read single token from file.
Public Member Functions inherited from TokenStream
TokenStream (const std::string &name)
Constructor.
virtual ~TokenStream ()
void putBack (const Token &token)
Put token back to stream.
const std::string & getName () const
Return stream name.
int getLine () const
Return line number.
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Member Functions
Token readNumber ()
Token readString ()
Token readWord ()
bool skipComments ()
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes
std::string line
int curr_char
Protected Attributes inherited from TokenStream
std::string stream_name
int curr_line
bool put_back_flag
Token put_back
Private Member Functions
AbsFileStream ()
AbsFileStream (const AbsFileStream &)
void operator= (const AbsFileStream &)
Detailed Description
A stream of input tokens.
Definition at line 31 of file AbsFileStream.h.
Constructor & Destructor Documentation
AbsFileStream() [1/3]
AbsFileStream::AbsFileStream (const std::string & name) explicit
Constructor.
Definition at line 31 of file AbsFileStream.cpp.
~AbsFileStream()
AbsFileStream::~AbsFileStream () virtual
Definition at line 38 of file AbsFileStream.cpp.
AbsFileStream() [2/3]
AbsFileStream::AbsFileStream () private
AbsFileStream() [3/3]
AbsFileStream::AbsFileStream (const AbsFileStream &) private
Member Function Documentation
fillLine()
virtual bool AbsFileStream::fillLine () pure virtual
Read next input line.
Implemented in FileStream.
Referenced by readToken(), and skipComments().
operator=()
void AbsFileStream::operator= (const AbsFileStream &) private
readNumber()
Token AbsFileStream::readNumber () protected
Definition at line 144 of file AbsFileStream.cpp.
References curr_char, TokenStream::curr_line, Token::IS_ERROR, line, and TokenStream::stream_name.
Referenced by readToken().
readString()
Token AbsFileStream::readString () protected
Definition at line 232 of file AbsFileStream.cpp.
References curr_char, TokenStream::curr_line, Token::IS_ERROR, Token::IS_STRING, line, and TokenStream::stream_name.
Referenced by readToken().
readToken()
Token AbsFileStream::readToken () virtual
Read single token from file.
Implements TokenStream.
Definition at line 42 of file AbsFileStream.cpp.
References curr_char, TokenStream::curr_line, fillLine(), Token::IS_DELIMITER, Token::IS_EOF, Token::IS_ERROR, line, TokenStream::put_back, TokenStream::put_back_flag, readNumber(), readString(), readWord(), skipComments(), and TokenStream::stream_name.
readWord()
Token AbsFileStream::readWord () protected
Definition at line 260 of file AbsFileStream.cpp.
References curr_char, TokenStream::curr_line, Token::IS_WORD, line, and TokenStream::stream_name.
Referenced by readToken().
skipComments()
bool AbsFileStream::skipComments () protected
Definition at line 278 of file AbsFileStream.cpp.
References curr_char, fillLine(), and line.
Referenced by readToken().
Member Data Documentation
curr_char
int AbsFileStream::curr_char protected
Definition at line 64 of file AbsFileStream.h.
Referenced by FileStream::fillLine(), readNumber(), readString(), readToken(), readWord(), and skipComments().
line
std::string AbsFileStream::line protected
Definition at line 63 of file AbsFileStream.h.
Referenced by FileStream::fillLine(), readNumber(), readString(), readToken(), readWord(), and skipComments().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Parser/AbsFileStream.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Parser/AbsFileStream.cpp