OPAL (Object Oriented Parallel Accelerator Library): AttributeBase Class Reference
AttributeBase Class Reference abstract
Abstract base class for attribute values of different types.
#include <AttributeBase.h>
Public Member Functions
AttributeBase ()
virtual ~AttributeBase ()
virtual AttributeBase * clone () const =0
Make clone.
std::string getImage () const
Convert to string.
virtual bool isExpression () const
Test for expression.
virtual void print (std::ostream &) const =0
Print value.
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Public Member Functions inherited from Invalidator
virtual void invalidate ()
Force re-evaluation.
Private Member Functions
AttributeBase (AttributeBase &)
void operator= (AttributeBase &)
Additional Inherited Members
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Detailed Description
Abstract base class for attribute values of different types.
Definition at line 32 of file AttributeBase.h.
Constructor & Destructor Documentation
AttributeBase() [1/2]
AttributeBase::AttributeBase ()
Definition at line 25 of file AttributeBase.cpp.
~AttributeBase()
AttributeBase::~AttributeBase () virtual
Definition at line 30 of file AttributeBase.cpp.
AttributeBase() [2/2]
AttributeBase::AttributeBase (AttributeBase &) private
Member Function Documentation
clone()
virtual AttributeBase* AttributeBase::clone () const pure virtual
Make clone.
Implemented in Expressions::ADeferred< T >, Expressions::SRefAttr< T >, Expressions::AAutomatic< T >, Expressions::AValue< T >, Expressions::SDeferred< T >, Expressions::SAutomatic< T >, and Expressions::SValue< T >.
getImage()
std::string AttributeBase::getImage () const
Convert to string.
Definition at line 34 of file AttributeBase.cpp.
References print().
Referenced by Attribute::getImage().
isExpression()
bool AttributeBase::isExpression () const virtual
Test for expression.
Reimplemented in Expressions::ADeferred< T >, and Expressions::SDeferred< T >.
Definition at line 42 of file AttributeBase.cpp.
Referenced by Attribute::isExpression(), and OpalElement::printMultipoleStrength().
operator=()
void AttributeBase::operator= (AttributeBase &) private
print()
virtual void AttributeBase::print (std::ostream &) const pure virtual
Print value.
Implemented in Expressions::AValue< T >, Expressions::AValue< T >, Expressions::SValue< T >, Expressions::SValue< T >, Expressions::AValue< T >, Expressions::SValue< T >, Expressions::AValue< T >, Expressions::SRefAttr< T >, Expressions::ADeferred< T >, Expressions::SDeferred< T >, Expressions::AValue< T >, and Expressions::SValue< T >.
Referenced by getImage(), and operator<<().
The documentation for this class was generated from the following files:
src/AbstractObjects/AttributeBase.h
src/AbstractObjects/AttributeBase.cpp