OPAL (Object Oriented Parallel Accelerator Library): IndexedBareFieldIterator< T, Dim > Class Template Reference
IndexedBareFieldIterator< T, Dim > Class Template Reference
#include <AssignDefs.h>
Public Types
enum { Dim_u = Dim }
typedef T return_type
Public Types inherited from BareFieldIterator< T, Dim >
typedef T return_type
Public Types inherited from BrickIterator< T, Dim >
typedef T PETE_Return_t
typedef BrickIterator< T, Dim > PETE_Expr_t
Public Member Functions
IndexedBareFieldIterator ()
IndexedBareFieldIterator (BareField< T, Dim > &df, const NDIndex< Dim > &idx)
~IndexedBareFieldIterator ()
const NDIndex< Dim > & getDomain () const
const BareField< T, Dim > & getBareField () const
BareField< T, Dim > & getBareField ()
template<unsigned D1, class T1 >
void FillGCIfNecessary (const BareField< T1, D1 > &lhs) const
template<unsigned int D2>
bool plugBase (const NDIndex< D2 > &i)
void SetCurrentLocation (const FieldLoc< Dim > &loc)
IndexedBareFieldIterator< T, Dim > & operator++ ()
void beginLField ()
Public Member Functions inherited from BareFieldIterator< T, Dim >
BareFieldIterator ()
BareFieldIterator (BareField< T, Dim > &df)
BareFieldIterator (const FieldLoc< Dim > &loc, BareField< T, Dim > &df)
BareFieldIterator (const BareFieldIterator< T, Dim > &iter)
~BareFieldIterator ()
const BareFieldIterator< T, Dim > & operator= (const BareFieldIterator< T, Dim > &rhs)
void SetCurrentLocation (const FieldLoc< Dim > &loc)
void GetCurrentLocation (FieldLoc< Dim > &loc) const
void GetCurrentLocation (int *loc) const
BareFieldIterator< T, Dim > & operator++ ()
T & operator* () const
void nextLField ()
bool done () const
bool done (unsigned d) const
void beginLField ()
bool IsCompressed () const
bool CanCompress () const
void Compress ()
void Compress (T val)
bool TryCompress ()
BareField< T, Dim > & GetBareField ()
const BareField< T, Dim > & GetBareField () const
void prepareForScalarCode (bool tryfill=true)
void finishScalarCode (bool modified=true)
Public Member Functions inherited from CompressedBrickIterator< T, Dim >
CompressedBrickIterator (T *t, const NDIndex< Dim > &c, const NDIndex< Dim > &a, T &compressed)
CompressedBrickIterator (T *t, const vec< int, Dim > &v, T &compressed)
CompressedBrickIterator (T &t)
CompressedBrickIterator ()
CompressedBrickIterator (const NDIndex< Dim > &a, T &compressed)
CompressedBrickIterator (const BrickIterator< T, Dim > &x, T &compressed)
bool IsCompressed () const
bool CanCompress (const T &) const
void Compress (T &val)
bool TryCompress ()
bool TryCompress (T val)
const CompressedBrickIterator< T, Dim > & operator= (const CompressedBrickIterator< T, Dim > &rhs)
CompressedBrickIterator (const CompressedBrickIterator< T, Dim > &X)
Message & putMessage (Message &m, bool makecopy=true)
Message & getMessage (Message &m)
CompressedBrickIterator< T, 1 > permute (NDIndex< Dim > &current, NDIndex< 1 > &permuted) const
CompressedBrickIterator< T, 2 > permute (NDIndex< Dim > &current, NDIndex< 2 > &permuted) const
CompressedBrickIterator< T, 3 > permute (NDIndex< Dim > &current, NDIndex< 3 > &permuted) const
CompressedBrickIterator< T, 4 > permute (NDIndex< Dim > &current, NDIndex< 4 > &permuted) const
CompressedBrickIterator< T, 5 > permute (NDIndex< Dim > &current, NDIndex< 5 > &permuted) const
CompressedBrickIterator< T, 6 > permute (NDIndex< Dim > &current, NDIndex< 6 > &permuted) const
void SetCurrent (T *p)
void SetCount (int d, int count)
void ResetCounter (int d)
void SetStride (int d, int stride)
int GetStride (int d) const
T & GetCompressedData () const
void SetCompressedData (T *newData)
Public Member Functions inherited from BrickIterator< T, Dim >
BrickIterator ()
BrickIterator (T *, const NDIndex< Dim > &, const NDIndex< Dim > &)
BrickIterator (T *, const vec< int, Dim > &)
BrickIterator & operator++ ()
bool whole () const
bool operator== (const BrickIterator< T, Dim > &a) const
bool operator!= (const BrickIterator< T, Dim > &a) const
T & operator* () const
void step (unsigned d)
void rewind (unsigned d)
T & offset (int i) const
T & offset (int i, int j) const
T & offset (int i, int j, int k) const
T & offset (int *i) const
T & unit_offset (int i) const
T & unit_offset (int i, int j) const
T & unit_offset (int i, int j, int k) const
void moveBy (int i)
void moveBy (int i, int j)
void moveBy (int i, int j, int k)
void moveBy (const int *i)
int Stride (int i) const
Message & putMessage (Message &, bool makecopy=true)
Message & getMessage (Message &)
PETE_Expr_t MakeExpression () const
Public Member Functions inherited from BrickCounter< Dim >
BrickCounter ()
BrickCounter (const NDIndex< Dim > &)
BrickCounter & operator++ ()
bool done (unsigned d) const
void step (unsigned d)
void rewind (unsigned d)
int size (unsigned d) const
int GetOffset (unsigned d) const
Protected Member Functions
void general_increment ()
Protected Member Functions inherited from BareFieldIterator< T, Dim >
void general_increment ()
bool isInGC () const
Protected Member Functions inherited from BrickIterator< T, Dim >
void op_pp ()
Protected Member Functions inherited from BrickCounter< Dim >
void op_pp ()
Protected Attributes
NDIndex< Dim > I
Protected Attributes inherited from BareFieldIterator< T, Dim >
BareField< T, Dim >::iterator_if CurrentLField
BareField< T, Dim > * MyBareField
T dummy_compressed_data
int LFIndex
Protected Attributes inherited from BrickIterator< T, Dim >
T *__restrict__ Current
vec< int, Dim > Strides
bool Whole
Protected Attributes inherited from BrickCounter< Dim >
vec< int, Dim > Counters
vec< int, Dim > Counts
Detailed Description
template<class T, unsigned Dim>
class IndexedBareFieldIterator< T, Dim >
Definition at line 20 of file AssignDefs.h.
Member Typedef Documentation
return_type
template<class T, unsigned Dim> typedef T IndexedBareFieldIterator< T, Dim >::return_type
Definition at line 42 of file IndexedBareField.h.
Member Enumeration Documentation
anonymous enum
template<class T, unsigned Dim> anonymous enum
Enumerator
Dim_u
Definition at line 41 of file IndexedBareField.h.
Constructor & Destructor Documentation
IndexedBareFieldIterator() [1/2]
template<class T, unsigned Dim> IndexedBareFieldIterator< T, Dim >::IndexedBareFieldIterator () inline
Definition at line 45 of file IndexedBareField.h.
IndexedBareFieldIterator() [2/2]
template<class T, unsigned Dim> IndexedBareFieldIterator< T, Dim >::IndexedBareFieldIterator (BareField< T, Dim > & df, const NDIndex< Dim > & idx) inline
Definition at line 51 of file IndexedBareField.h.
References IndexedBareFieldIterator< T, Dim >::beginLField().
~IndexedBareFieldIterator()
template<class T, unsigned Dim> IndexedBareFieldIterator< T, Dim >::~IndexedBareFieldIterator () inline
Definition at line 60 of file IndexedBareField.h.
Member Function Documentation
beginLField()
template<class T, unsigned Dim> void IndexedBareFieldIterator< T, Dim >::beginLField () inline
Definition at line 157 of file IndexedBareField.h.
References Physics::c, BareFieldIterator< T, Dim >::done(), IndexedBareFieldIterator< T, Dim >::I, and BareFieldIterator< T, Dim >::nextLField().
Referenced by IndexedBareFieldIterator< T, Dim >::general_increment(), and IndexedBareFieldIterator< T, Dim >::IndexedBareFieldIterator().
FillGCIfNecessary()
template<class T, unsigned Dim> template<unsigned D1, class T1 > void IndexedBareFieldIterator< T, Dim >::FillGCIfNecessary (const BareField< T1, D1 > & lhs) const inline
Definition at line 76 of file IndexedBareField.h.
References BareField< T, Dim >::fillGuardCells(), IndexedBareFieldIterator< T, Dim >::getBareField(), BareFieldIterator< T, Dim >::GetBareField(), IndexedBareFieldIterator< T, Dim >::getDomain(), BareField< T, Dim >::getDomain(), BareField< T, Dim >::getLayout(), and isStencil().
Referenced by for_each().
general_increment()
template<class T, unsigned Dim> void IndexedBareFieldIterator< T, Dim >::general_increment () inline protected
Definition at line 184 of file IndexedBareField.h.
References IndexedBareFieldIterator< T, Dim >::beginLField(), and BareFieldIterator< T, Dim >::nextLField().
Referenced by IndexedBareFieldIterator< T, Dim >::operator++().
getBareField() [1/2]
template<class T, unsigned Dim> const BareField<T,Dim>& IndexedBareFieldIterator< T, Dim >::getBareField () const inline
Definition at line 71 of file IndexedBareField.h.
References BareFieldIterator< T, Dim >::MyBareField.
Referenced by IndexedBareFieldIterator< T, Dim >::FillGCIfNecessary().
getBareField() [2/2]
template<class T, unsigned Dim> BareField<T,Dim>& IndexedBareFieldIterator< T, Dim >::getBareField () inline
Definition at line 72 of file IndexedBareField.h.
References BareFieldIterator< T, Dim >::MyBareField.
getDomain()
template<class T, unsigned Dim> const NDIndex<Dim>& IndexedBareFieldIterator< T, Dim >::getDomain (void) const inline
Definition at line 65 of file IndexedBareField.h.
References IndexedBareFieldIterator< T, Dim >::I.
Referenced by IndexedBareFieldIterator< T, Dim >::FillGCIfNecessary(), and for_each().
operator++()
template<class T, unsigned Dim> IndexedBareFieldIterator<T,Dim>& IndexedBareFieldIterator< T, Dim >::operator++ () inline
Definition at line 146 of file IndexedBareField.h.
References IndexedBareFieldIterator< T, Dim >::general_increment(), and BrickIterator< T, Dim >::operator++().
plugBase()
template<class T, unsigned Dim> template<unsigned int D2> bool IndexedBareFieldIterator< T, Dim >::plugBase (const NDIndex< D2 > & i) inline
Definition at line 106 of file IndexedBareField.h.
References Physics::e, and IndexedBareFieldIterator< T, Dim >::I.
Referenced by for_each().
SetCurrentLocation()
template<class T, unsigned Dim> void IndexedBareFieldIterator< T, Dim >::SetCurrentLocation (const FieldLoc< Dim > & loc) inline
Definition at line 135 of file IndexedBareField.h.
References BareFieldIterator< T, Dim >::done(), BareFieldIterator< T, Dim >::GetCurrentLocation(), FieldLoc< Dim >::getDomain(), IndexedBareFieldIterator< T, Dim >::I, and PAssert.
Member Data Documentation
I
template<class T, unsigned Dim> NDIndex<Dim> IndexedBareFieldIterator< T, Dim >::I protected
Definition at line 181 of file IndexedBareField.h.
Referenced by IndexedBareFieldIterator< T, Dim >::beginLField(), IndexedBareFieldIterator< T, Dim >::getDomain(), IndexedBareFieldIterator< T, Dim >::plugBase(), and IndexedBareFieldIterator< T, Dim >::SetCurrentLocation().
The documentation for this class was generated from the following files:
ippl/src/Field/AssignDefs.h
ippl/src/Field/IndexedBareField.h