OPAL (Object Oriented Parallel Accelerator Library): ippl/src/PETE/PETE.h File Reference
PETE.h File Reference
#include "PETE/TypeComputations.h"
#include "Utility/PAssert.h"
#include <cstdlib>
Classes
class PETE_Expr< WrappedExpr >
class PETE_Scalar< T >
struct EvalFunctor_0
struct PETE_Increment
struct PETE_CountElems
struct PETE_TUTree< Value_t, Child_t >
struct PETE_TBTree< Value_t, Left_t, Right_t >
class PETE_TTTree< Value_t, Left_t, Middle_t, Right_t >
struct PETE_Combiner< T, Op >
struct AssertEquals
struct PETE_NullCombiner
struct struct_for_each< Op, T1, T2, Functor >
struct ConditionalAssign< T >
struct struct_for_each< OpWhere, T1, T2, Functor >
struct SafeCombine< I1, I2 >
struct SafeCombine< 0, 0 >
struct SafeCombine< 1, 0 >
struct SafeCombine< 0, 1 >
struct SafeCombine< 1, 1 >
struct SafeExpression< Expr >
struct SafeExpression< PETE_TUTree< Op, Sub > >
struct SafeExpression< PETE_TBTree< Op, Left, Right > >
struct SafeExpression< PETE_TTTree< Op, Left, Middle, Right > >
struct SafeExpression< PETE_TBTree< OpDivide, Left, Right > >
struct TrinaryForEach< Safe, T1, T2, T3, Op, Functor >
struct TrinaryForEach< 0, T1, T2, T3, OpWhere, Functor >
struct PETE_StructApply< Op, T1, T2 >
struct PETE_StructApply< OpAssign, T1, T2 >
struct PETE_StructApply< OpAssign, T1, ConditionalAssign< T2 > >
struct PETE_StructApply< OpAddAssign, T1, T2 >
struct PETE_StructApply< OpAddAssign, T1, ConditionalAssign< T2 > >
struct PETE_StructApply< OpSubtractAssign, T1, T2 >
struct PETE_StructApply< OpSubtractAssign, T1, ConditionalAssign< T2 > >
struct PETE_StructApply< OpMultipplyAssign, T1, T2 >
struct PETE_StructApply< OpMultipplyAssign, T1, ConditionalAssign< T2 > >
struct PETE_StructApply< OpDivideAssign, T1, T2 >
struct PETE_StructApply< OpDivideAssign, T1, ConditionalAssign< T2 > >
struct PETE_StructApply< OpModAssign, T1, T2 >
struct PETE_StructApply< OpModAssign, T1, ConditionalAssign< T2 > >
struct PETE_StructApply< OpBitwiseOrAssign, T1, T2 >
struct PETE_StructApply< OpBitwiseOrAssign, T1, ConditionalAssign< T2 > >
struct PETE_StructApply< OpBitwiseAndAssign, T1, T2 >
struct PETE_StructApply< OpBitwiseAndAssign, T1, ConditionalAssign< T2 > >
struct PETE_StructApply< OpBitwiseXorAssign, T1, T2 >
struct PETE_StructApply< OpBitwiseXorAssign, T1, ConditionalAssign< T2 > >
struct PETE_StructApply< OpLeftShiftAssign, T1, T2 >
struct PETE_StructApply< OpLeftShiftAssign, T1, ConditionalAssign< T2 > >
struct PETE_StructApply< OpRightShiftAssign, T1, T2 >
struct PETE_StructApply< OpRightShiftAssign, T1, ConditionalAssign< T2 > >
struct Expressionize< T >
struct Expressionize< PETE_Expr< T > >
Macros
#define PETE_USER_REDUCTION_CODE
#define PETE_DefineUnary(Fun, Expr, Op)
#define PETE_DefineBinary(Fun, Expr, Op)
#define PETE_DefineBinarySynonym(Fun, Op)
#define PETE_DefineBinaryWithScalars(Fun, Op, Sca)
#define PETE_DefineTrinary(Fun, Expr, Op)
#define PETE_DefineTrinaryWithScalars(Fun, Op, Sca)
#define PETE_DefineScalar(Sca)
#define PETE_DefineAssign(Expr, Cond, Op)
#define UNARY_FUNCTION(RET, FUNC, ARG)
#define BINARY_FUNCTION(RET, FUNC, ARG1, ARG2)
Typedefs
typedef PETE_Combiner< bool, OpAnd > PETE_AndCombiner
typedef PETE_Combiner< bool, OpOr > PETE_OrCombiner
typedef PETE_Combiner< int, OpAdd > PETE_SumCombiner
Functions
template<class T >
T for_each (const PETE_Scalar< T > &p, EvalFunctor_0)
template<class T , class C >
int for_each (PETE_Scalar< T > &, PETE_Increment, C)
template<class T , class C >
int for_each (const PETE_Scalar< T > &, PETE_CountElems, C)
template<class Op , class T1 , class Functor , class Combiner >
Functor::PETE_Return_t for_each (PETE_TUTree< Op, T1 > &node, Functor f, Combiner c)
template<class Op , class T1 , class T2 , class Functor , class Combiner >
Functor::PETE_Return_t for_each (PETE_TBTree< Op, T1, T2 > &node, Functor f, Combiner c)
template<class Op , class T1 , class T2 , class T3 , class Functor , class Combiner >
Functor::PETE_Return_t for_each (PETE_TTTree< Op, T1, T2, T3 > &node, Functor f, Combiner c)
template<class Op , class T1 , class Functor >
PETEUnaryReturn< typename T1::PETE_Return_t, Op >::type for_each (PETE_TUTree< Op, T1 > &node, Functor f)
template<class Op , class T1 , class T2 , class Functor >
struct_for_each< Op, T1, T2, Functor >::Return_t for_each (PETE_TBTree< Op, T1, T2 > &node, Functor f)
template<class T1 , class T2 , class T3 , class Functor , class Op >
PETETrinaryReturn< typename T1::PETE_Return_t, typename T2::PETE_Return_t, typename T3::PETE_Return_t, Op >::type for_each (PETE_TTTree< Op, T1, T2, T3 > &node, Functor f)
template<class R , class T , class InitOp , class AccOp >
void Reduction (R &ret, const PETE_Expr< T > &const_expr, InitOp init_op, AccOp acc_op)
template<class T >
PETEUnaryReturn< T, OpUnaryMinus >::type PETE_apply (OpUnaryMinus, const T &a)
template<class T >
PETE_TUTree< OpUnaryMinus, typename T::PETE_Expr_t > operator- (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, OpUnaryPlus >::type PETE_apply (OpUnaryPlus, const T &a)
template<class T >
PETE_TUTree< OpUnaryPlus, typename T::PETE_Expr_t > operator+ (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, OpBitwiseNot >::type PETE_apply (OpBitwiseNot, const T &a)
template<class T >
PETE_TUTree< OpBitwiseNot, typename T::PETE_Expr_t > operator~ (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, OpNot >::type PETE_apply (OpNot, const T &a)
template<class T >
PETE_TUTree< OpNot, typename T::PETE_Expr_t > operator! (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, OpIdentity >::type PETE_apply (OpIdentity, const T &a)
template<class T >
PETE_TUTree< OpIdentity, typename T::PETE_Expr_t > PETE_identity (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnArcCos >::type PETE_apply (FnArcCos, const T &a)
template<class T >
PETE_TUTree< FnArcCos, typename T::PETE_Expr_t > acos (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnArcSin >::type PETE_apply (FnArcSin, const T &a)
template<class T >
PETE_TUTree< FnArcSin, typename T::PETE_Expr_t > asin (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnArcTan >::type PETE_apply (FnArcTan, const T &a)
template<class T >
PETE_TUTree< FnArcTan, typename T::PETE_Expr_t > atan (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnCeil >::type PETE_apply (FnCeil, const T &a)
template<class T >
PETE_TUTree< FnCeil, typename T::PETE_Expr_t > ceil (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnCos >::type PETE_apply (FnCos, const T &a)
template<class T >
PETE_TUTree< FnCos, typename T::PETE_Expr_t > cos (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnHypCos >::type PETE_apply (FnHypCos, const T &a)
template<class T >
PETE_TUTree< FnHypCos, typename T::PETE_Expr_t > cosh (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnExp >::type PETE_apply (FnExp, const T &a)
template<class T >
PETE_TUTree< FnExp, typename T::PETE_Expr_t > exp (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnFabs >::type PETE_apply (FnFabs, const T &a)
template<class T >
PETE_TUTree< FnFabs, typename T::PETE_Expr_t > fabs (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnFloor >::type PETE_apply (FnFloor, const T &a)
template<class T >
PETE_TUTree< FnFloor, typename T::PETE_Expr_t > floor (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnLog >::type PETE_apply (FnLog, const T &a)
template<class T >
PETE_TUTree< FnLog, typename T::PETE_Expr_t > log (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnLog10 >::type PETE_apply (FnLog10, const T &a)
template<class T >
PETE_TUTree< FnLog10, typename T::PETE_Expr_t > log10 (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnSin >::type PETE_apply (FnSin, const T &a)
template<class T >
PETE_TUTree< FnSin, typename T::PETE_Expr_t > sin (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnHypSin >::type PETE_apply (FnHypSin, const T &a)
template<class T >
PETE_TUTree< FnHypSin, typename T::PETE_Expr_t > sinh (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnSqrt >::type PETE_apply (FnSqrt, const T &a)
template<class T >
PETE_TUTree< FnSqrt, typename T::PETE_Expr_t > sqrt (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnTan >::type PETE_apply (FnTan, const T &a)
template<class T >
PETE_TUTree< FnTan, typename T::PETE_Expr_t > tan (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnHypTan >::type PETE_apply (FnHypTan, const T &a)
template<class T >
PETE_TUTree< FnHypTan, typename T::PETE_Expr_t > tanh (const PETE_Expr< T > &l)
template<class T >
PETEUnaryReturn< T, FnErf >::type PETE_apply (FnErf, const T &a)
template<class T >
PETE_TUTree< FnErf, typename T::PETE_Expr_t > erf (const PETE_Expr< T > &l)
template<class T1 , class T2 >
T1 PETE_apply (OpCast< T1 >, const T2 &a)
template<class T1 , class Expr >
PETE_TUTree< OpCast< T1 >, typename Expr::PETE_Expr_t > pete_cast (const T1 &, const PETE_Expr< Expr > &l)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpAdd >::type PETE_apply (OpAdd, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpAdd, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator+ (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpSubtract >::type PETE_apply (OpSubtract, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpSubtract, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator- (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpMultipply >::type PETE_apply (OpMultipply, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpMultipply, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator* (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpDivide >::type PETE_apply (OpDivide, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpDivide, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator/ (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpMod >::type PETE_apply (OpMod, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpMod, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator% (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpLT >::type PETE_apply (OpLT, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpLT, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator< (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpLE >::type PETE_apply (OpLE, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpLE, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator<= (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpGT >::type PETE_apply (OpGT, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpGT, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator> (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpGE >::type PETE_apply (OpGE, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpGE, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator>= (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpEQ >::type PETE_apply (OpEQ, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpEQ, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator== (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpNE >::type PETE_apply (OpNE, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpNE, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator!= (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpAnd >::type PETE_apply (OpAnd, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpAnd, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator && (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpOr >::type PETE_apply (OpOr, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpOr, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator|| (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpBitwiseAnd >::type PETE_apply (OpBitwiseAnd, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpBitwiseAnd, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator & (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpBitwiseOr >::type PETE_apply (OpBitwiseOr, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpBitwiseOr, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator| (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, OpBitwiseXor >::type PETE_apply (OpBitwiseXor, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< OpBitwiseXor, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > operator^ (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, FnCopysign >::type PETE_apply (FnCopysign, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< FnCopysign, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > copysign (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, FnLdexp >::type PETE_apply (FnLdexp, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< FnLdexp, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > ldexp (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, FnPow >::type PETE_apply (FnPow, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< FnPow, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > pow (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, FnFmod >::type PETE_apply (FnFmod, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< FnFmod, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > fmod (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 >
PETEBinaryReturn< T1, T2, FnArcTan2 >::type PETE_apply (FnArcTan2, const T1 &a, const T2 &b)
template<class T1 , class T2 >
PETE_TBTree< FnArcTan2, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > atan2 (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , class T3 >
PETETrinaryReturn< T1, T2, T3, OpWhere >::type PETE_apply (OpWhere, const T1 &a, const T2 &b, const T3 &c)
template<class Cond_t , class True_t , class False_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > &c, const PETE_Expr< True_t > &t, const PETE_Expr< False_t > &f)
template<class T1 , class T2 >
PETE_TBTree< OpWhere, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t > where (const PETE_Expr< T1 > &l, const PETE_Expr< T2 > &r)
template<class T >
PETE_TBTree< OpAdd, PETE_Scalar< short >, typename T::PETE_Expr_t > operator+ (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpAdd, typename T::PETE_Expr_t, PETE_Scalar< short > > operator+ (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpSubtract, PETE_Scalar< short >, typename T::PETE_Expr_t > operator- (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpSubtract, typename T::PETE_Expr_t, PETE_Scalar< short > > operator- (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpMultipply, PETE_Scalar< short >, typename T::PETE_Expr_t > operator* (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpMultipply, typename T::PETE_Expr_t, PETE_Scalar< short > > operator* (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpDivide, PETE_Scalar< short >, typename T::PETE_Expr_t > operator/ (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpDivide, typename T::PETE_Expr_t, PETE_Scalar< short > > operator/ (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpMod, PETE_Scalar< short >, typename T::PETE_Expr_t > operator% (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpMod, typename T::PETE_Expr_t, PETE_Scalar< short > > operator% (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpLT, PETE_Scalar< short >, typename T::PETE_Expr_t > operator< (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpLT, typename T::PETE_Expr_t, PETE_Scalar< short > > operator< (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpLE, PETE_Scalar< short >, typename T::PETE_Expr_t > operator<= (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpLE, typename T::PETE_Expr_t, PETE_Scalar< short > > operator<= (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpGT, PETE_Scalar< short >, typename T::PETE_Expr_t > operator> (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpGT, typename T::PETE_Expr_t, PETE_Scalar< short > > operator> (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpGE, PETE_Scalar< short >, typename T::PETE_Expr_t > operator>= (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpGE, typename T::PETE_Expr_t, PETE_Scalar< short > > operator>= (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpEQ, PETE_Scalar< short >, typename T::PETE_Expr_t > operator== (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpEQ, typename T::PETE_Expr_t, PETE_Scalar< short > > operator== (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpNE, PETE_Scalar< short >, typename T::PETE_Expr_t > operator!= (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpNE, typename T::PETE_Expr_t, PETE_Scalar< short > > operator!= (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpAnd, PETE_Scalar< short >, typename T::PETE_Expr_t > operator && (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpAnd, typename T::PETE_Expr_t, PETE_Scalar< short > > operator && (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpOr, PETE_Scalar< short >, typename T::PETE_Expr_t > operator|| (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpOr, typename T::PETE_Expr_t, PETE_Scalar< short > > operator|| (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpBitwiseAnd, PETE_Scalar< short >, typename T::PETE_Expr_t > operator & (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseAnd, typename T::PETE_Expr_t, PETE_Scalar< short > > operator & (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpBitwiseOr, PETE_Scalar< short >, typename T::PETE_Expr_t > operator| (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseOr, typename T::PETE_Expr_t, PETE_Scalar< short > > operator| (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpBitwiseXor, PETE_Scalar< short >, typename T::PETE_Expr_t > operator^ (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseXor, typename T::PETE_Expr_t, PETE_Scalar< short > > operator^ (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< OpWhere, PETE_Scalar< short >, typename T::PETE_Expr_t > where (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpWhere, typename T::PETE_Expr_t, PETE_Scalar< short > > where (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< FnCopysign, PETE_Scalar< short >, typename T::PETE_Expr_t > copysign (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnCopysign, typename T::PETE_Expr_t, PETE_Scalar< short > > copysign (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< FnLdexp, PETE_Scalar< short >, typename T::PETE_Expr_t > ldexp (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnLdexp, typename T::PETE_Expr_t, PETE_Scalar< short > > ldexp (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< FnPow, PETE_Scalar< short >, typename T::PETE_Expr_t > pow (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnPow, typename T::PETE_Expr_t, PETE_Scalar< short > > pow (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< FnFmod, PETE_Scalar< short >, typename T::PETE_Expr_t > fmod (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnFmod, typename T::PETE_Expr_t, PETE_Scalar< short > > fmod (const PETE_Expr< T > &l, const short r)
template<class T >
PETE_TBTree< FnArcTan2, PETE_Scalar< short >, typename T::PETE_Expr_t > atan2 (const short l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnArcTan2, typename T::PETE_Expr_t, PETE_Scalar< short > > atan2 (const PETE_Expr< T > &l, const short r)
template<class Cond_t , class True_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< short > > where (const PETE_Expr< Cond_t > &c, const PETE_Expr< True_t > &t, short f)
template<class Cond_t , class False_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< short >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > &c, short t, const PETE_Expr< False_t > &f)
template<class Cond_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< short >, PETE_Scalar< short > > where (const PETE_Expr< Cond_t > &c, short t, short f)
template<class T >
PETE_TBTree< OpAdd, PETE_Scalar< int >, typename T::PETE_Expr_t > operator+ (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpAdd, typename T::PETE_Expr_t, PETE_Scalar< int > > operator+ (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpSubtract, PETE_Scalar< int >, typename T::PETE_Expr_t > operator- (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpSubtract, typename T::PETE_Expr_t, PETE_Scalar< int > > operator- (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpMultipply, PETE_Scalar< int >, typename T::PETE_Expr_t > operator* (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpMultipply, typename T::PETE_Expr_t, PETE_Scalar< int > > operator* (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpDivide, PETE_Scalar< int >, typename T::PETE_Expr_t > operator/ (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpDivide, typename T::PETE_Expr_t, PETE_Scalar< int > > operator/ (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpMod, PETE_Scalar< int >, typename T::PETE_Expr_t > operator% (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpMod, typename T::PETE_Expr_t, PETE_Scalar< int > > operator% (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpLT, PETE_Scalar< int >, typename T::PETE_Expr_t > operator< (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpLT, typename T::PETE_Expr_t, PETE_Scalar< int > > operator< (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpLE, PETE_Scalar< int >, typename T::PETE_Expr_t > operator<= (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpLE, typename T::PETE_Expr_t, PETE_Scalar< int > > operator<= (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpGT, PETE_Scalar< int >, typename T::PETE_Expr_t > operator> (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpGT, typename T::PETE_Expr_t, PETE_Scalar< int > > operator> (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpGE, PETE_Scalar< int >, typename T::PETE_Expr_t > operator>= (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpGE, typename T::PETE_Expr_t, PETE_Scalar< int > > operator>= (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpEQ, PETE_Scalar< int >, typename T::PETE_Expr_t > operator== (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpEQ, typename T::PETE_Expr_t, PETE_Scalar< int > > operator== (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpNE, PETE_Scalar< int >, typename T::PETE_Expr_t > operator!= (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpNE, typename T::PETE_Expr_t, PETE_Scalar< int > > operator!= (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpAnd, PETE_Scalar< int >, typename T::PETE_Expr_t > operator && (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpAnd, typename T::PETE_Expr_t, PETE_Scalar< int > > operator && (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpOr, PETE_Scalar< int >, typename T::PETE_Expr_t > operator|| (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpOr, typename T::PETE_Expr_t, PETE_Scalar< int > > operator|| (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpBitwiseAnd, PETE_Scalar< int >, typename T::PETE_Expr_t > operator & (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseAnd, typename T::PETE_Expr_t, PETE_Scalar< int > > operator & (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpBitwiseOr, PETE_Scalar< int >, typename T::PETE_Expr_t > operator| (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseOr, typename T::PETE_Expr_t, PETE_Scalar< int > > operator| (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpBitwiseXor, PETE_Scalar< int >, typename T::PETE_Expr_t > operator^ (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseXor, typename T::PETE_Expr_t, PETE_Scalar< int > > operator^ (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< OpWhere, PETE_Scalar< int >, typename T::PETE_Expr_t > where (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpWhere, typename T::PETE_Expr_t, PETE_Scalar< int > > where (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< FnCopysign, PETE_Scalar< int >, typename T::PETE_Expr_t > copysign (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnCopysign, typename T::PETE_Expr_t, PETE_Scalar< int > > copysign (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< FnLdexp, PETE_Scalar< int >, typename T::PETE_Expr_t > ldexp (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnLdexp, typename T::PETE_Expr_t, PETE_Scalar< int > > ldexp (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< FnPow, PETE_Scalar< int >, typename T::PETE_Expr_t > pow (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnPow, typename T::PETE_Expr_t, PETE_Scalar< int > > pow (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< FnFmod, PETE_Scalar< int >, typename T::PETE_Expr_t > fmod (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnFmod, typename T::PETE_Expr_t, PETE_Scalar< int > > fmod (const PETE_Expr< T > &l, const int r)
template<class T >
PETE_TBTree< FnArcTan2, PETE_Scalar< int >, typename T::PETE_Expr_t > atan2 (const int l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnArcTan2, typename T::PETE_Expr_t, PETE_Scalar< int > > atan2 (const PETE_Expr< T > &l, const int r)
template<class Cond_t , class True_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< int > > where (const PETE_Expr< Cond_t > &c, const PETE_Expr< True_t > &t, int f)
template<class Cond_t , class False_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< int >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > &c, int t, const PETE_Expr< False_t > &f)
template<class Cond_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< int >, PETE_Scalar< int > > where (const PETE_Expr< Cond_t > &c, int t, int f)
template<class T >
PETE_TBTree< OpAdd, PETE_Scalar< long >, typename T::PETE_Expr_t > operator+ (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpAdd, typename T::PETE_Expr_t, PETE_Scalar< long > > operator+ (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpSubtract, PETE_Scalar< long >, typename T::PETE_Expr_t > operator- (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpSubtract, typename T::PETE_Expr_t, PETE_Scalar< long > > operator- (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpMultipply, PETE_Scalar< long >, typename T::PETE_Expr_t > operator* (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpMultipply, typename T::PETE_Expr_t, PETE_Scalar< long > > operator* (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpDivide, PETE_Scalar< long >, typename T::PETE_Expr_t > operator/ (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpDivide, typename T::PETE_Expr_t, PETE_Scalar< long > > operator/ (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpMod, PETE_Scalar< long >, typename T::PETE_Expr_t > operator% (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpMod, typename T::PETE_Expr_t, PETE_Scalar< long > > operator% (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpLT, PETE_Scalar< long >, typename T::PETE_Expr_t > operator< (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpLT, typename T::PETE_Expr_t, PETE_Scalar< long > > operator< (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpLE, PETE_Scalar< long >, typename T::PETE_Expr_t > operator<= (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpLE, typename T::PETE_Expr_t, PETE_Scalar< long > > operator<= (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpGT, PETE_Scalar< long >, typename T::PETE_Expr_t > operator> (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpGT, typename T::PETE_Expr_t, PETE_Scalar< long > > operator> (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpGE, PETE_Scalar< long >, typename T::PETE_Expr_t > operator>= (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpGE, typename T::PETE_Expr_t, PETE_Scalar< long > > operator>= (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpEQ, PETE_Scalar< long >, typename T::PETE_Expr_t > operator== (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpEQ, typename T::PETE_Expr_t, PETE_Scalar< long > > operator== (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpNE, PETE_Scalar< long >, typename T::PETE_Expr_t > operator!= (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpNE, typename T::PETE_Expr_t, PETE_Scalar< long > > operator!= (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpAnd, PETE_Scalar< long >, typename T::PETE_Expr_t > operator && (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpAnd, typename T::PETE_Expr_t, PETE_Scalar< long > > operator && (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpOr, PETE_Scalar< long >, typename T::PETE_Expr_t > operator|| (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpOr, typename T::PETE_Expr_t, PETE_Scalar< long > > operator|| (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpBitwiseAnd, PETE_Scalar< long >, typename T::PETE_Expr_t > operator & (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseAnd, typename T::PETE_Expr_t, PETE_Scalar< long > > operator & (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpBitwiseOr, PETE_Scalar< long >, typename T::PETE_Expr_t > operator| (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseOr, typename T::PETE_Expr_t, PETE_Scalar< long > > operator| (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpBitwiseXor, PETE_Scalar< long >, typename T::PETE_Expr_t > operator^ (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseXor, typename T::PETE_Expr_t, PETE_Scalar< long > > operator^ (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< OpWhere, PETE_Scalar< long >, typename T::PETE_Expr_t > where (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpWhere, typename T::PETE_Expr_t, PETE_Scalar< long > > where (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< FnCopysign, PETE_Scalar< long >, typename T::PETE_Expr_t > copysign (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnCopysign, typename T::PETE_Expr_t, PETE_Scalar< long > > copysign (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< FnLdexp, PETE_Scalar< long >, typename T::PETE_Expr_t > ldexp (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnLdexp, typename T::PETE_Expr_t, PETE_Scalar< long > > ldexp (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< FnPow, PETE_Scalar< long >, typename T::PETE_Expr_t > pow (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnPow, typename T::PETE_Expr_t, PETE_Scalar< long > > pow (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< FnFmod, PETE_Scalar< long >, typename T::PETE_Expr_t > fmod (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnFmod, typename T::PETE_Expr_t, PETE_Scalar< long > > fmod (const PETE_Expr< T > &l, const long r)
template<class T >
PETE_TBTree< FnArcTan2, PETE_Scalar< long >, typename T::PETE_Expr_t > atan2 (const long l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnArcTan2, typename T::PETE_Expr_t, PETE_Scalar< long > > atan2 (const PETE_Expr< T > &l, const long r)
template<class Cond_t , class True_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< long > > where (const PETE_Expr< Cond_t > &c, const PETE_Expr< True_t > &t, long f)
template<class Cond_t , class False_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< long >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > &c, long t, const PETE_Expr< False_t > &f)
template<class Cond_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< long >, PETE_Scalar< long > > where (const PETE_Expr< Cond_t > &c, long t, long f)
template<class T >
PETE_TBTree< OpAdd, PETE_Scalar< float >, typename T::PETE_Expr_t > operator+ (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpAdd, typename T::PETE_Expr_t, PETE_Scalar< float > > operator+ (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpSubtract, PETE_Scalar< float >, typename T::PETE_Expr_t > operator- (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpSubtract, typename T::PETE_Expr_t, PETE_Scalar< float > > operator- (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpMultipply, PETE_Scalar< float >, typename T::PETE_Expr_t > operator* (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpMultipply, typename T::PETE_Expr_t, PETE_Scalar< float > > operator* (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpDivide, PETE_Scalar< float >, typename T::PETE_Expr_t > operator/ (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpDivide, typename T::PETE_Expr_t, PETE_Scalar< float > > operator/ (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpMod, PETE_Scalar< float >, typename T::PETE_Expr_t > operator% (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpMod, typename T::PETE_Expr_t, PETE_Scalar< float > > operator% (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpLT, PETE_Scalar< float >, typename T::PETE_Expr_t > operator< (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpLT, typename T::PETE_Expr_t, PETE_Scalar< float > > operator< (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpLE, PETE_Scalar< float >, typename T::PETE_Expr_t > operator<= (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpLE, typename T::PETE_Expr_t, PETE_Scalar< float > > operator<= (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpGT, PETE_Scalar< float >, typename T::PETE_Expr_t > operator> (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpGT, typename T::PETE_Expr_t, PETE_Scalar< float > > operator> (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpGE, PETE_Scalar< float >, typename T::PETE_Expr_t > operator>= (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpGE, typename T::PETE_Expr_t, PETE_Scalar< float > > operator>= (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpEQ, PETE_Scalar< float >, typename T::PETE_Expr_t > operator== (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpEQ, typename T::PETE_Expr_t, PETE_Scalar< float > > operator== (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpNE, PETE_Scalar< float >, typename T::PETE_Expr_t > operator!= (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpNE, typename T::PETE_Expr_t, PETE_Scalar< float > > operator!= (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpAnd, PETE_Scalar< float >, typename T::PETE_Expr_t > operator && (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpAnd, typename T::PETE_Expr_t, PETE_Scalar< float > > operator && (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpOr, PETE_Scalar< float >, typename T::PETE_Expr_t > operator|| (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpOr, typename T::PETE_Expr_t, PETE_Scalar< float > > operator|| (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpBitwiseAnd, PETE_Scalar< float >, typename T::PETE_Expr_t > operator & (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseAnd, typename T::PETE_Expr_t, PETE_Scalar< float > > operator & (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpBitwiseOr, PETE_Scalar< float >, typename T::PETE_Expr_t > operator| (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseOr, typename T::PETE_Expr_t, PETE_Scalar< float > > operator| (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpBitwiseXor, PETE_Scalar< float >, typename T::PETE_Expr_t > operator^ (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseXor, typename T::PETE_Expr_t, PETE_Scalar< float > > operator^ (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< OpWhere, PETE_Scalar< float >, typename T::PETE_Expr_t > where (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpWhere, typename T::PETE_Expr_t, PETE_Scalar< float > > where (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< FnCopysign, PETE_Scalar< float >, typename T::PETE_Expr_t > copysign (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnCopysign, typename T::PETE_Expr_t, PETE_Scalar< float > > copysign (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< FnLdexp, PETE_Scalar< float >, typename T::PETE_Expr_t > ldexp (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnLdexp, typename T::PETE_Expr_t, PETE_Scalar< float > > ldexp (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< FnPow, PETE_Scalar< float >, typename T::PETE_Expr_t > pow (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnPow, typename T::PETE_Expr_t, PETE_Scalar< float > > pow (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< FnFmod, PETE_Scalar< float >, typename T::PETE_Expr_t > fmod (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnFmod, typename T::PETE_Expr_t, PETE_Scalar< float > > fmod (const PETE_Expr< T > &l, const float r)
template<class T >
PETE_TBTree< FnArcTan2, PETE_Scalar< float >, typename T::PETE_Expr_t > atan2 (const float l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnArcTan2, typename T::PETE_Expr_t, PETE_Scalar< float > > atan2 (const PETE_Expr< T > &l, const float r)
template<class Cond_t , class True_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< float > > where (const PETE_Expr< Cond_t > &c, const PETE_Expr< True_t > &t, float f)
template<class Cond_t , class False_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< float >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > &c, float t, const PETE_Expr< False_t > &f)
template<class Cond_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< float >, PETE_Scalar< float > > where (const PETE_Expr< Cond_t > &c, float t, float f)
template<class T >
PETE_TBTree< OpAdd, PETE_Scalar< double >, typename T::PETE_Expr_t > operator+ (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpAdd, typename T::PETE_Expr_t, PETE_Scalar< double > > operator+ (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpSubtract, PETE_Scalar< double >, typename T::PETE_Expr_t > operator- (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpSubtract, typename T::PETE_Expr_t, PETE_Scalar< double > > operator- (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpMultipply, PETE_Scalar< double >, typename T::PETE_Expr_t > operator* (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpMultipply, typename T::PETE_Expr_t, PETE_Scalar< double > > operator* (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpDivide, PETE_Scalar< double >, typename T::PETE_Expr_t > operator/ (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpDivide, typename T::PETE_Expr_t, PETE_Scalar< double > > operator/ (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpMod, PETE_Scalar< double >, typename T::PETE_Expr_t > operator% (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpMod, typename T::PETE_Expr_t, PETE_Scalar< double > > operator% (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpLT, PETE_Scalar< double >, typename T::PETE_Expr_t > operator< (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpLT, typename T::PETE_Expr_t, PETE_Scalar< double > > operator< (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpLE, PETE_Scalar< double >, typename T::PETE_Expr_t > operator<= (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpLE, typename T::PETE_Expr_t, PETE_Scalar< double > > operator<= (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpGT, PETE_Scalar< double >, typename T::PETE_Expr_t > operator> (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpGT, typename T::PETE_Expr_t, PETE_Scalar< double > > operator> (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpGE, PETE_Scalar< double >, typename T::PETE_Expr_t > operator>= (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpGE, typename T::PETE_Expr_t, PETE_Scalar< double > > operator>= (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpEQ, PETE_Scalar< double >, typename T::PETE_Expr_t > operator== (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpEQ, typename T::PETE_Expr_t, PETE_Scalar< double > > operator== (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpNE, PETE_Scalar< double >, typename T::PETE_Expr_t > operator!= (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpNE, typename T::PETE_Expr_t, PETE_Scalar< double > > operator!= (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpAnd, PETE_Scalar< double >, typename T::PETE_Expr_t > operator && (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpAnd, typename T::PETE_Expr_t, PETE_Scalar< double > > operator && (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpOr, PETE_Scalar< double >, typename T::PETE_Expr_t > operator|| (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpOr, typename T::PETE_Expr_t, PETE_Scalar< double > > operator|| (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpBitwiseAnd, PETE_Scalar< double >, typename T::PETE_Expr_t > operator & (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseAnd, typename T::PETE_Expr_t, PETE_Scalar< double > > operator & (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpBitwiseOr, PETE_Scalar< double >, typename T::PETE_Expr_t > operator| (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseOr, typename T::PETE_Expr_t, PETE_Scalar< double > > operator| (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpBitwiseXor, PETE_Scalar< double >, typename T::PETE_Expr_t > operator^ (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpBitwiseXor, typename T::PETE_Expr_t, PETE_Scalar< double > > operator^ (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< OpWhere, PETE_Scalar< double >, typename T::PETE_Expr_t > where (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< OpWhere, typename T::PETE_Expr_t, PETE_Scalar< double > > where (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< FnCopysign, PETE_Scalar< double >, typename T::PETE_Expr_t > copysign (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnCopysign, typename T::PETE_Expr_t, PETE_Scalar< double > > copysign (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< FnLdexp, PETE_Scalar< double >, typename T::PETE_Expr_t > ldexp (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnLdexp, typename T::PETE_Expr_t, PETE_Scalar< double > > ldexp (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< FnPow, PETE_Scalar< double >, typename T::PETE_Expr_t > pow (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnPow, typename T::PETE_Expr_t, PETE_Scalar< double > > pow (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< FnFmod, PETE_Scalar< double >, typename T::PETE_Expr_t > fmod (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnFmod, typename T::PETE_Expr_t, PETE_Scalar< double > > fmod (const PETE_Expr< T > &l, const double r)
template<class T >
PETE_TBTree< FnArcTan2, PETE_Scalar< double >, typename T::PETE_Expr_t > atan2 (const double l, const PETE_Expr< T > &r)
template<class T >
PETE_TBTree< FnArcTan2, typename T::PETE_Expr_t, PETE_Scalar< double > > atan2 (const PETE_Expr< T > &l, const double r)
template<class Cond_t , class True_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< double > > where (const PETE_Expr< Cond_t > &c, const PETE_Expr< True_t > &t, double f)
template<class Cond_t , class False_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< double >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > &c, double t, const PETE_Expr< False_t > &f)
template<class Cond_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< double >, PETE_Scalar< double > > where (const PETE_Expr< Cond_t > &c, double t, double f)
template<class T1 , class T2 >
void PETE_apply (OpAssign, T1 &a, const T2 &b)
template<class T1 , class T2 >
void PETE_apply (OpAddAssign, T1 &a, const T2 &b)
template<class T1 , class T2 >
void PETE_apply (OpSubtractAssign, T1 &a, const T2 &b)
template<class T1 , class T2 >
void PETE_apply (OpMultipplyAssign, T1 &a, const T2 &b)
template<class T1 , class T2 >
void PETE_apply (OpDivideAssign, T1 &a, const T2 &b)
template<class T1 , class T2 >
void PETE_apply (OpModAssign, T1 &a, const T2 &b)
template<class T1 , class T2 >
void PETE_apply (OpBitwiseOrAssign, T1 &a, const T2 &b)
template<class T1 , class T2 >
void PETE_apply (OpBitwiseAndAssign, T1 &a, const T2 &b)
template<class T1 , class T2 >
void PETE_apply (OpBitwiseXorAssign, T1 &a, const T2 &b)
template<class T1 , class T2 >
void PETE_apply (OpLeftShiftAssign, T1 &a, const T2 &b)
template<class T1 , class T2 >
void PETE_apply (OpRightShiftAssign, T1 &a, const T2 &b)
template<class T >
T::PETE_Expr_t::PETE_Return_t sum (const PETE_Expr< T > &expr)
template<class T >
T::PETE_Expr_t::PETE_Return_t prod (const PETE_Expr< T > &expr)
Macro Definition Documentation
BINARY_FUNCTION
#define BINARY_FUNCTION (RET, FUNC, ARG1, ARG2)
Value:
struct FnBinary_ ## FUNC {                                                  \
  enum { tag = PETE_BinaryPromoteTag };                                     \
};                                                                          \
PETE_DefineBinary(FUNC,(FUNC(a,b)),FnBinary_ ## FUNC)                       \
template<>                                                                  \
struct PETEBinaryReturn<ARG1,ARG2,FnBinary_ ## FUNC> {                      \
  typedef RET type;                                                         \
};
Definition at line 1145 of file PETE.h.
PETE_DefineAssign
#define PETE_DefineAssign (Expr, Cond, Op)
Value:
template<class T1, class T2>                                    \
struct PETE_StructApply<Op,T1,T2>                               \
{                                                               \
  static void apply(T1& a,const T2& b) { Expr; }                \
};                                                              \
                                                                \
template<class T1, class T2>                                    \
struct PETE_StructApply<Op,T1,ConditionalAssign<T2> >           \
{                                                               \
  static void apply(T1& a, const ConditionalAssign<T2>& b)      \
    {                                                           \
      if ( b.cond )                                             \
        Cond;                                                   \
    }                                                           \
};                                                              \
                                                                \
template<class T1, class T2>                                    \
inline void                            \
PETE_apply(Op, T1 &a, const T2& b)                              \
{                                                               \
  PETE_StructApply<Op,T1,T2>::apply(a,b);                       \
}
Definition at line 1031 of file PETE.h.
PETE_DefineBinary
#define PETE_DefineBinary (Fun, Expr, Op)
Value:
template<class T1, class T2>                                                \
inline typename PETEBinaryReturn<T1, T2, Op>::type                          \
PETE_apply(Op, const T1& a, const T2& b)                                    \
{                                                                           \
  return Expr;                                                              \
}                                                                           \
template<class T1, class T2>                                                \
inline PETE_TBTree<Op, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t>  \
Fun(const PETE_Expr<T1>& l, const PETE_Expr<T2>& r)                         \
{                                                                           \
  typedef PETE_TBTree<Op,typename T1::PETE_Expr_t,                          \
    typename T2::PETE_Expr_t> ret;                                          \
  return ret(l.PETE_unwrap().MakeExpression(),                              \
    r.PETE_unwrap().MakeExpression());                                      \
}
Definition at line 770 of file PETE.h.
PETE_DefineBinarySynonym
#define PETE_DefineBinarySynonym (Fun, Op)
Value:
template<class T1, class T2>                                                \
inline PETE_TBTree<Op, typename T1::PETE_Expr_t, typename T2::PETE_Expr_t>  \
Fun(const PETE_Expr<T1>& l, const PETE_Expr<T2>& r)                         \
{                                                                           \
  typedef PETE_TBTree<Op,typename T1::PETE_Expr_t,typename T2::PETE_Expr_t> \
    ret;                                                                    \
  return ret(l.PETE_unwrap().MakeExpression(),                              \
    r.PETE_unwrap().MakeExpression());                                      \
}
Definition at line 787 of file PETE.h.
PETE_DefineBinaryWithScalars
#define PETE_DefineBinaryWithScalars (Fun, Op, Sca)
Value:
template<class T>                                                           \
inline PETE_TBTree<Op, PETE_Scalar<Sca>, typename T::PETE_Expr_t>           \
Fun(const Sca l, const PETE_Expr<T>& r)                                     \
{                                                                           \
  typedef PETE_TBTree<Op, PETE_Scalar<Sca>, typename T::PETE_Expr_t> ret;   \
  return ret(PETE_Scalar<Sca>(l), r.PETE_unwrap().MakeExpression());        \
}                                                                           \
template<class T>                                                           \
inline PETE_TBTree<Op, typename T::PETE_Expr_t, PETE_Scalar<Sca> >          \
Fun(const PETE_Expr<T>& l, const Sca r)                                     \
{                                                                           \
  typedef PETE_TBTree<Op, typename T::PETE_Expr_t, PETE_Scalar<Sca> > ret;  \
  return ret(l.PETE_unwrap().MakeExpression(), PETE_Scalar<Sca>(r));        \
}
Definition at line 823 of file PETE.h.
PETE_DefineScalar
#define PETE_DefineScalar (Sca)
Value:
PETE_DefineBinaryWithScalars(operator+, OpAdd, Sca)                         \
PETE_DefineBinaryWithScalars(operator-, OpSubtract, Sca)                    \
PETE_DefineBinaryWithScalars(operator*, OpMultipply, Sca)                    \
PETE_DefineBinaryWithScalars(operator/, OpDivide, Sca)                      \
PETE_DefineBinaryWithScalars(operator%, OpMod, Sca)                         \
PETE_DefineBinaryWithScalars(operator<, OpLT, Sca)                          \
PETE_DefineBinaryWithScalars(operator<=, OpLE, Sca)                         \
PETE_DefineBinaryWithScalars(operator>, OpGT, Sca)                          \
PETE_DefineBinaryWithScalars(operator>=, OpGE, Sca)                         \
PETE_DefineBinaryWithScalars(operator==, OpEQ, Sca)                         \
PETE_DefineBinaryWithScalars(operator!=, OpNE, Sca)                         \
PETE_DefineBinaryWithScalars(operator&&, OpAnd, Sca)                        \
PETE_DefineBinaryWithScalars(operator||, OpOr, Sca)                         \
PETE_DefineBinaryWithScalars(operator&, OpBitwiseAnd, Sca)                  \
PETE_DefineBinaryWithScalars(operator|, OpBitwiseOr, Sca)                   \
PETE_DefineBinaryWithScalars(operator^, OpBitwiseXor, Sca)                  \
PETE_DefineBinaryWithScalars(where, OpWhere, Sca)                           \
PETE_DefineBinaryWithScalars(copysign, FnCopysign, Sca)                     \
PETE_DefineBinaryWithScalars(ldexp, FnLdexp, Sca)                           \
PETE_DefineBinaryWithScalars(pow, FnPow, Sca)                               \
PETE_DefineBinaryWithScalars(fmod, FnFmod, Sca)                             \
PETE_DefineBinaryWithScalars(atan2, FnArcTan2, Sca)                         \
PETE_DefineTrinaryWithScalars(where, OpWhere, Sca)
Definition at line 986 of file PETE.h.
PETE_DefineTrinary
#define PETE_DefineTrinary (Fun, Expr, Op)
Value:
template<class T1, class T2, class T3>                                      \
inline typename PETETrinaryReturn<T1,T2,T3,Op>::type                        \
PETE_apply(Op, const T1& a, const T2& b, const T3& c)                       \
{                                                                           \
  return Expr;                                                              \
}                                                                           \
template<class Cond_t, class True_t, class False_t>                         \
inline PETE_TTTree<Op, typename Cond_t::PETE_Expr_t,                        \
  typename True_t::PETE_Expr_t, typename False_t::PETE_Expr_t>              \
Fun(const PETE_Expr<Cond_t>& c, const PETE_Expr<True_t>& t,                 \
  const PETE_Expr<False_t>& f)                                              \
{                                                                           \
  typedef PETE_TTTree<Op, typename Cond_t::PETE_Expr_t,                     \
    typename True_t::PETE_Expr_t, typename False_t::PETE_Expr_t> ret;       \
  return ret(c.PETE_unwrap().MakeExpression(),                              \
    t.PETE_unwrap().MakeExpression(),                                       \
    f.PETE_unwrap().MakeExpression());                                      \
}
Definition at line 846 of file PETE.h.
PETE_DefineTrinaryWithScalars
#define PETE_DefineTrinaryWithScalars (Fun, Op, Sca)
Value:
template<class Cond_t, class True_t>                                        \
inline PETE_TTTree<Op, typename Cond_t::PETE_Expr_t,                        \
  typename True_t::PETE_Expr_t, PETE_Scalar<Sca> >                          \
Fun(const PETE_Expr<Cond_t>& c, const PETE_Expr<True_t>& t,Sca f)           \
{                                                                           \
  typedef PETE_TTTree<Op, typename Cond_t::PETE_Expr_t,                     \
    typename True_t::PETE_Expr_t, PETE_Scalar<Sca> > ret;                   \
  return ret(c.PETE_unwrap().MakeExpression(),                              \
    t.PETE_unwrap().MakeExpression(), PETE_Scalar<Sca>(f));                 \
}                                                                           \
template<class Cond_t, class False_t>                                       \
inline PETE_TTTree<Op, typename Cond_t::PETE_Expr_t, PETE_Scalar<Sca>,      \
  typename False_t::PETE_Expr_t >                                           \
Fun(const PETE_Expr<Cond_t>& c, Sca t, const PETE_Expr<False_t>& f)         \
{                                                                           \
  typedef PETE_TTTree<Op, typename Cond_t::PETE_Expr_t, PETE_Scalar<Sca>,   \
    typename False_t::PETE_Expr_t > ret;                                    \
  return ret(c.PETE_unwrap().MakeExpression(),                              \
    PETE_Scalar<Sca>(t), f.PETE_unwrap().MakeExpression());                 \
}                                                                           \
template<class Cond_t>                                                      \
inline PETE_TTTree<Op, typename Cond_t::PETE_Expr_t, PETE_Scalar<Sca>,      \
  PETE_Scalar<Sca> >                                                        \
Fun(const PETE_Expr<Cond_t>& c, Sca t, Sca f)                               \
{                                                                           \
  typedef PETE_TTTree<Op, typename Cond_t::PETE_Expr_t, PETE_Scalar<Sca>,   \
    PETE_Scalar<Sca> > ret;                                                 \
  return ret(c.PETE_unwrap().MakeExpression(),                              \
    PETE_Scalar<Sca>(t), PETE_Scalar<Sca>(f));                              \
}
Definition at line 889 of file PETE.h.
PETE_DefineUnary
#define PETE_DefineUnary (Fun, Expr, Op)
Value:
template<class T>                                                           \
inline typename PETEUnaryReturn<T, Op>::type                                \
PETE_apply(Op, const T& a)                                                  \
{                                                                           \
  return Expr;                                                              \
}                                                                           \
template<class T>                                                           \
inline PETE_TUTree<Op, typename T::PETE_Expr_t>                             \
Fun(const PETE_Expr<T>& l)                                                  \
{                                                                           \
  return PETE_TUTree<Op, typename T::PETE_Expr_t>                           \
    (l.PETE_unwrap().MakeExpression());                                     \
}
Definition at line 704 of file PETE.h.
PETE_USER_REDUCTION_CODE
#define PETE_USER_REDUCTION_CODE
Definition at line 654 of file PETE.h.
Referenced by Reduction().
UNARY_FUNCTION
#define UNARY_FUNCTION (RET, FUNC, ARG)
Value:
struct FnUnary_ ## FUNC {                                                   \
  enum { tag = PETE_UnaryPassThruTag };                                     \
};                                                                          \
PETE_DefineUnary(FUNC,FUNC(a),FnUnary_ ## FUNC)                             \
template <>                                                                 \
struct PETEUnaryReturn<ARG, FnUnary_ ## FUNC> {                             \
  typedef RET type;                                                         \
};
Definition at line 1135 of file PETE.h.
Typedef Documentation
PETE_AndCombiner
typedef PETE_Combiner<bool,OpAnd> PETE_AndCombiner
Definition at line 467 of file PETE.h.
PETE_OrCombiner
typedef PETE_Combiner<bool,OpOr> PETE_OrCombiner
Definition at line 468 of file PETE.h.
PETE_SumCombiner
typedef PETE_Combiner<int,OpAdd> PETE_SumCombiner
Definition at line 469 of file PETE.h.
Function Documentation
acos()
template<class T > PETE_TUTree< FnArcCos , typename T::PETE_Expr_t> acos (const PETE_Expr< T > & l) inline
Definition at line 725 of file PETE.h.
Referenced by Distribution::applyEmissModelAstra(), Distribution::applyEmissModelNonEquil(), ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), ParallelCyclotronTracker::bunchDumpStatData(), Mesher::computeMinimumAngle(), ClosedOrbitFinder< Value_type, Size_type, Stepper >::computeTune(), MapGenerator< Value_type, Size_type, Series_type, Map_type, Hamiltonian_type, Space_charge_type >::computeTunes(), ParallelCyclotronTracker::deleteParticle(), getAngleBetweenEdges(), VarRadiusGeometry::getTransform(), ParallelCyclotronTracker::initDistInGlobalFrame(), GlobalFunctions::_acos::operator()(), and matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
asin()
template<class T > PETE_TUTree< FnArcSin , typename T::PETE_Expr_t> asin (const PETE_Expr< T > & l) inline
Definition at line 726 of file PETE.h.
Referenced by BendBase::calcBendAngle(), RBend::findChordLength(), Distribution::generateBinomial(), Bend2D::getSurfaceMesh(), GlobalFunctions::_asin::operator()(), matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_(), and ThickTracker::visitSBend().
atan()
template<class T > PETE_TUTree< FnArcTan , typename T::PETE_Expr_t> atan (const PETE_Expr< T > & l) inline
Definition at line 727 of file PETE.h.
Referenced by Cyclotron::apply(), ScatteringPhysics::applyRandomRotation(), Vacuum::checkPressure(), TravelingWave::getAutoPhaseEstimate(), RFCavity::getAutoPhaseEstimate(), FFTBoxPoissonSolver::integratedGreensFunction(), FFTPoissonSolver::integratedGreensFunction(), P3MPoissonSolver::integratedGreensFunction(), GlobalFunctions::_atan::operator()(), MapAnalyser::printPhaseShift_m(), FFTBoxPoissonSolver::shiftedIntGreensFunction(), FFTPoissonSolver::shiftedIntGreensFunction(), MultipoleTCurvedConstRadius::transformCoords(), MultipoleT::transformCoords(), and matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
atan2() [1/11]
template<class T1 , class T2 > PETE_TBTree< FnArcTan2 , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> atan2 (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 821 of file PETE.h.
atan2() [2/11]
template<class T > PETE_TBTree< FnArcTan2 , PETE_Scalar< short >, typename T::PETE_Expr_t> atan2 (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
atan2() [3/11]
template<class T > PETE_TBTree< FnArcTan2 , typename T::PETE_Expr_t, PETE_Scalar< short > > atan2 (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
atan2() [4/11]
template<class T > PETE_TBTree< FnArcTan2 , PETE_Scalar< int >, typename T::PETE_Expr_t> atan2 (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
atan2() [5/11]
template<class T > PETE_TBTree< FnArcTan2 , typename T::PETE_Expr_t, PETE_Scalar< int > > atan2 (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
atan2() [6/11]
template<class T > PETE_TBTree< FnArcTan2 , PETE_Scalar< long >, typename T::PETE_Expr_t> atan2 (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
atan2() [7/11]
template<class T > PETE_TBTree< FnArcTan2 , typename T::PETE_Expr_t, PETE_Scalar< long > > atan2 (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
atan2() [8/11]
template<class T > PETE_TBTree< FnArcTan2 , PETE_Scalar< float >, typename T::PETE_Expr_t> atan2 (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
atan2() [9/11]
template<class T > PETE_TBTree< FnArcTan2 , typename T::PETE_Expr_t, PETE_Scalar< float > > atan2 (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
atan2() [10/11]
template<class T > PETE_TBTree< FnArcTan2 , PETE_Scalar< double >, typename T::PETE_Expr_t> atan2 (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
atan2() [11/11]
template<class T > PETE_TBTree< FnArcTan2 , typename T::PETE_Expr_t, PETE_Scalar< double > > atan2 (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
ceil()
template<class T > PETE_TUTree< FnCeil , typename T::PETE_Expr_t> ceil (const PETE_Expr< T > & l) inline
Definition at line 728 of file PETE.h.
Referenced by BoxLibLayout< T, Dim >::BoxLibLayout(), Distribution::checkEmissionParameters(), ParallelTTracker::computeParticleMatterInteraction(), BoundaryGeometry::fastIsInside(), HashPairBuilder< PBase >::for_each(), StepSizeConfig::getNumStepsFinestResolution(), _FM3DDynamic::getOnaxisEz(), Bend2D::getOutline(), GlobalFunctions::_ceil::operator()(), PeakFinder::PeakFinder(), Bend2D::readFieldMap(), _FM3DDynamic::readMap(), and matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
copysign() [1/11]
template<class T1 , class T2 > PETE_TBTree< FnCopysign , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> copysign (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 817 of file PETE.h.
copysign() [2/11]
template<class T > PETE_TBTree< FnCopysign , typename T::PETE_Expr_t, PETE_Scalar< short > > copysign (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
copysign() [3/11]
template<class T > PETE_TBTree< FnCopysign , PETE_Scalar< short >, typename T::PETE_Expr_t> copysign (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
copysign() [4/11]
template<class T > PETE_TBTree< FnCopysign , PETE_Scalar< int >, typename T::PETE_Expr_t> copysign (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
copysign() [5/11]
template<class T > PETE_TBTree< FnCopysign , typename T::PETE_Expr_t, PETE_Scalar< int > > copysign (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
copysign() [6/11]
template<class T > PETE_TBTree< FnCopysign , typename T::PETE_Expr_t, PETE_Scalar< long > > copysign (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
copysign() [7/11]
template<class T > PETE_TBTree< FnCopysign , PETE_Scalar< long >, typename T::PETE_Expr_t> copysign (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
copysign() [8/11]
template<class T > PETE_TBTree< FnCopysign , typename T::PETE_Expr_t, PETE_Scalar< float > > copysign (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
copysign() [9/11]
template<class T > PETE_TBTree< FnCopysign , PETE_Scalar< float >, typename T::PETE_Expr_t> copysign (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
copysign() [10/11]
template<class T > PETE_TBTree< FnCopysign , PETE_Scalar< double >, typename T::PETE_Expr_t> copysign (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
copysign() [11/11]
template<class T > PETE_TBTree< FnCopysign , typename T::PETE_Expr_t, PETE_Scalar< double > > copysign (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
cos()
template<class T > PETE_TUTree< FnCos , typename T::PETE_Expr_t> cos (const PETE_Expr< T > & l) inline
Definition at line 729 of file PETE.h.
cosh()
template<class T > PETE_TUTree< FnHypCos , typename T::PETE_Expr_t> cosh (const PETE_Expr< T > & l) inline
Definition at line 730 of file PETE.h.
erf()
template<class T > PETE_TUTree< FnErf , typename T::PETE_Expr_t> erf (const PETE_Expr< T > & l) inline
Definition at line 741 of file PETE.h.
exp()
template<class T > PETE_TUTree< FnExp , typename T::PETE_Expr_t> exp (const PETE_Expr< T > & l) inline
Definition at line 731 of file PETE.h.
fabs()
template<class T > PETE_TUTree< FnFabs , typename T::PETE_Expr_t> fabs (const PETE_Expr< T > & l) inline
Definition at line 732 of file PETE.h.
Referenced by RealDiracMatrix::diagonalize(), Hypervolume::hv(), Hypervolume::hv2(), Hypervolume::inclhv(), GlobalFunctions::_fabs::operator()(), and SigmaGenerator::updateInitialSigma().
floor()
template<class T > PETE_TUTree< FnFloor , typename T::PETE_Expr_t> floor (const PETE_Expr< T > & l) inline
Definition at line 733 of file PETE.h.
Referenced by CSRIGFWakeFunction::apply(), CSRWakeFunction::apply(), TravelingWave::apply(), GreenWakeFunction::apply(), TravelingWave::applyToReferenceParticle(), CSRWakeFunction::calculateContributionAfter(), CSRIGFWakeFunction::calculateContributionAfter(), CSRWakeFunction::calculateContributionInside(), Util::checkInt(), DistributionMoments::computePercentiles(), OpalVariableRFCavityFringeField::convertToUnsigned(), interpolation::NDGrid::coordLowerBound(), HashPairBuilderPeriodic< PBase >::for_each(), HashPairBuilderPeriodicParallel< PBase >::for_each(), HashPairBuilderParallel< PBase >::forEach(), TravelingWave::getAutoPhaseEstimate(), RFCavity::getAutoPhaseEstimate(), PartBins::getBin(), _FM2DMagnetoStatic::getFieldDerivative(), _FM3DDynamic::getFieldstrength(), _FM2DMagnetoStatic::getFieldstrength(), _FM2DElectroStatic::getFieldstrength(), _FM2DDynamic::getFieldstrength(), _FM3DMagnetoStatic::getIndex(), _FM3DMagnetoStaticExtended::getIndex(), _FM3DH5BlockBase::getOnaxisEz(), BoxLibLayout< T, Dim >::Index(), TravelingWave::initialise(), BoundaryGeometry::initialize(), BoundaryGeometry::mapPoint2Voxel(), GlobalFunctions::_floor::operator()(), IndexMap::print(), PartBunchBase< double, 3 >::resetPartBinID2(), OpalBeamline::save3DLattice(), TravelingWave::setPhasem(), AmrTrilinearInterpolater< Level >::stencil(), HashPairBuilder< PBase >::sum(), Util::toStringWithThousandSep(), matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_(), OpalVerticalFFAMagnet::update(), OpalScalingFFAMagnet::update(), OpalSplineTimeDependence::update(), OpalOutputPlane::update(), interpolation::ThreeDGrid::xLowerBound(), interpolation::ThreeDGrid::yLowerBound(), and interpolation::ThreeDGrid::zLowerBound().
fmod() [1/11]
template<class T1 , class T2 > PETE_TBTree< FnFmod , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> fmod (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 820 of file PETE.h.
fmod() [2/11]
template<class T > PETE_TBTree< FnFmod , typename T::PETE_Expr_t, PETE_Scalar< short > > fmod (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
fmod() [3/11]
template<class T > PETE_TBTree< FnFmod , PETE_Scalar< short >, typename T::PETE_Expr_t> fmod (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
fmod() [4/11]
template<class T > PETE_TBTree< FnFmod , PETE_Scalar< int >, typename T::PETE_Expr_t> fmod (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
fmod() [5/11]
template<class T > PETE_TBTree< FnFmod , typename T::PETE_Expr_t, PETE_Scalar< int > > fmod (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
fmod() [6/11]
template<class T > PETE_TBTree< FnFmod , PETE_Scalar< long >, typename T::PETE_Expr_t> fmod (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
fmod() [7/11]
template<class T > PETE_TBTree< FnFmod , typename T::PETE_Expr_t, PETE_Scalar< long > > fmod (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
fmod() [8/11]
template<class T > PETE_TBTree< FnFmod , PETE_Scalar< float >, typename T::PETE_Expr_t> fmod (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
fmod() [9/11]
template<class T > PETE_TBTree< FnFmod , typename T::PETE_Expr_t, PETE_Scalar< float > > fmod (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
fmod() [10/11]
template<class T > PETE_TBTree< FnFmod , typename T::PETE_Expr_t, PETE_Scalar< double > > fmod (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
fmod() [11/11]
template<class T > PETE_TBTree< FnFmod , PETE_Scalar< double >, typename T::PETE_Expr_t> fmod (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
for_each() [1/9]
template<class T > T for_each (const PETE_Scalar< T > & p, EvalFunctor_0) inline
Definition at line 202 of file PETE.h.
References Attrib::Legacy::Distribution::T.
Referenced by struct_for_each< Op, T1, T2, Functor >::apply(), struct_for_each< OpWhere, T1, T2, Functor >::apply(), TrinaryForEach< Safe, T1, T2, T3, Op, Functor >::apply(), TrinaryForEach< 0, T1, T2, T3, OpWhere, Functor >::apply(), for_each(), and Reduction().
for_each() [2/9]
template<class T , class C > int for_each (PETE_Scalar< T > & , PETE_Increment , C) inline
Definition at line 211 of file PETE.h.
for_each() [3/9]
template<class T , class C > int for_each (const PETE_Scalar< T > & , PETE_CountElems , C) inline
Definition at line 220 of file PETE.h.
for_each() [4/9]
template<class Op , class T1 , class Functor , class Combiner > Functor::PETE_Return_t for_each (PETE_TUTree< Op, T1 > & node, Functor f, Combiner c) inline
Definition at line 382 of file PETE.h.
References Physics::c, PETE_TUTree< Value_t, Child_t >::Child, and for_each().
for_each() [5/9]
template<class Op , class T1 , class T2 , class Functor , class Combiner > Functor::PETE_Return_t for_each (PETE_TBTree< Op, T1, T2 > & node, Functor f, Combiner c) inline
Definition at line 390 of file PETE.h.
References Physics::c, for_each(), PETE_TBTree< Value_t, Left_t, Right_t >::Left, and PETE_TBTree< Value_t, Left_t, Right_t >::Right.
for_each() [6/9]
template<class Op , class T1 , class T2 , class T3 , class Functor , class Combiner > Functor::PETE_Return_t for_each (PETE_TTTree< Op, T1, T2, T3 > & node, Functor f, Combiner c) inline
Definition at line 398 of file PETE.h.
References Physics::c, for_each(), PETE_TTTree< Value_t, Left_t, Middle_t, Right_t >::Left, PETE_TTTree< Value_t, Left_t, Middle_t, Right_t >::Middle, and PETE_TTTree< Value_t, Left_t, Middle_t, Right_t >::Right.
for_each() [7/9]
template<class Op , class T1 , class Functor > PETEUnaryReturn<typename T1::PETE_Return_t,Op>::type for_each (PETE_TUTree< Op, T1 > & node, Functor f) inline
Definition at line 481 of file PETE.h.
References PETE_TUTree< Value_t, Child_t >::Child, for_each(), PETE_apply(), and PETE_TUTree< Value_t, Child_t >::Value.
for_each() [8/9]
template<class Op , class T1 , class T2 , class Functor > struct_for_each<Op,T1,T2,Functor>::Return_t for_each (PETE_TBTree< Op, T1, T2 > & node, Functor f) inline
Definition at line 531 of file PETE.h.
References struct_for_each< Op, T1, T2, Functor >::apply().
for_each() [9/9]
template<class T1 , class T2 , class T3 , class Functor , class Op > PETETrinaryReturn<typename T1::PETE_Return_t, typename T2::PETE_Return_t, typename T3::PETE_Return_t,Op>::type for_each (PETE_TTTree< Op, T1, T2, T3 > & node, Functor f) inline
Definition at line 639 of file PETE.h.
ldexp() [1/11]
template<class T1 , class T2 > PETE_TBTree< FnLdexp , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> ldexp (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 818 of file PETE.h.
ldexp() [2/11]
template<class T > PETE_TBTree< FnLdexp , PETE_Scalar< short >, typename T::PETE_Expr_t> ldexp (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
ldexp() [3/11]
template<class T > PETE_TBTree< FnLdexp , typename T::PETE_Expr_t, PETE_Scalar< short > > ldexp (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
ldexp() [4/11]
template<class T > PETE_TBTree< FnLdexp , PETE_Scalar< int >, typename T::PETE_Expr_t> ldexp (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
ldexp() [5/11]
template<class T > PETE_TBTree< FnLdexp , typename T::PETE_Expr_t, PETE_Scalar< int > > ldexp (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
ldexp() [6/11]
template<class T > PETE_TBTree< FnLdexp , typename T::PETE_Expr_t, PETE_Scalar< long > > ldexp (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
ldexp() [7/11]
template<class T > PETE_TBTree< FnLdexp , PETE_Scalar< long >, typename T::PETE_Expr_t> ldexp (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
ldexp() [8/11]
template<class T > PETE_TBTree< FnLdexp , PETE_Scalar< float >, typename T::PETE_Expr_t> ldexp (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
ldexp() [9/11]
template<class T > PETE_TBTree< FnLdexp , typename T::PETE_Expr_t, PETE_Scalar< float > > ldexp (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
ldexp() [10/11]
template<class T > PETE_TBTree< FnLdexp , PETE_Scalar< double >, typename T::PETE_Expr_t> ldexp (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
ldexp() [11/11]
template<class T > PETE_TBTree< FnLdexp , typename T::PETE_Expr_t, PETE_Scalar< double > > ldexp (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
log()
template<class T > PETE_TUTree< FnLog , typename T::PETE_Expr_t> log (const PETE_Expr< T > & l) inline
Definition at line 734 of file PETE.h.
log10()
template<class T > PETE_TUTree< FnLog10 , typename T::PETE_Expr_t> log10 (const PETE_Expr< T > & l) inline
Definition at line 735 of file PETE.h.
Referenced by DistributionMoments::computePercentiles(), TrimCoilMirrored::doApplyField(), and matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
operator &() [1/11]
template<class T1 , class T2 > PETE_TBTree< OpBitwiseAnd , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator& (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 811 of file PETE.h.
operator &() [2/11]
template<class T > PETE_TBTree< OpBitwiseAnd , PETE_Scalar< short >, typename T::PETE_Expr_t> operator& (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator &() [3/11]
template<class T > PETE_TBTree< OpBitwiseAnd , typename T::PETE_Expr_t, PETE_Scalar< short > > operator& (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator &() [4/11]
template<class T > PETE_TBTree< OpBitwiseAnd , PETE_Scalar< int >, typename T::PETE_Expr_t> operator& (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator &() [5/11]
template<class T > PETE_TBTree< OpBitwiseAnd , typename T::PETE_Expr_t, PETE_Scalar< int > > operator& (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator &() [6/11]
template<class T > PETE_TBTree< OpBitwiseAnd , PETE_Scalar< long >, typename T::PETE_Expr_t> operator& (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator &() [7/11]
template<class T > PETE_TBTree< OpBitwiseAnd , typename T::PETE_Expr_t, PETE_Scalar< long > > operator& (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator &() [8/11]
template<class T > PETE_TBTree< OpBitwiseAnd , PETE_Scalar< float >, typename T::PETE_Expr_t> operator& (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator &() [9/11]
template<class T > PETE_TBTree< OpBitwiseAnd , typename T::PETE_Expr_t, PETE_Scalar< float > > operator& (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator &() [10/11]
template<class T > PETE_TBTree< OpBitwiseAnd , PETE_Scalar< double >, typename T::PETE_Expr_t> operator& (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator &() [11/11]
template<class T > PETE_TBTree< OpBitwiseAnd , typename T::PETE_Expr_t, PETE_Scalar< double > > operator& (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator &&() [1/11]
template<class T1 , class T2 > PETE_TBTree< OpAnd , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator&& (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 809 of file PETE.h.
operator &&() [2/11]
template<class T > PETE_TBTree< OpAnd , PETE_Scalar< short >, typename T::PETE_Expr_t> operator&& (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator &&() [3/11]
template<class T > PETE_TBTree< OpAnd , typename T::PETE_Expr_t, PETE_Scalar< short > > operator&& (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator &&() [4/11]
template<class T > PETE_TBTree< OpAnd , PETE_Scalar< int >, typename T::PETE_Expr_t> operator&& (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator &&() [5/11]
template<class T > PETE_TBTree< OpAnd , typename T::PETE_Expr_t, PETE_Scalar< int > > operator&& (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator &&() [6/11]
template<class T > PETE_TBTree< OpAnd , PETE_Scalar< long >, typename T::PETE_Expr_t> operator&& (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator &&() [7/11]
template<class T > PETE_TBTree< OpAnd , typename T::PETE_Expr_t, PETE_Scalar< long > > operator&& (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator &&() [8/11]
template<class T > PETE_TBTree< OpAnd , typename T::PETE_Expr_t, PETE_Scalar< float > > operator&& (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator &&() [9/11]
template<class T > PETE_TBTree< OpAnd , PETE_Scalar< float >, typename T::PETE_Expr_t> operator&& (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator &&() [10/11]
template<class T > PETE_TBTree< OpAnd , typename T::PETE_Expr_t, PETE_Scalar< double > > operator&& (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator &&() [11/11]
template<class T > PETE_TBTree< OpAnd , PETE_Scalar< double >, typename T::PETE_Expr_t> operator&& (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator!()
template<class T > PETE_TUTree< OpNot , typename T::PETE_Expr_t> operator! (const PETE_Expr< T > & l) inline
Definition at line 722 of file PETE.h.
operator!=() [1/11]
template<class T1 , class T2 > PETE_TBTree< OpNE , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator!= (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 808 of file PETE.h.
operator!=() [2/11]
template<class T > PETE_TBTree< OpNE , PETE_Scalar< short >, typename T::PETE_Expr_t> operator!= (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator!=() [3/11]
template<class T > PETE_TBTree< OpNE , typename T::PETE_Expr_t, PETE_Scalar< short > > operator!= (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator!=() [4/11]
template<class T > PETE_TBTree< OpNE , PETE_Scalar< int >, typename T::PETE_Expr_t> operator!= (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator!=() [5/11]
template<class T > PETE_TBTree< OpNE , typename T::PETE_Expr_t, PETE_Scalar< int > > operator!= (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator!=() [6/11]
template<class T > PETE_TBTree< OpNE , typename T::PETE_Expr_t, PETE_Scalar< long > > operator!= (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator!=() [7/11]
template<class T > PETE_TBTree< OpNE , PETE_Scalar< long >, typename T::PETE_Expr_t> operator!= (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator!=() [8/11]
template<class T > PETE_TBTree< OpNE , PETE_Scalar< float >, typename T::PETE_Expr_t> operator!= (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator!=() [9/11]
template<class T > PETE_TBTree< OpNE , typename T::PETE_Expr_t, PETE_Scalar< float > > operator!= (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator!=() [10/11]
template<class T > PETE_TBTree< OpNE , PETE_Scalar< double >, typename T::PETE_Expr_t> operator!= (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator!=() [11/11]
template<class T > PETE_TBTree< OpNE , typename T::PETE_Expr_t, PETE_Scalar< double > > operator!= (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator%() [1/11]
template<class T1 , class T2 > PETE_TBTree< OpMod , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator% (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 802 of file PETE.h.
operator%() [2/11]
template<class T > PETE_TBTree< OpMod , typename T::PETE_Expr_t, PETE_Scalar< short > > operator% (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator%() [3/11]
template<class T > PETE_TBTree< OpMod , PETE_Scalar< short >, typename T::PETE_Expr_t> operator% (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator%() [4/11]
template<class T > PETE_TBTree< OpMod , typename T::PETE_Expr_t, PETE_Scalar< int > > operator% (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator%() [5/11]
template<class T > PETE_TBTree< OpMod , PETE_Scalar< int >, typename T::PETE_Expr_t> operator% (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator%() [6/11]
template<class T > PETE_TBTree< OpMod , PETE_Scalar< long >, typename T::PETE_Expr_t> operator% (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator%() [7/11]
template<class T > PETE_TBTree< OpMod , typename T::PETE_Expr_t, PETE_Scalar< long > > operator% (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator%() [8/11]
template<class T > PETE_TBTree< OpMod , PETE_Scalar< float >, typename T::PETE_Expr_t> operator% (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator%() [9/11]
template<class T > PETE_TBTree< OpMod , typename T::PETE_Expr_t, PETE_Scalar< float > > operator% (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator%() [10/11]
template<class T > PETE_TBTree< OpMod , PETE_Scalar< double >, typename T::PETE_Expr_t> operator% (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator%() [11/11]
template<class T > PETE_TBTree< OpMod , typename T::PETE_Expr_t, PETE_Scalar< double > > operator% (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator*() [1/11]
template<class T1 , class T2 > PETE_TBTree< OpMultipply , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator* (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 800 of file PETE.h.
operator*() [2/11]
template<class T > PETE_TBTree< OpMultipply , PETE_Scalar< short >, typename T::PETE_Expr_t> operator* (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator*() [3/11]
template<class T > PETE_TBTree< OpMultipply , typename T::PETE_Expr_t, PETE_Scalar< short > > operator* (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator*() [4/11]
template<class T > PETE_TBTree< OpMultipply , typename T::PETE_Expr_t, PETE_Scalar< int > > operator* (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator*() [5/11]
template<class T > PETE_TBTree< OpMultipply , PETE_Scalar< int >, typename T::PETE_Expr_t> operator* (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator*() [6/11]
template<class T > PETE_TBTree< OpMultipply , typename T::PETE_Expr_t, PETE_Scalar< long > > operator* (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator*() [7/11]
template<class T > PETE_TBTree< OpMultipply , PETE_Scalar< long >, typename T::PETE_Expr_t> operator* (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator*() [8/11]
template<class T > PETE_TBTree< OpMultipply , PETE_Scalar< float >, typename T::PETE_Expr_t> operator* (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator*() [9/11]
template<class T > PETE_TBTree< OpMultipply , typename T::PETE_Expr_t, PETE_Scalar< float > > operator* (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator*() [10/11]
template<class T > PETE_TBTree< OpMultipply , PETE_Scalar< double >, typename T::PETE_Expr_t> operator* (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator*() [11/11]
template<class T > PETE_TBTree< OpMultipply , typename T::PETE_Expr_t, PETE_Scalar< double > > operator* (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator+() [1/12]
template<class T > PETE_TUTree< OpUnaryPlus , typename T::PETE_Expr_t> operator+ (const PETE_Expr< T > & l) inline
Definition at line 720 of file PETE.h.
operator+() [2/12]
template<class T1 , class T2 > PETE_TBTree< OpAdd , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator+ (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 798 of file PETE.h.
operator+() [3/12]
template<class T > PETE_TBTree< OpAdd , PETE_Scalar< short >, typename T::PETE_Expr_t> operator+ (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator+() [4/12]
template<class T > PETE_TBTree< OpAdd , typename T::PETE_Expr_t, PETE_Scalar< short > > operator+ (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator+() [5/12]
template<class T > PETE_TBTree< OpAdd , PETE_Scalar< int >, typename T::PETE_Expr_t> operator+ (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator+() [6/12]
template<class T > PETE_TBTree< OpAdd , typename T::PETE_Expr_t, PETE_Scalar< int > > operator+ (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator+() [7/12]
template<class T > PETE_TBTree< OpAdd , PETE_Scalar< long >, typename T::PETE_Expr_t> operator+ (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator+() [8/12]
template<class T > PETE_TBTree< OpAdd , typename T::PETE_Expr_t, PETE_Scalar< long > > operator+ (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator+() [9/12]
template<class T > PETE_TBTree< OpAdd , PETE_Scalar< float >, typename T::PETE_Expr_t> operator+ (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator+() [10/12]
template<class T > PETE_TBTree< OpAdd , typename T::PETE_Expr_t, PETE_Scalar< float > > operator+ (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator+() [11/12]
template<class T > PETE_TBTree< OpAdd , PETE_Scalar< double >, typename T::PETE_Expr_t> operator+ (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator+() [12/12]
template<class T > PETE_TBTree< OpAdd , typename T::PETE_Expr_t, PETE_Scalar< double > > operator+ (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator-() [1/12]
template<class T > PETE_TUTree< OpUnaryMinus , typename T::PETE_Expr_t> operator- (const PETE_Expr< T > & l) inline
Definition at line 719 of file PETE.h.
operator-() [2/12]
template<class T1 , class T2 > PETE_TBTree< OpSubtract , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator- (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 799 of file PETE.h.
operator-() [3/12]
template<class T > PETE_TBTree< OpSubtract , typename T::PETE_Expr_t, PETE_Scalar< short > > operator- (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator-() [4/12]
template<class T > PETE_TBTree< OpSubtract , PETE_Scalar< short >, typename T::PETE_Expr_t> operator- (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator-() [5/12]
template<class T > PETE_TBTree< OpSubtract , PETE_Scalar< int >, typename T::PETE_Expr_t> operator- (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator-() [6/12]
template<class T > PETE_TBTree< OpSubtract , typename T::PETE_Expr_t, PETE_Scalar< int > > operator- (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator-() [7/12]
template<class T > PETE_TBTree< OpSubtract , PETE_Scalar< long >, typename T::PETE_Expr_t> operator- (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator-() [8/12]
template<class T > PETE_TBTree< OpSubtract , typename T::PETE_Expr_t, PETE_Scalar< long > > operator- (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator-() [9/12]
template<class T > PETE_TBTree< OpSubtract , typename T::PETE_Expr_t, PETE_Scalar< float > > operator- (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator-() [10/12]
template<class T > PETE_TBTree< OpSubtract , PETE_Scalar< float >, typename T::PETE_Expr_t> operator- (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator-() [11/12]
template<class T > PETE_TBTree< OpSubtract , typename T::PETE_Expr_t, PETE_Scalar< double > > operator- (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator-() [12/12]
template<class T > PETE_TBTree< OpSubtract , PETE_Scalar< double >, typename T::PETE_Expr_t> operator- (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator/() [1/11]
template<class T1 , class T2 > PETE_TBTree< OpDivide , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator/ (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 801 of file PETE.h.
operator/() [2/11]
template<class T > PETE_TBTree< OpDivide , PETE_Scalar< short >, typename T::PETE_Expr_t> operator/ (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator/() [3/11]
template<class T > PETE_TBTree< OpDivide , typename T::PETE_Expr_t, PETE_Scalar< short > > operator/ (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator/() [4/11]
template<class T > PETE_TBTree< OpDivide , typename T::PETE_Expr_t, PETE_Scalar< int > > operator/ (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator/() [5/11]
template<class T > PETE_TBTree< OpDivide , PETE_Scalar< int >, typename T::PETE_Expr_t> operator/ (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator/() [6/11]
template<class T > PETE_TBTree< OpDivide , PETE_Scalar< long >, typename T::PETE_Expr_t> operator/ (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator/() [7/11]
template<class T > PETE_TBTree< OpDivide , typename T::PETE_Expr_t, PETE_Scalar< long > > operator/ (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator/() [8/11]
template<class T > PETE_TBTree< OpDivide , PETE_Scalar< float >, typename T::PETE_Expr_t> operator/ (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator/() [9/11]
template<class T > PETE_TBTree< OpDivide , typename T::PETE_Expr_t, PETE_Scalar< float > > operator/ (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator/() [10/11]
template<class T > PETE_TBTree< OpDivide , typename T::PETE_Expr_t, PETE_Scalar< double > > operator/ (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator/() [11/11]
template<class T > PETE_TBTree< OpDivide , PETE_Scalar< double >, typename T::PETE_Expr_t> operator/ (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator<() [1/11]
template<class T1 , class T2 > PETE_TBTree< OpLT , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator< (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 803 of file PETE.h.
operator<() [2/11]
template<class T > PETE_TBTree< OpLT , PETE_Scalar< short >, typename T::PETE_Expr_t> operator< (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator<() [3/11]
template<class T > PETE_TBTree< OpLT , typename T::PETE_Expr_t, PETE_Scalar< short > > operator< (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator<() [4/11]
template<class T > PETE_TBTree< OpLT , PETE_Scalar< int >, typename T::PETE_Expr_t> operator< (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator<() [5/11]
template<class T > PETE_TBTree< OpLT , typename T::PETE_Expr_t, PETE_Scalar< int > > operator< (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator<() [6/11]
template<class T > PETE_TBTree< OpLT , PETE_Scalar< long >, typename T::PETE_Expr_t> operator< (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator<() [7/11]
template<class T > PETE_TBTree< OpLT , typename T::PETE_Expr_t, PETE_Scalar< long > > operator< (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator<() [8/11]
template<class T > PETE_TBTree< OpLT , PETE_Scalar< float >, typename T::PETE_Expr_t> operator< (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator<() [9/11]
template<class T > PETE_TBTree< OpLT , typename T::PETE_Expr_t, PETE_Scalar< float > > operator< (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator<() [10/11]
template<class T > PETE_TBTree< OpLT , PETE_Scalar< double >, typename T::PETE_Expr_t> operator< (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator<() [11/11]
template<class T > PETE_TBTree< OpLT , typename T::PETE_Expr_t, PETE_Scalar< double > > operator< (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator<=() [1/11]
template<class T1 , class T2 > PETE_TBTree< OpLE , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator<= (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 804 of file PETE.h.
operator<=() [2/11]
template<class T > PETE_TBTree< OpLE , typename T::PETE_Expr_t, PETE_Scalar< short > > operator<= (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator<=() [3/11]
template<class T > PETE_TBTree< OpLE , PETE_Scalar< short >, typename T::PETE_Expr_t> operator<= (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator<=() [4/11]
template<class T > PETE_TBTree< OpLE , PETE_Scalar< int >, typename T::PETE_Expr_t> operator<= (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator<=() [5/11]
template<class T > PETE_TBTree< OpLE , typename T::PETE_Expr_t, PETE_Scalar< int > > operator<= (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator<=() [6/11]
template<class T > PETE_TBTree< OpLE , PETE_Scalar< long >, typename T::PETE_Expr_t> operator<= (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator<=() [7/11]
template<class T > PETE_TBTree< OpLE , typename T::PETE_Expr_t, PETE_Scalar< long > > operator<= (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator<=() [8/11]
template<class T > PETE_TBTree< OpLE , typename T::PETE_Expr_t, PETE_Scalar< float > > operator<= (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator<=() [9/11]
template<class T > PETE_TBTree< OpLE , PETE_Scalar< float >, typename T::PETE_Expr_t> operator<= (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator<=() [10/11]
template<class T > PETE_TBTree< OpLE , typename T::PETE_Expr_t, PETE_Scalar< double > > operator<= (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator<=() [11/11]
template<class T > PETE_TBTree< OpLE , PETE_Scalar< double >, typename T::PETE_Expr_t> operator<= (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator==() [1/11]
template<class T1 , class T2 > PETE_TBTree< OpEQ , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator== (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 807 of file PETE.h.
operator==() [2/11]
template<class T > PETE_TBTree< OpEQ , PETE_Scalar< short >, typename T::PETE_Expr_t> operator== (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator==() [3/11]
template<class T > PETE_TBTree< OpEQ , typename T::PETE_Expr_t, PETE_Scalar< short > > operator== (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator==() [4/11]
template<class T > PETE_TBTree< OpEQ , PETE_Scalar< int >, typename T::PETE_Expr_t> operator== (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator==() [5/11]
template<class T > PETE_TBTree< OpEQ , typename T::PETE_Expr_t, PETE_Scalar< int > > operator== (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator==() [6/11]
template<class T > PETE_TBTree< OpEQ , PETE_Scalar< long >, typename T::PETE_Expr_t> operator== (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator==() [7/11]
template<class T > PETE_TBTree< OpEQ , typename T::PETE_Expr_t, PETE_Scalar< long > > operator== (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator==() [8/11]
template<class T > PETE_TBTree< OpEQ , PETE_Scalar< float >, typename T::PETE_Expr_t> operator== (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator==() [9/11]
template<class T > PETE_TBTree< OpEQ , typename T::PETE_Expr_t, PETE_Scalar< float > > operator== (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator==() [10/11]
template<class T > PETE_TBTree< OpEQ , PETE_Scalar< double >, typename T::PETE_Expr_t> operator== (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator==() [11/11]
template<class T > PETE_TBTree< OpEQ , typename T::PETE_Expr_t, PETE_Scalar< double > > operator== (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator>() [1/11]
template<class T1 , class T2 > PETE_TBTree< OpGT , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator> (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 805 of file PETE.h.
operator>() [2/11]
template<class T > PETE_TBTree< OpGT , PETE_Scalar< short >, typename T::PETE_Expr_t> operator> (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator>() [3/11]
template<class T > PETE_TBTree< OpGT , typename T::PETE_Expr_t, PETE_Scalar< short > > operator> (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator>() [4/11]
template<class T > PETE_TBTree< OpGT , typename T::PETE_Expr_t, PETE_Scalar< int > > operator> (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator>() [5/11]
template<class T > PETE_TBTree< OpGT , PETE_Scalar< int >, typename T::PETE_Expr_t> operator> (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator>() [6/11]
template<class T > PETE_TBTree< OpGT , PETE_Scalar< long >, typename T::PETE_Expr_t> operator> (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator>() [7/11]
template<class T > PETE_TBTree< OpGT , typename T::PETE_Expr_t, PETE_Scalar< long > > operator> (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator>() [8/11]
template<class T > PETE_TBTree< OpGT , PETE_Scalar< float >, typename T::PETE_Expr_t> operator> (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator>() [9/11]
template<class T > PETE_TBTree< OpGT , typename T::PETE_Expr_t, PETE_Scalar< float > > operator> (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator>() [10/11]
template<class T > PETE_TBTree< OpGT , PETE_Scalar< double >, typename T::PETE_Expr_t> operator> (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator>() [11/11]
template<class T > PETE_TBTree< OpGT , typename T::PETE_Expr_t, PETE_Scalar< double > > operator> (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator>=() [1/11]
template<class T1 , class T2 > PETE_TBTree< OpGE , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator>= (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 806 of file PETE.h.
operator>=() [2/11]
template<class T > PETE_TBTree< OpGE , PETE_Scalar< short >, typename T::PETE_Expr_t> operator>= (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator>=() [3/11]
template<class T > PETE_TBTree< OpGE , typename T::PETE_Expr_t, PETE_Scalar< short > > operator>= (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator>=() [4/11]
template<class T > PETE_TBTree< OpGE , PETE_Scalar< int >, typename T::PETE_Expr_t> operator>= (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator>=() [5/11]
template<class T > PETE_TBTree< OpGE , typename T::PETE_Expr_t, PETE_Scalar< int > > operator>= (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator>=() [6/11]
template<class T > PETE_TBTree< OpGE , typename T::PETE_Expr_t, PETE_Scalar< long > > operator>= (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator>=() [7/11]
template<class T > PETE_TBTree< OpGE , PETE_Scalar< long >, typename T::PETE_Expr_t> operator>= (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator>=() [8/11]
template<class T > PETE_TBTree< OpGE , typename T::PETE_Expr_t, PETE_Scalar< float > > operator>= (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator>=() [9/11]
template<class T > PETE_TBTree< OpGE , PETE_Scalar< float >, typename T::PETE_Expr_t> operator>= (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator>=() [10/11]
template<class T > PETE_TBTree< OpGE , PETE_Scalar< double >, typename T::PETE_Expr_t> operator>= (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator>=() [11/11]
template<class T > PETE_TBTree< OpGE , typename T::PETE_Expr_t, PETE_Scalar< double > > operator>= (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator^() [1/11]
template<class T1 , class T2 > PETE_TBTree< OpBitwiseXor , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator^ (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 813 of file PETE.h.
operator^() [2/11]
template<class T > PETE_TBTree< OpBitwiseXor , PETE_Scalar< short >, typename T::PETE_Expr_t> operator^ (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator^() [3/11]
template<class T > PETE_TBTree< OpBitwiseXor , typename T::PETE_Expr_t, PETE_Scalar< short > > operator^ (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator^() [4/11]
template<class T > PETE_TBTree< OpBitwiseXor , PETE_Scalar< int >, typename T::PETE_Expr_t> operator^ (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator^() [5/11]
template<class T > PETE_TBTree< OpBitwiseXor , typename T::PETE_Expr_t, PETE_Scalar< int > > operator^ (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator^() [6/11]
template<class T > PETE_TBTree< OpBitwiseXor , PETE_Scalar< long >, typename T::PETE_Expr_t> operator^ (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator^() [7/11]
template<class T > PETE_TBTree< OpBitwiseXor , typename T::PETE_Expr_t, PETE_Scalar< long > > operator^ (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator^() [8/11]
template<class T > PETE_TBTree< OpBitwiseXor , PETE_Scalar< float >, typename T::PETE_Expr_t> operator^ (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator^() [9/11]
template<class T > PETE_TBTree< OpBitwiseXor , typename T::PETE_Expr_t, PETE_Scalar< float > > operator^ (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator^() [10/11]
template<class T > PETE_TBTree< OpBitwiseXor , PETE_Scalar< double >, typename T::PETE_Expr_t> operator^ (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator^() [11/11]
template<class T > PETE_TBTree< OpBitwiseXor , typename T::PETE_Expr_t, PETE_Scalar< double > > operator^ (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator|() [1/11]
template<class T1 , class T2 > PETE_TBTree< OpBitwiseOr , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator| (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 812 of file PETE.h.
operator|() [2/11]
template<class T > PETE_TBTree< OpBitwiseOr , PETE_Scalar< short >, typename T::PETE_Expr_t> operator| (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator|() [3/11]
template<class T > PETE_TBTree< OpBitwiseOr , typename T::PETE_Expr_t, PETE_Scalar< short > > operator| (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator|() [4/11]
template<class T > PETE_TBTree< OpBitwiseOr , PETE_Scalar< int >, typename T::PETE_Expr_t> operator| (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator|() [5/11]
template<class T > PETE_TBTree< OpBitwiseOr , typename T::PETE_Expr_t, PETE_Scalar< int > > operator| (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator|() [6/11]
template<class T > PETE_TBTree< OpBitwiseOr , typename T::PETE_Expr_t, PETE_Scalar< long > > operator| (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator|() [7/11]
template<class T > PETE_TBTree< OpBitwiseOr , PETE_Scalar< long >, typename T::PETE_Expr_t> operator| (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator|() [8/11]
template<class T > PETE_TBTree< OpBitwiseOr , PETE_Scalar< float >, typename T::PETE_Expr_t> operator| (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator|() [9/11]
template<class T > PETE_TBTree< OpBitwiseOr , typename T::PETE_Expr_t, PETE_Scalar< float > > operator| (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator|() [10/11]
template<class T > PETE_TBTree< OpBitwiseOr , typename T::PETE_Expr_t, PETE_Scalar< double > > operator| (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator|() [11/11]
template<class T > PETE_TBTree< OpBitwiseOr , PETE_Scalar< double >, typename T::PETE_Expr_t> operator| (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator||() [1/11]
template<class T1 , class T2 > PETE_TBTree< OpOr , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> operator|| (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 810 of file PETE.h.
operator||() [2/11]
template<class T > PETE_TBTree< OpOr , typename T::PETE_Expr_t, PETE_Scalar< short > > operator|| (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
operator||() [3/11]
template<class T > PETE_TBTree< OpOr , PETE_Scalar< short >, typename T::PETE_Expr_t> operator|| (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
operator||() [4/11]
template<class T > PETE_TBTree< OpOr , PETE_Scalar< int >, typename T::PETE_Expr_t> operator|| (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
operator||() [5/11]
template<class T > PETE_TBTree< OpOr , typename T::PETE_Expr_t, PETE_Scalar< int > > operator|| (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
operator||() [6/11]
template<class T > PETE_TBTree< OpOr , PETE_Scalar< long >, typename T::PETE_Expr_t> operator|| (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
operator||() [7/11]
template<class T > PETE_TBTree< OpOr , typename T::PETE_Expr_t, PETE_Scalar< long > > operator|| (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
operator||() [8/11]
template<class T > PETE_TBTree< OpOr , typename T::PETE_Expr_t, PETE_Scalar< float > > operator|| (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
operator||() [9/11]
template<class T > PETE_TBTree< OpOr , PETE_Scalar< float >, typename T::PETE_Expr_t> operator|| (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
operator||() [10/11]
template<class T > PETE_TBTree< OpOr , PETE_Scalar< double >, typename T::PETE_Expr_t> operator|| (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
operator||() [11/11]
template<class T > PETE_TBTree< OpOr , typename T::PETE_Expr_t, PETE_Scalar< double > > operator|| (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
operator~()
template<class T > PETE_TUTree< OpBitwiseNot , typename T::PETE_Expr_t> operator~ (const PETE_Expr< T > & l) inline
Definition at line 721 of file PETE.h.
PETE_apply() [1/56]
template<class T > PETEUnaryReturn<T, OpUnaryMinus >::type PETE_apply (OpUnaryMinus , const T & a) inline
Definition at line 719 of file PETE.h.
Referenced by struct_for_each< Op, T1, T2, Functor >::apply(), TrinaryForEach< Safe, T1, T2, T3, Op, Functor >::apply(), for_each(), PETE_Combiner< T, Op >::operator()(), and Reduction().
PETE_apply() [2/56]
template<class T > PETEUnaryReturn<T, OpUnaryPlus >::type PETE_apply (OpUnaryPlus , const T & a) inline
Definition at line 720 of file PETE.h.
PETE_apply() [3/56]
template<class T > PETEUnaryReturn<T, OpBitwiseNot >::type PETE_apply (OpBitwiseNot , const T & a) inline
Definition at line 721 of file PETE.h.
PETE_apply() [4/56]
template<class T > PETEUnaryReturn<T, OpNot >::type PETE_apply (OpNot , const T & a) inline
Definition at line 722 of file PETE.h.
PETE_apply() [5/56]
template<class T > PETEUnaryReturn<T, OpIdentity >::type PETE_apply (OpIdentity , const T & a) inline
Definition at line 723 of file PETE.h.
PETE_apply() [6/56]
template<class T > PETEUnaryReturn<T, FnArcCos >::type PETE_apply (FnArcCos , const T & a) inline
Definition at line 725 of file PETE.h.
PETE_apply() [7/56]
template<class T > PETEUnaryReturn<T, FnArcSin >::type PETE_apply (FnArcSin , const T & a) inline
Definition at line 726 of file PETE.h.
PETE_apply() [8/56]
template<class T > PETEUnaryReturn<T, FnArcTan >::type PETE_apply (FnArcTan , const T & a) inline
Definition at line 727 of file PETE.h.
PETE_apply() [9/56]
template<class T > PETEUnaryReturn<T, FnCeil >::type PETE_apply (FnCeil , const T & a) inline
Definition at line 728 of file PETE.h.
PETE_apply() [10/56]
template<class T > PETEUnaryReturn<T, FnCos >::type PETE_apply (FnCos , const T & a) inline
Definition at line 729 of file PETE.h.
PETE_apply() [11/56]
template<class T > PETEUnaryReturn<T, FnHypCos >::type PETE_apply (FnHypCos , const T & a) inline
Definition at line 730 of file PETE.h.
PETE_apply() [12/56]
template<class T > PETEUnaryReturn<T, FnExp >::type PETE_apply (FnExp , const T & a) inline
Definition at line 731 of file PETE.h.
PETE_apply() [13/56]
template<class T > PETEUnaryReturn<T, FnFabs >::type PETE_apply (FnFabs , const T & a) inline
Definition at line 732 of file PETE.h.
PETE_apply() [14/56]
template<class T > PETEUnaryReturn<T, FnFloor >::type PETE_apply (FnFloor , const T & a) inline
Definition at line 733 of file PETE.h.
PETE_apply() [15/56]
template<class T > PETEUnaryReturn<T, FnLog >::type PETE_apply (FnLog , const T & a) inline
Definition at line 734 of file PETE.h.
PETE_apply() [16/56]
template<class T > PETEUnaryReturn<T, FnLog10 >::type PETE_apply (FnLog10 , const T & a) inline
Definition at line 735 of file PETE.h.
PETE_apply() [17/56]
template<class T > PETEUnaryReturn<T, FnSin >::type PETE_apply (FnSin , const T & a) inline
Definition at line 736 of file PETE.h.
PETE_apply() [18/56]
template<class T > PETEUnaryReturn<T, FnHypSin >::type PETE_apply (FnHypSin , const T & a) inline
Definition at line 737 of file PETE.h.
PETE_apply() [19/56]
template<class T > PETEUnaryReturn<T, FnSqrt >::type PETE_apply (FnSqrt , const T & a) inline
Definition at line 738 of file PETE.h.
PETE_apply() [20/56]
template<class T > PETEUnaryReturn<T, FnTan >::type PETE_apply (FnTan , const T & a) inline
Definition at line 739 of file PETE.h.
PETE_apply() [21/56]
template<class T > PETEUnaryReturn<T, FnHypTan >::type PETE_apply (FnHypTan , const T & a) inline
Definition at line 740 of file PETE.h.
PETE_apply() [22/56]
template<class T > PETEUnaryReturn<T, FnErf >::type PETE_apply (FnErf , const T & a) inline
Definition at line 741 of file PETE.h.
PETE_apply() [23/56]
template<class T1 , class T2 > T1 PETE_apply (OpCast< T1 > , const T2 & a) inline
Definition at line 750 of file PETE.h.
References a.
PETE_apply() [24/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpAdd >::type PETE_apply (OpAdd , const T1 & a, const T2 & b) inline
Definition at line 798 of file PETE.h.
PETE_apply() [25/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpSubtract >::type PETE_apply (OpSubtract , const T1 & a, const T2 & b) inline
Definition at line 799 of file PETE.h.
PETE_apply() [26/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpMultipply >::type PETE_apply (OpMultipply , const T1 & a, const T2 & b) inline
Definition at line 800 of file PETE.h.
PETE_apply() [27/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpDivide >::type PETE_apply (OpDivide , const T1 & a, const T2 & b) inline
Definition at line 801 of file PETE.h.
PETE_apply() [28/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpMod >::type PETE_apply (OpMod , const T1 & a, const T2 & b) inline
Definition at line 802 of file PETE.h.
PETE_apply() [29/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpLT >::type PETE_apply (OpLT , const T1 & a, const T2 & b) inline
Definition at line 803 of file PETE.h.
PETE_apply() [30/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpLE >::type PETE_apply (OpLE , const T1 & a, const T2 & b) inline
Definition at line 804 of file PETE.h.
PETE_apply() [31/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpGT >::type PETE_apply (OpGT , const T1 & a, const T2 & b) inline
Definition at line 805 of file PETE.h.
PETE_apply() [32/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpGE >::type PETE_apply (OpGE , const T1 & a, const T2 & b) inline
Definition at line 806 of file PETE.h.
PETE_apply() [33/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpEQ >::type PETE_apply (OpEQ , const T1 & a, const T2 & b) inline
Definition at line 807 of file PETE.h.
PETE_apply() [34/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpNE >::type PETE_apply (OpNE , const T1 & a, const T2 & b) inline
Definition at line 808 of file PETE.h.
PETE_apply() [35/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpAnd >::type PETE_apply (OpAnd , const T1 & a, const T2 & b) inline
Definition at line 809 of file PETE.h.
PETE_apply() [36/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpOr >::type PETE_apply (OpOr , const T1 & a, const T2 & b) inline
Definition at line 810 of file PETE.h.
PETE_apply() [37/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpBitwiseAnd >::type PETE_apply (OpBitwiseAnd , const T1 & a, const T2 & b) inline
Definition at line 811 of file PETE.h.
PETE_apply() [38/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpBitwiseOr >::type PETE_apply (OpBitwiseOr , const T1 & a, const T2 & b) inline
Definition at line 812 of file PETE.h.
PETE_apply() [39/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, OpBitwiseXor >::type PETE_apply (OpBitwiseXor , const T1 & a, const T2 & b) inline
Definition at line 813 of file PETE.h.
PETE_apply() [40/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, FnCopysign >::type PETE_apply (FnCopysign , const T1 & a, const T2 & b) inline
Definition at line 817 of file PETE.h.
PETE_apply() [41/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, FnLdexp >::type PETE_apply (FnLdexp , const T1 & a, const T2 & b) inline
Definition at line 818 of file PETE.h.
PETE_apply() [42/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, FnPow >::type PETE_apply (FnPow , const T1 & a, const T2 & b) inline
Definition at line 819 of file PETE.h.
PETE_apply() [43/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, FnFmod >::type PETE_apply (FnFmod , const T1 & a, const T2 & b) inline
Definition at line 820 of file PETE.h.
PETE_apply() [44/56]
template<class T1 , class T2 > PETEBinaryReturn<T1, T2, FnArcTan2 >::type PETE_apply (FnArcTan2 , const T1 & a, const T2 & b) inline
Definition at line 821 of file PETE.h.
PETE_apply() [45/56]
template<class T1 , class T2 , class T3 > PETETrinaryReturn<T1,T2,T3,OpWhere>::type PETE_apply (OpWhere , const T1 & a, const T2 & b, const T3 & c) inline
Definition at line 868 of file PETE.h.
References a, and Physics::c.
PETE_apply() [46/56]
template<class T1 , class T2 > void PETE_apply (OpAssign , T1 & a, const T2 & b) inline
Definition at line 1055 of file PETE.h.
PETE_apply() [47/56]
template<class T1 , class T2 > void PETE_apply (OpAddAssign , T1 & a, const T2 & b) inline
Definition at line 1056 of file PETE.h.
PETE_apply() [48/56]
template<class T1 , class T2 > void PETE_apply (OpSubtractAssign , T1 & a, const T2 & b) inline
Definition at line 1057 of file PETE.h.
PETE_apply() [49/56]
template<class T1 , class T2 > void PETE_apply (OpMultipplyAssign , T1 & a, const T2 & b) inline
Definition at line 1058 of file PETE.h.
PETE_apply() [50/56]
template<class T1 , class T2 > void PETE_apply (OpDivideAssign , T1 & a, const T2 & b) inline
Definition at line 1059 of file PETE.h.
PETE_apply() [51/56]
template<class T1 , class T2 > void PETE_apply (OpModAssign , T1 & a, const T2 & b) inline
Definition at line 1060 of file PETE.h.
PETE_apply() [52/56]
template<class T1 , class T2 > void PETE_apply (OpBitwiseOrAssign , T1 & a, const T2 & b) inline
Definition at line 1061 of file PETE.h.
PETE_apply() [53/56]
template<class T1 , class T2 > void PETE_apply (OpBitwiseAndAssign , T1 & a, const T2 & b) inline
Definition at line 1062 of file PETE.h.
PETE_apply() [54/56]
template<class T1 , class T2 > void PETE_apply (OpBitwiseXorAssign , T1 & a, const T2 & b) inline
Definition at line 1063 of file PETE.h.
PETE_apply() [55/56]
template<class T1 , class T2 > void PETE_apply (OpLeftShiftAssign , T1 & a, const T2 & b) inline
Definition at line 1064 of file PETE.h.
PETE_apply() [56/56]
template<class T1 , class T2 > void PETE_apply (OpRightShiftAssign , T1 & a, const T2 & b) inline
Definition at line 1065 of file PETE.h.
pete_cast()
template<class T1 , class Expr > PETE_TUTree<OpCast<T1>, typename Expr::PETE_Expr_t> pete_cast (const T1 & , const PETE_Expr< Expr > & l) inline
Definition at line 757 of file PETE.h.
References PETE_Expr< WrappedExpr >::PETE_unwrap().
PETE_identity()
template<class T > PETE_TUTree< OpIdentity , typename T::PETE_Expr_t> PETE_identity (const PETE_Expr< T > & l) inline
Definition at line 723 of file PETE.h.
pow() [1/11]
template<class T1 , class T2 > PETE_TBTree< FnPow , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> pow (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 819 of file PETE.h.
pow() [2/11]
template<class T > PETE_TBTree< FnPow , PETE_Scalar< short >, typename T::PETE_Expr_t> pow (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
pow() [3/11]
template<class T > PETE_TBTree< FnPow , typename T::PETE_Expr_t, PETE_Scalar< short > > pow (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
pow() [4/11]
template<class T > PETE_TBTree< FnPow , PETE_Scalar< int >, typename T::PETE_Expr_t> pow (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
pow() [5/11]
template<class T > PETE_TBTree< FnPow , typename T::PETE_Expr_t, PETE_Scalar< int > > pow (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
pow() [6/11]
template<class T > PETE_TBTree< FnPow , typename T::PETE_Expr_t, PETE_Scalar< long > > pow (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
pow() [7/11]
template<class T > PETE_TBTree< FnPow , PETE_Scalar< long >, typename T::PETE_Expr_t> pow (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
pow() [8/11]
template<class T > PETE_TBTree< FnPow , PETE_Scalar< float >, typename T::PETE_Expr_t> pow (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
pow() [9/11]
template<class T > PETE_TBTree< FnPow , typename T::PETE_Expr_t, PETE_Scalar< float > > pow (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
pow() [10/11]
template<class T > PETE_TBTree< FnPow , PETE_Scalar< double >, typename T::PETE_Expr_t> pow (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
pow() [11/11]
template<class T > PETE_TBTree< FnPow , typename T::PETE_Expr_t, PETE_Scalar< double > > pow (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
prod()
template<class T > T::PETE_Expr_t::PETE_Return_t prod (const PETE_Expr< T > & expr) inline
Definition at line 1121 of file PETE.h.
References PETE_Expr< WrappedExpr >::PETE_unwrap(), and Reduction().
Referenced by MapGenerator< Value_type, Size_type, Series_type, Map_type, Hamiltonian_type, Space_charge_type >::combine(), RealDiracMatrix::diagonalize(), FTps< double, 2 *3 >::divide(), matt_boost::gemmm(), Distribution::generateMatchedGauss(), Bend2D::getSurfaceMesh(), FTps< double, 2 *3 >::inverse(), mslang::AffineTransformation::mult(), Tps< T >::multiply(), matt_boost::taylor_exp(), RealDiracMatrix::transform(), FLieGenerator< T, N >::transform(), mslang::AffineTransformation::transformTo(), SigmaGenerator::updateInitialSigma(), and SigmaGenerator::updateSigma().
Reduction()
template<class R , class T , class InitOp , class AccOp > void Reduction (R & ret, const PETE_Expr< T > & const_expr, InitOp init_op, AccOp acc_op) inline
Definition at line 660 of file PETE.h.
References for_each(), Hypervolume::n, PETE_apply(), PETE_Expr< WrappedExpr >::PETE_unwrap(), and PETE_USER_REDUCTION_CODE.
Referenced by prod(), and sum().
sin()
template<class T > PETE_TUTree< FnSin , typename T::PETE_Expr_t> sin (const PETE_Expr< T > & l) inline
Definition at line 736 of file PETE.h.
sinh()
template<class T > PETE_TUTree< FnHypSin , typename T::PETE_Expr_t> sinh (const PETE_Expr< T > & l) inline
Definition at line 737 of file PETE.h.
sqrt()
template<class T > PETE_TUTree< FnSqrt , typename T::PETE_Expr_t> sqrt (const PETE_Expr< T > & l) inline
Definition at line 738 of file PETE.h.
sum()
template<class T > T::PETE_Expr_t::PETE_Return_t sum (const PETE_Expr< T > & expr) inline
Definition at line 1111 of file PETE.h.
References PETE_Expr< WrappedExpr >::PETE_unwrap(), and Reduction().
Referenced by TSV_MetaDotDot< Tenzor< T1, D >, Tenzor< T2, D > >::apply(), TSV_MetaDot< Tenzor< T1, D >, Tenzor< T2, D > >::apply(), TSV_MetaDotDot< SymTenzor< T1, D >, SymTenzor< T2, D > >::apply(), TSV_MetaDotDot< SymTenzor< T1, D >, Tenzor< T2, D > >::apply(), TSV_MetaDot< SymTenzor< T1, D >, SymTenzor< T2, D > >::apply(), TSV_MetaDotDot< Tenzor< T1, D >, SymTenzor< T2, D > >::apply(), TSV_MetaDot< Tenzor< T1, D >, Vektor< T2, D > >::apply(), TSV_MetaDotDot< AntiSymTenzor< T1, D >, AntiSymTenzor< T2, D > >::apply(), TSV_MetaDotDot< AntiSymTenzor< T1, 2 >, AntiSymTenzor< T2, 2 > >::apply(), TSV_MetaDotDot< AntiSymTenzor< T1, 3 >, AntiSymTenzor< T2, 3 > >::apply(), TSV_MetaDot< Vektor< T1, D >, Tenzor< T2, D > >::apply(), TSV_MetaDot< SymTenzor< T1, D >, Vektor< T2, D > >::apply(), TSV_MetaDot< Vektor< T1, D >, SymTenzor< T2, D > >::apply(), TSV_MetaDot< SymTenzor< T1, D >, Tenzor< T2, D > >::apply(), TSV_MetaDot< Tenzor< T1, D >, SymTenzor< T2, D > >::apply(), TSV_MetaDot< Vektor< T1, D >, AntiSymTenzor< T2, D > >::apply(), TSV_MetaDot< AntiSymTenzor< T1, D >, Vektor< T2, D > >::apply(), FLUMatrix< T, N >::backSubstitute(), LUMatrix< T >::backSubstitute(), AmrParticleLevelCounter< size_t, size_t >::begin(), PartBunchBase< double, 3 >::boundp(), SocialNetworkGraph< TopoDiscoveryStrategy_t >::chooseRandomNeighbor(), ParallelCyclotronTracker::computePathLengthUpdate(), PartBunch::computeSelfFields(), PartBunch::computeSelfFields_cycl(), ParallelCyclotronTracker::deleteParticle(), Statistics< T >::dumpStatistics(), PartBunchBase< double, 3 >::getCharge(), AmrParticleLevelCounter< size_t, size_t >::getLocalNumUpToLevel(), ParallelCyclotronTracker::getTunes(), lubksb(), ludcmp(), SumErrSqRadialPeak::operator()(), FromFile::operator()(), SumErrSq::operator()(), polynomial::PolynomialSum::operator=(), Mesher::orientVerticesCCW(), PartBunchBase< double, 3 >::print(), Distribution::printEnergyBins(), IpplParticleBase< T >::resetID(), savgol(), scaled_norm(), _FM3DMagnetoStaticExtended::smoothData(), FVps< T, N >::substituteInto(), and matt_boost::trace().
tan()
template<class T > PETE_TUTree< FnTan , typename T::PETE_Expr_t> tan (const PETE_Expr< T > & l) inline
Definition at line 739 of file PETE.h.
tanh()
template<class T > PETE_TUTree< FnHypTan , typename T::PETE_Expr_t> tanh (const PETE_Expr< T > & l) inline
Definition at line 740 of file PETE.h.
where() [1/27]
template<class Cond_t , class True_t , class False_t > PETE_TTTree<OpWhere, typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, typename False_t::PETE_Expr_t> where (const PETE_Expr< Cond_t > & c, const PETE_Expr< True_t > & t, const PETE_Expr< False_t > & f) inline
Definition at line 877 of file PETE.h.
References Physics::c, and PETE_Expr< WrappedExpr >::PETE_unwrap().
where() [2/27]
template<class T1 , class T2 > PETE_TBTree< OpWhere , typename T1::PETE_Expr_t, typename T2::PETE_Expr_t> where (const PETE_Expr< T1 > & l, const PETE_Expr< T2 > & r) inline
Definition at line 978 of file PETE.h.
where() [3/27]
template<class T > PETE_TBTree< OpWhere , PETE_Scalar< short >, typename T::PETE_Expr_t> where (const short l, const PETE_Expr< T > & r) inline
Definition at line 1016 of file PETE.h.
where() [4/27]
template<class Cond_t , class False_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< short >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > & c, short t, const PETE_Expr< False_t > & f) inline
Definition at line 1016 of file PETE.h.
where() [5/27]
template<class Cond_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< short >, PETE_Scalar< short > > where (const PETE_Expr< Cond_t > & c, short t, short f) inline
Definition at line 1016 of file PETE.h.
where() [6/27]
template<class T > PETE_TBTree< OpWhere , typename T::PETE_Expr_t, PETE_Scalar< short > > where (const PETE_Expr< T > & l, const short r) inline
Definition at line 1016 of file PETE.h.
where() [7/27]
template<class Cond_t , class True_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< short > > where (const PETE_Expr< Cond_t > & c, const PETE_Expr< True_t > & t, short f) inline
Definition at line 1016 of file PETE.h.
where() [8/27]
template<class T > PETE_TBTree< OpWhere , PETE_Scalar< int >, typename T::PETE_Expr_t> where (const int l, const PETE_Expr< T > & r) inline
Definition at line 1017 of file PETE.h.
where() [9/27]
template<class Cond_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< int >, PETE_Scalar< int > > where (const PETE_Expr< Cond_t > & c, int t, int f) inline
Definition at line 1017 of file PETE.h.
where() [10/27]
template<class T > PETE_TBTree< OpWhere , typename T::PETE_Expr_t, PETE_Scalar< int > > where (const PETE_Expr< T > & l, const int r) inline
Definition at line 1017 of file PETE.h.
where() [11/27]
template<class Cond_t , class True_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< int > > where (const PETE_Expr< Cond_t > & c, const PETE_Expr< True_t > & t, int f) inline
Definition at line 1017 of file PETE.h.
where() [12/27]
template<class Cond_t , class False_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< int >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > & c, int t, const PETE_Expr< False_t > & f) inline
Definition at line 1017 of file PETE.h.
where() [13/27]
template<class Cond_t , class False_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< long >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > & c, long t, const PETE_Expr< False_t > & f) inline
Definition at line 1018 of file PETE.h.
where() [14/27]
template<class Cond_t , class True_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< long > > where (const PETE_Expr< Cond_t > & c, const PETE_Expr< True_t > & t, long f) inline
Definition at line 1018 of file PETE.h.
where() [15/27]
template<class T > PETE_TBTree< OpWhere , PETE_Scalar< long >, typename T::PETE_Expr_t> where (const long l, const PETE_Expr< T > & r) inline
Definition at line 1018 of file PETE.h.
where() [16/27]
template<class Cond_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< long >, PETE_Scalar< long > > where (const PETE_Expr< Cond_t > & c, long t, long f) inline
Definition at line 1018 of file PETE.h.
where() [17/27]
template<class T > PETE_TBTree< OpWhere , typename T::PETE_Expr_t, PETE_Scalar< long > > where (const PETE_Expr< T > & l, const long r) inline
Definition at line 1018 of file PETE.h.
where() [18/27]
template<class Cond_t , class False_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< float >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > & c, float t, const PETE_Expr< False_t > & f) inline
Definition at line 1019 of file PETE.h.
where() [19/27]
template<class Cond_t , class True_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< float > > where (const PETE_Expr< Cond_t > & c, const PETE_Expr< True_t > & t, float f) inline
Definition at line 1019 of file PETE.h.
where() [20/27]
template<class T > PETE_TBTree< OpWhere , typename T::PETE_Expr_t, PETE_Scalar< float > > where (const PETE_Expr< T > & l, const float r) inline
Definition at line 1019 of file PETE.h.
where() [21/27]
template<class Cond_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< float >, PETE_Scalar< float > > where (const PETE_Expr< Cond_t > & c, float t, float f) inline
Definition at line 1019 of file PETE.h.
where() [22/27]
template<class T > PETE_TBTree< OpWhere , PETE_Scalar< float >, typename T::PETE_Expr_t> where (const float l, const PETE_Expr< T > & r) inline
Definition at line 1019 of file PETE.h.
where() [23/27]
template<class T > PETE_TBTree< OpWhere , PETE_Scalar< double >, typename T::PETE_Expr_t> where (const double l, const PETE_Expr< T > & r) inline
Definition at line 1020 of file PETE.h.
where() [24/27]
template<class Cond_t , class True_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< double > > where (const PETE_Expr< Cond_t > & c, const PETE_Expr< True_t > & t, double f) inline
Definition at line 1020 of file PETE.h.
where() [25/27]
template<class Cond_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< double >, PETE_Scalar< double > > where (const PETE_Expr< Cond_t > & c, double t, double f) inline
Definition at line 1020 of file PETE.h.
where() [26/27]
template<class T > PETE_TBTree< OpWhere , typename T::PETE_Expr_t, PETE_Scalar< double > > where (const PETE_Expr< T > & l, const double r) inline
Definition at line 1020 of file PETE.h.
where() [27/27]
template<class Cond_t , class False_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< double >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > & c, double t, const PETE_Expr< False_t > & f) inline
Definition at line 1020 of file PETE.h.