OPAL (Object Oriented Parallel Accelerator Library): LSIndex< Dim > Class Template Reference
LSIndex< Dim > Class Template Reference
#include <LSIndex.h>
Public Types
typedef std::vector< SOffset< Dim > > container_t
typedef container_t::iterator iterator
typedef container_t::const_iterator const_iterator
typedef container_t::size_type size_type
Public Member Functions
LSIndex (Vnode< Dim > *vn)
LSIndex (const LSIndex< Dim > &lsi)
~LSIndex ()
LSIndex & operator= (const LSIndex &lsi)
bool IsCompressed () const
void Compress (bool docompress)
bool contains (const SOffset< Dim > &indx)
void addIndex (const SOffset< Dim > &indx)
SOffset< Dim > & getIndex (unsigned int n)
SOffset< Dim > getIndex (unsigned int n) const
void removeIndex (const SOffset< Dim > &indx)
void clear ()
void reserve (size_type n)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
size_type capacity () const
size_type size () const
iterator find (const SOffset< Dim > &indx)
bool hasIndex (const SOffset< Dim > &indx) const
const NDIndex< Dim > & getDomain () const
int getNode () const
Private Attributes
Vnode< Dim > * VN
container_t IndexList
bool compressed
SOffset< Dim > CompressedPoint
vec< int, Dim > Strides
Detailed Description
template<unsigned int Dim>
class LSIndex< Dim >
Definition at line 32 of file LSIndex.h.
Member Typedef Documentation
const_iterator
template<unsigned int Dim> typedef container_t::const_iterator LSIndex< Dim >::const_iterator
Definition at line 38 of file LSIndex.h.
container_t
template<unsigned int Dim> typedef std::vector< SOffset<Dim> > LSIndex< Dim >::container_t
Definition at line 36 of file LSIndex.h.
iterator
template<unsigned int Dim> typedef container_t::iterator LSIndex< Dim >::iterator
Definition at line 37 of file LSIndex.h.
size_type
template<unsigned int Dim> typedef container_t::size_type LSIndex< Dim >::size_type
Definition at line 39 of file LSIndex.h.
Constructor & Destructor Documentation
LSIndex() [1/2]
template<unsigned int Dim> LSIndex< Dim >::LSIndex (Vnode< Dim > * vn) inline
Definition at line 43 of file LSIndex.h.
References Dim, Vnode< Dim >::getDomain(), and LSIndex< Dim >::Strides.
LSIndex() [2/2]
template<unsigned int Dim> LSIndex< Dim >::LSIndex (const LSIndex< Dim > & lsi) inline
Definition at line 50 of file LSIndex.h.
~LSIndex()
template<unsigned int Dim> LSIndex< Dim >::~LSIndex () inline
Definition at line 55 of file LSIndex.h.
Member Function Documentation
addIndex()
template<unsigned int Dim> void LSIndex< Dim >::addIndex (const SOffset< Dim > & indx) inline
Definition at line 82 of file LSIndex.h.
References LSIndex< Dim >::compressed, and LSIndex< Dim >::IndexList.
begin() [1/2]
template<unsigned int Dim> iterator LSIndex< Dim >::begin () inline
Definition at line 153 of file LSIndex.h.
References LSIndex< Dim >::IndexList.
Referenced by LSIndex< Dim >::find(), LSIndex< Dim >::hasIndex(), and SIndex< Dim >::operator|=().
begin() [2/2]
template<unsigned int Dim> const_iterator LSIndex< Dim >::begin () const inline
Definition at line 155 of file LSIndex.h.
References LSIndex< Dim >::IndexList.
capacity()
template<unsigned int Dim> size_type LSIndex< Dim >::capacity () const inline
Definition at line 159 of file LSIndex.h.
References LSIndex< Dim >::IndexList.
clear()
template<unsigned int Dim> void LSIndex< Dim >::clear () inline
Definition at line 143 of file LSIndex.h.
References LSIndex< Dim >::IndexList.
Referenced by LSIndex< Dim >::Compress().
Compress()
template<unsigned int Dim> void LSIndex< Dim >::Compress (bool docompress) inline
Definition at line 70 of file LSIndex.h.
References LSIndex< Dim >::clear(), and LSIndex< Dim >::compressed.
contains()
template<unsigned int Dim> bool LSIndex< Dim >::contains (const SOffset< Dim > & indx) inline
Definition at line 76 of file LSIndex.h.
References SOffset< Dim >::inside(), and LSIndex< Dim >::VN.
end() [1/2]
template<unsigned int Dim> iterator LSIndex< Dim >::end () inline
Definition at line 154 of file LSIndex.h.
References LSIndex< Dim >::IndexList.
Referenced by LSIndex< Dim >::find(), LSIndex< Dim >::hasIndex(), SIndex< Dim >::operator|=(), and LSIndex< Dim >::removeIndex().
end() [2/2]
template<unsigned int Dim> const_iterator LSIndex< Dim >::end () const inline
Definition at line 156 of file LSIndex.h.
References LSIndex< Dim >::IndexList.
find()
template<unsigned int Dim> iterator LSIndex< Dim >::find (const SOffset< Dim > & indx) inline
Definition at line 166 of file LSIndex.h.
References a, LSIndex< Dim >::begin(), and LSIndex< Dim >::end().
getDomain()
template<unsigned int Dim> const NDIndex<Dim>& LSIndex< Dim >::getDomain (void) const inline
Definition at line 186 of file LSIndex.h.
References LSIndex< Dim >::VN.
getIndex() [1/2]
template<unsigned int Dim> SOffset<Dim>& LSIndex< Dim >::getIndex (unsigned int n) inline
Definition at line 88 of file LSIndex.h.
References LSIndex< Dim >::compressed, LSIndex< Dim >::CompressedPoint, Dim, LSIndex< Dim >::IndexList, Hypervolume::n, LSIndex< Dim >::Strides, and LSIndex< Dim >::VN.
getIndex() [2/2]
template<unsigned int Dim> SOffset<Dim> LSIndex< Dim >::getIndex (unsigned int n) const inline
Definition at line 110 of file LSIndex.h.
References LSIndex< Dim >::compressed, Dim, LSIndex< Dim >::IndexList, Hypervolume::n, LSIndex< Dim >::Strides, and LSIndex< Dim >::VN.
getNode()
template<unsigned int Dim> int LSIndex< Dim >::getNode () const inline
Definition at line 189 of file LSIndex.h.
References LSIndex< Dim >::VN.
hasIndex()
template<unsigned int Dim> bool LSIndex< Dim >::hasIndex (const SOffset< Dim > & indx) const inline
Definition at line 174 of file LSIndex.h.
References a, LSIndex< Dim >::begin(), and LSIndex< Dim >::end().
IsCompressed()
template<unsigned int Dim> bool LSIndex< Dim >::IsCompressed () const inline
Definition at line 67 of file LSIndex.h.
References LSIndex< Dim >::compressed.
operator=()
template<unsigned int Dim> LSIndex& LSIndex< Dim >::operator= (const LSIndex< Dim > & lsi) inline
Definition at line 58 of file LSIndex.h.
References LSIndex< Dim >::compressed, LSIndex< Dim >::IndexList, LSIndex< Dim >::Strides, and LSIndex< Dim >::VN.
removeIndex()
template<unsigned int Dim> void LSIndex< Dim >::removeIndex (const SOffset< Dim > & indx) inline
Definition at line 134 of file LSIndex.h.
References LSIndex< Dim >::end(), and LSIndex< Dim >::IndexList.
reserve()
template<unsigned int Dim> void LSIndex< Dim >::reserve (size_type n) inline
Definition at line 146 of file LSIndex.h.
References LSIndex< Dim >::IndexList, and Hypervolume::n.
size()
template<unsigned int Dim> size_type LSIndex< Dim >::size (void) const inline
Definition at line 160 of file LSIndex.h.
References LSIndex< Dim >::compressed, LSIndex< Dim >::IndexList, and LSIndex< Dim >::VN.
Member Data Documentation
compressed
template<unsigned int Dim> bool LSIndex< Dim >::compressed private
Definition at line 200 of file LSIndex.h.
Referenced by LSIndex< Dim >::addIndex(), LSIndex< Dim >::Compress(), LSIndex< Dim >::getIndex(), LSIndex< Dim >::IsCompressed(), LSIndex< Dim >::operator=(), and LSIndex< Dim >::size().
CompressedPoint
template<unsigned int Dim> SOffset<Dim> LSIndex< Dim >::CompressedPoint private
Definition at line 201 of file LSIndex.h.
Referenced by LSIndex< Dim >::getIndex().
IndexList
template<unsigned int Dim> container_t LSIndex< Dim >::IndexList private
Definition at line 196 of file LSIndex.h.
Referenced by LSIndex< Dim >::addIndex(), LSIndex< Dim >::begin(), LSIndex< Dim >::capacity(), LSIndex< Dim >::clear(), LSIndex< Dim >::end(), LSIndex< Dim >::getIndex(), LSIndex< Dim >::operator=(), LSIndex< Dim >::removeIndex(), LSIndex< Dim >::reserve(), and LSIndex< Dim >::size().
Strides
template<unsigned int Dim> vec<int,Dim> LSIndex< Dim >::Strides private
Definition at line 204 of file LSIndex.h.
Referenced by LSIndex< Dim >::getIndex(), LSIndex< Dim >::LSIndex(), and LSIndex< Dim >::operator=().
VN
template<unsigned int Dim> Vnode<Dim>* LSIndex< Dim >::VN private
Definition at line 193 of file LSIndex.h.
Referenced by LSIndex< Dim >::contains(), LSIndex< Dim >::getDomain(), LSIndex< Dim >::getIndex(), LSIndex< Dim >::getNode(), LSIndex< Dim >::operator=(), and LSIndex< Dim >::size().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Index/LSIndex.h