OPAL (Object Oriented Parallel Accelerator Library): TrackCmd Class Reference
TrackCmd Class Reference
#include <TrackCmd.h>
Public Member Functions
TrackCmd ()
virtual ~TrackCmd ()
virtual TrackCmd * clone (const std::string &name)
Return a clone.
virtual void execute ()
Execute the command.
std::vector< double > getDT () const
Return the timestep in seconds.
double getDTSCINIT () const
double getDTAU () const
double getT0 () const
Return the elapsed time (sec) of the bunch.
std::vector< unsigned long long > getMaxSteps () const
Return the maximum timsteps we integrate the system.
int getStepsPerTurn () const
double getZStart () const
location at which the simulation starts
std::vector< double > getZStop () const
location at which the simulation stops
Steppers::TimeIntegrator getTimeIntegrator ()
return the name of time integrator
void setIsParseable (bool isParseable)
set the IsParseable flag
Public Member Functions inherited from Action
virtual ~Action ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
TrackCmd (const TrackCmd &)
void operator= (const TrackCmd &)
TrackCmd (const std::string &name, TrackCmd *parent)
Private Attributes
bool isParseable_m = true
Static Private Attributes
static const std::map< std::string, Steppers::TimeIntegrator > stringTimeIntegrator_s
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Action
Action (int size, const char *name, const char *help)
Constructor for exemplars.
Action (const std::string &name, Action *parent)
Constructor for cloning.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 27 of file TrackCmd.h.
Constructor & Destructor Documentation
TrackCmd() [1/3]
TrackCmd::TrackCmd ()
Definition at line 62 of file TrackCmd.cpp.
References AttributeHandler::addAttributeOwner(), AttributeHandler::COMMAND, Physics::e, Object::itsAttr, Attrib::Distribution::LINE, Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeRealArray(), Attributes::makeString(), and Object::registerOwnership().
Referenced by clone().
~TrackCmd()
TrackCmd::~TrackCmd () virtual
Definition at line 112 of file TrackCmd.cpp.
TrackCmd() [2/3]
TrackCmd::TrackCmd (const TrackCmd &) private
TrackCmd() [3/3]
TrackCmd::TrackCmd (const std::string & name, TrackCmd * parent) private
Definition at line 107 of file TrackCmd.cpp.
Member Function Documentation
clone()
TrackCmd * TrackCmd::clone (const std::string & name) virtual
Return a clone.
Implements Object.
Definition at line 116 of file TrackCmd.cpp.
References name, and TrackCmd().
execute()
void TrackCmd::execute () virtual
Execute the command.
Reimplemented from Object.
Definition at line 191 of file TrackCmd.cpp.
References Track::block, BeamSequence::find(), Beam::find(), getDT(), getDTAU(), getDTSCINIT(), getMaxSteps(), Attributes::getReal(), Beam::getReference(), getStepsPerTurn(), Attributes::getString(), getT0(), getTimeIntegrator(), getZStart(), getZStop(), isParseable_m, Object::itsAttr, Attrib::Distribution::LINE, max(), Track::parser, OpalParser::run(), and Track::truncOrder.
getDT()
std::vector< double > TrackCmd::getDT () const
Return the timestep in seconds.
Definition at line 120 of file TrackCmd.cpp.
References Physics::e, Attributes::getRealArray(), and Object::itsAttr.
Referenced by execute().
getDTAU()
double TrackCmd::getDTAU () const
Definition at line 138 of file TrackCmd.cpp.
References Attributes::getReal(), and Object::itsAttr.
Referenced by execute().
getDTSCINIT()
double TrackCmd::getDTSCINIT () const
Definition at line 134 of file TrackCmd.cpp.
References Attributes::getReal(), and Object::itsAttr.
Referenced by execute().
getMaxSteps()
std::vector< unsigned long long > TrackCmd::getMaxSteps () const
Return the maximum timsteps we integrate the system.
Definition at line 158 of file TrackCmd.cpp.
References Attributes::getRealArray(), and Object::itsAttr.
Referenced by execute().
getStepsPerTurn()
int TrackCmd::getStepsPerTurn () const
Return the timsteps per revolution period. ONLY available for OPAL-cycl. In OPAL-cycl, timestep is calculated by STEPSPERTURN, rather than given in TRACK command.
Definition at line 177 of file TrackCmd.cpp.
References Attributes::getReal(), and Object::itsAttr.
Referenced by execute().
getT0()
double TrackCmd::getT0 () const
Return the elapsed time (sec) of the bunch.
Definition at line 142 of file TrackCmd.cpp.
References Attributes::getReal(), and Object::itsAttr.
Referenced by execute().
getTimeIntegrator()
Steppers::TimeIntegrator TrackCmd::getTimeIntegrator ()
return the name of time integrator
Definition at line 181 of file TrackCmd.cpp.
References Attributes::getString(), Object::itsAttr, name, and stringTimeIntegrator_s.
Referenced by execute().
getZStart()
double TrackCmd::getZStart () const
location at which the simulation starts
Definition at line 146 of file TrackCmd.cpp.
References Attributes::getReal(), and Object::itsAttr.
Referenced by execute().
getZStop()
std::vector< double > TrackCmd::getZStop () const
location at which the simulation stops
Definition at line 150 of file TrackCmd.cpp.
References Attributes::getRealArray(), and Object::itsAttr.
Referenced by execute().
operator=()
void TrackCmd::operator= (const TrackCmd &) private
setIsParseable()
void TrackCmd::setIsParseable (bool isParseable)
set the IsParseable flag
Definition at line 186 of file TrackCmd.cpp.
References isParseable_m.
Member Data Documentation
isParseable_m
bool TrackCmd::isParseable_m = true private
Definition at line 76 of file TrackCmd.h.
Referenced by execute(), and setIsParseable().
stringTimeIntegrator_s
const std::map< std::string, Steppers::TimeIntegrator > TrackCmd::stringTimeIntegrator_s static private
Initial value:
= {
    {"RK-4", Steppers::TimeIntegrator::RK4},
    {"RK4",  Steppers::TimeIntegrator::RK4},
    {"LF-2", Steppers::TimeIntegrator::LF2},
    {"LF2",  Steppers::TimeIntegrator::LF2},
    {"MTS",  Steppers::TimeIntegrator::MTS}
}
Definition at line 77 of file TrackCmd.h.
Referenced by getTimeIntegrator().
The documentation for this class was generated from the following files:
src/Track/TrackCmd.h
src/Track/TrackCmd.cpp