OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/ParticleDebug.h File Reference
ParticleDebug.h File Reference
#include "Utility/ParticleDebugFunctions.h"
#include "Utility/ParticleDebug.hpp"
Classes
class ParticleAttrib< T >
Functions
template<class T >
void pap (ParticleAttrib< T > &pattr, bool docomm=true)
template<class T >
void epap (ParticleAttrib< T > &pattr, int i, bool docomm=true)
template<class T >
void spap (ParticleAttrib< T > &pattr, int ibase, int ibound, int istride, bool docomm=true)
Variables
Inform * PtclDbgInform
bool PtclDbgInformIsSet
Inform * FldDbgInform
bool FldDbgInformIsSet
int elementsPerLine
int digitsPastDecimal
int widthOfElements
Function Documentation
epap()
template<class T > void epap (ParticleAttrib< T > & pattr, int i, bool docomm = true)
Definition at line 98 of file ParticleDebug.hpp.
References FldDbgInform, FldDbgInformIsSet, INFORM_ALL_NODES, PtclDbgInform, PtclDbgInformIsSet, setPtclDbgInform(), and spap().
pap()
template<class T > void pap (ParticleAttrib< T > & pattr, bool docomm = true)
Definition at line 42 of file ParticleDebug.hpp.
References Communicate::barrier(), Communicate::broadcast_others(), IpplInfo::Comm, FldDbgInform, FldDbgInformIsSet, Message::get(), IpplInfo::getNodes(), INFORM_ALL_NODES, IPPL_APP_CYCLE, IPPL_APP_TAG0, IpplInfo::myNode(), TagMaker::next_tag(), PtclDbgInform, PtclDbgInformIsSet, Message::put(), Communicate::receive_block(), Communicate::send(), setPtclDbgInform(), ParticleAttrib< T >::size(), and spap().
spap()
template<class T > void spap (ParticleAttrib< T > & pattr, int ibase, int ibound, int istride, bool docomm = true)
Definition at line 117 of file ParticleDebug.hpp.
References Communicate::barrier(), Communicate::broadcast_others(), IpplInfo::Comm, digitsPastDecimal, elementsPerLine, endl(), Index::first(), FldDbgInform, FldDbgInformIsSet, Message::get(), Message::getmsg(), IpplInfo::getNodes(), Inform::getPrintNode(), INFORM_ALL_NODES, Index::intersect(), IPPL_APP_CYCLE, IPPL_APP_TAG0, Index::last(), IpplInfo::myNode(), TagMaker::next_tag(), PtclDbgInform, PtclDbgInformIsSet, Message::put(), Message::putmsg(), Communicate::receive_block(), Communicate::send(), setPtclDbgInform(), ParticleAttrib< T >::size(), Index::touches(), WARNMSG, and widthOfElements.
Referenced by epap(), and pap().
Variable Documentation
digitsPastDecimal
int digitsPastDecimal
Definition at line 53 of file FieldDebugFunctions.cpp.
Referenced by setFormat().
elementsPerLine
int elementsPerLine
Definition at line 52 of file FieldDebugFunctions.cpp.
Referenced by setFormat().
FldDbgInform
Inform* FldDbgInform
Definition at line 31 of file FieldDebugFunctions.cpp.
Referenced by setInform().
FldDbgInformIsSet
bool FldDbgInformIsSet
Definition at line 38 of file FieldDebugFunctions.cpp.
Referenced by setInform().
PtclDbgInform
Inform* PtclDbgInform
Definition at line 41 of file ParticleDebugFunctions.cpp.
Referenced by epap(), pap(), setPtclDbgInform(), and spap().
PtclDbgInformIsSet
bool PtclDbgInformIsSet
Definition at line 42 of file ParticleDebugFunctions.cpp.
Referenced by epap(), pap(), setPtclDbgInform(), and spap().
widthOfElements
int widthOfElements
Definition at line 54 of file FieldDebugFunctions.cpp.
Referenced by setFormat().