OPAL (Object Oriented Parallel Accelerator Library): src/Classic/FixedAlgebra/FLieGenerator.hpp File Reference
FLieGenerator.hpp File Reference
#include "FixedAlgebra/FLieGenerator.h"
#include "Algebra/Array1D.h"
#include "FixedAlgebra/FArray1D.h"
#include "FixedAlgebra/FMatrix.h"
#include "FixedAlgebra/FMonomial.h"
#include "FixedAlgebra/FTps.h"
#include <complex>
#include <iosfwd>
#include <functional>
Functions
template<class T , int N>
FLieGenerator< T, N > operator+ (const FLieGenerator< T, N > &x, const FLieGenerator< T, N > &y)
Add.
template<class T , int N>
FLieGenerator< T, N > operator- (const FLieGenerator< T, N > &x, const FLieGenerator< T, N > &y)
Subtract.
template<class T , int N>
FLieGenerator< T, N > operator* (const FLieGenerator< T, N > &x, const T &y)
Multiply by scalar.
template<class T , int N>
FLieGenerator< T, N > operator* (const T &x, const FLieGenerator< T, N > &y)
Multiply by scalar.
template<class T , int N>
FLieGenerator< T, N > operator* (const FLieGenerator< T, N > &x, const FLieGenerator< T, N > &y)
Multiply by Lie generator.
template<class T , int N>
FLieGenerator< T, N > operator/ (const FLieGenerator< T, N > &x, const T &y)
Divide by scalar.
template<class T , int N>
FLieGenerator< T, N > real (const FLieGenerator< std::complex< T >, N > &x)
Take real part of a complex generator.
template<class T , int N>
FLieGenerator< T, N > imag (const FLieGenerator< std::complex< T >, N > &x)
Take imaginary part of a complex generator.
template<class T , int N>
FLieGenerator< std::complex< T >, N > toComplex (const FLieGenerator< T, N > &x)
Convert real generator to complex.
template<class T , int N>
FLieGenerator< T, N > PoissonBracket (const FLieGenerator< T, N > &f, const FLieGenerator< T, N > &g)
Poisson bracket of two Lie generators.
template<class T , int N>
std::ostream & operator<< (std::ostream &os, const FLieGenerator< T, N > &gen)
Output.
Function Documentation
imag()
template<class T , int N> FLieGenerator<T, N> imag (const FLieGenerator< std::complex< T >, N > & x)
Take imaginary part of a complex generator.
Definition at line 437 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::end(), and Attrib::Legacy::Distribution::T.
Referenced by BMultipoleField::Bfield(), BSingleMultipoleField< order >::Bfield(), FDoubleEigen< N >::eigenVectors(), FDoubleEigen< N >::hqr2(), MapAnalyser::invertMatrix_m(), MapAnalyser::normalizeEigen_m(), sqrt(), and Werrf().
operator*() [1/3]
template<class T , int N> FLieGenerator<T, N> operator* (const FLieGenerator< T, N > & x, const T & y)
Multiply by scalar.
Definition at line 368 of file FLieGenerator.hpp.
operator*() [2/3]
template<class T , int N> FLieGenerator<T, N> operator* (const T & x, const FLieGenerator< T, N > & y)
Multiply by scalar.
Definition at line 376 of file FLieGenerator.hpp.
operator*() [3/3]
template<class T , int N> FLieGenerator<T, N> operator* (const FLieGenerator< T, N > & x, const FLieGenerator< T, N > & y)
Multiply by Lie generator.
Definition at line 384 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::getBottomIndex(), FLieGenerator< T, N >::getOrder(), FTpsData< N >::getProductArray(), FLieGenerator< T, N >::getTopIndex(), FLieGenerator< T, N >::isZero(), and Attrib::Legacy::Distribution::T.
operator+()
template<class T , int N> FLieGenerator<T, N> operator+ (const FLieGenerator< T, N > & x, const FLieGenerator< T, N > & y)
Add.
Definition at line 352 of file FLieGenerator.hpp.
operator-()
template<class T , int N> FLieGenerator<T, N> operator- (const FLieGenerator< T, N > & x, const FLieGenerator< T, N > & y)
Subtract.
Definition at line 360 of file FLieGenerator.hpp.
operator/()
template<class T , int N> FLieGenerator<T, N> operator/ (const FLieGenerator< T, N > & x, const T & y)
Divide by scalar.
Definition at line 414 of file FLieGenerator.hpp.
operator<<()
template<class T , int N> std::ostream& operator<< (std::ostream & os, const FLieGenerator< T, N > & gen)
Output.
Definition at line 515 of file FLieGenerator.hpp.
References endl(), FTpsData< N >::getExponents(), FLieGenerator< T, N >::getOrder(), Inform::precision(), Inform::setf(), and Attrib::Legacy::Distribution::T.
PoissonBracket()
template<class T , int N> FLieGenerator<T, N> PoissonBracket (const FLieGenerator< T, N > & f, const FLieGenerator< T, N > & g)
Poisson bracket of two Lie generators.
Definition at line 466 of file FLieGenerator.hpp.
real()
template<class T , int N> FLieGenerator<T, N> real (const FLieGenerator< std::complex< T >, N > & x)
Take real part of a complex generator.
Definition at line 422 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::end(), and Attrib::Legacy::Distribution::T.
Referenced by FixedFFTLowPassFilter::apply(), RelativeFFTLowPassFilter::apply(), BMultipoleField::Bfield(), BSingleMultipoleField< order >::Bfield(), RelativeFFTLowPassFilter::calc_derivative(), FixedFFTLowPassFilter::calc_derivative(), SpecializedGreensFunction< 3 >::calculate(), P3MPoissonSolver::calculateGridForces(), GreenWakeFunction::CalcWakeFFT(), DumpFields::checkInt(), DumpEMFields::checkInt(), GreenWakeFunction::compEnergy(), interpolation::complex(), Astra1D_fast::computeFourierCoefficients(), convlv(), erf(), Attributes::getStringArray(), matheval::detail::grammar< real_t, Iterator >::grammar(), FDoubleEigen< N >::hqr2(), MapAnalyser::invertMatrix_m(), GreenWakeFunction::Wake::operator()(), MapAnalyser::printPhaseShift_m(), Astra1DElectroStatic::readMap(), Astra1DMagnetoStatic::readMap(), Astra1DDynamic::readMap(), GreenWakeFunction::setWakeFromFile(), sqrt(), and Werrf().
toComplex()
template<class T , int N> FLieGenerator<std::complex<T>, N> toComplex (const FLieGenerator< T, N > & x)
Convert real generator to complex.
Definition at line 452 of file FLieGenerator.hpp.
References FLieGenerator< T, N >::begin(), FLieGenerator< T, N >::end(), FLieGenerator< T, N >::getOrder(), and Attrib::Legacy::Distribution::T.