OPAL (Object Oriented Parallel Accelerator Library): MacroStream Class Reference
MacroStream Class Reference
An input buffer for macro commands.
#include <MacroStream.h>
Public Member Functions
MacroStream (const std::string &)
Constructor.
virtual ~MacroStream ()
void append (Token &)
Append a token to the stream.
virtual Token readToken ()
Read a token from the stream.
void start ()
Reset stream to start.
Public Member Functions inherited from TokenStream
TokenStream (const std::string &name)
Constructor.
virtual ~TokenStream ()
void putBack (const Token &token)
Put token back to stream.
const std::string & getName () const
Return stream name.
int getLine () const
Return line number.
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Types
typedef std::list< Token > TokenList
Private Member Functions
MacroStream ()
MacroStream (const MacroStream &)
void operator= (const MacroStream &)
Private Attributes
TokenList body
TokenList::iterator curr
Additional Inherited Members
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from TokenStream
std::string stream_name
int curr_line
bool put_back_flag
Token put_back
Detailed Description
An input buffer for macro commands.
Definition at line 31 of file MacroStream.h.
Member Typedef Documentation
TokenList
typedef std::list<Token> MacroStream::TokenList private
Definition at line 58 of file MacroStream.h.
Constructor & Destructor Documentation
MacroStream() [1/3]
MacroStream::MacroStream (const std::string & macName)
Constructor.
Definition at line 27 of file MacroStream.cpp.
~MacroStream()
MacroStream::~MacroStream () virtual
Definition at line 32 of file MacroStream.cpp.
MacroStream() [2/3]
MacroStream::MacroStream () private
MacroStream() [3/3]
MacroStream::MacroStream (const MacroStream &) private
Member Function Documentation
append()
void MacroStream::append (Token & token)
Append a token to the stream.
Definition at line 36 of file MacroStream.cpp.
References body.
Referenced by CompoundStatement::CompoundStatement(), MacroCmd::makeInstance(), SequenceTemplate::makeInstance(), MacroCmd::makeTemplate(), LineTemplate::parseTemplate(), and SequenceTemplate::parseTemplate().
operator=()
void MacroStream::operator= (const MacroStream &) private
readToken()
Token MacroStream::readToken () virtual
Read a token from the stream.
Implements TokenStream.
Definition at line 41 of file MacroStream.cpp.
References body, curr, Token::IS_EOF, TokenStream::put_back, TokenStream::put_back_flag, and TokenStream::stream_name.
Referenced by LineTemplate::makeInstance().
start()
void MacroStream::start ()
Reset stream to start.
Definition at line 53 of file MacroStream.cpp.
References body, curr, and TokenStream::put_back_flag.
Referenced by MacroCmd::execute(), CompoundStatement::execute(), LineTemplate::makeInstance(), and SequenceTemplate::makeInstance().
Member Data Documentation
body
TokenList MacroStream::body private
Definition at line 59 of file MacroStream.h.
Referenced by append(), readToken(), and start().
curr
TokenList::iterator MacroStream::curr private
Definition at line 60 of file MacroStream.h.
Referenced by readToken(), and start().
The documentation for this class was generated from the following files:
src/OpalParser/MacroStream.h
src/OpalParser/MacroStream.cpp