OPAL (Object Oriented Parallel Accelerator Library): TravelingWaveRep Class Reference
TravelingWaveRep Class Reference
#include <TravelingWaveRep.h>
Public Member Functions
TravelingWaveRep (const std::string &name)
Constructor with given name.
TravelingWaveRep ()
TravelingWaveRep (const TravelingWaveRep &)
virtual ~TravelingWaveRep ()
virtual ElementBase * clone () const
Return clone.
virtual Channel * getChannel (const std::string &aKey, bool=false)
Construct a read/write channel.
virtual AcceleratingField & getField ()
Get field.
virtual const AcceleratingField & getField () const
Get field.
virtual StraightGeometry & getGeometry ()
Get geometry.
virtual const StraightGeometry & getGeometry () const
Get geometry.
virtual double getAmplitude () const
Get amplitude.
virtual double getFrequency () const
Get frequency.
virtual double getPhase () const
Get phase.
virtual void setAmplitude (double V)
Set amplitude.
virtual void setFrequency (double f)
Set frequency.
virtual void setPhase (double phi)
Set phase.
Public Member Functions inherited from TravelingWave
TravelingWave (const std::string &name)
Constructor with given name.
TravelingWave ()
TravelingWave (const TravelingWave &)
virtual ~TravelingWave ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to TravelingWave.
virtual void setPhasem (double phase) override
void setNumCells (int NumCells)
void setMode (double mode)
virtual double getAutoPhaseEstimate (const double &E0, const double &t0, const double &q, const double &m) override
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void finalise () override
virtual bool bends () const override
virtual void goOnline (const double &kineticEnergy) override
virtual void goOffline () override
virtual ElementBase::ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
virtual bool isInside (const Vector_t &r) const override
virtual void getElementDimensions (double &begin, double &end) const override
virtual CoordinateSystemTrafo getEdgeToBegin () const override
virtual CoordinateSystemTrafo getEdgeToEnd () const override
Public Member Functions inherited from RFCavity
RFCavity (const std::string &name)
Constructor with given name.
RFCavity ()
RFCavity (const RFCavity &)
virtual ~RFCavity ()
void dropFieldmaps ()
virtual void setFieldMapFN (std::string fmapfn)
Set the name of the field map.
virtual std::string getFieldMapFN () const
virtual void setAmplitudem (double vPeak)
virtual double getAmplitudem () const
virtual void setAmplitudeError (double vPeakError)
virtual double getAmplitudeError () const
virtual void setFrequencym (double freq)
void setFrequency (double freq)
virtual double getFrequencym () const
virtual double getPhasem () const
double getPhasem (double t) const
virtual void setPhaseError (double phaseError)
virtual double getPhaseError () const
void setCavityType (std::string type)
std::string getCavityType () const
virtual void setFast (bool fast)
virtual bool getFast () const
virtual void setAutophaseVeto (bool veto=true)
virtual bool getAutophaseVeto () const
virtual double getAutoPhaseEstimateFallback (double E0, double t0, double q, double m)
virtual std::pair< double, double > trackOnAxisParticle (const double &p0, const double &t0, const double &dt, const double &q, const double &mass, std::ofstream *out=NULL)
virtual void initialise (PartBunchBase< double, 3 > *bunch, std::shared_ptr< AbstractTimeDependence > freq_atd, std::shared_ptr< AbstractTimeDependence > ampl_atd, std::shared_ptr< AbstractTimeDependence > phase_atd)
virtual void setDesignEnergy (const double &ekin, bool changeable=true) override
virtual double getDesignEnergy () const override
void setRmin (double rmin)
void setRmax (double rmax)
void setAzimuth (double angle)
void setPerpenDistance (double pdis)
void setGapWidth (double gapwidth)
void setPhi0 (double phi0)
virtual double getRmin () const
virtual double getRmax () const
virtual double getAzimuth () const
virtual double getCosAzimuth () const
virtual double getSinAzimuth () const
virtual double getPerpenDistance () const
virtual double getGapWidth () const
virtual double getPhi0 () const
virtual void setComponentType (std::string name) override
virtual std::string getComponentType () const override
virtual double getCycFrequency () const
void getMomentaKick (const double normalRadius, double momentum[], const double t, const double dtCorrt, const int PID, const double restMass, const int chargenumber)
used in OPAL-cycl
double spline (double z, double *za)
void setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setAmplitudeModelName (std::string name)
std::string getAmplitudeModelName ()
void setPhaseModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setPhaseModelName (std::string name)
std::string getPhaseModelName ()
void setFrequencyModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setFrequencyModelName (std::string name)
std::string getFrequencyModelName ()
virtual double getElementLength () const override
Get design length.
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual void setElementLength (double length)
Set design length.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static void setIgnore (bool ignore=false)
Set ignore switch.
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Private Member Functions
void operator= (const TravelingWaveRep &)
Private Attributes
StraightGeometry geometry
The cavity's geometry.
AcceleratingField field
The cavity's field.
Static Private Attributes
static bool ignoreCavities = false
Cavities are ignored (amplitude = 0) when this switch is set.
Additional Inherited Members
Public Types inherited from TravelingWave
enum CavityType { SW, TW }
Public Types inherited from RFCavity
enum CavityType { SW, SGSW }
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from RFCavity
std::shared_ptr< AbstractTimeDependence > phase_td_m
std::string phase_name_m
std::shared_ptr< AbstractTimeDependence > amplitude_td_m
std::string amplitude_name_m
std::shared_ptr< AbstractTimeDependence > frequency_td_m
std::string frequency_name_m
std::string filename_m
double scale_m
double scaleError_m
double phase_m
double phaseError_m
double frequency_m
bool fast_m
bool autophaseVeto_m
double designEnergy_m
Fieldmap * fieldmap_m
double startField_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 26 of file TravelingWaveRep.h.
Constructor & Destructor Documentation
TravelingWaveRep() [1/3]
TravelingWaveRep::TravelingWaveRep (const std::string & name) explicit
Constructor with given name.
Definition at line 66 of file TravelingWaveRep.cpp.
TravelingWaveRep() [2/3]
TravelingWaveRep::TravelingWaveRep ()
Definition at line 56 of file TravelingWaveRep.cpp.
Referenced by clone().
TravelingWaveRep() [3/3]
TravelingWaveRep::TravelingWaveRep (const TravelingWaveRep & right)
Definition at line 61 of file TravelingWaveRep.cpp.
~TravelingWaveRep()
TravelingWaveRep::~TravelingWaveRep () virtual
Definition at line 71 of file TravelingWaveRep.cpp.
Member Function Documentation
clone()
ElementBase * TravelingWaveRep::clone () const virtual
Return clone.
Implements ElementBase.
Definition at line 75 of file TravelingWaveRep.cpp.
References TravelingWaveRep().
getAmplitude()
double TravelingWaveRep::getAmplitude () const virtual
Get amplitude.
Implements TravelingWave.
Definition at line 110 of file TravelingWaveRep.cpp.
References field, ConstEzField::getEz(), and ignoreCavities.
getChannel()
Channel * TravelingWaveRep::getChannel (const std::string & aKey, bool create = false) virtual
Construct a read/write channel.
Reimplemented from ElementBase.
Definition at line 80 of file TravelingWaveRep.cpp.
References ElementBase::getChannel().
getField() [1/2]
AcceleratingField & TravelingWaveRep::getField () virtual
Get field.
Implements Component.
Definition at line 92 of file TravelingWaveRep.cpp.
References field.
getField() [2/2]
const AcceleratingField & TravelingWaveRep::getField () const virtual
Get field.
Implements Component.
Definition at line 96 of file TravelingWaveRep.cpp.
References field.
getFrequency()
double TravelingWaveRep::getFrequency () const virtual
Get frequency.
Implements TravelingWave.
Definition at line 115 of file TravelingWaveRep.cpp.
References field, and OscillatingField< Field >::getFrequency().
getGeometry() [1/2]
StraightGeometry & TravelingWaveRep::getGeometry () virtual
Get geometry.
Implements ElementBase.
Definition at line 101 of file TravelingWaveRep.cpp.
References geometry.
getGeometry() [2/2]
const StraightGeometry & TravelingWaveRep::getGeometry () const virtual
Get geometry.
Implements ElementBase.
Definition at line 105 of file TravelingWaveRep.cpp.
References geometry.
getPhase()
double TravelingWaveRep::getPhase () const virtual
Get phase.
Implements TravelingWave.
Definition at line 120 of file TravelingWaveRep.cpp.
References field, and OscillatingField< Field >::getPhase().
operator=()
void TravelingWaveRep::operator= (const TravelingWaveRep &) private
setAmplitude()
void TravelingWaveRep::setAmplitude (double V) virtual
Set amplitude.
Definition at line 125 of file TravelingWaveRep.cpp.
References field, and ConstEzField::setEz().
Referenced by OpalTravelingWave::update().
setFrequency()
void TravelingWaveRep::setFrequency (double f) virtual
Set frequency.
Definition at line 130 of file TravelingWaveRep.cpp.
References field, and OscillatingField< Field >::setFrequency().
Referenced by OpalTravelingWave::update().
setIgnore()
void TravelingWaveRep::setIgnore (bool ignore = false) static
Set ignore switch.
Definition at line 139 of file TravelingWaveRep.cpp.
References ignoreCavities.
setPhase()
void TravelingWaveRep::setPhase (double phi) virtual
Set phase.
Definition at line 135 of file TravelingWaveRep.cpp.
References field, and OscillatingField< Field >::setPhase().
Referenced by OpalTravelingWave::update().
Member Data Documentation
field
AcceleratingField TravelingWaveRep::field private
The cavity's field.
Definition at line 102 of file TravelingWaveRep.h.
Referenced by getAmplitude(), getField(), getFrequency(), getPhase(), setAmplitude(), setFrequency(), and setPhase().
geometry
StraightGeometry TravelingWaveRep::geometry private
The cavity's geometry.
Definition at line 99 of file TravelingWaveRep.h.
Referenced by getGeometry().
ignoreCavities
bool TravelingWaveRep::ignoreCavities = false static private
Cavities are ignored (amplitude = 0) when this switch is set.
Definition at line 105 of file TravelingWaveRep.h.
Referenced by getAmplitude(), and setIgnore().
The documentation for this class was generated from the following files:
src/Classic/BeamlineCore/TravelingWaveRep.h
src/Classic/BeamlineCore/TravelingWaveRep.cpp