OPAL (Object Oriented Parallel Accelerator Library): OpalParser Class Reference
OpalParser Class Reference
The default parser for OPAL-9.
#include <OpalParser.h>
Public Member Functions
OpalParser ()
virtual ~OpalParser ()
virtual void parse (Statement &) const
Parse and execute current statement.
virtual Statement * readStatement (TokenStream *) const
Read complete statement from a token stream.
virtual void run () const
Read current stream.
virtual void run (TokenStream *) const
Read given stream.
void stop () const
Set stop flag.
Public Member Functions inherited from Parser
Parser ()
virtual ~Parser ()
Static Public Member Functions
static Token readToken ()
Return next input token.
Protected Member Functions
void execute (Object *, const std::string &) const
Execute or check the current command.
virtual Object * find (const std::string &) const
Find object by name in the main directory.
virtual void parseAction (Statement &) const
Parse executable command.
virtual void parseAssign (Statement &) const
Parse assignment statement.
virtual void parseDefine (Statement &) const
Parse definition.
virtual void parseEnd (Statement &) const
Check for end of statement.
virtual void parseMacro (const std::string &name, Statement &) const
Parse macro definition or call.
virtual void printHelp (const std::string &) const
Print help on named command.
Private Member Functions
OpalParser (const OpalParser &)
void operator= (const OpalParser &)
Static Private Member Functions
static void parseBracketList (char close, Statement &)
static void parseTokenList (Statement &)
static std::string getHint (const std::string &, const std::string &="attribute")
Private Attributes
bool stopFlag
Static Private Attributes
static std::vector< Pointer< TokenStream > > inputStack
Detailed Description
The default parser for OPAL-9.
Definition at line 44 of file OpalParser.h.
Constructor & Destructor Documentation
OpalParser() [1/2]
OpalParser::OpalParser ()
Definition at line 58 of file OpalParser.cpp.
~OpalParser()
OpalParser::~OpalParser () virtual
Definition at line 62 of file OpalParser.cpp.
OpalParser() [2/2]
OpalParser::OpalParser (const OpalParser &) private
Member Function Documentation
execute()
void OpalParser::execute (Object * object, const std::string & name) const protected
Execute or check the current command.
Definition at line 126 of file OpalParser.cpp.
References endl(), OpalData::getInstance(), gmsg, Options::mtrace, name, Object::shouldTrace(), Object::shouldUpdate(), and OpalData::update().
Referenced by parseAction(), parseDefine(), and parseMacro().
find()
Object * OpalParser::find (const std::string & name) const protected virtual
Find object by name in the main directory.
Reimplemented in TrackParser.
Definition at line 151 of file OpalParser.cpp.
References OpalData::find(), OpalData::getInstance(), and name.
Referenced by parse(), parseAction(), parseAssign(), parseDefine(), parseMacro(), SequenceParser::parseMember(), and printHelp().
getHint()
std::string OpalParser::getHint (const std::string & name, const std::string & type = "attribute") static private
Definition at line 642 of file OpalParser.cpp.
References any(), AttributeHandler::COMMAND, AttributeHandler::ELEMENT, AttributeHandler::getOwner(), name, AttributeHandler::STATEMENT, and AttributeHandler::SUB_COMMAND.
Referenced by parse(), and parseAction().
operator=()
void OpalParser::operator= (const OpalParser &) private
parse()
void OpalParser::parse (Statement & stat) const virtual
Parse and execute current statement.
Implements Parser.
Reimplemented in SequenceParser.
Definition at line 66 of file OpalParser.cpp.
References Statement::atEnd(), Statement::delimiter(), find(), Statement::getCurrent(), getHint(), OpalData::getInstance(), Token::getLex(), Statement::keyword(), Statement::mark(), name, parseAction(), parseAssign(), parseDefine(), parseMacro(), Expressions::parseString(), Statement::position(), Statement::print(), printHelp(), Statement::restore(), and Statement::start().
parseAction()
void OpalParser::parseAction (Statement & stat) const protected virtual
Parse executable command.
Definition at line 156 of file OpalParser.cpp.
References Object::clone(), Statement::delimiter(), execute(), find(), getHint(), Object::parse(), parseEnd(), Expressions::parseString(), printHelp(), Statement::start(), and stopFlag.
Referenced by parse().
parseAssign()
void OpalParser::parseAssign (Statement & stat) const protected virtual
Parse assignment statement.
Definition at line 192 of file OpalParser.cpp.
References Object::clone(), OpalData::define(), Statement::delimiter(), find(), OpalData::find(), Object::findAttribute(), OpalData::getInstance(), Object::isTreeMember(), Statement::keyword(), OpalData::makeDirty(), Expressions::parseDelimiter(), parseEnd(), Expressions::parseRealConst(), Expressions::parseString(), and Statement::start().
Referenced by parse().
parseBracketList()
void OpalParser::parseBracketList (char close, Statement & stat) static private
Definition at line 457 of file OpalParser.cpp.
References Statement::append(), Token::isDel(), Token::isEOF(), and readToken().
Referenced by parseTokenList(), and readStatement().
parseDefine()
void OpalParser::parseDefine (Statement & stat) const protected virtual
Parse definition.
Definition at line 326 of file OpalParser.cpp.
References Object::clone(), OpalData::define(), Statement::delimiter(), execute(), find(), OpalData::getInstance(), Statement::keyword(), Object::makeInstance(), Object::parse(), parseEnd(), Expressions::parseString(), Object::setShared(), and Statement::start().
Referenced by parse().
parseEnd()
void OpalParser::parseEnd (Statement & stat) const protected virtual
Check for end of statement.
Definition at line 373 of file OpalParser.cpp.
References Statement::atEnd(), Statement::delimiter(), Statement::position(), and Statement::print().
Referenced by SequenceParser::parse(), parseAction(), parseAssign(), parseDefine(), and SequenceParser::parseMember().
parseMacro()
void OpalParser::parseMacro (const std::string & name, Statement & stat) const protected virtual
Parse macro definition or call.
Definition at line 389 of file OpalParser.cpp.
References OpalData::define(), Statement::delimiter(), execute(), find(), Statement::getCurrent(), OpalData::getInstance(), inputStack, Object::makeInstance(), Object::makeTemplate(), Statement::mark(), Expressions::parseString(), and Statement::restore().
Referenced by parse().
parseTokenList()
void OpalParser::parseTokenList (Statement & stat) static private
Definition at line 478 of file OpalParser.cpp.
References Statement::append(), Token::isDel(), Token::isEOF(), parseBracketList(), and readToken().
Referenced by readStatement().
printHelp()
void OpalParser::printHelp (const std::string & cmdName) const protected virtual
Print help on named command.
Definition at line 445 of file OpalParser.cpp.
References endl(), find(), and gmsg.
Referenced by parse(), and parseAction().
readStatement()
Statement * OpalParser::readStatement (TokenStream * is) const virtual
Read complete statement from a token stream.
Implements Parser.
Definition at line 508 of file OpalParser.cpp.
References Statement::append(), endl(), IpplInfo::Error, ERRORMSG, Token::getFile(), Token::getLine(), gmsg, inputStack, Token::isDel(), Token::isEOF(), Token::isKey(), Token::isString(), Token::isWord(), parseBracketList(), parseTokenList(), Statement::printWhere(), TokenStream::readToken(), Statement::start(), and ClassicException::what().
Referenced by run().
readToken()
Token OpalParser::readToken () static
Return next input token.
Definition at line 499 of file OpalParser.cpp.
References inputStack, and Token::IS_EOF.
Referenced by parseBracketList(), and parseTokenList().
run() [1/2]
void OpalParser::run () const virtual
Read current stream.
Definition at line 602 of file OpalParser.cpp.
References endl(), inputStack, readStatement(), stopFlag, ClassicException::what(), and ClassicException::where().
Referenced by TrackCmd::execute(), Call::execute(), SequenceTemplate::makeInstance(), opalMain(), Sequence::parse(), run(), and run_opal().
run() [2/2]
void OpalParser::run (TokenStream * is) const virtual
Read given stream.
Implements Parser.
Definition at line 631 of file OpalParser.cpp.
References inputStack, and run().
stop()
void OpalParser::stop () const
Set stop flag.
Definition at line 638 of file OpalParser.cpp.
References stopFlag.
Referenced by TrackEnd::execute(), and SequenceParser::parse().
Member Data Documentation
inputStack
std::vector< Pointer< TokenStream > > OpalParser::inputStack static private
Definition at line 119 of file OpalParser.h.
Referenced by parseMacro(), readStatement(), readToken(), and run().
stopFlag
bool OpalParser::stopFlag mutable private
Definition at line 116 of file OpalParser.h.
Referenced by parseAction(), run(), and stop().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/OpalParser/OpalParser.h
/psi/home/gsell/data/src/OPAL/src/src/OpalParser/OpalParser.cpp