OPAL (Object Oriented Parallel Accelerator Library): IntSUDSImpl< Dim > Class Template Reference
IntSUDSImpl< Dim > Class Template Reference
#include <IntSUDS.h>
Public Member Functions
IntSUDSImpl ()
~IntSUDSImpl ()
Public Member Functions inherited from Interpolator
Interpolator ()
~Interpolator ()
Static Public Member Functions
template<class FT , class M , class C , class PT >
static void scatter (const FT &, Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void scatter (const FT &, Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh, NDIndex< Dim > &ngp, Vektor< PT, Dim > &dpos)
template<class FT , class M , class C , class PT >
static void scatter (const FT &, Field< FT, Dim, M, C > &f, const NDIndex< Dim > &ngp, const Vektor< PT, Dim > &)
template<class FT , class M , class C , class PT >
static void gather (FT &, const Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void gather (FT &, const Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh, NDIndex< Dim > &ngp, Vektor< PT, Dim > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &, const Field< FT, Dim, M, C > &f, const NDIndex< Dim > &ngp, const Vektor< PT, Dim > &)
Additional Inherited Members
Static Protected Member Functions inherited from Interpolator
template<class T , unsigned Dim>
static CompressedBrickIterator< T, Dim > getFieldIter (const BareField< T, Dim > &f, const NDIndex< Dim > &pt)
Detailed Description
template<unsigned Dim>
class IntSUDSImpl< Dim >
Definition at line 34 of file IntSUDS.h.
Constructor & Destructor Documentation
IntSUDSImpl()
template<unsigned Dim> IntSUDSImpl< Dim >::IntSUDSImpl () inline
Definition at line 38 of file IntSUDS.h.
~IntSUDSImpl()
template<unsigned Dim> IntSUDSImpl< Dim >::~IntSUDSImpl () inline
Definition at line 39 of file IntSUDS.h.
Member Function Documentation
gather() [1/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntSUDSImpl< Dim >::gather (FT & , const Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh) inline static
Definition at line 110 of file IntSUDS.h.
References endl(), ERRORMSG, FindDelta(), FindNGP(), FindPos(), and Interpolator::getFieldIter().
Referenced by IntSUDS::gather().
gather() [2/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntSUDSImpl< Dim >::gather (FT & , const Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh, NDIndex< Dim > & ngp, Vektor< PT, Dim > & dpos) inline static
Definition at line 136 of file IntSUDS.h.
References endl(), ERRORMSG, FindDelta(), FindNGP(), FindPos(), and Interpolator::getFieldIter().
gather() [3/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntSUDSImpl< Dim >::gather (FT & , const Field< FT, Dim, M, C > & f, const NDIndex< Dim > & ngp, const Vektor< PT, Dim > &) inline static
Definition at line 162 of file IntSUDS.h.
References endl(), ERRORMSG, and Interpolator::getFieldIter().
scatter() [1/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntSUDSImpl< Dim >::scatter (const FT & , Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh) inline static
Definition at line 46 of file IntSUDS.h.
References endl(), ERRORMSG, FindDelta(), FindNGP(), FindPos(), and Interpolator::getFieldIter().
Referenced by IntSUDS::scatter().
scatter() [2/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntSUDSImpl< Dim >::scatter (const FT & , Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh, NDIndex< Dim > & ngp, Vektor< PT, Dim > & dpos) inline static
Definition at line 72 of file IntSUDS.h.
References endl(), ERRORMSG, FindDelta(), FindNGP(), FindPos(), and Interpolator::getFieldIter().
scatter() [3/3]
template<unsigned Dim> template<class FT , class M , class C , class PT > static void IntSUDSImpl< Dim >::scatter (const FT & , Field< FT, Dim, M, C > & f, const NDIndex< Dim > & ngp, const Vektor< PT, Dim > &) inline static
Definition at line 98 of file IntSUDS.h.
References endl(), ERRORMSG, and Interpolator::getFieldIter().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/IntSUDS.h