OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Index/SIndexAssign.hpp File Reference
SIndexAssign.hpp File Reference
#include "Index/SIndexAssign.h"
#include "Index/SIndex.h"
#include "Field/BrickIterator.h"
#include "Utility/IpplInfo.h"
Classes
class SIndexAssignTraits< Dim, OP >
class SIndexAssignTraits< Dim, OpAssign >
class SIndexAssignTraits< Dim, OpBitwiseAndAssign >
class SIndexAssignTraits< Dim, OpBitwiseOrAssign >
class SIndexExpLoop< OP, Dim >
class SIndexExpLoop< OP, 1U >
class SIndexExpLoop< OP, 2U >
class SIndexExpLoop< OP, 3U >
struct AssignActions< Dim, T >
struct AssignActions< Dim, SIExprTag< true > >
struct AssignActions< Dim, SIExprTag< false > >
Functions
template<unsigned Dim, class RHS , class Op , bool IsExpr>
void assign (SIndex< Dim > &a, RHS b, Op, const NDIndex< Dim > &domain, SIExprTag< IsExpr >)
Function Documentation
assign()
template<unsigned Dim, class RHS , class Op , bool IsExpr> void assign (SIndex< Dim > & a, RHS b, Op , const NDIndex< Dim > & domain, SIExprTag< IsExpr >)
Definition at line 334 of file SIndexAssign.hpp.
References a, IpplInfo::abort(), Dim, NDIndex< Dim >::empty(), endl(), ERRORMSG, SIndexExpLoop< OP, Dim >::evaluate(), for_each(), and NDIndex< Dim >::intersect().