OPAL (Object Oriented Parallel Accelerator Library): AssignActions< Dim, SIExprTag< true > > Struct Template Reference
AssignActions< Dim, SIExprTag< true > > Struct Template Reference
#include <SIndexAssign.hpp>
Static Public Member Functions
template<class RHS >
static void fillgc (RHS &bb, const NDIndex< Dim > &)
template<class RHS >
static bool plugbase (RHS &bb, const NDIndex< Dim > &domain)
template<class RHS >
static void nextLField (RHS &)
Detailed Description
template<unsigned Dim>
struct AssignActions< Dim, SIExprTag< true > >
Definition at line 281 of file SIndexAssign.hpp.
Member Function Documentation
fillgc()
template<unsigned Dim> template<class RHS > static void AssignActions< Dim, SIExprTag< true > >::fillgc (RHS & bb, const NDIndex< Dim > &) inline static
Definition at line 283 of file SIndexAssign.hpp.
References FillGCIfNecessary(), and for_each().
nextLField()
template<unsigned Dim> template<class RHS > static void AssignActions< Dim, SIExprTag< true > >::nextLField (RHS &) inline static
Definition at line 297 of file SIndexAssign.hpp.
plugbase()
template<unsigned Dim> template<class RHS > static bool AssignActions< Dim, SIExprTag< true > >::plugbase (RHS & bb, const NDIndex< Dim > & domain) inline static
Definition at line 290 of file SIndexAssign.hpp.
References for_each().
The documentation for this struct was generated from the following file:
ippl/src/Index/SIndexAssign.hpp