OPAL (Object Oriented Parallel Accelerator Library): TUNE_class Class Reference
TUNE_class Class Reference
#include <Ctunes.h>
Public Member Functions
TUNE_class ()
virtual ~TUNE_class (void)
int lombAnalysis (double *x, double *y, int Ndat, int nhis)
int lombAnalysis (std::vector< double > &x, std::vector< double > &y, int nhis, double Norm)
Private Attributes
double ofac
double hifac
double Qmin
double Qmax
Detailed Description
Definition at line 10 of file Ctunes.h.
Constructor & Destructor Documentation
TUNE_class()
TUNE_class::TUNE_class ()
Definition at line 22 of file Ctunes.cpp.
~TUNE_class()
TUNE_class::~TUNE_class (void) virtual
Definition at line 35 of file Ctunes.cpp.
Member Function Documentation
lombAnalysis() [1/2]
int TUNE_class::lombAnalysis (double * x, double * y, int Ndat, int nhis)
Definition at line 146 of file Ctunes.cpp.
References endl(), gmsg, hifac, ofac, LOMB_class::period(), Qmax, Qmin, LOMB_class::signi(), LOMB_TYPE::x, and LOMB_TYPE::y.
Referenced by ParallelCyclotronTracker::getTunes().
lombAnalysis() [2/2]
int TUNE_class::lombAnalysis (std::vector< double > & x, std::vector< double > & y, int nhis, double Norm)
Definition at line 47 of file Ctunes.cpp.
References endl(), gmsg, hifac, ofac, LOMB_class::period(), Qmax, Qmin, LOMB_class::signi(), LOMB_TYPE::x, and LOMB_TYPE::y.
Member Data Documentation
hifac
double TUNE_class::hifac private
Definition at line 16 of file Ctunes.h.
Referenced by lombAnalysis().
ofac
double TUNE_class::ofac private
Definition at line 16 of file Ctunes.h.
Referenced by lombAnalysis().
Qmax
double TUNE_class::Qmax private
Definition at line 17 of file Ctunes.h.
Referenced by lombAnalysis().
Qmin
double TUNE_class::Qmin private
Definition at line 17 of file Ctunes.h.
Referenced by lombAnalysis().
The documentation for this class was generated from the following files:
src/Algorithms/Ctunes.h
src/Algorithms/Ctunes.cpp