OPAL (Object Oriented Parallel Accelerator Library): H5PartWrapperForPT Class Reference
H5PartWrapperForPT Class Reference
#include <H5PartWrapperForPT.h>
Public Member Functions
H5PartWrapperForPT (const std::string &fileName, h5_int32_t flags=H5_O_WRONLY)
H5PartWrapperForPT (const std::string &fileName, int restartStep, std::string sourceFile, h5_int32_t flags=H5_O_RDWR)
virtual ~H5PartWrapperForPT ()
virtual void readHeader ()
virtual void readStep (PartBunchBase< double, 3 > *, h5_ssize_t firstParticle, h5_ssize_t lastParticle)
virtual void writeHeader ()
virtual void writeStep (PartBunchBase< double, 3 > *, const std::map< std::string, double > &additionalStepAttributes)
virtual bool predecessorIsSameFlavour () const
Public Member Functions inherited from H5PartWrapper
virtual ~H5PartWrapper ()
void close ()
double getLastPosition ()
void storeCavityInformation ()
size_t getNumParticles () const
Private Member Functions
void readStepHeader (PartBunchBase< double, 3 > *)
void readStepData (PartBunchBase< double, 3 > *, h5_ssize_t, h5_ssize_t)
void writeStepHeader (PartBunchBase< double, 3 > *, const std::map< std::string, double > &)
void writeStepData (PartBunchBase< double, 3 > *)
Additional Inherited Members
Protected Member Functions inherited from H5PartWrapper
H5PartWrapper (const std::string &fileName, h5_int32_t flags=H5_O_WRONLY)
H5PartWrapper (const std::string &fileName, int restartStep, std::string sourceFile, h5_int32_t flags=H5_O_RDWR)
void open (h5_int32_t flags)
void copyFile (const std::string &sourceFile, int lastStep=-1, h5_int32_t flags=H5_O_WRONLY)
void copyFileSystem (const std::string &sourceFile)
void copyHeader (h5_file_t source)
void copyStep (h5_file_t source, int step)
void copyStepHeader (h5_file_t source)
void copyStepData (h5_file_t source)
void sendFailureMessage (bool failed, const std::string &where, const std::string &what)
void receiveFailureMessage (int sourceNode, const std::string &where, const std::string &what)
Static Protected Member Functions inherited from H5PartWrapper
static void reportOnError (h5_int64_t rc, const char *file, int line)
Protected Attributes inherited from H5PartWrapper
h5_file_t file_m
std::string fileName_m
std::string predecessorOPALFlavour_m
h5_int64_t numSteps_m
bool startedFromExistingFile_m
Static Protected Attributes inherited from H5PartWrapper
static std::string copyFilePrefix_m = ".copy"
Detailed Description
Definition at line 25 of file H5PartWrapperForPT.h.
Constructor & Destructor Documentation
H5PartWrapperForPT() [1/2]
H5PartWrapperForPT::H5PartWrapperForPT (const std::string & fileName, h5_int32_t flags = H5_O_WRONLY)
Definition at line 35 of file H5PartWrapperForPT.cpp.
H5PartWrapperForPT() [2/2]
H5PartWrapperForPT::H5PartWrapperForPT (const std::string & fileName, int restartStep, std::string sourceFile, h5_int32_t flags = H5_O_RDWR)
Definition at line 39 of file H5PartWrapperForPT.cpp.
References H5PartWrapper::file_m, OpalData::getInstance(), and OpalData::setRestartStep().
~H5PartWrapperForPT()
H5PartWrapperForPT::~H5PartWrapperForPT () virtual
Definition at line 48 of file H5PartWrapperForPT.cpp.
Member Function Documentation
predecessorIsSameFlavour()
bool H5PartWrapperForPT::predecessorIsSameFlavour () const inline virtual
Implements H5PartWrapper.
Definition at line 48 of file H5PartWrapperForPT.h.
References H5PartWrapper::predecessorOPALFlavour_m.
readHeader()
void H5PartWrapperForPT::readHeader () virtual
Implements H5PartWrapper.
Definition at line 51 of file H5PartWrapperForPT.cpp.
References PyOpal::PyOpalObjectNS::attributeName, H5PartWrapper::file_m, OpalData::getInstance(), name, READFILEATTRIB, REPORTONERROR, OpalData::setGlobalPhaseShift(), and OpalData::setRestartDumpFreq().
readStep()
void H5PartWrapperForPT::readStep (PartBunchBase< double, 3 > * bunch, h5_ssize_t firstParticle, h5_ssize_t lastParticle) virtual
Implements H5PartWrapper.
Definition at line 105 of file H5PartWrapperForPT.cpp.
References H5PartWrapper::file_m, readStepData(), readStepHeader(), and REPORTONERROR.
readStepData()
void H5PartWrapperForPT::readStepData (PartBunchBase< double, 3 > * bunch, h5_ssize_t firstParticle, h5_ssize_t lastParticle) private
Definition at line 148 of file H5PartWrapperForPT.cpp.
References PartBunchBase< T, Dim >::Bin, Util::c_data(), H5PartWrapper::file_m, H5PartWrapper::getNumParticles(), PartBunchBase< T, Dim >::ID, Hypervolume::n, PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::Q, PartBunchBase< T, Dim >::R, READDATA, and REPORTONERROR.
Referenced by readStep().
readStepHeader()
void H5PartWrapperForPT::readStepHeader (PartBunchBase< double, 3 > * bunch) private
Definition at line 114 of file H5PartWrapperForPT.cpp.
References Quaternion::conjugate(), cos(), H5PartWrapper::file_m, READSTEPATTRIB, PartBunchBase< T, Dim >::RefPartP_m, PartBunchBase< T, Dim >::RefPartR_m, Quaternion::rotate(), PartBunchBase< T, Dim >::set_sPos(), PartBunchBase< T, Dim >::setGlobalTrackStep(), PartBunchBase< T, Dim >::setLocalTrackStep(), PartBunchBase< T, Dim >::setT(), sin(), and PartBunchBase< T, Dim >::toLabTrafo_m.
Referenced by readStep().
writeHeader()
void H5PartWrapperForPT::writeHeader () virtual
Write file dump frequency.
Write global phase change
Implements H5PartWrapper.
Definition at line 208 of file H5PartWrapperForPT.cpp.
References Options::ebDump, H5PartWrapper::file_m, Util::getGitRevision(), OpalData::getGlobalPhaseShift(), OpalData::getInstance(), OPAL_PROJECT_NAME, OPAL_PROJECT_VERSION, Options::psDumpFreq, Options::rhoDump, WRITEFILEATTRIB, and WRITESTRINGFILEATTRIB.
writeStep()
void H5PartWrapperForPT::writeStep (PartBunchBase< double, 3 > * bunch, const std::map< std::string, double > & additionalStepAttributes) virtual
Implements H5PartWrapper.
Definition at line 291 of file H5PartWrapperForPT.cpp.
References PartBunchBase< T, Dim >::calcBeamParameters(), H5PartWrapper::close(), PartBunchBase< T, Dim >::getTotalNum(), H5PartWrapper::open(), writeStepData(), and writeStepHeader().
writeStepData()
void H5PartWrapperForPT::writeStepData (PartBunchBase< double, 3 > * bunch) private
Write space charge field map if asked for.
Need this to align particles and fields when writing space charge map.
Definition at line 402 of file H5PartWrapperForPT.cpp.
References PartBunchBase< T, Dim >::Bf, Util::c_data(), Options::ebDump, PartBunchBase< T, Dim >::Ef, H5PartWrapper::file_m, PartBunchBase< T, Dim >::get_hr(), PartBunchBase< T, Dim >::get_origin(), PartBunchBase< T, Dim >::getFieldLayout(), FieldLayout< Dim >::getLocalNDIndex(), PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getRho(), PartBunchBase< T, Dim >::ID, max(), min(), PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::POrigin, PartBunchBase< T, Dim >::PType, PartBunchBase< T, Dim >::Q, PartBunchBase< T, Dim >::R, REPORTONERROR, H5PartWrapper::reportOnError(), Options::rhoDump, and WRITEDATA.
Referenced by writeStep().
writeStepHeader()
void H5PartWrapperForPT::writeStepHeader (PartBunchBase< double, 3 > * bunch, const std::map< std::string, double > & additionalStepAttributes) private
Write particle mass and charge per particle. (Consider making these file attributes.)
Definition at line 301 of file H5PartWrapperForPT.cpp.
References Physics::c, endl(), Physics::epsilon_0, ERRORMSG, Units::eV2GeV, H5PartWrapper::file_m, PartBunchBase< T, Dim >::get_centroid(), PartBunchBase< T, Dim >::get_emit(), PartBunchBase< T, Dim >::get_gamma(), PartBunchBase< T, Dim >::get_maxExtent(), PartBunchBase< T, Dim >::get_meanKineticEnergy(), PartBunchBase< T, Dim >::get_norm_emit(), PartBunchBase< T, Dim >::get_origin(), PartBunchBase< T, Dim >::get_PBounds(), PartBunchBase< T, Dim >::get_pmean(), PartBunchBase< T, Dim >::get_prms(), PartBunchBase< T, Dim >::get_rrms(), PartBunchBase< T, Dim >::get_sPos(), PartBunchBase< T, Dim >::getCharge(), PartBunchBase< T, Dim >::getdE(), PartBunchBase< T, Dim >::getGlobalTrackStep(), PartBunchBase< T, Dim >::getLocalTrackStep(), PartBunchBase< T, Dim >::getM(), PartBunchBase< T, Dim >::getQ(), CoordinateSystemTrafo::getRotation(), PartBunchBase< T, Dim >::getT(), Util::getTaitBryantAngles(), H5PartWrapper::numSteps_m, Physics::pi, PartBunchBase< T, Dim >::RefPartP_m, PartBunchBase< T, Dim >::RefPartR_m, REPORTONERROR, PartBunchBase< T, Dim >::toLabTrafo_m, WRITESTEPATTRIB, and WRITESTRINGSTEPATTRIB.
Referenced by writeStep().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Structure/H5PartWrapperForPT.h
/psi/home/gsell/data/src/OPAL/src/src/Structure/H5PartWrapperForPT.cpp