OPAL (Object Oriented Parallel Accelerator Library): src/Classic/Filters/SavitzkyGolay.cpp File Reference
SavitzkyGolay.cpp File Reference
#include "Filters/SavitzkyGolay.h"
#include "gsl/gsl_fft_real.h"
#include "gsl/gsl_fft_halfcomplex.h"
#include <iostream>
#include <cmath>
Functions
void savgol (std::vector< double > &c, const int &np, const int &nl, const int &nr, const int &ld, const int &m)
void convlv (const std::vector< double > &data, const std::vector< double > &respns, const int &isign, std::vector< double > &ans)
void ludcmp (std::vector< double > &a, std::vector< int > &indx, double &d)
void lubksb (std::vector< double > &a, std::vector< int > &indx, std::vector< double > &b)
Function Documentation
convlv()
void convlv (const std::vector< double > & data, const std::vector< double > & respns, const int & isign, std::vector< double > & ans)
Definition at line 74 of file SavitzkyGolay.cpp.
References Hypervolume::n, and real().
Referenced by SavitzkyGolayFilter::apply(), and SavitzkyGolayFilter::calc_derivative().
lubksb()
void lubksb (std::vector< double > & a, std::vector< int > & indx, std::vector< double > & b)
Definition at line 185 of file SavitzkyGolay.cpp.
References a, Hypervolume::n, and sum().
Referenced by savgol().
ludcmp()
void ludcmp (std::vector< double > & a, std::vector< int > & indx, double & d)
Definition at line 126 of file SavitzkyGolay.cpp.
References a, abs(), endl(), Hypervolume::n, and sum().
Referenced by savgol().
savgol()
void savgol (std::vector< double > & c, const int & np, const int & nl, const int & nr, const int & ld, const int & m)
Definition at line 32 of file SavitzkyGolay.cpp.
References a, Physics::c, endl(), lubksb(), ludcmp(), nr, pow(), and sum().
Referenced by SavitzkyGolayFilter::SavitzkyGolayFilter().