OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Classic/FixedAlgebra/FTps.h File Reference
FTps.h File Reference
#include "FixedAlgebra/FTpsData.h"
#include <iosfwd>
#include <list>
#include <string>
#include "FixedAlgebra/FVps.h"
#include "FixedAlgebra/FTps.hpp"
Classes
class Array1D< T >
One-dimensional array.
class FMatrix< T, R, C >
A templated representation for matrices.
class FMonomial< N >
Representation of the exponents for a monomial with fixed dimension.
class FTpsRep< T, N >
class FVector< T, N >
A templated representation for vectors.
class FVps< T, N >
Vector truncated power series in n variables.
class FTps< T, N >
Truncated power series in N variables of type T.
Functions
template<class T , int N>
FTps< T, N > operator+ (const FTps< T, N > &, const FTps< T, N > &)
Add.
template<class T , int N>
FTps< T, N > operator- (const FTps< T, N > &, const FTps< T, N > &)
Subtract.
template<class T , int N>
FTps< T, N > operator+ (const FTps< T, N > &, const T &)
Add.
template<class T , int N>
FTps< T, N > operator- (const FTps< T, N > &, const T &)
Subtract.
template<class T , int N>
FTps< T, N > operator+ (const T &, const FTps< T, N > &)
Add.
template<class T , int N>
FTps< T, N > operator- (const T &, const FTps< T, N > &)
Subtract.
template<class T , int N>
FTps< T, N > operator* (const FTps< T, N > &, const FTps< T, N > &)
Multiply.
template<class T , int N>
FTps< T, N > operator/ (const FTps< T, N > &, const FTps< T, N > &)
Divide.
template<class T , int N>
FTps< T, N > operator* (const FTps< T, N > &, const T &)
Multiply.
template<class T , int N>
FTps< T, N > operator/ (const FTps< T, N > &, const T &)
Divide.
template<class T , int N>
FTps< T, N > operator* (const T &, const FTps< T, N > &)
Multiply.
template<class T , int N>
FTps< T, N > operator/ (const T &, const FTps< T, N > &)
Divide.
template<class T , int N>
bool operator== (const T &, const FTps< T, N > &)
Equality.
template<class T , int N>
bool operator!= (const T &, const FTps< T, N > &)
Inequality.
template<class T , int N>
FVps< T, N > ExpMap (const FTps< T, N > &H, int trunc=FTps< T, N >::EXACT)
Build the exponential series.
template<class T , int N>
FTps< T, N > ExpMap (const FTps< T, N > &H, const FTps< T, N > &f, int trunc=FTps< T, N >::EXACT)
Build the exponential series.
template<class T , int N>
FTps< T, N > PoissonBracket (const FTps< T, N > &f, const FTps< T, N > &g, int trunc=FTps< T, N >::EXACT)
Poisson bracket.
template<class T , int N>
std::istream & operator>> (std::istream &is, FTps< T, N > &)
Extract FTps from stream [b]is[/b].
template<class T , int N>
std::ostream & operator<< (std::ostream &os, const FTps< T, N > &)
Insert FTps into stream [b]os[/b].
Function Documentation
ExpMap() [1/2]
template<class T , int N> FVps<T, N> ExpMap (const FTps< T, N > & H, int trunc = FTps< T, N >::EXACT)
Build the exponential series.
Definition at line 1994 of file FTps.hpp.
Referenced by MapGenerator< Value_type, Size_type, Series_type, Map_type, Hamiltonian_type, Space_charge_type >::generateMap(), and ThickTracker::track_m().
ExpMap() [2/2]
template<class T , int N> FTps<T, N> ExpMap (const FTps< T, N > & H, const FTps< T, N > & f, int trunc = FTps< T, N >::EXACT)
Build the exponential series.
Definition at line 2000 of file FTps.hpp.
References FTps< T, N >::derivative(), endl(), FTps< T, N >::getMinOrder(), FTps< T, N >::getTruncOrder(), min(), FTps< T, N >::multiply(), FTps< T, N >::setTruncOrder(), and Attrib::Legacy::Distribution::T.
operator!=()
template<class T , int N> bool operator!= (const T & , const FTps< T, N > &)
Inequality.
Definition at line 1988 of file FTps.hpp.
operator*() [1/3]
template<class T , int N> FTps<T, N> operator* (const FTps< T, N > & , const FTps< T, N > &)
Multiply.
Definition at line 1942 of file FTps.hpp.
References FTps< T, N >::multiply().
operator*() [2/3]
template<class T , int N> FTps<T, N> operator* (const FTps< T, N > & , const T &)
Multiply.
Definition at line 1955 of file FTps.hpp.
operator*() [3/3]
template<class T , int N> FTps<T, N> operator* (const T & , const FTps< T, N > &)
Multiply.
Definition at line 1969 of file FTps.hpp.
operator+() [1/3]
template<class T , int N> FTps<T, N> operator+ (const FTps< T, N > & , const FTps< T, N > &)
Add.
Definition at line 1802 of file FTps.hpp.
References FTps< T, N >::begin(), FTps< T, N >::getMaxOrder(), FTps< T, N >::getMinOrder(), FTps< T, N >::getTruncOrder(), max(), min(), FTps< T, N >::orderEnd(), FTps< T, N >::orderStart(), and Attrib::Legacy::Distribution::T.
operator+() [2/3]
template<class T , int N> FTps<T, N> operator+ (const FTps< T, N > & , const T &)
Add.
Definition at line 1914 of file FTps.hpp.
operator+() [3/3]
template<class T , int N> FTps<T, N> operator+ (const T & , const FTps< T, N > &)
Add.
Definition at line 1928 of file FTps.hpp.
operator-() [1/3]
template<class T , int N> FTps<T, N> operator- (const FTps< T, N > & , const FTps< T, N > &)
Subtract.
Definition at line 1858 of file FTps.hpp.
References FTps< T, N >::begin(), FTps< T, N >::getMaxOrder(), FTps< T, N >::getMinOrder(), FTps< T, N >::getTruncOrder(), max(), min(), FTps< T, N >::orderEnd(), FTps< T, N >::orderStart(), and Attrib::Legacy::Distribution::T.
operator-() [2/3]
template<class T , int N> FTps<T, N> operator- (const FTps< T, N > & , const T &)
Subtract.
Definition at line 1921 of file FTps.hpp.
operator-() [3/3]
template<class T , int N> FTps<T, N> operator- (const T & , const FTps< T, N > &)
Subtract.
Definition at line 1935 of file FTps.hpp.
operator/() [1/3]
template<class T , int N> FTps<T, N> operator/ (const FTps< T, N > & , const FTps< T, N > &)
Divide.
Definition at line 1949 of file FTps.hpp.
References FTps< T, N >::divide().
operator/() [2/3]
template<class T , int N> FTps<T, N> operator/ (const FTps< T, N > & , const T &)
Divide.
Definition at line 1962 of file FTps.hpp.
operator/() [3/3]
template<class T , int N> FTps<T, N> operator/ (const T & , const FTps< T, N > &)
Divide.
Definition at line 1976 of file FTps.hpp.
References FTps< T, N >::inverse().
operator<<()
template<class T , int N> std::ostream& operator<< (std::ostream & os, const FTps< T, N > &)
Insert FTps into stream [b]os[/b].
Definition at line 2098 of file FTps.hpp.
operator==()
template<class T , int N> bool operator== (const T & , const FTps< T, N > &)
Equality.
Definition at line 1982 of file FTps.hpp.
operator>>()
template<class T , int N> std::istream& operator>> (std::istream & is, FTps< T, N > &)
Extract FTps from stream [b]is[/b].
Definition at line 2092 of file FTps.hpp.
References FTps< T, N >::get().
PoissonBracket()
template<class T , int N> FTps<T, N> PoissonBracket (const FTps< T, N > & f, const FTps< T, N > & g, int trunc = FTps< T, N >::EXACT)
Poisson bracket.
Definition at line 2058 of file FTps.hpp.