OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Field/ReductionLoc.h File Reference
ReductionLoc.h File Reference
#include "PETE/IpplExpressions.h"
#include "Field/ReductionLoc.hpp"
Classes
class NDIndex< Dim >
class BareFieldIterator< T, Dim >
class IndexedBareFieldIterator< T, Dim >
struct FindLocation< D >
Functions
template<class T , class CompOp , class AccOp , unsigned D>
T::PETE_Return_t Reduction (const PETE_Expr< T > &const_expr, CompOp comp_op, AccOp acc_op, NDIndex< D > &loc)
template<class T , class C , unsigned int D>
int for_each (const IndexedBareFieldIterator< T, D > &expr, FindLocation< D > &find_loc, C)
template<class T , class C , unsigned int D>
int for_each (const BareFieldIterator< T, D > &expr, FindLocation< D > &find_loc, C)
template<class T , unsigned D>
T::PETE_Expr_t::PETE_Return_t min (const PETE_Expr< T > &expr, NDIndex< D > &loc)
template<class T , unsigned D>
T::PETE_Expr_t::PETE_Return_t max (const PETE_Expr< T > &expr, NDIndex< D > &loc)
Function Documentation
for_each() [1/2]
template<class T , class C , unsigned int D> int for_each (const IndexedBareFieldIterator< T, D > & expr, FindLocation< D > & find_loc, C) inline
Definition at line 47 of file ReductionLoc.h.
References BareFieldIterator< T, Dim >::GetCurrentLocation(), and FindLocation< D >::Loc.
for_each() [2/2]
template<class T , class C , unsigned int D> int for_each (const BareFieldIterator< T, D > & expr, FindLocation< D > & find_loc, C) inline
Definition at line 58 of file ReductionLoc.h.
References BareFieldIterator< T, Dim >::GetCurrentLocation(), and FindLocation< D >::Loc.
max()
template<class T , unsigned D> T::PETE_Expr_t::PETE_Return_t max (const PETE_Expr< T > & expr, NDIndex< D > & loc) inline
Definition at line 84 of file ReductionLoc.h.
References PETE_Expr< WrappedExpr >::PETE_unwrap(), and Reduction().
Referenced by _FM3DMagnetoStaticExtended::_FM3DMagnetoStaticExtended(), Expressions::AbsMax(), Util::angleBetweenAngles(), ParticleBConds< T, Dim >::apply(), PatchBC< T, D, M, C >::apply(), Tracker::applyDrift(), Tracker::applyThinMultipole(), PartBunchBase< double, 3 >::boundp(), ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), MultiBunchHandler::calcBunchBeamParameters(), calcEurekaDomain(), CalcParallelInterpolationDomain(), CalcParallelPeriodicDomain(), centeredInitialize(), Individual::checkBounds(), ComponentFunctionFaceBCApply(), ComponentLinearExtrapolateFaceBCApply(), BoxCornerDomain::compute(), OrbitThreader::computeDriftLengthToBoundingBox(), DistributionMoments::computeMeans(), BoundaryGeometry::computeMeshVoxelization(), DistributionMoments::computeNormalizedEmittance(), ParallelTTracker::computeParticleMatterInteraction(), DistributionMoments::computePercentiles(), AmrBoxLib::computeSelfFields_cycl(), LossDataSink::computeSetStatistics(), Distribution::createDistributionFromFile(), SimulatedBinaryCrossover< T >::crossover(), BlendCrossover< T >::crossover(), FTps< double, 2 *3 >::divide(), ParallelTTracker::doBinaryRepartition(), AmrParticleBase< PLayout >::domainMapping(), Septum::doPreCheck(), Probe::doPreCheck(), Stripper::doPreCheck(), CCollimator::doPreCheck(), CCollimator::doSetGeom(), EllipticDomain::EllipticDomain(), Distribution::emitParticles(), ValueRange< double >::enlargeIfOutside(), BoundingBox::enlargeToContainBoundingBox(), BoundingBox::enlargeToContainPosition(), TrackCmd::execute(), Option::execute(), SampleCmd::execute(), ExtrapolateAndZeroFaceBCApply(), ExtrapolateFaceBCApply(), DistributionMoments::fillMembers(), FTps< double, 2 *3 >::filter(), ClosedOrbitFinder< Value_type, Size_type, Stepper >::findOrbit(), HashPairBuilder< PBase >::for_each(), HashPairBuilderPeriodic< PBase >::for_each(), HashPairBuilderPeriodicParallel< PBase >::for_each(), HashPairBuilderParallel< PBase >::forEach(), FunctionFaceBCApply(), Distribution::generateBinomial(), PartBunchBase< double, 3 >::get_PBounds(), Rotation3D::getAxis(), Cyclotron::getdiffs(), PartBunch::getEExtrema(), AmrBoxLib::getEExtrema(), BoundingBox::getIntersectionPoint(), Util::getLengthString(), AmrParticleBase< PLayout >::getLocalBounds_m(), OrbitThreader::getMaxDesignEnergy(), FVps< T, N >::getMaxOrder(), DistributionMoments::getMaxR(), Distribution::getMinTOrZ(), Bend2D::getOutline(), TrueCondition< T, Dim >::getRange(), IndexMap::getRange(), FVps< T, N >::getTopOrder(), Vps< T >::getTopOrder(), TBeamline< T >::getTransform(), FDoubleEigen< N >::hqr2(), BoundaryGeometry::initialize(), InterpolationFaceBCApply(), BoundaryGeometry::intersectLineSegmentBoundary(), BoundaryGeometry::intersectTinyLineSegmentBoundary(), LinearExtrapolateFaceBCApply(), Expressions::Max(), Expressions::Maxa(), PartBunchBase< double, 3 >::maximumAmplitudes(), BoxLibLayout< T, Dim >::MaxRefRatio(), ParallelCyclotronTracker::MtsTracker(), Individual::new_gene(), LaserProfile::normalizeProfileData(), MaxNormRadialPeak::operator()(), operator+(), Tps< T >::operator+=(), operator-(), Tps< T >::operator-=(), FTps< double, 2 *3 >::operator==(), OrbitThreader::OrbitThreader(), PartBins::PartBins(), PeriodicFaceBCApply(), IndexMap::print(), Object::printHelp(), MGPoissonSolver::printLoadBalanceStats(), Quaternion::Quaternion(), _FM1DProfile2::readMap(), SampleCmd::SampleCmd(), OpalBeamline::save3DLattice(), FTps< double, 2 *3 >::scaleMonomials(), FlexibleCollimator::setDescription(), PluginElement::setDimensions(), Distribution::setDistParametersGauss(), StraightGeometry::setElementLength(), VarRadiusGeometry::setElementLength(), OutputPlane::setMaxIterations(), ParallelTTracker::setOptionalVariables(), IrregularDomain::setRangeMax(), FieldLayout< Dim >::setup(), MGPoissonSolver::setupMueLuList(), AmrBoxLib::solvePoisson_m(), LossDataSink::splitSets(), UniformCartesian< Dim, MFLOAT >::storeSpacingFields(), Cartesian< Dim, MFLOAT >::storeSpacingFields(), FVps< T, N >::substitute(), FTps< double, 2 *3 >::substitute(), OpalBeamline::switchElements(), Util::toStringWithThousandSep(), OpalMonitor::update(), Voxel::Voxel(), AmrYtWriter::writeBunch(), H5PartWrapperForPT::writeStepData(), and H5PartWrapperForPC::writeStepData().
min()
template<class T , unsigned D> T::PETE_Expr_t::PETE_Return_t min (const PETE_Expr< T > & expr, NDIndex< D > & loc) inline
Definition at line 76 of file ReductionLoc.h.
References PETE_Expr< WrappedExpr >::PETE_unwrap(), and Reduction().
Referenced by IndexMap::almostEqual(), Util::angleBetweenAngles(), Undulator::apply(), ParticleBConds< T, Dim >::apply(), PatchBC< T, D, M, C >::apply(), calcEurekaDomain(), CalcParallelInterpolationDomain(), CalcParallelPeriodicDomain(), Individual::checkBounds(), ComponentFunctionFaceBCApply(), ComponentLinearExtrapolateFaceBCApply(), BoundaryGeometry::computeMeshVoxelization(), Mesher::computeMinimumAngle(), ParallelTTracker::computeParticleMatterInteraction(), cos(), cosh(), SimulatedBinaryCrossover< T >::crossover(), BlendCrossover< T >::crossover(), FTps< double, 2 *3 >::divide(), Probe::doPreCheck(), CCollimator::doPreCheck(), EllipticDomain::EllipticDomain(), ValueRange< double >::enlargeIfOutside(), BoundingBox::enlargeToContainBoundingBox(), BoundingBox::enlargeToContainPosition(), erf(), ParallelTTracker::evenlyDistributeParticles(), SampleCmd::execute(), exp(), ExpMap(), ExtrapolateAndZeroFaceBCApply(), ExtrapolateFaceBCApply(), Tps< T >::filter(), FTps< double, 2 *3 >::filter(), FunctionFaceBCApply(), PartBunchBase< double, 3 >::get_bounds(), Cyclotron::getdiffs(), PartBunch::getEExtrema(), AmrBoxLib::getEExtrema(), AmrParticleBase< PLayout >::getGlobalBounds_m(), _FM3DH5BlockBase::getIndex(), Distribution::getMaxTOrZ(), FVps< T, N >::getMinOrder(), IndexMap::getRange(), FTps< double, 2 *3 >::getSubstOrders(), TBeamline< T >::getTransform(), FVps< T, N >::getTruncOrder(), Vps< T >::getTruncOrder(), Tps< T >::getTruncOrder(), FTps< double, 2 *3 >::grow(), PyOpal::PyNDGrid::initialiseFixedSpacing(), Tps< T >::integral(), FTps< double, 2 *3 >::integral(), FFTBoxPoissonSolver::integratedGreensFunction(), InterpolationFaceBCApply(), BoundaryGeometry::intersectLineSegmentBoundary(), BoundaryGeometry::intersectTinyLineSegmentBoundary(), FVps< T, N >::inverse(), Tps< T >::inverse(), FTps< double, 2 *3 >::inverse(), LinearExtrapolateFaceBCApply(), log(), Matrix< T >::Matrix(), Expressions::Min(), Tps< T >::multiply(), FTps< double, 2 *3 >::multiply(), Tps< T >::multiplyVariable(), FTps< double, 2 *3 >::multiplyVariable(), FVps< T, N >::myInverse(), Individual::new_gene(), FVps< T, N >::operator*(), operator+(), Matrix< T >::operator+=(), Tps< T >::operator+=(), operator-(), Matrix< T >::operator-=(), Tps< T >::operator-=(), Tps< T >::operator==(), FTps< double, 2 *3 >::operator==(), OptimizeCmd::OptimizeCmd(), OrbitThreader::OrbitThreader(), PeriodicFaceBCApply(), Timing::print(), MGPoissonSolver::printLoadBalanceStats(), IndexMap::query(), AmrBoxLib::regrid(), OpalSimulation::run(), run_opal(), SampleCmd::SampleCmd(), Tps< T >::scaleMonomials(), FTps< double, 2 *3 >::scaleMonomials(), FlexibleCollimator::setDescription(), PluginElement::setDimensions(), IrregularDomain::setRangeMin(), Bend2D::setupFringeWidths(), FFTBoxPoissonSolver::shiftedIntGreensFunction(), sin(), sinh(), sqrt(), UniformCartesian< Dim, MFLOAT >::storeSpacingFields(), Cartesian< Dim, MFLOAT >::storeSpacingFields(), VpsMap< T >::substitute(), FVps< T, N >::substitute(), FTps< double, 2 *3 >::substitute(), OpalBeamline::switchElements(), OrbitThreader::trackBack(), TransportMap< T, N >::TransportMap(), ParallelTTracker::updateReferenceParticle(), Voxel::Voxel(), AmrYtWriter::writeBunch(), H5PartWrapperForPC::writeStepData(), and H5PartWrapperForPT::writeStepData().
Reduction()
template<class T , class CompOp , class AccOp , unsigned D> T::PETE_Return_t Reduction (const PETE_Expr< T > & const_expr, CompOp comp_op, AccOp acc_op, NDIndex< D > & loc)
Definition at line 94 of file ReductionLoc.hpp.
References for_each(), ReduceLoc< T, LOC >::Loc, Hypervolume::n, PETE_apply(), PETE_Expr< WrappedExpr >::PETE_unwrap(), Attrib::Distribution::R, reduce_masked(), and ReduceLoc< T, LOC >::Val.
Referenced by any(), bounds(), max(), min(), minmax(), and where().