OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyVariableRFCavityFringeField Namespace Reference
PyOpal::PyVariableRFCavityFringeField Namespace Reference
Functions
BOOST_PYTHON_MODULE (variable_rf_cavity_fringe_field)
Variables
const char * module_docstring
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyVariableRFCavityFringeField::BOOST_PYTHON_MODULE (variable_rf_cavity_fringe_field)
Definition at line 65 of file PyVariableRFCavityFringeField.cpp.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::addGetFieldValue(), Physics::e, PyOpal::Globals::Initialise(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_element_class(), PyOpal::ExceptionTranslation::registerExceptions(), and Units::s2ns.
Variable Documentation
module_docstring
const char* PyOpal::PyVariableRFCavityFringeField::module_docstring
Initial value:
=
            "variable_rf_cavity contains the VariableRFCavityFringeField class"
Definition at line 62 of file PyVariableRFCavityFringeField.cpp.