OPAL (Object Oriented Parallel Accelerator Library): RegionLayout< T, Dim, MeshType > Class Template Reference
RegionLayout< T, Dim, MeshType > Class Template Reference
#include <RegionLayout.h>
Classes
class RnodePool
Public Types
typedef vmap< Unique::type, Rnode< T, Dim > * > ac_id_vnodes
typedef DomainMap< NDRegion< T, Dim >, Rnode< T, Dim > *, TouchesRegion< T, Dim >, ContainsRegion< T, Dim >, SplitRegion< T, Dim > > ac_domain_vnodes
typedef ac_id_vnodes::iterator iterator_iv
typedef ac_id_vnodes::const_iterator const_iterator_iv
typedef ac_domain_vnodes::iterator iterator_dv
typedef ac_domain_vnodes::const_iterator const_iterator_dv
typedef ac_domain_vnodes::touch_iterator touch_iterator_dv
typedef std::pair< touch_iterator_dv, touch_iterator_dv > touch_range_dv
Public Types inherited from User
typedef Unique::type ID_t
Public Member Functions
RegionLayout ()
RegionLayout (const RegionLayout< T, Dim, MeshType > &)
RegionLayout (const NDRegion< T, Dim > &domain, MeshType &mesh, int vnodes=-1)
RegionLayout (const PRegion< T > &i1, MeshType &mesh, int vnodes=-1)
RegionLayout (const PRegion< T > &i1, const PRegion< T > &i2, MeshType &mesh, int vnodes=-1)
RegionLayout (const PRegion< T > &i1, const PRegion< T > &i2, const PRegion< T > &i3, MeshType &mesh, int vnodes=-1)
RegionLayout (FieldLayout< Dim > &)
RegionLayout (FieldLayout< Dim > &, MeshType &)
RegionLayout (const NDIndex< Dim > &domain, int vnodes=-1)
RegionLayout (const Index &i1, int vnodes=-1)
RegionLayout (const Index &i1, const Index &i2, int vnodes=-1)
RegionLayout (const Index &i1, const Index &i2, const Index &i3, int vnodes=-1)
RegionLayout (const NDIndex< Dim > &domain, MeshType &mesh, int vnodes=-1)
RegionLayout (const Index &i1, MeshType &mesh, int vnodes=-1)
RegionLayout (const Index &i1, const Index &i2, MeshType &mesh, int vnodes=-1)
RegionLayout (const Index &i1, const Index &i2, const Index &i3, MeshType &mesh, int vnodes=-1)
virtual ~RegionLayout ()
bool initialized () const
const NDRegion< T, Dim > & getDomain () const
FieldLayout< Dim > & getFieldLayout ()
const FieldLayout< Dim > & getFieldLayout () const
MeshType & getMesh ()
const MeshType & getMesh () const
ac_id_vnodes::size_type size_iv () const
iterator_iv begin_iv ()
iterator_iv end_iv ()
const_iterator_iv begin_iv () const
const_iterator_iv end_iv () const
ac_domain_vnodes::size_type size_rdv () const
iterator_dv begin_rdv ()
iterator_dv end_rdv ()
const_iterator_dv begin_rdv () const
const_iterator_dv end_rdv () const
touch_range_dv touch_range_rdv (const NDRegion< T, Dim > &domain)
void changeDomain (FieldLayout< Dim > &)
void changeDomain (const NDIndex< Dim > &, int vnodes=-1)
void changeDomain (const NDRegion< T, Dim > &, int vnodes=-1)
void RepartitionLayout (NDIndex< Dim > *, NDIndex< Dim > *)
void RepartitionLayout (NDIndex< Dim > &domain)
NDRegion< T, Dim > convert_index (const NDIndex< Dim > &) const
NDIndex< Dim > convert_region (const NDRegion< T, Dim > &) const
bool operator== (const RegionLayout< T, Dim, MeshType > &x)
virtual void Repartition (UserList *)
virtual void notifyUserOfDelete (UserList *)
UserList::ID_t get_Id () const
void checkin (FieldLayoutUser &f)
void checkout (FieldLayoutUser &f)
Public Member Functions inherited from FieldLayoutUser
FieldLayoutUser ()
virtual ~FieldLayoutUser ()
Public Member Functions inherited from User
User ()
virtual ~User ()
ID_t get_Id () const
Private Member Functions
void setup (const NDRegion< T, Dim > &, int)
void make_rnodes (const NDRegion< T, Dim > &, FieldLayout< Dim > &)
void delete_rnodes ()
void store_flayout (FieldLayout< Dim > *, bool WeOwn)
void delete_flayout ()
void store_mesh (MeshType *, bool WeOwn)
void delete_mesh ()
NDRegion< T, Dim > getMeshDomain (MeshType *)
NDIndex< Dim > getMeshVertices (MeshType *)
Private Member Functions inherited from UserList
UserList ()
virtual ~UserList ()
size_type_user getNumUsers () const
ID_t getUserListID () const
bool haveUser (Key key) const
User & getUser (Key key)
iterator_user begin_user ()
iterator_user end_user ()
virtual ID_t checkinUser (User &user)
virtual void checkoutUser (Key key, bool informuser=false)
virtual void checkoutUser (const User &user, bool informuser=false)
Private Attributes
ac_id_vnodes Local_ac
ac_domain_vnodes * Remote_ac
NDRegion< T, Dim > Domain
FieldLayout< Dim > * FLayout
bool WeOwnFieldLayout
MeshType * theMesh
bool WeOwnMesh
NDIndex< Dim > MeshVertices
int IndexOffset [Dim]
bool CenterOffset [Dim]
Static Private Attributes
static RnodePool StaticRnodePool
Additional Inherited Members
Protected Attributes inherited from User
ID_t Id
Private Types inherited from UserList
typedef User::ID_t Key
typedef vmap< Key, User * > UserList_t
typedef UserList_t::iterator iterator_user
typedef UserList_t::size_type size_type_user
typedef User::ID_t ID_t
Detailed Description
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>>
class RegionLayout< T, Dim, MeshType >
Definition at line 48 of file RegionLayout.h.
Member Typedef Documentation
ac_domain_vnodes
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> typedef DomainMap<NDRegion<T,Dim>, Rnode<T,Dim> *, TouchesRegion<T,Dim>, ContainsRegion<T,Dim>, SplitRegion<T,Dim> > RegionLayout< T, Dim, MeshType >::ac_domain_vnodes
Definition at line 63 of file RegionLayout.h.
ac_id_vnodes
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> typedef vmap<Unique::type, Rnode<T,Dim> *> RegionLayout< T, Dim, MeshType >::ac_id_vnodes
Definition at line 59 of file RegionLayout.h.
const_iterator_dv
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> typedef ac_domain_vnodes::const_iterator RegionLayout< T, Dim, MeshType >::const_iterator_dv
Definition at line 69 of file RegionLayout.h.
const_iterator_iv
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> typedef ac_id_vnodes::const_iterator RegionLayout< T, Dim, MeshType >::const_iterator_iv
Definition at line 67 of file RegionLayout.h.
iterator_dv
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> typedef ac_domain_vnodes::iterator RegionLayout< T, Dim, MeshType >::iterator_dv
Definition at line 68 of file RegionLayout.h.
iterator_iv
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> typedef ac_id_vnodes::iterator RegionLayout< T, Dim, MeshType >::iterator_iv
Definition at line 66 of file RegionLayout.h.
touch_iterator_dv
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> typedef ac_domain_vnodes::touch_iterator RegionLayout< T, Dim, MeshType >::touch_iterator_dv
Definition at line 70 of file RegionLayout.h.
touch_range_dv
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> typedef std::pair<touch_iterator_dv,touch_iterator_dv> RegionLayout< T, Dim, MeshType >::touch_range_dv
Definition at line 71 of file RegionLayout.h.
Constructor & Destructor Documentation
RegionLayout() [1/16]
template<class T , unsigned Dim, class MeshType > RegionLayout< T, Dim, MeshType >::RegionLayout ()
Definition at line 45 of file RegionLayout.hpp.
RegionLayout() [2/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (const RegionLayout< T, Dim, MeshType > & r)
Definition at line 68 of file RegionLayout.hpp.
RegionLayout() [3/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (const NDRegion< T, Dim > & domain, MeshType & mesh, int vnodes = -1)
Definition at line 117 of file RegionLayout.hpp.
RegionLayout() [4/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (const PRegion< T > & i1, MeshType & mesh, int vnodes = -1)
Definition at line 132 of file RegionLayout.hpp.
RegionLayout() [5/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (const PRegion< T > & i1, const PRegion< T > & i2, MeshType & mesh, int vnodes = -1)
Definition at line 151 of file RegionLayout.hpp.
RegionLayout() [6/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (const PRegion< T > & i1, const PRegion< T > & i2, const PRegion< T > & i3, MeshType & mesh, int vnodes = -1)
Definition at line 172 of file RegionLayout.hpp.
RegionLayout() [7/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (FieldLayout< Dim > & fl)
Definition at line 363 of file RegionLayout.hpp.
RegionLayout() [8/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (FieldLayout< Dim > & fl, MeshType & mesh)
Definition at line 384 of file RegionLayout.hpp.
RegionLayout() [9/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (const NDIndex< Dim > & domain, int vnodes = -1)
Definition at line 196 of file RegionLayout.hpp.
RegionLayout() [10/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (const Index & i1, int vnodes = -1)
Definition at line 216 of file RegionLayout.hpp.
RegionLayout() [11/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (const Index & i1, const Index & i2, int vnodes = -1)
Definition at line 236 of file RegionLayout.hpp.
RegionLayout() [12/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (const Index & i1, const Index & i2, const Index & i3, int vnodes = -1)
Definition at line 259 of file RegionLayout.hpp.
RegionLayout() [13/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (const NDIndex< Dim > & domain, MeshType & mesh, int vnodes = -1)
Definition at line 284 of file RegionLayout.hpp.
RegionLayout() [14/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (const Index & i1, MeshType & mesh, int vnodes = -1)
Definition at line 300 of file RegionLayout.hpp.
RegionLayout() [15/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (const Index & i1, const Index & i2, MeshType & mesh, int vnodes = -1)
Definition at line 320 of file RegionLayout.hpp.
RegionLayout() [16/16]
template<class T, unsigned Dim, class MeshType> RegionLayout< T, Dim, MeshType >::RegionLayout (const Index & i1, const Index & i2, const Index & i3, MeshType & mesh, int vnodes = -1)
Definition at line 340 of file RegionLayout.hpp.
~RegionLayout()
template<class T , unsigned Dim, class MeshType > RegionLayout< T, Dim, MeshType >::~RegionLayout () virtual
Definition at line 99 of file RegionLayout.hpp.
Member Function Documentation
begin_iv() [1/2]
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> iterator_iv RegionLayout< T, Dim, MeshType >::begin_iv () inline
Definition at line 146 of file RegionLayout.h.
Referenced by ParticleSpatialLayout< T, Dim, Mesh >::new_swap_particles(), ParticleCashedLayout< T, Dim, Mesh >::rebuild_interaction_data(), ParticleInteractLayout< T, Dim, Mesh >::rebuild_interaction_data(), ParticleSpatialLayout< T, Dim, Mesh >::short_swap_particles(), ParticleCashedLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleInteractLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleSpatialLayout< T, Dim, Mesh >::swap_particles(), and BoxParticleCachingPolicy< T, Dim, Mesh >::updateCacheInformation().
begin_iv() [2/2]
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> const_iterator_iv RegionLayout< T, Dim, MeshType >::begin_iv () const inline
Definition at line 148 of file RegionLayout.h.
begin_rdv() [1/2]
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> iterator_dv RegionLayout< T, Dim, MeshType >::begin_rdv () inline
Definition at line 155 of file RegionLayout.h.
begin_rdv() [2/2]
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> const_iterator_dv RegionLayout< T, Dim, MeshType >::begin_rdv () const inline
Definition at line 157 of file RegionLayout.h.
changeDomain() [1/3]
template<class T , unsigned Dim, class MeshType > void RegionLayout< T, Dim, MeshType >::changeDomain (FieldLayout< Dim > & fl)
Definition at line 486 of file RegionLayout.hpp.
Referenced by PartBunch::initialize(), and ParticleSpatialLayout< T, Dim, Mesh >::rebuild_layout().
changeDomain() [2/3]
template<class T , unsigned Dim, class MeshType > void RegionLayout< T, Dim, MeshType >::changeDomain (const NDIndex< Dim > & domain, int vnodes = -1)
Definition at line 401 of file RegionLayout.hpp.
changeDomain() [3/3]
template<class T, unsigned Dim, class MeshType > void RegionLayout< T, Dim, MeshType >::changeDomain (const NDRegion< T, Dim > & domain, int vnodes = -1)
Definition at line 444 of file RegionLayout.hpp.
checkin()
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> void RegionLayout< T, Dim, MeshType >::checkin (FieldLayoutUser & f) inline
Definition at line 231 of file RegionLayout.h.
checkout()
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> void RegionLayout< T, Dim, MeshType >::checkout (FieldLayoutUser & f) inline
Definition at line 237 of file RegionLayout.h.
convert_index()
template<class T , unsigned Dim, class MeshType > NDRegion< T, Dim > RegionLayout< T, Dim, MeshType >::convert_index (const NDIndex< Dim > & ni) const
Definition at line 526 of file RegionLayout.hpp.
convert_region()
template<class T, unsigned Dim, class MeshType > NDIndex< Dim > RegionLayout< T, Dim, MeshType >::convert_region (const NDRegion< T, Dim > & nr) const
Definition at line 572 of file RegionLayout.hpp.
delete_flayout()
template<class T , unsigned Dim, class MeshType > void RegionLayout< T, Dim, MeshType >::delete_flayout () private
Definition at line 715 of file RegionLayout.hpp.
delete_mesh()
template<class T , unsigned Dim, class MeshType > void RegionLayout< T, Dim, MeshType >::delete_mesh () private
Definition at line 752 of file RegionLayout.hpp.
delete_rnodes()
template<class T , unsigned Dim, class MeshType > void RegionLayout< T, Dim, MeshType >::delete_rnodes () private
Definition at line 668 of file RegionLayout.hpp.
end_iv() [1/2]
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> iterator_iv RegionLayout< T, Dim, MeshType >::end_iv () inline
Definition at line 147 of file RegionLayout.h.
Referenced by ParticleSpatialLayout< T, Dim, Mesh >::new_swap_particles(), ParticleCashedLayout< T, Dim, Mesh >::rebuild_interaction_data(), ParticleInteractLayout< T, Dim, Mesh >::rebuild_interaction_data(), ParticleSpatialLayout< T, Dim, Mesh >::short_swap_particles(), ParticleCashedLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleInteractLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleSpatialLayout< T, Dim, Mesh >::swap_particles(), and BoxParticleCachingPolicy< T, Dim, Mesh >::updateCacheInformation().
end_iv() [2/2]
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> const_iterator_iv RegionLayout< T, Dim, MeshType >::end_iv () const inline
Definition at line 149 of file RegionLayout.h.
end_rdv() [1/2]
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> iterator_dv RegionLayout< T, Dim, MeshType >::end_rdv () inline
Definition at line 156 of file RegionLayout.h.
end_rdv() [2/2]
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> const_iterator_dv RegionLayout< T, Dim, MeshType >::end_rdv () const inline
Definition at line 158 of file RegionLayout.h.
get_Id()
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> UserList::ID_t RegionLayout< T, Dim, MeshType >::get_Id () const inline
Definition at line 226 of file RegionLayout.h.
getDomain()
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> const NDRegion<T,Dim>& RegionLayout< T, Dim, MeshType >::getDomain (void) const inline
Definition at line 131 of file RegionLayout.h.
Referenced by ParticleSpatialLayout< T, Dim, Mesh >::swap_particles(), and BoxParticleCachingPolicy< T, Dim, Mesh >::updateCacheInformation().
getFieldLayout() [1/2]
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> FieldLayout<Dim>& RegionLayout< T, Dim, MeshType >::getFieldLayout () inline
Definition at line 137 of file RegionLayout.h.
Referenced by BinaryRepartition(), PartBunch::getFieldLayout(), and ParticleSpatialLayout< T, Dim, Mesh >::getFieldLayout().
getFieldLayout() [2/2]
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> const FieldLayout<Dim>& RegionLayout< T, Dim, MeshType >::getFieldLayout () const inline
Definition at line 138 of file RegionLayout.h.
getMesh() [1/2]
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> MeshType& RegionLayout< T, Dim, MeshType >::getMesh () inline
Definition at line 141 of file RegionLayout.h.
Referenced by BinaryRepartition(), and PartBunch::getMesh().
getMesh() [2/2]
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> const MeshType& RegionLayout< T, Dim, MeshType >::getMesh () const inline
Definition at line 142 of file RegionLayout.h.
getMeshDomain()
template<class T , unsigned Dim, class MeshType> NDRegion< T, Dim > RegionLayout< T, Dim, MeshType >::getMeshDomain (MeshType * m) private
Definition at line 767 of file RegionLayout.hpp.
getMeshVertices()
template<class T , unsigned Dim, class MeshType> NDIndex< Dim > RegionLayout< T, Dim, MeshType >::getMeshVertices (MeshType * m) private
Definition at line 788 of file RegionLayout.hpp.
initialized()
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> bool RegionLayout< T, Dim, MeshType >::initialized () const inline
Definition at line 128 of file RegionLayout.h.
Referenced by BinaryRepartition(), and ParticleSpatialLayout< T, Dim, Mesh >::rebuild_layout().
make_rnodes()
template<class T, unsigned Dim, class MeshType > void RegionLayout< T, Dim, MeshType >::make_rnodes (const NDRegion< T, Dim > & dom, FieldLayout< Dim > & FL) private
Definition at line 607 of file RegionLayout.hpp.
notifyUserOfDelete()
template<class T , unsigned Dim, class MeshType > void RegionLayout< T, Dim, MeshType >::notifyUserOfDelete (UserList * userlist) virtual
Implements User.
Definition at line 912 of file RegionLayout.hpp.
operator==()
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> bool RegionLayout< T, Dim, MeshType >::operator== (const RegionLayout< T, Dim, MeshType > & x) inline
Definition at line 201 of file RegionLayout.h.
Repartition()
template<class T , unsigned Dim, class MeshType > void RegionLayout< T, Dim, MeshType >::Repartition (UserList * userlist) virtual
Implements FieldLayoutUser.
Definition at line 865 of file RegionLayout.hpp.
RepartitionLayout() [1/2]
template<class T , unsigned Dim, class MeshType > void RegionLayout< T, Dim, MeshType >::RepartitionLayout (NDIndex< Dim > * ni, NDIndex< Dim > * nf)
Definition at line 846 of file RegionLayout.hpp.
Referenced by BinaryRepartition(), and RegionLayout< T, Dim, Mesh >::RepartitionLayout().
RepartitionLayout() [2/2]
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> void RegionLayout< T, Dim, MeshType >::RepartitionLayout (NDIndex< Dim > & domain) inline
Definition at line 184 of file RegionLayout.h.
setup()
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> void RegionLayout< T, Dim, MeshType >::setup (const NDRegion< T, Dim > & , int) private
size_iv()
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> ac_id_vnodes::size_type RegionLayout< T, Dim, MeshType >::size_iv () const inline
Definition at line 145 of file RegionLayout.h.
Referenced by ParticleSpatialLayout< T, Dim, Mesh >::rebuild_layout(), and RegionLayout< T, Dim, Mesh >::RegionLayout().
size_rdv()
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> ac_domain_vnodes::size_type RegionLayout< T, Dim, MeshType >::size_rdv () const inline
Definition at line 152 of file RegionLayout.h.
Referenced by ParticleSpatialLayout< T, Dim, Mesh >::rebuild_layout(), and RegionLayout< T, Dim, Mesh >::RegionLayout().
store_flayout()
template<class T , unsigned Dim, class MeshType > void RegionLayout< T, Dim, MeshType >::store_flayout (FieldLayout< Dim > * f, bool WeOwn) private
Definition at line 694 of file RegionLayout.hpp.
store_mesh()
template<class T , unsigned Dim, class MeshType> void RegionLayout< T, Dim, MeshType >::store_mesh (MeshType * m, bool WeOwn) private
Definition at line 729 of file RegionLayout.hpp.
touch_range_rdv()
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> touch_range_dv RegionLayout< T, Dim, MeshType >::touch_range_rdv (const NDRegion< T, Dim > & domain) inline
Definition at line 159 of file RegionLayout.h.
Referenced by ParticleSpatialLayout< T, Dim, Mesh >::new_swap_particles(), ParticleCashedLayout< T, Dim, Mesh >::rebuild_interaction_data(), ParticleInteractLayout< T, Dim, Mesh >::rebuild_interaction_data(), ParticleSpatialLayout< T, Dim, Mesh >::short_swap_particles(), ParticleCashedLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleInteractLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleSpatialLayout< T, Dim, Mesh >::swap_particles(), and BoxParticleCachingPolicy< T, Dim, Mesh >::updateCacheInformation().
Member Data Documentation
CenterOffset
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> bool RegionLayout< T, Dim, MeshType >::CenterOffset[Dim] private
Definition at line 262 of file RegionLayout.h.
Referenced by RegionLayout< T, Dim, Mesh >::RegionLayout().
Domain
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> NDRegion<T,Dim> RegionLayout< T, Dim, MeshType >::Domain private
Definition at line 245 of file RegionLayout.h.
Referenced by RegionLayout< T, Dim, Mesh >::getDomain(), RegionLayout< T, Dim, Mesh >::operator==(), and RegionLayout< T, Dim, Mesh >::RegionLayout().
FLayout
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> FieldLayout<Dim>* RegionLayout< T, Dim, MeshType >::FLayout private
Definition at line 248 of file RegionLayout.h.
Referenced by RegionLayout< T, Dim, Mesh >::getFieldLayout(), RegionLayout< T, Dim, Mesh >::initialized(), and RegionLayout< T, Dim, Mesh >::RegionLayout().
IndexOffset
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> int RegionLayout< T, Dim, MeshType >::IndexOffset[Dim] private
Definition at line 259 of file RegionLayout.h.
Referenced by RegionLayout< T, Dim, Mesh >::RegionLayout().
Local_ac
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> ac_id_vnodes RegionLayout< T, Dim, MeshType >::Local_ac private
Definition at line 241 of file RegionLayout.h.
Referenced by RegionLayout< T, Dim, Mesh >::begin_iv(), RegionLayout< T, Dim, Mesh >::end_iv(), and RegionLayout< T, Dim, Mesh >::size_iv().
MeshVertices
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> NDIndex<Dim> RegionLayout< T, Dim, MeshType >::MeshVertices private
Definition at line 256 of file RegionLayout.h.
Remote_ac
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> ac_domain_vnodes* RegionLayout< T, Dim, MeshType >::Remote_ac private
Definition at line 242 of file RegionLayout.h.
Referenced by RegionLayout< T, Dim, Mesh >::begin_rdv(), RegionLayout< T, Dim, Mesh >::end_rdv(), RegionLayout< T, Dim, Mesh >::size_rdv(), and RegionLayout< T, Dim, Mesh >::touch_range_rdv().
StaticRnodePool
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> RegionLayout< T, Dim, MeshType >::RnodePool RegionLayout< T, Dim, MeshType >::StaticRnodePool static private
Definition at line 340 of file RegionLayout.h.
theMesh
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> MeshType* RegionLayout< T, Dim, MeshType >::theMesh private
Definition at line 252 of file RegionLayout.h.
Referenced by RegionLayout< T, Dim, Mesh >::getMesh(), and RegionLayout< T, Dim, Mesh >::RegionLayout().
WeOwnFieldLayout
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> bool RegionLayout< T, Dim, MeshType >::WeOwnFieldLayout private
Definition at line 249 of file RegionLayout.h.
Referenced by RegionLayout< T, Dim, Mesh >::RegionLayout().
WeOwnMesh
template<class T, unsigned Dim, class MeshType = UniformCartesian<Dim,T>> bool RegionLayout< T, Dim, MeshType >::WeOwnMesh private
Definition at line 253 of file RegionLayout.h.
Referenced by RegionLayout< T, Dim, Mesh >::RegionLayout().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Region/RegionLayout.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Region/RegionLayout.hpp