OPAL (Object Oriented Parallel Accelerator Library): OpalOutputPlane Class Reference
OpalOutputPlane Class Reference
Interface for output plane element.
#include <OpalOutputPlane.h>
Public Types
enum {
CENTRE = COMMON, NORMAL, WIDTH, HEIGHT,
RADIUS, XSTART, XEND, YSTART,
YEND, PLACEMENT_STYLE, ALGORITHM, TOLERANCE,
REFERENCE_ALIGNMENT_PARTICLE, VERBOSE, SIZE
}
The attributes of class OpalOutputPlane.
Public Types inherited from OpalElement
enum {
TYPE, APERT, LENGTH, ELEMEDGE,
WAKEF, PARTICLEMATTERINTERACTION, ORIGIN, ORIENTATION,
X, Y, Z, THETA,
PHI, PSI, DX, DY,
DZ, DTHETA, DPHI, DPSI,
OUTFN, DELETEONTRANSVERSEEXIT, COMMON
}
The common attributes for all elements.
Public Types inherited from Element
enum ReferenceType { IS_ENTRY, IS_CENTRE, IS_EXIT }
Reference for element positioning.
Public Member Functions
OpalOutputPlane ()
Exemplar constructor.
virtual ~OpalOutputPlane ()
virtual OpalOutputPlane * clone (const std::string &name)
Make clone.
virtual void update ()
Fill in all registered attributes.
Public Member Functions inherited from OpalElement
virtual ~OpalElement ()
virtual double getLength () const
Return element length.
const std::string getTypeName () const
Return the element's type name.
std::pair< ApertureType, std::vector< double > > getApert () const
const std::string getWakeF () const
Return the element's type name.
const std::string getParticleMatterInteraction () const
const std::string getWMaterial () const
const std::string getWakeGeom () const
std::vector< double > getWakeParam () const
const std::string getWakeConductivity () const
virtual void parse (Statement &)
Parse the element.
virtual void print (std::ostream &) const
Print the object.
virtual void updateUnknown (ElementBase *)
Transmit the `‘unknown’' (not known to OPAL) attributes to CLASSIC.
Public Member Functions inherited from Element
virtual ~Element ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual double getEntrance (ReferenceType) const
Return arc length from origin to entrance (negative !).
virtual double getExit (ReferenceType) const
Return arc length from origin to exit (positive !).
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded CLASSIC element.
void setElement (ElementBase *)
Assign new CLASSIC element.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
OpalOutputPlane (const OpalOutputPlane &)
void operator= (const OpalOutputPlane &)
OpalOutputPlane (const std::string &name, OpalOutputPlane *parent)
Additional Inherited Members
Static Public Member Functions inherited from Element
static Element * find (const std::string &name)
Find named Element.
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from OpalElement
OpalElement (int size, const char *name, const char *help)
Exemplar constructor.
OpalElement (const std::string &name, OpalElement *parent)
Clone constructor.
void registerOwnership () const
Protected Member Functions inherited from Element
Element (int size, const char *name, const char *help)
Constructor for exemplars.
Element (const std::string &name, Element *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Static Protected Member Functions inherited from OpalElement
static void printMultipoleStrength (std::ostream &os, int order, int &len, const std::string &sName, const std::string &tName, const Attribute &length, const Attribute &vNorm, const Attribute &vSkew)
Print multipole components in OPAL-8 format.
static void printAttribute (std::ostream &os, const std::string &name, const std::string &image, int &len)
Print an attribute with a OPAL-8 name (as an expression).
static void printAttribute (std::ostream &os, const std::string &name, double value, int &len)
Print an attribute with a OPAL-8 name (as a constant).
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Interface for output plane element.
Definition at line 25 of file OpalOutputPlane.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
The attributes of class OpalOutputPlane.
Enumerator
CENTRE
NORMAL
WIDTH
HEIGHT
RADIUS
XSTART
XEND
YSTART
YEND
PLACEMENT_STYLE
ALGORITHM
TOLERANCE
REFERENCE_ALIGNMENT_PARTICLE
VERBOSE
SIZE
Definition at line 30 of file OpalOutputPlane.h.
Constructor & Destructor Documentation
OpalOutputPlane() [1/3]
OpalOutputPlane::OpalOutputPlane ()
Exemplar constructor.
Definition at line 25 of file OpalOutputPlane.cpp.
References ALGORITHM, CENTRE, Physics::e, HEIGHT, Object::itsAttr, Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeRealArray(), NORMAL, PLACEMENT_STYLE, RADIUS, REFERENCE_ALIGNMENT_PARTICLE, OpalElement::registerOwnership(), Element::setElement(), TOLERANCE, VERBOSE, WIDTH, XEND, XSTART, YEND, and YSTART.
Referenced by clone().
~OpalOutputPlane()
OpalOutputPlane::~OpalOutputPlane () virtual
Definition at line 73 of file OpalOutputPlane.cpp.
OpalOutputPlane() [2/3]
OpalOutputPlane::OpalOutputPlane (const OpalOutputPlane &) private
OpalOutputPlane() [3/3]
OpalOutputPlane::OpalOutputPlane (const std::string & name, OpalOutputPlane * parent) private
Definition at line 66 of file OpalOutputPlane.cpp.
References Element::getElement(), and Element::setElement().
Member Function Documentation
clone()
OpalOutputPlane * OpalOutputPlane::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 77 of file OpalOutputPlane.cpp.
References name, and OpalOutputPlane().
operator=()
void OpalOutputPlane::operator= (const OpalOutputPlane &) private
update()
void OpalOutputPlane::update () virtual
Fill in all registered attributes.
Update the embedded CLASSIC septum.
Reimplemented from OpalElement.
Definition at line 81 of file OpalOutputPlane.cpp.
References ALGORITHM, CENTRE, euclidean_norm(), floor(), Element::getElement(), Attributes::getReal(), Attributes::getRealArray(), Attributes::getString(), HEIGHT, OutputPlane::INTERPOLATION, Object::itsAttr, NORMAL, OpalElement::OUTFN, PLACEMENT_STYLE, RADIUS, Hypervolume::ref, REFERENCE_ALIGNMENT_PARTICLE, OutputPlane::RK4STEP, OutputPlane::setAlgorithm(), OutputPlane::setCentre(), OutputPlane::setHorizontalExtent(), OutputPlane::setNormal(), ElementBase::setOutputFN(), OutputPlane::setRadialExtent(), OutputPlane::setRecentre(), OutputPlane::setTolerance(), OutputPlane::setVerboseLevel(), OutputPlane::setVerticalExtent(), sqrt(), TOLERANCE, OpalElement::update(), OpalElement::updateUnknown(), VERBOSE, WIDTH, XEND, XSTART, YEND, and YSTART.
The documentation for this class was generated from the following files:
src/Elements/OpalOutputPlane.h
src/Elements/OpalOutputPlane.cpp