OPAL (Object Oriented Parallel Accelerator Library): IndexedField< T, Dim, Brackets, M, C > Class Template Reference
IndexedField< T, Dim, Brackets, M, C > Class Template Reference
#include <Field.h>
Public Member Functions
IndexedField< T, Dim, Brackets+1, M, C > operator[] (const Index &idx)
IndexedField< T, Dim, Brackets+1, M, C > operator[] (int i)
IndexedField< T, Dim, Dim, M, C > operator[] (const NDIndex< Dim > &ndidx)
void operator= (T x)
IndexedField< T, Dim, Brackets, M, C > & operator= (const IndexedField< T, Dim, Brackets, M, C > &x)
IndexedField< T, Dim, Brackets, M, C > & operator= (const Index &x)
template<class T1 , unsigned Dim1, unsigned Brackets1, class M1 , class C1 >
IndexedField< T, Dim, Brackets, M, C > & operator= (const IndexedField< T1, Dim1, Brackets1, M1, C1 > &x)
template<class B >
IndexedField< T, Dim, Brackets, M, C > & operator= (const PETE_Expr< B > &x)
Field< T, Dim, M, C > & getField ()
const Field< T, Dim, M, C > & getField () const
Public Member Functions inherited from IndexedBareField< T, Dim, Brackets >
constexpr IndexedBareField (const IndexedBareField< T, Dim, Brackets > &)=default
IndexedBareField< T, Dim, Brackets+1 > operator[] (const Index &idx)
IndexedBareField< T, Dim, Brackets+1 > operator[] (int i)
IndexedBareField< T, Dim, Brackets+1 > operator[] (const NDIndex< Dim > &ndidx)
void operator= (T x)
IndexedBareField< T, Dim, Brackets > & operator= (const IndexedBareField< T, Dim, Brackets > &x)
template<class X , unsigned Dim1, unsigned Brackets1>
IndexedBareField< T, Dim, Brackets > & operator= (const IndexedBareField< X, Dim1, Brackets1 > &x)
IndexedBareField< T, Dim, Brackets > & operator= (const Index &x)
template<class B >
IndexedBareField< T, Dim, Brackets > & operator= (const PETE_Expr< B > &x)
const NDIndex< Dim > & getDomain () const
BareField< T, Dim > & getBareField ()
const BareField< T, Dim > & getBareField () const
PETE_TUTree< OpParens< int >, iterator > operator() (int arg)
PETE_TUTree< OpParens< std::pair< int, int > >, iterator > operator() (int a1, int a2)
T get ()
iterator begin () const
iterator end () const
void write (std::ostream &)
iterator MakeExpression () const
Public Member Functions inherited from PETE_Expr< IndexedBareField< T, Dim, Brackets > >
IndexedBareField< T, Dim, Brackets > & PETE_unwrap ()
const IndexedBareField< T, Dim, Brackets > & PETE_unwrap () const
Protected Member Functions
IndexedField (Field< T, Dim, M, C > &f, const Index &idx)
IndexedField (Field< T, Dim, M, C > &f, int i)
IndexedField (Field< T, Dim, M, C > &f, const NDIndex< Brackets-1 > &idx, const Index &i)
IndexedField (Field< T, Dim, M, C > &f, const NDIndex< Dim > &ndidx)
Protected Member Functions inherited from IndexedBareField< T, Dim, Brackets >
IndexedBareField (BareField< T, Dim > &a, const Index &idx)
IndexedBareField (BareField< T, Dim > &a, int i)
IndexedBareField (BareField< T, Dim > &a, const NDIndex< Brackets-1 > &idx, const Index &i)
IndexedBareField (BareField< T, Dim > &a, const NDIndex< Dim > &ndidx)
void getsingle (T &)
Protected Attributes
Field< T, Dim, M, C > & F
Protected Attributes inherited from IndexedBareField< T, Dim, Brackets >
BareField< T, Dim > & A
NDIndex< Brackets > Indexes
Friends
class IndexedField< T, Dim, Brackets-1, M, C >
class Field< T, Dim, M, C >
Additional Inherited Members
Public Types inherited from IndexedBareField< T, Dim, Brackets >
enum { Dim_u = Dim }
enum { IsExpr = 0 }
typedef T T_t
typedef IndexedBareFieldIterator< T, Dim > iterator
typedef iterator PETE_Expr_t
Public Types inherited from PETE_Expr< IndexedBareField< T, Dim, Brackets > >
typedef IndexedBareField< T, Dim, Brackets > Wrapped
Detailed Description
template<class T, unsigned Dim, unsigned Brackets, class M, class C>
class IndexedField< T, Dim, Brackets, M, C >
Definition at line 22 of file Field.h.
Constructor & Destructor Documentation
IndexedField() [1/4]
template<class T, unsigned Dim, unsigned Brackets, class M, class C> IndexedField< T, Dim, Brackets, M, C >::IndexedField (Field< T, Dim, M, C > & f, const Index & idx) inline protected
Definition at line 98 of file IndexedField.h.
IndexedField() [2/4]
template<class T, unsigned Dim, unsigned Brackets, class M, class C> IndexedField< T, Dim, Brackets, M, C >::IndexedField (Field< T, Dim, M, C > & f, int i) inline protected
Definition at line 100 of file IndexedField.h.
IndexedField() [3/4]
template<class T, unsigned Dim, unsigned Brackets, class M, class C> IndexedField< T, Dim, Brackets, M, C >::IndexedField (Field< T, Dim, M, C > & f, const NDIndex< Brackets-1 > & idx, const Index & i) inline protected
Definition at line 102 of file IndexedField.h.
IndexedField() [4/4]
template<class T, unsigned Dim, unsigned Brackets, class M, class C> IndexedField< T, Dim, Brackets, M, C >::IndexedField (Field< T, Dim, M, C > & f, const NDIndex< Dim > & ndidx) inline protected
Definition at line 105 of file IndexedField.h.
Member Function Documentation
getField() [1/2]
template<class T, unsigned Dim, unsigned Brackets, class M, class C> Field<T,Dim,M,C>& IndexedField< T, Dim, Brackets, M, C >::getField () inline
Definition at line 89 of file IndexedField.h.
References IndexedField< T, Dim, Brackets, M, C >::F.
getField() [2/2]
template<class T, unsigned Dim, unsigned Brackets, class M, class C> const Field<T,Dim,M,C>& IndexedField< T, Dim, Brackets, M, C >::getField () const inline
Definition at line 90 of file IndexedField.h.
References IndexedField< T, Dim, Brackets, M, C >::F.
operator=() [1/5]
template<class T, unsigned Dim, unsigned Brackets, class M, class C> void IndexedField< T, Dim, Brackets, M, C >::operator= (T x) inline
Definition at line 51 of file IndexedField.h.
References assign().
operator=() [2/5]
template<class T, unsigned Dim, unsigned Brackets, class M, class C> IndexedField<T,Dim,Brackets,M,C>& IndexedField< T, Dim, Brackets, M, C >::operator= (const IndexedField< T, Dim, Brackets, M, C > & x) inline
Definition at line 57 of file IndexedField.h.
References assign(), CTAssert, and Dim.
operator=() [3/5]
template<class T, unsigned Dim, unsigned Brackets, class M, class C> IndexedField<T,Dim,Brackets,M,C>& IndexedField< T, Dim, Brackets, M, C >::operator= (const Index & x) inline
Definition at line 65 of file IndexedField.h.
References assign().
operator=() [4/5]
template<class T, unsigned Dim, unsigned Brackets, class M, class C> template<class T1 , unsigned Dim1, unsigned Brackets1, class M1 , class C1 > IndexedField<T,Dim,Brackets,M,C>& IndexedField< T, Dim, Brackets, M, C >::operator= (const IndexedField< T1, Dim1, Brackets1, M1, C1 > & x) inline
Definition at line 73 of file IndexedField.h.
References assign(), and CTAssert.
operator=() [5/5]
template<class T, unsigned Dim, unsigned Brackets, class M, class C> template<class B > IndexedField<T,Dim,Brackets,M,C>& IndexedField< T, Dim, Brackets, M, C >::operator= (const PETE_Expr< B > & x) inline
Definition at line 82 of file IndexedField.h.
References assign().
operator[]() [1/3]
template<class T, unsigned Dim, unsigned Brackets, class M, class C> IndexedField<T,Dim,Brackets+1,M,C> IndexedField< T, Dim, Brackets, M, C >::operator[] (const Index & idx) inline
Definition at line 34 of file IndexedField.h.
References CTAssert, Dim, and IndexedField< T, Dim, Brackets, M, C >::F.
operator[]() [2/3]
template<class T, unsigned Dim, unsigned Brackets, class M, class C> IndexedField<T,Dim,Brackets+1,M,C> IndexedField< T, Dim, Brackets, M, C >::operator[] (int i) inline
Definition at line 39 of file IndexedField.h.
References CTAssert, Dim, and IndexedField< T, Dim, Brackets, M, C >::F.
operator[]() [3/3]
template<class T, unsigned Dim, unsigned Brackets, class M, class C> IndexedField<T,Dim,Dim,M,C> IndexedField< T, Dim, Brackets, M, C >::operator[] (const NDIndex< Dim > & ndidx) inline
Definition at line 45 of file IndexedField.h.
References CTAssert, Dim, and IndexedField< T, Dim, Brackets, M, C >::F.
Friends And Related Function Documentation
Field< T, Dim, M, C >
template<class T, unsigned Dim, unsigned Brackets, class M, class C> friend class Field< T, Dim, M, C > friend
Definition at line 30 of file IndexedField.h.
IndexedField< T, Dim, Brackets-1, M, C >
template<class T, unsigned Dim, unsigned Brackets, class M, class C> friend class IndexedField< T, Dim, Brackets-1, M, C > friend
Definition at line 29 of file IndexedField.h.
Member Data Documentation
F
template<class T, unsigned Dim, unsigned Brackets, class M, class C> Field<T,Dim,M,C>& IndexedField< T, Dim, Brackets, M, C >::F protected
Definition at line 94 of file IndexedField.h.
Referenced by IndexedField< T, Dim, Brackets, M, C >::getField(), and IndexedField< T, Dim, Brackets, M, C >::operator[]().
The documentation for this class was generated from the following files:
ippl/src/Field/Field.h
ippl/src/Field/IndexedField.h