OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Algorithms/BoostMatrix.h File Reference
BoostMatrix.h File Reference
#include <boost/numeric/ublas/matrix.hpp>
Typedefs
typedef boost::numeric::ublas::matrix< double > matrix_t
Functions
template<class T >
T prod_boost_vector (const boost::numeric::ublas::matrix< double > &rotation, const T &vector)
Typedef Documentation
matrix_t
typedef boost::numeric::ublas::matrix<double> matrix_t
Definition at line 23 of file BoostMatrix.h.
Function Documentation
prod_boost_vector()
template<class T > T prod_boost_vector (const boost::numeric::ublas::matrix< double > & rotation, const T & vector)
Definition at line 26 of file BoostMatrix.h.
References Attrib::Legacy::Distribution::T.
Referenced by ParallelCyclotronTracker::globalToLocal(), ParallelCyclotronTracker::localToGlobal(), ParallelCyclotronTracker::rotateAroundX(), ParallelCyclotronTracker::rotateAroundZ(), CoordinateSystemTrafo::rotateFrom(), CoordinateSystemTrafo::rotateTo(), and CoordinateSystemTrafo::transformTo().