OPAL (Object Oriented Parallel Accelerator Library): mslang::Shear Struct Reference
mslang::Shear Struct Reference
#include <Shear.h>
Public Member Functions
virtual ~Shear ()
virtual void print (int indentwidth)
void applyShear (std::vector< std::shared_ptr< Base > > &bfuncs)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Public Member Functions inherited from mslang::Function
virtual ~Function ()
virtual void apply (std::vector< std::shared_ptr< Base >> &bfuncs)=0
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
Static Public Member Functions inherited from mslang::Function
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
Function * func_m
double angleX_m
double angleY_m
Additional Inherited Members
Static Public Attributes inherited from mslang::Function
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\((.*)"
Detailed Description
Definition at line 7 of file Shear.h.
Constructor & Destructor Documentation
~Shear()
virtual mslang::Shear::~Shear () inline virtual
Definition at line 12 of file Shear.h.
References func_m.
Member Function Documentation
apply()
void mslang::Shear::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Definition at line 37 of file Shear.cpp.
References mslang::Function::apply(), applyShear(), and func_m.
applyShear()
void mslang::Shear::applyShear (std::vector< std::shared_ptr< Base > > & bfuncs)
Definition at line 22 of file Shear.cpp.
References angleX_m, angleY_m, and tan().
Referenced by apply().
parse_detail()
bool mslang::Shear::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 42 of file Shear.cpp.
References angleX_m, angleY_m, Physics::e, end(), endl(), func_m, mslang::ArgumentExtractor::get(), mslang::ArgumentExtractor::getLengthConsumed(), mslang::Function::parse(), and mslang::parseMathExpression().
Referenced by mslang::Function::parse().
print()
void mslang::Shear::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 8 of file Shear.cpp.
References abs(), angleX_m, angleY_m, endl(), func_m, and mslang::Function::print().
Member Data Documentation
angleX_m
double mslang::Shear::angleX_m
Definition at line 9 of file Shear.h.
Referenced by applyShear(), parse_detail(), and print().
angleY_m
double mslang::Shear::angleY_m
Definition at line 10 of file Shear.h.
Referenced by applyShear(), parse_detail(), and print().
func_m
Function* mslang::Shear::func_m
Definition at line 8 of file Shear.h.
Referenced by apply(), parse_detail(), print(), and ~Shear().
The documentation for this struct was generated from the following files:
src/Classic/Utilities/MSLang/Shear.h
src/Classic/Utilities/MSLang/Shear.cpp