OPAL (Object Oriented Parallel Accelerator Library): ParticleLayout< T, Dim > Class Template Reference
ParticleLayout< T, Dim > Class Template Reference
#include <ParticleLayout.h>
Public Types
enum { Dimension = Dim }
enum UpdateFlags {
SWAP, BCONDS, NUMFLAGS, OPTDESTROY,
ALL
}
typedef T Position_t
typedef unsigned Index_t
typedef Vektor< T, Dim > SingleParticlePos_t
Public Member Functions
ParticleLayout ()
~ParticleLayout ()
void setUpdateFlag (UpdateFlags f, bool val)
bool getUpdateFlag (UpdateFlags f) const
ParticleBConds< T, Dim > & getBConds ()
void setBConds (const ParticleBConds< T, Dim > &bc)
Protected Member Functions
template<class PPT , class NDI >
void apply_bconds (unsigned n, PPT &R, const ParticleBConds< T, Dim > &bcs, const NDI &nr)
Private Attributes
ParticleBConds< T, Dim > BoundConds
unsigned int UpdateOptions
Detailed Description
template<class T, unsigned Dim>
class ParticleLayout< T, Dim >
Definition at line 54 of file ParticleLayout.h.
Member Typedef Documentation
Index_t
template<class T, unsigned Dim> typedef unsigned ParticleLayout< T, Dim >::Index_t
Definition at line 63 of file ParticleLayout.h.
Position_t
template<class T, unsigned Dim> typedef T ParticleLayout< T, Dim >::Position_t
Definition at line 62 of file ParticleLayout.h.
SingleParticlePos_t
template<class T, unsigned Dim> typedef Vektor<T,Dim> ParticleLayout< T, Dim >::SingleParticlePos_t
Definition at line 64 of file ParticleLayout.h.
Member Enumeration Documentation
anonymous enum
template<class T, unsigned Dim> anonymous enum
Enumerator
Dimension
Definition at line 58 of file ParticleLayout.h.
UpdateFlags
template<class T, unsigned Dim> enum ParticleLayout::UpdateFlags
Enumerator
SWAP
BCONDS
NUMFLAGS
OPTDESTROY
ALL
Definition at line 59 of file ParticleLayout.h.
Constructor & Destructor Documentation
ParticleLayout()
template<class T , unsigned Dim> ParticleLayout< T, Dim >::ParticleLayout ()
Definition at line 35 of file ParticleLayout.hpp.
~ParticleLayout()
template<class T, unsigned Dim> ParticleLayout< T, Dim >::~ParticleLayout () inline
Definition at line 73 of file ParticleLayout.h.
Member Function Documentation
apply_bconds()
template<class T, unsigned Dim> template<class PPT , class NDI > void ParticleLayout< T, Dim >::apply_bconds (unsigned n, PPT & R, const ParticleBConds< T, Dim > & bcs, const NDI & nr) inline protected
Definition at line 106 of file ParticleLayout.h.
References ParticleBConds< T, Dim >::apply(), Dim, Hypervolume::n, nr, and Attrib::Distribution::R.
getBConds()
template<class T, unsigned Dim> ParticleBConds<T,Dim>& ParticleLayout< T, Dim >::getBConds () inline
Definition at line 91 of file ParticleLayout.h.
References ParticleLayout< T, Dim >::BoundConds.
Referenced by IpplParticleBase< T >::getBConds(), and BoxParticleCachingPolicy< T, Dim, Mesh >::updateCacheInformation().
getUpdateFlag()
template<class T, unsigned Dim> bool ParticleLayout< T, Dim >::getUpdateFlag (UpdateFlags f) const inline
Definition at line 86 of file ParticleLayout.h.
References ParticleLayout< T, Dim >::ALL, and ParticleLayout< T, Dim >::UpdateOptions.
Referenced by IpplParticleBase< T >::getUpdateFlag(), and BoxParticleCachingPolicy< T, Dim, Mesh >::updateCacheInformation().
setBConds()
template<class T, unsigned Dim> void ParticleLayout< T, Dim >::setBConds (const ParticleBConds< T, Dim > & bc) inline
Definition at line 94 of file ParticleLayout.h.
References ParticleLayout< T, Dim >::BoundConds.
Referenced by IpplParticleBase< T >::setBConds().
setUpdateFlag()
template<class T, unsigned Dim> void ParticleLayout< T, Dim >::setUpdateFlag (UpdateFlags f, bool val) inline
Definition at line 76 of file ParticleLayout.h.
References ParticleLayout< T, Dim >::ALL, and ParticleLayout< T, Dim >::UpdateOptions.
Referenced by IpplParticleBase< T >::setUpdateFlag().
Member Data Documentation
BoundConds
template<class T, unsigned Dim> ParticleBConds<T,Dim> ParticleLayout< T, Dim >::BoundConds private
Definition at line 118 of file ParticleLayout.h.
Referenced by ParticleLayout< T, Dim >::getBConds(), and ParticleLayout< T, Dim >::setBConds().
UpdateOptions
template<class T, unsigned Dim> unsigned int ParticleLayout< T, Dim >::UpdateOptions private
Definition at line 121 of file ParticleLayout.h.
Referenced by ParticleLayout< T, Dim >::getUpdateFlag(), and ParticleLayout< T, Dim >::setUpdateFlag().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/ParticleLayout.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/ParticleLayout.hpp