OPAL (Object Oriented Parallel Accelerator Library): YCorrectorRep Class Reference
YCorrectorRep Class Reference
#include <YCorrectorRep.h>
Public Member Functions
YCorrectorRep (const std::string &name)
Constructor with given name.
YCorrectorRep ()
YCorrectorRep (const YCorrectorRep &)
virtual ~YCorrectorRep ()
virtual ElementBase * clone () const
Return clone.
virtual Channel * getChannel (const std::string &aKey, bool=false)
Construct a read/write channel.
virtual Plane getPlane () const
Get plane.
virtual double getBy () const
Get field.
virtual void setBy (double)
Set field.
Public Member Functions inherited from CorrectorRep
CorrectorRep (const std::string &name)
Constructor with given name.
CorrectorRep ()
CorrectorRep (const CorrectorRep &right)
virtual ~CorrectorRep ()
virtual StraightGeometry & getGeometry ()
Get geometry.
virtual const StraightGeometry & getGeometry () const
Get geometry.
virtual double getBx () const
Get horizontal field component in Teslas.
virtual BDipoleField & getField ()
Get corrector field.
virtual const BDipoleField & getField () const
Get corrector field. Version for const corrector.
virtual void setBx (double)
Set horizontal field component in Teslas.
virtual void setActive (bool flag=true)
Set active flag.
Public Member Functions inherited from Corrector
Corrector (const std::string &name)
Constructor with given name.
Corrector ()
Corrector (const Corrector &right)
virtual ~Corrector ()
virtual void accept (BeamlineVisitor &) const
Apply a visitor to Corrector.
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B)
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField)
virtual void goOnline (const double &kineticEnergy)
virtual void finalise ()
virtual bool bends () const
virtual ElementBase::ElementType getType () const
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const
void setKickX (double k)
void setKickY (double k)
virtual void setDesignEnergy (const double &ekin, bool changeable=true)
double getKickX () const
double getKickY () const
void setKickField (const Vector_t &k0)
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void goOffline ()
virtual bool Online ()
virtual void setComponentType (std::string)
virtual std::string getComponentType () const
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void operator= (const YCorrectorRep &)
Additional Inherited Members
Public Types inherited from Corrector
enum Plane { OFF, X, Y, XY }
Plane selection.
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from Corrector
void operator= (const Corrector &)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from CorrectorRep
StraightGeometry geometry
The corrector geometry.
BDipoleField field
The corrector strengths.
bool active
The active/inactive flag.
Protected Attributes inherited from Corrector
Plane plane_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 25 of file YCorrectorRep.h.
Constructor & Destructor Documentation
YCorrectorRep() [1/3]
YCorrectorRep::YCorrectorRep (const std::string & name) explicit
Constructor with given name.
Definition at line 55 of file YCorrectorRep.cpp.
YCorrectorRep() [2/3]
YCorrectorRep::YCorrectorRep ()
Definition at line 45 of file YCorrectorRep.cpp.
Referenced by clone().
YCorrectorRep() [3/3]
YCorrectorRep::YCorrectorRep (const YCorrectorRep & right)
Definition at line 50 of file YCorrectorRep.cpp.
~YCorrectorRep()
YCorrectorRep::~YCorrectorRep () virtual
Definition at line 60 of file YCorrectorRep.cpp.
Member Function Documentation
clone()
ElementBase * YCorrectorRep::clone () const virtual
Return clone.
Reimplemented from CorrectorRep.
Definition at line 64 of file YCorrectorRep.cpp.
References YCorrectorRep().
getBy()
double YCorrectorRep::getBy () const virtual
Get field.
Reimplemented from CorrectorRep.
Definition at line 85 of file YCorrectorRep.cpp.
getChannel()
Channel * YCorrectorRep::getChannel (const std::string & aKey, bool create = false) virtual
Construct a read/write channel.
Reimplemented from CorrectorRep.
Definition at line 69 of file YCorrectorRep.cpp.
References ElementBase::getChannel().
getPlane()
Corrector::Plane YCorrectorRep::getPlane () const virtual
Get plane.
Reimplemented from CorrectorRep.
Definition at line 80 of file YCorrectorRep.cpp.
References Corrector::Y.
operator=()
void YCorrectorRep::operator= (const YCorrectorRep &) private
setBy()
void YCorrectorRep::setBy (double) virtual
Set field.
Reimplemented from CorrectorRep.
Definition at line 90 of file YCorrectorRep.cpp.
The documentation for this class was generated from the following files:
src/Classic/BeamlineCore/YCorrectorRep.h
src/Classic/BeamlineCore/YCorrectorRep.cpp