OPAL (Object Oriented Parallel Accelerator Library): mslang::ArgumentExtractor Struct Reference
mslang::ArgumentExtractor Struct Reference
#include <ArgumentExtractor.h>
Public Member Functions
ArgumentExtractor (const std::string &input)
std::string get (unsigned int i) const
unsigned int getLengthConsumed () const
unsigned int getNumArguments () const
Public Attributes
std::vector< std::pair< unsigned int, unsigned int > > argumentBoundaries_m
std::string inputArguments_m
unsigned int lengthConsumed_m
Detailed Description
Definition at line 9 of file ArgumentExtractor.h.
Constructor & Destructor Documentation
ArgumentExtractor()
mslang::ArgumentExtractor::ArgumentExtractor (const std::string & input)
Definition at line 6 of file ArgumentExtractor.cpp.
References argumentBoundaries_m, inputArguments_m, and lengthConsumed_m.
Member Function Documentation
get()
std::string mslang::ArgumentExtractor::get (unsigned int i) const
Definition at line 36 of file ArgumentExtractor.cpp.
References argumentBoundaries_m, and inputArguments_m.
Referenced by mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Rotation::parse_detail(), mslang::Translation::parse_detail(), mslang::Shear::parse_detail(), mslang::Repeat::parse_detail(), mslang::Ellipse::parse_detail(), and mslang::Rectangle::parse_detail().
getLengthConsumed()
unsigned int mslang::ArgumentExtractor::getLengthConsumed () const
Definition at line 45 of file ArgumentExtractor.cpp.
References lengthConsumed_m.
Referenced by mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Rotation::parse_detail(), mslang::Translation::parse_detail(), mslang::Shear::parse_detail(), mslang::Repeat::parse_detail(), mslang::Ellipse::parse_detail(), and mslang::Rectangle::parse_detail().
getNumArguments()
unsigned int mslang::ArgumentExtractor::getNumArguments () const
Definition at line 49 of file ArgumentExtractor.cpp.
References argumentBoundaries_m.
Referenced by mslang::Polygon::parse_detail(), and mslang::Repeat::parse_detail().
Member Data Documentation
argumentBoundaries_m
std::vector<std::pair<unsigned int, unsigned int> > mslang::ArgumentExtractor::argumentBoundaries_m
Definition at line 16 of file ArgumentExtractor.h.
Referenced by ArgumentExtractor(), get(), and getNumArguments().
inputArguments_m
std::string mslang::ArgumentExtractor::inputArguments_m
Definition at line 17 of file ArgumentExtractor.h.
Referenced by ArgumentExtractor(), and get().
lengthConsumed_m
unsigned int mslang::ArgumentExtractor::lengthConsumed_m
Definition at line 18 of file ArgumentExtractor.h.
Referenced by ArgumentExtractor(), and getLengthConsumed().
The documentation for this struct was generated from the following files:
src/Classic/Utilities/MSLang/ArgumentExtractor.h
src/Classic/Utilities/MSLang/ArgumentExtractor.cpp