OPAL (Object Oriented Parallel Accelerator Library): DataConnect Class Reference
DataConnect Class Reference
#include <DataConnect.h>
Public Types
typedef std::vector< DataSource * > container_t
typedef container_t::iterator iterator
typedef container_t::const_iterator const_iterator
Public Member Functions
DataConnect (const char *nm, const char *id, int dtm=DataSource::OUTPUT, int n=0)
virtual ~DataConnect ()
const char * DSID () const
int getDefaultTransferMethod () const
void setDefaultTransferMethod (int m)
int getNodes () const
bool onConnectNode () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
unsigned int size () const
unsigned int numDataSources () const
bool empty () const
virtual bool connected () const
virtual DataConnect * connect (const char *, DataSource *, int=DataSource::DEFAULT)
virtual DataConnect * connect (const char *, DataSource &, int=DataSource::DEFAULT)
virtual bool connect (DataSourceObject *)
virtual void updateConnections (DataConnect *=0)
virtual void disconnectConnections ()
virtual void interact (const char *=0, DataConnect *=0)
virtual void ready ()
Public Member Functions inherited from NamedObj
NamedObj (const char *nm=0)
virtual ~NamedObj ()
const char * name () const
const char * setName (const char *nm=0)
Private Member Functions
bool checkin (DataSource *)
bool checkout (DataSource *, bool=true)
Private Attributes
std::string MyID
container_t SourceList
int nodes
int DefTransMethod
Friends
class DataSource
Detailed Description
Definition at line 32 of file DataConnect.h.
Member Typedef Documentation
const_iterator
typedef container_t::const_iterator DataConnect::const_iterator
Definition at line 38 of file DataConnect.h.
container_t
typedef std::vector<DataSource *> DataConnect::container_t
Definition at line 36 of file DataConnect.h.
iterator
typedef container_t::iterator DataConnect::iterator
Definition at line 37 of file DataConnect.h.
Constructor & Destructor Documentation
DataConnect()
DataConnect::DataConnect (const char * nm, const char * id, int dtm = DataSource::OUTPUT, int n = 0)
Definition at line 37 of file DataConnect.cpp.
References DataConnectCreator::getDefaultNodes(), Hypervolume::n, and nodes.
~DataConnect()
DataConnect::~DataConnect () virtual
Definition at line 47 of file DataConnect.cpp.
References disconnectConnections().
Member Function Documentation
begin() [1/2]
iterator DataConnect::begin () inline
Definition at line 71 of file DataConnect.h.
References SourceList.
Referenced by checkin(), checkout(), FileFieldDataSource< T, Dim, M, C >::FileFieldDataSource(), interact(), and updateConnections().
begin() [2/2]
const_iterator DataConnect::begin () const inline
Definition at line 74 of file DataConnect.h.
References SourceList.
checkin()
bool DataConnect::checkin (DataSource * ds) private
Definition at line 130 of file DataConnect.cpp.
References a, begin(), end(), and SourceList.
Referenced by DataSource::connect().
checkout()
bool DataConnect::checkout (DataSource * ds, bool NeedDisconnect = true) private
Definition at line 147 of file DataConnect.cpp.
References a, begin(), DataSource::disconnect(), end(), and SourceList.
Referenced by DataSource::disconnect(), and disconnectConnections().
connect() [1/3]
DataConnect * DataConnect::connect (const char * nm, DataSource * s, int tm = DataSource::DEFAULT) virtual
Definition at line 74 of file DataConnect.cpp.
References DataSource::connect(), and connected().
Referenced by connect().
connect() [2/3]
DataConnect * DataConnect::connect (const char * nm, DataSource & s, int tm = DataSource::DEFAULT) virtual
Definition at line 81 of file DataConnect.cpp.
References connect().
connect() [3/3]
bool DataConnect::connect (DataSourceObject * dso) virtual
Definition at line 90 of file DataConnect.cpp.
References DataSource::connect(), DataSourceObject::getConnection(), and DataSourceObject::getSource().
connected()
bool DataConnect::connected () const virtual
Reimplemented in FileDataConnect.
Definition at line 63 of file DataConnect.cpp.
Referenced by connect().
disconnectConnections()
void DataConnect::disconnectConnections () virtual
Definition at line 113 of file DataConnect.cpp.
References checkout(), and SourceList.
Referenced by ~DataConnect().
DSID()
const char* DataConnect::DSID () const inline
Definition at line 55 of file DataConnect.h.
References MyID.
Referenced by FileFieldDataSource< T, Dim, M, C >::FileFieldDataSource(), FileIpplParticleBaseDataSource< T >::FileIpplParticleBaseDataSource(), FileParticleAttribDataSource< T >::FileParticleAttribDataSource(), and make_DataSourceObject().
empty()
bool DataConnect::empty () const inline
Definition at line 84 of file DataConnect.h.
References SourceList.
end() [1/2]
iterator DataConnect::end () inline
Definition at line 72 of file DataConnect.h.
References SourceList.
Referenced by checkin(), checkout(), interact(), and updateConnections().
end() [2/2]
const_iterator DataConnect::end () const inline
Definition at line 75 of file DataConnect.h.
References SourceList.
getDefaultTransferMethod()
int DataConnect::getDefaultTransferMethod () const inline
Definition at line 58 of file DataConnect.h.
References DefTransMethod.
Referenced by DataSource::connect().
getNodes()
int DataConnect::getNodes () const inline
Definition at line 62 of file DataConnect.h.
References nodes.
Referenced by onConnectNode().
interact()
void DataConnect::interact (const char * str = 0, DataConnect * dc = 0) virtual
Definition at line 122 of file DataConnect.cpp.
References a, begin(), and end().
numDataSources()
unsigned int DataConnect::numDataSources () const inline
Definition at line 83 of file DataConnect.h.
References SourceList.
onConnectNode()
bool DataConnect::onConnectNode () const
Definition at line 55 of file DataConnect.cpp.
References getNodes(), and IpplInfo::myNode().
ready()
void DataConnect::ready () virtual
Definition at line 177 of file DataConnect.cpp.
setDefaultTransferMethod()
void DataConnect::setDefaultTransferMethod (int m) inline
Definition at line 59 of file DataConnect.h.
References DefTransMethod.
size()
unsigned int DataConnect::size (void) const inline
Definition at line 82 of file DataConnect.h.
References SourceList.
Referenced by FileFieldDataSource< T, Dim, M, C >::FileFieldDataSource().
updateConnections()
void DataConnect::updateConnections (DataConnect * dc = 0) virtual
Definition at line 105 of file DataConnect.cpp.
References a, begin(), and end().
Friends And Related Function Documentation
DataSource
friend class DataSource friend
Definition at line 126 of file DataConnect.h.
Member Data Documentation
DefTransMethod
int DataConnect::DefTransMethod private
Definition at line 138 of file DataConnect.h.
Referenced by getDefaultTransferMethod(), and setDefaultTransferMethod().
MyID
std::string DataConnect::MyID private
Definition at line 129 of file DataConnect.h.
Referenced by DSID().
nodes
int DataConnect::nodes private
Definition at line 135 of file DataConnect.h.
Referenced by DataConnect(), and getNodes().
SourceList
container_t DataConnect::SourceList private
Definition at line 132 of file DataConnect.h.
Referenced by begin(), checkin(), checkout(), disconnectConnections(), empty(), end(), numDataSources(), and size().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/DataConnect.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/DataConnect.cpp