OPAL (Object Oriented Parallel Accelerator Library): src/Classic/Algorithms/PartBunchBase.h File Reference
PartBunchBase.h File Reference
#include "Particle/AbstractParticle.h"
#include "Particle/ParticleAttrib.h"
#include "Utility/IpplTimings.h"
#include "Utilities/GeneralClassicException.h"
#include "Algorithms/DistributionMoments.h"
#include "Algorithms/CoordinateSystemTrafo.h"
#include "Algorithms/OpalParticle.h"
#include "Algorithms/PBunchDefs.h"
#include "Algorithms/Quaternion.h"
#include "Algorithms/Vektor.h"
#include "FixedAlgebra/FMatrix.h"
#include "FixedAlgebra/FVector.h"
#include <memory>
#include <utility>
#include <vector>
#include "PartBunchBase.hpp"
Classes
class PartBunchBase< T, Dim >
class PartBunchBase< T, Dim >::ConstIterator
Enumerations
enum ParticleOrigin : short { ParticleOrigin::REGULAR, ParticleOrigin::SECONDARY, ParticleOrigin::STRIPPED }
enum ParticleType : short {
ParticleType::ELECTRON, ParticleType::PROTON, ParticleType::POSITRON, ParticleType::ANTIPROTON,
ParticleType::CARBON, ParticleType::HMINUS, ParticleType::URANIUM, ParticleType::MUON,
ParticleType::DEUTERON, ParticleType::XENON, ParticleType::H2P, ParticleType::ALPHA,
ParticleType::HYDROGEN, ParticleType::H3P, ParticleType::UNNAMED
}
Functions
template<class T , unsigned Dim>
PartBunchBase< T, Dim >::ConstIterator begin (PartBunchBase< T, Dim > const &bunch)
template<class T , unsigned Dim>
PartBunchBase< T, Dim >::ConstIterator end (PartBunchBase< T, Dim > const &bunch)
Enumeration Type Documentation
ParticleOrigin
enum ParticleOrigin : short strong
Enumerator
REGULAR
SECONDARY
STRIPPED
Definition at line 46 of file PartBunchBase.h.
ParticleType
enum ParticleType : short strong
Enumerator
ELECTRON
PROTON
POSITRON
ANTIPROTON
CARBON
HMINUS
URANIUM
MUON
DEUTERON
XENON
H2P
ALPHA
HYDROGEN
H3P
UNNAMED
Definition at line 50 of file PartBunchBase.h.
Function Documentation
begin()
template<class T , unsigned Dim> PartBunchBase<T, Dim>::ConstIterator begin (PartBunchBase< T, Dim > const & bunch)
Definition at line 730 of file PartBunchBase.h.
References PartBunchBase< T, Dim >::begin().
Referenced by SIndex< Dim >::addIndex(), BConds< Vektor, 3, UniformCartesian, Cell >::apply(), AmrMultiGrid::buildFineBoundaryMatrix_m(), LField< T, Dim >::CanCompressBasedOnPhysicalCells(), BConds< Vektor, 3, UniformCartesian, Cell >::changesPhysicalCells(), Taylor< T >::clear(), TBeamline< T >::clone(), FArray2D< T, R, C >::col_begin(), endfieldmodel::CompactVector(), LField< T, Dim >::Compress(), LField< T, Dim >::CompressBasedOnPhysicalCells(), TBeamline< T >::copyStructure(), AmrLagrangeInterpolater< Level >::crseLinear_m(), AmrLagrangeInterpolater< Level >::crseQuadratic_m(), FTps< double, 2 *3 >::derivative(), FTps< double, 2 *3 >::divide(), vmap< std::string, DiscConfig::SMPData *>::equal_range(), FTps< double, 2 *3 >::evaluate(), TrackRun::execute(), FArray1D< int, N+1 >::FArray1D(), FArray2D< T, R, C >::FArray2D(), FTps< double, 2 *3 >::filter(), ParticleInteractLayout< T, Dim, Mesh >::find_pairs(), TBeamline< T >::getArcLength(), RFCavity::getAutoPhaseEstimate(), Solenoid::getElementDimensions(), TravelingWave::getElementDimensions(), ElementBase::getElementDimensions(), RFCavity::getElementDimensions(), TBeamline< T >::getElementLength(), Interpolator::getFieldIter(), SampleIndividual::getIndex(), TBeamline< T >::getTotalTransform(), TBeamline< T >::getTransform(), vmap< std::string, DiscConfig::SMPData *>::insert(), FTps< double, 2 *3 >::integral(), Taylor< T >::integrate(), TBeamline< T >::iterate(), vmap< std::string, DiscConfig::SMPData *>::lower_bound(), TBeamline< T >::makeSharable(), ProbeHistReader::minimum(), FTps< double, 2 *3 >::multiply(), FTps< double, 2 *3 >::multiplyVariable(), FVector< std::complex< double >, N >::operator*=(), Vector< T >::operator*=(), Matrix< T >::operator*=(), FMatrix< double, N, N >::operator*=(), Taylor< T >::operator*=(), FTps< double, 2 *3 >::operator*=(), FVector< std::complex< double >, N >::operator+=(), Vector< T >::operator+=(), Matrix< T >::operator+=(), FMatrix< double, N, N >::operator+=(), Taylor< T >::operator+=(), FVector< std::complex< double >, N >::operator-(), Vector< T >::operator-(), Taylor< T >::operator-(), FTps< double, 2 *3 >::operator-(), FVector< std::complex< double >, N >::operator-=(), Vector< T >::operator-=(), Matrix< T >::operator-=(), FMatrix< double, N, N >::operator-=(), Taylor< T >::operator-=(), FVector< std::complex< double >, N >::operator/=(), Vector< T >::operator/=(), Matrix< T >::operator/=(), FMatrix< double, N, N >::operator/=(), Taylor< T >::operator/=(), Array1D< Tps< T > >::operator=(), FArray1D< int, N+1 >::operator=(), FArray2D< T, R, C >::operator=(), Array2D< int >::operator=(), FTps< double, 2 *3 >::operator==(), vmap< std::string, DiscConfig::SMPData *>::operator[](), Timing::print(), Cartesian< Dim, MFLOAT >::print(), OrbitThreader::processElementRegister(), FTps< double, 2 *3 >::put(), DiscField< Dim >::read_meta(), SIndex< Dim >::removeIndex(), DistributionMoments::reset(), Array1D< Tps< T > >::resize(), FTps< double, 2 *3 >::scaleMonomials(), SectorField::setPolarBoundingBox(), ParticleSpatialLayout< T, Dim, Mesh >::short_swap_particles(), interpolation::PPSolveFactory::solve(), AmrParticleBase< PLayout >::sort(), FVps< T, N >::substitute(), FTps< double, 2 *3 >::substitute(), Taylor< T >::sum(), ParticleSpatialLayout< T, Dim, Mesh >::swap_particles(), Beam::update(), ElementBase::update(), vmap< std::string, DiscConfig::SMPData *>::upper_bound(), BConds< Vektor, 3, UniformCartesian, Cell >::write(), and LField< T, Dim >::write().
end()
template<class T , unsigned Dim> PartBunchBase<T, Dim>::ConstIterator end (PartBunchBase< T, Dim > const & bunch)
Definition at line 735 of file PartBunchBase.h.
References PartBunchBase< T, Dim >::end().
Referenced by OpalBeamline::activateElements(), MeshGenerator::add(), SIndex< Dim >::addIndex(), BConds< Vektor, 3, UniformCartesian, Cell >::apply(), OrbitThreader::autophaseCavities(), AmrMultiGrid::buildFineBoundaryMatrix_m(), BConds< Vektor, 3, UniformCartesian, Cell >::changesPhysicalCells(), Fieldmap::checkMap(), Taylor< T >::clear(), TBeamline< T >::clone(), FArray2D< T, R, C >::col_end(), endfieldmodel::CompactVector(), LField< T, Dim >::Compress(), OpalBeamline::compute3DLattice(), OrbitThreader::computeBoundingBox(), ParallelTTracker::computeExternalFields(), ParallelTTracker::computeWakefield(), OrbitThreader::containsCavity(), TBeamline< T >::copyStructure(), Distribution::createOpalT(), AmrLagrangeInterpolater< Level >::crseLinear_m(), AmrLagrangeInterpolater< Level >::crseQuadratic_m(), FTps< double, 2 *3 >::divide(), vmap< std::string, DiscConfig::SMPData *>::equal_range(), Expression::evaluate(), OrbitThreader::execute(), FArray1D< int, N+1 >::FArray1D(), FArray2D< T, R, C >::FArray2D(), FTps< double, 2 *3 >::filter(), vmap< std::string, DiscConfig::SMPData *>::find(), ParticleInteractLayout< T, Dim, Mesh >::find_pairs(), FromFile::FromFile(), TBeamline< T >::getArcLength(), CmdArguments::getArguments(), RFCavity::getAutoPhaseEstimate(), Solenoid::getElementDimensions(), TravelingWave::getElementDimensions(), ElementBase::getElementDimensions(), RFCavity::getElementDimensions(), TBeamline< T >::getElementLength(), RFCavity::getElementLength(), OpalBeamline::getElements(), OpalBeamline::getFieldAt(), SampleIndividual::getIndex(), OrbitThreader::getMaxDesignEnergy(), Attributes::getString(), Attributes::getStringArray(), TBeamline< T >::getTotalTransform(), IndexMap::getTouchingElements(), TBeamline< T >::getTransform(), interpolation::PPSolveFactory::getValues(), vmap< std::string, DiscConfig::SMPData *>::insert(), Taylor< T >::integrate(), OrbitThreader::integrate(), TBeamline< T >::iterate(), vmap< std::string, DiscConfig::SMPData *>::lower_bound(), TBeamline< T >::makeSharable(), ProbeHistReader::minimum(), OpalElement::OpalElement(), FVector< std::complex< double >, N >::operator*=(), Vector< T >::operator*=(), Matrix< T >::operator*=(), FMatrix< double, N, N >::operator*=(), Taylor< T >::operator*=(), FTps< double, 2 *3 >::operator*=(), FVector< std::complex< double >, N >::operator+=(), Vector< T >::operator+=(), Matrix< T >::operator+=(), FMatrix< double, N, N >::operator+=(), Taylor< T >::operator+=(), FVector< std::complex< double >, N >::operator-(), Vector< T >::operator-(), Taylor< T >::operator-(), FTps< double, 2 *3 >::operator-(), FVector< std::complex< double >, N >::operator-=(), Vector< T >::operator-=(), Matrix< T >::operator-=(), FMatrix< double, N, N >::operator-=(), Taylor< T >::operator-=(), FVector< std::complex< double >, N >::operator/=(), Vector< T >::operator/=(), Matrix< T >::operator/=(), FMatrix< double, N, N >::operator/=(), Taylor< T >::operator/=(), vmap< std::string, DiscConfig::SMPData *>::operator[](), interpolation::PPSolveFactory::outOfBoundsPosition(), mslang::Function::parse(), mslang::parse(), Expression::parse(), mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Rotation::parse_detail(), mslang::Union::parse_detail(), mslang::Translation::parse_detail(), mslang::Shear::parse_detail(), mslang::Repeat::parse_detail(), mslang::SymmetricDifference::parse_detail(), mslang::Intersection::parse_detail(), mslang::Difference::parse_detail(), mslang::Ellipse::parse_detail(), mslang::Rectangle::parse_detail(), interpolation::PolynomialPatch::PolynomialPatch(), Timing::print(), OrbitThreader::processElementRegister(), PutSingleItem< T, false, false >::put(), PutSingleItem< T, true, true >::put(), FTps< double, 2 *3 >::put(), Message::put(), putMessage(), IndexMap::query(), DiscField< Dim >::read_meta(), SDDS::SDDSParser::readFile(), OrbitThreader::registerElement(), OpalElement::registerOwnership(), Object::registerOwnership(), SIndex< Dim >::removeIndex(), DistributionMoments::reset(), ParallelTTracker::restoreCavityPhases(), Util::rewindLinesSDDS(), OpalBeamline::save3DInput(), OpalBeamline::save3DLattice(), IndexMap::saveSDDS(), FTps< double, 2 *3 >::scaleMonomials(), OrbitThreader::setDesignEnergy(), VariableRFCavityFringeField::setEndField(), SectorField::setPolarBoundingBox(), ParticleSpatialLayout< T, Dim, Mesh >::short_swap_particles(), interpolation::PPSolveFactory::solve(), AmrParticleBase< PLayout >::sort(), H5PartWrapper::storeCavityInformation(), FVps< T, N >::substitute(), FTps< double, 2 *3 >::substitute(), Taylor< T >::sum(), ParticleSpatialLayout< T, Dim, Mesh >::swap_particles(), OpalVariableRFCavityFringeField::update(), Beam::update(), ParallelTTracker::updateReferenceParticle(), vmap< std::string, DiscConfig::SMPData *>::upper_bound(), MeshGenerator::write(), BConds< Vektor, 3, UniformCartesian, Cell >::write(), and LField< T, Dim >::write().