OPAL (Object Oriented Parallel Accelerator Library): PRegion< T > Class Template Reference
PRegion< T > Class Template Reference
#include <PRegion.h>
Public Member Functions
PRegion ()
PRegion (T B)
PRegion (T A, T B)
~PRegion ()
T min () const
T max () const
T length () const
T first () const
T last () const
bool empty () const
PRegion< T > & operator+= (T t)
PRegion< T > & operator-= (T t)
PRegion< T > & operator*= (T t)
PRegion< T > & operator/= (T t)
PRegion< T > intersect (const PRegion< T > &r) const
bool touches (const PRegion< T > &r) const
bool contains (const PRegion< T > &r) const
bool split (PRegion< T > &l, PRegion< T > &r) const
bool operator< (const PRegion< T > &r) const
bool operator== (const PRegion< T > &r) const
Message & putMessage (Message &m)
Message & getMessage (Message &m)
Private Attributes
T First
T Last
Detailed Description
template<class T>
class PRegion< T >
Definition at line 39 of file PRegion.h.
Constructor & Destructor Documentation
PRegion() [1/3]
template<class T> PRegion< T >::PRegion () inline
Definition at line 68 of file PRegion.h.
PRegion() [2/3]
template<class T> PRegion< T >::PRegion (T B) inline
Definition at line 69 of file PRegion.h.
PRegion() [3/3]
template<class T> PRegion< T >::PRegion (T A, T B) inline
Definition at line 70 of file PRegion.h.
~PRegion()
template<class T> PRegion< T >::~PRegion () inline
Definition at line 73 of file PRegion.h.
Member Function Documentation
contains()
template<class T> bool PRegion< T >::contains (const PRegion< T > & r) const inline
Definition at line 169 of file PRegion.h.
References PRegion< T >::max(), and PRegion< T >::min().
empty()
template<class T> bool PRegion< T >::empty () const inline
Definition at line 81 of file PRegion.h.
References PRegion< T >::First, and PRegion< T >::Last.
first()
template<class T> T PRegion< T >::first () const inline
Definition at line 79 of file PRegion.h.
References PRegion< T >::First.
Referenced by operator*(), operator+(), operator-(), and operator/().
getMessage()
template<class T> Message& PRegion< T >::getMessage (Message & m) inline
Definition at line 206 of file PRegion.h.
References Message::get_iter(), and Attrib::Legacy::Distribution::T.
intersect()
template<class T> PRegion<T> PRegion< T >::intersect (const PRegion< T > & r) const inline
Definition at line 110 of file PRegion.h.
References PRegion< T >::max(), PRegion< T >::min(), and Attrib::Legacy::Distribution::T.
last()
template<class T> T PRegion< T >::last () const inline
Definition at line 80 of file PRegion.h.
References PRegion< T >::Last.
Referenced by operator*(), operator+(), operator-(), and operator/().
length()
template<class T> T PRegion< T >::length () const inline
Definition at line 78 of file PRegion.h.
References PRegion< T >::max(), and PRegion< T >::min().
Referenced by PRegion< T >::operator<().
max()
template<class T> T PRegion< T >::max () const inline
Definition at line 77 of file PRegion.h.
References PRegion< T >::First, and PRegion< T >::Last.
Referenced by PRegion< T >::contains(), PRegion< T >::intersect(), PRegion< T >::length(), and PRegion< T >::touches().
min()
template<class T> T PRegion< T >::min () const inline
Definition at line 76 of file PRegion.h.
References PRegion< T >::First, and PRegion< T >::Last.
Referenced by PRegion< T >::contains(), PRegion< T >::intersect(), PRegion< T >::length(), PRegion< T >::operator<(), operator<<(), and PRegion< T >::touches().
operator*=()
template<class T> PRegion<T>& PRegion< T >::operator*= (T t) inline
Definition at line 94 of file PRegion.h.
References PRegion< T >::First, and PRegion< T >::Last.
operator+=()
template<class T> PRegion<T>& PRegion< T >::operator+= (T t) inline
Definition at line 84 of file PRegion.h.
References PRegion< T >::First, and PRegion< T >::Last.
operator-=()
template<class T> PRegion<T>& PRegion< T >::operator-= (T t) inline
Definition at line 89 of file PRegion.h.
References PRegion< T >::First, and PRegion< T >::Last.
operator/=()
template<class T> PRegion<T>& PRegion< T >::operator/= (T t) inline
Definition at line 99 of file PRegion.h.
References PRegion< T >::First, and PRegion< T >::Last.
operator<()
template<class T> bool PRegion< T >::operator< (const PRegion< T > & r) const inline
Definition at line 182 of file PRegion.h.
References PRegion< T >::length(), PRegion< T >::min(), and Attrib::Legacy::Distribution::T.
operator==()
template<class T> bool PRegion< T >::operator== (const PRegion< T > & r) const inline
Definition at line 192 of file PRegion.h.
References PRegion< T >::First, and PRegion< T >::Last.
putMessage()
template<class T> Message& PRegion< T >::putMessage (Message & m) inline
Definition at line 197 of file PRegion.h.
References PRegion< T >::First, PRegion< T >::Last, Message::put(), and Attrib::Legacy::Distribution::T.
split()
template<class T> bool PRegion< T >::split (PRegion< T > & l, PRegion< T > & r) const inline
Definition at line 174 of file PRegion.h.
References PRegion< T >::First, PRegion< T >::Last, and Attrib::Legacy::Distribution::T.
touches()
template<class T> bool PRegion< T >::touches (const PRegion< T > & r) const inline
Definition at line 143 of file PRegion.h.
References PRegion< T >::max(), PRegion< T >::min(), and Attrib::Legacy::Distribution::T.
Member Data Documentation
First
template<class T> T PRegion< T >::First private
Definition at line 215 of file PRegion.h.
Referenced by PRegion< T >::empty(), PRegion< T >::first(), PRegion< T >::max(), PRegion< T >::min(), PRegion< T >::operator*=(), PRegion< T >::operator+=(), PRegion< T >::operator-=(), PRegion< T >::operator/=(), PRegion< T >::operator==(), PRegion< T >::putMessage(), and PRegion< T >::split().
Last
template<class T> T PRegion< T >::Last private
Definition at line 215 of file PRegion.h.
Referenced by PRegion< T >::empty(), PRegion< T >::last(), PRegion< T >::max(), PRegion< T >::min(), PRegion< T >::operator*=(), PRegion< T >::operator+=(), PRegion< T >::operator-=(), PRegion< T >::operator/=(), PRegion< T >::operator==(), PRegion< T >::putMessage(), and PRegion< T >::split().
The documentation for this class was generated from the following file:
ippl/src/Region/PRegion.h