OPAL (Object Oriented Parallel Accelerator Library): mslang::BoundingBox Struct Reference
mslang::BoundingBox Struct Reference
#include <BoundingBox.h>
Public Member Functions
BoundingBox ()
BoundingBox (const BoundingBox &right)
BoundingBox (const Vector_t &llc, const Vector_t &urc)
BoundingBox & operator= (const BoundingBox &)=default
bool doesIntersect (const BoundingBox &bb) const
bool isInside (const Vector_t &X) const
bool isInside (const BoundingBox &b) const
virtual void writeGnuplot (std::ostream &out) const
void print (std::ostream &out) const
Public Attributes
Vector_t center_m
double width_m
double height_m
Detailed Description
Definition at line 10 of file BoundingBox.h.
Constructor & Destructor Documentation
BoundingBox() [1/3]
mslang::BoundingBox::BoundingBox () inline
Definition at line 15 of file BoundingBox.h.
BoundingBox() [2/3]
mslang::BoundingBox::BoundingBox (const BoundingBox & right) inline
Definition at line 21 of file BoundingBox.h.
BoundingBox() [3/3]
mslang::BoundingBox::BoundingBox (const Vector_t & llc, const Vector_t & urc) inline
Definition at line 27 of file BoundingBox.h.
Member Function Documentation
doesIntersect()
bool mslang::BoundingBox::doesIntersect (const BoundingBox & bb) const
Definition at line 4 of file BoundingBox.cpp.
References center_m, height_m, and width_m.
Referenced by mslang::Base::divideBy(), and Mesher::isPotentialEdgeIntersected().
isInside() [1/2]
bool mslang::BoundingBox::isInside (const Vector_t & X) const
Definition at line 11 of file BoundingBox.cpp.
References abs(), center_m, height_m, width_m, and X.
Referenced by mslang::Rectangle::isInside(), mslang::Ellipse::isInside(), isInside(), FlexibleCollimator::isStopped(), and mslang::QuadTree::transferIfInside().
isInside() [2/2]
bool mslang::BoundingBox::isInside (const BoundingBox & b) const
Definition at line 19 of file BoundingBox.cpp.
References center_m, height_m, isInside(), and width_m.
operator=()
BoundingBox& mslang::BoundingBox::operator= (const BoundingBox &) default
print()
void mslang::BoundingBox::print (std::ostream & out) const
Definition at line 42 of file BoundingBox.cpp.
References center_m, endl(), height_m, and width_m.
Referenced by mslang::operator<<().
writeGnuplot()
void mslang::BoundingBox::writeGnuplot (std::ostream & out) const virtual
Definition at line 26 of file BoundingBox.cpp.
References center_m, endl(), height_m, and width_m.
Referenced by mslang::QuadTree::writeGnuplot().
Member Data Documentation
center_m
Vector_t mslang::BoundingBox::center_m
Definition at line 11 of file BoundingBox.h.
Referenced by mslang::QuadTree::buildUp(), doesIntersect(), isInside(), mslang::QuadTree::isInside(), Mesher::isPotentialEdgeIntersected(), print(), FlexibleCollimator::setDescription(), and writeGnuplot().
height_m
double mslang::BoundingBox::height_m
Definition at line 13 of file BoundingBox.h.
Referenced by mslang::QuadTree::buildUp(), doesIntersect(), isInside(), Mesher::isPotentialEdgeIntersected(), print(), FlexibleCollimator::setDescription(), and writeGnuplot().
width_m
double mslang::BoundingBox::width_m
Definition at line 12 of file BoundingBox.h.
Referenced by mslang::QuadTree::buildUp(), doesIntersect(), isInside(), Mesher::isPotentialEdgeIntersected(), print(), FlexibleCollimator::setDescription(), and writeGnuplot().
The documentation for this struct was generated from the following files:
src/Classic/Utilities/MSLang/BoundingBox.h
src/Classic/Utilities/MSLang/BoundingBox.cpp