OPAL (Object Oriented Parallel Accelerator Library): FieldDataSource< T, Dim, M, C > Class Template Reference
FieldDataSource< T, Dim, M, C > Class Template Reference abstract
#include <FieldDataSource.h>
Public Member Functions
FieldDataSource (const char *, DataConnect *, int, Field< T, Dim, M, C > &)
virtual ~FieldDataSource ()
Public Member Functions inherited from DataSourceObject
DataSourceObject (const char *nm, DataSource *ds, DataConnect *dc, int tm)
DataSourceObject ()
virtual ~DataSourceObject ()
bool connected () const
DataConnect * getConnection ()
DataSource * getSource ()
virtual bool update ()
virtual void interact (const char *=0)
Public Member Functions inherited from NamedObj
NamedObj (const char *nm=0)
virtual ~NamedObj ()
const char * name () const
const char * setName (const char *nm=0)
Protected Member Functions
void gather_data ()
virtual void insert_data (const NDIndex< Dim > &, CompressedBrickIterator< T, Dim >)=0
Protected Attributes
Field< T, Dim, M, C > & MyField
Protected Attributes inherited from DataSourceObject
DataConnect * Connection
DataSource * Source
int TransferMethod
Detailed Description
template<class T, unsigned Dim, class M, class C>
class FieldDataSource< T, Dim, M, C >
Definition at line 44 of file FieldDataSource.h.
Constructor & Destructor Documentation
FieldDataSource()
template<class T , unsigned Dim, class M , class C > FieldDataSource< T, Dim, M, C >::FieldDataSource (const char * nm, DataConnect * dc, int tm, Field< T, Dim, M, C > & F)
Definition at line 38 of file FieldDataSource.hpp.
~FieldDataSource()
template<class T , unsigned Dim, class M , class C > FieldDataSource< T, Dim, M, C >::~FieldDataSource () virtual
Definition at line 48 of file FieldDataSource.hpp.
Member Function Documentation
gather_data()
template<class T , unsigned Dim, class M , class C > void FieldDataSource< T, Dim, M, C >::gather_data (void) protected
Definition at line 56 of file FieldDataSource.hpp.
References LField< T, Dim >::begin(), IpplInfo::Comm, COMM_ANY_NODE, NDIndex< Dim >::getMessage(), CompressedBrickIterator< T, Dim >::getMessage(), IpplInfo::getNodes(), LField< T, Dim >::getOwned(), IpplInfo::myNode(), Hypervolume::n, TagMaker::next_tag(), NDIndex< Dim >::putMessage(), CompressedBrickIterator< T, Dim >::putMessage(), Communicate::receive_block(), Communicate::send(), and Attrib::Legacy::Distribution::T.
insert_data()
template<class T , unsigned Dim, class M , class C > virtual void FieldDataSource< T, Dim, M, C >::insert_data (const NDIndex< Dim > & , CompressedBrickIterator< T, Dim >) protected pure virtual
Member Data Documentation
MyField
template<class T , unsigned Dim, class M , class C > Field<T,Dim,M,C>& FieldDataSource< T, Dim, M, C >::MyField protected
Definition at line 56 of file FieldDataSource.h.
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/FieldDataSource.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/DataSource/FieldDataSource.hpp