OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyScalingFFAMagnet Namespace Reference
PyOpal::PyScalingFFAMagnet Namespace Reference
Functions
BOOST_PYTHON_MODULE (scaling_ffa_magnet)
Variables
const char * module_docstring
std::string update_docstr
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyScalingFFAMagnet::BOOST_PYTHON_MODULE (scaling_ffa_magnet)
Definition at line 75 of file PyScalingFFAMagnet.cpp.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::addGetFieldValue(), Physics::e, PyOpal::Globals::Initialise(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_element_class(), PyOpal::ExceptionTranslation::registerExceptions(), and update_docstr.
Variable Documentation
module_docstring
const char* PyOpal::PyScalingFFAMagnet::module_docstring
Initial value:
=
    "scaling_ffa_magnet contains the ScalingFFAMagnet class"
Definition at line 40 of file PyScalingFFAMagnet.cpp.
update_docstr
std::string PyOpal::PyScalingFFAMagnet::update_docstr
Initial value:
=
"Check for changes to the EndFieldModel and update the ScalingFFAMagnet appropriately.\n"
"This is done automatically the first time the ScalingFFAMagnet is used but not for\n"
"subsequent uses. WARNING: if user changes the end field model, user must call\n"
"'update_end_field' manually to load the new parameters.\n"
"\n"
"May throw RuntimeError if the EndFieldModel is not valid or cannot be found.\n"
"\n"
"Returns None.\n"
Definition at line 65 of file PyScalingFFAMagnet.cpp.
Referenced by BOOST_PYTHON_MODULE().