OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyOpalObjectNS::PyOpalObject< C > Class Template Reference
PyOpal::PyOpalObjectNS::PyOpalObject< C > Class Template Reference
#include <PyOpalObject.h>
Public Types
typedef PyOpalObject< C > PyC
Public Member Functions
PyOpalObject ()
PyOpalObject (std::shared_ptr< C > object)
PyOpalObject (const PyOpalObject< C > &rhs)
virtual ~PyOpalObject ()=default
boost::python::class_< PyC > make_class (const char *className)
boost::python::class_< PyC > make_element_class (const char *className)
boost::python::class_< PyC > make_generic_class (const char *className)
template<class PYCLASS >
void addAttributes (PYCLASS &pyclass)
template<class PYCLASS >
void addExecute (PYCLASS &pyclass)
template<class PYCLASS >
void addRegister (PYCLASS &pyclass)
template<class PYCLASS >
void addGetOpalName (PYCLASS &pyclass)
template<class PYCLASS >
void addSetAttributes (PYCLASS &pyclass)
template<class PYCLASS >
void addSetOpalName (PYCLASS &pyclass)
template<class PYCLASS >
void addSetOpalElementName (PYCLASS &pyclass)
template<class PYCLASS >
void addGetOpalElement (PYCLASS &pyclass)
template<class PYCLASS >
void addGetFieldValue (PYCLASS &pyclass, double distanceUnits, double timeUnits, double bfieldUnits, double efieldUnits)
template<class ValueType >
ValueType dummyGet () const
virtual void doSetup ()
template<class ValueType >
void dummySet (ValueType test)
PyObject * getAttribute (AttributeType type, std::string opalName) const
void setAttribute (AttributeType type, std::string opalName, PyObject *value)
std::shared_ptr< C > getOpalShared ()
std::shared_ptr< C > getOpalShared () const
template<>
PyOpalObject ()
template<>
void doSetup ()
template<>
PyOpalObject ()
template<>
void doSetup ()
template<>
void doSetup ()
template<>
void doSetup ()
Protected Member Functions
std::string getDocString (AttributeDef &def)
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::string classDocstring
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::string classDocstring
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::string classDocstring
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::string classDocstring
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::string classDocstring
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::string classDocstring
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::string classDocstring
template<>
std::string classDocstring
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::string classDocstring
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::string classDocstring
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::string classDocstring
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::string classDocstring
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::string classDocstring
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::string classDocstring
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::vector< PyOpalObjectNS::AttributeDef > attributes
template<>
std::string classDocstring
Static Protected Member Functions
static boost::python::object getFieldValue (PyOpalObjectNS::PyOpalObject< C > &pyobject, double x, double y, double z, double t)
static std::string getOpalName (const PyOpalObject< C > &pyobject)
static void setOpalName (PyOpalObject< C > &pyobject, std::string name)
static void setOpalElementName (PyOpalObject< C > &pyobject, std::string name)
static void execute (PyOpalObject< C > &pyobject)
static void registerObject (PyOpalObject< C > &pyobject)
static boost::python::object getPyOpalElement (PyOpalObject< C > &pyobject)
static boost::python::object setAttributes (boost::python::tuple args, boost::python::dict kwargs)
Protected Attributes
std::shared_ptr< C > object_m
Static Protected Attributes
static std::vector< AttributeDef > attributes
static std::map< std::string, AttributeDef > pyNameToAttribute
static std::string classDocstring
static bool converterRegistered
static double distanceUnits_m = 1
static double timeUnits_m = 1
static double bfieldUnits_m = 1
static double efieldUnits_m = 1
static const std::string getFieldValueDocString
Detailed Description
template<class C>
class PyOpal::PyOpalObjectNS::PyOpalObject< C >
PyOpalObject<C> is the basic wrapper class for Opal Objects
PyOpalObject<C> is a wrapper for an Opal Object C. Opal Attributes are implemented in python as properties (public member data). Some default method calls can be enabled in the concrete implementation by setting flags. Docstring can be enabled by setting classDocString.
element_m: pointer to the base element attributes: vector of attributes. The order of the vector is the order that attributes will appear in the docstring classDocString: overall docstring. docstrings on each property and method are added automatically by the framework.
property access is set up in make_class using add_property from boost::python. Normally, the "get" method can't take any data; this would mean that we can't pass an Attribute name for the OpalElement lookup. In order to get around this limitation, we have a "dummy" getter dummyGet. Then there is a "real" getter, which is hidden in the call policy for the property (a sort of pre- and post- decorator). We use PyOpalObjectGetProperty to hold the Attribute name and then dummyGet just tells PyElementGetProperty the address of the PyOpalObject. PyElementGetProperty does a postcall action to overwrite the return value with the "real" return value, based on the stored Attribute name.
Setters work in exactly the same way, except now we have dummySet and PyElementSetProperty to handle the interface.
The routine then looks like: python::boost calls dummyGet; dummyGet tells PyElementGetProperty pointer to PyOpalObject python::boost calls PyElementGetProperty.postcall PyElementGetProperty.postcall calls PyOpalObject->getAttribute; where getAttribute takes the name of the Attribute as a string. It's a bit of a faff.
Definition at line 69 of file PyOpalObject.h.
Member Typedef Documentation
PyC
template<class C> typedef PyOpalObject<C> PyOpal::PyOpalObjectNS::PyOpalObject< C >::PyC
Definition at line 140 of file PyOpalObject.h.
Constructor & Destructor Documentation
PyOpalObject() [1/5]
template<class C > PyOpal::PyOpalObjectNS::PyOpalObject< C >::PyOpalObject () inline
Default constructor
Definition at line 530 of file PyOpalObject.h.
PyOpalObject() [2/5]
template<class C> PyOpal::PyOpalObjectNS::PyOpalObject< C >::PyOpalObject (std::shared_ptr< C > object) inline
Constructor taking the element as argument
Definition at line 144 of file PyOpalObject.h.
PyOpalObject() [3/5]
template<class C > PyOpal::PyOpalObjectNS::PyOpalObject< C >::PyOpalObject (const PyOpalObject< C > & rhs)
Copying is disabled
Definition at line 693 of file PyOpalObject.h.
~PyOpalObject()
template<class C> virtual PyOpal::PyOpalObjectNS::PyOpalObject< C >::~PyOpalObject () virtual default
Default destructor
PyOpalObject() [4/5]
template<> PyOpal::PyOpalObjectNS::PyOpalObject< OpalElement >::PyOpalObject ()
PyOpalObject() [5/5]
template<> PyOpal::PyOpalObjectNS::PyOpalObject< OpalElement >::PyOpalObject ()
Definition at line 19 of file PyOpalElement.cpp.
Member Function Documentation
addAttributes()
template<class C > template<class PYCLASS > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::addAttributes (PYCLASS & pyclass)
Add attributes to the python class.
Definition at line 820 of file PyOpalObject.h.
References PyOpal::PyOpalObjectNS::BOOL, PyOpal::PyOpalObjectNS::DOUBLE, PyOpal::PyOpalObjectNS::FLOAT_LIST, PyOpal::PyOpalObjectNS::INT, PyOpal::PyOpalObjectNS::PREDEFINED_STRING, PyOpal::PyOpalObjectNS::STRING, PyOpal::PyOpalObjectNS::STRING_LIST, and PyOpal::PyOpalObjectNS::UPPER_CASE_STRING.
addExecute()
template<class C > template<class PYCLASS > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::addExecute (PYCLASS & pyclass)
Add an "execute" method to the python class (e.g. if it is an ACTION)
Definition at line 761 of file PyOpalObject.h.
Referenced by PyOpal::PyDistributionNS::BOOST_PYTHON_MODULE(), PyOpal::PyTrackRunNS::BOOST_PYTHON_MODULE(), and PyOpal::PyOptionNS::BOOST_PYTHON_MODULE().
addGetFieldValue()
template<class C > template<class PYCLASS > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::addGetFieldValue (PYCLASS & pyclass, double distanceUnits, double timeUnits, double bfieldUnits, double efieldUnits)
Add a "get_field_value" method to the python class (for elements that expose a field)
PYCLASS: instance of the class to which the field is added
distanceUnits: set the distance units so that UI is in OPAL units
timeUnits: set the time units so that UI is in OPAL units
bfieldUnits: set the bfield units so that UI is in OPAL units
efieldUnits: set the efield units so that UI is in OPAL units
It is encouraged to expose the field map for field-type objects, for user to check that the field is as expected.
Note that conversion factors for units in distance, time, bfield and efield should be provided - the OPAL unit system should be exposed to user (see OPAL docs for current recommendation). Opal will call element->apply(R*distanceUnits, P, t*timeUnits, Efield, Bfield) and return Efield*efieldUnits, BField*bfield units.
Definition at line 805 of file PyOpalObject.h.
Referenced by PyOpal::PyVerticalFFAMagnet::BOOST_PYTHON_MODULE(), PyOpal::PyVariableRFCavity::BOOST_PYTHON_MODULE(), PyOpal::PyVariableRFCavityFringeField::BOOST_PYTHON_MODULE(), PyOpal::PyMultipoleT::BOOST_PYTHON_MODULE(), PyOpal::PyScalingFFAMagnet::BOOST_PYTHON_MODULE(), and PyOpal::PyRingDefinition::BOOST_PYTHON_MODULE().
addGetOpalElement()
template<class C > template<class PYCLASS > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::addGetOpalElement (PYCLASS & pyclass)
Add a "get_opal_element" method to the python class (to overload as a PyOpalElement)
This is required for OpalElement objects, in order that they can be used in a OPAL line object (for setting up beamlines having multiple elements). In general, if C is an OpalElement, developer should call addGetOpalElement in the module setup function.
Definition at line 799 of file PyOpalObject.h.
Referenced by PyOpal::PyLineNS::BOOST_PYTHON_MODULE().
addGetOpalName()
template<class C > template<class PYCLASS > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::addGetOpalName (PYCLASS & pyclass)
Add a get_opal_name method to the python class (to get the opal internal string that uniquely identifies the object)
Definition at line 773 of file PyOpalObject.h.
addRegister()
template<class C > template<class PYCLASS > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::addRegister (PYCLASS & pyclass)
Add a "register" method to the python class (to register against opal global data object)
Definition at line 767 of file PyOpalObject.h.
Referenced by PyOpal::PyBeamNS::BOOST_PYTHON_MODULE().
addSetAttributes()
template<class C > template<class PYCLASS > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::addSetAttributes (PYCLASS & pyclass)
Add a set_attributes method to the python class (to setup opalobject from a dictionary of kwargs)
Definition at line 779 of file PyOpalObject.h.
addSetOpalElementName()
template<class C > template<class PYCLASS > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::addSetOpalElementName (PYCLASS & pyclass)
Add a set_opal_name method to the python class (to set the opal internal string that uniquely identifies the object). This version has bindings specifically for OpalElements
Definition at line 793 of file PyOpalObject.h.
addSetOpalName()
template<class C > template<class PYCLASS > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::addSetOpalName (PYCLASS & pyclass)
Add a set_opal_name method to the python class (to set the opal internal string that uniquely identifies the object)
Definition at line 787 of file PyOpalObject.h.
attributes() [1/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalProbe >::attributes () protected
Definition at line 10 of file PyProbe.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE, and PyOpal::PyOpalObjectNS::STRING.
attributes() [2/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalOffset::OpalGlobalCartesianOffset >::attributes () protected
Definition at line 11 of file PyGlobalCartesianOffset.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE.
attributes() [3/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalOffset::OpalLocalCartesianOffset >::attributes () protected
Definition at line 11 of file PyLocalCartesianOffset.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE.
attributes() [4/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalElement >::attributes () protected
Definition at line 11 of file PyOpalElement.cpp.
attributes() [5/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalPolynomialTimeDependence >::attributes () protected
Definition at line 11 of file PyPolynomialTimeDependence.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE, and PyOpal::PyOpalObjectNS::FLOAT_LIST.
attributes() [6/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalEnge >::attributes () protected
Definition at line 11 of file PyEnge.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE, and PyOpal::PyOpalObjectNS::FLOAT_LIST.
attributes() [7/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalAsymmetricEnge >::attributes () protected
Definition at line 12 of file PyAsymmetricEnge.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE, and PyOpal::PyOpalObjectNS::FLOAT_LIST.
attributes() [8/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalOutputPlane >::attributes () protected
Definition at line 24 of file PyOutputPlane.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE, PyOpal::PyOpalObjectNS::FLOAT_LIST, PyOpal::PyOpalObjectNS::INT, PyOpal::PyOpalObjectNS::PREDEFINED_STRING, and PyOpal::PyOpalObjectNS::STRING.
attributes() [9/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< Distribution >::attributes () protected
Definition at line 25 of file PyDistribution.cpp.
References PyOpal::PyOpalObjectNS::PREDEFINED_STRING, and PyOpal::PyOpalObjectNS::STRING.
attributes() [10/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< TrackCmd >::attributes () protected
Definition at line 25 of file PyTrackCmd.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE, PyOpal::PyOpalObjectNS::FLOAT_LIST, PyOpal::PyOpalObjectNS::PREDEFINED_STRING, and PyOpal::PyOpalObjectNS::STRING.
attributes() [11/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalVerticalFFAMagnet >::attributes () protected
Definition at line 25 of file PyVerticalFFAMagnet.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE, and PyOpal::PyOpalObjectNS::INT.
attributes() [12/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< Option >::attributes () protected
Definition at line 26 of file PyOption.cpp.
References PyOpal::PyOpalObjectNS::BOOL, PyOpal::PyOpalObjectNS::DOUBLE, and PyOpal::PyOpalObjectNS::PREDEFINED_STRING.
attributes() [13/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< Beam >::attributes () protected
Definition at line 26 of file PyBeam.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE, and PyOpal::PyOpalObjectNS::PREDEFINED_STRING.
attributes() [14/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< FieldSolver >::attributes () protected
Definition at line 27 of file PyFieldSolver.cpp.
References PyOpal::PyOpalObjectNS::BOOL, PyOpal::PyOpalObjectNS::DOUBLE, PyOpal::PyOpalObjectNS::PREDEFINED_STRING, and PyOpal::PyOpalObjectNS::UPPER_CASE_STRING.
attributes() [15/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< TrackRun >::attributes () protected
Definition at line 28 of file PyTrackRun.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE, PyOpal::PyOpalObjectNS::PREDEFINED_STRING, PyOpal::PyOpalObjectNS::STRING, and PyOpal::PyOpalObjectNS::STRING_LIST.
attributes() [16/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalSinusoidalTimeDependence >::attributes () protected
Definition at line 28 of file PySinusoidalTimeDependence.cpp.
References PyOpal::PyOpalObjectNS::FLOAT_LIST.
attributes() [17/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< TBeamline< Element > >::attributes () protected
Definition at line 28 of file PyLine.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE, and PyOpal::PyOpalObjectNS::STRING.
attributes() [18/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalSplineTimeDependence >::attributes () protected
Definition at line 37 of file PySplineTimeDependence.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE, and PyOpal::PyOpalObjectNS::FLOAT_LIST.
attributes() [19/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalScalingFFAMagnet >::attributes () protected
Definition at line 39 of file PyScalingFFAMagnet.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE, PyOpal::PyOpalObjectNS::INT, and PyOpal::PyOpalObjectNS::STRING.
attributes() [20/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalMultipoleT >::attributes () protected
Definition at line 41 of file PyMultipoleT.cpp.
References PyOpal::PyOpalObjectNS::BOOL, PyOpal::PyOpalObjectNS::DOUBLE, PyOpal::PyOpalObjectNS::FLOAT_LIST, and PyOpal::PyOpalObjectNS::STRING.
attributes() [21/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalVariableRFCavity >::attributes () protected
Definition at line 42 of file PyVariableRFCavity.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE, and PyOpal::PyOpalObjectNS::STRING.
attributes() [22/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalVariableRFCavityFringeField >::attributes () protected
Definition at line 43 of file PyVariableRFCavityFringeField.cpp.
References PyOpal::PyOpalObjectNS::DOUBLE, and PyOpal::PyOpalObjectNS::STRING.
attributes() [23/23]
template<> std::vector< PyOpalObjectNS::AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< OpalRingDefinition >::attributes () protected
Definition at line 44 of file PyRingDefinition.cpp.
References PyOpal::PyOpalObjectNS::BOOL, PyOpal::PyOpalObjectNS::DOUBLE, and PyOpal::PyOpalObjectNS::INT.
classDocstring() [1/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< OpalElement >::classDocstring () protected
Definition at line 14 of file PyOpalElement.cpp.
classDocstring() [2/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< OpalEnge >::classDocstring () protected
Definition at line 18 of file PyEnge.cpp.
classDocstring() [3/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< OpalPolynomialTimeDependence >::classDocstring () protected
Definition at line 20 of file PyPolynomialTimeDependence.cpp.
classDocstring() [4/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< OpalAsymmetricEnge >::classDocstring () protected
Definition at line 22 of file PyAsymmetricEnge.cpp.
classDocstring() [5/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< OpalProbe >::classDocstring () protected
Definition at line 24 of file PyProbe.cpp.
classDocstring() [6/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< OpalRingDefinition >::classDocstring () protected
Definition at line 29 of file PyRingDefinition.cpp.
classDocstring() [7/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< OpalSinusoidalTimeDependence >::classDocstring () protected
Definition at line 36 of file PySinusoidalTimeDependence.cpp.
classDocstring() [8/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< OpalVerticalFFAMagnet >::classDocstring () protected
Definition at line 38 of file PyVerticalFFAMagnet.cpp.
classDocstring() [9/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< TrackRun >::classDocstring () protected
Definition at line 42 of file PyTrackRun.cpp.
classDocstring() [10/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< OpalSplineTimeDependence >::classDocstring () protected
Definition at line 44 of file PySplineTimeDependence.cpp.
classDocstring() [11/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< OpalOutputPlane >::classDocstring () protected
Definition at line 45 of file PyOutputPlane.cpp.
classDocstring() [12/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< OpalVariableRFCavity >::classDocstring () protected
Definition at line 52 of file PyVariableRFCavity.cpp.
classDocstring() [13/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< OpalVariableRFCavityFringeField >::classDocstring () protected
Definition at line 57 of file PyVariableRFCavityFringeField.cpp.
classDocstring() [14/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< OpalScalingFFAMagnet >::classDocstring () protected
Definition at line 57 of file PyScalingFFAMagnet.cpp.
classDocstring() [15/15]
template<> std::string PyOpal::PyOpalObjectNS::PyOpalObject< OpalMultipoleT >::classDocstring () protected
Definition at line 61 of file PyMultipoleT.cpp.
doSetup() [1/5]
template<> void PyOpal::PyOpalObjectNS::PyOpalObject< OpalScalingFFAMagnet >::doSetup ()
Overload this method on the PyOpalObject - it is supposed to be called every time the magnet is updated (i.e. every time get_field_value is called from python).
The point is the EndFieldModel could have changed and we redo setup just in case (terribly inefficient)
Definition at line 32 of file PyScalingFFAMagnet.cpp.
References ScalingFFAMagnet::setupEndField().
doSetup() [2/5]
template<> void PyOpal::PyOpalObjectNS::PyOpalObject< OpalMultipoleT >::doSetup ()
Overload this method on the PyOpalObject - it is supposed to be called every time the cavity is updated (i.e. every time get_field_value is called from python).
The point is the TimeDependence could have changed and we redo setup just in case (terribly inefficient, but only effects python side)
Definition at line 33 of file PyMultipoleT.cpp.
References MultipoleT::initialiseTimeDepencencies().
doSetup() [3/5]
template<> void PyOpal::PyOpalObjectNS::PyOpalObject< OpalVariableRFCavity >::doSetup ()
Overload this method on the PyOpalObject - it is supposed to be called every time the cavity is updated (i.e. every time get_field_value is called from python).
The point is the TimeDependence could have changed and we redo setup just in case (terribly inefficient, but only effects python side)
Definition at line 34 of file PyVariableRFCavity.cpp.
References VariableRFCavity::initialise().
doSetup() [4/5]
template<> void PyOpal::PyOpalObjectNS::PyOpalObject< OpalVariableRFCavityFringeField >::doSetup ()
Overload this method on the PyOpalObject - it is supposed to be called every time the cavity is updated (i.e. every time get_field_value is called from python).
The point is the TimeDependence could have changed and we redo setup just in case (terribly inefficient, but only effects python side)
Definition at line 34 of file PyVariableRFCavityFringeField.cpp.
References VariableRFCavityFringeField::initialise().
doSetup() [5/5]
template<class C> virtual void PyOpal::PyOpalObjectNS::PyOpalObject< C >::doSetup () inline virtual
Overload the method to perform any additional setup that can be made before the OpalObject is accessed, after OpalObject->update() is called.
Definition at line 258 of file PyOpalObject.h.
Referenced by PyOpal::PyOpalObjectNS::PyOpalObject< C >::getFieldValue().
dummyGet()
template<class C> template<class ValueType > ValueType PyOpal::PyOpalObjectNS::PyOpalObject< C >::dummyGet () const inline
dummyGet sets the object ptr for PyOpalObjectGetProperty but doesn't actually do the get(...)
Definition at line 253 of file PyOpalObject.h.
References PyOpal::PyOpalObjectNS::PyOpalObjectGetProperty< C >::setObject().
dummySet()
template<class C > template<class ValueType > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::dummySet (ValueType test) inline
dummySet sets the element ptr for PyOpalObjectSetProperty but doesn't actually do the set(...)
Definition at line 347 of file PyOpalObject.h.
References PyOpal::PyOpalObjectNS::PyOpalObjectSetProperty< C >::setObject().
execute()
template<class C > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::execute (PyOpalObject< C > & pyobject) static protected
method to call "execute" on an object
Definition at line 473 of file PyOpalObject.h.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalShared().
getAttribute()
template<class C > PyObject * PyOpal::PyOpalObjectNS::PyOpalObject< C >::getAttribute (AttributeType type, std::string opalName) const
Get the value of an attribute
type: the type expected for python
opalName: the name of the Opal Attribute Returns a PyObject holding data; INCREF is called on the object i.e. it is a new object, not borrowed.
It is an error if the Attribute does not exist (throws OpalException)
Definition at line 533 of file PyOpalObject.h.
References PyOpal::PyOpalObjectNS::attributeName, PyOpal::PyOpalObjectNS::BOOL, PyOpal::PyOpalObjectNS::DOUBLE, PyOpal::PyOpalObjectNS::FLOAT_LIST, Attributes::getBool(), Attributes::getReal(), Attributes::getRealArray(), Attributes::getString(), Attributes::getStringArray(), PyOpal::PyOpalObjectNS::INT, PyOpal::PyOpalObjectNS::PREDEFINED_STRING, PyOpal::PyOpalObjectNS::STRING, PyOpal::PyOpalObjectNS::STRING_LIST, and PyOpal::PyOpalObjectNS::UPPER_CASE_STRING.
getDocString()
template<class C > std::string PyOpal::PyOpalObjectNS::PyOpalObject< C >::getDocString (AttributeDef & def) protected
pointer to the element Generates a docstring from the attribute
Definition at line 697 of file PyOpalObject.h.
References PyOpal::PyOpalObjectNS::attributeName, PyOpal::PyOpalObjectNS::AttributeDef::docString_m, Attribute::getHelp(), PyOpal::PyOpalObjectNS::AttributeDef::opalName_m, PyOpal::PyOpalObjectNS::AttributeDef::pyName_m, and PyOpal::PyOpalObjectNS::AttributeDef::type_m.
getFieldValue()
template<class C > boost::python::object PyOpal::PyOpalObjectNS::PyOpalObject< C >::getFieldValue (PyOpalObjectNS::PyOpalObject< C > & pyobject, double x, double y, double z, double t) static protected
method to get field at a point in space-time
Definition at line 353 of file PyOpalObject.h.
References Component::apply(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::doSetup(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalShared(), and Attrib::Distribution::R.
getOpalName()
template<class C > std::string PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalName (const PyOpalObject< C > & pyobject) static protected
method to get the opal name of an object
Definition at line 491 of file PyOpalObject.h.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalShared().
getOpalShared() [1/2]
template<class C> std::shared_ptr<C> PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalShared () inline
Returns the Opal Object from the PyOpalObject
Definition at line 286 of file PyOpalObject.h.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::object_m.
Referenced by PyOpal::PyOpalObjectNS::PyOpalObject< C >::execute(), PyOpal::PyTrackCmdNS::executeWrapper(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::getFieldValue(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalName(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::getPyOpalElement(), PyOpal::PyDistributionNS::registerDistribution(), PyOpal::PyFieldSolverNS::registerFieldSolver(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::registerObject(), PyOpal::PyLine_< C >::setElement(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::setOpalElementName(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::setOpalName(), and PyOpal::PyOpalObjectNS::update().
getOpalShared() [2/2]
template<class C> std::shared_ptr<C> PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalShared () const inline
Returns the Opal Object from the PyOpalObject (const version)
Definition at line 289 of file PyOpalObject.h.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::object_m.
getPyOpalElement()
template<class C > boost::python::object PyOpal::PyOpalObjectNS::PyOpalObject< C >::getPyOpalElement (PyOpalObjectNS::PyOpalObject< C > & pyobject) static protected
return the underlying element (used e.g. by PyLine)
Definition at line 512 of file PyOpalObject.h.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalShared().
make_class()
template<class C > boost::python::class_< PyOpalObject< C > > PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_class (const char * className) inline
This is the basic method to make a class for OpalObjects. It should normally be called when the module is declared, BOOST_PYTHON_MODULE.
Note that while in principle this could be static, in the end we need an instance of C so that we can access the docString from the attribute.
Definition at line 745 of file PyOpalObject.h.
Referenced by PyOpal::PyEnge::BOOST_PYTHON_MODULE(), PyOpal::PyOpalPolynomialTimeDependence::BOOST_PYTHON_MODULE(), PyOpal::PyDistributionNS::BOOST_PYTHON_MODULE(), PyOpal::PyBeamNS::BOOST_PYTHON_MODULE(), PyOpal::PyTrackCmdNS::BOOST_PYTHON_MODULE(), PyOpal::PyOpalSinusoidalTimeDependence::BOOST_PYTHON_MODULE(), PyOpal::PyTrackRunNS::BOOST_PYTHON_MODULE(), PyOpal::PyOpalSplineTimeDependence::BOOST_PYTHON_MODULE(), and PyOpal::PyOptionNS::BOOST_PYTHON_MODULE().
make_element_class()
template<class C > boost::python::class_< PyOpalObject< C > > PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_element_class (const char * className) inline
This is the basic method to make a class for elements.
This differs from make_class(...) because the setOpalName method sets the underlying element name at the same time.
Definition at line 752 of file PyOpalObject.h.
Referenced by PyOpal::PyOpalGlobalCartesianOffset::BOOST_PYTHON_MODULE(), PyOpal::PyOpalLocalCartesianOffset::BOOST_PYTHON_MODULE(), PyOpal::PyOpalElement::BOOST_PYTHON_MODULE(), PyOpal::PyProbe::BOOST_PYTHON_MODULE(), PyOpal::PyAsymmetricEnge::BOOST_PYTHON_MODULE(), PyOpal::PyVerticalFFAMagnet::BOOST_PYTHON_MODULE(), PyOpal::PyOutputPlane::BOOST_PYTHON_MODULE(), PyOpal::PyVariableRFCavity::BOOST_PYTHON_MODULE(), PyOpal::PyVariableRFCavityFringeField::BOOST_PYTHON_MODULE(), PyOpal::PyMultipoleT::BOOST_PYTHON_MODULE(), PyOpal::PyScalingFFAMagnet::BOOST_PYTHON_MODULE(), and PyOpal::PyRingDefinition::BOOST_PYTHON_MODULE().
make_generic_class()
template<class C > boost::python::class_< PyOpalObject< C > > PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_generic_class (const char * className) inline
This is the basic method to make a class for generic Opal object type.
In this one, the setOpalName method is not assigned, and user has to assign it (if they want it)
Definition at line 711 of file PyOpalObject.h.
References endl(), gmsg, and OpalException::what().
registerObject()
template<class C > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::registerObject (PyOpalObjectNS::PyOpalObject< C > & pyobject) static protected
method to call "register" on an object
Definition at line 479 of file PyOpalObject.h.
References OpalData::define(), OpalData::getInstance(), and PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalShared().
setAttribute()
template<class C > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::setAttribute (AttributeType type, std::string opalName, PyObject * value)
Set the value of an attribute
type: the type expected for python
opalName: the name of the Opal Attribute
value: Python object holding the value to be stored. value refcnt is not changed - caller is responsible for managing the refcnt. It is an error if the Attribute does not exist (throws OpalException)
Definition at line 610 of file PyOpalObject.h.
References PyOpal::PyOpalObjectNS::attributeName, PyOpal::PyOpalObjectNS::BOOL, PyOpal::PyOpalObjectNS::DOUBLE, PyOpal::PyOpalObjectNS::FLOAT_LIST, PyOpal::PyOpalObjectNS::INT, PyOpal::PyOpalObjectNS::PREDEFINED_STRING, Attributes::setBool(), Attributes::setPredefinedString(), Attributes::setReal(), Attributes::setRealArray(), Attributes::setString(), Attributes::setStringArray(), Attributes::setUpperCaseString(), PyOpal::PyOpalObjectNS::STRING, PyOpal::PyOpalObjectNS::STRING_LIST, and PyOpal::PyOpalObjectNS::UPPER_CASE_STRING.
Referenced by PyOpal::PyOpalObjectNS::PyOpalObject< C >::setAttributes().
setAttributes()
template<class C > boost::python::object PyOpal::PyOpalObjectNS::PyOpalObject< C >::setAttributes (boost::python::tuple args, boost::python::dict kwargs) static protected
set many attributes at once as a dict, stored in kwarg. args should be exactly equal to (self,)
Pass a dictionary of attributes to the pyobject using the python *args **kwargs semantics
Definition at line 378 of file PyOpalObject.h.
References Expressions::find(), PyOpal::PyOpalObjectNS::AttributeDef::opalName_m, PyOpal::PyOpalObjectNS::PyOpalObject< C >::setAttribute(), and PyOpal::PyOpalObjectNS::AttributeDef::type_m.
setOpalElementName()
template<class C > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::setOpalElementName (PyOpalObject< C > & pyobject, std::string name) static protected
method to set the opal name of an element - elements have two "names", one belonging to the OpalObject and one belonging to the Component
Definition at line 503 of file PyOpalObject.h.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalShared(), and name.
setOpalName()
template<class C > void PyOpal::PyOpalObjectNS::PyOpalObject< C >::setOpalName (PyOpalObject< C > & pyobject, std::string name) static protected
method to set the opal name of an object
Definition at line 497 of file PyOpalObject.h.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalShared(), and name.
Member Data Documentation
attributes
template<class C> std::vector<AttributeDef> PyOpal::PyOpalObjectNS::PyOpalObject< C >::attributes static protected
Definition at line 293 of file PyOpalObject.h.
bfieldUnits_m
template<class C> double PyOpal::PyOpalObjectNS::PyOpalObject< C >::bfieldUnits_m = 1 static protected
Definition at line 325 of file PyOpalObject.h.
classDocstring
template<class C> std::string PyOpal::PyOpalObjectNS::PyOpalObject< C >::classDocstring static protected
maps python name to AttributeDef for fast lookup
Definition at line 295 of file PyOpalObject.h.
converterRegistered
template<class C> bool PyOpal::PyOpalObjectNS::PyOpalObject< C >::converterRegistered static protected
class docstring
Definition at line 296 of file PyOpalObject.h.
distanceUnits_m
template<class C> double PyOpal::PyOpalObjectNS::PyOpalObject< C >::distanceUnits_m = 1 static protected
Definition at line 323 of file PyOpalObject.h.
efieldUnits_m
template<class C> double PyOpal::PyOpalObjectNS::PyOpalObject< C >::efieldUnits_m = 1 static protected
Definition at line 326 of file PyOpalObject.h.
getFieldValueDocString
template<class C> const std::string PyOpal::PyOpalObjectNS::PyOpalObject< C >::getFieldValueDocString static protected
Definition at line 327 of file PyOpalObject.h.
object_m
template<class C> std::shared_ptr<C> PyOpal::PyOpalObjectNS::PyOpalObject< C >::object_m protected
set to true if the converter has been registered
Definition at line 297 of file PyOpalObject.h.
Referenced by PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalShared().
pyNameToAttribute
template<class C> std::map< std::string, AttributeDef > PyOpal::PyOpalObjectNS::PyOpalObject< C >::pyNameToAttribute static protected
class data (attributes)
apparently this is okay because it is a template and doesnt break one definition rule
Definition at line 294 of file PyOpalObject.h.
timeUnits_m
template<class C> double PyOpal::PyOpalObjectNS::PyOpalObject< C >::timeUnits_m = 1 static protected
Definition at line 324 of file PyOpalObject.h.
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/src/PyOpal/PyCore/PyOpalObject.h