OPAL (Object Oriented Parallel Accelerator Library): EVector Class Reference
EVector Class Reference
An electric field vector.
#include <EMField.h>
Public Member Functions
EVector (double, double, double)
Constructor.
EVector operator* (double scalar) const
Scale.
double getEx () const
Get component.
double getEy () const
Get component.
double getEz () const
Get component.
Private Attributes
double Ex
double Ey
double Ez
Detailed Description
An electric field vector.
Definition at line 63 of file EMField.h.
Constructor & Destructor Documentation
EVector()
EVector::EVector (double Exx, double Eyy, double Ezz)
Constructor.
Definition at line 47 of file EMField.cpp.
References Ex, Ey, and Ez.
Referenced by operator*().
Member Function Documentation
getEx()
double EVector::getEx () const
Get component.
Definition at line 55 of file EMField.cpp.
References Ex.
Referenced by EBVectors::getEx().
getEy()
double EVector::getEy () const
Get component.
Definition at line 59 of file EMField.cpp.
References Ey.
Referenced by EBVectors::getEy().
getEz()
double EVector::getEz () const
Get component.
Definition at line 63 of file EMField.cpp.
References Ez.
Referenced by EBVectors::getEz().
operator*()
EVector EVector::operator* (double scalar) const
Scale.
Definition at line 51 of file EMField.cpp.
References EVector(), Ex, Ey, and Ez.
Member Data Documentation
Ex
double EVector::Ex private
Definition at line 89 of file EMField.h.
Referenced by EVector(), getEx(), and operator*().
Ey
double EVector::Ey private
Definition at line 89 of file EMField.h.
Referenced by EVector(), getEy(), and operator*().
Ez
double EVector::Ez private
Definition at line 89 of file EMField.h.
Referenced by EVector(), getEz(), and operator*().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/EMField.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/EMField.cpp