OPAL (Object Oriented Parallel Accelerator Library): TSV_MetaDot< SymTenzor< T1, D >, Tenzor< T2, D > > Struct Template Reference
TSV_MetaDot< SymTenzor< T1, D >, Tenzor< T2, D > > Struct Template Reference
#include <TSVMetaDot.h>
Public Types
typedef PETEBinaryReturn< T1, T2, OpMultipply >::type T0
Static Public Member Functions
static Tenzor< T0, D > apply (const SymTenzor< T1, D > &lhs, const Tenzor< T2, D > &rhs)
Detailed Description
template<class T1, class T2, unsigned D>
struct TSV_MetaDot< SymTenzor< T1, D >, Tenzor< T2, D > >
Definition at line 450 of file TSVMetaDot.h.
Member Typedef Documentation
T0
template<class T1 , class T2 , unsigned D> typedef PETEBinaryReturn<T1,T2,OpMultipply>::type TSV_MetaDot< SymTenzor< T1, D >, Tenzor< T2, D > >::T0
Definition at line 452 of file TSVMetaDot.h.
Member Function Documentation
apply()
template<class T1 , class T2 , unsigned D> static Tenzor<T0,D> TSV_MetaDot< SymTenzor< T1, D >, Tenzor< T2, D > >::apply (const SymTenzor< T1, D > & lhs, const Tenzor< T2, D > & rhs) inline static
Definition at line 454 of file TSVMetaDot.h.
References dot(), SymTenzor< T, D >::HL(), and sum().
The documentation for this struct was generated from the following file:
ippl/src/AppTypes/TSVMetaDot.h