OPAL (Object Oriented Parallel Accelerator Library): CSRIGFWakeFunction Class Reference
CSRIGFWakeFunction Class Reference
#include <CSRIGFWakeFunction.h>
Public Member Functions
CSRIGFWakeFunction (const std::string &name, std::vector< Filter *> filters, const unsigned int &N)
void apply (PartBunchBase< double, 3 > *bunch) override
void initialize (const ElementBase *ref) override
virtual WakeType getType () const override
Public Member Functions inherited from WakeFunction
WakeFunction (std::string name, unsigned int n)
virtual ~WakeFunction ()
const std::string & getName () const
Private Member Functions
void calculateLineDensity (PartBunchBase< double, 3 > *bunch, std::pair< double, double > &meshInfo)
void calculateContributionInside (size_t sliceNumber, double angleOfSlice, double meshSpacing)
void calculateContributionAfter (size_t sliceNumber, double angleOfSlice, double meshSpacing)
void calculateGreenFunction (PartBunchBase< double, 3 > *bunch, double meshSpacing)
double calcPsi (const double &psiInitial, const double &x, const double &Ds) const
Private Attributes
std::vector< Filter * > filters_m
std::shared_ptr< Filter > defaultFilter_m
Filter * diffOp_m
LineDensity lineDensity_m
LineDensity dlineDensitydz_m
std::vector< double > Ez_m
std::vector< double > Chi_m
std::vector< double > Grn_m
std::vector< double > Psi_m
double Begin_m
double FieldBegin_m
double Length_m
double bendRadius_m
std::string bendName_m
double totalBendAngle_m
Additional Inherited Members
Protected Attributes inherited from WakeFunction
const unsigned int nBins_m
Detailed Description
Definition at line 29 of file CSRIGFWakeFunction.h.
Constructor & Destructor Documentation
CSRIGFWakeFunction()
CSRIGFWakeFunction::CSRIGFWakeFunction (const std::string & name, std::vector< Filter *> filters, const unsigned int & N)
Definition at line 35 of file CSRIGFWakeFunction.cpp.
References defaultFilter_m, diffOp_m, and filters_m.
Member Function Documentation
apply()
void CSRIGFWakeFunction::apply (PartBunchBase< double, 3 > * bunch) override virtual
Implements WakeFunction.
Definition at line 51 of file CSRIGFWakeFunction.cpp.
References bendName_m, bendRadius_m, calculateContributionAfter(), calculateContributionInside(), calculateGreenFunction(), calculateLineDensity(), Chi_m, Util::combineFilePath(), Options::csrDump, PartBunchBase< T, Dim >::Ef, endl(), Physics::epsilon_0, Ez_m, FieldBegin_m, floor(), PartBunchBase< T, Dim >::get_bounds(), PartBunchBase< T, Dim >::get_sPos(), OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), PartBunchBase< T, Dim >::getLocalNum(), Grn_m, lineDensity_m, IpplInfo::myNode(), PAssert_LT, Physics::pi, Psi_m, Attrib::Distribution::R, PartBunchBase< T, Dim >::R, and totalBendAngle_m.
calcPsi()
double CSRIGFWakeFunction::calcPsi (const double & psiInitial, const double & x, const double & Ds) const private
solve the equation
\[ \Delta s = \frac{R \Psi^3}{24} \frac{\Psi + 4x}{\Psi + x} \]
for \(\Psi\) using Newtons method.
Definition at line 257 of file CSRIGFWakeFunction.cpp.
References abs(), bendRadius_m, Physics::e, endl(), ERRORMSG, RootFinderForCSR::hasPositiveRealRoots(), pow(), and RootFinderForCSR::searchRoot().
Referenced by calculateContributionAfter().
calculateContributionAfter()
void CSRIGFWakeFunction::calculateContributionAfter (size_t sliceNumber, double angleOfSlice, double meshSpacing) private
Definition at line 198 of file CSRIGFWakeFunction.cpp.
References bendRadius_m, calcPsi(), dlineDensitydz_m, Ez_m, floor(), lineDensity_m, pow(), Psi_m, and totalBendAngle_m.
Referenced by apply().
calculateContributionInside()
void CSRIGFWakeFunction::calculateContributionInside (size_t sliceNumber, double angleOfSlice, double meshSpacing) private
Definition at line 189 of file CSRIGFWakeFunction.cpp.
References Ez_m, Grn_m, lineDensity_m, and totalBendAngle_m.
Referenced by apply().
calculateGreenFunction()
void CSRIGFWakeFunction::calculateGreenFunction (PartBunchBase< double, 3 > * bunch, double meshSpacing) private
Definition at line 163 of file CSRIGFWakeFunction.cpp.
References bendRadius_m, Chi_m, Physics::e, Units::eV2MeV, PartBunchBase< T, Dim >::get_meanKineticEnergy(), PartBunchBase< T, Dim >::getM(), Grn_m, lineDensity_m, log(), pow(), and sqrt().
Referenced by apply().
calculateLineDensity()
void CSRIGFWakeFunction::calculateLineDensity (PartBunchBase< double, 3 > * bunch, std::pair< double, double > & meshInfo) private
Definition at line 150 of file CSRIGFWakeFunction.cpp.
References Filter::calc_derivative(), PartBunchBase< T, Dim >::calcLineDensity(), diffOp_m, dlineDensitydz_m, filters_m, lineDensity_m, and WakeFunction::nBins_m.
Referenced by apply().
getType()
WakeType CSRIGFWakeFunction::getType () const override virtual
Implements WakeFunction.
Definition at line 285 of file CSRIGFWakeFunction.cpp.
References CSRIGFWakeFunction.
initialize()
void CSRIGFWakeFunction::initialize (const ElementBase * ref) override virtual
Reimplemented from WakeFunction.
Definition at line 134 of file CSRIGFWakeFunction.cpp.
References abs(), Begin_m, bendName_m, bendRadius_m, FieldBegin_m, BendBase::getBendAngle(), Bend2D::getBendRadius(), Bend2D::getDimensions(), Bend2D::getEffectiveCenter(), Bend2D::getEffectiveLength(), ElementBase::getName(), Length_m, RBEND, Hypervolume::ref, SBEND, and totalBendAngle_m.
Member Data Documentation
Begin_m
double CSRIGFWakeFunction::Begin_m private
Definition at line 67 of file CSRIGFWakeFunction.h.
Referenced by initialize().
bendName_m
std::string CSRIGFWakeFunction::bendName_m private
Definition at line 79 of file CSRIGFWakeFunction.h.
Referenced by apply(), and initialize().
bendRadius_m
double CSRIGFWakeFunction::bendRadius_m private
Definition at line 77 of file CSRIGFWakeFunction.h.
Referenced by apply(), calcPsi(), calculateContributionAfter(), calculateGreenFunction(), and initialize().
Chi_m
std::vector<double> CSRIGFWakeFunction::Chi_m private
Definition at line 58 of file CSRIGFWakeFunction.h.
Referenced by apply(), and calculateGreenFunction().
defaultFilter_m
std::shared_ptr<Filter> CSRIGFWakeFunction::defaultFilter_m private
Definition at line 48 of file CSRIGFWakeFunction.h.
Referenced by CSRIGFWakeFunction().
diffOp_m
Filter* CSRIGFWakeFunction::diffOp_m private
Definition at line 49 of file CSRIGFWakeFunction.h.
Referenced by calculateLineDensity(), and CSRIGFWakeFunction().
dlineDensitydz_m
LineDensity CSRIGFWakeFunction::dlineDensitydz_m private
Definition at line 52 of file CSRIGFWakeFunction.h.
Referenced by calculateContributionAfter(), and calculateLineDensity().
Ez_m
std::vector<double> CSRIGFWakeFunction::Ez_m private
Definition at line 55 of file CSRIGFWakeFunction.h.
Referenced by apply(), calculateContributionAfter(), and calculateContributionInside().
FieldBegin_m
double CSRIGFWakeFunction::FieldBegin_m private
Definition at line 71 of file CSRIGFWakeFunction.h.
Referenced by apply(), and initialize().
filters_m
std::vector<Filter*> CSRIGFWakeFunction::filters_m private
Definition at line 47 of file CSRIGFWakeFunction.h.
Referenced by calculateLineDensity(), and CSRIGFWakeFunction().
Grn_m
std::vector<double> CSRIGFWakeFunction::Grn_m private
Definition at line 61 of file CSRIGFWakeFunction.h.
Referenced by apply(), calculateContributionInside(), and calculateGreenFunction().
Length_m
double CSRIGFWakeFunction::Length_m private
Definition at line 74 of file CSRIGFWakeFunction.h.
Referenced by initialize().
lineDensity_m
LineDensity CSRIGFWakeFunction::lineDensity_m private
Definition at line 51 of file CSRIGFWakeFunction.h.
Referenced by apply(), calculateContributionAfter(), calculateContributionInside(), calculateGreenFunction(), and calculateLineDensity().
Psi_m
std::vector<double> CSRIGFWakeFunction::Psi_m private
Definition at line 64 of file CSRIGFWakeFunction.h.
Referenced by apply(), and calculateContributionAfter().
totalBendAngle_m
double CSRIGFWakeFunction::totalBendAngle_m private
Definition at line 81 of file CSRIGFWakeFunction.h.
Referenced by apply(), calculateContributionAfter(), calculateContributionInside(), and initialize().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Solvers/CSRIGFWakeFunction.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Solvers/CSRIGFWakeFunction.cpp