OPAL (Object Oriented Parallel Accelerator Library): Point3D Class Reference
Point3D Class Reference
A point in 3 dimensions.
#include <EMField.h>
Public Member Functions
Point3D (double x, double y, double z)
Constructor.
double getX () const
Return coordinate.
double getY () const
Return coordinate.
double getZ () const
Return coordinate.
Private Attributes
double x
double y
double z
Detailed Description
A point in 3 dimensions.
Definition at line 33 of file EMField.h.
Constructor & Destructor Documentation
Point3D()
Point3D::Point3D (double x, double y, double z)
Constructor.
Definition at line 31 of file EMField.cpp.
References x, y, and z.
Member Function Documentation
getX()
double Point3D::getX () const
Return coordinate.
Definition at line 34 of file EMField.cpp.
References x.
Referenced by BMultipoleField::Bfield(), and BSingleMultipoleField< order >::Bfield().
getY()
double Point3D::getY () const
Return coordinate.
Definition at line 37 of file EMField.cpp.
References y.
Referenced by BMultipoleField::Bfield(), and BSingleMultipoleField< order >::Bfield().
getZ()
double Point3D::getZ () const
Return coordinate.
Definition at line 40 of file EMField.cpp.
References z.
Member Data Documentation
x
double Point3D::x private
Definition at line 55 of file EMField.h.
Referenced by getX(), and Point3D().
y
double Point3D::y private
Definition at line 55 of file EMField.h.
Referenced by getY(), and Point3D().
z
double Point3D::z private
Definition at line 55 of file EMField.h.
Referenced by getZ(), and Point3D().
The documentation for this class was generated from the following files:
src/Classic/Fields/EMField.h
src/Classic/Fields/EMField.cpp