OPAL (Object Oriented Parallel Accelerator Library): client::error_handler< Iterator > Struct Template Reference
client::error_handler< Iterator > Struct Template Reference
#include <error_handler.hpp>
Classes
struct result
Public Member Functions
error_handler (Iterator first, Iterator last)
template<typename Message , typename What >
void operator() (Message const &message, What const &what, Iterator err_pos) const
Iterator get_pos (Iterator err_pos, int &line) const
std::string get_line (Iterator err_pos) const
Public Attributes
Iterator first
Iterator last
std::vector< Iterator > iters
Detailed Description
template<typename Iterator>
struct client::error_handler< Iterator >
Definition at line 20 of file error_handler.hpp.
Constructor & Destructor Documentation
error_handler()
template<typename Iterator> client::error_handler< Iterator >::error_handler (Iterator first, Iterator last) inline
Definition at line 25 of file error_handler.hpp.
Member Function Documentation
get_line()
template<typename Iterator> std::string client::error_handler< Iterator >::get_line (Iterator err_pos) const inline
Definition at line 77 of file error_handler.hpp.
References client::error_handler< Iterator >::last.
Referenced by client::error_handler< Iterator >::operator()().
get_pos()
template<typename Iterator> Iterator client::error_handler< Iterator >::get_pos (Iterator err_pos, int & line) const inline
Definition at line 51 of file error_handler.hpp.
References client::error_handler< Iterator >::first.
Referenced by client::error_handler< Iterator >::operator()().
operator()()
template<typename Iterator> template<typename Message , typename What > void client::error_handler< Iterator >::operator() (Message const & message, What const & what, Iterator err_pos) const inline
Definition at line 29 of file error_handler.hpp.
References endl(), client::error_handler< Iterator >::get_line(), client::error_handler< Iterator >::get_pos(), and client::error_handler< Iterator >::last.
Member Data Documentation
first
template<typename Iterator> Iterator client::error_handler< Iterator >::first
Definition at line 86 of file error_handler.hpp.
Referenced by client::error_handler< Iterator >::get_pos().
iters
template<typename Iterator> std::vector<Iterator> client::error_handler< Iterator >::iters
Definition at line 88 of file error_handler.hpp.
Referenced by client::parser::expression< Iterator >::expression().
last
template<typename Iterator> Iterator client::error_handler< Iterator >::last
Definition at line 87 of file error_handler.hpp.
Referenced by client::error_handler< Iterator >::get_line(), and client::error_handler< Iterator >::operator()().
The documentation for this struct was generated from the following file:
optimizer/Expression/Parser/error_handler.hpp