OPAL (Object Oriented Parallel Accelerator Library): FieldSpec< T, Dim, M, C > Class Template Reference
FieldSpec< T, Dim, M, C > Class Template Reference
#include <FieldSpec.h>
Public Member Functions
FieldSpec (const FieldLayout< Dim > &layout)
FieldSpec (const FieldLayout< Dim > &layout, const BConds< T, Dim, M, C > &bc, const GuardCellSizes< Dim > &gc)
FieldSpec (const FieldLayout< Dim > &layout, const GuardCellSizes< Dim > &gc, const BConds< T, Dim, M, C > &bc)
FieldSpec (const FieldSpec< T, Dim, M, C > &rhs)
~FieldSpec (void)
const FieldLayout< Dim > & get_Layout (void) const
BConds< T, Dim, M, C > get_BC (void) const
GuardCellSizes< Dim > get_GC (void) const
void set_BC (const BConds< T, Dim, M, C > &bc)
void set_GC (const GuardCellSizes< Dim > &gc)
FieldSpec< T, Dim, M, C > & operator= (const FieldSpec< T, Dim, M, C > &rhs)
Private Attributes
const FieldLayout< Dim > & Layout
BConds< T, Dim, M, C > BC
GuardCellSizes< Dim > GC
Detailed Description
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering>
class FieldSpec< T, Dim, M, C >
Definition at line 27 of file FieldSpec.h.
Constructor & Destructor Documentation
FieldSpec() [1/4]
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> FieldSpec< T, Dim, M, C >::FieldSpec (const FieldLayout< Dim > & layout) inline
Definition at line 34 of file FieldSpec.h.
FieldSpec() [2/4]
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> FieldSpec< T, Dim, M, C >::FieldSpec (const FieldLayout< Dim > & layout, const BConds< T, Dim, M, C > & bc, const GuardCellSizes< Dim > & gc) inline
Definition at line 36 of file FieldSpec.h.
FieldSpec() [3/4]
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> FieldSpec< T, Dim, M, C >::FieldSpec (const FieldLayout< Dim > & layout, const GuardCellSizes< Dim > & gc, const BConds< T, Dim, M, C > & bc) inline
Definition at line 41 of file FieldSpec.h.
FieldSpec() [4/4]
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> FieldSpec< T, Dim, M, C >::FieldSpec (const FieldSpec< T, Dim, M, C > & rhs) inline
Definition at line 46 of file FieldSpec.h.
~FieldSpec()
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> FieldSpec< T, Dim, M, C >::~FieldSpec (void) inline
Definition at line 49 of file FieldSpec.h.
Member Function Documentation
get_BC()
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> BConds<T,Dim,M,C> FieldSpec< T, Dim, M, C >::get_BC (void) const inline
Definition at line 52 of file FieldSpec.h.
References FieldSpec< T, Dim, M, C >::BC.
Referenced by Field< Vector_t, 3, Mesh_t, Center_t >::initialize(), and FieldSpec< T, Dim, M, C >::operator=().
get_GC()
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> GuardCellSizes<Dim> FieldSpec< T, Dim, M, C >::get_GC (void) const inline
Definition at line 53 of file FieldSpec.h.
References FieldSpec< T, Dim, M, C >::GC.
Referenced by Field< Vector_t, 3, Mesh_t, Center_t >::initialize(), and FieldSpec< T, Dim, M, C >::operator=().
get_Layout()
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> const FieldLayout<Dim>& FieldSpec< T, Dim, M, C >::get_Layout (void) const inline
Definition at line 51 of file FieldSpec.h.
References FieldSpec< T, Dim, M, C >::Layout.
Referenced by Field< Vector_t, 3, Mesh_t, Center_t >::initialize(), and FieldSpec< T, Dim, M, C >::operator=().
operator=()
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> FieldSpec<T,Dim,M,C>& FieldSpec< T, Dim, M, C >::operator= (const FieldSpec< T, Dim, M, C > & rhs) inline
Definition at line 57 of file FieldSpec.h.
References FieldSpec< T, Dim, M, C >::BC, endl(), ERRORMSG, FieldSpec< T, Dim, M, C >::GC, FieldSpec< T, Dim, M, C >::get_BC(), FieldSpec< T, Dim, M, C >::get_GC(), FieldSpec< T, Dim, M, C >::get_Layout(), and FieldSpec< T, Dim, M, C >::Layout.
set_BC()
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> void FieldSpec< T, Dim, M, C >::set_BC (const BConds< T, Dim, M, C > & bc) inline
Definition at line 54 of file FieldSpec.h.
References FieldSpec< T, Dim, M, C >::BC.
set_GC()
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> void FieldSpec< T, Dim, M, C >::set_GC (const GuardCellSizes< Dim > & gc) inline
Definition at line 55 of file FieldSpec.h.
References FieldSpec< T, Dim, M, C >::GC.
Member Data Documentation
BC
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> BConds<T,Dim,M,C> FieldSpec< T, Dim, M, C >::BC private
Definition at line 69 of file FieldSpec.h.
Referenced by FieldSpec< T, Dim, M, C >::get_BC(), FieldSpec< T, Dim, M, C >::operator=(), and FieldSpec< T, Dim, M, C >::set_BC().
GC
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> GuardCellSizes<Dim> FieldSpec< T, Dim, M, C >::GC private
Definition at line 70 of file FieldSpec.h.
Referenced by FieldSpec< T, Dim, M, C >::get_GC(), FieldSpec< T, Dim, M, C >::operator=(), and FieldSpec< T, Dim, M, C >::set_GC().
Layout
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> const FieldLayout<Dim>& FieldSpec< T, Dim, M, C >::Layout private
Definition at line 68 of file FieldSpec.h.
Referenced by FieldSpec< T, Dim, M, C >::get_Layout(), and FieldSpec< T, Dim, M, C >::operator=().
The documentation for this class was generated from the following file:
ippl/src/Field/FieldSpec.h