OPAL (Object Oriented Parallel Accelerator Library): BoxParticleCachingPolicy< T, Dim, Mesh > Class Template Reference
BoxParticleCachingPolicy< T, Dim, Mesh > Class Template Reference
#include <BoxParticleCachingPolicy.h>
Classes
struct Offset_t
Public Member Functions
BoxParticleCachingPolicy ()
void setCacheDimension (int d, T length)
void setAllCacheDimensions (T length)
template<class C >
void updateCacheInformation (ParticleSpatialLayout< T, Dim, Mesh, C > &PLayout)
template<class C >
void updateGhostParticles (IpplParticleBase< ParticleSpatialLayout< T, Dim, Mesh, C > > &PData, ParticleSpatialLayout< T, Dim, Mesh, C > &)
Protected Member Functions
~BoxParticleCachingPolicy ()
Private Attributes
T boxDimension [Dim]
bool periodic [2 *Dim]
std::map< unsigned, std::list< std::pair< NDRegion< T, Dim >, Offset_t > > > regions
Detailed Description
template<class T, unsigned Dim, class Mesh>
class BoxParticleCachingPolicy< T, Dim, Mesh >
Definition at line 23 of file BoxParticleCachingPolicy.h.
Constructor & Destructor Documentation
BoxParticleCachingPolicy()
template<class T , unsigned Dim, class Mesh > BoxParticleCachingPolicy< T, Dim, Mesh >::BoxParticleCachingPolicy () inline
Definition at line 25 of file BoxParticleCachingPolicy.h.
References BoxParticleCachingPolicy< T, Dim, Mesh >::boxDimension, Dim, and Attrib::Legacy::Distribution::T.
~BoxParticleCachingPolicy()
template<class T , unsigned Dim, class Mesh > BoxParticleCachingPolicy< T, Dim, Mesh >::~BoxParticleCachingPolicy () inline protected
Definition at line 249 of file BoxParticleCachingPolicy.h.
Member Function Documentation
setAllCacheDimensions()
template<class T , unsigned Dim, class Mesh > void BoxParticleCachingPolicy< T, Dim, Mesh >::setAllCacheDimensions (T length) inline
Definition at line 35 of file BoxParticleCachingPolicy.h.
References BoxParticleCachingPolicy< T, Dim, Mesh >::boxDimension, and Dim.
setCacheDimension()
template<class T , unsigned Dim, class Mesh > void BoxParticleCachingPolicy< T, Dim, Mesh >::setCacheDimension (int d, T length) inline
Definition at line 30 of file BoxParticleCachingPolicy.h.
References BoxParticleCachingPolicy< T, Dim, Mesh >::boxDimension.
updateCacheInformation()
template<class T , unsigned Dim, class Mesh > template<class C > void BoxParticleCachingPolicy< T, Dim, Mesh >::updateCacheInformation (ParticleSpatialLayout< T, Dim, Mesh, C > & PLayout) inline
Definition at line 40 of file BoxParticleCachingPolicy.h.
References BoxParticleCachingPolicy< T, Dim, Mesh >::Offset_t::begin(), RegionLayout< T, Dim, MeshType >::begin_iv(), BoxParticleCachingPolicy< T, Dim, Mesh >::boxDimension, Dim, BoxParticleCachingPolicy< T, Dim, Mesh >::Offset_t::end(), RegionLayout< T, Dim, MeshType >::end_iv(), ParticleLayout< T, Dim >::getBConds(), RegionLayout< T, Dim, MeshType >::getDomain(), ParticleLayout< T, Dim >::getUpdateFlag(), IpplInfo::myNode(), ParticlePeriodicBCond(), BoxParticleCachingPolicy< T, Dim, Mesh >::periodic, BoxParticleCachingPolicy< T, Dim, Mesh >::regions, and RegionLayout< T, Dim, MeshType >::touch_range_rdv().
Referenced by CellParticleCachingPolicy< T, Dim, Mesh >::updateCacheInformation().
updateGhostParticles()
template<class T , unsigned Dim, class Mesh > template<class C > void BoxParticleCachingPolicy< T, Dim, Mesh >::updateGhostParticles (IpplParticleBase< ParticleSpatialLayout< T, Dim, Mesh, C > > & PData, ParticleSpatialLayout< T, Dim, Mesh, C > &) inline
Definition at line 155 of file BoxParticleCachingPolicy.h.
References Communicate::barrier(), BoxParticleCachingPolicy< T, Dim, Mesh >::boxDimension, IpplInfo::Comm, Communicate::COMM_ANY_NODE, Dim, MsgBuffer::getBuffer(), MsgBuffer::getSize(), Hypervolume::n, TagMaker::next_tag(), P_LAYOUT_CYCLE, P_SPATIAL_GHOST_TAG, Communicate::raw_isend(), Communicate::raw_probe_receive(), BoxParticleCachingPolicy< T, Dim, Mesh >::regions, and NDRegion< T, Dim >::touches().
Referenced by CellParticleCachingPolicy< T, Dim, Mesh >::updateGhostParticles().
Member Data Documentation
boxDimension
template<class T , unsigned Dim, class Mesh > T BoxParticleCachingPolicy< T, Dim, Mesh >::boxDimension[Dim] private
Definition at line 260 of file BoxParticleCachingPolicy.h.
Referenced by BoxParticleCachingPolicy< T, Dim, Mesh >::BoxParticleCachingPolicy(), BoxParticleCachingPolicy< T, Dim, Mesh >::setAllCacheDimensions(), BoxParticleCachingPolicy< T, Dim, Mesh >::setCacheDimension(), BoxParticleCachingPolicy< T, Dim, Mesh >::updateCacheInformation(), and BoxParticleCachingPolicy< T, Dim, Mesh >::updateGhostParticles().
periodic
template<class T , unsigned Dim, class Mesh > bool BoxParticleCachingPolicy< T, Dim, Mesh >::periodic[2 *Dim] private
Definition at line 261 of file BoxParticleCachingPolicy.h.
Referenced by BoxParticleCachingPolicy< T, Dim, Mesh >::updateCacheInformation().
regions
template<class T , unsigned Dim, class Mesh > std::map<unsigned, std::list<std::pair<NDRegion<T,Dim>, Offset_t> > > BoxParticleCachingPolicy< T, Dim, Mesh >::regions private
Definition at line 262 of file BoxParticleCachingPolicy.h.
Referenced by BoxParticleCachingPolicy< T, Dim, Mesh >::updateCacheInformation(), and BoxParticleCachingPolicy< T, Dim, Mesh >::updateGhostParticles().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/BoxParticleCachingPolicy.h