OPAL (Object Oriented Parallel Accelerator Library): ippl/src/PETE/IpplExpressions.h File Reference
IpplExpressions.h File Reference
#include "Message/Message.h"
#include "PETE/IpplTypeComputations.h"
#include "PETE/PETE.h"
Classes
struct AnyHolder< T, OP >
struct BoundsHolder< T, D >
struct OperatorTraits< Op >
struct OperatorTraits< OpAssign >
Macros
#define PETE_USER_REDUCTION_CODE
#define PETE_DefineScalarMinMax(Sca)
#define PETE_DefineIPPLScalar(Sca)
#define PETE_DefineBinaryWithVSTScalars(Fun, Op, Sca)
#define PETE_DefineTrinaryWithVSTScalars(Fun, Op, Sca)
#define PETE_DefineVSTScalar(Sca)
Functions
PETE_DefineUnary (Abs,(0< a ? a :-a), FnAbs) inline double PETE_apply(FnAbs
template<class T >
PETE_TUTree< FnAbs, typename T::PETE_Expr_t > abs (const PETE_Expr< T > &l)
PETE_DefineUnary (conj,(conj(a)), FnConj) PETE_DefineUnary(arg
arg (a))
FnArg PETE_DefineUnary (norm,(norm(a)), FnNorm) PETE_DefineUnary(real
FnArg real (a))
FnArg FnReal PETE_DefineUnary (imag,(imag(a)), FnImag) PETE_DefineUnary(sign
FnArg FnReal sign (a))
FnArg FnReal FnSign PETE_DefineUnary (trace,(trace(a)), FnTrace) PETE_DefineUnary(transpose
FnArg FnReal FnSign transpose (a))
FnArg FnReal FnSign FnTranspose PETE_DefineUnary (det,(det(a)), FnDet) PETE_DefineUnary(cofactors
FnArg FnReal FnSign FnTranspose cofactors (a))
short Min (const short &a, const short &b)
short Max (const short &a, const short &b)
int Min (const int &a, const int &b)
int Max (const int &a, const int &b)
long Min (const long &a, const long &b)
long Max (const long &a, const long &b)
float Min (const float &a, const float &b)
float Max (const float &a, const float &b)
double Min (const double &a, const double &b)
double Max (const double &a, const double &b)
PETE_DefineBinary (Min,(Min(a, b)), FnMin) PETE_DefineBinary(Max
Max (a, b))
FnMax PETE_DefineBinary (dot,(dot(a, b)), FnDot) PETE_DefineBinary(dotdot
FnMax dotdot (a, b))
FnMax FnDotDot PETE_DefineBinary (outerProduct,(outerProduct(a, b)), FnOuterProduct) PETE_DefineBinary(cross
FnMax FnDotDot cross (a, b))
FnMax FnDotDot FnCross PETE_DefineBinarySynonym (lt, OpLT) PETE_DefineBinarySynonym(gt
FnMax FnDotDot FnCross OpGT PETE_DefineBinarySynonym (le, OpLE) PETE_DefineBinarySynonym(ge
FnMax FnDotDot FnCross OpGT OpGE PETE_DefineBinarySynonym (eq, OpEQ) PETE_DefineBinarySynonym(ne
PETE_DefineBinaryWithScalars (Min, FnMin, short) PETE_DefineBinaryWithScalars(Max
short PETE_DefineBinaryWithScalars (dot, FnDot, short) PETE_DefineBinaryWithScalars(dotdot
short short PETE_DefineBinaryWithScalars (outerProduct, FnOuterProduct, short) PETE_DefineBinaryWithScalars(cross
short short short PETE_DefineBinaryWithScalars (lt, OpLT, short) PETE_DefineBinaryWithScalars(le
short short short short PETE_DefineBinaryWithScalars (gt, OpGT, short) PETE_DefineBinaryWithScalars(ge
short short short short short PETE_DefineBinaryWithScalars (eq, OpEQ, short) PETE_DefineBinaryWithScalars(ne
short short short short short short PETE_DefineBinaryWithScalars (Min, FnMin, int) PETE_DefineBinaryWithScalars(Max
short short short short short short int PETE_DefineBinaryWithScalars (dot, FnDot, int) PETE_DefineBinaryWithScalars(dotdot
short short short short short short int int PETE_DefineBinaryWithScalars (outerProduct, FnOuterProduct, int) PETE_DefineBinaryWithScalars(cross
short short short short short short int int int PETE_DefineBinaryWithScalars (lt, OpLT, int) PETE_DefineBinaryWithScalars(le
short short short short short short int int int int PETE_DefineBinaryWithScalars (gt, OpGT, int) PETE_DefineBinaryWithScalars(ge
short short short short short short int int int int int PETE_DefineBinaryWithScalars (eq, OpEQ, int) PETE_DefineBinaryWithScalars(ne
short short short short short short int int int int int int PETE_DefineBinaryWithScalars (Min, FnMin, long) PETE_DefineBinaryWithScalars(Max
short short short short short short int int int int int int long PETE_DefineBinaryWithScalars (dot, FnDot, long) PETE_DefineBinaryWithScalars(dotdot
short short short short short short int int int int int int long long PETE_DefineBinaryWithScalars (outerProduct, FnOuterProduct, long) PETE_DefineBinaryWithScalars(cross
short short short short short short int int int int int int long long long PETE_DefineBinaryWithScalars (lt, OpLT, long) PETE_DefineBinaryWithScalars(le
short short short short short short int int int int int int long long long long PETE_DefineBinaryWithScalars (gt, OpGT, long) PETE_DefineBinaryWithScalars(ge
short short short short short short int int int int int int long long long long long PETE_DefineBinaryWithScalars (eq, OpEQ, long) PETE_DefineBinaryWithScalars(ne
short short short short short short int int int int int int long long long long long long PETE_DefineBinaryWithScalars (Min, FnMin, float) PETE_DefineBinaryWithScalars(Max
short short short short short short int int int int int int long long long long long long float PETE_DefineBinaryWithScalars (dot, FnDot, float) PETE_DefineBinaryWithScalars(dotdot
short short short short short short int int int int int int long long long long long long float float PETE_DefineBinaryWithScalars (outerProduct, FnOuterProduct, float) PETE_DefineBinaryWithScalars(cross
short short short short short short int int int int int int long long long long long long float float float PETE_DefineBinaryWithScalars (lt, OpLT, float) PETE_DefineBinaryWithScalars(le
short short short short short short int int int int int int long long long long long long float float float float PETE_DefineBinaryWithScalars (gt, OpGT, float) PETE_DefineBinaryWithScalars(ge
short short short short short short int int int int int int long long long long long long float float float float float PETE_DefineBinaryWithScalars (eq, OpEQ, float) PETE_DefineBinaryWithScalars(ne
short short short short short short int int int int int int long long long long long long float float float float float float PETE_DefineBinaryWithScalars (Min, FnMin, double) PETE_DefineBinaryWithScalars(Max
short short short short short short int int int int int int long long long long long long float float float float float float double PETE_DefineBinaryWithScalars (dot, FnDot, double) PETE_DefineBinaryWithScalars(dotdot
short short short short short short int int int int int int long long long long long long float float float float float float double double PETE_DefineBinaryWithScalars (outerProduct, FnOuterProduct, double) PETE_DefineBinaryWithScalars(cross
short short short short short short int int int int int int long long long long long long float float float float float float double double double PETE_DefineBinaryWithScalars (lt, OpLT, double) PETE_DefineBinaryWithScalars(le
short short short short short short int int int int int int long long long long long long float float float float float float double double double double PETE_DefineBinaryWithScalars (gt, OpGT, double) PETE_DefineBinaryWithScalars(ge
short short short short short short int int int int int int long long long long long long float float float float float float double double double double double PETE_DefineBinaryWithScalars (eq, OpEQ, double) PETE_DefineBinaryWithScalars(ne
short short short short short short int int int int int int long long long long long long float float float float float float double double double double double double PETE_DefineScalar (std::complex< double >) PETE_DefineBinaryWithScalars(eq
short short short short short short int int int int int int long long long long long long float float float float float float double double double double double double std::complex< double > PETE_DefineBinaryWithScalars (ne, OpNE, std::complex< double >) template< class T1
short short short short short short int int int int int int long long long long long long float float float float float float double double double double double double std::complex< double > unsigned class T2 inline PETE_TBTree< OpAdd, PETE_Scalar< Vektor< T1, Dim > >, T2::PETE_Expr_t > operator+ (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpAdd, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator+ (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpSubtract, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator- (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpSubtract, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator- (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpMultipply, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator* (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpMultipply, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator* (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpDivide, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator/ (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpDivide, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator/ (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpMod, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator% (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpMod, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator% (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpLT, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator< (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpLT, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator< (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpLE, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator<= (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpLE, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator<= (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpGT, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator> (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpGT, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator> (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpGE, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator>= (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpGE, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator>= (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpEQ, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator== (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpEQ, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator== (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpNE, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator!= (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpNE, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator!= (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpAnd, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator && (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpAnd, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator && (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpOr, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator|| (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpOr, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator|| (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpBitwiseAnd, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator & (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpBitwiseAnd, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator & (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpBitwiseOr, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator| (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpBitwiseOr, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator| (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpBitwiseXor, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > operator^ (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpBitwiseXor, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > operator^ (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnCopysign, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > copysign (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnCopysign, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > copysign (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnLdexp, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > ldexp (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnLdexp, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > ldexp (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnPow, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > pow (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnPow, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > pow (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnFmod, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > fmod (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnFmod, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > fmod (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnArcTan2, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > atan2 (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnArcTan2, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > atan2 (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class Cond_t , class True_t , class T , unsigned Dim>
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< Vektor< T, Dim > > > where (const PETE_Expr< Cond_t > &c, const PETE_Expr< True_t > &t, const Vektor< T, Dim > &f)
template<class Cond_t , class T , unsigned Dim, class False_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< Vektor< T, Dim > >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > &c, const Vektor< T, Dim > &t, const PETE_Expr< False_t > &f)
template<class Cond_t , class T , unsigned Dim>
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< Vektor< T, Dim > >, PETE_Scalar< Vektor< T, Dim > > > where (const PETE_Expr< Cond_t > &c, const Vektor< T, Dim > &t, const Vektor< T, Dim > &f)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnMin, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > Min (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnMin, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > Min (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnMax, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > Max (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnMax, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > Max (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnDot, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > dot (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnDot, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > dot (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnDotDot, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > dotdot (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnDotDot, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > dotdot (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnOuterProduct, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > outerProduct (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnOuterProduct, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > outerProduct (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnCross, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > cross (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnCross, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > cross (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpLT, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > lt (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpLT, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > lt (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpLE, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > le (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpLE, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > le (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpGT, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > gt (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpGT, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > gt (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpGE, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > ge (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpGE, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > ge (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpEQ, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > eq (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpEQ, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > eq (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpNE, PETE_Scalar< Vektor< T1, Dim > >, typename T2::PETE_Expr_t > ne (const Vektor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpNE, typename T1::PETE_Expr_t, PETE_Scalar< Vektor< T2, Dim > > > ne (const PETE_Expr< T1 > &l, const Vektor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpAdd, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator+ (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpAdd, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator+ (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpSubtract, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator- (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpSubtract, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator- (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpMultipply, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator* (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpMultipply, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator* (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpDivide, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator/ (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpDivide, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator/ (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpMod, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator% (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpMod, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator% (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpLT, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator< (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpLT, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator< (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpLE, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator<= (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpLE, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator<= (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpGT, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator> (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpGT, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator> (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpGE, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator>= (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpGE, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator>= (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpEQ, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator== (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpEQ, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator== (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpNE, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator!= (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpNE, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator!= (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpAnd, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator && (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpAnd, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator && (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpOr, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator|| (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpOr, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator|| (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpBitwiseAnd, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator & (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpBitwiseAnd, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator & (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpBitwiseOr, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator| (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpBitwiseOr, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator| (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpBitwiseXor, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator^ (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpBitwiseXor, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > operator^ (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnCopysign, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > copysign (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnCopysign, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > copysign (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnLdexp, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > ldexp (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnLdexp, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > ldexp (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnPow, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > pow (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnPow, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > pow (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnFmod, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > fmod (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnFmod, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > fmod (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnArcTan2, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > atan2 (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnArcTan2, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > atan2 (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class Cond_t , class True_t , class T , unsigned Dim>
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< SymTenzor< T, Dim > > > where (const PETE_Expr< Cond_t > &c, const PETE_Expr< True_t > &t, const SymTenzor< T, Dim > &f)
template<class Cond_t , class T , unsigned Dim, class False_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< SymTenzor< T, Dim > >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > &c, const SymTenzor< T, Dim > &t, const PETE_Expr< False_t > &f)
template<class Cond_t , class T , unsigned Dim>
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< SymTenzor< T, Dim > >, PETE_Scalar< SymTenzor< T, Dim > > > where (const PETE_Expr< Cond_t > &c, const SymTenzor< T, Dim > &t, const SymTenzor< T, Dim > &f)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnMin, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > Min (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnMin, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > Min (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnMax, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > Max (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnMax, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > Max (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnDot, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > dot (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnDot, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > dot (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnDotDot, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > dotdot (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnDotDot, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > dotdot (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnOuterProduct, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > outerProduct (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnOuterProduct, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > outerProduct (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnCross, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > cross (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnCross, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > cross (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpLT, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > lt (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpLT, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > lt (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpLE, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > le (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpLE, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > le (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpGT, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > gt (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpGT, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > gt (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpGE, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > ge (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpGE, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > ge (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpEQ, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > eq (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpEQ, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > eq (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpNE, PETE_Scalar< SymTenzor< T1, Dim > >, typename T2::PETE_Expr_t > ne (const SymTenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpNE, typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor< T2, Dim > > > ne (const PETE_Expr< T1 > &l, const SymTenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpAdd, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator+ (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpAdd, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator+ (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpSubtract, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator- (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpSubtract, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator- (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpMultipply, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator* (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpMultipply, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator* (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpDivide, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator/ (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpDivide, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator/ (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpMod, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator% (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpMod, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator% (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpLT, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator< (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpLT, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator< (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpLE, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator<= (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpLE, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator<= (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpGT, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator> (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpGT, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator> (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpGE, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator>= (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpGE, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator>= (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpEQ, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator== (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpEQ, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator== (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpNE, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator!= (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpNE, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator!= (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpAnd, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator && (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpAnd, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator && (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpOr, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator|| (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpOr, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator|| (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpBitwiseAnd, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator & (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpBitwiseAnd, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator & (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpBitwiseOr, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator| (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpBitwiseOr, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator| (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpBitwiseXor, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > operator^ (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpBitwiseXor, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > operator^ (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnCopysign, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > copysign (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnCopysign, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > copysign (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnLdexp, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > ldexp (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnLdexp, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > ldexp (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnPow, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > pow (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnPow, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > pow (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnFmod, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > fmod (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnFmod, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > fmod (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnArcTan2, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > atan2 (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnArcTan2, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > atan2 (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class Cond_t , class True_t , class T , unsigned Dim>
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< Tenzor< T, Dim > > > where (const PETE_Expr< Cond_t > &c, const PETE_Expr< True_t > &t, const Tenzor< T, Dim > &f)
template<class Cond_t , class T , unsigned Dim, class False_t >
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< Tenzor< T, Dim > >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > &c, const Tenzor< T, Dim > &t, const PETE_Expr< False_t > &f)
template<class Cond_t , class T , unsigned Dim>
PETE_TTTree< OpWhere, typename Cond_t::PETE_Expr_t, PETE_Scalar< Tenzor< T, Dim > >, PETE_Scalar< Tenzor< T, Dim > > > where (const PETE_Expr< Cond_t > &c, const Tenzor< T, Dim > &t, const Tenzor< T, Dim > &f)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnMin, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > Min (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnMin, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > Min (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnMax, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > Max (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnMax, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > Max (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnDot, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > dot (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnDot, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > dot (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnDotDot, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > dotdot (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnDotDot, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > dotdot (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnOuterProduct, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > outerProduct (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnOuterProduct, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > outerProduct (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< FnCross, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > cross (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< FnCross, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > cross (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpLT, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > lt (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpLT, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > lt (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpLE, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > le (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpLE, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > le (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpGT, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > gt (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpGT, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > gt (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpGE, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > ge (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpGE, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > ge (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpEQ, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > eq (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpEQ, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > eq (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
template<class T1 , unsigned Dim, class T2 >
PETE_TBTree< OpNE, PETE_Scalar< Tenzor< T1, Dim > >, typename T2::PETE_Expr_t > ne (const Tenzor< T1, Dim > &l, const PETE_Expr< T2 > &r)
template<class T1 , class T2 , unsigned Dim>
PETE_TBTree< OpNE, typename T1::PETE_Expr_t, PETE_Scalar< Tenzor< T2, Dim > > > ne (const PETE_Expr< T1 > &l, const Tenzor< T2, Dim > &r)
PETE_DefineAssign ((a=Min(a, b)),(a=Min(a, b.value)), OpMinAssign) PETE_DefineAssign((a
template<class T1 , class T2 >
void minmax (const PETE_Expr< T1 > &expr, T2 &minval, T2 &maxval)
template<class T1 , class T2 >
bool any (const PETE_Expr< T1 > &expr, T2 val)
template<class T1 , class T2 , class Op >
bool any (const PETE_Expr< T1 > &expr, T2 val, Op op)
template<class T1 , class T2 , unsigned int D>
void bounds (const PETE_Expr< T1 > &expr, Vektor< T2, D > &minval, Vektor< T2, D > &maxval)
template<class T , class TP >
PETEUnaryReturn< T, OpParens< TP > >::type PETE_apply (OpParens< TP > op, const T &a)
Variables
std::complex< double > a
FnMax
short FnDotDot
short short FnDot
short short short OpLE
short short short short OpGE
short short short short short OpNE
short short short short short short int int int int int int long long long long long long float float float float float float double double double double double double OpEQ
short short short short short short int int int int int int long long long long long long float float float float float float double double double double double double std::complex< double > unsigned Dim
Macro Definition Documentation
PETE_DefineBinaryWithVSTScalars
#define PETE_DefineBinaryWithVSTScalars (Fun, Op, Sca)
Value:
template<class T1, unsigned Dim, class T2>                                  \
inline PETE_TBTree<Op, PETE_Scalar< Sca<T1, Dim> >,                         \
  typename T2::PETE_Expr_t>                                                 \
Fun(const Sca<T1, Dim> &l, const PETE_Expr<T2>& r)                          \
{                                                                           \
  typedef PETE_TBTree<Op, PETE_Scalar< Sca<T1, Dim> >,                      \
    typename T2::PETE_Expr_t> ret;                                          \
  return ret(PETE_Scalar< Sca<T1, Dim> >(l),                                \
    r.PETE_unwrap().MakeExpression());                                      \
}                                                                           \
template<class T1, class T2, unsigned Dim>                                  \
inline PETE_TBTree<Op, typename T1::PETE_Expr_t,                            \
  PETE_Scalar< Sca<T2, Dim> > >                                             \
Fun(const PETE_Expr<T1>& l, const Sca<T2, Dim> &r)                          \
{                                                                           \
  typedef PETE_TBTree<Op, typename T1::PETE_Expr_t,                         \
    PETE_Scalar< Sca<T2, Dim> > > ret;                                      \
  return ret(l.PETE_unwrap().MakeExpression(),                              \
    PETE_Scalar< Sca<T2, Dim> >(r));                                        \
}
PETE_DefineIPPLScalar
#define PETE_DefineIPPLScalar (Sca)
Value:
PETE_DefineBinaryWithScalars(Min, FnMin, Sca)                               \
PETE_DefineBinaryWithScalars(Max, FnMax, Sca)                               \
PETE_DefineBinaryWithScalars(dot, FnDot, Sca)                               \
PETE_DefineBinaryWithScalars(dotdot, FnDotDot, Sca)                         \
PETE_DefineBinaryWithScalars(outerProduct, FnOuterProduct, Sca)             \
PETE_DefineBinaryWithScalars(cross, FnDot, Sca)                             \
PETE_DefineBinaryWithScalars(lt, OpLT, Sca)                                 \
PETE_DefineBinaryWithScalars(le, OpLE, Sca)                                 \
PETE_DefineBinaryWithScalars(gt, OpGT, Sca)                                 \
PETE_DefineBinaryWithScalars(ge, OpGE, Sca)                                 \
PETE_DefineBinaryWithScalars(eq, OpEQ, Sca)                                 \
PETE_DefineBinaryWithScalars(ne, OpNE, Sca)
Definition at line 121 of file IpplExpressions.h.
PETE_DefineScalarMinMax
#define PETE_DefineScalarMinMax (Sca)
Value:
inline Sca                                                                \
Min(const Sca& a, const Sca& b)                                           \
{                                                                         \
  return (a<b ? a : b);                                                   \
}                                                                         \
inline Sca                                                                \
Max(const Sca& a, const Sca& b)                                           \
{                                                                         \
  return (b<a ? a : b);                                                   \
}
Definition at line 87 of file IpplExpressions.h.
PETE_DefineTrinaryWithVSTScalars
#define PETE_DefineTrinaryWithVSTScalars (Fun, Op, Sca)
PETE_DefineVSTScalar
#define PETE_DefineVSTScalar (Sca)
PETE_USER_REDUCTION_CODE
#define PETE_USER_REDUCTION_CODE
Value:
R global_ret;                                                             \
  reduce_masked(ret, global_ret, acc_op, 0 < n );                           \
  ret = global_ret;
Definition at line 32 of file IpplExpressions.h.
Function Documentation
abs()
template<class T > PETE_TUTree<FnAbs, typename T::PETE_Expr_t> abs (const PETE_Expr< T > & l) inline
Definition at line 62 of file IpplExpressions.h.
References PETE_Expr< WrappedExpr >::PETE_unwrap().
Referenced by Expressions::AbsMax(), Bend2D::adjustFringeFields(), Stepper< FieldFunction, Arguments... >::advance(), cmp_diff::almost_eq(), cmp_ulp_obsolete::almost_eq(), cmp_ulp::almost_eq(), cmp_diff::almost_eq_zero(), cmp_ulp_obsolete::almost_eq_zero(), cmp_ulp::almost_eq_zero(), IndexMap::almostEqual(), RelativeFFTLowPassFilter::apply(), GreenWakeFunction::apply(), VariableRFCavity::apply(), VariableRFCavityFringeField::apply(), Distribution::applyEmissModelAstra(), TrimCoil::applyField(), ScatteringPhysics::applyRandomRotation(), Cyclotron::applyTrimCoil(), FDoubleEigen< N >::balance(), Offset::bends(), PartBunchBase< double, 3 >::boundp(), PartBunchBase< double, 3 >::boundp_destroyCycl(), PartBunchBase< double, 3 >::boundp_destroyT(), RelativeFFTLowPassFilter::calc_derivative(), BendBase::calcDesignRadius(), PartBunchBase< double, 3 >::calcGammas(), PartBunchBase< double, 3 >::calcNumPartsOutside(), CSRWakeFunction::calcPsi(), CSRIGFWakeFunction::calcPsi(), coordinatetransform::CoordinateTransform::calcSCoordinate(), PluginElement::calculateIncidentAngle(), Bend2D::calculateMapField(), FFTPACK< T >::callFFT(), cdiv(), Ring::checkAndClose(), OrbitThreader::checkElementLengths(), Distribution::checkEmissionParameters(), Distribution::checkFileMomentum(), ParallelCyclotronTracker::checkFileMomentum(), DumpFields::checkInt(), DumpEMFields::checkInt(), Fieldmap::checkMap(), Ring::checkMidplane(), SectorMagneticFieldMap::IO::comparator(), EllipticDomain::compute(), OpalBeamline::compute3DLattice(), mslang::Ellipse::computeBoundingBox(), ScatteringPhysics::computeCoulombScattering(), DistributionMoments::computePercentiles(), ClosedOrbitFinder< Value_type, Size_type, Stepper >::computeTune(), MapGenerator< Value_type, Size_type, Series_type, Map_type, Hamiltonian_type, Space_charge_type >::computeTunes(), OpalVariableRFCavityFringeField::convertToUnsigned(), Distribution::createDistributionMultiGauss(), PeakFinder::createHistogram_m(), Distribution::createMatchedGaussDistribution(), DistributionMoments::determinePercentilesDetail(), Septum::doCheck(), AmrParticleBase< PLayout >::domainMapping(), Septum::doPreCheck(), Probe::doPreCheck(), Stripper::doPreCheck(), CCollimator::doPreCheck(), FDoubleEigen< N >::elmhes(), Bend2D::estimateFieldAdjustmentStep(), ParallelTTracker::execute(), ThickTracker::fillGaps_m(), Bend2D::findBendEffectiveLength(), Bend2D::findBendStrength(), RBend::findChordLength(), Sequence::findDriftLength(), Bend2D::findIdealBendParameters(), ParallelTTracker::findStartPosition(), FLUMatrix< T, N >::FLUMatrix(), FM1DProfile1::FM1DProfile1(), FM3DMagnetoStaticExtended::FM3DMagnetoStaticExtended(), Distribution::generateAstraFlattopT(), Distribution::generateBinomial(), Distribution::generateGaussZ(), Distribution::generateLongFlattopT(), TravelingWave::getAutoPhaseEstimate(), RFCavity::getAutoPhaseEstimate(), Rotation3D::getAxis(), PartBins::getBin(), MultipoleTBase::getBs(), MultipoleTBase::getBx(), MultipoleTBase::getBz(), UniformCartesian< Dim, MFLOAT >::getCellRangeVolume(), Cartesian< Dim, MFLOAT >::getCellRangeVolume(), Util::getChargeString(), FM2DMagnetoStatic::getFieldstrength(), VerticalFFAMagnet::getFieldValue(), FM3DMagnetoStaticExtended::getIndex(), Util::getLengthString(), DistributionMoments::getMaxR(), Astra1DDynamic::getOnaxisEz(), Astra1DDynamic_fast::getOnaxisEz(), FM3DH5BlockBase::getOnaxisEz(), Bend2D::getOutline(), CavityAutophaser::getPhaseAtMaxEnergy(), getQuaternion(), ParallelCyclotronTracker::getQuaternionTwoVectors(), IndexMap::getRange(), Bend2D::getSurfaceMesh(), Offset::getTheta(), Util::getTimeString(), UniformCartesian< Dim, MFLOAT >::getVertRangeVolume(), Cartesian< Dim, MFLOAT >::getVertRangeVolume(), Distribution::getWeight(), RootFinderForCSR::hasPositiveRealRoots(), FDoubleEigen< N >::hqr(), FDoubleEigen< N >::hqr2(), TravelingWave::initialise(), RBend3D::initialise(), RFCavity::initialise(), CSRIGFWakeFunction::initialize(), CSRWakeFunction::initialize(), SigmaGenerator::initialize(), OpalFilter::initOpalFilter(), Bend2D::inMagnetCentralRegion(), Bend2D::inMagnetEntranceRegion(), Bend2D::inMagnetExitRegion(), MultipoleTBase::insideAperture(), MultipoleT::insideAperture(), Bend2D::isFieldZero(), FM3DMagnetoStaticExtended::isInside(), mslang::Rectangle::isInside(), mslang::BoundingBox2D::isInside(), Monitor::isInside(), Bend2D::isInside(), ElementBase::isInsideTransverse(), Mesher::isPointOnLine(), Mesher::isPotentialEdgeIntersected(), Quaternion::isPure(), Quaternion::isUnit(), EllipticDomain::linearInterpolation(), ArbitraryDomain::linearInterpolation(), BoxCornerDomain::linearInterpolation(), ludcmp(), LUMatrix< T >::LUMatrix(), SocialNetworkGraph< TopoDiscoveryStrategy_t >::manhattenDistance(), LOMB_class::moment(), Individual::new_gene(), MapAnalyser::normalizeEigen_m(), ParallelCyclotronTracker::normalizeQuaternion(), ParallelCyclotronTracker::normalizeVector(), MaxNormRadialPeak::operator()(), GreenWakeFunction::Wake::operator()(), operator==(), OrbitThreader::OrbitThreader(), mslang::Shear::print(), TrackRun::print(), Beam::print(), PartBunchBase< double, 3 >::print(), Distribution::printDistFlattop(), Distribution::printDistGauss(), Distribution::printEmissionModelAstra(), Distribution::printEmissionModelNone(), EllipticDomain::quadraticInterpolation(), BoxCornerDomain::quadraticInterpolation(), Quaternion::Quaternion(), Astra1D_fast::readFieldData(), Bend2D::readFieldMap(), FM1DElectroStatic::readFileData(), FM1DMagnetoStatic::readFileData(), FM1DDynamic::readFileData(), FM1DElectroStatic_fast::readFileData(), FM1DMagnetoStatic_fast::readFileData(), FM1DDynamic_fast::readFileData(), FM3DMagnetoStaticExtended::readMap(), Astra1DElectroStatic::readMap(), Astra1DMagnetoStatic::readMap(), FM2DElectroStatic::readMap(), FM2DMagnetoStatic::readMap(), FM3DMagnetoStatic::readMap(), Astra1DDynamic::readMap(), FM3DDynamic::readMap(), FM2DDynamic::readMap(), OrbitThreader::registerElement(), OpalBeamline::save3DInput(), OpalBeamline::save3DLattice(), ParallelTTracker::selectDT(), Bend2D::setBendEffectiveLength(), interpolation::NDGrid::setConstantSpacing(), interpolation::ThreeDGrid::setConstantSpacing(), BendBase::setDesignEnergy(), PluginElement::setDimensions(), FFTBase< 1U, T >::setDirectionName(), Distribution::setDistParametersBinomial(), Distribution::setDistParametersFlattop(), Distribution::setDistParametersGauss(), Distribution::setDistParametersMultiGauss(), Bend2D::setEngeOriginDelta(), Bend2D::setFieldCalcParam(), BendBase::setFullGap(), Bend2D::setK1(), MultipoleTBase::setLength(), MultipoleT::setLength(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), TrackRun::setupCyclotronTracker(), Distribution::setupEmissionModelAstra(), Distribution::setupEmissionModelNone(), Distribution::setupEmissionModelNonEquil(), Distribution::setupParticleBins(), SigmaGenerator::SigmaGenerator(), BSingleMultipoleField< order >::size(), FM3DMagnetoStaticExtended::smoothData(), PartBins::sortArray(), AmrBoxLib::tagForChargeDensity_m(), AmrBoxLib::tagForEfield_m(), AmrBoxLib::tagForPotentialStrength_m(), Expressions::Tgauss(), Util::toStringWithThousandSep(), OrbitThreader::trackBack(), matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_(), ThickTracker::visitSBend(), Werrf(), and ParallelTTracker::writePhaseSpace().
any() [1/2]
template<class T1 , class T2 > bool any (const PETE_Expr< T1 > & expr, T2 val) inline
Definition at line 409 of file IpplExpressions.h.
References OpEQ, PETE_Expr< WrappedExpr >::PETE_unwrap(), Reduction(), and AnyHolder< T, OP >::Test.
Referenced by OpalParser::getHint().
any() [2/2]
template<class T1 , class T2 , class Op > bool any (const PETE_Expr< T1 > & expr, T2 val, Op op) inline
Definition at line 421 of file IpplExpressions.h.
References PETE_Expr< WrappedExpr >::PETE_unwrap(), Reduction(), and AnyHolder< T, OP >::Test.
arg()
arg (a)
Referenced by MapGenerator< Value_type, Size_type, Series_type, Map_type, Hamiltonian_type, Space_charge_type >::computeTunes(), Expressions::SUnary< T, U >::evaluate(), Expressions::AUnary< T, U >::evaluate(), Expressions::ASUnary< T >::evaluate(), NativeHashGenerator::generate(), client::code_gen::requirements::operator()(), client::code_gen::StackEvaluator::operator()(), SubBareField< T, Dim, S >::operator()(), IndexedBareField< T, Dim, Brackets >::operator()(), operator-(), Expressions::parseRealConstArray(), LOMB_class::period(), PYBIND11_MODULE(), and OpalSimulation::run().
atan2() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnArcTan2 , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> atan2 (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
Referenced by Ring::appendElement(), ScatteringPhysics::applyRotation(), matheval::detail::grammar< real_t, Iterator >::bfunc_::bfunc_(), ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), ParallelCyclotronTracker::calculateAngle(), PartBunchBase< double, 3 >::calculateAngle(), ParallelCyclotronTracker::calculateAngle2(), Bend2D::calculateBendAngle(), Bend2D::calculateRefTrajectory(), mslang::Ellipse::computeBoundingBox(), SectorField::convertToPolar(), RealDiracMatrix::diagonalize(), Bend2D::findIdealBendParameters(), Distribution::generateBinomial(), mslang::AffineTransformation::getAngle(), Rotation3D::getAxis(), ScalingFFAMagnet::getFieldValue(), Bend2D::getOutline(), Ring::getRotationStartToEnd(), Util::getTaitBryantAngles(), Offset::getTheta(), RBend3D::initialise(), Bend2D::inMagnetCentralRegion(), LOMB_class::period(), OpalElement::printMultipoleStrength(), Bend2D::setFieldCalcParam(), RBend3D::trackRefParticleThrough(), and RealDiracMatrix::update().
atan2() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnArcTan2 , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > atan2 (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
atan2() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnArcTan2 , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> atan2 (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
atan2() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnArcTan2 , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > atan2 (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
atan2() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnArcTan2 , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> atan2 (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
atan2() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnArcTan2 , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > atan2 (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
bounds()
template<class T1 , class T2 , unsigned int D> void bounds (const PETE_Expr< T1 > & expr, Vektor< T2, D > & minval, Vektor< T2, D > & maxval) inline
Definition at line 500 of file IpplExpressions.h.
References BoundsHolder< T, D >::a, BoundsHolder< T, D >::b, PETE_Expr< WrappedExpr >::PETE_unwrap(), and Reduction().
Referenced by HashPairBuilder< PBase >::for_each(), and PartBunchBase< double, 3 >::get_PBounds().
cofactors()
FnArg FnReal FnSign FnTranspose cofactors (a)
copysign() [1/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnCopysign , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > copysign (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
copysign() [2/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnCopysign , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> copysign (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
Referenced by OrbitThreader::execute(), Bend2D::findBendStrength(), RBend::findChordLength(), Bend2D::findIdealBendParameters(), Distribution::generateBinomial(), Beam::getChargePerParticle(), FM3DMagnetoStaticExtended::getFieldstrength(), RootFinderForCSR::hasPositiveRealRoots(), RBend3D::initialise(), OrbitThreader::integrate(), Quaternion::Quaternion(), ParallelTTracker::updateRefToLabCSTrafo(), and mslang::Ellipse::writeGnuplot().
copysign() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnCopysign , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> copysign (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
copysign() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnCopysign , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > copysign (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
copysign() [5/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnCopysign , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > copysign (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
copysign() [6/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnCopysign , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> copysign (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
cross() [1/7]
FnMax FnDotDot cross (a , b)
cross() [2/7]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnCross , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> cross (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
cross() [3/7]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnCross , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > cross (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
cross() [4/7]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnCross , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> cross (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
cross() [5/7]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnCross , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > cross (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
cross() [6/7]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnCross , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> cross (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
cross() [7/7]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnCross , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > cross (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
dot() [1/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnDot , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > dot (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
dot() [2/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnDot , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> dot (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
dot() [3/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnDot , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > dot (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
dot() [4/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnDot , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> dot (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
dot() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnDot , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> dot (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
dot() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnDot , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > dot (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
dotdot() [1/7]
FnMax dotdot (a , b)
dotdot() [2/7]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnDotDot , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> dotdot (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
dotdot() [3/7]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnDotDot , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > dotdot (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
dotdot() [4/7]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnDotDot , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > dotdot (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
dotdot() [5/7]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnDotDot , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> dotdot (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
dotdot() [6/7]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnDotDot , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> dotdot (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
dotdot() [7/7]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnDotDot , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > dotdot (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
eq() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpEQ , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> eq (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
eq() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpEQ , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > eq (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
eq() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpEQ , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> eq (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
eq() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpEQ , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > eq (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
eq() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpEQ , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> eq (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
eq() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpEQ , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > eq (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
fmod() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnFmod , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> fmod (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
Referenced by Cyclotron::apply(), ScatteringPhysics::applyRotation(), RFCavity::getAutoPhaseEstimateFallback(), RFCavity::getMomentaKick(), Bend2D::getOutline(), CavityAutophaser::getPhaseAtMaxEnergy(), Util::getTaitBryantAngles(), matheval::detail::grammar< real_t, Iterator >::grammar(), CavityAutophaser::guessCavityPhase(), Bend2D::inMagnetCentralRegion(), Cyclotron::interpolate(), Expressions::Mod(), GlobalFunctions::_fmod::operator()(), CavityAutophaser::optimizeCavityPhase(), and Bend2D::setFieldCalcParam().
fmod() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnFmod , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > fmod (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
fmod() [3/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnFmod , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > fmod (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
fmod() [4/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnFmod , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> fmod (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
fmod() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnFmod , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> fmod (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
fmod() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnFmod , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > fmod (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
ge() [1/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpGE , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > ge (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
ge() [2/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpGE , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> ge (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
ge() [3/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpGE , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > ge (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
ge() [4/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpGE , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> ge (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
ge() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpGE , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> ge (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
ge() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpGE , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > ge (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
gt() [1/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpGT , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > gt (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
gt() [2/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpGT , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> gt (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
gt() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpGT , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> gt (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
gt() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpGT , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > gt (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
gt() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpGT , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> gt (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
gt() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpGT , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > gt (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
ldexp() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnLdexp , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> ldexp (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
ldexp() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnLdexp , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > ldexp (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
ldexp() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnLdexp , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> ldexp (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
ldexp() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnLdexp , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > ldexp (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
ldexp() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnLdexp , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> ldexp (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
ldexp() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnLdexp , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > ldexp (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
le() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpLE , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> le (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
le() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpLE , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > le (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
le() [3/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpLE , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > le (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
le() [4/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpLE , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> le (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
le() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpLE , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> le (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
le() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpLE , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > le (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
lt() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpLT , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> lt (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
lt() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpLT , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > lt (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
lt() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpLT , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> lt (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
lt() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpLT , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > lt (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
lt() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpLT , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> lt (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
lt() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpLT , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > lt (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
Max() [1/12]
short Max (const short & a, const short & b) inline
Definition at line 99 of file IpplExpressions.h.
Max() [2/12]
int Max (const int & a, const int & b) inline
Definition at line 100 of file IpplExpressions.h.
Max() [3/12]
long Max (const long & a, const long & b) inline
Definition at line 101 of file IpplExpressions.h.
Max() [4/12]
float Max (const float & a, const float & b) inline
Definition at line 102 of file IpplExpressions.h.
Max() [5/12]
double Max (const double & a, const double & b) inline
Definition at line 103 of file IpplExpressions.h.
Max() [6/12]
Max (a , b)
Max() [7/12]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnMax , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> Max (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
Max() [8/12]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnMax , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > Max (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
Max() [9/12]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnMax , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> Max (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
Max() [10/12]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnMax , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > Max (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
Max() [11/12]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnMax , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> Max (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
Max() [12/12]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnMax , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > Max (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
Min() [1/11]
short Min (const short & a, const short & b) inline
Definition at line 99 of file IpplExpressions.h.
Min() [2/11]
int Min (const int & a, const int & b) inline
Definition at line 100 of file IpplExpressions.h.
Min() [3/11]
long Min (const long & a, const long & b) inline
Definition at line 101 of file IpplExpressions.h.
Min() [4/11]
float Min (const float & a, const float & b) inline
Definition at line 102 of file IpplExpressions.h.
Min() [5/11]
double Min (const double & a, const double & b) inline
Definition at line 103 of file IpplExpressions.h.
Min() [6/11]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnMin , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> Min (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
Min() [7/11]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnMin , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > Min (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
Min() [8/11]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnMin , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > Min (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
Min() [9/11]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnMin , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> Min (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
Min() [10/11]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnMin , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > Min (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
Min() [11/11]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnMin , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> Min (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
minmax()
template<class T1 , class T2 > void minmax (const PETE_Expr< T1 > & expr, T2 & minval, T2 & maxval) inline
Definition at line 341 of file IpplExpressions.h.
References PETE_Expr< WrappedExpr >::PETE_unwrap(), and Reduction().
ne() [1/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpNE , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > ne (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
ne() [2/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpNE , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> ne (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
ne() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpNE , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> ne (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
ne() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpNE , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > ne (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
ne() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpNE , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> ne (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
ne() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpNE , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > ne (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator &() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpBitwiseAnd , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator& (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator &() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpBitwiseAnd , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator& (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator &() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpBitwiseAnd , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator& (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator &() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpBitwiseAnd , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator& (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator &() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpBitwiseAnd , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator& (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator &() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpBitwiseAnd , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator& (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator &&() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpAnd , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator&& (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator &&() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpAnd , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator&& (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator &&() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpAnd , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator&& (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator &&() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpAnd , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator&& (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator &&() [5/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpAnd , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator&& (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator &&() [6/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpAnd , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator&& (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator!=() [1/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpNE , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator!= (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator!=() [2/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpNE , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator!= (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator!=() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpNE , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator!= (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator!=() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpNE , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator!= (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator!=() [5/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpNE , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator!= (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator!=() [6/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpNE , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator!= (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator%() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpMod , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator% (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator%() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpMod , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator% (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator%() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpMod , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator% (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator%() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpMod , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator% (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator%() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpMod , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator% (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator%() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpMod , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator% (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator*() [1/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpMultipply , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator* (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator*() [2/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpMultipply , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator* (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator*() [3/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpMultipply , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator* (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator*() [4/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpMultipply , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator* (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator*() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpMultipply , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator* (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator*() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpMultipply , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator* (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator+() [1/6]
short short short short short short int int int int int int long long long long long long float float float float float float double double double double double double std::complex<double> unsigned class T2 inline PETE_TBTree< OpAdd , PETE_Scalar< Vektor <T1, Dim> >, T2::PETE_Expr_t> operator+ (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r)
Definition at line 244 of file IpplExpressions.h.
operator+() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpAdd , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator+ (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator+() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpAdd , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator+ (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator+() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpAdd , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator+ (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator+() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpAdd , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator+ (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator+() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpAdd , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator+ (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator-() [1/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpSubtract , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator- (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator-() [2/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpSubtract , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator- (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator-() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpSubtract , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator- (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator-() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpSubtract , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator- (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator-() [5/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpSubtract , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator- (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator-() [6/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpSubtract , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator- (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator/() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpDivide , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator/ (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator/() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpDivide , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator/ (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator/() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpDivide , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator/ (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator/() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpDivide , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator/ (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator/() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpDivide , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator/ (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator/() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpDivide , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator/ (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator<() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpLT , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator< (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator<() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpLT , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator< (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator<() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpLT , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator< (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator<() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpLT , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator< (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator<() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpLT , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator< (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator<() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpLT , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator< (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator<=() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpLE , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator<= (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator<=() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpLE , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator<= (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator<=() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpLE , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator<= (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator<=() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpLE , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator<= (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator<=() [5/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpLE , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator<= (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator<=() [6/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpLE , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator<= (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator==() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpEQ , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator== (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator==() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpEQ , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator== (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator==() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpEQ , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator== (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator==() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpEQ , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator== (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator==() [5/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpEQ , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator== (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator==() [6/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpEQ , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator== (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator>() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpGT , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator> (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator>() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpGT , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator> (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator>() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpGT , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator> (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator>() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpGT , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator> (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator>() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpGT , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator> (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator>() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpGT , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator> (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator>=() [1/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpGE , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator>= (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator>=() [2/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpGE , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator>= (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator>=() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpGE , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator>= (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator>=() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpGE , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator>= (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator>=() [5/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpGE , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator>= (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator>=() [6/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpGE , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator>= (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator^() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpBitwiseXor , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator^ (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator^() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpBitwiseXor , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator^ (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator^() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpBitwiseXor , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator^ (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator^() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpBitwiseXor , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator^ (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator^() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpBitwiseXor , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator^ (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator^() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpBitwiseXor , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator^ (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator|() [1/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpBitwiseOr , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator| (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator|() [2/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpBitwiseOr , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator| (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator|() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpBitwiseOr , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator| (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator|() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpBitwiseOr , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator| (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator|() [5/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpBitwiseOr , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator| (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator|() [6/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpBitwiseOr , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator| (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator||() [1/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpOr , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > operator|| (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator||() [2/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpOr , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> operator|| (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
operator||() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpOr , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator|| (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator||() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpOr , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > operator|| (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
operator||() [5/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< OpOr , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > operator|| (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
operator||() [6/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< OpOr , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> operator|| (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
outerProduct() [1/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnOuterProduct , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> outerProduct (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
outerProduct() [2/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnOuterProduct , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > outerProduct (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
outerProduct() [3/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnOuterProduct , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> outerProduct (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
outerProduct() [4/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnOuterProduct , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > outerProduct (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
outerProduct() [5/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnOuterProduct , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> outerProduct (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
outerProduct() [6/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnOuterProduct , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > outerProduct (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
PETE_apply()
template<class T , class TP > PETEUnaryReturn<T,OpParens<TP> >::type PETE_apply (OpParens< TP > op, const T & a) inline
Definition at line 520 of file IpplExpressions.h.
References a, and OpParens< TP >::Arg.
Referenced by AnyHolder< T, OP >::operator*=(), and AnyHolder< T, OP >::operator=().
PETE_DefineAssign()
PETE_DefineAssign ((a=Min(a, b)) , (a=Min(a, b.value)) , OpMinAssign)
PETE_DefineBinary() [1/3]
PETE_DefineBinary (Min , (Min(a, b)) , FnMin)
PETE_DefineBinary() [2/3]
FnMax PETE_DefineBinary (dot , (dot(a, b)) , FnDot)
PETE_DefineBinary() [3/3]
FnMax FnDotDot PETE_DefineBinary (outerProduct , (outerProduct(a, b)) , FnOuterProduct)
PETE_DefineBinarySynonym() [1/3]
FnMax FnDotDot FnCross PETE_DefineBinarySynonym (lt , OpLT)
PETE_DefineBinarySynonym() [2/3]
FnMax FnDotDot FnCross OpGT PETE_DefineBinarySynonym (le , OpLE)
PETE_DefineBinarySynonym() [3/3]
FnMax FnDotDot FnCross OpGT OpGE PETE_DefineBinarySynonym (eq , OpEQ)
PETE_DefineBinaryWithScalars() [1/31]
PETE_DefineBinaryWithScalars (Min , FnMin , short)
PETE_DefineBinaryWithScalars() [2/31]
short short short short PETE_DefineBinaryWithScalars (gt , OpGT , short)
PETE_DefineBinaryWithScalars() [3/31]
short short short short short PETE_DefineBinaryWithScalars (eq , OpEQ , short)
PETE_DefineBinaryWithScalars() [4/31]
short short PETE_DefineBinaryWithScalars (outerProduct , FnOuterProduct , short)
PETE_DefineBinaryWithScalars() [5/31]
short short short PETE_DefineBinaryWithScalars (lt , OpLT , short)
PETE_DefineBinaryWithScalars() [6/31]
short PETE_DefineBinaryWithScalars (dot , FnDot , short)
PETE_DefineBinaryWithScalars() [7/31]
short short short short short short int int PETE_DefineBinaryWithScalars (outerProduct , FnOuterProduct , int)
PETE_DefineBinaryWithScalars() [8/31]
short short short short short short int int int int int PETE_DefineBinaryWithScalars (eq , OpEQ , int)
PETE_DefineBinaryWithScalars() [9/31]
short short short short short short int int int PETE_DefineBinaryWithScalars (lt , OpLT , int)
PETE_DefineBinaryWithScalars() [10/31]
short short short short short short PETE_DefineBinaryWithScalars (Min , FnMin , int)
PETE_DefineBinaryWithScalars() [11/31]
short short short short short short int int int int PETE_DefineBinaryWithScalars (gt , OpGT , int)
PETE_DefineBinaryWithScalars() [12/31]
short short short short short short int PETE_DefineBinaryWithScalars (dot , FnDot , int)
PETE_DefineBinaryWithScalars() [13/31]
short short short short short short int int int int int int long long long PETE_DefineBinaryWithScalars (lt , OpLT , long)
PETE_DefineBinaryWithScalars() [14/31]
short short short short short short int int int int int int long long long long PETE_DefineBinaryWithScalars (gt , OpGT , long)
PETE_DefineBinaryWithScalars() [15/31]
short short short short short short int int int int int int long long PETE_DefineBinaryWithScalars (outerProduct , FnOuterProduct , long)
PETE_DefineBinaryWithScalars() [16/31]
short short short short short short int int int int int int long long long long long PETE_DefineBinaryWithScalars (eq , OpEQ , long)
PETE_DefineBinaryWithScalars() [17/31]
short short short short short short int int int int int int PETE_DefineBinaryWithScalars (Min , FnMin , long)
PETE_DefineBinaryWithScalars() [18/31]
short short short short short short int int int int int int long PETE_DefineBinaryWithScalars (dot , FnDot , long)
PETE_DefineBinaryWithScalars() [19/31]
short short short short short short int int int int int int long long long long long long PETE_DefineBinaryWithScalars (Min , FnMin , float)
PETE_DefineBinaryWithScalars() [20/31]
short short short short short short int int int int int int long long long long long long float float float PETE_DefineBinaryWithScalars (lt , OpLT , float)
PETE_DefineBinaryWithScalars() [21/31]
short short short short short short int int int int int int long long long long long long float float float float PETE_DefineBinaryWithScalars (gt , OpGT , float)
PETE_DefineBinaryWithScalars() [22/31]
short short short short short short int int int int int int long long long long long long float float float float float PETE_DefineBinaryWithScalars (eq , OpEQ , float)
PETE_DefineBinaryWithScalars() [23/31]
short short short short short short int int int int int int long long long long long long float PETE_DefineBinaryWithScalars (dot , FnDot , float)
PETE_DefineBinaryWithScalars() [24/31]
short short short short short short int int int int int int long long long long long long float float PETE_DefineBinaryWithScalars (outerProduct , FnOuterProduct , float)
PETE_DefineBinaryWithScalars() [25/31]
short short short short short short int int int int int int long long long long long long float float float float float float double PETE_DefineBinaryWithScalars (dot , FnDot , double)
PETE_DefineBinaryWithScalars() [26/31]
short short short short short short int int int int int int long long long long long long float float float float float float PETE_DefineBinaryWithScalars (Min , FnMin , double)
PETE_DefineBinaryWithScalars() [27/31]
short short short short short short int int int int int int long long long long long long float float float float float float double double PETE_DefineBinaryWithScalars (outerProduct , FnOuterProduct , double)
PETE_DefineBinaryWithScalars() [28/31]
short short short short short short int int int int int int long long long long long long float float float float float float double double double double double PETE_DefineBinaryWithScalars (eq , OpEQ , double)
PETE_DefineBinaryWithScalars() [29/31]
short short short short short short int int int int int int long long long long long long float float float float float float double double double PETE_DefineBinaryWithScalars (lt , OpLT , double)
PETE_DefineBinaryWithScalars() [30/31]
short short short short short short int int int int int int long long long long long long float float float float float float double double double double PETE_DefineBinaryWithScalars (gt , OpGT , double)
PETE_DefineBinaryWithScalars() [31/31]
short short short short short short int int int int int int long long long long long long float float float float float float double double double double double double std::complex<double> PETE_DefineBinaryWithScalars (ne , OpNE , std::complex< double >)
PETE_DefineScalar()
short short short short short short int int int int int int long long long long long long float float float float float float double double double double double double PETE_DefineScalar (std::complex< double >)
PETE_DefineUnary() [1/6]
PETE_DefineUnary (Abs , (0< a ? a :-a) , FnAbs)
PETE_DefineUnary() [2/6]
PETE_DefineUnary (conj , (conj(a)) , FnConj)
PETE_DefineUnary() [3/6]
FnArg PETE_DefineUnary (norm , (norm(a)) , FnNorm)
PETE_DefineUnary() [4/6]
FnArg FnReal PETE_DefineUnary (imag , (imag(a)) , FnImag)
PETE_DefineUnary() [5/6]
FnArg FnReal FnSign PETE_DefineUnary (trace , (trace(a)) , FnTrace)
PETE_DefineUnary() [6/6]
FnArg FnReal FnSign FnTranspose PETE_DefineUnary (det , (det(a)) , FnDet)
pow() [1/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnPow , typename T1::PETE_Expr_t, PETE_Scalar< Vektor <T2, Dim> > > pow (const PETE_Expr< T1 > & l, const Vektor< T2, Dim > & r) inline
Definition at line 244 of file IpplExpressions.h.
pow() [2/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnPow , PETE_Scalar< Vektor <T1, Dim> >, typename T2::PETE_Expr_t> pow (const Vektor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 244 of file IpplExpressions.h.
pow() [3/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnPow , typename T1::PETE_Expr_t, PETE_Scalar< SymTenzor <T2, Dim> > > pow (const PETE_Expr< T1 > & l, const SymTenzor< T2, Dim > & r) inline
Definition at line 245 of file IpplExpressions.h.
pow() [4/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnPow , PETE_Scalar< SymTenzor <T1, Dim> >, typename T2::PETE_Expr_t> pow (const SymTenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 245 of file IpplExpressions.h.
pow() [5/6]
template<class T1 , class T2 , unsigned Dim> PETE_TBTree< FnPow , typename T1::PETE_Expr_t, PETE_Scalar< Tenzor <T2, Dim> > > pow (const PETE_Expr< T1 > & l, const Tenzor< T2, Dim > & r) inline
Definition at line 246 of file IpplExpressions.h.
pow() [6/6]
template<class T1 , unsigned Dim, class T2 > PETE_TBTree< FnPow , PETE_Scalar< Tenzor <T1, Dim> >, typename T2::PETE_Expr_t> pow (const Tenzor< T1, Dim > & l, const PETE_Expr< T2 > & r) inline
Definition at line 246 of file IpplExpressions.h.
real()
FnArg real (a)
sign()
FnArg FnReal sign (a)
Referenced by AmrOpenBoundary< Level >::abc1_m(), AmrOpenBoundary< Level >::abc2_m(), AmrOpenBoundary< Level >::abc3_m(), BoundingBox::getIntersectionPoint(), and SigmaGenerator::updateInitialSigma().
transpose()
FnArg FnReal FnSign transpose (a)
where() [1/9]
template<class Cond_t , class True_t , class T , unsigned Dim> PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< Vektor <T, Dim> > > where (const PETE_Expr< Cond_t > & c, const PETE_Expr< True_t > & t, const Vektor< T, Dim > & f) inline
Definition at line 244 of file IpplExpressions.h.
Referenced by FFTBoxPoissonSolver::FFTBoxPoissonSolver(), P3MPoissonSolver::initializeFields(), FFTPoissonSolver::initializeFields(), H5PartWrapper::receiveFailureMessage(), H5PartWrapper::sendFailureMessage(), PartBunchBase< double, 3 >::setBinCharge(), AmrYtWriter::writeBunch(), and AmrYtWriter::writeParticles_m().
where() [2/9]
template<class Cond_t , class T , unsigned Dim, class False_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< Vektor <T, Dim> >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > & c, const Vektor< T, Dim > & t, const PETE_Expr< False_t > & f) inline
Definition at line 244 of file IpplExpressions.h.
where() [3/9]
template<class Cond_t , class T , unsigned Dim> PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< Vektor <T, Dim> >, PETE_Scalar< Vektor <T, Dim> > > where (const PETE_Expr< Cond_t > & c, const Vektor< T, Dim > & t, const Vektor< T, Dim > & f) inline
Definition at line 244 of file IpplExpressions.h.
where() [4/9]
template<class Cond_t , class T , unsigned Dim> PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< SymTenzor <T, Dim> >, PETE_Scalar< SymTenzor <T, Dim> > > where (const PETE_Expr< Cond_t > & c, const SymTenzor< T, Dim > & t, const SymTenzor< T, Dim > & f) inline
Definition at line 245 of file IpplExpressions.h.
where() [5/9]
template<class Cond_t , class True_t , class T , unsigned Dim> PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< SymTenzor <T, Dim> > > where (const PETE_Expr< Cond_t > & c, const PETE_Expr< True_t > & t, const SymTenzor< T, Dim > & f) inline
Definition at line 245 of file IpplExpressions.h.
where() [6/9]
template<class Cond_t , class T , unsigned Dim, class False_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< SymTenzor <T, Dim> >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > & c, const SymTenzor< T, Dim > & t, const PETE_Expr< False_t > & f) inline
Definition at line 245 of file IpplExpressions.h.
where() [7/9]
template<class Cond_t , class T , unsigned Dim> PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< Tenzor <T, Dim> >, PETE_Scalar< Tenzor <T, Dim> > > where (const PETE_Expr< Cond_t > & c, const Tenzor< T, Dim > & t, const Tenzor< T, Dim > & f) inline
Definition at line 246 of file IpplExpressions.h.
References PETE_Expr< WrappedExpr >::PETE_unwrap(), and Reduction().
where() [8/9]
template<class Cond_t , class T , unsigned Dim, class False_t > PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, PETE_Scalar< Tenzor <T, Dim> >, typename False_t::PETE_Expr_t > where (const PETE_Expr< Cond_t > & c, const Tenzor< T, Dim > & t, const PETE_Expr< False_t > & f) inline
Definition at line 246 of file IpplExpressions.h.
where() [9/9]
template<class Cond_t , class True_t , class T , unsigned Dim> PETE_TTTree< OpWhere , typename Cond_t::PETE_Expr_t, typename True_t::PETE_Expr_t, PETE_Scalar< Tenzor <T, Dim> > > where (const PETE_Expr< Cond_t > & c, const PETE_Expr< True_t > & t, const Tenzor< T, Dim > & f) inline
Definition at line 246 of file IpplExpressions.h.
Variable Documentation
a
std::complex<double> a
Initial value:
{
  return abs(a)
Definition at line 56 of file IpplExpressions.h.
Referenced by Expressions::Add(), RNGXDiv::advijk(), Expressions::And(), TSV_MetaCross< Vektor< T1, 3 >, Vektor< T2, 3 > >::apply(), BConds< Vektor, 3, UniformCartesian, Cell >::apply(), assertion::assertion(), assign(), BareField< T1, D >::BareField(), interpolation::MMatrix< double >::build_matrix(), GreenWakeFunction::CalcWakeFFT(), DataConnect::checkin(), DataConnect::checkout(), SIndex< Dim >::clear(), NDIndex< Brackets >::contains(), Index::contains(), NDIndex< Brackets >::containsAllPoints(), Mesher::crossProduct(), interpolation::MMatrix< double >::Diagonal(), DataSource::disconnect(), Expressions::Div(), DomainMap< Key, T, Touches, Contains, Split >::DomainMap(), dotProduct(), Expressions::Eq(), euclidean_norm(), BeamStrippingPhysics::evalLorentzStripping(), ExtrapolateAndZeroFaceBCApply2(), ExtrapolateAndZeroFaceBCApply3(), ExtrapolateFaceBCApply2(), LSIndex< Dim >::find(), DataSource::findDataSourceObject(), Expressions::Ge(), vmap< std::string, DiscConfig::SMPData *>::Ge(), Distribution::generateAstraFlattopT(), getAngleBetweenEdges(), RFCavity::getAutoPhaseEstimate(), Cartesian< Dim, MFLOAT >::getDeltaCell(), Cartesian< Dim, MFLOAT >::getDeltaVertex(), Bend2D::getOutline(), RNGXDiv::GetRandom(), Distribution::getTEmission(), vmap< std::string, DiscConfig::SMPData *>::Gt(), Expressions::Gt(), LSIndex< Dim >::hasIndex(), SIndex< Dim >::hasIndex(), SigmaGenerator::initialize(), tanhderiv::integrate(), DataConnect::interact(), DataSource::interact(), BoundaryGeometry::intersectLineTriangle(), endfieldmodel::IterableEquality(), Expressions::Le(), vmap< std::string, DiscConfig::SMPData *>::Le(), Expressions::Lt(), lubksb(), ludcmp(), Matrix3D::Matrix3D(), Expressions::Max(), Distribution::MDependentBehavior::MDependentBehavior(), Expressions::Min(), interpolation::MMatrix< double >::MMatrix(), Expressions::Mod(), Expressions::Mpy(), Expressions::Ne(), Expressions::Neg(), BrickIterator< T, Dim >::operator!=(), SOffset< Dim >::operator!=(), ParticleAttribElemIterator< T, Dim >::operator!=(), ParticleAttribIterator< T >::operator!=(), ParticleAttribConstIterator< T >::operator!=(), ProxyPred_t< A >::operator()(), RadiusCondition< T, Dim >::operator()(), BoxCondition< T, Dim >::operator()(), OrbitThreader::elementPositionComp::operator()(), AntiSymTenzor< T, D >::operator()(), SymTenzor< double, 6 >::operator()(), SOffsetAssignOp::operator()(), SOffsetAddAssignOp::operator()(), SOffsetSubAssignOp::operator()(), SOffsetMultAssignOp::operator()(), SOffsetDivAssignOp::operator()(), AntiSymTenzor< T, 1 >::operator()(), operator*(), operator+(), operator-(), ParticleAttribIterator< T >::operator-(), ParticleAttribConstIterator< T >::operator-(), operator/(), SOffset< Dim >::operator<(), ParticleAttribIterator< T >::operator<(), ParticleAttribConstIterator< T >::operator<(), operator<<(), Expressions::operator<<(), SOffset< Dim >::operator<=(), ParticleAttribIterator< T >::operator<=(), ParticleAttribConstIterator< T >::operator<=(), assertion::operator=(), AntiSymTenzor< T, D >::AssignProxy::operator=(), AntiSymTenzor< T, 1 >::AssignProxy::operator=(), DomainMap< Key, T, Touches, Contains, Split >::operator=(), BrickIterator< T, Dim >::operator==(), SOffset< Dim >::operator==(), ParticleAttribElemIterator< T, Dim >::operator==(), ParticleAttribIterator< T >::operator==(), ParticleAttribConstIterator< T >::operator==(), SOffset< Dim >::operator>(), ParticleAttribIterator< T >::operator>(), ParticleAttribConstIterator< T >::operator>(), SOffset< Dim >::operator>=(), ParticleAttribIterator< T >::operator>=(), ParticleAttribConstIterator< T >::operator>=(), ParticleAttrib< ParticleOrigin >::operator[](), SIndex< Dim >::operator|=(), Expressions::Or(), PETE_apply(), Index::plugBase(), Timing::print(), DiscParticle::printDebug(), ProxyPred(), IndexMap::query(), DiscField< Dim >::read(), DiscParticle::read(), SIndex< Dim >::reserve(), RootFinderForCSR::RootFinderForCSR(), OpalBeamline::save3DLattice(), savgol(), endfieldmodel::Enge::setCoefficients(), BMultipoleField::setSkewComponent(), FieldLayout< Dim >::setup(), sign(), Expressions::Sign(), GreenWakeFunction::simpson(), SIndex< Dim >::size(), StepSizeConfig::sortAscendingZStop(), NDIndex< Brackets >::split(), Index::split(), Expressions::Sub(), LField< T, Dim >::swapData(), Touches< Dim >::test(), Contains< Dim >::test(), Split< Dim >::test(), TouchesRegion< T, Dim >::test(), ContainsRegion< T, Dim >::test(), SplitRegion< T, Dim >::test(), Expressions::Tgauss(), toss_cookies(), NDIndex< Brackets >::touches(), Index::touches(), DataSource::updateConnection(), DataConnect::updateConnections(), Variator< ind_t, CrossoverOperator, MutationOperator >::variate(), DiscParticle::write(), DiscParticle::write_data(), ParallelTTracker::writePhaseSpace(), DiscMeta::~DiscMeta(), and UserList::~UserList().
Dim
short short short short short short int int int int int int long long long long long long float float float float float float double double double double double double std::complex<double> unsigned Dim
Definition at line 244 of file IpplExpressions.h.
FnDot
short short short short short short int int int int int int long long long long long long float float float float float float double double FnDot
Definition at line 135 of file IpplExpressions.h.
FnDotDot
short short short short short short int int int int int int long long long long long long float float float float float float double FnDotDot
Definition at line 135 of file IpplExpressions.h.
FnMax
short short short short short short int int int int int int long long long long long long float float float float float float FnMax
Definition at line 135 of file IpplExpressions.h.
OpEQ
short short short short short short int int int int int int long long long long long long float float float float float float double double double double double double OpEQ
Definition at line 142 of file IpplExpressions.h.
Referenced by any().
OpGE
short short short short short short int int int int int int long long long long long long float float float float float float double double double double OpGE
Definition at line 135 of file IpplExpressions.h.
OpLE
short short short short short short int int int int int int long long long long long long float float float float float float double double double OpLE
Definition at line 135 of file IpplExpressions.h.
OpNE
short short short short short short int int int int int int long long long long long long float float float float float float double double double double double OpNE
Definition at line 135 of file IpplExpressions.h.