OPAL (Object Oriented Parallel Accelerator Library): Rnode< T, Dim > Class Template Reference
Rnode< T, Dim > Class Template Reference
#include <Rnode.h>
Public Member Functions
Rnode (const NDRegion< T, Dim > &domain, const Vektor< T, Dim > &offset, int node)
Rnode (const NDRegion< T, Dim > &domain, int node)
Rnode (const NDIndex< Dim > &domain, const Vektor< T, Dim > &offset, int node)
Rnode (const NDIndex< Dim > &domain, int node)
Rnode< T, Dim > & operator= (const Rnode< T, Dim > &r)
int getNode ()
const NDRegion< T, Dim > & getDomain ()
const Vektor< T, Dim > & getOffset ()
Private Attributes
NDRegion< T, Dim > Domain
Vektor< T, Dim > Offset
int Node
Detailed Description
template<class T, unsigned Dim>
class Rnode< T, Dim >
Definition at line 30 of file Rnode.h.
Constructor & Destructor Documentation
Rnode() [1/4]
template<class T, unsigned Dim> Rnode< T, Dim >::Rnode (const NDRegion< T, Dim > & domain, const Vektor< T, Dim > & offset, int node) inline
Definition at line 34 of file Rnode.h.
Rnode() [2/4]
template<class T, unsigned Dim> Rnode< T, Dim >::Rnode (const NDRegion< T, Dim > & domain, int node) inline
Definition at line 36 of file Rnode.h.
Rnode() [3/4]
template<class T, unsigned Dim> Rnode< T, Dim >::Rnode (const NDIndex< Dim > & domain, const Vektor< T, Dim > & offset, int node) inline
Definition at line 38 of file Rnode.h.
Rnode() [4/4]
template<class T, unsigned Dim> Rnode< T, Dim >::Rnode (const NDIndex< Dim > & domain, int node) inline
Definition at line 40 of file Rnode.h.
Member Function Documentation
getDomain()
template<class T, unsigned Dim> const NDRegion<T,Dim>& Rnode< T, Dim >::getDomain (void) inline
Definition at line 53 of file Rnode.h.
References Rnode< T, Dim >::Domain.
Referenced by RegionLayout< T, Dim, Mesh >::make_rnodes().
getNode()
template<class T, unsigned Dim> int Rnode< T, Dim >::getNode () inline
Definition at line 52 of file Rnode.h.
References Rnode< T, Dim >::Node.
Referenced by ParticleCashedLayout< T, Dim, Mesh >::swap_ghost_particles(), and ParticleInteractLayout< T, Dim, Mesh >::swap_ghost_particles().
getOffset()
template<class T, unsigned Dim> const Vektor<T,Dim>& Rnode< T, Dim >::getOffset () inline
Definition at line 54 of file Rnode.h.
References Rnode< T, Dim >::Offset.
operator=()
template<class T, unsigned Dim> Rnode<T,Dim>& Rnode< T, Dim >::operator= (const Rnode< T, Dim > & r) inline
Definition at line 44 of file Rnode.h.
References Rnode< T, Dim >::Domain, Rnode< T, Dim >::Node, and Rnode< T, Dim >::Offset.
Member Data Documentation
Domain
template<class T, unsigned Dim> NDRegion<T,Dim> Rnode< T, Dim >::Domain private
Definition at line 57 of file Rnode.h.
Referenced by Rnode< T, Dim >::getDomain(), and Rnode< T, Dim >::operator=().
Node
template<class T, unsigned Dim> int Rnode< T, Dim >::Node private
Definition at line 59 of file Rnode.h.
Referenced by Rnode< T, Dim >::getNode(), and Rnode< T, Dim >::operator=().
Offset
template<class T, unsigned Dim> Vektor<T,Dim> Rnode< T, Dim >::Offset private
Definition at line 58 of file Rnode.h.
Referenced by Rnode< T, Dim >::getOffset(), and Rnode< T, Dim >::operator=().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Region/Rnode.h