OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyAbstractTimeDependence Namespace Reference
PyOpal::PyAbstractTimeDependence Namespace Reference
Functions
template<class C >
double function (PyOpalObjectNS::PyOpalObject< C > pyobject, double t)
Variables
std::string functionDocstring
Function Documentation
function()
template<class C > double PyOpal::PyAbstractTimeDependence::function (PyOpalObjectNS::PyOpalObject< C > pyobject, double t)
Definition at line 16 of file PyAbstractTimeDependence.h.
References AbstractTimeDependence::getTimeDependence(), and name.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser(), SDDS::parser::associate_parser< Iterator >::associate_parser(), client::parser::expression< Iterator >::expression(), SDDS::parser::include_parser< Iterator >::include_parser(), client::code_gen::requirements::requirements(), and client::code_gen::StackEvaluator::StackEvaluator().
Variable Documentation
functionDocstring
std::string PyOpal::PyAbstractTimeDependence::functionDocstring
Initial value:
=
"Update the TimeDependence and then calculate the value at a give time\n"
"- t [float]: time at which to evaluate the function\n"
"Returns the function value.\n"
Definition at line 10 of file PyAbstractTimeDependence.h.