OPAL (Object Oriented Parallel Accelerator Library): _Fieldmap Class Reference
_Fieldmap Class Reference abstract
#include <Fieldmap.h>
Classes
struct FieldmapDescription
struct TypeParseTraits
struct TypeParseTraits< double >
struct TypeParseTraits< int >
struct TypeParseTraits< std::string >
struct TypeParseTraits< unsigned int >
Public Member Functions
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const =0
virtual bool getFieldDerivative (const Vector_t &R, Vector_t &E, Vector_t &B, const DiffDirection &dir) const =0
virtual void getFieldDimensions (double &zBegin, double &zEnd) const =0
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const =0
virtual void swap ()=0
virtual void getInfo (Inform *msg)=0
virtual double getFrequency () const =0
virtual void setFrequency (double freq)=0
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &onaxis)
virtual bool isInside (const Vector_t &) const
virtual void readMap ()=0
virtual void freeMap ()=0
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Static Public Member Functions
static Fieldmap getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions
_Fieldmap ()=delete
_Fieldmap (const std::string &filename)
virtual ~_Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Static Private Attributes
static char buffer_m [256]
static std::string alpha_numeric
static std::map< std::string, FieldmapDescription > FieldmapDictionary = std::map<std::string, _Fieldmap::FieldmapDescription>()
Detailed Description
Definition at line 61 of file Fieldmap.h.
Constructor & Destructor Documentation
_Fieldmap() [1/2]
_Fieldmap::_Fieldmap () protected delete
_Fieldmap() [2/2]
_Fieldmap::_Fieldmap (const std::string & filename) inline protected
Definition at line 110 of file Fieldmap.h.
~_Fieldmap()
virtual _Fieldmap::~_Fieldmap () inline protected virtual
Definition at line 115 of file Fieldmap.h.
Member Function Documentation
checkMap() [1/2]
void _Fieldmap::checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > & fourierCoefficients, gsl_spline * splineCoefficients, gsl_interp_accel * splineAccelerator) protected
Definition at line 448 of file Fieldmap.cpp.
Referenced by _FM1DElectroStatic_fast::prepareForMapCheck(), _FM1DMagnetoStatic_fast::prepareForMapCheck(), _FM1DDynamic_fast::prepareForMapCheck(), _Astra1DElectroStatic_fast::readMap(), _Astra1DMagnetoStatic_fast::readMap(), and _Astra1DDynamic_fast::readMap().
checkMap() [2/2]
void _Fieldmap::checkMap (unsigned int accuracy, double length, const std::vector< double > & zSampling, const std::vector< double > & fourierCoefficients, gsl_spline * splineCoefficients, gsl_interp_accel * splineAccelerator) protected
Definition at line 464 of file Fieldmap.cpp.
References abs(), Util::combineFilePath(), cos(), Physics::e, end(), endl(), Filename_m, OpalData::getInstance(), lowResolutionWarning(), IpplInfo::myNode(), Hypervolume::n, pow(), sin(), sqrt(), and Physics::two_pi.
clearDictionary()
void _Fieldmap::clearDictionary () static
Definition at line 274 of file Fieldmap.cpp.
References FieldmapDictionary.
Referenced by opalMain(), and run_opal().
deleteFieldmap()
void _Fieldmap::deleteFieldmap (std::string Filename) static
Definition at line 270 of file Fieldmap.cpp.
References freeMap().
disableFieldmapWarning()
void _Fieldmap::disableFieldmapWarning () protected
Definition at line 610 of file Fieldmap.cpp.
References Filename_m.
Referenced by _Astra1DDynamic::_Astra1DDynamic(), _Astra1DDynamic_fast::_Astra1DDynamic_fast(), _Astra1DElectroStatic::_Astra1DElectroStatic(), _Astra1DElectroStatic_fast::_Astra1DElectroStatic_fast(), _Astra1DMagnetoStatic::_Astra1DMagnetoStatic(), _Astra1DMagnetoStatic_fast::_Astra1DMagnetoStatic_fast(), _FM1DDynamic::_FM1DDynamic(), _FM1DDynamic_fast::_FM1DDynamic_fast(), _FM1DElectroStatic::_FM1DElectroStatic(), _FM1DElectroStatic_fast::_FM1DElectroStatic_fast(), _FM1DMagnetoStatic::_FM1DMagnetoStatic(), _FM1DMagnetoStatic_fast::_FM1DMagnetoStatic_fast(), _FM1DProfile1::_FM1DProfile1(), _FM1DProfile2::_FM1DProfile2(), _FM2DDynamic::_FM2DDynamic(), _FM2DElectroStatic::_FM2DElectroStatic(), _FM2DMagnetoStatic::_FM2DMagnetoStatic(), _FM3DDynamic::_FM3DDynamic(), and _FM3DMagnetoStaticExtended::_FM3DMagnetoStaticExtended().
exceedingValuesWarning()
void _Fieldmap::exceedingValuesWarning () protected
Definition at line 600 of file Fieldmap.cpp.
References Filename_m, and lines_read_m.
Referenced by interpreteEOF().
freeMap() [1/2]
void _Fieldmap::freeMap (std::string Filename) static
Definition at line 431 of file Fieldmap.cpp.
References FieldmapDictionary.
freeMap() [2/2]
virtual void _Fieldmap::freeMap () pure virtual
Implemented in _FM1DProfile1, _FM3DH5Block, _FM3DH5Block_nonscale, _FM3DMagnetoStaticH5Block, _FM3DH5BlockBase, _FM1DDynamic_fast, _FM1DDynamic, _FM1DElectroStatic, _FM1DElectroStatic_fast, _FM1DMagnetoStatic, _FM1DMagnetoStatic_fast, _FM2DDynamic, _Astra1DDynamic, _FM1DProfile2, _FM3DDynamic, _Astra1DElectroStatic, _Astra1DMagnetoStatic, _FM2DElectroStatic, _FM2DMagnetoStatic, _FM3DMagnetoStatic, _FM3DMagnetoStaticExtended, and _Astra1D_fast.
Referenced by deleteFieldmap(), Solenoid::goOffline(), TravelingWave::goOffline(), RBend3D::goOffline(), and RFCavity::goOffline().
get1DProfile1EngeCoeffs()
void _Fieldmap::get1DProfile1EngeCoeffs (std::vector< double > & engeCoeffsEntry, std::vector< double > & engeCoeffsExit) virtual
Reimplemented in _FM1DProfile1.
Definition at line 709 of file Fieldmap.cpp.
get1DProfile1EntranceParam()
void _Fieldmap::get1DProfile1EntranceParam (double & entranceParameter1, double & entranceParameter2, double & entranceParameter3) virtual
Reimplemented in _FM1DProfile1.
Definition at line 714 of file Fieldmap.cpp.
get1DProfile1ExitParam()
void _Fieldmap::get1DProfile1ExitParam (double & exitParameter1, double & exitParameter2, double & exitParameter3) virtual
Reimplemented in _FM1DProfile1.
Definition at line 720 of file Fieldmap.cpp.
getFieldDerivative()
virtual bool _Fieldmap::getFieldDerivative (const Vector_t & R, Vector_t & E, Vector_t & B, const DiffDirection & dir) const pure virtual
Implemented in _FM3DH5BlockBase, _Astra1DDynamic_fast, _FM1DProfile1, _FM1DElectroStatic, _FM1DElectroStatic_fast, _FM1DMagnetoStatic, _FM1DMagnetoStatic_fast, _FM2DDynamic, _Astra1DMagnetoStatic_fast, _Astra1DElectroStatic, _Astra1DElectroStatic_fast, _Astra1DMagnetoStatic, _FM2DElectroStatic, _FM3DDynamic, _FM3DMagnetoStatic, _Astra1D_fast, _Astra1DDynamic, _FM1DDynamic, _FM1DDynamic_fast, _FM1DProfile2, _FM2DMagnetoStatic, and _FM3DMagnetoStaticExtended.
getFieldDimensions() [1/2]
virtual void _Fieldmap::getFieldDimensions (double & zBegin, double & zEnd) const pure virtual
Implemented in _FM3DH5BlockBase, _Astra1DDynamic_fast, _FM1DProfile1, _FM1DDynamic, _FM1DDynamic_fast, _FM2DDynamic, _Astra1D_fast, _Astra1DDynamic, _Astra1DMagnetoStatic_fast, _FM1DProfile2, _FM2DMagnetoStatic, _FM3DMagnetoStaticExtended, _Astra1DElectroStatic, _Astra1DElectroStatic_fast, _Astra1DMagnetoStatic, _FM1DElectroStatic, _FM1DElectroStatic_fast, _FM1DMagnetoStatic, _FM1DMagnetoStatic_fast, _FM2DElectroStatic, _FM3DDynamic, and _FM3DMagnetoStatic.
getFieldDimensions() [2/2]
virtual void _Fieldmap::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const pure virtual
Implemented in _FM3DH5BlockBase, _Astra1DDynamic_fast, _FM1DProfile1, _FM1DDynamic, _FM1DDynamic_fast, _FM2DDynamic, _Astra1D_fast, _Astra1DDynamic, _Astra1DMagnetoStatic_fast, _FM1DProfile2, _FM2DMagnetoStatic, _FM3DMagnetoStaticExtended, _Astra1DElectroStatic, _Astra1DElectroStatic_fast, _Astra1DMagnetoStatic, _FM1DElectroStatic, _FM1DElectroStatic_fast, _FM1DMagnetoStatic, _FM1DMagnetoStatic_fast, _FM2DElectroStatic, _FM3DDynamic, and _FM3DMagnetoStatic.
getFieldGap()
double _Fieldmap::getFieldGap () virtual
Reimplemented in _FM1DProfile1.
Definition at line 726 of file Fieldmap.cpp.
getFieldmap()
Fieldmap _Fieldmap::getFieldmap (std::string Filename, bool fast = false) static
Definition at line 48 of file Fieldmap.cpp.
References _Astra1DElectroStatic_fast::create(), _Astra1DMagnetoStatic_fast::create(), _FM3DMagnetoStatic::create(), _FM3DMagnetoStaticExtended::create(), _Astra1DMagnetoStatic::create(), _Astra1DElectroStatic::create(), _FM2DElectroStatic::create(), _FM2DMagnetoStatic::create(), _FM3DDynamic::create(), _FM1DProfile2::create(), _Astra1DDynamic::create(), _FM1DElectroStatic_fast::create(), _FM1DMagnetoStatic::create(), _FM1DMagnetoStatic_fast::create(), _FM1DElectroStatic::create(), _FM2DDynamic::create(), _FM1DDynamic::create(), _FM1DDynamic_fast::create(), _FM3DMagnetoStaticH5Block::create(), _FM3DH5Block::create(), _FM3DH5Block_nonscale::create(), _Astra1DDynamic_fast::create(), _FM1DProfile1::create(), FieldmapDictionary, readHeader(), T1DDynamic, T1DElectroStatic, T1DMagnetoStatic, T1DProfile1, T1DProfile2, T2DDynamic, T2DElectroStatic, T2DMagnetoStatic, T3DDynamic, T3DDynamicH5Block, T3DMagnetoStatic, T3DMagnetoStatic_Extended, T3DMagnetoStaticH5Block, TAstraDynamic, TAstraElectroStatic, and TAstraMagnetoStatic.
Referenced by Cyclotron::getFieldFromFile_BandRF(), Cyclotron::getFieldFromFile_Synchrocyclotron(), Solenoid::initialise(), RBend3D::initialise(), RFCavity::initialise(), and Bend2D::initializeFieldMap().
getFieldstrength()
virtual bool _Fieldmap::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const pure virtual
Implemented in _FM3DH5BlockBase, _FM1DProfile1, _Astra1DDynamic_fast, _FM3DH5Block, _FM3DH5Block_nonscale, _FM3DMagnetoStaticH5Block, _FM2DDynamic, _Astra1DMagnetoStatic_fast, _Astra1D_fast, _Astra1DDynamic, _Astra1DElectroStatic, _Astra1DElectroStatic_fast, _Astra1DMagnetoStatic, _FM1DDynamic, _FM1DDynamic_fast, _FM1DElectroStatic, _FM1DElectroStatic_fast, _FM1DMagnetoStatic, _FM1DMagnetoStatic_fast, _FM1DProfile2, _FM2DElectroStatic, _FM2DMagnetoStatic, _FM3DDynamic, _FM3DMagnetoStatic, and _FM3DMagnetoStaticExtended.
getFrequency()
virtual double _Fieldmap::getFrequency () const pure virtual
Implemented in _FM3DH5BlockBase, _FM3DMagnetoStaticH5Block, _FM1DProfile1, _Astra1DDynamic_fast, _FM1DDynamic, _FM1DDynamic_fast, _FM1DElectroStatic, _FM1DElectroStatic_fast, _FM1DMagnetoStatic, _FM1DMagnetoStatic_fast, _FM2DDynamic, _Astra1DMagnetoStatic_fast, _Astra1D_fast, _Astra1DDynamic, _Astra1DElectroStatic, _Astra1DElectroStatic_fast, _Astra1DMagnetoStatic, _FM1DProfile2, _FM2DElectroStatic, _FM2DMagnetoStatic, _FM3DDynamic, _FM3DMagnetoStatic, and _FM3DMagnetoStaticExtended.
getInfo()
virtual void _Fieldmap::getInfo (Inform * msg) pure virtual
Implemented in _FM3DH5BlockBase, _FM1DProfile1, _Astra1DDynamic_fast, _FM1DDynamic, _FM1DDynamic_fast, _FM1DElectroStatic, _FM1DElectroStatic_fast, _FM1DMagnetoStatic, _FM1DMagnetoStatic_fast, _FM2DDynamic, _Astra1DMagnetoStatic_fast, _Astra1D_fast, _Astra1DDynamic, _Astra1DElectroStatic, _Astra1DElectroStatic_fast, _Astra1DMagnetoStatic, _FM1DProfile2, _FM2DElectroStatic, _FM2DMagnetoStatic, _FM3DDynamic, _FM3DMagnetoStatic, and _FM3DMagnetoStaticExtended.
getLine() [1/2]
void _Fieldmap::getLine (std::ifstream & in, std::string & buffer) inline protected
Definition at line 122 of file Fieldmap.h.
References lines_read_m.
Referenced by interpretLine(), readHeader(), _FM3DMagnetoStatic::readMap(), _FM3DMagnetoStaticExtended::readMap(), _Astra1DElectroStatic::readMap(), _Astra1DMagnetoStatic::readMap(), _FM2DElectroStatic::readMap(), _FM2DMagnetoStatic::readMap(), _Astra1DDynamic::readMap(), _FM3DDynamic::readMap(), _FM2DDynamic::readMap(), _FM1DElectroStatic::stripFileHeader(), _FM1DMagnetoStatic::stripFileHeader(), _FM1DDynamic::stripFileHeader(), _FM1DElectroStatic_fast::stripFileHeader(), _FM1DMagnetoStatic_fast::stripFileHeader(), and _FM1DDynamic_fast::stripFileHeader().
getLine() [2/2]
void _Fieldmap::getLine (std::ifstream & in, int & lines_read, std::string & buffer) static protected
Definition at line 533 of file Fieldmap.cpp.
References alpha_numeric, buffer_m, and READ_BUFFER_LENGTH.
getListFieldmapNames()
std::vector< std::string > _Fieldmap::getListFieldmapNames () static
Definition at line 262 of file Fieldmap.cpp.
References FieldmapDictionary.
getOnaxisEz()
void _Fieldmap::getOnaxisEz (std::vector< std::pair< double, double > > & onaxis) virtual
Reimplemented in _FM3DH5BlockBase, _Astra1DDynamic_fast, _FM2DDynamic, _Astra1D_fast, _Astra1DDynamic, and _FM3DDynamic.
Definition at line 706 of file Fieldmap.cpp.
getType()
MapType _Fieldmap::getType () inline
Definition at line 98 of file Fieldmap.h.
References Type.
interpreteEOF()
bool _Fieldmap::interpreteEOF (std::ifstream & in) protected
Definition at line 555 of file Fieldmap.cpp.
References alpha_numeric, buffer_m, exceedingValuesWarning(), lines_read_m, and READ_BUFFER_LENGTH.
Referenced by _FM1DProfile1::_FM1DProfile1(), _FM1DProfile2::_FM1DProfile2(), _FM2DDynamic::_FM2DDynamic(), _FM2DElectroStatic::_FM2DElectroStatic(), _FM2DMagnetoStatic::_FM2DMagnetoStatic(), _FM3DDynamic::_FM3DDynamic(), _FM3DMagnetoStatic::_FM3DMagnetoStatic(), _FM3DMagnetoStaticExtended::_FM3DMagnetoStaticExtended(), _FM1DElectroStatic_fast::checkFileData(), _FM1DDynamic::checkFileData(), _FM1DMagnetoStatic_fast::checkFileData(), _FM1DElectroStatic::checkFileData(), _FM1DMagnetoStatic::checkFileData(), and _FM1DDynamic_fast::checkFileData().
interpretLine() [1/6]
template<class T > bool _Fieldmap::interpretLine (std::ifstream & in, T & value, const bool & file_length_known)
Definition at line 12 of file Fieldmap.hpp.
References getLine(), interpretWarning(), and missingValuesWarning().
interpretLine() [2/6]
template<class S > bool _Fieldmap::interpretLine (std::ifstream & in, S & value, const bool & file_length_known = true) protected
interpretLine() [3/6]
template<class S , class T > bool _Fieldmap::interpretLine (std::ifstream & in, S & value1, T & value2, const bool & file_length_known = true) protected
Definition at line 39 of file Fieldmap.hpp.
References getLine(), interpretWarning(), and missingValuesWarning().
interpretLine() [4/6]
template<class S , class T , class U > bool _Fieldmap::interpretLine (std::ifstream & in, S & value1, T & value2, U & value3, const bool & file_length_known = true) protected
Definition at line 70 of file Fieldmap.hpp.
References getLine(), interpretWarning(), and missingValuesWarning().
interpretLine() [5/6]
template<class S , class T , class U , class V > bool _Fieldmap::interpretLine (std::ifstream & in, S & value1, T & value2, U & value3, V & value4, const bool & file_length_known = true) protected
Definition at line 104 of file Fieldmap.hpp.
References getLine(), interpretWarning(), and missingValuesWarning().
interpretLine() [6/6]
template<class S > bool _Fieldmap::interpretLine (std::ifstream & in, S & value1, S & value2, S & value3, S & value4, S & value5, S & value6, const bool & file_length_known = true) protected
Definition at line 141 of file Fieldmap.hpp.
References getLine(), interpretWarning(), and missingValuesWarning().
interpretWarning()
void _Fieldmap::interpretWarning (const std::ios_base::iostate & state, const bool & read_all, const std::string & error_msg, const std::string & found) protected
Definition at line 571 of file Fieldmap.cpp.
References endl(), Filename_m, and lines_read_m.
Referenced by interpretLine().
isInside()
virtual bool _Fieldmap::isInside (const Vector_t &) const inline virtual
Reimplemented in _FM3DH5BlockBase, _FM1DDynamic, _FM1DDynamic_fast, _FM1DElectroStatic, _FM1DElectroStatic_fast, _FM1DMagnetoStatic, _FM1DMagnetoStatic_fast, _FM2DDynamic, _Astra1D_fast, _Astra1DDynamic, _FM3DDynamic, _Astra1DElectroStatic, _Astra1DMagnetoStatic, _FM2DElectroStatic, _FM2DMagnetoStatic, _FM3DMagnetoStatic, and _FM3DMagnetoStaticExtended.
Definition at line 102 of file Fieldmap.h.
lowResolutionWarning()
void _Fieldmap::lowResolutionWarning (double squareError, double maxError) protected
Definition at line 626 of file Fieldmap.cpp.
References endl(), ERRORMSG, Filename_m, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), IpplInfo::myNode(), and typeset_msg().
Referenced by checkMap().
missingValuesWarning()
void _Fieldmap::missingValuesWarning () protected
Definition at line 590 of file Fieldmap.cpp.
References Filename_m, and lines_read_m.
Referenced by interpretLine().
noFieldmapWarning()
void _Fieldmap::noFieldmapWarning () protected
Definition at line 618 of file Fieldmap.cpp.
References Filename_m.
Referenced by _Astra1DDynamic::_Astra1DDynamic(), _Astra1DDynamic_fast::_Astra1DDynamic_fast(), _Astra1DElectroStatic::_Astra1DElectroStatic(), _Astra1DElectroStatic_fast::_Astra1DElectroStatic_fast(), _Astra1DMagnetoStatic::_Astra1DMagnetoStatic(), _Astra1DMagnetoStatic_fast::_Astra1DMagnetoStatic_fast(), _FM1DDynamic::_FM1DDynamic(), _FM1DDynamic_fast::_FM1DDynamic_fast(), _FM1DElectroStatic::_FM1DElectroStatic(), _FM1DElectroStatic_fast::_FM1DElectroStatic_fast(), _FM1DMagnetoStatic::_FM1DMagnetoStatic(), _FM1DMagnetoStatic_fast::_FM1DMagnetoStatic_fast(), _FM1DProfile1::_FM1DProfile1(), _FM1DProfile2::_FM1DProfile2(), _FM2DDynamic::_FM2DDynamic(), _FM2DElectroStatic::_FM2DElectroStatic(), _FM2DMagnetoStatic::_FM2DMagnetoStatic(), and _FM3DDynamic::_FM3DDynamic().
readHeader()
MapType _Fieldmap::readHeader (std::string Filename) static
Definition at line 282 of file Fieldmap.cpp.
References endl(), IpplInfo::getComm(), getLine(), lines_read_m, name, PAssert, T1DDynamic, T1DElectroStatic, T1DMagnetoStatic, T1DProfile1, T2DDynamic, T2DElectroStatic, T2DMagnetoStatic, T3DDynamic, T3DDynamicH5Block, T3DElectroStatic, T3DMagnetoStatic, T3DMagnetoStatic_Extended, T3DMagnetoStaticH5Block, TAstraDynamic, TAstraElectroStatic, TAstraMagnetoStatic, and UNKNOWN.
Referenced by getFieldmap().
readMap() [1/2]
void _Fieldmap::readMap (std::string Filename) static
Definition at line 422 of file Fieldmap.cpp.
References FieldmapDictionary.
readMap() [2/2]
virtual void _Fieldmap::readMap () pure virtual
Implemented in _FM1DProfile1, _Astra1DDynamic_fast, _FM3DH5Block, _FM3DH5Block_nonscale, _FM3DMagnetoStaticH5Block, _FM3DH5BlockBase, _FM1DDynamic_fast, _FM1DDynamic, _FM1DElectroStatic, _FM1DElectroStatic_fast, _FM1DMagnetoStatic, _FM1DMagnetoStatic_fast, _FM2DDynamic, _Astra1DDynamic, _FM1DProfile2, _FM3DDynamic, _Astra1DElectroStatic, _Astra1DMagnetoStatic, _Astra1DMagnetoStatic_fast, _FM2DElectroStatic, _FM2DMagnetoStatic, _FM3DMagnetoStatic, _FM3DMagnetoStaticExtended, _Astra1D_fast, and _Astra1DElectroStatic_fast.
Referenced by Solenoid::goOnline(), TravelingWave::goOnline(), RBend3D::goOnline(), RFCavity::goOnline(), and Bend2D::readFieldMap().
setEdgeConstants()
void _Fieldmap::setEdgeConstants (const double & bendAngle, const double & entranceAngle, const double & exitAngle) virtual
Reimplemented in _FM1DProfile2.
Definition at line 527 of file Fieldmap.cpp.
setFieldGap()
void _Fieldmap::setFieldGap (double gap) virtual
Reimplemented in _FM1DProfile1.
Definition at line 730 of file Fieldmap.cpp.
setFieldLength()
void _Fieldmap::setFieldLength (const double &) virtual
Definition at line 530 of file Fieldmap.cpp.
setFrequency()
virtual void _Fieldmap::setFrequency (double freq) pure virtual
Implemented in _FM3DH5BlockBase, _FM1DProfile1, _Astra1DDynamic_fast, _FM1DDynamic, _FM1DDynamic_fast, _FM1DElectroStatic, _FM1DElectroStatic_fast, _FM1DMagnetoStatic, _FM1DMagnetoStatic_fast, _FM2DDynamic, _Astra1DMagnetoStatic_fast, _Astra1D_fast, _Astra1DDynamic, _Astra1DElectroStatic, _Astra1DElectroStatic_fast, _Astra1DMagnetoStatic, _FM1DProfile2, _FM2DElectroStatic, _FM2DMagnetoStatic, _FM3DDynamic, _FM3DMagnetoStatic, and _FM3DMagnetoStaticExtended.
swap()
virtual void _Fieldmap::swap () pure virtual
Implemented in _FM3DH5BlockBase, _FM1DProfile1, _Astra1DDynamic_fast, _FM1DDynamic, _FM1DDynamic_fast, _FM1DElectroStatic, _FM1DElectroStatic_fast, _FM1DMagnetoStatic, _FM1DMagnetoStatic_fast, _FM2DDynamic, _Astra1DMagnetoStatic_fast, _Astra1D_fast, _Astra1DDynamic, _Astra1DElectroStatic, _Astra1DElectroStatic_fast, _Astra1DMagnetoStatic, _FM1DProfile2, _FM2DElectroStatic, _FM2DMagnetoStatic, _FM3DDynamic, _FM3DMagnetoStatic, and _FM3DMagnetoStaticExtended.
typeset_msg()
std::string _Fieldmap::typeset_msg (const std::string & msg, const std::string & title) static
Definition at line 649 of file Fieldmap.cpp.
References Physics::c.
Referenced by RFCavity::initialise(), lowResolutionWarning(), CCollimator::print(), FlexibleCollimator::print(), _Astra1DElectroStatic_fast::readMap(), _Astra1DMagnetoStatic::readMap(), _Astra1DMagnetoStatic_fast::readMap(), _FM2DElectroStatic::readMap(), _FM2DMagnetoStatic::readMap(), _Astra1DElectroStatic::readMap(), _FM3DMagnetoStatic::readMap(), _FM3DMagnetoStaticExtended::readMap(), _Astra1DDynamic::readMap(), _FM1DProfile2::readMap(), _FM3DDynamic::readMap(), _FM1DMagnetoStatic_fast::readMap(), _FM2DDynamic::readMap(), _FM1DMagnetoStatic::readMap(), _FM1DDynamic::readMap(), _FM1DElectroStatic::readMap(), _FM1DElectroStatic_fast::readMap(), _FM1DDynamic_fast::readMap(), _FM3DH5Block_nonscale::readMap(), _FM3DMagnetoStaticH5Block::readMap(), _FM3DH5Block::readMap(), _Astra1DDynamic_fast::readMap(), and _FM1DProfile1::readMap().
write3DField()
void _Fieldmap::write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > & xrange, const std::pair< double, double > & yrange, const std::pair< double, double > & zrange, const std::vector< Vector_t > & ef, const std::vector< Vector_t > & bf) protected
Definition at line 734 of file Fieldmap.cpp.
References Util::combineFilePath(), endl(), Filename_m, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), IpplInfo::myNode(), and PAssert.
Referenced by _FM3DDynamic::readMap().
Member Data Documentation
alpha_numeric
std::string _Fieldmap::alpha_numeric static private
Definition at line 183 of file Fieldmap.h.
Referenced by getLine(), and interpreteEOF().
buffer_m
char _Fieldmap::buffer_m static private
Definition at line 182 of file Fieldmap.h.
Referenced by getLine(), and interpreteEOF().
FieldmapDictionary
std::map< std::string, _Fieldmap::FieldmapDescription > _Fieldmap::FieldmapDictionary = std::map<std::string, _Fieldmap::FieldmapDescription>() static private
Definition at line 198 of file Fieldmap.h.
Referenced by clearDictionary(), freeMap(), getFieldmap(), getListFieldmapNames(), and readMap().
Filename_m
std::string _Fieldmap::Filename_m protected
Definition at line 118 of file Fieldmap.h.
Referenced by _Astra1DDynamic::_Astra1DDynamic(), _Astra1DDynamic_fast::_Astra1DDynamic_fast(), _Astra1DElectroStatic::_Astra1DElectroStatic(), _Astra1DElectroStatic_fast::_Astra1DElectroStatic_fast(), _Astra1DMagnetoStatic::_Astra1DMagnetoStatic(), _Astra1DMagnetoStatic_fast::_Astra1DMagnetoStatic_fast(), _FM1DDynamic::_FM1DDynamic(), _FM1DDynamic_fast::_FM1DDynamic_fast(), _FM1DElectroStatic::_FM1DElectroStatic(), _FM1DElectroStatic_fast::_FM1DElectroStatic_fast(), _FM1DMagnetoStatic::_FM1DMagnetoStatic(), _FM1DMagnetoStatic_fast::_FM1DMagnetoStatic_fast(), _FM1DProfile1::_FM1DProfile1(), _FM1DProfile2::_FM1DProfile2(), _FM2DDynamic::_FM2DDynamic(), _FM2DElectroStatic::_FM2DElectroStatic(), _FM2DMagnetoStatic::_FM2DMagnetoStatic(), _FM3DDynamic::_FM3DDynamic(), _FM3DMagnetoStatic::_FM3DMagnetoStatic(), _FM3DMagnetoStaticExtended::_FM3DMagnetoStaticExtended(), checkMap(), _FM3DH5BlockBase::closeFile(), disableFieldmapWarning(), exceedingValuesWarning(), _FM3DH5BlockBase::getFieldInfo(), _Astra1DMagnetoStatic::getInfo(), _FM3DDynamic::getInfo(), _FM3DMagnetoStatic::getInfo(), _Astra1DElectroStatic::getInfo(), _FM3DMagnetoStaticExtended::getInfo(), _Astra1DDynamic::getInfo(), _FM1DProfile2::getInfo(), _Astra1DElectroStatic_fast::getInfo(), _FM2DElectroStatic::getInfo(), _FM2DMagnetoStatic::getInfo(), _Astra1DMagnetoStatic_fast::getInfo(), _FM2DDynamic::getInfo(), _FM1DDynamic::getInfo(), _FM1DDynamic_fast::getInfo(), _FM1DElectroStatic::getInfo(), _FM1DElectroStatic_fast::getInfo(), _FM1DMagnetoStatic::getInfo(), _FM1DMagnetoStatic_fast::getInfo(), _Astra1DDynamic_fast::getInfo(), _FM1DProfile1::getInfo(), _FM3DH5BlockBase::getInfo(), _FM3DH5BlockBase::getNumSteps(), _FM3DDynamic::getOnaxisEz(), _Astra1DDynamic::getOnaxisEz(), _FM1DDynamic_fast::getOnaxisEz(), _FM1DDynamic::getOnaxisEz(), _Astra1DDynamic_fast::getOnaxisEz(), _FM3DH5BlockBase::getResonanceFrequency(), interpretWarning(), lowResolutionWarning(), missingValuesWarning(), noFieldmapWarning(), _FM3DH5BlockBase::readField(), _Astra1DElectroStatic_fast::readMap(), _FM3DMagnetoStaticExtended::readMap(), _Astra1DMagnetoStatic_fast::readMap(), _FM2DElectroStatic::readMap(), _FM3DMagnetoStatic::readMap(), _FM2DMagnetoStatic::readMap(), _Astra1DElectroStatic::readMap(), _Astra1DMagnetoStatic::readMap(), _Astra1DDynamic::readMap(), _FM1DProfile2::readMap(), _FM3DDynamic::readMap(), _FM1DDynamic::readMap(), _FM1DElectroStatic_fast::readMap(), _FM1DMagnetoStatic_fast::readMap(), _FM1DMagnetoStatic::readMap(), _FM1DElectroStatic::readMap(), _FM2DDynamic::readMap(), _FM1DDynamic_fast::readMap(), _FM3DMagnetoStaticH5Block::readMap(), _FM3DH5Block_nonscale::readMap(), _FM3DH5Block::readMap(), _Astra1DDynamic_fast::readMap(), _FM1DProfile1::readMap(), _FM3DH5BlockBase::setStep(), and write3DField().
lines_read_m
int _Fieldmap::lines_read_m protected
Definition at line 119 of file Fieldmap.h.
Referenced by _Astra1DDynamic::_Astra1DDynamic(), _Astra1DElectroStatic::_Astra1DElectroStatic(), _Astra1DMagnetoStatic::_Astra1DMagnetoStatic(), _FM1DProfile2::_FM1DProfile2(), _FM2DDynamic::_FM2DDynamic(), _FM2DElectroStatic::_FM2DElectroStatic(), _FM2DMagnetoStatic::_FM2DMagnetoStatic(), _FM3DMagnetoStaticExtended::_FM3DMagnetoStaticExtended(), _Astra1D_fast::determineNumSamplingPoints(), exceedingValuesWarning(), getLine(), interpreteEOF(), interpretWarning(), missingValuesWarning(), and readHeader().
normalize_m
bool _Fieldmap::normalize_m protected
Definition at line 121 of file Fieldmap.h.
Referenced by _Astra1D_fast::_Astra1D_fast(), _Astra1DDynamic::_Astra1DDynamic(), _Astra1DElectroStatic::_Astra1DElectroStatic(), _Astra1DMagnetoStatic::_Astra1DMagnetoStatic(), _FM2DDynamic::_FM2DDynamic(), _FM2DElectroStatic::_FM2DElectroStatic(), _FM2DMagnetoStatic::_FM2DMagnetoStatic(), _FM3DMagnetoStatic::_FM3DMagnetoStatic(), _FM3DMagnetoStaticExtended::_FM3DMagnetoStaticExtended(), _FM1DMagnetoStatic_fast::normalizeField(), _Astra1D_fast::readFieldData(), _FM1DElectroStatic::readFileData(), _FM1DMagnetoStatic::readFileData(), _FM1DDynamic::readFileData(), _FM1DElectroStatic_fast::readFileData(), _FM1DDynamic_fast::readFileData(), _Astra1DElectroStatic_fast::readFileHeader(), _Astra1DMagnetoStatic_fast::readFileHeader(), _FM1DElectroStatic::readFileHeader(), _FM1DMagnetoStatic::readFileHeader(), _FM1DDynamic::readFileHeader(), _FM1DElectroStatic_fast::readFileHeader(), _FM1DMagnetoStatic_fast::readFileHeader(), _FM1DDynamic_fast::readFileHeader(), _Astra1DDynamic_fast::readFileHeader(), _Astra1DMagnetoStatic::readMap(), _FM3DMagnetoStatic::readMap(), _Astra1DElectroStatic::readMap(), _FM2DElectroStatic::readMap(), _FM3DMagnetoStaticExtended::readMap(), _FM2DMagnetoStatic::readMap(), _Astra1DDynamic::readMap(), _FM2DDynamic::readMap(), and _FM1DDynamic_fast::scaleField().
Type
MapType _Fieldmap::Type protected
Definition at line 115 of file Fieldmap.h.
Referenced by _Astra1DDynamic::_Astra1DDynamic(), _Astra1DDynamic_fast::_Astra1DDynamic_fast(), _Astra1DElectroStatic::_Astra1DElectroStatic(), _Astra1DElectroStatic_fast::_Astra1DElectroStatic_fast(), _Astra1DMagnetoStatic::_Astra1DMagnetoStatic(), _Astra1DMagnetoStatic_fast::_Astra1DMagnetoStatic_fast(), _FM1DDynamic::_FM1DDynamic(), _FM1DDynamic_fast::_FM1DDynamic_fast(), _FM1DElectroStatic::_FM1DElectroStatic(), _FM1DElectroStatic_fast::_FM1DElectroStatic_fast(), _FM1DMagnetoStatic::_FM1DMagnetoStatic(), _FM1DMagnetoStatic_fast::_FM1DMagnetoStatic_fast(), _FM1DProfile1::_FM1DProfile1(), _FM1DProfile2::_FM1DProfile2(), _FM2DDynamic::_FM2DDynamic(), _FM2DElectroStatic::_FM2DElectroStatic(), _FM2DMagnetoStatic::_FM2DMagnetoStatic(), _FM3DDynamic::_FM3DDynamic(), _FM3DH5Block::_FM3DH5Block(), _FM3DH5Block_nonscale::_FM3DH5Block_nonscale(), _FM3DMagnetoStatic::_FM3DMagnetoStatic(), _FM3DMagnetoStaticExtended::_FM3DMagnetoStaticExtended(), _FM3DMagnetoStaticH5Block::_FM3DMagnetoStaticH5Block(), and getType().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/Fieldmap.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/Fieldmap.cpp
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/Fieldmap.hpp