OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyPolynomialPatch Namespace Reference
PyOpal::PyPolynomialPatch Namespace Reference
Functions
PolynomialPatch * initialiseFromSolveFactory (NDGrid *points, boost::python::list values, int polyPatchOrder, int smoothingOrder)
py::list function (PolynomialPatch *patch, py::list point)
BOOST_PYTHON_MODULE (polynomial_patch)
Variables
const char * module_docstring = "polynomial_patch module returns the field"
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyPolynomialPatch::BOOST_PYTHON_MODULE (polynomial_patch)
Definition at line 66 of file PyPolynomialPatch.cpp.
References initialiseFromSolveFactory(), and PyOpal::ExceptionTranslation::registerExceptions().
function()
py::list PyOpal::PyPolynomialPatch::function (PolynomialPatch * patch, py::list point)
Definition at line 44 of file PyPolynomialPatch.cpp.
References interpolation::PolynomialPatch::getPointDimension().
Referenced by SDDS::parser::array_parser< Iterator >::array_parser(), SDDS::parser::associate_parser< Iterator >::associate_parser(), client::parser::expression< Iterator >::expression(), SDDS::parser::include_parser< Iterator >::include_parser(), client::code_gen::requirements::requirements(), and client::code_gen::StackEvaluator::StackEvaluator().
initialiseFromSolveFactory()
PolynomialPatch * PyOpal::PyPolynomialPatch::initialiseFromSolveFactory (NDGrid * points, boost::python::list values, int polyPatchOrder, int smoothingOrder)
Definition at line 21 of file PyPolynomialPatch.cpp.
References interpolation::NDGrid::clone(), and interpolation::PPSolveFactory::solve().
Referenced by BOOST_PYTHON_MODULE().
Variable Documentation
module_docstring
const char * PyOpal::PyPolynomialPatch::module_docstring = "polynomial_patch module returns the field"
Definition at line 64 of file PyPolynomialPatch.cpp.