OPAL (Object Oriented Parallel Accelerator Library): struct_for_each< Op, T1, T2, Functor > Struct Template Reference
struct_for_each< Op, T1, T2, Functor > Struct Template Reference
#include <PETE.h>
Public Types
typedef PETEBinaryReturn< typename T1::PETE_Return_t, typename T2::PETE_Return_t, Op >::type Return_t
Static Public Member Functions
static Return_t apply (PETE_TBTree< Op, T1, T2 > &node, Functor f)
Detailed Description
template<class Op, class T1, class T2, class Functor>
struct struct_for_each< Op, T1, T2, Functor >
Definition at line 489 of file PETE.h.
Member Typedef Documentation
Return_t
template<class Op, class T1, class T2, class Functor> typedef PETEBinaryReturn<typename T1::PETE_Return_t, typename T2::PETE_Return_t,Op>::type struct_for_each< Op, T1, T2, Functor >::Return_t
Definition at line 493 of file PETE.h.
Member Function Documentation
apply()
template<class Op, class T1, class T2, class Functor> static Return_t struct_for_each< Op, T1, T2, Functor >::apply (PETE_TBTree< Op, T1, T2 > & node, Functor f) inline static
Definition at line 496 of file PETE.h.
References for_each(), PETE_TBTree< Value_t, Left_t, Right_t >::Left, PETE_apply(), PETE_TBTree< Value_t, Left_t, Right_t >::Right, and PETE_TBTree< Value_t, Left_t, Right_t >::Value.
Referenced by for_each().
The documentation for this struct was generated from the following file:
ippl/src/PETE/PETE.h