OPAL (Object Oriented Parallel Accelerator Library): TSV_MetaCompareArrays< T1, T2, D > Struct Template Reference
TSV_MetaCompareArrays< T1, T2, D > Struct Template Reference
#include <TSVMetaCompare.h>
Static Public Member Functions
static bool apply (const T1 *lhs, const T2 *rhs)
Detailed Description
template<class T1, class T2, unsigned D>
struct TSV_MetaCompareArrays< T1, T2, D >
Definition at line 21 of file TSVMetaCompare.h.
Member Function Documentation
apply()
template<class T1 , class T2 , unsigned D> static bool TSV_MetaCompareArrays< T1, T2, D >::apply (const T1 * lhs, const T2 * rhs) inline static
Definition at line 24 of file TSVMetaCompare.h.
Referenced by TSV_MetaCompare< Vektor< T1, D >, Vektor< T2, D > >::apply(), TSV_MetaCompare< Tenzor< T1, D >, Tenzor< T2, D > >::apply(), Vektor< int, 3 >::operator==(), and Tenzor< T, D >::operator==().
The documentation for this struct was generated from the following file:
ippl/src/AppTypes/TSVMetaCompare.h