OPAL (Object Oriented Parallel Accelerator Library): SDDS::parser::array_parser< Iterator > Struct Template Reference
SDDS::parser::array_parser< Iterator > Struct Template Reference
#include <array.hpp>
Inherits grammar< Iterator, array(), skipper< Iterator > >.
Public Member Functions
array_parser (error_handler< Iterator > &_error_handler)
Public Attributes
qi::rule< Iterator, array(), skipper< Iterator > > start
qi::rule< Iterator, std::string(), skipper< Iterator > > array_name
qi::rule< Iterator, std::string(), skipper< Iterator > > array_symbol
qi::rule< Iterator, std::string(), skipper< Iterator > > array_units
qi::rule< Iterator, std::string(), skipper< Iterator > > array_description
qi::rule< Iterator, std::string(), skipper< Iterator > > array_format
qi::rule< Iterator, std::string(), skipper< Iterator > > array_group
qi::rule< Iterator, std::string(), skipper< Iterator > > units
qi::rule< Iterator, std::string(), skipper< Iterator > > string
qi::rule< Iterator, std::string(), skipper< Iterator > > quoted_string
qi::rule< Iterator, long(), skipper< Iterator > > array_field
qi::rule< Iterator, long(), skipper< Iterator > > array_dimensions
qi::rule< Iterator, ast::datatype, skipper< Iterator > > array_type
qi::rule< Iterator, ast::nil(), skipper< Iterator > > array_unsupported_pre
qi::rule< Iterator, ast::nil(), skipper< Iterator > > array_unsupported_post
qi::symbols< char, ast::datatype > arraytype
Detailed Description
template<typename Iterator>
struct SDDS::parser::array_parser< Iterator >
Definition at line 109 of file array.hpp.
Constructor & Destructor Documentation
array_parser()
template<typename Iterator > SDDS::parser::array_parser< Iterator >::array_parser (error_handler< Iterator > & _error_handler)
Definition at line 30 of file array_def.hpp.
References Physics::alpha, SDDS::parser::array_parser< Iterator >::array_description, SDDS::parser::array_parser< Iterator >::array_dimensions, SDDS::parser::array_parser< Iterator >::array_field, SDDS::parser::array_parser< Iterator >::array_format, SDDS::parser::array_parser< Iterator >::array_group, SDDS::parser::array_parser< Iterator >::array_name, SDDS::parser::array_parser< Iterator >::array_symbol, SDDS::parser::array_parser< Iterator >::array_type, SDDS::parser::array_parser< Iterator >::array_units, SDDS::parser::array_parser< Iterator >::array_unsupported_post, SDDS::parser::array_parser< Iterator >::array_unsupported_pre, SDDS::parser::array_parser< Iterator >::arraytype, SDDS::ast::CHARACTER, SDDS::ast::DOUBLE, SDDS::ast::FLOAT, PyOpal::PyAbstractTimeDependence::function(), SDDS::ast::LONG, SDDS::parser::array_parser< Iterator >::quoted_string, SDDS::ast::SHORT, SDDS::parser::array_parser< Iterator >::start, SDDS::ast::STRING, SDDS::parser::array_parser< Iterator >::string, and SDDS::parser::array_parser< Iterator >::units.
Member Data Documentation
array_description
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::array_parser< Iterator >::array_description
Definition at line 114 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
array_dimensions
template<typename Iterator > qi::rule<Iterator, long(), skipper<Iterator> > SDDS::parser::array_parser< Iterator >::array_dimensions
Definition at line 117 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
array_field
template<typename Iterator > qi::rule<Iterator, long(), skipper<Iterator> > SDDS::parser::array_parser< Iterator >::array_field
Definition at line 117 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
array_format
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::array_parser< Iterator >::array_format
Definition at line 114 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
array_group
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::array_parser< Iterator >::array_group
Definition at line 114 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
array_name
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::array_parser< Iterator >::array_name
Definition at line 114 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
array_symbol
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::array_parser< Iterator >::array_symbol
Definition at line 114 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
array_type
template<typename Iterator > qi::rule<Iterator, ast::datatype, skipper<Iterator> > SDDS::parser::array_parser< Iterator >::array_type
Definition at line 119 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
array_units
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::array_parser< Iterator >::array_units
Definition at line 114 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
array_unsupported_post
template<typename Iterator > qi::rule<Iterator, ast::nil(), skipper<Iterator> > SDDS::parser::array_parser< Iterator >::array_unsupported_post
Definition at line 120 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
array_unsupported_pre
template<typename Iterator > qi::rule<Iterator, ast::nil(), skipper<Iterator> > SDDS::parser::array_parser< Iterator >::array_unsupported_pre
Definition at line 120 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
arraytype
template<typename Iterator > qi::symbols<char, ast::datatype> SDDS::parser::array_parser< Iterator >::arraytype
Definition at line 122 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
quoted_string
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::array_parser< Iterator >::quoted_string
Definition at line 114 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
start
template<typename Iterator > qi::rule<Iterator, array(), skipper<Iterator> > SDDS::parser::array_parser< Iterator >::start
Definition at line 113 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
string
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::array_parser< Iterator >::string
Definition at line 114 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
units
template<typename Iterator > qi::rule<Iterator, std::string(), skipper<Iterator> > SDDS::parser::array_parser< Iterator >::units
Definition at line 114 of file array.hpp.
Referenced by SDDS::parser::array_parser< Iterator >::array_parser().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/optimizer/Util/SDDSParser/array.hpp
/psi/home/gsell/data/src/OPAL/src/optimizer/Util/SDDSParser/array_def.hpp