OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Message/GlobalComm.h File Reference
GlobalComm.h File Reference
#include "Message/GlobalComm.hpp"
Functions
template<class InputIterator , class OutputIterator , class ReduceOp >
bool reduce (Communicate &, InputIterator, InputIterator, OutputIterator, const ReduceOp &, bool *IncludeVal=0)
template<class InputIterator , class OutputIterator , class ReduceOp >
bool reduce (InputIterator, InputIterator, OutputIterator, const ReduceOp &, bool *IncludeVal=0)
template<class T , class ReduceOp >
bool reduce (Communicate &comm, T &input, T &output, const ReduceOp &op)
template<class T , class ReduceOp >
bool reduce (T &input, T &output, const ReduceOp &op)
template<class T , class ReduceOp >
bool reduce_masked (Communicate &comm, T &input, T &output, const ReduceOp &op, bool IncludeVal)
template<class T , class ReduceOp >
bool reduce_masked (T &input, T &output, const ReduceOp &op, bool IncludeVal)
template<class InputIterator , class RandomIterator , class ScatterOp >
bool scatter (Communicate &, InputIterator, InputIterator, RandomIterator, int *, int *, const ScatterOp &)
template<class InputIterator , class RandomIterator , class ScatterOp >
bool scatter (InputIterator, InputIterator, RandomIterator, int *, int *, const ScatterOp &)
template<typename T >
void gather (const T *input, T *output, int count, int root=0)
template<typename T >
void scatter (const T *input, T *output, int count, int root=0)
template<typename T , class Op >
void reduce (const T *input, T *output, int count, Op op, int root=0)
template<typename T , class Op >
void new_reduce (const T *input, T *output, int count, Op op, int root=0)
template<typename T , class Op >
void new_reduce (T *inout, int count, Op op, int root=0)
template<typename T , class Op >
void reduce (const T &input, T &output, int count, Op op, int root=0)
template<typename T , class Op >
void allreduce (const T *input, T *output, int count, Op op)
template<typename T , class Op >
void allreduce (const T &input, T &output, int count, Op op)
template<typename T , class Op >
void allreduce (T *inout, int count, Op op)
template<typename T , class Op >
void allreduce (T &inout, int count, Op op)
Function Documentation
allreduce() [1/4]
template<typename T , class Op > void allreduce (const T * input, T * output, int count, Op op)
Definition at line 510 of file GlobalComm.hpp.
References IpplInfo::getComm().
Referenced by Distribution::adjustPhaseSpace(), allreduce(), Undulator::apply(), MultiBunchHandler::calcBunchBeamParameters(), PartBunchBase< double, 3 >::calcGammas_cycl(), ParallelCyclotronTracker::checkFileMomentum(), DistributionMoments::computeDebyeLength(), DistributionMoments::computeMeanKineticEnergy(), DistributionMoments::computeMeans(), DistributionMoments::computeNormalizedEmittance(), ParallelCyclotronTracker::computePathLengthUpdate(), DistributionMoments::computePercentiles(), LossDataSink::computeSetStatistics(), DistributionMoments::computeStatistics(), PartBunchBase< double, 3 >::countTotalNumPerBunch(), ParallelCyclotronTracker::deleteParticle(), DistributionMoments::determinePercentilesDetail(), PeakFinder::evaluate(), ParallelTTracker::evenlyDistributeParticles(), BeamStrippingPhysics::gatherStatistics(), ScatteringPhysics::gatherStatistics(), PartBunchBase< double, 3 >::get_bounds(), AmrParticleBase< PLayout >::getGlobalBounds_m(), LossDataSink::hasTurnInformations(), ParticleSpatialLayout< T, Dim, Mesh >::new_swap_particles(), LossDataSink::splitSets(), BoxLibLayout< T, Dim >::update(), and AmrYtWriter::writeBunch().
allreduce() [2/4]
template<typename T , class Op > void allreduce (const T & input, T & output, int count, Op op)
Definition at line 520 of file GlobalComm.hpp.
References allreduce().
allreduce() [3/4]
template<typename T , class Op > void allreduce (T * inout, int count, Op op)
Definition at line 526 of file GlobalComm.hpp.
References IpplInfo::getComm().
allreduce() [4/4]
template<typename T , class Op > void allreduce (T & inout, int count, Op op)
Definition at line 537 of file GlobalComm.hpp.
References allreduce().
gather()
template<typename T > void gather (const T * input, T * output, int count, int root = 0)
Definition at line 449 of file GlobalComm.hpp.
References IpplInfo::getComm().
Referenced by PartBunchBase< double, 3 >::calcNumPartsOutside(), PartBunchBase< double, 3 >::gatherLoadBalanceStatistics(), and IpplMemoryUsage::sample().
new_reduce() [1/2]
template<typename T , class Op > void new_reduce (const T * input, T * output, int count, Op op, int root = 0)
Definition at line 477 of file GlobalComm.hpp.
References IpplInfo::getComm().
Referenced by MemoryProfiler::compute().
new_reduce() [2/2]
template<typename T , class Op > void new_reduce (T * inout, int count, Op op, int root = 0)
Definition at line 488 of file GlobalComm.hpp.
References IpplInfo::getComm(), and IpplInfo::myNode().
reduce() [1/6]
template<class InputIterator , class OutputIterator , class ReduceOp > bool reduce (Communicate & , InputIterator , InputIterator , OutputIterator , const ReduceOp & , bool * IncludeVal = 0)
Definition at line 55 of file GlobalComm.hpp.
References IpplInfo::abort(), Communicate::broadcast_others(), COMM_ANY_NODE, COMM_REDUCE_CYCLE, COMM_REDUCE_RECV_TAG, COMM_REDUCE_SEND_TAG, Message::MsgItem::data(), endl(), ERRORMSG, getMessage(), Communicate::getNodes(), Message::item(), Communicate::myNode(), TagMaker::next_tag(), PETE_apply(), putMessage(), Communicate::receive_block(), Communicate::send(), and Message::size().
Referenced by PartBunchBase< double, 3 >::boundp_destroyT(), PartBunchBase< double, 3 >::calcGammas(), PartBunchBase< double, 3 >::calcLineDensity(), ParallelCyclotronTracker::calcMeanP(), PartBunchBase< double, 3 >::calcMeanPhi(), ParallelCyclotronTracker::calcMeanR(), GreenWakeFunction::CalcWakeFFT(), ParallelCyclotronTracker::checkNumPart(), Distribution::checkParticleNumber(), Vacuum::checkVacuum(), BareField< T1, D >::CompressedFraction(), PeakFinder::computeCentroid_m(), ParallelTTracker::computeExternalFields(), ParallelTTracker::computeParticleMatterInteraction(), MGPoissonSolver::computePotential(), Distribution::createDistributionFromFile(), PeakFinder::createHistogram_m(), ParallelCyclotronTracker::deleteParticle(), PartBunchBase< double, 3 >::destroyT(), Stripper::doFinaliseCheck(), CCollimator::doFinaliseCheck(), Distribution::doRestartOpalCycl(), Distribution::emitParticles(), Distribution::fillEBinHistogram(), AmrPartBunch::gatherLevelStatistics(), PartBunchBase< double, 3 >::getIfBeamEmitting(), PartBunchBase< double, 3 >::getLastEmittedEnergyBin(), Distribution::getMaxTOrZ(), Distribution::getMinTOrZ(), Distribution::getNumberOfParticlesInFile(), PartBins::getTotalNum(), PartBins::getTotalNumPerBin(), ParallelTTracker::hasEndOfLineReached(), LossDataSink::hasNoParticlesToDump(), ParticleAttrib< ParticleOrigin >::isDirty(), IpplMessageCounterRegion::print(), Timing::print(), Distribution::printDist(), IpplCounter::printIt(), MGPoissonSolver::printLoadBalanceStats(), PartBunchBase< double, 3 >::Rebin(), reduce(), Distribution::reflectDistribution(), PartBunchBase< double, 3 >::resetPartBinID2(), PartBins::resetPartInBin_cyc(), LossDataSink::saveH5(), Distribution::setupEmissionModelNone(), Distribution::shiftBeam(), PartBins::sortArray(), PartBunchBase< double, 3 >::updateNumTotal(), Distribution::writeOutFileHeader(), Distribution::writeOutFileInjection(), and ParallelTTracker::writePhaseSpace().
reduce() [2/6]
template<class InputIterator , class OutputIterator , class ReduceOp > bool reduce (InputIterator , InputIterator , OutputIterator , const ReduceOp & , bool * IncludeVal = 0)
Definition at line 194 of file GlobalComm.hpp.
References IpplInfo::Comm, and reduce().
reduce() [3/6]
template<class T , class ReduceOp > bool reduce (Communicate & comm, T & input, T & output, const ReduceOp & op)
Definition at line 71 of file GlobalComm.h.
References reduce_masked().
reduce() [4/6]
template<class T , class ReduceOp > bool reduce (T & input, T & output, const ReduceOp & op)
Definition at line 78 of file GlobalComm.h.
References reduce_masked().
reduce() [5/6]
template<typename T , class Op > void reduce (const T * input, T * output, int count, Op op, int root = 0)
Definition at line 467 of file GlobalComm.hpp.
References IpplInfo::getComm().
reduce() [6/6]
template<typename T , class Op > void reduce (const T & input, T & output, int count, Op op, int root = 0)
Definition at line 504 of file GlobalComm.hpp.
References reduce().
reduce_masked() [1/2]
template<class T , class ReduceOp > bool reduce_masked (Communicate & comm, T & input, T & output, const ReduceOp & op, bool IncludeVal)
Definition at line 208 of file GlobalComm.hpp.
References IpplInfo::abort(), Communicate::broadcast_others(), COMM_ANY_NODE, COMM_REDUCE_CYCLE, COMM_REDUCE_RECV_TAG, COMM_REDUCE_SEND_TAG, getMessage(), Communicate::getNodes(), Communicate::myNode(), Hypervolume::n, TagMaker::next_tag(), PETE_apply(), putMessage(), Communicate::receive_block(), Communicate::send(), Message::size(), and Attrib::Legacy::Distribution::T.
Referenced by reduce(), reduce_masked(), and Reduction().
reduce_masked() [2/2]
template<class T , class ReduceOp > bool reduce_masked (T & input, T & output, const ReduceOp & op, bool IncludeVal)
Definition at line 334 of file GlobalComm.hpp.
References IpplInfo::Comm, and reduce_masked().
scatter() [1/3]
template<class InputIterator , class RandomIterator , class ScatterOp > bool scatter (Communicate & , InputIterator , InputIterator , RandomIterator , int * , int * , const ScatterOp &)
Definition at line 353 of file GlobalComm.hpp.
References COMM_ANY_NODE, COMM_REDUCE_CYCLE, COMM_REDUCE_SCATTER_TAG, Message::MsgItem::data(), endl(), ERRORMSG, Message::get(), getMessage(), Communicate::getNodes(), Message::item(), Communicate::myNode(), TagMaker::next_tag(), PETE_apply(), putMessage(), Communicate::receive_block(), Communicate::send(), and Message::size().
Referenced by BinaryRepartition(), BoxLibParticle< PLayout >::scatter(), and scatter().
scatter() [2/3]
template<class InputIterator , class RandomIterator , class ScatterOp > bool scatter (InputIterator , InputIterator , RandomIterator , int * , int * , const ScatterOp &)
Definition at line 440 of file GlobalComm.hpp.
References IpplInfo::Comm, and scatter().
scatter() [3/3]
template<typename T > void scatter (const T * input, T * output, int count, int root = 0)
Definition at line 458 of file GlobalComm.hpp.
References IpplInfo::getComm().