OPAL (Object Oriented Parallel Accelerator Library): ippl/src/AppTypes/AntiSymTenzor.h File Reference
AntiSymTenzor.h File Reference
#include "Utility/PAssert.h"
#include "Message/Message.h"
#include "PETE/IpplExpressions.h"
#include "AppTypes/TSVMeta.h"
#include "AppTypes/Tenzor.h"
#include <iostream>
Classes
class AntiSymTenzor< T, D >
class AntiSymTenzor< T, D >::DontInitialize
class AntiSymTenzor< T, D >::AssignProxy
class AntiSymTenzor< T, 1 >
class AntiSymTenzor< T, 1 >::DontInitialize
class AntiSymTenzor< T, 1 >::AssignProxy
Functions
template<class T , unsigned D>
T trace (const AntiSymTenzor< T, D > &)
template<class T , unsigned D>
AntiSymTenzor< T, D > transpose (const AntiSymTenzor< T, D > &rhs)
template<class T >
T det (const AntiSymTenzor< T, 3 > &)
template<class T >
T det (const AntiSymTenzor< T, 2 > &t)
template<class T >
T det (const AntiSymTenzor< T, 1 > &)
template<class T , unsigned D>
Tenzor< T, D > cofactors (const AntiSymTenzor< T, D > &)
template<class T >
Tenzor< T, 3 > cofactors (const AntiSymTenzor< T, 3 > &rhs)
template<class T >
Tenzor< T, 2 > cofactors (const AntiSymTenzor< T, 2 > &rhs)
template<class T >
Tenzor< T, 1 > cofactors (const AntiSymTenzor< T, 1 > &)
template<class T , unsigned D>
AntiSymTenzor< T, D > operator- (const AntiSymTenzor< T, D > &op)
template<class T , unsigned D>
const AntiSymTenzor< T, D > & operator+ (const AntiSymTenzor< T, D > &op)
template<class T1 , class T2 , unsigned D>
Tenzor< typename PETEBinaryReturn< T1, T2, OpMultipply >::type, D > dot (const AntiSymTenzor< T1, D > &lhs, const AntiSymTenzor< T2, D > &rhs)
template<class T1 , class T2 , unsigned D>
Tenzor< typename PETEBinaryReturn< T1, T2, OpMultipply >::type, D > dot (const AntiSymTenzor< T1, D > &lhs, const Tenzor< T2, D > &rhs)
template<class T1 , class T2 , unsigned D>
Tenzor< typename PETEBinaryReturn< T1, T2, OpMultipply >::type, D > dot (const Tenzor< T1, D > &lhs, const AntiSymTenzor< T2, D > &rhs)
template<class T1 , class T2 , unsigned D>
Tenzor< typename PETEBinaryReturn< T1, T2, OpMultipply >::type, D > dot (const AntiSymTenzor< T1, D > &lhs, const SymTenzor< T2, D > &rhs)
template<class T1 , class T2 , unsigned D>
Tenzor< typename PETEBinaryReturn< T1, T2, OpMultipply >::type, D > dot (const SymTenzor< T1, D > &lhs, const AntiSymTenzor< T2, D > &rhs)
template<class T1 , class T2 , unsigned D>
Vektor< typename PETEBinaryReturn< T1, T2, OpMultipply >::type, D > dot (const Vektor< T1, D > &lhs, const AntiSymTenzor< T2, D > &rhs)
template<class T1 , class T2 , unsigned D>
Vektor< typename PETEBinaryReturn< T1, T2, OpMultipply >::type, D > dot (const AntiSymTenzor< T1, D > &lhs, const Vektor< T2, D > &rhs)
template<class T1 , class T2 , unsigned D>
PETEBinaryReturn< T1, T2, OpMultipply >::type dotdot (const AntiSymTenzor< T1, D > &lhs, const AntiSymTenzor< T2, D > &rhs)
template<class T1 , class T2 , unsigned D>
PETEBinaryReturn< T1, T2, OpMultipply >::type dotdot (const AntiSymTenzor< T1, D > &lhs, const Tenzor< T2, D > &rhs)
template<class T1 , class T2 , unsigned D>
PETEBinaryReturn< T1, T2, OpMultipply >::type dotdot (const Tenzor< T1, D > &lhs, const AntiSymTenzor< T2, D > &rhs)
template<class T1 , class T2 , unsigned D>
PETEBinaryReturn< T1, T2, OpMultipply >::type dotdot (const AntiSymTenzor< T1, D > &lhs, const SymTenzor< T2, D > &rhs)
template<class T1 , class T2 , unsigned D>
PETEBinaryReturn< T1, T2, OpMultipply >::type dotdot (const SymTenzor< T1, D > &lhs, const AntiSymTenzor< T2, D > &rhs)
template<class T , unsigned D>
std::ostream & operator<< (std::ostream &out, const AntiSymTenzor< T, D > &rhs)
Function Documentation
cofactors() [1/4]
template<class T , unsigned D> Tenzor<T,D> cofactors (const AntiSymTenzor< T, D > &) inline
Definition at line 514 of file AntiSymTenzor.h.
References PInsist.
cofactors() [2/4]
template<class T > Tenzor<T,3> cofactors (const AntiSymTenzor< T, 3 > & rhs) inline
Definition at line 520 of file AntiSymTenzor.h.
cofactors() [3/4]
template<class T > Tenzor<T,2> cofactors (const AntiSymTenzor< T, 2 > & rhs) inline
Definition at line 537 of file AntiSymTenzor.h.
cofactors() [4/4]
template<class T > Tenzor<T,1> cofactors (const AntiSymTenzor< T, 1 > &) inline
Definition at line 551 of file AntiSymTenzor.h.
det() [1/3]
template<class T > T det (const AntiSymTenzor< T, 3 > &) inline
Definition at line 486 of file AntiSymTenzor.h.
References Attrib::Legacy::Distribution::T.
Referenced by mslang::AffineTransformation::getInverse(), Bend2D::getSurfaceMesh(), and Matrix3D::inverse().
det() [2/3]
template<class T > T det (const AntiSymTenzor< T, 2 > & t) inline
Definition at line 493 of file AntiSymTenzor.h.
References Attrib::Legacy::Distribution::T.
det() [3/3]
template<class T > T det (const AntiSymTenzor< T, 1 > &) inline
Definition at line 502 of file AntiSymTenzor.h.
References Attrib::Legacy::Distribution::T.
dot() [1/7]
template<class T1 , class T2 , unsigned D> Tenzor<typename PETEBinaryReturn<T1,T2,OpMultipply>::type,D> dot (const AntiSymTenzor< T1, D > & lhs, const AntiSymTenzor< T2, D > & rhs) inline
Definition at line 602 of file AntiSymTenzor.h.
dot() [2/7]
template<class T1 , class T2 , unsigned D> Tenzor<typename PETEBinaryReturn<T1,T2,OpMultipply>::type,D> dot (const AntiSymTenzor< T1, D > & lhs, const Tenzor< T2, D > & rhs) inline
Definition at line 610 of file AntiSymTenzor.h.
dot() [3/7]
template<class T1 , class T2 , unsigned D> Tenzor<typename PETEBinaryReturn<T1,T2,OpMultipply>::type,D> dot (const Tenzor< T1, D > & lhs, const AntiSymTenzor< T2, D > & rhs) inline
Definition at line 618 of file AntiSymTenzor.h.
dot() [4/7]
template<class T1 , class T2 , unsigned D> Tenzor<typename PETEBinaryReturn<T1,T2,OpMultipply>::type,D> dot (const AntiSymTenzor< T1, D > & lhs, const SymTenzor< T2, D > & rhs) inline
Definition at line 626 of file AntiSymTenzor.h.
dot() [5/7]
template<class T1 , class T2 , unsigned D> Tenzor<typename PETEBinaryReturn<T1,T2,OpMultipply>::type,D> dot (const SymTenzor< T1, D > & lhs, const AntiSymTenzor< T2, D > & rhs) inline
Definition at line 634 of file AntiSymTenzor.h.
dot() [6/7]
template<class T1 , class T2 , unsigned D> Vektor<typename PETEBinaryReturn<T1,T2,OpMultipply>::type,D> dot (const Vektor< T1, D > & lhs, const AntiSymTenzor< T2, D > & rhs) inline
Definition at line 642 of file AntiSymTenzor.h.
dot() [7/7]
template<class T1 , class T2 , unsigned D> Vektor<typename PETEBinaryReturn<T1,T2,OpMultipply>::type,D> dot (const AntiSymTenzor< T1, D > & lhs, const Vektor< T2, D > & rhs) inline
Definition at line 649 of file AntiSymTenzor.h.
dotdot() [1/5]
template<class T1 , class T2 , unsigned D> PETEBinaryReturn<T1,T2,OpMultipply>::type dotdot (const AntiSymTenzor< T1, D > & lhs, const AntiSymTenzor< T2, D > & rhs) inline
Definition at line 660 of file AntiSymTenzor.h.
dotdot() [2/5]
template<class T1 , class T2 , unsigned D> PETEBinaryReturn<T1,T2,OpMultipply>::type dotdot (const AntiSymTenzor< T1, D > & lhs, const Tenzor< T2, D > & rhs) inline
Definition at line 668 of file AntiSymTenzor.h.
dotdot() [3/5]
template<class T1 , class T2 , unsigned D> PETEBinaryReturn<T1,T2,OpMultipply>::type dotdot (const Tenzor< T1, D > & lhs, const AntiSymTenzor< T2, D > & rhs) inline
Definition at line 676 of file AntiSymTenzor.h.
dotdot() [4/5]
template<class T1 , class T2 , unsigned D> PETEBinaryReturn<T1,T2,OpMultipply>::type dotdot (const AntiSymTenzor< T1, D > & lhs, const SymTenzor< T2, D > & rhs) inline
Definition at line 684 of file AntiSymTenzor.h.
dotdot() [5/5]
template<class T1 , class T2 , unsigned D> PETEBinaryReturn<T1,T2,OpMultipply>::type dotdot (const SymTenzor< T1, D > & lhs, const AntiSymTenzor< T2, D > & rhs) inline
Definition at line 692 of file AntiSymTenzor.h.
operator+()
template<class T , unsigned D> const AntiSymTenzor<T,D>& operator+ (const AntiSymTenzor< T, D > & op) inline
Definition at line 574 of file AntiSymTenzor.h.
operator-()
template<class T , unsigned D> AntiSymTenzor<T,D> operator- (const AntiSymTenzor< T, D > & op) inline
Definition at line 566 of file AntiSymTenzor.h.
operator<<()
template<class T , unsigned D> std::ostream& operator<< (std::ostream & out, const AntiSymTenzor< T, D > & rhs) inline
Definition at line 701 of file AntiSymTenzor.h.
trace()
template<class T , unsigned D> T trace (const AntiSymTenzor< T, D > &) inline
Definition at line 472 of file AntiSymTenzor.h.
References Attrib::Legacy::Distribution::T.
transpose()
template<class T , unsigned D> AntiSymTenzor<T,D> transpose (const AntiSymTenzor< T, D > & rhs) inline
Definition at line 477 of file AntiSymTenzor.h.
Referenced by CoordinateSystemTrafo::invert(), CoordinateSystemTrafo::rotateFrom(), and CoordinateSystemTrafo::transformFrom().