OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Message/MessageFunctions.cpp File Reference
MessageFunctions.cpp File Reference
#include "Message/Message.h"
#include "Message/Communicate.h"
#include "Utility/Inform.h"
#include "Utility/IpplInfo.h"
#include "Utility/PAssert.h"
#include <new>
#include <memory>
#include <cstdlib>
#include <cstddef>
Functions
std::ostream & operator<< (std::ostream &o, const Message &m)
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & o, const Message & m)
Definition at line 195 of file MessageFunctions.cpp.
References endl(), Message::item(), Message::MsgItem::numBytes(), Message::MsgItem::numElems(), Message::removed(), Message::size(), and Message::MsgItem::willNeedDelete().