OPAL (Object Oriented Parallel Accelerator Library): BendBase Class Reference
BendBase Class Reference abstract
#include <BendBase.h>
Public Member Functions
BendBase ()
BendBase (const BendBase &)
BendBase (const std::string &)
virtual bool bends () const
Indicates that element bends the beam.
double getChordLength () const
virtual void setBendAngle (double angle)
double getBendAngle () const
virtual void setEntranceAngle (double entranceAngle)
double getEntranceAngle () const
virtual double getExitAngle () const =0
void setFullGap (double)
double getFullGap () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
double getDesignEnergy () const
std::vector< Vector_t > getDesignPath () const
void setFieldAmplitude (double k0, double k0s)
double getFieldAmplitude () const
void setFieldMapFN (std::string fileName)
std::string getFieldMapFN () const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
virtual EMField & getField ()=0
Return field.
virtual const EMField & getField () const =0
Return field.
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B)
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField)=0
virtual void finalise ()=0
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual void getDimensions (double &zBegin, double &zEnd) const =0
virtual ElementBase::ElementType getType () const
Get element type std::string.
virtual void setComponentType (std::string)
virtual std::string getComponentType () const
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual void accept (BeamlineVisitor &visitor) const =0
Apply visitor.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Member Functions
double calcDesignRadius (double fieldAmplitude) const
Calculate design radius from design energy and field amplitude.
double calcFieldAmplitude (double radius) const
Calculate field amplitude from design energy and radius.
double calcBendAngle (double chordLength, double radius) const
Calculate bend angle from chord length and design radius.
double calcDesignRadius (double chordLength, double angle) const
Calculate design radius from chord length and bend angle.
double calcGamma () const
Calculate gamma from design energy.
double calcBetaGamma () const
Calculate beta*gamma from design energy.
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes
double chordLength_m
double angle_m
Bend angle.
double entranceAngle_m
Fieldmap * fieldmap_m
Magnet field map.
const bool fast_m = false
Flag to turn on fast field calculation.
double gap_m
Full vertical gap of the magnets.
double designEnergy_m
Bend design energy (eV).
bool designEnergyChangeable_m
std::vector< Vector_t > refTrajMap_m
Map of reference particle trajectory.
double fieldAmplitudeX_m
double fieldAmplitudeY_m
double fieldAmplitude_m
Field amplitude.
std::string fileName_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Additional Inherited Members
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 11 of file BendBase.h.
Constructor & Destructor Documentation
BendBase() [1/3]
BendBase::BendBase ()
Definition at line 7 of file BendBase.cpp.
BendBase() [2/3]
BendBase::BendBase (const BendBase & right)
Definition at line 11 of file BendBase.cpp.
BendBase() [3/3]
BendBase::BendBase (const std::string & name)
Definition at line 27 of file BendBase.cpp.
Member Function Documentation
bends()
bool BendBase::bends () const inline virtual
Indicates that element bends the beam.
Implements Component.
Definition at line 77 of file BendBase.h.
calcBendAngle()
double BendBase::calcBendAngle (double chordLength, double radius) const protected
Calculate bend angle from chord length and design radius.
Definition at line 79 of file BendBase.cpp.
References asin().
Referenced by Bend2D::findIdealBendParameters().
calcBetaGamma()
double BendBase::calcBetaGamma () const protected
Calculate beta*gamma from design energy.
Definition at line 95 of file BendBase.cpp.
References calcGamma(), pow(), and sqrt().
Referenced by calcDesignRadius(), calcFieldAmplitude(), Bend2D::calculateBendAngle(), Bend2D::calculateRefTrajectory(), and RBend3D::trackRefParticleThrough().
calcDesignRadius() [1/2]
double BendBase::calcDesignRadius (double fieldAmplitude) const protected
Calculate design radius from design energy and field amplitude.
Definition at line 61 of file BendBase.cpp.
References abs(), Physics::c, calcBetaGamma(), PartBunchBase< T, Dim >::getM(), PartBunchBase< T, Dim >::getQ(), and Component::RefPartBunch_m.
Referenced by RBend::findChordLength(), Bend2D::findIdealBendParameters(), and Bend2D::isFieldZero().
calcDesignRadius() [2/2]
double BendBase::calcDesignRadius (double chordLength, double angle) const protected
Calculate design radius from chord length and bend angle.
Definition at line 84 of file BendBase.cpp.
References sin().
calcFieldAmplitude()
double BendBase::calcFieldAmplitude (double radius) const protected
Calculate field amplitude from design energy and radius.
Definition at line 70 of file BendBase.cpp.
References Physics::c, calcBetaGamma(), PartBunchBase< T, Dim >::getM(), PartBunchBase< T, Dim >::getQ(), and Component::RefPartBunch_m.
Referenced by Bend2D::estimateFieldAdjustmentStep(), Bend2D::findIdealBendParameters(), RBend3D::initialise(), and Bend2D::setBendStrength().
calcGamma()
double BendBase::calcGamma () const protected
Calculate gamma from design energy.
Definition at line 89 of file BendBase.cpp.
References designEnergy_m, PartBunchBase< T, Dim >::getM(), and Component::RefPartBunch_m.
Referenced by calcBetaGamma(), Bend2D::calculateRefTrajectory(), and RBend3D::trackRefParticleThrough().
getBendAngle()
double BendBase::getBendAngle () const inline
Definition at line 92 of file BendBase.h.
References angle_m.
Referenced by OpalBeamline::compute3DLattice(), RBend::findChordLength(), RBend3D::getExitAngle(), CSRIGFWakeFunction::initialize(), CSRWakeFunction::initialize(), OpalBeamline::save3DInput(), OpalBeamline::save3DLattice(), RBend::setEntranceAngle(), and Bend2D::setFieldCalcParam().
getChordLength()
double BendBase::getChordLength () const inline
Definition at line 82 of file BendBase.h.
References chordLength_m.
Referenced by OpalBeamline::compute3DLattice(), and Bend2D::setFieldCalcParam().
getDesignEnergy()
double BendBase::getDesignEnergy () const inline virtual
Reimplemented from Component.
Definition at line 126 of file BendBase.h.
References designEnergy_m.
Referenced by OpalBeamline::activateElements(), and ThickTracker::visitSBend().
getDesignPath()
std::vector< Vector_t > BendBase::getDesignPath () const
Definition at line 43 of file BendBase.cpp.
References refTrajMap_m.
Referenced by OpalBeamline::compute3DLattice(), and OpalBeamline::save3DLattice().
getEntranceAngle()
double BendBase::getEntranceAngle () const inline
Definition at line 103 of file BendBase.h.
References entranceAngle_m.
Referenced by OpalBeamline::compute3DLattice(), RBend::findChordLength(), RBend3D::getExitAngle(), OpalBeamline::save3DInput(), RBend::setBendAngle(), Bend2D::setFieldCalcParam(), Bend2D::setupBendGeometry(), and ThickTracker::visitSBend().
getExitAngle()
virtual double BendBase::getExitAngle () const pure virtual
Implemented in Bend2D, and RBend3D.
getFieldAmplitude()
double BendBase::getFieldAmplitude () const inline
Definition at line 131 of file BendBase.h.
References fieldAmplitude_m.
getFieldMapFN()
std::string BendBase::getFieldMapFN () const inline
Definition at line 142 of file BendBase.h.
References fileName_m.
getFullGap()
double BendBase::getFullGap () const inline
Definition at line 113 of file BendBase.h.
References gap_m.
Referenced by Bend2D::getBoundingBoxInLabCoords(), and Bend2D::getSurfaceMesh().
setBendAngle()
void BendBase::setBendAngle (double angle) inline virtual
Reimplemented in RBend.
Definition at line 87 of file BendBase.h.
References angle_m.
Referenced by RBend::setBendAngle(), OpalSBend::update(), and OpalRBend3D::update().
setDesignEnergy()
void BendBase::setDesignEnergy (const double & energy, bool changeable = true) inline virtual
Reimplemented from Component.
Definition at line 118 of file BendBase.h.
References abs(), designEnergy_m, and designEnergyChangeable_m.
Referenced by OpalRBend::update(), OpalSBend::update(), and OpalRBend3D::update().
setEntranceAngle()
void BendBase::setEntranceAngle (double entranceAngle) inline virtual
Reimplemented in RBend, and Bend2D.
Definition at line 97 of file BendBase.h.
References entranceAngle_m.
Referenced by Bend2D::setEntranceAngle(), and OpalRBend3D::update().
setFieldAmplitude()
void BendBase::setFieldAmplitude (double k0, double k0s)
Definition at line 56 of file BendBase.cpp.
References fieldAmplitudeX_m, and fieldAmplitudeY_m.
Referenced by OpalRBend::update(), OpalSBend::update(), and OpalRBend3D::update().
setFieldMapFN()
void BendBase::setFieldMapFN (std::string fileName) inline
Definition at line 137 of file BendBase.h.
References fileName_m.
Referenced by OpalRBend::update(), OpalSBend::update(), and OpalRBend3D::update().
setFullGap()
void BendBase::setFullGap (double gap) inline
Definition at line 108 of file BendBase.h.
References abs(), and gap_m.
Referenced by OpalRBend::update(), OpalSBend::update(), and OpalRBend3D::update().
Member Data Documentation
angle_m
double BendBase::angle_m protected
Bend angle.
Definition at line 53 of file BendBase.h.
Referenced by Bend2D::estimateFieldAdjustmentStep(), Bend2D::findBendEffectiveLength(), Bend2D::findBendStrength(), Bend2D::findIdealBendParameters(), getBendAngle(), Bend2D::getEffectiveCenter(), Bend2D::getEffectiveLength(), Bend2D::getSurfaceMesh(), RBend3D::initialise(), Bend2D::isFieldZero(), Bend2D::print(), setBendAngle(), Bend2D::setBendEffectiveLength(), and Bend2D::setFieldBoundaries().
chordLength_m
double BendBase::chordLength_m protected
Definition at line 52 of file BendBase.h.
Referenced by Bend2D::adjustFringeFields(), getChordLength(), RBend3D::initialise(), Bend2D::isFieldZero(), Bend2D::setEngeOriginDelta(), and Bend2D::setupBendGeometry().
designEnergy_m
double BendBase::designEnergy_m protected
Bend design energy (eV).
Definition at line 61 of file BendBase.h.
Referenced by calcGamma(), getDesignEnergy(), Bend2D::isFieldZero(), Bend2D::print(), and setDesignEnergy().
designEnergyChangeable_m
bool BendBase::designEnergyChangeable_m protected
Definition at line 62 of file BendBase.h.
Referenced by setDesignEnergy().
entranceAngle_m
double BendBase::entranceAngle_m protected
Angle between incoming reference trajectory and the entrance face of the magnet (radians).
Definition at line 54 of file BendBase.h.
Referenced by Bend2D::calculateBendAngle(), Bend2D::calculateRefTrajectory(), Bend2D::findIdealBendParameters(), getEntranceAngle(), Bend2D::getSurfaceMesh(), RBend3D::initialise(), Bend2D::print(), setEntranceAngle(), Bend2D::setEntranceAngle(), Bend2D::setFieldBoundaries(), and RBend3D::trackRefParticleThrough().
fast_m
const bool BendBase::fast_m = false protected
Flag to turn on fast field calculation.
Definition at line 57 of file BendBase.h.
Referenced by RBend3D::initialise(), and Bend2D::initializeFieldMap().
fieldAmplitude_m
double BendBase::fieldAmplitude_m protected
Field amplitude.
Definition at line 71 of file BendBase.h.
Referenced by RBend3D::apply(), Bend2D::apply(), RBend3D::applyToReferenceParticle(), Bend2D::calculateBendAngle(), Bend2D::calculateRefTrajectory(), Bend2D::estimateFieldAdjustmentStep(), Bend2D::findBendStrength(), Bend2D::findIdealBendParameters(), getFieldAmplitude(), RBend3D::initialise(), Bend2D::isFieldZero(), Bend2D::print(), and Bend2D::setBendStrength().
fieldAmplitudeX_m
double BendBase::fieldAmplitudeX_m protected
Field amplitude in x direction. Value not updated if user defines strength with angle
Definition at line 66 of file BendBase.h.
Referenced by RBend::findChordLength(), Bend2D::findIdealBendParameters(), RBend3D::initialise(), Bend2D::isFieldZero(), and setFieldAmplitude().
fieldAmplitudeY_m
double BendBase::fieldAmplitudeY_m protected
Field amplitude in y direction. Value not updated if user defines strength with angle
Definition at line 68 of file BendBase.h.
Referenced by RBend::findChordLength(), Bend2D::findIdealBendParameters(), RBend3D::initialise(), Bend2D::isFieldZero(), and setFieldAmplitude().
fieldmap_m
Fieldmap* BendBase::fieldmap_m protected
Magnet field map.
Definition at line 56 of file BendBase.h.
Referenced by RBend3D::apply(), RBend3D::applyToReferenceParticle(), Bend2D::getEntranceFringeFieldLength(), Bend2D::getExitFringeFieldLength(), RBend3D::getSurfaceMesh(), RBend3D::initialise(), Bend2D::initializeFieldMap(), RBend3D::isInside(), Bend2D::readFieldMap(), and Bend2D::setGapFromFieldMap().
fileName_m
std::string BendBase::fileName_m protected
Definition at line 73 of file BendBase.h.
Referenced by getFieldMapFN(), RBend3D::goOffline(), RBend3D::goOnline(), RBend3D::initialise(), Bend2D::initialise(), Bend2D::initializeFieldMap(), Bend2D::print(), Bend2D::readFieldMap(), setFieldMapFN(), and Bend2D::setupBendGeometry().
gap_m
double BendBase::gap_m protected
Full vertical gap of the magnets.
Definition at line 59 of file BendBase.h.
Referenced by Bend2D::calcEngeFunction(), Bend2D::calculateMapField(), Bend2D::findBendEffectiveLength(), getFullGap(), Bend2D::isInside(), Bend2D::print(), Bend2D::readFieldMap(), setFullGap(), and Bend2D::setGapFromFieldMap().
refTrajMap_m
std::vector<Vector_t> BendBase::refTrajMap_m protected
Map of reference particle trajectory.
Definition at line 64 of file BendBase.h.
Referenced by Bend2D::calculateRefTrajectory(), and getDesignPath().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/BendBase.h
src/Classic/AbsBeamline/BendBase.cpp