OPAL (Object Oriented Parallel Accelerator Library): VarRadiusGeometry Class Reference
VarRadiusGeometry Class Reference
#include <VarRadiusGeometry.h>
Public Member Functions
VarRadiusGeometry (double length, double rho, double s_0, double lambda_left, double lambda_right)
VarRadiusGeometry (const VarRadiusGeometry &right)
virtual ~VarRadiusGeometry ()
const VarRadiusGeometry & operator= (const VarRadiusGeometry &right)
virtual double getArcLength () const
virtual double getElementLength () const
virtual void setElementLength (double length)
double getRadius () const
void setRadius (const double &rho)
double getS0 () const
void setS0 (const double &s_0)
double getLambdaLeft () const
void setLambdaLeft (const double &lambda_left)
double getLambdaRight () const
void setLambdaRight (const double &lambda_right)
virtual Euclid3D getTransform (double fromS, double toS) const
virtual Euclid3D getEntranceFrame () const
virtual Euclid3D getExitFrame () const
Public Member Functions inherited from BGeometryBase
BGeometryBase ()
BGeometryBase (const BGeometryBase &right)
virtual ~BGeometryBase ()
const BGeometryBase & operator= (const BGeometryBase &right)
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
Private Attributes
double length_m
double rho_m
double s_0_m
double lambda_left_m
double lambda_right_m
Detailed Description
VarRadiusGeometry represents a Geometry with variable radius. Assuming
a Tanh model for fringe fields, the radius of curvature varies inversely
proportional with the fringe field. Such a magnet will follow the
trajectory of the reference particle. The origin is defined at the centre and extends from -length / 2 to
+length / 2. Transformations are calculated using a CoordinateTransformation object,
which integrates to find the reference trajectory.
Class category: AbsBeamline
$Author: Martin Duy Tat, Chris Rogers
Definition at line 57 of file VarRadiusGeometry.h.
Constructor & Destructor Documentation
VarRadiusGeometry() [1/2]
VarRadiusGeometry::VarRadiusGeometry (double length, double rho, double s_0, double lambda_left, double lambda_right) inline
Build VarRadiusGeometry with given length, centre radius of curvature and fringe field
Parameters
length -> Length of geometry
rho -> Centre radius of curvature of geometry
s_0 -> Length of central fringe field
lambda_left -> Length of left end fringe field
lambda_right -> Length of right end fringe field
Definition at line 136 of file VarRadiusGeometry.h.
VarRadiusGeometry() [2/2]
VarRadiusGeometry::VarRadiusGeometry (const VarRadiusGeometry & right) inline
Copy constructor
Definition at line 146 of file VarRadiusGeometry.h.
~VarRadiusGeometry()
VarRadiusGeometry::~VarRadiusGeometry () inline virtual
Destructor
Definition at line 164 of file VarRadiusGeometry.h.
Member Function Documentation
getArcLength()
double VarRadiusGeometry::getArcLength () const inline virtual
Arc length along the design arc
Implements BGeometryBase.
Definition at line 167 of file VarRadiusGeometry.h.
References length_m.
getElementLength()
double VarRadiusGeometry::getElementLength () const inline virtual
Get element length measured along hte design arc
Implements BGeometryBase.
Definition at line 171 of file VarRadiusGeometry.h.
References length_m.
getEntranceFrame()
Euclid3D VarRadiusGeometry::getEntranceFrame () const inline virtual
Transform of the local coordinate system from the origin to the entrance of the element Equivalent to getTransform(0.0, getEntrance())
Reimplemented from BGeometryBase.
Definition at line 215 of file VarRadiusGeometry.h.
References BGeometryBase::getEntrance(), BGeometryBase::getOrigin(), and getTransform().
getExitFrame()
Euclid3D VarRadiusGeometry::getExitFrame () const inline virtual
Transform of the local coordinate system from the origin to the exit of the element Equivalent to getTransform(0.0, getExit())
Reimplemented from BGeometryBase.
Definition at line 219 of file VarRadiusGeometry.h.
References BGeometryBase::getExit(), BGeometryBase::getOrigin(), and getTransform().
getLambdaLeft()
double VarRadiusGeometry::getLambdaLeft () const inline
Get left end fringe field length
Definition at line 199 of file VarRadiusGeometry.h.
References lambda_left_m.
getLambdaRight()
double VarRadiusGeometry::getLambdaRight () const inline
Get right end fringe field length
Definition at line 207 of file VarRadiusGeometry.h.
References lambda_right_m.
getRadius()
double VarRadiusGeometry::getRadius () const inline
Get centre radius of curvature
Definition at line 183 of file VarRadiusGeometry.h.
References rho_m.
getS0()
double VarRadiusGeometry::getS0 () const inline
Get central fringe field length
Definition at line 191 of file VarRadiusGeometry.h.
References s_0_m.
getTransform()
Euclid3D VarRadiusGeometry::getTransform (double fromS, double toS) const virtual
Transform of the local coordinate system
Parameters
fromS -> Transform from this position
toS -> Transform to this position
Implements BGeometryBase.
Definition at line 34 of file VarRadiusGeometry.cpp.
References acos(), coordinatetransform::CoordinateTransform::calcReferenceTrajectory(), coordinatetransform::CoordinateTransform::getUnitTangentVector(), lambda_left_m, lambda_right_m, rho_m, s_0_m, Euclid3D::setX(), Euclid3D::setZ(), and Euclid3D::YRotation().
Referenced by getEntranceFrame(), and getExitFrame().
operator=()
const VarRadiusGeometry & VarRadiusGeometry::operator= (const VarRadiusGeometry & right) inline
Assigment operator
Definition at line 154 of file VarRadiusGeometry.h.
References lambda_left_m, lambda_right_m, length_m, rho_m, and s_0_m.
setElementLength()
void VarRadiusGeometry::setElementLength (double length) inline virtual
Set arc length
Parameters
length -> Length of element
Reimplemented from BGeometryBase.
Definition at line 175 of file VarRadiusGeometry.h.
References length_m, and max().
Referenced by MultipoleTCurvedVarRadius::initialise().
setLambdaLeft()
void VarRadiusGeometry::setLambdaLeft (const double & lambda_left) inline
Set left end fringe field length
Parameters
lambda_left -> Left end fringe field length
Definition at line 203 of file VarRadiusGeometry.h.
References lambda_left_m.
Referenced by MultipoleTCurvedVarRadius::initialise().
setLambdaRight()
void VarRadiusGeometry::setLambdaRight (const double & lambda_right) inline
Set right end fringe field length
Parameters
lambda_right -> Right end fringe field length
Definition at line 211 of file VarRadiusGeometry.h.
References lambda_right_m.
Referenced by MultipoleTCurvedVarRadius::initialise().
setRadius()
void VarRadiusGeometry::setRadius (const double & rho) inline
Set centre radius of curvature
Parameters
rho -> Central radius of curvature
Definition at line 187 of file VarRadiusGeometry.h.
References rho_m.
Referenced by MultipoleTCurvedVarRadius::initialise().
setS0()
void VarRadiusGeometry::setS0 (const double & s_0) inline
Set central fringe field length
Parameters
s_0 -> Central fringe field length
Definition at line 195 of file VarRadiusGeometry.h.
References s_0_m.
Referenced by MultipoleTCurvedVarRadius::initialise().
Member Data Documentation
lambda_left_m
double VarRadiusGeometry::lambda_left_m private
Definition at line 129 of file VarRadiusGeometry.h.
Referenced by getLambdaLeft(), getTransform(), operator=(), and setLambdaLeft().
lambda_right_m
double VarRadiusGeometry::lambda_right_m private
Definition at line 130 of file VarRadiusGeometry.h.
Referenced by getLambdaRight(), getTransform(), operator=(), and setLambdaRight().
length_m
double VarRadiusGeometry::length_m private
Definition at line 126 of file VarRadiusGeometry.h.
Referenced by getArcLength(), getElementLength(), operator=(), and setElementLength().
rho_m
double VarRadiusGeometry::rho_m private
Definition at line 127 of file VarRadiusGeometry.h.
Referenced by getRadius(), getTransform(), operator=(), and setRadius().
s_0_m
double VarRadiusGeometry::s_0_m private
Definition at line 128 of file VarRadiusGeometry.h.
Referenced by getS0(), getTransform(), operator=(), and setS0().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/BeamlineGeometry/VarRadiusGeometry.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/BeamlineGeometry/VarRadiusGeometry.cpp