OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyProbe Namespace Reference
PyOpal::PyProbe Namespace Reference
Functions
BOOST_PYTHON_MODULE (probe)
Variables
const char * module_docstring = "probe contains the Probe class"
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyProbe::BOOST_PYTHON_MODULE (probe)
Definition at line 31 of file PyProbe.cpp.
References PyOpal::Globals::Initialise(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_element_class(), and PyOpal::ExceptionTranslation::registerExceptions().
Variable Documentation
module_docstring
const char* PyOpal::PyProbe::module_docstring = "probe contains the Probe class"
Definition at line 29 of file PyProbe.cpp.