OPAL (Object Oriented Parallel Accelerator Library): SIndexExpLoop< OP, Dim > Class Template Reference
SIndexExpLoop< OP, Dim > Class Template Reference
#include <SIndexAssign.hpp>
Static Public Member Functions
template<class RHS >
static void evaluate (SIndex< Dim > &si, typename SIndex< Dim >::iterator_iv &lsi, NDIndex< Dim > &dom, RHS &Rhs)
Detailed Description
template<class OP, unsigned int Dim>
class SIndexExpLoop< OP, Dim >
Definition at line 137 of file SIndexAssign.hpp.
Member Function Documentation
evaluate()
template<class OP , unsigned int Dim> template<class RHS > static void SIndexExpLoop< OP, Dim >::evaluate (SIndex< Dim > & si, typename SIndex< Dim >::iterator_iv & lsi, NDIndex< Dim > & dom, RHS & Rhs) inline static
Definition at line 141 of file SIndexAssign.hpp.
References Dim, BrickCounter< Dim >::done(), endl(), ERRORMSG, for_each(), BrickCounter< Dim >::rewind(), and BrickCounter< Dim >::step().
Referenced by assign().
The documentation for this class was generated from the following file:
ippl/src/Index/SIndexAssign.hpp