OPAL (Object Oriented Parallel Accelerator Library): IpplInfo Class Reference
IpplInfo Class Reference
#include <IpplInfo.h>
Public Types
enum { KEEP = 0, REMOVE = 1 }
Public Member Functions
IpplInfo (int &, char **&, int removeargs=REMOVE, MPI_Comm mpicomm=MPI_COMM_WORLD)
IpplInfo ()
IpplInfo (const IpplInfo &)
~IpplInfo ()
IpplInfo & operator= (const IpplInfo &)
Static Public Member Functions
static void abort (const char *=0)
static void abortAllNodes (const char *=0)
static MPI_Comm getComm ()
static int myNode ()
static int getNodes ()
static int getContexts (int)
static int getProcesses (int, int)
static int getSMPs ()
static int getSMPNodes (int)
static int mySMP ()
static int mySMPNode ()
static int getArgc ()
static char ** getArgv ()
static bool useChecksums ()
static bool retransmit ()
static int maxFFTNodes ()
static int chunkSize ()
static bool perSMPParallelIO ()
static void printVersion (void)
static void printHelp ()
static const char * version ()
static const char * compileArch ()
static const char * compileDate ()
static const char * compileLine ()
static const char * compileMachine ()
static const char * compileOptions ()
static const char * compileUser ()
static void stash ()
static void pop ()
static void here ()
static void printStatistics (Inform &)
static void instantiateGlobals ()
static void deleteGlobals ()
Static Public Attributes
static Inform * Info = 0
static Inform * Warn = 0
static Inform * Error = 0
static Inform * Debug = 0
static Communicate * Comm = 0
static IpplStats * Stats = 0
static bool deferGuardCellFills = false
static bool noFieldCompression = false
static bool offsetStorage = false
static bool extraCompressChecks = false
Static Private Member Functions
static void param_error (const char *, const char *, const char *)
static void param_error (const char *, const char *, const char *, const char *)
static void find_smp_nodes ()
Static Private Attributes
static MPI_Comm communicator_m = MPI_COMM_WORLD
static int NumCreated = 0
static bool CommInitialized = false
static bool PrintStats = false
static bool NeedDeleteComm = false
static bool UseChecksums = false
static bool Retransmit = false
static int MyArgc = 0
static char ** MyArgv = 0
static int MyNode = 0
static int TotalNodes = 1
static int NumSMPs = 1
static int * SMPIDList = 0
static int * SMPNodeList = 0
static int MaxFFTNodes = 0
static int ChunkSize = 512*1024
static bool PerSMPParallelIO = false
static std::stack< StaticIpplInfo > stashedStaticMembers
Detailed Description
Definition at line 69 of file IpplInfo.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
KEEP
REMOVE
Definition at line 74 of file IpplInfo.h.
Constructor & Destructor Documentation
IpplInfo() [1/3]
IpplInfo::IpplInfo (int & argc, char **& argv, int removeargs = REMOVE, MPI_Comm mpicomm = MPI_COMM_WORLD)
Definition at line 158 of file IpplInfo.cpp.
References RNGXDivSequence::AdvanceSeed(), ChunkSize, Timer::clear(), Comm, CommInitialized, communicator_m, compileOptions(), CommCreator::create(), Debug, deferGuardCellFills, endl(), Error, extraCompressChecks, find_smp_nodes(), CommCreator::getAllLibraryNames(), DataConnectCreator::getAllMethodNames(), IpplStats::getTime(), Info, INFOMSG, INFORM_ALL_NODES, IpplRandom, KEEP, CommCreator::known(), DataConnectCreator::known(), MaxFFTNodes, MyArgc, MyArgv, MyNode, Hypervolume::n, NeedDeleteComm, noFieldCompression, NumCreated, offsetStorage, param_error(), PerSMPParallelIO, printHelp(), PrintStats, printVersion(), Retransmit, DataConnectCreator::setDefaultMethod(), DataConnectCreator::setDefaultNodes(), Inform::setOutputLevel(), Timer::start(), Stats, Timer::stop(), CommCreator::supported(), DataConnectCreator::supported(), TotalNodes, UseChecksums, and Warn.
IpplInfo() [2/3]
IpplInfo::IpplInfo ()
Definition at line 532 of file IpplInfo.cpp.
References Debug, Error, Info, INFORM_ALL_NODES, NumCreated, Stats, and Warn.
Referenced by abort(), and abortAllNodes().
IpplInfo() [3/3]
IpplInfo::IpplInfo (const IpplInfo &)
Definition at line 549 of file IpplInfo.cpp.
References Debug, Error, Info, INFORM_ALL_NODES, NumCreated, Stats, and Warn.
~IpplInfo()
IpplInfo::~IpplInfo ()
Definition at line 566 of file IpplInfo.cpp.
References Comm, CommInitialized, INFORM_ALL_NODES, MyArgv, NeedDeleteComm, NumCreated, printStatistics(), PrintStats, SMPIDList, SMPNodeList, and Stats.
Member Function Documentation
abort()
void IpplInfo::abort (const char * msg = 0) static
Definition at line 616 of file IpplInfo.cpp.
References Comm, endl(), ERRORMSG, INFORM_ALL_NODES, IpplInfo(), NeedDeleteComm, printStatistics(), and PrintStats.
Referenced by assign(), BinaryRepartition(), CommMPI::CommMPI(), DiscField< Dim >::create_files(), DiscConfig::DiscConfig(), DiscMeta::DiscMeta(), DiscField< Dim >::distribute_offsets(), for_each(), Interpolator::getFieldIter(), DiscParticle::initialize(), BareField< T1, D >::localElement(), DiscField< Dim >::open_df_file(), param_error(), DiscConfig::parse_config(), DiscField< Dim >::parse_config(), FieldDebugPrint< T, Dim >::print(), DiscField< Dim >::read(), DiscField< Dim >::read_data(), DiscField< Dim >::read_layout(), DiscField< Dim >::read_meta(), DiscField< Dim >::read_NDIndex(), DiscField< Dim >::read_offset(), reduce(), reduce_masked(), DiscConfig::replace_wildcards(), BareFieldIterator< T, Dim >::SetCurrentLocation(), BareField< T1, D >::setup(), ParticleSpatialLayout< T, Dim, Mesh >::swap_particles(), DiscField< Dim >::write(), DiscField< Dim >::write_layout(), and DiscField< Dim >::write_offset_and_data().
abortAllNodes()
void IpplInfo::abortAllNodes (const char * msg = 0) static
Definition at line 647 of file IpplInfo.cpp.
References endl(), ERRORMSG, getNodes(), INFORM_ALL_NODES, IPPL_ABORT_TAG, IpplInfo(), printStatistics(), and PrintStats.
Referenced by TSV_MetaCross< Vektor< T1, D >, Vektor< T2, D > >::apply().
chunkSize()
static int IpplInfo::chunkSize () inline static
Definition at line 206 of file IpplInfo.h.
References ChunkSize.
Referenced by DiscField< Dim >::distribute_offsets(), operator<<(), DiscField< Dim >::read(), and DiscField< Dim >::write_offset_and_data().
compileArch()
const char * IpplInfo::compileArch () static
Definition at line 804 of file IpplInfo.cpp.
References ippl_compile_arch.
compileDate()
const char * IpplInfo::compileDate () static
Definition at line 812 of file IpplInfo.cpp.
References ippl_compile_date.
Referenced by printVersion().
compileLine()
const char * IpplInfo::compileLine () static
Definition at line 820 of file IpplInfo.cpp.
References ippl_compile_line.
compileMachine()
const char * IpplInfo::compileMachine () static
Definition at line 828 of file IpplInfo.cpp.
References ippl_compile_machine.
Referenced by printVersion().
compileOptions()
const char * IpplInfo::compileOptions () static
Definition at line 836 of file IpplInfo.cpp.
References ippl_compile_options.
Referenced by IpplInfo(), and opalMain().
compileUser()
const char * IpplInfo::compileUser () static
Definition at line 844 of file IpplInfo.cpp.
References ippl_compile_user.
Referenced by printVersion().
deleteGlobals()
void IpplInfo::deleteGlobals () static
Definition at line 68 of file IpplInfo.cpp.
References Comm, Debug, Error, Info, Stats, and Warn.
Referenced by IpplInfoWrapper::~IpplInfoWrapper().
find_smp_nodes()
void IpplInfo::find_smp_nodes () static private
Definition at line 885 of file IpplInfo.cpp.
References COMM_ANY_NODE, vmap< Key, T, Compare >::end(), endl(), ERRORMSG, vmap< Key, T, Compare >::find(), getMessage(), getMessage_iter(), vmap< Key, T, Compare >::insert(), IPPL_MAKE_HOST_MAP_TAG, IPPL_TAG_CYCLE, MyNode, Hypervolume::n, name, NumSMPs, PInsist, putMessage(), vmap< Key, T, Compare >::size(), SMPIDList, SMPNodeList, and TotalNodes.
Referenced by IpplInfo().
getArgc()
static int IpplInfo::getArgc () inline static
Definition at line 188 of file IpplInfo.h.
References MyArgc.
getArgv()
static char** IpplInfo::getArgv () inline static
Definition at line 189 of file IpplInfo.h.
References MyArgv.
getComm()
static MPI_Comm IpplInfo::getComm () inline static
Definition at line 152 of file IpplInfo.h.
References communicator_m.
Referenced by allreduce(), H5PartWrapper::copyFile(), Distribution::createDistributionFromFile(), gather(), new_reduce(), opalMain(), H5PartWrapper::open(), _FM3DH5BlockBase::openFileMPIOCollective(), LossDataSink::openH5(), _Fieldmap::readHeader(), reduce(), scatter(), and Distribution::writeOutFileEmission().
getContexts()
int IpplInfo::getContexts (int n) static
Definition at line 677 of file IpplInfo.cpp.
References Hypervolume::n.
getNodes()
int IpplInfo::getNodes () static
Definition at line 670 of file IpplInfo.cpp.
References TotalNodes.
Referenced by abortAllNodes(), BareField< T1, D >::accumGuardCells(), DiscConfig::add_SMP_directory(), SDDSWriter::addDefaultParameters(), ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), assign(), BoxLibLayout< T, Dim >::BoxLibLayout(), CalcIndexedReceive(), PartBunchBase< double, 3 >::calcNumPartsOutside(), Distribution::checkParticleNumber(), MemoryProfiler::compute(), H5PartWrapper::copyStepData(), Distribution::create(), Distribution::createDistributionFromFile(), Distribution::createDistributionMultiGauss(), DistributionMoments::determinePercentilesDetail(), Inform::display_single_line(), GreenWakeFunction::distrIndices(), Distribution::doRestartOpalCycl(), Distribution::doRestartOpalT(), FieldWriter::dumpField(), ParallelTTracker::evenlyDistributeParticles(), BareField< T1, D >::fillGuardCells(), LBalWriter::fillHeader(), GridLBalWriter::fillHeader(), MemoryWriter::fillHeader(), StatWriter::fillHeader(), FieldDataSource< T, Dim, M, C >::gather_data(), PartBunchBase< double, 3 >::gatherLoadBalanceStatistics(), Distribution::generateAstraFlattopT(), Distribution::generateBinomial(), Distribution::generateFlattopLaserProfile(), Distribution::generateFlattopT(), Distribution::generateFlattopZ(), Distribution::generateGaussZ(), Distribution::generateLongFlattopT(), Distribution::generateMatchedGauss(), Distribution::generateTransverseGauss(), DataConnectCreator::getDefaultNodes(), ParticleSpatialLayout< T, Dim, Mesh >::getEmptyNode(), Cyclotron::getFieldFromFile_AVFEQ(), Cyclotron::getFieldFromFile_Carbon(), Cyclotron::getFieldFromFile_FFA(), ParticleSpatialLayout< T, Dim, Mesh >::getNodeCount(), Distribution::getNumOfLocalParticlesToCreate(), BareField< T1, D >::getsingle(), BareField< T1, D >::getsingle_bc(), IpplParticleBase< T >::globalCreate(), IndexedSend(), BoxLibLayout< T, Dim >::initBaseBox_m(), FieldLayout< Dim >::initialize(), ParallelCyclotronTracker::initializeTracking_m(), IpplMemoryUsage::IpplMemoryUsage(), ParticleSpatialLayout< T, Dim, Mesh >::new_swap_particles(), operator<<(), pap(), DiscConfig::parse_config(), ParticleUniformLayout< T, Dim >::ParticleUniformLayout(), FieldPrint< T, Dim >::print(), FieldDebugPrint< T, Dim >::print(), Timing::print(), ParticleSpatialLayout< T, Dim, Mesh >::printDebug(), FieldSolver::printInfo(), IpplCounter::printIt(), FieldLayout< Dim >::read(), MultiBunchHandler::readBunch(), ParticleCashedLayout< T, Dim, Mesh >::rebuild_interaction_data(), ParticleInteractLayout< T, Dim, Mesh >::rebuild_interaction_data(), ParticleSpatialLayout< T, Dim, Mesh >::rebuild_layout(), IpplParticleBase< T >::resetID(), IpplMemoryUsage::sample(), LossDataSink::saveASCII(), LossDataSink::saveH5(), PartBunch::setBCAllPeriodic(), PartBunch::setBCForDCBeam(), ParallelTTracker::setOptionalVariables(), ParticleCashedLayout< T, Dim, Mesh >::setup(), ParticleInteractLayout< T, Dim, Mesh >::setup(), ParticleSpatialLayout< T, Dim, Mesh >::setup(), FieldLayout< Dim >::setup(), PartBunchBase< double, 3 >::setup(), ParticleSpatialLayout< T, Dim, Mesh >::short_swap_particles(), ParallelCyclotronTracker::singleParticleDump(), spap(), ParticleCashedLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleInteractLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleSpatialLayout< T, Dim, Mesh >::swap_particles(), FFTBase< 1U, T >::transVnodes(), ParticleUniformLayout< T, Dim >::update(), ParticleCashedLayout< T, Dim, Mesh >::update(), ParticleInteractLayout< T, Dim, Mesh >::update(), ParticleSpatialLayout< T, Dim, Mesh >::update(), BoxLibLayout< T, Dim >::update(), LBalWriter::write(), MemoryWriter::write(), GridLBalWriter::write(), StatWriter::write(), FieldLayout< Dim >::write(), Distribution::writeOutFileEmission(), and Distribution::writeOutFileInjection().
getProcesses()
int IpplInfo::getProcesses (int n, int c) static
Definition at line 684 of file IpplInfo.cpp.
References Physics::c, and Hypervolume::n.
getSMPNodes()
int IpplInfo::getSMPNodes (int smpindx) static
Definition at line 706 of file IpplInfo.cpp.
References SMPIDList, and TotalNodes.
Referenced by operator<<().
getSMPs()
int IpplInfo::getSMPs () static
Definition at line 699 of file IpplInfo.cpp.
References NumSMPs.
Referenced by operator<<().
here()
void IpplInfo::here () static
Definition at line 783 of file IpplInfo.cpp.
instantiateGlobals()
void IpplInfo::instantiateGlobals () static
Definition at line 53 of file IpplInfo.cpp.
References Debug, Error, Info, INFORM_ALL_NODES, Stats, and Warn.
Referenced by PyOpal::Globals::Initialise().
maxFFTNodes()
static int IpplInfo::maxFFTNodes () inline static
Definition at line 199 of file IpplInfo.h.
References MaxFFTNodes.
Referenced by FFTBase< 1U, T >::transVnodes().
myNode()
int IpplInfo::myNode () static
Definition at line 691 of file IpplInfo.cpp.
References MyNode.
Referenced by ElementPositionWriter::addRow(), MonitorStatisticsWriter::addRow(), ThickTracker::advanceDispersion_m(), AmrYtWriter::AmrYtWriter(), LossDataSink::appendASCII(), CSRIGFWakeFunction::apply(), CSRWakeFunction::apply(), Distribution::calcPartPerDist(), Bend2D::calculateRefTrajectory(), _Fieldmap::checkMap(), SDDSWriter::close(), LossDataSink::closeASCII(), PeakFinder::computeCentroid_m(), BoundaryGeometry::computeMeshVoxelization(), MGPoissonSolver::computePotential(), H5PartWrapper::copyFile(), H5PartWrapper::copyFileSystem(), H5PartWrapper::copyStepData(), Distribution::create(), Distribution::createDistributionFromFile(), Distribution::createDistributionMultiGauss(), DistributionMoments::determinePercentilesDetail(), DiscMeta::DiscMeta(), Inform::display_single_line(), DiscField< Dim >::distribute_offsets(), GreenWakeFunction::distrIndices(), AmrParticleBase< PLayout >::domainMapping(), Distribution::doRestartOpalCycl(), Distribution::doRestartOpalT(), ParallelTTracker::evenlyDistributeParticles(), System::execute(), Call::execute(), Echo::execute(), FileStream::fillLine(), HashPairBuilderParallel< PBase >::forEach(), FieldDataSource< T, Dim, M, C >::gather_data(), Distribution::generateAstraFlattopT(), Distribution::generateBinomial(), Distribution::generateFlattopLaserProfile(), Distribution::generateFlattopT(), Distribution::generateFlattopZ(), Distribution::generateGaussZ(), Distribution::generateLongFlattopT(), Distribution::generateMatchedGauss(), Distribution::generateTransverseGauss(), Interpolator::getFieldIter(), FieldLayout< Dim >::getLocalNDIndex(), RFCavity::getMomentaKick(), Distribution::getNumberOfParticlesInFile(), Distribution::getNumOfLocalParticlesToCreate(), Bend2D::getOutline(), BareField< T1, D >::getsingle_bc(), IpplParticleBase< T >::globalCreate(), Inform::Inform(), Monitor::initialise(), RFCavity::initialise(), FieldLayout< Dim >::initialize(), OrbitThreader::integrate(), BareField< T1, D >::localElement(), _Fieldmap::lowResolutionWarning(), new_reduce(), ParticleSpatialLayout< T, Dim, Mesh >::new_swap_particles(), DataConnect::onConnectNode(), opalMain(), SDDSWriter::open(), DiscField< Dim >::open_df_file(), DiscField< Dim >::open_df_file_fd(), DiscParticle::open_file(), LossDataSink::openASCII(), operator<<(), OrbitThreader::OrbitThreader(), Inform::outputMessage(), pap(), DiscConfig::parse_config(), DiscField< Dim >::parse_config(), FieldDebugPrint< T, Dim >::print(), CCollimator::print(), FlexibleCollimator::print(), DiscConfig::printDebug(), DiscField< Dim >::query(), DiscField< Dim >::read(), DiscParticle::read(), FieldLayout< Dim >::read(), DiscParticle::read_meta(), DiscField< Dim >::read_meta(), MultiBunchHandler::readBunch(), RealConstant::RealConstant(), ParticleCashedLayout< T, Dim, Mesh >::rebuild_interaction_data(), ParticleInteractLayout< T, Dim, Mesh >::rebuild_interaction_data(), ParticleSpatialLayout< T, Dim, Mesh >::rebuild_layout(), Distribution::reflectDistribution(), DiscConfig::replace_wildcards(), SDDSWriter::replaceVersionString(), IpplParticleBase< T >::resetID(), SDDSWriter::rewindLines(), Util::rewindLinesSDDS(), StatBaseWriter::rewindToSpos(), OpalBeamline::save3DInput(), OpalBeamline::save3DLattice(), LossDataSink::saveH5(), ScatteringPhysics::ScatteringPhysics(), FieldLayout< Dim >::setup(), spap(), ParticleCashedLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleInteractLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleSpatialLayout< T, Dim, Mesh >::swap_particles(), RBend3D::trackRefParticleThrough(), Communicate::unpack_message(), ParticleUniformLayout< T, Dim >::update(), ParticleCashedLayout< T, Dim, Mesh >::update(), ParticleInteractLayout< T, Dim, Mesh >::update(), ParticleSpatialLayout< T, Dim, Mesh >::update(), BoxLibLayout< T, Dim >::update(), BoxParticleCachingPolicy< T, Dim, Mesh >::updateCacheInformation(), LBalWriter::write(), MemoryWriter::write(), GridLBalWriter::write(), MultiBunchDump::write(), StatWriter::write(), MemoryProfiler::write(), BareField< T1, D >::write(), DiscParticle::write(), FieldLayout< Dim >::write(), DiscField< Dim >::write(), _Fieldmap::write3DField(), ThickTracker::write_m(), DiscParticle::write_meta(), AmrYtWriter::writeBunch(), AmrYtWriter::writeFields(), DataSink::writeGeomToVtk(), SDDSWriter::writeHeader(), LossDataSink::writeHeaderASCII(), FlexibleCollimator::writeHolesAndQuadtree(), DataSink::writeImpactStatistics(), Distribution::writeOutFileEmission(), Distribution::writeOutFileHeader(), Distribution::writeOutFileInjection(), and AmrYtWriter::writeParticles_m().
mySMP()
int IpplInfo::mySMP () static
Definition at line 721 of file IpplInfo.cpp.
References MyNode, and SMPIDList.
Referenced by operator<<().
mySMPNode()
int IpplInfo::mySMPNode () static
Definition at line 728 of file IpplInfo.cpp.
References MyNode, and SMPNodeList.
Referenced by operator<<().
operator=()
IpplInfo & IpplInfo::operator= (const IpplInfo &)
Definition at line 611 of file IpplInfo.cpp.
param_error() [1/2]
void IpplInfo::param_error (const char * param, const char * msg, const char * bad) static private
Definition at line 853 of file IpplInfo.cpp.
References abort(), endl(), and ERRORMSG.
Referenced by IpplInfo().
param_error() [2/2]
void IpplInfo::param_error (const char * param, const char * msg1, const char * msg2, const char * bad) static private
Definition at line 865 of file IpplInfo.cpp.
References abort(), endl(), and ERRORMSG.
perSMPParallelIO()
static bool IpplInfo::perSMPParallelIO () inline static
Definition at line 211 of file IpplInfo.h.
References PerSMPParallelIO.
Referenced by DiscField< Dim >::distribute_offsets(), and operator<<().
pop()
void IpplInfo::pop () static
Definition at line 1053 of file IpplInfo.cpp.
References ChunkSize, CommInitialized, communicator_m, Debug, deferGuardCellFills, Error, extraCompressChecks, Info, MaxFFTNodes, MyArgc, MyArgv, MyNode, NeedDeleteComm, noFieldCompression, NumCreated, NumSMPs, offsetStorage, PAssert_EQ, PerSMPParallelIO, PrintStats, Retransmit, SMPIDList, SMPNodeList, stashedStaticMembers, Stats, TotalNodes, UseChecksums, and Warn.
Referenced by OptimizeCmd::popEnvironment(), and SampleCmd::popEnvironment().
printHelp()
void IpplInfo::printHelp () static
Definition at line 744 of file IpplInfo.cpp.
References CommCreator::getAllLibraryNames(), DataConnectCreator::getAllMethodNames(), and INFOMSG.
Referenced by IpplInfo().
printStatistics()
void IpplInfo::printStatistics (Inform & o) static
Definition at line 789 of file IpplInfo.cpp.
References IpplStats::print(), and Stats.
Referenced by abort(), abortAllNodes(), and ~IpplInfo().
printVersion()
void IpplInfo::printVersion (void) static
Definition at line 736 of file IpplInfo.cpp.
References compileDate(), compileMachine(), compileUser(), endl(), INFOMSG, and version().
Referenced by IpplInfo(), and opalMain().
retransmit()
static bool IpplInfo::retransmit () inline static
Definition at line 195 of file IpplInfo.h.
References Retransmit, and UseChecksums.
Referenced by Communicate::fill_msg_buffer(), CommMPI::mysend(), operator<<(), Communicate::receive_block(), and Communicate::unpack_message().
stash()
void IpplInfo::stash () static
Definition at line 988 of file IpplInfo.cpp.
References ChunkSize, StaticIpplInfo::Comm, Comm, CommInitialized, communicator_m, Debug, deferGuardCellFills, Error, extraCompressChecks, Info, MaxFFTNodes, MyArgc, MyArgv, MyNode, NeedDeleteComm, noFieldCompression, NumCreated, NumSMPs, offsetStorage, PAssert_EQ, PerSMPParallelIO, PrintStats, Retransmit, SMPIDList, SMPNodeList, stashedStaticMembers, Stats, TotalNodes, UseChecksums, and Warn.
Referenced by OptimizeCmd::stashEnvironment(), and SampleCmd::stashEnvironment().
useChecksums()
static bool IpplInfo::useChecksums () inline static
Definition at line 192 of file IpplInfo.h.
References UseChecksums.
Referenced by Communicate::fill_msg_buffer(), Communicate::find_msg_length(), operator<<(), and Communicate::unpack_message().
version()
const char * IpplInfo::version () static
Definition at line 795 of file IpplInfo.cpp.
References ippl_version_name.
Referenced by printVersion().
Member Data Documentation
ChunkSize
int IpplInfo::ChunkSize = 512*1024 static private
Definition at line 326 of file IpplInfo.h.
Referenced by chunkSize(), IpplInfo(), pop(), and stash().
Comm
Communicate * IpplInfo::Comm = 0 static
Definition at line 84 of file IpplInfo.h.
Referenced by abort(), BareField< T1, D >::accumGuardCells(), AmrYtWriter::AmrYtWriter(), ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), assign(), BcastCuts(), ParallelCyclotronTracker::bunchMode_m(), CalcBinaryRepartition(), H5PartWrapper::close(), MGPoissonSolver::computePotential(), H5PartWrapper::copyFile(), deleteGlobals(), DiscField< Dim >::distribute_offsets(), ParallelTTracker::doBinaryRepartition(), ParallelTTracker::evenlyDistributeParticles(), FieldLayout< Dim >::FieldLayout(), BareField< T1, D >::fillGuardCells(), ParallelCyclotronTracker::finalizeTracking_m(), FieldDataSource< T, Dim, M, C >::gather_data(), IpplParticleBase< T >::getNextID(), BareField< T1, D >::getsingle(), BareField< T1, D >::getsingle_bc(), IndexedReceive(), IndexedSend(), Monitor::initialise(), MultiBunchHandler::injectBunch(), IpplInfo(), ParallelCyclotronTracker::MtsTracker(), ParticleSpatialLayout< T, Dim, Mesh >::new_swap_particles(), opalMain(), operator<<(), pap(), DiscConfig::parse_config(), FieldPrint< T, Dim >::print(), FieldDebugPrint< T, Dim >::print(), DiscField< Dim >::read(), FieldLayout< Dim >::read(), DiscParticle::read_meta(), DiscField< Dim >::read_meta(), ParticleSpatialLayout< T, Dim, Mesh >::rebuild_layout(), H5PartWrapper::receiveFailureMessage(), reduce(), reduce_masked(), ParallelCyclotronTracker::repartition(), IpplParticleBase< T >::resetID(), run_opal(), LossDataSink::save(), LossDataSink::saveASCII(), scatter(), H5PartWrapper::sendFailureMessage(), IpplParticleBase< T >::setup(), ParticleSpatialLayout< T, Dim, Mesh >::short_swap_particles(), IpplParticleBase< T >::singleInitNode(), ParallelCyclotronTracker::singleParticleDump(), spap(), stash(), ParticleCashedLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleInteractLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleSpatialLayout< T, Dim, Mesh >::swap_particles(), ParticleUniformLayout< T, Dim >::update(), ParticleCashedLayout< T, Dim, Mesh >::update(), ParticleInteractLayout< T, Dim, Mesh >::update(), ParticleSpatialLayout< T, Dim, Mesh >::update(), BoxLibLayout< T, Dim >::update(), BoxParticleCachingPolicy< T, Dim, Mesh >::updateGhostParticles(), BareField< T1, D >::write(), DiscParticle::write(), DiscField< Dim >::write(), AmrYtWriter::writeBunch(), AmrYtWriter::writeFields(), Distribution::writeOutFileEmission(), and ~IpplInfo().
CommInitialized
bool IpplInfo::CommInitialized = false static private
Definition at line 291 of file IpplInfo.h.
Referenced by IpplInfo(), pop(), stash(), and ~IpplInfo().
communicator_m
MPI_Comm IpplInfo::communicator_m = MPI_COMM_WORLD static private
Definition at line 283 of file IpplInfo.h.
Referenced by getComm(), IpplInfo(), pop(), and stash().
Debug
Inform * IpplInfo::Debug = 0 static
Definition at line 81 of file IpplInfo.h.
Referenced by deleteGlobals(), instantiateGlobals(), IpplInfo(), opalMain(), pop(), and stash().
deferGuardCellFills
bool IpplInfo::deferGuardCellFills = false static
Definition at line 259 of file IpplInfo.h.
Referenced by IpplInfo(), operator<<(), pop(), BareField< T1, D >::setDirtyFlag(), and stash().
Error
Inform * IpplInfo::Error = 0 static
Definition at line 80 of file IpplInfo.h.
Referenced by deleteGlobals(), instantiateGlobals(), IpplInfo(), opalMain(), pop(), OpalParser::readStatement(), run_opal(), and stash().
extraCompressChecks
bool IpplInfo::extraCompressChecks = false static
Definition at line 270 of file IpplInfo.h.
Referenced by assign(), LField< T, Dim >::CanCompress(), LField< T, Dim >::CanCompressBasedOnPhysicalCells(), IpplInfo(), operator<<(), pop(), and stash().
Info
Inform * IpplInfo::Info = 0 static
Definition at line 78 of file IpplInfo.h.
Referenced by agfp1(), agfp2(), agfp3(), deleteGlobals(), Option::execute(), fp1(), fp2(), TravelingWave::getAutoPhaseEstimate(), RFCavity::getAutoPhaseEstimate(), RFCavity::getAutoPhaseEstimateFallback(), ggfp1(), ggfp2(), instantiateGlobals(), IpplInfo(), MGPoissonSolver::MGPoissonSolver(), opalMain(), pop(), run_opal(), Inform::setup(), sfp1(), sfp2(), sfp3(), and stash().
MaxFFTNodes
int IpplInfo::MaxFFTNodes = 0 static private
Definition at line 323 of file IpplInfo.h.
Referenced by IpplInfo(), maxFFTNodes(), pop(), and stash().
MyArgc
int IpplInfo::MyArgc = 0 static private
Definition at line 307 of file IpplInfo.h.
Referenced by getArgc(), IpplInfo(), pop(), and stash().
MyArgv
char ** IpplInfo::MyArgv = 0 static private
Definition at line 308 of file IpplInfo.h.
Referenced by getArgv(), IpplInfo(), pop(), stash(), and ~IpplInfo().
MyNode
int IpplInfo::MyNode = 0 static private
Definition at line 312 of file IpplInfo.h.
Referenced by find_smp_nodes(), IpplInfo(), myNode(), mySMP(), mySMPNode(), pop(), and stash().
NeedDeleteComm
bool IpplInfo::NeedDeleteComm = false static private
Definition at line 298 of file IpplInfo.h.
Referenced by abort(), IpplInfo(), pop(), stash(), and ~IpplInfo().
noFieldCompression
bool IpplInfo::noFieldCompression = false static
Definition at line 262 of file IpplInfo.h.
Referenced by LField< T, Dim >::CanCompress(), LField< T, Dim >::CanCompressBasedOnPhysicalCells(), LField< T, Dim >::Compress(), LField< T, Dim >::CompressBasedOnPhysicalCells(), IpplInfo(), operator<<(), pop(), BareField< T1, D >::setCompression(), stash(), LField< T, Dim >::TryCompress(), and TryCompressLHS().
NumCreated
int IpplInfo::NumCreated = 0 static private
Definition at line 287 of file IpplInfo.h.
Referenced by IpplInfo(), pop(), stash(), and ~IpplInfo().
NumSMPs
int IpplInfo::NumSMPs = 1 static private
Definition at line 317 of file IpplInfo.h.
Referenced by find_smp_nodes(), getSMPs(), pop(), and stash().
offsetStorage
bool IpplInfo::offsetStorage = false static
Definition at line 266 of file IpplInfo.h.
Referenced by LField< T, Dim >::allocateStorage(), LField< T, Dim >::deallocateStorage(), IpplInfo(), operator<<(), pop(), and stash().
PerSMPParallelIO
bool IpplInfo::PerSMPParallelIO = false static private
Definition at line 331 of file IpplInfo.h.
Referenced by IpplInfo(), perSMPParallelIO(), pop(), and stash().
PrintStats
bool IpplInfo::PrintStats = false static private
Definition at line 295 of file IpplInfo.h.
Referenced by abort(), abortAllNodes(), IpplInfo(), pop(), stash(), and ~IpplInfo().
Retransmit
bool IpplInfo::Retransmit = false static private
Definition at line 304 of file IpplInfo.h.
Referenced by IpplInfo(), pop(), retransmit(), and stash().
SMPIDList
int * IpplInfo::SMPIDList = 0 static private
Definition at line 318 of file IpplInfo.h.
Referenced by find_smp_nodes(), getSMPNodes(), mySMP(), pop(), stash(), and ~IpplInfo().
SMPNodeList
int * IpplInfo::SMPNodeList = 0 static private
Definition at line 319 of file IpplInfo.h.
Referenced by find_smp_nodes(), mySMPNode(), pop(), stash(), and ~IpplInfo().
stashedStaticMembers
std::stack< StaticIpplInfo > IpplInfo::stashedStaticMembers static private
Definition at line 333 of file IpplInfo.h.
Referenced by pop(), and stash().
Stats
IpplStats * IpplInfo::Stats = 0 static
Definition at line 87 of file IpplInfo.h.
Referenced by deleteGlobals(), instantiateGlobals(), IpplInfo(), operator<<(), pop(), printStatistics(), stash(), and ~IpplInfo().
TotalNodes
int IpplInfo::TotalNodes = 1 static private
Definition at line 313 of file IpplInfo.h.
Referenced by find_smp_nodes(), getNodes(), getSMPNodes(), IpplInfo(), pop(), and stash().
UseChecksums
bool IpplInfo::UseChecksums = false static private
Definition at line 301 of file IpplInfo.h.
Referenced by IpplInfo(), pop(), retransmit(), stash(), and useChecksums().
Warn
Inform * IpplInfo::Warn = 0 static
Definition at line 79 of file IpplInfo.h.
Referenced by deleteGlobals(), Option::execute(), instantiateGlobals(), IpplInfo(), opalMain(), pop(), run_opal(), and stash().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/IpplInfo.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/IpplInfo.cpp