OPAL (Object Oriented Parallel Accelerator Library): mslang::Repeat Struct Reference
mslang::Repeat Struct Reference
#include <Repeat.h>
Public Member Functions
virtual ~Repeat ()
virtual void print (int indentwidth)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Public Member Functions inherited from mslang::Function
virtual ~Function ()
virtual void apply (std::vector< std::shared_ptr< Base >> &bfuncs)=0
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
Static Public Member Functions inherited from mslang::Function
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
Function * func_m
unsigned int N_m
double shiftx_m
double shifty_m
double rot_m
Additional Inherited Members
Static Public Attributes inherited from mslang::Function
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\((.*)"
Detailed Description
Definition at line 7 of file Repeat.h.
Constructor & Destructor Documentation
~Repeat()
virtual mslang::Repeat::~Repeat () inline virtual
Definition at line 14 of file Repeat.h.
References func_m.
Member Function Documentation
apply()
void mslang::Repeat::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Definition at line 17 of file Repeat.cpp.
References mslang::Function::apply(), cos(), func_m, mslang::AffineTransformation::mult(), N_m, rot_m, shiftx_m, shifty_m, and sin().
parse_detail()
bool mslang::Repeat::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 36 of file Repeat.cpp.
References Physics::e, end(), endl(), func_m, mslang::ArgumentExtractor::get(), mslang::ArgumentExtractor::getLengthConsumed(), mslang::ArgumentExtractor::getNumArguments(), N_m, mslang::Function::parse(), mslang::parseMathExpression(), rot_m, shiftx_m, and shifty_m.
Referenced by mslang::Function::parse().
print()
void mslang::Repeat::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 6 of file Repeat.cpp.
References endl(), func_m, N_m, mslang::Function::print(), shiftx_m, and shifty_m.
Member Data Documentation
func_m
Function* mslang::Repeat::func_m
Definition at line 8 of file Repeat.h.
Referenced by apply(), parse_detail(), print(), and ~Repeat().
N_m
unsigned int mslang::Repeat::N_m
Definition at line 9 of file Repeat.h.
Referenced by apply(), parse_detail(), and print().
rot_m
double mslang::Repeat::rot_m
Definition at line 12 of file Repeat.h.
Referenced by apply(), and parse_detail().
shiftx_m
double mslang::Repeat::shiftx_m
Definition at line 10 of file Repeat.h.
Referenced by apply(), parse_detail(), and print().
shifty_m
double mslang::Repeat::shifty_m
Definition at line 11 of file Repeat.h.
Referenced by apply(), parse_detail(), and print().
The documentation for this struct was generated from the following files:
src/Classic/Utilities/MSLang/Repeat.h
src/Classic/Utilities/MSLang/Repeat.cpp