OPAL (Object Oriented Parallel Accelerator Library): Help Class Reference
Help Class Reference
#include <Help.h>
Public Member Functions
Help ()
Exemplar constructor.
virtual ~Help ()
virtual Help * clone (const std::string &name)
Make clone.
virtual void execute ()
Execute the command.
virtual void parse (Statement &)
Parse command (special for one-attribute command).
Public Member Functions inherited from Action
virtual ~Action ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
Help (const Help &)
void operator= (const Help &)
Help (const std::string &name, Help *parent)
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Action
Action (int size, const char *name, const char *help)
Constructor for exemplars.
Action (const std::string &name, Action *parent)
Constructor for cloning.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 24 of file Help.h.
Constructor & Destructor Documentation
Help() [1/3]
Help::Help ()
Exemplar constructor.
Definition at line 28 of file Help.cpp.
References Object::itsAttr, Attributes::makeString(), Object::registerOwnership(), and AttributeHandler::STATEMENT.
Referenced by clone().
~Help()
Help::~Help () virtual
Definition at line 44 of file Help.cpp.
Help() [2/3]
Help::Help (const Help &) private
Help() [3/3]
Help::Help (const std::string & name, Help * parent) private
Definition at line 39 of file Help.cpp.
Member Function Documentation
clone()
Help * Help::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 48 of file Help.cpp.
References Help(), and name.
execute()
void Help::execute () virtual
Execute the command.
Reimplemented from Object.
Definition at line 53 of file Help.cpp.
References endl(), ERRORMSG, Expressions::find(), OpalData::getInstance(), Attributes::getString(), Object::itsAttr, name, and Object::printHelp().
operator=()
void Help::operator= (const Help &) private
parse()
void Help::parse (Statement & statement) virtual
Parse command (special for one-attribute command).
Reimplemented from Object.
Definition at line 69 of file Help.cpp.
References Object::parseShortcut().
The documentation for this class was generated from the following files:
src/BasicActions/Help.h
src/BasicActions/Help.cpp