OPAL (Object Oriented Parallel Accelerator Library): MsgBuffer Class Reference
MsgBuffer Class Reference
#include <MsgBuffer.h>
Public Member Functions
MsgBuffer (Format *f, int count, int offset=0)
MsgBuffer (Format *f, char *d, int size)
bool add (Message *)
Message * get ()
template<class T >
void get (T &v)
template<class T >
void put (T &v)
int getSize ()
void * getBuffer ()
Format * getFormat ()
~MsgBuffer ()
Private Attributes
Format * format
unsigned int datasize
unsigned int writepos
unsigned int readpos
std::vector< char > data
Detailed Description
Definition at line 29 of file MsgBuffer.h.
Constructor & Destructor Documentation
MsgBuffer() [1/2]
MsgBuffer::MsgBuffer (Format * f, int count, int offset = 0)
Definition at line 23 of file MsgBuffer.cpp.
References data, datasize, format, and Format::getSize().
MsgBuffer() [2/2]
MsgBuffer::MsgBuffer (Format * f, char * d, int size)
Definition at line 31 of file MsgBuffer.cpp.
References data, and datasize.
~MsgBuffer()
MsgBuffer::~MsgBuffer ()
Definition at line 40 of file MsgBuffer.cpp.
Member Function Documentation
add()
bool MsgBuffer::add (Message * msg)
Definition at line 44 of file MsgBuffer.cpp.
References data, Message::MsgItem::data(), datasize, format, Format::getItemBytes(), Format::getItemCount(), Format::getItemElems(), Message::item(), Message::MsgItem::numBytes(), Message::MsgItem::numElems(), Message::size(), and writepos.
Referenced by BoxLibLayout< T, Dim >::update(), IpplParticleBase< T >::writeMsgBuffer(), and IpplParticleBase< T >::writeMsgBufferWithOffsets().
get() [1/2]
Message * MsgBuffer::get ()
Definition at line 71 of file MsgBuffer.cpp.
References data, datasize, format, Format::getItemBytes(), Format::getItemCount(), Format::getItemElems(), Format::getSize(), Message::putmsg(), readpos, Message::setCopy(), and Message::setDelete().
Referenced by IpplParticleBase< T >::readGhostMsgBuffer(), IpplParticleBase< T >::readMsgBuffer(), and BoxLibLayout< T, Dim >::update().
get() [2/2]
template<class T > void MsgBuffer::get (T & v) inline
Definition at line 39 of file MsgBuffer.h.
References data, readpos, and Attrib::Legacy::Distribution::T.
getBuffer()
void* MsgBuffer::getBuffer () inline
Definition at line 54 of file MsgBuffer.h.
References data.
Referenced by BoxLibLayout< T, Dim >::update(), and BoxParticleCachingPolicy< T, Dim, Mesh >::updateGhostParticles().
getFormat()
Format* MsgBuffer::getFormat () inline
Definition at line 59 of file MsgBuffer.h.
References format.
getSize()
int MsgBuffer::getSize () inline
Definition at line 50 of file MsgBuffer.h.
References writepos.
Referenced by BoxLibLayout< T, Dim >::update(), and BoxParticleCachingPolicy< T, Dim, Mesh >::updateGhostParticles().
put()
template<class T > void MsgBuffer::put (T & v) inline
Definition at line 45 of file MsgBuffer.h.
References data, Attrib::Legacy::Distribution::T, and writepos.
Member Data Documentation
data
std::vector<char> MsgBuffer::data private
Definition at line 68 of file MsgBuffer.h.
Referenced by add(), get(), getBuffer(), MsgBuffer(), and put().
datasize
unsigned int MsgBuffer::datasize private
Definition at line 67 of file MsgBuffer.h.
Referenced by add(), get(), and MsgBuffer().
format
Format* MsgBuffer::format private
Definition at line 66 of file MsgBuffer.h.
Referenced by add(), get(), getFormat(), and MsgBuffer().
readpos
unsigned int MsgBuffer::readpos private
Definition at line 67 of file MsgBuffer.h.
Referenced by get().
writepos
unsigned int MsgBuffer::writepos private
Definition at line 67 of file MsgBuffer.h.
Referenced by add(), getSize(), and put().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Message/MsgBuffer.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Message/MsgBuffer.cpp