OPAL (Object Oriented Parallel Accelerator Library): FLUMatrix< T, N > Class Template Reference
FLUMatrix< T, N > Class Template Reference
A templated representation of a LU-decomposition.
#include <FLUMatrix.h>
Public Member Functions
FLUMatrix (const FMatrix< T, N, N > &M)
Constructor.
FLUMatrix ()
FLUMatrix (const FLUMatrix< T, N > &)
~FLUMatrix ()
FLUMatrix< T, N > & operator= (const FLUMatrix &)
void backSubstitute (FVector< T, N > &B) const
Back substitution.
template<int M>
void backSubstitute (FMatrix< T, N, M > &MM) const
Back substitution.
FMatrix< T, N, N > inverse () const
Get inverse.
template<class I>
void backSubstitute (I iter) const
Private Member Functions
template<class Iterator >
void backSubstitute (Iterator) const
Private Attributes
FMatrix< T, N, N > decomp
FArray1D< int, N > index
Detailed Description
template<class T, int N>
class FLUMatrix< T, N >
A templated representation of a LU-decomposition.
Definition at line 42 of file FLUMatrix.h.
Constructor & Destructor Documentation
FLUMatrix() [1/3]
template<class T , int N> FLUMatrix< T, N >::FLUMatrix (const FMatrix< T, N, N > & M) explicit
Constructor.
Definition at line 101 of file FLUMatrix.h.
References abs(), FLUMatrix< T, N >::decomp, FLUMatrix< T, N >::index, FArray2D< T, M, N >::swapRows(), and Attrib::Legacy::Distribution::T.
FLUMatrix() [2/3]
template<class T , int N> FLUMatrix< T, N >::FLUMatrix ()
Definition at line 89 of file FLUMatrix.h.
FLUMatrix() [3/3]
template<class T , int N> FLUMatrix< T, N >::FLUMatrix (const FLUMatrix< T, N > & rhs)
Definition at line 95 of file FLUMatrix.h.
~FLUMatrix()
template<class T , int N> FLUMatrix< T, N >::~FLUMatrix ()
Definition at line 167 of file FLUMatrix.h.
Member Function Documentation
backSubstitute() [1/4]
template<class T , int N> void FLUMatrix< T, N >::backSubstitute (FVector< T, N > & B) const
Back substitution.
Definition at line 222 of file FLUMatrix.h.
References FArray1D< T, N >::begin().
backSubstitute() [2/4]
template<class T , int N> template<int M> void FLUMatrix< T, N >::backSubstitute (FMatrix< T, N, M > & MM) const
Back substitution.
Definition at line 228 of file FLUMatrix.h.
References FArray2D< T, R, C >::col_begin().
backSubstitute() [3/4]
template<class T, int N> template<class Iterator > void FLUMatrix< T, N >::backSubstitute (Iterator) const private
backSubstitute() [4/4]
template<class T, int N> template<class I> void FLUMatrix< T, N >::backSubstitute (I iter) const inline
Definition at line 180 of file FLUMatrix.h.
References sum(), and Attrib::Legacy::Distribution::T.
inverse()
template<class T , int N> FMatrix< T, N, N > FLUMatrix< T, N >::inverse () const
Get inverse.
Definition at line 236 of file FLUMatrix.h.
References Attrib::Legacy::Distribution::T.
Referenced by TransportMap< T, N >::inverse(), LinearMap< T, N >::inverse(), FVps< T, N >::inverse(), and FVps< T, N >::myInverse().
operator=()
template<class T , int N> FLUMatrix< T, N > & FLUMatrix< T, N >::operator= (const FLUMatrix< T, N > & rhs)
Definition at line 172 of file FLUMatrix.h.
References FLUMatrix< T, N >::decomp, and FLUMatrix< T, N >::index.
Member Data Documentation
decomp
template<class T, int N> FMatrix<T, N, N> FLUMatrix< T, N >::decomp private
Definition at line 78 of file FLUMatrix.h.
Referenced by FLUMatrix< T, N >::FLUMatrix(), and FLUMatrix< T, N >::operator=().
index
template<class T, int N> FArray1D<int, N> FLUMatrix< T, N >::index private
Definition at line 81 of file FLUMatrix.h.
Referenced by FLUMatrix< T, N >::FLUMatrix(), and FLUMatrix< T, N >::operator=().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/src/Classic/FixedAlgebra/FLUMatrix.h