OPAL (Object Oriented Parallel Accelerator Library): ippl/src/FFT/fftpack_FFT.h File Reference
fftpack_FFT.h File Reference
#include "Utility/PAssert.h"
#include "Utility/IpplInfo.h"
Classes
class FFTPACK_wrap< T >
class FFTPACK_wrap< float >
class FFTPACK_wrap< double >
class FFTPACK< T >
Functions
void cffti (size_t n, double &wsave)
void cfftf (size_t n, double &r, double &wsave)
void cfftb (size_t n, double &r, double &wsave)
void rffti (size_t n, double &wsave)
void rfftf (size_t n, double &r, double &wsave)
void rfftb (size_t n, double &r, double &wsave)
void sinti (size_t n, double &wsave)
void sint (size_t n, double &r, double &wsave)
void fcffti (size_t n, float &wsave)
void fcfftf (size_t n, float &r, float &wsave)
void fcfftb (size_t n, float &r, float &wsave)
void frffti (size_t n, float &wsave)
void frfftf (size_t n, float &r, float &wsave)
void frfftb (size_t n, float &r, float &wsave)
void fsinti (size_t n, float &wsave)
void fsint (size_t n, float &r, float &wsave)
Function Documentation
cfftb()
void cfftb (size_t n, double & r, double & wsave)
Referenced by FFTPACK_wrap< double >::ccfftb().
cfftf()
void cfftf (size_t n, double & r, double & wsave)
Referenced by FFTPACK_wrap< double >::ccfftf().
cffti()
void cffti (size_t n, double & wsave)
Referenced by FFTPACK_wrap< double >::ccffti().
fcfftb()
void fcfftb (size_t n, float & r, float & wsave)
Referenced by FFTPACK_wrap< float >::ccfftb().
fcfftf()
void fcfftf (size_t n, float & r, float & wsave)
Referenced by FFTPACK_wrap< float >::ccfftf().
fcffti()
void fcffti (size_t n, float & wsave)
Referenced by FFTPACK_wrap< float >::ccffti().
frfftb()
void frfftb (size_t n, float & r, float & wsave)
Referenced by FFTPACK_wrap< float >::rcfftb().
frfftf()
void frfftf (size_t n, float & r, float & wsave)
Referenced by FFTPACK_wrap< float >::rcfftf().
frffti()
void frffti (size_t n, float & wsave)
Referenced by FFTPACK_wrap< float >::rcffti().
fsint()
void fsint (size_t n, float & r, float & wsave)
Referenced by FFTPACK_wrap< float >::rrfft().
fsinti()
void fsinti (size_t n, float & wsave)
Referenced by FFTPACK_wrap< float >::rrffti().
rfftb()
void rfftb (size_t n, double & r, double & wsave)
Referenced by FFTPACK_wrap< double >::rcfftb().
rfftf()
void rfftf (size_t n, double & r, double & wsave)
Referenced by FFTPACK_wrap< double >::rcfftf().
rffti()
void rffti (size_t n, double & wsave)
Referenced by FFTPACK_wrap< double >::rcffti().
sint()
void sint (size_t n, double & r, double & wsave)
Referenced by FFTPACK_wrap< double >::rrfft().
sinti()
void sinti (size_t n, double & wsave)
Referenced by FFTPACK_wrap< double >::rrffti().