OPAL (Object Oriented Parallel Accelerator Library): ParticleAttribBase Class Reference
ParticleAttribBase Class Reference abstract
#include <ParticleAttribBase.h>
Public Types
typedef long SortListIndex_t
typedef std::vector< SortListIndex_t > SortList_t
Public Member Functions
ParticleAttribBase (unsigned int size, const std::string &typestr)
ParticleAttribBase (const ParticleAttribBase &pa)
virtual ~ParticleAttribBase ()
unsigned int elementSize () const
const std::string & typeString () const
void setTemporary (bool t)
bool isTemporary () const
virtual void create (size_t M)=0
virtual void destroy (size_t M, size_t I, bool optDestroy)=0
virtual void destroy (const std::vector< std::pair< size_t, size_t > > &dlist, bool optDestroy)=0
virtual size_t putMessage (Message &, size_t, size_t)=0
virtual size_t putMessage (Message &, const std::vector< size_t > &)=0
virtual size_t getMessage (Message &, size_t)=0
virtual size_t ghostDestroy (size_t M, size_t I)=0
virtual void ghostCreate (size_t M)=0
virtual size_t ghostPutMessage (Message &, size_t, size_t)=0
virtual size_t ghostPutMessage (Message &, const std::vector< size_t > &)=0
virtual size_t ghostGetMessage (Message &, size_t)=0
virtual void calcSortList (SortList_t &slist, bool ascending=true)=0
virtual void sort (SortList_t &slist)=0
virtual void printDebug (Inform &)=0
Private Attributes
unsigned int ElementSize
std::string TypeString
bool Temporary
Detailed Description
Definition at line 37 of file ParticleAttribBase.h.
Member Typedef Documentation
SortList_t
typedef std::vector<SortListIndex_t> ParticleAttribBase::SortList_t
Definition at line 48 of file ParticleAttribBase.h.
SortListIndex_t
typedef long ParticleAttribBase::SortListIndex_t
Definition at line 47 of file ParticleAttribBase.h.
Constructor & Destructor Documentation
ParticleAttribBase() [1/2]
ParticleAttribBase::ParticleAttribBase (unsigned int size, const std::string & typestr) inline
Definition at line 55 of file ParticleAttribBase.h.
ParticleAttribBase() [2/2]
ParticleAttribBase::ParticleAttribBase (const ParticleAttribBase & pa) inline
Definition at line 59 of file ParticleAttribBase.h.
~ParticleAttribBase()
virtual ParticleAttribBase::~ParticleAttribBase () inline virtual
Definition at line 64 of file ParticleAttribBase.h.
Member Function Documentation
calcSortList()
virtual void ParticleAttribBase::calcSortList (SortList_t & slist, bool ascending = true) pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, and ParticleAttrib< ParticleOrigin >.
create()
virtual void ParticleAttribBase::create (size_t M) pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, and ParticleAttrib< ParticleOrigin >.
destroy() [1/2]
virtual void ParticleAttribBase::destroy (size_t M, size_t I, bool optDestroy) pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, and ParticleAttrib< ParticleOrigin >.
destroy() [2/2]
virtual void ParticleAttribBase::destroy (const std::vector< std::pair< size_t, size_t > > & dlist, bool optDestroy) pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, and ParticleAttrib< ParticleOrigin >.
elementSize()
unsigned int ParticleAttribBase::elementSize () const inline
Definition at line 71 of file ParticleAttribBase.h.
References ElementSize.
Referenced by DiscParticle::read(), and DiscParticle::write().
getMessage()
virtual size_t ParticleAttribBase::getMessage (Message & , size_t) pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, and ParticleAttrib< ParticleOrigin >.
ghostCreate()
virtual void ParticleAttribBase::ghostCreate (size_t M) pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, and ParticleAttrib< ParticleOrigin >.
ghostDestroy()
virtual size_t ParticleAttribBase::ghostDestroy (size_t M, size_t I) pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, ParticleAttrib< ParticleOrigin >, and ParticleInteractAttrib< T >.
ghostGetMessage()
virtual size_t ParticleAttribBase::ghostGetMessage (Message & , size_t) pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, ParticleAttrib< ParticleOrigin >, and ParticleInteractAttrib< T >.
ghostPutMessage() [1/2]
virtual size_t ParticleAttribBase::ghostPutMessage (Message & , size_t , size_t) pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, ParticleAttrib< ParticleOrigin >, and ParticleInteractAttrib< T >.
ghostPutMessage() [2/2]
virtual size_t ParticleAttribBase::ghostPutMessage (Message & , const std::vector< size_t > &) pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, ParticleAttrib< ParticleOrigin >, and ParticleInteractAttrib< T >.
isTemporary()
bool ParticleAttribBase::isTemporary () const inline
Definition at line 83 of file ParticleAttribBase.h.
References Temporary.
printDebug()
virtual void ParticleAttribBase::printDebug (Inform &) pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, ParticleAttrib< ParticleOrigin >, and ParticleInteractAttrib< T >.
putMessage() [1/2]
virtual size_t ParticleAttribBase::putMessage (Message & , size_t , size_t) pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, ParticleAttrib< ParticleOrigin >, and ParticleInteractAttrib< T >.
putMessage() [2/2]
virtual size_t ParticleAttribBase::putMessage (Message & , const std::vector< size_t > &) pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, ParticleAttrib< ParticleOrigin >, and ParticleInteractAttrib< T >.
setTemporary()
void ParticleAttribBase::setTemporary (bool t) inline
Definition at line 80 of file ParticleAttribBase.h.
References Temporary.
sort()
virtual void ParticleAttribBase::sort (SortList_t & slist) pure virtual
Implemented in ParticleAttrib< T >, ParticleAttrib< ParticleType >, ParticleAttrib< double >, ParticleAttrib< int >, ParticleAttrib< short >, ParticleAttrib< Vektor >, ParticleAttrib< CacheDataCIC< double, 3U > >, and ParticleAttrib< ParticleOrigin >.
typeString()
const std::string& ParticleAttribBase::typeString () const inline
Definition at line 75 of file ParticleAttribBase.h.
References TypeString.
Referenced by DiscParticle::write().
Member Data Documentation
ElementSize
unsigned int ParticleAttribBase::ElementSize private
Definition at line 169 of file ParticleAttribBase.h.
Referenced by elementSize().
Temporary
bool ParticleAttribBase::Temporary private
Definition at line 176 of file ParticleAttribBase.h.
Referenced by isTemporary(), and setTemporary().
TypeString
std::string ParticleAttribBase::TypeString private
Definition at line 172 of file ParticleAttribBase.h.
Referenced by typeString().
The documentation for this class was generated from the following file:
ippl/src/Particle/ParticleAttribBase.h