OPAL (Object Oriented Parallel Accelerator Library): AssignActions< Dim, SIExprTag< false > > Struct Template Reference
AssignActions< Dim, SIExprTag< false > > Struct Template Reference
#include <SIndexAssign.hpp>
Static Public Member Functions
template<class RHS >
static void fillgc (RHS &bb, const NDIndex< Dim > &)
template<class RHS >
static bool plugbase (RHS &bb, const NDIndex< Dim > &)
template<class RHS >
static void nextLField (RHS &bb)
Detailed Description
template<unsigned Dim>
struct AssignActions< Dim, SIExprTag< false > >
Definition at line 304 of file SIndexAssign.hpp.
Member Function Documentation
fillgc()
template<unsigned Dim> template<class RHS > static void AssignActions< Dim, SIExprTag< false > >::fillgc (RHS & bb, const NDIndex< Dim > &) inline static
Definition at line 306 of file SIndexAssign.hpp.
References FillGCIfNecessary(), and for_each().
nextLField()
template<unsigned Dim> template<class RHS > static void AssignActions< Dim, SIExprTag< false > >::nextLField (RHS & bb) inline static
Definition at line 322 of file SIndexAssign.hpp.
References for_each().
plugbase()
template<unsigned Dim> template<class RHS > static bool AssignActions< Dim, SIExprTag< false > >::plugbase (RHS & bb, const NDIndex< Dim > &) inline static
Definition at line 315 of file SIndexAssign.hpp.
References for_each().
The documentation for this struct was generated from the following file:
ippl/src/Index/SIndexAssign.hpp