OPAL (Object Oriented Parallel Accelerator Library): DiscBuffer Class Reference
DiscBuffer Class Reference
#include <DiscBuffer.h>
Public Member Functions
DiscBuffer ()
~DiscBuffer ()
Static Public Member Functions
static long size ()
static void * buffer ()
static void * resize (long sz)
static void * grow (long amt)
Static Public Attributes
static double readtime = 0.0
static double writetime = 0.0
static long readbytes = 0
static long writebytes = 0
Static Private Attributes
static long size_s = 0
static char * buffer_s = 0
Detailed Description
Definition at line 29 of file DiscBuffer.h.
Constructor & Destructor Documentation
DiscBuffer()
DiscBuffer::DiscBuffer ()
Definition at line 55 of file DiscBuffer.cpp.
~DiscBuffer()
DiscBuffer::~DiscBuffer ()
Definition at line 64 of file DiscBuffer.cpp.
References buffer_s, and size_s.
Member Function Documentation
buffer()
static void* DiscBuffer::buffer () inline static
Definition at line 55 of file DiscBuffer.h.
References buffer_s.
Referenced by resize().
grow()
static void* DiscBuffer::grow (long amt) inline static
Definition at line 73 of file DiscBuffer.h.
References PAssert_GE, resize(), and size().
resize()
void * DiscBuffer::resize (long sz) static
Definition at line 79 of file DiscBuffer.cpp.
References buffer(), buffer_s, PAssert, PAssert_GE, and size_s.
Referenced by grow(), DiscField< Dim >::read(), and DiscField< Dim >::write_offset_and_data().
size()
static long DiscBuffer::size (void) inline static
Definition at line 48 of file DiscBuffer.h.
References size_s.
Referenced by grow().
Member Data Documentation
buffer_s
char * DiscBuffer::buffer_s = 0 static private
Definition at line 94 of file DiscBuffer.h.
Referenced by buffer(), resize(), and ~DiscBuffer().
readbytes
long DiscBuffer::readbytes = 0 static
Definition at line 84 of file DiscBuffer.h.
Referenced by DiscField< Dim >::read_data().
readtime
double DiscBuffer::readtime = 0.0 static
Definition at line 82 of file DiscBuffer.h.
Referenced by DiscField< Dim >::read_data().
size_s
long DiscBuffer::size_s = 0 static private
Definition at line 90 of file DiscBuffer.h.
Referenced by resize(), size(), and ~DiscBuffer().
writebytes
long DiscBuffer::writebytes = 0 static
Definition at line 85 of file DiscBuffer.h.
Referenced by DiscField< Dim >::write_offset_and_data().
writetime
double DiscBuffer::writetime = 0.0 static
Definition at line 83 of file DiscBuffer.h.
Referenced by DiscField< Dim >::write_offset_and_data().
The documentation for this class was generated from the following files:
ippl/src/Utility/DiscBuffer.h
ippl/src/Utility/DiscBuffer.cpp