OPAL (Object Oriented Parallel Accelerator Library): ElmPtr Class Reference
ElmPtr Class Reference
A section of a beam line.
#include <ElmPtr.h>
Public Member Functions
ElmPtr ()
ElmPtr (const ElmPtr &)
ElmPtr (ElementBase *)
virtual ~ElmPtr ()
virtual void accept (BeamlineVisitor &) const
Apply visitor.
ElementBase * getElement () const
Get the element pointer.
void setElement (ElementBase *)
Set the element pointer.
Protected Attributes
Pointer< ElementBase > itsElement
Detailed Description
A section of a beam line.
Definition at line 32 of file ElmPtr.h.
Constructor & Destructor Documentation
ElmPtr() [1/3]
ElmPtr::ElmPtr ()
Definition at line 26 of file ElmPtr.cpp.
ElmPtr() [2/3]
ElmPtr::ElmPtr (const ElmPtr & rhs)
Definition at line 31 of file ElmPtr.cpp.
ElmPtr() [3/3]
ElmPtr::ElmPtr (ElementBase * elem)
Definition at line 36 of file ElmPtr.cpp.
~ElmPtr()
ElmPtr::~ElmPtr () virtual
Definition at line 41 of file ElmPtr.cpp.
Member Function Documentation
accept()
void ElmPtr::accept (BeamlineVisitor & visitor) const virtual
Apply visitor.
Reimplemented in FlaggedElmPtr.
Definition at line 45 of file ElmPtr.cpp.
References ElementBase::accept(), and itsElement.
getElement()
ElementBase * ElmPtr::getElement () const inline
Get the element pointer.
Definition at line 58 of file ElmPtr.h.
References itsElement.
Referenced by Sequence::copy(), PlaceRep::enter(), Selector::handleElement(), PlaceRep::leave(), Sequence::print(), SequenceMember::setLength(), RangeSelector::visitFlaggedElmPtr(), Replacer::visitFlaggedElmPtr(), DefaultVisitor::visitFlaggedElmPtr(), and SpecificElementVisitor< ELEM >::visitFlaggedElmPtr().
setElement()
void ElmPtr::setElement (ElementBase * elem) inline
Set the element pointer.
Definition at line 63 of file ElmPtr.h.
References itsElement.
Referenced by Sequence::addEndMarkers(), Sequence::copy(), Sequence::insertDrifts(), and SequenceParser::parseMember().
Member Data Documentation
itsElement
Pointer<ElementBase> ElmPtr::itsElement protected
Definition at line 54 of file ElmPtr.h.
Referenced by accept(), getElement(), and setElement().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Beamlines/ElmPtr.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Beamlines/ElmPtr.cpp