OPAL (Object Oriented Parallel Accelerator Library): Line Class Reference
Line Class Reference
#include <Line.h>
Public Member Functions
Line ()
Exemplar constructor.
virtual ~Line ()
virtual Line * clone (const std::string &name)
Make clone.
virtual Line * copy (const std::string &name)
Make complete copy.
virtual double getLength () const
Return line length.
virtual Object * makeTemplate (const std::string &name, TokenStream &is, Statement &stat)
Make a line template.
virtual void parse (Statement &stat)
Parse the line object.
virtual void print (std::ostream &stream) const
Print the line.
Public Member Functions inherited from BeamSequence
virtual ~BeamSequence ()
virtual const std::string getCategory () const
Return the object category as a string.
Public Member Functions inherited from Element
virtual ~Element ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual double getEntrance (ReferenceType) const
Return arc length from origin to entrance (negative !).
virtual double getExit (ReferenceType) const
Return arc length from origin to exit (positive !).
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded CLASSIC element.
void setElement (ElementBase *)
Assign new CLASSIC element.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
Line (const Line &)
void operator= (const Line &)
Line (const std::string &name, Line *parent)
virtual FlaggedBeamline * fetchLine () const
Return the embedded CLASSIC beam line.
void parseList (Statement &)
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
Friends
class LineTemplate
Additional Inherited Members
Public Types inherited from Element
enum ReferenceType { IS_ENTRY, IS_CENTRE, IS_EXIT }
Reference for element positioning.
Static Public Member Functions inherited from BeamSequence
static BeamSequence * find (const std::string &name)
Find a BeamSequence by name.
Static Public Member Functions inherited from Element
static Element * find (const std::string &name)
Find named Element.
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from BeamSequence
BeamSequence (int size, const char *name, const char *help)
Constructor for exemplars.
BeamSequence (const std::string &name, BeamSequence *parent)
Constructor for clones.
Protected Member Functions inherited from Element
Element (int size, const char *name, const char *help)
Constructor for exemplars.
Element (const std::string &name, Element *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 32 of file Line.h.
Constructor & Destructor Documentation
Line() [1/3]
Line::Line ()
Exemplar constructor.
Definition at line 65 of file Line.cpp.
References Object::itsAttr, Attributes::makeReal(), Attributes::makeRealArray(), Attributes::makeString(), Object::registerOwnership(), Element::setElement(), AttributeHandler::STATEMENT, Attrib::Distribution::TYPE, and X.
Referenced by clone(), and copy().
~Line()
Line::~Line () virtual
Definition at line 113 of file Line.cpp.
Line() [2/3]
Line::Line (const Line &) private
Line() [3/3]
Line::Line (const std::string & name, Line * parent) private
Definition at line 106 of file Line.cpp.
References name, and Element::setElement().
Member Function Documentation
clone()
Line * Line::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 117 of file Line.cpp.
References Line(), and name.
Referenced by copy(), LineTemplate::makeInstance(), and PyOpal::PyLine_< C >::registerObject().
copy()
Line * Line::copy (const std::string & name) virtual
Make complete copy.
Implements BeamSequence.
Definition at line 122 of file Line.cpp.
References clone(), fetchLine(), Line(), and name.
fetchLine()
FlaggedBeamline * Line::fetchLine () const private virtual
Return the embedded CLASSIC beam line.
Implements BeamSequence.
Definition at line 289 of file Line.cpp.
References Element::getElement().
Referenced by copy(), parseList(), print(), and replace().
getLength()
double Line::getLength () const virtual
Return line length.
Implements Element.
Definition at line 130 of file Line.cpp.
References Attributes::getReal(), and Object::itsAttr.
makeTemplate()
Object * Line::makeTemplate (const std::string & name, TokenStream & is, Statement & stat) virtual
Make a line template.
Reimplemented from Object.
Definition at line 136 of file Line.cpp.
References name, and LineTemplate::parseTemplate().
operator=()
void Line::operator= (const Line &) private
parse()
void Line::parse (Statement & stat) virtual
Parse the line object.
Reimplemented from Object.
Definition at line 150 of file Line.cpp.
Referenced by LineTemplate::makeInstance().
parseList()
void Line::parseList (Statement & stat) private
Definition at line 294 of file Line.cpp.
References Statement::delimiter(), fetchLine(), OpalData::find(), OpalData::getInstance(), Statement::integer(), Pointer< Object >::isValid(), Object::makeInstance(), name, Expressions::parseDelimiter(), parseList(), Expressions::parseString(), and FlaggedElmPtr::setReflectionFlag().
Referenced by parseList().
print()
void Line::print (std::ostream & stream) const virtual
Print the line.
Reimplemented from Object.
Definition at line 267 of file Line.cpp.
References endl(), fetchLine(), Object::getOpalName(), and name.
replace()
void Line::replace (Object * oldObject, Object * newObject) private virtual
Replace references.
Reimplemented from Object.
Definition at line 361 of file Line.cpp.
References DefaultVisitor::execute(), fetchLine(), Element::getElement(), and Object::getOpalName().
Friends And Related Function Documentation
LineTemplate
friend class LineTemplate friend
Definition at line 34 of file Line.h.
The documentation for this class was generated from the following files:
src/Lines/Line.h
src/Lines/Line.cpp