OPAL (Object Oriented Parallel Accelerator Library): SubParticleAttrib< PA, T, Dim > Class Template Reference
SubParticleAttrib< PA, T, Dim > Class Template Reference
#include <SubParticleAttrib.h>
Public Types
enum { Dim_u = Dim }
enum { IsExpr = 1 }
typedef PA Attrib_t
typedef T T_t
typedef SubParticleAttribIter< PA, T, Dim > iterator
typedef iterator::Index_t Index_t
typedef iterator PETE_Expr_t
Public Types inherited from PETE_Expr< SubParticleAttrib< PA, T, Dim > >
typedef SubParticleAttrib< PA, T, Dim > Wrapped
Public Member Functions
SubParticleAttrib (PA &a, const Index_t &dom)
SubParticleAttrib (const SubParticleAttrib< PA, T, Dim > &spa)
~SubParticleAttrib ()
const Index_t & getDomain () const
PA & getAttrib () const
void makeNDIndex (NDIndex< Dim > &i)
iterator begin () const
iterator end () const
int adjustSize ()
SubParticleAttrib< PA, T, Dim > & operator= (const SubParticleAttrib< PA, T, Dim > &)
SubParticleAttrib< PA, T, Dim > & operator= (T)
template<class B >
SubParticleAttrib< PA, T, Dim > & operator= (const PETE_Expr< B > &b)
void write (std::ostream &) const
PETE_Expr_t MakeExpression () const
Public Member Functions inherited from PETE_Expr< SubParticleAttrib< PA, T, Dim > >
SubParticleAttrib< PA, T, Dim > & PETE_unwrap ()
const SubParticleAttrib< PA, T, Dim > & PETE_unwrap () const
Static Public Member Functions
static int getSubsetType ()
Private Attributes
PA & A
const Index_t & MyDomain
Detailed Description
template<class PA, class T, unsigned Dim>
class SubParticleAttrib< PA, T, Dim >
Definition at line 58 of file SubParticleAttrib.h.
Member Typedef Documentation
Attrib_t
template<class PA, class T, unsigned Dim> typedef PA SubParticleAttrib< PA, T, Dim >::Attrib_t
Definition at line 154 of file SubParticleAttrib.h.
Index_t
template<class PA, class T, unsigned Dim> typedef iterator::Index_t SubParticleAttrib< PA, T, Dim >::Index_t
Definition at line 157 of file SubParticleAttrib.h.
iterator
template<class PA, class T, unsigned Dim> typedef SubParticleAttribIter<PA,T,Dim> SubParticleAttrib< PA, T, Dim >::iterator
Definition at line 156 of file SubParticleAttrib.h.
PETE_Expr_t
template<class PA, class T, unsigned Dim> typedef iterator SubParticleAttrib< PA, T, Dim >::PETE_Expr_t
Definition at line 234 of file SubParticleAttrib.h.
T_t
template<class PA, class T, unsigned Dim> typedef T SubParticleAttrib< PA, T, Dim >::T_t
Definition at line 155 of file SubParticleAttrib.h.
Member Enumeration Documentation
anonymous enum
template<class PA, class T, unsigned Dim> anonymous enum
Enumerator
Dim_u
Definition at line 160 of file SubParticleAttrib.h.
anonymous enum
template<class PA, class T, unsigned Dim> anonymous enum
Enumerator
IsExpr
Definition at line 233 of file SubParticleAttrib.h.
Constructor & Destructor Documentation
SubParticleAttrib() [1/2]
template<class PA, class T, unsigned Dim> SubParticleAttrib< PA, T, Dim >::SubParticleAttrib (PA & a, const Index_t & dom) inline
Definition at line 163 of file SubParticleAttrib.h.
SubParticleAttrib() [2/2]
template<class PA, class T, unsigned Dim> SubParticleAttrib< PA, T, Dim >::SubParticleAttrib (const SubParticleAttrib< PA, T, Dim > & spa) inline
Definition at line 167 of file SubParticleAttrib.h.
~SubParticleAttrib()
template<class PA, class T, unsigned Dim> SubParticleAttrib< PA, T, Dim >::~SubParticleAttrib () inline
Definition at line 171 of file SubParticleAttrib.h.
Member Function Documentation
adjustSize()
template<class PA , class T , unsigned Dim> int SubParticleAttrib< PA, T, Dim >::adjustSize ()
Definition at line 90 of file SubParticleAttrib.hpp.
begin()
template<class PA , class T , unsigned Dim> SubParticleAttrib< PA, T, Dim >::iterator SubParticleAttrib< PA, T, Dim >::begin () const
Definition at line 67 of file SubParticleAttrib.hpp.
Referenced by SubParticleAttrib< PA, T, Dim >::MakeExpression().
end()
template<class PA , class T , unsigned Dim> SubParticleAttrib< PA, T, Dim >::iterator SubParticleAttrib< PA, T, Dim >::end () const
Definition at line 77 of file SubParticleAttrib.hpp.
getAttrib()
template<class PA, class T, unsigned Dim> PA& SubParticleAttrib< PA, T, Dim >::getAttrib () const inline
Definition at line 181 of file SubParticleAttrib.h.
References SubParticleAttrib< PA, T, Dim >::A.
getDomain()
template<class PA, class T, unsigned Dim> const Index_t& SubParticleAttrib< PA, T, Dim >::getDomain (void) const inline
Definition at line 178 of file SubParticleAttrib.h.
References SubParticleAttrib< PA, T, Dim >::MyDomain.
getSubsetType()
template<class PA, class T, unsigned Dim> static int SubParticleAttrib< PA, T, Dim >::getSubsetType () inline static
Definition at line 184 of file SubParticleAttrib.h.
References SubParticleAttribIter< PA, T, Dim >::getSubsetType().
MakeExpression()
template<class PA, class T, unsigned Dim> PETE_Expr_t SubParticleAttrib< PA, T, Dim >::MakeExpression () const inline
Definition at line 235 of file SubParticleAttrib.h.
References SubParticleAttrib< PA, T, Dim >::begin().
makeNDIndex()
template<class PA, class T, unsigned Dim> void SubParticleAttrib< PA, T, Dim >::makeNDIndex (NDIndex< Dim > & i) inline
Definition at line 187 of file SubParticleAttrib.h.
References SubParticleAttribIter< PA, T, Dim >::makeNDIndex(), and SubParticleAttrib< PA, T, Dim >::MyDomain.
operator=() [1/3]
template<class PA, class T, unsigned Dim> SubParticleAttrib< PA, T, Dim > & SubParticleAttrib< PA, T, Dim >::operator= (const SubParticleAttrib< PA, T, Dim > & t)
Definition at line 38 of file SubParticleAttrib.hpp.
References assign().
operator=() [2/3]
template<class PA, class T, unsigned Dim> SubParticleAttrib< PA, T, Dim > & SubParticleAttrib< PA, T, Dim >::operator= (T t)
Definition at line 51 of file SubParticleAttrib.hpp.
References assign().
operator=() [3/3]
template<class PA, class T, unsigned Dim> template<class B > SubParticleAttrib<PA,T,Dim>& SubParticleAttrib< PA, T, Dim >::operator= (const PETE_Expr< B > & b) inline
Definition at line 215 of file SubParticleAttrib.h.
References assign().
write()
template<class PA , class T , unsigned Dim> void SubParticleAttrib< PA, T, Dim >::write (std::ostream & o) const
Definition at line 113 of file SubParticleAttrib.hpp.
References endl(), and PInsist.
Member Data Documentation
A
template<class PA, class T, unsigned Dim> PA& SubParticleAttrib< PA, T, Dim >::A private
Definition at line 239 of file SubParticleAttrib.h.
Referenced by SubParticleAttrib< PA, T, Dim >::getAttrib().
MyDomain
template<class PA, class T, unsigned Dim> const Index_t& SubParticleAttrib< PA, T, Dim >::MyDomain private
Definition at line 242 of file SubParticleAttrib.h.
Referenced by SubParticleAttrib< PA, T, Dim >::getDomain(), and SubParticleAttrib< PA, T, Dim >::makeNDIndex().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/SubParticle/SubParticleAttrib.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/SubParticle/SubParticleAttrib.hpp