OPAL (Object Oriented Parallel Accelerator Library): _Astra1DMagnetoStatic_fast Class Reference
_Astra1DMagnetoStatic_fast Class Reference
#include <Astra1DMagnetoStatic_fast.h>
Public Member Functions
virtual ~_Astra1DMagnetoStatic_fast ()
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const
virtual void getFieldDimensions (double &zBegin, double &zEnd) const
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const
virtual bool getFieldDerivative (const Vector_t &R, Vector_t &E, Vector_t &B, const DiffDirection &dir) const
virtual void swap ()
virtual void getInfo (Inform *)
virtual double getFrequency () const
virtual void setFrequency (double freq)
Public Member Functions inherited from _Astra1D_fast
virtual ~_Astra1D_fast ()
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &F)
virtual bool isInside (const Vector_t &r) const
Public Member Functions inherited from _Fieldmap
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Private Member Functions
_Astra1DMagnetoStatic_fast (const std::string &filename)
virtual void readMap ()
bool readFileHeader (std::ifstream &file)
int stripFileHeader (std::ifstream &file)
Static Private Member Functions
static Astra1DMagnetoStatic_fast create (const std::string &filename)
Friends
class _Fieldmap
Additional Inherited Members
Static Public Member Functions inherited from _Fieldmap
static Fieldmap getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions inherited from _Astra1D_fast
_Astra1D_fast (const std::string &filename)
virtual void freeMap ()
bool determineNumSamplingPoints (std::ifstream &file)
double readFieldData (std::ifstream &file)
void normalizeFieldData (double maxEz)
std::vector< double > getEvenlyDistributedSamplingPoints ()
std::vector< double > interpolateFieldData (std::vector< double > &samplingPoints)
void computeFieldDerivatives (std::vector< double > &fourierComponents, int accuracy)
std::vector< double > computeFourierCoefficients (int accuracy, std::vector< double > &evenSampling)
Protected Member Functions inherited from _Fieldmap
_Fieldmap ()=delete
_Fieldmap (const std::string &filename)
virtual ~_Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions inherited from _Fieldmap
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes inherited from _Astra1D_fast
double * onAxisField_m
double * zvals_m
gsl_spline * onAxisInterpolants_m [4]
gsl_interp_accel * onAxisAccel_m [4]
double hz_m
double zbegin_m
double zend_m
double length_m
int num_gridpz_m
int numHeaderLines_m
Protected Attributes inherited from _Fieldmap
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Detailed Description
Definition at line 7 of file Astra1DMagnetoStatic_fast.h.
Constructor & Destructor Documentation
~_Astra1DMagnetoStatic_fast()
_Astra1DMagnetoStatic_fast::~_Astra1DMagnetoStatic_fast () virtual
Definition at line 41 of file Astra1DMagnetoStatic_fast.cpp.
References _Astra1D_fast::freeMap().
_Astra1DMagnetoStatic_fast()
_Astra1DMagnetoStatic_fast::_Astra1DMagnetoStatic_fast (const std::string & filename) private
Definition at line 9 of file Astra1DMagnetoStatic_fast.cpp.
References _Astra1D_fast::determineNumSamplingPoints(), _Fieldmap::disableFieldmapWarning(), Physics::e, _Fieldmap::Filename_m, _Astra1D_fast::hz_m, _Astra1D_fast::length_m, _Fieldmap::noFieldmapWarning(), _Astra1D_fast::num_gridpz_m, _Astra1D_fast::numHeaderLines_m, _Astra1D_fast::onAxisField_m, readFileHeader(), TAstraMagnetoStatic, _Fieldmap::Type, _Astra1D_fast::zbegin_m, and _Astra1D_fast::zend_m.
Referenced by create().
Member Function Documentation
create()
Astra1DMagnetoStatic_fast _Astra1DMagnetoStatic_fast::create (const std::string & filename) static private
Definition at line 45 of file Astra1DMagnetoStatic_fast.cpp.
References _Astra1DMagnetoStatic_fast().
Referenced by _Fieldmap::getFieldmap().
getFieldDerivative()
bool _Astra1DMagnetoStatic_fast::getFieldDerivative (const Vector_t & R, Vector_t & E, Vector_t & B, const DiffDirection & dir) const virtual
Implements _Astra1D_fast.
Definition at line 98 of file Astra1DMagnetoStatic_fast.cpp.
getFieldDimensions() [1/2]
void _Astra1DMagnetoStatic_fast::getFieldDimensions (double & zBegin, double & zEnd) const virtual
Implements _Astra1D_fast.
Definition at line 102 of file Astra1DMagnetoStatic_fast.cpp.
References _Astra1D_fast::zbegin_m, and _Astra1D_fast::zend_m.
getFieldDimensions() [2/2]
void _Astra1DMagnetoStatic_fast::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const virtual
Implements _Astra1D_fast.
Definition at line 107 of file Astra1DMagnetoStatic_fast.cpp.
getFieldstrength()
bool _Astra1DMagnetoStatic_fast::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const virtual
Implements _Astra1D_fast.
Definition at line 80 of file Astra1DMagnetoStatic_fast.cpp.
References _Astra1D_fast::onAxisAccel_m, _Astra1D_fast::onAxisInterpolants_m, Attrib::Distribution::R, and _Astra1D_fast::zbegin_m.
getFrequency()
double _Astra1DMagnetoStatic_fast::getFrequency () const virtual
Implements _Astra1D_fast.
Definition at line 116 of file Astra1DMagnetoStatic_fast.cpp.
getInfo()
void _Astra1DMagnetoStatic_fast::getInfo (Inform * msg) virtual
Implements _Astra1D_fast.
Definition at line 112 of file Astra1DMagnetoStatic_fast.cpp.
References endl(), _Fieldmap::Filename_m, _Astra1D_fast::zbegin_m, and _Astra1D_fast::zend_m.
readFileHeader()
bool _Astra1DMagnetoStatic_fast::readFileHeader (std::ifstream & file) private
Definition at line 123 of file Astra1DMagnetoStatic_fast.cpp.
References Physics::e, _Fieldmap::normalize_m, and Util::toUpper().
Referenced by _Astra1DMagnetoStatic_fast().
readMap()
void _Astra1DMagnetoStatic_fast::readMap () private virtual
Reimplemented from _Astra1D_fast.
Definition at line 50 of file Astra1DMagnetoStatic_fast.cpp.
References _Fieldmap::checkMap(), _Astra1D_fast::computeFieldDerivatives(), _Astra1D_fast::computeFourierCoefficients(), endl(), _Fieldmap::Filename_m, _Astra1D_fast::getEvenlyDistributedSamplingPoints(), INFOMSG, _Astra1D_fast::interpolateFieldData(), _Astra1D_fast::length_m, level3(), _Astra1D_fast::normalizeFieldData(), _Astra1D_fast::num_gridpz_m, _Astra1D_fast::onAxisAccel_m, _Astra1D_fast::onAxisField_m, _Astra1D_fast::onAxisInterpolants_m, _Astra1D_fast::readFieldData(), stripFileHeader(), _Fieldmap::typeset_msg(), and _Astra1D_fast::zvals_m.
setFrequency()
void _Astra1DMagnetoStatic_fast::setFrequency (double freq) virtual
Implements _Astra1D_fast.
Definition at line 120 of file Astra1DMagnetoStatic_fast.cpp.
stripFileHeader()
int _Astra1DMagnetoStatic_fast::stripFileHeader (std::ifstream & file) private
Definition at line 146 of file Astra1DMagnetoStatic_fast.cpp.
References Physics::e.
Referenced by readMap().
swap()
void _Astra1DMagnetoStatic_fast::swap () virtual
Implements _Astra1D_fast.
Definition at line 109 of file Astra1DMagnetoStatic_fast.cpp.
Friends And Related Function Documentation
_Fieldmap
friend class _Fieldmap friend
Definition at line 31 of file Astra1DMagnetoStatic_fast.h.
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/Astra1DMagnetoStatic_fast.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/Astra1DMagnetoStatic_fast.cpp