OPAL (Object Oriented Parallel Accelerator Library): HashPairBuilder< PBase > Class Template Reference
HashPairBuilder< PBase > Class Template Reference
#include <HashPairBuilder.h>
Public Types
enum { Dim = PBase::Dim }
typedef PBase::Position_t Position_t
Public Member Functions
HashPairBuilder (PBase &p)
template<class Pred , class OP >
void for_each (const Pred &pred, const OP &op)
Private Member Functions
template<class Pred >
int sum (int i, const Pred &pred, int f[], int offset[])
template<class Pred >
int get_bucket_id (int i, const Pred &pred)
int mod (int x, int m)
Private Attributes
PBase & particles
Vektor< int, 3 > buckets_per_dim
Vektor< double, 3 > rmin_m
Vektor< double, 3 > rmax_m
Detailed Description
template<class PBase>
class HashPairBuilder< PBase >
Definition at line 10 of file HashPairBuilder.h.
Member Typedef Documentation
Position_t
template<class PBase > typedef PBase::Position_t HashPairBuilder< PBase >::Position_t
Definition at line 14 of file HashPairBuilder.h.
Member Enumeration Documentation
anonymous enum
template<class PBase > anonymous enum
Enumerator
Dim
Definition at line 13 of file HashPairBuilder.h.
Constructor & Destructor Documentation
HashPairBuilder()
template<class PBase > HashPairBuilder< PBase >::HashPairBuilder (PBase & p) inline
Definition at line 16 of file HashPairBuilder.h.
Member Function Documentation
for_each()
template<class PBase > template<class Pred , class OP > void HashPairBuilder< PBase >::for_each (const Pred & pred, const OP & op) inline
Definition at line 19 of file HashPairBuilder.h.
References bounds(), HashPairBuilder< PBase >::buckets_per_dim, ceil(), endl(), HashPairBuilder< PBase >::get_bucket_id(), max(), Hypervolume::n, HashPairBuilder< PBase >::particles, HashPairBuilder< PBase >::rmax_m, and HashPairBuilder< PBase >::rmin_m.
get_bucket_id()
template<class PBase > template<class Pred > int HashPairBuilder< PBase >::get_bucket_id (int i, const Pred & pred) inline private
Definition at line 202 of file HashPairBuilder.h.
References HashPairBuilder< PBase >::buckets_per_dim, HashPairBuilder< PBase >::particles, and HashPairBuilder< PBase >::rmin_m.
Referenced by HashPairBuilder< PBase >::for_each().
mod()
template<class PBase > int HashPairBuilder< PBase >::mod (int x, int m) inline private
Definition at line 212 of file HashPairBuilder.h.
Referenced by HashPairBuilder< PBase >::sum().
sum()
template<class PBase > template<class Pred > int HashPairBuilder< PBase >::sum (int i, const Pred & pred, int f[], int offset[]) inline private
Definition at line 183 of file HashPairBuilder.h.
References HashPairBuilder< PBase >::Dim, endl(), floor(), HashPairBuilder< PBase >::mod(), and HashPairBuilder< PBase >::particles.
Member Data Documentation
buckets_per_dim
template<class PBase > Vektor<int,3> HashPairBuilder< PBase >::buckets_per_dim private
Definition at line 221 of file HashPairBuilder.h.
Referenced by HashPairBuilder< PBase >::for_each(), and HashPairBuilder< PBase >::get_bucket_id().
particles
template<class PBase > PBase& HashPairBuilder< PBase >::particles private
Definition at line 220 of file HashPairBuilder.h.
Referenced by HashPairBuilder< PBase >::for_each(), HashPairBuilder< PBase >::get_bucket_id(), and HashPairBuilder< PBase >::sum().
rmax_m
template<class PBase > Vektor<double,3> HashPairBuilder< PBase >::rmax_m private
Definition at line 224 of file HashPairBuilder.h.
Referenced by HashPairBuilder< PBase >::for_each().
rmin_m
template<class PBase > Vektor<double,3> HashPairBuilder< PBase >::rmin_m private
Definition at line 223 of file HashPairBuilder.h.
Referenced by HashPairBuilder< PBase >::for_each(), and HashPairBuilder< PBase >::get_bucket_id().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/PairBuilder/HashPairBuilder.h