OPAL (Object Oriented Parallel Accelerator Library): MultiBunchDump Class Reference
MultiBunchDump Class Reference
#include <MultiBunchDump.h>
Public Types
typedef MultiBunchHandler::beaminfo_t beaminfo_t
Public Types inherited from SDDSWriter
typedef std::pair< std::string, std::string > desc_t
typedef std::tuple< std::string, std::string, std::string > param_t
typedef std::pair< std::string, size_t > data_t
typedef std::tuple< std::string, std::string, std::string, std::string > cols_t
Public Member Functions
MultiBunchDump (const std::string &fname, bool restart)
void fillHeader ()
void write (const PartBunchBase< double, 3 > *beam, const beaminfo_t &binfo)
virtual void write (const PartBunchBase< double, 3 > *)
Public Member Functions inherited from StatBaseWriter
StatBaseWriter (const std::string &fname, bool restart)
unsigned int rewindToSpos (double maxSpos)
delete the last 'numberOfLines' lines of the statistics file
Public Member Functions inherited from SDDSWriter
SDDSWriter (const std::string &fname, bool restart)
virtual ~SDDSWriter ()
virtual void write (const PartBunchBase< double, 3 > *)
void rewindLines (size_t numberOfLines)
delete the last 'numberOfLines' lines of the file 'fileName'
void replaceVersionString ()
double getLastValue (const std::string &column)
bool exists () const
Additional Inherited Members
Protected Member Functions inherited from SDDSWriter
void addDescription (const std::string &text, const std::string &content)
template<typename T >
void addParameter (const std::string &name, const std::string &type, const std::string &desc, const T &value)
void addDefaultParameters ()
void addColumn (const std::string &name, const std::string &type, const std::string &unit, const std::string &desc)
void addInfo (const std::string &mode, const size_t &no_row_counts)
void writeRow ()
void open ()
void close ()
void writeHeader ()
Write SDDS header.
template<typename T >
std::string toString (const T &val)
bool hasColumns () const
Protected Attributes inherited from SDDSWriter
std::string fname_m
std::ios_base::openmode mode_m
First write to the statistics output file.
SDDSColumnSet columns_m
Detailed Description
Definition at line 29 of file MultiBunchDump.h.
Member Typedef Documentation
beaminfo_t
typedef MultiBunchHandler::beaminfo_t MultiBunchDump::beaminfo_t
Definition at line 32 of file MultiBunchDump.h.
Constructor & Destructor Documentation
MultiBunchDump()
MultiBunchDump::MultiBunchDump (const std::string & fname, bool restart)
Definition at line 33 of file MultiBunchDump.cpp.
Member Function Documentation
fillHeader()
void MultiBunchDump::fillHeader ()
Definition at line 38 of file MultiBunchDump.cpp.
References SDDSColumnSet::addColumn(), SDDSWriter::addDefaultParameters(), SDDSWriter::addDescription(), SDDSWriter::addInfo(), SDDSWriter::columns_m, OPALTimer::Timer::date(), OpalData::getInputFn(), OpalData::getInstance(), SDDSWriter::hasColumns(), SDDSWriter::mode_m, and OPALTimer::Timer::time().
Referenced by write().
write() [1/2]
virtual void SDDSWriter::write inline
Definition at line 66 of file SDDSWriter.h.
write() [2/2]
void MultiBunchDump::write (const PartBunchBase< double, 3 > * beam, const beaminfo_t & binfo)
Definition at line 96 of file MultiBunchDump.cpp.
References SDDSColumnSet::addColumnValue(), MultiBunchHandler::beaminfo_t::azimuth, SDDSWriter::close(), SDDSWriter::columns_m, MultiBunchHandler::beaminfo_t::correlation, MultiBunchHandler::beaminfo_t::dEkin, MultiBunchHandler::beaminfo_t::ekin, MultiBunchHandler::beaminfo_t::emit, fillHeader(), MultiBunchHandler::beaminfo_t::halo, MultiBunchHandler::beaminfo_t::mean, IpplInfo::myNode(), MultiBunchHandler::beaminfo_t::nParticles, SDDSWriter::open(), MultiBunchHandler::beaminfo_t::pathlength, MultiBunchHandler::beaminfo_t::prms, MultiBunchHandler::beaminfo_t::radius, MultiBunchHandler::beaminfo_t::rrms, MultiBunchHandler::beaminfo_t::time, SDDSWriter::writeHeader(), and SDDSWriter::writeRow().
The documentation for this class was generated from the following files:
src/Structure/MultiBunchDump.h
src/Structure/MultiBunchDump.cpp