OPAL (Object Oriented Parallel Accelerator Library): OptimizeCmd Class Reference
OptimizeCmd Class Reference
The OPTIMIZE command.
#include <OptimizeCmd.h>
Public Member Functions
OptimizeCmd ()
Exemplar constructor.
virtual ~OptimizeCmd ()
virtual OptimizeCmd * clone (const std::string &name)
Make clone.
virtual void execute ()
Execute the command.
Public Member Functions inherited from Action
virtual ~Action ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Types
enum CrossOver { Blend = 0, NaiveOnePoint, NaiveUniform, SimulatedBinary }
enum Mutation { IndependentBit = 10, OneBit = 20 }
Private Member Functions
OptimizeCmd (const OptimizeCmd &)=delete
void operator= (const OptimizeCmd &)=delete
OptimizeCmd (const std::string &name, OptimizeCmd *parent)
void stashEnvironment ()
void popEnvironment ()
CrossOver crossoverSelection (std::string crossover)
Mutation mutationSelection (std::string mutation)
void run (const CmdArguments_t &args, const functionDictionary_t &funcs, const DVarContainer_t &dvars, const Expressions::Named_t &objectives, const Expressions::Named_t &constraints)
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Action
Action (int size, const char *name, const char *help)
Constructor for exemplars.
Action (const std::string &name, Action *parent)
Constructor for cloning.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
The OPTIMIZE command.
Definition at line 16 of file OptimizeCmd.h.
Member Enumeration Documentation
CrossOver
enum OptimizeCmd::CrossOver private
Enumerator
Blend
NaiveOnePoint
NaiveUniform
SimulatedBinary
Definition at line 43 of file OptimizeCmd.h.
Mutation
enum OptimizeCmd::Mutation private
Enumerator
IndependentBit
OneBit
Definition at line 52 of file OptimizeCmd.h.
Constructor & Destructor Documentation
OptimizeCmd() [1/3]
OptimizeCmd::OptimizeCmd ()
Exemplar constructor.
Definition at line 108 of file OptimizeCmd.cpp.
References AttributeHandler::COMMAND, Object::itsAttr, Attributes::makeBool(), Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeRealArray(), Attributes::makeString(), Attributes::makeStringArray(), min(), and Object::registerOwnership().
Referenced by clone().
~OptimizeCmd()
OptimizeCmd::~OptimizeCmd () virtual
Definition at line 189 of file OptimizeCmd.cpp.
OptimizeCmd() [2/3]
OptimizeCmd::OptimizeCmd (const OptimizeCmd &) private delete
OptimizeCmd() [3/3]
OptimizeCmd::OptimizeCmd (const std::string & name, OptimizeCmd * parent) private
Definition at line 185 of file OptimizeCmd.cpp.
Member Function Documentation
clone()
OptimizeCmd * OptimizeCmd::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 192 of file OptimizeCmd.cpp.
References name, and OptimizeCmd().
crossoverSelection()
OptimizeCmd::CrossOver OptimizeCmd::crossoverSelection (std::string crossover) private
Definition at line 528 of file OptimizeCmd.cpp.
Referenced by run().
execute()
void OptimizeCmd::execute () virtual
Execute the command.
Reimplemented from Object.
Definition at line 196 of file OptimizeCmd.cpp.
References Physics::e, endl(), Hypervolume::FromFile(), Hypervolume::fs, Attributes::getBool(), Objective::getExpression(), Constraint::getExpression(), OpalData::getInstance(), DVar::getLowerBound(), Attributes::getReal(), Attributes::getRealArray(), Attributes::getString(), Attributes::getStringArray(), DVar::getUpperBound(), DVar::getVariable(), gmsg, Object::itsAttr, name, run(), and SIZE.
mutationSelection()
OptimizeCmd::Mutation OptimizeCmd::mutationSelection (std::string mutation) private
Definition at line 557 of file OptimizeCmd.cpp.
Referenced by run().
operator=()
void OptimizeCmd::operator= (const OptimizeCmd &) private delete
popEnvironment()
void OptimizeCmd::popEnvironment () private
Definition at line 521 of file OptimizeCmd.cpp.
References Track::pop(), IpplTimings::pop(), IpplInfo::pop(), and OpalData::popInstance().
Referenced by run().
run()
void OptimizeCmd::run (const CmdArguments_t & args, const functionDictionary_t & funcs, const DVarContainer_t & dvars, const Expressions::Named_t & objectives, const Expressions::Named_t & constraints) private
Definition at line 578 of file OptimizeCmd.cpp.
References crossoverSelection(), OpalData::getInstance(), Attributes::getRealArray(), Attributes::getString(), OpalData::getVariableData(), Object::itsAttr, mutationSelection(), pi, popEnvironment(), and stashEnvironment().
Referenced by execute().
stashEnvironment()
void OptimizeCmd::stashEnvironment () private
Definition at line 514 of file OptimizeCmd.cpp.
References Track::stash(), IpplTimings::stash(), IpplInfo::stash(), and OpalData::stashInstance().
Referenced by run().
The documentation for this class was generated from the following files:
src/Optimize/OptimizeCmd.h
src/Optimize/OptimizeCmd.cpp