OPAL (Object Oriented Parallel Accelerator Library): IndexedBareField< T, Dim, Brackets > Class Template Reference
IndexedBareField< T, Dim, Brackets > Class Template Reference
#include <Assign.h>
Public Types
enum { Dim_u = Dim }
enum { IsExpr = 0 }
typedef T T_t
typedef IndexedBareFieldIterator< T, Dim > iterator
typedef iterator PETE_Expr_t
Public Types inherited from PETE_Expr< IndexedBareField< T, Dim, Brackets > >
typedef IndexedBareField< T, Dim, Brackets > Wrapped
Public Member Functions
constexpr IndexedBareField (const IndexedBareField< T, Dim, Brackets > &)=default
IndexedBareField< T, Dim, Brackets+1 > operator[] (const Index &idx)
IndexedBareField< T, Dim, Brackets+1 > operator[] (int i)
IndexedBareField< T, Dim, Brackets+1 > operator[] (const NDIndex< Dim > &ndidx)
void operator= (T x)
IndexedBareField< T, Dim, Brackets > & operator= (const IndexedBareField< T, Dim, Brackets > &x)
template<class X , unsigned Dim1, unsigned Brackets1>
IndexedBareField< T, Dim, Brackets > & operator= (const IndexedBareField< X, Dim1, Brackets1 > &x)
IndexedBareField< T, Dim, Brackets > & operator= (const Index &x)
template<class B >
IndexedBareField< T, Dim, Brackets > & operator= (const PETE_Expr< B > &x)
const NDIndex< Dim > & getDomain () const
BareField< T, Dim > & getBareField ()
const BareField< T, Dim > & getBareField () const
PETE_TUTree< OpParens< int >, iterator > operator() (int arg)
PETE_TUTree< OpParens< std::pair< int, int > >, iterator > operator() (int a1, int a2)
T get ()
iterator begin () const
iterator end () const
void write (std::ostream &)
iterator MakeExpression () const
Public Member Functions inherited from PETE_Expr< IndexedBareField< T, Dim, Brackets > >
IndexedBareField< T, Dim, Brackets > & PETE_unwrap ()
const IndexedBareField< T, Dim, Brackets > & PETE_unwrap () const
Protected Member Functions
IndexedBareField (BareField< T, Dim > &a, const Index &idx)
IndexedBareField (BareField< T, Dim > &a, int i)
IndexedBareField (BareField< T, Dim > &a, const NDIndex< Brackets-1 > &idx, const Index &i)
IndexedBareField (BareField< T, Dim > &a, const NDIndex< Dim > &ndidx)
void getsingle (T &)
Protected Attributes
BareField< T, Dim > & A
NDIndex< Brackets > Indexes
Friends
class IndexedBareField< T, Dim, Brackets-1 >
class BareField< T, Dim >
Detailed Description
template<class T, unsigned Dim, unsigned Brackets>
class IndexedBareField< T, Dim, Brackets >
Definition at line 21 of file Assign.h.
Member Typedef Documentation
iterator
template<class T, unsigned Dim, unsigned Brackets> typedef IndexedBareFieldIterator<T,Dim> IndexedBareField< T, Dim, Brackets >::iterator
Definition at line 204 of file IndexedBareField.h.
PETE_Expr_t
template<class T, unsigned Dim, unsigned Brackets> typedef iterator IndexedBareField< T, Dim, Brackets >::PETE_Expr_t
Definition at line 298 of file IndexedBareField.h.
T_t
template<class T, unsigned Dim, unsigned Brackets> typedef T IndexedBareField< T, Dim, Brackets >::T_t
Definition at line 202 of file IndexedBareField.h.
Member Enumeration Documentation
anonymous enum
template<class T, unsigned Dim, unsigned Brackets> anonymous enum
Enumerator
Dim_u
Definition at line 203 of file IndexedBareField.h.
anonymous enum
template<class T, unsigned Dim, unsigned Brackets> anonymous enum
Enumerator
IsExpr
Definition at line 297 of file IndexedBareField.h.
Constructor & Destructor Documentation
IndexedBareField() [1/5]
template<class T, unsigned Dim, unsigned Brackets> constexpr IndexedBareField< T, Dim, Brackets >::IndexedBareField (const IndexedBareField< T, Dim, Brackets > &) default
IndexedBareField() [2/5]
template<class T, unsigned Dim, unsigned Brackets> IndexedBareField< T, Dim, Brackets >::IndexedBareField (BareField< T, Dim > & a, const Index & idx) inline protected
Definition at line 307 of file IndexedBareField.h.
IndexedBareField() [3/5]
template<class T, unsigned Dim, unsigned Brackets> IndexedBareField< T, Dim, Brackets >::IndexedBareField (BareField< T, Dim > & a, int i) inline protected
Definition at line 309 of file IndexedBareField.h.
IndexedBareField() [4/5]
template<class T, unsigned Dim, unsigned Brackets> IndexedBareField< T, Dim, Brackets >::IndexedBareField (BareField< T, Dim > & a, const NDIndex< Brackets-1 > & idx, const Index & i) inline protected
Definition at line 311 of file IndexedBareField.h.
IndexedBareField() [5/5]
template<class T, unsigned Dim, unsigned Brackets> IndexedBareField< T, Dim, Brackets >::IndexedBareField (BareField< T, Dim > & a, const NDIndex< Dim > & ndidx) inline protected
Definition at line 315 of file IndexedBareField.h.
Member Function Documentation
begin()
template<class T, unsigned Dim, unsigned Brackets> iterator IndexedBareField< T, Dim, Brackets >::begin () const inline
Definition at line 290 of file IndexedBareField.h.
References IndexedBareField< T, Dim, Brackets >::A, and IndexedBareField< T, Dim, Brackets >::Indexes.
Referenced by IndexedBareField< T, Dim, Brackets >::MakeExpression(), and IndexedBareField< T, Dim, Brackets >::operator()().
end()
template<class T, unsigned Dim, unsigned Brackets> iterator IndexedBareField< T, Dim, Brackets >::end () const inline
Definition at line 291 of file IndexedBareField.h.
get()
template<class T , unsigned Dim, unsigned Brackets> T IndexedBareField< T, Dim, Brackets >::get ()
Definition at line 89 of file IndexedBareField.hpp.
References BareField< T, Dim >::getsingle(), and Attrib::Legacy::Distribution::T.
getBareField() [1/2]
template<class T, unsigned Dim, unsigned Brackets> BareField<T,Dim>& IndexedBareField< T, Dim, Brackets >::getBareField () inline
Definition at line 263 of file IndexedBareField.h.
References IndexedBareField< T, Dim, Brackets >::A.
Referenced by assign(), CalcIndexedReceive(), IndexedLocalAssign(), IndexedReceive(), and IndexedSend().
getBareField() [2/2]
template<class T, unsigned Dim, unsigned Brackets> const BareField<T,Dim>& IndexedBareField< T, Dim, Brackets >::getBareField () const inline
Definition at line 264 of file IndexedBareField.h.
References IndexedBareField< T, Dim, Brackets >::A.
getDomain()
template<class T, unsigned Dim, unsigned Brackets> const NDIndex<Dim>& IndexedBareField< T, Dim, Brackets >::getDomain (void) const inline
Definition at line 262 of file IndexedBareField.h.
References IndexedBareField< T, Dim, Brackets >::Indexes.
Referenced by assign(), CalcIndexedReceive(), IndexedLocalAssign(), IndexedReceive(), and IndexedSend().
getsingle()
template<class T , unsigned Dim, unsigned Brackets> void IndexedBareField< T, Dim, Brackets >::getsingle (T & r) protected
Definition at line 78 of file IndexedBareField.hpp.
MakeExpression()
template<class T, unsigned Dim, unsigned Brackets> iterator IndexedBareField< T, Dim, Brackets >::MakeExpression () const inline
Definition at line 299 of file IndexedBareField.h.
References IndexedBareField< T, Dim, Brackets >::begin().
operator()() [1/2]
template<class T, unsigned Dim, unsigned Brackets> PETE_TUTree< OpParens<int>, iterator > IndexedBareField< T, Dim, Brackets >::operator() (int arg) inline
Definition at line 270 of file IndexedBareField.h.
References arg(), IndexedBareField< T, Dim, Brackets >::begin(), CTAssert, and Dim.
operator()() [2/2]
template<class T, unsigned Dim, unsigned Brackets> PETE_TUTree< OpParens< std::pair<int,int> >, iterator > IndexedBareField< T, Dim, Brackets >::operator() (int a1, int a2) inline
Definition at line 277 of file IndexedBareField.h.
References IndexedBareField< T, Dim, Brackets >::begin(), CTAssert, and Dim.
operator=() [1/5]
template<class T, unsigned Dim, unsigned Brackets> void IndexedBareField< T, Dim, Brackets >::operator= (T x) inline
Definition at line 225 of file IndexedBareField.h.
References assign().
operator=() [2/5]
template<class T, unsigned Dim, unsigned Brackets> IndexedBareField<T,Dim,Brackets>& IndexedBareField< T, Dim, Brackets >::operator= (const IndexedBareField< T, Dim, Brackets > & x) inline
Definition at line 231 of file IndexedBareField.h.
References assign(), CTAssert, and Dim.
operator=() [3/5]
template<class T, unsigned Dim, unsigned Brackets> template<class X , unsigned Dim1, unsigned Brackets1> IndexedBareField<T,Dim,Brackets>& IndexedBareField< T, Dim, Brackets >::operator= (const IndexedBareField< X, Dim1, Brackets1 > & x) inline
Definition at line 240 of file IndexedBareField.h.
References assign(), and CTAssert.
operator=() [4/5]
template<class T, unsigned Dim, unsigned Brackets> IndexedBareField<T,Dim,Brackets>& IndexedBareField< T, Dim, Brackets >::operator= (const Index & x) inline
Definition at line 248 of file IndexedBareField.h.
References assign().
operator=() [5/5]
template<class T, unsigned Dim, unsigned Brackets> template<class B > IndexedBareField<T,Dim,Brackets>& IndexedBareField< T, Dim, Brackets >::operator= (const PETE_Expr< B > & x) inline
Definition at line 256 of file IndexedBareField.h.
References assign().
operator[]() [1/3]
template<class T, unsigned Dim, unsigned Brackets> IndexedBareField<T,Dim,Brackets+1> IndexedBareField< T, Dim, Brackets >::operator[] (const Index & idx) inline
Definition at line 207 of file IndexedBareField.h.
References IndexedBareField< T, Dim, Brackets >::A, CTAssert, Dim, and IndexedBareField< T, Dim, Brackets >::Indexes.
operator[]() [2/3]
template<class T, unsigned Dim, unsigned Brackets> IndexedBareField<T,Dim,Brackets+1> IndexedBareField< T, Dim, Brackets >::operator[] (int i) inline
Definition at line 213 of file IndexedBareField.h.
References IndexedBareField< T, Dim, Brackets >::A, CTAssert, Dim, and IndexedBareField< T, Dim, Brackets >::Indexes.
operator[]() [3/3]
template<class T, unsigned Dim, unsigned Brackets> IndexedBareField<T,Dim,Brackets+1> IndexedBareField< T, Dim, Brackets >::operator[] (const NDIndex< Dim > & ndidx) inline
Definition at line 219 of file IndexedBareField.h.
References IndexedBareField< T, Dim, Brackets >::A, CTAssert, Dim, and IndexedBareField< T, Dim, Brackets >::Indexes.
write()
template<class T , unsigned Dim, unsigned Brackets> void IndexedBareField< T, Dim, Brackets >::write (std::ostream & out)
Definition at line 50 of file IndexedBareField.hpp.
References assign(), Dim, and PInsist.
Referenced by operator<<().
Friends And Related Function Documentation
BareField< T, Dim >
template<class T, unsigned Dim, unsigned Brackets> friend class BareField< T, Dim > friend
Definition at line 198 of file IndexedBareField.h.
IndexedBareField< T, Dim, Brackets-1 >
template<class T, unsigned Dim, unsigned Brackets> friend class IndexedBareField< T, Dim, Brackets-1 > friend
Definition at line 197 of file IndexedBareField.h.
Member Data Documentation
A
template<class T, unsigned Dim, unsigned Brackets> BareField<T,Dim>& IndexedBareField< T, Dim, Brackets >::A protected
Definition at line 302 of file IndexedBareField.h.
Referenced by IndexedBareField< T, Dim, Brackets >::begin(), IndexedBareField< T, Dim, Brackets >::getBareField(), and IndexedBareField< T, Dim, Brackets >::operator[]().
Indexes
template<class T, unsigned Dim, unsigned Brackets> NDIndex<Brackets> IndexedBareField< T, Dim, Brackets >::Indexes protected
Definition at line 303 of file IndexedBareField.h.
Referenced by IndexedBareField< T, Dim, Brackets >::begin(), IndexedBareField< T, Dim, Brackets >::getDomain(), and IndexedBareField< T, Dim, Brackets >::operator[]().
The documentation for this class was generated from the following files:
ippl/src/Field/Assign.h
ippl/src/Field/IndexedBareField.h
ippl/src/Field/IndexedBareField.hpp