OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyLineNS Namespace Reference
PyOpal::PyLineNS Namespace Reference
Functions
BOOST_PYTHON_MODULE (line)
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyLineNS::BOOST_PYTHON_MODULE (line)
Definition at line 42 of file PyLine.cpp.
References PyOpal::PyOpalObjectNS::PyOpalObject< C >::addGetOpalElement(), PyOpal::PyLine_< C >::append(), PyOpal::PyLine_< C >::getElement(), PyOpal::PyLine_< C >::getLength(), PyOpal::PyLine_< C >::getName(), PyOpal::Globals::Initialise(), PyOpal::PyLine_< C >::make_class(), PyOpal::ExceptionTranslation::registerExceptions(), PyOpal::PyLine_< C >::registerObject(), PyOpal::PyLine_< C >::setElement(), and PyOpal::PyLine_< C >::setName().