OPAL (Object Oriented Parallel Accelerator Library): TBeamline< T > Class Template Reference
TBeamline< T > Class Template Reference
#include <TBeamline.h>
Public Member Functions
TBeamline ()
Default constructor.
TBeamline (const std::string &name)
Constructor with given name.
TBeamline (const TBeamline< T > &right)
virtual ~TBeamline ()
virtual void accept (BeamlineVisitor &) const
Apply BeamlineVisitor to this line.
virtual void iterate (BeamlineVisitor &, bool r2l) const
Apply visitor to all elements of the line.
virtual TBeamline< T > * clone () const
Make clone.
virtual TBeamline< T > * copyStructure ()
Make structure copy.
virtual void makeSharable ()
Set sharable flag.
virtual BeamlineGeometry & getGeometry ()
Get geometry.
virtual const BeamlineGeometry & getGeometry () const
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual ElementBase::ElementType getType () const
Get beamline type.
virtual void append (const T &)
Append a T object.
virtual void prepend (const T &)
Prepend a T object.
void setOrigin3D (const Vector_t &ori)
Vector_t getOrigin3D () const
void setInitialDirection (const Quaternion &rot)
Quaternion getInitialDirection () const
void setRelativeFlag (bool flag)
bool getRelativeFlag () const
Public Member Functions inherited from Beamline
Beamline (const std::string &name)
Constructor with given name.
Beamline ()
Beamline (const Beamline &)
virtual ~Beamline ()
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
bool isSharable () const
Test if the element can be shared.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Attributes
BeamlineGeometry itsGeometry
The beamline geometry.
Vector_t itsOrigin_m
Quaternion itsCoordTrafoTo_m
bool relativePositions_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Additional Inherited Members
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Detailed Description
template<class T>
class TBeamline< T >
Definition at line 33 of file TBeamline.h.
Constructor & Destructor Documentation
TBeamline() [1/3]
template<class T > TBeamline< T >::TBeamline ()
Default constructor.
Definition at line 159 of file TBeamline.h.
TBeamline() [2/3]
template<class T > TBeamline< T >::TBeamline (const std::string & name) explicit
Constructor with given name.
Definition at line 170 of file TBeamline.h.
TBeamline() [3/3]
template<class T > TBeamline< T >::TBeamline (const TBeamline< T > & right)
Definition at line 181 of file TBeamline.h.
~TBeamline()
template<class T > TBeamline< T >::~TBeamline () virtual
Definition at line 192 of file TBeamline.h.
Member Function Documentation
accept()
template<class T > void TBeamline< T >::accept (BeamlineVisitor & visitor) const virtual
Apply BeamlineVisitor to this line.
Implements ElementBase.
Definition at line 197 of file TBeamline.h.
References BeamlineVisitor::visitBeamline().
append()
template<class T > void TBeamline< T >::append (const T & obj) inline virtual
Append a T object.
Definition at line 415 of file TBeamline.h.
Referenced by TBeamline< T >::clone(), and TBeamline< T >::copyStructure().
clone()
template<class T > TBeamline< T > * TBeamline< T >::clone () const virtual
Make clone.
Implements ElementBase.
Definition at line 219 of file TBeamline.h.
References TBeamline< T >::append(), begin(), end(), TBeamline< T >::itsCoordTrafoTo_m, TBeamline< T >::itsOrigin_m, TBeamline< T >::relativePositions_m, and Attrib::Legacy::Distribution::T.
copyStructure()
template<class T > TBeamline< T > * TBeamline< T >::copyStructure () virtual
Make structure copy.
Reimplemented from ElementBase.
Definition at line 239 of file TBeamline.h.
References TBeamline< T >::append(), begin(), end(), TBeamline< T >::itsCoordTrafoTo_m, TBeamline< T >::itsOrigin_m, TBeamline< T >::relativePositions_m, and Attrib::Legacy::Distribution::T.
getArcLength()
template<class T > double TBeamline< T >::getArcLength () const virtual
Get arc length.
Reimplemented from ElementBase.
Definition at line 286 of file TBeamline.h.
References begin(), and end().
getElementLength()
template<class T > double TBeamline< T >::getElementLength () const virtual
Get design length.
Reimplemented from ElementBase.
Definition at line 299 of file TBeamline.h.
References begin(), and end().
getEntrance()
template<class T > double TBeamline< T >::getEntrance () const virtual
Get entrance position.
Reimplemented from ElementBase.
Definition at line 318 of file TBeamline.h.
getEntranceFrame()
template<class T > Euclid3D TBeamline< T >::getEntranceFrame () const virtual
Get transform.
Reimplemented from ElementBase.
Definition at line 397 of file TBeamline.h.
getExit()
template<class T > double TBeamline< T >::getExit () const virtual
Get exit position.
Reimplemented from ElementBase.
Definition at line 324 of file TBeamline.h.
getExitFrame()
template<class T > Euclid3D TBeamline< T >::getExitFrame () const virtual
Get transform.
Reimplemented from ElementBase.
Definition at line 403 of file TBeamline.h.
getGeometry() [1/2]
template<class T > BeamlineGeometry & TBeamline< T >::getGeometry () inline virtual
Get geometry.
Implements ElementBase.
Definition at line 274 of file TBeamline.h.
getGeometry() [2/2]
template<class T > const BeamlineGeometry & TBeamline< T >::getGeometry () const inline virtual
Get geometry.
Implements ElementBase.
Definition at line 280 of file TBeamline.h.
getInitialDirection()
template<class T > Quaternion TBeamline< T >::getInitialDirection () const inline virtual
Reimplemented from Beamline.
Definition at line 441 of file TBeamline.h.
Referenced by ParallelTTracker::visitBeamline(), and ThickTracker::visitBeamline().
getOrigin()
template<class T > double TBeamline< T >::getOrigin () const virtual
Get origin position.
Reimplemented from ElementBase.
Definition at line 312 of file TBeamline.h.
getOrigin3D()
template<class T > Vector_t TBeamline< T >::getOrigin3D () const inline virtual
Reimplemented from Beamline.
Definition at line 431 of file TBeamline.h.
Referenced by ParallelTTracker::visitBeamline(), and ThickTracker::visitBeamline().
getRelativeFlag()
template<class T > bool TBeamline< T >::getRelativeFlag () const inline virtual
Reimplemented from Beamline.
Definition at line 451 of file TBeamline.h.
Referenced by ParallelTTracker::visitBeamline(), and ThickTracker::visitBeamline().
getTotalTransform()
template<class T > Euclid3D TBeamline< T >::getTotalTransform () const virtual
Get transform.
Reimplemented from ElementBase.
Definition at line 378 of file TBeamline.h.
References begin(), Euclid3D::dotBy(), and end().
getTransform() [1/2]
template<class T > Euclid3D TBeamline< T >::getTransform (double fromS, double toS) const virtual
Get transform.
Reimplemented from ElementBase.
Definition at line 330 of file TBeamline.h.
References begin(), end(), ElementBase::getArcLength(), ElementBase::getTransform(), max(), and min().
getTransform() [2/2]
template<class T > Euclid3D TBeamline< T >::getTransform (double s) const virtual
Get transform.
Reimplemented from ElementBase.
Definition at line 391 of file TBeamline.h.
getType()
template<class T > ElementBase::ElementType TBeamline< T >::getType () const inline virtual
Get beamline type.
Implements ElementBase.
Definition at line 409 of file TBeamline.h.
iterate()
template<class T > void TBeamline< T >::iterate (BeamlineVisitor & visitor, bool r2l) const virtual
Apply visitor to all elements of the line.
Implements Beamline.
Definition at line 203 of file TBeamline.h.
References begin(), and end().
Referenced by ParallelCyclotronTracker::visitBeamline(), ParallelTTracker::visitBeamline(), and ThickTracker::visitBeamline().
makeSharable()
template<class T > void TBeamline< T >::makeSharable () inline virtual
Set sharable flag.
Reimplemented from ElementBase.
Definition at line 263 of file TBeamline.h.
References begin(), and end().
prepend()
template<class T > void TBeamline< T >::prepend (const T & obj) inline virtual
Prepend a T object.
Definition at line 421 of file TBeamline.h.
setInitialDirection()
template<class T > void TBeamline< T >::setInitialDirection (const Quaternion & rot) inline
Definition at line 436 of file TBeamline.h.
setOrigin3D()
template<class T > void TBeamline< T >::setOrigin3D (const Vector_t & ori) inline
Definition at line 426 of file TBeamline.h.
setRelativeFlag()
template<class T > void TBeamline< T >::setRelativeFlag (bool flag) inline
Definition at line 446 of file TBeamline.h.
Member Data Documentation
itsCoordTrafoTo_m
template<class T> Quaternion TBeamline< T >::itsCoordTrafoTo_m protected
Definition at line 150 of file TBeamline.h.
Referenced by TBeamline< T >::clone(), and TBeamline< T >::copyStructure().
itsGeometry
template<class T> BeamlineGeometry TBeamline< T >::itsGeometry protected
The beamline geometry.
Definition at line 147 of file TBeamline.h.
itsOrigin_m
template<class T> Vector_t TBeamline< T >::itsOrigin_m protected
Definition at line 149 of file TBeamline.h.
Referenced by TBeamline< T >::clone(), and TBeamline< T >::copyStructure().
relativePositions_m
template<class T> bool TBeamline< T >::relativePositions_m protected
Definition at line 151 of file TBeamline.h.
Referenced by TBeamline< T >::clone(), and TBeamline< T >::copyStructure().
The documentation for this class was generated from the following file:
src/Classic/Beamlines/TBeamline.h