OPAL (Object Oriented Parallel Accelerator Library): IntCICImpl< 2U > Class Template Reference
IntCICImpl< 2U > Class Template Reference
#include <IntCIC.h>
Public Member Functions
IntCICImpl ()
~IntCICImpl ()
Public Member Functions inherited from Interpolator
Interpolator ()
~Interpolator ()
Static Public Member Functions
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 2U, M, C > &f, const Vektor< PT, 2U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 2U, M, C > &f, const Vektor< PT, 2U > &ppos, const M &mesh, NDIndex< 2U > &ngp, int lgpoff[2U], Vektor< PT, 2U > &dpos)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 2U, M, C > &f, const NDIndex< 2U > &ngp, const int lgpoff[2U], const Vektor< PT, 2U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 2U, M, C > &f, const Vektor< PT, 2U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 2U, M, C > &f, const Vektor< PT, 2U > &ppos, const M &mesh, NDIndex< 2U > &ngp, int lgpoff[2U], Vektor< PT, 2U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 2U, M, C > &f, const NDIndex< 2U > &ngp, const int lgpoff[2U], const Vektor< PT, 2U > &dpos)
template<class FT , class M , class PT >
static void scatter (const Vektor< FT, 2U > &pdata, Field< Vektor< FT, 2U >, 2U, M, Edge > &f, const Vektor< PT, 2U > &ppos, const M &mesh)
template<class FT , class M , class PT >
static void scatter (const FT &, Field< FT, 2U, M, Edge > &, const Vektor< PT, 2U > &, const M &)
template<class FT , class M , class PT >
static void scatter (const FT &, Field< FT, 2U, M, Edge > &, const Vektor< PT, 2U > &, const M &, NDIndex< 2U > &, int [2U], Vektor< PT, 2U > &)
template<class FT , class M , class PT >
static void scatter (const FT &, Field< FT, 2U, M, Edge > &, const NDIndex< 2U > &, const int [2U], const Vektor< PT, 2U > &)
template<class FT , class M , class PT >
static void gather (Vektor< FT, 2U > &pdata, const Field< Vektor< FT, 2U >, 2U, M, Edge > &f, const Vektor< PT, 2U > &ppos, const M &mesh)
template<class FT , class M , class PT >
static void gather (FT &, const Field< FT, 2U, M, Edge > &, const Vektor< PT, 2U > &, const M &)
template<class FT , class M , class PT >
static void gather (FT &, const Field< FT, 2U, M, Edge > &, const Vektor< PT, 2U > &, const M &, NDIndex< 2U > &, int [2U], Vektor< PT, 2U > &)
template<class FT , class M , class PT >
static void gather (FT &, const Field< FT, 2U, M, Edge > &, const NDIndex< 2U > &, const int [2U], const Vektor< PT, 2U > &)
Additional Inherited Members
Static Protected Member Functions inherited from Interpolator
template<class T , unsigned Dim>
static CompressedBrickIterator< T, Dim > getFieldIter (const BareField< T, Dim > &f, const NDIndex< Dim > &pt)
Detailed Description
template<>
class IntCICImpl< 2U >
Definition at line 453 of file IntCIC.h.
Constructor & Destructor Documentation
IntCICImpl()
IntCICImpl< 2U >::IntCICImpl () inline
Definition at line 457 of file IntCIC.h.
~IntCICImpl()
IntCICImpl< 2U >::~IntCICImpl () inline
Definition at line 458 of file IntCIC.h.
Member Function Documentation
gather() [1/7]
template<class FT , class M , class C , class PT > static void IntCICImpl< 2U >::gather (FT & pdata, const Field< FT, 2U, M, C > & f, const Vektor< PT, 2U > & ppos, const M & mesh) inline static
Definition at line 570 of file IntCIC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
gather() [2/7]
template<class FT , class M , class C , class PT > static void IntCICImpl< 2U >::gather (FT & pdata, const Field< FT, 2U, M, C > & f, const Vektor< PT, 2U > & ppos, const M & mesh, NDIndex< 2U > & ngp, int lgpoff[2U], Vektor< PT, 2U > & dpos) inline static
Definition at line 614 of file IntCIC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
gather() [3/7]
template<class FT , class M , class C , class PT > static void IntCICImpl< 2U >::gather (FT & pdata, const Field< FT, 2U, M, C > & f, const NDIndex< 2U > & ngp, const int lgpoff[2U], const Vektor< PT, 2U > & dpos) inline static
Definition at line 656 of file IntCIC.h.
References Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
gather() [4/7]
template<class FT , class M , class PT > static void IntCICImpl< 2U >::gather (Vektor< FT, 2U > & pdata, const Field< Vektor< FT, 2U >, 2U, M, Edge > & f, const Vektor< PT, 2U > & ppos, const M & mesh) inline static
Definition at line 740 of file IntCIC.h.
References FindDelta(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
gather() [5/7]
template<class FT , class M , class PT > static void IntCICImpl< 2U >::gather (FT & , const Field< FT, 2U, M, Edge > & , const Vektor< PT, 2U > & , const M &) inline static
Definition at line 776 of file IntCIC.h.
References endl(), and ERRORMSG.
gather() [6/7]
template<class FT , class M , class PT > static void IntCICImpl< 2U >::gather (FT & , const Field< FT, 2U, M, Edge > & , const Vektor< PT, 2U > & , const M & , NDIndex< 2U > & , int [2U], Vektor< PT, 2U > &) inline static
Definition at line 786 of file IntCIC.h.
References endl(), and ERRORMSG.
gather() [7/7]
template<class FT , class M , class PT > static void IntCICImpl< 2U >::gather (FT & , const Field< FT, 2U, M, Edge > & , const NDIndex< 2U > & , const int [2U], const Vektor< PT, 2U > &) inline static
Definition at line 796 of file IntCIC.h.
References endl(), and ERRORMSG.
scatter() [1/7]
template<class FT , class M , class C , class PT > static void IntCICImpl< 2U >::scatter (const FT & pdata, Field< FT, 2U, M, C > & f, const Vektor< PT, 2U > & ppos, const M & mesh) inline static
Definition at line 465 of file IntCIC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
scatter() [2/7]
template<class FT , class M , class C , class PT > static void IntCICImpl< 2U >::scatter (const FT & pdata, Field< FT, 2U, M, C > & f, const Vektor< PT, 2U > & ppos, const M & mesh, NDIndex< 2U > & ngp, int lgpoff[2U], Vektor< PT, 2U > & dpos) inline static
Definition at line 509 of file IntCIC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
scatter() [3/7]
template<class FT , class M , class C , class PT > static void IntCICImpl< 2U >::scatter (const FT & pdata, Field< FT, 2U, M, C > & f, const NDIndex< 2U > & ngp, const int lgpoff[2U], const Vektor< PT, 2U > & dpos) inline static
Definition at line 551 of file IntCIC.h.
References Interpolator::getFieldIter(), BrickIterator< T, Dim >::moveBy(), and BrickIterator< T, Dim >::offset().
scatter() [4/7]
template<class FT , class M , class PT > static void IntCICImpl< 2U >::scatter (const Vektor< FT, 2U > & pdata, Field< Vektor< FT, 2U >, 2U, M, Edge > & f, const Vektor< PT, 2U > & ppos, const M & mesh) inline static
Definition at line 675 of file IntCIC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
scatter() [5/7]
template<class FT , class M , class PT > static void IntCICImpl< 2U >::scatter (const FT & , Field< FT, 2U, M, Edge > & , const Vektor< PT, 2U > & , const M &) inline static
Definition at line 712 of file IntCIC.h.
References endl(), and ERRORMSG.
scatter() [6/7]
template<class FT , class M , class PT > static void IntCICImpl< 2U >::scatter (const FT & , Field< FT, 2U, M, Edge > & , const Vektor< PT, 2U > & , const M & , NDIndex< 2U > & , int [2U], Vektor< PT, 2U > &) inline static
Definition at line 721 of file IntCIC.h.
References endl(), and ERRORMSG.
scatter() [7/7]
template<class FT , class M , class PT > static void IntCICImpl< 2U >::scatter (const FT & , Field< FT, 2U, M, Edge > & , const NDIndex< 2U > & , const int [2U], const Vektor< PT, 2U > &) inline static
Definition at line 730 of file IntCIC.h.
References endl(), and ERRORMSG.
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/IntCIC.h