OPAL (Object Oriented Parallel Accelerator Library): Attributes::Real Class Reference
Attributes::Real Class Reference
Parser for an attribute of type real.
#include <Real.h>
Public Member Functions
Real (const std::string &name, const std::string &help)
Constructor.
virtual ~Real ()
virtual const std::string & getType () const
Return attribute type string `‘real’'.
virtual void parse (Attribute &, Statement &, bool) const
Parse the attribute.
Public Member Functions inherited from AttributeHandler
AttributeHandler (const std::string &name, const std::string &help, AttributeBase *def)
Constructor.
virtual ~AttributeHandler ()
virtual AttributeHandler * clone () const
Make clone.
virtual AttributeBase * getDefault () const
Return default value.
virtual const std::string & getHelp () const
Return help string.
virtual const std::string & getName () const
Return attribute name.
virtual void parseComponent (Attribute &a, Statement &s, bool eval, int i) const
Parse component value.
bool isDeferred () const
Return defer flag.
void setDeferred (bool)
Set or reset defer flag.
bool isReadOnly () const
Return read-only flag.
void setReadOnly (bool)
Set or reset read-only flag.
void setPredefinedValues (const std::set< std::string > &, const std::string &)
Add predefined strings values to the help.
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
Real ()
Real (const Real &)
void operator= (const Real &)
Additional Inherited Members
Public Types inherited from AttributeHandler
enum OwnerType {
ELEMENT, COMMAND, SUB_COMMAND, STATEMENT,
NONE
}
Static Public Member Functions inherited from AttributeHandler
static std::multimap< OwnerType, std::string > getOwner (const std::string &att)
static void addAttributeOwner (const std::string &owner, const OwnerType &type, const std::string &name)
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from AttributeHandler
const std::string itsName
Attribute name.
const std::string itsHelp
Help text.
Pointer< AttributeBase > itsDefault
Default value.
bool is_deferred
Defer flag.
bool is_readonly
Read-only flag.
Detailed Description
Parser for an attribute of type real.
Definition at line 31 of file Real.h.
Constructor & Destructor Documentation
Real() [1/3]
Attributes::Real::Real (const std::string & name, const std::string & help)
Constructor.
Definition at line 40 of file Real.cpp.
~Real()
Attributes::Real::~Real () virtual
Definition at line 45 of file Real.cpp.
Real() [2/3]
Attributes::Real::Real () private
Real() [3/3]
Attributes::Real::Real (const Real &) private
Member Function Documentation
getType()
const std::string & Attributes::Real::getType () const virtual
Return attribute type string `‘real’'.
Implements AttributeHandler.
Definition at line 49 of file Real.cpp.
operator=()
void Attributes::Real::operator= (const Real &) private
parse()
void Attributes::Real::parse (Attribute & attr, Statement & statement, bool eval) const virtual
Parse the attribute.
Implements AttributeHandler.
Definition at line 55 of file Real.cpp.
References AttributeHandler::isDeferred(), Expressions::parseReal(), and Attribute::set().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Attributes/Real.h
/psi/home/gsell/data/src/OPAL/src/src/Attributes/Real.cpp