OPAL (Object Oriented Parallel Accelerator Library): Vacuum Class Reference
Vacuum Class Reference
#include <Vacuum.h>
Public Member Functions
Vacuum (const std::string &name)
Constructor with given name.
Vacuum ()
Vacuum (const Vacuum &rhs)
virtual ~Vacuum ()
virtual void accept (BeamlineVisitor &) const
Apply visitor to Vacuum.
virtual bool checkVacuum (PartBunchBase< double, 3 > *bunch, Cyclotron *cycl)
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField)
virtual void initialise (PartBunchBase< double, 3 > *bunch, const double &scaleFactor)
virtual void finalise ()
virtual bool bends () const
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual ElementBase::ElementType getType () const
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const
std::string getVacuumShape ()
int checkPoint (const double &x, const double &y, const double &z)
double checkPressure (const double &x, const double &y)
void setPressure (double pressure)
double getPressure () const
void setTemperature (double temperature)
double getTemperature () const
void setPressureMapFN (std::string pmapfn)
virtual std::string getPressureMapFN () const
void setPScale (double ps)
virtual double getPScale () const
void setResidualGas (std::string gas)
ResidualGas getResidualGas () const
std::string getResidualGasName ()
void setStop (bool stopflag)
virtual bool getStop () const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
virtual EMField & getField ()=0
Return field.
virtual const EMField & getField () const =0
Return field.
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B)
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual bool Online ()
virtual void setComponentType (std::string)
virtual std::string getComponentType () const
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Member Functions
void initR (double rmin, double dr, int nrad)
void getPressureFromFile (const double &scaleFactor)
int idx (int irad, int ktet)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes
PFieldData PField
PPositions PP
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Private Attributes
ParticleMatterInteractionHandler * parmatint_m
mm
ResidualGas gas_m
parameters for Vacuum
double pressure_m
std::string pmapfn_m
mbar
double pscale_m
stores the filename of the pressure map
double temperature_m
a scale factor for the P-field
bool stop_m
K.
double minr_m
Flag if particles should be stripped or stopped.
double maxr_m
mm
double minz_m
mm
double maxz_m
mm
Additional Inherited Members
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 67 of file Vacuum.h.
Constructor & Destructor Documentation
Vacuum() [1/3]
Vacuum::Vacuum (const std::string & name) explicit
Constructor with given name.
Definition at line 68 of file Vacuum.cpp.
References NOGAS.
Vacuum() [2/3]
Vacuum::Vacuum ()
Definition at line 49 of file Vacuum.cpp.
Vacuum() [3/3]
Vacuum::Vacuum (const Vacuum & rhs)
Definition at line 53 of file Vacuum.cpp.
~Vacuum()
Vacuum::~Vacuum () virtual
Definition at line 83 of file Vacuum.cpp.
References goOffline(), and Component::online_m.
Member Function Documentation
accept()
void Vacuum::accept (BeamlineVisitor & visitor) const virtual
Apply visitor to Vacuum.
Implements ElementBase.
Definition at line 89 of file Vacuum.cpp.
References BeamlineVisitor::visitVacuum().
bends()
bool Vacuum::bends () const virtual
Implements Component.
Definition at line 247 of file Vacuum.cpp.
checkPoint()
int Vacuum::checkPoint (const double & x, const double & y, const double & z)
Definition at line 261 of file Vacuum.cpp.
References maxr_m, maxz_m, minr_m, and sqrt().
Referenced by checkVacuum().
checkPressure()
double Vacuum::checkPressure (const double & x, const double & y)
Definition at line 272 of file Vacuum.cpp.
References atan(), PPositions::delr, PPositions::dtet, endl(), ElementBase::getName(), getPressure(), gmsg, idx(), level4(), PFieldData::nrad, PFieldData::ntetS, PField, PFieldData::pfld, Physics::pi, pmapfn_m, PP, matheval::detail::math::rad(), Physics::rad2deg, PPositions::rmin, sqrt(), and Physics::two_pi.
checkVacuum()
bool Vacuum::checkVacuum (PartBunchBase< double, 3 > * bunch, Cyclotron * cycl) virtual
Definition at line 176 of file Vacuum.cpp.
References ParticleMatterInteractionHandler::apply(), PartBunchBase< T, Dim >::Bin, checkPoint(), euclidean_norm(), PartBunchBase< T, Dim >::get_bounds(), PartBunchBase< T, Dim >::getLocalNum(), Cyclotron::getMaxR(), Cyclotron::getMaxZ(), Cyclotron::getMinR(), Cyclotron::getMinZ(), maxr_m, maxz_m, minr_m, minz_m, parmatint_m, PartBunchBase< T, Dim >::R, and reduce().
Referenced by ParallelCyclotronTracker::applyPluginElements().
finalise()
void Vacuum::finalise () virtual
Implements Component.
Definition at line 234 of file Vacuum.cpp.
References endl(), gmsg, goOffline(), and Component::online_m.
getDimensions()
void Vacuum::getDimensions (double & zBegin, double & zEnd) const virtual
Implements Component.
Definition at line 251 of file Vacuum.cpp.
getPressure()
double Vacuum::getPressure () const
Definition at line 97 of file Vacuum.cpp.
References pressure_m.
Referenced by checkPressure(), and ParallelCyclotronTracker::visitVacuum().
getPressureFromFile()
void Vacuum::getPressureFromFile (const double & scaleFactor) protected
Definition at line 354 of file Vacuum.cpp.
References CHECK_VAC_FSCANF_EOF, PPositions::delr, PPositions::dtet, endl(), gmsg, idx(), PFieldData::nrad, PFieldData::ntet, PFieldData::ntetS, PFieldData::ntot, PPositions::Pfact, PField, PFieldData::pfld, pmapfn_m, PP, PPositions::rmin, and PPositions::tetmin.
Referenced by initialise().
getPressureMapFN()
std::string Vacuum::getPressureMapFN () const virtual
Definition at line 123 of file Vacuum.cpp.
References pmapfn_m.
Referenced by ParallelCyclotronTracker::visitVacuum().
getPScale()
double Vacuum::getPScale () const virtual
Definition at line 131 of file Vacuum.cpp.
References pscale_m.
Referenced by ParallelCyclotronTracker::visitVacuum().
getResidualGas()
ResidualGas Vacuum::getResidualGas () const
Definition at line 148 of file Vacuum.cpp.
References gas_m.
Referenced by BeamStrippingPhysics::computeCrossSection(), and BeamStrippingPhysics::getSecondaryParticles().
getResidualGasName()
std::string Vacuum::getResidualGasName ()
Definition at line 152 of file Vacuum.cpp.
References AIR, gas_m, and H2.
Referenced by ParallelCyclotronTracker::visitVacuum().
getStop()
bool Vacuum::getStop () const virtual
Definition at line 171 of file Vacuum.cpp.
References stop_m.
Referenced by BeamStrippingPhysics::doPhysics(), and ParallelCyclotronTracker::visitVacuum().
getTemperature()
double Vacuum::getTemperature () const
Definition at line 110 of file Vacuum.cpp.
References temperature_m.
Referenced by BeamStrippingPhysics::computeCrossSection(), and ParallelCyclotronTracker::visitVacuum().
getType()
ElementBase::ElementType Vacuum::getType () const virtual
Get element type std::string.
Reimplemented from Component.
Definition at line 253 of file Vacuum.cpp.
References ElementBase::VACUUM.
getVacuumShape()
std::string Vacuum::getVacuumShape ()
Definition at line 257 of file Vacuum.cpp.
goOffline()
void Vacuum::goOffline () virtual
Reimplemented from Component.
Definition at line 243 of file Vacuum.cpp.
References Component::online_m.
Referenced by finalise(), and ~Vacuum().
goOnline()
void Vacuum::goOnline (const double & kineticEnergy) virtual
Reimplemented from Component.
Definition at line 240 of file Vacuum.cpp.
Referenced by initialise().
idx()
int Vacuum::idx (int irad, int ktet) inline protected
Definition at line 132 of file Vacuum.h.
References PFieldData::ntetS, and PField.
Referenced by checkPressure(), and getPressureFromFile().
initialise() [1/2]
void Vacuum::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) virtual
Implements Component.
Definition at line 206 of file Vacuum.cpp.
References ElementBase::getElementLength(), and pscale_m.
Referenced by ParallelCyclotronTracker::visitVacuum().
initialise() [2/2]
void Vacuum::initialise (PartBunchBase< double, 3 > * bunch, const double & scaleFactor) virtual
Definition at line 211 of file Vacuum.cpp.
References PartBunchBase< T, Dim >::Bin, PPositions::delr, PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getM(), ElementBase::getParticleMatterInteraction(), getPressureFromFile(), PartBunchBase< T, Dim >::getQ(), goOnline(), initR(), PartBunchBase< T, Dim >::M, PFieldData::nrad, parmatint_m, PField, pmapfn_m, PP, PartBunchBase< T, Dim >::Q, Physics::q_e, Component::RefPartBunch_m, PPositions::rmin, and PartBunchBase< T, Dim >::weHaveBins().
initR()
void Vacuum::initR (double rmin, double dr, int nrad) protected
Definition at line 345 of file Vacuum.cpp.
References PPositions::delr, PP, and PPositions::rarr.
Referenced by initialise().
setPressure()
void Vacuum::setPressure (double pressure)
Definition at line 93 of file Vacuum.cpp.
References pressure_m.
Referenced by OpalVacuum::update().
setPressureMapFN()
void Vacuum::setPressureMapFN (std::string pmapfn)
Definition at line 119 of file Vacuum.cpp.
References pmapfn_m.
Referenced by OpalVacuum::update().
setPScale()
void Vacuum::setPScale (double ps)
Definition at line 127 of file Vacuum.cpp.
References pscale_m.
Referenced by OpalVacuum::update().
setResidualGas()
void Vacuum::setResidualGas (std::string gas)
Definition at line 140 of file Vacuum.cpp.
References AIR, gas_m, and H2.
Referenced by OpalVacuum::update().
setStop()
void Vacuum::setStop (bool stopflag)
Definition at line 167 of file Vacuum.cpp.
References stop_m.
Referenced by OpalVacuum::update().
setTemperature()
void Vacuum::setTemperature (double temperature)
Definition at line 106 of file Vacuum.cpp.
References temperature_m.
Referenced by OpalVacuum::update().
Member Data Documentation
gas_m
ResidualGas Vacuum::gas_m private
parameters for Vacuum
Definition at line 137 of file Vacuum.h.
Referenced by getResidualGas(), getResidualGasName(), and setResidualGas().
maxr_m
double Vacuum::maxr_m private
mm
Definition at line 147 of file Vacuum.h.
Referenced by checkPoint(), and checkVacuum().
maxz_m
double Vacuum::maxz_m private
mm
Definition at line 149 of file Vacuum.h.
Referenced by checkPoint(), and checkVacuum().
minr_m
double Vacuum::minr_m private
Flag if particles should be stripped or stopped.
size limits took from cyclotron
Definition at line 146 of file Vacuum.h.
Referenced by checkPoint(), and checkVacuum().
minz_m
double Vacuum::minz_m private
mm
Definition at line 148 of file Vacuum.h.
Referenced by checkVacuum().
parmatint_m
ParticleMatterInteractionHandler* Vacuum::parmatint_m private
mm
Definition at line 152 of file Vacuum.h.
Referenced by checkVacuum(), and initialise().
PField
PFieldData Vacuum::PField protected
Definition at line 156 of file Vacuum.h.
Referenced by checkPressure(), getPressureFromFile(), idx(), and initialise().
pmapfn_m
std::string Vacuum::pmapfn_m private
mbar
Definition at line 139 of file Vacuum.h.
Referenced by checkPressure(), getPressureFromFile(), getPressureMapFN(), initialise(), and setPressureMapFN().
PP
PPositions Vacuum::PP protected
Definition at line 159 of file Vacuum.h.
Referenced by checkPressure(), getPressureFromFile(), initialise(), and initR().
pressure_m
double Vacuum::pressure_m private
Definition at line 138 of file Vacuum.h.
Referenced by getPressure(), and setPressure().
pscale_m
double Vacuum::pscale_m private
stores the filename of the pressure map
Definition at line 140 of file Vacuum.h.
Referenced by getPScale(), initialise(), and setPScale().
stop_m
bool Vacuum::stop_m private
K.
Definition at line 142 of file Vacuum.h.
Referenced by getStop(), and setStop().
temperature_m
double Vacuum::temperature_m private
a scale factor for the P-field
Definition at line 141 of file Vacuum.h.
Referenced by getTemperature(), and setTemperature().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/Vacuum.h
src/Classic/AbsBeamline/Vacuum.cpp