OPAL (Object Oriented Parallel Accelerator Library): PoissonSolver Class Reference
PoissonSolver Class Reference abstract
#include <PoissonSolver.h>
Public Member Functions
virtual void computePotential (Field_t &rho, Vector_t hr)=0
virtual void solve (AmrScalarFieldContainer_t &, AmrScalarFieldContainer_t &, AmrVectorFieldContainer_t &, unsigned short, unsigned short, bool=true)
virtual void hasToRegrid ()
virtual void computePotential (Field_t &rho, Vector_t hr, double zshift)=0
virtual double getXRangeMin (unsigned short level=0)=0
virtual double getXRangeMax (unsigned short level=0)=0
virtual double getYRangeMin (unsigned short level=0)=0
virtual double getYRangeMax (unsigned short level=0)=0
virtual double getZRangeMin (unsigned short level=0)=0
virtual double getZRangeMax (unsigned short level=0)=0
virtual void test (PartBunchBase< double, 3 > *bunch)=0
virtual ~PoissonSolver ()
virtual void resizeMesh (Vector_t &, Vector_t &, const Vector_t &, const Vector_t &, double)
virtual double getinteractionRadius () const
virtual void calculatePairForces (PartBunchBase< double, 3 > *, double)
Protected Types
typedef Field< int, 3, Mesh_t, Center_t > IField_t
typedef Field< std::complex< double >, 3, Mesh_t, Center_t > CxField_t
Detailed Description
Definition at line 16 of file PoissonSolver.h.
Member Typedef Documentation
CxField_t
typedef Field<std::complex<double>, 3, Mesh_t, Center_t> PoissonSolver::CxField_t protected
Definition at line 20 of file PoissonSolver.h.
IField_t
typedef Field<int, 3, Mesh_t, Center_t> PoissonSolver::IField_t protected
Definition at line 19 of file PoissonSolver.h.
Constructor & Destructor Documentation
~PoissonSolver()
virtual PoissonSolver::~PoissonSolver () inline virtual
Definition at line 66 of file PoissonSolver.h.
Member Function Documentation
calculatePairForces()
virtual void PoissonSolver::calculatePairForces (PartBunchBase< double, 3 > * , double) inline virtual
Reimplemented in P3MPoissonSolver.
Definition at line 74 of file PoissonSolver.h.
Referenced by PartBunch::computeSelfFields().
computePotential() [1/2]
virtual void PoissonSolver::computePotential (Field_t & rho, Vector_t hr) pure virtual
Implemented in MGPoissonSolver, P3MPoissonSolver, FFTPoissonSolver, FFTBoxPoissonSolver, AmrPoissonSolver< AmrObject >, and AmrPoissonSolver< AmrBoxLib >.
Referenced by PartBunch::computeSelfFields(), and PartBunch::computeSelfFields_cycl().
computePotential() [2/2]
virtual void PoissonSolver::computePotential (Field_t & rho, Vector_t hr, double zshift) pure virtual
Implemented in MGPoissonSolver, P3MPoissonSolver, FFTPoissonSolver, AmrPoissonSolver< AmrObject >, AmrPoissonSolver< AmrBoxLib >, and FFTBoxPoissonSolver.
getinteractionRadius()
virtual double PoissonSolver::getinteractionRadius () const inline virtual
Reimplemented in P3MPoissonSolver.
Definition at line 72 of file PoissonSolver.h.
Referenced by PartBunchBase< double, 3 >::boundp().
getXRangeMax()
virtual double PoissonSolver::getXRangeMax (unsigned short level = 0) pure virtual
Implemented in AmrMultiGrid, MGPoissonSolver, P3MPoissonSolver, FMGPoissonSolver, FFTPoissonSolver, MLPoissonSolver, and FFTBoxPoissonSolver.
Referenced by PartBunch::resizeMesh().
getXRangeMin()
virtual double PoissonSolver::getXRangeMin (unsigned short level = 0) pure virtual
Implemented in AmrMultiGrid, MGPoissonSolver, P3MPoissonSolver, FMGPoissonSolver, FFTPoissonSolver, MLPoissonSolver, and FFTBoxPoissonSolver.
Referenced by PartBunch::resizeMesh().
getYRangeMax()
virtual double PoissonSolver::getYRangeMax (unsigned short level = 0) pure virtual
Implemented in AmrMultiGrid, MGPoissonSolver, P3MPoissonSolver, FMGPoissonSolver, FFTPoissonSolver, MLPoissonSolver, and FFTBoxPoissonSolver.
Referenced by PartBunch::resizeMesh().
getYRangeMin()
virtual double PoissonSolver::getYRangeMin (unsigned short level = 0) pure virtual
Implemented in AmrMultiGrid, MGPoissonSolver, P3MPoissonSolver, FMGPoissonSolver, FFTPoissonSolver, MLPoissonSolver, and FFTBoxPoissonSolver.
Referenced by PartBunch::resizeMesh().
getZRangeMax()
virtual double PoissonSolver::getZRangeMax (unsigned short level = 0) pure virtual
Implemented in AmrMultiGrid, MGPoissonSolver, P3MPoissonSolver, FMGPoissonSolver, FFTPoissonSolver, MLPoissonSolver, and FFTBoxPoissonSolver.
getZRangeMin()
virtual double PoissonSolver::getZRangeMin (unsigned short level = 0) pure virtual
Implemented in AmrMultiGrid, MGPoissonSolver, P3MPoissonSolver, FMGPoissonSolver, FFTPoissonSolver, MLPoissonSolver, and FFTBoxPoissonSolver.
hasToRegrid()
virtual void PoissonSolver::hasToRegrid () inline virtual
Tell solver to regrid
Reimplemented in AmrPoissonSolver< AmrObject >, and AmrPoissonSolver< AmrBoxLib >.
Definition at line 52 of file PoissonSolver.h.
Referenced by AmrBoxLib::postRegrid_m().
resizeMesh()
virtual void PoissonSolver::resizeMesh (Vector_t & , Vector_t & , const Vector_t & , const Vector_t & , double) inline virtual
Reimplemented in MGPoissonSolver.
Definition at line 68 of file PoissonSolver.h.
Referenced by PartBunch::resizeMesh().
solve()
virtual void PoissonSolver::solve (AmrScalarFieldContainer_t & , AmrScalarFieldContainer_t & , AmrVectorFieldContainer_t & , unsigned short , unsigned short , bool = true) inline virtual
AMR solver calls
Parameters
rho right-hand side charge density on grid [C / m]
phi electrostatic potential (unknown) [V]
efield electric field [V / m]
baseLevel for solve
finestLevel for solve
prevAsGuess use of previous solution as initial guess
Reimplemented in AmrMultiGrid, FMGPoissonSolver, and MLPoissonSolver.
Definition at line 39 of file PoissonSolver.h.
Referenced by AmrBoxLib::computeSelfFields_cycl(), and AmrBoxLib::solvePoisson_m().
test()
virtual void PoissonSolver::test (PartBunchBase< double, 3 > * bunch) pure virtual
Implemented in MGPoissonSolver, P3MPoissonSolver, FFTPoissonSolver, FFTBoxPoissonSolver, AmrPoissonSolver< AmrObject >, and AmrPoissonSolver< AmrBoxLib >.
The documentation for this class was generated from the following file:
src/Solvers/PoissonSolver.h