OPAL (Object Oriented Parallel Accelerator Library): SubFieldIterBase< T, Dim, S, ExprDim > Class Template Reference
SubFieldIterBase< T, Dim, S, ExprDim > Class Template Reference
#include <SubFieldIter.h>
Public Types
enum { ExprDim_u = ExprDim }
Public Member Functions
SubFieldIterBase (const BareField< T, Dim > &df, const typename BareField< T, Dim >::iterator_if &ldf, const S &s, unsigned int B)
SubFieldIterBase ()
~SubFieldIterBase ()
BareField< T, Dim > & getBareField ()
const BareField< T, Dim > & getBareField () const
BareField< T, Dim >::iterator_if getLFieldIter () const
S & getDomain ()
const S & getDomain () const
bool checkBrackets () const
unsigned int getBrackets () const
BareField< T, Dim >::iterator_if nextLField ()
LField< T, Dim > * getLField ()
const LField< T, Dim > * getLField () const
void setLField (LField< T, Dim > *p)
void setLFieldData (LField< T, Dim > *p, NDIndex< Dim > &)
void FillGCIfNecessary () const
Private Attributes
BareField< T, Dim > * MyBareField
S * MyDomain
LField< T, Dim > * LFPtr
BareField< T, Dim >::iterator_if CurrentLField
unsigned int MyBrackets
Detailed Description
template<class T, unsigned int Dim, class S, unsigned int ExprDim>
class SubFieldIterBase< T, Dim, S, ExprDim >
Definition at line 122 of file SubFieldIter.h.
Member Enumeration Documentation
anonymous enum
template<class T, unsigned int Dim, class S, unsigned int ExprDim> anonymous enum
Enumerator
ExprDim_u
Definition at line 127 of file SubFieldIter.h.
Constructor & Destructor Documentation
SubFieldIterBase() [1/2]
template<class T, unsigned int Dim, class S, unsigned int ExprDim> SubFieldIterBase< T, Dim, S, ExprDim >::SubFieldIterBase (const BareField< T, Dim > & df, const typename BareField< T, Dim >::iterator_if & ldf, const S & s, unsigned int B) inline
Definition at line 130 of file SubFieldIter.h.
SubFieldIterBase() [2/2]
template<class T, unsigned int Dim, class S, unsigned int ExprDim> SubFieldIterBase< T, Dim, S, ExprDim >::SubFieldIterBase () inline
Definition at line 146 of file SubFieldIter.h.
~SubFieldIterBase()
template<class T, unsigned int Dim, class S, unsigned int ExprDim> SubFieldIterBase< T, Dim, S, ExprDim >::~SubFieldIterBase () inline
Definition at line 149 of file SubFieldIter.h.
Member Function Documentation
checkBrackets()
template<class T, unsigned int Dim, class S, unsigned int ExprDim> bool SubFieldIterBase< T, Dim, S, ExprDim >::checkBrackets () const inline
Definition at line 166 of file SubFieldIter.h.
FillGCIfNecessary()
template<class T, unsigned int Dim, class S, unsigned int ExprDim> void SubFieldIterBase< T, Dim, S, ExprDim >::FillGCIfNecessary () const inline
Definition at line 219 of file SubFieldIter.h.
getBareField() [1/2]
template<class T, unsigned int Dim, class S, unsigned int ExprDim> BareField<T,Dim>& SubFieldIterBase< T, Dim, S, ExprDim >::getBareField () inline
Definition at line 153 of file SubFieldIter.h.
Referenced by SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::FillGCIfNecessary(), SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::nextLField(), and SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::SubFieldIterBase().
getBareField() [2/2]
template<class T, unsigned int Dim, class S, unsigned int ExprDim> const BareField<T,Dim>& SubFieldIterBase< T, Dim, S, ExprDim >::getBareField () const inline
Definition at line 154 of file SubFieldIter.h.
getBrackets()
template<class T, unsigned int Dim, class S, unsigned int ExprDim> unsigned int SubFieldIterBase< T, Dim, S, ExprDim >::getBrackets () const inline
Definition at line 167 of file SubFieldIter.h.
getDomain() [1/2]
template<class T, unsigned int Dim, class S, unsigned int ExprDim> S& SubFieldIterBase< T, Dim, S, ExprDim >::getDomain (void) inline
Definition at line 162 of file SubFieldIter.h.
getDomain() [2/2]
template<class T, unsigned int Dim, class S, unsigned int ExprDim> const S& SubFieldIterBase< T, Dim, S, ExprDim >::getDomain (void) const inline
Definition at line 163 of file SubFieldIter.h.
getLField() [1/2]
template<class T, unsigned int Dim, class S, unsigned int ExprDim> LField<T,Dim>* SubFieldIterBase< T, Dim, S, ExprDim >::getLField () inline
Definition at line 185 of file SubFieldIter.h.
getLField() [2/2]
template<class T, unsigned int Dim, class S, unsigned int ExprDim> const LField<T,Dim>* SubFieldIterBase< T, Dim, S, ExprDim >::getLField () const inline
Definition at line 186 of file SubFieldIter.h.
getLFieldIter()
template<class T, unsigned int Dim, class S, unsigned int ExprDim> BareField<T,Dim>::iterator_if SubFieldIterBase< T, Dim, S, ExprDim >::getLFieldIter () const inline
Definition at line 157 of file SubFieldIter.h.
nextLField()
template<class T, unsigned int Dim, class S, unsigned int ExprDim> BareField<T,Dim>::iterator_if SubFieldIterBase< T, Dim, S, ExprDim >::nextLField () inline
Definition at line 170 of file SubFieldIter.h.
Referenced by SubFieldIter< T, Dim, SIndex< Dim > >::nextLField().
setLField()
template<class T, unsigned int Dim, class S, unsigned int ExprDim> void SubFieldIterBase< T, Dim, S, ExprDim >::setLField (LField< T, Dim > * p) inline
Definition at line 189 of file SubFieldIter.h.
setLFieldData()
template<class T, unsigned int Dim, class S, unsigned int ExprDim> void SubFieldIterBase< T, Dim, S, ExprDim >::setLFieldData (LField< T, Dim > * p, NDIndex< Dim > &) inline
Definition at line 192 of file SubFieldIter.h.
Referenced by SubFieldIter< T, Dim, NDIndex< Dim > >::setLFieldData(), and SubFieldIter< T, Dim, SOffset< Dim > >::setLFieldData().
Member Data Documentation
CurrentLField
template<class T, unsigned int Dim, class S, unsigned int ExprDim> BareField<T,Dim>::iterator_if SubFieldIterBase< T, Dim, S, ExprDim >::CurrentLField private
Definition at line 239 of file SubFieldIter.h.
Referenced by SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::getLFieldIter(), SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::nextLField(), and SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::SubFieldIterBase().
LFPtr
template<class T, unsigned int Dim, class S, unsigned int ExprDim> LField<T,Dim>* SubFieldIterBase< T, Dim, S, ExprDim >::LFPtr private
Definition at line 236 of file SubFieldIter.h.
Referenced by SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::getLField(), SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::nextLField(), SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::setLField(), SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::setLFieldData(), and SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::SubFieldIterBase().
MyBareField
template<class T, unsigned int Dim, class S, unsigned int ExprDim> BareField<T,Dim>* SubFieldIterBase< T, Dim, S, ExprDim >::MyBareField private
Definition at line 228 of file SubFieldIter.h.
Referenced by SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::getBareField().
MyBrackets
template<class T, unsigned int Dim, class S, unsigned int ExprDim> unsigned int SubFieldIterBase< T, Dim, S, ExprDim >::MyBrackets private
Definition at line 242 of file SubFieldIter.h.
Referenced by SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::checkBrackets(), and SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::getBrackets().
MyDomain
template<class T, unsigned int Dim, class S, unsigned int ExprDim> S* SubFieldIterBase< T, Dim, S, ExprDim >::MyDomain private
Definition at line 231 of file SubFieldIter.h.
Referenced by SubFieldIterBase< T, Dim, SOffset< Dim >, 1U >::getDomain().
The documentation for this class was generated from the following file:
ippl/src/SubField/SubFieldIter.h