OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Particle/PAssign.hpp File Reference
PAssign.hpp File Reference
#include "Particle/PAssign.h"
#include "Particle/PAssignDefs.h"
#include "Particle/ParticleAttrib.h"
#include "Particle/ParticleAttribElem.h"
#include "PETE/IpplExpressions.h"
#include "Utility/IpplStats.h"
Functions
template<class T , unsigned Dim, class RHS , class OP >
void assign (const ParticleAttribElem< T, Dim > &ca, RHS b, OP op)
template<class T , class RHS , class OP >
void assign (const ParticleAttrib< T > &ca, RHS b, OP op)
Function Documentation
assign() [1/2]
template<class T , unsigned Dim, class RHS , class OP > void assign (const ParticleAttribElem< T, Dim > & ca, RHS b, OP op)
Definition at line 40 of file PAssign.hpp.
References a, for_each(), INCIPPLSTAT, PETE_apply(), and PETE_Expr< ParticleAttribElem< T, Dim > >::PETE_unwrap().
assign() [2/2]
template<class T , class RHS , class OP > void assign (const ParticleAttrib< T > & ca, RHS b, OP op)
Definition at line 58 of file PAssign.hpp.
References a, for_each(), INCIPPLSTAT, PETE_apply(), and PETE_Expr< ParticleAttrib< T > >::PETE_unwrap().
Referenced by assign().