OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Classic/FixedAlgebra/FVps.h File Reference
FVps.h File Reference
#include <algorithm>
#include <iosfwd>
#include "FixedAlgebra/FVps.hpp"
Classes
class Array1D< T >
One-dimensional array.
class FMatrix< T, R, C >
A templated representation for matrices.
class FTps< T, N >
Truncated power series in N variables of type T.
class FVector< T, N >
A templated representation for vectors.
class LinearMap< T, N >
Linear map with values of type [b]T[/b] in [b]N[/b] variables.
class TransportMap< T, N >
Transport map with values of type [b]T[/b] in [b]N[/b] variables.
class FArray1D< T, N >
A templated representation for one-dimensional arrays.
class FVps< T, N >
Vector truncated power series in n variables.
Functions
template<class T , int N>
FVps< T, N > operator+ (const FVps< T, N > &lhs, const FVps< T, N > &rhs)
Add.
template<class T , int N>
FVps< T, N > operator- (const FVps< T, N > &lhs, const FVps< T, N > &rhs)
Subtract.
template<class T , int N>
FVps< T, N > operator+ (const FVps< T, N > &lhs, const FVector< T, N > &rhs)
Add.
template<class T , int N>
FVps< T, N > operator- (const FVps< T, N > &lhs, const FVector< T, N > &rhs)
Subtract.
template<class T , int N>
FVps< T, N > operator+ (const FVector< T, N > &lhs, const FVps< T, N > &rhs)
Add.
template<class T , int N>
FVps< T, N > operator- (const FVector< T, N > &lhs, const FVps< T, N > &rhs)
Subtract.
template<class T , int N>
FVector< T, N > operator* (const FVps< T, N > &lhs, const FVector< T, N > &rhs)
Multiply.
template<class T , int N>
FVps< T, N > operator* (const FVps< T, N > &lhs, const FTps< T, N > &rhs)
Multiply.
template<class T , int N>
FVps< T, N > operator* (const FTps< T, N > &lhs, const FVps< T, N > &rhs)
Multiply.
template<class T , int N>
FVps< T, N > operator* (const FVps< T, N > &lhs, const T &rhs)
Multiply.
template<class T , int N>
FVps< T, N > operator* (const T &lhs, const FVps< T, N > &rhs)
Multiply.
template<class T , int N>
FVps< T, N > operator* (const FMatrix< T, N, N > &lhs, const FVps< T, N > &rhs)
Multiply.
template<class T , int N>
FVps< T, N > operator/ (const FVps< T, N > &lhs, const FTps< T, N > &rhs)
Divide.
template<class T , int N>
FVps< T, N > operator/ (const FVps< T, N > &lhs, const T &rhs)
Divide.
template<class T , int N>
FVps< T, N > ExpMap (const FTps< T, N > &H, const FVps< T, N > &M, int trunc=(FTps< T, N >::EXACT))
Build the exponential series.
template<class T , int N>
FVps< T, N > PoissonBracket (const FTps< T, N > &x, const FVps< T, N > &y, int trunc=(FTps< T, N >::EXACT))
Poisson bracket.
template<class T , int N>
std::istream & operator>> (std::istream &is, FVps< T, N > &)
Extract FVps from stream [b]is[/b].
template<class T , int N>
std::ostream & operator<< (std::ostream &os, const FVps< T, N > &vps)
Insert FVps to stream [b]os[/b].
Function Documentation
ExpMap()
template<class T , int N> FVps<T, N> ExpMap (const FTps< T, N > & H, const FVps< T, N > & M, int trunc = (FTps< T, N >::EXACT))
Build the exponential series.
Definition at line 1201 of file FVps.hpp.
References FTps< T, N >::derivative(), endl(), FTps< T, N >::getMinOrder(), FVps< T, N >::getTruncOrder(), FTps< T, N >::getTruncOrder(), min(), FTps< T, N >::multiply(), FTps< T, N >::setTruncOrder(), and Attrib::Legacy::Distribution::T.
operator*() [1/6]
template<class T , int N> FVector<T, N> operator* (const FVps< T, N > & lhs, const FVector< T, N > & rhs)
Multiply.
Definition at line 1137 of file FVps.hpp.
References FTps< T, N >::evaluate(), and FVps< T, N >::getComponent().
operator*() [2/6]
template<class T , int N> FVps<T, N> operator* (const FVps< T, N > & lhs, const FTps< T, N > & rhs)
Multiply.
Definition at line 1148 of file FVps.hpp.
operator*() [3/6]
template<class T , int N> FVps<T, N> operator* (const FTps< T, N > & lhs, const FVps< T, N > & rhs)
Multiply.
Definition at line 1156 of file FVps.hpp.
operator*() [4/6]
template<class T , int N> FVps<T, N> operator* (const FVps< T, N > & lhs, const T & rhs)
Multiply.
Definition at line 1164 of file FVps.hpp.
operator*() [5/6]
template<class T , int N> FVps<T, N> operator* (const T & lhs, const FVps< T, N > & rhs)
Multiply.
Definition at line 1172 of file FVps.hpp.
operator*() [6/6]
template<class T , int N> FVps<T, N> operator* (const FMatrix< T, N, N > & lhs, const FVps< T, N > & rhs)
Multiply.
Definition at line 1179 of file FVps.hpp.
References FVps< T, N >::substituteInto().
operator+() [1/3]
template<class T , int N> FVps<T, N> operator+ (const FVps< T, N > & lhs, const FVps< T, N > & rhs)
Add.
Definition at line 1089 of file FVps.hpp.
operator+() [2/3]
template<class T , int N> FVps<T, N> operator+ (const FVps< T, N > & lhs, const FVector< T, N > & rhs)
Add.
Definition at line 1105 of file FVps.hpp.
operator+() [3/3]
template<class T , int N> FVps<T, N> operator+ (const FVector< T, N > & lhs, const FVps< T, N > & rhs)
Add.
Definition at line 1121 of file FVps.hpp.
operator-() [1/3]
template<class T , int N> FVps<T, N> operator- (const FVps< T, N > & lhs, const FVps< T, N > & rhs)
Subtract.
Definition at line 1097 of file FVps.hpp.
operator-() [2/3]
template<class T , int N> FVps<T, N> operator- (const FVps< T, N > & lhs, const FVector< T, N > & rhs)
Subtract.
Definition at line 1113 of file FVps.hpp.
operator-() [3/3]
template<class T , int N> FVps<T, N> operator- (const FVector< T, N > & lhs, const FVps< T, N > & rhs)
Subtract.
Definition at line 1129 of file FVps.hpp.
operator/() [1/2]
template<class T , int N> FVps<T, N> operator/ (const FVps< T, N > & lhs, const FTps< T, N > & rhs)
Divide.
Definition at line 1185 of file FVps.hpp.
operator/() [2/2]
template<class T , int N> FVps<T, N> operator/ (const FVps< T, N > & lhs, const T & rhs)
Divide.
Definition at line 1193 of file FVps.hpp.
operator<<()
template<class T , int N> std::ostream& operator<< (std::ostream & os, const FVps< T, N > & vps)
Insert FVps to stream [b]os[/b].
Definition at line 1281 of file FVps.hpp.
References FVps< T, N >::put().
operator>>()
template<class T , int N> std::istream& operator>> (std::istream & is, FVps< T, N > &)
Extract FVps from stream [b]is[/b].
Definition at line 1275 of file FVps.hpp.
References FVps< T, N >::get().
PoissonBracket()
template<class T , int N> FVps<T, N> PoissonBracket (const FTps< T, N > & x, const FVps< T, N > & y, int trunc = (FTps< T, N >::EXACT))
Poisson bracket.
Definition at line 1266 of file FVps.hpp.