OPAL (Object Oriented Parallel Accelerator Library): mslang::SymmetricDifference Struct Reference
mslang::SymmetricDifference Struct Reference
#include <SymmetricDifference.h>
Public Member Functions
SymmetricDifference ()
SymmetricDifference (const SymmetricDifference &right)
virtual ~SymmetricDifference ()
virtual void print (int indentwidth)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Public Member Functions inherited from mslang::Function
virtual ~Function ()
virtual void apply (std::vector< std::shared_ptr< Base >> &bfuncs)=0
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
Static Public Member Functions inherited from mslang::Function
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
Function * firstOperand_m
Function * secondOperand_m
Additional Inherited Members
Static Public Attributes inherited from mslang::Function
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\((.*)"
Detailed Description
Definition at line 7 of file SymmetricDifference.h.
Constructor & Destructor Documentation
SymmetricDifference() [1/2]
mslang::SymmetricDifference::SymmetricDifference () inline
Definition at line 11 of file SymmetricDifference.h.
SymmetricDifference() [2/2]
mslang::SymmetricDifference::SymmetricDifference (const SymmetricDifference & right) inline
Definition at line 14 of file SymmetricDifference.h.
~SymmetricDifference()
virtual mslang::SymmetricDifference::~SymmetricDifference () inline virtual
Definition at line 19 of file SymmetricDifference.h.
References firstOperand_m, and secondOperand_m.
Member Function Documentation
apply()
void mslang::SymmetricDifference::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Definition at line 16 of file SymmetricDifference.cpp.
References mslang::Function::apply(), firstOperand_m, and secondOperand_m.
parse_detail()
bool mslang::SymmetricDifference::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 43 of file SymmetricDifference.cpp.
References end(), firstOperand_m, mslang::Function::parse(), and secondOperand_m.
Referenced by mslang::Function::parse().
print()
void mslang::SymmetricDifference::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 6 of file SymmetricDifference.cpp.
References firstOperand_m, mslang::Function::print(), and secondOperand_m.
Member Data Documentation
firstOperand_m
Function* mslang::SymmetricDifference::firstOperand_m
Definition at line 8 of file SymmetricDifference.h.
Referenced by apply(), parse_detail(), print(), and ~SymmetricDifference().
secondOperand_m
Function* mslang::SymmetricDifference::secondOperand_m
Definition at line 9 of file SymmetricDifference.h.
Referenced by apply(), parse_detail(), print(), and ~SymmetricDifference().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/SymmetricDifference.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/SymmetricDifference.cpp