OPAL (Object Oriented Parallel Accelerator Library): IpplMemoryUsage Class Reference
IpplMemoryUsage Class Reference
#include <IpplMemoryUsage.h>
Public Types
enum Unit {
BIT, B, KB, KiB,
MB, MiB, GB, GiB
}
typedef IpplMemoryUsage * IpplMemory_p
typedef std::unique_ptr< IpplMemoryUsage > IpplMemory_t
Public Member Functions
double getMemoryUsage (int core) const
void sample ()
const std::string & getUnit () const
Static Public Member Functions
static IpplMemory_p getInstance (Unit unit=Unit::GB, bool reset=true)
Private Member Functions
IpplMemoryUsage ()
IpplMemoryUsage (Unit unit=Unit::GB, bool reset=true)
void sample_m ()
Private Attributes
std::unique_ptr< double[]> globalMemPerCore_m
memory of all cores
std::string unit_m
what's the unit of the memory
double initial_memory_m
memory usage at construction time [GB] or [GiB]
double max_rss_m
max. resident set size [GB] or [GiB]
double conversion_factor_m
to various units. getrusage() returns in kB
double who_m
RUSAGE_SELF, RUSAGE_CHILDREN (, RUSAGE_THREAD)
Static Private Attributes
static IpplMemory_t instance_mp
*this
Detailed Description
Definition at line 51 of file IpplMemoryUsage.h.
Member Typedef Documentation
IpplMemory_p
typedef IpplMemoryUsage* IpplMemoryUsage::IpplMemory_p
Definition at line 55 of file IpplMemoryUsage.h.
IpplMemory_t
typedef std::unique_ptr<IpplMemoryUsage> IpplMemoryUsage::IpplMemory_t
Definition at line 56 of file IpplMemoryUsage.h.
Member Enumeration Documentation
Unit
enum IpplMemoryUsage::Unit
Enumerator
BIT
Bit.
B
Byte.
KB
KiloByte.
KiB
KibiByte.
MB
MegaByte.
MiB
MebiByte.
GB
GigaByte.
GiB
GebiByte.
Definition at line 58 of file IpplMemoryUsage.h.
Constructor & Destructor Documentation
IpplMemoryUsage() [1/2]
IpplMemoryUsage::IpplMemoryUsage () private
Does nothing.
Definition at line 47 of file IpplMemoryUsage.cpp.
Referenced by getInstance().
IpplMemoryUsage() [2/2]
IpplMemoryUsage::IpplMemoryUsage (Unit unit = Unit::GB, bool reset = true) private
Create an instance.
Parameters
unit we want to have
reset the memory to zero. The value at construction time is subtracted at every sampling.
Definition at line 51 of file IpplMemoryUsage.cpp.
References conversion_factor_m, IpplInfo::getNodes(), globalMemPerCore_m, initial_memory_m, max_rss_m, sample_m(), and unit_m.
Member Function Documentation
getInstance()
IpplMemoryUsage::IpplMemory_p IpplMemoryUsage::getInstance (Unit unit = Unit::GB, bool reset = true) static
Create / Get pointer to instance
Parameters
unit of memory
reset the memory to zero. (see constructor documentation)
Definition at line 100 of file IpplMemoryUsage.cpp.
References instance_mp, and IpplMemoryUsage().
Referenced by Option::execute(), MemoryWriter::fillHeader(), and MemoryWriter::write().
getMemoryUsage()
double IpplMemoryUsage::getMemoryUsage (int core) const
Get the memory of a specific core (only valid call for root core 0)
Parameters
core we want memory of.
Returns
the max. resident set size
Definition at line 108 of file IpplMemoryUsage.cpp.
References globalMemPerCore_m.
Referenced by MemoryWriter::write().
getUnit()
const std::string & IpplMemoryUsage::getUnit () const
Returns
the unit string.
Definition at line 126 of file IpplMemoryUsage.cpp.
References unit_m.
Referenced by MemoryWriter::fillHeader().
sample()
void IpplMemoryUsage::sample ()
Collect the memory data of all cores.
Definition at line 113 of file IpplMemoryUsage.cpp.
References gather(), IpplInfo::getNodes(), globalMemPerCore_m, max_rss_m, and sample_m().
Referenced by Option::execute(), and MemoryWriter::write().
sample_m()
void IpplMemoryUsage::sample_m () private
Obtain the memory consumption. It throws an exception if an error ocurred.
Definition at line 131 of file IpplMemoryUsage.cpp.
References conversion_factor_m, initial_memory_m, max_rss_m, and who_m.
Referenced by IpplMemoryUsage(), and sample().
Member Data Documentation
conversion_factor_m
double IpplMemoryUsage::conversion_factor_m private
to various units. getrusage() returns in kB
Definition at line 120 of file IpplMemoryUsage.h.
Referenced by IpplMemoryUsage(), and sample_m().
globalMemPerCore_m
std::unique_ptr<double[]> IpplMemoryUsage::globalMemPerCore_m private
memory of all cores
Definition at line 116 of file IpplMemoryUsage.h.
Referenced by getMemoryUsage(), IpplMemoryUsage(), and sample().
initial_memory_m
double IpplMemoryUsage::initial_memory_m private
memory usage at construction time [GB] or [GiB]
Definition at line 118 of file IpplMemoryUsage.h.
Referenced by IpplMemoryUsage(), and sample_m().
instance_mp
IpplMemory_t IpplMemoryUsage::instance_mp static private
*this
Definition at line 115 of file IpplMemoryUsage.h.
Referenced by getInstance().
max_rss_m
double IpplMemoryUsage::max_rss_m private
max. resident set size [GB] or [GiB]
Definition at line 119 of file IpplMemoryUsage.h.
Referenced by IpplMemoryUsage(), sample(), and sample_m().
unit_m
std::string IpplMemoryUsage::unit_m private
what's the unit of the memory
Definition at line 117 of file IpplMemoryUsage.h.
Referenced by getUnit(), and IpplMemoryUsage().
who_m
double IpplMemoryUsage::who_m private
RUSAGE_SELF, RUSAGE_CHILDREN (, RUSAGE_THREAD)
Definition at line 121 of file IpplMemoryUsage.h.
Referenced by sample_m().
The documentation for this class was generated from the following files:
ippl/src/Utility/IpplMemoryUsage.h
ippl/src/Utility/IpplMemoryUsage.cpp