OPAL (Object Oriented Parallel Accelerator Library): IPPL Namespace Reference
IPPL Namespace Reference
Functions
template<class T1 , class T2 , class MFLOAT >
Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > & Average (Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > &x, Field< T2, 1U, Cartesian< 1U, MFLOAT >, Cell > &w, Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > & Average (Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > &x, Field< T2, 2U, Cartesian< 2U, MFLOAT >, Cell > &w, Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > & Average (Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > &x, Field< T2, 3U, Cartesian< 3U, MFLOAT >, Cell > &w, Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > & Average (Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > &x, Field< T2, 1U, Cartesian< 1U, MFLOAT >, Vert > &w, Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > & Average (Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > &x, Field< T2, 2U, Cartesian< 2U, MFLOAT >, Vert > &w, Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > & Average (Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > &x, Field< T2, 3U, Cartesian< 3U, MFLOAT >, Vert > &w, Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > &r)
template<class T1 , class MFLOAT >
Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > & Average (Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > &x, Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > &r)
template<class T1 , class MFLOAT >
Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > & Average (Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > &x, Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > &r)
template<class T1 , class MFLOAT >
Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > & Average (Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > &x, Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > &r)
template<class T1 , class MFLOAT >
Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > & Average (Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > &x, Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > &r)
template<class T1 , class MFLOAT >
Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > & Average (Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > &x, Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > &r)
template<class T1 , class MFLOAT >
Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > & Average (Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > &x, Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & Average (Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &x, Field< T2, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &w, Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & Average (Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &x, Field< T2, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &w, Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & Average (Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &x, Field< T2, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &w, Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & Average (Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &x, Field< T2, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &w, Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & Average (Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &x, Field< T2, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &w, Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & Average (Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &x, Field< T2, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &w, Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &r)
template<class T1 , class MFLOAT >
Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & Average (Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &x, Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &r)
template<class T1 , class MFLOAT >
Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & Average (Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &x, Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &r)
template<class T1 , class MFLOAT >
Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & Average (Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &x, Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &r)
template<class T1 , class MFLOAT >
Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & Average (Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &x, Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &r)
template<class T1 , class MFLOAT >
Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & Average (Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &x, Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &r)
template<class T1 , class MFLOAT >
Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & Average (Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &x, Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &r)
Function Documentation
Average() [1/24]
template<class T1 , class T2 , class MFLOAT > Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > & x, Field< T2, 1U, Cartesian< 1U, MFLOAT >, Cell > & w, Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 3113 of file Cartesian.hpp.
Average() [2/24]
template<class T1 , class T2 , class MFLOAT > Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > & x, Field< T2, 2U, Cartesian< 2U, MFLOAT >, Cell > & w, Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 3125 of file Cartesian.hpp.
Average() [3/24]
template<class T1 , class T2 , class MFLOAT > Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > & x, Field< T2, 3U, Cartesian< 3U, MFLOAT >, Cell > & w, Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 3146 of file Cartesian.hpp.
Average() [4/24]
template<class T1 , class T2 , class MFLOAT > Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & x, Field< T2, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & w, Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 2332 of file UniformCartesian.hpp.
References assign().
Average() [5/24]
template<class T1 , class T2 , class MFLOAT > Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > & x, Field< T2, 1U, Cartesian< 1U, MFLOAT >, Vert > & w, Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 3179 of file Cartesian.hpp.
Average() [6/24]
template<class T1 , class T2 , class MFLOAT > Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & x, Field< T2, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & w, Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 2346 of file UniformCartesian.hpp.
References assign().
Average() [7/24]
template<class T1 , class T2 , class MFLOAT > Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > & x, Field< T2, 2U, Cartesian< 2U, MFLOAT >, Vert > & w, Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 3191 of file Cartesian.hpp.
Average() [8/24]
template<class T1 , class T2 , class MFLOAT > Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & x, Field< T2, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & w, Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 2368 of file UniformCartesian.hpp.
References assign().
Average() [9/24]
template<class T1 , class T2 , class MFLOAT > Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > & x, Field< T2, 3U, Cartesian< 3U, MFLOAT >, Vert > & w, Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 3212 of file Cartesian.hpp.
Average() [10/24]
template<class T1 , class T2 , class MFLOAT > Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & x, Field< T2, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & w, Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 2402 of file UniformCartesian.hpp.
References assign().
Average() [11/24]
template<class T1 , class MFLOAT > Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > & x, Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 3245 of file Cartesian.hpp.
Average() [12/24]
template<class T1 , class T2 , class MFLOAT > Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & x, Field< T2, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & w, Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 2416 of file UniformCartesian.hpp.
References assign().
Average() [13/24]
template<class T1 , class MFLOAT > Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > & x, Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 3256 of file Cartesian.hpp.
Average() [14/24]
template<class T1 , class T2 , class MFLOAT > Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & x, Field< T2, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & w, Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 2438 of file UniformCartesian.hpp.
References assign().
Average() [15/24]
template<class T1 , class MFLOAT > Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > & x, Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 3268 of file Cartesian.hpp.
Average() [16/24]
template<class T1 , class MFLOAT > Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 1U, Cartesian< 1U, MFLOAT >, Vert > & x, Field< T1, 1U, Cartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 3286 of file Cartesian.hpp.
Average() [17/24]
template<class T1 , class MFLOAT > Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & x, Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 2472 of file UniformCartesian.hpp.
Average() [18/24]
template<class T1 , class MFLOAT > Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 2U, Cartesian< 2U, MFLOAT >, Vert > & x, Field< T1, 2U, Cartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 3297 of file Cartesian.hpp.
Average() [19/24]
template<class T1 , class MFLOAT > Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & x, Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 2483 of file UniformCartesian.hpp.
Average() [20/24]
template<class T1 , class MFLOAT > Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 3U, Cartesian< 3U, MFLOAT >, Vert > & x, Field< T1, 3U, Cartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 3309 of file Cartesian.hpp.
Average() [21/24]
template<class T1 , class MFLOAT > Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & x, Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 2495 of file UniformCartesian.hpp.
Average() [22/24]
template<class T1 , class MFLOAT > Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & x, Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 2513 of file UniformCartesian.hpp.
Average() [23/24]
template<class T1 , class MFLOAT > Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & x, Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 2525 of file UniformCartesian.hpp.
Average() [24/24]
template<class T1 , class MFLOAT > Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & x, Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 2537 of file UniformCartesian.hpp.