OPAL (Object Oriented Parallel Accelerator Library): matheval::detail::grammar< real_t, Iterator > Struct Template Reference
matheval::detail::grammar< real_t, Iterator > Struct Template Reference
Expression Grammar.
#include <matheval.hpp>
Inherits grammar< Iterator, expr_ast< real_t >(), ascii::space_type >.
Classes
struct bfunc_
symbol table for binary functions like "pow"
struct constant_
symbol table for constants like "pi"
struct ufunc_
symbol table for unary functions like "abs"
Public Member Functions
grammar ()
Constructor builds the grammar.
Public Attributes
matheval::detail::grammar::constant_ constant
matheval::detail::grammar::ufunc_ ufunc
matheval::detail::grammar::bfunc_ bfunc
Private Attributes
expectation_handler err_handler
qi::rule< Iterator, expr_ast< real_t >), ascii::space_type > expression
qi::rule< Iterator, expr_ast< real_t >), ascii::space_type > term
qi::rule< Iterator, expr_ast< real_t >), ascii::space_type > factor
qi::rule< Iterator, expr_ast< real_t >), ascii::space_type > primary
qi::rule< Iterator, std::string()> variable
Detailed Description
template<typename real_t, typename Iterator>
struct matheval::detail::grammar< real_t, Iterator >
Expression Grammar.
Definition at line 373 of file matheval.hpp.
Constructor & Destructor Documentation
grammar()
template<typename real_t, typename Iterator> matheval::detail::grammar< real_t, Iterator >::grammar () inline
Constructor builds the grammar.
Definition at line 468 of file matheval.hpp.
References Physics::alpha, matheval::detail::grammar< real_t, Iterator >::bfunc, matheval::detail::grammar< real_t, Iterator >::constant, matheval::detail::grammar< real_t, Iterator >::err_handler, matheval::detail::grammar< real_t, Iterator >::expression, matheval::detail::grammar< real_t, Iterator >::factor, fmod(), pow(), matheval::detail::grammar< real_t, Iterator >::primary, real(), Hypervolume::ref, matheval::detail::grammar< real_t, Iterator >::term, matheval::detail::grammar< real_t, Iterator >::ufunc, and matheval::detail::grammar< real_t, Iterator >::variable.
Member Data Documentation
bfunc
template<typename real_t, typename Iterator> matheval::detail::grammar::bfunc_ matheval::detail::grammar< real_t, Iterator >::bfunc
Referenced by matheval::detail::grammar< real_t, Iterator >::grammar().
constant
template<typename real_t, typename Iterator> matheval::detail::grammar::constant_ matheval::detail::grammar< real_t, Iterator >::constant
Referenced by matheval::detail::grammar< real_t, Iterator >::grammar().
err_handler
template<typename real_t, typename Iterator> expectation_handler matheval::detail::grammar< real_t, Iterator >::err_handler private
Definition at line 379 of file matheval.hpp.
Referenced by matheval::detail::grammar< real_t, Iterator >::grammar().
expression
template<typename real_t, typename Iterator> qi::rule<Iterator, expr_ast<real_t>), ascii::space_type> matheval::detail::grammar< real_t, Iterator >::expression private
Definition at line 380 of file matheval.hpp.
Referenced by matheval::detail::grammar< real_t, Iterator >::grammar().
factor
template<typename real_t, typename Iterator> qi::rule<Iterator, expr_ast<real_t>), ascii::space_type> matheval::detail::grammar< real_t, Iterator >::factor private
Definition at line 382 of file matheval.hpp.
Referenced by matheval::detail::grammar< real_t, Iterator >::grammar().
primary
template<typename real_t, typename Iterator> qi::rule<Iterator, expr_ast<real_t>), ascii::space_type> matheval::detail::grammar< real_t, Iterator >::primary private
Definition at line 383 of file matheval.hpp.
Referenced by matheval::detail::grammar< real_t, Iterator >::grammar().
term
template<typename real_t, typename Iterator> qi::rule<Iterator, expr_ast<real_t>), ascii::space_type> matheval::detail::grammar< real_t, Iterator >::term private
Definition at line 381 of file matheval.hpp.
Referenced by matheval::detail::grammar< real_t, Iterator >::grammar().
ufunc
template<typename real_t, typename Iterator> matheval::detail::grammar::ufunc_ matheval::detail::grammar< real_t, Iterator >::ufunc
Referenced by matheval::detail::grammar< real_t, Iterator >::grammar().
variable
template<typename real_t, typename Iterator> qi::rule<Iterator, std::string()> matheval::detail::grammar< real_t, Iterator >::variable private
Definition at line 384 of file matheval.hpp.
Referenced by matheval::detail::grammar< real_t, Iterator >::grammar().
The documentation for this struct was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/matheval.hpp