OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Classic/FixedAlgebra/FTps.hpp File Reference
FTps.hpp File Reference
#include "FixedAlgebra/FTps.h"
#include "FixedAlgebra/FTpsData.h"
#include "Algebra/Array1D.h"
#include "FixedAlgebra/FArray1D.h"
#include "FixedAlgebra/FMatrix.h"
#include "FixedAlgebra/FMonomial.h"
#include "FixedAlgebra/FVector.h"
#include "Utilities/ConvergenceError.h"
#include "Utilities/DivideError.h"
#include "Utilities/FormatError.h"
#include "Utilities/LogicalError.h"
#include <climits>
#include <algorithm>
#include <iomanip>
#include <iostream>
#include <functional>
#include <string>
Classes
class FTpsRep< T, N >
Functions
template<class T , int N>
FTps< T, N > operator+ (const FTps< T, N > &lhs, const FTps< T, N > &rhs)
Add.
template<class T , int N>
FTps< T, N > operator- (const FTps< T, N > &lhs, const FTps< T, N > &rhs)
Subtract.
template<class T , int N>
FTps< T, N > operator+ (const FTps< T, N > &lhs, const T &rhs)
Add.
template<class T , int N>
FTps< T, N > operator- (const FTps< T, N > &lhs, const T &rhs)
Subtract.
template<class T , int N>
FTps< T, N > operator+ (const T &lhs, const FTps< T, N > &rhs)
Add.
template<class T , int N>
FTps< T, N > operator- (const T &lhs, const FTps< T, N > &rhs)
Subtract.
template<class T , int N>
FTps< T, N > operator* (const FTps< T, N > &lhs, const FTps< T, N > &rhs)
Multiply.
template<class T , int N>
FTps< T, N > operator/ (const FTps< T, N > &lhs, const FTps< T, N > &rhs)
Divide.
template<class T , int N>
FTps< T, N > operator* (const FTps< T, N > &lhs, const T &rhs)
Multiply.
template<class T , int N>
FTps< T, N > operator/ (const FTps< T, N > &lhs, const T &rhs)
Divide.
template<class T , int N>
FTps< T, N > operator* (const T &lhs, const FTps< T, N > &rhs)
Multiply.
template<class T , int N>
FTps< T, N > operator/ (const T &lhs, const FTps< T, N > &rhs)
Divide.
template<class T , int N>
bool operator== (const T &lhs, const FTps< T, N > &rhs)
Equality.
template<class T , int N>
bool operator!= (const T &lhs, const FTps< T, N > &rhs)
Inequality.
template<class T , int N>
FVps< T, N > ExpMap (const FTps< T, N > &H, int trunc)
Build the exponential series.
template<class T , int N>
FTps< T, N > ExpMap (const FTps< T, N > &H, const FTps< T, N > &f, int trunc)
Build the exponential series.
template<class T , int N>
FTps< T, N > PoissonBracket (const FTps< T, N > &f, const FTps< T, N > &g, int trunc)
Poisson bracket.
template<class T , int N>
std::istream & operator>> (std::istream &is, FTps< T, N > &tps)
Extract FTps from stream [b]is[/b].
template<class T , int N>
std::ostream & operator<< (std::ostream &os, const FTps< T, N > &tps)
Insert FTps into stream [b]os[/b].
Function Documentation
ExpMap() [1/2]
template<class T , int N> FVps<T, N> ExpMap (const FTps< T, N > & H, int trunc)
Build the exponential series.
Definition at line 1994 of file FTps.hpp.
Referenced by MapGenerator< Value_type, Size_type, Series_type, Map_type, Hamiltonian_type, Space_charge_type >::generateMap(), and ThickTracker::track_m().
ExpMap() [2/2]
template<class T , int N> FTps<T, N> ExpMap (const FTps< T, N > & H, const FTps< T, N > & f, int trunc)
Build the exponential series.
Definition at line 2000 of file FTps.hpp.
References FTps< T, N >::derivative(), endl(), FTps< T, N >::getMinOrder(), FTps< T, N >::getTruncOrder(), min(), FTps< T, N >::multiply(), FTps< T, N >::setTruncOrder(), and Attrib::Legacy::Distribution::T.
operator!=()
template<class T , int N> bool operator!= (const T & lhs, const FTps< T, N > & rhs)
Inequality.
Definition at line 1988 of file FTps.hpp.
operator*() [1/3]
template<class T , int N> FTps<T, N> operator* (const FTps< T, N > & lhs, const FTps< T, N > & rhs)
Multiply.
Definition at line 1942 of file FTps.hpp.
References FTps< T, N >::multiply().
operator*() [2/3]
template<class T , int N> FTps<T, N> operator* (const FTps< T, N > & lhs, const T & rhs)
Multiply.
Definition at line 1955 of file FTps.hpp.
operator*() [3/3]
template<class T , int N> FTps<T, N> operator* (const T & lhs, const FTps< T, N > & rhs)
Multiply.
Definition at line 1969 of file FTps.hpp.
operator+() [1/3]
template<class T , int N> FTps<T, N> operator+ (const FTps< T, N > & lhs, const FTps< T, N > & rhs)
Add.
Definition at line 1802 of file FTps.hpp.
References FTps< T, N >::begin(), FTps< T, N >::getMaxOrder(), FTps< T, N >::getMinOrder(), FTps< T, N >::getTruncOrder(), max(), min(), FTps< T, N >::orderEnd(), FTps< T, N >::orderStart(), and Attrib::Legacy::Distribution::T.
operator+() [2/3]
template<class T , int N> FTps<T, N> operator+ (const FTps< T, N > & lhs, const T & rhs)
Add.
Definition at line 1914 of file FTps.hpp.
operator+() [3/3]
template<class T , int N> FTps<T, N> operator+ (const T & lhs, const FTps< T, N > & rhs)
Add.
Definition at line 1928 of file FTps.hpp.
operator-() [1/3]
template<class T , int N> FTps<T, N> operator- (const FTps< T, N > & lhs, const FTps< T, N > & rhs)
Subtract.
Definition at line 1858 of file FTps.hpp.
References FTps< T, N >::begin(), FTps< T, N >::getMaxOrder(), FTps< T, N >::getMinOrder(), FTps< T, N >::getTruncOrder(), max(), min(), FTps< T, N >::orderEnd(), FTps< T, N >::orderStart(), and Attrib::Legacy::Distribution::T.
operator-() [2/3]
template<class T , int N> FTps<T, N> operator- (const FTps< T, N > & lhs, const T & rhs)
Subtract.
Definition at line 1921 of file FTps.hpp.
operator-() [3/3]
template<class T , int N> FTps<T, N> operator- (const T & lhs, const FTps< T, N > & rhs)
Subtract.
Definition at line 1935 of file FTps.hpp.
operator/() [1/3]
template<class T , int N> FTps<T, N> operator/ (const FTps< T, N > & lhs, const FTps< T, N > & rhs)
Divide.
Definition at line 1949 of file FTps.hpp.
References FTps< T, N >::divide().
operator/() [2/3]
template<class T , int N> FTps<T, N> operator/ (const FTps< T, N > & lhs, const T & rhs)
Divide.
Definition at line 1962 of file FTps.hpp.
operator/() [3/3]
template<class T , int N> FTps<T, N> operator/ (const T & lhs, const FTps< T, N > & rhs)
Divide.
Definition at line 1976 of file FTps.hpp.
References FTps< T, N >::inverse().
operator<<()
template<class T , int N> std::ostream& operator<< (std::ostream & os, const FTps< T, N > & tps)
Insert FTps into stream [b]os[/b].
Definition at line 2098 of file FTps.hpp.
operator==()
template<class T , int N> bool operator== (const T & lhs, const FTps< T, N > & rhs)
Equality.
Definition at line 1982 of file FTps.hpp.
operator>>()
template<class T , int N> std::istream& operator>> (std::istream & is, FTps< T, N > & tps)
Extract FTps from stream [b]is[/b].
Definition at line 2092 of file FTps.hpp.
References FTps< T, N >::get().
PoissonBracket()
template<class T , int N> FTps<T, N> PoissonBracket (const FTps< T, N > & f, const FTps< T, N > & g, int trunc)
Poisson bracket.
Definition at line 2058 of file FTps.hpp.