OPAL (Object Oriented Parallel Accelerator Library): mslang::BoundingBox2D Struct Reference
mslang::BoundingBox2D Struct Reference
#include <BoundingBox2D.h>
Public Member Functions
BoundingBox2D ()
BoundingBox2D (const BoundingBox2D &right)
BoundingBox2D (const Vector_t &llc, const Vector_t &urc)
BoundingBox2D & operator= (const BoundingBox2D &)=default
bool doesIntersect (const BoundingBox2D &bb) const
bool isInside (const Vector_t &X) const
bool isInside (const BoundingBox2D &b) const
virtual void writeGnuplot (std::ostream &out) const
void print (std::ostream &out) const
Public Attributes
Vector_t center_m
double width_m
double height_m
Detailed Description
Definition at line 30 of file BoundingBox2D.h.
Constructor & Destructor Documentation
BoundingBox2D() [1/3]
mslang::BoundingBox2D::BoundingBox2D () inline
Definition at line 35 of file BoundingBox2D.h.
BoundingBox2D() [2/3]
mslang::BoundingBox2D::BoundingBox2D (const BoundingBox2D & right) inline
Definition at line 41 of file BoundingBox2D.h.
BoundingBox2D() [3/3]
mslang::BoundingBox2D::BoundingBox2D (const Vector_t & llc, const Vector_t & urc) inline
Definition at line 47 of file BoundingBox2D.h.
Member Function Documentation
doesIntersect()
bool mslang::BoundingBox2D::doesIntersect (const BoundingBox2D & bb) const
Definition at line 24 of file BoundingBox2D.cpp.
References center_m, height_m, and width_m.
Referenced by mslang::Base::divideBy(), and Mesher::isPotentialEdgeIntersected().
isInside() [1/2]
bool mslang::BoundingBox2D::isInside (const Vector_t & X) const
Definition at line 31 of file BoundingBox2D.cpp.
References abs(), center_m, height_m, width_m, and X.
Referenced by mslang::Rectangle::isInside(), mslang::Ellipse::isInside(), isInside(), FlexibleCollimator::isStopped(), and mslang::QuadTree::transferIfInside().
isInside() [2/2]
bool mslang::BoundingBox2D::isInside (const BoundingBox2D & b) const
Definition at line 39 of file BoundingBox2D.cpp.
References center_m, height_m, isInside(), and width_m.
operator=()
BoundingBox2D& mslang::BoundingBox2D::operator= (const BoundingBox2D &) default
print()
void mslang::BoundingBox2D::print (std::ostream & out) const
Definition at line 62 of file BoundingBox2D.cpp.
References center_m, endl(), height_m, and width_m.
Referenced by mslang::operator<<().
writeGnuplot()
void mslang::BoundingBox2D::writeGnuplot (std::ostream & out) const virtual
Definition at line 46 of file BoundingBox2D.cpp.
References center_m, endl(), height_m, and width_m.
Referenced by mslang::QuadTree::writeGnuplot().
Member Data Documentation
center_m
Vector_t mslang::BoundingBox2D::center_m
Definition at line 31 of file BoundingBox2D.h.
Referenced by mslang::QuadTree::buildUp(), doesIntersect(), mslang::QuadTree::isInside(), isInside(), Mesher::isPotentialEdgeIntersected(), print(), FlexibleCollimator::setDescription(), and writeGnuplot().
height_m
double mslang::BoundingBox2D::height_m
Definition at line 33 of file BoundingBox2D.h.
Referenced by mslang::QuadTree::buildUp(), doesIntersect(), isInside(), Mesher::isPotentialEdgeIntersected(), print(), FlexibleCollimator::setDescription(), and writeGnuplot().
width_m
double mslang::BoundingBox2D::width_m
Definition at line 32 of file BoundingBox2D.h.
Referenced by mslang::QuadTree::buildUp(), doesIntersect(), isInside(), Mesher::isPotentialEdgeIntersected(), print(), FlexibleCollimator::setDescription(), and writeGnuplot().
The documentation for this struct was generated from the following files:
src/Classic/Utilities/MSLang/BoundingBox2D.h
src/Classic/Utilities/MSLang/BoundingBox2D.cpp