OPAL (Object Oriented Parallel Accelerator Library): IntTSC Class Reference
IntTSC Class Reference
#include <IntTSC.h>
Public Member Functions
IntTSC ()
~IntTSC ()
Static Public Member Functions
template<class FT , unsigned Dim, class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh)
template<class FT , unsigned Dim, class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh, CacheDataTSC< PT, Dim > &cache)
template<class FT , unsigned Dim, class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, Dim, M, C > &f, const CacheDataTSC< PT, Dim > &cache)
template<class FT , unsigned Dim, class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh)
template<class FT , unsigned Dim, class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, Dim, M, C > &f, const Vektor< PT, Dim > &ppos, const M &mesh, CacheDataTSC< PT, Dim > &cache)
template<class FT , unsigned Dim, class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, Dim, M, C > &f, const CacheDataTSC< PT, Dim > &cache)
Detailed Description
Definition at line 872 of file IntTSC.h.
Constructor & Destructor Documentation
IntTSC()
IntTSC::IntTSC () inline
Definition at line 876 of file IntTSC.h.
~IntTSC()
IntTSC::~IntTSC () inline
Definition at line 877 of file IntTSC.h.
Member Function Documentation
gather() [1/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntTSC::gather (FT & pdata, const Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh) inline static
Definition at line 912 of file IntTSC.h.
References IntTSCImpl< Dim >::gather().
gather() [2/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntTSC::gather (FT & pdata, const Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh, CacheDataTSC< PT, Dim > & cache) inline static
Definition at line 921 of file IntTSC.h.
References CacheDataTSC< T, Dim >::Delta_m, IntTSCImpl< Dim >::gather(), CacheDataTSC< T, Dim >::Index_m, and CacheDataTSC< T, Dim >::Offset_m.
gather() [3/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntTSC::gather (FT & pdata, const Field< FT, Dim, M, C > & f, const CacheDataTSC< PT, Dim > & cache) inline static
Definition at line 931 of file IntTSC.h.
References CacheDataTSC< T, Dim >::Delta_m, IntTSCImpl< Dim >::gather(), CacheDataTSC< T, Dim >::Index_m, and CacheDataTSC< T, Dim >::Offset_m.
scatter() [1/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntTSC::scatter (const FT & pdata, Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh) inline static
Definition at line 884 of file IntTSC.h.
References IntTSCImpl< Dim >::scatter().
scatter() [2/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntTSC::scatter (const FT & pdata, Field< FT, Dim, M, C > & f, const Vektor< PT, Dim > & ppos, const M & mesh, CacheDataTSC< PT, Dim > & cache) inline static
Definition at line 893 of file IntTSC.h.
References CacheDataTSC< T, Dim >::Delta_m, CacheDataTSC< T, Dim >::Index_m, CacheDataTSC< T, Dim >::Offset_m, and IntTSCImpl< Dim >::scatter().
scatter() [3/3]
template<class FT , unsigned Dim, class M , class C , class PT > static void IntTSC::scatter (const FT & pdata, Field< FT, Dim, M, C > & f, const CacheDataTSC< PT, Dim > & cache) inline static
Definition at line 903 of file IntTSC.h.
References CacheDataTSC< T, Dim >::Delta_m, CacheDataTSC< T, Dim >::Index_m, CacheDataTSC< T, Dim >::Offset_m, and IntTSCImpl< Dim >::scatter().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/IntTSC.h