OPAL (Object Oriented Parallel Accelerator Library): FFTPACK_wrap< double > Class Template Reference
FFTPACK_wrap< double > Class Template Reference
#include <fftpack_FFT.h>
Static Public Member Functions
static void ccffti (size_t n, double *wsave)
static void rcffti (size_t n, double *wsave)
static void rrffti (size_t n, double *wsave)
static void ccfftf (size_t n, double *r, double *wsave)
static void ccfftb (size_t n, double *r, double *wsave)
static void rcfftf (size_t n, double *r, double *wsave)
static void rcfftb (size_t n, double *r, double *wsave)
static void rrfft (size_t n, double *r, double *wsave)
Detailed Description
template<>
class FFTPACK_wrap< double >
Definition at line 79 of file fftpack_FFT.h.
Member Function Documentation
ccfftb()
static void FFTPACK_wrap< double >::ccfftb (size_t n, double * r, double * wsave) inline static
Definition at line 90 of file fftpack_FFT.h.
References cfftb(), and Hypervolume::n.
ccfftf()
static void FFTPACK_wrap< double >::ccfftf (size_t n, double * r, double * wsave) inline static
Definition at line 89 of file fftpack_FFT.h.
References cfftf(), and Hypervolume::n.
ccffti()
static void FFTPACK_wrap< double >::ccffti (size_t n, double * wsave) inline static
Definition at line 85 of file fftpack_FFT.h.
References cffti(), and Hypervolume::n.
rcfftb()
static void FFTPACK_wrap< double >::rcfftb (size_t n, double * r, double * wsave) inline static
Definition at line 93 of file fftpack_FFT.h.
References Hypervolume::n, and rfftb().
rcfftf()
static void FFTPACK_wrap< double >::rcfftf (size_t n, double * r, double * wsave) inline static
Definition at line 92 of file fftpack_FFT.h.
References Hypervolume::n, and rfftf().
rcffti()
static void FFTPACK_wrap< double >::rcffti (size_t n, double * wsave) inline static
Definition at line 86 of file fftpack_FFT.h.
References Hypervolume::n, and rffti().
rrfft()
static void FFTPACK_wrap< double >::rrfft (size_t n, double * r, double * wsave) inline static
Definition at line 95 of file fftpack_FFT.h.
References Hypervolume::n, and sint().
rrffti()
static void FFTPACK_wrap< double >::rrffti (size_t n, double * wsave) inline static
Definition at line 87 of file fftpack_FFT.h.
References Hypervolume::n, and sinti().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/FFT/fftpack_FFT.h