OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Classic/Algorithms/Quaternion.cpp File Reference
Quaternion.cpp File Reference
#include "Algorithms/BoostMatrix.h"
#include "Algorithms/Quaternion.h"
#include "Physics/Physics.h"
#include "Utility/RandomNumberGen.h"
#include "Utilities/GeneralClassicException.h"
Functions
Quaternion getQuaternion (Vector_t u, Vector_t ref)
Function Documentation
getQuaternion()
Quaternion getQuaternion (Vector_t u, Vector_t ref)
Definition at line 34 of file Quaternion.cpp.
References abs(), cos(), cross(), dot(), Physics::e, IpplRandom, Physics::pi, Hypervolume::ref, sin(), and sqrt().
Referenced by ParallelTTracker::applyFractionalStep(), ParallelTTracker::computeSpaceChargeFields(), ParallelTTracker::computeWakefield(), Monitor::driftToCorrectPositionAndSave(), Bend2D::getOutline(), Bend2D::setFieldCalcParam(), and ParallelTTracker::updateRefToLabCSTrafo().