OPAL (Object Oriented Parallel Accelerator Library): ParticleCashedLayout< T, Dim, Mesh > Class Template Reference
ParticleCashedLayout< T, Dim, Mesh > Class Template Reference
#include <ParticleCashedLayout.h>
Public Types
typedef ParticleLayout< T, Dim >::SingleParticlePos_t SingleParticlePos_t
typedef ParticleLayout< T, Dim >::Index_t Index_t
typedef ParticleInteractAttrib< SingleParticlePos_t > ParticlePos_t
typedef ParticleInteractAttrib< Index_t > ParticleIndex_t
typedef ParticleInteractAttrib< T > ParticleInterRadius_t
Public Types inherited from ParticleSpatialLayout< T, Dim, Mesh >
typedef int pair_t
typedef pair_t * pair_iterator
typedef ParticleLayout< T, Dim >::SingleParticlePos_t SingleParticlePos_t
typedef ParticleLayout< T, Dim >::Index_t Index_t
typedef ParticleAttrib< SingleParticlePos_t > ParticlePos_t
typedef ParticleAttrib< Index_t > ParticleIndex_t
typedef RegionLayout< T, Dim, Mesh > RegionLayout_t
Public Types inherited from ParticleLayout< T, Dim >
enum { Dimension = Dim }
enum UpdateFlags {
SWAP, BCONDS, NUMFLAGS, OPTDESTROY,
ALL
}
typedef T Position_t
typedef unsigned Index_t
typedef Vektor< T, Dim > SingleParticlePos_t
Public Types inherited from User
typedef Unique::type ID_t
Public Member Functions
ParticleCashedLayout (FieldLayout< Dim > &)
ParticleCashedLayout (FieldLayout< Dim > &, Mesh &)
ParticleCashedLayout (const RegionLayout< T, Dim, Mesh > &)
ParticleCashedLayout ()
~ParticleCashedLayout ()
void update (IpplParticleBase< ParticleCashedLayout< T, Dim, Mesh > > &p, const ParticleAttrib< char > *canSwap=0)
void getCashedParticles (IpplParticleBase< ParticleCashedLayout< T, Dim, Mesh > > &)
void setInteractionRadius (const T &r)
T getMaxInteractionRadius ()
T getInteractionRadius (unsigned)
void setNeedGhostSwap (bool cond=true)
virtual void Repartition (UserList *)
Public Member Functions inherited from ParticleSpatialLayout< T, Dim, Mesh >
ParticleSpatialLayout (FieldLayout< Dim > &)
ParticleSpatialLayout (FieldLayout< Dim > &, Mesh &)
ParticleSpatialLayout (const RegionLayout< T, Dim, Mesh > &)
ParticleSpatialLayout ()
~ParticleSpatialLayout ()
FieldLayout< Dim > & getFieldLayout ()
RegionLayout< T, Dim, Mesh > & getLayout ()
const RegionLayout< T, Dim, Mesh > & getLayout () const
int getNodeCount (unsigned i) const
bool getEmptyNode (unsigned i) const
void update (IpplParticleBase< ParticleSpatialLayout< T, Dim, Mesh, BoxParticleCachingPolicy< T, Dim, Mesh > > > &p, const ParticleAttrib< char > *canSwap=0)
void printDebug (Inform &)
virtual void notifyUserOfDelete (UserList *)
void enableCaching ()
void disableCaching ()
Public Member Functions inherited from ParticleLayout< T, Dim >
ParticleLayout ()
~ParticleLayout ()
void setUpdateFlag (UpdateFlags f, bool val)
bool getUpdateFlag (UpdateFlags f) const
ParticleBConds< T, Dim > & getBConds ()
void setBConds (const ParticleBConds< T, Dim > &bc)
Public Member Functions inherited from FieldLayoutUser
FieldLayoutUser ()
virtual ~FieldLayoutUser ()
Public Member Functions inherited from User
User ()
virtual ~User ()
ID_t get_Id () const
Public Member Functions inherited from BoxParticleCachingPolicy< T, Dim, Mesh >
BoxParticleCachingPolicy ()
void setCacheDimension (int d, T length)
void setAllCacheDimensions (T length)
template<class C >
void updateCacheInformation (ParticleSpatialLayout< T, Dim, Mesh, C > &PLayout)
template<class C >
void updateGhostParticles (IpplParticleBase< ParticleSpatialLayout< T, Dim, Mesh, C > > &PData, ParticleSpatialLayout< T, Dim, Mesh, C > &)
Private Member Functions
void setup ()
void rebuild_interaction_data ()
void rebuild_interaction_data (const bool periodicBC[2 *Dim])
void swap_ghost_particles (unsigned, IpplParticleBase< ParticleCashedLayout< T, Dim, Mesh > > &)
void swap_ghost_particles (unsigned, IpplParticleBase< ParticleCashedLayout< T, Dim, Mesh > > &, const bool periodicBC[2 *Dim])
void setMaxInteractionRadius (T maxval)
T getMaxLocalInteractionRadius ()
Private Attributes
bool NeedGhostSwap
bool * InterNodeList
bool * SentToNodeList
unsigned InteractionNodes
T InterRadius
T MaxGlobalInterRadius
Additional Inherited Members
Protected Member Functions inherited from ParticleSpatialLayout< T, Dim, Mesh >
void setup ()
void rebuild_layout (size_t haveLocal, PB &PData)
size_t swap_particles (size_t LocalNum, PB &PData)
size_t swap_particles (size_t LocalNum, PB &PData, const ParticleAttrib< char > &canSwap)
size_t short_swap_particles (size_t LocalNum, PB &PData)
size_t new_swap_particles (size_t LocalNum, PB &PData)
size_t new_swap_particles (size_t LocalNum, PB &PData, const ParticleAttrib< char > &canSwap)
Protected Member Functions inherited from ParticleLayout< T, Dim >
template<class PPT , class NDI >
void apply_bconds (unsigned n, PPT &R, const ParticleBConds< T, Dim > &bcs, const NDI &nr)
Protected Member Functions inherited from BoxParticleCachingPolicy< T, Dim, Mesh >
~BoxParticleCachingPolicy ()
Protected Attributes inherited from ParticleSpatialLayout< T, Dim, Mesh >
RegionLayout< T, Dim, Mesh > RLayout
size_t * NodeCount
bool * EmptyNode
bool * SwapNodeList [Dim]
Message ** SwapMsgList
unsigned NeighborNodes [Dim]
std::vector< size_t > * PutList
bool caching
Protected Attributes inherited from User
ID_t Id
Detailed Description
template<class T, unsigned Dim, class Mesh = UniformCartesian<Dim,T>>
class ParticleCashedLayout< T, Dim, Mesh >
Definition at line 50 of file ParticleCashedLayout.h.
Member Typedef Documentation
Index_t
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> typedef ParticleLayout<T, Dim>::Index_t ParticleCashedLayout< T, Dim, Mesh >::Index_t
Definition at line 67 of file ParticleCashedLayout.h.
ParticleIndex_t
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> typedef ParticleInteractAttrib<Index_t> ParticleCashedLayout< T, Dim, Mesh >::ParticleIndex_t
Definition at line 71 of file ParticleCashedLayout.h.
ParticleInterRadius_t
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> typedef ParticleInteractAttrib<T> ParticleCashedLayout< T, Dim, Mesh >::ParticleInterRadius_t
Definition at line 72 of file ParticleCashedLayout.h.
ParticlePos_t
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> typedef ParticleInteractAttrib<SingleParticlePos_t> ParticleCashedLayout< T, Dim, Mesh >::ParticlePos_t
Definition at line 70 of file ParticleCashedLayout.h.
SingleParticlePos_t
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> typedef ParticleLayout<T, Dim>::SingleParticlePos_t ParticleCashedLayout< T, Dim, Mesh >::SingleParticlePos_t
Definition at line 66 of file ParticleCashedLayout.h.
Constructor & Destructor Documentation
ParticleCashedLayout() [1/4]
template<class T , unsigned Dim, class Mesh > ParticleCashedLayout< T, Dim, Mesh >::ParticleCashedLayout (FieldLayout< Dim > & fl)
Definition at line 49 of file ParticleCashedLayout.hpp.
References ParticleCashedLayout< T, Dim, Mesh >::setup().
ParticleCashedLayout() [2/4]
template<class T , unsigned Dim, class Mesh > ParticleCashedLayout< T, Dim, Mesh >::ParticleCashedLayout (FieldLayout< Dim > & fl, Mesh & mesh)
Definition at line 59 of file ParticleCashedLayout.hpp.
References ParticleCashedLayout< T, Dim, Mesh >::setup().
ParticleCashedLayout() [3/4]
template<class T , unsigned Dim, class Mesh > ParticleCashedLayout< T, Dim, Mesh >::ParticleCashedLayout (const RegionLayout< T, Dim, Mesh > & rl)
Definition at line 69 of file ParticleCashedLayout.hpp.
References ParticleCashedLayout< T, Dim, Mesh >::setup().
ParticleCashedLayout() [4/4]
template<class T , unsigned Dim, class Mesh > ParticleCashedLayout< T, Dim, Mesh >::ParticleCashedLayout ()
Definition at line 79 of file ParticleCashedLayout.hpp.
References ParticleCashedLayout< T, Dim, Mesh >::setup().
~ParticleCashedLayout()
template<class T , unsigned Dim, class Mesh > ParticleCashedLayout< T, Dim, Mesh >::~ParticleCashedLayout ()
Definition at line 105 of file ParticleCashedLayout.hpp.
Member Function Documentation
getCashedParticles()
template<class T , unsigned Dim, class Mesh > void ParticleCashedLayout< T, Dim, Mesh >::getCashedParticles (IpplParticleBase< ParticleCashedLayout< T, Dim, Mesh > > & PData)
Definition at line 128 of file ParticleCashedLayout.hpp.
References Dim, and ParticlePeriodicBCond().
getInteractionRadius()
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> T ParticleCashedLayout< T, Dim, Mesh >::getInteractionRadius (unsigned) inline
Definition at line 124 of file ParticleCashedLayout.h.
References ParticleCashedLayout< T, Dim, Mesh >::InterRadius.
getMaxInteractionRadius()
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> T ParticleCashedLayout< T, Dim, Mesh >::getMaxInteractionRadius () inline
Definition at line 121 of file ParticleCashedLayout.h.
References ParticleCashedLayout< T, Dim, Mesh >::MaxGlobalInterRadius.
getMaxLocalInteractionRadius()
template<class T , unsigned Dim, class Mesh > T ParticleCashedLayout< T, Dim, Mesh >::getMaxLocalInteractionRadius () private
Definition at line 116 of file ParticleCashedLayout.hpp.
rebuild_interaction_data() [1/2]
template<class T , unsigned Dim, class Mesh > void ParticleCashedLayout< T, Dim, Mesh >::rebuild_interaction_data () private
Definition at line 169 of file ParticleCashedLayout.hpp.
References RegionLayout< T, Dim, MeshType >::begin_iv(), Dim, RegionLayout< T, Dim, MeshType >::end_iv(), IpplInfo::getNodes(), Attrib::Legacy::Distribution::T, and RegionLayout< T, Dim, MeshType >::touch_range_rdv().
rebuild_interaction_data() [2/2]
template<class T , unsigned Dim, class Mesh > void ParticleCashedLayout< T, Dim, Mesh >::rebuild_interaction_data (const bool periodicBC[2 *Dim]) private
Definition at line 229 of file ParticleCashedLayout.hpp.
References RegionLayout< T, Dim, MeshType >::begin_iv(), Dim, RegionLayout< T, Dim, MeshType >::end_iv(), IpplInfo::getNodes(), IpplInfo::myNode(), PAssert, Attrib::Legacy::Distribution::T, RegionLayout< T, Dim, MeshType >::touch_range_rdv(), and NDRegion< T, Dim >::touches().
Repartition()
template<class T , unsigned Dim, class Mesh > void ParticleCashedLayout< T, Dim, Mesh >::Repartition (UserList * userlist) virtual
Reimplemented from ParticleSpatialLayout< T, Dim, Mesh >.
Definition at line 896 of file ParticleCashedLayout.hpp.
References UserList::getUserListID().
setInteractionRadius()
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> void ParticleCashedLayout< T, Dim, Mesh >::setInteractionRadius (const T & r) inline
Definition at line 114 of file ParticleCashedLayout.h.
References ParticleCashedLayout< T, Dim, Mesh >::InterRadius.
setMaxInteractionRadius()
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> void ParticleCashedLayout< T, Dim, Mesh >::setMaxInteractionRadius (T maxval) inline private
Definition at line 182 of file ParticleCashedLayout.h.
References ParticleCashedLayout< T, Dim, Mesh >::MaxGlobalInterRadius.
setNeedGhostSwap()
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> void ParticleCashedLayout< T, Dim, Mesh >::setNeedGhostSwap (bool cond = true) inline
Definition at line 131 of file ParticleCashedLayout.h.
References ParticleCashedLayout< T, Dim, Mesh >::NeedGhostSwap.
setup()
template<class T , unsigned Dim, class Mesh > void ParticleCashedLayout< T, Dim, Mesh >::setup (void) private
Definition at line 88 of file ParticleCashedLayout.hpp.
References IpplInfo::getNodes().
Referenced by ParticleCashedLayout< T, Dim, Mesh >::ParticleCashedLayout().
swap_ghost_particles() [1/2]
template<class T , unsigned Dim, class Mesh > void ParticleCashedLayout< T, Dim, Mesh >::swap_ghost_particles (unsigned LocalNum, IpplParticleBase< ParticleCashedLayout< T, Dim, Mesh > > & PData) private
Definition at line 526 of file ParticleCashedLayout.hpp.
References IpplInfo::getNodes(), and Attrib::Legacy::Distribution::T.
swap_ghost_particles() [2/2]
template<class T , unsigned Dim, class Mesh > void ParticleCashedLayout< T, Dim, Mesh >::swap_ghost_particles (unsigned LocalNum, IpplParticleBase< ParticleCashedLayout< T, Dim, Mesh > > & PData, const bool periodicBC[2 *Dim]) private
Definition at line 657 of file ParticleCashedLayout.hpp.
References RegionLayout< T, Dim, MeshType >::begin_iv(), IpplInfo::Comm, Communicate::COMM_ANY_NODE, Dim, RegionLayout< T, Dim, MeshType >::end_iv(), endl(), ERRORMSG, Rnode< T, Dim >::getNode(), IpplInfo::getNodes(), IpplInfo::myNode(), TagMaker::next_tag(), P_LAYOUT_CYCLE, P_SPATIAL_GHOST_TAG, PAssert, Communicate::receive_block(), Communicate::send(), Attrib::Legacy::Distribution::T, RegionLayout< T, Dim, MeshType >::touch_range_rdv(), and NDRegion< T, Dim >::touches().
update()
template<class T , unsigned Dim, class Mesh > void ParticleCashedLayout< T, Dim, Mesh >::update (IpplParticleBase< ParticleCashedLayout< T, Dim, Mesh > > & p, const ParticleAttrib< char > * canSwap = 0)
Definition at line 383 of file ParticleCashedLayout.hpp.
References Communicate::broadcast_others(), IpplInfo::Comm, Communicate::COMM_ANY_NODE, Dim, Message::get(), IpplInfo::getNodes(), IpplInfo::myNode(), TagMaker::next_tag(), P_LAYOUT_CYCLE, P_SPATIAL_LAYOUT_TAG, P_SPATIAL_RETURN_TAG, ParticlePeriodicBCond(), Message::put(), Communicate::receive_block(), Communicate::send(), SWAP, and Attrib::Legacy::Distribution::T.
Member Data Documentation
InteractionNodes
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> unsigned ParticleCashedLayout< T, Dim, Mesh >::InteractionNodes private
Definition at line 147 of file ParticleCashedLayout.h.
InterNodeList
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> bool* ParticleCashedLayout< T, Dim, Mesh >::InterNodeList private
Definition at line 145 of file ParticleCashedLayout.h.
InterRadius
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> T ParticleCashedLayout< T, Dim, Mesh >::InterRadius private
Definition at line 153 of file ParticleCashedLayout.h.
Referenced by ParticleCashedLayout< T, Dim, Mesh >::getInteractionRadius(), and ParticleCashedLayout< T, Dim, Mesh >::setInteractionRadius().
MaxGlobalInterRadius
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> T ParticleCashedLayout< T, Dim, Mesh >::MaxGlobalInterRadius private
Definition at line 153 of file ParticleCashedLayout.h.
Referenced by ParticleCashedLayout< T, Dim, Mesh >::getMaxInteractionRadius(), and ParticleCashedLayout< T, Dim, Mesh >::setMaxInteractionRadius().
NeedGhostSwap
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> bool ParticleCashedLayout< T, Dim, Mesh >::NeedGhostSwap private
Definition at line 144 of file ParticleCashedLayout.h.
Referenced by ParticleCashedLayout< T, Dim, Mesh >::setNeedGhostSwap().
SentToNodeList
template<class T , unsigned Dim, class Mesh = UniformCartesian<Dim,T>> bool* ParticleCashedLayout< T, Dim, Mesh >::SentToNodeList private
Definition at line 146 of file ParticleCashedLayout.h.
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/ParticleCashedLayout.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/ParticleCashedLayout.hpp