OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Field/Assign.hpp File Reference
Assign.hpp File Reference
#include "Field/Assign.h"
#include "Field/AssignDefs.h"
#include "Field/BareField.h"
#include "Field/BrickExpression.h"
#include "Field/IndexedBareField.h"
#include "Field/LField.h"
#include "Message/Communicate.h"
#include "Message/Message.h"
#include "Utility/PAssert.h"
#include "Utility/IpplInfo.h"
#include "Utility/IpplStats.h"
#include "PETE/IpplExpressions.h"
#include <map>
#include <vector>
#include <functional>
#include <utility>
#include <iostream>
#include <typeinfo>
Classes
class ParensIterator< Expr >
Functions
template<class T , unsigned Dim, class A , class Op >
bool TryCompressLHS (LField< T, Dim > &lf, A &rhs, Op op, const NDIndex< Dim > &domain)
template<class T1 , unsigned Dim, class RHS , class OP >
void assign (const IndexedBareField< T1, Dim, Dim > &aa, RHS b, OP op, ExprTag< true >, bool fillGC)
template<class A , class RHS , class OP , class Tag , class TP >
void assign (PETE_TUTree< OpParens< TP >, A > lhs, RHS wrhs, OP op, Tag, bool fillGC)
template<class T1 , unsigned Dim, class RHS , class OP >
void assign (const BareField< T1, Dim > &ca, RHS b, OP op, ExprTag< true >)
Function Documentation
assign() [1/3]
template<class T1 , unsigned Dim, class RHS , class OP > void assign (const IndexedBareField< T1, Dim, Dim > & aa, RHS b, OP op, ExprTag< true > , bool fillGC)
Definition at line 231 of file Assign.hpp.
References a, IpplInfo::abort(), ASSIGNMSG, LField< T, Dim >::begin(), NDIndex< Dim >::empty(), endl(), ERRORMSG, IpplInfo::extraCompressChecks, FillGCIfNecessary(), for_each(), IndexedBareField< T, Dim, Brackets >::getDomain(), LField< T, Dim >::getOwned(), INFORM_ALL_NODES, PETE_apply(), LField< T, Dim >::TryCompress(), and TryCompressLHS().
assign() [2/3]
template<class A , class RHS , class OP , class Tag , class TP > void assign (PETE_TUTree< OpParens< TP >, A > lhs, RHS wrhs, OP op, Tag , bool fillGC)
Definition at line 404 of file Assign.hpp.
References IpplInfo::abort(), Expressionize< T >::apply(), ASSIGNMSG, LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::Compress(), BareField< T, Dim >::compressible(), NDIndex< Dim >::containsAllPoints(), Dim, NDIndex< Dim >::empty(), BareField< T, Dim >::end_if(), endl(), ERRORMSG, IpplInfo::extraCompressChecks, FillGCIfNecessary(), BareField< T, Dim >::fillGuardCellsIfNotDirty(), for_each(), LField< T, Dim >::getOwned(), INFORM_ALL_NODES, NDIndex< Dim >::intersect(), LField< T, Dim >::IsCompressed(), BareField< T, Dim >::isDirty(), PETE_apply(), PETE_Expr< WrappedExpr >::PETE_unwrap(), BareField< T, Dim >::setDirtyFlag(), LField< T, Dim >::TryCompress(), and LField< T, Dim >::Uncompress().
assign() [3/3]
template<class T1 , unsigned Dim, class RHS , class OP > void assign (const BareField< T1, Dim > & ca, RHS b, OP op, ExprTag< true >)
Definition at line 566 of file Assign.hpp.
References a, ASSIGNMSG, LField< T, Dim >::begin(), endl(), IpplInfo::extraCompressChecks, for_each(), BareField< T, Dim >::getDomain(), LField< T, Dim >::getOwned(), INFORM_ALL_NODES, PETE_apply(), PETE_Expr< WrappedExpr >::PETE_unwrap(), LField< T, Dim >::TryCompress(), and TryCompressLHS().
TryCompressLHS()
template<class T , unsigned Dim, class A , class Op > bool TryCompressLHS (LField< T, Dim > & lf, A & rhs, Op op, const NDIndex< Dim > & domain)
Definition at line 48 of file Assign.hpp.
References ASSIGNMSG, LField< T, Dim >::begin(), LField< T, Dim >::Compress(), NDIndex< Dim >::containsAllPoints(), endl(), for_each(), LField< T, Dim >::getOwned(), INFORM_ALL_NODES, LField< T, Dim >::IsCompressed(), IpplInfo::noFieldCompression, PETE_apply(), Attrib::Legacy::Distribution::T, and LField< T, Dim >::Uncompress().
Referenced by assign().