OPAL (Object Oriented Parallel Accelerator Library): AntiSymTenzor< T, 1 > Class Template Reference
AntiSymTenzor< T, 1 > Class Template Reference
#include <AntiSymTenzor.h>
Classes
class AssignProxy
class DontInitialize
Public Types
enum { ElemDim = 2 }
typedef T Element_t
Public Member Functions
AntiSymTenzor ()
AntiSymTenzor (const AntiSymTenzor< T, 1 > &)
AntiSymTenzor (DontInitialize)
AntiSymTenzor (const Tenzor< T, 1 > &)
~AntiSymTenzor ()
const AntiSymTenzor< T, 1 > & operator= (const AntiSymTenzor< T, 1 > &)
template<class T1 >
const AntiSymTenzor< T, 1 > & operator= (const AntiSymTenzor< T1, 1 > &)
const AntiSymTenzor< T, 1 > & operator= (const T &rhs)
template<class T1 >
AntiSymTenzor< T, 1 > & operator+= (const AntiSymTenzor< T1, 1 > &)
template<class T1 >
AntiSymTenzor< T, 1 > & operator-= (const AntiSymTenzor< T1, 1 > &)
template<class T1 >
AntiSymTenzor< T, 1 > & operator*= (const AntiSymTenzor< T1, 1 > &)
AntiSymTenzor< T, 1 > & operator*= (const T &)
template<class T1 >
AntiSymTenzor< T, 1 > & operator/= (const AntiSymTenzor< T1, 1 > &)
AntiSymTenzor< T, 1 > & operator/= (const T &)
int len (void) const
int size (void) const
int get_Size (void) const
Element_t operator() (unsigned int i, unsigned int j) const
Element_t operator() (std::pair< int, int > a) const
AssignProxy operator() (unsigned int i, unsigned int j)
AssignProxy operator() (std::pair< int, int > a)
Element_t operator[] (unsigned int i) const
Element_t operator() (unsigned int i) const
bool operator== (const AntiSymTenzor< T, 1 > &) const
bool operator!= (const AntiSymTenzor< T, 1 > &that) const
Message & putMessage (Message &m) const
Message & getMessage (Message &m)
Private Types
enum { Size = 0 }
Static Private Attributes
static T Zero
Friends
class AssignProxy
Detailed Description
template<class T>
class AntiSymTenzor< T, 1 >
Definition at line 281 of file AntiSymTenzor.h.
Member Typedef Documentation
Element_t
template<class T > typedef T AntiSymTenzor< T, 1 >::Element_t
Definition at line 285 of file AntiSymTenzor.h.
Member Enumeration Documentation
anonymous enum
template<class T > anonymous enum
Enumerator
ElemDim
Definition at line 286 of file AntiSymTenzor.h.
anonymous enum
template<class T > anonymous enum private
Enumerator
Size
Definition at line 450 of file AntiSymTenzor.h.
Constructor & Destructor Documentation
AntiSymTenzor() [1/4]
template<class T > AntiSymTenzor< T, 1 >::AntiSymTenzor () inline
Definition at line 289 of file AntiSymTenzor.h.
AntiSymTenzor() [2/4]
template<class T > AntiSymTenzor< T, 1 >::AntiSymTenzor (const AntiSymTenzor< T, 1 > &) inline
Definition at line 292 of file AntiSymTenzor.h.
AntiSymTenzor() [3/4]
template<class T > AntiSymTenzor< T, 1 >::AntiSymTenzor (DontInitialize) inline
Definition at line 296 of file AntiSymTenzor.h.
AntiSymTenzor() [4/4]
template<class T > AntiSymTenzor< T, 1 >::AntiSymTenzor (const Tenzor< T, 1 > &) inline
Definition at line 299 of file AntiSymTenzor.h.
~AntiSymTenzor()
template<class T > AntiSymTenzor< T, 1 >::~AntiSymTenzor () inline
Definition at line 301 of file AntiSymTenzor.h.
Member Function Documentation
get_Size()
template<class T > int AntiSymTenzor< T, 1 >::get_Size (void) const inline
Definition at line 347 of file AntiSymTenzor.h.
References AntiSymTenzor< T, D >::Size.
getMessage()
template<class T > Message& AntiSymTenzor< T, 1 >::getMessage (Message & m) inline
Definition at line 439 of file AntiSymTenzor.h.
References Message::get(), and Attrib::Legacy::Distribution::T.
len()
template<class T > int AntiSymTenzor< T, 1 >::len (void) const inline
Definition at line 345 of file AntiSymTenzor.h.
References AntiSymTenzor< T, D >::Size.
operator!=()
template<class T > bool AntiSymTenzor< T, 1 >::operator!= (const AntiSymTenzor< T, 1 > & that) const inline
Definition at line 427 of file AntiSymTenzor.h.
operator()() [1/5]
template<class T > Element_t AntiSymTenzor< T, 1 >::operator() (unsigned int i, unsigned int j) const inline
Definition at line 381 of file AntiSymTenzor.h.
References PAssert_EQ, and Attrib::Legacy::Distribution::T.
operator()() [2/5]
template<class T > Element_t AntiSymTenzor< T, 1 >::operator() (std::pair< int, int > a) const inline
Definition at line 390 of file AntiSymTenzor.h.
References a.
operator()() [3/5]
template<class T > AssignProxy AntiSymTenzor< T, 1 >::operator() (unsigned int i, unsigned int j) inline
Definition at line 396 of file AntiSymTenzor.h.
References AntiSymTenzor< T, D >::AssignProxy, and PAssert_EQ.
operator()() [4/5]
template<class T > AssignProxy AntiSymTenzor< T, 1 >::operator() (std::pair< int, int > a) inline
Definition at line 402 of file AntiSymTenzor.h.
References a.
operator()() [5/5]
template<class T > Element_t AntiSymTenzor< T, 1 >::operator() (unsigned int i) const inline
Definition at line 416 of file AntiSymTenzor.h.
References PAssert.
operator*=() [1/2]
template<class T > template<class T1 > AntiSymTenzor<T,1>& AntiSymTenzor< T, 1 >::operator*= (const AntiSymTenzor< T1, 1 > &) inline
Definition at line 328 of file AntiSymTenzor.h.
operator*=() [2/2]
template<class T > AntiSymTenzor<T,1>& AntiSymTenzor< T, 1 >::operator*= (const T &) inline
Definition at line 331 of file AntiSymTenzor.h.
operator+=()
template<class T > template<class T1 > AntiSymTenzor<T,1>& AntiSymTenzor< T, 1 >::operator+= (const AntiSymTenzor< T1, 1 > &) inline
Definition at line 318 of file AntiSymTenzor.h.
operator-=()
template<class T > template<class T1 > AntiSymTenzor<T,1>& AntiSymTenzor< T, 1 >::operator-= (const AntiSymTenzor< T1, 1 > &) inline
Definition at line 323 of file AntiSymTenzor.h.
operator/=() [1/2]
template<class T > template<class T1 > AntiSymTenzor<T,1>& AntiSymTenzor< T, 1 >::operator/= (const AntiSymTenzor< T1, 1 > &) inline
Definition at line 336 of file AntiSymTenzor.h.
operator/=() [2/2]
template<class T > AntiSymTenzor<T,1>& AntiSymTenzor< T, 1 >::operator/= (const T &) inline
Definition at line 339 of file AntiSymTenzor.h.
operator=() [1/3]
template<class T > const AntiSymTenzor<T,1>& AntiSymTenzor< T, 1 >::operator= (const AntiSymTenzor< T, 1 > &) inline
Definition at line 304 of file AntiSymTenzor.h.
operator=() [2/3]
template<class T > template<class T1 > const AntiSymTenzor<T,1>& AntiSymTenzor< T, 1 >::operator= (const AntiSymTenzor< T1, 1 > &) inline
Definition at line 308 of file AntiSymTenzor.h.
operator=() [3/3]
template<class T > const AntiSymTenzor<T,1>& AntiSymTenzor< T, 1 >::operator= (const T & rhs) inline
Definition at line 311 of file AntiSymTenzor.h.
References PInsist.
operator==()
template<class T > bool AntiSymTenzor< T, 1 >::operator== (const AntiSymTenzor< T, 1 > &) const inline
Definition at line 424 of file AntiSymTenzor.h.
operator[]()
template<class T > Element_t AntiSymTenzor< T, 1 >::operator[] (unsigned int i) const inline
Definition at line 408 of file AntiSymTenzor.h.
References PAssert.
putMessage()
template<class T > Message& AntiSymTenzor< T, 1 >::putMessage (Message & m) const inline
Definition at line 433 of file AntiSymTenzor.h.
References Message::put(), and Message::setCopy().
size()
template<class T > int AntiSymTenzor< T, 1 >::size (void) const inline
Definition at line 346 of file AntiSymTenzor.h.
Friends And Related Function Documentation
AssignProxy
template<class T > friend class AssignProxy friend
Definition at line 447 of file AntiSymTenzor.h.
Member Data Documentation
Zero
template<class T > T AntiSymTenzor< T, 1 >::Zero static private
Definition at line 455 of file AntiSymTenzor.h.
The documentation for this class was generated from the following file:
ippl/src/AppTypes/AntiSymTenzor.h