OPAL (Object Oriented Parallel Accelerator Library): _FM1DDynamic Class Reference
_FM1DDynamic Class Reference
#include <FM1DDynamic.h>
Public Member Functions
virtual ~_FM1DDynamic ()
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const
virtual bool getFieldDerivative (const Vector_t &R, Vector_t &E, Vector_t &B, const DiffDirection &dir) const
virtual void getFieldDimensions (double &zBegin, double &zEnd) const
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const
virtual void swap ()
virtual void getInfo (Inform *)
virtual double getFrequency () const
virtual void setFrequency (double freq)
virtual void getOnaxisEz (std::vector< std::pair< double, double >> &eZ)
virtual bool isInside (const Vector_t &r) const
Public Member Functions inherited from _Fieldmap
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &onaxis)
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Private Member Functions
_FM1DDynamic (const std::string &filename)
virtual void readMap ()
virtual void freeMap ()
bool checkFileData (std::ifstream &fieldFile, bool parsingPassed)
void computeFieldOffAxis (const Vector_t &R, Vector_t &E, Vector_t &B, std::vector< double > fieldComponents) const
void computeFieldOnAxis (double z, std::vector< double > &fieldComponents) const
void computeFourierCoefficients (double maxEz, double fieldData[])
void convertHeaderData ()
double readFileData (std::ifstream &fieldFile, double fieldData[])
double readFileData (std::ifstream &fieldFile, std::vector< std::pair< double, double >> &eZ)
bool readFileHeader (std::ifstream &fieldFile)
void scaleField (double maxEz, std::vector< std::pair< double, double >> &eZ)
void stripFileHeader (std::ifstream &fieldFile)
Static Private Member Functions
static FM1DDynamic create (const std::string &filename)
Private Attributes
double frequency_m
double twoPiOverLambdaSq_m
Field angular frequency (Hz).
double rBegin_m
2 Pi divided by the field RF wavelength squared.
double rEnd_m
Minimum radius of field.
double zBegin_m
Maximum radius of field.
double zEnd_m
Longitudinal start of field.
double length_m
Longitudinal end of field.
int numberOfGridPoints_m
Field length.
int accuracy_m
Number of grid points in field input file.
std::vector< double > fourierCoefs_m
Number of Fourier coefficients to use reconstructing field.
Friends
class _Fieldmap
Fourier coefficients derived from field map.
Additional Inherited Members
Static Public Member Functions inherited from _Fieldmap
static Fieldmap getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions inherited from _Fieldmap
_Fieldmap ()=delete
_Fieldmap (const std::string &filename)
virtual ~_Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions inherited from _Fieldmap
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes inherited from _Fieldmap
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Detailed Description
Definition at line 6 of file FM1DDynamic.h.
Constructor & Destructor Documentation
~_FM1DDynamic()
_FM1DDynamic::~_FM1DDynamic () virtual
Definition at line 41 of file FM1DDynamic.cpp.
References freeMap().
_FM1DDynamic()
_FM1DDynamic::_FM1DDynamic (const std::string & filename) private
Definition at line 13 of file FM1DDynamic.cpp.
References checkFileData(), convertHeaderData(), _Fieldmap::disableFieldmapWarning(), Physics::e, _Fieldmap::Filename_m, length_m, _Fieldmap::noFieldmapWarning(), numberOfGridPoints_m, readFileHeader(), T1DDynamic, _Fieldmap::Type, zBegin_m, and zEnd_m.
Referenced by create().
Member Function Documentation
checkFileData()
bool _FM1DDynamic::checkFileData (std::ifstream & fieldFile, bool parsingPassed) private
Definition at line 145 of file FM1DDynamic.cpp.
References _Fieldmap::interpreteEOF(), and numberOfGridPoints_m.
Referenced by _FM1DDynamic().
computeFieldOffAxis()
void _FM1DDynamic::computeFieldOffAxis (const Vector_t & R, Vector_t & E, Vector_t & B, std::vector< double > fieldComponents) const private
Definition at line 156 of file FM1DDynamic.cpp.
References frequency_m, pow(), Attrib::Distribution::R, and twoPiOverLambdaSq_m.
Referenced by getFieldstrength().
computeFieldOnAxis()
void _FM1DDynamic::computeFieldOnAxis (double z, std::vector< double > & fieldComponents) const private
Definition at line 181 of file FM1DDynamic.cpp.
References accuracy_m, cos(), fourierCoefs_m, length_m, Hypervolume::n, Physics::pi, pow(), sin(), and Physics::two_pi.
Referenced by getFieldstrength().
computeFourierCoefficients()
void _FM1DDynamic::computeFourierCoefficients (double maxEz, double fieldData[]) private
Definition at line 214 of file FM1DDynamic.cpp.
References accuracy_m, fourierCoefs_m, numberOfGridPoints_m, and Units::Vpm2MVpm.
Referenced by readMap().
convertHeaderData()
void _FM1DDynamic::convertHeaderData () private
Definition at line 235 of file FM1DDynamic.cpp.
References Physics::c, Units::cm2m, frequency_m, Units::MHz2Hz, pow(), rBegin_m, rEnd_m, Physics::two_pi, twoPiOverLambdaSq_m, zBegin_m, and zEnd_m.
Referenced by _FM1DDynamic().
create()
FM1DDynamic _FM1DDynamic::create (const std::string & filename) static private
Definition at line 45 of file FM1DDynamic.cpp.
References _FM1DDynamic().
Referenced by _Fieldmap::getFieldmap().
freeMap()
void _FM1DDynamic::freeMap () private virtual
Implements _Fieldmap.
Definition at line 66 of file FM1DDynamic.cpp.
References fourierCoefs_m.
Referenced by ~_FM1DDynamic().
getFieldDerivative()
bool _FM1DDynamic::getFieldDerivative (const Vector_t & R, Vector_t & E, Vector_t & B, const DiffDirection & dir) const virtual
Implements _Fieldmap.
Definition at line 83 of file FM1DDynamic.cpp.
References accuracy_m, cos(), fourierCoefs_m, length_m, Hypervolume::n, Physics::pi, Attrib::Distribution::R, sin(), Physics::two_pi, and zBegin_m.
getFieldDimensions() [1/2]
void _FM1DDynamic::getFieldDimensions (double & zBegin, double & zEnd) const virtual
Implements _Fieldmap.
Definition at line 106 of file FM1DDynamic.cpp.
References zBegin_m, and zEnd_m.
getFieldDimensions() [2/2]
void _FM1DDynamic::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const virtual
Implements _Fieldmap.
Definition at line 111 of file FM1DDynamic.cpp.
getFieldstrength()
bool _FM1DDynamic::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const virtual
Implements _Fieldmap.
Definition at line 73 of file FM1DDynamic.cpp.
References computeFieldOffAxis(), computeFieldOnAxis(), Attrib::Distribution::R, and zBegin_m.
getFrequency()
double _FM1DDynamic::getFrequency () const virtual
Implements _Fieldmap.
Definition at line 126 of file FM1DDynamic.cpp.
References frequency_m.
getInfo()
void _FM1DDynamic::getInfo (Inform * msg) virtual
Implements _Fieldmap.
Definition at line 119 of file FM1DDynamic.cpp.
References endl(), _Fieldmap::Filename_m, zBegin_m, and zEnd_m.
getOnaxisEz()
void _FM1DDynamic::getOnaxisEz (std::vector< std::pair< double, double >> & eZ) virtual
Definition at line 134 of file FM1DDynamic.cpp.
References _Fieldmap::Filename_m, numberOfGridPoints_m, readFileData(), scaleField(), and stripFileHeader().
isInside()
bool _FM1DDynamic::isInside (const Vector_t & r) const inline virtual
Reimplemented from _Fieldmap.
Definition at line 62 of file FM1DDynamic.h.
References zBegin_m, and zEnd_m.
readFileData() [1/2]
double _FM1DDynamic::readFileData (std::ifstream & fieldFile, double fieldData[]) private
Definition at line 249 of file FM1DDynamic.cpp.
References abs(), _Fieldmap::normalize_m, and numberOfGridPoints_m.
Referenced by getOnaxisEz(), and readMap().
readFileData() [2/2]
double _FM1DDynamic::readFileData (std::ifstream & fieldFile, std::vector< std::pair< double, double >> & eZ) private
Definition at line 273 of file FM1DDynamic.cpp.
References abs(), _Fieldmap::normalize_m, numberOfGridPoints_m, zBegin_m, and zEnd_m.
readFileHeader()
bool _FM1DDynamic::readFileHeader (std::ifstream & fieldFile) private
Definition at line 291 of file FM1DDynamic.cpp.
References accuracy_m, Physics::e, frequency_m, _Fieldmap::normalize_m, numberOfGridPoints_m, rBegin_m, rEnd_m, Util::toUpper(), zBegin_m, and zEnd_m.
Referenced by _FM1DDynamic().
readMap()
void _FM1DDynamic::readMap () private virtual
Implements _Fieldmap.
Definition at line 49 of file FM1DDynamic.cpp.
References computeFourierCoefficients(), endl(), _Fieldmap::Filename_m, fourierCoefs_m, INFOMSG, numberOfGridPoints_m, readFileData(), stripFileHeader(), and _Fieldmap::typeset_msg().
scaleField()
void _FM1DDynamic::scaleField (double maxEz, std::vector< std::pair< double, double >> & eZ) private
Definition at line 338 of file FM1DDynamic.cpp.
References numberOfGridPoints_m.
Referenced by getOnaxisEz().
setFrequency()
void _FM1DDynamic::setFrequency (double freq) virtual
Implements _Fieldmap.
Definition at line 130 of file FM1DDynamic.cpp.
References frequency_m.
stripFileHeader()
void _FM1DDynamic::stripFileHeader (std::ifstream & fieldFile) private
Definition at line 343 of file FM1DDynamic.cpp.
References _Fieldmap::getLine().
Referenced by getOnaxisEz(), and readMap().
swap()
void _FM1DDynamic::swap () virtual
Implements _Fieldmap.
Definition at line 116 of file FM1DDynamic.cpp.
Friends And Related Function Documentation
_Fieldmap
friend class _Fieldmap friend
Fourier coefficients derived from field map.
Definition at line 59 of file FM1DDynamic.h.
Member Data Documentation
accuracy_m
int _FM1DDynamic::accuracy_m private
Number of grid points in field input file.
Definition at line 56 of file FM1DDynamic.h.
Referenced by computeFieldOnAxis(), computeFourierCoefficients(), getFieldDerivative(), and readFileHeader().
fourierCoefs_m
std::vector<double> _FM1DDynamic::fourierCoefs_m private
Number of Fourier coefficients to use reconstructing field.
Definition at line 57 of file FM1DDynamic.h.
Referenced by computeFieldOnAxis(), computeFourierCoefficients(), freeMap(), getFieldDerivative(), and readMap().
frequency_m
double _FM1DDynamic::frequency_m private
Definition at line 46 of file FM1DDynamic.h.
Referenced by computeFieldOffAxis(), convertHeaderData(), getFrequency(), readFileHeader(), and setFrequency().
length_m
double _FM1DDynamic::length_m private
Longitudinal end of field.
Definition at line 53 of file FM1DDynamic.h.
Referenced by _FM1DDynamic(), computeFieldOnAxis(), and getFieldDerivative().
numberOfGridPoints_m
int _FM1DDynamic::numberOfGridPoints_m private
Field length.
Definition at line 54 of file FM1DDynamic.h.
Referenced by _FM1DDynamic(), checkFileData(), computeFourierCoefficients(), getOnaxisEz(), readFileData(), readFileHeader(), readMap(), and scaleField().
rBegin_m
double _FM1DDynamic::rBegin_m private
2 Pi divided by the field RF wavelength squared.
Definition at line 49 of file FM1DDynamic.h.
Referenced by convertHeaderData(), and readFileHeader().
rEnd_m
double _FM1DDynamic::rEnd_m private
Minimum radius of field.
Definition at line 50 of file FM1DDynamic.h.
Referenced by convertHeaderData(), and readFileHeader().
twoPiOverLambdaSq_m
double _FM1DDynamic::twoPiOverLambdaSq_m private
Field angular frequency (Hz).
Definition at line 47 of file FM1DDynamic.h.
Referenced by computeFieldOffAxis(), and convertHeaderData().
zBegin_m
double _FM1DDynamic::zBegin_m private
Maximum radius of field.
Definition at line 51 of file FM1DDynamic.h.
Referenced by _FM1DDynamic(), convertHeaderData(), getFieldDerivative(), getFieldDimensions(), getFieldstrength(), getInfo(), isInside(), readFileData(), and readFileHeader().
zEnd_m
double _FM1DDynamic::zEnd_m private
Longitudinal start of field.
Definition at line 52 of file FM1DDynamic.h.
Referenced by _FM1DDynamic(), convertHeaderData(), getFieldDimensions(), getInfo(), isInside(), readFileData(), and readFileHeader().
The documentation for this class was generated from the following files:
src/Classic/Fields/FM1DDynamic.h
src/Classic/Fields/FM1DDynamic.cpp