OPAL (Object Oriented Parallel Accelerator Library): MaxNormRadialPeak Struct Reference
MaxNormRadialPeak Struct Reference
#include <MaxNormRadialPeak.h>
Public Member Functions
Expressions::Result_t operator() (client::function::arguments_t args)
Static Public Attributes
static const std::string name
Private Attributes
std::string meas_filename_
std::string sim_filename_
int begin_
int end_
boost::tuple< std::string, std::string, int, int > argument_types
Detailed Description
Definition at line 46 of file MaxNormRadialPeak.h.
Member Function Documentation
operator()()
Expressions::Result_t MaxNormRadialPeak::operator() (client::function::arguments_t args) inline
Definition at line 50 of file MaxNormRadialPeak.h.
References abs(), begin_, Physics::e, end_, endl(), max(), meas_filename_, sim_filename_, and OptPilotException::what().
Member Data Documentation
argument_types
boost::tuple<std::string, std::string, int, int> MaxNormRadialPeak::argument_types private
Definition at line 105 of file MaxNormRadialPeak.h.
begin_
int MaxNormRadialPeak::begin_ private
Definition at line 101 of file MaxNormRadialPeak.h.
Referenced by operator()().
end_
int MaxNormRadialPeak::end_ private
Definition at line 102 of file MaxNormRadialPeak.h.
Referenced by operator()().
meas_filename_
std::string MaxNormRadialPeak::meas_filename_ private
Definition at line 99 of file MaxNormRadialPeak.h.
Referenced by operator()().
name
const std::string MaxNormRadialPeak::name static
Definition at line 48 of file MaxNormRadialPeak.h.
sim_filename_
std::string MaxNormRadialPeak::sim_filename_ private
Definition at line 100 of file MaxNormRadialPeak.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/optimizer/Expression/MaxNormRadialPeak.h