OPAL (Object Oriented Parallel Accelerator Library): PortableGraymapReader Class Reference
PortableGraymapReader Class Reference
#include <PortableGraymapReader.h>
Public Member Functions
PortableGraymapReader (const std::string &input)
unsigned int getWidth () const
unsigned int getHeight () const
unsigned short getPixel (unsigned int i, unsigned int j) const
std::vector< unsigned short > getPixels () const
void print (std::ostream &out) const
Private Types
enum FileType { ASCII, BINARY }
Private Member Functions
void readHeader (std::istream &in)
void readImageAscii (std::istream &in)
void readImageBinary (std::istream &in)
std::string getNextPart (std::istream &in)
unsigned int getIdx (unsigned int h, unsigned int w) const
Private Attributes
unsigned int width_m
unsigned int height_m
unsigned short depth_m
FileType type_m
std::vector< unsigned short > pixels_m
Detailed Description
Definition at line 10 of file PortableGraymapReader.h.
Member Enumeration Documentation
FileType
enum PortableGraymapReader::FileType private
Enumerator
ASCII
BINARY
Definition at line 33 of file PortableGraymapReader.h.
Constructor & Destructor Documentation
PortableGraymapReader()
PortableGraymapReader::PortableGraymapReader (const std::string & input)
Definition at line 9 of file PortableGraymapReader.cpp.
References ASCII, height_m, pixels_m, readHeader(), readImageAscii(), readImageBinary(), type_m, and width_m.
Member Function Documentation
getHeight()
unsigned int PortableGraymapReader::getHeight () const inline
Definition at line 49 of file PortableGraymapReader.h.
References height_m.
Referenced by LaserProfile::readPGMFile().
getIdx()
unsigned int PortableGraymapReader::getIdx (unsigned int h, unsigned int w) const inline private
Definition at line 64 of file PortableGraymapReader.h.
References height_m, and width_m.
Referenced by getPixel(), and print().
getNextPart()
std::string PortableGraymapReader::getNextPart (std::istream & in) private
Definition at line 22 of file PortableGraymapReader.cpp.
References Physics::c.
Referenced by readHeader().
getPixel()
unsigned short PortableGraymapReader::getPixel (unsigned int i, unsigned int j) const inline
Definition at line 54 of file PortableGraymapReader.h.
References getIdx(), and pixels_m.
Referenced by LaserProfile::readPGMFile().
getPixels()
std::vector< unsigned short > PortableGraymapReader::getPixels () const inline
Definition at line 59 of file PortableGraymapReader.h.
References pixels_m.
getWidth()
unsigned int PortableGraymapReader::getWidth () const inline
Definition at line 44 of file PortableGraymapReader.h.
References width_m.
Referenced by LaserProfile::readPGMFile().
print()
void PortableGraymapReader::print (std::ostream & out) const
Definition at line 115 of file PortableGraymapReader.cpp.
References endl(), getIdx(), height_m, pixels_m, and width_m.
readHeader()
void PortableGraymapReader::readHeader (std::istream & in) private
Definition at line 44 of file PortableGraymapReader.cpp.
References ASCII, BINARY, depth_m, getNextPart(), height_m, type_m, and width_m.
Referenced by PortableGraymapReader().
readImageAscii()
void PortableGraymapReader::readImageAscii (std::istream & in) private
Definition at line 81 of file PortableGraymapReader.cpp.
References Physics::c, height_m, pixels_m, and width_m.
Referenced by PortableGraymapReader().
readImageBinary()
void PortableGraymapReader::readImageBinary (std::istream & in) private
Definition at line 93 of file PortableGraymapReader.cpp.
References Physics::c, depth_m, height_m, pixels_m, and width_m.
Referenced by PortableGraymapReader().
Member Data Documentation
depth_m
unsigned short PortableGraymapReader::depth_m private
Definition at line 31 of file PortableGraymapReader.h.
Referenced by readHeader(), and readImageBinary().
height_m
unsigned int PortableGraymapReader::height_m private
Definition at line 30 of file PortableGraymapReader.h.
Referenced by getHeight(), getIdx(), PortableGraymapReader(), print(), readHeader(), readImageAscii(), and readImageBinary().
pixels_m
std::vector<unsigned short> PortableGraymapReader::pixels_m private
Definition at line 40 of file PortableGraymapReader.h.
Referenced by getPixel(), getPixels(), PortableGraymapReader(), print(), readImageAscii(), and readImageBinary().
type_m
FileType PortableGraymapReader::type_m private
Definition at line 38 of file PortableGraymapReader.h.
Referenced by PortableGraymapReader(), and readHeader().
width_m
unsigned int PortableGraymapReader::width_m private
Definition at line 29 of file PortableGraymapReader.h.
Referenced by getIdx(), getWidth(), PortableGraymapReader(), print(), readHeader(), readImageAscii(), and readImageBinary().
The documentation for this class was generated from the following files:
src/Classic/Utilities/PortableGraymapReader.h
src/Classic/Utilities/PortableGraymapReader.cpp