OPAL (Object Oriented Parallel Accelerator Library): Constraint Class Reference
Constraint Class Reference
#include <Constraint.h>
Public Member Functions
Constraint ()
~Constraint ()
virtual Constraint * clone (const std::string &name)
Return a clone.
virtual void execute ()
Execute the command.
std::string getExpression () const
Public Member Functions inherited from Definition
virtual ~Definition ()
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
Constraint (const std::string &name, Constraint *parent)
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Definition
Definition (int size, const char *name, const char *help)
Constructor for exemplars.
Definition (const std::string &name, Definition *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 6 of file Constraint.h.
Constructor & Destructor Documentation
Constraint() [1/2]
Constraint::Constraint ()
Definition at line 11 of file Constraint.cpp.
References Object::itsAttr, Attributes::makeString(), Object::registerOwnership(), and AttributeHandler::STATEMENT.
Referenced by clone().
~Constraint()
Constraint::~Constraint ()
Definition at line 24 of file Constraint.cpp.
Constraint() [2/2]
Constraint::Constraint (const std::string & name, Constraint * parent) private
Definition at line 20 of file Constraint.cpp.
Member Function Documentation
clone()
Constraint * Constraint::clone (const std::string & name) inline virtual
Return a clone.
Implements Object.
Definition at line 22 of file Constraint.h.
References Constraint(), and name.
execute()
void Constraint::execute () virtual
Execute the command.
Reimplemented from Object.
Definition at line 27 of file Constraint.cpp.
getExpression()
std::string Constraint::getExpression () const
Definition at line 31 of file Constraint.cpp.
References Attributes::getString(), and Object::itsAttr.
Referenced by OptimizeCmd::execute().
The documentation for this class was generated from the following files:
src/Optimize/Constraint.h
src/Optimize/Constraint.cpp