OPAL (Object Oriented Parallel Accelerator Library): Tps< T > Class Template Reference
Tps< T > Class Template Reference
Truncated power series.
#include <Tps.h>
Public Member Functions
Tps (int maxOrder, int nVar)
Constructor.
Tps (const T &y)
Conversion.
Tps (int y)
Conversion.
Tps ()
Tps (const Tps< T > &x)
~Tps ()
Tps< T > & operator= (const Tps< T > &y)
Tps< T > & operator= (const T &y)
Convert and assign.
Tps< T > filter (int lowOrder, int highOrder) const
Extract orders.
Tps< T > truncate (int trunc)
Truncate.
const T getCoefficient (int index) const
Get coefficient.
void setCoefficient (int index, const T &value)
Set coefficient.
const T getCoefficient (const TpsMonomial &monomial) const
Get coefficient.
void setCoefficient (const TpsMonomial &monomial, const T &value)
Set coefficient.
const T operator[] (int index) const
Get coefficient.
T & operator[] (int index)
Get coefficient.
const T operator[] (const TpsMonomial &monomial) const
Get coefficient.
T & operator[] (const TpsMonomial &monomial)
Get coefficient.
Tps< T > operator+ () const
Unary plus.
Tps< T > operator- () const
Unary minus.
Tps< T > & operator+= (const Tps< T > &y)
Add and assign.
Tps< T > & operator-= (const Tps< T > &y)
Subtract and assign.
Tps< T > & operator*= (const Tps< T > &y)
Multiply and assign.
Tps< T > & operator/= (const Tps< T > &y)
Divide and assign.
Tps< T > & operator+= (const T &y)
Add constant and assign.
Tps< T > & operator-= (const T &y)
Subtract constant and assign.
Tps< T > & operator*= (const T &y)
Multiply by constant and assign.
Tps< T > & operator/= (const T &y)
Divide by constant and assign.
bool operator== (const Tps< T > &y) const
Equality operator.
bool operator== (const T &y) const
Equlatity with constant.
bool operator!= (const Tps< T > &y) const
Inequality operator.
bool operator!= (const T &y) const
Inequality with constant.
Tps< T > substitute (const Matrix< T > &M) const
Substitute.
Tps< T > substitute (const VpsMap< T > &m) const
Substitute.
T evaluate (const Vector< T > &v) const
Substitute.
void clear ()
Set to zero.
Tps< T > inverse (int order=truncOrder) const
Reciprocal value.
Tps< T > multiply (const Tps< T > &y, int trunc) const
Truncated multiplication.
Tps< T > derivative (int var) const
Partial derivative.
Tps< T > integral (int var) const
Partial integral.
Tps< T > multiplyVariable (int var) const
Multiply by variable [b]var[/b].
Tps< T > scaleMonomials (const Tps< T > &y) const
Multiply monomial-wise.
Tps< T > Taylor (const T series[], int n) const
Taylor series.
int getMaxOrder () const
Get maximal order.
int getTruncOrder () const
Get truncation order.
int getVariables () const
Get number of variables.
int getSize () const
Get number of coefficients.
std::istream & get (std::istream &is)
Get Tps from the stream is.
std::ostream & put (std::ostream &os) const
Put Tps to the stream is.
const TpsMonomial & getExponents (int index) const
Get exponents.
int getOrder (int index) const
Get order.
int getSize (int order) const
Size.
bool isConstant () const
Test for constant.
Static Public Member Functions
static Tps< T > makeVariable (int nVar, int var)
Make variable.
static Tps< T > makeVarPower (int nVar, int var, int power)
Make power.
static Tps< T > makeMonomial (const TpsMonomial &m, const T &t)
Make monomial.
static int getGlobalTruncOrder ()
Get global truncation order.
static void setGlobalTruncOrder (int order)
Set global truncation order.
Static Public Attributes
static const int EXACT = INT_MAX
Representation of infinite precision.
Private Member Functions
Tps (TpsRep< T > *)
void setMaxOrder (int)
void unique ()
Private Attributes
TpsRep< T > * rep
Static Private Attributes
static int truncOrder = EXACT
Detailed Description
template<class T>
class Tps< T >
Truncated power series.
Definition at line 27 of file Tps.h.
Constructor & Destructor Documentation
Tps() [1/6]
template<class T > Tps< T >::Tps (int maxOrder, int nVar)
Constructor.
Definition at line 227 of file Tps.hpp.
Tps() [2/6]
template<class T > Tps< T >::Tps (const T & y)
Conversion.
Definition at line 239 of file Tps.hpp.
References Tps< T >::rep.
Tps() [3/6]
template<class T > Tps< T >::Tps (int y)
Conversion.
Definition at line 246 of file Tps.hpp.
References Tps< T >::rep, and Attrib::Legacy::Distribution::T.
Tps() [4/6]
template<class T > Tps< T >::Tps ()
Definition at line 221 of file Tps.hpp.
Tps() [5/6]
template<class T > Tps< T >::Tps (const Tps< T > & x)
Definition at line 233 of file Tps.hpp.
~Tps()
template<class T > Tps< T >::~Tps ()
Definition at line 253 of file Tps.hpp.
References TpsRep< T >::release(), and Tps< T >::rep.
Tps() [6/6]
template<class T > Tps< T >::Tps (TpsRep< T > * d) inline private
Definition at line 1096 of file Tps.hpp.
Member Function Documentation
clear()
template<class T > void Tps< T >::clear ()
Set to zero.
Definition at line 714 of file Tps.hpp.
References TpsRep< T >::release(), Tps< T >::rep, and TpsRep< T >::zero().
derivative()
template<class T > Tps< T > Tps< T >::derivative (int var) const
Partial derivative.
Definition at line 920 of file Tps.hpp.
References TpsRep< T >::create(), TpsRep< T >::data(), Tps< T >::getExponents(), Tps< T >::getMaxOrder(), Tps< T >::getSize(), Tps< T >::getTruncOrder(), Tps< T >::getVariables(), Tps< T >::rep, and Attrib::Legacy::Distribution::T.
evaluate()
template<class T > T Tps< T >::evaluate (const Vector< T > & v) const
Substitute.
Definition at line 686 of file Tps.hpp.
References Tps< T >::getMaxOrder(), Tps< T >::getVariables(), TpsSubstitution::index, TpsSubstitution::order, Tps< T >::rep, Array1D< T >::size(), TpsSubstitution::skip, Attrib::Legacy::Distribution::T, and TpsSubstitution::variable.
filter()
template<class T > Tps< T > Tps< T >::filter (int lowOrder, int highOrder) const
Extract orders.
Definition at line 279 of file Tps.hpp.
References TpsRep< T >::create(), TpsRep< T >::data(), Tps< T >::getMaxOrder(), Tps< T >::getSize(), Tps< T >::getTruncOrder(), Tps< T >::getVariables(), min(), and Tps< T >::rep.
Referenced by Tps< T >::truncate().
get()
template<class T > std::istream & Tps< T >::get (std::istream & is)
Get Tps from the stream is.
Definition at line 721 of file Tps.hpp.
References TpsMonomial::getIndex(), Tps< T >::setMaxOrder(), Attrib::Legacy::Distribution::T, and Tps< T >::truncOrder.
Referenced by operator>>().
getCoefficient() [1/2]
template<class T > const T Tps< T >::getCoefficient (int index) const
Get coefficient.
Definition at line 327 of file Tps.hpp.
References Tps< T >::rep.
Referenced by Tps< T >::getCoefficient().
getCoefficient() [2/2]
template<class T > const T Tps< T >::getCoefficient (const TpsMonomial & monomial) const
Get coefficient.
Definition at line 355 of file Tps.hpp.
References Tps< T >::getCoefficient(), TpsMonomial::getIndex(), TpsMonomial::getVariables(), and Tps< T >::getVariables().
getExponents()
template<class T > const TpsMonomial & Tps< T >::getExponents (int index) const
Get exponents.
Definition at line 1073 of file Tps.hpp.
References Tps< T >::rep.
Referenced by Tps< T >::derivative(), Tps< T >::integral(), and Tps< T >::put().
getGlobalTruncOrder()
template<class T > int Tps< T >::getGlobalTruncOrder () static
Get global truncation order.
Definition at line 1061 of file Tps.hpp.
References Tps< T >::truncOrder.
getMaxOrder()
template<class T > int Tps< T >::getMaxOrder () const
Get maximal order.
Definition at line 1031 of file Tps.hpp.
References Tps< T >::rep.
Referenced by Tps< T >::derivative(), Tps< T >::evaluate(), Tps< T >::filter(), Vps< T >::getTopOrder(), Tps< T >::multiply(), Tps< T >::operator+=(), Tps< T >::operator-(), Tps< T >::operator-=(), Tps< T >::operator==(), Tps< T >::put(), Tps< T >::scaleMonomials(), and Tps< T >::substitute().
getOrder()
template<class T > int Tps< T >::getOrder (int index) const
Get order.
Definition at line 1084 of file Tps.hpp.
References Tps< T >::rep.
Referenced by Tps< T >::setCoefficient().
getSize() [1/2]
template<class T > int Tps< T >::getSize () const
Get number of coefficients.
Definition at line 1049 of file Tps.hpp.
References Tps< T >::rep.
Referenced by Tps< T >::derivative(), Tps< T >::filter(), Tps< T >::integral(), Tps< T >::multiply(), Tps< T >::multiplyVariable(), Tps< T >::operator+=(), Tps< T >::operator-=(), Tps< T >::operator==(), and Tps< T >::put().
getSize() [2/2]
template<class T > int Tps< T >::getSize (int order) const
Size.
Definition at line 1090 of file Tps.hpp.
References Tps< T >::rep.
getTruncOrder()
template<class T > int Tps< T >::getTruncOrder () const
Get truncation order.
Definition at line 1037 of file Tps.hpp.
References min(), Tps< T >::rep, and Tps< T >::truncOrder.
Referenced by cos(), cosh(), Tps< T >::derivative(), exp(), Tps< T >::filter(), Vps< T >::getTruncOrder(), Tps< T >::inverse(), log(), Tps< T >::multiply(), Tps< T >::operator+=(), Tps< T >::operator-(), Tps< T >::operator-=(), Tps< T >::operator==(), Tps< T >::put(), Tps< T >::scaleMonomials(), sin(), sinh(), sqrt(), and Tps< T >::substitute().
getVariables()
template<class T > int Tps< T >::getVariables () const
Get number of variables.
Definition at line 1043 of file Tps.hpp.
References Tps< T >::rep.
Referenced by Tps< T >::derivative(), Tps< T >::evaluate(), Tps< T >::filter(), Tps< T >::getCoefficient(), Tps< T >::integral(), Tps< T >::multiply(), Tps< T >::multiplyVariable(), Tps< T >::operator+=(), Tps< T >::operator-(), Tps< T >::operator-=(), Tps< T >::operator==(), Tps< T >::put(), Tps< T >::scaleMonomials(), Tps< T >::setCoefficient(), Vps< T >::setComponent(), and Tps< T >::substitute().
integral()
template<class T > Tps< T > Tps< T >::integral (int var) const
Partial integral.
Definition at line 946 of file Tps.hpp.
References TpsRep< T >::create(), TpsRep< T >::data(), Tps< T >::getExponents(), Tps< T >::getSize(), Tps< T >::getVariables(), min(), Tps< T >::rep, Attrib::Legacy::Distribution::T, and Tps< T >::truncOrder.
inverse()
template<class T > Tps< T > Tps< T >::inverse (int order = truncOrder) const
Reciprocal value.
Definition at line 897 of file Tps.hpp.
References Tps< T >::getTruncOrder(), Tps< T >::isConstant(), min(), Tps< T >::rep, Attrib::Legacy::Distribution::T, and Tps< T >::Taylor().
Referenced by operator/(), Vps< T >::operator/=(), Tps< T >::operator/=(), and pow().
isConstant()
template<class T > bool Tps< T >::isConstant () const
Test for constant.
Definition at line 1055 of file Tps.hpp.
References Tps< T >::rep.
Referenced by Tps< T >::inverse(), and Tps< T >::Taylor().
makeMonomial()
template<class T > Tps< T > Tps< T >::makeMonomial (const TpsMonomial & m, const T & t) static
Make monomial.
Definition at line 401 of file Tps.hpp.
References TpsRep< T >::create(), Tps< T >::EXACT, TpsMonomial::getOrder(), and TpsMonomial::getVariables().
makeVariable()
template<class T > Tps< T > Tps< T >::makeVariable (int nVar, int var) static
Make variable.
Definition at line 383 of file Tps.hpp.
References TpsRep< T >::create(), TpsRep< T >::data(), Tps< T >::EXACT, and Attrib::Legacy::Distribution::T.
makeVarPower()
template<class T > Tps< T > Tps< T >::makeVarPower (int nVar, int var, int power) static
Make power.
Definition at line 391 of file Tps.hpp.
References TpsRep< T >::create(), Tps< T >::EXACT, and Attrib::Legacy::Distribution::T.
multiply()
template<class T > Tps< T > Tps< T >::multiply (const Tps< T > & y, int trunc) const
Truncated multiplication.
Definition at line 823 of file Tps.hpp.
References TpsRep< T >::create(), Tps< T >::EXACT, Tps< T >::getMaxOrder(), Tps< T >::getSize(), Tps< T >::getTruncOrder(), Tps< T >::getVariables(), min(), prod(), Tps< T >::rep, and Attrib::Legacy::Distribution::T.
Referenced by Tps< T >::operator*=(), Tps< T >::operator/=(), and Tps< T >::Taylor().
multiplyVariable()
template<class T > Tps< T > Tps< T >::multiplyVariable (int var) const
Multiply by variable [b]var[/b].
Definition at line 969 of file Tps.hpp.
References TpsRep< T >::create(), TpsRep< T >::data(), Tps< T >::getSize(), Tps< T >::getVariables(), min(), Tps< T >::rep, Attrib::Legacy::Distribution::T, and Tps< T >::truncOrder.
operator!=() [1/2]
template<class T > bool Tps< T >::operator!= (const Tps< T > & y) const
Inequality operator.
Definition at line 602 of file Tps.hpp.
operator!=() [2/2]
template<class T > bool Tps< T >::operator!= (const T & y) const
Inequality with constant.
Definition at line 608 of file Tps.hpp.
operator*=() [1/2]
template<class T > Tps< T > & Tps< T >::operator*= (const Tps< T > & y)
Multiply and assign.
Definition at line 499 of file Tps.hpp.
References Tps< T >::multiply(), and Tps< T >::truncOrder.
operator*=() [2/2]
template<class T > Tps< T > & Tps< T >::operator*= (const T & y)
Multiply by constant and assign.
Definition at line 527 of file Tps.hpp.
References Tps< T >::rep, Attrib::Legacy::Distribution::T, and Tps< T >::unique().
operator+()
template<class T > Tps< T > Tps< T >::operator+ () const
Unary plus.
Definition at line 411 of file Tps.hpp.
operator+=() [1/2]
template<class T > Tps< T > & Tps< T >::operator+= (const Tps< T > & y)
Add and assign.
Definition at line 427 of file Tps.hpp.
References TpsRep< T >::create(), TpsRep< T >::data(), Tps< T >::getMaxOrder(), Tps< T >::getSize(), Tps< T >::getTruncOrder(), Tps< T >::getVariables(), max(), min(), TpsRep< T >::release(), Tps< T >::rep, Attrib::Legacy::Distribution::T, and Tps< T >::unique().
operator+=() [2/2]
template<class T > Tps< T > & Tps< T >::operator+= (const T & y)
Add constant and assign.
Definition at line 511 of file Tps.hpp.
References Tps< T >::rep, and Tps< T >::unique().
operator-()
template<class T > Tps< T > Tps< T >::operator- () const
Unary minus.
Definition at line 417 of file Tps.hpp.
References TpsRep< T >::create(), TpsRep< T >::data(), Tps< T >::getMaxOrder(), Tps< T >::getTruncOrder(), Tps< T >::getVariables(), and Tps< T >::rep.
operator-=() [1/2]
template<class T > Tps< T > & Tps< T >::operator-= (const Tps< T > & y)
Subtract and assign.
Definition at line 462 of file Tps.hpp.
References TpsRep< T >::create(), TpsRep< T >::data(), Tps< T >::getMaxOrder(), Tps< T >::getSize(), Tps< T >::getTruncOrder(), Tps< T >::getVariables(), max(), min(), TpsRep< T >::release(), Tps< T >::rep, Attrib::Legacy::Distribution::T, and Tps< T >::unique().
operator-=() [2/2]
template<class T > Tps< T > & Tps< T >::operator-= (const T & y)
Subtract constant and assign.
Definition at line 519 of file Tps.hpp.
References Tps< T >::rep, and Tps< T >::unique().
operator/=() [1/2]
template<class T > Tps< T > & Tps< T >::operator/= (const Tps< T > & y)
Divide and assign.
Definition at line 505 of file Tps.hpp.
References Tps< T >::inverse(), Tps< T >::multiply(), and Tps< T >::truncOrder.
operator/=() [2/2]
template<class T > Tps< T > & Tps< T >::operator/= (const T & y)
Divide by constant and assign.
Definition at line 536 of file Tps.hpp.
References Tps< T >::rep, and Attrib::Legacy::Distribution::T.
operator=() [1/2]
template<class T > Tps< T > & Tps< T >::operator= (const Tps< T > & y)
Definition at line 259 of file Tps.hpp.
References TpsRep< T >::release(), and Tps< T >::rep.
operator=() [2/2]
template<class T > Tps< T > & Tps< T >::operator= (const T & y)
Convert and assign.
Definition at line 270 of file Tps.hpp.
References TpsRep< T >::release(), Tps< T >::rep, and TpsRep< T >::zero().
operator==() [1/2]
template<class T > bool Tps< T >::operator== (const Tps< T > & y) const
Equality operator.
Definition at line 545 of file Tps.hpp.
References Tps< T >::getMaxOrder(), Tps< T >::getSize(), Tps< T >::getTruncOrder(), Tps< T >::getVariables(), min(), Tps< T >::rep, and Attrib::Legacy::Distribution::T.
operator==() [2/2]
template<class T > bool Tps< T >::operator== (const T & y) const
Equlatity with constant.
Definition at line 588 of file Tps.hpp.
References Tps< T >::getSize(), Tps< T >::rep, and Attrib::Legacy::Distribution::T.
operator[]() [1/4]
template<class T > const T Tps< T >::operator[] (int index) const
Get coefficient.
Definition at line 301 of file Tps.hpp.
References Tps< T >::rep.
operator[]() [2/4]
template<class T > T & Tps< T >::operator[] (int index)
Get coefficient.
Definition at line 307 of file Tps.hpp.
References Tps< T >::rep, and Tps< T >::unique().
operator[]() [3/4]
template<class T > const T Tps< T >::operator[] (const TpsMonomial & monomial) const
Get coefficient.
Definition at line 314 of file Tps.hpp.
References TpsMonomial::getIndex(), and Tps< T >::rep.
operator[]() [4/4]
template<class T > T & Tps< T >::operator[] (const TpsMonomial & monomial)
Get coefficient.
Definition at line 320 of file Tps.hpp.
References TpsMonomial::getIndex(), Tps< T >::rep, and Tps< T >::unique().
put()
template<class T > std::ostream & Tps< T >::put (std::ostream & os) const
Put Tps to the stream is.
Definition at line 784 of file Tps.hpp.
References endl(), Tps< T >::getExponents(), Tps< T >::getMaxOrder(), Tps< T >::getSize(), Tps< T >::getTruncOrder(), Tps< T >::getVariables(), Inform::precision(), Tps< T >::rep, and Attrib::Legacy::Distribution::T.
scaleMonomials()
template<class T > Tps< T > Tps< T >::scaleMonomials (const Tps< T > & y) const
Multiply monomial-wise.
Definition at line 992 of file Tps.hpp.
References TpsRep< T >::create(), Tps< T >::getMaxOrder(), Tps< T >::getTruncOrder(), Tps< T >::getVariables(), min(), Tps< T >::rep, and Attrib::Legacy::Distribution::T.
setCoefficient() [1/2]
template<class T > void Tps< T >::setCoefficient (int index, const T & value)
Set coefficient.
Definition at line 337 of file Tps.hpp.
References TpsRep< T >::create(), TpsRep< T >::data(), Tps< T >::getOrder(), Tps< T >::getVariables(), TpsRep< T >::release(), Tps< T >::rep, and Tps< T >::unique().
Referenced by Tps< T >::setCoefficient().
setCoefficient() [2/2]
template<class T > void Tps< T >::setCoefficient (const TpsMonomial & monomial, const T & value)
Set coefficient.
Definition at line 369 of file Tps.hpp.
References TpsMonomial::getIndex(), TpsMonomial::getVariables(), Tps< T >::getVariables(), and Tps< T >::setCoefficient().
setGlobalTruncOrder()
template<class T > void Tps< T >::setGlobalTruncOrder (int order) static
Set global truncation order.
Definition at line 1067 of file Tps.hpp.
References Tps< T >::truncOrder.
setMaxOrder()
template<class T > void Tps< T >::setMaxOrder (int order) inline private
Definition at line 49 of file Tps.hpp.
Referenced by Tps< T >::get().
substitute() [1/2]
template<class T > Tps< T > Tps< T >::substitute (const Matrix< T > & M) const
Substitute.
Definition at line 614 of file Tps.hpp.
References Tps< T >::getMaxOrder(), Tps< T >::getVariables(), TpsSubstitution::index, Array2D< T >::ncols(), Array2D< T >::nrows(), TpsSubstitution::order, Tps< T >::rep, Array1D< T >::size(), TpsSubstitution::skip, Attrib::Legacy::Distribution::T, and TpsSubstitution::variable.
substitute() [2/2]
template<class T > Tps< T > Tps< T >::substitute (const VpsMap< T > & m) const
Substitute.
Definition at line 657 of file Tps.hpp.
References Vps< T >::getDimension(), Tps< T >::getMaxOrder(), Tps< T >::getTruncOrder(), Tps< T >::getVariables(), TpsSubstitution::index, TpsSubstitution::order, Tps< T >::rep, Array1D< T >::size(), TpsSubstitution::skip, Attrib::Legacy::Distribution::T, and TpsSubstitution::variable.
Taylor()
template<class T > Tps< T > Tps< T >::Taylor (const T series[], int n) const
Taylor series.
Definition at line 1014 of file Tps.hpp.
References Tps< T >::isConstant(), Tps< T >::multiply(), and Attrib::Legacy::Distribution::T.
Referenced by cos(), cosh(), exp(), Tps< T >::inverse(), sin(), sinh(), and sqrt().
truncate()
template<class T > Tps< T > Tps< T >::truncate (int trunc)
Truncate.
Definition at line 295 of file Tps.hpp.
References Tps< T >::filter().
unique()
template<class T > void Tps< T >::unique () inline private
Definition at line 55 of file Tps.hpp.
Referenced by Tps< T >::operator*=(), Tps< T >::operator+=(), Tps< T >::operator-=(), Tps< T >::operator[](), and Tps< T >::setCoefficient().
Member Data Documentation
EXACT
template<class T> const int Tps< T >::EXACT = INT_MAX static
Representation of infinite precision.
Definition at line 260 of file Tps.h.
Referenced by Tps< T >::makeMonomial(), Tps< T >::makeVariable(), Tps< T >::makeVarPower(), and Tps< T >::multiply().
rep
template<class T> TpsRep<T>* Tps< T >::rep private
Definition at line 274 of file Tps.h.
Referenced by Tps< T >::clear(), Tps< T >::derivative(), Tps< T >::evaluate(), Tps< T >::filter(), Tps< T >::getCoefficient(), Tps< T >::getExponents(), Tps< T >::getMaxOrder(), Tps< T >::getOrder(), Tps< T >::getSize(), Tps< T >::getTruncOrder(), Tps< T >::getVariables(), Tps< T >::integral(), Tps< T >::inverse(), Tps< T >::isConstant(), Tps< T >::multiply(), Tps< T >::multiplyVariable(), Tps< T >::operator*=(), Tps< T >::operator+=(), Tps< T >::operator-(), Tps< T >::operator-=(), Tps< T >::operator/=(), Tps< T >::operator=(), Tps< T >::operator==(), Tps< T >::operator[](), Tps< T >::put(), Tps< T >::scaleMonomials(), Tps< T >::setCoefficient(), Tps< T >::substitute(), Tps< T >::Tps(), and Tps< T >::~Tps().
truncOrder
template<class T> int Tps< T >::truncOrder = EXACT static private
Definition at line 277 of file Tps.h.
Referenced by Tps< T >::get(), Tps< T >::getGlobalTruncOrder(), Tps< T >::getTruncOrder(), Tps< T >::integral(), Tps< T >::multiplyVariable(), Tps< T >::operator*=(), Tps< T >::operator/=(), and Tps< T >::setGlobalTruncOrder().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algebra/Tps.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algebra/Tps.hpp