OPAL (Object Oriented Parallel Accelerator Library): IntTSCImpl< 1U > Class Template Reference
IntTSCImpl< 1U > Class Template Reference
#include <IntTSC.h>
Public Member Functions
IntTSCImpl ()
~IntTSCImpl ()
Public Member Functions inherited from Interpolator
Interpolator ()
~Interpolator ()
Static Public Member Functions
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 1U, M, C > &f, const Vektor< PT, 1U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 1U, M, C > &f, const Vektor< PT, 1U > &ppos, const M &mesh, NDIndex< 1U > &ngp, int [1U], Vektor< PT, 1U > &dpos)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 1U, M, C > &f, const NDIndex< 1U > &ngp, const int [1U], const Vektor< PT, 1U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 1U, M, C > &f, const Vektor< PT, 1U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 1U, M, C > &f, const Vektor< PT, 1U > &ppos, const M &mesh, NDIndex< 1U > &ngp, int [1U], Vektor< PT, 1U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 1U, M, C > &f, const NDIndex< 1U > &ngp, const int [1U], const Vektor< PT, 1U > &dpos)
Additional Inherited Members
Static Protected Member Functions inherited from Interpolator
template<class T , unsigned Dim>
static CompressedBrickIterator< T, Dim > getFieldIter (const BareField< T, Dim > &f, const NDIndex< Dim > &pt)
Detailed Description
template<>
class IntTSCImpl< 1U >
Definition at line 247 of file IntTSC.h.
Constructor & Destructor Documentation
IntTSCImpl()
IntTSCImpl< 1U >::IntTSCImpl () inline
Definition at line 251 of file IntTSC.h.
~IntTSCImpl()
IntTSCImpl< 1U >::~IntTSCImpl () inline
Definition at line 252 of file IntTSC.h.
Member Function Documentation
gather() [1/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 1U >::gather (FT & pdata, const Field< FT, 1U, M, C > & f, const Vektor< PT, 1U > & ppos, const M & mesh) inline static
Definition at line 350 of file IntTSC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
gather() [2/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 1U >::gather (FT & pdata, const Field< FT, 1U, M, C > & f, const Vektor< PT, 1U > & ppos, const M & mesh, NDIndex< 1U > & ngp, int [1U], Vektor< PT, 1U > & dpos) inline static
Definition at line 385 of file IntTSC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
gather() [3/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 1U >::gather (FT & pdata, const Field< FT, 1U, M, C > & f, const NDIndex< 1U > & ngp, const int [1U], const Vektor< PT, 1U > & dpos) inline static
Definition at line 420 of file IntTSC.h.
References Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
scatter() [1/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 1U >::scatter (const FT & pdata, Field< FT, 1U, M, C > & f, const Vektor< PT, 1U > & ppos, const M & mesh) inline static
Definition at line 259 of file IntTSC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
scatter() [2/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 1U >::scatter (const FT & pdata, Field< FT, 1U, M, C > & f, const Vektor< PT, 1U > & ppos, const M & mesh, NDIndex< 1U > & ngp, int [1U], Vektor< PT, 1U > & dpos) inline static
Definition at line 293 of file IntTSC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
scatter() [3/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 1U >::scatter (const FT & pdata, Field< FT, 1U, M, C > & f, const NDIndex< 1U > & ngp, const int [1U], const Vektor< PT, 1U > & dpos) inline static
Definition at line 326 of file IntTSC.h.
References Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/IntTSC.h