OPAL (Object Oriented Parallel Accelerator Library): Simulation Class Reference
Simulation Class Reference abstract
#include <Simulation.h>
Public Member Functions
Simulation (CmdArguments_t args)
~Simulation ()
CmdArguments_t getArgs ()
virtual void run ()=0
virtual void collectResults ()=0
virtual reqVarContainer_t getResults ()=0
Private Attributes
CmdArguments_t args_
Detailed Description
Definition at line 37 of file Simulation.h.
Constructor & Destructor Documentation
Simulation()
Simulation::Simulation (CmdArguments_t args) inline
Definition at line 41 of file Simulation.h.
~Simulation()
Simulation::~Simulation () inline
Definition at line 45 of file Simulation.h.
Member Function Documentation
collectResults()
virtual void Simulation::collectResults () pure virtual
Collect all results from after the simulation has been executed. Make sure that data is available before returning from function.
See also
run()
Implemented in OpalSimulation.
getArgs()
CmdArguments_t Simulation::getArgs () inline
Definition at line 48 of file Simulation.h.
References args_.
Referenced by OpalSimulation::copyH5_m(), OpalSimulation::run(), and OpalSimulation::setupSimulation().
getResults()
virtual reqVarContainer_t Simulation::getResults () pure virtual
Get all requested information.
Implemented in OpalSimulation.
run()
virtual void Simulation::run () pure virtual
Run the simulation (different for every simulation we specify). This method can block or return immediately, the worker is calling collectResults() to get the results. This means that the implementation of the Simulation class has to make sure that collectResults() waits until the data is available.
Implemented in OpalSimulation.
Member Data Documentation
args_
CmdArguments_t Simulation::args_ private
Definition at line 73 of file Simulation.h.
Referenced by getArgs().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/optimizer/Simulation/Simulation.h