OPAL (Object Oriented Parallel Accelerator Library): BoundingBox Class Reference
BoundingBox Class Reference
#include <BoundingBox.h>
Public Member Functions
BoundingBox ()
void enlargeToContainPosition (const Vector_t &position)
void enlargeToContainBoundingBox (const BoundingBox &boundingBox)
boost::optional< Vector_t > getIntersectionPoint (const Vector_t &position, const Vector_t &direction) const
bool isInside (const Vector_t &position) const
bool isOutside (const Vector_t &position) const
void print (std::ostream &output) const
std::pair< Vector_t, Vector_t > getCorners () const
Static Public Member Functions
static BoundingBox getBoundingBox (const std::vector< Vector_t > &positions)
Private Attributes
Vector_t lowerLeftCorner_m
Vector_t upperRightCorner_m
Detailed Description
Definition at line 33 of file BoundingBox.h.
Constructor & Destructor Documentation
BoundingBox()
BoundingBox::BoundingBox ()
Definition at line 26 of file BoundingBox.cpp.
Member Function Documentation
enlargeToContainBoundingBox()
void BoundingBox::enlargeToContainBoundingBox (const BoundingBox & boundingBox)
Definition at line 49 of file BoundingBox.cpp.
References lowerLeftCorner_m, max(), min(), and upperRightCorner_m.
Referenced by OrbitThreader::computeBoundingBox().
enlargeToContainPosition()
void BoundingBox::enlargeToContainPosition (const Vector_t & position)
Definition at line 41 of file BoundingBox.cpp.
References lowerLeftCorner_m, max(), min(), and upperRightCorner_m.
Referenced by getBoundingBox(), Bend2D::getBoundingBoxInLabCoords(), OrbitThreader::integrate(), and OrbitThreader::updateBoundingBoxWithCurrentPosition().
getBoundingBox()
BoundingBox BoundingBox::getBoundingBox (const std::vector< Vector_t > & positions) static
Definition at line 31 of file BoundingBox.cpp.
References enlargeToContainPosition().
Referenced by ElementBase::getBoundingBoxInLabCoords().
getCorners()
std::pair< Vector_t, Vector_t > BoundingBox::getCorners () const inline
Definition at line 57 of file BoundingBox.h.
References lowerLeftCorner_m, and upperRightCorner_m.
getIntersectionPoint()
boost::optional< Vector_t > BoundingBox::getIntersectionPoint (const Vector_t & position, const Vector_t & direction) const
Definition at line 57 of file BoundingBox.cpp.
References dot(), euclidean_norm(), lowerLeftCorner_m, max(), sign(), and upperRightCorner_m.
Referenced by OrbitThreader::computeDriftLengthToBoundingBox().
isInside()
bool BoundingBox::isInside (const Vector_t & position) const
Definition at line 99 of file BoundingBox.cpp.
References lowerLeftCorner_m, and upperRightCorner_m.
Referenced by isOutside().
isOutside()
bool BoundingBox::isOutside (const Vector_t & position) const inline
Definition at line 62 of file BoundingBox.h.
References isInside().
Referenced by ParallelTTracker::hasEndOfLineReached().
print()
void BoundingBox::print (std::ostream & output) const
Definition at line 109 of file BoundingBox.cpp.
References endl(), lowerLeftCorner_m, Inform::precision(), and upperRightCorner_m.
Member Data Documentation
lowerLeftCorner_m
Vector_t BoundingBox::lowerLeftCorner_m private
Definition at line 52 of file BoundingBox.h.
Referenced by enlargeToContainBoundingBox(), enlargeToContainPosition(), getCorners(), getIntersectionPoint(), isInside(), and print().
upperRightCorner_m
Vector_t BoundingBox::upperRightCorner_m private
Definition at line 53 of file BoundingBox.h.
Referenced by enlargeToContainBoundingBox(), enlargeToContainPosition(), getCorners(), getIntersectionPoint(), isInside(), and print().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Structure/BoundingBox.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Structure/BoundingBox.cpp