OPAL (Object Oriented Parallel Accelerator Library): RFCavity Class Reference
RFCavity Class Reference abstract
Interface for RF cavity.
#include <RFCavity.h>
Public Types
enum CavityType { SW, SGSW }
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Public Member Functions
RFCavity (const std::string &name)
Constructor with given name.
RFCavity ()
RFCavity (const RFCavity &)
virtual ~RFCavity ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to RFCavity.
virtual double getAmplitude () const =0
Get RF amplitude.
virtual double getFrequency () const =0
Get RF frequencey.
virtual double getPhase () const =0
Get RF phase.
void dropFieldmaps ()
virtual void setFieldMapFN (std::string fmapfn)
Set the name of the field map.
virtual std::string getFieldMapFN () const
virtual void setAmplitudem (double vPeak)
virtual double getAmplitudem () const
virtual void setAmplitudeError (double vPeakError)
virtual double getAmplitudeError () const
virtual void setFrequencym (double freq)
void setFrequency (double freq)
virtual double getFrequencym () const
virtual void setPhasem (double phase)
virtual double getPhasem () const
double getPhasem (double t) const
virtual void setPhaseError (double phaseError)
virtual double getPhaseError () const
void setCavityType (std::string type)
std::string getCavityType () const
virtual void setFast (bool fast)
virtual bool getFast () const
virtual void setAutophaseVeto (bool veto=true)
virtual bool getAutophaseVeto () const
virtual double getAutoPhaseEstimate (const double &E0, const double &t0, const double &q, const double &m)
virtual double getAutoPhaseEstimateFallback (double E0, double t0, double q, double m)
virtual std::pair< double, double > trackOnAxisParticle (const double &p0, const double &t0, const double &dt, const double &q, const double &mass, std::ofstream *out=NULL)
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
virtual void initialise (PartBunchBase< double, 3 > *bunch, std::shared_ptr< AbstractTimeDependence > freq_atd, std::shared_ptr< AbstractTimeDependence > ampl_atd, std::shared_ptr< AbstractTimeDependence > phase_atd)
virtual void finalise () override
virtual bool bends () const override
virtual void goOnline (const double &kineticEnergy) override
virtual void goOffline () override
virtual void setDesignEnergy (const double &ekin, bool changeable=true) override
virtual double getDesignEnergy () const override
void setRmin (double rmin)
void setRmax (double rmax)
void setAzimuth (double angle)
void setPerpenDistance (double pdis)
void setGapWidth (double gapwidth)
void setPhi0 (double phi0)
virtual double getRmin () const
virtual double getRmax () const
virtual double getAzimuth () const
virtual double getCosAzimuth () const
virtual double getSinAzimuth () const
virtual double getPerpenDistance () const
virtual double getGapWidth () const
virtual double getPhi0 () const
virtual void setComponentType (std::string name) override
virtual std::string getComponentType () const override
virtual double getCycFrequency () const
void getMomentaKick (const double normalRadius, double momentum[], const double t, const double dtCorrt, const int PID, const double restMass, const int chargenumber)
used in OPAL-cycl
double spline (double z, double *za)
virtual ElementBase::ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
virtual bool isInside (const Vector_t &r) const override
void setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setAmplitudeModelName (std::string name)
std::string getAmplitudeModelName ()
void setPhaseModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setPhaseModelName (std::string name)
std::string getPhaseModelName ()
void setFrequencyModel (std::shared_ptr< AbstractTimeDependence > time_dep)
void setFrequencyModelName (std::string name)
std::string getFrequencyModelName ()
virtual double getElementLength () const override
Get design length.
virtual void getElementDimensions (double &begin, double &end) const override
virtual CoordinateSystemTrafo getEdgeToBegin () const override
virtual CoordinateSystemTrafo getEdgeToEnd () const override
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
virtual EMField & getField ()=0
Return field.
virtual const EMField & getField () const =0
Return field.
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual void setElementLength (double length)
Set design length.
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Protected Attributes
std::shared_ptr< AbstractTimeDependence > phase_td_m
std::string phase_name_m
std::shared_ptr< AbstractTimeDependence > amplitude_td_m
std::string amplitude_name_m
std::shared_ptr< AbstractTimeDependence > frequency_td_m
std::string frequency_name_m
std::string filename_m
double scale_m
double scaleError_m
double phase_m
double phaseError_m
double frequency_m
bool fast_m
bool autophaseVeto_m
double designEnergy_m
Fieldmap * fieldmap_m
double startField_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Private Member Functions
double getdE (const int &i, const std::vector< double > &t, const double &dz, const double &phi, const double &frequency, const std::vector< double > &F) const
double getdT (const int &i, const std::vector< double > &E, const double &dz, const double mass) const
double getdA (const int &i, const std::vector< double > &t, const double &dz, const double &frequency, const std::vector< double > &F) const
double getdB (const int &i, const std::vector< double > &t, const double &dz, const double &frequency, const std::vector< double > &F) const
void operator= (const RFCavity &)
Private Attributes
double endField_m
CavityType type_m
double rmin_m
double rmax_m
double angle_m
double sinAngle_m
double cosAngle_m
double pdis_m
double gapwidth_m
double phi0_m
std::unique_ptr< double[]> RNormal_m
std::unique_ptr< double[]> VrNormal_m
std::unique_ptr< double[]> DvDr_m
int num_points_m
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Interface for RF cavity.
Definition at line 37 of file RFCavity.h.
Member Enumeration Documentation
CavityType
enum RFCavity::CavityType
Enumerator
SW
SGSW
Definition at line 41 of file RFCavity.h.
Constructor & Destructor Documentation
RFCavity() [1/3]
RFCavity::RFCavity (const std::string & name) explicit
Constructor with given name.
Definition at line 82 of file RFCavity.cpp.
RFCavity() [2/3]
RFCavity::RFCavity ()
Definition at line 41 of file RFCavity.cpp.
RFCavity() [3/3]
RFCavity::RFCavity (const RFCavity & right)
Definition at line 46 of file RFCavity.cpp.
~RFCavity()
RFCavity::~RFCavity () virtual
Definition at line 115 of file RFCavity.cpp.
Member Function Documentation
accept()
void RFCavity::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to RFCavity.
Implements ElementBase.
Reimplemented in TravelingWave.
Definition at line 118 of file RFCavity.cpp.
References BeamlineVisitor::visitRFCavity().
apply() [1/2]
bool RFCavity::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Reimplemented in TravelingWave.
Definition at line 122 of file RFCavity.cpp.
References PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::R, and Component::RefPartBunch_m.
apply() [2/2]
bool RFCavity::apply (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Reimplemented in TravelingWave.
Definition at line 126 of file RFCavity.cpp.
References cos(), fieldmap_m, frequency_m, getElementLength(), Fieldmap::getFieldstrength(), phase_m, phaseError_m, Attrib::Distribution::R, scale_m, scaleError_m, sin(), and startField_m.
applyToReferenceParticle()
bool RFCavity::applyToReferenceParticle (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Reimplemented from Component.
Reimplemented in TravelingWave.
Definition at line 145 of file RFCavity.cpp.
References cos(), fieldmap_m, frequency_m, getElementLength(), Fieldmap::getFieldstrength(), phase_m, Attrib::Distribution::R, scale_m, sin(), and startField_m.
Referenced by trackOnAxisParticle().
bends()
bool RFCavity::bends () const override virtual
Implements Component.
Reimplemented in TravelingWave.
Definition at line 252 of file RFCavity.cpp.
dropFieldmaps()
void RFCavity::dropFieldmaps () inline
Definition at line 353 of file RFCavity.h.
References fieldmap_m.
Referenced by OpalCavity::update().
finalise()
void RFCavity::finalise () override virtual
Implements Component.
Reimplemented in TravelingWave.
Definition at line 249 of file RFCavity.cpp.
getAmplitude()
virtual double RFCavity::getAmplitude () const pure virtual
Get RF amplitude.
Implemented in RFCavityRep, TravelingWaveRep, and TravelingWave.
getAmplitudeError()
double RFCavity::getAmplitudeError () const inline virtual
Definition at line 383 of file RFCavity.h.
References scaleError_m.
getAmplitudem()
double RFCavity::getAmplitudem () const inline virtual
Definition at line 373 of file RFCavity.h.
References scale_m.
Referenced by CavityAutophaser::getPhaseAtMaxEnergy().
getAmplitudeModelName()
std::string RFCavity::getAmplitudeModelName () inline
Definition at line 468 of file RFCavity.h.
References amplitude_name_m.
Referenced by ParallelCyclotronTracker::visitRFCavity().
getAutoPhaseEstimate()
double RFCavity::getAutoPhaseEstimate (const double & E0, const double & t0, const double & q, const double & m) virtual
Reimplemented in TravelingWave.
Definition at line 536 of file RFCavity.cpp.
References a, abs(), atan(), begin(), Physics::c, cos(), end(), endl(), fieldmap_m, floor(), frequency_m, getAutoPhaseEstimateFallback(), Util::getBetaGamma(), getdA(), getdB(), getdE(), getdT(), Fieldmap::getOnaxisEz(), IpplInfo::Info, INFOMSG, matheval::detail::math::isnan(), level2(), Physics::pi, Inform::precision(), Physics::rad2deg, scale_m, sin(), and Physics::two_pi.
Referenced by CavityAutophaser::guessCavityPhase().
getAutoPhaseEstimateFallback()
double RFCavity::getAutoPhaseEstimateFallback (double E0, double t0, double q, double m) virtual
Definition at line 494 of file RFCavity.cpp.
References Physics::e, endl(), fmod(), Util::getBetaGamma(), Util::getKineticEnergy(), getPhasem(), IpplInfo::Info, INFOMSG, level2(), Physics::pi, Inform::precision(), Physics::rad2deg, setPhasem(), trackOnAxisParticle(), and Physics::two_pi.
Referenced by getAutoPhaseEstimate().
getAutophaseVeto()
bool RFCavity::getAutophaseVeto () const inline virtual
Definition at line 453 of file RFCavity.h.
References autophaseVeto_m.
Referenced by ParallelTTracker::autophaseCavities(), CavityAutophaser::getPhaseAtMaxEnergy(), CavityAutophaser::guessCavityPhase(), and CavityAutophaser::optimizeCavityPhase().
getAzimuth()
double RFCavity::getAzimuth () const virtual
Definition at line 301 of file RFCavity.cpp.
References angle_m.
Referenced by ParallelCyclotronTracker::visitRFCavity().
getCavityType()
std::string RFCavity::getCavityType () const inline
Definition at line 433 of file RFCavity.h.
getComponentType()
std::string RFCavity::getComponentType () const override virtual
Reimplemented from Component.
Definition at line 347 of file RFCavity.cpp.
References SGSW, and type_m.
Referenced by ParallelCyclotronTracker::visitRFCavity().
getCosAzimuth()
double RFCavity::getCosAzimuth () const virtual
Definition at line 309 of file RFCavity.cpp.
References cosAngle_m.
Referenced by ParallelCyclotronTracker::checkGapCross(), and ParallelCyclotronTracker::execute().
getCycFrequency()
double RFCavity::getCycFrequency () const virtual
Definition at line 354 of file RFCavity.cpp.
References frequency_m.
Referenced by ParallelCyclotronTracker::visitRFCavity().
getdA()
double RFCavity::getdA (const int & i, const std::vector< double > & t, const double & dz, const double & frequency, const std::vector< double > & F) const inline private
Definition at line 319 of file RFCavity.h.
References cos(), and sin().
Referenced by getAutoPhaseEstimate().
getdB()
double RFCavity::getdB (const int & i, const std::vector< double > & t, const double & dz, const double & frequency, const std::vector< double > & F) const inline private
Definition at line 331 of file RFCavity.h.
References cos(), and sin().
Referenced by getAutoPhaseEstimate().
getdE()
double RFCavity::getdE (const int & i, const std::vector< double > & t, const double & dz, const double & phi, const double & frequency, const std::vector< double > & F) const inline private
Definition at line 279 of file RFCavity.h.
References cos(), and sin().
Referenced by getAutoPhaseEstimate().
getDesignEnergy()
double RFCavity::getDesignEnergy () const inline override virtual
Reimplemented from Component.
Definition at line 348 of file RFCavity.h.
References designEnergy_m.
Referenced by OrbitThreader::getMaxDesignEnergy(), and CavityAutophaser::getPhaseAtMaxEnergy().
getDimensions()
void RFCavity::getDimensions (double & zBegin, double & zEnd) const override virtual
Implements Component.
Reimplemented in TravelingWave.
Definition at line 484 of file RFCavity.cpp.
References endField_m, and startField_m.
getdT()
double RFCavity::getdT (const int & i, const std::vector< double > & E, const double & dz, const double mass) const inline private
Definition at line 291 of file RFCavity.h.
References Physics::c, and sqrt().
Referenced by getAutoPhaseEstimate().
getEdgeToBegin()
CoordinateSystemTrafo RFCavity::getEdgeToBegin () const inline override virtual
Reimplemented from ElementBase.
Reimplemented in TravelingWave.
Definition at line 504 of file RFCavity.h.
References startField_m.
getEdgeToEnd()
CoordinateSystemTrafo RFCavity::getEdgeToEnd () const inline override virtual
Reimplemented from ElementBase.
Reimplemented in TravelingWave.
Definition at line 511 of file RFCavity.h.
References getElementLength(), and startField_m.
getElementDimensions()
void RFCavity::getElementDimensions (double & begin, double & end) const override virtual
Reimplemented from ElementBase.
Reimplemented in TravelingWave.
Definition at line 733 of file RFCavity.cpp.
References begin(), end(), fieldmap_m, and Fieldmap::getFieldDimensions().
getElementLength()
double RFCavity::getElementLength () const override virtual
Get design length.
Reimplemented from ElementBase.
Definition at line 722 of file RFCavity.cpp.
References Physics::e, end(), fieldmap_m, ElementBase::getElementLength(), and Fieldmap::getFieldDimensions().
Referenced by TravelingWave::apply(), apply(), TravelingWave::applyToReferenceParticle(), applyToReferenceParticle(), TravelingWave::getDimensions(), TravelingWave::getEdgeToEnd(), getEdgeToEnd(), TravelingWave::getElementDimensions(), and trackOnAxisParticle().
getFast()
bool RFCavity::getFast () const inline virtual
Definition at line 443 of file RFCavity.h.
References fast_m.
getFieldMapFN()
std::string RFCavity::getFieldMapFN () const inline virtual
Definition at line 363 of file RFCavity.h.
References filename_m.
Referenced by ParallelCyclotronTracker::visitRFCavity().
getFrequency()
virtual double RFCavity::getFrequency () const pure virtual
Get RF frequencey.
Implemented in RFCavityRep, TravelingWaveRep, and TravelingWave.
getFrequencym()
double RFCavity::getFrequencym () const inline virtual
Definition at line 398 of file RFCavity.h.
References frequency_m.
Referenced by CavityAutophaser::getPhaseAtMaxEnergy(), and CavityAutophaser::optimizeCavityPhase().
getFrequencyModelName()
std::string RFCavity::getFrequencyModelName () inline
Definition at line 498 of file RFCavity.h.
References frequency_name_m.
Referenced by ParallelCyclotronTracker::visitRFCavity().
getGapWidth()
double RFCavity::getGapWidth () const virtual
Definition at line 317 of file RFCavity.cpp.
References gapwidth_m.
Referenced by ParallelCyclotronTracker::visitRFCavity().
getMomentaKick()
void RFCavity::getMomentaKick (const double normalRadius, double momentum[], const double t, const double dtCorrt, const int PID, const double restMass, const int chargenumber)
used in OPAL-cycl
Is called from OPAL-cycl and can handle time dependent frequency, amplitude and phase
At the moment (test) only the frequency is time dependent
B field effects
Definition at line 368 of file RFCavity.cpp.
References Physics::c, cos(), cosAngle_m, Physics::e, endl(), fmod(), frequency_m, frequency_td_m, gapwidth_m, ElementBase::getName(), gmsg, IpplInfo::myNode(), phi0_m, Physics::pi, pow(), rmax_m, rmin_m, scale_m, sin(), sinAngle_m, spline(), sqrt(), and Physics::two_pi.
Referenced by ParallelCyclotronTracker::RFkick().
getPerpenDistance()
double RFCavity::getPerpenDistance () const virtual
Definition at line 313 of file RFCavity.cpp.
References pdis_m.
Referenced by ParallelCyclotronTracker::checkGapCross(), ParallelCyclotronTracker::execute(), ParallelCyclotronTracker::RFkick(), and ParallelCyclotronTracker::visitRFCavity().
getPhase()
virtual double RFCavity::getPhase () const pure virtual
Get RF phase.
Implemented in RFCavityRep, TravelingWaveRep, and TravelingWave.
getPhaseError()
double RFCavity::getPhaseError () const inline virtual
Definition at line 423 of file RFCavity.h.
References phaseError_m.
getPhasem() [1/2]
double RFCavity::getPhasem () const inline virtual
Definition at line 408 of file RFCavity.h.
References phase_m.
Referenced by getAutoPhaseEstimateFallback(), CavityAutophaser::getPhaseAtMaxEnergy(), CavityAutophaser::guessCavityPhase(), CavityAutophaser::optimizeCavityPhase(), and CavityAutophaser::track().
getPhasem() [2/2]
double RFCavity::getPhasem (double t) const inline
Definition at line 413 of file RFCavity.h.
References frequency_m, and phase_m.
getPhaseModelName()
std::string RFCavity::getPhaseModelName () inline
Definition at line 483 of file RFCavity.h.
References phase_name_m.
Referenced by ParallelCyclotronTracker::visitRFCavity().
getPhi0()
double RFCavity::getPhi0 () const virtual
Definition at line 321 of file RFCavity.cpp.
References phi0_m.
Referenced by ParallelCyclotronTracker::visitRFCavity().
getRmax()
double RFCavity::getRmax () const virtual
Definition at line 297 of file RFCavity.cpp.
References rmax_m.
Referenced by ParallelCyclotronTracker::RFkick(), and ParallelCyclotronTracker::visitRFCavity().
getRmin()
double RFCavity::getRmin () const virtual
Definition at line 293 of file RFCavity.cpp.
References rmin_m.
Referenced by ParallelCyclotronTracker::RFkick(), and ParallelCyclotronTracker::visitRFCavity().
getSinAzimuth()
double RFCavity::getSinAzimuth () const virtual
Definition at line 305 of file RFCavity.cpp.
References sinAngle_m.
Referenced by ParallelCyclotronTracker::checkGapCross(), and ParallelCyclotronTracker::execute().
getType()
ElementBase::ElementType RFCavity::getType () const override virtual
Get element type std::string.
Reimplemented from Component.
Reimplemented in TravelingWave.
Definition at line 490 of file RFCavity.cpp.
References ElementBase::RFCAVITY.
goOffline()
void RFCavity::goOffline () override virtual
Reimplemented from Component.
Reimplemented in TravelingWave.
Definition at line 263 of file RFCavity.cpp.
References filename_m, Fieldmap::freeMap(), and Component::online_m.
goOnline()
void RFCavity::goOnline (const double & kineticEnergy) override virtual
Reimplemented from Component.
Reimplemented in TravelingWave.
Definition at line 257 of file RFCavity.cpp.
References filename_m, Component::online_m, and Fieldmap::readMap().
initialise() [1/2]
void RFCavity::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Implements Component.
Reimplemented in TravelingWave.
Definition at line 165 of file RFCavity.cpp.
References abs(), Physics::e, endField_m, endl(), ERRORMSG, fast_m, fieldmap_m, filename_m, frequency_m, Fieldmap::getFieldDimensions(), Fieldmap::getFieldmap(), Fieldmap::getFrequency(), Fieldmap::getInfo(), ElementBase::getName(), gmsg, level2(), IpplInfo::myNode(), Component::RefPartBunch_m, ElementBase::setElementLength(), startField_m, Physics::two_pi, and Fieldmap::typeset_msg().
Referenced by TravelingWave::initialise(), and ParallelCyclotronTracker::visitRFCavity().
initialise() [2/2]
void RFCavity::initialise (PartBunchBase< double, 3 > * bunch, std::shared_ptr< AbstractTimeDependence > freq_atd, std::shared_ptr< AbstractTimeDependence > ampl_atd, std::shared_ptr< AbstractTimeDependence > phase_atd) virtual
set the time dependent models
Definition at line 205 of file RFCavity.cpp.
References angle_m, cos(), cosAngle_m, Physics::deg2rad, DvDr_m, endl(), filename_m, frequency_name_m, PartBunchBase< T, Dim >::getQ(), gmsg, num_points_m, Component::RefPartBunch_m, RNormal_m, setAmplitudeModel(), setFrequencyModel(), setPhaseModel(), sin(), sinAngle_m, and VrNormal_m.
isInside()
bool RFCavity::isInside (const Vector_t & r) const override virtual
Reimplemented from ElementBase.
Reimplemented in TravelingWave.
Definition at line 714 of file RFCavity.cpp.
References fieldmap_m, Fieldmap::isInside(), and ElementBase::isInsideTransverse().
operator=()
void RFCavity::operator= (const RFCavity &) private
setAmplitudeError()
void RFCavity::setAmplitudeError (double vPeakError) inline virtual
Definition at line 378 of file RFCavity.h.
References scaleError_m.
Referenced by OpalTravelingWave::update(), and OpalCavity::update().
setAmplitudem()
void RFCavity::setAmplitudem (double vPeak) inline virtual
Definition at line 368 of file RFCavity.h.
References scale_m.
Referenced by CavityAutophaser::getPhaseAtMaxEnergy(), OpalTravelingWave::update(), and OpalCavity::update().
setAmplitudeModel()
void RFCavity::setAmplitudeModel (std::shared_ptr< AbstractTimeDependence > time_dep) inline
Definition at line 458 of file RFCavity.h.
References amplitude_td_m.
Referenced by initialise().
setAmplitudeModelName()
void RFCavity::setAmplitudeModelName (std::string name) inline
Definition at line 463 of file RFCavity.h.
References amplitude_name_m, and name.
Referenced by OpalCavity::update().
setAutophaseVeto()
void RFCavity::setAutophaseVeto (bool veto = true) inline virtual
Definition at line 448 of file RFCavity.h.
References autophaseVeto_m.
Referenced by CavityAutophaser::getPhaseAtMaxEnergy(), OpalTravelingWave::update(), OpalCavity::update(), and ParallelTTracker::updateRFElement().
setAzimuth()
void RFCavity::setAzimuth (double angle)
Definition at line 277 of file RFCavity.cpp.
References angle_m.
Referenced by OpalCavity::update().
setCavityType()
void RFCavity::setCavityType (std::string type) inline
Definition at line 428 of file RFCavity.h.
Referenced by OpalCavity::update().
setComponentType()
void RFCavity::setComponentType (std::string name) override virtual
Reimplemented from Component.
Definition at line 325 of file RFCavity.cpp.
References endl(), ERRORMSG, ElementBase::getName(), IpplInfo::myNode(), name, SGSW, SW, type_m, and Fieldmap::typeset_msg().
Referenced by OpalCavity::update().
setDesignEnergy()
void RFCavity::setDesignEnergy (const double & ekin, bool changeable = true) inline override virtual
Reimplemented from Component.
Definition at line 343 of file RFCavity.h.
References designEnergy_m.
Referenced by OpalTravelingWave::update(), and OpalCavity::update().
setFast()
void RFCavity::setFast (bool fast) inline virtual
Definition at line 438 of file RFCavity.h.
References fast_m.
Referenced by OpalTravelingWave::update(), and OpalCavity::update().
setFieldMapFN()
void RFCavity::setFieldMapFN (std::string fmapfn) inline virtual
Set the name of the field map.
Definition at line 358 of file RFCavity.h.
References filename_m.
Referenced by OpalTravelingWave::update(), and OpalCavity::update().
setFrequency()
void RFCavity::setFrequency (double freq) inline
Definition at line 388 of file RFCavity.h.
References frequency_m.
setFrequencym()
void RFCavity::setFrequencym (double freq) inline virtual
Definition at line 393 of file RFCavity.h.
References frequency_m.
Referenced by OpalTravelingWave::update(), and OpalCavity::update().
setFrequencyModel()
void RFCavity::setFrequencyModel (std::shared_ptr< AbstractTimeDependence > time_dep) inline
Definition at line 488 of file RFCavity.h.
References frequency_td_m.
Referenced by initialise().
setFrequencyModelName()
void RFCavity::setFrequencyModelName (std::string name) inline
Definition at line 493 of file RFCavity.h.
References frequency_name_m, and name.
Referenced by OpalCavity::update().
setGapWidth()
void RFCavity::setGapWidth (double gapwidth)
Definition at line 285 of file RFCavity.cpp.
References gapwidth_m.
Referenced by OpalCavity::update().
setPerpenDistance()
void RFCavity::setPerpenDistance (double pdis)
Definition at line 281 of file RFCavity.cpp.
References pdis_m.
Referenced by OpalCavity::update().
setPhaseError()
void RFCavity::setPhaseError (double phaseError) inline virtual
Definition at line 418 of file RFCavity.h.
References phaseError_m.
Referenced by OpalTravelingWave::update(), and OpalCavity::update().
setPhasem()
void RFCavity::setPhasem (double phase) inline virtual
Reimplemented in TravelingWave.
Definition at line 403 of file RFCavity.h.
References phase_m.
Referenced by getAutoPhaseEstimateFallback(), CavityAutophaser::getPhaseAtMaxEnergy(), CavityAutophaser::track(), OpalCavity::update(), and ParallelTTracker::updateRFElement().
setPhaseModel()
void RFCavity::setPhaseModel (std::shared_ptr< AbstractTimeDependence > time_dep) inline
Definition at line 473 of file RFCavity.h.
References phase_td_m.
Referenced by initialise().
setPhaseModelName()
void RFCavity::setPhaseModelName (std::string name) inline
Definition at line 478 of file RFCavity.h.
References name, and phase_name_m.
Referenced by OpalCavity::update().
setPhi0()
void RFCavity::setPhi0 (double phi0)
Definition at line 289 of file RFCavity.cpp.
References phi0_m.
Referenced by OpalCavity::update().
setRmax()
void RFCavity::setRmax (double rmax)
Definition at line 273 of file RFCavity.cpp.
References rmax_m.
Referenced by OpalCavity::update().
setRmin()
void RFCavity::setRmin (double rmin)
Definition at line 269 of file RFCavity.cpp.
References rmin_m.
Referenced by OpalCavity::update().
spline()
double RFCavity::spline (double z, double * za)
Definition at line 424 of file RFCavity.cpp.
References DvDr_m, num_points_m, RNormal_m, and VrNormal_m.
Referenced by getMomentaKick().
trackOnAxisParticle()
std::pair< double, double > RFCavity::trackOnAxisParticle (const double & p0, const double & t0, const double & dt, const double & q, const double & mass, std::ofstream * out = NULL) virtual
Definition at line 665 of file RFCavity.cpp.
References applyToReferenceParticle(), Physics::c, dot(), endl(), getElementLength(), Util::getGamma(), Util::getKineticEnergy(), PartBunchBase< T, Dim >::getReference(), Component::RefPartBunch_m, sqrt(), and startField_m.
Referenced by getAutoPhaseEstimateFallback(), and CavityAutophaser::track().
Member Data Documentation
amplitude_name_m
std::string RFCavity::amplitude_name_m protected
Definition at line 211 of file RFCavity.h.
Referenced by getAmplitudeModelName(), and setAmplitudeModelName().
amplitude_td_m
std::shared_ptr<AbstractTimeDependence> RFCavity::amplitude_td_m protected
Definition at line 210 of file RFCavity.h.
Referenced by setAmplitudeModel().
angle_m
double RFCavity::angle_m private
Definition at line 238 of file RFCavity.h.
Referenced by getAzimuth(), initialise(), and setAzimuth().
autophaseVeto_m
bool RFCavity::autophaseVeto_m protected
Definition at line 224 of file RFCavity.h.
Referenced by getAutophaseVeto(), and setAutophaseVeto().
cosAngle_m
double RFCavity::cosAngle_m private
Definition at line 240 of file RFCavity.h.
Referenced by getCosAzimuth(), getMomentaKick(), and initialise().
designEnergy_m
double RFCavity::designEnergy_m protected
Definition at line 226 of file RFCavity.h.
Referenced by getDesignEnergy(), and setDesignEnergy().
DvDr_m
std::unique_ptr<double[]> RFCavity::DvDr_m private
Definition at line 247 of file RFCavity.h.
Referenced by initialise(), and spline().
endField_m
double RFCavity::endField_m private
Definition at line 232 of file RFCavity.h.
Referenced by getDimensions(), and initialise().
fast_m
bool RFCavity::fast_m protected
Definition at line 223 of file RFCavity.h.
Referenced by getFast(), initialise(), and setFast().
fieldmap_m
Fieldmap* RFCavity::fieldmap_m protected
Definition at line 228 of file RFCavity.h.
Referenced by TravelingWave::apply(), apply(), TravelingWave::applyToReferenceParticle(), applyToReferenceParticle(), dropFieldmaps(), TravelingWave::getAutoPhaseEstimate(), getAutoPhaseEstimate(), getElementDimensions(), getElementLength(), initialise(), and isInside().
filename_m
std::string RFCavity::filename_m protected
The name of the inputfile
Definition at line 215 of file RFCavity.h.
Referenced by getFieldMapFN(), TravelingWave::goOffline(), goOffline(), TravelingWave::goOnline(), goOnline(), initialise(), and setFieldMapFN().
frequency_m
double RFCavity::frequency_m protected
Read in frequency of time varying field(Hz)
Definition at line 221 of file RFCavity.h.
Referenced by TravelingWave::apply(), apply(), TravelingWave::applyToReferenceParticle(), applyToReferenceParticle(), TravelingWave::getAutoPhaseEstimate(), getAutoPhaseEstimate(), getCycFrequency(), TravelingWave::getdA(), TravelingWave::getdB(), TravelingWave::getdE(), getFrequencym(), getMomentaKick(), getPhasem(), initialise(), setFrequency(), and setFrequencym().
frequency_name_m
std::string RFCavity::frequency_name_m protected
Definition at line 213 of file RFCavity.h.
Referenced by getFrequencyModelName(), initialise(), and setFrequencyModelName().
frequency_td_m
std::shared_ptr<AbstractTimeDependence> RFCavity::frequency_td_m protected
Definition at line 212 of file RFCavity.h.
Referenced by getMomentaKick(), and setFrequencyModel().
gapwidth_m
double RFCavity::gapwidth_m private
Definition at line 242 of file RFCavity.h.
Referenced by getGapWidth(), getMomentaKick(), and setGapWidth().
num_points_m
int RFCavity::num_points_m private
Definition at line 248 of file RFCavity.h.
Referenced by initialise(), and spline().
pdis_m
double RFCavity::pdis_m private
Definition at line 241 of file RFCavity.h.
Referenced by getPerpenDistance(), and setPerpenDistance().
phase_m
double RFCavity::phase_m protected
phase shift of time varying field (rad)
Definition at line 219 of file RFCavity.h.
Referenced by TravelingWave::apply(), apply(), TravelingWave::applyToReferenceParticle(), applyToReferenceParticle(), TravelingWave::getAutoPhaseEstimate(), getPhasem(), TravelingWave::initialise(), TravelingWave::setPhasem(), and setPhasem().
phase_name_m
std::string RFCavity::phase_name_m protected
Definition at line 209 of file RFCavity.h.
Referenced by getPhaseModelName(), and setPhaseModelName().
phase_td_m
std::shared_ptr<AbstractTimeDependence> RFCavity::phase_td_m protected
Definition at line 208 of file RFCavity.h.
Referenced by setPhaseModel().
phaseError_m
double RFCavity::phaseError_m protected
phase shift error (rad)
Definition at line 220 of file RFCavity.h.
Referenced by TravelingWave::apply(), apply(), getPhaseError(), and setPhaseError().
phi0_m
double RFCavity::phi0_m private
Definition at line 243 of file RFCavity.h.
Referenced by getMomentaKick(), getPhi0(), and setPhi0().
rmax_m
double RFCavity::rmax_m private
Definition at line 237 of file RFCavity.h.
Referenced by getMomentaKick(), getRmax(), and setRmax().
rmin_m
double RFCavity::rmin_m private
Definition at line 236 of file RFCavity.h.
Referenced by getMomentaKick(), getRmin(), and setRmin().
RNormal_m
std::unique_ptr<double[]> RFCavity::RNormal_m private
Definition at line 245 of file RFCavity.h.
Referenced by initialise(), and spline().
scale_m
double RFCavity::scale_m protected
scale multiplier
Definition at line 217 of file RFCavity.h.
Referenced by TravelingWave::apply(), apply(), TravelingWave::applyToReferenceParticle(), applyToReferenceParticle(), getAmplitudem(), TravelingWave::getAutoPhaseEstimate(), getAutoPhaseEstimate(), getMomentaKick(), TravelingWave::initialise(), and setAmplitudem().
scaleError_m
double RFCavity::scaleError_m protected
additive scale error
Definition at line 218 of file RFCavity.h.
Referenced by TravelingWave::apply(), apply(), getAmplitudeError(), TravelingWave::initialise(), and setAmplitudeError().
sinAngle_m
double RFCavity::sinAngle_m private
Definition at line 239 of file RFCavity.h.
Referenced by getMomentaKick(), getSinAzimuth(), and initialise().
startField_m
double RFCavity::startField_m protected
starting point of field(m)
Definition at line 229 of file RFCavity.h.
Referenced by apply(), applyToReferenceParticle(), getDimensions(), getEdgeToBegin(), getEdgeToEnd(), TravelingWave::initialise(), initialise(), and trackOnAxisParticle().
type_m
CavityType RFCavity::type_m private
Definition at line 234 of file RFCavity.h.
Referenced by getComponentType(), and setComponentType().
VrNormal_m
std::unique_ptr<double[]> RFCavity::VrNormal_m private
Definition at line 246 of file RFCavity.h.
Referenced by initialise(), and spline().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/RFCavity.h
src/Classic/AbsBeamline/RFCavity.cpp