OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/Interpolator.h File Reference
Interpolator.h File Reference
#include "Field/BareField.h"
#include "Field/LField.h"
#include "Field/CompressedBrickIterator.h"
#include "Index/NDIndex.h"
#include "Meshes/Centering.h"
#include "AppTypes/Vektor.h"
#include "Utility/IpplInfo.h"
#include "Utility/IpplException.h"
#include <ostream>
#include <vector>
Classes
class CenteringTag< C >
struct InterpolatorTraits< T, Dim, InterpolatorType >
struct CacheData1< T, Dim >
struct CacheDataCIC< T, Dim >
struct CacheDataTSC< T, Dim >
class Interpolator
Functions
template<class PT , unsigned Dim, class M >
NDIndex< Dim > FindNGP (const M &mesh, const Vektor< PT, Dim > &ppos, CenteringTag< Cell >)
template<class PT , unsigned Dim, class M >
NDIndex< Dim > FindNGP (const M &mesh, const Vektor< PT, Dim > &ppos, CenteringTag< Vert >)
template<class PT , unsigned Dim, class M >
std::vector< NDIndex< Dim > > FindNGP (const M &mesh, const Vektor< PT, Dim > &ppos, CenteringTag< Edge >)
template<class PT , unsigned Dim, class M >
void FindPos (Vektor< PT, Dim > &pos, const M &mesh, const NDIndex< Dim > &indices, CenteringTag< Cell >)
template<class PT , unsigned Dim, class M >
void FindPos (Vektor< PT, Dim > &pos, const M &mesh, const NDIndex< Dim > &indices, CenteringTag< Vert >)
template<class PT , unsigned Dim, class M >
void FindPos (std::vector< Vektor< PT, Dim > > &pos, const M &mesh, const std::vector< NDIndex< Dim > > &indices, CenteringTag< Edge >)
template<class PT , unsigned Dim, class M >
void FindDelta (Vektor< PT, Dim > &delta, const M &mesh, const NDIndex< Dim > &gp, CenteringTag< Cell >)
template<class PT , unsigned Dim, class M >
void FindDelta (Vektor< PT, Dim > &delta, const M &mesh, const NDIndex< Dim > &gp, CenteringTag< Vert >)
template<class PT , unsigned Dim, class M >
void FindDelta (std::vector< Vektor< PT, Dim > > &delta, const M &mesh, const std::vector< NDIndex< Dim > > &gp, CenteringTag< Edge >)
template<class T , unsigned Dim>
std::ostream & operator<< (std::ostream &o, const CacheData1< T, Dim > &c)
template<class T , unsigned Dim>
std::ostream & operator<< (std::ostream &o, const CacheDataCIC< T, Dim > &c)
Function Documentation
FindDelta() [1/3]
template<class PT , unsigned Dim, class M > void FindDelta (Vektor< PT, Dim > & delta, const M & mesh, const NDIndex< Dim > & gp, CenteringTag< Cell >) inline
Definition at line 95 of file Interpolator.h.
References Dim.
Referenced by IntSUDSImpl< Dim >::gather(), IntCICImpl< Dim >::gather(), IntTSCImpl< Dim >::gather(), IntSUDSImpl< 1U >::gather(), IntTSCImpl< 1U >::gather(), IntCICImpl< 1U >::gather(), IntSUDSImpl< 2U >::gather(), IntTSCImpl< 2U >::gather(), IntSUDSImpl< 3U >::gather(), IntCICImpl< 2U >::gather(), IntTSCImpl< 3U >::gather(), IntCICImpl< 3U >::gather(), IntSUDSImpl< Dim >::scatter(), IntCICImpl< Dim >::scatter(), IntTSCImpl< Dim >::scatter(), IntSUDSImpl< 1U >::scatter(), IntCICImpl< 1U >::scatter(), IntTSCImpl< 1U >::scatter(), IntSUDSImpl< 2U >::scatter(), IntTSCImpl< 2U >::scatter(), IntCICImpl< 2U >::scatter(), IntSUDSImpl< 3U >::scatter(), IntTSCImpl< 3U >::scatter(), and IntCICImpl< 3U >::scatter().
FindDelta() [2/3]
template<class PT , unsigned Dim, class M > void FindDelta (Vektor< PT, Dim > & delta, const M & mesh, const NDIndex< Dim > & gp, CenteringTag< Vert >) inline
Definition at line 105 of file Interpolator.h.
FindDelta() [3/3]
template<class PT , unsigned Dim, class M > void FindDelta (std::vector< Vektor< PT, Dim > > & delta, const M & mesh, const std::vector< NDIndex< Dim > > & gp, CenteringTag< Edge >) inline
Definition at line 113 of file Interpolator.h.
References Dim.
FindNGP() [1/3]
template<class PT , unsigned Dim, class M > NDIndex<Dim> FindNGP (const M & mesh, const Vektor< PT, Dim > & ppos, CenteringTag< Cell >) inline
Definition at line 37 of file Interpolator.h.
Referenced by IntNGP::gather(), IntSUDSImpl< Dim >::gather(), IntCICImpl< Dim >::gather(), IntTSCImpl< Dim >::gather(), IntSUDSImpl< 1U >::gather(), IntTSCImpl< 1U >::gather(), IntCICImpl< 1U >::gather(), IntSUDSImpl< 2U >::gather(), IntTSCImpl< 2U >::gather(), IntSUDSImpl< 3U >::gather(), IntCICImpl< 2U >::gather(), IntTSCImpl< 3U >::gather(), IntCICImpl< 3U >::gather(), IntNGP::scatter(), IntSUDSImpl< Dim >::scatter(), IntCICImpl< Dim >::scatter(), IntTSCImpl< Dim >::scatter(), IntSUDSImpl< 1U >::scatter(), IntCICImpl< 1U >::scatter(), IntTSCImpl< 1U >::scatter(), IntSUDSImpl< 2U >::scatter(), IntTSCImpl< 2U >::scatter(), IntCICImpl< 2U >::scatter(), IntSUDSImpl< 3U >::scatter(), IntTSCImpl< 3U >::scatter(), and IntCICImpl< 3U >::scatter().
FindNGP() [2/3]
template<class PT , unsigned Dim, class M > NDIndex<Dim> FindNGP (const M & mesh, const Vektor< PT, Dim > & ppos, CenteringTag< Vert >) inline
Definition at line 44 of file Interpolator.h.
FindNGP() [3/3]
template<class PT , unsigned Dim, class M > std::vector<NDIndex<Dim> > FindNGP (const M & mesh, const Vektor< PT, Dim > & ppos, CenteringTag< Edge >) inline
Definition at line 51 of file Interpolator.h.
FindPos() [1/3]
template<class PT , unsigned Dim, class M > void FindPos (Vektor< PT, Dim > & pos, const M & mesh, const NDIndex< Dim > & indices, CenteringTag< Cell >) inline
Definition at line 62 of file Interpolator.h.
Referenced by IntSUDSImpl< Dim >::gather(), IntCICImpl< Dim >::gather(), IntTSCImpl< Dim >::gather(), IntSUDSImpl< 1U >::gather(), IntTSCImpl< 1U >::gather(), IntCICImpl< 1U >::gather(), IntSUDSImpl< 2U >::gather(), IntTSCImpl< 2U >::gather(), IntSUDSImpl< 3U >::gather(), IntCICImpl< 2U >::gather(), IntTSCImpl< 3U >::gather(), IntCICImpl< 3U >::gather(), IntSUDSImpl< Dim >::scatter(), IntCICImpl< Dim >::scatter(), IntTSCImpl< Dim >::scatter(), IntSUDSImpl< 1U >::scatter(), IntCICImpl< 1U >::scatter(), IntTSCImpl< 1U >::scatter(), IntSUDSImpl< 2U >::scatter(), IntTSCImpl< 2U >::scatter(), IntCICImpl< 2U >::scatter(), IntSUDSImpl< 3U >::scatter(), IntTSCImpl< 3U >::scatter(), and IntCICImpl< 3U >::scatter().
FindPos() [2/3]
template<class PT , unsigned Dim, class M > void FindPos (Vektor< PT, Dim > & pos, const M & mesh, const NDIndex< Dim > & indices, CenteringTag< Vert >) inline
Definition at line 70 of file Interpolator.h.
FindPos() [3/3]
template<class PT , unsigned Dim, class M > void FindPos (std::vector< Vektor< PT, Dim > > & pos, const M & mesh, const std::vector< NDIndex< Dim > > & indices, CenteringTag< Edge >) inline
Definition at line 78 of file Interpolator.h.
References Dim.
operator<<() [1/2]
template<class T , unsigned Dim> std::ostream& operator<< (std::ostream & o, const CacheData1< T, Dim > & c) inline
Definition at line 138 of file Interpolator.h.
References Physics::c.
operator<<() [2/2]
template<class T , unsigned Dim> std::ostream& operator<< (std::ostream & o, const CacheDataCIC< T, Dim > & c) inline
Definition at line 163 of file Interpolator.h.
References Physics::c, and Dim.