OPAL (Object Oriented Parallel Accelerator Library): SocialNetworkGraph< TopoDiscoveryStrategy_t > Class Template Reference
SocialNetworkGraph< TopoDiscoveryStrategy_t > Class Template Reference
#include <SocialNetworkGraph.h>
Inherits TopoDiscoveryStrategy_t.
Public Member Functions
std::set< size_t > execute (size_t numMasters, size_t dimensions, size_t id, int)
Private Member Functions
void setNetworkNeighbors ()
double manhattenDistance (size_t from, size_t to)
void chooseRandomNeighbor ()
Private Attributes
boost::random::mt19937 gen_
double alpha_
size_t numMasters_
size_t dim_
size_t myID_
size_t randomNeighbor_
std::set< size_t > realNetworkNeighborPIDs_
Detailed Description
template<class TopoDiscoveryStrategy_t>
class SocialNetworkGraph< TopoDiscoveryStrategy_t >
Definition at line 48 of file SocialNetworkGraph.h.
Member Function Documentation
chooseRandomNeighbor()
template<class TopoDiscoveryStrategy_t > void SocialNetworkGraph< TopoDiscoveryStrategy_t >::chooseRandomNeighbor () inline private
compute random neighbor using power law distribution with \(\alpha = 2\).
Definition at line 131 of file SocialNetworkGraph.h.
References SocialNetworkGraph< TopoDiscoveryStrategy_t >::alpha_, SocialNetworkGraph< TopoDiscoveryStrategy_t >::gen_, SocialNetworkGraph< TopoDiscoveryStrategy_t >::manhattenDistance(), SocialNetworkGraph< TopoDiscoveryStrategy_t >::myID_, SocialNetworkGraph< TopoDiscoveryStrategy_t >::numMasters_, pow(), SocialNetworkGraph< TopoDiscoveryStrategy_t >::randomNeighbor_, and sum().
Referenced by SocialNetworkGraph< TopoDiscoveryStrategy_t >::execute().
execute()
template<class TopoDiscoveryStrategy_t > std::set<size_t> SocialNetworkGraph< TopoDiscoveryStrategy_t >::execute (size_t numMasters, size_t dimensions, size_t id, int) inline
Definition at line 52 of file SocialNetworkGraph.h.
References SocialNetworkGraph< TopoDiscoveryStrategy_t >::chooseRandomNeighbor(), SocialNetworkGraph< TopoDiscoveryStrategy_t >::dim_, SocialNetworkGraph< TopoDiscoveryStrategy_t >::myID_, SocialNetworkGraph< TopoDiscoveryStrategy_t >::numMasters_, SocialNetworkGraph< TopoDiscoveryStrategy_t >::realNetworkNeighborPIDs_, and SocialNetworkGraph< TopoDiscoveryStrategy_t >::setNetworkNeighbors().
manhattenDistance()
template<class TopoDiscoveryStrategy_t > double SocialNetworkGraph< TopoDiscoveryStrategy_t >::manhattenDistance (size_t from, size_t to) inline private
Definition at line 118 of file SocialNetworkGraph.h.
References abs(), SocialNetworkGraph< TopoDiscoveryStrategy_t >::numMasters_, and sqrt().
Referenced by SocialNetworkGraph< TopoDiscoveryStrategy_t >::chooseRandomNeighbor().
setNetworkNeighbors()
template<class TopoDiscoveryStrategy_t > void SocialNetworkGraph< TopoDiscoveryStrategy_t >::setNetworkNeighbors () inline private
Definition at line 77 of file SocialNetworkGraph.h.
References SocialNetworkGraph< TopoDiscoveryStrategy_t >::myID_, SocialNetworkGraph< TopoDiscoveryStrategy_t >::numMasters_, SocialNetworkGraph< TopoDiscoveryStrategy_t >::realNetworkNeighborPIDs_, and sqrt().
Referenced by SocialNetworkGraph< TopoDiscoveryStrategy_t >::execute().
Member Data Documentation
alpha_
template<class TopoDiscoveryStrategy_t > double SocialNetworkGraph< TopoDiscoveryStrategy_t >::alpha_ private
Definition at line 68 of file SocialNetworkGraph.h.
Referenced by SocialNetworkGraph< TopoDiscoveryStrategy_t >::chooseRandomNeighbor().
dim_
template<class TopoDiscoveryStrategy_t > size_t SocialNetworkGraph< TopoDiscoveryStrategy_t >::dim_ private
Definition at line 71 of file SocialNetworkGraph.h.
Referenced by SocialNetworkGraph< TopoDiscoveryStrategy_t >::execute().
gen_
template<class TopoDiscoveryStrategy_t > boost::random::mt19937 SocialNetworkGraph< TopoDiscoveryStrategy_t >::gen_ private
Definition at line 67 of file SocialNetworkGraph.h.
Referenced by SocialNetworkGraph< TopoDiscoveryStrategy_t >::chooseRandomNeighbor().
myID_
template<class TopoDiscoveryStrategy_t > size_t SocialNetworkGraph< TopoDiscoveryStrategy_t >::myID_ private
Definition at line 72 of file SocialNetworkGraph.h.
Referenced by SocialNetworkGraph< TopoDiscoveryStrategy_t >::chooseRandomNeighbor(), SocialNetworkGraph< TopoDiscoveryStrategy_t >::execute(), and SocialNetworkGraph< TopoDiscoveryStrategy_t >::setNetworkNeighbors().
numMasters_
template<class TopoDiscoveryStrategy_t > size_t SocialNetworkGraph< TopoDiscoveryStrategy_t >::numMasters_ private
Definition at line 70 of file SocialNetworkGraph.h.
Referenced by SocialNetworkGraph< TopoDiscoveryStrategy_t >::chooseRandomNeighbor(), SocialNetworkGraph< TopoDiscoveryStrategy_t >::execute(), SocialNetworkGraph< TopoDiscoveryStrategy_t >::manhattenDistance(), and SocialNetworkGraph< TopoDiscoveryStrategy_t >::setNetworkNeighbors().
randomNeighbor_
template<class TopoDiscoveryStrategy_t > size_t SocialNetworkGraph< TopoDiscoveryStrategy_t >::randomNeighbor_ private
Definition at line 74 of file SocialNetworkGraph.h.
Referenced by SocialNetworkGraph< TopoDiscoveryStrategy_t >::chooseRandomNeighbor().
realNetworkNeighborPIDs_
template<class TopoDiscoveryStrategy_t > std::set<size_t> SocialNetworkGraph< TopoDiscoveryStrategy_t >::realNetworkNeighborPIDs_ private
Definition at line 75 of file SocialNetworkGraph.h.
Referenced by SocialNetworkGraph< TopoDiscoveryStrategy_t >::execute(), and SocialNetworkGraph< TopoDiscoveryStrategy_t >::setNetworkNeighbors().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/optimizer/Comm/MasterGraph/SocialNetworkGraph.h