OPAL (Object Oriented Parallel Accelerator Library): Attributes::StringArray Class Reference
Attributes::StringArray Class Reference
Parser for an attribute of type string array.
#include <StringArray.h>
Public Member Functions
StringArray (const std::string &name, const std::string &help)
Constructor.
virtual ~StringArray ()
virtual const std::string & getType () const
Return attribute type string `‘string array’'.
virtual void parse (Attribute &, Statement &, bool) const
Parse the attribute.
virtual void parseComponent (Attribute &, Statement &, bool, int) const
Parse a component of the array.
Public Member Functions inherited from AttributeHandler
AttributeHandler (const std::string &name, const std::string &help, AttributeBase *def)
Constructor.
virtual ~AttributeHandler ()
virtual AttributeHandler * clone () const
Make clone.
virtual AttributeBase * getDefault () const
Return default value.
virtual const std::string & getHelp () const
Return help string.
virtual const std::string & getName () const
Return attribute name.
bool isDeferred () const
Return defer flag.
void setDeferred (bool)
Set or reset defer flag.
bool isReadOnly () const
Return read-only flag.
void setReadOnly (bool)
Set or reset read-only flag.
void setPredefinedValues (const std::set< std::string > &, const std::string &)
Add predefined strings values to the help.
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
StringArray ()
StringArray (const StringArray &)
void operator= (const StringArray &)
Additional Inherited Members
Public Types inherited from AttributeHandler
enum OwnerType {
ELEMENT, COMMAND, SUB_COMMAND, STATEMENT,
NONE
}
Static Public Member Functions inherited from AttributeHandler
static std::multimap< OwnerType, std::string > getOwner (const std::string &att)
static void addAttributeOwner (const std::string &owner, const OwnerType &type, const std::string &name)
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from AttributeHandler
const std::string itsName
Attribute name.
const std::string itsHelp
Help text.
Pointer< AttributeBase > itsDefault
Default value.
bool is_deferred
Defer flag.
bool is_readonly
Read-only flag.
Detailed Description
Parser for an attribute of type string array.
Definition at line 32 of file StringArray.h.
Constructor & Destructor Documentation
StringArray() [1/3]
Attributes::StringArray::StringArray (const std::string & name, const std::string & help)
Constructor.
Definition at line 35 of file StringArray.cpp.
~StringArray()
Attributes::StringArray::~StringArray () virtual
Definition at line 40 of file StringArray.cpp.
StringArray() [2/3]
Attributes::StringArray::StringArray () private
StringArray() [3/3]
Attributes::StringArray::StringArray (const StringArray &) private
Member Function Documentation
getType()
const std::string & Attributes::StringArray::getType () const virtual
Return attribute type string `‘string array’'.
Implements AttributeHandler.
Definition at line 44 of file StringArray.cpp.
operator=()
void Attributes::StringArray::operator= (const StringArray &) private
parse()
void Attributes::StringArray::parse (Attribute & attr, Statement & stat, bool) const virtual
Parse the attribute.
Implements AttributeHandler.
Definition at line 50 of file StringArray.cpp.
References Expressions::parseStringArray(), and Attributes::setStringArray().
parseComponent()
void Attributes::StringArray::parseComponent (Attribute & attr, Statement & statement, bool , int index) const virtual
Parse a component of the array.
Reimplemented from AttributeHandler.
Definition at line 56 of file StringArray.cpp.
References Attribute::getBase(), Attributes::getStringArray(), Expressions::parseStringValue(), and Attributes::setStringArray().
The documentation for this class was generated from the following files:
src/Attributes/StringArray.h
src/Attributes/StringArray.cpp