OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/ParticleBalancer.hpp File Reference
ParticleBalancer.hpp File Reference
#include "Particle/ParticleBalancer.h"
#include "Particle/IpplParticleBase.h"
#include "Particle/ParticleSpatialLayout.h"
#include "Particle/ParticleUniformLayout.h"
#include "Particle/ParticleAttrib.h"
#include "Particle/IntNGP.h"
#include "Region/RegionLayout.h"
#include "Index/NDIndex.h"
#include "FieldLayout/FieldLayout.h"
#include "FieldLayout/BinaryBalancer.h"
#include "Utility/IpplInfo.h"
Functions
template<class T , unsigned Dim, class Mesh , class CachingPolicy >
bool BinaryRepartition (IpplParticleBase< ParticleSpatialLayout< T, Dim, Mesh, CachingPolicy > > &PB, double offset)
template<class T , unsigned Dim>
bool BinaryRepartition (IpplParticleBase< ParticleUniformLayout< T, Dim > > &, double)
Function Documentation
BinaryRepartition() [1/2]
template<class T , unsigned Dim, class Mesh , class CachingPolicy > bool BinaryRepartition (IpplParticleBase< ParticleSpatialLayout< T, Dim, Mesh, CachingPolicy > > & PB, double offset)
Definition at line 46 of file ParticleBalancer.hpp.
References IpplInfo::abort(), CalcBinaryRepartition(), Dim, endl(), ERRORMSG, FieldLayout< Dim >::getDomain(), RegionLayout< T, Dim, MeshType >::getFieldLayout(), RegionLayout< T, Dim, MeshType >::getMesh(), RegionLayout< T, Dim, MeshType >::initialized(), RegionLayout< T, Dim, MeshType >::RepartitionLayout(), and scatter().
BinaryRepartition() [2/2]
template<class T , unsigned Dim> bool BinaryRepartition (IpplParticleBase< ParticleUniformLayout< T, Dim > > & , double)
Definition at line 144 of file ParticleBalancer.hpp.