OPAL (Object Oriented Parallel Accelerator Library): FieldSolver Class Reference
FieldSolver Class Reference
#include <FieldSolver.h>
Public Member Functions
FieldSolver ()
Exemplar constructor.
virtual ~FieldSolver ()
virtual FieldSolver * clone (const std::string &name)
Make clone.
std::string getType ()
double getMX () const
Return meshsize.
double getMY () const
Return meshsize.
double getMT () const
Return meshsize.
void setMX (double)
Store emittance for mode 1.
void setMY (double)
Store emittance for mode 2.
void setMT (double)
Store emittance for mode 3.
virtual void update ()
Update the field solver data.
virtual void execute ()
Execute (init) the field solver data.
void initCartesianFields ()
void initSolver (PartBunchBase< double, 3 > *b)
bool hasValidSolver ()
void setFieldSolverType ()
FieldSolverType getFieldSolverType () const
Layout_t & getParticleLayout ()
FieldLayout_t * getFieldLayout ()
Inform & printInfo (Inform &os) const
unsigned int getInteractionRadius ()
bool hasPeriodicZ ()
bool isAmrSolverType () const
AmrObject * getAmrObject ()
const AmrObject * getAmrObject () const
Public Member Functions inherited from Definition
virtual ~Definition ()
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static FieldSolver * find (const std::string &name)
Find named FieldSolver.
Public Attributes
PoissonSolver * solver_m
the actual solver, should be a base object
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Private Member Functions
std::string getTagging_m () const
void initAmrObject_m ()
void initAmrSolver_m ()
FieldSolver (const FieldSolver &)
void operator= (const FieldSolver &)
FieldSolver (const std::string &name, FieldSolver *parent)
Private Attributes
std::unique_ptr< AmrObject > itsAmrObject_mp
Mesh_t * mesh_m
The cartesian mesh.
FieldLayout_t * FL_m
The field layout f.
std::unique_ptr< Layout_t > PL_m
The particle layout.
PartBunchBase< double, 3 > * itsBunch_m
all the particles are here ...
std::string fsName_m
FieldSolverType fsType_m
double rpp_m
Additional Inherited Members
Protected Member Functions inherited from Definition
Definition (int size, const char *name, const char *help)
Constructor for exemplars.
Definition (const std::string &name, Definition *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 52 of file FieldSolver.h.
Constructor & Destructor Documentation
FieldSolver() [1/3]
FieldSolver::FieldSolver ()
Exemplar constructor.
Definition at line 126 of file FieldSolver.cpp.
References ALPHA, Physics::e, FL_m, Object::itsAttr, Attributes::makeBool(), Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeRealArray(), Attributes::makeUpperCaseString(), mesh_m, Attrib::Distribution::MT, Attrib::Distribution::MX, Attrib::Distribution::MY, PL_m, Object::registerOwnership(), Attributes::setRealArray(), solver_m, and AttributeHandler::STATEMENT.
Referenced by clone().
~FieldSolver()
FieldSolver::~FieldSolver () virtual
Definition at line 362 of file FieldSolver.cpp.
References FL_m, mesh_m, and solver_m.
FieldSolver() [2/3]
FieldSolver::FieldSolver (const FieldSolver &) private
FieldSolver() [3/3]
FieldSolver::FieldSolver (const std::string & name, FieldSolver * parent) private
Definition at line 352 of file FieldSolver.cpp.
References FL_m, mesh_m, PL_m, and solver_m.
Member Function Documentation
clone()
FieldSolver * FieldSolver::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 377 of file FieldSolver.cpp.
References FieldSolver(), and name.
execute()
void FieldSolver::execute () virtual
Execute (init) the field solver data.
Reimplemented from Object.
Definition at line 381 of file FieldSolver.cpp.
References setFieldSolverType(), and update().
find()
FieldSolver * FieldSolver::find (const std::string & name) static
Find named FieldSolver.
Definition at line 386 of file FieldSolver.cpp.
References OpalData::find(), Hypervolume::fs, OpalData::getInstance(), and name.
Referenced by TrackRun::setupFieldsolver().
getAmrObject() [1/2]
AmrObject* FieldSolver::getAmrObject () inline
Definition at line 114 of file FieldSolver.h.
References itsAmrObject_mp.
Referenced by AmrPartBunch::setSolver().
getAmrObject() [2/2]
const AmrObject* FieldSolver::getAmrObject () const inline
Definition at line 118 of file FieldSolver.h.
References itsAmrObject_mp.
getFieldLayout()
FieldLayout_t* FieldSolver::getFieldLayout () inline
Definition at line 103 of file FieldSolver.h.
References FL_m.
Referenced by PartBunchBase< double, 3 >::setSolver().
getFieldSolverType()
FieldSolverType FieldSolver::getFieldSolverType () const inline
Definition at line 164 of file FieldSolver.h.
References fsType_m.
Referenced by PartBunchBase< double, 3 >::boundp(), PartBunch::computeSelfFields(), PartBunch::computeSelfFields_cycl(), PartBunchBase< double, 3 >::getFieldSolverType(), PartBunch::resizeMesh(), and TrackRun::setupFieldsolver().
getInteractionRadius()
unsigned int FieldSolver::getInteractionRadius () inline
Definition at line 107 of file FieldSolver.h.
References rpp_m.
getMT()
double FieldSolver::getMT () const
Return meshsize.
Definition at line 407 of file FieldSolver.cpp.
References Attributes::getReal(), Object::itsAttr, and Attrib::Distribution::MT.
Referenced by initAmrObject_m(), initCartesianFields(), and TrackRun::setupFieldsolver().
getMX()
double FieldSolver::getMX () const
Return meshsize.
Definition at line 399 of file FieldSolver.cpp.
References Attributes::getReal(), Object::itsAttr, and Attrib::Distribution::MX.
Referenced by initAmrObject_m(), initCartesianFields(), and TrackRun::setupFieldsolver().
getMY()
double FieldSolver::getMY () const
Return meshsize.
Definition at line 403 of file FieldSolver.cpp.
References Attributes::getReal(), Object::itsAttr, and Attrib::Distribution::MY.
Referenced by initAmrObject_m(), initCartesianFields(), and TrackRun::setupFieldsolver().
getParticleLayout()
Layout_t& FieldSolver::getParticleLayout () inline
Definition at line 101 of file FieldSolver.h.
References PL_m.
getTagging_m()
std::string FieldSolver::getTagging_m () const private
Definition at line 709 of file FieldSolver.cpp.
References Attributes::getString(), AmrObject::getTaggingString(), Util::isAllDigits(), and Object::itsAttr.
Referenced by initAmrObject_m(), and printInfo().
getType()
std::string FieldSolver::getType ()
Definition at line 395 of file FieldSolver.cpp.
References Attributes::getString(), and Object::itsAttr.
Referenced by initAmrSolver_m(), and setFieldSolverType().
hasPeriodicZ()
bool FieldSolver::hasPeriodicZ ()
Definition at line 459 of file FieldSolver.cpp.
References Attributes::getString(), and Object::itsAttr.
Referenced by TrackRun::setupFieldsolver().
hasValidSolver()
bool FieldSolver::hasValidSolver ()
Definition at line 590 of file FieldSolver.cpp.
References solver_m.
Referenced by AmrPartBunch::computeSelfFields(), PartBunch::computeSelfFields(), PartBunch::computeSelfFields_cycl(), and PartBunchBase< double, 3 >::hasFieldSolver().
initAmrObject_m()
void FieldSolver::initAmrObject_m () private
Definition at line 720 of file FieldSolver.cpp.
References AmrBoxLib::create(), getMT(), getMX(), getMY(), Attributes::getReal(), Attributes::getRealArray(), getTagging_m(), AmrObject::AmrInfo::grid, Options::info, itsAmrObject_mp, Object::itsAttr, itsBunch_m, AmrObject::AmrInfo::maxgrid, and PartBunchBase< T, Dim >::set_meshEnlargement().
Referenced by initSolver().
initAmrSolver_m()
void FieldSolver::initAmrSolver_m () private
Definition at line 762 of file FieldSolver.cpp.
References AMRMG, FMG, fsType_m, Attributes::getBool(), Attributes::getReal(), Attributes::getString(), getType(), HPGMG, HYPRE, itsAmrObject_mp, Object::itsAttr, ML, and solver_m.
Referenced by initSolver().
initCartesianFields()
void FieldSolver::initCartesianFields ()
Definition at line 427 of file FieldSolver.cpp.
References FL_m, Attributes::getBool(), getMT(), getMX(), getMY(), Attributes::getString(), isAmrSolverType(), Object::itsAttr, mesh_m, PARALLEL, PL_m, and SERIAL.
Referenced by TrackRun::setupFieldsolver().
initSolver()
void FieldSolver::initSolver (PartBunchBase< double, 3 > * b)
Definition at line 499 of file FieldSolver.cpp.
References ALPHA, Object::clear(), endl(), FFT, FFTBOX, BoundaryGeometry::find(), FL_m, fsName_m, fsType_m, BoundaryGeometry::getA(), OpalData::getGlobalGeometry(), OpalData::getInstance(), Attributes::getReal(), Attributes::getString(), INFOMSG, initAmrObject_m(), initAmrSolver_m(), isAmrSolverType(), Object::itsAttr, itsBunch_m, mesh_m, P3M, SAAMG, PartBunchBase< T, Dim >::set_meshEnlargement(), and solver_m.
Referenced by PartBunchBase< double, 3 >::setSolver().
isAmrSolverType()
bool FieldSolver::isAmrSolverType () const
Definition at line 466 of file FieldSolver.cpp.
References Options::amr, AMRMG, FMG, fsType_m, and ML.
Referenced by initCartesianFields(), initSolver(), and printInfo().
operator=()
void FieldSolver::operator= (const FieldSolver &) private
printInfo()
Inform & FieldSolver::printInfo (Inform & os) const
Definition at line 594 of file FieldSolver.cpp.
References ALPHA, Options::amr, AMRMG, endl(), FFT, fsName_m, fsType_m, Attributes::getBool(), IpplInfo::getNodes(), Object::getOpalName(), Attributes::getReal(), Attributes::getRealArray(), Attributes::getString(), getTagging_m(), INFOMSG, isAmrSolverType(), Object::itsAttr, level3(), mesh_m, Attrib::Distribution::MT, Attrib::Distribution::MX, Attrib::Distribution::MY, P3M, PL_m, SAAMG, and solver_m.
setFieldSolverType()
void FieldSolver::setFieldSolverType ()
Definition at line 477 of file FieldSolver.cpp.
References AMRMG, FFT, FFTBOX, FMG, fsName_m, fsType_m, getType(), HPGMG, HYPRE, ML, NONE, P3M, and SAAMG.
Referenced by execute().
setMT()
void FieldSolver::setMT (double value)
Store emittance for mode 3.
Definition at line 419 of file FieldSolver.cpp.
References Object::itsAttr, Attrib::Distribution::MT, and Attributes::setReal().
setMX()
void FieldSolver::setMX (double value)
Store emittance for mode 1.
Definition at line 411 of file FieldSolver.cpp.
References Object::itsAttr, Attrib::Distribution::MX, and Attributes::setReal().
setMY()
void FieldSolver::setMY (double value)
Store emittance for mode 2.
Definition at line 415 of file FieldSolver.cpp.
References Object::itsAttr, Attrib::Distribution::MY, and Attributes::setReal().
update()
void FieldSolver::update () virtual
Update the field solver data.
Reimplemented from Object.
Definition at line 423 of file FieldSolver.cpp.
Referenced by execute().
Member Data Documentation
FL_m
FieldLayout_t* FieldSolver::FL_m private
The field layout f.
Definition at line 149 of file FieldSolver.h.
Referenced by FieldSolver(), getFieldLayout(), initCartesianFields(), initSolver(), and ~FieldSolver().
fsName_m
std::string FieldSolver::fsName_m private
Definition at line 157 of file FieldSolver.h.
Referenced by initSolver(), printInfo(), and setFieldSolverType().
fsType_m
FieldSolverType FieldSolver::fsType_m private
Definition at line 158 of file FieldSolver.h.
Referenced by getFieldSolverType(), initAmrSolver_m(), initSolver(), isAmrSolverType(), printInfo(), and setFieldSolverType().
itsAmrObject_mp
std::unique_ptr<AmrObject> FieldSolver::itsAmrObject_mp private
Definition at line 135 of file FieldSolver.h.
Referenced by getAmrObject(), initAmrObject_m(), and initAmrSolver_m().
itsBunch_m
PartBunchBase<double, 3>* FieldSolver::itsBunch_m private
all the particles are here ...
Definition at line 155 of file FieldSolver.h.
Referenced by initAmrObject_m(), and initSolver().
mesh_m
Mesh_t* FieldSolver::mesh_m private
The cartesian mesh.
Definition at line 146 of file FieldSolver.h.
Referenced by FieldSolver(), initCartesianFields(), initSolver(), printInfo(), and ~FieldSolver().
PL_m
std::unique_ptr<Layout_t> FieldSolver::PL_m private
The particle layout.
Definition at line 152 of file FieldSolver.h.
Referenced by FieldSolver(), getParticleLayout(), initCartesianFields(), and printInfo().
rpp_m
double FieldSolver::rpp_m private
Definition at line 160 of file FieldSolver.h.
Referenced by getInteractionRadius().
solver_m
PoissonSolver* FieldSolver::solver_m
the actual solver, should be a base object
Definition at line 124 of file FieldSolver.h.
Referenced by PartBunchBase< double, 3 >::boundp(), PartBunch::computeSelfFields(), PartBunch::computeSelfFields_cycl(), FieldSolver(), AmrPartBunch::getFieldSolver(), hasValidSolver(), initAmrSolver_m(), initSolver(), printInfo(), PartBunch::resizeMesh(), and ~FieldSolver().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Structure/FieldSolver.h
/psi/home/gsell/data/src/OPAL/src/src/Structure/FieldSolver.cpp