OPAL (Object Oriented Parallel Accelerator Library): LF2< FieldFunction, Arguments > Class Template Reference
LF2< FieldFunction, Arguments > Class Template Reference
Leap-Frog 2nd order.
#include <LF2.h>
Public Member Functions
LF2 (const FieldFunction &fieldfunc)
Public Member Functions inherited from Stepper< FieldFunction, Arguments... >
Stepper (const FieldFunction &fieldfunc)
virtual bool advance (PartBunchBase< double, 3 > *bunch, const size_t &i, const double &t, const double dt, Arguments &... args) const
virtual ~Stepper ()
Private Member Functions
bool doAdvance_m (PartBunchBase< double, 3 > *bunch, const size_t &i, const double &t, const double dt, Arguments &... args) const
void push_m (Vector_t &R, const Vector_t &P, const double &h) const
bool kick_m (PartBunchBase< double, 3 > *bunch, const size_t &i, const double &t, const double &h, Arguments &... args) const
Additional Inherited Members
Protected Attributes inherited from Stepper< FieldFunction, Arguments... >
const FieldFunction & fieldfunc_m
Detailed Description
template<typename FieldFunction, typename ... Arguments>
class LF2< FieldFunction, Arguments >
Leap-Frog 2nd order.
Definition at line 26 of file LF2.h.
Constructor & Destructor Documentation
LF2()
template<typename FieldFunction , typename ... Arguments> LF2< FieldFunction, Arguments >::LF2 (const FieldFunction & fieldfunc) inline
Definition at line 29 of file LF2.h.
Member Function Documentation
doAdvance_m()
template<typename FieldFunction , typename ... Arguments> bool LF2< FieldFunction, Arguments >::doAdvance_m (PartBunchBase< double, 3 > * bunch, const size_t & i, const double & t, const double dt, Arguments &... args) const private virtual
Implements Stepper< FieldFunction, Arguments... >.
Definition at line 22 of file LF2.hpp.
References PartBunchBase< T, Dim >::P, and PartBunchBase< T, Dim >::R.
kick_m()
template<typename FieldFunction , typename ... Arguments> bool LF2< FieldFunction, Arguments >::kick_m (PartBunchBase< double, 3 > * bunch, const size_t & i, const double & t, const double & h, Arguments &... args) const private
Definition at line 54 of file LF2.hpp.
References Units::GeV2eV, BorisPusher::kick(), PartBunchBase< T, Dim >::M, PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::Q, Physics::q_e, and PartBunchBase< T, Dim >::R.
push_m()
template<typename FieldFunction , typename ... Arguments> void LF2< FieldFunction, Arguments >::push_m (Vector_t & R, const Vector_t & P, const double & h) const private
Definition at line 43 of file LF2.hpp.
References Physics::c, dot(), Attrib::Distribution::R, and sqrt().
The documentation for this class was generated from the following files:
src/Steppers/LF2.h
src/Steppers/LF2.hpp