OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/ParticleAttrib.h File Reference
ParticleAttrib.h File Reference
#include "Particle/ParticleAttribBase.h"
#include "Particle/ParticleAttribElem.h"
#include "Particle/PAssign.h"
#include "SubParticle/SubParticleAttrib.h"
#include "DataSource/DataSource.h"
#include "DataSource/MakeDataSource.h"
#include "PETE/IpplExpressions.h"
#include "Index/NDIndex.h"
#include "Utility/DiscType.h"
#include "Utility/Inform.h"
#include "Utility/IpplStats.h"
#include <vector>
#include <utility>
#include "Particle/ParticleAttrib.hpp"
Classes
class Vektor< T, D >
class Field< T, Dim, M, C >
class ParticleAttribIterator< T >
class ParticleAttribConstIterator< T >
class ParticleAttrib< T >
class ParticleAttribIterator< T >
class ParticleAttribConstIterator< T >
Functions
template<class T >
ParticleAttribIterator< T > operator+ (size_t n, const ParticleAttribIterator< T > &a)
template<class T >
ParticleAttribConstIterator< T > operator+ (size_t n, const ParticleAttribConstIterator< T > &a)
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp >
void scatter (const ParticleAttrib< FT > &attrib, Field< FT, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &intop)
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp , class CacheData >
void scatter (const ParticleAttrib< FT > &attrib, Field< FT, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &intop, ParticleAttrib< CacheData > &cache)
template<class FT , unsigned Dim, class M , class C , class IntOp , class CacheData >
void scatter (const ParticleAttrib< FT > &attrib, Field< FT, Dim, M, C > &f, const IntOp &intop, const ParticleAttrib< CacheData > &cache)
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp >
void gather (ParticleAttrib< FT > &attrib, const Field< FT, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &intop)
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp , class CacheData >
void gather (ParticleAttrib< FT > &attrib, const Field< FT, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &intop, ParticleAttrib< CacheData > &cache)
template<class FT , unsigned Dim, class M , class C , class CacheData , class IntOp >
void gather (ParticleAttrib< FT > &attrib, const Field< FT, Dim, M, C > &f, const IntOp &intop, const ParticleAttrib< CacheData > &cache)
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp >
void scatter (Field< FT, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &intop, FT val)
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp , class CacheData >
void scatter (Field< FT, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &intop, ParticleAttrib< CacheData > &cache, FT val)
template<class FT , unsigned Dim, class M , class C , class IntOp , class CacheData >
void scatter (Field< FT, Dim, M, C > &f, const IntOp &intop, const ParticleAttrib< CacheData > &cache, FT val)
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp >
void scatter (Field< FT, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &intop)
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp , class CacheData >
void scatter (Field< FT, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &intop, ParticleAttrib< CacheData > &cache)
template<class FT , unsigned Dim, class M , class C , class IntOp , class CacheData >
void scatter (Field< FT, Dim, M, C > &f, const IntOp &intop, const ParticleAttrib< CacheData > &cache)
Function Documentation
gather() [1/3]
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp > void gather (ParticleAttrib< FT > & attrib, const Field< FT, Dim, M, C > & f, const ParticleAttrib< Vektor< PT, Dim > > & pp, const IntOp & intop) inline
Definition at line 853 of file ParticleAttrib.h.
References ParticleAttrib< T >::gather().
Referenced by ParticleAttrib< ParticleOrigin >::gather().
gather() [2/3]
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp , class CacheData > void gather (ParticleAttrib< FT > & attrib, const Field< FT, Dim, M, C > & f, const ParticleAttrib< Vektor< PT, Dim > > & pp, const IntOp & intop, ParticleAttrib< CacheData > & cache) inline
Definition at line 863 of file ParticleAttrib.h.
References ParticleAttrib< T >::gather().
gather() [3/3]
template<class FT , unsigned Dim, class M , class C , class CacheData , class IntOp > void gather (ParticleAttrib< FT > & attrib, const Field< FT, Dim, M, C > & f, const IntOp & intop, const ParticleAttrib< CacheData > & cache) inline
Definition at line 874 of file ParticleAttrib.h.
References ParticleAttrib< T >::gather().
operator+() [1/2]
template<class T > ParticleAttribIterator<T> operator+ (size_t n, const ParticleAttribIterator< T > & a)
Definition at line 685 of file ParticleAttrib.h.
References a, and Hypervolume::n.
operator+() [2/2]
template<class T > ParticleAttribConstIterator<T> operator+ (size_t n, const ParticleAttribConstIterator< T > & a)
Definition at line 813 of file ParticleAttrib.h.
References a, and Hypervolume::n.
scatter() [1/9]
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp > void scatter (const ParticleAttrib< FT > & attrib, Field< FT, Dim, M, C > & f, const ParticleAttrib< Vektor< PT, Dim > > & pp, const IntOp & intop) inline
Definition at line 823 of file ParticleAttrib.h.
References ParticleAttrib< T >::scatter().
Referenced by ParticleAttrib< ParticleOrigin >::scatter(), and scatter().
scatter() [2/9]
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp , class CacheData > void scatter (const ParticleAttrib< FT > & attrib, Field< FT, Dim, M, C > & f, const ParticleAttrib< Vektor< PT, Dim > > & pp, const IntOp & intop, ParticleAttrib< CacheData > & cache) inline
Definition at line 833 of file ParticleAttrib.h.
References ParticleAttrib< T >::scatter().
scatter() [3/9]
template<class FT , unsigned Dim, class M , class C , class IntOp , class CacheData > void scatter (const ParticleAttrib< FT > & attrib, Field< FT, Dim, M, C > & f, const IntOp & intop, const ParticleAttrib< CacheData > & cache) inline
Definition at line 844 of file ParticleAttrib.h.
References ParticleAttrib< T >::scatter().
scatter() [4/9]
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp > void scatter (Field< FT, Dim, M, C > & f, const ParticleAttrib< Vektor< PT, Dim > > & pp, const IntOp & intop, FT val)
Definition at line 562 of file ParticleAttrib.hpp.
References BareField< T, Dim >::accumGuardCells(), ParticleAttrib< T >::cbegin(), Field< T, Dim, M, C >::get_mesh(), INCIPPLSTAT, BareField< T, Dim >::setGuardCells(), ParticleAttribConstIterator< T >::size(), and BareField< T, Dim >::Uncompress().
Referenced by scatter().
scatter() [5/9]
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp , class CacheData > void scatter (Field< FT, Dim, M, C > & f, const ParticleAttrib< Vektor< PT, Dim > > & pp, const IntOp & intop, ParticleAttrib< CacheData > & cache, FT val)
Definition at line 587 of file ParticleAttrib.hpp.
References BareField< T, Dim >::accumGuardCells(), ParticleAttrib< T >::begin(), Field< T, Dim, M, C >::get_mesh(), INCIPPLSTAT, scatter(), BareField< T, Dim >::setGuardCells(), ParticleAttribIterator< T >::size(), and BareField< T, Dim >::Uncompress().
scatter() [6/9]
template<class FT , unsigned Dim, class M , class C , class IntOp , class CacheData > void scatter (Field< FT, Dim, M, C > & f, const IntOp & intop, const ParticleAttrib< CacheData > & cache, FT val)
Definition at line 613 of file ParticleAttrib.hpp.
References BareField< T, Dim >::accumGuardCells(), ParticleAttrib< T >::begin(), INCIPPLSTAT, scatter(), BareField< T, Dim >::setGuardCells(), ParticleAttrib< T >::size(), and BareField< T, Dim >::Uncompress().
scatter() [7/9]
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp > void scatter (Field< FT, Dim, M, C > & f, const ParticleAttrib< Vektor< PT, Dim > > & pp, const IntOp & intop) inline
Definition at line 902 of file ParticleAttrib.h.
References scatter().
scatter() [8/9]
template<class FT , unsigned Dim, class M , class C , class PT , class IntOp , class CacheData > void scatter (Field< FT, Dim, M, C > & f, const ParticleAttrib< Vektor< PT, Dim > > & pp, const IntOp & intop, ParticleAttrib< CacheData > & cache) inline
Definition at line 911 of file ParticleAttrib.h.
References scatter().
scatter() [9/9]
template<class FT , unsigned Dim, class M , class C , class IntOp , class CacheData > void scatter (Field< FT, Dim, M, C > & f, const IntOp & intop, const ParticleAttrib< CacheData > & cache) inline
Definition at line 920 of file ParticleAttrib.h.
References scatter().