OPAL (Object Oriented Parallel Accelerator Library): IntSUDSImpl< 1U > Class Template Reference
IntSUDSImpl< 1U > Class Template Reference
#include <IntSUDS.h>
Public Member Functions
IntSUDSImpl ()
~IntSUDSImpl ()
Public Member Functions inherited from Interpolator
Interpolator ()
~Interpolator ()
Static Public Member Functions
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 1U, M, C > &f, const Vektor< PT, 1U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 1U, M, C > &f, const Vektor< PT, 1U > &ppos, const M &mesh, NDIndex< 1U > &ngp, Vektor< PT, 1U > &dpos)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 1U, M, C > &f, const NDIndex< 1U > &ngp, const Vektor< PT, 1U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 1U, M, C > &f, const Vektor< PT, 1U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 1U, M, C > &f, const Vektor< PT, 1U > &ppos, const M &mesh, NDIndex< 1U > &ngp, Vektor< PT, 1U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 1U, M, C > &f, const NDIndex< 1U > &ngp, const Vektor< PT, 1U > &dpos)
Additional Inherited Members
Static Protected Member Functions inherited from Interpolator
template<class T , unsigned Dim>
static CompressedBrickIterator< T, Dim > getFieldIter (const BareField< T, Dim > &f, const NDIndex< Dim > &pt)
Detailed Description
template<>
class IntSUDSImpl< 1U >
Definition at line 175 of file IntSUDS.h.
Constructor & Destructor Documentation
IntSUDSImpl()
IntSUDSImpl< 1U >::IntSUDSImpl () inline
Definition at line 179 of file IntSUDS.h.
~IntSUDSImpl()
IntSUDSImpl< 1U >::~IntSUDSImpl () inline
Definition at line 180 of file IntSUDS.h.
Member Function Documentation
gather() [1/3]
template<class FT , class M , class C , class PT > static void IntSUDSImpl< 1U >::gather (FT & pdata, const Field< FT, 1U, M, C > & f, const Vektor< PT, 1U > & ppos, const M & mesh) inline static
Definition at line 255 of file IntSUDS.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
gather() [2/3]
template<class FT , class M , class C , class PT > static void IntSUDSImpl< 1U >::gather (FT & pdata, const Field< FT, 1U, M, C > & f, const Vektor< PT, 1U > & ppos, const M & mesh, NDIndex< 1U > & ngp, Vektor< PT, 1U > & dpos) inline static
Definition at line 281 of file IntSUDS.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
gather() [3/3]
template<class FT , class M , class C , class PT > static void IntSUDSImpl< 1U >::gather (FT & pdata, const Field< FT, 1U, M, C > & f, const NDIndex< 1U > & ngp, const Vektor< PT, 1U > & dpos) inline static
Definition at line 307 of file IntSUDS.h.
References Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
scatter() [1/3]
template<class FT , class M , class C , class PT > static void IntSUDSImpl< 1U >::scatter (const FT & pdata, Field< FT, 1U, M, C > & f, const Vektor< PT, 1U > & ppos, const M & mesh) inline static
Definition at line 187 of file IntSUDS.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
scatter() [2/3]
template<class FT , class M , class C , class PT > static void IntSUDSImpl< 1U >::scatter (const FT & pdata, Field< FT, 1U, M, C > & f, const Vektor< PT, 1U > & ppos, const M & mesh, NDIndex< 1U > & ngp, Vektor< PT, 1U > & dpos) inline static
Definition at line 214 of file IntSUDS.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
scatter() [3/3]
template<class FT , class M , class C , class PT > static void IntSUDSImpl< 1U >::scatter (const FT & pdata, Field< FT, 1U, M, C > & f, const NDIndex< 1U > & ngp, const Vektor< PT, 1U > & dpos) inline static
Definition at line 241 of file IntSUDS.h.
References Interpolator::getFieldIter(), and BrickIterator< T, Dim >::offset().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/IntSUDS.h