OPAL (Object Oriented Parallel Accelerator Library): PutSingleItem< T, false, false > Struct Template Reference
PutSingleItem< T, false, false > Struct Template Reference
#include <Message.h>
Static Public Member Functions
static Message & put (Message &, const T &)
static Message & get (Message &, T &)
static Message & put (Message &, T, T)
static Message & put (Message &, const std::vector< size_t > &, T)
static Message & get_iter (Message &, T)
Detailed Description
template<class T>
struct PutSingleItem< T, false, false >
Definition at line 102 of file Message.h.
Member Function Documentation
get()
template<class T > Message & PutSingleItem< T, false, false >::get (Message & msg, T & value) static
Definition at line 34 of file Message.hpp.
get_iter()
template<class T > Message & PutSingleItem< T, false, false >::get_iter (Message & m, T o) static
Definition at line 121 of file Message.hpp.
References Message::MsgItem::data(), Message::empty(), endl(), ERRORMSG, Message::get(), Message::item(), Message::MsgItem::numElems(), and value_type().
put() [1/3]
template<class T > Message & PutSingleItem< T, false, false >::put (Message & msg, const T & cvalue) static
Definition at line 25 of file Message.hpp.
References Attrib::Legacy::Distribution::T.
put() [2/3]
template<class T > Message & PutSingleItem< T, false, false >::put (Message & m, T beg, T end) static
Definition at line 42 of file Message.hpp.
References end(), Message::putmsg(), Message::setCopy(), Message::setDelete(), Attrib::Legacy::Distribution::T, value_type(), and Message::willCopy().
put() [3/3]
template<class T > Message & PutSingleItem< T, false, false >::put (Message & m, const std::vector< size_t > & indices, T beg) static
Definition at line 87 of file Message.hpp.
References Message::putmsg(), Message::setCopy(), Message::setDelete(), Message::size(), and value_type().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Message/Message.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Message/Message.hpp