OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/FieldLayout/CenteredFieldLayout.hpp File Reference
CenteredFieldLayout.hpp File Reference
#include "FieldLayout/CenteredFieldLayout.h"
#include "Meshes/Centering.h"
#include "Meshes/CartesianCentering.h"
#include "Utility/PAssert.h"
Functions
template<unsigned Dim, class Mesh >
void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Cell > &cfl, const Mesh &mesh, e_dim_tag *edt, int vnodes)
template<unsigned Dim, class Mesh >
void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Vert > &cfl, const Mesh &mesh, e_dim_tag *edt, int vnodes)
template<unsigned Dim, class Mesh >
void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Edge > &cfl, const Mesh &mesh, e_dim_tag *edt, int vnodes)
template<CenteringEnum * CE, unsigned Dim, class Mesh , unsigned NComponents>
void centeredInitialize (CenteredFieldLayout< Dim, Mesh, CartesianCentering< CE, Dim, NComponents > > &cfl, const Mesh &mesh, e_dim_tag *edt, int vnodes)
template<unsigned Dim, class Mesh >
void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Cell > &cfl, const Mesh &mesh, e_dim_tag *edt, unsigned *vnodesAlongDirection, bool recurse, int vnodes)
template<unsigned Dim, class Mesh >
void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Vert > &cfl, const Mesh &mesh, e_dim_tag *edt, unsigned *vnodesAlongDirection, bool recurse, int vnodes)
template<unsigned Dim, class Mesh >
void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Edge > &cfl, const Mesh &mesh, e_dim_tag *edt, unsigned *vnodesAlongDirection, bool recurse, int vnodes)
template<CenteringEnum * CE, unsigned Dim, class Mesh , unsigned NComponents>
void centeredInitialize (CenteredFieldLayout< Dim, Mesh, CartesianCentering< CE, Dim, NComponents > > &cfl, const Mesh &mesh, e_dim_tag *edt, unsigned *vnodesAlongDirection, bool recurse, int vnodes)
template<unsigned Dim, class Mesh >
void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Cell > &cfl, const Mesh &mesh, const NDIndex< Dim > *dombegin, const NDIndex< Dim > *domend, const int *nbegin, const int *nend)
template<unsigned Dim, class Mesh >
void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Vert > &cfl, const Mesh &mesh, const NDIndex< Dim > *dombegin, const NDIndex< Dim > *domend, const int *nbegin, const int *nend)
template<unsigned Dim, class Mesh >
void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Edge > &cfl, const Mesh &mesh, const NDIndex< Dim > *dombegin, const NDIndex< Dim > *domend, const int *nbegin, const int *nend)
template<CenteringEnum * CE, unsigned Dim, class Mesh , unsigned NComponents>
void centeredInitialize (CenteredFieldLayout< Dim, Mesh, CartesianCentering< CE, Dim, NComponents > > &cfl, const Mesh &mesh, const NDIndex< Dim > *dombegin, const NDIndex< Dim > *domend, const int *nbegin, const int *nend)
Function Documentation
centeredInitialize() [1/12]
template<unsigned Dim, class Mesh > void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Cell > & cfl, const Mesh & mesh, e_dim_tag * edt, int vnodes) inline
Definition at line 50 of file CenteredFieldLayout.hpp.
References Dim, and FieldLayout< Dim >::initialize().
Referenced by CenteredFieldLayout< Dim, Mesh, Centering >::CenteredFieldLayout().
centeredInitialize() [2/12]
template<unsigned Dim, class Mesh > void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Vert > & cfl, const Mesh & mesh, e_dim_tag * edt, int vnodes) inline
Definition at line 64 of file CenteredFieldLayout.hpp.
References Dim, and FieldLayout< Dim >::initialize().
centeredInitialize() [3/12]
template<unsigned Dim, class Mesh > void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Edge > & cfl, const Mesh & mesh, e_dim_tag * edt, int vnodes) inline
Definition at line 78 of file CenteredFieldLayout.hpp.
References Dim, and FieldLayout< Dim >::initialize().
centeredInitialize() [4/12]
template<CenteringEnum * CE, unsigned Dim, class Mesh , unsigned NComponents> void centeredInitialize (CenteredFieldLayout< Dim, Mesh, CartesianCentering< CE, Dim, NComponents > > & cfl, const Mesh & mesh, e_dim_tag * edt, int vnodes) inline
Definition at line 93 of file CenteredFieldLayout.hpp.
References Physics::c, CELL, Dim, and max().
centeredInitialize() [5/12]
template<unsigned Dim, class Mesh > void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Cell > & cfl, const Mesh & mesh, e_dim_tag * edt, unsigned * vnodesAlongDirection, bool recurse, int vnodes) inline
Definition at line 132 of file CenteredFieldLayout.hpp.
References Dim, and FieldLayout< Dim >::initialize().
centeredInitialize() [6/12]
template<unsigned Dim, class Mesh > void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Vert > & cfl, const Mesh & mesh, e_dim_tag * edt, unsigned * vnodesAlongDirection, bool recurse, int vnodes) inline
Definition at line 147 of file CenteredFieldLayout.hpp.
References Dim, and FieldLayout< Dim >::initialize().
centeredInitialize() [7/12]
template<unsigned Dim, class Mesh > void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Edge > & cfl, const Mesh & mesh, e_dim_tag * edt, unsigned * vnodesAlongDirection, bool recurse, int vnodes) inline
Definition at line 162 of file CenteredFieldLayout.hpp.
References Dim, and FieldLayout< Dim >::initialize().
centeredInitialize() [8/12]
template<CenteringEnum * CE, unsigned Dim, class Mesh , unsigned NComponents> void centeredInitialize (CenteredFieldLayout< Dim, Mesh, CartesianCentering< CE, Dim, NComponents > > & cfl, const Mesh & mesh, e_dim_tag * edt, unsigned * vnodesAlongDirection, bool recurse, int vnodes) inline
Definition at line 178 of file CenteredFieldLayout.hpp.
References Physics::c, CELL, Dim, and max().
centeredInitialize() [9/12]
template<unsigned Dim, class Mesh > void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Cell > & cfl, const Mesh & mesh, const NDIndex< Dim > * dombegin, const NDIndex< Dim > * domend, const int * nbegin, const int * nend) inline
Definition at line 214 of file CenteredFieldLayout.hpp.
References Dim, and FieldLayout< Dim >::initialize().
centeredInitialize() [10/12]
template<unsigned Dim, class Mesh > void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Vert > & cfl, const Mesh & mesh, const NDIndex< Dim > * dombegin, const NDIndex< Dim > * domend, const int * nbegin, const int * nend) inline
Definition at line 229 of file CenteredFieldLayout.hpp.
References Dim, and FieldLayout< Dim >::initialize().
centeredInitialize() [11/12]
template<unsigned Dim, class Mesh > void centeredInitialize (CenteredFieldLayout< Dim, Mesh, Edge > & cfl, const Mesh & mesh, const NDIndex< Dim > * dombegin, const NDIndex< Dim > * domend, const int * nbegin, const int * nend) inline
Definition at line 244 of file CenteredFieldLayout.hpp.
References Dim, and FieldLayout< Dim >::initialize().
centeredInitialize() [12/12]
template<CenteringEnum * CE, unsigned Dim, class Mesh , unsigned NComponents> void centeredInitialize (CenteredFieldLayout< Dim, Mesh, CartesianCentering< CE, Dim, NComponents > > & cfl, const Mesh & mesh, const NDIndex< Dim > * dombegin, const NDIndex< Dim > * domend, const int * nbegin, const int * nend) inline
Definition at line 260 of file CenteredFieldLayout.hpp.
References Physics::c, CELL, Dim, and max().