OPAL (Object Oriented Parallel Accelerator Library): FieldWriter Class Reference
FieldWriter Class Reference
#include <FieldWriter.h>
Public Member Functions
template<typename FieldType >
void dumpField (FieldType &field, std::string name, std::string unit, long long step, FieldType *image=nullptr)
Dump a scalar or vector field to a file.
Detailed Description
Definition at line 24 of file FieldWriter.h.
Member Function Documentation
dumpField()
template<typename FieldType > void FieldWriter::dumpField (FieldType & field, std::string name, std::string unit, long long step, FieldType * image = nullptr)
Dump a scalar or vector field to a file.
Definition at line 30 of file FieldWriter.hpp.
References endl(), OpalData::getAuxiliaryOutputDirectory(), OpalData::getInputBasename(), OpalData::getInstance(), IpplInfo::getNodes(), INFOMSG, name, and Util::toUpper().
Referenced by PartBunch::computeSelfFields(), and PartBunch::computeSelfFields_cycl().
The documentation for this class was generated from the following files:
src/Structure/FieldWriter.h
src/Structure/FieldWriter.hpp