OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Field/AssignGeneralIBF.hpp File Reference
AssignGeneralIBF.hpp File Reference
#include "Field/Assign.h"
#include "Field/AssignDefs.h"
#include "Field/BareField.h"
#include "Field/BrickExpression.h"
#include "Field/IndexedBareField.h"
#include "Field/LField.h"
#include "Message/Communicate.h"
#include "Message/Message.h"
#include "Utility/PAssert.h"
#include "Utility/IpplInfo.h"
#include "Utility/IpplStats.h"
#include "PETE/IpplExpressions.h"
#include <map>
#include <vector>
#include <functional>
#include <utility>
#include <iostream>
#include <typeinfo>
Classes
struct AssignTouches< D1, D2 >
struct AssignTouches< D1, D1 >
Functions
template<class T1 , class T2 , unsigned D1, unsigned D2>
void IndexedSend (IndexedBareField< T1, D1, D1 > &ilhs, IndexedBareField< T2, D2, D2 > &irhs, int tag)
template<class T1 , class T2 , unsigned D1, unsigned D2, class Container >
void CalcIndexedReceive (IndexedBareField< T1, D1, D1 > &ilhs, IndexedBareField< T2, D2, D2 > &irhs, Container &recv_ac, int &msgnum)
template<class T1 , class T2 , unsigned D1, unsigned D2, class Op >
void IndexedLocalAssign (IndexedBareField< T1, D1, D1 > &ilhs, IndexedBareField< T2, D2, D2 > &irhs, Op &op)
template<class T1 , class T2 , unsigned D1, unsigned D2, class Op , class Container >
void IndexedReceive (IndexedBareField< T1, D1, D1 > &ilhs, IndexedBareField< T2, D2, D2 > &, Op &op, Container &recv_ac, int msgnum, int tag)
template<class T1 , unsigned D1, class RHS , class Op >
void assign (IndexedBareField< T1, D1, D1 > lhs, RHS rhsp, Op op, ExprTag< false >)
Function Documentation
assign()
template<class T1 , unsigned D1, class RHS , class Op > void assign (IndexedBareField< T1, D1, D1 > lhs, RHS rhsp, Op op, ExprTag< false >)
Definition at line 502 of file AssignGeneralIBF.hpp.
References CalcIndexedReceive(), IpplInfo::Comm, endl(), ERRORMSG, F_GEN_ASSIGN_TAG, F_TAG_CYCLE, FillGCIfNecessary(), for_each(), IndexedBareField< T, Dim, Brackets >::getBareField(), IndexedBareField< T, Dim, Brackets >::getDomain(), IpplInfo::getNodes(), IndexedLocalAssign(), IndexedReceive(), IndexedSend(), TagMaker::next_tag(), and PAssert.
CalcIndexedReceive()
template<class T1 , class T2 , unsigned D1, unsigned D2, class Container > void CalcIndexedReceive (IndexedBareField< T1, D1, D1 > & ilhs, IndexedBareField< T2, D2, D2 > & irhs, Container & recv_ac, int & msgnum) inline
Definition at line 165 of file AssignGeneralIBF.hpp.
References ASSIGNMSG, BareField< T, Dim >::begin_if(), endl(), LField< T, Dim >::getAllocated(), IndexedBareField< T, Dim, Brackets >::getBareField(), IndexedBareField< T, Dim, Brackets >::getDomain(), BareField< T, Dim >::getLayout(), IpplInfo::getNodes(), INFORM_ALL_NODES, NDIndex< Dim >::intersect(), cmp_diff::lt(), FieldLayout< Dim >::touch_range_rdv(), NDIndex< Dim >::touches(), and value_type().
Referenced by assign().
IndexedLocalAssign()
template<class T1 , class T2 , unsigned D1, unsigned D2, class Op > void IndexedLocalAssign (IndexedBareField< T1, D1, D1 > & ilhs, IndexedBareField< T2, D2, D2 > & irhs, Op & op) inline
Definition at line 236 of file AssignGeneralIBF.hpp.
References ASSIGNMSG, LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), LField< T, Dim >::Compress(), NDIndex< Dim >::contains(), NDIndex< Dim >::containsAllPoints(), BareField< T, Dim >::end_if(), endl(), LField< T, Dim >::getAllocated(), IndexedBareField< T, Dim, Brackets >::getBareField(), IndexedBareField< T, Dim, Brackets >::getDomain(), LField< T, Dim >::getOwned(), INFORM_ALL_NODES, NDIndex< Dim >::intersect(), LField< T, Dim >::IsCompressed(), cmp_diff::lt(), CompressedBrickIterator< T, Dim >::permute(), PETE_apply(), NDIndex< Dim >::touches(), and LField< T, Dim >::Uncompress().
Referenced by assign().
IndexedReceive()
template<class T1 , class T2 , unsigned D1, unsigned D2, class Op , class Container > void IndexedReceive (IndexedBareField< T1, D1, D1 > & ilhs, IndexedBareField< T2, D2, D2 > & , Op & op, Container & recv_ac, int msgnum, int tag) inline
Definition at line 385 of file AssignGeneralIBF.hpp.
References ASSIGNMSG, IpplInfo::Comm, COMM_ANY_NODE, NDIndex< Dim >::containsAllPoints(), endl(), IndexedBareField< T, Dim, Brackets >::getBareField(), IndexedBareField< T, Dim, Brackets >::getDomain(), NDIndex< Dim >::getMessage(), INFORM_ALL_NODES, LField< T, Dim >::IsCompressed(), PAssert, PETE_apply(), Communicate::receive_block(), and Message::size().
Referenced by assign().
IndexedSend()
template<class T1 , class T2 , unsigned D1, unsigned D2> void IndexedSend (IndexedBareField< T1, D1, D1 > & ilhs, IndexedBareField< T2, D2, D2 > & irhs, int tag) inline
Definition at line 66 of file AssignGeneralIBF.hpp.
References ASSIGNMSG, LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), IpplInfo::Comm, BareField< T, Dim >::end_if(), endl(), IndexedBareField< T, Dim, Brackets >::getBareField(), IndexedBareField< T, Dim, Brackets >::getDomain(), IpplInfo::getNodes(), LField< T, Dim >::getOwned(), INFORM_ALL_NODES, cmp_diff::lt(), PAssert, CompressedBrickIterator< T, Dim >::permute(), NDIndex< Dim >::putMessage(), CompressedBrickIterator< T, Dim >::putMessage(), Communicate::send(), NDIndex< Dim >::touches(), and CompressedBrickIterator< T, Dim >::TryCompress().
Referenced by assign().