OPAL (Object Oriented Parallel Accelerator Library): src/opal.cpp File Reference
opal.cpp File Reference
#include "opal.h"
#include "AbstractObjects/OpalData.h"
#include "OpalConfigure/Configure.h"
#include "OpalParser/OpalParser.h"
#include "Parser/FileStream.h"
#include "Utilities/OpalException.h"
#include "Fields/Fieldmap.h"
#include "Structure/IpplInfoWrapper.h"
#include "Utilities/Options.h"
#include "OPALconfig.h"
#include <AMReX.H>
#include "Message/Communicate.h"
#include "GSLErrorHandling.h"
#include <gsl/gsl_errno.h>
#include <fstream>
#include <iostream>
#include <limits>
#include <string>
Functions
int run_opal (char *[], std::string inputfile, int restartStep, int infoLevel, int warnLevel, MPI_Comm comm)
Variables
Ippl * ippl
Inform * gmsg
Function Documentation
run_opal()
int run_opal (char * [], std::string inputfile, int restartStep, int infoLevel, int warnLevel, MPI_Comm comm)
Definition at line 32 of file opal.cpp.
References Options::amr, Communicate::barrier(), Fieldmap::clearDictionary(), IpplInfo::Comm, Configure::configure(), OpalData::deleteInstance(), IpplInfo::Error, OpalData::getInstance(), gmsg, handleGSLErrors(), IpplInfo::Info, Options::infoLevel, min(), OpalParser::run(), Inform::setDestination(), OpalData::setRestartFileName(), OpalData::setRestartRun(), OpalData::setRestartStep(), OpalData::storeInputFn(), IpplInfo::Warn, and Options::warnLevel.
Referenced by OpalSimulation::run().
Variable Documentation
gmsg
Inform* gmsg
Definition at line 62 of file Main.cpp.
Referenced by run_opal().
ippl
Ippl* ippl
Definition at line 61 of file Main.cpp.
Referenced by main().