OPAL (Object Oriented Parallel Accelerator Library): ConstEzField Class Reference
ConstEzField Class Reference
#include <ConstEzField.h>
Public Member Functions
ConstEzField ()
Default constructor.
virtual ~ConstEzField ()
virtual EVector Efield (const Point3D &P) const
Get field.
virtual EVector Efield (const Point3D &P, double t) const
Get field.
virtual double getEz () const
Get component.
virtual void setEz (double)
Set component.
virtual void scale (double scalar)
Scale the field.
Public Member Functions inherited from StaticElectricField
StaticElectricField ()
virtual ~StaticElectricField ()
Public Member Functions inherited from EMField
EMField ()
Default constructor.
EMField (const EMField &right)
virtual ~EMField ()
const EMField & operator= (const EMField &right)
virtual BVector Bfield (const Point3D &P) const
Get field.
virtual BVector Bfield (const Point3D &P, double t) const
Get field.
virtual EBVectors EBfield (const Point3D &P) const
Get field.
virtual EBVectors EBfield (const Point3D &P, double t) const
Get field.
Private Attributes
double Ez
Additional Inherited Members
Static Public Attributes inherited from EMField
static const EVector ZeroEfield
The constant representing a zero electric field.
static const BVector ZeroBfield
The constant representing a zero magnetic field.
static const EBVectors ZeroEBfield
The constant representing a zero electromagnetic field.
Detailed Description
Definition at line 23 of file ConstEzField.h.
Constructor & Destructor Documentation
ConstEzField()
ConstEzField::ConstEzField ()
Default constructor.
Definition at line 21 of file ConstEzField.cpp.
~ConstEzField()
ConstEzField::~ConstEzField () virtual
Definition at line 25 of file ConstEzField.cpp.
Member Function Documentation
Efield() [1/2]
EVector ConstEzField::Efield (const Point3D & P) const virtual
Get field.
Reimplemented from EMField.
Reimplemented in OscillatingField< ConstEzField >.
Definition at line 29 of file ConstEzField.cpp.
References Ez.
Efield() [2/2]
EVector ConstEzField::Efield (const Point3D & P, double t) const virtual
Get field.
Reimplemented from EMField.
Reimplemented in OscillatingField< ConstEzField >.
Definition at line 34 of file ConstEzField.cpp.
References Ez.
getEz()
double ConstEzField::getEz () const virtual
Get component.
Definition at line 39 of file ConstEzField.cpp.
References Ez.
Referenced by RFCavityRep::getAmplitude(), and TravelingWaveRep::getAmplitude().
scale()
void ConstEzField::scale (double scalar) virtual
Scale the field.
Implements EMField.
Definition at line 49 of file ConstEzField.cpp.
References Ez.
setEz()
void ConstEzField::setEz (double value) virtual
Set component.
Definition at line 44 of file ConstEzField.cpp.
References Ez.
Referenced by RFCavityRep::setAmplitude(), and TravelingWaveRep::setAmplitude().
Member Data Documentation
Ez
double ConstEzField::Ez private
Definition at line 56 of file ConstEzField.h.
Referenced by Efield(), getEz(), scale(), and setEz().
The documentation for this class was generated from the following files:
src/Classic/Fields/ConstEzField.h
src/Classic/Fields/ConstEzField.cpp