OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Field/Assign.h File Reference
Assign.h File Reference
#include "PETE/IpplExpressions.h"
#include <complex>
#include "Field/Assign.hpp"
#include "Field/AssignGeneralBF.hpp"
#include "Field/AssignGeneralIBF.hpp"
Classes
class BareField< T, Dim >
class LField< T, Dim >
class IndexedBareField< T, Dim, Brackets >
class ExprTag< IsExpr >
struct IsExprTrait< T >
struct IsExprTrait< double >
struct IsExprTrait< std::complex< double > >
struct IsExprTrait< float >
struct IsExprTrait< short >
struct IsExprTrait< int >
struct IsExprTrait< long >
struct IsExprTrait< Index >
Macros
#define ASSIGNMSG(x)
#define ASSIGNMENT_OPERATORS(FUNC, OP)
Functions
template<class T , unsigned Dim, class RHS , class OP >
void assign (const BareField< T, Dim > &a, RHS b, OP op, ExprTag< true >)
template<class T1 , unsigned Dim, class RHS , class OP >
void assign (const IndexedBareField< T1, Dim, Dim > &a, RHS b, OP op, ExprTag< true >, bool fillGC)
template<class T1 , unsigned Dim, class RHS , class OP >
void assign (const IndexedBareField< T1, Dim, Dim > &a, RHS b, OP op, ExprTag< true > et)
template<class A , class RHS , class OP , class Tag , class TP >
void assign (PETE_TUTree< OpParens< TP >, A > lhs, RHS rhs, OP op, Tag, bool fillGC=true)
template<class T1 , unsigned D1, class RHS , class Op >
void assign (const BareField< T1, D1 > &lhs, RHS rhs, Op op, ExprTag< false >)
template<class T1 , unsigned D1, class RHS , class Op >
void assign (IndexedBareField< T1, D1, D1 > lhs, RHS rhs, Op, ExprTag< false >)
template<class T , unsigned D, class OP >
void assign (BareField< T, D > &a, const T &b, OP op, ExprTag< true >)
template<class T , unsigned D, class OP >
void assign (IndexedBareField< T, D, D > a, const T &b, OP op, ExprTag< true >)
template<class LHS , class RHS >
void assign (const PETE_Expr< LHS > &lhs, const PETE_Expr< RHS > &rhs)
template<class T , unsigned D>
void assign (const IndexedBareField< T, D, D > &lhs, const T &rhs)
template<class T , unsigned D>
void assign (const BareField< T, D > &lhs, const T &rhs)
template<class A , class TP >
void assign (const PETE_TUTree< OpParens< TP >, A > &lhs, const bool &rhs)
template<class A , class TP >
void assign (const PETE_TUTree< OpParens< TP >, A > &lhs, const char &rhs)
template<class A , class TP >
void assign (const PETE_TUTree< OpParens< TP >, A > &lhs, const int &rhs)
template<class A , class TP >
void assign (const PETE_TUTree< OpParens< TP >, A > &lhs, const float &rhs)
template<class A , class TP >
void assign (const PETE_TUTree< OpParens< TP >, A > &lhs, const double &rhs)
template<class A , class TP >
void assign (const PETE_TUTree< OpParens< TP >, A > &lhs, const std::complex< double > &rhs)
template<class LHS , class RHS >
void operator<< (const PETE_Expr< LHS > &lhs, const PETE_Expr< RHS > &rhs)
template<class T , unsigned D>
void operator<< (const IndexedBareField< T, D, D > &lhs, const T &rhs)
template<class T , unsigned D>
void operator<< (const BareField< T, D > &lhs, const T &rhs)
template<class A , class TP >
void operator<< (const PETE_TUTree< OpParens< TP >, A > &lhs, const bool &rhs)
template<class A , class TP >
void operator<< (const PETE_TUTree< OpParens< TP >, A > &lhs, const char &rhs)
template<class A , class TP >
void operator<< (const PETE_TUTree< OpParens< TP >, A > &lhs, const int &rhs)
template<class A , class TP >
void operator<< (const PETE_TUTree< OpParens< TP >, A > &lhs, const float &rhs)
template<class A , class TP >
void operator<< (const PETE_TUTree< OpParens< TP >, A > &lhs, const double &rhs)
template<class A , class TP >
void operator<< (const PETE_TUTree< OpParens< TP >, A > &lhs, const std::complex< double > &rhs)
template<class LHS , class RHS >
void operator+= (const PETE_Expr< LHS > &lhs, const PETE_Expr< RHS > &rhs)
template<class T , unsigned D>
void operator+= (const IndexedBareField< T, D, D > &lhs, const T &rhs)
template<class T , unsigned D>
void operator+= (const BareField< T, D > &lhs, const T &rhs)
template<class A , class TP >
void operator+= (const PETE_TUTree< OpParens< TP >, A > &lhs, const bool &rhs)
template<class A , class TP >
void operator+= (const PETE_TUTree< OpParens< TP >, A > &lhs, const char &rhs)
template<class A , class TP >
void operator+= (const PETE_TUTree< OpParens< TP >, A > &lhs, const int &rhs)
template<class A , class TP >
void operator+= (const PETE_TUTree< OpParens< TP >, A > &lhs, const float &rhs)
template<class A , class TP >
void operator+= (const PETE_TUTree< OpParens< TP >, A > &lhs, const double &rhs)
template<class A , class TP >
void operator+= (const PETE_TUTree< OpParens< TP >, A > &lhs, const std::complex< double > &rhs)
template<class LHS , class RHS >
void operator-= (const PETE_Expr< LHS > &lhs, const PETE_Expr< RHS > &rhs)
template<class T , unsigned D>
void operator-= (const IndexedBareField< T, D, D > &lhs, const T &rhs)
template<class T , unsigned D>
void operator-= (const BareField< T, D > &lhs, const T &rhs)
template<class A , class TP >
void operator-= (const PETE_TUTree< OpParens< TP >, A > &lhs, const bool &rhs)
template<class A , class TP >
void operator-= (const PETE_TUTree< OpParens< TP >, A > &lhs, const char &rhs)
template<class A , class TP >
void operator-= (const PETE_TUTree< OpParens< TP >, A > &lhs, const int &rhs)
template<class A , class TP >
void operator-= (const PETE_TUTree< OpParens< TP >, A > &lhs, const float &rhs)
template<class A , class TP >
void operator-= (const PETE_TUTree< OpParens< TP >, A > &lhs, const double &rhs)
template<class A , class TP >
void operator-= (const PETE_TUTree< OpParens< TP >, A > &lhs, const std::complex< double > &rhs)
template<class LHS , class RHS >
void operator*= (const PETE_Expr< LHS > &lhs, const PETE_Expr< RHS > &rhs)
template<class T , unsigned D>
void operator*= (const IndexedBareField< T, D, D > &lhs, const T &rhs)
template<class T , unsigned D>
void operator*= (const BareField< T, D > &lhs, const T &rhs)
template<class A , class TP >
void operator*= (const PETE_TUTree< OpParens< TP >, A > &lhs, const bool &rhs)
template<class A , class TP >
void operator*= (const PETE_TUTree< OpParens< TP >, A > &lhs, const char &rhs)
template<class A , class TP >
void operator*= (const PETE_TUTree< OpParens< TP >, A > &lhs, const int &rhs)
template<class A , class TP >
void operator*= (const PETE_TUTree< OpParens< TP >, A > &lhs, const float &rhs)
template<class A , class TP >
void operator*= (const PETE_TUTree< OpParens< TP >, A > &lhs, const double &rhs)
template<class A , class TP >
void operator*= (const PETE_TUTree< OpParens< TP >, A > &lhs, const std::complex< double > &rhs)
template<class LHS , class RHS >
void operator/= (const PETE_Expr< LHS > &lhs, const PETE_Expr< RHS > &rhs)
template<class T , unsigned D>
void operator/= (const IndexedBareField< T, D, D > &lhs, const T &rhs)
template<class T , unsigned D>
void operator/= (const BareField< T, D > &lhs, const T &rhs)
template<class A , class TP >
void operator/= (const PETE_TUTree< OpParens< TP >, A > &lhs, const bool &rhs)
template<class A , class TP >
void operator/= (const PETE_TUTree< OpParens< TP >, A > &lhs, const char &rhs)
template<class A , class TP >
void operator/= (const PETE_TUTree< OpParens< TP >, A > &lhs, const int &rhs)
template<class A , class TP >
void operator/= (const PETE_TUTree< OpParens< TP >, A > &lhs, const float &rhs)
template<class A , class TP >
void operator/= (const PETE_TUTree< OpParens< TP >, A > &lhs, const double &rhs)
template<class A , class TP >
void operator/= (const PETE_TUTree< OpParens< TP >, A > &lhs, const std::complex< double > &rhs)
template<class LHS , class RHS >
void mineq (const PETE_Expr< LHS > &lhs, const PETE_Expr< RHS > &rhs)
template<class T , unsigned D>
void mineq (const IndexedBareField< T, D, D > &lhs, const T &rhs)
template<class T , unsigned D>
void mineq (const BareField< T, D > &lhs, const T &rhs)
template<class A , class TP >
void mineq (const PETE_TUTree< OpParens< TP >, A > &lhs, const bool &rhs)
template<class A , class TP >
void mineq (const PETE_TUTree< OpParens< TP >, A > &lhs, const char &rhs)
template<class A , class TP >
void mineq (const PETE_TUTree< OpParens< TP >, A > &lhs, const int &rhs)
template<class A , class TP >
void mineq (const PETE_TUTree< OpParens< TP >, A > &lhs, const float &rhs)
template<class A , class TP >
void mineq (const PETE_TUTree< OpParens< TP >, A > &lhs, const double &rhs)
template<class A , class TP >
void mineq (const PETE_TUTree< OpParens< TP >, A > &lhs, const std::complex< double > &rhs)
template<class LHS , class RHS >
void maxeq (const PETE_Expr< LHS > &lhs, const PETE_Expr< RHS > &rhs)
template<class T , unsigned D>
void maxeq (const IndexedBareField< T, D, D > &lhs, const T &rhs)
template<class T , unsigned D>
void maxeq (const BareField< T, D > &lhs, const T &rhs)
template<class A , class TP >
void maxeq (const PETE_TUTree< OpParens< TP >, A > &lhs, const bool &rhs)
template<class A , class TP >
void maxeq (const PETE_TUTree< OpParens< TP >, A > &lhs, const char &rhs)
template<class A , class TP >
void maxeq (const PETE_TUTree< OpParens< TP >, A > &lhs, const int &rhs)
template<class A , class TP >
void maxeq (const PETE_TUTree< OpParens< TP >, A > &lhs, const float &rhs)
template<class A , class TP >
void maxeq (const PETE_TUTree< OpParens< TP >, A > &lhs, const double &rhs)
template<class A , class TP >
void maxeq (const PETE_TUTree< OpParens< TP >, A > &lhs, const std::complex< double > &rhs)
template<class T , unsigned Dim, class A , class Op >
bool TryCompressLHS (LField< T, Dim > &, A &, Op, const NDIndex< Dim > &)
Macro Definition Documentation
ASSIGNMENT_OPERATORS
#define ASSIGNMENT_OPERATORS (FUNC, OP)
Definition at line 115 of file Assign.h.
ASSIGNMSG
#define ASSIGNMSG (x)
Definition at line 28 of file Assign.h.
Referenced by assign(), CalcIndexedReceive(), IndexedLocalAssign(), IndexedReceive(), IndexedSend(), and TryCompressLHS().
Function Documentation
assign() [1/17]
template<class T , unsigned Dim, class RHS , class OP > void assign (const BareField< T, Dim > & a, RHS b, OP op, ExprTag< true >)
Referenced by assign(), IPPL::Average(), Div(), UniformCartesian< Dim, MFLOAT >::getSurfaceNormalFields(), Cartesian< Dim, MFLOAT >::getSurfaceNormalFields(), Grad(), Grad1Ord(), IndexedField< T, Dim, Brackets, M, C >::operator=(), IndexedSIndex< Dim, Brackets >::operator=(), ParticleInteractAttrib< T >::operator=(), SIndex< Dim >::operator=(), SubField< T, Dim, M, C, S >::operator=(), Field< Vector_t, 3, Mesh_t, Center_t >::operator=(), ParticleAttribElem< T, Dim >::operator=(), SubBareField< T, Dim, S >::operator=(), BareField< T1, D >::operator=(), SubParticleAttrib< PA, T, Dim >::operator=(), IndexedBareField< T, Dim, Brackets >::operator=(), ParticleAttrib< ParticleOrigin >::operator=(), and IndexedBareField< T, Dim, Brackets >::write().
assign() [2/17]
template<class T1 , unsigned Dim, class RHS , class OP > void assign (const IndexedBareField< T1, Dim, Dim > & a, RHS b, OP op, ExprTag< true > , bool fillGC)
Definition at line 231 of file Assign.hpp.
References a, IpplInfo::abort(), ASSIGNMSG, LField< T, Dim >::begin(), NDIndex< Dim >::empty(), endl(), ERRORMSG, IpplInfo::extraCompressChecks, FillGCIfNecessary(), for_each(), IndexedBareField< T, Dim, Brackets >::getDomain(), LField< T, Dim >::getOwned(), INFORM_ALL_NODES, PETE_apply(), LField< T, Dim >::TryCompress(), and TryCompressLHS().
assign() [3/17]
template<class T1 , unsigned Dim, class RHS , class OP > void assign (const IndexedBareField< T1, Dim, Dim > & a, RHS b, OP op, ExprTag< true > et) inline
Definition at line 67 of file Assign.h.
References a, and assign().
assign() [4/17]
template<class A , class RHS , class OP , class Tag , class TP > void assign (PETE_TUTree< OpParens< TP >, A > lhs, RHS rhs, OP op, Tag , bool fillGC = true)
Definition at line 407 of file Assign.hpp.
References IpplInfo::abort(), Expressionize< T >::apply(), ASSIGNMSG, LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::Compress(), BareField< T, Dim >::compressible(), NDIndex< Dim >::containsAllPoints(), Dim, NDIndex< Dim >::empty(), BareField< T, Dim >::end_if(), endl(), ERRORMSG, IpplInfo::extraCompressChecks, FillGCIfNecessary(), BareField< T, Dim >::fillGuardCellsIfNotDirty(), for_each(), LField< T, Dim >::getOwned(), INFORM_ALL_NODES, NDIndex< Dim >::intersect(), LField< T, Dim >::IsCompressed(), BareField< T, Dim >::isDirty(), PETE_apply(), PETE_Expr< WrappedExpr >::PETE_unwrap(), BareField< T, Dim >::setDirtyFlag(), LField< T, Dim >::TryCompress(), and LField< T, Dim >::Uncompress().
assign() [5/17]
template<class T1 , unsigned D1, class RHS , class Op > void assign (const BareField< T1, D1 > & lhs, RHS rhs, Op op, ExprTag< false >)
assign() [6/17]
template<class T1 , unsigned D1, class RHS , class Op > void assign (IndexedBareField< T1, D1, D1 > lhs, RHS rhs, Op , ExprTag< false >)
Definition at line 502 of file AssignGeneralIBF.hpp.
References CalcIndexedReceive(), IpplInfo::Comm, endl(), ERRORMSG, F_GEN_ASSIGN_TAG, F_TAG_CYCLE, FillGCIfNecessary(), for_each(), IndexedBareField< T, Dim, Brackets >::getBareField(), IndexedBareField< T, Dim, Brackets >::getDomain(), IpplInfo::getNodes(), IndexedLocalAssign(), IndexedReceive(), IndexedSend(), TagMaker::next_tag(), and PAssert.
assign() [7/17]
template<class T , unsigned D, class OP > void assign (BareField< T, D > & a, const T & b, OP op, ExprTag< true >) inline
Definition at line 92 of file Assign.h.
References a, and assign().
assign() [8/17]
template<class T , unsigned D, class OP > void assign (IndexedBareField< T, D, D > a, const T & b, OP op, ExprTag< true >) inline
Definition at line 99 of file Assign.h.
References a, and assign().
assign() [9/17]
template<class A , class TP > void assign (const PETE_TUTree< OpParens< TP >, A > & lhs, const double & rhs) inline
Definition at line 176 of file Assign.h.
assign() [10/17]
template<class A , class TP > void assign (const PETE_TUTree< OpParens< TP >, A > & lhs, const std::complex< double > & rhs) inline
Definition at line 176 of file Assign.h.
assign() [11/17]
template<class LHS , class RHS > void assign (const PETE_Expr< LHS > & lhs, const PETE_Expr< RHS > & rhs) inline
Definition at line 176 of file Assign.h.
assign() [12/17]
template<class T , unsigned D> void assign (const IndexedBareField< T, D, D > & lhs, const T & rhs) inline
Definition at line 176 of file Assign.h.
assign() [13/17]
template<class T , unsigned D> void assign (const BareField< T, D > & lhs, const T & rhs) inline
Definition at line 176 of file Assign.h.
assign() [14/17]
template<class A , class TP > void assign (const PETE_TUTree< OpParens< TP >, A > & lhs, const bool & rhs) inline
Definition at line 176 of file Assign.h.
assign() [15/17]
template<class A , class TP > void assign (const PETE_TUTree< OpParens< TP >, A > & lhs, const char & rhs) inline
Definition at line 176 of file Assign.h.
assign() [16/17]
template<class A , class TP > void assign (const PETE_TUTree< OpParens< TP >, A > & lhs, const int & rhs) inline
Definition at line 176 of file Assign.h.
assign() [17/17]
template<class A , class TP > void assign (const PETE_TUTree< OpParens< TP >, A > & lhs, const float & rhs) inline
Definition at line 176 of file Assign.h.
maxeq() [1/9]
template<class A , class TP > void maxeq (const PETE_TUTree< OpParens< TP >, A > & lhs, const bool & rhs) inline
Definition at line 183 of file Assign.h.
maxeq() [2/9]
template<class LHS , class RHS > void maxeq (const PETE_Expr< LHS > & lhs, const PETE_Expr< RHS > & rhs) inline
Definition at line 183 of file Assign.h.
maxeq() [3/9]
template<class T , unsigned D> void maxeq (const IndexedBareField< T, D, D > & lhs, const T & rhs) inline
Definition at line 183 of file Assign.h.
maxeq() [4/9]
template<class T , unsigned D> void maxeq (const BareField< T, D > & lhs, const T & rhs) inline
Definition at line 183 of file Assign.h.
maxeq() [5/9]
template<class A , class TP > void maxeq (const PETE_TUTree< OpParens< TP >, A > & lhs, const char & rhs) inline
Definition at line 183 of file Assign.h.
maxeq() [6/9]
template<class A , class TP > void maxeq (const PETE_TUTree< OpParens< TP >, A > & lhs, const int & rhs) inline
Definition at line 183 of file Assign.h.
maxeq() [7/9]
template<class A , class TP > void maxeq (const PETE_TUTree< OpParens< TP >, A > & lhs, const float & rhs) inline
Definition at line 183 of file Assign.h.
maxeq() [8/9]
template<class A , class TP > void maxeq (const PETE_TUTree< OpParens< TP >, A > & lhs, const double & rhs) inline
Definition at line 183 of file Assign.h.
maxeq() [9/9]
template<class A , class TP > void maxeq (const PETE_TUTree< OpParens< TP >, A > & lhs, const std::complex< double > & rhs) inline
Definition at line 183 of file Assign.h.
mineq() [1/9]
template<class T , unsigned D> void mineq (const IndexedBareField< T, D, D > & lhs, const T & rhs) inline
Definition at line 182 of file Assign.h.
mineq() [2/9]
template<class T , unsigned D> void mineq (const BareField< T, D > & lhs, const T & rhs) inline
Definition at line 182 of file Assign.h.
mineq() [3/9]
template<class A , class TP > void mineq (const PETE_TUTree< OpParens< TP >, A > & lhs, const bool & rhs) inline
Definition at line 182 of file Assign.h.
mineq() [4/9]
template<class A , class TP > void mineq (const PETE_TUTree< OpParens< TP >, A > & lhs, const int & rhs) inline
Definition at line 182 of file Assign.h.
mineq() [5/9]
template<class A , class TP > void mineq (const PETE_TUTree< OpParens< TP >, A > & lhs, const float & rhs) inline
Definition at line 182 of file Assign.h.
mineq() [6/9]
template<class A , class TP > void mineq (const PETE_TUTree< OpParens< TP >, A > & lhs, const double & rhs) inline
Definition at line 182 of file Assign.h.
mineq() [7/9]
template<class A , class TP > void mineq (const PETE_TUTree< OpParens< TP >, A > & lhs, const std::complex< double > & rhs) inline
Definition at line 182 of file Assign.h.
mineq() [8/9]
template<class A , class TP > void mineq (const PETE_TUTree< OpParens< TP >, A > & lhs, const char & rhs) inline
Definition at line 182 of file Assign.h.
mineq() [9/9]
template<class LHS , class RHS > void mineq (const PETE_Expr< LHS > & lhs, const PETE_Expr< RHS > & rhs) inline
Definition at line 182 of file Assign.h.
operator*=() [1/9]
template<class A , class TP > void operator*= (const PETE_TUTree< OpParens< TP >, A > & lhs, const float & rhs) inline
Definition at line 180 of file Assign.h.
operator*=() [2/9]
template<class LHS , class RHS > void operator*= (const PETE_Expr< LHS > & lhs, const PETE_Expr< RHS > & rhs) inline
Definition at line 180 of file Assign.h.
operator*=() [3/9]
template<class T , unsigned D> void operator*= (const IndexedBareField< T, D, D > & lhs, const T & rhs) inline
Definition at line 180 of file Assign.h.
operator*=() [4/9]
template<class T , unsigned D> void operator*= (const BareField< T, D > & lhs, const T & rhs) inline
Definition at line 180 of file Assign.h.
operator*=() [5/9]
template<class A , class TP > void operator*= (const PETE_TUTree< OpParens< TP >, A > & lhs, const bool & rhs) inline
Definition at line 180 of file Assign.h.
operator*=() [6/9]
template<class A , class TP > void operator*= (const PETE_TUTree< OpParens< TP >, A > & lhs, const char & rhs) inline
Definition at line 180 of file Assign.h.
operator*=() [7/9]
template<class A , class TP > void operator*= (const PETE_TUTree< OpParens< TP >, A > & lhs, const int & rhs) inline
Definition at line 180 of file Assign.h.
operator*=() [8/9]
template<class A , class TP > void operator*= (const PETE_TUTree< OpParens< TP >, A > & lhs, const double & rhs) inline
Definition at line 180 of file Assign.h.
operator*=() [9/9]
template<class A , class TP > void operator*= (const PETE_TUTree< OpParens< TP >, A > & lhs, const std::complex< double > & rhs) inline
Definition at line 180 of file Assign.h.
operator+=() [1/9]
template<class A , class TP > void operator+= (const PETE_TUTree< OpParens< TP >, A > & lhs, const int & rhs) inline
Definition at line 178 of file Assign.h.
operator+=() [2/9]
template<class A , class TP > void operator+= (const PETE_TUTree< OpParens< TP >, A > & lhs, const std::complex< double > & rhs) inline
Definition at line 178 of file Assign.h.
operator+=() [3/9]
template<class A , class TP > void operator+= (const PETE_TUTree< OpParens< TP >, A > & lhs, const char & rhs) inline
Definition at line 178 of file Assign.h.
operator+=() [4/9]
template<class LHS , class RHS > void operator+= (const PETE_Expr< LHS > & lhs, const PETE_Expr< RHS > & rhs) inline
Definition at line 178 of file Assign.h.
operator+=() [5/9]
template<class T , unsigned D> void operator+= (const IndexedBareField< T, D, D > & lhs, const T & rhs) inline
Definition at line 178 of file Assign.h.
operator+=() [6/9]
template<class T , unsigned D> void operator+= (const BareField< T, D > & lhs, const T & rhs) inline
Definition at line 178 of file Assign.h.
operator+=() [7/9]
template<class A , class TP > void operator+= (const PETE_TUTree< OpParens< TP >, A > & lhs, const float & rhs) inline
Definition at line 178 of file Assign.h.
operator+=() [8/9]
template<class A , class TP > void operator+= (const PETE_TUTree< OpParens< TP >, A > & lhs, const bool & rhs) inline
Definition at line 178 of file Assign.h.
operator+=() [9/9]
template<class A , class TP > void operator+= (const PETE_TUTree< OpParens< TP >, A > & lhs, const double & rhs) inline
Definition at line 178 of file Assign.h.
operator-=() [1/9]
template<class T , unsigned D> void operator-= (const IndexedBareField< T, D, D > & lhs, const T & rhs) inline
Definition at line 179 of file Assign.h.
operator-=() [2/9]
template<class LHS , class RHS > void operator-= (const PETE_Expr< LHS > & lhs, const PETE_Expr< RHS > & rhs) inline
Definition at line 179 of file Assign.h.
operator-=() [3/9]
template<class A , class TP > void operator-= (const PETE_TUTree< OpParens< TP >, A > & lhs, const char & rhs) inline
Definition at line 179 of file Assign.h.
operator-=() [4/9]
template<class A , class TP > void operator-= (const PETE_TUTree< OpParens< TP >, A > & lhs, const int & rhs) inline
Definition at line 179 of file Assign.h.
operator-=() [5/9]
template<class A , class TP > void operator-= (const PETE_TUTree< OpParens< TP >, A > & lhs, const float & rhs) inline
Definition at line 179 of file Assign.h.
operator-=() [6/9]
template<class A , class TP > void operator-= (const PETE_TUTree< OpParens< TP >, A > & lhs, const std::complex< double > & rhs) inline
Definition at line 179 of file Assign.h.
operator-=() [7/9]
template<class A , class TP > void operator-= (const PETE_TUTree< OpParens< TP >, A > & lhs, const double & rhs) inline
Definition at line 179 of file Assign.h.
operator-=() [8/9]
template<class A , class TP > void operator-= (const PETE_TUTree< OpParens< TP >, A > & lhs, const bool & rhs) inline
Definition at line 179 of file Assign.h.
operator-=() [9/9]
template<class T , unsigned D> void operator-= (const BareField< T, D > & lhs, const T & rhs) inline
Definition at line 179 of file Assign.h.
operator/=() [1/9]
template<class A , class TP > void operator/= (const PETE_TUTree< OpParens< TP >, A > & lhs, const bool & rhs) inline
Definition at line 181 of file Assign.h.
operator/=() [2/9]
template<class A , class TP > void operator/= (const PETE_TUTree< OpParens< TP >, A > & lhs, const float & rhs) inline
Definition at line 181 of file Assign.h.
operator/=() [3/9]
template<class LHS , class RHS > void operator/= (const PETE_Expr< LHS > & lhs, const PETE_Expr< RHS > & rhs) inline
Definition at line 181 of file Assign.h.
operator/=() [4/9]
template<class A , class TP > void operator/= (const PETE_TUTree< OpParens< TP >, A > & lhs, const double & rhs) inline
Definition at line 181 of file Assign.h.
operator/=() [5/9]
template<class A , class TP > void operator/= (const PETE_TUTree< OpParens< TP >, A > & lhs, const int & rhs) inline
Definition at line 181 of file Assign.h.
operator/=() [6/9]
template<class T , unsigned D> void operator/= (const BareField< T, D > & lhs, const T & rhs) inline
Definition at line 181 of file Assign.h.
operator/=() [7/9]
template<class A , class TP > void operator/= (const PETE_TUTree< OpParens< TP >, A > & lhs, const std::complex< double > & rhs) inline
Definition at line 181 of file Assign.h.
operator/=() [8/9]
template<class A , class TP > void operator/= (const PETE_TUTree< OpParens< TP >, A > & lhs, const char & rhs) inline
Definition at line 181 of file Assign.h.
operator/=() [9/9]
template<class T , unsigned D> void operator/= (const IndexedBareField< T, D, D > & lhs, const T & rhs) inline
Definition at line 181 of file Assign.h.
operator<<() [1/9]
template<class A , class TP > void operator<< (const PETE_TUTree< OpParens< TP >, A > & lhs, const bool & rhs) inline
Definition at line 177 of file Assign.h.
operator<<() [2/9]
template<class A , class TP > void operator<< (const PETE_TUTree< OpParens< TP >, A > & lhs, const float & rhs) inline
Definition at line 177 of file Assign.h.
operator<<() [3/9]
template<class A , class TP > void operator<< (const PETE_TUTree< OpParens< TP >, A > & lhs, const char & rhs) inline
Definition at line 177 of file Assign.h.
operator<<() [4/9]
template<class LHS , class RHS > void operator<< (const PETE_Expr< LHS > & lhs, const PETE_Expr< RHS > & rhs) inline
Definition at line 177 of file Assign.h.
operator<<() [5/9]
template<class A , class TP > void operator<< (const PETE_TUTree< OpParens< TP >, A > & lhs, const std::complex< double > & rhs) inline
Definition at line 177 of file Assign.h.
operator<<() [6/9]
template<class A , class TP > void operator<< (const PETE_TUTree< OpParens< TP >, A > & lhs, const int & rhs) inline
Definition at line 177 of file Assign.h.
operator<<() [7/9]
template<class T , unsigned D> void operator<< (const IndexedBareField< T, D, D > & lhs, const T & rhs) inline
Definition at line 177 of file Assign.h.
operator<<() [8/9]
template<class T , unsigned D> void operator<< (const BareField< T, D > & lhs, const T & rhs) inline
Definition at line 177 of file Assign.h.
operator<<() [9/9]
template<class A , class TP > void operator<< (const PETE_TUTree< OpParens< TP >, A > & lhs, const double & rhs) inline
Definition at line 177 of file Assign.h.
TryCompressLHS()
template<class T , unsigned Dim, class A , class Op > bool TryCompressLHS (LField< T, Dim > & , A & , Op , const NDIndex< Dim > &)
Definition at line 48 of file Assign.hpp.
References ASSIGNMSG, LField< T, Dim >::begin(), LField< T, Dim >::Compress(), NDIndex< Dim >::containsAllPoints(), endl(), for_each(), LField< T, Dim >::getOwned(), INFORM_ALL_NODES, LField< T, Dim >::IsCompressed(), IpplInfo::noFieldCompression, PETE_apply(), Attrib::Legacy::Distribution::T, and LField< T, Dim >::Uncompress().
Referenced by assign().