OPAL (Object Oriented Parallel Accelerator Library): SumErrSq Struct Reference
SumErrSq Struct Reference
#include <SumErrSq.h>
Public Member Functions
Expressions::Result_t operator() (client::function::arguments_t args)
Static Public Attributes
static const std::string name = "SumErrSq"
Private Member Functions
void parseMeasurements (std::string measurement_filename)
Private Attributes
std::vector< Measurement > measurements_
std::string var_name_
std::string stat_filename_
boost::tuple< std::string, std::string, std::string > argument_types
Detailed Description
Definition at line 53 of file SumErrSq.h.
Member Function Documentation
operator()()
Expressions::Result_t SumErrSq::operator() (client::function::arguments_t args) inline
Definition at line 57 of file SumErrSq.h.
References Physics::e, endl(), measurements_, parseMeasurements(), sqrt(), stat_filename_, sum(), var_name_, and OptPilotException::what().
parseMeasurements()
void SumErrSq::parseMeasurements (std::string measurement_filename) private
parses a simple list of spos and measurements using tab as delimiter.
Definition at line 13 of file SumErrSq.cpp.
References measurements_.
Referenced by operator()().
Member Data Documentation
argument_types
boost::tuple<std::string, std::string, std::string> SumErrSq::argument_types private
Definition at line 110 of file SumErrSq.h.
measurements_
std::vector<Measurement> SumErrSq::measurements_ private
Definition at line 102 of file SumErrSq.h.
Referenced by operator()(), and parseMeasurements().
name
const std::string SumErrSq::name = "SumErrSq" static
Definition at line 55 of file SumErrSq.h.
stat_filename_
std::string SumErrSq::stat_filename_ private
Definition at line 105 of file SumErrSq.h.
Referenced by operator()().
var_name_
std::string SumErrSq::var_name_ private
Definition at line 104 of file SumErrSq.h.
Referenced by operator()().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/optimizer/Expression/SumErrSq.h
/psi/home/gsell/data/src/OPAL/src/optimizer/Expression/SumErrSq.cpp