OPAL (Object Oriented Parallel Accelerator Library): IntTSCImpl< 2U > Class Template Reference
IntTSCImpl< 2U > Class Template Reference
#include <IntTSC.h>
Public Member Functions
IntTSCImpl ()
~IntTSCImpl ()
Public Member Functions inherited from Interpolator
Interpolator ()
~Interpolator ()
Static Public Member Functions
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 2U, M, C > &f, const Vektor< PT, 2U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 2U, M, C > &f, const Vektor< PT, 2U > &ppos, const M &mesh, NDIndex< 2U > &ngp, int [2U], Vektor< PT, 2U > &dpos)
template<class FT , class M , class C , class PT >
static void scatter (const FT &pdata, Field< FT, 2U, M, C > &f, const NDIndex< 2U > &ngp, const int [2U], const Vektor< PT, 2U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 2U, M, C > &f, const Vektor< PT, 2U > &ppos, const M &mesh)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 2U, M, C > &f, const Vektor< PT, 2U > &ppos, const M &mesh, NDIndex< 2U > &ngp, int [2U], Vektor< PT, 2U > &dpos)
template<class FT , class M , class C , class PT >
static void gather (FT &pdata, const Field< FT, 2U, M, C > &f, const NDIndex< 2U > &ngp, const int [2U], const Vektor< PT, 2U > &dpos)
Additional Inherited Members
Static Protected Member Functions inherited from Interpolator
template<class T , unsigned Dim>
static CompressedBrickIterator< T, Dim > getFieldIter (const BareField< T, Dim > &f, const NDIndex< Dim > &pt)
Detailed Description
template<>
class IntTSCImpl< 2U >
Definition at line 444 of file IntTSC.h.
Constructor & Destructor Documentation
IntTSCImpl()
IntTSCImpl< 2U >::IntTSCImpl () inline
Definition at line 448 of file IntTSC.h.
~IntTSCImpl()
IntTSCImpl< 2U >::~IntTSCImpl () inline
Definition at line 449 of file IntTSC.h.
Member Function Documentation
gather() [1/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 2U >::gather (FT & pdata, const Field< FT, 2U, M, C > & f, const Vektor< PT, 2U > & ppos, const M & mesh) inline static
Definition at line 554 of file IntTSC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
gather() [2/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 2U >::gather (FT & pdata, const Field< FT, 2U, M, C > & f, const Vektor< PT, 2U > & ppos, const M & mesh, NDIndex< 2U > & ngp, int [2U], Vektor< PT, 2U > & dpos) inline static
Definition at line 591 of file IntTSC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
gather() [3/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 2U >::gather (FT & pdata, const Field< FT, 2U, M, C > & f, const NDIndex< 2U > & ngp, const int [2U], const Vektor< PT, 2U > & dpos) inline static
Definition at line 627 of file IntTSC.h.
References Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
scatter() [1/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 2U >::scatter (const FT & pdata, Field< FT, 2U, M, C > & f, const Vektor< PT, 2U > & ppos, const M & mesh) inline static
Definition at line 456 of file IntTSC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
scatter() [2/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 2U >::scatter (const FT & pdata, Field< FT, 2U, M, C > & f, const Vektor< PT, 2U > & ppos, const M & mesh, NDIndex< 2U > & ngp, int [2U], Vektor< PT, 2U > & dpos) inline static
Definition at line 492 of file IntTSC.h.
References FindDelta(), FindNGP(), FindPos(), Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
scatter() [3/3]
template<class FT , class M , class C , class PT > static void IntTSCImpl< 2U >::scatter (const FT & pdata, Field< FT, 2U, M, C > & f, const NDIndex< 2U > & ngp, const int [2U], const Vektor< PT, 2U > & dpos) inline static
Definition at line 528 of file IntTSC.h.
References Interpolator::getFieldIter(), BrickIterator< T, Dim >::offset(), and Attrib::Distribution::W.
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/IntTSC.h