OPAL (Object Oriented Parallel Accelerator Library): mslang::Intersection Struct Reference
mslang::Intersection Struct Reference
#include <Intersection.h>
Public Member Functions
Intersection ()
Intersection (const Intersection &right)
virtual ~Intersection ()
virtual void print (int indentwidth)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Public Member Functions inherited from mslang::Function
virtual ~Function ()
virtual void apply (std::vector< std::shared_ptr< Base >> &bfuncs)=0
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
Static Public Member Functions inherited from mslang::Function
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
Function * firstOperand_m
Function * secondOperand_m
Additional Inherited Members
Static Public Attributes inherited from mslang::Function
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\((.*)"
Detailed Description
Definition at line 7 of file Intersection.h.
Constructor & Destructor Documentation
Intersection() [1/2]
mslang::Intersection::Intersection () inline
Definition at line 11 of file Intersection.h.
Intersection() [2/2]
mslang::Intersection::Intersection (const Intersection & right) inline
Definition at line 14 of file Intersection.h.
~Intersection()
virtual mslang::Intersection::~Intersection () inline virtual
Definition at line 19 of file Intersection.h.
References firstOperand_m, and secondOperand_m.
Member Function Documentation
apply()
void mslang::Intersection::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Definition at line 16 of file Intersection.cpp.
References mslang::Function::apply(), firstOperand_m, and secondOperand_m.
parse_detail()
bool mslang::Intersection::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 40 of file Intersection.cpp.
References end(), firstOperand_m, mslang::Function::parse(), and secondOperand_m.
Referenced by mslang::Function::parse().
print()
void mslang::Intersection::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 6 of file Intersection.cpp.
References firstOperand_m, mslang::Function::print(), and secondOperand_m.
Member Data Documentation
firstOperand_m
Function* mslang::Intersection::firstOperand_m
Definition at line 8 of file Intersection.h.
Referenced by apply(), parse_detail(), print(), and ~Intersection().
secondOperand_m
Function* mslang::Intersection::secondOperand_m
Definition at line 9 of file Intersection.h.
Referenced by apply(), parse_detail(), print(), and ~Intersection().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Intersection.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Intersection.cpp