OPAL (Object Oriented Parallel Accelerator Library): PyOpal::Globals Namespace Reference
PyOpal::Globals Namespace Reference
Functions
void Initialise ()
Function Documentation
Initialise()
void PyOpal::Globals::Initialise ()
Globals namespace provides routines to initialise global objects:
ippl
gmsg
Definition at line 78 of file Globals.cpp.
References endl(), gmsg, and ippl.
Referenced by PyOpal::PyLineNS::BOOST_PYTHON_MODULE(), PyOpal::PyDistributionNS::BOOST_PYTHON_MODULE(), PyOpal::PyTrackCmdNS::BOOST_PYTHON_MODULE(), PyOpal::PyTrackRunNS::BOOST_PYTHON_MODULE(), PyOpal::PyRingDefinition::BOOST_PYTHON_MODULE(), PyInit_polynomial_coefficient(), and PyInit_polynomial_map().