OPAL (Object Oriented Parallel Accelerator Library): Beamline Class Reference
Beamline Class Reference abstract
An abstract sequence of beam line components.
#include <Beamline.h>
Public Member Functions
Beamline (const std::string &name)
Constructor with given name.
Beamline ()
Beamline (const Beamline &)
virtual ~Beamline ()
virtual void iterate (BeamlineVisitor &, bool reverse) const =0
Apply visitor to all elements of the line.
virtual Vector_t getOrigin3D () const
virtual Quaternion getInitialDirection () const
virtual bool getRelativeFlag () const
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
virtual ElementType getType () const =0
Get element type std::string.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual void accept (BeamlineVisitor &visitor) const =0
Apply visitor.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void operator= (const Beamline &)
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Detailed Description
An abstract sequence of beam line components.
Definition at line 34 of file Beamline.h.
Constructor & Destructor Documentation
Beamline() [1/3]
Beamline::Beamline (const std::string & name) explicit
Constructor with given name.
Definition at line 40 of file Beamline.cpp.
References ElementBase::shareFlag.
Beamline() [2/3]
Beamline::Beamline ()
Definition at line 28 of file Beamline.cpp.
References ElementBase::shareFlag.
Beamline() [3/3]
Beamline::Beamline (const Beamline &)
Definition at line 34 of file Beamline.cpp.
References ElementBase::shareFlag.
~Beamline()
Beamline::~Beamline () virtual
Definition at line 46 of file Beamline.cpp.
Member Function Documentation
getInitialDirection()
Quaternion Beamline::getInitialDirection () const virtual
Reimplemented in TBeamline< T >.
Definition at line 53 of file Beamline.cpp.
Referenced by ThickTracker::ThickTracker().
getOrigin3D()
Vector_t Beamline::getOrigin3D () const virtual
Reimplemented in TBeamline< T >.
Definition at line 49 of file Beamline.cpp.
Referenced by ThickTracker::ThickTracker().
getRelativeFlag()
bool Beamline::getRelativeFlag () const virtual
Reimplemented in TBeamline< T >.
Definition at line 57 of file Beamline.cpp.
iterate()
virtual void Beamline::iterate (BeamlineVisitor & , bool reverse) const pure virtual
Apply visitor to all elements of the line.
Implemented in TBeamline< T >.
Referenced by SpecificElementVisitor< ELEM >::SpecificElementVisitor(), DefaultVisitor::visitBeamline(), and SpecificElementVisitor< ELEM >::visitBeamline().
operator=()
void Beamline::operator= (const Beamline &) private
The documentation for this class was generated from the following files:
src/Classic/Beamlines/Beamline.h
src/Classic/Beamlines/Beamline.cpp