OPAL (Object Oriented Parallel Accelerator Library): Message Class Reference
Message Class Reference
#include <Message.h>
Classes
class MsgItem
Public Member Functions
Message (unsigned int numelems=8)
~Message ()
size_t size () const
size_t removed () const
bool empty () const
MsgItem & item (size_t n)
const MsgItem & item (size_t n) const
Message & setCopy (const bool c)
bool willCopy () const
Message & setDelete (const bool c)
bool willDelete () const
Message & clear ()
void * remove ()
void useCommunicate (Communicate *c, void *d)
template<class T >
Message & put (const T &val)
Message & put (const char *d)
Message & put (const std::string &s)
template<class ForwardIterator >
Message & put (ForwardIterator beg, ForwardIterator end)
template<class RandomAccessIterator >
Message & put (const std::vector< size_t > &indices, RandomAccessIterator beg)
Message & putmsg (void *, int, int=0)
template<class T >
Message & get (const T &cval)
Message & get (const std::string &s)
Message & get ()
template<class OutputIterator >
Message & get_iter (OutputIterator o)
Message & getmsg (void *)
Private Member Functions
void deleteMsgItem ()
Private Attributes
std::vector< MsgItem > MsgItemList
size_t numRemoved
bool DoCopy
bool DoDelete
Communicate * comm
void * commdata
Detailed Description
Definition at line 142 of file Message.h.
Constructor & Destructor Documentation
Message()
Message::Message (unsigned int numelems = 8) inline
Definition at line 277 of file Message.h.
References MsgItemList.
~Message()
Message::~Message ()
Definition at line 44 of file MessageFunctions.cpp.
References Hypervolume::n.
Member Function Documentation
clear()
Message & Message::clear (void)
Definition at line 146 of file MessageFunctions.cpp.
deleteMsgItem()
void Message::deleteMsgItem () private
Definition at line 65 of file MessageFunctions.cpp.
empty()
bool Message::empty () const inline
Definition at line 300 of file Message.h.
References size().
Referenced by PutSingleItem< T, false, false >::get_iter(), ParticleSpatialLayout< T, Dim, Mesh >::new_swap_particles(), and BoxLibLayout< T, Dim >::update().
get() [1/3]
template<class T > Message& Message::get (const T & cval) inline
Definition at line 476 of file Message.h.
References get(), and Attrib::Legacy::Distribution::T.
Referenced by DiscField< Dim >::distribute_offsets(), FieldLayout< Dim >::FieldLayout(), PutSingleItem< T, false, false >::get_iter(), Vnode< Dim >::getMessage(), CompressedBrickIterator< T, Dim >::getMessage(), BrickIterator< T, Dim >::getMessage(), IpplParticleBase< T >::getMessage(), AnyHolder< T, OP >::getMessage(), AntiSymTenzor< T, 1 >::getMessage(), Index::getMessage(), BoundsHolder< T, D >::getMessage(), getMessage(), IpplParticleBase< T >::ghostGetMessage(), ParticleSpatialLayout< T, Dim, Mesh >::new_swap_particles(), pap(), FieldLayout< Dim >::read(), DiscParticle::read_meta(), DiscField< Dim >::read_meta(), ParticleSpatialLayout< T, Dim, Mesh >::rebuild_layout(), IpplParticleBase< T >::resetID(), LossDataSink::saveASCII(), scatter(), ParallelCyclotronTracker::singleParticleDump(), spap(), ParticleUniformLayout< T, Dim >::update(), ParticleCashedLayout< T, Dim, Mesh >::update(), ParticleInteractLayout< T, Dim, Mesh >::update(), and ParticleSpatialLayout< T, Dim, Mesh >::update().
get() [2/3]
Message& Message::get (const std::string & s) inline
Definition at line 485 of file Message.h.
get() [3/3]
Message& Message::get () inline
Definition at line 498 of file Message.h.
References getmsg().
Referenced by get().
get_iter()
template<class OutputIterator > Message& Message::get_iter (OutputIterator o) inline
Definition at line 511 of file Message.h.
Referenced by vec< unsigned, Dim >::getMessage(), PRegion< T >::getMessage(), getMessage(), getMessage_iter(), and FieldLayout< Dim >::read().
getmsg()
Message & Message::getmsg (void * data)
Definition at line 111 of file MessageFunctions.cpp.
References Message::MsgItem::data(), endl(), ERRORMSG, Message::MsgItem::numBytes(), and PAssert.
Referenced by get(), and spap().
item() [1/2]
MsgItem& Message::item (size_t n) inline
Definition at line 308 of file Message.h.
References MsgItemList, Hypervolume::n, and numRemoved.
Referenced by MsgBuffer::add(), Communicate::fill_msg_buffer(), Communicate::find_msg_length(), Format::Format(), PutSingleItem< T, false, false >::get_iter(), BrickIterator< T, Dim >::getMessage(), operator<<(), reduce(), and scatter().
item() [2/2]
const MsgItem& Message::item (size_t n) const inline
Definition at line 312 of file Message.h.
References MsgItemList, Hypervolume::n, and numRemoved.
put() [1/5]
template<class T > Message& Message::put (const T & val) inline
Definition at line 406 of file Message.h.
References Attrib::Legacy::Distribution::T.
Referenced by BareField< T1, D >::accumGuardCells(), BcastCuts(), DiscField< Dim >::distribute_offsets(), FieldLayout< Dim >::FieldLayout(), BareField< T1, D >::fillGuardCells(), IpplParticleBase< T >::ghostPutMessage(), pap(), put(), vec< unsigned, Dim >::putMessage(), Vnode< Dim >::putMessage(), CompressedBrickIterator< T, Dim >::putMessage(), BrickIterator< T, Dim >::putMessage(), PRegion< T >::putMessage(), IpplParticleBase< T >::putMessage(), AnyHolder< T, OP >::putMessage(), AntiSymTenzor< T, 1 >::putMessage(), Index::putMessage(), BoundsHolder< T, D >::putMessage(), putMessage(), DiscParticle::read(), FieldLayout< Dim >::read(), DiscParticle::read_meta(), DiscField< Dim >::read_meta(), ParticleSpatialLayout< T, Dim, Mesh >::rebuild_layout(), Communicate::request_retransmission(), IpplParticleBase< T >::resetID(), LossDataSink::saveASCII(), Communicate::send_ok_message(), ParallelCyclotronTracker::singleParticleDump(), spap(), ParticleUniformLayout< T, Dim >::update(), ParticleCashedLayout< T, Dim, Mesh >::update(), ParticleInteractLayout< T, Dim, Mesh >::update(), ParticleSpatialLayout< T, Dim, Mesh >::update(), and DiscParticle::write().
put() [2/5]
Message& Message::put (const char * d) inline
Definition at line 419 of file Message.h.
References putmsg().
put() [3/5]
Message& Message::put (const std::string & s) inline
Definition at line 424 of file Message.h.
References put().
put() [4/5]
template<class ForwardIterator > Message& Message::put (ForwardIterator beg, ForwardIterator end) inline
Definition at line 437 of file Message.h.
References end(), and put().
put() [5/5]
template<class RandomAccessIterator > Message& Message::put (const std::vector< size_t > & indices, RandomAccessIterator beg) inline
Definition at line 450 of file Message.h.
References put().
putmsg()
Message & Message::putmsg (void * data, int s, int nelem = 0)
Definition at line 78 of file MessageFunctions.cpp.
Referenced by DiscField< Dim >::distribute_offsets(), MsgBuffer::get(), PutSingleItem< T, false, false >::put(), PutSingleItem< T, true, false >::put(), PutSingleItem< T, true, true >::put(), put(), BrickIterator< T, Dim >::putMessage(), DiscParticle::read(), spap(), and Communicate::unpack_message().
remove()
void * Message::remove ()
Definition at line 166 of file MessageFunctions.cpp.
References Message::MsgItem::cancelDelete(), Message::MsgItem::data(), Message::MsgItem::numBytes(), and Message::MsgItem::willNeedDelete().
removed()
size_t Message::removed () const inline
Definition at line 296 of file Message.h.
References numRemoved.
Referenced by operator<<().
setCopy()
Message& Message::setCopy (const bool c) inline
Definition at line 319 of file Message.h.
References Physics::c, and DoCopy.
Referenced by DiscField< Dim >::distribute_offsets(), MsgBuffer::get(), PutSingleItem< T, false, false >::put(), BrickIterator< T, Dim >::putMessage(), Vektor< int, 3 >::putMessage(), Tenzor< double, 3 >::putMessage(), AntiSymTenzor< T, D >::putMessage(), SymTenzor< double, 6 >::putMessage(), AntiSymTenzor< T, 1 >::putMessage(), DiscParticle::read(), and Communicate::unpack_message().
setDelete()
Message& Message::setDelete (const bool c) inline
Definition at line 331 of file Message.h.
References Physics::c, and DoDelete.
Referenced by DiscField< Dim >::distribute_offsets(), MsgBuffer::get(), PutSingleItem< T, false, false >::put(), BrickIterator< T, Dim >::putMessage(), DiscParticle::read(), and Communicate::unpack_message().
size()
size_t Message::size (void) const inline
Definition at line 292 of file Message.h.
References MsgItemList, and numRemoved.
Referenced by BareField< T1, D >::accumGuardCells(), MsgBuffer::add(), ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), assign(), empty(), Communicate::fill_msg_buffer(), BareField< T1, D >::fillGuardCells(), Communicate::find_msg_length(), Format::Format(), IndexedReceive(), operator<<(), PutSingleItem< T, false, false >::put(), reduce(), reduce_masked(), and scatter().
useCommunicate()
void Message::useCommunicate (Communicate * c, void * d) inline
Definition at line 358 of file Message.h.
References Physics::c, comm, and commdata.
Referenced by CommMPI::mysend().
willCopy()
bool Message::willCopy () const inline
Definition at line 324 of file Message.h.
References DoCopy.
Referenced by PutSingleItem< T, false, false >::put().
willDelete()
bool Message::willDelete () const inline
Definition at line 336 of file Message.h.
References DoDelete.
Member Data Documentation
comm
Communicate* Message::comm private
Definition at line 538 of file Message.h.
Referenced by useCommunicate().
commdata
void* Message::commdata private
Definition at line 539 of file Message.h.
Referenced by useCommunicate().
DoCopy
bool Message::DoCopy private
Definition at line 531 of file Message.h.
Referenced by setCopy(), and willCopy().
DoDelete
bool Message::DoDelete private
Definition at line 534 of file Message.h.
Referenced by setDelete(), and willDelete().
MsgItemList
std::vector<MsgItem> Message::MsgItemList private
Definition at line 525 of file Message.h.
Referenced by item(), Message(), and size().
numRemoved
size_t Message::numRemoved private
Definition at line 528 of file Message.h.
Referenced by item(), removed(), and size().
The documentation for this class was generated from the following files:
ippl/src/Message/Message.h
ippl/src/Message/MessageFunctions.cpp