OPAL (Object Oriented Parallel Accelerator Library): SectorMagneticFieldMap::IO Class Reference
SectorMagneticFieldMap::IO Class Reference
handles reading sector field maps
#include <SectorMagneticFieldMap.h>
Static Public Member Functions
static interpolation::VectorMap * readMap (std::string file_name, std::vector< double > units, SectorMagneticFieldMap::symmetry sym, int poly_order, int smoothing_order)
Private Member Functions
IO ()
IO (const IO &map)
~IO ()
Static Private Member Functions
static std::vector< std::vector< double > > readLines (std::string file_name, std::vector< double > units)
static interpolation::ThreeDGrid * generateGrid (const std::vector< std::vector< double > > field_points, SectorMagneticFieldMap::symmetry sym)
static interpolation::VectorMap * getInterpolator (const std::vector< std::vector< double > > field_points, interpolation::ThreeDGrid *grid, SectorMagneticFieldMap::symmetry sym)
static interpolation::VectorMap * getInterpolatorPolyPatch (const std::vector< std::vector< double > > field_points, interpolation::ThreeDGrid *grid, SectorMagneticFieldMap::symmetry sym, int poly_order, int smoothing_order)
static bool floatGreaterEqual (double in1, double in2)
static bool comparator (std::vector< double > field_item1, std::vector< double > field_item2)
Static Private Attributes
static const double floatTolerance_m = 1e-3
static const int sortOrder_m [3] = {0, 1, 2}
static const std::string errMsg1
Detailed Description
handles reading sector field maps
SectorMagneticFieldMap::IO provides routines to read a sector field map for input to tracking.
Definition at line 242 of file SectorMagneticFieldMap.h.
Constructor & Destructor Documentation
IO() [1/2]
SectorMagneticFieldMap::IO::IO () private
IO() [2/2]
SectorMagneticFieldMap::IO::IO (const IO & map) private
~IO()
SectorMagneticFieldMap::IO::~IO () private
Member Function Documentation
comparator()
bool SectorMagneticFieldMap::IO::comparator (std::vector< double > field_item1, std::vector< double > field_item2) static private
Definition at line 419 of file SectorMagneticFieldMap.cpp.
References abs().
Referenced by readLines().
floatGreaterEqual()
bool SectorMagneticFieldMap::IO::floatGreaterEqual (double in1, double in2) static private
Definition at line 481 of file SectorMagneticFieldMap.cpp.
generateGrid()
ThreeDGrid * SectorMagneticFieldMap::IO::generateGrid (const std::vector< std::vector< double > > field_points, SectorMagneticFieldMap::symmetry sym) static private
Definition at line 487 of file SectorMagneticFieldMap.cpp.
References endl(), gmsg, and interpolation::ThreeDGrid::setConstantSpacing().
Referenced by readMap().
getInterpolator()
VectorMap * SectorMagneticFieldMap::IO::getInterpolator (const std::vector< std::vector< double > > field_points, interpolation::ThreeDGrid * grid, SectorMagneticFieldMap::symmetry sym) static private
Definition at line 376 of file SectorMagneticFieldMap.cpp.
References interpolation::ThreeDGrid::xSize(), interpolation::ThreeDGrid::ySize(), and interpolation::ThreeDGrid::zSize().
Referenced by readMap().
getInterpolatorPolyPatch()
VectorMap * SectorMagneticFieldMap::IO::getInterpolatorPolyPatch (const std::vector< std::vector< double > > field_points, interpolation::ThreeDGrid * grid, SectorMagneticFieldMap::symmetry sym, int poly_order, int smoothing_order) static private
Definition at line 332 of file SectorMagneticFieldMap.cpp.
References SectorMagneticFieldMap::dipole, endl(), gmsg, and interpolation::PPSolveFactory::solve().
Referenced by readMap().
readLines()
std::vector< std::vector< double > > SectorMagneticFieldMap::IO::readLines (std::string file_name, std::vector< double > units) static private
Definition at line 432 of file SectorMagneticFieldMap.cpp.
References comparator(), SectorField::convertToPolar(), endl(), and gmsg.
Referenced by readMap().
readMap()
VectorMap * SectorMagneticFieldMap::IO::readMap (std::string file_name, std::vector< double > units, SectorMagneticFieldMap::symmetry sym, int poly_order, int smoothing_order) static
Read in the field map
Read in the field map with some specified geometry
Parameters
file_name name of the file containing the field map
units units of the file - should be 6-vector
sym symmetry of the file - either "none" (full field map) or "dipole" (field map is reflected about y = 0)
poly_order order of the polynomial fit
smoothing_order order of the polynomial smoothing
Definition at line 295 of file SectorMagneticFieldMap.cpp.
References endl(), generateGrid(), getInterpolator(), getInterpolatorPolyPatch(), gmsg, and readLines().
Referenced by SectorMagneticFieldMap::readMap().
Member Data Documentation
errMsg1
const std::string SectorMagneticFieldMap::IO::errMsg1 static private
Initial value:
=
    std::string("field points during read ")+
    std::string("operation; this could mean that the field ")+
    std::string("map was not complete, or that OPAL could ")+
    std::string("not calculate regular grid spacings properly. ")+
    std::string("Check that the field map is on a cylindrical ")+
    std::string("grid written in Cartesian coordinates and the ")+
    std::string("grid points are written with enough precision (")+
    std::string("check the grid size information above).")
Definition at line 303 of file SectorMagneticFieldMap.h.
floatTolerance_m
const double SectorMagneticFieldMap::IO::floatTolerance_m = 1e-3 static private
Definition at line 262 of file SectorMagneticFieldMap.h.
sortOrder_m
const int SectorMagneticFieldMap::IO::sortOrder_m = {0, 1, 2} static private
Definition at line 263 of file SectorMagneticFieldMap.h.
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/SectorMagneticFieldMap.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/SectorMagneticFieldMap.cpp