OPAL (Object Oriented Parallel Accelerator Library): _Astra1DDynamic Class Reference
_Astra1DDynamic Class Reference
#include <Astra1DDynamic.h>
Public Member Functions
virtual ~_Astra1DDynamic ()
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const
virtual bool getFieldDerivative (const Vector_t &R, Vector_t &E, Vector_t &B, const DiffDirection &dir) const
virtual void getFieldDimensions (double &zBegin, double &zEnd) const
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const
virtual void swap ()
virtual void getInfo (Inform *)
virtual double getFrequency () const
virtual void setFrequency (double freq)
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &F)
virtual bool isInside (const Vector_t &r) const
Public Member Functions inherited from _Fieldmap
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Private Member Functions
_Astra1DDynamic (const std::string &filename)
virtual void readMap ()
virtual void freeMap ()
Static Private Member Functions
static Astra1DDynamic create (const std::string &filename)
Private Attributes
double *__restrict__ FourCoefs_m
double frequency_m
double xlrep_m
double zbegin_m
double zend_m
double length_m
int accuracy_m
int num_gridpz_m
Friends
class _Fieldmap
Additional Inherited Members
Static Public Member Functions inherited from _Fieldmap
static Fieldmap getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions inherited from _Fieldmap
_Fieldmap ()=delete
_Fieldmap (const std::string &filename)
virtual ~_Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions inherited from _Fieldmap
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes inherited from _Fieldmap
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Detailed Description
Definition at line 6 of file Astra1DDynamic.h.
Constructor & Destructor Documentation
~_Astra1DDynamic()
_Astra1DDynamic::~_Astra1DDynamic () virtual
Definition at line 88 of file Astra1DDynamic.cpp.
References freeMap().
_Astra1DDynamic()
_Astra1DDynamic::_Astra1DDynamic (const std::string & filename) private
Definition at line 16 of file Astra1DDynamic.cpp.
References accuracy_m, Physics::c, _Fieldmap::disableFieldmapWarning(), Physics::e, _Fieldmap::Filename_m, frequency_m, length_m, _Fieldmap::lines_read_m, Units::MHz2Hz, _Fieldmap::noFieldmapWarning(), _Fieldmap::normalize_m, num_gridpz_m, TAstraDynamic, Util::toUpper(), Physics::two_pi, _Fieldmap::Type, xlrep_m, zbegin_m, and zend_m.
Referenced by create().
Member Function Documentation
create()
Astra1DDynamic _Astra1DDynamic::create (const std::string & filename) static private
Definition at line 92 of file Astra1DDynamic.cpp.
References _Astra1DDynamic().
Referenced by _Fieldmap::getFieldmap().
freeMap()
void _Astra1DDynamic::freeMap () private virtual
Implements _Fieldmap.
Definition at line 181 of file Astra1DDynamic.cpp.
References FourCoefs_m.
Referenced by ~_Astra1DDynamic().
getFieldDerivative()
bool _Astra1DDynamic::getFieldDerivative (const Vector_t & R, Vector_t & E, Vector_t & B, const DiffDirection & dir) const virtual
Implements _Fieldmap.
Definition at line 229 of file Astra1DDynamic.cpp.
References accuracy_m, cos(), FourCoefs_m, length_m, Hypervolume::n, Physics::pi, Attrib::Distribution::R, sin(), Physics::two_pi, and zbegin_m.
getFieldDimensions() [1/2]
void _Astra1DDynamic::getFieldDimensions (double & zBegin, double & zEnd) const virtual
Implements _Fieldmap.
Definition at line 242 of file Astra1DDynamic.cpp.
References zbegin_m, and zend_m.
getFieldDimensions() [2/2]
void _Astra1DDynamic::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const virtual
Implements _Fieldmap.
Definition at line 247 of file Astra1DDynamic.cpp.
getFieldstrength()
bool _Astra1DDynamic::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const virtual
Implements _Fieldmap.
Definition at line 188 of file Astra1DDynamic.cpp.
References accuracy_m, Physics::c, cos(), FourCoefs_m, length_m, Hypervolume::n, Physics::pi, Attrib::Distribution::R, sin(), Physics::two_pi, xlrep_m, and zbegin_m.
getFrequency()
double _Astra1DDynamic::getFrequency () const virtual
Implements _Fieldmap.
Definition at line 256 of file Astra1DDynamic.cpp.
References frequency_m.
getInfo()
void _Astra1DDynamic::getInfo (Inform * msg) virtual
Implements _Fieldmap.
Definition at line 252 of file Astra1DDynamic.cpp.
References endl(), _Fieldmap::Filename_m, zbegin_m, and zend_m.
getOnaxisEz()
void _Astra1DDynamic::getOnaxisEz (std::vector< std::pair< double, double > > & F) virtual
Reimplemented from _Fieldmap.
Definition at line 264 of file Astra1DDynamic.cpp.
References abs(), _Fieldmap::Filename_m, and num_gridpz_m.
isInside()
bool _Astra1DDynamic::isInside (const Vector_t & r) const inline virtual
Reimplemented from _Fieldmap.
Definition at line 45 of file Astra1DDynamic.h.
References zbegin_m, and zend_m.
readMap()
void _Astra1DDynamic::readMap () private virtual
Implements _Fieldmap.
Definition at line 97 of file Astra1DDynamic.cpp.
References abs(), accuracy_m, Physics::e, endl(), _Fieldmap::Filename_m, FourCoefs_m, _Fieldmap::getLine(), INFOMSG, level3(), _Fieldmap::normalize_m, num_gridpz_m, real(), _Fieldmap::typeset_msg(), Units::Vpm2MVpm, zbegin_m, and zend_m.
setFrequency()
void _Astra1DDynamic::setFrequency (double freq) virtual
Implements _Fieldmap.
Definition at line 260 of file Astra1DDynamic.cpp.
References frequency_m.
swap()
void _Astra1DDynamic::swap () virtual
Implements _Fieldmap.
Definition at line 249 of file Astra1DDynamic.cpp.
Friends And Related Function Documentation
_Fieldmap
friend class _Fieldmap friend
Definition at line 42 of file Astra1DDynamic.h.
Member Data Documentation
accuracy_m
int _Astra1DDynamic::accuracy_m private
Definition at line 39 of file Astra1DDynamic.h.
Referenced by _Astra1DDynamic(), getFieldDerivative(), getFieldstrength(), and readMap().
FourCoefs_m
double* __restrict__ _Astra1DDynamic::FourCoefs_m private
Definition at line 30 of file Astra1DDynamic.h.
Referenced by freeMap(), getFieldDerivative(), getFieldstrength(), and readMap().
frequency_m
double _Astra1DDynamic::frequency_m private
Definition at line 32 of file Astra1DDynamic.h.
Referenced by _Astra1DDynamic(), getFrequency(), and setFrequency().
length_m
double _Astra1DDynamic::length_m private
Definition at line 37 of file Astra1DDynamic.h.
Referenced by _Astra1DDynamic(), getFieldDerivative(), and getFieldstrength().
num_gridpz_m
int _Astra1DDynamic::num_gridpz_m private
Definition at line 40 of file Astra1DDynamic.h.
Referenced by _Astra1DDynamic(), getOnaxisEz(), and readMap().
xlrep_m
double _Astra1DDynamic::xlrep_m private
Definition at line 33 of file Astra1DDynamic.h.
Referenced by _Astra1DDynamic(), and getFieldstrength().
zbegin_m
double _Astra1DDynamic::zbegin_m private
Definition at line 35 of file Astra1DDynamic.h.
Referenced by _Astra1DDynamic(), getFieldDerivative(), getFieldDimensions(), getFieldstrength(), getInfo(), isInside(), and readMap().
zend_m
double _Astra1DDynamic::zend_m private
Definition at line 36 of file Astra1DDynamic.h.
Referenced by _Astra1DDynamic(), getFieldDimensions(), getInfo(), isInside(), and readMap().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/Astra1DDynamic.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Fields/Astra1DDynamic.cpp