OPAL (Object Oriented Parallel Accelerator Library): VerticalFFAMagnet Class Reference
VerticalFFAMagnet Class Reference
#include <VerticalFFAMagnet.h>
Public Member Functions
VerticalFFAMagnet (const std::string &name)
~VerticalFFAMagnet ()
ElementBase * clone () const
bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B)
bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
bool getFieldValue (const Vector_t &R, Vector_t &B) const
void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField)
void initialise ()
void finalise ()
bool bends () const
void getDimensions (double &, double &) const
BGeometryBase & getGeometry ()
const BGeometryBase & getGeometry () const
EMField & getField ()
const EMField & getField () const
void accept (BeamlineVisitor &visitor) const
endfieldmodel::EndFieldModel * getEndField () const
void setEndField (endfieldmodel::EndFieldModel *endField)
size_t getMaxOrder () const
void setMaxOrder (size_t maxOrder)
double getB0 () const
void setB0 (double Bz)
double getFieldIndex () const
void setFieldIndex (double index)
double getNegativeVerticalExtent () const
void setNegativeVerticalExtent (double negativeExtent)
double getPositiveVerticalExtent () const
void setPositiveVerticalExtent (double positiveExtent)
double getBBLength () const
void setBBLength (double bbLength)
double getWidth () const
void setWidth (double width)
std::vector< std::vector< double > > getDfCoefficients () const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual ElementType getType () const
Get element type std::string.
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void calculateDfCoefficients ()
VerticalFFAMagnet (const VerticalFFAMagnet &right)
VerticalFFAMagnet & operator= (const VerticalFFAMagnet &rhs)
Private Attributes
StraightGeometry straightGeometry_m
BMultipoleField dummy
size_t maxOrder_m = 0
double k_m = 0.
double Bz_m = 0.
double zNegExtent_m = 0.
double zPosExtent_m = 0.
double halfWidth_m = 0.
double bbLength_m = 0.
std::unique_ptr< endfieldmodel::EndFieldModel > endField_m
std::vector< std::vector< double > > dfCoefficients_m
const double mm =1000.
const double Tesla =10.
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Bending magnet with an exponential dependence on field in the vertical plane
VerticalFFAMagnet makes a rectangular bending magnet with a dipole field that has a dependence like B0 exp(mz)
Definition at line 28 of file VerticalFFAMagnet.h.
Constructor & Destructor Documentation
VerticalFFAMagnet() [1/2]
VerticalFFAMagnet::VerticalFFAMagnet (const std::string & name) explicit
Construct a new VerticalFFAMagnet
Parameters
name User-defined name of the VerticalFFAMagnet
Definition at line 17 of file VerticalFFAMagnet.cpp.
Referenced by clone().
~VerticalFFAMagnet()
VerticalFFAMagnet::~VerticalFFAMagnet ()
Destructor - deletes the field
Definition at line 38 of file VerticalFFAMagnet.cpp.
VerticalFFAMagnet() [2/2]
VerticalFFAMagnet::VerticalFFAMagnet (const VerticalFFAMagnet & right) private
Copy constructor
Definition at line 21 of file VerticalFFAMagnet.cpp.
References Component::RefPartBunch_m.
Member Function Documentation
accept()
void VerticalFFAMagnet::accept (BeamlineVisitor & visitor) const virtual
Accept a beamline visitor
Implements ElementBase.
Definition at line 77 of file VerticalFFAMagnet.cpp.
References BeamlineVisitor::visitVerticalFFAMagnet().
apply() [1/2]
bool VerticalFFAMagnet::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) inline virtual
Calculate the field at the position of the ith particle
Parameters
i index of the particle event; field is calculated at this position
t time at which the field is to be calculated
E calculated electric field - always 0 (no E-field)
B calculated magnetic field
Returns
true if particle is outside the field map
Reimplemented from Component.
Definition at line 218 of file VerticalFFAMagnet.h.
References PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::R, and Component::RefPartBunch_m.
apply() [2/2]
bool VerticalFFAMagnet::apply (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) inline virtual
Calculate the field at some arbitrary position
Parameters
R position in the local coordinate system of the magnet
P not used
t not used
E not used
B calculated magnetic field
Returns
true if particle is outside the field map, else false
Reimplemented from Component.
Definition at line 223 of file VerticalFFAMagnet.h.
References getFieldValue(), and Attrib::Distribution::R.
bends()
bool VerticalFFAMagnet::bends () const inline virtual
Return false - VerticalFFAMagnet is a straight magnet
Nb: the VerticalFFAMagnet geometry is straight even though trajectories are not
Implements Component.
Definition at line 97 of file VerticalFFAMagnet.h.
calculateDfCoefficients()
void VerticalFFAMagnet::calculateDfCoefficients () private
Definition at line 123 of file VerticalFFAMagnet.cpp.
References dfCoefficients_m, k_m, maxOrder_m, and Hypervolume::n.
Referenced by initialise().
clone()
ElementBase * VerticalFFAMagnet::clone () const virtual
Inheritable copy constructor
Implements ElementBase.
Definition at line 41 of file VerticalFFAMagnet.cpp.
References initialise(), and VerticalFFAMagnet().
finalise()
void VerticalFFAMagnet::finalise () virtual
Finalise the VerticalFFAMagnet - sets bunch to nullptr
Implements Component.
Definition at line 65 of file VerticalFFAMagnet.cpp.
References Component::RefPartBunch_m.
getB0()
double VerticalFFAMagnet::getB0 () const inline
Get the centre field at z=0
Definition at line 140 of file VerticalFFAMagnet.h.
References Bz_m, and Tesla.
getBBLength()
double VerticalFFAMagnet::getBBLength () const inline
Get the length of the bounding box (centred on magnet centre)
Definition at line 164 of file VerticalFFAMagnet.h.
References bbLength_m, and mm.
getDfCoefficients()
std::vector< std::vector< double > > VerticalFFAMagnet::getDfCoefficients () const inline
Get the coefficients used for the field expansion
B_y is given by sum_n B_0 exp(ky) f_n x^n where f_n = sum_k c_{nk} partial_k f_0
Returns a vector of vectors, like c[n][k]. The expansion for the other field elements can be related back to c[n][k] (see elsewhere for details).
Definition at line 228 of file VerticalFFAMagnet.h.
References dfCoefficients_m.
getDimensions()
void VerticalFFAMagnet::getDimensions (double & , double &) const inline virtual
Not implemented
Implements Component.
Definition at line 100 of file VerticalFFAMagnet.h.
getEndField()
endfieldmodel::EndFieldModel* VerticalFFAMagnet::getEndField () const inline
Get the fringe field
Returns the fringe field model; VerticalFFAMagnet retains ownership of the returned memory.
Definition at line 122 of file VerticalFFAMagnet.h.
References endField_m.
Referenced by OpalVerticalFFAMagnet::update().
getField() [1/2]
EMField & VerticalFFAMagnet::getField () virtual
Return a dummy (0.) field value (what is this for?)
Implements Component.
Definition at line 47 of file VerticalFFAMagnet.cpp.
References dummy.
getField() [2/2]
const EMField & VerticalFFAMagnet::getField () const virtual
Return a dummy (0.) field value (what is this for?)
Implements Component.
Definition at line 51 of file VerticalFFAMagnet.cpp.
References dummy.
getFieldIndex()
double VerticalFFAMagnet::getFieldIndex () const inline
Get the field index
Definition at line 146 of file VerticalFFAMagnet.h.
References k_m, and mm.
getFieldValue()
bool VerticalFFAMagnet::getFieldValue (const Vector_t & R, Vector_t & B) const
Calculate the field at some arbitrary position in cartesian coordinates
Parameters
R position in the local coordinate system of the bend, in cartesian coordinates defined like (x, y, z)
B calculated magnetic field defined like (Bx, By, Bz)
Returns
true if particle is outside the field map, else false
Definition at line 82 of file VerticalFFAMagnet.cpp.
References abs(), bbLength_m, Bz_m, dfCoefficients_m, endField_m, exp(), halfWidth_m, k_m, maxOrder_m, Hypervolume::n, Attrib::Distribution::R, zNegExtent_m, and zPosExtent_m.
Referenced by apply().
getGeometry() [1/2]
BGeometryBase & VerticalFFAMagnet::getGeometry () virtual
Return the cell geometry
Implements ElementBase.
Definition at line 69 of file VerticalFFAMagnet.cpp.
References straightGeometry_m.
getGeometry() [2/2]
const BGeometryBase & VerticalFFAMagnet::getGeometry () const virtual
Return the cell geometry
Implements ElementBase.
Definition at line 73 of file VerticalFFAMagnet.cpp.
References straightGeometry_m.
getMaxOrder()
size_t VerticalFFAMagnet::getMaxOrder () const inline
Get the maximum power of x used in the off-midplane expansion;
Definition at line 133 of file VerticalFFAMagnet.h.
References maxOrder_m.
getNegativeVerticalExtent()
double VerticalFFAMagnet::getNegativeVerticalExtent () const inline
Get the maximum extent below z = 0
Definition at line 152 of file VerticalFFAMagnet.h.
References mm, and zNegExtent_m.
getPositiveVerticalExtent()
double VerticalFFAMagnet::getPositiveVerticalExtent () const inline
Get the maximum extent above z = 0
Definition at line 158 of file VerticalFFAMagnet.h.
References mm, and zPosExtent_m.
getWidth()
double VerticalFFAMagnet::getWidth () const inline
Get the full width of the bounding box (centred on magnet centre)
Definition at line 170 of file VerticalFFAMagnet.h.
References halfWidth_m, and mm.
initialise() [1/2]
void VerticalFFAMagnet::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) virtual
Initialise the VerticalFFAMagnet
Parameters
bunch the global bunch object (but not used)
startField not used
endField not used
Implements Component.
Definition at line 60 of file VerticalFFAMagnet.cpp.
References initialise(), and Component::RefPartBunch_m.
Referenced by clone(), and OpalVerticalFFAMagnet::update().
initialise() [2/2]
void VerticalFFAMagnet::initialise ()
Initialise the VerticalFFAMagnet
Sets up the field expansion and the geometry; call after changing any field parameters
Definition at line 55 of file VerticalFFAMagnet.cpp.
References bbLength_m, calculateDfCoefficients(), StraightGeometry::setElementLength(), and straightGeometry_m.
Referenced by initialise().
operator=()
VerticalFFAMagnet& VerticalFFAMagnet::operator= (const VerticalFFAMagnet & rhs) private
setB0()
void VerticalFFAMagnet::setB0 (double Bz) inline
Set the centre field at z=0
Definition at line 143 of file VerticalFFAMagnet.h.
References Bz_m, and Tesla.
Referenced by OpalVerticalFFAMagnet::update().
setBBLength()
void VerticalFFAMagnet::setBBLength (double bbLength) inline
Set the length of the bounding box (centred on magnet centre)
Definition at line 167 of file VerticalFFAMagnet.h.
References bbLength_m, and mm.
Referenced by OpalVerticalFFAMagnet::update().
setEndField()
void VerticalFFAMagnet::setEndField (endfieldmodel::EndFieldModel * endField)
Set the fringe field
endField: the new fringe field; VerticalFFAMagnet takes ownership of the memory associated with endField.
Definition at line 144 of file VerticalFFAMagnet.cpp.
References endField_m, and maxOrder_m.
Referenced by OpalVerticalFFAMagnet::OpalVerticalFFAMagnet().
setFieldIndex()
void VerticalFFAMagnet::setFieldIndex (double index) inline
Set the field index
Definition at line 149 of file VerticalFFAMagnet.h.
References k_m, and mm.
Referenced by OpalVerticalFFAMagnet::update().
setMaxOrder()
void VerticalFFAMagnet::setMaxOrder (size_t maxOrder)
Set the maximum power of x used in the off-midplane expansion;
Definition at line 149 of file VerticalFFAMagnet.cpp.
References endField_m, and maxOrder_m.
Referenced by OpalVerticalFFAMagnet::update().
setNegativeVerticalExtent()
void VerticalFFAMagnet::setNegativeVerticalExtent (double negativeExtent) inline
Set the maximum extent below z = 0
Definition at line 210 of file VerticalFFAMagnet.h.
References mm, and zNegExtent_m.
Referenced by OpalVerticalFFAMagnet::update().
setPositiveVerticalExtent()
void VerticalFFAMagnet::setPositiveVerticalExtent (double positiveExtent) inline
set the maximum extent above z = 0
Definition at line 214 of file VerticalFFAMagnet.h.
References mm, and zPosExtent_m.
Referenced by OpalVerticalFFAMagnet::update().
setWidth()
void VerticalFFAMagnet::setWidth (double width) inline
Set the full width of the bounding box (centred on magnet centre)
Definition at line 173 of file VerticalFFAMagnet.h.
References halfWidth_m, and mm.
Referenced by OpalVerticalFFAMagnet::update().
Member Data Documentation
bbLength_m
double VerticalFFAMagnet::bbLength_m = 0. private
Definition at line 202 of file VerticalFFAMagnet.h.
Referenced by getBBLength(), getFieldValue(), initialise(), and setBBLength().
Bz_m
double VerticalFFAMagnet::Bz_m = 0. private
Definition at line 198 of file VerticalFFAMagnet.h.
Referenced by getB0(), getFieldValue(), and setB0().
dfCoefficients_m
std::vector<std::vector<double> > VerticalFFAMagnet::dfCoefficients_m private
Definition at line 204 of file VerticalFFAMagnet.h.
Referenced by calculateDfCoefficients(), getDfCoefficients(), and getFieldValue().
dummy
BMultipoleField VerticalFFAMagnet::dummy private
Definition at line 194 of file VerticalFFAMagnet.h.
Referenced by getField().
endField_m
std::unique_ptr<endfieldmodel::EndFieldModel> VerticalFFAMagnet::endField_m private
Definition at line 203 of file VerticalFFAMagnet.h.
Referenced by getEndField(), getFieldValue(), setEndField(), and setMaxOrder().
halfWidth_m
double VerticalFFAMagnet::halfWidth_m = 0. private
Definition at line 201 of file VerticalFFAMagnet.h.
Referenced by getFieldValue(), getWidth(), and setWidth().
k_m
double VerticalFFAMagnet::k_m = 0. private
Definition at line 197 of file VerticalFFAMagnet.h.
Referenced by calculateDfCoefficients(), getFieldIndex(), getFieldValue(), and setFieldIndex().
maxOrder_m
size_t VerticalFFAMagnet::maxOrder_m = 0 private
Definition at line 196 of file VerticalFFAMagnet.h.
Referenced by calculateDfCoefficients(), getFieldValue(), getMaxOrder(), setEndField(), and setMaxOrder().
mm
const double VerticalFFAMagnet::mm =1000. private
Definition at line 206 of file VerticalFFAMagnet.h.
Referenced by getBBLength(), getFieldIndex(), getNegativeVerticalExtent(), getPositiveVerticalExtent(), getWidth(), setBBLength(), setFieldIndex(), setNegativeVerticalExtent(), setPositiveVerticalExtent(), and setWidth().
straightGeometry_m
StraightGeometry VerticalFFAMagnet::straightGeometry_m private
Definition at line 193 of file VerticalFFAMagnet.h.
Referenced by getGeometry(), and initialise().
Tesla
const double VerticalFFAMagnet::Tesla =10. private
Definition at line 207 of file VerticalFFAMagnet.h.
Referenced by getB0(), and setB0().
zNegExtent_m
double VerticalFFAMagnet::zNegExtent_m = 0. private
Definition at line 199 of file VerticalFFAMagnet.h.
Referenced by getFieldValue(), getNegativeVerticalExtent(), and setNegativeVerticalExtent().
zPosExtent_m
double VerticalFFAMagnet::zPosExtent_m = 0. private
Definition at line 200 of file VerticalFFAMagnet.h.
Referenced by getFieldValue(), getPositiveVerticalExtent(), and setPositiveVerticalExtent().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/VerticalFFAMagnet.h
src/Classic/AbsBeamline/VerticalFFAMagnet.cpp