OPAL (Object Oriented Parallel Accelerator Library): Vector< T > Class Template Reference
Vector< T > Class Template Reference
Vector.
#include <Tps.h>
Public Member Functions
Vector ()
Default constructor.
Vector (int n)
Constructor.
Vector (int n, const T &t)
Constructor.
Vector (const Array1D< T > &)
Conversion.
Vector (const Vector< T > &)
~Vector ()
Vector< T > & operator= (const Vector< T > &)
Vector< T > operator- () const
Change sign of vector.
Vector< T > & operator*= (const T &)
Multiply by scalar and assign.
Vector< T > & operator/= (const T &)
Divide by scalar and assign.
Vector< T > & operator+= (const Vector< T > &)
Add vector and assign.
Vector< T > & operator-= (const Vector< T > &)
Subtract vector and assign.
Public Member Functions inherited from Array1D< T >
Array1D ()
Default constructor.
Array1D (int n)
Constructor.
Array1D (int n, const T &t)
Constructor.
Array1D (const Array1D< T > &)
~Array1D ()
Array1D< T > & operator= (const Array1D< T > &)
T & operator() (int n)
Get reference to element.
const T & operator() (int n) const
Get value of element.
T & operator[] (int)
Get reference to element.
const T & operator[] (int) const
Get value of element.
iterator begin ()
Get beginning of data.
iterator end ()
Get end of data.
const_iterator begin () const
Get beginning of data.
const_iterator end () const
Get end of data.
int size () const
Get array size.
void resize (int size)
Change array size.
Additional Inherited Members
Public Types inherited from Array1D< T >
typedef T value_type
The value type of this array.
typedef T * iterator
The iterator type for the array.
typedef const T * const_iterator
The iterator type for constant array.
Protected Attributes inherited from Array1D< T >
int len
T * data
Detailed Description
template<class T>
class Vector< T >
Vector.
Definition at line 30 of file Tps.h.
Constructor & Destructor Documentation
Vector() [1/5]
template<class T > Vector< T >::Vector ()
Default constructor.
Definition at line 109 of file Vector.h.
Vector() [2/5]
template<class T > Vector< T >::Vector (int n) explicit
Constructor.
Definition at line 115 of file Vector.h.
Vector() [3/5]
template<class T > Vector< T >::Vector (int n, const T & t)
Constructor.
Definition at line 121 of file Vector.h.
Vector() [4/5]
template<class T > Vector< T >::Vector (const Array1D< T > & array)
Conversion.
Definition at line 133 of file Vector.h.
Vector() [5/5]
template<class T > Vector< T >::Vector (const Vector< T > & array)
Definition at line 127 of file Vector.h.
~Vector()
template<class T > Vector< T >::~Vector ()
Definition at line 139 of file Vector.h.
Member Function Documentation
operator*=()
template<class T > Vector< T > & Vector< T >::operator*= (const T & val)
Multiply by scalar and assign.
Definition at line 159 of file Vector.h.
References begin(), and end().
operator+=()
template<class T > Vector< T > & Vector< T >::operator+= (const Vector< T > & array)
Add vector and assign.
Definition at line 175 of file Vector.h.
References Array1D< T >::begin(), begin(), and end().
operator-()
template<class T > Vector< T > Vector< T >::operator- () const
Change sign of vector.
Definition at line 151 of file Vector.h.
References Array1D< T >::begin(), begin(), and end().
operator-=()
template<class T > Vector< T > & Vector< T >::operator-= (const Vector< T > & array)
Subtract vector and assign.
Definition at line 183 of file Vector.h.
References Array1D< T >::begin(), begin(), and end().
operator/=()
template<class T > Vector< T > & Vector< T >::operator/= (const T & val)
Divide by scalar and assign.
Definition at line 167 of file Vector.h.
References begin(), and end().
operator=()
template<class T > Vector< T > & Vector< T >::operator= (const Vector< T > & right)
Definition at line 144 of file Vector.h.
References Array1D< T >::operator=().
The documentation for this class was generated from the following files:
src/Classic/Algebra/Tps.h
src/Classic/Algebra/Vector.h