OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/ParticleBConds.h File Reference
ParticleBConds.h File Reference
#include "Region/NDRegion.h"
#include "Index/NDIndex.h"
Classes
class ParticleBConds< T, Dim >
Functions
template<class T >
T ParticleNoBCond (const T t, const T, const T)
template<class T >
T ParticlePeriodicBCond (const T t, const T minval, const T maxval)
template<class T >
T ParticleReflectiveBCond (const T t, const T minval, const T maxval)
template<class T >
T ParticleSinkBCond (const T t, const T minval, const T maxval)
Function Documentation
ParticleNoBCond()
template<class T > T ParticleNoBCond (const T t, const T , const T) inline
Definition at line 32 of file ParticleBConds.h.
Referenced by ParticleBConds< T, Dim >::ParticleBConds(), PartBunch::setBCAllOpen(), and PartBunch::setBCForDCBeam().
ParticlePeriodicBCond()
template<class T > T ParticlePeriodicBCond (const T t, const T minval, const T maxval) inline
Definition at line 38 of file ParticleBConds.h.
Referenced by ParticleCashedLayout< T, Dim, Mesh >::getCashedParticles(), ParticleInteractLayout< T, Dim, Mesh >::getPairlist(), PartBunch::setBCAllPeriodic(), PartBunch::setBCForDCBeam(), ParticleCashedLayout< T, Dim, Mesh >::update(), ParticleInteractLayout< T, Dim, Mesh >::update(), and BoxParticleCachingPolicy< T, Dim, Mesh >::updateCacheInformation().
ParticleReflectiveBCond()
template<class T > T ParticleReflectiveBCond (const T t, const T minval, const T maxval) inline
Definition at line 49 of file ParticleBConds.h.
ParticleSinkBCond()
template<class T > T ParticleSinkBCond (const T t, const T minval, const T maxval) inline
Definition at line 60 of file ParticleBConds.h.