OPAL (Object Oriented Parallel Accelerator Library): Sequence Class Reference
Sequence Class Reference
#include <Sequence.h>
Public Types
typedef TBeamline< SequenceMember > TLine
The type of a sequence line.
Public Types inherited from Element
enum ReferenceType { IS_ENTRY, IS_CENTRE, IS_EXIT }
Reference for element positioning.
Public Member Functions
Sequence ()
Exemplar constructor.
virtual ~Sequence ()
virtual Sequence * clone (const std::string &name)
Make clone.
virtual Sequence * copy (const std::string &name)
Make copy of the sequence line.
virtual double getLength () const
Return sequence length.
virtual double getEntrance (ReferenceType) const
Return the arc length from origin to entrance.
virtual double getExit (ReferenceType) const
Return the arc length from origin to exit.
ReferenceType getReference () const
Return the reference type flag.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Make a sequence template.
virtual void parse (Statement &)
Parse sequence.
virtual void print (std::ostream &) const
Print sequence.
virtual void replace (Object *oldObject, Object *newObject)
Replace references to elements.
virtual void update ()
Update the embedded CLASSIC beam line.
virtual TLine * fetchLine () const
Return the embedded CLASSIC beam line.
void storeLine (TLine &line)
Store sequence line.
Public Member Functions inherited from BeamSequence
virtual ~BeamSequence ()
virtual const std::string getCategory () const
Return the object category as a string.
Public Member Functions inherited from Element
virtual ~Element ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded CLASSIC element.
void setElement (ElementBase *)
Assign new CLASSIC element.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
Sequence (const Sequence &)
void operator= (const Sequence &)
Sequence (const std::string &name, Sequence *parent)
void addEndMarkers (TLine &line) const
double findDriftLength (TLine::iterator drift) const
TLine::iterator findNamedPosition (TLine &, const std::string &) const
void insertDrifts (TLine &line)
Static Private Member Functions
static void updateList (Sequence *, TLine *)
Private Attributes
ReferenceType itsCode
std::string itsRefPoint
Friends
class Edit
class SequenceParser
class SequenceTemplate
Additional Inherited Members
Static Public Member Functions inherited from BeamSequence
static BeamSequence * find (const std::string &name)
Find a BeamSequence by name.
Static Public Member Functions inherited from Element
static Element * find (const std::string &name)
Find named Element.
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from BeamSequence
BeamSequence (int size, const char *name, const char *help)
Constructor for exemplars.
BeamSequence (const std::string &name, BeamSequence *parent)
Constructor for clones.
Protected Member Functions inherited from Element
Element (int size, const char *name, const char *help)
Constructor for exemplars.
Element (const std::string &name, Element *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 33 of file Sequence.h.
Member Typedef Documentation
TLine
typedef TBeamline<SequenceMember> Sequence::TLine
The type of a sequence line.
Definition at line 42 of file Sequence.h.
Constructor & Destructor Documentation
Sequence() [1/3]
Sequence::Sequence ()
Exemplar constructor.
Definition at line 52 of file Sequence.cpp.
References Object::itsAttr, Attributes::makeReal(), Attributes::makeString(), Object::registerOwnership(), Element::setElement(), AttributeHandler::STATEMENT, and Attrib::Distribution::TYPE.
Referenced by clone().
~Sequence()
Sequence::~Sequence () virtual
Definition at line 93 of file Sequence.cpp.
Sequence() [2/3]
Sequence::Sequence (const Sequence &) private
Sequence() [3/3]
Sequence::Sequence (const std::string & name, Sequence * parent) private
Definition at line 83 of file Sequence.cpp.
References name, and Element::setElement().
Member Function Documentation
addEndMarkers()
void Sequence::addEndMarkers (TLine & line) const private
Definition at line 312 of file Sequence.cpp.
References SequenceMember::ABSOLUTE, Element::find(), Element::getElement(), getLength(), SequenceMember::GLOBAL, SequenceMember::itsFlag, SequenceMember::itsPosition, SequenceMember::itsType, and ElmPtr::setElement().
Referenced by SequenceParser::parse().
clone()
Sequence * Sequence::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 97 of file Sequence.cpp.
References name, and Sequence().
Referenced by copy(), and SequenceTemplate::makeInstance().
copy()
Sequence * Sequence::copy (const std::string & name) virtual
Make copy of the sequence line.
Implements BeamSequence.
Definition at line 102 of file Sequence.cpp.
References clone(), ElementBase::clone(), ElementBase::copyStructure(), fetchLine(), SequenceMember::GENERATED, ElmPtr::getElement(), name, ElmPtr::setElement(), and storeLine().
fetchLine()
Sequence::TLine * Sequence::fetchLine () const virtual
Return the embedded CLASSIC beam line.
Implements BeamSequence.
Definition at line 278 of file Sequence.cpp.
References Element::getElement().
Referenced by copy(), getEntrance(), getExit(), print(), replace(), storeLine(), and update().
findDriftLength()
double Sequence::findDriftLength (TLine::iterator drift) const private
Definition at line 325 of file Sequence.cpp.
References abs(), Element::getEntrance(), Element::getExit(), Object::getOpalName(), and itsCode.
Referenced by updateList().
findNamedPosition()
Sequence::TLine::iterator Sequence::findNamedPosition (TLine & line, const std::string & name) const private
Definition at line 124 of file Sequence.cpp.
References SequenceMember::GENERATED, and name.
Referenced by SequenceParser::findFromPositions(), getEntrance(), and getExit().
getEntrance()
double Sequence::getEntrance (ReferenceType ref) const virtual
Return the arc length from origin to entrance.
Reimplemented from Element.
Definition at line 155 of file Sequence.cpp.
References fetchLine(), findNamedPosition(), Element::getEntrance(), itsRefPoint, and Hypervolume::ref.
getExit()
double Sequence::getExit (ReferenceType ref) const virtual
Return the arc length from origin to exit.
Reimplemented from Element.
Definition at line 166 of file Sequence.cpp.
References fetchLine(), findNamedPosition(), Element::getExit(), getLength(), itsRefPoint, and Hypervolume::ref.
getLength()
double Sequence::getLength () const virtual
Return sequence length.
Implements Element.
Definition at line 150 of file Sequence.cpp.
References Attributes::getReal(), and Object::itsAttr.
Referenced by addEndMarkers(), and getExit().
getReference()
Sequence::ReferenceType Sequence::getReference () const
Return the reference type flag.
Definition at line 177 of file Sequence.cpp.
References Attributes::getString(), Element::IS_CENTRE, Element::IS_ENTRY, Element::IS_EXIT, Object::itsAttr, and Hypervolume::ref.
Referenced by storeLine().
insertDrifts()
void Sequence::insertDrifts (Sequence::TLine & line) private
Definition at line 368 of file Sequence.cpp.
References SequenceMember::GENERATED, SequenceMember::itsType, ElmPtr::setElement(), and ElementBase::setName().
Referenced by SequenceParser::parse().
makeTemplate()
Object * Sequence::makeTemplate (const std::string & name, TokenStream & is, Statement & statement) virtual
Make a sequence template.
Reimplemented from Object.
Definition at line 192 of file Sequence.cpp.
References name, and SequenceTemplate::parseTemplate().
operator=()
void Sequence::operator= (const Sequence &) private
parse()
void Sequence::parse (Statement & statement) virtual
Parse sequence.
Reimplemented from Object.
Definition at line 206 of file Sequence.cpp.
References Attributes::getString(), Object::itsAttr, itsRefPoint, Object::parse(), and OpalParser::run().
print()
void Sequence::print (std::ostream & os) const virtual
Print sequence.
Reimplemented from Object.
Definition at line 218 of file Sequence.cpp.
References endl(), fetchLine(), SequenceMember::GENERATED, ElmPtr::getElement(), ElementBase::getName(), Object::getOpalName(), FlaggedElmPtr::getReflectionFlag(), Object::isShared(), Object::itsAttr, SequenceMember::itsPosition, SequenceMember::itsType, name, and Inform::precision().
replace()
void Sequence::replace (Object * oldObject, Object * newObject) virtual
Replace references to elements.
Reimplemented from Object.
Definition at line 259 of file Sequence.cpp.
References DefaultVisitor::execute(), fetchLine(), Element::getElement(), and Object::getOpalName().
storeLine()
void Sequence::storeLine (TLine & line)
Store sequence line.
Definition at line 283 of file Sequence.cpp.
References OpalData::apply(), fetchLine(), Element::find(), SequenceMember::GENERATED, OpalData::getInstance(), getReference(), Object::increment(), itsCode, and name.
Referenced by copy(), and SequenceParser::parse().
update()
void Sequence::update () virtual
Update the embedded CLASSIC beam line.
Reimplemented from Object.
Definition at line 272 of file Sequence.cpp.
References fetchLine(), and updateList().
updateList()
void Sequence::updateList (Sequence * seq, TLine * line) static private
Definition at line 383 of file Sequence.cpp.
References OpalData::find(), findDriftLength(), OpalData::getInstance(), ElementBase::getName(), and ElementBase::isSharable().
Referenced by update().
Friends And Related Function Documentation
Edit
friend class Edit friend
Definition at line 35 of file Sequence.h.
SequenceParser
friend class SequenceParser friend
Definition at line 36 of file Sequence.h.
SequenceTemplate
friend class SequenceTemplate friend
Definition at line 37 of file Sequence.h.
Member Data Documentation
itsCode
ReferenceType Sequence::itsCode private
Definition at line 124 of file Sequence.h.
Referenced by findDriftLength(), and storeLine().
itsRefPoint
std::string Sequence::itsRefPoint private
Definition at line 127 of file Sequence.h.
Referenced by getEntrance(), getExit(), and parse().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Lines/Sequence.h
/psi/home/gsell/data/src/OPAL/src/src/Lines/Sequence.cpp