OPAL (Object Oriented Parallel Accelerator Library): HashPairBuilderParallel< PBase > Class Template Reference
HashPairBuilderParallel< PBase > Class Template Reference
#include <HashPairBuilderParallel.h>
Public Types
enum { Dim = PBase::Dim }
typedef PBase::Position_t Position_t
Public Member Functions
HashPairBuilderParallel (PBase &p_r, double gammaz)
template<class Pred , class OP >
void forEach (const Pred &pred_r, const OP &op_r)
Private Member Functions
std::size_t getBucketId (std::size_t i)
Private Attributes
PBase & particles_mr
double gammaz_m
Vektor< int, 3 > bucketsPerDim_m
Vektor< double, 3 > hChaining_m
Vektor< double, 3 > rmin_m
Vektor< double, 3 > rmax_m
Vektor< double, 3 > hr_m
Detailed Description
template<class PBase>
class HashPairBuilderParallel< PBase >
Definition at line 37 of file HashPairBuilderParallel.h.
Member Typedef Documentation
Position_t
template<class PBase> typedef PBase::Position_t HashPairBuilderParallel< PBase >::Position_t
Definition at line 41 of file HashPairBuilderParallel.h.
Member Enumeration Documentation
anonymous enum
template<class PBase> anonymous enum
Enumerator
Dim
Definition at line 40 of file HashPairBuilderParallel.h.
Constructor & Destructor Documentation
HashPairBuilderParallel()
template<class PBase> HashPairBuilderParallel< PBase >::HashPairBuilderParallel (PBase & p_r, double gammaz) inline
Definition at line 43 of file HashPairBuilderParallel.h.
References HashPairBuilderParallel< PBase >::hr_m.
Member Function Documentation
forEach()
template<class PBase> template<class Pred , class OP > void HashPairBuilderParallel< PBase >::forEach (const Pred & pred_r, const OP & op_r) inline
Definition at line 48 of file HashPairBuilderParallel.h.
References HashPairBuilderParallel< PBase >::bucketsPerDim_m, endl(), floor(), HashPairBuilderParallel< PBase >::gammaz_m, HashPairBuilderParallel< PBase >::getBucketId(), HashPairBuilderParallel< PBase >::hChaining_m, HashPairBuilderParallel< PBase >::hr_m, max(), IpplInfo::myNode(), Hypervolume::n, HashPairBuilderParallel< PBase >::particles_mr, HashPairBuilderParallel< PBase >::rmax_m, and HashPairBuilderParallel< PBase >::rmin_m.
Referenced by P3MPoissonSolver::calculatePairForces().
getBucketId()
template<class PBase> std::size_t HashPairBuilderParallel< PBase >::getBucketId (std::size_t i) inline private
Definition at line 190 of file HashPairBuilderParallel.h.
References HashPairBuilderParallel< PBase >::bucketsPerDim_m, HashPairBuilderParallel< PBase >::hChaining_m, HashPairBuilderParallel< PBase >::particles_mr, HashPairBuilderParallel< PBase >::rmax_m, and HashPairBuilderParallel< PBase >::rmin_m.
Referenced by HashPairBuilderParallel< PBase >::forEach().
Member Data Documentation
bucketsPerDim_m
template<class PBase> Vektor<int,3> HashPairBuilderParallel< PBase >::bucketsPerDim_m private
Definition at line 214 of file HashPairBuilderParallel.h.
Referenced by HashPairBuilderParallel< PBase >::forEach(), and HashPairBuilderParallel< PBase >::getBucketId().
gammaz_m
template<class PBase> double HashPairBuilderParallel< PBase >::gammaz_m private
Definition at line 213 of file HashPairBuilderParallel.h.
Referenced by HashPairBuilderParallel< PBase >::forEach().
hChaining_m
template<class PBase> Vektor<double,3> HashPairBuilderParallel< PBase >::hChaining_m private
Definition at line 215 of file HashPairBuilderParallel.h.
Referenced by HashPairBuilderParallel< PBase >::forEach(), and HashPairBuilderParallel< PBase >::getBucketId().
hr_m
template<class PBase> Vektor<double,3> HashPairBuilderParallel< PBase >::hr_m private
Definition at line 218 of file HashPairBuilderParallel.h.
Referenced by HashPairBuilderParallel< PBase >::forEach(), and HashPairBuilderParallel< PBase >::HashPairBuilderParallel().
particles_mr
template<class PBase> PBase& HashPairBuilderParallel< PBase >::particles_mr private
Definition at line 212 of file HashPairBuilderParallel.h.
Referenced by HashPairBuilderParallel< PBase >::forEach(), and HashPairBuilderParallel< PBase >::getBucketId().
rmax_m
template<class PBase> Vektor<double,3> HashPairBuilderParallel< PBase >::rmax_m private
Definition at line 217 of file HashPairBuilderParallel.h.
Referenced by HashPairBuilderParallel< PBase >::forEach(), and HashPairBuilderParallel< PBase >::getBucketId().
rmin_m
template<class PBase> Vektor<double,3> HashPairBuilderParallel< PBase >::rmin_m private
Definition at line 216 of file HashPairBuilderParallel.h.
Referenced by HashPairBuilderParallel< PBase >::forEach(), and HashPairBuilderParallel< PBase >::getBucketId().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/PairBuilder/HashPairBuilderParallel.h