OPAL (Object Oriented Parallel Accelerator Library): PETE_Expr< WrappedExpr > Class Template Reference
PETE_Expr< WrappedExpr > Class Template Reference
#include <PETE.h>
Public Types
typedef WrappedExpr Wrapped
Public Member Functions
WrappedExpr & PETE_unwrap ()
const WrappedExpr & PETE_unwrap () const
Detailed Description
template<class WrappedExpr>
class PETE_Expr< WrappedExpr >
Definition at line 76 of file PETE.h.
Member Typedef Documentation
Wrapped
template<class WrappedExpr> typedef WrappedExpr PETE_Expr< WrappedExpr >::Wrapped
Definition at line 79 of file PETE.h.
Member Function Documentation
PETE_unwrap() [1/2]
template<class WrappedExpr> WrappedExpr& PETE_Expr< WrappedExpr >::PETE_unwrap () inline
Definition at line 81 of file PETE.h.
Referenced by abs(), any(), assign(), bounds(), max(), min(), minmax(), pete_cast(), prod(), Reduction(), sum(), and where().
PETE_unwrap() [2/2]
template<class WrappedExpr> const WrappedExpr& PETE_Expr< WrappedExpr >::PETE_unwrap () const inline
Definition at line 85 of file PETE.h.
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/PETE/PETE.h