OPAL (Object Oriented Parallel Accelerator Library): H5PartWrapper Class Reference
H5PartWrapper Class Reference abstract
#include <H5PartWrapper.h>
Public Member Functions
virtual ~H5PartWrapper ()
void close ()
double getLastPosition ()
virtual void readHeader ()=0
virtual void readStep (PartBunchBase< double, 3 > *, h5_ssize_t firstParticle, h5_ssize_t lastParticle)=0
virtual void writeHeader ()=0
virtual void writeStep (PartBunchBase< double, 3 > *, const std::map< std::string, double > &)=0
virtual bool predecessorIsSameFlavour () const =0
void storeCavityInformation ()
size_t getNumParticles () const
Protected Member Functions
H5PartWrapper (const std::string &fileName, h5_int32_t flags=H5_O_WRONLY)
H5PartWrapper (const std::string &fileName, int restartStep, std::string sourceFile, h5_int32_t flags=H5_O_RDWR)
void open (h5_int32_t flags)
void copyFile (const std::string &sourceFile, int lastStep=-1, h5_int32_t flags=H5_O_WRONLY)
void copyFileSystem (const std::string &sourceFile)
void copyHeader (h5_file_t source)
void copyStep (h5_file_t source, int step)
void copyStepHeader (h5_file_t source)
void copyStepData (h5_file_t source)
void sendFailureMessage (bool failed, const std::string &where, const std::string &what)
void receiveFailureMessage (int sourceNode, const std::string &where, const std::string &what)
Static Protected Member Functions
static void reportOnError (h5_int64_t rc, const char *file, int line)
Protected Attributes
h5_file_t file_m
std::string fileName_m
std::string predecessorOPALFlavour_m
h5_int64_t numSteps_m
bool startedFromExistingFile_m
Static Protected Attributes
static std::string copyFilePrefix_m = ".copy"
Detailed Description
Definition at line 34 of file H5PartWrapper.h.
Constructor & Destructor Documentation
~H5PartWrapper()
H5PartWrapper::~H5PartWrapper () virtual
Definition at line 57 of file H5PartWrapper.cpp.
References close().
H5PartWrapper() [1/2]
H5PartWrapper::H5PartWrapper (const std::string & fileName, h5_int32_t flags = H5_O_WRONLY) protected
Definition at line 31 of file H5PartWrapper.cpp.
References open().
H5PartWrapper() [2/2]
H5PartWrapper::H5PartWrapper (const std::string & fileName, int restartStep, std::string sourceFile, h5_int32_t flags = H5_O_RDWR) protected
Definition at line 41 of file H5PartWrapper.cpp.
References copyFile(), fileName_m, and open().
Member Function Documentation
close()
void H5PartWrapper::close ()
Definition at line 61 of file H5PartWrapper.cpp.
References Communicate::barrier(), IpplInfo::Comm, file_m, and REPORTONERROR.
Referenced by H5Writer::close(), copyFile(), H5Writer::H5Writer(), open(), MultiBunchHandler::readBunch(), MultiBunchHandler::saveBunch(), storeCavityInformation(), H5PartWrapperForPC::writeStep(), H5PartWrapperForPT::writeStep(), and ~H5PartWrapper().
copyFile()
void H5PartWrapper::copyFile (const std::string & sourceFile, int lastStep = -1, h5_int32_t flags = H5_O_WRONLY) protected
Definition at line 128 of file H5PartWrapper.cpp.
References Communicate::barrier(), close(), IpplInfo::Comm, copyFilePrefix_m, copyFileSystem(), copyHeader(), copyStep(), fileName_m, Hypervolume::fs, IpplInfo::getComm(), IpplInfo::myNode(), numSteps_m, open(), PAssert, predecessorOPALFlavour_m, READSTEPATTRIB, and REPORTONERROR.
Referenced by H5PartWrapper().
copyFileSystem()
void H5PartWrapper::copyFileSystem (const std::string & sourceFile) protected
Definition at line 253 of file H5PartWrapper.cpp.
References fileName_m, IpplInfo::myNode(), receiveFailureMessage(), and sendFailureMessage().
Referenced by copyFile().
copyHeader()
void H5PartWrapper::copyHeader (h5_file_t source) protected
Definition at line 290 of file H5PartWrapper.cpp.
References PyOpal::PyOpalObjectNS::attributeName, file_m, READFILEATTRIB, REPORTONERROR, WRITEFILEATTRIB, and WRITESTRINGFILEATTRIB.
Referenced by copyFile().
copyStep()
void H5PartWrapper::copyStep (h5_file_t source, int step) protected
Definition at line 360 of file H5PartWrapper.cpp.
References copyStepData(), copyStepHeader(), file_m, numSteps_m, and REPORTONERROR.
Referenced by copyFile().
copyStepData()
void H5PartWrapper::copyStepData (h5_file_t source) protected
Definition at line 445 of file H5PartWrapper.cpp.
References Util::c_data(), file_m, IpplInfo::getNodes(), IpplInfo::myNode(), READDATA, REPORTONERROR, and WRITEDATA.
Referenced by copyStep().
copyStepHeader()
void H5PartWrapper::copyStepHeader (h5_file_t source) protected
Definition at line 371 of file H5PartWrapper.cpp.
References PyOpal::PyOpalObjectNS::attributeName, file_m, predecessorOPALFlavour_m, READSTEPATTRIB, REPORTONERROR, WRITESTEPATTRIB, and WRITESTRINGSTEPATTRIB.
Referenced by copyStep().
getLastPosition()
double H5PartWrapper::getLastPosition () inline
Definition at line 89 of file H5PartWrapper.h.
References file_m, open(), readStep(), READSTEPATTRIB, and REPORTONERROR.
Referenced by H5Writer::getLastPosition().
getNumParticles()
size_t H5PartWrapper::getNumParticles () const
Definition at line 524 of file H5PartWrapper.cpp.
References file_m, numSteps_m, and REPORTONERROR.
Referenced by Distribution::doRestartOpalCycl(), Distribution::doRestartOpalT(), MultiBunchHandler::readBunch(), H5PartWrapperForPT::readStepData(), and H5PartWrapperForPC::readStepData().
open()
void H5PartWrapper::open (h5_int32_t flags) protected
Definition at line 71 of file H5PartWrapper.cpp.
References close(), file_m, fileName_m, IpplInfo::getComm(), and PAssert.
Referenced by copyFile(), getLastPosition(), H5PartWrapper(), storeCavityInformation(), H5PartWrapperForPC::writeStep(), and H5PartWrapperForPT::writeStep().
predecessorIsSameFlavour()
virtual bool H5PartWrapper::predecessorIsSameFlavour () const pure virtual
Implemented in H5PartWrapperForPT, and H5PartWrapperForPC.
Referenced by Distribution::doRestartOpalCycl().
readHeader()
virtual void H5PartWrapper::readHeader () pure virtual
Implemented in H5PartWrapperForPT, and H5PartWrapperForPC.
Referenced by Distribution::doRestartOpalCycl(), and Distribution::doRestartOpalT().
readStep()
virtual void H5PartWrapper::readStep (PartBunchBase< double, 3 > * , h5_ssize_t firstParticle, h5_ssize_t lastParticle) pure virtual
Implemented in H5PartWrapperForPT, and H5PartWrapperForPC.
Referenced by Distribution::doRestartOpalCycl(), Distribution::doRestartOpalT(), and getLastPosition().
receiveFailureMessage()
void H5PartWrapper::receiveFailureMessage (int sourceNode, const std::string & where, const std::string & what) protected
Definition at line 512 of file H5PartWrapper.cpp.
References IpplInfo::Comm, getMessage(), Communicate::receive_block(), and where().
Referenced by copyFileSystem().
reportOnError()
void H5PartWrapper::reportOnError (h5_int64_t rc, const char * file, int line) inline static protected
Definition at line 83 of file H5PartWrapper.h.
References endl(), and ERRORMSG.
Referenced by H5PartWrapperForPT::writeStepData().
sendFailureMessage()
void H5PartWrapper::sendFailureMessage (bool failed, const std::string & where, const std::string & what) protected
Definition at line 500 of file H5PartWrapper.cpp.
References Communicate::broadcast_all(), IpplInfo::Comm, putMessage(), and where().
Referenced by copyFileSystem().
storeCavityInformation()
void H5PartWrapper::storeCavityInformation ()
Write number of Cavities with autophase information
Definition at line 86 of file H5PartWrapper.cpp.
References close(), end(), endl(), file_m, OpalData::getFirstMaxPhases(), OpalData::getInstance(), OpalData::getLastMaxPhases(), OpalData::getNumberOfMaxPhases(), INFOMSG, open(), WRITEFILEATTRIB, and WRITESTRINGFILEATTRIB.
Referenced by H5Writer::storeCavityInformation().
writeHeader()
virtual void H5PartWrapper::writeHeader () pure virtual
Implemented in H5PartWrapperForPT, and H5PartWrapperForPC.
Referenced by H5Writer::H5Writer().
writeStep()
virtual void H5PartWrapper::writeStep (PartBunchBase< double, 3 > * , const std::map< std::string, double > &) pure virtual
Implemented in H5PartWrapperForPT, and H5PartWrapperForPC.
Referenced by H5Writer::writePhaseSpace().
Member Data Documentation
copyFilePrefix_m
std::string H5PartWrapper::copyFilePrefix_m = ".copy" static protected
Definition at line 79 of file H5PartWrapper.h.
Referenced by copyFile().
file_m
h5_file_t H5PartWrapper::file_m protected
Definition at line 73 of file H5PartWrapper.h.
Referenced by close(), copyHeader(), copyStep(), copyStepData(), copyStepHeader(), getLastPosition(), getNumParticles(), H5PartWrapperForPT::H5PartWrapperForPT(), open(), H5PartWrapperForPC::readHeader(), H5PartWrapperForPT::readHeader(), H5PartWrapperForPC::readStep(), H5PartWrapperForPT::readStep(), H5PartWrapperForPT::readStepData(), H5PartWrapperForPC::readStepData(), H5PartWrapperForPT::readStepHeader(), H5PartWrapperForPC::readStepHeader(), storeCavityInformation(), H5PartWrapperForPC::writeHeader(), H5PartWrapperForPT::writeHeader(), H5PartWrapperForPC::writeStepData(), H5PartWrapperForPT::writeStepData(), H5PartWrapperForPT::writeStepHeader(), and H5PartWrapperForPC::writeStepHeader().
fileName_m
std::string H5PartWrapper::fileName_m protected
Definition at line 74 of file H5PartWrapper.h.
Referenced by copyFile(), copyFileSystem(), H5PartWrapper(), and open().
numSteps_m
h5_int64_t H5PartWrapper::numSteps_m protected
Definition at line 76 of file H5PartWrapper.h.
Referenced by copyFile(), copyStep(), getNumParticles(), H5PartWrapperForPC::writeStep(), H5PartWrapperForPC::writeStepHeader(), and H5PartWrapperForPT::writeStepHeader().
predecessorOPALFlavour_m
std::string H5PartWrapper::predecessorOPALFlavour_m protected
Definition at line 75 of file H5PartWrapper.h.
Referenced by copyFile(), copyStepHeader(), H5PartWrapperForPC::predecessorIsSameFlavour(), H5PartWrapperForPT::predecessorIsSameFlavour(), H5PartWrapperForPC::readStepData(), and H5PartWrapperForPC::readStepHeader().
startedFromExistingFile_m
bool H5PartWrapper::startedFromExistingFile_m protected
Definition at line 77 of file H5PartWrapper.h.
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Structure/H5PartWrapper.h
/psi/home/gsell/data/src/OPAL/src/src/Structure/H5PartWrapper.cpp