OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Utility/ParticleDebug.hpp File Reference
ParticleDebug.hpp File Reference
#include "Utility/ParticleDebug.h"
#include "Utility/Inform.h"
#include "Particle/ParticleAttrib.h"
#include <iostream>
#include <iomanip>
Functions
template<class T >
void pap (ParticleAttrib< T > &pattr, bool docomm)
template<class T >
void epap (ParticleAttrib< T > &pattr, int i, bool docomm)
template<class T >
void spap (ParticleAttrib< T > &pattr, int ibase, int ibound, int istride, bool docomm)
Function Documentation
epap()
template<class T > void epap (ParticleAttrib< T > & pattr, int i, bool docomm)
Definition at line 98 of file ParticleDebug.hpp.
References FldDbgInform, FldDbgInformIsSet, INFORM_ALL_NODES, PtclDbgInform, PtclDbgInformIsSet, setPtclDbgInform(), and spap().
pap()
template<class T > void pap (ParticleAttrib< T > & pattr, bool docomm)
Definition at line 42 of file ParticleDebug.hpp.
References Communicate::barrier(), Communicate::broadcast_others(), IpplInfo::Comm, FldDbgInform, FldDbgInformIsSet, Message::get(), IpplInfo::getNodes(), INFORM_ALL_NODES, IPPL_APP_CYCLE, IPPL_APP_TAG0, IpplInfo::myNode(), TagMaker::next_tag(), PtclDbgInform, PtclDbgInformIsSet, Message::put(), Communicate::receive_block(), Communicate::send(), setPtclDbgInform(), ParticleAttrib< T >::size(), and spap().
spap()
template<class T > void spap (ParticleAttrib< T > & pattr, int ibase, int ibound, int istride, bool docomm)
Definition at line 117 of file ParticleDebug.hpp.
References Communicate::barrier(), Communicate::broadcast_others(), IpplInfo::Comm, digitsPastDecimal, elementsPerLine, endl(), Index::first(), FldDbgInform, FldDbgInformIsSet, Message::get(), Message::getmsg(), IpplInfo::getNodes(), Inform::getPrintNode(), INFORM_ALL_NODES, Index::intersect(), IPPL_APP_CYCLE, IPPL_APP_TAG0, Index::last(), IpplInfo::myNode(), TagMaker::next_tag(), PtclDbgInform, PtclDbgInformIsSet, Message::put(), Message::putmsg(), Communicate::receive_block(), Communicate::send(), setPtclDbgInform(), ParticleAttrib< T >::size(), Index::touches(), WARNMSG, and widthOfElements.
Referenced by epap(), and pap().