OPAL (Object Oriented Parallel Accelerator Library): IpplTimerInfo Class Reference
IpplTimerInfo Class Reference
#include <IpplTimings.h>
Public Types
typedef unsigned int TimerRef
Public Member Functions
IpplTimerInfo ()
~IpplTimerInfo ()
void start ()
void stop ()
void clear ()
Public Attributes
Timer t
std::string name
double cpuTime
double wallTime
bool running
TimerRef indx
Detailed Description
Definition at line 53 of file IpplTimings.h.
Member Typedef Documentation
TimerRef
typedef unsigned int IpplTimerInfo::TimerRef
Definition at line 57 of file IpplTimings.h.
Constructor & Destructor Documentation
IpplTimerInfo()
IpplTimerInfo::IpplTimerInfo () inline
Definition at line 60 of file IpplTimings.h.
References clear().
~IpplTimerInfo()
IpplTimerInfo::~IpplTimerInfo () inline
Definition at line 65 of file IpplTimings.h.
Member Function Documentation
clear()
void IpplTimerInfo::clear (void) inline
Definition at line 96 of file IpplTimings.h.
References Timer::clear(), running, Timer::stop(), and t.
Referenced by IpplTimerInfo().
start()
void IpplTimerInfo::start () inline
Definition at line 68 of file IpplTimings.h.
References Timer::clear(), name, running, Timer::start(), Timer::stop(), and t.
stop()
void IpplTimerInfo::stop () inline
Definition at line 82 of file IpplTimings.h.
References Timer::clock_time(), Timer::cpu_time(), cpuTime, name, running, Timer::stop(), t, and wallTime.
Member Data Documentation
cpuTime
double IpplTimerInfo::cpuTime
Definition at line 109 of file IpplTimings.h.
Referenced by Timing::print(), and stop().
indx
TimerRef IpplTimerInfo::indx
Definition at line 116 of file IpplTimings.h.
Referenced by Timing::getTimer().
name
std::string IpplTimerInfo::name
Definition at line 106 of file IpplTimings.h.
Referenced by Timing::getTimer(), Timing::print(), start(), and stop().
running
bool IpplTimerInfo::running
Definition at line 113 of file IpplTimings.h.
Referenced by clear(), start(), and stop().
t
Timer IpplTimerInfo::t
Definition at line 103 of file IpplTimings.h.
Referenced by clear(), start(), and stop().
wallTime
double IpplTimerInfo::wallTime
Definition at line 110 of file IpplTimings.h.
Referenced by Timing::print(), and stop().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/IpplTimings.h