OPAL (Object Oriented Parallel Accelerator Library): HashPairBuilderPeriodicParallel< PBase > Class Template Reference
HashPairBuilderPeriodicParallel< PBase > Class Template Reference
#include <HashPairBuilderPeriodicParallel.h>
Public Types
enum { Dim = PBase::Dim }
enum { Dim = PBase::Dim }
typedef PBase::Position_t Position_t
typedef PBase::Position_t Position_t
Public Member Functions
HashPairBuilderPeriodicParallel (PBase &p)
template<class Pred , class OP >
void for_each (const Pred &pred, const OP &op, Vektor< double, 3 > extend_l, Vektor< double, 3 > extend_r)
HashPairBuilderPeriodicParallel (PBase &p)
template<class Pred , class OP >
void for_each (const Pred &pred, const OP &op, Vektor< double, 3 > extend_l, Vektor< double, 3 > extend_r)
Private Member Functions
template<class Pred >
int get_bucket_id (int i, const Pred &)
template<class Pred >
int get_bucket_id (int i, const Pred &pred)
Private Attributes
PBase & particles
Vektor< int, 3 > buckets_per_dim
Vektor< double, 3 > h_chaining
Vektor< double, 3 > rmin_m
Vektor< double, 3 > rmax_m
Vektor< double, 3 > hr_m
Detailed Description
template<class PBase>
class HashPairBuilderPeriodicParallel< PBase >
Definition at line 25 of file HashPairBuilderPeriodicParallel.h.
Member Typedef Documentation
Position_t [1/2]
template<class PBase > typedef PBase::Position_t HashPairBuilderPeriodicParallel< PBase >::Position_t
Definition at line 14 of file HashPairBuilderPeriodicParallel_globCHaining.h.
Position_t [2/2]
template<class PBase > typedef PBase::Position_t HashPairBuilderPeriodicParallel< PBase >::Position_t
Definition at line 29 of file HashPairBuilderPeriodicParallel.h.
Member Enumeration Documentation
anonymous enum
template<class PBase > anonymous enum
Enumerator
Dim
Definition at line 28 of file HashPairBuilderPeriodicParallel.h.
anonymous enum
template<class PBase > anonymous enum
Enumerator
Dim
Definition at line 13 of file HashPairBuilderPeriodicParallel_globCHaining.h.
Constructor & Destructor Documentation
HashPairBuilderPeriodicParallel() [1/2]
template<class PBase > HashPairBuilderPeriodicParallel< PBase >::HashPairBuilderPeriodicParallel (PBase & p) inline
Definition at line 31 of file HashPairBuilderPeriodicParallel.h.
References HashPairBuilderPeriodicParallel< PBase >::hr_m.
HashPairBuilderPeriodicParallel() [2/2]
template<class PBase > HashPairBuilderPeriodicParallel< PBase >::HashPairBuilderPeriodicParallel (PBase & p) inline
Definition at line 16 of file HashPairBuilderPeriodicParallel_globCHaining.h.
Member Function Documentation
for_each() [1/2]
template<class PBase > template<class Pred , class OP > void HashPairBuilderPeriodicParallel< PBase >::for_each (const Pred & pred, const OP & op, Vektor< double, 3 > extend_l, Vektor< double, 3 > extend_r) inline
Definition at line 19 of file HashPairBuilderPeriodicParallel_globCHaining.h.
References HashPairBuilderPeriodicParallel< PBase >::buckets_per_dim, endl(), floor(), HashPairBuilderPeriodicParallel< PBase >::get_bucket_id(), HashPairBuilderPeriodicParallel< PBase >::h_chaining, max(), Hypervolume::n, HashPairBuilderPeriodicParallel< PBase >::particles, HashPairBuilderPeriodicParallel< PBase >::rmax_m, and HashPairBuilderPeriodicParallel< PBase >::rmin_m.
for_each() [2/2]
template<class PBase > template<class Pred , class OP > void HashPairBuilderPeriodicParallel< PBase >::for_each (const Pred & pred, const OP & op, Vektor< double, 3 > extend_l, Vektor< double, 3 > extend_r) inline
Definition at line 34 of file HashPairBuilderPeriodicParallel.h.
References HashPairBuilderPeriodicParallel< PBase >::buckets_per_dim, floor(), HashPairBuilderPeriodicParallel< PBase >::get_bucket_id(), HashPairBuilderPeriodicParallel< PBase >::h_chaining, HashPairBuilderPeriodicParallel< PBase >::hr_m, max(), Hypervolume::n, HashPairBuilderPeriodicParallel< PBase >::particles, HashPairBuilderPeriodicParallel< PBase >::rmax_m, and HashPairBuilderPeriodicParallel< PBase >::rmin_m.
get_bucket_id() [1/2]
template<class PBase > template<class Pred > int HashPairBuilderPeriodicParallel< PBase >::get_bucket_id (int i, const Pred & pred) inline private
Definition at line 182 of file HashPairBuilderPeriodicParallel_globCHaining.h.
References HashPairBuilderPeriodicParallel< PBase >::buckets_per_dim, HashPairBuilderPeriodicParallel< PBase >::h_chaining, HashPairBuilderPeriodicParallel< PBase >::particles, and HashPairBuilderPeriodicParallel< PBase >::rmin_m.
get_bucket_id() [2/2]
template<class PBase > template<class Pred > int HashPairBuilderPeriodicParallel< PBase >::get_bucket_id (int i, const Pred &) inline private
Definition at line 205 of file HashPairBuilderPeriodicParallel.h.
References HashPairBuilderPeriodicParallel< PBase >::buckets_per_dim, HashPairBuilderPeriodicParallel< PBase >::h_chaining, HashPairBuilderPeriodicParallel< PBase >::particles, and HashPairBuilderPeriodicParallel< PBase >::rmin_m.
Referenced by HashPairBuilderPeriodicParallel< PBase >::for_each().
Member Data Documentation
buckets_per_dim
template<class PBase > Vektor< int, 3 > HashPairBuilderPeriodicParallel< PBase >::buckets_per_dim private
Definition at line 219 of file HashPairBuilderPeriodicParallel.h.
Referenced by HashPairBuilderPeriodicParallel< PBase >::for_each(), and HashPairBuilderPeriodicParallel< PBase >::get_bucket_id().
h_chaining
template<class PBase > Vektor< double, 3 > HashPairBuilderPeriodicParallel< PBase >::h_chaining private
Definition at line 220 of file HashPairBuilderPeriodicParallel.h.
Referenced by HashPairBuilderPeriodicParallel< PBase >::for_each(), and HashPairBuilderPeriodicParallel< PBase >::get_bucket_id().
hr_m
template<class PBase > Vektor<double,3> HashPairBuilderPeriodicParallel< PBase >::hr_m private
Definition at line 223 of file HashPairBuilderPeriodicParallel.h.
Referenced by HashPairBuilderPeriodicParallel< PBase >::for_each(), and HashPairBuilderPeriodicParallel< PBase >::HashPairBuilderPeriodicParallel().
particles
template<class PBase > PBase & HashPairBuilderPeriodicParallel< PBase >::particles private
Definition at line 218 of file HashPairBuilderPeriodicParallel.h.
Referenced by HashPairBuilderPeriodicParallel< PBase >::for_each(), and HashPairBuilderPeriodicParallel< PBase >::get_bucket_id().
rmax_m
template<class PBase > Vektor< double, 3 > HashPairBuilderPeriodicParallel< PBase >::rmax_m private
Definition at line 222 of file HashPairBuilderPeriodicParallel.h.
Referenced by HashPairBuilderPeriodicParallel< PBase >::for_each().
rmin_m
template<class PBase > Vektor< double, 3 > HashPairBuilderPeriodicParallel< PBase >::rmin_m private
Definition at line 221 of file HashPairBuilderPeriodicParallel.h.
Referenced by HashPairBuilderPeriodicParallel< PBase >::for_each(), and HashPairBuilderPeriodicParallel< PBase >::get_bucket_id().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/PairBuilder/HashPairBuilderPeriodicParallel.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/PairBuilder/HashPairBuilderPeriodicParallel_globCHaining.h