OPAL (Object Oriented Parallel Accelerator Library): FlaggedElmPtr Class Reference
FlaggedElmPtr Class Reference
A section of a beam line.
#include <FlaggedElmPtr.h>
Public Member Functions
FlaggedElmPtr (const ElmPtr &, bool reflected=false, bool selected=false)
Constructor.
FlaggedElmPtr (const FlaggedElmPtr &)
Copy constructor.
FlaggedElmPtr ()
virtual ~FlaggedElmPtr ()
virtual void accept (BeamlineVisitor &) const
Apply visitor.
int getCounter () const
Get clone counter.
bool getReflectionFlag () const
Get reflection flag.
bool getSelectionFlag () const
Get selection flag.
void setCounter (int) const
Set clone counter.
void setReflectionFlag (bool flag) const
Set reflection flag.
void setSelectionFlag (bool flag) const
Get selection flag.
Public Member Functions inherited from ElmPtr
ElmPtr ()
ElmPtr (const ElmPtr &)
ElmPtr (ElementBase *)
virtual ~ElmPtr ()
ElementBase * getElement () const
Get the element pointer.
void setElement (ElementBase *)
Set the element pointer.
Protected Attributes
int itsCounter
Clone counter.
bool isReflected
The reflection flag.
bool isSelected
The selection flag.
Protected Attributes inherited from ElmPtr
Pointer< ElementBase > itsElement
Detailed Description
A section of a beam line.
Definition at line 36 of file FlaggedElmPtr.h.
Constructor & Destructor Documentation
FlaggedElmPtr() [1/3]
FlaggedElmPtr::FlaggedElmPtr (const ElmPtr & elem, bool reflected = false, bool selected = false) explicit
Constructor.
Definition at line 30 of file FlaggedElmPtr.cpp.
FlaggedElmPtr() [2/3]
FlaggedElmPtr::FlaggedElmPtr (const FlaggedElmPtr & rhs)
Copy constructor.
Definition at line 46 of file FlaggedElmPtr.cpp.
FlaggedElmPtr() [3/3]
FlaggedElmPtr::FlaggedElmPtr ()
Definition at line 38 of file FlaggedElmPtr.cpp.
~FlaggedElmPtr()
FlaggedElmPtr::~FlaggedElmPtr () virtual
Definition at line 54 of file FlaggedElmPtr.cpp.
Member Function Documentation
accept()
void FlaggedElmPtr::accept (BeamlineVisitor & v) const virtual
Apply visitor.
Reimplemented from ElmPtr.
Definition at line 58 of file FlaggedElmPtr.cpp.
References BeamlineVisitor::visitFlaggedElmPtr().
getCounter()
int FlaggedElmPtr::getCounter () const inline
Get clone counter.
Definition at line 96 of file FlaggedElmPtr.h.
References itsCounter.
Referenced by PlaceRep::enter(), and PlaceRep::leave().
getReflectionFlag()
bool FlaggedElmPtr::getReflectionFlag () const inline
Get reflection flag.
Definition at line 101 of file FlaggedElmPtr.h.
References isReflected.
Referenced by Sequence::print(), and DefaultVisitor::visitFlaggedElmPtr().
getSelectionFlag()
bool FlaggedElmPtr::getSelectionFlag () const inline
Get selection flag.
Definition at line 106 of file FlaggedElmPtr.h.
References isSelected.
setCounter()
void FlaggedElmPtr::setCounter (int count) const inline
Set clone counter.
Definition at line 111 of file FlaggedElmPtr.h.
References itsCounter.
setReflectionFlag()
void FlaggedElmPtr::setReflectionFlag (bool flag) const inline
Set reflection flag.
Definition at line 116 of file FlaggedElmPtr.h.
References isReflected.
Referenced by Line::parseList(), and SequenceParser::parseMember().
setSelectionFlag()
void FlaggedElmPtr::setSelectionFlag (bool flag) const inline
Get selection flag.
Definition at line 121 of file FlaggedElmPtr.h.
References isSelected.
Referenced by Selector::handleElement(), and Flagger::visitFlaggedElmPtr().
Member Data Documentation
isReflected
bool FlaggedElmPtr::isReflected mutable protected
The reflection flag.
Definition at line 87 of file FlaggedElmPtr.h.
Referenced by getReflectionFlag(), and setReflectionFlag().
isSelected
bool FlaggedElmPtr::isSelected mutable protected
The selection flag.
Definition at line 92 of file FlaggedElmPtr.h.
Referenced by getSelectionFlag(), and setSelectionFlag().
itsCounter
int FlaggedElmPtr::itsCounter mutable protected
Clone counter.
Definition at line 82 of file FlaggedElmPtr.h.
Referenced by getCounter(), and setCounter().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Beamlines/FlaggedElmPtr.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Beamlines/FlaggedElmPtr.cpp