OPAL (Object Oriented Parallel Accelerator Library): mslang::Mask Struct Reference
mslang::Mask Struct Reference
#include <Mask.h>
Classes
struct IntPoint
Public Member Functions
virtual void print (int ident)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Public Member Functions inherited from mslang::Function
virtual ~Function ()
virtual void apply (std::vector< std::shared_ptr< Base >> &bfuncs)=0
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
Static Public Member Functions inherited from mslang::Function
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
std::vector< Rectangle > pixels_m
Private Types
typedef std::pair< IntPoint, IntPoint > IntPixel_t
Private Member Functions
std::vector< IntPixel_t > minimizeNumberOfRectangles (std::vector< bool > pixels, unsigned int height, unsigned int width)
std::pair< IntPoint, IntPoint > findMaximalRectangle (const std::vector< bool > &pixels, unsigned int height, unsigned int width) const
unsigned int computeArea (const IntPoint &ll, const IntPoint &ur) const
void updateCache (const std::vector< bool > &pixels, std::vector< unsigned int > &cache, unsigned int y) const
Additional Inherited Members
Static Public Attributes inherited from mslang::Function
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\((.*)"
Detailed Description
Definition at line 8 of file Mask.h.
Member Typedef Documentation
IntPixel_t
typedef std::pair<IntPoint, IntPoint> mslang::Mask::IntPixel_t private
Definition at line 27 of file Mask.h.
Member Function Documentation
apply()
void mslang::Mask::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Definition at line 190 of file Mask.cpp.
References pixels_m.
computeArea()
unsigned int mslang::Mask::computeArea (const IntPoint & ll, const IntPoint & ur) const private
Definition at line 22 of file Mask.cpp.
References mslang::Mask::IntPoint::x_m, and mslang::Mask::IntPoint::y_m.
Referenced by minimizeNumberOfRectangles().
findMaximalRectangle()
std::pair< Mask::IntPoint, Mask::IntPoint > mslang::Mask::findMaximalRectangle (const std::vector< bool > & pixels, unsigned int height, unsigned int width) const private
Definition at line 29 of file Mask.cpp.
References updateCache(), mslang::Mask::IntPoint::x_m, and mslang::Mask::IntPoint::y_m.
Referenced by minimizeNumberOfRectangles().
minimizeNumberOfRectangles()
std::vector< Mask::IntPixel_t > mslang::Mask::minimizeNumberOfRectangles (std::vector< bool > pixels, unsigned int height, unsigned int width) private
Definition at line 81 of file Mask.cpp.
References computeArea(), and findMaximalRectangle().
Referenced by parse_detail().
parse_detail()
bool mslang::Mask::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 120 of file Mask.cpp.
References Physics::e, end(), endl(), ERRORMSG, mslang::ArgumentExtractor::get(), PortableBitmapReader::getHeight(), mslang::ArgumentExtractor::getLengthConsumed(), PortableBitmapReader::getPixels(), PortableBitmapReader::getWidth(), mslang::Rectangle::height_m, minimizeNumberOfRectangles(), mslang::parseMathExpression(), pixels_m, mslang::Base::trafo_m, mslang::Rectangle::width_m, mslang::Mask::IntPoint::x_m, and mslang::Mask::IntPoint::y_m.
Referenced by mslang::Function::parse().
print()
void mslang::Mask::print (int ident) virtual
Implements mslang::Function.
Definition at line 186 of file Mask.cpp.
References pixels_m.
updateCache()
void mslang::Mask::updateCache (const std::vector< bool > & pixels, std::vector< unsigned int > & cache, unsigned int y) const private
Definition at line 10 of file Mask.cpp.
Referenced by findMaximalRectangle().
Member Data Documentation
pixels_m
std::vector<Rectangle> mslang::Mask::pixels_m
Definition at line 13 of file Mask.h.
Referenced by apply(), parse_detail(), and print().
The documentation for this struct was generated from the following files:
src/Classic/Utilities/MSLang/Mask.h
src/Classic/Utilities/MSLang/Mask.cpp