OPAL (Object Oriented Parallel Accelerator Library): FileFieldDataSource< T, Dim, M, C > Class Template Reference
FileFieldDataSource< T, Dim, M, C > Class Template Reference
#include <FileFieldDataSource.h>
Public Member Functions
FileFieldDataSource (const char *, DataConnect *, int, Field< T, Dim, M, C > &)
virtual ~FileFieldDataSource ()
virtual bool update ()
virtual void interact (const char *=0)
Public Member Functions inherited from DataSourceObject
DataSourceObject (const char *nm, DataSource *ds, DataConnect *dc, int tm)
DataSourceObject ()
virtual ~DataSourceObject ()
bool connected () const
DataConnect * getConnection ()
DataSource * getSource ()
Public Member Functions inherited from NamedObj
NamedObj (const char *nm=0)
virtual ~NamedObj ()
const char * name () const
const char * setName (const char *nm=0)
Private Attributes
DiscField< Dim > * DF
Field< T, Dim, M, C > & myField
int FieldID
int counter
Additional Inherited Members
Protected Attributes inherited from DataSourceObject
DataConnect * Connection
DataSource * Source
int TransferMethod
Detailed Description
template<class T, unsigned Dim, class M, class C>
class FileFieldDataSource< T, Dim, M, C >
Definition at line 31 of file FileFieldDataSource.h.
Constructor & Destructor Documentation
FileFieldDataSource()
template<class T , unsigned Dim, class M , class C > FileFieldDataSource< T, Dim, M, C >::FileFieldDataSource (const char * nm, DataConnect * dc, int tm, Field< T, Dim, M, C > & F)
Definition at line 38 of file FileFieldDataSource.hpp.
References DataConnect::begin(), DataSourceObject::Connection, FileFieldDataSource< T, Dim, M, C >::DF, DataConnect::DSID(), endl(), ERRORMSG, FileFieldDataSource< T, Dim, M, C >::FieldID, FileDataConnect::getNumObjects(), FileDataConnect::getTypeString(), DataSource::INPUT, NamedObj::name(), DataSource::OUTPUT, DataConnect::size(), and DataSourceObject::TransferMethod.
~FileFieldDataSource()
template<class T , unsigned Dim, class M , class C > FileFieldDataSource< T, Dim, M, C >::~FileFieldDataSource () virtual
Definition at line 84 of file FileFieldDataSource.hpp.
Member Function Documentation
interact()
template<class T , unsigned Dim, class M , class C > void FileFieldDataSource< T, Dim, M, C >::interact (const char * = 0) virtual
Reimplemented from DataSourceObject.
Definition at line 115 of file FileFieldDataSource.hpp.
update()
template<class T , unsigned Dim, class M , class C > bool FileFieldDataSource< T, Dim, M, C >::update () virtual
Reimplemented from DataSourceObject.
Definition at line 97 of file FileFieldDataSource.hpp.
References DataSource::INPUT, and DataSource::OUTPUT.
Member Data Documentation
counter
template<class T, unsigned Dim, class M, class C> int FileFieldDataSource< T, Dim, M, C >::counter private
Definition at line 66 of file FileFieldDataSource.h.
DF
template<class T, unsigned Dim, class M, class C> DiscField<Dim>* FileFieldDataSource< T, Dim, M, C >::DF private
Definition at line 57 of file FileFieldDataSource.h.
Referenced by FileFieldDataSource< T, Dim, M, C >::FileFieldDataSource().
FieldID
template<class T, unsigned Dim, class M, class C> int FileFieldDataSource< T, Dim, M, C >::FieldID private
Definition at line 63 of file FileFieldDataSource.h.
Referenced by FileFieldDataSource< T, Dim, M, C >::FileFieldDataSource().
myField
template<class T, unsigned Dim, class M, class C> Field<T,Dim,M,C>& FileFieldDataSource< T, Dim, M, C >::myField private
Definition at line 60 of file FileFieldDataSource.h.
The documentation for this class was generated from the following files:
ippl/src/DataSource/FileFieldDataSource.h
ippl/src/DataSource/FileFieldDataSource.hpp