OPAL (Object Oriented Parallel Accelerator Library): ippl/src/Utility/Inform.h File Reference
Inform.h File Reference
#include <iostream>
#include <iomanip>
#include <sstream>
#include <string>
Classes
class Inform
Macros
#define INFORM_ALL_NODES (-1)
Functions
Inform & endl (Inform &)
Inform & level1 (Inform &)
Inform & level2 (Inform &)
Inform & level3 (Inform &)
Inform & level4 (Inform &)
Inform & level5 (Inform &)
template<class T >
Inform & operator<< (Inform &o, const T &val)
Inform & operator<< (Inform &o, Inform &(*d)(Inform &))
Inform & operator<< (Inform &o, const void *val)
Inform & operator<< (Inform &o, const long long &val)
Inform & operator<< (Inform &out, const std::string &s)
Macro Definition Documentation
INFORM_ALL_NODES
#define INFORM_ALL_NODES (-1)
Definition at line 39 of file Inform.h.
Referenced by IpplInfo::abort(), IpplInfo::abortAllNodes(), Ring::apply(), Cyclotron::apply(), ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), assign(), ParallelCyclotronTracker::bgf_main_collision_test(), CalcIndexedReceive(), LField< T, Dim >::CanCompressBasedOnPhysicalCells(), Communicate::clear_ok_messages(), LField< T, Dim >::Compress(), MGPoissonSolver::computePotential(), PartBunchBase< double, 3 >::destroyT(), Stripper::doCheck(), BeamStrippingPhysics::doPhysics(), epap(), IndexedLocalAssign(), IndexedReceive(), IndexedSend(), IpplInfo::instantiateGlobals(), IpplInfo::IpplInfo(), main(), pap(), DiscParticle::printDebug(), DiscField< Dim >::printDebug(), Communicate::process_resend_requests(), LField< T, Dim >::ReallyUncompress(), Communicate::remove_single_ok_message(), Communicate::request_retransmission(), Communicate::send_ok_message(), FieldLayout< Dim >::setup(), spap(), ParticleSpatialLayout< T, Dim, Mesh >::swap_particles(), BeamStrippingPhysics::transformToH3plus(), BeamStrippingPhysics::transformToHminus(), BeamStrippingPhysics::transformToHydrogen(), BeamStrippingPhysics::transformToProton(), LField< T, Dim >::TryCompress(), TryCompressLHS(), Communicate::unpack_retransmission_request(), and IpplInfo::~IpplInfo().
Function Documentation
endl()
Inform& endl (Inform &)
Definition at line 42 of file Inform.cpp.
References Inform::outputMessage().
Referenced by IpplInfo::abort(), IpplInfo::abortAllNodes(), Expressions::AbsMax(), DiscConfig::add_SMP_directory(), Communicate::add_to_send_cache(), ThickTracker::advanceDispersion_m(), FTps< double, 2 *3 >::allocate(), AmrMultiGrid::AmrMultiGrid(), Ring::appendElement(), TSV_MetaCross< Vektor< T1, D >, Vektor< T2, D > >::apply(), CSRIGFWakeFunction::apply(), CSRWakeFunction::apply(), Undulator::apply(), SDDS::include::complainUnsupported< A >::apply(), SDDS::array::complainUnsupported< A >::apply(), SDDS::associate::complainUnsupported< A >::apply(), GreenWakeFunction::apply(), SDDS::data::complainUnsupported< A >::apply(), SDDS::column::complainUnsupported< A >::apply(), SDDS::parameter::complainUnsupported< A >::apply(), Ring::apply(), Cyclotron::apply(), ParallelPeriodicFace< T, D, M, C >::apply(), ParallelInterpolationFace< T, D, M, C >::apply(), ParallelCyclotronTracker::applyPluginElements(), assign(), BCondBase< T, D, M, C >::BCondBase(), ParallelCyclotronTracker::bgf_main_collision_test(), BinaryRepartition(), PartBunchBase< double, 3 >::boundp(), ParallelCyclotronTracker::bunchDumpPhaseSpaceData(), ParallelCyclotronTracker::bunchMode_m(), PartBunchBase< double, 3 >::calcGammas(), PartBunchBase< double, 3 >::calcGammas_cycl(), CalcIndexedReceive(), PartBunchBase< double, 3 >::calcMeanPhi(), CalcParallelPeriodicDomain(), CSRWakeFunction::calcPsi(), CSRIGFWakeFunction::calcPsi(), coordinatetransform::CoordinateTransform::calcReferenceTrajectory(), Bend2D::calculateRefTrajectory(), FFTPACK< T >::callFFT(), LField< T, Dim >::CanCompress(), LField< T, Dim >::CanCompressBasedOnPhysicalCells(), Statistics< T >::changeStatisticBy(), SubBareField< T, Dim, S >::checkAddBrackets(), Individual::checkConstraints(), Fieldmap::checkMap(), ParallelCyclotronTracker::checkNumPart(), FTps< double, 2 *3 >::checkOrders(), Vacuum::checkPressure(), Distribution::chooseInputMomentumUnits(), OpalSimulation::cleanUp(), Communicate::clear_ok_messages(), OpalSimulation::collectResults(), ComponentFunctionFace< T, D, M, C >::ComponentFunctionFace(), ComponentFunctionFaceBCApply(), ComponentLinearExtrapolateFace< T, D, M, C >::ComponentLinearExtrapolateFace(), LField< T, Dim >::Compress(), ArbitraryDomain::compute(), P3MPoissonSolver::compute_temperature(), ScatteringPhysics::computeEnergyLoss(), ParallelTTracker::computeExternalFields(), Population< Individual_t >::computeHypervolume(), BoundaryGeometry::computeMeshVoxelization(), ParallelTTracker::computeParticleMatterInteraction(), MGPoissonSolver::computePotential(), PartBunch::computeSelfFields(), PartBunch::computeSelfFields_cycl(), ParallelTTracker::computeWakefield(), DataSource::connect(), OpalSimulation::copyH5_m(), DataConnectCreator::create(), Distribution::create(), DiscField< Dim >::create_files(), Distribution::createMatchedGaussDistribution(), OpalSimulation::createSymlink_m(), OpalData::define(), ParallelCyclotronTracker::deleteParticle(), DiscConfig::DiscConfig(), DiscMeta::DiscMeta(), Inform::display_single_line(), FTps< double, 2 *3 >::divide(), ParallelTTracker::doBinaryRepartition(), Stripper::doCheck(), Stripper::doFinalise(), CCollimator::doFinalise(), Probe::doGoOffline(), Septum::doInitialise(), BeamStrippingPhysics::doPhysics(), Distribution::doRestartOpalCycl(), Distribution::doRestartOpalT(), ThickTracker::dump_m(), ParallelCyclotronTracker::dumpAzimuthAngles_m(), FieldWriter::dumpField(), Statistics< T >::dumpStatistics(), ParallelTTracker::dumpStats(), ParallelCyclotronTracker::dumpThetaEachTurn_m(), Distribution::emitParticles(), AmrBoxLib::ErrorEst(), SIndexExpLoop< OP, Dim >::evaluate(), OptimizeCmd::execute(), Call::execute(), Echo::execute(), Help::execute(), PSystem::execute(), System::execute(), Value::execute(), Option::execute(), SampleCmd::execute(), TrackRun::execute(), OrbitThreader::execute(), OpalParser::execute(), ParallelCyclotronTracker::execute(), ParallelTTracker::execute(), ThickTracker::execute(), ExpMap(), ExtrapolateAndZeroFaceBCApply(), ExtrapolateFaceBCApply(), BoundaryGeometry::fastIsInside(), FieldDebugWriteb(), FieldLayout< Dim >::FieldLayout(), FileFieldDataSource< T, Dim, M, C >::FileFieldDataSource(), FileIpplParticleBaseDataSource< T >::FileIpplParticleBaseDataSource(), FileParticleAttribDataSource< T >::FileParticleAttribDataSource(), GenerateOpalSimulation::fillDictionary(), FlexibleCollimator::finalise(), Degrader::finalise(), Vacuum::finalise(), Cyclotron::finalise(), ParallelCyclotronTracker::finalizeTracking_m(), IpplInfo::find_smp_nodes(), BoundaryGeometry::findInsidePoint(), ClosedOrbitFinder< Value_type, Size_type, Stepper >::findOrbit(), ClosedOrbitFinder< Value_type, Size_type, Stepper >::findOrbitOfEnergy_m(), FM2DDynamic::FM2DDynamic(), FM2DElectroStatic::FM2DElectroStatic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), FMDummy::FMDummy(), HashPairBuilder< PBase >::for_each(), HashPairBuilderPeriodic< PBase >::for_each(), HashPairBuilderPeriodicParallel< PBase >::for_each(), Astra1DElectroStatic::freeMap(), Astra1DMagnetoStatic::freeMap(), FM2DElectroStatic::freeMap(), FM2DMagnetoStatic::freeMap(), FM3DMagnetoStatic::freeMap(), FM3DMagnetoStaticExtended::freeMap(), Astra1D_fast::freeMap(), Astra1DDynamic::freeMap(), FM1DProfile2::freeMap(), FM3DDynamic::freeMap(), FM1DElectroStatic::freeMap(), FM1DElectroStatic_fast::freeMap(), FM1DMagnetoStatic::freeMap(), FM1DMagnetoStatic_fast::freeMap(), FM2DDynamic::freeMap(), FM1DDynamic::freeMap(), FM1DDynamic_fast::freeMap(), FM3DH5Block::freeMap(), FM3DH5Block_nonscale::freeMap(), FM3DMagnetoStaticH5Block::freeMap(), FunctionFaceBCApply(), IntSUDSImpl< Dim >::gather(), IntCICImpl< Dim >::gather(), IntTSCImpl< Dim >::gather(), IntCICImpl< 2U >::gather(), IntCICImpl< 3U >::gather(), Distribution::generateGaussZ(), SectorMagneticFieldMap::IO::generateGrid(), ParallelCyclotronTracker::GenericTracker(), EurekaAssign< T >::get(), PutSingleItem< T, false, false >::get_iter(), CmdArguments::getArg(), TravelingWave::getAutoPhaseEstimate(), RFCavity::getAutoPhaseEstimate(), RFCavity::getAutoPhaseEstimateFallback(), UniformCartesian< Dim, MFLOAT >::getCellPosition(), Cartesian< Dim, MFLOAT >::getCellPosition(), Cartesian< Dim, MFLOAT >::getCellRangeVolume(), UniformCartesian< Dim, MFLOAT >::getCellVolume(), Cartesian< Dim, MFLOAT >::getCellVolume(), FTps< double, 2 *3 >::getCoefficient(), OpalSimulation::getData(), Cartesian< Dim, MFLOAT >::getDeltaCell(), Cartesian< Dim, MFLOAT >::getDeltaVertex(), interpolation::PPSolveFactory::getDerivs(), Cyclotron::getFieldFromFile_AVFEQ(), Cyclotron::getFieldFromFile_BandRF(), Cyclotron::getFieldFromFile_Carbon(), Cyclotron::getFieldFromFile_CYCIAE(), Cyclotron::getFieldFromFile_FFA(), Cyclotron::getFieldFromFile_Ring(), Cyclotron::getFieldFromFile_Synchrocyclotron(), Interpolator::getFieldIter(), Astra1DDynamic::getInfo(), Astra1DElectroStatic::getInfo(), Astra1DElectroStatic_fast::getInfo(), Astra1DMagnetoStatic::getInfo(), Astra1DMagnetoStatic_fast::getInfo(), FM1DProfile2::getInfo(), FM2DElectroStatic::getInfo(), FM2DMagnetoStatic::getInfo(), FM3DDynamic::getInfo(), FM3DMagnetoStatic::getInfo(), FM3DMagnetoStaticExtended::getInfo(), FM2DDynamic::getInfo(), FM1DDynamic::getInfo(), FM1DDynamic_fast::getInfo(), FM1DElectroStatic::getInfo(), FM1DElectroStatic_fast::getInfo(), FM1DMagnetoStatic::getInfo(), FM1DMagnetoStatic_fast::getInfo(), Astra1DDynamic_fast::getInfo(), FM1DProfile1::getInfo(), FM3DH5BlockBase::getInfo(), SectorMagneticFieldMap::getInfo(), SectorMagneticFieldMap::IO::getInterpolatorPolyPatch(), RFCavity::getMomentaKick(), Message::getmsg(), Cartesian< Dim, MFLOAT >::getNearestVertex(), Bend2D::getOutline(), CavityAutophaser::getPhaseAtMaxEnergy(), Vacuum::getPressureFromFile(), PartBunchBase< double, 3 >::getPTypeString(), BareField< T1, D >::getsingle(), FTps< double, 2 *3 >::getSubstOrders(), ParallelCyclotronTracker::getTunes(), Cartesian< Dim, MFLOAT >::getVertexBelow(), UniformCartesian< Dim, MFLOAT >::getVertexPosition(), Cartesian< Dim, MFLOAT >::getVertexPosition(), Cartesian< Dim, MFLOAT >::getVertRangeVolume(), Degrader::goOffline(), GreenWakeFunction::GreenWakeFunction(), OpalSimulation::hasResultsAvailable(), IndexedLocalAssign(), IndexedReceive(), IndexedSend(), Individual::Individual(), Inform::Inform(), ParallelCyclotronTracker::initDistInGlobalFrame(), AmrBoxLib::initFineLevels(), Bend2D::initialise(), RFCavity::initialise(), BoundaryGeometry::initialize(), FieldLayout< Dim >::initialize(), ParallelCyclotronTracker::initializeTracking_m(), OpalFilter::initOpalFilter(), OpalTrimCoil::initOpalTrimCoil(), ParticleMatterInteraction::initParticleMatterInteractionHandler(), AmrMultiGrid::initResidual_m(), FieldSolver::initSolver(), ParallelCyclotronTracker::initTrackOrbitFile(), OpalWake::initWakefunction(), Distribution::injectBeam(), MultiBunchHandler::injectBunch(), ParallelCyclotronTracker::injectBunch(), OrbitThreader::integrate(), Fieldmap::interpretWarning(), BoundaryGeometry::intersectLineSegmentBoundary(), BoundaryGeometry::intersectRayBoundary(), BoundaryGeometry::intersectTinyLineSegmentBoundary(), FVps< T, N >::inverse(), FTps< double, 2 *3 >::inverse(), MapAnalyser::invertMatrix_m(), IpplInfo::IpplInfo(), SDDS::data::isASCII(), Bend2D::isFieldZero(), BareField< T1, D >::localElement(), Ring::lockRing(), TUNE_class::lombAnalysis(), Fieldmap::lowResolutionWarning(), ludcmp(), main(), SigmaGenerator::match(), Expressions::Maxa(), Expressions::Mina(), ParallelCyclotronTracker::MtsTracker(), MultiBunchHandler::MultiBunchHandler(), FTps< double, 2 *3 >::multiplyVariable(), FVps< T, N >::myInverse(), CommMPI::myreceive(), BareField< T1, D >::notifyUserOfDelete(), Sampler::onMessage(), SampleWorker< Sim_t >::onMessage(), Worker< Sim_t >::onMessage(), SamplePilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >::onMessage(), Pilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >::onMessage(), OpalSimulation::OpalSimulation(), DiscField< Dim >::open_df_file(), DiscField< Dim >::open_df_file_fd(), DiscParticle::open_file(), ParallelCyclotronTracker::openFiles(), RadialPeak::operator()(), client::error_handler< Iterator >::operator()(), ProbeVariable::operator()(), SDDS::error_handler< Iterator >::operator()(), SeptumExpr::operator()(), NumberOfPeaks::operator()(), SDDSVariable::operator()(), SumErrSqRadialPeak::operator()(), MaxNormRadialPeak::operator()(), SumErrSq::operator()(), client::code_gen::StackEvaluator::operator()(), GreenWakeFunction::Wake::operator()(), SDDS::operator<<(), operator<<(), FieldSpec< T, Dim, M, C >::operator=(), ParticleInteractAttrib< T >::operator=(), ParticleAttribElem< T, Dim >::operator=(), ParticleAttrib< ParticleOrigin >::operator=(), OrbitThreader::OrbitThreader(), IpplInfo::param_error(), mslang::parse(), Expression::parse(), DiscConfig::parse_config(), DiscField< Dim >::parse_config(), mslang::Mask::parse_detail(), mslang::Polygon::parse_detail(), mslang::Rotation::parse_detail(), mslang::Shear::parse_detail(), mslang::Translation::parse_detail(), mslang::Repeat::parse_detail(), mslang::Rectangle::parse_detail(), mslang::Ellipse::parse_detail(), ManyMasterSplit< TopoDiscoveryStrategy >::parseArguments(), Pilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >::parseInputFile(), PartBinsCyc::PartBinsCyc(), BoundaryGeometry::partInside(), Communicate::perform_resend(), PeriodicFaceBCApply(), ParallelTTracker::prepareEmission(), mslang::Rotation::print(), mslang::Shear::print(), mslang::Union::print(), mslang::Translation::print(), mslang::Repeat::print(), PortableBitmapReader::print(), PortableGraymapReader::print(), mslang::Triangle::print(), mslang::Rectangle::print(), mslang::Ellipse::print(), IpplMessageCounterRegion::print(), FieldPrint< T, Dim >::print(), mslang::BoundingBox::print(), FieldDebugPrint< T, Dim >::print(), StringConstant::print(), BoolConstant::print(), RealVector::print(), RealVariable::print(), RealConstant::print(), Format::print(), CCollimator::print(), OpalWake::print(), ListElem::print(), StepSizeConfig::print(), IpplStats::print(), IndexMap::print(), OpalFilter::print(), ParticleMatterInteraction::print(), OpalTrimCoil::print(), Line::print(), FlexibleCollimator::print(), FFTBoxPoissonSolver::print(), PolynomialTimeDependence::print(), FFTPoissonSolver::print(), ScatteringPhysics::print(), P3MPoissonSolver::print(), MLPoissonSolver::print(), Sequence::print(), FMGPoissonSolver::print(), SampleIndividual::print(), OpalElement::print(), Beam::print(), SplineTimeDependence::print(), DumpFields::print(), Object::print(), DumpEMFields::print(), PartBins::print(), MGPoissonSolver::print(), Timing::print(), Attribute::print(), Statement::print(), Bend2D::print(), SectorMagneticFieldMap::print(), Cartesian< Dim, MFLOAT >::print(), AmrMultiGrid::print(), ElementBase::BoundingBox::print(), PartBunchBase< double, 3 >::print(), Cell::print_Centerings(), CartesianCentering< CE, Dim, NComponents >::print_Centerings(), Vert::print_Centerings(), Edge::print_Centerings(), VariableRFCavityFringeField::printCoefficients(), DiscMeta::printDebug(), DiscConfig::printDebug(), SIndex< Dim >::printDebug(), IpplParticleBase< T >::printDebug(), DiscParticle::printDebug(), DiscField< Dim >::printDebug(), Distribution::printDist(), Distribution::printDistBinomial(), Distribution::printDistFlattop(), Distribution::printDistFromFile(), Distribution::printDistGauss(), Distribution::printDistMatchedGauss(), Distribution::printDistMultiGauss(), FieldDebugPrint< T, Dim >::printelem(), Distribution::printEmissionModel(), Distribution::printEmissionModelAstra(), Distribution::printEmissionModelNone(), Distribution::printEmissionModelNonEquil(), Distribution::printEnergyBins(), OpalParser::printHelp(), Object::printHelp(), LaserProfile::printInfo(), BoundaryGeometry::printInfo(), FieldSolver::printInfo(), Distribution::printInfo(), IpplCounter::printIt(), MGPoissonSolver::printLoadBalanceStats(), OpalData::printNames(), polynomial::DifferentialOperator::printOperator(), polynomial::DifferentialOperatorTwo::printOperator(), printVector(), IpplInfo::printVersion(), Statement::printWhere(), Communicate::process_resend_requests(), PartBunchBase< double, 3 >::push_back(), LinearMap< T, N >::put(), Vps< T >::put(), LinearFun< T, N >::put(), TransportFun< T, N >::put(), Tps< T >::put(), FVps< T, N >::put(), FTps< double, 2 *3 >::put(), DiscField< Dim >::read(), DiscParticle::read(), Cyclotron::read(), FieldLayout< Dim >::read(), DiscParticle::read_data(), DiscField< Dim >::read_data(), DiscField< Dim >::read_layout(), DiscParticle::read_meta(), DiscField< Dim >::read_meta(), DiscField< Dim >::read_NDIndex(), DiscField< Dim >::read_offset(), MultiBunchHandler::readBunch(), Fieldmap::readHeader(), SectorMagneticFieldMap::IO::readLines(), Astra1DElectroStatic_fast::readMap(), Astra1DMagnetoStatic_fast::readMap(), Astra1DElectroStatic::readMap(), Astra1DMagnetoStatic::readMap(), FM2DElectroStatic::readMap(), FM2DMagnetoStatic::readMap(), FM3DMagnetoStatic::readMap(), FM3DMagnetoStaticExtended::readMap(), Astra1DDynamic::readMap(), FM1DProfile2::readMap(), FM3DDynamic::readMap(), FM1DMagnetoStatic::readMap(), FM1DMagnetoStatic_fast::readMap(), FM1DElectroStatic_fast::readMap(), FM2DDynamic::readMap(), FM1DElectroStatic::readMap(), FM1DDynamic::readMap(), FM1DDynamic_fast::readMap(), FM3DMagnetoStaticH5Block::readMap(), FM3DH5Block::readMap(), FM3DH5Block_nonscale::readMap(), Astra1DDynamic_fast::readMap(), FM1DProfile1::readMap(), SectorMagneticFieldMap::IO::readMap(), OpalParser::readStatement(), H5PartWrapperForPC::readStepHeader(), LField< T, Dim >::ReallyUncompress(), PartBunchBase< double, 3 >::Rebin(), reduce(), Statistics< T >::registerStatistic(), AmrBoxLib::regrid(), Communicate::remove_single_ok_message(), DiscConfig::replace_wildcards(), H5PartWrapper::reportOnError(), Communicate::request_retransmission(), PartBunchBase< double, 3 >::resetPartBinID2(), PartBunch::resizeMesh(), Util::rewindLinesSDDS(), Expressions::Rmsa(), OpalSimulation::run(), OpalParser::run(), Worker< Sim_t >::runCoWorker(), SampleWorker< Sim_t >::runSlave(), PeakFinder::save(), LossDataSink::save(), OpalBeamline::save3DInput(), OpalBeamline::save3DLattice(), LossDataSink::saveASCII(), PeakFinder::saveASCII_m(), MultiBunchHandler::saveBunch(), LaserProfile::saveData(), savgol(), IntSUDSImpl< Dim >::scatter(), IntTSCImpl< Dim >::scatter(), IntCICImpl< Dim >::scatter(), scatter(), IntCICImpl< 2U >::scatter(), IntCICImpl< 3U >::scatter(), SDDSWriter::SDDSWriter(), Select::select(), Selector::Selector(), Distribution::selectRandomGenerator(), Communicate::send(), Communicate::send_ok_message(), SamplePilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >::sendNewJobToWorker(), Pilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >::sendNewJobToWorker(), ParallelCyclotronTracker::seoMode_m(), ElementBase::setAttribute(), PartBunch::setBCAllOpen(), PartBunch::setBCAllPeriodic(), PartBunch::setBCForDCBeam(), MultiBunchHandler::setBinning(), PartBunchBase< double, 3 >::setCharge(), FTps< double, 2 *3 >::setCoefficient(), RFCavity::setComponentType(), Distribution::setDistParametersGauss(), TrackRun::setDistributionParallelT(), FTps< double, 2 *3 >::setMaxOrder(), FTps< double, 2 *3 >::setMinOrder(), MultiBunchHandler::setMode(), ClassicField::setOff(), ClassicField::setOn(), Amesos2BottomSolver< Level >::setOperator(), ParallelTTracker::setOptionalVariables(), PartBunchBase< double, 3 >::setPBins(), PartBunchBase< double, 3 >::setPType(), MultiBunchHandler::setRadiusTurns(), Distribution::setSigmaP_m(), FFTPACK< T >::setup(), Pilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >::setup(), BareField< T1, D >::setup(), FieldLayout< Dim >::setup(), TrackRun::setupCyclotronTracker(), Bend2D::setupDefaultFieldMap(), OpalSimulation::setupFSStructure(), TrackRun::setupThickTracker(), TrackRun::setupTTracker(), GreenWakeFunction::setWakeFromFile(), sfp1(), sfp2(), sfp3(), Distribution::shiftDistCoordinates(), ParallelCyclotronTracker::singleMode_m(), ParallelCyclotronTracker::singleParticleDump(), BelosBottomSolver< Level >::solve(), interpolation::PPSolveFactory::solve(), spap(), sqrt(), Pilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >::startOptimizer(), Pilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >::startPilot(), SamplePilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >::startSampler(), SamplePilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >::startWorker(), Pilot< Opt_t, Sim_t, SolPropagationGraph_t, Comm_t >::startWorker(), IpplCounter::stopCounter(), MasterNode< SolutionState_t, NeighborStrategy_t >::store(), H5PartWrapper::storeCavityInformation(), Cartesian< Dim, MFLOAT >::storeSpacingFields(), FVps< T, N >::substitute(), FTps< double, 2 *3 >::substitute(), HashPairBuilder< PBase >::sum(), ParticleCashedLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleInteractLayout< T, Dim, Mesh >::swap_ghost_particles(), ParticleSpatialLayout< T, Dim, Mesh >::swap_particles(), AmrBoxLib::tagForEfield_m(), AmrBoxLib::tagForPotentialStrength_m(), P3MPoissonSolver::test(), RFCavity::trackOnAxisParticle(), RBend3D::trackRefParticleThrough(), BeamStrippingPhysics::transformToH3plus(), BeamStrippingPhysics::transformToHminus(), BeamStrippingPhysics::transformToHydrogen(), BeamStrippingPhysics::transformToProton(), LField< T, Dim >::TryCompress(), TryCompressLHS(), Communicate::unpack_message(), Communicate::unpack_retransmission_request(), OpalSBend::update(), OpalRBend::update(), OpalPepperPot::update(), OpalRBend3D::update(), ParallelCyclotronTracker::update_m(), Cartesian< Dim, MFLOAT >::updateMeshSpacingGuards(), ParallelTTracker::updateReferenceParticle(), ParallelTTracker::updateRFElement(), Variator< ind_t, CrossoverOperator, MutationOperator >::variate(), OpalBeamline::visit(), ThickTracker::visitBeamline(), ParallelCyclotronTracker::visitCCollimator(), ParallelCyclotronTracker::visitCorrector(), ParallelCyclotronTracker::visitCyclotron(), ParallelCyclotronTracker::visitDegrader(), ParallelCyclotronTracker::visitDrift(), ParallelCyclotronTracker::visitMultipole(), ParallelCyclotronTracker::visitMultipoleT(), ParallelCyclotronTracker::visitMultipoleTCurvedConstRadius(), ParallelCyclotronTracker::visitMultipoleTCurvedVarRadius(), ParallelCyclotronTracker::visitMultipoleTStraight(), ParallelCyclotronTracker::visitProbe(), ParallelCyclotronTracker::visitRBend(), ParallelCyclotronTracker::visitRFCavity(), ParallelCyclotronTracker::visitRing(), ParallelCyclotronTracker::visitSBend(), ParallelCyclotronTracker::visitSBend3D(), ParallelCyclotronTracker::visitScalingFFAMagnet(), ParallelCyclotronTracker::visitSeptum(), ParallelCyclotronTracker::visitSolenoid(), ParallelCyclotronTracker::visitStripper(), ParallelCyclotronTracker::visitVacuum(), ParallelCyclotronTracker::visitVariableRFCavity(), ParallelCyclotronTracker::visitVariableRFCavityFringeField(), ParallelCyclotronTracker::visitVerticalFFAMagnet(), FFTBase< 1U, T >::write(), BConds< Vektor, 3, UniformCartesian, Cell >::write(), SubParticleAttrib< PA, T, Dim >::write(), DiscParticle::write(), FieldLayout< Dim >::write(), ConstantFace< T, D, M, C >::write(), DiscField< Dim >::write(), Fieldmap::write3DField(), DiscParticle::write_data(), DiscField< Dim >::write_layout(), ThickTracker::write_m(), DiscParticle::write_meta(), DiscField< Dim >::write_offset_and_data(), SDDSWriter::writeDescription(), DumpFields::writeFieldThis(), DumpEMFields::writeFieldThis(), BoundaryGeometry::writeGeomToVtk(), mslang::Triangle::writeGnuplot(), mslang::Ellipse::writeGnuplot(), mslang::Rectangle::writeGnuplot(), mslang::BoundingBox::writeGnuplot(), mslang::QuadTree::writeGnuplot(), DumpEMFields::writeHeader(), LossDataSink::writeHeaderASCII(), DataSink::writeImpactStatistics(), SDDSWriter::writeInfo(), GenerateOpalSimulation::writeInputFile(), SigmaGenerator::writeMatrix(), SigmaGenerator::writeOrbitOutput_m(), Distribution::writeOutFileEmission(), Distribution::writeOutFileHeader(), Distribution::writeOutFileInjection(), Cyclotron::writeOutputFieldFiles(), ParallelTTracker::writePhaseSpace(), SDDSColumnSet::writeRow(), AmrMultiGrid::writeSDDSHeader_m(), H5PartWrapperForPC::writeStepHeader(), H5PartWrapperForPT::writeStepHeader(), and CommMPI::~CommMPI().
level1()
Inform& level1 (Inform &)
Definition at line 45 of file Inform.cpp.
References Inform::setMessageLevel().
Referenced by PartBunchBase< double, 3 >::boundp(), ParallelTTracker::computeExternalFields(), ParallelTTracker::dumpStats(), OrbitThreader::execute(), ParallelTTracker::execute(), CavityAutophaser::getPhaseAtMaxEnergy(), Timing::print(), PartBunchBase< double, 3 >::print(), ParallelTTracker::updateReferenceParticle(), and Distribution::writeOutFileEmission().
level2()
Inform& level2 (Inform &)
Definition at line 46 of file Inform.cpp.
References Inform::setMessageLevel().
Referenced by PartBunchBase< double, 3 >::calcGammas(), ArbitraryDomain::compute(), BoundaryGeometry::computeMeshVoxelization(), ParallelTTracker::computeParticleMatterInteraction(), ParallelTTracker::computeWakefield(), Distribution::create(), ParallelTTracker::dumpStats(), AmrBoxLib::ErrorEst(), ParallelTTracker::execute(), BoundaryGeometry::findInsidePoint(), TravelingWave::getAutoPhaseEstimate(), RFCavity::getAutoPhaseEstimate(), RFCavity::getAutoPhaseEstimateFallback(), Solenoid::initialise(), RBend3D::initialise(), Bend2D::initialise(), RFCavity::initialise(), BoundaryGeometry::initialize(), ParallelTTracker::prepareEmission(), ScatteringPhysics::print(), Bend2D::print(), Bend2D::readFieldMap(), PartBunch::resizeMesh(), Util::rewindLinesSDDS(), PeakFinder::save(), LossDataSink::save(), Select::select(), ParallelTTracker::setOptionalVariables(), TrackRun::setupThickTracker(), TrackRun::setupTTracker(), AmrBoxLib::tagForEfield_m(), AmrBoxLib::tagForPotentialStrength_m(), and ParallelTTracker::writePhaseSpace().
level3()
Inform& level3 (Inform &)
Definition at line 47 of file Inform.cpp.
References Inform::setMessageLevel().
Referenced by MGPoissonSolver::computePotential(), ParallelCyclotronTracker::deleteParticle(), ParallelTTracker::dumpStats(), Distribution::emitParticles(), ClosedOrbitFinder< Value_type, Size_type, Stepper >::findOrbit(), Astra1DMagnetoStatic::freeMap(), FM2DMagnetoStatic::freeMap(), FM3DMagnetoStatic::freeMap(), FM3DMagnetoStaticExtended::freeMap(), Astra1DElectroStatic::freeMap(), Astra1D_fast::freeMap(), FM3DDynamic::freeMap(), Astra1DDynamic::freeMap(), FM1DProfile2::freeMap(), FM1DElectroStatic::freeMap(), FM1DElectroStatic_fast::freeMap(), FM1DMagnetoStatic::freeMap(), FM1DMagnetoStatic_fast::freeMap(), FM2DDynamic::freeMap(), FM1DDynamic_fast::freeMap(), FM3DH5Block::freeMap(), FM3DH5Block_nonscale::freeMap(), FM3DMagnetoStaticH5Block::freeMap(), OpalTrimCoil::initOpalTrimCoil(), FlexibleCollimator::print(), LaserProfile::printInfo(), FieldSolver::printInfo(), Astra1DMagnetoStatic_fast::readMap(), Astra1DElectroStatic_fast::readMap(), FM2DMagnetoStatic::readMap(), FM3DMagnetoStatic::readMap(), FM3DMagnetoStaticExtended::readMap(), Astra1DElectroStatic::readMap(), Astra1DMagnetoStatic::readMap(), FM3DDynamic::readMap(), Astra1DDynamic::readMap(), FM1DProfile2::readMap(), FM2DDynamic::readMap(), FM1DElectroStatic::readMap(), FM1DMagnetoStatic::readMap(), FM1DElectroStatic_fast::readMap(), FM1DMagnetoStatic_fast::readMap(), FM3DMagnetoStaticH5Block::readMap(), FM3DH5Block::readMap(), FM3DH5Block_nonscale::readMap(), Astra1DDynamic_fast::readMap(), FM1DProfile1::readMap(), PartBunch::setBCAllOpen(), PartBunch::setBCAllPeriodic(), PartBunch::setBCForDCBeam(), ClassicField::setOff(), ClassicField::setOn(), and ParallelTTracker::writePhaseSpace().
level4()
Inform& level4 (Inform &)
Definition at line 48 of file Inform.cpp.
References Inform::setMessageLevel().
Referenced by Cyclotron::apply(), ParallelCyclotronTracker::bgf_main_collision_test(), Vacuum::checkPressure(), ScatteringPhysics::computeEnergyLoss(), Stripper::doCheck(), BeamStrippingPhysics::doPhysics(), BeamStrippingPhysics::transformToH3plus(), BeamStrippingPhysics::transformToHminus(), BeamStrippingPhysics::transformToHydrogen(), and BeamStrippingPhysics::transformToProton().
level5()
Inform& level5 (Inform &)
Definition at line 49 of file Inform.cpp.
References Inform::setMessageLevel().
Referenced by main().
operator<<() [1/5]
template<class T > Inform& operator<< (Inform & o, const T & val) inline
Definition at line 175 of file Inform.h.
References Inform::getStream().
operator<<() [2/5]
Inform& operator<< (Inform & o, Inform &(*)(Inform &) d) inline
Definition at line 183 of file Inform.h.
operator<<() [3/5]
Inform& operator<< (Inform & o, const void * val) inline
Definition at line 190 of file Inform.h.
References Inform::getStream(), and Inform::setf().
operator<<() [4/5]
Inform& operator<< (Inform & o, const long long & val) inline
Definition at line 199 of file Inform.h.
References Inform::getStream().
operator<<() [5/5]
Inform& operator<< (Inform & out, const std::string & s) inline
Definition at line 205 of file Inform.h.