OPAL (Object Oriented Parallel Accelerator Library): FFTPACK_wrap< float > Class Template Reference
FFTPACK_wrap< float > Class Template Reference
#include <fftpack_FFT.h>
Static Public Member Functions
static void ccffti (size_t n, float *wsave)
static void rcffti (size_t n, float *wsave)
static void rrffti (size_t n, float *wsave)
static void ccfftf (size_t n, float *r, float *wsave)
static void ccfftb (size_t n, float *r, float *wsave)
static void rcfftf (size_t n, float *r, float *wsave)
static void rcfftb (size_t n, float *r, float *wsave)
static void rrfft (size_t n, float *r, float *wsave)
Detailed Description
template<>
class FFTPACK_wrap< float >
Definition at line 58 of file fftpack_FFT.h.
Member Function Documentation
ccfftb()
static void FFTPACK_wrap< float >::ccfftb (size_t n, float * r, float * wsave) inline static
Definition at line 69 of file fftpack_FFT.h.
References fcfftb(), and Hypervolume::n.
ccfftf()
static void FFTPACK_wrap< float >::ccfftf (size_t n, float * r, float * wsave) inline static
Definition at line 68 of file fftpack_FFT.h.
References fcfftf(), and Hypervolume::n.
ccffti()
static void FFTPACK_wrap< float >::ccffti (size_t n, float * wsave) inline static
Definition at line 64 of file fftpack_FFT.h.
References fcffti(), and Hypervolume::n.
rcfftb()
static void FFTPACK_wrap< float >::rcfftb (size_t n, float * r, float * wsave) inline static
Definition at line 72 of file fftpack_FFT.h.
References frfftb(), and Hypervolume::n.
rcfftf()
static void FFTPACK_wrap< float >::rcfftf (size_t n, float * r, float * wsave) inline static
Definition at line 71 of file fftpack_FFT.h.
References frfftf(), and Hypervolume::n.
rcffti()
static void FFTPACK_wrap< float >::rcffti (size_t n, float * wsave) inline static
Definition at line 65 of file fftpack_FFT.h.
References frffti(), and Hypervolume::n.
rrfft()
static void FFTPACK_wrap< float >::rrfft (size_t n, float * r, float * wsave) inline static
Definition at line 74 of file fftpack_FFT.h.
References fsint(), and Hypervolume::n.
rrffti()
static void FFTPACK_wrap< float >::rrffti (size_t n, float * wsave) inline static
Definition at line 66 of file fftpack_FFT.h.
References fsinti(), and Hypervolume::n.
The documentation for this class was generated from the following file:
ippl/src/FFT/fftpack_FFT.h