OPAL (Object Oriented Parallel Accelerator Library): PyOpal::Globals Namespace Reference
PyOpal::Globals Namespace Reference
Functions
void printArgv (char **argv)
void Initialise ()
Function Documentation
Initialise()
void PyOpal::Globals::Initialise ()
Globals namespace provides routines to initialise global objects:
ippl
gmsg
Definition at line 50 of file Globals.cpp.
References gmsg, gmsgALL, INFORM_ALL_NODES, IpplInfo::instantiateGlobals(), and ippl.
Referenced by PyOpal::PyOpalGlobalCartesianOffset::BOOST_PYTHON_MODULE(), PyOpal::PyOpalLocalCartesianOffset::BOOST_PYTHON_MODULE(), PyOpal::PyOpalElement::BOOST_PYTHON_MODULE(), PyOpal::PyEnge::BOOST_PYTHON_MODULE(), PyOpal::PyProbe::BOOST_PYTHON_MODULE(), PyOpal::PyOpalPolynomialTimeDependence::BOOST_PYTHON_MODULE(), PyOpal::PyAsymmetricEnge::BOOST_PYTHON_MODULE(), PyOpal::PyDistributionNS::BOOST_PYTHON_MODULE(), PyOpal::PyBeamNS::BOOST_PYTHON_MODULE(), PyOpal::PyLineNS::BOOST_PYTHON_MODULE(), PyOpal::PyVerticalFFAMagnet::BOOST_PYTHON_MODULE(), PyOpal::PyOpalSinusoidalTimeDependence::BOOST_PYTHON_MODULE(), PyOpal::PyTrackCmdNS::BOOST_PYTHON_MODULE(), PyOpal::PyOutputPlane::BOOST_PYTHON_MODULE(), PyOpal::PyTrackRunNS::BOOST_PYTHON_MODULE(), PyOpal::PyOpalSplineTimeDependence::BOOST_PYTHON_MODULE(), PyOpal::PyVariableRFCavity::BOOST_PYTHON_MODULE(), PyOpal::PyFieldSolverNS::BOOST_PYTHON_MODULE(), PyOpal::PyOptionNS::BOOST_PYTHON_MODULE(), PyOpal::PyVariableRFCavityFringeField::BOOST_PYTHON_MODULE(), PyOpal::PyMultipoleT::BOOST_PYTHON_MODULE(), PyOpal::PyParser::BOOST_PYTHON_MODULE(), PyOpal::PyScalingFFAMagnet::BOOST_PYTHON_MODULE(), PyOpal::PyRingDefinition::BOOST_PYTHON_MODULE(), PyOpal::Field::BOOST_PYTHON_MODULE(), PyInit_polynomial_coefficient(), and PyInit_polynomial_map().
printArgv()
void PyOpal::Globals::printArgv (char ** argv)
Definition at line 41 of file Globals.cpp.
References endl().