OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Classic/FixedAlgebra/FTpsMath.h File Reference
FTpsMath.h File Reference
#include "FixedAlgebra/FTps.h"
#include "Utilities/DomainError.h"
#include <complex>
#include <type_traits>
Classes
struct is_complex< T >
struct is_complex< std::complex< T > >
Functions
template<class T , int N>
FTps< T, N > pow (const FTps< T, N > &x, int y, int trunc=(FTps< T, N >::EXACT))
Tps x to the power (int y).
template<class T , int N>
FTps< T, N > sqrt (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Square root.
template<class T , int N>
FTps< T, N > sin (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Sine.
template<class T , int N>
FTps< T, N > cos (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Cosine.
template<class T , int N>
FTps< T, N > tan (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Tangent.
template<class T , int N>
FTps< T, N > cot (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Cotangent.
template<class T , int N>
FTps< T, N > sec (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Secant.
template<class T , int N>
FTps< T, N > csc (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Cosecant.
template<class T , int N>
FTps< T, N > exp (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Exponential.
template<class T , int N>
FTps< T, N > log (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Natural logarithm.
template<class T , int N>
FTps< T, N > sinh (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Hyperbolic sine.
template<class T , int N>
FTps< T, N > cosh (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Hyperbolic cosine.
template<class T , int N>
FTps< T, N > tanh (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Hyperbolic tangent.
template<class T , int N>
FTps< T, N > coth (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Hyperbolic cotangent.
template<class T , int N>
FTps< T, N > sech (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Hyperbolic secant.
template<class T , int N>
FTps< T, N > csch (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Hyperbolic cosecant.
template<class T , int N>
FTps< T, N > erf (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Error function.
template<class T , int N>
FTps< T, N > erfc (const FTps< T, N > &x, int trunc=(FTps< T, N >::EXACT))
Complementary error function.
Function Documentation
cos()
template<class T , int N> FTps< T, N > cos (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Cosine.
Definition at line 191 of file FTpsMath.h.
References FTps< T, N >::getMinOrder(), FTps< T, N >::getTruncOrder(), min(), sin(), Attrib::Legacy::Distribution::T, and FTps< T, N >::taylor().
Referenced by cot(), sec(), sin(), and tan().
cosh()
template<class T , int N> FTps< T, N > cosh (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Hyperbolic cosine.
Definition at line 324 of file FTpsMath.h.
References FTps< T, N >::getMinOrder(), FTps< T, N >::getTruncOrder(), min(), sinh(), Attrib::Legacy::Distribution::T, and FTps< T, N >::taylor().
Referenced by coth(), sech(), sinh(), and tanh().
cot()
template<class T , int N> FTps< T, N > cot (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Cotangent.
Definition at line 222 of file FTpsMath.h.
References cos(), FTps< T, N >::getMinOrder(), sin(), and Attrib::Legacy::Distribution::T.
coth()
template<class T , int N> FTps< T, N > coth (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Hyperbolic cotangent.
Definition at line 355 of file FTpsMath.h.
References cosh(), FTps< T, N >::getMinOrder(), sinh(), and Attrib::Legacy::Distribution::T.
csc()
template<class T , int N> FTps< T, N > csc (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Cosecant.
Definition at line 241 of file FTpsMath.h.
References FTps< T, N >::getMinOrder(), sin(), and Attrib::Legacy::Distribution::T.
csch()
template<class T , int N> FTps< T, N > csch (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Hyperbolic cosecant.
Definition at line 374 of file FTpsMath.h.
References FTps< T, N >::getMinOrder(), sinh(), and Attrib::Legacy::Distribution::T.
erf()
template<class T , int N> FTps< T, N > erf (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Error function.
Definition at line 385 of file FTpsMath.h.
References exp(), FTps< T, N >::getMinOrder(), FTps< T, N >::getTruncOrder(), min(), real(), sqrt(), Attrib::Legacy::Distribution::T, and FTps< T, N >::taylor().
Referenced by P3MGreensFunction< 3 >::calculate(), erfc(), Util::erfinv(), ApplyField< T >::operator()(), and matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
erfc()
template<class T , int N> FTps< T, N > erfc (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Complementary error function.
Definition at line 414 of file FTpsMath.h.
References erf(), and Attrib::Legacy::Distribution::T.
Referenced by matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
exp()
template<class T , int N> FTps< T, N > exp (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Exponential.
Definition at line 252 of file FTpsMath.h.
References FTps< T, N >::getMinOrder(), FTps< T, N >::getTruncOrder(), min(), Attrib::Legacy::Distribution::T, and FTps< T, N >::taylor().
Referenced by erf().
log()
template<class T , int N> FTps< T, N > log (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Natural logarithm.
Definition at line 274 of file FTpsMath.h.
References FTps< T, N >::getMinOrder(), FTps< T, N >::getTruncOrder(), min(), Attrib::Legacy::Distribution::T, and FTps< T, N >::taylor().
pow()
template<class T , int N> FTps< T, N > pow (const FTps< T, N > & x, int y, int trunc = (FTps<T, N>::EXACT))
Tps x to the power (int y).
Definition at line 118 of file FTpsMath.h.
References FTps< T, N >::getMinOrder(), FTps< T, N >::inverse(), FTps< T, N >::multiply(), and Attrib::Legacy::Distribution::T.
sec()
template<class T , int N> FTps< T, N > sec (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Secant.
Definition at line 233 of file FTpsMath.h.
References cos().
sech()
template<class T , int N> FTps< T, N > sech (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Hyperbolic secant.
Definition at line 366 of file FTpsMath.h.
References cosh().
sin()
template<class T , int N> FTps< T, N > sin (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Sine.
Definition at line 168 of file FTpsMath.h.
References cos(), FTps< T, N >::getMinOrder(), FTps< T, N >::getTruncOrder(), min(), Attrib::Legacy::Distribution::T, and FTps< T, N >::taylor().
Referenced by cos(), cot(), csc(), and tan().
sinh()
template<class T , int N> FTps< T, N > sinh (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Hyperbolic sine.
Definition at line 301 of file FTpsMath.h.
References cosh(), FTps< T, N >::getMinOrder(), FTps< T, N >::getTruncOrder(), min(), Attrib::Legacy::Distribution::T, and FTps< T, N >::taylor().
Referenced by cosh(), coth(), csch(), and tanh().
sqrt()
template<class T , int N> FTps< T, N > sqrt (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Square root.
Definition at line 137 of file FTpsMath.h.
References endl(), FTps< T, N >::getMinOrder(), FTps< T, N >::getTruncOrder(), imag(), min(), real(), Attrib::Legacy::Distribution::T, and FTps< T, N >::taylor().
Referenced by erf().
tan()
template<class T , int N> FTps< T, N > tan (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Tangent.
Definition at line 214 of file FTpsMath.h.
References cos(), and sin().
tanh()
template<class T , int N> FTps< T, N > tanh (const FTps< T, N > & x, int trunc = (FTps<T, N>::EXACT))
Hyperbolic tangent.
Definition at line 347 of file FTpsMath.h.
References cosh(), and sinh().