OPAL (Object Oriented Parallel Accelerator Library): Interpolator Class Reference
Interpolator Class Reference
#include <Interpolator.h>
Public Member Functions
Interpolator ()
~Interpolator ()
Static Protected Member Functions
template<class T , unsigned Dim>
static CompressedBrickIterator< T, Dim > getFieldIter (const BareField< T, Dim > &f, const NDIndex< Dim > &pt)
Detailed Description
Definition at line 176 of file Interpolator.h.
Constructor & Destructor Documentation
Interpolator()
Interpolator::Interpolator () inline
Definition at line 226 of file Interpolator.h.
~Interpolator()
Interpolator::~Interpolator () inline
Definition at line 227 of file Interpolator.h.
Member Function Documentation
getFieldIter()
template<class T , unsigned Dim> static CompressedBrickIterator<T,Dim> Interpolator::getFieldIter (const BareField< T, Dim > & f, const NDIndex< Dim > & pt) inline static protected
Definition at line 183 of file Interpolator.h.
References IpplInfo::abort(), LField< T, Dim >::begin(), begin(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), endl(), ERRORMSG, LField< T, Dim >::getAllocated(), BareField< T, Dim >::getLayout(), LField< T, Dim >::getOwned(), and IpplInfo::myNode().
Referenced by IntNGP::gather(), IntSUDSImpl< Dim >::gather(), IntCICImpl< Dim >::gather(), IntTSCImpl< Dim >::gather(), IntSUDSImpl< 1U >::gather(), IntTSCImpl< 1U >::gather(), IntCICImpl< 1U >::gather(), IntSUDSImpl< 2U >::gather(), IntTSCImpl< 2U >::gather(), IntSUDSImpl< 3U >::gather(), IntCICImpl< 2U >::gather(), IntTSCImpl< 3U >::gather(), IntCICImpl< 3U >::gather(), IntNGP::scatter(), IntSUDSImpl< Dim >::scatter(), IntCICImpl< Dim >::scatter(), IntTSCImpl< Dim >::scatter(), IntSUDSImpl< 1U >::scatter(), IntCICImpl< 1U >::scatter(), IntTSCImpl< 1U >::scatter(), IntSUDSImpl< 2U >::scatter(), IntTSCImpl< 2U >::scatter(), IntCICImpl< 2U >::scatter(), IntSUDSImpl< 3U >::scatter(), IntTSCImpl< 3U >::scatter(), and IntCICImpl< 3U >::scatter().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Particle/Interpolator.h