OPAL (Object Oriented Parallel Accelerator Library): RNGStream Class Reference
RNGStream Class Reference
#include <RNGStream.h>
Public Member Functions
std::mt19937_64 & getGenerator ()
template<class DISTR >
DISTR::result_type getNext (DISTR &RNGDist)
Static Public Member Functions
static RNGStream * getInstance ()
static RNGStream * getInstance (unsigned int seed)
static void deleteInstance (RNGStream *&generator)
static void setGlobalSeed (unsigned int seed)
static unsigned int getGlobalSeed ()
Private Member Functions
RNGStream ()
RNGStream (unsigned int seed)
~RNGStream ()
Private Attributes
std::mt19937_64 RNGenerator_m
bool isGlobal_m
Static Private Attributes
static RNGStream * globalInstance_sm = nullptr
static unsigned int globalSeed_sm = 42
static unsigned int numGlobalInstances_sm = 0
Detailed Description
Definition at line 23 of file RNGStream.h.
Constructor & Destructor Documentation
RNGStream() [1/2]
RNGStream::RNGStream () inline private
Definition at line 42 of file RNGStream.h.
Referenced by getInstance().
RNGStream() [2/2]
RNGStream::RNGStream (unsigned int seed) inline private
Definition at line 47 of file RNGStream.h.
~RNGStream()
RNGStream::~RNGStream () inline private
Definition at line 52 of file RNGStream.h.
Member Function Documentation
deleteInstance()
void RNGStream::deleteInstance (RNGStream *& generator) static
Definition at line 38 of file RNGStream.cpp.
References isGlobal_m, and numGlobalInstances_sm.
Referenced by LatinHyperCube::~LatinHyperCube(), Normal::~Normal(), and Uniform< size_t >::~Uniform().
getGenerator()
std::mt19937_64 & RNGStream::getGenerator ()
Definition at line 64 of file RNGStream.cpp.
References RNGenerator_m.
getGlobalSeed()
unsigned int RNGStream::getGlobalSeed () static
Definition at line 60 of file RNGStream.cpp.
References globalSeed_sm.
getInstance() [1/2]
RNGStream * RNGStream::getInstance () static
Definition at line 26 of file RNGStream.cpp.
References globalInstance_sm, numGlobalInstances_sm, and RNGStream().
Referenced by Normal::allocate(), Uniform< size_t >::allocate(), and LatinHyperCube::allocate().
getInstance() [2/2]
RNGStream * RNGStream::getInstance (unsigned int seed) static
Definition at line 34 of file RNGStream.cpp.
References RNGStream(), and Options::seed.
getNext()
template<class DISTR > DISTR::result_type RNGStream::getNext (DISTR & RNGDist) inline
Definition at line 37 of file RNGStream.h.
References RNGenerator_m.
Referenced by Normal::create(), Uniform< size_t >::create(), LatinHyperCube::create(), and Uniform< size_t >::getNext().
setGlobalSeed()
void RNGStream::setGlobalSeed (unsigned int seed) static
Definition at line 53 of file RNGStream.cpp.
References globalInstance_sm, globalSeed_sm, RNGenerator_m, and Options::seed.
Referenced by SampleCmd::execute().
Member Data Documentation
globalInstance_sm
RNGStream * RNGStream::globalInstance_sm = nullptr static private
Definition at line 55 of file RNGStream.h.
Referenced by getInstance(), and setGlobalSeed().
globalSeed_sm
unsigned int RNGStream::globalSeed_sm = 42 static private
Definition at line 56 of file RNGStream.h.
Referenced by getGlobalSeed(), and setGlobalSeed().
isGlobal_m
bool RNGStream::isGlobal_m private
Definition at line 59 of file RNGStream.h.
Referenced by deleteInstance().
numGlobalInstances_sm
unsigned int RNGStream::numGlobalInstances_sm = 0 static private
Definition at line 57 of file RNGStream.h.
Referenced by deleteInstance(), and getInstance().
RNGenerator_m
std::mt19937_64 RNGStream::RNGenerator_m private
Definition at line 58 of file RNGStream.h.
Referenced by getGenerator(), getNext(), and setGlobalSeed().
The documentation for this class was generated from the following files:
src/Sample/RNGStream.h
src/Sample/RNGStream.cpp