OPAL (Object Oriented Parallel Accelerator Library): SymTenzor< T, D > Class Template Reference
SymTenzor< T, D > Class Template Reference
#include <SymTenzor.h>
Classes
class DontInitialize
Public Types
enum { ElemDim = 2 }
enum { Size = D*(D+1)/2 }
typedef T Element_t
Public Member Functions
SymTenzor ()
SymTenzor (DontInitialize)
SymTenzor (const T &x00)
SymTenzor (const T &x00, const T &x10, const T &x11)
SymTenzor (const T &x00, const T &x10, const T &x11, const T &x20, const T &x21, const T &x22)
SymTenzor (const SymTenzor< T, D > &rhs)
SymTenzor (const Tenzor< T, D > &t)
~SymTenzor ()
const SymTenzor< T, D > & operator= (const SymTenzor< T, D > &rhs)
template<class T1 >
const SymTenzor< T, D > & operator= (const SymTenzor< T1, D > &rhs)
const SymTenzor< T, D > & operator= (const T &rhs)
const SymTenzor< T, D > & operator= (const Tenzor< T, D > &rhs)
template<class T1 >
SymTenzor< T, D > & operator+= (const SymTenzor< T1, D > &rhs)
SymTenzor< T, D > & operator+= (const T &rhs)
template<class T1 >
SymTenzor< T, D > & operator-= (const SymTenzor< T1, D > &rhs)
SymTenzor< T, D > & operator-= (const T &rhs)
template<class T1 >
SymTenzor< T, D > & operator*= (const SymTenzor< T1, D > &rhs)
SymTenzor< T, D > & operator*= (const T &rhs)
template<class T1 >
SymTenzor< T, D > & operator/= (const SymTenzor< T1, D > &rhs)
SymTenzor< T, D > & operator/= (const T &rhs)
void diagonal (const T &rhs)
int len (void) const
int size (void) const
int get_Size (void) const
Element_t operator() (unsigned int i, unsigned int j) const
Element_t & operator() (unsigned int i, unsigned int j)
Element_t & operator() (std::pair< int, int > a)
Element_t operator() (std::pair< int, int > a) const
Element_t HL (unsigned int hi, unsigned int lo) const
Element_t & HL (unsigned int hi, unsigned int lo)
Element_t & operator[] (unsigned int i)
Element_t operator[] (unsigned int i) const
Element_t & operator() (unsigned int i)
Element_t operator() (unsigned int i) const
bool operator== (const SymTenzor< T, D > &that) const
bool operator!= (const SymTenzor< T, D > &that) const
Message & putMessage (Message &m) const
Message & getMessage (Message &m)
Private Attributes
T X [Size]
Detailed Description
template<class T, unsigned D>
class SymTenzor< T, D >
Definition at line 37 of file SymTenzor.h.
Member Typedef Documentation
Element_t
template<class T, unsigned D> typedef T SymTenzor< T, D >::Element_t
Definition at line 41 of file SymTenzor.h.
Member Enumeration Documentation
anonymous enum
template<class T, unsigned D> anonymous enum
Enumerator
ElemDim
Definition at line 42 of file SymTenzor.h.
anonymous enum
template<class T, unsigned D> anonymous enum
Enumerator
Size
Definition at line 43 of file SymTenzor.h.
Constructor & Destructor Documentation
SymTenzor() [1/7]
template<class T, unsigned D> SymTenzor< T, D >::SymTenzor () inline
Definition at line 46 of file SymTenzor.h.
SymTenzor() [2/7]
template<class T, unsigned D> SymTenzor< T, D >::SymTenzor (DontInitialize) inline
Definition at line 52 of file SymTenzor.h.
SymTenzor() [3/7]
template<class T, unsigned D> SymTenzor< T, D >::SymTenzor (const T & x00) inline
Definition at line 55 of file SymTenzor.h.
SymTenzor() [4/7]
template<class T, unsigned D> SymTenzor< T, D >::SymTenzor (const T & x00, const T & x10, const T & x11) inline
Definition at line 60 of file SymTenzor.h.
SymTenzor() [5/7]
template<class T, unsigned D> SymTenzor< T, D >::SymTenzor (const T & x00, const T & x10, const T & x11, const T & x20, const T & x21, const T & x22) inline
Definition at line 65 of file SymTenzor.h.
SymTenzor() [6/7]
template<class T, unsigned D> SymTenzor< T, D >::SymTenzor (const SymTenzor< T, D > & rhs) inline
Definition at line 73 of file SymTenzor.h.
SymTenzor() [7/7]
template<class T, unsigned D> SymTenzor< T, D >::SymTenzor (const Tenzor< T, D > & t) inline
Definition at line 80 of file SymTenzor.h.
~SymTenzor()
template<class T, unsigned D> SymTenzor< T, D >::~SymTenzor () inline
Definition at line 89 of file SymTenzor.h.
Member Function Documentation
diagonal()
template<class T, unsigned D> void SymTenzor< T, D >::diagonal (const T & rhs) inline
Definition at line 175 of file SymTenzor.h.
get_Size()
template<class T, unsigned D> int SymTenzor< T, D >::get_Size (void) const inline
Definition at line 183 of file SymTenzor.h.
getMessage()
template<class T, unsigned D> Message& SymTenzor< T, D >::getMessage (Message & m) inline
Definition at line 267 of file SymTenzor.h.
Referenced by SymTenzor< double, 6 >::getMessage().
HL() [1/2]
template<class T, unsigned D> Element_t SymTenzor< T, D >::HL (unsigned int hi, unsigned int lo) const inline
Definition at line 215 of file SymTenzor.h.
Referenced by TSV_MetaDotDot< SymTenzor< T1, D >, SymTenzor< T2, D > >::apply(), TSV_MetaDot< SymTenzor< T1, D >, SymTenzor< T2, D > >::apply(), TSV_MetaDot< SymTenzor< T1, D >, Vektor< T2, D > >::apply(), TSV_MetaDot< SymTenzor< T1, D >, Tenzor< T2, D > >::apply(), and TSV_MetaDot< Tenzor< T1, D >, SymTenzor< T2, D > >::apply().
HL() [2/2]
template<class T, unsigned D> Element_t& SymTenzor< T, D >::HL (unsigned int hi, unsigned int lo) inline
Definition at line 220 of file SymTenzor.h.
len()
template<class T, unsigned D> int SymTenzor< T, D >::len (void) const inline
Definition at line 181 of file SymTenzor.h.
operator!=()
template<class T, unsigned D> bool SymTenzor< T, D >::operator!= (const SymTenzor< T, D > & that) const inline
Definition at line 255 of file SymTenzor.h.
operator()() [1/6]
template<class T, unsigned D> Element_t SymTenzor< T, D >::operator() (unsigned int i, unsigned int j) const inline
Definition at line 187 of file SymTenzor.h.
operator()() [2/6]
template<class T, unsigned D> Element_t& SymTenzor< T, D >::operator() (unsigned int i, unsigned int j) inline
Definition at line 193 of file SymTenzor.h.
operator()() [3/6]
template<class T, unsigned D> Element_t& SymTenzor< T, D >::operator() (std::pair< int, int > a) inline
Definition at line 199 of file SymTenzor.h.
operator()() [4/6]
template<class T, unsigned D> Element_t SymTenzor< T, D >::operator() (std::pair< int, int > a) const inline
Definition at line 207 of file SymTenzor.h.
operator()() [5/6]
template<class T, unsigned D> Element_t& SymTenzor< T, D >::operator() (unsigned int i) inline
Definition at line 239 of file SymTenzor.h.
operator()() [6/6]
template<class T, unsigned D> Element_t SymTenzor< T, D >::operator() (unsigned int i) const inline
Definition at line 244 of file SymTenzor.h.
operator*=() [1/2]
template<class T, unsigned D> template<class T1 > SymTenzor<T,D>& SymTenzor< T, D >::operator*= (const SymTenzor< T1, D > & rhs) inline
Definition at line 146 of file SymTenzor.h.
operator*=() [2/2]
template<class T, unsigned D> SymTenzor<T,D>& SymTenzor< T, D >::operator*= (const T & rhs) inline
Definition at line 152 of file SymTenzor.h.
operator+=() [1/2]
template<class T, unsigned D> template<class T1 > SymTenzor<T,D>& SymTenzor< T, D >::operator+= (const SymTenzor< T1, D > & rhs) inline
Definition at line 118 of file SymTenzor.h.
operator+=() [2/2]
template<class T, unsigned D> SymTenzor<T,D>& SymTenzor< T, D >::operator+= (const T & rhs) inline
Definition at line 124 of file SymTenzor.h.
operator-=() [1/2]
template<class T, unsigned D> template<class T1 > SymTenzor<T,D>& SymTenzor< T, D >::operator-= (const SymTenzor< T1, D > & rhs) inline
Definition at line 132 of file SymTenzor.h.
operator-=() [2/2]
template<class T, unsigned D> SymTenzor<T,D>& SymTenzor< T, D >::operator-= (const T & rhs) inline
Definition at line 138 of file SymTenzor.h.
operator/=() [1/2]
template<class T, unsigned D> template<class T1 > SymTenzor<T,D>& SymTenzor< T, D >::operator/= (const SymTenzor< T1, D > & rhs) inline
Definition at line 160 of file SymTenzor.h.
operator/=() [2/2]
template<class T, unsigned D> SymTenzor<T,D>& SymTenzor< T, D >::operator/= (const T & rhs) inline
Definition at line 166 of file SymTenzor.h.
operator=() [1/4]
template<class T, unsigned D> const SymTenzor<T,D>& SymTenzor< T, D >::operator= (const SymTenzor< T, D > & rhs) inline
Definition at line 92 of file SymTenzor.h.
operator=() [2/4]
template<class T, unsigned D> template<class T1 > const SymTenzor<T,D>& SymTenzor< T, D >::operator= (const SymTenzor< T1, D > & rhs) inline
Definition at line 98 of file SymTenzor.h.
operator=() [3/4]
template<class T, unsigned D> const SymTenzor<T,D>& SymTenzor< T, D >::operator= (const T & rhs) inline
Definition at line 103 of file SymTenzor.h.
operator=() [4/4]
template<class T, unsigned D> const SymTenzor<T,D>& SymTenzor< T, D >::operator= (const Tenzor< T, D > & rhs) inline
Definition at line 107 of file SymTenzor.h.
operator==()
template<class T, unsigned D> bool SymTenzor< T, D >::operator== (const SymTenzor< T, D > & that) const inline
Definition at line 252 of file SymTenzor.h.
operator[]() [1/2]
template<class T, unsigned D> Element_t& SymTenzor< T, D >::operator[] (unsigned int i) inline
Definition at line 226 of file SymTenzor.h.
operator[]() [2/2]
template<class T, unsigned D> Element_t SymTenzor< T, D >::operator[] (unsigned int i) const inline
Definition at line 231 of file SymTenzor.h.
putMessage()
template<class T, unsigned D> Message& SymTenzor< T, D >::putMessage (Message & m) const inline
Definition at line 261 of file SymTenzor.h.
Referenced by SymTenzor< double, 6 >::putMessage().
size()
template<class T, unsigned D> int SymTenzor< T, D >::size (void) const inline
Definition at line 182 of file SymTenzor.h.
Member Data Documentation
X
template<class T, unsigned D> T SymTenzor< T, D >::X[Size] private
Definition at line 275 of file SymTenzor.h.
Referenced by SymTenzor< double, 6 >::diagonal(), SymTenzor< double, 6 >::getMessage(), SymTenzor< double, 6 >::HL(), SymTenzor< double, 6 >::operator()(), SymTenzor< double, 6 >::operator==(), SymTenzor< double, 6 >::operator[](), SymTenzor< double, 6 >::putMessage(), and SymTenzor< double, 6 >::SymTenzor().
The documentation for this class was generated from the following file:
ippl/src/AppTypes/SymTenzor.h