OPAL (Object Oriented Parallel Accelerator Library): Table Class Reference
Table Class Reference abstract
The base class for all OPAL tables.
#include <Table.h>
Classes
struct Cell
Descriptor for printing a table cell.
Public Types
typedef std::vector< Cell > CellArray
An array of cell descriptors.
Public Member Functions
virtual ~Table ()
virtual bool canReplaceBy (Object *newObject)
Test if object can be replaced.
virtual void fill ()=0
Refill the buffer.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual double getCell (const PlaceRep &row, const std::string &col)=0
Return value in selected table cell.
virtual std::vector< double > getColumn (const RangeRep &range, const std::string &col)=0
Return column [b]col[/b] of this table, limited by [b]range[/b].
virtual CellArray getDefault () const =0
Return the default print columns.
virtual double getLength ()=0
Return the length of the table.
virtual const Beamline * getLine () const =0
Return embedded CLASSIC beamline.
virtual std::vector< double > getRow (const PlaceRep &, const std::vector< std::string > &)=0
Return a table row.
virtual void invalidate ()
Mark this table as invalid, if it is dynamic.
virtual bool isDependent (const std::string &name) const =0
Find out if table depends on the object identified by [b]name[/b].
virtual Expressions::PtrToScalar< double > makeColumnExpression (const std::string &) const =0
virtual bool matches (Table *rhs) const =0
Check that [b]rhs[/b] is of same type as [b]this[/b].
virtual void printTable (std::ostream &, const CellArray &) const =0
Print list for the table.
Public Member Functions inherited from Object
virtual ~Object ()
virtual Object * clone (const std::string &name)=0
Return a clone.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static Table * find (const std::string &name)
Find named Table.
Protected Member Functions
Table (int size, const char *name, const char *help)
Constructor for exemplars.
Table (const std::string &name, Table *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes
bool dynamic
Flag dynamic table.
bool refill
Refill flag.
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Private Member Functions
Table ()
Table (const Table &)
void operator= (const Table &)
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Detailed Description
The base class for all OPAL tables.
Definition at line 42 of file Table.h.
Member Typedef Documentation
CellArray
typedef std::vector<Cell> Table::CellArray
An array of cell descriptors.
Definition at line 63 of file Table.h.
Constructor & Destructor Documentation
~Table()
Table::~Table () virtual
Definition at line 30 of file Table.cpp.
References Object::builtin, OpalData::getInstance(), and OpalData::unregisterTable().
Table() [1/4]
Table::Table (int size, const char * name, const char * help) protected
Constructor for exemplars.
Definition at line 70 of file Table.cpp.
Table() [2/4]
Table::Table (const std::string & name, Table * parent) protected
Constructor for clones.
Definition at line 76 of file Table.cpp.
References OpalData::getInstance(), and OpalData::registerTable().
Table() [3/4]
Table::Table () private
Table() [4/4]
Table::Table (const Table &) private
Member Function Documentation
canReplaceBy()
bool Table::canReplaceBy (Object * newObject) virtual
Test if object can be replaced.
Reimplemented from Object.
Definition at line 36 of file Table.cpp.
fill()
virtual void Table::fill () pure virtual
Refill the buffer.
Referenced by Expressions::SCell::evaluate(), Expressions::AColumn::evaluate(), and Expressions::ARow::evaluate().
find()
Table * Table::find (const std::string & name) static
Find named Table.
Definition at line 41 of file Table.cpp.
References OpalData::find(), OpalData::getInstance(), and name.
Referenced by Expressions::SCell::evaluate(), Expressions::ARow::evaluate(), Expressions::AColumn::evaluate(), and List::execute().
getCategory()
const std::string Table::getCategory () const virtual
Return the object category as a string.
Implements Object.
Definition at line 50 of file Table.cpp.
getCell()
virtual double Table::getCell (const PlaceRep & row, const std::string & col) pure virtual
Return value in selected table cell.
Referenced by Expressions::SCell::evaluate().
getColumn()
virtual std::vector<double> Table::getColumn (const RangeRep & range, const std::string & col) pure virtual
Return column [b]col[/b] of this table, limited by [b]range[/b].
Referenced by Expressions::AColumn::evaluate().
getDefault()
virtual CellArray Table::getDefault () const pure virtual
Return the default print columns.
Referenced by List::list().
getLength()
virtual double Table::getLength () pure virtual
Return the length of the table.
getLine()
virtual const Beamline* Table::getLine () const pure virtual
Return embedded CLASSIC beamline.
getRow()
virtual std::vector<double> Table::getRow (const PlaceRep & , const std::vector< std::string > &) pure virtual
Return a table row.
Referenced by Expressions::ARow::evaluate().
invalidate()
void Table::invalidate () virtual
Mark this table as invalid, if it is dynamic.
Definition at line 65 of file Table.cpp.
References dynamic, and refill.
isDependent()
virtual bool Table::isDependent (const std::string & name) const pure virtual
Find out if table depends on the object identified by [b]name[/b].
Referenced by OpalData::define().
makeColumnExpression()
virtual Expressions::PtrToScalar<double> Table::makeColumnExpression (const std::string &) const pure virtual
Referenced by Expressions::parsePrimary().
matches()
virtual bool Table::matches (Table * rhs) const pure virtual
Check that [b]rhs[/b] is of same type as [b]this[/b].
operator=()
void Table::operator= (const Table &) private
printTable()
virtual void Table::printTable (std::ostream & , const CellArray &) const pure virtual
Print list for the table.
Referenced by List::list().
shouldTrace()
bool Table::shouldTrace () const virtual
Trace flag.
Implements Object.
Definition at line 55 of file Table.cpp.
shouldUpdate()
bool Table::shouldUpdate () const virtual
Update flag.
Implements Object.
Definition at line 60 of file Table.cpp.
Member Data Documentation
dynamic
bool Table::dynamic protected
Flag dynamic table.
Definition at line 153 of file Table.h.
Referenced by invalidate().
refill
bool Table::refill protected
Refill flag.
Definition at line 158 of file Table.h.
Referenced by invalidate().
The documentation for this class was generated from the following files:
src/AbstractObjects/Table.h
src/AbstractObjects/Table.cpp