OPAL (Object Oriented Parallel Accelerator Library): MueLuPreconditioner< Level > Class Template Reference
MueLuPreconditioner< Level > Class Template Reference
#include <MueLuPreconditioner.h>
Public Types
typedef amr::Preconditioner Preconditioner
typedef amr::scalar_t scalar_t
typedef amr::local_ordinal_t lo_t
typedef amr::global_ordinal_t go_t
typedef amr::AmrBox_t AmrBox_t
typedef MueLu::TpetraOperator< scalar_t, lo_t, go_t, amr::node_t > precond_t
typedef amr::AmrIntVect_t AmrIntVect_t
typedef std::map< std::string, Preconditioner > map_t
Public Types inherited from AmrPreconditioner< amr::matrix_t, Level >
typedef amr::operator_t operator_t
Public Member Functions
MueLuPreconditioner (const std::string &reuse)
void create (const Teuchos::RCP< amr::matrix_t > &A, Level *level_p=nullptr)
Teuchos::RCP< amr::operator_t> get ()
Static Public Member Functions
static void fillMap (map_t &map)
static std::string convertToMueLuReuseOption (const std::string &reuse)
Private Member Functions
void init_m (const std::string &reuse)
Private Attributes
Teuchos::ParameterList params_m
Teuchos::RCP< precond_t > prec_mp
Detailed Description
template<class Level>
class MueLuPreconditioner< Level >
Definition at line 32 of file MueLuPreconditioner.h.
Member Typedef Documentation
AmrBox_t
template<class Level > typedef amr::AmrBox_t MueLuPreconditioner< Level >::AmrBox_t
Definition at line 40 of file MueLuPreconditioner.h.
AmrIntVect_t
template<class Level > typedef amr::AmrIntVect_t MueLuPreconditioner< Level >::AmrIntVect_t
Definition at line 49 of file MueLuPreconditioner.h.
go_t
template<class Level > typedef amr::global_ordinal_t MueLuPreconditioner< Level >::go_t
Definition at line 39 of file MueLuPreconditioner.h.
lo_t
template<class Level > typedef amr::local_ordinal_t MueLuPreconditioner< Level >::lo_t
Definition at line 38 of file MueLuPreconditioner.h.
map_t
template<class Level > typedef std::map<std::string, Preconditioner> MueLuPreconditioner< Level >::map_t
Definition at line 51 of file MueLuPreconditioner.h.
precond_t
template<class Level > typedef MueLu::TpetraOperator< scalar_t, lo_t, go_t, amr::node_t > MueLuPreconditioner< Level >::precond_t
Definition at line 47 of file MueLuPreconditioner.h.
Preconditioner
template<class Level > typedef amr::Preconditioner MueLuPreconditioner< Level >::Preconditioner
Definition at line 35 of file MueLuPreconditioner.h.
scalar_t
template<class Level > typedef amr::scalar_t MueLuPreconditioner< Level >::scalar_t
Definition at line 37 of file MueLuPreconditioner.h.
Constructor & Destructor Documentation
MueLuPreconditioner()
template<class Level > MueLuPreconditioner< Level >::MueLuPreconditioner (const std::string & reuse) explicit
Definition at line 27 of file MueLuPreconditioner.hpp.
References MueLuPreconditioner< Level >::init_m().
Member Function Documentation
convertToMueLuReuseOption()
template<class Level > std::string MueLuPreconditioner< Level >::convertToMueLuReuseOption (const std::string & reuse) static
Definition at line 58 of file MueLuPreconditioner.hpp.
Referenced by AmrMultiGrid::initPrec_m().
create()
template<class Level > void MueLuPreconditioner< Level >::create (const Teuchos::RCP< amr::matrix_t > & A, Level * level_p = nullptr) virtual
Instantiate the preconditioner matrix
Parameters
A matrix for which to create preconditioner
level_p bottom level if necessary to build preconditioner
Implements AmrPreconditioner< amr::matrix_t, Level >.
Definition at line 35 of file MueLuPreconditioner.hpp.
fillMap()
template<class Level > void MueLuPreconditioner< Level >::fillMap (map_t & map) static
Definition at line 51 of file MueLuPreconditioner.hpp.
References amr::SA.
Referenced by AmrMultiGrid::convertToEnumPreconditioner_m().
get()
template<class Level > Teuchos::RCP< amr::operator_t> MueLuPreconditioner< Level >::get () virtual
Returns
the preconditioner
Implements AmrPreconditioner< amr::matrix_t, Level >.
Definition at line 45 of file MueLuPreconditioner.hpp.
init_m()
template<class Level > void MueLuPreconditioner< Level >::init_m (const std::string & reuse) private
Definition at line 78 of file MueLuPreconditioner.hpp.
Referenced by MueLuPreconditioner< Level >::MueLuPreconditioner().
Member Data Documentation
params_m
template<class Level > Teuchos::ParameterList MueLuPreconditioner< Level >::params_m private
Definition at line 68 of file MueLuPreconditioner.h.
prec_mp
template<class Level > Teuchos::RCP<precond_t> MueLuPreconditioner< Level >::prec_mp private
Definition at line 69 of file MueLuPreconditioner.h.
The documentation for this class was generated from the following files:
src/Solvers/AMR_MG/MueLuPreconditioner.h
src/Solvers/AMR_MG/MueLuPreconditioner.hpp