OPAL (Object Oriented Parallel Accelerator Library): FTps< T, N > Class Template Reference
FTps< T, N > Class Template Reference
Truncated power series in N variables of type T.
#include <FLieGenerator.h>
Public Member Functions
FTps ()
Default constructor.
FTps (const FTps &x)
Copy constructor.
FTps (int minOrder, int maxOrder, int trcOrder)
Constructor.
FTps (const T &)
Conversion.
FTps (int)
Conversion.
~FTps ()
Destructor.
FTps & operator= (const FTps &y)
Assign.
FTps & operator= (const T &y)
Convert and assign.
const T getCoefficient (int index) const
Get coefficient.
void setCoefficient (int index, const T &value)
Set coefficient.
const T getCoefficient (const FMonomial< N > &monomial) const
Get coefficient.
void setCoefficient (const FMonomial< N > &monomial, const T &value)
Set coefficient.
const T operator[] (int index) const
Get coefficient.
T & operator[] (int index)
Get (Set) coefficient.
const T operator[] (const FMonomial< N > &monomial) const
Get coefficient.
T & operator[] (const FMonomial< N > &monomial)
Get (Set) coefficient.
T * begin () const
Return beginning of monomial array.
T * end () const
Return end of monomial array.
T * begin (int order) const
Return beginning of coefficient storage for given order.
T * end (int order) const
Return end of coefficient storage for given order.
int getSize () const
Get total number of coefficients.
int getMinOrder () const
Get minimum order.
void setMinOrder (int order)
Set minimum order.
int getMaxOrder () const
Get maximum order.
void setMaxOrder (int order)
Set maximum order.
int getTruncOrder () const
Get truncation order.
void setTruncOrder (int order)
Set truncation order.
FTps filter (int minOrder, int maxOrder, int trcOrder=EXACT) const
Extract given range of orders, with truncation.
FTps truncate (int trunc)
Truncate.
FTps operator+ () const
Unary plus.
FTps operator- () const
Unary minus.
FTps & operator+= (const FTps &y)
Add and assign.
FTps & operator-= (const FTps &y)
Subtract and assign.
FTps & operator*= (const FTps &y)
Multiply and assign.
FTps & operator/= (const FTps &y)
Divide and assign.
FTps & operator+= (const T &y)
Add constant and assign.
FTps & operator-= (const T &y)
Subtract constant and assign.
FTps & operator*= (const T &y)
Multiply by constant and assign.
FTps & operator/= (const T &y)
Divide by constant and assign.
FTps scaleMonomials (const FTps &y) const
Scale monomial coefficients by coefficients in [b]y[/b].
FTps multiplyVariable (int var, int trunc=EXACT) const
Multiply by variable [b]var[/b].
FTps multiply (const FTps &y, int trunc=EXACT) const
Multiplication.
FTps inverse (int trunc=EXACT) const
Reciprocal, 1/(*this).
FTps divide (const FTps &y, int trunc=EXACT) const
Division.
bool operator== (const FTps &y) const
Equality operator.
bool operator== (const T &y) const
Equality with constant.
bool operator!= (const FTps &y) const
Inequality operator.
bool operator!= (const T &y) const
Inequality with constant.
T evaluate (const FVector< T, N > &) const
Evaluate FTps at point.
Array1D< int > getSubstOrders (const FVps< T, N > &rhs, int trunc=EXACT) const
Return orders {min, max, trc} of f(rhs(z)).
FTps substitute (const FMatrix< T, N, N > &M, int n) const
Substitute.
FTps substitute (const FMatrix< T, N, N > &M, int nl, int nh) const
Substitute.
FTps substitute (const FMatrix< T, N, N > &M) const
Substitute.
FTps substitute (const FVps< T, N > &m, int trunc=EXACT) const
Substitute.
FTps derivative (int var) const
Partial derivative.
FVps< T, N > gradient () const
Gradient.
FTps integral (int var, int trunc=EXACT) const
Partial integral.
FTps taylor (const Array1D< T > &series, int order) const
Taylor series.
void unique ()
Make representation unique.
std::list< int > getListOfNonzeroCoefficients () const
Get a list containing the indexes of non-zero coefficients of a FTps.
FArray1D< int, N > extractExponents (int index) const
Extract exponents of coefficient.
FTps< T, N > makePower (int power) const
Multiply FTps with itself.
std::istream & get (std::istream &is)
Read FTps on the stream [b]is[/b].
std::ostream & put (std::ostream &os) const
Write FTps on the stream [b]os[/b].
Static Public Member Functions
static int getVariables ()
Get number of variables.
static int getSize (int order)
Get number of coefficients of degree [b]order[/b] or less.
static int orderStart (int order)
Get index at which [b]order[/b] starts.
static int orderEnd (int order)
Get one plus index at which [b]order[/b] ends.
static int orderLength (int order)
static int orderLength (int orderL, int orderH)
static const FMonomial< N > & getExponents (int index)
Get exponents for given index.
static int getIndex (const FMonomial< N > &mono)
Get Giorgilli index for monomial.
static int getGlobalTruncOrder ()
Return the global truncation order.
static void setGlobalTruncOrder (int order)
Set the global truncation order.
static const Array1D< int > & getProductArray (int index)
Index array for products of monomial "index".
static const Array1D< int > & getVariableList (int index)
List of variables contained in monomial "index".
static const Array1D< TpsSubstitution > & getSubTable ()
Return the substitution table.
static FTps makeVariable (int var)
Make variable.
static FTps makeVarPower (int var, int power)
Make power.
static FTps makeMonomial (int index, const T &t)
Make monomial.
static FTps makeMonomial (const FMonomial< N > &m, const T &t)
Make monomial.
static Array1D< T > evalMonoms (const FVector< T, N > &, int)
Evaluate monomials at point.
static Array1D< int > getSubstOrders (Array1D< int > &ordersL, Array1D< int > &ordersR, int trunc=EXACT)
Return orders {min, max, trc} of f(rhs(z)),.
Static Public Attributes
static const int EXACT = INT_MAX
Representation of infinite precision.
Private Member Functions
void grow (int maxOrder, int trcOrder)
Array1D< int > getRepOrders () const
Static Private Member Functions
static FTpsRep< T, N > * allocate (int minOrder, int maxOrder, int trcOrder)
static void deallocate (FTpsRep< T, N > *)
static void checkOrders (const std::string &method, int minOrder, int maxOrder, int &trcOrder)
Private Attributes
FTpsRep< T, N > * itsRep
Static Private Attributes
static FTpsRep< T, N > * freeList [100]
static int globalTruncOrder
Detailed Description
template<class T, int N>
class FTps< T, N >
Truncated power series in N variables of type T.
Definition at line 29 of file FLieGenerator.h.
Constructor & Destructor Documentation
FTps() [1/5]
template<class T , int N> FTps< T, N >::FTps ()
Default constructor.
Definition at line 159 of file FTps.hpp.
FTps() [2/5]
template<class T , int N> FTps< T, N >::FTps (const FTps< T, N > & x)
Copy constructor.
Definition at line 166 of file FTps.hpp.
FTps() [3/5]
template<class T , int N> FTps< T, N >::FTps (int minOrder, int maxOrder, int trcOrder)
Constructor.
Definition at line 173 of file FTps.hpp.
FTps() [4/5]
template<class T, int N> FTps< T, N >::FTps (const T & rhs)
Conversion.
Definition at line 180 of file FTps.hpp.
FTps() [5/5]
template<class T, int N> FTps< T, N >::FTps (int rhs)
Conversion.
Definition at line 187 of file FTps.hpp.
~FTps()
template<class T , int N> FTps< T, N >::~FTps ()
Destructor.
Definition at line 194 of file FTps.hpp.
Member Function Documentation
allocate()
template<class T , int N> FTpsRep< T, N > * FTps< T, N >::allocate (int minOrder, int maxOrder, int trcOrder) inline static private
Definition at line 1692 of file FTps.hpp.
Referenced by FTps< double, 2 *3 >::unique().
begin() [1/2]
template<class T, int N> T* FTps< T, N >::begin () const inline
Return beginning of monomial array.
Definition at line 118 of file FTps.h.
Referenced by FTps< double, 2 *3 >::derivative(), FTps< double, 2 *3 >::divide(), FTps< double, 2 *3 >::filter(), FLieGenerator< T, N >::FLieGenerator(), FTps< double, 2 *3 >::integral(), FVps< T, N >::linearTerms(), operator+(), FTps< double, 2 *3 >::operator-(), operator-(), FTps< double, 2 *3 >::scaleMonomials(), and FTps< double, 2 *3 >::substitute().
begin() [2/2]
template<class T, int N> T* FTps< T, N >::begin (int order) const inline
Return beginning of coefficient storage for given order.
Definition at line 124 of file FTps.h.
checkOrders()
template<class T , int N> void FTps< T, N >::checkOrders (const std::string & method, int minOrder, int maxOrder, int & trcOrder) static private
Definition at line 1767 of file FTps.hpp.
deallocate()
template<class T, int N> void FTps< T, N >::deallocate (FTpsRep< T, N > * rep) inline static private
Definition at line 1726 of file FTps.hpp.
derivative()
template<class T , int N> FTps< T, N > FTps< T, N >::derivative (int var) const
Partial derivative.
Definition at line 1396 of file FTps.hpp.
Referenced by Tracker::applyThinSBend(), Tracker::buildSBendVectorPotential(), Tracker::buildSBendVectorPotential2D(), ExpMap(), and FVps< T, N >::linearTerms().
divide()
template<class T , int N> FTps< T, N > FTps< T, N >::divide (const FTps< T, N > & y, int trunc = EXACT) const
Division.
Definition at line 761 of file FTps.hpp.
Referenced by operator/().
end() [1/2]
template<class T, int N> T* FTps< T, N >::end () const inline
Return end of monomial array.
Definition at line 121 of file FTps.h.
Referenced by FTps< double, 2 *3 >::substitute().
end() [2/2]
template<class T, int N> T* FTps< T, N >::end (int order) const inline
Return end of coefficient storage for given order.
Definition at line 128 of file FTps.h.
evalMonoms()
template<class T, int N> Array1D< T > FTps< T, N >::evalMonoms (const FVector< T, N > & rhs, int maxOrder) static
Evaluate monomials at point.
Definition at line 898 of file FTps.hpp.
Referenced by FVps< T, N >::linearTerms().
evaluate()
template<class T, int N> T FTps< T, N >::evaluate (const FVector< T, N > & rhs) const
Evaluate FTps at point.
Definition at line 934 of file FTps.hpp.
Referenced by Tracker::applyThinSBend(), and operator*().
extractExponents()
template<class T , int N> FArray1D< int, N > FTps< T, N >::extractExponents (int index) const
Extract exponents of coefficient.
Definition at line 1535 of file FTps.hpp.
Referenced by FVps< T, N >::operator*().
filter()
template<class T , int N> FTps< T, N > FTps< T, N >::filter (int minOrder, int maxOrder, int trcOrder = EXACT) const
Extract given range of orders, with truncation.
Definition at line 451 of file FTps.hpp.
get()
template<class T , int N> std::istream & FTps< T, N >::get (std::istream & is)
Read FTps on the stream [b]is[/b].
Definition at line 1571 of file FTps.hpp.
Referenced by operator>>().
getCoefficient() [1/2]
template<class T , int N> const T FTps< T, N >::getCoefficient (int index) const
Get coefficient.
Definition at line 223 of file FTps.hpp.
Referenced by FVps< T, N >::operator*().
getCoefficient() [2/2]
template<class T , int N> const T FTps< T, N >::getCoefficient (const FMonomial< N > & monomial) const
Get coefficient.
Definition at line 261 of file FTps.hpp.
getExponents()
template<class T , int N> const FMonomial< N > & FTps< T, N >::getExponents (int index) static
Get exponents for given index.
Definition at line 309 of file FTps.hpp.
Referenced by FTps< double, 2 *3 >::extractExponents().
getGlobalTruncOrder()
template<class T, int N> static int FTps< T, N >::getGlobalTruncOrder () inline static
Return the global truncation order.
Definition at line 191 of file FTps.h.
Referenced by FVps< T, N >::operator*().
getIndex()
template<class T , int N> int FTps< T, N >::getIndex (const FMonomial< N > & mono) static
Get Giorgilli index for monomial.
Definition at line 315 of file FTps.hpp.
getListOfNonzeroCoefficients()
template<class T , int N> std::list< int > FTps< T, N >::getListOfNonzeroCoefficients () const
Get a list containing the indexes of non-zero coefficients of a FTps.
Definition at line 1515 of file FTps.hpp.
Referenced by FVps< T, N >::operator*().
getMaxOrder()
template<class T, int N> int FTps< T, N >::getMaxOrder () const inline
Get maximum order.
Definition at line 174 of file FTps.h.
Referenced by Tracker::buildMultipoleVectorPotential(), Tracker::buildMultipoleVectorPotential2D(), Tracker::buildSBendVectorPotential(), Tracker::buildSBendVectorPotential2D(), FTps< double, 2 *3 >::divide(), FLieGenerator< T, N >::FLieGenerator(), FTps< double, 2 *3 >::get(), FVps< T, N >::getMaxOrder(), FVps< T, N >::getTopOrder(), FVps< T, N >::linearTerms(), operator+(), operator-(), FTps< double, 2 *3 >::operator==(), and FTps< double, 2 *3 >::scaleMonomials().
getMinOrder()
template<class T, int N> int FTps< T, N >::getMinOrder () const inline
Get minimum order.
Definition at line 165 of file FTps.h.
Referenced by cos(), cosh(), cot(), coth(), csc(), csch(), erf(), exp(), ExpMap(), FTps< double, 2 *3 >::get(), FVps< T, N >::getMinOrder(), FVps< T, N >::linearTerms(), log(), FVps< T, N >::operator*(), operator+(), operator-(), FTps< double, 2 *3 >::operator==(), pow(), FTps< double, 2 *3 >::scaleMonomials(), sin(), sinh(), and sqrt().
getProductArray()
template<class T , int N> const Array1D< int > & FTps< T, N >::getProductArray (int index) inline static
Index array for products of monomial "index".
Definition at line 433 of file FTps.hpp.
getRepOrders()
template<class T , int N> Array1D< int > FTps< T, N >::getRepOrders () const private
Definition at line 1756 of file FTps.hpp.
getSize() [1/2]
template<class T, int N> int FTps< T, N >::getSize () const inline
Get total number of coefficients.
Definition at line 136 of file FTps.h.
Referenced by FVps< T, N >::substitute().
getSize() [2/2]
template<class T , int N> int FTps< T, N >::getSize (int order) static
Get number of coefficients of degree [b]order[/b] or less.
Definition at line 303 of file FTps.hpp.
getSubstOrders() [1/2]
template<class T, int N> Array1D< int > FTps< T, N >::getSubstOrders (const FVps< T, N > & rhs, int trunc = EXACT) const
Return orders {min, max, trc} of f(rhs(z)).
Definition at line 1008 of file FTps.hpp.
Referenced by FVps< T, N >::getSubstOrders().
getSubstOrders() [2/2]
template<class T, int N> Array1D< int > FTps< T, N >::getSubstOrders (Array1D< int > & ordersL, Array1D< int > & ordersR, int trunc = EXACT) static
Return orders {min, max, trc} of f(rhs(z)),.
Definition at line 1022 of file FTps.hpp.
getSubTable()
template<class T , int N> const Array1D< TpsSubstitution > & FTps< T, N >::getSubTable () inline static
Return the substitution table.
Definition at line 445 of file FTps.hpp.
getTruncOrder()
template<class T, int N> int FTps< T, N >::getTruncOrder () const inline
Get truncation order.
Definition at line 183 of file FTps.h.
Referenced by cos(), cosh(), FTps< double, 2 *3 >::divide(), erf(), exp(), ExpMap(), FVps< T, N >::getTruncOrder(), log(), operator+(), operator-(), FTps< double, 2 *3 >::operator==(), FTps< double, 2 *3 >::scaleMonomials(), sin(), sinh(), and sqrt().
getVariableList()
template<class T , int N> const Array1D< int > & FTps< T, N >::getVariableList (int index) inline static
List of variables contained in monomial "index".
Definition at line 439 of file FTps.hpp.
getVariables()
template<class T, int N> static int FTps< T, N >::getVariables () inline static
Get number of variables.
Definition at line 132 of file FTps.h.
gradient()
template<class T , int N> FVps< T, N > FTps< T, N >::gradient () const
Gradient.
Definition at line 1433 of file FTps.hpp.
grow()
template<class T , int N> void FTps< T, N >::grow (int maxOrder, int trcOrder) private
Definition at line 1734 of file FTps.hpp.
integral()
template<class T , int N> FTps< T, N > FTps< T, N >::integral (int var, int trunc = EXACT) const
Partial integral.
Definition at line 1441 of file FTps.hpp.
inverse()
template<class T , int N> FTps< T, N > FTps< T, N >::inverse (int trunc = EXACT) const
Reciprocal, 1/(*this).
Definition at line 707 of file FTps.hpp.
Referenced by operator/(), FVps< T, N >::operator/=(), and pow().
makeMonomial() [1/2]
template<class T, int N> FTps< T, N > FTps< T, N >::makeMonomial (int index, const T & t) static
Make monomial.
Definition at line 499 of file FTps.hpp.
makeMonomial() [2/2]
template<class T, int N> FTps< T, N > FTps< T, N >::makeMonomial (const FMonomial< N > & m, const T & t) static
Make monomial.
Definition at line 508 of file FTps.hpp.
makePower()
template<class T , int N> FTps< T, N > FTps< T, N >::makePower (int power) const
Multiply FTps with itself.
Definition at line 1555 of file FTps.hpp.
Referenced by FVps< T, N >::operator*().
makeVariable()
template<class T , int N> FTps< T, N > FTps< T, N >::makeVariable (int var) static
Make variable.
Definition at line 481 of file FTps.hpp.
Referenced by Tracker::buildMultipoleVectorPotential2D(), and Tracker::buildSBendVectorPotential2D().
makeVarPower()
template<class T , int N> FTps< T, N > FTps< T, N >::makeVarPower (int var, int power) static
Make power.
Definition at line 489 of file FTps.hpp.
multiply()
template<class T , int N> FTps< T, N > FTps< T, N >::multiply (const FTps< T, N > & y, int trunc = EXACT) const
Multiplication.
Definition at line 650 of file FTps.hpp.
Referenced by ExpMap(), FVps< T, N >::operator*(), operator*(), pow(), and FTps< double, 2 *3 >::taylor().
multiplyVariable()
template<class T , int N> FTps< T, N > FTps< T, N >::multiplyVariable (int var, int trunc = EXACT) const
Multiply by variable [b]var[/b].
Definition at line 610 of file FTps.hpp.
operator!=() [1/2]
template<class T , int N> bool FTps< T, N >::operator!= (const FTps< T, N > & y) const
Inequality operator.
Definition at line 886 of file FTps.hpp.
operator!=() [2/2]
template<class T, int N> bool FTps< T, N >::operator!= (const T & y) const
Inequality with constant.
Definition at line 892 of file FTps.hpp.
operator*=() [1/2]
template<class T , int N> FTps< T, N > & FTps< T, N >::operator*= (const FTps< T, N > & y)
Multiply and assign.
Definition at line 545 of file FTps.hpp.
operator*=() [2/2]
template<class T, int N> FTps< T, N > & FTps< T, N >::operator*= (const T & y)
Multiply by constant and assign.
Definition at line 575 of file FTps.hpp.
operator+()
template<class T , int N> FTps< T, N > FTps< T, N >::operator+ () const
Unary plus.
Definition at line 517 of file FTps.hpp.
operator+=() [1/2]
template<class T , int N> FTps< T, N > & FTps< T, N >::operator+= (const FTps< T, N > & y)
Add and assign.
Definition at line 533 of file FTps.hpp.
operator+=() [2/2]
template<class T, int N> FTps< T, N > & FTps< T, N >::operator+= (const T & y)
Add constant and assign.
Definition at line 557 of file FTps.hpp.
operator-()
template<class T , int N> FTps< T, N > FTps< T, N >::operator- () const
Unary minus.
Definition at line 523 of file FTps.hpp.
operator-=() [1/2]
template<class T , int N> FTps< T, N > & FTps< T, N >::operator-= (const FTps< T, N > & y)
Subtract and assign.
Definition at line 539 of file FTps.hpp.
operator-=() [2/2]
template<class T, int N> FTps< T, N > & FTps< T, N >::operator-= (const T & y)
Subtract constant and assign.
Definition at line 566 of file FTps.hpp.
operator/=() [1/2]
template<class T , int N> FTps< T, N > & FTps< T, N >::operator/= (const FTps< T, N > & y)
Divide and assign.
Definition at line 551 of file FTps.hpp.
operator/=() [2/2]
template<class T, int N> FTps< T, N > & FTps< T, N >::operator/= (const T & y)
Divide by constant and assign.
Definition at line 583 of file FTps.hpp.
operator=() [1/2]
template<class T , int N> FTps< T, N > & FTps< T, N >::operator= (const FTps< T, N > & y)
Assign.
Definition at line 201 of file FTps.hpp.
operator=() [2/2]
template<class T, int N> FTps< T, N > & FTps< T, N >::operator= (const T & y)
Convert and assign.
Definition at line 213 of file FTps.hpp.
operator==() [1/2]
template<class T , int N> bool FTps< T, N >::operator== (const FTps< T, N > & y) const
Equality operator.
Definition at line 831 of file FTps.hpp.
operator==() [2/2]
template<class T, int N> bool FTps< T, N >::operator== (const T & y) const
Equality with constant.
Definition at line 867 of file FTps.hpp.
operator[]() [1/4]
template<class T , int N> const T FTps< T, N >::operator[] (int index) const inline
Get coefficient.
Definition at line 275 of file FTps.hpp.
operator[]() [2/4]
template<class T , int N> T & FTps< T, N >::operator[] (int index) inline
Get (Set) coefficient.
Definition at line 281 of file FTps.hpp.
operator[]() [3/4]
template<class T , int N> const T FTps< T, N >::operator[] (const FMonomial< N > & monomial) const
Get coefficient.
Definition at line 288 of file FTps.hpp.
operator[]() [4/4]
template<class T , int N> T & FTps< T, N >::operator[] (const FMonomial< N > & monomial)
Get (Set) coefficient.
Definition at line 295 of file FTps.hpp.
orderEnd()
template<class T, int N> static int FTps< T, N >::orderEnd (int order) inline static
Get one plus index at which [b]order[/b] ends.
Definition at line 147 of file FTps.h.
Referenced by FVps< T, N >::linearTerms(), operator+(), operator-(), and FVps< T, N >::substitute().
orderLength() [1/2]
template<class T, int N> static int FTps< T, N >::orderLength (int order) inline static
Definition at line 151 of file FTps.h.
orderLength() [2/2]
template<class T, int N> static int FTps< T, N >::orderLength (int orderL, int orderH) inline static
Definition at line 155 of file FTps.h.
orderStart()
template<class T, int N> static int FTps< T, N >::orderStart (int order) inline static
Get index at which [b]order[/b] starts.
Definition at line 143 of file FTps.h.
Referenced by FVps< T, N >::linearTerms(), operator+(), operator-(), and FVps< T, N >::substitute().
put()
template<class T , int N> std::ostream & FTps< T, N >::put (std::ostream & os) const
Write FTps on the stream [b]os[/b].
Definition at line 1648 of file FTps.hpp.
scaleMonomials()
template<class T , int N> FTps< T, N > FTps< T, N >::scaleMonomials (const FTps< T, N > & y) const
Scale monomial coefficients by coefficients in [b]y[/b].
Definition at line 589 of file FTps.hpp.
setCoefficient() [1/2]
template<class T, int N> void FTps< T, N >::setCoefficient (int index, const T & value)
Set coefficient.
Definition at line 236 of file FTps.hpp.
setCoefficient() [2/2]
template<class T, int N> void FTps< T, N >::setCoefficient (const FMonomial< N > & monomial, const T & value)
Set coefficient.
Definition at line 268 of file FTps.hpp.
setGlobalTruncOrder()
template<class T , int N> void FTps< T, N >::setGlobalTruncOrder (int order) static
Set the global truncation order.
Definition at line 419 of file FTps.hpp.
Referenced by main().
setMaxOrder()
template<class T , int N> void FTps< T, N >::setMaxOrder (int order)
Set maximum order.
Definition at line 357 of file FTps.hpp.
setMinOrder()
template<class T , int N> void FTps< T, N >::setMinOrder (int order)
Set minimum order.
Definition at line 321 of file FTps.hpp.
Referenced by FVps< T, N >::operator*(), and FTps< double, 2 *3 >::taylor().
setTruncOrder()
template<class T , int N> void FTps< T, N >::setTruncOrder (int order)
Set truncation order.
Definition at line 393 of file FTps.hpp.
Referenced by Tracker::buildMultipoleVectorPotential(), Tracker::buildMultipoleVectorPotential2D(), Tracker::buildSBendVectorPotential(), Tracker::buildSBendVectorPotential2D(), ExpMap(), and FTps< double, 2 *3 >::taylor().
substitute() [1/4]
template<class T, int N> FTps< T, N > FTps< T, N >::substitute (const FMatrix< T, N, N > & M, int n) const
Substitute.
Definition at line 1075 of file FTps.hpp.
substitute() [2/4]
template<class T, int N> FTps< T, N > FTps< T, N >::substitute (const FMatrix< T, N, N > & M, int nl, int nh) const
Substitute.
Definition at line 1174 of file FTps.hpp.
substitute() [3/4]
template<class T, int N> FTps< T, N > FTps< T, N >::substitute (const FMatrix< T, N, N > & M) const
Substitute.
Definition at line 1302 of file FTps.hpp.
substitute() [4/4]
template<class T, int N> FTps< T, N > FTps< T, N >::substitute (const FVps< T, N > & m, int trunc = EXACT) const
Substitute.
Definition at line 1308 of file FTps.hpp.
taylor()
template<class T, int N> FTps< T, N > FTps< T, N >::taylor (const Array1D< T > & series, int order) const
Taylor series.
Definition at line 1481 of file FTps.hpp.
Referenced by cos(), cosh(), erf(), exp(), log(), sin(), sinh(), and sqrt().
truncate()
template<class T , int N> FTps< T, N > FTps< T, N >::truncate (int trunc) inline
Truncate.
Definition at line 475 of file FTps.hpp.
unique()
template<class T , int N> void FTps< T, N >::unique () inline
Make representation unique.
Definition at line 1505 of file FTps.hpp.
Referenced by FTps< double, 2 *3 >::taylor().
Member Data Documentation
EXACT
template<class T, int N> const int FTps< T, N >::EXACT = INT_MAX static
Representation of infinite precision.
Definition at line 383 of file FTps.h.
freeList
template<class T, int N> FTpsRep< T, N > * FTps< T, N >::freeList static private
Definition at line 409 of file FTps.h.
globalTruncOrder
template<class T, int N> int FTps< T, N >::globalTruncOrder static private
Definition at line 412 of file FTps.h.
Referenced by FTps< double, 2 *3 >::getGlobalTruncOrder().
itsRep
template<class T, int N> FTpsRep<T, N>* FTps< T, N >::itsRep private
Definition at line 405 of file FTps.h.
Referenced by FTps< double, 2 *3 >::begin(), FTps< double, 2 *3 >::divide(), FTps< double, 2 *3 >::end(), FTps< double, 2 *3 >::FTps(), FTps< double, 2 *3 >::get(), FTps< double, 2 *3 >::getMaxOrder(), FTps< double, 2 *3 >::getMinOrder(), FTps< double, 2 *3 >::getSize(), FTps< double, 2 *3 >::getTruncOrder(), FTps< double, 2 *3 >::inverse(), FTps< double, 2 *3 >::multiply(), FTps< double, 2 *3 >::operator=(), FTps< double, 2 *3 >::operator==(), and FTps< double, 2 *3 >::taylor().
The documentation for this class was generated from the following files:
src/Classic/FixedAlgebra/FLieGenerator.h
src/Classic/FixedAlgebra/FTps.h
src/Classic/FixedAlgebra/FTps.hpp