OPAL (Object Oriented Parallel Accelerator Library): SubParticleAttribIter< PA, T, Dim > Class Template Reference
SubParticleAttribIter< PA, T, Dim > Class Template Reference
#include <SubParticleAttrib.h>
Public Types
enum { IsExpr = 1 }
typedef SIndex< Dim > Index_t
typedef SubFieldIter< T, Dim, Index_t > SFI
typedef Index_t::const_iterator_iv const_iterator_iv
typedef SubParticleAttribIter< PA, T, Dim > PETE_Expr_t
typedef T PETE_Return_t
Public Types inherited from PETE_Expr< SubParticleAttribIter< PA, T, Dim > >
typedef SubParticleAttribIter< PA, T, Dim > Wrapped
Public Member Functions
SubParticleAttribIter (PA &a, const_iterator_iv lf, int o, const Index_t &s)
SubParticleAttribIter (const SubParticleAttribIter< PA, T, Dim > &i)
SubParticleAttribIter ()
~SubParticleAttribIter ()
bool operator!= (const SubParticleAttribIter< PA, T, Dim > &i)
PA & getAttrib ()
const Index_t & getDomain () const
void initialize ()
int size () const
int size (int) const
T & offset (int i)
T & unit_offset (int i)
const_iterator_iv nextLField ()
const_iterator_iv getLFieldIter () const
bool plugBase (const NDIndex< Dim > &)
PETE_Expr_t MakeExpression () const
Public Member Functions inherited from PETE_Expr< SubParticleAttribIter< PA, T, Dim > >
SubParticleAttribIter< PA, T, Dim > & PETE_unwrap ()
const SubParticleAttribIter< PA, T, Dim > & PETE_unwrap () const
Static Public Member Functions
static int getSubsetType ()
static bool matchType (int t)
static void makeNDIndex (const Index_t &s, NDIndex< Dim > &i)
Private Attributes
const Index_t * dom
PA * attrib
const_iterator_iv lfield
int attribOffset
Detailed Description
template<class PA, class T, unsigned Dim>
class SubParticleAttribIter< PA, T, Dim >
Definition at line 66 of file SubParticleAttrib.h.
Member Typedef Documentation
const_iterator_iv
template<class PA, class T, unsigned Dim> typedef Index_t::const_iterator_iv SubParticleAttribIter< PA, T, Dim >::const_iterator_iv
Definition at line 73 of file SubParticleAttrib.h.
Index_t
template<class PA, class T, unsigned Dim> typedef SIndex<Dim> SubParticleAttribIter< PA, T, Dim >::Index_t
Definition at line 71 of file SubParticleAttrib.h.
PETE_Expr_t
template<class PA, class T, unsigned Dim> typedef SubParticleAttribIter<PA,T,Dim> SubParticleAttribIter< PA, T, Dim >::PETE_Expr_t
Definition at line 132 of file SubParticleAttrib.h.
PETE_Return_t
template<class PA, class T, unsigned Dim> typedef T SubParticleAttribIter< PA, T, Dim >::PETE_Return_t
Definition at line 133 of file SubParticleAttrib.h.
SFI
template<class PA, class T, unsigned Dim> typedef SubFieldIter<T, Dim, Index_t> SubParticleAttribIter< PA, T, Dim >::SFI
Definition at line 72 of file SubParticleAttrib.h.
Member Enumeration Documentation
anonymous enum
template<class PA, class T, unsigned Dim> anonymous enum
Enumerator
IsExpr
Definition at line 131 of file SubParticleAttrib.h.
Constructor & Destructor Documentation
SubParticleAttribIter() [1/3]
template<class PA, class T, unsigned Dim> SubParticleAttribIter< PA, T, Dim >::SubParticleAttribIter (PA & a, const_iterator_iv lf, int o, const Index_t & s) inline
Definition at line 76 of file SubParticleAttrib.h.
SubParticleAttribIter() [2/3]
template<class PA, class T, unsigned Dim> SubParticleAttribIter< PA, T, Dim >::SubParticleAttribIter (const SubParticleAttribIter< PA, T, Dim > & i) inline
Definition at line 80 of file SubParticleAttrib.h.
SubParticleAttribIter() [3/3]
template<class PA, class T, unsigned Dim> SubParticleAttribIter< PA, T, Dim >::SubParticleAttribIter () inline
Definition at line 87 of file SubParticleAttrib.h.
~SubParticleAttribIter()
template<class PA, class T, unsigned Dim> SubParticleAttribIter< PA, T, Dim >::~SubParticleAttribIter () inline
Definition at line 90 of file SubParticleAttrib.h.
Member Function Documentation
getAttrib()
template<class PA, class T, unsigned Dim> PA& SubParticleAttribIter< PA, T, Dim >::getAttrib () inline
Definition at line 96 of file SubParticleAttrib.h.
References SubParticleAttribIter< PA, T, Dim >::attrib.
getDomain()
template<class PA, class T, unsigned Dim> const Index_t& SubParticleAttribIter< PA, T, Dim >::getDomain (void) const inline
Definition at line 97 of file SubParticleAttrib.h.
References SubParticleAttribIter< PA, T, Dim >::dom.
getLFieldIter()
template<class PA, class T, unsigned Dim> const_iterator_iv SubParticleAttribIter< PA, T, Dim >::getLFieldIter () const inline
Definition at line 119 of file SubParticleAttrib.h.
References SubParticleAttribIter< PA, T, Dim >::lfield.
Referenced by assign().
getSubsetType()
template<class PA, class T, unsigned Dim> static int SubParticleAttribIter< PA, T, Dim >::getSubsetType () inline static
Definition at line 99 of file SubParticleAttrib.h.
Referenced by SubParticleAttrib< PA, T, Dim >::getSubsetType().
initialize()
template<class PA, class T, unsigned Dim> void SubParticleAttribIter< PA, T, Dim >::initialize () inline
Definition at line 102 of file SubParticleAttrib.h.
Referenced by assign(), and for_each().
MakeExpression()
template<class PA, class T, unsigned Dim> PETE_Expr_t SubParticleAttribIter< PA, T, Dim >::MakeExpression () const inline
Definition at line 134 of file SubParticleAttrib.h.
makeNDIndex()
template<class PA, class T, unsigned Dim> static void SubParticleAttribIter< PA, T, Dim >::makeNDIndex (const Index_t & s, NDIndex< Dim > & i) inline static
Definition at line 109 of file SubParticleAttrib.h.
References SIndex< Dim >::getDomain().
Referenced by SubParticleAttrib< PA, T, Dim >::makeNDIndex().
matchType()
template<class PA, class T, unsigned Dim> static bool SubParticleAttribIter< PA, T, Dim >::matchType (int t) inline static
Definition at line 100 of file SubParticleAttrib.h.
Referenced by for_each().
nextLField()
template<class PA, class T, unsigned Dim> const_iterator_iv SubParticleAttribIter< PA, T, Dim >::nextLField () inline
Definition at line 113 of file SubParticleAttrib.h.
References SubParticleAttribIter< PA, T, Dim >::attribOffset, SubParticleAttribIter< PA, T, Dim >::lfield, and SubParticleAttribIter< PA, T, Dim >::size().
Referenced by assign(), and for_each().
offset()
template<class PA, class T, unsigned Dim> T& SubParticleAttribIter< PA, T, Dim >::offset (int i) inline
Definition at line 106 of file SubParticleAttrib.h.
References SubParticleAttribIter< PA, T, Dim >::attrib, and SubParticleAttribIter< PA, T, Dim >::attribOffset.
Referenced by for_each().
operator!=()
template<class PA, class T, unsigned Dim> bool SubParticleAttribIter< PA, T, Dim >::operator!= (const SubParticleAttribIter< PA, T, Dim > & i) inline
Definition at line 92 of file SubParticleAttrib.h.
References SubParticleAttribIter< PA, T, Dim >::attribOffset.
plugBase()
template<class PA, class T, unsigned Dim> bool SubParticleAttribIter< PA, T, Dim >::plugBase (const NDIndex< Dim > &) inline
Definition at line 123 of file SubParticleAttrib.h.
Referenced by for_each().
size() [1/2]
template<class PA, class T, unsigned Dim> int SubParticleAttribIter< PA, T, Dim >::size (void) const inline
Definition at line 104 of file SubParticleAttrib.h.
References SubParticleAttribIter< PA, T, Dim >::attrib.
Referenced by SubParticleAttribIter< PA, T, Dim >::nextLField().
size() [2/2]
template<class PA, class T, unsigned Dim> int SubParticleAttribIter< PA, T, Dim >::size (int) const inline
Definition at line 105 of file SubParticleAttrib.h.
unit_offset()
template<class PA, class T, unsigned Dim> T& SubParticleAttribIter< PA, T, Dim >::unit_offset (int i) inline
Definition at line 107 of file SubParticleAttrib.h.
References SubParticleAttribIter< PA, T, Dim >::attrib, and SubParticleAttribIter< PA, T, Dim >::attribOffset.
Member Data Documentation
attrib
template<class PA, class T, unsigned Dim> PA* SubParticleAttribIter< PA, T, Dim >::attrib private
Definition at line 139 of file SubParticleAttrib.h.
Referenced by SubParticleAttribIter< PA, T, Dim >::getAttrib(), SubParticleAttribIter< PA, T, Dim >::offset(), SubParticleAttribIter< PA, T, Dim >::size(), and SubParticleAttribIter< PA, T, Dim >::unit_offset().
attribOffset
template<class PA, class T, unsigned Dim> int SubParticleAttribIter< PA, T, Dim >::attribOffset private
Definition at line 144 of file SubParticleAttrib.h.
Referenced by SubParticleAttribIter< PA, T, Dim >::nextLField(), SubParticleAttribIter< PA, T, Dim >::offset(), SubParticleAttribIter< PA, T, Dim >::operator!=(), and SubParticleAttribIter< PA, T, Dim >::unit_offset().
dom
template<class PA, class T, unsigned Dim> const Index_t* SubParticleAttribIter< PA, T, Dim >::dom private
Definition at line 138 of file SubParticleAttrib.h.
Referenced by SubParticleAttribIter< PA, T, Dim >::getDomain().
lfield
template<class PA, class T, unsigned Dim> const_iterator_iv SubParticleAttribIter< PA, T, Dim >::lfield private
Definition at line 140 of file SubParticleAttrib.h.
Referenced by SubParticleAttribIter< PA, T, Dim >::getLFieldIter(), and SubParticleAttribIter< PA, T, Dim >::nextLField().
The documentation for this class was generated from the following file:
ippl/src/SubParticle/SubParticleAttrib.h