OPAL (Object Oriented Parallel Accelerator Library): mslang::Triangle Struct Reference
mslang::Triangle Struct Reference
#include <Triangle.h>
Public Member Functions
Triangle ()
Triangle (const Triangle &right)
virtual ~Triangle ()
virtual void print (int indentwidth)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
virtual std::shared_ptr< Base > clone () const
virtual void writeGnuplot (std::ofstream &out) const
virtual void computeBoundingBox ()
double crossProduct (const Vector_t &pt, unsigned int nodeNum) const
virtual bool isInside (const Vector_t &R) const
void orientNodesCCW ()
Public Member Functions inherited from mslang::Base
Base ()
Base (const Base &right)
virtual ~Base ()
virtual void divideBy (std::vector< std::shared_ptr< Base > > &divisors)
Public Member Functions inherited from mslang::Function
virtual ~Function ()
virtual void apply (std::vector< std::shared_ptr< Base >> &bfuncs)=0
Public Attributes
std::vector< Vector_t > nodes_m
Public Attributes inherited from mslang::Base
AffineTransformation trafo_m
BoundingBox2D bb_m
std::vector< std::shared_ptr< Base > > divisor_m
Additional Inherited Members
Static Public Member Functions inherited from mslang::Function
static bool parse (iterator &it, const iterator &end, Function *&fun)
Static Public Attributes inherited from mslang::Function
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\((.*)"
Detailed Description
Definition at line 7 of file Triangle.h.
Constructor & Destructor Documentation
Triangle() [1/2]
mslang::Triangle::Triangle () inline
Definition at line 9 of file Triangle.h.
Referenced by clone().
Triangle() [2/2]
mslang::Triangle::Triangle (const Triangle & right) inline
Definition at line 14 of file Triangle.h.
~Triangle()
virtual mslang::Triangle::~Triangle () inline virtual
Definition at line 19 of file Triangle.h.
Member Function Documentation
apply()
void Triangle::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Definition at line 22 of file Triangle.cpp.
References clone().
clone()
std::shared_ptr< Base > Triangle::clone () const virtual
Implements mslang::Base.
Definition at line 26 of file Triangle.cpp.
References mslang::Base::bb_m, mslang::Base::divisor_m, mslang::Base::trafo_m, and Triangle().
Referenced by apply().
computeBoundingBox()
void Triangle::computeBoundingBox () virtual
Implements mslang::Base.
Definition at line 57 of file Triangle.cpp.
References mslang::Base::bb_m, mslang::Base::divisor_m, nodes_m, mslang::Base::trafo_m, and mslang::AffineTransformation::transformFrom().
crossProduct()
double Triangle::crossProduct (const Vector_t & pt, unsigned int nodeNum) const
Definition at line 79 of file Triangle.cpp.
References nodes_m.
Referenced by isInside(), and orientNodesCCW().
isInside()
bool Triangle::isInside (const Vector_t & R) const virtual
Implements mslang::Base.
Definition at line 89 of file Triangle.cpp.
References crossProduct(), mslang::Base::divisor_m, Attrib::Distribution::R, mslang::Base::trafo_m, mslang::AffineTransformation::transformTo(), and X.
orientNodesCCW()
void Triangle::orientNodesCCW ()
Definition at line 104 of file Triangle.cpp.
References crossProduct(), and nodes_m.
print()
void Triangle::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 5 of file Triangle.cpp.
References endl(), mslang::AffineTransformation::getAngle(), mslang::AffineTransformation::getOrigin(), nodes_m, Units::rad2deg, and mslang::Base::trafo_m.
writeGnuplot()
void Triangle::writeGnuplot (std::ofstream & out) const virtual
Implements mslang::Base.
Definition at line 38 of file Triangle.cpp.
References mslang::Base::divisor_m, endl(), nodes_m, mslang::Base::trafo_m, and mslang::AffineTransformation::transformFrom().
Member Data Documentation
nodes_m
std::vector<Vector_t> mslang::Triangle::nodes_m
Definition at line 8 of file Triangle.h.
Referenced by Mesher::apply(), computeBoundingBox(), crossProduct(), orientNodesCCW(), print(), and writeGnuplot().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Triangle.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Triangle.cpp