OPAL (Object Oriented Parallel Accelerator Library): Field< T, Dim, M, C > Class Template Reference
Field< T, Dim, M, C > Class Template Reference
#include <FieldDataSource.h>
Public Types
typedef M Mesh_t
typedef C Centering_t
typedef BareField< T, Dim > Base_t
typedef FieldLayout< Dim > Layout_t
typedef BConds< T, Dim, M, C > bcond_container
typedef BCondBase< T, Dim, M, C > bcond_value
typedef bcond_container::iterator bcond_iterator
Public Types inherited from BareField< T, Dim >
enum { Dim_u = Dim }
enum { IsExpr = 0 }
typedef T T_t
typedef FieldLayout< Dim > Layout_t
typedef LField< T, Dim > LField_t
typedef vmap< typename Unique::type, my_auto_ptr< LField< T, Dim > > > ac_id_larray
typedef ac_id_larray::iterator iterator_if
typedef ac_id_larray::const_iterator const_iterator_if
typedef LField< T, Dim >::iterator LFI
typedef BareFieldIterator< T, Dim > iterator
typedef iterator PETE_Expr_t
Public Types inherited from User
typedef Unique::type ID_t
Public Types inherited from PETE_Expr< BareField< T, Dim > >
typedef BareField< T, Dim > Wrapped
Public Types inherited from DataSource
enum DsMode { INPUT, OUTPUT, BOTH, DEFAULT }
typedef std::vector< DataSourceObject * > container_t
Public Member Functions
Field ()
virtual ~Field ()
Field (Layout_t &)
Field (Layout_t &, const GuardCellSizes< Dim > &)
Field (Layout_t &, const BConds< T, Dim, M, C > &)
Field (Layout_t &, const GuardCellSizes< Dim > &, const BConds< T, Dim, M, C > &)
Field (Layout_t &, const BConds< T, Dim, M, C > &, const GuardCellSizes< Dim > &)
Field (FieldSpec< T, Dim, M, C > &)
constexpr Field (Field< T, Dim, M, C > &)=default
Field (Mesh_t &, Layout_t &)
Field (Mesh_t &, Layout_t &, const GuardCellSizes< Dim > &)
Field (Mesh_t &, Layout_t &, const BConds< T, Dim, M, C > &)
Field (Mesh_t &, Layout_t &, const GuardCellSizes< Dim > &, const BConds< T, Dim, M, C > &)
Field (Mesh_t &, Layout_t &, const BConds< T, Dim, M, C > &, const GuardCellSizes< Dim > &)
Field (Mesh_t &, FieldSpec< T, Dim, M, C > &)
void initialize (Layout_t &)
void initialize (Layout_t &, const GuardCellSizes< Dim > &)
void initialize (Layout_t &, const BConds< T, Dim, M, C > &)
void initialize (Layout_t &, const GuardCellSizes< Dim > &, const BConds< T, Dim, M, C > &)
void initialize (Layout_t &, const BConds< T, Dim, M, C > &, const GuardCellSizes< Dim > &)
void initialize (FieldSpec< T, Dim, M, C > &)
void initialize (Mesh_t &, Layout_t &)
void initialize (Mesh_t &, Layout_t &, const bool)
void initialize (Mesh_t &, Layout_t &, const GuardCellSizes< Dim > &)
void initialize (Mesh_t &, Layout_t &, const BConds< T, Dim, M, C > &)
void initialize (Mesh_t &, Layout_t &, const GuardCellSizes< Dim > &, const BConds< T, Dim, M, C > &)
void initialize (Mesh_t &, Layout_t &, const BConds< T, Dim, M, C > &, const GuardCellSizes< Dim > &)
void initialize (Mesh_t &, FieldSpec< T, Dim, M, C > &)
const bcond_value & getBCond (int bc) const
bcond_value & getBCond (int bc)
const bcond_container & getBConds () const
bcond_container & getBConds ()
bcond_iterator begin_BConds ()
bcond_iterator end_BConds ()
Mesh_t & get_mesh () const
IndexedField< T, Dim, 1, M, C > operator[] (const Index &)
IndexedField< T, Dim, 1, M, C > operator[] (int)
IndexedField< T, Dim, Dim, M, C > operator[] (const NDIndex< Dim > &)
SubField< T, Dim, M, C, SIndex< Dim > > operator[] (const SIndex< Dim > &)
const Field< T, Dim, M, C > & operator= (T x)
const Field< T, Dim, M, C > & operator= (const Field< T, Dim, M, C > &x)
template<class X >
const Field< T, Dim, M, C > & operator= (const BareField< X, Dim > &x)
template<class B >
const Field< T, Dim, M, C > & operator= (const PETE_Expr< B > &x)
void fillGuardCells (bool reallyFill=true) const
void print_Centerings (std::ostream &)
virtual void Repartition (UserList *)
virtual void notifyUserOfDelete (UserList *)
Public Member Functions inherited from BareField< T, Dim >
BareField ()
BareField (const BareField< T, Dim > &)
BareField (Layout_t &)
BareField (Layout_t &, const GuardCellSizes< Dim > &)
~BareField ()
void initialize (Layout_t &)
void initialize (Layout_t &, const bool)
void initialize (Layout_t &, const GuardCellSizes< Dim > &)
iterator_if begin_if ()
iterator_if end_if ()
const_iterator_if begin_if () const
const_iterator_if end_if () const
ac_id_larray::size_type size_if () const
void setGuardCells (const T &) const
void accumGuardCells ()
bool isDirty () const
void setDirtyFlag ()
void clearDirtyFlag ()
void fillGuardCellsIfNotDirty () const
Layout_t & getLayout () const
IndexedBareField< T, Dim, 1 > operator[] (const Index &idx)
IndexedBareField< T, Dim, 1 > operator[] (int i)
IndexedBareField< T, Dim, Dim > operator[] (const NDIndex< Dim > &nidx)
SubBareField< T, Dim, SIndex< Dim > > operator[] (const SIndex< Dim > &)
const GuardCellSizes< Dim > & getGC () const
const GuardCellSizes< Dim > & getGuardCellSizes () const
unsigned leftGuard (unsigned d) const
unsigned rightGuard (unsigned d) const
const Index & getIndex (unsigned d) const
const NDIndex< Dim > & getDomain () const
const BareField< T, Dim > & operator= (T x)
const BareField< T, Dim > & operator= (const BareField< T, Dim > &x)
template<class X >
const BareField< T, Dim > & operator= (const BareField< X, Dim > &x)
template<class B >
const BareField< T, Dim > & operator= (const PETE_Expr< B > &x)
bool compressible () const
double CompressedFraction () const
void Compress () const
void Uncompress () const
void setCompression (bool compress)
iterator begin () const
iterator end () const
iterator beginLoc (const FieldLoc< Dim > &loc) const
void prepareForScalarCode (bool tryfill=true)
void finishScalarCode (bool modified=true)
T & localElement (const NDIndex< Dim > &) const
void getsingle (const NDIndex< Dim > &, T &) const
void write (std::ostream &)
iterator MakeExpression () const
Public Member Functions inherited from FieldLayoutUser
FieldLayoutUser ()
virtual ~FieldLayoutUser ()
Public Member Functions inherited from User
User ()
virtual ~User ()
ID_t get_Id () const
Public Member Functions inherited from PETE_Expr< BareField< T, Dim > >
BareField< T, Dim > & PETE_unwrap ()
const BareField< T, Dim > & PETE_unwrap () const
Public Member Functions inherited from DataSource
DataSource ()
virtual ~DataSource ()
bool connected (DataConnect *=0) const
DataSourceObject * findDataSourceObject (DataConnect *) const
DataConnect * connect (const char *, DataConnect *=0, int=DataSource::DEFAULT)
bool connect (DataSourceObject *)
bool disconnect (DataConnect *=0)
bool updateConnection (DataConnect *=0)
void interact (DataConnect *=0)
void interact (const char *, DataConnect *=0)
Protected Member Functions
virtual DataSourceObject * createDataSourceObject (const char *, DataConnect *, int)
Private Member Functions
void store_mesh (Mesh_t *, bool)
void delete_mesh ()
Private Attributes
bcond_container Bc
Mesh_t * mesh
bool WeOwnMesh
Friends
class BareFieldIterator< T, Dim >
Additional Inherited Members
Protected Attributes inherited from BareField< T, Dim >
ac_id_larray Locals_ac
Protected Attributes inherited from User
ID_t Id
Detailed Description
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering>
class Field< T, Dim, M, C >
Definition at line 38 of file FieldDataSource.h.
Member Typedef Documentation
Base_t
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> typedef BareField<T,Dim> Field< T, Dim, M, C >::Base_t
Definition at line 41 of file Field.h.
bcond_container
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> typedef BConds<T,Dim,M,C> Field< T, Dim, M, C >::bcond_container
Definition at line 43 of file Field.h.
bcond_iterator
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> typedef bcond_container::iterator Field< T, Dim, M, C >::bcond_iterator
Definition at line 45 of file Field.h.
bcond_value
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> typedef BCondBase<T,Dim,M,C> Field< T, Dim, M, C >::bcond_value
Definition at line 44 of file Field.h.
Centering_t
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> typedef C Field< T, Dim, M, C >::Centering_t
Definition at line 40 of file Field.h.
Layout_t
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> typedef FieldLayout<Dim> Field< T, Dim, M, C >::Layout_t
Definition at line 42 of file Field.h.
Mesh_t
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> typedef M Field< T, Dim, M, C >::Mesh_t
Definition at line 39 of file Field.h.
Constructor & Destructor Documentation
Field() [1/14]
template<class T , unsigned Dim, class M , class C > Field< T, Dim, M, C >::Field ()
Definition at line 103 of file Field.hpp.
~Field()
template<class T , unsigned Dim, class M , class C > Field< T, Dim, M, C >::~Field () virtual
Definition at line 113 of file Field.hpp.
Field() [2/14]
template<class T , unsigned Dim, class M , class C > Field< T, Dim, M, C >::Field (Layout_t & l)
Definition at line 126 of file Field.hpp.
Field() [3/14]
template<class T , unsigned Dim, class M , class C > Field< T, Dim, M, C >::Field (Layout_t & l, const GuardCellSizes< Dim > & gc)
Definition at line 133 of file Field.hpp.
Field() [4/14]
template<class T, unsigned Dim, class M, class C> Field< T, Dim, M, C >::Field (Layout_t & l, const BConds< T, Dim, M, C > & bc)
Definition at line 141 of file Field.hpp.
Field() [5/14]
template<class T, unsigned Dim, class M, class C> Field< T, Dim, M, C >::Field (Layout_t & l, const GuardCellSizes< Dim > & gc, const BConds< T, Dim, M, C > & bc)
Definition at line 149 of file Field.hpp.
Field() [6/14]
template<class T, unsigned Dim, class M, class C> Field< T, Dim, M, C >::Field (Layout_t & l, const BConds< T, Dim, M, C > & bc, const GuardCellSizes< Dim > & gc)
Definition at line 158 of file Field.hpp.
Field() [7/14]
template<class T, unsigned Dim, class M, class C> Field< T, Dim, M, C >::Field (FieldSpec< T, Dim, M, C > & spec)
Definition at line 167 of file Field.hpp.
Field() [8/14]
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> constexpr Field< T, Dim, M, C >::Field (Field< T, Dim, M, C > &) default
Field() [9/14]
template<class T, unsigned Dim, class M, class C> Field< T, Dim, M, C >::Field (Mesh_t & m, Layout_t & l)
Definition at line 179 of file Field.hpp.
Field() [10/14]
template<class T, unsigned Dim, class M, class C> Field< T, Dim, M, C >::Field (Mesh_t & m, Layout_t & l, const GuardCellSizes< Dim > & gc)
Definition at line 187 of file Field.hpp.
Field() [11/14]
template<class T, unsigned Dim, class M, class C> Field< T, Dim, M, C >::Field (Mesh_t & m, Layout_t & l, const BConds< T, Dim, M, C > & bc)
Definition at line 195 of file Field.hpp.
Field() [12/14]
template<class T, unsigned Dim, class M, class C> Field< T, Dim, M, C >::Field (Mesh_t & m, Layout_t & l, const GuardCellSizes< Dim > & gc, const BConds< T, Dim, M, C > & bc)
Definition at line 204 of file Field.hpp.
Field() [13/14]
template<class T, unsigned Dim, class M, class C> Field< T, Dim, M, C >::Field (Mesh_t & m, Layout_t & l, const BConds< T, Dim, M, C > & bc, const GuardCellSizes< Dim > & gc)
Definition at line 213 of file Field.hpp.
Field() [14/14]
template<class T, unsigned Dim, class M, class C> Field< T, Dim, M, C >::Field (Mesh_t & m, FieldSpec< T, Dim, M, C > & spec)
Definition at line 222 of file Field.hpp.
Member Function Documentation
begin_BConds()
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> bcond_iterator Field< T, Dim, M, C >::begin_BConds () inline
Definition at line 106 of file Field.h.
createDataSourceObject()
template<class T , unsigned Dim, class M , class C > DataSourceObject * Field< T, Dim, M, C >::createDataSourceObject (const char * nm, DataConnect * dc, int tm) protected virtual
Implements DataSource.
Definition at line 489 of file Field.hpp.
delete_mesh()
template<class T , unsigned Dim, class M , class C > void Field< T, Dim, M, C >::delete_mesh () private
Definition at line 513 of file Field.hpp.
end_BConds()
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> bcond_iterator Field< T, Dim, M, C >::end_BConds () inline
Definition at line 107 of file Field.h.
fillGuardCells()
template<class T , unsigned Dim, class M , class C > void Field< T, Dim, M, C >::fillGuardCells (bool reallyFill = true) const virtual
Reimplemented from BareField< T, Dim >.
Definition at line 366 of file Field.hpp.
Referenced by ParticleAttrib< ParticleOrigin >::gather().
get_mesh()
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> Mesh_t& Field< T, Dim, M, C >::get_mesh () const inline
Definition at line 110 of file Field.h.
Referenced by PartBunch::computeSelfFields(), ParticleAttrib< ParticleOrigin >::gather(), ParticleAttrib< ParticleOrigin >::scatter(), and scatter().
getBCond() [1/2]
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> const bcond_value& Field< T, Dim, M, C >::getBCond (int bc) const inline
Definition at line 102 of file Field.h.
getBCond() [2/2]
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> bcond_value& Field< T, Dim, M, C >::getBCond (int bc) inline
Definition at line 103 of file Field.h.
getBConds() [1/2]
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> const bcond_container& Field< T, Dim, M, C >::getBConds () const inline
Definition at line 104 of file Field.h.
Referenced by Field< Vector_t, 3, Mesh_t, Center_t >::fillGuardCells().
getBConds() [2/2]
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> bcond_container& Field< T, Dim, M, C >::getBConds () inline
Definition at line 105 of file Field.h.
initialize() [1/13]
template<class T , unsigned Dim, class M , class C > void Field< T, Dim, M, C >::initialize (Layout_t & l)
Definition at line 236 of file Field.hpp.
Referenced by FFTBoxPoissonSolver::FFTBoxPoissonSolver(), P3MPoissonSolver::initializeFields(), FFTPoissonSolver::initializeFields(), PartBunch::resizeMesh(), FFTBoxPoissonSolver::shiftedIntGreensFunction(), and PartBunch::updateFields().
initialize() [2/13]
template<class T , unsigned Dim, class M , class C > void Field< T, Dim, M, C >::initialize (Layout_t & l, const GuardCellSizes< Dim > & gc)
Definition at line 244 of file Field.hpp.
initialize() [3/13]
template<class T, unsigned Dim, class M, class C> void Field< T, Dim, M, C >::initialize (Layout_t & l, const BConds< T, Dim, M, C > & bc)
Definition at line 253 of file Field.hpp.
initialize() [4/13]
template<class T, unsigned Dim, class M, class C> void Field< T, Dim, M, C >::initialize (Layout_t & l, const GuardCellSizes< Dim > & gc, const BConds< T, Dim, M, C > & bc)
Definition at line 263 of file Field.hpp.
initialize() [5/13]
template<class T, unsigned Dim, class M, class C> void Field< T, Dim, M, C >::initialize (Layout_t & l, const BConds< T, Dim, M, C > & bc, const GuardCellSizes< Dim > & gc)
Definition at line 274 of file Field.hpp.
initialize() [6/13]
template<class T, unsigned Dim, class M, class C> void Field< T, Dim, M, C >::initialize (FieldSpec< T, Dim, M, C > & spec)
Definition at line 285 of file Field.hpp.
initialize() [7/13]
template<class T, unsigned Dim, class M, class C> void Field< T, Dim, M, C >::initialize (Mesh_t & m, Layout_t & l)
Definition at line 298 of file Field.hpp.
initialize() [8/13]
template<class T, unsigned Dim, class M, class C> void Field< T, Dim, M, C >::initialize (Mesh_t & m, Layout_t & l, const bool p)
Definition at line 307 of file Field.hpp.
initialize() [9/13]
template<class T, unsigned Dim, class M, class C> void Field< T, Dim, M, C >::initialize (Mesh_t & m, Layout_t & l, const GuardCellSizes< Dim > & gc)
Definition at line 315 of file Field.hpp.
initialize() [10/13]
template<class T, unsigned Dim, class M, class C> void Field< T, Dim, M, C >::initialize (Mesh_t & m, Layout_t & l, const BConds< T, Dim, M, C > & bc)
Definition at line 323 of file Field.hpp.
initialize() [11/13]
template<class T, unsigned Dim, class M, class C> void Field< T, Dim, M, C >::initialize (Mesh_t & m, Layout_t & l, const GuardCellSizes< Dim > & gc, const BConds< T, Dim, M, C > & bc)
Definition at line 333 of file Field.hpp.
initialize() [12/13]
template<class T, unsigned Dim, class M, class C> void Field< T, Dim, M, C >::initialize (Mesh_t & m, Layout_t & l, const BConds< T, Dim, M, C > & bc, const GuardCellSizes< Dim > & gc)
Definition at line 343 of file Field.hpp.
initialize() [13/13]
template<class T, unsigned Dim, class M, class C> void Field< T, Dim, M, C >::initialize (Mesh_t & m, FieldSpec< T, Dim, M, C > & spec)
Definition at line 353 of file Field.hpp.
notifyUserOfDelete()
template<class T , unsigned Dim, class M , class C > void Field< T, Dim, M, C >::notifyUserOfDelete (UserList * userlist) virtual
Reimplemented from BareField< T, Dim >.
Definition at line 471 of file Field.hpp.
operator=() [1/4]
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> const Field<T,Dim,M,C>& Field< T, Dim, M, C >::operator= (T x) inline
Definition at line 123 of file Field.h.
operator=() [2/4]
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> const Field<T,Dim,M,C>& Field< T, Dim, M, C >::operator= (const Field< T, Dim, M, C > & x) inline
Definition at line 128 of file Field.h.
operator=() [3/4]
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> template<class X > const Field<T,Dim,M,C>& Field< T, Dim, M, C >::operator= (const BareField< X, Dim > & x) inline
Definition at line 134 of file Field.h.
operator=() [4/4]
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> template<class B > const Field<T,Dim,M,C>& Field< T, Dim, M, C >::operator= (const PETE_Expr< B > & x) inline
Definition at line 140 of file Field.h.
operator[]() [1/4]
template<class T , unsigned Dim, class M , class C > IndexedField< T, Dim, 1, M, C > Field< T, Dim, M, C >::operator[] (const Index & idx)
Definition at line 390 of file Field.hpp.
operator[]() [2/4]
template<class T , unsigned Dim, class M , class C > IndexedField< T, Dim, 1, M, C > Field< T, Dim, M, C >::operator[] (int i)
Definition at line 400 of file Field.hpp.
operator[]() [3/4]
template<class T , unsigned D, class M , class C > IndexedField< T, D, D, M, C > Field< T, D, M, C >::operator[] (const NDIndex< D > & n)
Definition at line 410 of file Field.hpp.
operator[]() [4/4]
template<class T , unsigned D, class M , class C > SubField< T, D, M, C, SIndex< D > > Field< T, D, M, C >::operator[] (const SIndex< D > & s)
Definition at line 420 of file Field.hpp.
print_Centerings()
template<class T , unsigned Dim, class M , class C > void Field< T, Dim, M, C >::print_Centerings (std::ostream & out)
Definition at line 431 of file Field.hpp.
Repartition()
template<class T , unsigned Dim, class M , class C > void Field< T, Dim, M, C >::Repartition (UserList * userlist) virtual
Reimplemented from BareField< T, Dim >.
Definition at line 441 of file Field.hpp.
store_mesh()
template<class T , unsigned Dim, class M , class C > void Field< T, Dim, M, C >::store_mesh (Mesh_t * m, bool WeOwn) private
Definition at line 500 of file Field.hpp.
Referenced by Field< Vector_t, 3, Mesh_t, Center_t >::Field().
Friends And Related Function Documentation
BareFieldIterator< T, Dim >
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> friend class BareFieldIterator< T, Dim > friend
Definition at line 35 of file Field.h.
Member Data Documentation
Bc
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> bcond_container Field< T, Dim, M, C >::Bc private
Definition at line 171 of file Field.h.
Referenced by Field< Vector_t, 3, Mesh_t, Center_t >::begin_BConds(), Field< Vector_t, 3, Mesh_t, Center_t >::end_BConds(), Field< Vector_t, 3, Mesh_t, Center_t >::getBCond(), and Field< Vector_t, 3, Mesh_t, Center_t >::getBConds().
mesh
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> Mesh_t* Field< T, Dim, M, C >::mesh private
Definition at line 174 of file Field.h.
Referenced by Field< Vector_t, 3, Mesh_t, Center_t >::get_mesh().
WeOwnMesh
template<class T, unsigned Dim, class M = UniformCartesian<Dim,double>, class C = typename M::DefaultCentering> bool Field< T, Dim, M, C >::WeOwnMesh private
Definition at line 175 of file Field.h.
The documentation for this class was generated from the following files:
ippl/src/DataSource/FieldDataSource.h
ippl/src/Field/Field.h
ippl/src/Field/Field.hpp