OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Field/BCond.hpp File Reference
BCond.hpp File Reference
#include "Field/BCond.h"
#include "Field/BareField.h"
#include "Index/NDIndex.h"
#include "Index/Index.h"
#include "Field/GuardCellSizes.h"
#include "Field/BrickIterator.h"
#include "Field/BrickExpression.h"
#include "Meshes/Centering.h"
#include "Meshes/CartesianCentering.h"
#include "Utility/IpplInfo.h"
#include "Utility/PAssert.h"
#include "AppTypes/AppTypeTraits.h"
#include <iostream>
#include <typeinfo>
#include <vector>
Classes
struct OpPeriodic< T >
struct OpPeriodicComponent< T >
struct OpInterpolation< T >
struct OpInterpolationComponent< T >
struct OpExtrapolate< T >
struct OpExtrapolateComponent< T >
struct OpExtrapolateAndZero< T >
struct OpExtrapolateAndZeroComponent< T >
struct OpAssignComponent< T >
struct OpBCFunctionEq< T >
struct OpBCFunctionEqComponent< T >
struct EurekaAssign< T >
struct EurekaAssign< Vektor< T, D > >
struct EurekaAssign< Tenzor< T, D > >
struct EurekaAssign< AntiSymTenzor< T, D > >
struct EurekaAssign< SymTenzor< T, D > >
Macros
#define COMPONENT_APPLY_BUILTIN(OP, T)
Functions
template<class T >
void PETE_apply (const OpPeriodic< T > &, T &a, const T &b)
template<class T >
void PETE_apply (const OpPeriodicComponent< T > &e, T &a, const T &b)
void PETE_apply (const OpPeriodicComponent< char > &, char &, const char &)
void PETE_apply (const OpPeriodicComponent< bool > &, bool &, const bool &)
void PETE_apply (const OpPeriodicComponent< int > &, int &, const int &)
void PETE_apply (const OpPeriodicComponent< unsigned > &, unsigned &, const unsigned &)
void PETE_apply (const OpPeriodicComponent< short > &, short &, const short &)
void PETE_apply (const OpPeriodicComponent< long > &, long &, const long &)
void PETE_apply (const OpPeriodicComponent< float > &, float &, const float &)
void PETE_apply (const OpPeriodicComponent< double > &, double &, const double &)
void PETE_apply (const OpPeriodicComponent< std::complex< double > > &, std::complex< double > &, const std::complex< double > &)
template<class T >
void PETE_apply (const OpInterpolation< T > &, T &a, const T &b)
template<class T >
void PETE_apply (const OpInterpolationComponent< T > &e, T &a, const T &b)
void PETE_apply (const OpInterpolationComponent< char > &, char &, const char &)
void PETE_apply (const OpInterpolationComponent< bool > &, bool &, const bool &)
void PETE_apply (const OpInterpolationComponent< int > &, int &, const int &)
void PETE_apply (const OpInterpolationComponent< unsigned > &, unsigned &, const unsigned &)
void PETE_apply (const OpInterpolationComponent< short > &, short &, const short &)
void PETE_apply (const OpInterpolationComponent< long > &, long &, const long &)
void PETE_apply (const OpInterpolationComponent< float > &, float &, const float &)
void PETE_apply (const OpInterpolationComponent< double > &, double &, const double &)
void PETE_apply (const OpInterpolationComponent< std::complex< double > > &, std::complex< double > &, const std::complex< double > &)
template<class T , unsigned D, class M >
void PeriodicFaceBCApply (PeriodicFace< T, D, M, Cell > &pf, Field< T, D, M, Cell > &A)
template<class T , unsigned D, class M >
void InterpolationFaceBCApply (InterpolationFace< T, D, M, Cell > &pf, Field< T, D, M, Cell > &A)
template<class T , unsigned D, class M >
void PeriodicFaceBCApply (PeriodicFace< T, D, M, Vert > &pf, Field< T, D, M, Vert > &A)
template<class T , unsigned D, class M >
void PeriodicFaceBCApply (PeriodicFace< T, D, M, Edge > &pf, Field< T, D, M, Edge > &A)
template<class T , unsigned D, class M , CenteringEnum * CE, unsigned NC>
void PeriodicFaceBCApply (PeriodicFace< T, D, M, CartesianCentering< CE, D, NC > > &pf, Field< T, D, M, CartesianCentering< CE, D, NC > > &A)
template<class T , unsigned D, class M >
void CalcParallelPeriodicDomain (const Field< T, D, M, Cell > &A, const ParallelPeriodicFace< T, D, M, Cell > &pf, NDIndex< D > &dest_slab, int &offset)
template<class T , unsigned D, class M >
void CalcParallelPeriodicDomain (const Field< T, D, M, Vert > &A, const ParallelPeriodicFace< T, D, M, Vert > &pf, NDIndex< D > &dest_slab, int &offset)
template<class T , unsigned D, class M >
void CalcParallelPeriodicDomain (const Field< T, D, M, Edge > &A, const ParallelPeriodicFace< T, D, M, Edge > &pf, NDIndex< D > &dest_slab, int &offset)
template<class T , unsigned D, class M , CenteringEnum * CE, unsigned NC>
void CalcParallelPeriodicDomain (const Field< T, D, M, CartesianCentering< CE, D, NC > > &A, const ParallelPeriodicFace< T, D, M, CartesianCentering< CE, D, NC > > &pf, NDIndex< D > &dest_slab, int &offset)
template<class T , unsigned D, class M >
void CalcParallelInterpolationDomain (const Field< T, D, M, Cell > &A, const ParallelInterpolationFace< T, D, M, Cell > &pf, NDIndex< D > &src_slab, int &offset)
template<class T >
void PETE_apply (const OpExtrapolate< T > &e, T &a, const T &b)
template<class T >
void PETE_apply (const OpExtrapolateComponent< T > &e, T &a, const T &b)
void PETE_apply (const OpExtrapolateComponent< char > &, char &, const char &)
void PETE_apply (const OpExtrapolateComponent< bool > &, bool &, const bool &)
void PETE_apply (const OpExtrapolateComponent< int > &, int &, const int &)
void PETE_apply (const OpExtrapolateComponent< unsigned > &, unsigned &, const unsigned &)
void PETE_apply (const OpExtrapolateComponent< short > &, short &, const short &)
void PETE_apply (const OpExtrapolateComponent< long > &, long &, const long &)
void PETE_apply (const OpExtrapolateComponent< float > &, float &, const float &)
void PETE_apply (const OpExtrapolateComponent< double > &, double &, const double &)
void PETE_apply (const OpExtrapolateComponent< std::complex< double > > &, std::complex< double > &, const std::complex< double > &)
template<class T , unsigned D, class M >
void ExtrapolateFaceBCApply (ExtrapolateFace< T, D, M, Cell > &ef, Field< T, D, M, Cell > &A)
template<class T , unsigned D, class M >
void ExtrapolateFaceBCApply (ExtrapolateFace< T, D, M, Vert > &ef, Field< T, D, M, Vert > &A)
template<class T , unsigned D, class M >
void ExtrapolateFaceBCApply (ExtrapolateFace< T, D, M, Edge > &ef, Field< T, D, M, Edge > &A)
template<class T , unsigned D, class M , CenteringEnum * CE, unsigned NC>
void ExtrapolateFaceBCApply (ExtrapolateFace< T, D, M, CartesianCentering< CE, D, NC > > &ef, Field< T, D, M, CartesianCentering< CE, D, NC > > &A)
template<class T , unsigned D, class M , class C >
void ExtrapolateFaceBCApply2 (const NDIndex< D > &dest, const NDIndex< D > &src, LField< T, D > &fill, LField< T, D > &from, const NDIndex< D > &from_alloc, ExtrapolateFace< T, D, M, C > &ef)
template<class T >
void PETE_apply (const OpExtrapolateAndZero< T > &e, T &a, const T &b)
template<class T >
void PETE_apply (const OpExtrapolateAndZeroComponent< T > &e, T &a, const T &b)
void PETE_apply (const OpExtrapolateAndZeroComponent< char > &, char &, const char &)
void PETE_apply (const OpExtrapolateAndZeroComponent< bool > &, bool &, const bool &)
void PETE_apply (const OpExtrapolateAndZeroComponent< int > &, int &, const int &)
void PETE_apply (const OpExtrapolateAndZeroComponent< unsigned > &, unsigned &, const unsigned &)
void PETE_apply (const OpExtrapolateAndZeroComponent< short > &, short &, const short &)
void PETE_apply (const OpExtrapolateAndZeroComponent< long > &, long &, const long &)
void PETE_apply (const OpExtrapolateAndZeroComponent< float > &, float &, const float &)
void PETE_apply (const OpExtrapolateAndZeroComponent< double > &, double &, const double &)
void PETE_apply (const OpExtrapolateAndZeroComponent< std::complex< double > > &, std::complex< double > &, const std::complex< double > &)
template<class T , class T1 >
void PETE_apply (const OpAssignComponent< T > &e, T &a, const T1 &b)
void PETE_apply (const OpAssignComponent< char > &, char &, const char &)
void PETE_apply (const OpAssignComponent< bool > &, bool &, const bool &)
void PETE_apply (const OpAssignComponent< int > &, int &, const int &)
void PETE_apply (const OpAssignComponent< unsigned > &, unsigned &, const unsigned &)
void PETE_apply (const OpAssignComponent< short > &, short &, const short &)
void PETE_apply (const OpAssignComponent< long > &, long &, const long &)
void PETE_apply (const OpAssignComponent< float > &, float &, const float &)
void PETE_apply (const OpAssignComponent< double > &, double &, const double &)
void PETE_apply (const OpAssignComponent< std::complex< double > > &, std::complex< double > &, const std::complex< double > &)
template<class T , unsigned D, class M >
void ExtrapolateAndZeroFaceBCApply (ExtrapolateAndZeroFace< T, D, M, Cell > &ef, Field< T, D, M, Cell > &A)
template<class T , unsigned D, class M >
void ExtrapolateAndZeroFaceBCApply (ExtrapolateAndZeroFace< T, D, M, Vert > &ef, Field< T, D, M, Vert > &A)
template<class T , unsigned D, class M >
void ExtrapolateAndZeroFaceBCApply (ExtrapolateAndZeroFace< T, D, M, Edge > &ef, Field< T, D, M, Edge > &A)
template<class T , unsigned D, class M , CenteringEnum * CE, unsigned NC>
void ExtrapolateAndZeroFaceBCApply (ExtrapolateAndZeroFace< T, D, M, CartesianCentering< CE, D, NC > > &ef, Field< T, D, M, CartesianCentering< CE, D, NC > > &A)
template<class T , unsigned D, class M , class C >
void ExtrapolateAndZeroFaceBCApply2 (const NDIndex< D > &dest, const NDIndex< D > &src, LField< T, D > &fill, LField< T, D > &from, const NDIndex< D > &from_alloc, ExtrapolateAndZeroFace< T, D, M, C > &ef)
template<class T , unsigned D, class M , class C >
void ExtrapolateAndZeroFaceBCApply3 (const NDIndex< D > &dest, LField< T, D > &fill, ExtrapolateAndZeroFace< T, D, M, C > &ef)
template<class T >
void PETE_apply (const OpBCFunctionEq< T > &e, T &a, T &b)
template<class T , unsigned D, class M >
void FunctionFaceBCApply (FunctionFace< T, D, M, Cell > &ff, Field< T, D, M, Cell > &A)
template<class T , unsigned D, class M >
void FunctionFaceBCApply (FunctionFace< T, D, M, Vert > &ff, Field< T, D, M, Vert > &A)
template<class T , unsigned D, class M >
void FunctionFaceBCApply (FunctionFace< T, D, M, Edge > &ff, Field< T, D, M, Edge > &A)
template<class T , unsigned D, class M , CenteringEnum * CE, unsigned NC>
void FunctionFaceBCApply (FunctionFace< T, D, M, CartesianCentering< CE, D, NC > > &ff, Field< T, D, M, CartesianCentering< CE, D, NC > > &A)
template<class T >
void PETE_apply (const OpBCFunctionEqComponent< T > &e, T &a, const T &b)
void PETE_apply (const OpBCFunctionEqComponent< char > &, char &, const char &)
void PETE_apply (const OpBCFunctionEqComponent< bool > &, bool &, const bool &)
void PETE_apply (const OpBCFunctionEqComponent< int > &, int &, const int &)
void PETE_apply (const OpBCFunctionEqComponent< unsigned > &, unsigned &, const unsigned &)
void PETE_apply (const OpBCFunctionEqComponent< short > &, short &, const short &)
void PETE_apply (const OpBCFunctionEqComponent< long > &, long &, const long &)
void PETE_apply (const OpBCFunctionEqComponent< float > &, float &, const float &)
void PETE_apply (const OpBCFunctionEqComponent< double > &, double &, const double &)
void PETE_apply (const OpBCFunctionEqComponent< std::complex< double > > &, std::complex< double > &, const std::complex< double > &)
template<class T , unsigned D, class M >
void ComponentFunctionFaceBCApply (ComponentFunctionFace< T, D, M, Cell > &ff, Field< T, D, M, Cell > &A)
template<class T , unsigned D, class M >
void ComponentFunctionFaceBCApply (ComponentFunctionFace< T, D, M, Vert > &ff, Field< T, D, M, Vert > &A)
template<class T , unsigned D, class M >
void ComponentFunctionFaceBCApply (ComponentFunctionFace< T, D, M, Edge > &ff, Field< T, D, M, Edge > &A)
template<class T , unsigned D, class M , CenteringEnum * CE, unsigned NC>
void ComponentFunctionFaceBCApply (ComponentFunctionFace< T, D, M, CartesianCentering< CE, D, NC > > &ff, Field< T, D, M, CartesianCentering< CE, D, NC > > &A)
template<class T >
void PETE_apply (const EurekaAssign< T > &e, T &a, const T &b)
template<unsigned int D>
NDIndex< D > calcEurekaDomain (const NDIndex< D > &realDomain, int face, const GuardCellSizes< D > &gc)
template<class T , unsigned D, class M , class C >
void LinearExtrapolateFaceBCApply (LinearExtrapolateFace< T, D, M, C > &ef, Field< T, D, M, C > &A)
template<class T , unsigned D, class M , class C >
void LinearExtrapolateFaceBCApply2 (const NDIndex< D > &dest, const NDIndex< D > &src1, const NDIndex< D > &src2, LField< T, D > &fill, LinearExtrapolateFace< T, D, M, C > &, int slopeMultipplier)
template<class T , unsigned D, class M , class C >
void ComponentLinearExtrapolateFaceBCApply (ComponentLinearExtrapolateFace< T, D, M, C > &ef, Field< T, D, M, C > &A)
template<class T , unsigned D, class M , class C >
void ComponentLinearExtrapolateFaceBCApply2 (const NDIndex< D > &dest, const NDIndex< D > &src1, const NDIndex< D > &src2, LField< T, D > &fill, ComponentLinearExtrapolateFace< T, D, M, C > &ef, int slopeMultipplier)
Macro Definition Documentation
COMPONENT_APPLY_BUILTIN
#define COMPONENT_APPLY_BUILTIN (OP, T)
Value:
inline void PETE_apply(const OP<T>&, T&, const T&)                          \
{                                                                           \
  ERRORMSG("Component boundary condition on a scalar (T)." << endl);        \
  Ippl::abort();                                                           \
}
Definition at line 40 of file BCond.hpp.
Function Documentation
calcEurekaDomain()
template<unsigned int D> NDIndex<D> calcEurekaDomain (const NDIndex< D > & realDomain, int face, const GuardCellSizes< D > & gc) inline
Definition at line 5582 of file BCond.hpp.
References AddGuardCells(), GuardCellSizes< Dim >::left(), max(), min(), PAssert_GE, PAssert_LE, and GuardCellSizes< Dim >::right().
CalcParallelInterpolationDomain()
template<class T , unsigned D, class M > void CalcParallelInterpolationDomain (const Field< T, D, M, Cell > & A, const ParallelInterpolationFace< T, D, M, Cell > & pf, NDIndex< D > & src_slab, int & offset) inline
Definition at line 1987 of file BCond.hpp.
References BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::leftGuard(), Index::length(), max(), and min().
Referenced by ParallelInterpolationFace< T, D, M, C >::apply().
CalcParallelPeriodicDomain() [1/4]
template<class T , unsigned D, class M > void CalcParallelPeriodicDomain (const Field< T, D, M, Cell > & A, const ParallelPeriodicFace< T, D, M, Cell > & pf, NDIndex< D > & dest_slab, int & offset) inline
Definition at line 1036 of file BCond.hpp.
References BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::leftGuard(), Index::length(), max(), and min().
Referenced by ParallelPeriodicFace< T, D, M, C >::apply().
CalcParallelPeriodicDomain() [2/4]
template<class T , unsigned D, class M > void CalcParallelPeriodicDomain (const Field< T, D, M, Vert > & A, const ParallelPeriodicFace< T, D, M, Vert > & pf, NDIndex< D > & dest_slab, int & offset) inline
Definition at line 1084 of file BCond.hpp.
References BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::leftGuard(), Index::length(), max(), min(), and BareField< T, Dim >::rightGuard().
CalcParallelPeriodicDomain() [3/4]
template<class T , unsigned D, class M > void CalcParallelPeriodicDomain (const Field< T, D, M, Edge > & A, const ParallelPeriodicFace< T, D, M, Edge > & pf, NDIndex< D > & dest_slab, int & offset) inline
Definition at line 1132 of file BCond.hpp.
References BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::leftGuard(), Index::length(), max(), min(), and BareField< T, Dim >::rightGuard().
CalcParallelPeriodicDomain() [4/4]
template<class T , unsigned D, class M , CenteringEnum * CE, unsigned NC> void CalcParallelPeriodicDomain (const Field< T, D, M, CartesianCentering< CE, D, NC > > & A, const ParallelPeriodicFace< T, D, M, CartesianCentering< CE, D, NC > > & pf, NDIndex< D > & dest_slab, int & offset) inline
Definition at line 1180 of file BCond.hpp.
References Physics::c, CELL, endl(), ERRORMSG, Index::length(), max(), and min().
ComponentFunctionFaceBCApply() [1/4]
template<class T , unsigned D, class M > void ComponentFunctionFaceBCApply (ComponentFunctionFace< T, D, M, Cell > & ff, Field< T, D, M, Cell > & A)
Definition at line 5004 of file BCond.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), ComponentFunctionFace< T, D, M, C >::Func, LField< T, Dim >::getAllocated(), BCondBase< T, D, M, C >::getComponent(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), Index::max(), min(), Index::min(), NDIndex< Dim >::plugBase(), BareField< T, Dim >::rightGuard(), NDIndex< Dim >::touches(), and LField< T, Dim >::Uncompress().
Referenced by ComponentFunctionFace< T, D, M, C >::apply().
ComponentFunctionFaceBCApply() [2/4]
template<class T , unsigned D, class M > void ComponentFunctionFaceBCApply (ComponentFunctionFace< T, D, M, Vert > & ff, Field< T, D, M, Vert > & A)
Definition at line 5091 of file BCond.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), ComponentFunctionFace< T, D, M, C >::Func, LField< T, Dim >::getAllocated(), BCondBase< T, D, M, C >::getComponent(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), Index::max(), min(), Index::min(), NDIndex< Dim >::plugBase(), BareField< T, Dim >::rightGuard(), NDIndex< Dim >::touches(), and LField< T, Dim >::Uncompress().
ComponentFunctionFaceBCApply() [3/4]
template<class T , unsigned D, class M > void ComponentFunctionFaceBCApply (ComponentFunctionFace< T, D, M, Edge > & ff, Field< T, D, M, Edge > & A)
Definition at line 5182 of file BCond.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), ComponentFunctionFace< T, D, M, C >::Func, LField< T, Dim >::getAllocated(), BCondBase< T, D, M, C >::getComponent(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), Index::max(), min(), Index::min(), NDIndex< Dim >::plugBase(), BareField< T, Dim >::rightGuard(), NDIndex< Dim >::touches(), and LField< T, Dim >::Uncompress().
ComponentFunctionFaceBCApply() [4/4]
template<class T , unsigned D, class M , CenteringEnum * CE, unsigned NC> void ComponentFunctionFaceBCApply (ComponentFunctionFace< T, D, M, CartesianCentering< CE, D, NC > > & ff, Field< T, D, M, CartesianCentering< CE, D, NC > > & A)
Definition at line 5270 of file BCond.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), CELL, BareField< T, Dim >::end_if(), endl(), ERRORMSG, LField< T, Dim >::getAllocated(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), max(), min(), Index::min(), NDIndex< Dim >::plugBase(), NDIndex< Dim >::touches(), and LField< T, Dim >::Uncompress().
ComponentLinearExtrapolateFaceBCApply()
template<class T , unsigned D, class M , class C > void ComponentLinearExtrapolateFaceBCApply (ComponentLinearExtrapolateFace< T, D, M, C > & ef, Field< T, D, M, C > & A)
Definition at line 5989 of file BCond.hpp.
References AddGuardCells(), BareField< T, Dim >::begin_if(), ComponentLinearExtrapolateFaceBCApply2(), BareField< T, Dim >::end_if(), LField< T, Dim >::getAllocated(), BareField< T, Dim >::getDomain(), BareField< T, Dim >::getGuardCellSizes(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), min(), BareField< T, Dim >::rightGuard(), and NDIndex< Dim >::touches().
Referenced by ComponentLinearExtrapolateFace< T, D, M, C >::apply().
ComponentLinearExtrapolateFaceBCApply2()
template<class T , unsigned D, class M , class C > void ComponentLinearExtrapolateFaceBCApply2 (const NDIndex< D > & dest, const NDIndex< D > & src1, const NDIndex< D > & src2, LField< T, D > & fill, ComponentLinearExtrapolateFace< T, D, M, C > & ef, int slopeMultipplier) inline
Definition at line 5945 of file BCond.hpp.
References LField< T, Dim >::begin(), LField< T, Dim >::end(), and LField< T, Dim >::IsCompressed().
Referenced by ComponentLinearExtrapolateFaceBCApply().
ExtrapolateAndZeroFaceBCApply() [1/4]
template<class T , unsigned D, class M > void ExtrapolateAndZeroFaceBCApply (ExtrapolateAndZeroFace< T, D, M, Cell > & ef, Field< T, D, M, Cell > & A)
Definition at line 3756 of file BCond.hpp.
References AddGuardCells(), BareField< T, Dim >::begin_if(), NDIndex< Dim >::contains(), BareField< T, Dim >::end_if(), ExtrapolateAndZeroFaceBCApply2(), LField< T, Dim >::getAllocated(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), Index::max(), min(), Index::min(), BareField< T, Dim >::rightGuard(), and NDIndex< Dim >::touches().
Referenced by ExtrapolateAndZeroFace< T, D, M, C >::apply().
ExtrapolateAndZeroFaceBCApply() [2/4]
template<class T , unsigned D, class M > void ExtrapolateAndZeroFaceBCApply (ExtrapolateAndZeroFace< T, D, M, Vert > & ef, Field< T, D, M, Vert > & A)
Definition at line 3889 of file BCond.hpp.
References AddGuardCells(), BareField< T, Dim >::begin_if(), NDIndex< Dim >::contains(), BareField< T, Dim >::end_if(), ExtrapolateAndZeroFaceBCApply2(), ExtrapolateAndZeroFaceBCApply3(), LField< T, Dim >::getAllocated(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), min(), BareField< T, Dim >::rightGuard(), and NDIndex< Dim >::touches().
ExtrapolateAndZeroFaceBCApply() [3/4]
template<class T , unsigned D, class M > void ExtrapolateAndZeroFaceBCApply (ExtrapolateAndZeroFace< T, D, M, Edge > & ef, Field< T, D, M, Edge > & A)
Definition at line 4053 of file BCond.hpp.
References AddGuardCells(), BareField< T, Dim >::begin_if(), NDIndex< Dim >::contains(), BareField< T, Dim >::end_if(), ExtrapolateAndZeroFaceBCApply2(), ExtrapolateAndZeroFaceBCApply3(), LField< T, Dim >::getAllocated(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), min(), BareField< T, Dim >::rightGuard(), and NDIndex< Dim >::touches().
ExtrapolateAndZeroFaceBCApply() [4/4]
template<class T , unsigned D, class M , CenteringEnum * CE, unsigned NC> void ExtrapolateAndZeroFaceBCApply (ExtrapolateAndZeroFace< T, D, M, CartesianCentering< CE, D, NC > > & ef, Field< T, D, M, CartesianCentering< CE, D, NC > > & A)
Definition at line 4214 of file BCond.hpp.
References AddGuardCells(), BareField< T, Dim >::begin_if(), Physics::c, CELL, NDIndex< Dim >::contains(), BareField< T, Dim >::end_if(), endl(), ERRORMSG, ExtrapolateAndZeroFaceBCApply2(), ExtrapolateAndZeroFaceBCApply3(), LField< T, Dim >::getAllocated(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), max(), Index::max(), min(), and NDIndex< Dim >::touches().
ExtrapolateAndZeroFaceBCApply2()
template<class T , unsigned D, class M , class C > void ExtrapolateAndZeroFaceBCApply2 (const NDIndex< D > & dest, const NDIndex< D > & src, LField< T, D > & fill, LField< T, D > & from, const NDIndex< D > & from_alloc, ExtrapolateAndZeroFace< T, D, M, C > & ef) inline
Definition at line 3620 of file BCond.hpp.
References a, BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BCondBase< T, D, M, C >::getComponent(), LField< T, Dim >::getCompressedData(), ExtrapolateAndZeroFace< T, D, M, C >::getOffset(), ExtrapolateAndZeroFace< T, D, M, C >::getSlope(), NDIndex< Dim >::intersect(), LField< T, Dim >::IsCompressed(), PETE_apply(), NDIndex< Dim >::plugBase(), Attrib::Legacy::Distribution::T, and LField< T, Dim >::Uncompress().
Referenced by ExtrapolateAndZeroFaceBCApply().
ExtrapolateAndZeroFaceBCApply3()
template<class T , unsigned D, class M , class C > void ExtrapolateAndZeroFaceBCApply3 (const NDIndex< D > & dest, LField< T, D > & fill, ExtrapolateAndZeroFace< T, D, M, C > & ef) inline
Definition at line 3688 of file BCond.hpp.
References a, LField< T, Dim >::begin(), BCondBase< T, D, M, C >::getComponent(), LField< T, Dim >::getCompressedData(), LField< T, Dim >::IsCompressed(), PETE_apply(), Attrib::Legacy::Distribution::T, and LField< T, Dim >::Uncompress().
Referenced by ExtrapolateAndZeroFaceBCApply().
ExtrapolateFaceBCApply() [1/4]
template<class T , unsigned D, class M > void ExtrapolateFaceBCApply (ExtrapolateFace< T, D, M, Cell > & ef, Field< T, D, M, Cell > & A)
Definition at line 2878 of file BCond.hpp.
References AddGuardCells(), BareField< T, Dim >::begin_if(), NDIndex< Dim >::contains(), BareField< T, Dim >::end_if(), ExtrapolateFaceBCApply2(), LField< T, Dim >::getAllocated(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), Index::max(), min(), Index::min(), BareField< T, Dim >::rightGuard(), and NDIndex< Dim >::touches().
Referenced by ExtrapolateFace< T, D, M, C >::apply().
ExtrapolateFaceBCApply() [2/4]
template<class T , unsigned D, class M > void ExtrapolateFaceBCApply (ExtrapolateFace< T, D, M, Vert > & ef, Field< T, D, M, Vert > & A)
Definition at line 3010 of file BCond.hpp.
References AddGuardCells(), BareField< T, Dim >::begin_if(), NDIndex< Dim >::contains(), BareField< T, Dim >::end_if(), ExtrapolateFaceBCApply2(), LField< T, Dim >::getAllocated(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), Index::max(), min(), Index::min(), BareField< T, Dim >::rightGuard(), and NDIndex< Dim >::touches().
ExtrapolateFaceBCApply() [3/4]
template<class T , unsigned D, class M > void ExtrapolateFaceBCApply (ExtrapolateFace< T, D, M, Edge > & ef, Field< T, D, M, Edge > & A)
Definition at line 3144 of file BCond.hpp.
References AddGuardCells(), BareField< T, Dim >::begin_if(), NDIndex< Dim >::contains(), BareField< T, Dim >::end_if(), ExtrapolateFaceBCApply2(), LField< T, Dim >::getAllocated(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), Index::max(), min(), Index::min(), BareField< T, Dim >::rightGuard(), and NDIndex< Dim >::touches().
ExtrapolateFaceBCApply() [4/4]
template<class T , unsigned D, class M , CenteringEnum * CE, unsigned NC> void ExtrapolateFaceBCApply (ExtrapolateFace< T, D, M, CartesianCentering< CE, D, NC > > & ef, Field< T, D, M, CartesianCentering< CE, D, NC > > & A)
Definition at line 3273 of file BCond.hpp.
References AddGuardCells(), BareField< T, Dim >::begin_if(), Physics::c, CELL, NDIndex< Dim >::contains(), BareField< T, Dim >::end_if(), endl(), ERRORMSG, ExtrapolateFaceBCApply2(), LField< T, Dim >::getAllocated(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), max(), Index::max(), min(), and NDIndex< Dim >::touches().
ExtrapolateFaceBCApply2()
template<class T , unsigned D, class M , class C > void ExtrapolateFaceBCApply2 (const NDIndex< D > & dest, const NDIndex< D > & src, LField< T, D > & fill, LField< T, D > & from, const NDIndex< D > & from_alloc, ExtrapolateFace< T, D, M, C > & ef) inline
Definition at line 2807 of file BCond.hpp.
References a, BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BCondBase< T, D, M, C >::getComponent(), LField< T, Dim >::getCompressedData(), ExtrapolateFace< T, D, M, C >::getOffset(), ExtrapolateFace< T, D, M, C >::getSlope(), NDIndex< Dim >::intersect(), LField< T, Dim >::IsCompressed(), PETE_apply(), NDIndex< Dim >::plugBase(), Attrib::Legacy::Distribution::T, and LField< T, Dim >::Uncompress().
Referenced by ExtrapolateFaceBCApply().
FunctionFaceBCApply() [1/4]
template<class T , unsigned D, class M > void FunctionFaceBCApply (FunctionFace< T, D, M, Cell > & ff, Field< T, D, M, Cell > & A)
Definition at line 4553 of file BCond.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), FunctionFace< T, D, M, C >::Func, LField< T, Dim >::getAllocated(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), Index::max(), min(), Index::min(), NDIndex< Dim >::plugBase(), BareField< T, Dim >::rightGuard(), NDIndex< Dim >::touches(), and LField< T, Dim >::Uncompress().
Referenced by FunctionFace< T, D, M, C >::apply().
FunctionFaceBCApply() [2/4]
template<class T , unsigned D, class M > void FunctionFaceBCApply (FunctionFace< T, D, M, Vert > & ff, Field< T, D, M, Vert > & A)
Definition at line 4638 of file BCond.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), FunctionFace< T, D, M, C >::Func, LField< T, Dim >::getAllocated(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), Index::max(), min(), Index::min(), NDIndex< Dim >::plugBase(), BareField< T, Dim >::rightGuard(), NDIndex< Dim >::touches(), and LField< T, Dim >::Uncompress().
FunctionFaceBCApply() [3/4]
template<class T , unsigned D, class M > void FunctionFaceBCApply (FunctionFace< T, D, M, Edge > & ff, Field< T, D, M, Edge > & A)
Definition at line 4727 of file BCond.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), FunctionFace< T, D, M, C >::Func, LField< T, Dim >::getAllocated(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), max(), Index::max(), min(), Index::min(), NDIndex< Dim >::plugBase(), BareField< T, Dim >::rightGuard(), NDIndex< Dim >::touches(), and LField< T, Dim >::Uncompress().
FunctionFaceBCApply() [4/4]
template<class T , unsigned D, class M , CenteringEnum * CE, unsigned NC> void FunctionFaceBCApply (FunctionFace< T, D, M, CartesianCentering< CE, D, NC > > & ff, Field< T, D, M, CartesianCentering< CE, D, NC > > & A)
Definition at line 4813 of file BCond.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), Physics::c, CELL, BareField< T, Dim >::end_if(), endl(), ERRORMSG, LField< T, Dim >::getAllocated(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), max(), min(), NDIndex< Dim >::plugBase(), NDIndex< Dim >::touches(), and LField< T, Dim >::Uncompress().
InterpolationFaceBCApply()
template<class T , unsigned D, class M > void InterpolationFaceBCApply (InterpolationFace< T, D, M, Cell > & pf, Field< T, D, M, Cell > & A)
Definition at line 592 of file BCond.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), LField< T, Dim >::getAllocated(), BCondBase< T, D, M, C >::getComponent(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), Index::length(), max(), min(), NDIndex< Dim >::plugBase(), NDIndex< Dim >::touches(), and LField< T, Dim >::Uncompress().
Referenced by InterpolationFace< T, D, M, C >::apply().
LinearExtrapolateFaceBCApply()
template<class T , unsigned D, class M , class C > void LinearExtrapolateFaceBCApply (LinearExtrapolateFace< T, D, M, C > & ef, Field< T, D, M, C > & A)
Definition at line 5802 of file BCond.hpp.
References AddGuardCells(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), LField< T, Dim >::getAllocated(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), LinearExtrapolateFaceBCApply2(), max(), min(), BareField< T, Dim >::rightGuard(), and NDIndex< Dim >::touches().
Referenced by LinearExtrapolateFace< T, D, M, C >::apply().
LinearExtrapolateFaceBCApply2()
template<class T , unsigned D, class M , class C > void LinearExtrapolateFaceBCApply2 (const NDIndex< D > & dest, const NDIndex< D > & src1, const NDIndex< D > & src2, LField< T, D > & fill, LinearExtrapolateFace< T, D, M, C > & , int slopeMultipplier) inline
Definition at line 5763 of file BCond.hpp.
References LField< T, Dim >::begin(), LField< T, Dim >::end(), and LField< T, Dim >::IsCompressed().
Referenced by LinearExtrapolateFaceBCApply().
PeriodicFaceBCApply() [1/4]
template<class T , unsigned D, class M > void PeriodicFaceBCApply (PeriodicFace< T, D, M, Cell > & pf, Field< T, D, M, Cell > & A)
Definition at line 495 of file BCond.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), LField< T, Dim >::getAllocated(), BCondBase< T, D, M, C >::getComponent(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), Index::length(), max(), min(), NDIndex< Dim >::plugBase(), NDIndex< Dim >::touches(), and LField< T, Dim >::Uncompress().
Referenced by PeriodicFace< T, D, M, C >::apply().
PeriodicFaceBCApply() [2/4]
template<class T , unsigned D, class M > void PeriodicFaceBCApply (PeriodicFace< T, D, M, Vert > & pf, Field< T, D, M, Vert > & A)
Definition at line 688 of file BCond.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), LField< T, Dim >::getAllocated(), BCondBase< T, D, M, C >::getComponent(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), Index::length(), max(), min(), NDIndex< Dim >::plugBase(), BareField< T, Dim >::rightGuard(), NDIndex< Dim >::touches(), and LField< T, Dim >::Uncompress().
PeriodicFaceBCApply() [3/4]
template<class T , unsigned D, class M > void PeriodicFaceBCApply (PeriodicFace< T, D, M, Edge > & pf, Field< T, D, M, Edge > & A)
Definition at line 786 of file BCond.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), BareField< T, Dim >::end_if(), LField< T, Dim >::getAllocated(), BCondBase< T, D, M, C >::getComponent(), BareField< T, Dim >::getDomain(), BCondBase< T, D, M, C >::getFace(), BareField< T, Dim >::getGuardCellSizes(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), BareField< T, Dim >::leftGuard(), Index::length(), max(), min(), NDIndex< Dim >::plugBase(), BareField< T, Dim >::rightGuard(), NDIndex< Dim >::touches(), and LField< T, Dim >::Uncompress().
PeriodicFaceBCApply() [4/4]
template<class T , unsigned D, class M , CenteringEnum * CE, unsigned NC> void PeriodicFaceBCApply (PeriodicFace< T, D, M, CartesianCentering< CE, D, NC > > & pf, Field< T, D, M, CartesianCentering< CE, D, NC > > & A)
Definition at line 880 of file BCond.hpp.
References AddGuardCells(), BrickExpression< Dim, LHS, RHS, OP >::apply(), LField< T, Dim >::begin(), BareField< T, Dim >::begin_if(), Physics::c, CELL, BareField< T, Dim >::end_if(), endl(), ERRORMSG, LField< T, Dim >::getAllocated(), LField< T, Dim >::getOwned(), NDIndex< Dim >::intersect(), Index::length(), max(), min(), NDIndex< Dim >::plugBase(), Attrib::Legacy::Distribution::T, NDIndex< Dim >::touches(), and LField< T, Dim >::Uncompress().
PETE_apply() [1/66]
template<class T > void PETE_apply (const OpPeriodic< T > & , T & a, const T & b) inline
Definition at line 353 of file BCond.hpp.
References a.
Referenced by BrickExpLoop< LHS, RHS, OP, Dim >::apply(), TSV_MetaUnary< Vektor< T1, D >, OP >::apply(), TSV_MetaAssign< Vektor< T1, D >, Vektor< T2, D >, OP >::apply(), TSV_MetaBinary< Vektor< T1, D >, Vektor< T2, D >, OP >::apply(), TSV_MetaAssignScalar< Vektor< T1, D >, T2, OP >::apply(), TSV_MetaBinaryScalar< Vektor< T1, D >, T2, OP >::apply(), TSV_MetaUnary< Vektor< T1, 1 >, OP >::apply(), TSV_MetaAssign< Vektor< T1, 1 >, Vektor< T2, 1 >, OP >::apply(), TSV_MetaBinaryScalar< T1, Vektor< T2, D >, OP >::apply(), BrickExpLoop< LHS, RHS, OP, 1U >::apply(), TSV_MetaAssignScalar< Vektor< T1, 1 >, T2, OP >::apply(), TSV_MetaUnary< Vektor< T1, 2 >, OP >::apply(), BrickExpLoop< LHS, RHS, OP, 2U >::apply(), TSV_MetaBinary< Vektor< T1, 1 >, Vektor< T2, 1 >, OP >::apply(), TSV_MetaAssign< Vektor< T1, 2 >, Vektor< T2, 2 >, OP >::apply(), TSV_MetaUnary< Vektor< T1, 3 >, OP >::apply(), TSV_MetaBinaryScalar< Vektor< T1, 1 >, T2, OP >::apply(), TSV_MetaAssignScalar< Vektor< T1, 2 >, T2, OP >::apply(), BrickExpLoop< LHS, RHS, OP, 3U >::apply(), TSV_MetaBinaryScalar< T1, Vektor< T2, 1 >, OP >::apply(), TSV_MetaUnary< Tenzor< T1, D >, OP >::apply(), TSV_MetaAssign< Vektor< T1, 3 >, Vektor< T2, 3 >, OP >::apply(), TSV_MetaBinary< Vektor< T1, 2 >, Vektor< T2, 2 >, OP >::apply(), TSV_MetaAssignScalar< Vektor< T1, 3 >, T2, OP >::apply(), TSV_MetaUnary< Tenzor< T1, 1 >, OP >::apply(), TSV_MetaBinaryScalar< Vektor< T1, 2 >, T2, OP >::apply(), TSV_MetaAssign< Tenzor< T1, D >, Tenzor< T2, D >, OP >::apply(), TSV_MetaBinaryScalar< T1, Vektor< T2, 2 >, OP >::apply(), TSV_MetaUnary< Tenzor< T1, 2 >, OP >::apply(), TSV_MetaAssignScalar< Tenzor< T1, D >, T2, OP >::apply(), TSV_MetaBinary< Vektor< T1, 3 >, Vektor< T2, 3 >, OP >::apply(), TSV_MetaUnary< Tenzor< T1, 3 >, OP >::apply(), TSV_MetaAssign< Tenzor< T1, 1 >, Tenzor< T2, 1 >, OP >::apply(), TSV_MetaBinaryScalar< Vektor< T1, 3 >, T2, OP >::apply(), TSV_MetaAssignScalar< Tenzor< T1, 1 >, T2, OP >::apply(), TSV_MetaBinaryScalar< T1, Vektor< T2, 3 >, OP >::apply(), TSV_MetaUnary< SymTenzor< T1, D >, OP >::apply(), TSV_MetaAssign< Tenzor< T1, 2 >, Tenzor< T2, 2 >, OP >::apply(), TSV_MetaBinary< Tenzor< T1, D >, Tenzor< T2, D >, OP >::apply(), TSV_MetaAssignScalar< Tenzor< T1, 2 >, T2, OP >::apply(), TSV_MetaUnary< SymTenzor< T1, 1 >, OP >::apply(), TSV_MetaBinaryScalar< Tenzor< T1, D >, T2, OP >::apply(), TSV_MetaUnary< SymTenzor< T1, 2 >, OP >::apply(), TSV_MetaAssign< Tenzor< T1, 3 >, Tenzor< T2, 3 >, OP >::apply(), TSV_MetaBinaryScalar< T1, Tenzor< T2, D >, OP >::apply(), TSV_MetaAssignScalar< Tenzor< T1, 3 >, T2, OP >::apply(), TSV_MetaUnary< SymTenzor< T1, 3 >, OP >::apply(), TSV_MetaBinary< Tenzor< T1, 1 >, Tenzor< T2, 1 >, OP >::apply(), TSV_MetaBinaryScalar< Tenzor< T1, 1 >, T2, OP >::apply(), TSV_MetaUnary< AntiSymTenzor< T1, D >, OP >::apply(), TSV_MetaAssign< SymTenzor< T1, D >, SymTenzor< T2, D >, OP >::apply(), TSV_MetaBinaryScalar< T1, Tenzor< T2, 1 >, OP >::apply(), TSV_MetaAssignScalar< SymTenzor< T1, D >, T2, OP >::apply(), TSV_MetaUnary< AntiSymTenzor< T1, 1 >, OP >::apply(), TSV_MetaBinary< Tenzor< T1, 2 >, Tenzor< T2, 2 >, OP >::apply(), TSV_MetaAssign< SymTenzor< T1, 1 >, SymTenzor< T2, 1 >, OP >::apply(), TSV_MetaUnary< AntiSymTenzor< T1, 2 >, OP >::apply(), TSV_MetaBinaryScalar< Tenzor< T1, 2 >, T2, OP >::apply(), TSV_MetaAssignScalar< SymTenzor< T1, 1 >, T2, OP >::apply(), TSV_MetaBinaryScalar< T1, Tenzor< T2, 2 >, OP >::apply(), TSV_MetaUnary< AntiSymTenzor< T1, 3 >, OP >::apply(), TSV_MetaAssign< SymTenzor< T1, 2 >, SymTenzor< T2, 2 >, OP >::apply(), TSV_MetaAssignScalar< SymTenzor< T1, 2 >, T2, OP >::apply(), TSV_MetaBinary< Tenzor< T1, 3 >, Tenzor< T2, 3 >, OP >::apply(), TSV_MetaAssign< SymTenzor< T1, 3 >, SymTenzor< T2, 3 >, OP >::apply(), TSV_MetaBinaryScalar< Tenzor< T1, 3 >, T2, OP >::apply(), TSV_MetaAssignScalar< SymTenzor< T1, 3 >, T2, OP >::apply(), TSV_MetaBinaryScalar< T1, Tenzor< T2, 3 >, OP >::apply(), TSV_MetaAssign< AntiSymTenzor< T1, D >, AntiSymTenzor< T2, D >, OP >::apply(), TSV_MetaAssignScalar< AntiSymTenzor< T1, D >, T2, OP >::apply(), TSV_MetaBinary< SymTenzor< T1, D >, SymTenzor< T2, D >, OP >::apply(), TSV_MetaBinaryScalar< SymTenzor< T1, D >, T2, OP >::apply(), TSV_MetaBinaryScalar< T1, SymTenzor< T2, D >, OP >::apply(), TSV_MetaAssign< AntiSymTenzor< T1, 2 >, AntiSymTenzor< T2, 2 >, OP >::apply(), TSV_MetaAssignScalar< AntiSymTenzor< T1, 2 >, T2, OP >::apply(), TSV_MetaBinary< SymTenzor< T1, 1 >, SymTenzor< T2, 1 >, OP >::apply(), TSV_MetaBinaryScalar< SymTenzor< T1, 1 >, T2, OP >::apply(), TSV_MetaAssign< AntiSymTenzor< T1, 3 >, AntiSymTenzor< T2, 3 >, OP >::apply(), TSV_MetaBinaryScalar< T1, SymTenzor< T2, 1 >, OP >::apply(), TSV_MetaAssignScalar< AntiSymTenzor< T1, 3 >, T2, OP >::apply(), TSV_MetaBinary< SymTenzor< T1, 2 >, SymTenzor< T2, 2 >, OP >::apply(), TSV_MetaBinaryScalar< SymTenzor< T1, 2 >, T2, OP >::apply(), TSV_MetaBinaryScalar< T1, SymTenzor< T2, 2 >, OP >::apply(), TSV_MetaBinary< SymTenzor< T1, 3 >, SymTenzor< T2, 3 >, OP >::apply(), TSV_MetaBinaryScalar< SymTenzor< T1, 3 >, T2, OP >::apply(), TSV_MetaBinaryScalar< T1, SymTenzor< T2, 3 >, OP >::apply(), TSV_MetaBinary< SymTenzor< T1, D >, Tenzor< T2, D >, OP >::apply(), TSV_MetaBinary< Tenzor< T1, D >, SymTenzor< T2, D >, OP >::apply(), TSV_MetaBinary< AntiSymTenzor< T1, D >, AntiSymTenzor< T2, D >, OP >::apply(), TSV_MetaBinaryScalar< AntiSymTenzor< T1, D >, T2, OP >::apply(), TSV_MetaBinaryScalar< T1, AntiSymTenzor< T2, D >, OP >::apply(), TSV_MetaBinary< AntiSymTenzor< T1, 2 >, AntiSymTenzor< T2, 2 >, OP >::apply(), TSV_MetaBinaryScalar< AntiSymTenzor< T1, 2 >, T2, OP >::apply(), TSV_MetaBinaryScalar< T1, AntiSymTenzor< T2, 2 >, OP >::apply(), TSV_MetaBinary< AntiSymTenzor< T1, 3 >, AntiSymTenzor< T2, 3 >, OP >::apply(), TSV_MetaBinaryScalar< AntiSymTenzor< T1, 3 >, T2, OP >::apply(), TSV_MetaBinaryScalar< T1, AntiSymTenzor< T2, 3 >, OP >::apply(), assign(), ExtrapolateAndZeroFaceBCApply2(), ExtrapolateAndZeroFaceBCApply3(), ExtrapolateFaceBCApply2(), IndexedLocalAssign(), IndexedReceive(), DiscField< Dim >::read(), reduce(), reduce_masked(), Reduction(), scatter(), and TryCompressLHS().
PETE_apply() [2/66]
template<class T > void PETE_apply (const OpPeriodicComponent< T > & e, T & a, const T & b) inline
Definition at line 364 of file BCond.hpp.
References a, and Physics::e.
PETE_apply() [3/66]
void PETE_apply (const OpPeriodicComponent< char > & , char & , const char &) inline
Definition at line 373 of file BCond.hpp.
PETE_apply() [4/66]
void PETE_apply (const OpPeriodicComponent< bool > & , bool & , const bool &) inline
Definition at line 374 of file BCond.hpp.
PETE_apply() [5/66]
void PETE_apply (const OpPeriodicComponent< int > & , int & , const int &) inline
Definition at line 375 of file BCond.hpp.
PETE_apply() [6/66]
void PETE_apply (const OpPeriodicComponent< unsigned > & , unsigned & , const unsigned &) inline
Definition at line 376 of file BCond.hpp.
PETE_apply() [7/66]
void PETE_apply (const OpPeriodicComponent< short > & , short & , const short &) inline
Definition at line 377 of file BCond.hpp.
PETE_apply() [8/66]
void PETE_apply (const OpPeriodicComponent< long > & , long & , const long &) inline
Definition at line 378 of file BCond.hpp.
PETE_apply() [9/66]
void PETE_apply (const OpPeriodicComponent< float > & , float & , const float &) inline
Definition at line 379 of file BCond.hpp.
PETE_apply() [10/66]
void PETE_apply (const OpPeriodicComponent< double > & , double & , const double &) inline
Definition at line 380 of file BCond.hpp.
PETE_apply() [11/66]
void PETE_apply (const OpPeriodicComponent< std::complex< double > > & , std::complex< double > & , const std::complex< double > &) inline
Definition at line 381 of file BCond.hpp.
PETE_apply() [12/66]
template<class T > void PETE_apply (const OpInterpolation< T > & , T & a, const T & b) inline
Definition at line 410 of file BCond.hpp.
References a.
PETE_apply() [13/66]
template<class T > void PETE_apply (const OpInterpolationComponent< T > & e, T & a, const T & b) inline
Definition at line 421 of file BCond.hpp.
References a, and Physics::e.
PETE_apply() [14/66]
void PETE_apply (const OpInterpolationComponent< char > & , char & , const char &) inline
Definition at line 432 of file BCond.hpp.
PETE_apply() [15/66]
void PETE_apply (const OpInterpolationComponent< bool > & , bool & , const bool &) inline
Definition at line 433 of file BCond.hpp.
PETE_apply() [16/66]
void PETE_apply (const OpInterpolationComponent< int > & , int & , const int &) inline
Definition at line 434 of file BCond.hpp.
PETE_apply() [17/66]
void PETE_apply (const OpInterpolationComponent< unsigned > & , unsigned & , const unsigned &) inline
Definition at line 435 of file BCond.hpp.
PETE_apply() [18/66]
void PETE_apply (const OpInterpolationComponent< short > & , short & , const short &) inline
Definition at line 436 of file BCond.hpp.
PETE_apply() [19/66]
void PETE_apply (const OpInterpolationComponent< long > & , long & , const long &) inline
Definition at line 437 of file BCond.hpp.
PETE_apply() [20/66]
void PETE_apply (const OpInterpolationComponent< float > & , float & , const float &) inline
Definition at line 438 of file BCond.hpp.
PETE_apply() [21/66]
void PETE_apply (const OpInterpolationComponent< double > & , double & , const double &) inline
Definition at line 439 of file BCond.hpp.
PETE_apply() [22/66]
void PETE_apply (const OpInterpolationComponent< std::complex< double > > & , std::complex< double > & , const std::complex< double > &) inline
Definition at line 440 of file BCond.hpp.
PETE_apply() [23/66]
template<class T > void PETE_apply (const OpExtrapolate< T > & e, T & a, const T & b) inline
Definition at line 2727 of file BCond.hpp.
References a, and Physics::e.
PETE_apply() [24/66]
template<class T > void PETE_apply (const OpExtrapolateComponent< T > & e, T & a, const T & b) inline
Definition at line 2740 of file BCond.hpp.
References a, and Physics::e.
PETE_apply() [25/66]
void PETE_apply (const OpExtrapolateComponent< char > & , char & , const char &) inline
Definition at line 2760 of file BCond.hpp.
PETE_apply() [26/66]
void PETE_apply (const OpExtrapolateComponent< bool > & , bool & , const bool &) inline
Definition at line 2761 of file BCond.hpp.
PETE_apply() [27/66]
void PETE_apply (const OpExtrapolateComponent< int > & , int & , const int &) inline
Definition at line 2762 of file BCond.hpp.
PETE_apply() [28/66]
void PETE_apply (const OpExtrapolateComponent< unsigned > & , unsigned & , const unsigned &) inline
Definition at line 2763 of file BCond.hpp.
PETE_apply() [29/66]
void PETE_apply (const OpExtrapolateComponent< short > & , short & , const short &) inline
Definition at line 2764 of file BCond.hpp.
PETE_apply() [30/66]
void PETE_apply (const OpExtrapolateComponent< long > & , long & , const long &) inline
Definition at line 2765 of file BCond.hpp.
PETE_apply() [31/66]
void PETE_apply (const OpExtrapolateComponent< float > & , float & , const float &) inline
Definition at line 2766 of file BCond.hpp.
PETE_apply() [32/66]
void PETE_apply (const OpExtrapolateComponent< double > & , double & , const double &) inline
Definition at line 2767 of file BCond.hpp.
PETE_apply() [33/66]
void PETE_apply (const OpExtrapolateComponent< std::complex< double > > & , std::complex< double > & , const std::complex< double > &) inline
Definition at line 2768 of file BCond.hpp.
PETE_apply() [34/66]
template<class T > void PETE_apply (const OpExtrapolateAndZero< T > & e, T & a, const T & b) inline
Definition at line 3512 of file BCond.hpp.
References a, and Physics::e.
PETE_apply() [35/66]
template<class T > void PETE_apply (const OpExtrapolateAndZeroComponent< T > & e, T & a, const T & b) inline
Definition at line 3525 of file BCond.hpp.
References a, and Physics::e.
PETE_apply() [36/66]
void PETE_apply (const OpExtrapolateAndZeroComponent< char > & , char & , const char &) inline
Definition at line 3548 of file BCond.hpp.
PETE_apply() [37/66]
void PETE_apply (const OpExtrapolateAndZeroComponent< bool > & , bool & , const bool &) inline
Definition at line 3549 of file BCond.hpp.
PETE_apply() [38/66]
void PETE_apply (const OpExtrapolateAndZeroComponent< int > & , int & , const int &) inline
Definition at line 3550 of file BCond.hpp.
PETE_apply() [39/66]
void PETE_apply (const OpExtrapolateAndZeroComponent< unsigned > & , unsigned & , const unsigned &) inline
Definition at line 3551 of file BCond.hpp.
PETE_apply() [40/66]
void PETE_apply (const OpExtrapolateAndZeroComponent< short > & , short & , const short &) inline
Definition at line 3552 of file BCond.hpp.
PETE_apply() [41/66]
void PETE_apply (const OpExtrapolateAndZeroComponent< long > & , long & , const long &) inline
Definition at line 3553 of file BCond.hpp.
PETE_apply() [42/66]
void PETE_apply (const OpExtrapolateAndZeroComponent< float > & , float & , const float &) inline
Definition at line 3554 of file BCond.hpp.
PETE_apply() [43/66]
void PETE_apply (const OpExtrapolateAndZeroComponent< double > & , double & , const double &) inline
Definition at line 3555 of file BCond.hpp.
PETE_apply() [44/66]
void PETE_apply (const OpExtrapolateAndZeroComponent< std::complex< double > > & , std::complex< double > & , const std::complex< double > &) inline
Definition at line 3556 of file BCond.hpp.
PETE_apply() [45/66]
template<class T , class T1 > void PETE_apply (const OpAssignComponent< T > & e, T & a, const T1 & b) inline
Definition at line 3568 of file BCond.hpp.
References a, and Physics::e.
PETE_apply() [46/66]
void PETE_apply (const OpAssignComponent< char > & , char & , const char &) inline
Definition at line 3573 of file BCond.hpp.
PETE_apply() [47/66]
void PETE_apply (const OpAssignComponent< bool > & , bool & , const bool &) inline
Definition at line 3574 of file BCond.hpp.
PETE_apply() [48/66]
void PETE_apply (const OpAssignComponent< int > & , int & , const int &) inline
Definition at line 3575 of file BCond.hpp.
PETE_apply() [49/66]
void PETE_apply (const OpAssignComponent< unsigned > & , unsigned & , const unsigned &) inline
Definition at line 3576 of file BCond.hpp.
PETE_apply() [50/66]
void PETE_apply (const OpAssignComponent< short > & , short & , const short &) inline
Definition at line 3577 of file BCond.hpp.
PETE_apply() [51/66]
void PETE_apply (const OpAssignComponent< long > & , long & , const long &) inline
Definition at line 3578 of file BCond.hpp.
PETE_apply() [52/66]
void PETE_apply (const OpAssignComponent< float > & , float & , const float &) inline
Definition at line 3579 of file BCond.hpp.
PETE_apply() [53/66]
void PETE_apply (const OpAssignComponent< double > & , double & , const double &) inline
Definition at line 3580 of file BCond.hpp.
PETE_apply() [54/66]
void PETE_apply (const OpAssignComponent< std::complex< double > > & , std::complex< double > & , const std::complex< double > &) inline
Definition at line 3581 of file BCond.hpp.
PETE_apply() [55/66]
template<class T > void PETE_apply (const OpBCFunctionEq< T > & e, T & a, T & b) inline
Definition at line 4504 of file BCond.hpp.
References a, and Physics::e.
PETE_apply() [56/66]
template<class T > void PETE_apply (const OpBCFunctionEqComponent< T > & e, T & a, const T & b) inline
Definition at line 4942 of file BCond.hpp.
References a, and Physics::e.
PETE_apply() [57/66]
void PETE_apply (const OpBCFunctionEqComponent< char > & , char & , const char &) inline
Definition at line 4952 of file BCond.hpp.
PETE_apply() [58/66]
void PETE_apply (const OpBCFunctionEqComponent< bool > & , bool & , const bool &) inline
Definition at line 4953 of file BCond.hpp.
PETE_apply() [59/66]
void PETE_apply (const OpBCFunctionEqComponent< int > & , int & , const int &) inline
Definition at line 4954 of file BCond.hpp.
PETE_apply() [60/66]
void PETE_apply (const OpBCFunctionEqComponent< unsigned > & , unsigned & , const unsigned &) inline
Definition at line 4955 of file BCond.hpp.
PETE_apply() [61/66]
void PETE_apply (const OpBCFunctionEqComponent< short > & , short & , const short &) inline
Definition at line 4956 of file BCond.hpp.
PETE_apply() [62/66]
void PETE_apply (const OpBCFunctionEqComponent< long > & , long & , const long &) inline
Definition at line 4957 of file BCond.hpp.
PETE_apply() [63/66]
void PETE_apply (const OpBCFunctionEqComponent< float > & , float & , const float &) inline
Definition at line 4958 of file BCond.hpp.
PETE_apply() [64/66]
void PETE_apply (const OpBCFunctionEqComponent< double > & , double & , const double &) inline
Definition at line 4959 of file BCond.hpp.
PETE_apply() [65/66]
void PETE_apply (const OpBCFunctionEqComponent< std::complex< double > > & , std::complex< double > & , const std::complex< double > &) inline
Definition at line 4960 of file BCond.hpp.
PETE_apply() [66/66]
template<class T > void PETE_apply (const EurekaAssign< T > & e, T & a, const T & b) inline
Definition at line 5566 of file BCond.hpp.
References a, Physics::e, and EurekaAssign< T >::get().