OPAL (Object Oriented Parallel Accelerator Library): coordinatetransform Namespace Reference
coordinatetransform Namespace Reference
Classes
class CoordinateTransform
struct myParams
Functions
double getUnitTangentVectorX (double s, void *p)
double getUnitTangentVectorY (double s, void *p)
Detailed Description
CoordinateTransform transforms between the coordinate system centred
at the entrance and the local Frenet-Serret coordinate system. Assuming
CoordinateTransform takes in the fringe field parameters and calculates
the coordinate transformation. First the coordinates are transformed to
a coordinate system centred in the middle of the magnet. From here
the Frenet-Serret coordinates are found using numerical integration.
Class category: AbsBeamline
Author: Martin Duy Tat
Function Documentation
getUnitTangentVectorX()
double coordinatetransform::getUnitTangentVectorX (double s, void * p)
Internal function used for GSL numerical integration
Definition at line 195 of file CoordinateTransform.cpp.
References cosh(), coordinatetransform::myParams::lambdaleft, coordinatetransform::myParams::lambdaright, log(), coordinatetransform::myParams::rho, coordinatetransform::myParams::s_0, sin(), and tanh().
Referenced by coordinatetransform::CoordinateTransform::calcReferenceTrajectory().
getUnitTangentVectorY()
double coordinatetransform::getUnitTangentVectorY (double s, void * p)
Internal function used for GSL numerical integration
Definition at line 204 of file CoordinateTransform.cpp.
References cos(), cosh(), coordinatetransform::myParams::lambdaleft, coordinatetransform::myParams::lambdaright, log(), coordinatetransform::myParams::rho, coordinatetransform::myParams::s_0, and tanh().
Referenced by coordinatetransform::CoordinateTransform::calcReferenceTrajectory().