OPAL (Object Oriented Parallel Accelerator Library): mslang::Union Struct Reference
mslang::Union Struct Reference
#include <Union.h>
Public Member Functions
virtual ~Union ()
virtual void print (int indentwidth)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Public Member Functions inherited from mslang::Function
virtual ~Function ()
virtual void apply (std::vector< std::shared_ptr< Base >> &bfuncs)=0
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
Static Public Member Functions inherited from mslang::Function
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
std::vector< Function * > funcs_m
Additional Inherited Members
Static Public Attributes inherited from mslang::Function
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\((.*)"
Detailed Description
Definition at line 7 of file Union.h.
Constructor & Destructor Documentation
~Union()
virtual mslang::Union::~Union () inline virtual
Definition at line 10 of file Union.h.
References funcs_m.
Member Function Documentation
apply()
void mslang::Union::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Definition at line 22 of file Union.cpp.
References mslang::Function::apply(), and funcs_m.
parse_detail()
bool mslang::Union::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 31 of file Union.cpp.
References end(), funcs_m, and mslang::Function::parse().
Referenced by mslang::Function::parse().
print()
void mslang::Union::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 6 of file Union.cpp.
References endl(), and funcs_m.
Member Data Documentation
funcs_m
std::vector<Function*> mslang::Union::funcs_m
Definition at line 8 of file Union.h.
Referenced by apply(), parse_detail(), print(), and ~Union().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Union.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Union.cpp