OPAL (Object Oriented Parallel Accelerator Library): ParticleAttrib< T > Class Template Reference
ParticleAttrib< T > Class Template Reference
#include <MakeDataSource.h>
Public Types
enum { IsExpr = 0 }
typedef T Return_t
typedef std::vector< T > ParticleList_t
typedef ParticleAttribIterator< T > iterator
typedef ParticleAttribConstIterator< T > const_iterator
typedef ParticleAttribBase::SortListIndex_t SortListIndex_t
typedef ParticleAttribBase::SortList_t SortList_t
typedef const_iterator PETE_Expr_t
Public Types inherited from ParticleAttribBase
typedef long SortListIndex_t
typedef std::vector< SortListIndex_t > SortList_t
Public Types inherited from DataSource
enum DsMode { INPUT, OUTPUT, BOTH, DEFAULT }
typedef std::vector< DataSourceObject * > container_t
Public Types inherited from PETE_Expr< ParticleAttrib< T > >
typedef ParticleAttrib< T > Wrapped
Public Member Functions
ParticleAttrib ()
ParticleAttrib (const ParticleAttrib< T > &pa)
~ParticleAttrib ()
bool isDirty ()
void resetDirtyFlag ()
ParticleList_t::reference operator[] (size_t n)
ParticleList_t::const_reference operator[] (size_t n) const
template<unsigned Dim>
SubParticleAttrib< ParticleAttrib< T >, T, Dim > operator[] (const SIndex< Dim > &s) const
PETE_Expr_t MakeExpression () const
iterator begin ()
iterator end ()
const_iterator cbegin () const
const_iterator cend () const
size_t size (void) const
ParticleAttribElem< T, 1U > operator() (unsigned)
ParticleAttribElem< T, 2U > operator() (unsigned, unsigned)
ParticleAttribElem< T, 3U > operator() (unsigned, unsigned, unsigned)
template<unsigned Dim, class M , class C , class PT , class IntOp >
void scatter (Field< T, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &) const
template<unsigned Dim, class M , class C , class PT , class IntOp , class CacheData >
void scatter (Field< T, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &, ParticleAttrib< CacheData > &cache) const
template<unsigned Dim, class M , class C , class IntOp , class CacheData >
void scatter (Field< T, Dim, M, C > &f, const IntOp &, const ParticleAttrib< CacheData > &cache) const
template<unsigned Dim, class M , class C , class PT , class IntOp >
void gather (const Field< T, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &)
template<unsigned Dim, class M , class C , class PT , class IntOp , class CacheData >
void gather (const Field< T, Dim, M, C > &f, const ParticleAttrib< Vektor< PT, Dim > > &pp, const IntOp &, ParticleAttrib< CacheData > &cache)
template<unsigned Dim, class M , class C , class IntOp , class CacheData >
void gather (const Field< T, Dim, M, C > &f, const IntOp &, const ParticleAttrib< CacheData > &cache)
template<class T1 >
const ParticleAttrib< T > & operator= (const PETE_Expr< T1 > &rhs)
const ParticleAttrib< T > & operator= (const ParticleAttrib< T > &rhs)
const ParticleAttrib< T > & operator= (T rhs)
virtual void create (size_t)
virtual void destroy (size_t M, size_t I, bool optDestroy=true)
virtual void destroy (const std::vector< std::pair< size_t, size_t > > &dlist, bool optDestroy=true)
virtual size_t putMessage (Message &, size_t, size_t)
virtual size_t putMessage (Message &, const std::vector< size_t > &)
virtual size_t getMessage (Message &, size_t)
virtual size_t ghostDestroy (size_t, size_t)
virtual void ghostCreate (size_t)
virtual size_t ghostPutMessage (Message &, size_t, size_t)
virtual size_t ghostPutMessage (Message &, const std::vector< size_t > &)
virtual size_t ghostGetMessage (Message &, size_t)
virtual void calcSortList (SortList_t &slist, bool ascending=true)
virtual void sort (SortList_t &slist)
virtual void printDebug (Inform &)
Public Member Functions inherited from ParticleAttribBase
ParticleAttribBase (unsigned int size, const std::string &typestr)
ParticleAttribBase (const ParticleAttribBase &pa)
virtual ~ParticleAttribBase ()
unsigned int elementSize () const
const std::string & typeString () const
void setTemporary (bool t)
bool isTemporary () const
Public Member Functions inherited from DataSource
DataSource ()
virtual ~DataSource ()
bool connected (DataConnect *=0) const
DataSourceObject * findDataSourceObject (DataConnect *) const
DataConnect * connect (const char *, DataConnect *=0, int=DataSource::DEFAULT)
bool connect (DataSourceObject *)
bool disconnect (DataConnect *=0)
bool updateConnection (DataConnect *=0)
void interact (DataConnect *=0)
void interact (const char *, DataConnect *=0)
Public Member Functions inherited from PETE_Expr< ParticleAttrib< T > >
ParticleAttrib< T > & PETE_unwrap ()
const ParticleAttrib< T > & PETE_unwrap () const
Protected Member Functions
virtual DataSourceObject * createDataSourceObject (const char *nm, DataConnect *dc, int tm)
Protected Attributes
ParticleList_t ParticleList
size_t LocalSize
Private Attributes
bool attributeIsDirty_
Friends
class ParticleAttribIterator< T >
class ParticleAttribConstIterator< T >
Detailed Description
template<class T>
class ParticleAttrib< T >
Definition at line 25 of file MakeDataSource.h.
Member Typedef Documentation
const_iterator
template<class T> typedef ParticleAttribConstIterator<T> ParticleAttrib< T >::const_iterator
Definition at line 110 of file ParticleAttrib.h.
iterator
template<class T> typedef ParticleAttribIterator<T> ParticleAttrib< T >::iterator
Definition at line 109 of file ParticleAttrib.h.
ParticleList_t
template<class T> typedef std::vector<T> ParticleAttrib< T >::ParticleList_t
Definition at line 108 of file ParticleAttrib.h.
PETE_Expr_t
template<class T> typedef const_iterator ParticleAttrib< T >::PETE_Expr_t
Definition at line 170 of file ParticleAttrib.h.
Return_t
template<class T> typedef T ParticleAttrib< T >::Return_t
Definition at line 107 of file ParticleAttrib.h.
SortList_t
template<class T> typedef ParticleAttribBase::SortList_t ParticleAttrib< T >::SortList_t
Definition at line 112 of file ParticleAttrib.h.
SortListIndex_t
template<class T> typedef ParticleAttribBase::SortListIndex_t ParticleAttrib< T >::SortListIndex_t
Definition at line 111 of file ParticleAttrib.h.
Member Enumeration Documentation
anonymous enum
template<class T> anonymous enum
Enumerator
IsExpr
Definition at line 169 of file ParticleAttrib.h.
Constructor & Destructor Documentation
ParticleAttrib() [1/2]
template<class T> ParticleAttrib< T >::ParticleAttrib () inline
Definition at line 116 of file ParticleAttrib.h.
ParticleAttrib() [2/2]
template<class T> ParticleAttrib< T >::ParticleAttrib (const ParticleAttrib< T > & pa) inline
Definition at line 121 of file ParticleAttrib.h.
~ParticleAttrib()
template<class T> ParticleAttrib< T >::~ParticleAttrib () inline
Definition at line 127 of file ParticleAttrib.h.
Member Function Documentation
begin()
template<class T> iterator ParticleAttrib< T >::begin () inline
Definition at line 174 of file ParticleAttrib.h.
Referenced by ParticleAttrib< ParticleOrigin >::gather(), ParticleAttrib< ParticleOrigin >::scatter(), and scatter().
calcSortList()
template<class T > void ParticleAttrib< T >::calcSortList (SortList_t & slist, bool ascending = true) virtual
Implements ParticleAttribBase.
Definition at line 422 of file ParticleAttrib.hpp.
cbegin()
template<class T> const_iterator ParticleAttrib< T >::cbegin () const inline
Definition at line 177 of file ParticleAttrib.h.
Referenced by ParticleAttrib< ParticleOrigin >::gather(), ParticleAttrib< ParticleOrigin >::MakeExpression(), ParticleAttrib< ParticleOrigin >::scatter(), and scatter().
cend()
template<class T> const_iterator ParticleAttrib< T >::cend () const inline
Definition at line 178 of file ParticleAttrib.h.
create()
template<class T > void ParticleAttrib< T >::create (size_t M) virtual
Implements ParticleAttribBase.
Definition at line 74 of file ParticleAttrib.hpp.
Referenced by PartBunch::computeSelfFields(), MultiBunchHandler::saveBunch(), and ParallelTTracker::writePhaseSpace().
createDataSourceObject()
template<class T> virtual DataSourceObject* ParticleAttrib< T >::createDataSourceObject (const char * nm, DataConnect * dc, int tm) inline protected virtual
Implements DataSource.
Definition at line 502 of file ParticleAttrib.h.
destroy() [1/2]
template<class T > void ParticleAttrib< T >::destroy (size_t M, size_t I, bool optDestroy = true) virtual
Implements ParticleAttribBase.
Definition at line 98 of file ParticleAttrib.hpp.
Referenced by PartBunch::computeSelfFields(), DiscParticle::read(), PartBunch::resetInterpolationCache(), and ParallelTTracker::writePhaseSpace().
destroy() [2/2]
template<class T > void ParticleAttrib< T >::destroy (const std::vector< std::pair< size_t, size_t > > & dlist, bool optDestroy = true) virtual
Implements ParticleAttribBase.
Definition at line 140 of file ParticleAttrib.hpp.
end()
template<class T> iterator ParticleAttrib< T >::end () inline
Definition at line 175 of file ParticleAttrib.h.
gather() [1/3]
template<class T> template<unsigned Dim, class M , class C , class PT , class IntOp > void ParticleAttrib< T >::gather (const Field< T, Dim, M, C > & f, const ParticleAttrib< Vektor< PT, Dim > > & pp, const IntOp &) inline
Definition at line 291 of file ParticleAttrib.h.
Referenced by gather().
gather() [2/3]
template<class T> template<unsigned Dim, class M , class C , class PT , class IntOp , class CacheData > void ParticleAttrib< T >::gather (const Field< T, Dim, M, C > & f, const ParticleAttrib< Vektor< PT, Dim > > & pp, const IntOp & , ParticleAttrib< CacheData > & cache) inline
Definition at line 321 of file ParticleAttrib.h.
gather() [3/3]
template<class T> template<unsigned Dim, class M , class C , class IntOp , class CacheData > void ParticleAttrib< T >::gather (const Field< T, Dim, M, C > & f, const IntOp & , const ParticleAttrib< CacheData > & cache) inline
Definition at line 352 of file ParticleAttrib.h.
getMessage()
template<class T > size_t ParticleAttrib< T >::getMessage (Message & msg, size_t M) virtual
Implements ParticleAttribBase.
Definition at line 279 of file ParticleAttrib.hpp.
Referenced by DiscParticle::read().
ghostCreate()
template<class T > void ParticleAttrib< T >::ghostCreate (size_t M) virtual
Implements ParticleAttribBase.
Definition at line 328 of file ParticleAttrib.hpp.
ghostDestroy()
template<class T > size_t ParticleAttrib< T >::ghostDestroy (size_t M, size_t I) virtual
Implements ParticleAttribBase.
Reimplemented in ParticleInteractAttrib< T >.
Definition at line 341 of file ParticleAttrib.hpp.
ghostGetMessage()
template<class T > size_t ParticleAttrib< T >::ghostGetMessage (Message & msg, size_t M) virtual
Implements ParticleAttribBase.
Reimplemented in ParticleInteractAttrib< T >.
Definition at line 354 of file ParticleAttrib.hpp.
ghostPutMessage() [1/2]
template<class T > size_t ParticleAttrib< T >::ghostPutMessage (Message & , size_t , size_t) virtual
Implements ParticleAttribBase.
Reimplemented in ParticleInteractAttrib< T >.
Definition at line 312 of file ParticleAttrib.hpp.
ghostPutMessage() [2/2]
template<class T > size_t ParticleAttrib< T >::ghostPutMessage (Message & , const std::vector< size_t > &) virtual
Implements ParticleAttribBase.
Reimplemented in ParticleInteractAttrib< T >.
Definition at line 318 of file ParticleAttrib.hpp.
isDirty()
template<class T> bool ParticleAttrib< T >::isDirty () inline
notify user that attribute has changed. The user is responsible to define the meaning of the dirt and clean state
Definition at line 135 of file ParticleAttrib.h.
Referenced by AmrPartBunch::boundp(), and PartBunchBase< double, 3 >::boundp().
MakeExpression()
template<class T> PETE_Expr_t ParticleAttrib< T >::MakeExpression () const inline
Definition at line 171 of file ParticleAttrib.h.
operator()() [1/3]
template<class T > ParticleAttribElem< T, 1U > ParticleAttrib< T >::operator() (unsigned i)
Definition at line 41 of file ParticleAttrib.hpp.
operator()() [2/3]
template<class T > ParticleAttribElem< T, 2U > ParticleAttrib< T >::operator() (unsigned i, unsigned j)
Definition at line 52 of file ParticleAttrib.hpp.
operator()() [3/3]
template<class T > ParticleAttribElem< T, 3U > ParticleAttrib< T >::operator() (unsigned i, unsigned j, unsigned k)
Definition at line 63 of file ParticleAttrib.hpp.
operator=() [1/3]
template<class T> template<class T1 > const ParticleAttrib<T>& ParticleAttrib< T >::operator= (const PETE_Expr< T1 > & rhs) inline
Definition at line 381 of file ParticleAttrib.h.
operator=() [2/3]
template<class T> const ParticleAttrib<T>& ParticleAttrib< T >::operator= (const ParticleAttrib< T > & rhs) inline
Definition at line 387 of file ParticleAttrib.h.
operator=() [3/3]
template<class T> const ParticleAttrib<T>& ParticleAttrib< T >::operator= (T rhs) inline
Definition at line 397 of file ParticleAttrib.h.
operator[]() [1/3]
template<class T> ParticleList_t::reference ParticleAttrib< T >::operator[] (size_t n) inline
Definition at line 145 of file ParticleAttrib.h.
operator[]() [2/3]
template<class T> ParticleList_t::const_reference ParticleAttrib< T >::operator[] (size_t n) const inline
Definition at line 151 of file ParticleAttrib.h.
operator[]() [3/3]
template<class T> template<unsigned Dim> SubParticleAttrib<ParticleAttrib<T>, T, Dim> ParticleAttrib< T >::operator[] (const SIndex< Dim > & s) const inline
Definition at line 161 of file ParticleAttrib.h.
printDebug()
template<class T > void ParticleAttrib< T >::printDebug (Inform & o) virtual
Implements ParticleAttribBase.
Reimplemented in ParticleInteractAttrib< T >.
Definition at line 371 of file ParticleAttrib.hpp.
putMessage() [1/2]
template<class T > size_t ParticleAttrib< T >::putMessage (Message & msg, size_t M, size_t I) virtual
Implements ParticleAttribBase.
Reimplemented in ParticleInteractAttrib< T >.
Definition at line 231 of file ParticleAttrib.hpp.
Referenced by ParticleInteractAttrib< T >::putMessage(), and DiscParticle::write().
putMessage() [2/2]
template<class T > size_t ParticleAttrib< T >::putMessage (Message & msg, const std::vector< size_t > & putList) virtual
Implements ParticleAttribBase.
Reimplemented in ParticleInteractAttrib< T >.
Definition at line 254 of file ParticleAttrib.hpp.
resetDirtyFlag()
template<class T> void ParticleAttrib< T >::resetDirtyFlag () inline
Definition at line 140 of file ParticleAttrib.h.
Referenced by AmrPartBunch::boundp().
scatter() [1/3]
template<class T> template<unsigned Dim, class M , class C , class PT , class IntOp > void ParticleAttrib< T >::scatter (Field< T, Dim, M, C > & f, const ParticleAttrib< Vektor< PT, Dim > > & pp, const IntOp &) const inline
Definition at line 204 of file ParticleAttrib.h.
Referenced by PartBunch::computeSelfFields(), PartBunch::computeSelfFields_cycl(), and scatter().
scatter() [2/3]
template<class T> template<unsigned Dim, class M , class C , class PT , class IntOp , class CacheData > void ParticleAttrib< T >::scatter (Field< T, Dim, M, C > & f, const ParticleAttrib< Vektor< PT, Dim > > & pp, const IntOp & , ParticleAttrib< CacheData > & cache) const inline
Definition at line 233 of file ParticleAttrib.h.
scatter() [3/3]
template<class T> template<unsigned Dim, class M , class C , class IntOp , class CacheData > void ParticleAttrib< T >::scatter (Field< T, Dim, M, C > & f, const IntOp & , const ParticleAttrib< CacheData > & cache) const inline
Definition at line 264 of file ParticleAttrib.h.
size()
template<class T> size_t ParticleAttrib< T >::size (void) const inline
Definition at line 180 of file ParticleAttrib.h.
Referenced by PartBunch::computeSelfFields(), ParticleInteractAttrib< T >::operator=(), ParticleAttrib< ParticleOrigin >::operator=(), ParticleInteractAttrib< T >::operator[](), pap(), DiscParticle::read(), PartBunch::resetInterpolationCache(), scatter(), spap(), and DiscParticle::write().
sort()
template<class T > void ParticleAttrib< T >::sort (SortList_t & slist) virtual
Implements ParticleAttribBase.
Definition at line 492 of file ParticleAttrib.hpp.
Friends And Related Function Documentation
ParticleAttribConstIterator< T >
template<class T> friend class ParticleAttribConstIterator< T > friend
Definition at line 103 of file ParticleAttrib.h.
ParticleAttribIterator< T >
template<class T> friend class ParticleAttribIterator< T > friend
Definition at line 102 of file ParticleAttrib.h.
Member Data Documentation
attributeIsDirty_
template<class T> bool ParticleAttrib< T >::attributeIsDirty_ private
Definition at line 512 of file ParticleAttrib.h.
Referenced by ParticleAttrib< ParticleOrigin >::isDirty(), ParticleAttrib< ParticleOrigin >::operator[](), and ParticleAttrib< ParticleOrigin >::resetDirtyFlag().
LocalSize
template<class T> size_t ParticleAttrib< T >::LocalSize protected
Definition at line 509 of file ParticleAttrib.h.
Referenced by ParticleAttrib< ParticleOrigin >::cend(), ParticleAttrib< ParticleOrigin >::end(), ParticleAttrib< ParticleOrigin >::gather(), ParticleAttrib< ParticleOrigin >::scatter(), and ParticleAttrib< ParticleOrigin >::size().
ParticleList
template<class T> ParticleList_t ParticleAttrib< T >::ParticleList protected
Definition at line 508 of file ParticleAttrib.h.
Referenced by ParticleAttrib< ParticleOrigin >::gather(), ParticleInteractAttrib< T >::operator[](), ParticleAttrib< ParticleOrigin >::operator[](), and ParticleAttrib< ParticleOrigin >::scatter().
The documentation for this class was generated from the following files:
ippl/src/DataSource/MakeDataSource.h
ippl/src/Particle/ParticleAttrib.h
ippl/src/Particle/ParticleAttrib.hpp