OPAL (Object Oriented Parallel Accelerator Library): BeamlineVisitor Class Reference
BeamlineVisitor Class Reference abstract
#include <BeamlineVisitor.h>
Public Member Functions
BeamlineVisitor ()
virtual ~BeamlineVisitor ()
virtual void execute ()=0
Execute the algorithm on the attached beam line.
virtual void visitBeamline (const Beamline &)=0
Apply the algorithm to a beam line.
virtual void visitCCollimator (const CCollimator &)=0
Apply the algorithm to a collimator.
virtual void visitComponent (const Component &)=0
Apply the algorithm to an arbitrary component.
virtual void visitCorrector (const Corrector &)=0
Apply the algorithm to a closed orbit corrector.
virtual void visitCyclotron (const Cyclotron &)=0
Apply the algorithm to a cyclotron.
virtual void visitDegrader (const Degrader &)=0
Apply the algorithm to a degrader.
virtual void visitDrift (const Drift &)=0
Apply the algorithm to a drift space.
virtual void visitFlaggedElmPtr (const FlaggedElmPtr &)=0
Apply the algorithm to a FlaggedElmPtr.
virtual void visitFlexibleCollimator (const FlexibleCollimator &)=0
Apply the algorithm to a flexible collimator.
virtual void visitMarker (const Marker &)=0
Apply the algorithm to a marker.
virtual void visitMonitor (const Monitor &)=0
Apply the algorithm to a beam position monitor.
virtual void visitMultipole (const Multipole &)=0
Apply the algorithm to a multipole.
virtual void visitMultipoleT (const MultipoleT &)=0
Apply the algorithm to an arbitrary multipole.
virtual void visitMultipoleTStraight (const MultipoleTStraight &)=0
Apply the algorithm to an arbitrary straight multipole.
virtual void visitMultipoleTCurvedConstRadius (const MultipoleTCurvedConstRadius &)=0
Apply the algorithm to an arbitrary curved multipole of constant radius.
virtual void visitMultipoleTCurvedVarRadius (const MultipoleTCurvedVarRadius &)=0
Apply the algorithm to an arbitrary curved multipole of variable radius.
virtual void visitOffset (const Offset &)=0
Apply the algorithm to an offset (placement).
virtual void visitProbe (const Probe &)=0
Apply the algorithm to a probe.
virtual void visitRBend (const RBend &)=0
Apply the algorithm to a rectangular bend.
virtual void visitRBend3D (const RBend3D &)
Apply the algorithm to a rectangular bend.
virtual void visitRFCavity (const RFCavity &)=0
Apply the algorithm to a RF cavity.
virtual void visitRing (const Ring &)=0
Apply the algorithm to a ring.
virtual void visitSBend (const SBend &)=0
Apply the algorithm to a sector bend.
virtual void visitSBend3D (const SBend3D &)=0
Apply the algorithm to a sector bend with 3D field map.
virtual void visitScalingFFAMagnet (const ScalingFFAMagnet &)=0
Apply the algorithm to a scaling FFA magnet.
virtual void visitSeptum (const Septum &)=0
Apply the algorithm to a septum magnet.
virtual void visitSolenoid (const Solenoid &)=0
Apply the algorithm to a solenoid.
virtual void visitSource (const Source &)=0
Apply the algorithm to a source.
virtual void visitStripper (const Stripper &)=0
Apply the algorithm to a particle stripper.
virtual void visitTravelingWave (const TravelingWave &)=0
Apply the algorithm to a traveling wave.
virtual void visitVacuum (const Vacuum &)=0
Apply the algorithm to a vacuum space.
virtual void visitVariableRFCavity (const VariableRFCavity &)=0
Apply the algorithm to a variable RF cavity.
virtual void visitVariableRFCavityFringeField (const VariableRFCavityFringeField &)=0
Apply the algorithm to a variable RF cavity with Fringe Field.
virtual void visitVerticalFFAMagnet (const VerticalFFAMagnet &)=0
Apply the algorithm to a vertical FFA magnet.
Private Member Functions
BeamlineVisitor (const BeamlineVisitor &)
void operator= (const BeamlineVisitor &)
Detailed Description
Definition at line 79 of file BeamlineVisitor.h.
Constructor & Destructor Documentation
BeamlineVisitor() [1/2]
BeamlineVisitor::BeamlineVisitor ()
Definition at line 36 of file BeamlineVisitor.cpp.
~BeamlineVisitor()
BeamlineVisitor::~BeamlineVisitor () virtual
Definition at line 40 of file BeamlineVisitor.cpp.
BeamlineVisitor() [2/2]
BeamlineVisitor::BeamlineVisitor (const BeamlineVisitor &) private
Member Function Documentation
execute()
virtual void BeamlineVisitor::execute () pure virtual
Execute the algorithm on the attached beam line.
Implemented in ThickTracker, ParallelTTracker, SpecificElementVisitor< ELEM >, ParallelCyclotronTracker, DefaultVisitor, Selector, and RangeSelector.
operator=()
void BeamlineVisitor::operator= (const BeamlineVisitor &) private
visitBeamline()
virtual void BeamlineVisitor::visitBeamline (const Beamline &) pure virtual
Apply the algorithm to a beam line.
Implemented in ThickTracker, ParallelTTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by TBeamline< T >::accept().
visitCCollimator()
virtual void BeamlineVisitor::visitCCollimator (const CCollimator &) pure virtual
Apply the algorithm to a collimator.
Implemented in ThickTracker, ParallelTTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by CCollimator::accept().
visitComponent()
virtual void BeamlineVisitor::visitComponent (const Component &) pure virtual
Apply the algorithm to an arbitrary component.
Implemented in Tracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
visitCorrector()
virtual void BeamlineVisitor::visitCorrector (const Corrector &) pure virtual
Apply the algorithm to a closed orbit corrector.
Implemented in ThickTracker, ParallelTTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by Corrector::accept().
visitCyclotron()
virtual void BeamlineVisitor::visitCyclotron (const Cyclotron &) pure virtual
Apply the algorithm to a cyclotron.
Implemented in ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by Cyclotron::accept().
visitDegrader()
virtual void BeamlineVisitor::visitDegrader (const Degrader &) pure virtual
Apply the algorithm to a degrader.
Implemented in ThickTracker, ParallelTTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by Degrader::accept().
visitDrift()
virtual void BeamlineVisitor::visitDrift (const Drift &) pure virtual
Apply the algorithm to a drift space.
Implemented in ThickTracker, ParallelTTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by Drift::accept().
visitFlaggedElmPtr()
virtual void BeamlineVisitor::visitFlaggedElmPtr (const FlaggedElmPtr &) pure virtual
Apply the algorithm to a FlaggedElmPtr.
Implemented in SpecificElementVisitor< ELEM >, DefaultVisitor, Replacer, RangeSelector, and Flagger.
Referenced by FlaggedElmPtr::accept().
visitFlexibleCollimator()
virtual void BeamlineVisitor::visitFlexibleCollimator (const FlexibleCollimator &) pure virtual
Apply the algorithm to a flexible collimator.
Implemented in ThickTracker, ParallelTTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by FlexibleCollimator::accept().
visitMarker()
virtual void BeamlineVisitor::visitMarker (const Marker &) pure virtual
Apply the algorithm to a marker.
Implemented in ThickTracker, ParallelTTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by Marker::accept().
visitMonitor()
virtual void BeamlineVisitor::visitMonitor (const Monitor &) pure virtual
Apply the algorithm to a beam position monitor.
Implemented in ThickTracker, ParallelTTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by Monitor::accept().
visitMultipole()
virtual void BeamlineVisitor::visitMultipole (const Multipole &) pure virtual
Apply the algorithm to a multipole.
Implemented in ThickTracker, ParallelTTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by Multipole::accept().
visitMultipoleT()
virtual void BeamlineVisitor::visitMultipoleT (const MultipoleT &) pure virtual
Apply the algorithm to an arbitrary multipole.
Implemented in ParallelTTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by MultipoleT::accept().
visitMultipoleTCurvedConstRadius()
virtual void BeamlineVisitor::visitMultipoleTCurvedConstRadius (const MultipoleTCurvedConstRadius &) pure virtual
Apply the algorithm to an arbitrary curved multipole of constant radius.
Implemented in ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by MultipoleTCurvedConstRadius::accept().
visitMultipoleTCurvedVarRadius()
virtual void BeamlineVisitor::visitMultipoleTCurvedVarRadius (const MultipoleTCurvedVarRadius &) pure virtual
Apply the algorithm to an arbitrary curved multipole of variable radius.
Implemented in ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by MultipoleTCurvedVarRadius::accept().
visitMultipoleTStraight()
virtual void BeamlineVisitor::visitMultipoleTStraight (const MultipoleTStraight &) pure virtual
Apply the algorithm to an arbitrary straight multipole.
Implemented in ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by MultipoleTStraight::accept().
visitOffset()
virtual void BeamlineVisitor::visitOffset (const Offset &) pure virtual
Apply the algorithm to an offset (placement).
Implemented in ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by Offset::accept().
visitProbe()
virtual void BeamlineVisitor::visitProbe (const Probe &) pure virtual
Apply the algorithm to a probe.
Implemented in ThickTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, ParallelTTracker, and DefaultVisitor.
Referenced by Probe::accept().
visitRBend()
virtual void BeamlineVisitor::visitRBend (const RBend &) pure virtual
Apply the algorithm to a rectangular bend.
Implemented in ThickTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, ParallelTTracker, and DefaultVisitor.
Referenced by RBend::accept().
visitRBend3D()
void BeamlineVisitor::visitRBend3D (const RBend3D &) inline virtual
Apply the algorithm to a rectangular bend.
Reimplemented in SpecificElementVisitor< ELEM >, ParallelTTracker, and DefaultVisitor.
Definition at line 205 of file BeamlineVisitor.h.
Referenced by RBend3D::accept().
visitRFCavity()
virtual void BeamlineVisitor::visitRFCavity (const RFCavity &) pure virtual
Apply the algorithm to a RF cavity.
Implemented in ThickTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, ParallelTTracker, and DefaultVisitor.
Referenced by RFCavity::accept().
visitRing()
virtual void BeamlineVisitor::visitRing (const Ring &) pure virtual
Apply the algorithm to a ring.
Implemented in ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by Ring::accept().
visitSBend()
virtual void BeamlineVisitor::visitSBend (const SBend &) pure virtual
Apply the algorithm to a sector bend.
Implemented in ThickTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, ParallelTTracker, and DefaultVisitor.
Referenced by SBend::accept().
visitSBend3D()
virtual void BeamlineVisitor::visitSBend3D (const SBend3D &) pure virtual
Apply the algorithm to a sector bend with 3D field map.
Implemented in ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by SBend3D::accept().
visitScalingFFAMagnet()
virtual void BeamlineVisitor::visitScalingFFAMagnet (const ScalingFFAMagnet &) pure virtual
Apply the algorithm to a scaling FFA magnet.
Implemented in ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by ScalingFFAMagnet::accept().
visitSeptum()
virtual void BeamlineVisitor::visitSeptum (const Septum &) pure virtual
Apply the algorithm to a septum magnet.
Implemented in ThickTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, ParallelTTracker, and DefaultVisitor.
Referenced by Septum::accept().
visitSolenoid()
virtual void BeamlineVisitor::visitSolenoid (const Solenoid &) pure virtual
Apply the algorithm to a solenoid.
Implemented in ThickTracker, ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, ParallelTTracker, and DefaultVisitor.
Referenced by Solenoid::accept().
visitSource()
virtual void BeamlineVisitor::visitSource (const Source &) pure virtual
Apply the algorithm to a source.
Implemented in SpecificElementVisitor< ELEM >, ParallelTTracker, and DefaultVisitor.
Referenced by Source::accept().
visitStripper()
virtual void BeamlineVisitor::visitStripper (const Stripper &) pure virtual
Apply the algorithm to a particle stripper.
Implemented in ParallelCyclotronTracker, SpecificElementVisitor< ELEM >, and DefaultVisitor.
Referenced by Stripper::accept().
visitTravelingWave()
virtual void BeamlineVisitor::visitTravelingWave (const TravelingWave &) pure virtual
Apply the algorithm to a traveling wave.
Implemented in ThickTracker, SpecificElementVisitor< ELEM >, ParallelTTracker, and DefaultVisitor.
Referenced by TravelingWave::accept().
visitVacuum()
virtual void BeamlineVisitor::visitVacuum (const Vacuum &) pure virtual
Apply the algorithm to a vacuum space.
Implemented in SpecificElementVisitor< ELEM >, ThickTracker, ParallelCyclotronTracker, ParallelTTracker, and DefaultVisitor.
Referenced by Vacuum::accept().
visitVariableRFCavity()
virtual void BeamlineVisitor::visitVariableRFCavity (const VariableRFCavity &) pure virtual
Apply the algorithm to a variable RF cavity.
Implemented in SpecificElementVisitor< ELEM >, ParallelCyclotronTracker, and DefaultVisitor.
Referenced by VariableRFCavity::accept(), and VariableRFCavityFringeField::accept().
visitVariableRFCavityFringeField()
virtual void BeamlineVisitor::visitVariableRFCavityFringeField (const VariableRFCavityFringeField &) pure virtual
Apply the algorithm to a variable RF cavity with Fringe Field.
Implemented in SpecificElementVisitor< ELEM >, ParallelCyclotronTracker, and DefaultVisitor.
visitVerticalFFAMagnet()
virtual void BeamlineVisitor::visitVerticalFFAMagnet (const VerticalFFAMagnet &) pure virtual
Apply the algorithm to a vertical FFA magnet.
Implemented in SpecificElementVisitor< ELEM >, ParallelCyclotronTracker, and DefaultVisitor.
Referenced by VerticalFFAMagnet::accept().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/BeamlineVisitor.h
src/Classic/AbsBeamline/BeamlineVisitor.cpp