OPAL (Object Oriented Parallel Accelerator Library): SBend3D Class Reference
SBend3D Class Reference
#include <SBend3D.h>
Public Member Functions
SBend3D (const std::string &name)
SBend3D (const SBend3D &right)
~SBend3D ()
ElementBase * clone () const override
bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
void finalise () override
bool bends () const override
void getDimensions (double &, double &) const override
BGeometryBase & getGeometry () override
const BGeometryBase & getGeometry () const override
EMField & getField () override
const EMField & getField () const override
void accept (BeamlineVisitor &visitor) const override
void setFieldMapFileName (std::string name)
std::string getFieldMapFileName () const
double getLengthUnits () const
void setLengthUnits (double lengthUnits)
double getFieldUnits () const
void setFieldUnits (double fieldUnits)
int getPolynomialOrder () const
void setPolynomialOrder (int polyOrder)
int getSmoothingOrder () const
void setSmoothingOrder (int polyOrder)
SectorMagneticFieldMap * getSectorMagneticFieldMap () const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual void goOnline (const double &kineticEnergy)
virtual void goOffline ()
virtual bool Online ()
virtual ElementBase::ElementType getType () const
Get element type std::string.
virtual void setComponentType (std::string)
virtual std::string getComponentType () const
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Attributes
SectorMagneticFieldMap * map_m
PlanarArcGeometry planarArcGeometry_m
double fieldUnits_m
double lengthUnits_m
int polyOrder_m
double smoothOrder_m
BMultipoleField dummy
Additional Inherited Members
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Sector bending magnet from a 3D field map
SBend3D provides interface between Component type and routines for linear interpolation from a 3D field map in a sector geometry.
Parameters
planarArcGeometry_m Cell geometry is a PlanarArcGeometry with radius of curvature equal to the radius at the middle of the field map and angle given by the field map opening angle.
map_m the actual field map class (with associated interpolation and IO routines).
field_m a dummy field - never used, only put in to obey inheritance requirements
Definition at line 50 of file SBend3D.h.
Constructor & Destructor Documentation
SBend3D() [1/2]
SBend3D::SBend3D (const std::string & name) explicit
Construct a new SBend3D
Parameters
name User-defined name of the SBend3D
Definition at line 32 of file SBend3D.cpp.
Referenced by clone().
SBend3D() [2/2]
SBend3D::SBend3D (const SBend3D & right)
Copy constructor
Definition at line 38 of file SBend3D.cpp.
References map_m, and Component::RefPartBunch_m.
~SBend3D()
SBend3D::~SBend3D ()
Destructor - deletes map
Definition at line 49 of file SBend3D.cpp.
References map_m.
Member Function Documentation
accept()
void SBend3D::accept (BeamlineVisitor & visitor) const override virtual
Accept a beamline visitor
Implements ElementBase.
Definition at line 117 of file SBend3D.cpp.
References BeamlineVisitor::visitSBend3D().
apply() [1/2]
bool SBend3D::apply (const size_t & i, const double & t, Vector_t & E, Vector_t & B) override virtual
Calculate the field at the position of the ith particle
Parameters
i index of the particle event; field is calculated at this position
t time at which the field is to be calculated
E calculated electric field - always 0 (no E-field)
B calculated magnetic field
Returns
true if particle is outside the field map
Reimplemented from Component.
Definition at line 66 of file SBend3D.cpp.
References PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::R, and Component::RefPartBunch_m.
apply() [2/2]
bool SBend3D::apply (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & E, Vector_t & B) override virtual
Calculate the field at some arbitrary position
Parameters
R position in the local coordinate system of the bend
t time at which the field is to be calculated
E calculated electric field - always 0 (no E-field)
B calculated magnetic field
Returns
true if particle is outside the field map, else false
Reimplemented from Component.
Definition at line 71 of file SBend3D.cpp.
References SectorMagneticFieldMap::getFieldstrength(), map_m, and Attrib::Distribution::R.
bends()
bool SBend3D::bends () const inline override virtual
Return true - SBend3D always bends the reference particle
Implements Component.
Definition at line 85 of file SBend3D.cpp.
clone()
ElementBase * SBend3D::clone () const override virtual
Inheritable copy constructor
Implements ElementBase.
Definition at line 53 of file SBend3D.cpp.
References SBend3D().
finalise()
void SBend3D::finalise () override virtual
Finalise the SBend3D - sets bunch to NULL
Implements Component.
Definition at line 81 of file SBend3D.cpp.
References Component::RefPartBunch_m.
getDimensions()
void SBend3D::getDimensions (double & , double &) const inline override virtual
Not implemented
Implements Component.
Definition at line 104 of file SBend3D.h.
getField() [1/2]
EMField & SBend3D::getField () override virtual
Return a dummy (0.) field value (what is this for?)
Implements Component.
Definition at line 58 of file SBend3D.cpp.
References dummy.
getField() [2/2]
const EMField & SBend3D::getField () const override virtual
Return a dummy (0.) field value (what is this for?)
Implements Component.
Definition at line 62 of file SBend3D.cpp.
References dummy.
getFieldMapFileName()
std::string SBend3D::getFieldMapFileName () const inline
Get the file name of the field map
Definition at line 174 of file SBend3D.h.
References SectorMagneticFieldMap::getFieldMapFileName(), and map_m.
getFieldUnits()
double SBend3D::getFieldUnits () const inline
Get the scale factor
Definition at line 140 of file SBend3D.h.
References fieldUnits_m.
getGeometry() [1/2]
BGeometryBase & SBend3D::getGeometry () override virtual
Return the cell geometry
Implements ElementBase.
Definition at line 89 of file SBend3D.cpp.
References planarArcGeometry_m.
getGeometry() [2/2]
const BGeometryBase & SBend3D::getGeometry () const override virtual
Return the cell geometry
Implements ElementBase.
Definition at line 93 of file SBend3D.cpp.
References planarArcGeometry_m.
getLengthUnits()
double SBend3D::getLengthUnits () const inline
Get the scale factor
Definition at line 134 of file SBend3D.h.
References lengthUnits_m.
getPolynomialOrder()
int SBend3D::getPolynomialOrder () const inline
Get the polynomial order
Definition at line 146 of file SBend3D.h.
References polyOrder_m.
getSectorMagneticFieldMap()
SectorMagneticFieldMap* SBend3D::getSectorMagneticFieldMap () const inline
Get the sector magnetic field map
Definition at line 158 of file SBend3D.h.
References map_m.
getSmoothingOrder()
int SBend3D::getSmoothingOrder () const inline
Get the smoothing factor
Definition at line 152 of file SBend3D.h.
References smoothOrder_m.
initialise()
void SBend3D::initialise (PartBunchBase< double, 3 > * bunch, double & startField, double & endField) override virtual
Initialise the SBend3D
Parameters
bunch the global bunch object
startField not used
endField not used
Implements Component.
Definition at line 77 of file SBend3D.cpp.
References Component::RefPartBunch_m.
setFieldMapFileName()
void SBend3D::setFieldMapFileName (std::string name)
Set the field map file
Parameters
name the file name of the field map
This generates a new field map object with the given name. If name == "" then sets the field map to NULL.
Definition at line 97 of file SBend3D.cpp.
References fieldUnits_m, SectorMagneticFieldMap::getDeltaPhi(), SectorField::getPolarBoundingBoxMax(), SectorField::getPolarBoundingBoxMin(), lengthUnits_m, map_m, name, planarArcGeometry_m, polyOrder_m, PlanarArcGeometry::setCurvature(), PlanarArcGeometry::setElementLength(), and smoothOrder_m.
Referenced by OpalSBend3D::update().
setFieldUnits()
void SBend3D::setFieldUnits (double fieldUnits) inline
Set the scale factor
Definition at line 143 of file SBend3D.h.
References fieldUnits_m.
Referenced by OpalSBend3D::update().
setLengthUnits()
void SBend3D::setLengthUnits (double lengthUnits) inline
Set the scale factor
Definition at line 137 of file SBend3D.h.
References lengthUnits_m.
Referenced by OpalSBend3D::update().
setPolynomialOrder()
void SBend3D::setPolynomialOrder (int polyOrder) inline
Set the polynomial order
Definition at line 149 of file SBend3D.h.
References polyOrder_m.
setSmoothingOrder()
void SBend3D::setSmoothingOrder (int polyOrder) inline
Set the smoothing factor
Definition at line 155 of file SBend3D.h.
References smoothOrder_m.
Member Data Documentation
dummy
BMultipoleField SBend3D::dummy private
Definition at line 171 of file SBend3D.h.
Referenced by getField().
fieldUnits_m
double SBend3D::fieldUnits_m private
Definition at line 165 of file SBend3D.h.
Referenced by getFieldUnits(), setFieldMapFileName(), and setFieldUnits().
lengthUnits_m
double SBend3D::lengthUnits_m private
Definition at line 166 of file SBend3D.h.
Referenced by getLengthUnits(), setFieldMapFileName(), and setLengthUnits().
map_m
SectorMagneticFieldMap* SBend3D::map_m private
Definition at line 161 of file SBend3D.h.
Referenced by apply(), getFieldMapFileName(), getSectorMagneticFieldMap(), SBend3D(), setFieldMapFileName(), and ~SBend3D().
planarArcGeometry_m
PlanarArcGeometry SBend3D::planarArcGeometry_m private
Definition at line 163 of file SBend3D.h.
Referenced by getGeometry(), and setFieldMapFileName().
polyOrder_m
int SBend3D::polyOrder_m private
Definition at line 168 of file SBend3D.h.
Referenced by getPolynomialOrder(), setFieldMapFileName(), and setPolynomialOrder().
smoothOrder_m
double SBend3D::smoothOrder_m private
Definition at line 169 of file SBend3D.h.
Referenced by getSmoothingOrder(), setFieldMapFileName(), and setSmoothingOrder().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/SBend3D.h
src/Classic/AbsBeamline/SBend3D.cpp