OPAL (Object Oriented Parallel Accelerator Library): ParticleMatterInteraction Class Reference
ParticleMatterInteraction Class Reference
#include <ParticleMatterInteraction.h>
Public Member Functions
ParticleMatterInteraction ()
Exemplar constructor.
virtual ~ParticleMatterInteraction ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual ParticleMatterInteraction * clone (const std::string &name)
Make clone.
virtual void execute ()
Check the PARTICLEMATTERINTERACTION data.
virtual void update ()
Update the PARTICLEMATTERINTERACTION data.
void print (std::ostream &os) const
Print the object.
void initParticleMatterInteractionHandler (ElementBase &element)
void updateElement (ElementBase *element)
Public Member Functions inherited from Definition
virtual ~Definition ()
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static ParticleMatterInteraction * find (const std::string &name)
Find named PARTICLEMATTERINTERACTION.
Public Attributes
ParticleMatterInteractionHandler * handler_m
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Private Types
enum InteractionType : unsigned short { InteractionType::SCATTERING, InteractionType::BEAMSTRIPPING }
Private Member Functions
ParticleMatterInteraction (const ParticleMatterInteraction &)
void operator= (const ParticleMatterInteraction &)
ParticleMatterInteraction (const std::string &name, ParticleMatterInteraction *parent)
void getInteractionType ()
Private Attributes
InteractionType type_m
Additional Inherited Members
Protected Member Functions inherited from Definition
Definition (int size, const char *name, const char *help)
Constructor for exemplars.
Definition (const std::string &name, Definition *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 34 of file ParticleMatterInteraction.h.
Member Enumeration Documentation
InteractionType
enum ParticleMatterInteraction::InteractionType : unsigned short strong private
Enumerator
SCATTERING
BEAMSTRIPPING
Definition at line 66 of file ParticleMatterInteraction.h.
Constructor & Destructor Documentation
ParticleMatterInteraction() [1/3]
ParticleMatterInteraction::ParticleMatterInteraction ()
Exemplar constructor.
Definition at line 50 of file ParticleMatterInteraction.cpp.
References Object::builtin, clone(), OpalData::define(), OpalData::getInstance(), Object::itsAttr, Attributes::makeBool(), Attributes::makePredefinedString(), Attributes::makeReal(), Object::registerOwnership(), AttributeHandler::STATEMENT, Attrib::Distribution::TYPE, and update().
Referenced by clone().
~ParticleMatterInteraction()
ParticleMatterInteraction::~ParticleMatterInteraction () virtual
Definition at line 102 of file ParticleMatterInteraction.cpp.
References handler_m.
ParticleMatterInteraction() [2/3]
ParticleMatterInteraction::ParticleMatterInteraction (const ParticleMatterInteraction &) private
ParticleMatterInteraction() [3/3]
ParticleMatterInteraction::ParticleMatterInteraction (const std::string & name, ParticleMatterInteraction * parent) private
Definition at line 96 of file ParticleMatterInteraction.cpp.
Member Function Documentation
canReplaceBy()
bool ParticleMatterInteraction::canReplaceBy (Object * object) virtual
Test if replacement is allowed.
Reimplemented from Object.
Definition at line 108 of file ParticleMatterInteraction.cpp.
clone()
ParticleMatterInteraction * ParticleMatterInteraction::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 114 of file ParticleMatterInteraction.cpp.
References name, and ParticleMatterInteraction().
Referenced by ParticleMatterInteraction(), OpalSBend::update(), OpalRBend::update(), OpalECollimator::update(), OpalDegrader::update(), OpalRCollimator::update(), OpalSlit::update(), OpalFlexibleCollimator::update(), OpalPepperPot::update(), OpalCCollimator::update(), OpalRBend3D::update(), OpalDrift::update(), OpalQuadrupole::update(), and OpalVacuum::update().
execute()
void ParticleMatterInteraction::execute () virtual
Check the PARTICLEMATTERINTERACTION data.
Reimplemented from Object.
Definition at line 119 of file ParticleMatterInteraction.cpp.
References update().
find()
ParticleMatterInteraction * ParticleMatterInteraction::find (const std::string & name) static
Find named PARTICLEMATTERINTERACTION.
Definition at line 124 of file ParticleMatterInteraction.cpp.
References OpalData::find(), OpalData::getInstance(), and name.
Referenced by OpalRBend::update(), OpalSBend::update(), OpalECollimator::update(), OpalDegrader::update(), OpalRCollimator::update(), OpalSlit::update(), OpalFlexibleCollimator::update(), OpalPepperPot::update(), OpalCCollimator::update(), OpalRBend3D::update(), OpalDrift::update(), OpalQuadrupole::update(), and OpalVacuum::update().
getInteractionType()
void ParticleMatterInteraction::getInteractionType () private
Definition at line 141 of file ParticleMatterInteraction.cpp.
References BEAMSTRIPPING, Attributes::getString(), Object::itsAttr, SCATTERING, Attrib::Distribution::TYPE, and type_m.
Referenced by initParticleMatterInteractionHandler().
initParticleMatterInteractionHandler()
void ParticleMatterInteraction::initParticleMatterInteractionHandler (ElementBase & element)
Definition at line 156 of file ParticleMatterInteraction.cpp.
References BEAMSTRIPPING, endl(), Attributes::getBool(), getInteractionType(), Object::getOpalName(), Attributes::getReal(), Attributes::getString(), gmsg, handler_m, Object::itsAttr, SCATTERING, and type_m.
Referenced by OpalRBend::update(), OpalSBend::update(), OpalECollimator::update(), OpalDegrader::update(), OpalRCollimator::update(), OpalSlit::update(), OpalFlexibleCollimator::update(), OpalPepperPot::update(), OpalCCollimator::update(), OpalRBend3D::update(), OpalDrift::update(), OpalQuadrupole::update(), and OpalVacuum::update().
operator=()
void ParticleMatterInteraction::operator= (const ParticleMatterInteraction &) private
print()
void ParticleMatterInteraction::print (std::ostream & msg) const virtual
Print the object.
Reimplemented from Object.
Definition at line 184 of file ParticleMatterInteraction.cpp.
References Util::boolToUpperString(), endl(), Attributes::getBool(), ParticleMatterInteractionHandler::getElement(), ElementBase::getName(), Object::getOpalName(), Attributes::getReal(), Attributes::getString(), handler_m, Object::itsAttr, SCATTERING, Attrib::Distribution::TYPE, and type_m.
Referenced by operator<<().
update()
void ParticleMatterInteraction::update () virtual
Update the PARTICLEMATTERINTERACTION data.
Reimplemented from Object.
Definition at line 136 of file ParticleMatterInteraction.cpp.
References Object::getOpalName(), and Object::setOpalName().
Referenced by execute(), and ParticleMatterInteraction().
updateElement()
void ParticleMatterInteraction::updateElement (ElementBase * element)
Definition at line 180 of file ParticleMatterInteraction.cpp.
References handler_m, and ParticleMatterInteractionHandler::updateElement().
Member Data Documentation
handler_m
ParticleMatterInteractionHandler* ParticleMatterInteraction::handler_m
Definition at line 63 of file ParticleMatterInteraction.h.
Referenced by initParticleMatterInteractionHandler(), print(), OpalSBend::update(), OpalRBend::update(), OpalECollimator::update(), OpalDegrader::update(), OpalRCollimator::update(), OpalSlit::update(), OpalFlexibleCollimator::update(), OpalPepperPot::update(), OpalCCollimator::update(), OpalRBend3D::update(), OpalDrift::update(), OpalQuadrupole::update(), OpalVacuum::update(), updateElement(), and ~ParticleMatterInteraction().
type_m
InteractionType ParticleMatterInteraction::type_m private
Definition at line 80 of file ParticleMatterInteraction.h.
Referenced by getInteractionType(), initParticleMatterInteractionHandler(), and print().
The documentation for this class was generated from the following files:
src/Structure/ParticleMatterInteraction.h
src/Structure/ParticleMatterInteraction.cpp