OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyOpalPolynomialTimeDependence Namespace Reference
PyOpal::PyOpalPolynomialTimeDependence Namespace Reference
Functions
BOOST_PYTHON_MODULE (polynomial_time_dependence)
Variables
const char * module_docstring
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyOpalPolynomialTimeDependence::BOOST_PYTHON_MODULE (polynomial_time_dependence)
Definition at line 34 of file PyPolynomialTimeDependence.cpp.
References PyOpal::Globals::Initialise(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::make_class(), and PyOpal::ExceptionTranslation::registerExceptions().
Variable Documentation
module_docstring
const char* PyOpal::PyOpalPolynomialTimeDependence::module_docstring
Initial value:
=
"polynomial_time_dependence module holds a PolynomialTimeDependence class"
Definition at line 11 of file PyPolynomialTimeDependence.cpp.