OPAL (Object Oriented Parallel Accelerator Library): StringStream Class Reference
StringStream Class Reference
A stream of input tokens.
#include <StringStream.h>
Public Member Functions
StringStream (const std::string &s)
Constructor.
virtual ~StringStream ()
virtual Token readToken ()
Read single token from file.
Public Member Functions inherited from TokenStream
TokenStream (const std::string &name)
Constructor.
virtual ~TokenStream ()
void putBack (const Token &token)
Put token back to stream.
const std::string & getName () const
Return stream name.
int getLine () const
Return line number.
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
StringStream ()
StringStream (const StringStream &)
void operator= (const StringStream &)
Token readNumber ()
Token readString ()
Token readWord ()
Private Attributes
const std::string line_m
std::string::size_type currentChar_m
Additional Inherited Members
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from TokenStream
std::string stream_name
int curr_line
bool put_back_flag
Token put_back
Detailed Description
A stream of input tokens.
Definition at line 31 of file StringStream.h.
Constructor & Destructor Documentation
StringStream() [1/3]
StringStream::StringStream (const std::string & s)
Constructor.
Definition at line 31 of file StringStream.cpp.
~StringStream()
StringStream::~StringStream () virtual
Definition at line 38 of file StringStream.cpp.
StringStream() [2/3]
StringStream::StringStream () private
StringStream() [3/3]
StringStream::StringStream (const StringStream &) private
Member Function Documentation
operator=()
void StringStream::operator= (const StringStream &) private
readNumber()
Token StringStream::readNumber () private
Definition at line 107 of file StringStream.cpp.
References currentChar_m, Token::IS_ERROR, and line_m.
Referenced by readToken().
readString()
Token StringStream::readString () private
Definition at line 194 of file StringStream.cpp.
References currentChar_m, Token::IS_STRING, and line_m.
Referenced by readToken().
readToken()
Token StringStream::readToken () virtual
Read single token from file.
Implements TokenStream.
Definition at line 42 of file StringStream.cpp.
References TokenStream::curr_line, currentChar_m, Token::IS_DELIMITER, Token::IS_EOF, Token::IS_ERROR, line_m, TokenStream::put_back, TokenStream::put_back_flag, readNumber(), readString(), readWord(), and TokenStream::stream_name.
readWord()
Token StringStream::readWord () private
Definition at line 222 of file StringStream.cpp.
References currentChar_m, Token::IS_WORD, and line_m.
Referenced by readToken().
Member Data Documentation
currentChar_m
std::string::size_type StringStream::currentChar_m private
Definition at line 62 of file StringStream.h.
Referenced by readNumber(), readString(), readToken(), and readWord().
line_m
const std::string StringStream::line_m private
Definition at line 61 of file StringStream.h.
Referenced by readNumber(), readString(), readToken(), and readWord().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Parser/StringStream.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Parser/StringStream.cpp