OPAL (Object Oriented Parallel Accelerator Library): ippl/src/DataSource/MakeDataSource.h File Reference
MakeDataSource.h File Reference
#include "DataSource/MakeDataSource.hpp"
Classes
class Field< T, Dim, M, C >
class ParticleAttrib< T >
class IpplParticleBase< PLayout >
Functions
template<class T , unsigned Dim, class M , class C >
DataSourceObject * make_DataSourceObject (const char *, DataConnect *, int, Field< T, Dim, M, C > &)
template<class T >
DataSourceObject * make_DataSourceObject (const char *, DataConnect *, int, ParticleAttrib< T > &)
template<class PLayout >
DataSourceObject * make_DataSourceObject (const char *, DataConnect *, int, IpplParticleBase< PLayout > &)
Function Documentation
make_DataSourceObject() [1/3]
template<class T , unsigned Dim, class M , class C > DataSourceObject* make_DataSourceObject (const char * , DataConnect * , int , Field< T, Dim, M, C > &)
Definition at line 53 of file MakeDataSource.hpp.
References DataSourceObject::DataSourceObject(), and DataConnect::DSID().
Referenced by Field< Vector_t, 3, Mesh_t, Center_t >::createDataSourceObject(), IpplParticleBase< T >::createDataSourceObject(), and ParticleAttrib< ParticleOrigin >::createDataSourceObject().
make_DataSourceObject() [2/3]
template<class T > DataSourceObject* make_DataSourceObject (const char * , DataConnect * , int , ParticleAttrib< T > &)
Definition at line 78 of file MakeDataSource.hpp.
References DataSourceObject::DataSourceObject(), and DataConnect::DSID().
make_DataSourceObject() [3/3]
template<class PLayout > DataSourceObject* make_DataSourceObject (const char * , DataConnect * , int , IpplParticleBase< PLayout > &)
Definition at line 103 of file MakeDataSource.hpp.
References DataSourceObject::DataSourceObject(), and DataConnect::DSID().