OPAL (Object Oriented Parallel Accelerator Library): Attributes::PredefinedString Class Reference
Attributes::PredefinedString Class Reference
Parser for an attribute of type string.
#include <PredefinedString.h>
Public Member Functions
PredefinedString (const std::string &name, const std::string &help, const std::initializer_list< std::string > &predefinedStrings, const std::string &defaultValue="_HAS_NO_DEFAULT_")
Constructor.
virtual ~PredefinedString ()
virtual const std::string & getType () const
Return attribute type string `‘string’'.
virtual void parse (Attribute &, Statement &, bool) const
Parse the attribute.
Public Member Functions inherited from AttributeHandler
AttributeHandler (const std::string &name, const std::string &help, AttributeBase *def)
Constructor.
virtual ~AttributeHandler ()
virtual AttributeHandler * clone () const
Make clone.
virtual AttributeBase * getDefault () const
Return default value.
virtual const std::string & getHelp () const
Return help string.
virtual const std::string & getName () const
Return attribute name.
virtual void parseComponent (Attribute &a, Statement &s, bool eval, int i) const
Parse component value.
bool isDeferred () const
Return defer flag.
void setDeferred (bool)
Set or reset defer flag.
bool isReadOnly () const
Return read-only flag.
void setReadOnly (bool)
Set or reset read-only flag.
void setPredefinedValues (const std::set< std::string > &, const std::string &)
Add predefined strings values to the help.
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
PredefinedString ()
PredefinedString (const PredefinedString &)
void operator= (const PredefinedString &)
Private Attributes
std::set< std::string > predefinedStrings_m
Additional Inherited Members
Public Types inherited from AttributeHandler
enum OwnerType {
ELEMENT, COMMAND, SUB_COMMAND, STATEMENT,
NONE
}
Static Public Member Functions inherited from AttributeHandler
static std::multimap< OwnerType, std::string > getOwner (const std::string &att)
static void addAttributeOwner (const std::string &owner, const OwnerType &type, const std::string &name)
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from AttributeHandler
const std::string itsName
Attribute name.
const std::string itsHelp
Help text.
Pointer< AttributeBase > itsDefault
Default value.
bool is_deferred
Defer flag.
bool is_readonly
Read-only flag.
Detailed Description
Parser for an attribute of type string.
Definition at line 30 of file PredefinedString.h.
Constructor & Destructor Documentation
PredefinedString() [1/3]
Attributes::PredefinedString::PredefinedString (const std::string & name, const std::string & help, const std::initializer_list< std::string > & predefinedStrings, const std::string & defaultValue = "_HAS_NO_DEFAULT_")
Constructor.
Definition at line 30 of file PredefinedString.cpp.
References predefinedStrings_m, AttributeHandler::setPredefinedValues(), and Util::toUpper().
~PredefinedString()
Attributes::PredefinedString::~PredefinedString () virtual
Definition at line 43 of file PredefinedString.cpp.
PredefinedString() [2/3]
Attributes::PredefinedString::PredefinedString () private
PredefinedString() [3/3]
Attributes::PredefinedString::PredefinedString (const PredefinedString &) private
Member Function Documentation
getType()
const std::string & Attributes::PredefinedString::getType () const virtual
Return attribute type string `‘string’'.
Implements AttributeHandler.
Definition at line 47 of file PredefinedString.cpp.
operator=()
void Attributes::PredefinedString::operator= (const PredefinedString &) private
parse()
void Attributes::PredefinedString::parse (Attribute & attr, Statement & stat, bool) const virtual
Parse the attribute.
Implements AttributeHandler.
Definition at line 52 of file PredefinedString.cpp.
References Expressions::parseStringValue(), predefinedStrings_m, Attributes::setPredefinedString(), and Util::toUpper().
Member Data Documentation
predefinedStrings_m
std::set<std::string> Attributes::PredefinedString::predefinedStrings_m private
Definition at line 56 of file PredefinedString.h.
Referenced by parse(), and PredefinedString().
The documentation for this class was generated from the following files:
src/Attributes/PredefinedString.h
src/Attributes/PredefinedString.cpp