OPAL (Object Oriented Parallel Accelerator Library): SBendRep Class Reference
SBendRep Class Reference
#include <SBendRep.h>
Public Member Functions
SBendRep (const std::string &name)
Constructor with given name.
SBendRep ()
SBendRep (const SBendRep &)
virtual ~SBendRep ()
virtual ElementBase * clone () const
Return clone.
virtual Channel * getChannel (const std::string &aKey, bool=false)
Construct a read/write channel.
virtual BMultipoleField & getField ()
Get field.
virtual const BMultipoleField & getField () const
Get field.
virtual PlanarArcGeometry & getGeometry ()
Get geometry.
virtual const PlanarArcGeometry & getGeometry () const
Get geometry.
virtual double getB () const
Get field.
virtual void setB (double By)
Set vertical component.
virtual void setField (const BMultipoleField &field)
Set field.
virtual double getEntryFaceRotation () const
Get pole entry face rotation.
virtual double getExitFaceRotation () const
Get exit pole face rotation.
virtual double getEntryFaceCurvature () const
Get entry pole face curvature.
virtual double getExitFaceCurvature () const
Get exit pole face curvature.
virtual void setEntryFaceRotation (double e1)
Set pole entry face rotation.
virtual void setExitFaceRotation (double e2)
Set exit pole face rotation.
virtual void setEntryFaceCurvature (double h1)
Set entry pole face curvature.
virtual void setExitFaceCurvature (double h2)
Set exit pole face curvature.
virtual double getSlices () const
Get number of slices.
virtual double getStepsize () const
Get stepsize.
virtual void setSlices (double sl)
Set number of slices.
virtual void setStepsize (double ds)
Set stepsize.
Public Member Functions inherited from SBend
SBend (const std::string &name)
Constructor with given name.
SBend ()
SBend (const SBend &)
virtual ~SBend ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to SBend.
double getNormalComponent (int) const
Get normal component.
double getSkewComponent (int) const
Get skew component.
void setNormalComponent (int, double)
Set normal component.
void setSkewComponent (int, double)
Set skew component.
virtual ElementType getType () const override
Get element type std::string.
Public Member Functions inherited from Bend2D
Bend2D (const std::string &name)
Constructor with given name.
Bend2D ()
Bend2D (const Bend2D &)
virtual ~Bend2D ()
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
Apply field to particles with coordinates in magnet frame.
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
Apply field to particles in beam frame.
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
virtual void goOnline (const double &kineticEnergy) override
virtual void finalise () override
virtual void getDimensions (double &sBegin, double &sEnd) const override
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
double getBendRadius () const
double getEffectiveCenter () const
double getEffectiveLength () const
void setK1 (double k1)
Set quadrupole field component.
virtual void setEntranceAngle (double entranceAngle) override
void setExitAngle (double exitAngle)
virtual double getExitAngle () const override
std::vector< Vector_t > getOutline () const
MeshData getSurfaceMesh () const
virtual CoordinateSystemTrafo getEdgeToEnd () const override
CoordinateSystemTrafo getBeginToEnd_local () const
virtual bool isInside (const Vector_t &r) const override
void setNSlices (const std::size_t &nSlices)
std::size_t getNSlices () const
std::array< double, 2 > getEntranceFringeFieldLength () const
Get entrance fringe field length.
std::array< double, 2 > getExitFringeFieldLength () const
Get exit fringe field length.
BoundingBox getBoundingBoxInLabCoords () const override
Public Member Functions inherited from BendBase
BendBase ()
BendBase (const BendBase &)
BendBase (const std::string &)
virtual bool bends () const
Indicates that element bends the beam.
double getChordLength () const
virtual void setBendAngle (double angle)
double getBendAngle () const
double getEntranceAngle () const
void setFullGap (double)
double getFullGap () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
double getDesignEnergy () const
std::vector< Vector_t > getDesignPath () const
void setFieldAmplitude (double k0, double k0s)
double getFieldAmplitude () const
void setFieldMapFN (std::string fileName)
std::string getFieldMapFN () const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual void goOffline ()
virtual bool Online ()
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ApertureType, std::vector< double > > getAperture () const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setFlagDeleteOnTransverseExit (bool=true)
bool getFlagDeleteOnTransverseExit () const
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void operator= (const SBendRep &)
Private Attributes
PlanarArcGeometry geometry
The bend geometry.
BMultipoleField field
The multipole expansion.
double rEntry
double rExit
double hEntry
double hExit
double slices
double stepsize
Additional Inherited Members
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from Bend2D
void setMessageHeader (const std::string &header)
double getStartField () const
Protected Member Functions inherited from BendBase
double calcDesignRadius (double fieldAmplitude) const
Calculate design radius from design energy and field amplitude.
double calcFieldAmplitude (double radius) const
Calculate field amplitude from design energy and radius.
double calcBendAngle (double chordLength, double radius) const
Calculate bend angle from chord length and design radius.
double calcDesignRadius (double chordLength, double angle) const
Calculate design radius from chord length and bend angle.
double calcGamma () const
Calculate gamma from design energy.
double calcBetaGamma () const
Calculate beta*gamma from design energy.
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from BendBase
double chordLength_m
double angle_m
Bend angle.
double entranceAngle_m
Fieldmap fieldmap_m
Magnet field map.
const bool fast_m = false
Flag to turn on fast field calculation.
double gap_m
Full vertical gap of the magnets.
double designEnergy_m
Bend design energy (eV).
bool designEnergyChangeable_m
std::vector< Vector_t > refTrajMap_m
Map of reference particle trajectory.
double fieldAmplitudeX_m
double fieldAmplitudeY_m
double fieldAmplitude_m
Field amplitude.
std::string fileName_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 28 of file SBendRep.h.
Constructor & Destructor Documentation
SBendRep() [1/3]
SBendRep::SBendRep (const std::string & name) explicit
Constructor with given name.
Definition at line 87 of file SBendRep.cpp.
References hEntry, hExit, rEntry, and rExit.
SBendRep() [2/3]
SBendRep::SBendRep ()
Definition at line 68 of file SBendRep.cpp.
References hEntry, hExit, rEntry, and rExit.
Referenced by clone().
SBendRep() [3/3]
SBendRep::SBendRep (const SBendRep & rhs)
Definition at line 76 of file SBendRep.cpp.
References hEntry, hExit, rEntry, and rExit.
~SBendRep()
SBendRep::~SBendRep () virtual
Definition at line 95 of file SBendRep.cpp.
Member Function Documentation
clone()
ElementBase * SBendRep::clone () const virtual
Return clone.
Implements ElementBase.
Definition at line 99 of file SBendRep.cpp.
References SBendRep().
getB()
double SBendRep::getB () const virtual
Get field.
Implements SBend.
Definition at line 155 of file SBendRep.cpp.
References field, and BMultipoleField::getNormalComponent().
getChannel()
Channel * SBendRep::getChannel (const std::string & aKey, bool create = false) virtual
Construct a read/write channel.
Reimplemented from ElementBase.
Definition at line 104 of file SBendRep.cpp.
References ElementBase::getChannel(), SBend::getNormalComponent(), SBend::getSkewComponent(), Hypervolume::n, SBend::setNormalComponent(), and SBend::setSkewComponent().
getEntryFaceCurvature()
double SBendRep::getEntryFaceCurvature () const virtual
Get entry pole face curvature.
Implements SBend.
Definition at line 181 of file SBendRep.cpp.
References hEntry.
getEntryFaceRotation()
double SBendRep::getEntryFaceRotation () const virtual
Get pole entry face rotation.
Implements SBend.
Definition at line 164 of file SBendRep.cpp.
References rEntry.
getExitFaceCurvature()
double SBendRep::getExitFaceCurvature () const virtual
Get exit pole face curvature.
Implements SBend.
Definition at line 185 of file SBendRep.cpp.
References hExit.
getExitFaceRotation()
double SBendRep::getExitFaceRotation () const virtual
Get exit pole face rotation.
Implements SBend.
Definition at line 169 of file SBendRep.cpp.
References rExit.
getField() [1/2]
BMultipoleField & SBendRep::getField () virtual
Get field.
Implements SBend.
Definition at line 137 of file SBendRep.cpp.
References field.
getField() [2/2]
const BMultipoleField & SBendRep::getField () const virtual
Get field.
Implements SBend.
Definition at line 141 of file SBendRep.cpp.
References field.
getGeometry() [1/2]
PlanarArcGeometry & SBendRep::getGeometry () virtual
Get geometry.
Implements SBend.
Definition at line 146 of file SBendRep.cpp.
References geometry.
Referenced by OpalSBend::update().
getGeometry() [2/2]
const PlanarArcGeometry & SBendRep::getGeometry () const virtual
Get geometry.
Implements SBend.
Definition at line 150 of file SBendRep.cpp.
References geometry.
getSlices()
double SBendRep::getSlices () const virtual
Get number of slices.
Implements SBend.
Definition at line 198 of file SBendRep.cpp.
References slices.
getStepsize()
double SBendRep::getStepsize () const virtual
Get stepsize.
Implements SBend.
Definition at line 202 of file SBendRep.cpp.
References stepsize.
operator=()
void SBendRep::operator= (const SBendRep &) private
setB()
void SBendRep::setB (double By) virtual
Set vertical component.
Definition at line 159 of file SBendRep.cpp.
References field, and BMultipoleField::setNormalComponent().
setEntryFaceCurvature()
void SBendRep::setEntryFaceCurvature (double h1) virtual
Set entry pole face curvature.
Definition at line 189 of file SBendRep.cpp.
References hEntry.
Referenced by OpalSBend::update().
setEntryFaceRotation()
void SBendRep::setEntryFaceRotation (double e1) virtual
Set pole entry face rotation.
Definition at line 173 of file SBendRep.cpp.
References rEntry.
Referenced by OpalSBend::update().
setExitFaceCurvature()
void SBendRep::setExitFaceCurvature (double h2) virtual
Set exit pole face curvature.
Definition at line 193 of file SBendRep.cpp.
References hExit.
Referenced by OpalSBend::update().
setExitFaceRotation()
void SBendRep::setExitFaceRotation (double e2) virtual
Set exit pole face rotation.
Definition at line 177 of file SBendRep.cpp.
References rExit.
Referenced by OpalSBend::update().
setField()
void SBendRep::setField (const BMultipoleField & field) virtual
Set field.
Definition at line 215 of file SBendRep.cpp.
References field.
Referenced by OpalSBend::update().
setSlices()
void SBendRep::setSlices (double sl) virtual
Set number of slices.
Definition at line 206 of file SBendRep.cpp.
References slices.
Referenced by OpalSBend::update().
setStepsize()
void SBendRep::setStepsize (double ds) virtual
Set stepsize.
Definition at line 210 of file SBendRep.cpp.
References stepsize.
Referenced by OpalSBend::update().
Member Data Documentation
field
BMultipoleField SBendRep::field private
The multipole expansion.
Definition at line 142 of file SBendRep.h.
Referenced by getB(), getField(), setB(), and setField().
geometry
PlanarArcGeometry SBendRep::geometry private
The bend geometry.
Definition at line 139 of file SBendRep.h.
Referenced by getGeometry().
hEntry
double SBendRep::hEntry private
Definition at line 147 of file SBendRep.h.
Referenced by getEntryFaceCurvature(), SBendRep(), and setEntryFaceCurvature().
hExit
double SBendRep::hExit private
Definition at line 148 of file SBendRep.h.
Referenced by getExitFaceCurvature(), SBendRep(), and setExitFaceCurvature().
rEntry
double SBendRep::rEntry private
Definition at line 145 of file SBendRep.h.
Referenced by getEntryFaceRotation(), SBendRep(), and setEntryFaceRotation().
rExit
double SBendRep::rExit private
Definition at line 146 of file SBendRep.h.
Referenced by getExitFaceRotation(), SBendRep(), and setExitFaceRotation().
slices
double SBendRep::slices private
Definition at line 151 of file SBendRep.h.
Referenced by getSlices(), and setSlices().
stepsize
double SBendRep::stepsize private
Definition at line 152 of file SBendRep.h.
Referenced by getStepsize(), and setStepsize().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/BeamlineCore/SBendRep.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/BeamlineCore/SBendRep.cpp