OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Classic/FixedAlgebra/TransportFun.hpp File Reference
TransportFun.hpp File Reference
#include "FixedAlgebra/TransportFun.h"
#include "FixedAlgebra/FMatrix.h"
#include "FixedAlgebra/FVector.h"
#include "FixedAlgebra/TransportMap.h"
#include "Utilities/DivideError.h"
#include "Utilities/FormatError.h"
#include <iomanip>
#include <iostream>
#include <cstring>
Functions
template<class T , int N>
TransportFun< T, N > operator+ (const TransportFun< T, N > &lhs, const TransportFun< T, N > &rhs)
Add.
template<class T , int N>
TransportFun< T, N > operator- (const TransportFun< T, N > &lhs, const TransportFun< T, N > &rhs)
Subtract.
template<class T , int N>
TransportFun< T, N > operator+ (const TransportFun< T, N > &lhs, const T &rhs)
Add.
template<class T , int N>
TransportFun< T, N > operator- (const TransportFun< T, N > &lhs, const T &rhs)
Subtract.
template<class T , int N>
TransportFun< T, N > operator+ (const T &lhs, const TransportFun< T, N > &rhs)
Add.
template<class T , int N>
TransportFun< T, N > operator- (const T &lhs, const TransportFun< T, N > &rhs)
Subtract.
template<class T , int N>
TransportFun< T, N > operator* (const TransportFun< T, N > &lhs, const TransportFun< T, N > &rhs)
Multiply.
template<class T , int N>
TransportFun< T, N > operator/ (const TransportFun< T, N > &lhs, const TransportFun< T, N > &rhs)
Divide.
template<class T , int N>
TransportFun< T, N > operator* (const TransportFun< T, N > &lhs, const T &rhs)
Multiply.
template<class T , int N>
TransportFun< T, N > operator/ (const TransportFun< T, N > &lhs, const T &rhs)
Divide.
template<class T , int N>
TransportFun< T, N > operator* (const T &lhs, const TransportFun< T, N > &rhs)
Multiply.
template<class T , int N>
TransportFun< T, N > operator/ (const T &lhs, const TransportFun< T, N > &rhs)
Divide 1 / TransportFun.
template<class T , int N>
bool operator== (const T &lhs, const TransportFun< T, N > &rhs)
Equality.
template<class T , int N>
bool operator!= (const T &lhs, const TransportFun< T, N > &rhs)
Inequality.
template<class T , int N>
std::istream & operator>> (std::istream &is, TransportFun< T, N > &fun)
Extract TransportFun from stream [b]is[/b].
template<class T , int N>
std::ostream & operator<< (std::ostream &os, const TransportFun< T, N > &fun)
Insert TransportFun to stream [b]os[/b].
Function Documentation
operator!=()
template<class T , int N> bool operator!= (const T & lhs, const TransportFun< T, N > & rhs) inline
Inequality.
Definition at line 547 of file TransportFun.hpp.
operator*() [1/3]
template<class T , int N> TransportFun<T, N> operator* (const TransportFun< T, N > & lhs, const TransportFun< T, N > & rhs) inline
Multiply.
Definition at line 502 of file TransportFun.hpp.
References TransportFun< T, N >::multiply().
operator*() [2/3]
template<class T , int N> TransportFun<T, N> operator* (const TransportFun< T, N > & lhs, const T & rhs) inline
Multiply.
Definition at line 514 of file TransportFun.hpp.
operator*() [3/3]
template<class T , int N> TransportFun<T, N> operator* (const T & lhs, const TransportFun< T, N > & rhs) inline
Multiply.
Definition at line 528 of file TransportFun.hpp.
operator+() [1/3]
template<class T , int N> TransportFun<T, N> operator+ (const TransportFun< T, N > & lhs, const TransportFun< T, N > & rhs) inline
Add.
Definition at line 460 of file TransportFun.hpp.
operator+() [2/3]
template<class T , int N> TransportFun<T, N> operator+ (const TransportFun< T, N > & lhs, const T & rhs) inline
Add.
Definition at line 474 of file TransportFun.hpp.
operator+() [3/3]
template<class T , int N> TransportFun<T, N> operator+ (const T & lhs, const TransportFun< T, N > & rhs) inline
Add.
Definition at line 488 of file TransportFun.hpp.
operator-() [1/3]
template<class T , int N> TransportFun<T, N> operator- (const TransportFun< T, N > & lhs, const TransportFun< T, N > & rhs) inline
Subtract.
Definition at line 467 of file TransportFun.hpp.
operator-() [2/3]
template<class T , int N> TransportFun<T, N> operator- (const TransportFun< T, N > & lhs, const T & rhs) inline
Subtract.
Definition at line 481 of file TransportFun.hpp.
operator-() [3/3]
template<class T , int N> TransportFun<T, N> operator- (const T & lhs, const TransportFun< T, N > & rhs) inline
Subtract.
Definition at line 495 of file TransportFun.hpp.
operator/() [1/3]
template<class T , int N> TransportFun<T, N> operator/ (const TransportFun< T, N > & lhs, const TransportFun< T, N > & rhs) inline
Divide.
Definition at line 508 of file TransportFun.hpp.
References TransportFun< T, N >::inverse(), and TransportFun< T, N >::multiply().
operator/() [2/3]
template<class T , int N> TransportFun<T, N> operator/ (const TransportFun< T, N > & lhs, const T & rhs) inline
Divide.
Definition at line 521 of file TransportFun.hpp.
operator/() [3/3]
template<class T , int N> TransportFun<T, N> operator/ (const T & lhs, const TransportFun< T, N > & rhs) inline
Divide 1 / TransportFun.
Definition at line 535 of file TransportFun.hpp.
References TransportFun< T, N >::inverse().
operator<<()
template<class T , int N> std::ostream& operator<< (std::ostream & os, const TransportFun< T, N > & fun)
Insert TransportFun to stream [b]os[/b].
Definition at line 559 of file TransportFun.hpp.
operator==()
template<class T , int N> bool operator== (const T & lhs, const TransportFun< T, N > & rhs) inline
Equality.
Definition at line 541 of file TransportFun.hpp.
operator>>()
template<class T , int N> std::istream& operator>> (std::istream & is, TransportFun< T, N > & fun)
Extract TransportFun from stream [b]is[/b].
Definition at line 553 of file TransportFun.hpp.
References TransportFun< T, N >::get().