OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyParser Namespace Reference
PyOpal::PyParser Namespace Reference
Functions
int initialise_from_opal_file (std::string file_name)
boost::python::list list_objects ()
BOOST_PYTHON_MODULE (parser)
Variables
std::string initialise_from_opal_file_docstring
std::string list_objects_docstring
std::string module_docstring
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyParser::BOOST_PYTHON_MODULE (parser)
Definition at line 73 of file PyParser.cpp.
References PyOpal::Globals::Initialise(), initialise_from_opal_file(), initialise_from_opal_file_docstring, list_objects(), list_objects_docstring, module_docstring, and PyOpal::ExceptionTranslation::registerExceptions().
initialise_from_opal_file()
int PyOpal::PyParser::initialise_from_opal_file (std::string file_name)
Definition at line 42 of file PyParser.cpp.
References opalMain().
Referenced by BOOST_PYTHON_MODULE().
list_objects()
boost::python::list PyOpal::PyParser::list_objects ()
Definition at line 60 of file PyParser.cpp.
References OpalData::getAllNames(), and OpalData::getInstance().
Referenced by BOOST_PYTHON_MODULE().
Variable Documentation
initialise_from_opal_file_docstring
std::string PyOpal::PyParser::initialise_from_opal_file_docstring
Initial value:
=
"Initialise from opal file\n"
"- file_name: string corresponding to the file name of the OPAL\n"
"  file.\n"
"Note that if file_name is not valid, OPAL may terminate the python script\n"
"execution abnormally (without the usual python exit semantics).\n"
"\n"
"Returns an integer; 0 for successful execution or non-zero if an error\n"
"occurred.\n"
Definition at line 32 of file PyParser.cpp.
Referenced by BOOST_PYTHON_MODULE().
list_objects_docstring
std::string PyOpal::PyParser::list_objects_docstring
Initial value:
=
"List the objects that are known by the Opal parser, either through calls to\n"
"initialise_from_opal_file or through calls directly to the python API\n"
"\n"
"Returns a list of strings, each one corresponding to the name of a\n"
"particular object\n"
Definition at line 53 of file PyParser.cpp.
Referenced by BOOST_PYTHON_MODULE().
module_docstring
std::string PyOpal::PyParser::module_docstring
Initial value:
=
"The parser module is used to load an OPAL input file from within python"
Definition at line 70 of file PyParser.cpp.
Referenced by BOOST_PYTHON_MODULE().