BUNCH
{
  
  bunch-sampling
  {
    sample						= false
    directory						= ./
    base-name 						= bunch-sampling/bunch
    rhythm						= 8
  }
    
  bunch-visualization
  {
    sample						= false
    directory						= ./
    base-name						= bunch-visualization/bunch
    rhythm						= 5.0
  }
    
  bunch-profile
  {
    sample						= false
    directory						= ./
    base-name						= bunch-profile/bunch
    time						= 16.0
  }
}

FIELD
{
  field-initialization
  {
    type      						= gaussian-beam
    position  						= ( 0.0, 0.0, -2500.0)
    direction						= ( 0.0, 0.0, 1.0)
    polarization 					= ( 0.0, 1.0, 0.0)
    radius-parallel					= 0.5
    radius-perpendicular				= 0.5
    strength-parameter					= 0.0
    signal-type    					= gaussian
    offset    						= 0.00e-9
    variance  						= 1.00
    wavelength						= 0.0
    CEP  						= 0.0
  }
    
  field-visualization
  {
    sample						= false
    type						= in-plane
    field						= Ex
    field						= Ey
    field						= Ez
    plane						= x-normal
    position						= (0.0, 0.0, 110.0)
    directory						= ./
    base-name						= field-visualization/field1
    rhythm						= 5.0
  }
  
  field-visualization
  {
    sample						= false
    type						= in-plane
    field						= Ex
    field						= Ey
    field						= Ez
    plane						= y-normal
    position						= (0.0, 0.0, 110.0)
    directory						= ./
    base-name						= field-visualization/field2
    rhythm						= 30.0
  }
    
  field-profile
  {
    sample						= false
    field                           			= Q
    directory						= ./
    base-name						= field-profile/field
    rhythm						= 100
  }
}

FEL-OUTPUT
{
  radiation-power
  {
    sample						= true
    type						= at-point
    directory						= ./
    base-name						= power-sampling/power
    plane-position					= 110
    normalized-frequency				= 1.00
  }
}
