OPAL (Object Oriented Parallel Accelerator Library): PyPolynomialCoefficient Namespace Reference
PyPolynomialCoefficient Namespace Reference
Classes
struct PyCoefficient
Functions
int _init (PyObject *self, PyObject *args, PyObject *kwds)
PyObject * _alloc (PyTypeObject *type, Py_ssize_t nitems)
PyObject * _new (PyTypeObject *type, Py_ssize_t nitems)
void _free (PyCoefficient *self)
void _dealloc (PyCoefficient *self)
Variables
std::string class_docstring
Function Documentation
_alloc()
PyObject * PyPolynomialCoefficient::_alloc (PyTypeObject * type, Py_ssize_t nitems)
_alloc allocates memory for PyPolynomialMap
Parameters
type - pointer to aPyPolynomialMapType object, as defined in PyPolynomialMap.cc
returns a PyPolynomialMap* (cast as a PyObject*); caller owns this memory
Definition at line 69 of file PyPolynomialCoefficient.cpp.
References PyPolynomialCoefficient::PyCoefficient::coeff.
Referenced by _new().
_dealloc()
void PyPolynomialCoefficient::_dealloc (PyCoefficient * self)
Definition at line 90 of file PyPolynomialCoefficient.cpp.
References _free().
_free()
void PyPolynomialCoefficient::_free (PyCoefficient * self)
Definition at line 82 of file PyPolynomialCoefficient.cpp.
Referenced by _dealloc().
_init()
int PyPolynomialCoefficient::_init (PyObject * self, PyObject * args, PyObject * kwds)
_init initialises an allocated PyPolynomialMap object
Parameters
self an initialised PyPolynomialMap* cast as a PyObject*; caller owns this memory
args not used
kwds not used
Returns
0 on success; -1 on failure
Definition at line 14 of file PyPolynomialCoefficient.cpp.
References PyPolynomialCoefficient::PyCoefficient::coeff.
_new()
PyObject * PyPolynomialCoefficient::_new (PyTypeObject * type, Py_ssize_t nitems)
Definition at line 78 of file PyPolynomialCoefficient.cpp.
References _alloc().
Variable Documentation
class_docstring
std::string PyPolynomialCoefficient::class_docstring
Initial value:
=
std::string("PolynomialCoefficient docstring\n")
Definition at line 102 of file PyPolynomialCoefficient.cpp.