OPAL (Object Oriented Parallel Accelerator Library): PyOpal::PyFieldSolverNS Namespace Reference
PyOpal::PyFieldSolverNS Namespace Reference
Functions
void registerFieldSolver (PyOpalObjectNS::PyOpalObject< FieldSolver > &pyfs)
BOOST_PYTHON_MODULE (field_solver)
Function Documentation
BOOST_PYTHON_MODULE()
PyOpal::PyFieldSolverNS::BOOST_PYTHON_MODULE (field_solver)
Definition at line 64 of file PyFieldSolver.cpp.
References Hypervolume::fs, PyOpal::Globals::Initialise(), PyOpal::ExceptionTranslation::registerExceptions(), and registerFieldSolver().
registerFieldSolver()
void PyOpal::PyFieldSolverNS::registerFieldSolver (PyOpalObjectNS::PyOpalObject< FieldSolver > & pyfs)
Definition at line 51 of file PyFieldSolver.cpp.
References OpalData::define(), Hypervolume::fs, OpalData::getInstance(), and PyOpal::PyOpalObjectNS::PyOpalObject< C >::getOpalShared().
Referenced by BOOST_PYTHON_MODULE().