OPAL (Object Oriented Parallel Accelerator Library): ParallelCyclotronTracker Class Reference
ParallelCyclotronTracker Class Reference
#include <ParallelCyclotronTracker.h>
Classes
struct settings
Public Types
typedef std::vector< double > dvector_t
typedef std::vector< int > ivector_t
typedef std::pair< double[8], Component * > element_pair
typedef std::pair< ElementType, element_pair > type_pair
typedef std::list< type_pair * > beamline_list
Public Types inherited from AbstractTracker
enum {
X, PX, Y, PY,
T, PT
}
Public Member Functions
ParallelCyclotronTracker (const Beamline &bl, PartBunchBase< double, 3 > *bunch, DataSink &ds, const PartData &data, bool revBeam, bool revTrack, int maxSTEPS, Steppers::TimeIntegrator timeintegrator, const int &numBunch, const double &mbEta, const double &mbPara, const std::string &mbMode, const std::string &mbBinning)
Constructor.
virtual ~ParallelCyclotronTracker ()
virtual void execute ()
Apply the algorithm to the top-level beamline.
bool computeExternalFields_m (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &Efield, Vector_t &Bfield)
Calculate the field map at an arbitrary point.
virtual void visitBeamline (const Beamline &)
Apply the algorithm to a beam line.
virtual void visitCCollimator (const CCollimator &)
Apply the algorithm to a collimator.
virtual void visitCorrector (const Corrector &)
Apply the algorithm to a closed orbit corrector.
virtual void visitCyclotron (const Cyclotron &cycl)
Apply the algorithm to a cyclotron.
virtual void visitDegrader (const Degrader &)
Apply the algorithm to a degrader.
virtual void visitDrift (const Drift &)
Apply the algorithm to a drift space.
virtual void visitFlexibleCollimator (const FlexibleCollimator &)
Apply the algorithm to a flexible collimator.
virtual void visitMarker (const Marker &)
Apply the algorithm to a marker.
virtual void visitMonitor (const Monitor &)
Apply the algorithm to a beam position monitor.
virtual void visitMultipole (const Multipole &)
Apply the algorithm to a multipole.
virtual void visitMultipoleT (const MultipoleT &)
Apply the algorithm to an arbitrary multipole.
virtual void visitMultipoleTStraight (const MultipoleTStraight &)
Apply the algorithm to an arbitrary straight multipole.
virtual void visitMultipoleTCurvedConstRadius (const MultipoleTCurvedConstRadius &)
Apply the algorithm to an arbitrary curved multipole of constant radius.
virtual void visitMultipoleTCurvedVarRadius (const MultipoleTCurvedVarRadius &)
Apply the algorithm to an arbitrary curved multipole of variable radius.
virtual void visitOffset (const Offset &)
Apply the algorithm to a offset (placement).
virtual void visitOutputPlane (const OutputPlane &)
Apply the algorithm to a outputplane.
virtual void visitProbe (const Probe &)
Apply the algorithm to a probe.
virtual void visitRBend (const RBend &)
Apply the algorithm to a rectangular bend.
virtual void visitRFCavity (const RFCavity &)
Apply the algorithm to a RF cavity.
virtual void visitRing (const Ring &ring)
Apply the algorithm to a ring.
virtual void visitSBend (const SBend &)
Apply the algorithm to a sector bend.
virtual void visitSBend3D (const SBend3D &)
Apply the algorithm to a sector bend with 3D field map.
virtual void visitScalingFFAMagnet (const ScalingFFAMagnet &bend)
Apply the algorithm to a scaling FFA magnet.
virtual void visitSeptum (const Septum &)
Apply the algorithm to a septum.
virtual void visitSolenoid (const Solenoid &)
Apply the algorithm to a solenoid.
virtual void visitStripper (const Stripper &)
Apply the algorithm to a particle stripper.
virtual void visitVacuum (const Vacuum &)
Apply the algorithm to a vacuum space.
virtual void visitVariableRFCavity (const VariableRFCavity &cav)
Apply the algorithm to a variabel RF cavity.
virtual void visitVariableRFCavityFringeField (const VariableRFCavityFringeField &cav)
Apply the algorithm to a variable RF cavity with Fringe Field.
virtual void visitVerticalFFAMagnet (const VerticalFFAMagnet &bend)
Apply the algorithm to a vertical FFA magnet.
void setLastDumpedStep (const int para)
set last dumped step
void bgf_main_collision_test ()
void initializeBoundaryGeometry ()
Ring * getRing () const
void setPr (double x)
Method for restart.
void setPt (double x)
void setPz (double x)
void setR (double x)
void setTheta (double x)
void setZ (double x)
void setBeGa (double x)
void setPhi (double x)
void setPsi (double x)
void setPreviousH5Local (bool x)
Public Member Functions inherited from Tracker
Tracker (const Beamline &, const PartData &, bool backBeam, bool backTrack)
Constructor.
Tracker (const Beamline &, PartBunchBase< double, 3 > *bunch, const PartData &, bool backBeam, bool backTrack)
Constructor.
virtual ~Tracker ()
const PartBunchBase< double, 3 > * getBunch () const
Return the current bunch.
void addToBunch (const OpalParticle &)
Add particle to bunch.
virtual void visitComponent (const Component &)
Store the bunch.
virtual void setNumBunch (short)
set total number of tracked bunches
virtual short getNumBunch ()
get total number of tracked bunches
Public Member Functions inherited from AbstractTracker
AbstractTracker (const Beamline &, const PartData &, bool backBeam, bool backTrack)
Constructor.
virtual ~AbstractTracker ()
Public Member Functions inherited from DefaultVisitor
DefaultVisitor (const Beamline &beamline, bool backBeam, bool backTrack)
Constructor.
virtual ~DefaultVisitor ()=0
virtual void visitFlaggedElmPtr (const FlaggedElmPtr &)
Apply the algorithm to a FlaggedElmPtr.
virtual void visitRBend3D (const RBend3D &)
Apply the algorithm to a rectangular bend.
virtual void visitSource (const Source &)
Apply the algorithm to a source.
virtual void visitTravelingWave (const TravelingWave &)
Apply the algorithm to a traveling wave.
Public Member Functions inherited from BeamlineVisitor
BeamlineVisitor ()
virtual ~BeamlineVisitor ()
Private Types
enum TrackingMode : unsigned short { TrackingMode::UNDEFINED, TrackingMode::SINGLE, TrackingMode::SEO, TrackingMode::BUNCH }
typedef std::function< bool(const double &, const size_t &, Vector_t &, Vector_t &)> function_t
Private Member Functions
ParallelCyclotronTracker ()
ParallelCyclotronTracker (const ParallelCyclotronTracker &)
void operator= (const ParallelCyclotronTracker &)
void MtsTracker ()
void GenericTracker ()
bool getFieldsAtPoint (const double &t, const size_t &Pindex, Vector_t &Efield, Vector_t &Bfield)
void dumpAngle (const double &theta, double &prevAzimuth, double &azimuth, const short &bunchNr=0)
double computeRadius (const Vector_t &meanR) const
void computePathLengthUpdate (std::vector< double > &dl, const double &dt)
void openFiles (size_t numFiles, std::string fn)
@ open / close output coordinate files
void closeFiles ()
void buildupFieldList (double BcParameter[], ElementType elementType, Component *elptr)
double calculateAngle (double x, double y)
double calculateAngle2 (double x, double y)
bool checkGapCross (Vector_t Rold, Vector_t Rnew, RFCavity *rfcavity, double &DistOld)
bool RFkick (RFCavity *rfcavity, const double t, const double dt, const int Pindex)
bool getTunes (dvector_t &t, dvector_t &r, dvector_t &z, int lastTurn, double &nur, double &nuz)
Vector_t calcMeanR (short bunchNr=-1) const
Vector_t calcMeanP () const
void repartition ()
void globalToLocal (ParticleAttrib< Vector_t > &vectorArray, double phi, Vector_t const translationToGlobal=0)
void localToGlobal (ParticleAttrib< Vector_t > &vectorArray, double phi, Vector_t const translationToGlobal=0)
void globalToLocal (ParticleAttrib< Vector_t > &vectorArray, Quaternion_t const quaternion, Vector_t const meanR=Vector_t(0.0))
void localToGlobal (ParticleAttrib< Vector_t > &vectorArray, Quaternion_t const quaternion, Vector_t const meanR=Vector_t(0.0))
void globalToLocal (ParticleAttrib< Vector_t > &particleVectors, double const phi, double const psi, Vector_t const meanR=Vector_t(0.0))
void localToGlobal (ParticleAttrib< Vector_t > &particleVectors, double const phi, double const psi, Vector_t const meanR=Vector_t(0.0))
void globalToLocal (Vector_t &myVector, double const phi, double const psi, Vector_t const meanR=Vector_t(0.0))
void localToGlobal (Vector_t &myVector, double const phi, double const psi, Vector_t const meanR=Vector_t(0.0))
void rotateWithQuaternion (ParticleAttrib< Vector_t > &vectorArray, Quaternion_t const quaternion)
void getQuaternionTwoVectors (Vector_t u, Vector_t v, Quaternion_t &quaternion)
void normalizeQuaternion (Quaternion_t &quaternion)
void normalizeVector (Vector_t &vector)
void rotateAroundZ (ParticleAttrib< Vector_t > &particleVectors, double const phi)
void rotateAroundX (ParticleAttrib< Vector_t > &particleVectors, double const psi)
void rotateAroundZ (Vector_t &myVector, double const phi)
void rotateAroundX (Vector_t &myVector, double const psi)
bool push (double h)
bool kick (double h)
void borisExternalFields (double h)
bool applyPluginElements (const double dt)
bool deleteParticle (bool=false)
void initTrackOrbitFile ()
void singleParticleDump ()
void bunchDumpStatData ()
void bunchDumpPhaseSpaceData ()
void evaluateSpaceChargeField ()
void initDistInGlobalFrame ()
void setTimeStep ()
void checkFileMomentum ()
void checkNumPart (std::string s)
double getHarmonicNumber () const
bool isTurnDone ()
Check if turn done.
void update_m (double &t, const double &dt, const bool &finishedTurn)
Update time and path length, write to output files.
std::tuple< double, double, double > initializeTracking_m ()
void finalizeTracking_m (dvector_t &Ttime, dvector_t &Tdeltr, dvector_t &Tdeltz, ivector_t &TturnNumber)
void setTrackingMode ()
void seoMode_m (double &t, const double dt, bool &finishedTurn, dvector_t &Ttime, dvector_t &Tdeltr, dvector_t &Tdeltz, ivector_t &TturnNumber)
void singleMode_m (double &t, const double dt, bool &finishedTurn, double &oldReferenceTheta)
void bunchMode_m (double &t, const double dt, bool &finishedTurn)
void gapCrossKick_m (size_t i, double t, double dt, const Vector_t &Rold, const Vector_t &Pold)
void dumpAzimuthAngles_m (const double &t, const Vector_t &R, const Vector_t &P, const double &oldReferenceTheta, const double &temp_meanTheta)
void dumpThetaEachTurn_m (const double &t, const Vector_t &R, const Vector_t &P, const double &temp_meanTheta, bool &finishedTurn)
void computeSpaceChargeFields_m ()
bool computeExternalFields_m (const size_t &i, const double &t, Vector_t &Efield, Vector_t &Bfield)
void injectBunch (bool &flagTransition)
void saveInjectValues ()
bool isMultiBunch () const
bool hasMultiBunch () const
void updatePathLength (const double &dt)
void updateTime (const double &dt)
void updateAzimuthAndRadius ()
void initPathLength ()
Private Attributes
beamline_list FieldDimensions
std::list< Component * > myElements
Beamline * itsBeamline
std::vector< PluginElement * > pluginElements_m
std::vector< CavityCrossData > cavCrossDatas_m
DataSink * itsDataSink
BoundaryGeometry * bgf_m
Cyclotron * cycl_m
int maxSteps_m
The maximal number of steps the system is integrated.
double bega
The reference variables.
double referenceR
double referenceTheta
double beamInitialRotation = 0.0
double referenceZ = 0.0
double referencePr
double referencePt
double referencePz = 0.0
double referencePtot
double referencePsi
double referencePhi
bool spiral_flag = false
Vector_t PreviousMeanP
bool previousH5Local
double sinRefTheta_m
double cosRefTheta_m
std::unique_ptr< MultiBunchHandler > mbHandler_m
int lastDumpedStep_m
double pathLength_m
long long step_m
long long restartStep0_m
int turnnumber_m
double azimuth_m
double prevAzimuth_m
Vector_t FDext_m [2]
Vector_t extE_m
Vector_t extB_m
const int myNode_m
const size_t initialLocalNum_m
const size_t initialTotalNum_m
std::vector< std::unique_ptr< std::ofstream > > outfTheta_m
output coordinates at different azimuthal angles and one after every turn
std::vector< double > azimuth_angle_m
the different azimuthal angles for the outfTheta_m output files
std::ofstream outfTrackOrbit_m
IpplTimings::TimerRef IntegrationTimer_m
IpplTimings::TimerRef DumpTimer_m
IpplTimings::TimerRef TransformTimer_m
IpplTimings::TimerRef BinRepartTimer_m
IpplTimings::TimerRef PluginElemTimer_m
IpplTimings::TimerRef DelParticleTimer_m
Ring * opalRing_m
std::unique_ptr< LossDataSink > lossDs_m
std::unique_ptr< Stepper< function_t > > itsStepper_mp
struct ParallelCyclotronTracker::settings setup_m
TrackingMode mode_m
Steppers::TimeIntegrator stepper_m
matrix_t rotation_m
Static Private Attributes
static Vector_t const xaxis = Vector_t(1.0, 0.0, 0.0)
The positive axes unit vectors.
static Vector_t const yaxis = Vector_t(0.0, 1.0, 0.0)
static Vector_t const zaxis = Vector_t(0.0, 0.0, 1.0)
Additional Inherited Members
Public Attributes inherited from Tracker
FieldList cavities_m
const Beamline & itsBeamline_m
Protected Member Functions inherited from Tracker
void applyDrift (double length)
Apply a drift length.
void applyThinMultipole (const BMultipoleField &field, double factor)
void applyThinSBend (const BMultipoleField &field, double scale, double h)
void applyTransform (const Euclid3D &, double refLength=0.0)
Apply a geometric transformation.
FTps< double, 2 > buildMultipoleVectorPotential2D (const BMultipoleField &)
Construct vector potential for a Multipole.
FTps< double, 6 > buildMultipoleVectorPotential (const BMultipoleField &)
Construct vector potential for a Multipole.
FTps< double, 2 > buildSBendVectorPotential2D (const BMultipoleField &, double h)
Construct vector potential for a SBend.
FTps< double, 6 > buildSBendVectorPotential (const BMultipoleField &, double h)
Construct vector potential for a SBend.
Protected Attributes inherited from Tracker
PartBunchBase< double, 3 > * itsBunch_m
The bunch of particles to be tracked.
Protected Attributes inherited from AbstractTracker
const PartData itsReference
The reference information.
Protected Attributes inherited from DefaultVisitor
const Beamline & itsLine
bool back_beam
bool back_track
bool back_path
double flip_B
double flip_s
Detailed Description
Definition at line 55 of file ParallelCyclotronTracker.h.
Member Typedef Documentation
beamline_list
typedef std::list<type_pair*> ParallelCyclotronTracker::beamline_list
Definition at line 62 of file ParallelCyclotronTracker.h.
dvector_t
typedef std::vector<double> ParallelCyclotronTracker::dvector_t
Definition at line 58 of file ParallelCyclotronTracker.h.
element_pair
typedef std::pair<double[8], Component*> ParallelCyclotronTracker::element_pair
Definition at line 60 of file ParallelCyclotronTracker.h.
function_t
typedef std::function<bool(const double&, const size_t&, Vector_t&, Vector_t&)> ParallelCyclotronTracker::function_t private
Definition at line 464 of file ParallelCyclotronTracker.h.
ivector_t
typedef std::vector<int> ParallelCyclotronTracker::ivector_t
Definition at line 59 of file ParallelCyclotronTracker.h.
type_pair
typedef std::pair<ElementType, element_pair> ParallelCyclotronTracker::type_pair
Definition at line 61 of file ParallelCyclotronTracker.h.
Member Enumeration Documentation
TrackingMode
enum ParallelCyclotronTracker::TrackingMode : unsigned short strong private
Enumerator
UNDEFINED
SINGLE
SEO
BUNCH
Definition at line 211 of file ParallelCyclotronTracker.h.
Constructor & Destructor Documentation
ParallelCyclotronTracker() [1/3]
ParallelCyclotronTracker::ParallelCyclotronTracker (const Beamline & beamline, PartBunchBase< double, 3 > * bunch, DataSink & ds, const PartData & reference, bool revBeam, bool revTrack, int maxSTEPS, Steppers::TimeIntegrator timeintegrator, const int & numBunch, const double & mbEta, const double & mbPara, const std::string & mbMode, const std::string & mbBinning)
Constructor.
Constructor ParallelCyclotronTracker
Parameters
beamline
bunch
ds
reference
revBeam
revTrack
maxSTEPS
timeIntegrator
Definition at line 113 of file ParallelCyclotronTracker.cpp.
References BinRepartTimer_m, ElementBase::clone(), DelParticleTimer_m, DumpTimer_m, IpplTimings::getTimer(), IntegrationTimer_m, itsBeamline, itsDataSink, mbHandler_m, PluginElemTimer_m, setTrackingMode(), and TransformTimer_m.
~ParallelCyclotronTracker()
ParallelCyclotronTracker::~ParallelCyclotronTracker () virtual
Destructor ParallelCyclotronTracker
Definition at line 162 of file ParallelCyclotronTracker.cpp.
References FieldDimensions, itsBeamline, and myElements.
ParallelCyclotronTracker() [2/3]
ParallelCyclotronTracker::ParallelCyclotronTracker () private
ParallelCyclotronTracker() [3/3]
ParallelCyclotronTracker::ParallelCyclotronTracker (const ParallelCyclotronTracker &) private
Member Function Documentation
applyPluginElements()
bool ParallelCyclotronTracker::applyPluginElements (const double dt) private
Definition at line 2093 of file ParallelCyclotronTracker.cpp.
References Vacuum::checkVacuum(), cycl_m, endl(), FieldDimensions, PartBunchBase< T, Dim >::getT(), PartBunchBase< T, Dim >::getTotalNum(), gmsg, Tracker::itsBunch_m, pluginElements_m, PluginElemTimer_m, IpplTimings::startTimer(), IpplTimings::stopTimer(), turnnumber_m, PartBunchBase< T, Dim >::updateNumTotal(), and VACUUM.
Referenced by borisExternalFields(), bunchMode_m(), GenericTracker(), and singleMode_m().
bgf_main_collision_test()
void ParallelCyclotronTracker::bgf_main_collision_test ()
Here we check if a particle is outside the domain, flag it for deletion
Definition at line 174 of file ParallelCyclotronTracker.cpp.
References bgf_m, PartBunchBase< T, Dim >::Bin, PartBunchBase< T, Dim >::bunchNum, endl(), PartBunchBase< T, Dim >::getdT(), getHarmonicNumber(), PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getT(), gmsgALL, PartBunchBase< T, Dim >::ID, Tracker::itsBunch_m, level4(), lossDs_m, PartBunchBase< T, Dim >::M, PartBunchBase< T, Dim >::P, BoundaryGeometry::partInside(), PartBunchBase< T, Dim >::Q, PartBunchBase< T, Dim >::R, and turnnumber_m.
Referenced by bunchMode_m(), and singleMode_m().
borisExternalFields()
void ParallelCyclotronTracker::borisExternalFields (double h) private
Definition at line 2063 of file ParallelCyclotronTracker.cpp.
References applyPluginElements(), PartBunchBase< T, Dim >::Bf, computeExternalFields_m(), deleteParticle(), PartBunchBase< T, Dim >::Ef, PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getT(), IntegrationTimer_m, Tracker::itsBunch_m, kick(), push(), IpplTimings::startTimer(), and IpplTimings::stopTimer().
Referenced by MtsTracker().
buildupFieldList()
void ParallelCyclotronTracker::buildupFieldList (double BcParameter[], ElementType elementType, Component * elptr) private
Parameters
BcParameter
ElementType
elptr
Definition at line 1131 of file ParallelCyclotronTracker.cpp.
References CYCLOTRON, FieldDimensions, and RING.
Referenced by visitCCollimator(), visitCyclotron(), visitOutputPlane(), visitProbe(), visitRFCavity(), visitRing(), visitSeptum(), visitStripper(), and visitVacuum().
bunchDumpPhaseSpaceData()
void ParallelCyclotronTracker::bunchDumpPhaseSpaceData () private
Definition at line 2686 of file ParallelCyclotronTracker.cpp.
References acos(), atan2(), BUNCH_MEAN, calcMeanP(), calcMeanR(), calculateAngle(), computeRadius(), cos(), DataSink::dumpH5(), DumpTimer_m, endl(), euclidean_norm(), extB_m, extE_m, FDext_m, FieldDimensions, PartBunchBase< T, Dim >::get_meanKineticEnergy(), PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getT(), PartBunchBase< T, Dim >::getTotalNum(), GLOBAL, globalToLocal(), gmsg, isMultiBunch(), Tracker::itsBunch_m, itsDataSink, Units::kG2T, lastDumpedStep_m, localToGlobal(), Units::m2mm, max(), PartBunchBase< T, Dim >::P, Physics::pi, Options::psDumpFrame, Options::psDumpFreq, PartBunchBase< T, Dim >::R, Units::rad2deg, referencePr, referencePt, referencePtot, referencePz, referenceR, referenceTheta, referenceZ, sin(), sqrt(), IpplTimings::startTimer(), step_m, and IpplTimings::stopTimer().
Referenced by initDistInGlobalFrame(), and update_m().
bunchDumpStatData()
void ParallelCyclotronTracker::bunchDumpStatData () private
Definition at line 2579 of file ParallelCyclotronTracker.cpp.
References acos(), azimuth_m, BUNCH_MEAN, calcMeanP(), calcMeanR(), calculateAngle(), dumpAngle(), DataSink::dumpSDDS(), DumpTimer_m, euclidean_norm(), extB_m, extE_m, FDext_m, FieldDimensions, PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getT(), GLOBAL, globalToLocal(), isMultiBunch(), Tracker::itsBunch_m, itsDataSink, Units::kG2T, localToGlobal(), mbHandler_m, PartBunchBase< T, Dim >::P, Physics::pi, prevAzimuth_m, Options::psDumpFrame, PartBunchBase< T, Dim >::R, Units::rad2deg, IpplTimings::startTimer(), IpplTimings::stopTimer(), updateAzimuthAndRadius(), and DataSink::writeMultiBunchStatistics().
Referenced by initDistInGlobalFrame(), and update_m().
bunchMode_m()
void ParallelCyclotronTracker::bunchMode_m (double & t, const double dt, bool & finishedTurn) private
Definition at line 3156 of file ParallelCyclotronTracker.cpp.
References applyPluginElements(), Communicate::barrier(), PartBunchBase< T, Dim >::Bf, bgf_main_collision_test(), PartBunchBase< T, Dim >::Bin, calcMeanP(), PartBunchBase< T, Dim >::cavityGapCrossed, IpplInfo::Comm, computeSpaceChargeFields_m(), deleteParticle(), PartBunchBase< T, Dim >::Ef, endl(), gapCrossKick_m(), PartBunchBase< T, Dim >::getLocalNum(), getQuaternionTwoVectors(), PartBunchBase< T, Dim >::getTotalNum(), globalToLocal(), gmsg, PartBunchBase< T, Dim >::hasFieldSolver(), injectBunch(), IntegrationTimer_m, isMultiBunch(), isTurnDone(), Tracker::itsBunch_m, itsStepper_mp, mbHandler_m, PartBunchBase< T, Dim >::P, PreviousMeanP, PartBunchBase< T, Dim >::R, Options::rebinFreq, ParallelCyclotronTracker::settings::scSolveFreq, setup_m, singleParticleDump(), Options::sptDumpFreq, IpplTimings::startTimer(), step_m, IpplTimings::stopTimer(), and turnnumber_m.
Referenced by GenericTracker().
calcMeanP()
Vector_t ParallelCyclotronTracker::calcMeanP () const private
Definition at line 1671 of file ParallelCyclotronTracker.cpp.
References PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getTotalNum(), Tracker::itsBunch_m, PartBunchBase< T, Dim >::P, and reduce().
Referenced by bunchDumpPhaseSpaceData(), bunchDumpStatData(), bunchMode_m(), computeSpaceChargeFields_m(), deleteParticle(), initDistInGlobalFrame(), and MtsTracker().
calcMeanR()
Vector_t ParallelCyclotronTracker::calcMeanR (short bunchNr = -1) const private
Definition at line 1648 of file ParallelCyclotronTracker.cpp.
References PartBunchBase< T, Dim >::bunchNum, PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getTotalNum(), PartBunchBase< T, Dim >::getTotalNumPerBunch(), Tracker::itsBunch_m, Hypervolume::n, PartBunchBase< T, Dim >::R, and reduce().
Referenced by bunchDumpPhaseSpaceData(), bunchDumpStatData(), computeSpaceChargeFields_m(), deleteParticle(), initDistInGlobalFrame(), MtsTracker(), saveInjectValues(), and updateAzimuthAndRadius().
calculateAngle()
double ParallelCyclotronTracker::calculateAngle (double x, double y) inline private
Parameters
x
y
Returns
angle range [0~2PI) degree
Definition at line 568 of file ParallelCyclotronTracker.h.
References atan2(), and Physics::two_pi.
Referenced by bunchDumpPhaseSpaceData(), bunchDumpStatData(), deleteParticle(), initDistInGlobalFrame(), MtsTracker(), saveInjectValues(), seoMode_m(), and updateAzimuthAndRadius().
calculateAngle2()
double ParallelCyclotronTracker::calculateAngle2 (double x, double y) inline private
Parameters
x
y
Returns
angle range [-PI~PI) degree
Definition at line 582 of file ParallelCyclotronTracker.h.
References atan2().
Referenced by MtsTracker(), and singleMode_m().
checkFileMomentum()
void ParallelCyclotronTracker::checkFileMomentum () private
Definition at line 2420 of file ParallelCyclotronTracker.cpp.
References abs(), allreduce(), euclidean_norm(), PartBunchBase< T, Dim >::getMomentumTolerance(), initialLocalNum_m, initialTotalNum_m, Tracker::itsBunch_m, PartBunchBase< T, Dim >::P, and referencePtot.
Referenced by initDistInGlobalFrame().
checkGapCross()
bool ParallelCyclotronTracker::checkGapCross (Vector_t Rold, Vector_t Rnew, RFCavity * rfcavity, double & Dold) private
Parameters
Rold
Rnew
elptr
Dold
Returns
Definition at line 1512 of file ParallelCyclotronTracker.cpp.
References RFCavity::getCosAzimuth(), RFCavity::getPerpenDistance(), and RFCavity::getSinAzimuth().
Referenced by gapCrossKick_m().
checkNumPart()
void ParallelCyclotronTracker::checkNumPart (std::string s) private
Definition at line 1161 of file ParallelCyclotronTracker.cpp.
References endl(), PartBunchBase< T, Dim >::getLocalNum(), gmsg, Tracker::itsBunch_m, and reduce().
Referenced by initDistInGlobalFrame().
closeFiles()
void ParallelCyclotronTracker::closeFiles () private
Close all files related to special output in the Cyclotron mode.
Definition at line 304 of file ParallelCyclotronTracker.cpp.
References outfTheta_m.
Referenced by finalizeTracking_m().
computeExternalFields_m() [1/2]
bool ParallelCyclotronTracker::computeExternalFields_m (const Vector_t & R, const Vector_t & P, const double & t, Vector_t & Efield, Vector_t & Bfield)
Calculate the field map at an arbitrary point.
Definition at line 3434 of file ParallelCyclotronTracker.cpp.
References FieldDimensions, Units::kG2T, Units::kV2V, Units::mm2m, and Attrib::Distribution::R.
Referenced by borisExternalFields(), PyOpal::Field::get_field_value_cyclotron(), and getFieldsAtPoint().
computeExternalFields_m() [2/2]
bool ParallelCyclotronTracker::computeExternalFields_m (const size_t & i, const double & t, Vector_t & Efield, Vector_t & Bfield) private
Definition at line 3420 of file ParallelCyclotronTracker.cpp.
References FieldDimensions, Units::kG2T, Units::kV2V, and Units::mm2m.
computePathLengthUpdate()
void ParallelCyclotronTracker::computePathLengthUpdate (std::vector< double > & dl, const double & dt) private
Definition at line 235 of file ParallelCyclotronTracker.cpp.
References allreduce(), BUNCH_MEAN, PartBunchBase< T, Dim >::bunchNum, Physics::c, dot(), PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getTotalNum(), PartBunchBase< T, Dim >::getTotalNumPerBunch(), isMultiBunch(), Tracker::itsBunch_m, PartBunchBase< T, Dim >::P, Options::psDumpFrame, sqrt(), and sum().
Referenced by updatePathLength().
computeRadius()
double ParallelCyclotronTracker::computeRadius (const Vector_t & meanR) const private
Definition at line 230 of file ParallelCyclotronTracker.cpp.
References Units::m2mm, and sqrt().
Referenced by bunchDumpPhaseSpaceData(), saveInjectValues(), and updateAzimuthAndRadius().
computeSpaceChargeFields_m()
void ParallelCyclotronTracker::computeSpaceChargeFields_m () private
Definition at line 3345 of file ParallelCyclotronTracker.cpp.
References PartBunchBase< T, Dim >::Bf, PartBunchBase< T, Dim >::boundp(), PartBunchBase< T, Dim >::boundp_destroyCycl(), Options::boundpDestroyFreq, PartBunchBase< T, Dim >::calcGammas_cycl(), calcMeanP(), calcMeanR(), PartBunchBase< T, Dim >::computeSelfFields_cycl(), PartBunchBase< T, Dim >::Ef, PartBunchBase< T, Dim >::getChargePerParticle(), PartBunchBase< T, Dim >::getFieldSolverType(), Util::getGamma(), PartBunchBase< T, Dim >::getLastemittedBin(), getQuaternionTwoVectors(), globalToLocal(), hasMultiBunch(), Tracker::itsBunch_m, localToGlobal(), PreviousMeanP, PartBunchBase< T, Dim >::Q, PartBunchBase< T, Dim >::R, repartition(), SAAMG, PartBunchBase< T, Dim >::setBinCharge(), PartBunchBase< T, Dim >::setGlobalMeanR(), PartBunchBase< T, Dim >::setGlobalToLocalQuaternion(), spiral_flag, step_m, and yaxis.
Referenced by bunchMode_m(), and MtsTracker().
deleteParticle()
bool ParallelCyclotronTracker::deleteParticle (bool flagNeedUpdate = false) private
Definition at line 2122 of file ParallelCyclotronTracker.cpp.
References acos(), allreduce(), PartBunchBase< T, Dim >::Bin, PartBunchBase< T, Dim >::boundp(), PartBunchBase< T, Dim >::bunchNum, PartBunchBase< T, Dim >::calcBeamParameters(), calcMeanP(), calcMeanR(), calculateAngle(), Options::delPartFreq, DelParticleTimer_m, PartBunchBase< T, Dim >::destroy(), endl(), euclidean_norm(), PartBunchBase< T, Dim >::getLastemittedBin(), PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getLocalNumPerBunch(), PartBunchBase< T, Dim >::getNumBunch(), globalToLocal(), gmsg, isMultiBunch(), Tracker::itsBunch_m, level3(), localToGlobal(), mbHandler_m, PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::performDestroy(), Physics::pi, PartBunchBase< T, Dim >::R, reduce(), PartBunchBase< T, Dim >::setLocalBinCount(), PartBunchBase< T, Dim >::setLocalNumPerBunch(), PartBunchBase< T, Dim >::setTotalNum(), PartBunchBase< T, Dim >::setTotalNumPerBunch(), IpplTimings::startTimer(), step_m, IpplTimings::stopTimer(), and sum().
Referenced by borisExternalFields(), bunchMode_m(), GenericTracker(), and singleMode_m().
dumpAngle()
void ParallelCyclotronTracker::dumpAngle (const double & theta, double & prevAzimuth, double & azimuth, const short & bunchNr = 0) private
Definition at line 206 of file ParallelCyclotronTracker.cpp.
Referenced by bunchDumpStatData(), saveInjectValues(), and updateAzimuthAndRadius().
dumpAzimuthAngles_m()
void ParallelCyclotronTracker::dumpAzimuthAngles_m (const double & t, const Vector_t & R, const Vector_t & P, const double & oldReferenceTheta, const double & temp_meanTheta) inline private
Definition at line 3298 of file ParallelCyclotronTracker.cpp.
References azimuth_angle_m, cos(), ParallelCyclotronTracker::settings::deltaTheta, endl(), outfTheta_m, Attrib::Distribution::R, Units::rad2deg, Units::s2ns, setup_m, sin(), and turnnumber_m.
Referenced by MtsTracker(), and singleMode_m().
dumpThetaEachTurn_m()
void ParallelCyclotronTracker::dumpThetaEachTurn_m (const double & t, const Vector_t & R, const Vector_t & P, const double & temp_meanTheta, bool & finishedTurn) inline private
Definition at line 3320 of file ParallelCyclotronTracker.cpp.
References cos(), Units::deg2rad, endl(), gmsg, isTurnDone(), outfTheta_m, Attrib::Distribution::R, Units::s2ns, sin(), sqrt(), and turnnumber_m.
Referenced by MtsTracker(), and singleMode_m().
evaluateSpaceChargeField()
void ParallelCyclotronTracker::evaluateSpaceChargeField () private
execute()
void ParallelCyclotronTracker::execute () virtual
Apply the algorithm to the top-level beamline.
Reimplemented from DefaultVisitor.
Definition at line 1172 of file ParallelCyclotronTracker.cpp.
References ElementBase::accept(), OpalData::APPEND, Options::asciidump, azimuth_m, bgf_m, cavCrossDatas_m, CCOLLIMATOR, endl(), extB_m, extE_m, FDext_m, FieldDimensions, GenericTracker(), RFCavity::getCosAzimuth(), getFieldsAtPoint(), OpalData::getGlobalGeometry(), OpalData::getInstance(), PartBunchBase< T, Dim >::getNumBunch(), Object::getOpalName(), RFCavity::getPerpenDistance(), RFCavity::getSinAzimuth(), ElementBase::getTypeString(), gmsg, isMultiBunch(), itsBeamline, Tracker::itsBunch_m, itsStepper_mp, Steppers::LF2, Ring::lockRing(), lossDs_m, mbHandler_m, Steppers::MTS, MtsTracker(), opalRing_m, OUTPUTPLANE, pluginElements_m, prevAzimuth_m, PROBE, restartStep0_m, RFCAVITY, Steppers::RK4, SEPTUM, OpalData::setOpenMode(), step_m, stepper_m, STRIPPER, turnnumber_m, DumpFields::writeFields(), and DumpEMFields::writeFields().
finalizeTracking_m()
void ParallelCyclotronTracker::finalizeTracking_m (dvector_t & Ttime, dvector_t & Tdeltr, dvector_t & Tdeltz, ivector_t & TturnNumber) private
Definition at line 2973 of file ParallelCyclotronTracker.cpp.
References Communicate::barrier(), BUNCH, PartBunchBase< T, Dim >::calcBeamParameters(), closeFiles(), IpplInfo::Comm, endl(), Units::eV2MeV, PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getM(), PartBunchBase< T, Dim >::getTotalNum(), getTunes(), gmsg, PartBunchBase< T, Dim >::ID, isMultiBunch(), Tracker::itsBunch_m, lastDumpedStep_m, mode_m, myNode_m, outfTrackOrbit_m, PartBunchBase< T, Dim >::P, pow(), SEO, SINGLE, sqrt(), turnnumber_m, and UNDEFINED.
Referenced by GenericTracker(), and MtsTracker().
gapCrossKick_m()
void ParallelCyclotronTracker::gapCrossKick_m (size_t i, double t, double dt, const Vector_t & Rold, const Vector_t & Pold) private
Definition at line 3251 of file ParallelCyclotronTracker.cpp.
References Physics::c, PartBunchBase< T, Dim >::cavityGapCrossed, checkGapCross(), euclidean_norm(), FieldDimensions, Util::getBeta(), Tracker::itsBunch_m, itsStepper_mp, PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::R, RFCAVITY, and RFkick().
Referenced by bunchMode_m(), and singleMode_m().
GenericTracker()
void ParallelCyclotronTracker::GenericTracker () private
Definition at line 1404 of file ParallelCyclotronTracker.cpp.
References applyPluginElements(), BUNCH, bunchMode_m(), deleteParticle(), endl(), finalizeTracking_m(), PartBunchBase< T, Dim >::getTotalNum(), gmsg, initializeTracking_m(), Tracker::itsBunch_m, maxSteps_m, mode_m, SEO, seoMode_m(), SINGLE, singleMode_m(), step_m, UNDEFINED, and update_m().
Referenced by execute().
getFieldsAtPoint()
bool ParallelCyclotronTracker::getFieldsAtPoint (const double & t, const size_t & Pindex, Vector_t & Efield, Vector_t & Bfield) private
Definition at line 1482 of file ParallelCyclotronTracker.cpp.
References PartBunchBase< T, Dim >::Bf, computeExternalFields_m(), PartBunchBase< T, Dim >::Ef, PartBunchBase< T, Dim >::hasFieldSolver(), PartBunchBase< T, Dim >::ID, and Tracker::itsBunch_m.
Referenced by execute().
getHarmonicNumber()
double ParallelCyclotronTracker::getHarmonicNumber () const private
Definition at line 1636 of file ParallelCyclotronTracker.cpp.
References FieldDimensions, Cyclotron::getCyclHarm(), Ring::getHarmonicNumber(), and opalRing_m.
Referenced by bgf_main_collision_test(), and initializeTracking_m().
getQuaternionTwoVectors()
void ParallelCyclotronTracker::getQuaternionTwoVectors (Vector_t u, Vector_t v, Quaternion_t & quaternion) inline private
Definition at line 1956 of file ParallelCyclotronTracker.cpp.
References abs(), cos(), cross(), dot(), normalizeQuaternion(), normalizeVector(), Physics::pi, sin(), sqrt(), xaxis, and zaxis.
Referenced by bunchMode_m(), and computeSpaceChargeFields_m().
getRing()
Ring* ParallelCyclotronTracker::getRing () const inline
Definition at line 209 of file ParallelCyclotronTracker.h.
References opalRing_m.
Referenced by PyOpal::Field::getRing().
getTunes()
bool ParallelCyclotronTracker::getTunes (dvector_t & t, dvector_t & r, dvector_t & z, int lastTurn, double & nur, double & nuz) private
Parameters
t
r
z
lastTurn
nur
nuz
Returns
Definition at line 1569 of file ParallelCyclotronTracker.cpp.
References endl(), for_each(), gmsg, TUNE_class::lombAnalysis(), sum(), and AbstractTracker::T.
Referenced by finalizeTracking_m().
globalToLocal() [1/4]
void ParallelCyclotronTracker::globalToLocal (ParticleAttrib< Vector_t > & vectorArray, double phi, Vector_t const translationToGlobal = 0) private
Definition at line 1693 of file ParallelCyclotronTracker.cpp.
References cos(), PartBunchBase< T, Dim >::getLocalNum(), Tracker::itsBunch_m, prod_boost_vector(), rotation_m, sin(), IpplTimings::startTimer(), IpplTimings::stopTimer(), and TransformTimer_m.
Referenced by bunchDumpPhaseSpaceData(), bunchDumpStatData(), bunchMode_m(), computeSpaceChargeFields_m(), deleteParticle(), initDistInGlobalFrame(), and MtsTracker().
globalToLocal() [2/4]
void ParallelCyclotronTracker::globalToLocal (ParticleAttrib< Vector_t > & vectorArray, Quaternion_t const quaternion, Vector_t const meanR = Vector_t(0.0)) inline private
Definition at line 1737 of file ParallelCyclotronTracker.cpp.
References rotateWithQuaternion(), IpplTimings::startTimer(), IpplTimings::stopTimer(), and TransformTimer_m.
globalToLocal() [3/4]
void ParallelCyclotronTracker::globalToLocal (ParticleAttrib< Vector_t > & particleVectors, double const phi, double const psi, Vector_t const meanR = Vector_t(0.0)) inline private
Definition at line 1766 of file ParallelCyclotronTracker.cpp.
References rotateAroundX(), rotateAroundZ(), IpplTimings::startTimer(), IpplTimings::stopTimer(), and TransformTimer_m.
globalToLocal() [4/4]
void ParallelCyclotronTracker::globalToLocal (Vector_t & myVector, double const phi, double const psi, Vector_t const meanR = Vector_t(0.0)) inline private
Definition at line 1787 of file ParallelCyclotronTracker.cpp.
References rotateAroundX(), rotateAroundZ(), IpplTimings::startTimer(), IpplTimings::stopTimer(), and TransformTimer_m.
hasMultiBunch()
bool ParallelCyclotronTracker::hasMultiBunch () const inline private
Definition at line 594 of file ParallelCyclotronTracker.h.
References isMultiBunch(), and mbHandler_m.
Referenced by computeSpaceChargeFields_m().
initDistInGlobalFrame()
void ParallelCyclotronTracker::initDistInGlobalFrame () private
Definition at line 2269 of file ParallelCyclotronTracker.cpp.
References acos(), beamInitialRotation, PartBunchBase< T, Dim >::Bin, PartBunchBase< T, Dim >::boundp(), bunchDumpPhaseSpaceData(), bunchDumpStatData(), PartBunchBase< T, Dim >::calcBeamParameters(), calcMeanP(), calcMeanR(), calculateAngle(), checkFileMomentum(), checkNumPart(), cosRefTheta_m, PartBunchBase< T, Dim >::countTotalNumPerBunch(), endl(), euclidean_norm(), FROMFILE, PartBunchBase< T, Dim >::get_sPos(), PartBunchBase< T, Dim >::getDistType(), OpalData::getInstance(), GLOBAL, globalToLocal(), gmsg, PartBunchBase< T, Dim >::ID, initialLocalNum_m, initialTotalNum_m, isMultiBunch(), Tracker::itsBunch_m, localToGlobal(), mbHandler_m, PartBunchBase< T, Dim >::P, pathLength_m, Physics::pi, Options::psDumpFrame, PartBunchBase< T, Dim >::R, referencePhi, referencePr, referencePsi, referencePt, referencePz, referenceR, referenceTheta, referenceZ, repartition(), saveInjectValues(), setTimeStep(), sinRefTheta_m, sqrt(), and step_m.
Referenced by initializeTracking_m().
initializeBoundaryGeometry()
void ParallelCyclotronTracker::initializeBoundaryGeometry ()
initializeTracking_m()
std::tuple< double, double, double > ParallelCyclotronTracker::initializeTracking_m () private
Returns
the time t [s], time step dt [s] and the azimuth angle [rad]
Definition at line 2862 of file ParallelCyclotronTracker.cpp.
References azimuth_angle_m, BUNCH, Units::deg2rad, ParallelCyclotronTracker::settings::deltaTheta, endl(), PartBunchBase< T, Dim >::getdT(), getHarmonicNumber(), OpalData::getInputBasename(), OpalData::getInstance(), PartBunchBase< T, Dim >::getLocalTrackStep(), IpplInfo::getNodes(), PartBunchBase< T, Dim >::getNumBunch(), PartBunchBase< T, Dim >::getStepsPerTurn(), PartBunchBase< T, Dim >::getT(), gmsg, initDistInGlobalFrame(), initPathLength(), initTrackOrbitFile(), isMultiBunch(), Tracker::itsBunch_m, mbHandler_m, mode_m, openFiles(), Physics::pi, Options::rebinFreq, referenceTheta, Options::repartFreq, restartStep0_m, Units::s2ns, Options::scSolveFreq, ParallelCyclotronTracker::settings::scSolveFreq, SEO, setup_m, SINGLE, spiral_flag, Options::sptDumpFreq, step_m, ParallelCyclotronTracker::settings::stepsNextCheck, ParallelCyclotronTracker::settings::stepsPerTurn, turnnumber_m, and UNDEFINED.
Referenced by GenericTracker(), and MtsTracker().
initPathLength()
void ParallelCyclotronTracker::initPathLength () private
multi-bunch mode: set the path length of each bunch in case of restart mode
At creation of DataSink the lines are rewinded properly –> the last entry of the path length is therefore the initial path length at restart.
Precondition
In order to work properly in restart mode, the lines in the multi-bunch *.smb files need to be rewinded first.
Definition at line 3557 of file ParallelCyclotronTracker.cpp.
References isMultiBunch(), itsDataSink, mbHandler_m, and DataSink::setMultiBunchInitialPathLengh().
Referenced by initializeTracking_m().
initTrackOrbitFile()
void ParallelCyclotronTracker::initTrackOrbitFile () private
Definition at line 2250 of file ParallelCyclotronTracker.cpp.
References endl(), OpalData::getInputBasename(), OpalData::getInstance(), PartBunchBase< T, Dim >::getLocalTrackStep(), Tracker::itsBunch_m, myNode_m, and outfTrackOrbit_m.
Referenced by initializeTracking_m().
injectBunch()
void ParallelCyclotronTracker::injectBunch (bool & flagTransition) private
Definition at line 3449 of file ParallelCyclotronTracker.cpp.
References endl(), gmsg, isMultiBunch(), Tracker::itsBunch_m, AbstractTracker::itsReference, mbHandler_m, saveInjectValues(), setup_m, step_m, ParallelCyclotronTracker::settings::stepsNextCheck, ParallelCyclotronTracker::settings::stepsPerTurn, and turnnumber_m.
Referenced by bunchMode_m(), and MtsTracker().
isMultiBunch()
bool ParallelCyclotronTracker::isMultiBunch () const inline private
Definition at line 588 of file ParallelCyclotronTracker.h.
References Tracker::itsBunch_m, mbHandler_m, and PartBunchBase< T, Dim >::weHaveBins().
Referenced by bunchDumpPhaseSpaceData(), bunchDumpStatData(), bunchMode_m(), computePathLengthUpdate(), deleteParticle(), execute(), finalizeTracking_m(), hasMultiBunch(), initDistInGlobalFrame(), initializeTracking_m(), initPathLength(), injectBunch(), MtsTracker(), saveInjectValues(), updateAzimuthAndRadius(), updatePathLength(), updateTime(), and visitCyclotron().
isTurnDone()
bool ParallelCyclotronTracker::isTurnDone () private
Check if turn done.
Definition at line 2815 of file ParallelCyclotronTracker.cpp.
References setup_m, step_m, and ParallelCyclotronTracker::settings::stepsPerTurn.
Referenced by bunchMode_m(), dumpThetaEachTurn_m(), MtsTracker(), and seoMode_m().
kick()
bool ParallelCyclotronTracker::kick (double h) private
Definition at line 2043 of file ParallelCyclotronTracker.cpp.
References PartBunchBase< T, Dim >::Bf, PartBunchBase< T, Dim >::Bin, PartBunchBase< T, Dim >::Ef, PartBunchBase< T, Dim >::getLocalNum(), Units::GeV2eV, IntegrationTimer_m, Tracker::itsBunch_m, BorisPusher::kick(), PartBunchBase< T, Dim >::M, PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::Q, Physics::q_e, PartBunchBase< T, Dim >::R, IpplTimings::startTimer(), and IpplTimings::stopTimer().
Referenced by borisExternalFields(), and MtsTracker().
localToGlobal() [1/4]
void ParallelCyclotronTracker::localToGlobal (ParticleAttrib< Vector_t > & vectorArray, double phi, Vector_t const translationToGlobal = 0) private
Definition at line 1714 of file ParallelCyclotronTracker.cpp.
References cos(), PartBunchBase< T, Dim >::getLocalNum(), Tracker::itsBunch_m, prod_boost_vector(), rotation_m, sin(), IpplTimings::startTimer(), IpplTimings::stopTimer(), and TransformTimer_m.
Referenced by bunchDumpPhaseSpaceData(), bunchDumpStatData(), computeSpaceChargeFields_m(), deleteParticle(), initDistInGlobalFrame(), and MtsTracker().
localToGlobal() [2/4]
void ParallelCyclotronTracker::localToGlobal (ParticleAttrib< Vector_t > & vectorArray, Quaternion_t const quaternion, Vector_t const meanR = Vector_t(0.0)) inline private
Definition at line 1750 of file ParallelCyclotronTracker.cpp.
References rotateWithQuaternion(), IpplTimings::startTimer(), IpplTimings::stopTimer(), and TransformTimer_m.
localToGlobal() [3/4]
void ParallelCyclotronTracker::localToGlobal (ParticleAttrib< Vector_t > & particleVectors, double const phi, double const psi, Vector_t const meanR = Vector_t(0.0)) inline private
Definition at line 1808 of file ParallelCyclotronTracker.cpp.
References rotateAroundX(), rotateAroundZ(), IpplTimings::startTimer(), IpplTimings::stopTimer(), and TransformTimer_m.
localToGlobal() [4/4]
void ParallelCyclotronTracker::localToGlobal (Vector_t & myVector, double const phi, double const psi, Vector_t const meanR = Vector_t(0.0)) inline private
Definition at line 1829 of file ParallelCyclotronTracker.cpp.
References rotateAroundX(), rotateAroundZ(), IpplTimings::startTimer(), IpplTimings::stopTimer(), and TransformTimer_m.
MtsTracker()
void ParallelCyclotronTracker::MtsTracker () private
Definition at line 1273 of file ParallelCyclotronTracker.cpp.
References Communicate::barrier(), borisExternalFields(), BUNCH, calcMeanP(), calcMeanR(), calculateAngle(), calculateAngle2(), IpplInfo::Comm, computeSpaceChargeFields_m(), dumpAzimuthAngles_m(), dumpThetaEachTurn_m(), endl(), finalizeTracking_m(), PartBunchBase< T, Dim >::getTotalNum(), globalToLocal(), gmsg, PartBunchBase< T, Dim >::hasFieldSolver(), initializeTracking_m(), injectBunch(), isMultiBunch(), isTurnDone(), Tracker::itsBunch_m, kick(), localToGlobal(), max(), maxSteps_m, mbHandler_m, mode_m, Options::mtsSubsteps, Hypervolume::n, PartBunchBase< T, Dim >::P, Physics::pi, PartBunchBase< T, Dim >::R, Options::rebinFreq, Options::repartFreq, repartition(), Units::s2ns, SINGLE, singleParticleDump(), Options::sptDumpFreq, step_m, turnnumber_m, update_m(), and PartBunchBase< T, Dim >::updateNumTotal().
Referenced by execute().
normalizeQuaternion()
void ParallelCyclotronTracker::normalizeQuaternion (Quaternion_t & quaternion) inline private
Definition at line 1864 of file ParallelCyclotronTracker.cpp.
References abs(), dot(), and sqrt().
Referenced by getQuaternionTwoVectors().
normalizeVector()
void ParallelCyclotronTracker::normalizeVector (Vector_t & vector) inline private
Definition at line 1876 of file ParallelCyclotronTracker.cpp.
References abs(), dot(), and sqrt().
Referenced by getQuaternionTwoVectors().
openFiles()
void ParallelCyclotronTracker::openFiles (size_t numFiles, std::string SfileName) private
@ open / close output coordinate files
Parameters
fn Base file name
Definition at line 278 of file ParallelCyclotronTracker.cpp.
References endl(), and outfTheta_m.
Referenced by initializeTracking_m().
operator=()
void ParallelCyclotronTracker::operator= (const ParallelCyclotronTracker &) private
push()
bool ParallelCyclotronTracker::push (double h) private
Definition at line 2000 of file ParallelCyclotronTracker.cpp.
References PartBunchBase< T, Dim >::Bin, Physics::c, cavCrossDatas_m, euclidean_norm(), Util::getGamma(), PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::getT(), IntegrationTimer_m, Tracker::itsBunch_m, PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::R, RFkick(), IpplTimings::startTimer(), and IpplTimings::stopTimer().
Referenced by borisExternalFields().
repartition()
void ParallelCyclotronTracker::repartition () private
Definition at line 1684 of file ParallelCyclotronTracker.cpp.
References Communicate::barrier(), BinRepartTimer_m, IpplInfo::Comm, PartBunchBase< T, Dim >::do_binaryRepart(), Tracker::itsBunch_m, Options::repartFreq, IpplTimings::startTimer(), step_m, and IpplTimings::stopTimer().
Referenced by computeSpaceChargeFields_m(), initDistInGlobalFrame(), and MtsTracker().
RFkick()
bool ParallelCyclotronTracker::RFkick (RFCavity * rfcavity, const double t, const double dt, const int Pindex) private
Definition at line 1527 of file ParallelCyclotronTracker.cpp.
References PartBunchBase< T, Dim >::getM(), RFCavity::getMomentaKick(), RFCavity::getPerpenDistance(), PartBunchBase< T, Dim >::getQ(), RFCavity::getRmax(), RFCavity::getRmin(), PartBunchBase< T, Dim >::ID, Tracker::itsBunch_m, PartBunchBase< T, Dim >::P, pow(), PartBunchBase< T, Dim >::R, and sqrt().
Referenced by gapCrossKick_m(), and push().
rotateAroundX() [1/2]
void ParallelCyclotronTracker::rotateAroundX (ParticleAttrib< Vector_t > & particleVectors, double const psi) inline private
Definition at line 1922 of file ParallelCyclotronTracker.cpp.
References cos(), PartBunchBase< T, Dim >::getLocalNum(), Tracker::itsBunch_m, prod_boost_vector(), rotation_m, and sin().
Referenced by globalToLocal(), and localToGlobal().
rotateAroundX() [2/2]
void ParallelCyclotronTracker::rotateAroundX (Vector_t & myVector, double const psi) inline private
Definition at line 1940 of file ParallelCyclotronTracker.cpp.
References cos(), prod_boost_vector(), rotation_m, and sin().
rotateAroundZ() [1/2]
void ParallelCyclotronTracker::rotateAroundZ (ParticleAttrib< Vector_t > & particleVectors, double const phi) inline private
Definition at line 1888 of file ParallelCyclotronTracker.cpp.
References cos(), PartBunchBase< T, Dim >::getLocalNum(), Tracker::itsBunch_m, prod_boost_vector(), rotation_m, and sin().
Referenced by globalToLocal(), and localToGlobal().
rotateAroundZ() [2/2]
void ParallelCyclotronTracker::rotateAroundZ (Vector_t & myVector, double const phi) inline private
Definition at line 1906 of file ParallelCyclotronTracker.cpp.
References cos(), prod_boost_vector(), rotation_m, and sin().
rotateWithQuaternion()
void ParallelCyclotronTracker::rotateWithQuaternion (ParticleAttrib< Vector_t > & vectorArray, Quaternion_t const quaternion) inline private
Definition at line 1850 of file ParallelCyclotronTracker.cpp.
References cross(), dot(), PartBunchBase< T, Dim >::getLocalNum(), and Tracker::itsBunch_m.
Referenced by globalToLocal(), and localToGlobal().
saveInjectValues()
void ParallelCyclotronTracker::saveInjectValues () private
Definition at line 3485 of file ParallelCyclotronTracker.cpp.
References MultiBunchHandler::injection_t::azimuth, azimuth_m, calcMeanR(), calculateAngle(), computeRadius(), dumpAngle(), PartBunchBase< T, Dim >::get_sPos(), PartBunchBase< T, Dim >::getT(), isMultiBunch(), Tracker::itsBunch_m, mbHandler_m, MultiBunchHandler::injection_t::pathlength, prevAzimuth_m, Units::rad2deg, MultiBunchHandler::injection_t::radius, and MultiBunchHandler::injection_t::time.
Referenced by initDistInGlobalFrame(), and injectBunch().
seoMode_m()
void ParallelCyclotronTracker::seoMode_m (double & t, const double dt, bool & finishedTurn, dvector_t & Ttime, dvector_t & Tdeltr, dvector_t & Tdeltz, ivector_t & TturnNumber) private
Definition at line 3044 of file ParallelCyclotronTracker.cpp.
References calculateAngle(), cos(), endl(), PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::ID, IntegrationTimer_m, isTurnDone(), Tracker::itsBunch_m, itsStepper_mp, outfTrackOrbit_m, PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::R, sin(), Options::sptDumpFreq, IpplTimings::startTimer(), step_m, IpplTimings::stopTimer(), and turnnumber_m.
Referenced by GenericTracker().
setBeGa()
void ParallelCyclotronTracker::setBeGa (double x) inline
Definition at line 201 of file ParallelCyclotronTracker.h.
References bega.
Referenced by TrackRun::setupCyclotronTracker().
setLastDumpedStep()
void ParallelCyclotronTracker::setLastDumpedStep (const int para) inline
set last dumped step
Definition at line 192 of file ParallelCyclotronTracker.h.
References lastDumpedStep_m.
Referenced by TrackRun::setupCyclotronTracker().
setPhi()
void ParallelCyclotronTracker::setPhi (double x) inline
Definition at line 202 of file ParallelCyclotronTracker.h.
References referencePhi.
Referenced by TrackRun::setupCyclotronTracker().
setPr()
void ParallelCyclotronTracker::setPr (double x) inline
Method for restart.
Definition at line 195 of file ParallelCyclotronTracker.h.
References referencePr.
Referenced by TrackRun::setupCyclotronTracker().
setPreviousH5Local()
void ParallelCyclotronTracker::setPreviousH5Local (bool x) inline
Definition at line 204 of file ParallelCyclotronTracker.h.
References previousH5Local.
Referenced by TrackRun::setupCyclotronTracker().
setPsi()
void ParallelCyclotronTracker::setPsi (double x) inline
Definition at line 203 of file ParallelCyclotronTracker.h.
References referencePsi.
Referenced by TrackRun::setupCyclotronTracker().
setPt()
void ParallelCyclotronTracker::setPt (double x) inline
Definition at line 196 of file ParallelCyclotronTracker.h.
References referencePt.
Referenced by TrackRun::setupCyclotronTracker().
setPz()
void ParallelCyclotronTracker::setPz (double x) inline
Definition at line 197 of file ParallelCyclotronTracker.h.
References referencePz.
Referenced by TrackRun::setupCyclotronTracker().
setR()
void ParallelCyclotronTracker::setR (double x) inline
Definition at line 198 of file ParallelCyclotronTracker.h.
References referenceR.
Referenced by TrackRun::setupCyclotronTracker().
setTheta()
void ParallelCyclotronTracker::setTheta (double x) inline
Definition at line 199 of file ParallelCyclotronTracker.h.
References referenceTheta.
Referenced by TrackRun::setupCyclotronTracker().
setTimeStep()
void ParallelCyclotronTracker::setTimeStep () private
Definition at line 2414 of file ParallelCyclotronTracker.cpp.
References PartBunchBase< T, Dim >::dt, PartBunchBase< T, Dim >::getdT(), initialLocalNum_m, and Tracker::itsBunch_m.
Referenced by initDistInGlobalFrame().
setTrackingMode()
void ParallelCyclotronTracker::setTrackingMode () private
Definition at line 3032 of file ParallelCyclotronTracker.cpp.
References BUNCH, initialTotalNum_m, mode_m, SEO, SINGLE, and UNDEFINED.
Referenced by ParallelCyclotronTracker().
setZ()
void ParallelCyclotronTracker::setZ (double x) inline
Definition at line 200 of file ParallelCyclotronTracker.h.
References referenceZ.
Referenced by TrackRun::setupCyclotronTracker().
singleMode_m()
void ParallelCyclotronTracker::singleMode_m (double & t, const double dt, bool & finishedTurn, double & oldReferenceTheta) private
Definition at line 3092 of file ParallelCyclotronTracker.cpp.
References applyPluginElements(), bgf_main_collision_test(), PartBunchBase< T, Dim >::Bin, calculateAngle2(), PartBunchBase< T, Dim >::cavityGapCrossed, deleteParticle(), dumpAzimuthAngles_m(), dumpThetaEachTurn_m(), endl(), gapCrossKick_m(), PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::ID, IntegrationTimer_m, Tracker::itsBunch_m, itsStepper_mp, outfTrackOrbit_m, PartBunchBase< T, Dim >::P, PartBunchBase< T, Dim >::R, Options::sptDumpFreq, IpplTimings::startTimer(), step_m, and IpplTimings::stopTimer().
Referenced by GenericTracker().
singleParticleDump()
void ParallelCyclotronTracker::singleParticleDump () private
Definition at line 2451 of file ParallelCyclotronTracker.cpp.
References Communicate::barrier(), IpplInfo::Comm, COMM_ANY_NODE, DumpTimer_m, endl(), ERRORMSG, Message::get(), PartBunchBase< T, Dim >::getLocalNum(), IpplInfo::getNodes(), PartBunchBase< T, Dim >::ID, IPPL_APP_CYCLE, IPPL_APP_TAG4, Tracker::itsBunch_m, myNode_m, TagMaker::next_tag(), outfTrackOrbit_m, PartBunchBase< T, Dim >::P, Message::put(), PartBunchBase< T, Dim >::R, Communicate::receive_block(), PartBunchBase< T, Dim >::RefPartP_m, PartBunchBase< T, Dim >::RefPartR_m, IpplTimings::startTimer(), and IpplTimings::stopTimer().
Referenced by bunchMode_m(), and MtsTracker().
update_m()
void ParallelCyclotronTracker::update_m (double & t, const double & dt, const bool & finishedTurn) private
Update time and path length, write to output files.
Definition at line 2819 of file ParallelCyclotronTracker.cpp.
References bunchDumpPhaseSpaceData(), bunchDumpStatData(), endl(), PartBunchBase< T, Dim >::getTotalNum(), gmsg, Tracker::itsBunch_m, mode_m, pluginElements_m, Options::psDumpEachTurn, Options::psDumpFreq, SEO, PartBunchBase< T, Dim >::setLocalTrackStep(), Options::statDumpFreq, step_m, updatePathLength(), and updateTime().
Referenced by GenericTracker(), and MtsTracker().
updateAzimuthAndRadius()
void ParallelCyclotronTracker::updateAzimuthAndRadius () private
Definition at line 3541 of file ParallelCyclotronTracker.cpp.
References MultiBunchHandler::beaminfo_t::azimuth, calcMeanR(), calculateAngle(), computeRadius(), dumpAngle(), isMultiBunch(), mbHandler_m, MultiBunchHandler::beaminfo_t::prevAzimuth, Units::rad2deg, and MultiBunchHandler::beaminfo_t::radius.
Referenced by bunchDumpStatData().
updatePathLength()
void ParallelCyclotronTracker::updatePathLength (const double & dt) private
Definition at line 3509 of file ParallelCyclotronTracker.cpp.
References computePathLengthUpdate(), isMultiBunch(), Tracker::itsBunch_m, mbHandler_m, pathLength_m, and PartBunchBase< T, Dim >::set_sPos().
Referenced by update_m().
updateTime()
void ParallelCyclotronTracker::updateTime (const double & dt) private
Definition at line 3530 of file ParallelCyclotronTracker.cpp.
References PartBunchBase< T, Dim >::getT(), isMultiBunch(), Tracker::itsBunch_m, mbHandler_m, and PartBunchBase< T, Dim >::setT().
Referenced by update_m().
visitBeamline()
void ParallelCyclotronTracker::visitBeamline (const Beamline & bl) virtual
Apply the algorithm to a beam line.
Parameters
bl
Reimplemented from DefaultVisitor.
Definition at line 1156 of file ParallelCyclotronTracker.cpp.
References TBeamline< T >::iterate().
visitCCollimator()
void ParallelCyclotronTracker::visitCCollimator (const CCollimator & coll) virtual
Apply the algorithm to a collimator.
Parameters
coll
Reimplemented from DefaultVisitor.
Definition at line 481 of file ParallelCyclotronTracker.cpp.
References buildupFieldList(), CCOLLIMATOR, ElementBase::clone(), endl(), ElementBase::getName(), CCollimator::getWidth(), PluginElement::getXEnd(), PluginElement::getXStart(), PluginElement::getYEnd(), PluginElement::getYStart(), CCollimator::getZEnd(), CCollimator::getZStart(), gmsg, PluginElement::initialise(), Tracker::itsBunch_m, and myElements.
visitCorrector()
void ParallelCyclotronTracker::visitCorrector (const Corrector & corr) virtual
Apply the algorithm to a closed orbit corrector.
Parameters
corr
Reimplemented from DefaultVisitor.
Definition at line 528 of file ParallelCyclotronTracker.cpp.
References ElementBase::clone(), endl(), ElementBase::getElementLength(), gmsg, and myElements.
visitCyclotron()
void ParallelCyclotronTracker::visitCyclotron (const Cyclotron & cycl) virtual
Apply the algorithm to a cyclotron.
Parameters
cycl
Reimplemented from DefaultVisitor.
Definition at line 316 of file ParallelCyclotronTracker.cpp.
References Cyclotron::BANDRF, bega, Util::boolVectorToUpperString(), buildupFieldList(), Cyclotron::checkInitialReferenceParticle(), ElementBase::clone(), cos(), cosRefTheta_m, cycl_m, CYCLOTRON, Units::deg2rad, Util::doubleVectorToString(), Physics::e, endl(), PartData::getBeta(), Cyclotron::getBFieldType(), Cyclotron::getBScale(), Cyclotron::getCyclHarm(), Cyclotron::getCyclotronType(), Cyclotron::getEScale(), Cyclotron::getFieldMapFN(), PartData::getGamma(), OpalData::getInstance(), Cyclotron::getMaxR(), Cyclotron::getMaxZ(), Cyclotron::getMinR(), Cyclotron::getMinZ(), Cyclotron::getNumberOfTrimcoils(), Cyclotron::getPHIinit(), Cyclotron::getPRinit(), Cyclotron::getPZinit(), Cyclotron::getRfFrequ(), Cyclotron::getRfPhi(), Cyclotron::getRinit(), Cyclotron::getRmax(), Cyclotron::getRmin(), Cyclotron::getSpiralFlag(), Cyclotron::getSuperpose(), Cyclotron::getSymmetry(), Cyclotron::getZinit(), GLOBAL, gmsg, Cyclotron::initialise(), isMultiBunch(), Tracker::itsBunch_m, AbstractTracker::itsReference, mbHandler_m, Units::mm2m, myElements, previousH5Local, Options::psDumpFrame, Units::rad2deg, referencePhi, referencePr, referencePsi, referencePt, referencePtot, referencePz, referenceR, referenceTheta, referenceZ, Cyclotron::setBFieldType(), sin(), sinRefTheta_m, spiral_flag, and sqrt().
visitDegrader()
void ParallelCyclotronTracker::visitDegrader (const Degrader & deg) virtual
Apply the algorithm to a degrader.
Parameters
degrader
Reimplemented from DefaultVisitor.
Definition at line 538 of file ParallelCyclotronTracker.cpp.
References matheval::detail::math::deg(), endl(), gmsg, and myElements.
visitDrift()
void ParallelCyclotronTracker::visitDrift (const Drift & drift) virtual
Apply the algorithm to a drift space.
Parameters
drift
Reimplemented from DefaultVisitor.
Definition at line 549 of file ParallelCyclotronTracker.cpp.
References ElementBase::clone(), endl(), ElementBase::getElementLength(), gmsg, and myElements.
visitFlexibleCollimator()
void ParallelCyclotronTracker::visitFlexibleCollimator (const FlexibleCollimator &) virtual
Apply the algorithm to a flexible collimator.
Parameters
Reimplemented from DefaultVisitor.
Definition at line 559 of file ParallelCyclotronTracker.cpp.
visitMarker()
void ParallelCyclotronTracker::visitMarker (const Marker & marker) virtual
Apply the algorithm to a marker.
Parameters
marker
Reimplemented from DefaultVisitor.
Definition at line 581 of file ParallelCyclotronTracker.cpp.
References ElementBase::clone(), and myElements.
visitMonitor()
void ParallelCyclotronTracker::visitMonitor (const Monitor & corr) virtual
Apply the algorithm to a beam position monitor.
Parameters
corr
Reimplemented from DefaultVisitor.
Definition at line 592 of file ParallelCyclotronTracker.cpp.
References ElementBase::clone(), and myElements.
visitMultipole()
void ParallelCyclotronTracker::visitMultipole (const Multipole & mult) virtual
Apply the algorithm to a multipole.
Parameters
mult
Reimplemented from DefaultVisitor.
Definition at line 603 of file ParallelCyclotronTracker.cpp.
References ElementBase::clone(), endl(), ElementBase::getElementLength(), gmsg, and myElements.
visitMultipoleT()
void ParallelCyclotronTracker::visitMultipoleT (const MultipoleT & multT) virtual
Apply the algorithm to an arbitrary multipole.
Parameters
multT
Reimplemented from DefaultVisitor.
Definition at line 613 of file ParallelCyclotronTracker.cpp.
References Ring::appendElement(), MultipoleT::clone(), endl(), gmsg, myElements, and opalRing_m.
visitMultipoleTCurvedConstRadius()
void ParallelCyclotronTracker::visitMultipoleTCurvedConstRadius (const MultipoleTCurvedConstRadius & multTccurv) virtual
Apply the algorithm to an arbitrary curved multipole of constant radius.
Parameters
multTccurv
Reimplemented from DefaultVisitor.
Definition at line 645 of file ParallelCyclotronTracker.cpp.
References Ring::appendElement(), MultipoleTCurvedConstRadius::clone(), endl(), gmsg, myElements, and opalRing_m.
visitMultipoleTCurvedVarRadius()
void ParallelCyclotronTracker::visitMultipoleTCurvedVarRadius (const MultipoleTCurvedVarRadius & multTvcurv) virtual
Apply the algorithm to an arbitrary curved multipole of variable radius.
Parameters
multTvcurv
Reimplemented from DefaultVisitor.
Definition at line 661 of file ParallelCyclotronTracker.cpp.
References Ring::appendElement(), MultipoleTCurvedVarRadius::clone(), endl(), gmsg, myElements, and opalRing_m.
visitMultipoleTStraight()
void ParallelCyclotronTracker::visitMultipoleTStraight (const MultipoleTStraight & multTstraight) virtual
Apply the algorithm to an arbitrary straight multipole.
Parameters
multTstraight
Reimplemented from DefaultVisitor.
Definition at line 629 of file ParallelCyclotronTracker.cpp.
References Ring::appendElement(), MultipoleTStraight::clone(), endl(), gmsg, myElements, and opalRing_m.
visitOffset()
void ParallelCyclotronTracker::visitOffset (const Offset & off) virtual
Apply the algorithm to a offset (placement).
Parameters
off
Reimplemented from DefaultVisitor.
Definition at line 568 of file ParallelCyclotronTracker.cpp.
References Ring::appendElement(), and opalRing_m.
visitOutputPlane()
void ParallelCyclotronTracker::visitOutputPlane (const OutputPlane & plane) virtual
Apply the algorithm to a outputplane.
Parameters
plane
Reimplemented from DefaultVisitor.
Definition at line 678 of file ParallelCyclotronTracker.cpp.
References buildupFieldList(), OutputPlane::clone(), OutputPlane::getCentre(), OutputPlane::getHorizontalExtent(), OutputPlane::getNormal(), PluginElement::initialise(), Tracker::itsBunch_m, Units::mm2m, myElements, opalRing_m, OUTPUTPLANE, and OutputPlane::setGlobalFieldMap().
visitProbe()
void ParallelCyclotronTracker::visitProbe (const Probe & prob) virtual
Apply the algorithm to a probe.
Parameters
prob
Reimplemented from DefaultVisitor.
Definition at line 708 of file ParallelCyclotronTracker.cpp.
References buildupFieldList(), ElementBase::clone(), endl(), ElementBase::getName(), PluginElement::getXEnd(), PluginElement::getXStart(), PluginElement::getYEnd(), PluginElement::getYStart(), gmsg, PluginElement::initialise(), Tracker::itsBunch_m, myElements, and PROBE.
visitRBend()
void ParallelCyclotronTracker::visitRBend (const RBend & bend) virtual
Apply the algorithm to a rectangular bend.
Parameters
bend
Reimplemented from DefaultVisitor.
Definition at line 747 of file ParallelCyclotronTracker.cpp.
References ElementBase::clone(), endl(), ElementBase::getElementLength(), gmsg, and myElements.
visitRFCavity()
void ParallelCyclotronTracker::visitRFCavity (const RFCavity & as) virtual
Apply the algorithm to a RF cavity.
Parameters
as
Reimplemented from DefaultVisitor.
Definition at line 757 of file ParallelCyclotronTracker.cpp.
References buildupFieldList(), ElementBase::clone(), endl(), RFCavity::getAmplitudeModelName(), RFCavity::getAzimuth(), RFCavity::getCavityType(), RFCavity::getCavityTypeString(), RFCavity::getCycFrequency(), RFCavity::getFieldMapFN(), RFCavity::getFrequencyModelName(), RFCavity::getGapWidth(), ElementBase::getName(), RFCavity::getPerpenDistance(), RFCavity::getPhaseModelName(), RFCavity::getPhi0(), RFCavity::getRmax(), RFCavity::getRmin(), AbstractTimeDependence::getTimeDependence(), gmsg, RFCavity::initialise(), Tracker::itsBunch_m, myElements, Units::rad2deg, RFCAVITY, and SGSW.
visitRing()
void ParallelCyclotronTracker::visitRing (const Ring & ring) virtual
Apply the algorithm to a ring.
Parameters
ring
Reimplemented from DefaultVisitor.
Definition at line 851 of file ParallelCyclotronTracker.cpp.
References Util::angleBetweenAngles(), beamInitialRotation, buildupFieldList(), Ring::clone(), cos(), cosRefTheta_m, endl(), Ring::getBeamPhiInit(), Ring::getBeamPRInit(), Ring::getBeamRInit(), Ring::getBeamThetaInit(), PartData::getBeta(), PartData::getGamma(), Ring::getHarmonicNumber(), Ring::getSymmetry(), gmsg, Ring::initialise(), Tracker::itsBunch_m, AbstractTracker::itsReference, myElements, opalRing_m, Physics::pi, referencePr, referencePt, referencePtot, referencePz, referenceR, referenceTheta, referenceZ, RING, sin(), sinRefTheta_m, and sqrt().
visitSBend()
void ParallelCyclotronTracker::visitSBend (const SBend & bend) virtual
Apply the algorithm to a sector bend.
Parameters
bend
Reimplemented from DefaultVisitor.
Definition at line 904 of file ParallelCyclotronTracker.cpp.
References ElementBase::clone(), endl(), ElementBase::getElementLength(), gmsg, and myElements.
visitSBend3D()
void ParallelCyclotronTracker::visitSBend3D (const SBend3D & bend) virtual
Apply the algorithm to a sector bend with 3D field map.
Reimplemented from DefaultVisitor.
Definition at line 909 of file ParallelCyclotronTracker.cpp.
References Ring::appendElement(), endl(), gmsg, and opalRing_m.
visitScalingFFAMagnet()
void ParallelCyclotronTracker::visitScalingFFAMagnet (const ScalingFFAMagnet & bend) virtual
Apply the algorithm to a scaling FFA magnet.
Reimplemented from DefaultVisitor.
Definition at line 918 of file ParallelCyclotronTracker.cpp.
References Ring::appendElement(), ScalingFFAMagnet::clone(), endl(), gmsg, opalRing_m, and ScalingFFAMagnet::setupEndField().
visitSeptum()
void ParallelCyclotronTracker::visitSeptum (const Septum & sept) virtual
Apply the algorithm to a septum.
Parameters
sept
Reimplemented from DefaultVisitor.
Definition at line 935 of file ParallelCyclotronTracker.cpp.
References buildupFieldList(), ElementBase::clone(), endl(), ElementBase::getName(), Septum::getWidth(), PluginElement::getXEnd(), PluginElement::getXStart(), PluginElement::getYEnd(), PluginElement::getYStart(), gmsg, Septum::initialise(), Tracker::itsBunch_m, myElements, and SEPTUM.
visitSolenoid()
void ParallelCyclotronTracker::visitSolenoid (const Solenoid & solenoid) virtual
Apply the algorithm to a solenoid.
Parameters
solenoid
Reimplemented from DefaultVisitor.
Definition at line 977 of file ParallelCyclotronTracker.cpp.
References ElementBase::clone(), endl(), gmsg, ElementBase::hasAttribute(), and myElements.
visitStripper()
void ParallelCyclotronTracker::visitStripper (const Stripper & stripper) virtual
Apply the algorithm to a particle stripper.
Parameters
stripper
Reimplemented from DefaultVisitor.
Definition at line 991 of file ParallelCyclotronTracker.cpp.
References buildupFieldList(), ElementBase::clone(), endl(), ElementBase::getName(), Stripper::getOPCharge(), Stripper::getOPMass(), Stripper::getStop(), PluginElement::getXEnd(), PluginElement::getXStart(), PluginElement::getYEnd(), PluginElement::getYStart(), gmsg, PluginElement::initialise(), Tracker::itsBunch_m, myElements, and STRIPPER.
visitVacuum()
void ParallelCyclotronTracker::visitVacuum (const Vacuum & vac) virtual
Apply the algorithm to a vacuum space.
Parameters
vac
Reimplemented from DefaultVisitor.
Definition at line 1042 of file ParallelCyclotronTracker.cpp.
References buildupFieldList(), ElementBase::clone(), endl(), Vacuum::getPressure(), Vacuum::getPressureMapFN(), Vacuum::getPScale(), Vacuum::getResidualGasName(), Vacuum::getStop(), Vacuum::getTemperature(), gmsg, Vacuum::initialise(), Tracker::itsBunch_m, myElements, and VACUUM.
visitVariableRFCavity()
void ParallelCyclotronTracker::visitVariableRFCavity (const VariableRFCavity & cav) virtual
Apply the algorithm to a variabel RF cavity.
Parameters
cav
Reimplemented from DefaultVisitor.
Definition at line 1085 of file ParallelCyclotronTracker.cpp.
References Ring::appendElement(), endl(), gmsg, and opalRing_m.
visitVariableRFCavityFringeField()
void ParallelCyclotronTracker::visitVariableRFCavityFringeField (const VariableRFCavityFringeField & cav) virtual
Apply the algorithm to a variable RF cavity with Fringe Field.
Parameters
cav
Reimplemented from DefaultVisitor.
Definition at line 1100 of file ParallelCyclotronTracker.cpp.
References endl(), and gmsg.
visitVerticalFFAMagnet()
void ParallelCyclotronTracker::visitVerticalFFAMagnet (const VerticalFFAMagnet & mag) virtual
Apply the algorithm to a vertical FFA magnet.
Parameters
mag
Reimplemented from DefaultVisitor.
Definition at line 1114 of file ParallelCyclotronTracker.cpp.
References Ring::appendElement(), endl(), gmsg, and opalRing_m.
Member Data Documentation
azimuth_angle_m
std::vector<double> ParallelCyclotronTracker::azimuth_angle_m private
the different azimuthal angles for the outfTheta_m output files
Definition at line 318 of file ParallelCyclotronTracker.h.
Referenced by dumpAzimuthAngles_m(), and initializeTracking_m().
azimuth_m
double ParallelCyclotronTracker::azimuth_m private
Definition at line 290 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpStatData(), execute(), and saveInjectValues().
beamInitialRotation
double ParallelCyclotronTracker::beamInitialRotation = 0.0 private
Definition at line 247 of file ParallelCyclotronTracker.h.
Referenced by initDistInGlobalFrame(), and visitRing().
bega
double ParallelCyclotronTracker::bega private
The reference variables.
Definition at line 244 of file ParallelCyclotronTracker.h.
Referenced by setBeGa(), and visitCyclotron().
bgf_m
BoundaryGeometry* ParallelCyclotronTracker::bgf_m private
Definition at line 231 of file ParallelCyclotronTracker.h.
Referenced by bgf_main_collision_test(), and execute().
BinRepartTimer_m
IpplTimings::TimerRef ParallelCyclotronTracker::BinRepartTimer_m private
Definition at line 341 of file ParallelCyclotronTracker.h.
Referenced by ParallelCyclotronTracker(), and repartition().
cavCrossDatas_m
std::vector<CavityCrossData> ParallelCyclotronTracker::cavCrossDatas_m private
Definition at line 227 of file ParallelCyclotronTracker.h.
Referenced by execute(), and push().
cosRefTheta_m
double ParallelCyclotronTracker::cosRefTheta_m private
Definition at line 265 of file ParallelCyclotronTracker.h.
Referenced by initDistInGlobalFrame(), visitCyclotron(), and visitRing().
cycl_m
Cyclotron* ParallelCyclotronTracker::cycl_m private
Definition at line 233 of file ParallelCyclotronTracker.h.
Referenced by applyPluginElements(), and visitCyclotron().
DelParticleTimer_m
IpplTimings::TimerRef ParallelCyclotronTracker::DelParticleTimer_m private
Definition at line 343 of file ParallelCyclotronTracker.h.
Referenced by deleteParticle(), and ParallelCyclotronTracker().
DumpTimer_m
IpplTimings::TimerRef ParallelCyclotronTracker::DumpTimer_m private
Definition at line 339 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpPhaseSpaceData(), bunchDumpStatData(), ParallelCyclotronTracker(), and singleParticleDump().
extB_m
Vector_t ParallelCyclotronTracker::extB_m private
Definition at line 309 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpPhaseSpaceData(), bunchDumpStatData(), and execute().
extE_m
Vector_t ParallelCyclotronTracker::extE_m private
Definition at line 309 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpPhaseSpaceData(), bunchDumpStatData(), and execute().
FDext_m
Vector_t ParallelCyclotronTracker::FDext_m[2] private
Definition at line 309 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpPhaseSpaceData(), bunchDumpStatData(), and execute().
FieldDimensions
beamline_list ParallelCyclotronTracker::FieldDimensions private
Definition at line 223 of file ParallelCyclotronTracker.h.
Referenced by applyPluginElements(), buildupFieldList(), bunchDumpPhaseSpaceData(), bunchDumpStatData(), computeExternalFields_m(), execute(), gapCrossKick_m(), getHarmonicNumber(), and ~ParallelCyclotronTracker().
initialLocalNum_m
const size_t ParallelCyclotronTracker::initialLocalNum_m private
Definition at line 312 of file ParallelCyclotronTracker.h.
Referenced by checkFileMomentum(), initDistInGlobalFrame(), and setTimeStep().
initialTotalNum_m
const size_t ParallelCyclotronTracker::initialTotalNum_m private
Definition at line 313 of file ParallelCyclotronTracker.h.
Referenced by checkFileMomentum(), initDistInGlobalFrame(), and setTrackingMode().
IntegrationTimer_m
IpplTimings::TimerRef ParallelCyclotronTracker::IntegrationTimer_m private
Definition at line 338 of file ParallelCyclotronTracker.h.
Referenced by borisExternalFields(), bunchMode_m(), kick(), ParallelCyclotronTracker(), push(), seoMode_m(), and singleMode_m().
itsBeamline
Beamline* ParallelCyclotronTracker::itsBeamline private
Definition at line 225 of file ParallelCyclotronTracker.h.
Referenced by execute(), ParallelCyclotronTracker(), and ~ParallelCyclotronTracker().
itsDataSink
DataSink* ParallelCyclotronTracker::itsDataSink private
Definition at line 229 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpPhaseSpaceData(), bunchDumpStatData(), initPathLength(), and ParallelCyclotronTracker().
itsStepper_mp
std::unique_ptr< Stepper<function_t> > ParallelCyclotronTracker::itsStepper_mp private
Definition at line 466 of file ParallelCyclotronTracker.h.
Referenced by bunchMode_m(), execute(), gapCrossKick_m(), seoMode_m(), and singleMode_m().
lastDumpedStep_m
int ParallelCyclotronTracker::lastDumpedStep_m private
Definition at line 270 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpPhaseSpaceData(), finalizeTracking_m(), and setLastDumpedStep().
lossDs_m
std::unique_ptr<LossDataSink> ParallelCyclotronTracker::lossDs_m private
Definition at line 455 of file ParallelCyclotronTracker.h.
Referenced by bgf_main_collision_test(), and execute().
maxSteps_m
int ParallelCyclotronTracker::maxSteps_m private
The maximal number of steps the system is integrated.
Definition at line 236 of file ParallelCyclotronTracker.h.
Referenced by GenericTracker(), and MtsTracker().
mbHandler_m
std::unique_ptr<MultiBunchHandler> ParallelCyclotronTracker::mbHandler_m private
Definition at line 268 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpStatData(), bunchMode_m(), deleteParticle(), execute(), hasMultiBunch(), initDistInGlobalFrame(), initializeTracking_m(), initPathLength(), injectBunch(), isMultiBunch(), MtsTracker(), ParallelCyclotronTracker(), saveInjectValues(), updateAzimuthAndRadius(), updatePathLength(), updateTime(), and visitCyclotron().
mode_m
TrackingMode ParallelCyclotronTracker::mode_m private
Definition at line 475 of file ParallelCyclotronTracker.h.
Referenced by finalizeTracking_m(), GenericTracker(), initializeTracking_m(), MtsTracker(), setTrackingMode(), and update_m().
myElements
std::list<Component*> ParallelCyclotronTracker::myElements private
Definition at line 224 of file ParallelCyclotronTracker.h.
Referenced by visitCCollimator(), visitCorrector(), visitCyclotron(), visitDegrader(), visitDrift(), visitMarker(), visitMonitor(), visitMultipole(), visitMultipoleT(), visitMultipoleTCurvedConstRadius(), visitMultipoleTCurvedVarRadius(), visitMultipoleTStraight(), visitOutputPlane(), visitProbe(), visitRBend(), visitRFCavity(), visitRing(), visitSBend(), visitSeptum(), visitSolenoid(), visitStripper(), visitVacuum(), and ~ParallelCyclotronTracker().
myNode_m
const int ParallelCyclotronTracker::myNode_m private
Definition at line 311 of file ParallelCyclotronTracker.h.
Referenced by finalizeTracking_m(), initTrackOrbitFile(), and singleParticleDump().
opalRing_m
Ring* ParallelCyclotronTracker::opalRing_m private
Definition at line 452 of file ParallelCyclotronTracker.h.
Referenced by execute(), getHarmonicNumber(), getRing(), visitMultipoleT(), visitMultipoleTCurvedConstRadius(), visitMultipoleTCurvedVarRadius(), visitMultipoleTStraight(), visitOffset(), visitOutputPlane(), visitRing(), visitSBend3D(), visitScalingFFAMagnet(), visitVariableRFCavity(), and visitVerticalFFAMagnet().
outfTheta_m
std::vector<std::unique_ptr<std::ofstream> > ParallelCyclotronTracker::outfTheta_m private
output coordinates at different azimuthal angles and one after every turn
Definition at line 316 of file ParallelCyclotronTracker.h.
Referenced by closeFiles(), dumpAzimuthAngles_m(), dumpThetaEachTurn_m(), and openFiles().
outfTrackOrbit_m
std::ofstream ParallelCyclotronTracker::outfTrackOrbit_m private
output file for six dimensional phase space
Definition at line 324 of file ParallelCyclotronTracker.h.
Referenced by finalizeTracking_m(), initTrackOrbitFile(), seoMode_m(), singleMode_m(), and singleParticleDump().
pathLength_m
double ParallelCyclotronTracker::pathLength_m private
Definition at line 273 of file ParallelCyclotronTracker.h.
Referenced by initDistInGlobalFrame(), and updatePathLength().
pluginElements_m
std::vector<PluginElement*> ParallelCyclotronTracker::pluginElements_m private
Definition at line 226 of file ParallelCyclotronTracker.h.
Referenced by applyPluginElements(), execute(), and update_m().
PluginElemTimer_m
IpplTimings::TimerRef ParallelCyclotronTracker::PluginElemTimer_m private
Definition at line 342 of file ParallelCyclotronTracker.h.
Referenced by applyPluginElements(), and ParallelCyclotronTracker().
prevAzimuth_m
double ParallelCyclotronTracker::prevAzimuth_m private
Definition at line 291 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpStatData(), execute(), and saveInjectValues().
previousH5Local
bool ParallelCyclotronTracker::previousH5Local private
Definition at line 262 of file ParallelCyclotronTracker.h.
Referenced by setPreviousH5Local(), and visitCyclotron().
PreviousMeanP
Vector_t ParallelCyclotronTracker::PreviousMeanP private
Definition at line 260 of file ParallelCyclotronTracker.h.
Referenced by bunchMode_m(), and computeSpaceChargeFields_m().
referencePhi
double ParallelCyclotronTracker::referencePhi private
Definition at line 256 of file ParallelCyclotronTracker.h.
Referenced by initDistInGlobalFrame(), setPhi(), and visitCyclotron().
referencePr
double ParallelCyclotronTracker::referencePr private
Definition at line 250 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpPhaseSpaceData(), initDistInGlobalFrame(), setPr(), visitCyclotron(), and visitRing().
referencePsi
double ParallelCyclotronTracker::referencePsi private
Definition at line 255 of file ParallelCyclotronTracker.h.
Referenced by initDistInGlobalFrame(), setPsi(), and visitCyclotron().
referencePt
double ParallelCyclotronTracker::referencePt private
Definition at line 251 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpPhaseSpaceData(), initDistInGlobalFrame(), setPt(), visitCyclotron(), and visitRing().
referencePtot
double ParallelCyclotronTracker::referencePtot private
Definition at line 253 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpPhaseSpaceData(), checkFileMomentum(), visitCyclotron(), and visitRing().
referencePz
double ParallelCyclotronTracker::referencePz = 0.0 private
Definition at line 252 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpPhaseSpaceData(), initDistInGlobalFrame(), setPz(), visitCyclotron(), and visitRing().
referenceR
double ParallelCyclotronTracker::referenceR private
Definition at line 245 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpPhaseSpaceData(), initDistInGlobalFrame(), setR(), visitCyclotron(), and visitRing().
referenceTheta
double ParallelCyclotronTracker::referenceTheta private
Definition at line 246 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpPhaseSpaceData(), initDistInGlobalFrame(), initializeTracking_m(), setTheta(), visitCyclotron(), and visitRing().
referenceZ
double ParallelCyclotronTracker::referenceZ = 0.0 private
Definition at line 248 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpPhaseSpaceData(), initDistInGlobalFrame(), setZ(), visitCyclotron(), and visitRing().
restartStep0_m
long long ParallelCyclotronTracker::restartStep0_m private
Definition at line 285 of file ParallelCyclotronTracker.h.
Referenced by execute(), and initializeTracking_m().
rotation_m
matrix_t ParallelCyclotronTracker::rotation_m private
Definition at line 480 of file ParallelCyclotronTracker.h.
Referenced by globalToLocal(), localToGlobal(), rotateAroundX(), and rotateAroundZ().
setup_m
struct ParallelCyclotronTracker::settings ParallelCyclotronTracker::setup_m private
Referenced by bunchMode_m(), dumpAzimuthAngles_m(), initializeTracking_m(), injectBunch(), and isTurnDone().
sinRefTheta_m
double ParallelCyclotronTracker::sinRefTheta_m private
Definition at line 264 of file ParallelCyclotronTracker.h.
Referenced by initDistInGlobalFrame(), visitCyclotron(), and visitRing().
spiral_flag
bool ParallelCyclotronTracker::spiral_flag = false private
Definition at line 258 of file ParallelCyclotronTracker.h.
Referenced by computeSpaceChargeFields_m(), initializeTracking_m(), and visitCyclotron().
step_m
long long ParallelCyclotronTracker::step_m private
Definition at line 284 of file ParallelCyclotronTracker.h.
Referenced by bunchDumpPhaseSpaceData(), bunchMode_m(), computeSpaceChargeFields_m(), deleteParticle(), execute(), GenericTracker(), initDistInGlobalFrame(), initializeTracking_m(), injectBunch(), isTurnDone(), MtsTracker(), repartition(), seoMode_m(), singleMode_m(), and update_m().
stepper_m
Steppers::TimeIntegrator ParallelCyclotronTracker::stepper_m private
Definition at line 477 of file ParallelCyclotronTracker.h.
Referenced by execute().
TransformTimer_m
IpplTimings::TimerRef ParallelCyclotronTracker::TransformTimer_m private
Definition at line 340 of file ParallelCyclotronTracker.h.
Referenced by globalToLocal(), localToGlobal(), and ParallelCyclotronTracker().
turnnumber_m
int ParallelCyclotronTracker::turnnumber_m private
Definition at line 287 of file ParallelCyclotronTracker.h.
Referenced by applyPluginElements(), bgf_main_collision_test(), bunchMode_m(), dumpAzimuthAngles_m(), dumpThetaEachTurn_m(), execute(), finalizeTracking_m(), initializeTracking_m(), injectBunch(), MtsTracker(), and seoMode_m().
xaxis
Vector_t const ParallelCyclotronTracker::xaxis = Vector_t(1.0, 0.0, 0.0) static private
The positive axes unit vectors.
Definition at line 239 of file ParallelCyclotronTracker.h.
Referenced by getQuaternionTwoVectors().
yaxis
Vector_t const ParallelCyclotronTracker::yaxis = Vector_t(0.0, 1.0, 0.0) static private
Definition at line 240 of file ParallelCyclotronTracker.h.
Referenced by computeSpaceChargeFields_m().
zaxis
Vector_t const ParallelCyclotronTracker::zaxis = Vector_t(0.0, 0.0, 1.0) static private
Definition at line 241 of file ParallelCyclotronTracker.h.
Referenced by getQuaternionTwoVectors().
The documentation for this class was generated from the following files:
src/Algorithms/ParallelCyclotronTracker.h
src/Algorithms/ParallelCyclotronTracker.cpp