OPAL (Object Oriented Parallel Accelerator Library): CCollimator Class Reference
CCollimator Class Reference
#include <CCollimator.h>
Public Member Functions
CCollimator (const std::string &name)
Constructor with given name.
CCollimator ()
CCollimator (const CCollimator &rhs)
void operator= (const CCollimator &)=delete
virtual ~CCollimator ()
virtual void accept (BeamlineVisitor &) const override
Apply visitor to CCollimator.
void print ()
unused check method
void setDimensions (double xstart, double xend, double ystart, double yend, double zstart, double zend, double width)
Set dimensions and consistency checks.
void setDimensions (double xstart, double xend, double ystart, double yend)
unhide PluginElement::setDimensions(double xstart, double xend, double ystart, double yend)
virtual void goOnline (const double &kineticEnergy) override
Override implementation of PluginElement.
virtual ElementBase::ElementType getType () const override
Get element type std::string.
virtual void getDimensions (double &zBegin, double &zEnd) const override
double getZStart ()
Member variable access.
double getZEnd ()
double getWidth ()
Public Member Functions inherited from PluginElement
PluginElement (const std::string &name)
Constructor with given name.
PluginElement ()
PluginElement (const PluginElement &)
void operator= (const PluginElement &)=delete
virtual ~PluginElement ()
void setDimensions (double xstart, double xend, double ystart, double yend)
Set dimensions and consistency checks.
bool check (PartBunchBase< double, 3 > *bunch, const int turnnumber, const double t, const double tstep)
int checkPoint (const double &x, const double &y) const
Checks if coordinate is within element.
void save ()
Save output.
virtual void initialise (PartBunchBase< double, 3 > *bunch, double &startField, double &endField) override
Pure virtual implementation of Component.
void initialise (PartBunchBase< double, 3 > *bunch)
virtual void finalise () final
virtual void goOffline () final
virtual bool bends () const override
virtual bool apply (const size_t &i, const double &t, Vector_t &E, Vector_t &B) override
virtual bool applyToReferenceParticle (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B) override
double getXStart () const
Member variable access.
double getXEnd () const
double getYStart () const
double getYEnd () const
Public Member Functions inherited from Component
Component (const std::string &name)
Constructor with given name.
Component ()
Component (const Component &right)
virtual ~Component ()
virtual EMField & getField ()=0
Return field.
virtual const EMField & getField () const =0
Return field.
EVector Efield (const Point3D &P) const
Return the field in a point.
BVector Bfield (const Point3D &P) const
Return the field in a point.
EVector Efield (const Point3D &P, double t) const
Return the field in a point.
BVector Bfield (const Point3D &P, double t) const
Return the field in a point.
EBVectors EBfield (const Point3D &P) const
Return the field in a point.
EBVectors EBfield (const Point3D &P, double t) const
Return the field in a point.
virtual bool apply (const Vector_t &R, const Vector_t &P, const double &t, Vector_t &E, Vector_t &B)
virtual bool getPotential (const Vector_t &, const double &, Vector_t &, double &)
virtual double getDesignEnergy () const
virtual void setDesignEnergy (const double &energy, bool changeable=true)
virtual bool Online ()
virtual void setComponentType (std::string)
virtual std::string getComponentType () const
virtual const ElementBase & getDesign () const
Return design element.
virtual void trackBunch (PartBunchBase< double, 3 > *bunch, const PartData &, bool revBeam, bool revTrack) const
Track particle bunch.
virtual void trackMap (FVps< double, 6 > &map, const PartData &, bool revBeam, bool revTrack) const
Track a map.
void setExitFaceSlope (const double &)
Public Member Functions inherited from ElementBase
ElementBase (const std::string &name)
Constructor with given name.
ElementBase ()
ElementBase (const ElementBase &)
virtual ~ElementBase ()
virtual const std::string & getName () const
Get element name.
virtual void setName (const std::string &name)
Set element name.
std::string getTypeString () const
virtual BGeometryBase & getGeometry ()=0
Get geometry.
virtual const BGeometryBase & getGeometry () const =0
Get geometry.
virtual double getArcLength () const
Get arc length.
virtual double getElementLength () const
Get design length.
virtual void setElementLength (double length)
Set design length.
virtual void getElementDimensions (double &begin, double &end) const
virtual double getOrigin () const
Get origin position.
virtual double getEntrance () const
Get entrance position.
virtual double getExit () const
Get exit position.
virtual Euclid3D getTransform (double fromS, double toS) const
Get transform.
virtual Euclid3D getTransform (double s) const
Get transform.
virtual Euclid3D getTotalTransform () const
Get transform.
virtual Euclid3D getEntranceFrame () const
Get transform.
virtual Euclid3D getExitFrame () const
Get transform.
virtual Euclid3D getEntrancePatch () const
Get patch.
virtual Euclid3D getExitPatch () const
Get patch.
virtual double getAttribute (const std::string &aKey) const
Get attribute value.
virtual bool hasAttribute (const std::string &aKey) const
Test for existence of an attribute.
virtual void removeAttribute (const std::string &aKey)
Remove an existing attribute.
virtual void setAttribute (const std::string &aKey, double val)
Set value of an attribute.
virtual Channel * getChannel (const std::string &aKey, bool create=false)
Construct a read/write channel.
virtual const ConstChannel * getConstChannel (const std::string &aKey) const
Construct a read-only channel.
virtual ElementBase * clone () const =0
Return clone.
virtual ElementBase * copyStructure ()
Make a structural copy.
bool isSharable () const
Test if the element can be shared.
virtual void makeSharable ()
Set sharable flag.
bool update (const AttributeSet &)
Update element.
virtual void setBoundaryGeometry (BoundaryGeometry *geo)
virtual BoundaryGeometry * getBoundaryGeometry () const
return the attached boundary geometrt object if there is any
virtual bool hasBoundaryGeometry () const
virtual void setWake (WakeFunction *wf)
attach a wake field to the element
virtual WakeFunction * getWake () const
return the attached wake object if there is any
virtual bool hasWake () const
virtual void setParticleMatterInteraction (ParticleMatterInteractionHandler *spys)
virtual ParticleMatterInteractionHandler * getParticleMatterInteraction () const
virtual bool hasParticleMatterInteraction () const
void setCSTrafoGlobal2Local (const CoordinateSystemTrafo &ori)
CoordinateSystemTrafo getCSTrafoGlobal2Local () const
void releasePosition ()
void fixPosition ()
bool isPositioned () const
virtual CoordinateSystemTrafo getEdgeToBegin () const
virtual CoordinateSystemTrafo getEdgeToEnd () const
void setAperture (const ApertureType &type, const std::vector< double > &args)
std::pair< ElementBase::ApertureType, std::vector< double > > getAperture () const
virtual bool isInside (const Vector_t &r) const
void setMisalignment (const CoordinateSystemTrafo &cst)
void getMisalignment (double &x, double &y, double &s) const
CoordinateSystemTrafo getMisalignment () const
void setActionRange (const std::queue< std::pair< double, double > > &range)
void setCurrentSCoordinate (double s)
void setRotationAboutZ (double rotation)
Set rotation about z axis in bend frame.
double getRotationAboutZ () const
virtual BoundingBox getBoundingBoxInLabCoords () const
virtual int getRequiredNumberOfTimeSteps () const
void setOutputFN (std::string fn)
Set output filename.
std::string getOutputFN () const
Get output filename.
void setElementPosition (double elemedge)
Access to ELEMEDGE attribute.
double getElementPosition () const
bool isElementPositionSet () const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
virtual void doInitialise (PartBunchBase< double, 3 > *bunch) override
Initialise particle matter interaction.
virtual bool doCheck (PartBunchBase< double, 3 > *bunch, const int turnnumber, const double t, const double tstep) override
Record hits when bunch particles pass.
virtual void doSetGeom () override
Calculate extend in r.
virtual void doFinalise () override
Virtual hook for finalise.
virtual bool doPreCheck (PartBunchBase< double, 3 > *) override
Virtual hook for preCheck.
virtual bool doFinaliseCheck (PartBunchBase< double, 3 > *bunch, bool flagNeedUpdate) override
Virtual hook for finaliseCheck.
Private Attributes
bool informed_m = false
Flag if error information already printed.
double rmax_m
maximum extend in r
ParticleMatterInteractionHandler * parmatint_m = nullptr
double zstart_m
input geometry positions
double zend_m
double width_m
Additional Inherited Members
Public Types inherited from ElementBase
enum ApertureType { RECTANGULAR, ELLIPTICAL, CONIC_RECTANGULAR, CONIC_ELLIPTICAL }
enum ElementType {
BEAMLINE, CCOLLIMATOR, CORRECTOR, CYCLOTRON,
DEGRADER, DRIFT, FLEXIBLECOLLIMATOR, MARKER,
MONITOR, MPSPLITINTEGRATOR, MULTIPOLE, MULTIPOLET,
OFFSET, PROBE, RBEND, RBEND3D,
RFCAVITY, RING, SBEND3D, SBEND,
SEPTUM, SOLENOID, SOURCE, STRIPPER,
TRAVELINGWAVE, UNDULATOR, VACUUM, VARIABLERFCAVITY,
ANY
}
Static Public Member Functions inherited from ElementBase
static std::string getTypeString (ElementType type)
Protected Member Functions inherited from PluginElement
void setGeom (const double dist)
Sets geometry geom_m with element width dist.
void changeWidth (PartBunchBase< double, 3 > *bunch, int i, const double tstep, const double tangle)
Change probe width depending on step size and angle of particle.
double calculateIncidentAngle (double xp, double yp) const
Calculate angle of particle/bunch wrt to element.
Protected Member Functions inherited from ElementBase
bool isInsideTransverse (const Vector_t &r) const
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from PluginElement
double rmin_m
radius closest to the origin
Point geom_m [5]
actual geometry positions with adaptive width such that each particle hits element once per turn
double A_m
double B_m
double R_m
double C_m
Geometric lengths used in calculations.
std::unique_ptr< LossDataSink > lossDs_m
Pointer to Loss instance.
int numPassages_m = 0
Number of turns (number of times save() method is called)
double xstart_m
input geometry positions
double xend_m
double ystart_m
double yend_m
double rstart_m
double rend_m
Protected Attributes inherited from Component
double exit_face_slope_m
PartBunchBase< double, 3 > * RefPartBunch_m
bool online_m
Protected Attributes inherited from ElementBase
bool shareFlag
CoordinateSystemTrafo csTrafoGlobal2Local_m
CoordinateSystemTrafo misalignment_m
std::pair< ApertureType, std::vector< double > > aperture_m
double elementEdge_m
double rotationZAxis_m
Static Protected Attributes inherited from Component
static const std::vector< double > defaultAperture_m
Detailed Description
Definition at line 25 of file CCollimator.h.
Constructor & Destructor Documentation
CCollimator() [1/3]
CCollimator::CCollimator (const std::string & name) explicit
Constructor with given name.
Definition at line 34 of file CCollimator.cpp.
References setDimensions(), and PluginElement::setGeom().
CCollimator() [2/3]
CCollimator::CCollimator ()
Definition at line 31 of file CCollimator.cpp.
CCollimator() [3/3]
CCollimator::CCollimator (const CCollimator & rhs)
Definition at line 40 of file CCollimator.cpp.
References setDimensions(), PluginElement::setGeom(), width_m, PluginElement::xend_m, PluginElement::xstart_m, PluginElement::yend_m, PluginElement::ystart_m, zend_m, and zstart_m.
~CCollimator()
CCollimator::~CCollimator () virtual
Definition at line 50 of file CCollimator.cpp.
Member Function Documentation
accept()
void CCollimator::accept (BeamlineVisitor & visitor) const override virtual
Apply visitor to CCollimator.
Implements ElementBase.
Definition at line 52 of file CCollimator.cpp.
References BeamlineVisitor::visitCCollimator().
doCheck()
bool CCollimator::doCheck (PartBunchBase< double, 3 > * bunch, const int turnnumber, const double t, const double tstep) override private virtual
Record hits when bunch particles pass.
bunch->Bin[i] != -1 makes sure the particle is not stored in more than one collimator
Implements PluginElement.
Definition at line 78 of file CCollimator.cpp.
References PartBunchBase< T, Dim >::Bin, PartBunchBase< T, Dim >::bunchNum, PluginElement::checkPoint(), PartBunchBase< T, Dim >::getLocalNum(), PartBunchBase< T, Dim >::ID, PluginElement::lossDs_m, PartBunchBase< T, Dim >::M, PartBunchBase< T, Dim >::P, parmatint_m, PartBunchBase< T, Dim >::Q, PartBunchBase< T, Dim >::R, zend_m, and zstart_m.
doFinalise()
void CCollimator::doFinalise () override private virtual
Virtual hook for finalise.
Reimplemented from PluginElement.
Definition at line 126 of file CCollimator.cpp.
References endl(), ElementBase::getName(), and gmsg.
doFinaliseCheck()
bool CCollimator::doFinaliseCheck (PartBunchBase< double, 3 > * bunch, bool flagNeedUpdate) override private virtual
Virtual hook for finaliseCheck.
Reimplemented from PluginElement.
Definition at line 104 of file CCollimator.cpp.
References ParticleMatterInteractionHandler::apply(), euclidean_norm(), PartBunchBase< T, Dim >::get_bounds(), parmatint_m, and reduce().
doInitialise()
void CCollimator::doInitialise (PartBunchBase< double, 3 > * bunch) override private virtual
Initialise particle matter interaction.
Reimplemented from PluginElement.
Definition at line 117 of file CCollimator.cpp.
References ElementBase::getParticleMatterInteraction(), and parmatint_m.
doPreCheck()
bool CCollimator::doPreCheck (PartBunchBase< double, 3 > * bunch) override private virtual
Virtual hook for preCheck.
Reimplemented from PluginElement.
Definition at line 56 of file CCollimator.cpp.
References abs(), PartBunchBase< T, Dim >::get_bounds(), max(), min(), rmax_m, PluginElement::rmin_m, zend_m, and zstart_m.
doSetGeom()
void CCollimator::doSetGeom () override private virtual
Calculate extend in r.
Reimplemented from PluginElement.
Definition at line 167 of file CCollimator.cpp.
References PluginElement::geom_m, max(), and rmax_m.
getDimensions()
void CCollimator::getDimensions (double & zBegin, double & zEnd) const override virtual
Reimplemented from PluginElement.
Definition at line 158 of file CCollimator.cpp.
References ElementBase::getElementLength().
getType()
ElementBase::ElementType CCollimator::getType () const override virtual
Get element type std::string.
Reimplemented from Component.
Definition at line 163 of file CCollimator.cpp.
References ElementBase::CCOLLIMATOR.
getWidth()
double CCollimator::getWidth () inline
Definition at line 100 of file CCollimator.h.
References width_m.
Referenced by ParallelCyclotronTracker::visitCCollimator().
getZEnd()
double CCollimator::getZEnd () inline
Definition at line 95 of file CCollimator.h.
References zend_m.
Referenced by ParallelCyclotronTracker::visitCCollimator().
getZStart()
double CCollimator::getZStart () inline
Member variable access.
Definition at line 90 of file CCollimator.h.
References zstart_m.
Referenced by ParallelCyclotronTracker::visitCCollimator().
goOnline()
void CCollimator::goOnline (const double & kineticEnergy) override virtual
Override implementation of PluginElement.
Reimplemented from Component.
Definition at line 121 of file CCollimator.cpp.
References Component::online_m, and print().
operator=()
void CCollimator::operator= (const CCollimator &) delete
print()
void CCollimator::print ()
unused check method
Some debug print
Definition at line 130 of file CCollimator.cpp.
References endl(), ERRORMSG, informed_m, IpplInfo::myNode(), Component::RefPartBunch_m, and Fieldmap::typeset_msg().
Referenced by goOnline().
setDimensions() [1/2]
void CCollimator::setDimensions (double xstart, double xend, double ystart, double yend, double zstart, double zend, double width)
Set dimensions and consistency checks.
Definition at line 146 of file CCollimator.cpp.
References PluginElement::setGeom(), width_m, zend_m, and zstart_m.
Referenced by CCollimator(), and OpalCCollimator::update().
setDimensions() [2/2]
void PluginElement::setDimensions
unhide PluginElement::setDimensions(double xstart, double xend, double ystart, double yend)
Definition at line 85 of file PluginElement.cpp.
Member Data Documentation
informed_m
bool CCollimator::informed_m = false private
Flag if error information already printed.
Definition at line 77 of file CCollimator.h.
Referenced by print().
parmatint_m
ParticleMatterInteractionHandler* CCollimator::parmatint_m = nullptr private
Definition at line 86 of file CCollimator.h.
Referenced by doCheck(), doFinaliseCheck(), and doInitialise().
rmax_m
double CCollimator::rmax_m private
maximum extend in r
Definition at line 84 of file CCollimator.h.
Referenced by doPreCheck(), and doSetGeom().
width_m
double CCollimator::width_m private
Definition at line 82 of file CCollimator.h.
Referenced by CCollimator(), getWidth(), and setDimensions().
zend_m
double CCollimator::zend_m private
Definition at line 81 of file CCollimator.h.
Referenced by CCollimator(), doCheck(), doPreCheck(), getZEnd(), and setDimensions().
zstart_m
double CCollimator::zstart_m private
input geometry positions
Definition at line 80 of file CCollimator.h.
Referenced by CCollimator(), doCheck(), doPreCheck(), getZStart(), and setDimensions().
The documentation for this class was generated from the following files:
src/Classic/AbsBeamline/CCollimator.h
src/Classic/AbsBeamline/CCollimator.cpp