OPAL (Object Oriented Parallel Accelerator Library): SubField< T, Dim, M, C, S > Class Template Reference
SubField< T, Dim, M, C, S > Class Template Reference
#include <SubField.h>
Public Member Functions
Field< T, Dim, M, C > & getField () const
template<class S2 >
SubField< T, Dim, M, C, typename SubFieldTraits< T, Dim, S, S2 >::Return_t > operator[] (const S2 &s)
void operator= (T)
SubField< T, Dim, M, C, S > & operator= (const SubField< T, Dim, M, C, S > &)
template<class B >
SubField< T, Dim, M, C, S > & operator= (const PETE_Expr< B > &b)
template<class S2 >
SubField (Field< T, Dim, M, C > &f, const S2 &s)
Public Member Functions inherited from SubBareField< T, Dim, S >
constexpr SubBareField (const SubBareField< T, Dim, S > &)=default
iterator begin () const
iterator end () const
const S & getDomain () const
void makeNDIndex (NDIndex< Dim > &i)
BareField< T, Dim > & getBareField () const
T get ()
void get (T &r)
bool checkBrackets () const
template<class S2 >
SubBareField< T, Dim, typename SubFieldTraits< T, Dim, S, S2 >::Return_t > operator[] (const S2 &s)
SubBareField< T, Dim, S > & operator= (const SubBareField< T, Dim, S > &)
SubBareField< T, Dim, S > & operator= (T)
template<class B >
SubBareField< T, Dim, S > & operator= (const PETE_Expr< B > &b)
void write (std::ostream &)
iterator MakeExpression () const
PETE_TUTree< OpParens< int >, iterator > operator() (int arg)
PETE_TUTree< OpParens< std::pair< int, int > >, iterator > operator() (int a1, int a2)
template<class S2 >
SubBareField (BareField< T, Dim > &f, const S2 &s)
Public Member Functions inherited from PETE_Expr< SubBareField< T, Dim, S > >
SubBareField< T, Dim, S > & PETE_unwrap ()
const SubBareField< T, Dim, S > & PETE_unwrap () const
Protected Attributes
Field< T, Dim, M, C > & F
Protected Attributes inherited from SubBareField< T, Dim, S >
BareField< T, Dim > & A
S MyDomain
unsigned int Brackets
Friends
class Field< T, Dim, M, C >
Additional Inherited Members
Public Types inherited from SubBareField< T, Dim, S >
enum { Dim_u = Dim }
enum { IsExpr = 1 }
typedef T T_t
typedef S Index_t
typedef SubFieldIter< T, Dim, S > iterator
typedef iterator PETE_Expr_t
Public Types inherited from PETE_Expr< SubBareField< T, Dim, S > >
typedef SubBareField< T, Dim, S > Wrapped
Static Public Member Functions inherited from SubBareField< T, Dim, S >
static int getSubsetType ()
Protected Member Functions inherited from SubBareField< T, Dim, S >
bool checkAddBrackets (unsigned int)
Detailed Description
template<class T, unsigned int Dim, class M, class C, class S>
class SubField< T, Dim, M, C, S >
Definition at line 32 of file SubField.h.
Constructor & Destructor Documentation
SubField()
template<class T, unsigned int Dim, class M, class C, class S> template<class S2 > SubField< T, Dim, M, C, S >::SubField (Field< T, Dim, M, C > & f, const S2 & s) inline
Definition at line 122 of file SubField.h.
Member Function Documentation
getField()
template<class T, unsigned int Dim, class M, class C, class S> Field<T,Dim,M,C>& SubField< T, Dim, M, C, S >::getField () const inline
Definition at line 42 of file SubField.h.
References SubField< T, Dim, M, C, S >::F.
operator=() [1/3]
template<class T , unsigned int Dim, class M , class C , class S > void SubField< T, Dim, M, C, S >::operator= (T t)
Definition at line 36 of file SubField.hpp.
References assign().
operator=() [2/3]
template<class T , unsigned int Dim, class M , class C , class S > SubField< T, Dim, M, C, S > & SubField< T, Dim, M, C, S >::operator= (const SubField< T, Dim, M, C, S > & s)
Definition at line 46 of file SubField.hpp.
References assign().
operator=() [3/3]
template<class T, unsigned int Dim, class M, class C, class S> template<class B > SubField<T,Dim,M,C,S>& SubField< T, Dim, M, C, S >::operator= (const PETE_Expr< B > & b) inline
Definition at line 100 of file SubField.h.
References assign().
operator[]()
template<class T, unsigned int Dim, class M, class C, class S> template<class S2 > SubField<T,Dim,M,C,typename SubFieldTraits<T,Dim,S,S2>::Return_t> SubField< T, Dim, M, C, S >::operator[] (const S2 & s) inline
Definition at line 58 of file SubField.h.
References SubBareField< T, Dim, S >::checkAddBrackets(), SubFieldTraits< T, Dim, S1, S2 >::combine(), Dim, SubField< T, Dim, M, C, S >::F, and Attrib::Legacy::Distribution::T.
Friends And Related Function Documentation
Field< T, Dim, M, C >
template<class T, unsigned int Dim, class M, class C, class S> friend class Field< T, Dim, M, C > friend
Definition at line 34 of file SubField.h.
Member Data Documentation
F
template<class T, unsigned int Dim, class M, class C, class S> Field<T,Dim,M,C>& SubField< T, Dim, M, C, S >::F protected
Definition at line 110 of file SubField.h.
Referenced by SubField< T, Dim, M, C, S >::getField(), and SubField< T, Dim, M, C, S >::operator[]().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/SubField/SubField.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/SubField/SubField.hpp