OPAL (Object Oriented Parallel Accelerator Library): SampleCmd Class Reference
SampleCmd Class Reference
#include <SampleCmd.h>
Public Member Functions
SampleCmd ()
Exemplar constructor.
virtual ~SampleCmd ()
virtual SampleCmd * clone (const std::string &name)
Make clone.
virtual void execute ()
Execute the command.
Public Member Functions inherited from Action
virtual ~Action ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
SampleCmd (const SampleCmd &)=delete
void operator= (const SampleCmd &)=delete
SampleCmd (const std::string &name, SampleCmd *parent)
void stashEnvironment ()
void popEnvironment ()
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Action
Action (int size, const char *name, const char *help)
Constructor for exemplars.
Action (const std::string &name, Action *parent)
Constructor for cloning.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 28 of file SampleCmd.h.
Constructor & Destructor Documentation
SampleCmd() [1/3]
SampleCmd::SampleCmd ()
Exemplar constructor.
Definition at line 92 of file SampleCmd.cpp.
References AttributeHandler::COMMAND, Object::itsAttr, Attributes::makeBool(), Attributes::makeReal(), Attributes::makeString(), Attributes::makeStringArray(), Attributes::makeUpperCaseStringArray(), max(), min(), and Object::registerOwnership().
Referenced by clone().
~SampleCmd()
SampleCmd::~SampleCmd () virtual
Definition at line 141 of file SampleCmd.cpp.
SampleCmd() [2/3]
SampleCmd::SampleCmd (const SampleCmd &) private delete
SampleCmd() [3/3]
SampleCmd::SampleCmd (const std::string & name, SampleCmd * parent) private
Definition at line 137 of file SampleCmd.cpp.
Member Function Documentation
clone()
SampleCmd * SampleCmd::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 144 of file SampleCmd.cpp.
References name, and SampleCmd().
execute()
void SampleCmd::execute () virtual
Execute the command.
Reimplemented from Object.
Definition at line 148 of file SampleCmd.cpp.
References Physics::e, endl(), OpalSample::find(), Hypervolume::FromFile(), Hypervolume::fs, Attributes::getBool(), Objective::getExpression(), OpalData::getInstance(), DVar::getLowerBound(), Attributes::getReal(), OpalSample::getSize(), Attributes::getString(), Attributes::getStringArray(), DVar::getUpperBound(), DVar::getVariable(), OpalSample::getVariable(), gmsg, OpalSample::initialize(), Object::itsAttr, max(), min(), name, pi, popEnvironment(), OpalSample::sampleMethod_m, Options::seed, RNGStream::setGlobalSeed(), SIZE, and stashEnvironment().
operator=()
void SampleCmd::operator= (const SampleCmd &) private delete
popEnvironment()
void SampleCmd::popEnvironment () private
Definition at line 503 of file SampleCmd.cpp.
References Track::pop(), IpplTimings::pop(), IpplInfo::pop(), and OpalData::popInstance().
Referenced by execute().
stashEnvironment()
void SampleCmd::stashEnvironment () private
Definition at line 496 of file SampleCmd.cpp.
References Track::stash(), IpplTimings::stash(), IpplInfo::stash(), and OpalData::stashInstance().
Referenced by execute().
The documentation for this class was generated from the following files:
src/Sample/SampleCmd.h
src/Sample/SampleCmd.cpp