OPAL (Object Oriented Parallel Accelerator Library): WhileStatement Class Reference
WhileStatement Class Reference
While statement.
#include <WhileStatement.h>
Public Member Functions
WhileStatement (const Parser &, TokenStream &)
Constructor.
virtual ~WhileStatement ()
virtual void execute (const Parser &)
Execute.
Public Member Functions inherited from Statement
Statement (const std::string &name, int line)
Constructor.
Statement (const std::string &name, TokenList &)
Constructor.
virtual ~Statement ()
void append (const Token &)
Append a token.
bool atEnd () const
Test for end of command.
bool boolean (bool &value)
Return boolean value.
bool delimiter (char c)
Test for delimiter.
bool delimiter (const char *s)
Test for delimiter choice.
Token & getCurrent ()
Return current token and skip it.
bool integer (int &value)
Return signed integer.
bool integer (unsigned &value)
Return unsigned integer.
bool keyword (const char *s)
Test for keyword.
bool real (double &value)
Return real value.
bool str (std::string &value)
Return string value.
bool word (std::string &value)
Return word value.
void mark ()
Mark position in command.
void restore ()
Return to marked position.
void start ()
Return to start.
void skip ()
Skip.
unsigned int position () const
Return current character number in line.
virtual void print (std::ostream &os) const
Print statement.
virtual void printWhere (Inform &msg, bool withToken) const
Print position.
std::string str () const
Private Member Functions
WhileStatement ()
WhileStatement (const WhileStatement &)
void operator= (const WhileStatement &)
Private Attributes
Statement * while_block
Additional Inherited Members
Public Types inherited from Statement
typedef std::list< Token > TokenList
The type of the enclosed token list.
Protected Attributes inherited from Statement
int stat_line
std::string buffer_name
TokenList tokens
TokenList::iterator curr
TokenList::iterator keep
Detailed Description
While statement.
Definition at line 35 of file WhileStatement.h.
Constructor & Destructor Documentation
WhileStatement() [1/3]
WhileStatement::WhileStatement (const Parser & parser, TokenStream & is)
Constructor.
Definition at line 36 of file WhileStatement.cpp.
References Statement::append(), Token::isDel(), Token::isEOF(), Token::isKey(), Parser::readStatement(), TokenStream::readToken(), and while_block.
~WhileStatement()
WhileStatement::~WhileStatement () virtual
Definition at line 67 of file WhileStatement.cpp.
References while_block.
WhileStatement() [2/3]
WhileStatement::WhileStatement () private
WhileStatement() [3/3]
WhileStatement::WhileStatement (const WhileStatement &) private
Member Function Documentation
execute()
void WhileStatement::execute (const Parser & parser) virtual
Execute.
Implements Statement.
Definition at line 72 of file WhileStatement.cpp.
References Statement::curr, ERRORMSG, Statement::execute(), Attributes::getBool(), OpalData::getInstance(), Statement::keep, Attributes::makeBool(), Attribute::parse(), Statement::print(), Statement::tokens, OpalData::update(), and while_block.
operator=()
void WhileStatement::operator= (const WhileStatement &) private
Member Data Documentation
while_block
Statement* WhileStatement::while_block private
Definition at line 56 of file WhileStatement.h.
Referenced by execute(), WhileStatement(), and ~WhileStatement().
The documentation for this class was generated from the following files:
src/OpalParser/WhileStatement.h
src/OpalParser/WhileStatement.cpp