OPAL (Object Oriented Parallel Accelerator Library): MonitorStatisticsWriter Class Reference
MonitorStatisticsWriter Class Reference
#include <MonitorStatisticsWriter.h>
Public Member Functions
MonitorStatisticsWriter (const std::string &fname, bool restart)
void addRow (const SetStatistics &set)
Public Member Functions inherited from SDDSWriter
SDDSWriter (const std::string &fname, bool restart)
virtual ~SDDSWriter ()
virtual void write (const PartBunchBase< double, 3 > *)
void rewindLines (size_t numberOfLines)
delete the last 'numberOfLines' lines of the file 'fileName'
void replaceVersionString ()
double getLastValue (const std::string &column)
bool exists () const
Private Member Functions
void fillHeader ()
Additional Inherited Members
Public Types inherited from SDDSWriter
typedef std::pair< std::string, std::string > desc_t
typedef std::tuple< std::string, std::string, std::string > param_t
typedef std::pair< std::string, size_t > data_t
typedef std::tuple< std::string, std::string, std::string, std::string > cols_t
Protected Member Functions inherited from SDDSWriter
void addDescription (const std::string &text, const std::string &content)
template<typename T >
void addParameter (const std::string &name, const std::string &type, const std::string &desc, const T &value)
void addDefaultParameters ()
void addColumn (const std::string &name, const std::string &type, const std::string &unit, const std::string &desc)
void addInfo (const std::string &mode, const size_t &no_row_counts)
void writeRow ()
void open ()
void close ()
void writeHeader ()
Write SDDS header.
template<typename T >
std::string toString (const T &val)
bool hasColumns () const
Protected Attributes inherited from SDDSWriter
std::string fname_m
std::ios_base::openmode mode_m
First write to the statistics output file.
SDDSColumnSet columns_m
Detailed Description
Definition at line 25 of file MonitorStatisticsWriter.h.
Constructor & Destructor Documentation
MonitorStatisticsWriter()
MonitorStatisticsWriter::MonitorStatisticsWriter (const std::string & fname, bool restart)
Definition at line 24 of file MonitorStatisticsWriter.cpp.
Member Function Documentation
addRow()
void MonitorStatisticsWriter::addRow (const SetStatistics & set)
Definition at line 77 of file MonitorStatisticsWriter.cpp.
References SDDSColumnSet::addColumnValue(), SDDSWriter::close(), SDDSWriter::columns_m, fillHeader(), IpplInfo::myNode(), SDDSWriter::open(), Units::s2ns, SDDSWriter::writeHeader(), and SDDSWriter::writeRow().
Referenced by Monitor::writeStatistics().
fillHeader()
void MonitorStatisticsWriter::fillHeader () private
Definition at line 29 of file MonitorStatisticsWriter.cpp.
References SDDSColumnSet::addColumn(), SDDSWriter::addDefaultParameters(), SDDSWriter::addDescription(), SDDSWriter::addInfo(), SDDSWriter::columns_m, and SDDSWriter::hasColumns().
Referenced by addRow().
The documentation for this class was generated from the following files:
src/Structure/MonitorStatisticsWriter.h
src/Structure/MonitorStatisticsWriter.cpp