OPAL (Object Oriented Parallel Accelerator Library): SOffset< Dim > Class Template Reference
SOffset< Dim > Class Template Reference
#include <SOffset.h>
Public Types
typedef int * iterator
typedef const int * const_iterator
Public Member Functions
SOffset ()
SOffset (int v0)
SOffset (int v0, int v1)
SOffset (int v0, int v1, int v2)
SOffset (int v0, int v1, int v2, int v3)
SOffset (int v0, int v1, int v2, int v3, int v4)
SOffset (int v0, int v1, int v2, int v3, int v4, int v5)
SOffset (const int *vv)
SOffset (const SOffset< Dim > &)
SOffset< Dim > & operator= (const SOffset< Dim > &)
SOffset< Dim > & operator= (const int *)
int & operator[] (unsigned int d)
const int & operator[] (unsigned int d) const
bool operator== (const SOffset< Dim > &) const
bool operator< (const SOffset< Dim > &) const
bool operator!= (const SOffset< Dim > &a) const
bool operator<= (const SOffset< Dim > &a) const
bool operator>= (const SOffset< Dim > &a) const
bool operator> (const SOffset< Dim > &a) const
SOffset< Dim > & operator+= (const SOffset< Dim > &)
SOffset< Dim > & operator+= (const int *)
SOffset< Dim > & operator-= (const SOffset< Dim > &)
SOffset< Dim > & operator-= (const int *)
SOffset< Dim > & operator*= (const SOffset< Dim > &)
SOffset< Dim > & operator*= (const int *)
SOffset< Dim > & operator/= (const SOffset< Dim > &)
SOffset< Dim > & operator/= (const int *)
Message & putMessage (Message &)
Message & getMessage (Message &)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
unsigned int size () const
bool inside (const NDIndex< Dim > &) const
Private Attributes
int v [Dim]
Detailed Description
template<unsigned Dim>
class SOffset< Dim >
Definition at line 22 of file SOffset.h.
Member Typedef Documentation
const_iterator
template<unsigned Dim> typedef const int* SOffset< Dim >::const_iterator
Definition at line 87 of file SOffset.h.
iterator
template<unsigned Dim> typedef int* SOffset< Dim >::iterator
Definition at line 86 of file SOffset.h.
Constructor & Destructor Documentation
SOffset() [1/9]
template<unsigned Dim> SOffset< Dim >::SOffset () inline
Definition at line 91 of file SOffset.h.
References Dim, and SOffset< Dim >::v.
SOffset() [2/9]
template<unsigned Dim> SOffset< Dim >::SOffset (int v0) inline
Definition at line 92 of file SOffset.h.
References Dim, and SOffset< Dim >::v.
SOffset() [3/9]
template<unsigned int Dim> SOffset< Dim >::SOffset (int v0, int v1) inline
Definition at line 154 of file SOffset.h.
References CTAssert, and Dim.
SOffset() [4/9]
template<unsigned int Dim> SOffset< Dim >::SOffset (int v0, int v1, int v2) inline
Definition at line 162 of file SOffset.h.
References CTAssert, and Dim.
SOffset() [5/9]
template<unsigned int Dim> SOffset< Dim >::SOffset (int v0, int v1, int v2, int v3) inline
Definition at line 171 of file SOffset.h.
References CTAssert, and Dim.
SOffset() [6/9]
template<unsigned int Dim> SOffset< Dim >::SOffset (int v0, int v1, int v2, int v3, int v4) inline
Definition at line 181 of file SOffset.h.
References CTAssert, and Dim.
SOffset() [7/9]
template<unsigned int Dim> SOffset< Dim >::SOffset (int v0, int v1, int v2, int v3, int v4, int v5) inline
Definition at line 192 of file SOffset.h.
References CTAssert, and Dim.
SOffset() [8/9]
template<unsigned int L> SOffset< L >::SOffset (const int * vv) inline
Definition at line 350 of file SOffset.h.
References divide_soffset_op().
SOffset() [9/9]
template<unsigned int L> SOffset< L >::SOffset (const SOffset< L > & SO) inline
Definition at line 342 of file SOffset.h.
References divide_soffset_op(), and SOffset< Dim >::v.
Member Function Documentation
begin() [1/2]
template<unsigned Dim> iterator SOffset< Dim >::begin () inline
Definition at line 132 of file SOffset.h.
References SOffset< Dim >::v.
Referenced by SubFieldIter< T, Dim, SIndex< Dim > >::offset(), and SubFieldIter< T, Dim, SOffset< Dim > >::setLFieldData().
begin() [2/2]
template<unsigned Dim> const_iterator SOffset< Dim >::begin () const inline
Definition at line 134 of file SOffset.h.
References SOffset< Dim >::v.
end() [1/2]
template<unsigned Dim> iterator SOffset< Dim >::end () inline
Definition at line 133 of file SOffset.h.
References Dim, and SOffset< Dim >::v.
end() [2/2]
template<unsigned Dim> const_iterator SOffset< Dim >::end () const inline
Definition at line 135 of file SOffset.h.
References Dim, and SOffset< Dim >::v.
getMessage()
template<unsigned int Dim> Message & SOffset< Dim >::getMessage (Message & m) inline
Definition at line 234 of file SOffset.h.
References getMessage_iter().
inside()
template<unsigned int Dim> bool SOffset< Dim >::inside (const NDIndex< Dim > & ndi) const inline
Definition at line 254 of file SOffset.h.
References Dim.
Referenced by LSIndex< Dim >::contains().
operator!=()
template<unsigned Dim> bool SOffset< Dim >::operator!= (const SOffset< Dim > & a) const inline
Definition at line 110 of file SOffset.h.
References a.
operator*=() [1/2]
template<unsigned int L> SOffset< L > & SOffset< L >::operator*= (const SOffset< L > & SO) inline
Definition at line 413 of file SOffset.h.
References divide_soffset_op(), and SOffset< Dim >::v.
operator*=() [2/2]
template<unsigned int L> SOffset< L > & SOffset< L >::operator*= (const int * SO) inline
Definition at line 422 of file SOffset.h.
References divide_soffset_op().
operator+=() [1/2]
template<unsigned int L> SOffset< L > & SOffset< L >::operator+= (const SOffset< L > & SO) inline
Definition at line 377 of file SOffset.h.
References divide_soffset_op(), and SOffset< Dim >::v.
operator+=() [2/2]
template<unsigned int L> SOffset< L > & SOffset< L >::operator+= (const int * SO) inline
Definition at line 386 of file SOffset.h.
References divide_soffset_op().
operator-=() [1/2]
template<unsigned int L> SOffset< L > & SOffset< L >::operator-= (const SOffset< L > & SO) inline
Definition at line 395 of file SOffset.h.
References divide_soffset_op(), and SOffset< Dim >::v.
operator-=() [2/2]
template<unsigned int L> SOffset< L > & SOffset< L >::operator-= (const int * SO) inline
Definition at line 404 of file SOffset.h.
References divide_soffset_op().
operator/=() [1/2]
template<unsigned int L> SOffset< L > & SOffset< L >::operator/= (const SOffset< L > & SO) inline
Definition at line 431 of file SOffset.h.
References divide_soffset_op(), and SOffset< Dim >::v.
operator/=() [2/2]
template<unsigned int L> SOffset< L > & SOffset< L >::operator/= (const int * SO) inline
Definition at line 440 of file SOffset.h.
References divide_soffset_op().
operator<()
template<unsigned int Dim> bool SOffset< Dim >::operator< (const SOffset< Dim > & a) const inline
Definition at line 213 of file SOffset.h.
References a, and Dim.
operator<=()
template<unsigned Dim> bool SOffset< Dim >::operator<= (const SOffset< Dim > & a) const inline
Definition at line 111 of file SOffset.h.
References a.
operator=() [1/2]
template<unsigned int L> SOffset< L > & SOffset< L >::operator= (const SOffset< L > & SO) inline
Definition at line 358 of file SOffset.h.
References divide_soffset_op(), and SOffset< Dim >::v.
operator=() [2/2]
template<unsigned int L> SOffset< L > & SOffset< L >::operator= (const int * SO) inline
Definition at line 368 of file SOffset.h.
References divide_soffset_op().
operator==()
template<unsigned int Dim> bool SOffset< Dim >::operator== (const SOffset< Dim > & a) const inline
Definition at line 204 of file SOffset.h.
References a, and Dim.
operator>()
template<unsigned Dim> bool SOffset< Dim >::operator> (const SOffset< Dim > & a) const inline
Definition at line 113 of file SOffset.h.
References a.
operator>=()
template<unsigned Dim> bool SOffset< Dim >::operator>= (const SOffset< Dim > & a) const inline
Definition at line 112 of file SOffset.h.
References a.
operator[]() [1/2]
template<unsigned Dim> int& SOffset< Dim >::operator[] (unsigned int d) inline
Definition at line 104 of file SOffset.h.
References SOffset< Dim >::v.
operator[]() [2/2]
template<unsigned Dim> const int& SOffset< Dim >::operator[] (unsigned int d) const inline
Definition at line 105 of file SOffset.h.
References SOffset< Dim >::v.
putMessage()
template<unsigned int Dim> Message & SOffset< Dim >::putMessage (Message & m) inline
Definition at line 227 of file SOffset.h.
References Dim, and putMessage().
size()
template<unsigned Dim> unsigned int SOffset< Dim >::size (void) const inline
Definition at line 136 of file SOffset.h.
References Dim.
Member Data Documentation
v
template<unsigned Dim> int SOffset< Dim >::v[Dim] private
Definition at line 142 of file SOffset.h.
Referenced by SOffset< Dim >::begin(), SOffset< Dim >::end(), SOffset< Dim >::operator*=(), SOffset< Dim >::operator+=(), SOffset< Dim >::operator-=(), SOffset< Dim >::operator/=(), SOffset< Dim >::operator=(), SOffset< Dim >::operator[](), and SOffset< Dim >::SOffset().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Index/SOffset.h