OPAL (Object Oriented Parallel Accelerator Library): SampleGaussianSequence Class Reference
SampleGaussianSequence Class Reference
#include <SampleGaussianSequence.h>
Public Member Functions
SampleGaussianSequence (double lower, double upper, size_t modulo, int nSample)
void create (std::shared_ptr< SampleIndividual > &ind, size_t i)
double getNext (unsigned int id)
Public Member Functions inherited from SamplingMethod
virtual ~SamplingMethod ()
virtual void allocate (const CmdArguments_t &, const Comm::Bundle_t &)
Private Attributes
std::vector< double > sampleChain_m
unsigned int numSamples_m
size_t volumeLowerDimensions_m
Detailed Description
Definition at line 35 of file SampleGaussianSequence.h.
Constructor & Destructor Documentation
SampleGaussianSequence()
SampleGaussianSequence::SampleGaussianSequence (double lower, double upper, size_t modulo, int nSample) inline
Definition at line 40 of file SampleGaussianSequence.h.
References Util::erfinv(), sampleChain_m, and sqrt().
Member Function Documentation
create()
void SampleGaussianSequence::create (std::shared_ptr< SampleIndividual > & ind, size_t i) inline virtual
Implements SamplingMethod.
Definition at line 55 of file SampleGaussianSequence.h.
References getNext().
getNext()
double SampleGaussianSequence::getNext (unsigned int id) inline
Definition at line 59 of file SampleGaussianSequence.h.
References numSamples_m, sampleChain_m, and volumeLowerDimensions_m.
Referenced by create().
Member Data Documentation
numSamples_m
unsigned int SampleGaussianSequence::numSamples_m private
Definition at line 71 of file SampleGaussianSequence.h.
Referenced by getNext().
sampleChain_m
std::vector<double> SampleGaussianSequence::sampleChain_m private
Definition at line 70 of file SampleGaussianSequence.h.
Referenced by getNext(), and SampleGaussianSequence().
volumeLowerDimensions_m
size_t SampleGaussianSequence::volumeLowerDimensions_m private
Definition at line 72 of file SampleGaussianSequence.h.
Referenced by getNext().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/src/Sample/SampleGaussianSequence.h