OPAL (Object Oriented Parallel Accelerator Library): Fieldmap Class Reference
Fieldmap Class Reference abstract
#include <Fieldmap.h>
Classes
struct FieldmapDescription
struct TypeParseTraits
struct TypeParseTraits< double >
struct TypeParseTraits< int >
struct TypeParseTraits< std::string >
struct TypeParseTraits< unsigned int >
Public Member Functions
virtual bool getFieldstrength (const Vector_t &R, Vector_t &E, Vector_t &B) const =0
virtual bool getFieldDerivative (const Vector_t &R, Vector_t &E, Vector_t &B, const DiffDirection &dir) const =0
virtual void getFieldDimensions (double &zBegin, double &zEnd) const =0
virtual void getFieldDimensions (double &xIni, double &xFinal, double &yIni, double &yFinal, double &zIni, double &zFinal) const =0
virtual void swap ()=0
virtual void getInfo (Inform *msg)=0
virtual double getFrequency () const =0
virtual void setFrequency (double freq)=0
virtual void setEdgeConstants (const double &bendAngle, const double &entranceAngle, const double &exitAngle)
virtual void setFieldLength (const double &)
virtual void get1DProfile1EngeCoeffs (std::vector< double > &engeCoeffsEntry, std::vector< double > &engeCoeffsExit)
virtual void get1DProfile1EntranceParam (double &entranceParameter1, double &entranceParameter2, double &entranceParameter3)
virtual void get1DProfile1ExitParam (double &exitParameter1, double &exitParameter2, double &exitParameter3)
virtual double getFieldGap ()
virtual void setFieldGap (double gap)
MapType getType ()
virtual void getOnaxisEz (std::vector< std::pair< double, double > > &onaxis)
virtual bool isInside (const Vector_t &) const
virtual void readMap ()=0
virtual void freeMap ()=0
template<class T >
bool interpretLine (std::ifstream &in, T &value, const bool &file_length_known)
Static Public Member Functions
static Fieldmap * getFieldmap (std::string Filename, bool fast=false)
static std::vector< std::string > getListFieldmapNames ()
static void deleteFieldmap (std::string Filename)
static void clearDictionary ()
static MapType readHeader (std::string Filename)
static void readMap (std::string Filename)
static void freeMap (std::string Filename)
static std::string typeset_msg (const std::string &msg, const std::string &title)
Protected Member Functions
Fieldmap ()=delete
Fieldmap (const std::string &aFilename)
virtual ~Fieldmap ()
void getLine (std::ifstream &in, std::string &buffer)
template<class S >
bool interpretLine (std::ifstream &in, S &value, const bool &file_length_known=true)
template<class S , class T >
bool interpretLine (std::ifstream &in, S &value1, T &value2, const bool &file_length_known=true)
template<class S , class T , class U >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, const bool &file_length_known=true)
template<class S , class T , class U , class V >
bool interpretLine (std::ifstream &in, S &value1, T &value2, U &value3, V &value4, const bool &file_length_known=true)
template<class S >
bool interpretLine (std::ifstream &in, S &value1, S &value2, S &value3, S &value4, S &value5, S &value6, const bool &file_length_known=true)
bool interpreteEOF (std::ifstream &in)
void interpretWarning (const std::ios_base::iostate &state, const bool &read_all, const std::string &error_msg, const std::string &found)
void missingValuesWarning ()
void exceedingValuesWarning ()
void disableFieldmapWarning ()
void noFieldmapWarning ()
void lowResolutionWarning (double squareError, double maxError)
void checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void checkMap (unsigned int accuracy, double length, const std::vector< double > &zSampling, const std::vector< double > &fourierCoefficients, gsl_spline *splineCoefficients, gsl_interp_accel *splineAccelerator)
void write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > &xrange, const std::pair< double, double > &yrange, const std::pair< double, double > &zrange, const std::vector< Vector_t > &ef, const std::vector< Vector_t > &bf)
Static Protected Member Functions
static void getLine (std::ifstream &in, int &lines_read, std::string &buffer)
Protected Attributes
MapType Type
std::string Filename_m
int lines_read_m
bool normalize_m
Static Private Attributes
static char buffer_m [256]
static std::string alpha_numeric
static std::map< std::string, FieldmapDescription > FieldmapDictionary = std::map<std::string, Fieldmap::FieldmapDescription>()
Detailed Description
Definition at line 60 of file Fieldmap.h.
Constructor & Destructor Documentation
Fieldmap() [1/2]
Fieldmap::Fieldmap () protected delete
Fieldmap() [2/2]
Fieldmap::Fieldmap (const std::string & aFilename) inline protected
Definition at line 109 of file Fieldmap.h.
~Fieldmap()
virtual Fieldmap::~Fieldmap () inline protected virtual
Definition at line 114 of file Fieldmap.h.
Member Function Documentation
checkMap() [1/2]
void Fieldmap::checkMap (unsigned int accuracy, std::pair< double, double > fieldDimensions, double deltaZ, const std::vector< double > & fourierCoefficients, gsl_spline * splineCoefficients, gsl_interp_accel * splineAccelerator) protected
Definition at line 451 of file Fieldmap.cpp.
Referenced by FM1DElectroStatic_fast::prepareForMapCheck(), FM1DMagnetoStatic_fast::prepareForMapCheck(), FM1DDynamic_fast::prepareForMapCheck(), Astra1DElectroStatic_fast::readMap(), Astra1DMagnetoStatic_fast::readMap(), and Astra1DDynamic_fast::readMap().
checkMap() [2/2]
void Fieldmap::checkMap (unsigned int accuracy, double length, const std::vector< double > & zSampling, const std::vector< double > & fourierCoefficients, gsl_spline * splineCoefficients, gsl_interp_accel * splineAccelerator) protected
Definition at line 467 of file Fieldmap.cpp.
References abs(), Util::combineFilePath(), cos(), Physics::e, end(), endl(), Filename_m, OpalData::getInstance(), lowResolutionWarning(), IpplInfo::myNode(), Hypervolume::n, pow(), sin(), sqrt(), and Physics::two_pi.
clearDictionary()
void Fieldmap::clearDictionary () static
Definition at line 275 of file Fieldmap.cpp.
References FieldmapDictionary.
Referenced by opalMain(), and run_opal().
deleteFieldmap()
void Fieldmap::deleteFieldmap (std::string Filename) static
Definition at line 271 of file Fieldmap.cpp.
References freeMap().
disableFieldmapWarning()
void Fieldmap::disableFieldmapWarning () protected
Definition at line 613 of file Fieldmap.cpp.
References Filename_m.
Referenced by Astra1DDynamic::Astra1DDynamic(), Astra1DDynamic_fast::Astra1DDynamic_fast(), Astra1DElectroStatic::Astra1DElectroStatic(), Astra1DElectroStatic_fast::Astra1DElectroStatic_fast(), Astra1DMagnetoStatic::Astra1DMagnetoStatic(), Astra1DMagnetoStatic_fast::Astra1DMagnetoStatic_fast(), FM1DDynamic::FM1DDynamic(), FM1DDynamic_fast::FM1DDynamic_fast(), FM1DElectroStatic::FM1DElectroStatic(), FM1DElectroStatic_fast::FM1DElectroStatic_fast(), FM1DMagnetoStatic::FM1DMagnetoStatic(), FM1DMagnetoStatic_fast::FM1DMagnetoStatic_fast(), FM1DProfile1::FM1DProfile1(), FM1DProfile2::FM1DProfile2(), FM2DDynamic::FM2DDynamic(), FM2DElectroStatic::FM2DElectroStatic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), FM3DDynamic::FM3DDynamic(), FM3DMagnetoStaticExtended::FM3DMagnetoStaticExtended(), and FMDummy::FMDummy().
exceedingValuesWarning()
void Fieldmap::exceedingValuesWarning () protected
Definition at line 603 of file Fieldmap.cpp.
References Filename_m, and lines_read_m.
Referenced by interpreteEOF().
freeMap() [1/2]
void Fieldmap::freeMap (std::string Filename) static
Definition at line 433 of file Fieldmap.cpp.
References FieldmapDictionary.
freeMap() [2/2]
virtual void Fieldmap::freeMap () pure virtual
Implemented in FM1DProfile1, FM3DH5Block, FM3DH5Block_nonscale, FM3DMagnetoStaticH5Block, FM3DH5BlockBase, FM1DDynamic, FM1DDynamic_fast, FM1DElectroStatic, FM1DElectroStatic_fast, FM1DMagnetoStatic, FM1DMagnetoStatic_fast, FM2DDynamic, Astra1D_fast, Astra1DDynamic, FM1DProfile2, FM3DDynamic, Astra1DElectroStatic, Astra1DMagnetoStatic, FM2DElectroStatic, FM2DMagnetoStatic, FM3DMagnetoStatic, FM3DMagnetoStaticExtended, and FMDummy.
Referenced by deleteFieldmap(), Solenoid::goOffline(), TravelingWave::goOffline(), RBend3D::goOffline(), and RFCavity::goOffline().
get1DProfile1EngeCoeffs()
void Fieldmap::get1DProfile1EngeCoeffs (std::vector< double > & engeCoeffsEntry, std::vector< double > & engeCoeffsExit) virtual
Reimplemented in FM1DProfile1.
Definition at line 712 of file Fieldmap.cpp.
Referenced by Bend2D::readFieldMap().
get1DProfile1EntranceParam()
void Fieldmap::get1DProfile1EntranceParam (double & entranceParameter1, double & entranceParameter2, double & entranceParameter3) virtual
Reimplemented in FM1DProfile1.
Definition at line 717 of file Fieldmap.cpp.
Referenced by Bend2D::getEntranceFringeFieldLength(), and Bend2D::readFieldMap().
get1DProfile1ExitParam()
void Fieldmap::get1DProfile1ExitParam (double & exitParameter1, double & exitParameter2, double & exitParameter3) virtual
Reimplemented in FM1DProfile1.
Definition at line 723 of file Fieldmap.cpp.
Referenced by Bend2D::getExitFringeFieldLength(), and Bend2D::readFieldMap().
getFieldDerivative()
virtual bool Fieldmap::getFieldDerivative (const Vector_t & R, Vector_t & E, Vector_t & B, const DiffDirection & dir) const pure virtual
Implemented in FM3DH5BlockBase, Astra1DDynamic_fast, FM1DProfile1, FM1DElectroStatic, FM1DElectroStatic_fast, FM1DMagnetoStatic, FM1DMagnetoStatic_fast, FM2DDynamic, Astra1DElectroStatic, Astra1DElectroStatic_fast, Astra1DMagnetoStatic, Astra1DMagnetoStatic_fast, FM2DElectroStatic, FM3DDynamic, FM3DMagnetoStatic, Astra1D_fast, Astra1DDynamic, FM1DDynamic, FM1DDynamic_fast, FM1DProfile2, FM2DMagnetoStatic, FM3DMagnetoStaticExtended, and FMDummy.
getFieldDimensions() [1/2]
virtual void Fieldmap::getFieldDimensions (double & zBegin, double & zEnd) const pure virtual
Implemented in FM3DH5BlockBase, Astra1DDynamic_fast, FM1DProfile1, FM1DDynamic, FM1DDynamic_fast, FM2DDynamic, Astra1D_fast, Astra1DDynamic, FM1DProfile2, FM2DMagnetoStatic, FM3DMagnetoStaticExtended, FMDummy, Astra1DElectroStatic, Astra1DElectroStatic_fast, Astra1DMagnetoStatic, Astra1DMagnetoStatic_fast, FM1DElectroStatic, FM1DElectroStatic_fast, FM1DMagnetoStatic, FM1DMagnetoStatic_fast, FM2DElectroStatic, FM3DDynamic, and FM3DMagnetoStatic.
Referenced by RFCavity::getElementDimensions(), RFCavity::getElementLength(), RBend3D::getSurfaceMesh(), Solenoid::initialise(), RBend3D::initialise(), and RFCavity::initialise().
getFieldDimensions() [2/2]
virtual void Fieldmap::getFieldDimensions (double & xIni, double & xFinal, double & yIni, double & yFinal, double & zIni, double & zFinal) const pure virtual
Implemented in FM3DH5BlockBase, Astra1DDynamic_fast, FM1DProfile1, FM1DDynamic, FM1DDynamic_fast, FM2DDynamic, Astra1D_fast, Astra1DDynamic, FM1DProfile2, FM2DMagnetoStatic, FM3DMagnetoStaticExtended, FMDummy, Astra1DElectroStatic, Astra1DElectroStatic_fast, Astra1DMagnetoStatic, Astra1DMagnetoStatic_fast, FM1DElectroStatic, FM1DElectroStatic_fast, FM1DMagnetoStatic, FM1DMagnetoStatic_fast, FM2DElectroStatic, FM3DDynamic, and FM3DMagnetoStatic.
getFieldGap()
double Fieldmap::getFieldGap () virtual
Reimplemented in FM1DProfile1.
Definition at line 729 of file Fieldmap.cpp.
Referenced by Bend2D::setGapFromFieldMap().
getFieldmap()
Fieldmap * Fieldmap::getFieldmap (std::string Filename, bool fast = false) static
Definition at line 50 of file Fieldmap.cpp.
References FieldmapDictionary, readHeader(), T1DDynamic, T1DElectroStatic, T1DMagnetoStatic, T1DProfile1, T1DProfile2, T2DDynamic, T2DElectroStatic, T2DMagnetoStatic, T3DDynamic, T3DDynamicH5Block, T3DMagnetoStatic, T3DMagnetoStatic_Extended, T3DMagnetoStaticH5Block, TAstraDynamic, TAstraElectroStatic, and TAstraMagnetoStatic.
Referenced by Cyclotron::getFieldFromFile_BandRF(), Cyclotron::getFieldFromFile_Synchrocyclotron(), Solenoid::initialise(), RBend3D::initialise(), RFCavity::initialise(), and Bend2D::initializeFieldMap().
getFieldstrength()
virtual bool Fieldmap::getFieldstrength (const Vector_t & R, Vector_t & E, Vector_t & B) const pure virtual
Implemented in FM3DH5BlockBase, FM1DProfile1, Astra1DDynamic_fast, FM3DH5Block, FM3DH5Block_nonscale, FM3DMagnetoStaticH5Block, FM2DDynamic, Astra1D_fast, Astra1DDynamic, Astra1DElectroStatic, Astra1DElectroStatic_fast, Astra1DMagnetoStatic, Astra1DMagnetoStatic_fast, FM1DDynamic, FM1DDynamic_fast, FM1DElectroStatic, FM1DElectroStatic_fast, FM1DMagnetoStatic, FM1DMagnetoStatic_fast, FM1DProfile2, FM2DElectroStatic, FM2DMagnetoStatic, FM3DDynamic, FM3DMagnetoStatic, FM3DMagnetoStaticExtended, and FMDummy.
Referenced by Solenoid::apply(), TravelingWave::apply(), RBend3D::apply(), RFCavity::apply(), Solenoid::applyToReferenceParticle(), TravelingWave::applyToReferenceParticle(), RBend3D::applyToReferenceParticle(), RFCavity::applyToReferenceParticle(), and RBend3D::initialise().
getFrequency()
virtual double Fieldmap::getFrequency () const pure virtual
Implemented in FM3DH5BlockBase, FM3DMagnetoStaticH5Block, FM1DProfile1, Astra1DDynamic_fast, FM1DDynamic, FM1DDynamic_fast, FM1DElectroStatic, FM1DElectroStatic_fast, FM1DMagnetoStatic, FM1DMagnetoStatic_fast, FM2DDynamic, Astra1D_fast, Astra1DDynamic, Astra1DElectroStatic, Astra1DElectroStatic_fast, Astra1DMagnetoStatic, Astra1DMagnetoStatic_fast, FM1DProfile2, FM2DElectroStatic, FM2DMagnetoStatic, FM3DDynamic, FM3DMagnetoStatic, FM3DMagnetoStaticExtended, and FMDummy.
Referenced by RFCavity::initialise().
getInfo()
virtual void Fieldmap::getInfo (Inform * msg) pure virtual
Implemented in FM3DH5BlockBase, FM1DProfile1, Astra1DDynamic_fast, FM1DDynamic, FM1DDynamic_fast, FM1DElectroStatic, FM1DElectroStatic_fast, FM1DMagnetoStatic, FM1DMagnetoStatic_fast, FM2DDynamic, Astra1D_fast, Astra1DDynamic, Astra1DElectroStatic, Astra1DElectroStatic_fast, Astra1DMagnetoStatic, Astra1DMagnetoStatic_fast, FM1DProfile2, FM2DElectroStatic, FM2DMagnetoStatic, FM3DDynamic, FM3DMagnetoStatic, FM3DMagnetoStaticExtended, and FMDummy.
Referenced by Solenoid::initialise(), RBend3D::initialise(), RFCavity::initialise(), and Bend2D::readFieldMap().
getLine() [1/2]
void Fieldmap::getLine (std::ifstream & in, std::string & buffer) inline protected
Definition at line 121 of file Fieldmap.h.
References lines_read_m.
Referenced by interpretLine(), readHeader(), FM3DMagnetoStatic::readMap(), FM3DMagnetoStaticExtended::readMap(), Astra1DElectroStatic::readMap(), Astra1DMagnetoStatic::readMap(), FM2DElectroStatic::readMap(), FM2DMagnetoStatic::readMap(), Astra1DDynamic::readMap(), FM3DDynamic::readMap(), FM2DDynamic::readMap(), FM1DElectroStatic::stripFileHeader(), FM1DMagnetoStatic::stripFileHeader(), FM1DDynamic::stripFileHeader(), FM1DElectroStatic_fast::stripFileHeader(), FM1DMagnetoStatic_fast::stripFileHeader(), and FM1DDynamic_fast::stripFileHeader().
getLine() [2/2]
void Fieldmap::getLine (std::ifstream & in, int & lines_read, std::string & buffer) static protected
Definition at line 536 of file Fieldmap.cpp.
References alpha_numeric, buffer_m, and READ_BUFFER_LENGTH.
getListFieldmapNames()
std::vector< std::string > Fieldmap::getListFieldmapNames () static
Definition at line 263 of file Fieldmap.cpp.
References FieldmapDictionary.
getOnaxisEz()
void Fieldmap::getOnaxisEz (std::vector< std::pair< double, double > > & onaxis) virtual
Reimplemented in FM3DH5BlockBase, Astra1DDynamic_fast, FM2DDynamic, Astra1D_fast, Astra1DDynamic, and FM3DDynamic.
Definition at line 709 of file Fieldmap.cpp.
Referenced by TravelingWave::getAutoPhaseEstimate(), and RFCavity::getAutoPhaseEstimate().
getType()
MapType Fieldmap::getType () inline
Definition at line 97 of file Fieldmap.h.
References Type.
interpreteEOF()
bool Fieldmap::interpreteEOF (std::ifstream & in) protected
Definition at line 558 of file Fieldmap.cpp.
References alpha_numeric, buffer_m, exceedingValuesWarning(), lines_read_m, and READ_BUFFER_LENGTH.
Referenced by FM1DElectroStatic::checkFileData(), FM1DElectroStatic_fast::checkFileData(), FM1DMagnetoStatic::checkFileData(), FM1DMagnetoStatic_fast::checkFileData(), FM1DDynamic_fast::checkFileData(), FM1DDynamic::checkFileData(), FM1DProfile1::FM1DProfile1(), FM1DProfile2::FM1DProfile2(), FM2DDynamic::FM2DDynamic(), FM2DElectroStatic::FM2DElectroStatic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), FM3DDynamic::FM3DDynamic(), FM3DMagnetoStatic::FM3DMagnetoStatic(), and FM3DMagnetoStaticExtended::FM3DMagnetoStaticExtended().
interpretLine() [1/6]
template<class T > bool Fieldmap::interpretLine (std::ifstream & in, T & value, const bool & file_length_known)
Definition at line 12 of file Fieldmap.hpp.
References getLine(), interpretWarning(), and missingValuesWarning().
interpretLine() [2/6]
template<class S > bool Fieldmap::interpretLine (std::ifstream & in, S & value, const bool & file_length_known = true) protected
interpretLine() [3/6]
template<class S , class T > bool Fieldmap::interpretLine (std::ifstream & in, S & value1, T & value2, const bool & file_length_known = true) protected
Definition at line 39 of file Fieldmap.hpp.
References getLine(), interpretWarning(), and missingValuesWarning().
interpretLine() [4/6]
template<class S , class T , class U > bool Fieldmap::interpretLine (std::ifstream & in, S & value1, T & value2, U & value3, const bool & file_length_known = true) protected
Definition at line 70 of file Fieldmap.hpp.
References getLine(), interpretWarning(), and missingValuesWarning().
interpretLine() [5/6]
template<class S , class T , class U , class V > bool Fieldmap::interpretLine (std::ifstream & in, S & value1, T & value2, U & value3, V & value4, const bool & file_length_known = true) protected
Definition at line 104 of file Fieldmap.hpp.
References getLine(), interpretWarning(), and missingValuesWarning().
interpretLine() [6/6]
template<class S > bool Fieldmap::interpretLine (std::ifstream & in, S & value1, S & value2, S & value3, S & value4, S & value5, S & value6, const bool & file_length_known = true) protected
Definition at line 141 of file Fieldmap.hpp.
References getLine(), interpretWarning(), and missingValuesWarning().
interpretWarning()
void Fieldmap::interpretWarning (const std::ios_base::iostate & state, const bool & read_all, const std::string & error_msg, const std::string & found) protected
Definition at line 574 of file Fieldmap.cpp.
References endl(), Filename_m, and lines_read_m.
Referenced by interpretLine().
isInside()
virtual bool Fieldmap::isInside (const Vector_t &) const inline virtual
Reimplemented in FM3DH5BlockBase, FM1DDynamic, FM1DDynamic_fast, FM1DElectroStatic, FM1DElectroStatic_fast, FM1DMagnetoStatic, FM1DMagnetoStatic_fast, FM2DDynamic, Astra1D_fast, Astra1DDynamic, FM3DDynamic, Astra1DElectroStatic, Astra1DMagnetoStatic, FM2DElectroStatic, FM2DMagnetoStatic, FM3DMagnetoStatic, and FM3DMagnetoStaticExtended.
Definition at line 101 of file Fieldmap.h.
Referenced by TravelingWave::apply(), TravelingWave::applyToReferenceParticle(), Solenoid::isInside(), RBend3D::isInside(), and RFCavity::isInside().
lowResolutionWarning()
void Fieldmap::lowResolutionWarning (double squareError, double maxError) protected
Definition at line 629 of file Fieldmap.cpp.
References endl(), ERRORMSG, Filename_m, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), IpplInfo::myNode(), and typeset_msg().
Referenced by checkMap().
missingValuesWarning()
void Fieldmap::missingValuesWarning () protected
Definition at line 593 of file Fieldmap.cpp.
References Filename_m, and lines_read_m.
Referenced by interpretLine().
noFieldmapWarning()
void Fieldmap::noFieldmapWarning () protected
Definition at line 621 of file Fieldmap.cpp.
References Filename_m.
Referenced by Astra1DDynamic::Astra1DDynamic(), Astra1DDynamic_fast::Astra1DDynamic_fast(), Astra1DElectroStatic::Astra1DElectroStatic(), Astra1DElectroStatic_fast::Astra1DElectroStatic_fast(), Astra1DMagnetoStatic::Astra1DMagnetoStatic(), Astra1DMagnetoStatic_fast::Astra1DMagnetoStatic_fast(), FM1DDynamic::FM1DDynamic(), FM1DDynamic_fast::FM1DDynamic_fast(), FM1DElectroStatic::FM1DElectroStatic(), FM1DElectroStatic_fast::FM1DElectroStatic_fast(), FM1DMagnetoStatic::FM1DMagnetoStatic(), FM1DMagnetoStatic_fast::FM1DMagnetoStatic_fast(), FM1DProfile1::FM1DProfile1(), FM1DProfile2::FM1DProfile2(), FM2DDynamic::FM2DDynamic(), FM2DElectroStatic::FM2DElectroStatic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), and FM3DDynamic::FM3DDynamic().
readHeader()
MapType Fieldmap::readHeader (std::string Filename) static
Definition at line 284 of file Fieldmap.cpp.
References endl(), IpplInfo::getComm(), getLine(), lines_read_m, name, PAssert, T1DDynamic, T1DElectroStatic, T1DMagnetoStatic, T1DProfile1, T2DDynamic, T2DElectroStatic, T2DMagnetoStatic, T3DDynamic, T3DDynamicH5Block, T3DElectroStatic, T3DMagnetoStatic, T3DMagnetoStatic_Extended, T3DMagnetoStaticH5Block, TAstraDynamic, TAstraElectroStatic, TAstraMagnetoStatic, and UNKNOWN.
Referenced by getFieldmap().
readMap() [1/2]
void Fieldmap::readMap (std::string Filename) static
Definition at line 424 of file Fieldmap.cpp.
References FieldmapDictionary.
Referenced by Cyclotron::getFieldFromFile_BandRF(), and Cyclotron::getFieldFromFile_Synchrocyclotron().
readMap() [2/2]
virtual void Fieldmap::readMap () pure virtual
Implemented in FM1DProfile1, Astra1DDynamic_fast, FM3DH5Block, FM3DH5Block_nonscale, FM3DMagnetoStaticH5Block, FM3DH5BlockBase, FM1DDynamic, FM1DDynamic_fast, FM1DElectroStatic, FM1DElectroStatic_fast, FM1DMagnetoStatic, FM1DMagnetoStatic_fast, FM2DDynamic, Astra1D_fast, Astra1DDynamic, FM1DProfile2, FM3DDynamic, Astra1DElectroStatic, Astra1DMagnetoStatic, FM2DElectroStatic, FM2DMagnetoStatic, FM3DMagnetoStatic, FM3DMagnetoStaticExtended, Astra1DElectroStatic_fast, Astra1DMagnetoStatic_fast, and FMDummy.
Referenced by Solenoid::goOnline(), TravelingWave::goOnline(), RBend3D::goOnline(), RFCavity::goOnline(), and Bend2D::readFieldMap().
setEdgeConstants()
void Fieldmap::setEdgeConstants (const double & bendAngle, const double & entranceAngle, const double & exitAngle) virtual
Reimplemented in FM1DProfile2.
Definition at line 530 of file Fieldmap.cpp.
setFieldGap()
void Fieldmap::setFieldGap (double gap) virtual
Reimplemented in FM1DProfile1.
Definition at line 733 of file Fieldmap.cpp.
setFieldLength()
void Fieldmap::setFieldLength (const double &) virtual
Definition at line 533 of file Fieldmap.cpp.
setFrequency()
virtual void Fieldmap::setFrequency (double freq) pure virtual
Implemented in FM3DH5BlockBase, FM1DProfile1, Astra1DDynamic_fast, FM1DDynamic, FM1DDynamic_fast, FM1DElectroStatic, FM1DElectroStatic_fast, FM1DMagnetoStatic, FM1DMagnetoStatic_fast, FM2DDynamic, Astra1D_fast, Astra1DDynamic, Astra1DElectroStatic, Astra1DElectroStatic_fast, Astra1DMagnetoStatic, Astra1DMagnetoStatic_fast, FM1DProfile2, FM2DElectroStatic, FM2DMagnetoStatic, FM3DDynamic, FM3DMagnetoStatic, FM3DMagnetoStaticExtended, and FMDummy.
swap()
virtual void Fieldmap::swap () pure virtual
Implemented in FM3DH5BlockBase, FM1DProfile1, Astra1DDynamic_fast, FM1DDynamic, FM1DDynamic_fast, FM1DElectroStatic, FM1DElectroStatic_fast, FM1DMagnetoStatic, FM1DMagnetoStatic_fast, FM2DDynamic, Astra1D_fast, Astra1DDynamic, Astra1DElectroStatic, Astra1DElectroStatic_fast, Astra1DMagnetoStatic, Astra1DMagnetoStatic_fast, FM1DProfile2, FM2DElectroStatic, FM2DMagnetoStatic, FM3DDynamic, FM3DMagnetoStatic, FM3DMagnetoStaticExtended, and FMDummy.
typeset_msg()
std::string Fieldmap::typeset_msg (const std::string & msg, const std::string & title) static
Definition at line 652 of file Fieldmap.cpp.
References Physics::c.
Referenced by FMDummy::FMDummy(), FM2DElectroStatic::freeMap(), FM2DMagnetoStatic::freeMap(), FM3DMagnetoStatic::freeMap(), FM3DMagnetoStaticExtended::freeMap(), Astra1DElectroStatic::freeMap(), Astra1DMagnetoStatic::freeMap(), Astra1D_fast::freeMap(), FM3DDynamic::freeMap(), Astra1DDynamic::freeMap(), FM1DProfile2::freeMap(), FM1DElectroStatic::freeMap(), FM1DElectroStatic_fast::freeMap(), FM1DMagnetoStatic::freeMap(), FM1DMagnetoStatic_fast::freeMap(), FM2DDynamic::freeMap(), FM1DDynamic::freeMap(), FM1DDynamic_fast::freeMap(), FM3DH5Block::freeMap(), FM3DH5Block_nonscale::freeMap(), FM3DMagnetoStaticH5Block::freeMap(), RFCavity::initialise(), lowResolutionWarning(), CCollimator::print(), FlexibleCollimator::print(), Astra1DElectroStatic_fast::readMap(), Astra1DMagnetoStatic_fast::readMap(), FM2DElectroStatic::readMap(), Astra1DElectroStatic::readMap(), Astra1DMagnetoStatic::readMap(), FM3DMagnetoStatic::readMap(), FM3DMagnetoStaticExtended::readMap(), FM2DMagnetoStatic::readMap(), FM3DDynamic::readMap(), Astra1DDynamic::readMap(), FM1DProfile2::readMap(), FM1DElectroStatic_fast::readMap(), FM1DMagnetoStatic_fast::readMap(), FM1DMagnetoStatic::readMap(), FM1DElectroStatic::readMap(), FM2DDynamic::readMap(), FM1DDynamic::readMap(), FM1DDynamic_fast::readMap(), FM3DH5Block::readMap(), FM3DMagnetoStaticH5Block::readMap(), FM3DH5Block_nonscale::readMap(), Astra1DDynamic_fast::readMap(), and FM1DProfile1::readMap().
write3DField()
void Fieldmap::write3DField (unsigned int nx, unsigned int ny, unsigned int nz, const std::pair< double, double > & xrange, const std::pair< double, double > & yrange, const std::pair< double, double > & zrange, const std::vector< Vector_t > & ef, const std::vector< Vector_t > & bf) protected
Definition at line 737 of file Fieldmap.cpp.
References Util::combineFilePath(), endl(), Filename_m, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), IpplInfo::myNode(), and PAssert.
Referenced by FM3DDynamic::readMap().
Member Data Documentation
alpha_numeric
std::string Fieldmap::alpha_numeric static private
Definition at line 182 of file Fieldmap.h.
Referenced by getLine(), and interpreteEOF().
buffer_m
char Fieldmap::buffer_m static private
Definition at line 181 of file Fieldmap.h.
Referenced by getLine(), and interpreteEOF().
FieldmapDictionary
std::map< std::string, Fieldmap::FieldmapDescription > Fieldmap::FieldmapDictionary = std::map<std::string, Fieldmap::FieldmapDescription>() static private
Definition at line 197 of file Fieldmap.h.
Referenced by clearDictionary(), freeMap(), getFieldmap(), getListFieldmapNames(), and readMap().
Filename_m
std::string Fieldmap::Filename_m protected
Definition at line 117 of file Fieldmap.h.
Referenced by Astra1DDynamic::Astra1DDynamic(), Astra1DDynamic_fast::Astra1DDynamic_fast(), Astra1DElectroStatic::Astra1DElectroStatic(), Astra1DElectroStatic_fast::Astra1DElectroStatic_fast(), Astra1DMagnetoStatic::Astra1DMagnetoStatic(), Astra1DMagnetoStatic_fast::Astra1DMagnetoStatic_fast(), checkMap(), FM3DH5BlockBase::closeFile(), disableFieldmapWarning(), exceedingValuesWarning(), FM1DDynamic::FM1DDynamic(), FM1DDynamic_fast::FM1DDynamic_fast(), FM1DElectroStatic::FM1DElectroStatic(), FM1DElectroStatic_fast::FM1DElectroStatic_fast(), FM1DMagnetoStatic::FM1DMagnetoStatic(), FM1DMagnetoStatic_fast::FM1DMagnetoStatic_fast(), FM1DProfile1::FM1DProfile1(), FM1DProfile2::FM1DProfile2(), FM2DDynamic::FM2DDynamic(), FM2DElectroStatic::FM2DElectroStatic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), FM3DDynamic::FM3DDynamic(), FM3DMagnetoStatic::FM3DMagnetoStatic(), FM3DMagnetoStaticExtended::FM3DMagnetoStaticExtended(), FMDummy::FMDummy(), FM2DElectroStatic::freeMap(), FM2DMagnetoStatic::freeMap(), Astra1DMagnetoStatic::freeMap(), FM3DMagnetoStatic::freeMap(), Astra1DElectroStatic::freeMap(), FM3DMagnetoStaticExtended::freeMap(), FM1DProfile2::freeMap(), Astra1DDynamic::freeMap(), FM3DDynamic::freeMap(), Astra1D_fast::freeMap(), FM2DDynamic::freeMap(), FM1DElectroStatic::freeMap(), FM1DElectroStatic_fast::freeMap(), FM1DMagnetoStatic::freeMap(), FM1DMagnetoStatic_fast::freeMap(), FM1DDynamic::freeMap(), FM1DDynamic_fast::freeMap(), FM3DH5Block::freeMap(), FM3DH5Block_nonscale::freeMap(), FM3DMagnetoStaticH5Block::freeMap(), FM3DH5BlockBase::getFieldInfo(), Astra1DElectroStatic_fast::getInfo(), FM1DProfile2::getInfo(), Astra1DMagnetoStatic_fast::getInfo(), Astra1DMagnetoStatic::getInfo(), FM2DElectroStatic::getInfo(), FM2DMagnetoStatic::getInfo(), FM3DDynamic::getInfo(), Astra1DDynamic::getInfo(), FM3DMagnetoStaticExtended::getInfo(), FM3DMagnetoStatic::getInfo(), Astra1DElectroStatic::getInfo(), FM2DDynamic::getInfo(), FM1DDynamic::getInfo(), FM1DDynamic_fast::getInfo(), FM1DElectroStatic::getInfo(), FM1DElectroStatic_fast::getInfo(), FM1DMagnetoStatic::getInfo(), FM1DMagnetoStatic_fast::getInfo(), Astra1DDynamic_fast::getInfo(), FM1DProfile1::getInfo(), FM3DH5BlockBase::getInfo(), FM3DH5BlockBase::getNumSteps(), FM3DDynamic::getOnaxisEz(), Astra1DDynamic::getOnaxisEz(), FM1DDynamic::getOnaxisEz(), FM1DDynamic_fast::getOnaxisEz(), Astra1DDynamic_fast::getOnaxisEz(), FM3DH5BlockBase::getResonanceFrequency(), interpretWarning(), lowResolutionWarning(), missingValuesWarning(), noFieldmapWarning(), FM3DH5BlockBase::readField(), Astra1DMagnetoStatic_fast::readMap(), Astra1DElectroStatic_fast::readMap(), Astra1DMagnetoStatic::readMap(), FM2DElectroStatic::readMap(), Astra1DElectroStatic::readMap(), FM2DMagnetoStatic::readMap(), FM3DMagnetoStaticExtended::readMap(), FM3DMagnetoStatic::readMap(), Astra1DDynamic::readMap(), FM1DProfile2::readMap(), FM3DDynamic::readMap(), FM1DMagnetoStatic::readMap(), FM1DMagnetoStatic_fast::readMap(), FM1DElectroStatic_fast::readMap(), FM1DElectroStatic::readMap(), FM2DDynamic::readMap(), FM1DDynamic_fast::readMap(), FM1DDynamic::readMap(), FM3DH5Block_nonscale::readMap(), FM3DH5Block::readMap(), FM3DMagnetoStaticH5Block::readMap(), Astra1DDynamic_fast::readMap(), FM1DProfile1::readMap(), FM3DH5BlockBase::setStep(), and write3DField().
lines_read_m
int Fieldmap::lines_read_m protected
Definition at line 118 of file Fieldmap.h.
Referenced by Astra1DDynamic::Astra1DDynamic(), Astra1DElectroStatic::Astra1DElectroStatic(), Astra1DMagnetoStatic::Astra1DMagnetoStatic(), Astra1D_fast::determineNumSamplingPoints(), exceedingValuesWarning(), FM1DProfile2::FM1DProfile2(), FM2DDynamic::FM2DDynamic(), FM2DElectroStatic::FM2DElectroStatic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), FM3DMagnetoStaticExtended::FM3DMagnetoStaticExtended(), getLine(), interpreteEOF(), interpretWarning(), missingValuesWarning(), and readHeader().
normalize_m
bool Fieldmap::normalize_m protected
Definition at line 120 of file Fieldmap.h.
Referenced by Astra1D_fast::Astra1D_fast(), Astra1DDynamic::Astra1DDynamic(), Astra1DElectroStatic::Astra1DElectroStatic(), Astra1DMagnetoStatic::Astra1DMagnetoStatic(), FM2DDynamic::FM2DDynamic(), FM2DElectroStatic::FM2DElectroStatic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), FM3DMagnetoStatic::FM3DMagnetoStatic(), FM3DMagnetoStaticExtended::FM3DMagnetoStaticExtended(), FM1DMagnetoStatic_fast::normalizeField(), Astra1D_fast::readFieldData(), FM1DElectroStatic::readFileData(), FM1DMagnetoStatic::readFileData(), FM1DDynamic::readFileData(), FM1DElectroStatic_fast::readFileData(), FM1DDynamic_fast::readFileData(), Astra1DElectroStatic_fast::readFileHeader(), Astra1DMagnetoStatic_fast::readFileHeader(), FM1DElectroStatic::readFileHeader(), FM1DMagnetoStatic::readFileHeader(), FM1DDynamic::readFileHeader(), FM1DElectroStatic_fast::readFileHeader(), FM1DMagnetoStatic_fast::readFileHeader(), FM1DDynamic_fast::readFileHeader(), Astra1DDynamic_fast::readFileHeader(), Astra1DMagnetoStatic::readMap(), FM3DMagnetoStatic::readMap(), Astra1DElectroStatic::readMap(), FM2DElectroStatic::readMap(), FM3DMagnetoStaticExtended::readMap(), FM2DMagnetoStatic::readMap(), Astra1DDynamic::readMap(), FM2DDynamic::readMap(), and FM1DDynamic_fast::scaleField().
Type
MapType Fieldmap::Type protected
Definition at line 114 of file Fieldmap.h.
Referenced by Astra1DDynamic::Astra1DDynamic(), Astra1DDynamic_fast::Astra1DDynamic_fast(), Astra1DElectroStatic::Astra1DElectroStatic(), Astra1DElectroStatic_fast::Astra1DElectroStatic_fast(), Astra1DMagnetoStatic::Astra1DMagnetoStatic(), Astra1DMagnetoStatic_fast::Astra1DMagnetoStatic_fast(), FM1DDynamic::FM1DDynamic(), FM1DDynamic_fast::FM1DDynamic_fast(), FM1DElectroStatic::FM1DElectroStatic(), FM1DElectroStatic_fast::FM1DElectroStatic_fast(), FM1DMagnetoStatic::FM1DMagnetoStatic(), FM1DMagnetoStatic_fast::FM1DMagnetoStatic_fast(), FM1DProfile1::FM1DProfile1(), FM1DProfile2::FM1DProfile2(), FM2DDynamic::FM2DDynamic(), FM2DElectroStatic::FM2DElectroStatic(), FM2DMagnetoStatic::FM2DMagnetoStatic(), FM3DDynamic::FM3DDynamic(), FM3DH5Block::FM3DH5Block(), FM3DH5Block_nonscale::FM3DH5Block_nonscale(), FM3DMagnetoStatic::FM3DMagnetoStatic(), FM3DMagnetoStaticExtended::FM3DMagnetoStaticExtended(), FM3DMagnetoStaticH5Block::FM3DMagnetoStaticH5Block(), and getType().
The documentation for this class was generated from the following files:
src/Classic/Fields/Fieldmap.h
src/Classic/Fields/Fieldmap.cpp
src/Classic/Fields/Fieldmap.hpp