OPAL (Object Oriented Parallel Accelerator Library): BorisPusher Class Reference
BorisPusher Class Reference
#include <BorisPusher.h>
Public Member Functions
BorisPusher (const PartData &ref)
BorisPusher ()
void initialise (const PartData *ref)
void kick (const Vector_t &R, Vector_t &P, const Vector_t &Ef, const Vector_t &Bf, const double &dt) const
void kick (const Vector_t &R, Vector_t &P, const Vector_t &Ef, const Vector_t &Bf, const double &dt, const double &mass, const double &charge) const
void push (Vector_t &R, const Vector_t &P, const double &dt) const
Private Attributes
const PartData * itsReference
Detailed Description
Definition at line 30 of file BorisPusher.h.
Constructor & Destructor Documentation
BorisPusher() [1/2]
BorisPusher::BorisPusher (const PartData & ref) inline
Definition at line 52 of file BorisPusher.h.
BorisPusher() [2/2]
BorisPusher::BorisPusher () inline
Definition at line 56 of file BorisPusher.h.
Member Function Documentation
initialise()
void BorisPusher::initialise (const PartData * ref) inline
Definition at line 60 of file BorisPusher.h.
References itsReference, and Hypervolume::ref.
Referenced by Bend2D::setupPusher().
kick() [1/2]
void BorisPusher::kick (const Vector_t & R, Vector_t & P, const Vector_t & Ef, const Vector_t & Bf, const double & dt) const inline
Definition at line 65 of file BorisPusher.h.
References PartData::getM(), PartData::getQ(), itsReference, and Attrib::Distribution::R.
Referenced by Bend2D::calculateBendAngle(), Bend2D::calculateRefTrajectory(), OrbitThreader::integrate(), ParallelCyclotronTracker::kick(), LF2< FieldFunction, Arguments >::kick_m(), ParallelTTracker::kickParticles(), and ParallelTTracker::updateReferenceParticle().
kick() [2/2]
void BorisPusher::kick (const Vector_t & R, Vector_t & P, const Vector_t & Ef, const Vector_t & Bf, const double & dt, const double & mass, const double & charge) const inline
Definition at line 73 of file BorisPusher.h.
References Physics::c, cross(), dot(), and sqrt().
push()
void BorisPusher::push (Vector_t & R, const Vector_t & P, const double & dt) const inline
\[ \vec{x}_{n+1/2} = \vec{x}_{n} + \frac{1}{2}\vec{v}_{n-1/2}\quad (= \vec{x}_{n} + \frac{\Delta t}{2} \frac{\vec{\beta}_{n-1/2}\gamma_{n-1/2}}{\gamma_{n-1/2}}) \]
R[i] += 0.5 * P[i] * recpgamma;
Definition at line 131 of file BorisPusher.h.
References dot(), Attrib::Distribution::R, and sqrt().
Referenced by ParallelTTracker::applyFractionalStep(), ParallelTTracker::autophaseCavities(), Bend2D::calculateBendAngle(), Bend2D::calculateRefTrajectory(), OrbitThreader::execute(), OrbitThreader::integrate(), ParallelTTracker::pushParticles(), OrbitThreader::trackBack(), and ParallelTTracker::updateReferenceParticle().
Member Data Documentation
itsReference
const PartData* BorisPusher::itsReference private
Definition at line 49 of file BorisPusher.h.
Referenced by initialise(), and kick().
The documentation for this class was generated from the following file:
/psi/home/gsell/data/src/OPAL/src/src/Steppers/BorisPusher.h