OPAL (Object Oriented Parallel Accelerator Library): DumpFields Class Reference
DumpFields Class Reference
#include <DumpFields.h>
Public Types
enum {
FILE_NAME, X_START, DX, X_STEPS,
Y_START, DY, Y_STEPS, Z_START,
DZ, Z_STEPS, SIZE
}
The common attributes of DumpFields.
Public Member Functions
DumpFields ()
DumpFields (const std::string &name, DumpFields *parent)
virtual ~DumpFields ()
virtual DumpFields * clone (const std::string &name)
virtual void execute ()
void print (std::ostream &os) const
Public Member Functions inherited from Action
virtual ~Action ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static void writeFields (Component *field)
Private Member Functions
virtual void writeFieldThis (Component *field)
virtual void buildGrid ()
DumpFields (const DumpFields &dump)
DumpFields & operator= (const DumpFields &dump)
Static Private Member Functions
static void checkInt (double value, std::string name, double tolerance=1e-9)
Private Attributes
interpolation::ThreeDGrid * grid_m = nullptr
std::string filename_m
Static Private Attributes
static std::unordered_set< DumpFields * > dumpsSet_m
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Action
Action (int size, const char *name, const char *help)
Constructor for exemplars.
Action (const std::string &name, Action *parent)
Constructor for cloning.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
DumpFields dumps the static magnetic field of a Ring in a user-defined grid
The idea is to print out the field map across a grid in space for debugging purposes. The problem is to manage the DumpFields object through three phases of program execution; initial construction, parsing and then actual field map writing (where we need to somehow let DumpFields know what the field maps are). So for each DumpFields object created, we store in a set. When the execute() method is called, DumpFields builds a grid using the parsed information.
When the ParallelCyclotronTracker is about to start tracking, it calls writeFields method which loops over the static set of DumpFields and writes each one. It is not the cleanest implementation, but I can't see a better way.
The DumpFields themselves operate by iterating over a ThreeDGrid object and looking up the field/writing it out on each grid point.
In order to dump time dependent fields, for example RF, see the DumpEMFields action.
Definition at line 54 of file DumpFields.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
The common attributes of DumpFields.
Enumerator
FILE_NAME
X_START
DX
X_STEPS
Y_START
DY
Y_STEPS
Z_START
DZ
Z_STEPS
SIZE
Definition at line 58 of file DumpFields.h.
Constructor & Destructor Documentation
DumpFields() [1/3]
DumpFields::DumpFields ()
Constructor
Definition at line 35 of file DumpFields.cpp.
References DX, DY, DZ, FILE_NAME, Object::itsAttr, Attributes::makeReal(), Attributes::makeString(), Object::registerOwnership(), AttributeHandler::STATEMENT, X_START, X_STEPS, Y_START, Y_STEPS, Z_START, and Z_STEPS.
Referenced by clone().
DumpFields() [2/3]
DumpFields::DumpFields (const std::string & name, DumpFields * parent)
Constructor
Definition at line 74 of file DumpFields.cpp.
~DumpFields()
DumpFields::~DumpFields () virtual
Destructor deletes grid_m and if in the dumps set, take it out
Definition at line 78 of file DumpFields.cpp.
References dumpsSet_m, and grid_m.
DumpFields() [3/3]
DumpFields::DumpFields (const DumpFields & dump) private
Member Function Documentation
buildGrid()
void DumpFields::buildGrid () private virtual
Definition at line 104 of file DumpFields.cpp.
References checkInt(), DX, DY, DZ, FILE_NAME, filename_m, Attributes::getReal(), Attributes::getString(), grid_m, Object::itsAttr, X_START, X_STEPS, Y_START, Y_STEPS, Z_START, and Z_STEPS.
Referenced by execute().
checkInt()
void DumpFields::checkInt (double value, std::string name, double tolerance = 1e-9) static private
Definition at line 136 of file DumpFields.cpp.
References abs(), floor(), name, and real().
Referenced by buildGrid().
clone()
DumpFields * DumpFields::clone (const std::string & name) virtual
Make a clone (overloadable copy-constructor).
Parameters
name not used If this is in the dumpsSet_m, so will the clone. Not sure how the itsAttr stuff works, so this may not get properly copied?
Implements Object.
Definition at line 83 of file DumpFields.cpp.
References interpolation::ThreeDGrid::clone(), DumpFields(), dumpsSet_m, filename_m, grid_m, and name.
Referenced by execute().
execute()
void DumpFields::execute () virtual
Builds the grid but does not write the field map
Builds a grid of points in x-y-z space using the ThreeDGrid algorithm. Checks that X_STEPS, Y_STEPS, Z_STEPS are integers or throws OpalException.
Reimplemented from Object.
Definition at line 95 of file DumpFields.cpp.
References buildGrid(), clone(), and dumpsSet_m.
operator=()
DumpFields& DumpFields::operator= (const DumpFields & dump) private
print()
void DumpFields::print (std::ostream & os) const virtual
Print the attributes of DumpFields to standard out
Reimplemented from Object.
Definition at line 204 of file DumpFields.cpp.
References DX, DY, DZ, endl(), filename_m, Attributes::getReal(), Object::itsAttr, X_START, X_STEPS, Y_START, Y_STEPS, Z_START, and Z_STEPS.
Referenced by operator<<().
writeFields()
void DumpFields::writeFields (Component * field) static
Write the fields for all defined DumpFields objects
Parameters
field borrowed reference to the Component object that holds the field map; caller owns the memory. Iterates over the DumpFields in the dumpsSet_m and calls writeFieldThis on each DumpFields. This writes each field map in turn. Format is: <number of="" rows>=""> <column 1> <units> <column 2> <units> <column 3> <units> <column 4> <units> <column 5> <units> <column 6> <units> 0 <field map="" data>="">
Definition at line 129 of file DumpFields.cpp.
References dumpsSet_m.
Referenced by ParallelCyclotronTracker::execute().
writeFieldThis()
void DumpFields::writeFieldThis (Component * field) private virtual
Definition at line 148 of file DumpFields.cpp.
References Component::apply(), interpolation::ThreeDGrid::begin(), Util::combineFilePath(), interpolation::ThreeDGrid::end(), endl(), filename_m, OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), gmsg, grid_m, and interpolation::Mesh::Iterator::toInteger().
Member Data Documentation
dumpsSet_m
std::unordered_set< DumpFields * > DumpFields::dumpsSet_m static private
Definition at line 125 of file DumpFields.h.
Referenced by clone(), execute(), writeFields(), and ~DumpFields().
filename_m
std::string DumpFields::filename_m private
Definition at line 123 of file DumpFields.h.
Referenced by buildGrid(), clone(), print(), and writeFieldThis().
grid_m
interpolation::ThreeDGrid* DumpFields::grid_m = nullptr private
Definition at line 121 of file DumpFields.h.
Referenced by buildGrid(), clone(), writeFieldThis(), and ~DumpFields().
The documentation for this class was generated from the following files:
src/BasicActions/DumpFields.h
src/BasicActions/DumpFields.cpp