OPAL (Object Oriented Parallel Accelerator Library): Option Class Reference
Option Class Reference
#include <Option.h>
Public Member Functions
Option ()
virtual ~Option ()
virtual Option * clone (const std::string &name)
Make clone.
virtual void execute ()
Execute the command.
Public Member Functions inherited from Action
virtual ~Action ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
void handlePsDumpFrame (const std::string &dumpFrame)
void update (const std::vector< Attribute > &)
Option (const Option &)
void operator= (const Option &)
Option (const std::string &name, Option *parent)
virtual void update ()
Update this object.
Static Private Member Functions
static std::string getDumpFrameString (const DumpFrame &df)
Static Private Attributes
static const boost::bimap< DumpFrame, std::string > bmDumpFrameString_s
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from Action
Action (int size, const char *name, const char *help)
Constructor for exemplars.
Action (const std::string &name, Action *parent)
Constructor for cloning.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 30 of file Option.h.
Constructor & Destructor Documentation
Option() [1/3]
Option::Option ()
Definition at line 104 of file Option.cpp.
References Options::amrRegridFreq, Options::amrYtDumpFreq, Options::asciidump, Options::autoPhase, Options::beamHaloBoundary, Options::boundpDestroyFreq, Options::cloTuneOnly, Options::computePercentiles, Options::csrDump, Options::cZero, Options::delPartFreq, Options::dumpBeamMatrix, Options::ebDump, Options::echo, Options::enableHDF5, Options::enableVTK, Options::haloShift, Options::idealized, Options::info, Object::itsAttr, Attributes::makeBool(), Attributes::makePredefinedString(), Attributes::makeReal(), Options::memoryDump, Options::minBinEmitted, Options::minStepForRebin, Options::mtrace, Options::psDumpEachTurn, Options::psDumpFreq, Options::rebinFreq, Object::registerOwnership(), Options::remotePartDel, Options::repartFreq, Options::rhoDump, Options::rngtype, FileStream::setEcho(), Options::sptDumpFreq, Options::statDumpFreq, AttributeHandler::STATEMENT, Options::version, Options::warn, and Options::writeBendTrajectories.
Referenced by clone().
~Option()
Option::~Option () virtual
Definition at line 356 of file Option.cpp.
Option() [2/3]
Option::Option (const Option &) private
Option() [3/3]
Option::Option (const std::string & name, Option * parent) private
Definition at line 306 of file Option.cpp.
References Options::amrRegridFreq, Options::amrYtDumpFreq, Options::asciidump, Options::autoPhase, Options::beamHaloBoundary, Options::boundpDestroyFreq, Options::cloTuneOnly, Options::computePercentiles, Options::csrDump, Options::cZero, Options::delPartFreq, Options::dumpBeamMatrix, Options::ebDump, Options::echo, Options::enableHDF5, Options::enableVTK, getDumpFrameString(), Options::haloShift, Options::idealized, Options::info, Object::itsAttr, Options::memoryDump, Options::minBinEmitted, Options::minStepForRebin, Options::mtrace, Options::mtsSubsteps, Options::nLHS, Options::numBlocks, Options::psDumpEachTurn, Options::psDumpFrame, Options::psDumpFreq, Options::rebinFreq, Options::recycleBlocks, Options::remotePartDel, Options::repartFreq, Options::rhoDump, Options::rngtype, Options::scSolveFreq, Options::seed, Attributes::setBool(), Attributes::setPredefinedString(), Attributes::setReal(), Options::sptDumpFreq, Options::statDumpFreq, Options::version, Options::warn, and Options::writeBendTrajectories.
Member Function Documentation
clone()
Option * Option::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 360 of file Option.cpp.
References name, and Option().
execute()
void Option::execute () virtual
Execute the command.
note: rangen is used only for the random number generator in the OPAL language not for the distributions
note: rangen is used only for the random number generator in the OPAL language not for the distributions
Reimplemented from Object.
Definition at line 365 of file Option.cpp.
References Options::amrRegridFreq, Options::amrYtDumpFreq, Options::asciidump, Options::autoPhase, Options::beamHaloBoundary, Options::cloTuneOnly, Options::computePercentiles, Options::csrDump, Options::cZero, Options::delPartFreq, Options::dumpBeamMatrix, Options::ebDump, Options::echo, Options::enableHDF5, Options::enableVTK, endl(), OpalData::find(), Attributes::getBool(), OpalData::getInstance(), IpplMemoryUsage::getInstance(), Attributes::getReal(), Attributes::getString(), gmsg, Options::haloShift, handlePsDumpFrame(), Options::idealized, Options::info, IpplInfo::Info, Random::init55(), Object::itsAttr, main(), max(), Options::memoryDump, Options::minBinEmitted, Options::minStepForRebin, Options::mtrace, Options::mtsSubsteps, Options::nLHS, Options::numBlocks, Inform::on(), Options::psDumpEachTurn, Options::psDumpFreq, Options::rangen, Options::rebinFreq, Options::recycleBlocks, Options::remotePartDel, Options::repartFreq, Options::rhoDump, Options::rngtype, IpplMemoryUsage::sample(), Options::scSolveFreq, Options::seed, FileStream::setEcho(), Options::sptDumpFreq, Options::statDumpFreq, Options::version, Options::warn, IpplInfo::Warn, and Options::writeBendTrajectories.
getDumpFrameString()
std::string Option::getDumpFrameString (const DumpFrame & df) static private
Definition at line 527 of file Option.cpp.
References bmDumpFrameString_s.
Referenced by Option().
handlePsDumpFrame()
void Option::handlePsDumpFrame (const std::string & dumpFrame) private
Definition at line 523 of file Option.cpp.
References bmDumpFrameString_s, and Options::psDumpFrame.
Referenced by execute().
operator=()
void Option::operator= (const Option &) private
update() [1/2]
void Object::update private
Update this object.
Definition at line 263 of file Object.cpp.
update() [2/2]
void Option::update (const std::vector< Attribute > & othersAttributes) private
Definition at line 531 of file Option.cpp.
References Object::itsAttr, and SIZE.
Member Data Documentation
bmDumpFrameString_s
const boost::bimap< DumpFrame, std::string > Option::bmDumpFrameString_s static private
Initial value:
=
    boost::assign::list_of<const boost::bimap<DumpFrame, std::string>::relation>
        (DumpFrame::GLOBAL,     "GLOBAL")
        (DumpFrame::BUNCH_MEAN, "BUNCH_MEAN")
        (DumpFrame::REFERENCE,  "REFERENCE")
Definition at line 59 of file Option.h.
Referenced by getDumpFrameString(), and handlePsDumpFrame().
The documentation for this class was generated from the following files:
src/BasicActions/Option.h
src/BasicActions/Option.cpp