OPAL (Object Oriented Parallel Accelerator Library): CSRWakeFunction Class Reference
CSRWakeFunction Class Reference
#include <CSRWakeFunction.h>
Public Member Functions
CSRWakeFunction (const std::string &name, std::vector< Filter *> filters, const unsigned int &N)
void apply (PartBunchBase< double, 3 > *bunch) override
void initialize (const ElementBase *ref) override
virtual WakeType getType () const override
Public Member Functions inherited from WakeFunction
WakeFunction (std::string name, unsigned int n)
virtual ~WakeFunction ()
const std::string & getName () const
Private Member Functions
void calculateLineDensity (PartBunchBase< double, 3 > *bunch, std::pair< double, double > &meshInfo)
void calculateContributionInside (size_t sliceNumber, double angleOfSlice, double meshSpacing)
void calculateContributionAfter (size_t sliceNumber, double angleOfSlice, double meshSpacing)
double calcPsi (const double &psiInitial, const double &x, const double &Ds) const
Private Attributes
std::vector< Filter * > filters_m
std::shared_ptr< Filter > defaultFilter_m
Filter * diffOp_m
LineDensity lineDensity_m
LineDensity dlineDensitydz_m
std::vector< double > Ez_m
std::vector< double > Psi_m
double Begin_m
double FieldBegin_m
double Length_m
double bendRadius_m
std::string bendName_m
double totalBendAngle_m
Additional Inherited Members
Protected Attributes inherited from WakeFunction
const unsigned int nBins_m
Detailed Description
Definition at line 29 of file CSRWakeFunction.h.
Constructor & Destructor Documentation
CSRWakeFunction()
CSRWakeFunction::CSRWakeFunction (const std::string & name, std::vector< Filter *> filters, const unsigned int & N)
Definition at line 34 of file CSRWakeFunction.cpp.
References defaultFilter_m, diffOp_m, and filters_m.
Member Function Documentation
apply()
void CSRWakeFunction::apply (PartBunchBase< double, 3 > * bunch) override virtual
Implements WakeFunction.
Definition at line 52 of file CSRWakeFunction.cpp.
References bendName_m, bendRadius_m, calculateContributionAfter(), calculateContributionInside(), calculateLineDensity(), Util::combineFilePath(), Options::csrDump, dlineDensitydz_m, PartBunchBase< T, Dim >::Ef, endl(), Physics::epsilon_0, Ez_m, FieldBegin_m, floor(), PartBunchBase< T, Dim >::get_bounds(), PartBunchBase< T, Dim >::get_sPos(), OpalData::getAuxiliaryOutputDirectory(), OpalData::getInstance(), PartBunchBase< T, Dim >::getLocalNum(), lineDensity_m, IpplInfo::myNode(), PAssert_LT, Physics::pi, Psi_m, Attrib::Distribution::R, and PartBunchBase< T, Dim >::R.
calcPsi()
double CSRWakeFunction::calcPsi (const double & psiInitial, const double & x, const double & Ds) const private
solve the equation
\[ \Delta s = \frac{R \Psi^3}{24} \frac{\Psi + 4x}{\Psi + x} \]
for \(\Psi\) using Newtons method.
Definition at line 309 of file CSRWakeFunction.cpp.
References abs(), bendRadius_m, Physics::e, endl(), ERRORMSG, RootFinderForCSR::hasPositiveRealRoots(), pow(), and RootFinderForCSR::searchRoot().
Referenced by calculateContributionAfter().
calculateContributionAfter()
void CSRWakeFunction::calculateContributionAfter (size_t sliceNumber, double angleOfSlice, double meshSpacing) private
Definition at line 252 of file CSRWakeFunction.cpp.
References bendRadius_m, calcPsi(), dlineDensitydz_m, Ez_m, floor(), lineDensity_m, pow(), Psi_m, and totalBendAngle_m.
Referenced by apply().
calculateContributionInside()
void CSRWakeFunction::calculateContributionInside (size_t sliceNumber, double angleOfSlice, double meshSpacing) private
Definition at line 166 of file CSRWakeFunction.cpp.
References bendRadius_m, dlineDensitydz_m, Ez_m, floor(), lineDensity_m, pow(), and totalBendAngle_m.
Referenced by apply().
calculateLineDensity()
void CSRWakeFunction::calculateLineDensity (PartBunchBase< double, 3 > * bunch, std::pair< double, double > & meshInfo) private
Definition at line 153 of file CSRWakeFunction.cpp.
References Filter::calc_derivative(), PartBunchBase< T, Dim >::calcLineDensity(), diffOp_m, dlineDensitydz_m, filters_m, lineDensity_m, and WakeFunction::nBins_m.
Referenced by apply().
getType()
WakeType CSRWakeFunction::getType () const override virtual
Implements WakeFunction.
Definition at line 340 of file CSRWakeFunction.cpp.
References CSRWakeFunction.
initialize()
void CSRWakeFunction::initialize (const ElementBase * ref) override virtual
Reimplemented from WakeFunction.
Definition at line 137 of file CSRWakeFunction.cpp.
References abs(), Begin_m, bendName_m, bendRadius_m, FieldBegin_m, BendBase::getBendAngle(), Bend2D::getBendRadius(), Bend2D::getDimensions(), Bend2D::getEffectiveCenter(), Bend2D::getEffectiveLength(), ElementBase::getName(), Length_m, RBEND, Hypervolume::ref, SBEND, and totalBendAngle_m.
Member Data Documentation
Begin_m
double CSRWakeFunction::Begin_m private
Definition at line 60 of file CSRWakeFunction.h.
Referenced by initialize().
bendName_m
std::string CSRWakeFunction::bendName_m private
Definition at line 72 of file CSRWakeFunction.h.
Referenced by apply(), and initialize().
bendRadius_m
double CSRWakeFunction::bendRadius_m private
Definition at line 70 of file CSRWakeFunction.h.
Referenced by apply(), calcPsi(), calculateContributionAfter(), calculateContributionInside(), and initialize().
defaultFilter_m
std::shared_ptr<Filter> CSRWakeFunction::defaultFilter_m private
Definition at line 47 of file CSRWakeFunction.h.
Referenced by CSRWakeFunction().
diffOp_m
Filter* CSRWakeFunction::diffOp_m private
Definition at line 48 of file CSRWakeFunction.h.
Referenced by calculateLineDensity(), and CSRWakeFunction().
dlineDensitydz_m
LineDensity CSRWakeFunction::dlineDensitydz_m private
Definition at line 51 of file CSRWakeFunction.h.
Referenced by apply(), calculateContributionAfter(), calculateContributionInside(), and calculateLineDensity().
Ez_m
std::vector<double> CSRWakeFunction::Ez_m private
Definition at line 54 of file CSRWakeFunction.h.
Referenced by apply(), calculateContributionAfter(), and calculateContributionInside().
FieldBegin_m
double CSRWakeFunction::FieldBegin_m private
Definition at line 64 of file CSRWakeFunction.h.
Referenced by apply(), and initialize().
filters_m
std::vector<Filter*> CSRWakeFunction::filters_m private
Definition at line 46 of file CSRWakeFunction.h.
Referenced by calculateLineDensity(), and CSRWakeFunction().
Length_m
double CSRWakeFunction::Length_m private
Definition at line 67 of file CSRWakeFunction.h.
Referenced by initialize().
lineDensity_m
LineDensity CSRWakeFunction::lineDensity_m private
Definition at line 50 of file CSRWakeFunction.h.
Referenced by apply(), calculateContributionAfter(), calculateContributionInside(), and calculateLineDensity().
Psi_m
std::vector<double> CSRWakeFunction::Psi_m private
Definition at line 57 of file CSRWakeFunction.h.
Referenced by apply(), and calculateContributionAfter().
totalBendAngle_m
double CSRWakeFunction::totalBendAngle_m private
Definition at line 74 of file CSRWakeFunction.h.
Referenced by calculateContributionAfter(), calculateContributionInside(), and initialize().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Solvers/CSRWakeFunction.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Solvers/CSRWakeFunction.cpp