OPAL (Object Oriented Parallel Accelerator Library): ProbeHistReader Class Reference
ProbeHistReader Class Reference
#include <ProbeHistReader.h>
Public Types
typedef std::vector< size_t > container_t
Public Member Functions
ProbeHistReader (std::string filename)
void parseFile ()
size_t minimum (double lower, double upper)
Private Member Functions
void parseHeader (std::ifstream &ifs)
template<typename T >
T getValue (const std::string &s)
Private Attributes
std::string filename_m
Histogram file.
double rmin_m
double binwidth_m
container_t bincount_m
Detailed Description
Definition at line 31 of file ProbeHistReader.h.
Member Typedef Documentation
container_t
typedef std::vector<size_t> ProbeHistReader::container_t
Definition at line 34 of file ProbeHistReader.h.
Constructor & Destructor Documentation
ProbeHistReader()
ProbeHistReader::ProbeHistReader (std::string filename)
Definition at line 29 of file ProbeHistReader.cpp.
Member Function Documentation
getValue()
template<typename T > T ProbeHistReader::getValue (const std::string & s) private
Definition at line 63 of file ProbeHistReader.h.
References Attrib::Legacy::Distribution::T.
minimum()
size_t ProbeHistReader::minimum (double lower, double upper)
Parameters
lower radius [mm]
upper radius [mm]
Definition at line 65 of file ProbeHistReader.cpp.
References begin(), bincount_m, binwidth_m, end(), and rmin_m.
parseFile()
void ProbeHistReader::parseFile ()
Definition at line 37 of file ProbeHistReader.cpp.
References bincount_m, filename_m, and parseHeader().
parseHeader()
void ProbeHistReader::parseHeader (std::ifstream & ifs) private
Definition at line 99 of file ProbeHistReader.cpp.
References bincount_m, binwidth_m, filename_m, interpolation::re(), and rmin_m.
Referenced by parseFile().
Member Data Documentation
bincount_m
container_t ProbeHistReader::bincount_m private
Definition at line 58 of file ProbeHistReader.h.
Referenced by minimum(), parseFile(), and parseHeader().
binwidth_m
double ProbeHistReader::binwidth_m private
Definition at line 56 of file ProbeHistReader.h.
Referenced by minimum(), and parseHeader().
filename_m
std::string ProbeHistReader::filename_m private
Histogram file.
Definition at line 53 of file ProbeHistReader.h.
Referenced by parseFile(), and parseHeader().
rmin_m
double ProbeHistReader::rmin_m private
Definition at line 55 of file ProbeHistReader.h.
Referenced by minimum(), and parseHeader().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/optimizer/Util/ProbeHistReader.h
/psi/home/gsell/data/src/OPAL/src/optimizer/Util/ProbeHistReader.cpp