OPAL (Object Oriented Parallel Accelerator Library): Expressions::AColumn Class Reference
Expressions::AColumn Class Reference
An array expression defined as a table column.
#include <AColumn.h>
Public Member Functions
AColumn (const std::string &tName, const std::string &cName, const RangeRep &rng)
Constructor.
AColumn (const AColumn &)
~AColumn ()
virtual OArray< double > * clone () const
Make clone.
virtual std::vector< double > evaluate () const
Evaluate.
virtual void print (std::ostream &os, int precedence=99) const
Print expression.
Public Member Functions inherited from Expressions::OArray< double >
OArray ()
OArray (const OArray &)
virtual ~OArray ()
virtual bool isConstant () const
Test for constant.
Private Member Functions
AColumn ()
const AColumn & operator= (const AColumn &)
Private Attributes
const std::string tab_name
const std::string col_name
RangeRep itsRange
Detailed Description
An array expression defined as a table column.
Definition at line 36 of file AColumn.h.
Constructor & Destructor Documentation
AColumn() [1/3]
Expressions::AColumn::AColumn (const std::string & tName, const std::string & cName, const RangeRep & rng)
Constructor.
Definition at line 39 of file AColumn.cpp.
AColumn() [2/3]
Expressions::AColumn::AColumn (const AColumn & rhs)
Definition at line 32 of file AColumn.cpp.
~AColumn()
Expressions::AColumn::~AColumn ()
Definition at line 44 of file AColumn.cpp.
AColumn() [3/3]
Expressions::AColumn::AColumn () private
Referenced by clone().
Member Function Documentation
clone()
OArray< double > * Expressions::AColumn::clone () const virtual
Make clone.
Implements Expressions::OArray< double >.
Definition at line 48 of file AColumn.cpp.
References AColumn().
evaluate()
std::vector< double > Expressions::AColumn::evaluate () const virtual
Evaluate.
Implements Expressions::OArray< double >.
Definition at line 53 of file AColumn.cpp.
References col_name, Table::fill(), Table::find(), Table::getColumn(), itsRange, and tab_name.
operator=()
const AColumn& Expressions::AColumn::operator= (const AColumn &) private
print()
void Expressions::AColumn::print (std::ostream & os, int precedence = 99) const virtual
Print expression.
Implements Expressions::OArray< double >.
Definition at line 60 of file AColumn.cpp.
References col_name, itsRange, and tab_name.
Member Data Documentation
col_name
const std::string Expressions::AColumn::col_name private
Definition at line 66 of file AColumn.h.
Referenced by evaluate(), and print().
itsRange
RangeRep Expressions::AColumn::itsRange private
Definition at line 69 of file AColumn.h.
Referenced by evaluate(), and print().
tab_name
const std::string Expressions::AColumn::tab_name private
Definition at line 65 of file AColumn.h.
Referenced by evaluate(), and print().
The documentation for this class was generated from the following files:
src/Expressions/AColumn.h
src/Expressions/AColumn.cpp