OPAL (Object Oriented Parallel Accelerator Library): OpalSample Class Reference
OpalSample Class Reference
#include <OpalSample.h>
Public Member Functions
OpalSample ()
Exemplar constructor.
virtual ~OpalSample ()
virtual OpalSample * clone (const std::string &name)
Make clone.
virtual void execute ()
Check the OpalSample data.
void initialize (const std::string &dvarName, double lower, double upper, size_t modulo=1, bool sequence=false)
std::string getVariable () const
unsigned int getSize () const
Public Member Functions inherited from Definition
virtual ~Definition ()
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
Public Member Functions inherited from Object
virtual ~Object ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static OpalSample * find (const std::string &name)
Find sampling method.
Public Attributes
std::shared_ptr< SamplingMethod > sampleMethod_m
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Private Types
enum OpalSampleMethod : unsigned short {
OpalSampleMethod::UNIFORM_INT, OpalSampleMethod::UNIFORM, OpalSampleMethod::GAUSSIAN, OpalSampleMethod::FROMFILE,
OpalSampleMethod::LATIN_HYPERCUBE, OpalSampleMethod::RANDOM_SEQUENCE_UNIFORM_INT, OpalSampleMethod::RANDOM_SEQUENCE_UNIFORM
}
Private Member Functions
OpalSample (const std::string &name, OpalSample *parent)
OpalSample (const OpalSample &)=delete
Not implemented.
void operator= (const OpalSample &)=delete
Private Attributes
unsigned int size_m
Additional Inherited Members
Protected Member Functions inherited from Definition
Definition (int size, const char *name, const char *help)
Constructor for exemplars.
Definition (const std::string &name, Definition *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 31 of file OpalSample.h.
Member Enumeration Documentation
OpalSampleMethod
enum OpalSample::OpalSampleMethod : unsigned short strong private
Enumerator
UNIFORM_INT
UNIFORM
GAUSSIAN
FROMFILE
LATIN_HYPERCUBE
RANDOM_SEQUENCE_UNIFORM_INT
RANDOM_SEQUENCE_UNIFORM
Definition at line 61 of file OpalSample.h.
Constructor & Destructor Documentation
OpalSample() [1/3]
OpalSample::OpalSample ()
Exemplar constructor.
Definition at line 52 of file OpalSample.cpp.
References Attrib::Distribution::FNAME, Object::itsAttr, Attributes::makeBool(), Attributes::makePredefinedString(), Attributes::makeReal(), Attributes::makeString(), Object::registerOwnership(), AttributeHandler::STATEMENT, and Attrib::Distribution::TYPE.
Referenced by clone().
~OpalSample()
virtual OpalSample::~OpalSample () inline virtual
Definition at line 37 of file OpalSample.h.
OpalSample() [2/3]
OpalSample::OpalSample (const OpalSample &) private delete
Not implemented.
OpalSample() [3/3]
OpalSample::OpalSample (const std::string & name, OpalSample * parent) private
Private copy constructor, called by clone
Definition at line 89 of file OpalSample.cpp.
Member Function Documentation
clone()
OpalSample * OpalSample::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 94 of file OpalSample.cpp.
References name, and OpalSample().
execute()
void OpalSample::execute () virtual
Check the OpalSample data.
Reimplemented from Object.
Definition at line 99 of file OpalSample.cpp.
find()
OpalSample * OpalSample::find (const std::string & name) static
Find sampling method.
Definition at line 104 of file OpalSample.cpp.
References OpalData::find(), OpalData::getInstance(), and name.
Referenced by SampleCmd::execute().
getSize()
unsigned int OpalSample::getSize () const inline
Definition at line 82 of file OpalSample.h.
References size_m.
Referenced by SampleCmd::execute(), and initialize().
getVariable()
std::string OpalSample::getVariable () const
Definition at line 232 of file OpalSample.cpp.
References Attributes::getString(), and Object::itsAttr.
Referenced by SampleCmd::execute().
initialize()
void OpalSample::initialize (const std::string & dvarName, double lower, double upper, size_t modulo = 1, bool sequence = false)
Definition at line 115 of file OpalSample.cpp.
References Attrib::Distribution::FNAME, FROMFILE, Hypervolume::FromFile(), GAUSSIAN, Attributes::getBool(), Attributes::getReal(), getSize(), Attributes::getString(), Object::itsAttr, LATIN_HYPERCUBE, RANDOM_SEQUENCE_UNIFORM, RANDOM_SEQUENCE_UNIFORM_INT, sampleMethod_m, Options::seed, size_m, Attrib::Distribution::TYPE, UNIFORM, and UNIFORM_INT.
Referenced by SampleCmd::execute().
operator=()
void OpalSample::operator= (const OpalSample &) private delete
Member Data Documentation
sampleMethod_m
std::shared_ptr<SamplingMethod> OpalSample::sampleMethod_m
Definition at line 58 of file OpalSample.h.
Referenced by SampleCmd::execute(), and initialize().
size_m
unsigned int OpalSample::size_m private
Definition at line 78 of file OpalSample.h.
Referenced by getSize(), and initialize().
The documentation for this class was generated from the following files:
src/Sample/OpalSample.h
src/Sample/OpalSample.cpp