OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/ippl/src/Meshes/UniformCartesian.hpp File Reference
UniformCartesian.hpp File Reference
#include "Utility/PAssert.h"
#include "Utility/IpplInfo.h"
#include "Field/BareField.h"
#include "Field/BrickExpression.h"
#include "Field/LField.h"
#include "Field/Assign.h"
#include "Field/AssignDefs.h"
Classes
struct OpUMeshExtrapolate< T >
Namespaces
IPPL
Functions
template<class T >
void PETE_apply (OpUMeshExtrapolate< T > e, T &a, T b)
template<class T , class MFLOAT >
Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & Div (Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &x, Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & Div (Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &x, Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & Div (Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &x, Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & Div (Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &x, Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & Div (Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &x, Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & Div (Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &x, Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & Div (Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &x, Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & Div (Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &x, Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & Div (Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &x, Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & Div (Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Edge > &x, Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & Div (Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Edge > &x, Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & Div (Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Edge > &x, Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & Div (Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &x, Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & Div (Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &x, Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & Div (Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &x, Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & Div (Field< Tenzor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & Div (Field< Tenzor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & Div (Field< Tenzor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & Div (Field< SymTenzor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & Div (Field< SymTenzor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & Div (Field< SymTenzor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & Div (Field< Tenzor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & Div (Field< Tenzor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & Div (Field< Tenzor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & Div (Field< SymTenzor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & Div (Field< SymTenzor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & Div (Field< SymTenzor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & Grad (Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & Grad (Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & Grad (Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &r)
Grad operator approximate at the border up to a term of order O(h^2)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Edge > & Grad (Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Edge > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Edge > & Grad (Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Edge > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Edge > & Grad (Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Edge > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & Grad (Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & Grad (Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & Grad (Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & Grad (Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & Grad (Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & Grad (Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & Grad (Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & Grad (Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & Grad (Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & Grad1Ord (Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Tenzor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & Grad (Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &x, Field< Tenzor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Tenzor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & Grad (Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &x, Field< Tenzor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Tenzor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & Grad (Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &x, Field< Tenzor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &r)
template<class T , class MFLOAT >
Field< Tenzor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & Grad (Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &x, Field< Tenzor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Tenzor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & Grad (Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &x, Field< Tenzor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &r)
template<class T , class MFLOAT >
Field< Tenzor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & Grad (Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &x, Field< Tenzor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &x, Field< T2, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &w, Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &x, Field< T2, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &w, Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &x, Field< T2, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &w, Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &x, Field< T2, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &w, Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &x, Field< T2, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &w, Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &r)
template<class T1 , class T2 , class MFLOAT >
Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &x, Field< T2, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &w, Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &r)
template<class T1 , class MFLOAT >
Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &x, Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &r)
template<class T1 , class MFLOAT >
Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &x, Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &r)
template<class T1 , class MFLOAT >
Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & IPPL::Average (Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &x, Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &r)
template<class T1 , class MFLOAT >
Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Vert > &x, Field< T1, 1U, UniformCartesian< 1U, MFLOAT >, Cell > &r)
template<class T1 , class MFLOAT >
Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Vert > &x, Field< T1, 2U, UniformCartesian< 2U, MFLOAT >, Cell > &r)
template<class T1 , class MFLOAT >
Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & IPPL::Average (Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Vert > &x, Field< T1, 3U, UniformCartesian< 3U, MFLOAT >, Cell > &r)
Function Documentation
Div() [1/27]
template<class T , class MFLOAT > Field<T,1U,UniformCartesian<1U,MFLOAT>,Cell>& Div (Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & x, Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 1279 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [2/27]
template<class T , class MFLOAT > Field<T,2U,UniformCartesian<2U,MFLOAT>,Cell>& Div (Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & x, Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 1293 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [3/27]
template<class T , class MFLOAT > Field<T,3U,UniformCartesian<3U,MFLOAT>,Cell>& Div (Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & x, Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 1310 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [4/27]
template<class T , class MFLOAT > Field<T,1U,UniformCartesian<1U,MFLOAT>,Vert>& Div (Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & x, Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 1334 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [5/27]
template<class T , class MFLOAT > Field<T,2U,UniformCartesian<2U,MFLOAT>,Vert>& Div (Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & x, Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 1349 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [6/27]
template<class T , class MFLOAT > Field<T,3U,UniformCartesian<3U,MFLOAT>,Vert>& Div (Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & x, Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 1366 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [7/27]
template<class T , class MFLOAT > Field<T,1U,UniformCartesian<1U,MFLOAT>,Vert>& Div (Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & x, Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 1390 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [8/27]
template<class T , class MFLOAT > Field<T,2U,UniformCartesian<2U,MFLOAT>,Vert>& Div (Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & x, Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 1404 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [9/27]
template<class T , class MFLOAT > Field<T,3U,UniformCartesian<3U,MFLOAT>,Vert>& Div (Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & x, Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 1424 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [10/27]
template<class T , class MFLOAT > Field<T,1U,UniformCartesian<1U,MFLOAT>,Vert>& Div (Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Edge > & x, Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 1453 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [11/27]
template<class T , class MFLOAT > Field<T,2U,UniformCartesian<2U,MFLOAT>,Vert>& Div (Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Edge > & x, Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 1467 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [12/27]
template<class T , class MFLOAT > Field<T,3U,UniformCartesian<3U,MFLOAT>,Vert>& Div (Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Edge > & x, Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 1487 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [13/27]
template<class T , class MFLOAT > Field<T,1U,UniformCartesian<1U,MFLOAT>,Cell>& Div (Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & x, Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 1516 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [14/27]
template<class T , class MFLOAT > Field<T,2U,UniformCartesian<2U,MFLOAT>,Cell>& Div (Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & x, Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 1530 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [15/27]
template<class T , class MFLOAT > Field<T,3U,UniformCartesian<3U,MFLOAT>,Cell>& Div (Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & x, Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 1550 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [16/27]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,UniformCartesian<1U,MFLOAT>,Cell>& Div (Field< Tenzor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 1579 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [17/27]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,UniformCartesian<2U,MFLOAT>,Cell>& Div (Field< Tenzor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 1593 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [18/27]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,UniformCartesian<3U,MFLOAT>,Cell>& Div (Field< Tenzor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & r) inline
Definition at line 1611 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [19/27]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,UniformCartesian<1U,MFLOAT>,Cell>& Div (Field< SymTenzor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & r) inline
Definition at line 1636 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [20/27]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,UniformCartesian<2U,MFLOAT>,Cell>& Div (Field< SymTenzor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & r) inline
Definition at line 1650 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [21/27]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,UniformCartesian<3U,MFLOAT>,Cell>& Div (Field< SymTenzor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & r) inline
Definition at line 1667 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [22/27]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,UniformCartesian<1U,MFLOAT>,Vert>& Div (Field< Tenzor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 1692 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [23/27]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,UniformCartesian<2U,MFLOAT>,Vert>& Div (Field< Tenzor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 1706 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [24/27]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,UniformCartesian<3U,MFLOAT>,Vert>& Div (Field< Tenzor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 1723 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [25/27]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,UniformCartesian<1U,MFLOAT>,Vert>& Div (Field< SymTenzor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 1748 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [26/27]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,UniformCartesian<2U,MFLOAT>,Vert>& Div (Field< SymTenzor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 1762 of file UniformCartesian.hpp.
References assign(), and dot().
Div() [27/27]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,UniformCartesian<3U,MFLOAT>,Vert>& Div (Field< SymTenzor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 1779 of file UniformCartesian.hpp.
References assign(), and dot().
Grad() [1/21]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,UniformCartesian<1U,MFLOAT>,Cell>& Grad (Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 1804 of file UniformCartesian.hpp.
References assign().
Grad() [2/21]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,UniformCartesian<2U,MFLOAT>,Cell>& Grad (Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 1818 of file UniformCartesian.hpp.
References assign().
Grad() [3/21]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,UniformCartesian<3U,MFLOAT>,Cell>& Grad (Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & r)
Grad operator approximate at the border up to a term of order O(h^2)
Definition at line 1835 of file UniformCartesian.hpp.
References assign().
Grad() [4/21]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,UniformCartesian<1U,MFLOAT>,Edge>& Grad (Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Edge > & r)
Definition at line 1860 of file UniformCartesian.hpp.
References assign().
Grad() [5/21]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,UniformCartesian<2U,MFLOAT>,Edge>& Grad (Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Edge > & r)
Definition at line 1874 of file UniformCartesian.hpp.
References assign().
Grad() [6/21]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,UniformCartesian<3U,MFLOAT>,Edge>& Grad (Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Edge > & r)
Definition at line 1903 of file UniformCartesian.hpp.
References assign().
Grad() [7/21]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,UniformCartesian<1U,MFLOAT>,Vert>& Grad (Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 1952 of file UniformCartesian.hpp.
References assign().
Grad() [8/21]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,UniformCartesian<2U,MFLOAT>,Vert>& Grad (Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 1966 of file UniformCartesian.hpp.
References assign().
Grad() [9/21]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,UniformCartesian<3U,MFLOAT>,Vert>& Grad (Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 1983 of file UniformCartesian.hpp.
References assign().
Grad() [10/21]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,UniformCartesian<1U,MFLOAT>,Vert>& Grad (Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 2007 of file UniformCartesian.hpp.
References assign().
Grad() [11/21]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,UniformCartesian<2U,MFLOAT>,Vert>& Grad (Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 2022 of file UniformCartesian.hpp.
References assign().
Grad() [12/21]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,UniformCartesian<3U,MFLOAT>,Vert>& Grad (Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 2043 of file UniformCartesian.hpp.
References assign().
Grad() [13/21]
template<class T , class MFLOAT > Field<Vektor<T,1U>,1U,UniformCartesian<1U,MFLOAT>,Cell>& Grad (Field< T, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & x, Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 2073 of file UniformCartesian.hpp.
References assign().
Grad() [14/21]
template<class T , class MFLOAT > Field<Vektor<T,2U>,2U,UniformCartesian<2U,MFLOAT>,Cell>& Grad (Field< T, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & x, Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 2088 of file UniformCartesian.hpp.
References assign().
Grad() [15/21]
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,UniformCartesian<3U,MFLOAT>,Cell>& Grad (Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 2110 of file UniformCartesian.hpp.
References assign(), and Index::length().
Grad() [16/21]
template<class T , class MFLOAT > Field<Tenzor<T,1U>,1U,UniformCartesian<1U,MFLOAT>,Cell>& Grad (Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & x, Field< Tenzor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & r)
Definition at line 2218 of file UniformCartesian.hpp.
References assign(), and outerProduct().
Grad() [17/21]
template<class T , class MFLOAT > Field<Tenzor<T,2U>,2U,UniformCartesian<2U,MFLOAT>,Cell>& Grad (Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & x, Field< Tenzor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & r)
Definition at line 2232 of file UniformCartesian.hpp.
References assign(), and outerProduct().
Grad() [18/21]
template<class T , class MFLOAT > Field<Tenzor<T,3U>,3U,UniformCartesian<3U,MFLOAT>,Cell>& Grad (Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & x, Field< Tenzor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & r)
Definition at line 2249 of file UniformCartesian.hpp.
References assign(), and outerProduct().
Grad() [19/21]
template<class T , class MFLOAT > Field<Tenzor<T,1U>,1U,UniformCartesian<1U,MFLOAT>,Vert>& Grad (Field< Vektor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Cell > & x, Field< Tenzor< T, 1U >, 1U, UniformCartesian< 1U, MFLOAT >, Vert > & r)
Definition at line 2274 of file UniformCartesian.hpp.
References assign(), and outerProduct().
Grad() [20/21]
template<class T , class MFLOAT > Field<Tenzor<T,2U>,2U,UniformCartesian<2U,MFLOAT>,Vert>& Grad (Field< Vektor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Cell > & x, Field< Tenzor< T, 2U >, 2U, UniformCartesian< 2U, MFLOAT >, Vert > & r)
Definition at line 2288 of file UniformCartesian.hpp.
References assign(), and outerProduct().
Grad() [21/21]
template<class T , class MFLOAT > Field<Tenzor<T,3U>,3U,UniformCartesian<3U,MFLOAT>,Vert>& Grad (Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & x, Field< Tenzor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Vert > & r)
Definition at line 2305 of file UniformCartesian.hpp.
References assign(), and outerProduct().
Grad1Ord()
template<class T , class MFLOAT > Field<Vektor<T,3U>,3U,UniformCartesian<3U,MFLOAT>,Cell>& Grad1Ord (Field< T, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & x, Field< Vektor< T, 3U >, 3U, UniformCartesian< 3U, MFLOAT >, Cell > & r) inline
Definition at line 2188 of file UniformCartesian.hpp.
References assign().
PETE_apply()
template<class T > void PETE_apply (OpUMeshExtrapolate< T > e, T & a, T b) inline
Definition at line 490 of file UniformCartesian.hpp.
References a, and Physics::e.