OPAL (Object Oriented Parallel Accelerator Library): Timing Struct Reference
Timing Struct Reference
#include <IpplTimings.h>
Public Types
typedef unsigned int TimerRef
typedef IpplTimerInfo TimerInfo
typedef std::vector< my_auto_ptr< TimerInfo > > TimerList_t
typedef std::map< std::string, TimerInfo * > TimerMap_t
Public Member Functions
Timing ()
~Timing ()
TimerRef getTimer (const char *)
void startTimer (TimerRef)
void stopTimer (TimerRef)
void clearTimer (TimerRef)
TimerInfo * infoTimer (const char *nm)
void print ()
void print (const std::string &fn, const std::map< std::string, unsigned int > &problemSize)
Private Attributes
TimerList_t TimerList
TimerMap_t TimerMap
Detailed Description
Definition at line 119 of file IpplTimings.h.
Member Typedef Documentation
TimerInfo
typedef IpplTimerInfo Timing::TimerInfo
Definition at line 125 of file IpplTimings.h.
TimerList_t
typedef std::vector<my_auto_ptr<TimerInfo> > Timing::TimerList_t
Definition at line 159 of file IpplTimings.h.
TimerMap_t
typedef std::map<std::string, TimerInfo *> Timing::TimerMap_t
Definition at line 160 of file IpplTimings.h.
TimerRef
typedef unsigned int Timing::TimerRef
Definition at line 122 of file IpplTimings.h.
Constructor & Destructor Documentation
Timing()
Timing::Timing ()
Definition at line 24 of file IpplTimings.cpp.
~Timing()
Timing::~Timing ()
Definition at line 32 of file IpplTimings.cpp.
References TimerList, and TimerMap.
Member Function Documentation
clearTimer()
void Timing::clearTimer (TimerRef t)
Definition at line 81 of file IpplTimings.cpp.
References TimerList.
Referenced by IpplTimings::clearTimer().
getTimer()
Timing::TimerRef Timing::getTimer (const char * nm)
Definition at line 44 of file IpplTimings.cpp.
References IpplTimerInfo::indx, IpplTimerInfo::name, TimerList, TimerMap, and value_type().
Referenced by IpplTimings::getTimer().
infoTimer()
TimerInfo* Timing::infoTimer (const char * nm) inline
Definition at line 146 of file IpplTimings.h.
References TimerMap.
Referenced by IpplTimings::infoTimer().
print() [1/2]
void Timing::print ()
Definition at line 90 of file IpplTimings.cpp.
References a, begin(), IpplTimerInfo::cpuTime, end(), endl(), IpplInfo::getNodes(), level1(), min(), IpplTimerInfo::name, reduce(), TimerList, and IpplTimerInfo::wallTime.
Referenced by IpplTimings::print().
print() [2/2]
void Timing::print (const std::string & fn, const std::map< std::string, unsigned int > & problemSize)
Definition at line 153 of file IpplTimings.cpp.
References a, begin(), IpplTimerInfo::cpuTime, end(), endl(), IpplInfo::getNodes(), min(), IpplTimerInfo::name, reduce(), TimerList, and IpplTimerInfo::wallTime.
startTimer()
void Timing::startTimer (TimerRef t)
Definition at line 63 of file IpplTimings.cpp.
References TimerList.
Referenced by IpplTimings::startTimer().
stopTimer()
void Timing::stopTimer (TimerRef t)
Definition at line 72 of file IpplTimings.cpp.
References TimerList.
Referenced by IpplTimings::stopTimer().
Member Data Documentation
TimerList
TimerList_t Timing::TimerList private
Definition at line 164 of file IpplTimings.h.
Referenced by clearTimer(), getTimer(), print(), startTimer(), stopTimer(), and ~Timing().
TimerMap
TimerMap_t Timing::TimerMap private
Definition at line 167 of file IpplTimings.h.
Referenced by getTimer(), infoTimer(), and ~Timing().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/IpplTimings.h
/psi/home/gsell/data/src/OPAL/src/ippl/src/Utility/IpplTimings.cpp