OPAL (Object Oriented Parallel Accelerator Library): Element Class Reference
Element Class Reference abstract
#include <Element.h>
Public Types
enum ReferenceType { IS_ENTRY, IS_CENTRE, IS_EXIT }
Reference for element positioning.
Public Member Functions
virtual ~Element ()
virtual bool canReplaceBy (Object *object)
Test if replacement is allowed.
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual double getLength () const =0
Return element length.
virtual double getEntrance (ReferenceType) const
Return arc length from origin to entrance (negative !).
virtual double getExit (ReferenceType) const
Return arc length from origin to exit (positive !).
virtual void setShared (bool)
Set shared flag.
ElementBase * getElement () const
Return the embedded CLASSIC element.
void setElement (ElementBase *)
Assign new CLASSIC element.
Public Member Functions inherited from Object
virtual ~Object ()
virtual Object * clone (const std::string &name)=0
Return a clone.
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void print (std::ostream &) const
Print the object.
virtual void printValue (std::ostream &) const
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Static Public Member Functions
static Element * find (const std::string &name)
Find named Element.
Protected Member Functions
Element (int size, const char *name, const char *help)
Constructor for exemplars.
Element (const std::string &name, Element *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Private Member Functions
Element ()
Element (const Element &)
void operator= (const Element &)
Private Attributes
Pointer< ElementBase > itsClassicElement
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 38 of file Element.h.
Member Enumeration Documentation
ReferenceType
enum Element::ReferenceType
Reference for element positioning.
Enumerator
IS_ENTRY
IS_CENTRE
IS_EXIT
Definition at line 44 of file Element.h.
Constructor & Destructor Documentation
~Element()
Element::~Element () virtual
Definition at line 36 of file Element.cpp.
Element() [1/4]
Element::Element (int size, const char * name, const char * help) protected
Constructor for exemplars.
Definition at line 107 of file Element.cpp.
Element() [2/4]
Element::Element (const std::string & name, Element * parent) protected
Constructor for clones.
Definition at line 112 of file Element.cpp.
Element() [3/4]
Element::Element () private
Element() [4/4]
Element::Element (const Element &) private
Member Function Documentation
canReplaceBy()
bool Element::canReplaceBy (Object * object) virtual
Test if replacement is allowed.
Reimplemented from Object.
Definition at line 40 of file Element.cpp.
find()
Element * Element::find (const std::string & name) static
Find named Element.
Definition at line 45 of file Element.cpp.
References OpalData::find(), OpalData::getInstance(), and name.
Referenced by Sequence::addEndMarkers(), SequenceParser::findNeighbourPositions(), Selector::handleElement(), Selector::Selector(), and Sequence::storeLine().
getCategory()
const std::string Element::getCategory () const virtual
Return the object category as a string.
Implements Object.
Reimplemented in BeamSequence.
Definition at line 56 of file Element.cpp.
getElement()
ElementBase * Element::getElement () const inline
Return the embedded CLASSIC element.
Definition at line 120 of file Element.h.
References itsClassicElement.
Referenced by Sequence::addEndMarkers(), Line::fetchLine(), Sequence::fetchLine(), OpalMarker::OpalMarker(), OpalOutputPlane::OpalOutputPlane(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVariableRFCavityFringeField::OpalVariableRFCavityFringeField(), Line::replace(), Sequence::replace(), PyOpal::PyLine_< C >::setElement(), OpalScalingFFAMagnet::setupDefaultEndField(), OpalScalingFFAMagnet::setupNamedEndField(), OpalMonitor::update(), OpalRBend::update(), OpalSBend::update(), OpalSource::update(), OpalDegrader::update(), OpalSlit::update(), OpalHKicker::update(), OpalMarker::update(), OpalECollimator::update(), OpalRCollimator::update(), OpalFlexibleCollimator::update(), OpalSolenoid::update(), OpalSeptum::update(), OpalProbe::update(), OpalPepperPot::update(), OpalCCollimator::update(), OpalSextupole::update(), OpalRBend3D::update(), OpalVerticalFFAMagnet::update(), OpalMultipole::update(), OpalOctupole::update(), OpalUndulator::update(), OpalDrift::update(), OpalQuadrupole::update(), OpalVacuum::update(), OpalMultipoleT::update(), OpalTravelingWave::update(), OpalVKicker::update(), OpalStripper::update(), OpalSBend3D::update(), OpalKicker::update(), OpalVariableRFCavity::update(), OpalScalingFFAMagnet::update(), OpalRingDefinition::update(), OpalCavity::update(), OpalOutputPlane::update(), OpalVariableRFCavityFringeField::update(), OpalCyclotron::update(), OpalMultipoleTStraight::update(), OpalOffset::OpalLocalCartesianOffset::update(), OpalMultipoleTCurvedVarRadius::update(), OpalMultipoleTCurvedConstRadius::update(), and OpalElement::update().
getEntrance()
double Element::getEntrance (ReferenceType ref) const virtual
Return arc length from origin to entrance (negative !).
Reimplemented in Sequence.
Definition at line 71 of file Element.cpp.
References getLength(), IS_CENTRE, IS_EXIT, and Hypervolume::ref.
Referenced by Sequence::findDriftLength(), and Sequence::getEntrance().
getExit()
double Element::getExit (ReferenceType ref) const virtual
Return arc length from origin to exit (positive !).
Reimplemented in Sequence.
Definition at line 86 of file Element.cpp.
References getLength(), IS_CENTRE, IS_ENTRY, and Hypervolume::ref.
Referenced by Sequence::findDriftLength(), and Sequence::getExit().
getLength()
virtual double Element::getLength () const pure virtual
Return element length.
Implemented in OpalElement, Sequence, and Line.
Referenced by SequenceParser::findNeighbourPositions(), getEntrance(), and getExit().
operator=()
void Element::operator= (const Element &) private
setElement()
void Element::setElement (ElementBase * base) inline
Assign new CLASSIC element.
Definition at line 125 of file Element.h.
References itsClassicElement.
Referenced by Line::Line(), OpalCavity::OpalCavity(), OpalCCollimator::OpalCCollimator(), OpalCyclotron::OpalCyclotron(), OpalDegrader::OpalDegrader(), OpalDrift::OpalDrift(), OpalECollimator::OpalECollimator(), OpalFlexibleCollimator::OpalFlexibleCollimator(), OpalHKicker::OpalHKicker(), OpalKicker::OpalKicker(), OpalOffset::OpalLocalCartesianOffset::OpalLocalCartesianOffset(), OpalMarker::OpalMarker(), OpalMonitor::OpalMonitor(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalMultipoleTCurvedConstRadius::OpalMultipoleTCurvedConstRadius(), OpalMultipoleTCurvedVarRadius::OpalMultipoleTCurvedVarRadius(), OpalMultipoleTStraight::OpalMultipoleTStraight(), OpalOctupole::OpalOctupole(), OpalOutputPlane::OpalOutputPlane(), OpalPepperPot::OpalPepperPot(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRBend::OpalRBend(), OpalRBend3D::OpalRBend3D(), OpalRCollimator::OpalRCollimator(), OpalRingDefinition::OpalRingDefinition(), OpalSBend::OpalSBend(), OpalSBend3D::OpalSBend3D(), OpalScalingFFAMagnet::OpalScalingFFAMagnet(), OpalSeptum::OpalSeptum(), OpalSextupole::OpalSextupole(), OpalSlit::OpalSlit(), OpalSolenoid::OpalSolenoid(), OpalSource::OpalSource(), OpalStripper::OpalStripper(), OpalTravelingWave::OpalTravelingWave(), OpalUndulator::OpalUndulator(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVariableRFCavityFringeField::OpalVariableRFCavityFringeField(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), OpalVKicker::OpalVKicker(), PyOpal::PyLine_< C >::registerObject(), Sequence::Sequence(), OpalVerticalFFAMagnet::update(), OpalMultipoleT::update(), OpalSBend3D::update(), OpalVariableRFCavity::update(), OpalScalingFFAMagnet::update(), OpalRingDefinition::update(), OpalOffset::OpalGlobalCylindricalOffset::update(), OpalVariableRFCavityFringeField::update(), OpalOffset::OpalLocalCylindricalOffset::update(), OpalOffset::OpalGlobalCartesianOffset::update(), OpalMultipoleTStraight::update(), OpalOffset::OpalLocalCartesianOffset::update(), OpalMultipoleTCurvedConstRadius::update(), OpalMultipoleTCurvedVarRadius::update(), and Replacer::visitFlaggedElmPtr().
setShared()
void Element::setShared (bool flag) virtual
Set shared flag.
Reimplemented from Object.
Definition at line 101 of file Element.cpp.
References itsClassicElement, ElementBase::makeSharable(), and Object::setShared().
shouldTrace()
bool Element::shouldTrace () const virtual
Trace flag.
Implements Object.
Definition at line 61 of file Element.cpp.
shouldUpdate()
bool Element::shouldUpdate () const virtual
Update flag.
Implements Object.
Definition at line 66 of file Element.cpp.
Member Data Documentation
itsClassicElement
Pointer<ElementBase> Element::itsClassicElement private
Definition at line 113 of file Element.h.
Referenced by getElement(), setElement(), and setShared().
The documentation for this class was generated from the following files:
src/AbstractObjects/Element.h
src/AbstractObjects/Element.cpp