OPAL (Object Oriented Parallel Accelerator Library): Unique Class Reference
Unique Class Reference
#include <Unique.h>
Public Types
typedef unsigned int type
Static Public Member Functions
static type get ()
Private Member Functions
Unique ()
Static Private Attributes
static type Last = 0
Detailed Description
Definition at line 28 of file Unique.h.
Member Typedef Documentation
type
typedef unsigned int Unique::type
Definition at line 31 of file Unique.h.
Constructor & Destructor Documentation
Unique()
Unique::Unique () private
Member Function Documentation
get()
static type Unique::get () inline static
Definition at line 33 of file Unique.h.
References Last.
Referenced by FieldLayout< Dim >::FieldLayout(), FieldLayout< Dim >::initialize(), RegionLayout< T, Dim, Mesh >::make_rnodes(), and FieldLayout< Dim >::setup().
Member Data Documentation
Last
Unique::type Unique::Last = 0 static private
Definition at line 41 of file Unique.h.
Referenced by get().
The documentation for this class was generated from the following files:
ippl/src/Utility/Unique.h
ippl/src/Utility/Unique.cpp