OPAL (Object Oriented Parallel Accelerator Library): RealConstant Class Reference
RealConstant Class Reference
#include <RealConstant.h>
Public Member Functions
RealConstant ()
Exemplar constructor.
RealConstant (const std::string &name, RealConstant *parent, double value)
Constructor for built-in constants.
virtual ~RealConstant ()
virtual bool canReplaceBy (Object *object)
Test if object can be replaced.
virtual RealConstant * clone (const std::string &name)
Make clone.
virtual void print (std::ostream &) const
Print the constant.
virtual void printValue (std::ostream &os) const
Print its value.
virtual double getReal () const
Return value.
Public Member Functions inherited from ValueDefinition
virtual ~ValueDefinition ()
virtual const std::string getCategory () const
Return the object category as a string.
virtual bool shouldTrace () const
Trace flag.
virtual bool shouldUpdate () const
Update flag.
virtual bool getBool () const
Return logical value.
virtual bool getBoolComponent (int) const
Return indexed logical value.
virtual double getRealComponent (int) const
Return indexed real value.
virtual std::string getString () const
Return string value.
virtual std::string getStringComponent (int) const
Return indexed string value.
Attribute & value ()
Return the attribute representing the value of the definition.
const Attribute & value () const
Return the attribute representing the value of the definition.
Public Member Functions inherited from Object
virtual ~Object ()
void copyAttributes (const Object &)
Copy attributes from another object.
virtual void execute ()
Execute the command.
virtual Attribute * findAttribute (const std::string &name)
Find an attribute by name.
virtual const Attribute * findAttribute (const std::string &name) const
Find an attribute by name.
virtual Object * makeTemplate (const std::string &, TokenStream &, Statement &)
Macro handler function.
virtual Object * makeInstance (const std::string &name, Statement &, const Parser *)
Macro handler function.
virtual void parse (Statement &)
Parse the object.
virtual void parseShortcut (Statement &, bool eval=true)
Parser for single-attribute commands.
virtual void printHelp (std::ostream &) const
Print help.
virtual void replace (Object *oldObject, Object *newObject)
Replace references.
virtual void update ()
Update this object.
bool isBuiltin () const
True, if [b]this[/b] is a built-in object.
virtual bool isShared () const
Shared flag.
virtual void setShared (bool)
Set/reset shared flag.
void setDirty (bool)
Set/reset the [b]modified[/b] flag.
bool isDirty () const
True, if the [b]modified[/b] flag is set.
void setFlag (bool)
Flag/unflag this object, e. g. to control output of objects for.
bool isFlagged () const
True, if [b]this[/b] is flagged by setFlag(true).
const Object * getBaseObject () const
Return the object's base type object.
const std::string & getOpalName () const
Return object name.
Object * getParent () const
Return parent pointer.
bool isTreeMember (const Object *subTree) const
Test for tree membership.
void setOpalName (const std::string &name)
Set object name.
void setParent (Object *)
Set parent object.
void clear ()
Clear the occurrence counter.
int increment ()
Increment and return the occurrence counter.
int occurrenceCount ()
Return the occurrence counter.
void registerReference (Invalidator *a)
Register a reference to this object.
void unregisterReference (Invalidator *a)
Unegister a reference to this object.
void registerOwnership (const AttributeHandler::OwnerType &itsClass) const
Public Member Functions inherited from RCObject
int addReference () const
Increment reference count.
int removeReference () const
Decrement the reference count.
bool isShared () const
Test for sharing.
Private Member Functions
RealConstant (const RealConstant &)
void operator= (const RealConstant &)
RealConstant (const std::string &name, RealConstant *parent)
Additional Inherited Members
Public Attributes inherited from Object
std::vector< Attribute > itsAttr
The object attributes.
Protected Member Functions inherited from ValueDefinition
ValueDefinition (int size, const char *name, const char *help)
Constructor for exemplars.
ValueDefinition (const std::string &name, ValueDefinition *parent)
Constructor for clones.
Protected Member Functions inherited from Object
Object (int size, const char *name, const char *help)
Constructor for exemplars.
Object (const std::string &name, Object *parent)
Constructor for clones.
Protected Member Functions inherited from RCObject
RCObject ()
Default constructor.
RCObject (const RCObject &)
Copy constructor.
virtual ~RCObject ()=0
RCObject & operator= (const RCObject &right)
Protected Attributes inherited from ValueDefinition
const std::string itsPrefix
The declaration prefix.
Protected Attributes inherited from Object
bool builtin
Built-in flag.
bool modified
Dirty flag.
bool flagged
Object flag.
Detailed Description
Definition at line 24 of file RealConstant.h.
Constructor & Destructor Documentation
RealConstant() [1/4]
RealConstant::RealConstant ()
Exemplar constructor.
Definition at line 32 of file RealConstant.cpp.
References Physics::amu, Physics::c, OpalData::create(), Units::deg2rad, Physics::e, OpalData::getInstance(), Object::itsAttr, Physics::m_alpha, Physics::m_c, Physics::m_d, Physics::m_e, Physics::m_h2p, Physics::m_hm, Physics::m_mu, Physics::m_p, Physics::m_u, Physics::m_xe, Attributes::makeReal(), IpplInfo::myNode(), OPAL_VERSION_MAJOR, OPAL_VERSION_MINOR, OPAL_VERSION_PATCH, Physics::pi, Units::rad2deg, Object::registerOwnership(), AttributeHandler::STATEMENT, and Physics::two_pi.
Referenced by clone().
RealConstant() [2/4]
RealConstant::RealConstant (const std::string & name, RealConstant * parent, double value)
Constructor for built-in constants.
Definition at line 75 of file RealConstant.cpp.
References Object::builtin, Object::itsAttr, Attributes::setReal(), and ValueDefinition::value().
~RealConstant()
RealConstant::~RealConstant () virtual
Definition at line 84 of file RealConstant.cpp.
RealConstant() [3/4]
RealConstant::RealConstant (const RealConstant &) private
RealConstant() [4/4]
RealConstant::RealConstant (const std::string & name, RealConstant * parent) private
Definition at line 70 of file RealConstant.cpp.
Member Function Documentation
canReplaceBy()
bool RealConstant::canReplaceBy (Object * object) virtual
Test if object can be replaced.
Reimplemented from Object.
Definition at line 88 of file RealConstant.cpp.
clone()
RealConstant * RealConstant::clone (const std::string & name) virtual
Make clone.
Implements Object.
Definition at line 93 of file RealConstant.cpp.
References name, and RealConstant().
getReal()
double RealConstant::getReal () const virtual
Return value.
Reimplemented from ValueDefinition.
Definition at line 98 of file RealConstant.cpp.
References Attributes::getReal(), and Object::itsAttr.
operator=()
void RealConstant::operator= (const RealConstant &) private
print()
void RealConstant::print (std::ostream & os) const virtual
Print the constant.
Reimplemented from Object.
Definition at line 103 of file RealConstant.cpp.
References endl(), Object::getOpalName(), and Object::itsAttr.
printValue()
void RealConstant::printValue (std::ostream & os) const virtual
Print its value.
Reimplemented from Object.
Definition at line 108 of file RealConstant.cpp.
References Object::itsAttr.
The documentation for this class was generated from the following files:
src/ValueDefinitions/RealConstant.h
src/ValueDefinitions/RealConstant.cpp