OPAL (Object Oriented Parallel Accelerator Library): VpsMap< T > Class Template Reference
VpsMap< T > Class Template Reference
Truncate power series map.
#include <Tps.h>
Public Member Functions
VpsMap (int nDim, int nVar)
Constructor.
VpsMap (const Vps< T > &rhs)
Convert.
VpsMap (int nDim, const Tps< T > rhs[])
Constructor.
VpsMap (const Matrix< T > &M)
Convert.
VpsMap (const Vector< T > &V)
Convert.
VpsMap ()
VpsMap (const VpsMap< T > &rhs)
~VpsMap ()
VpsMap< T > & operator= (const VpsMap< T > &y)
VpsMap< T > substitute (const VpsMap< T > &vv) const
Substitute.
VpsMap< T > substitute (const Matrix< T > &M) const
Substitute.
VpsMap< T > substitute (const VpsMap< T > &y, int trunc) const
Substitute and truncate.
VpsMap< T > substituteInto (const Matrix< T > &x) const
Substitute.
Vector< T > constantTerm (const Vector< T > &y) const
Evaluate map at point.
Vector< T > constantTerm () const
Evaluate map at origin.
Matrix< T > linearTerms (const Vector< T > &y) const
Extract linear terms at point.
Matrix< T > linearTerms () const
Extract linear terms at origin.
VpsMap< T > derivative (int var) const
Derivative with respect to variable [b]var[/b].
VpsMap< T > integral (int var) const
Integral with respect to variable [b]var[/b].
Public Member Functions inherited from Vps< T >
Vps (int nDim, int nVar=0)
Constructor.
Vps (const Matrix< T > &M)
Convert.
Vps (const Vector< T > &V)
Convert from vector.
Vps ()
Vps (const Vps< T > &rhs)
~Vps ()
Vps< T > & operator= (const Vps< T > &)
const Tps< T > & getComponent (int index) const
Get component.
void setComponent (int index, const Tps< T > &value)
Set component.
Tps< T > & operator[] (int index)
Get component.
const Tps< T > & operator[] (int index) const
Set component.
void check () const
Check consistency.
Vps< T > operator+ () const
Unary plus.
Vps< T > operator- () const
Unary minus.
Vps< T > & operator*= (const Tps< T > &y)
Multiply by Tps<T> and assign.
Vps< T > & operator/= (const Tps< T > &y)
Divide by Tps<T> and assign.
Vps< T > & operator*= (const T &y)
Multiply by constant and assign.
Vps< T > & operator/= (const T &y)
Divide by constant and assign.
Vps< T > & operator+= (const Vps< T > &y)
Addition.
Vps< T > & operator-= (const Vps< T > &y)
Subtraction.
Vps< T > & operator+= (const Vector< T > &y)
Add and assign.
Vps< T > & operator-= (const Vector< T > &y)
Subtract and assign.
std::istream & get (std::istream &is)
Get a Vps<T> from stream is.
std::ostream & put (std::ostream &os) const
Put a Vps<T> to stream os.
int getDimension () const
Get dimension (number of Tps<T> components).
int getTopOrder () const
Get highest order contained in any component.
int getTruncOrder () const
Get lowest truncation order in any component.
int getVariables () const
Get number of variables (the same in all components).
Vps< T > filter (int lowOrder, int highOrder) const
Extract range of orders, set others to zero.
Vps< T > truncate (int trunc)
Truncate, may also increase truncation order.
Additional Inherited Members
Protected Attributes inherited from Vps< T >
Array1D< Tps< T > > data
int variables
Detailed Description
template<class T>
class VpsMap< T >
Truncate power series map.
Definition at line 31 of file Tps.h.
Constructor & Destructor Documentation
VpsMap() [1/7]
template<class T > VpsMap< T >::VpsMap (int nDim, int nVar) inline
Constructor.
Definition at line 173 of file VpsMap.h.
VpsMap() [2/7]
template<class T > VpsMap< T >::VpsMap (const Vps< T > & rhs) inline
Convert.
Definition at line 185 of file VpsMap.h.
VpsMap() [3/7]
template<class T > VpsMap< T >::VpsMap (int nDim, const Tps< T > rhs[]) inline
Constructor.
Definition at line 191 of file VpsMap.h.
VpsMap() [4/7]
template<class T > VpsMap< T >::VpsMap (const Matrix< T > & M) inline
Convert.
Definition at line 197 of file VpsMap.h.
VpsMap() [5/7]
template<class T > VpsMap< T >::VpsMap (const Vector< T > & V) inline
Convert.
Definition at line 203 of file VpsMap.h.
VpsMap() [6/7]
template<class T > VpsMap< T >::VpsMap () inline
Definition at line 167 of file VpsMap.h.
VpsMap() [7/7]
template<class T > VpsMap< T >::VpsMap (const VpsMap< T > & rhs) inline
Definition at line 179 of file VpsMap.h.
~VpsMap()
template<class T > VpsMap< T >::~VpsMap () inline
Definition at line 209 of file VpsMap.h.
Member Function Documentation
constantTerm() [1/2]
template<class T > Vector< T > VpsMap< T >::constantTerm (const Vector< T > & y) const
Evaluate map at point.
Definition at line 233 of file VpsMap.h.
References TpsData::getSubTable(), TpsData::getTpsData(), TpsSubstitution::index, TpsSubstitution::order, Array1D< T >::size(), TpsSubstitution::skip, Attrib::Legacy::Distribution::T, and TpsSubstitution::variable.
constantTerm() [2/2]
template<class T > Vector< T > VpsMap< T >::constantTerm () const
Evaluate map at origin.
Definition at line 266 of file VpsMap.h.
derivative()
template<class T > VpsMap< T > VpsMap< T >::derivative (int var) const
Derivative with respect to variable [b]var[/b].
Definition at line 302 of file VpsMap.h.
References VpsMap< T >::derivative().
Referenced by VpsMap< T >::derivative().
integral()
template<class T > VpsMap< T > VpsMap< T >::integral (int var) const
Integral with respect to variable [b]var[/b].
Definition at line 314 of file VpsMap.h.
References VpsMap< T >::integral().
Referenced by VpsMap< T >::integral().
linearTerms() [1/2]
template<class T > Matrix< T > VpsMap< T >::linearTerms (const Vector< T > & y) const
Extract linear terms at point.
Definition at line 274 of file VpsMap.h.
References Array2D< T >::ncols(), and Array2D< T >::nrows().
linearTerms() [2/2]
template<class T > Matrix< T > VpsMap< T >::linearTerms () const
Extract linear terms at origin.
Definition at line 288 of file VpsMap.h.
operator=()
template<class T > VpsMap< T > & VpsMap< T >::operator= (const VpsMap< T > & y) inline
Definition at line 214 of file VpsMap.h.
References Vps< T >::operator=().
substitute() [1/3]
template<class T > VpsMap< T > VpsMap< T >::substitute (const VpsMap< T > & vv) const inline
Substitute.
Definition at line 221 of file VpsMap.h.
substitute() [2/3]
template<class T > VpsMap< T > VpsMap< T >::substitute (const Matrix< T > & M) const inline
Substitute.
Definition at line 227 of file VpsMap.h.
substitute() [3/3]
template<class T > VpsMap< T > VpsMap< T >::substitute (const VpsMap< T > & y, int trunc) const
Substitute and truncate.
Definition at line 326 of file VpsMap.h.
References Vps< T >::check(), Vps< T >::data, Vps< T >::getDimension(), TpsData::getSubTable(), TpsData::getTpsData(), TpsSubstitution::index, min(), TpsSubstitution::order, Array1D< T >::size(), TpsSubstitution::skip, Attrib::Legacy::Distribution::T, and TpsSubstitution::variable.
substituteInto()
template<class T > VpsMap< T > VpsMap< T >::substituteInto (const Matrix< T > & x) const
Substitute.
Definition at line 371 of file VpsMap.h.
References Array2D< T >::ncols(), and Array2D< T >::nrows().
Referenced by operator*().
The documentation for this class was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algebra/Tps.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Algebra/VpsMap.h