OPAL (Object Oriented Parallel Accelerator Library): mslang::Translation Struct Reference
mslang::Translation Struct Reference
#include <Translation.h>
Public Member Functions
virtual ~Translation ()
virtual void print (int indentwidth)
void applyTranslation (std::vector< std::shared_ptr< Base > > &bfuncs)
virtual void apply (std::vector< std::shared_ptr< Base > > &bfuncs)
Public Member Functions inherited from mslang::Function
virtual ~Function ()
virtual void apply (std::vector< std::shared_ptr< Base >> &bfuncs)=0
Static Public Member Functions
static bool parse_detail (iterator &it, const iterator &end, Function *&fun)
Static Public Member Functions inherited from mslang::Function
static bool parse (iterator &it, const iterator &end, Function *&fun)
Public Attributes
Function * func_m
double shiftx_m
double shifty_m
Additional Inherited Members
Static Public Attributes inherited from mslang::Function
static const std::string UDouble = "([0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string Double = "(-?[0-9]+\\.?[0-9]*([Ee][+-]?[0-9]+)?)"
static const std::string UInt = "([0-9]+)"
static const std::string FCall = "([a-z_]*)\\((.*)"
Detailed Description
Definition at line 7 of file Translation.h.
Constructor & Destructor Documentation
~Translation()
virtual mslang::Translation::~Translation () inline virtual
Definition at line 12 of file Translation.h.
References func_m.
Member Function Documentation
apply()
void mslang::Translation::apply (std::vector< std::shared_ptr< Base > > & bfuncs) virtual
Definition at line 34 of file Translation.cpp.
References mslang::Function::apply(), applyTranslation(), and func_m.
applyTranslation()
void mslang::Translation::applyTranslation (std::vector< std::shared_ptr< Base > > & bfuncs)
Definition at line 20 of file Translation.cpp.
References shiftx_m, and shifty_m.
Referenced by apply().
parse_detail()
bool mslang::Translation::parse_detail (iterator & it, const iterator & end, Function *& fun) static
Definition at line 39 of file Translation.cpp.
References Physics::e, end(), endl(), func_m, mslang::ArgumentExtractor::get(), mslang::ArgumentExtractor::getLengthConsumed(), mslang::Function::parse(), mslang::parseMathExpression(), shiftx_m, and shifty_m.
Referenced by mslang::Function::parse().
print()
void mslang::Translation::print (int indentwidth) virtual
Implements mslang::Function.
Definition at line 10 of file Translation.cpp.
References endl(), func_m, mslang::Function::print(), shiftx_m, and shifty_m.
Member Data Documentation
func_m
Function* mslang::Translation::func_m
Definition at line 8 of file Translation.h.
Referenced by apply(), parse_detail(), print(), and ~Translation().
shiftx_m
double mslang::Translation::shiftx_m
Definition at line 9 of file Translation.h.
Referenced by applyTranslation(), parse_detail(), and print().
shifty_m
double mslang::Translation::shifty_m
Definition at line 10 of file Translation.h.
Referenced by applyTranslation(), parse_detail(), and print().
The documentation for this struct was generated from the following files:
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Translation.h
/psi/home/gsell/data/src/OPAL/src/src/Classic/Utilities/MSLang/Translation.cpp