OPAL (Object Oriented Parallel Accelerator Library): /psi/home/gsell/data/src/OPAL/src/src/Classic/FixedAlgebra/Taylor.hpp File Reference
Taylor.hpp File Reference
#include <functional>
#include <numeric>
#include <iomanip>
#include "FixedAlgebra/Taylor.h"
Functions
template<class T >
Taylor< T > operator+ (const Taylor< T > &lhs, const Taylor< T > &rhs)
Add.
template<class T >
Taylor< T > operator- (const Taylor< T > &lhs, const Taylor< T > &rhs)
Subtract.
template<class T >
Taylor< T > operator* (const Taylor< T > &lhs, double rhs)
Multiply by scalar.
template<class T >
Taylor< T > operator* (double lhs, const Taylor< T > &rhs)
Multiply by scalar.
template<class T >
Taylor< T > operator/ (const Taylor< T > &lhs, double rhs)
Divide by scalar.
template<class T >
Taylor< T > PoissonBracket (const Taylor< T > &lhs, const Taylor< T > &rhs)
Poisson bracket of two Taylor seriess.
template<class T >
std::ostream & operator<< (std::ostream &os, const Taylor< T > &series)
Output.
Function Documentation
operator*() [1/2]
template<class T > Taylor<T> operator* (const Taylor< T > & lhs, double rhs)
Multiply by scalar.
Definition at line 235 of file Taylor.hpp.
References Taylor< T >::begin(), Taylor< T >::end(), Taylor< T >::getOrder(), and Attrib::Legacy::Distribution::T.
operator*() [2/2]
template<class T > Taylor<T> operator* (double lhs, const Taylor< T > & rhs)
Multiply by scalar.
Definition at line 248 of file Taylor.hpp.
References Taylor< T >::begin(), Taylor< T >::end(), Taylor< T >::getOrder(), and Attrib::Legacy::Distribution::T.
operator+()
template<class T > Taylor<T> operator+ (const Taylor< T > & lhs, const Taylor< T > & rhs)
Add.
Definition at line 203 of file Taylor.hpp.
References Taylor< T >::begin(), Taylor< T >::end(), Taylor< T >::getOrder(), max(), and Attrib::Legacy::Distribution::T.
operator-()
template<class T > Taylor<T> operator- (const Taylor< T > & lhs, const Taylor< T > & rhs)
Subtract.
Definition at line 219 of file Taylor.hpp.
References Taylor< T >::begin(), Taylor< T >::end(), Taylor< T >::getOrder(), max(), and Attrib::Legacy::Distribution::T.
operator/()
template<class T > Taylor<T> operator/ (const Taylor< T > & lhs, double rhs)
Divide by scalar.
Definition at line 261 of file Taylor.hpp.
References Taylor< T >::begin(), Taylor< T >::end(), Taylor< T >::getOrder(), and Attrib::Legacy::Distribution::T.
operator<<()
template<class T > std::ostream& operator<< (std::ostream & os, const Taylor< T > & series)
Output.
Definition at line 290 of file Taylor.hpp.
References endl().
PoissonBracket()
template<class T > Taylor<T> PoissonBracket (const Taylor< T > & lhs, const Taylor< T > & rhs)
Poisson bracket of two Taylor seriess.
Definition at line 274 of file Taylor.hpp.
References Taylor< T >::getOrder().