OPAL (Object Oriented Parallel Accelerator Library): matheval::detail::math Namespace Reference
matheval::detail::math Namespace Reference
Functions
template<typename T >
T sgn (T x)
Sign function.
template<typename T >
T isnan (T x)
isnan function with adjusted return type
template<typename T >
T isinf (T x)
isinf function with adjusted return type
template<typename T >
T deg (T x)
Convert radians to degrees.
template<typename T >
T rad (T x)
Convert degrees to radians.
Function Documentation
deg()
template<typename T > T matheval::detail::math::deg (T x)
Convert radians to degrees.
Definition at line 74 of file matheval.hpp.
Referenced by matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_(), OpalDegrader::update(), DefaultVisitor::visitDegrader(), ParallelCyclotronTracker::visitDegrader(), and ParallelTTracker::visitDegrader().
isinf()
template<typename T > T matheval::detail::math::isinf (T x)
isinf function with adjusted return type
Definition at line 70 of file matheval.hpp.
Referenced by Bend2D::calcEngeFunction(), AmrParticleBase< PLayout >::domainMapping(), ParallelTTracker::dumpStats(), and matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
isnan()
template<typename T > T matheval::detail::math::isnan (T x)
isnan function with adjusted return type
Definition at line 66 of file matheval.hpp.
Referenced by Stepper< FieldFunction, Arguments... >::advance(), cmp_ulp_obsolete::almost_eq(), cmp_ulp::almost_eq(), Bend2D::calcEngeFunction(), AmrParticleBase< PLayout >::domainMapping(), ParallelTTracker::dumpStats(), RFCavity::getAutoPhaseEstimate(), and matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
rad()
template<typename T > T matheval::detail::math::rad (T x)
Convert degrees to radians.
Definition at line 78 of file matheval.hpp.
Referenced by Cyclotron::apply(), Vacuum::checkPressure(), Cyclotron::interpolate(), and matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().
sgn()
template<typename T > T matheval::detail::math::sgn (T x)
Sign function.
Missing function in the STL. This calculates the mathematical sign function.
\[ \mathop{\mathrm{sgn}}(x) = \begin{cases} 1 & x > 0 \\ 0 & x = 0 \\ -1 & x < 0 \\ \end{cases} \]
Parameters
[in] x number
Returns
the sign of x
Definition at line 62 of file matheval.hpp.
References Attrib::Legacy::Distribution::T.
Referenced by matheval::detail::grammar< real_t, Iterator >::ufunc_::ufunc_().