OPAL (Object Oriented Parallel Accelerator Library): ClassicException Class Reference
ClassicException Class Reference
The abstract base class for all exceptions in CLASSIC.
#include <ClassicException.h>
Public Member Functions
virtual const std::string & what () const
Return the message string for the exception.
virtual const std::string & where () const
Return the name of the method or function which detected the exception.
Protected Member Functions
ClassicException (const std::string &meth, const std::string &msg)
The usual constructor.
ClassicException (const ClassicException &)
virtual ~ClassicException ()
ClassicException ()
Protected Attributes
const std::string message
const std::string method
Detailed Description
The abstract base class for all exceptions in CLASSIC.
Definition at line 29 of file ClassicException.h.
Constructor & Destructor Documentation
ClassicException() [1/3]
ClassicException::ClassicException (const std::string & meth, const std::string & msg) protected
The usual constructor.
Definition at line 28 of file ClassicException.cpp.
ClassicException() [2/3]
ClassicException::ClassicException (const ClassicException & rhs) protected
Definition at line 33 of file ClassicException.cpp.
~ClassicException()
ClassicException::~ClassicException () protected virtual
Definition at line 38 of file ClassicException.cpp.
ClassicException() [3/3]
ClassicException::ClassicException () protected
Member Function Documentation
what()
const std::string & ClassicException::what () const virtual
Return the message string for the exception.
Definition at line 42 of file ClassicException.cpp.
References message.
Referenced by Expressions::SDeferred< T >::evaluate(), Expressions::ADeferred< T >::evaluate(), PySquarePolynomialMap::exact_solve(), PySquarePolynomialMap::least_squares(), opalMain(), OpalParser::readStatement(), OpalSimulation::run(), and OpalParser::run().
where()
const std::string & ClassicException::where () const virtual
Return the name of the method or function which detected the exception.
Definition at line 47 of file ClassicException.cpp.
References method.
Referenced by Expressions::SDeferred< T >::evaluate(), Expressions::ADeferred< T >::evaluate(), opalMain(), OpalSimulation::run(), and OpalParser::run().
Member Data Documentation
message
const std::string ClassicException::message protected
Definition at line 60 of file ClassicException.h.
Referenced by what().
method
const std::string ClassicException::method protected
Definition at line 61 of file ClassicException.h.
Referenced by where().
The documentation for this class was generated from the following files:
src/Classic/Utilities/ClassicException.h
src/Classic/Utilities/ClassicException.cpp