OPAL (Object Oriented Parallel Accelerator Library): Attributes Namespace Reference
Attributes Namespace Reference
A collection of routines to construct object Attributes and retrieve.
Classes
class Bool
Parser for attribute of type logical.
class BoolArray
Parser for an attribute of type logical array.
class Place
Parser for an attribute of type place reference.
class PredefinedString
Parser for an attribute of type string.
class Range
Parser for an attribute of type range definition.
class Real
Parser for an attribute of type real.
class RealArray
Parser for an attribute of type real array.
class Reference
Parser for an attribute of type attribute reference.
class String
Parser for an attribute of type string.
class StringArray
Parser for an attribute of type string array.
class TableRow
Parser for an attribute of type table row reference.
class TokenList
Parser for an attribute of type token list.
class TokenListArray
Parser for an attribute of type token list array.
class UpperCaseString
Parser for an attribute of type string.
class UpperCaseStringArray
Parser for an attribute of type string array.
Functions
Attribute makeBool (const std::string &name, const std::string &help)
Make logical attribute.
Attribute makeBool (const std::string &name, const std::string &help, bool initial)
Make logical attribute.
bool getBool (const Attribute &)
Return logical value.
void setBool (Attribute &, bool)
Set logical value.
Attribute makeBoolArray (const std::string &name, const std::string &help)
Create a logical array attribute.
std::vector< bool > getBoolArray (const Attribute &)
Get logical array value.
void setBoolArray (Attribute &, const std::vector< bool > &)
Set logical array value.
Attribute makePlace (const std::string &name, const std::string &help)
Create a place attribute.
PlaceRep getPlace (const Attribute &)
Get place value.
void setPlace (Attribute &, const PlaceRep &)
Set place value.
Attribute makeRange (const std::string &name, const std::string &help)
Create a range attribute.
RangeRep getRange (const Attribute &)
Get range value.
void setRange (Attribute &, const RangeRep &)
Set range value.
Attribute makeReal (const std::string &name, const std::string &help)
Make real attribute.
Attribute makeReal (const std::string &name, const std::string &help, double initial)
Make real attribute.
double getReal (const Attribute &attr)
Return real value.
void setReal (Attribute &attr, double val)
Set real value.
Attribute makeRealArray (const std::string &name, const std::string &help)
Create real array attribute.
std::vector< double > getRealArray (const Attribute &)
Get array value.
void setRealArray (Attribute &, const std::vector< double > &)
Set array value.
Attribute makeReference (const std::string &name, const std::string &help)
Create a reference attribute.
Attribute makeString (const std::string &name, const std::string &help)
Make string attribute.
Attribute makeString (const std::string &name, const std::string &help, const std::string &initial)
Make string attribute.
std::string getString (const Attribute &attr)
Get string value.
void setString (Attribute &attr, const std::string &val)
Set string value.
Attribute makePredefinedString (const std::string &name, const std::string &help, const std::initializer_list< std::string > &predefinedStrings)
Make predefined string attribute.
Attribute makePredefinedString (const std::string &name, const std::string &help, const std::initializer_list< std::string > &predefinedStrings, const std::string &initial)
Make predefined string attribute.
void setPredefinedString (Attribute &attr, const std::string &val)
Set predefined string value.
Attribute makeUpperCaseString (const std::string &name, const std::string &help)
Make uppercase string attribute.
Attribute makeUpperCaseString (const std::string &name, const std::string &help, const std::string &initial)
Make uppercase string attribute.
void setUpperCaseString (Attribute &attr, const std::string &val)
Set uppercase string value.
Attribute makeStringArray (const std::string &name, const std::string &help)
Create a string array attribute.
std::vector< std::string > getStringArray (const Attribute &)
Get string array value.
void setStringArray (Attribute &, const std::vector< std::string > &)
Set string array value.
Attribute makeUpperCaseStringArray (const std::string &name, const std::string &help)
Make uppercase string array attribute.
void setUpperCaseStringArray (Attribute &, const std::vector< std::string > &)
Set upper case string array value.
Attribute makeTableRow (const std::string &name, const std::string &help)
Create a table row attribute.
TableRowRep getTableRow (const Attribute &)
Get table row value.
void setTableRow (Attribute &, const TableRowRep &)
Set table row value.
Attribute makeTokenList (const std::string &name, const std::string &help)
Make token list attribute.
std::list< Token > getTokenList (const Attribute &attr)
Return token list value.
void setTokenList (Attribute &attr, const std::list< Token > &)
Set token list value.
Attribute makeTokenListArray (const std::string &name, const std::string &help)
Make token list attribute.
std::vector< std::list< Token > > getTokenListArray (const Attribute &attr)
Return token list array value.
void setTokenListArray (Attribute &attr, const std::vector< std::list< Token > > &)
Set token list array value.
Detailed Description
A collection of routines to construct object Attributes and retrieve.
Function Documentation
getBool()
bool Attributes::getBool (const Attribute & attr)
Return logical value.
Definition at line 100 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), and Attribute::isBaseAllocated().
Referenced by Distribution::checkIfEmitted(), Distribution::create(), Distribution::createDistributionMultiGauss(), Distribution::createMatchedGaussDistribution(), OptimizeCmd::execute(), Option::execute(), SampleCmd::execute(), IfStatement::execute(), WhileStatement::execute(), Distribution::generateAstraFlattopT(), Distribution::generateBinomial(), Distribution::generateFlattopLaserProfile(), Distribution::generateFlattopT(), Distribution::generateFlattopZ(), Distribution::generateGaussZ(), Distribution::generateLongFlattopT(), Distribution::generateMatchedGauss(), Distribution::generateTransverseGauss(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::getAttribute(), BoolConstant::getBool(), FieldSolver::initAmrSolver_m(), FieldSolver::initCartesianFields(), OpalSample::initialize(), ParticleMatterInteraction::initParticleMatterInteractionHandler(), OpalWake::initWakefunction(), List::list(), ParticleMatterInteraction::print(), FieldSolver::printInfo(), Distribution::printInfo(), Select::select(), Distribution::setDistParametersFlattop(), TrackRun::setupTTracker(), OpalSource::update(), OpalSolenoid::update(), OpalFlexibleCollimator::update(), OpalVacuum::update(), OpalTravelingWave::update(), OpalStripper::update(), OpalCavity::update(), OpalCyclotron::update(), OpalMultipoleT::update(), OpalRingDefinition::update(), OpalElement::update(), Distribution::writeOutFileEmission(), Distribution::writeOutFileHeader(), and Distribution::writeOutFileInjection().
getBoolArray()
std::vector< bool > Attributes::getBoolArray (const Attribute & attr)
Get logical array value.
Definition at line 141 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getName(), and Attribute::isBaseAllocated().
Referenced by OpalCyclotron::update().
getPlace()
PlaceRep Attributes::getPlace (const Attribute & attr)
Get place value.
Definition at line 178 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getName(), and Attribute::isBaseAllocated().
getRange()
RangeRep Attributes::getRange (const Attribute & attr)
Get range value.
Definition at line 212 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getName(), and Attribute::isBaseAllocated().
Referenced by Select::select().
getReal()
double Attributes::getReal (const Attribute & attr)
Return real value.
Definition at line 252 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), and Attribute::isBaseAllocated().
Referenced by Distribution::adjustPhaseSpace(), DumpFields::buildGrid(), DumpEMFields::buildGrid(), Distribution::checkEmissionParameters(), Distribution::createMatchedGaussDistribution(), Distribution::createOpalT(), OptimizeCmd::execute(), TrackCmd::execute(), SampleCmd::execute(), Option::execute(), TrackRun::execute(), SequenceParser::findNeighbourPositions(), Distribution::generateAstraFlattopT(), Distribution::generateLongFlattopT(), BoundaryGeometry::getA(), PyOpal::PyElementNS::PyElement< C >::getAttribute(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::getAttribute(), BoundaryGeometry::getB(), BoundaryGeometry::getC(), Beam::getCharge(), Beam::getCurrent(), TrackCmd::getDTAU(), TrackCmd::getDTSCINIT(), Distribution::getEmissionTimeShift(), Beam::getFrequency(), BoundaryGeometry::getL1(), BoundaryGeometry::getL2(), Line::getLength(), Sequence::getLength(), OpalElement::getLength(), BoundaryGeometry::getLength(), DVar::getLowerBound(), Beam::getMass(), FieldSolver::getMT(), FieldSolver::getMX(), FieldSolver::getMY(), OpalWake::getNumberOfBins(), Beam::getNumberOfParticles(), RealConstant::getReal(), RealVariable::getReal(), BoundaryGeometry::getS(), TrackCmd::getStepsPerTurn(), TrackCmd::getT0(), Distribution::getTEmission(), DVar::getUpperBound(), Distribution::getWeight(), TrackCmd::getZStart(), FieldSolver::initAmrObject_m(), FieldSolver::initAmrSolver_m(), OpalSample::initialize(), OpalFilter::initOpalFilter(), OpalTrimCoil::initOpalTrimCoil(), ParticleMatterInteraction::initParticleMatterInteractionHandler(), FieldSolver::initSolver(), OpalWake::initWakefunction(), OpalWake::print(), TrackRun::print(), OpalFilter::print(), ParticleMatterInteraction::print(), OpalTrimCoil::print(), Beam::print(), DumpFields::print(), DumpEMFields::print(), Distribution::printDistFlattop(), Distribution::printDistGauss(), Distribution::printEmissionModelAstra(), Distribution::printEmissionModelNone(), BoundaryGeometry::printInfo(), FieldSolver::printInfo(), OpalElement::printMultipoleStrength(), Distribution::scaleDistCoordinates(), Distribution::setDistParametersBinomial(), Distribution::setDistParametersFlattop(), Distribution::setDistParametersGauss(), Distribution::setDistParametersMultiGauss(), Distribution::setSigmaP_m(), Distribution::setSigmaR_m(), TrackRun::setupCyclotronTracker(), OpalScalingFFAMagnet::setupDefaultEndField(), Distribution::setupEmissionModelAstra(), Distribution::setupEmissionModelNone(), Distribution::setupEmissionModelNonEquil(), Distribution::setupParticleBins(), Distribution::shiftDistCoordinates(), OpalEnge::update(), OpalAsymmetricEnge::update(), OpalMonitor::update(), OpalSBend::update(), OpalRBend::update(), OpalSlit::update(), OpalDegrader::update(), OpalECollimator::update(), OpalHKicker::update(), OpalRCollimator::update(), OpalFlexibleCollimator::update(), OpalSolenoid::update(), OpalSeptum::update(), OpalProbe::update(), OpalVerticalFFAMagnet::update(), OpalPepperPot::update(), OpalCCollimator::update(), OpalRBend3D::update(), OpalSextupole::update(), OpalDrift::update(), OpalUndulator::update(), OpalOctupole::update(), OpalQuadrupole::update(), OpalVacuum::update(), OpalVKicker::update(), OpalTravelingWave::update(), OpalSBend3D::update(), OpalStripper::update(), OpalKicker::update(), OpalSplineTimeDependence::update(), OpalPolynomialTimeDependence::update(), OpalOffset::OpalGlobalCylindricalOffset::update(), OpalCavity::update(), OpalOffset::OpalLocalCylindricalOffset::update(), OpalOffset::OpalGlobalCartesianOffset::update(), OpalCyclotron::update(), OpalMultipoleTStraight::update(), OpalScalingFFAMagnet::update(), OpalVariableRFCavity::update(), OpalOffset::OpalLocalCartesianOffset::update(), OpalMultipoleTCurvedVarRadius::update(), OpalMultipoleTCurvedConstRadius::update(), OpalMultipoleT::update(), OpalRingDefinition::update(), OpalVariableRFCavityFringeField::update(), Beam::update(), OpalElement::update(), and OpalElement::updateUnknown().
getRealArray()
std::vector< double > Attributes::getRealArray (const Attribute & attr)
Get array value.
Definition at line 294 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), and Attribute::isBaseAllocated().
Referenced by OptimizeCmd::execute(), Value::execute(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::getAttribute(), TrackCmd::getDT(), TrackCmd::getMaxSteps(), RealVector::getRealComponent(), TrackCmd::getZStop(), FieldSolver::initAmrObject_m(), OpalTrimCoil::initOpalTrimCoil(), Distribution::injectBeam(), FieldSolver::printInfo(), OpalTrimCoil::printPolynom(), OptimizeCmd::run(), Distribution::setDistParametersBinomial(), Distribution::setDistParametersGauss(), OpalEnge::update(), OpalAsymmetricEnge::update(), OpalMultipole::update(), OpalUndulator::update(), OpalMultipoleTStraight::update(), OpalCyclotron::update(), OpalMultipoleT::update(), OpalMultipoleTCurvedVarRadius::update(), OpalMultipoleTCurvedConstRadius::update(), and OpalElement::update().
getString()
std::string Attributes::getString (const Attribute & attr)
Get string value.
Definition at line 343 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), and Attribute::isBaseAllocated().
Referenced by BoundaryGeometry::BoundaryGeometry(), DumpFields::buildGrid(), DumpEMFields::buildGrid(), Distribution::calcPartPerDist(), Distribution::chooseInputMomentumUnits(), Distribution::createDistributionFromFile(), Distribution::createMatchedGaussDistribution(), OptimizeCmd::execute(), TrackCmd::execute(), Help::execute(), Call::execute(), PSystem::execute(), System::execute(), Title::execute(), Echo::execute(), Select::execute(), SampleCmd::execute(), Option::execute(), List::execute(), SequenceParser::findNeighbourPositions(), OpalElement::getApert(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::getAttribute(), Constraint::getExpression(), Objective::getExpression(), BoundaryGeometry::getFilename(), ParticleMatterInteraction::getInteractionType(), Distribution::getNumberOfParticlesInFile(), OpalElement::getParticleMatterInteraction(), Beam::getParticleName(), Sequence::getReference(), StringConstant::getString(), FieldSolver::getTagging_m(), TrackCmd::getTimeIntegrator(), BoundaryGeometry::getTopology(), FieldSolver::getType(), OpalElement::getTypeName(), DVar::getVariable(), OpalSample::getVariable(), OpalElement::getWakeF(), FieldSolver::hasPeriodicZ(), FieldSolver::initAmrSolver_m(), FieldSolver::initCartesianFields(), OpalSample::initialize(), OpalFilter::initOpalFilter(), OpalTrimCoil::initOpalTrimCoil(), ParticleMatterInteraction::initParticleMatterInteractionHandler(), FieldSolver::initSolver(), OpalWake::initWakefunction(), Sequence::parse(), DumpEMFields::parseCoordinateSystem(), OpalFilter::print(), ParticleMatterInteraction::print(), OpalTrimCoil::print(), Beam::print(), DumpEMFields::print(), Distribution::printDistFromFile(), BoundaryGeometry::printInfo(), FieldSolver::printInfo(), OptimizeCmd::run(), Select::select(), TrackRun::setBoundaryGeometry(), Distribution::setDistParametersFlattop(), Distribution::setDistType(), TrackRun::setRunMethod(), TrackRun::setupCyclotronTracker(), Distribution::setupEmissionModel(), TrackRun::setupFieldsolver(), OpalScalingFFAMagnet::setupNamedEndField(), TrackRun::setupThickTracker(), TrackRun::setupTTracker(), OpalMonitor::update(), OpalRBend::update(), OpalSBend::update(), OpalSource::update(), OpalECollimator::update(), OpalDegrader::update(), OpalRCollimator::update(), OpalSlit::update(), OpalFlexibleCollimator::update(), OpalSolenoid::update(), OpalSeptum::update(), OpalProbe::update(), OpalPepperPot::update(), OpalCCollimator::update(), OpalRBend3D::update(), OpalUndulator::update(), OpalDrift::update(), OpalQuadrupole::update(), OpalVacuum::update(), OpalTravelingWave::update(), OpalSBend3D::update(), OpalStripper::update(), OpalCavity::update(), OpalCyclotron::update(), OpalVariableRFCavity::update(), and OpalVariableRFCavityFringeField::update().
getStringArray()
std::vector< std::string > Attributes::getStringArray (const Attribute & attr)
Get string array value.
Definition at line 478 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), OpalData::getInstance(), and Attribute::isBaseAllocated().
Referenced by OptimizeCmd::execute(), SampleCmd::execute(), OpalWake::initWakefunction(), Attributes::UpperCaseStringArray::parseComponent(), Attributes::StringArray::parseComponent(), TrackRun::setDistributionParallelT(), TrackRun::setupCyclotronTracker(), and OpalCyclotron::update().
getTableRow()
TableRowRep Attributes::getTableRow (const Attribute & attr)
Get table row value.
Definition at line 562 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getName(), and Attribute::isBaseAllocated().
getTokenList()
std::list< Token > Attributes::getTokenList (const Attribute & attr)
Return token list value.
Definition at line 597 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), and Attribute::isBaseAllocated().
getTokenListArray()
std::vector< std::list< Token > > Attributes::getTokenListArray (const Attribute & attr)
Return token list array value.
Definition at line 630 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), and Attribute::isBaseAllocated().
Referenced by List::list().
makeBool() [1/2]
Attribute Attributes::makeBool (const std::string & name, const std::string & help)
Make logical attribute.
Definition at line 90 of file Attributes.cpp.
References name.
Referenced by BoolConstant::BoolConstant(), WhileStatement::execute(), IfStatement::execute(), FieldSolver::FieldSolver(), List::List(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalCyclotron::OpalCyclotron(), OpalElement::OpalElement(), OpalFlexibleCollimator::OpalFlexibleCollimator(), OpalMultipoleT::OpalMultipoleT(), OpalRingDefinition::OpalRingDefinition(), OpalSample::OpalSample(), OpalSolenoid::OpalSolenoid(), OpalSource::OpalSource(), OpalStripper::OpalStripper(), OpalTravelingWave::OpalTravelingWave(), OpalVacuum::OpalVacuum(), OpalWake::OpalWake(), OptimizeCmd::OptimizeCmd(), Option::Option(), ParticleMatterInteraction::ParticleMatterInteraction(), SampleCmd::SampleCmd(), Select::Select(), Distribution::setAttributes(), and TrackRun::TrackRun().
makeBool() [2/2]
Attribute Attributes::makeBool (const std::string & name, const std::string & help, bool ini)
Make logical attribute.
Definition at line 95 of file Attributes.cpp.
References name.
makeBoolArray()
Attribute Attributes::makeBoolArray (const std::string & name, const std::string & help)
Create a logical array attribute.
Definition at line 136 of file Attributes.cpp.
References name.
Referenced by OpalCyclotron::OpalCyclotron().
makePlace()
Attribute Attributes::makePlace (const std::string & name, const std::string & help)
Create a place attribute.
Definition at line 172 of file Attributes.cpp.
References name.
makePredefinedString() [1/2]
Attribute Attributes::makePredefinedString (const std::string & name, const std::string & help, const std::initializer_list< std::string > & predefinedStrings)
Make predefined string attribute.
Definition at line 409 of file Attributes.cpp.
References name.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::DumpEMFields(), FieldSolver::FieldSolver(), OpalElement::OpalElement(), OpalFilter::OpalFilter(), OpalSample::OpalSample(), OpalTrimCoil::OpalTrimCoil(), OpalVacuum::OpalVacuum(), OpalWake::OpalWake(), OptimizeCmd::OptimizeCmd(), Option::Option(), ParticleMatterInteraction::ParticleMatterInteraction(), Distribution::setAttributes(), TrackCmd::TrackCmd(), and TrackRun::TrackRun().
makePredefinedString() [2/2]
Attribute Attributes::makePredefinedString (const std::string & name, const std::string & help, const std::initializer_list< std::string > & predefinedStrings, const std::string & initial)
Make predefined string attribute.
Definition at line 417 of file Attributes.cpp.
References name, and Util::toUpper().
makeRange()
Attribute Attributes::makeRange (const std::string & name, const std::string & help)
Create a range attribute.
Definition at line 206 of file Attributes.cpp.
References name.
Referenced by Select::Select().
makeReal() [1/2]
Attribute Attributes::makeReal (const std::string & name, const std::string & help)
Make real attribute.
Definition at line 240 of file Attributes.cpp.
References name.
Referenced by Beam::Beam(), BoundaryGeometry::BoundaryGeometry(), DumpEMFields::DumpEMFields(), DumpFields::DumpFields(), DVar::DVar(), FieldSolver::FieldSolver(), Line::Line(), OpalAsymmetricEnge::OpalAsymmetricEnge(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalCCollimator::OpalCCollimator(), OpalCyclotron::OpalCyclotron(), OpalDegrader::OpalDegrader(), OpalDrift::OpalDrift(), OpalECollimator::OpalECollimator(), OpalElement::OpalElement(), OpalEnge::OpalEnge(), OpalFilter::OpalFilter(), OpalOffset::OpalGlobalCartesianOffset::OpalGlobalCartesianOffset(), OpalOffset::OpalGlobalCylindricalOffset::OpalGlobalCylindricalOffset(), OpalHKicker::OpalHKicker(), OpalKicker::OpalKicker(), OpalOffset::OpalLocalCartesianOffset::OpalLocalCartesianOffset(), OpalOffset::OpalLocalCylindricalOffset::OpalLocalCylindricalOffset(), OpalMultipoleT::OpalMultipoleT(), OpalMultipoleTCurvedConstRadius::OpalMultipoleTCurvedConstRadius(), OpalMultipoleTCurvedVarRadius::OpalMultipoleTCurvedVarRadius(), OpalMultipoleTStraight::OpalMultipoleTStraight(), OpalOctupole::OpalOctupole(), OpalPepperPot::OpalPepperPot(), OpalPolynomialTimeDependence::OpalPolynomialTimeDependence(), OpalProbe::OpalProbe(), OpalQuadrupole::OpalQuadrupole(), OpalRBend3D::OpalRBend3D(), OpalRCollimator::OpalRCollimator(), OpalRingDefinition::OpalRingDefinition(), OpalSample::OpalSample(), OpalSBend3D::OpalSBend3D(), OpalScalingFFAMagnet::OpalScalingFFAMagnet(), OpalSeptum::OpalSeptum(), OpalSextupole::OpalSextupole(), OpalSlit::OpalSlit(), OpalSolenoid::OpalSolenoid(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalStripper::OpalStripper(), OpalTravelingWave::OpalTravelingWave(), OpalTrimCoil::OpalTrimCoil(), OpalUndulator::OpalUndulator(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVariableRFCavityFringeField::OpalVariableRFCavityFringeField(), OpalVerticalFFAMagnet::OpalVerticalFFAMagnet(), OpalVKicker::OpalVKicker(), OpalWake::OpalWake(), OptimizeCmd::OptimizeCmd(), Option::Option(), ParticleMatterInteraction::ParticleMatterInteraction(), RealConstant::RealConstant(), RealVariable::RealVariable(), SampleCmd::SampleCmd(), Sequence::Sequence(), Distribution::setAttributes(), TrackCmd::TrackCmd(), and TrackRun::TrackRun().
makeReal() [2/2]
Attribute Attributes::makeReal (const std::string & name, const std::string & help, double initial)
Make real attribute.
Definition at line 246 of file Attributes.cpp.
References name.
makeRealArray()
Attribute Attributes::makeRealArray (const std::string & name, const std::string & help)
Create real array attribute.
Definition at line 289 of file Attributes.cpp.
References name.
Referenced by BoundaryGeometry::BoundaryGeometry(), FieldSolver::FieldSolver(), Line::Line(), OpalAsymmetricEnge::OpalAsymmetricEnge(), OpalCyclotron::OpalCyclotron(), OpalElement::OpalElement(), OpalEnge::OpalEnge(), OpalMultipole::OpalMultipole(), OpalMultipoleT::OpalMultipoleT(), OpalMultipoleTCurvedConstRadius::OpalMultipoleTCurvedConstRadius(), OpalMultipoleTCurvedVarRadius::OpalMultipoleTCurvedVarRadius(), OpalMultipoleTStraight::OpalMultipoleTStraight(), OpalSplineTimeDependence::OpalSplineTimeDependence(), OpalTrimCoil::OpalTrimCoil(), OpalUndulator::OpalUndulator(), OptimizeCmd::OptimizeCmd(), RealVector::RealVector(), Distribution::setAttributes(), TrackCmd::TrackCmd(), and Value::Value().
makeReference()
Attribute Attributes::makeReference (const std::string & name, const std::string & help)
Create a reference attribute.
Definition at line 324 of file Attributes.cpp.
References name.
makeString() [1/2]
Attribute Attributes::makeString (const std::string & name, const std::string & help)
Make string attribute.
Definition at line 332 of file Attributes.cpp.
References name.
Referenced by BoundaryGeometry::BoundaryGeometry(), Call::Call(), Constraint::Constraint(), DumpEMFields::DumpEMFields(), DumpFields::DumpFields(), DVar::DVar(), Echo::Echo(), Help::Help(), Line::Line(), List::List(), Objective::Objective(), OpalBend::OpalBend(), OpalCavity::OpalCavity(), OpalCyclotron::OpalCyclotron(), OpalDrift::OpalDrift(), OpalElement::OpalElement(), OpalFlexibleCollimator::OpalFlexibleCollimator(), OpalRBend3D::OpalRBend3D(), OpalSample::OpalSample(), OpalSBend3D::OpalSBend3D(), OpalScalingFFAMagnet::OpalScalingFFAMagnet(), OpalSolenoid::OpalSolenoid(), OpalTravelingWave::OpalTravelingWave(), OpalUndulator::OpalUndulator(), OpalVacuum::OpalVacuum(), OpalVariableRFCavity::OpalVariableRFCavity(), OpalVariableRFCavityFringeField::OpalVariableRFCavityFringeField(), OpalWake::OpalWake(), OptimizeCmd::OptimizeCmd(), PSystem::PSystem(), SampleCmd::SampleCmd(), Select::Select(), Sequence::Sequence(), Distribution::setAttributes(), StringConstant::StringConstant(), System::System(), Title::Title(), TrackCmd::TrackCmd(), and TrackRun::TrackRun().
makeString() [2/2]
Attribute Attributes::makeString (const std::string & name, const std::string & help, const std::string & initial)
Make string attribute.
Definition at line 338 of file Attributes.cpp.
References name.
makeStringArray()
Attribute Attributes::makeStringArray (const std::string & name, const std::string & help)
Create a string array attribute.
Definition at line 473 of file Attributes.cpp.
References name.
Referenced by OpalCyclotron::OpalCyclotron(), OpalSource::OpalSource(), OpalWake::OpalWake(), OptimizeCmd::OptimizeCmd(), SampleCmd::SampleCmd(), and TrackRun::TrackRun().
makeTableRow()
Attribute Attributes::makeTableRow (const std::string & name, const std::string & help)
Create a table row attribute.
Definition at line 557 of file Attributes.cpp.
References name.
makeTokenList()
Attribute Attributes::makeTokenList (const std::string & name, const std::string & help)
Make token list attribute.
Definition at line 592 of file Attributes.cpp.
References name.
makeTokenListArray()
Attribute Attributes::makeTokenListArray (const std::string & name, const std::string & help)
Make token list attribute.
Definition at line 625 of file Attributes.cpp.
References name.
Referenced by List::List().
makeUpperCaseString() [1/2]
Attribute Attributes::makeUpperCaseString (const std::string & name, const std::string & help)
Make uppercase string attribute.
Definition at line 445 of file Attributes.cpp.
References name.
Referenced by FieldSolver::FieldSolver().
makeUpperCaseString() [2/2]
Attribute Attributes::makeUpperCaseString (const std::string & name, const std::string & help, const std::string & initial)
Make uppercase string attribute.
Definition at line 451 of file Attributes.cpp.
References name, and Util::toUpper().
makeUpperCaseStringArray()
Attribute Attributes::makeUpperCaseStringArray (const std::string & name, const std::string & help)
Make uppercase string array attribute.
Definition at line 536 of file Attributes.cpp.
References name.
Referenced by SampleCmd::SampleCmd().
setBool()
void Attributes::setBool (Attribute & attr, bool val)
Set logical value.
Definition at line 119 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), Attribute::isBaseAllocated(), Hypervolume::ref, Expressions::SRefAttr< T >::set(), and Attribute::set().
Referenced by Option::Option(), and PyOpal::PyOpalObjectNS::PyOpalObject< C >::setAttribute().
setBoolArray()
void Attributes::setBoolArray (Attribute & attr, const std::vector< bool > & value)
Set logical array value.
Definition at line 157 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
setPlace()
void Attributes::setPlace (Attribute & attr, const PlaceRep & rep)
Set place value.
Definition at line 193 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
setPredefinedString()
void Attributes::setPredefinedString (Attribute & attr, const std::string & val)
Set predefined string value.
Definition at line 426 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), Attribute::isBaseAllocated(), Hypervolume::ref, Expressions::SRefAttr< T >::set(), Attribute::set(), and Util::toUpper().
Referenced by Option::Option(), and Attributes::PredefinedString::parse().
setRange()
void Attributes::setRange (Attribute & attr, const RangeRep & rep)
Set range value.
Definition at line 227 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
setReal()
void Attributes::setReal (Attribute & attr, double val)
Set real value.
Definition at line 271 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), Attribute::isBaseAllocated(), Hypervolume::ref, Expressions::SRefAttr< T >::set(), and Attribute::set().
Referenced by Option::Option(), RealConstant::RealConstant(), RealVariable::RealVariable(), PyOpal::PyElementNS::PyElement< C >::setAttribute(), PyOpal::PyOpalObjectNS::PyOpalObject< C >::setAttribute(), FieldSolver::setMT(), FieldSolver::setMX(), FieldSolver::setMY(), and Beam::update().
setRealArray()
void Attributes::setRealArray (Attribute & attr, const std::vector< double > & value)
Set array value.
Definition at line 309 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
Referenced by FieldSolver::FieldSolver(), and PyOpal::PyOpalObjectNS::PyOpalObject< C >::setAttribute().
setString()
void Attributes::setString (Attribute & attr, const std::string & val)
Set string value.
Definition at line 391 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), Attribute::isBaseAllocated(), Hypervolume::ref, Expressions::SRefAttr< T >::set(), and Attribute::set().
Referenced by PyOpal::PyOpalObjectNS::PyOpalObject< C >::setAttribute(), and StringConstant::StringConstant().
setStringArray()
void Attributes::setStringArray (Attribute & attr, const std::vector< std::string > & value)
Set string array value.
Definition at line 524 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
Referenced by Attributes::StringArray::parse().
setTableRow()
void Attributes::setTableRow (Attribute & attr, const TableRowRep & rep)
Set table row value.
Definition at line 578 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
setTokenList()
void Attributes::setTokenList (Attribute & attr, const std::list< Token > & val)
Set token list value.
Definition at line 612 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), and Attribute::set().
setTokenListArray()
void Attributes::setTokenListArray (Attribute & attr, const std::vector< std::list< Token > > & value)
Set token list array value.
Definition at line 646 of file Attributes.cpp.
References Attribute::set().
Referenced by Attributes::TokenListArray::parse().
setUpperCaseString()
void Attributes::setUpperCaseString (Attribute & attr, const std::string & val)
Set uppercase string value.
Definition at line 456 of file Attributes.cpp.
References Attribute::getBase(), Attribute::getHandler(), Attribute::getName(), Attribute::isBaseAllocated(), Hypervolume::ref, Expressions::SRefAttr< T >::set(), Attribute::set(), and Util::toUpper().
Referenced by Attributes::UpperCaseString::parse().
setUpperCaseStringArray()
void Attributes::setUpperCaseStringArray (Attribute & attr, const std::vector< std::string > & value)
Set upper case string array value.
Definition at line 540 of file Attributes.cpp.
References Attribute::getHandler(), Attribute::getName(), Attribute::set(), and Util::toUpper().
Referenced by Attributes::UpperCaseStringArray::parse().